### ISSUE TITLE
"Maximize panel" button is no longer visible

### ISSUE THREAD

**Issue by benknight** [microsoft/vscode#147094]
![image](https://user-images.githubusercontent.com/786691/162473417-52832209-f12c-4720-9051-fceb2a264eec.png)

Issue Type: <b>Bug</b>

1. Open panel
2. Observe that "maximize panel" (the icon that looks like a chevron pointing up) is missing, but it used to be there.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:52.288Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No
Connection to 'SSH: nc-aftermarket-api' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 1d902cdb-955d-4b36-8c23-78ec5bf89ade|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: nc-aftermarket-api' could not be established  Canceled
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
gitstash|art|5.1.0
vscode-log-viewer|ber|0.12.2
vscode-tailwindcss|bra|0.7.7
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.5
prettier-vscode|esb|9.5.0
vscode-graphql|Gra|0.4.1
vscode-test-explorer|hbe|2.21.1
zentabs|hit|0.0.7
prettify-json|moh|0.0.3
vscode-docker|ms-|1.21.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.5
vetur|oct|0.35.0
vscode-thunder-client|ran|1.14.4
rust|rus|0.7.8
vscode-fileutils|sle|3.5.0
alphabetical-sorter|ue|2.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment]
What is you panel alignment? Maximize is only available for Center

Also see #141094

**Comment by benknight** [comment]
I had my panel alignment set to "right". I set it to "center" and the maximize button reappeared, but the panel looks exactly the same in "right" and "center" alignment so I don't understand the difference. Anyway thanks!

**Comment by IllusionMH** [comment]
Panel Alignment controls "composition" with Primary/Secondary Side Bars.

Then I assume that you have Primary Side Bar (Explorer etc.) on the left you can check difference if you set panel alignment to Left. In your case (and with alignment Right) you would see difference if you show Secondary Side bar.

Please close this issue if there are no other expected action items.

**Comment by benknight** [comment]
Sure, I'll just mention this subtlety might be lost on a good number of users. I consider myself pretty tech fluent and I spent over a month trying to fix this on my own to no luck. This might be one of those features where less is more, but thanks for the quick support!
