### ISSUE TITLE
Update Always asking to Update to v1.66.1

### ISSUE THREAD

**Issue by prasoon-ctctipl** [microsoft/vscode#147131]
We have written the needed data into your clipboard because it was too large to sen
Issue Type: <b>Bug</b>

After the last update when ever the VS Code is opened It is asking for Updating to 1.66.1 Version

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (9.52GB free)|
|Process Argv|--crash-reporter-id fb4f029e-fedc-436b-a7dc-2544565fb788|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>
Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-django|bat|1.10.0
pico-go|Chr|1.4.3
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
python-extension-pack|don|1.7.0
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
vscode-pull-request-github|Git|0.38.1
CppSnippets|har|0.0.15
better-cpp-syntax|jef|1.15.13
vscode-circuitpython|joe|0.1.16
MagicPython|mag|1.1.0
cortex-debug|mar|1.4.4
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.2.1030672458
remote-containers|ms-|0.231.4
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.64.2
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
notepadplusplus-keybindings|ms-|1.0.7
vscode-typescript-tslint-plugin|ms-|1.3.4
platformio-ide|pla|2.4.3
java|red|1.4.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.0.10
vscodeintellicode|Vis|1.2.18
vscode-arduino|vsc|0.4.11
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vscode-icons|vsc|11.10.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
vscaac:30438847
pynewfile477:30463512

```

</details>

d. Please paste.

**Comment by prasoon-ctctipl** [comment]
![2 ](https://user-images.githubusercontent.com/63372454/162560396-37bb1625-1525-4958-8cb6-753e2549d2b1.PNG)
![3 Again asking after update](https://user-images.githubusercontent.com/63372454/162560397-c0721397-1def-4c03-b282-e89aa9cd8309.PNG)
![1 start up](https://user-images.githubusercontent.com/63372454/162560398-7b27d1cc-881c-4528-a511-b4002fb1856d.PNG)

**Comment by prasoon-ctctipl** [comment]
![1 start up](https://user-images.githubusercontent.com/63372454/162560417-deabf6ab-8cc4-499d-a03b-6c8bbef57c24.PNG)
![2 Updating ](https://user-images.githubusercontent.com/63372454/162560436-59feb766-a21d-4668-b994-91c6ff7fd5ad.PNG)
![3 Again asking after update](https://user-images.githubusercontent.com/63372454/162560437-4383a96c-323f-4883-b193-db2e85f142ae.PNG)

**Comment by Lemmingh** [comment]
/needsMoreInfo

What's the value of your `update.mode` setting? Do you have Settings Sync enabled and encounter unexpected change in settings?

**Comment by joaomoreno** [comment]
Are you using the system or uset setup?
