### ISSUE TITLE
Terminal text size doesn't change despite settings

### ISSUE THREAD

**Issue by cyrusae** [microsoft/vscode#147124]
Issue Type: <b>Bug</b>

I use VSC on both Mac and Windows; on Windows, the Terminal text size appears to change in relation to my settings, but on Mac it does not. This makes Terminal on Mac too small to read. 

The fact that this doesn't happen on Windows leads me to assume it is a bug on Mac; I apologize if this assumption is incorrect and the problem is something else.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|--crash-reporter-id 520a8566-3043-4966-a445-d857623cf57b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-babel|mgm|0.0.36
prisma|Pri|3.12.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
sass-indented|syl|1.8.19

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

> VS Code version: Code 1.63.2

Is old version. Please check if it's reproducible in latest stable version 1.66.1
https://code.visualstudio.com/Download
