### ISSUE TITLE
Saving custom editor proposes wrong file extension

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#147110]
Originally reported by @pomdtr https://github.com/excalidraw/excalidraw-vscode/pull/23#issuecomment-1093246970

> I think the language detection feature of vscode is playing against us here. If I hit save on the new untitled excalidraw file, the extension propose to save it as Excalidraw-1.excalidraw.json instead of Excalidraw-1.excalidraw
> I would prefer it we could avoid this. Do you have an idea how to disable this behoviour ?

> I just looked at the tldraw extension, and it looks like it has the same issue.

**Comment by rebornix** [comment]
As long as we modify the custom editor and it saves content into the document, we will use `json` as file extension. This is probably because the underlining content for the custom document is JSON. However we should not attempt to append `json` file extension to custom document (we would need to disable the language detection in this case).

**Comment by mjbvz** [comment]
Related  #124423

**Comment by lramos15** [comment]
@rebornix Is this still an issue. I see that if we have a jupyter notebook for example that is JSON underneath then we don't improperly save it. Ben just pushed a fix recently for some wonky file path appending happening so maybe this also fixed that.

**Comment by lramos15** [comment]
Closing as I believe this has been fixed by some other save changes
