### ISSUE TITLE
Adds "return" for breadcrumbs 

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#147167]
I believe we need a support for the "return" properties for the breadcrumbs on vscode. 

For example, in the below JavaScript (React) script: 

```js

class Content extends Component {

    constructor(props) {
        super(props);
    }

    componentDidMount() {

    }
    
    render() {
        const Loading = () => {

        }
        return (
            <div>
            </div>
        )
    }
}
```

The breadcrumbs shows: 

```
Content 
-- constructor
-- componentDidMount
-- render
---- Loading 
```

But it would be nicer to be like, I think: 

```
Content 
-- constructor
-- componentDidMount
-- render
---- Loading 
---- return 
```

In the default options JSON file there are many breadcrumbs options like the below, so adding "return" there to enable users choose true or false for the return to be shown the breadcrumbs is a good idea I think. 

```
// When enabled breadcrumbs show `variable`-symbols.
"breadcrumbs.showVariables": true,
```

Thanks.

**Comment by mjbvz** [comment]
I don't feel this request fits with how we think about breadcrumbs

We use breadcrumbs to show declarations, such as variables and classes. They aren't meant to show the structure of your code, such as `if` or `return` statements
