### ISSUE TITLE
Cannot update configuration from main process

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147160]
This caught by me by surprise: 

https://github.com/microsoft/vscode/blob/4ee3ed1ff239dd9b51cd07ed8a35e29ca9d441c2/src/vs/platform/configuration/common/configurationService.ts#L60-L66

**Comment by sandy081** [comment]
This is never supported in main/shared process. One hurdle to support is that we do not know the formatting options of the settings file in this process.

**Comment by bpasero** [comment]
@sandy081 not super critical, but the new confirmation dialog on quit offers a checkbox to "Do not ask again" and this writes a setting. In one case the command is coming from the main process, mainly when the native menu appears (e.g. on macOS).

**Comment by sandy081** [comment]
This is supported now - https://github.com/microsoft/vscode/issues/195436

**Comment by TylerLeonhardt** [comment]
Added:
```
configurationService.updateValue('window.autoDetectColorScheme', false).then(() => {
			console.log('asdf');
		});
```
Here:
https://github.com/microsoft/vscode/blob/ed6c2eca2d09587ff2470fc397ccf2414e7609d7/src/vs/platform/encryption/electron-main/encryptionMainService.ts#L29

and it worked 👍
