### ISSUE TITLE
everything got deleted

### ISSUE THREAD

**Issue by TeutaM16** [microsoft/vscode#147172]
Issue Type: <b>Performance Issue</b>

when i wanted to open my project wich i  worked on for a very long time it just wasn't there. it got erased and i didn't do anything to it. i only have a smal file now wich contained almost nothing and the file i worked on the most go deleted aswell and i tryed restarting my computer, running a debug and still nothing worked. i want my hard work back. thank you

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (4.62GB free)|
|Process Argv|--crash-reporter-id 933ff4cf-fb89-4909-a92b-54442cfa88a3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    93	  8576	code main
    0	    38	  2980	   utility-network-service
    2	    81	  3884	   issue-reporter
    1	   130	  7472	   gpu-process
    0	   151	  8596	   window (contact.css - website - Visual Studio Code)
    0	   102	  8948	   extensionHost
    0	    77	 11380	     "C:\Users\Iulian\Desktop\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Iulian\Desktop\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8948
    0	    76	 12388	     "C:\Users\Iulian\Desktop\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Iulian\Desktop\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=8948
    0	    26	 11408	   crashpad-handler
    0	    95	 12236	   shared-process
    0	    74	  1552	     ptyHost
    0	    76	  7240	     fileWatcher
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (contact.css - website - Visual Studio Code)
|    Folder (website): 4 files
|      File types: json(1) css(1)
|      Conf files: launch.json(1)
|      Launch Configs: pwa-chrome;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflight:30433670
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment]
What was the exact path of the folder where you wrote your code?
