### ISSUE TITLE
Hangs when try save

### ISSUE THREAD

**Issue by vinay-kotian** [microsoft/vscode#147159]
Open Vi Studio. 
New File.
Click on Save. (Error Pops Up after some time) Force Quit or Wait

**Comment by watersne** [comment]
I am having the same problem.

```
$ code --version
1.66.2
dfd34e8260c270da74b5c2d86d61aee4b6d56977
x64


$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

It occurs when I try to use FIle -> Open Folder or File -> Save As. Basically anything that results in opening a file explorer window.

![image](https://user-images.githubusercontent.com/9658254/164781867-e2f5b979-4002-42e4-92d9-444198fd1c14.png)
