### ISSUE TITLE
Cannot see local/uncommited changes in Timeline anymore after March 30 2022 update

### ISSUE THREAD

**Issue by am9417** [microsoft/vscode#147199]
I have added one line into a python file and saved the file.

After saving a file, previously (prior to update in late March 2022?) Visual Studio Code created an "Uncommitted changes" item in the Timeline view (by default in the sidebar in the left). Clicking the item opened a view where the uncommitted changes could be compared. Currently such item is not created, but instead, a "File Saved" item is created which doesn't seem to show the changes properly.

(Looks like, in the current version of VSCode, a view similar to the previous "Uncommitted changes" can be still displayed with by navigating to Source Control and clicking the file in Source Control View, under the list of changed files.)

Image 1: The view previously opened after clicking "Uncommitted changes" item in the timeline.
![One uncommitted line added to a Python function](https://user-images.githubusercontent.com/10899115/162680775-47231891-b236-49ad-8f0f-b642474900b8.png)

However, this view cannot be displayed in the timeline anymore. Instead, a "File Saved" item is created in the Timeline (image 2) but clicking it does not reveal any changes (image 3):

Image 2: File Saved Pipeline
![Timeline: file saved](https://user-images.githubusercontent.com/10899115/162682239-8bf21532-8b64-45b9-8f51-2e392b337e41.png)

Image 3: Clicking the item opens a compare view. No changes highlighted.
![Changes but not changes](https://user-images.githubusercontent.com/10899115/162682479-dea04b64-ac39-42f2-995b-c28c9121d720.png)

I was expecting to see that one new line highlighted, similarly as in Image 1. Instead no changes are highlighted. However, the file name in the tab is yellow, so there are uncommitted changes.

Looking more into it, looks like clicking the "local changes" items in the timeline (such as File Saved and Undo/Redo) don't open a compare view that displays the changes done in *that particular point*, but compare the then version of the file with the *current version of the file*. So, I'm not sure if this is a bug or a feature, but it's not following the expected pattern in the timeline, where clicking a commit shows the changes introduced in that particular commit.

About VSCode:
>Version: 1.66.0 (system setup)
>Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
>Date: 2022-03-30T05:50:14.623Z
>Electron: 17.2.0
>Chromium: 98.0.4758.109
>Node.js: 16.13.0
>V8: 9.8.177.11-electron.0
>OS: Windows_NT x64 10.0.22000

**Comment by bpasero** [comment]
Intentional: https://github.com/microsoft/vscode/issues/145723
