### ISSUE TITLE
Can not install an extension using the command line

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#147103]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.0-insider (user setup)
Commit: 6ea335e334b90a9aca753d558dec1d14741eff1e
Date: 2022-04-08T07:13:56.078Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. code-insiders --install-extension ms-python.python

It fails and prints this:
Cannot read properties of undefined (reading 'userExtensionsLocation')

**Comment by Emilgardis** [comment]
also experiencing this installing self-built https://github.com/rust-analyzer/rust-analyzer via `code-insiders.cmd --install-extension rust-analyzer.vsix --force` on windows 11

```
1.67.0-insider
6ea335e334b90a9aca753d558dec1d14741eff1e
x64
```

**Comment by aeschli** [comment]
Same problem with `code-insiders --locate-extension  ms-vscode-remote.remote-wsl`

This causes https://github.com/microsoft/vscode-remote-release/issues/6593

**Comment by aeschli** [comment]
At https://github.com/microsoft/vscode/blob/main/src/vs/platform/extensionManagement/node/extensionsScanner.ts#L40, extensionsScannerService is undefined.
I guess cliProcessMain also needs to set a `IExtensionsScannerService`

**Comment by DonJayamanne** [comment]
Re-opening thi sissue, as we're still running into this on CI servers.
https://github.com/microsoft/vscode-jupyter/runs/6072274354?check_suite_focus=true

@sandy081 please let me know when you need (the logs are attached above).

**Comment by rchiodo** [comment]
@DonJayamanne  I don't think it's the same issue? 

This is what we're getting now:

```
Installing Python Extension ms-python.python
Installing extensions...
Server returned 503
```

The original error was this:

```
Cannot read properties of undefined (reading 'userExtensionsLocation')
```
