### ISSUE TITLE
Pull changes from Github causes bug in AL code

### ISSUE THREAD

**Issue by ShammyLevva** [microsoft/vscode#147111]
Issue Type: <b>Bug</b>

1. Create an extension in AL code 
2. in app.json file set the ID ranges eg: 60000 to 60001
3. commit changes to github
4. on second users machine clone repository and add extra object giving it ID 600002
5. update app.json to set the ID ranges to 60000 to 60002
6. this all works so far on 2nd machine - now commit changes
7. on original machine use pull command to pull down changes 2nd user made. 
8. Note that even though it correctly pulls down the app.json file and that the app.json file is now updated to show object ID ranges as 60000 to 60002 the new object created with the ID 60002 shows an error that it's ID is outside acceptable range.

To fix:
Close application and open again. It now loads the code fresh and all is well. So the act of pulling down the code is failing to refresh something about reading the ranges in app.json and causing it to reject the new ID as valid. 

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900K (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (46.34GB free)|
|Process Argv|--crash-reporter-id f214c9ac-07b8-4d58-9e0d-444dc0ac131a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.11.0
csharp|ms-|1.24.3
al|ms-|9.0.605172
powershell|ms-|2021.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by ShammyLevva** [comment]
I forgot to mention in case it's relevant this was creating code for Microsoft Dynamics 365 Business Central Cloud service. To follow the steps above you can use Microsoft AL language extension then the AL Go command to create a test extension. The issue only seems to appear when you are pulling code from GitHub onto a 2nd machine. 

I'm not sure if bug is in VS Code or the AL Language extension.

**Comment by lszomoru** [comment]
> Note that even though it correctly pulls down the app.json file and that the app.json file is now updated to show object ID ranges as 60000 to 60002 the new object created with the ID 60002 shows an error that it's ID is outside acceptable range

This observation hints towards a possible issue with the Microsoft AL Language extension. Could you please file an issue [in this repository](https://github.com/Microsoft/AL/issues) and have the team owning the extension investigate first. Thank you very much!
