### ISSUE TITLE
Add option to switch compared files (right and left side)

### ISSUE THREAD

**Issue by ericmp33** [microsoft/vscode#147138]
When I compare 2 files in VSC, sometimes I mess it a little. Let's say I only have 2 files, I first choose the wrong file, so that makes that the file I want to be compared is the one on the left part of the screen, and the other one on the right side. But I actually wanted it the other way, the file on the left, on the right side, and the file on the right, on the left side. Argh, annoying.

So what do I do now? I close the comparison and I start over again, but thinking of the order or files that I have to choose. First, the file I want to be on the left side of comparison, then the other one.

I'd like to see an option in the comparison tab where it says "switch files" or something related, so I click it and the file on the left moves to the right, and the file on the right moves to the left. So I don't have to start all over again and choose the right order of files to be compared.

Anyway, this is not only because of a mistake when setting up the comparison. Maybe someone wants to compare the file being on the left side of the comparison, but, for any reason, later on wants it to in the other side of the comparison. So will be also be useful in that aspect. The user will just press "switch" option, and files will switch from left to right and from right to left, without having to set up a new comparison but in different order.

Image with a simulation of the new functionality button:
![new-functionality-image-example](https://user-images.githubusercontent.com/60661635/162569126-5105dfe2-15a5-44d2-be0c-507d33c2366f.png)

**Comment by JacksonKearl** [comment]
cc @lramos15 maybe a contender for new tabs API?
