### ISSUE TITLE
Add option to prevent same file opening twice

### ISSUE THREAD

**Issue by basickarl** [Microsoft/vscode#14718]
Sometimes I've forgotten that I have opened the same file twice in two or more panes in vscode. This has led me to edit the wrong file opened which in turn creates confusion as to why my code isn't working as intended.

I'm wondering, could an option be added to prevent the same file being opened more than once. If it is opened in a new pane, let the other opened version close (do you want to save edits etc.).

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.
