### ISSUE TITLE
Launch configuration - preLaunchTask - Could not find the task

### ISSUE THREAD

**Issue by aesweeting** [microsoft/vscode#147193]
Issue Type: <b>Bug</b>

We have a `preLaunchTask` to build our project and then start our backend application, which has worked for the last couple of years.

However, when we try to start the debugger, we get the message:

> Could not find the task 'myproject:build'.

The task is `"type": "npm"`, and removing any colon's etc from the task's label doesn't resolve the issue.

Tasks:

```json
    {
      "label": "myproject:build",
      "type": "npm",
      "script": "build",
      "path": "projects/myproject/",
      "group": "build",
      "problemMatcher": ["$tsc"],
      "detail": "tsc",
      "presentation": {
        "reveal": "silent",
        "group": "build",
        "close": true
      }
    },
```

Launch configuration:

```json
    {
      "type": "node",
      "request": "launch",
      "name": "server:myproject",
      "cwd": "${workspaceRoot}/projects/myproject",
      "program": "${workspaceRoot}/projects/myproject/dist/server.js",
      "preLaunchTask": "myproject:build",
      "outputCapture": "std",
      "skipFiles": ["<node_internals>/**"]
    },
```

Both myself and a colleague are using VS Code Insiders and started experiencing this issue mid last week.

It can also be replicated without any extensions enabled.

VS Code version: Code - Insiders 1.67.0-insider (Universal) (6ea335e334b90a9aca753d558dec1d14741eff1e, 2022-04-08T05:18:35.034Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|15, 15, 15|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id 1996d2d1-7ae0-4989-a453-8d3d6ec023ea|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebug:30466689
pynewfile477:30451556

```

</details>

**Comment by aesweeting** [comment]
This might be related to #147106?

**Comment by aesweeting** [comment]
Additionally, I _can_ see the build task in the list when I run `Tasks > Run Task`.

However, upon selecting I don't receive an error and I don't see the task start in VS Code or in a watched process status output via `watch --interval 0.1 "ps | grep -i build"`.

**Comment by aesweeting** [comment]
Thanks for the quick turnaround, we didn't even think to check that as it has worked for so long.

Confirming that dropping the trailing slash works with our existing insiders build as well.
Thanks for resolving the BC issue too!

**Comment by aesweeting** [comment]
Is there going to the a March Recovery 3 release?

- Insiders now supports both with and without the trailing slash.
- We updated to remove the trailing slash, as it was noted as incorrect.
- Current stable release, without the trailing slash, incorrectly runs the task at the project root.

The same as the linked commit above from @SPGoding, we're probably going to revert back to the "incorrect" trailing slash again.

**Comment by alexr00** [comment]
There is no March recovery 3 planned as we haven't found enough issues for one and 1.67 should happen in approximately the next week and a half. Reverting the incorrect trailing slash in your project makes sense as it works in both insiders and stable.
