### ISSUE TITLE
grid-template-areas shows errors after css reformat

### ISSUE THREAD

**Issue by Moosemorals** [microsoft/vscode#147155]
Issue Type: <b>Bug</b>

1. Create a blank .css file
2. Add minimal example
```
body {
  grid-template-areas: "a" "b";
}
```
3. Format document
4. File now looks like:
```
body {
  grid-template-areas: "a""b";
}
```
with "b" wavy underlined ("semi-colon-expected") and the close brace wavy underlined "at-ule or selecter expected".

Based on my reading ofhttps://www.w3.org/TR/css-values-4/#component-whitespace I think the correct behaviour would be for the reformat to leave the space between "a" and "b", although at least Firefox v99 doesn't seem to care.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (8.40GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bdebian/home/osric/Projects/uk.co.aaru/OsricUK --crash-reporter-id c5b73b99-246e-42dd-bc51-63feb923970a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2591)|
|Memory (System)|12.37GB (11.27GB free)|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying CSS formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?

The issue looks very similar to https://github.com/beautify-web/js-beautify/issues/2024 which will have a fix in the next release of jsbeautify
