### ISSUE TITLE
Settings sync logs out every time VSC starts

### ISSUE THREAD

**Issue by cyrusae** [microsoft/vscode#147123]
Issue Type: <b>Bug</b>

I have a laptop and a desktop with VSC installed on both. Every time I start VSC, I log in with GitHub in order to sync settings. This login literally never persists between sessions, including if I close it and then open it five minutes later, which defeats much of the point and means that among the settings that refuse to sync are accessibility-related display settings. (e.g. text size resets on restart.)

I have no idea what settings *are* supposed to sync in the first place because I don't think it's done so successfully at any point, so for all I know the logging in also doesn't work; I would think that it wouldn't treat me as a new user on launch every time, for example, and that I shouldn't have to re-apply my preferences for saving, font size, indent size, etc.

Clicking the option to sign in via GitHub opens the window to generate a token to send to VSC as usual and VSC claims to be logged in thereafter until closed.

If this behavior is intentional, it defeats the point of the option for me; I assume it is not intentional.

I apologize if I have made any errors in reporting this. Thank you.

VS Code version: Code 1.63.2 (Universal) (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:37:28.172Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 520a8566-3043-4966-a445-d857623cf57b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-babel|mgm|0.0.36
prisma|Pri|3.12.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
sass-indented|syl|1.8.19

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30429731
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Same note as neighbor issue - Please check if it's reproducible in latest stable version
https://code.visualstudio.com/Download

**Comment by Wombosvideo** [comment]
For me it's not exactly *every time VSC starts* but rather every 2-5 days, randomly. Logging in then also doesn't work most of the time, as if VSC failed to receive the token.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-40-generic snap
Restricted Mode: No

**Comment by sandy081** [comment]
@cyrusae Please try with latest version and see if you can reproduce it and reopen the issue
