### ISSUE TITLE
Microsoft extension on the vscode website will be great

### ISSUE THREAD

**Issue by ivannp** [microsoft/vscode#147150]
Thanks for the exceptional product!

Firewalls at companies seem to allow vscode upgrades, but not the marketplace. A good number of best extensions are from Microsoft - can you host them together with vscode? This way allowing content from the vscode channel will allow access to best extensions for companies with stricter firewall policies.

Thanks!

**Comment by isidorn** [comment]
I suggest to add the common hostnames VS Code uses to the allow list of your firewalls https://code.visualstudio.com/docs/setup/network#_common-hostnames

We do not plan to host some extensions on our website, as that would be duplicating the Marketplace work. Thus closing as out of scope.
