### ISSUE TITLE
External terminal fails to open

### ISSUE THREAD

**Issue by chtenb** [microsoft/vscode#147102]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.0-insider (system setup)
Commit: 909602cf04e0fa42528d692676d0d4e15e67bba2
Date: 2022-03-31T11:00:49.798Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Type ctrl-shift-p en select "Open new external terminal"
2. Nothing happens

I scrolled through the logfiles but nothing strange shows up. I don't use this feature often, but this has worked in the past. I've tried several different options for `terminal.external.windowsExec` including not defining it at all. (Though if something is wrong with that setting I'd expect an error message at least).

**Comment by meganrogge** [comment]
can you provide me with your settings.json file and any errors in the dev tools console? it's working for me

**Comment by chtenb** [comment]
My settings.json is `{ }`. Here is a screenshot that includes the dev tools:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/1030961/163317278-8b6e5f4f-8d23-49ce-a28b-1b9cef82e955.png">

It's very strange. Could there be some issue on my particular PC that makes VSCode behave this way? What strikes me as odd the most is that there is no error feedback.

**Comment by meganrogge** [comment]
Since i cannot repro the issue, it's up to you to debug. Could you pls go to sources in dev tools, find this file, set a breakpoint and see what happens?
![Screen Shot 2022-04-13 at 10 44 14 PM](https://user-images.githubusercontent.com/29464607/163321428-90a9844c-d7b4-4a26-aecc-e28472fad063.png)

**Comment by chtenb** [comment]
I doesn't get hit. But I notice that the code looks very different from yours:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/1030961/163341141-1c2eadf9-6e91-41ef-869a-cbebb3256fe1.png">

**Comment by chtenb** [comment]
Btw, I updated my insider version in the meantime, just to make sure I'm up-to-date:

Version: 1.67.0-insider (system setup)
Commit: e3f21a18e2727ac37c78159ba81f2c6ee4a982cc
Date: 2022-04-13T05:15:45.536Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by chtenb** [comment]
Just to verify: the function should work without explicitly defining `terminal.external.windowsExec`, correct?

**Comment by meganrogge** [comment]
Sorry there are two files with that name - this is the one you want to debug
![Screen Shot 2022-04-18 at 9 01 30 AM](https://user-images.githubusercontent.com/29464607/163836456-4fa70332-a681-4d87-9a4e-10066b35bd1d.png)

**Comment by meganrogge** [comment]
> Just to verify: the function should work without explicitly defining terminal.external.windowsExec, correct?

Yeah that shouldn't be necessary

**Comment by chtenb** [comment]
Yes, it does get hit there and walks through the lines until line 72. I tried stepping into that and figure out what was going on, but I got lost there in logic I did not understand.

**Comment by chtenb** [comment]
```
linuxExec: "xterm"
osxExec: "Terminal.app"
windowsExec: "C:\\WINDOWS\\System32\\cmd.exe"
```

**Comment by meganrogge** [comment]
okay it looks like that must be exiting when it's spawned. https://github.com/microsoft/vscode/blob/4a130c40ed876644ed8af2943809d08221375408/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L71

does that directory exist? "C:\\WINDOWS\\System32\\cmd.exe"

**Comment by chtenb** [comment]
> does that directory exist? "C:\WINDOWS\System32\cmd.exe"

Yes

![image](https://user-images.githubusercontent.com/1030961/164051190-282ade08-5a95-4b45-9b82-6c68c2ea1fae.png)

**Comment by chtenb** [comment]
I can also run and use cmd.exe just fine when I launch it manually.

**Comment by meganrogge** [comment]
does this work for you in VS Code stable?

**Comment by chtenb** [comment]
No, it works neither in the insiders version nor in the stable version. I've also tested WSL and vanilla windows; both do not work.

**Comment by meganrogge** [comment]
do you have anti-virus software installed? the only other thing you could try is debugging more bc I cannot reproduce the issue

**Comment by chtenb** [comment]
> do you have anti-virus software installed?

Yeah, but it doesn't give any reports pointing towards this issue.

> the only other thing you could try is debugging more bc I cannot reproduce the issue

I understand. Unfortunately I don't have any ideas about how I could narrow down the issue.

**Comment by meganrogge** [comment]
You could step in to the code that I mentioned above and send screen shots with info about what's going on
