### ISSUE TITLE
Dropped frame when scrolling in integrated terminal

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#147117]
<img width="835" alt="image" src="https://user-images.githubusercontent.com/876920/162529146-5cee2c46-1858-4c07-b446-53389c0d6a29.png">

I have `terminal.integrated.scrollback` set to 10,000 and scrolling in the build task after a while is sluggish.

**Comment by meganrogge** [comment]
did you have shell integration enabled when this happened?

**Comment by rebornix** [comment]
@meganrogge I don't. There are issues with shell integration so I have it turned off.

**Comment by meganrogge** [comment]
did you have gpuAcceleration enabled here?
