### ISSUE TITLE
Codespace for CS50x not loading

### ISSUE THREAD

**Issue by Splyfy** [microsoft/vscode#147145]
Hello there!

Just reporting an issue with my codespace failing to load when trying to connect through cs50x links @ https://cs50.harvard.edu/x/2022/
Unsure of cause. Browser is up to date. 

Thanks!

**Comment by aeschli** [comment]
Did you contact the admins of the cs50 project? They might would know how to debug this and file issue against Codespaces.
This is the VS Code repo and not the right place for codespaces issue.

**Comment by aeschli** [comment]
Did you contact the admins of the cs50 project? They might would know how to debug this and file issue against Codespaces.
This is the VS Code repo and not the right place for codespaces issue.

**Comment by dyf99** [comment]
same problem

**Comment by dyf99** [comment]
i solve it just go into this link 
https://code.cs50.io/restart

After your Codespace is stopped
login again from here  https://code.cs50.io/ :)
