### ISSUE TITLE
Something wrong with icon

### ISSUE THREAD

**Issue by lwshanbd** [microsoft/vscode#147189]
Issue Type: <b>Bug</b>

Problem as https://drive.google.com/file/d/1OlXUSeOVtjK-PUgbjFbAy_5vfXo3J308/view?usp=sharing

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.11.12-300.fc34.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 9, 7|
|Memory (System)|32.00GB (2.97GB free)|
|Process Argv|--crash-reporter-id a37a0fc4-e8b8-41d5-ab16-eceb67cb6ba7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: exxact-f1|
|OS|Linux x64 5.11.12-300.fc34.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 5115 CPU @ 2.40GHz (40 x 2400)|
|Memory (System)|187.57GB (91.06GB free)|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Please paste your screenshot directly into the issue here instead of expecting people to click on a link to Google Drive

**Comment by lwshanbd** [comment]
So sorry for that…. I used the VScode’s feedback, and it doesn’t support uploading image…. Anyway, I have solved it and I will close this issue.

Baodi SHAN
Ph.D. Student
Exasca||ab
Institute for Advanced Computational Science
Stony Brook University

**Comment by gjsjohnmurray** [comment]
> I used the VScode’s feedback, and it doesn’t support uploading image. 

Maybe use the phrase "screenshot to follow" in the issue body, then edit the issue on GH to replace those words with your screenshot.
