### ISSUE TITLE
Reload after extension install do not work

### ISSUE THREAD

**Issue by okmechak** [microsoft/vscode#147143]
Issue Type: <b>Bug</b>

My profile synced few extenstion and they need now reload, but after clicking reload extensions steel not work.
This is present on mac.

VS Code version: Code 1.62.3 (Universal) (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T07:59:13.865Z)
OS version: Darwin arm64 20.3.0
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.19GB free)|
|Process Argv|--crash-reporter-id 03dd8eaf-fe3b-4417-9736-b9846c30696f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ursa-major|
|OS|Linux x64 5.13.0-39-generic|
|CPUs|Intel(R) Core(TM) i3-4330 CPU @ 3.50GHz (4 x 800)|
|Memory (System)|11.56GB (5.08GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.66.1
remote-ssh-edit|ms-|0.70.0
vscode-freefem|Pie|2.0.10
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.15.13
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
references-view|ms-|0.0.89
vscode-freefem|Pie|2.0.10
java|red|1.4.0
vscode-3dviewer|sle|0.2.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
meshviewer|zjc|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please check if this issue reproducible is latest stable version 1.66.1.
https://code.visualstudio.com/Download
