### ISSUE TITLE
Log in to github in vscode

### ISSUE THREAD

**Issue by tanhh326** [microsoft/vscode#147104]
This is My  environment:
        windwos 11
       VSCodeUserSetup-x64-1.66.1

error:
        login to github in vscode show this toolTip box , and the browser will not pop up for me to log in
![image](https://user-images.githubusercontent.com/82007768/162491850-7d499e9f-ead3-4735-8911-2a4299b07a53.png)

I hope you can help me. Thank you (*^▽^*)

**Comment by vsodergr** [comment]
I'm having the same issue. When selecting to log into GitHub from "Sign in to Sync Settings" on the Accounts icon VS Code opens a Firefox browser window attached to VS Code, not in the main Firefox instance. My credentials for GitHub are accepted and reports that I am being directed back to VS Code. But back in Code there is no change, except for the "Cancelled" notification in the lower right corner. 

Version: 1.66.1
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:51:26.173Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.4.0-107-generic snap

**Comment by Wombosvideo** [comment]
Exact same issue here. Using Vivaldi (Chromium based) as default browser.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-40-generic snap
Restricted Mode: No

**Comment by TylerLeonhardt** [comment]
I have improved this by adding a fallback mechanism if the first auth flow doesn't finish. Now what will happen is... if you don't finish the first flow (like if your browser doesn't redirect back to vscode correctly) you will get a notification that asks if you wanna try again. At this point, we will try a new flow that doesn't involve redirecting back to vscode and instead redirects to a local server that vscode spins up. If THAT fails, then we'll fall back to the device code flow which doesn't use any local server or redirection and really should work.

**Comment by TylerLeonhardt** [comment]
Verification steps:

* start a GitHub log in but don't finish the flow in your browser
* Go back to vscode and wait... eventually you'll see a notification about using a different a login flow
* Proceed and this time go through the login

You'll notice that this flow doesn't redirect back to vscode and instead shows you a "You can now close this tab" page. This is to workaround #148041.

**Comment by Emin141** [comment]
For anyone still having this issue, on my Ubuntu LTS 20.04 I have installed VS Code using snap and not the official .deb package. Completely forgot that snap updates software on its own and always assumed that VS Code will be updated with "sudo apt update && sudo apt upgrade -y". Took me a while to realise I had an outdated version of VS Code, so it's something worth checking.
