### ISSUE TITLE
move file out of directory when renaming file by prefixing with `../`

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [microsoft/vscode#147157]
Search terms:
- move file out of directory
- ../

I have this file:
![image](https://user-images.githubusercontent.com/52586855/162597300-b39b8fed-3c55-495f-83f7-bb107082c284.png)

I want to move it out of the `startStop` directory.

I want to rename the file and add `../` before it, similar to `mv file.ts ../file.ts`:

The current behavior does not allow this:
![image](https://user-images.githubusercontent.com/52586855/162597343-0e84bac0-d988-4143-bf55-005617ec2f44.png)

I'm requesting that this should be allowed and it should move the file out of the directory.

Right now the fastest way is to drag, which can take some time to scroll up to the parent directory:

https://user-images.githubusercontent.com/52586855/162597448-f97f30da-1852-4975-a03f-1000951f72f3.mp4

**Comment by lramos15** [comment]
\duplicate #150124
