### ISSUE TITLE
Collapsed/minimized sections in notebook cells re-opening on scroll

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode#147114]
Issue Type: <b>Bug</b>

Create some cells
Define functions
Click on the little arrows next to the function definition to 'collapse' or 'minimize' them into a single line
Scroll until the cells with the collapsed functions are out of view
Scroll back so the cells are in view
The functions are no longer collapsed

Since I have functions which are long in lines of code, I collapse them so I can more quickly move back and forth in my code.
This hasn't always been the case. I can't pinpoint the update, But it happened in the last week or 2

Extension version: 2022.4.1000991945
VS Code version: Code - Insiders 1.67.0-insider (a3d53f76790d8c88f835afe85225ff6442703409, 2022-04-07T05:15:43.863Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1059-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (2.13GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: AWS|
|OS|Linux x64 5.4.0-1059-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 3120)|
|Memory (System)|30.91GB (29.02GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
pynewfile477:30451556

```

</details>

**Comment by rebornix** [comment]
hmm, it seems due to that we now delay the restore of the view state. Reverted my change.
