### ISSUE TITLE
All files deleted

### ISSUE THREAD

**Issue by cdftgh** [microsoft/vscode#147182]
Issue Type: <b>Bug</b>

All of my files have been deleted and i dont know why. Please fix it

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.94GB (3.40GB free)|
|Process Argv|--crash-reporter-id ebe4e828-20e9-4465-9f74-474955a8df87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
bracket-pair-colorizer-2|Coe|0.2.4
javadebugger|don|0.1.5
vscode-javac|geo|0.2.39
beautify|Hoo|1.5.0
material-icon-theme|PKi|4.15.0
java|red|1.4.0
LiveServer|rit|5.7.5
vscodeintellicode|Vis|1.2.18
vscode-gradle|vsc|3.11.0
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by gjsjohnmurray** [comment]
In exactly which folder did you write your code?

**Comment by unanmed** [comment]
My friend meets the same problem. The files were deleted when vscode was closed, and all of the files except the folders were deleted. Maybe the computer's performance matters. Or maybe some important dependencies or tools are not installed.

**Comment by unanmed** [comment]
My friends solved the problem recently. Probably because you closed the vscode before the updater finished updating, which caused the files were destroyed.

**Comment by JacksonKearl** [comment]
@unanmed what folder were you developing in?
