### ISSUE TITLE
color code not responding

### ISSUE THREAD

**Issue by angelibagsik** [microsoft/vscode#147195]
I don't know what happened.
I linked my my css file to my html.
Then when I'm coding for a background color
it's not appearing on the preview.
And when I try redownloading the app
it says createprocess failed 740 and 
something with the user account elevation??

Pls.. help..

Thank you

**Comment by aeschli** [comment]
How do you preview your HTML page? How is VS Code involved?

**Comment by angelibagsik** [comment]
I “open with chrome”
Then I try “open with live server”

I also download sublime text and it has the same issue.I don’t know how to
fix it.

**Comment by aeschli** [comment]
So it is probably related to your HTML and CSS source files?

Could also be the Live Preview extension you a using, but if you see the same when opening with Chrome, I doubt that.

Sorry, this is the issue inbox for VS Code issues. Please try to get help about HTML and CSS in another forum.
