### ISSUE TITLE
Keymapping issues with ctrl+z VSC

### ISSUE THREAD

**Issue by sneakerush** [microsoft/vscode#147185]
I am having issues with my Undo, Key Mapping function. It's default is ctrl+z which is exactly what I want but the shortcut key does not work. The same goes for the Redo key (which is ctrl+y/ctrl+shift+z). When i tried remapping the key, it does not even let me type in ctrl+Z respectively. I am able to type them separately, but when i try together it does not work. My ctrl+Z function works with literally every other application i have, so its not a keyboard issue. 

FYI, my installed extensions are; Jupyter, Jupyter Keymap, Jupyter Notebook Renderers, Live Server, Pylance, and Python. I've already tried disabling Jupiter Keymap to see if that was the issue and it didn't make a difference

I've looked everywhere for an answer but no solution has been appropriate for me. Any help will be appreciated. I really don't want to have to switch to a different editor. 

Below i have also attached the Developer: Inspect key mappings for review.

[Dev Kep Mapping Inspect.txt](https://github.com/microsoft/vscode/files/8459857/Dev.Kep.Mapping.Inspect.txt)

**Comment by sneakerush** [comment]
@alexdima any help

**Comment by alexdima** [comment]
Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
