### ISSUE TITLE
Visualize data structures while debugging

### ISSUE THREAD

**Issue by miaokela** [microsoft/vscode#147142]
Visualize data structures while debugging

**Comment by miaokela** [comment]
Data display as a table or a box may be lean but necessary and more visualized.

**Comment by hediet** [comment]
@miaokela You can try out my personal extension ["Debug Visualizer"](https://marketplace.visualstudio.com/items?itemName=hediet.debug-visualizer)

**Comment by miaokela** [comment]
I had already tried,but it's not useful that there are some bugs just like losing params or data dispaly out of the whole window.
