### ISSUE TITLE
Improve automatic language detection in ployglot notebooks

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#147184]
Improve the language detection in ployglot notebooks by language detection in cell content, workspace stats, etc.

**Comment by JacksonKearl** [comment]
Thinking through this a bit, it's probably the case that almost all of the time your notebook will be in the same language. So it could be nice to instead have some sort of "the current language isn't correct, please use a different one" command. On "normal" notebooks this would end up being just a toggle between the notebook's one code lang (python, gh issue query, etc.), and markdown. In polyglot notebooks it'd do some sort of ML-assisted cycling: "current cell is python, user says pick a new language, so run the detector on all the languages the notebooks supports except python, and set to what what it says". 

What do you think about something along those lines?
