### ISSUE TITLE
Powershell Plugin - Inconsistent Debug Console Output

### ISSUE THREAD

**Issue by rageshm110** [Microsoft/vscode#14712]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: donjayamanne.python-0.5.0, ms-vscode.PowerShell-0.7.2

Steps to Reproduce:

1. Ctrl+Shift+D
2. Start Debugging

I am not able to see any output at debug console even with very basic cmdlets like get-service. PowerShell v5 is installed on machine. I have posted a question on answers.microsoft.com https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/visual-studio-code-powershell-debugging/8aea94d7-cb07-473f-9f25-1340c7c6f836

Please help.

**Comment by rageshm110** [comment]
![error](https://cloud.githubusercontent.com/assets/6996136/19835134/fb2e9684-9ea2-11e6-8e51-30a354c7cf8c.PNG)

**Comment by weinand** [comment]
This issue was moved to PowerShell/vscode-powershell#332
