### ISSUE TITLE
Integrated terminal session did not restored with previous Working Directory on Git Bash

### ISSUE THREAD

**Issue by fadhilx** [microsoft/vscode#147135]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.66.1
- OS Version: Windows_NT x64 10.0.19044

### Steps to Reproduce:
1. open folder on vscode
2. open terminal
3. cd to directory
4. close vscode
5. open vscode
6. observer terminal, you will see current working directory is not the same as the last one

![image](https://user-images.githubusercontent.com/15516786/162565373-b4f0a8f5-4b1c-4c8f-9b2c-77a699e8b5ba.png)
### Observed behavior:
before close vscode, the path : `..../shop/shop-next`
after session restored, the path : `..../shop`

#### Expected behavior: 
current directory should in `..../shop/shop-next` as the last working directory, not `..../shop`

**Comment by meganrogge** [comment]
This happens with or without shell integration enabled.

**Comment by fadhilx** [comment]
> This happens with or without shell integration enabled.

both with and without

**Comment by Tyriar** [comment]
Restoring the previous cwd depends on shell integration, back when this was reported shell integration didn't exist for Git Bash. This should work if you manually install git bash shell integration: https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation
