### ISSUE TITLE
Portable Mode in Windows 10 mapped network drive doesn't launch after upgrade from 1.65.2 to 1.66.1

### ISSUE THREAD

**Issue by JoseALermaIII** [microsoft/vscode#147174]
Does this issue occur when all extensions are disabled?: Yes

Issue Type: <b>Bug</b>

- VS Code Version: 1.66.1
- OS Version: Windows 10
<details>

<summary>OS Info</summary>

|Item|Value|
|---|---|
|Edition|Windows 10 Pro|
|Version|21H1|
|Installed on|‎7/‎3/‎2021|
|OS build|19043.1586|
|Experience|Windows Feature Experience Pack 120.2212.4170.0|

</details>

Prerequisites:

* A Windows 10 mapped network drive pointing to a folder in the Public user's Documents folder `C:\Users\Public\Documents\portableapps\`. More info on the steps here:
https://support.microsoft.com/en-gb/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d

Steps to Reproduce:

1. Follow Portable Mode directions for Windows:
https://code.visualstudio.com/docs/editor/portable
2. Extract the zip file to:
`P:\portableapps\VSCode_x64\`
3. In the portable directory, double-click the `Code.exe` file:
`P:\portableapps\VSCode_x64\Code.exe`

Expected behavior:
Application opens

Actual behavior:
The application doesn't launch

Additional Notes:
* The previous version `1.65.2` still works:
https://update.code.visualstudio.com/1.65.2/win32-x64-archive/stable
* Launching from PowerShell produces this output:
```
PS P:\portableapps\VSCode_x64> .\Code.exe
PS P:\portableapps\VSCode_x64>
[960:0410/220136.035:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.235:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.264:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.493:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.496:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.498:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.636:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.640:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.734:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[960:0410/220136.734:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
```
Using `--verbose` is similar:
```
PS P:\portableapps\VSCode_x64> .\Code.exe --verbose
PS P:\portableapps\VSCode_x64>
[3316:0410/235335.600:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235335.717:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235335.730:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235335.909:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235335.912:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235336.040:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235336.087:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235336.241:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[main 2022-04-11T04:53:36.246Z] [File Watcher (node.js)] Request to start watching: p:\portableapps\VSCode_x64\data\user-data\User (excludes: <none>),p:\portableapps\VSCode_x64\data\user-data\User\settings.json (excludes: <none>)
[3316:0410/235336.257:ERROR:gpu_process_host.cc(977)] GPU process launch failed: error_code=18
[3316:0410/235336.259:FATAL:gpu_data_manager_impl_private.cc(448)] GPU process isn't usable. Goodbye.
```
* Opening a terminal/file explorer to the non-network share location and launching from there works:
```
C:\Users\Public\Documents\portableapps\portableapps\VSCode_x64>Code.exe
[main 2022-04-10T15:40:37.604Z] window#load: attempt to load window (id: 1)
[main 2022-04-10T15:40:37.621Z] update#setState idle
[main 2022-04-10T15:40:37.680Z] ExtensionHostStarterWorker created
[main 2022-04-10T15:40:38.780Z] window#load: window reported ready (id: 1)
[main 2022-04-10T15:40:39.002Z] Starting extension host with pid 15656 (fork() took 30 ms).
[main 2022-04-10T15:40:39.004Z] ExtensionHostStarterWorker.start() took 33 ms.
[main 2022-04-10T15:40:50.833Z] window#load: attempt to load window (id: 1)
[main 2022-04-10T15:40:50.855Z] Extension host with pid 15656 exited with code: 0, signal: null.
[main 2022-04-10T15:40:51.734Z] window#load: window reported ready (id: 1)
[main 2022-04-10T15:40:51.950Z] Starting extension host with pid 9884 (fork() took 17 ms).
[main 2022-04-10T15:40:51.951Z] ExtensionHostStarterWorker.start() took 19 ms.
[main 2022-04-10T15:41:07.639Z] update#setState checking for updates
[main 2022-04-10T15:41:07.741Z] update#setState idle
[13352:0410/104237.415:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is disabled, ANGLE is
[main 2022-04-10T16:06:50.601Z] Waiting for extension host with pid 9884 to exit.
[main 2022-04-10T16:06:50.638Z] Extension host with pid 9884 exited with code: 0, signal: null.
```
PowerShell:
```
PS C:\Users\Public\Documents\portableapps\portableapps\VSCode_x64> .\Code.exe
PS C:\Users\Public\Documents\portableapps\portableapps\VSCode_x64>
[main 2022-04-11T03:02:59.835Z] window#load: attempt to load window (id: 1)
[main 2022-04-11T03:02:59.883Z] update#setState idle
[main 2022-04-11T03:02:59.964Z] ExtensionHostStarterWorker created
[main 2022-04-11T03:03:01.624Z] window#load: window reported ready (id: 1)
[main 2022-04-11T03:03:02.210Z] Starting extension host with pid 6020 (fork() took 91 ms).
[main 2022-04-11T03:03:02.242Z] ExtensionHostStarterWorker.start() took 126 ms.
[main 2022-04-11T03:03:08.731Z] Waiting for extension host with pid 6020 to exit.
[main 2022-04-11T03:03:08.782Z] Extension host with pid 6020 exited with code: 0, signal: null.
```
* Insider version `1.67.0` also doesn't work:
https://code.visualstudio.com/insiders/#
* Deleting the `data` folder and creating an empty one also doesn't work.
* Restarting the computer didn't work
* Saw no related entries in the virus scanner

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (8.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
bitburner-vscode-integration|bit|1.3.3
vscode-eslint|dba|2.2.2

</details>

**Comment by JoseALermaIII** [comment]
I don't know _how_ this fixed it but:

1. Move the portable folder out of the Public user folder into the currently logged in user directory structure:
`C:\Users\User\Desktop\VSCode_x64`
2. Double-click the `Code.exe` file to open the app
3. Close the app
4. Move the portable folder back to the Public user folder:
`C:\Users\Public\Documents\portableapps\portableapps\VSCode_x64`
5. Double-click the `Code.exe` file to open the app

Maybe a permissions issue? I restarted my computer and checked my virus scanner and neither of those was it.

I suppose this will be here for anyone else with the same problem.

**Comment by JoseALermaIII** [comment]
After some additional tests, I found out how to reproduce.

Please let me know if there's any other information I can provide

**Comment by JoseALermaIII** [comment]
After more digging, it looks like this could be related to #146464 and/or [#32074](https://github.com/electron/electron/issues/32074)

**Comment by JoseALermaIII** [comment]
Based on the suggestion in #146464, using `--disable-gpu-sandbox` does work:
```
PS P:\portableapps\VSCode_x64> .\Code.exe --disable-gpu-sandbox
PS P:\portableapps\VSCode_x64>
Warning: 'disable-gpu-sandbox' is not in the list of known options, but still passed to Electron/Chromium.
[13764:0411/004031.298:ERROR:gl_surface_egl.cc(808)] EGL Driver message (Error) eglCreateContext: Requested GLES version (3.0) is greater than max supported (2, 0).
[13764:0411/004031.329:ERROR:gl_context_egl.cc(355)] eglCreateContext failed with error EGL_SUCCESS
[main 2022-04-11T05:40:33.582Z] window#load: attempt to load window (id: 1)
[main 2022-04-11T05:40:33.834Z] update#setState idle
[main 2022-04-11T05:40:35.169Z] ExtensionHostStarterWorker created
[main 2022-04-11T05:40:40.316Z] window#load: window reported ready (id: 1)
[main 2022-04-11T05:40:41.280Z] Starting extension host with pid 6268 (fork() took 258 ms).
[main 2022-04-11T05:40:41.297Z] ExtensionHostStarterWorker.start() took 276 ms.
[main 2022-04-11T05:40:47.716Z] Extension host with pid 6268 exited with code: 0, signal: null.
```

Unless I'm missing something, this can likely be closed as a duplicate

**Comment by joaomoreno** [comment]
Fantastic issue details and investigation @JoseALermaIII 👏
