### ISSUE TITLE
Visual Studio Code is lagging and is responding too late if I type anything

### ISSUE THREAD

**Issue by adityadond** [microsoft/vscode#147130]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by adityadond** [comment]
Yes  VS code version:1.66.1
and OS version: Windows 10

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by mjbvz** [comment]
Please also see the issue reporting guidelines. There is not enough information to investigate this

/needsMoreInfo
