### ISSUE TITLE
Test item range is wrong when workspace edit is applied

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#147132]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.66.1 (user setup)
Commit: 8dfae7a5cd50421d10cd99cb873990460525a898
Date: 2022-04-06T14:50:12.141Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Clone the repository: https://github.com/jdneo/test-api-issue.
2. Setup the extension and launch it.
3. Open `test.txt`
4. Trigger command `Hello World`, which will apply a workspace edit.
5. One test item disappear and the range is different from that set via api.

https://user-images.githubusercontent.com/6193897/162564176-84c73b2e-ef0a-4031-8000-eb67878ac57d.mp4

Note: From my observation, this error relates with how many lines between the 'parent' and 'child' item. When the lines added by the workspace edit is the same as the lines between the parent and child, then this will happen. If they are different, then everything works fine:

https://user-images.githubusercontent.com/6193897/162564220-bbcd9564-5b6d-445f-a6f9-c1b56d4c2ea7.mp4

**Comment by connor4312** [comment]
Fixed this in https://github.com/microsoft/vscode/pull/161446

**Comment by jdneo** [comment]
Confirmed that it is fixed in 

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
