### ISSUE TITLE
Add go to declaration or function

### ISSUE THREAD

**Issue by lexgo13** [Microsoft/vscode#14714]
i want do this:
With right click on a variable, access to a contextual menu. Select go to *
- (variable declaration, function declaration, anything declaration in relation with a current word)

**Comment by SeanHub** [comment]
When using TypeScript you can press F12 to go to the function/variable declaration. Not sure about other languages though.

**Comment by jrieken** [comment]
Yeah - extensions can plugin *data providers* to this feature. TypeScript, Go, C#, etc do this but it always depends on the language and the set of extensions. 

@lexgo13 I have understood you request be a more fine grained version of our current go to declaration. Am I correct or did you try this with a language no extension provides the data for yet?

**Comment by jrieken** [comment]
@lexgo13 ping
