### ISSUE TITLE
Terminal: using nerd font with starship is rendering oddly

### ISSUE THREAD

**Issue by jessicah** [microsoft/vscode#147196]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.1
- OS Version: Wintows NT x64 10.0.19044

Steps to Reproduce:

1. Set Terminal font to a Nerd Font patched copy of Operator Mono XLight (I've added to a private repo, https://github.com/jessicah/nerdfont, if I need to add someone to access list for testing purposes)
2. In a Terminal, `cat` contents of https://gist.github.com/jessicah/abfeda83ec1cb8049414e1d166f77e79

Desired Output (e.g. PuTTY):
![image](https://user-images.githubusercontent.com/274082/162665667-66239bc6-4d8c-4b5b-9876-fbf6af576c77.png)

Actual Output (VSCode Terminal):
![image](https://user-images.githubusercontent.com/274082/162665704-e2044288-e111-4b35-aae1-93774d4b753b.png)

Also note that the glyphs appear to be slightly truncated at the right as well.

**Comment by albertosantini** [comment]
Is this issue related to https://github.com/microsoft/vscode/issues/146471?

**Comment by jessicah** [comment]
Unsure, echoing the same output in Windows Terminal (1.12.10732.0) renders correctly.

![image](https://user-images.githubusercontent.com/274082/162841886-19352c3d-bafb-4423-9050-3071c1632963.png)

**Comment by jessicah** [comment]
That addresses the colours, but not the truncated characters; also the emoji seem oversize, and would prefer that it uses the emoji from the configured font.
