### ISSUE TITLE
Illegal instruction electron_run_as_node=1

### ISSUE THREAD

**Issue by giuliohome** [Microsoft/vscode#14724]
- VSCode Version: latest 32-bit .deb 
- OS Version: Ubuntu 12.04

Steps to Reproduce:
1.  Installing .deb
2.  Running code

Complete description of the issue is here: 
http://askubuntu.com/questions/843518/visual-studio-code-on-ubntu-12-04-32bit

Despite the question is answered, the problem is still open

**Comment by joaomoreno** [comment]
What is your physical hardware? Is it a 32 bit system? Or an ARM system?

`Illegal instruction` comes from the Electron binary indicating that the instructions in the executable are wrong for this system.

**Comment by giuliohome** [comment]
Thanks for your prompt reply. System is old 32 bit and cpu Amd Athlon ... I don't know where electron binary  and how to choose/setup the correct executable. Let me know if you want me to run any commands. Thanks again

**Comment by joaomoreno** [comment]
Can you run the `electron` executable from the vanilla Electron release? https://github.com/electron/electron/releases/download/v1.3.8/electron-v1.3.8-linux-ia32.zip

**Comment by giuliohome** [comment]
Unzipped, thank you for the link: how am I supposed to test it? Running only ./electron results in Illegal instruction

**Comment by joaomoreno** [comment]
Can you then file an issue in Electron? They will help you find out what's wrong: https://github.com/electron/electron/issues

**Comment by giuliohome** [comment]
I filed [issue 7808](https://github.com/electron/electron/issues/7808)
