### ISSUE TITLE
Update fails comeback 47841#

### ISSUE THREAD

**Issue by Osmiogrzesznik** [microsoft/vscode#147249]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: Cannot access , update broke my install
- OS Version: Windows 10

Steps to Reproduce:

1. Close Visual Studio Code

How it is possible that after system-wide installation i had no problems for 3 months and it happens again?
https://github.com/microsoft/vscode/issues/47841#issue-314190638

**Comment by joaomoreno** [comment]
Have you tried disabling Windows background updates? Set `update.enableWindowsBackgroundUpdates` to `false`.
