### ISSUE TITLE
VS Code reorders properties in ipynb file

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#147252]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/9601

<div type='discussions-op-text'>

<sup>Originally posted by **VacuousTruth0** April  5, 2022</sup>
1. Create an ipynb file with a code cell:
```
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "print('Hello world')"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```
2. Open the file in VS Code and save it.
3. The order of properties in the code cell has changed - `metadata` and `outputs` are now below `source`:
```
{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "source": [
    "print('Hello world')"
   ],
   "outputs": [],
   "metadata": {
    "tags": []
   }
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
```

Is this the expected behaviour? Based on https://github.com/microsoft/vscode-jupyter/issues/742, I was expecting the properties to remain in sorted order.

I'm using VS Code 1.60.0.</div>

**Comment by roblourens** [comment]
1.60 is pretty old, please upgrade. I verified that it works for me in the latest
