### ISSUE TITLE
The problem is in the output data

### ISSUE THREAD

**Issue by P1X9L** [microsoft/vscode#147247]

**Comment by P1X9L** [comment]
[Running] node "c:\Users\Acer\Desktop\sadf\tempCodeRunnerFile.javascript"
[Done] exited with code=0 in 2.822 seconds
When the program starts, the output writes this:

![kYGRDriw0sY](https://user-images.githubusercontent.com/103454335/162815208-f95b4ae9-4b82-4105-a064-63af5360632a.jpg)

**Comment by weinand** [comment]
@P1X9L I cannot see a problem here.
Your program logs the variable `x` to the output and `x` has the value `2`.
What's wrong with that?
