### ISSUE TITLE
Copy/paste file path from the file explorer is not working[Ubuntu 18.04]

### ISSUE THREAD

**Issue by sandesha-hegde** [microsoft/vscode#147285]
Issue Type: <b>Bug</b>

File path is not coming If I do CTRL + C (copy) file from the file explorer and CTRL + V in vscode. It used work for older version but stopped working now. Current vs code version is 1.66.1.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.4.0-104-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|15.45GB (8.14GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 1a0b4cd4-f796-4640-a7ad-8f51d68cf68b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by sandesha-hegde** [comment]
I saw lot off issues are raised for the same but I didn't find any solution for this.

**Comment by JacksonKearl** [comment]
same as #146770
