### ISSUE TITLE
Terminal Split Width is not persisted if not focused within exit

### ISSUE THREAD

**Issue by glekner** [microsoft/vscode#147289]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.1
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Have 1 Terminal with 2 Split views.
2. Create a new Terminal.
3. Exit VSCode
4. Open VSCode and return to the first Terminal with split view, now the right terminal is taking 90% of the width.

https://user-images.githubusercontent.com/24938324/162940231-48279cb0-b809-4b0a-8099-c6f038075ff0.mov

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode/pull/149594 fixing this
