### ISSUE TITLE
Since 1.66.0 code fails to start and exits with 0x80000003(portable version)

### ISSUE THREAD

**Issue by lidaxs** [microsoft/vscode#147200]
Issue Type: <b>Bug</b>

We make the executable through share  and since version 1.66.0 VSC is not able to start anymore.
We get a message that "Visual Studio Code does not work anymore" with button to close the application.
In the applicationlog of the eventviewer we see:
Naam van toepassing met fout: Code.exe, versie: 1.66.1.0, tijdstempel: 0x624052f8
Naam van module met fout: Code.exe, versie: 1.66.1.0, tijdstempel: 0x624052f8
Uitzonderingscode: 0x80000003
Foutmarge: 0x000000000157aef3
Id van proces met fout: 0x120c
Starttijd van toepassing met fout: 0x01d84d7230467677
Pad naar toepassing met fout: P:\VSCode-win32-x64-1.66.1\Code.exe
Pad naar module met fout: P:\VSCode-win32-x64-1.66.1\Code.exe
Rapport-id: 1237be64-deff-4360-9e8b-043fcf684003

To file this issue i used the newest installer to install the package on a vm which works good.
I think you created an awesome product and we use it al lot and hope you can fix this issue.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz (2 x 3601)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.44GB free)|
|Process Argv|--crash-reporter-id 3a913c18-e603-4d13-91eb-e294d18fb114|
|Screen Reader|no|
|VM|100%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by deepak1556** [comment]
Is the issue present with latest stable version `1.73` ?

**Comment by lidaxs** [comment]
The issue still exists with latest stable version 1.73.0
It is not possible to run this app from networklocation e.g.
\\fileserver\share\vsc\code.exe
Our workaround is to copy the files to the local computer and start the app
from there.

Op wo 7 dec. 2022 10:13 schreef Robo ***@***.***>:

**Comment by deepak1556** [comment]
This is a limitation of the runtime https://github.com/electron/electron/issues/27356, closing as not actionable.
