### ISSUE TITLE
Incorrect code highlight in Shell Script editor

### ISSUE THREAD

**Issue by tkitynski** [microsoft/vscode#147293]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.1
- OS Version: Linux x64 5.13.0-27-generic (Linux Mint 20.3 Cinnamon)

Steps to Reproduce:

1. Just type the code, as in screenshot, to see, that for some reason RegEx in `if` clause disturbs code highlight:

![obraz](https://user-images.githubusercontent.com/35531372/162946484-07a5bb95-ebd3-444e-b509-7f9b35b89451.png)

I found out, that when one removes the nested round brackets (capturing group with index 2), highlighting continues to work correctly.

**Comment by alexr00** [comment]
@tkitynski can you please share a copy-pastable example that I can use to reproduce the issue?

**Comment by tkitynski** [comment]
You're welcome:
```shell
#!/bin/bash

if [[ "${foo}" =~ ^(([^:]*)/)$ ]]; then
	declare bar="no highlight";
	declare baz="highlight works back again";
fi;
```

**Comment by alexr00** [comment]
Thanks, I can repro it. It seems that the `meta.scope.logical-expression.shell` scope is not getting closed. 

We get our shell script syntax highlighting grammar from https://github.com/atom/language-shellscript, but the grammar we use there is no longer being updated. Linking to https://github.com/microsoft/vscode/issues/77675, which track finding and adopting a better maintained grammar.
