### ISSUE TITLE
FILE NOT FOUND

### ISSUE THREAD

**Issue by shro-2002** [microsoft/vscode#147214]
Issue Type: <b>Bug</b>

EVEN THOUGH THE FOLDER EXISTS , it's showing Cannot find path 'c:\Users\KIIT\Desktop\Semester-4\Operating SyStem[OS]\OS LAB ASSIGNMENTS\LAB 12\' because it does not exist.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (9.35GB free)|
|Process Argv|--crash-reporter-id 26b35d12-65bf-4957-9191-e5651fe186b2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
vscode-pull-request-github|Git|0.40.0
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.231.5
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5449
vsliveshare-audio|ms-|0.1.91
vscode-css-peek|pra|4.2.0
java|red|1.4.0
LiveServer|rit|5.7.5
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by lramos15** [comment]
Can you provide a gif of you opening the folder in your explorer vs trying to open it in vs code.
