### ISSUE TITLE
Remove the notebookContentProvider API proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#147248]
The `notebookContentProvider` API proposal is currently not on track for finalization. This api was introduced when we were still figuring out the model for working with notebooks and was inspired by the custom editor api. However we ultimately went with the much simpler `NotebookSerializer` API

Parts of the `notebookContentProvider` API are not well tested or supported today and maintaining it adds complexity to VS Code. We'd like to remove it, however the API is currently used by (or at least enabled for):

- [x] Liveshare @alyssajotice @fubaduba (please copy correct owners if I got them wrong
- [x] Dot net interactive @brettfo, @colombod

Please let us know if/how you are using the `notebookContentProvider` api and if there are any factors that would block you from migrating off of it

**Comment by alyssajotice** [comment]
@mjbvz we should have what we need to migrate here: https://github.com/microsoft/vscode/issues/125757. I expect to have this done by the end of the month. I'll update this thread when we've stopped using it.

**Comment by alyssajotice** [comment]
@mjbvz here is an update: https://github.com/microsoft/vscode/issues/125757#issuecomment-1101818621

**Comment by mjbvz** [comment]
@alyssajotice How's Liveshare's migration been going? Run into any blockers or have any questions?

**Comment by alyssajotice** [comment]
Hey @mjbvz, I am currently working on the design docs for this. This will be a large, three-part change to the Live Share notebooks architecture, and our goal is to have this done by the fall. I'll send you the design doc when it is complete so you can stay up to date.

**Comment by mjbvz** [comment]
Looks like liveshare is not using `save`, `saveAs`, or `backup`. Let's remove these from the proposal entirely

**Comment by mjbvz** [comment]
All consumers have now migrated off this api

We just need to move our tests off of this api and then we can remove it entirely: https://github.com/microsoft/vscode/issues/160580
