### ISSUE TITLE
after vscode Update, can't connect to remote server, nor to check for update

### ISSUE THREAD

**Issue by hazho** [microsoft/vscode#147232]
Issue Type: <b>Bug</b>

Hi;
after vscode Update, I can't connect to remote server, nor to check for update

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (11.04GB free)|
|Process Argv|-n --crash-reporter-id 4105b3d0-1ea4-4e3e-8138-2dbd587d55b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
exe-runner|bra|0.2.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.79.2022040715
remote-ssh-edit|ms-|0.80.0
commandlist|yam|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by roblourens** [comment]
Please give some more details about exactly what you are trying to do and what error message you see.

**Comment by Hesamp** [comment]
hi
I have a similar problem,
For ssh, we connect to the server as an interactive-keybord.
The server does not have internet access.
In previous versions, after trying to download vscode-server files, if it was not successful, it would download through the system that was established by ssh and transfer the files.
But in the current version, it shows a 404 error and sometimes writes xhr error
![image](https://user-images.githubusercontent.com/1300289/162974806-155decd9-f8cc-49a7-82af-0514b30de624.png)

**Comment by Hesamp** [comment]
This problem occurs in the current version and if you downgrade to the previous version, the problem will be solved.

**Comment by icecrow77** [comment]
Hi,
similar error occured after upgrade VScode to
VS Code version: Code 1.66.1 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

the renderer log shows:

`[2022-04-12 15:59:27.274] [renderer1] [error] Cannot register remote filesystem provider. Error while fetching remote environment. Server returned 404
[2022-04-12 15:59:27.319] [renderer1] [error] Error: Server returned 404
....
[2022-04-12 15:59:27.675] [renderer1] [error] Server returned 404: Error: Server returned 404
    at w (vscode-file://vscode-app/c:/Users/*****/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:618:6598)
    at k.download (vscode-file://vscode-app/c:/Users/*****/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:619:1585)`

**Comment by Hesamp** [comment]
Yes, the problem is solved
