### ISSUE TITLE
Include glob pattern for Search does not behave correctly for workspace folders that include parentheses in their names

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#147257]
I have a `.code-workspace` that contains two virtual folders, one that has a parentheses in its name and one without. When I only include the non-parentheses workspace folder, the `TextSearchProvider` is only called for that workspace folder:

<img width="736" alt="Screen Shot 2022-04-11 at 4 43 01 PM" src="https://user-images.githubusercontent.com/44776135/162829300-a1f992d5-24bb-41e7-bf21-9f41e9a122ab.png">

When I only include the workspace folder with parentheses, the `TextSearchProvider` is called for every workspace folder:

<img width="740" alt="Screen Shot 2022-04-11 at 4 43 51 PM" src="https://user-images.githubusercontent.com/44776135/162829440-f397037a-a99b-49b3-9a7b-85a8dad586ae.png">

The search box does not give me the error that the workspace folder does not exist, so VS Code must know that this is a valid name. Is there a way that I should be escaping the parentheses? I tried checking for the folder name in the `options.includes` array in the `TextSearchProvider` so I could do the filtering myself, but it was empty.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/82415
