### ISSUE TITLE
The indentation is incorrectly changed after pasting

### ISSUE THREAD

**Issue by Z-E-D** [microsoft/vscode#147223]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 7

Steps to Reproduce:

The indentation of the existing closing code is changed after pasting, depending on the level of indentation of the copied code. Here is the animated screenshot:
![Indentation after paste](https://user-images.githubusercontent.com/97363660/162749466-cafe67db-c2ca-40a0-9053-8ae3908b0e5a.gif)

1. the first copied block (top) has indentation with one tab more than the resulting indentation -> after pasting, the existing closing bracket has one tab less indentation;
2. the second copied block (bottom) has indentation with three tabs less then the resulting indentation -> after pasting, the existing closing bracket has three tabs more indentation.

I have "editor.autoIndent": "full" because I like that option of VSCode very much with its automatic indentation based on the surrounding code.

Maybe these issues are related: #86301 and #85781.

**Comment by rebornix** [comment]
It looks like that the indentation rules for JS is not covering this case. Currently the indentation rules for 
 auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.

**Comment by Z-E-D** [comment]
This is not problem only with JS files. Here is HTML:
![2022-12-13_07-51-05](https://user-images.githubusercontent.com/97363660/207251174-22e749fb-8fc0-469d-84a6-fdb9ad61ec5a.gif)

Here is CSS:
![2022-12-13_07-53-51](https://user-images.githubusercontent.com/97363660/207251351-f840ba0f-d5d9-4bed-a585-5e7694395026.gif)

And JSON:
![2022-12-13_08-05-04](https://user-images.githubusercontent.com/97363660/207251408-ab080b37-08e9-4d59-8453-067783de0b7f.gif)

I don't understand how your regex code could add the proper number of tabs/space characters just fine to all pasted lines, except the last one.

Could you please point me in the right direction, where should I look in your code? I am not that good with TypeScript, but I am quite fine with regular expressions and maybe I could fix that for you.
