### ISSUE TITLE
Space Issues

### ISSUE THREAD

**Issue by mgarciaqblox** [microsoft/vscode#147296]
Issue Type: <b>Performance Issue</b>

At the moment Visual Studio Code takes up 49GB of space on my computer. I think this is not normal.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.4.0-107-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (6 x 2918)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|10.60GB (0.18GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 4b2660bb-72f4-45d6-b6ba-ea11b87169bb|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   141	 15210	code main
    0	    43	 15212	   zygote
    0	    76	 15332	     gpu-process
    0	    43	 15213	   zygote
    0	    87	 15487	     issue-reporter
    0	    54	 15260	   utility-network-service
    0	   228	 15280	   window (cluster_qrm - Visual Studio Code)
    0	   130	 15356	   shared-process
    0	    65	 15393	     ptyHost
    0	    65	 15418	     fileWatcher
    0	     0	 15504	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   119	 15385	   extensionHost
   16	   358	 15442	     /home/qblox/.vscode/extensions/ms-vscode.cpptools-1.9.7-linux-x64/bin/cpptools
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (cluster_qrm - Visual Studio Code)
|    Folder (cluster_qrm): 6076 files
|      File types: cpp(768) make(573) md(520) o(411) cmake(396) txt(290)
|                  h(281) hpp(214) internal(141) includecache(139)
|      Conf files: cmake(396) makefile(54) sln(6) dockerfile(2);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.4.0
rainbow-csv|mec|2.2.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.3.4
jupyter|ms-|2022.3.1000901801
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by ricahardHaggioGwati** [comment]
That's not normal, have you tried using filer explorer to check its containing files within your machine. Alternatively, I would suggest a full uninstallation and reinstall of vs code. Hopefully, that helps

**Comment by mjbvz** [comment]
Looks like this issue didn't get the correct attention when it was first opened

I'm closing it since there hasn't been any follow up. It's possible that an extension was causing this. If you are still seeing this, try seeing what is taking up all that space and let us know your findings
