### ISSUE TITLE
Don't switch to "Test explorer" when calling 'testing.runAll'

### ISSUE THREAD

**Issue by karolzlot** [microsoft/vscode#147288]
I set `F7` key as keyboard shortcut for "testing.runAll". It works, but when I click then not only tests are run but also tab is switched to "Test explorer".

I prefer that tab isn't switched. I am ok with tests happening in background.

If any test will fail I will get prompt anyway, because I set `"testing.automaticallyOpenPeekView": "failureAnywhere"`.

------------

Partially similar issue: https://github.com/microsoft/vscode/issues/137737

**Comment by connor4312** [comment]
This is configured via the `testing.openTesting` setting.
