### ISSUE TITLE
Rendering issue/Blur creation during mid internvals of opening VsCode

### ISSUE THREAD

**Issue by Shantanu66** [microsoft/vscode#147246]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.1
- OS Version:19044.1586
![Screenshot 2022-04-11 232342](https://user-images.githubusercontent.com/64373963/162800139-967d9662-aa70-4d7b-bc32-87f92e7465d4.png)
Steps to Reproduce:

1.Open vscode 
2.Try to open a new application/try to take a screenshot.

**Comment by deepak1556** [comment]
Can you check if the issue repros with `--disable-gpu` ?

**Comment by Shantanu66** [comment]
Yeah now its working as normal.Is there some problem with graphic driver interference?
