### ISSUE TITLE
Can we still display the Debug output window on the side

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#14725]
- VSCode Version: 1.6
- OS Version: OS X

In the older versions (don't remember the version, but fairly old) of VS Code, the debug output panel would be displayed on the right hand side (right hand side of the editor).
Today this output panel is displayed at the bottom along with the other output panels (like tasks, terminals etc).

Is it still possible to display the `Debug` output window on the right hand (see below).

![Image](https://raw.githubusercontent.com/DonJayamanne/pythonVSCode/master/images/standardDebugging.gif)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2806
