### ISSUE TITLE
update displaying problems

### ISSUE THREAD

**Issue by DeadlyKom** [microsoft/vscode#147208]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.1
- OS Version: Win 10 x64

Steps to Reproduce:

1. I had a similar problem, 2-3 weeks ago it was not there ... https://github.com/microsoft/vscode/issues/111443
2. The problem is that the highlighting of files that had errors does not update, and after editing these errors, the explorer does not update, although in fact there are no errors

Please advise what to do, I tried to search and did not find solutions
![image](https://user-images.githubusercontent.com/23453697/162701567-f54d99f4-f22d-4697-bc87-fb45b2fb17f2.png)

**Comment by gjsjohnmurray** [comment]
Explorer shows problems that are still listed on the Problems tab:

![image](https://user-images.githubusercontent.com/6726799/162720804-a6afbc1d-ecd7-411e-bc11-62950643dc22.png)

These problems are contributed by extensions, and it is the responsibility of the contributing extension to remove a problem from that tab when the problem no longer exists.

I suggest you raise the issue with the author of the extension from which the two problems on your Problems tab originated.

**Comment by DeadlyKom** [comment]
thanks, that's what I wanted to know
