### ISSUE TITLE
VSCode-insiders lock wsl terminal

### ISSUE THREAD

**Issue by Cybercrab** [microsoft/vscode#147220]
Issue Type: <b>Bug</b>

With the newest version, opening vscode in terminal (for instance, ```code-insiders .``` ) locks the terminal (Can't use the terminal for other tasks).

In previous versions, whenever I open vscode in terminal, it opens the editor and it was possible to keep using the same terminal windows for other tasks

VS Code version: Code - Insiders 1.67.0-insider (b84feecf9231d404a766e251f8a37c730089511b, 2022-04-11T05:15:52.676Z)
OS version: Windows_NT x64 10.0.22593
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (1.56GB free)|
|Process Argv|--crash-reporter-id eaa10567-176b-4a19-9599-8b82ae831ba7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.0
spellright|ban|3.0.62
vagrant|bbe|0.5.0
better-toml|bun|0.3.2
lua-templates|com|0.0.1
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.3
gitlens|eam|12.0.5
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
foam-vscode|foa|0.17.8
go|gol|0.32.0
beautify|Hoo|1.5.0
vscode-markdown-notes|kor|0.0.24
git-graph|mhu|1.30.0
vscode-docker|ms-|1.21.0
vscode-language-pack-pt-BR|MS-|1.66.2
vscode-edge-devtools|ms-|1.4.7
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.232.5
remote-wsl|ms-|0.66.0
live-server|ms-|0.2.12
vscode-paste-image|mus|1.0.4
indent-rainbow|ode|8.3.1
red|red|0.4.3
rust|rus|0.7.8
vscode-lua|tri|0.12.4
vscode-vlang|vla|0.1.11
markdown-all-in-one|yzh|3.4.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
vscaac:30438845
pynewfile477:30451556

```

</details>

**Comment by Cybercrab** [comment]
Additional info: the lock happens only when vscode-insiders is closed. If there's an open window already, the lock doesn't happen

**Comment by meganrogge** [comment]
Can you pls attach a gif so I know exactly what you're talking about?

**Comment by meganrogge** [comment]
> Additional info: the lock happens only when vscode-insiders is closed. If there's an open window already, the lock doesn't happen

So no vscode windows are open and in an external terminal you run `code-insiders .`?

**Comment by Cybercrab** [comment]
> > Additional info: the lock happens only when vscode-insiders is closed. If there's an open window already, the lock doesn't happen
> 
> So no vscode windows are open and in an external terminal you run `code-insiders .`?

Exactly this. Whenever I run the command in a external terminal, the external terminal was locked, coudn't be used for another tasks.  However, in the last update (downloaded this morning) the bug doesn't happen anymore.

**Comment by meganrogge** [comment]
Okay great, so closing this as it must be fixed
