### ISSUE TITLE
Notebook formatting is inconsistent

### ISSUE THREAD

**Issue by firelizzard18** [microsoft/vscode#147268]
Issue Type: <b>Bug</b>

Formatting for `stdout` output items is inconsistent. In the following image, there are two outputs with one item each. The first one is formatted monospace with `whitespace: pre`, the second one is not.

![image](https://user-images.githubusercontent.com/879055/162861865-1e9fa676-702f-4374-a55a-8eb1e6fdcb5f.png)

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.88GB (39.75GB free)|
|Process Argv|--crash-reporter-id 8d76c88c-bb0c-4275-afc9-bb8b9f014c6a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|Memory (System)|50.10GB (40.96GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz (20 x 3600)|
|Memory (System)|50.10GB (40.96GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
Bookmarks|ale|13.2.4
tsl-problem-matcher|amo|0.6.2
quitcontrol-vscode|art|4.0.0
esbuild-problem-matchers|con|0.0.2
systemd-unit-file|coo|1.0.6
simple-notebook-renderers|eth|0.1.1
vscode-firefox-debug|fir|2.9.6
remotehub|Git|0.30.0
gitpod-desktop|git|0.0.29
terraform|has|2.21.0
remote-containers|ms-|0.231.5
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
remote-repositories|ms-|0.4.0
material-icon-theme|PKi|4.15.0
slim|sia|0.1.2
rewrap|stk|1.16.3
haml|vay|1.0.1
vscode-nginx|wil|0.7.2
vscode-ruby|win|0.28.0
better-toml|bun|0.3.2
dart-code|Dar|3.38.2
gitlens|eam|12.0.5
go-notebook-kernel|eth|0.2.0
gitlab-workflow|Git|3.42.0
go-nightly|gol|2022.4.616
terraform|has|2.21.0
vscode-go-template|jin|0.2.1
git-graph|mhu|1.30.0
vscode-markdown-notebook|ms-|0.0.26
vscode-yaml|red|1.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

I am working on an extension that incorporates a fork of the official markdown notebook extension. The notebook is serialized as the following:

    ```go
    import "fmt"
    ```

    ```go{ id: 1 }
    fmt.Println("Hello\nWorld")
    fmt.Println("Hello\nWorld")
    ```

    ```{ result_of: 1, id: 1, mime: "application/vnd.code.notebook.stdout" }
    Hello
    World
    ```

    ```{ result_of: 1, id: 2, mime: "application/vnd.code.notebook.stdout" }
    Hello
    World
    ```

**Comment by rebornix** [comment]
This issue should now be fixed.
