### ISSUE TITLE
Search Regex doesn't recognize "\A" (beginning of file)

### ISSUE THREAD

**Issue by DrPepperBianco** [microsoft/vscode#147209]
Issue Type: <b>Bug</b>

Open a folder, search for "\A" and activate Regex search. Error message "/\A/" is not a valid regex. But it should be. "\A" means beginning of text and "\z" end of text. The same works in "Visual Studio" without a problem. 

Although Visual Studio seems to search files per line, so \A finds the start of every line, instead of just the first line. But when searching multiple files, it should mean only the start of the file instead. Otherwise it is not possible to search for files that start with a pattern.

VS Code version: Code 1.64.0 (5554b12acf27056905806867f251c859323ff7e9, 2022-02-03T04:22:20.678Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (13.19GB free)|
|Process Argv|C:\\Git-Code\\ACSMask-Modules\\Siemens-Wrapper\\impl-auskoppeln --crash-reporter-id 885e577e-a37c-475a-ae63-83f52b4e19fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
doxdocgen|csc|1.4.0
xml|Dot|2.5.1
gitlens|eam|12.0.5
gc-excelviewer|Gra|4.2.54
vscode-ansi|ili|1.1.2
plantuml|jeb|2.17.2
better-cpp-syntax|jef|1.15.13
vscode-icon-theme|jtl|1.6.6
rainbow-csv|mec|2.2.0
azure-pipelines|ms-|1.202.0
csharp|ms-|1.24.1
remote-containers|ms-|0.231.5
remote-ssh|ms-|0.76.1
remote-ssh-edit|ms-|0.78.0
remote-wsl|ms-|0.64.2
azure-account|ms-|0.10.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.5
powershell|ms-|2021.12.0
vscode-xml|red|0.20.0
msbuild-project-tools|tin|0.4.3
json2yaml|tux|0.2.0
cmake|twx|0.0.17
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by DrPepperBianco** [comment]
Workaround: Search for `(?<!\n)^`, it has roughly the same meaning as `\A`.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support to understand which regex syntax is supported.

**Comment by roblourens** [comment]
@gjsjohnmurray has the right idea, this isn't supported by js
