### ISSUE TITLE
If you modify the "editor.lineHeight" setting, multiline tooltips will overlap

### ISSUE THREAD

**Issue by darkred** [Microsoft/vscode#14721]
- VSCode Version: 1,6,0
- OS Version: win10x64

Steps to Reproduce:
1.  Open a new file, set as language Javascript, and type this:

```
var a = [1,
2]
```
1. Here is how the tooltip lines are displayed (after clicking the balloon icon) while the  `editor.lineHeight` setting has its default value (0) :  
   ![2016-10-30_233100](https://cloud.githubusercontent.com/assets/723651/19840180/781e55ac-9ef9-11e6-9d8d-e61a534842d3.jpg)
2. Now, in File|Preferences|User Settings add this entry `editor.lineHeight": 15` ( \* )  
   Here is how the tooltip lines are displayed:  
   ![2016-10-30_233128](https://cloud.githubusercontent.com/assets/723651/19840194/b13a4d14-9ef9-11e6-9961-55ebc495f334.jpg)  
   i.e. they now overlap.

<br>
( \* ) I use that setting combined with`"editor.fontSize": 13` but this doesn't affect the issue.

**Comment by joaomoreno** [comment]
How did you get that `Fix this semi problem, Fix all auto-fixable problems` thing? Which extension gives you that?

@jrieken Is this the lightbulb, which is implemented as a native menu?

**Comment by jrieken** [comment]
Closing as obsolete because since 1.7.0 we use the native context menu for code actions

**Comment by darkred** [comment]
[**@joaomoreno**](https://github.com/joaomoreno) commented on [Oct 31, 2016, 10:52 AM GMT+2](https://github.com/Microsoft/vscode/issues/14721#issuecomment-257241976 "2016-10-31T08:52:50Z - Replied by Github Reply Comments"):
> How did you get that `Fix this semi problem, Fix all auto-fixable problems` thing? Which extension gives you that?
> 
> [@jrieken](https://github.com/jrieken) Is this the lightbulb, which is implemented as a native menu?
vscode-eslint.

I'm glad it's fixed!
