### ISSUE TITLE
go.testEnvVars not working as expected

### ISSUE THREAD

**Issue by marcami** [microsoft/vscode#147277]
Issue Type: <b>Bug</b>

1.  Add go.testEnvVars to settings.json in VSCode
     {
    "window.zoomLevel": 1,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "go.toolsManagement.autoUpdate": true,
    "azureFunctions.showCoreToolsWarning": false,
    "go.testEnvVars": {
        "ABC": "123"
    }
}
2. Create Go test program that prints environment variable "ABC"
    fmt.Println(os.Getenv("ABC"))
3.  I was expecting "123" to be printed, but I got an empty string "" instead
 

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (6.00GB free)|
|Process Argv|--crash-reporter-id b609df02-2135-4a50-9a41-b21fdb27ec3a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
go|gol|0.32.0
terraform|has|2.21.0
vscode-azurefunctions|ms-|1.6.1
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.21.0
remote-containers|ms-|0.231.5
azure-account|ms-|0.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by deepak1556** [comment]
This seems to be an issue with the go extension, please report it in their issue tracker https://github.com/golang/vscode-go. This issue tracker is only for vscode core related issues.
