### ISSUE TITLE
Unsatisfiable when-clause is ignored, command is shown anyways

### ISSUE THREAD

**Issue by EmilDamsbo** [microsoft/vscode#147202]
I am working on an extension, which should have a command which is not available in the command palette, but accessible through the context menu. However, when I build my extension the command is shown in the command palette: I have the following package.json;

```
{
    "name": "testextension",
    "version": "1.0.0",
    "publisher": "Myself",
    "engines": {
        "vscode": "^1.60.0"
    },
    "contributes": {
        "commands": [
            {
                "title": "MyCommand",
                "command": "testext.domycommand",
                "category": "test",
                "when": "0 == 1"
            }
        ],
        "explorer/context": [
                {
                    "when": "resourceExtname == .zip && !inDebugMode",
                    "command": "testext.domycommand",
                    "group": "navigation"
                }
        ]
    }
}
```

It should be evident that `"when": "0 == 1"` is not satisfiable, however I am still seeing the command in the command palette. Is this a known issue and is there a mitigation or fix available?

This also happens with `"when": "false"`.

**Comment by lewisl9029** [comment]
Also seeing this for my extension on the latest insider and stable:

Version: 1.67.0-insider (system setup)
Commit: 27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee
Date: 2022-04-12T18:38:45.140Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

Version: 1.66.2 (system setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by EmilDamsbo** [comment]
@alexdima I was wondering if there are current plans to fix this? This is frustrating to work around.

**Comment by EmilDamsbo** [comment]
Okay so I see what had happened, my problem was actually a case of 2 things which I had not accounted for in my example:

- I had 2 commands with very similar names, say cmd1 and cmd2. cmd1 was listed explicitly in contributes.menus.commandPalette, cmd2 was not but apparently items in contributes.commands surface to the palette anyway so I was seeing cmd1 and cmd2
- Because cmd2 was not explicitly listed in contributes.menus.commandPalette, and "when" does not apply to items in contributes.commands, the condition was not being followed

Is the implicit surfacing from contributes.commands to the command palette documented anywhere? If not, I suggest improving the docs, otherwise my issue is resolved without need for further action.
