### ISSUE TITLE
Finalize "simpleUI" debug option

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147264]
Added in https://github.com/microsoft/vscode/issues/128588

```ts
	export interface DebugSessionOptions {

		debugUI?: {
			/**
			 * When true, the debug toolbar will not be shown for this session, the window statusbar color will not be changed, and the debug viewlet will not be automatically revealed.
			 */
			simple?: boolean;
		};
```

Allows to start a debug session which has the debug UI hidden by default. Used for jupyter's Run By Line, and could be useful for other extensions starting atypical-style debug experiences.

**Comment by mjbvz** [comment]
Anything holding back this from finalization @roblourens?

**Comment by roblourens** [comment]
No. Could discuss it next month

**Comment by mjbvz** [comment]
Moving this to July based on discussions from last week

**Comment by jrieken** [comment]
Maybe inside `debugUI` into `DebugSessionOptions`, like the `compact` property and other?

**Comment by roblourens** [comment]
The only thing that bugs me is flooding DebugSessionOptions with a bunch of properties that feel sort of different from the others, and probably won't be commonly used... but I don't have a strong opinion about it

**Comment by jrieken** [comment]
```
suppressDebugToolbar?: boolean;
suppressDebugStatusbar?: boolean;
suppressDebugView?: boolean;
```
