### ISSUE TITLE
workbench.desktop.main.js:3100 Extension host (LocalProcess) terminated unexpectedly. Code: 3758096423, Signal: null

### ISSUE THREAD

**Issue by harry-ezratty** [microsoft/vscode#147210]
On my work machine, Windows 10, using Python/Pylance, I'm no longer able to start the Python interpreter
[vscode-app-1649395093425.log](https://github.com/microsoft/vscode/files/8448893/vscode-app-1649395093425.log)
 in VS code. Happened suddenly last night, I can't identify what triggered it. I don't think it coincided with an update or settings change or anything like that. Incidentally, workmachine is prohibited from visiting github urls, so if there's any automatic debugging info that should be included when submitting from the in-app help menu, please let me know, I will add it manually.

Things I've tried so far: 

1. Opening different projects: same issue
2. Opening WSL projects: same issue
3. Uninstalling and reinstalling Python and Pylance Extension: same issue
4. Restarting machine: same issue
5. Checking my personal which has settings sync on, so might be affected as well: no issue observed on personal machine
6. Starting from command line with --disable-extensions flag: Despite python & pylance being disabled, the extensions host still crashes.
7. Reinstalling VS code: it worked, but i didn't want to loose my settings, so once settings sync was turned back on, issue returned. I didn't get a chance to try reinstalling the Python & pylance extensions from scratch, would prefer to avoid if possible

Please let me know if there are additional logs or info I can provide or any suggestions you may have for me. 

Thanks!

**Comment by alexr00** [comment]
> but i didn't want to loose my settings, so once settings sync was turned back on, issue returned.

@sandy081 it looks like all extensions are disabled and the extension host crashes when setting sync is turned on.

**Comment by harry-ezratty** [comment]
@alexr00 Hi, hopefully the following info could be helpful: 

With settings sync turned back on after reinstalling, if I run code --disable-extensions, I'm still getting the same problem of the extensions host crashing.

I downloaded the nightly insiders build and installed only python and pylance extensions (no settings sync) and have no issues in there (though performance seems a little degraded relative to regular build before this issue started). 

So I think it's some interaction between something in my settings and something on that PC (because it's not happening on other PCs where settings sync is turned on) Maybe I can provide a dump of my settings?

**Comment by sandy081** [comment]
Settings Sync will synchronise your data from one machine to another machine. Not sure how this can cause the crash. Assigning to @alexdima for analysing the ext host crash.

**Comment by harry-ezratty** [comment]
Sorry, have been busy this week, haven't had a chance to update. I just wanted to inform that I confirmed that I'm getting the same error even if I fresh install vs code and don't turn on settings sync.

I have not seen this issue in the nightly insiders build for some reason

**Comment by alexdima** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
