### ISSUE TITLE
Adware to upgrade power shell and cluttered terminal for python output.

### ISSUE THREAD

**Issue by Defcon404** [microsoft/vscode#147271]
Issue Type: <b>Feature Request</b>

Hello,

Everytime I run terminal in vs code, I see  a comment informing me to upgrade to latest version of power shell. I am not interested and its irritating to see the information pop into my vs code terminal every time i launch my vs code. Please do something.

Also when I run my python scripts in the vs code terminal, I see a long unnecesary links along with the python output which clutters the terminal. Even after disabling Breadcrumbs and show links option, I see this. Please Please do some thin about this. All we want to see in the terminal is our python output and not anything else.

Thank You for the support.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by meganrogge** [comment]
> Everytime I run terminal in vs code, I see a comment informing me to upgrade to latest version of power shell

This is coming from pwsh, not us

> Also when I run my python scripts in the vs code terminal, I see a long unnecesary links along with the python output which clutters the terminal

Also not vscode causing this
