### ISSUE TITLE
[Accessibility] Consider adding audio cues for diffs (added / deleted code)

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#147226]
CC @isidorn and @hediet

It would be so much nicer if screen reader users could hear any unique audio cues for added and deleted lines when comparing git diffs. Currently, it is only possible by tediously reviewing plus (+) and minus (-) signs.

**Comment by isidorn** [comment]
@jooyoungseo so your suggestion is to have two different sounds. One for an added line, and one for a deleted line. Right?

I think this makes sense. I suggest that we leave this open for now and we can add it in the future.

fyi @gino-scarpino

**Comment by gino-scarpino** [comment]
Cool idea. I also hear your tonal logic for add and delete. Will add to the backlog. Thanks!

**Comment by jooyoungseo** [comment]
@gino-scarpino and @isidorn -- I know you are already swamped with other prioirity work, but I was wondering if you had any specifically planned milestone for this feature.

These days, I have seen many discussions and concerns about accessible git diffs among blind programmers in the program-l listserv. Although F7/Shift+F7, Alt+F5/Shift+Alt+F5 are very instrumental, having more discernable and discoverable audio tones would be much more accessible. A related issue (#88695) filed few years ago by another screen reader user also suggested this idea using sounds for diffs, but audio cues were not supported in VSCode back then. #152511, while it's closed, also reveals the discoverability challenges of diff accessibility features among screen reader users.

Given that VSCode audio cues are highly appreciated by many blind programmers recently, I believe it is the right timing to introduce this feature for diffs. I also believe this addition would be potentially helpful for sighted users as well (see #15371).

**Comment by isidorn** [comment]
@jooyoungseo great feedback thanks!
@meganrogge I think this is one of the features we should look into in November or December milestones. Assigning also to you and we can discuss more.

**Comment by meganrogge** [comment]
@AFre100 could you pls add these sounds to the vscode repo?

**Comment by AFre100** [comment]
@meganrogge  Yes! We have Diff sounds for VS Windows that are shipped. Sent via chat.

**Comment by meganrogge** [comment]
One interesting thing about this is the cursor skips over deleted lines in the diff view. So we can play the diff deleted cue on the line above or below the deletion perhaps?

**Comment by AFre100** [comment]
For some reason Git won't let me view this on the site even though I'm
logged in. Anyways, I've been testing and trying to trigger sounds in VSC
and VS. I made a python file to test sounds as a template where anyone
can click around to listen to playback while experiencing the actual
interaction. Been gathering footage as well, of interactions.

Any chance you could record your screen (w/its audio) of this issue and
show me?

**Comment by meganrogge** [comment]
@jooyoungseo from what I see, the `DiffReview` editor has only two states - lines added and deleted.

When I modify a line, in the editor, I see one line deleted and one added.

**Comment by jooyoungseo** [comment]
Thanks for your prompt reply, @meganrogge. I guess that happens within DiffReview pane (F7/Shift+F7). However, what does happen in editor? You know, you can jump between changes by pressing Alt+F5 and Alt+Shift+F5 in editor. Do we hear audio cues for modified lines there?

**Comment by meganrogge** [comment]
@jooyoungseo I don't think there are audio cues for the normal editor corresponding to the git decorations.

I looked into implementing them there when I initially started this work bc didn't realize the request was for the diff review editor and it seems more involved, but doable

**Comment by jooyoungseo** [comment]
@meganrogge  It would be greatly appreciated if the diff audio cues could be triggered in normal editor as well b/c there's no semantic clues for screen readers for this in the editor besides the explicit DiffReview (F7) call. If I return to my suggestions above, there might be three cases representing changes in normal editor: added, deleted, and modified lines. I was suggesting adding one more audio cue indicating the modified line; otherwise, we may hear both deleted and added audio cues simultaneously, which may not that obvious. What do you think?

**Comment by meganrogge** [comment]
Hey @jooyoungseo yes that makes sense and I agree with that approach for the normal editors. 

My linked PR will only fix this for diff review mode/editors - in which there is no such thing as a modified state. 

I can consider working on this for normal editors in the coming iterations

**Comment by meganrogge** [comment]
@AFre100 I'm not sure what you are asking

**Comment by jooyoungseo** [comment]
@meganrogge -- After updating to the latest insider build, all the audio cues stopped working.

Version: 1.74.0-insider (system setup)
Commit: d9a70c4236a8bde4fe7435df3ecdd333c7bc939c
Date: 2022-11-17T05:26:03.777Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by AFre100** [comment]
@meganrogge <https://github.com/meganrogge>  Ah yes, was asking -- if
you're already testing these interactions in VSC, could you record your
screen and send it to me? Just want to make sure I'm aligned with what
you're describing...If you've moved on though, no worries!

**Comment by meganrogge** [comment]
@jooyoungseo it would be great if you could verify that this feature works for you today in insiders

**Comment by jooyoungseo** [comment]
@meganrogge Yes, verified. It works nicely. Thanks!
