### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by Medkhat** [microsoft/vscode#147282]
Hi, big thank you for the cool code editor)) I have a small issue, when I press CTRL+R, this functionality doesn't work. Always I see on the bottom message such as below:
"(Ctrl+R) was pressed. Waiting for second key of chord"

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Most likely this is some extension that provides these shortcuts, e.g. #60711

**Comment by ngahika01** [comment]
Was originating from git extension pack and the project manager. Fixed it. Thanks @IllusionMH

**Comment by Medkhat** [comment]
> /needsMoreInfo
> 
> Is it reproducible with all extensions disabled? You can try this with F1 and `>Developer: Reload Window With Extensions Disabled`
> 
> Most likely this is some extension that provides these shortcuts, e.g. #60711

Yes, I have installed the npm extension from Microsoft)) Fixed! Thanks!
