### ISSUE TITLE
output's font settings for Jupyter notebook

### ISSUE THREAD

**Issue by alexhtwen** [microsoft/vscode#147243]
Issue Type: <b>Feature Request</b>

Would it be possible to add the following font settings for Jupyter Notebook editor?
* "notebook.output.fontFamily"
*  "notebook.output.fontSize"
* "notebook.output.color"
*  "notebook.output.backgroundColor"
* "notebook.output.lineHeight"
* ...

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.13.0-39-generic
Restricted Mode: No

**Comment by amunger** [comment]
We have recently implemented 3 of these settings in insiders

```
notebook.outputLineHeight
notebook.outputFontSize
notebook.outputFontFamily
```

**Comment by alexhtwen** [comment]
I appreciate your efforts.

**Comment by amunger** [comment]
I have split out the remaining requests into https://github.com/microsoft/vscode/issues/148822 since over half of these settings were implemented (and very soon to be released). Please update that other issue and add any comments for other settings that might be useful
