### ISSUE TITLE
Font weight is different between Light and Dark themes with ALL fonts and ALL themes

### ISSUE THREAD

**Issue by maximo-torterolo-ambrosini** [microsoft/vscode#147265]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66
- OS Version: Windows 10 64bits

Steps to Reproduce:

1. Select a dark theme
2. Watch the weight of the font you're using
3. Switch to a light theme
4. You'll realise that the font weight is slightly different

Dark theme, font weight preview:
![Dark theme](https://i.imgur.com/7N6il6p.png)

Light theme, font weight preview:
![Light theme](https://i.imgur.com/cNqC13H.png)

**Comment by maximo-torterolo-ambrosini** [comment]
Found out this is caused by the next config in my settings.json

When I set the font style to italic it makes it italic and slightly bolder on dark themes for some reason.

```json
"editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": [
                    //following will be in italic (=FlottFlott)
                    "comment",
                    "entity.name.type.class", //class names
                    "keyword", //import, export, return…
                    "constant", //String, Number, Boolean…, this, super
                    "storage.modifier", //static keyword
                    "storage.type.class.js", //class keyword
                    // "entity.name.type",
                    "entity.name.function", // Func
                    "constant.other.placeholder",
                    "storage"
                ],
                "settings": {
                    "fontStyle": "italic",
                },
            },
        ]
},
```

I guess this shouldn't happen right?

**Comment by rzhao271** [comment]
Hi @maximo-torterolo-ambrosini 
I'm wondering whether this problem started in the newest version of VS Code, or if it's been there since a previous version?
Also, what font family are you using in this case? Does the problem still occur if you don't style the font as italic?

**Comment by maximo-torterolo-ambrosini** [comment]
The problem was in previous versions but I've never reported it. I'm using Cascadia Code but it happens with JetBrains Mono and Fira Code (I tested it with those 3 only). And yes, if you style the font as bold it has more weight in dark themes than light ones, I can add another screenshot if you want.

**Comment by rzhao271** [comment]
I believe I have confirmed your issue, but after taking a screenshot, I noticed that the difference in appearance could be from the subpixel rendering.

![Two lines saying abcdefghijkl in Cascadia Code bold. The first one is in light theme and seems to have BGR subpixel rendering. The second one is in dark theme and seems to have RGB subpixel rendering.](https://user-images.githubusercontent.com/7199958/163836625-0e24fc9f-8ce0-4fa7-8c0d-e623276953ed.PNG)

**Comment by maximo-torterolo-ambrosini** [comment]
Good to hear that I'm not the only one with this issue, honestly I thinks this was a problem from my Vs Code and not in general. Should I close the issue or you'll close it later when is fixed?

**Comment by maximo-torterolo-ambrosini** [comment]
Good to hear that I'm not the only one with this issue, honestly I thought this was a problem from my Vs Code and not in general. Should I close the issue or you'll close it later when is fixed?

**Comment by rzhao271** [comment]
Hi again, I currently wonder whether what we're seeing is an optical illusion?
For example, when I use Cascadia Code bold, it looks like the lowercase e is bolder on a darker theme than on a lighter theme. But, when I tried measuring the pixels, they were the same size.
Here is a screenshot demonstrating the phenomenon:
![A screenshot showing that though the white-on-black text seems bolder than the black-on-white text from a distance, especially for the lowercase e, when zoomed in and measured, it turns out they are about the same size](https://user-images.githubusercontent.com/7199958/164532038-0659fda8-dc15-49cd-90f8-95938d14f035.PNG)

**Comment by maximo-torterolo-ambrosini** [comment]
Hi Raymond, taking advantage of your example with the 'e' letter I can clearly see that the gap between the e tail and its head is significantly bigger. Is this because the last example is in bold and the previous one no? I think that bold weights don't affect font size but indeed its thickness.

![Example](https://i.imgur.com/AgEMzjA.png)

**Comment by rzhao271** [comment]
Both samples are using Cascadia Code bold. In your example, you're measuring the two gaps differently. Here's another screenshot showing the gaps are the same:

![A screenshot showing the two lowercase e's have the same gaps between the head and tail](https://user-images.githubusercontent.com/7199958/164542171-6f99b6fd-9c18-46b6-a787-585df0e06102.PNG)

**Comment by maximo-torterolo-ambrosini** [comment]
You're right, I noticed that. I tried inverting the phot, if you see it well, at the end of the tail of the e there are missing some blue pixels, I believe that those missing ones affects the perception of the weight.

![](https://i.imgur.com/x7CrEal.png)

**Comment by rzhao271** [comment]
Your inversion shows that the red and blue tints used for the subpixel rendering are not direct complementary colours to each other.
Please file an issue for the apparent font weight difference with Chromium instead: https://bugs.chromium.org/
