### ISSUE TITLE
Go to defination not working

### ISSUE THREAD

**Issue by jaydip-9548** [microsoft/vscode#147295]
Issue Type: <b>Performance Issue</b>

Go to defination not working with F12 keyword or ctrl + click combination.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:51:26.173Z)
OS version: Linux x64 5.13.0-39-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.46GB (9.09GB free)|
|Process Argv|--unity-launch --crash-reporter-id 824d9916-39cf-4aaf-b03f-f19404a60d94|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   142	 10466	code main
    0	    32	 10471	   zygote
    0	   111	 10505	     gpu-process
    0	    32	 10472	   zygote
    0	     0	 10474	     zygote
    0	    79	 11151	       issue-reporter
    0	    47	 10514	   utility-network-service
    0	   222	 10532	   window (views.py - entropy - Visual Studio Code)
    0	   127	 10569	   shared-process
    0	    63	 10598	     ptyHost
    0	     0	 10681	       /usr/bin/bash
    0	     0	 10688	       /usr/bin/bash
    0	     0	 10695	       /usr/bin/bash
    0	     0	 10702	       /usr/bin/bash
    0	   111	 10640	     fileWatcher
    0	     0	 11171	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 11172	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   174	 10583	   extensionHost
    0	    79	 10711	     /usr/share/code/code --ms-enable-electron-run-as-node /home/fx/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js --node-ipc --clientProcessId=10583
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (views.py - entropy - Visual Studio Code)
|    Folder (entropy): more than 22660 files
|      File types: gz(8091) py(2365) pyc(2274) json(894) mo(754) po(754)
|                  tsx(243) ts(222) txt(127) less(123)
|      Conf files: dockerfile(4) package.json(2) github-actions(1)
|                  settings.json(1) jsconfig.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
bracket-pair-colorizer-2|Coe|0.2.4
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.5.0
vscode-pull-request-github|Git|0.40.0
python|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
material-icon-theme|PKi|4.15.0
LiveServer|rit|5.7.5
code-spell-checker|str|2.1.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by yiliang114** [comment]
The same problem. Go to defination not working in all language,  maybe the main reason is `tsconfig.json` has been moved to `src` from root. @mjbvz

**Comment by jaydip-9548** [comment]
I am using python with djnago and django-rest framework.
Go to definition not working with ctrl + click and F12 key.

What should i do ?
