### ISSUE TITLE
insiders version need to restart twice to upgrade

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#147206]
When there is a insiders version update, I `cmd + q` to upgrade it.
But after I restart vscode, there is still a upgrade notice, so I restart again.
After twice restart, I can upgrade to latest version without the upgrade notice.

My expected behavier is that I need only one retsart to upgrade to latest version.

Versions: 

```
MacOS: 12.3.1
VSCode: 1.67.0-insider
```

**Comment by joaomoreno** [comment]
This often happens if we ship a new version while your Code already has a pending update. There's no way to stop an update once it hits the "pending" state. So you're going to go through a second update notification in that case.
