### ISSUE TITLE
 Cannot read property 'parameters' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#14738]
Issue Id: <b>a98217aa-d553-ce26-e3a3-32aa1b16c7b2</b><br /><br />*Versions* <br />- 1.7.0-insider (10/28/2016 1:02:33 PM)<br />*Stack* <br />TypeError: Cannot read property 'parameters' of undefined<br />[/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L300:34 (parameters)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L300:34 (parameters))<br />[/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L195:8 (render)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L195:8 (render))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L101:17 (fire)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/editor/contrib/parameterHints/browser/parameterHintsWidget.ts#L101:17 (fire))<br />[/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/0706b425537d8cfe2766eac00662ecf988c7ed7f/src/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />

**Comment by ramya-rao-a** [comment]
@joaomoreno This wouldnt have made 1.7.1 correct?

**Comment by joaomoreno** [comment]
Nope.

```
vscode master $ git tag --contains 963435d
translation/20161111.01
```
