### ISSUE TITLE
Discard all open terminals on exit

### ISSUE THREAD

**Issue by SkryptX** [microsoft/vscode#147366]
As far as my research goes, there is no way to completely discard every open terminal on exit and start without any terminals open.

My use case is this: I want to edit text documents with as much screen space as possible and I will never need a terminal for that. What I do have is a custom task I irregularly execute to build some artifacts. This task opens a terminal and prints some temporary debugging output. So a terminal gets opened once I need it. What now happens is, that when I reload vscode a generic and frankly useless powershell window gets opened, because it thinks I opened a terminal in the session before and I surely want a terminal again. So I have to close a Powershell window every time I open VSCode.

The solution would be to have a setting, which does exactly as the title says: Discard every terminal upon exit, which also disables all the session restore and so on.

**Comment by meganrogge** [comment]
can you attach a screen shot of what happens when you try this with `terminal.integrated.enablePersistentSessions: false`?

**Comment by SkryptX** [comment]
Sorry I didn't respond for so long.

I prepared a .code-workspace file so you can try it out yourself:
```
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {
		"terminal.integrated.enablePersistentSessions": false
	},
	"tasks": {
		"version": "2.0.0",
		"linux": {
			"options": {
				"shell": {
					"executable": "bash",
					"args": [
						"-c"
					]
				}
			},
		},
		"windows": {
			"options": {
				"shell": {
					"executable": "powershell.exe"
				}
			},
		},
		"presentation": {
			"echo": false,
			"group": "test",
			"reveal": "always",
			"focus": false,
			"panel": "shared",
			"showReuseMessage": false,
			"clear": true
		},
		"tasks": [
			{
				"label": "Test",
				"type": "shell",
				"windows": {
					"command": "Get-Date"
				},
				"linux": {
					"command": "date"
				},
				"problemMatcher": []
			},
		]
	}
}
```

**Steps to reproduce**
1. Create this .code-workspace file
2. Place it in an empty folder
3. Open it and close all the terminals
4. Execute this random task (works on Windows and Linux)
5. Close Visual Studio Code
6. Open Visual Studio Code
7. There should now be an empty terminal waiting for you

I hope this better illustrates my problem than some confusing description 😊
