### ISSUE TITLE
Can't save Jupyter Notebook

### ISSUE THREAD

**Issue by buth11** [microsoft/vscode#147307]
Issue Type: <b>Bug</b>

Like in title just can't save Jupyter Notebook.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (7.30GB free)|
|Process Argv|--crash-reporter-id b091b8eb-d25b-4f90-bdc2-abf30627e321|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
vscode-great-icons|emm|2.1.86
hungry-delete|jas|1.6.0
vscode-language-pack-pl|MS-|1.66.2
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
powershell|ms-|2021.12.0
code-spell-checker|str|2.1.11
code-spell-checker-polish|str|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by rebornix** [comment]
@buth11 it would be great if you can share more info of what you were seeing when this happened, a screen recording works the best, thanks in advance!

**Comment by buth11** [comment]
Video doesn't have a 'Save as' window, I tried with every
extension(.ipynb.json, .ipynb, .json) none of them worked. Always same
error like on video.
 Obecnosci - Visual Studio Code 2022-04-12 20-51...
<https://drive.google.com/file/d/1nFFbXlKQmD1GBIw-ZLstpgPOBs87w2g5/view?usp=drive_web>

**Comment by buth11** [comment]
https://drive.google.com/file/d/1veTPulbrg7ILjhcc0RZLu3GsQjcinVRH/view?usp=sharing

**Comment by buth11** [comment]
https://drive.google.com/file/d/1veTPulbrg7ILjhcc0RZLu3GsQjcinVRH/view?usp=sharing

**Comment by ragdollfun** [comment]
I experience a similar issue where, on creation, Jupyter Notebooks aren't treated as a separate file type by vscode who tries to save them with a JSON file extension:

![Screenshot 2022-04-17 115133](https://user-images.githubusercontent.com/68953298/163710315-7ff03f3b-f063-4599-8551-9103898cc07f.png)

**Comment by ragdollfun** [comment]
This can easily be reproduced with a fresh install of vscode with only the Jupyter extension by Microsoft loaded.

From the "Get Started" tab, select "New File...", then click on "Jupyter Notebook .ipynb support", then try to save the notebook (with Ctrl+S or through File -> Save), choose a name and location for your file in the pop-up window, click on "Save" and you'll get this exact error.

Btw, this didn't use to happen on earlier versions of vscode.

**Comment by rebornix** [comment]
This should be fixed now in VS Code Insiders.

**Comment by ragdollfun** [comment]
When can we expect the fix to reach the stable release ?
