### ISSUE TITLE
Error when I run an automation task using the terminal cmd.exe

### ISSUE THREAD

**Issue by hugotom** [Microsoft/vscode#14736]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.18, akamud.vscode-caniuse-0.5.3, alefragnani.project-manager-0.12.0, alexdima.copy-relative-path-0.0.1, andreaskian.vscode-select-line-0.0.3, bogdan-sinitsa.theme-dark-monokai-0.3.0, christian-kohler.path-intellisense-1.1.0, cmstead.jsrefactor-0.5.3, donjayamanne.bower-0.0.3, donjayamanne.jquerysnippets-0.0.1, donjayamanne.listFiles-0.0.3, HookyQR.beautify-0.5.3, jakelucas.code-select-until-0.6.0, lukasz-wronski.ftp-sync-0.3.1, ms-vscode.cpptools-0.9.2, qinjia.view-in-browser-0.0.3, robertohuertasm.vscode-icons-3.0.7, Shan.code-settings-sync-2.3.3, Tyriar.lorem-ipsum-1.0.0, wcwhitehead.bootstrap-3-snippets-0.0.7

Steps to Reproduce:

1. When an automation task is executed using the terminal.

2. For example less to css compiling, in this case I'm using less-watch-compiler (npm package https://github.com/jonycheung/deadsimple-less-watch-compiler):

{[Error: Command failed: C: \ WINDOWS \ system32 \ cmd.exe / s / c "lessc -x less / bootstrap.less> css / bootstrap.css"
The process can not access the file Because it is being used by another process.
]
  Killed: false,
  code: 1,
  signal: null,
  cmd: 'C: \\ WINDOWS \\ system32 \\ cmd.exe / s / c "lessc -x less / bootstrap.less> css / bootstrap.css"'}

If it works and compiles, but not because it tells me that error. I've tried other npm package and always tells me error.

![sin titulo-1](https://cloud.githubusercontent.com/assets/2887985/19847063/fe893c0c-9f11-11e6-897d-ca7eaa10fa17.jpg)

**Comment by dbaeumer** [comment]
@hugotom the problem is that the output file  bootstrap.css is used by another process hence the less -> css compiler can't write the file. Do you have another tool open that consumes bootstrap.css. Some server ? There is little VS Code can do about this. Under windows you can use https://technet.microsoft.com/en-us/sysinternals/handle.aspx to find out who is holding a write lock on bootstrap.css and therefore blocking updating the fine.
