### ISSUE TITLE
Web API exposes both `getUriScheme` and `uriScheme`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147368]
I think the `getUriScheme` can be dropped?

**Comment by joaomoreno** [comment]
> not sure. we don't expose uriScheme on our API at all: https://github.com/microsoft/vscode-dev/blob/6087d66d848190e5faa0a13a7d4c0f3b64ffa637/common/typings/workbench.api.d.ts
> because our API create function just returns a disposable... not the workbench itself
