### ISSUE TITLE
Terminal display problem

### ISSUE THREAD

**Issue by veryneo** [microsoft/vscode#147390]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.2
- OS Version:Ubuntu 18.04.6

Hello, I met a problem which showed in the following picture in the use of terminal.
![微信截图_20220413222417](https://user-images.githubusercontent.com/57743569/163202473-7233241a-d41f-453b-b6ee-e1aadd0b6b97.png)
In the first line, the characters and symbols display normally.
But after that, some of them get something wrong. They can not display completely.
Can you tell me how can l solve this.
Thanks!!!

**Comment by meganrogge** [comment]
Please provide a [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal

**Comment by TarynChambers** [comment]
I'm having same issue as OP.
![image](https://user-images.githubusercontent.com/10948165/163254068-45e37469-7eb6-44d2-8fce-1b21f13b60fe.png)

vs code version: 1.66.2
OS Version: Ubuntu 20.04.4 LTS

I think it used to show the path in the terminal too?

**Comment by veryneo** [comment]
> I'm having same issue as OP. ![image](https://user-images.githubusercontent.com/10948165/163254068-45e37469-7eb6-44d2-8fce-1b21f13b60fe.png)
> 
> vs code version: 1.66.2 OS Version: Ubuntu 20.04.4 LTS
> 
> I think it used to show the path in the terminal too?

I find the solution.
Turn off the Integrated: Gpu Acceleration
![微信截图_20220414092735](https://user-images.githubusercontent.com/57743569/163295986-e130f9b7-f3b0-4d68-a307-341230e90f2a.png)

**Comment by meganrogge** [comment]
Looks like a problem with Chromium GPU acceleration in canvas/linux, you can try updating your graphics driver and if that doesn't work you can move to the DOM-based renderer with this setting:
"terminal.integrated.rendererType": "dom"
/label terminal terminal-rendering *question

**Comment by tiansin** [comment]
> 

The latest version does not have this setting.

**Comment by Tyriar** [comment]
@tiansin it's been changed to `terminal.integrated.gpuAcceleration`
