### ISSUE TITLE
VS Code thinks Html tag < and > is a special character 

### ISSUE THREAD

**Issue by gadgetcrawford** [microsoft/vscode#147334]
I am creating a webpack. In template.html, I have a line of code like this:
<title><%= htmlWebpackPlugin.options.title %></title>

In wsl, IT is saying the opening and closing brackets <% ... %> needs to be escaped as it is a special character.

![error](https://user-images.githubusercontent.com/31297763/163080045-bbdd82eb-8305-4a5c-b903-f9f5c20bacd1.png)

Does this issue occur when all extensions are disabled?: 
I have disabled every extension, ad I am still getting the error.

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?:
> Im not disabling all my extensions just to check.

I suggest you try using the Start Extension Bisect command from the Command Palette. This will begin by temporarily disabling all non-builtin extensions, reloading the window, and asking you if the issue remains. If you say no it will re-enable half and reload again, etc. At any point you can end the bisect and all your previously enabled extensions will be back.
