### ISSUE TITLE
something wrong with inno_updater.exe

### ISSUE THREAD

**Issue by Zhang-kg** [microsoft/vscode#147362]
Issue Type: <b>Bug</b>

Click on "Check for updates" in the bottom left “gear”, or start the program to run automatic updates. A prompt will appear - "An error occurred while inno_updater.exe was trying to create a file in the target directory: access denied..."

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.34GB free)|
|Process Argv|--crash-reporter-id d4ee7239-d6c5-44bf-b0f4-8a50fe3be73e|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
code-runner|for|0.11.7
better-cpp-syntax|jef|1.15.13
mips|kda|0.0.9
asm-code-lens|maz|1.10.2
vscode-language-pack-zh-hans|MS-|1.66.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.5
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
veriloghdl|msh|1.5.3
java|red|1.4.0
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.18
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
markdown-all-in-one|yzh|3.4.0
linkerscript|Zix|1.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by joaomoreno** [comment]
In which location is VS Code installed? Can you uninstall and reinstall VS Code?

**Comment by hideaki-t** [comment]
this may be useless information ,but I had a similar or the same issue.

I installed VS Code 1.66.1 in `AppData\Local\Programs\Microsoft VS Code`.
I got an access denied message when tried to update. I don't remember the entire message, but I remember it was about unins000.exe and access denied.

I even couldn't uninstall VS Code a user, got access denied for unins000.dat. so I did "Run as administrator" unins000.exe then I could run the uninstaller. I noticed that the uninstall left some files in `Microsoft VS Code`.
next, I tried to run `VSCodeUserSetup-x64-1.66.2.exe` to install it in the same place, then it also got the access denied.
I moved `Microsoft VS Code` folder to somewhere, and finally could install VS Code using the installer.

**Comment by PaulskPt** [comment]
Same problem here. Every time I exit VSCode I see this popup in the upper left corner of the MS Windows 11 Pro desktop. It contains an empty progress bar. It hangs. If I right-click on the VSCicon on the taskbar to stop it I am presented a popup window with an error.

**Comment by RyanHill-MSFT** [comment]
Same issue here. The error message received is `Opening file hande: "%APP_DATA%\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js": Failed to create file handle: Access is denied. Please verify there are no Visual Studio Code processes still executing"

Below is the stack from procmon for that CreateFile event.

```
0	FLTMGR.SYS	FltGetFileNameInformation + 0x1f1b	0xfffff8021831939b	C:\WINDOWS\System32\drivers\FLTMGR.SYS
1	FLTMGR.SYS	FltGetFileNameInformation + 0x19a1	0xfffff80218318e21	C:\WINDOWS\System32\drivers\FLTMGR.SYS
2	FLTMGR.SYS	FltGetFileNameInformationUnsafe + 0x16ef	0xfffff8021834efdf	C:\WINDOWS\System32\drivers\FLTMGR.SYS
3	ntoskrnl.exe	IofCallDriver + 0x55	0xfffff80219e0e015	C:\WINDOWS\system32\ntoskrnl.exe
4	ntoskrnl.exe	RtlValidAcl + 0x5033	0xfffff8021a2c30f3	C:\WINDOWS\system32\ntoskrnl.exe
5	ntoskrnl.exe	ObOpenObjectByNameEx + 0x1245	0xfffff8021a2ce575	C:\WINDOWS\system32\ntoskrnl.exe
6	ntoskrnl.exe	ObOpenObjectByNameEx + 0x1f2	0xfffff8021a2cd522	C:\WINDOWS\system32\ntoskrnl.exe
7	ntoskrnl.exe	NtCreateFile + 0xb99	0xfffff8021a334519	C:\WINDOWS\system32\ntoskrnl.exe
8	ntoskrnl.exe	NtCreateFile + 0x79	0xfffff8021a3339f9	C:\WINDOWS\system32\ntoskrnl.exe
9	ntoskrnl.exe	setjmpex + 0x82e5	0xfffff8021a038f65	C:\WINDOWS\system32\ntoskrnl.exe
10	ntdll.dll	NtCreateFile + 0x14	0x7ffe53d8f6e4	C:\WINDOWS\SYSTEM32\ntdll.dll
11	wow64.dll	RedirectDosPath + 0x21ca	0x7ffe51e95b1a	C:\WINDOWS\System32\wow64.dll
12	wow64.dll	Wow64SystemServiceEx + 0x164	0x7ffe51e97804	C:\WINDOWS\System32\wow64.dll
13	wow64cpu.dll	TurboDispatchJumpAddressEnd + 0xb	0x778617ba	C:\WINDOWS\System32\wow64cpu.dll
14	wow64cpu.dll	TurboDispatchJumpAddressEnd + 0x5c6	0x77861d75	C:\WINDOWS\System32\wow64cpu.dll
15	wow64.dll	Wow64KiUserCallbackDispatcher + 0x67d	0x7ffe51e9ea8d	C:\WINDOWS\System32\wow64.dll
16	wow64.dll	Wow64LdrpInitialize + 0x12d	0x7ffe51e9e18d	C:\WINDOWS\System32\wow64.dll
17	ntdll.dll	EtwLogTraceEvent + 0x2617e	0x7ffe53dc5c3e	C:\WINDOWS\SYSTEM32\ntdll.dll
18	ntdll.dll	EtwLogTraceEvent + 0x19f5e	0x7ffe53db9a1e	C:\WINDOWS\SYSTEM32\ntdll.dll
19	ntdll.dll	LdrInitializeThunk + 0xe3	0x7ffe53d63f23	C:\WINDOWS\SYSTEM32\ntdll.dll
20	ntdll.dll	LdrInitializeThunk + 0xe	0x7ffe53d63e4e	C:\WINDOWS\SYSTEM32\ntdll.dll
21	ntdll.dll	ZwCreateFile + 0xc	0x778e66fc	C:\WINDOWS\SysWOW64\ntdll.dll
22	KERNELBASE.dll	CreateFileW + 0x60f	0x75d2c7ff	C:\WINDOWS\SysWOW64\KERNELBASE.dll
23	KERNELBASE.dll	CreateFileW + 0x6e	0x75d2c25e	C:\WINDOWS\SysWOW64\KERNELBASE.dll
24	inno_updater.exe	inno_updater.exe + 0x417b9	0x3a17b9	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\tools\inno_updater.exe
25	inno_updater.exe	inno_updater.exe + 0xa070	0x36a070	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\tools\inno_updater.exe
26	inno_updater.exe	inno_updater.exe + 0xc497	0x36c497	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\tools\inno_updater.exe
27	inno_updater.exe	inno_updater.exe + 0x494b6	0x3a94b6	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\tools\inno_updater.exe
28	KERNEL32.DLL	BaseThreadInitThunk + 0x19	0x769a7ba9	C:\WINDOWS\SysWOW64\KERNEL32.DLL
29	ntdll.dll	RtlInitializeExceptionChain + 0x6b	0x778db7db	C:\WINDOWS\SysWOW64\ntdll.dll
30	ntdll.dll	RtlClearBits + 0xbf	0x778db75f	C:\WINDOWS\SysWOW64\ntdll.dll
```

I also did confirm that Code.exe issued a CloseFile before inno_update ran.

```
13:32:18.4298295	Code.exe	22080	ReadFile	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js	SUCCESS	Offset: 0, Length: 1,006, Priority: Normal
13:32:18.4306383	Code.exe	22080	CloseFile	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js	SUCCESS	
13:33:08.9223235	inno_updater.exe	11096	CreateFile	C:\Users\ryhill\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-amd.js	ACCESS DENIED	Desired Access: Read Attributes, Delete, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: None, AllocationSize: n/a
```

**Comment by joaomoreno** [comment]
Interesting. If you uninstall and reinstall, does the problem persist?

**Comment by PaulskPt** [comment]
I uninstalled and reinstalled. Problem gone

**Comment by RyanHill-MSFT** [comment]
Uninstalled and reinstalled worked for me as well. Just curious was to what led to the error in the first place.

**Comment by PaulskPt** [comment]
I don't know what led to the error.
