### ISSUE TITLE
go language parse error

### ISSUE THREAD

**Issue by rohan-rayaraddi** [microsoft/vscode#147326]
Issue Type: <b>Bug</b>

Say file f1 has a struct MyStruct on branch main. f1 was renamed to f2 in branch feature and then you checkout main branch, main shows an error than Mystruct is declared twice in f1 and f2, when infact f2 does not exist in the main branch

VS Code version: Code 1.66.0 (Universal) (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:04.419Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id 024ec871-2a39-4a15-a1d2-f323d13a6d9f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
githistory|don|0.6.19
gitlens|eam|12.0.6
vscode-pull-request-github|Git|0.40.0
go|gol|0.32.0
plantuml|jeb|2.17.2
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.21.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.5
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
vscaat:30438848
pynewfile477:30463512

```

</details>

**Comment by rzhao271** [comment]
Is this issue specific to the go extension? If so, you'll want to file an issue at https://github.com/golang/vscode-go.

**Comment by rohan-rayaraddi** [comment]
thanks, posted in vs-code-go https://github.com/golang/vscode-go/issues/2200
