### ISSUE TITLE
Bug in HTML document in VSS code

### ISSUE THREAD

**Issue by alexks123** [microsoft/vscode#147313]
When I open HTML document and scroll down, in one moment whole visual code program stop working. I tried to reinstall program, restart a computer, but it didtn help.

**Comment by ricahardHaggioGwati** [comment]
So the bug appears right after you open an Html document? Have you tried a different type of document, to see if it produces the same bug and they is also the <a href="https://code.visualstudio.com/insiders/">Insider Edition<a> of Visual Studio code, give that a shot? Can you share your system information as well?

**Comment by aeschli** [comment]
Did you run VS Code with all extension disabled?

**Comment by alexks123** [comment]
I solved the problem. Thank you for sure.

pon, 25. tra 2022. u 16:26 Martin Aeschlimann ***@***.***>
napisao je:
