### ISSUE TITLE
Cant open second instance

### ISSUE THREAD

**Issue by vieiraes** [microsoft/vscode#147347]
Issue Type: <b>Bug</b>

since Ive update i Cant open second instance runnind code . at terminal

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-39-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 3299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 3|
|Memory (System)|15.24GB (1.42GB free)|
|Process Argv|--unity-launch --crash-reporter-id e5229a3d-9a5f-4416-a44c-de629646612b|
|Screen Reader|yes|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
jest-snippets|and|1.8.0
gitlab-pipeline-monitor|bal|2.0.0
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
dart-code|Dar|3.38.2
vscode-eslint|dba|2.2.3
npm-browser|den|1.1.3
vscode-notes|dio|1.1.0
docs-images|doc|0.0.10
docs-yaml|doc|0.2.8
gitlens|eam|12.0.6
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
vscode-express-snippets|Exp|1.1.1
vscode-jest-runner|fir|0.4.48
auto-rename-tag|for|0.1.10
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
copilot-nightly|Git|1.12.5556
vscode-pull-request-github|Git|0.40.0
gitlab-workflow|Git|3.42.1
todo-tree|Gru|0.0.215
vscode-mocha-test-adapter|hbe|2.13.3
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
docker-linter|hen|0.5.0
rest-client|hum|0.24.6
vscode-postfix-ts|ipa|1.9.4
search-node-modules|jas|1.3.0
plantuml|jeb|2.17.2
vscode-peacock|joh|4.0.1
js-index|joo|0.3.5
vscode-dependency-cruiser|jua|0.0.1
solidity|Jua|0.0.138
vscode-jest-test-adapter|kav|0.8.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.21.0
kind-vscode|ms-|0.0.3
vscode-kubernetes-tools|ms-|1.3.7
vscode-postgresql|ms-|0.3.0
test-adapter-converter|ms-|0.1.6
vscode-typescript-next|ms-|4.7.20220408
vscode-json-editor|nic|0.3.0
vscode-extension-auto-import|Nuc|1.4.3
docker-compose|p1c|0.3.5
material-icon-theme|PKi|4.15.0
tsimporter|pmn|2.0.1
prisma|Pri|3.12.0
typescript-hero|rbb|3.0.0
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
vs-code-prettier-eslint|rve|3.1.0
code-settings-sync|Sha|3.4.3
es6-mocha-snippets|spo|0.2.2
move-ts|str|1.12.0
vscodeintellicode|Vis|1.2.18
vscode-icons|vsc|11.10.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
pynewfile477:30463512

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
