### ISSUE TITLE
VS Code fails to download server archive (HTTP 404)

### ISSUE THREAD

**Issue by maciej-boniecki** [microsoft/vscode#147324]
Issue Type: <b>Bug</b>

1) Start Visual Studio Code 1.66.2 on Windows 20H2 (build 19042.1586)
2) Try to connect to Linux server (which has no Internet access) using remote SSH feature. Server I am connecting to is running CentOS Linux release 7.9.2009 (Core).
3) Visual Studio Code will first try to download server archive using wget, which will obviously fail because of no Internet access on the remote host. After that it will try to download server archive locally to my computer, transfer it using scp to remote host and install.

**Expected result:**
Visual Studio Code should download server archive to my computer, transfer it using scp to remote host and install.

**Actual result:**
Downloading to my computer fails with HTTP 404 error. Developer tools shows that it tries to download server archive from address: https://update.code.visualstudio.com/commit%3Adfd34e8260c270da74b5c2d86d61aee4b6d56977/server-linux-x64/stable
I tried to download this archive using my browser and it also ended up with HTTP 404. The problem is %3A sequence (URL encoded colon) in address. When I have changed it to:
https://update.code.visualstudio.com/commit:dfd34e8260c270da74b5c2d86d61aee4b6d56977/server-linux-x64/stable
file downloaded successfully.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Connection to 'SSH' could not be established  Server returned 404

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.98GB free)|
|Process Argv|--crash-reporter-id bd674a83-7284-4154-8dd2-a6974af38761|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH' could not be established  Server returned 404
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by tanhakabir** [comment]
Seems like a duplicate of https://github.com/microsoft/vscode-remote-release/issues/6607#event-6426881168

@maciej-boniecki could you try again? It looks like it was a temporary failure

**Comment by maciej-boniecki** [comment]
@tanhakabir It works now, so probably you are right that it was temporary failure.
