### ISSUE TITLE
JSX syntax highlighting in 0.10.5

### ISSUE THREAD

**Issue by luisrudge** [Microsoft/vscode#1473]
I'm seeing lots of inconsistencies with JSX highlighting in 0.10.5:

![image](https://cloud.githubusercontent.com/assets/941075/11912828/5f282f1c-a636-11e5-8d46-ffa7ad560741.png)

* `export` and `default` are keywords and should be colored accordingly
* A class should be colored too
* `render` is a method  and should be colored accordingly
* `const` is a keyword and should be colored accordingly
* `{'this is a string and has to be colored accordingly'}`
* string interpolation should work inside jsx parameters

**Comment by egamma** [comment]
This is a consequence of #1470, pls see my [comment](https://github.com/Microsoft/vscode/issues/1470#issuecomment-166111410) for background and apologies.

Can you please try another theme e.g. Monokai? There the tokens should be rendered properly.

Closing as a duplicate of #1470

**Comment by luisrudge** [comment]
Thanks for the clarification @egamma
