### ISSUE TITLE
erorr of install iq

### ISSUE THREAD

**Issue by tomHcalvin** [microsoft/vscode#147359]
Issue Type: <b>Feature Request</b>

Could not install IQ#:
Failed to load A, error: dlopen(/usr/local/share/dotnet/host/fxr/6.0.3/libhostfxr.dylib, 0x0001): tried: '/usr/local/share/dotnet/host/fxr/6.0.3/libhostfxr.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
The library libhostfxr.dylib was found, but loading it from /usr/local/share/dotnet/host/fxr/6.0.3/libhostfxr.dylib failed
  - Installing .NET Core prerequisites might help resolve this problem.
     https://go.microsoft.com/fwlink/?linkid=2063366

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

**Comment by Tyriar** [comment]
This doesn't seem related to vscode.
