### ISSUE TITLE
Error: Make sure to edit the README.md file before you publish your extension. 

### ISSUE THREAD

**Issue by csyj501** [Microsoft/vscode#14730]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: abusaidm.html-snippets-0.0.18, bajdzis.vscode-refresh-html-0.0.2, Compulim.vscode-express-0.0.5, dbaeumer.vscode-eslint-1.0.8, donjayamanne.jquerysnippets-0.0.1, tomoki1207.vscode-input-sequence-0.1.0, vladmrnv.expresssnippet-0.0.8

Error: Make sure to edit the README.md file before you publish your extension. 
but README.md file  is exist!

Steps to Reproduce:

1.vsce package

**Comment by AkashGutha** [comment]
You should edit the default README file provided with the extension generator. 

Change it according to your extension's features and publish it.

**Comment by csyj501** [comment]
thank you
