### ISSUE TITLE
Git repo fetch issue

### ISSUE THREAD

**Issue by sw-tt-umangkothari** [microsoft/vscode#147378]
Issue Type: <b>Bug</b>

Project is loaded but still not VS code is not fetching get repo and having issue in git

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-39-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2100 CPU @ 3.10GHz (4 x 2946)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|11.53GB (5.30GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9ed3e4c0-8081-42f7-a5d2-c8d6ba066ae2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
beautify|Hoo|1.5.0
json|Mee|0.0.1
sublime-keybindings|ms-|4.0.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689
pynewfile477:30463512

```

</details>

**Comment by sw-tt-umangkothari** [comment]
Hello All,

Git issue occurs due to new git version 
in that we have to add the project as safe directory. Pleas use below command in ubuntu to add git folder in safe directory
git config --global --add safe.directory "path"

**Comment by lszomoru** [comment]
That is correct. [This blog](https://github.blog/2022-04-12-git-security-vulnerability-announced/) describes the change in behaviour when discovering `.git` folders.
