### ISSUE TITLE
Match system theme keeps turning on dark mode

### ISSUE THREAD

**Issue by Inventrohyder** [microsoft/vscode#147389]
Issue Type: <b>Bug</b>

When I have VS code to match the system theme (either light or dark), it keeps switching back to the dark theme even though the system is on light mode.

To make VS code work, I have to turn on dark mode, then turn it back to light mode for it to go back to light mode. However, upon certain actions, such as clicking on a file in the problems tab turns on dark mode again for VS Code.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

**Comment by GoldEagle93** [comment]
Same here

**Comment by aeschli** [comment]
Do you have steps to reproduce? When exactly does it switch back?

**Comment by Inventrohyder** [comment]
Yeap,
The steps are:
* Switch to light theme,
* Open a file or just wait a few seconds

https://user-images.githubusercontent.com/22187034/165124203-f7638a42-c16c-41ae-9f72-208724377459.mov

**Comment by aeschli** [comment]
Does this reproduce with extensions disabled?

**Comment by Inventrohyder** [comment]
It seems to work correctly when all of the extensions are disabled

interesting

Uploading Screen Recording 2022-04-25 at 22.05.52.mov…

**Comment by aeschli** [comment]
You can use the `Start Extension Bisect` command to find out which extension is causing this.

**Comment by Inventrohyder** [comment]
Wow That is a great tool

It helped me crack it

It seems the developers of the extension are aware too.


<img width="957" alt="Screenshot 2022-04-26 at 01 31 55" src="https://user-images.githubusercontent.com/22187034/165185567-9c597570-f256-4902-91cf-249b00d4b977.png">

**Comment by aeschli** [comment]
Thanks for the insights. I hope their fix is available soon.

Closing the issue here.
