### ISSUE TITLE
March 2022 Recovery 2 broken link

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#147314]
See here:
https://github.com/microsoft/vscode/releases/tag/1.66.2

> The update addresses these [issues](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+milestone%3A%22March+2022+Recovery+2%22+is%3Aclosed), including a fix for a security vulnerability.

The "issues" link doesn't work.

**Comment by lalo-mx** [comment]
You can compare tags https://github.com/microsoft/vscode/compare/1.66.1...1.66.2#diff-8eb217427e5ed249ab8aa04ad2924766dfdab80b8998a43d735b1ddd54fe605cR338

**Comment by TylerLeonhardt** [comment]
Yep, we were still getting issues opened since these were security related :) They are there now. Thanks!
