### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vikramdattu** [microsoft/vscode#147377]
git extension takes lot of time starting up. It shows `unresponsive`  when seen in running extensions tab.

If this is relevant to the issue: Many a times I have seen git gutter indicators not working for certain workspaces.

Below is the issue description from vscode's report the issue option for the same. 

- Issue Type: `Bug`
- Extension Name: `git`
- Extension Version: `1.0.0`
- OS Version: `Darwin x64 21.4.0`
- VS Code version: `1.66.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 35,
		"activateCallTime": 9,
		"activateResolvedTime": 905,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "vscode.git",
				"_lower": "vscode.git"
			},
			"activationEvent": "*"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

PTAL at the screenshot attached. This is unresponsive issue for C/C++ extension, similar to git.
<img width="1037" alt="Screenshot 2022-04-13 at 7 08 55 PM" src="https://user-images.githubusercontent.com/5511751/163193521-bd8cea8b-b516-430b-87ae-058de701d565.png">

**Comment by lszomoru** [comment]
@vikramdattu, could you please describe the issue that you are running into? Thanks!
