### ISSUE TITLE
Allow Remote-SSH to use a WSL ssh agent

### ISSUE THREAD

**Issue by kevmo314** [microsoft/vscode#147315]
Can there be a setting to use the ssh agent in WSL instead of the Windows ssh agent? I always ssh from WSL instead and it would be nice to share configs.

**Comment by kevmo314** [comment]
> How do you invoke `ssh` in WSL? From the terminal?

Yes. In particular, running `wsl ssh ...` from PowerShell invokes the WSL ssh agent. I've created an ssh.bat in my home directory that way when I run `ssh` in PowerShell it runs through WSL.
 
> This sounds more like an WSL configuration issue (how to share the ssh settings between WSL and Wndows), and not directly related to VS Code. Maybe [this](https://devblogs.microsoft.com/commandline/sharing-ssh-keys-between-windows-and-wsl-2/) is useful?

I'd like to use the WSL agent to ssh. `gcloud` from GCP will often update `id_rsa` so it's not really enough to one-time copy the two files together. I guess symlinking them could work, but it doesn't sound great to symlink since the ssh client on Windows won't match the client in WSL.

I suppose it's only tangentially related to VS Code but I definitely lost a good few hours trying to figure out why VS Code hung while connecting before eventually realizing it was because I was using the wsl ssh agent.

**Comment by aeschli** [comment]
Not sure how VS Code can hang because of ssh. The Remote-WSL extension does not rely on ssh.

**Comment by kevmo314** [comment]
> Not sure how VS Code can hang because of ssh. The Remote-WSL extension does not rely on ssh.

No this is the Remote-SSH extension. I would like the Remote-SSH extension to use the WSL ssh agent instead of the Windows ssh agent. Remote-WSL is unrelated.

**Comment by roblourens** [comment]
I guess this is covered by the issue you mention or https://github.com/microsoft/vscode-remote-release/issues/937
