### ISSUE TITLE
Toggle Tab Visibility keybind is too similar to Close File keybind

### ISSUE THREAD

**Issue by culli** [microsoft/vscode#147310]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.1
- OS Version: macOS 12.3.1

Steps to Reproduce:

1.  Accidentally press Ctrl+Cmd+W when meaning to press some other shortcut.
2.  VS Code changes to show only one tab at a time.

Previously this was reported here: https://github.com/microsoft/vscode/issues/62959, but I believe it was closed in error. The reasoning given was that 3000+ people were using the shortcut (according to some internally available tracking metric).  However, [this Stackoverflow question](https://stackoverflow.com/questions/48589785/vscode-showing-only-one-file-in-the-tab-bar-cant-open-multiple-files) shows there are at least 500 people who upvoted the answers while trying to figure out what had happened to their VS Code.  The issue has been viewed 134k times, and I believe some portion of that represents people who are confused by this behavior.

I suggest removing this keybind to help not waste the time of possibly thousands of developers looking to undo this after they hit it.  Yes there is a workaround, but the default setup should not be something that behaves in this confusing way, it definitely comes across as a bug.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/30314 gives an original reasoning for having a keybinding but I think a keybinding makes little sense for this. To me hiding or showing tabs is a one-time decision that should not have a default keybinding. I hope others feel the same once this ships to stable...

**Comment by culli** [comment]
Thanks for doing this!
