### ISSUE TITLE
VSCode Tasks: Typescript tasks running wrong command

### ISSUE THREAD

**Issue by anburocky3** [microsoft/vscode#147397]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2 (user setup)
- OS Version: Windows_NT x64 10.0.22593

Steps to Reproduce:

1. Create `tsconfig.json` file and insert the following code.

```json
{
  "compilerOptions": {
    "outDir": "lib",
    "module": "commonjs",
    "target": "es6",
    "moduleResolution": "node",
    "noImplicitAny": true,
    "sourceMap": true
  },
  "exclude": ["node_modules"]
}
```

2. And run the task either by `CTRL + Shift + B`, which asks two options:

![image](https://user-images.githubusercontent.com/15264938/163232264-f3e844f7-8291-471c-8221-a9ffa05ad2fb.png)

3. Select any one option, and the executing command is like that.

![image](https://user-images.githubusercontent.com/15264938/163232391-691f3522-95e1-4b0e-a4c9-494d43dc0b1d.png)

The command should be like this.

```shell
tsc -p s:\git-projects\my-projects\tsconfig.json --watch 
```
but it is appending with `<` don't why.

**Comment by mjbvz** [comment]
Not sure I understand. Isn't the `<` just part of the printed text which tells you which task is being run? I don't think it's actually part of the executed command

https://github.com/microsoft/vscode/blob/ccd7649e358de68964d37f3e5c34d4f4321d223a/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1159

**Comment by anburocky3** [comment]
> Not sure I understand. Isn't the `<` just part of the printed text which tells you which task is being run? I don't think it's actually part of the executed command
> 
> https://github.com/microsoft/vscode/blob/ccd7649e358de68964d37f3e5c34d4f4321d223a/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1159

Oh right, then why doesn't the script is not running?

Check this:

![image](https://user-images.githubusercontent.com/15264938/163255371-9a173397-ea47-4649-9c5f-d1ef73607d72.png)

If i run this command: `tsc -p s:\git-projects\snippet-generator\tsconfig.json --watch`

**It is working.** (While running this, check the task status, it is tick now.)

![image](https://user-images.githubusercontent.com/15264938/163255504-9876e7ea-84dc-426d-8766-39dd56c2a569.png)

**Comment by mjbvz** [comment]
@anburocky3 Are errors being reported in the first case?

**Comment by anburocky3** [comment]
Yes, after running the build, it is still loading, but as you can see, the script doesn't execute it.

Check this, it is been loading for more than 1 minute, but the script got exited. 

![image](https://user-images.githubusercontent.com/15264938/163256404-ec5e8dfd-5cdf-46f3-a874-a49244e1c415.png)

**Comment by alexr00** [comment]
I see the task get executed properly:
```
> Executing task: tsc -p c:\Users\alros\Documents\testing\stuckTSBuild\tsconfig.json --watch <

[10:07:14 AM] Starting compilation in watch mode...

error TS18003: No inputs were found in config file 'c:/Users/alros/Documents/testing/stuckTSBuild/tsconfig.json'. Specified '
include' paths were '["**/*"]' and 'exclude' paths were '["node_modules"]'.

[10:07:14 AM] Found 1 error. Watching for file changes.
```

Do you have any terminal or task settings set?

**Comment by anburocky3** [comment]
> I see the task get executed properly:
> 
> ```
> > Executing task: tsc -p c:\Users\alros\Documents\testing\stuckTSBuild\tsconfig.json --watch <
> 
> [10:07:14 AM] Starting compilation in watch mode...
> 
> error TS18003: No inputs were found in config file 'c:/Users/alros/Documents/testing/stuckTSBuild/tsconfig.json'. Specified '
> include' paths were '["**/*"]' and 'exclude' paths were '["node_modules"]'.
> 
> [10:07:14 AM] Found 1 error. Watching for file changes.
> ```
> 
> Do you have any terminal or task settings set?

No based on my `tsconfig.json` file, it is suggesting it.

Even if i have this `tasks.json` file, 

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "typescript",
      "tsconfig": "tsconfig.json",
      "option": "watch",
      "problemMatcher": ["$tsc-watch"],
      "group": "build",
      "label": "tsc: watch - tsconfig.json"
    }
  ]
}
```

I experiencing the same problem. 

I see no errors on **problems** and **output** tab. On the taskbar, i see the **Building status** like this.

![image](https://user-images.githubusercontent.com/15264938/163380262-9745d998-93bb-4c2a-8304-b3c15f9159b3.png)

**Comment by alexr00** [comment]
@anburocky3 can you share your user and workspace settings.json?

**Comment by anburocky3** [comment]
These are my `settings.json` file

``` jsonc
{
  "editor.fontFamily": "MonoLisa", 
  "editor.fontSize": 15,
  "editor.lineHeight": 30,
  "editor.suggestFontSize": 15,
  "editor.suggestLineHeight": 28,
  "terminal.integrated.fontSize": 15,
  "terminal.integrated.lineHeight": 1.5,
  "[html]": {
    "editor.defaultFormatter": "HookyQR.beautify"
  },
  "[css]": {
    "editor.defaultFormatter": "HookyQR.beautify"
  },
  "editor.minimap.enabled": false,
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "editor.formatOnSave": true,
  "codesnap.shutterAction": "copy",
  "codesnap.transparentBackground": true,
  "git.autofetch": true,
  "git.confirmSync": false,
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "liveSassCompile.settings.formats": [
    {
      "format": "expanded",
      "extensionName": ".css",
      "savePath": "/assets/css"
    }
  ],
  "[scss]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },

  "emmet.includeLanguages": {
    "javascript": "javascriptreact"
  },
  "workbench.iconTheme": "vscode-icons",
  "css.lint.unknownAtRules": "ignore",
  "editor.quickSuggestions": {
    "strings": true
  },
  "diffEditor.ignoreTrimWhitespace": false,

  // tailwindCSS
  "tailwindCSS.emmetCompletions": true,
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "liveServer.settings.donotVerifyTags": true,

  // cmd
  "terminal.integrated.profiles.windows": {
    "PowerShell": {
      "source": "PowerShell",
      "icon": "terminal-powershell"
    },
    "Command Prompt": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": [],
      "icon": "terminal-cmd"
    },
    "Git Bash": {
      "source": "Git Bash"
    },
    "Cmder": {
      "path": "S:\\laragon\\bin\\cmder\\cmder.bat",
      "args": ["."]
    }
  },
  "terminal.integrated.defaultProfile.windows": "Cmder",
  "workbench.colorTheme": "Monokai",
  "editor.accessibilitySupport": "off",
  "eslint.alwaysShowStatus": true,
  "eslint.format.enable": true,
  "eslint.packageManager": "yarn",
  "editor.codeActionsOnSave": {
    "source.fixAll.eslint": true
  },
  "typescript.updateImportsOnFileMove.enabled": "always"
}

```

**Comment by alexr00** [comment]
Can you try changing `terminal.integrated.defaultProfile.windows` to `"terminal.integrated.defaultProfile.windows": "Command Prompt"`, close all integrated terminals, then run again? I recognize that you don't want to use this setting permanently, but it may help determine what's going on.

**Comment by alexr00** [comment]
I'm not sure why cmder wouldn't work. @meganrogge, do you know if there's anything special about cmder that could cause running a task to hang?

@anburocky3, if you're willing to use something other than cmder for task terminals, then you can set the automation profile setting(`erminal.integrated.automationProfile.windows`) and leave ` "terminal.integrated.defaultProfile.windows": "Cmder"`.

**Comment by anburocky3** [comment]
Thanks @alexr00 , i made it work with this:

```json
 "Cmder": {
      "path": [
        "${env:windir}\\Sysnative\\cmd.exe",
        "${env:windir}\\System32\\cmd.exe"
      ],
      "args": ["/K", "%CMDER_ROOT%\\vendor\\bin\\vscode_init.cmd"]
    }
```

Anyhow, like to remove the info message, but i think, this is more of cmder issue, so closing it. https://github.com/cmderdev/cmder/discussions/2692

Thank you for attending this issue. Good Luck.
