### ISSUE TITLE
A new line appears after executing commands with parameters using the dash/minus symbol "-" with zsh

### ISSUE THREAD

**Issue by GooseCoder** [Microsoft/vscode#14731]
- VSCode Version: 1.6.1  9e4e44c19e393803e2b05fe2323cf4ed7e36880e 
- OS Version: Fedora 21 

Steps to Reproduce:

1. Open to the integrated terminal, using zsh.
2. Execute the following command.
> ls -al
3. Repeat until the lines with the same command are formatted as follows:
> ls -
al
4. Try to execute the same command or another one with a "-" used, like for example to add configuration parameters like:
> babel --
version
5. The attribute is misplaced in another line and this happens from the executed commands onwards.
6. The command runs fine but is quite annoying have the lines stacked like that.
![new line](https://cloud.githubusercontent.com/assets/356675/19844344/25fe89e6-9f02-11e6-9400-07f8a5120db5.png)

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?

**Comment by GooseCoder** [comment]
I've already tested this issue using the insiders version, and I can confirm that the issue has been fixed. I 'll be looking forward the new version. Thanks. :)

**Comment by Tyriar** [comment]
Good to hear :smile: 

>
