### ISSUE TITLE
I like this blue line,but it was disappeared

### ISSUE THREAD

**Issue by IOLOII** [microsoft/vscode#147352]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.66.2 (user setup)
- OS Version:Windows_NT x64 10.0.22000

Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0

Steps to Reproduce:
1. I update my vscode just ten minutes ago
2. this blue line not appear in my vscode

This blue line may appear in my laste update my vscode,it was beautiful than the green line

After this update , no, nothing happend,
So i report this change, how does it change? I don't know

if there are some commit change this line,please Revert
if this is some config , tell me ,tks

> Is there anyone ,like me like this blue line ?🤪

![image](https://user-images.githubusercontent.com/34856171/163125851-ff4367ab-5aa1-4a8b-84c2-b6b061078955.png)

**Comment by IllusionMH** [comment]
/question
These decorations has different meanings: green - added lines, blue - modified lines.
https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators

You can change them if you want by overriding 
```
editorGutter.modifiedBackground
editorGutter.addedBackground
editorGutter.deletedBackground
```

**Comment by IOLOII** [comment]
> /question These decorations has different meanings: green - added lines, blue - modified lines. https://code.visualstudio.com/docs/editor/versioncontrol#_gutter-indicators
> 
> You can change them if you want by overriding
> 
> ```
> editorGutter.modifiedBackground
> editorGutter.addedBackground
> editorGutter.deletedBackground
> ```

yes! Got it,thank you
