### ISSUE TITLE
Feature request : supress warning and error messages

### ISSUE THREAD

**Issue by AkashGutha** [Microsoft/vscode#14735]
I think it would be helpful if for some users if they don't want __info__ and __error__ messages popping up all the time.

I'm having this problem while working in a restricted environment at office.

![warning msg](https://cloud.githubusercontent.com/assets/10159531/19846781/27d79620-9f68-11e6-9d80-222bda40d56d.png)

Options like this would be helpful:

``` js
 'editor.supressWarningMessages' : true
```

**Comment by bpasero** [comment]
For 1.7 we added an option to hide this warning.

**Comment by AkashGutha** [comment]
when will the 1.7 update be out?

**Comment by bpasero** [comment]
This week. Meanwhile: 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by AkashGutha** [comment]
what is the option that i need to set. any documentation anywhere?

**Comment by bpasero** [comment]
@AkashGutha when you see the warning there should be a button to never show again.

**Comment by AkashGutha** [comment]
Yes it is working . 

And it shows up only if I change the folder or if I reopen vscode . Is this the intended behavior ?

**Comment by bpasero** [comment]
@AkashGutha it will warn you once per workspace but should then remember it for that workspace.

**Comment by AkashGutha** [comment]
yes, it does that perfectly.  it only pops up if i have the folder closed from menu and open an new folder.

**Comment by bpasero** [comment]
@AkashGutha that is true, it will probably pop up all the time from after you closed a folder. Is that what annoys you still?
