### ISSUE TITLE
In version 1.66.1, Check for Updates gets error: Access is denied to create unins000.exe in C:\Users\<username>\AppData\LOcal\Programs\Microsoft VS Code

### ISSUE THREAD

**Issue by Glanbia123** [microsoft/vscode#147370]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.1
- OS Version: Windows 10

Steps to Reproduce:

1. Select "Check for Updates"
2. See error: Access is denied to create unins000.exe in C:\Users\<username>\AppData\LOcal\Programs\Microsoft VS Code

**Comment by ershiwo** [comment]
When click ignor button，Setup.exe still promt user that some files cannot be created and the installation cannot continue.
![2022-04-13_205214](https://user-images.githubusercontent.com/14813866/163184650-e6fbe947-23b5-4451-bead-5c8fa10710a5.jpg)

**Comment by ershiwo** [comment]
Found a temporary solution: remove the whole VS Code installation directory, and reinstall it.

Conside this issue relate with recently security change.

**Comment by joaomoreno** [comment]
Might just be a /duplicate #47841, unrelated to the recent security change. Glad to know reinstalling it fixed it for you.

**Comment by eg-chdev** [comment]
Had the same issue, followed @ershiwo 's advice and that worked. Does anyone know what the root cause is?

**Comment by Eveldee** [comment]
Same issue here, VS Code is installed in AppData, allowing full control for users changes nothing.

Running VSCode setup gave me the same error, installing it from winget fixed the issue.

**Comment by datnt19213** [comment]
Go to VScode and turn on the 'Setting Sync'  and go to file location C:\Users<username>\AppData\LOcal\Programs\Microsoft VS Code and double click on the unis000.exe file to and following to uninstall and reinstall on the VScode website. Hope you're fixed, no problem your setting and data file will not happen.

**Comment by eg-chdev** [comment]
> Go to VScode and turn on the 'Setting Sync' and go to file location C:\Users\AppData\LOcal\Programs\Microsoft VS Code and double click on the unis000.exe file and following to uninstall and reinstall on the VScode website. Hope you're fixed, no problem your setting and data file will not happen.

Kindly asking, why/how does the setting sync feature/option, impact the filesystem permission errors this issue is related to?

**Comment by datnt19213** [comment]
> > Go to VScode and turn on the 'Setting Sync' and go to file location C:\Users\AppData\LOcal\Programs\Microsoft VS Code and double click on the unis000.exe file and following to uninstall and reinstall on the VScode website. Hope you're fixed, no problem your setting and data file will not happen.
> 
> Kindly asking, why/how does the setting sync feature/option, impact the filesystem permission errors this issue is related to?

It's nothing but it's only an operation to avoid losing the plugin you're installed.

**Comment by Eveldee** [comment]
> > Go to VScode and turn on the 'Setting Sync' and go to file location C:\Users\AppData\LOcal\Programs\Microsoft VS Code and double click on the unis000.exe file and following to uninstall and reinstall on the VScode website. Hope you're fixed, no problem your setting and data file will not happen.
> 
> Kindly asking, why/how does the setting sync feature/option, impact the filesystem permission errors this issue is related to?

I don't think it's related to the issue, it's just to make sure you don't lose your settings when you reinstall

**Comment by ershiwo** [comment]
> Had the same issue, followed @ershiwo 's advice and that worked. Does anyone know what the root cause is?

I found the old directory ACLs are not as same as the reinstalled one. Maybe someone could verify it.
