### ISSUE TITLE
VSCode seems to be opened in "compatibility mode" in a short time after startup

### ISSUE THREAD

**Issue by ddarfantasy** [microsoft/vscode#147341]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows 10 (21H1)

Steps to Reproduce:

1. Open VScode.
2. The UI appers to be in compatibility mode in a short peroid of time.

I don't know if anyone has submitted this issue. As it's hard to describe, I cannot find an existing issue. Sorry if it's a dup or it's an expected behavior.

**Comment by ddarfantasy** [comment]
BTW, the issue can be found back to 1.66.0.

**Comment by scriptingstudio** [comment]
Can confirm

**Comment by deepak1556** [comment]
Can you provide a screen recording demonstrating the issue, thanks!

**Comment by scriptingstudio** [comment]
My case. It started after 1.66 update
![vscstart](https://user-images.githubusercontent.com/17237559/163217560-566486fa-886c-48b5-8a45-155011f71244.gif)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146683
