### ISSUE TITLE
SSH not reconnecting when going offline

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147318]
- Connect to SSH remote
- Turn off wifi
- After a minute, the window disconnects and never tries to reconnect

From the log, it looks like SSH is doing the right thing by throwing `RemoteAuthorityResolverError.TemporarilyNotAvailable`, but vscode never invoked the resolver again to reconnect.

Anything change on your end lately?

**Comment by alexdima** [comment]
After running `vscode-bisect --runtime desktop --verify-main-branch` it points to https://github.com/microsoft/vscode/compare/db0525ff4ba814780e901a5b9e399aaf596b9b20...d572d6e9d1282b352227916cb8f95bb2b03ddcaa and from that list I think the first bad commit is https://github.com/microsoft/vscode/commit/354b4129575cd78292a382ca3990953c7abfebeb
