### ISSUE TITLE
[css] Cascade layers: Support layer() function in @import

### ISSUE THREAD

**Issue by BenjaminAster** [microsoft/vscode#147354]
With the new CSS cascade layers, it is possible to import a CSS file and directly specify the layer in the `@import` statement ([see specification](https://www.w3.org/TR/css-cascade-5/#layer-declaration)):
```css
@import url("./foo.css") layer(foo);
```
However, VSCode shows a syntax error when using this syntax in a CSS file. Cascade layers are supported in all three modern browsers now, so it would be great if VSCode would be updated to recognize this new syntax.

**Comment by BenjaminAster** [comment]
@aeschli Are there any updates on this? Cascade layers have now been supported by all modern browsers for over three months, so many people (including me!) already want to use this in production. If the world's most popular code editor shows an error when using a well-supported and not-brand-new feature, most people won't use it. Please prioritize this!

**Comment by Pekes317** [comment]
I just want to +1 this feature

**Comment by Pekes317** [comment]
Okay, it must be the linter I'm using because  it was getting the proper syntax color and I thought is saw a warning about an unknown At-Rule. If there working being done for the import usage of layers it might worth doing a little discount double on the rest of the layer usage. Well anyway excited for all the CSS Layer stuff.

**Comment by Chris-titsus010** [comment]
@Pekes317 I too have the warning saying 'Unknown at rule @layer' but I don't have any linter extension installed.

**Comment by BenjaminAster** [comment]
@Chris-titsus010 Just checked, and yes, indeed: I had
```jsonc
"css.lint.unknownProperties": "ignore",
"css.lint.unknownAtRules": "ignore",
```
in my `settings.json`. Can recommend to everyone, as VSCode shows a warning for a ton of new CSS properties & at-rules.

Btw, with
```jsonc
"css.validate": false,
"html.validate.styles": false,
```
you can disable all warnings and errors in all your CSS.

**Comment by DavidSouther** [comment]
I am getting `css(css-semicolonexpected)` with

```
@import './sanitize.css' layer(reset);
                                              ^-- semi-colon expected
```

**Comment by DavidSouther** [comment]
Whoo! Thank you!
