### ISSUE TITLE
White screen flash during new instance launch

### ISSUE THREAD

**Issue by soumesh2002** [microsoft/vscode#147369]
Does this issue occur when all extensions are disabled?: Yes

At first when I launch my new instance a white screen flashes just before the window fully renders.

- VS Code Version: 1.66.2
- OS Version: Windows 11

Steps to Reproduce:

1. At new instance launch

**Comment by AdityaSre** [comment]
even I am facing same issue

**Comment by scriptingstudio** [comment]
the same here

**Comment by soumesh2002** [comment]
https://user-images.githubusercontent.com/53593544/163235176-565c2f56-9067-4a22-b76c-a9052e40f8a8.mp4

I don't have any custom value set.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/132339

**Comment by soumesh2002** [comment]
Waiting for the fix... 🧑‍💻😌 vscode-team
