### ISSUE TITLE
Weird debug behavior, variable pops up only when I use the variable explicitly

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#147340]
Does this issue occur when all extensions are disabled?: Yes/No

No because some extensions are mandatory for the debugging

- VS Code Version: 1.64.2 
- OS Version: windows 10

Steps to Reproduce:

I don't think there is a series of reproduction steps for this. Because I'm sure this is a vscode bug, so I have no clue. 

I don't know how to reproduce the bug but I have the result of the bug: 

When I have the following node.js script, it doesn't work, I mean the in the "watch" section I can't see "props" variable, I cannot debug "props" variable from the console as well, as the following screenshot: 

```js
return (
        <button
            {...props}
            ref={button}
            onClick={e => {
                animate(e);
            }}
        >
            {props.children}
        </button>
    );
```

![ShareX_ScreenShot_4b8de27b-6723-4907-aefe-3bf3949e424f](https://user-images.githubusercontent.com/24733624/163094782-1888b4a7-2f9f-4a4e-b92c-11e6fb840f43.png)

However just adding a line, explicitly using the variable that I desire to access, with the following script, it does work, as the following screenshot. So weird. 

```js 
return (
        <button
            {...props}
            ref={button}
            onClick={e => {
                animate(e);
                console.log();
                console.log(props);
            }}
        >
            {props.children}
        </button>
    );
```

![ShareX_ScreenShot_c5a51a3f-7bb5-417c-b0ae-e09208f42f48](https://user-images.githubusercontent.com/24733624/163094788-86aaa8fa-1a78-438e-b6fd-979d79deeee6.png)

**Comment by connor4312** [comment]
This is a behavior in V8. If a variable is not used in a scope, it may be accessible in expressions executed in that scope. However, you can view variable values up the stack in the **VARIABLE** view.

**Comment by yuis-ice** [comment]
Wait, but in the variables section also I cannot see the values, you see? the first screenshot, there is no the props variable there while it should be there. 

So, but what can we do when we want to access to the not-used-in-a-scope variables while debugging or stopping on a breakpoint? For now, I do just place console.log(variable) like the above screenshot before the debugger launch. I don't think re-launching debugger each time I found a variable that is not-used-in-a-scope is an efficient practice. 

Is there any workaround to this, for someone like me who want to be always able to see/watch/debug all accessible variables?

**Comment by connor4312** [comment]
> Wait, but in the variables section also I cannot see the values, you see? the first screenshot, there is no the props variable there while it should be there.

`props` is not used in the scope the debugger is paused in, you can check out https://developer.mozilla.org/en-US/docs/Glossary/Scope for more info about scopes

> Is there any workaround to this, for someone like me who want to be always able to see/watch/debug all accessible variables?

No workaround currently available, you can lend your support to https://bugs.chromium.org/p/v8/issues/detail?id=2710, but it does not appear that the V8/Chromium team is eager to fix this.

**Comment by yuis-ice** [comment]
Okay, thanks.
