### ISSUE TITLE
GistPad icon gone

### ISSUE THREAD

**Issue by ShadowInSoul** [microsoft/vscode#147395]
I was testing VS Code for the web, and in the moment it sync with my extensions from my VS Code for the desktop, the web version display the GistPad icon almost transparent (really hard to see). It doesn't happen with the other icons even reloading the page.

I understand not all extensions are compatible yet, but i thought you should check it out, in the case this issue happen with other things.

Thanks for your time.

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36 OPR/85.0.4341.60
Embedder: vscode.dev

**Comment by joaomoreno** [comment]
> I was testing VS Code for the web, and in the moment it sync with my extensions from my VS Code for the desktop, the web version display the GistPad icon almost transparent (really hard to see). It doesn't happen with the other icons even reloading the page.

Can you share a screenshot?

**Comment by ShadowInSoul** [comment]
Sure, in the image of the left is another icon selected... and on the rigth it's GistPad selected.
[https://i.imgur.com/RW6AOoF.png](url)

**Comment by joaomoreno** [comment]
Can you reproduce if you switch themes?
