### ISSUE TITLE
Environment Resolution Fails for Fish Shell 

### ISSUE THREAD

**Issue by mojotx** [microsoft/vscode#147320]
Does this issue occur when all extensions are disabled?: Unknown, since problem only occurs when launched from the macOS Dock, and it's tough to disable extensions without running `code --disable-extensions`. 

- VS Code Version: 
    ```
    Version: 1.66.2 (Universal)
    Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
    Date: 2022-04-11T07:49:20.994Z (1 day ago)
    Electron: 17.2.0
    Chromium: 98.0.4758.109
    Node.js: 16.13.0
    V8: 9.8.177.11-electron.0
    OS: Darwin x64 21.4.0
    ```
- OS Version: macOS Monterey v12.3.1 x64

Launching VSCode from the Dock gives the user an error pop-up with the message, _"Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGSEGV)"_

Note the Fish terminal window that works just fine behind the error message. 
![Screen Shot 2022-04-12 at 13 57 12](https://user-images.githubusercontent.com/5694899/163033968-c5b26a34-dd05-456a-a18d-085d425ec337.png)

Steps to Reproduce:

1.  Change login shell to [fish shell](https://github.com/fish-shell/fish-shell): `brew install fish && chsh -s /usr/local/bin/fish`
1.  Launch VSCode from macOS Dock
1.  Observe the error, _"Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGSEGV)"_
1. Note that the problem ONLY occurs when launching VSCode from the macOS Dock. Launching from the command-line bypasses the ["shell environment" code](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/platform/shell/node/shellEnv.ts#L53-L58), so the problem doesn't occur when VSCode is launched from a terminal. 

The contents of main.log are:
```txt
[2022-04-12 13:55:41.230] [main] [info] window#load: attempt to load window (id: 1)
[2022-04-12 13:55:41.238] [main] [info] update#setState idle
[2022-04-12 13:55:41.448] [main] [info] ExtensionHostStarterWorker created
[2022-04-12 13:55:41.664] [main] [error] Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGSEGV)
[2022-04-12 13:55:42.396] [main] [info] window#load: window reported ready (id: 1)
[2022-04-12 13:55:42.707] [main] [info] Starting extension host with pid 39455 (fork() took 3 ms).
[2022-04-12 13:55:42.708] [main] [info] ExtensionHostStarterWorker.start() took 11 ms.
[2022-04-12 13:55:42.763] [main] [error] Unable to resolve your shell environment: Unexpected exit code from spawned shell (code null, signal SIGSEGV)
[2022-04-12 13:55:43.308] [main] [error] RequestService#request resolving shell environment failed {}
[2022-04-12 13:56:11.244] [main] [info] update#setState checking for updates
[2022-04-12 13:56:11.650] [main] [info] update#setState idle
```

I have tried to debug this issue myself, but Node.js and TypeScript are not my area of expertise. I can build VSCode from source, but I cannot figure out how to launch the compiled version from my macOS Dock. I can launch my compiled version by running `./scripts/code.sh`, but the problem doesn't occur there, since it's not being launched from the dock. I tried running the universal binary with `code --force-user-env --log trace`, but the error doesn't occur when I launch it that way. I also tried running my compiled-from-source version with `./scripts/code.sh --force-user-env --log trace`, but when launched that way, the problem does not occur. 

If someone can tell me how I can force VSCode to run with `--log trace` (by setting an environment variable, or some other hack) I can probably figure out the issue myself. 

Note: I originally opened this as issue https://github.com/microsoft/vscode/issues/146719, but it was closed because it was assumed to be a duplicate of https://github.com/microsoft/vscode/issues/138708. However, I read the details of https://github.com/microsoft/vscode/issues/138708, and that user was modifying the `DYLD_LIBRARY_PATH` environment variable, and I have not modified that value. It is not even set, so I am not sure why my original issue was closed when there was no relation to my issue, other than they were the same error message. 

The relevant source file is https://github.com/microsoft/vscode/blob/main/src/vs/platform/shell/node/shellEnv.ts,

**Comment by mojotx** [comment]
From looking through the code, the shell environment analysis starts in [getResolvedShellEnv()](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/platform/shell/node/shellEnv.ts#L37), and then if you're not running from a CLI, or you pass the `--force-user-env` flag, it runs [doResolveUnixShellEnv()](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/platform/shell/node/shellEnv.ts#L101), which in turn calls [getSystemShell()](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/base/node/shell.ts#L16), which calls [getSystemShellUnixLike()](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/base/node/shell.ts#L41), where it tries resolving the environment variable `$SHELL`, which in my case, the value is `/usr/local/bin/fish`. 

From looking at the code, I think it is comparing the environment variables of the vscode process ([process.env](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/platform/shell/node/shellEnv.ts#L112)) with the environment from a [spawned shell](https://github.com/microsoft/vscode/blob/27dd7b41b6a830d5ea8eb896d5b2bb9c4bcd95ee/src/vs/platform/shell/node/shellEnv.ts#L147-L151), and looking for differences. 

I am not sure what's causing the error when launched from the dock, because the error goes away when run from the CLI.

**Comment by mojotx** [comment]
Once again, if someone could tell me how to launch the VSCode application from the Dock with `--log trace`, I suspect that the problem would become obvious. 

I am not an expert at Node.js and TypeScript, although I can follow the gist of the code. I tried searching through the code and documentation to see if I could set an environment variable or something similar to bump the logging from `info` to `trace`. 

I am still looking through the code, trying to find where the default log level is set. If I can find that, I can build VSCode locally, defaulting to `trace` logging, and then try to figure out a way to launch the locally-compiled version from the Dock. (So far, I haven't had much luck with that.)

**Comment by meganrogge** [comment]
@joaomoreno do you know of a way to launch VSCode from the dock while setting the log level? I do not.

**Comment by deepak1556** [comment]
Sorry I missed the original bug, can you provide crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by mojotx** [comment]
> Sorry I missed the original bug, can you provide crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

Hello, @deepak1556, I think I found the issue! 🎉 

I am checking some things first, but I will hopefully have a PR to fix the issue soon. I am trying to determine if the problem lies within VSCode, or with the [fish shell](github.com/fish-shell/fish-shell.git).

**Comment by mojotx** [comment]
Long story short, the [problem seems to be on the fish shell side](https://github.com/fish-shell/fish-shell/issues/8873). The `$TERM` environment variable is not being set by VSCode, which is causing the segmentation fault. I am closing this issue, since this is not a VSCode problem. Thank you!

**Comment by mojotx** [comment]
Also, if anyone finds this closed issue, I was able to run VSCode from the Dock, with increased logging, by using the Automator tool. 

I went into Automator, told it I wanted to automate an app, then clicked "Run Shell Script" as the action, and then entered this:
```
open -a "Visual Studio Code.app" --args --crash-reporter-directory /Users/mjarvis/vscode-dump/ --log trace
```

That gave me more verbose logs in `~/Library/Application Support/Code/logs`, and based on those I could identify the problem, to the point I did not need the crash dump files.
