### ISSUE TITLE
Feature Request: Org mode

### ISSUE THREAD

**Issue by Immortalin** [Microsoft/vscode#14733]
Org mode is a structured document format for notetaking, authoring and documentation. It's key feature is the notes' collapsible tree structure à la workflowy

**Comment by eedahl** [comment]
This would be super useful. This is an introduction to all the cool stuff you can do in a fully featured org-mode:
https://www.youtube.com/watch?v=SzA2YODtgK4

**Comment by eedahl** [comment]
Related, though I don't know whether it would be useful https://github.com/daitangio/org-mode-parser

**Comment by bernsie** [comment]
being a long-term emacs user, I have nothing bad to say about org-mode, i've recently started using vscode and I'm beyond impressed, a proper org-mode implementation would be amazing

**Comment by abhi18av** [comment]
The WebTech would only enhance the functionality of org-mode! This is *potentially* awesome :)
