### ISSUE TITLE
Anaconda extension on Apple M1 silicon

### ISSUE THREAD

**Issue by fikretc** [microsoft/vscode#147349]
The Anaconda extension from Microsoft is not available on Apple M1 silicon. I could not see it in the list of extensions on my MacBook M1. however it is available on my windows laptop.
can you provide if and when this extension will be available on VScode for M1 silicon?

**Comment by sandy081** [comment]
Can you please provide the link of the extension in the Marketplace?

**Comment by fikretc** [comment]
Thanks for asking.

On my windows laptop when searching for extensions it does not show up.
however I have it LOCAL-INSTALLED as "Anaconda Extension Pack v1.0.1"
On my windows laptop, the "Resources" heading does not exist for this
extension pack.
Seems like this is a combination of two extensions packed together?

Categories: Extension Packs
identifier: ms-python.anaconda-extension-pack
The Anaconda Extension Pack is a set of extensions that enhance the
experience of Anaconda customers using Visual Studio Code. It includes the
following set of Visual Studio Code extensions:
- Microsoft Python Extension for Visual Studio Code:
https://marketplace.visualstudio.com/items?itemName=ms-python.python
- YAML Support by Red Hat:
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml

Best regards,
Fikret Calikoglu

**Comment by sandy081** [comment]
It seems this extension does not exist in the Marketplace. May be you might have side loaded it using VSIX?

**Comment by fikretc** [comment]
you are right that it is no more in the marketplace. so I am closing the issue.
thanks for your support.
