### ISSUE TITLE
Korean translation for terminal.integated.shell.windows removes slashes from path names

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#14734]
```js
    // 터미널이 Windows에서 사용하는 셸의 경로입니다. Windows와 함께 제공되는 셸을 사용하는 경우(cmd, PowerShell 또는 Ubuntu의 Bash) 64비트 버전을 사용하려면 C:WindowsSystem32보다 C:Windowssysnative가 더 좋습니다.
    "terminal.integrated.shell.windows": "cmd.exe",
```

"C:WindowsSystem32보다" should be "C:\Windows\System32보다"
"C:Windowssysnative보다" should be "C:\Windows\sysnative보다"

**Comment by Tyriar** [comment]
Japanese is the same:

```js
// 端末が Windows で使用するシェルのパス。Windows に付属のシェル (cmd、PowerShell、または Bash on Ubuntu) を使用する場合、64 ビット バージョンを使用するには、C:WindowsSystem32 ではなく、C:Windowssysnative を選びます。
```

I'm pretty sure these locales need at least some separator in Windows paths if not `\`

**Comment by johnliu2016** [comment]
@Tyriar I quickly checked the translations for the 3 languages and I see correct path separator in loc strings, no difference from other Latin languages. Can you elaborate repro environment as I could remember path separator on Windows OS varies on fareast languages? I guess system locale (codepage) may impact. @dbaeumer, Can you share your opinion?

**Comment by dbaeumer** [comment]
I consumed translation on Friday morning. Could it be that this didn't make its way yet into MonacoLocalization repository. @Tyriar in which file are these strings. Then I can have a look.

**Comment by Tyriar** [comment]
This was on a recent build of Insiders (v1.7) and the strings are in settings.json.

**Comment by johnliu2016** [comment]
loc file location, e.g. KOR - [terminal.contribution.nls.resx.lcl](https://monacotools.visualstudio.com/Monaco/_git/MonacoLocalization#path=%2FLocalize%2Fkor%2Fvscode%2Fsrc%2Fvs%2Fworkbench%2Fparts%2Fterminal%2Felectron-browser%2Fterminal.contribution.nls.resx.lcl&version=GBmaster&_a=contents)

      <Item ItemId=";terminal.integrated.shell.windows" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[The path of the shell that the terminal uses on Windows. When using shells shipped with Windows (cmd, PowerShell or Bash on Ubuntu), prefer C:\Windows\sysnative over C:\Windows\System32 to use the 64-bit versions.]]></Val>
          <Tgt Cat="Text" Stat="Loc" Orig="New">
            <Val><![CDATA[터미널이 Windows에서 사용하는 셸의 경로입니다. Windows와 함께 제공되는 셸을 사용하는 경우(cmd, PowerShell 또는 Ubuntu의 Bash) 64비트 버전을 사용하려면 C:\Windows\System32보다 C:\Windows\sysnative가 더 좋습니다.]]></Val>
          </Tgt>
          <Prev Cat="Text">
            <Val><![CDATA[The path of the shell that the terminal uses on Windows.]]></Val>
          </Prev>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by dbaeumer** [comment]
Actually this was a tooling issue. I fixed it in the MonacoLocalization repository.
