### ISSUE TITLE
Scrolling treeView quickly triggers leak detection in Insiders

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#147456]
Does this issue occur when all extensions are disabled?: Yes (apart from our own extension providing the treeview)

- VS Code Version: 1.67.0-insider (Universal) Commit: a7a7f209ade96c516ce3cd9b330aa8c3db816223

- OS Version: macOS Big Sur 11.6

We are developing an extension and I noticed that we get these logs in the developer console when scrolling quickly up and down in our treeView.

```
event.ts:540 [4ca] potential listener LEAK detected, having 175 listeners already. MOST frequent listener (1):
event.ts:541 Error
    at Function.create (event.ts:554:25)
    at ee._event._event (event.ts:673:25)
    at bl.renderElement (treeView.ts:1077:41)
    at renderElement (asyncDataTree.ts:108:17)
    at E.renderElement (abstractTree.ts:411:17)
    at U.renderElement (listWidget.ts:1104:13)
    at p.insertItemInDOM (listView.ts:817:13)
    at p.render (listView.ts:754:10)
    at p.onScroll (listView.ts:984:9)
    at S.invoke (event.ts:575:17)
    at r.deliver (event.ts:779:22)
    at o.fire (event.ts:740:24)
    at scrollableElement.ts:191:19
    at S.invoke (event.ts:575:17)
    at r.deliver (event.ts:779:22)
    at o.fire (event.ts:740:24)
    at k._setState (scrollable.ts:391:18)
    at k.setScrollPositionNow (scrollable.ts:305:8)
    at k.setScrollPositionSmooth (scrollable.ts:311:16)
    at c._onMouseWheel (scrollableElement.ts:440:23)
    at HTMLDivElement.b (scrollableElement.ts:357:10)
```

I've seen similar reports when searching but I'm not using Python in any way.

I realise this is an insiders bug report which means you might already be aware and on top of it, but I figured I'd post it here to in case you think it looks suspicious and should be taken care of, then I could help provide more information if needed. Otherwise feel free to close this :)

**Comment by joaomoreno** [comment]
Unfortunately, it's a false positive. It warns of many listeners, because there are indeed many listeners. If your workbench is tall enough and you scroll fast enough there will be upwards of 175 rows rendered simultaneously, each with a [`themeService.onDidFileIconThemeChange` listener](https://github.com/microsoft/vscode/blob/ccf4a9e339b55a5c1f4c0d757c5f1e26a7b9dc8c/src/vs/workbench/browser/parts/views/treeView.ts#L1077).

I'll bump up the leak warning threshold.

cc @alexr00

**Comment by bpasero** [comment]
Fyi icon labels had a similar issue and I ended up with a [`ResourceLabels`](https://github.com/microsoft/vscode/blob/e43b54417f9780b6d470fd173060b308c3429e67/src/vs/workbench/browser/labels.ts#L104) collection that forwards events to widgets.

**Comment by joaomoreno** [comment]
> Fyi icon labels had a similar issue and I ended up with a [`ResourceLabels`](https://github.com/microsoft/vscode/blob/e43b54417f9780b6d470fd173060b308c3429e67/src/vs/workbench/browser/labels.ts#L104) collection that forwards events to widgets.

That has the same complexity, except that it keeps a list of N objects rather than the event emitter keeping a list of N listeners. It just helps in getting away from the leak listener warning, right?

**Comment by bpasero** [comment]
It can avoid having to call some checks per label by calling it once outside, e.g.:

https://github.com/microsoft/vscode/blob/e43b54417f9780b6d470fd173060b308c3429e67/src/vs/workbench/browser/labels.ts#L175-L177

But there is probably not a lot to gain here.
