### ISSUE TITLE
The TypeScript language service died unexpectedly 5 times in the last 5 Minutes.

### ISSUE THREAD

**Issue by paulkotov** [microsoft/vscode#147464]
We have written the needed data into your clipboard because it wa
Issue Type: <b>Bug</b>

Just work with VScode for some period, and after while you'll have this bug with notebook overheating

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|--crash-reporter-id d2169464-4985-44e8-8620-00eaa14ab00a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
vscode-angular2-files|ale|1.6.4
vscode-intelephense-client|bme|1.8.2
phpserver|bra|3.0.2
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
linter|fna|0.0.11
code-runner|for|0.11.7
rest-client|hum|0.24.6
vscode-react-typescript|inf|1.3.1
graphql-for-vscode|kum|1.15.3
blockman|leo|1.5.7
vscode-docker|ms-|1.21.0
remote-wsl|ms-|0.66.0
vscode-typescript-tslint-plugin|ms-|1.3.4
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
vscode-graphql|ors|0.3.18
quicktype|qui|12.0.46
LiveServer|rit|5.7.5
vscode-javascript-booster|sbu|14.0.1
markdown-preview-enhanced|shd|0.6.2
sapling|tea|1.2.0
vscode-icons|vsc|11.10.0
quokka-vscode|Wal|1.0.457

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690

```

</details>

s too large to send. Please paste.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
