### ISSUE TITLE
Unify CSS escaping

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147430]
We have 2 competing methods to escape CSS:

https://github.com/microsoft/vscode/blob/318f04c7dace7414c63fdf213001ff5259e1c8dd/src/vs/editor/common/services/getIconClasses.ts#L113-L115

https://github.com/microsoft/vscode/blob/9245f60f40351b349ba86c20ba3e6ab501564db1/src/vs/workbench/services/themes/browser/fileIconThemeData.ts#L447-L450

I suggest to have 1 method in `dom.ts` for this. It is also unclear to me why we still need to use the regex.

I found I user in `common` that would need to move to `browser` but I think that is doable: `src/vs/workbench/services/extensionRecommendations/common/workspaceExtensionsConfig.ts`

Thereby also assigning Sandeep.

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode/pull/233687
