### ISSUE TITLE
Allow pannels in multiple places

### ISSUE THREAD

**Issue by bernardoadc** [microsoft/vscode#147471]
I want to have for instance Terminal in both bottom pannel and on right sidebar - I have one wide monitor (in which is good to see terminal on the right) and a flipped wide monitor (tall but narrow, in which is good to see terminal on the bottom), with a duplicate workspace.

This could be true to other pannels too (problems, output, etc).

**Comment by Tyriar** [comment]
There is only one terminal panel by design. If you want multiple you should use terminals in the editor area: https://code.visualstudio.com/docs/terminal/basics#_terminals-in-editor-area
