### ISSUE TITLE
Terminal is unresponsive 

### ISSUE THREAD

**Issue by zbs** [microsoft/vscode#147486]
Issue Type: <b>Bug</b>

I'm using VS Code over a remote connection, and am largely operating within a tmux session. There is considerable lag when typing, hitting CTRL+C, etc that seems to have started recently, presumably tied to the new release.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1062.9.1.el7.company3.x86_64
Remote OS version: Linux x64 3.10.0-1062.9.1.el7.company3.x86_64
Remote OS version: Linux x64 3.10.0-1062.9.1.el7.company3.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (14.47GB free)|
|Process Argv|--folder-uri vscode-remote://ssh-remote%2Bcolo-login0010/physical/gpfs/colo-teamusers/colo_team_users02/data_files/team/home/team/zsilversmith/dev/git/repo5 --crash-reporter-id 745587e8-1a3a-48d7-afc4-0a837a16dc7e|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: colo-login0010|
|OS|Linux x64 3.10.0-1062.9.1.el7.company3.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (36 x 3399)|
|Memory (System)|754.19GB (19.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: colo-login0007|
|OS|Linux x64 3.10.0-1062.9.1.el7.company3.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (36 x 3399)|
|Memory (System)|754.19GB (89.39GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: colo-login0009|
|OS|Linux x64 3.10.0-1062.9.1.el7.company3.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (36 x 3399)|
|Memory (System)|754.19GB (93.19GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.78.0
vim|vsc|1.22.2
gitlens|eam|12.0.6
shifter|Gru|0.0.6
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
trailing-spaces|sha|0.3.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by Tyriar** [comment]
I don't believe there is any regression wrt remote latency. If there lag, chances are your remote connection is worse. I'm happy to be proven wrong but we don't plan on investigating this further.
