### ISSUE TITLE
JS doc @component fixes

### ISSUE THREAD

**Issue by justingolden21** [microsoft/vscode#147490]
I have a `.svelte` file with this comment just above the HTML component:

```html
<!--
@component
A customizable analog clock

@param {string} mode: 'static' if the clock displays only one time
-->
```

And when hovering, it provides this helpful tooltip:

![image](https://user-images.githubusercontent.com/30274440/163501928-66a547da-eff3-4ffc-bd3b-a01462a35ddf.png)

![image](https://user-images.githubusercontent.com/30274440/163502081-24fbbd55-e857-4b7e-945d-f6f056d7b900.png)

But because it's in an HTML comment, the `@param` doesn't syntax highlight correctly, and even if I add spaces or asterisks or both it still doesn't work. Even if I make it a JS comment in the script above, then the entire `@component` doc doesn't display at all.

![image](https://user-images.githubusercontent.com/30274440/163502058-b0427b65-d5e5-40a0-b52c-e158d553db0e.png)

![image](https://user-images.githubusercontent.com/30274440/163502047-50958641-d8fc-4688-9d5f-18eb56988773.png)

You can see that adding the asterisk highlights it in a brighter green, and in markdown it's a bullet point (correctly so), but I cannot get it to highlight `@param` as someone would usually see:

![image](https://user-images.githubusercontent.com/30274440/163502142-d905280e-8c39-4621-9800-11b2e54d0a56.png)

I would guess this is a bug, but it's also kind of a feature request to add syntax highlighting, so I didn't want to distract from actually valid bugs. Feel free to recategorize this.

**Comment by mjbvz** [comment]
I think this highlighting comes from your svelte extension so please file this issue against them
