### ISSUE TITLE
Extensions in WSL: Ubuntu Problem

### ISSUE THREAD

**Issue by Boole91** [microsoft/vscode#147469]
Issue Type: <b>Bug</b>

All of the extensions that I had installed for WSL: Ubuntu have disappeared, and when I attempt to install any extension in WSL: Ubuntu, it does nothing. Depending on the extension, it will either say 'Installing' and hang indefinitely, or it won't even acknowledge that I clicked the install button.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.72-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3993)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (23.66GB free)|
|Process Argv|--crash-reporter-id 69e12a2a-a7a2-4643-ab8b-cf42b3a7486f|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.4.72-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor (16 x 3992)|
|Memory (System)|15.59GB (14.56GB free)|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
es7-react-js-snippets|dsz|4.4.3
better-cpp-syntax|jef|1.15.13
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
material-icon-theme|PKi|4.15.0
JavaScriptSnippets|xab|1.8.0
bootstrap5-vscode|Anb|0.2.2
ng-template|Ang|13.3.0
doxdocgen|csc|1.4.0
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
better-cpp-syntax|jef|1.15.13
csharp|ms-|1.24.3
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.3.1000901801
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
vscode-typescript-next|ms-|4.7.20220408
LiveServer|rit|5.7.5
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by PeterWang-dev** [comment]
Same problem occured on me.

**Comment by sandy081** [comment]
Seems to be connection issues with WSL.

**Comment by aeschli** [comment]
@sandy081 Can there be a timeout and an error message? IMO this needs to be handled at the place where the downloading happens. I don't see what I as the provider of the resolver can do here.

**Comment by PeterWang-dev** [comment]
> a timeout and an error message? IMO this needs to be handled at the place where the downloading happens. I don't see what I as the provider

Honestly, I didn't notice that some errors like timeout displayed in the debug window.

**Comment by PeterWang-dev** [comment]
> @sandy081 Can there be a timeout and an error message? IMO this needs to be handled at the place where the downloading happens. I don't see what I as the provider of the resolver can do here.

It seems working out of box now although I didn't do anything.

**Comment by sandy081** [comment]
@Boole91 Please try following and share logs

- Set log level to trace `F1 > Set Log Level... > Trace`
- Try to install extension
- Share following logs
  - `F1 > Open View... > Log (Window)`
  - `F1 > Open View... > Log (Remote)`
