### ISSUE TITLE
vscode.workspace.findFiles behaves differently on vscode.dev and on Desktop/Mac

### ISSUE THREAD

**Issue by lgrammel** [microsoft/vscode#147407]
Does this issue occur when all extensions are disabled?: No - it's extension specific (VSCode API)

- VS Code Version: 1.66.2 (Universal) (desktop), 1.66.2 vscode.dev
- OS Version: macOS Monterey 12.2

Steps to Reproduce:

In my extension, I'm using the following code to filter out relative paths:

```
    const matchedUris = await vscode.workspace.findFiles(
      new vscode.RelativePattern(workspaceFolder, matchPath),
      new vscode.RelativePattern(workspaceFolder, excludedPathPattern),
      1
    );
```

`matchPath` is a relative path, e.g. `folder/myFile.js`. On vscode.dev, this code only worked as intended for me when I prepended a slash to the relative path, which in turn broke the behavior on Desktop/node. I needed to implement conditional logic to support both environments:

```
    const matchPath = isBrowser ? `/${relativePath}` : relativePath;
    const matchedUris = await vscode.workspace.findFiles(
      new vscode.RelativePattern(workspaceFolder, matchPath),
      new vscode.RelativePattern(workspaceFolder, excludedPathPattern),
      1
    );
```

(`isBrowser` gets set based on the environment)

I would expect the behavior in vscode.dev match the behavior on Desktop/node. It is not clear to me which behavior is the desired behavior.

**Comment by lgrammel** [comment]
I've switched to using `minimatch` to check for file exclusions (not using `findFiles` with exclusions any more).

**Comment by roblourens** [comment]
@lgrammel can you check this in insiders.vscode.dev?

@JacksonKearl maybe relevant to the changes you just made?

**Comment by lgrammel** [comment]
I've checked P42 v1.94.5 (which was prior to my slash prefix workaround) on insiders and it works. I've checked the same version again on vscode.dev and it is broken there.

**Comment by roblourens** [comment]
Ok thanks for confirming, I think this was just fixed

**Comment by JacksonKearl** [comment]
> I've checked P42 v1.94.5 (which was prior to my slash prefix workaround) on insiders and it works. I've checked the same version again on vscode.dev and it is broken there.

When you say insiders here are you referring to `insiders.vscode.dev`?

**Comment by lgrammel** [comment]
> > I've checked P42 v1.94.5 (which was prior to my slash prefix workaround) on insiders and it works. I've checked the same version again on vscode.dev and it is broken there.
> 
> When you say insiders here are you referring to `insiders.vscode.dev`?

Yes
