### ISSUE TITLE
Source control stopped working

### ISSUE THREAD

**Issue by ajmeese7** [microsoft/vscode#147418]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows 11 Pro 21H2 22000.613

After updating from 1.66.0 VS Code suddenly no longer detects any git repositories. I have tried disabling all of the extensions, closing and re-opening my projects, and reloading the windows, but nothing I can do will make version control work again.

The sidebar no longer highlights changed files at all, and git works fine on my machine, both on WSL 2 and on native Windows. Any input would be greatly appreciated, thanks in advance!

**Comment by zhaodext** [comment]
I'm having the same issue. VSC couldn't find the git repository when I connect to the docker container.

- VS Code Version: 1.66.2 (Universal)
- OS Version: Mac OS Monterey 12.3.1

**Comment by lszomoru** [comment]
@ajmeese7, @zhaodext, have you upgraded `git` recently? There has been an update to `git` that contains a change on how git detects repositories. As VS Code invokes git to detect a git repository you might see changes in behaviour due to this. Please consult [the following blog post](https://github.blog/2022-04-12-git-security-vulnerability-announced/) describing the change in bahaviour.

**Comment by gmutinel** [comment]
On windows I solved it running Code.exe as admin (setted on file properties, for all users). But I guess it depends on
- How you installed it (For all users/Just for yours)
- Where you keep your project (it's a user-rights issue)
- Misc userrights differences in configurations.

Setting the directory in the git global configs seems to work too but it cannot be done with a wildcard (or at least, I couldn't find the way) so you'd need to list all your project dirs and keep it updated

```
[safe]
	directory = C:/Apache24/htdocs/project_name
```

**Comment by zhaodext** [comment]
I have tried below:

- Update my git from 2.24 to 2.35.3, and reboot the computer
- Upgrade the "remote - containers", "Docker", "Git Extension Pack" plugin to the latest version
- Disable all other plugins
- Uninstall the VS Code and reinstall an older version
- Upgrade the Docker to the latest version (4.7.0)

But I still see the source control couldn't find repo issue.
The source control works fine if I run all the code locally. The issue only appears when connecting to the docker remote containers.

My teammate sees everything working fine from his machine. So I guess there might be some dependencies versions not matching with each other.

**Comment by atompkins** [comment]
Update git to 2.35.3
opt out with
```git config --global --add safe.directory *```

**Comment by rdenneman** [comment]
> @ajmeese7, @zhaodext, have you upgraded `git` recently? There has been an update to `git` that contains a change on how git detects repositories. As VS Code invokes git to detect a git repository you might see changes in behaviour due to this. Please consult [the following blog post](https://github.blog/2022-04-12-git-security-vulnerability-announced/) describing the change in bahaviour.

I'm on git 2.35.3.windows.1
Both git bash and PyCharm (using the same git executable path) recognize the repositories just fine.
VSCode 1.66.2 does not.

This happens for repositories located on
-  \\wsl$ share
- via the Remote - WSL extension
- located on another windows pc (via file share)
- local repositories

**Comment by mrleemon** [comment]
I'm on Windows 10 and I'm having the same problem.
Even though .git folders are present in all of my projects, VSCode doesn't detect any local repositories.

**Comment by Enoril** [comment]
Since I have updated git to the version `2.35.3.windows.1` i have the same bug.

[atompkins](https://github.com/atompkins) command resolved my problem after a Visual Studio Code reload.
> `git config --global --add safe.directory *`

I assume using the right git directory instead of `*` could have also worked.
> `git config --global --add safe.directory W:/git/online/my-git-repository`

**Comment by lszomoru** [comment]
@zhaodext, please note that when using a docker container, VS Code will use the version of git that is installed in the container. Can you please check the version of git installed in the container, and see if that matches the version that you have installed locally? 

@rdenneman, when using WSL, VS code will use the version of git that is installed in WSL. You will have to upgrade the version of git in WSL to the latest version, and then add the directory in WSL to the `safe.directory` in the WSL terminal.

**Comment by zhaodext** [comment]
@lszomoru Hello! Sorry for getting back late. So yes, the VS Code is using the git version inside the container. But due to the image we are using, the ceiling git version in the container is 2.17. A better choice might be running a command inside the container to add a safe directory to the project inside the container. 

To whoever faces this issue, you can probably solve this by running `git config --global --add safe.directory /{:project_name}`.
