### ISSUE TITLE
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', 'msbuild /property:GenerateFullPaths=true /t:build /consoleloggerparameters:NoSummary'" terminated with exit code: 127.

### ISSUE THREAD

**Issue by Suvam67** [microsoft/vscode#147477]
Executing task: msbuild /property:GenerateFullPaths=true /t:build /consoleloggerparameters:NoSummary <

/usr/bin/bash: msbuild: command not found
The terminal process "C:\Program Files\Git\bin\bash.exe '--login', '-c', 'msbuild /property:GenerateFullPaths=true /t:build /consoleloggerparameters:NoSummary'" terminated with exit code: 127.

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal

**Comment by ChasKane** [comment]
I'm getting a similar error when running the vscode-neovim extension in the debugger. It seems that somewhere along the steps listed in this section of the doc on how to debug extensions, the `'-c'` is being added and I can't figure out why. `-c` tells bash to accept a string command as the first parameter, but idk why it's adding the single-quotes around it.
