### ISSUE TITLE
Rename file does not show (refactor) preview

### ISSUE THREAD

**Issue by Onapmek** [microsoft/vscode#147444]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Have a folder with files
2. Rename the file

The issue being is that it renames a certain file but does not change the imported module instances in my code. The enable preview box is ticked for renaming.

**Comment by mjbvz** [comment]
What language is this for?

**Comment by Onapmek** [comment]
@mjbvz It's for Python
