### ISSUE TITLE
typescript auto restart 5 times in 5 minute

### ISSUE THREAD

**Issue by mfv-brian** [microsoft/vscode#147445]
Issue Type: <b>Bug</b>

don't do anything, only using vscode and it show that error and computer is very slow

VS Code version: Code 1.66.1 (Universal) (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:47.400Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (1.06GB free)|
|Process Argv|--crash-reporter-id a16c9f55-9c3a-41b3-9777-a3ce9049ad0b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-styled-jsx|bla|2.1.1
vscode-tailwindcss|bra|0.8.1
cssrem|cip|3.0.0
package-json-upgrade|cod|1.6.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.6
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
url-encode|fle|1.1.0
auto-close-tag|for|0.5.14
go|gol|0.32.0
gc-excelviewer|Gra|4.2.54
base64viewer|Jas|1.2.1
calculator|lix|0.1.1
template-string-converter|meg|0.6.0
import-sorter|mik|3.3.1
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.21.0
vscode-typescript-next|ms-|4.7.20220408
vscode-typescript-tslint-plugin|ms-|1.3.4
color-highlight|nau|2.5.0
vscode-extension-auto-import|Nuc|1.4.3
docker-compose|p1c|0.3.5
material-icon-theme|PKi|4.15.0
tsimporter|pmn|2.0.1
vscode-yaml|red|1.6.0
px-to-rem|sai|1.3.1
vscode-scss-formatter|sib|2.4.2
autoimport|ste|1.5.4
move-ts|str|1.12.0
sass-indented|syl|1.8.19
sort-lines|Tyr|1.9.1
sort-js-object-keys|zen|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
