### ISSUE TITLE
Randomly bugged projects

### ISSUE THREAD

**Issue by FrameMuse** [microsoft/vscode#147453]
Issue Type: <b>Bug</b>

1. Clone this template https://github.com/FrameMuse/react-template
2. Open project directory via "Open folder"
3.1. See that the "Initializing JS/TS features" is taking too long.
3.2. See `autoimport` feature is not working for newly created files and just updated files names.

I tried a bigger project with this template and the procces of init took as twice as fast than and no bugs.

I oppend all projects via `open folder`.

I used the same extentions as are on the bigger project.

The issue is that somehow sometimes it happens that projects randomly got bugged and became slow.

VS Code version: Code - Insiders 1.67.0-insider (a7a7f209ade96c516ce3cd9b330aa8c3db816223, 2022-04-14T05:15:18.304Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.36GB (4.81GB free)|
|Process Argv|--crash-reporter-id cd0f9251-fe64-49a4-9c24-55fad5dd78c7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics (12 x 3293)|
|Memory (System)|11.37GB (8.05GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
es7-react-js-snippets|dsz|3.1.1
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
html-slim-scss-css-class-completion|gen|1.7.8
vscode-pull-request-github|Git|0.40.0
beautify|Hoo|1.5.0
vscode-env|Iro|0.1.0
vue|jcb|0.1.5
svg|joc|1.4.17
vscode-github|Kni|0.30.7
file-count|Mik|1.2.0
vscode-scss|mrm|0.10.0
vscode-language-pack-ru|MS-|1.66.3
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
wordcount|ms-|0.1.0
vue-beautify|pea|2.0.4
snippet-creator|rya|0.1.3
mdx|sil|0.1.0
code-spell-checker|str|2.1.11
vscode-counter|uct|3.0.4
vscode-maven|vsc|0.35.1
vscode-icons|vsc|11.10.0
vscode-todo-highlight|way|1.0.5
vscode-import-cost|wix|3.3.0
vscode-mdx-preview|xyc|0.3.3

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I just tested with the linked project but everything seems to work fine. If you're still seeing issues with extensions disabled, please share specific tests I can use so we can investigate this problem
