### ISSUE TITLE
Extension issues after latest vs-code update

### ISSUE THREAD

**Issue by tmd-uk** [Microsoft/vscode#1474]
Uhh! Is this supposed to be like this after the most recent update? Has anyone else got this?

![vscode-erros](https://cloud.githubusercontent.com/assets/7654330/11912877/2dfa20fe-a649-11e5-95ce-a5cbca566212.jpg)

**Comment by bpasero** [comment]
@tmd-uk can you try to uninstall vscode, make sure the folder is fully deleted from program files directory and then reinstall to see if that solves the issues?

**Comment by tmd-uk** [comment]
I'll have to try it later on.

**Comment by jshowatt** [comment]
Simply deleting the csharp-o folder was enough to remove the issue for me. There were no files in there, just a series of empty folders.

**Comment by bpasero** [comment]
This can happen when the installer fails to delete the extensions folder for some reason. Typically deleting VS Code manually and running the installer again solves these issues.

**Comment by tmd-uk** [comment]
Sorted, thanks for the help guys.
