### ISSUE TITLE
Desfoque - Unfocus

### ISSUE THREAD

**Issue by ediliojr** [microsoft/vscode#147489]
Tentei desativar todas as opções que afetariam o desfoque dos campos, porém continua desfocando. O problema acontece com os campos que o mouse não está em cima, e quando o mouse fica parado por mais de 3 segundos.
I've tried to deactivate all options that would affect the unfocus, but the issu still up. All the sectors lose the focus if the mouse arrow isn't in it, and when the arrow stead still by 3 seconds.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo including whether the problem is being caused by one of your extensions.

The Start Extension Bisect command can help you to investigate this.
