### ISSUE TITLE
`vscode.dev` badge no longer available

### ISSUE THREAD

**Issue by Stanzilla** [microsoft/vscode#147402]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2	
- OS Version: Windows 11 22H2

Steps to Reproduce:

1. I used to use the following badge on my repository but the image is no longer there `https://open.vscode.dev/badges/open-in-vscode.svg`
2.

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/128813#issuecomment-943125631
