### ISSUE TITLE
JS/TS keeps crashing

### ISSUE THREAD

**Issue by sylvain-bourgin** [microsoft/vscode#147484]
Issue Type: <b>Bug</b>

JS/TS keeps crashing in our codebase

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 6|
|Memory (System)|32.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id 2e1d9459-158f-45c0-bd3f-d1cbce43ea0a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
asana-vsc|asa|0.0.5
vscode-bazel|Baz|0.5.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
typescript-namespace-imports-vscode-plugin|jos|0.2.3
intellij-idea-keybindings|k--|1.5.1
vscode-scss|mrm|0.10.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
debugger-for-chrome|msj|4.13.0
back-n-forth|nic|3.1.1
vscode-stylelint|sty|1.2.2
vscode-todo-highlight|way|1.0.5

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by sylvain-bourgin** [comment]
I'm somehow no longer able to reproduce this bug. Not sure what happened.
