### ISSUE TITLE
Ask permission from the user to download an update instead of downloading it automatically in the background

### ISSUE THREAD

**Issue by preIdiot** [microsoft/vscode#147494]
I'd really want to see a tiny modification in the vscode updating process, where when an update is available, the editor should ask permission to download it instead of downloading it automatically in the background and then waiting for a restart to apply it.

I recently went from Ubuntu to MacOS, and when I was on Ubuntu, I had complete control over updates because I installed vscode from a deb file, and I had to utilise the update manager to update any application. On MacOS, though, things are a little different; every package updates itself without requesting permission.

**Comment by gjsjohnmurray** [comment]
Previous requested in #119307 and declined by @joaomoreno

Do any of the `update.mode` setting options help you?

**Comment by preIdiot** [comment]
Thanks, I believe `"update.mode": "manual"` will enough for the time being.
