### ISSUE TITLE
 Cannot set property 'totalFrames' of undefined

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#14740]
Issue Id: <b>50befb3f-ca26-ae64-fb07-4aecd65497fa</b><br /><br />*Versions* <br />- 1.7.0-insider (10/28/2016 1:02:33 PM)<br />-  1d2d5e089a8261ebb6ad6dfb2e847e5aa1c16f9d<br />-  3c6f232d0546f32644e9fd3378ee967373655fc4<br />*Stack* <br />TypeError: Cannot set property 'totalFrames' of undefined<br />    at process.session.stackTrace.then.t.stoppedDetails.framesErrorMessage (<br />    at Object.g [as _notify] (<br />    at Object.enter (<br />    at _run (<br />    at _completed (<br />    at <br />    at t.e.dispatch (<br />    at t.e.handleData (<br />    at Socket.<anonymous> (<br />    at emitOne (events.js:96:13)<br />

**Comment by weinand** [comment]
@isidorn is this an issue with the VS Code or with node-debug?

**Comment by isidorn** [comment]
@weinand with vscode.
totalFrames tries to be set before the thread has data about why it is stopped here
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugModel.ts#L439

I believe it is a timing issue which did not surface during testing -> thus assigning it to November and not a candidate.
