### ISSUE TITLE
inlay hint left over on comments

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#147472]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/876920/163456277-f0b36649-4b7e-4eeb-96ec-b121fb8b6f01.png">

I don't have stable reproduce, but this happens pretty often, especially I'm moving lines around.

**Comment by hediet** [comment]
I don't think this is a bug of injected text: When there are not decorations, there cannot be any injected text.

**Comment by jrieken** [comment]
@rebornix Do you use the `editor.inlayHints.toggle` setting? Do you still see this with latest & greatest insiders?

**Comment by rebornix** [comment]
@jrieken I'm using the setting but haven't seen it for a while since I reported the issue.

**Comment by jrieken** [comment]
Leaving this open, lets find steps

**Comment by jrieken** [comment]
@hediet Is it possible that this is caused by the recursive `deltaDecorations` issue?

**Comment by hediet** [comment]
Could be the case!

The fix is to use it like this:
```ts
this.editor.changeDecorations(accessor => {
    this.decorationIds = accessor.deltaDecorations(this.decorationIds, decorations);
});
```

**Comment by jrieken** [comment]
Oh, so inside the `changeDecorations` runner?

**Comment by hediet** [comment]
Yes, because change events are only send out after `changeDecorations` returns. Thus, `deltaDecorations` is not reentrant anymore and `this.decorationIds` will be assigned correctly.
