### ISSUE TITLE
Stop changing selection in explorer when autoReveal = false

### ISSUE THREAD

**Issue by kaiwood** [Microsoft/vscode#14745]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1. Start VSCode via "code --disable-extensions"
2. Set "explorer.autoReveal": false in settings.json

Not sure when this happened or if its specific to my installation (normally I use the default), but if I disable the auto reveal it still jumps to the files in the explorer.

![autoreveal](https://cloud.githubusercontent.com/assets/7542/19848668/567bbc22-9f4f-11e6-9744-89dc17f1abeb.gif)

**Comment by bpasero** [comment]
@kaiwood this only controls revealing the file of the editor, we still show the file selected in the explorer because the explorer is synchronized with the editor at all times.

Let's rephrase this issue to express what you were expecting.

**Comment by kaiwood** [comment]
@bpasero Oh my, I was quite sure that it meant exactly this (even thought I tried it out a couple of weeks ago). Feature request is fine, I guess it would be quite useful to lots of users 👍

**Comment by bpasero** [comment]
@kaiwood the setting prevents the scrolling position to change which I think is the more annoying thing for many users (not the fact that we change the selection).

But I agree, maybe people expect also the selection to stay. Interestingly no-one complained about it so far.

**Comment by gregmarr** [comment]
Yes, this is EXTREMELY annoying.  I scrolled to another part of the tree for a reason.  Don't scroll me away to some other part of the tree just because you think it's a good idea at the time, such as I deleted a file from the tree.  Especially since I didn't interact with the editor at all.

**Comment by bpasero** [comment]
@gregmarr wait, the scrolling away can be disabled with exactly that setting, did you try?

**Comment by gregmarr** [comment]
@bpasero Which setting is that?  You said "this only controls revealing the file of the editor, we still show the file selected in the explorer because the explorer is synchronized with the editor at all times." which is what I want to avoid.

**Comment by kaiwood** [comment]
@gregmarr `"explorer.autoReveal": false`

To add a little more context, it was about this on Stackoverflow: http://stackoverflow.com/questions/40336835/vscode-prevent-file-explorer-from-jumping/40339047#40339047

**Comment by gregmarr** [comment]
Ah, I see, thanks.  I'd still like the behavior from the original request, but that's better than nothing.

**Comment by marty-wang** [comment]
please add a setting to make it configurable, because it is rather annoying to lose my current position in explorer, just because I switch active files.

**Comment by VojtechVitek** [comment]
@bpasero I have `autoReveal=false` and it works well. But is there any command that I could use for forcing the Explorer to reveal the current/active file?

**Comment by marty-wang** [comment]
yeah. they fix it. @VojtechVitek , the command you are looking for is 'show active file in explorer'

**Comment by VojtechVitek** [comment]
Thanks!

I've set up a shortcut to `workbench.files.action.showActiveFileInExplorer`

**Comment by bpasero** [comment]
There is also a context menu entry on tabs to reveal the file of the tab in the explorer.
