### ISSUE TITLE
Weird x: and s: showing up all over my code.

### ISSUE THREAD

**Issue by Micha3lB** [microsoft/vscode#147480]
Issue Type: <b>Performance Issue</b>

I was trying to get rid of the error saying .Java is a non-project file and saw something that suggested Clean Java Server Workspace. After selecting that my code has things all over the place such as "x:" in my println, "s:" in my print and my variable names showing up in parameters. I've completly deleted all vs code files but when I downloaded it back it was this here. Please help

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   213	  1597	code main
    4	   131	  1598	   gpu-process
    0	    49	  1600	   utility-network-service
    0	   541	  1605	   window (Settings)
    6	   311	  1617	   shared-process
    0	    66	  1620	     ptyHost
    0	     0	  2001	       /bin/zsh -l
    0	     0	  2027	       /bin/zsh -l
    0	    66	  1725	     fileWatcher
    1	     0	  2323	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   295	  1720	   extensionHost
    0	   737	  1736	     /Users/michaelbauer/.vscode/extensions/redhat.java-1.5.0-darwin-arm64/jre/17.0.2-macosx-aarch64/bin/java --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.nio.fs=ALL-UNNAMED -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Djava.import.generatesMetadataFilesAtProjectRoot=false -Dfile.encoding=utf8 -XX:+UseParallelGC -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true -Xmx1G -Xms100m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/folders/hs/3wwwvyl93psc4vylplm76ms80000gn/T/vscodesws_6224f -jar /Users/michaelbauer/.vscode/extensions/redhat.java-1.5.0-darwin-arm64/server/plugins/org.eclipse.equinox.launcher_1.6.400.v20210924-0641.jar -configuration /Users/michaelbauer/Library/Application Support/Code/User/globalStorage/redhat.java/1.5.0/config_mac -data /var/folders/hs/3wwwvyl93psc4vylplm76ms80000gn/T/vscodesws_6224f/jdt_ws
    0	    98	  1822	     /private/var/folders/hs/3wwwvyl93psc4vylplm76ms80000gn/T/AppTranslocation/A4DD1811-DC25-4106-9B25-09503CC80F28/d/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/michaelbauer/.vscode/extensions/ms-python.vscode-pylance-2022.4.1/dist/server.bundle.js --cancellationReceive=file:290a59589b007d89f70947144ff4263782cadcfd18 --node-ipc --clientProcessId=1720
    0	   115	  1864	     /private/var/folders/hs/3wwwvyl93psc4vylplm76ms80000gn/T/AppTranslocation/A4DD1811-DC25-4106-9B25-09503CC80F28/d/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/michaelbauer/.vscode/extensions/streetsidesoftware.code-spell-checker-2.1.11/packages/_server/dist/main.js --node-ipc --clientProcessId=1720
    0	    49	  2022	     /private/var/folders/hs/3wwwvyl93psc4vylplm76ms80000gn/T/AppTranslocation/A4DD1811-DC25-4106-9B25-09503CC80F28/d/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /private/var/folders/hs/3wwwvyl93psc4vylplm76ms80000gn/T/AppTranslocation/A4DD1811-DC25-4106-9B25-09503CC80F28/d/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1720
    3	    98	  2316	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.4
prettier-vscode|esb|9.5.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
java|red|1.5.0
code-spell-checker|str|2.1.11
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by mjbvz** [comment]
Please start by filing this against the Java extension

/extJava

**Comment by Micha3lB** [comment]
> Please start by filing this against the Java extension
> 
> /extJava

Sorry, this is my first time using GitHub. How do I do that?

**Comment by mjbvz** [comment]
You can manually file the issue over here instead: https://github.com/redhat-developer/vscode-java/issues

Or in the VS Code issue reporter, select `An extension` for the source and then select the `java` extension from the list before clicking submit
