### ISSUE TITLE
The new Node version is not official release version.

### ISSUE THREAD

**Issue by Lak4CYUT** [microsoft/vscode#147498]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: code_1.66.2-1649664567_amd64
- OS Version: Linux 5.4.0-96-generic Ubuntu

Steps to Reproduce:
As the changelog https://code.visualstudio.com/updates/v1_66#_nodemoduleversion-and-nodejs-api-update mentioned, 

NODE_MODULE_VERSION / process.versions.modules | 101

but the Node official release is NOT include module_version 101. the latest version should be 93 or 102.
https://nodejs.org/zh-cn/download/releases/
It seems to cause some extensions (eg pico-go) to not work properly.

**Comment by Lak4CYUT** [comment]
So this is not a issue?

**Comment by deepak1556** [comment]
Node module version on desktop is based on the version claimed by the Electron runtime https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json, if you are building native modules for desktop then you will have build using the correct headers https://github.com/electron/electron/blob/main/docs/tutorial/using-native-node-modules.md. If you want to avoid version compatibility issues then prefer to build with [Node-API](https://nodejs.org/dist/latest-v16.x/docs/api/n-api.html)

**Comment by Lak4CYUT** [comment]
Thanks.
