### ISSUE TITLE
Failure when try to publish an extension for 'Productivity'

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14749]
* have an extension that uses the `productivity` category
* you get the error below

```
Error: Failed Request: Bad Request(400) - The category 'Productivity' is not available in language 'en-us'.
```

**Comment by joaomoreno** [comment]
Productivity doesn't seem to exist as a category in https://marketplace.visualstudio.com/?VScode=1 . Category names are fixed by the Marketplace. 😕

**Comment by jrieken** [comment]
We should then not have it in our intellisense list I suggest

**Comment by aeschli** [comment]
@joaomoreno You added it through https://github.com/Microsoft/vscode/pull/7304.

Removing it...

**Comment by joaomoreno** [comment]
Thanks @aeschli, I must've missed @seanmcbreen's comment.
