### ISSUE TITLE
Can not input fullwidth character in terminal, such as 。，！；

### ISSUE THREAD

**Issue by j1g5awi** [microsoft/vscode#147429]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version:  Arch Linux x86_64 5.17.1-arch1-1 

Steps to Reproduce:

1. Install Chinese Input Method Engine like fcitx5
2. Open Terminal in Vscode, try to input ，。；！, and it will bocome , . ; !

I try to find what cause this, and I find it's from this commit: 9520f0a515e7e24802c92f885a0efb242fca3831
But I don't know why upgrade electron will make me can not input fullwidth character.

**Comment by yanyongyu** [comment]
Same to me. I found that i can't input chinese character `。` since vscode 1.60 . maybe caused by upgrading to electron 13

**Comment by meganrogge** [comment]
pls let us know if you're still seeing this issue
