### ISSUE TITLE
cant resize vscode terminal

### ISSUE THREAD

**Issue by DD10654** [microsoft/vscode#147433]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0 (Universal)
- OS Version: macOS 12

Steps to Reproduce:

1. open the terminal and drag it to the top

**Comment by DD10654** [comment]
heres a image
![Screenshot 2022-04-14 at 12 39 24 PM](https://user-images.githubusercontent.com/75024070/163332801-9c06f33d-ed88-407a-b105-3fcbc74e033b.png)

so how do I reduce the height?

**Comment by gjsjohnmurray** [comment]
Try a right-click immediately to the left of the filter field. Then choose "Move Panel To Bottom".

![image](https://user-images.githubusercontent.com/6726799/163362083-37aa5046-9c38-44f2-94b4-bb07a7b78462.png)

The arrow button in the top right corner should now point downwards. Click it.

**Comment by DD10654** [comment]
thanks
