### ISSUE TITLE
Add [correct|full] code [completion|suggestion], please!

### ISSUE THREAD

**Issue by weranda** [microsoft/vscode#147405]
I use python with a "Python extension for Visual Studio Code" from Microsof and it doesn't work properly.

I use this code:

```
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String


engine = create_engine("sqlite:///foo.db")
Session = sessionmaker(bind=engine)
session = Session()

Base = declarative_base()


class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True)
    name = Column(String(50))


usr1 = User(
    name = "Iona"
)

sel = session.
```

After the last dot I suppose to see any suggestion, but it doesn't happen. I think it is a bug.
![1](https://user-images.githubusercontent.com/9132570/163251138-131bd17e-90ad-4951-b48b-665ad780c019.png)
![2](https://user-images.githubusercontent.com/9132570/163251162-d3b56d1c-aa7f-4bba-b4d3-9d16d313d540.png)

 Take a look how it works in a PyChart — it works correctly.
![3](https://user-images.githubusercontent.com/9132570/163251224-46711645-aae3-4ac4-b156-679314ffd7b7.png)
![4](https://user-images.githubusercontent.com/9132570/163251255-6d54fc87-16ae-413f-b229-897b019d2234.png)

**Comment by IllusionMH** [comment]
/extPython

As you've mentioned it's Python extension. Please fill in this issue in extension's repo, as this repo is for VS Code editor itself.
