### ISSUE TITLE
Can't change my vscode theme

### ISSUE THREAD

**Issue by WXZhang365** [microsoft/vscode#147462]
Issue Type: <b>Bug</b>

When I changed my theme to other theme(theme is not 'vscode default dark'),
Then i click or open  any file, or edit any file the theme ,then my theme will
auto change to the"vscode default dark".
Also when i open a new window as vscode,the theme is "vscode default dark"

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22598
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (6.47GB free)|
|Process Argv|--crash-reporter-id f71b2f4e-da86-4958-ae93-ce20750249ff|
|Screen Reader|no|
|VM|67%|
</details>

**Comment by aeschli** [comment]
Fid you try running with all extension disabled?
