### ISSUE TITLE
Terminal Link Detection worse without enabled Shell Integrations

### ISSUE THREAD

**Issue by sanbox-irl** [microsoft/vscode#147466]
Issue Type: <b>Bug</b>

Since the Shell Integration support was added, link detection outside it has stopped working. In particular, it does not work on *relative* paths anymore.

So say I'm in `foo` and I have a file `bar.txt`. It will only work if the path is, in full, `path/to/foo/bar.txt`, and not just `bar.txt`, even though `bar.txt` in the path from `cwd`.

Turning on Shell Integration does fix this, but I don't want shell integration on

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:47:29.396Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (7.44GB free)|
|Process Argv|--crash-reporter-id d5a44b8d-191d-4c6e-a8e9-8f7a0eff9ab1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
primer-light|and|0.0.6
vscode-zipfs|arc|3.0.0
shell-syntax|bma|1.0.3
better-toml|bun|0.3.2
path-intellisense|chr|2.8.0
vscode-mac-color-picker|dae|1.0.2
vscode-markdownlint|Dav|0.47.0
gitlens|eam|12.0.6
moxer-icons|Equ|5.8.0
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
vscode-pull-request-github|Git|0.40.0
easy-icons|jam|0.3.1
better-cpp-syntax|jef|1.15.13
vscode-fix-checksums|leh|1.1.0
gml-support|lia|1.7.4
rust-analyzer|mat|0.2.1010
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.5
live-server|ms-|0.2.12
vsliveshare|ms-|1.0.5527
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
gm-code-vsc|san|0.2.4
crates|ser|0.5.10
shader|sle|1.1.5
cmake|twx|0.0.17
luna-paint|Tyr|0.13.2
unity-debug|Uni|3.0.2
vscode-lldb|vad|1.7.0
vscode-icons|vsc|11.10.0
clang-format|xav|1.9.0

(14 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689

```

</details>

**Comment by Panke** [comment]
What exactly is meant with Shell Integration support? I am running into the same issue and would be willing to turn that on if that helps.

**Comment by sanbox-irl** [comment]
Check your settings on most recent update. There's a new thing called "shell integration support"

**Comment by Tyriar** [comment]
This seems to be working as expected for me on both Windows and macOS:

![image](https://user-images.githubusercontent.com/2193314/166475266-b076c2ab-31df-4fcb-9e08-8d7f37a35b77.png)

Note that since we don't know what the cwd is when shell integration is disabled it does a workspace search. Do you see something different?
