### ISSUE TITLE
my vs code is freezing

### ISSUE THREAD

**Issue by jaffaruddin** [microsoft/vscode#147451]
Issue Type: <b>Performance Issue</b>

any operation(selecting any option or while typing) my vs code editor is freezing for about 5-6 seconds 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (3.28GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/91868/Documents/FS_A --crash-reporter-id 7af673a6-fdf7-4ee2-9e58-6f9e8c7129b1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    89	 17536	code main
    0	   150	  5692	   extensionHost
    0	    68	  2848	     "C:\Users\91868\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\91868\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=5692
    0	    14	  8704	     c:\Users\91868\.vscode\extensions\ms-vscode.cpptools-1.9.7-win32-x64\bin\cpptools.exe
    0	     6	 17140	       console-window-host (Windows internal process)
    0	    12	 18524	       c:\Users\91868\.vscode\extensions\ms-vscode.cpptools-1.9.7-win32-x64/bin/cpptools-srv.exe 8704 {D0E967F4-D45C-424A-9273-7181C873F8A8}
    0	    86	  9764	   issue-reporter
    0	    41	  9972	   utility-network-service
    0	   157	 10632	   window (Day2Program2.c - FS_A - Visual Studio Code)
    0	   145	 15392	   gpu-process
    0	    91	 15412	   shared-process
    0	    66	  7332	     ptyHost
    0	    44	  2512	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 17048	       console-window-host (Windows internal process)
    0	    67	 15432	     fileWatcher
    0	    25	 17564	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Day2Program2.c - FS_A - Visual Studio Code)
|    Folder (FS_A): 131 files
|      File types: java(104) xml(6) gitignore(2) iml(2) py(2) pdf(2) c(2)
|                  js(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
better-cpp-syntax|jef|1.15.13
vscode-leetcode|Lee|0.18.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
java|red|1.5.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.0.10
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.0
vscode-java-pack|vsc|0.22.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by weinand** [comment]
It is possible that this issue is caused by an installed extension. Can you try to run VS Code without extensions? From the command line, execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by FrameMuse** [comment]
I have noticed it sometimes happend to me when I switching tabs quite fast. Also I experienced that my vscode **absolutly** not responding but only visually, typing, selecting and the rest are working properly.
