### ISSUE TITLE
[Mac] VSCode crashes on .ts files 

### ISSUE THREAD

**Issue by victorfei** [microsoft/vscode#147473]
VS code virtually unusable for .ts files it constantly crash

CPUs | Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled
Load (avg) | 4, 5, 5
Memory (System) | 16.00GB (0.40GB free)
Process Argv | --crash-reporter-id 241de91c-33b9-4f96-b0d8-ac1453a94228
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
armview | ben | 0.4.6
vsc-material-theme | Equ | 33.4.0
vsc-material-theme-icons | equ | 2.2.1
prettier-vscode | esb | 9.5.0
prettier-eslint-typescript | hb4 | 1.0.5
solidity | Jua | 0.0.139
sort-typescript-imports | mic | 1.4.1
azure-pipelines | ms- | 1.202.0
vscode-azurefunctions | ms- | 1.6.2
vscode-azureresourcegroups | ms- | 0.4.0
vscode-azurestorage | ms- | 0.13.0
vscode-azurevirtualmachines | ms- | 0.5.0
vscode-bicep | ms- | 0.5.6
vscode-cosmosdb | ms- | 0.18.1
vscode-dotnet-runtime | ms- | 1.5.0
azure-account | ms- | 0.10.1
azurecli | ms- | 0.5.0
vscode-node-azure-pack | ms- | 0.2.1
azurerm-vscode-tools | msa | 0.15.6
vim | vsc | 1.22.2

vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135****

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by victorfei** [comment]
yes with nightly insider build with all extensions incl. built in typescript extension build in it still crashes. unfortunately it crashes. this has been persisting for weeks. 
it repros when you type "-" in large typescript projects. this is a very bad bug should be p0 in your ADO tracking item.

**Comment by mjbvz** [comment]
Can you share a minimal project that demonstrates the issue?

**Comment by mjbvz** [comment]
Please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by victorfei** [comment]
[tsserver.log](https://github.com/microsoft/vscode/files/8492546/tsserver.log)
[tsserver2.log](https://github.com/microsoft/vscode/files/8492547/tsserver2.log)
Here are two tsserver log from the time when vscode crashed. I took a brief look, I didn't catch anything obvious

**Comment by mjbvz** [comment]
Thanks. Are there any errors printed in the output panel? If the server runs out of memory for example, it will print an error message there but no in the logs

**Comment by victorfei** [comment]
close this issue as resolved. I had my key mapping to some weird thing so typing '-' ends up closing VSCode.
