### ISSUE TITLE
Typescript died 5 times

### ISSUE THREAD

**Issue by therealgabryx** [microsoft/vscode#147441]
Issue Type: <b>Bug</b>

 

VS Code version: Code 1.66.1 (Universal) (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:49:47.400Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 13973b3c-602b-4bea-a96d-6efa1f191b49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwind-docs|aus|2.0.0
github-markdown-preview|bie|0.2.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-tailwindcss|bra|0.8.1
gitignore|cod|0.7.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
copilot|Git|1.12.5517
gitignore-templates|has|1.0.1
terraform|has|2.21.0
firebase-explorer|jsa|0.3.3
vscode-github|Kni|0.30.7
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.21.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5527
material-icon-theme|PKi|4.15.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
sass-indented|syl|1.8.19
vsfire|tob|1.4.1
quokka-vscode|Wal|1.0.457
glean|wix|5.2.2
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.20

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
pynewfile477:30463512

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
