### ISSUE TITLE
Cannot find code when I copy them into the search bar

### ISSUE THREAD

**Issue by HIIIIIHAAA** [microsoft/vscode#147435]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. open lu_su_enchantment_mission.lua
2. copy line 948 to 1220 into the search bar and it shows no result (it works when I copy them separately in group of 100 lines)
3. The search feature keeps saying invalid regular expression (was working fine about 1 hour ago)
![VSC_search_bug_report](https://user-images.githubusercontent.com/49533042/163329983-0dd9b531-73ed-409b-91a2-018438726df2.png)

**Comment by HIIIIIHAAA** [comment]
also this when i copied into the global search feature
![VSC_search_bug_report02](https://user-images.githubusercontent.com/49533042/163330682-ede36504-d7d4-4e51-bbc3-afc1e45f4b1e.png)

**Comment by HIIIIIHAAA** [comment]
![VSC_search_bug_report03](https://user-images.githubusercontent.com/49533042/163330781-7c3fe268-0cf2-404a-a066-4b44de5b293a.png)

**Comment by gjsjohnmurray** [comment]
What are you trying to achieve by pasting 300 lines of code into the Find field?
