### ISSUE TITLE
Removing the textDocumentNotebook API proposal

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#147414]
The `textDocumentNotebook` api proposal is currently not on track for finalization. See https://github.com/microsoft/vscode/issues/102091#issuecomment-865050645 for details on this

As an workaround, today you can achieve the same functionality with:

```ts
vscode.workspace.notebookDocuments.find(notebook => notebook.getCells().some(cell => cell.document === myTextDocument))
```

We plan to remove the `TextDocument.notebook` property once all consumers have moved off of it:

- [x] LiveShare @alyssajotice @fubaduba 
- [x] Dot net interactive @brettfo, @colombod
- [x] Copilot (and copilot nightly) @Krzysztof-Cieslak (let me know the correct owner if I got this wrong)
- [x] microsoft/vscode-jupyter#9679

If you are on this list, please look into migrating off of this api and let us know if you run into any issues with the migration

**Comment by rchiodo** [comment]
Looks like we weren't really using it. I removed our usage.

**Comment by alyssajotice** [comment]
Live Share is not using it. I will remove from our package.json.

**Comment by hsenag** [comment]
>  Copilot (and copilot nightly) @Krzysztof-Cieslak (let me know the correct owner if I got this wrong)

Thanks for the ping! We've ticketed this to deal with next week (I'm responding on behalf of @Krzysztof-Cieslak as he's not around today)

**Comment by Krzysztof-Cieslak** [comment]
Hey, the use of the API is removed on the Copilot side of things, but the new version of the extension hasn't been released yet.

**Comment by mjbvz** [comment]
@Krzysztof-Cieslak OK can you let me know when it is safe to remove on our side?

**Comment by hsenag** [comment]
@mjbvz sorry we didn't update sooner: we did a release a few days ago so I think we're good for you to remove it.

**Comment by alyssajotice** [comment]
@mjbvz Live Share has not released yet - I will update here once we do.

**Comment by mjbvz** [comment]
Confirmed that dot net is not using this. Will remove them from api consumers

**Comment by alyssajotice** [comment]
Live Share released yeserday - you can remove us from the list of consumers.
