### ISSUE TITLE
--open-url flag does not work on file paths

### ISSUE THREAD

**Issue by bpfoster** [microsoft/vscode#147475]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: CentOS 7

Steps to Reproduce:

1.  Attempt to open a file with `--open-url` flag, e.g.:  `code --open-url /path/to/my/file.txt`
3.  VSCode does not open the file.  If it's not already running, it will launch with the previous session, but not the requested file.  If it's already running, nothing happens.

Running with `--verbose` gives the following lines of interest:
```
[main 2022-04-14T19:11:44.533Z] app#handleURL:  file:///path/to/my/file.txt {
  originalUrl: '/path/to/my/file.txt'
}
[main 2022-04-14T19:11:44.534Z] app#handleURL: windowOpenableFromProtocolLink =  undefined
```

While I don't need to use `--open-url` directly, I do want to use the GNOME "Open with VS Code URL handler" action (https://github.com/microsoft/vscode/blob/main/resources/linux/code-url-handler.desktop) which never works.  I end up changing `--open-url` to `-n` in that file every update.

**Comment by bpfoster** [comment]
This line seems suspicious
https://github.com/microsoft/vscode/blob/a9288be67bab4e9c4dbe62207f01fafc2bdaadcb/src/vs/code/electron-main/app.ts#L1014

Should it not be checking `uri.scheme`?  `authority` on this URL is empty.

**Comment by joaomoreno** [comment]
`/path/to/my/file.txt` isn't a URL. Does it work if you provide `file:///path/to/my/file.txt` instead?

**Comment by bpfoster** [comment]
You can see in the verbose logs above that the path is getting massaged into a `file://` URL.

Ran with `file:///path/to/my/file.txt`, and no, there is no change in behavior.  The only difference is the log has that as the `originalUrl`:
```
[main 2022-04-28T11:22:22.940Z] app#handleURL:  file:///path/to/my/file.txt { originalUrl: 'file:///path/to/my/file.txt' }
[main 2022-04-28T11:22:22.940Z] app#handleURL: windowOpenableFromProtocolLink =  undefined


Also worth noting that `/path/to/my/file.txt` is the format passed by GNOME to the handler.

**Comment by joaomoreno** [comment]
So, a few things:

- `--open-url` is meant for URLs *only*. In fact, that `code-url-handler.desktop` file is specifically about handling URLs. We have [another file](https://github.com/microsoft/vscode/blob/main/resources/linux/code.desktop) which registers VS Code as an opener of files. I wonder why Gnome isn't using that in your case.
- VS Code can only handle URLs meant specifically for itself, ie that start with `code:` or `code-insiders:`.

**Comment by bpfoster** [comment]
Ahh thank you.  I didn't realize but had an old errant `code.desktop` file in `~/.local` that was completely hiding that handler :facepalm:.
Removing that I now see both handlers in the GNOME open dialog.

Think this is therefore a non-issue, closing.
