### ISSUE TITLE
Support using a "clean" environment for the terminal in remote scenarios

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#147421]
Basically the ask is to support `terminal.integrated.inheritEnv` in remote scope.

This setting was added in https://github.com/microsoft/vscode/issues/70248 to support using a "clean" environment for the terminal. For Python extension this would mean that activations for conda work as expected. As the setting is user-scoped, this is still an issue for remote scenarios like dev container: https://github.com/microsoft/vscode-python/issues/18510

**Comment by Tyriar** [comment]
Python setting `terminal.integrated.inheritEnv` actually caused a bunch of issues to get reported about people having it set and not knowing it. I'm not too happy with that setting's current implementation and we have had other discussions around terminal profiles/environments for Python recently which I think supercede this.
