### ISSUE TITLE
SCSS auto-formattter break tailwindcss prefix classes on save

### ISSUE THREAD

**Issue by DibyodyutiMondal** [microsoft/vscode#147548]
Issue Type: <b>Bug</b>

This is what I type
```
 @apply lg:container ;
```

This is what it becomes after a save
```
 @apply lg: container;
```

That extra space between `lg:` and `container` breaks the parsing for tailwind scss. Scss complains that it cannot find the class called `lg:` 

I am using this on WSL, but I haven't checked if this happens in Windows

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.16GB free)|
|Process Argv|--crash-reporter-id b664f6b3-a4a8-4a5d-9282-2ac18f232630|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|Memory (System)|7.76GB (0.38GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
ng-template|Ang|13.3.1
vscode-tailwindcss|bra|0.8.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
vscode-graphql|Gra|0.4.1
git-graph|mhu|1.30.0
angular-console|nrw|17.15.0
vsfire|tob|1.4.1
vscodeintellicode|Vis|1.2.19

</details>

**Comment by DibyodyutiMondal** [comment]
This also affects custom tailwind rules..
This is what I type
```
  @apply grid gap-6 mt-6 
    grid-cols-[repeat(1,minmax(12rem,1fr))] 
    sm:grid-cols-[repeat(2,minmax(12rem,1fr))] 
    lg:grid-cols-[repeat(3,minmax(12rem,1fr))]
```

This is what happens on save
```
  @apply grid gap-6 mt-6 grid-cols-[repeat(1, minmax(12rem, 1fr))] sm: grid-cols-[repeat(2, minmax(12rem, 1fr))] lg:grid-cols-[repeat(3, minmax(12rem, 1fr))]
```

It removes the line breaks which I inserted for readability (which is still fine). But it inserts spaces after the commas, which breaks the parsing and throws scss build errors.

**Comment by aeschli** [comment]
We use [beautifyjs](http://jsbeautifier.org/) as the underlying SCSS formatter. Would you mind filing this request directly against https://github.com/beautify-web/js-beautify ?
