### ISSUE TITLE
Toggle the Terminal Panel

### ISSUE THREAD

**Issue by MRezaFarahmand** [microsoft/vscode#147559]
when terminal panel is selected to show at the right of screen, there is not a way to move it back at the bottom.

**Comment by gjsjohnmurray** [comment]
Did you try right clicking on the panel's title bar?

**Comment by MRezaFarahmand** [comment]
Yes, of course. There is not any item in appeared list. Here in below please find a screen shot of what is happening there.


***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by gjsjohnmurray** [comment]
You cannot email screenshots to GitHub. Please use the website and paste it into your reply.

**Comment by MRezaFarahmand** [comment]
![Untitled](https://user-images.githubusercontent.com/91828242/163707466-e0f142b5-8d82-4f71-961a-f1e4aba4b7e1.jpg)

**Comment by MRezaFarahmand** [comment]
![Untitled](https://user-images.githubusercontent.com/91828242/163707508-f7a722a0-13c0-41d1-a572-6dd23948db43.jpg)

**Comment by MRezaFarahmand** [comment]
Please keep me informed about this issue.

**Comment by sbatten** [comment]
@MRezaFarahmand It looks like you have moved the terminal into the secondary side bar. I apologize for the confusion here as we changed courses a little bit ago on how to recommend moving views (e.g. the terminal) to the side. To move the terminal back, you can right-click the terminal icon and "Reset location".

**Comment by MRezaFarahmand** [comment]
thanks for your reply. finally it's done.
