### ISSUE TITLE
Visual glitches

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147518]
I've noticed a rendering glitch like this a few random times. This one I could repro by following the same actions - scroll to the right, move the cursor back, then some text is missing until I move the cursor. I assume a chromium/electron rendering glitch?

![Recording 2022-04-15 at 10 19 05](https://user-images.githubusercontent.com/323878/163601038-15ffbba1-64cf-40e1-935c-c194bec8e077.gif)

**Comment by rzhao271** [comment]
Hi Rob, does this issue still occur on the latest Insiders?
If so, does launching Code with `--disable-gpu` work?

**Comment by roblourens** [comment]
I don't remember seeing it in awahile
