### ISSUE TITLE
error with highlight

### ISSUE THREAD

**Issue by MineDark909** [microsoft/vscode#147575]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66.2
- OS Version: Windows 11

Steps to Reproduce:

I open my vscode, the code has lots of error highlighted even there are  no error in the code.
![image](https://user-images.githubusercontent.com/87105792/163694310-99b9c4cf-7671-42d8-a7fa-5aba5f793db0.png)
 
Pls help me

**Comment by sandy081** [comment]
Please file issue against the extension that is generating these errors. I assume this extension is python extension
