### ISSUE TITLE
Enable/disable ports to automatic port fowarding

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#147580]
While the vscode's automatic port fowarding is oftentimes great, I found that it sometimes causes issues or crashes, bugs. For example I see a lot the port fowarding on vscode conflicts with previous vscode's same port fowarding, or with already-opening port fowarding ports. 

I see on #108346 `remote.autoForwardPorts` would work to completely disable the feature, but I would suggest there should also be a feature that enables users to allow/block which ports to auto port forward and ports not to auto port forward.

**Comment by alexr00** [comment]
This is possible already with the `remote.portsAttributes` setting. For example:
```
	"remote.portsAttributes": {
		"3000": {
			"onAutoForward": "ignore"
		}
	},
```
