### ISSUE TITLE
CaskaydiaCove NF is not rendered properly in VScode editor

### ISSUE THREAD

**Issue by sba923** [microsoft/vscode#147517]
Issue Type: <b>Bug</b>

A piece of PowerShell code contains the following lines:

```powershell
# first part of $progress_re within first () is 
# U+0393 U+00fb U+00ea U+007c U+0393 U+00fb U+00c6 U+007c 
# U+005b U+2588 U+2589 U+258a U+258b U+258c U+258d U+258e U+258f U+2592 U+005d
$progress_re = '(Γûê|ΓûÆ|[█▉▊▋▌▍▎▏▒])+\s+([\d\.]+\s+.B\s+/\s+[\d\.]+\s+.B|[\d\.]+%)'
```

At a PowerShell 7.2.2 in Windows Terminal Preview 1.13.10733.0 this is correctly rendered as:

![image](https://user-images.githubusercontent.com/12860484/163596938-ca0ddd8f-81ef-40ee-9aeb-10c7994c5df5.png)

In VScode's editor this is rendered as:

![image](https://user-images.githubusercontent.com/12860484/163596978-f33ae37c-6d9c-4430-932b-dcf20609e876.png)

The "block character" glyphs are not rendered correctly.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (18.07GB free)|
|Process Argv|s:/powershell --crash-reporter-id cf71009a-be63-4901-9a7d-985810ce477a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (85)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.2.4
ng-template|Ang|13.3.1
vscode-color|ans|0.4.5
vscode-tidyhtml|anw|1.10.0
code-gnu-global|aus|0.2.2
better-toml|bun|0.3.2
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
autoit|Dam|1.0.7
vscode-markdownlint|Dav|0.47.0
ini-for-vscode|Dav|0.0.4
xml|Dot|2.5.1
vscode-PSStackoverflow|Dou|0.0.2
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
vscode-go-test-adapter|eth|0.1.6
vscode-firefox-debug|fir|2.9.6
platformio|for|0.3.0
vscode-pull-request-github|Git|0.40.0
go|gol|0.32.0
gc-excelviewer|Gra|4.2.54
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
live-html-previewer|hdg|0.3.0
beautify|Hoo|1.5.0
rest-client|hum|0.24.6
angular2-switcher|inf|0.3.4
reg|ion|1.0.3
github-pr|jas|1.0.0
plantuml|jeb|2.17.2
eml|lei|0.4.0
rainbow-csv|mec|2.2.0
Angular-BeastCode|Mik|10.0.3
azure-pipelines|ms-|1.202.0
csharp|ms-|1.24.4
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.1
cpptools|ms-|1.9.7
powershell-preview|ms-|2022.4.0
test-adapter-converter|ms-|0.1.6
vscode-typescript-tslint-plugin|ms-|1.3.4
debugger-for-chrome|msj|4.13.0
angular2-inline|nat|0.0.17
printcode|nob|3.0.0
angular-console|nrw|17.15.0
indent-rainbow|ode|8.3.1
platformio-ide|pla|2.4.3
quicktype|qui|12.0.46
geo-data-viewer|Ran|2.5.0
java|red|1.5.0
vscode-yaml|red|1.6.0
prettier-vscode|Sim|2.0.7
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
vscode-inline-values-powershell|Tyl|0.0.5
lorem-ipsum|Tyr|1.3.1
vscodeintellicode|Vis|1.2.19
vscode-svg-previewer|vit|0.7.0
vscode-java-debug|vsc|0.40.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
yog-plantuml-highlight|Yog|0.0.5
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.0
html-css-class-completion|Zig|1.20.0
ab-html-formatter|zov|0.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by meganrogge** [comment]
Does changing the setting terminal.integrated.gpuAcceleration help?

**Comment by sba923** [comment]
Nope. Tried `on`, `off` and `canvas`, closing and restarting VScode each time.
Can you repro?

**Comment by sba923** [comment]
Note that I can't repro this on all my PCs. What should I be looking at to dig further on the one machine where I filed the issue from?

**Comment by Tyriar** [comment]
This is talking about the editor, not the terminal. I recommend closing this off as won't fix for the editor as you're simply rendering what the font is giving you, and the terminal and WT draw those characters to the canvas by hand.

**Comment by alexdima** [comment]
VS Code is built with Electron, which is built with Chromium. The font rendering in the editor is delegated to Chromium, so the font glyph shaping and rendering is unfortunately not directly under control. If you are able to reproduce this problem in a Chromium-based browser such as Edge or Chrome, then please report the issue directly against Chromium at https://bugs.chromium.org/p/chromium/issues/list
