### ISSUE TITLE
I have 2 problems.

### ISSUE THREAD

**Issue by coder65536** [microsoft/vscode#147557]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
![Ekran Alıntısı 136](https://user-images.githubusercontent.com/103519704/163673114-d6975fbd-bf8f-4314-82b3-fd76be23a57f.PNG)
I wrote a sample post. I don't want to see the error red line at the bottom of the text. How can I do it.

2.
![Ekran Alıntısı 137](https://user-images.githubusercontent.com/103519704/163673140-db65e674-8dbe-4eb6-bfb3-4e12b842d203.PNG)
There are 2 problems under the problems. Even if there is an error in the code, I don't want to see the error notification under the problems. How can I do it.

**Comment by gjsjohnmurray** [comment]
Sel language mode to Plain Text

**Comment by coder65536** [comment]
> Dil modunu Düz Metin olarak ayarlayın

Sir, I couldn't. Can you tell me with a photo?

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/164247950-dc4ef4b9-d4b5-428b-8bad-0c81a2a6d47d.png)

**Comment by sandy081** [comment]
@coder65536 Please try changing the language mode to Plain Text otherwise file an issue against Python extension if you want to configure the problems

**Comment by coder65536** [comment]
![image](https://user-images.githubusercontent.com/103519704/165763098-bbf47328-0f19-4a87-b471-e54cc2a94992.png)
Sir, I made prose, but the tools in this photo are not visible. The vehicles in this photo I want should appear. But underlined errors and errors should not appear in the problems section next to the terminal .
