### ISSUE TITLE
Git - Odd behaviour reverting git ranges in Working Tree mode

### ISSUE THREAD

**Issue by jakobnator** [microsoft/vscode#147520]
Version 1.66.2
Windows 10
All Extensions disabled

In a git repo try reverting a range with multiple changes in file:
![image](https://user-images.githubusercontent.com/6003430/163601123-20b5a0d3-0edb-4691-b61b-f4a9624361a9.png)

![image](https://user-images.githubusercontent.com/6003430/163601136-8245ba17-43cc-4661-b6af-e9228f7a6224.png)

Ranges outside of selected range are modified usually with making copies of function calls, repetitive else statements or repetitive brackets that were not previously there. In this example its adding two function calls with an alternating  tab order.
![image](https://user-images.githubusercontent.com/6003430/163601076-070d945c-502d-424a-aee7-a54e4d6a17dc.png)

This is somewhat difficult to reproduce as it happens in only  certain situations that I have not been able to determine is the qualifying condition. I have attached two files before.c and after.c If you commit before.c in a new git repo, then paste after.c after the initial commit. Try and revert the range of the last few lines and you will see the bug occur locally.

EDIT: It appears to have to do with the previous range of changes having whitespace before the function call that was not previously there....

before.c
`
LOCATION_SCREEN_FUNCTIONS
void CustomerScreenRatingUnitsNextScreen(void)
{

   if(input->RatingId == 2)
   {
      CustomerScreenSetInstance(23);
      CustomerScreenActivate(D4D_FALSE);
   }
   else
   {
      if(input->RatingId <= 52)
      {
         CustomerScreenEscape();
      }     
   }
}

void CustomerScreenRatingUnitsPreviousScreen(void)
{
   //DO NOT SAVE SELECTION
   CustomerScreenEscape();
}

#ifdef CONFIG_AUTOTEST
void CustomerScreenRatingUnitsScreenData(json_t* Autotest)
{
    AppListSelectScreenSerializeScreenData(Autotest);
}
#endif
asdf
`

after.c
`
LOCATION_SCREEN_FUNCTIONS
void CustomerScreenRatingUnitsNextScreen(void)
{

   if(input->RatingId == 2)
   {
      CustomerScreenSetInstance(23);
      CustomerScreenActivate(D4D_FALSE);
   }
   else
   {
      if(input->RatingId <= 52)
      {
         CustomerScreenEscape();
      }     
   }
}

LOCATION_SCREEN_FUNCTIONS
void CustomerScreenRatingUnitsNextScreen(void)        
{

   if(input->RatingId == 2)
   {  
      CustomerScreenSetInstance(23);
      CustomerScreenActivate(D4D_FALSE);     
   }
   else
   {
      if(input->RatingId <= 52)
      {
               CustomerScreenEscape();       
      }     
   }
}

void CustomerScreenRatingUnitsPreviousScreen(void)
{
   //DO NOT SAVE SELECTION
   CustomerScreenEscape();
}

#ifdef CONFIG_AUTOTEST
void CustomerScreenRatingUnitsScreenData(json_t* Autotest)
{
AppListSelectScreenSerializeScreenData(Autotest);
}
#endif
`

**Comment by lszomoru** [comment]
Apologies for not getting back to you on this until now. In recent days I have pushed some changes that address some of the issues with the "stage/unstage/revert selected ranges" commands. I would really appreciate if you could try the latest [VS Code Insiders release](https://code.visualstudio.com/insiders/) (version information below) and would let me know if that resolves the problem. In case you are still able to reproduce the issues I would really appreciate if you could:
1. See if you are able to reproduce in a simple repository which you could share
2. Share a recording (https://gifcap.dev) assuming that you are able to consistently reproduce the issue
3. Let me know if you are invoking the command from a text editor or a diff editor
4. If you are using a diff editor see if you can reproduce the problem when using the "Revert Selection" command available in the editor gutter. 

```
Version: 1.97.0-insider
Commit: cf2ebd91b8e42e3bc5ab0e85e3323c886a977ffe
Date: 2024-12-18T06:50:13.779Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Darwin arm64 24.2.0
```

**Comment by alexr00** [comment]
@lszomoru I'm not able to repro the original issue, so I can't verify it. Is there a way to repro this reliably?

**Comment by lszomoru** [comment]
@alexr00, I was not able to come up with a set of repro steps for this one hence the "author-verification-requested" label. There have been couple of fixes that went in this area during December hence I optimistically closed this issue as well. I will add the "verified" label and wait to hear back from the issue author.
