### ISSUE TITLE
TS Server repeatedly crashes across multiple machines

### ISSUE THREAD

**Issue by ShaunSpringer** [microsoft/vscode#147531]
Issue Type: <b>Bug</b>

I believe this came from a filename change that was case sensitive on a case sensitive volume. Happening across two machines. Downgrading to vscode 1.62 from 1.66 is the only way we've seen it resolve

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|10, 10, 7|
|Memory (System)|32.00GB (1.29GB free)|
|Process Argv|--crash-reporter-id 1182677e-4c46-44ef-aff6-7facd0f47f54|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.8.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
vscode-open-in-github|fab|1.3.0
vscode-hcl-format|fre|1.0.0
terraform|has|2.21.0
file-downloader|min|1.0.11
vscode-docker|ms-|1.21.0
vscode-typescript-tslint-plugin|ms-|1.3.4
vscode-stylelint|sty|1.2.2
vscode-icons|vsc|11.10.0
HCL|who|0.0.5

(8 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690
vscaat:30438848

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

My bet is on `vscode-typescript-tslint-plugin`

**Comment by qazhub** [comment]
It's reproducible with all extensions disabled. However it is not reliably to reproduce. I only noticed this issue after upgrading to 1.66.2. However after downgrading to 1.66.1 this still happens. The TS server crashing would cause CPU usage spikes during typing, resulting in lagging.

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

Look through that log file for errors or stack traces. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this
