### ISSUE TITLE
no stdout content when debugging node with execSync

### ISSUE THREAD

**Issue by jeffmcaffer** [microsoft/vscode#147525]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: VS Code on Win10

```
Version: 1.66.0 (user setup)
Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5
Date: 2022-03-30T05:50:14.623Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043
```
Steps to Reproduce:

1. [install the GitHub Command line](https://github.com/cli/cli#installation). this may happen with other apps/scenarios but this repros 100% of the time on multiple machines
2. run `gh auth status` directly in the shell and verify that there's some output. (I'm authenticated so I see something like
```
github.com
  ✓ Logged in to github.com as jeffmcaffer (/home/jm/.config/gh/hosts.yml)
  ✓ Git operations for github.com configured to use ssh protocol.
  ✓ Token: *******************
```
3. write a little test program that `execSync`'s `gh` like this (assume it's `index.js`)
```javascript
const child_process = require('child_process')
const out = child_process.execSync('gh auth status').toString()
console.log(out)
```
4. run `node index.js` and notice that the output of `gh auth status` shows up and looks the same
5. In VS Code, add a Node launch config with all the normal defaults and point at your `index.js`. 
6. Hit run and notice that the program exits fine but no output. If you put a breakpoint on the `console.log` line, `out` is an empty string
7. For fun, use just `gh auth` and redo all the above. Notice that it works correctly both from the command line and VS Code. (shows the help text)

There may be something funky going on with `gh` but regardless it appears that VS Code is somehow launching node in a different way than from the shell as the behavior of `index.js` is different.

I have looked at the environment vars in the launched node process and the exec'd process (use `execSync('printenv')` on linux) and they look reasonable.

The net result is that while my app runs fine from the command line, I can't debug it at all as it depends on getting the output from these commands.

**Comment by jeffmcaffer** [comment]
Quick follow up. I poked around some and found that `gh` writes the output of `gh auth status` to `stderr` (not sure why but that's a separate conversation). That led me to look at `stdout` vs `stderr`.  I'm not sure this is directly related but I noticed that the following gives different output when run directly in a shell vs run from the VS Code debugger.

```javascript
process.stderr.write('process.stdout\n')
process.stderr.write('process.stderr\n')
console.log('console.log')
console.error('console.err')
```

In the shell you get all four lines output. In the debugger you just get 
```
console.log
console.err
```

This is somewhat separate from the original problem but perhaps there is something more general going on around how the VS Code debugger is setting up and managing the stdio streams.

**Comment by connor4312** [comment]
> Hit run and notice that the program exits fine but no output. If you put a breakpoint on the console.log line, out is an empty string

It seems like the debugger is working okay here, the debugger does add environment variables that affect Node.js debugging (namely NODE_OPTIONS) but as the GH CLI is written in Go that should not make any difference.

> I'm not sure this is directly related but I noticed that the following gives different output when run directly in a shell vs run from the VS Code debugger.

 This is expected behavior, which can be configured with the [`outputCapture` attribute](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_launch-configuration-attributes).

**Comment by jeffmcaffer** [comment]
Thanks for the pointer on `outputCapture`.  

For the real problem noted here, the behavior of the Node program is different when run from the command line vs the shell. When run from the shell, `const out = child_process.execSync('gh auth status').toString()` has a value. When run in the debugger it does not. To reliably debug, the behavior of the target program should be as close to the same as possible. 

What's different between the two exectuions?

**Comment by connor4312** [comment]
This looks like TTY detection done in the GH CLI. It's weird that they don't print anything when not run under a TTY, but that appears to be what it is. You can add `"console": "integratedTerminal"` to your launch.json (or use auto attach) to run the process in a TTY.
