### ISSUE TITLE
VS Code 1.65 and 1.66 won't launch in Windows Server 2019 version 1809

### ISSUE THREAD

**Issue by lbtagao** [microsoft/vscode#147563]
Does this issue occur when all extensions are disabled?: Yes. This is a fresh installation so there are no extension. Tried starting with '--disable-extension' nonetheless and it behaves the same. I would get the popup that says "the window is not responding"

- VS Code Version: 1.65.2 and 1.66.0
- OS Version: Windows Server 2019 version 1809

Steps to Reproduce:

1. Disabled antivirus
2. Reinstalled with backward-compatibility with Windows 8.

**Comment by lbtagao** [comment]
https://user-images.githubusercontent.com/19632636/165785535-e5851fb8-3821-4f95-a091-3afc53c2db93.MOV

**Comment by lbtagao** [comment]
Hi there! Sorry, had to upload mov. As you can see, vscode won't launch at all. This is a "fresh" install so it does not have any extension installed/enabled. I'm trying to launch it just after installation. I've tried installing it on a couple other windows server 2019 using either the system or user installer and i get the same "window not responding". I don't see this issue on our vs code installation on windows server 2016.

**Comment by deepak1556** [comment]
Can you launch the application from command line with following command `code --verbose` and attach the output.

**Comment by lbtagao** [comment]
> Can you launch the application from command line with following command `code --verbose` and attach the output.

Here you go. 

[vscode_verbose.txt](https://github.com/microsoft/vscode/files/8596426/vscode_verbose.txt)

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!
