### ISSUE TITLE
Incorrect highlighting when { } are used inside YAML literal style

### ISSUE THREAD

**Issue by ivanz** [Microsoft/vscode#14753]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Having issues with the highlighting of some AWS CloudFormation YAML templates which have some jsons fragments in YAML literal. Seems the `{ }` may be tripping over the highlighting. Note how on the screenshot the highlighting stops working after the `Bla:` block. 

![image](https://cloud.githubusercontent.com/assets/79742/19851554/83ff2db2-9f56-11e6-9459-582146d56bfd.png)

**Comment by aeschli** [comment]
```
Bla:
  - 
  {
    "jsonStuff": {
      "${something}": {
        "bla1":"sd",
        "bal2":"${asdf}",
        "bla3":"$[asdf]"
      }
    }
  }
this: is,
```

Seems to work with spaces after the colons

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#18
