### ISSUE TITLE
A 'return' statement can only be used within a function body.ts(1108)

### ISSUE THREAD

**Issue by crymic** [microsoft/vscode#147538]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Windows 11

Steps to Reproduce:

1. In Javascript I get the error A 'return' statement can only be used within a function body.ts(1108) whenever I use a return. It doesn't need to be within a function or not, Can be used with an If statement.
2. Code Example in ES6
```js
let findToken = canvas.tokens.placeables.find(i => i.actor.id === "whatever");   
if (!findToken) return {}; // this shows up as an error, this should be 100% fine cause it will hault the script at this point.
```

**Comment by gjsjohnmurray** [comment]
Maybe #143220 or #147267
