### ISSUE TITLE
ctrl+click open a url in terminal will add some data in the end and break my own url

### ISSUE THREAD

**Issue by xiaolang124** [microsoft/vscode#147500]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: win11	10.0.22000 Build 22000

Steps to Reproduce:

1. Install teamsfx cli.
2. Use ```teamsfx account login m365```, this will generate login url. CTRL+CLICK the url. It will open a web with normal url + some string. And it will break login.

![image](https://user-images.githubusercontent.com/13211513/163545137-1988471d-ac3d-42b3-8aa3-82e0d3a8434c.png)

https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=7ea7c24c-b1f6-4a20-9d11-9ae12e9e7ac0&scope=https%3a%2f%2fdev.teams.microsoft.com%2fAppDefinitions.ReadWrite+openid+profile+offline_access&redirect_uri=http%3a%2f%2flocalhost%3a44479&client-request-id=d649f5d8-1326-4723-839a-5ada5fbdf79f&response_mode=query&response_type=code&x-client-SKU=msal.js.node&x-client-VER=1.0.0-beta.6&x-client-OS=linux&x-client-CPU=x64&client_info=1&code_challenge=L1nTxQtRaZeMzYMU2abSk2rc7QAM08MqKrU3D_mhYhU&code_challenge_method=S256&prompt=select_account%25u00a0&sso_nonce=AwABAAEAAAACAOz_BAD0_3Yr84foUnBXuZ5J8zcUGqT3nvZngKcfkO_0GGRTvlsdfSv9WZDAGaLi0JiD3G1aF3niqLcL0mhyzxb2Pc9EqosgAA&mscrid=d649f5d8-1326-4723-839a-5ada5fbdf79f

![image](https://user-images.githubusercontent.com/13211513/163545256-544bed98-5d8e-49c8-ac43-808041e31d74.png)

**Comment by meganrogge** [comment]
what's the part of the string that's appended and unexpected?

**Comment by xiaolang124** [comment]
Sorry for the inconvenience, this is my bad. There is some hidden character in the url, so this is not VsCode problem. Thanks.
