### ISSUE TITLE
[c++] Syntax highlighting makes mistake when meeting with "using namespace std;"

### ISSUE THREAD

**Issue by LittleSaya** [Microsoft/vscode#1475]
Here is the screenshot:
![1](https://cloud.githubusercontent.com/assets/16049823/11912961/4afe4f40-a68f-11e5-8284-243af43165c8.PNG)
The first "std" is colored blue, but the second is colored white. Should they both be colored white?
And, both ";" are colored blue...I think they should originally be white.

Version: 0.10.5
Color Theme: Dark (default color theme)

**Comment by aeschli** [comment]
This is a consequence that in VSCode we flatten the text mate scopes. The second namespace name matches the 'function' scope created for 'int main()'
Not easy to fix.

**Comment by jamesqo** [comment]
This also seems to be happening with some C# files as well. I don't have a screenshot right now, but I'll post one if I come across it.

**Comment by mjbvz** [comment]
I believe this has been fixed:

<img width="291" alt="screen shot 2017-02-15 at 4 19 12 pm" src="https://cloud.githubusercontent.com/assets/12821956/23001528/8f635ba4-f39a-11e6-97f2-90b040265c1b.png">
<img width="278" alt="screen shot 2017-02-15 at 4 19 35 pm" src="https://cloud.githubusercontent.com/assets/12821956/23001527/8f62d4e0-f39a-11e6-892f-70836ea7e126.png">
