### ISSUE TITLE
Acesso negado

### ISSUE THREAD

**Issue by tanivia-code** [microsoft/vscode#147569]
Issue Type: <b>Bug</b>

C:\Users\User\AppData\Local\Programs\Microsoft VS Code\unins000.exe

Um erro ocorreu enquanto tentava criar um arquivo no diretório destino: acesso negado.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500 6-Core Processor               (6 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (17.88GB free)|
|Process Argv|--crash-reporter-id 1711e3b6-64d0-48fe-ba7f-aec5a86dacb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 5 3500 6-Core Processor (6 x 3593)|
|Memory (System)|24.99GB (21.86GB free)|
|VM|0%|
</details><details><summary>Extensions (166)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
es7-javascript-class-snippets|abr|0.4.0
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
bracket-pair-colorizer|Coe|1.0.62
bracket-pair-colorizer-2|Coe|0.2.4
moxer-icons|Equ|5.8.0
chrome-codespaces-keymap|eri|0.0.4
auto-close-tag|for|0.5.14
codespaces|Git|1.7.0
bootstrap5-snippets|Han|1.2.5
mysql-syntax|jak|1.3.1
better-cpp-syntax|jef|1.15.13
vscode-csharp-snippets|jor|1.1.0
unity-code-snippets|kle|1.3.0
ligatures-limited|ksh|1.4.1
dotenv|mik|1.0.1
vscode-language-pack-pt-BR|MS-|1.66.3
vscode-edge-devtools|ms-|1.4.7
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
notepadplusplus-keybindings|ms-|1.0.7
vsonline|ms-|1.0.3075
debugger-for-edge|msj|1.0.15
vscode-autohotkey|sle|0.2.2
go-mysql-highlighter|Sti|0.0.2
ayu|tea|1.0.5
import-font|tit|1.0.1
vscode-icons|vsc|11.10.0
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
unity-snippets|Ycl|0.1.2
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
copy-relative-path|ale|0.0.2
CustomColoring|Alt|1.4.4
shaderlabvscodefree|aml|1.3.0
colorify|Att|1.0.3
code-gnu-global|aus|0.2.2
vscode-database|baj|2.2.3
vscode-django|bat|1.10.0
c-cpp-compile-run-windows|BDZ|0.0.2
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-devtools-for-chrome|cod|0.0.7
gitignore|cod|0.7.0
doxdocgen|csc|1.4.0
vscode-mysql-client2|cwe|5.1.6
c-cpp-compile-run|dan|1.0.15
vscode-markdownlint|Dav|0.47.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
zsh-completion-script|dua|1.0.0
dircolors|dun|1.1.1
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
fix-compile-commands|el-|0.0.3
windows-explorer-context-menu|ele|3.2.1
prettier-vscode|esb|9.5.0
chromium-source-opener|Fan|1.0.22
git-project-manager|fel|1.8.2
code-runner|for|0.11.7
sfdx-codespaces-auth|gfa|0.0.1
vscode-pull-request-github|Git|0.40.0
cloudcode|goo|1.17.2
vscode-graphql|Gra|0.4.1
beautify|Hoo|1.5.0
rest-client|hum|0.24.6
gzipdecompressor|Hyu|1.2.0
vscode-heroku|iva|1.2.6
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.15.13
vscode-csharp-snippets|jor|1.1.0
vscode-colorize|kam|0.11.1
vsc-python-indent|Kev|1.15.0
wsl-path|kgr|0.1.0
dotnet-core-essentials|Kis|0.0.8
unity-code-snippets|kle|1.3.0
csharpfixformat|Leo|0.0.84
workspace-layout|los|0.0.7
code-beautifier|mic|2.3.3
file-downloader|min|1.0.11
mindaro|min|1.0.120220125
mongodb-vscode|mon|0.9.2
vscode-docker|ms-|1.21.0
vscode-language-pack-pt-BR|MS-|1.66.3
csharp|ms-|1.24.4
vscode-dotnet-sdk|ms-|0.8.0
vscode-aks-tools|ms-|0.0.16
vscode-kubernetes-tools|ms-|1.3.7
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
live-server|ms-|0.2.12
vscode-typescript-next|ms-|4.7.20220415
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
color-highlight|nau|2.5.0
live-server-preview|neg|0.1.4
magic|Net|0.18.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
mysql-inline-decorator|odu|0.0.5
oracledevtools|Ora|21.4.0
heroku-command|pko|0.0.8
typescript-hero|rbb|3.0.0
java|red|1.5.0
vscode-commons|red|0.0.6
vscode-rsp-ui|red|0.23.11
vscode-server-connector|red|0.25.3
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
partial-diff|ryu|1.4.3
vc6-keybindings|sam|0.2.0
markdown-preview-enhanced|shd|0.6.2
guides|spy|0.9.3
autoimport|ste|1.5.4
code-spell-checker|str|2.1.11
code-spell-checker-portuguese|str|0.1.11
tabnine-vscode|Tab|3.5.42
cursive|The|0.8.5
python|tht|0.2.3
unity-tools|Tob|1.2.12
vscode-status-bar-format-toggle|tom|3.0.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
unity-debug|Uni|3.0.2
intellicode-api-usage-examples|Vis|0.0.10
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vscode-spring-initializr|vsc|0.9.0
nodejs-extension-pack|wad|0.1.9
games-dev-extension-pack|wal|1.0.0
wallaby-vscode|Wal|1.0.335
jinja|who|0.0.8
windows-terminal|wra|2.1.0
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0
unity-snippets|Ycl|0.1.2
city-lights-icon-vsc|Yum|1.1.3
vscode-open-in-github|ziy|1.3.6

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689

```

</details>

**Comment by FelipeNogueira92** [comment]
Vá na pasta do VS Code clique com o botão direito e selecione propriedades 
em segurança habilite todas as permissões para os usuários.
depois disso o erro deve parar de aparecer... Foi assim que consegui aqui.
