### ISSUE TITLE
lost files

### ISSUE THREAD

**Issue by LeonardoClark** [microsoft/vscode#147591]
Someone help me, my VSCode closed, and deleted half of my code, and it has automatic salvation, how do I restore it??

I still don't understand how this happened, I really need this backup, I heard that you send it to the database, can you provide it to me please???

**Comment by bpasero** [comment]
Maybe try with https://code.visualstudio.com/updates/v1_66#_local-history

**Comment by LeonardoClark** [comment]
> Maybe try with https://code.visualstudio.com/updates/v1_66#_local-history

Here is a DB file, is there no way to recover it?
C:\Users\AppData\Roaming\Code\User\workspaceStorage\df62bc63fd320c9017249d10efd5bac3\ms-vscode.cpptools

**Comment by bpasero** [comment]
There is a command to restore any file contents from local history:

![image](https://user-images.githubusercontent.com/900690/163758094-c64c8293-d624-4070-998a-4a5cd83bfa71.png)
