### ISSUE TITLE
Scroll bar for status bar, or some method for small screen sizes

### ISSUE THREAD

**Issue by wyatthuckaby** [microsoft/vscode#147564]
I normally do my development work on my workstation, who's screen is large enough to support my status bar w/ extensions. However i also have an older mac, which with the same extensions, i cannot see all of the items on my status bar, which is a problem, because cmake-tools uses the status bar for quick "run w/ debug" or "run" buttons. 

If possible, i would like to see something like this get implemented to support my smaller screen.

thanks!

**Comment by gjsjohnmurray** [comment]
See also #6651

**Comment by sbatten** [comment]
see https://github.com/microsoft/vscode/issues/154708
