### ISSUE TITLE
not reporting method name typo as an error

### ISSUE THREAD

**Issue by jessewriter** [microsoft/vscode#147523]
Issue Type: <b>Bug</b>

      if(wordIndex+1 == word.Length){
        console.log('matched');  
        return true
    }

I spent the longest time trying to figure out why this app would not properly compare two numbers!
I would console log 'wordIndex' and 'word.length' and when both were 5 i would still get a false comparison, why why i said to myself
unfortunately the next day i finally found the error, a damn upper case L for Length instead of javascripts built in length method
There are no methods with **Length** not sure how this even compiles
VS Code did nothing to flag this as a typo

VS Code should identify that a method is called that does not exist

Node also failed me with no warnings or errors :(

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:41.156Z)
OS version: Linux x64 5.16.19-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.35GB (6.61GB free)|
|Process Argv|--unity-launch --crash-reporter-id d73e7858-6231-427c-99c9-7c4ef12ea8d8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by mjbvz** [comment]
To see this type of error, you need to enable semantic check (type checking) in your JS files: https://code.visualstudio.com/Docs/languages/javascript#_type-checking

**Comment by jessewriter** [comment]
@mjbvz  i tested this with `//@ts-check` at the beginning of my files and vscode still did not recognize that array.Length is a typo :(
