### ISSUE TITLE
quickOpenRecent Command Shows InputBox in quick pick

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#147511]
```
workbench.action.quickOpenRecent
```

Uses "quick navigation" and is behaving as expected but it's odd there's an input box shown in the quick pick even though you'd never be able to use it.

We should hide it like Ctrl+Tab.

**Comment by TylerLeonhardt** [comment]
Fixed in https://github.com/microsoft/vscode/pull/147493

**Comment by TylerLeonhardt** [comment]
Verification:

1. Add following keybinding to keybindings.json:

```
     {    
         "key": "ctrl+m",    
         "command": "workbench.action.quickOpenRecent"    
     },    
```

2. Use keybinding in VSCode


vscode will try to quick open recent files, then will try to close current workspace and open previously opened workspace.

This is expected and now you shouldn't see the inputbox/filter box in the quick pick anymore.

**Comment by rzhao271** [comment]
So, we have to use up/down arrows to navigate through the options now? I don't see anything happen when I try typing to get to a result.

**Comment by TylerLeonhardt** [comment]
@rzhao271 can you elaborate? After this change you shouldn't be typing anything because it's supposed to behave like Ctrl+Tab

**Comment by bpasero** [comment]
To get the input field back, simply use `workbench.action.openRecent` instead. That is also the default command we bind to `Ctrl+R`.
