### ISSUE TITLE
I have a problem.

### ISSUE THREAD

**Issue by coder65536** [microsoft/vscode#147528]
![image](https://user-images.githubusercontent.com/103519704/163628597-ecaaee07-2766-4d67-a531-e8a04aa4c0db.png)

I have a problem. I don't want to see error notification in visual studio code. I don't want to see the error notification inside the square white line. How can I disable this feature? I am using microsoft python plugin in vs code. I disabled the yellow bulb feature without deleting and disabling the microsoft python plugin. Accordingly, How can I disable the error notification within the square white line without deleting and deactivating the microsoft python plugin?

**Comment by IllusionMH** [comment]
/question

You should start with settings that contain `decorations`
