### ISSUE TITLE
Go to Symbol should position text cursor on name of target

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#14759]
- VSCode Version: Code - Insiders 1.7.0-insider (0706b425537d8cfe2766eac00662ecf988c7ed7f, 2016-10-28T13:00:19.188Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.3|
|vscode-docker|PeterJausovec|0.0.6|
|regex|chrmarti|0.0.6|
|vscode-eslint|dbaeumer|1.0.7|
|ghlink|dt|0.0.4|
|gitlens|eamodio|0.5.5|
|tslint|eg2|0.5.39|
|PowerShell|ms-vscode|0.7.2|
|csharp|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|2.1.0|
|diff|rafaelmaiolla|0.0.1|
|kustovscode|seanmcbreen|0.0.1|
|vscode-open-in-github|sysoev|1.2.0|

---

Steps to Reproduce:

1. Go to Symbol that's a class or a class member (possibly others)
2. The text cursor is positioned on the first modifier before the name

This breaks the flow of keyboard navigation for actions like Find All References, Rename Symbol, etc., because the user now has to navigate the cursor to the symbol's name first.

**Comment by rebornix** [comment]
I found it share the same experience with Go To Definition.

**Comment by dbaeumer** [comment]
We simply use the position we get from the tsserver. So need to check what they return (using tracing option)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12000

**Comment by waderyan** [comment]
@dbaeumer I may have migrated that issue too early. Can you clarify what you mean by 

> So need to check what they return (using tracing option)

Is this on our end or TypeScript's?

**Comment by dbaeumer** [comment]
This is on our end. I would do the following: enable tsserver tracing in VS Code's setting and do goto definition. If the trace shows that TS gives us the position of the visibility keyword (public, private, ...) then we should move this it the TS team. If not then it looks like a bug on our end.

**Comment by waderyan** [comment]
Ok. This fell through the cracks but getting to it now. 

I tested with this code:

```typescript
class Foo {
    public x;
}

var foo = new Foo();

foo.x;
```

![image](https://cloud.githubusercontent.com/assets/2449568/20285023/96198c3a-aa74-11e6-97db-80251ae39ccf.png)

Here is the output I see from TS. 

![image](https://cloud.githubusercontent.com/assets/2449568/20285042/b0117cec-aa74-11e6-952b-988108ba8fc3.png)


From reading this it looks like TS Server is providing the offset at the location of the `public` keyword rather than the target name. Can you confirm I understood the log correctly?

**Comment by dbaeumer** [comment]
Yes the reported offset is at the beginning of public. I recommend to ask the TS team to change this.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12270
