### ISSUE TITLE
Can't expand object in debugger variable list

### ISSUE THREAD

**Issue by Krimik** [Microsoft/vscode#14755]
- VSCode Version: 1.6.1
- OS Version: Windows 7

Steps to Reproduce:

1. Stop at any breakpoint, debugging javascript
2. Cannot expand any objects in watch/global list but can watch each variable individually http://i.imgur.com/bLtgZoR.jpg Arrays can be expanded just fine

**Comment by weinand** [comment]
@Krimik you are using VS Code Insiders and not v1.6.1, correct?

**Comment by Krimik** [comment]
This was 1.6.1, I checked "About", but now this issue fixed itself, I guess restart helped... 
Could it have been that I am opening folders on Google Drive ?
