### ISSUE TITLE
CompletionItem decorator

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14757]
_From @TheColorRed on October 25, 2016 15:46_

Is there a way to add a decorator to a CompletionItem?

I would like to add a color like the way CSS shows the color of the item. Is this possible? If so how can I do it?

_Copied from original issue: Microsoft/vscode-extension-vscode#40_

**Comment by jrieken** [comment]
Yeah - use [`kind: Color`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2252) and make the label match a color, like `#22ee44` or `hsl(122, 221, 32)`
