### ISSUE TITLE
Open editor window from terminal output

### ISSUE THREAD

**Issue by dedalebeda** [Microsoft/vscode#14752]
Would be nice if appropriate editor can be opened based on output from integrated terminal. Possibly on specific position if line:column is specified

**Comment by weinand** [comment]
@dedalebeda it is already possible to launch vscode from the command line (e.g. the integrated terminal) on a specific position. Am I missing something from your request?

![2016-10-31_16-28-25](https://cloud.githubusercontent.com/assets/1898161/19859892/1fc8cffc-9f87-11e6-8044-b73d81a74709.png)

**Comment by dedalebeda** [comment]
Sorry for being unclear. Let me give an example: TypeScript compiler produces an error, but I have to locate the error line manually. I would like to click on the red text on the screenshot below to open exact line of code.
![image](https://cloud.githubusercontent.com/assets/7872442/19860383/c98b84f2-9f88-11e6-866c-e21da46917f1.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7321
