### ISSUE TITLE
formatting for single line methods in TypeScript is behaving strangely

### ISSUE THREAD

**Issue by polshgiant** [microsoft/vscode#147516]
Issue Type: <b>Bug</b>

Create a new typescript file with an empty function.

```
export function test() {
}
```

Into that function, type the following `if (true) { debugger; }`.  As soon as you type the semicolon, notice that the auto-formatting places the closing brace on the next line, at the beginning of the line:

```
export function test() {
    if (false) { debugger;
}
}
```

This behavior started happening about 2 or so weeks ago.  This occurs even with extensions disabled.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.618Z)
OS version: Windows_NT ia32 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3998)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (17.00GB free)|
|Process Argv|--crash-reporter-id 575b3752-ea8e-4290-9beb-26dcea7c7126|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by polshgiant** [comment]
@mjbvz Just tried it on the insiders build and the issue does not exist there, so I think that means the issue can be closed.  👍
