### ISSUE TITLE
[API] Support `render()` on `MarkdownString`

### ISSUE THREAD

**Issue by zardoy** [microsoft/vscode#147530]
Let's take a code snippet for example to illustrate the problem:
```ts
const md = new vscode.MarkdownString().appendCodeblock('const num = 5', 'typescript')
console.log(md.value)
```
It would print:
```
    ```typescript
    const num = 5
    ```
```
But in some cases (especially when parsing `MarkdownString`s from completions of other providers), I want to get human-readable part only:
```ts
md.render() // const num = 5
```

By the way, I don't even know if there a npm package to do in easy way.

**Comment by mjbvz** [comment]
`MarkdownString` is only intended for VS Code's consumption. It is not a generic utility type for working with markdown

Try using a library such as `marked` for that (this is what VS Code uses internally to render markdown)
