### ISSUE TITLE
(cmd + . ) keyboard shortcut not being able to set in VSCode (in Flutter)

### ISSUE THREAD

**Issue by aakarshy** [microsoft/vscode#147506]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.  Press cmd + shift + p to open the command palette
2. Type Preferences: Open Keyboard Shortcuts
3. Select any combination that you want to change and try to set it to cmd + .
4. It doesn't allow me to set this combination

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/49898433/163561873-704fb764-3210-439b-aea8-ddef69d14437.png">
Ignore 'shift + cmd' in there. Was taking a screenshot. But the goal is to set any combo as "cmd + . "

**Comment by sandy081** [comment]
@alexdima Assigning to you as its seems to be related to keybindings dispatch.

**Comment by alexdima** [comment]
Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.
