### ISSUE TITLE
Cannot open menu bar shortcuts with native title bar on KDE Plasma

### ISSUE THREAD

**Issue by ElHyperion** [microsoft/vscode#147594]
Does this issue occur when all extensions are disabled?: Yes

The menu bar only appears but the individual menus cannot be opened with keyboard shortcuts such as Alt+F for the File menu, only by clicking them with a cursor. I tried changing **window.menuBarVisibility** or enabling **window.enableMenuBarMnemonics** but to no effect. My menu bar works in any other applications that I use in my KDE Plasma environment. Custom menu bar works fine, but I would like to use the Native one instead, to merge with my main system bar.

- VS Code Version: 1.66.2
- OS Version: Linux x64 5.17.1-3-MANJARO

Steps to Reproduce:

1. Set up Plasma KDE with an AppMenu widget in the title bar (I'm using Latte)
2. Set **"window.titleBarStyle": "native"** or keep the default
3. Press Alt+F or Alt+E shortcuts to open File/Edit menus

Menu bar focused with cursor:
![image](https://user-images.githubusercontent.com/5313557/163718168-74b716da-cc35-4d33-938a-7c59490f718f.png)

**Comment by krisutofu** [comment]
I recently installed Garuda with Plasma Desktop. Same issue for me.
