### ISSUE TITLE
Hover shows different type than associated type definition (reached via Go to Definition)

### ISSUE THREAD

**Issue by kleinfreund** [microsoft/vscode#147558]
Issue Type: <b>Bug</b>

1. Paste the following JavaScript snippet into an editor (if necessary, change the language to JavaScript):

   ```javascript
   const element = document.querySelector('a')
   element.getAttribute('test')
   //      ^^^^^^^^^^^^ hover here.
   ```

2. Hover over `getAttribute`. The return type of the `Element.getAttribute` method is shown as `string`.
3. Activate the “Go to Definition” command for `getAttribute`. This opens [TypeScript’s `lib/lib.dom.d.ts` file](https://github.com/microsoft/TypeScript/blob/main/lib/lib.dom.d.ts#L4908-L4911). The return type of the `Element.getAttribute` method is shown as `string | null`.

**Expected outcome**:

The return type of `Element.getAttribute` on hover is shown as `string | null`.

**Actual outcome**:

The return type of `Element.getAttribute` on hover is shown as `string`.

**Comments**:

- There is likely a good explanation for why this is the case that I’m unaware of, but writing some basic JavaScript code and taking a return type as shown VS Code for granted could lead me to unexpected errors in my program if I didn’t know that `Element.prototype.getAttribute` can in fact return `null` when `qualifiedName` can’t be resolved to an existing attribute on the `Element`. I expect the types on hover and when going to the type definition to be the same.
- The same thing happens with `/** @type {HTMLElement} */ (element).dataset.test` where `test` is shown to be a `string` when it can be `undefined` as well (according to the interface `DOMStringMap` and according to testing it in Firefox).

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-39-generic snap
Restricted Mode: No

Extensions: none (ran VS Code via `code --disable-extensions`)

**Comment by mjbvz** [comment]
This is happening because you do not have [strict null checks](https://www.typescriptlang.org/tsconfig#strictNullChecks) enabled

After enabling it, VS Code will show `| null`
