### ISSUE TITLE
Add support for yaml git diff

### ISSUE THREAD

**Issue by SebTardif** [microsoft/vscode#147599]
Currently, if you use repository git diff, and the file is yaml, it shows nothing different when the yaml is totally different due to indentation between both version. Beside yaml, Python also care about indentation, so I guess both could be handled in one fix.

For example:

```
aaa:
  bbb:
```

is shows as same as:

```
aaa:
bbb:
```

It tooks more than a week to find a bug in the application I'm supporting. I did a lot of comparing with a similar version that works, and I coudn't find anything significant!

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/163738462-d32ce883-2145-4717-977b-d9c76e263fbd.png)

There is a "Show Whitespace Differences" button if only whitespaces changes.

![image](https://user-images.githubusercontent.com/1330321/163738749-40c5a79c-da29-472d-8e83-95b3d3e6261f.png)

There is a button on toolbar to toggle that globally.

It's also possible to enable it for only some file types

```json
  "[yaml]": {
    "diffEditor.ignoreTrimWhitespace": false
  }
```

AFAIK it's impossible to add language-specific default value directly in Code's source code.

**Comment by SebTardif** [comment]
I didn't know we could control ignoreTrimWhitespace for specific file type. It's a good start. If we could just do that for 'trailing white space so having a toggle, probabaly named ignoreTrailingTrimWhitespace and it set as false by default for "[yaml]", "[yml]", and "[py}", that would be perfect.

**Comment by roblourens** [comment]
The settings are the correct answer since this is a user preference
