### ISSUE TITLE
Warn when variable rename can break code

### ISSUE THREAD

**Issue by orenelbaum** [microsoft/vscode#147586]
Currently, when using the variable rename refactor (F2), this refactor could actually break your code.
For example:
```js
const a = 1;
{
  const b = 2;
  console.log(a);
}
```
If I rename the variable `b` to `a` we get:
```js
const a = 1;
{
  const a = 2;
  console.log(a);
}
```
Which breaks the original code.
I would love VSCode to warn me in this case that this action could potentially break my code.

**Comment by mjbvz** [comment]
@jrieken Adding you since I believe this would require some new APIs. We can throw an error to prevent the rename or ask user for confirmation on rename

However a better flow IMO would be to show a warning in the rename widget as the user is typing out the new name

**Comment by xinaesthete** [comment]
Another way rename can break; I just found myself absent-mindedly renaming something to `functionName();`, which lead to the code calling it changing to `functionName();();`.
