### ISSUE TITLE
How to comment in html code that already has comments?

### ISSUE THREAD

**Issue by thefatwhale** [microsoft/vscode#147549]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: both Windows 7 x64 SP1 & Neon Linux 5.24

Steps to Reproduce:

1. write some html code like this
```html
<h1>sth</h1>
<!-- comment -->
<h2>sth</h2>
```
2. select them and <kbd>Ctrl</kbd>+<kbd>/</kbd> Or <kbd>Alt</kbd>+<kbd>Shift</kbd>+<kbd>A</kbd>
3. it will comment like this
![image](https://user-images.githubusercontent.com/50515732/163664664-fec0ae2f-99bc-471f-9971-df4a2f760ec8.png)

**Comment by DibyodyutiMondal** [comment]
Tbh, this is not a `new release` issue, it has always been like this

**Comment by thefatwhale** [comment]
# @aeschli how about this?
![image](https://user-images.githubusercontent.com/50515732/164895453-90b996c6-696b-4577-a047-5a325dbf6460.png)
# Or
![image](https://user-images.githubusercontent.com/50515732/164895561-db0a391d-3e10-4db6-9655-7053bf143a02.png)
Learn from Jetbrains IDE

**Comment by aeschli** [comment]
Our comment feature by design does not modify the content of the commented code except for adding the comment delimiters.
That keeps it simple and predictable.

No changes planed
