### ISSUE TITLE
Allow to open folder from any opened file in Code

### ISSUE THREAD

**Issue by marcosdiez** [Microsoft/vscode#14750]
Let's say I am editing blah.html on visual studio code.
Later I realize I have to do some changes on blah.css, which is in the same folder as blah.html.

I want to open the explorer tab (not Windows Explorer) on Visual Studio Code, right click on blah.html and click on "Open Folder Here".

Doing this should make the folder where blah.html is stored available on Visual Studio Code, just as if I clicked on "File / Open Folder ..."

Sorry if you could not understand me earlier. Please inform me if I still wasn't able to fully express myself.

**Comment by bpasero** [comment]
![Uploading image.png…]()

**Comment by marcosdiez** [comment]
Hi..

I guess I was not clear. Whenever one clicks on "Open Folder with Code", the whole folder should show on Microsoft Visual Studio Code, so one can easily edit the files in the same folder.

It has nothing to do with Windows Explorer.

**Comment by bpasero** [comment]
@marcosdiez I am confused, your first words are talking about windows explorer, so how can this have nothing to do with Windows Explorer?

Do you want to right click into the empty white space of an opened folder in the Windows Explorer to open Code here?

**Comment by marcosdiez** [comment]
Let's say I am editing blah.html on visual studio code.
Later I realize I have to do some changes on blah.css, which is in the same folder as blah.html.

I want to open the explorer tab (not Windows Explorer) on Visual Studio Code, right click on blah.html and click on "Open Folder Here".

Doing this should make the folder where blah.html is stored available on Visual Studio Code, just as if I clicked on "File / Open Folder ..."

Sorry if you could not understand me earlier. Please inform me if I still wasn't able to fully express myself.

**Comment by bpasero** [comment]
Makes sense now 👍
