### ISSUE TITLE
Severe graphical issues

### ISSUE THREAD

**Issue by afuelcell** [microsoft/vscode#147519]
Not sure how / what caused this to happen. Happens across vscode windows (remote ssh & local). 

Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/92111973/163601196-14529484-ad3f-4617-839c-2544917b8ba8.png)

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 *censored*

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: cloud|
|OS|*censored*|
|CPUs|*censored*|
|Memory (System)|62.03GB (8.17GB free)|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
Bookmarks|ale|13.2.4
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-boost-jam|mlo|0.0.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
vscode-remote-extensionpack|ms-|0.21.0
sublime-keybindings|ms-|4.0.10
material-icon-theme|PKi|4.15.0
code-settings-sync|Sha|3.4.3
python-extended-snippets|tus|0.0.1
vscode-icons|vsc|11.10.0
json-parse-validator|Adr|1.1.2
cform|aws|0.0.24
xml2json|bui|1.2.4
vscode-terminal-capture|dev|0.0.1
gitlens|eam|12.0.6
vscode-diff|fab|1.4.2
vscode-lombok|Gab|1.0.1
sendtoterminalplus|ivo|1.0.4
vscode-docker|ms-|1.21.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
java|red|1.5.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
velocity|sod|0.2.0
vscode-terminal-here|Tyr|0.2.4
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

(3 theme extensions excluded)

</details>

**Comment by afuelcell** [comment]
It does not appear to affect the text inside integrated terminal

**Comment by deepak1556** [comment]
Can you check if the issue repros with `code --disable-gpu` ?
