### ISSUE TITLE
Poor syntax highlighting in HC-Light markdown code blocks

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#147652]
<img width="1375" alt="image" src="https://user-images.githubusercontent.com/8586769/163884583-6eeddaba-a60f-4f99-b6e1-5a25f2cd32b3.png">

**Comment by daviddossett** [comment]
Yikes. Looks like this is a regression. Shouldn't take long to fix..I'm on it.

**Comment by daviddossett** [comment]
Fixed:

<img width="477" alt="CleanShot 2022-04-18 at 15 14 21@2x" src="https://user-images.githubusercontent.com/25163139/163886094-c2b505a0-f858-487d-a81d-d36755ade8d6.png">

**Comment by JacksonKearl** [comment]
Snappy, thanks!
