### ISSUE TITLE
Incorrect bash/zsh syntax highlighting

### ISSUE THREAD

**Issue by VorpalBlade** [microsoft/vscode#147673]
Issue Type: <b>Bug</b>

Vscode gets confused by the following fragment of zsh code (where the first line is taken verbatim from the `_arguments` completion helper code that is bundled with zsh):

```zsh
"${(@)^${(@)tmp:#^*:*}//:/[}]"
# This part should not be in the string in zsh
```
The second line (and everything after in the file) is incorrectly considered part of the string by VSCode's shell syntax highlighting. For some to me unfathomable reason it appears VSCode does not properly detect the end quote of the string on the first line.

Here is how it looks in vscode:
![image](https://user-images.githubusercontent.com/3315306/163949844-068051b4-0957-4279-a09b-3b11f85871d6.png)

Removing the last ] in the string "fixes" the highlighting (but of course breaks the code): 
![image](https://user-images.githubusercontent.com/3315306/163950040-560aed56-a131-4a9b-8f34-b79e53ba763a.png)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.17.3-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2816)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.12GB (24.32GB free)|
|Process Argv|--disable-extensions --crash-reporter-id a77f92e1-4f12-4a9f-aad2-4dc61886222c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions disabled

**Comment by VorpalBlade** [comment]
After debugging this I believe the issue may be that VSCode gives higher "precedence" to `[]` than `{}`. I believe that the [ and ] at the end in the code are in fact unrelated (though I admit the code is hard to read!).

```zsh
"${var//:/[}]"
```
is a simplified example that still exhibits the issue. The correct interpretation of it is
1. `$var` but with all `:` replaced with `[`
2. A final `]` outside the variable substitution.

Zsh processes nested substitutions from inside out, so the whole `${...}` is processed before ] is considered, and a lone `]` at the end of the string is a normal literal character, nothing fancy going on.

**Comment by VorpalBlade** [comment]
By the way, this is not zsh specific, I can reproduce this with the following bash code, which also syntax highlights incorrectly in vscode in the same manner:
```bash
v="a:b"
echo "${v/:/[}]"
# Prints a[b]
```

**Comment by alexr00** [comment]
We get our shellscript grammar from https://github.com/atom/language-shellscript, but the textmate grammar there is no longer maintained. This issue would need to be solved by adopting a new shellscript grammar: https://github.com/microsoft/vscode/issues/77675
