### ISSUE TITLE
VSCode crashed while trying to restore full-screen

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#147606]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Restore full screen does not work if **Prefer tabs: Always**

VS Code version: Code - Insiders 1.67.0-insider (a9288be67bab4e9c4dbe62207f01fafc2bdaadcb, 2022-04-15T05:28:12.573Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 2|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id 74c2ad87-67ad-4b90-b2c4-247f0ea3d1f9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|2.7.0
vscode-fish|bma|1.0.27
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.1
vscode-css-modules|cli|0.4.1
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
vscode-deno|den|3.12.0
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
LogFileHighlighter|emi|2.15.0
prettier-vscode|esb|9.5.0
shell-format|fox|7.2.2
vscode-google-translate|fun|1.4.13
vscode-pull-request-github|Git|0.40.0
go|gol|0.32.0
todo-tree|Gru|0.0.215
r|Iku|2.4.0
vscode-phpfmt|kok|1.0.31
sftp|lix|1.12.10
rust-analyzer|mat|0.2.1010
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
HTMLHint|mka|0.10.0
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
gather|ms-|2022.3.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.7
color-highlight|nau|2.5.0
proto|pet|0.0.2
material-icon-theme|PKi|4.15.0
polacode|pnp|0.3.4
java|red|1.5.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
postcss|ric|2.0.0
code-settings-sync|Sha|3.4.3
gitconfig|sid|2.0.1
code-spell-checker|str|2.1.11
code-spell-checker-russian|str|2.0.3
vscode-styled-components|sty|1.7.4
vscode-stylelint|sty|1.2.2
vscode-sql-lit|the|0.4.0
vscodeintellicode|Vis|1.2.19
vscode-nginx|wil|0.7.2
viml|Xad|2.1.1
vscode-open-in-github|ziy|1.3.6

</details>

## Steps

> Set macOS **Prefer tabs** to **Always** to reproduce this error

1. Download VSCode Insiders
2. Open a 3-4 apps in native tabs (on macOS-only)
3. Set these settings
```json
 "window.nativeTabs": true,
  "window.dialogStyle": "native",
  "window.titleBarStyle": "native",
  "window.menuBarVisibility": "compact",
  "window.nativeFullScreen": true,
  "window.restoreFullscreen": true,
  "window.restoreWindows": "all",
```
4. Exit VSCode (Cmd+Q)
5. Try to re-open VSCode

## Related issues

- https://github.com/microsoft/vscode/issues/76537
- https://github.com/microsoft/vscode/issues/131018

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by dalisoft** [comment]
@bpasero Here it is dump

[a72505bd-653a-4333-97aa-aa47a57c10bf.dmp.zip](https://github.com/microsoft/vscode/files/8504601/a72505bd-653a-4333-97aa-aa47a57c10bf.dmp.zip)

**Comment by dalisoft** [comment]
@bpasero Currently at version `1.70.2` it works, really, some repos cannot be closed but for other repos works
