### ISSUE TITLE
Layout control is missing when `nativeTabs` enabled on macOS

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#147655]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2 & 1.67.0-insider
- OS Version: macOS 11.6.5 (20G527)

Feature https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_65.md#new-layout-control-options is not working when `nativeTabs` set to `true`

Steps to Reproduce:

1. Set `nativeTabs: true`
2. Try to show three layout keys

Note: I remember it worked somehow before and now noticed it is not available ?))

**Comment by ctf0** [comment]
good catch, however its not showing at all on insiders builds
```
Version: 1.74.0-insider
Commit: e8eb39bac26ddc87f27ed69fa06c54cd230d18f9
Date: 2022-11-03T18:59:03.601Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

**Comment by sbatten** [comment]
Layout Controls require the custom title bar to be enabled. Native tabs are not compatible with the custom title bar.
