### ISSUE TITLE
Error and warnings gets overrided by dependencies projects

### ISSUE THREAD

**Issue by supchi31** [Microsoft/vscode#14762]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:43:46.054Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions: christian-kohler.path-intellisense-1.1.0, ms-vscode.csharp-1.4.1, qinjia.seti-icons-0.1.2

Steps to Reproduce:

1.Create 2 projects, write basic code in each, reference project 1 in project 2
2.Make unecessary using in project 1
3. Type an error in project 2, project 2 shows error for a brief moment, then just shows warning of project 1

Very annoying

**Comment by weinand** [comment]
@supchi31 you are talking bout C# projects?

**Comment by supchi31** [comment]
Yes, indeed

I guess the problem comes from omnisharp, I might have posted the issue in the wrong place.
Sorry.

**Comment by weinand** [comment]
@supchi31 I'll move the issue.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#855
