### ISSUE TITLE
Font settings lost after an auto update. (And can not recover manually. )

### ISSUE THREAD

**Issue by chemwolf6922** [microsoft/vscode#147611]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Windows 10.0.19042

Steps to Reproduce:

1. Cascadia Code is working and working correctly before.
2. Did not touch the computer for a weekend and VS code auto updated. 
3. Cascadia Code is somehow lost in settings.json and not working anymore.
4. Can not recover by adding the font again. 

Suggestions: I have encountered lots of newly baked bugs due to auto updates in the past. If the stability and quality can not be ensured. How about change the default behavior to not auto update?

**Comment by dbaeumer** [comment]
I just tested this under Windows and I can enable Cascadia Code font without problems. Any additional steps?

**Comment by chemwolf6922** [comment]
After reinstalling the font and resetting vscode font settings for several times, Cascadia Code is working again. I am not sure what caused and fixed the problem. During the whole process, Cascadia Code was working fine in Windows terminal.

**Comment by alexdima** [comment]
I'm happy you were able to resolve the problem. I have heard of this once before and it got resolved by uninstalling the font, restarting the PC, and installing the font again. I am not sure what would cause a working font to become unusuable... Maybe there was also a Windows update in the meantime 🤷 . In any case, we (VS Code) delegate all font rendering to the browser (Chromium) and don't really interact with the OS directly for font reading, etc, so there's no change we can possibly do in VS Code itself to improve this. If you notice this happening again, please also check how Chrome or Edge behave.

**Comment by chemwolf6922** [comment]
After a system reboot. Cascadia code is lost again in vs code... And it is working fine in other applications (e.g. windows terminal).

**Comment by chemwolf6922** [comment]
I wrote a simple html page and Cascadia Code is not working in Edge... Should I report this issue to the Cascadia Code repo or even send feedback to Windows? (I guess I should just switch to a mac. )

**Comment by alexdima** [comment]
@chemwolf6922 Please report to https://bugs.chromium.org/p/chromium/issues/list?q=topics (Edge is also built with Chromium, just like VS Code)
