### ISSUE TITLE
use regular expression  *\t*

### ISSUE THREAD

**Issue by jonnijoe1990** [microsoft/vscode#147627]
use regular expression  *\t*
![image](https://user-images.githubusercontent.com/7115690/31597794-f78e7938-b27c-11e7-8bbf-7a699ad7a1ee.png)

_Originally posted by @purocean in https://github.com/microsoft/vscode/issues/36321#issuecomment-336790788_

This is not working in the current release on MacOS

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide full steps to reproduce this problem with proper version info.
