### ISSUE TITLE
VSCode not functioning behind proxy

### ISSUE THREAD

**Issue by stefanofiorentino** [Microsoft/vscode#14764]
- VSCode Version: 1.6.1
- OS Version: OS X 10.11.4

Steps to Reproduce:

1. F1->ext install

The only way to have this functioning is
1. Open User Settings 
2. Write in settings.json
```
{
    "http.proxy": "http://172.16.1.1:8080/"
}
```

Take care of use "http://". 
` require('url').parse('172.16.1.1:8080') `highlighted the error in parsing host and hostname.

I found this thanks to @joaomoreno at this [link](https://github.com/microsoft/vscode/issues/69#issuecomment-185199160)

**Comment by rebornix** [comment]
@stefanofiorentino if you can download extensions with `http.proxy` set correctly, that's basically what's `http.proxy` used for.

If there is no problem to download ext with proxy, then I'd like to close this one.

**Comment by stefanofiorentino** [comment]
@joaomoreno it took me almost 2 hours to found the right info at the link you proposed the fix. Just think to help others find the solution faster. By the way, thanks.

**Comment by joaomoreno** [comment]
I see what you are saying. But the settings file should've indicated something was wrong about the format. Didn't you get a warning, when using the value `172.16.1.1:8080`?

![image](https://cloud.githubusercontent.com/assets/22350/19920297/373c3e2e-a0d8-11e6-8129-41985ce21128.png)

**Comment by stefanofiorentino** [comment]
I missed the warning, you right.
Thanks.
