### ISSUE TITLE
unknown or unsupported transport disabled in mongodb for vscode

### ISSUE THREAD

**Issue by captcha781** [microsoft/vscode#147624]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.x
- OS Version: Linux Ubuntu 20.04 focal ARM64

Steps to Reproduce:

1.Install VS Code
2.Install mongodb and start the mongodb server on terminal
3.Install mongodb extension for vscode
4.Connect to the mongodb server

Here comes the issue,
![Screenshot from 2022-04-18 17-57-04](https://user-images.githubusercontent.com/58650753/163808247-ff3c2867-53f8-42a5-a28f-46009b057801.png)

But the MongoDB Shell works perfectly fine.
I tried to solve by searching this on internet but I can't.

**Comment by IllusionMH** [comment]
/causedByExtension

This error comes from extension and should be reported in extension repo first.
