### ISSUE TITLE
Option for updating all extension at a time

### ISSUE THREAD

**Issue by HEGADE** [microsoft/vscode#147696]
I dunno whether this feature is already built into  vscode or not, but I wanted an option  or a button to update the all vs code extension at a time

**Comment by nhedger** [comment]
The command `Update All Extensions` already exists.

To see it, you must have `@outdated` extensions and `extensions.autoUpdate` must either be set to `false` or `onlyEnabledExtensions`.

**Comment by HEGADE** [comment]
ok thanks
