### ISSUE TITLE
Error when I open integrated terminal (on Mac)

### ISSUE THREAD

**Issue by brennanMKE** [Microsoft/vscode#14768]
- VSCode Version: 1.6.1
- OS Version: MacOS El Capitan

Steps to Reproduce:

1. Open Integrated Terminal
2. See error displayed at the top

I have 2 MacBooks with VSCode installed. One works fine and the other has this error. I have ready other issues related to the integrated terminal not working related to folders with spaces or special characters but that is not the case here. There is no folder in the path which is unusual.

How can I get more information about the error? I opened the Console and did not see anything logged there after attempting to open the integrated terminal. I'd like to figure out why this is happening so I can fix it and start using there terminal within VSCode.

**Comment by brennanMKE** [comment]
Possibly related: https://github.com/Microsoft/vscode/issues/14528

**Comment by Tyriar** [comment]
@brennanMKE are you in a directory with non-ascii character like in https://github.com/Microsoft/vscode/issues/7727?

**Comment by brennanMKE** [comment]
I tried opening my home folder which is `/Users/username` without any special characters and it still fails. Is there any place I can look for additional error logging?

**Comment by Tyriar** [comment]
No there is not as it's run in a different process and no error information is sent back other than the exit code right now.

This error occurs when the shell process exits immediately. Typically their is either non-ascii text (pre 1.7) or you have a bad shell setup (`terminal.integrated.shell.osx`, `terminal.integrated.shellArgs.osx`). Do you have those settings set?

[This is the line that is relevant](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L263), it contains the environment that will be used by the terminal as well as the command (`PTYSHELL`) and args (`PTYSHELLARG`). If you can debug to that line it will probably reveal what's going wrong.

**Comment by brennanMKE** [comment]
I opened up workspace settings and found the shell was set to `/bin/false` which I did not set myself. This is a computer was set up by the company by IT. Maybe they set it that way.

My shell also was not configured since I use `.bash_profile` so I symlinked `.profile` and `.bashrc` to it so there VSCode integrated terminal is configured and has the `PATH` set up properly.

Maybe there is a way to detect this bad setting and warn the user.

**Comment by Tyriar** [comment]
I've never seen anyone else have this sort of issue, I suppose they set `$SHELL` to `/bin/false` for some reason as that's what `"terminal.integrated.shell.osx"`'s default value is derived from on OSX. So you can override this inside VS Code by using "terminal.integrated.shell.osx": "/bin/bash" or by setting the SHELL env variable if you have access to do that.

There is an issue open for showing a better error message here https://github.com/Microsoft/vscode/issues/9087
