### ISSUE TITLE
[Accessibility] No API support to add tooltip for tree section

### ISSUE THREAD

**Issue by HuihuiWu-Microsoft** [microsoft/vscode#147675]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.0
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. We're supporting accessibility for our extension but there's no API to add tooltip for tree section. User will not know the brief introduction of what the tree is about:
![image](https://user-images.githubusercontent.com/73154171/163953304-fbc2d654-5ad9-4f9e-988c-3b7c4eaaf7bd.png)

**Comment by isidorn** [comment]
@HuihuiWu-Microsoft you can use the [AccessibilityInformation](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L10094) to set accessbility labels on the items.

Why would you want to change the tooltip of the whole Split View section?
Built-in vscode views do not do this. Why do you think your custom view should have a different tooltip than the name of the view?

**Comment by HuihuiWu-Microsoft** [comment]
> @HuihuiWu-Microsoft you can use the [AccessibilityInformation](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.d.ts#L10094) to set accessbility labels on the items.
> 
> Why would you want to change the tooltip of the whole Split View section? Built-in vscode views do not do this. Why do you think your custom view should have a different tooltip than the name of the view?

Hi @isidorn , personally I'm OK with current behavior and it's raised by accessibility team during our onboarding process.

**Comment by isidorn** [comment]
Then please talk to your accessibility team so they provide a clear use case :)
Let's close this as we do not plan to add this functionality. Also 0 users requested this.
Thanks

**Comment by Ashutoshsahoo164** [comment]
Hi @isidorn I have logged a new bug, explaining the issue correctly .
https://github.com/microsoft/vscode/issues/148113

Please check the bug. Thanks
Please don't close the bugs, the bugs will be only closed by trusted tester post verification.
@HuihuiWu-Microsoft FYI
