### ISSUE TITLE
Provide completion for preLaunchTask and postDebugTask of launch configuration

### ISSUE THREAD

**Issue by apupier** [microsoft/vscode#147678]
in launch.json file,  for a Launch configuration, it is possible to provide `preLaunchTask` and `postDebugTask`, it will be convenient to provide completion for tasks which are defined globally and locally.

Bonus: when providing snippets, to have a variable to access this list of tasks too.

**Comment by roblourens** [comment]
Yep, this is actually a bug that we are discussing: https://github.com/microsoft/vscode/issues/142642

**Comment by roblourens** [comment]
Btw @lramos15, backlog candidates bot did not show up in the 7 hours it was on that milestone
