### ISSUE TITLE
Error occured when building APK, terminal's pty host is unresponsive

### ISSUE THREAD

**Issue by linxkaa** [microsoft/vscode#147622]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 20.3.0

Steps to Reproduce:

1. I tried to build my flutter apk using `Task: run build task` for building an APK (its the same result when manually type in the terminal itself)
i run this command in terminal `flutter build apk --flavor dev --release -t lib/core/main/main_dev.dart`
This is the task command on `.vscode` folder:
```json
 {
      "label": "Android : Build App",
      "type": "shell",
      "command": "flutter",
      "args": [
        "build",
        "${input:buildType}",
        "--flavor",
        "${input:buildFlavor}",
        "--release",
        "-t",
        "lib/core/main/main_${input:buildFlavor}.dart"
        // "--obfuscate",
        // "--split-debug-info=obfuscate"
      ],
      "problemMatcher": [],
      "group": "build"
    },
```
3. It shows `The connection to the terminal pty host process is unresponsive,...` just like this [issues](https://github.com/microsoft/vscode/issues/117542) 
![image](https://user-images.githubusercontent.com/57997512/163797673-f8c1920b-6e94-450a-9b0e-9c671f867891.png)
4. I tried to put this 
```json
"terminal.integrated.windowsEnableConpty": false,
```
in my setting json but nothing happened 

I already restart my laptop and uninstall-reinstall the current version of vscode, but still getting this exact issues

Also my computer is slowing down whenever i open Vscode and it restart by itself. I have 16 GB Ram, and on an M1 chip.

Note: if i manually used this `flutter build apk --flavor dev --release -t lib/core/main/main_dev.dart` in terminal outside the vscode, it run successfully

Please help! Thank you in advance!

**Comment by meganrogge** [comment]
Thanks for the issue. Could you please run some of the troubleshooting/info gathering actions documented here? https://github.com/Microsoft/vscode/wiki/Performance-Issues 
/label "needs more info" terminal

**Comment by meganrogge** [comment]
Also try insider's please as some people have noted that 1.66 is slower than 1.67

**Comment by linxkaa** [comment]
Hi @meganrogge thanks for responding! I already upgrade my vscode to insiders, but still occur the same issues, my laptop restarted by itself

Version: 1.67.0-insider (Universal)
Commit: e6d98a13fcd3bf928d0e755eaae873ac200a98bd
Date: 2022-04-18T05:22:43.402Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 20.3.0

and this is the performance issues that i run from vscode


Issue Type: <b>Performance Issue</b>

Tried to build an APK by using run build task, but after i run this, eventually my laptop freezed & restarted by itself

VS Code version: Code - Insiders 1.67.0-insider (Universal) (e6d98a13fcd3bf928d0e755eaae873ac200a98bd, 2022-04-18T05:22:43.402Z)
OS version: Darwin arm64 20.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|62, 15, 6|
|Memory (System)|16.00GB (2.16GB free)|
|Process Argv|--crash-reporter-id 1b7399c4-8a90-44fc-a3a4-7279871c7aca|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   13	   164	   705	code-insiders main
    7	    66	   728	   gpu-process
    0	    33	   730	   utility-network-service
   31	   377	   732	   window (register_failure.dart — ayo_aja)
   21	   180	   922	   extensionHost
    0	     0	  1120	     bash /Users/lintangkusuma/flutter/flutter/bin/flutter daemon
   30	   360	  1217	       /Users/lintangkusuma/flutter/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/lintangkusuma/flutter/flutter/packages/flutter_tools/.packages /Users/lintangkusuma/flutter/flutter/bin/cache/flutter_tools.snapshot daemon
   85	   885	  1124	     /Users/lintangkusuma/flutter/flutter/bin/cache/dart-sdk/bin/dart /Users/lintangkusuma/flutter/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp --client-id=VS-Code --client-version=3.38.2
    0	   295	  1176	     /Users/lintangkusuma/flutter/flutter/bin/cache/dart-sdk/bin/dart pub global run devtools --machine --try-ports 10 --allow-embedding
    0	   197	  1180	       electron_node config.js 
    0	     0	  1225	     (git)
   29	   213	   923	   shared-process
    0	    66	   924	     ptyHost
    1	    49	  1108	     fileWatcher
    0	     0	  1226	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   30	    82	  1213	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (register_failure.dart — ayo_aja)
|    Folder (ayo_aja): more than 20179 files
|      File types: flat(2251) xml(2118) png(1462) class(1319) json(784)
|                  len(440) txt(433) h(372) jar(370) plist(190)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: dart(4);
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
codesnap|adp|1.3.4
terminal-commands|adr|1.0.5
vscode-javascript-snippet-pack|aka|0.1.6
project-manager|ale|12.5.0
bracket-pair-colorizer|Coe|1.0.62
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-eslint|dba|2.2.2
toggle-excluded-files|eam|1.7.0
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.5.0
bloc|Fel|6.5.0
file-icons|fil|1.0.29
code-runner|for|0.11.7
dart-import|lua|0.3.1
flutter-print-tools|mar|1.0.0
theme-monokai-pro-vscode|mon|1.1.20
awesome-flutter-snippets|Nas|3.0.3
file-and-folder-icons|nex|1.0.4
material-icon-theme|PKi|4.15.0
explorer-exclude-vscode-extension|Red|1.2.0
LiveServer|rit|5.7.5
vs-code-prettier-eslint|rve|3.1.0
prettier-vscode|Sim|2.0.7
indenticator|Sir|0.7.0
bunker|sld|1.1.6
ayu|tea|1.0.5
vt100-syntax-highlighting|Tob|1.0.1
errorlens|use|3.4.2
vscode-icons|vsc|11.10.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.21

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebugcf:30466690
pynewfile477:30451556

```

</details>



is this correct?

**Comment by meganrogge** [comment]
Can you follow the steps here?

https://github.com/Microsoft/vscode/wiki/Performance-Issues#collect-information-about-the-running-vs-code

**Comment by dalisoft** [comment]
This is happening on macOS on running automated tasks and sometimes when trying to run terminal first time on window
