### ISSUE TITLE
Command 'Terminal: Create New Terminal' resulted in an error (Invalid script url: https://vscodeweb.azureedge.net/stable/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node_modules/xterm/lib/xterm.js)

### ISSUE THREAD

**Issue by joshunger** [microsoft/vscode#147639]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.22
- OS Version: Codespaces Web

Steps to Reproduce:

1. Open codespaces https://joshunger-alltrails-alltrails-xxr4gprc69vg.github.dev/ in the web browser. 
2. Open command palette.
3. Terminal: Create New Terminal.

EXPECTING: new terminal is created.

ACTUAL: modal showing Command 'Terminal: Create New Terminal' resulted in an error (Invalid script url: https://vscodeweb.azureedge.net/stable/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node_modules/xterm/lib/xterm.js).

![image](https://user-images.githubusercontent.com/2301847/163848387-26a77b5a-f8a3-4288-8789-2e3f1b41e1dc.png)

If I run across codespace issues outside of vscode, where do I log those? This is awesome just running across some flaky behavior in some cases. Thanks!

**Comment by meganrogge** [comment]
Github.dev does not yet support terminals, so i'm not sure how you're accessing that command. Could you please create a gif reproducing the issue?

**Comment by joshunger** [comment]
@meganrogge yup! codespaces opens a URL to https://joshunger-alltrails-alltrails-xxr4gprc69vg.github.dev/ It is working again maybe just a bad build? Should I close this?
