### ISSUE TITLE
When using Sort JSON, big integers lose precision

### ISSUE THREAD

**Issue by Kefan-Lin** [microsoft/vscode#147621]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.64.0 (Universal)
- OS Version: MacOS Big Sur 11.6.2 (20G314)

Steps to Reproduce:

1. Create an empty file and copy this json string into it: {"20ones": 11111111111111111111, "19ones":1111111111111111111, "18ones": 111111111111111111, "17ones":11111111111111111, "16ones":1111111111111111}

2. Right click, and then click "Sort JSON"
3. You will see the result as the following:
{
    "16ones": 1111111111111111,
    "17ones": 11111111111111112,
    "18ones": 111111111111111100,
    "19ones": 1111111111111111200,
    "20ones": 11111111111111110000
}
In this  result, you can see the precision loss.

**Comment by Kefan-Lin** [comment]
I think it's because Javascript uses 64-bit float point number to represent all numbers. If the integer is greater than 2^53, it will lose precision in Javascript.

**Comment by IllusionMH** [comment]
/causedByExtension

VS Code doesn't provide this function, you should report issue to extensions repo.
