### ISSUE TITLE
Github.dev: Theme doesn't highlight selection in diff view

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#147684]
GitHub light default:
![image](https://user-images.githubusercontent.com/2931520/163982974-b8f3d42c-4213-4672-b49e-6bdf65c0a21e.png)

GitHub light:
![image](https://user-images.githubusercontent.com/2931520/163983013-d33f1de3-de48-40f7-bc80-a4a684c5d939.png)

Light (Visual Studio):
![image](https://user-images.githubusercontent.com/2931520/163983088-28bbf60a-bf07-4b95-b613-23d76cf0419d.png)

As you can see (or not), GitHub light default uses the same color for selections and for added/changed lines.

**Comment by joaomoreno** [comment]
@hediet Should this be filled in https://github.com/primer/github-vscode-theme ?

**Comment by hediet** [comment]
But this is the official github theme on github.dev
