### ISSUE TITLE
VS Code borders still resize and move the window in fullscreen

### ISSUE THREAD

**Issue by zackste** [microsoft/vscode#147654]
Issue Type: <b>Bug</b>

When VS Code is in fullscreen on a multiple monitor setup on Windows, clicking the left or right window edge (sitting on a monitor border) moves the window to the adjacent display or resizes the window when dragged, despite being fullscreen. This can make clicking the scrollbar trickier on a high DPI display and takes over input when the user expects to change focus to another app. Since this will actually move the entire VS Code window to the display just on the other side of the border, this can be a very jarring change.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22598
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (16 x 3493)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|18.61GB (5.71GB free)|
|Process Argv|.verify\\verify.code-workspace --crash-reporter-id 172bc31b-8267-4e48-a86a-8a528e0d81b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.13.2
mermaid-markdown-syntax-highlighting|bpr|1.2.3
xml|Dot|2.5.1
gitlens|eam|12.0.6
vscode-edit-csv|jan|0.6.8
rainbow-csv|mec|2.2.0
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.5
powershell|ms-|2021.12.0
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
kuskus-kusto-syntax-highlighting|ros|1.1.20
vscode-hexdump|sle|1.8.1
code-spell-checker|str|2.1.11
vscode-scope|yiw|0.0.26

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689

```

</details>

**Comment by sbatten** [comment]
@deepak1556 known behavior of electron?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/153200
