### ISSUE TITLE
InlayHints should be removed from the editor when their text edits are applied

### ISSUE THREAD

**Issue by JoeRobich** [microsoft/vscode#147663]
While implementing TextEdit support for C# hints I noticed that the hint remains in the editor until new hints can be requested for the updated document. Since the point of the TextEdits is to remove the need for the inlay hint, it should be removed at the same time TextEdits are applied. 

Behavior of both 1.66.0 and 1.67.0-insiders:

https://user-images.githubusercontent.com/611219/164035862-34e74700-2f62-4d4c-a360-1bb2eef72296.mov

**Comment by jrieken** [comment]
The recording seems broken, please upload again, preferably directly into a comment. 

> Since the point of the TextEdits is to remove the need for the inlay hint, it should be removed at the same time TextEdits are applied.

Do you meaning typing in the sense of user gesture or automated text edits, like refactorings et al?

**Comment by JoeRobich** [comment]
> The recording seems broken, please upload again, preferably directly into a comment.

Sorry, it embedded correctly in the linked PR. I have uploaded it again into this issue.

> Do you meaning typing in the sense of user gesture or automated text edits, like refactorings et al?

I am referring to the inlay hint double click behavior which applies a set of TextEdits to the document.

According to the documentation
```
	 * *Note* that edits are expected to change the document so that the inlay
	 * hint (or its nearest variant) is now part of the document and the inlay
	 * hint itself is now obsolete.
```

**Comment by jrieken** [comment]
Understood. Thanks for clarifying.

**Comment by jrieken** [comment]
I have pushed a change to immediately request inlay hints after apply a inlay hints edits. Will be in next/tomorrows insiders

**Comment by JoeRobich** [comment]
@jrieken Performance with latest insiders build:

https://user-images.githubusercontent.com/611219/164331428-8f47621d-d3bd-4224-930c-35bd6239dfce.mov

I think it is fair to say that the O# language server could be faster at producing updated inlayHints, but I am not sure it would ever be fast enough that the users wouldn't see flashes where text is split with an inlay in the middle.
<img width="943" alt="image" src="https://user-images.githubusercontent.com/611219/164332476-fe7d7fde-0ec2-409d-90c7-6a2eede3ce82.png">

**Comment by jrieken** [comment]
> I think it is fair to say that the O# language server could be faster at producing updated inlayHints, 

@JoeRobich I believe my changes weren't in insiders yet. We had trouble producing a build yesterday, version https://github.com/microsoft/vscode/commit/bd95a8d4516d590256eefecfce465a2f10e8f5e5 or more recent should have this fix and things should be much better there

**Comment by JoeRobich** [comment]
>  I believe my changes weren't in insiders yet.

Thanks, I now see the issue tags tell a whole story.


Here I thought O# wouldn't be up to the task, but the experience should be fine for our users.

https://user-images.githubusercontent.com/611219/164499405-e2eea6fa-2560-4fde-915a-d5a4fad5d41e.mov

**Comment by jrieken** [comment]
Thanks for verifying
