### ISSUE TITLE
css incorrect "semi-colon expected css (css-semicolonexpected)"

### ISSUE THREAD

**Issue by KooiInc** [microsoft/vscode#147674]
in css one can use unicode within :after - content. In more complex string, strings have to be concatenated to make it work, like

```
content: 'Hello\0A''world'
content: attr('hello')  'world'
```

VS-code reports the first syntax as a problem:  "*semi-colon expected css*". 

This seems wrong. It is not a problem, it works in the browser. According to [MDN formal syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/content#formal_syntax) a collection of strings is one of the possibilities for `content` afaik. 

---
VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 6.2.9200
Restricted Mode: No

**Comment by aeschli** [comment]
fixed by https://github.com/microsoft/vscode-css-languageservice/commit/c378f1da7ff9539966891a186c1ac191c776560c
