### ISSUE TITLE
Unable to sign in into GitHub with VS code in Ubuntu

### ISSUE THREAD

**Issue by aniket8979** [microsoft/vscode#147691]
Issue Type: <b>Bug</b>

my vs code editor is no signing into github, previously it was signed in for some time but signed out automatically, also cant use co-pilot feature due to same. please resolve this issue.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-39-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-5005U CPU @ 2.00GHz (4 x 700)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|5.72GB (0.91GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 9ac87b84-7a49-4870-8a89-a68f0d4e15e5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|13.3.1
code-gnu-global|aus|0.2.2
apex-pmd|chu|0.5.9
bracket-pair-colorizer-2|Coe|0.2.4
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.15
vscode-eslint|dba|2.2.2
green-fish-comfort|Dip|0.0.3
githistory|don|0.6.19
javadebugger|don|0.1.5
prettier-vscode|esb|9.5.0
lana|Fin|1.4.2
code-runner|for|0.11.7
c-cpp-runner|fra|3.3.9
copilot|Git|1.12.5517
vscode-pull-request-github|Git|0.40.0
r|Iku|2.4.0
better-cpp-syntax|jef|1.15.13
intellij-idea-keybindings|k--|1.5.1
vscode-github|Kni|0.30.7
MagicPython|mag|1.1.0
git-graph|mhu|1.30.0
apex-code-coverage-visualizer|mod|0.9.6
vscode-docker|ms-|1.21.0
python|ms-|2022.5.11051003
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.7
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
emoji|Per|1.0.1
material-icon-theme|PKi|4.15.0
java|red|1.5.0
vscode-xml|red|0.20.0
vscode-yaml|red|1.6.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|54.8.0
salesforcedx-vscode-apex|sal|54.8.0
salesforcedx-vscode-apex-debugger|sal|54.8.0
salesforcedx-vscode-apex-replay-debugger|sal|54.8.0
salesforcedx-vscode-core|sal|54.8.0
salesforcedx-vscode-expanded|sal|54.8.0
salesforcedx-vscode-lightning|sal|54.8.0
salesforcedx-vscode-lwc|sal|54.8.0
salesforcedx-vscode-soql|sal|54.8.0
salesforcedx-vscode-visualforce|sal|54.8.0
pytorch-snippets|SBS|1.0.2
cmake|twx|0.0.17
c-cpp-flag-debugging|uts|0.0.1
vscode-lldb|vad|1.7.0
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
vim|vsc|1.22.2

(18 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689

```

</details>

**Comment by Abbe98** [comment]
This has started occurring for me as well, now the various sign-in triggers(co-pilot/sync, etc) open an empty browser window and then do nothing until an error notification appears(the error depends on the extension/trigger).

Example:

"GitHub Copilot could not connect to server. Extension activation failed: "Cancelled""

**Comment by aniket8979** [comment]
> 

this is exactly what happening with mine

**Comment by AlexHowansky** [comment]
I am getting this issue as well, Chrome will successfully get a token from GitHub but then fail to pass it to VSCode. The network debug tab shows a red "cancelled" status on the request for the `vscode://` redirect URL. How do I manually put the token in? There used to be a popup where you could paste it if the redirect failed, but that's gone since 1.66.0.

**Comment by TylerLeonhardt** [comment]
@AlexHowansky did you always have to use this popup workaround to get redirection working or did redirection work previously?

**Comment by sahensley** [comment]
I've also was facing the same issue.  

For my specific setup, I found the cause: having my default browser set to Flatpak Firefox instead of the default Firefox included with Kinoite. Once I changed my default back to the default Firefox install and tried a sync again, I was able to sign now.  Then I could change my default browser back to Flatpak Firefox.

The removal of the popup window to paste a token makes troubleshooting incredibly painful.

**Comment by Abbe98** [comment]
I was able to solve it by setting Chromium as my default browser temporarily while signing in.

**Comment by AlexHowansky** [comment]
@TylerLeonhardt The auto-redirect has never worked for me on Linux, I've always had to paste the token in. (Currently on Ubuntu 20.04 and Chrome 100.0.4896.127.) Granted, it was always pretty easy to do that manual paste, so I never spent much time debugging this issue.

Still fiddling with it, but it seems to be related to xdg-open, as I can't get it to work with any browser.

**Comment by AlexHowansky** [comment]
If I run `xdg-settings set default-url-scheme-handler vscode vscode.desktop` it will now at least launch VSCode when it gets that redirect URL, but it's then just opening a new editor window and not passing the token to the plugin that asked for it.

**Comment by AlexHowansky** [comment]
OK got it! I had to make two changes to my `vscode.desktop` file:

- Add `--open-url %U` to the end of the invocation command for the `Exec` line.
- Add `x-scheme-handler/vscode` to the `MimeType` line, either via the xdg-settings command or manually.

```
Exec=/path/to/vscode/bin/code --open-url %U
MimeType=x-scheme-handler/vscode;
```

**Comment by TylerLeonhardt** [comment]
What's interesting to me is have this got messed up... Installing the VS Code Snap _should_ set this already... unless you were using the standalone linux build of VS Code? The standalone doesn't have a "setup" so it can't setup this xdg default.

cc @deepak1556 please correct me if I'm wrong.

**Comment by aniket8979** [comment]
It worked, i was unable to set edge as default so had to remove firefox first. changing default browser worked. Had to Re-install Copilot extension

**Comment by AlexHowansky** [comment]
@TylerLeonhardt Correct, I'm using the tarball and had manually created the vscode.desktop file. (I'm on a rather restricted VM that I don't have a lot of control over and snaps don't work well.) I never realized that you could register browser protocol handlers in a .desktop file. In any case, the removal of the ability to manually paste the token is really what got me -- that process worked well as a work-around and I never bothered investigating why the auto-redirect didn't work.

I am back in business, thanks for the help.

**Comment by TylerLeonhardt** [comment]
FWIW, we now have some fallback logic that will take you through a flow that doesn't rely on protocol handlers. That's in VS Code Insiders today, and will be in the next VS Code stable.

In short, you cancel the existing flow and it'll say "wanna try a different flow?" And when you say "yes" you'll be taken through that. It works similar to how Microsoft auth works today, for reference.
