### ISSUE TITLE
Improve `markdown.styles` - distinguish Markdown themes and styles

### ISSUE THREAD

**Issue by SNDST00M** [microsoft/vscode#147609]
- Install two holistic Markdown themes and they will conflict aggressively with each other, confusing the user.
- It's hard to mix these themes, e.g. GfM themes, with local styles while knowing where customisations come from.
- There are still smaller extension styles for syntax highlighting or other things that could remain enabled with each other, independent of other theme-like extensions.
- There's no Settings UI or extension button to control all of this (which probably should have buttons to add/remove a style.. or filter out an extension).
  Generally speaking this editor could do with a UI for file strings or arrays in the Settings contribution.

**Comment by mjbvz** [comment]
It's all just css at the end of the day. We can't distinguish extensions that completely theme the markdown preview from one that changes a single element, and I'm not in favor of adding a new separate markdown theme contribution point unless we get more feedback on this being a real problem
