### ISSUE TITLE
typescript crash

### ISSUE THREAD

**Issue by wooltar** [microsoft/vscode#147632]
Issue Type: <b>Bug</b>

typescript crash continually

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|9, 8, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 73ad4295-2b8c-4d16-8726-dacf10058147|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
html-snippets|abu|0.2.1
vscode-caniuse|aka|0.5.4
aws-toolkit-vscode|ama|1.37.0
vscode-color|ans|0.4.5
pgformatter|bra|1.18.0
path-intellisense|chr|2.8.0
vscode-postgres|cko|1.4.0
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
angular2-snippets|dan|1.0.21
vscode-eslint|dba|2.2.2
dotup-vscode-test-generator|dot|0.0.3
tslint|eg2|1.0.47
prettier-vscode|esb|9.5.0
vscode-silq|eth|0.0.39
shell-format|fox|7.2.2
go|gol|0.32.0
terraform|has|2.21.0
composer-support-client|Hyp|0.19.12
add-new-line-to-files|jdf|0.1.1
docthis|joe|0.7.1
Angular2|joh|13.0.0
postgresql|JPT|0.0.2
solidity|Jua|0.0.139
docthis-shockoe|kyl|0.6.2
vs-color-picker|lih|1.0.0
import-sorter|mik|3.3.1
zenuml|MrC|0.5.4
vscode-docker|ms-|1.21.0
vscode-language-pack-es|MS-|1.66.3
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.1.1
mssql|ms-|1.13.0
sql-database-projects-vscode|ms-|0.14.1
cpptools|ms-|1.9.7
node-debug2|ms-|1.43.0
vscode-typescript-tslint-plugin|ms-|1.3.4
debugger-for-chrome|msj|4.13.0
open-html-in-browser|pea|2.1.9
material-icon-theme|PKi|4.15.0
platformio-ide|pla|2.4.3
tsimporter|pmn|2.0.1
vscode-css-peek|pra|4.2.0
typescript-hero|rbb|3.0.0
RustyCode|sav|0.19.1
html5-boilerplate|sid|1.1.1
autoimport|ste|1.5.4
code-spell-checker|str|2.1.11
open-in-browser|tec|2.0.0
vscode-status-bar-format-toggle|tom|3.0.0
vscode-counter|uct|3.0.4
vscodeintellicode|Vis|1.2.19
vscode-icons|vsc|11.10.0
vscode-todo-highlight|way|1.0.5
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30466690

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
