### ISSUE TITLE
Smoke Test: install and enable vscode-smoketest-check extension

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#147679]
Failed both on Windows and Linux:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=167165&view=results

**Comment by bpasero** [comment]
Isn't this marketplace being down?

**Comment by joaomoreno** [comment]
![doh](https://media.giphy.com/media/xT5LMESsx1kUe8Hiyk/giphy.gif)
