### ISSUE TITLE
Question: How to silent install with "Open with Code" enabled?

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#14767]
Hello,

I can install VSCode silently with: VSCode.exe /verysilent
How do I make it turn on the options for "Open with Code" in the context menu when I install that way?

Thanks!

**Comment by joaomoreno** [comment]
Maybe try

```
VSCodeSetup.exe /mergetasks="addcontextmenufiles,addcontextmenufolders"
```

Reference: https://github.com/Microsoft/vscode/blob/master/build/win32/code.iss#L762
