### ISSUE TITLE
Fix window in vscode

### ISSUE THREAD

**Issue by HasanKanani1** [microsoft/vscode#147620]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.I want to when I write code
Do not move from the width I set for that window and do not scroll my page
2.

**Comment by dbaeumer** [comment]
@HasanKanani1 I am not sure I understand the problem correctly. Can you please attach a screen shot showing your problem?

**Comment by HasanKanani1** [comment]
![Capture](https://user-images.githubusercontent.com/100203691/164783247-c08a2db6-0b48-4969-a975-6922f6ad9d65.PNG)

**Comment by HasanKanani1** [comment]
I want some of this page to overflow, I want the line to be cut

**Comment by alexdima** [comment]
@HasanKanani1 You can use `View > Word Wrap`.
