### ISSUE TITLE
Moving extension editor to another group makes details lost

### ISSUE THREAD

**Issue by MichaelZalla** [Microsoft/vscode#14760]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: DmitryDorofeev.empty-indent-0.1.2, MattiasPernhult.vscode-todo-0.8.0, SirTori.indenticator-0.2.1, Tyriar.lorem-ipsum, Tyriar.sort-lines-1.1.0, dbaeumer.jshint-0.10.15, dbaeumer.vscode-eslint-1.0.8, donjayamanne.python-0.4.2, eg2.tslint-0.5.39, gerane.Theme-BetterJS-0.0.3, gerane.Theme-ChromeDevTools-0.0.2, gerane.Theme-Github-0.0.2, gerane.Theme-HotDogStand-0.0.2, gerane.Theme-Hyrule-0.0.2, gerane.Theme-TomorrowNightEighties-0.0.2, jakob101.RelativePath-0.11.0, jmallien.ReplaceWithNewline-0.0.1, johnpapa.Angular2-1.0.2, jpalioto.StretchTimer, mrmlnc.vscode-apache-1.1.0, msjsdiag.debugger-for-chrome-1.2.2, nwallace.language-vscode-javascript-angular2-0.0.11, shyykoserhiy.vscode-spotify-1.0.0, stkb.rewrap-0.6.2, wmaurer.join-lines

Steps to reproduce:

1. Open Visual Studio Code.
2. `Preferences > Open User Settings` to open `Default Settings` and `settings.json` side-by-side.
3. `Extensions > Show Installed Extensions` to open the Extensions sidebar.
4. Click on an extension's title to open a description tab on the right.
5. With the `Default Settings` (left) tab in focus, hit <kbd>⌘</kbd> + <kbd>K</kbd> + <kbd>→</kbd> to swap left and right panes.

Expected result:

1. The `Extension:` tab switches sides with no change to its appearance.
2. The user may close all settings tabs and re-open them (i.e., <kbd>⌘</kbd> + <kbd>,</kbd>).

Actual result:

1. Inside the `Extension:` tab, contents of the `Details` sub-tab (to the left of the `Contributions` sub-tab) disappears. The user must click on `Contributions` and then back on `Details` to display the details again.
2. Closing all Settings windows and attempting to re-open (i.e., <kbd>⌘</kbd> + <kbd>,</kbd>) results in an error: `Unable to open 'Default Settings': Cannot read property 'length' of null.`.

**Comment by bpasero** [comment]
Error 1. I refer you to @joaomoreno why the webview does not load the details again.

Error 2. you are describing seems to be https://github.com/Microsoft/vscode/issues/13513

**Comment by bpasero** [comment]
Much easier to reproduce by just moving the group of where the extension editor is in to another group:

![editors](https://cloud.githubusercontent.com/assets/900690/19861555/487a0488-9f8d-11e6-9036-6811dcf2ff91.gif)

**Comment by joaomoreno** [comment]
@bpasero It works when moving the editor itself, instead of the whole group.

**Comment by bpasero** [comment]
@joaomoreno check what the `htmlPreviewPart` does in this case: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/html/browser/htmlPreviewPart.ts#L92

Maybe there is room for some reuse in that component so that you do not have to rebuild everything? Ideally all webview code lives in one component with all the tricks and hacks included.

**Comment by joaomoreno** [comment]
@bpasero Thanks!
