### ISSUE TITLE
Cannot copy text out of rendered markdown cell

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#147604]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have a rendered markdown cell
2. Try to use mouse to select rendered text
3. :bug: the entire markdown cell is treated as a drag target, so I have to enter edit mode every time I want to copy text out of the markdown cell. Note that I can select and copy text out of the markdown preview (and that's why I also expected to be able to select and copy text out of the rendered markdown cell). In the markdown cell case, I would expect regions that don't have text to be draggable, and regions with text to support text selection.

**Comment by roblourens** [comment]
> I would expect regions that don't have text to be draggable, and regions with text to support text selection.

I don't think that's possible :/

When we made markdown cells draggable, we decided that you will just have to put the cell in edit mode to copy it.

**Comment by joyceerhl** [comment]
😭

**Comment by kongdd** [comment]
I also need the copy and paste feature, for markdown cell.

**Comment by znorman-harris** [comment]
I'm surprised this is marked as "out of scope" and closed.

What's the difference between allowing selection of rendered markdown text and code cells? Notionally there isn't. Meaning: if you want to move a code cell, you grab the left-hand-side of the cell and move it. Yet you can still interact with the text within the code block.

I don't see why it would be a big problem to have that also be the interaction for rendered markdown cells as well because users already have to do that for code blocks.

**Comment by vimchun** [comment]
> One workaround I've found is disabling the cell drag and drop:
> 
> ```
> "notebook.dragAndDropEnabled": false
> ```

Hi @Serhiy-Shekhovtsov, what's your behavior when you select text on a rendered markdown (on a notebook) with the mouse ?
Mine after setting `"notebook.dragAndDropEnabled": false` is that I can select text with the mouse, but the text selection disappears as soon as I release the left-click mouse, so I cannot copy the text (even with CTRL+C when the text is selected).
Maybe you have a workaround to let the text selected and copy it, with extra settings, or maybe you have an extension ?
If you can share your thoughts, thanks :)

**Comment by Serhiy-Shekhovtsov** [comment]
Hey, @vimchun. I can confirm that the option `"notebook.dragAndDropEnabled": false` no longer works for me and my experience is the same as you described above.
