### ISSUE TITLE
Fat extension descriptions

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#14763]
We have an [`ExtensionDescription`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensions/common/extensions.ts#L12) which is basically a subset of an extension's `package.json`. However, when [parsing](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionPoints.ts#L87) and worst send setting up the extension host we use *everything* that's in the file. That can be a lot more data then we want and might affect start up performance because we need everything to be send over to the extension host

**Comment by DustinCampbell** [comment]
Hey guys, this breaks the latest beta of the C# extension and I'm certain it will break the shipping version of the C/C++ extension. In those extensions, we've added more information to the manifest, which we use in the extension to download platform-specific dependencies at runtime.

**Comment by DustinCampbell** [comment]
cc @eamodio

**Comment by eamodio** [comment]
Maybe extensions can have some way of expressing a whitelist of properties they do want provided?

**Comment by DustinCampbell** [comment]
Possibly, but that requires extensions to update. Personally, I'd prefer avoiding a breaking change.

**Comment by jrieken** [comment]
Oh, 💩... Didn't even think of that. @sandy081 Sorry for the mess, but I think we need to revert this...

**Comment by sandy081** [comment]
Sure.. will revert

**Comment by sandy081** [comment]
@jrieken I reverted this for now.

I see we expose the packageJSON as an API, and this will be broken if we do not send all data. 
What is the use case of exposing this? If it is just let extensions to access their package.json, Isn't it possible for them to get it by calling `require(package.json)` instead of us providing it?

**Comment by DustinCampbell** [comment]
@sandy081: That would still break shipping extensions. Are there measurements indicating that this change is worth the headache?

**Comment by sandy081** [comment]
@DustinCampbell Ofcourse removing any API will break the extensions. I am trying to understand why we had this API. 

I do not have any measurements, but reducing data to sent is always faster. I agree that this should not impact in any breakages. I will revisit this with better and non-breaking approach, if there is major performance impact.

**Comment by DustinCampbell** [comment]
Could changes be made to understand who uses this? If it's a limited number of extensions and this change results in a meaningful performance improvement, it'd be good to understand the impact.

**Comment by jrieken** [comment]
We should measure but I am not expecting this to be very expensive. My initial complained was a bit anal as before we would load and discover all extension descriptions inside the extension host. Now we do it outside and have to send that as initial payload. Let's measure first how much that costs...
