### ISSUE TITLE
VS Code intellisense is not working 

### ISSUE THREAD

**Issue by selvabalaji17** [microsoft/vscode#147614]
Issue Type: <b>Performance Issue</b>

VS Code intellisense is not working even after running refresh definitions sfdx command and even after setting java home path as well.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.68GB free)|
|Process Argv|--crash-reporter-id 54299449-814b-4759-a21f-f7f81a95dce7|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	 13908	code main
    0	   195	  3076	   window (AccountSearch.cls - lwcpractise - Visual Studio Code)
    0	    99	  3404	   shared-process
    0	    78	  1940	     ptyHost
    0	    63	  2648	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 13560	       console-window-host (Windows internal process)
    0	    81	  9912	     fileWatcher
    0	   263	  5144	   extensionHost
    0	    79	  1596	     "C:\Program Files\Java\jdk-18\bin\java" -DwatchParentProcess=false -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=c:\Users\selva\AppData\Roaming\Code\User\globalStorage\redhat.vscode-xml -Xmx64M -cp c:\Users\selva\.vscode\extensions\redhat.vscode-xml-0.20.0\server\org.eclipse.lemminx-0.20.0-uber.jar org.eclipse.lemminx.XMLServerLauncher
    0	    10	 14772	       console-window-host (Windows internal process)
    0	    78	  3620	     "C:\Users\selva\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\selva\.vscode\extensions\salesforce.salesforcedx-vscode-soql-54.8.0\node_modules\@salesforce\soql-language-server\lib\server.js --node-ipc --clientProcessId=5144
    0	    95	  9636	     "C:\Users\selva\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\selva\.vscode\extensions\salesforce.salesforcedx-vscode-lightning-54.8.0\node_modules\@salesforce\aura-language-server\lib\server.js --node-ipc --clientProcessId=5144
    0	   135	 10988	     "C:\Users\selva\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\selva\.vscode\extensions\salesforce.salesforcedx-vscode-lwc-54.8.0\node_modules\@salesforce\lwc-language-server\lib\server.js --node-ipc --clientProcessId=5144
    0	    96	 14868	     "C:\Users\selva\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\selva\.vscode\extensions\salesforce.salesforcedx-vscode-visualforce-54.8.0\node_modules\@salesforce\salesforcedx-visualforce-language-server\out\src\visualforceServer.js --node-ipc --clientProcessId=5144
    0	    27	  8976	   crashpad-handler
    1	   203	 10044	   gpu-process
    1	    90	 12968	   issue-reporter
    0	    40	 16328	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AccountSearch.cls - lwcpractise - Visual Studio Code)
|    Folder (lwcpractise): 1995 files
|      File types: json(646) ts(640) cls(638) xml(9) js(5) html(4)
|                  eslintignore(1) forceignore(1) gitignore(1)
|                  prettierignore(1)
|      Conf files: launch.json(1) settings.json(1) jsconfig.json(1)
|                  package.json(1)
|      Launch Configs: apex-replay;
```

</details>
<details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
apex-autocomplete|chu|0.2.13
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.5.0
lana|Fin|1.4.2
vscode-pull-request-github|Git|0.40.0
live-server|ms-|0.2.12
indent-rainbow|ode|8.3.1
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
LiveServer|rit|5.7.5
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|54.8.0
salesforcedx-vscode-apex|sal|54.8.0
salesforcedx-vscode-apex-debugger|sal|54.8.0
salesforcedx-vscode-apex-replay-debugger|sal|54.8.0
salesforcedx-vscode-core|sal|54.8.0
salesforcedx-vscode-lightning|sal|54.8.0
salesforcedx-vscode-lwc|sal|54.8.0
salesforcedx-vscode-soql|sal|54.8.0
salesforcedx-vscode-visualforce|sal|54.8.0
indenticator|Sir|0.7.0
sfdx-package-xml-generator|Vig|2.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30466689

```

</details>

**Comment by selvabalaji17** [comment]
![image](https://user-images.githubusercontent.com/83115450/163750379-b8f929ad-e220-4ad2-843c-505eec4d20b3.png)

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please raise this with the provider of the Salesforce extension.
