### ISSUE TITLE
Terminal word selection range not correct

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#147619]
On following video, you can see iterm2 select the number range is correct, but in vscode terminal is not right.

- MacOS: 12.3.1
- VSCode: 1.67.0-insider

Steps to Reproduce:

1. copy words `获取模板 25235168 的预览图失败`
2. double click on the number

https://user-images.githubusercontent.com/41773861/163772454-fff35b32-dc14-449f-bb2c-3d4037f71f32.mov

**Comment by meganrogge** [comment]
doesn't reproduce here https://xtermjs.org/

**Comment by tjx666** [comment]
After I reset all the settings and reload with disable extensions, I can still repro this issue in zsh and bash:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/163844646-64eddeed-6315-48b6-9202-04e4ea1bd87f.png">

**Comment by meganrogge** [comment]
Yes I can reproduce the issue.

**Comment by Tyriar** [comment]
Tracked in https://github.com/xtermjs/xterm.js/issues/4307

**Comment by Tyriar** [comment]
This is not an upstream problem but an issue with the word link provider
