### ISSUE TITLE
Cmd+D has no "select all occurrences" counterpart

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14765]
Cmd+D currently seems to require that you hit it as many times as there are occurrences, in order to match all occurrences of the selection. Atom has shift+cmd+D, which instantly (as far as anything in Atom is instant) selects all occurrences. This is extremely useful.

(It's unfortunate that VSCode has already used shift+cmd+D for "go to debugger pane". It's not a great idea to abuse shift like this when there's already a corresponding shift-less shortcut — shift's behaviour is usually to modify another shortcut. Wouldn't the function keys F1, F2 etc. be better for switching between the "big task" panes?)

**Comment by kaiwood** [comment]
The feature is there, full name of the command is `Select All Occurrences of Find Match`, default shortcut is `cmd-shift-l`.

**Comment by atombender** [comment]
Ah. I couldn't find it because the command name is `editor.action.selectHighlights`, which doesn't mean anything to me (what is a "highlight"?). The cmd+D action is `editor.action.addSelectionToNextFindMatch`. I propose that the command is renamed to something like `selectAllFindMatches` or something like that, to make it clear what it does.

**Comment by rebornix** [comment]
Thanks @kaiwood for the clarification :) Close it first as it's covered by existing commands right now.

**Comment by kaiwood** [comment]
It's a little easier to discover it via the command palette (cmd-shift-p).

Technically speaking `editor.action.selectHighlights` does exactly what it says. If you simply position the cursor over a "word", all other occurrences of that word are highlighted. `cmd-shift-l` works right away and selects the highlights.

But you are right, it's a little confusing to have multiple wordings for the command.

**Comment by atombender** [comment]
But it's inconsistent: Its counterpart is `editor.action.addSelectionToNextFindMatch`, not `editor.action.selectNextHighlight` or whatever. It's not clear that they are related. I don't even know what "next find match" means here; if `selectHighlights` selects _all_ highlights, then cmd-D finds the _next_ highlight. But how does "find" fit into it?

**Comment by kaiwood** [comment]
Without the selection part, there is the (OS) standard combination of `cmd+f` for find and `cmd-g` for "Find Next" which works in every macOS application. In VSCode this command is called `editor.action.nextMatchFindAction`. If you think about it from that angle, what `cmd-d` does is the standard "Find next" plus the additional selection on it.

**Comment by atombender** [comment]
But "Find" doesn't automatically pick up the current highlighted word. "Find" requires the user to type something to find. So it's definitely inconsistent and weird.

**Comment by kaiwood** [comment]
Yes it does, the input field that opens on `cmd+f` is always prefilled with the current selection – and if nothing is selected, it uses the highlighted word under the cursor. Try it :)

**Comment by atombender** [comment]
Hm, I see. But you still have to open the find box, which cmd-D doesn't. It's not like cmd-G picks up current word to do its search, and it's not like you can add to the selection through cmd-F/cmd-G. 

The name is also nonsensical purely semantically: It does "add the selection _to the next find match_". It _adds to the selection_, ie. it adds another selection, _from_ the next find match. It's reversed.

Back to basics: Cmd-D takes the _current word_ (or selection if there is one), finds the next _occurrence_ of this, and _selects it_. Since this system of "other words in the same file which are the same as this one" is apparently know as highlighting (which is also a bit misleading as a term), the logical choice would be `addNextHighlightOccurrenceToSelection`. It's long because it's exact.

It would be better if these actions were hierarchical: `editor.action.highlight.addNextOccurrenceToSelection`, and then `editor.action.highlight.selectAll` for the shift-cmd-L version. You have it for markers (`marker.next`, `marker.prev`), so obviously the capability is there.

Actually, I discovered that there is another command which seems to do the same thing:
`editor.action.changeAll` ("Select all occurrences of current word", according to [this page](https://code.visualstudio.com/docs/customization/keybindings)). I don't see any difference in behaviour between the two commands.

**Comment by kaiwood** [comment]
That wording makes sense, yes. +1 on this.

Good spot on `editor.action.changeAll`, I tried it and it looks like it really is a duplication. Strange. Maybe @alexandrudima can clarify this?
