### ISSUE TITLE
MicroPython

### ISSUE THREAD

**Issue by ansh-mitt** [microsoft/vscode#147698]
It would be so much easier for me to select MicroPython as a language right from languages than to download extensions or adapt code.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide more detailed description of request and expected action items.

**Comment by lramos15** [comment]
VS Code thrives on the extension model. We don't want to bloat the core editor with too many built in features that people won't use. Instead installing a set of extensions allows you select exactly what you want from VS Code. This can then be synced to all your machines via setting sync so you only have to setup one machine and after that everything is set and ready to go for you.
