### ISSUE TITLE
Extra quotes inserted when typed during cmd-D selection

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14766]
- VSCode Version: 1.6.1
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Create a file with a _non-plaintext_ syntax, such as Python.
2. Populate the file with: `'a', 'b', 'c'`
3. Select a single quote and hit cmd-D 5 times (to select all).
4. Hit backspace to delete quote.
5. Type a single quote (or a double quote; same bug).
6. Result will be: `'a', 'b', 'c''` (note last extract quote)

Also note that if you select across multiple lines, the extra quote is inserted on each line:

```
'a', 'b', 'c''
'a', 'b', 'c''
```

**Comment by kaiwood** [comment]
For some additional context: Tried to reproduce this, it doesn't happen when language mode is set to plain text, but I can confirm that it happens at least in JavaScript, Ruby and C-Mode.

**Comment by atombender** [comment]
Yes, it only works in languages that have automatic quote insertion.

**Comment by alexandrudima** [comment]
This has been fixed in the meantime. All cursors will now do the same thing when typing.
