### ISSUE TITLE
Integrate file CRUD with vscode.QuickOpen

### ISSUE THREAD

**Issue by suryanshmak** [microsoft/vscode#147689]
Hey there, 
I recently created a vsc extension which commands better file CRUD. You can check it out [here](https://marketplace.visualstudio.com/items?itemName=suryanshmak.advanced-file). 

**Why integrate it?**
I've seen many people like it though they were opinionated about using my plugin because it didn't have the feature to open recently visited files and also I wasn't able to get custom file icons for each files/dir.
I think integrating this feature with the `vscode.quickOpen` would be really cool and useful.

Also, there are many extensions out there which help doing this and it would be really helpful if it was an integrated vscode feature.

**Comment by tanhakabir** [comment]
Thank you for your suggestion! Based on a quick look at your extension I believe that most of these features are easy enough to do in vscode already and the fact that an extension exists proves that it works fine as a separate extension.

If you would like some of the specific features built in, you can make a specific feature request for those features.
