### ISSUE TITLE
ARM builds not available on snap store

### ISSUE THREAD

**Issue by globalhuman** [microsoft/vscode#147656]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: latest
- OS Version: ubuntu 20.04

Steps to Reproduce:

web:

1. Go to https://snapcraft.io/code
2. Select version dropdown
3. Select "Show Architecture"

![image](https://user-images.githubusercontent.com/38127975/163899302-6e5acac3-d797-414a-b84a-36c354177041.png)

terminal:

1. `sudo snap install code --classic`

```shell
error: snap "code" is not available on stable for this architecture (arm64) but exists on other
       architectures (amd64)
```

Only amd64 is available according to the snapcraft store even though it is indicated in the PR https://github.com/microsoft/vscode/pull/111008 that ARM snap builds should be available.

**Comment by joaomoreno** [comment]
We are still blocked here, since we don't run builds on ARM hardware: https://github.com/microsoft/vscode/issues/106473#issuecomment-732237745

We can only do this once we run on ARM build machines.
