### ISSUE TITLE
Add notebook.background color customization

### ISSUE THREAD

**Issue by tweakimp** [microsoft/vscode#147693]
Right now, the notebook background color is determined by `editor.background`.

The problem with this is that `editor.background` determines the color of an area in which you can input text, while in notebooks it determines the color of the background, but you put the text in cells which have their own background color (`notebook.cellEditorBackground`).
If you then want to have the same color for the normal editor area and the notebook cells, then the cells and the area around them are in the same color.

I would like to have a setting like `notebook.background` with which the notebook background color can be set independently from cell background and normal editor background.

**Comment by gjsjohnmurray** [comment]
Is https://github.com/microsoft/vscode/issues/125549#issuecomment-857874093 any help?

**Comment by tweakimp** [comment]
> Is [#125549 (comment)](https://github.com/microsoft/vscode/issues/125549#issuecomment-857874093) any help?

Not for this issue, because with `notebook.outputContainerBackgroundColor` I can not color the notebook background, only the output container background which is on top of the notebook background.

**Comment by rebornix** [comment]
Good suggestion, thank you!

**Comment by tweakimp** [comment]
@rebornix Sorry to summon you again, but can you tell me how can I get people to upvote this issue to get the needed upvotes?

**Comment by roblourens** [comment]
We are actually working on this for June. In general for other "Backlog Candidate" issues, you can ask your friends :)
