### ISSUE TITLE
History: delete entries that are deleted or moved on disk

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14761]
A regression from some work in October, this used to work.

**Comment by bpasero** [comment]
To verify, make sure that a file that you delete is removed from the recently opened in Cmd+P

**Comment by chrmarti** [comment]
Deleted a file in the VSCode Explorer on OSX and it was not removed from the recently opened files.

- VSCode Version: Code - Insiders 1.8.0-insider (e0871329738682651367be4e8a618912ad693e03, 2016-12-08T07:05:13.731Z)
- OS Version: Darwin x64 15.6.0

![screen shot 2016-12-08 at 10 13 32 am](https://cloud.githubusercontent.com/assets/9205389/21021813/037d77b0-bd2f-11e6-8117-03f20a9e1f04.png)

**Comment by bpasero** [comment]
@chrmarti due to a bug in hot exit, you opened the workspace folder with lowercases and this means our file watcher does not work correctly. Please run from the command line using the correct casing of the folder and try again. Then it will work.

**Comment by roblourens** [comment]
This now works as described if I delete the file while vscode is open. But if I close vscode, delete the file, then reopen vscode, it's still in the quick open list. Is that a different issue?

**Comment by Tyriar** [comment]
@roblourens both cases seem to work fine for me on Ubuntu.

**Comment by roblourens** [comment]
There's one edge case where it doesn't work. I'm calling this verified and opening a new issue.
