### ISSUE TITLE
Cursor Jumping out of cell in Jupyter on autosave

### ISSUE THREAD

**Issue by MLDERES** [microsoft/vscode#147649]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows [Version 10.0.17763.2686] (Remote Container version: Debian GNU/Linux 11 (bullseye))

I've searched for other similar issues and it always points back to an extension.  But in this case, I have 0 extensions enabled in the container and only the Remote - Containers extension installed on the localhost.

Steps to Reproduce:

1. Open folder from container.
2. Create a Jupyter notebook file (.ipynb)
3. Type a few lines of text
4. Either explicitly save or let autosave run to save the file.
5. Cursor moves out of the cell.
![autosave-vscodebug](https://user-images.githubusercontent.com/17891342/163878020-7183e181-a46e-4641-8bfe-50ffff4cf081.gif)

**Comment by rebornix** [comment]
@MLDERES are you also seeing this on local vscode instance or you are seeing it on local and remote? It would be helpful if we can know if it's specific to remote.
