### ISSUE TITLE
"Peek problem" shows diagnostic after it is resolved (can be confusing)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#147683]
When you have the Peek Problem window open and resolve the problem, the Peek window remains with the last version of the diagnostic that was at that range. It is greyed out and italic, but it's not completely clear that this means "this diagnostic has been fixed" and if the message contains parts of the source, it's no longer up-to-date (for example here the message contains `dynamicbar` which no longer exists in the source after I added a space):

![Apr-19-2022 10-57-54](https://user-images.githubusercontent.com/1078012/163979431-5c602523-65c5-4084-b9e5-7b040aa3e643.gif)

I think it could be made clearer, for ex:

- Remove the diagnostic text entirely and just show something like "this problem was resolved"
- Strike the problem text out
- Append something like "this problem was resolved" to the top/bottom of the peek text

**Comment by jrieken** [comment]
This is on purpose because the code would move/wiggle otherwise. The error is rendered greyed out to make it clear that the error is stale

**Comment by DanTup** [comment]
I understand that it's intended, but I think perhaps it could be clearer (https://github.com/Dart-Code/Dart-Code/issues/3928 was raised because it seemed like a bug in the extension, but we have no control over this).

The diagnostics are already updating during typing, so minor changes to the text don't seem like they would cause any additional wiggling. Some suggestions in the original comment above were:

- Remove the diagnostic text entirely and just show something like "this problem was resolved"
- Strike the problem text out
- Append something like "this problem was resolved" to the top/bottom of the peek text

Would any of these be reasonable?
