### ISSUE TITLE
Unbound breakpoint in a webpack bundled module

### ISSUE THREAD

**Issue by dimmil123** [microsoft/vscode#147662]
- VS Code Version: 1.65.2
- OS Version: Ubuntu 20.04.4 LTS

I am working on a JavaScript app and bundling my modules with Webpack. When I put a breakpoint in one of my modules, it turns into an unbound breakpoint when I start the debugger.

My launch.json:
```
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "pwa-chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:5500/dist",
      "webRoot": "${workspaceFolder}/src",
      "sourceMapPathOverrides": {
        "webpack://battleship/./*": "${workspaceFolder}/*"
      },
      "trace": true
    }
  ]
}
```

My trace logs are attached.
[vscode-debugadapter-7570a5d5.json.gz](https://github.com/microsoft/vscode/files/8509464/vscode-debugadapter-7570a5d5.json.gz)

**Comment by connor4312** [comment]
It looks like you want `"webpack://battleship/*": "${workspaceFolder}/*"` instead of `"webpack://battleship/./*": "${workspaceFolder}/*"` in your sourceMapPathOverrides.

**Comment by dimmil123** [comment]
I am still getting the unbound breakpoint: 
![Screenshot_2022-04-19_17-44-35](https://user-images.githubusercontent.com/103977832/164107161-8bab54dc-214a-48e3-ae94-42c07fcaa902.png)

New trace:
[vscode-debugadapter-64301321.json.gz](https://github.com/microsoft/vscode/files/8516659/vscode-debugadapter-64301321.json.gz)

**Comment by connor4312** [comment]
Ah, I see, for some reason webpack is adding a `?` onto the end of your file URLs. While `?` is allowed in file paths on Linux and OSX, we could try to normalize that. Interestingly invoking webpack in a path with `?` in it fails, but esbuild works.

**Comment by dimmil123** [comment]
Sorry, how should go about fixing that? My webpack.config.js does not have a question mark in it.

**Comment by connor4312** [comment]
This'll be fixed in the upcoming [nightly build](https://github.com/microsoft/vscode-js-debug#nightly-extension). Please give it a shot!
