### ISSUE TITLE
Setting to exclude file patterns from editor.formatOnSave

### ISSUE THREAD

**Issue by PAI5REECHO** [microsoft/vscode#147677]
Something like `editor.formatExclusions` so I can ignore certain files, directories and glob patterns from `editor.formatOnSave`

**Comment by jrieken** [comment]
You can already do that via language specific settings, e.g 

```json
"[html]": {
"editor.formatOnSave": false
},
```

Is that what you are looking for?

**Comment by jrieken** [comment]
What level on granularity are you looking for? Is this just for format on save or also other settings, like the default formatter or indentation settings etc?

**Comment by PAI5REECHO** [comment]
Just format on save. `workbench.action.files.saveWithoutFormatting` is easy to forget, all it takes is one save and you lost all your manual formatting. My language auto code formatter doesn't have a way to guard sections of a file from auto formatting so it'd be nice to be able to not run the formatter at all on certain files in my project.

If I could have something like:
```
"[nix]": {
  "editor.formatExclusions": [
    "**/list.nix`
  ],
},
```
for example that would never format files named `list.nix` on save.
