### ISSUE TITLE
Unable to resolve your shell environment: Unexpected number in JSON at position 35

### ISSUE THREAD

**Issue by almaceleste** [microsoft/vscode#147630]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Ubuntu Studio Xfce4 Linux x64 5.13.0-19-lowlatensy

Steps to Reproduce:

1. Add to ~/.bashrc next line:
`trap 'printf "\033]0;%s\007" "${BASH_COMMAND//[^[:print:]]/}"' DEBUG`
3. Launch VS Code from the Applications Menu or double click the associated file
4. Get error message:
> Unable to resolve your shell environment: Unexpected number in JSON at position 35

![image](https://user-images.githubusercontent.com/36765595/163817625-95d890c5-761a-4c45-a1e5-9ba550118729.png)

**Upd:** If I comment this line VS Code runs without error.

**Comment by IllusionMH** [comment]
Do you see any errors in you ~settings.json` for User and Workspace?

**Comment by almaceleste** [comment]
@IllusionMH, no, I don't see any error in my `settings.json`.

**Comment by meganrogge** [comment]
What are you trying to do with that line?

**Comment by almaceleste** [comment]
@meganrogge, this line changes the title of my terminal window to the currently running command, so that I can see in the taskbar which command currently running in each terminal window.  
but it shouldn't matter to `vscode`. and a few versions ago it was. I have been using this line since very beginning of using Linux. and `vscode` didn't throw this error until recently.

**Comment by meganrogge** [comment]
I added that line to my `.bashrc` and I don't have a problem

when VS Code launches, we source a "dev environment" by running your default shell. When this fails we show the error message that your shell returned. You have some issue in your shell init files that's causing that error, you need to investigate on your end as it's a problem with your environment, not with VS Code.

See here for what we do before showing this error:

https://github.com/microsoft/vscode/blob/87b365f433427f0b936b02382b177abebc7c6369/src/vs/platform/environment/node/shellEnv.ts#L126-L151

**Comment by TheRealAgentK** [comment]
I'd disagree with this being an environment problem and I'm not sure if should be closed.

>Unable to resolve your shell environment: Unexpected number in JSON at position 35

I'm seeing the exact same problem as the OP in 1.68.0 (can't say when it started, skipped a few versions) and it's triggering over a custom git prompt in bash on Ubuntu that I've been using fine in all sorts of environments since forever.

Happy to provide more info to debug this if that helps and if you'd provide some guidance what to do.

Also: if there is an issue in a user's shell configuration, wouldn't it be useful to make the error message a bit more user friendly? As a suggestion, it'd be good if it explained that and maybe render the actual command VS Code tried to run and that failed? Or some more information in VS Code logs?

**Comment by Tyriar** [comment]
This is a better repro for me from https://github.com/microsoft/vscode/issues/163768

```
trap 'echo -ne "\033]0;$BASH_COMMAND\007"' DEBUG
```

**Comment by Tyriar** [comment]
The exception happens here:

'" + JSON.stringify(process.env) + "b5ef8d0b8229"'b5ef8d0b8229{"key":"value",...}'

This is what rawStripped is:

```
'" + JSON.stringify(process.env) + "b5ef8d0b8229"'b5ef8d0b8229{"key":"value",...}'
```
<img width="622" alt="Screenshot 2022-12-02 at 10 19 27 am" src="https://user-images.githubusercontent.com/2193314/205359716-39c96f23-e68f-4639-9d1d-af4c304db1e9.png">

Here's what it is when it works:

```
'{"key":"value",...}'
```

**Comment by Tyriar** [comment]
And the raw when it doesn't work:

<img width="1141" alt="Screenshot 2022-12-02 at 10 23 34 am" src="https://user-images.githubusercontent.com/2193314/205360462-14069294-9ba4-490a-9c39-c7b7ddf163ac.png">

The 2 marks are in the sequence, we should be matching on the last 2 marks, not the first 2.
