### ISSUE TITLE
Searching in terminal with large scrollback is slow on macOS

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vscode#147685]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0-insiders
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Change the terminal scrollback to 30'000
2. execute `for i in {0..20000}; do echo "absdj bkwefkl wqdoqwdjadcnbyx ncbahjsgf7zr92834rjpowef0sdjfisdnjfbsjdf"; done`
3. Search for `abs`

With version 1.65.0 this was not a problem, but there was no highlighting. It would be enough if I can disable the highlighting or disable the highlighting automatically if the history is longer than x lines.

https://user-images.githubusercontent.com/41973254/163984460-fb641131-3565-415a-a8c2-ceb6e2d4a1ac.mp4

**Comment by ChaseKnowlden** [comment]
Is it Upstream or VSCode Core.

**Comment by MrAndersen1** [comment]
Happens for me too, when you search then type abs quickly and it takes ~5-10 seconds for the letters to appear, same goes with erasing letters.

**Comment by sandy081** [comment]
Search is fast now but matches info is not being shown - https://github.com/microsoft/vscode/issues/148335
