### ISSUE TITLE
Cancelled Github Authentication

### ISSUE THREAD

**Issue by aazsamir** [microsoft/vscode#147601]
- VS Code Version: 1.66.2
- OS Version: Linux x64 5.17.1-3 MANJARO snap

Steps to Reproduce:

1. When I'm trying to connect with my github account (sync settings, or for extensions), my output on GitHub Authentication tab is

> [Info  - 17:13:04.178] Reading sessions from keychain...
> [Info  - 17:13:04.204] Getting sessions for user:email...
> [Info  - 17:13:04.220] Getting sessions for all scopes...
> [Info  - 17:13:04.665] Getting sessions for read:user,repo,user:email...
> [Error  - 17:13:04.667] Getting token failed: Error: Input is not valid base64-encoded data.
> [Info  - 17:13:04.667] Got 0 sessions for user:email...
> [Info  - 17:13:04.667] Got 0 sessions for ...
> [Info  - 17:13:04.667] Got 0 sessions for read:user,repo,user:email...
> [Info  - 17:13:05.752] Getting sessions for all scopes...
> [Info  - 17:13:05.753] Got 0 sessions for ...
> [Info  - 17:13:05.803] Getting sessions for read:user...
> [Info  - 17:13:05.803] Got 0 sessions for read:user...
> [Info  - 17:13:06.91] Getting sessions for read:user,repo,user:email...
> [Info  - 17:13:06.91] Got 0 sessions for read:user,repo,user:email...
> [Info  - 17:13:06.238] Getting sessions for read:user,repo,user:email...
> [Info  - 17:13:06.238] Got 0 sessions for read:user,repo,user:email...

2. I had VSCode version 1.66.0 on my laptop, and github authentication was working fine (same OS). After update to 1.66.2 there is same problem. On my main machine I reverted snap package to 1.66.1, and still not working, so I assume that problem have started with 1.66.1 update.

3. Have tried Insiders version, but without success. I Also have windows 10 on dualboot, and it's working fine there.

**Comment by TylerLeonhardt** [comment]
I actually included some fixes in this area very recently. They're currently only available in the Insider build of VS Code right now which you can get here: https://code.visualstudio.com/insiders

This is also available as a snap here: https://snapcraft.io/code-insiders

In short, if we detect that you are having trouble logging in, we show you a notification to try a different way to log in... and if that doesn't work we try yet another way.

**Comment by aazsamir** [comment]
I have updated vscode to 1.67.0-insider, github authentication is working fine now at second attempt, but it's kinda slow, and having option to not to ask, but always try second method (or force it as first) would be nice. 
Solved, thanks.

**Comment by deepak1556** [comment]
Related to https://github.com/microsoft/vscode/issues/147515

**Comment by Aire-One** [comment]
Hello, 

I also experiment a similar issue with VSCode on Arch Linux. The funny thing is that on my computer, the GitHub authentication from Firefox opened a new tab on VSCode with the activation link URL.

Here is my VSCode version:
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.0-arch1-1
```

As hinted by @TylerLeonhardt, I tried with VSCode-insider, and it successfully worked!
Thanks for pointing out this working method to activate Copilot on my computer.
Do you happen to know how long until the fix land in the regular version of VSCode, @TylerLeonhardt?

Just in case, here is my VSCode-insider version:
```
Version: 1.67.0-insider
Commit: ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af
Date: 2022-04-26T05:16:02.333Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.0-arch1-1
```

**Comment by TylerLeonhardt** [comment]
> Do you happen to know how long until the fix land in the regular version of VSCode, @TylerLeonhardt?

Next week. Wednesday or Thursday most likely.
