### ISSUE TITLE
highlighting lines with mouse cursor jumps on linux ARM64

### ISSUE THREAD

**Issue by globalhuman** [microsoft/vscode#147658]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: 
  - linux
    - `uname -a`
    - `Linux ubuntu-linux-20-04-desktop 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:21:14 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`
  - mac
    - macOS Monterey 12.3.1

Steps to Reproduce:

1. Highlight lines of text and move cursor outside of the immediate text editor. i.e. hover over the line numbers as you move up/down to highlight more text

Expected behavior:

- Lines are still highlighted if mouse cursor is outside of the main editor screen as per behavior on other platforms and OS's

Current behavior:

- When highlighting text the lines are not highlighted when the cursor is outside of the text editor. When the cursor re-enters the text editor the lines are highlighted again. See attached screen grabs of macOS vs Linux

- linux arm64 (parallels)
  - ran with `code-insiders --disable-extensions`
  - https://user-images.githubusercontent.com/38127975/163900607-d105a561-75cd-4074-8ff6-92405fc79bd8.mov

- mac arm64 M1
  - https://user-images.githubusercontent.com/38127975/163900635-890375e7-2219-4e10-955f-a2f655afde1e.mov

**Comment by alexdima** [comment]
Let's track in #146947
