### ISSUE TITLE
Notebook created in VSCode Tries to Save as JSON

### ISSUE THREAD

**Issue by user-github2018** [microsoft/vscode#147657]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I created a notebook through the tool palette and when I tried to save it, it fails because it tries to save as json.

### VS Code Version

Version: 1.66.0 (user setup) Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5 Date: 2022-03-30T05:50:14.623Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Windows_NT x64 10.0.19042

### Jupyter Extension Version

 v2022.3.1000901801

### Coding Language and Runtime Version

base (Python 3.8.3)

### Running Jupyter locally or remotely?

Local

**Comment by amunger** [comment]
Does setting the dropdown to "no extension" and keeping the *.ipynb in the filename help?

**Comment by user-github2018** [comment]
It works for me if I: 1) erase the .json at end of file name in save box 2) save as no extension

**Comment by amunger** [comment]
Glad to hear that works as a workaround. We're still trying to figure out the issue on our end since it doesn't seem to behave the same way for us when trying to repro.

**Comment by roblourens** [comment]
Here we find ipynb in the unsliced list of extensions, then return the sliced list that doesn't include ipynb. The order of this list seems random.

https://github.com/microsoft/vscode/blob/ca936dcc94fba1f8d6c6de2b5984827571e24eaa/src/vs/workbench/services/dialogs/browser/abstractFileDialogService.ts#L326

I am guessing that 10 is an arbitrary number that looks good to display? We went to 20 https://github.com/microsoft/vscode/commit/d1d39f1e60e88b070dade09a4f77e94a11e07e2e then reverted that https://github.com/microsoft/vscode/commit/9d53a7290e0850677bdc3b1c47a031bf54c9c34b. Or maybe having more than 10 causes some obscure issue on windows.

I think we should add the matched extension to the sliced list, if it got cut out. I'll do that if nobody knows any reason not to.
