### ISSUE TITLE
not able to Authorize

### ISSUE THREAD

**Issue by Aanchal20081** [microsoft/vscode#147765]
Issue Type: <b>Feature Request</b>

I am not getting authorize an org after creating project 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Sounds like you're using the Salesforce extension.

/causedByExtension
