### ISSUE TITLE
Regression of #127762: terminal link detector fails to recognize standard path:line:column:match output

### ISSUE THREAD

**Issue by ssbarnea** [microsoft/vscode#147769]
Regression of #127762 which was closed and locked, even if I doubt it was ever resolved.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: MacOS 12.3.1

Steps to Reproduce:

1. Open terminal and do "echo 'filename.txt:1:2:foo'
2. Ctrl click to link detector and click it
3. vscode will prompt to open `filename.txt:1:2:foo` instead of `filename.txt` at line 1 and column 2

![ss](https://sbarnea.com/ss/Screen-Shot-2022-04-20-15-11-32.79.png)

As seen in the screenshot, I disable all extensions. You can also see various variations of expected terminal output, for all of them the regular expression used for matching is matching too much.

```
some.txt:213:12: alpha (space after the 3rd colon)
some.txt:260:11:# beta (no space), it wrongly includes the hash
some.txt:76:7:gamma=(...) wrongly selects until the oparenthesisanteses
```

Expected behavior:

* recognize the `:line:column` notation and ignore anything after the column (which is numeric).
* not to prompt user to create an invalid filename such "foo.txt:1:2"

**Comment by ssbarnea** [comment]
I did some more extensive investigation with @cirdblock in order to narrow down what happens and apparently if filenames start with `./` it does behave correctly. The only case where it misbehaves is when the filename does not have a path component in it.

* `file.txt` will not work well (reproduces)
* `./file.txt` will work as expected
* `../file.txt` will work fine
* `/home/user/file.txt` will work fine
* `src/file.tx` will work fine

The only case it fails where there is not any path separator inside the filename. The bad part is that not all the tools are adding the `./` prefix to filenames.

**Comment by ssbarnea** [comment]
I do also have another bug related to it, slightly different:
```shell
FAILED test/test_utils.py::test_cli_auto_detect 
# ^ pytest default output format
```

Using cmd+click over the filename above does highlight the entire line and clicking on it confuses vscode as it prompts about "test/test_utils.py::test_cli_auto_detect" with **No matching found**. Use of colon (`:`) should never be accepted as valid filename and code should be smart enough to at least ignore after it.

When clicking over a simple filename that is not followed by a colon, it seems to properly be able to lookup the filename and provide a dropdown. Even in this case is not perfect as it does not directly open the file when there is a perfect match, see below:

![ss](https://sbarnea.com/ss/Screen-Shot-2022-04-21-10-43-10.06.png)

**Comment by Tyriar** [comment]
Looks like this works now:



![Image](https://user-images.githubusercontent.com/2193314/205735843-b2704aba-ab7f-4ea4-83eb-77114f6e83ba.png)
