### ISSUE TITLE
Excessive CPU usage in version 1.66.2

### ISSUE THREAD

**Issue by tyxou2** [microsoft/vscode#147776]
Issue Type: <b>Performance Issue</b>

Update to version 1.66.2 spiked CPU usage to over 100% even while idle.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           X5650  @ 2.67GHz (24 x 2660)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|48.00GB (30.36GB free)|
|Process Argv|--crash-reporter-id 0e1771d0-f68e-4212-8f91-1905d1b7e4c0|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	   147	  8892	code main
    0	    49	  8896	   gpu-process
    0	    49	  8898	   utility-network-service
    0	   442	  8899	   window (Home.tsx — app)
   57	   688	  8903	   extensionHost
    0	   147	  8912	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/bx/zpwh9l4x68qgcwyj4gcbr0cw0000gp/T/vscode-typescript502/778fa977e557a8065b14/tscancellation-b8d45a9f59c7c8481315.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   246	  8913	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/bx/zpwh9l4x68qgcwyj4gcbr0cw0000gp/T/vscode-typescript502/778fa977e557a8065b14/tscancellation-9ba613fae022bcaac2b6.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    98	  8917	       /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/MAC/Library/Caches/typescript/4.6 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    49	  8915	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/MAC/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10/packages/server/dist/serverMain.js --node-ipc --clientProcessId=8903
    0	    98	  8916	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/MAC/.vscode/extensions/mtxr.sqltools-0.23.0/dist/languageserver.js --node-ipc --clientProcessId=8903
    0	    98	  8936	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=8903
    0	    98	  8937	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/MAC/.vscode/extensions/mongodb.mongodb-vscode-0.9.2/dist/languageServer.js --node-ipc --clientProcessId=8903
    0	    49	  8941	     /Applications/Visual Studio Code.app/Contents/MacOS/Electron --ms-enable-electron-run-as-node /Users/MAC/.vscode/extensions/dbaeumer.vscode-eslint-2.2.2/server/out/eslintServer.js --node-ipc --clientProcessId=8903
    0	   197	  8904	   shared-process
    0	    49	  8905	     ptyHost
    0	    49	  8910	     fileWatcher
    0	     0	  8987	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    98	  8979	   issue-reporter
```

</details>
<details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
html-symbols|Die|0.0.2
output-colorizer|IBM|0.1.2
html-snippets|abu|0.2.1
vscode-m3u|af4|1.0.0
project-manager|ale|12.5.0
rtf|ale|2.5.0
vscode-sqlite|ale|0.14.0
laravel-extra-intellisense|ami|0.6.2
code-gnu-global|aus|0.2.2
emojisense|bie|0.9.0
vscode-styled-jsx|bla|2.1.1
vscode-intelephense-client|bme|1.8.2
htmltagwrap|bra|0.0.7
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
vscode-faker|dee|2.0.0
vscode-glsllint|dto|1.8.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
vscode-firefox-debug|fir|2.9.6
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vscode-yarn|gam|2.1.0
gc-excelviewer|Gra|4.2.54
beautify|Hoo|1.5.0
rest-client|hum|0.24.6
vscode-edit-csv|jan|0.6.8
c-cpp-flylint|jbe|1.11.0
vscode-jsonp|luy|1.0.1
MagicPython|mag|1.1.0
rainbow-csv|mec|2.2.0
vscode-language-babel|mgm|0.0.36
vscode-clang|mit|0.2.4
vscode-kanban|mkl|1.32.0
mongodb-vscode|mon|0.9.2
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
cpptools|ms-|1.9.7
vsliveshare|ms-|1.0.5527
sqltools|mtx|0.23.0
sqltools-driver-mssql|mtx|0.2.0
sqltools-driver-pg|mtx|0.2.0
vetur|oct|0.35.0
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
subtitles-editor|pep|1.1.6
LiveServer|rit|5.7.5
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.2
shader|sle|1.1.5
sass-indented|syl|1.8.19
pdf|tom|1.2.0
vscode-icons|vsc|11.11.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.26.0
markdown-all-in-one|yzh|3.4.2
material-theme|zhu|3.13.21

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30433507
vsclayoutctrc:30437038
vsrem710:30416614
dsvsc009:30440023
vsbas813:30436447
vscscmwlcmt:30438805
helix:30440343

```

</details>

**Comment by romanlex** [comment]
Can confirm
![image](https://user-images.githubusercontent.com/3369304/164482061-52401a68-f656-4ef1-b51f-fb4b9178c961.png)

**Comment by romanlex** [comment]
![image](https://user-images.githubusercontent.com/3369304/164483791-1149fbf8-3055-4a66-af0f-fc36c9a308a1.png)
can confirm

**Comment by tyxou** [comment]
unfortunately this became unbearable and had to switch to another IDE, until hopefully it is fixed

**Comment by deepak1556** [comment]
@tyxou2 can you provide the cli of the process that shows high cpu usage, from the process info you have shared in the issue it indicates CPU usage from the extension host, so this is very likely related to one of the extensions you have installed and not from core. The cli is a good starting point to narrow down what process is responsible.

**Comment by tyxou2** [comment]
sorry, forgot it open!
