### ISSUE TITLE
Suggestion to add "title" to contributes/menus

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#147746]
When developing an extension which adds a lot of commands we prefix all commands with an identifier so that you easily can find all commands belonging to our extension when opening the command palette and searching for that prefix. (Also if we didn't prefix the command it wouldn't be obvious to the user that it belongs to the extension which we want)

However contributes/menus/"view/title" reuses the title from the command so that when you hover over a button it has the same prefix, which we don't really want since (in this case) the custom treeview we have is really obvious that it belongs to our extension.

Similarly we might want the hover to be more or less descriptive than the command title in general.

So if we could have an extra "title" or similar in contributes/menus/"view/title"-entries which could default to the command name that would be nice.

Mockup contributes (might contain errors) to hopefully help with showing what I mean:
```
{
  "contributes": {
    "commands": [
      {
        "command": "customList.doSomething",
        "title": "NameOfExtension do something",
        "icon": {
          "light": "media/iconBlack.svg",
          "dark": "media/iconWhite.svg"
        }
      }
    ],
    "menus": {
      "view/title": [
        {
          "command": "customList.doSomething",
          "when": "view == customList",
          "group": "navigation@1",
          "title": "Do something" // <--- suggested field to avoid hover showing "NameOfExtension do something"
        }
      ]
    },
    "views": {
      "custom-list": [
        {
          "id": "customList",
          "name": "",
          "icon": "media/listIcon.svg",
          "contextualTitle": "Custom"
        }
      ]
    }
  }
}
```

**Comment by MrAndersen1** [comment]
I can work around this by having two commands, with the same behavior, where the one assigned to the button has an "enablement" property with value "view == customList" causing it to not show up in the command palette.

Maybe that's the intended way to do it? Then we can close this.

**Comment by joaomoreno** [comment]
I generally like this idea, but I'll leave it up to @jrieken.

**Comment by jrieken** [comment]
> When developing an extension which adds a lot of commands we prefix all commands with an identifier so that you easily can find all commands belonging to our extension when opening the command palette

Don't do that. Instead use the `category`-property. In short

* `title` should be the normal title, 
* there is `shortTitle` for a more compact variant of that, 
* and `category` for the name of the scope/feature/extension. 

The different UIs will then decide what of these bits and pieces to render, eg the command palette renders "<category>: <title>" but other menu use just title
