### ISSUE TITLE
Frequent disconnection while connecting to AML

### ISSUE THREAD

**Issue by bkuriach** [microsoft/vscode#147784]
Issue Type: <b>Bug</b>

Frequent disconnection while connecting to AML

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22598
Restricted Mode: No
Connection to 'Azure ML: aml-workspace-cpu' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.41GB free)|
|Process Argv|--open-url --crash-reporter-id fa2c14b4-d105-43b1-8a16-b7b86827cfb5 -- vscode://ms-toolsai.vscode-ai/computeInstance/remote?computeId=/subscriptions/4c7cb17d-ccf9-4af5-964f-b453c96bbd72/resourceGroups/aml-resources-bk/providers/Microsoft.MachineLearningServices/workspaces/aml-workspace-bk/computes/aml-workspace-cpu&sessionId=Im9wJ|
|Screen Reader|no|
|VM|0%|

Connection to 'Azure ML: aml-workspace-cpu' could not be established  Canceled
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by dbaeumer** [comment]
@bkuriach VS Code doesn't ship with Azure-ML integration in the box. Can you please report the issue against the extension you are using.
