### ISSUE TITLE
Add custom sidebar items to View menu

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#147719]
This confuses users that it's absent, especially if the sidebar is hidden. A picture is worth a 1000 words:
![image](https://user-images.githubusercontent.com/5781692/164089097-2b8f93d1-42b8-4501-b2df-e890fa163993.png)

Note that if you right click on the sidebar, it does show up, so users expect the same to happen in the View menu:
![image](https://user-images.githubusercontent.com/5781692/164089265-6a3b8916-b122-4dd8-905f-96413a73fa6c.png)

**Comment by sbatten** [comment]
The list is currently static and built-in views. This is to ensure that the menus are not overrun by entries as well as ensure the user can find built-in views no matter how complicated added extensions make the UI. I don't personally see this as something we would change.
