### ISSUE TITLE
In a remote window, folder picker shows the contents of the parent directory rather than the current directory

### ISSUE THREAD

**Issue by shsuman** [microsoft/vscode#147795]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Win 11 Enterprise

Steps to Reproduce:

1. Open a remote connection in Folder A/B/C
2. Click File -> Open Folder
3. The folder picker opens up and shows all the directories in parent folder B and not inside C

Is this by design ? Is there a way to override this ?

**Comment by alexr00** [comment]
@shsuman this should be how "Open Folder" works in all cases, remote or not. I have folder c:\users\alros\repos\microsoft\vscode open in VS Code, then I run "Open Folder", the starting dir will be c:\users\alros\repos\microsoft. This is different from "Open File", which starts in c:\users\alros\repos\microsoft\vscode
