### ISSUE TITLE
Provide a way to disable 'WorkSpace Trust' popup so it won't show in remote development env

### ISSUE THREAD

**Issue by luyu12** [microsoft/vscode#147736]
Provide a way to disable 'WorkSpace Trust' popup so it won't show in remote development env

The trusted workspaces concept is intended to centralize and unify a security conscious decision required by a variety of VS Code features. so that's why I guess the settings only belong to users' setting but not other workspaces/folders.
But I'm also seeing that in remote env, you have some logics to make resolver explicitly set the workspace trust to true, so it won't show the 'trust folder' popup to users?
`		// Remote - resolver explicitly sets workspace trust to TRUE
		if (this.environmentService.remoteAuthority && this._remoteAuthority?.options?.isTrusted) {
			return this._remoteAuthority.options.isTrusted;
		}
`
is there a way to make it explicitly useable/callable? Is there a way to disable the popup in remote env but not changing the global user setting?

**Comment by sbatten** [comment]
@luyu12 I am not sure exactly what you mean. Are you referring to this as a user or an extension author? Can you walk me through the specific scenario?

**Comment by luyu12** [comment]
Yeah. Im talking about this as an extension author. 
My goal is to have a way implemented in the extension to disable/suppress the 'trust workspace' popup only in remote dev environment not globally(though I'm aware that the val can be disabled in users.settings e.g. `"security.workspace.trust.enabled": false`). Is there a mechanism that VS Code internally is using to suppress the 'trust workspace' popup in the remote(e.g. codespaces)? Does this clarify?

**Comment by sbatten** [comment]
closing after offline discussion
