### ISSUE TITLE
Test: editor error placeholders

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147706]
Refs: https://github.com/microsoft/vscode/issues/142875, https://github.com/microsoft/vscode/issues/130971

- [ ] anyOS @TylerLeonhardt
- [x] anyOS @chrmarti

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23147706%0A%0A&assignees=bpasero)

---

The editor placeholder in case of error was updated and also shows in more cases now. The easiest is to create a HTML file with a link to a file that does not exist and click it to open as editor.
* verify you still get asked to create the file from a modal dialog
* if you don't create a file, the editor place holder properly conveys the error and offers the same action as the dialog
* if you create the missing file in this flow, the editor place holder goes away

Alternatively you can:
* open a file
* close VSCode
* delete the file
* start VSCode
* the editor restores but with the error placeholder since the file was deleted on disk

**Comment by TylerLeonhardt** [comment]
Works well!
