### ISSUE TITLE
Wrong bash terminal loaded on startup

### ISSUE THREAD

**Issue by markschat** [microsoft/vscode#147786]
When (and only when) I start VSCode a bash terminal is loaded, that is not the default one, nor existent in the terminal profiles. If I open my default bash terminal after startup, everything works out fine.

I use the following setup
- VSCode (v.1.66.2) on Windows 10 connected via the "Remote - SSH" Plugin to an Linux Server
- My bash has a specific setup defined in `.bash_profile` -> `"args":["-l"]` ensures the setup is called

Here´s settings.json:
``` json
{
  "terminal.integrated.profiles.linux": {
      "bash": {
        "path": "/usr/bin/bash",
        "icon": "terminal-bash",
        "args": [
          "-l"
        ]
      },
     // ...
    },
    "r.rpath.linux": "/opt/R/4.1.1/lib64/R/bin/R",
    "terminal.integrated.customGlyphs": false,
    "terminal.integrated.defaultProfile.linux": "bash",
    // ...
}
```

On startup I see this Terminal (see icon & bash appearance):

![image](https://user-images.githubusercontent.com/43857618/164287087-0850f472-d39e-44a6-9d49-342237a776bb.png)

When opening my default bash afterwards I get this:

![image](https://user-images.githubusercontent.com/43857618/164287342-1ddaf651-b828-4338-9f0b-cf14406e0a36.png)
- icon as defined in `settings.json`
- my bash setup from `.bash_profile` is loaded correctly

A weird thing I´ve observed are the `Integrated > Default Profile: Linux` settings. In `settings.json` bash is only defined once - here I see two options.

![image](https://user-images.githubusercontent.com/43857618/164288409-dcc45dea-5dc9-409d-aa0e-5cd01e2b7eb1.png)

it seems `bash (2)` is loaded at startup as `"args":["-l"]` is missing there...

<!-- 📣 Issues caused by an extension need to be reported directly to the extension publisher. The 'Help > Report Issue' dialog can

**Comment by meganrogge** [comment]
It works for terminal #2 and beyond, correct?

**Comment by markschat** [comment]
@meganrogge thanks for pointing out the existing issue 👏. Seems to be the same problem here - wasn´t able to find it among the few other ones 😉.
