### ISSUE TITLE
Breakpoint in JavaScript becomes unbound breakpoint at runtime

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#147723]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Same issue with Insiders.

Steps to Reproduce:

1. Set a JavaScript breakpoint. Breakpoint shows as solid red dot
![image](https://user-images.githubusercontent.com/1051118/164103155-f6641d81-24f3-4b51-b6c4-d259b6089557.png)

2. Run application
3. Breakpoint becomes disabled unbound breakpoint hollow dot
![image](https://user-images.githubusercontent.com/1051118/164103259-02bd43f1-c4d9-4d57-96c6-0bbef50f80e9.png)

4. Go to page that will trigger breakpoint
5. Click the unbound breakpoint to remove it. Click again to re-add it
6. Breakpoint becomes enabled
![image](https://user-images.githubusercontent.com/1051118/164103796-51882646-02e7-451a-a141-4b2ed4480011.png)

launch.json

    {
      "name": "Chrome Launch",
      "type": "chrome",
      "request": "launch",
      "url": "https://localhost/mysite/",
      "webRoot": "${workspaceFolder}",
      "runtimeArgs": ["--profile-directory=debug-profile"],
      "resolveSourceMapLocations": [
        "${workspaceFolder}/**",
        "!**/node_modules/**"
      ]
    }

**Comment by cupric8** [comment]
I'm seeing similar behavior.

1. set a breakpoint in a javascript file
2. start a session with the 'Launch Chrome' configuration
3. breakpoint indicators change to empty circles (unbound breakpoint)
4. open chrome developer tools and use them to set a breakpoint at an earlier line
5. refresh page - execution halts at the line set in chrome.  VSCode reports execution stopped at that line.  The breakpoint set in VSCode continues to show as unbound (hollow circle).  
6. deleting the unbound breakpoint and resetting it shows it as bound.
7. continuing execution stops at the breakpoint from previous step.
8. setting breakpoints now proceeds normally even if execution is not currently halted in the debugger.

Relevant portion of launch.json:
"configurations": [
        {
            "name": "Launch Chrome",
            "request": "launch",
            "type": "chrome",
            "url": "http://localhost/${workspaceFolderBasename}",
            "webRoot": "/Users/dxxxxxxxxxxxx/Sites/${workspaceFolderBasename}"
        }

About VSCode: 
Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0

All plugins are disabled.

macOS Monterey
version 12.3.1 

Chrome
Version 100.0.4896.127 (Official Build) (arm64)

**Comment by Mil0o118** [comment]
Same issue here, it work if I remove the "${workspaceFolder}/**" to the lauch.json file in configurations : "resolveSourceMapLocations": ["${workspaceFolder}/**", "!**/node_modules/**"]

**Comment by xgdgsc** [comment]
Could it be a variable resolvation issue like what I have with the julia extension: https://github.com/julia-vscode/julia-vscode/issues/2851 ? Variables like `workspaceFolderBasename` could fail to resolve randomly?

**Comment by connor4312** [comment]
It looks like your `webRoot` is set to `/Users/USERNAME/Sites/Bankbook`, however your code is located in `/Users/USERNAME/SourceCode/Bankbook`.

Based on this, when you set a breakpoint in `/Users/USERNAME/SourceCode/Bankbook/js/ledger.js`, the debugger expected to find that at `http://localhost/../SourceCode/Bankbook/ledger.js`, but it was actually at `http://localhost/Bankbook/js/ledger.js`.

So you should just need to set your webRoot to `/Users/USERNAME/SourceCode` instead.

**Comment by connor4312** [comment]
It looks like your `webRoot` is set to `/Users/USERNAME/Sites/PROJECT`, however your code is located in `/Users/USERNAME/SourceCode/PROJECT`.

Based on this, when you set a breakpoint in `/Users/USERNAME/SourceCode/PROJECT/js/ledger.js`, the debugger expected to find that at `http://localhost/../SourceCode/PROJECT/ledger.js`, but it was actually at `http://localhost/PROJECT/js/ledger.js`.

So you should just need to set your webRoot to `/Users/USERNAME/SourceCode` instead.

**Comment by capegreg** [comment]
> It looks like your `webRoot` is set to `/Users/USERNAME/Sites/PROJECT`, however your code is located in `/Users/USERNAME/SourceCode/PROJECT`.
> 
> Based on this, when you set a breakpoint in `/Users/USERNAME/SourceCode/PROJECT/js/ledger.js`, the debugger expected to find that at `http://localhost/../SourceCode/PROJECT/ledger.js`, but it was actually at `http://localhost/PROJECT/js/ledger.js`.
> 
> So you should just need to set your webRoot to `/Users/USERNAME/SourceCode` instead.

I do not believe this issue should be closed. How did you determine this solution? Was the webRoot path issue determined from the provided trace dump, or are you responding to another member? My launch.json configuration has not changed in 3 years, but only after VSCode dumped Chrome debugger did breakpoints stop working.

**Comment by connor4312** [comment]
Yes, I was able to determine the issue by looking at the trace dump

**Comment by capegreg** [comment]
> Yes, I was able to determine the issue by looking at the trace dump

This is my workspaceFolder. I can only guess that you're not looking at my trace log because I don't have any js/ledger.js and I don't do any work from my /Users directory.
![image](https://user-images.githubusercontent.com/1051118/165301159-179e58c5-3be1-4cb5-a9b0-c955ae23395e.png)

**Comment by connor4312** [comment]
Ah, looks like I got two emails from this issue. The former solution is for @cupric8.

In your case, it looks like the webroot should also be adjusted, to `C:\Workspace\dev.manateepao.com`. Using the same logic: the webroot is set to `C:\Workspace\dev.manateepao.com\wp-content\themes\frontier-child`, and you set a breakpoint in `c:\Workspace\dev.manateepao.com\wp-content\themes\frontier-child\assets\js\mcpao-aerial.js`, therefore it expects the script to be located at `https://<DOMAIN>.com/assets/js/mcpao-aerial.js`, but it's actually at `https://<DOMAIN>.com/wp-content/themes/frontier-child/assets/js/mcpao-aerial.js`. You actually want to preserve those fragments, so should set the webRoot to `C:\Workspace\dev.manateepao.com` instead.

Long term I want to fix this with https://github.com/microsoft/vscode-js-debug/issues/1214
