### ISSUE TITLE
Errors in debug consoles: Error: getaddrinfo ENOTFOUND default.exp-tas.com

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode#147743]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.1
- OS Version: Windows 10 1909

Steps to Reproduce:

1. Debug an extension...

```
[Extension Host] stack trace: Error: getaddrinfo ENOTFOUND default.exp-tas.com	at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)	at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) (at c:\Users\Ark\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:104:35330)
D @ workbench.desktop.main.js:71
$logExtensionHostMessage @ workbench.desktop.main.js:1705
_doInvokeHandler @ workbench.desktop.main.js:1705
_invokeHandler @ workbench.desktop.main.js:1705
_receiveRequest @ workbench.desktop.main.js:1705
_receiveOneMessage @ workbench.desktop.main.js:1705
(anonymous) @ workbench.desktop.main.js:1705
invoke @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:83
_receiveMessage @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
invoke @ workbench.desktop.main.js:67
fire @ workbench.desktop.main.js:67
acceptChunk @ workbench.desktop.main.js:83
(anonymous) @ workbench.desktop.main.js:83
O @ workbench.desktop.main.js:3102
emit @ node:events:390
addChunk @ node:internal/streams/readable:315
readableAddChunk @ node:internal/streams/readable:289
Readable.push @ node:internal/streams/readable:228
onStreamRead @ node:internal/stream_base_commons:199
```

I tried to visit the address. Previously it was not responding at all.

Right now it has `<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p>0YX5fYgAAAAB0eutYofHmQ7/c8abCoxMbQ08xRURHRTEyMTUARWRnZQ==`.

How can I make this stop? It interferes with my debugging.

![image](https://user-images.githubusercontent.com/1829149/164144909-9443a1cf-03a6-4974-b8d7-01cde362e1fd.png)

**Comment by sbatten** [comment]
You can right click the error in the dev console and hide messages from workbench.desktop.main.js. Alternatively, you can also disable experiments with the setting `workbench.enableExperiments` set to `false`. This should prevent us from trying to make the request at this time.
