### ISSUE TITLE
Integrated terminal access through extension?

### ISSUE THREAD

**Issue by hveiras** [Microsoft/vscode#14771]
Hi,

Is there any way to access the content shown in integrated terminal through an extension? I'm interested in formatting error messages o even explore the possibility of extending it so I can click on a stack trace and go to the line.

**Comment by rebornix** [comment]
Current Terminal API doesn't support this, you can take a look at https://github.com/Microsoft/vscode-extension-samples/blob/master/terminal-example/README.md to get an idea of what kind support we have right now.

**Comment by Tyriar** [comment]
It's not currently possible to get at the output or transform it in any way, here are some relevant issues:  

- https://github.com/Microsoft/vscode/issues/7321 clicking links in the terminal
- https://github.com/Microsoft/vscode/issues/11422 expose more info
- https://github.com/Microsoft/vscode/issues/13337 pipe all stdout/in through an extension

I'd love to bring link clicking to VS Code natively but it's currently blocked on the backing library we use [xterm.js](https://github.com/sourcelair/xterm.js). There's a bit to do to enable this like [fixing the linkify addon](https://github.com/sourcelair/xterm.js/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20linkify%20addon) and then allowing it to hook up to VS Code.
