### ISSUE TITLE
Langauge server keeps dieing

### ISSUE THREAD

**Issue by tautologistics** [microsoft/vscode#147740]
Issue Type: <b>Bug</b>

Start up VS Code and open a .ts file

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 7, 6|
|Memory (System)|64.00GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (122)</summary>

Extension|Author (truncated)|Version
---|---|---
postgresql|JPT|0.0.2
better-comments|aar|3.0.0
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.2.4
vscode-sqlite|ale|0.14.0
aws-toolkit-vscode|ama|1.37.0
vscode-color|ans|0.4.5
vscode-apollo|apo|1.19.10
cform|aws|0.0.24
vscode-django|bat|1.10.0
unique-lines|bib|1.0.0
markdown-checkbox|bie|0.3.2
markdown-mermaid|bie|1.13.2
mermaid-markdown-syntax-highlighting|bpr|1.2.3
insert-unicode|bru|0.13.3
vscode-modelines|chr|2.0.5
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
regex|chr|0.4.0
gitignore|cod|0.7.0
transformer|dak|1.12.1
aws-cloudformation-yaml|Dan|0.2.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
vscode-dash|dee|2.4.0
python-preview|don|0.0.4
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.6
toggle-excluded-files|eam|1.7.0
vscode-html-css|ecm|1.11.0
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.24
LogFileHighlighter|emi|2.15.0
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
json-tools|eri|1.0.2
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.40.0
go|gol|0.32.0
vscode-graphql|Gra|0.4.1
todo-tree|Gru|0.0.215
vscode-journal-view|Gru|0.0.26
vscode-dynamodb|har|0.0.1
vscode-guid|hea|1.4.20
beautify|Hoo|1.5.0
rest-client|hum|0.24.6
vscode-postfix-ts|ipa|1.9.4
vscode-random|jre|1.11.0
react-native-snippet|jun|0.5.6
vscode-cfn-lint|kdd|0.21.0
vscode-cloudformation|key|0.0.21
MagicPython|mag|1.1.0
rainbow-csv|mec|2.2.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-todo-parser|min|1.9.1
ecdc|mit|1.7.0
nc-gcode|ML|0.13.0
prettify-json|moh|0.0.3
compare-folders|mos|0.22.2
vscode-pugbeautify|mrm|1.0.2
vscode-docker|ms-|1.22.0
data-workspace-vscode|ms-|0.1.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
atom-keybindings|ms-|3.0.9
cpptools|ms-|1.9.7
hexeditor|ms-|1.9.5
node-debug2|ms-|1.43.0
vscode-typescript-next|ms-|4.7.20220419
vscode-typescript-tslint-plugin|ms-|1.3.4
sqltools|mtx|0.23.0
vscode-json-editor|nic|0.3.0
snippet-creator|nik|0.0.5
autodocstring|njp|0.6.1
hide-gitignored|npx|1.1.0
indent-rainbow|ode|8.3.1
vscode-journal|paj|1.0.0
vscode-code-outline|pat|0.2.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.16.0
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.6.0
synthwave-vscode|Rob|0.1.11
codeui|rya|0.3.2
partial-diff|ryu|1.4.3
text-marker|ryu|1.11.0
explorer-excluded-files|sad|1.0.0
jinjahtml|sam|0.17.0
preview-vscode|sea|2.2.5
vscode-sql-beautify|sen|0.0.4
markdown-preview-enhanced|shd|0.6.2
guides|spy|0.9.3
autoimport|ste|1.5.4
unique-window-colors|stu|1.0.51
python|tht|0.2.3
go-to-method|tri|0.2.0
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.19
vscode-mermaid-preview|vst|1.6.2
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
change-case|wma|1.0.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.2

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by tautologistics** [comment]
A little more info before I close this...

The TS language server would repeatedly get terminated from a `SIGABRT` signal shortly after startup and with no relevant info in the logs of that extension or any other. It appears that the TS lint extension (`ms-vscode.vscode-typescript-tslint-plugin`) was silently failing because for some reason it could no longer find a suitable `tslint` in its `PATH`.

This TS lint failure seems to have been causing the the language server to also terminate (or perhaps the tslint dependency was causing both to fail?) because as soon as I reinstalled tslint globally (specifically `npm i -g eslint@8.2`) the language server stopped terminating.
