### ISSUE TITLE
Deleting a project

### ISSUE THREAD

**Issue by KiaEkstrom** [microsoft/vscode#147796]
Issue Type: <b>Performance Issue</b>

I have problems committing my files to GitHub so I would just want to delete everything from my VS Code and start fresh. Why is it impossible to delete a project on VS Code?

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by lszomoru** [comment]
@KiaEkstrom, could you please clarify what you mean by "deleting a project on VS Code"? You can always clone the GitHub repository to a new folder, so that you do not lose your local change, and open the project from the new location in VS Code.

**Comment by KiaEkstrom** [comment]
@lszomoru That didn't come to my mind, but I cloned my repository to a new folder and now it's working! Earlier I had tried so many times to delete my files from VS Code and add them again, and the committing wasn't just working anymore. I was too fixated to commit the files from VS Code and didn't consider doing it the other way around. But cloning the GitHub repository helped, thanks a lot!
