### ISSUE TITLE
Typing } or ] sometimes doesn't work due to "Error: Brackets from different language configurations cannot be used" with the latest VS Code Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#147724]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.67.0-insider (user setup)
Commit: e7c6ad74aff28965d0189ca1dd584f5e9829cf06
Date: 2022-04-19T09:43:36.551Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000
- OS Version: Windows

Steps to Reproduce:

1. Install the C/C++ extension -- that extension isn't the cause, but it seems to be a requirement for some unknown reason.
2. Open a blank VS Code instance.
3. Do File->New Text File.
4. Change the language to C++.
5. Paste code
```

int main()
{
    int main()
    {

    
}
```
6. Try to type } to close the bracket for the inner main method.

Bug: Typing } or ] fails to have any effect.

Toggle Developer Console shows the error: "Error: Brackets from different language configuration cannot be used."
```
y (languageBracketsConfiguration.ts:168)
closes (languageBracketsConfiguration.ts:143)
(anonymous) (bracketPairsImpl.ts:133)
l (arrays.ts:369)
n (arrays.ts:358)
findMatchingBracketUp (bracketPairsImpl.ts:132)
_typeInterceptorElectricChar (cursorTypeOperations.ts:789)
typeWithInterceptors (cursorTypeOperations.ts:968)
(anonymous) (cursor.ts:559)
_executeEdit (cursor.ts:514)
type (cursor.ts:548)
(anonymous) (viewModelImpl.ts:1009)
_withViewEventsCollector (viewModelImpl.ts:1058)
_executeCursorEdit (viewModelImpl.ts:997)
type (viewModelImpl.ts:1009)
_type (codeEditorWidget.ts:1142)
trigger (codeEditorWidget.ts:1075)
runCommand (coreCommands.ts:1892)
handler (editorExtensions.ts:121)
E.handler (commands.ts:90)
invokeFunction (instantiationService.ts:61)
_tryExecuteCommand (commandService.ts:95)
executeCommand (commandService.ts:60)
type (codeEditorWidget.ts:1727)
type (viewController.ts:71)
(anonymous) (textAreaHandler.ts:311)
invoke (event.ts:575)
deliver (event.ts:779)
fire (event.ts:740)
(anonymous) (textAreaInput.ts:370)
invoke (event.ts:575)
deliver (event.ts:779)
fire (event.ts:740)
Ye (dom.ts:157)
```

It seems like a recent change to VS Code Insiders in regards to } matching is the cause.

This is a major blocking issue and I have to switch to the non-Insiders VS Code.

**Comment by sean-mcmanus** [comment]
I got a 100% repro, but so far only with my closed source file , and it only seems to repro when I enable our C/C++ extension -- I don't know how our extension could be breaking typing of }, maybe it requires semantic tokens or something.

**Comment by sean-mcmanus** [comment]
Toggle Developer Console shows the error "Error: Brackets from different language configuration cannot be used. " -- that appears to be the "cause". Is that enough to figure out the bug?

**Comment by sean-mcmanus** [comment]
This may have been caused by https://github.com/microsoft/vscode/commit/d1e27d8f7d1fdac8446cc6e7335286331d85c5bc 

@hediet Do you understand how your change may have caused this bug to repro?

**Comment by sean-mcmanus** [comment]
For some reason it thinks `other['config'] !== this.config` but the values appear identical in the debugger -- the underlying objects might be different.

**Comment by sean-mcmanus** [comment]
I figured out repro steps -- the original description has been updated.

**Comment by hediet** [comment]
Thanks, I'm looking into it!

**Comment by hediet** [comment]
Bugfix will be available in tomorrows insider release!
