### ISSUE TITLE
Namespace '"vscode"' has no exported member 'TreeDragAndDropController'.

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#147729]
I am trying to play with the new TreeView drag and drop api but I get the error in the title for all related api usages.  Like:

```
import * as vscode from 'vscode';

vscode.TreeDragAndDropController       // these all get the red squigglies and error message
vscode.DataTransfer<vscode.DataTransferItem>
vscode.DataTransferItem
```

Also: `Argument of type '{ treeDataProvider: TabTreeDataProvider; showCollapseAll: true; canSelectMany: true; dragAndDropController: TabTreeDragContoller; }' is not assignable to parameter of type 'TreeViewOptions<treeNodes>'.
  Object literal may only specify known properties, and 'dragAndDropController' does not exist in type 'TreeViewOptions<treeNodes>'.`

It is as if the interface `interface TreeDragAndDropController<T>` is not yet exposed in the api.  It isn't  **proposed** anymore - is there something I have to do to get access to this part of the api?

@meganrogge 

This happens in current Stable or Insiders.  

Version: 1.67.0-insider (user setup)
Commit: e7c6ad74aff28965d0189ca1dd584f5e9829cf06
Date: 2022-04-19T09:43:36.551Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22598

**Comment by alexr00** [comment]
Make sure you bump all your vscode versions in your package.json to 1.66, the version that the API was finalized in, and then do an `npm install` or `yarn`.
