### ISSUE TITLE
No workbench action to hide panel

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14779]
- VSCode Version: 1.6.1

There's no editor action to hide the panel. There is only `workbench.action.togglePanel`, and there's apparently no context so you can do `when: "panelVisible"` or whatever. So there's no way to bind a key to something that hides the panel.

**Comment by rebornix** [comment]
That's `cmd+b` :)

**Comment by atombender** [comment]
_Panel_, not sidebar.

```
{ "key": "cmd+j", "command": "workbench.action.togglePanel" },
{ "key": "cmd+b", "command": "workbench.action.toggleSidebarVisibility" },
```

**Comment by atombender** [comment]
(Also, `cmd+b` also _toggles_, doesn't hide.)

**Comment by atombender** [comment]
@rebornix Want to reopen?

**Comment by rebornix** [comment]
Sorry for the misunderstanding. And yes they share the same problem, no way to directly hide or show. It's a valid request and I think ppl have similar request in #13776 . Let's see if there will be any new API while implement that feature.

**Comment by atombender** [comment]
That seems like a different issue: Hide _all_ panels/sidebar. This is just about needing a command.

**Comment by rebornix** [comment]
IMO I think it's not a good idea that just exposing a way to hide everything instead of splitting them into several meaningful commands. But wait and see @isidorn 's input on this and then see if we want to open this issue for tracking.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/14674
