### ISSUE TITLE
Cmd+D selects too broadly in some grammars

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14770]
- VSCode Version: 1.6.1
- OS Version: 10.12.1

In some grammars such as JSON, cmd+D matches a lot more than in other grammars. In most grammars, cmd+D seems to use word-matching semantics. In most grammars, if your caret is here:

```go
"hello world<caret>"
```

and you hit cmd+D, then `world` is selected. In JSON files, the entire `"hello world"` is selected. That's inconsistent and weird. I don't know what other grammars are affected.

Behaviour is same irrespective of whether "whole word" match semantics are enabled.

**Comment by rebornix** [comment]
@atombender thanks for reporting this issue. About `cmd+d` behavior in json files, it's tracked in #10080 and actually our way of handling `cmd+d` is consistent, it's selecting a word under cursor while different languages take different wordSeparators. That's basically why you see this issue. Please take a look at that issue if you are interested.
