### ISSUE TITLE
Test flat file watchers inside workspace

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147703]
Refs: https://github.com/microsoft/vscode/issues/146066

- [x] anyOS @meganrogge
- [ ] anyOS @chrmarti

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23147703%0A%0A&assignees=bpasero)

---

Previously an extension was not able to create a file system watcher inside the workspace, but now we allow this for non-recursive watchers. This allows an extension to not be impacted by a potentially blocking `files.watcherExclude` rule.

* have a simple hello world extension
* use the `createFileSystemWatcher` API for a folder that is inside the opened workspace with a non-recursive pattern (i.e. no `**`)
* configure `files.watcherExclude` to explicitly exclude the folder your extension wants to watch
* verify that you still get the file events delivered to your extension

**Comment by chrmarti** [comment]
@bpasero With the following I get events without the exclusion, but none with the exclusion. Do I misunderstand the instructions or is this a bug?

```ts
		const watcher = vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern(vscode.workspace.workspaceFolders[0], 'bar/*.js'));
		watcher.onDidChange(uri => {
			console.log('onDidChange');
			console.log(uri.toString());
		});
		watcher.onDidCreate(uri => {
			console.log('onDidCreate');
			console.log(uri.toString());
		});
		watcher.onDidDelete(uri => {
			console.log('onDidDelete');
			console.log(uri.toString());
		});
```

```json
	"files.watcherExclude": {
		"bar": true
	}
```

Version: 1.67.0-insider
Commit: ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af
Date: 2022-04-26T05:15:57.573Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

**Comment by bpasero** [comment]
@chrmarti I am seeing events though, even with the setting:
![Recording 2022-04-26 at 16 24 53 (1)](https://user-images.githubusercontent.com/900690/165322482-64728ded-c952-49d3-8beb-a2ebc17a15ca.gif)

**Comment by chrmarti** [comment]
It started working and only stopped working again when I started with a new workspace folder. Not sure if I'm doing something specific to trigger it or if there is some randomness to it.

**Comment by chrmarti** [comment]
Continuing in https://github.com/microsoft/vscode/issues/148245.
