### ISSUE TITLE
JavaScript highlighting issue

### ISSUE THREAD

**Issue by SMH110** [Microsoft/vscode#14776]
- VSCode Version: Code - Insiders 1.7.0-insider (0706b425537d8cfe2766eac00662ecf988c7ed7f, 2016-10-28T13:10:55.168Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|3.0.7|
|code-spell-checker|streetsidesoftware|0.11.4|

---

See screenshot below. Text highlighting seems broken for `'person\'s email'`

![image](https://cloud.githubusercontent.com/assets/16171515/19868340/8e0a3e34-9f9f-11e6-89ce-9fa249785bc3.png)

**Comment by waderyan** [comment]
@SMH110 thank you for opening this issue. The grammar is dependent on this [repo](https://github.com/Microsoft/TypeScript-TmLanguage). Can you move it there and they can resolve the issue?
