### ISSUE TITLE
Source Control and Explorer don't update after some changes in directory or files

### ISSUE THREAD

**Issue by WolfAvenger** [microsoft/vscode#147779]
Issue Type: <b>Performance Issue</b>

Hello! I have the next problem. I pulled my repo from gitlab via ssh and after it my explorer and source control started not to see any changes in my files I do after some work with my code. On other PCs VSCode does it automatically, but here I have to press reload button to look for all the changes I did. How can I fix that? Thanks a lot.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (25.50GB free)|
|Process Argv|--crash-reporter-id dd3cd20d-7655-4196-ae19-924f8b45e0c2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	  6004	code main
    0	    87	   996	   issue-reporter
    0	    26	  6380	   crashpad-handler
    0	    86	  7276	   gpu-process
    0	   105	  8032	   shared-process
    0	    69	  1412	     ptyHost
    0	    73	  7296	     fileWatcher
    0	   180	  9696	   extensionHost
    0	   172	   608	     "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\semen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName C:\Users\semen\AppData\Local\Temp\vscode-typescript\0a8b97dcd00f85ac7e98\tscancellation-9874eebfe54c1dff608a.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    91	 11008	       "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:/Users/semen/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js" --globalTypingsCacheLocation C:/Users/semen/AppData/Local/Microsoft/TypeScript/4.6 --enableTelemetry --typesMapLocation "c:/Users/semen/AppData/Local/Programs/Microsoft VS Code/resources/app/extensions/node_modules/typescript/lib/typesMap.json" --validateDefaultNpmLocation
    0	   115	  2008	     "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node --max-old-space-size=3072 "c:\Users\semen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\tsserver.js" --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName C:\Users\semen\AppData\Local\Temp\vscode-typescript\0a8b97dcd00f85ac7e98\tscancellation-056f71a078a57efcec87.tmp* --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    73	  6636	     "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\semen\.vscode\extensions\stylelint.vscode-stylelint-1.2.2\dist\start-server.js --stdio --clientProcessId=9696
    0	   141	  7960	     "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\semen\.vscode\extensions\dbaeumer.vscode-eslint-2.2.2\server\out\eslintServer.js --node-ipc --clientProcessId=9696
    0	    72	 11312	     "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\semen\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=9696
    0	    71	 11828	     "C:\Users\semen\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\semen\.vscode\extensions\formulahendry.auto-rename-tag-0.1.10\packages\server\dist\serverMain.js --node-ipc --clientProcessId=9696
    0	   192	 10712	   window (App.tsx | frontend | Visual Studio Code)
    0	    38	 11580	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (App.tsx | frontend | Visual Studio Code)
|    Folder (frontend): 26 files
|      File types: json(4) ts(3) tsx(3) css(2) md(2) png(2) yml(1) svg(1)
|                  gitignore(1) txt(1)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
color-info|bie|0.7.0
vscode-toggle-quotes|Bri|0.3.6
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vue|jcb|0.1.5
vscode-docker|ms-|1.22.0
remote-wsl|ms-|0.66.0
vetur|oct|0.35.0
material-icon-theme|PKi|4.16.0
project-snippets|reb|0.5.0
vscode-stylelint|sty|1.2.2
vscode-status-bar-format-toggle|tom|3.0.0
ts-react-snippets|vad|1.4.0
vscode-todo-highlight|way|1.0.5
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by lszomoru** [comment]
The list of files in the source control viewlet are being refreshed as a response of file system events.
Could you please try the following and share the logs that are being generated:
- Open the folder/workspace in VS Code
- Enable logging for file system events as described in the following [wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local)
- Invoke the `Git: Set Log Level` command from the command palette and set the log level to `Trace`
- Make a change to a file, and save the changes
- Attach the file system logs, as well as the git output logs that you can access by invoking the `Git: Show Git Log` command from the command palette

You also mention that on other PCs this works as expected. Have you checked out the exact same repository in the other PCs and things are working as expected?

**Comment by WolfAvenger** [comment]
I tried to find solution on my own while expecting the answer and found it accidentally. The problem was in my WSL Ubuntu 18.04, it had some issues and I decided to install another version of Ubuntu 20.04 LTS. This ticket may be closed. Thank you a lot :3

**Comment by lszomoru** [comment]
Thanks for the update. Glad to hear that the issue has been resolved.

**Comment by gziras-in** [comment]
> The list of files in the source control viewlet are being refreshed as a response of file system events. Could you please try the following and share the logs that are being generated:
> 
> * Open the folder/workspace in VS Code
> * Enable logging for file system events as described in the following [wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local)
> * Invoke the `Git: Set Log Level` command from the command palette and set the log level to `Trace`
> * Make a change to a file, and save the changes
> * Attach the file system logs, as well as the git output logs that you can access by invoking the `Git: Show Git Log` command from the command palette
> 
> You also mention that on other PCs this works as expected. Have you checked out the exact same repository in the other PCs and things are working as expected?

Hello! I have a similar problem under remote development extension. I am attaching remote server log files after I change and save a file.

In the first case,  in a large repository everything seems ok. Source control viewlet is auto-refreshed.
[ok.log](https://github.com/microsoft/vscode/files/8558498/ok.log)

In the second case, in a smaller repository at the same server the line "File Watcher (parcel)" is missing. Source control viewlet is not updated.  
[problematic.log](https://github.com/microsoft/vscode/files/8558499/problematic.log)

Git logs do not show anything until i hit the refresh button. Is there anything else I can share with you in order to assist? 

Thank you in advance.

**Comment by lszomoru** [comment]
@gziras-in, could you please file a separate issue so that we can investigate the problem that you are facing. Could you please follow the steps from [this wiki page](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues), to collect additional telemetry related to the file system watcher, and attach the logs to the new issue. Thank you!
