### ISSUE TITLE
Move tab with keyboard

### ISSUE THREAD

**Issue by oste** [Microsoft/vscode#14772]
- VSCode Version: 1.6
- OS Version: OSX Sierra

It would be great if you could move tabs with the keyboard. Something like this Sublimetext plugin https://github.com/SublimeText/MoveTab

This makes it so pressing shift and command + arrow would move the tab left or right. You could also configure it so you can move a tab to the first position with one binding.

**Comment by rebornix** [comment]
We've already have this support, see here https://github.com/Microsoft/vscode/issues/10291
