### ISSUE TITLE
Feature Request : able to action 'testing.unhideTest' from a task.

### ISSUE THREAD

**Issue by yuki2006** [microsoft/vscode#147759]
I would like to run all the tests from the task.

However, if there is a hidden test (e.g. by mistake), that test will not be executed.

Is it possible to make `testing.unhideTest` work from task?

Or if there is a command that ignores the hidden ones and runs all tests, that would be fine.

`task.json`

```
        {
            "label": "test all",
            "type": "shell",
            "problemMatcher": [],
            "dependsOrder": "sequence",
            "promptOnClose": true,
            "dependsOn": [
                "testing.unhideTest",
                "testing.runAll",
            ]
        },

        {
            "label": "testing.unhideTest",
            "type": "shell",
            "problemMatcher": [],
            "command": "${command:testing.unhideTest}", # no action
        },
       {
            "label": "testing.runAll",
            "type": "shell",
            "problemMatcher": [],
            "command": "${command:testing.runAll}",
        },
```

**Comment by alexr00** [comment]
It looks like `testing.unhideTest` expects some arguments and you're looking for a command that unhides all.

**Comment by connor4312** [comment]
Code pointer for the existing action: https://github.com/microsoft/vscode/blob/5ca4d13b40a6b72a39b7ebf55941cdfa2d0558f6/src/vs/workbench/contrib/testing/browser/testExplorerActions.ts#L90

**Comment by Suven-p** [comment]
Should there be a new command to unhide all tests say testing.hideAll or a task to run all tasks including hidden tests - testing.runAllIncludingHidden?

**Comment by yuki2006** [comment]
@Suven-p Yes! please.

**Comment by rchiodo** [comment]
Verified it unhides all hidden tests.
