### ISSUE TITLE
New insider build corrupts settings.json and all existing settings in User Settings are no longer accessible 

### ISSUE THREAD

**Issue by erickangMSFT** [Microsoft/vscode#14774]
- VSCode Version: 17.0-insider
- OS Version: MAC 10.12.1

Steps to Reproduce:

1. Have settings in settings.json for User settings before updating VSCode to 17.0-insider
2. Upgrade to 17.0
3. All existing user settings in settings.json disappears and it is overrides by some properties from VSCode itself.

Some existing feature in Extensions are broken badly with this change.

**Comment by seanmcbreen** [comment]
@bpasero and @jrieken I htink you are the right guys here.

@erickangMSFT can you provide additional detail e.g. the commit number in the About dialogue and a sample of before and after settings.  I cannot repro this.  This would break the core of VS Code and also many extension so sounds bad - but there also could be an issue in how you are reading and writing settings.

**Comment by erickangMSFT** [comment]
We found out the insider build now reads settings.json file from a different location from GA version. This makes sense to me. Before 17.0, GA version and Insider versions read the same settings.json from the same location. In this case, it will be a no issue from my perspective.

**Comment by erickangMSFT** [comment]
This turn out to be a by-design where Insider build reads settings.json for Insider build specifically instead of sharing the same settings.json file with GA version. Thanks for the detail information from @seanmcbreen. Sharing the information here to help others as well.

Insider ‘user’ settings are specific to the insider build.  ‘Stable’ as a result stores there settings in another location, you can sync the two with:
[Howto sync settings between Stable and Insider version](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync)

[The location is documented here](http://code.visualstudio.com/docs/customization/userandworkspace#_settings-file-locations)

**Comment by bpasero** [comment]
Insiders build and stable build never read anything from the same location, they always had distinct folders for all the data (not just settings). There was no change in this area.

**Comment by hveiras** [comment]
The exact same thing happened to me today. I was switching between Insiders and Stable and I lost configurations in settings.json

**Comment by bpasero** [comment]
@hveiras what? is this reproducible?
