### ISSUE TITLE
i have a problem

### ISSUE THREAD

**Issue by fatdv** [microsoft/vscode#147768]
The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe" terminated with exit code: 2.
i dont know how to fix that , thank for read my report <3 
![image](https://user-images.githubusercontent.com/102346392/164250540-d28bf42f-0e8b-47ca-8ef6-d66c2fced9aa.png)

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"
