### ISSUE TITLE
Clavier MacOS

### ISSUE THREAD

**Issue by zime2019** [microsoft/vscode#147747]
Issue Type: <b>Bug</b>

Il faudrait faciliter l’utilisation du clavier MacOS ainsi que de pouvoir mettre les accents car cela est très penible 

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id f70b0564-a461-47f8-ae49-464540065ad7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
ACF-Snippet|ant|1.9.0
woocommerce|cla|1.1.0
wpcs-whitelist-flags|cla|1.1.0
vscode-devtools-for-chrome|cod|0.0.7
xml|Dot|2.5.1
gitlens|eam|12.0.6
vscode-html-css|ecm|1.11.0
vscode-pull-request-github|Git|0.41.2022040609
vscode-test-explorer|hbe|2.21.1
wordpress|hri|1.0.1
rest-client|hum|0.24.6
vscode-wordpress-hooks|joh|0.7.0
vscode-docker|ms-|1.22.0
vscode-language-pack-fr|MS-|1.66.3
vscode-edge-devtools|ms-|1.4.7
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.6
sqltools|mtx|0.23.0
php-docblocker|nei|2.7.0
vscode-xml|red|0.20.0
xml-toolkit|SAP|1.1.0
sap-ux-annotation-modeler-extension|SAP|1.5.4
bootstrap4-vscode|the|6.1.0
vscodeintellicode|Vis|1.2.19
vim|vsc|1.22.2
wordpress-toolbox|wor|1.3.12
cors-browser|Wsc|1.0.11
php-debug|xde|1.26.0
php-pack|xde|1.0.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

**Comment by rzhao271** [comment]
If I'm understanding you right, the issue is that it's currently annoying to add letters with accents using a macOS keyboard?
Do you have an example gif or key sequence that you can use to show how it's annoying? You can use https://gifcap.dev/ to record a short gif.
I'm also wondering what keyboard layout you are using?
