### ISSUE TITLE
Remote Container Stucks

### ISSUE THREAD

**Issue by fredcsfaria** [microsoft/vscode#147787]
Issue Type: <b>Bug</b>

1.  Open Remote-SSH COnnection to Linux Box
2.Open the Remote Folder in Container

3.  Expected Result: remote workspace openned in VS COde

Actual result:
The VS Code stucks in "OpenningContainer" and the log last lines show :
70898 ms] Start: Run in Host: docker exec -i -u root 9b67379d7f92ea643ad0ef2e0f20cfefac4e8da6cf76bfbe302a1aebadb51f03 /bin/sh
[70923 ms] Start: Downloading VS Code Server
[70924 ms] dfd34e8260c270da74b5c2d86d61aee4b6d56977 linux-x64 stable 
[71039 ms] Starting monitor process...
[71063 ms] Received message: [{"type":"configure","sequence":0,"options":{"cwd":"  ( ...  ) 
[131069 ms] Received message: []
[191080 ms] Received message: []
[251093 ms] Received message: []

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No
Connection to 'dev-container+7b22686f737450617468223a222f686f6d652f6773692f667265642f6c61626f7261746f72696f2f6964652f6f70656e7673636f64652f7673636f64652d72656d6f74652d7472792d6e6f6465222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22686f7374223a227373683a2f2f63642d6170706a642d3032227d7d' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD PRO A10-8750B R7, 12 Compute Cores 4C+8G    (4 x 3593)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|6.95GB (3.00GB free)|
|Process Argv|--crash-reporter-id 731cd3a8-93b5-4a52-b0bf-44451ff9b569|
|Screen Reader|no|
|VM|0%|

Connection to 'dev-container+7b22686f737450617468223a222f686f6d652f6773692f667265642f6c61626f7261746f72696f2f6964652f6f70656e7673636f64652f7673636f64652d72656d6f74652d7472792d6e6f6465222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22686f7374223a227373683a2f2f63642d6170706a642d3032227d7d' could not be established
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-pull-request-github|Git|0.40.0
gitlab-workflow|Git|3.42.1
cloudcode|goo|1.17.2
vscode-docker|ms-|1.22.0
vscode-aks-tools|ms-|0.0.16
vscode-kubernetes-tools|ms-|1.3.7
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.10.1
java|red|1.5.0
vscode-yaml|red|1.6.0
snyk-vulnerability-scanner|sny|1.2.14
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by chrmarti** [comment]
Could you append the full log?
