### ISSUE TITLE
SecretState class to have a verbose catch mechanism

### ISSUE THREAD

**Issue by attriaayush** [microsoft/vscode#147760]
Noticed that the retrieval of the token method defined [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/browser/mainThreadSecretState.ts#L48) within the `api/browser/mainThreadSecretState.ts` throws a very generic error,

 ```javascript
    throw new Error('Cannot get password');
```

We can see that some of our users are seeing this error using our plugin that uses `SecretStorage` to manage tokens. But without any further details other than `Cannot get password`, it is hard for us to recreate or pin point why exactly this error is thrown. For now we have wrapped this within a `try/catch` block and if there is an error the token is cleared from the `SecretStorage` but would still love to understand if there is a way we can prevent this error.

Would it be possible to implement a bit more verbose catch mechanism that pin points what actually goes wrong during the token retrieval for this error to be thrown?

**Comment by TylerLeonhardt** [comment]
I can't really change this error if an extension is already depending on it, unfortunately. If that throws, you should assume that secret is gone and you should ask/store the secret again. To be somewhat more informative, I did add a log statement that actually logs the error: c22cb87311b5eb1a3bf5600d18733f7485355dc0
