### ISSUE TITLE
Open Editors icon sometimes doesn't update when language is changed

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#147733]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.0-insider (Universal)
Commit: e7c6ad74aff28965d0189ca1dd584f5e9829cf06
Date: 2022-04-19T05:18:48.693Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

Steps to Reproduce:

1. create the following folder with 2 files:

* `random` (no extension)
```js
foobar: ['foobar','']
// a comment
```
* `another` (no extension) empty file
```
```

2. Open the workspace
3. click on `random` (notice auto-detect turns it into JS, looks right)
4. click on `another` (Plain text, looks right)
5. click on `random` again

Notice auto-detect works and changes it to default but `Open Editors` in the Explorer doesn't update the icon:
![image](https://user-images.githubusercontent.com/2644648/164117029-2c7bbce7-d646-45c5-b176-8c1f523fa124.png)

(I think this is you, @bpasero?)

**Comment by bpasero** [comment]
@JacksonKearl can you check if this is an issue with open editors or further down?
