### ISSUE TITLE
Provide editor.renderWhitespace "selection" option

### ISSUE THREAD

**Issue by OlsonDev** [microsoft/vscode#1477]
Sublime Text has the option:

```
    // Set to "none" to turn off drawing white space, "selection" to draw only the
    // white space within the selection, and "all" to draw all white space
    "draw_white_space": "selection",
```

I would like to see `selection` added to list of possible values for `editor.renderWhitespace`. I find it incredibly useful.

While writing code, I prefer to not show whitespace. However, when I copy-paste code snippets, I like to know the whitespace matches the target document by simply selecting it (usually via `Ctrl+A`), not using the arrow keys or toggling a setting.

Thanks

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by elad** [comment]
I feel bad commenting "+1" on this issue, especially after the open letter to GitHub, but there's no other way of letting you know how important this is to me without doing so. So +1. :)

**Comment by samal84** [comment]
50 thumb ups atm, multiple duplicates, but no no movement on this for a year? Seems like a low hanging fruit, ripe for the picking, to me. Anybody?

**Comment by RomainLanz** [comment]
Hopefully this will be added in the next release!

**Comment by Swift-R** [comment]
Taking a while... :(

**Comment by calebmosher** [comment]
This seems to be the main issue that is being tracked for this. Any update on when we can expect to see this feature in a future release?

**Comment by CoolGoose** [comment]
It would be great to have this, since it's valuable to know whitespace status in various cases including linting.

**Comment by liuliangsir** [comment]
+1

**Comment by spywhere** [comment]
While we wait, I have create an extension explicitly for this issue. Please [take a look](https://marketplace.visualstudio.com/items?itemName=spywhere.whiteviz).

**Comment by chmln** [comment]
>Shameless plug

For those who want sublime's tab+space rendering 
![](https://github.com/chmln/betterWhiteSpace/raw/master/assets/tabSpaceRender.png)

see https://marketplace.visualstudio.com/items?itemName=chmln.better-whitespace

**Comment by spywhere** [comment]
@chmln I don't want to inform about this for the sake of installation numbers on my extension but I believe you just derived my work there. Although I didn't specified any license in my repository. GitHub's default license for unlicensed repository is as followed...

![screen shot 2560-04-24 at 08 36 07](https://cloud.githubusercontent.com/assets/1087399/25319519/3e1008ce-28c9-11e7-9934-960517436c5a.png)
(ref: [Licensing a repository](https://help.github.com/articles/licensing-a-repository/))

If you believe that it's totally all your hard work, could you prove it that it's yours?

If you just want to do a variant implementation, you could just PR on my extension as your extension do most things the same way as mine do.

**Comment by chmln** [comment]
@spywhere I wouldn't like to derail this thread now and spam inboxes of all those who are subscribed here. Let's talk about it [elsewhere](https://github.com/spywhere/vscode-whiteviz/pull/1)

**Comment by alexandrudima** [comment]
I just wanted to share a quick dirty hack:

```
	"editor.renderWhitespace": "all",
	"workbench.colorCustomizations": {
		"editorWhitespace.foreground": "#ffffffff" // <-- use here the theme's background color
	}
```

It isn't really the same, but not super bad either:
![1477](https://cloud.githubusercontent.com/assets/5047891/26679331/df52c93c-46d4-11e7-9259-3595a971bdb4.gif)

**Comment by Stuk** [comment]
In addition to the above, I had to set `editorIndentGuide.background` so that my indent guides didn't disappear too (with Oceanic theme):

```js
    "workbench.colorCustomizations": {
        "editorWhitespace.foreground": "#1B2B34", // theme background
        "editorIndentGuide.background": "#65737E" // indent guide color
    }
```

**Comment by volosovich** [comment]
Hello,
Does exist any chance to add this small feature in future releases?
Really small option, but need to use whole extention for that.
A lot of thanks to @chmln for it

**Comment by Stibbons** [comment]
+1 That would be so much useful!

**Comment by janniks** [comment]
+1 @elad

**Comment by emkayy** [comment]
It has been moved back several times now ...!
@ramya-rao-a when will it actually be included?

**Comment by tbrebant** [comment]
Yet another +1

**Comment by DarkRoastOtter** [comment]
While the boundary setting is nice, having a proper selection render would be truly ideal, definitely support this too! +1

**Comment by komlenic** [comment]
+1

**Comment by PymZoR** [comment]
+1

**Comment by towry** [comment]
Updates on this feature?

**Comment by rodrigogonegit** [comment]
Any news?

**Comment by kanlukasz** [comment]
Until this is not fixed, we can use:
https://marketplace.visualstudio.com/items?itemName=spywhere.whiteviz
Anyway, i think VS Code Team should make it in standard

**Comment by gsemet** [comment]
thank @kanlukasz :)

**Comment by Otiel** [comment]
> Until this is not fixed, we can use:
> https://marketplace.visualstudio.com/items?itemName=spywhere.whiteviz

Any advantage compared to using the [tip](https://github.com/Microsoft/vscode/issues/1477#issuecomment-305476169) shared by @alexandrudima?

> ```
> 	"editor.renderWhitespace": "all",
> 	"workbench.colorCustomizations": {
> 		"editorWhitespace.foreground": "#ffffffff" // <-- use here the theme's background color
> 	}
> ```
> 
> ![1477](https://cloud.githubusercontent.com/assets/5047891/26679331/df52c93c-46d4-11e7-9259-3595a971bdb4.gif)

**Comment by kanlukasz** [comment]
> Any advantage compared to using the [tip](https://github.com/Microsoft/vscode/issues/1477#issuecomment-305476169) shared by @alexandrudima?

In this plugin you have some extra options, for example - changing this arrows to a straight lines

**Comment by wlchn** [comment]
+1 Any news?

And thanks @kanlukasz

**Comment by RMacfarlane** [comment]
The setting will be available in tomorrow’s VS Code Insiders, which you can download here if you want to try it out: https://code.visualstudio.com/insiders/. It will be part of our next release in August. Thanks!

**Comment by spywhere** [comment]
Nice job! I'll update the extension to encourage this change accordingly then. 😄
