### ISSUE TITLE
Open folder isn't returning a listing, just spins

### ISSUE THREAD

**Issue by dfberry** [Microsoft/vscode#14773]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.1.0
- Extensions: 

Steps to Reproduce:

1. close existing folder
2. select pages icon on left side
3. choose open folder from expanding left-side menu
4. select into my main repositories directory (nested repos with .git folders inside)
5. select to parent above folder I want to select
6. spinning icon in folder selector never returns
7. I choose the parent, which is the farthest down the dir structure vscode will go and still return dir/folder structure - that works in terms of code working but I really want to be 1 dir farther so my git works inside vscode

On mac os Sierra, 10.12.1.

**Comment by rebornix** [comment]
@dfberry sorry I don't quite understand your problem, do you mind providing a Gif or similar to describe this issue better?

**Comment by aeschli** [comment]
Closing issue due to lack of additional information.
