### ISSUE TITLE
Register or Notify on Extension

### ISSUE THREAD

**Issue by ArieHein** [Microsoft/vscode#14778]
Not sure if this is available through the recommended extenstion.json but would like to have an option to set specific words, that upon opening VS or the Extension pane / choosing from menu will show me all the new extensions that contain my specified words that have been added since last opened or seen.

**Comment by joaomoreno** [comment]
This will likely not happen for VS Code. It's an interesting request for the [Marketplace](https://marketplace.visualstudio.com/?VScode=1) though. Especially, if they open up their API, you could actually implement this yourself.
