### ISSUE TITLE
Page in Windows Store has no content populated due to JS errors

### ISSUE THREAD

**Issue by RichardBronosky** [microsoft/vscode#147710]
Does this issue occur when all extensions are disabled?: N.A.

- VS Code Version: N.A.
- OS Version: N.A.

Steps to Reproduce:

The page returned from searching https://apps.microsoft.com/store/apps for "vscode" or "visual studio code" is https://apps.microsoft.com/store/detail/visual-studio-code/XP9KHM4BK9FZ7Q but it has no content populated due to JS errors that are not present on other pages. ex: https://apps.microsoft.com/store/detail/python-39/9P7QFQMJRFP7

**Comment by sbatten** [comment]
The linked page is not owned by our team. We only provide the contents for this page. Also, I do not see the same issue. The content is populated for me.

**Comment by RichardBronosky** [comment]
The error has in fact gone away. I did try it on Linux and Windows; Firefox, Chrome, and Edge and all were failing.
I wish I had captured more info. I do believe it was caused by some data you were sending them, but I can't tell you what changed. #sigh
