### ISSUE TITLE
bloquage 

### ISSUE THREAD

**Issue by kionou** [microsoft/vscode#147782]
Issue Type: <b>Bug</b>

lorsque je click sur une ligne je n'arrive pas affaire des modification le curseur refuser

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5675R CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.20GB free)|
|Process Argv|--crash-reporter-id 5b46ea25-ab56-43fe-8268-59f7d63e2b1e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
js-quick-console|Aha|0.0.3
vscode-javascript-snippet-pack|aka|0.1.6
npm-intellisense|chr|1.4.1
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
helium-icon-theme|hel|1.0.0
beautify|Hoo|1.5.0
easy-icons|jam|0.3.1
vscode-github|Kni|0.30.7
vscode-language-pack-fr|MS-|1.66.3
vscode-dotnet-runtime|ms-|1.5.0
material-icon-theme|PKi|4.16.0
LiveServer|rit|5.7.5
es6-string-html|Tob|2.12.0
intellicode-api-usage-examples|Vis|0.0.10
vscodeintellicode|Vis|1.2.19
vscodeintellicode-completions|Vis|1.0.10
vscodeintellicode-insiders|Vis|1.1.8
vim|vsc|1.22.2
JavaScriptSnippets|xab|1.8.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

**Comment by sbatten** [comment]
Translation: When I click on a line, I can't make any changes.

@kionou Can you please share a screenshot?

**Comment by kionou** [comment]
I then solved the problem. I had downloaded a keyboard extension called vim and that was preventing me from working.
