### ISSUE TITLE
Powershell debug terminal keeps env modifications between runs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#147709]
See https://github.com/microsoft/vscode/issues/145265#issuecomment-1102440302

**Comment by rioj7** [comment]
@roblourens 

Please don't implement a separate shell for the launch configs in Powershell.

No Powershell user that uses environment variables in the launch config has problems with the current way it is implemented for Powershell terminals. There is no issue created by such a user. They probably configure the launch config to set/reset the variables they use in there different configs, or they just use a new terminal when they switch applications, but that new application also configures (set/reset) all the environment variables it uses.

So no need to create a sub-shell to execute the command.

So don't introduce a possible trap and confused users complaining it does not work anymore when using some special characters in the arguments or environment variables.

**Comment by roblourens** [comment]
I don't know if that's a safe assumption- it seems like it would be dangerous and confusing that one debug session might pollute the environment of another. But realistically I probably can't take the time to fix this unless users are complaining.
