### ISSUE TITLE
Provide easy way to delete launch configurations in VS Code like from context menu

### ISSUE THREAD

**Issue by fbs2016** [microsoft/vscode#147766]
We can Add Configuration from the Run/Debug item list and and open launch.json to edit it. 
Can we provide an easier way to remove the Run/Debug configuration item.
We can see a long list if there are many Run/Debug item, but if we want to clear some one, we have to:

-  Check which workspace folder it exist
-  Open file launch.json
-  Search name the configuration 
-  Delete the configuration in {}
-  Save launch.json

It's not friendly to users. Could  we provide an easy way to delete them like the context menu or other? Thanks.

![launch configuration](https://user-images.githubusercontent.com/24663582/164240836-94ab9ea1-13ac-49ed-a0ec-0c865d2b2a09.png)

**Comment by weinand** [comment]
I think we should not provide an "easy delete" for launch.json entries because we are not doing this anywhere else in VS Code. But we could make it easier to locate the correct launch.json and select the specific config inside.

**Comment by roblourens** [comment]
We seem to already do this - the gear icon opens the correct launch.json and navigates to the selected config. I was thinking it should work that way and it already does 😁 

I agree that we shouldn't add a delete button, using the gear is the right thing to do.

**Comment by fbs2016** [comment]
Yes the gear icon can open launch.json file and navigates to the selected config, it need us to delete the configure in {} and save the file. This way is not friendly for multiple configurations in multiple workspace folders/launch.json.
