### ISSUE TITLE
Semantic Tokens Overlapping Support

### ISSUE THREAD

**Issue by mhatzl** [microsoft/vscode#147774]
I am currently working on a LSP implementation for a markdown like language and I want to use
semantic tokens to highlight the original text in the editor.

At the moment (<= 1.66.2), vscode does not support overlapping tokens.
This makes semantic tokens nearly impossible to use for languages like markdown, because there are many overlapping tokens.

e.g.

```
**bold *inner italic* outer bold**
```

Using TextMate and regex is also not really an option, because it takes much more effort to write a compiler/LSP + regex statements. Keeping them in sync is also difficult and for some more complex scenarios, regex cannot handle the tokenization correctly.

Is it planned to support overlapping tokens at some point? I have not found any open issues about this topic.
Thanks!

**Comment by alexdima** [comment]
We don't have any plans to support overlapping semantic tokens, simply because the implementation cost of storing, updating and reading the tokens is not worth it. One simple solution would be for you to flatten them out on your side before returning them. e.g.:
```
|---------------tokenA--------------|
           |---tokenB---|
|---tokenA-|---tokenAB--|---tokenA--|
```

**Comment by mhatzl** [comment]
Thanks for your response.

I will try to flatten them as you mentioned and use modifiers too.
