### ISSUE TITLE
`hideFromUser` terminals shouldn't try to use shell integration

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#147717]
reported by @roblourens

**Comment by rchiodo** [comment]
@meganrogge do you have any verifications steps? I'm not sure how to create a hidden terminal or tell that it was using the integrated terminal.

**Comment by meganrogge** [comment]
@roblourens could you pls verify this?

**Comment by meganrogge** [comment]
to verify:

- create an extension terminal with `hideFromUser: true`
- enable shell integration
- create one of your extension terminals
- verify that shell integration is not enabled in it
