### ISSUE TITLE
Opening a small file takes multiple seconds

### ISSUE THREAD

**Issue by ewerybody** [microsoft/vscode#147840]
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

### Steps to Reproduce:

1. Open a small or even empty file
2. wait 3 seconds
3. have the file opened

### Expected:

1. Open a small or even empty file
2. have the file opened

### Example Videos

Ok. Actually testet it back to version `1.63.0` where files opened up immediately!
Each time with no extensions enabled, blank, New Window:
From version `1.64.0` I see it taking around 1.6 seconds, same with `1.65.0` and `1.66.2` takes **2.6 seconds!** See: 

https://user-images.githubusercontent.com/218956/164450031-e8b987a4-6458-4919-ad69-ab60183f4268.mp4

https://user-images.githubusercontent.com/218956/164450089-fa5751bc-a9dc-4436-8f58-cc14a05fddc6.mp4

https://user-images.githubusercontent.com/218956/164450149-d86a3e76-ae50-4d27-a8cb-de42511e57c4.mp4

https://user-images.githubusercontent.com/218956/164450159-2e20a891-6369-4e99-bc21-31d37a95f89e.mp4

### Questions
I know this is not a "biggie" but for me it surely takes away from my feeling of VS Code being my tiny lightweight code editor.
Am I missing something here? Is there some checksum testing in the background? Can that be disabled?

**Comment by bpasero** [comment]
Are you running as admin?

**Comment by ewerybody** [comment]
Nope. My user is Admin on the machine but I didn't do **Run as Admin** or something. Just the zips, unpacked, started ...

**Comment by bpasero** [comment]
> The difference is system setup.

You mean you used the system installer of VSCode and not the user installer? Maybe that still makes a difference though that VSCode thinks you are a user with admin rights. 

And to clarify, this only reproduces via drag and drop, not when you open a file from the explorer inside VSCode?

**Comment by ewerybody** [comment]
> And to clarify, this only reproduces via drag and drop, not when you open a file from the explorer inside VSCode?

No No! This is **any** method. I tried: <kbd>Ctrl+P</kbd>, <kbd>Ctrl+O</kbd>, Recent Files menu ...
Drag and drop was just most convenient for the setup with recording the different version videos.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by ewerybody** [comment]
> You mean you used the system installer of VSCode and not the user installer? Maybe that still makes a difference though that VSCode thinks you are a user with admin rights.

Yeah I have it on one machine installed in user space. It has the delays.
And another where things are in `C:\Program Files\Microsoft VS Code\Code.exe` the delays are barely noticible. But things are also faster here with the zips from https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions 

Can I somehow try to make it run with "factory settings" without throwing away my settings?

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by ewerybody** [comment]
Ok. Please Pardon the delay!

It MUST have something to do with my `user-data-dir`!!

As soon as I bend it away its quick again. But `--disable-extensions` on/off doesn't change a thing.

**Comment by bpasero** [comment]
Ok weird, you could enable settings sync to sync everything over from the one dir to the other and then use that one going forward.

**Comment by ewerybody** [comment]
OK I just renamed my user-data-dir. And synced it back from remote. Seems to work 👍👍
To recap:

* It is **not** something with extensions.
* It happens from version `1.64.0`
* Its "fixed" when `user-data-dir` is emptied/removed or pointed to a different location

Somewhat saddening conclusion. I was coming from Eclipse to VS Code because of this kind of voodoo stuff.
But alright. It works and apparently I'm not missing much from the old user data.
Thank you @bpasero 🙏😊
