### ISSUE TITLE
Full Screen Exit Too Hard to Find

### ISSUE THREAD

**Issue by markhdavid** [microsoft/vscode#147867]
Issue Type: <b>Feature Request</b>

I think it's too hard to find the Full Screen toggle. It should be at top level under View, not a submenu of Appearance, at least once you're in Full Screen mode. 

I had to google it. Then I noticed it's on a page for Accessibility (https://code.visualstudio.com/docs/editor/accessibility - which is weird also, like it's for people with disabilities?) 

That's my suggestion. Thank you for listening.

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

**Comment by weinand** [comment]
there are two ways to find VS Code's commands:
- the macOS way: type "full" in the search field under "Help"
- the VS Code way: "F1" and type "full"
