### ISSUE TITLE
CODE.EXE is a blocked application my LANDesk security

### ISSUE THREAD

**Issue by DAD713** [Microsoft/vscode#14780]
After investigation of why code.exe is blocked on my system.  Come to find out the code.exe is a known adult web site autodialer

Please consider changing the name of the executable, maybe VSCODE.EXE

**Comment by seanmcbreen** [comment]
Hi,

Thanks for reporting this - we are not familiar with LANDesk.

Unfortunately changing our core executable name would be very disruptive for our existing installed base on multiple dimensions and there is no guarantee that any new name would not create additional issues.  This is the first such report we have had.  But I'm sure not the last.  

As a result the best thing to do in this case it to report to LANDesk that they have a false positive in there system for VS Code.  This will be best done by you as they will need additional context to isolate the issue.  Sorry for the inconvenience here.

Closing this issue for now as we can't directly do anything without disrupting the entire user base.
Sean
