### ISSUE TITLE
settings.json based on SSH host 

### ISSUE THREAD

**Issue by yuis-ice** [microsoft/vscode#147860]
In vscode settings.json, a setting similar to this is possible: 

```json
"[python]":  {
    "editor.wordBasedSuggestions": false
},
```

This applies only to python files. 

Let's say I have the following settings.json, 

```json
"remote.SSH.remotePlatform": {
        "ubuntupc": "linux",
    },
```

and I want to apply some settings to the remote.SSH.remotePlatform > ubuntupc scope. 

So, something similar to the below would be desired: 

```json 
"[remotePlatform]": {
  "[ubuntupc]":  {
      "editor.wordBasedSuggestions": false
  },
}
```

So, for example, I can apply custom css configs (e.g. change the header color based on the host).

**Comment by rzhao271** [comment]
When you connect to a remote, are you able to run the `workbench.action.openRemoteSettingsFile` command?
I've attached a screenshot where I opened the command palette in a remote container and searched up the command.

![A command palette showing two Open Remote Settings commands, one for the Settings UI and the other for the settings JSON file](https://user-images.githubusercontent.com/7199958/164533439-ae4dc376-d93d-4874-9df3-9e3b95e3df67.PNG)

**Comment by yuis-ice** [comment]
great! that's what I wanted, the issue has solved for me. by the way the remote config files path is `/home/user/.vscode-server/data/Machine/settings.json`. it's all the same path between remote hosts. Where the each data is being located may I know? Thanks.

**Comment by rzhao271** [comment]
That file is located on the machine that you connected to.
