### ISSUE TITLE
SSH starts too many processes on remote server

### ISSUE THREAD

**Issue by sterroso** [microsoft/vscode#147805]
Issue Type: <b>Performance Issue</b>

I've just requested my hosting provider authorization to open SSH connections between my client (vs code) and my remote web server (CentOS Linux / Jailshell)

Whenever I try to open a ssh connection, my remote shell crashes.

When I pointed this to my hosting provider, his support people told me that there were too many processes started by me from the client side and sent me the list. 23 of those were instances of .vscode-server/bin/.../node and 2 were instances of .vscode-server/bin/.../bin/code.

Is there a way to limit the number of processes launched by vscode remote server?

My provider limits to 26 max simultaneous processes per user for ssh connections.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Connection to 'SSH: hostgator2222' could not be established  WebSocket close with status code 1006

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3450U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.89GB (0.53GB free)|
|Process Argv|--crash-reporter-id 739b76bb-82bc-46e8-9353-10c8dc09cedc|
|Screen Reader|no|
|VM|0%|

Connection to 'SSH: hostgator2222' could not be established  WebSocket close with status code 1006
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    98	 21196	code main
    0	   106	  2628	   extensionHost
    0	   114	  3400	   gpu-process
    0	   117	  3520	   window (Visual Studio Code)
    1	    91	  7052	   issue-reporter
    0	    96	  7560	   shared-process
    0	    72	 10596	     fileWatcher
    0	    73	 16132	     fileWatcher
    0	    72	 18120	     ptyHost
    0	     7	 11972	       console-window-host (Windows internal process)
    0	     4	 19224	       C:\WINDOWS\System32\cmd.exe /c (type "C:\Users\sergi\AppData\Local\Temp\vscode-linux-multi-line-command-hostgator2222-174861449.sh" | ssh -T -D 56664 hostgator2222 bash) & exit /b 0
    0	     9	 16896	         ssh  -T -D 56664 hostgator2222 bash
    0	   170	 17172	   window (Visual Studio Code)
    0	    91	 18212	   extensionHost
    0	   111	 19360	   window (undefined)
    0	    26	 20440	   crashpad-handler
    0	    39	 21212	   utility-network-service
Connection to 'SSH: hostgator2222' could not be established  WebSocket close with status code 1006
```

</details>
<details>
<summary>Workspace Info</summary>

```

Connection to 'SSH: hostgator2222' could not be established  WebSocket close with status code 1006;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by roblourens** [comment]
No, if you have resource limits like this, then Remote-SSH is probably not the right solution.

23 sounds like a lot but it depends on which extensions you have activated, and there is a new set per remote window.
