### ISSUE TITLE
White window border every time vscode starts

### ISSUE THREAD

**Issue by 0eme** [microsoft/vscode#147864]
Issue Type: __Bug__

 Whenever I start vscode, be it _User Installer_, _System Installer_ or _Insider_, a win7 border shows and after a seconds the program starts normally. I reinstalled it many times, and always shows me the win7 border.
![vscodei](https://user-images.githubusercontent.com/93450421/164513344-ef46c741-a650-406f-ab0b-4a0642113539.png)

- When I installed previous versions like 1.63.0 the problem disappears. It only happens with new versions of vscode, I hope you can fix it.

VS Code version: Code 1.66.2, Code_insider 1.67.0
OS version: Windows 10 Pro x64
Restricted Mode: No

**Comment by nonyoo** [comment]
Closes #147864
