### ISSUE TITLE
CPU high usage when opening notebook with multi cell folded.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#147846]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. create notebook with multiple cell folded. in each cell is another foldable cells.
2. try reopen it. cpu usage will be high while it's open.

![image](https://user-images.githubusercontent.com/26390254/164468470-6dad0748-c5e8-445d-b51a-f93b3e688c3b.png)

**Comment by rebornix** [comment]
I tried to open a notebook with and without folding, the CPU will go high for a few seconds in both cases and then go down. Is this what you are also seeing or the CPU stays high with folding?

**Comment by byehack** [comment]
> I tried to open a notebook with and without folding, the CPU will go high for a few seconds in both cases and then go down. Is this what you are also seeing or the CPU stays high with folding?

is stays high.
![image](https://user-images.githubusercontent.com/26390254/164778464-e6f9f5ef-3773-4fc3-882f-07e3f7b1cf53.png)

test notebook:
[FoldBug.zip](https://github.com/microsoft/vscode/files/8543421/FoldBug.zip)

**Comment by byehack** [comment]
close in favor of https://github.com/microsoft/vscode-jupyter/issues/9910
