### ISSUE TITLE
Bug: "Cannot read properties of undefined (reading 'logger')" when using Python run/debug through SSH

### ISSUE THREAD

**Issue by csital** [microsoft/vscode#147828]
Does this issue occur when all extensions are disabled?: No

No, because Python Run / Debug cannot be used if the Python extension is disabled. Issue still occurs when all other extensions, except for Python, are disabled. 

- VS Code Version: 1.66.2
- OS Version: Windows_NT x64 10.0.19044
- Python extension Version: 2022.4.1

Steps to Reproduce:

1. Run or debug any .py file in VSCode through SSH (Workspace Folder is located on an SSH machine). Issue does not occur when using Run or debug on a .py file located on the local machine.

![image](https://user-images.githubusercontent.com/47785770/164413480-ddce2086-e793-4c44-8cf8-d6163391e181.png)

I have been using the same VSCode + SSH setup for months now without problems, but now I keep getting this error since yesterday.

**Comment by bpasero** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/147929
