### ISSUE TITLE
Keyboard Shortcut - Select and Restart Debugging

### ISSUE THREAD

**Issue by cppshane** [microsoft/vscode#147898]
There doesn't seem to be a keyboard shortcut for changing the target launch config, however I found there is an option for `Debug: Select and Start Debugging`, which is good enough.

However, I'd also like to have the option to select a launch config and _restart_ debugging. Currently, if I use the shortcut above for a launch config that is already running, it just gives me a warning "X is already running. Do you want to start another instance?"

This would be very useful, I'm getting carpal tunnel from having to constantly change launch targets.

**Comment by weinand** [comment]
"Restart" only makes sense on a running debug session.
So parameters for "Restart" are not the available launch configs but only the running debug sessions, right?

**Comment by cppshane** [comment]
Yeah that makes sense, though I think the ideal solution would be to just allow keyboard shortcuts for switching launch targets. Since I can use keyboard commands to start/stop/restart the selected launch target, keyboard shortcuts for switching the launch target would solve my issue.
