### ISSUE TITLE
Cant update VS code on windows 10

### ISSUE THREAD

**Issue by mredodos** [microsoft/vscode#147820]
when i try to update vs code the update process cant finish because you do not have permissions to remove the file code.exe. 

if i restart the computer the problem is solved but in the next update same problem all time. 

how to fix this ?

there are many reports both here and on other sites of this problem but it has never been resolved or fixed. there are no answers or solutions.

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code? Let me know if it keeps happening after you do that.

**Comment by joaomoreno** [comment]
Can you try using the System Setup?
