### ISSUE TITLE
Failure in: Upload configuration (for Bing settings search)

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#147819]
Maybe an issue from the build refactorings.

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=167560&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb

```
Upload configuration (for Bing settings search)

[View raw log](https://monacotools.visualstudio.com/DefaultCollection/a6d41577-0fa3-498e-af22-257312ff0545/_apis/build/builds/167560/logs/364)

Starting: Upload configuration (for Bing settings search)
==============================================================================
Task         : Command line
Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
Version      : 2.201.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/4ccfeea4-dddc-474a-ae18-baa956983834.sh
Error: export-default-configuration process timed out
    at Timeout._onTimeout (/Users/runner/work/1/s/build/azure-pipelines/upload-configuration.js:54:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
##[error]Bash exited with code '1'.
Finishing: Upload configuration (for Bing settings search)
```

**Comment by joaomoreno** [comment]
> Maybe an issue from the build refactorings.

This green build ran after the refactorings, so that can't be the cause: https://monacotools.visualstudio.com/Monaco/_build/results?buildId=167146&view=results

**Comment by bpasero** [comment]
Could still be a race condition.

**Comment by joaomoreno** [comment]
Could also be the same root cause as https://github.com/microsoft/vscode/issues/147749

**Comment by bpasero** [comment]
Unlikely, this works fine for me: `code-insiders --export-default-configuration=/Users/bpasero/Desktop/out.log`

The smoke test issue was:
* a single test triggering "File > Clear Recently Opened"
* a new confirmation dialog that appears asking whether to proceed

I doubt that exporting the config would "Clear Recently Opened"

**Comment by roblourens** [comment]
It has randomly timed out like 1 in 1e5 builds. I'll keep an eye on it

**Comment by bpasero** [comment]
Yeah agreed. Doesn't fail today, lets just close.
