### ISSUE TITLE
https://github.com/microsoft/vscode-file-downloader appears abandoned

### ISSUE THREAD

**Issue by pcj** [microsoft/vscode#147807]
Numerous documentation recommends using https://github.com/microsoft/vscode-file-downloader in conjunction with https://github.com/microsoft/vscode-file-downloader-api for extension authors that need the capability to download binary artifacts.

This extension unfortunately does not seem to have an active maintainer.  Specifically, this extension is affected by https://github.com/nodejs/node/issues/40191 and needs a fix.  There is an open PR https://github.com/microsoft/vscode-file-downloader/pull/32 that needs attention from someone with rights on this repository.

Anyhow, it leads to a degraded experience for vscode extensions that depend on this one, I don't have the stats of how many.

Sorry to raise it here, hoping someone from the vscode team will see it and can triage the right person.

Thanks in advance!

**Comment by isidorn** [comment]
@pcj thanks for raising this issue. Can you share some of that numerous documentation that recommends this extension?

On the VS Code side we can mark that extension as deprecated.

**Comment by prb28** [comment]
@isidorn , thanks for this info.
What is the preferred way to download files from an extension?
Is there some example somewhere?
Can the code in this extension be used as a starting point to integrate it in an extension?

**Comment by isidorn** [comment]
@prb28 I suggest to join the extension author community here and ask those questions 
https://vscode-dev-community.slack.com

**Comment by prb28** [comment]
> @prb28 I suggest to join the extension author community here and ask those questions 
> 
> https://vscode-dev-community.slack.com

Thanks

**Comment by pcj** [comment]
@isidorn I'll look around to find examples of the recommendation I mentioned.  However, the existence of  <https://github.com/microsoft/vscode-file-downloader> having 321K installs and https://github.com/microsoft/vscode-file-downloader-api gives it an appearance of solidity.

Looks like @daniv-msft merged that PR (thanks!) so hopefully we're all good for now.  

I'll go ahead and close this, thanks for your attention!
