### ISSUE TITLE
VS Code does not recognize that there is a later version of the extansion Calva

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#147801]
Issue Type: <b>Bug</b>

1. Have Calva v2.0.268 installed
2. Check for Extension Updates

**Expected**: Calva v2.0.269 will be found

**Actual**: It is not found. Instead: ”All extensions are up-to-date”

What complicates the reproduction is that if you don't have Calva installed, then VS Code picks up the latest version. I don't know how to solve that. In my Case my regular VS Code install has latest Calva because I uninstalled it, reloaded the window and then installed it again. But in Insiders I can still reproduce the issue.

VS Code version: Code - Insiders 1.67.0-insider (e7c6ad74aff28965d0189ca1dd584f5e9829cf06, 2022-04-19T05:18:48.693Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id bb70326f-fa59-483f-b56d-effcec0a22c0|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
calva|bet|2.0.268
emojisense|bie|0.9.0
better-toml|bun|0.3.2
gitlens|eam|12.0.6
vscode-pull-request-github|Git|0.40.0
vscode-mocha-test-adapter|hbe|2.13.3
vscode-test-explorer|hbe|2.21.1
chat|kar|0.35.0
restructuredtext|lex|185.0.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.22.0
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.9.2
ruby|reb|0.28.1
vscode-yaml|red|1.6.0
code-settings-sync|Sha|3.4.3
vscode-scss-formatter|sib|2.4.2
code-spell-checker|str|2.1.11
shellcheck|tim|0.19.2
org-mode|too|0.5.0
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebugcf:30475217
pynewfile477:30451556

```

</details>

**Comment by bpringe** [comment]
I also experienced this with this extension, just FYI (and notified @PEZ).

**Comment by isidorn** [comment]
@PEZ thanks for filling this issue.
I assume you are referring to this extension https://marketplace.visualstudio.com/items?itemName=betterthantomorrow.calva
I can reproduce this problem.

Marketplace was having some downtime yesterday, so it might be that at the time you updated your extension Marketplace mishandled this. Can you try to publish another update so we check if that one also can not be found?

fyi @prashantvc @saikanth007

**Comment by isidorn** [comment]
Marketplace team just confirmed this is an issue on their side. They are investigating and will let us know more soon.

**Comment by gjsjohnmurray** [comment]
@isidorn are you able to escalate this with the Marketplace team? I am getting no response from them about progress (see https://github.com/microsoft/vsmarketplace/issues/384#issuecomment-1106026480)

**Comment by gjsjohnmurray** [comment]
> @isidorn are you able to escalate this with the Marketplace team? I am getting no response from them about progress (see [microsoft/vsmarketplace#384 (comment)](https://github.com/microsoft/vsmarketplace/issues/384#issuecomment-1106026480))

Forget that - I just re-checked the status of our extensions and the new versions are now appearing in the Extensions view for VS Code users.

**Comment by isidorn** [comment]
@gjsjohnmurray sorry about that.
@prashantvc can you please comment so community is aware of the status here.

**Comment by isidorn** [comment]
I can no longer reproduce this, it seems like the Marketplace issue has been fixed.
For now closing this issue, if anybody else is still seeing this issue please let me know and I can reopen.

@prashantvc is it expected that this got fixed? Can you provide a bit more details?
