### ISSUE TITLE
when I run childProcess.exec in my extension got some error

### ISSUE THREAD

**Issue by KingJch** [microsoft/vscode#147861]
my extension
```javascript
function activate(context: vscode.ExtensionContext) {

let disposable = vscode.commands.registerCommand('webview-demo-one.helloWorld', () => {
		vscode.window.showInformationMessage('Hello World from webview_demo_one!');

    const child = childProcess.exec(
      `yarn -v`,
      { env: { ...process.env } },
      err => {
        if (err) {
          console.error(err);
        }
      },
    );
    child.stdout.on('data', data => {
      console.info(data);
    });
    child.stderr.on('data', data => {
      console.info(data);
    });
    child.on('close', code => {
      console.log(code);
    });
	});
	context.subscriptions.push(disposable);
}
```
i got that error
![image](https://user-images.githubusercontent.com/14137329/164500204-10fa0519-fa92-4e8b-aa04-8ceb2db31334.png)

**but i run` yarn -v` in vscode integrated terminal it work**

**Comment by AkatQuas** [comment]
Same issue here. (But I don't have any idea to sort it out.)

You might check the "process.env.PATH" value.

![Group](https://user-images.githubusercontent.com/24731539/165213784-52525a88-4375-4eb1-b443-fd408a24068a.png)

**Comment by mjbvz** [comment]
Have you tried running similar code in node directly?

**Comment by alexdima** [comment]
@KingJch @AkatQuas I have tried running both your samples from a VS Code extension and both of them execute fine for me.
