### ISSUE TITLE
"Cmd + click to follow link" tooltip overrides truncation expansion tooltip

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode#147882]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.0-insider
Commit: bd95a8d4516d590256eefecfce465a2f10e8f5e5
Date: 2022-04-21T05:16:16.439Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

Steps to Reproduce:

I’m sure there’s an easier way to repro this, but this is the one I’m hitting right now:

1. Debug a JS file with a local variable whose value is an absolute path to a text file that exists on your system. See that variable in the "variables" tree of the debug panel, and make the panel narrow enough that the value is truncated with an ellipsis.
2. Hover the value.

Expected behavior: system tooltip shows the un-truncated value of the string. (Example image works because this string lacks the `.ts` extension, so it’s not a file existing on disk.)

<img width="507" alt="image" src="https://user-images.githubusercontent.com/3277153/164567726-ba4326ea-3c7d-4994-9371-d2c120f7cb3b.png">

Actual behavior: system tooltip says "Cmd + click to follow link".

<img width="502" alt="image" src="https://user-images.githubusercontent.com/3277153/164567693-e2c20bbc-7e99-434d-b9da-dd748747857c.png">

I think the truncation tooltip should have a higher priority, because the follow-link behavior is indicated from the underline on hover.

**Comment by kingfrost987** [comment]
No

**Comment by weinand** [comment]
This looks like a bug to me: should we really perform link detection in variables values?

**Comment by roblourens** [comment]
I noticed this recently and it surprised me. Came from https://github.com/microsoft/vscode/pull/80502

**Comment by roblourens** [comment]
This was fixed recently
