### ISSUE TITLE
Insiders regression -- code action edits to more than one file triggers an auto-save that isn't preventable

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#147885]
Does this issue occur when all extensions are disabled?: Yes (but I used an unreleased C/C++ extension to generate a multi-file code action edit).

- VS Code Version:Version: 1.67.0-insider (user setup)
Commit: bd95a8d4516d590256eefecfce465a2f10e8f5e5
Date: 2022-04-21T05:16:20.746Z
Electron: 17.4.0
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
Doesn't repro with 1.66.2.
OS: Windows_NT x64 10.0.22000
- OS Version: Windows 11 -- I can repro on multiple machines (including a fresh machine with no settings changes).

Steps to Reproduce:

1. You need some extension that exposes a code action that creates a WorkspaceEdit on multiple files. Our 1.10.1 vsix for the C/C++ extensions has this, but it hasn't been released yet. I could build/send a pre-release vsix via email.
2. Open a folder.
3. Set setting
```
    "C_Cpp.codeAnalysis.clangTidy.checks.enabled": [
        "cppcoreguidelines-init-variables"
    ]
```
or whatever setting is required for the repro.
4. Create a test.cpp file with
```
int main()
{
int i;
return 0;
}
```
or whatever repro file can trigger the code action.
5. Copy the file.
6. Run the C/C++: Run Code Analysis on All Files command or whatever is required to generate the code actions.
7. Select code action "Fix all cppcoreguidelines-init-variables problems" or trigger the code action that does the multi-file edit.

Bug: Every edit triggers VS Code to send a textDocument/didSave instead of keeping the files dirty. It also won't auto-open the files.. The bug doesn't repro if the code action edits just a single file (which makes me believe it's not a "by design" change). The non-Insiders of VS Code doesn't repro this bug. I don't have any auto-save enabled. Doing undo causes the files to open and become dirty (i.e. expected results).

NOTE: The code action type is QuickFix -- see the code at https://github.com/microsoft/vscode-cpptools/blob/seanmcm/codeAnalysisFixCodeAction/Extension/src/LanguageServer/client.ts#L287 ...the code action has a command attached to it too (not sure if that's required for the repro, but I could try removing it if you want, but that command doesn't do anything that should trigger a save).

**Comment by jrieken** [comment]
> he bug doesn't repro if the code action edits just a single file (which makes me believe it's not a "by design" change). The non-Insiders of VS Code doesn't repro this bug. 

This is https://github.com/microsoft/vscode/issues/47573, there is a new setting which is (currently) on by default: `files.refactoring.autoSave`

@sean-mcmanus What makes you thing this is a bug? What "bad" consequences does this have for you?

**Comment by sean-mcmanus** [comment]
@jrieken Yeah, I remembering seeing that setting, but I ignored it because I didn't think it was relevant because my code action is not a "refactor" code action (it's a QuickFix). Is that intentional? Maybe the setting description or naming could be improved?

As long as there's a setting to disable it, that would be okay with me -- I needed it to not auto-save in order to properly test/repro a bug I was investigating with our extension changes, because we trigger additional actions on saving, such as re-running code analysis.

So it's a bug that it doesn't auto-save with a single file?

Another consequence is that the edited files aren't opened, so it's not immediately clear which files were changed (unless source control finds it, but my temporary projects for testing generally aren't under source control), and any IntelliSense squiggles that would appear previously due to buggy code action edits (see https://github.com/microsoft/vscode-cpptools/issues/9221) don't appear (since our extension only show IntelliSense errors for open files).

**Comment by sean-mcmanus** [comment]
To re-emphasize what I just said -- our pending quick fixes have the potential to generate garbage/uncompilable code, such as the previously referenced bug, so the previous behavior is safer for the users of our feature, since the garbage code was immediately detected by our IntelliSense, so it was less likely to be permanently saved to disk. Our extension may decide to override that auto-save default for [c]/[cpp] languages (at least until the edits generated by the feature have been deemed safe enough).

**Comment by sean-mcmanus** [comment]
I get "This setting does not support per-language configuration" when I use

```
    "configurationDefaults": {
      "[cpp]": {
        "files.refactoring.autoSave": false
      },
```.

Is there some way we can tell VS Code that our code action edits are potentially "unsafe" and/or shouldn't be saved immediately by default?

**Comment by sean-mcmanus** [comment]
I do not repro this issue any more, so I'm closing it. Not sure if it was intentionally fixed or not.

A files.codeAction.quickFix.autoSave setting that users can opt-in to would be okay, although in that case it should apply even with code actions that impact just one file.
