### ISSUE TITLE
Bash syntax highlighting bug

### ISSUE THREAD

**Issue by EMLGaming** [microsoft/vscode#147845]
Issue Type: <b>Bug</b>

When you write the following: 

```bash
cat <<EOF
echo $testvar
EOF
```

The ``testvar`` should be highlighted as a variable but right now it is seen as a string, while bash/zsh/fish all interpet it as a variable.

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:55.248Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.12.5517
vscode-bicep|ms-|0.5.6
vscode-docker|ms-|1.22.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.2.1030672458
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
azure-account|ms-|0.10.1
powershell|ms-|2021.12.0
vsliveshare|ms-|1.0.5527

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by alexr00** [comment]
A similar issue was recently fixed in the shell script grammar we use. Can you try installing VS Code insiders and confirming whether the issue persists there?

**Comment by EMLGaming** [comment]
![image](https://user-images.githubusercontent.com/25344246/166438684-841e1d82-62e2-4a1b-a275-d2c89d85beed.png)

@alexr00 it has indeed been fixed in VS Code insiders! Thanks
