### ISSUE TITLE
Workbench navigation does not work inside notebooks. 

### ISSUE THREAD

**Issue by tbenthompson** [microsoft/vscode#147881]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Open a notebook. In my case, I have a Jupyter notebook (.ipynb). 
2. Run any of the "workbench.action.navigateLeft" or "workbench.action.navigateRight" or "workbench.action.navigateUp" or "workbench.action.navigateDown". 
3. Nothing happens! 

These navigation commands work just fine in all other views/panels that I regularly use. 

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (12.27GB free)|
|Process Argv|--disable-extensions --crash-reporter-id b532f079-f941-47c0-ab2f-f74d9a137557|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by bpasero** [comment]
@rebornix this sounds like a real bug to me, the issue is that notebooks do not seem to be rooted below the editor part in the DOM:

![image](https://user-images.githubusercontent.com/900690/164624548-6edc5f89-2143-47f5-b4d5-05495f79f69b.png)

That asks for trouble because we have lots of checks in code to figure out if the editor area has DOM focus or not, e.g.:

https://github.com/microsoft/vscode/blob/ff3d5bb4911dbfd3f3f2851d352132bea32a71e3/src/vs/workbench/browser/layout.ts#L884-L893

What is the rationale? I checked with custom editors, and they manage to put the `iframe` into the DOM hierarchy of the editor part.

**Comment by rebornix** [comment]
We render the notebook out of the grid view as it contains a webview, which can not be re-parented when users drag editors between groups. I basically followed what Custom Editor does 

>  I checked with custom editors, and they manage to put the iframe into the DOM hierarchy of the editor part

@mjbvz did we change this recently? I wonder if it's already safe to do so.

**Comment by BDannowitzHudl** [comment]
Can confirm that I am also experiencing this.

In the meantime, I've found that this kind of works for moving left and right:

```json
    {
        "key": "ctrl+h",
        "command": "workbench.action.focusLeftGroup",
        "when": "notebookEditorFocused"
    },
    {
        "key": "ctrl+l",
        "command": "workbench.action.focusRightGroup",
        "when": "notebookEditorFocused"
    }
```

But there is no `focusUpGroup` or `focusDownGroup`, and this fails when attempting to move to panels.

Looking forward to a fix, or if anyone has a workaround.

**Comment by bpasero** [comment]
@rebornix fyi we no longer use `webview` but only `iframe`, so maybe that changed.

**Comment by rebornix** [comment]
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/876920/166074247-e173c210-c569-47d3-a38b-ecef0dbad954.png">

I found that we are not putting custom editor webviews in the editor grid either. @bpasero

**Comment by bpasero** [comment]
@rebornix oh ok, turns out we seem to have logic to still make that work via a special `flow-to` code, looks like notebooks should adopt it as well:

https://github.com/microsoft/vscode/blob/08ef40bd522d5a1309d7b54fb5ba9066d4cf5983/src/vs/workbench/contrib/webviewPanel/browser/webviewEditor.ts#L160-L163

**Comment by mjbvz** [comment]
Yes to my knowledge iframes still cannot be reparented. All webviews are rendered as top level elements with absolute positioning to work around this

@rebornix Let me know if you have any questions about using `DOM.setParentFlowTo`. I believe it should help fix this issue

**Comment by ajkerrigan** [comment]
> Can confirm that I am also experiencing this.
> 
> In the meantime, I've found that this kind of works for moving left and right:
> 
> ```json
>     {
>         "key": "ctrl+h",
>         "command": "workbench.action.focusLeftGroup",
>         "when": "notebookEditorFocused"
>     },
>     {
>         "key": "ctrl+l",
>         "command": "workbench.action.focusRightGroup",
>         "when": "notebookEditorFocused"
>     }
> ```
> 
> But there is no `focusUpGroup` or `focusDownGroup`, and this fails when attempting to move to panels.
> 
> Looking forward to a fix, or if anyone has a workaround.

This feels like a useful workaround. Concerning moving up and down, you can use the `focusAboveGroup` and `focusBelowGroup` actions ([reference](https://github.com/microsoft/vscode/blob/bb5215fff67fd9f40e247a353cc0e5e84a28f49f/src/vs/workbench/browser/parts/editor/editorActions.ts#L366-L392)).

**Comment by rebornix** [comment]
@mjbvz `DOM.setParentFlowTo ` works great, it would be great if you can help review https://github.com/microsoft/vscode/pull/148730

**Comment by tbenthompson** [comment]
Yep, this seems to be fixed in the insiders build. Looking forward to seeing it merged into stable! Thanks everyone!
