### ISSUE TITLE
Logitech MX Master 3 + Win11, cannot do horizontal scroll

### ISSUE THREAD

**Issue by darkguy2008** [microsoft/vscode#147880]
Issue Type: <b>Bug</b>

1. Have an MX Master 3
2. Try using the horizontal scrollbar

This seems to work for some reason in Linux, but not in Windows. It scrolls like, a single step, and then it doesn't scroll at all.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-39-generic
Remote OS version: Linux x64 5.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (15.84GB free)|
|Process Argv|--crash-reporter-id ae42ad3a-3f2b-4993-8156-fbb72c9abaaa|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: wsl|
|OS|Linux x64 5.13.0-39-generic|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (6 x 2495)|
|Memory (System)|7.75GB (1.70GB free)|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: wsl|
|OS|Linux x64 5.13.0-39-generic|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (6 x 2495)|
|Memory (System)|7.75GB (1.70GB free)|
|VM|50%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
mikrotik-routeros-script|dev|2018.8.2
haskell-nsis|idl|1.0.2
routeros-conf|lau|1.0.0
remote-ssh|ms-|0.78.0
html-preview|ty4|1.4.0
remove-empty-lines|use|0.0.8
vscode-json|and|1.5.0
ng-template|Ang|13.3.1
unique-lines|bib|1.0.0
multi-cursor-case-preserve|Car|1.0.5
mikrotik-routeros-script|dev|2018.8.2
vs-code-xml-format|fab|0.1.5
url-encode|fle|1.1.0
auto-using|Fud|0.7.15
todo-tree|Gru|0.0.215
haskell-nsis|idl|1.0.2
nsis|idl|3.49.0
csharpsortusings|jon|0.0.6
routeros-conf|lau|1.0.0
align-vertically|mat|0.2.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
hexeditor|ms-|1.9.5
increase-by-1|nor|1.1.0
remove-comments|pli|1.2.2
vscode-scss-formatter|sib|2.4.2
shopify-liquid|sis|2.3.0
duplicate-finder|tle|0.0.6
html-preview|ty4|1.4.0
sort-lines|Tyr|1.9.1
remove-empty-lines|use|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by alexdima** [comment]
Let's track in #84136
