### ISSUE TITLE
Explorer doesn't refresh on doing Refresh

### ISSUE THREAD

**Issue by Leon99** [Microsoft/vscode#14782]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: austin.code-gnu-global-0.2.1, chrisdias.vscode-opennewinstance-0.0.3, christian-kohler.path-intellisense-1.1.0, codezombiech.gitignore-0.2.0, Compulim.compulim-vscode-closetag-0.1.2, dbankier.vscode-instant-markdown-0.1.0, donjayamanne.listFiles-0.0.3, donjayamanne.python-0.5.0, DotJoshJohnson.xml-1.6.0, emilast.LogFileHighlighter-1.0.0, espresso3389.vcterminal-0.0.3, formulahendry.code-runner-0.4.1, gep13.chocolatey-vscode-0.2.2, hars.CppSnippets-0.0.5, HookyQR.beautify-0.5.3, jedmao.tabsanity-0.0.8, jrieken.backspace-plusplus-0.0.14, k--kato.docomment-0.0.7, lafe.contextualduplicate-0.2.0, michelemelluso.gitignore-1.0.1, mohsen1.prettify-json-0.0.3, mousetraps.quicksnippet-0.0.1, ms-vscode.cpptools-0.9.2, ms-vscode.csharp-1.4.1, ms-vscode.PowerShell-0.7.2, ms-vscode.Theme-MaterialKit-0.1.1, ms-vsts.team-1.108.0, naumovs.color-highlight-1.2.1, NgekNgok.vscode-custom-snippets-1.1.4, qub.qub-xml-0.3.0, remcoros.startanyshell-0.3.1, robertohuertasm.vscode-icons-3.0.7, rubbersheep.gi-0.2.7, seanmcbreen.Spell-0.8.6, seesharprun.view-in-default-application-2.0.0, Shan.code-settings-sync-2.3.5, SirTori.indenticator-0.2.1, sleistner.vscode-fileutils-2.3.1, streetsidesoftware.code-spell-checker-0.11.4, tomoki1207.vscode-input-sequence-0.1.0, zhuangtongfa.Material-theme-1.0.3, ziyasal.vscode-open-in-github-1.2.2

Steps to Reproduce:

1. Run a PowerShell script that removes files inside the opened folder
2. Run Refresh/press Refresh button in the Explorer

Result: files are still shown in the Explorer while they don't exist any more.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by aeschli** [comment]
Closing due to lack of information. Please reopen with data described above.
