### ISSUE TITLE
Can't login to LiveShare with github

### ISSUE THREAD

**Issue by DoneDeal0** [microsoft/vscode#147853]
Hello,

I've been using Live Share for years without any problems. But since a few weeks, I can't login anymore.

Steps to reproduce:
- In VSCode, I click on "live share" on the blue footer.
- It opens a popup to sign-in with Microsoft or Github
- I click on "Sign in with Github"
- It opens a webpage. I click on "Authorize Visual Studio Live Share".
- It redirects me to a new webpage: "Ready to collaborate!", with a code such as WFRT-PSHR-NTPN-CRND
- I go back in VSCode, open the command palette, select "Live share: sign in with user code".
- I enter the code and press enter. 
- A popup appears at the bottom right of VSCode, to inform me that the sign-in is processing.
- The sign-in runs perpetually. It never works. 
- It also doesn't work with a sign-in with an outlook account.

How to fix this?

- VS Code Version: 1.41.1
- OS Version: OSX 11.4

**Comment by TylerLeonhardt** [comment]
\extLiveShare
