### ISSUE TITLE
Open/Open Folder not Working

### ISSUE THREAD

**Issue by Manty-K** [microsoft/vscode#147822]
Issue Type: <b>Bug</b>

I am working on Mac M1 2020.
Sometimes VS Code does not respond to the open button.
The finder window does not open when clicked.

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 1e313b71-451e-4597-a467-732ddd690936|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
dart-data-class-generator|Ben|0.5.5
bracket-pair-colorizer-2|Coe|0.2.4
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
gitlens|eam|12.0.6
Kotlin|mat|1.7.1
vscode-docker|ms-|1.22.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vsliveshare|ms-|1.0.5527
awesome-flutter-snippets|Nas|3.0.3
material-icon-theme|PKi|4.16.0
remove-comments|pli|1.2.2
vscode-thunder-client|ran|1.16.2
java|red|1.5.0
vscode-yaml|red|1.4.0
vscodeintellicode|Vis|1.2.19
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by JacksonKearl** [comment]
Which button are you referring to here?

**Comment by Manty-K** [comment]
@JacksonKearl 
The Open button in Getting Started Screen.
And Open button in File Tab Dropdown

**Comment by JacksonKearl** [comment]
cc @deepak1556 getting started is running the command `workbench.action.files.openFileFolder`. I see that's essentially just calling electron's `showOpenDialog`, but there's a lock to be acquired first.
