### ISSUE TITLE
Settings Sync Dialog Box Not Loading

### ISSUE THREAD

**Issue by StarAssassin64** [microsoft/vscode#147800]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.66.0
- OS Version: Manjaro Linux (Based off Arch Linux) | Linux x64 5.15.32-1-MANJARO
- Version: 1.66.0

Steps to Reproduce:

1. Try to click on the accounts button
2. It continuously loads, but never finishes

![image](https://user-images.githubusercontent.com/64805947/164334385-10777c46-886b-41f8-a5e8-7acf5fbc43b6.png)

**Comment by lucasraziel** [comment]
I think this is the same error of #148036

**Comment by TylerLeonhardt** [comment]
@StarAssassin64 based on your screenshot, you appear to be using "Code - OSS" from sources and not our built version of VS Code.

"Code - OSS" doesn't include settings sync which usually checks for auth immediately and causes this "Loading..." to not be shown.

Can you please install a different package of VS Code?

**Comment by StarAssassin64** [comment]
> Can you please install a different package of VS Code?

I would, but there is no way for me to install the official version of VSCode on an Arch Linux base (what Manjaro is based off of). If Code - OSS doesn't support setting's sync, then why does it have spots for it. Shouldn't that be only on the Offical VS Code

**Comment by TylerLeonhardt** [comment]
Does this doc help you?:

https://wiki.archlinux.org/title/Visual_Studio_Code

> Visual Studio Code — Microsoft-branded binary release.
> https://code.visualstudio.com/ || visual-studio-code-binAUR, visual-studio-code-insiders-binAUR

**Comment by StarAssassin64** [comment]
Yes it does! Thanks! Tho I do question why we have that dialog box in the first place if it can't do anything as just Code - OSS

**Comment by TylerLeonhardt** [comment]
@StarAssassin64 it actually does something once you have an extension that wants to log in with something. So in Code - OSS, if you install the GitHub Pull Requests extension or GitHub Repositories extension, those will ask you to sign in. Once you sign in, the account will show up in that pain. The problem is that `Loading...` text is maybe not the best placeholder... but since you never have this issue in VS Code (as apposed to Code - OSS) I haven't sat down to think about what it _should_ be.

Maybe "No accounts requested yet..." is clearer.

**Comment by StarAssassin64** [comment]
That would be a lot better

**Comment by aeschli** [comment]
Verified in OSS.
I personally would just have a sigle dot instead of the ellipses.

**Comment by StarAssassin64** [comment]
> I personally would just have a sigle dot instead of the ellipses.

I think that the ellipses add the feeling of waiting. Just seems right for this text

**Comment by aeschli** [comment]
If I understand that right, waiting won't help, nothing is initializing in the background.
Only when the user invokes something that requires an account with authentication, then something happens.

**Comment by StarAssassin64** [comment]
What I mean by waiting is that it is waiting for you to need an account to link with code. Just how it is phrased makes an ellipsis needed 

>"No Account Requested **Yet**..."
