### ISSUE TITLE
Inlay Hints with minimal parameters count

### ISSUE THREAD

**Issue by antfu** [microsoft/vscode#147875]
### Motivation

With `javascript.inlayHints.parameterNames.enabled: 'all'`, we got

```ts
parseInt(/* str: */ '123', /* radix: */ 8)
```

While in many cases, we only use one parameter when calling a function, for example

```ts
parseInt(/* str: */ '123')
```
```ts
console.log(/* message: */ foo)
```
```ts
// Vue's Composition API
const state = ref(/* value: */ 1)
```
```ts
array
  .filter(/* predicate: */ Boolean)
  .map(/* callbackFn: */ i => i.value)
```

In those cases, the contexts are less ambitious and the inlay hints become a bit redundant and even verbose.

### Proposal

Thus I am proposing to introduce a new setting to configure the minimal parameters count required for the inlay hints to enable in each function call.

Imagining

```ts
"javascript.inlayHints.parameterNames.minCount": 2 /* default: 0 */
```

To hide the inlay hints when calling functions with a single argument.

Happy to work on the implementation.

**Comment by antfu** [comment]
It turns out the inlay hints feature is implemented in TypeScript, so I made a mirror issue to it
- https://github.com/microsoft/TypeScript/issues/48817

Implementations (PR pending for feature approval)
- TypeScript: https://github.com/antfu/TypeScript/commit/395477592183cf555ab5cea6b0eaa041ae2a757b
- VS Code: https://github.com/antfu/vscode/commit/c0870e079375ac3630982277d215b2d0a1da24f2

**Comment by mjbvz** [comment]
https://github.com/microsoft/TypeScript/issues/48899 seems like a better approach to me. This is also being discussed upstream on the TypeScript repo however so closing in favor of https://github.com/microsoft/TypeScript/issues/48817
