### ISSUE TITLE
Is it possible to setup live typescript type checking in Vscode virtual workspaces

### ISSUE THREAD

**Issue by laurencefass** [microsoft/vscode#147874]
[](https://stackoverflow.com/posts/71937535/timeline)

I am using Vscode to edit my typescript projects in virtual workspaces which I am connecting to through SSH FS extension.

Whilst benefitting from the convenience of remote access I have had to forego all of the benefits of live typescript checking that Vscode automatically provides for projects in local storage.

Is there a way to combine the best of both worlds and have live typescript checking in virtual projects? I realise this is out of scope of vscode usage and that documentation suggests its not possible (at least not by design), but vscode seems super flexible so I am wondering if anyone has been able to achieve this?

**Comment by IllusionMH** [comment]
Why not to use Remote - SSH for fully functional remote development?
https://code.visualstudio.com/docs/remote/ssh

**Comment by laurencefass** [comment]
Thanks I did not know about that have been using SSH FS extension for years. thanks,

**Comment by laurencefass** [comment]
works great now I just need to significantly increase my server memory to accommodate all of vscodes additional processes and services.
