### ISSUE TITLE
When developing an extension there should be a way to prevent commands from showing up in keybindings

### ISSUE THREAD

**Issue by MrAndersen1** [microsoft/vscode#147838]
For instance if we have an inline menu in a treeview

```
"view/item/context": [
  {
    "command": "myCommand",
    "when": "view == myList && viewItem == aSpecificListItemType",
    "group": "inline@1"
  }
]
``` 

Then it's required to be in the commands array

```
commands: [
  {
    "command": "myCommand",
    "title": "Do something",
    "enablement": "view == myList && viewItem == aSpecificListItemType" // not required but seems to prevent the command from appearing in the command palette
  }
]
```

But this makes it show in keybindings and a keybinding for the command will not work since we don't get the list item provided when pressing the inline button.

The best I can do right now (I think) is to show an information message to the user if they try to invoke it manually, but I would prefer if you couldn't assign a keybinding to it at all.

**Comment by gjsjohnmurray** [comment]
> // not required but seems to prevent the command from appearing in the command palette

FYI, to hide a command from Command Palette, contribute it to the `commandPalette` menu with a `when` clause of `false`, e.g.

```json
"contributes": {
...
  "menus": {
...
    "commandPalette": [
...
      {
        "command": "myCommand",
        "when": "false"
      }
    ]
  }
}
```

**Comment by gjsjohnmurray** [comment]
Previously requested in  #99439, where there is also a tip about prefixing your command name with underscore (which I haven't personally tried).

**Comment by MrAndersen1** [comment]
@gjsjohnmurray Thanks for that :+1:  I had missed the commandPalette menu item.

I'll take a look at thread too, there are some interesting things in there.

Slightly unrelated to this topic it seems all commands provided by an extension has to guard against being run without arguments (e.g. in the case of the intended use being inline) and also against being run when their enablement is false since a user can remove the "when" part in their keybindings?

Anyways, since that thread was closed, and I had missed it, feel free to close this for the same reason if you want.
