### ISSUE TITLE
VSCode opened from Command prompt closes if cmd closed

### ISSUE THREAD

**Issue by AkashGutha** [Microsoft/vscode#14789]
- VSCode Version: 1.6.1
- OS Version: windows 7

Steps to Reproduce:

1. open command prompt in a folder and use command 'code .'
2. after vscode launches close the cmd , it will also close the corresponding vscode window.

I would be great if this wasn't the case.

**Comment by bpasero** [comment]
@AkashGutha That should not be the case unless code points to the actual code.exe in the installation directory.

**Comment by AkashGutha** [comment]
my path is setup to point the VSCode installation folder.

D:\vscode

**Comment by bpasero** [comment]
@AkashGutha make sure to not point to `code.exe` but `code.cmd` inside the `bin` folder:

![image](https://cloud.githubusercontent.com/assets/900690/19881480/5a13dd8a-a006-11e6-97a5-fc808de25d75.png)

**Comment by AkashGutha** [comment]
Yes! that worked. :)
