### ISSUE TITLE
no dedicated documentation about launch.json

### ISSUE THREAD

**Issue by zzzgit** [microsoft/vscode#147832]
`launch.json` is important for us to debug and do other developing things. I found there's no such an article in `VSC`'s documentation focusing on `launch.json`.

Why not add an article focusing on `launch.json` to make us more professional in editing it.

**Comment by weinand** [comment]
You can find the generic documentation about launch.json here: https://code.visualstudio.com/docs/editor/debugging#_launch-configurations

But please note that most properties available in the launch.json are defined by the debugger extensions you are using. So you will have to look for specific documentation on the extensions's documentation in the VS Code Marketplace.
