### ISSUE TITLE
mvc project,each cshtml file tip:The type name "Action" does not exist in the type "System"

### ISSUE THREAD

**Issue by jack-liew** [microsoft/vscode#147886]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.2
- OS Version:windows 11

Steps to Reproduce:

1.Mvc+EFCore,  everytime,open the project, each cshtml file has two error message :
"The type name "Action" does not exist in the type "System"", or "类型“System”中不存在类型名“Action”"
"Type name "Object" does not exist in type "System" ".
But debugging is all right.

when I double click the message to open a [*.cshtml_bg_virtual.cs], the error message will be disappear.

2.I used vscode version 1.66.2, when debug the mvc application, If I set a breakpoint,vscode will Stuck for more than ten seconds.

Thanks

**Comment by sbatten** [comment]
This sounds like it caused by an extension, probably https://github.com/OmniSharp/omnisharp-vscode/issues
