### ISSUE TITLE
Vs code for android!

### ISSUE THREAD

**Issue by Arashvscode** [microsoft/vscode#147868]
Friends who are interested in the real version of Android can help me at this link
https://github.com/Arashvscode/Vs-code-Mobile

And you can also download the Android version from this Telegram channel

https://t.me/vscodeappmobile

**Comment by Arashvscode** [comment]
Lol

**Comment by isidorn** [comment]
No planned action here, thus closing as out of scope.
In the meantime checkout https://vscode.dev/
