### ISSUE TITLE
TERMINAL BUG

### ISSUE THREAD

**Issue by luweiqianyi** [microsoft/vscode#147889]
Issue Type: <b>Bug</b>

Issue Type: <b>Bug</b>

TERMINAL
1. click mouse right button,terminal will show the latest input 
2. my expectation: do nothing

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.89GB free)|
|Process Argv|--crash-reporter-id e0d4071a-02d8-496a-b590-1c4361785849|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ue4-snippets|CAP|2.0.1
texinfo|cis|0.2.4
doxdocgen|csc|1.4.0
graphviz-preview|EFa|1.5.0
vscode-npm-script|eg2|0.3.24
vscode-open-in-github|fab|1.3.0
vscode-npm|fkn|3.3.0
vscode-opencl|gal|0.7.3
vscode-pull-request-github|Git|0.40.0
better-cpp-syntax|jef|1.15.13
vscode-graphviz|joa|0.0.6
python-sphinx-highlight|leo|0.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
kconfig|luv|1.0.3
autoconf|mae|0.1.0
Kotlin|mat|1.7.1
formate|Mik|1.2.1
vscode-html-format|moh|0.0.4
language-gettext|mro|0.2.0
vscode-docker|ms-|1.22.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
vscode-gn|npc|1.1.0
unreal-engine-4-helper|ope|0.3.2
vscode-gnformat|per|0.0.3
java|red|1.5.0
shader|sle|1.1.5
python|tht|0.2.3
simple-rst|tro|1.5.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
cocos-effect|Yaj|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (10.66GB free)|
|Process Argv|--crash-reporter-id e0d4071a-02d8-496a-b590-1c4361785849|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
ue4-snippets|CAP|2.0.1
texinfo|cis|0.2.4
doxdocgen|csc|1.4.0
graphviz-preview|EFa|1.5.0
vscode-npm-script|eg2|0.3.24
vscode-open-in-github|fab|1.3.0
vscode-npm|fkn|3.3.0
vscode-opencl|gal|0.7.3
vscode-pull-request-github|Git|0.40.0
better-cpp-syntax|jef|1.15.13
vscode-graphviz|joa|0.0.6
python-sphinx-highlight|leo|0.1.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
kconfig|luv|1.0.3
autoconf|mae|0.1.0
Kotlin|mat|1.7.1
formate|Mik|1.2.1
vscode-html-format|moh|0.0.4
language-gettext|mro|0.2.0
vscode-docker|ms-|1.22.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
vscode-gn|npc|1.1.0
unreal-engine-4-helper|ope|0.3.2
vscode-gnformat|per|0.0.3
java|red|1.5.0
shader|sle|1.1.5
python|tht|0.2.3
simple-rst|tro|1.5.2
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.22.3
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
cocos-effect|Yaj|0.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/docs/editor/integrated-terminal#_rightclick-behavior
