### ISSUE TITLE
ボタン操作が無効化される

### ISSUE THREAD

**Issue by terurin** [microsoft/vscode#147892]
4K/カスタムスケーリング150%のディスプレイ環境で、ターミナルのボタン(追加や分割・切り替え)がクリックできない。また、通知のポップアップも同様にクリックできない。

暫定的にウィンドウを縮小する・ディスプレイのスケーリングを100%にすることでこの不具合を回避できることを手元の環境で確認している。

**Comment by connor4312** [comment]
>I can't click the terminal buttons (add, split, switch) in a 4K / custom scaling 150% display environment. Also, notification pop-ups cannot be clicked either.
>
>We have confirmed in the environment at hand that this problem can be avoided by temporarily reducing the window and scaling the display to 100%.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label "needs more info" terminal
