### ISSUE TITLE
No start page

### ISSUE THREAD

**Issue by jk404-bit** [microsoft/vscode#147823]
Issue Type: <b>Bug</b>

I just cannot start a new project because the welcome page is just not there. I have read a lot of manuals, and ticked the "Welcome window on the start", it doesn't show. Could you please keep the functionality as simple as possible without beginners like me having to scour the Internet for the right answers to just start a new project, please

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.06GB free)|
|Process Argv|--crash-reporter-id 339c5e97-05ac-40ef-b2f7-2b25fce913af --crash-reporter-id 339c5e97-05ac-40ef-b2f7-2b25fce913af --crash-reporter-id 339c5e97-05ac-40ef-b2f7-2b25fce913af|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
What you refer to as "the welcome page" is this:

![image](https://user-images.githubusercontent.com/6726799/164422848-75a472f9-e812-43ea-a9fb-24f967929177.png)

If you're not seeing it, use the "Get Started" option from the "Help" menu.

**Comment by jk404-bit** [comment]
As it has turned out, it is the wrong product, Visual Studio Code and
Visual Studio are TWO DIFFERENT ones. Perfect naming, thanks a lot. :(

Am Do., 21. Apr. 2022 um 11:19 Uhr schrieb John Murray <
***@***.***>:

**Comment by gjsjohnmurray** [comment]
Please close your issue on GitHub.
