### ISSUE TITLE
Prompted to save webpage when Ctrl+S in vscode.dev when focus is on notebook editor 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#147878]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: Windows 11

Steps to Reproduce:

1. Create a notebook in vscode.dev
2. Click on the notebook editor below the cell list
    ![image](https://user-images.githubusercontent.com/30305945/164555078-a51a8a10-66e7-4b3e-890d-592f5c15e376.png)
4. Ctrl+s
5. :bug: prompted to save webpage
    ![image](https://user-images.githubusercontent.com/30305945/164555142-e8028abc-fa53-4e53-a052-1ad678878550.png)

**Comment by rebornix** [comment]
@joyceerhl thanks!

@mjbvz The focus is in the webview but it seems the save action is not handled properly.
