### ISSUE TITLE
Internal terminal isn't correctly wrapped bash terminal

### ISSUE THREAD

**Issue by CodeGenTeam** [Microsoft/vscode#14787]
I cannot overwrite in settings "terminal.integrated.shell.windows": "%COMSPEC%"
![image](https://cloud.githubusercontent.com/assets/11016041/19879272/cadc1a12-a012-11e6-8387-90099482c450.png)
For `"terminal.external.windowsExec": "%CURRENT_DIR%git-for-windows\\bin\\bash.exe"`
I can

This is not help #7286, but it's dublicate: #7344 (it's not resolve)

But It's work: `"terminal.integrated.shell.windows": "D:\\git-for-windows\\bin\\bash.exe"`
Full path is working!
`SET CURRENT_DIR=%~dp0`

Found solution:
` SET COMSPEC=%CURRENT_DIR%git-for-windows\bin\bash.exe`
and after that run VSCODE

But I cannot run terminal.external.windowsExec

And I have problem with bash, there are extra characters, the console behaves is abnormally. When I run bash outside, all is correct.
![image](https://cloud.githubusercontent.com/assets/11016041/19881447/9330ef7e-a027-11e6-9349-7800f35f472c.png)

**Comment by rebornix** [comment]
@CodeGenTeam sorry are you saying this issue is dup of #7344 ? If so I'd like to close this one and track it there.

**Comment by CodeGenTeam** [comment]
This problem have another issue. bash isn't work correctly in wrapped terminal.

**Comment by Tyriar** [comment]
So environment variables being evaluated in the setting is tracked in #7344. Git bash does have some known issues on Windows in addition to some other shells, general git bash input issues are tracked in #7345.
