### ISSUE TITLE
PseudoTerminal as Terminal Profile broken location

### ISSUE THREAD

**Issue by ShuP1** [microsoft/vscode#147856]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Ubuntu 20.04.4 LTS

Steps to Reproduce:

1. Create an extension providing a terminal profile for external terminal aka `pty`
2. See https://github.com/microsoft/vscode-extension-samples [Extension Terminal sample](https://github.com/Microsoft/vscode-extension-samples/tree/main/extension-terminal-sample) and [Terminal sample](https://github.com/Microsoft/vscode-extension-samples/tree/main/terminal-sample)
3. Create a split terminal with this profile
4. It appears as in a new tab. Not splited

Probably related issue:

1. Same extension
2. Set `terminal.integrated.defaultLocation` to `editor`
3. Into panel, create a terminal with this profile
4. It appears in edtior area. But other profiles like `bash` appears in terminal panel

None of those problems when terminal profile uses `shellPath`

**Comment by meganrogge** [comment]
This works for me now, so believe it's been fixed
