### ISSUE TITLE
No editor action to jump to next error in project

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14783]
- VSCode Version: 1.6.1

The editor action `editor.action.marker.next` ("Go to Next Error or Warning") only works for the current file. There seems to be no editor action for finding the next error in the project, even when the errors panel shows multiple files.

**Comment by rebornix** [comment]
assign to @alexandrudima first per git blame but I think we might already have this issue reported.

**Comment by alexandrudima** [comment]
fyi @jrieken @sandy081

**Comment by jrieken** [comment]
@atombender @steveluc and other subscribed to this issue: What would be the expected behaviour when you have errors but not in the current file. Would you expect to replace the current file with the 'first' file with errors or is that only expected when coming from a file with errors?

**Comment by pragmascript** [comment]
I would expect the same behaviour as "clicking" the same error in problem panel has.

**Comment by atombender** [comment]
I would expect a _new_ tab to be opened for the erroring file. I would expect that it would marked as a preview tab, so that multiple "next error" jumps forward would replace that new tab with the next file.

There has to be a "previous error" command, too, of course.

**Comment by atombender** [comment]
Column? As in editor split pane? The same, yes.

**Comment by jrieken** [comment]
Wrt to navigation order our plan is to use the order of the markers panel. Today F8 and the marker panels are two different components but the plan is to let them both use the same model. That means sorting and filtering will apply to F8. 

1. Files are sorted by the presence of at least one error, then by their filename

<img width="1031" alt="screen shot 2018-03-05 at 12 14 30" src="https://user-images.githubusercontent.com/1794099/36972350-1124748c-206f-11e8-9a96-d73067f1b2ba.png">

2. When a filter is applied F8 only visits only markers from the filtered-view-model

<img width="997" alt="screen shot 2018-03-05 at 12 14 59" src="https://user-images.githubusercontent.com/1794099/36972389-2e4e4d9e-206f-11e8-9c79-9ea58bc569af.png">

**Comment by sandy081** [comment]
@jrieken You said, we will not move F8 functionality to Problems panel. If so, Let me know if there is anything to be done in Problems panel? User can already navigate problems across files in the panel.

**Comment by jrieken** [comment]
@sandy081 you are off the hook, it already happened

**Comment by monk-time** [comment]
@jrieken I don't quite understand why this change was implemented as a total replacement of the old behavior. I can see its usefulness in projects where all files have zero problems. But as it stands now it's no longer possible to use a keyboard shortcut (F8) to navigate through the problems _only_ in the current file, which can be very useful when working on a project where many files have unresolved problems. 

I don't think I'm the only one who has gotten used to the old behavior, and to me switching to an unrelated file on F8 (with no way to limit it only to the current file) quite jarring and disruptive. I hope you would consider adding a way to configure this or at least a pair of keyboard binding for the old behavior.

Also see #47367 (maybe that issue can be renamed as a feature request for a setting/bindings).
