### ISSUE TITLE
Ability to install specific version from the command line, without it being autoupdated immediately

### ISSUE THREAD

**Issue by oharboe** [microsoft/vscode#147844]
I would like autoupdates for extendsion to be enabled, but for some extensions I would like to be able to run a script to make sure that the right version for us installed and pinned.

The use case is that the extensions must be in sync with external Python dependencies.

Today this is possible, but only via the userinterface, which makes the setup process and deployment of Visual Studio Code brittle; automated setup would fix this.

So something like:

```
code --pin --force --install-extension lextudio.restructuredtext@183.0.0
```

Where "--pin" is an option that, like the userinterface, pins the version number.

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/63903
