### ISSUE TITLE
Cannot push to github using integrated tools or integrated terminal on linux

### ISSUE THREAD

**Issue by ChristopherJTrent** [microsoft/vscode#147990]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.65.1-1
- OS Version: Manjaro Linux 5.15.28-1-MANJARO, KDE Plasma 5.24.3, KDE Framework 5.91.0, Qt 5.15.3

Steps to Reproduce:

1. Attempt to push code to your own github repository using the integrated tools
2. when the browser window opens, note that it gives an error message amounting to "We made breaking changes in a minor version in direct violation of the standards of semantic versioning."

**Comment by lszomoru** [comment]
@TylerLeonhardt, seems to be an issue with GitHub auth flow. Could you please take a look? Thanks!

**Comment by TylerLeonhardt** [comment]
@ChristopherJTrent you seem to be on an older version of VS Code. Can you please get the latest version and let us know if you see the same behavior?
