### ISSUE TITLE
Markdown syntax highlighting highlights parenthetical title text containing parenthesis incorrectly

### ISSUE THREAD

**Issue by CAD97** [microsoft/vscode#147966]
Issue Type: <b>Bug</b>

Create a markdown file:

```md
[link](target (and title (text) with parenthesis)), more text and [another link](target (with title text)).
```

The resulting syntax highlighting:

![image](https://user-images.githubusercontent.com/5992217/164878366-a3f23622-bcf5-4176-935c-e6e9ee13b9cb.png)

Scope inspector:

![image](https://user-images.githubusercontent.com/5992217/164878375-06d41304-cad7-4939-961b-d89a2e1935f8.png)

Per [the CommonMark spec](https://spec.commonmark.org/0.30/#link-title) parenthesized title text must not contain unescaped `(` or `)` characters, so this should not be parsed as a link.

Interestingly, the preview panel correctly does not render this as a link:

![image](https://user-images.githubusercontent.com/5992217/164878407-24481fc4-d789-4c14-a9e4-de68c1111413.png)

VS Code version: Code - Insiders 1.67.0-insider (72b4be55fad0d41092d7df8e03b5597c715fd2e2, 2022-04-22T06:27:20.290Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebug:30475216
pynewfile477:30451556

```

</details>

**Comment by CAD97** [comment]
I found the tm grammar repo and opened a sister issue there: https://github.com/microsoft/vscode-markdown-tm-grammar/issues/108

**Comment by mjbvz** [comment]
Thanks. Closing this in favor of the upstream issue you opened: https://github.com/microsoft/vscode-markdown-tm-grammar/issues/108
