### ISSUE TITLE
Add a Feature to Lock a Folder (which can prevent unknowingly creating something in the respective folder)

### ISSUE THREAD

**Issue by KunalTanwar** [microsoft/vscode#147963]
Introduce a feature to lock/unlock folders (which can prevent unwantedly creating something in that folder). **For Example** - Lets say someone wants to create some file in a parent folder but (i don't know about people) but it happened with me a lot of time that I created that file in `node_modules` folder.

**Image for Reference**

![image 1](https://user-images.githubusercontent.com/77537933/164878123-4f9eb64a-bc39-410c-a6ea-7c549bd380e6.png)

![image 2](https://user-images.githubusercontent.com/77537933/164878155-36f521a3-2632-4f6d-899f-6c746a43b515.png)

**Comment by JacksonKearl** [comment]
Thanks for the feature request. Unfortunately I don't think this is practical for a variety of reasons, for one there are many different ways to create a new file, and it's not clear which of them should be affected by this. You can always lock it at the OS level to truly seal it.
