### ISSUE TITLE
Allow opening a recent project into a new window

### ISSUE THREAD

**Issue by yaugenka** [microsoft/vscode#147933]
When opening a recent project ask if it should be opened in the current or new window.

**Comment by IllusionMH** [comment]
Just FYI: If you are opening recent project from **File** > **Open Recent** then you can hold <kbd>Shift</kbd> or <kbd>Ctrl</kbd> to open the in a new window.

**Comment by yaugenka** [comment]
Oh, that's awesome. I did not know about that. No need for this feature then.
