### ISSUE TITLE
The terminal is not working!

### ISSUE THREAD

**Issue by Arij-Adel** [microsoft/vscode#147951]
An issue with the terminal!
It doesn't allow me to type anything, and the $ sign does't show up!
Version: 1.67.0-insider
Commit: 72b4be55fad0d41092d7df8e03b5597c715fd2e2
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36 Edg/100.0.1185.44
Embedder: codespaces

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
