### ISSUE TITLE
Not able to reload or quit VS Code

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#14795]
- VSCode Version: Code - Insiders 1.7.0-insider (0706b425537d8cfe2766eac00662ecf988c7ed7f, 2016-10-28T13:00:19.188Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.7|
|theme-atom-one-dark|andischerer|0.0.1|
|close-all|benjpas|1.0.2|
|vscode-eslint|dbaeumer|1.0.8|
|tslint|eg2|0.5.39|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|Theme-Dawn|gerane|0.0.2|
|vscode-codemetrics|kisstkondoros|1.1.3|
|copy-github-url|mattlott|0.0.3|
|debugger-for-chrome|msjsdiag|2.1.0|
|vscode-stocks|roblourens|0.0.3|
|Theme-GitHubCleanWhite|saviorisdead|0.0.3|
|slack|sozercan|0.0.8|

---

While coding, I saw a message that Extension host is crashed and asked to reload the window. 
I tried to reload the window - I got an error.
I tried to quit VS Code - I got an error.

See the attached gif / screenshot

![nov-01-2016 09-10-26](https://cloud.githubusercontent.com/assets/10746682/19883200/33bc8a4e-a013-11e6-9a9c-dd74ec21f7b7.gif)

![image](https://cloud.githubusercontent.com/assets/10746682/19883207/3dc34ad2-a013-11e6-9dd6-cf2a450efaac.png)

There were no exact steps to reproduce. It happened all of a sudden today,

**Comment by bpasero** [comment]
Tried to reproduce but failed. The reload window command is very trivial, I wonder why it failed. If it happens again, please try to debug:

![untitled](https://cloud.githubusercontent.com/assets/900690/19885974/d51645de-a021-11e6-8fff-de5e19d48ff4.gif)

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
