### ISSUE TITLE
existing namespaces are reported as missing

### ISSUE THREAD

**Issue by mleistritz** [microsoft/vscode#147945]
Issue Type: <b>Bug</b>

I was working on an existing project when VSC suddenly reported more than 1k problems. All of them are related to missing namespaces and follow-up problems. The code however is perfectly fine, the namespaces are there and the application compiles and runs without any issues. Coding in VSC however, is impossible in this state.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
unity-code-snippets|kle|1.3.0
csharp|ms-|1.24.4
powershell|ms-|2021.12.0
unity-debug|Uni|3.0.2

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

You should at least provide language and code sample that causes problem.

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

**Comment by mleistritz** [comment]
Hi there! It is a unity project in C#. Most of the "non-standard" namespaces (= everything but System.*  and UnityEngine.*) are affected. After some research and trial and error regeneration the project files in Unity did the trick.
