### ISSUE TITLE
macos window splitting

### ISSUE THREAD

**Issue by adnanjpg** [microsoft/vscode#147969]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:47:29.396Z (1 wk ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0
```
- OS Version:
```
System Version:	macOS 12.3.1 (21E258)
Kernel Version:	Darwin 21.4.0
```

Steps to Reproduce:

1. open 2 vsc instances, make them fullscreen, and then drag them next to each other to split the screen (also reproducable by splitting with other apps like chrome)
2. now the app is kinda considered as a one piece, so the side menu will fade away when you minimize the screen too much
<img width="1352" alt="Screen Shot 2022-04-23 at 10 42 45" src="https://user-images.githubusercontent.com/54329101/164885356-088d6ed2-f360-45dc-b6e2-2ad4e3d84ffb.png">
(notice how half of the menu is faded)
<img width="1352" alt="Screen Shot 2022-04-23 at 10 43 04" src="https://user-images.githubusercontent.com/54329101/164885362-0eddd09f-a577-4909-a285-404c5a6fca4d.png">

**Comment by bpasero** [comment]
?

**Comment by adnanjpg** [comment]
hi @bpasero, I think it is very disrespectful for you to comment a '?' . what is the wrong with you?

**Comment by adnanjpg** [comment]
this is the first time I see this much disrespect against a person trying to make the product better.

**Comment by joaomoreno** [comment]
@adnanjpg That amount of horizontal space just isn't enough for VS Code to fully render. While it is still operational, it is below an optimal size. There are [a bunch of open feature requests related to workbench layout](https://github.com/microsoft/vscode/issues?page=2&q=is%3Aopen+is%3Aissue+label%3Alayout+label%3Afeature-request) which would help in this specific case of narrow width, feel free to subscribe to them and upvote them.
