### ISSUE TITLE
Smudgy fonts and icons

### ISSUE THREAD

**Issue by AidanVIII** [microsoft/vscode#147982]
![Screenshot (27)](https://user-images.githubusercontent.com/20214995/164942600-716c630a-cd86-4053-b863-80fcd4a79a2f.png)

# Does this issue occur when all extensions are disabled?

Yes

# About

Version: 1.67.0-insider (user setup)
Commit: 72b4be55fad0d41092d7df8e03b5597c715fd2e2
Date: 2022-04-22T06:27:20.290Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

# Steps to Reproduce

1. Start VSCode

# Expected

Readable fonts and icons

# Saw

Smudgy fonts and icons

# Additionaly

- https://github.com/microsoft/vscode/issues/146399 seems related, although:
    - I don't have the bold setting on.
    - It happens with every font.
- Randomly gets better/worse with interactions.
- Happens since 1.66

**Comment by deepak1556** [comment]
Can you check if running with `code --disable-gpu` fixes the issue ?

**Comment by AidanVIII** [comment]
Yes!
Should I consider this an issue with my particular GPU or its model in general?
(GTX 1660 Super AERO ITX OC)

**Comment by AidanVIII** [comment]
Updating drivers did not fix it.

**Comment by AidanVIII** [comment]
I just noticed [the upstream](https://bugs.chromium.org/p/chromium/issues/detail?id=1313968) for https://github.com/microsoft/vscode/issues/146399 reports a similar GPU.
I'll try there.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146381, please follow that issue for updates.
