### ISSUE TITLE
Terminal history is truncated after resizing the window when word wrap setting is being applied

### ISSUE THREAD

**Issue by vladimir-trifonov** [Microsoft/vscode#14796]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra v. 10.12.1

Steps to Reproduce:

1. Add "editor.wrappingColumn": 0 in settings.json to apply word-wrap setting by default.
2. Resize the window - make it smaller, then maximize it again.

The terminal history is truncated:

![screenshot 2016-11-01 10 29 42](https://cloud.githubusercontent.com/assets/7524789/19883832/0f0ed646-a01f-11e6-8217-1247b72eb912.png)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/8336
