### ISSUE TITLE
CPU&memory occupation high and windows break down when using VSCode as external editor of Xilinx Vivado

### ISSUE THREAD

**Issue by HeroChan0330** [microsoft/vscode#147988]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.setting VSCode as the external editor of Vivado. Opening vivado, goto the menu bar Tool->Setting->Text Editor Select Custom as current editor. Fill the textbox by **"path of vscode/Code.exe" -g [file name]:[line number]**
2.Then open a large project by vivado, open one source file. It shold goto the VSCode immediately, However the window always break down.

**Comment by sandy081** [comment]
We do not support this integration. So I would request to file the issue against Xilinx Vivado product to get it diagnosed. Thanks.

**Comment by HeroChan0330** [comment]
I don't think it is the matter of Vivado. When I use the same way to set Atom as the external editor of Vivado, Atom would never break down. Using VSCode as the external editor of Vivado is just a process of create a VSCode process and pass some argument into VSCode, Therefore VSCode process is totally independent from Vivado. I really think that it's the matter of VSCode. You should checkout the executing way of command line  `code.exe -g <filename>:<line>`

**Comment by yizakat** [comment]
See open issue: https://github.com/microsoft/vscode/issues/147541

**Comment by HeroChan0330** [comment]
> 

So, we can sure that this isn`t a special case, almost all the computer occur this bug when using vscode as the external editor of Vivado.  Just because vscode`s auto update and some bugs when produce.
