### ISSUE TITLE
already updated

### ISSUE THREAD

**Issue by Aryandadhich** [microsoft/vscode#147971]
Issue Type: <b>Bug</b>

sir i already updated visual code but it still ask for update and reinstallation?

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.65GB free)|
|Process Argv|--crash-reporter-id bdce7547-6787-4d5d-ab33-f815d935e926|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
author-stats|ada|1.0.4
android-dev-ext|ade|1.3.2
flutter-snippets|ale|3.0.0
vscode-django|bat|1.10.0
dart-data-class-generator|Ben|0.5.5
bracket-pair-colorizer-2|Coe|0.2.4
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
emulate|Die|1.6.0
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
threejs|En1|0.0.1
pip-packages|etm|0.4.3
php-intellisense|fel|2.3.14
code-runner|for|0.11.7
html-snippets|gey|0.2.3
opencv-snippets|gsG|1.2.2
vscode-picture|Jak|1.0.0
csharpextensions|jch|1.3.1
vscode-csharp-snippets|jor|1.1.0
unity-code-snippets|kle|1.3.0
tag-inserter|l7s|1.4.0
quickstart|lol|0.1.0
vscode-JS-CSS-HTML-formatter|lon|0.2.3
code-groovy|mar|0.1.2
groovy|Mel|1.0.0
csharp|ms-|1.24.4
anaconda-extension-pack|ms-|1.0.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.66.0
open-html-in-browser|pea|2.1.9
vscode-yaml|red|1.6.0
LiveServer|rit|5.7.5
html5-boilerplate|sid|1.1.1
ejs-snippets|Tao|0.1.0
open-in-browser|tec|2.0.0
html-preview-vscode|tht|0.2.5
HTML5-extension-pack|wal|1.0.0
html-snippets|wge|0.1.5
php-debug|xde|1.26.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code?
