### ISSUE TITLE
Lint error in Python for := operator

### ISSUE THREAD

**Issue by anselal** [microsoft/vscode#147980]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.1
- OS Version: Windows 10 + Ubuntu 20.4.4

Steps to Reproduce:

1. write an expression with a := operator like

```python
a=1
b=1
c=True

if (check := (a==b) and c):
    print(check)

```

I get the following error

```
SyntaxError: invalid syntaxjedi
keyword :
Slicings
********
```
![2022-04-23_18h59_05](https://user-images.githubusercontent.com/8732668/164913722-280def58-bc27-4345-b1c6-357c92da45d8.png)

**Comment by WolfyzDev** [comment]
Personally by copying your code, I have no errors (neither in "problems" nor at runtime).
What is your version of Python and does this error persist by running the Python file on your system (not via VS Code therefore but by double-clicking on it in the file explorer for example) please?

**Comment by anselal** [comment]
I am running Python 3.8.

It is a linting error, for some reason this operator `:=` is not recognised.

I can run the code without any errors...
