### ISSUE TITLE
Allow several settings.json

### ISSUE THREAD

**Issue by turion** [microsoft/vscode#147911]
### Proposed feature

VSCode should not only read the standard `settings.json`, but also additional settings files. I can imagine different ways how to specify these files. For example:

* All `*.json` files in a predefined folder like `~/.config/VSCodium/User/settings`
* All files matching a regex like `settings.*\.json` (matching `settings.json`, `settings1.json`, `settingsReadOnly.json`, `settingsTeamWide.json`, `settingsCheckedInToGitRepo.json`, etc.)
* Files given on the command line like `codium --additional-settings=path/to/additional/settings.json`

This way, different sets of settings can be specified editor-wide. These would have to be merged with some notion of precedence, similar to how workspace settings are merged with user settings.

### Context

I'm trying to improve the VSCodium experience on [NixOS](nixos.org/)/[Home Manager](https://rycee.gitlab.io/home-manager/). There, one configures the editor declaratively, producing a config file that is not writable by the editor. It would be great if there were two settings files, one read-only file produced by Home Manager, and an editor-writable file (the standard `settings.json`).

#### Other use cases

* Software development teams might want to share some of their settings (across multiple workspaces) by checking them into version control. On top, some team members want their own settings.
* For debugging, one could turn a set of settings on or off by extracting them to a file.

**Comment by sandy081** [comment]
It seems you are using VSCodium and this project is VS Code and both are not same. I would request to file issue against VSCodium project.

**Comment by turion** [comment]
Sorry, I accidentally posted the VSCodium paths because I tested whether the issue is there as well. But the issue is about VSCode. Can we reopen?

**Comment by sandy081** [comment]
There is a duplicate of this request, please search for existing issues. Thanks.

**Comment by turion** [comment]
I have searched through >300 issues here: https://github.com/microsoft/vscode/issues?q=is%3Aissue+settings.json+is%3Aopen.

I found some related ones:
* https://github.com/microsoft/vscode/issues/80972
* https://github.com/microsoft/vscode/issues/17634
* https://github.com/microsoft/vscode/issues/15909
