### ISSUE TITLE
Setting keyboard shortcut `when` to `editorTextFocus && (editorDirty || editorReadonly)` gives `editorReadonly) || (editorDirty && editorTextFocus` instead

### ISSUE THREAD

**Issue by stdedos** [microsoft/vscode#147904]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: https://vscode.dev/
- OS Version: https://vscode.dev/

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/133706/164634304-33c71600-8592-4c08-8d7e-043f54a0c677.png)

**Comment by alexdima** [comment]
@stdedos The parser for context keys does not support parens, so when typing:
```
editorTextFocus && (editorDirty || editorReadonly)
---------------    ------------    ---------------
        A                B               C
```
it parses `A && B || C`, where `A` is `editorTextFocus`, `B` is `(editorDirty` and `C` is `editorReadonly)`.

It then proceeds to render that as `C || A && B` which yields:
```
editorReadonly) || editorTextFocus && (editorDirty
---------------    ---------------    ------------
        C                A                 B
```

So the root request here is to add parens support to context keys.
