### ISSUE TITLE
Context menu (pop and click) doesn't focus the window

### ISSUE THREAD

**Issue by vsly-ru** [microsoft/vscode#147967]
Issue Type: <b>Bug</b>

0) using macOS. Preferably with 2 or more displays.
1) Open a VSCode window (let's call it "first") with any project and the (file) Explorer opened on a side bar. 
2) Focus some other ("second") window (e.g. a browser or another VSCode window)
3) Back in the first window (without first focusing it), open a file or folder's context menu and select something that requires typing (new file, new folder, rename...).
4) Type a file or folder name on your keyboard.

Expected behaviour: keyboard input goes into the highlited input field. 
Actual behaviour: window doesn't focus and keyboard input goes into the second window.
macOS behaviour (in Finder): main window doesn't focus but keyboard input goes into its input field.

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 20.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id c45ad719-2498-406c-9421-8cd79d6b01c2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
svelte-intellisense|ard|0.7.1
vscode-tailwindcss|bra|0.8.2
bracket-pair-colorizer|Coe|1.0.62
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-great-icons|emm|2.1.86
vsc-material-theme-icons|equ|2.2.1
json-to-dart|hir|3.5.7
vscode-github|Kni|0.30.7
dart-import|lua|0.3.1
svelte-format|mel|0.0.7
fluent-icons|mig|0.0.17
awesome-flutter-snippets|Nas|3.0.3
svelte-autoimport|piv|1.0.4
material-icon-theme|PKi|4.16.0
vscode-yaml|red|1.6.0
svelte-vscode|sve|105.16.0
icons|tal|3.1.0
vscode-icons|vsc|11.11.0
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details>

**Comment by isidorn** [comment]
I am sorry but I do not know the exact duplicate issue number. But please search for "electron context menu focus" and you should be able to find it. Thanks
