### ISSUE TITLE
New comments panel: author name gets truncated

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#147920]
When the comment is too long to fit in the panel (which is common), the author name and the date get truncated first. Instead, we should truncate the comment:

e.g. look at the last comment in
![image](https://user-images.githubusercontent.com/485572/164717547-ed7f3f86-696d-452e-a7b9-b420c92bcf4d.png)

Showing the author name (instead of `c...`) should be more important than showing a few more characters in the comment preview.

(cc @hermannloose, @alexr00)

**Comment by rchiodo** [comment]
/verified

It prefers the user name over comment now.
