### ISSUE TITLE
filter problems text area keeps stealing focus

### ISSUE THREAD

**Issue by clenfest** [microsoft/vscode#147942]
I'm sure I need to provide some sort of trace, so please give me the instructions for that, but in the meantime here's what I know:
- I've tried using the extension bisect feature and it still seems to be a problem even when no extensions are running.
- It doesn't happen in every project. The one that it occurs in most often is rather large and it happens every minute or so, but in a smaller project it happens almost never
- Both projects are typescript based

Happy to provide whatever additional info is required. Thanks!

**Comment by sandy081** [comment]
Can you please record a video and share with us?
