### ISSUE TITLE
Switch focus to terminal when switching between them

### ISSUE THREAD

**Issue by miselico** [microsoft/vscode#147919]
When one has multiple integrated terminals open, and then use the mouse to switch between them, the focus remains on the bar with the tabs, rather than switching to the now active terminal. I'd like the focus to switch to the terminal This would be consistent to how switching happens between editor tabs.

**Comment by gjsjohnmurray** [comment]
Set `"terminal.integrated.tabs.focusMode": "singleClick"` to achieve this.

**Comment by miselico** [comment]
Thanks @gjsjohnmurray this is indeed what I wanted. I would vouch for making this the default, but having the option is great!
