### ISSUE TITLE
Insiders: Margin Around Maximized Window on Wayland/Gnome 42.0

### ISSUE THREAD

**Issue by jcdickinson** [microsoft/vscode#147984]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0-insider
- OS Version: Linux x64 5.17.1-xm1.0.fc36.x86_64
- Commit: 72b4be55fad0d41092d7df8e03b5597c715fd2e2
- Electron: 17.4.1
- Chromium: 98.0.4758.141

https://gfycat.com/elderlyrepulsivehyrax

Steps to Reproduce:

1. Install VSCode on Wayland
2. Start VSCode with these additional flags:
   `--enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-platform=wayland --ozone-platform-hint=auto`
3. Maximize the window

There is a margin around the window, most likely it is the size of the window drop shadow.

Demonstration: https://gfycat.com/elderlyrepulsivehyrax

Edit: when manually sizing/moving the window it does snap to the screen edges.

**Comment by vially** [comment]
This seems to be an upstream Electron issue: https://github.com/electron/electron/issues/33161.

**Comment by deepak1556** [comment]
This should be addressed in latest stable `1.73`
