### ISSUE TITLE
Wrap highlighted code into brackets on bracket key press

### ISSUE THREAD

**Issue by yaugenka** [microsoft/vscode#147937]
Assume there are some lines of code which you want to wrap into an if condition.
You add the if contidion at the top of the code, then highlight the code you want to wrap and press the opening bracket key.
The hightlighted code should get wrapped by opening and closing brackets and indented appropriately.

**Comment by hediet** [comment]
I think the formatter feature should do this (here format on save):

![Code_-_Insiders_aCdRopy2MO](https://user-images.githubusercontent.com/2931520/206723480-1d24452a-edcd-4697-bd60-8920d90e252d.gif)
