### ISSUE TITLE
Chinese characters visible

### ISSUE THREAD

**Issue by rosrad** [Microsoft/vscode#14790]
- VSCode Version:1.6.1
- OS Version: win10

Steps to Reproduce:

1.  can not show Chinese characters

**Comment by rebornix** [comment]
Can you provide detailed steps and information, like which Chinese characters are not shown, Menu, Panel or document? It would be better if you can provide a screenshot.

**Comment by rosrad** [comment]
the Chinese characters be in documents. you may see in the screenshot
![image](https://cloud.githubusercontent.com/assets/2343640/19918859/adfb46b4-a109-11e6-91dc-81ba3add7ef4.png)

**Comment by rebornix** [comment]
Per your screenshot your problem is quite similar to #9511 and it's likely an encoding issue. Do you mind giving it a check that all content are encoded correctly or maybe you can provide a copy of the file uploaded to see what the binary contents of the file are.

**Comment by aeschli** [comment]
Closing due to lack of information. Please reopen with data described above.
