### ISSUE TITLE
mode Contraste élevé

### ISSUE THREAD

**Issue by Marcibcp2ri1** [microsoft/vscode#147996]
Nous avons écrit les données nécessaires dans votre presse-papie
Issue Type: <b>Bug</b>

J'ai mis les contrastes élevé sur Windows 10 et vs code ne veux plus se remettre comme avant, il reste soit tout blanc soit tout noir.

**Comment by WolfyzDev** [comment]
Que voulez-vous dire par "soit tout blanc soit tout noir" please ? 
Et quelle était le rendu avant de mettre le contraste élevée please ?

What do you mean by "either all white or all black" please?
And what was the rendering before putting the high contrast please?
