### ISSUE TITLE
Failure trying to create exe file in personal folder

### ISSUE THREAD

**Issue by tomgallagher** [microsoft/vscode#147918]
Issue Type: <b>Bug</b>

I keep on getting asked about permissions being denied to install an exe file `unins000.exe` in my `users\..\AppData\Local\Microsoft VC Code` folder on C drive.

VS Code version: Code 1.66.1 (8dfae7a5cd50421d10cd99cb873990460525a898, 2022-04-06T14:50:12.141Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3606)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.29GB free)|
|Process Argv|--crash-reporter-id 3490e4c5-70ac-467b-a396-77692c989314|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-pull-request-github|Git|0.40.0
vscode-react-typescript|inf|1.3.1
vscode-peacock|joh|4.0.1
jq-syntax-highlighting|jq-|0.0.2
chat|kar|0.35.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
debugger-for-chrome|msj|4.13.0
es6-css-minify|olb|3.3.3
run-on-save|puc|1.5.1
LiveServer|rit|5.7.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by joaomoreno** [comment]
Is this during an update?

If so, can you uninstall and reinstall VS Code?

**Comment by tomgallagher** [comment]
Yes, I did that. Seems to have fixed the problem. 

Not quite sure how it happened
