### ISSUE TITLE
View -> Appearance -> Fullscreen still says 'F11' despite F11 key doing otherwise.

### ISSUE THREAD

**Issue by Kerdek** [microsoft/vscode#147928]
Issue Type: <b>Bug</b>

I have no way of knowing exactly what of the 1000s of possible sources of incoming side-effects could contribute to this. The amount of information I can access allows me to be certain that it will be reproducible only where you have my exact system with my exact module set. The F11 key causes a debug session to initiate while I am working on this javascript file while a nodejs package source folder is open in the latest version of vscode downloaded into debian using apt according to the instructions on their wiki.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.10.106
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 4602)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (9.11GB free)|
|Process Argv|--unity-launch --crash-reporter-id e585ffe9-7db6-45fd-8db9-70a6acc77de2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
ebrew-vscode|498|0.1.4
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.16
vscode-clangd|llv|0.1.15
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
hexeditor|ms-|1.9.6
vscode-typescript-next|ms-|4.7.20220421
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaat:30438848

```

</details>

**Comment by weinand** [comment]
please see https://stackoverflow.com/questions/29955146/unable-to-debug-with-f11-with-vscode-toggled-fullscreen

**Comment by gjsjohnmurray** [comment]
@weinand the OP's version info shows Linux rather than macOS.

**Comment by weinand** [comment]
On linux the following commands are assigned to the `F11` key:
![CleanShot 2022-04-25 at 15 00 22@2x](https://user-images.githubusercontent.com/1898161/165094316-69f80138-ea0a-4350-bdc3-5f57d4bb88f9.png)

So the "Fullscreen" command uses the `F11` key on linux.
Yes this is unfortunate, but we will not change this.

**Comment by Kerdek** [comment]
So why does the menu still put F11 text next to View -> Appearance -> Full Screen if F11 is assigned to something else? Even if node devs are going to get preference here, why lie to everyone else?

**Comment by Kerdek** [comment]
![image](https://user-images.githubusercontent.com/8801228/165293156-0df67c4d-5e91-4eae-831f-9ec88c84bd0d.png)

**Comment by weinand** [comment]
F11 is typically used for debugging as well. So there is a clash.
In VS Code F11 for debugging should only be enabled if the currently selected launch config is of type "node". 

@isidorn @connor4312 do you remember the rational behind this?

**Comment by isidorn** [comment]
@weinand probably the keybinding enablement of full screen is not dynamic enough and the menu does not pick it up.

**Comment by connor4312** [comment]
> In VS Code F11 for debugging should only be enabled if the currently selected launch config is of type "node".

That should be the case (and seems to be from the screenshot). It sounds like the enablement isn't quite right. That also seemed like a culprit in https://github.com/microsoft/vscode/issues/71800, where testing using `cmd+h` seemed to sometimes permanently start capturing that shortcut (though I have since moved to use a different shortcut in testing)
