### ISSUE TITLE
File Nesting: nested files of same pattern are invisible after deleting one

### ISSUE THREAD

**Issue by ntnyq** [microsoft/vscode#147987]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: macOS 10.14.3

Steps to Reproduce:

1. setup file nesting
2. delete a nested file

**Comment by ntnyq** [comment]
https://user-images.githubusercontent.com/22659150/164952491-66bc44c2-53b0-464b-b5a9-eee21153eb24.mov

**Comment by JacksonKearl** [comment]
Haven't been able to repro this, can you check in the latest Insiders? If it still reproduces there please share your nesting config and a sample repo is possible. Also there may be information logged to the developer tools (`Developer: Toggle Developer Tools`)

**Comment by ntnyq** [comment]
Besides, there isn't any logs in the developer tools.

**Comment by JacksonKearl** [comment]
Do you have `explorer.fileNesting.expand` set to `false`? I am able to repro with that but not otherwise.

**Comment by ntnyq** [comment]
Yes `explorer.fileNesting.expand` is set to `false`

**Comment by JacksonKearl** [comment]
Thanks for the report, I'm going to track this with #148218 as it has the most comprehensive repro steps.
