### ISSUE TITLE
global bash profile isn't run for login shell when shell integration is enabled

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#147952]
1. add something to your `/etc/bash_profile`
2. enable shell integration
3. 🐛  your global `bash_profile` did not get run

**Comment by connor4312** [comment]
Hmm, I created `/etc/bash_profile` both on OSX and Linux, but it doesn't seem to be executed when I run `bash` with or without shell integration. If it matters, zshell is the default on both these systems. Anything I need to do to turn it on?

**Comment by meganrogge** [comment]
you have to be using a login shell - what are your terminal settings at the moment? 

also, does it run in an external terminal?

**Comment by JacksonKearl** [comment]
Verified `/etc/bash_profile` does run for login shells when shell integration is enabled, but I wonder if it should... I haven't found anything documenting it online, and it doesn't run in external terminals or with shell integration disabled. @meganrogge where did you see it documented?

I believe we should actually be running `/etc/profile` when shell integration is enabled, this is run when shell integration is disabled and in external terminals (in login shells only), but not when shell integration is enabled. 

See https://www.golinuxcloud.com/bashrc-vs-bash-profile/#List_of_bash_startup_files

**Comment by meganrogge** [comment]
😦 yes you are correct - that should be `/etc/profile` not `/etc/bash_profile`. it's a bit confusing for bash. for every global `zsh` startup script, there's a corresponding global one of the same name in the `/etc/` file. Not the case here though

**Comment by JacksonKearl** [comment]
What could be more simple? 🥲 Joys of working with 30+ year old software.
![image](https://user-images.githubusercontent.com/8586769/166077600-c70dd731-e0fa-47bd-b3a2-0d45bb003f3c.png)
