### ISSUE TITLE
Can't close "ambiguous unicode characters" in diff view

### ISSUE THREAD

**Issue by SethFalco** [microsoft/vscode#147991]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
```
Version: 1.67.0-insider
Commit: 72b4be55fad0d41092d7df8e03b5597c715fd2e2
Date: 2022-04-22T06:27:40.408Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.10.0-13-amd64 snap
```

- OS Version:
```
Linux 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64
```

Steps to Reproduce:

1. Open a workspace in a directory with this file inside.
   * https://gist.github.com/SethFalco/d197e138e5078cd6d5a66334cd343447
2. Initialize a git repository so Visual Studio's git integration can display changes.
3. Go to the "Source Control" view and review the changes.
4. Click "ahh.po" to preview the changes.

![image](https://user-images.githubusercontent.com/22801583/164960919-d6fc77d1-22d8-4896-aeb4-3ef55710a86b.png)

At the top left, the `x` button can't be clicked. Instead, if I click there it scrolls to the top, and if I hold, then I can pull down to scroll down. (Basically we end up getting control of the scroll bar instead.)

**Comment by lszomoru** [comment]
@hediet, is this something that falls under your area of ownership? Thanks!

**Comment by SharakPL** [comment]
And how can I find these "ambiguous unicode characters" in a file? I get that message on sql dumps, but have no idea which characters are ambigious. File has over 300k lines. How am I supposed to find them in there? These characters should be pointed out.

**Comment by hediet** [comment]
This got fixed with the diff editor rewrite.
