### ISSUE TITLE
The continuous growth of CPU and memory occupied by node processes leads to server crash

### ISSUE THREAD

**Issue by 1997shp** [microsoft/vscode#147992]
server： ubuntu 20.04
my computer: win10
vscode: 1.66.2

The node process keeps increasing. When I use vscode remote SSH to connect to the remote server
I want to know how to solve this problem. Thank you very much
I didn't encounter this problem on my other server

Tasks: 122 total,   2 running, 120 sleeping,   0 stopped,   0 zombie
%Cpu(s): 31.2 us, 23.9 sy,  0.0 ni, 44.7 id,  0.0 wa,  0.0 hi,  0.2 si,  0.0 st
MiB Mem :   3931.2 total,   2040.8 free,   1019.2 used,    871.2 buff/cache
MiB Swap:      0.0 total,      0.0 free,      0.0 used.   2592.1 avail Mem 

PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                               
3120 root      20   0 1199328 481116  32540 R 100.0  12.0   8:35.65 node                                                                                                                                                  
3008 root      20   0  999128 165780  41304 S   7.3   4.1   0:37.29 node

**Comment by 1997shp** [comment]
I solved the problem by deleting the root/.vscode-server directory

**Comment by weinand** [comment]
I don't understand your problem.
Are the node processes running on your server VS code processes?

**Comment by 1997shp** [comment]
> 我不明白你的问题。 节点进程是否在您的服务器 VS 代码进程或您自己的服务器的一部分上运行消耗大量内存？

This process occurs when I install extensions on the server

**Comment by 1997shp** [comment]
> 我不明白你的。 进程是否在您的服务器 VS 进程代码问题或您自己的服务器的一部分上运行占用大量内存？

Next, the  node process will keep increasing the memory consumption. I disconnect remote-ssh, the node process will not be destroyed

**Comment by 1997shp** [comment]
> I don't understand your problem. Are the node processes consuming lots of memory running on your server VS code processes or part of your own server?

My current solution is to delete / root / vscode_ Server directory, restart ubuntu, No more extensions installed.

In this state, the service is stable

**Comment by 1997shp** [comment]
> I don't understand your problem. Are the node processes consuming lots of memory running on your server VS code processes or part of your own server?

I hope this information can help you

**Comment by alexdima** [comment]
@1997shp It looks like you have installed an extension which ends up consuming a lot of memory. When you delete the vscode server directory, you are effectively also deleting installed extensions. Which extensions are you installing? Does the Out-Of-Memory crash occur if you avoid installing extensions?

**Comment by 1997shp** [comment]
> @1997shp看起来您已经安装了一个最终会消耗大量内存的扩展程序。当您删除 vscode 服务器目录时，您实际上也删除了已安装的扩展。您要安装哪些扩展程序？如果您避免安装扩展程序，是否会发生 Out-Of-Memory 崩溃？
@alexdima  I have python installed   But the strange thing is that this is not the case on my other ubuntu  server. Additional ubuntu servers are even smaller

**Comment by 1997shp** [comment]
@alexdima  Unfortunately, I can't reproduce the scene with my home computer  Even if I installed the same extension 
I can only wait until the end of the holiday. I use my work computer to experiment

**Comment by alexdima** [comment]
Thank you for your prompt answer! Please update the issue here as soon as you have a chance.

**Comment by 1997shp** [comment]
> Thank you for your prompt answer! Please update the issue here as soon as you have a chance.

@alexdima  Hello, after many attempts. I think this pylance extension caused the problem.When I uninstall it from the remote server, the node process no longer takes up too much memory and CPU
![image](https://user-images.githubusercontent.com/49704057/166133801-85803566-4528-481d-849f-b7fe4ae34175.png)

**Comment by alexdima** [comment]
@1997shp Thank you for the information. Please create an issue directly against the Pylance extension at https://github.com/microsoft/pylance-release/issues
