### ISSUE TITLE
Codespaces creating a virtual env in a pure markdown repo

### ISSUE THREAD

**Issue by thepalbi** [microsoft/vscode#147954]
Github Codespaces is creating a Python virtualenv in a pure markdown repo. This is not per-se an issue, but it's annoying since I don't need Python, and I have to manually delete the .venv directory, or keep looking out to not stage those files in git.

<img width="420" alt="image" src="https://user-images.githubusercontent.com/2617411/164814012-cb508ed8-7cb9-467d-99d0-8b975df0f0d7.png">

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Embedder: codespaces

**Comment by alexr00** [comment]
@thepalbi do you have the python extension installed?

**Comment by thepalbi** [comment]
Hey @alexr00 , found out there was a Python file in the middle of the repo, so GH marked the repo as 100% Python. I guess that's why the venv was created for me. 
Thanks for answering 😀
