### ISSUE TITLE
Vscode Secrets API not clearing all credentials from credential manager

### ISSUE THREAD

**Issue by monil-patel** [microsoft/vscode#147938]
Does this issue occur when all extensions are disabled?: Yes/No
N/A need one extension in order to sign in 

- VS Code Version: 1.66.2
- OS Version: Windows 11

Steps to Reproduce:

I have an extension using the microsoft provider for sign in. 

First Sign in -> results in these entries in the windows credential manager which makes sense since it needs to be split up to fit

Was using this powershell line to list entries in wincred
```
cmdkey /list | ForEach-Object{if($_ -like "*Target:*" -and $_ -like "*vscodevscode.microsoft-*"){echo $_}}
```

```
First Sign In 

Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/microsoft.login.keylist
Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/XXXXX-41af-91ab-2d7cd011db47/XXXXX-a9fb4fb8687a/XXXXX-82a6-79d8b45c5231
Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/XXXXX-41af-91ab-2d7cd011db47/XXXXX-a9fb4fb8687a/XXXXX-82a6-79d8b45c5231-1

Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/XXXXX-41af-91ab-2d7cd011db47/XXXXX-a9fb4fb8687a/XXXXX-4c31-a023-3b655c1fb9f3
Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/XXXXX-41af-91ab-2d7cd011db47/XXXXX-a9fb4fb8687a/XXXXX-4c31-a023-3b655c1fb9f3-1
```

Sign out using accounts menu . The entries for the credential-1 still are in there. 

```
Sign out 
Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/microsoft.login.keylist
Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/XXXXX-41af-91ab-2d7cd011db47/XXXXX-a9fb4fb8687a/XXXXX-82a6-79d8b45c5231-1
Target: LegacyGeneric:target=vscodevscode.microsoft-authentication/XXXXX-41af-91ab-2d7cd011db47/XXXXX-a9fb4fb8687a/XXXXXb-4c31-a023-3b655c1fb9f3-1
```

This means overtime it will keep adding but not clear things properly. Not sure if its because of local development/alot of testing but at one point after signing into the "microsoft provider" the output pane said "not enough resources to complete this operation" I think it was hitting some potential max of storage in the windows credential manager(?) I was able to resolve it by removing old stored creds but discovered this behavior

**Comment by monil-patel** [comment]
Update I dont think this is specific to microsoft provider. seems to be more of an issue with the vscode.secrets API. Our extension was also leveraging that and seeing it for other stored credentials the split up creds (-1) isnt being removed properly

**Comment by TylerLeonhardt** [comment]
@monil-patel unfortunately, you'll need to manually delete those extra passwords out of cred man, but the leftover secrets shouldn't happen anymore.

**Comment by TylerLeonhardt** [comment]
verification steps:

* On Windows, log in with your Microsoft account for settings sync or some random extension
* run `cmdkey /list | ForEach-Object{if($_ -like "*Target:*" -and $_ -like "*vscodevscode.microsoft-*"){echo $_}}` you should see 3 entries
* Now log out of that account
* run the command again, you should see only 1 left, the keylist.

NOTE: If you already have extra `-1` secrets it means you've already hit this bug. You'll need to remove those secrets from CredMan manually before verifying this issue.
