### ISSUE TITLE
`process(` unhelpfully auto-completes to `ProcessingInstruction`

### ISSUE THREAD

**Issue by hamirmahal** [microsoft/vscode#147943]
Issue Type: <b>Bug</b>

Open a JavaScript file in VSCode with all extensions disabled.

Type in `process(`.

What is presumably Visual Studio Code's JavaScript language server autocompletes `process(` to `ProcessingInstruction()`.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (19.09GB free)|
|Process Argv|--crash-reporter-id 8611a859-5531-48ae-aa17-0d46229dd3cc|
|Screen Reader|no|
|VM|33%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4199)|
|Memory (System)|7.76GB (3.14GB free)|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.66.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by hamirmahal** [comment]
https://user-images.githubusercontent.com/43425812/164775372-a8cea745-bddf-4456-9d03-7c66e1cee97d.mp4

**Comment by mjbvz** [comment]
Try adding the typings for whatever package you are trying to work with (the one with the `process` function)

If you want to disable `(` accepting suggestions, set `"editor.acceptSuggestionOnCommitCharacter": false`
