### ISSUE TITLE
Python interpreter selector missing from the GUI

### ISSUE THREAD

**Issue by thesalmonidae** [microsoft/vscode#147997]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: W11 10.0.22000 (WSL2, Ubuntu 20.04)

Steps to Reproduce:

1. Create directory foobar
2. code foobar
3. Create file foobar.py
4. Open foobar.py

Note: cannot select the interpreter for python as the selector is not visible:
<img width="1080" alt="Screenshot 2022-04-24 134557" src="https://user-images.githubusercontent.com/37503589/164972807-824aa149-04f0-4ab7-94d0-76432c9a1c2a.png">

Note2: It shows the text that it is activating an extension, but no error.

**Comment by WolfyzDev** [comment]
Another option is possible to add the Python interpreter, via the command palette.
Step 1: Go to the view tab at the top and press "Command Palette" (also accessible with the shortcut Control + Shift + P)
Step 2: Search for "Python"

![image](https://user-images.githubusercontent.com/93478889/164976180-1bc9ec59-98c8-47bf-aea3-2a49901c99b5.png)

Step 3: Click on the "Python: Select Interpreter" option
It will list the Python interpreters in your system and just select it. Sinom use the button "Enter interpreter path' and search in the files for the interpreter.

I know this doesn't replace the button but at least you can select the interpreter.

**Comment by WolfyzDev** [comment]
Did it work?

**Comment by thesalmonidae** [comment]
> Did it work?

Yes this works. I would have been very surprised if that would not have worked :-)
