### ISSUE TITLE
Emmet - Sass

### ISSUE THREAD

**Issue by EvgeniyJet** [microsoft/vscode#147975]
Мы скопировали необходимые данные в буфер обмена, так как у них был слишком большой размер для отправки. Вставьте эти данные.

**Comment by EvgeniyJet** [comment]
Emmet перестаёт работать в sass файлах , иногда снова работает, очистка настроек не помогает, перезапуск тоже

**Comment by EvgeniyJet** [comment]
Перестаёт работь с любыми файлами

**Comment by EvgeniyJet** [comment]
Emmet stops working in sass
  and any other files, sometimes it works again, clearing the settings does not help, restarting too

**Comment by rzhao271** [comment]
Do you have an example code snippet that I can use to confirm the issue, or an example screen recording? You can use https://gifcap.dev to create a GIF if necessary.
