### ISSUE TITLE
Weird window padding (again)

### ISSUE THREAD

**Issue by zethon** [microsoft/vscode#147917]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version: Version: 1.66.2 (Universal)
OS Version: macOS 10.15.7

I have a project that I've somehow gotten VSCode into a weird state. I have padding on either side of the editor, like so:

![image](https://user-images.githubusercontent.com/5203583/164711216-7444ae13-aafe-48ff-8891-991d6d261163.png)

I've already posted this issue once before but it was answered and closed, however the answer did not fix the issue, and I still believe this is a bug. I've created a video that illustrates the problem and also shows me trying what was suggested in #147637, the original issue:

https://youtu.be/_RZE_iGLNbU

I can resize the padding but not all the way so that it is gone.

**Comment by IllusionMH** [comment]
/question
/duplicate

Video doesn't contain steps that was posted as answer to your issue in https://github.com/microsoft/vscode/issues/147637#issuecomment-1102893928.
> You can use the layout controls button (top right of screen) to disable "centered layout". Or just run the command "View: Toggle Centered Layout"


You should either open **View** (in application menu) > **Appearance** > **Centered Layout** or run command in Command Palette <kbd>F1</kbd>
