### ISSUE TITLE
Markdown syntax highlighting broken by link with empty parenthetical title text

### ISSUE THREAD

**Issue by CAD97** [microsoft/vscode#147965]
Issue Type: <b>Bug</b>

Create a markdown file:

```markdown
[link](target ()), more text and [another link](target (with title text)).
```

The resulting syntax highlighting:

![image](https://user-images.githubusercontent.com/5992217/164878157-01595ded-09fd-4856-9e7d-8e8e59a2946c.png)

Scope inspector:

![image](https://user-images.githubusercontent.com/5992217/164878212-dfa74f10-4353-4fe9-89bb-b59b450e9eec.png)

The correct behavior is for the textmate scope `string.other.link.description.title.markdown` scope to cover just `()`, `)` to close the markdown inline link, and `,` to resume `meta.paragraph.markdown`.

Interestingly, the preview panel parses the link correctly.

![image](https://user-images.githubusercontent.com/5992217/164878272-b99d8c75-c407-483d-858c-76b1eee44591.png)

VS Code version: Code - Insiders 1.67.0-insider (72b4be55fad0d41092d7df8e03b5597c715fd2e2, 2022-04-22T06:27:20.290Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (18.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebug:30475216
pynewfile477:30451556

```

</details>

**Comment by CAD97** [comment]
This also occurs with `""` or `''` as title text.

Note that [the spec](https://spec.commonmark.org/0.30/#link-title) allows "zero or more characters between" the delimiters, so the preview panel is correct here, and the syntax highlighter is incorrect.

**Comment by CAD97** [comment]
I found the tm grammar repo and opened a sister issue there: https://github.com/microsoft/vscode-markdown-tm-grammar/issues/109

**Comment by mjbvz** [comment]
Thanks. Closing in favor of the upstream issue you opened
