### ISSUE TITLE
Rest $IFS to prior value

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#147939]
@meganrogge This PR leaves `$IFS` as the empty string in the shell, rather than as what it had before. Is there a reason that you don't save the value of `$IFS` before you change it and reset it afterwards rather than leaving it as the empty string? (Note also that "the empty string" is different in bash than "unset"; the latter leads to the default value of "space tab newline" and the former just means no splitting.)

I discovered this because this change means that shell integration breaks configuring `GIT_PS1_SHOWUPSTREAM` for the popular `git-prompt.sh` distributed with `git`, because this shell script [uses bash word splitting to parse the variable into words](https://github.com/git/git/blob/6cd33dceed60949e2dbc32e3f0f5e67c4c882e1e/contrib/completion/git-prompt.sh#L142-L148). Perhaps git-prompt.sh should set IFS explicitly but it does not. Permanently overriding `$IFS` in the shell seems like a mistake, right?

_Originally posted by @glasser in https://github.com/microsoft/vscode/issues/144779#issuecomment-1105952478_

**Comment by meganrogge** [comment]
to verify:

1. set `IFS` to something in your `bash_profile`

```
IFS=$'\n\n\n\n\n'
```

2. Set your `PROMPT_COMMAND` to something in your `bash_profile`
3. Verify via echo or other method that `IFS` is set to what you set it to in step 1.

**Comment by rchiodo** [comment]
/verified.

PROMPT_COMMAND needs to be set to repro.
