### ISSUE TITLE
golang 有些关键词提示不全，例如struct，return等

### ISSUE THREAD

**Issue by magic007** [Microsoft/vscode#14798]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: felixfbecker.php-debug-1.9.7, lukehoban.Go-0.6.47

Steps to Reproduce:

1.struct，return 无提示
2.

**Comment by rebornix** [comment]
Please file this issue to github.com/microsoft/vscode-go as it's go related.
