### ISSUE TITLE
Vs Code doesn't run at 144hz - everything feels like 60hz and choppy

### ISSUE THREAD

**Issue by realiti4** [microsoft/vscode#147978]
VS Code Version: Latest 1.66.2
OS Version: Windows 11 21H2
Hardware: 12600k, rtx 2060, 32gb ram, 4k 144hz monitor

Hi,

After upgrading to a 144hz monitor, I was really looking forward to use vs code, but it looks like it can't go above 60hz and scrolling experience is very choppy. I saw similar posts about this for linux and mac with some solutions, but can't find anything related to Windows. Also, it doesn't make any sense that why it wouldn't work since everything else and Chrome just work fine at 144hz on my system.

**Edit: I am updating my report.**

After further testing, Vs Code indeed supports 144hz. For example, extantion page's scrolling is buttery smooth. I think the issue here is that editor's minimap and scroll inputs are limited to 60hz for optimization, and this cause '60hz like' experience when draging minimap location on anything other than 60hz monitor. I think it'd be nice to enable this in settings for smoother experience for high refresh rate monitors.

**Comment by realiti4** [comment]
Hello,

Thanks for the improvement, I tried it on the insider build, but I think this only fixed the issue with minimap and scroll bar. They are refreshing at 144hz now, but main editor's movement still feels like 60hz.

**Comment by alexdima** [comment]
@realiti4 We're using [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) for rendering the editor:
> You should call this method whenever you're ready to update your animation onscreen. This will request that your animation function be called before the browser performs the next repaint. The number of callbacks is usually 60 times per second, but will generally match the display refresh rate in most web browsers as per W3C recommendation.

@deepak1556  Are you aware of any artificial limitation of `requestAnimationFrame` in Electron/Chromium?
