### ISSUE TITLE
the terminal.cwd priority can't override the default path of zsh profile

### ISSUE THREAD

**Issue by HomyeeKing** [microsoft/vscode#147999]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.66.2
- OS Version: arm64

Steps to Reproduce:

1. set the starting path of zsh by setting `cd <start path>` in `.zshrc`
2. when click the terminal icon in the status bar, the start path is the path specified in zshrc, not the `terminal.integrated.cwd`

can we make `terminal.integrated.cwd` higher priority?

**Comment by meganrogge** [comment]
We can't do this because your `.zshrc` file runs after we have set the cwd using `terminal.integrated.cwd` by definition since `.zshrc` runs on startup and we have no control over that

**Comment by HomyeeKing** [comment]
@meganrogge how about just make `terminal in staus bar` acts like  `Open in Termnial` in menu bar by default 
or making `terminal.integrated.cwd` more priority since I think the editor should have higher config 
![image](https://user-images.githubusercontent.com/49113249/165233642-a6969bb8-a344-4e55-8903-a75bc84031c7.png)
