### ISSUE TITLE
[c++] C++ syntax highlighting inconsistent in 0.10.0

### ISSUE THREAD

**Issue by Yelmond** [Microsoft/vscode#148]
The Improved Syntax Highlighting in 0.10.0 is nice in that it does more than a simple keyword match and comment detection. However, it seems to produce inconsistent colouring for C++ files.

All themes below use the default Dark theme that comes with VSCode and Visual Studio 2015. The default Light theme has the same problems. Actually, all themes I tried have the same inconsistencies except of course the colours themselves are different.

## The Problem ##

VSCode 0.10.0:
![image](https://cloud.githubusercontent.com/assets/178878/11263547/a7647352-8e59-11e5-90d3-41cf8d5be643.png)

Some specific concerns/issues:
1. Why is the `#include` and `#define` **pink**? I *really* hope this is not a new direction for the default VS Dark theme.
2. Why are the `if`, `return`, and `else` keywords **pink** but the `int`, `namespace`, and `class` keywords the good-old-VS **blue**?
3. Why are function names like `main()` and `do_stuff()` **yellow**, while their use **orange**?
4. Why are class names like `Foo` and namespace names like `space` using keyword **blue** colour?

## For Reference ##

VSCode 0.9 and below (it was simpler but at least it was consistent):
![image](https://cloud.githubusercontent.com/assets/178878/11263559/c61f1c34-8e59-11e5-83eb-070cfe597ecb.png)

Visual Studio 2015 (obviously can infer more about the language but this is what I'd expect from the default Dark theme):
![image](https://cloud.githubusercontent.com/assets/178878/11263567/dbe8445a-8e59-11e5-9c17-b7ffff63d2d5.png)

**Comment by maritz** [comment]
Yeah, even in Typescript there seem to be a lot of inconsistencies.

**Comment by JayXon** [comment]
And why are the two BLAH have different color?

**Comment by egamma** [comment]
@aeschli please verify what is still open from the above issues

**Comment by aeschli** [comment]
We replaced our tokenizers to text mate tokenizers. As these tokenizers create very different tokens, some of the colors changed unintentionally. I polished the light and dark theme to be in the spirit of what we had.
here's how it looks now (for the December release). I kept the yellow for function and method declaration.
![image](https://cloud.githubusercontent.com/assets/6461412/11481595/8b628d8a-979e-11e5-8528-9db5d58b0307.png)

**Comment by Yelmond** [comment]
Sorry, but it still seems inconsistent with Visual Studio itself. One of the (many) things I like about Code is that it _looks_ like Visual Studio right out of the box so I have a consistent experience on all 3 platforms. This is no longer the case.

My main issue is the use of the keyword color (in this case, blue) for the namespace and class names themselves (ie. "space" and "Foo"). This is rather confusing for me since the _use_ of a namespace and class name is not blue.

I also have a (more minor) issue with the use of yellow for function and macro names as that yellow is also used for constants (like 5 above). It's also equally inconsistent with namespace and class names as they are only colored yellow in their declaration/signature, not their use.

I'm not asking for anything as fancy as Visual Studio coloring. I think even leaving function, macro, namespace, and class names as white would be better than trying to color them this way.
