### ISSUE TITLE
Why my VS Code did't throw the typescript error ?

### ISSUE THREAD

**Issue by shezhangzhang** [microsoft/vscode#148032]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Darwin x64 19.6.0
- VS Code Typescript Version: 4.6.3

Steps to Reproduce:

Here is the original typescript code:
```typescript
enum Test {
    AA = 'aa',
    BB = 'bb'
}

Object.keys(Test).forEach((key) => {
    console.log(key, Test[key]);
});
```

In typescript official playground: 

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/26793777/165053097-c24055c6-e3fd-4319-a3d1-edfa54bb8545.png">

In vscode: (there were no error prompt)

<img width="592" alt="image" src="https://user-images.githubusercontent.com/26793777/165053804-2ec13cb3-3056-442b-8210-2a477094e99f.png">

**Comment by Lemmingh** [comment]
What's your TSConfig?

The TS Playground enables `noImplicitAny` by default. Do you also have it in your local environment?

**Comment by shezhangzhang** [comment]
> What's your TSConfig?
> 
> The TS Playground enables `noImplicitAny` by default. Do you also have it in your local environment?

Sure, solved my problem, thanks!

By the way, could the TS playground exposed the tsconfig? Because when I use it, I can't find its tsconfig.

**Comment by Lemmingh** [comment]
The Playground supports a portion of the compiler options, which are listed in the "TS Config" panel.

For more information, please see its Help:
https://www.typescriptlang.org/play#handbook-1
