### ISSUE TITLE
Test toggle inlay hints

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148040]
Refs: https://github.com/microsoft/vscode/issues/128162

- [x] anyOS @JacksonKearl
- [x] anyOS @lszomoru

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148040%0A%0A&assignees=jrieken)

---

There is a new settings for toggling inlay hints. Test that

* the global view menu has an entry to enable/disable inlay hints
* there is a new setting `editor.inlayHints.toggle` which allows to quick hide/show inlay hints

**Comment by IllusionMH** [comment]
Just small clarification - it is still expected that holding <kbd>Ctrl</kbd>+<kbd>Alt</kbd> will still treat them as pressed separately in the same time:
* <kbd>Ctrl</kbd> - activates "Go To ..." for parts of code
* <kbd>Alt</kbd> - alters scroll speed

I guess that <kbd>Ctrl</kbd> function is still required as <kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>Click</kbd> has existing behavior, however wasn't expecting to see scroll speed change.
