### ISSUE TITLE
Allow toggling Activity Bar / Status Bar in Zen Mode

### ISSUE THREAD

**Issue by xgdgsc** [microsoft/vscode#148022]
Does this issue occur when all extensions are disabled?: Yes 
 
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.15.0-25-generic

Steps to Reproduce:

1. open zen mode 
2. run ` toggle activity bar visibility` 

Some extensions have important function inside activity bar.  Unable to toggle activity bar in Zen mode is unproductive.

**Comment by sbatten** [comment]
At first I thought this was a regression from previous layout work, but I've determined that this is long standing behavior. I agree we can improve here, but it isn't happening immediately.
