### ISSUE TITLE
Comments panel: overview is broken when a snippet has <br> tags

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#148054]
![image](https://user-images.githubusercontent.com/485572/165117683-041492c6-6423-4cc1-a7ab-27e3b370a47f.png)

Below "Hi Laurent", the line with the number of comments is missing.

Using Chrome debugger tools, I see that the line is just pushed below and hidden. This happens when the comment snippet contains multiple `<br>` tags.

It should be possible to fix it by removing the `<br>` tags from the snippet (or by setting a height on `comment-metadata-container`).

cc @alexr00 @hermannloose

**Comment by rchiodo** [comment]
@alexr00 I'm not sure if I'm testing this correctly, but I don't see the `</br>` lines in the comments panel? You can just open that PR I added a link to.

This is the contents of the comment:
```
Don't mind this comment. I'm just testing issue: https://github.com/microsoft/vscode/issues/148054

</br>
</br>

More comments after br

</br>

Even more comments.
```

This is what I get in the comments panel:
![image](https://user-images.githubusercontent.com/19672699/165626633-8aa41ba3-88fd-467a-bfe6-e7894cb08a92.png)

**Comment by alexr00** [comment]
@rchiodo it looks like your test example would reproduce this issue.

To verify:
1. Install GHPRI pre-release
2. Open a folder with a GitHub repo
3. Open a file from a PR that you can leave comments in
4. Leave 2 comments, both of which have 2 newlines near the beginning of the comment. Something like this:
```
Hello

World
```
5. Verify that the comment view doesn't have an empty line in it (as the image in the original issue shows).
