### ISSUE TITLE
Test basic support for dropping files from the OS into custom trees

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#148046]
Refs: https://github.com/microsoft/vscode/issues/146734

- [x] macOS @roblourens 
- [x] linux @lramos15
- [x] windows @joaomoreno

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148046%0A%0A&assignees=alexr00)

---

The custom tree API only supports dropping strings, not files. For files, the file URIs are `toString`ed and dropped in the custom tree as `text/uri-list`. To verify, you can use your own extension with a tree that supports drag and drop, or you can follow the steps to use the tree sample:

1. Add `text/uri-list` to the `TreeDragAndDropController`'s `dropMimeTypes`:
https://github.com/microsoft/vscode-extension-samples/blob/92b34c5733e2d1640ad877e9ed4605da04709124/tree-view-sample/src/testViewDragAndDrop.ts#L6-L7

2. In `handleDrop`, get the `text/uri-list` from the drag and drop source:
https://github.com/microsoft/vscode-extension-samples/blob/92b34c5733e2d1640ad877e9ed4605da04709124/tree-view-sample/src/testViewDragAndDrop.ts#L60-L61

3. Log or set a breakpoint in `handleDrop` so that you can see that the uri list is correct. Docs for `text/uri-list`: 
https://github.com/microsoft/vscode/blob/26f019d9193924a94e59b21000c7fcc92ea94966/src/vscode-dts/vscode.d.ts#L9806-L9808

Using your sample, verify
- that you can drag a file from your OS into your custom tree and that the `text/uri-list` is correct.
- that you can drag several files from your OS into your custom tree and that the `text/uri-list` is correct.

**Comment by lramos15** [comment]
After speaking with @alexr00. This seems to be broken at the moment, unable to test will wait for fix and test again

**Comment by alexr00** [comment]
Yes, there's a bug here. Fix is https://github.com/microsoft/vscode/commit/32c8745ba7d7e3450523c3b5688b05c1ffa0e978 so we'll need to wait for the next build.

**Comment by roblourens** [comment]
It should be in today's build right? Not working for me in latest insiders - `sources.get('text/uri-list')` returns undefined.

**Comment by joaomoreno** [comment]
Same here. @alexr00

**Comment by alexr00** [comment]
New fix is in (e0dc61da20dc7aead439485538ab192fa5e74297) if you want to test out of source.

**Comment by joaomoreno** [comment]
Tested out of sources.

**Comment by lramos15** [comment]
@alexr00 Tested building out of sources. URI list is always undefined still for me.

**Comment by michaeljones** [comment]
I'm experiencing behaviour that I don't understand when having multiple files in a `text/uri-list` when dragging from a treeview using the `TreeDragAndDropController`. I've created an example of the issue here: https://github.com/microsoft/vscode-extension-samples/pull/628

Is that to be expected at the moment? Is it related to this ticket or should I create a separate ticket for it? 

I have a related issue that when I have a `TreeDragAndDropController` but nothing meaningful to drag from a particular node in the tree view then VS Code still allows the user to create a split-view in the editor with the drag action but there won't be anything in the new split when nothing has been set to the `DataTransfer` object. It would be nice to be able to indicate in the `handleDrag` function that there isn't anything meaningful to drag from the selected source. Maybe the cancellation token is for that but it seems like that is more for being told of a cancellation rather than cancelling the drag action from the `handleDrag`. Happy to create a ticket for that too if it seems reasonable. I hope I'm not cluttering up this thread but I don't want to create unnecessary duplication if there are known issues at the moment.

**Comment by roblourens2** [comment]
```
console.log(item.value);
console.log(await item.asString());
```

This logs undefined and the stringified URIs. I think that is what is expected right?

**Comment by lramos15** [comment]
Thanks for the pointer @roblourens I guess that's why I was confused as well.

**Comment by alexr00** [comment]
@michaeljones there are no known issues around tree drag and drop + `text/uri-list` right now. Glad to hear that you're trying it out! Please do file new issues for any problems that you encounter.

>It would be nice to be able to indicate in the handleDrag function that there isn't anything meaningful to drag from the selected source. 

That's what `dragMimeTypes` on your dnd controller is for. Do you tree elements have different mime types that they would like to transfer when dragged? We don't currently offer a way to specify this at the tree element level, only at the level of the whole dnd controller.

**Comment by michaeljones** [comment]
Thanks for the reply @alexr00 - I've made a ticket here about the `text/uri-list` issue that I've seen: https://github.com/microsoft/vscode/issues/148411

For the second part, we have a tree like this:
![image](https://user-images.githubusercontent.com/5390/166420582-f1404aec-c458-4d43-a84a-fd083421ae18.png)
Where we'd like the file items (like `dynamic_cmd.c`) to be draggable into the editor but there isn't anything intuitive to be done with the 'Size' item and the only option I can think of for the 'Application' item is to have it represent all the files underneath it. It would be great if we could have a drag for the file item but not for the others. 

At the moment if you drag the 'Size' item for which we don't attach any specific data to the `DataTransfer` then it'll still trigger a "Split view" action in the editor but create an empty panel when dropped in the 'split view target zone'.

Would it make be useful for me to create an issue about this?

**Comment by alexr00** [comment]
> At the moment if you drag the 'Size' item for which we don't attach any specific data to the DataTransfer then it'll still trigger a "Split view" action in the editor but create an empty panel when dropped in the 'split view target zone'.

We should not be creating an empty panel in this case. Instead, the drop should be a no-op. Yes, please do create a new issue for this, and thanks for using the new drag and drop support!

**Comment by michaeljones** [comment]
@alexr00 - thank you for the reply. I've created https://github.com/microsoft/vscode/issues/148622 for it.
