### ISSUE TITLE
Regression: Keybinding conflict for Command-E

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#148009]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0-insider (Universal), Commit: 72b4be55fad0d41092d7df8e03b5597c715fd2e2
- OS Version: macOS 12.3.1

### Bug description:

Command-E is by default bound to "Find with selection" (always has been). I use this shortcut many times every day.

As of bd95a8d451, it is also bound to "Detect language from content" (`editor.detectLanguage`). It seems that this takes precedence for some reason, so "Find with selection" no longer worked for me until I removed the key binding for "Detect language from content". It took me quite a long time to figure this out.

Please bind "Detect language from content" to something other than Command-E; this is a very common shortcut for all Mac applications (commonly called "Use selection for Find").

Cc: @JacksonKearl

**Comment by JacksonKearl** [comment]
Ah, my bad. I disabled that binding locally so when I searched for existing items I didn't find any.

**Comment by bpasero** [comment]
I don't think we allow `Alt` keybindings though, because it is the key to bring up the menu?

**Comment by JacksonKearl** [comment]
We have a bunch of existing ones... not sure about any warnings
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/8586769/165142851-51bec22a-2d56-4d93-b981-e85f74330e24.png">

**Comment by JacksonKearl** [comment]
Using Alt+Shift+D after conversation with @sbatten
