### ISSUE TITLE
Terminal links should support WSL folders

### ISSUE THREAD

**Issue by karolzlot** [microsoft/vscode#148062]
This text in terminal should be clickable and open Windows explorer with WSL path:
```
//wsl$/Ubuntu/tmp/tmpxjck8ple
```

Currently it isn't clickable.

Similar issue to: https://github.com/microsoft/vscode/issues/102638

**Comment by Tyriar** [comment]
Code pointers for anyone who wants to help out with a PR:

- Where I'd expect these links to get detected: https://github.com/microsoft/vscode/blob/6aea4eba61b6b03a39c1e22c3fd44387a377448e/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts
- Where links get handled: https://github.com/microsoft/vscode/blob/6aea4eba61b6b03a39c1e22c3fd44387a377448e/src/vs/workbench/contrib/terminal/browser/links/terminalLinkOpeners.ts#L34-L47
