### ISSUE TITLE
Impove the native Monokai theme with better syntax highlighting for Terraform

### ISSUE THREAD

**Issue by jolsby** [microsoft/vscode#148013]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66.2
- OS Version: WSL2 Ubuntu-18.04

Steps to Reproduce:

1. Natively activate the native Monokai theme provided by Microsoft. 

- **Identifier** `vscode.theme-monokai`

3. Observe the difficult to read syntax highlighting for .tf files.

- Repeating underlying for all resources, no display of var and other attributes during calls, heavy use of red coloring which is hard on the eyes, no showing nested inputs for various resources, etc. 
- Added slight white differences and bolding to separate names resources, vs. assigned attributes

I have made changes based better highlight syntax which can be found in this [repo](https://github.com/jolsby/monokai-terraform-vscode).  I merely improved what already existed.

**Comment by aeschli** [comment]
We don't really want to tune theme for specific grammars & languages. Especially not the themes that were originally authored by others (Monokai, Solarize,...)
Instead, you want to look at the Terraform grammar and what scopes it generates. Using standard scopes will improve rendering for all themes.
