### ISSUE TITLE
vs code automatically importing python module 

### ISSUE THREAD

**Issue by Defcon404** [microsoft/vscode#148026]
Hi,

Whenever I open my python file and run my script, vs code seems to automatically insert some python module in my script without my
permission or knowledge. It seems to insert different modules in different scripts automatically. Later on, I have to manually remove these modules (which is not required to run my scripts).
Note: I am not talking about the vs code, Code auto-completion feature which is awesome.

Is this a BUG or a feature that I can turn off? 
Please Help

Thank You

**Comment by WolfyzDev** [comment]
Hi!
If I understood correctly, vs code automatically modifies Python files at runtime, is that correct?
Have you installed any extensions to vs code regarding Python?
And a small question (while we're at it): are the modules always the same and if so which ones?
