### ISSUE TITLE
Support before() and after() for tests

### ISSUE THREAD

**Issue by akamud** [Microsoft/vscode#1480]
I assumed VSCode used [Mocha](https://mochajs.org/) for testing, which supports `before` and `after` functions, but when I use them and I launch my tests (F5) I always get an exception like VSCode does not understand neither of these functions.

This is the relevant snippet in my test code:
```javascript
suite("Can I Use Tests", () => {
	before((done) => { // VSCode throws an exception in this line
        // setup
        done();
    });
	
	test("test1", () => {
        // some test
    });
});
```
This is the error logged in the console:
```
ReferenceError: before is not defined
```
If I run my tests using Mocha, they run just fine.

Is this a bug or am I misunderstanding something?

**Comment by bpasero** [comment]
@akamud try with `setup` and `teardown` instead.

**Comment by egamma** [comment]
@akamud you can also configure mocha to use `bdd` instead of `tdd` in test/index.ts.

```typescript
testRunner.configure({
	ui: 'bdd', 		// the TDD UI is being used in extension.test.ts (suite, test, etc.)
	useColors: true, // colored output from test results
	timeout: 5000
});
```

**Comment by akamud** [comment]
Thank you for making it clear, so VSCode *is* using Mocha, I just mixed BDD with TDD.
