### ISSUE TITLE
Mouse selection is not working

### ISSUE THREAD

**Issue by Anoop74** [microsoft/vscode#148024]
Issue Type: <b>Bug</b>

Mouse selection is not working

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.36GB free)|
|Process Argv|--crash-reporter-id 6abcceab-0082-4b4c-8dc8-1d7ee64b5eb8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-eslint|dba|2.2.2
python-preview|don|0.0.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
code-runner|for|0.11.7
search-node-modules|jas|1.3.0
vscode-codemetrics|kis|1.24.0
kite|kit|0.147.0
node-module-intellisense|lei|1.5.0
mongodb-vscode|mon|0.9.2
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1
cpptools|ms-|1.9.8
debugger-for-chrome|msj|4.13.0
awesome-flutter-snippets|Nas|3.0.3
vscode-for-node-js-development-pack|nod|2.0.1
java|red|1.5.0
LiveServer|rit|5.7.5
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.34.2
vscode-maven|vsc|0.35.1
nodejs-extension-pack|wad|0.1.9
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by DonSudheera** [comment]
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

more information needed

**Comment by alexdima** [comment]
* run `F1 > Help: Start Extension Bisect`
* (this will restart VS Code with half of your extensions disabled)
* try to do the steps which reproduce the problem
* if the problem reproduces, click "This is bad" (this narrows down the problematic extension to the half which was enabled)
* if the problem does not reproduce, click "Good now" (this narrows down the problematic extension to the half which was disabled)
* these steps will repeat until the problematic extension is found

| initial | step | final |
|---|---|---|
| ![image](https://user-images.githubusercontent.com/5047891/101918658-e9170f80-3bc9-11eb-9977-857baa291937.png) | ![image](https://user-images.githubusercontent.com/5047891/101918683-ef0cf080-3bc9-11eb-9f9e-98b0177991b2.png) | ![image](https://user-images.githubusercontent.com/5047891/101918706-f502d180-3bc9-11eb-8c86-e56355958bd4.png) |
