### ISSUE TITLE
Use language status item to show formatter conflicts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148053]
The can be multiple formatters installed per file, this often happens for JS/TS files after installing prettier. In such cases one formatter must be picked as default. Prompting for that is pretty aggressive when explicitly invoking format (modal dialog) but the conflict UI is very subtle when formatting automatically, e.g on save. In such flows we cannot show a modal and use a status bar message and silent notification instead. This isn't working so well (see https://github.com/microsoft/vscode/issues/146544 and related) the issue is about using the language status item to show format conflicts

**Comment by jrieken** [comment]
This is how it looks atm

<img width="657" alt="Screenshot 2022-04-25 at 17 23 05" src="https://user-images.githubusercontent.com/1794099/165120975-ef3e8136-ab39-4383-ad54-8f39d23d90bd.png">

**Comment by rzhao271** [comment]
I installed Prettier and switched to a JSON file and confirmed the error indicator shows up.
But, after selecting a default filter, the error indicator still shows.
