### ISSUE TITLE
Initialize Repository Not Responding

### ISSUE THREAD

**Issue by saxamrawat** [microsoft/vscode#148023]
Issue Type: <b>Bug</b>

I cannot turn on source control, since the Initialize Repository function is not responding.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (11.28GB free)|
|Process Argv|--crash-reporter-id 9cc4f877-7394-47df-be6b-a561937da51d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
gitignore|cod|0.7.0
doxdocgen|csc|1.4.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.0.6
code-runner|for|0.11.7
better-cpp-syntax|jef|1.15.13
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
cmake|twx|0.0.17
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by miguelc1221** [comment]
for what is worth I was having the same issue, used Bisect and found that https://marketplace.visualstudio.com/items?itemName=steoates.autoimport was the culprit.

**Comment by charlesdeb** [comment]
I have the same problem. The "initialise repository" does not seem to do anything in the UI - even though when I check the file system it is creating a repo. However, even after closing and reopening VScode, it doesn't seem to recognise this repo, and still shows the "initialise repo" button.

I used the bisect thing, and even with all extensions turned off (I am using 57 of them), I am still not seeing the repo in VS code. I have 4 folders in my current workspace. When I open another workspace, git within vscode appears to be working fine - so presumably there is something weird about this current workspace. But what? How can I trouble shoot this?

**Comment by charlesdeb** [comment]
Found the problem:

```
$ git status
fatal: unsafe repository ('/media/edrive/Documents/folder-x' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /media/edrive/folder-x
```
and the suggestion fixed it

**Comment by holytshirt** [comment]
This seems to be a folder permissions issue. Either Git or VSCode has changed something recently.
```
Version: 1.66.2 (system setup)
OS: Windows_NT x64 10.0.19044
Git: git version 2.36.0.windows.1
```

If I clone a repo and the process is running as administrator the owner of the folder is .\Administrators and this issue occurs.
![image](https://user-images.githubusercontent.com/90132/166943273-6a8e2286-affe-4154-9bc4-c78d1329e1df.png)

If I clone a repo and the process is *NOT* running as administrator the owner of the folder is .\Me and everything works fine.
![image](https://user-images.githubusercontent.com/90132/166942557-0e48a752-ce43-4268-9e56-a749219098fc.png)

So changing the folder owner to yourself fixes the issue to. So stop cloning or creating git repos while running as administrator seems to be the moral of the story 😃

**Comment by lszomoru** [comment]
This is due to [a change in behaviour](https://github.blog/2022-04-12-git-security-vulnerability-announced/) in the way git discovers repositories. I will close the issue accordingly.
