### ISSUE TITLE
UTF8bom files do not open as UTF8 after fix in #39084

### ISSUE THREAD

**Issue by Raydir** [microsoft/vscode#148025]
Issue Type: <b>Bug</b>
As mentioned in https://github.com/microsoft/vscode/issues/127936 this fix does not work for me.

In my extension "f-script" files.encoding is set to OEM850.
After the fix from #39084 this is working also when files are opened directly with no runnig instance of VSCode (as described in the mentioned Issue).

Regression:
Files that are explicit saved as UTF8BOM are opened also in OEM850 now -> this has changed.

Steps to reproduce:

1. set files.encoding in an extension to e.g. OEM850 
2. close all instances of VSCode / Insider
3. via context menu open a UTF8bom saved file within "insider" 
4. file is opened as "pseudo-OEM850", BOM stands there as text...

![image](https://user-images.githubusercontent.com/17499573/165025770-2ded871c-2121-450c-843c-340454e9ac87.png)

----

VS Code version: Code - Insiders 1.67.0-insider (72b4be55fad0d41092d7df8e03b5597c715fd2e2, 2022-04-22T06:27:20.290Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (21.02GB free)|
|Process Argv|H:\\Insyde\\FF\\HO-CatEnterpriseSearch-02.v614.ff --crash-reporter-id 7225540c-8dfb-4d99-8bb4-c4faee480e6c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
Bookmarks|ale|13.2.4
vdf|ali|0.3.2
tsl-problem-matcher|amo|0.6.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.24
windows-explorer-context-menu|ele|3.2.1
vscode-npm|fkn|3.3.0
gc-excelviewer|Gra|4.2.54
todo-tree|Gru|0.0.215
ilspy-vscode|ics|0.13.1
easy-icons|jam|0.3.1
vscode-language-pack-de|MS-|1.67.0
vscode-dotnet-runtime|ms-|1.5.0
cpptools|ms-|1.10.0
opacciconbar|Opa|0.0.1
f-script|Opa|17.0.1
opacc-fscript-debug|Opa|16.20.1
webapplicationservices-language-server|Opa|6.14.0
jsdoc-live-preview|Per|2.0.0
qub-msbuild|qub|0.6.3
snippets-viewer|Ran|1.9.0
testcafe-test-runner|rom|2.1.1
testlatte|ssh|2.1.2
msbuild-tools|ste|0.0.12
addDocComments|ste|0.0.8
vscode-sftp|sun|1.1.1
msbuild-project-tools|tin|0.4.3
snippets-view|use|0.2.10
cursorCharCode|zei|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebugcf:30475217
pynewfile477:30451556

```

</details>

**Comment by Raydir** [comment]
UTF8bom:
Variation of UTF8 that explicit defines a byte order mark (first 3 bit in a file), so editors can check against it to verify that the file is UTF8 without "guessing".

**Comment by bpasero** [comment]
The same issue is present also for UTF16-LE and UTF16-BE. I pushed a change to never change the encoding when opening a file and we have an encoding that we can detect 100%. The only encodings we can detect 100% are: UTF8 with BOM and UTF16 LE/BE.

**Comment by Raydir** [comment]
@bpasero  "should" that fix be already in the actual insider build?

**Comment by Raydir** [comment]
@bpasero the fix does work for Files that are less than 12Kb as it seems.
[TEST.zip](https://github.com/microsoft/vscode/files/8561150/TEST.zip)

**Steps to reproduce**
In the zipfile attached, I added 5 Files that are related to my Extension: 
> OpaccSoftwareAG.f-script

if you click on OEM850.FF, OEM850.FX, UTF8bom.FF or UTF8bom.FX everything is fine.

The file OEM850_false.FX is the same as OEM850.FX but the included Text is copied several time (until ~12Kb)
When the Text within the file is reduced lower than 11Kb it seems to work again.

It seems for me, that the file is tried to be loaded completely --> it would be enough to only read the 3 first bit for UTF8bom

https://stackoverflow.com/a/19283954 could be of help for a proper solution.

Thanx for your work
Roman

**Comment by bpasero** [comment]
@Raydir I do not think there is a bug in VSCode, the UTF-8 BOM detection (and UTF16 btw) work by reading the first bytes of the file, you can see the code in action here:

https://github.com/microsoft/vscode/blob/62b0d5cb815aa8161ffdb6550ed1787e4bffdd17/src/vs/workbench/services/textfile/common/encoding.ts#L413

Proof:
![Recording 2022-04-26 at 10 25 58](https://user-images.githubusercontent.com/900690/165256483-45065333-8484-4f11-ad92-de8a453e5044.gif)

**Comment by Raydir** [comment]
https://user-images.githubusercontent.com/17499573/165261730-f8c705be-8d77-44ed-a928-a2bd6046347b.mp4

**Comment by bpasero** [comment]
To clarify, the only setting you have is:

```json
"[hlsl]": {
    "files.encoding": "cp850"
}
```

Right? No other encoding or auto-guess encoding setting?

**Comment by Raydir** [comment]
no user settings except the colorisation and those are the defaults for f-Script:

`		"configurationDefaults": {
			"[f-script]": {
				"files.encoding": "cp850",
				"files.autoGuessEncoding": false,
				"editor.fontFamily": "Courier New,monospace",
				"editor.fontSize": 14,
				"editor.fontWeight": "bold",
				"editor.folding": true,
				"editor.showFoldingControls": "always",
				"editor.autoIndent": "advanced",
				"editor.codeLens": true,
				"editor.lineNumbers": "on",
				"editor.tabSize": 4,
				"editor.insertSpaces": false,
				"editor.mouseWheelZoom": true,
				"editor.renderLineHighlight": "gutter",
				"editor.dragAndDrop": true,
				"editor.matchBrackets": "always",
				"editor.colorDecorators": true,
				"editor.cursorBlinking": "phase",
				"editor.quickSuggestions": {
					"other": true,
					"comments": false,
					"strings": false
				},
				"editor.quickSuggestionsDelay": 600,
				"editor.wordBasedSuggestions": true,
				"editor.snippetSuggestions": "bottom",
				"editor.acceptSuggestionOnEnter": "off",
				"editor.wordSeparators": "`~!@#$%^&*()-=+[{]}\\|;:'\",.«»<>/?"
			}`

**Comment by Raydir** [comment]
-> autoguess ist "explicit" to false

**Comment by Raydir** [comment]
the loading time of newly opened files seems also to be much slower now btw.
>File > Open File

**Comment by bpasero** [comment]
I cannot reproduce. It shows initially as UTF-8 which is the default, but then switches to the right encoding.

![Recording 2022-04-26 at 11 13 21](https://user-images.githubusercontent.com/900690/165266171-596b538a-b30b-4352-87a5-d31327a4e217.gif)

🤷

**Comment by Raydir** [comment]
Is there a way to "debug" the loading behaviour?  
For me it seems that it "does work" in 1 out of 10 tries...

Perhaps you can reproduce as follows:

1. open UTF8BOM.FX by click in windows editor
2. close vscode insider
3. open OEM850_false.FX by click in windows editor


Did you try with my extension?
-> there is a very large amount of syntax-highlighting Code that is loaded by the extension... is it possible that the loading takes to long and thus the encoding does not load fast enough?

**Comment by Raydir** [comment]
the above steps to preproduce result always in false encoding.
If i do not open a UTF8Bom file in advance it seems to work somehow.

> not opening a utf8bom file in advance means that i "wait some seconds" until opening the next file..
perhaps there is some "

**Comment by Raydir** [comment]
> does also occure when started via CMD

Difference could also be, that I am working on a windows 10 machine perhaps (i dunno if this matters)

**Comment by Raydir** [comment]
That's right, UTF8bom seems to be fine now.

But it does have something to do with the original issue, since the problen is/was that the encoding set as default by the extension is not used (for bigger files).

At the moment it is worse than before since it works "sometimes" what can lead to even more problems than before. If its always false its even better thsn if its buggy sometimes (my point of view).


I'll try to test  the problem tomorrow again, töby reducing settings, other Extensions..

Regards


Holen Sie sich Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Raydir** [comment]
I tried the following steps:

**Deaktivate all other Extensions**
_> No change in behaviour > Problem remains_

----

**De-Installation of VSCode Insider on Win 10 client**
- New installation of VSCode Insider 
- New Installation of F-Script Extension
_> No change in behaviour > Problem remains_

----
 
**Clean Windows 11 Client** 
- Install Insider Build
- Install F-Script Extension
- Test Files
Problem does not occure...

----

**De-Installation and manually delete \appdata\roamong\code-insiders\ **
- New Installation of VSCode Insyder
- New Installation of F-Script Extension
- _Problem does not occure anymore_ 


---- 
While trying to reproduce i mentioned that if you press "any key" while the file is loaded, the file is changed and thus stays in UTF8.

So problem seems to be fixed with a clean installation... 
But perhaps it would be better if the file could not be changed during load process, since that would cripple the file encoding.

 guess you could "force" the problem

**Comment by bpasero** [comment]
> While trying to reproduce i mentioned that if you press "any key" while the file is loaded, the file is changed and thus stays in UTF8.

To clarify: you change the file right when it opens so that it is dirty? But in that case we cannot change the encoding because the file has already been loaded from disk and modified by you? Are you saying this issue does NOT reproduce when you don't change the file? Why do you need to change the file right on startup?

**Comment by Raydir** [comment]
No i did not say that.
I did not change a file myself when i created this issue...
The problem was related to something in my AppData -> After killing AppDate completely everything is fine.


I just mentioned, that this problem ALSO occures when you press a Key during VSCode Startup/File open).
I don't need to change the file - that was just something i did during tests.

**Comment by bpasero** [comment]
Ah ok nice! I cannot explain what could cause this, but todays insider build will have some additional logging if you run `code-insiders --verbose`.

**Comment by Raydir** [comment]
not sure if i get the problem again - since i killed my AppData but  i gonna love the --verbose command.

I have to give coding-lessons for our script-language today, but i'll check the new command tomorrow/tonight.

**Comment by Raydir** [comment]
@bpasero  since i killed my AppData the problem does not happen once - i guess this did solve the problem somehow.
Logfile:
[log.txt](https://github.com/microsoft/vscode/files/8588403/log.txt)

Should the problem occure again somethimes I'll open a new Issue with the verbose-log -> could be useful for something else i guess! :)

Thanx
