### ISSUE TITLE
double or more thai vowel are not show in VSCode editor

### ISSUE THREAD

**Issue by SajjaAtikij** [microsoft/vscode#148020]
Issue Type: <b>Bug</b>

1. Open VSCode 
2. new File , then type any thai double thai vowel e.g. { ่, ้, ๊, ๋ } 
3. In editor are combine in one vowel but file are save correctly.

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<!-- generated by issue reporter --
<img width="836" alt="Screen Shot 2565-04-25 at 10 16 32" src="https://user-images.githubusercontent.com/104336867/165015010-b9def4fc-1fbd-447f-97d6-0a0eac5cb49a.png">
>

**Comment by alexdima** [comment]
@SajjaAtikij Could you please provide an example word which uses these characters that I can copy-paste? How does this word render in TextEdit? How does it render in vscode?

**Comment by SajjaAtikij** [comment]
1. example word are below:-
ดีีีีีี
ปีีีีีี
ที่่่่่่

2. In Text editor and search bar in VSCode: multiple thai vowel (upper character) see picture
https://user-images.githubusercontent.com/104336867/165156955-7cee7f81-eada-4590-92e5-b0c7ce07d3d1.png

<img width="168" alt="Screen Shot 2565-04-26 at 02 05 54" src="https://user-images.githubusercontent.com/104336867/165156955-7cee7f81-eada-4590-92e5-b0c7ce07d3d1.png">

3. In VScode editor  (macOS): combine in one vowel see picture 
https://user-images.githubusercontent.com/104336867/165157334-f21b8e7b-d510-49b4-86b5-3d22f09959fa.png

<img width="231" alt="Screen Shot 2565-04-26 at 02 08 40" src="https://user-images.githubusercontent.com/104336867/165157334-f21b8e7b-d510-49b4-86b5-3d22f09959fa.png">

**Comment by alexdima** [comment]
This is controlled by the font that is used. e.g. configuring `"editor.fontFamily": "Arial"`:
<img width="88" alt="image" src="https://user-images.githubusercontent.com/5047891/165158519-256f9d80-0aa0-4b7f-96e8-7adaf75aa0a8.png">
`"editor.fontFamily": "Fira Code"`:
<img width="61" alt="image" src="https://user-images.githubusercontent.com/5047891/165158566-836d9735-508d-47fa-87ef-8872322a5815.png">
I can recommend to switch to a font that better renders these characters if monospace fonts are not good enough.
