### ISSUE TITLE
Negation of negative (double negatives) in settings

### ISSUE THREAD

**Issue by s130059660** [Microsoft/vscode#14808]
- VSCode: Latest Insider 1.7:
- OS Version: Any

Hi,

Do you think this double negatives in VSCode settings:
`"typescript.disableAutomaticTypeAcquisition": false`

Should be re-worded to positive one like:
`typescript.AutomaticTypeAcquisition": true`
or 
`typescript.EnableAutomaticTypeAcquisition": true`
or 
`typescript.AcquireTypeAutomatically": true`

**Comment by Bill-Stewart** [comment]
FWIW I agree. I think "disable"s should be `false` and "enable"s should be `true`. This is less confusing.

**Comment by dbaeumer** [comment]
It is called disableAutomaticTypeAcquisition since TS calls it the same way. I would like to keep it that way to not confuse people. And I try to make the absence of a setting correspond to the falsy value.
