### ISSUE TITLE
Docs say no JavaScript linter comes with VSCode, but it's still linting (and doing it wrong in *.cshtml)

### ISSUE THREAD

**Issue by ruffin--** [microsoft/vscode#148065]
Issue Type: <b>Bug</b>

1. Open VSCode with no extensions with `code --disable-extensions`.
2. Create a JavaScript file. Say `c:\temp\temp.js`
3. Enter the following code in `temp.js`:

```
var
```

4. Select "View >>> Problems" from the menubar.
5. See linting error reported, "Variable declaration list cannot be empty."
6. Look at VSCode docs here: [https://code.visualstudio.com/docs/languages/javascript#_linters](https://code.visualstudio.com/docs/languages/javascript#_linters)
7. Note quote: 
    * "_While VS Code does not include a built-in JavaScript linter, many JavaScript linter extensions available in the marketplace._"
8. Be confused what's reporting an error.
9. Have no idea how to turn this off.

![showing state in vscode describe in steps, above](https://user-images.githubusercontent.com/5659878/165138446-1e1ba98c-6ab4-49f1-b9b2-fe9d34272147.png)

---

### Actual, not simplest, use case (and [StackOverflow question to match](https://stackoverflow.com/questions/71973401/turning-off-misidentified-experimental-decorators-linting-errors-in-cshtml-raz)): 

I have cshtml files where whatever is doing this linting reports...

"Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option in your 'tsconfig' or 'jsconfig' to remove this warning.".

... for value Razor template comments in the form 

```
@* This is my comment in Razor template format *@
```
I use eslint to lint elsewhere. I need this turned off.

![showing cshtml/Razor template error](https://user-images.githubusercontent.com/5659878/165138607-9f9e9b36-fbd4-439a-899c-b2ce784ee276.png)

---

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (13.01GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 10d9d6b4-285d-425e-8f68-9113effa0ab4|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by IllusionMH** [comment]
That's not separate linter such as ESLint, but VS Code comes with bundled JS/TS support and it reports errors including syntax errors.

Problem in your case is that `.cshtml` files are treated as usual HTML files(see HTML in status bar) which and if you use `<script>` tag without `type` attribute or with `application/javascript` VS Code will treat it content as regular JS and will report obviously invalid JS Syntax.

In general case - you should check for extension that will provide proper support for razor templates (should be supported by C# extension which should treat them as "ASP.NET Razor" instead of "HTML") and  will account for that syntax.

**Not recommended way** - search for settings with "validate" in them.

**Comment by ruffin--** [comment]
@IllusionMH Thanks for the kick in the pants. Yeah, I stumbled over the not recommended solution (setting `html.validate.scripts` to false) earlier today for my cshtml issue, and I think I crept closer to the recommended a bit (both covered in [my answer to my own question on SO](https://stackoverflow.com/a/72003399/1028230)), if only by saying I bet it's related to my `"files.associations"` settings which considers cshtml as html [for other extensions to play usefully with Razor templates].

Sure enough, that does work -- if I remove both `"html.validate.scripts": false,` and...

```
  "files.associations": {
    "*.cshtml": "html"
  },
```

from settings, the errors disappear. 

But I'm now not getting _any_ script parsing in cshtml now.

So I'm still not sure how to get cshtml and script parsing to play together nicely, but otherwise it's working.

I'll close.

**Comment by IllusionMH** [comment]
I think it's best to check existing docs for C# extension to see if there is existing solution or open new issue there (if there isn't one).

I don't think that there is any solution possible for plain HTML(with embedded JS) to have invalid JS syntax and still have adequate suggestions. Extension that handles these files should provide support for both: razor syntax and, probably, embed JS parts.
