### ISSUE TITLE
Terminal: option+click off by ~3 characters

### ISSUE THREAD

**Issue by collinanderson** [microsoft/vscode#148061]
Issue Type: <b>Bug</b>

In the regular MacOS terminal (outside Visual Studio Code), option+click will move the cursor to a given point in the text. This is nice for editing the middle of a long command line, or for moving around vim.

However, when the MacOS Terminal is being run inside Visual Studio Code, when I option+click text, the cursor moves _close_ to where I clicked, but it's off by about 3 characters.

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:38:17.605Z)
OS version: Darwin arm64 21.1.0
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-105-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.47GB free)|
|Process Argv|--crash-reporter-id e3955928-6bb2-4744-a03c-d22a56f2c7b0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: ***|
|OS|Linux x64 5.4.0-105-generic|
|CPUs|AMD EPYC 7542 32-Core Processor (4 x 2899)|
|Memory (System)|7.77GB (3.09GB free)|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-ssh|ms-|0.70.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
references-view|ms-|0.0.89

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by meganrogge** [comment]
Does not reproduce in the xterm.js demo

**Comment by meganrogge** [comment]
shouldn't the padding be on the cursor layer?

**Comment by Tyriar** [comment]
I think this rule is the problem but haven't looked into it:

![image](https://user-images.githubusercontent.com/2193314/166746902-bc7a65e5-e620-47c9-90f1-ccdb399bfebf.png)

We recently moved the padding from `.terminal-wrapper` to `.terminal` I think which would explain the regression
