### ISSUE TITLE
Not readily reflected.

### ISSUE THREAD

**Issue by h-shino** [microsoft/vscode#148092]
Issue Type: <b>Bug</b>

Selecting browse -> repository from here is not immediately reflected in the workspace.
When I close the workspace and reopen it, it is reflected.
This was not a problem in previous versions.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.57GB free)|
|Process Argv|--crash-reporter-id e6c4610b-18f0-42ee-8a53-dbc5b0693a37|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
Bookmarks|ale|13.2.4
numbered-bookmarks|ale|8.2.0
code-gnu-global|aus|0.2.2
vscode-opennewinstance|chr|0.0.12
doxdocgen|csc|1.4.0
githistory|don|0.6.19
gitlens|eam|12.0.6
git-project-manager|fel|1.8.2
asciidecorator|hel|0.2.0
vscode-edit-csv|jan|0.6.8
better-cpp-syntax|jef|1.15.13
binary-viewer|mom|0.0.1
vscode-language-pack-ja|MS-|1.66.3
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
uwsc-support|nal|0.0.3
vscode-print|pdc|0.9.14
code-settings-sync|Sha|3.4.3
vscode-hexdump|sle|1.8.1
numbermonger|sof|0.5.0
vscode-workspace-explorer|tom|1.5.0
cmake|twx|0.0.17
hex-ascii-converter|yrp|0.0.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by h-shino** [comment]
Please give me some time.
I will summarize the procedure.

**Comment by h-shino** [comment]
Please see attached documents.
[Fault phenomenon.pdf](https://github.com/microsoft/vscode/files/8704122/Fault.phenomenon.pdf)

**Comment by lszomoru** [comment]
@h-shino, thank you very much for the document and apologies for not getting back to you on this until now. I have looked at the document and based on the provided screenshots, it looks like the problem that you are experiencing is related to a feature that is contributed by the GitLens extension. I would recommend that you file this issue in [the extension's repository](https://github.com/gitkraken/vscode-gitlens). Thank you!
