### ISSUE TITLE
Keep it Simple

### ISSUE THREAD

**Issue by madhaven** [microsoft/vscode#148029]
Issue Type: <b>Feature Request</b>

One of the primary reasons I shifted to VSCode was because of its simplicity and minimalist UI.  
*IT HAD ONLY THAT WHICH WAS NEEDED*  
Of course everyone had the options to add features that they wanted.
*THIS WAS CLEAN*

I just downloaded the latest release and I noted some features that seriously impact my workflow and comfort with VSCode.
* The ugly icons on the top, beside the minimize buttons: Seriously ? IS  there ANY WAY I could get rid of that !?
* I like the source control highlights on editors but why do you have to give it texture and make it so kiddish? stick to solid colors guys.

I LOVE vscode. Would really appreciate it if you could keep it simple.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
> * The ugly icons on the top, beside the minimize buttons: Seriously ? IS  there ANY WAY I could get rid of that !?

Documented at https://code.visualstudio.com/updates/v1_65#_new-layout-control-options

Configurable with `workbench.layoutControl.enabled` and `workbench.layoutControl.type`

> 
> * I like the source control highlights on editors but why do you have to give it texture and make it so kiddish? stick to solid colors guys.

https://code.visualstudio.com/updates/v1_66#_updated-source-control-decorators explains that it was done for accessibility.

Configurable in 1.67 (current Insiders) - `scm.diffDecorationsGutterPattern`

**Comment by misolori** [comment]
Thanks @gjsjohnmurray for providing the settings for these and thanks @madhaven for the feedback. Given that these are changeable via settings I'll go ahead and close out this issue.
