### ISSUE TITLE
Test API proposal for cross extension host extension info

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148039]
Refs: https://github.com/microsoft/vscode/issues/145307

- [x] anyOS @aeschli 
- [x] anyOS @DonJayamanne

Complexity: 3
Authors: @alexdima @jrieken 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148039%0A%0A&assignees=jrieken,alexdima)

---

There is a new API proposal to read extension information from all extension host: [vscode.proposed.extensionsAny.d.ts](https://github.com/microsoft/vscode/blob/ad4470522ecd858cfaf53a87c2702d7a40946ba1/src/vscode-dts/vscode.proposed.extensionsAny.d.t). Write a web extension that exercises the API, test that

* you can read extension information from all extensions across all extension host
* the extension locations are correct and make sense in their contexts (right uri-scheme)
* you cannot access API (`exports`) from an extension on another extension host
* you can active extensions from anywhere, their activation status is correct
* think about the chosen names 
* verify the doc makes sense 

---

* [Create an extension guide](https://code.visualstudio.com/api/get-started/your-first-extension)
* or start [Extensions samples repo](https://github.com/Microsoft/vscode-extension-samples)
* Add a proposed API:
  * First add the proposed API to the `package.json` (see below)
  * Then run `npx vscode-dts dev` to get the typings
```json
	"enabledApiProposals": [
		"extensionsAny"
	],
```
> Note the name of the proposed API is gathered from the [file name in the vscode-dts folder](https://github.com/microsoft/vscode/tree/main/src/vscode-dts)

**Comment by aeschli** [comment]
All looks good. Tested the new APIs and verified that the properties on `Extension` make sense
Tested on local and remote desktop, code-server web, web serverless.

**Comment by aeschli** [comment]
@DonJayamanne  I used the following test extension: https://github.com/aeschli/ext-all-extensions if you want to build on this.
