### ISSUE TITLE
`--do-not-sync` server argument is ignored when installing extensions

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#148011]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: insiders and from sources

Steps to Reproduce:

1. Ensure you have settings sync already enabled or run server and enable settings sync
2. Run server again with `./scripts/code-server.sh --without-connection-token --install-extension znck.vue --do-not-sync --start-server`
3. :bug: Observe extension `znck.vue` gets synced

cc @sandy081

**Comment by jeanp413** [comment]
Created PR https://github.com/microsoft/vscode/pull/148012 fixing it

**Comment by sandy081** [comment]
Fixed by e428b0bc9f535cdb0ecb9850cc5d30a514ee19a7

**Comment by sandy081** [comment]
Reopening it for the following specific case

- install extension using vsix with `--do-not-sync` disconnected from the internet due to some X reason
- connect to internet, run server, and open in browser
- extension will be synced

**Comment by sandy081** [comment]
This should be fixed now. Please reopen it if it is not.
