### ISSUE TITLE
comments on js cannot be used !

### ISSUE THREAD

**Issue by luckylucy1233** [Microsoft/vscode#14802]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: AESSoft.aessoft-class-autocomplete-0.1.0, IBM.output-colorizer-0.0.8

Steps to Reproduce:

1.<script></script>内的js代码不能多行注释，如下
`  `
![1](https://cloud.githubusercontent.com/assets/22283858/19886092/cbb46c74-a05c-11e6-9bb3-4f5e4e6d8069.png)

**Comment by AkashGutha** [comment]
it's because that is not how js comments work.
for js comments see http://www.w3schools.com/js/js_comments.asp

single line 
```js
//single line comment
this is not inside comment
var b = 0;
```

multiline comment
```js
/*this 
is 
a
multiline 
comment
*/
var a = 0;
```

the one you are using are HTML comments they won't work in JaavScript

**Comment by rebornix** [comment]
Close as it's not a Code issue and @AkashGutha already helped with it. Thanks!
