### ISSUE TITLE
Enhancement request: text formatting access in vscode.window.showInformationMessage

### ISSUE THREAD

**Issue by jammerware** [Microsoft/vscode#14807]
I'd like the ability to format information messages that my extension shows possibly via markdown. For example, I'd like the following input to be rendered as markdown when the alert is presented to the user:

```
vscode.window.showInformationMessage('Hi. I think *this* is really important.');
```

Just thought I'd see if this makes sense to anyone else. Thanks for your consideration and for your hard work on VS Code!

**Comment by rebornix** [comment]
thanks for reporting this issue. It's dup of #6087. Let's track it there.

**Comment by jammerware** [comment]
Sorry about that! Thanks.
