### ISSUE TITLE
Style inside Webcomponent shadowroot isn't working inside custom extension

### ISSUE THREAD

**Issue by max529** [microsoft/vscode#148018]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create an extension to open a custom webview
2. Add a webcomponent and attach shadowRoot in open mode
3. Add an inline style inside the template of your component
4. Open the web dev tools and notice that your style isn't applied to the element inside your shadowRoot

![Capture](https://user-images.githubusercontent.com/19285564/164998321-2efa0510-1567-4c07-bdbe-291d2d4b7486.PNG)

**Comment by mjbvz** [comment]
Isn't this the expected behavior for shadow doms?

Please test outside of VS Code first. If you think VS Code is doing something weird, then share a minimal extension samples that demonstrates the issue

**Comment by max529** [comment]
No this isn't the expected behavior...

You can clone this repo : https://github.com/max529/rkdb

Run the extension and open a file with extension .rkdb and open the file test.html inside your browser and you will see that the result is different. Style isn't applied inside vs-code but is applied in my browser (test with Chrome Version 100.0.4896.127 and Firefox 99.0.1)
