### ISSUE TITLE
Test: Language Detection Hints

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#148089]
Refs: #147184

- [x] anyOS @sandy081
- [x] anyOS @misolori

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148089%0A%0A&assignees=JacksonKearl)

---

Added language detection hints to notebook cells and untitled editors. 

### Notebooks
1. Install a polyglot notebook. Handy dandy is a good option: https://marketplace.visualstudio.com/items?itemName=jakearl.handydandy-notebook
2. Create a new notebook (File => New File...)
3. In the new notebook, start typing various language in both markdown and code cells. A lightbulb should appear in the status bar near the language selector suggesting you to switch to the detected language. Note that this will only suggest languages supported by the notebook, you can click the notebook language picker to see them all.  (you may need to explicitly select a kernel for this to work)
4. Try editing `handydandy-notebook.dispatch` to add a new language support, reload the window and try detecting that language

### Untitled Editors
1. Paste text into a new untitled editor, the language should be set to the source language.
2. Now, edit the text until it looks like a different language. Observe the lightbulb appear in the status bar, clicking it should change the language. 
3. Alternatively, open a new untitled editor and manually pick a language. Start typing in a different language, observe lightbulb appear.

**Comment by sandy081** [comment]
Make sure you select the kernel after installing the `jakearl.handydandy-notebook` extension. Otherwise light bulb is not working.

**Comment by sandy081** [comment]
@JacksonKearl Can you please provide some examples or additional instructions to test following:

> Try editing handydandy-notebook.dispatch to add a new language support, reload the window and try detecting that language

**Comment by JacksonKearl** [comment]
To test the ability to add new languages please run from sources (I can't publish updates, no Marketplace PAT): https://github.com/JacksonKearl/vscode-handydandy-notebook

you can try adding a simple config like:
```
"go": [ "echo", [ "${code}" ] ]
```
just to verify that adding the language allows it to be detected:

```go
package main

import "fmt"

func main() {
	fmt.Println("Hello, world.")
}
```

**Comment by misolori** [comment]
it works for me:

<img width="839" alt="CleanShot 2022-04-27 at 08 45 39@2x" src="https://user-images.githubusercontent.com/35271042/165558532-3a1b0c49-c628-4d50-9359-c9f820fa17ba.png">
