### ISSUE TITLE
Allow to close an editor at index

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#148084]
Similar to the `workbench.action.openEditorAtIndex` command, it would be helpful if there was the corresponding

`workbench.action.closeEditorAtIndex` command.

I am working with dragging "tabs" represented in a tree of editor groups and a `closeEditorAtIndex` would avoid a lot of code.  Currently, the only close editor commands work on the active editor only - so using that command would require making the editor you want to close (perhaps because you are dragging its tree item to another group, see demo below) the active one, and then resetting the active editor to the previously active editor afterwards for the user.  Same with the various `moveEditor` commands - it appears they only work on the currently active editor.

My `dragHandler` code can easily access the indices of the tabs that are selected and dragged.

[The demo uses the `TabGroups.move()` method which is no longer available, but will hopefully be in the future.] 

![editorManagerMove](https://user-images.githubusercontent.com/31813701/165179428-76061d82-85e3-4c80-b3e2-da528bdc1baa.gif)

**Comment by bpasero** [comment]
Even though this talks about adding a command, I feel this belongs more into the new tabs API.

**Comment by lramos15** [comment]
With the tabs API are you not already able to do this? 

```
const group = window.tabGroups[groupIndex];
group.close(group.tabs[tabIndex]);
```
