### ISSUE TITLE
Test - Source control repositories sort options

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#148078]
Refs: #146359

- [x] anyOS @tanhakabir
- [x] anyOS @rzhao271

Complexity: 3

Authors: @lszomoru, @joaomoreno 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148078%0A%0A&assignees=lszomoru,joaomoreno)

---

This milestone we have added a new setting, `scm.repositories.sortOrder` to set the default sort order of the repositories in the "Source Control Repositories" view, as well as surfaced the options to sort the repositories in the "Source Control" viewlet. 

### Prerequisites
1. Open VS Code Insiders and ensure that the value of the `scm.repositories.sortOrder` is set to `discovery time`
2. Switch to the "Source Control" viewlet, and ensure that the "Source Control Repositories" view is visible
3. Set up a VS Code workspace with multiple folders/repositories
    - Create a new folder `workspace`
    - Create a new folder inside `workspace` called `a`
    - Create a new folder inside `workspace` called `b`
    - Create a new folder inside `workspace` called `c`
    - Create a new folder inside `workspace` called `d`
    - In each folder of the folders (a, b, c, d) execute `git init` (no need to add any files)
    - In the `workspace` folder create a new file called `test.code-workspace` with the following content:
    ```json
    {
	"folders": [
		{
			"path": "d"
		},
		{
			"path": "c"
		},
		{
			"path": "b"
		},
		{
			"path": "a"
		}
	],
	"settings": {}
    }
    ```

### Test Plan
1. Open VS Code Insiders
2. Use "Open Workspace from File" and select the `test.code-workspace` file
3. Switch to the "Source Control" viewlet
    - Confirm that in the "Source Control Repositories" view the repositories appear in the following oder: d, c, b, a
4. Select one of the repositories (ex: `b`), then use `Ctrl + Click` to select other repositories one by one
    - Confirm that in the "Source Control" view, the repositories appear in the exact order that they were selected
5. Click on the `...` menu in the "Source Control Repositories" view, and pick the "Sort by Name" option
    - Confirm that the repositories in the "Source Control Repositories" and "Source Control" views are sorted by name and that the selection of the repositories has been maintained
6. Reload the window
    - Confirm that after reload, the order and selected was restored in the "Source Control Repositories" and "Source Control" views
7. Click on the `...` menu in the "Source Control Repositories" view
    - Confirm that the "Sort by Name" option is checked

**Comment by rzhao271** [comment]
Along with the original steps, I also tried a variation where for Step 6, I did a reload after switching back to the "Sort by Discovery Time" option. I noticed in that case that the repositories in the "Source Control" view order changed from `c a b` to `c b a`.
The original steps LGTM.

**Comment by tanhakabir** [comment]
None of the sort options seem to work for me
