### ISSUE TITLE
Thunder Client and Git Graph in VSCode 1.66

### ISSUE THREAD

**Issue by alexandreguz** [microsoft/vscode#148050]
- **VS Code Version**: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 20.6.0

- **OS Version**: macOS Big Sur version 11.6.5

Steps to Reproduce:

Just updated the VSCode to 1.66 and the extensions Thunder Client and Git Lens stopped working.
The message error was 

> Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

Is this related to the version and will be fixed later, or is the extensions problem?

**Comment by gjsjohnmurray** [comment]
Your title refers to Git Graph but your description refers to Git Lens. Please clarify.
