### ISSUE TITLE
Stabilize File Nesting

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#148090]
Already gone through several rounds of testing, so just a verification that the new, non-experimental settings work as expected:

`explorer.fileNesting.enabled`, `explorer.fileNesting.expand`, and `explorer.fileNesting.patterns`. 

`explorer.fileNesting.experimental.operateAsGroup` remains intentionally experimental and will be removed soon.

**Comment by jrieken** [comment]
@JacksonKearl I am a real fan of this feature
