### ISSUE TITLE
Test: suspendDebuggee UI

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#148070]
Refs: #134412

- [x] macOS @bpasero
- [x] windows @minsa110

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148070%0A%0A&assignees=roblourens)

---

- Clone the vscode-mock-debug repo, `yarn`, run the "watch" task
- You will check every combination of capabilities and launch/attach to check that the right options show up on the debug toolbar
- Modify the capabilities here: https://github.com/Microsoft/vscode-mock-debug/blob/a0f49b793dd32cfc235c7013e97ba1e1188f55ef/src/mockDebug.ts#L216
- Run the Extension launch config, start debugging the sampleWorkspace/readme.md file, and check the options on the stop button are correct according to the list below

<img width="292" alt="image" src="https://user-images.githubusercontent.com/51177946/164628167-d96b18e0-9e26-477c-84a6-664f4623029a.png">

* supportsTerminateDebuggee=false supportsSuspendDebuggee=false
   * launch:
      * square icon
      * no dropdown
    * attach:
      * plug
      * no dropdown
    * Alt modifier key: not honored

* supportsTerminateDebuggee=true supportsSuspendDebuggee=false
   * launch:
      * square icon
      * dropdown:
         * "disconnect"
       * alt: flips to plug icon
    * attach:
      * plug icon
      * dropdown:
         * Stop
       * alt: flips to square icon

* supportsTerminateDebuggee=false supportsSuspendDebuggee=true
   * launch:
      * square icon
    * attach:
      * plug icon
      * dropdown:
         * "disconnect and suspend"
    * Alt modifier key: not honored

* supportsTerminateDebuggee=true supportsSuspendDebuggee=true
   * launch:
      * square icon
      * dropdown:
         * "disconnect"
         * "disconnect and suspend"
      * alt: flips to plug icon
    * attach:
      * plug icon
      * dropdown:
         * "disconnect and suspend"
         * "stop"
      * alt: flips to square icon

**Comment by bpasero** [comment]
👍  best test plan item I had
