### ISSUE TITLE
Test new default value of `comments.openView`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#148045]
Refs: https://github.com/microsoft/vscode/issues/147365

- [x] macOS @lychung7
- [x] linux @brettcannon
- [x] windows @dbaeumer

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23148045%0A%0A&assignees=alexr00)

---

The old default value of `comments.openView` was `file`, which would cause the Comments view to open whenever you open a file with comments in it. This was too noisy as a default. The new default value `firstFile` only opens the Comment view the first time in a session that a file with comments is opened.

You can use the following setup steps or use your own setup for files with comments.
1. Install the pre-release version of GitHub Pull Requests and Issues.
2. Open a folder with a GitHub repository that has pull requests with comments. 

Verify:
- that the Comments view is only opened the first time a file with comments is opened (until you reload).
- that after you reload and open a file with comments again that the comments view is opened.
- that the description of the setting value `firstFile` makes sense.

**Comment by dbaeumer** [comment]
Just to ensure: the comments view only came to front when opening the modified version of a file.

**Comment by brettcannon** [comment]
Opened https://github.com/microsoft/vscode/issues/148208 as I didn't get the expected result when the terminal was initially opened after reloading.
