### ISSUE TITLE
Spaces are converted to tabs in html regardless of indentation settings

### ISSUE THREAD

**Issue by Andikki** [Microsoft/vscode#14809]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a folder with one .html file with some indented html content and workspace settings.json (`F1` => `Preferences: Open Workspace Settings`). Define settings like this:
```
{
  "editor.tabSize": 2,
  "editor.insertSpaces": true,
  "editor.formatOnSave": true,
  "editor.renderWhitespace": "all"
}
```
2. Open the .html file, press `F1` > `Convert Indentation to Spaces` (or do this from the status bar). See that the lines are indented with spaces.
3. Save the file (since `formatOnSave` is set to `true`) or just auto-format it with `Alt+Shift+F`.

Expected result:
The file is indented with 2 spaces.

Actual result:
All spaces are converted to tabs.

![spaces-replaced-with-tabs](https://cloud.githubusercontent.com/assets/10902643/19895747/fe87967a-a062-11e6-89e6-e8ab4856cc41.gif)

**Comment by rebornix** [comment]
It's dup of #13563. We have already fixed this in master and you can see this in 1.7
