### ISSUE TITLE
Edit extension settings from Feature Contributions

### ISSUE THREAD

**Issue by lustickd** [microsoft/vscode#148095]
Usually after installing extensions I need to change some settings so go to the Feature Contributions page to see the names and defaults. I've often wished I could edit settings in some capacity from here.

A button or link that opens settings.json and adds or finds the key + value (with the value selected so you can delete it) would be extremely useful.

**Comment by sandy081** [comment]
You can open settings for an extension using `Extension Settings` action

<img width="568" alt="image" src="https://user-images.githubusercontent.com/10746682/165273771-0daa343f-4659-401a-af65-d7815ba4ed2f.png">
