### ISSUE TITLE
Smart file highlight in explorer tree

### ISSUE THREAD

**Issue by gabriellopes00** [microsoft/vscode#148080]
I noticed that if you open a folder in vscode and open two or more files from this folder by clicking them in explorer, you will see that the highlight in the explorer tree is not going to "follow" the current file in focus. It would be a nice "feature" if the highlighted file in the explorer was the one you're editing or the one in focus. 
There are some more stuffs:
- If you close the file, the highlight automatically jumps to the one on focus. 
- If you close the last file opened, then just remove the highlight from the explorer.

What do you think guys?

**Comment by pfgithub** [comment]
This is already supported and controlled by the setting `explorer.autoReveal`

![image](https://user-images.githubusercontent.com/6010774/165162440-d108e758-f4ca-4008-8f7f-4e84253761d3.png)

**Comment by gabriellopes00** [comment]
Oohh yeeah, I'm sorry... I've disabled that because when I open some typescript definition file which is inside `node_modules`, the explorer expands all the node_modules until the file, and I hate that... kkkkkkk
But thanks a lot.
