### ISSUE TITLE
reading suggestions from gitub copilot

### ISSUE THREAD

**Issue by jeanbrazcosta** [microsoft/vscode#148098]
After being approved to use the copilot github extension, I did the whole installation and authorization procedure, however, I was not able to get the suggestions that the extension suggested with the screen reader.

I tried both making a comment and starting to type new stuff.

I know there were suggestions, because I asked a friend.

VSCode versão: Versão: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Data: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

NVDA version: 2021.3

Would it be possible to make NVDa read the suggestions so we can interact with them in the future?

Thank you very much in advance

**Comment by dbaeumer** [comment]
@jeanbrazcosta according to the copilot documentation  https://github.com/github/copilot-docs you need to report bugs about copilot here: https://github.com/github/feedback/discussions/categories/copilot-feedback
