### ISSUE TITLE
No autoscroll feature and select all in integrated console

### ISSUE THREAD

**Issue by sanmahad** [Microsoft/vscode#14805]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: dbaeumer.jshint-0.10.15, gerane.Theme-Dreamweaver-0.0.2

Steps to Reproduce:

1. In the integrated console, run few commands
2. Try to copy the lines more than you can see in the integrated console. It wont auto scroll.
2. Also there is no select all feature.

**Comment by rebornix** [comment]
We are using xterm.js and this issue is on our list, please keep an eye on https://github.com/sourcelair/xterm.js/issues/207 about its status.
