### ISSUE TITLE
Pre-release extension goes back to normal extension

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148115]
Steps to Reproduce:

1. fresh insiders, fresh dirs
2. install GH PR pre-release extension
3. quit
4. start again

=> extensions viewlet reports the non-pre-release extension is installed.

**Comment by sandy081** [comment]
It is an UI glitch and fixed it already.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/commit/e428b0bc9f535cdb0ecb9850cc5d30a514ee19a7
