### ISSUE TITLE
Light bulb did not appear while typing any language in notebook editor

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#148159]
Testing #148089

1. Install a polyglot notebook. Handy dandy is a good option: https://marketplace.visualstudio.com/items?itemName=jakearl.handydandy-notebook
2. Create a new notebook (File => New File...)
3. In the new notebook, start typing various language in the code cell

🐛 Light bulb did not appear

<img width="699" alt="image" src="https://user-images.githubusercontent.com/10746682/165321605-014733d6-339a-4488-b5b7-b2ca360b91ff.png">

**Comment by sandy081** [comment]
It started working after selecting the Kernel to Handy Dandy Kernel

**Comment by JacksonKearl** [comment]
cc @rebornix is there a way to have the kernel set by default when there's only one option?
