### ISSUE TITLE
Go to definition stuck on white space

### ISSUE THREAD

**Issue by Ejbosch** [microsoft/vscode#148141]
Issue Type: <b>Bug</b>

The file cannot be opened with 'go to definition'. Reason: white spaces in the object are translated into %20. 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.81GB (26.68GB free)|
|Process Argv|--crash-reporter-id 4b72f2ee-7094-42ab-940d-d4478bb97896|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
al-code-outline|and|3.0.32
al-codeactions|dav|1.0.18
gitlens|eam|12.0.6
todo-tree|Gru|0.0.215
al|ms-|9.0.611415
mysalhelper|Mys|1.7.8
text-marker|ryu|1.11.0
crs-al-language-extension|wal|1.5.4
file-path-bar|wra|2.1.6

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Please provide steps/core to reliable reproduce this problem
