### ISSUE TITLE
[theme] a new white theme has the same white color for selection 

### ISSUE THREAD

**Issue by Gelassen** [microsoft/vscode#148167]
Issue Type: <b>Bug</b>

Hello the VS team,

I applied yours new white theme and noticed in terminal there is no selection. Actualy it is, but because of selection color is the same white I do not see a text is selected. 

Just a feedback. Hope it is a bug and not a feature :)

Thanks!

Dmitry 

VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T15:36:26.048Z)
OS version: Linux x64 5.4.0-109-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|

</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by daviddossett** [comment]
@Gelassen which theme is this? There's a known problem with the Light High Contrast theme where the terminal foreground text doesn't update on selection as described in #145973.

But it sounds like you might be seeing a different issue?

**Comment by Gelassen** [comment]
@daviddossett , I already moved back to default Dark theme, but checked again White Themes - yes, it is Light High Contrast experimental. 

Good to know you are aware of this issue. Thank you for your work on this IDE.
