### ISSUE TITLE
Stable to insiders smoke test: Viewlets don't reopen

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#148186]
Testing #147702

- Open a local repo in VS Code stable
- Open readme
- Open SCM view and type a commit message `test`, but don't commit
- Open VS Code Insiders with Stable data-dir
- The readme opens automatically, and if I look at the SCM view, it remembers `test` in the commit box. But, the SCM view didn't open by default. Is restoring state supposed to also include which view was open?

**Comment by bpasero** [comment]
A long time ago we decided that the "Explorer" is always the view to open unless you do a window reload.
