### ISSUE TITLE
Markdown rename not discoverable

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#148149]
Testing #147738

I like the nice markdown rename flow you did, nice work!
I worry that users will not discover it because when I try to rename on a random location that we can not rename we say "Rename not supported on location". This is probably coming from core and not sure if you have control of this message.

But how could we make rename more discoverable for Markdown? Some ideas:

1. Rename is always enabled - if a user renames a word we rename all ocurrences of that word in the document. That way uses would start using it no matter what.
2. Rename action is enabled / disabled in menu based on click location
3. We show a msg that renaming markdown links is possible instead of the current msg

Other ideas?

![Screenshot 2022-04-26 at 15 05 58](https://user-images.githubusercontent.com/1926584/165306574-bb5625b1-876c-4bf8-a81e-2ebbe7abfa92.png)

**Comment by mjbvz** [comment]
/cc @jrieken for idea number 2

I originally went with approach 3 but then we started supporting renames in more places so the message (`Rename only supported on headers and links)` felt kind of long

**Comment by jrieken** [comment]
> Rename action is enabled / disabled in menu based on click location

That's quite tricky because the menu renders sync and knowing if something can be renamed is async...

A good hint for renamability is mark occurrences, e.g header and header-link can be emphasised with the document symbol API

**Comment by mjbvz** [comment]
This is now also documented: https://code.visualstudio.com/Docs/languages/markdown#_rename-headers-and-links
