### ISSUE TITLE
text on scroll area

### ISSUE THREAD

**Issue by gkalvarog** [microsoft/vscode#148150]
The issue is that when I resize the page to see it along with other content, I can see some text over the scroll page area. I think it wasn't supposed to work like this, that's why i'm reporting it here.

![1](https://user-images.githubusercontent.com/103211949/165307838-61541758-7e36-45e9-93d1-ec73e34a1abb.png)
![2](https://user-images.githubusercontent.com/103211949/165307845-11dedb08-bd87-42de-84cd-cf4206ca2257.png)
.

**Comment by alexdima** [comment]
The scrollbar is intentionally transparent. We have a color `editorOverviewRuler.background` that is used only when the minimap is enabled. We could potentially use it always if set to allow defining opaque scrollbars.

**Comment by gkalvarog** [comment]
Oh. Thank you for explaining :)

In this case, sorry for bothering!



Best,
Alvaro



Sent from my Galaxy



-------- Original message --------
From: Alexandru Dima ***@***.***>
Date: 4/27/22 17:29 (GMT-03:00)
To: microsoft/vscode ***@***.***>
Cc: Alvin ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vscode] text on scroll area (Issue #148150)


The scrollbar is intentionally transparent. We have a color editorOverviewRuler.background that is used only when the minimap is enabled. We could potentially use it always if set to allow defining opaque scrollbars.

**Comment by alexdima** [comment]
To verify, configure the color `editorOverviewRuler.background` and that will be applied and will make the overview ruler opaque. e.g.

```
"workbench.colorCustomizations": {
	"editorOverviewRuler.background": "#ff0000ff",
}
```
