### ISSUE TITLE
Markdown: rename failed to apply edits when invalid link to file

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#148147]
Testing #147738

1. Open https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/June_2016.md#L15
2. Have the following content
```
[link](./July_222016.md)
```
3. Try to rename the file. It fails with an error: "failed to apply edits" 🐛 

I would expect that at least the rename of my selected symbol would work (even though it does not point to anything).

![Screenshot 2022-04-26 at 14 55 28](https://user-images.githubusercontent.com/1926584/165304726-6539bb81-8a88-4892-8ce7-b80a934b06e6.png)

**Comment by mjbvz** [comment]
This should now work. Let me know if you notice any issues

(I also opened a separate issue to investigate rename without the `.md`: https://github.com/microsoft/vscode/issues/148490)
