### ISSUE TITLE
VC code got stuck on "Get started - Visual Studio Code "page. 

### ISSUE THREAD

**Issue by chrisluwtw** [microsoft/vscode#148194]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Debian GNU/Linux 10 (buster)

Steps to Reproduce:

1. just click to open VS code in Debian GNU LINUX 10.10
2. it only see pure white and pure black blocks.
3. 
![111](https://user-images.githubusercontent.com/83245014/165363304-6c1eb579-d234-465f-b14c-02b80e02e1a2.jpg)

**Comment by deepak1556** [comment]
Is this on a VM ? Can you try running with `code --disable-gpu` ?

**Comment by chrisluwtw** [comment]
wow, actually, you command works, yes, it is in a vm, disable gpu made it working.
