### ISSUE TITLE
Renaming in file in explorer does not rename its reference in markdown

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#148146]
Testing #147738

1. Open the following file in markdown https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/June_2016.md#L22
2. Add the following content
```
[link](./July_2016.md)
```
3. Open Explorer, rename the file `July_2016.md`. The link in markdown does not get updated 🐛

**Comment by mjbvz** [comment]
Hm, thought I already had a feature request tracking this but perhaps I repurposed that issue 

Yes this is not expected to work today as the `rename` provider is not involved at all in this flow. I'd expected  rename on files to work much like how it does for JS/TS

**Comment by mjbvz** [comment]
Reopening since the feature is still experimental
