### ISSUE TITLE
Sticky commit box input

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148111]
No matter how hard I try, I cannot clear the git commit box, the content always comes back after restart.
![Recording 2022-04-26 at 07 31 40](https://user-images.githubusercontent.com/900690/165228521-07acc8ec-586e-4a7c-a71a-07da582ff2f6.gif)

**Comment by lszomoru** [comment]
@bpasero, was `aa` a previous commit message?
I am asking as I am wondering if we are somehow restoring the latest commit message.

**Comment by bpasero** [comment]
No its the thing I typed last in the box.

**Comment by lszomoru** [comment]
Thanks! Will look into it, and will reach out in case I cannot repro the issue.
