### ISSUE TITLE
Stream Markdown reference provider?

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#148190]
Testing #147731

Initially looking for a reference in vscode-docs repo takes quite some time where no results show. It's faster on the next go, but it'd be nice (especially in massive repos like azure-docs) to initially show at least the results in open editors fairly quickly.

**Comment by mjbvz** [comment]
This is not possible with our current provider apis. They require all results to be returned in one shot 

After the first request thought we cache the results so future request will be faster
