### ISSUE TITLE
Confirm Before Close dialog shows when quitting any window

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#148122]
Testing #147704

From the test plan item:

> - Linux/Windows: ensure this works when you close the last window which on these OS will trigger application quit (as opposed to macOS)
> - consequently you should never see this dialog when you close a window and the application is not quitting (e.g. when there is still a window opened or on macOS where closing a window never quits)

On Windows, I have 3 windows open. I set Confirm Before Close to "always" and hit the x on one of the Windows. I saw the confirm dialog even though there were 2 other windows.

![image](https://user-images.githubusercontent.com/38270282/165265245-4a65bd4a-8490-4446-b510-c1ee6dad942f.png)

**Comment by bpasero** [comment]
Yeah sorry, bad test plan item description. https://github.com/microsoft/vscode/issues/14710#issuecomment-1094699388 explains the reasoning, I think originally I had it different but then went back.
