### ISSUE TITLE
Breakpoint in JavaScript becomes unbound breakpoint at runtime 

### ISSUE THREAD

**Issue by capegreg** [microsoft/vscode#148144]
Same as issue #147723, which was improperly closed.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.2 (user setup)
Commit: https://github.com/microsoft/vscode/commit/dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044

Same issue with Insiders build.

Steps to Reproduce:

1. Set a JavaScript breakpoint. Breakpoint shows as solid red dot
![image](https://user-images.githubusercontent.com/1051118/165301588-d57908b1-2009-4f01-91cb-7c4b51df7b9f.png)

2. Run application
3. Breakpoint becomes disabled unbound breakpoint hollow dot
![image](https://user-images.githubusercontent.com/1051118/165301714-ca913a29-4856-49b1-af57-1d6f77044833.png)

4. Go to page that will trigger breakpoint
5. Click the unbound breakpoint to remove it. Click again to re-add it
6. Breakpoint becomes enabled
![image](https://user-images.githubusercontent.com/1051118/165301809-0c85c1c8-dd74-4c4f-b0f7-8d86dcebf904.png)

{
  "name": "Chrome Launch",
  "type": "chrome",
  "request": "launch",
  "url": "https://localhost/mysite/",
  "webRoot": "${workspaceFolder}",
  "runtimeArgs": ["--profile-directory=debug-profile"],
  "resolveSourceMapLocations": [
    "${workspaceFolder}/**",
    "!**/node_modules/**"
  ]
}

captured from trace log

webRoot = "C:\\Workspace\\dev.manateepao.com\\wp-content\\themes\\frontier-child"

![image](https://user-images.githubusercontent.com/1051118/165302603-2f67223e-30ec-4bef-98e1-9c8a6c379c89.png)

![image](https://user-images.githubusercontent.com/1051118/165302764-ff460440-f575-4814-8154-055b07bf0501.png)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/147723

**Comment by capegreg** [comment]
Why do you close this and the previous when your answer is wrong?
