### ISSUE TITLE
Unclear if notebook cell works with empty language cell

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#148189]
Testing #148089

<img width="600" alt="CleanShot 2022-04-26 at 10 43 03@2x" src="https://user-images.githubusercontent.com/35271042/165360580-48b0e33e-5d42-48f7-984d-06adf7299fbb.png">

1. create new notebook (handy dandy notebook)
2. start writing `console.log()`
3. :bug: language status bar is missing, which makes me think the notebook does not work

I also ran into other issues where as I wrote more code, like a js function, it still wouldn't show up. Even copilot knows what I'm about to write:

<img width="735" alt="CleanShot 2022-04-26 at 10 45 47@2x" src="https://user-images.githubusercontent.com/35271042/165360969-c26656d4-b742-40d5-84a7-94d1cd8f73c7.png">

**Comment by JacksonKearl** [comment]
Have you explicitly selected the kernel here? I see it not get selected sometimes even though its the only option

**Comment by misolori** [comment]
I did not select it, it was already auto-selected

**Comment by JacksonKearl** [comment]
Hm. With just `function addNumbers` there's not really a string signal for language, if you type more js specific stuff do you get anything?

**Comment by misolori** [comment]
Also this repros consistently if you reload + create a new notebook file via the command palette

**Comment by JacksonKearl** [comment]
This should be fixed now, detection will use suggested or selected kernel, and handy dandy notebook will default to js (there's a config for the default)
