### ISSUE TITLE
Inlay hints - settings feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#148151]
Testing #148040

This is more like general feedback about the `editor.inlayHints.enabled` and `editor.inlayHints.toggle` settings. There is clear correlation between these two settings so I was wondering whether it would make sense to unify them to options like:
- always show
- show on `Ctrl + Alt`
- hide on `Ctrl + Alt`

This would also address the issue that currently the default value for the `editor.inlayHints.toggle` is `null`.

**Comment by jrieken** [comment]
April for consideration. Initially I had this in mind but couldn't find nice "word" for the `.enabled: showOnKeys` and `hideOnKeys`. Open for suggestions

**Comment by JacksonKearl** [comment]
Maybe something like `hideWhenPressed`, `showWhenPressed`, `ignorePress`?

**Comment by jrieken** [comment]
After discussions I have merged both settings into one. Values are "on", "onUnlessPressed", "offUnlessPressed", and "off". I went with "xyzUnlessPressed" because it seems clearer than "hideWhenPressed" - hideWhenPressed means on which isn't obvious IMO

<img width="523" alt="Screenshot 2022-04-28 at 10 54 21" src="https://user-images.githubusercontent.com/1794099/165715887-a093b521-e4cc-47bd-9fd7-e006b5088128.png">

**Comment by IllusionMH** [comment]
Nice to see this change, because selecting `null` for `editor.inlayHints.toggle` in Settings editor will replace selectbox with this view on blur (+ warning in `settings.json`)
![image](https://user-images.githubusercontent.com/1312662/165732996-2460926f-c913-431e-9514-f7ea5ca7ef07.png)

**Comment by jrieken** [comment]
I know but I also cannot make it an OR-type because the settings editor will also fail to render that... @roblourens @rzhao271 do you have advice how to best migrate a boolean-setting into a string-enum?

**Comment by IllusionMH** [comment]
Just in case - my comment was about removed(?) setting `editor.inlayHints.toggle` (still in Insider build) it was confusing to select value proposed in selectbox and then see validation error.

For updated setting `editor.inlayHints.enabled` (not yet in Insiders build) I don't see this will be the case to selectc something and get error, just warning about old boolean value.

**Comment by jrieken** [comment]
Oh, sorry... Didn't read that properly and `null` should have been supported in the (now removed) toggle setting... Tho, you'll see the same with new change where boolean goes to string

<img width="698" alt="Screenshot 2022-04-28 at 14 45 19" src="https://user-images.githubusercontent.com/1794099/165754952-4090964a-2728-4604-bdae-db47f5c4d6f6.png">

**Comment by jrieken** [comment]
> Even better - button to replace old with corresponding new if there is 1:1 mapping.

Internally there is [migration code](https://github.com/microsoft/vscode/blob/d1f72318c70e08780a75e934b185b253a6d9edc8/src/vs/editor/common/config/editorOptions.ts#L2579-L2581) but it sits at the wrong layer - the settings world isn't aware of it, it happens inside the editor
