### ISSUE TITLE
Editor limit only updates on editor open

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#148198]
Found verifying: #144309

1. Have exclude dirty on and a small editor limit (I chose 1)
2. Have one dirty file and one non dirty file
3. Undo the dirty changes
4. 🐛 You have two clean files open even though your limit is 1.

This feels like polish and isn't a huge deal but maybe we want to listen to a few more events here or use tabs API.

**Comment by bpasero** [comment]
I worry to change this behaviour because editor limit has been there since >1y and I did not hear feedback from users that would expect non-dirty editors to close when they are saved or reverted.
