### ISSUE TITLE
Using mocha - describe and it are not defined

### ISSUE THREAD

**Issue by kristianmandrup** [Microsoft/vscode#14814]
How do I make the editor understand that `describe` and `it` are valid globals?
I have an `eslintrc`, a `jscrc` and a `tsconfig.json` file. Where to define such globals so that VSC picks them up? I guess it is a linter error?

Thanks!

**Comment by rebornix** [comment]
What you actually need is typings file for mocha https://gist.github.com/muratg/4163650

**Comment by kristianmandrup** [comment]
But I'm not using TypeScript, just a plain ES6 Javascript project. I need it even then!?

**Comment by rebornix** [comment]
@kristianmandrup for now it is, Code needs it to do the type checking.

But we implemented automatic type acquisition https://github.com/Microsoft/vscode/issues/14296, which means you don't need to do so this anymore with 1.7.0 (Insiders right now or Stable after we release it).

For now my personal experience with Mocha on Code Insiders 1.7 is

1. Create node project
2. `npm install --save mocha`
3. Create a test file, write `var assert = require('assert');`
4. Then start to write `describe` and the intellisense is there 

![screen shot 2016-11-01 at 10 59 06 am](https://cloud.githubusercontent.com/assets/876920/19900873/4848dac6-a022-11e6-9b5c-f8ab6f02e71b.png)

**Comment by kristianmandrup** [comment]
Sweet :) looking forward to 1.7!!!
For now I got around it by using my own chaining DSL around mocha.

npm: mocha-test-dsl :)
