### ISSUE TITLE
Disable breakpoint keybinding isn't shown anywhere

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#148157]
Found while testing https://github.com/microsoft/vscode/issues/147597.

Usually keyboard shortcuts are shown in context menus and in the keybindings. `shift+click` to disable breakpoints isn't shown in either place:

![image](https://user-images.githubusercontent.com/38270282/165320041-90665948-ec45-436c-a226-5cdc88d6f3b5.png)

**Comment by roblourens** [comment]
Would like to show it somewhere but I can't make it show up as a keybinding (since it's not really a keybinding) and I think that would be too much text for the main hover.
