### ISSUE TITLE
BUG-2016/11/02

### ISSUE THREAD

**Issue by Shiichi0w0** [Microsoft/vscode#14819]
- VSCode Version: Code 1.6.1 **[Unsupported]** (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: abusaidm.html-snippets-0.0.18, AdamCaviness.theme-monokai-dark-soda-0.0.5, anseki.vscode-color-0.2.1, donjayamanne.python-0.5.0, felixfbecker.php-debug-1.9.7, formulahendry.auto-rename-tag-0.0.7, HookyQR.beautify-0.5.3, magicstack.MagicPython-0.5.17, moozzyk.Arduino-0.0.4, ms-vscode.cpptools-0.9.2, ms-vscode.Theme-MaterialKit-0.1.1, naumovs.color-highlight-1.2.1, robertohuertasm.vscode-icons-3.0.7, shalldie.background-1.1.7, zhuangtongfa.Material-theme-1.0.3, Zignd.html-css-class-completion-1.0.3

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Community need More information to try to help you. Please, provide more detailed description and steps to reproduce your problem.

**Comment by aeschli** [comment]
Closing issue.
