### ISSUE TITLE
Segfault on Asahi Linux M1 Max

### ISSUE THREAD

**Issue by victoryang00** [microsoft/vscode#148116]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  current latest aarch64 release on linux
- OS Version: Asahi Linux

Steps to Reproduce:

1. in asahi linux M1 Max, I ran the latest code-insider and the latest code with segfault
```bash
victoryang00@victoryang00-mac:~/Downloads/VSCode-linux-arm64/bin -$ ./code-insiders 
./code-insiders: line 53: 46797 Segmentation fault      ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"
```

**Comment by deepak1556** [comment]
Can you provide the crash log following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by victoryang00** [comment]
It sounds like the crash occur before it can output the crash report.

I have other unusable desktop like telegram, I think the problem is because of the allocator don't support 16KB page size.
```bash
 telegram-desktop 
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
GLib (gthread-posix.c): Unexpected error from C library during 'malloc': Cannot allocate memory.  Aborting.
[1]    1788 IOT instruction (core dumped)  telegram-desktop
```

**Comment by deepak1556** [comment]
The runtime uses a custom allocator https://chromium.googlesource.com/chromium/src/+/HEAD/base/allocator/partition_allocator/PartitionAlloc.md and from the log the runtime is incorrectly using jemalloc, please check if you `LD_PRELOAD` that might have caused this allocator to be loaded.

**Comment by Legarts** [comment]
The same problem with M1 Air (2020) :

    VS Code Version: current latest aarch64 release on linux
    OS Version: Asahi Linux

`LD_PRELOAD` is clean

**Comment by 12101111** [comment]
As this page say: https://github.com/AsahiLinux/docs/wiki/Software-known-to-have-issues-with-16k-page-size

You need build electron yourself and backport this patch: https://chromium.googlesource.com/chromium/src/+/a704c3a94179e6f3abb28f090d096ced72657d7c

**Comment by 12101111** [comment]
![图片](https://user-images.githubusercontent.com/8438475/165699928-3e458bf2-b8ae-43ba-8051-9a806be2dc4e.png)

**Comment by deepak1556** [comment]
@12101111 thanks for linking to the chromium CL

I will wait for the upstream issue to be verified before backporting the patch to Electron https://bugs.chromium.org/p/chromium/issues/detail?id=1301788

**Comment by victoryang00** [comment]
> As this page say: https://github.com/AsahiLinux/docs/wiki/Software-known-to-have-issues-with-16k-page-size
> 
> You need build electron yourself and backport this patch: https://chromium.googlesource.com/chromium/src/+/a704c3a94179e6f3abb28f090d096ced72657d7c

Yeah, my solution is to build a 4k page size latest Linux kernel for all the stuff to work.
