### ISSUE TITLE
Linux: Crash dialog does not allow to reopen

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#148197]
Testing #147699

This is a little funky on my Linux vms. On one of them, if I don't check the "don't restore editors" box and click "reopen", the window never reopens. It works as expected if I check "don't restore editors".

On the other, there is no "don't reload editors" checkbox, and "reopen" never reloads the window.

**Comment by bpasero** [comment]
This is a tougher one, I believe there are actually 2 crashes happening: one from `process.crash()` and the other from our handling and I think the second one takes down the entire application.

@deepak1556 can you check the dump files we get when this happens? To reproduce:
* on Linux run with providing `--crash-reporter-directory`
* run out of sources
* open devtools
* `process.crash()`
* click Reopen or Close, both will produce a second dmp file

First `dmp` (probably from `process.crash`):

[4953a25f-53a0-4d79-a084-ea019260a09d.dmp.zip](https://github.com/microsoft/vscode/files/8569307/4953a25f-53a0-4d79-a084-ea019260a09d.dmp.zip)

Second `dmp` (when clicking "Close" or "Reopen"): 
[7f77b438-deba-4c4d-a09a-9bca9fdc0e44.dmp.zip](https://github.com/microsoft/vscode/files/8569311/7f77b438-deba-4c4d-a09a-9bca9fdc0e44.dmp.zip)

**Comment by deepak1556** [comment]
I haven't debugged this on my machine yet, but it very likely might be the focus call before the window is completely setup https://github.com/microsoft/vscode/blob/main/src/vs/platform/windows/electron-main/window.ts#L671

There have also been some recent changes in the activation event code path https://chromium-review.googlesource.com/c/chromium/src/+/3474337, will see if that helps as well.

**Comment by bpasero** [comment]
@deepak1556 however, the crash also happens when selecting "Close" and in that way we do not open a new window. Even removing the `window.focus()` call does not seem to help when I pick "Reopen".

**Comment by bpasero** [comment]
Btw this seems to reproduce with Electron 13 even, just tried from an older version of VSCode.

**Comment by bpasero** [comment]
Nevermind, this is caused by devtools being visible. Here are steps that work fine and allow "Reopen" to work:
* open devtools
* in console put this: `setTimeout(() => process.crash(), 5000)`
* close devtools
* wait for crash dialog
* pick "Reopen"

=> it should reopen
