### ISSUE TITLE
Settings profile doesn't install extensions if restart required while applying settings

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#148174]
Testing #148058

I opened code insiders with a new user data dir and extensions dir. When I imported the profile file, I got a dialog saying that the editor had to restart to apply a certain setting. After restarting the editor, I went to the settings JSON file and noticed that my settings were there. But, I saw in the extensions viewlet that none of my extensions were installed. After importing for a second time, I saw that my extensions were installed.

An example setting you can add to the `settings.json` file to get the dialog to show up is 
`"update.mode": "manual"`.

**Comment by sandy081** [comment]
This is fixed with settings profiles as importing a profile creates a new settings profile where application scoped settings are ignored and hence restart is not triggered.
