### ISSUE TITLE
Be able to run code after debugging completes.

### ISSUE THREAD

**Issue by xinyanmsft** [Microsoft/vscode#14816]
This is a feature request. 

I am doing an experiment using VSCode around remote debugging. I use SSH port forwarding to connect to remote debugger (as part of preLaunchTask). It works great. However there is currently no way for me to shutdown the SSH after debugging completes. 

It will be great if there are something like 'postDebugTask' where I can run something to clean things up. This seems to be a common scenario for remote debugging.

- VSCode Version: 1.6
- OS Version: Linux/Windows

**Comment by rebornix** [comment]
Dup of #11522 . Thanks @xinyanmsft
