### ISSUE TITLE
Find ocurrences incorectly rendered in terminal scroll bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#148138]
Testing #148060

Have the same content in the editor and in the terminal.
Search for something.
Notice how the occurrence are fat and visible in the editor scrollbar.
Notice how they are not fat and sparse in terminal. They seem to be incorrectly placed since my match is almost on every line and that is not the feeling I get from the terminal scroll bar 🐛 

![Screenshot 2022-04-26 at 13 41 10](https://user-images.githubusercontent.com/1926584/165292370-90436cb3-8795-40bf-9623-0d70782d3e74.png)

![Screenshot 2022-04-26 at 13 40 43](https://user-images.githubusercontent.com/1926584/165292365-ca772e6f-3665-4e13-bad3-ba8d627b03a2.png)

**Comment by isidorn** [comment]
@meganrogge I had the same number of lines as the terminal which is 23.
If I had more lines in the editor I think that would mean that the decorations are smaller in the editor, not larger and that seems to be happening :)

**Comment by meganrogge** [comment]
to me, it looks like the decorations are closer together and not taking up as much vertical space in the scrollbar

see how the lower half is just empty?
![Screen Shot 2022-04-26 at 8 41 31 AM](https://user-images.githubusercontent.com/29464607/165339299-9748133b-0074-4c9c-8b4b-75134838a24a.png)

**Comment by meganrogge** [comment]
Here is what I see and they look similar IMO

https://user-images.githubusercontent.com/29464607/165348857-ea0dd8c7-01a1-4ca1-aa7d-df6066423235.mov

**Comment by meganrogge** [comment]
Strange because we are doing the right thing here, but `window.devicePixelRatio` is 1 here for me on a mac 🤔 . 
![Screen Shot 2022-04-27 at 10 56 43 AM](https://user-images.githubusercontent.com/29464607/165589655-3bf86f5e-6b5f-4bd9-a298-fbec8797d420.png)

**Comment by meganrogge** [comment]
We can make these heights different based on the number of lines in the buffer similar to what the editor does

**Comment by Tyriar** [comment]
Upstream issue: https://github.com/xtermjs/xterm.js/issues/3840
