### ISSUE TITLE
Alt-key to flip dropdown should flip menu as well?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148153]
Testing #148070

This is probably a more generic UX issue, but when I press Alt to flip the dropdown, I cannot flip the entries in the dropdown, only the primary action:

![Recording 2022-04-26 at 15 45 12](https://user-images.githubusercontent.com/900690/165314045-3125c858-f7e6-45e4-a5a0-1f448c1a66e3.gif)

**Comment by roblourens** [comment]
Well, if I was implementing it from scratch I wouldn't have even added the alt action. The menu is far more discoverable. But the alt action was added first a while bad, and now people are used to it, so I kept it so people can still trigger the most common action with a single click. I don't think applying alt to the full dropdown menu would be that useful, do you?
