### ISSUE TITLE
VSCode stuck at 'installing' phase while installing plugins.

### ISSUE THREAD

**Issue by ConsoleHack000** [Microsoft/vscode#14812]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.10
I simply can't install extensions on VSCode. When I find the desired extension and click Install, the button turns slightly grayish, the text becomes "installing" and its stuck like that forever. It does not freeze or anything, it doesn't install the extension, but I am able to use VSCode fine.
Somehow it did install one extension and I don't think it was visible before restarting it. I opened VSCode to see if it is so again and I saw one of the extensions I was trying to install. The issue *could* be internet connection as its pretty slow but it used to work fine sometime ago - now it just doesn't. I don't know if you'll be able to reproduce this but whatever.
Steps to Reproduce:
1. Open a freshly installed VSCode
2. Go to the extensions thing on the left sidebar
3. Find your desired extension
4. Click Install
5. Get stuck.

**Comment by joaomoreno** [comment]
Does it happen with everything you try to install? Even simple extensions such as themes?

**Comment by ConsoleHack000** [comment]
Yes. every single extension, no matter what it is

**Comment by ConsoleHack000** [comment]
Ok it took a good 20 mins to install an extension but it did. Does it really take this long?

**Comment by joaomoreno** [comment]
No, it shouldn't. It seems you have a really slow internet connection. Where are you located by the way?

cc @modigrv

**Comment by ConsoleHack000** [comment]
Ok it took a good 20 mins to install an extension but it did. Does it really take this long?

**Comment by ConsoleHack000** [comment]
my internet connection is around 7mb/s (megabit). isn't that enough?

**Comment by ConsoleHack000** [comment]
Ok now I sound very dumb but I completely reinstalled vscode (even though the one which didn't work was freshly installed) and... it works fine
