### ISSUE TITLE
Add a loading indicator for notebook language detector

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#148196]
Testing #148089

Noticed there is a few second delay of the cell updating to when the action is gone. I think this would be a great place to use the `loading~spin` icon as it's processing the change as the first few seconds you are not sure if clicking on it worked. The spinner will help in this situation.

https://user-images.githubusercontent.com/35271042/165363321-0651e2d3-82c1-45ca-b3d5-0259807e6313.mp4

**Comment by JacksonKearl** [comment]
Decided to make it fast instead of load :)

**Comment by rchiodo** [comment]
/verified?

It detects the language really fast but it doesn't auto switch anymore? I'm guessing this is on purpose.

**Comment by JacksonKearl** [comment]
Notebooks have never auto switched, but untitled editors still should. This bug did not affect untitled editors.
