### ISSUE TITLE
Find in Files problem when searching in specific file extensions (case sensitive extension name)

### ISSUE THREAD

**Issue by AlxSts** [microsoft/vscode#148173]
Issue Type: <b>Bug</b>

I have a folder in my laptop where I store Harbour Language source code files (xBase). Inside this folder, file names and extensions (.Prg) are written sometimes all lowercase, sometimes all upper case and other times mixed case.
![image](https://user-images.githubusercontent.com/17136246/165339947-dbaf1c34-f253-4b58-abb2-0f1aab2f552f.png)
I have opened this folder in Visual Studio Code and made some changes in three source files and, for each change, I’ve added a  comment containing the string ‘JOB#1094’.
![image](https://user-images.githubusercontent.com/17136246/165340091-eaa613d9-15c7-42e7-8584-56e748d9e28e.png)
When I was done, tried to find all changes I made, using VS Code Find in Files feature. I know I have three changed files. When I use Find in files and leave ‘Files to include’ empty, it works fine.
![image](https://user-images.githubusercontent.com/17136246/165340158-95ee0e02-9e3a-4a5f-bbfc-8f0464c2a73c.png)
If I ask VS Code to search only .PRG files, it shows up wrong results
![image](https://user-images.githubusercontent.com/17136246/165340240-c0d970bd-cb41-4326-966b-53e841f4c6db.png)
If I change the case of file types I want, other wrong result is shown.
![image](https://user-images.githubusercontent.com/17136246/165340335-ddae6e3e-ea2c-47ce-8862-ec02373efdd1.png)
In a short way, VS Code Find in Files is using a case sensitive search for the file extensions in file system, when it should use a case insensitive search.

Notepad++ v8.4 correctly shows three occurencies

![image](https://user-images.githubusercontent.com/17136246/165341390-6b1c1539-84f6-41d3-923c-781dcbb25758.png)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.618Z)
OS version: Windows_NT ia32 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.49GB free)|
|Process Argv|--crash-reporter-id fa68e302-8ab1-452c-97ec-98ffbbe7e12f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
numbered-bookmarks|ale|8.2.0
harbour|ape|1.0.3
vscode-dbf|ape|0.1.2
xml|Dot|2.5.1
harbour|eko|0.0.8
vscode-language-pack-pt-BR|MS-|1.66.3
data-workspace-vscode|ms-|0.2.0
mssql|ms-|1.14.1
sql-bindings-vscode|ms-|0.0.1
sql-database-projects-vscode|ms-|0.16.1
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaat:30438848

```

</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/10633
