### ISSUE TITLE
Sort by name in SCM view doesn't seem to change order

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#148187]
Testing #148078

Version: 1.67.0-insider (Universal)
Commit: ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af
Date: 2022-04-26T05:15:57.573Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0

Sort by name in SCM view doesn't seem to change order:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/12758612/165359620-e6ce1f6f-6617-44a6-b2b3-bbb136326634.png">

**Comment by joaomoreno** [comment]
@tanhakabir The repository sort options are in the `Repositories` submenu. The sort orders at the toplevel menu apply to changes within each repository only.

@lszomoru Maybe we should further classify those options as applying to changes only.

**Comment by lszomoru** [comment]
@joaomoreno, we could rename the label to "Sort Changes by Name", etc. if you think that would make things more clear.

**Comment by tanhakabir** [comment]
Ohh I see, then that does work for me! Thanks!
