### ISSUE TITLE
vscode.dev open file dialog thinks setting profile files are .txt

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#148182]
Testing #148058

When importing a setting profile on `insiders.vscode.dev` I notice that by default the filetype filter is set to `.txt` and `.text` instead of `.code-profile`:

![Screenshot showing the open file dialog requests a .txt file instead of a .code-profile file by default](https://user-images.githubusercontent.com/7199958/165356227-e506e658-75a6-4d33-ac91-80fee6513f70.PNG)

**Comment by sandy081** [comment]
Also same while exporting

<img width="416" alt="image" src="https://user-images.githubusercontent.com/10746682/165532670-30cec7ba-ca27-49df-a095-5890639855ee.png">

This works fine in Desktop, meaning, file dialog looks for `.code-profile` files only.  This is how I am invoking the picker

https://github.com/microsoft/vscode/blob/522d784b28326601bafb052c18fdf2fd4dc50b72/src/vs/workbench/contrib/profiles/common/profilesActions.ts#L109-L115

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode/issues/130035#issuecomment-895091067

I'm not sure what level the issue with `-` and `_` in file extension is at, but they couldn't be included in the suggested types.
