### ISSUE TITLE
inconsistencies with the "render whitespace" option

### ISSUE THREAD

**Issue by maravento** [microsoft/vscode#148169]
Does this issue occur when all extensions are disabled?: Yes/No
no

- VS Code Version:
1.66.2
- OS Version:
ubuntu 22.04

Steps to Reproduce:

Shows the same TAB and Spaces in the text (should show them different, since they are not the same)

![Captura de pantalla -2022-04-26 10-32-14](https://user-images.githubusercontent.com/14880802/165338275-d0e15ce1-4aba-44ea-8de0-d4415e06e142.png)

![Captura de pantalla -2022-04-26 10-30-36](https://user-images.githubusercontent.com/14880802/165338242-91725e0e-e6ab-4d1e-b9e9-39a6a3f12a82.png)

**Comment by StevieDicks** [comment]
Tabs are spaces:
![image](https://user-images.githubusercontent.com/50631116/165339246-93eaa8db-3362-4718-a471-4d692dad6203.png)

**Comment by maravento** [comment]
I have it like this and the problem persists
![Captura de pantalla -2022-04-26 10-54-09](https://user-images.githubusercontent.com/14880802/165341895-586851ec-ec64-4520-ba8b-3031263472ef.png)

**Comment by StevieDicks** [comment]
Interestingly if I uncheck and recheck "View -> Render Whitespace" then my whitespace properly renders and distinguishes tabs and spaces:
![image](https://user-images.githubusercontent.com/50631116/165341856-b84a183e-5823-4ad7-8086-3d0d2334e1c5.png)

My two settings are the same as the ones in your comment

**Comment by maravento** [comment]
I just did what you say and the problem persists

**Comment by IllusionMH** [comment]
Are you really have `\t` in content or just pressed <kbd>Tab</kbd> key?

Because later will insert spaces instead of `\t` depending on your indentation settings for file and setting like `editor.insertSpaces` and `editor.detectIndentation`.

**Comment by maravento** [comment]
Here is a discussion thread on the subject and the solution does not work with the current version https://stackoverflow.com/questions/30140595/show-whitespace-characters-in-visual-studio-code

**Comment by IllusionMH** [comment]
Not sure where to look on SO.
But that didn't answered actual question - do you really have `\t` character there (check by searching by regexp) or no?

![image](https://user-images.githubusercontent.com/1312662/165352120-271c2715-e5fb-4db2-b054-0322092c461e.png)
Works as expected in 1.66.2 (on Windows at least)

Try to copy content below and paste in into editor
```
this is a	tab
these are 4    spaces
```

**Comment by maravento** [comment]
solved. The problem is that if I create the file in vscode and hit TAB on the text, it shows dots instead.
If the file is created with another editor (sublime, etc) and I press TAB on the text, then when opening the file in vscode, it already shows the TAB correctly

![Captura de pantalla -2022-04-26 12-14-12](https://user-images.githubusercontent.com/14880802/165356171-0872f3fc-b69f-4150-8e2d-6aa790a711b2.png)
