### ISSUE TITLE
editor.quickSuggestions doesn't render in the Settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#148163]
Currently, the `editor.quickSuggestions` setting doesn't render in the Settings editor, because the Settings editor cannot handle settings with `anyOf` types.
The current accepted values are of the form
```jsonc
anyOf: [{
	type: 'boolean',
}, {
	type: 'object',
	properties: {
		strings: {
			anyOf: types,
			default: defaults.strings,
			description: nls.localize('quickSuggestions.strings', "Enable quick suggestions inside strings.")
		},
		comments: {
			anyOf: types,
			default: defaults.comments,
			description: nls.localize('quickSuggestions.comments', "Enable quick suggestions inside comments.")
		},
		other: {
			anyOf: types,
			default: defaults.other,
			description: nls.localize('quickSuggestions.other', "Enable quick suggestions outside of strings and comments.")
		},
	}
}],
```

Questions: 
1. What is the difference between `true` and `"on"` or `false` and `"off"` for each field?
2. Is `editor.quickSuggestions: true` just a shorthand for setting each field to `true`?

If we can change the setting configuration so that it is just an object with fields "strings", "comments", and "other", and the value for each field is an enum of options `["inline", "on", "off"]`, then the setting can render in the Settings editor UI. Along with changing the type over, we'll have to migrate the setting value for users still using the old setting value. I believe Emmet has example code for this process for the setting `emmet.extensionsPath`.

**Comment by jrieken** [comment]
Yeah, there is a lot of history: it started with a simple boolean, become an object with booleans, and it now an object with enum values. When working on https://github.com/microsoft/vscode/issues/126375 I tried to simplify the setting but without success, I couldn't get the editor to render this...

I'll try to simplify the setting to be a simple object with just (string) enum values

**Comment by jrieken** [comment]
@rzhao271 I have started on this, the setting is now just an [object](https://github.com/microsoft/vscode/blob/9c44dba7b022d46ca5c696f1e3642f9a2ad7dbfb/src/vs/editor/common/config/editorOptions.ts#L2932) but the settings editor still doesn't show it. What is missing?

**Comment by rzhao271** [comment]
I don't believe we currently support anyOf bool string, still. Are you expecting it to render as an enum like true, false, "on", "inline", "off"?
Also, `additionalProperties` needs to be set to `false`.

**Comment by jrieken** [comment]
> Also, additionalProperties needs to be set to false.

Cool. Thanks! That did make the difference here

<img width="562" alt="Screenshot 2022-05-05 at 09 22 08" src="https://user-images.githubusercontent.com/1794099/166878350-dc7ff1d2-7d32-4f2d-ba46-ba670641c596.png">
