### ISSUE TITLE
Markdown low level header preview font size too small

### ISSUE THREAD

**Issue by falrom** [microsoft/vscode#148100]
The default font size of low level header in markdown preview seems too small:

![image](https://user-images.githubusercontent.com/18463741/165211495-9f374bb0-851c-4147-b80b-857973fa4463.png)

No matter how low-level headings are, the font size should not be smaller than the body text. This makes confusion for people reading the documentation.

-----------------------------------

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.13.0-39-generic

**Comment by mjbvz** [comment]
This styling comes from the browser's usage agent:

<img width="621" alt="Screen Shot 2022-04-30 at 5 27 38 PM" src="https://user-images.githubusercontent.com/12821956/166123241-3fbdb0a5-33c5-4b8c-850e-a9a93139199f.png">

You see the same if you view a `h6` in a browser

Given that we haven't seen any other feedback on this, I'm inclined to keep using the browser's styling here
