### ISSUE TITLE
Markdown preview does not show a SVG image

### ISSUE THREAD

**Issue by ErikSchierboom** [Microsoft/vscode#1481]
Currently, when I include an SVG image in my Markdown file, the preview window does not correctly display it. Would be great if it did.

**Comment by bpasero** [comment]
@ErikSchierboom works for me on Mac, are you on another OS?

**Comment by ErikSchierboom** [comment]
@bpasero I'm also on a Mac. It's this file:

https://raw.githubusercontent.com/ErikSchierboom/ErikSchierboom.github.io/nameof/images/posts/csharp6-under-the-hood-nameof/dotnet-compilation.svg

Any I'm including it in my Markdown as follows:

`<img src="/images/posts/csharp6-under-the-hood-nameof/dotnet-compilation.svg" alt="Compilation of .NET code" class="image mod-full-width" />`

**Comment by bpasero** [comment]
@ErikSchierboom I think we dont support absolute paths, can you try moving it to the workspace and relative?

**Comment by ErikSchierboom** [comment]
@bpasero I copied the image to the same directory as the Markdown file, used a relative path (both with ./ and without), but it still won't display.

**Comment by bpasero** [comment]
Weird :)

**Comment by bpasero** [comment]
This is actually #1615 it seems.
