### ISSUE TITLE
SaveAll Linux keybinding Ctrl+Alt+S minimizes VS Code on Ubuntu

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14818]
- VSCode Version: 1.7.0 insiders
- OS Version: Linux Ubuntu 14.04

We added a keybinding for workbench.action.files.saveAll in the 1.7 release to Ctrl+Alt+S for Linux.

{ "key": "ctrl+alt+s",            "command": "workbench.action.files.saveAll" }

For Ubuntu, this is bound to OS command to minimizes the window and VS Code is minimized (not what the user is expecting).

Suggestion: bind Files: SaveAll to chord Ctrl+K S like on Windows.

**Comment by rebornix** [comment]
This issue is similar to #13567 which targets windows platform. That issue was initially assigned to @chrmarti first so I did so as well.

**Comment by Tyriar** [comment]
It actually seems to do nothing on Ubuntu 16.10, either at a OS level or saving all. What was the reason this keybinding was added anything? Is `ctrl+k s` used in any other editors?

**Comment by chrmarti** [comment]
Should have checked more carefully. The reason for adding this was: Users with auto-save disabled will end up with multiple dirty editors after global Replace All, Rename across files, possibly others. Binding Save All seemed like a good idea.

**Comment by Tyriar** [comment]
There's a bit of background to this, many people actually wanted it to be bound to ctrl+shift+s at launch because I believe VS is like that. We decided to align with Sublime's keybinding in this respect.

Given what we now know about ctrl+alt+s, I'm not sure there's much value in hiding it being a chord keybinding that isn't used in other programs.

**Comment by chrmarti** [comment]
Atom and ST don't bind it on Ubuntu 14.04 or Windows 10, only on OS X. They might not use multiple dirty editors in their regular workflow as much as we do.

**Comment by Tyriar** [comment]
I'd say align with Atom and ST in this respect, a new non-standard keybinding wouldn't be discoverable and people can always fallback on a custom keybinding if they need to.

On a personal note I don't use auto save or save all, when I use TS refactoring I go through my quick open editors list and save the files after making sure. Not the most efficient method but I'm concerned I have either untitled files or changes I don't want to save hanging around from earlier.
