### ISSUE TITLE
"TS died 5 times in the last few minutes"

### ISSUE THREAD

**Issue by sh-pq** [microsoft/vscode#148183]
Issue Type: <b>Bug</b>

I switched branch, had some deleted editors open which I closed, then opened some files in a sizeable Angular codebase (a few hundred TS files).

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|21, 10, 7|
|Memory (System)|16.00GB (0.68GB free)|
|Process Argv|--crash-reporter-id e70b19ff-bc0c-43f1-aba7-6f4b0afb8b71|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
map-replace-js|Yuk|0.2.2
es6-string-css|bas|0.1.0
hextorgb|dav|0.0.1
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
gitkraken-authentication|git|1.0.3
vscode-test-explorer|hbe|2.21.1
batch-rename-extension|Jan|0.0.5
svg|joc|1.4.17
vscode-peacock|joh|4.0.1
l13-diff|L13|1.0.3
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.22.0
cpptools|ms-|1.9.8
test-adapter-converter|ms-|0.1.6
vscode-typescript-tslint-plugin|ms-|1.3.4
debugger-for-chrome|msj|4.13.0
gulptasks|nic|1.3.1
vetur|oct|0.35.0
sass-indented|syl|1.8.19
language-stylus|sys|1.15.0
es6-string-html|Tob|2.12.0
vscode-icons|vsc|11.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by innellea** [comment]
I had the same issue, in my case, it was an incompatible .ts media file in a subfolder. I deleted and it solved the issue.

**Comment by mjbvz** [comment]
Closing as we need more info from the original poster to investigate
