### ISSUE TITLE
"Find all references" silently fails if a target exists more than once

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#148129]
Testing #147731

By accident I had a duplicated header in my markdown file.
The header was referenced by a few links. 
Trying "Find all references" on the second (duplicated) header did not result in the expected references. Only a self-reference was found.
For the first header all expected references were found correctly.

It would be helpful if this situation is somehow flagged as a problem.

**Comment by amunger** [comment]
Duplicate headers are differentiated when referencing them by adding a digit (and finding references for them seem to work for me).

e.g. if you have two markdown headers, both `# results`, you can reference them with `[results](#results)` and `[results](#results-1)`

**Comment by weinand** [comment]
@amunger I did not intend to have duplicated headers, so I do not need a way to differentiate them.
I've created a duplicated header by accident, so I was not aware of the problem.

I'm asking for some mechanism that indicates that there is a problem.

**Comment by amunger** [comment]
Duplicate headers are supported though, and make sense with something like:

```
# Topic 1

## More info

# Topic 2

## More info
```

I don't think we should make a change to start flagging that as a problem - although having a duplicate header within the same group is more likely a mistake.

**Comment by mjbvz** [comment]
Yes you can have duplicate headers but they must use number suffixed for them:

<img width="269" alt="Screen Shot 2022-04-30 at 5 23 47 PM" src="https://user-images.githubusercontent.com/12821956/166123134-cafb5c4f-fb88-4e57-9fd0-1e9d4a0523a7.png">

I tested this but please share some markdown if feel something is off about the existing behavior
