### ISSUE TITLE
Test: watch expressions drag and drop

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#14813]
- [x] any os @alexandrudima 

Complexity: 1

As per user request #14125, we now support reordering of watch expresions via drag and drop. Make sure this works as expected - both during a debug session and outside of a debug session.

**Comment by DinisCruz** [comment]
Hi, is there a test for this? (or was it a manual check)

**Comment by isidorn** [comment]
@DinisCruz this is a test item which we manually try out and check off at the end of a given iteration. In this case this was tested manually by Alex at the end of November
