### ISSUE TITLE
Hitting enter in find widget input box cycles through matches backwards

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#148108]
Testing #148060

In a regular text editor, type a query into the find widget and hit enter. Each enter will move the selection forward to the next match. 

In the terminal, hitting enter scrolls _backward_ through the terminal output. Additionally, the find widget's <> of <> text does not update to reflect which selection is currently highlighted.

**Comment by meganrogge** [comment]
This is not new behavior - find previous was called prior to this work when enter is pressed. I believe the reason for this is that we assume people are at the last part of the buffer and therefore want to see the prior result instead of next, which would wrap all the way to the start.

**Comment by meganrogge** [comment]
As for the text not updating, could you pls attach a gif?

**Comment by meganrogge** [comment]
Can repro the label not updating and that's covered by #148136
