### ISSUE TITLE
Unable to Run and Debug!!!

### ISSUE THREAD

**Issue by yoko-kurrrama** [microsoft/vscode#148219]
Compiled Java files, debug just keeps on loading... My file and code not running :( I already uninstalled and re-installed VS Code in my Mac Machine...

**Comment by farshid1** [comment]
Not sure if this is related but the debugger's run button is not starting the debugger anymore.

https://user-images.githubusercontent.com/5376505/165406507-1c1dbddb-e7f2-48c2-be7e-fd13b2419614.mov
