### ISSUE TITLE
Build Task for Clang does not end.

### ISSUE THREAD

**Issue by Nerwosolek** [microsoft/vscode#148200]
Issue Type: <b>Bug</b>

VSC version 1.66.2 Mac x86
default build task with clang on Mac stopped working after update.
Proper clang command string generated, terminal opened and command issued there but did not end.
"Building" icon spinning endlessly in info bar at the bottom.
The same command put into terminal (VSC one) will compile super fast successfully.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.56GB free)|
|Process Argv|--crash-reporter-id 8ea3aeb5-7459-4aa2-8fe8-57bf4a0e1788|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.5.0
pascal-formatter|ale|2.6.0
tasks-shell-input|aug|1.7.0
vscode-standardjs|che|1.4.1
doxdocgen|csc|1.4.0
githistory|don|0.6.19
language-forth|ftt|0.0.5
vscode-pull-request-github|Git|0.40.0
r|Iku|2.4.0
linter-gfortran|krv|2.6.2
mads|mir|0.0.5
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.10.0
cpptools-extension-pack|ms-|1.1.0
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
ossaction|pga|1.0.0
r-debugger|RDe|0.4.7
prolog|reb|0.0.4
vscode-scheme|sjh|0.4.0
html-preview-vscode|tht|0.2.5

(1 theme extensions excluded)

</details>

**Comment by tanhakabir** [comment]
I believe this issue should be filed with the C++ extension instead: https://github.com/microsoft/vscode-cpptools/issues

**Comment by Nerwosolek** [comment]
What kind of info would you like me to add?

**Comment by tanhakabir** [comment]
Sorry I would like you to open this issue in the other repo I have linked and if there's additional issues that can be found to be vscode specific we can add it to this issue.

**Comment by Nerwosolek** [comment]
OK. I was just pointed here by the VSCode itself, it had this icon to submit the bug.

**Comment by Nerwosolek** [comment]
In what section? Language Service?

**Comment by tanhakabir** [comment]
Yes sorry that is a catch all for all bugs but some bugs are extension specific such as C++ build tasks from the C++ extension. 

Debugging sounds right for this scenario.

**Comment by Nerwosolek** [comment]
OK. Issue created: https://github.com/microsoft/vscode-cpptools/issues/9241
