### ISSUE TITLE
Can't install local vsix in Codespace

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#148292]
Version: 1.67.0-insider
Commit: 410fe0fc7890ef563830bb86cbcd763995bfc65f
Date: 2022-04-27T05:19:04.915Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.4985.0 Safari/537.36 Edg/102.0.1235.1

1) create an extension vsix on  your local box
2) Open/create a codespace directly from GH, i.e. in the browser
3) Choose "Install from VSIX..." from the overflow menu in the extension view
4) In the file quick pick switch to "Local"
5) Select the vsix you created in step 1
-> You get an error "No Servers"

Java Console error:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/4674940/165579566-a6e54c9e-f1f3-4936-a142-4487743de2e3.png">

This scenario is documented here: https://code.visualstudio.com/api/advanced-topics/remote-extensions#installing-a-development-version-of-your-extension

**Comment by sandy081** [comment]
/Duplicate https://github.com/microsoft/vscode/issues/106914

Installing a VSIX in web+server setup is supported only when the VSIX is in the remote machine.
