### ISSUE TITLE
File nesting doesn't update correctly

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148257]
* have the config below
* have `index.ts`, `index.js`, and `index.js.map`
* .js and .js.map are children ✅ 
* from the context menu delete the `index.js` file
* :bug: the `index.js.map` file is gone

https://user-images.githubusercontent.com/1794099/165513829-2e4f4488-15e9-4fbc-a91b-9f2228297168.mov

```
"explorer.fileNesting.patterns": {
		"*.ts": "$(capture).js, $(capture).js.map, $(capture).d.ts",
		"*.js": "$(capture).js.map, $(capture).min.js, $(capture).d.ts",
		"*.jsx": "$(capture).js",
		"*.tsx": "$(capture).ts",
		"tsconfig.json": "tsconfig.*.json",
		"package.json": "package-lock.json, .npmrc, yarn.lock, .yarnrc"
	},
```

**Comment by gjsjohnmurray** [comment]
Maybe a duplicate of #147987

**Comment by JacksonKearl** [comment]
@jrieken thanks, do you have `explorer.fileNesting.expand` set to `false`?

**Comment by jrieken** [comment]
Confirmative
