### ISSUE TITLE
Stuck in recovery mode

### ISSUE THREAD

**Issue by Christianv93** [microsoft/vscode#148230]
ADD ISSUE DESCRIPTION HERE
My visual studio I am using for CS50P is stuck in recovery mode. I am unsure hoe to update the dev container, but there was an error when updating. Is there a way to return this to normal?
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Embedder: codespaces

**Comment by chrmarti** [comment]
Please report this at https://github.com/github/feedback/discussions/categories/codespaces-feedback. Thanks.
