### ISSUE TITLE
Lazy variable button has weird title

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148255]
* have a lazy variable
* hover over the 👁️ 
* 😕 the title is the entry, I would expect "Click to evaluate" or so

<img width="366" alt="Screenshot 2022-04-27 at 13 54 58" src="https://user-images.githubusercontent.com/1794099/165512978-52cc4df7-a66d-4a83-a0f0-b05a022f497f.png">

**Comment by roblourens** [comment]
Yeah, I can make the tooltip descriptive now
