### ISSUE TITLE
File nesting does not respect compact folders settings

### ISSUE THREAD

**Issue by Shigma** [microsoft/vscode#148244]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Darwin Kernel Version 21.2.0

Steps to Reproduce:

<img width="999" alt="image" src="https://user-images.githubusercontent.com/33423008/165483019-55e9dcfc-9a10-4484-b6fa-ad31a1cb6ede.png">

<img width="475" alt="image" src="https://user-images.githubusercontent.com/33423008/165482869-c2906bfd-cfc8-4475-b08a-fe75a68eccb7.png">

<img width="294" alt="image" src="https://user-images.githubusercontent.com/33423008/165482928-4d9da924-f206-447d-b3a5-7494d76d6db2.png">

**Comment by JacksonKearl** [comment]
This looks expected to me. The parent file (index.ts) should not be rendered as a compact folder, as it is not a folder. Not sure if I'm missing something here?

**Comment by Shigma** [comment]
I'm developing a project with a lot of workspaces, each of which has a similar structure (_src/index.ts_, _package.json_, _tsconfig.json_, etc). When I just saw this feature, I couldn't help but wonder if I can directly map each workspace folder to _src/index.ts_, and then the rest of the files can be expanded with the help of file nesting, so that I don't have to click a lot each time. (I know about `files.exclude`, but I don't plan to exclude package.json files directly, because I may modify them occasionally.)

You're right though, now I realize now that this is probably beyond the scope of the file nesting feature. If you don't care about the above, please close this issue.

Thank you for providing such a useful feature.
