### ISSUE TITLE
Hover tooltip/popover syntax color doesn't match selected theme

### ISSUE THREAD

**Issue by cnshenj** [microsoft/vscode#148204]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Windows 11 Version 10.0.22000.613

Steps to Reproduce:

1. Choose "Default Dark+" color theme
2. Add the following to settings:
   ```json
   "editor.semanticTokenColorCustomizations": {
     "[Default Dark+]": {
       "rules": {
         "parameter": "#98a0c8"
       }
     }
   }
   ```
3. Hover over a function that has parameter(s)
   ![image](https://user-images.githubusercontent.com/8441956/165372476-a82085d2-d592-47ea-bba9-e07c2873f9ab.png)
4. Or, hover over the parameter directly
   ![image](https://user-images.githubusercontent.com/8441956/165373286-f4e50913-8a58-4641-9ee1-e6fce66a5ca5.png)

**Comment by aeschli** [comment]
For 3. The `param` in the code is slightly darker as it is marked as unused. We don't show that information in the hover.
For 4. That's a known limitation as we run the grammar on a substring `param: string` and the grammar doesn't know the context.

No plans to improve on this.
