### ISSUE TITLE
Add Copy Cell Uri command to notebook cells

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148275]
Follow up from https://github.com/microsoft/vscode/issues/147183#issuecomment-1111087981

We have this sweet feature of deep-linking into a notebook cell but it's really hard to come up with these uris. Suggestion to add something to the Copy As or Notebook Cell menu.

<img width="967" alt="Screenshot 2022-04-27 at 16 41 47" src="https://user-images.githubusercontent.com/1794099/165544958-5b65ad1e-060b-4992-b16c-c50b697dfb84.png">

**Comment by joyceerhl** [comment]
Would've been super handy to have this, since I needed to deeplink to a specific cell in https://github.com/microsoft/vscode/issues/151168

**Comment by rebornix** [comment]
I think we should consider this especially that now we have "Share" menu cc @alexr00

**Comment by rebornix** [comment]
Put this on deck since we are going to have the Share menu working in notebooks from tomorrow's Insiders.

**Comment by roblourens** [comment]
I think this exists now
