### ISSUE TITLE
Multi-line comment marker ignores the first line.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#148210]
Testing #148048

![image](https://user-images.githubusercontent.com/3840081/165384595-24129024-8de5-47f2-b0c6-ce6240ab451b.png)

**Comment by alexr00** [comment]
The gutter bar should actually not show for this (it should only be on the line where there's a diamond in the gutter bar). The only way I can reproduce this is by selecting some text again around an existing comment. Is that what you have done here?

**Comment by karthiknadig** [comment]
@alexr00 You are correct, I am not able to repro this either.
