### ISSUE TITLE
TS features not working

### ISSUE THREAD

**Issue by vnenkpet** [microsoft/vscode#148233]
Issue Type: <b>Bug</b>

TS features keep freezing/not initializing. Can barely work.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|18, 17, 15|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 2bf36d89-d443-467e-bd52-7c97e26bfa25|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
nestjs-files|Abh|0.5.1
project-manager|ale|12.5.0
vscode-npm-import-package-version|axe|0.8.1
stories|ben|2.22.0
env-vscode|Ber|0.1.1
featurehighlight|Blo|1.8.0
gltf-vscode|ces|2.3.14
gitignore|cod|0.7.0
vscode-svgviewer|css|2.0.0
gitlab-ci-validator|cst|1.0.0
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.5.0
text-transform|flo|0.1.0
html-slim-scss-css-class-completion|gen|1.7.8
copilot|Git|1.13.5700
gitlab-workflow|Git|3.42.2
gc-excelviewer|Gra|4.2.54
vscode-drawio|hed|1.6.4
rest-client|hum|0.24.6
vscode-env|Iro|0.1.0
latex-workshop|Jam|8.25.0
plantuml|jeb|2.17.2
pubspec-assist|jer|2.3.2
chat|kar|0.35.0
graphql-for-vscode|kum|1.15.3
deno-std-lib-snippets|lau|0.0.8
rainbow-csv|mec|2.2.0
vscode-styled-components|mf|0.2.2
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.4
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
remote-containers|ms-|0.231.6
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5527
sqltools|mtx|0.23.0
language-liquid|nei|0.1.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.16.0
prisma|Pri|3.13.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.7.5
synthwave-vscode|Rob|0.1.11
vscode-uppercase|rui|1.0.1
vs-code-prettier-eslint|rve|3.1.0
vscode-coverage-gutters|rya|2.9.1
markdown-preview-enhanced|shd|0.6.2
svg-preview|Sim|2.8.3
open-in-browser|tec|2.0.0
gitblame|wad|8.1.0
fig|wit|0.0.6
vscode-import-cost|wix|3.3.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.13.24
vscode-open-in-github|ziy|1.3.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible with all extensions disabled?
You can try this with <kbd>F1</kbd> and `>Developer: Reload Window With Extensions Disabled`

Especially without `vscode-typescript-tslint-plugin`

**Comment by kkor** [comment]
I had the same problem, no autocomplete or imports or tserrors working. In addition the bottom statusbar icon left to "Typescript React" said that IntelliSense is operating in partial mode (https://code.visualstudio.com/docs/nodejs/working-with-javascript#_partial-intellisense-mode).

Disabling extensions did not help.

What helped me was to comment out this typescript setting:
typescript.tsserver.useSyntaxServer": "always",

If this doesn't help, try disabling all the other typescript related settings?

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
