### ISSUE TITLE
Consider use entire line decorations for multiline ranges

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148266]
Testing #148048

Considering that multiline ranges apply to entire lines, should the decorations span the entire width of the editor? It currently feels weird, especially on very short lines.

![image](https://user-images.githubusercontent.com/22350/165533712-039e7dfa-89c0-4102-8f2e-465a9bbffcd5.png)

**Comment by alexr00** [comment]
I'm used to it not stretching the full width of the editor since other code review tools I've used also only highlight until the end of the line. I'll do some looking and see what additional tools do.

@laurentlb, I know you have experience with other code review tools: what do you expect here?

**Comment by laurentlb** [comment]
In our tool, multiline comments don't necessarily apply to full lines, e.g. it can look like this:
![image](https://user-images.githubusercontent.com/485572/165593782-f5f4c65b-bc28-4a2e-94e6-ca98dd85bb93.png)

The screenshot of the first comment looks okay to me, except that the range probably shouldn't end with the newline character (either end somewhere on line 10, or stop at the end of line 9).

cc @albertelo

**Comment by alexr00** [comment]
Closing in favor of only highlighting the text.
