### ISSUE TITLE
Allow for "shellArgs" in Windows integrated terminal

### ISSUE THREAD

**Issue by madcampos** [Microsoft/vscode#14825]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Try to change `terminal.integrated.shell.windows` to pass additional parameters like variable expansion flag.
2. terminal fails with exit code 1

There is no current way to pass additional parameters to the Windows shell, it would be useful for configuration scripts and flags passed to the terminal, os other options passed to custom terminals.
In fact, the integrated terminal don't work with anything other than powershell and cmd.

**Comment by rebornix** [comment]
Assign to @octref first as I saw https://github.com/Microsoft/vscode/pull/11982

**Comment by octref** [comment]
> the integrated terminal don't work with anything other than powershell and cmd.

What shell are you using?

CC @Tyriar

**Comment by Tyriar** [comment]
This is fixed for Windows and coming to stable soon in v1.7.
