### ISSUE TITLE
Prompt to reload after modifying extension info doesn't always appear

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#148276]
Testing #148059

Sadly I cannot reproduce it reliably 😔 

https://user-images.githubusercontent.com/51720070/165544559-35e9455b-d6ee-4d44-8cbc-6e9e149d3158.mov

**Comment by sandy081** [comment]
I suspect in these cases when you do not see the modified prompt, cache would have been invalidated already.

@alexdima in these cases, is there another way to validate that cache is upto date?

**Comment by alexdima** [comment]
> I suspect in these cases when you do not see the modified prompt, cache would have been invalidated already.

I think the test plan item steps are misleading:
> * Update extension description property
> * Reload window and make sure you get a prompt that Extensions have been modified on Disk.
> * Reload window again and make sure no prompt is shown and updated extension description is shown

A prompt doesn't need to be always shown. A prompt is shown only if the information presented in the renderer is incorrect and no longer up-to-date with the disk contents. So the real question from me is if there is any way to validate that the new description "Updated description" is now used. How does the Extension editor do the rendering? Does it use the description from disk or from the marketplace?

**Comment by kimadeline** [comment]
These updated steps work 👍
