### ISSUE TITLE
Confusing use of gear icon

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#148287]
Testing microsoft/vscode-jupyter#9768

Not sure what extensions are capable of here, but the gear icon being an action (selecting the default kernel for the notebook type) and not opening some configuration was very confusing to me.

<img width="468" alt="image" src="https://user-images.githubusercontent.com/6561887/165556038-9877aab7-85be-40a2-841d-6695fd44b46b.png">

**Comment by rebornix** [comment]
I think this is already removed.
