### ISSUE TITLE
saving files, sometimes are not being saved

### ISSUE THREAD

**Issue by scgm11** [Microsoft/vscode#14829]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.1.0
- Extensions: HookyQR.beautify-0.5.3, Zignd.html-css-class-completion-1.0.3, abusaidm.html-snippets-0.0.18, cazzar09.Gradle-1.0.1, ceps.theme-darcula-0.0.4, christian-kohler.path-intellisense-1.1.0, eg2.vscode-npm-script-0.0.21, hars.CppSnippets-0.0.5, humao.rest-client-0.9.0, lukasz-wronski.ftp-sync-0.3.1, medzhidov.font-awesome-codes-html-0.0.3, mitaki28.vscode-clang-0.2.1, ms-vscode.cpptools-0.9.2, msjsdiag.debugger-for-chrome-2.1.3, redhat.java-0.0.6, tushortz.java-snippets-0.0.1, waderyan.gitblame-1.3.0

Steps to Reproduce:

1.
2.

**Comment by octref** [comment]
Dup of #14635, fixed in the upcoming release.
