### ISSUE TITLE
Intellisense C++ no longer works after installing/uninstalling the clangd extension

### ISSUE THREAD

**Issue by karimHarbaoui** [microsoft/vscode#148250]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66
- OS Version: Windows 11 

Steps to Reproduce:

1. Install clangd extension 
2. Uninstall clangd extension 
3. Intellisense is not working

**Comment by tanhakabir** [comment]
Hm if you run `Ctrl + Shift + P` and search for `clangd` do you see commands show up?
