### ISSUE TITLE
Multi Root Workspace Search Fails to Find Results when specifying "Files to Include"

### ISSUE THREAD

**Issue by crossan007** [microsoft/vscode#148299]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2 (User setup) and 1.67.0-insider (User setup)
- OS Version: Windows 10 Pro 21H1

Steps to Reproduce:
## Setup

1.  Create a multi-root workspace, with at least two items in the `folders` array
    *  The folders added here should be children of a folder which is a sibling of the workspace configuration JSON file.
    *  This folder and workspace arrangement may be useful when using `git worktree` to concurrently checkout multiple branches of a repository to multiple child-paths within a "workspace"
    * e.g. 
```
      - workspace.json
      - prodenvironment1\frontend
      - prodenvironment1\backend
      - stagingenvironmentB\frontend
      - stagingenvironmentB\backend
```

workspace.json:
```
{
	"folders": [
		{
			"name": "Prod/Frontend",
			"path": "prodenvironment1\\frontend"
		},
                {
			"name": "Prod/Backend",
			"path": "prodenvironment1\\backend"
		},
		{
			"name": "Staging/Frontend",
			"path": "stagingenvironmentB\\frontend"
		},
                {
			"name": "Staging/Backend",
			"path": "stagingenvironmentB\\backend"
		}
```

    
3.  Specify a `name` property for one or more objects in the `folders` array of the workspace configuration file to override the display name of the folder

## Bug Reproduction
5. Search for a known-present string with a blank "files to include" search term
  *  Confirm that the results appear with the "Display name" of the workspace folder present in the results heiriarchy
6. Set the "files to include" search term to the display name value of a workspace folder in which the string is known to exist
  *  Notice that the search term is not found
7. Set the "files to include" search term to the relative path of a workspace folder _without a preceding `./`_ in which the string is known to exist (taking care to try variations of the path separator `\`, `/` and `\\`)
  *  Notice that the search term is not found,
9. Set the "files to include" search term to the relative path of a workspace folder _with a preceding `./`_ in which the string is known to exist (taking care to try variations of the path separator `\`, `/` and `\\`)
  *  Notice that the search term is not found, AND a message appears in the search term text box stating "Workspace folder does not exist"

## Related issues:
*  https://github.com/microsoft/vscode/issues/127790
* https://github.com/microsoft/vscode/issues/68970
* https://github.com/microsoft/vscode/issues/52651
* https://github.com/microsoft/vscode/issues/121142
* https://github.com/microsoft/vscode/issues/61297

## Expected Behavior
*  Searching for a string with a "files to include" search restriction which fully or partially (possibly with a wildcard) matches either a workspace folder name or relative path returns all files containing the searched string where the files are within the path (fragment) defined in the "files to include' search restriction

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/61297

**Comment by crossan007** [comment]
@roblourens  thanks for the issue link.

Just in case anyone finds themself experiencing my issue, I'm linking the "resolution" here as well.
https://github.com/microsoft/vscode/issues/61297#issuecomment-432026807
