### ISSUE TITLE
File tree nesting in sidebar is misaligned (Seti theme)

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#14820]
- VSCode Version: 1.6.1

Example, annotated:

<img width="297" alt="x1" src="https://cloud.githubusercontent.com/assets/50314/19903301/8c8c8d50-a044-11e6-96db-d1704648b061.png">

VSCode makes it look like the .go files are all inside `testdata`, but they are in `querying`. The alignment is completely misleading. 

Fixed:

<img width="297" alt="x2 copy" src="https://cloud.githubusercontent.com/assets/50314/19903424/017f2be0-a045-11e6-9a1e-d00f5cf391fe.png">

Here's how Atom renders it:

<img width="297" alt="x3" src="https://cloud.githubusercontent.com/assets/50314/19902914/f52db43a-a042-11e6-8af8-d2ee675951aa.png">

**Comment by rebornix** [comment]
Dup of #11762 .

@atombender thanks for reporting these issues, you contributed quite a lot these days.
