### ISSUE TITLE
Second multi-line comment marker only marks the last line

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#148211]
Testing #148048

![image](https://user-images.githubusercontent.com/3840081/165385819-5430615b-f27a-4473-89c8-df1323f81644.png)

**Comment by alexr00** [comment]
This is actually intentional. We only show the gutter marker on the last line, but the background/border on the entire range of lines, to avoid a problem where it's hard to expand/collapse comments that have overlapping ranges.
