### ISSUE TITLE
Extension description not updated after reloading the window

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#148274]
Testing #148059

Updated the description in the Python extension's package.json, and this did not get reflected in the extension page:

https://user-images.githubusercontent.com/51720070/165544103-f82c1c9f-4921-4eba-bf23-77e97e39e5db.mov

**Comment by sandy081** [comment]
This is expected because we sync installed extensions with extensions in Marketplace and show the description from extension in Marketplace.
