### ISSUE TITLE
Cursor position and other decorations are not updated when inlay hints toggled

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#148215]
Issue Type: <b>Bug</b>

Related to  #148040

Code (just to have more decorations)
```js
console.log('Before', console.log('Before', console.log('Before', document.location)))
```

Set `"editor.inlayHints.toggle": "hide"` 
Put cursor somewhere in third `Before` and you should see cursor, 3 highlighted words, and horizontal guide for bracket pairs.
![image](https://user-images.githubusercontent.com/1312662/165388704-f7820937-2713-433b-8ace-f6bef61ce2d7.png)

Press <kbd>Ctrl</kbd>+<kbd>Alt</kbd> and you should see that positions of cursor, decorations, and guide are now in "random" places which is confusing.

![image](https://user-images.githubusercontent.com/1312662/165388821-e3d58a86-4ddf-4df2-8cda-2c5b502dde9d.png)

Same is true for `"show"` but in this case it's easier to get cursor/highlights to overlay inline hints.

VS Code version: Code - Insiders 1.67.0-insider (ab86e0229d6b4d0cb49cfd6747c92cafcd2bd4af, 2022-04-26T05:15:54.133Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (15.57GB free)|
|Process Argv|--crash-reporter-id 19aedffb-5c29-4248-9110-b5b20040c42f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jrieken** [comment]
You caught me there... This is current CSS only and skips the editor layout. Need to work on a proper solution

**Comment by jrieken** [comment]
Stretch for April

**Comment by IllusionMH** [comment]
/verified

I wasn't expecting that "Stretch for April" will be fixes this quick 🚀 

Works as expected for me and after update today I'm unable to reproduce #148207 as well 👍

**Comment by jrieken** [comment]
Thanks for the quick response
