### ISSUE TITLE
Cell language indicator is slow to appear

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#148220]
- Open a notebook
- Scroll down
- See that the language indicator appears after a noticeable delay

I think this is because the providers are stuck on the debounced language detection provider, @JacksonKearl. I think I see a way to improve it, I'll look into it

**Comment by JacksonKearl** [comment]
I actually have a fix rn (for #148196), so I should be able to take it

**Comment by roblourens** [comment]
Will the `await this._languageDetectionService.detectLanguage` be slow? If so, it's possible to do that in the background then fire the provider's change event. I just wrote a fix that works that way and can show you if you think we need it.

**Comment by JacksonKearl** [comment]
It's around 100ms with the old model and 1ms with the new one. Did you see fix I put in for the other issue?

**Comment by roblourens** [comment]
![Recording 2022-05-03 at 12 49 55](https://user-images.githubusercontent.com/323878/166522457-1bcb4c3e-1ea1-4b43-9ed9-6e7790128dcf.gif)

Still slow for me
