### ISSUE TITLE
multi-line comment marker shifts by one line after submitting the comment

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#148213]
Testing #148048

![image](https://user-images.githubusercontent.com/3840081/165385503-32e0535e-ff03-4091-9b07-7f2163e0bf5a.png)

**Comment by alexr00** [comment]
This looks like https://github.com/microsoft/vscode/issues/148210#issuecomment-1110823492 too. Can you walk me through the exact steps you took to end up with this?

**Comment by karthiknadig** [comment]
Not able to repro this. I may have selected some area of text.
