### ISSUE TITLE
Can't access comment actions when space is too narrow

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148279]
Testing #148048

![image](https://user-images.githubusercontent.com/22350/165547266-a548ff7a-8cee-4f8c-8f58-1a0480d8deaa.png)

**Comment by meganrogge** [comment]
I wonder if the font size should shrink when it's this narrow so the text doesn't get cut off?
![Screen Shot 2022-04-29 at 9 52 56 AM](https://user-images.githubusercontent.com/29464607/165989006-9c84a6ab-0646-419e-b4da-a73f31b427e5.png)

**Comment by alexr00** [comment]
@meganrogge did you try moving your cursor? The `+` should go away when the cursor is no longer on that line.

**Comment by meganrogge** [comment]
I expected the white decoration to go away. Is that not what we want?

**Comment by alexr00** [comment]
The decoration with the `+` (marked by a yellow circle below) should go away, the narrow rectangle that indicates a commenting range (a portion of which is marked by a yellow rectangle) should not go away.

![image](https://user-images.githubusercontent.com/38270282/166264561-205d6ec2-9314-4ae2-b988-74a9f009a711.png)

**Comment by meganrogge** [comment]
Why do the white lines remain when there is no comment there?

**Comment by alexr00** [comment]
The white lines indicate that there is an extension which supports commenting on that range.
