### ISSUE TITLE
'Copy Cell Up' seems missing

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148236]
Discovered the copy/move command in the cell context menu. Logic tells me that there should be "Copy Cell Up"

<img width="577" alt="Screenshot 2022-04-27 at 09 29 23" src="https://user-images.githubusercontent.com/1794099/165465085-e1f5137f-ac5a-4015-b44b-69eb32c10d06.png">

**Comment by roblourens** [comment]
We've been trying to keep this list minimal since it's already very full. Copy up/down are... basically the same thing, so I left Up out. Move up/down and Join previous/next are actually different actions. Do you think missing Copy Up is a problem?

**Comment by jrieken** [comment]
Oh, now I get it. How about calling it "Duplicate Cell" then?

**Comment by roblourens** [comment]
I want to match the editor commands "Copy Line Up/Down" for when people look for these in command palette or keyboard shortcuts, although "duplicate" might have been better for those too since copying is something else.

**Comment by roblourens** [comment]
I'm going to leave it for consistency with the editor
