### ISSUE TITLE
Rendered markdown note show additional lines 

### ISSUE THREAD

**Issue by Andd54** [microsoft/vscode#148285]
Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.4.0
This is the markdown under editing mode:
<img width="1415" alt="image" src="https://user-images.githubusercontent.com/70097898/165521273-bfb0e595-9fc8-49ca-a62a-1052101b2592.png">
This is the markdown after exit editing mode:
<img width="1454" alt="image" src="https://user-images.githubusercontent.com/70097898/165521213-1f6e9ec5-fc56-4214-aabb-05406a2a8710.png">

**Comment by Andd54** [comment]
Thank you

**Comment by mjbvz** [comment]
Please share a file (or text) that demonstrates the issue 

/needsMoreInfo

**Comment by Andd54** [comment]
If the length of the markdown in a single markdown box exceeds a certain amount of volume, when I exit editing, it will show as the image presents:
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/70097898/166612290-0285e3c0-1d44-4690-973a-ba29c8f2fa5b.png">
However, when there are a limited amount of texts, the situation does not exist.
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/70097898/166612411-a29a7b07-7d3b-4a05-b037-89b510a27970.png">

**Comment by Andd54** [comment]
For the detail part, I am not that sure, but I am sure it has something to do with the number of characters.

**Comment by mjbvz** [comment]
Please share the notebook file itself

**Comment by Andd54** [comment]
This is my notebook file on Google Drive:
https://drive.google.com/file/d/1u0nBvCiuavEDd13xe37CyRxgWU76VTF2/view?usp=sharing

**Comment by mjbvz** [comment]
Thanks @Andd54!
