### ISSUE TITLE
Multiline comment doesn't work if I click the first line's decoration to create it

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148277]
Testing #148048

![Recording 2022-04-27 at 16 50 37](https://user-images.githubusercontent.com/22350/165546614-cd897797-20e6-4b8c-912d-f899ed883ef6.gif)

**Comment by alexr00** [comment]
I haven't been able to repro this. Does this repro for you every time?

![Recording 2022-04-28 at 15 38 42](https://user-images.githubusercontent.com/38270282/165765315-466ba21b-b7f9-4350-9f56-e517262c5fdf.gif)

**Comment by alexr00** [comment]
Closing as not-reproducible.
