### ISSUE TITLE
Switching tabs loses scroll position

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#14822]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.0.0
- Extensions: DotJoshJohnson.xml-1.6.0, Shan.code-settings-sync-2.3.5, donjayamanne.python-0.5.0, groksrc.haml-0.0.2, lukehoban.Go-0.6.47, ms-vscode.csharp-1.4.1, rebornix.Ruby-0.10.1

Steps to Reproduce:

1. Open several files (my tests were all C# / .cs files)
2. Click on some line in a file
3. Scroll, in the that same file, do another location
4. Click another tab
5. Click on tab of the original file -- note that the window is positioned to the cursor (the line you clicked) and not the last scroll position

**Comment by rebornix** [comment]
As I can't reproduce this issue, can you try run vscode without any extensions by `code --disable-extensions` and see if it's still there.

**Comment by brendandixon** [comment]
@rebornix I'll close this for now. With the 1.7 update, it seems to no longer occur.

**Comment by rebornix** [comment]
@brendandixon thanks for your help!
