### ISSUE TITLE
`code .` spams console and listens to Ctrl-C

### ISSUE THREAD

**Issue by apple502j** [microsoft/vscode#148246]
Issue Type: <b>Bug</b>

1. Run `code .` on command prompt

Expected: No logs appear on the command prompt, and pressing Ctrl-C on the command prompt does not close VSCode.

Actual: The command prompt gets spammed with logs (see below), and pressing Ctrl-C on the command prompt closes VSCode. Note that this does not occur when running `code . > nul`.

```
[main 2022-04-27T09:15:23.110Z] window#load: attempt to load window (id: 1)
[main 2022-04-27T09:15:23.192Z] update#setState idle
[main 2022-04-27T09:15:23.370Z] ExtensionHostStarterWorker created
[main 2022-04-27T09:15:25.157Z] window#load: window reported ready (id: 1)
[main 2022-04-27T09:15:25.421Z] Starting extension host with pid 1696 (fork() took 49 ms).
[main 2022-04-27T09:15:25.422Z] ExtensionHostStarterWorker.start() took 53 ms.
```

Video:

https://user-images.githubusercontent.com/33279053/165490272-eabe6bbc-84d8-400f-9aff-6c978e876a06.mp4

(While this is not displayed, VSCode opened in the background but closed when I pressed Ctrl-C at 0:10)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.618Z)
OS version: Windows_NT ia32 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.64GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.2
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
atom-keybindings|ms-|3.0.9
js-atom-grammar|ms-|0.1.14
datapack-language-server|SPG|3.3.29

(1 theme extensions excluded)

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/66750
