### ISSUE TITLE
Markdown tokenize issue after using # in triple ticks

### ISSUE THREAD

**Issue by ErikSchierboom** [Microsoft/vscode#1482]
Some Markdown dialects support specifying the language when using triple backticks (```) to mark a section of text as code. One popular example of this is the Jekyll blogging engine. At the moment, the syntax highlighting breaks down when using triple backticks.

Consider the following code:

<pre>
```c#
using System;
					
public class Program
{
	private static DateTime Today = DateTime.Now;
}
```

## Restrictions

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget ante dapibus, egestas leo nec, convallis ligula. Proin tempor augue fermentum ex rhoncus, eget faucibus purus vehicula. Suspendisse cursus auctor quam, non tristique odio lacinia vel. Pellentesque cursus neque posuere vestibulum aliquam. Nam lacus odio, suscipit vel consequat sagittis, auctor nec nisl. Maecenas ac justo nunc. Aenean efficitur aliquam odio, sit amet consequat nisi congue at. Suspendisse pellentesque enim non tortor bibendum, ac posuere justo iaculis. Nullam vulputate diam non justo tempus aliquet vitae non turpis.
</pre>

This is displayed as follows:

![image](https://cloud.githubusercontent.com/assets/135246/11914025/2b330878-a675-11e5-9a44-70bdc677622b.png)

One can clearly see that the parsing breaks down after handling the code section.

**Comment by bpasero** [comment]
Hm, I suspect the issue here is the trailing # for C#, does it work when you pick "csharp" instead?

**Comment by ErikSchierboom** [comment]
@bpasero Yes, that's it. Changing it to "csharp" fixes the problem. I'll try to create a PR for this :)
