### ISSUE TITLE
Ctrl+Alt+ UpArrow/DownArrow  Creates additional cursor

### ISSUE THREAD

**Issue by joshualemli** [Microsoft/vscode#14824]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: none

Steps to Reproduce:

1. Open file to edit
2. Ctrl+Alt+ (UpArrow or DownArrow)

**Comment by rebornix** [comment]
hey @joshualemli after press ctrl+alt+up, try press keys /a-zA-Z0-9/ and you will see it's our multi cursor feature.
