### ISSUE TITLE
Pressing Enter creates line with bad indent

### ISSUE THREAD

**Issue by kato033** [microsoft/vscode#148256]
Issue Type: <b>Bug</b>

Please look this,

![image](https://user-images.githubusercontent.com/97441570/165941642-8f743bd8-2ede-456b-a7ef-d01afce3a3fd.png)

Line 2: `SP` `SP` `Tab` "Text"
Line 3: `Tab` `SP` `SP`  .... This is auto indent line.

-------
以下のような行で、`Enter`で改行すると自動インデントとなりますが、その時のインデントが不適切ではないでしょうか?
(表示上、`SP`:空白, `Tab`: タブ)

`SP` `SP` `Tab`ABC`Enter` とすると、
`Tab` `SP` `SP`  となる。

**Comment by kato033** [comment]
I update this issue. But, It is automaticaly closed.  Why?

Please look this updated isuue.

**Comment by alexdima** [comment]
@kato033 What are the steps to reproduce? What is happening versus what you would expect to happen?

**Comment by kato033** [comment]
First line is, (`<SP>` is white space, `<Tab>` is Tab code)
`<SP>` `<SP>` `<Tab>` "Text" + `Enter`-key 

Actual input is: (The above procedure removes the white space.)
[Tab]-key, "Text", (move coursor position to the beginning of line), [Space][Space], (move coursor position to end of line), [Enter]

The next cursor position is invalid.

Please look the image of issue.

I think, this is not serious but incorrect behavior.

**Comment by kato033** [comment]
Thanks.

**Comment by TylerLeonhardt** [comment]
@alexdima can we have some verification steps?

**Comment by alexdima** [comment]
Posting [the steps](https://github.com/microsoft/vscode/issues/148256#issuecomment-1122364649) again:

Thank you for the extra information. Here are simplified steps:
* have a file with the contents `<space><space><tab>`
* press <kbd>Enter</kbd>
* if indentation is configured with tabs, the new line will contain `<tab><space><space>`. <---- **this is a bug, the result should be `<tab>`** such that the second line aligns with the first line
* if indentation is configured with spaces, the new line will contain `<space><space><space><space><space><space>` <--- **this is a bug, the result should be `<space><space><space><space>`** such that the second line aligns with the first line
