### ISSUE TITLE
Tooltip text wrapping cuts words, has scroll bar

### ISSUE THREAD

**Issue by use-strict** [Microsoft/vscode#14827]
- VSCode Version: 1.6.1 (and insiders as well)
- OS Version: linux/win

See old tooltip (1.4, top) vs new tooltip (1.6.1, bottom)

![Tooltips](http://i.imgur.com/TQwgfkt.png)

I have a few problems with this tooltip:
1. The wrapping seems to be break-word, making some symbols hard to read.
2. There is a horizontal scrollbar inside the tooltip (Could editor.fontSize affect this?)
3. The tooltip is not stable on mouse move out/over repeatedly. It changes width and wrapping.

Some subjective observations as well:
- Was the max-width reduced?
- I think the contrast is better with the darker background.

**Comment by joaomoreno** [comment]
#14541

**Comment by use-strict** [comment]
@joaomoreno , I don't know if the word-wrap issue has the same cause as the horizontal scrollbar, but if not it should be tracked separately. In my ignorance, I imagine it shouldn't be more than removing a "word-wrap: break-word;" rule.

**Comment by joaomoreno** [comment]
It is quite a bit more. 👍
