### ISSUE TITLE
Notebook does not stop after setting dispatch setting

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#148201]
Testing #148089

<img width="539" alt="CleanShot 2022-04-26 at 11 32 09@2x" src="https://user-images.githubusercontent.com/35271042/165368443-e9b10de3-d877-4f6b-9783-911f9c5eeeb8.png">

1. use handy dandy notebook
2. set `dispatch` setting to:
```json
"handydandy-notebook.dispatch": {
    "css": [
      "html"
    ]
}
```
3. try running a cell with that language
4. :bug: unable to stop cell

I was just playing around with the setting and unsure of how to use it and ran into an endless loop without being able to stop

**Comment by JacksonKearl** [comment]
Bug on the notebook, it's experimental and doesn't handle errors well... unfortunately I can't publish to it anymore since we lost ability to create marketplace PAT's :( 

Will maybe republish under my personal account.
