### ISSUE TITLE
Rubber band scrolling for MacOS

### ISSUE THREAD

**Issue by bmidget** [Microsoft/vscode#14823]
Feature request.

Native Mac apps rubber band when reaching the end of scrolling. It's one of the best features of macOS UI. But VSC does not rubber band when scrolling to the end of a document.

VSC should do native rubber banding when scrolling to top and bottom of a document on macOS.

**Comment by coreh** [comment]
This would probably require some custom touch/gesture recognition code on OS X, but would be pretty cool!
