### ISSUE TITLE
Renaming file paths on windows replaces backslashes in path with equivalent uri encoding

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#148223]
Testing #147738

1. ![image](https://user-images.githubusercontent.com/13199757/165409740-f041e23b-c787-4899-b161-675b5b57749c.png)

2. ![image](https://user-images.githubusercontent.com/13199757/165409775-55608fb4-c0c2-4af8-b82a-250fe7ccf160.png)

3. ![image](https://user-images.githubusercontent.com/13199757/165409812-bcbd5b14-5d52-47bf-a3dc-309bffa03dd3.png)

I prefer it to be 
![image](https://user-images.githubusercontent.com/13199757/165409902-ea60d9c5-8df2-4755-8621-0e0da6fedc76.png)
as it is cleaner.

**Comment by mjbvz** [comment]
This should have already been fixed
