### ISSUE TITLE
Open the README for extension while/after installation

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#14826]
Once the user finds an extension in the extension viewlet, clicks on install, it would be nice to have the Extension page (with the readme etc) open up while the extension installs.
At present, this comes up only if the extension list item is selected.
Clicking on the "Install" button should trigger the same action

**Comment by joaomoreno** [comment]
I don't agree. The install action is there specifically as a _fast track_ for installing an extension without taking away your currently open editors.
