### ISSUE TITLE
Error: your 131072x1 screen size is bogus. expect trouble

### ISSUE THREAD

**Issue by oliversalzburg** [microsoft/vscode#148346]
Issue Type: <b>Bug</b>

When I try to commit from VS Code (which invokes a pre-commit hook with lint-staged in the background), the commit fails. Inspecting the command output shows an error being surfaced from `pidtree`.

Related: https://github.com/okonet/lint-staged/issues/1147 https://github.com/microsoft/vscode/issues/35798

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file -
Running lint-staged...
(node:20444) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] .lintstagedrc.js — 5 files
[STARTED] package.json — 1 file
[STARTED] *.{js,json,md,sh,ts,yml} — 5 files
[STARTED] yarn prettier-package-json --write
[STARTED] prettier --write
[FAILED] prettier --write [FAILED]
[FAILED] prettier --write [FAILED]
[SUCCESS] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[SUCCESS] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[SUCCESS] Cleaning up temporary files...

✖ prettier --write:
[error] No parser could be inferred for file: packages/documentation/.scripts/build.sh
[error] No parser could be inferred for file: packages/documentation/.scripts/serve.sh
package.json-scripts.json 42ms
packages/documentation/docs/reference/Repository Scripts/index.md 77ms
packages/documentation/package.json 3ms
/home/oliver/projects/monolit/.yarn/cache/pidtree-npm-0.5.0-ed08283e89-371cd14bbc.zip/node_modules/pidtree/lib/bin.js:42
      return done(new Error(stderr));
                  ^

Error: your 131072x1 screen size is bogus. expect trouble

    at ChildProcess.<anonymous> (/home/oliver/projects/monolit/.yarn/cache/pidtree-npm-0.5.0-ed08283e89-371cd14bbc.zip/node_modules/pidtree/lib/bin.js:42:19)
    at ChildProcess.emit (node:events:526:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Socket.<anonymous> (node:internal/child_process:451:11)
    at Socket.emit (node:events:526:28)
    at Pipe.<anonymous> (node:net:687:12)
```

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3598)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (38.31GB free)|
|Process Argv|--crash-reporter-id f825acfe-92fa-4526-a38a-f8815cf9f7ea|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.13GB (41.26GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.13GB (41.26GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3597)|
|Memory (System)|50.13GB (41.26GB free)|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
javascript-ejs-support|Dig|1.3.1
terraform|has|2.22.0
vscode-drawio|hed|1.6.4
output-colorizer|IBM|0.1.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.11.0
tsl-problem-matcher|amo|0.6.2
vscode-zipfs|arc|3.0.0
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.2
javascript-ejs-support|Dig|1.3.1
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vs-code-xml-format|fab|0.1.5
shell-format|fox|7.2.2
vscode-graphql|Gra|0.4.4
terraform|has|2.22.0
vscode-esformatter|how|1.6.0
output-colorizer|IBM|0.1.2
svg|joc|1.4.17
vscode-random|jre|1.11.0
template-string-converter|meg|0.6.0
code-beautifier|mic|2.3.3
vscode-docker|ms-|1.22.0
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
test-adapter-converter|ms-|0.1.6
vscode-js-profile-flame|ms-|1.0.0
vscode-paste-image|mus|1.0.4
monolit|Oli|0.1.1
vscode-yaml|red|1.7.0
vscode-icons|vsc|11.11.0
docker|vsc|1.0.0
yaml|vsc|1.0.0

(2 theme extensions excluded)

</details>

**Comment by oliversalzburg** [comment]
Seems like it was just a configuration error and a misleading error message.

**Comment by juliomrc** [comment]
@oliversalzburg Can you elaborate on what was the configuration problem?
I am running into a similar case with lint-staged and committing from VSCode.
