### ISSUE TITLE
Go to references/Go to definition support for markdown slugs and references

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#148301]
Testing #147738

I wish I was able to put my cursor on a slug of a file path, hit F12 and have it jump over to the heading in the other file.

Additionally, if I use link reference references:
```
[ref]

[yes][ref]

[ref]: /Hello.md
```

I should be able to F12 on any of those "refs"

**Comment by mjbvz** [comment]
@TylerLeonhardt I believe `find all references` should work in both cases

`go to definition`/`F12` support is currently not implemented but is tracked by #148017

Please let me know if I misunderstood the issue
