### ISSUE TITLE
the setting "debug.openDebug" did not perform as expected

### ISSUE THREAD

**Issue by ZhuangQu** [microsoft/vscode#148333]
Issue Type: <b>Bug</b>

2

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.54GB free)|
|Process Argv|D:\\OneDrive\\桌面\\LaTeX.code-workspace --crash-reporter-id 3b7c6f93-a58d-47eb-acad-8ac2c4e25687|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
latex-workshop|Jam|8.25.0
rainbow-csv|mec|2.2.0
vscode-language-pack-zh-hans|MS-|1.66.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
remote-ssh|ms-|0.78.0
markdown-preview-enhanced|shd|0.6.2
vscode-autohotkey2-lsp|thq|1.3.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

My `debug.openDebug` is set to `openOnDebugBreak`, whose expected behavior is to open the debug view when the first (active) breakpoint is encountered. However, when no breakpoint exist, after pressing F5 (start debug), the debug view is also opened. This happens just after opening a workspace. In other words, `openOnDebugBreak` behaves just like `openOnSessionStart`, which is not expected.

**Comment by ZhuangQu** [comment]
@roblourens Can you reproduce the situation I described

**Comment by roblourens2** [comment]
https://github.com/microsoft/vscode/issues/140089
