### ISSUE TITLE
Shell integration breaks zsh on Linux remote

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#148312]
1. Remote from Windows to Linux where zshell is installed, with shell integration turned on
2. Create a new (zsh) terminal. Terminal remains empty 🐛 
3. Create a bash terminal. That works ✅ 
4. Disable shell intergation and create a zsh terminal. That works ✅ 

Left side was created with shell integration on, right side was create 

![](https://memes.peet.io/img/22-04-c0ce35b8-0764-458b-b3ee-b00e659e5618.png)

Let me know if there's any addition info to get.

**Comment by meganrogge** [comment]
It would be helpful if you could turn on trace logging and provide the logs
