### ISSUE TITLE
Link is changed when clicked in vscode terminal and opened in the browser

### ISSUE THREAD

**Issue by epoberezkin** [microsoft/vscode#148375]
Issue Type: <b>Bug</b>

If the link contains certain escaped characters they are replaced with non-escaped characters.

For example, when the link https://microsoft.com/#abc%3D is clicked in vscode terminal it becomes https://www.microsoft.com/en-gb/#abc= in the browser (and it does not change if it is copy-pasted).
The assumption that these two links are equivalent is incorrect, in general, as some parsers are unable to cope with unescaped characters.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:47:29.396Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.
