### ISSUE TITLE
TreeView.reveal not collapse the TreeItem

### ISSUE THREAD

**Issue by MikeSchulze** [microsoft/vscode#148359]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64.0-insider (Universal) Commit: 16856037e075275f53b25b7e2dec2303e8e25728
- OS Version: macOS 11.3

Steps to Reproduce:

1. using `_tree.reveal(node, { select: true, focus: true })` with node has set `node.collapsibleState` == Expanded
2. using `_tree.reveal(node, { select: true, focus: true })` with node has set `node.collapsibleState` == Collapsed

The treeItem is expanded at first but never collapsed.
My TreeNode has a unique id set.

here my listener i user to select and focus a node, the node has the correct  collapsibleState but collapse is not working
```
let revealQueue = Promise.resolve();

this._treeProvider.onDidChangeSelection(node => {
            if (node) {
                console.log(`Select node ${node.name} ${node.collapsibleState}`);
                revealQueue = revealQueue.then(() => this._tree.reveal(node, { select: true, focus: true }));
            } else {
                this._tree.selection.map(async node => {
                    revealQueue = revealQueue.then(() => this._tree.reveal(node, { select: false }));
                });
            }
        });
```
The console output looks like. Starting with `BoolAssertTest` == Expanded and finally == Collapsed.
The child nodes has  collapsibleState == NONE
```
Select node BoolAssertTest 2
Select node IsTrue 0
Select node IsFalse 0
...

Select node Interrupt_IsFailure 0
Select node BoolAssertTest 1
```

**Comment by MikeSchulze** [comment]
if it need you can inspect my extension https://marketplace.visualstudio.com/items?itemName=mikeschulze.gdunit3

**Comment by alexr00** [comment]
Once the tree is has been rendered you cannot update the `collapsibleState` as this could interfere with the collapse/expand state that the user has set.

**Comment by MikeSchulze** [comment]
Sorry the API of `tree.reveal()` is the supposed method to control select and expand state. It acceptes a flag for expandt (true|false) to for my understanding this is the related method to control the expand state via a program. 
Why this shold not allowed?
