### ISSUE TITLE
Left-side tree file view collapsing when opening file 

### ISSUE THREAD

**Issue by apham727** [microsoft/vscode#148362]
Issue Type: <b>Bug</b>

When opening a tsx file (though this might just be specific to our project), the tree view will initially expand to show the open file in the tree view. However, after click around in the file, the tree view will sometimes collapse to the root folder, and I have to re-open the file to get it to show up in the tree view 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.59GB (28.18GB free)|
|Process Argv|C:\\repos2\\AzureUX-IaaSExp\\IaaSExp-Compute.code-workspace --crash-reporter-id 1de23038-85e5-4a16-bc22-e2662e528723|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
tslint|eg2|1.0.47
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
project-tasks|hau|1.0.0
copy-filename|jac|2.3.2
vscode-edit-csv|jan|0.6.8
theme-monokai-pro-vscode|mon|1.1.20
vscode-bicep|ms-|0.5.6
vscode-docker|ms-|1.21.0
csharp|ms-|1.24.4
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azurecli|ms-|0.5.0
azurerm-vscode-tools|msa|0.15.6
material-icon-theme|PKi|4.15.0
markdown-preview-enhanced|shd|0.6.2
vscode-icons|vsc|11.10.0
save-and-run|wk-|0.0.22
markdown-all-in-one|yzh|3.4.0
material-theme|zhu|3.13.21

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135

```

</details>

**Comment by JacksonKearl** [comment]
Are you using multi root wokrspaces?
