### ISSUE TITLE
Setting/Defining Extension Configuration (if one does not want to use VSCode's default settings/configuration)

### ISSUE THREAD

**Issue by anasir975** [microsoft/vscode#148338]
I would like to use this platform to propose an idea (please let me know if it already exists and I have somehow missed it).

I would like you to add a feature where **one can set the configurations or settings of any extension using package.json file** without having to go to Preferences->Settings->Extensions and making the changes in configuration for that particular extension. It would be great if this can be automated and done through package.json file.

**Comment by anasir975** [comment]
@sandy081 will you please assist on this issue?

**Comment by sandy081** [comment]
> one can set the configurations or settings of any extension using package.json file

Not sure if I understand this. Can you please provide an example?

**Comment by anasir975** [comment]
As you can see in the picture posted below, Gitlens: Show Welcome on Install is set to true by default by VSCode. Can I force change this value to false in package.json? I mean I do not want to go to Preferences->Settings->Extensions->Gitlense again and again and make the changes. I want to automate the process.

![vscode](https://user-images.githubusercontent.com/97193092/165830803-9c02dd88-ae2a-4a01-8f53-ffad9b17c311.png)

**Comment by sandy081** [comment]
> For instance, by default the setting gitlens.showWelcomeOnInstall is set to true by VSCode. Is there any way I can force this setting to false in package.json?

Yes, you can override defaults using `configurationDefaults` contribution point. Please refer https://code.visualstudio.com/updates/v1_63#_configuration-defaults-overrides
