### ISSUE TITLE
([^\n]) matches empty strings

### ISSUE THREAD

**Issue by LinAGKar** [microsoft/vscode#148345]
Issue Type: <b>Bug</b>

Steps:

1. Go to the global search
2. Enable regex search
3. Search for `([^\n])`

This should match any single character that's not a newline (same as `[^\n]`), however it also returns zero-character matches at ends of lines (getting stuck on a loop where it matches the same position thousands of times).

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.17.4-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 1|
|Memory (System)|62.71GB (10.76GB free)|
|Process Argv|--disable-features=SendMouseLeaveEvents /home/linus/git/work/apps-dev1/apps-dev1.code-workspace --crash-reporter-id 535de6ce-c9a7-475b-b42a-4c7e671b2334|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.2.4
meson|asa|1.3.0
better-toml|bun|0.3.2
texinfo|cis|0.2.4
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.6
vscode-opencl|gal|0.7.3
gitlab-workflow|Git|3.42.2
language-cython|guy|0.0.7
bash-ide-vscode|mad|1.13.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
vscode-typescript-tslint-plugin|ms-|1.3.4
vscode-yaml|red|1.7.0
rust|rus|0.7.8
trailing-spaces|sha|0.3.1
markdown-preview-enhanced|shd|0.6.2
code-spell-checker|str|2.1.11
code-spell-checker-swedish|str|1.0.3
svelte-vscode|sve|105.16.0
cmake|twx|0.0.17
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by ArturoDent** [comment]
I see this:

![newlineRegex](https://user-images.githubusercontent.com/31813701/166131411-17f17db5-8222-4e47-8477-a0f57c9287ce.gif)

Can you give the text you are searching and show a gif.  I am on W11, could it be linux-related?

Did you try with all extensions disabled?

**Comment by roblourens** [comment]
It will happen when the file is not open. I see it, it actually has the same cause as https://github.com/microsoft/vscode/issues/131507

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/131507 is fixed, I believe this is as well
