### ISSUE TITLE
There is a bug in file search (Ctrl + Shift + F) that matches a non-search character string.

### ISSUE THREAD

**Issue by Vendetta1209** [microsoft/vscode#148314]
ファイル検索(Ctrl+Shift+F)で検索文字じゃない文字列に一致するバグが発生しています。    

</TD>でファイル検索したところ、</span>や</asp:textbox>のextに一致したりする。
*.aspxのファイルがShiftJISであるため、検索画面では文字化けがそもそも発生している。
それが原因と関係しているかもしれません。

**Comment by Vendetta1209** [comment]
When I search for a file with the search key **< /TD>**, it matches ext of </ span> and </ asp: TextBox>. Since the * .aspx file is ShiftJIS, garbled characters occur in the search screen in the first place. It may be related to the cause.

**Comment by Vendetta1209** [comment]
Here is a screenshot of that.
![image](https://user-images.githubusercontent.com/9120115/165656793-2872abd0-21b3-4ff7-bd97-7683977026c8.png)

**Comment by roblourens** [comment]
> Since the * .aspx file is ShiftJIS, garbled characters occur in the search screen in the first place. It may be related to the cause.

Yes, you can set `files.encoding` to fix this.
