### ISSUE TITLE
in-product release notes blank after editor group changes

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#14832]
- VSCode Version: 1.6.1, 1.7.0 insiders
- OS Version: Windows 10, OS X

Steps to Reproduce:

1. Create a least two editor groups and put the in-product release notes in a right or lower editor group.
2. Close the left or top editor group.

The in-product release notes become blank. Clicking the editor or scrolling has no effect.  Double-clicking the tab heading refreshes the release notes.

It doesn't repro if the release notes are left or above the closing editor group.

**Comment by joaomoreno** [comment]
#14760
