### ISSUE TITLE
Some CSS properties do not receive syntax highlighting

### ISSUE THREAD

**Issue by Keyacom** [microsoft/vscode#148377]
Issue Type: <b>Bug</b>

1. Create a new file.
2. Copy-paste the following CSS snippet to VSCode:
```css
p {
    margin-inline: 5px;
    margin-block: 5px;
    padding-inline: 5px;
    padding-block: 5px;
    padding-inline-start: 120px;
    font-size: 5em;
}
```
3. Most likely, the code will be recognized as CSS, and VSCode will apply its syntax highlighting rules.

**Expected**: The `margin-inline`, `margin-block`, `padding-inline` and `padding-block` properties should receive syntax highlighting.
**Actual**: The `margin-inline`, `margin-block`, `padding-inline` and `padding-block` properties do not receive syntax highlighting.
Result on Monokai theme:
![Syntax highlighting bug](https://user-images.githubusercontent.com/70766223/165841447-5893760a-64e5-48ab-81f8-5c4d11858e0e.png)

Longhand properties that are part of these four, such as `padding-inline-start`, are not affected by this bug.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.75GB free)|
|Process Argv|--crash-reporter-id 57c06a69-98ac-4fc4-8225-c3db59f39ccc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pl|MS-|1.66.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
LiveServer|rit|5.7.5
wikitext|Row|3.6.4
open-in-github-desktop|wra|1.4.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by Mathias-S** [comment]
Looking at [css.tmLanguage.json](https://github.com/microsoft/vscode/blob/main/extensions/css/syntaxes/css.tmLanguage.json), it seems like the CSS definitions are pulled in from [atom/language-css](https://github.com/atom/language-css).

There is an open pull request at atom/language-css#185 which aims to fix this, but it's been open since October and that repository has had no commits in a while.

**Comment by Mathias-S** [comment]
The upstream repo has now been updated to include the missing functions and properties.

**Comment by alexr00** [comment]
Thanks for the heads up. I'll update the css grammar today.
