### ISSUE TITLE
Two "Open Repository from GitHub" options when Open Remote Repository picker on desktop

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#148310]
From https://github.com/microsoft/vscode/issues/148155#issuecomment-1111508711
One of these is contributed by the GitHub Repositories extension, and the other is contributed by the builtin GitHub extension. We should ensure that there is only one, e.g. by moving the code in the GitHub Repositories provider into the builtin GitHub extension. GitHub Repositories should still contribute the recent remote sources though.

**Comment by joyceerhl** [comment]
Pushed a workaround for this in GitHub Repositories, but we should still deduplicate the GitHub provider code.

**Comment by rzhao271** [comment]
I'm wondering what the expected output is?
Here's a screenshot I took on the latest Stable:
![A screenshot showing three open repository commands](https://user-images.githubusercontent.com/7199958/166736494-cf7a0397-0ffd-4a01-b7b6-76502d8d695e.PNG)

**Comment by joyceerhl** [comment]
Ah, so when you select 'Open Remote Repository', there should only be one 'Open Repository from GitHub' option, not two.
