### ISSUE TITLE
Auto-format has started inserting tabs instead of spaces.

### ISSUE THREAD

**Issue by Robban1980** [Microsoft/vscode#14837]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: dbaeumer.jshint-0.10.15, ms-vscode.csharp-1.4.1, ms-vscode.js-atom-grammar-0.1.10, ms-vscode.jscs-0.1.9, ms-vscode.PowerShell-0.7.2, msjsdiag.debugger-for-chrome-0.5.2

Steps to Reproduce:

1. push Alt+Shift+f for auto format, and tabs are inserted instead of spaces. 

Configuration has not change so this is all i have in form of reproduction. Pushing Tab inserts the correct number of spaces as configured.

**Comment by rebornix** [comment]
It's dup of https://github.com/Microsoft/vscode/issues/14809 and it has been fixed. Let me know if you can still run into this problem after we release 1.7 and then we can reopen it.
