### ISSUE TITLE
CSS comments don't work inside of HTML file document.

### ISSUE THREAD

**Issue by realwumbl3** [microsoft/vscode#148388]
Does this issue occur when all extensions are disabled?: Yes/No
Haven't tried, isn't commenting handled by VSCODE?

- VS Code Version: 1.6.22
- OS Version: Windows 10 Version	10.0.19044 Build 19044

Steps to Reproduce:

1.  Create the following file. 
```
<!DOCTYPE html>

<head>

</head>

<body>
    <style>
        .body {
            background-color: aqua;
        }
    </style>
</body>
```
2. Try to comment out the background color using CTRL + /

When I do this in VSCODE, I get 
`<!-- background-color: aqua; -->`
 which breaks the document.

**Comment by realwumbl3** [comment]
Side comment: Ctrl + P - New Window With Extensions Turned Off.

Would be neato.

**Comment by aeschli** [comment]
This normally works unless you have an extension installed that changes the HTML configuration. Django is one of these.

Here's what I see with just the build-in extensions.

![Peek 2022-04-29 14-49](https://user-images.githubusercontent.com/6461412/165947405-6267d777-63b2-4c53-b1a8-26a5ef8fa150.gif)

**Comment by realwumbl3** [comment]
It was Django. Thanks.

**Comment by realwumbl3** [comment]
Well, I disabled Django and today this behavior started again. I even "Reload With Extensions Disabled" and it still does it.

Please help.

**Comment by realwumbl3** [comment]
Well, I disabled Django and today this behavior started again. I even "Reload With Extensions Disabled" and it still does it.

Please help.

**Comment by realwumbl3** [comment]
Update: Now the Jinja extension does the same. Noted. WTF.
