### ISSUE TITLE
Clicking the ⚙️  icon in kernel selector doesn't do anything

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#148361]
On the prerelease Jupyter extension, open the IW and click on the kernel selector in the top right. Then, click on the ⚙️ icon for any environment. Nothing happens.

![image](https://user-images.githubusercontent.com/2230985/165801696-845f03a5-5e06-493c-92a7-c41a0c03f568.png)

**Comment by IanMatthewHuff** [comment]
Previous gear icon issue: https://github.com/microsoft/vscode/issues/146667 was duped against the bigger "handling preferred better" issue: https://github.com/microsoft/vscode/issues/146339

**Comment by rebornix** [comment]
It doesn't do anything it seems, we should now remove it.

**Comment by rebornix** [comment]
Let's merge it into https://github.com/microsoft/vscode/issues/148287
