### ISSUE TITLE
System freezes

### ISSUE THREAD

**Issue by marifcelik** [microsoft/vscode#148339]
Issue Type: <b>Bug</b>

I don't know why, but when working with code, the entire operating system freezes and does not respond to anything. I have to turn it off with the power button.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.15.30-051530-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx (8 x 2093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 1, 0|
|Memory (System)|5.77GB (1.01GB free)|
|Process Argv|--unity-launch --crash-reporter-id 23b483b8-12b1-4b40-8581-ad3d58eb82cd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.0
vscode-html-css|ecm|1.11.0
auto-rename-tag|for|0.1.10
snapcode|moy|1.1.0
vscode-docker|ms-|1.22.0
vscode-language-pack-tr|MS-|1.66.3
csharp|ms-|1.24.4
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.8
js-debug-nightly|ms-|2022.4.2217
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
material-icon-theme|PKi|4.16.0
java|red|1.5.0
LiveServer|rit|5.7.5
pdf|tom|1.2.0
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
material-theme|zhu|3.13.24
php-intellisense|zob|1.0.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether the issue is being caused by one of your extensions.

**Comment by marifcelik** [comment]
When I open the extensions one after the other, it happens because the ram is not enough, I solved the problem by adding swap. Thanks
