### ISSUE TITLE
Search: Use Ignore Files exclude source files not in .gitignore or .ignore

### ISSUE THREAD

**Issue by Asgaroth** [microsoft/vscode#148357]
Issue Type: <b>Bug</b>

Enabling `Search: Use Ignore Files` causes some source files to not show up in the results unless explicitly added to "files to include"

Does this issue occur when all extensions are disabled?: Yes

`.gitignore` file is empty and I don't have a `.ignore` file

`search.useGlobalIgnoreFiles = false`
`search.useParentIgnoreFiles = false`

## With setting disabled

<img width="1344" alt="Screen Shot 2022-04-28 at 9 29 15 AM" src="https://user-images.githubusercontent.com/755568/165776245-cc6b46b8-e478-4ee6-8d28-39f868214798.png">

```[2022-04-28 09:30:45.222] [renderer1] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Users/alex/src/panamaRN","external":"file:///Users/alex/src/panamaRN","path":"/Users/alex/src/panamaRN","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/Thumbs.db":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.expo":true},"fileEncoding":"utf8","disregardIgnoreFiles":true,"disregardGlobalIgnoreFiles":true,"disregardParentIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"onlyOpenEditors":false,"maxResults":20000,"type":2,"contentPattern":{"pattern":"shopReducer","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}```

## With setting enabled

<img width="1340" alt="Screen Shot 2022-04-28 at 9 29 24 AM" src="https://user-images.githubusercontent.com/755568/165776264-7458cdd8-f1b4-48c8-9f7e-682a450cdf12.png">

```[2022-04-28 09:34:17.094] [renderer1] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Users/alex/src/panamaRN","external":"file:///Users/alex/src/panamaRN","path":"/Users/alex/src/panamaRN","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/Thumbs.db":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.expo":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"disregardParentIgnoreFiles":true,"ignoreSymlinks":false}],"usingSearchPaths":false,"onlyOpenEditors":false,"maxResults":20000,"type":2,"contentPattern":{"pattern":"shopReducer","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}```

## With setting enabled + files to include

<img width="1329" alt="Screen Shot 2022-04-28 at 9 29 35 AM" src="https://user-images.githubusercontent.com/755568/165776273-9f4eae9c-260b-476e-80f8-49d972df4be7.png">

```[2022-04-28 09:34:45.219] [renderer1] [trace] SearchService#search {"_reason":"searchView","folderQueries":[{"folder":{"$mid":1,"fsPath":"/Users/alex/src/panamaRN","external":"file:///Users/alex/src/panamaRN","path":"/Users/alex/src/panamaRN","scheme":"file"},"excludePattern":{"**/.git":true,"**/.svn":true,"**/.hg":true,"**/CVS":true,"**/.DS_Store":true,"**/Thumbs.db":true,"**/node_modules":true,"**/bower_components":true,"**/*.code-search":true,"**/.expo":true},"fileEncoding":"utf8","disregardIgnoreFiles":false,"disregardGlobalIgnoreFiles":true,"disregardParentIgnoreFiles":true,"ignoreSymlinks":false,"includePattern":{"src":true,"src/**":true}}],"usingSearchPaths":true,"onlyOpenEditors":false,"maxResults":20000,"type":2,"contentPattern":{"pattern":"shopReducer","isRegExp":false,"isCaseSensitive":false,"isWordMatch":false,"wordSeparators":"`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?"},"previewOptions":{"matchLines":1,"charsPerLine":1000},"usePCRE2":false}```

VS Code version: Code - Insiders 1.67.0-insider (Universal) (7fc8af4e2d8f50a3950b809b9beab86fa5135f29, 2022-04-28T05:19:19.018Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (18.02GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebugcf:30475217
vsclangdc:30480125

```

</details>

**Comment by roblourens** [comment]
Any difference if .gitignore is deleted, vs present (and empty)?

Thanks for including logs, can you grab the search logs from `Log (Extension Host)` which will show us the actual ripgrep command that was run?

If you want you can try to run this command manually, and include `--trace` which might help

**Comment by Asgaroth** [comment]
So I was writing a lot of debug info when I got to the last step and manually ran the command with `--trace`

`Ignore(IgnoreMatch(Gitignore(Glob { from: Some("./.git/info/exclude"), original: "index.js", actual: "**/index.js"`

It turns out, someday, for whatever reason, I added `index.js` to `.git/info/exclude` when it should have been `./index.js`

Thank you for the help!
