### ISSUE TITLE
[c#] syntax highlighting is broken when function has Unicode characters

### ISSUE THREAD

**Issue by ktos** [Microsoft/vscode#1483]
When function name has Unicode characters in it, syntax highlighting for strings is broken.

There is a constructor named "Jednorożec" which triggers the error:
![code0](https://cloud.githubusercontent.com/assets/1633261/11914178/e7d96b04-a678-11e5-94a4-4dfdd9cc8f14.PNG)

If it was called without "ż", everything is OK:
![code1](https://cloud.githubusercontent.com/assets/1633261/11914179/e9994c5c-a678-11e5-9834-be6e61bc817e.PNG)

Introduced in 0.10.5.

**Comment by egamma** [comment]
CCing martin @aeschli

**Comment by aeschli** [comment]
This was a issue with a Text mate infrastructure and has been fixed in the meantime.
