### ISSUE TITLE
Debug actions for notebook cell aren't initially visible

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#148370]
On the latest Insiders and so on:

1. Reload the window
2. "Create a New Jupyter Notebook"
3. Enter a few lines into a cell
4. Note there's no visible UI to debug the cell 🤔  so execute "Jupyter: Run by Line" from the command palette
5. You will now be in debug mode but not have any UI to step or continue execution in the cell toolbar

![image](https://user-images.githubusercontent.com/2230985/165822626-f15de284-31d1-4647-b106-bc807e81f1a2.png)

6. Switch back to a different tab and back again, the buttons appear

![image](https://user-images.githubusercontent.com/2230985/165822850-994cfaf5-92ca-4412-a1c7-8ac5b12ee370.png)

7. After you stop debugging, you now get the split "play" button that allows debugging

**Comment by roblourens** [comment]
I have seen this too, but it will probably be fixed with a more proper way to control custom context keys for individual cells from extensions. The current hack is prone to messing up the keys with races
