### ISSUE TITLE
git not working in dev container

### ISSUE THREAD

**Issue by DanTaranis** [microsoft/vscode#148360]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: ubuntu 20.04

Steps to Reproduce:

1. clone a repo from github
2. create a container with Dockerfile and devcontainer.json
3. build container and open 
git no longer works :/

**Comment by rkeulemans** [comment]
You should probably use the microsoft base image, so instead of:

```
{
    "image": "ubuntu:latest"
}
```

You want:
```
{
    "image": "mcr.microsoft.com/vscode/devcontainers/base:ubuntu-20.04"
}
```

The ubuntu image does not contain `git`, so this is expected behaviour.

**Comment by lszomoru** [comment]
@DanTaranis, when opening a container using VS Code, you need to have git installed in the container in order to use the git functionality available in VS Code. As @rkeulemans, mentioned above, please make sure that you are using a base image that has git installed.

**Comment by danFromTelAviv** [comment]
@lszomoru (this is my other git account)
do i need to install it in my dockerfile, or can i do it somehow through .devcontainer?

**Comment by lszomoru** [comment]
You can either start from a base image that has git installed, or you can do something along the lines of:
```
FROM ubuntu:latest
RUN apt-get -y update
RUN apt-get -y install git
```
