### ISSUE TITLE
My C and CPP File are not run this Platform Pleased Help!!!

### ISSUE THREAD

**Issue by Pranil9699** [microsoft/vscode#148395]
my c and c++ file are not run this paltform there is one error show i t tell " C:\MinGW\bin\g++.exe -fdiagnostics-color=always -g C:\Users\prani\OneDrive\Documents\html_all\Sample1.cpp -o C:\Users\prani\OneDrive\Documents\html_all\Sample1.exe c:/mingw/bin/../lib/gcc/mingw32/6.3.0/../../../libmingw32.a: file not recognized: File format not recognized collect2.exe: error: ld returned 1 exit status " this is error show for me

**Comment by roblourens** [comment]
This sounds like an issue with your project. Please give more details why it's a vscode issue, if you think it's a vscode issue.
