### ISSUE TITLE
Performance memory profiler for java/c# on Vscode

### ISSUE THREAD

**Issue by devmet34** [microsoft/vscode#148382]
Hello, 

Please consider providing performance/memory profiler to Vscode for Java and C#, others would be welcome too :)
It doesnt have to be an advanced one, but a basic one like memory dumping and a simple cpu profiler would be great feature for Vscode. Besides, this would increase the popularity quite a lot.

**Comment by roblourens** [comment]
This is a feature request for those language extensions
