### ISSUE TITLE
Spacebar stops working

### ISSUE THREAD

**Issue by yaa110** [microsoft/vscode#148336]
Issue Type: <b>Bug</b>

Sometimes spacebar stops working and no space character is added by pressing spacebar, after one or two seconds all those spaces are added simultaneously.

Gnome: 42.1 (X11)

uname -a
Arch Linux username 5.17.4-arch1-1 #1 SMP PREEMPT Wed, 20 Apr 2022 18:29:28 +0000 x86_64 GNU/Linux

version: 1.66.2
The bug occurs even after a downgrade to 1.65.2.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.17.4-arch1-1
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2657)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.43GB (8.91GB free)|
|Process Argv|--unity-launch --crash-reporter-id 40f5e5a0-9ae2-405d-ae69-170a877d3f69|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.14.0
ocaml-formatter|bad|1.14.0
toml|be5|0.6.0
vscode-zonefile|Com|0.0.4
vscode-markdownlint|Dav|0.47.0
vscode-wasm|dts|1.3.1
vscode-go-syntax|dun|0.0.18
rust-syntax|dus|0.6.0
vscode-html-css|ecm|1.11.0
shell-format|fox|7.2.2
delugelang|gdp|0.0.4
go|gol|0.32.0
todo-tree|Gru|0.0.215
unicode-math-vscode|Gui|0.3.4
terraform|has|2.22.0
vscode-wasm-essentials|jcm|0.1.0
vscode-wasm-syntax-lite|jcm|0.3.0
better-cpp-syntax|jef|1.15.13
autoconf|mae|0.1.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
material-icon-theme|PKi|4.16.0
fabric8-analytics|red|0.3.5
java|red|1.5.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.7.0
rust|rus|0.7.8
jinjahtml|sam|0.17.0
crates|ser|0.5.10
lua|sum|3.2.2
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by gjsjohnmurray** [comment]
Does this also happen with all of your extensions disabled? The `Start Extension Bisect` command can help you investigate this.

**Comment by yaa110** [comment]
No it does not happen when all extensions are disabled

**Comment by gjsjohnmurray** [comment]
> No it does not happen when all extensions are disabled

So please use `Start Extension Bisect` to identify which extension is causing the issue. Then report the problem to the extension author. The `Report Issue` option from the `Help` menu offers a convenient way of doing this if the extension author provided a link to their repository.

/causedByExtension

**Comment by yaa110** [comment]
It has been fixed by disabling https://github.com/gatapia/unicode-math-vscode
