### ISSUE TITLE
JavaScript Intellisense doesn't autocomplete Element.value property

### ISSUE THREAD

**Issue by Immortalin** [Microsoft/vscode#14833]
- VSCode Version: 1.6.1
- OS Version: Ubuntu 16.04.1 LTS
 
Steps to Reproduce:

1. Open a JavaScript file
2. Attempt to autocomplete an element e.g. through 
```JavaScript
let el =  document.getElementbyId("id")
el.value  // <-- This doesn't autocomplete, however the following does:
el.nodeValue // autocompletes

**Comment by waderyan** [comment]
@Immortalin thank you for opening this issue. I'm not seeing auto complete for either of these. Can you share more from your workspace? Do you have a jsconfig.json? 

Here is what I see. 

![image](https://cloud.githubusercontent.com/assets/2449568/19941658/3bdb563e-a0ee-11e6-8bba-244b084a92fb.png)

**Comment by waderyan** [comment]
Closing until more info is obtained.
