### ISSUE TITLE
Native sparql notebook language server error

### ISSUE THREAD

**Issue by BenjaminHofstetter** [microsoft/vscode#148384]
Does this issue occur when all extensions are disabled?:  No

- VS Code Version: 1.66.2 (Universal)
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Install https://marketplace.visualstudio.com/items?itemName=stardog-union.vscode-stardog-languages
2. Install https://marketplace.visualstudio.com/items?itemName=Zazuko.sparql-notebook
3. Create a file test.sparqlbook
4. Create a Code cell and enter somme sparql code e.g. 

```sparql
# [endpoint=https://lindas.admin.ch/query]
PREFIX canton: <http://classifications.data.admin.ch/canton/>
PREFIX gont: <https://gont.ch/>
PREFIX purl: <http://purl.org/dc/terms/> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

DESCRIBE canton:BL
```

5. hover over the code and the stardog language server start to throw errors in the output console.

```
[Error - 10:25:03 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read properties of undefined (reading 'getText')
  Code: -32603 
```

I crated an issue in stardogs lsp GitHub repo https://github.com/stardog-union/stardog-language-servers/issues/47 for this.
That error was not raised in older versions of vscode. 

This error is not present outside of vscode notebooks.

**Comment by rebornix** [comment]
This looks like an extension/language server to me but let's see what's the response we get from https://github.com/zazuko/vscode-sparql-notebook/issues/16

**Comment by BenjaminHofstetter** [comment]
Sorry for the confusion. I am the author of  https://github.com/zazuko/vscode-sparql-notebook/ and I don't have an answer. This is why I created this issue here because I don't see a solution or I cannot find the cause of this problem.

**Comment by rebornix** [comment]
@BenjaminHofstetter sorry I totally missed that. Looping in our LSP folks.

**Comment by dbaeumer** [comment]
Commented in https://github.com/zazuko/vscode-sparql-notebook/issues/16

**Comment by dbaeumer** [comment]
I will close the issue based on comments I put into https://github.com/zazuko/vscode-sparql-notebook/issues/16
