### ISSUE TITLE
Syncing UI State with multiple moved view containers will break

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#148363]
Issue Type: <b>Bug</b>

Repro using Profiles Feature
1. Create a new user data dir and launch VS Code.
2. Move timeline to its own container in the activity bar
3. Move search container to secondary side bar
4. Export the profile

5. Create a new user data dir and launch VS Code.
6. Import the profile

:bug: => the timeline container will not be created and timeline will remain in the explorer view

cc @sandy081 

VS Code version: Code - Insiders 1.67.0-insider (410fe0fc7890ef563830bb86cbcd763995bfc65f, 2022-04-27T05:15:39.871Z)
OS version: Windows_NT x64 10.0.22593
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Is this #148320?

**Comment by sbatten** [comment]
unfortunately no, this another case where we break with similar symptoms :(
