### ISSUE TITLE
Enabling shell integration in remote with zshell fails with ENOENT

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#148366]
1. Use the tool Tanha and I have been working on to connect to a remote machine with zshell
2. Turn on shell integration
3. See this error in the server's console, and notice creating a shell fails

```
[Error: ENOENT: no such file or directory, copyfile '/Users/connor/.vscode-server/server-insiders/bin/7fc8af4e2d8f50a3950b809b9beab86fa5135f29/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-profile.zsh' -> '/var/folders/q1/7d0txh0j6gg7gj9_wf70qcgm0000gn/T/vscode-zsh/.zprofile']
```

That folder contains only the following files, no `shellIntegration-profile.zsh`:

```
> ls -a  /Users/connor/.vscode-server/server-insiders/bin/7fc8af4e2d8f50a3950b809b9beab86fa5135f29/out/vs/workbench/contrib/terminal/browser/media/
.                        ..                       shellIntegration-bash.sh shellIntegration.ps1     shellIntegration.zsh
```

This results in the same state I saw in https://github.com/microsoft/vscode/issues/148312, might be the root cause?

**Comment by meganrogge** [comment]
I believe this is happening because in a remote context, there probably isn't permission to be accessing `.zprofile` - thus the ENOENT

**Comment by connor4312** [comment]
From the command it looked like it was trying to copy a file called `shellIntegration-profile.zsh`, but that file didn't exist.

**Comment by meganrogge** [comment]
that file should definitely exist because we make it 
https://github.com/microsoft/vscode/blob/43464213a6989181e9dfe49d0fe9189b1c67f7c7/src/vs/platform/terminal/node/terminalProcess.ts#L213

**Comment by connor4312** [comment]
Hm. I may be misunderstanding the code or error, but it seems like we want to copy it from the `out` folder of the app

https://github.com/microsoft/vscode/blob/35c2141bf1babe9b8d18a86f80abcb6e6555b546/src/vs/platform/terminal/node/terminalEnvironment.ts#L200

However, it's not included there, at least in the latest Insiders server build that I was using

```
➜  vscode git:(main) ✗ unzip -l vscode-server-darwin-arm64.zip | grep shellIntegration-profile.zsh
➜  vscode git:(main) ✗
```

**Comment by meganrogge** [comment]
Oh yes you're correct, will fix
