### ISSUE TITLE
"console": "integratedTerminal" not working

### ISSUE THREAD

**Issue by ZiqiFrancisFan** [microsoft/vscode#148351]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: local win10, remote Linux

Steps to Reproduce:
1. Set the launch.json as follows. Note that  "console": "integratedTerminal" is specified, so the debug launch should start from the integrated terminal, rather than the debug console.
{
            "name": "(cuda-gdb) Launch Leaf Algo",
            "type": "cuda-gdb",
            "request": "launch",
            "program": "${workspaceFolder}/regera/Blazer/MercuryImageComputer/KT/leaf/M31/BrightField/bin/LeafStandalone/Debug/12/LeafStandAlone.x86-64",
            "args": "-noForcedPatches ${workspaceFolder}/virgo_dependency/imc_integration/jobdumps_for_ziqi/R0C0S_master_0_cpu0_JobInfoRL_14205_s4_j13_ID_0 ${workspaceFolder}/virgo_dependency/imc_integration/jobdumps_for_ziqi/AlgoParams.xml",
            "stopAtEntry": true,
            "environment": [],
            "console": "integratedTerminal",
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description":  "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
2. You may observe that debug starts from the debug console.

**Comment by roblourens** [comment]
This is an issue for the debug extension
