### ISSUE TITLE
Screen Flickering

### ISSUE THREAD

**Issue by dhirajgite** [microsoft/vscode#148332]
Issue Type: <b>Bug</b>

In ubuntu 22.04 When using vs code in full window model screen is flickering

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.15.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 905)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|11.58GB (0.15GB free)|
|Process Argv|. --crash-reporter-id c41bfa3f-0a03-427e-9bdd-8886ed55586c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by deepak1556** [comment]
Is this in a VM ? Also is this with wayland or X11 session ?

**Comment by dhirajgite** [comment]
No. I am using VS-code on my laptop.

**Comment by BuLLHACK** [comment]
I think this bug is related with Ubuntu 22.04 and has nothing to do with VS Code. I have experienced the same flickering on other apps.

**Comment by deepak1556** [comment]
Does the issue happen with chromium browser on your device ?

/gifPlease

**Comment by dhirajgite** [comment]
@BuLLHACK I only experienced this issue with vs code. When the screen is flickering on vs-code if the change application flickering stops and then go to vs-code it's start flickering again.

**Comment by dhirajgite** [comment]
@deepak1556 no it's only happening with vs-code.

**Comment by dhirajgite** [comment]
Will try to update gif or screenshot when next time if happens.

**Comment by dhirajgite** [comment]
@wmcmurray I don't use many other applications only firefox and vs code. maybe due to this, I have not noticed it with other applications.

**Comment by BuLLHACK** [comment]
This is a known bug in 22.04, the following steps may help you get rid of the flickering:
Open /etc/default/grub
Add these parameters to GRUB_CMDLINE_LINUX_DEFAULT:
`GRUB_CMDLINE_LINUX_DEFAULT="quiet splash" i915.enable_dc=0 intel_idle.max_cstate=2`
Save the file and update grub
`sudo update-grub`
Then restart you computer

Source: [https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1970426/comments/24](url)
