### ISSUE TITLE
detected language is JSON in python notebook cells

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#148374]
while testing https://github.com/microsoft/vscode-jupyter/issues/9767

Open a notebook
create a python cell or edit one

A quick action lightbulb shows up to accept the detected language (JSON)

![image](https://user-images.githubusercontent.com/2019016/165353414-cb97885d-fd03-4a3d-a093-71ec763d1513.png)

**Comment by greazer** [comment]
Jupyter doesn't handle the detected language feature for cells.

**Comment by amunger** [comment]
I'm not seeing this anymore
