### ISSUE TITLE
"Cannot reconnect. Please reload the window."

### ISSUE THREAD

**Issue by calston16** [microsoft/vscode#148350]
Keep getting the following error message following recent update: Cannot reconnect. Please reload the window. It happens shortly after logging me in, and keeps happening despite attempts to refresh/open again. 

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36
Embedder: codespaces

**Comment by alexdima** [comment]
@calston16 Are there any errors in the console? 

cc @jkeech
