### ISSUE TITLE
Github: PR template picker needs polish

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148323]
From @joyceerhl in https://github.com/microsoft/vscode/issues/143083#issuecomment-1111314703

> I did get the list of PR templates:
> ![image](https://user-images.githubusercontent.com/30305945/165588454-628d1096-c9b0-4bef-9dc8-cacc352b3570.png)
> 
> However, I had no way to get back to the picker after taking that screenshot (which dismissed the picker). At minimum I feel we should use `ignoreFocusOut: true`, since the Create PR functionality is not exposed as a command palette command, I am stuck.
> 
> Additionally, after I selected a template to create the PR, nothing happened.
> 
> Finally, it was unexpected that I get two popups to create a PR when the GitHub Pull Requests and Issues extension is installed: 
> ![image](https://user-images.githubusercontent.com/30305945/165589263-a942ee6d-33f7-44be-89a6-20eeae520b7a.png)

**Comment by joaomoreno** [comment]
From what I can tell:

- The PR list appears with full paths, each row should appear as a relative path from the repo root
- @joyceerhl could only run the command once successfully
- We should use `ignoreFocusOut: true`

Unsure of what to do about the simultaneous GHPR.

---

@babakks Would you like to tackle this in another PR?

**Comment by babakks** [comment]
@joaomoreno Yes, I'll submit a PR.

**Comment by babakks** [comment]
@joaomoreno I've just submitted the PR. I forgot to create the PR at that time.

**Comment by connor4312** [comment]
Could not verify due to https://github.com/microsoft/vscode/issues/143083#issuecomment-1172726534. Maybe someone else will have better luck

**Comment by joaomoreno** [comment]
Moving verification to July to account for https://github.com/microsoft/vscode/issues/148568#issuecomment-1173021392

**Comment by joaomoreno** [comment]
**Verification:**

1. Run `Git: Clone` and clone https://github.com/joaomoreno/test-pr-templates/
2. Create a branch
3. Make a change to `README.md` and commit
4. Attempt to push/publish that branch. Code should tell you you can't push to that repo and will offer to fork the repository, accept.
5. Code should then ask you whether you'd like to create a PR, accept.

The PR list should be polished.
