### ISSUE TITLE
Switch to Terminal when running script

### ISSUE THREAD

**Issue by BogdanChipara** [microsoft/vscode#148315]
Issue Type: <b>Feature Request</b>

Hi,

When running a script it would be very useful to swith to the terminal window, especially when the script requires user input.

Otherwise many times I input over the code what I actually need to input in the Terminal.

Thank you!
Bogdan
www.everymindisdifferent.com

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by meganrogge** [comment]
Hi can you pls elaborate on what you mean?

**Comment by BogdanChipara** [comment]
Good morning Megan,

As you can see in the screenshot attached. The prompter is in the *Editing
Window*, while the script is running and waiting for my *input* in the

*Terminal Window.*
So what I was suggesting is to change the active windows to Terminal once a
script is running.

[image: image.png]

Thank you!

*Have a good day,*

*Bogdan Chipara*

*Architectwww.floatingvolume.com <http://www.floatingvolume.com>*
*d3v310pm3nT                          *
*www.everymindisdifferent.com* <https://bit.ly/3EpqzYo>
*NL +31 648447980*

**Comment by meganrogge** [comment]
Thanks for the issue, but we won't do this because don't want to change focus for the user as that would be unexpected.

**Comment by BogdanChipara** [comment]
Than place it as an option. Some ppl need to be distracted.
