### ISSUE TITLE
Feature request: Add a way to disable default formatter for a block of code

### ISSUE THREAD

**Issue by ararunaufc** [microsoft/vscode#148379]
I've searched **a lot** over the internet for a way to prevent the (default) formatter from running on a section of my document and I have found nothing yet... I only found #36797, which asks for the same feature, but was closed and referred to a TypeScript-specific implementation, which does not cover my case.

I'm editing a `.html` document that mixes CSS, JS, HTML, and a custom template syntax. I need a way to disable the CSS formatter temporarily, and maybe the best option is by using a "comment code" like prettier has (`prettier-ignore-begin`/`end`).

Currently, I'm unable to do what I'm trying to do because the formatter messes up my template code.

I'm not using any custom extension that manages CSS, so the problem really lies with the default one. Also, disabling auto-formatting (I'm using formatOnSave) is not an option for me.

**Comment by aeschli** [comment]
For the HTML formatter there's a setting `html.format.unformattedContentDelimiter`. See here: https://code.visualstudio.com/updates/v1_52#_html

Can you give it a try?

**Comment by ararunaufc** [comment]
> For the HTML formatter there's a setting `html.format.unformattedContentDelimiter`. See here: https://code.visualstudio.com/updates/v1_52#_html
> 
> Can you give it a try?

Thank you. It kinda works as a workaround, but now I have a very large `<script>` that I'll need to format manually...

For the time being it is acceptable, but I don't think it is enough to close this issue since the feature request still stands.
