### ISSUE TITLE
save as... has no option for saving as notebook ipynb

### ISSUE THREAD

**Issue by perdigao1** [microsoft/vscode#148342]
Issue Type: <b>Feature Request</b>

When crating a new notebook and trying to save it, user has to explicitly type the extension *.ipynb in order to successfully save the notebook. The extension that it proposes is a JSON format, which is kind of correct but no ipynb extension is within the format presented.

Request a new 'extension' in the drop-down list, *.ipynb would be useful.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by roblourens** [comment]
This flow should work- can you explain a little more, maybe with screenshots? How did you create the notebook and what do you see in the save dialog?

**Comment by perdigao1** [comment]
In the last version it is working correctly. It appears to have been fixed in some past update.
