### ISSUE TITLE
When folding code, garbled characters appear

### ISSUE THREAD

**Issue by dacapoday** [microsoft/vscode#148396]
Issue Type: <b>Bug</b>

When folding code, garbled characters appear
![Snipaste_2022-04-29_11-05-31](https://user-images.githubusercontent.com/9378047/165880069-9cc10dfd-91ec-4c81-a5e5-f19c8ea228ab.png)
![Snipaste_2022-04-29_11-05-06](https://user-images.githubusercontent.com/9378047/165880072-d3e0f076-656b-4c31-a6df-10dc9a1a9775.png)
![Snipaste_2022-04-29_11-06-57](https://user-images.githubusercontent.com/9378047/165880074-9e8637d2-151b-4eb0-b8d2-5f9cb13057ff.png)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.11.0-44-generic

<details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|13.2.4
vscode-drawio|hed|1.6.4
eml|lei|0.4.0
vscode-language-pack-zh-hans|MS-|1.66.3
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
vscode-remote-extensionpack|ms-|0.21.0
vsonline|ms-|1.0.3076
material-icon-theme|PKi|4.16.0
vscode-openapi|42C|4.9.5
markdown-mermaid|bie|1.13.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
shell-format|fox|7.2.2
go|gol|0.32.0
todo-tree|Gru|0.0.215
rest-client|hum|0.24.6
git-graph|mhu|1.30.0
vscode-antlr4|mik|2.2.4
vscode-docker|ms-|1.22.0
vscode-language-pack-zh-hans|MS-|1.66.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
hexeditor|ms-|1.9.6
vscode-yaml|red|1.7.0
partial-diff|ryu|1.4.3
code-navigation|vik|0.2.0
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.20
file-size|zh9|1.0.0

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by IllusionMH** [comment]
Do you have DevTools opened for this VS Code window when these characters appear?
