### ISSUE TITLE
"revealProblems" closes Terminal

### ISSUE THREAD

**Issue by Srekel** [microsoft/vscode#148318]
Issue Type: <b>Bug</b>

I'm using a build task to compile, and want it to switch to the problem tab when it finds an error so I use revealProblems: onProblem.

However, when I do that, and there's an error, the terminal disappears. And the terminal often contain more detail on the build error that occured. I haven't seen a setting that disables the automatic closing of the terminal.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.35GB free)|
|Process Argv|--crash-reporter-id 2e997ea4-1d71-4990-99fa-ecc34be7ca37|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
overtype|ada|0.2.0
increment-selection|alb|0.2.0
zls-vscode|Aug|1.0.4
toml|be5|0.6.0
markdown-emoji|bie|0.2.1
markdown-preview-github-styles|bie|1.0.1
gltf-vscode|ces|2.3.14
smoothscroll|cya|1.0.4
vscode-markdownlint|Dav|0.47.0
sort-lines-by-selection|ear|1.0.0
EditorConfig|Edi|0.16.4
graphviz-preview|EFa|1.5.0
vscode-diff|fab|1.4.2
godot-tools|gee|1.2.0
asciidecorator|hel|0.2.0
vscode-graphviz|joa|0.0.6
contextualduplicate|laf|0.2.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.1
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
vshaxe|nad|2.23.3
indent-rainbow|ode|8.3.1
git-file-history|pom|1.0.1
text-power-tools|qcz|1.32.0
webgl-glsl-editor|rac|1.3.0
indenticator|Sir|0.7.0
vscode-fileutils|sle|3.5.0
shader|sle|1.1.5
vscode-3dviewer|sle|0.2.2
vscode-hexdump|sle|1.8.1
code-spell-checker|str|2.1.11
ninja|sur|0.0.1
zig|tie|0.2.5
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
gitblame|wad|8.1.0
markdown-all-in-one|yzh|3.4.3
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaat:30438848

```

</details>

**Comment by Tyriar** [comment]
Do you have both problems and terminal visible at the same time by tweaking your views? Can you show a screenshot if so?
