### ISSUE TITLE
Error when connecting to a Codespace

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148414]
![image](https://user-images.githubusercontent.com/22350/165906433-52b253e4-47d8-453d-b180-26f79c590af2.png)

cc @alexr00 @TylerLeonhardt

**Comment by joaomoreno** [comment]
Summary:

- This now happens because GHPR now depends on GitHub Authentication
- Each extension runs on different locations (one UI, one workspace)
- @alexdima suggests to use `api: 'none'` in github-authentication to make the dependency an activation dependency only

**Comment by joaomoreno** [comment]
In order not to push a new change at the last day of endgame, @alexr00 will simply revert the dependency and we'll push a proper fix next week.

**Comment by alexr00** [comment]
Dependency removed and a new GHPRI pre-release is in the works.

**Comment by TylerLeonhardt** [comment]
Sorry, what is `api: none`?

**Comment by TylerLeonhardt** [comment]
Very cool. Thanks for the context!

**Comment by alexdima** [comment]
(you can read more about `api:none` [here](https://code.visualstudio.com/api/advanced-topics/remote-extensions#:~:text=APIs%20by%20using-,%22api%22%3A%20%22none%22,-in%20their%20extension%27s))
