### ISSUE TITLE
Windows: Prevent update service from activating if running as Admin in User install

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148428]
From https://github.com/microsoft/vscode/issues/147763#issuecomment-1113107610

**Comment by RussKie** [comment]
Perhaps the update should not be run if there are any other Code instances are open.

**Comment by joaomoreno** [comment]
That won't happen anyway unless they aren't sharing the same user data dir. Have you observed otherwise?

**Comment by benallred** [comment]
Added this on 147763, but probably should have put it here.

> We might want to disable update in sessions started as Admin, when in the user setup. What do you think?

@joaomoreno: Just thought I should mention that running VS Code as admin is what enabled my VS Code to actually update in a user setup. https://github.com/microsoft/vscode/issues/147408#issuecomment-1155987859

**Comment by joaomoreno** [comment]
> @joaomoreno: Just thought I should mention that running VS Code as admin is what enabled my VS Code to actually update in a user setup. [#147408 (comment)](https://github.com/microsoft/vscode/issues/147408#issuecomment-1155987859)

Yeah I'm aware of that. Is also theoretically what put you in that situation. Is it possible you ran Code like that prior to the bug happening? I'm currently investigating.

**Comment by benallred** [comment]
> Is it possible you ran Code like that prior to the bug happening?

If you mean, ran as admin once and it updated while that instance was running, then, yes, that's possible. I never had the error on the linked issue happen before my winget switch, though, thus my suspicion there. On the other hand, where VS Code updates only happen once a month, it could just be that one-off runs as admin never coincided with an update. On the first hand, though, I have this problem on two machines now, since that switch, and it seems unlikely that I would have run as admin at the same time as the monthly update on two machines where I never had before. 🤷

**Comment by benallred** [comment]
> > Is it possible you ran Code like that prior to the bug happening?
> 
> I have this problem on two machines now, since that switch, and it seems unlikely that I would have run as admin at the same time as the monthly update on two machines where I never had before. 🤷

I'm running into this on a third machine that I know absolutely never runs Code as admin. (It is still installed as admin, but never run as admin.)

**Comment by joaomoreno** [comment]
**Verification:**

1. Install the user setup on Windows
2. Launch Code as Admin
3. Open the Main log and confirm updates are disabled

**Comment by gjsjohnmurray** [comment]
@joaomoreno this verifies on today's Insiders if no other instances of Code are running when I run as admin. But if I already have a normally-launched instance, the main log of a subsequent admin-launched instance doesn't report that message. Is this correct?

**Comment by depascalis** [comment]
This solution doesn't work for me, I need to be running vscode elevated and always have been, same for my team members. I don't remember why, but after some days/weeks running vscode normally I always get reminded of why it was needed.

Could a solution be to prevent the update service **only** when vscode has a normal instance AND an elevated instance running at the same time? I believe this would make everyone happy. 🥳
