### ISSUE TITLE
User code cannot wake up

### ISSUE THREAD

**Issue by wdy2580** [microsoft/vscode#148481]
Issue Type: <b>Bug</b>

Code snippets cannot be used in C language and C++ language. If the wake-up character is #1, it cannot be used, and if it is #c, it can be used. The wake-up symbol can be used in java.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (8.37GB free)|
|Process Argv|--crash-reporter-id 48393912-2052-4f44-a5c1-19d339f3edf1|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
Bookmarks|ale|13.2.4
project-manager|ale|12.5.0
code-gnu-global|aus|0.2.2
bracket-pair-colorizer|Coe|1.0.62
code-runner|for|0.11.7
copilot|Git|1.14.5744
vscode-power-mode|hoo|2.2.0
intellij-idea-keybindings|k--|1.5.1
vscode-language-pack-zh-hans|MS-|1.66.3
python|ms-|2022.5.11191822
vscode-pylance|ms-|2022.4.3
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
cmake-tools|ms-|1.11.14
cpptools-extension-pack|ms-|1.1.0
one-dark-theme|msk|1.14.2
java|red|1.5.0
tabnine-vscode|Tab|3.5.42
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.2022041411
vscode-java-dependency|vsc|0.19.2022042300
vscode-java-pack|vsc|0.22.2022042300
vscode-java-test|vsc|0.35.2022042302
vscode-maven|vsc|0.35.2022042603
yao-translate|Yao|1.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by wdy2580** [comment]
This is what happened after I reset the system.

**Comment by jrieken** [comment]
The share the snippet and precise steps that describe what you are doing
