### ISSUE TITLE
Customize header actions

### ISSUE THREAD

**Issue by ahmafi** [microsoft/vscode#148475]
Adding or removing actions from these headers would be nice. For example, I want to add `Close saved editors` in this header, next to `Close All Editors`:

![image](https://user-images.githubusercontent.com/12560109/166103043-525688e1-3968-4fec-a81e-5478af9c0991.png)

Or I would like to add `Stage Selected Range` in the source control view:

![image](https://user-images.githubusercontent.com/12560109/166103149-04cf73dd-1e7e-465e-9aa5-dbb2854b10c2.png)

**Comment by joyceerhl** [comment]
Likely duplicate of https://github.com/microsoft/vscode/issues/9285.

Alternatively you could write an extension which contributes these commands to the relevant menus: https://code.visualstudio.com/api/references/contribution-points#contributes.menus

**Comment by ahmafi** [comment]
I found this extension after searching for a bit. [Shortcut Menu Bar](https://marketplace.visualstudio.com/items?itemName=jerrygoyal.shortcut-menu-bar)
