### ISSUE TITLE
Snippet choice shows "no suggestions"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148406]
That setting is true for me. I tested this further, and it looks like it only repros for me when the file is saved (looks like that's not the case for you since you're working with a saved file). I can select any language for an unsaved file and the choices come up, but as soon as I save the file, suggestions no longer populate. Same case with python, typescript, C#, markdown

![snippetChoices](https://user-images.githubusercontent.com/2019016/165816697-ba64e8da-f572-4636-8230-3fbba1997e31.gif)

_Originally posted by @amunger in https://github.com/microsoft/vscode/issues/75594#issuecomment-1112501469_

**Comment by jrieken** [comment]
@amunger Can you please share you settings here

**Comment by amunger** [comment]
{
  "jupyter.askForKernelRestart": false,
  "remote.SSH.remotePlatform": {
    "20.69.93.0": "linux",
    "20.69.111.33": "linux",
    "52.247.214.84": "linux"
  },
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "jupyter.widgetScriptSources": [
    "jsdelivr.com",
    "unpkg.com"
  ],
  "window.newWindowDimensions": "offset",
  "jupyter.interactiveWindowMode": "perFile",
  "experiments.override.gettingStarted.overrideCategory.ms-python.python.pythonWelcome.when":"false",
  "experiments.override.gettingStarted.overrideCategory.ms-python.python.pythonWelcomeWithDS.when": "workspacePlatform != webworker",
  "experiments.override.gettingStarted.overrideCategory.ms-toolsai.jupyter.jupyterWelcome.when": "workspacePlatform != webworker",
  "jupyter.notebookFileRoot": "${filenameDir}",
  "workbench.startupEditor": "none",
  "audioCues.debuggerExecutionPaused": "off",
  "terminal.integrated.shellIntegration.enabled": true,
  "python.createNewFileEnabled": true,
  "workbench.editor.languageDetection": false,
  "markdown.preview.typographer": true,
  "jupyter.pythonExportMethod": "direct",
  "gitlens.statusBar.enabled": false,
  "gitlens.currentLine.enabled": false,
  "gitlens.hovers.currentLine.over": "line",
  "gitlens.showWelcomeOnInstall": false,
  "extensions.ignoreRecommendations": true,
  "terminal.integrated.commandsToSkipShell": [
    "language-julia.interrupt"
  ],
  "julia.symbolCacheDownload": true,
  "julia.enableTelemetry": true,
  "editor.cursorSurroundingLines": 2,
  "editor.language.colorizedBracketPairs": true,
  "files.hotExit": "onExitAndWindowClose",
  "[json]": {
    "editor.defaultFormatter": "vscode.json-language-features"
  },
  "terminal.integrated.tabs.focusMode": "singleClick",
  "scm.diffDecorationsGutterPattern": {
    "modified": false
  },
  "editor.minimap.enabled": false,
  "jupyter.debugJustMyCode": false,
  "jupyter.logging.level": "verbose",
  "notebook.outputLineHeight": 20,
  "typescript.updateImportsOnFileMove.enabled": "always",
  "jupyter.pythonCompletionTriggerCharacters": ".%",
  "[css]": {
    "editor.defaultFormatter": "vscode.css-language-features"
  },
  "css.format.braceStyle": "expand",
  "explorer.fileNesting.enabled": true,
  "explorer.fileNesting.expand": false,
  "explorer.experimental.fileNesting.operateAsGroup": false,
  "files.autoSave": "afterDelay",
  "notebook.cellToolbarLocation": {
    "default": "right",
    "github-issues": "right"
  },
}

**Comment by amunger** [comment]
no worries. Still repros with all extensions disabled and bisect only makes it one step before stopping.

**Comment by rebornix** [comment]
I'm also seeing the same behavior, it only shows the suggestions when it's unsaved buffer. I'm on Windows if that matters.

**Comment by jrieken** [comment]
Thanks @rebornix - I can reproduce on windows

**Comment by jrieken** [comment]
I (believe) that I now understand: when snippets are active a special completion item provider for that model is registered. From the document that's being edited it uses the scheme, langauge, and path to register a provider (document selector). However, it uses [`path`, not `fsPath`](https://github.com/microsoft/vscode/blob/5ec992bc086b6e6d52397b1ddc779dccda5a06ca/src/vs/editor/contrib/snippet/browser/snippetController2.ts#L168-L172), for the `pattern`-part

**Comment by jrieken** [comment]
Same mistake happens with tab completions: https://github.com/microsoft/vscode/blob/6e1e0b1d899b2d262265e8faeadee98c562cfe7b/src/vs/workbench/contrib/snippets/browser/tabCompletion.ts#L150
