### ISSUE TITLE
Untitled file with associated path shows full path as label

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148409]
Steps to Reproduce:

1. be on POSIX
2. connect via SSH to Windows (this works fine via parallels by installing OpenSSH Server as additional feature on windows and starting that service)
3. open VSCode from POSIX and connect Windows via SSH remote extension
4. open terminal
5. type `code-insiders -r <absolute path to non-existing file on disk>
6. an untitled editor should open

=> 🐛  the label of the editor is the full path instead of the name of the file

The underlying bug here is that we use `path.basename` on a path with backslashes on POSIX. Backslash on POSIX is a valid character for a file/folder, so `path.basename` will return the entire thing.

**Comment by tanhakabir** [comment]
I'm not sure if I did this correctly but a new window reload and opens for me which seems to be fine

**Comment by bpasero** [comment]
@tanhakabir sorry, the steps missed a critical part, esp. how to launch VSCode, can you try again?

**Comment by tanhakabir** [comment]
@bpasero I don't see the full path in label but the tooltip is correct: 
![image](https://user-images.githubusercontent.com/12758612/172663447-672ded21-22bb-4bc4-9789-718857796659.png)

**Comment by bpasero** [comment]
Arghs, disable tabs should show the path as description piece next to the label.
