### ISSUE TITLE
Double-clicking when editing a 'when' expresson opens the 'change hotkey' dialog instead of selecting the current word

### ISSUE THREAD

**Issue by HolyBlackCat** [microsoft/vscode#148493]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Xubuntu 22.04 (Linux x64 5.15.0-27-generic)

Steps to Reproduce:

1. <kbd>Ctrl</kbd><kbd>K</kbd> -> <kbd>Ctrl</kbd><kbd>S</kbd> to open the keyboard shortcuts.
2. Find a shortcut with a complex 'when' expression. Right-click, "Change When Expression".
3. Double-click a word in the expression, as if to select it.

I expected that this would select a single word, like it does elsewhere. Instead, it opens the "change hotkey" dialog.

I propose that a doubleclick should only trigger the dialog when the 'when' expression is not being edited.

**Comment by TylerLeonhardt** [comment]
I think this is yours, @sandy081?
