### ISSUE TITLE
Setting to turn off ALL popups?

### ISSUE THREAD

**Issue by tslocke** [Microsoft/vscode#14840]
- VSCode Version: 1.6.1
- OS Version: MacOS 10.12

Steps to Reproduce:

1. Do any programming in JavaScript

- - -

VS Code is constantly popping up tips etc around the caret. My personal experience is that they are more of a hindrance than a help 99% of the time. I am CONSTANTLY hitting escape to get rid of them so I can see my code.

Is there an option to have them triggered by a shortcut key rather than automatically as I type? This is the first editor I've come across where there's no clear way to do that.

Generally I really love VS Code, but this one feature makes it feel like I'm fighting the editor.

I've already got

    "editor.quickSuggestions": false,

but it hasn't helped.

Thanks

**Comment by rebornix** [comment]
I saw @joaomoreno had a fix for turning off parameter hint in https://github.com/Microsoft/vscode/issues/2972 but this time ppl wants to turn off everything.

**Comment by tslocke** [comment]
`"editor.parameterHints": false` is a huge help : ) Sweet. tyvm :)

**Comment by joaomoreno** [comment]
Closing as it seems disabling quick suggestions and parameter hints was enough.

**Comment by andy-hanson** [comment]
When I type C# code in vscode, every time I type a character, a light bulb pops up (usually "Generate variable"). When I type another character, it disappears for an instant, then appears again. The result is rapid flashing whenever I type, which is seriously distracting!
