### ISSUE TITLE
VSCode windows does not respond while debugging

### ISSUE THREAD

**Issue by kapodamy** [microsoft/vscode#148496]
_Does this issue occur when all extensions are disabled?_: not checked, i need the extensions

- VS Code Version: 1.66.2
- OS Version: Windows 8.1

_Steps to Reproduce:_

1. place a breakpoint somewhere
2. switch to the debugging program **without minimize vscode** (clicking the "mininize button" or the window taskbar icon)
3. wait a few seconds
4. do something in the program to trigger the breakpoint
5. switch back to vscode clicking the taskbak icon 
6.  the bug occurs as follow:
- vscode window become unresponsive for a few seconds (maybe until the taskbar stops flashing)
- minimizing vscode and bring it back (clicking the icon on the taskbar) solves the issue

Here a footage video:

https://user-images.githubusercontent.com/16857233/166129183-78680bd1-489e-4ff3-9de5-e4171a001a90.mp4

**Comment by roblourens** [comment]
Probably same as https://github.com/microsoft/vscode/issues/116865, https://github.com/microsoft/vscode/issues/116615

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/116615
