### ISSUE TITLE
[Feature Request] VSC explorer isolate folder

### ISSUE THREAD

**Issue by AmelianceSkyMusic** [microsoft/vscode#148486]
When we have a lot of folders, we need to simplify view for better concentrate and orientation
![image](https://user-images.githubusercontent.com/38717657/166119137-447f4116-1a3a-464a-bab9-a06b115b51b6.png)

**Comment by albertosantini** [comment]
Did you try https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree?

**Comment by AmelianceSkyMusic** [comment]
> Did you try https://code.visualstudio.com/docs/getstarted/userinterface#_filtering-the-document-tree?

Can I filter only folders?
When I'm trying to filter folder, files inside needed folder also hides
https://streamable.com/km3h91

**Comment by JacksonKearl** [comment]
You can configure `files.exclude` to hide the other folders, otherwise duplicate of #41860
