### ISSUE TITLE
User friendly theme editor

### ISSUE THREAD

**Issue by Keaten3** [microsoft/vscode#148435]
A theme editor inside VS code that would let you see changes to the theme in real-time. It would be nice to have drop-down menus of all different aspects of the editor that could change color with a preview screen off to the side. Preset color options and even color wheels would really help with the user-friendly aspect of it. Functionality to edit pre-made themes and save them would go a long way also. I know there are editors outside of the editor that can do these things, but it would be nice to have a fleshed-out editor within VS code.

**Comment by aeschli** [comment]
Sorry, we don't have any plans for a more sophisticated, graphical, theme editor.

The current approach also lets you try out changes in real-time:
- [customize the current theme](https://code.visualstudio.com/docs/getstarted/themes?source=korben.info#_customizing-a-color-theme) in the settings, see all colors applied live, then [generate the theme](https://code.visualstudio.com/docs/getstarted/themes?source=korben.info#_creating-your-own-color-theme) with the `Developer: Generate Color Theme From Current Settings` command
or
- create a new theme with `yo code` and open it in VS Code and make changes while [testing the theme](https://code.visualstudio.com/api/extension-guides/color-theme#test-a-new-color-theme).
