### ISSUE TITLE
Extention and debug note intallled

### ISSUE THREAD

**Issue by Git-CS-01** [microsoft/vscode#148474]
ADD ISSUE DESCRIPTION HERE

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36
Embedder: vscode.dev

**Comment by Git-CS-01** [comment]
![Screenshot_20220430_162935](https://user-images.githubusercontent.com/89677098/166102725-72d4e4ba-7cc5-422c-a3f1-bdbe450a8976.jpg)
why i cant run

**Comment by roblourens** [comment]
Debugging is not supported on vscode.dev
