### ISSUE TITLE
Markdown rename requires  `.md` extension

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#148490]
Also happens when I do not use the `.md` extension in the link

_Originally posted by @isidorn in https://github.com/microsoft/vscode/issues/148147#issuecomment-1109780515_

**Comment by mjbvz** [comment]
@isidorn I just tested this with the follow workspace:

`a.md`:

```md
# abc
```

`b.md`
```md
[](./a) // rename here
[](./a#abc) // or here on `a`
```

I believe this works as expected. I tried using a new name with and without the `.md` extension (both cases should result in a new file that uses the `.md` extension)

Let me know if you still see any issues with this

**Comment by isidorn** [comment]
Yes. It seems to work fine now. I tried with your simple sample and also in vscode-docs and it is just fine. Thanks for trying it out.

Also I was surprised with all the great `md` support we have now. Great work 👏
