### ISSUE TITLE
Pasting from Nautilus to editor pastes the file name and not the path

### ISSUE THREAD

**Issue by bol7asan** [microsoft/vscode#148499]
Issue Type: <b>Bug</b>

I recently re-installed vscode to the latest version. My OS is Ubuntu 20.04 and it is up to date.

For some reason, I can't copy the path of files from nautilus/filemanger and paste it directly into vscode. 

Pasting anywhere else in the system works fine. Also, pasting into the integrated terminal of vscode works fine also.

Pasting into scripts I write doesn't work. 

Please note that this issue only happens if the source is the file/manager (nautilus)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-40-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2245 CPU @ 3.90GHz (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|62.50GB (55.98GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

**Comment by Stefanqn** [comment]
same for me with either Dolphin or another VSC window. Maybe it's Linux related in general?

**Comment by ralfriegel5** [comment]
same for me. Before finding this issue, I opened a topic on stackoverflow:

[https://stackoverflow.com/questions/72247775/copy-paste-filepath-from-nautilus-files-in-ubuntu-does-not-work-anymore](https://stackoverflow.com/questions/72247775/copy-paste-filepath-from-nautilus-files-in-ubuntu-does-not-work-anymore)

In my case only the filename gets copied. Everywhere else it works.

**Comment by gmankab** [comment]
still actual

**Comment by gmankab** [comment]
same problem with dolphin

**Comment by deepak1556** [comment]
Is this issue still present with latest insiders https://code.visualstudio.com/insiders ?

**Comment by Gui-U** [comment]
> Is this issue still present with latest insiders https://code.visualstudio.com/insiders ?

Yes still relevant in latest insider build (x64 Ubuntu 20.04)

**Comment by deepak1556** [comment]
Can confirm that file paths are copied over to integrated terminal but only filenames are copied into editor area, /cc @bpasero who owns editor area.

**Comment by bpasero** [comment]
Forwarding to editor folks, because this seems about pasting into the code editor.

If I had to guess, terminal is maybe checking for data transfer types and preferring paths over file names? Maybe @Tyriar or @meganrogge could confirm.

**Comment by hediet** [comment]
This is how we read text:
https://github.com/microsoft/vscode/blob/376af084af1ef6ebf35cc1176dca84768aaf42d7/src/vs/platform/clipboard/browser/clipboardService.ts#L133

I don't think we can fix this issue.

**Comment by Archiatrus** [comment]
Works again with 1.79.0 (on my Ubuntu 20.04) :)

**Comment by ralfriegel5** [comment]
Same. Works for me again with 1.80.2

**Comment by ingo-m** [comment]
When I copy-paste a file path into vscode, e.g. `/home/my_name/example.txt`, the value that appears in vscode is `[text](../../example.txt)`.

```
Version: 1.87.0
Commit: 019f4d1419fbc8219a181fab7892ebccf7ee29a2
Date: 2024-02-27T23:42:16.599Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Linux x64 6.5.0-21-generic
```

Also mentioned here: https://github.com/microsoft/vscode/issues/170708

**Comment by mjbvz** [comment]
@ingo-m That's expected in markdown files. You can then use the paste selector to change to a normal path if you prefer:

![Image](https://github.com/microsoft/vscode/assets/12821956/0bc9a924-18cd-45e3-b59c-517a729224eb)

Closing since based on previous comments it sounds like this may no longer be an issue
