### ISSUE TITLE
VSCode busy building symbols and stops the auto complete from working

### ISSUE THREAD

**Issue by DimitarTasev** [Microsoft/vscode#14848]
- VSCode Version: 1.6.1
- OS Version: Windows 7

Hello, I've been having issues with using an extension that builds symbols. I can replicate the issue with both the official C++ and Python extensions.

Some info about the project:

- It's large (10k+ files)
- It's mostly on cpp and python, but there's a wide variety of file types
- I've added loads of file extensions to be ignored (not sure if this affects which files are processed)

Regardless of extension, the auto complete is stuck on `Loading...` most of the time, I imagine that is because the symbols are being built? The symbols also seem to be lost on editor change, resulting in another ~30sec symbol building.

However **Reloading the window** from the command prompt actually refreshes all the symbols and auto complete and builds/loads them in nearly instantly.. until the editor is changed again.

I am not sure whether this is an extension specific issue, however getting exactly the same problem with 2 completely different extension leads me to believe that there could be a deeper problem in VSCode.

I'll provide any additional info you want if I can.

Steps to Reproduce:

1. Load very large project (the one Im working on is 10k+ files)
2. Need an extension that builds symbols for the language, the problem does not exist if symbols are not being built.
3. Play around with the files and editors, the auto complete will stop working and most of the time will be spent building symbols.

**Comment by rebornix** [comment]
Not quite sure who is the owner but see @joaomoreno had perf fix for #1923 so assign to him first.

**Comment by DimitarTasev** [comment]
The problem that was in the previous issue has not reappeared, the big test file loads all the intellisense symbols quickly.

I did some profiling and it seems that for the most part VSCode just hangs idle

**Comment by joaomoreno** [comment]
It would be great to know which extension you refer to. This is very likely an issue for that extension.

**Comment by DimitarTasev** [comment]
@joaomoreno The C/C++ microsoft extension and the Don Jayamanne Python extension both get stuck loading symbols, used on the same project

**Comment by joaomoreno** [comment]
Do they get stuck also when used exclusively? Disable one, try the other. And vice versa.

**Comment by DimitarTasev** [comment]
@joaomoreno Yes they do get stuck when installed exclusively. However with 1.7 the building of the symbols still takes years, but the symbols are no longer lost on each editor change.

**Comment by joaomoreno** [comment]
@jrieken Any thoughts on this?

**Comment by jrieken** [comment]
@DimitarTasev When you say `is stuck` do you mean *high CPU load of main process, the editor is unresponsive* or do you mean *it is just slow, shows loading forever but you can switch to another file, you can still type*?

**Comment by DimitarTasev** [comment]
I'm sorry for not being more clear, by `stuck` i mean `shows loading forever but you can switch to another file, you can still type`, the editor is still as responsive as usual, just symbols show the animated line that moves and auto complete shows `Loading...` for a long time. The CPU usage doesn't increase for `Code.exe`. 

I had the same problem yesterday on a small project as well, just a few files, with the same two extensions (both installed at the same time and each one separately)

**Comment by DimitarTasev** [comment]
This seems to be less of an issue in Windows now, as on Windows all the symbols are usually kept after being built (even though that still takes a while). On Ubuntu 14.04 however the issue persists and the symbols keep being lost, making the default visual studio auto complete unusable

**Comment by joaomoreno** [comment]
@DimitarTasev Is it possible to show us a screencast recording of the behaviour you observe?

**Comment by DimitarTasev** [comment]
I'll try and have a screencast done and up over the weekend at the latest!

**Comment by DimitarTasev** [comment]
The C++ extension works on _Windows_ now, it takes a bit to build symbols, but afterwards they are kept. The Python extension doesn't build symbols properly, leaving me to think that the issue is related to the extensions. On Linux both extensions fail to build the symbols and block any auto-complete until that has happened (if it ever finishes). I'm closing this issue until I have a recording so I can show you the behaviour.

**Comment by DimitarTasev** [comment]
If anyone happens upon a similar problem, look into your extensions and find if they have specific directories to be `included` (the C/C++ extension) in the search or `excluded` (the Python extension). 

Setting those up could help them process your folder faster. 

Watch out for including big directories as they might just parse them recursively (the C/C++ extension), in that case it's better to specify the specific folders containing the C/C++ files.

In the Python extension, you can exclude those big directories from being parsed. 

Hope that helps.
