### ISSUE TITLE
Dragging multi-line `text/uri-list` from tree to editor results in error

### ISSUE THREAD

**Issue by michaeljones** [microsoft/vscode#148411]
Does this issue occur when all extensions are disabled?: No (as it is a custom extension behaviour.)

- VS Code Version: 1.66.2
- OS Version: Ubuntu 20.04.4 LTS

## Steps to Reproduce:

1. Pull down https://github.com/michaeljones/vscode-extension-samples/pull/1 locally
3. Run example
4. Open 'drag & drop tree' down to 'bb' item (or any item)
5. Drag item to editor 
6. Observe that it opens the temp markdown file correctly
7. Uncomment code to add two items to list
8. Run example
9. Repeat the same action
10. Observe that it pop-ups an error

## Expected behaviour

I would assume that all entries would open as tabs

## Context

I have a tree which represents a folder structure. I would like to be able to drag the file items into the editor but I don't mind much about the folders. I don't seem to be able to disable the drag from the folders though (dragging from the folder with no `DataTransferItem` set still allows me to create a split-view panel in the editor even though there is nothing to drag there - I can create another ticket for this if desirable.) So the multi-line `text/uri-list` is because I can't think of what else to meaningfully do with the folders. 

So ideally:
1. I'd like to be able to disable dragging from an entry or have no split-view behaviour when no data has been set to the `DataTransferItem`.
2. Otherwise have the `text/uri-list` work with multiple items as that is the only behaviour I can think of as being reasonable for a folder. There might be others though.

I've just started playing around with the `TreeDragAndDropController` so I might be doing things wrong. Sorry if I've made a mistake with this.

**Comment by alexr00** [comment]
@michaeljones thank you for the complete sample, I can reproduce the bug.

> allows me to create a split-view panel in the editor even though there is nothing to drag there

The empty editor splitting is https://github.com/microsoft/vscode/issues/148622, which you also filed and the fix will be in the May release.

> I'd like to be able to disable dragging from an entry

We're not currently planning on supporting this, but if we get enough extension authors wanting this behavior then we'll consider adding it.

> Otherwise have the text/uri-list work with multiple items as that is the only behaviour I can think of as being reasonable for a folder. There might be others though.

Will be fixed with https://github.com/microsoft/vscode/pull/151224.

**Comment by michaeljones** [comment]
Ace, good to know. Thanks!

**Comment by roblourens** [comment]
Seems like it just concatenates the paths and tries to open one file that can't be found

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/323878/176575490-9c14cc6e-def0-4670-9ae4-89a01170589f.png">

**Comment by roblourens** [comment]
Suspicious @mjbvz 

https://github.com/microsoft/vscode/pull/152756/files#diff-163b39f5ba635edb809137c96235e18f6393d43cbe43754090b4d3929a53bb69R74

**Comment by alexr00** [comment]
The format of text/uri-list was updated to use \r\n instead of \n. When verifying, you'll need to update the example code to use \r\n too.
