### ISSUE TITLE
Use platform agnostic relative paths for workspace file

### ISSUE THREAD

**Issue by Rami-Sabbagh** [microsoft/vscode#148492]
Issue Type: <b>Bug</b>

1. Create a workspace file (`.code-workspace`) on a Windows machine.
2. Add the file to the git repository so the rest of the team can take advantage of a preconfigured one.
3. Clone the repository on a Linux machine (supposedly another team member who is a Linux user instead of a Windows one).
4. VS Code will complain about being unable to locate some workspace folders.

![image](https://user-images.githubusercontent.com/6272475/166123112-3e8928d6-8f4f-41c8-9642-f86fe9ac1c37.png)

## Expected Behavior

VS Code would automatically convert Window-styled paths into Unix-styled paths (internally only) and vice versa.

## Walkthrough

Duplicate the file and manually convert the paths.

## Windows Machine Details (which created the file)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.19GB free)|
|Process Argv|--crash-reporter-id 900e10ac-fc10-4c51-8225-4957ba5ee1d8|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by bpasero** [comment]
You should be able to use relative paths with `/`, can you share an example?

**Comment by Rami-Sabbagh** [comment]
Here's our workspace file:

```json
{
	"folders": [
		{
			"name": "labeeb (workspace)",
			"path": ".",
		},
		{
			"name": "frontend (client)",
			"path": "packages\\client",
		},
		{
			"name": "backend (server)",
			"path": "packages\\server",
		},
	],
	"settings": {
		"typescript.tsdk": ".yarn/sdks/typescript/lib",
		"typescript.enablePromptUseWorkspaceTsdk": true,
	}
}
```

**Comment by bpasero** [comment]
If you replace the `\\` with `/` it should be fine. On POSIX, `\` is a valid character for a file path.

**Comment by Rami-Sabbagh** [comment]
> On POSIX, `\` is a valid character for a file path.

But you can see in the screenshot attached to the first comment vscode complaining about `Unable to resolve folder`
The folder do exist but vscode is not recognizing it.

**The issue contains the machine details of the Windows machine.**
**But the screenshot is from a Linux machine and so the error exists on the Linux machine.**

The workspace file works fine on windows.

> If you replace the \\ with / it should be fine.

Upon replacing all the `\\` with `/` in the workspace file works fine on both Windows and Linux.

## What is the problem?

- Workspace files with paths containing `\\` don't work properly on Linux machines. They are causing the `Unable to resolve folder` error.

## Why it's considered a "non platform agnostic problem"?

- Because if a workspace file is created using a Windows machine, then used in a Linux machine it doesn't work.

## What's the expected behavior?

- If a workspace file is created using a Windows machine, it should work fine on a Linux machine.
- Manually replacing `\\` with `/` is a **manual** solution to the issue, it's expected for vscode to have an automatic solution in itself.

Please tell me if the issue is still not clear.

**Comment by bpasero** [comment]
When a workspace file is created from windows, we use backslash by default to keep it platform specific. If you want to share the file across OS you can change the separators to slashes.

@sandy081 @aeschli I believe one of you also contributed to the format used in multi root workspaces right? Do you remember our reasoning around picking either backslash or slash for paths in the workspace file?

**Comment by Rami-Sabbagh** [comment]
Heyy, keeping it platform specific is not really bad!

But can vscode on Linux machines automatically detect Windows paths and convert them on the fly in-memory?
Just like how Windows does for Unix paths.

**Comment by bpasero** [comment]
@Rami-Sabbagh yeah we could, but keep in mind that backslash is a valid file character on Linux, so this would essentially disable support for any paths with a backslash on Linux.

**Comment by sandy081** [comment]
I do not remember exactly and I assume there is no particular reason. We just followed the path semantics in the platform and we never thought about this specific use case.

**Comment by aeschli** [comment]
I was not involved in the initial decision.
I think for relative paths we should generate forward slashes by default. Workspaces with relative paths are suited to be shared in SCM and we want them to work cross platform.

**Comment by bpasero** [comment]
Yeah I like that 👍

**Comment by bpasero** [comment]
After some discussion we had the idea to use slash on all platforms for all paths. Advantages:
* looks and reads great (vs the `\\` today)
* works cross platform for relative paths
* you can copy and paste paths with slash and open in windows explorer and terminal

The only exception is UNC paths.
