### ISSUE TITLE
Incorrect token colors for parentheses

### ISSUE THREAD

**Issue by SniperGER** [microsoft/vscode#148405]
Opening files that contain parentheses (such as JavaScript, JSON or Python files, maybe others), the syntax highlighter colors parentheses in a way that doesn't match their specified token colors. Instead, they are colored pink or yellow.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.67.0-insider (8632e9c4096eab5773958b9fb3f45f92efba74a8)
- OS Version: Windows 11 (10.0.22000.613), macOS Monterey 12.3.1 (21E258)

Steps to Reproduce:

1. Create a new file
2. Set the syntax to "JSON"
3. Copy and paste this example into your window

```json
{
	"key": "value",
	"key2": {
		"a": true,
		"b": 1234
	}
}
```

In my case, using the default Dark+ theme, it looks like this:

![example](https://user-images.githubusercontent.com/6178765/165897291-4c86e35b-60eb-4f2e-aa9c-75ac0ddecba1.png)

However, the token color definition appears to still use the correct color, as seen here:

![token_colors](https://user-images.githubusercontent.com/6178765/165897373-8b7c30ad-d5d2-4cca-a1de-1eeeeac2e9aa.png)

This issue also appeared a while ago, but was fixed shortly after. The non-Insider build doesn't appear to be affected.

**Comment by gjsjohnmurray** [comment]
Looks like the Bracket Pair Colorization feature.

https://code.visualstudio.com/updates/v1_60#_high-performance-bracket-pair-colorization

**Comment by SniperGER** [comment]
Alright, that seems to be the culprit! Thanks for your help 👍 

Probably missed this in the changelogs, that's why I didn't know about this feature.

**Comment by hediet** [comment]
@alexdima @isidorn maybe it could be helpful to show a notice in the token inspector that the selected token got colored by the bracket colorization feature?

**Comment by isidorn** [comment]
@hediet that makes sense. If we can bake that in.
