### ISSUE TITLE
Auto removes new lines

### ISSUE THREAD

**Issue by Ajith-Kumar-G** [microsoft/vscode#148467]
Issue Type: <b>Bug</b>

Welp!! Immediately removes newlines after creating one, unable to edit anything

VS Code version: Code 1.66.0 (e18005f0f1b33c29e81d732535d8c0e47cafb0b5, 2022-03-30T05:50:14.623Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
save-typing|akh|0.1.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
doxdocgen|csc|1.4.0
dart-code|Dar|3.38.2
flutter|Dar|3.38.1
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.24
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.15.13
vs-color-picker|lih|1.0.0
theme-monokai-pro-vscode|mon|1.1.20
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.16.0
LiveServer|rit|5.7.5
nodejs-extension-pack|wad|0.1.9
JavaScriptSnippets|xab|1.8.0

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Ajith-Kumar-G** [comment]
yeah, it seems to be caused by flutter and dart extension
