### ISSUE TITLE
Feature request: Sorting repositories according to the workspace folder order

### ISSUE THREAD

**Issue by nexcvon** [microsoft/vscode#148425]
Git Graph settings 'Repository Dropdown Order' provides an option 'Workspace Full Path':
> Sort repositories according to the Visual Studio Code
> Workspace Folder order, then alphabetically by the
> full path of the repository.

I have a workspace with many folders. A sorting option like this would be very useful.

**Comment by gjsjohnmurray** [comment]
Sorting options are coming in 1.67 and you can already try them if you install [Insiders](https://code.visualstudio.com/insiders).

**Comment by lszomoru** [comment]
This is now supported through the `scm.repositories.sortOrder` setting.
