### ISSUE TITLE
Set includePath in c_cpp_properties.json of.vscode, but still use headers from the system path, not from workspace first

### ISSUE THREAD

**Issue by remainfox** [microsoft/vscode#148412]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.66.2
- OS Version:  Win10.0，19043

Steps to Reproduce:

1. Add OpenSSL Header Path , Set IncludePath in .vscode/c_cpp_properties.json
2. Click on the header file in vscode, want to jump to the openssl headers of workspace, but still to system openssl headers (/ usr/local/include/openssl)

```json
"configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "${workspaceFolder}/../depends/install/include/openssl",
                "${workspaceFolder}/../depends/**",
                "${default}"
            ],
```

**Comment by aeschli** [comment]
Please file this against the C++ extension that you use.

**Comment by remainfox** [comment]
The OPTION to set includepath is not found in the C/C ++ extension
