### ISSUE TITLE
inconsistency in configuration registry of files.contribution.ts

### ISSUE THREAD

**Issue by cognominal** [microsoft/vscode#148421]
A key is not spelled the same way in the `enum` and the `enumDescriptions`
`ModificationsIfAvailable` in the first and  `ModificationIfAvailable` in the second.
I don't know the consequences if any so I won't propose any fix that may break localisation.

See around https://github.com/Microsoft/vscode/blob/main/src/vs/workbench/contrib/files/browser/files.contribution.ts#L324:L324

**Comment by aeschli** [comment]
The second key is for the NLS look up file. If can be named anything, doesn't have to match the enum key.

You can purpose a fix for consistency, but it really doesn't matter.
