### ISSUE TITLE
Python. Displaying the type (class) of variables in the "Variables" panel during debugging, as implemented in PyCharm

### ISSUE THREAD

**Issue by dbulgakov7** [microsoft/vscode#148436]
Is it possible for Python to display variable type (class) in the "Run and Debug" -> "Variables" panel?
For simple types, it is not difficult to understand the type (class) of a variable, but for complex types it can be a problem. Moreover, in VS Code, information about a variable type does not always display information in Special Variables -> __class__

I attach screenshots of how the information about variables in PyCharm and VS Code looks like. What I want to see in the PyCharm screenshot is underlined with red lines.

![pycharm_under](https://user-images.githubusercontent.com/73781118/165974624-1543f339-3868-4fca-92ab-faddce155acf.png)

![vscode](https://user-images.githubusercontent.com/73781118/165974677-cb911b1e-e2ce-4005-835e-3b88928c811d.png)

**Comment by roblourens** [comment]
I think this is a request for the python extension
