### ISSUE TITLE
debug a mvc project with firefox, Stuck for more than ten seconds

### ISSUE THREAD

**Issue by jack-liew** [microsoft/vscode#148460]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.2
- OS Version: win 11

Steps to Reproduce:

1. Debug a mvc project with firefox, If I set a breakpoint,vscode will stuck for more than ten seconds.
but,When I switch to firefox and go back to vscode, vscode worked.
2. If use ms edge, There is no problem .

Thanks

**Comment by roblourens** [comment]
Can you explain more what you mean by 

> vscode will stuck for more than ten seconds.

Does this mean the window is hanging and nothing happens when you click in it? Or something else?

**Comment by jack-liew** [comment]
> Can you explain more what you mean by
> 
> > vscode will stuck for more than ten seconds.
> 
> Does this mean the window is hanging and nothing happens when you click in it? Or something else?
---------------------------------

Vscode becomes unresponsive. when move the mouse on vscode menu or editer area, the cursor over vscode changes very slowly, eventually changes to a hand cursor. but, when I switch to firefox and go back to vscode, everything is fine.  

If use microsoft edge, everything be ok.
--------------------
![动画](https://user-images.githubusercontent.com/102201538/167050999-5a4b78bb-9c40-46a3-8d39-78aeaa06bf22.gif)

**Comment by roblourens** [comment]
Are you using this extension? https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug or only debugging C# code?

**Comment by jack-liew** [comment]
> Are you using this extension? https://marketplace.visualstudio.com/items?itemName=firefox-devtools.vscode-firefox-debug or only debugging C# code?

-----------------
just C#.
-----------------
Thanks

**Comment by roblourens** [comment]
Can you try starting vscode with the flag `--disable-features=CalculateNativeWinOcclusion`? Maybe this is like https://github.com/microsoft/vscode/issues/132142

**Comment by jack-liew** [comment]
> Can you try starting vscode with the flag `--disable-features=CalculateNativeWinOcclusion`? Maybe this is like #132142

-----------------
It worked, thank U.
-----------------

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/123257
