### ISSUE TITLE
Unable to resolve your shell environment.... Why is the resolver failing?

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#148434]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin x64 20.6.0

Since the last 2 releases (1.65?) I've been getting this notification on the first launch of VSCode (from the dock). It didn't happen before but now happens every time. See below

<img width="530" alt="Screenshot 2022-04-29 at 16 02 57" src="https://user-images.githubusercontent.com/936006/165972533-f83d0177-afb1-42a3-8e40-4223af505630.png">

Steps to Reproduce:

1. Start VSCode for the first time on MacOS
2. The notification pops up, closing it then trying to use things like Docker fail

I have followed https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails but im sure i don't have anything taking more than "10 seconds" to resolve. i.e launching iterm has no issues.

Secondly this only happens the first time, if i close and launch VSCode from the Dock again it works fine. So why would only the first time fail? 
I wonder if this "resolver" script can give more feedback as to what exactly is failing?

Related: https://github.com/microsoft/vscode/issues/113869

**Comment by jasonwilliams** [comment]
I think I managed to resolve it following https://spin.atomicobject.com/2022/01/18/terminal-lazy-loading/ it may be worth linking to that from https://code.visualstudio.com/docs/supporting/faq#_investigate-slow-shell-initialization

**Comment by ZantsuRocks** [comment]
The best solution for this in my opinion is to let the user choose waiting timeout for shell envs to load.

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode-docs/pull/5303#issuecomment-1116190007
