### ISSUE TITLE
C++ parameter suggestion

### ISSUE THREAD

**Issue by Yuang98** [microsoft/vscode#148430]
Issue Type: <b>Feature Request</b>

The parameter suggestion now can't select the proper overload according to the arguments we've typed in. And if I select the overload version by ↑ or ↓, the hint will change if I move to the next argument. Could vscode support the overload deduction, or could the parameter suggestion be fixed after I choose it mannually?

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by JacksonKearl** [comment]
\extC++
