### ISSUE TITLE
All debug adapters: support `evaluateName` attribute for Variables

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#14846]
If a Variable has an `evaluateName` attribute, the VS Code debugger UI will use this instead of creating an evaluatable expression by using some heuristics.
All debug adapters should support this mechanism so that VS Code can drop the heuristic.

**Comment by isidorn** [comment]
We should realeae note this

**Comment by weinand** [comment]
@isidorn Chrome debug already implements `evaluateName`.
Are you are using `evaluateName` already?

**Comment by isidorn** [comment]
@weinand yes the frontend already uses `evaluateName` when it is provided

**Comment by weinand** [comment]
@isidorn for the final removal of the old heuristics based implementation I've created a followup issue. #25166

**Comment by weinand** [comment]
For `"protocol": "legacy"` verify that "Add to watches" adds a proper "evaluatable expression" to the watches view.

Please note: for array '..' chunks, and Maps and Sets the (still existent) heuristic in VS Code will add a bogus expression to the watches view (see bug #25147). This heuristic will be removed in the May milestone (see #25166).
