### ISSUE TITLE
vscode starts with a  weird window 7 aero UI first 

### ISSUE THREAD

**Issue by T-Arjun** [microsoft/vscode#148432]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  version 1.66
- OS Version: Windows 10 home single language 

Every time I open vscode
I get this weird window 7 aero UI first and then vscode app starts . At first I thought it might be some operating system or some configuration problem . But I tried on windows 10 and on windows 11 .and turns out both of them has this problem . I tried installing older version of vscode and the problem didn't appear.
![unknown](https://user-images.githubusercontent.com/68766323/165970690-62450a74-056c-472b-aec2-76de6fb8ea08.png)

**Comment by soumesh2002** [comment]
Even I'm facing the same issue, but seems they have closed my issue without giving me a solution.

**Comment by Harry-Hopkinson** [comment]
I have been facing it as well, it only shows up on the newest version of vscode.

**Comment by T-Arjun** [comment]
@Harry-Hopkinson Yes , I tried installing an older version of vscode and the problem didn't appear. 

@soumesh2002  Just for confirmation , I asked my friend to check this problem . Even he had this same problem . So its a common problem . I guess all windows users face this issue.
