### ISSUE TITLE
Explorer views not merge during initial load

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148403]
* only a single view in the explorer viewlet. This gives the pretty merged title
* connect to a remote 
* while first connection happens the views aren't merged 

https://user-images.githubusercontent.com/1794099/165897072-2dd8216b-c970-477b-a691-30a70036900b.mov

**Comment by bpasero** [comment]
I think this is https://github.com/microsoft/vscode/issues/147280.

**Comment by sandy081** [comment]
/duplicate

Yes
