### ISSUE TITLE
Do not snap to minimize when resizing window or sidebar/panel

### ISSUE THREAD

**Issue by ufateh** [Microsoft/vscode#1484]

**Comment by ufateh** [comment]
1. Split the editor.
![1](https://cloud.githubusercontent.com/assets/7270662/11914202/5c31a814-a69b-11e5-9070-46cfa04c0396.png)

2. resize the window
![2](https://cloud.githubusercontent.com/assets/7270662/11914207/75521e50-a69b-11e5-91b7-bda98b1e8269.png)

3. resize window again and splitted-editor are affected
![3](https://cloud.githubusercontent.com/assets/7270662/11914213/a9ee9dc8-a69b-11e5-87c5-7d5bdab44c77.png)


On re-sizing, the vertical partition of the editor should be relative.

**Comment by bpasero** [comment]
@ufateh this is because you drag the window small enough that the one editor becomes minimized. In this state it will not grow again after you expand.

**Comment by ufateh** [comment]
@bpasero in sublime editor, re-sizing window do not minimize any of the editors.

**Comment by thepont** [comment]
Becomes a bit of an issue if you're using i3 for window management, and switching between full screen and tiled.

![desktop-animation5](https://cloud.githubusercontent.com/assets/2901992/15917845/9f0c28c8-2e43-11e6-925e-240412be93d1.gif)

**Comment by bpasero** [comment]
Verify:
* resize the window with multiple editors open small enough to hit minimal size of the editor and then grow the window again, no editor should be stuck in minimized state
* test the same resizing sidebar or panel
* test both when vertical or horizontal layout is enabled
* test that you can still minimize/maximize editors by sizing them via Sash or using the related action (Minimize other editors)

**Comment by octref** [comment]
Not working for panel:

![resize](https://cloud.githubusercontent.com/assets/4033249/19748785/c365b5be-9b98-11e6-99ec-47966b6ffc1c.gif)

**Comment by bpasero** [comment]
@octref good catch but that is actually a very different issue, can you please report it separately? My fix was only going into the area of editors minimizing, I was not aware of the panel behaving like that.

**Comment by octref** [comment]
Tracked at #14594

**Comment by chrmarti** [comment]
Verified as per instructions to verify. The ratio between non-minimized editors can still change though. (Make one 'almost' minimized and then shrink&grow window horizontally to reproduce.)
