### ISSUE TITLE
[Feature Request] VSC explorer hide / show folders

### ISSUE THREAD

**Issue by AmelianceSkyMusic** [microsoft/vscode#148487]
When we have a lot of folders, we need to simplify view for better concentrate and orientation, we can hide some folders from explorer that we don't use
![image](https://user-images.githubusercontent.com/38717657/166119175-96a43253-e9e2-4413-9089-31a0a3a03151.png)

**Comment by albertosantini** [comment]
Generally speaking, I add that in `.vscode/settings.json` in the root of the project.

For example:

```
{
    "files.exclude": {
        "**/node_modules": true
    },
    "search.exclude": {
        "**/node_modules": true
    }
}
```

**Comment by AmelianceSkyMusic** [comment]
> 

Thanks. Nice tip. I have tried it already.
Anyway, I'd like to have the possibility to hide / show all folders except one in a quick way using GUI.

**Comment by JacksonKearl** [comment]
Same as #148486
