### ISSUE TITLE
Issue Reporter window is blank

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#148447]
On the latest Insiders, the issue reporter is blank for me.

1. Open the Issue Reporter ("Help: Report Issue" command).
2. :bug: Issue Reporter doesn't load.

![A screenshot of the Issue Reporter window, showing that it is blank](https://user-images.githubusercontent.com/7199958/166007142-998a5586-73c4-420c-8fbd-b35a0f631e83.PNG)

**Comment by gjsjohnmurray** [comment]
Doesn't happen with OSS built from main right now.

**Comment by jeanp413** [comment]
it still happens building from sources, this is the commit ed63059a4752d031535182b1d6eb37719483fbbd that broke it
created a PR fixing it https://github.com/microsoft/vscode/pull/148456
