### ISSUE TITLE
AudioContext.decodeAudioData() error: Uncaught (in promise) DOMException: Unable to decode audio data

### ISSUE THREAD

**Issue by lanly-dev** [microsoft/vscode#148494]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1. Run debug [spectrogram](https://github.com/lanly-dev/VSCode-Spectrogram) from source
2. Open a directory that has an mp3 audio file
3. Select a valid mp3 -> webview shows up, and the error prompted `Unable to decode audio data.`
4. You could check out the error in the developer tool's console

The extension has never been working on official and insider build (same error), but somehow it worked in the exploration build in the past. The extension worked fine when I tried out the extension on this old exploration build: https://github.com/microsoft/vscode/issues/94523#issuecomment-614241358. If I update the exploration vscode to 1.66, it doesn't work anymore and gives out the error.

I'm not sure if this error is intentional (maybe vscode or electron doesn't want to include the necessary codec to decode mp3 files) or a bug for the newer version? But `AudioContext` should work fine, at least in the past, see the issue https://github.com/microsoft/vscode/issues/78333.

VS Code version: Code - Exploration 1.66.0-exploration (b056e68d8ddb4036ac8453a67c63f559589850fc, 2022-03-10T09:18:09.603Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (3.66GB free)|
|Process Argv|--crash-reporter-id 0f541a63-ae4f-4db5-913f-fc5df9332f75|
|Screen Reader|no|
|VM|40%|

**Comment by mjbvz** [comment]
This is likely because the official builds do not include a full ffmpeg version (which I believe contributes support for mp3s)

**Comment by deepak1556** [comment]
Yes the current ffmpeg library shipped with insiders, stable and explorations does not support `mp3` codec. We are currently looking to [support it](https://github.com/microsoft/vscode/issues/118275#issuecomment-1113117320), you can follow https://github.com/microsoft/vscode/issues/118275 for updates. Thanks!
