### ISSUE TITLE
Terminal list first item is not centered

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148559]
I have zoom: 1

![Recording 2022-05-02 at 15 34 47](https://user-images.githubusercontent.com/900690/166242603-d543ab8c-2c61-4e17-9669-558063e24a13.gif)

Notice how the input box border is missing in the first item.

**Comment by Tyriar** [comment]
Can you change to a theme that shows the border? This is Light+

![image](https://user-images.githubusercontent.com/2193314/166479009-85c253b3-2fb0-4dde-9be5-26b82522057e.png)

**Comment by bpasero** [comment]
Oh yeah, maybe this is because my `focusBorder` is set to `white`.
