### ISSUE TITLE
Add auto-hide output (feature suggestion)

### ISSUE THREAD

**Issue by jsa41394** [Microsoft/vscode#14850]
Similar to VS Studio, very annoying to click "close output" after every code/task run.

It should hide when mouse hovers over code, or at least when click code (faster than clicking little close button in the corner)

**Comment by rebornix** [comment]
We have API to toggle panel `workbench.action.togglePanel` and you can listen to selection change so it's a good candidate for an extension.

I'll close this first as this kind of behavior change requires UI analysis but feel free to upvote/downvote on this issue then let's see if we want to have it built in.
