### ISSUE TITLE
Default 'Step into' keybinding conflicts with default macOS shortcut

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#148586]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: macOS 12.3.1

On macOS, the default behavior of F11 is to show the desktop. This conflicts with the VS Code default for `workbench.action.debug.stepInto`, which also uses F11.

Steps to Reproduce:

1. Open VS Code
2. Start the debugger and hit a breakpoint
3. Press F11

**Comment by gjsjohnmurray** [comment]
/duplicate

https://github.com/microsoft/vscode/issues?q=is%3Aissue+macos+f11+is%3Aclosed
