### ISSUE TITLE
LD_LIBRARY_PATH env var "stuck"

### ISSUE THREAD

**Issue by njbrake** [microsoft/vscode#148553]
Issue Type: <b>Bug</b>

Hi! No idea what is happening but my LD_LIBRARY_PATH is stuck on a set value in the integrated terminal for an SSH target. If I ssh into the target via my terminal (still using ZSH) the LD_LIBRARY_PATH variable is unset, but if I access using the integrated terminal, it is set and I can't determine what is setting it. Seems like maybe vscode is caching a value (because at one point I did have it set via my .zshrc).

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-39-generic
Remote OS version: Linux x64 5.13.0-39-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 26acfa46-ee50-4022-bc13-3d71412ce322|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.13.0-39-generic|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (10 x 2304)|
|Memory (System)|15.63GB (3.33GB free)|
|VM|100%|

|Item|Value|
|---|---|
|Remote|SSH: vm|
|OS|Linux x64 5.13.0-39-generic|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (10 x 2304)|
|Memory (System)|15.63GB (3.33GB free)|
|VM|100%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
terraform|has|2.22.0
better-cpp-syntax|jef|1.15.13
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.5.0
terraform|has|2.22.0
vscode-ansi|ili|1.1.2
better-cpp-syntax|jef|1.15.13
vs-cron|mkl|3.0.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
cmake-tools|ms-|1.11.14
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
hexeditor|ms-|1.9.6
vscode-xml|red|0.20.0
vscode-yaml|red|1.7.0
wav-preview|suk|2.0.2
cmake|twx|0.0.17
clang-format|xav|1.9.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by meganrogge** [comment]
do you have `terminal.integrated.shellIntegration` enabled?

**Comment by njbrake** [comment]
Hi @meganrogge, sorry for the slow response! For some reason I didn't get a notification that you had asked a question 🤦 .

No, from looking at my settings.json, I do not have `terminal.integrated.shellIntegration` enabled.
