### ISSUE TITLE
No option to create a fork when unable to push to a repo

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#148568]
For step 4 of https://github.com/microsoft/vscode/issues/143083#issuecomment-1109436736, when I try publishing the branch, I get the error "Git: remote: Permission to joaomoreno/test-pr-templates.git denied to rzhao271." There is no option to create a fork:
![Screenshot showing modal dialog. None of the options are to create a fork](https://user-images.githubusercontent.com/7199958/166001530-d7c884e3-edcd-4fdf-9124-ab3c15712faa.PNG)

_Originally posted by @rzhao271 in https://github.com/microsoft/vscode/issues/143083#issuecomment-1113597175_

**Comment by joaomoreno** [comment]
@connor4312 says:

I got the same issue on the latest Insiders

<img width="1202" alt="image" src="https://user-images.githubusercontent.com/2230985/176970138-7cf0c0fc-9841-471e-8bd3-f5fd9c879707.png">

Command output:

```
> git push -u origin test-branch
ERROR: Permission to joaomoreno/test-pr-templates.git denied to connor4312.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Remote URL:

```
> git config --get remote.origin.url
git@github.com:joaomoreno/test-pr-templates.git
```

**Comment by joaomoreno** [comment]
@connor4312 Can you give me *exact* steps?

**Comment by joaomoreno** [comment]
I think I figured it out.

**Comment by joaomoreno** [comment]
**Verification:**

1. Run `Git: Clone` and clone https://github.com/joaomoreno/test-pr-templates/
2. Create a branch
3. Make a change to `README.md` and commit
4. Attempt to push/publish that branch. Code should tell you that you can't push to that repo and will offer to fork the repository, accept.
