### ISSUE TITLE
vscode wont run in WSL mode 

### ISSUE THREAD

**Issue by josepagan** [microsoft/vscode#148504]
We have written the needed data 
Issue Type: <b>Bug</b>

After a clean install of W11 with all updates and installing wsl  Ubuntu with no issues. For some reason when I try to open a file from wsl with the usual 'code .' vscode wont trigger the fetching of components needed to run WLS and it will open the file as if it was just a normal part of the windows filesystem.

Opening a terminal within vscode will open a power shell session with PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\Ubuntu\home\MYNAME>

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.73GB (2.61GB free)|
|Process Argv|. --crash-reporter-id 453a8feb-54c4-4570-98de-b235d747af81|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

into your clipboard because it was too large to send. Please paste.

**Comment by aeschli** [comment]
Can you run (from your WSL shell):
` VSCODE_WSL_DEBUG_INFO=true code .`

And paste the output here?
