### ISSUE TITLE
Explorer file nesting: Add support for simple string transformation in patterns

### ISSUE THREAD

**Issue by colinfang** [microsoft/vscode#148557]
It would be great if we could allow nesting for filenames that differ slightly from the parent filename e.g.

- parent `filename`
  - Allow a pattern to nest `Filename` // Capitialize
  - Allow a pattern to nest `FILENAME` // Uppercase
- parent `FILENAME`
  - Allow a pattern to nest `fILENAME` // Un-capitialize
  - Allow a pattern to nest `filename` // Lowercase

I have a lot of files like `Foo Bar.md` and `foo_bar.ts` and ultimately I would love to nest those `.ts` under the corresponding `.md` . This would be not too hard to achieve once the transformation mentioned above is implemented.

**Comment by JacksonKearl** [comment]
What platform are you on? Most file systems are case insensitive and nesting should respect that. Supporting substituting spaces for underscores is a different matter.
