### ISSUE TITLE
VS Code extension host launches 2nd VS Code Icon in dock on macOS

### ISSUE THREAD

**Issue by didier** [microsoft/vscode#148544]
Issue Type: <b>Bug</b>

1. Start up VS Code on macOS 12.3.1 Monterey
2. Wait for the extension host to start up
3. Notice a second VS Code icon appear in the dock. 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:47:29.396Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 5|
|Memory (System)|32.00GB (8.29GB free)|
|Process Argv|--crash-reporter-id 3d2f6136-acb4-4301-9e21-54d9feb3bd9c|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
svelte-intellisense|ard|0.7.1
astro-vscode|ast|0.16.0
spellright|ban|3.0.64
vscode-tailwindcss|bra|0.8.3
better-toml|bun|0.3.2
path-intellisense|chr|2.8.0
postcss|css|1.0.9
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
vscode-svelte-snippets|fiv|0.5.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
copilot|Git|1.15.5815
vscode-pull-request-github|Git|0.40.0
gitkraken-authentication|git|1.0.3
headwind|hey|1.7.0
JSDocTagComplete|Hoo|0.0.2
howivscode|How|0.1.0
caddyfile-support|mat|0.2.0
template-string-converter|meg|0.6.0
fluent-icons|mig|0.0.17
dotenv|mik|1.0.1
vscode-dotnet-runtime|ms-|1.5.0
playwright|ms-|0.2.3
live-server|ms-|0.2.12
vsliveshare|ms-|1.0.5527
debugger-for-edge|msj|1.0.15
svelte-autoimport|piv|1.0.4
material-icon-theme|PKi|4.16.0
prisma|Pri|3.13.0
vscode-thunder-client|ran|1.16.2
java|red|1.5.0
vscode-sort-json|ric|1.20.0
mdx|sil|0.1.0
shader|sle|1.1.5
stately-vscode|sta|1.7.6
addDocComments|ste|0.0.8
vscode-stylelint|sty|1.2.2
svelte-vscode|sve|105.16.0
pdf|tom|1.2.0
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
fig|wit|0.0.6
markdown-all-in-one|yzh|3.4.3

(2 theme extensions excluded)

</details>

**Comment by didier** [comment]
![CleanShot 2022-05-02 at 12 55 01](https://user-images.githubusercontent.com/9499859/166223449-95855863-9b24-4908-bf03-234c548b873f.png)

**Comment by alexdima** [comment]
I also see this every now and then. But I don't think this has anything to do with the extension host.

**Comment by didier** [comment]
Well, I’m not 100% sure either, but (I should have mentioned this) closing the second icon causes the extension host to quit.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by deepak1556** [comment]
Can you disable spellright extension and see if the issue repros ? If not, please try our extension bisect utility https://code.visualstudio.com/blogs/2021/02/16/extension-bisect#_welcome-extension-bisect to narrow down the extension.

Duplicate of https://github.com/microsoft/vscode/issues/138712

**Comment by didier** [comment]
@deepak1556 Yep, Spellright seemed to be the culprit! Can't reproduce this issue with Spellright disabled.
