### ISSUE TITLE
Couldn't install the Python extension

### ISSUE THREAD

**Issue by roblourens2** [microsoft/vscode#148598]
Had a confusing bad experience trying to get vscode set up for a new user at the PyCon booth.

- Installed vscode on a Windows laptop
- Find the Python extension, click "Install". It said "Installing" for at least 5 minutes. We thought it could be slow convention center wifi, although extensions at the booth installed very quickly. Eventually, we reloaded the window
- Clicked "Install" on the Python extension, and it would flash to "Installing" and immediately go back to "Install". Clicked several times with the same result. Reloaded the window again, same result. I didn't check for errors, I was just trying to get it to work.
- Opened `~/.vscode/extensions` and deleted everything inside. I think that vscode installs extensions somewhere else then copies them over to that folder. I didn't know where that temp folder is, so I couldn't clear that out. Reloaded and tried to install the extension again, but got the same result.
- Then I tried to install the pre-release version of the Python extension as a test, and that worked. Left it there.

Dunno if this is useful without logs or a user who can repro, but do you have any idea?

**Comment by sandy081** [comment]
Hmm very weird. Logs would be helpful to understand what happened. Were you on remote (ssh/wsl) or on local window? We download VSIXs in `<user-data-dir>/CachedExtensionVSIXs` and extract them into `~/.vscode/extensions` folder with the dot at the beginning of the name and rename it to by removing the dot. If you have the set up, we can get the logs from the `<user-data-dir>/Logs` folder?

**Comment by roblourens2** [comment]
I at least know that the extension was not there with the dot. There must have been something wrong with the vsix in `CachedExtensionVSIXs`? I don't have any way to talk to the customer or get logs. So if there isn't anything you can do with this info, feel free to close it.

**Comment by sandy081** [comment]
Sorry that I can't do anything with the given info. If you encounter this again please try to provide me the shared process logs.
