### ISSUE TITLE
Able to trigger double the selfhost build tasks simultaneously

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148560]
Not sure how, I think I pressed <kbd>Ctrl Shift B</kbd> twice real fast:

![image](https://user-images.githubusercontent.com/22350/166244883-03f93a14-5d05-462b-921f-91618b69e651.png)

**Comment by alexr00** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/141774. There's a difficult to remove delay between when the build command is executed and when the tasks are considered to be running.
