### ISSUE TITLE
Could we have in search an option to search ignoring underscore (_) ?

### ISSUE THREAD

**Issue by doivosevic** [microsoft/vscode#148543]
Lets say you are searching for some variable name in a codebase with multiple languages or there is some additional serialization/deserialization code which uses different casing (snake_case instead of camelCase e.g.). You can easily write a regex for this, but would this be a common enough use case to get a separate button next to 
![slika](https://user-images.githubusercontent.com/6378638/166220536-a1e73d49-7bb1-4752-ac36-fc117331dcf9.png)
?

**Comment by roblourens2** [comment]
I don't think this is a common enough case. It's better for you to write the regex, than for us to try and guess (or change your query to `a_?b_?c_?` etc)
