### ISSUE TITLE
[loc][Query][VSCode] Please clarify the single word strings

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#14859]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Enabled
Installed

File Name:
src\vs\workbench\parts\extensions\electron-browser\extensionsWidgets.nls.resx

Resource ID:
".resx", 0; "enabled"
".resx", 0; "installed"

Query:
Cany ou please clarify what is enabled/installed?

**Comment by joaomoreno** [comment]
The adjectives refer to **extensions** as in:

- An extension is enabled.
- An extension is installed.
