### ISSUE TITLE
Whitespace below code, remove ability to scroll all the code out of sight

### ISSUE THREAD

**Issue by adjnor** [Microsoft/vscode#14856]
- VSCode Version: 1.6.1 
- OS Version: Mac OS Sierra 10.12.1 

Steps to Reproduce:

1. Open any text file
2. Scroll to the bottom.

The scrolling doesn't stop at the end of the code, but continues until almost all the code is out of sight. This results in seeing an empty window (since the code is now out of sight), needing to scroll back up to see the last bits of code.

It is not a major issue but perhaps an option to have the scrolling stop at the end of code would be useful.

**Comment by rebornix** [comment]
Set `"editor.scrollBeyondLastLine": false`

**Comment by kaiwood** [comment]
The setting you are looking for exists, it's "editor.scrollBeyondLastLine".
