### ISSUE TITLE
Custom menu blends in with various background

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#148587]
<img width="353" alt="CleanShot 2022-05-02 at 13 52 20@2x" src="https://user-images.githubusercontent.com/35271042/166325845-2bacae03-4dd8-447d-b504-4ccf321c920d.png">

Would love it if we could polish the visual styles of our custom menus as sometimes they blend in with the background and don't look as nice. Also worth looking at a few different examples from other products that have nice menus:

<img width="348" alt="CleanShot 2022-05-02 at 13 53 15@2x" src="https://user-images.githubusercontent.com/35271042/166325964-c82fd7f0-ec53-4ae1-af90-90e263d99cb0.png">

<img width="266" alt="CleanShot 2022-05-02 at 13 54 22@2x" src="https://user-images.githubusercontent.com/35271042/166326050-70a88fcb-a172-4c93-a2e0-76bdc7f77392.png">

<img width="240" src="https://user-images.githubusercontent.com/35271042/166326484-ecf430f7-2fe6-46a9-96a8-2fe5cf7fc7f7.png">

**Comment by daviddossett** [comment]
Emojis in front of every item. Done 😛

Kidding. Good shout—I'll propose some ideas here in the next week or two.
