### ISSUE TITLE
la touche j

### ISSUE THREAD

**Issue by bleudy-kitondo** [microsoft/vscode#148565]
Issue Type: <b>Performance Issue</b>

ma touche j ne foctionne pas, on me dit que la touche j est utilisé

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-40-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 1134)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.51GB (10.12GB free)|
|Process Argv|--unity-launch --crash-reporter-id c73d356a-0c2a-40ab-9c65-3b52a43c9ceb|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   159	  5326	code main
    0	    32	  5331	   zygote
    1	    95	  5367	     gpu-process
    0	    32	  5332	   zygote
    0	     0	  5334	     zygote
    0	    79	  6296	       window (undefined)
    2	    79	  6345	       issue-reporter
    0	    48	  5376	   utility-network-service
    0	   238	  5393	   window (● Untitled-1.ipynb - Visual Studio Code)
    0	   191	  5424	   extensionHost
    0	    79	  5498	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=5424
    0	    64	  5499	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=5424
    0	     0	  5521	     /home/bleudy/.vscode/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/cpptools
    0	   159	  5581	     /usr/share/code/code --ms-enable-electron-run-as-node /home/bleudy/.vscode/extensions/ms-python.vscode-pylance-2022.4.3/dist/server.bundle.js --cancellationReceive=file:57d7cddcf52b69d1af121bf159d4a379ffca450373 --node-ipc --clientProcessId=5424
    0	    64	  5602	     /usr/share/code/code --ms-enable-electron-run-as-node /usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=5424
    0	    95	  6315	     /usr/share/code/code --ms-enable-electron-run-as-node /home/bleudy/.vscode/extensions/ms-python.vscode-pylance-2022.4.3/dist/server.bundle.js --cancellationReceive=file:3cdbffa4b678a8a785c670797148571677e81c5b8e --node-ipc --clientProcessId=5424
    0	   127	  5436	   shared-process
    0	    64	  5449	     ptyHost
    0	     0	  5513	       /usr/bin/bash
    0	    64	  5486	     fileWatcher
    0	     0	  6418	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  6419	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
askia-qexml-generator-extension|Ask|1.0.1
htmlplay|bia|0.0.10
vscode-pull-request-github|Git|0.41.2022040609
vscode-language-pack-fr|MS-|1.66.3
csharp|ms-|1.24.4
vscode-ros|ms-|0.8.2
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.8
js-debug-nightly|ms-|2022.4.2217
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.9.2
vscode-janus-debug|otr|1.5.8
ruby|reb|0.28.1
java|red|1.5.0
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vscode-ruby|win|0.28.0
eno|Wsc|2.3.53
php-debug|xde|1.26.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by chrmarti** [comment]
Where do see this message? Could you append a screenshot? Please reply in English. Thanks.
