### ISSUE TITLE
Intellisense stuck loading forever

### ISSUE THREAD

**Issue by kingsleykbc** [microsoft/vscode#148590]
Issue Type: <b>Bug</b>

My intellisense isn't working. At the same time, vscode is consuming over 25% of my CPU. And the program i'm writing isn't even running.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (5.06GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Kingsley/Desktop/Projects/LBH/lbh-server --crash-reporter-id deab6e83-e33f-40e7-a81c-2c4861ba2767|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (89)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-languagetool|ada|3.8.0
vscode-languagetool-en|ada|3.8.0
vscode-styled-jsx-languageserver|And|1.0.1
vscode-color|ans|0.4.5
vscode-apollo|apo|1.19.10
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-styled-jsx|bla|2.1.1
vscode-intelephense-client|bme|1.8.2
simple-react-snippets|bur|1.2.6
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
bracket-pair-colorizer-2|Coe|0.2.4
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.15
dart-code|Dar|3.40.0
flutter|Dar|3.40.0
vscode-eslint|dba|2.2.2
jquerysnippets|don|0.0.1
gitlens|eam|12.0.6
vscode-html-css|ecm|1.11.0
vscode-npm-script|eg2|0.3.24
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
auto-rename-tag|for|0.1.10
next-js|fox|0.0.2
kotlin|fwc|0.2.26
vscode-pull-request-github|Git|0.40.0
vscode-graphql|Gra|0.4.4
vue-snippets|hol|1.0.4
rest-client|hum|0.24.6
vscode-react-typescript|inf|1.3.1
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.15.13
spellcheck|Jul|1.1.4
react-native-snippet|jun|0.5.6
StarboundJson|Kyl|0.1.3
node-module-intellisense|lei|1.5.0
vue|liu|0.1.5
quickstart|lol|0.1.0
vscode-language-babel|mgm|0.0.36
vscode-exec-node|mir|0.5.4
data-workspace-vscode|ms-|0.2.0
mssql|ms-|1.14.1
sql-bindings-vscode|ms-|0.0.1
sql-database-projects-vscode|ms-|0.16.1
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
sublime-keybindings|ms-|4.0.10
vscode-typescript-next|ms-|4.7.20220501
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
mysql-inline-decorator|odu|0.0.5
material-icon-theme|PKi|4.16.0
quicktype|qui|12.0.46
java|red|1.5.0
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
js-jsx-snippets|sky|11.0.0
shader|sle|1.1.5
code-spell-checker|str|2.1.11
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vscode-icons|vsc|11.11.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.462
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0

(13 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by mjbvz** [comment]
What language is this for?

Also does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

/needsMoreInfo
