### ISSUE TITLE
"Keyboard Shortcuts" table hardcodes `automaticKeyboardNavigation`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#148536]
I have JK bound to `list.focusDown` and `list.focusUp` provided by vscode-neovim, in other lists, JK works fine but in the "Keyboard Shortcuts" panel, J/K always jumps to commands that start with J/K, which makes JK list navigation unusable.

I have `workbench.list.automaticKeyboardNavigation` set to `false`, but the "Keyboard Shortcuts" panel doesn't respect this setting. I don't know if it's intended or a bug, if it's intended, please add an option to disable keyboard navigation in the "Keyboard Shortcuts" panel.

![image](https://user-images.githubusercontent.com/28700378/166194870-177c3352-54d9-45e4-8840-dfbff68695db.png)
![image](https://user-images.githubusercontent.com/28700378/166194385-b1025d14-be60-41fc-bed6-0de4f1a3c6a3.png)

**Comment by sandy081** [comment]
> but in the "Keyboard Shortcuts" panel, J/K always jumps to commands that start with J/K, which makes JK list navigation unusable.

May I know where are you focused while typing J/K? Are you focused in the search input or on the table?

**Comment by wenfangdu** [comment]
@sandy081 The table.

**Comment by wenfangdu** [comment]
@sandy081 The table, and it's not affected by `"workbench.list.automaticKeyboardNavigation": false`.

**Comment by sandy081** [comment]
It is a workbench table and unsure why it is not working

**Comment by wenfangdu** [comment]
@sandy081 Why did you remove `workbench.list.automaticKeyboardNavigation` in v1.70.0? Now the vscode-neovim explorer list navigation is completely broken.

**Comment by joaomoreno** [comment]
@wenfangdu What do you mean? Can you provide details?

**Comment by wenfangdu** [comment]
@joaomoreno Sorry, I just read https://github.com/microsoft/vscode/pull/152481, seems there's a redesign, never mind :).

**Comment by wenfangdu** [comment]
But it'll be great if you could make [this](https://github.com/microsoft/vscode/issues/158643) happen.
