### ISSUE TITLE
[Bug] "Keyboard Shortcuts" panel doesn't respect `workbench.list.automaticKeyboardNavigation`

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#148537]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.66.2
- OS Version: Windows 10

I have JK bound to `list.focusDown` and `list.focusUp` provided by vscode-neovim, in other lists, JK works fine but in the "Keyboard Shortcuts" panel, J/K always jumps to commands that start with J/K, which makes JK list navigation unusable.

I have `workbench.list.automaticKeyboardNavigation` set to `false`, but the "Keyboard Shortcuts" panel doesn't respect this setting. I don't know if it's intended or a bug, if it's intended, please add an option to disable keyboard navigation in the "Keyboard Shortcuts" panel.

![image](https://user-images.githubusercontent.com/28700378/166194870-177c3352-54d9-45e4-8840-dfbff68695db.png)
![image](https://user-images.githubusercontent.com/28700378/166194385-b1025d14-be60-41fc-bed6-0de4f1a3c6a3.png)

**Comment by sandy081** [comment]
/duplicate

https://github.com/microsoft/vscode/issues/148536
