### ISSUE TITLE
Workspace Template Creation Feature Request.

### ISSUE THREAD

**Issue by 1216892614** [microsoft/vscode#148530]
As a user who writes a variety of languages, relies on plugins, and the computer performance is not very strong. Creating a list of disabled plugins for each workspace separately is a hassle.

Workspace templates mean I can save a `setting.json` file for workspace beforehand and decide whether to apply it when creating the template.

Although I can save and manage these settings manually, it is still a hassle.

## interactions

This differs from the existing workspace mechanism in that it requires additional interactions:

- Save an existing workspace setting file as *a workspace template*
- Select a static file from the template to initialize the current workspace

## implement

Implementing it as a plugin can give this feature a higher degree of freedom.
Implementing this feature with the editor function allows more people who need it to know and use this feature.

**Comment by 1216892614** [comment]
No, I'm ask for a featrue to remember some different settings workspace.
In that case, When I create a new workspace I can select an existing setting to use.

**Comment by 1216892614** [comment]
## How do I set up a workspace before I have this feature:

- File > Add Folder To Workspace >..
- **Find out all the plugin I do not need, Disable(`Workspace`)**

## How would I set up a workspace if I had this feature:

- File > Add Folder To Workspace >..
- Find a template that I set befor and apply it.

**Comment by sandy081** [comment]
I do not think this feature can be done in multi root workspace because extensions enablement is at workspace level not folder level.

**Comment by 1216892614** [comment]
but that's why I ask a issue for this feature, rather than program a plugin.
