### ISSUE TITLE
HC Theme: activity icons give no hover feedback

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148534]
Noticed how every other location gives hover feedback except for the activity icons.

![Recording 2022-05-02 at 08 27 38](https://user-images.githubusercontent.com/900690/166193334-b1a4b5f8-fab5-4e2d-8665-414d3cf98730.gif)

//cc @isidorn

**Comment by daviddossett** [comment]
Yep—known issue on my radar. See: #143533
