### ISSUE TITLE
tsx intellisense wrong with tag function

### ISSUE THREAD

**Issue by SparkElf** [microsoft/vscode#148502]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.66.2
- OS Version:windows11

Steps to Reproduce:
![TYZ3QKN SM$GB245ND9%_D9](https://user-images.githubusercontent.com/58362707/166134123-8a3f4d62-c625-429e-854e-2eff848dcfb2.png)
The project works normally, but the highlight is not correct. It seems that the code highlight of TSX encountered some errors when processing the tag function.

**Comment by mjbvz** [comment]
Please share a self contained example  (as text) that demonstrates the issue

**Comment by SparkElf** [comment]
The error occur when using the mdx bable macro with tsx, i am not sure whether other macro will cause the same crash, i will test it later.
