### ISSUE TITLE
VSCode / Arduino - Cannot find Arduino IDE.

### ISSUE THREAD

**Issue by donniebergh** [microsoft/vscode#148516]
Issue Type: <b>Bug</b>

Per the instauctions I have:

    "arduino.path": "/Applications",
    "arduino.commandPath": "/Contents/MacOS/Arduino",

I'm runnig Mac Monterey 12.3.1

and I get the folowing error:

Cannot find Arduino IDE. Please specify the "arduino.path" in the User Settings. 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (45.11GB free)|
|Process Argv|--crash-reporter-id 2726433a-bf54-4eac-b3db-eb652aa6406f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
doxdocgen|csc|1.4.0
python-preview|don|0.0.4
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
better-cpp-syntax|jef|1.15.13
vsc-python-indent|Kev|1.15.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
autodocstring|njp|0.6.1
python|tht|0.2.3
python-extended-snippets|tus|0.0.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.20
vscode-arduino|vsc|0.4.11
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by IllusionMH** [comment]
/causedByExtension

This error comes from the extension and should be reported there after checking necessary docs and existing issues there.
