### ISSUE TITLE
Is there any API for handling Search Results?

### ISSUE THREAD

**Issue by alefragnani** [Microsoft/vscode#14855]
Hi,

I'm looking for an API that would give access to the search results, more specifically the files and line numbers/characters that _where found_. I didn't find anything like this, but instead, just the `vscode.workspace.findFiles` function.

With this in hand, it would be possible to _mark_ each result for further navigation. (Original request from my [Bookmarks extension](https://github.com/alefragnani/vscode-bookmarks/issues/7))

Thanks in advance

**Comment by Bill-Stewart** [comment]
This would be useful for many things. For example we could answer questions like "is this the last or first search result in the current file?"

**Comment by rebornix** [comment]
For line numbers part, it's dup of https://github.com/Microsoft/vscode/issues/10085 but this one is more generic.

**Comment by sandy081** [comment]
Duplicates #9049

**Comment by alefragnani** [comment]
Sorry about the duplicate. I will follow the other issue.
Thanks :+1:
