### ISSUE TITLE
Support arguments when defining keybindings

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14854]
Allow to pass arguments to commands defined in keybindings.json.

/cc @alexandrudima not sure if you have an existing item for this already?

**Comment by bpasero** [comment]
@alexandrudima currently I am not showing args in IntelliSense so this feature is a bit hard to learn as a new user unless you maybe check the documentation. But I also worry that it is such a corner case that it maybe would be advertised too prominently. Any ideas how to make this discoverable?

![image](https://cloud.githubusercontent.com/assets/900690/19939857/e435a9ec-a12a-11e6-8cef-d74a6b389140.png)

**Comment by alexandrudima** [comment]
@bpasero At one point we will migrate to a single move command. ie. cursorLeft, cursorRight, etc. will all point to one command and pass in different args. It shall then become discoverable :)
