### ISSUE TITLE
Commandline hangs in wsl on Windows 11

### ISSUE THREAD

**Issue by seank-com** [microsoft/vscode#148582]
Issue Type: <b>Bug</b>

1. Install Windows 11
2. Install VS Code
3. Install Windows Terminal
4. Run the following from an elevated command prompt
```
wsl --install
wsl --install -d Ubuntu
```
5. Launch Windows Terminal
6. Open Ubuntu tab and run the following command
```
code .
```
7. Leave VS Code running and Alt-Tab back to Ubuntu tab

Expected:
new prompt to enter additional shell commands

Actual:
shell hung waiting for VS Code to close (like using -w)

Additional Info:
Works as expected from Powershell and Command Prompt tabs in Windows Terminal.

Only repos when VS Code is not already running. For example, if you launch VS Code from Command Prompt, then launch from Ubuntu a second VS Code window will open and Ubuntu shell will work as expected. If you close all VS Code windows and then try to launch again from Ubuntu, the shell will hang like before.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (22.40GB free)|
|Process Argv|. --crash-reporter-id a86fcb05-a404-4742-9c64-16acbfac16b1|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by seank-com** [comment]
Installing the following extension fixed this issue and many more.

Name: Remote - WSL
Id: ms-vscode-remote.remote-wsl
Description: Open any folder in the Windows Subsystem for Linux (WSL) and take advantage of Visual Studio Code's full feature set.
Version: 0.66.2
Publisher: Microsoft
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl

**Comment by meganrogge** [comment]
yes you need that extension to have a good experience with wsl
