### ISSUE TITLE
TS Server keeps getting killed

### ISSUE THREAD

**Issue by jasonpraful** [microsoft/vscode#148509]
Issue Type: <b>Bug</b>

ts version 4.6.4
tried different versions no help

VS Code version: Code 1.66.2 (Universal) (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|75, 52, 29|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv|--crash-reporter-id 48f3b359-7116-4297-b9b1-e289d44fa5a6|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
cucumberautocomplete|ale|2.15.2
vscode-color|ans|0.4.5
github-markdown-preview|bie|0.2.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.2.1
markdown-footnotes|bie|0.0.7
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
shell-syntax|bma|1.0.3
npm-intellisense|chr|1.4.1
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.24
prettier-vscode|esb|9.5.0
code-runner|for|0.11.7
copilot|Git|1.14.5744
todo-tree|Gru|0.0.215
terraform|has|2.22.0
theme-by-language|jsa|1.2.1
solidity|Jua|0.0.139
vscode-cfn-lint|kdd|0.21.0
vscode-codemetrics|kis|1.24.0
image-resizer|luk|0.1.0
vscode-docker|ms-|1.22.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.10.1
vscode-typescript-next|ms-|4.7.20220430
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare-pack|ms-|0.4.0
vscode-react-native|msj|1.9.2
color-highlight|nau|2.5.0
gremlins|nho|0.26.0
deepdark-material|Nim|3.3.0
vetur|oct|0.35.0
material-icon-theme|PKi|4.16.0
heroku-command|pko|0.0.8
vscode-css-peek|pra|4.2.0
java|red|1.5.0
vscode-yaml|red|1.7.0
rust|rus|0.7.8
vs-code-prettier-eslint|rve|3.1.0
trxviewer|sca|1.0.1
swdc-vscode|sof|2.6.30
sonarlint-vscode|Son|3.4.1
vscode-rustfmt|sta|0.1.2
autoimport|ste|1.5.4
pdf|tom|1.2.0
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vscode-backup|Wes|0.0.6
jinja|who|0.0.8
fig|wit|0.0.6
save-as-root|yy0|1.3.9
markdown-all-in-one|yzh|3.4.3
json|Zai|2.0.2
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
