### ISSUE TITLE
Proxy issues when installing MS C# Extension (omnisharp)

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#14852]
- VSCode Version: 1.7.0-insider
- OS Version: Windows Server 2008 R2

Steps to Reproduce:

1. Use Visual Studio Code with Corporate Proxy

settings.json contains:
```
	// The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
	"http.proxy": "http://user:pw@123.123.123.123:8080",
	"http.proxyStrictSSL": false,
```

2. Install C# Extension

Result:

**Proxy works for Installation of Extensions and Update checking. The proxyStrictSSL works.
It seems that the OmniSharp Extensions Network Connection does not use http.proxyStrictSSL.**
_=> unable to verify the first certificate_

The OmniSharp Log shows:

> 
> Installing OmniSharp to C:\Users\MYUSERNAME\.vscode-insiders\extensions\ms-vscode.csharp-1.4.1\out\.omnisharp-desktop
>     Attempting to download omnisharp-1.9-beta14-win-x64-net451.zip

The Debug Console of VSCode shows: 

> 
> /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:121 [Extension Host] Uncaught Exception:  Error: unable to verify the first certificatew.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:121
> /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:121 [Extension Host] Error: unable to verify the first certificate
>     at Error (native)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
>     at emitNone (events.js:86:13)
>     at TLSSocket.emit (events.js:185:7)
>     at TLSSocket._finishInit (_tls_wrap.js:584:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)w.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:121
> /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:126 unable to verify the first certificate: Error: unable to verify the first certificate
>     at Error (native)
>     at TLSSocket.<anonymous> (_tls_wrap.js:1060:38)
>     at emitNone (events.js:86:13)
>     at TLSSocket.emit (events.js:185:7)
>     at TLSSocket._finishInit (_tls_wrap.js:584:8)
>     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:416:38)e.onUnexpectedError @ /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:126
> /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:121 [Extension Host] Uncaught Exception:  Error: socket hang upw.logExtensionHostMessage @ /C:/Program Files (x86)/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:121

**Comment by rebornix** [comment]
It's an OmniSharp issue and it's already logged there https://github.com/OmniSharp/omnisharp-vscode/issues/579

**Comment by FloMaetschke** [comment]
Thx, for the linked temporary workaround. I can now use omnisharp.
