### ISSUE TITLE
please add auto save with version system on the basis of time

### ISSUE THREAD

**Issue by itneshkumar** [microsoft/vscode#148599]
Issue Type: <b>Feature Request</b>

If our code will save at a particular time in the form of history version . Then code recovery easy . It would be possible . vs code provide auto saving mode.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.13.0-40-generic snap
Restricted Mode: No

**Comment by bpasero** [comment]
Isnt this https://code.visualstudio.com/updates/v1_66#_local-history ?
