### ISSUE TITLE
[loc][Query][VSCode] Please clarify "Language"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#14857]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Invalid value in `contributes.{0}.embeddedLanguages`. Must be an object map from scope name to language. Provided value: {1}
A map of scope name to language id if this grammar contains embedded languages.

File Name:
src\vs\editor\node\textMate\TMSyntax.nls.resx

Resource ID:
".resx", 0; "invalid.embeddedLanguages"
".resx", 0; "vscode.extension.contributes.grammars.embeddedLanguages"

Query:
Does Language refer to programming language or English, Spanish, etc.?	Cristina Carrasco	11/2/2016 11:04:11 AM

**Comment by rebornix** [comment]
Assign to @aeschli first by searching and git blame :)

**Comment by alexandrudima** [comment]
In that context, language refers to a programming language identifier. 

It should get a similar translation to other usages in that file, such as:

```
"Unknown language in `contributes.{0}.language`. Provided value: {1}"
"A map of scope name to language id if this grammar contains embedded languages"
"Language identifier for which this syntax is contributed to."
```
