### ISSUE TITLE
Currently selected kernel not showing as the first one in kernel picker

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#148584]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/876920/166313861-566c3640-97d4-4d0b-bdda-806cf6f65fa3.png">

It feels weird that the currently selected kernel is not showing as the first kernel in the list. In the screenshot above it looks like suggesting the pyodide kernel over the currently used one.

**Comment by roblourens** [comment]
Should there be a new "Currently selected" section at the top?

**Comment by roblourens** [comment]
I think we can close this in favor of the bigger kernel picker work
