### ISSUE TITLE
Open vscode and pop up win7 window for a moment

### ISSUE THREAD

**Issue by zhaozhenyu1111** [microsoft/vscode#148500]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: windows11 22610.1

Steps to Reproduce:

1.Open vscode and pop up win7 window for a moment

I tried the first few versions and this doesn't happen
![vscode_open](https://user-images.githubusercontent.com/72144628/166131802-6b47598f-e731-42a8-a699-91c1725b5cce.gif)

**Comment by hello-smile6** [comment]
> Does this issue occur when all extensions are disabled?: Yes
> 
> * VS Code Version: 1.66.2
> * OS Version: windows11 22610.1
> 
> Steps to Reproduce:
> 
> 1.Open vscode and pop up win7 window for a moment
> 
> I tried the first few versions and this doesn't happen ![vscode_open](https://user-images.githubusercontent.com/72144628/166131802-6b47598f-e731-42a8-a699-91c1725b5cce.gif)

This also seems to affect other programs with custom window bars, including Microsoft Edge. Could it be an issue with Windows?

**Comment by zhaozhenyu1111** [comment]
My edge and chrome are not like this, and vscode is only like this in the last few versions。

**Comment by hello-smile6** [comment]
> My edge and chrome are not like this, and vscode is only like this in the last few versions。

Microsoft edge does it when you run several (1 per CPU core) infinite loop executables at high priority, but not normally. (self-induced denial-of-service isn't a normal use case, so I guess it doesn't matter much) . I believe I saw QEMU do it once, though. (I dragged the window off of it)

**Comment by zhaozhenyu1111** [comment]
But I use the v1.58 version and it is normal, I guess it is the problem of the new version.

**Comment by zhaozhenyu1111** [comment]
I just installed the latest version of vscode on another computer (windows11 22610) and it is the same as me.

**Comment by gjsjohnmurray** [comment]
Is this #147864?
