### ISSUE TITLE
System crashes while running on AWS UBUNTU host

### ISSUE THREAD

**Issue by dogusdeniz** [microsoft/vscode#148526]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.66.2`

when i click on a .js file the code intelligence starts automatically and then the system gets no response from the remote connection. the remote connection doesn't react like it's in an infinite loop and I have to kill the intance in aws.

I wish I could get a picture of it but when the website crashes I'm scared and immediately disable the "vscode.typescript-language-features" plugin. :( please have a clue of deleting this.

**Comment by mjbvz** [comment]
Can you share a project that causes this issue?

Also does it happen if you open the same project locally?

**Comment by dogusdeniz** [comment]
I use the vscode remote connection tool to integrate the strapi project into the server.

and the connection is successful. all features are working.
but

if i enter a .js .ts .vue or .d.ts file the javascript/typescript code intelligence works. (I think it recognizes the codes and tries to fix it)

When this happens, the instance freezes if I don't close vscode right away.

I enter aws and wait for 10 minutes with the force close option. (processes do not stop inside)

Worst case scenario, I need to terminate instance. which makes me lose 10 hours in 1 day.


and now i have only one solution room is to disable all plugins and vscode features and make remote connection.

**Comment by mjbvz** [comment]
Did you get a change to test locally too? AlsocCan you try sharing a project that causes this issue?

**Comment by dogusdeniz** [comment]
when i run locally the aws instance works fine. whenever i make a remote connection with vscode there is no problem at first but when i open a remote file with vscode the aws instance crashes (freezes).

If I can learn to debug vscode maybe I can find a solution to this problem myself. But then this came to my mind:
if I run 'npm install' on an aws instance that I'm connected to via vscode, the aws instance starts downloading the packages.
1 - ram may be full before download is complete
2 - vscode remote connection plugin may have entered an infinite loop
3 - the aws instance may have run out of cpu limit.
4 - typescript and javascript intelligence might be killing ssh (no idea how)

I can't share a project sample because it's covered by a commercial confidentiality agreement.

Thanks for your interest, I will try deploy with docker instead of remote connection. We can close these issues.

**Comment by mjbvz** [comment]
Ok, closing based on this feedback

If you are still running into issues, please try putting together a minimal project that demonstrates that issue so we can investigate this
