### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Unknown Error occured)

### ISSUE THREAD

**Issue by pierrelouisbescond** [microsoft/vscode#148511]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

_Note: This error message is the same for different Data Scientists / Data Engineers working in the same team but with possible different laptops and Windows versions, extensions, which makes us think the switch from 1.65.2 to 1.66.2 is causing this issue._

When updating VS Code from 1.65.2 to 1.66.2, VS Code is no longer able to connect to instances in Azure Machine Learning Studio.

Error messages are as follows:

```
Failed to connect to the remote extension host server (Error: Unknown Error occurred)

request to https://***********.francecentral.instances.azureml.ms/api/terminals?****** failed, reason: certificate signature failure

[Extension Host] Unhandled Error: ENOPRO: No file system provider found for resource 'vscode-remote://amlext***/home/azureuser/***'    at p.withProvider (vscode-file://vscode-app/c:/Users/*******/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:27776)    at processTicksAndRejections (node:internal/process/task_queues:96:5)    at async p.exists (vscode-file://vscode-app/c:/Users/********/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:610:30371)    at async Promise.all (index 0)    at async vscode-file://vscode-app/c:/Users/********/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2110:2110
D @ console.ts:137
```

![vs_code_1 66 2_failure](https://user-images.githubusercontent.com/65066394/166405598-3353dadd-9cb3-4777-9ca1-33bed3b9e74d.png)

**Comment by roblourens** [comment]
Please file this on https://github.com/microsoft/vscode-tools-for-ai/issues
