### ISSUE TITLE
feature request: up arrow go to bottom of quick fix ⌘. menu

### ISSUE THREAD

**Issue by MarkPieszak** [microsoft/vscode#148566]
Currently, when opening the Quick Fix menu via **`⌘.`**:

**Current Behavior:**

It automatically has the first item at the top of the menu **selected**, and you are _unable_ to push **Up Arrow** to get to the _bottom_ of the list.

> This would be extremely helpful in situations like eslint/prettier when the "fix with prettier" (or similar option) is always at the bottom of the list.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/2574412/166265386-baa73338-9931-42c5-892c-632471d22afd.png">

**Desired Behavior:**

To push the up arrow on the Quick Fix menu, and it takes you to the bottom of the list.

---

This desired behavior actually already exists when doing a `right click` somewhere (as nothing is selected), and you are able to push **Up Arrrow**, and it takes you to the bottom of the list.

Fantastic work on VSCode as always, this is a super minor thing - but I think it would be fantastic for an even better DX <3

**Comment by justschen** [comment]
@MarkPieszak I think this should be resolved (in both the original Quick Fix Menu and with the new Code Action Widget which will replace this menu - see https://github.com/microsoft/vscode/issues/152913)

Just one thing though - @mjbvz can you confirm some behavior on MacOS vs Windows?

When hitting `Ctrl + .` on Windows, the Quick Fix menu will actually include the `Learn more about TS/JS Refactoring` option. When opening the Quick Fix menu from an error (View Problem) and hitting the text that says `Quick Fix...`, the menu won't include the `Learn more....` option.

Is this the same with `⌘ + . ` on Mac? This means that hitting the up arrow works, but would be an option that most users wouldn't intend to click on.

**Comment by mjbvz** [comment]
@justschen Yes that's the same behavior on macOS too
