### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by RenRenj** [microsoft/vscode#148570]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.npm generate run
2.Command not found

**Comment by gjsjohnmurray** [comment]
Have you installed npm?

**Comment by RenRenj** [comment]
No I have not installed Npm

**Comment by gjsjohnmurray** [comment]
Therefore when you ask to run the npm command you are told "command not found".

**Comment by RenRenj** [comment]
Yes

**Comment by roblourens** [comment]
I guess if you are trying to run an npm command you need to install node/npm first. Give more details if you think this is a vscode issue.
