### ISSUE TITLE
Add custom panels in terminal VS Code Extension

### ISSUE THREAD

**Issue by subhikaran** [microsoft/vscode#148686]
![image](https://user-images.githubusercontent.com/50451692/166635397-581f6713-f383-4c07-87f4-4eae6c2227a0.png)
I am trying to add a custom webview panel in the "terminal" vs code. Could you please help me with that?

**Comment by sbatten** [comment]
You'll need to add the view to a custom view container that is registered to the panel, docs here https://code.visualstudio.com/api/extension-guides/tree-view#view-container
