### ISSUE TITLE
Camel case navigation in renaming symbol

### ISSUE THREAD

**Issue by rasulomaroff** [microsoft/vscode#148647]
There's a possibility to move the caret using camel case in the editor (cursorWordPartRight and cursorWordPartLeft), but I can't see the same opportunity while renaming symbol, but the interesting thing is that the usual navigation by word (cursorWordRight and cursorWordLeft) works when renaming symbol. Is this a bug? I believe it should work the same in renaming symbol as it does in the editor.

**Comment by jrieken** [comment]
This is a duplicate. Unfortunately, I don't recall the exact issue number nor its title :flushed: Anyways, searching for issues with the same labels will likely help you :point_right:
https://github.com/microsoft/vscode/issues?utf8=✓&q=is%3Aopen+label%3A"rename"

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/53666
