### ISSUE TITLE
Cannot use up/down arrows to access command history in Azure Cloud Shell for PowerShell

### ISSUE THREAD

**Issue by pisees** [microsoft/vscode#148657]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Windows 11 (21H2)

Steps to Reproduce:

1. Chose Azure Cloud Shell (PowerShell) terminal
2. Enter commands
3. Try to navigate command history with up/down errors

See that this was opened previously, but it is still an issue: https://github.com/Microsoft/vscode/issues/70418

**Comment by meganrogge** [comment]
Please file an issue with that extension
