### ISSUE TITLE
CSS Language Features format result breaks syntax and throws errors

### ISSUE THREAD

**Issue by ntnyq** [microsoft/vscode#148684]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Darwin x64 18.2.0

Steps to Reproduce:

1. Copy snippets below and enable format on save with CSS Language Features
2. Save

```css
quote {
  quotes: "'" "'";
}
```
Refs:

- [MDN quotes - values](https://developer.mozilla.org/zh-CN/docs/Web/CSS/quotes#values)

Then VS Code throws two errors and the result breaks the syntax.

**Comment by aeschli** [comment]
`quotes: "'""'";` is actually valid CSS. In 1.67 I fixed the CSS validator to no longer report an error.

However, should the CSS formatter remove that space? I agree it shouldn't. I created https://github.com/beautify-web/js-beautify/issues/2051 against JS Beautify which we use as underlying formatter.
