### ISSUE TITLE
Unable launch VSCode on Linux Fedora 23

### ISSUE THREAD

**Issue by NTMan** [Microsoft/vscode#1486]
![screenshot from 2015-12-19 22-54-39](https://cloud.githubusercontent.com/assets/200750/11914765/f75fa04e-a6a9-11e5-9622-24deb5fa50ce.png)

**Comment by bgse** [comment]
Maybe I'm off the mark, but could you be running into this issue?

http://stackoverflow.com/questions/22475849/node-js-error-enospc

also look at answer here:

http://stackoverflow.com/questions/16748737/grunt-watch-error-waiting-fatal-error-watch-enospc/31926452#31926452

**Comment by bpasero** [comment]
See https://code.visualstudio.com/Docs/supporting/FAQ#_linux-error-enospc

**Comment by NTMan** [comment]
Ok, increasing `fs.inotify.max_user_watches` helps.
But very strange that Atom which based on Electron too not has such problem.
