### ISSUE TITLE
Can't Save

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#14864]
- VSCode Version: 1.6.1
- OS Version: Win 10 Pro

I was working w/ Code all day today and all of a sudden, I can't save a file. I don't get a visual error, and the app seems completely fine in every other aspect. But the 'dirty' indicator won't go away and the file never actually saves. 

I opened up dev tools and see this:

C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:1716 [1] - Grammar is in an endless loop - Grammar pushed & popped a rule without advancingscanNext @ C:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\vscode-textmate\release\main.js:1716

**Comment by cfjedimaster** [comment]
Actually I'm wrong. Menu items still work, but I can't select any file.

**Comment by cfjedimaster** [comment]
I went to Task Manager to try to kill Code. It prompted me to save again so I figured, why not. I got multiple errors then. They include:

Error from the extension host: channel closed
Extension host terminated unexpectedly. Please reload the window to recover.
Error from the extension host: write EPIPE

**Comment by cfjedimaster** [comment]
After killing Code and restarting it, I can recreate the issue. I am editing an HTML file. I had 2 form fields. I added value="stuff" to them and Code breaks.

**Comment by cfjedimaster** [comment]
Nope, not related to that line. Any edit, even adding a new line, causes the issue. No errors show in devtools.

**Comment by cfjedimaster** [comment]
And it's not HTML related at all. Even a JS file has the same behavior now. Wow - I'm at a loss now.

**Comment by cfjedimaster** [comment]
Wow, I rebooted, and I still can't save files. :(

**Comment by cfjedimaster** [comment]
Ah no - sorry - it was just a bit slow. So yeah, rebooting did help.

**Comment by cfjedimaster** [comment]
And I'm back to it being broken. :( I went back to my html file, added those value="..." things again, and I managed to make it break. Nothing in console. But can't save.

**Comment by cfjedimaster** [comment]
So I had Code open and was ignoring it while on a phone call. The file was in it's dirty state, not being able to save. While I was on the phone, the UI popped up two issues:

Error from the extension host: channel closed
Extension host terminated unexpectedly. Please reload the window to recover.

Devtools had 3 errors:

messageService.ts:128 Extension host terminated unexpectedly. Please reload the window to recover.e.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ threadService.ts:267emitTwo @ events.js:106emit @ events.js:191ChildProcess._handle.onexit @ internal/child_process.js:215

threadService.ts:271 Extension host terminated unexpectedly. Code:  3  Signal:  null(anonymous function) @ threadService.ts:271emitTwo @ events.js:106emit @ events.js:191ChildProcess._handle.onexit @ internal/child_process.js:215

messageService.ts:128 Error from the extension host: channel closede.doShow @ messageService.ts:128e.show @ messageService.ts:107(anonymous function) @ threadService.ts:257emitOne @ events.js:96emit @ events.js:188target.send @ internal/child_process.js:544a.postMessage @ threadService.ts:322(anonymous function) @ threadService.ts:66t @ ipcRemoteCom.ts:257_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by cfjedimaster** [comment]
So I disabled one extension at a time and it seems to have been the spellchecker extension. I'd like to post this bug on their repo - let me figure out how to do that before I close this one.

**Comment by rebornix** [comment]
ppl ran into similar issues in #14436 and @jrieken might be interested in @cfjedimaster 's repro steps.

**Comment by cfjedimaster** [comment]
This issue was moved to swyphcosmo/vscode-spellchecker#15
