### ISSUE TITLE
1.66 update package not available in snap

### ISSUE THREAD

**Issue by Kbre** [microsoft/vscode#148631]
Issue Type: <b>Bug</b>

Hi, I am using Visual Studio Code in Ubuntu installed as snap. It continues to tell me that a new version is available. I confirmed in the web the lastest version is 1.66.2 but the current snap version my system has is 1.65.0

I’ve tried 'sudo snap refresh code' and it says: 'snap "code" has no updates available'

The snap site shows the last version as “dfd34e82” published 12 April 2022 but I dont see the relationship with 1.6x versions...

VS Code version: Code 1.65.0 (b5205cc8eb4fbaa726835538cd82372cc0222d43, 2022-03-02T11:12:36.248Z)
OS version: Linux x64 5.15.0-27-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (1 x 2419)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|4, 1, 0|
|Memory (System)|2.91GB (0.07GB free)|
|Process Argv|--unity-launch --crash-reporter-id 9a1d4f59-cd8f-4d7e-995c-baf85dddbfab|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>

**Comment by joaomoreno** [comment]
`dfd34e82` is the commit ID of the 1.66.2 build.

I suggest you reach out to the Snap Store, since it seems like your snap daemon simply isn't updating properly.
