### ISSUE TITLE
Show broken extensions in the UI

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#148646]
In web, it is quite often that a side loaded extension is no longer be accessible or the server hosting the extension is down. It is helpful for the user to see these extensions and uninstall them if they no longer need them.

**Comment by rzhao271** [comment]
After uninstalling the extension, I still get an error message:

![luna-ex](https://user-images.githubusercontent.com/7199958/171472876-81c40124-edc6-4cdf-a20e-c2c61c078ea3.PNG)

**Comment by sandy081** [comment]
Extracted above comment to https://github.com/microsoft/vscode/issues/151193
