### ISSUE TITLE
Allow extensions to contribute to issue body when using Issue Reporter

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#148675]
When an extension, say Python, is selected in the report issue dropdown:
<img src="https://user-images.githubusercontent.com/13199757/166593282-fff161a5-9f69-427e-bfd7-96d5fabaf06a.png" width=400 />

"Steps to reproduce" should be auto-filled with extension specific templates if available.
<img src="https://user-images.githubusercontent.com/13199757/166595185-c3ff1e19-f898-49ca-a3a1-21ac8861dd19.png" width=400 />

Right now the workaround is that every extension has its own report issue command, which isn't always used when reporting issues (users rely on the general `Help: Report Issue` instead): 
<img src="https://user-images.githubusercontent.com/13199757/166598464-68f9e951-e464-49c9-9882-a1088a07f52a.png" width=400 />

**Comment by TylerLeonhardt** [comment]
related: https://github.com/microsoft/vscode/issues/46726

**Comment by karrtikr** [comment]
An easy solution for this would be to provide a hook when an extension is selected in the dropdown, which then launches the extension specific report command. This can be specified in 'package.json'.

**Comment by bwateratmsft** [comment]
For Docker and several Azure extensions, we'd like to use the built-in issue reporter but also attach some additional data (error details, call stack, etc.), while _still_ requiring users to fill something into the repro steps field.
