### ISSUE TITLE
Get error after trying turn on Settings Sync with GitHub

### ISSUE THREAD

**Issue by pavelsyunev** [microsoft/vscode#148669]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Windows 11

Steps to Reproduce:

1. vscode was installed on PC and sync worked correctly;
2. Windows User folder was renamed and vscode was uninstalled incorrectly, not with "uninstall", just by deleting folder;
3. Installed vscode again and turn on Settings Sync with GitHub;
4. Get error - Error while turning on Settings Sync. Cancelled

Log (Setting sync)
[2022-05-03 18:18:20.055] [settingssync] [info] Using settings sync service https://vscode-sync.trafficmanager.net/
[2022-05-03 18:18:20.055] [settingssync] [info] Auto Sync is disabled.

**Comment by pavelsyunev** [comment]
Today I tried new version - 1.67.0, but same problem:
![17-08-44](https://user-images.githubusercontent.com/31213600/167027566-bce45591-326a-46ac-aecb-d58248af512d.gif)
[Info  - 21:18:25.467] Reading sessions from keychain...
[Info  - 21:18:25.535] Getting sessions for user:email...
[Info  - 21:18:25.536] Getting sessions for all scopes...
[Info  - 21:18:25.536] Got 0 sessions for user:email...
[Info  - 21:18:25.536] Got 0 sessions for ...
[Info  - 21:18:26.877] Getting sessions for all scopes...
[Info  - 21:18:26.877] Got 0 sessions for ...
[Info  - 21:18:28.908] Getting sessions for user:email...
[Info  - 21:18:28.908] Got 0 sessions for user:email...
[Info  - 21:18:29.967] Logging in for the following scopes: user:email
[Info  - 21:18:29.972] Trying without local server... (user:email)
[Error  - 21:19:29.990] Cancelled
[Info  - 21:26:50.946] Getting sessions for all scopes...
[Info  - 21:26:50.946] Got 0 sessions for ...
[Info  - 21:26:53.208] Getting sessions for user:email...
[Info  - 21:26:53.208] Got 0 sessions for user:email...
[Info  - 21:26:54.575] Logging in for the following scopes: user:email
[Info  - 21:26:54.578] Trying without local server... (user:email)
[Error  - 21:27:54.595] Cancelled
[Error  - 21:27:54.630] Error: Cancelled

**Comment by pavelsyunev** [comment]
Finally sync settings start working with  https://github.com/login/device and 6 dig code

**Comment by TylerLeonhardt** [comment]
@pavelsyunev in your video above, is your browser opening at all? I'm curious to know what you see on that side... if anything
