### ISSUE TITLE
Support creating binary files in a WorkspaceEdit

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#148667]
## Feature Request
Add support for setting the contents of files created by workspace edits

My proposed would be to add a `contents` option to `createFile`:

```ts
createFile(uri: Uri, options?: { overwrite?: boolean; ignoreIfExists?: boolean; contents?: UInt8Array }, metadata?: WorkspaceEditEntryMetadata): void;
```

## Use case
For #147481, we want to support copying images from desktop into vscode.dev with drag and drop. Right now we have to use the `fs` apis to create the image file

Using a workspace edit would let us express the entire operation in a single `WorkspaceEdit`, which will play more nicely with undo/redo

**Comment by mjbvz** [comment]
Looks like support for this may already exist internally: https://github.com/microsoft/vscode/blob/0656d21d11910e1b241d7d6c52761d89c0ba23a4/src/vs/workbench/contrib/bulkEdit/browser/bulkFileEdits.ts#L150

However getting a `UInt8Array` of new file data from the extension host to the main process may be tricky. We can only efficiently serialize a `UInt8Array` if it is a top level argument to an RPC call or if the entire object is wrapped in a `SerializableObjectWithBuffers` (which has a perf cost). Open to ideas on how to handle this

**Comment by jrieken** [comment]
@mjbvz work started here: https://github.com/microsoft/vscode/pull/160193. I didn't bother with `SerializableObjectWithBuffers` or hoisting the data to the top but instead it uses quick and dirty base64 encoding. I'd suggest we go with that and see how it works out over time.
