### ISSUE TITLE
daprd task doesn's start correctly when specifying a logLevel

### ISSUE THREAD

**Issue by francotiveron** [microsoft/vscode#148681]
Issue Type: <b>Bug</b>

- create a debug configuration that works
- add "logLevel": "error"
- now the task doesn't start anymore

VS Code version: Code - Insiders 1.67.0-insider (3159d61ccf5150764f7742f098d76872e3114dcb, 2022-05-04T00:06:04.293Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (39.99GB free)|
|Process Argv|--crash-reporter-id 069701b0-35c0-493b-b96d-091de8b8f40e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
k8s-snippets|dog|0.1.2
gitlens|eam|12.0.6
vscode-open-in-application|fab|1.0.6
flux|inf|1.0.4
Ionide-fsharp|Ion|6.0.2
file-downloader|min|1.0.12
mindaro|min|1.0.120220125
azure-pipelines|ms-|1.204.0
vscode-azureappservice|ms-|0.23.3
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.6.1
vscode-cosmosdb|ms-|0.18.1
vscode-dapr|ms-|0.6.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
vscode-dotnet-runtime|ms-|1.5.0
vscode-aks-tools|ms-|0.0.17
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1001252103
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.233.1
remote-wsl|ms-|0.66.2
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
powershell-preview|ms-|2022.5.0
vscode-node-azure-pack|ms-|0.3.0
azurerm-vscode-tools|msa|0.15.6
vscode-yaml|red|1.7.0
azure-event-hub-explorer|Sum|0.1.1
large-file|yy0|1.0.12
k8s-snippets|yzd|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebugcf:30475217
vscaac:30438845
vsclangdf:30480126

```

</details>

**Comment by roblourens** [comment]
Can you give more specific steps? What type of debug configuration?

**Comment by francotiveron** [comment]
https://github.com/microsoft/vscode/issues/148682

**Comment by roblourens** [comment]
How is this issue different from https://github.com/microsoft/vscode/issues/148682? This would be an issue with the extension that provides that task definition

**Comment by francotiveron** [comment]
@roblourens https://github.com/microsoft/vscode/issues/148682 is about the wording ("warn" vs "warning"), this is about the daprd task being stuck when logLevel is specified.
They are two different issue even if related

**Comment by roblourens** [comment]
Ok. I think this would be an issue with the extension that provides this task definition.
