### ISSUE TITLE
.bug

### ISSUE THREAD

**Issue by N000131509** [microsoft/vscode#148676]
Issue Type: <b>Bug</b>

*Context*
- Managed Dependencies: on
- Cloud SDK Version: 384.0.0
- Skaffold Version: v1.38.0
- Minikube Version: 1.25.2

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.18GB free)|
|Process Argv|--crash-reporter-id e30c18f9-d594-4435-a534-6d5e05d7dba2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (105)</summary>

Extension|Author (truncated)|Version
---|---|---
1tbs-editorconfig-generator|Alp|0.1.2
sculptui-vscode|ard|0.7.1
python-six|asc|2022.5.0
bala-bks-docker-snippets|bal|0.1.3
cake-vscode|cak|2.0.0
npm-intellisense|chr|1.4.1
doxdocgen|csc|1.4.0
plcc-plugin|dav|0.12.17
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
phptools-vscode|DEV|1.9.9277
githistory|don|0.6.19
javadebugger|don|0.1.5
xml|Dot|2.5.1
vscode-docker-syntax|dun|0.1.5
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.24
vscode-react-native-kit|emi|0.0.1
open-lnk|Enk|0.0.1
vscode-rtf-readme|env|0.2.16
vscode-firefox-debug|fir|2.9.6
rtl-quick-debug|fit|2.0.0
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
c-cpp-runner|fra|3.3.9
docker-run|geo|1.1.0
codespaces|Git|1.8.0
vscode-pull-request-github|Git|0.40.0
go|gol|0.33.0
go-nightly|gol|2022.5.313
cloudcode|goo|1.18.1
gc-excelviewer|Gra|4.2.54
vscode-test-explorer|hbe|2.21.1
ibmcloud-account|IBM|1.0.6
ibm-blockchain-platform|IBM|2.0.8
powershell-universal|iro|2.10.1
powershellprotools|iro|2022.4.3
macro-executor|iSo|0.3.3
vscode-edit-csv|jan|0.6.8
csharpextensions|jch|1.3.1
better-cpp-syntax|jef|1.15.13
docomment|k--|0.1.30
php-xdebug|kak|0.0.7
ts-debug|kak|0.0.6
csharpextensions|kre|1.7.0
dockerfile-validator|mar|1.2.0
start-git-bash|McC|1.2.1
rainbow-csv|mec|2.3.0
vscode-dapr|ms-|0.6.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
vscode-edge-devtools|ms-|1.4.8
vscode-kubernetes-tools|ms-|1.3.7
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
azure-account|ms-|0.10.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
js-debug-nightly|ms-|2022.4.2217
mono-debug|ms-|0.16.2
powershell|ms-|2021.12.0
powershell-preview|ms-|2022.5.0
test-adapter-converter|ms-|0.1.6
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.9.2
vscode-react-native-preview|msj|2022.4.1421
oracleguidconverter|pik|0.0.8
platformio-ide|pla|2.4.3
vscode-hack|pra|2.13.0
vscode-data-preview|Ran|2.3.0
java|red|1.5.0
vscode-yaml|red|1.7.0
LiveServer|rit|5.7.5
bash-debug|rog|0.3.9
salesforcedx-vscode-apex|sal|54.9.0
salesforcedx-vscode-apex-debugger|sal|54.9.0
salesforcedx-vscode-apex-replay-debugger|sal|54.9.0
salesforcedx-vscode-core|sal|54.9.0
vscode-zipexplorer|sle|0.3.1
vscode-docker-ws|tii|0.5.0
run-in-powershell|tob|1.1.1
cmake|twx|0.0.17
usql-vscode-ext|usq|0.2.15
c-cpp-flag-debugging|uts|0.0.1
vscode-lldb|vad|1.7.0
vscodeintellicode|Vis|1.2.20
vscode-arduino|vsc|0.4.11
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
quokka-vscode|Wal|1.0.462
debug|web|0.26.0
eno|Wsc|2.3.53
php-debug|xde|1.26.1
targetframeworksswitcher|yam|1.0.3
vsc-docker|Zim|0.34.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

What is the problem?
