### ISSUE TITLE
PageUp / PageDown keys do not reach tmux

### ISSUE THREAD

**Issue by magdumnikhil** [microsoft/vscode#148685]
Issue Type: <b>Bug</b>

Configure tmux to cycle through windows with key "Ctrl + PageUp", "Ctrl + PageDown"

```
bind -n C-PgDn prev
bind -n C-PgUp next
```

Launch tmux, create multiple windows
Issue the above key-combinations

Output: Nothing happens with Ctrl + PageUp. Ctrl-PageDown just prints the "~" character on the terminal.

Any default/user-defined keyboard shortcuts involving PageUp/PageDown related to the terminal are removed.

settings and keybindings are attached

The keyboard is set to "US QWERTY"

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-107-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.21GB free)|
|Process Argv|--crash-reporter-id 85c323a1-5d98-45e5-8818-74519d9e3b95|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 10.40.199.111|
|OS|Linux x64 5.4.0-107-generic|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 3600)|
|Memory (System)|62.70GB (7.58GB free)|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.5.0
docs-view|bie|0.0.10
arm|dan|1.7.4
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
linkerscript|Zix|1.0.2
atlascode|atl|2.10.12
codealignment-vscode|cpm|2.0.19
doxdocgen|csc|1.4.0
gitlens|eam|12.0.6
todo-tree|Gru|0.0.215
cpptools|ms-|1.9.8
hexeditor|ms-|1.9.6
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
vscode-yaml|red|1.7.0
tmlanguage|Tog|0.9.0

(1 theme extension excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

[settings.txt](https://github.com/microsoft/vscode/files/8618340/settings.txt)
[keybindings.txt](https://github.com/microsoft/vscode/files/8618341/keybindings.txt)

**Comment by Tyriar** [comment]
With these keybindings:

```
{ "key": "ctrl+pagedown",         "command": "-workbench.action.nextEditor" },
{ "key": "ctrl+pageup",           "command": "-workbench.action.previousEditor" },
{ "key": "ctrl+pagedown",         "command": "-workbench.action.terminal.focusNext",
    "when": "terminalFocus && terminalHasBeenCreated && !terminalEditorFocus || terminalFocus && terminalProcessSupported && !terminalEditorFocus" },
{ "key": "ctrl+pageup",           "command": "-workbench.action.terminal.focusPrevious",
    "when": "terminalFocus && terminalHasBeenCreated && !terminalEditorFocus || terminalFocus && terminalProcessSupported && !terminalEditorFocus" },
```

ctrl+pageup/pagedown do get sent to the shell, but end up getting send using the same sequence as without ctrl.

```
pageup:        xterm.js: sending data "[5~" (4) [27, 91, 53, 126]
ctrl+pageup:   xterm.js: sending data "[5~" (4) [27, 91, 53, 126]
pagedown:      xterm.js: sending data "[6~" (4) [27, 91, 54, 126]
ctrl+pagedown: xterm.js: sending data "[6~" (4) [27, 91, 54, 126]
```

**Comment by magdumnikhil** [comment]
Is any workaround available?

**Comment by Tyriar** [comment]
Yes, you can use `workbench.action.terminal.sendSequence` to send whatever you want, example keybinding:

```
{ "key": "ctrl+backspace",
  "command": "workbench.action.terminal.sendSequence",
  "when": "terminalFocus",
  "args": {"text":"\u0017"} }
```

You'd need to figure out the right sequence to send though, I'm not sure currently.

**Comment by magdumnikhil** [comment]
Thanks for the suggestion. The following entries in the keybindings.json helped.
```
{
	"key": "ctrl+pageup",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u001b\u005b\u0035\u003b\u0035\u007e"},
	"when": "terminalFocus"
},
{
	"key": "ctrl+pagedown",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u001b\u005b\u0036\u003b\u0035\u007e"},
	"when": "terminalFocus"
}
```

In case anyone else lands here, the following is the pyhon3 code to get the sequence
```
key = input()

print("".join("\\u{:04x}".format(ord(k)) for k in key))
```

**Comment by Tyriar** [comment]
Thanks for looking up the sequence, I put a fix out upstream https://github.com/xtermjs/xterm.js/pull/3761

**Comment by Tyriar** [comment]
Fixed via https://github.com/microsoft/vscode/pull/148923

**Comment by magdumnikhil** [comment]
Thanks for the quick fix.
I see a similar issue with alt+arrow keys.

```
{
	"key": "alt+left",
	"command": "-workbench.action.terminal.focusPreviousPane",
	"when": "terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported"
},
{
	"key": "alt+right",
	"command": "-workbench.action.terminal.focusNextPane",
	"when": "terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported"
},
{
	"key": "alt+up",
	"command": "-workbench.action.terminal.focusPreviousPane",
	"when": "terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported"
},
{
	"key": "alt+down",
	"command": "-workbench.action.terminal.focusNextPane",
	"when": "terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported"
},
{
	"key": "alt+right",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u001b\u005b\u0031\u003b\u0033\u0043"},
	"when": "terminalFocus"
},
{
	"key": "alt+left",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u001b\u005b\u0031\u003b\u0035\u0044"},
	"when": "terminalFocus"
},
{
	"key": "alt+up",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u001b\u005b\u0031\u003b\u0035\u0041"},
	"when": "terminalFocus"
},
{
	"key": "alt+down",
	"command": "workbench.action.terminal.sendSequence",
	"args": { "text": "\u001b\u005b\u0031\u003b\u0035\u0042"},
	"when": "terminalFocus"
}
```

But even after sending the specific sequence, required actions in tmux are not triggered. Only alt+right works.
If you would like, I'll create another bug.

**Comment by roblourens** [comment]
I was trying to set this up in iTerm at first to compare, but was confused because it just doesn't work in iTerm 😁  works great in vscode
