### ISSUE TITLE
Setting default editor for markdown files not persisting

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#148643]
https://user-images.githubusercontent.com/35271042/166488843-1c9066b2-dd9c-44f4-9474-c7c7adc9aa6e.mp4

Steps to Reproduce:

1. Install [Go notebook extension](https://marketplace.visualstudio.com/items?itemName=gobookdev.gobook)
2. open markdown file
3. see the notebook editor open, close
4. right-click on markdown file and open with
5. change default for markdown files to text editor
6. re-open file
7. :bug: notebook editor still opens

Version: 1.67.0-insider (Universal)
Commit: 7295846887c3a4bf911ba2bd1e64971321cbbb07
Date: 2022-05-03T12:37:53.700Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

**Comment by lramos15** [comment]
According to the go notebook readme it has been deprecated in favor of codebook. So I installed codebook and tried the flow and I cannot reproduce. Give it a shot and let me know.

![Recording 2022-05-06 at 11 38 54](https://user-images.githubusercontent.com/4544166/167166132-84de2162-6e83-4492-9416-0156074d6540.gif)
