### ISSUE TITLE
Markdown "open preview" button should open to the side, when cmd+click

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14865]
The git 'switch to editor view' button does this.

**Comment by bpasero** [comment]
I forgot why but maybe @jrieken knows why we settled on Alt click.

**Comment by jrieken** [comment]
It is <kbd>Alt+Click</kbd> as in *alternative* click

**Comment by roblourens** [comment]
Ok, but why should it be different than the cmd+click for 'switch to editor/diff view' to the side, and cmd+click/cmd+enter to open a file from quick open in a new editor group? And how could I have discovered it?

**Comment by jrieken** [comment]
Unsure if there is a difference in discovering cmd or alt? The cmd+click behaviour seems to be inspired by browser which usually open a new tab/window when cmd+clicking on something. The menu item story is inspired by the mac menus which update when clicking alt. The one is a modification/params to a command where as the other is an alternative command (different icon, label etc).
