### ISSUE TITLE
VSCode UI process can hang if a semantic token with negative values is returned by language service

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#148651]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.66.2
- OS Version: Win11 (but presumably affects all OSs)

See https://github.com/microsoft/vscode-docker/issues/3450, https://github.com/rcjsuen/dockerfile-language-service/issues/104

Steps to Reproduce:

1. With the Docker extension installed, open the Dockerfile example from https://github.com/microsoft/vscode-docker/issues/3450, or simply enter this into a Dockerfile:
`RUN a=${b:="c"}`
1. Observe VSCode freezing up

We are independently working on the issue where negative-valued semantic tokens are returned, but invalid token data from the language service should not be causing VSCode to freeze up.

**Comment by bwateratmsft** [comment]
@rcjsuen I'm not very familiar with semantic tokens, so if there's more info you can add here feel free!

**Comment by rcjsuen** [comment]
I've tried reproducing this in a simple VS Code extension but have not had much luck. @dbaeumer I do not see anything obvious in the LSP client bridge code so I feel like it should be reproducible in a regular extension also...

**Comment by dbaeumer** [comment]
Yes, agree. This should be reproducible in a VS Code extension also.

**Comment by rcjsuen** [comment]
@alexdima Thanks for the speedy fix!
