### ISSUE TITLE
Toggle spell check doesn't work

### ISSUE THREAD

**Issue by jsachs** [Microsoft/vscode#14863]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 15.6.0
- Extensions: johnpapa.Angular1-0.1.16, mauve.terraform-0.0.2, ms-vscode.cpptools-0.9.2, samverschueren.yo-0.8.5, saviorisdead.RustyCode-0.18.0, seanmcbreen.Spell-0.8.6, xabikos.JavaScriptSnippets-1.1.0, zhuangtongfa.Material-theme-1.0.3

Steps to Reproduce:

1. Toggle spell check off
2. Toggle spell check back on. An error message occurs that the step failed.

**Comment by rebornix** [comment]
Seems it's Spell extension's issue, moved there https://github.com/Microsoft/vscode-spell-check/issues/55
