### ISSUE TITLE
WSL VS Code connection "VS Code Server for WSL closed unexpectedly."

### ISSUE THREAD

**Issue by JoeBusLife** [microsoft/vscode#148605]
I updated VS Code and now WSL connection no longer works

Just says "VS Code Server for WSL closed unexpectedly."

WSL log

> [2022-05-03 03:12:11.364] WSL Daemon exited with code 0
> [2022-05-03 03:12:10.898] Resolving wsl+ubuntu, resolveAttempt: 1
> [2022-05-03 03:12:10.937] Starting VS Code Server inside WSL (wsl2)
> [2022-05-03 03:12:10.937] Extension version: 0.66.2
> [2022-05-03 03:12:10.937] Windows build: 19044. Multi distro support: available. WSL path support: enabled
> [2022-05-03 03:12:10.937] No shell environment set or found for current distro.
> [2022-05-03 03:12:11.052] WSL daemon log file: 
> [2022-05-03 03:12:11.053] Probing if server is already installed: C:\Windows\System32\wsl.exe -d Ubuntu -e sh -c "[ -d ~/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977 ] && printf found || ([ -f /etc/alpine-release ] && printf alpine-; uname -m)"
> [2022-05-03 03:12:11.150] Probing result: found
> [2022-05-03 03:12:11.150] Server install found in WSL
> [2022-05-03 03:12:11.150] Launching C:\Windows\System32\wsl.exe -d Ubuntu sh -c '"$VSCODE_WSL_EXT_LOCATION/scripts/wslServer.sh" dfd34e8260c270da74b5c2d86d61aee4b6d56977 stable code-server .vscode-server --host=127.0.0.1 --port=0 --connection-token=560190440-3466534138 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all'
> [2022-05-03 03:12:11.236] Setting up server environment: Looking for /home/joebuslife/.vscode-server/server-env-setup. Not found.
> [2022-05-03 03:12:11.236] WSL version: 5.4.72-microsoft-standard-WSL2 Ubuntu
> [2022-05-03 03:12:11.236] WSL-shell-PID: 225
> [2022-05-03 03:12:11.236] Node executable: /home/joebuslife/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/node
> [2022-05-03 03:12:11.236] Starting server: /home/joebuslife/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/bin/code-server --host=127.0.0.1 --port=0 --connection-token=560190440-3466534138 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all
> [2022-05-03 03:12:11.236] VS Code Server for WSL closed unexpectedly.
> [2022-05-03 03:12:11.236] For help with startup problems, go to
> [2022-05-03 03:12:11.236] https://code.visualstudio.com/docs/remote/troubleshooting#_wsl-tips
> [2022-05-03 03:12:11.239] C:\Windows\System32\wsl.exe -d Ubuntu -e kill 225

Info from > "VSCODE_WSL_DEBUG_INFO=true code ."

> VSCODE_WSL_DEBUG_INFO=true code .
> + COMMIT=dfd34e8260c270da74b5c2d86d61aee4b6d56977
> + APP_NAME=code
> + QUALITY=stable
> + NAME=Code
> + SERVERDATAFOLDER=.vscode-server
> + realpath /mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/bin/code
> + dirname /mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/bin/code
> + dirname /mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/bin
> + VSCODE_PATH=/mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code
> + ELECTRON=/mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/Code.exe
> + IN_WSL=false
> + [ -n Ubuntu ]
> + IN_WSL=true
> + [ true = true ]
> + export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
> + wslpath -m /mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
> + CLI=C:/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
> + WSL_EXT_ID=ms-vscode-remote.remote-wsl
> + ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
> + cat /tmp/remote-wsl-loc.txt
> + WSL_EXT_WLOC=c:\Users\TheRa\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.2
> + [ -n c:\Users\TheRa\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.2 ]
> + wslpath -u c:\Users\TheRa\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.2
> + WSL_CODE=/mnt/c/Users/TheRa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.2/scripts/wslCode.sh
> + /mnt/c/Users/TheRa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.2/scripts/wslCode.sh dfd34e8260c270da74b5c2d86d61aee4b6d56977 stable /mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server .
> + [ -z .vscode-server ]
> + [ .vscode-server = .vscode-insiders ]
> + [ ! -t 0 ]
> + VSCODE_REMOTE_BIN=/home/joebuslife/.vscode-server/bin
> + AUTHORITY=wsl+default
> + [ Ubuntu ]
> + AUTHORITY=wsl+Ubuntu
> + dirname /mnt/c/Users/TheRa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.2/scripts/wslCode.sh
> + /mnt/c/Users/TheRa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.2/scripts/wslDownload.sh dfd34e8260c270da74b5c2d86d61aee4b6d56977 stable /home/joebuslife/.vscode-server/bin
> + [ ! -d /home/joebuslife/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977 ]
> + RC=0
> + [ 0 -ne 0 ]
> + mktemp /tmp/vscode-distro-env.XXXXXX
> + STORED_ENV=/tmp/vscode-distro-env.nzR5Zl
> + env
> + dirname /mnt/c/Users/TheRa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.2/scripts/wslCode.sh
> + VSCODE_CLIENT_COMMAND=/mnt/c/Users/TheRa/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/TheRa/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.2/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.nzR5Zl VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID /home/joebuslife/.vscode-server/bin/dfd34e8260c270da74b5c2d86d61aee4b6d56977/bin/remote-cli/code .
> + exit 0

**Comment by JoeBusLife** [comment]
any help for this?

**Comment by aeschli** [comment]
The server doesn't seem to start up, I'mm missing the server welcome message.

Can you try each of these and see if 
- close all remote windows and WSL terminals and run: `wsl --showdown`. See if it works now.
- if that doesn't help, manually run the server `/dfd34e8260c270da74b5c2d86d61aee4b6d56977/bin/code-server --host=127.0.0.1 --port=0 --connection-token=560190440-3466534138 --use-host-proxy --without-browser-env-var --disable-websocket-compression --accept-server-license-terms --telemetry-level=all` and see if we get a more helpful error message
- delete the server with `rm -r /home/joebuslife/.vscode-server/bin` and restart.

**Comment by JoeBusLife** [comment]
Nice! I got it to work.

Deleting the server did the trick.

thanks

**Comment by aeschli** [comment]
Looks like the build was corrupted. Closing the issue.
