### ISSUE TITLE
Is there any way to one button switch the vscode style 

### ISSUE THREAD

**Issue by ydmykr** [microsoft/vscode#148604]
Like what I said on title.
I have some vscode styles, they involves font and some appearance settings of editor.
I want one way to one button switch the vscode style because it's too much trouble to change many lines in setting.json.

**Comment by rzhao271** [comment]
I wonder if Settings profile can somewhat help with this

**Comment by sandy081** [comment]
/duplicate

Yes, this is like an ask for profiles
