### ISSUE TITLE
Interactive plots not working via remote ssh

### ISSUE THREAD

**Issue by pasassi** [microsoft/vscode#148662]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

I have a working environment in a remote server that have GPUs. I work in ubuntu 20.04 and the server also runs ubuntu 20.04, I like the remote ssh extension for running my scripts and notebooks in the server. However, when trying to plot interactive plots, these do not render.

For instance, working with matplotlib I am able to plot inline plots with ```%matplotlib inline``` but when I use ```%matplotlib widget``` or ```%matplotlib qt``` (interactive) the cell runs properly but nothing is showed (In the case of "qt" the cells keeps running, as it does in a local environment until the pop up window with the figure is closed).

Interactive plots are very useful for getting fast insights in some figures. 

I also tried opening a parallel ```ssh -X user@server``` connection as I found in this [answer](https://stackoverflow.com/questions/57152770/open-a-matplotlib-figure-through-ssh-tunnel-of-vscode)

But still no luck.

### VS Code Version

Version: 1.66.0 Commit: e18005f0f1b33c29e81d732535d8c0e47cafb0b5 Date: 2022-03-30T05:50:41.156Z Electron: 17.2.0 Chromium: 98.0.4758.109 Node.js: 16.13.0 V8: 9.8.177.11-electron.0 OS: Linux x64 5.13.0-39-generic

### Jupyter Extension Version

v2022.3.1000901801

### Jupyter logs

```shell
There are no outputs
```

### Coding Language and Runtime Version

Python v3.8.10

### Language Extension Version (if applicable)

Python v2022.4.0

### Running Jupyter locally or remotely?

Remote

**Comment by greazer** [comment]
Per sync discussion, @roblourens  mentioned he'd take a look.

**Comment by roblourens** [comment]
Sorry for my slow response here

Looking at https://github.com/microsoft/vscode/issues/148662#issuecomment-1116681522,

> I wonder if we can instead just load these files directly from the CDN from within the webview itself (instead of trying to send ourselves a message to get them).

We should definitely look at this - a common scenario is using Remote-SSH to connect to a remote that doesn't have internet access.

> `workbench.desktop.main.js:71 [Extension Host] ApplicationInsights:Sender (2) ['Ingestion endpoint could not be reached 80 consecu…y be resulting telemetry loss. Most recent error:', {…}]`

@lramos15 do you know what issue this log message implies?

Can someone give me an example of a cell with `%matplotlib widget` that fails here?

I can probably add some super verbose logging behind a setting.

**Comment by rchiodo** [comment]
This would likely fail:

```
# Cell 1
%matplotlib widget
```

```
# Cell 2
from matplotlib import pyplot as plt
fig,ax = plt.subplots(figsize=[10,3])
fig
```

Should draw a blank graph.

I think we could probably move to just referencing files from the CDN directly? Can we reference URIs outside of VS code from within a webview?

**Comment by lramos15** [comment]
> @lramos15 do you know what issue this log message implies?

To me it sounds like the telemetry endpoint isn't responsive so telemetry isn't being sent

**Comment by roblourens** [comment]
@pasassi and anyone else who can repro this, I've created a private build that has some extra logging, and would appreciate you trying again with this build and sharing the logs

- Run the command, "Set Log Level" > Trace
- Connect to your remote and repro the issue again
- Share the logs from the `Log (Window)` and `Log (Remote Extension Host)` output channels, and the jupyter logs


Use whichever of these builds is appropriate:
- winx64:
    - win32-x64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCodeSetup-x64-1.69.0-insider.exe
    - win32-x64-archive: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCode-win32-x64-1.69.0-insider.zip
    - win32-x64-user: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCodeUserSetup-x64-1.69.0-insider.exe
- winia32:
    - win32: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCodeSetup-ia32-1.69.0-insider.exe
    - win32-archive: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCode-win32-ia32-1.69.0-insider.zip
    - win32-user: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCodeUserSetup-ia32-1.69.0-insider.exe
- winarm64:
    - win32-arm64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCodeSetup-arm64-1.69.0-insider.exe
    - win32-arm64-archive: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCode-win32-arm64-1.69.0-insider.zip
    - win32-arm64-user: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCodeUserSetup-arm64-1.69.0-insider.exe
- macOS x64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCode-darwin.zip
- macOS arm64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCode-darwin-arm64.zip
- macOS Universal: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/VSCode-darwin-universal.zip
- Linux 64:
    - linux-x64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/code-insider-x64-1655146251.tar.gz
    - linux-deb-x64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/code-insiders_1.69.0-1655146007_amd64.deb
    - linux-rpm-x64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/code-insiders-1.69.0-1655146068.el7.x86_64.rpm
    - linux-snap-x64: https://az764295.vo.msecnd.net/insider/a921ae6c6a71715e8a14d6277f60c36ad12bbb8f/code-insider-x64-1655146523.snap

**Comment by roblourens** [comment]
Merging this into https://github.com/microsoft/vscode/issues/138784
