### ISSUE TITLE
Outline slow loading + timeout

### ISSUE THREAD

**Issue by ogmios-voice** [microsoft/vscode#148603]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows 10.0.19043 x64

Steps to Reproduce:

1. open large markdown document (10k lines) -- outline is already loading much slower then a few major versions before
2. change anything
3. switch to another file, then back
4. outline loading hangup + high CPU usage
5. after quite some time in dev tools console:

``` log
event.ts:39 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
onFirstListenerAdd @ event.ts:39
_event._event @ event.ts:659
(anonymous) @ event.ts:90
onFirstListenerAdd @ event.ts:150
_event._event @ event.ts:659
L @ listWidget.ts:598
L @ abstractTree.ts:1157
createMouseController @ abstractTree.ts:1245
q @ listWidget.ts:1379
M @ abstractTree.ts:1241
N @ abstractTree.ts:1393
k @ dataTree.ts:33
Y @ listService.ts:941
_createInstance @ instantiationService.ts:110
createInstance @ instantiationService.ts:76
_handleEditorControlChanged @ outlinePane.ts:248
processTicksAndRejections @ node:internal/process/task_queues:96
```

**Comment by jrieken** [comment]
Can you attach the file that you are testing this with.

Also try to CPU profile this. Hit F1 > Toggle Developer Tools. In the overflow menu select 'More Tools > JavaScript Profiler'. In there select start, let it profile for 30 to 60 seconds, stop it, save it to a file and attach the file here. Thanks.

https://user-images.githubusercontent.com/1794099/120606621-a97e0180-c44f-11eb-8e32-9fdafdc949ec.mov
