### ISSUE TITLE
Missing suggestion from modules that are already imported

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#148610]
* using 4.7.0-dev.20220501
* type the name of a symbol which module is already imported, e.g change `EditorInput` to `IUntypedEditorInput` [here](https://github.com/microsoft/vscode/blob/bf9929206a56b5e6115beda7e8a4a3c8f6b36908/src/vs/workbench/contrib/notebook/common/notebookEditorModel.ts#L550)
* no suggestions, quick fix resolves this

I can't guarantee that these steps are 100% the repro steps, it seems to work sometimes but often it doesn't

https://user-images.githubusercontent.com/1794099/166413299-5bde5d13-de60-458b-a1e3-25f790f49f9c.mov

**Comment by mjbvz** [comment]
I just tested this and think it may be related to inline quick suggestions. On the TS side, I don't see a call to `resolveCompletionItem` in some cases using the inline quick suggestions

**Comment by jrieken** [comment]
Hm... I should call `resolve` once for first [5 items](https://github.com/microsoft/vscode/blob/b12bb3038136b7cc32e057c382a72f868980a9ea/src/vs/editor/contrib/suggest/browser/suggestInlineCompletions.ts#L101) and also when an item has [been shown](https://github.com/microsoft/vscode/blob/b12bb3038136b7cc32e057c382a72f868980a9ea/src/vs/editor/contrib/suggest/browser/suggestInlineCompletions.ts#L207). But has usual there is no awaiting... Tho, it occurs to me that I don't flow back the resolved completion item info into the inline completion item. However, that shouldn't affect widget-based suggestions...

**Comment by jrieken** [comment]
havn't seen this anymore 🤷
