### ISSUE TITLE
`markdown.styles` doesn't support HTTPS URLs

### ISSUE THREAD

**Issue by stankovictab** [microsoft/vscode#148677]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Kubuntu 21.10

Steps to Reproduce:

1. Edit `markdown.styles` with a URL starting with HTTPS, to a .css file, for example, I have a public .dotfiles git repo in which I have a .css file for styling markdown previews - getting the URL of the raw file and pasting it in doesn't work, I get the "Could not load markdown.styles..." error.

![image](https://user-images.githubusercontent.com/62820268/166611220-24162bf2-c242-45ad-a025-6f2f0ccfed9f.png)

**Comment by mjbvz** [comment]
Have you tried hosting somewhere else? I don't think raw.github can be used for stylesheets like this

**Comment by stankovictab** [comment]
I've tried PasteBin and GitHub Gist, none of them seem to work.\
Do you have any recommendations?

![image](https://user-images.githubusercontent.com/62820268/166831233-bd37e231-01e3-419e-b76a-439d3b95b6ca.png)

**Comment by mjbvz** [comment]
If you open the dev tools to investigate further, you should see:

```
used to apply style from 'https://XXX' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

The sites all return their content as plaintext, likely because they don't want to be used as a generic CDN for stylesheets and script. So I don't think this has anything to do with https, it's just how the sites you are trying to use to host the contents are configured 


Closing this as by-design

**Comment by stankovictab** [comment]
Would be nice if this was mentioned somewhere in the docs, because as it stands this feature is very limiting.\
At the very least mention an example of a hosting service that would return the right content type, we shouldn't need to guess.
