### ISSUE TITLE
Parsing failure when tasks.json contains comment in args array

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#148679]
I originally posted this at https://github.com/OmniSharp/omnisharp-vscode/issues/4377 and it was recommended to report it here as it's a vscode problem, not an omnisharp one.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.3
- OS Version: ubuntu 20

Steps to Reproduce:

From original issue:

### Problem
When opening a project, I get a popup error:
> Failed to parse tasks.json file

### Sample
This is `.vscode/tasks.json` which is a `jsonc` file:
````jsonc
// this comment is allowed
{
  // this comment is allowed
  "version": "2.0.0",
  "tasks": [
    {
      // this comment is allowed
      "label": "run",
      "type": "process",
      "command": "dotnet",             // this comment is allowed
      "args": [
        "run",
        "--project",
        "${workspaceFolder}/src/Foo/Foo.csproj",
        //"--launch-profile", "Production",           // <<<<<<<<<< THIS IS THE PROBLEM
      ],
    },
  ],
  // this comment is allowed
}

````

The comment inside the `args` array is the problem. When removed, there is no error.

**Comment by alexr00** [comment]
As far as I can see that error isn't coming from VS Code. You could try the extension [bisect feature](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) feature to figure out which extension.
