### ISSUE TITLE
language scope markdown math

### ISSUE THREAD

**Issue by funnym0nk3y** [microsoft/vscode#148644]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Win10 21H2

This issue is about the language scope for markdown inline math. Creating a inline via a snippet leads to inconsistent behavior. See below. 

Steps to Reproduce:

1. Create markdown inline math with `$$`
2. Set the cursor between both dollar symbols
3. View language scope

It seems that the cursor position directly infront of the closing dollar symbol hat the language scope `markdown` instead of the language scope `latex`. This leads to inconsistent snippet behavior.

**Comment by 0xdw** [comment]
@mjbvz I would like to assist with this. Can I have more details on this?

**Comment by Priyankcoder** [comment]
@funnym0nk3y I followed your steps to reproduce the bug but was unable to view the language scope. How to see the language scope? 
It would be easy to understand if you can please provide a gif or video that shows producing the bug.

**Comment by funnym0nk3y** [comment]
Sure, here you go: 
![Animation](https://user-images.githubusercontent.com/41870754/173188536-deb4f8f7-95ac-45df-a89a-2d86d75dae5c.gif)

You can view the language scope by searching for the command `Developer: Inspect Editor Tokens and Scopes`

**Comment by jamiecha88** [comment]
Hi, is anyone still working on this? I'm new to open source and would love to contribute!

**Comment by Mres01** [comment]
Hey @jamiecha88 , do you know how cani scop two different variables, i wanna use two different color for variable quoted and variable unquoted.
