### ISSUE TITLE
Undo Last Commit not enabled when commiting only part of changes

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#14869]
- VSCode Version: Code 1.7.0 (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T14:34:01.691Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Steps to Reproduce:

1. Change 2 files
2. Stage 1 file
3. Commit change
4. Observe: Undo Last Commit is not enabled in the viewlet's menu

**Comment by joaomoreno** [comment]
Undo Last Commit is disabled whenever your working directory is not clean. This is to prevent situations in which undoing the last commit would overwrite changes you've done.

**Comment by joaomoreno** [comment]
#13197
