### ISSUE TITLE
Use ETag caching when running from source

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#148642]
Follow up from https://github.com/microsoft/vscode/pull/147311#discussion_r863619204

Doing the following steps:
* `scripts/code-server.sh`
* open the web ui
* uncheck "Disable caching" in DevTools
* cause a page load by pressing Enter in the URL bar (cmd+r sometimes is interpreted by some browsers as load without cache, so use that if your browser doesn't disable caching when pressing it)

### Without ETag (59.5MB transferred, page load 3.82s):
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/5047891/166483691-7d5ba5e4-b57d-4f18-baa5-e0f5cfa1076d.png">

### With ETag (275kB transferred, page load 2.83s)
* apply the patch:
```patch
diff --git a/src/vs/server/node/webClientServer.ts b/src/vs/server/node/webClientServer.ts
index 6053e046a51..11e361ee77d 100644
--- a/src/vs/server/node/webClientServer.ts
+++ b/src/vs/server/node/webClientServer.ts
@@ -158,7 +158,7 @@ export class WebClientServer {
 			return serveError(req, res, 400, `Bad request.`);
 		}
 
-		return serveFile(filePath, this._environmentService.isBuilt ? CacheControl.NO_EXPIRY : CacheControl.NO_CACHING, this._logService, req, res, headers);
+		return serveFile(filePath, this._environmentService.isBuilt ? CacheControl.NO_EXPIRY : CacheControl.ETAG, this._logService, req, res, headers);
 	}
 
 	private _getResourceURLTemplateAuthority(uri: URI): string | undefined {
```

Do the same steps:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/5047891/166484105-c860034a-9411-4dbd-b69a-204a6709289e.png">

This pays off especially when using a codespace to develop vscode web, etc.

**Comment by aeschli** [comment]
Ok, convinced, thanks for the measurements!
