### ISSUE TITLE
Drag and drop message should not appear for certain editors

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#148655]
<img width="1442" alt="CleanShot 2022-05-03 at 12 38 04@2x" src="https://user-images.githubusercontent.com/35271042/166553083-b11b614a-3508-4484-92b3-45b4d3263e1e.png">

This was when I was dragging around the simple browser and I didn't expect to see the message. Dropping it does nothing so we should at least disable this interaction for the simple browser and others editors where it doesn't make sesne?

**Comment by mjbvz** [comment]
We already disable drag and drop for things like the welcome view

We keep it enabled for webviews as they may support dropping (and there's not really a good way to determine if they do or do not)

**Comment by misolori** [comment]
This feels like a design flaw in that we tell the user they can perform an action but it doesn't actually work, which makes the product look unintelligent.

**Comment by misolori** [comment]
Is there no way for us to introduce a flag to enable/disable this certain webviews?

**Comment by mjbvz** [comment]
Yes but then we'd need extensions to adopt it. I just don't see it being worth it

As to why this is enabled: you can drop into text inputs and webviews allow custom drop behaviors too. To avoid regressions, we need to keep this enabled by default
