### ISSUE TITLE
Comment loss when clicking "Go to review"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#148629]
Related to microsoft/vscode#149157, when you click the wrong button after having entered a review, the comment is gone for good. I really think the button has to go away.

![Recording 2022-04-14 at 07 16 33](https://user-images.githubusercontent.com/900690/163318481-2f7cb391-b521-4695-920e-450a35461453.gif)

**Comment by joyceerhl** [comment]
If I start typing a comment for a particular line in the source, then click collapse, then start a comment for the same line, the contents of the editor widget disappear, is that expected?

**Comment by alexr00** [comment]
Yes, if you collapse the comment then you've dismissed the the comment and the contents should disappear.
