### ISSUE TITLE
Clicking a validation warning in 'default settings' opens a 'settings.json' file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14867]
- Install tslint (or some other extension that produces a validation warning in its default settings)
- Open the split settings view
- Open the problems panel
- See the warning listed under `/settings.json`
- Double click it
- It opens in a file called `/settings.json` which has the same contents as Default Settings. Can it open in Default Settings instead?

![image](https://cloud.githubusercontent.com/assets/323878/19940599/74f13e42-a0ea-11e6-80e3-7214658a3ef5.png)

**Comment by sandy081** [comment]
Duplicates #8714
