### ISSUE TITLE
The integrated terminal is not used

### ISSUE THREAD

**Issue by ndzuki** [microsoft/vscode#148602]
When you open an integrated terminal or create a new terminal, it is an invalid response.
![image](https://user-images.githubusercontent.com/40823052/166392953-293045ca-4271-4db9-8d2f-d2f04b91346f.png)

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"
