### ISSUE TITLE
[loc][Query][VSCode] Please clarify "Process"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#14860]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Process

File Name:
src\vs\workbench\parts\debug\electron-browser\debugViewer.nls.resx

Resource ID:
".resx", 0; "process"

Query:
Is this a verb or a noun?	Cristina Carrasco	11/1/2016 6:24:06 PM

**Comment by rebornix** [comment]
assign to @roblourens first as @roblourens takes over debugging stuff these few days.

**Comment by isidorn** [comment]
It is a noun in that context - added a comment to the nls call
