### ISSUE TITLE
Autocomplete can't parse JSON object properties

### ISSUE THREAD

**Issue by Ruzie** [microsoft/vscode#148626]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.66.2
- OS Version: Ubuntu 22.04 LTS

Steps to Reproduce:

1. Open VSCode and create a JSON file.
2. Fill up JSON file with some data.
3. Now try to read the JSON file by importing it though TypeScript, sometimes VSCode autocomplete doesn't show up JSON objects properties, until you restart your IDE.

Let me elaborate, as I said it's happens randomly (especially if I'm working on VSCode for a long time), and when I try to parse a JSON file by importing it, JSON file objects doesn't shows up in autocomplete, by trying to force writing, it will throw an error, for example "property Y doesn't exist on type X". So every-time I need to restart VSCode and then it loaded the JSON file correctly, if I update the JSON file again, it creates the same issue.

**Comment by mjbvz** [comment]
Can you please share a project that demonstrates this issue?
