### ISSUE TITLE
the PowerShell's devcontainer.json is invalid

### ISSUE THREAD

**Issue by eitsupi** [microsoft/vscode#148615]
https://github.com/microsoft/vscode-dev-containers/blob/dfba31dbeee27378ce3beced5e5004462a2c6311/containers/powershell/.devcontainer/devcontainer.json#L7

`pwsh` does not seem accepted.

> Value is not accepted. Valid values: "sh", "bash", "bash (2)", "rbash", "rbash (2)", "dash", "dash (2)", "tmux", "screen", "fish", "JavaScript Debug Terminal".(1)

This seems to be a schema issue rather than a definition issue, but I didn't know where to report it. Please transfer if necessary.

- VSCode Version: 1.66.2
- Local OS Version: WSL2
- Local chip architecture: x86
- Reproduces in: Remote - Containers
- Name of Dev Container Definition with Issue: PowerShell

**Comment by chrmarti** [comment]
@Tyriar @meganrogge The issue here is that WSL does not have `pwsh` installed, only the dev container has. So there is an unexpected warning when being connected to WSL.

**Comment by meganrogge** [comment]
You'll need to add a `pwsh` profile to your `"terminal.integrated.profiles.linux"` with the proper path to that executable

**Comment by Tyriar** [comment]
I feel like this warning is by design on my end since the setting has some advanced validation. I'd recommend @meganrogge's approach to workaround.

**Comment by eitsupi** [comment]
Note that, the warning did not occur on the container.
The warning occurs before the container is built.
`devcontainer.json` is a file to edit before creating the container.
