### ISSUE TITLE
Visual Studio code making noise on syntax error 😱💥

### ISSUE THREAD

**Issue by objectiveSee** [microsoft/vscode#148641]
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.66.2 (Universal)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:20.994Z (3 wks ago)
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Darwin arm64 21.1.0

Steps to Reproduce:

1. Type invalid code
2. VScode makes a "do doo" sound on EVERY SINGLE ERROR. This is driving me insane. I have to mute my entire Mac in order to work.

Seems related to this bug https://developercommunity.visualstudio.com/t/visual-studio-code-making-noise-on-syntax-error-ho/1690800 which was not resolved in the comment.

**Comment by isidorn** [comment]
@ArturoDent thanks for answering
@objectiveSee this is because you had a screen reader turned on while using VS Code. Or at least some time in the past.

**Comment by objectiveSee** [comment]
Thanks! That fixed it :) 🎊
