### ISSUE TITLE
Dragging files over editor tab for a few seconds should open the editor so I can drop into it

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#148664]
**Repo**
1. With a few open editor tabs in a single group
2. Start dragging a file from the VS Code explorer
3. Try to drag into one of the non-open editors

**Feature request**
While dragging, I should be able to hover over an unopened editor tab for a few seconds to open the editor. After the editor is opened I should then be able to drop into it by holding `shift`

**Comment by rzhao271** [comment]
Verified that shift+drop results in the path being pasted.
