### ISSUE TITLE
integrated terminal profile is not respected by git build in

### ISSUE THREAD

**Issue by maksim-pinguin** [microsoft/vscode#148720]
- VS Code Version: 1.66.2
- OS Version: Windows 10

Steps to Reproduce:

1. install cygwin 
2. configuire integrated termial to cygwin
```
  "terminal.integrated.profiles.windows": {
        "Cygwin": {
          "path": "C:\\cygwin\\bin\\bash.exe",
          "args": ["--login"],
          "env": {"CHERE_INVOKING": "1"}
        }
    }
```

3. git build in doesn't respect this. 
Gitlense on the other hand makes use of the integrated terminal profile so setting git.path can only satisfy gitlense or git base

**Comment by maksim-pinguin** [comment]
i guss this would also fix this  #7998

**Comment by meganrogge** [comment]
Yes /duplicate #7998

**Comment by maksim-pinguin** [comment]
@meganrogge @Tyriar would you please reopen either this or https://github.com/microsoft/vscode/issues/7998 since this issue still exists

**Comment by Tyriar** [comment]
It's not totally clear what you mean here but we don't support Cygwin for the built-in git functionality (#7998 was closed as out of scope/won't fix), plus the integrated terminal has nothing to do with built-in git so they are unrelated; the terminal will not use git.path by design.

**Comment by maksim-pinguin** [comment]
> the terminal will not use git.path by design.
but the extensition do., see Gitlense e.g.

>'s not totally clear what you mean here but we don't support Cygwin for the built-in git functionality

my question is why is git built-in not using the integrated terminal like other extension are doing it. like the setting in git.path would have to be different per extension but just per terminal

**Comment by maksim-pinguin** [comment]
it's less of a question of supporting cygwin per se, but of supporting the configured integrated terminal setup

**Comment by Tyriar** [comment]
@maksim-pinguin the only integration I think exists between them is git injecting an auth provider via environment variables. The terminal picks up git from your path, if it's not on your path you should configure your terminal to do that. Basically this is out of scope as well.

**Comment by maksim-pinguin** [comment]
> @maksim-pinguin the only integration I think exists between them is git injecting an auth provider via environment variables. The terminal picks up git from your path, if it's not on your path you should configure your terminal to do that. Basically this is out of scope as well.

I have got on my path. In the terminal integration. 

So again the build in git is not using the right  terminal. You will have the same problem when trying to use git with a wsl terminal.

**Comment by maksim-pinguin** [comment]
@Tyriar @meganrogge 
Can you tell me at least we're I need to approach this to make git (build in) use my integrated terminal?

I would like to try to implement it.

**Comment by Tyriar** [comment]
I still don't understand what you mean, the built-in git does not use a terminal.
