### ISSUE TITLE
Allow for vertically arranged editor tabs

### ISSUE THREAD

**Issue by fcntl** [Microsoft/vscode#14875]
- VSCode Version: all
- OS Version: all

Horizontal tabs are a bad design decision, as when you have more than about 10 they start to cut off the name in the tab title. Vertically arranged tabs are the best solution to this, and there should be an option to switch between horizontally and vertically arranged editor tabs.

**Comment by rebornix** [comment]
Thanks for your suggestion but currently I don't think we are going to do this. cc @bgashler1 @bpasero

**Comment by grantbowering** [comment]
I know this is closed, but with uservoice deprecated, I don't know where else to express that it's a really key/killer feature for me.  The Productivity Power Tools extension for Visual Studio 2012-2015 is one of the first things I install and I really miss it in VSCode.  
Honestly, as soon as you work with vertical tabs for more than a few minutes, it's hard to imagine why horizontal tabs are the standard.  16:9 means that we always have SO much horizontal space across our monitors, way more than we need for writing code... and the vertical burden of a filename is only the height of ONE character, whereas the horizontal burden is the entire length of the filename... so when you think about it critically, it's sort of _**bananas**_ that everything is horizontal tabs by default.

Which is easier to find the file you want to switch back to working with, honestly?  This:
![normal tab well](https://cloud.githubusercontent.com/assets/2152220/20069933/c760c540-a4db-11e6-882c-3b9ca551ece1.png)
Or this?
![vertical tab well](https://cloud.githubusercontent.com/assets/2152220/20069951/dd66b5a2-a4db-11e6-8433-73fc87fcceff.png)

The thing is, VSCode is already pretty close to HAVING this feature.  If one uses the Open Editors pane, and only uses one editor group, it already pretty much IS a vertical tab well... and those of us who want that can just turn the horizontal tabs off...
So all that we need to satisfy this feature request is actually to be able to _**separate**_ Open Editors from Explorer, so we can have Open Editors in its own column on the left hand side of the workbench and Explorer in its own column on the right hand side of the workbench.  (And maybe tweak the font size and padding of the items in Open Editors a bit to be more tab-like, but I'm not even picky about that...)

**Comment by thers** [comment]
Is this suggestion considered dead completely? :(
