### ISSUE TITLE
Search/Find input boxes should respect "editor.dragAndDrop": false

### ISSUE THREAD

**Issue by Z-E-D** [microsoft/vscode#148779]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.0
- OS Version: Windows 7

Steps to Reproduce:
![2022-05-05_10-53-47](https://user-images.githubusercontent.com/97363660/166893040-9ca19f2a-68e8-40bc-a861-11e8ce73918b.gif)

1. open file, select any part of text in editor and press Ctrl+F;
2. select any part of the text in the Find widget;
3. try again to select the text in the Find widget -> VSCode is trying to drag&drop the selected part, you need to click on the empty area to deselect text to be able to select another part of the text.

I have "editor.dragAndDrop": false since I hate the option to drag&drop the selected text. I find it more troublesome, with inadvertently moved text, than helpful.

The Search/Find input boxes should respect that settings.

**Comment by amunger** [comment]
the editor.* settings are implemented for Monaco editors, so this would be a new feature.
