### ISSUE TITLE
Ouch! There are too many extensions in vscode!

### ISSUE THREAD

**Issue by hpytrail** [microsoft/vscode#148798]
# Why
There are always too many extensions in vscode. Especially, when I am developing with many programming language.
# What I wish
I wish I could create some groups like c++, web, python, themes and so on. I can put some of my extensions in them. That's nice.
# at the end
Thank you for the developers of vscode.

**Comment by IllusionMH** [comment]
Looks like it's duplicate of issues mentioned in https://github.com/microsoft/vscode/issues/139747#issuecomment-1001340183
