### ISSUE TITLE
Test Explorer not visible in Activity Bar

### ISSUE THREAD

**Issue by gregorybleiker** [microsoft/vscode#148795]
Issue Type: <b>Bug</b>

It is my understanding that there should be a Test Explorer built-in to VS Code. However, my installation:

Version: 1.66.2 (system setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19043

(also tried insider) does not show this activity:

![image](https://user-images.githubusercontent.com/1917329/166921289-d65100a9-9887-4adf-b494-db8c3b180b31.png)

Also opening a .net core c# project with a tests folder an solution did not change anything. 

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (0.69GB free)|
|Process Argv|--crash-reporter-id fce29084-cca9-45a8-931d-559dd906be6b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|0.0.84
jsonpath-extract|dav|1.2.3
vscode-jq-playground|dav|4.2.0
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
jq-syntax-highlighting|jq-|0.0.2
language-haskell|jus|3.6.0
rainbow-csv|mec|2.3.0
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
csharp|ms-|1.24.4
azure-account|ms-|0.10.1
powershell|ms-|2022.5.0
vscode-yaml|red|1.7.0
rf-intellisense|Tom|2.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by connor4312** [comment]
The Test explorer is only available when a test controller is registered by an extension. If you expects tests to show up from the C# extension but they don't, please open an issue on that extension!
