### ISSUE TITLE
Find in Selection Does Not Support Multiple Selections

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#14872]
- VSCode Version: 1.7.0-insider
- OS Version: Windows 7 Professional x64

Steps to Reproduce:
1. Select several blocks containing the same substring.
2. Search for that substring in the current selection.
3. Observe that only the last instance is found.

**Comment by freMea** [comment]
VS Code version | OS
------------------ | ----
1.13.0  | Win x64 pro (french)

## Steps to reproduce

1. Select non concurrent block with `CTRL+LeftClickDrag` on gutter
2. `CTRL+F` then enable _find in selection_ feature

## Results

Only the first selected concurrent lines are affected by the _find in selection_ feature. The other are then unselected.

## Expectations

Use the user selected blocks/lines even if non concurrent when find/replace and _find in selection_ is ON.

**Comment by rebornix** [comment]
It already works now.
