### ISSUE TITLE
Improve the sorting and matching of quick pick

### ISSUE THREAD

**Issue by kentcdodds** [Microsoft/vscode#14879]
Originally posted in the [`vscode-project-manager`](https://github.com/alefragnani/vscode-project-manager) extension issues [here](https://github.com/alefragnani/vscode-project-manager/issues/66). @alefragnani suggested that I file the issue here to have this applied to `PickList`. I'm unfamiliar with this codebase. But I think that [`match-sorter`](https://github.com/kentcdodds/match-sorter) provides a better way to filter and sort items in a list based on user input. Could we consider adding that kind of functionality to VSCode?

Thanks!

**Comment by bpasero** [comment]
@kentcdodds is this about general sorting in all quick open things like file search, command search etc. or only for extensions that use the picker widget?

**Comment by kentcdodds** [comment]
I think that the way match-sorter works too improve the intuitiveness of lost filtering and matching is actually pretty great, so it probably makes sense for everything.

**Comment by bpasero** [comment]
Makes sense.

**Comment by alefragnani** [comment]
@bpasero, When I asked @kentcdodds to fill an issue here, I didn't remember the other issue that already existed. I did another search and found, it's https://github.com/Microsoft/vscode/issues/14727. 

Since you were looking for a better fuzzy search, I thought you could work together on this.

Hope this helps

**Comment by bpasero** [comment]
Yup, they are related. I am however currently not working on it (I unassigned myself). Sorry for the confusion.

**Comment by atombender** [comment]
Here's an example of where it goes wrong:

<img width="678" alt="e8b7bd8a-aa6b-11e6-8188-78c294ce5efd" src="https://cloud.githubusercontent.com/assets/50314/22657617/1b0744c8-ec65-11e6-984d-74efc97193d4.png">

The file `cmd/gradient/main.go` is scored lower even though the text I typed matches _contiguously_. The top matches have matched random characters in other file names which seem to have accidentally have bumped their score up, even though the matches make less sense.

The solution is to score in a way that promotes results with a low distance between each character. Levenshtein would work here.

**Comment by kentcdodds** [comment]
Yeah, there's an issue right now for adding something like that to `match-sorter` [here](https://github.com/kentcdodds/match-sorter/issues/21). FWIW, given that screenshot, match-sorter would have sorted things more cleanly.
