### ISSUE TITLE
Update or clean install of @code 1.6.1.0 displaying blank screen and consuming CPU

### ISSUE THREAD

**Issue by kevsully** [Microsoft/vscode#14870]
- VSCode Version: 1.6.1.0
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Install or Update to 1.6.1.0
2. Run
![vscode](https://cloud.githubusercontent.com/assets/8667124/19943004/01b6a35a-a10c-11e6-8ab9-dd02d564cca3.jpg)

**Comment by rebornix** [comment]
@kevsully do you mind taking a look at these steps https://github.com/Microsoft/vscode/issues/14222#issuecomment-255724170 by @bpasero to help us understand what's the problem?

**Comment by bpasero** [comment]
@kevsully are you running Windows on a VM?

**Comment by kevsully** [comment]
Hi bpasero, sorry for delay. I'm looking at this again now. Yes the 2012 R2 box(es) are hosted in Azure. I'll try the steps you mention above and let you know.

**Comment by kevsully** [comment]
OK, so I looked through the previous #14222 and mine is a bit different as there are no extensions, no preview build, just a clean new install. I tried it on upgrade as well and had same experience. Azure server instance. Happy to share or do a screen share with someone if interested as it is easy to repro... takes just a few minutes.

**Comment by bpasero** [comment]
This seems to be https://github.com/Microsoft/vscode/issues/13882
