### ISSUE TITLE
Source Control not working with git

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [microsoft/vscode#148736]
Issue Type: <b>Bug</b>

I have recently updated ubuntu from 20.04 to 22.04. Then I have installed the vs code and synced all. But I found, whenever I tried to check git output from vs code, I can't see anything. I have installed git and also added it to path. I also noticed other extentions can initialize the path but not working. However, when I was running the vs code in ubuntu 20.04, it worked fine. 
I searched in the internet and disabled the builtin git extention and enabled again but did not work. Also, I runned vs code with 'code --disable-extensions' but not worked. Then, I have cleaned all user data and uninstalled the code but not worked.

### Update
I am using duel boot  mode in my desktop. Thus, I have booted my pc with windows 11. Here, I can see the same error, where this works well in my laptop. All the reposetories are showing. But in my desktop, it only shows to initialize reposetory, though I have already. However, git is working in intregated terminal. Again, When I click on **Initialize Reposetory**, nothing happens.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.15.0-27-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2800)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (5.82GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 0c66816d-c45e-4254-bb2e-25793d1d2980|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (101)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
html-snippets|abu|0.2.1
codesnap|adp|1.3.4
project-manager|ale|12.5.0
vscode-django|bat|1.10.0
armview|ben|0.4.6
django-html|bib|1.3.0
npm-intellisense|chr|1.4.1
gitignore|cod|0.7.0
bracket-pair-colorizer-2|Coe|0.2.4
systemd-unit-file|coo|1.0.6
dart-code|Dar|3.40.0
flutter|Dar|3.40.0
flutter-auto-import|dav|0.0.1
jshint|dba|0.11.0
vscode-eslint|dba|2.2.2
python-preview|don|0.0.4
git-extension-pack|don|0.1.3
githistory|don|0.6.19
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
micropython-ide-vscode|dph|0.0.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
vscode-html-css|ecm|1.11.0
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.24
LogFileHighlighter|emi|2.15.0
json-tools|eri|1.0.2
prettier-vscode|esb|9.5.0
git-project-manager|fel|1.8.2
auto-rename-tag|for|0.1.10
codespaces|Git|1.8.0
copilot|Git|1.15.5815
vscode-pull-request-github|Git|0.40.0
unibeautify-vscode|Gla|0.8.2
gc-excelviewer|Gra|4.2.54
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.6.8
svg|joc|1.4.17
vsc-python-indent|Kev|1.15.0
vscode-python-test-adapter|lit|0.7.1
MagicPython|mag|1.1.0
python-path|mge|0.0.11
git-graph|mhu|1.30.0
azure-pipelines|ms-|1.204.0
vscode-azureappservice|ms-|0.23.3
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurestorage|ms-|0.13.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.6.1
vscode-cosmosdb|ms-|0.18.1
vscode-docker|ms-|1.22.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
test-adapter-converter|ms-|0.1.6
vscode-node-azure-pack|ms-|0.3.0
vsliveshare|ms-|1.0.5527
azurerm-vscode-tools|msa|0.15.6
vscode-react-native|msj|1.9.2
awesome-flutter-snippets|Nas|3.0.3
linux-desktop-file|nic|0.0.21
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
es6-css-minify|olb|3.3.3
material-icon-theme|PKi|4.16.0
material-product-icons|PKi|1.3.0
sqlite-viewer|qwt|0.1.5
vscode-thunder-client|ran|1.16.2
LiveServer|rit|5.7.5
bootstrap-product-icons|rub|1.0.2
ayu|tea|1.0.5
vscode-djaneiro|the|1.4.2
vscode-readme-pattern|tho|1.3.0
pdf|tom|1.2.0
cmake|twx|0.0.17
errorlens|use|3.4.2
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.20
vscode-wakatime|Wak|18.1.2
quokka-vscode|Wal|1.0.462
jinja|who|0.0.8
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
markdown-pdf|yza|1.4.4
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by lszomoru** [comment]
@ahnaf-tahmid-chowdhury, the latest Insiders release (2022-05-15) contains some logging improvements, and additional logging for the process of discovering a git repository. Could you please implement the following steps and share the output:
1. Download the latest Insiders release from https://code.visualstudio.com
2. Enable verbose logging as described in the following [wiki page](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#log-level-setting)
3. Open the workspace/folder that contains the git repository
4. Share the contents of the git output channel
