### ISSUE TITLE
SQL syntax highlighting: escaped quote (`\'`) not handled properly in single-quoted strings

### ISSUE THREAD

**Issue by jivanpal** [microsoft/vscode#148789]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: macOS 10.15.7 (Catalina build 19H1824)

Steps to Reproduce:

1. Create a new file, switch syntax highlighting to SQL, enter the following snippet:
```
SELECT
'Hello',
'th\'ere',
'how',
'are',
'you';
```
2. Observe that highlighting occurs improperly after `\'` on line 3; the escaped quote is incorrectly seen as the end of the string `th\`. [This is a bug in the underlying Textmate grammar](https://github.com/textmate/sql.tmbundle/blob/6d4edbc113d3272f7c097d6b1504624289ee2bc5/Syntaxes/SQL.plist#L587), but [textmate/sql.tmbundle](https://github.com/textmate/sql.tmbundle) has not been maintained for over 5 years, so does this see any chance of being resolved?

As a workaround, the single-quoted string can be changed to double-quoted:

```
SELECT
'Hello',
"th'ere",
'how',
'are',
'you';
```

However, I noticed this issue when comments and other large chunks of code in an existing codebase were not highlighted properly (instead all being considered part of a single string and thus highlighted as such) due to single-quoted strings containing `\'` not being parsed properly; it's a nuisance to have to change all such instances in order to fix this presentation issue.

**Comment by alexr00** [comment]
@jivanpal please correct me if I'm wrong but I think using `\` to escape `'` is valid in MySQL but not SQL.

**Comment by jivanpal** [comment]
Hmm, seems you're right that `\'` is not valid in ANSI SQL, and is MySQL/MariaDB-specific. Source: https://www.databasestar.com/sql-escape-single-quote/

You learn something new every day! I take it this is a nofix then? Is there a recommended/official extension for MySQL syntax highlighting? The ones I've tried don't seem to do a great job.

**Comment by alexr00** [comment]
Yes, since our SQL grammar tries to be general this is wont-fix. You might try ms-mssql.mssql since it contributes a grammar, but it may have the same issue.
