### ISSUE TITLE
Add "Stage selected lines" to context menu

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#14873]
It's in the '...' menu on the diff editor but not the context menu. It feels much more natural to select something then right click to stage.

**Comment by joaomoreno** [comment]
Which context menu do you mean?

**Comment by roblourens** [comment]
In the editor

**Comment by ice-blaze** [comment]
I would suggest to add a keybinding to do it too. I don't know if I have to create another issue ?

**Comment by hun1ahpu** [comment]
@joaomoreno Do you think it's a good idea? i'd like to work on this feature if yes.

**Comment by hun1ahpu** [comment]
@joaomoreno I'd appreciate some help on this one as I am new to the codebase.

Looking at gitActions.contribution.ts and StageRangeAction. Is using editorAction the right and only approach to add an action to a context menu of the DiffEditor?

Thanks.

**Comment by joaomoreno** [comment]
It should be. Try figuring out how these actions get there:

![image](https://cloud.githubusercontent.com/assets/22350/21605178/a30f5fbe-d1a7-11e6-961b-518024a72818.png)

**Comment by jrob** [comment]
I would like to second the request for keybinding ability. I am happy to create a separate request if it is worth it.

**Comment by ice-blaze** [comment]
@jrob In the latest version of march 1.11, you can bind `(un)stage selected lines ` to shortcuts
