### ISSUE TITLE
Live share modal text failure

### ISSUE THREAD

**Issue by HookyQR** [microsoft/vscode#148759]
When live share opens in the web, initially, I have what I'm assuming are i18n failures:
![CleanShot 2022-05-05 at 10 59 19](https://user-images.githubusercontent.com/14353068/166857803-1b94716d-090f-4899-9306-aac25a47c1a4.png)

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: vscode.dev
- OS Version: macos
- Browser: Brave

Steps to Reproduce:

1. click a liveshare link with brave set as default browser (not sure if it's brave or the server with the issue)

**Comment by HookyQR** [comment]
With shields down, I get:
![CleanShot 2022-05-05 at 11 34 35](https://user-images.githubusercontent.com/14353068/166860306-9087e157-d4cf-48e5-9ef2-965d787a81f2.png)
The only errors logged (which don't provide much detail) 
![CleanShot 2022-05-05 at 11 37 08](https://user-images.githubusercontent.com/14353068/166860421-56a621df-f999-40ef-b11c-63b57c78cf41.png)
Oddly, after clicking (accidentialy) Open in vs code, the text reverts back to the original display (with the cancel button). I'm assuming the initial time it automatically started opening in VSCode.

Note: I cleared the app storage before trying with shield down, so that might have caused the in between dialog seen here.

Might help:
`navigator.language === 'en-AU'`

**Comment by HookyQR** [comment]
`navaigator.language = 'en-US'` has the same result.

**Comment by HookyQR** [comment]
Probably needs to move to https://github.com/MicrosoftDocs/live-share 🤦

**Comment by sbatten** [comment]
@HookyQR please file on live share
