### ISSUE TITLE
Terminal doesn't open file:// URIs

### ISSUE THREAD

**Issue by mrlegohead0x45** [microsoft/vscode#148729]
Issue Type: <b>Bug</b>

1. Run any command that outputs a file:// URI into the terminal
2. Hover over it
3. Box appears 
![Screenshot 2022-05-04 195546](https://user-images.githubusercontent.com/96256923/166806264-fbd9c79c-a86c-42f3-a4c9-08d43523da6e.png)
4. Ctrl+Click

Expected behaviour: Opened in browser like a http[s]:// URI
Actual behaviour: Upon Ctrl+Click ing 'file://C:\Users', an error box pops up

![Screenshot 2022-05-04 195214](https://user-images.githubusercontent.com/96256923/166805966-0e6e85b2-3569-423c-bb7b-aa52d993abd3.png)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.17GB free)|
|Process A

rgv|--crash-reporter-id fa09f6c9-9244-4513-b4ef-c981711ab2fd|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-sqlite|ale|0.14.0
mermaid-markdown-syntax-highlighting|bpr|1.2.3
better-toml|bun|0.3.2
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
vdf|GEE|0.0.7
copilot|Git|1.15.5815
vscode-pull-request-github|Git|0.40.0
minify|Hoo|0.4.3
rest-client|hum|0.24.6
better-cpp-syntax|jef|1.15.13
vscode-graphviz|joa|0.0.6
vscode-docker|ms-|1.22.0
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
hexeditor|ms-|1.9.6
powershell|ms-|2022.5.0
autodocstring|njp|0.6.1
vscode-yaml|red|1.7.0
swdc-vscode|sof|2.6.30
ninja|sur|0.0.1
simple-rst|tro|1.5.2
cmake|twx|0.0.17
vscode-icons|vsc|11.11.0
vscode-mermaid-preview|vst|1.6.2
jinja|who|0.0.8
vscode-nginx|wil|0.7.2
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by Tyriar** [comment]
You're not meant to use \ as the separator in file:// paths: https://en.wikipedia.org/wiki/File_URI_scheme#Windows
