### ISSUE TITLE
Import path cannot end with ".ts" extension

### ISSUE THREAD

**Issue by idanran** [microsoft/vscode#148756]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Windows 11

Steps to Reproduce:

1.
```js
export * from "./config.ts"
```

2.
It say:
`An import path cannot end with a '.ts' extension. Consider importing './config.js' instead.`

3.
I use Deno, which needs to specify the extension, including ts

**Comment by IllusionMH** [comment]
/question

If you work with Deno you should install and configure Deno extension.

See https://deno.land/manual/vscode_deno#troubleshooting specifically and check full page content as well.
