### ISSUE TITLE
Github.dev - Cannot open file

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#148771]
https://github.dev/microsoft/vscode/pull/148767/files
In microsoft/vscode/src/vs/workbench/api/common/extHostLanguageFeatures.ts

![recording](https://user-images.githubusercontent.com/2931520/166878590-80f6251f-2847-4e70-a78a-ced7996aabef.gif)

**Comment by Lukas-Batema** [comment]
I am having this issue too on insiders.vscode.dev, with opening files AND opening remote repos...

**Comment by joaomoreno** [comment]
Unsure if Remote Repositories or anycode...
