### ISSUE TITLE
Cannot tab into statusbar

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#14871]
- VSCode Version: Code 1.7.0 (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T14:34:01.691Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

Smoke-testing 1.7.0: Could not find a way to tab into the statusbar.

**Comment by bpasero** [comment]
@chrmarti The status bar actually was never keyboard accessible, we did this "by design" to reduce the number of hits you have to do until you reach the more important pieces of the UI. the rationale was that all things in the status bar are also reachable via commands from the command palette.
