### ISSUE TITLE
Sorting of source by path doesnt work

### ISSUE THREAD

**Issue by shaiky88** [microsoft/vscode#148784]
Issue Type: <b>Bug</b>

Hi Team ,

I see that with new version 1.66.2 sorting of source by path is not working correctly. Also not all the subprojects are shown as part of source control.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.78GB free)|
|Process Argv|--crash-reporter-id ca8ce366-73c9-466c-b7c9-f5bc31d27c8c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
1.67 is likely to be released later today. I suggest you re-test with that, then paste screenshots (obfuscated if necessary) if you still have the problems.

**Comment by frank-weinberg** [comment]
I have (a version of) this bug in 1.67.0. It looks like all repos in a directory are listed before submodules of either of them. Example:

Is:
a
a/b
a/c
a/b/d
a/b/g
a/b/d/f
a/c/e

Expected:
a
a/b
a/b/d
a/b/d/f
a/b/g
a/c
a/c/e

I have not had an instance of missing submodules.

**Comment by shaiky88** [comment]
Hi ,

I tested today and I see the sorting issue is resolved with new 1.67
version.

I think I need to update the visible items of submodule from 10 to 20 in
user and workspace settings.
