### ISSUE TITLE
IDE not recognizing loops

### ISSUE THREAD

**Issue by NobilGautam** [microsoft/vscode#148775]
Issue Type: <b>Bug</b>

I am not able to use loops in my code as the IDE wont recognize "for", "do" and "while" keywords

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.33GB free)|
|Process Argv|--crash-reporter-id b3c6be6f-aac5-47ba-9d4b-fefcf6d2eb62|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.14.0
code-runner|for|0.11.7
cpptools|ms-|1.9.8
java|red|1.5.0
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by gjsjohnmurray** [comment]
/gifPlease

What language are you coding in?

**Comment by NobilGautam** [comment]
> 

java

**Comment by NobilGautam** [comment]
![Screenshot (96)](https://user-images.githubusercontent.com/95188574/167015792-63bab5cf-2a96-4722-8e6c-0f99427ceaa2.png)
![Screenshot (97)](https://user-images.githubusercontent.com/95188574/167015805-c5ed7455-739c-4a00-9a2e-f37aa8ed2c14.png)

following are the screenshots of the error... 
![Screenshot (95)](https://user-images.githubusercontent.com/95188574/167015809-d66e7c22-bb0d-488f-99da-6f7724f1e83f.png)
