### ISSUE TITLE
Incorrect grouping of default settings if used an existing namespace

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#14877]
- VSCode Version: Code 1.7.0 (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T14:34:01.691Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-scss|mrmlnc|0.5.0|

---

Steps to Reproduce:

1. Install `vscode-scss` extension
2. Open default settings
3. See `Telemetry` section

![image](https://cloud.githubusercontent.com/assets/7034281/19948384/5dbfc536-a15d-11e6-929c-cc560530a468.png)

**Comment by sandy081** [comment]
@aeschli Looks like we are putting the configuration without title under the last group/title. May be we should have an untitled section for them?

**Comment by aeschli** [comment]
@sandy081 Maybe we can use the extension name?

https://github.com/Microsoft/vscode/blob/master/src/vs/platform/configuration/common/configurationRegistry.ts#L135 is the place for that

**Comment by sandy081** [comment]
@aeschli Fixed this by falling back to `id`.

**Comment by chrmarti** [comment]
Is there anything the extension needs to do to get a proper title?

Marking as verified:
![screen shot 2016-12-08 at 9 53 31 am](https://cloud.githubusercontent.com/assets/9205389/21021271/993fb4be-bd2c-11e6-8053-3cab672dc4c7.png)
