### ISSUE TITLE
Localization support in Notebook Renderer

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#148722]
While polishing the error renderer in Jupyter we found that to support localization in the renderer https://github.com/microsoft/vscode-jupyter/pull/9885, we need to have an extension side code which loads traditional localization bundle from the extension to the renderer. There isn't a straightforward way to have localization support in pure renderer yet. 

Potential solutions we now have for pure renderers:

* Renderers bundle loc files into renderer. This would increase the bundle size
* Introduce renderer API which can help read `package.nls.json` from the extension vsix

cc @connor4312 @mjbvz

**Comment by connor4312** [comment]
Webviews have an identical problem. In my ideal world there is webview API which vscode-nls can hook into 'magically', so from an extension author point of view there's little to no difference between loc in extension code versus webview code.

**Comment by rebornix** [comment]
@TylerLeonhardt can we take this in account when exploring nls for webview?

**Comment by TylerLeonhardt** [comment]
https://github.com/microsoft/vscode/issues/170919 has more info

/duplicate
