### ISSUE TITLE
Sidebar modules in status bar

### ISSUE THREAD

**Issue by lucianmarin** [Microsoft/vscode#14876]
- VSCode Version: 1.7
- OS Version: macOS

The black modules bar is annoying! You could move the switches to the status bar on the left side. Clicking them would disable or enable the sidebar.

An alternative design: take a look at Panic Coda and move the sidebar modules at the top or bottom.

Having the sidebar modules in the status bar is more Visual Studio Code like design.

**Comment by rebornix** [comment]
I don't think we are going to make this kind of change as we have this side bar from the very beginning.

**Comment by lucianmarin** [comment]
But the current sidebar design is really bad. Keeping a bad design just because it was like this from “the very beginning” doesn’t make sense.
