### ISSUE TITLE
mac 12.3.1版本 鼠标滚动掉帧（MAC 12.3.1 Mouse scroll away frames）

### ISSUE THREAD

**Issue by huhan-o** [microsoft/vscode#148768]
Such as the title ，A problem with the latest vscode version

**Comment by huhan-o** [comment]
Issue Type: <b>Bug</b>

Such as the title ，A problem with the latest vscode version

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:47:29.396Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 12, 15|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 4328c3c1-aa8b-4e5d-a28a-6684538ebdab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
project-manager|ale|12.5.0
console-helper|AT-|2.4.25
color-info|bie|0.7.0
ts-snippets|chr|1.1.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
bracket-pair-colorizer-2|Coe|0.2.4
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.6
vscode-html-css|ecm|1.11.0
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vue-snippets|hol|1.0.4
dotenv|mik|1.0.1
vscode-language-pack-zh-hans|MS-|1.66.3
vetur|oct|0.35.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.5
postcode|roh|1.3.9
svg-preview|Sim|2.8.3
guides|spy|0.9.3
code-spell-checker|str|2.1.11
tabnine-vscode|Tab|3.5.45
codelf|unb|11.7.0
vscode-icons|vsc|11.11.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1


</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by Bistard** [comment]
I think you probably meant for `mouse scrolling drops frame`?

**Comment by huhan-o** [comment]
> I think you probably meant for `mouse scrolling drops frame`?

yes

**Comment by Ir1d** [comment]
I also face this issue

**Comment by Ir1d** [comment]
@roblourens why is this completed? How do you solve this?

**Comment by roblourens** [comment]
I have no idea what this issue is about, I posted that it needs more information and nobody provided it. Please open a new issue with complete details if you are having an issue.

**Comment by Ir1d** [comment]
@roblourens What other information do you need besides the info provided by @huhan-o ?
