### ISSUE TITLE
es2022 is not accepted in lib attribute from tsconfig.base.json

### ISSUE THREAD

**Issue by danjor** [microsoft/vscode#148797]
- VS Code Version: 1.26.2
- OS Version: Windows 10
- typescript: 4.6.4

Steps to Reproduce:

Try to set es2022 in lib attribute inside tsconfig.base.ts will raise a warning about value not being part of an enum.

![image](https://user-images.githubusercontent.com/3473673/166925949-a7af7aaa-afa6-4c7d-9df5-9b087db7cac6.png)

**Comment by IllusionMH** [comment]
/question

This is just validation based on schema from SchemaStore and external for this issue tracker
[schema for `tsconfig.json` `lib`](https://github.com/SchemaStore/schemastore/blob/f0936d359adb3539b6fc723ac63cf20bd7fbcac2/src/schemas/json/tsconfig.json#L729-L838)

**Comment by danjor** [comment]
> /question
> 
> This is just validation based on schema from SchemaStore and external for this issue tracker [schema for `tsconfig.json` `lib`](https://github.com/SchemaStore/schemastore/blob/f0936d359adb3539b6fc723ac63cf20bd7fbcac2/src/schemas/json/tsconfig.json#L729-L838)
> 
> There are no actions that can be done in this repo, but you are definitely welcome to submit PR to ScmenaStore repo.

Thanks for the link.
I created an issue there as VSCode is using this schema repo as a dependency.
