### ISSUE TITLE
Notebook custom renderers are not very discoverable if multiple exist

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode#148724]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Author a new VS Code Notebook Renderer using the [official guide](https://code.visualstudio.com/api/extension-guides/notebook#notebook-renderer)
2. According to the description [here](https://code.visualstudio.com/api/extension-guides/notebook#output-types), it should be possible to override MIME types with built-in renderers, e.g.:

> An extension may optionally choose to render "simple" Rich Outputs itself, for instance to add LaTeX support to Markdown outputs.

3. I tried to create a renderer replacing the `text/html` renderer, but didn't realize it was buried under the following UI interface:
![image](https://user-images.githubusercontent.com/8560030/166798372-fcae5ab2-102f-4b59-b40d-cf1817065fd9.png)
![image](https://user-images.githubusercontent.com/8560030/166798111-89325fbb-6fc0-4827-9c0c-680f14e81a0f.png)

For the output renderer I am authoring, I am mainly looking to augment the existing HTML renderer (ie. add a button above the existing output) so it wouldn't make sense to have users manually select it as a renderer option. Would it be possible to either make the renderer more discoverable or add some API to allow for the scenario I'm describing where it's mostly an augmentation and therefore should be shown by default?

Thanks!

**Comment by rebornix** [comment]
Verifier: when following https://code.visualstudio.com/api/extension-guides/notebook#notebook-renderer to create a renderer extension, type in `text/html` for the mimetype.
