### ISSUE TITLE
Git: Support to configure branches which should be protected from direct commits

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148783]
Given we now want to avoid committing to `main` directly, we could have a workspace setting which would have the Git extension warn when the user is about to commit directly on the `main` branch.

Generalizing it, we could have a list of branches which would cause that alert. That alert could guide the user to create a new branch, possibly leveraging https://github.com/microsoft/vscode/issues/148781

**Comment by lszomoru** [comment]
Branch protection has been implemented.
