### ISSUE TITLE
"Signing in to github" 

### ISSUE THREAD

**Issue by mohammedha** [microsoft/vscode#148717]
Hi All

After updating to the latest version 1.66.2, 
When I try to sign in to GitHub then clicking on "Signing in to GitHub" on the status bar to add the OAuth token, it only open the notifications but not prompting for the OAuth token.

<img width="152" alt="2022-05-04_16h40_59" src="https://user-images.githubusercontent.com/4114872/166721311-d589b665-d618-4550-b9e1-697ae17dfbb4.png">

Using the browser authorization works fine when you run VScode as the currently logged in user but I login to windows as a normal user and start VSCode as Admin, using the browser authorization will open VScode as currently logged in user.

<img width="351" alt="2022-05-04_16h57_05" src="https://user-images.githubusercontent.com/4114872/166721852-978079b9-54a4-4cc5-9861-b79e51e7df10.png">

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (49.42GB free)|
|Process Argv|--crash-reporter-id 6c42b971-2072-478a-a83e-eb6646af7707|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-django|bat|1.10.0
vscode-icontheme-nomo-dark|be5|1.3.6
beardedicons|Bea|0.18.0
vscode-tldr|bmu|1.0.0
<img width="152" alt="2022-05-04_16h40_59" src="https://user-images.githubusercontent.com/4114872/166721134-f2750aa7-3945-4ee6-9ff0-bffe783d2e5c.png">

bracket-pair-colorizer-2|Coe|0.2.4
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-PSStackoverflow|Dou|0.0.2
gitlens|eam|12.0.6
vscode-great-icons|emm|2.1.86
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
file-icons|fil|1.0.29
vscode-test-explorer|hbe|2.21.1
vsc-python-indent|Kev|1.15.0
regexp-preview|Lou|0.1.5
rainbow-csv|mec|2.3.0
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
remote-wsl|ms-|0.66.2
azurecli|ms-|0.5.0
powershell|ms-|2022.5.0
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
deepdark-material|Nim|3.3.0
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.16.0
synthwave-vscode|Rob|0.1.11
code-settings-sync|Sha|3.4.3
vscode-zipexplorer|sle|0.3.1
vscode-pester-test-adapter|Tyl|0.0.23
shell-launcher|Tyr|0.4.1
errorlens|use|3.4.2
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.20
vscode-icons|vsc|11.11.0
codetour|vsl|0.0.58
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.13.24

(15 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

nto your clipboard because it was too large to send. Please paste

**Comment by TylerLeonhardt** [comment]
@mohammedha we have added better fallback logic for scenarios like this where the OS prevents us from going back to the correct editor. This is in 1.67 which was released today. Please give it a try.

/duplicate #147104

related: https://github.com/microsoft/vscode/issues/148041

cc @deepak1556
