### ISSUE TITLE
Matching # in regex match in syntaxes json tmlanguage files failing

### ISSUE THREAD

**Issue by dehilsterlexis** [Microsoft/vscode#14874]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Enterprise

The parser for the syntaxes json files not properly handling "#" in the regex match.

Steps to Reproduce:

1.  Put this pattern in the "patterns":
 	{
		"name": "entity.name.type.ecl",
		"match": "\\b#(append|break|declare)\\b"
	},
2. Should highlight "#append" and "#break".... Does not. I tried many variations on the pattern to try an get around the problem but the closest I got was "\\b#append|#break|#declare\\b" which worked for all BUT the first pattern "#append" (#break #declare and the rest to the right worked).

I really need this in the end: "match": "\\b#(?i:(append|break|declare))\\b"

**Comment by GordonSmith** [comment]
Shouldn't that be:  ```#\b(append|break|declare)\b```?

**Comment by dehilsterlexis** [comment]
![11-2-2016 4-32-55 pm](https://cloud.githubusercontent.com/assets/10133951/19946306/150dca92-a11a-11e6-8a3f-a331720a7e23.png)

**Comment by GordonSmith** [comment]
But the regex of ```#\b(append|break|declare)\b``` reads "hash symbol followed by the whole word of either append, break or declare"?

IOW #appends will not match but #append will?

**Comment by dehilsterlexis** [comment]
That works! Dummy me.
