### ISSUE TITLE
Support slashes in Quick open dialog even on Windows

### ISSUE THREAD

**Issue by elisee** [Microsoft/vscode#1487]
I just updated to 0.10.5, thanks for adding path support for quick open dialog (Ctrl+P)!

Even though I'm on Windows, I often use slashes to separate paths, because they are easier to type on my French AZERTY keyboard (backslashes require hitting Alt Gr+8 which breaks the flow of my typing). This is supported basically everywhere (command line, explorer, etc.) so it'd be nice to be able to use them for filtering in the quick open dialog too.

**Comment by bpasero** [comment]
:+1:

**Comment by elisee** [comment]
Thank you so much! :heart:
