### ISSUE TITLE
Terminal File Link Jump to line failed

### ISSUE THREAD

**Issue by sunxfancy** [microsoft/vscode#148765]
Issue Type: <b>Bug</b>

For the output in terminal of any program. If it's a file link with line number in the following format:
XXX.cpp:123
The file link is always jump to the top of the file of XXX.cpp, and can not jump to line 123 as it did before.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:24.808Z)
OS version: Linux x64 5.17.1-3-MANJARO
Restricted Mode: No
Remote OS version: Linux x64 5.17.1-3-MANJARO
Remote OS version: Linux x64 5.13.10-1-MANJARO

<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
docs-view|bie|0.0.10
pythonsnippets|frh|1.0.2
remote-containers|ms-|0.231.6
remote-ssh|ms-|0.78.0
remote-wsl|ms-|0.66.2
gistfs|vsl|0.4.1
doxdocgen|csc|1.4.0
gitlens|eam|12.0.6
copilot|Git|1.15.5815
better-cpp-syntax|jef|1.15.13
vscode-graphviz|joa|0.0.6
language-haskell|jus|3.6.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.1.0
graphviz-interactive-preview|tin|0.2.1
cmake|twx|0.0.17
vscode-markdown-draw|zha|0.1.4

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by meganrogge** [comment]
This is working for me in insider's. Could you include a gif?

**Comment by sunxfancy** [comment]
![vokoscreenNG-2022-05-05_15-30-04](https://user-images.githubusercontent.com/6300305/167035724-04823e2b-9642-4739-8fee-04bca2c4a334.gif)
Sure, by the way, I have already disabled all the extensions.

**Comment by meganrogge** [comment]
could you set log level to debug (via cmd/ctrl shift p in the command palette) and provide me with the log starting with `Opening link...`?

**Comment by sunxfancy** [comment]
Hi Megan, here is the log but I only see this line after clicking the file link. 
[2022-05-06 00:04:27.231] [renderer12] [debug] Opening link {"text":"KleeCommon.cpp:67","bufferRange":{"start":{"x":4,"y":8},"end":{"x":20,"y":8}},"type":3}

**Comment by Tyriar** [comment]
Can repro in 1.66 but not in 1.67, so should be fixed in the latest version
