### ISSUE TITLE
Code Actions in the Problems window UI become cached when the lightbulb is clicked and don't update correctly leading to stale edits

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#148723]
Does this issue occur when all extensions are disabled?: Yes, but the repro requires an extension.

- VS Code Version: 1.66.2 or the latest/today's Insiders.
- OS Version: Windows 11 (I assume other OS's too).

Steps to Reproduce:

1. Install the 1.10.1-dogood5 vsix for the C/C++ extension, which I could send you a link via email internally or maybe post it on our GitHub releases page.
2. Add setting:
```json
    "C_Cpp.codeAnalysis.clangTidy.checks.enabled": [
        "modernize-use-trailing-return-type"
    ],
```
3. Create a test.cpp file with code
```cpp
int main
(){}
```
4. Run the "C/C++: Run Code Analysis on Active File" command via the right-click menu or command palette.
5. Hover over the warning icon in the Problems window and then click the lightbulb to see the "Fix" option -- the bug doesn't repro if this step is skipped, seemingly because this step causes VS Code to cache the soon to be stale code actions.
6. Put your cursor before the `(` and then hit Backspace to delete the newline.
7. Optionally, to verify the correct/expected behavior, click the lightbulb in the document to see that the "Fix" option has been removed, because our extension has removed it in the latest codeAction request from VS Code (code is at https://github.com/microsoft/vscode-cpptools/blob/seanmcm/codeAnalysisFixCodeAction/Extension/src/LanguageServer/Providers/codeActionProvider.ts):
![image](https://user-images.githubusercontent.com/19859882/166746649-e3150db0-ac18-40d4-b1dd-66a11edb6357.png)
8. Repeat step 5, i.e. hover over the warning icon in the Problems window and then click the lightbulb.

Bug: The code action list is stale and has the removed code action still.

![image](https://user-images.githubusercontent.com/19859882/166747598-068531f9-5477-467f-8550-39edadf2461d.png)

If you select the stale "Fix" command invalid code gets generated:

![image](https://user-images.githubusercontent.com/19859882/166747958-eac6681b-e3c4-491d-a0ca-8f01f592b9e7.png)

Our extension may attempt to workaround this bug by updating the code action's edit (and the diagnostic) on document change, but we're not sure yet if that will be sufficient, since vscode could still use the old code action (or we could switch from using the vscode.CodeAction.edit to doing the edit in a command and skipping the invalid edit when the command is invoked).

Another potential fix would be to add support for versioned document edits in the code actions as mentioned in the LSP at https://microsoft.github.io/language-server-protocol/specification#workspaceEdit (we're not using the LSP for code actions and we're not sure if the vscode client would support that if we switched to that).

**Comment by sean-mcmanus** [comment]
Bug #2: I could file this as a separate bug if you want, but it seems like it shares the same root cause due to the lightbulb expansion results being cached and all the repro steps are identical except for 2/3/6 which are modified. I refer to the original bug as `Bug #1`.

1. (Same as Step 1 in `Bug #1`): Install the 1.10.1-dogood5 vsix for the C/C++ extension, which I could send you a link via email internally or maybe post it on our GitHub releases page.
2. (Altered version of Step 2 in `Bug #1`): Add setting:
```json
    "C_Cpp.codeAnalysis.clangTidy.checks.enabled": [
        "cppcoreguidelines-init-variables"
    ],
```
3. (Altered version of Step 3 in `Bug #1`): Create a test.cpp file with code
```cpp
auto main() -> int {
    
    int i;
    return 0;
}
```
4. (Same as Step 4 in `Bug #1`): Run the "C/C++: Run Code Analysis on Active File" command via the right-click menu or command palette.
5. (Same as Step 5 in `Bug #1`): Hover over the warning icon in the Problems window and then click the lightbulb to see the "Fix" option -- the bug doesn't repro if this step is skipped, seemingly because this step causes VS Code to cache the soon to be stale code actions (same as `Bug #1`).
6. (Altered version of Step 6 in Bug #1): Put your cursor on the blank line (above `i` in `int`) and hit Enter.
7. (Same as Step 8 in `Bug #1`): Repeat step 5, i.e. hover over the warning icon in the Problems window and then click the lightbulb.
8. (New step): Optionally, logging or debugging can be used to confirm that no codeAction request is sent from VS Code in step 6 or 7, which occurs if step 5 is omitted, i.e. in `Bug #1` we receive and respond to the codeAction request but the UI isn't updated to use it, while in this case the UI isn't triggering an update request.

Bug: The code action list is stale and has the removed code action still.

![image](https://user-images.githubusercontent.com/19859882/166809928-1eaddf28-cbe5-402c-be5f-96f8ab583d2e.png)

And invoking the Fix code action generates invalid code:

![image](https://user-images.githubusercontent.com/19859882/166810162-b1e89a03-a02b-4bcd-8b54-4359680ac886.png)

As with `Bug #1`, we believe we can attempt to workaround this by switching from using `vscode.CodeAction.edit` to making a decision whether to apply the edit or not in the `vscode.CodeAction.command` (although the UI would still be stale, un-optimal), and possibly sending a new diagnostic with an updated Location/Line may cause VS Code to invalidate its cache and send the codeAction request and show it updated (we can't tell until we implement it).

**Comment by sandy081** [comment]
In problems view, in order to show light bulbs, code actions are requested cached and they get invalidated only when the diagnostic changes, so that we put less traffic on extension host. 

May be I shall not use the cache when user asks for code actions, like clicking on the light bulb
