### ISSUE TITLE
Overlapping UI elements in diff view - Notebook

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode#148814]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.0 - Insiders
- OS Version: 12.3.1

Steps to Reproduce:

1. Throw a large error as the output of a cell in a Jupyter Notebook
2. Examine the diff and see that there are overlapping elements where the error is shown as the changed output.

https://user-images.githubusercontent.com/686963/166968759-812e8a32-821e-4735-a3e0-e3585a50313c.mp4

**Comment by DonJayamanne** [comment]
No longer able to repro, and given that I've resolved a few of these sceen cheese issues earlier this year, I believe its safe to close this.
