### ISSUE TITLE
Unwanted Local User files showing up in the explorer bar

### ISSUE THREAD

**Issue by ClauPred** [microsoft/vscode#148869]
Issue Type: <b>Performance Issue</b>

Hello
I cannot seem to find on the web, or in the settings, how to prevent Visual Studio from adding my local user files and adding them to the explorer bar. Files such as pictures, videos, contacts, etc.
It started happening after I installed Git and also added the Python extension so I am unaware if one of the two or any is the culprit.
I've tried changing the workspace trust settings to prevent the trust of the parent folders, deleting my projects under the Trusted Folders & Workspaces list, uninstalling Visual Studio and Git through windows app settings and also deleting the hidden files on my c drive as well as restarting my computer after each attempt.
Thank you for any assistance

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: Yes

**Comment by ClauPred** [comment]
![Recording 2022-05-06 at 12 46 15](https://user-images.githubusercontent.com/105032570/167207195-6147e089-ed0c-40bc-bc80-0f6ff6f01ab8.gif)

**Comment by dannoe** [comment]
You somehow opened your user folder (``C:\Users\<yourname>\``) in vscode. Just use ``File -> Close Folder`` and you are good to go. 
If you right click inside an folder and use "Open with Code" it will open the whole folder.

**Comment by ClauPred** [comment]
Simple Solution
Yes, I must of clicked on "Open with Code" and did not realize it
Thank you so much
