### ISSUE TITLE
Terminal in VS Code (bash shell) is not responding to commands compared to Mac's Terminal (bash shell)

### ISSUE THREAD

**Issue by Ella6882** [microsoft/vscode#148813]
Does this issue occur when all extensions are disabled?: Makes no difference

- VS Code Version: 1.66.2
- OS Version: 12.3.1 (Monterey)
- Extensions Installed: Docker, HashiCorp Terraform, Terraform

Steps to Reproduce:

1. When running any command (e.g. pyenv, saml2aws, terraform) in the bash shell in VS Code, I get the error "command not found". However, when I run it in my terminal in the bash profile, it works as expected. zsh shell works fine across both VS code and terminal.

`$ saml2aws
bash: saml2aws: command not found

$ pyenv
bash: pyenv: command not found

$ terraform
terraform: command not found`

I have tried reinstalling VS Code, launching it from the terminal, making changes to the settings.json file, but no luck.
The settings.json file currently looks like:
`{
    "workbench.colorTheme": "GitHub Dark",
    "git.autofetch": true,
    "editor.suggestSelection": "first",
    "editor.guides.indentation": true,
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "window.zoomLevel": 4,
    "workbench.editor.enablePreview": false,
    "python.defaultInterpreterPath": "/Users/my_name/.pyenv/versions/3.8.12/bin/python",
    "terminal.integrated.defaultProfile.osx": null,
    "terminal.integrated.inheritEnv": false,
    "terminal.integrated.env.osx": {

		"PATH": "",
    
},
"diffEditor.ignoreTrimWhitespace": false,
"terminal.integrated.shellIntegration.showWelcome": false,
}

**Comment by thetrompf** [comment]
It is because you have set the path variable to empty string, which means the terminal won't find any executables. The PATH environment variable is responsible for telling the terminal where to look for executable. You should ommit it or set it to whatever your normal terminal has set. I'll recommend trying to unset it, as that should lead to vscode inherets the PATH variable value.

**Comment by Ella6882** [comment]
Hi @thetrompf! Sorry, that was added in when experimenting with the settings.json file. It doesn't make a difference if I omit it or not.

**Comment by thetrompf** [comment]
If you open your normal terminal and run `echo $PATH` then copy the value into the place where specified the PATH env variable before, just to see if that makes any difference.

**Comment by meganrogge** [comment]
pretty sure this is the issue:

"terminal.integrated.defaultProfile.osx": null

**Comment by Ella6882** [comment]
Hi @meganrogge! "terminal.integrated.defaultProfile.osx" was set to another value but again, it made no difference. @thetrompf that worked! Thank you so much!!
