### ISSUE TITLE
Properly support commonmark angle bracket syntax in links 

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#148818]
The angle bracket syntax described in [Example 488](https://spec.commonmark.org/0.30/#example-488) of the commonmark spec is not supported:

1. Syntax highlighting is wrong:
<img width="149" alt="image" src="https://user-images.githubusercontent.com/2845433/166980641-9350f905-9626-4df2-996b-4eb9958d1942.png">

2. Url is not linked and cannot be followed by cmd-clicking on it. 

- VS Code Version: 1.66.2
- OS Version: MacOS Big Sur

Steps to Reproduce:

1. Create a markdown file `My Note.md`
4. Create a new markdown file in the same folder with this link as content `[](<My Note.md>)`.

**Comment by memeplex** [comment]
Related issue: https://github.com/microsoft/vscode/issues/136073

**Comment by memeplex** [comment]
With the superb features added in April 2022 (find header/file references, update all links after renaming, etc) VSCode is providing a modern wiki environment OOB. Short of supporting the non-standard `[[...]]` wikilink syntax, this feature would allow to reference pages with spaces in their name, which are rather usual in wikis.

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode-markdown-tm-grammar/commit/2f9bda284d391f97982f7932ba49eb89b2ac83b1 and #151178
