### ISSUE TITLE
Typo in changelog for file nesting

### ISSUE THREAD

**Issue by Kampfkarren** [microsoft/vscode#148847]
Issue Type: <b>Bug</b>

File nesting changelog suggests `"*": "${basename}.*.${dirname}"` as a useful possibility. This does not properly capture what it expects to capture (such as file.spec.js). It instead should be `"*": "${basename}.*.${extname}"`.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by JacksonKearl** [comment]
Good catch, thanks.
