### ISSUE TITLE
Terminal panel pops up after closing interactive window

### ISSUE THREAD

**Issue by amar-0** [microsoft/vscode#148899]
Issue Type: <b>Bug</b>

When closing the Python interactive window the Terminal panel shows itself.

![terminal](https://user-images.githubusercontent.com/66088666/167117604-78151894-3a7d-4afc-ae9c-c628a0db7386.gif)

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.32.0
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1001271738
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-repositories|ms-|0.6.0
markdown-all-in-one|yzh|3.4.3

</details>

**Comment by rebornix** [comment]
@sbatten what's the recommended approach to debug this? I'm not sure who is opening the terminal (but I know it's not notebook or iw as it's the editor tab close button)

**Comment by sbatten** [comment]
I debugged this, and determined that when the interactive window is closed, it updates a context key which hide a view container in the panel. this incorrectly triggers the panel to show.
