### ISSUE TITLE
🐛 `Go To Definition` mouse action not active for `@` in TypeScript imports

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [microsoft/vscode#148874]
Issue Type: <b>Bug</b>

It seems that when vscode is facing module targets that contain an `@` character, the hover cursor for `Go To Definition` does not include the `@` character. So the hover in the example will only show when the mouse is over `nestjs/common` instead of  `@nestjs/common`.

Example:
`import { Module } from '@nestjs/common';`

VS Code version: Code - Insiders 1.67.0-insider (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:03:42.454Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.71GB free)|
|Process Argv|--log-net-log=netlog.json --ignore-certificate-error --crash-reporter-id 5f9e326c-2a01-458b-95a4-f411641d6f56|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-base64|ada|0.1.0
iconify|ant|0.3.2
icons-carbon|ant|0.2.4
smart-clicks|ant|0.0.13
apollo-workbench|Apo|2.2.1
vscode-apollo|apo|1.19.10
atlascode|atl|2.10.12
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
typescript-notebook|don|2.0.6
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.86
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
copilot|Git|1.17.5850
remotehub|Git|0.31.2022050502
vscode-pull-request-github|Git|0.43.2022050511
gitlab-workflow|Git|3.43.1
vscode-graphql|Gra|0.4.4
dance|gre|0.5.9
output-colorizer|IBM|0.1.2
prettier-sql-vscode|inf|0.3.0
vscode-peacock|joh|4.0.1
volar|joh|0.34.11
vscode-typescript-vue-plugin|joh|0.34.11
i18n-ally|lok|2.8.1
ts-error-translator|mat|0.3.0
fluent-icons|mig|0.0.17
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
jupyter|ms-|2022.5.1001271006
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
remote-repositories|ms-|0.5.2022050501
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
incrementor|nms|1.0.3
angular-console|nrw|17.16.0
vscode-jest|Ort|4.5.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.16.0
polacode|pnp|0.3.4
inline-sql-syntax|quf|2.10.3
vscode-yaml|red|1.7.0
vscode-coverage-gutters|rya|2.9.1
sonarlint-vscode|Son|3.4.1
classify-ts-import|Stu|1.0.1
sass-indented|syl|1.8.19
teamhub|Tea|15.0.6
win-ca|uko|3.5.0
intellicode-api-usage-examples|Vis|0.1.1
vscodeintellicode|Vis|1.2.20
vscode-conventional-commits|viv|1.24.1
vscode-icons|vsc|11.11.0
change-case|wma|1.0.0
type-challenges|YRM|1.1.0
vitest-explorer|Zix|0.1.23

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebugcf:30475217
vscaat:30438846
vsclangdf:30480126

```

</details>

**Comment by gjsjohnmurray** [comment]
Please edit the title of your issue so it tells us what it's about.

**Comment by sschneider-ihre-pvs** [comment]
oops forgot to hit save
