### ISSUE TITLE
"editor.find.addExtraSpaceOnTop": true has no effect

### ISSUE THREAD

**Issue by DanKaplanSES** [microsoft/vscode#148890]
Issue Type: <b>Bug</b>

I don't see any difference between the setting `"editor.find.addExtraSpaceOnTop": true` and `"editor.find.addExtraSpaceOnTop": false`. Either way, typing `ctrl+f` in my editor puts the search on top of the first line, instead of making space above the first line. 

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
The extra space is available for you to scroll up into if you want to. Scrolling doesn't happen automatically.

**Comment by DanKaplanSES** [comment]
Ah, good to know. I've probably done that on accident without noticing. Thanks.
