### ISSUE TITLE
April 2022 (version 1.67) why theme color change

### ISSUE THREAD

**Issue by hug-love** [microsoft/vscode#148867]
<img width="482" alt="image" src="https://user-images.githubusercontent.com/42996632/167062265-c7255b33-8368-4a4c-859b-322f4e7af180.png">
the color is very very very very very very very very bad. what can I do? I don't like it at all. It reminds me of death

**Comment by Drakota** [comment]
Bracket pair colorization has been enabled by default, just disable it with `"editor.bracketPairColorization.enabled": false,` in your settings.json

**Comment by hug-love** [comment]
Problem solved. Thank you very much 😉

**Comment by hug-love** [comment]
> Bracket pair colorization has been enabled by default, just disable it with `"editor.bracketPairColorization.enabled": false,` in your settings.json

Problem solved. Thank you very much 😉
