### ISSUE TITLE
VS Code View Blurry

### ISSUE THREAD

**Issue by Zetronentabak** [microsoft/vscode#148886]
Hi there, I've been getting these kind of frozen looking feature on VScode, every time I move my cursor on the surface it keeps getting worse. Anyone with who has this problem please help me out, I really would like to know a solution to fix this please, its been giving me a hard time to focus when I'm coding.

![VS_bug_1](https://user-images.githubusercontent.com/18098639/167100503-2bca2ac0-ebd3-40e4-97a7-eda5e698cb79.png)

**Comment by gjsjohnmurray** [comment]
Please try launching VS Code from a Windows command prompt (not a VS Code Terminal), adding the --disable-gpu switch:
```
code --disable-gpu
```

**Comment by kamenminkov** [comment]
If you're using an Nvidia GPU, this is kind of a known issue - I've experienced it myself.

You have to go into NVIDIA Control Panel -> 3D Settings -> Manage 3D settings, then either look for "Image Scaling" or "Image Sharpening" (differs by driver version) and disable those.

**Comment by Zetronentabak** [comment]
> If you're using an Nvidia GPU, this is kind of a known issue - I've experienced it myself.
> 
> You have to go into NVIDIA Control Panel -> 3D Settings -> Manage 3D settings, then either look for "Image Scaling" or "Image Sharpening" (differs by driver version) and disable those.

Wow it works! thank you so much for your help. I was struggling for so long :D
