### ISSUE TITLE
As per the new release the vs code supports multiline comment but it is not working on my vs code

### ISSUE THREAD

**Issue by abhijitchikane** [microsoft/vscode#148828]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.67
- OS Version:windows 10

Steps to Reproduce:

1. select the multiple lines
2. try to get the + button in the gutter line(but the plus button is not visible as shown in release notes)

is there something I am missing?
and yeah one more thing
can you please give us way to select the color from the multiple selection for the new bracket pair colorization default setting, cause it would be great to have this as I don't like some of the color

Thank you!!!

**Comment by gjsjohnmurray** [comment]
AFAIK the comments feature shown in the 1.67 release notes only shows up in the UI if an extension is using the [Comments API](https://code.visualstudio.com/updates/v1_35#_comments-api). In the release notes video it's [GitHub Pull Requests and Issues](https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github).

**Comment by gjsjohnmurray** [comment]
> and yeah one more thing

Please don't combine unrelated issues.

**Comment by abhijitchikane** [comment]
Thanks
