### ISSUE TITLE
Enable user level setting when folder or workspace opened and extension is disabled at workspace level

### ISSUE THREAD

**Issue by Harshad667** [microsoft/vscode#148891]
Currently having issue in vscode extension enable disable behaviour
When workspace is opened and vscode extension disabled at workspace level then it is disabling at both user and workspace
Following are steps to reproduce this issue
1. Open vscode and add one or more folder and save workspace
![image](https://user-images.githubusercontent.com/105044071/167103842-9fc5f83f-8545-456d-a18f-dc0ef072e531.png)

2. now disable workspace level setting it is disabling both user and workspace setting as shown in image
![image](https://user-images.githubusercontent.com/105044071/167103929-b3c426cb-371e-4595-a947-e54b22082b2e.png)
![image](https://user-images.githubusercontent.com/105044071/167104033-2cabcfda-2a15-4b9d-9634-4a0d77d415a8.png)
Expected behaviour
It should allow extension to be enable at user level when extension is disabled at workspace level

**Comment by sandy081** [comment]
> It should allow extension to be enable at user level when extension is disabled at workspace level

Settings and Extensions are different. Disabling an extension in workspace will not load extension in that workspace and hence you do not see any settings of that extension in Settings UI in that workspace. To configure settings of an extension in a window, the extension has to be enabled. So please open another window to edit settings of that extension.
