### ISSUE TITLE
'Format document' and 'go to definition' not working in Javascript file

### ISSUE THREAD

**Issue by dyliew** [Microsoft/vscode#14887]
- VSCode Version: 1.7.0
- OS Version: Windows 10

Steps to Reproduce:

1. open any js file
2. mess up with the indentations and try to use 'format document'

1. create a function and use it in the code
2. using 'go to definition' doesn't bring the cursor to the function

Thanks a lot

**Comment by rebornix** [comment]
@dyliew did it work before you upgrade to 1.7.0, is it a valid javascript project?

**Comment by waderyan** [comment]
@dyliew thank you for opening this issue. Can you provide a code sample we can test with?

**Comment by dyliew** [comment]
Hi there, I tried it on TS and html and they still worked. It only happened on JS.

I've reverted my VSCode version to 1.6.1 due to work and cannot replicate this on my machine anymore.

Basically, something like this would be able to replicate this issue (as of my testing yesterday).

`function doSomething() {`
`console.log('something is done'); // there's no indentation here (alt + shift + f doesn't work)`
`}`

`doSomething(); // go to definition (F12) doesn't move the cursor`


Thanks for looking into this.

**Comment by dyliew** [comment]
**Just updated to 1.7.1 and they are still there

**Comment by waderyan** [comment]
@dyliew thank you for looking into this. Please reopen if you see it again.

**Comment by dyliew** [comment]
Nice to see them fixed in 1.7.1

Thank you all very much
