### ISSUE TITLE
Release notes did not pop up on update to 1.67.0 (user setup)

### ISSUE THREAD

**Issue by dannoe** [microsoft/vscode#148884]
Does this issue occur when all extensions are disabled?: I don't know. It is too late.

- VS Code Version: Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open vscode
2. Update was installed but no changelog/release notes were opened.

**Comment by gjsjohnmurray** [comment]
What is your `update.showReleaseNotes` setting?

**Comment by joaomoreno** [comment]
Can you try installing 1.66, then 1.67 again and confirm that indeed you don't get a release notes prompt? Is it possible that the notes actually appeared but an extension might've closed the editor?

**Comment by dannoe** [comment]
After reinstalling 1.66 and using the update function it is indeed showing the patch notes again. 

> Is it possible that the notes actually appeared but an extension might've closed the editor?
Possible
