### ISSUE TITLE
HTML chars are wrongly displayed

### ISSUE THREAD

**Issue by aloisdg** [Microsoft/vscode#14880]
- VSCode Version: 1.7.0
- OS Version: Windows 10 (Version 1607 (OS Build 14393.351)

Steps to Reproduce:

1. clone https://github.com/aloisdg/Summary2Pages.git
2. open it with vscode

The problem may come from @Ionide.

I should see `string -> unit` but I get `string -&gt; unit`:

![bug-vscode](https://cloud.githubusercontent.com/assets/3449303/19948694/3f82918e-a14e-11e6-9021-e3d1538176e3.PNG)

[on ionide](https://github.com/ionide/ionide-vscode-fsharp/issues/266)

**Comment by Krzysztof-Cieslak** [comment]
Caused by additional escaping I've added on plugin side ( to handle escaping before https://github.com/Microsoft/vscode/pull/13244 was released in Stable).

Can be closed.

**Comment by aloisdg** [comment]
Thank you for your work!
