### ISSUE TITLE
Polish shell integration messaging

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#148839]
Action items after a discussion:

- [x] Explain when shell integration may fail to activate in the setting docs, ie. complex prompt command for example (debug trap specified?)
- [x] Remove in-terminal shell integration disabled warning
- [x] Hide shell integration activated message in favor of an item in the command decoration? How does this work? Learn more?
  - The reason we had the activated message to begin with was to disclose to people that we have performed some script injection. We believe it's sufficient now just showing the rich command decorations (and the terminal tab hover) as an indicator, also with documentation on the website that explains how the terminal works.
- [x] Remove capabilities from tab hover, only say "Shell integration activated" or "Shell integration failed to activate"

**Comment by meganrogge** [comment]
We should also add a section in the docs describing which args are supported

**Comment by meganrogge** [comment]
Made this a feature request because think it should get tested with a TPI

**Comment by joyceerhl** [comment]
Should the skipped/empty command decoration also have a 'How does this work' menu item? 
![image](https://user-images.githubusercontent.com/30305945/171471186-06e8c22e-547c-419b-8d21-5d52a9ff911c.png)
