### ISSUE TITLE
Intellisense causing performance issues

### ISSUE THREAD

**Issue by alexandretperez** [Microsoft/vscode#1488]
I just update to the latest version, and now when I'm writing something like element.addEventListener("input", handler, false), the intellisense causes an increase of at least 12% on the CPU, causing lags when typing.

I do not experienced this issue on the previous version.

**Comment by irakliy81** [comment]
+1

Intellisense is noticeably slower for me as well - it was fine before the upgrade to the latest version. I'm working with TypeScript projects.

**Comment by dbaeumer** [comment]
0.10.6 ships with a new version of the tsserver (e.g. 1.7.5). The last VSCode version ship 1.6.x. Moving to the TypeScript team to investigate.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6340
