### ISSUE TITLE
Collapse a tree view when clicking a button

### ISSUE THREAD

**Issue by asifkareem03** [microsoft/vscode#148875]
Is it possible to minimise the tree-view when a button is clicked

eg:- I want Minimise the **Firmware Layout View**  when 'Locate in Project View' is clicked.
Any one have any idea about this

<img width="960" alt="Screenshot (17)" src="https://user-images.githubusercontent.com/48887516/167074516-e0b8aea7-4eef-483b-ac7e-e9f5844bbc57.png">

**Comment by gjsjohnmurray** [comment]
I think this would need to be done by the author of the extension which contributes those views and that menu option. But until #88219 is addressed there probably isn't a way for them to achieve what you want.

**Comment by alexr00** [comment]
@gjsjohnmurray is correct. First we would need to have https://github.com/microsoft/vscode/issues/88219, then the author of the extension would need to use it.
