### ISSUE TITLE
[Debug console] Press Enter evaluate an expression instead of triggering autocomplete

### ISSUE THREAD

**Issue by mbelsky** [microsoft/vscode#148853]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.0-insider
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:09:01.690Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0

Steps to Reproduce:

1. Start debugging
2. Click on input of Debug console
3. Type `cons`
4. Wait for autocomplete options
5. Select `console`
6. Press Enter

Expected behaviour: Debug console input's value changes to `console`.
Actual behaviour: Debug console evaluates `cons` expression.

Screen recording is attached.

https://user-images.githubusercontent.com/3923527/167032836-bd13256d-5727-454f-bde2-97f86095c272.mov

**Comment by mbelsky** [comment]
I'd like to work on this issue. Could you please tell me what is the right place to start debugging and fixing it?

**Comment by roblourens** [comment]
You just need the setting `debug.console.acceptSuggestionOnEnter`

This is why there is a hint that you need to press tab to accept the suggestion.
