### ISSUE TITLE
Use hint message/button to indicate that "file to include/exclude" is set for the search panel

### ISSUE THREAD

**Issue by ppggff** [microsoft/vscode#148866]
Currently, if the user sets something to the "file to include/exclude" fields of search panel, these fields will alway expand to indicate there is non-default settings. Then, after updating an extension, restart computer, user must click the "toggle search details" button to save the screen space. (try to request in issue #144808)

To save the screen space and avoid repeated operations (click the "toggle search details" button) after each reload, it's better to use hint message/button to indicate that "file to include/exclude" is set for the search panel. For example:

* hint message
   * Display a hit text in the search box (addition to 'Search (↑↓ for history)')
   * Show some summary information with the search result

<img width="537" alt="Screen Shot 2022-05-06 at 11 07 33 AM" src="https://user-images.githubusercontent.com/2892417/167061332-2a92369e-099a-430b-af4d-1d0036740867.png">

<img width="537" src="https://user-images.githubusercontent.com/2892417/167062121-8fecc630-53bc-440e-9dac-1df44968ea66.png">

* button

<img width="537" alt="Screen Shot 2022-05-06 at 11 14 44 AM" src="https://user-images.githubusercontent.com/2892417/167061371-b79af9ef-ba01-4176-876b-9e2e482a1695.png">

**Comment by roblourens** [comment]
Thanks for the suggestions. I'm not that interested in inventing new UI to solve this. I think this is too much visual noise, especially for long values, and duplicates something that is already on the screen. In general I feel the same way as I did in the earlier issues.

**Comment by ppggff** [comment]
> Thanks for the suggestions. I'm not that interested in inventing new UI to solve this. I think this is too much visual noise, especially for long values, and duplicates something that is already on the screen. In general I feel the same way as I did in the earlier issues.

Thanks. Please try to put something in the 'file to include' input box, and leave it here for couple days. It is really annoying...

> too much visual noise
compare to 2 full length input box? There should be a better way to indicate 'file to include/exclude', may be I need to try more.

> duplicates something that is already on the screen
where? if the hint message/button is implemented, that 2 full length input box should be hidden away.

**Comment by ppggff** [comment]
for user who want a simple fix:
```
sed -i _bak -e 's/&&this.toggleQueryDetails(!0,!0,!0),/\&\&0\&\&this.toggleQueryDetails(!0,!0,!0),/' "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js"
```

`workbench.desktop.main.js_bak` is a backup.

ignore the warning message after restart.
