### ISSUE TITLE
Extension disabled due to trust, but in trusted workspace

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#148872]
Open the DotNet development container sample. Install Ionide extension. See:

<img width="978" alt="image" src="https://user-images.githubusercontent.com/8586769/167067222-ac89e12f-b406-40f4-b6eb-d77ae4605139.png">
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/8586769/167067231-ae5c9752-8385-459f-9982-b2a057228f69.png">

**Comment by JacksonKearl** [comment]
Once I manually enable (`Enable (Workspace)`), extension contributions appear, but the disabled message remains: 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/8586769/167067448-3f0366cb-2e63-4b06-a847-0042464a0461.png">

**Comment by sandy081** [comment]
@lszomoru Please do initial investigation and let me know if there is anything that needs my involvement.

**Comment by lszomoru** [comment]
I am unable to repro this issue with the latest version of VS Code Insiders.
