### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#148861]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?
![166878598-e373a532-9c06-4cc4-b92b-99da8133c9b0](https://user-images.githubusercontent.com/26390254/166881665-f9423722-3b51-46da-9c3c-fcbc81aea1eb.png)

from https://github.com/microsoft/vscode/issues/147846

after testing with different senario, found that this problem is from jupyter extension.
reproduce:

1. install vscode
2. install python extension (this will also brings other extensions in screenshot)
3. open `FoldBug.ipynb`.

After that everythings are Ok, but after install a python interpreter in system and restart vscode, CPU will never goes down.

### VS Code Version

Version: 1.67.0-insider (user setup) Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47 Date: 2022-05-04T12:03:42.454Z

### Jupyter Extension Version

v2022.4.1001252103

### Running Jupyter locally or remotely?

Local

**Comment by byehack** [comment]
did you installed Python extension and set kernel?
try restart vscode.

**Comment by rchiodo** [comment]
You might also try running this:

1. Start VS code
2. Open notebook.
3. Uncollapse all the collapsed sections. 
4. See that CPU usage goes down
5. Run 'Developer: Show Running Extensions'
6. Click on 'Start Extension Host Profile', it should ask you to reload VS code
7. Restart VS code
8. Open notebook
10. Wait for CPU to stop (Python Extension will be discovering interpreters)
11. Start the extension host profile again
12. Repro the folding problem
13. Stop the profile.
14. Upload the profile here. 

Somebody blogged about the same thing here if that wasn't clear:
https://www.nicoespeon.com/en/2019/11/fix-vscode-extension-performance-issue/

That should at least indicate if it's an extension problem or not.

**Comment by byehack** [comment]
[CPU-20220507T050813.577Z.zip](https://github.com/microsoft/vscode/files/8644503/CPU-20220507T050813.577Z.zip)

**Comment by byehack** [comment]
maybe related to https://github.com/microsoft/vscode/issues/148762

**Comment by byehack** [comment]
still happens after latest insider.

https://user-images.githubusercontent.com/26390254/167534295-f34df9b4-9c10-4c1b-8b9f-34d69224e45a.mp4

**Comment by byehack** [comment]
lets track this issue in https://github.com/microsoft/vscode/issues/151252
