### ISSUE TITLE
Takes a hell lot of time during compilation.

### ISSUE THREAD

**Issue by ykboss** [microsoft/vscode#148896]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

Compily normal C++ code with minGW compiler is very slow. I am really frustrated with this . Kindly resolve my Issue. My laptop has 8GB ram with i5 11 gen processor, still it is very slow.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.75GB (2.59GB free)|
|Process Argv|--crash-reporter-id acb54b62-1dc4-49fb-9bd7-643a76905356 --inspect-extensions=38828 --crash-reporter-id acb54b62-1dc4-49fb-9bd7-643a76905356|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	 15976	code main
    2	    87	  5424	   issue-reporter
    0	   109	  7024	   shared-process
    0	    81	 10808	     ptyHost
    0	     6	  5068	       console-window-host (Windows internal process)
    0	    59	 15860	       C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    78	 13308	     fileWatcher
    0	   143	 14760	   extensionHost
    0	    28	  9224	     "c:\Users\Yogesh Kumar Pandey\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\bin\cpptools.exe" Helloworld
    0	    10	  4648	       console-window-host (Windows internal process)
    0	    36	 15820	       "c:\Users\Yogesh Kumar Pandey\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64/bin/cpptools-srv.exe" 9224 {C0F81F80-516A-425F-962B-56EC5FCA382D}
    0	    58	 16048	   crashpad-handler
    0	   181	 16148	   gpu-process
    0	    61	 16188	   utility-network-service
    0	   199	 16268	   window (max.cpp - Helloworld - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (max.cpp - Helloworld - Visual Studio Code)
|    Folder (Helloworld): 7 files
|      File types: json(2) cpp(2) exe(2)
|      Conf files: launch.json(1) tasks.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.7
cpptools|ms-|1.9.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847

```

</details>

**Comment by the-exodus** [comment]
If you build the same project by invoking g++ from a terminal instead of through vscode it will take exactly as long. The compilation isn't performed by vscode, it just invokes mingw through your defined build action.
