### ISSUE TITLE
Flooding npm with @types package requests

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#14889]
- VSCode Version: 1.7.0

Reported by npm folks. Seems to be triggered by the automatic type acquisition in TS.

**Comment by seldo** [comment]
I gave a response from npm over on HN, and rather than duplicate it I'll just link: https://news.ycombinator.com/item?id=12861093

**Comment by dbaeumer** [comment]
@chrmarti we discussed this in the meeting today and before we don't have a fix in the tsserver available we decided to turn off ATA completely. That means users can't turn it on to avoid that too many users for enable it and cause another round of problems.

**Comment by kevinSuttle** [comment]
Outstanding response to this, Code team. 

In the interim, is it possible to ship a build with everything in 1.7 excluding the Intellisense issue?

**Comment by weinand** [comment]
@kevinSuttle a 1.7.1 build is in preparation...
