### ISSUE TITLE
Allow to move debug pane into title bar

### ISSUE THREAD

**Issue by generikvault** [microsoft/vscode#148879]
I would like to drop the debug pane in the title bar of the vs code window.

![grafik](https://user-images.githubusercontent.com/31845534/167088595-9cac4f5d-9d63-4437-acad-3a597440c647.png)

**Comment by gjsjohnmurray** [comment]
Interesting idea. Meanwhile you may like to try this extension:

https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-statusbar-debugger

**Comment by roblourens** [comment]
There are some other options, see `debug.toolBarLocation`. But I don't think we will be able to get it in the title bar - we are in the process of trying to fit more stuff in the title bar, and there isn't necessarily a lot of room
