### ISSUE TITLE
Remote Containers: Shell integration cannot be activated due to complex PROMPT_COMMAND: prompt;history -a

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#148871]
Tried opening the C# remote container sample, see ugly warning on every terminal. Ideally we'd not be broken here, but at minimum maybe only show the error once? 

<img width="751" alt="image" src="https://user-images.githubusercontent.com/8586769/167066782-ef9a67d6-9f13-4450-860d-7942bdc9724b.png">

**Comment by meganrogge** [comment]
Will
Be fixed by #148848

**Comment by meganrogge** [comment]
Curious about why that prompt command would be happening for a remote container 🤔. Where is that set?

**Comment by Tyriar** [comment]
@meganrogge different containers are based on different Linux distros, it's up to the distro how the shells are setup

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/171967443-2c099020-9366-4792-9500-e272ca5702ba.png)

looks good
