### ISSUE TITLE
Show all Symbols: Partial matching is not supported

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode#148833]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.0 Stable
- OS Version: Windows 11

Steps to Reproduce:

1. Create a .md file, add a header `# test test`
2. Try ⌘T, type `est`
3. 1.66.2: works fine
![屏幕截图 2022-05-06 025700](https://user-images.githubusercontent.com/16591303/167007662-06aea786-7c88-4f67-8436-edc276524a00.png)
4. 1.67.0: No matching workspaces symbols
![屏幕截图 2022-05-06 025820](https://user-images.githubusercontent.com/16591303/167007711-07d9f1ef-a682-4388-b5f2-53ba69c35769.png)

**Comment by mjbvz** [comment]
@jrieken I confirmed that markdown returns the workspace symbols in this case. They then seem to be filtered out on the VS Code side

**Comment by liyuhang1997** [comment]
https://user-images.githubusercontent.com/16591303/167020352-e6e5f15a-e89e-4d7a-a4b7-c6efd1a791e8.mp4

**Comment by jrieken** [comment]
This is a regression from https://github.com/microsoft/vscode/commit/368c39cd7a884f22fa21948e941babddafe186cb. I have changed how `fuzzyScore` is configured and made the wrong adoption here...
