### ISSUE TITLE
VS Code 1.7 Hangs on Release Notes page

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#14884]
- VSCode Version: Code 1.7.0 (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T14:34:01.691Z)
- OS Version: Windows_NT ia32 10.0.14955
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|cpptools|ms-vscode|0.9.2|
|PowerShell|ms-vscode|0.7.2|
|rewrap|stkb|0.6.2|

---

Steps to Reproduce:

1. Read release notes page for 1.7 in VS Code for multiple minutes.
2. VS Code Release Notes: 1.7 page freezes.
3. (Sometimes:)
    1. Modal dialog comes up saying the page has stopped responding.
    2. After dismissing the dialog, VS Code remains responsive but page is still not responsive.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by dilijev** [comment]
@joaomoreno no proxy

**Comment by joaomoreno** [comment]
Does it happen if you read a Markdown file preview for multiple minutes too?

**Comment by dilijev** [comment]
@joaomoreno I'll open one up and see. This doesn't seem to repro consistently so I'll only be able to say for sure if it actually happens.

**Comment by Jussif** [comment]
@dilijev  Could you solve this issue? One I update the VS Code program the pages just stopped working.

**Comment by dilijev** [comment]
I haven't had a problem in a while. I'll reopen this issue if I encounter it again.
