### ISSUE TITLE
Shortcut initiated selection occurrence indicators are not cleaning up

### ISSUE THREAD

**Issue by tomasklaen** [microsoft/vscode#148893]
VS Code: 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)

Since this update (also tested on clean Insiders), if a variable is selected using the "editor.action.addSelectionToNextFindMatch" shortcut (`Ctrl+D` in my case), the occurrence indicators of it don't clean up when selection is canceled by cursor navigating away from it.

Here is how it works with a mouse (correct):

![occurences_cursor](https://user-images.githubusercontent.com/47283320/167105871-93b9b677-dce3-43eb-ba33-3f0b660f22ad.gif)

And with a shortcut (stay forever):

![occurences_shortcut](https://user-images.githubusercontent.com/47283320/167105936-48c1a5e8-f781-4d4e-92a6-75c8e3f84305.gif)

They won't clean up even if I select a different variable, the indicators are just added to the previous ones.

They only disappear if I switch editor to a different file and come back.

**Comment by alexdima** [comment]
fyi @hediet this is also caused by `deltaDecorations` recursing i.e. https://github.com/microsoft/vscode/issues/148423

**Comment by mreza0100** [comment]
Would you like to release a patch?
This bug is so annoying!!!
