### ISSUE TITLE
vscode extension test run modifies package.json after 1.67.0

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#148975]
Our presubmit tests started to fail consistently since our test setup picked up code 1.67.0 yesterday.
https://github.com/golang/vscode-go/issues/2230

Our test is basically doing

* first, run [extension tests](https://github.com/golang/vscode-go/blob/master/test/runTest.ts) written with `runTests` from `@vscode/test-electron`
* after the extension tests succeed, run a check on the consistency between our `package.json` file and documentation/settings info.

After running the extension tests with 1.67.0, it looks like the second step that involves reading package.json sees a differently formatted package.json. Actually, it's not only a differently formatted package.json, but it includes a new `"__metadata"` property (`id`, `publisherId`, ...) at the end. 

The test passes if I make the extension tests to use 1.66.2.

We can work around by arranging our presubmit test order or rewriting our `package.json` test logic to handle this.
But, we want to understand what is going on behind the scene and why this package.json modification is necessary.

Thanks!

**Comment by connor4312** [comment]
@sandy081 this looks suspicious...

https://github.com/microsoft/vscode/blob/e09e27e716073e7cd7d3a2aaf5860380b851efb9/src/vs/platform/extensionManagement/common/extensionsScannerService.ts#L229-L241

**Comment by sandy081** [comment]
This is designed and expected. It is the metadata VS Code stores per extension while installing that can be used later for other features like updating etc.,

So I would recommend your extension to handle this.

**Comment by andschwa** [comment]
@sandy081 this has started breaking our extension's tests without warning, and moreover, the way it writes to `package.json` it's modifying the whole file (looks like whitespace changes).

**Comment by andschwa** [comment]
@hyangah how have you gone about working around this breaking change? I'm trying to get a release out myself and am suddenly blocked 😭

**Comment by andschwa** [comment]
Whelp, something else went on that broke my tests, but definitely noticed this too and will need to be careful about not committing the reformatted `package.json`.

**Comment by andschwa** [comment]
I'm currently reverting it. Would love to know if we should do otherwise.

**Comment by sandy081** [comment]
Reopening this to investigate if there is something changed on VS Code while running extension tests

**Comment by remcohaszing** [comment]
I wanted to re-report this issue, because it was previously misunderstood and closed. Of course I won’t now this is open, but I already typed out reproduction steps. Perhaps they help.


Steps to Reproduce:

1. Setup a git repository (this makes the issue more clear)
   ```sh
   mkdir vscode-bug
   cd vscode-bug
   git init
   ```
2. Create a minimal VSCode extension with a test. The issue becomes more apparent if an existing extension name / publisher is used.

   **package.json**
   ```json
   {
     "name": "vscode-eslint",
     "publisher": "dbaeumer",
     "scripts": {
       "test": "node test.mjs"
     },
     "dependencies": {
       "@vscode/test-electron": "^2.0.0"
     }
   }
   ```

   **test.mjs**
   ```js
   #!/usr/bin/env node
   import {runTests} from '@vscode/test-electron'

   await runTests({
     extensionDevelopmentPath: new URL('.', import.meta.url).pathname,
     extensionTestsPath: new URL('index.test.js', import.meta.url).pathname
   })
   ```

   **index.test.js**
   ```js
   module.exports.run = () => new Promise((resolve) => {
     // The error can be reproduced more consistently if test runs take longer
     setTimeout(resolve, 10_000)
   })
   ```

   **.gitignore**
   ```ignore
   node_modules/
   .vscode-test/
   ```
3. Install and commit
   ```sh
   npm install
   git commit -a .
   ```
4. Now we actually reproduce the bug. Run the extension tests
   ```sh
   npm test
   ```

Note that running tests has modified `package.json`. Formatting is changed to use tabs, the final newline is stripped, and publisher metadata is added to the file.

**Comment by sandy081** [comment]
To verify:

- Create some hello world extension and open it package.json and change the name and publisher to an extension that already exists in Marketplace. Eg: 

```json
{
  "name": "vscode-eslint",
  "publisher": "dbaeumer"
}
```

- Quit Code Insiders and Start from CLI with following arguments `code-insiders --extensionDevelopmentPath <path-to-above-hello-world-extension> --user-data-dir <path-to-new-user-data-dir> --extensions-dir <path-to-new-extensions-dir>`
- Make sure hello world extension's package.json is **not** updated with `__metadata` property

**Comment by ArturoDent** [comment]
This looks related to https://stackoverflow.com/questions/72983445/vscode-extension-how-to-prevent-development-related-fields-automatically-added?noredirect=1#comment128910168_72983445

which didn't have anything to do with testing the extension, but only debugging it, and getting the same metadata written to an "unsuspecting" package.json.

Will this fix handle this SO situation as well?  The problem occurred very rarely so I couldn't give steps to reproduce, but I was only debugging and not running tests on the extension.

**Comment by sandy081** [comment]
> Will this fix handle this SO situation as well? 

Yes

**Comment by ArturoDent** [comment]
@sandy081 

I have learned more about my situation of getting this extra data when debugging an extension.  It happens when the extension writes to the `package.json`.  I have a couple of extensions which allow the user to make settings that will be read and converted to commands.

I files a separate issue: https://github.com/microsoft/vscode/issues/161286
