### ISSUE TITLE
Search for Objects and Properties in the Watch, Autos, and Locals Windows

### ISSUE THREAD

**Issue by pinguin999** [microsoft/vscode#148908]
VS 2012 has the possibility to search the locals and watch in debugging. 
https://devblogs.microsoft.com/visualstudio/enhanced-in-visual-studio-2019-search-for-objects-and-properties-in-the-watch-autos-and-locals-windows/

I would love to see that also in VS Code

**Comment by roblourens** [comment]
This exists - focus the variables and just start typing 😄 making this more discoverable is an ongoing conversation
