### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by BalajeV** [microsoft/vscode#148987]
Issue Type: <b>Performance Issue</b>

My VS code terminal was working properly until yesterday when I reinstall new version of python. The terminal does not show the current directory after executing code for once. I have to delete the current terminal and run the code again in a new terminal. Kindly help me with this. 

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label "needs more info" terminal
