### ISSUE TITLE
VScode won't open in browser

### ISSUE THREAD

**Issue by jmar123** [microsoft/vscode#148950]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I've attempted to open my project through the 'Live server' and 'open in browser' plugins and neither seem to work. I've changed the default browsers in both extension settings to no avail. I've reinstalled VScode and every browser that I had and no success either. Googling an answer only produces a handful of threads on stackoverflow, but they're mainly for ubuntu and linux machines, and even some of the possible solutions (though they sound too advance for me) don't seem to work for some of the people. I don't know what to do at this point. Not being able to open projects this way feels a little like running with your hands tied behind your back. Any help would be appreciated!

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.94GB free)|
|Process Argv|--crash-reporter-id 0092293f-930b-4e5c-940d-f20e7f871693|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
color-highlight|nau|2.5.0
LiveServer|rit|5.7.5
open-in-browser|tec|2.0.0
material-theme|zhu|3.13.24

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

**Comment by roblourens** [comment]
Please file an issue on the extension with some more details about what the problem is
