### ISSUE TITLE
how to hide sidebar

### ISSUE THREAD

**Issue by fegg** [Microsoft/vscode#14896]
- VSCode Version: 1.6.1
- OS Version: Mac OS 10.11.6

Hi~
How to hide vscode sidebar of left postion, like sublime text's global screen. some time not need sidebar, its ok. ^.^ if easy add this feature,its greate!

**Comment by SamVerschueren** [comment]
<kbd>⌘</kbd> + <kbd>b</kbd>

**Comment by fegg** [comment]
= = wu....not cmd+b, want to hide and sidebar's icon.
![效果](http://ww1.sinaimg.cn/large/006tNbRwgw1f9fbfl39auj304k07ujrg.jpg)

**Comment by bpasero** [comment]
That would be https://github.com/Microsoft/vscode/issues/1105
