### ISSUE TITLE
AutoCAD AutoLISP Extension Errors after Break set

### ISSUE THREAD

**Issue by MarkMitchellADP-Resources** [microsoft/vscode#148959]
Issue Type: <b>Bug</b>

AutoCAD AutoLISP Extension running in Visual Studio Code
Every time I set a break point: 
On running the code I get, "error: malformed list on input"
This has nothing to do with the soundness of the code.
It is a perfectly formed list. 

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (6 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.58GB free)|
|Process Argv|--crash-reporter-id b4cfc67a-be2e-4ca1-82ad-b43b59b07277|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
autolispext|Aut|1.5.0
doxdocgen|csc|1.4.0
vscode-download-file|dar|0.0.1
latex-workshop|Jam|8.26.0
better-cpp-syntax|jef|1.15.13
kite|kit|0.147.0
vscode-dbml|mat|0.3.5
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.78.0
remote-wsl|ms-|0.66.2
azure-account|ms-|0.10.1
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.2.0
geo-data-viewer|Ran|2.5.0
pdf|tom|1.2.0
cmake|twx|0.0.17
usql-vscode-ext|usq|0.2.15

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by roblourens** [comment]
Sounds like an error coming from the extension
