### ISSUE TITLE
The possible values for `editor.CursorBlinking` are not shown in `settings.json`

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#1489]
```
// Controls the cursor blinking animation.
	"editor.cursorBlinking": "blink",
```

The comment should also mention the various accepted values like they do for the other properties. I could work on this, but don't know what the possible values are?

**Comment by chrisdias** [comment]
you can see the possible values by clearing out the value and pressing Cmd+Space:

![image](https://cloud.githubusercontent.com/assets/1487073/11915759/3c335f66-a66a-11e5-920c-4a2f0aa31d46.png)

**Comment by hashhar** [comment]
Thanks for this information. Should I close this then since a solution exists?

**Comment by chrisdias** [comment]
I'll check in a fix for the comments as originally suggested, thanks!!
