### ISSUE TITLE
New file opening error doesn't wrap properly for very long lines

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#148968]
Was trying to open a private repo in github.dev:

![image](https://user-images.githubusercontent.com/2193314/167223676-bc7f2ca4-3ebf-4538-97f0-597e33aaa054.png)

We should allow words to break so they don't overflow

**Comment by joyceerhl** [comment]
@Tyriar was this failure to open a file expected (you had the file open from a previous session and the file has since been deleted) or not (the GitHub Repositories extension failed to load etc)?

**Comment by Tyriar** [comment]
@joyceerhl delayed response but I'm pretty sure it was unexpected, I think connecting to the workspace failed (maybe my extension was disabled or something)

**Comment by Tyriar** [comment]
Since the top was hard to repro, verified by opening an image in the text editor and manually changing the dom:

![image](https://user-images.githubusercontent.com/2193314/171849151-11556e6c-875f-4186-a90f-56f8552a397b.png)
