### ISSUE TITLE
Extension debug: opening another folder from target window opens twice

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#14895]
Steps to Reproduce:

1. run a hello world extension
2. from the window select File > Open Recent and pick another folder

=> the folder opes but then shortly later the window opens again

I suspect that the debug adapter is reloading the window again for some reason?

**Comment by weinand** [comment]
@bpasero I cannot reproduce this on macOS with the Insiders. Are you seeing this on Windows?

**Comment by bpasero** [comment]
On Mac but I was running out of sources so it could well be that I had an old debug extension?

**Comment by bpasero** [comment]
@weinand no, I can reproduce with using the latest node debug (1.7.9) as long as I am running "out of sources".

**Comment by bpasero** [comment]
@weinand looks like you can reproduce this now? maybe it only happens when running "out of sources".

**Comment by weinand** [comment]
@bpasero I'm not running VS Code out of sources.

@isidorn this looks like a regression. With the Insiders the debug adapter receives another launch request when reloading the EH window. This does not occur in Stable.
