### ISSUE TITLE
Using "Copy as HTML" option on selection in Terminal copies text with wrong background color

### ISSUE THREAD

**Issue by DesmondWillowbrook** [microsoft/vscode#148937]
Issue Type: <b>Bug</b>

- Change "terminal.integrated.rightClickBehavior" to default.
- Select text in terminal, then right-click and select "Copy as HTML"
- Text copied has a background-color of `#ffffff`, regardless of actual theme.
This is in direct contrast to Copy behaviour in main editor context.

Can test by using `Get-Clipboard -TextFormatType Html` in Powershell.

Copied from main editor:
<html>
<body>
<div style="color: #f8f8f2;background-color: #272822;font-family: Iosevka, Consolas, 'Courier New', monospace;font-weight: 400;font-size: 14px;line-height: 19px;white-space: pre;"><div><span style="color: #f8f8f2;">ls</span></div></div>
</body>
</html>

```
<html>
<body>
<!--StartFragment--><div style="color: #f8f8f2;background-color: #272822;font-family: Iosevka, Consolas, 'Courier New', monospace;font-weight: 400;font-size: 14px;line-height: 19px;white-space: pre;"><div><span style="color: #f8f8f2;">ls</span></div></div><!--EndFragment-->
</body>
</html>
```

Copied from terminal:
<div style='color: #000000; background-color: #ffffff; font-family: Iosevka; font-size: 14px;'><div><span></span><span style='color: #e2e22e;'>ls</span></div></div>

```
<html>
<body>
<!--StartFragment--><html><body><!--StartFragment--><pre><div style='color: #000000; background-color: #ffffff; font-family: Iosevka; font-size: 14px;'><div><span></span><span style='color: #e2e22e;'>ls</span></div></div></pre><!--EndFragment--></body></html><!--EndFragment-->
</body>
</html>
```

Rendered:
Original in editor:
![image](https://user-images.githubusercontent.com/51814158/167198097-5891be69-d5fa-433f-87cf-14f461c118c2.png)

In browser HTML (I put a `center` tag around it, the text is fine):
![image](https://user-images.githubusercontent.com/51814158/167198074-c4060686-09f5-4e23-a5e7-01087b72c3f7.png)

Original in terminal:
![image](https://user-images.githubusercontent.com/51814158/167198006-ec655eb0-df04-4db7-8e16-5f674dbb6363.png)

Copy-pasted from terminal:
![image](https://user-images.githubusercontent.com/51814158/167197951-384320a8-a6a8-43ce-82fc-07e2904b39db.png)

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.42GB (4.37GB free)|
|Process Argv|--crash-reporter-id c3a121e0-8201-482c-8e2f-86ecbfeb99ad|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics (16 x 3293)|
|Memory (System)|12.02GB (9.77GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-deno|den|3.12.0
commit-lint|kol|0.0.9
remote-wsl|ms-|0.66.2
vscode-typescript-next|ms-|4.7.20220505
vscode-ltex|val|13.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by meganrogge** [comment]
See the discussion here 

https://github.com/xtermjs/xterm.js/pull/3619#issuecomment-1028356061

**Comment by meganrogge** [comment]
Has to do with where you're pasting it, not what we're copying
