### ISSUE TITLE
Terminel is closed

### ISSUE THREAD

**Issue by josevictoremiliano** [microsoft/vscode#148906]
Issue Type: <b>Bug</b>

Opening terminal > crash terminal and closed

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.88GB (3.60GB free)|
|Process Argv|. --crash-reporter-id 92d74746-0629-43c7-97b3-0cc3a5900b5a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-django|bat|1.10.0
vscode-tailwindcss|bra|0.8.3
vscode-eslint|dba|2.2.2
vscord|Leo|4.5.0
fluent-icons|mig|0.0.17
vscode-html-format|moh|0.0.4
vscode-language-pack-pt-BR|MS-|1.67.2
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1001271738
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-wsl|ms-|0.66.2
js-debug-nightly|ms-|2022.5.417
vsliveshare|ms-|1.0.5527
html-fmt-vscode|Nik|0.8.0
material-icon-theme|PKi|4.17.0
LiveServer|rit|5.7.5
js-jsx-snippets|sky|11.0.0
code-spell-checker|str|2.1.11
code-spell-checker-portuguese-brazilian|str|2.0.6
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by josevictoremiliano** [comment]
I resolved it by formatting the PC, unfortunately I needed it as soon as possible to have vscode working for work.


But in my settings.json there was nothing, I deleted everything and tested again and nothing worked, so I thought I'd better format it soon
