### ISSUE TITLE
eol

### ISSUE THREAD

**Issue by sujingang** [microsoft/vscode#148984]
Issue Type: <b>Feature Request</b>

The code I pulled from the git repository has both LF and CRLF line breaks. When I use vscode to save, vscode automatically unifies all line breaks as LF or CRLF, but I use source insight. Shouldn't I just change the lines I modified when I'm thinking the editor saves the file? Why modify the entire file?

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by sujingang** [comment]
I don't want to change the newlines for non-modified lines

**Comment by lszomoru** [comment]
@sujingang, could you try using the `editor.formatOnSaveMode` setting?

**Comment by qinhanlei** [comment]
The same issue,`editor.formatOnSaveMode` is false, and I've tried disable all other extensions. 
When I saved the mixed EOL file, It changed to the non-mixed EOL file.
We want to keep it mixed for a while for some historical reasons.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/127
