### ISSUE TITLE
How to configure a task to run in WSL?

### ISSUE THREAD

**Issue by DavidA2014** [Microsoft/vscode#14898]
- VSCode Version: 1.6.1
- OS Version: Windows 10 Version 1607 for x64-based Systems

I am running VS Code 1.6 on Windows and have configured the integrated terminal to be bash:

"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe",

I want to build my C++ project using 'make' running in WSL. So I defined a task:

{
    "version": "0.1.0",
    "command": "make",
    "isShellCommand": true,
    "args": [""],
    "showOutput": "always"
}
How can I configure that task to run in WSL?

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/6579
