### ISSUE TITLE
Improve the Testing experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#148930]
Creating this as a master issue for improving the testing experience and assigning to May for initial PMy tasks. For dev items we will most likely look into it from June.

- [ ] Write testing docs @isidorn 
- [ ] Promote testing API so we get more extensions @isidorn 
- [ ] Convert [mocha extension](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-mocha-test-adapter) to fully use the new Testing API @connor4312 
- [ ] Add testing framework detection with decent recommendations @connor4312 @isidorn 
- [ ] Make viewlet visible by default with welcome text @connor4312 @isidorn 
- [ ] Make VS Code team selfhost more on Testing so we get more bugs and feedback @isidorn 

fyi @hediet @MarcusFelling

**Comment by connor4312** [comment]
> Provide an option to not focus on the error peek view and change users' selection when the test failed. Otherwise, the watch mode is annoying if the related test files are opened.

This is configured via the `testing.automaticallyOpenPeekView` setting 🙂

**Comment by zxch3n** [comment]
@connor4312 Great! thanks

**Comment by li1234yun** [comment]
https://github.com/microsoft/vscode/issues/153879

**Comment by isidorn** [comment]
This issue is outdated, and Connor is nicely driving the improvements to the Testing experience.
Thus closing this one. Thanks
