### ISSUE TITLE
Quick navigition with CtrlP missing

### ISSUE THREAD

**Issue by Rednas83** [microsoft/vscode#148992]
Issue Type: <b>Bug</b>

Press Ctrl+P is not showing quick navigation anymore.

What happen to this command?

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (21.17GB free)|
|Process Argv|--crash-reporter-id 4a68cf63-7e64-4db2-a55c-05f342c51d87|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
browse-lite|ant|0.3.0
code-gnu-global|aus|0.2.2
QML|bbe|1.0.0
vs-code-bpmn-io|bpm|0.13.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
dataverse-devtools|dan|2.0.5
pcf-builder|dan|1.1.2
power-platform-extension-pack|dan|0.0.1
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
code-runner|for|0.11.7
vscode-mysql|for|0.4.1
vscode-yarn|gam|2.1.0
copilot|Git|1.17.5850
copilot-labs|Git|0.1.122
todo-tree|Gru|0.0.215
vscode-scl|Gun|0.0.21
vscode-test-explorer|hbe|2.21.1
vue-snippets|hol|1.0.4
svg|joc|1.4.17
volar|joh|0.34.11
powerplatform-vscode|mic|1.0.5
vscode-exec-node|mir|0.5.4
csharp|ms-|1.24.4
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
cpptools|ms-|1.9.8
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.6
debugger-for-edge|msj|1.0.15
vetur|oct|0.35.0
portal-helper-vscode|ole|1.2.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.17.0
quicktype|qui|12.0.46
geo-data-viewer|Ran|2.5.0
vsmqtt|rpd|1.4.3
vue-vscode-snippets|sdr|3.1.1
vscode-st|Ser|1.11.23
ignore-gitignore|stu|1.0.1
vscode-mermaid-editor|tom|0.14.0
qtvsctools|ton|0.11.0
errorlens|use|3.4.2
vscodeintellicode|Vis|1.2.20
quokka-vscode|Wal|1.0.466

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaat:30438848

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions

**Comment by Rednas83** [comment]
It was caused by the PCF builder extension. I reported it to the author.

Thanks for sharing this usefull command🚀
