### ISSUE TITLE
Decoration listeners are added every time a decoration is rendered

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#148957]
Many of these onDispose listeners get created:

https://github.com/microsoft/vscode/blob/35e789713db25ee32dbf53a8d300b10578d828eb/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L237-L239

**Comment by meganrogge** [comment]
we fixed this at one pt.
![Screen Shot 2022-05-06 at 1 14 43 PM](https://user-images.githubusercontent.com/29464607/167210543-fb09aaee-96c5-427b-8a60-6af858fe59ea.png)

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/blob/5357dcfc04ddfce12661dca80ae9a104640a2c7e/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L119-L122

**Comment by Tyriar** [comment]
They were added in https://github.com/microsoft/vscode/commit/e45bef5c7a1d6e57e085ae74008d7042413bb8fc and https://github.com/microsoft/vscode/commit/280e61839aed8c9e7ba6709c49234c1ecc78ebe9

**Comment by meganrogge** [comment]
here's when we lost it https://github.com/microsoft/vscode/commit/2de0f469d8f3b37ef3c974985198c0a17afa3e6a

**Comment by meganrogge** [comment]
want to fix it since you're working on that PR?

**Comment by Tyriar** [comment]
Let's hold off until it's done, this PR is complicated enough without merge problems

**Comment by meganrogge** [comment]
it's a simple fix - literally adding `!this._decorations.get(decoration.marker.id)` to the conditional here

https://github.com/microsoft/vscode/blob/5357dcfc04ddfce12661dca80ae9a104640a2c7e/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L211-L218

**Comment by Tyriar** [comment]
Did another review and haven't seen this issue since 👍
