### ISSUE TITLE
The new highlight color scheme is confusing

### ISSUE THREAD

**Issue by BSPR0002** [microsoft/vscode#148936]
Issue Type: <b>Feature Request</b>

The new highlight color scheme for Javascript is confusing. It makes the color of the array different from that of the array within it. This is also reflected in objects, code blocks, and other identifiers.
Please revert to the previous color scheme.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Maybe this is what you are referring to.

https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

**Comment by BSPR0002** [comment]
> Maybe this is what you are referring to.
> 
> https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

Thanks. But I think this feature could be better. At least don't let the bracket pairs of the same usage have different colors.
