### ISSUE TITLE
"Show more" and "Clear recently opened" are too close in the "Open" menu.

### ISSUE THREAD

**Issue by bencehusi** [microsoft/vscode#148900]
Issue Type: <b>Feature Request</b>

In the open menu I always end up accidentally pushing the "Clear recently opened" instead of the "Show more".

It's very annoying that they're so close because it's very easy to fuck up and then I'm losing a lot of time for nothing.

If you could just revise the placement of that two actions, that's be great!

Screenshot:
https://capture.dropbox.com/w8v56cjg78Ga7qnA

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:49:20.994Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
After you update to 1.67 I think you will be asked to confirm clearing recently opened list.

**Comment by sbatten** [comment]
@gjsjohnmurray is correct
