### ISSUE TITLE
Code Color Display Error

### ISSUE THREAD

**Issue by brnanders** [microsoft/vscode#148905]
Issue Type: <b>Bug</b>

The color scheme is incorrect now, just randomly happened today, I'm assuming there was some update that happened.  This needs to be fixed as it is very difficult to read the code.  The brackets and parenthesis are different colors all over the place and it makes no sense.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.85GB free)|
|Process Argv|--folder-uri file:///d%3A/Users/Bryan/Documents/www/horizon --crash-reporter-id 05f9a256-9f34-46a7-8e0f-a5738e828ebf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
gitlens|eam|12.0.6
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
php-debug|xde|1.26.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

![image](https://user-images.githubusercontent.com/32779198/167135652-b63839cb-024e-4ae8-87cb-9d20fc779bf5.png)

**Comment by siegelaaron94** [comment]
I like this feature however the choice of bright colors is an issue for me, I would suggest a feature to change the brightness of the brackets instead of the color.

**Comment by hediet** [comment]
Please file a new issue to adapt bracket pair colorization colors for a specific theme.
