### ISSUE TITLE
Disable extension

### ISSUE THREAD

**Issue by HenriqueFQuick** [microsoft/vscode#148915]
Hello,
I have a small script to install a bunch of stuff in the computer to help new people that join my team, and one of those things is vscode and some extensions.
But the thing is, i want to install an specific extension and let it disabled for now. (because extension is important, but early in training it causes more confusion than it helps, so my idea was to install it but let it disabled and when they get to a certain part of the training, they would re-enable it)
The command that i'm using to install is code --install-extension extension_id
Is there a flag that i can use in this command to install but don't enable the extension?
I tried using code --disable-extension extension_id on my terminal, and it was disabling the extension but the button the enable it disappeared, and i wanted to the user to re-enable it, not that he had to run a command for this.

**Comment by gjsjohnmurray** [comment]
Maybe try the Settings Profile preview feature:

https://code.visualstudio.com/updates/v1_67#_settings-profile

**Comment by HenriqueFQuick** [comment]
Hmm, looks interesting...
Is there a command to import the settings? I could export the settings and inside the script only import it...
