### ISSUE TITLE
editor reports invalid deprication

### ISSUE THREAD

**Issue by EddieRich** [microsoft/vscode#148919]
Issue Type: <b>Bug</b>

const name = 'sally'
console.log(name)

![image](https://user-images.githubusercontent.com/11982581/167163097-36a95f18-96b2-479e-89c2-6f64dd7fa4e3.png)

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (22.27GB free)|
|Process Argv|C:\\Users\\ehandrich\\Desktop\\GetStatusItem --crash-reporter-id d340edea-2563-416e-88af-89baa3fb794c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.0.6
vscode-firefox-debug|fir|2.9.6
LiveServer|rit|5.7.5

</details>

**Comment by EddieRich** [comment]
This is not a 'duplicate'. The other issue is from over a year ago and has no resolution.
This is brand new and has only started happening since I installed your 'update' 2 days ago.

**Comment by EddieRich** [comment]
> /duplicate of #117401

This is not a 'duplicate'. This just started happening since the update 2 days ago.

**Comment by IllusionMH** [comment]
It's duplicate. Message changed but you can see that diagnostic code didn't.

Please see https://github.com/microsoft/vscode/issues/117401#issuecomment-784243053 for detailed explanation and linksl to upstream issue.
