### ISSUE TITLE
Changing Key Binding doesn't update Hotkey Hint Text in Menu until restart

### ISSUE THREAD

**Issue by joeizy** [Microsoft/vscode#14892]
- VSCode Version: 1.6.1
- OS Version: Linux Mint 17.3 Rosa

**VSCode About**
Version 1.6.1
Commit 9e4e44c19e393803e2b05fe2323cf4ed7e36880e
Date 2016-10-13T15:43:46.054Z
Shell 1.3.7
Renderer 52.0.2743.82
Node 6.5.0

**OS**
```
$ cat /etc/linuxmint/info 
RELEASE=17.3
CODENAME=rosa
EDITION="Cinnamon 64-bit"
DESCRIPTION="Linux Mint 17.3 Rosa"
DESKTOP=Gnome
TOOLKIT=GTK
NEW_FEATURES_URL=http://www.linuxmint.com/rel_rosa_cinnamon_whatsnew.php
RELEASE_NOTES_URL=http://www.linuxmint.com/rel_rosa_cinnamon.php
USER_GUIDE_URL=help:linuxmint
GRUB_TITLE=Linux Mint 17.3 Cinnamon 64-bit
```

**Steps to Reproduce:**

1. Click "File" Menu
2. Take note of the Hotkey Hint Text for "Save All" menu item
3. Click "Preferences > Keyboard Shortcuts"
4. Edit JSON file to adjust hokey for "Save All" action
```
{ "key": "ctrl+shift+s", "command": "workbench.action.files.saveAll" }
```
5. Save
6. Click File Menu

**Expected Result:**
The Hotkey Hint Text for "Save All" menu item should be "Ctrl+Shift+S"

**Actual Result:**
The Hotkey Hint Text for "Save All" menu item is whatever is was before editing.

**NOTE & Workaround:**
Closing VSCode and reopening will show the correct Hotkey Hint Text.

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by joeizy** [comment]
I did search but didn't find the issue, I'm not sure why because I looked again now and found it with ease. Sorry for dulicate.
