### ISSUE TITLE
VScode auto-formatting inserting tabs instead of spaces in HTML files

### ISSUE THREAD

**Issue by Zorgatone** [Microsoft/vscode#14899]
- VSCode Version: 1.6.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Set editor options to indent with space and indent size 2 (I've set both the user's options and the project's .editorconfig)
2. Open an .html file with indentation of 2 spaces
3. Auto-format the code using VSCode
4. Now all the spaces are gone, and tabs are oddly inserted instead.

On the right of the bottom editor bar, it says `spaces: 2` which tells the indentation setting is loaded correctly. For some reason it's getting ignored by auto-formatting.
I've also tried again with `detectIndentation: false`, but didn't work either

**Comment by rebornix** [comment]
It has been fixed in 1.7, please update :)

**Comment by Zorgatone** [comment]
@rebornix I've updated to 1.7.1

Now when I auto-format an .HTML file containing only spaces it works.
If I auto-format an .HTML file containing both spaces and tabs, seems it isn't doing anything at all. The tabs remain tabs and the spaces remain spaces.

Is VSCode supposed to work like that?

**Comment by Zorgatone** [comment]
I've tried in the same file to replace those spaces with tabs. Now when I auto-format some tabs become spaces, and some tabs remain tabs. Seems to be the same as the initial file before I replaced the spaces.

**Comment by Zorgatone** [comment]
@rebornix Here's the file I'm having trouble with: http://pastebin.com/0d6hrKK1
