### ISSUE TITLE
vscode crashes so frequently with vscode-go extension enabled and editing a go file

### ISSUE THREAD

**Issue by frezbo** [microsoft/vscode#148922]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.67.0 
- OS Version: PoP OS 22.04 5.17.5
![image](https://user-images.githubusercontent.com/18496730/167169455-5291a99d-c02b-4c2f-ba4c-e5b4230c1b8c.png)

Steps to Reproduce:

1. Open a go project in vscode
2. Try saving the go file with a change, vscode exits/crashes

Disabling the go-extension and cannot reproduce.

**Comment by hyangah** [comment]
@gjsjohnmurray Is there any guidance on how to capture the crash logs of vscode?

**Comment by gjsjohnmurray** [comment]
@hyangah maybe this?

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues
