### ISSUE TITLE
My VS Code can't detect my venv

### ISSUE THREAD

**Issue by HamzaElFergougui** [microsoft/vscode#148946]
Dear support team,

My VS Code can't detect the virtual environement that I created, I tried many ways to solve the problem and it's taking me days to do it, but can't achieve any results. It was working before, but due to some run error, VS Code lost knowledge of my venv even though I can see it and see its content in my project folder. Please help me with this, thank you. 

Kind regards,
Hamza El Fergougui

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues
