### ISSUE TITLE
Add OutputChannel.isVisible API

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#148993]
This will be useful to my extension. Thanks.

**Comment by gjsjohnmurray** [comment]
Please describe your use case.

**Comment by justanotheranonymoususer** [comment]
I have an extension with 2 output channels, and I need to switch between them for different situations. But if the user navigates away, I don't want to bother him. So I need code like:
```
if (is_b_active && a.isVisible()) {
  b.show();
}
```

**Comment by sandy081** [comment]
Not sure if I understand your use case, what do you mean by navigates away? Can you be more clear in explaining your use case?

**Comment by justanotheranonymoususer** [comment]
I have an extension with 2 output channels, one for info and one for errors. If the user looks at the info channel and there are errors, I want to switch to the errors channel for him. If there are no more errors and he's looking at the errors channel, I want to switch to the info channel. But if the user looks at other channel, or doesn't look at any channel at all, I don't want to bring up my channel to him. I hope this is clearer.

**Comment by sandy081** [comment]
Did you try using `window.visibleTextEditors` api? Output channel is an editor internally and opened output channel can be accessed from the above api

**Comment by justanotheranonymoususer** [comment]
I didn't try. How can I know a TextEditor is the output channel? How can I
get the currently open output channel from the TextEditor object?

**Comment by sandy081** [comment]
> How can I know a TextEditor is the output channel? 

From its URI

**Comment by justanotheranonymoususer** [comment]
So I tried and I see this object:
```
_formatted:'output:extension-output-vscode-samples.cat-coding-%231'
_fsPath:null
authority:''
fragment:''
fsPath:ƒ fsPath(){return this._fsPath||(this._fsPath=f(this,!1)),this._fsPath}
path:'extension-output-vscode-samples.cat-coding-#1'
query:''
scheme:'output'
```

I wish there was the output name instead of `#1`, then it could help. As it is now, the number doesn't allow to differentiate between the two, since I can't know which was created first (and I'd rather not track it). Maybe it can be improved to include the output name? Maybe something like `output:extension-output-vscode-samples.cat-coding-#1-MyOutputNameHere`.

**Comment by vanowm** [comment]
Here is my case use:
I create multiple output channels for each launched script.
There is also "common" output channel which displays output from all launched scripts.

When script finished it's task and exits, it's output channel is removed with `dispose()`, at which point VSCode automatically opens the first available output channel in the list (in my case it's `Tasks`).
I need to detect if any of output channels created by my extension were opened prior `dispose()`, if so, switch to "common" output channel otherwise do nothing.
