### ISSUE TITLE
Terminal cannot open

### ISSUE THREAD

**Issue by falkodev** [microsoft/vscode#148921]
Issue Type: <b>Bug</b>

Since update 1.67.0, no terminal can be added in VSCode. When opening one, it closes right away.

I am on a Mac, using Monterey and it used to work.

VS Code version: Code 1.67.0 (Universal) (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:14:47.100Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 4|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 8e1711aa-ea26-4548-a904-4164ef5e262c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by falkodev** [comment]
I restarted the computer and it works again, so no real issue for me here. Thanks
