### ISSUE TITLE
Persist terminal configuration in a remote workspace

### ISSUE THREAD

**Issue by marcfernandez1** [microsoft/vscode#148920]
The problem: 
When working on a remote session, I have a few terminals open. I rename and color code each terminal for a different tasks, ie watching several loggers. However, If I have to reload my remote session, it kills my terminals and their configuration. I have tried the save workspace option.

Is there a way to persist those terminals and their configuration in the workspace?
See attached for example:
![image](https://user-images.githubusercontent.com/55679871/167167206-475987ce-5ff7-4089-ab41-d1b87c50d91c.png)

**Comment by Tyriar** [comment]
This should work now, the terminals will eventually timeout if not reconnected to but simple reloads should keep them around.
