### ISSUE TITLE
Integrated terminal icons are cut off

### ISSUE THREAD

**Issue by Legion64** [microsoft/vscode#148999]
Duplicated of #148857
Issue Type: <b>Bug</b>

Hello, I encountered this error, although I did not make any changes in the editor today, while there was no problem yesterday. Even though I completely removed all plugins, settings files and even VSCode, nothing changed. Thinking that there might be a problem with the font, I downloaded different "Nerd Fonts" this time and tried, but it still didn't work.

**Hyper and Windows Terminal ScreenShots:**
![HyperAndWindows](https://i.imgur.com/Xbb4Det.png)

**VSCode Terminal:**
![VSCodeTerminal](https://i.imgur.com/imHjvzM.png)

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.16GB free)|
|Process Argv|--crash-reporter-id e4febc4b-d87b-410d-b89c-a23b466f9ba9 --crash-reporter-id e4febc4b-d87b-410d-b89c-a23b466f9ba9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
postcss|css|1.0.9
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.3.1
copilot|Git|1.17.5850
todo-tree|Gru|0.0.215
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.16
better-cpp-syntax|jef|1.15.13
git-graph|mhu|1.30.0
vscode-language-pack-tr|MS-|1.67.2
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-react-native|msj|1.9.2
laravel-blade|one|1.32.0
material-icon-theme|PKi|4.17.0
java|red|1.6.0
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vscode-env|Iro|0.1.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes516:30244333
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by dadocreate** [comment]
Hello! Any update on this?

**Comment by Legion64** [comment]
For now, until this issue is resolved i recommended use ```"terminal.integrated.gpuAcceleration": "canvas"``` in settings.json
