### ISSUE TITLE
feature request : file tab menu

### ISSUE THREAD

**Issue by rosrad** [Microsoft/vscode#14891]
- VSCode Version: v1.61
- OS Version: win10

New feature request:
In visual studio, the menu of file tab contains open file locations/directory. 
I think this small feature maybe very useful, it is very convenient to open my file located directory.
maybe u can add this feature in the further release.

Thanks, it will be a great editor for coder.

![image](https://cloud.githubusercontent.com/assets/2343640/19954556/05db933e-a1b4-11e6-906b-ffe5c08059a2.png)

**Comment by rebornix** [comment]
Sounds like a good extension for me. Take a look at our API https://github.com/Microsoft/vscode/pull/13199 and feel free to contribute!
