### ISSUE TITLE
Surface policy values in settings editor

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#148944]
Depends on https://github.com/microsoft/vscode/issues/148943

Whenever a policy value is set, the settings editor should:

- Prevent the user from changing the setting's value
- Provide a description similar to the following:

![image](https://user-images.githubusercontent.com/22350/167199683-a3ed3424-b8d0-4d53-b20d-e6f0f5cdecf7.png)

**Comment by sandy081** [comment]
Verified by code review
