### ISSUE TITLE
Version Control

### ISSUE THREAD

**Issue by GIT-MDW** [microsoft/vscode#148928]
Issue Type: <b>Feature Request</b>

Please add your own version control, the best one ))

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by lszomoru** [comment]
@GIT-MDW, I am not sure I understand this feature request? Could you please elaborate? Thanks!

**Comment by GIT-MDW** [comment]
Can you add git version control in VS code? like sublime merge

**Comment by lszomoru** [comment]
VS Code supports various source control providers. Please check [the product documentation](https://code.visualstudio.com/docs/editor/versioncontrol) for more information. Thanks!
