### ISSUE TITLE
Running created extension gets error

### ISSUE THREAD

**Issue by BradTFT** [microsoft/vscode#148932]
Issue Type: <b>Bug</b>

Hi,

So i installed and went through the generator process and got started. updated vscode to the newest version, and followed the docs. I went into the F5 window and ran the Hello World command. after i ran it it did nothing but brought this popup up: 
```
Activating extension 'undefined_publisher.vscode-extension' failed: Cannot find module '/home/user/vscode-extension/vscode-extension/dist/extension.js' Require stack: - /usr/share/code/resources/app/out/vs/loader.js - /usr/share/code/resources/app/out/bootstrap-amd.js - /usr/share/code/resources/app/out/bootstrap-fork.js.
```
i read thru some other issues and have not found the fix for it. 

i am not sure how this could be reproducable, but i followed all steps on the docs page exactly and got these errors

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:07.189Z)
OS version: Linux arm64 5.10.101-14962-gede4ccb2bf53
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (8 x 0)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|2.71GB (2.69GB free)|
|Process Argv|--unity-launch --crash-reporter-id b4d26343-fe2a-4779-a9f7-92554719d303|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
tsl-problem-matcher|amo|0.6.2
bracket-pair-colorizer|Coe|1.0.62
discord-tools|Dar|1.5.0
docs-markdown|doc|0.2.110
docs-preview|doc|0.3.58
githistory|don|0.6.19
gitlens|eam|12.0.6
vscode-html-css|ecm|1.12.2
vscode-npm-script|eg2|0.3.25
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
dotenv|mik|1.0.1
vscode-kubernetes-tools|ms-|1.3.8
playwright|ms-|0.2.3
python|ms-|2022.4.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.3.1000901801
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.8
vscode-css-peek|pra|4.2.0
vscode-yaml|red|1.7.0
LiveServer|rit|5.7.5
vscode-note|shi|0.14.0
swdc-vscode|sof|2.6.30
vscodeintellicode|Vis|1.2.20
vscode-icons|vsc|11.11.0
discord-py-snippets|Was|1.5.2
vscode-ruby|win|0.28.0
material-theme|zhu|3.13.24

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by BradTFT** [comment]
@sandy081 are you going to respond?

**Comment by alexdima** [comment]
@BradTFT That error indicates that the extension was not compiled. Before launching the extension, it first needs to be compiled and that happens via the defined build task.

**Comment by BradTFT** [comment]
Hi,

How can i compile it?

**Comment by alexdima** [comment]
@BradTFT When you press `F5` the build task will run automatically. If not, you can run it by yourself using the menu `Terminal > Run Build Task...`.

**Comment by alexdima** [comment]
Does the file `/home/<username>/vscode-extension/vscode-extension/out/extension.js` exist on disk? Can you check in your extension's `package.json` what is the value of the `"main"` property? Seeing the double folder "vscode-extension/vscode-extension" makes me think that perhaps you have manually moved things around after the `yo` generator finished?

**Comment by BradTFT** [comment]
output of "main": "main": "./out/extension.js",

i cannot find the dir for the above directory. 

i have not touched anything inside of the generated folder besides extension.ts and i renamed one of the markdown files. i could re instate the generator with a different name

**Comment by BradTFT** [comment]
Do i need to run the compile command?

**Comment by alexr00** [comment]
> which one. i attempted to create one a few years ago and its set as the default

Can you share a screen shot of your build tasks? 

From the above, it sounds like you've made some changes to the generated files. Can you also please share your tasks.json file and your launch.json file?

**Comment by BradTFT** [comment]
Hi,
I attempted to make a build task a few years ago and i did it wrong bc i had no idea what i was doing. i have not touched any files inside of the generated folder.



tasks.json:
```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "watch",
			"problemMatcher": "$tsc-watch",
			"isBackground": true,
			"presentation": {
				"reveal": "never"
			},
			"group": {
				"kind": "build",
				"isDefault": true
			}
		}
	]
}
```

launch.json:

```
// A launch configuration that compiles the extension and then opens it inside a new window
// Use IntelliSense to learn about possible attributes.
// Hover to view descriptions of existing attributes.
// For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/out/test/suite/index"
			],
			"outFiles": [
				"${workspaceFolder}/out/test/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		}
	]
}
```

**Comment by BradTFT** [comment]
![Screenshot 2022-05-11 11 18 25 AM](https://user-images.githubusercontent.com/50968931/167886268-81b14a0e-ae42-41c0-932a-0b5f2e50a792.png)

what should i choose for default build task

**Comment by BradTFT** [comment]
I ran the compile build task and it generated a new folder with another tasks.json file


task.json outside of the generator folder:

```
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "npm",
			"script": "compile",
			"path": "vscode-extension/",
			"group": {
				"kind": "build",
				"isDefault": true
			},
			"problemMatcher": [],
			"label": "npm: compile - vscode-extension",
			"detail": "tsc -p ./"
		}
	]
}
```

**Comment by BradTFT** [comment]
i updated vscode and reran the extension and i got this error collection in the debug term

```
Could not read source map for file:///usr/share/code/resources/app/out/bootstrap-fork.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/bootstrap-fork.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/vs/base/common/performance.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/vs/base/common/performance.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/bootstrap.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/bootstrap.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/bootstrap-node.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/bootstrap-node.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/bootstrap-amd.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/bootstrap-amd.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/vs/loader.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/vs/loader.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/vs/workbench/api/node/extensionHostProcess.js.map'
Could not read source map for file:///usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.nls.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/core/vs/workbench/api/node/extensionHostProcess.nls.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/microsoft-authentication/dist/extension.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/debug-auto-launch/dist/extension.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/git-base/dist/extension.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/git-base/dist/extension.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/ipynb/dist/ipynbMain.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/ipynb/dist/ipynbMain.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/git/dist/main.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/git/dist/main.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/github/dist/extension.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/github/dist/extension.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/github-authentication/dist/extension.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/github-authentication/dist/extension.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/emmet/dist/node/emmetNodeMain.js.map'
Could not read source map for file:///usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain.js: ENOENT: no such file or directory, open '/home/user/vscode-extension/sourcemaps/da15b6fd3ef856477bf6f4fb29ba1b7af717770d/extensions/merge-conflict/dist/mergeConflictMain.js.map'
```

also, could the generated folder from the generator be confusing vscode because the dir that it is in is also called vscode-extension? they are both called vscode-extension

**Comment by alexr00** [comment]
It looks like you don't have the correct folder open. You must open the generated folder in VS Code, not the parent folder.
