### ISSUE TITLE
output window - crashes under load.

### ISSUE THREAD

**Issue by sinclairzx81** [Microsoft/vscode#149]
Hi

When configuring the vscode task runner for ```"showOutput": "always"```, I note the output window may become overwhelmed if the process emits large amounts of text/data. This results in the application becoming unresponsive and requiring a restart.

Is it possible to buffer any output from a process and page it gracefully to the output window?

Many Thanks

**Comment by bpasero** [comment]
@sinclairzx81 any chance you can provide a reproducible case? we added some buffering recently but maybe it is not enough.

**Comment by bpasero** [comment]
please reopen when you have more information.
