### ISSUE TITLE
Menu bar not toggled when alt is pressed

### ISSUE THREAD

**Issue by N1kto** [microsoft/vscode#149082]
Issue Type: <b>Bug</b>

I am suing VS code without menu bar. So, when I need it I press the Alt key. 

All works as expected until  release notes are displayed. It happens both when release notes are displayed  automatically (after a new release) or when opened via menu (Help -> Release Notes). Once notes get displayed it is no longer possible to toggle the menu bar by pressing the alt key. To "fix" that one should close the VS Code editor and open it again. Then alt key pressing works as expeted (untill the next time release notes are displayed).

This has been happening for some time now (not related to the last release), I just didn't post the issue until today.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:08:42.978Z)
OS version: Linux x64 5.4.0-109-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 4099)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|62.57GB (14.75GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id e6f7f053-a327-4c38-972e-f01d4a1707b0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
stylus|Ala|0.0.4
haskero|Van|1.3.1
Handlebars|and|0.4.1
laravel-5-snippets|ate|0.0.1
theme-verdandi|be5|2.0.1
toml|be5|0.6.0
vscode-tailwindcss|bra|0.8.3
vscode-standard-format|che|0.0.12
vscode-standardjs|che|1.4.1
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
cjsx|cri|0.0.6
vscode-eslint|dba|2.2.2
vscode-coffeescript-preview|dre|1.0.1
gitlens|eam|12.0.6
prettier-vscode|esb|9.5.0
foam-vscode|foa|0.18.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-ghc-mod|hoo|1.2.0
hoogle-vscode|jca|0.0.7
docthis|joe|0.7.1
language-haskell|jus|3.6.0
vscode-markdown-notes|kor|0.0.24
graphql-for-vscode|kum|1.15.3
hg|mrc|1.8.1
language-gettext|mro|0.2.0
vscode-docker|ms-|1.22.0
vscode-kubernetes-tools|ms-|1.3.8
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
azure-account|ms-|0.10.1
language-purescript|nwo|0.2.8
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
laravel-helpers|raf|0.2.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.7.0
coffeescript-snippets|ron|0.1.3
rust|rus|0.7.8
elm|sbr|0.26.0
crates|ser|0.5.10
rust-grammar|sib|0.1.0
vscode-coffeelint|slb|0.0.2
code-spell-checker|str|2.1.11
sass-indented|syl|1.8.19
markdown-links|tch|0.8.0
ayu|tea|1.0.5
haskelly|UCL|0.5.5
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
markdown-all-in-one|yzh|3.4.3

(24 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaat:30438848

```

</details>

**Comment by jvesouza** [comment]
Thanks for reporting this issue. It happens here also in my linux environment but I didn't know how to reproduce it. 
I thought this problem had something to do with accessibility, but it seems I was wrong.
