### ISSUE TITLE
"quick open recent" cannot type name to search

### ISSUE THREAD

**Issue by lsongseven** [microsoft/vscode#149055]
Issue Type: <b>Bug</b>

Actual: After select "File: Quick Open Recent", there is no input box  through which I can type words to search recent projects.

Expect: The input box appears

VS Code version: Code 1.67.0 (Universal) (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:14:47.100Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No
Remote OS version: Linux x64 4.19.117.bsk.6-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 6|
|Memory (System)|32.00GB (5.73GB free)|
|Process Argv|--crash-reporter-id 033c5020-1aa0-4db4-b74d-36938d86b9d1|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: bigdevbox|
|OS|Linux x64 4.19.117.bsk.6-amd64|
|CPUs|Intel(R) Xeon(R) Platinum 8260 CPU @ 2.40GHz (32 x 2399)|
|Memory (System)|62.28GB (21.12GB free)|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
authenticator|byt|0.2.24
thrift|cdu|0.0.1
better-cpp-syntax|jef|1.15.13
vscode-language-pack-zh-hans|MS-|1.65.2
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.209.5
remote-ssh|ms-|0.79.2022040715
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.63.5
material-icon-theme|PKi|4.11.0
vim|vsc|1.22.2
tcl|bit|0.4.0
thrift-language-support|byt|0.0.6
cloud-toolkit|byt|0.3.24
gallery|byt|0.6.0
bytesec-vscode|byt|1.0.52
doxdocgen|csc|1.3.2
vscode-markdownlint|Dav|0.47.0
gitlens|eam|11.7.0
copilot|Git|1.12.5517
go|gol|0.32.0
vscode-test-explorer|hbe|2.21.1
better-cpp-syntax|jef|1.15.13
rss|luy|0.10.4
git-graph|mhu|1.30.0
thrift-syntax-support|mrk|0.0.9
vscode-docker|ms-|1.21.0
vscode-language-pack-zh-hans|MS-|1.65.2
python|ms-|2022.5.10981002
vscode-pylance|ms-|2022.4.0
jupyter|ms-|2022.4.1000991945
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.4
cmake-tools|ms-|1.11.7
cpptools|ms-|1.9.0
cpptools-extension-pack|ms-|1.1.0
makefile-tools|ms-|0.5.0
test-adapter-converter|ms-|0.1.5
sqltools|mtx|0.23.0
sqltools-driver-mysql|mtx|0.2.0
java|red|1.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.16
vscode-java-debug|vsc|0.37.0
vscode-java-dependency|vsc|0.18.8
vscode-java-pack|vsc|0.22.2022040800
vscode-java-test|vsc|0.34.2022033002
vscode-maven|vsc|0.35.2022041103
markdown-all-in-one|yzh|3.4.0
json|Zai|2.0.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by lsongseven** [comment]
Additional Infomation

![image](https://user-images.githubusercontent.com/26639581/167337535-e15c9801-04a5-41d7-89a5-7b6b11cea2bc.png)

After select "File: Quick Open Recent", the input box is missing

![image](https://user-images.githubusercontent.com/26639581/167337679-0df8692a-c4a8-44db-9d37-6c546336a924.png)

**Comment by chrmarti** [comment]
Try `File: Open Recent...` (without the `Quick` in the name). The `Quick` actions are navigated without the text box by keeping the modifier keys of the shortcut pressed and repeatedly pressing the other keys (they are not useful when no shortcut is assigned).

**Comment by theLMGN** [comment]
I'd appreciate it if developers would keep changing command names to a minimum where possible, this isn't the first time I'm going to have to reprogram my muscle memory! 😛
