### ISSUE TITLE
build[macos]: Upload configuration (for Bing settings search) timeout

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#149089]
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=170302&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb

**Comment by roblourens** [comment]
Not sure what's going on - this process is pretty straightforward and hasn't changed in years.

I am launching the full vscode window on this build machine, nothing has changed in electron that would interact with that right?

**Comment by deepak1556** [comment]
`main` and `release/1.67` are on same electron versions, the step worked fine in the `release/1.67` latest build last Friday https://dev.azure.com/monacotools/Monaco/_build/results?buildId=170088&view=results, first timeout failure started since insiders were turned back on `main` last Saturday https://dev.azure.com/monacotools/Monaco/_build/results?buildId=170136&view=results and since then all insiders build seem to consistently hit the timeout

Todays' nightly run: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=170422&view=logs&j=3792f238-f35e-5f82-0dbc-272432d9a0fb&t=0d7e5bc9-922f-51dd-b06a-a90d0b9feeeb

```
Error: export-default-configuration process timed out
    at Timeout._onTimeout (/Users/runner/work/1/s/build/azure-pipelines/upload-configuration.js:54:20)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

Testing if I can repro the issue locally.

**Comment by deepak1556** [comment]
Testing the callsite https://github.com/microsoft/vscode/blob/934e3781652f33a3c3352d8be153c090fff1e9f1/build/azure-pipelines/upload-configuration.ts#L44 locally seems to work fine.

**Comment by deepak1556** [comment]
I wonder if the timeout is insufficient, testing a build with increased timeout here https://monacotools.visualstudio.com/Monaco/_build/results?buildId=170440&view=results

**Comment by deepak1556** [comment]
Previous build did not enable the upload step, new build https://monacotools.visualstudio.com/Monaco/_build/results?buildId=170483&view=results

**Comment by roblourens** [comment]
Kicked off another, removing the branch check

**Comment by hediet** [comment]
Might not be fixed (https://dev.azure.com/monacotools/Monaco/_build/results?buildId=170713&view=results - run on 11th of May, one day after this fix has been merged to main)

**Comment by deepak1556** [comment]
@hediet the fix only landed in `main`, failing build was on `release/1.67`

**Comment by roblourens** [comment]
I can do that
