### ISSUE TITLE
`showTextDocument` is not respecting `preview: true` if user has `enablePreview` disabled

### ISSUE THREAD

**Issue by DavyLandman** [microsoft/vscode#149088]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.0
- OS Version: Windows 10 10.0.19044

Steps to Reproduce:

1. Set `workbench.editor.enablePreview` to `false`
2. Inside an extension, open a TextDocument via the [showTextDocument api](https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions), pass in the `{ preview: true }` option.
3. The new tab is not preview.
4. Open another file via the `showTextDocument` api, and again a new tab is opened, non preview.

Either this is a bug, or the manual is incorrect: 

> An optional flag that controls if an [editor](https://code.visualstudio.com/api/references/vscode-api#TextEditor)-tab shows as preview. Preview tabs will be replaced and reused until set to stay - either explicitly or through editing. The default behaviour depends on the workbench.editor.enablePreview-setting.

I would understand (but be a bit sad) if the documentation is wrong, like that maybe it should say that this flag is only working when `workbench.editor.enablePreview` is true. I think the preferred behavior would be that the first time this is called, and no preview tab exists, a new one is allocated, and all the following `showTextDocument` calls with `{ preview: true }` will use that new preview tab regardless of the user setting.

**Comment by DavyLandman** [comment]
I've been reading the source a bit, if I understand correctly, this line says that if `enablePreview` is set, the `preview` (which is negated to the `options.pinned` flag) flag is ignored.

https://github.com/microsoft/vscode/blob/91a9cf495b9b0907309f8dbd4787ce2eba9c2f02/src/vs/workbench/browser/parts/editor/editorGroupView.ts#L999

**Comment by bpasero** [comment]
Yeah, if the user has disabled preview tabs, an extension cannot enforce it. We should probably document that.

**Comment by DavyLandman** [comment]
Thank you for clarifying. I'll just have to tell users not to disable previews if they want this feature (of our extension) if they want to keep snappy cycles through files.
