### ISSUE TITLE
Explore a partial WASI implementation using the VS Code API

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#149092]

**Comment by lostintangent** [comment]
This is exciting! Out of curiosity: what's the current thinking around the scope of the partial implementation? And are there specific use cases that we're taking into account?

I'd love to have official support for a Pyodide-based notebook kernel, and was just wondering if this work would help accrue towards that 😀

// @joyceerhl

**Comment by dbaeumer** [comment]
The first focus will be on file IO and stdin, stderr, stdout.

The challenging things is that WASI is sync and all our API is async. If you are interested where this goes the repository is https://github.com/Microsoft/vscode-wasi

**Comment by dbaeumer** [comment]
Closing in favor of #154797

**Comment by dbaeumer** [comment]
First implementation is available at https://github.com/microsoft/vscode-wasi
