### ISSUE TITLE
Terminal keeps switching to Output tab to code settings sync output

### ISSUE THREAD

**Issue by mcqua007** [microsoft/vscode#149054]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.0
- OS Version: Mac OS Monterey 12.3.1  or from VS code about Darwin arm64 21.4.0

Steps to Reproduce:

1. Open VS code, open terminal
2. Then VS code keeps opening the output tab every 3 mins
3. 3. I keep switching back to terminal and then again it opens up the output tab. It goes to the code settings sync output. I havent installed any extension or changed settings recently.
<img width="1419" alt="Screen Shot 2022-05-08 at 8 43 24 PM" src="https://user-images.githubusercontent.com/17321059/167336956-b9a6eb68-b611-449d-9730-1da55ecfe0df.png">

**Comment by Tyriar** [comment]
This is the settings sync extension:

https://github.com/shanalikhan/code-settings-sync/blob/eb332ba5e8180680e613e94be89119119c5638d1/src/sync.ts#L595-L597

Note that VS Code now has a setting sync feature built-in: https://code.visualstudio.com/docs/editor/settings-sync

**Comment by mcqua007** [comment]
> https://github.com/shanalikhan/code-settings-sync/blob/eb332ba5e8180680e613e94be89119119c5638d1/src/sync.ts#L595-L597

Opps my bad. I though that was the built in VS code Settings Sync. As thats the one I am using. Must have been still installed from before you guys added built in Sync settings. Thanks for the help and the quick reply. I really appreciate it.
