### ISSUE TITLE
Terminal Icons

### ISSUE THREAD

**Issue by waelelsawy** [microsoft/vscode#149045]
Hi there,

After upgrading VSCode to version 1.67, the icons on terminal is not rendered properly
<img width="131" alt="Screen Shot 2022-05-08 at 11 33 49 PM" src="https://user-images.githubusercontent.com/10009971/167316712-6431a597-d99f-4004-9f87-98793be9bfbb.png">
<img width="126" alt="Screen Shot 2022-05-08 at 11 28 39 PM" src="https://user-images.githubusercontent.com/10009971/167316554-95efbb61-fab0-4630-8fc6-68d11c330a4d.png">

When I set "terminal.integrated.gpuAcceleration": "canvas", the icons is rendered perfectly.
<img width="111" alt="Screen Shot 2022-05-08 at 11 06 01 PM" src="https://user-images.githubusercontent.com/10009971/167315940-76dbf4ea-da63-49a5-882d-a740cb8a0526.png">
However, as you see the canvas has a weird background color and I can't get rid of it.

Is it possible to render the icons correctly without setting "terminal.integrated.gpuAcceleration" to canvas?

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: macOS Monterey v12.3.1

**Comment by gjsjohnmurray** [comment]
Maybe #148857
