### ISSUE TITLE
settings sync disabled because it is making too many requests

### ISSUE THREAD

**Issue by eljonny** [microsoft/vscode#149012]
Issue Type: <b>Bug</b>

computer under heavy load.
Installing extension updates, and installing a new extension.
Error appeared.

VS Code version: Code 1.60.0 (e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff, 2021-09-01T10:41:52.311Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-6200 Six-Core Processor              (6 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.95GB (0.34GB free)|
|Process Argv|--crash-reporter-id 5b628a76-a8e0-49ba-81ed-c8dd3458149f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (265)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
rainbow-brackets|2gu|0.0.6
elm-format|aba|0.1.0
logcat|abh|0.0.7
vscode-nsp|ada|1.0.1
Bookmarks|ale|13.2.2
pascal|ale|9.3.0
pascal-formatter|ale|2.5.0
vscode-sqlite|ale|0.13.0
aws-toolkit-vscode|ama|1.37.0
Handlebars|and|0.4.1
ng-template|Ang|13.3.2
vscode-color|ans|0.4.5
swagger-viewer|Arj|3.1.2
aurelia|Aur|2.1.4
code-gnu-global|aus|0.2.2
vscode-database|baj|2.2.3
vscode-django|bat|1.10.0
togglehs|bbe|0.1.2
vscode-node-readme|ben|3.0.2
django-html|bib|1.3.0
vscode-intelephense-client|bme|1.8.2
puppet|Bor|0.3.2
phpserver|bra|3.0.2
better-toml|bun|0.3.2
stylus|buz|0.1.0
cake-vscode|cak|2.0.0
plsql|cas|0.0.5
Gradle|caz|1.1.2
chef|che|2.1.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
regex|chr|0.4.0
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
gitignore|cod|0.7.0
vscode-express|Com|0.0.5
vscode-mocha|Com|0.1.1
erb|Cra|0.0.1
vscode-github-actions|csc|0.24.1
doxdocgen|csc|1.4.0
vscode-svgviewer|css|2.0.0
arm|dan|1.7.4
dart-code|Dar|3.27.2
flutter|Dar|3.27.0
vscode-markdownlint|Dav|0.47.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.1
vscode-instant-markdown|dba|1.4.7
vscode-dash|dee|2.4.0
vscode-yaml-validation|dja|0.0.1
vscode-npm-source|dku|1.0.0
githistory|don|0.6.19
python-extension-pack|don|1.6.0
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
ghlink|dt|1.2.0
vscode-sql-connect|dvd|0.2.1
vscode-babel-coloring|dza|0.0.4
gitlens|eam|11.6.1
vscode-html-css|ecm|1.10.2
EditorConfig|Edi|0.16.4
tslint|eg2|1.0.47
vscode-npm-script|eg2|0.3.25
LogFileHighlighter|emi|2.15.0
react-native-react-redux|EQu|2.0.6
json-tools|eri|1.0.2
prettier-vscode|esb|9.5.0
vs-code-xml-format|fab|0.1.5
mithril-emmet|Fal|0.7.7
tortoise-svn|fan|0.1.1
git-project-manager|fel|1.7.1
php-intellisense|fel|2.3.14
vsc-ember-cli|fel|0.3.3
vsc-travis-ci-status|fel|1.1.0
vscode-firefox-debug|fir|2.9.6
vscode-npm|fkn|3.3.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
terminal|for|0.0.10
vscode-mysql|for|0.4.1
fortran|Gim|0.2.0
matlab|Gim|2.3.1
copilot|Git|1.13.5700
vscode-pull-request-github|Git|0.32.0
go|gol|0.33.0
gc-excelviewer|Gra|3.0.44
ocaml|hac|0.6.44
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
haskell-linter|hoo|0.0.6
vscode-ghc-mod|hoo|1.2.0
rest-client|hum|0.24.6
coldfusion|ili|1.0.1
smarty|imp|0.3.0
java-properties|ith|0.0.2
latex-workshop|Jam|8.21.1
plantuml|jeb|2.17.2
better-cpp-syntax|jef|1.15.13
vscode-nuget-package-manager|jmr|1.1.6
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.0.1
postgresql|JPT|0.0.2
language-julia|jul|1.4.0
language-haskell|jus|3.6.0
format-indent|Kas|1.3.0
swift|Kas|0.2.0
vsc-python-indent|Kev|1.14.2
Lua|key|0.0.9
codeshell|Kip|0.2.2
vscode-codemetrics|kis|1.24.0
vscode-github|Kni|0.30.7
sftp|lix|1.12.10
vscode-JS-CSS-HTML-formatter|lon|0.2.3
ftp-sync|luk|0.3.9
MagicPython|mag|1.1.0
VS-code-drupal|mar|0.0.12
aws-cli-configure|mar|0.3.0
Kotlin|mat|1.7.1
vscode-todo|Mat|0.8.0
tgit-cmds|mbi|1.4.1
start-git-bash|McC|1.2.1
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-exec-node|mir|0.5.4
vscode-clang|mit|0.2.4
ecdc|mit|1.7.0
vscode-elixir|mjm|1.1.0
HTMLHint|mka|0.10.0
prettify-json|moh|0.0.3
Arduino|moo|0.0.4
vscode-apache|mrm|1.2.0
azure-pipelines|ms-|1.202.0
vscode-azureappservice|ms-|0.23.0
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-docker|ms-|1.20.0
csharp|ms-|1.23.16
vscode-dotnet-runtime|ms-|1.3.0
vscode-kubernetes-tools|ms-|1.3.8
data-workspace-vscode|ms-|0.2.0
mssql|ms-|1.14.1
sql-bindings-vscode|ms-|0.0.1
sql-database-projects-vscode|ms-|0.16.1
python|ms-|2021.10.1365161279
vscode-pylance|ms-|2022.1.3
vscode-ai-remote|ms-|0.6.0
remote-containers|ms-|0.194.3
remote-ssh|ms-|0.66.0
remote-ssh-edit|ms-|0.70.0
remote-wsl|ms-|0.58.5
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
cmake-tools|ms-|1.9.2
cpptools|ms-|1.7.1
cpptools-extension-pack|ms-|1.2.0
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2022.5.1
test-adapter-converter|ms-|0.1.3
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5527
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
team|ms-|1.122.0
veriloghdl|msh|1.5.3
cordova-tools|msj|2.4.1
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
debugger-for-ios-web|msj|0.1.2
vscode-react-native|msj|1.9.2
sqltools|mtx|0.23.0
nativescript|Nat|0.12.3
color-highlight|nau|2.5.0
node-modules-resolve|nau|1.0.2
autodocstring|njp|0.6.1
angular-console|nrw|17.16.0
createGUID|nwa|0.0.2
peep|nwa|0.0.5
vetur|oct|0.35.0
indent-rainbow|ode|8.3.1
vscode-jest|Ort|4.2.1
erlang|pgo|0.8.4
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.33.0
vscode-manifest-yaml|Piv|1.33.0
vscode-spring-boot|Piv|1.33.0
material-icon-theme|PKi|4.17.0
platformio-ide|pla|2.4.3
polymer-ide|pol|0.6.0
view-in-browser|qin|0.0.5
diff|raf|0.0.1
ravi-debug|rav|1.0.2
typescript-hero|rbb|3.0.0
ruby|reb|0.28.1
java|red|1.1.0
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
vscode-yaml|red|1.7.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
sass-indented|rob|1.4.8
sharecode|Rol|0.4.1
rust|rus|0.7.8
partial-diff|ryu|1.4.3
git-add-remote|sam|0.0.2
final-newline|sam|0.3.2
yo|sam|0.9.3
whitespace|san|0.0.5
RustyCode|sav|0.19.1
elm|sbr|0.26.0
vscode-sql-beautify|sen|0.0.4
code-settings-sync|Sha|3.4.3
vscode-nginx|sha|0.6.0
trailing-spaces|sha|0.3.1
stylelint|shi|0.33.0
swiftlint|shi|0.1.3
html5-boilerplate|sid|1.1.1
shader|sle|1.1.5
vscode-hexdump|sle|1.8.1
autoimport|ste|1.5.4
cucumber|ste|0.13.5
addDocComments|ste|0.0.8
code-spell-checker|str|2.1.11
html-preview-vscode|tht|0.2.5
pdf|tom|1.2.0
json2yaml|tux|0.2.0
jsx|Twe|0.0.1
twig|Twe|0.0.4
cmake|twx|0.0.17
gitflow|vec|1.2.1
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.20
vscode-arduino|vsc|0.4.12
vscode-java-debug|vsc|0.38.0
vscode-java-dependency|vsc|0.19.0
vscode-java-pack|vsc|0.21.0
vscode-java-test|vsc|0.32.0
vscode-maven|vsc|0.34.2
vscode-spring-boot-dashboard|vsc|0.3.0
vscode-spring-initializr|vsc|0.9.0
vscode-icons|vsc|11.11.0
vscode-meteor|vuh|0.1.1
babelrc|wad|1.0.0
gitblame|wad|8.1.0
vscode-todo-highlight|way|1.0.5
code-d|web|0.23.2
debug|web|0.26.0
jinja|who|0.0.8
vscode-ruby|win|0.28.0
github-detial-comment|wk-|0.0.9
JasmineSnippets|xab|1.0.1
php-debug|fel|1.22.0
php-pack|xde|1.0.3
D3Snippets|yoy|0.1.11
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.13.20
html-css-class-completion|Zig|1.20.0
vscode-open-in-github|ziy|1.3.6
php-intellisense|zob|1.0.4
vscode-proto3|zxh|0.5.5

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vscaac:30438847

```

</details>

**Comment by gjsjohnmurray** [comment]
Please update to the current release which is 1.67

**Comment by kamenminkov** [comment]
Just a guess - there were a lot of extensions updated at once and this triggered the protection (because `extensions.json` keeps track of the versions too). I don't know what's the threshold, but you can open the palette and execute `View: Show Settings Sync` and under `Sync Activity` you'll see what's been synced recently - and if there are a lot of entries for extensions it would confirm my guess.

**Comment by sandy081** [comment]
This is fixed. Please update to latest version.
