### ISSUE TITLE
Django Debugger does not start using launch.json

### ISSUE THREAD

**Issue by AtlasUser5** [microsoft/vscode#149063]
Issue Type: <b>Bug</b>

Django debugger does not load the terminal when started and the operation closes itself without any error. This occurs when the python environment is created in current user directory (C:\Users\CurrentUser\...\env)

I have used the default Django Configuration in launch.json file with added python env path
Python : 3.10.4 (Installed for current user only)
Django : 4.0.4
Env Path : C:\Users\CodeUser\Development\Environments\Python\env3104dev01
launch.json :
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Django",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder}\\manage.py",
            "args": [
                "runserver"
            ],
            "django": true,
            "justMyCode": true
        }
    ]
}

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.35GB (3.65GB free)|
|Process Argv|--crash-reporter-id 4dd5bf7c-1be4-4910-a13c-753cb545e6a4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

</details>

**Comment by roblourens** [comment]
Please file this on the Python extension's repo
