### ISSUE TITLE
Custom code snippets in project folder

### ISSUE THREAD

**Issue by Liero** [Microsoft/vscode#14900]
I would like to share project specific code snippets with my team, just like I share my .vscode/setting.js resp .vscode/tasks.js:

![capture](https://cloud.githubusercontent.com/assets/3494407/19960647/672a47d0-a1ae-11e6-8ed0-998719f3bb1b.PNG)

**Comment by rebornix** [comment]
dup of https://github.com/Microsoft/vscode/issues/8102
