### ISSUE TITLE
auto detect not working 

### ISSUE THREAD

**Issue by AJCJ-3568** [microsoft/vscode#149017]
Issue Type: <b>Bug</b>

vscode auto detect not working is not wroking how is show the js 

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (12.89GB free)|
|Process Argv|--crash-reporter-id 37a7b5b9-126f-485e-8891-8b8e672ae97d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.1
dart-code|Dar|3.40.0
flutter|Dar|3.40.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
vscode-html-css|ecm|1.12.2
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
vscode-edge-devtools|ms-|2.0.0
data-workspace-vscode|ms-|0.2.0
mssql|ms-|1.14.1
sql-bindings-vscode|ms-|0.0.1
sql-database-projects-vscode|ms-|0.16.1
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
cmake-tools|ms-|1.10.5
powershell|ms-|2022.5.1
vsliveshare|ms-|1.0.5527
vscode-react-native|msj|1.9.2
material-icon-theme|PKi|4.17.0
java|red|1.6.0
LiveServer|rit|5.7.5
autoimport|ste|1.5.4
code-spell-checker|str|2.1.11
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.20
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vscode-import-cost|wix|3.3.0
php-debug|xde|1.26.1
php-pack|xde|1.0.3
php-intellisense|zob|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaat:30438848

```

</details>

**Comment by mjbvz** [comment]
Please share steps to reproduce the issue and explain what the expected behavior is vs what is currently happening

/needsMoreInfo
