### ISSUE TITLE
VSCode is not working in Safari < 14

### ISSUE THREAD

**Issue by mifopen** [microsoft/vscode#149076]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: doesn't matter

The same as in https://github.com/microsoft/monaco-editor/issues/2432
Because of this https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/browser.ts#L79
```ts
		this._mediaQueryList.addEventListener('change', this._listener);
```
And this https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/browser.ts#L151
```ts
	query.addEventListener('change', callback);
```
And maybe some other places

**Comment by mifopen** [comment]
@alexdima fyi

**Comment by alexdima** [comment]
There are no plans to support Safari < 14. Safari 13 and 14 are [no longer supported by Apple](https://en.wikipedia.org/wiki/Safari_version_history).
