### ISSUE TITLE
File order can be confusing when having test and source files next to each other

### ISSUE THREAD

**Issue by astrebel** [Microsoft/vscode#14901]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a file for example server.ts and server.test.ts
2. Create a file for example server-client.ts

The file order as it is today is confusing in this case when having test files next to source files. I would like to have server.test.ts directly below the corresponding source file.

server.ts
server.test.ts
server-client.ts
(server-client.test.ts)

![filename-order](https://cloud.githubusercontent.com/assets/5836940/19961412/cdb857fe-a1b2-11e6-82f1-6e2a8879dc23.png)

**Comment by rebornix** [comment]
It's our default behavior. If you like a customization, it's tracked in #12345
