### ISSUE TITLE
Option to wrap at specified column only when window is larger than the specified number of columns

### ISSUE THREAD

**Issue by hashhar** [Microsoft/vscode#1490]
Consider this a feature request:

I am looking to be able to wrap code to 80 columns but only when my window is larger than 80 columns.   
Otherwise I want it to use the viewport wrapping.

I guess this would be useful for people who have two windows open side by side and one of the windows has two files open side by side (`settings.json` for me). In such cases, I cannot view the file without scrolling sideways.

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by Fania** [comment]
Yes please!

**Comment by hashhar** [comment]
I would like to start implementing this myself. Reading through the code myself and setting up the environment. Will ask if any help needed.

**Comment by hashhar** [comment]
Hmmm, I was having some issues building it. But it's building fine now. I'll try and send a PR within a 5 or 6 days.

**Comment by hashhar** [comment]
How can I find out the current viewport width? I think adding an extra conditional to `src/vs/editor/common/config/commonEditorConfig.ts` near [line 117](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/common/config/commonEditorConfig.ts#L117) would do the trick?

I'm sorry, this is turning out to be a bit more difficult than I expected. The codebase is really large.

**Comment by hashhar** [comment]
Got it working. I now need to integrate it properly. @alexandrudima or @bpasero.

You can see the patch [here](https://github.com/hashhar/vscode/commit/f7dbfcef4c810215f510deb73d82d5be11b663c4). I have some notes in the commit message regarding the next steps to take to integrate it properly.

**Comment by hashhar** [comment]
Ummm, needed a help. I made a few more changes to convert the option to an editor setting. But on commit, it tells me Hygeine.js failed but I can't tell where it is failing.

**Comment by hashhar** [comment]
@alexandrudima I am not able to get it to show in the default config file. How is the default config file generated?

**Comment by hashhar** [comment]
I'm gonna send a PR. It works on my end.

**Comment by Fania** [comment]
Sounds great. Thanks for the effort!

**Comment by alexandrudima** [comment]
Just merged the PR from @hashhar. Thank you @hashhar!

**Comment by hashhar** [comment]
Thanks.
