### ISSUE TITLE
Tag 1.999.0 still exists in the repository

### ISSUE THREAD

**Issue by zeshuaro** [microsoft/vscode#149080]
Same issue as #140207, the tag [1.999.0](https://github.com/microsoft/vscode/releases/tag/1.999.0) is being added to the repository again. Breaking automated tools like Renovate Bot thinking that there is a new version to update.

<img width="934" alt="image" src="https://user-images.githubusercontent.com/12210067/167401263-47eed54c-c945-44f4-821f-cafec7a567e2.png">

**Comment by chrmarti** [comment]
@JacksonKearl Is there a way a GitHub action could help identify who pushed the tag and delete the tag automatically?

/cc @joaomoreno

**Comment by JacksonKearl** [comment]
We can id the tag and ping the creator, we don't give our Actions git write access so can't go and delete the tag automatically.

**Comment by JacksonKearl** [comment]
Deleted tag, added action to ping the pusher upon pushing it back to the repo. Actions dont have write access so cannot delete it themselves.
