### ISSUE TITLE
[Improvement] Close toggle for `Customize Layout` button when its open

### ISSUE THREAD

**Issue by Gumichocopengin8** [microsoft/vscode#149052]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: macOS 12.3.1 (21E258)

### Steps to Reproduce:

1. Open `Customize Layout` using the button
2. Click the button again to close it but cannot close it3. 
<img width="1076" alt="a" src="https://user-images.githubusercontent.com/34010665/167334110-1b05a83f-b62e-4965-8fe3-7fc905b3fa0e.png">

### The issue code:

https://github.com/microsoft/vscode/blob/e3f21a18e2727ac37c78159ba81f2c6ee4a982cc/src/vs/workbench/browser/actions/layoutActions.ts#L1309 

Its always running show method, so I think it should have an open/close state to manage it.

**Comment by gjsjohnmurray** [comment]
Try clicking here:

![image](https://user-images.githubusercontent.com/6726799/167381349-42f3c14a-cd21-4ed5-9579-48ec0b77aadc.png)

**Comment by Gumichocopengin8** [comment]
@gjsjohnmurray Thank you for the comment. Yes, I know I can close it by clicking the button, but it would be nice to close it by clicking the original button.

**Comment by gjsjohnmurray** [comment]
@Gumichocopengin8 please improve the issue title, which currently states that you "cannot close" it.

**Comment by Gumichocopengin8** [comment]
@gjsjohnmurray My bad. I'll fix it now

**Comment by sbatten** [comment]
@misolori for UX guidance here. when actions open quick picks we don't tend to have an inverse action if its still open. this is not usually the case because it is closed when focus is lost, but not something we can rely on here.

**Comment by Gumichocopengin8** [comment]
Thank you
Even if the focus is lost, the action view won't be closed on Mac. Also, other buttons allow us to open and close by clicking, so it should be consistent. I often click the button by accident and need to move cursor to close the view. That would be nice to have a toggle feature on the button too.

**Comment by gjsjohnmurray** [comment]
> I often click the button by accident

Maybe use the setting which removes the button completely?

**Comment by misolori** [comment]
We don't currently hide any of the quick picks with other actions or clicking the same action (changing focus would actually close it). I think given that we have the `Escape` key and the close button in the top right of the quick pick, I don't think we'd be able to do anything else.
