### ISSUE TITLE
Allow to have the editor tab bar above the side bar

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#14904]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393
# Current state
After opening the side bar, tab bar width is horizontally limited to the area left over by the open side bar
# Wanted
*Vertically* shrink side bar to allow tab bar extend to the full width of the window, even if side bar is open

**Comment by bpasero** [comment]
How can you NOT shrink the tab bar but still make room for the sidebar?

**Comment by PunchyRascal** [comment]
Curent:

![tab-side-bar-current](https://cloud.githubusercontent.com/assets/821272/19967271/eb36e5b2-a1cf-11e6-9e16-956b53ecba0a.png)

wanted:

![tab-side-bar-wanted](https://cloud.githubusercontent.com/assets/821272/19967272/eb3a08dc-a1cf-11e6-948e-663806b8dcdc.png)

**Comment by bpasero** [comment]
@PunchyRascal appreciate the drawing :)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
