### ISSUE TITLE
Can't recognize file path using `file://` schema 

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#149031]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/167303923-9b0b3548-15c9-41b1-a40c-c6c02bcfbbe3.png">

```
file:///Users/yutengjing/code/js-handwriting-2022/src/objectUtils/test.js:6:8
```

Version: 

```
MacOS: 12.3.1
VSCode: 1.67.0-inside
```

**Comment by Tyriar** [comment]
Fixed today

/duplicate https://github.com/microsoft/vscode/issues/150526
