### ISSUE TITLE
"Open in External Terminal" action to files in the WSL doesn't work as expected

### ISSUE THREAD

**Issue by fryhsueh** [microsoft/vscode#149011]
Issue Type: <b>Bug</b>

The project CS61A is under WSL. After "Open in External Terminal" action to the _lab13_,
 
![image](https://user-images.githubusercontent.com/104141275/167280218-ceb6eb90-b9c8-4140-8576-b0d63286a98e.png)

I got this

![image](https://user-images.githubusercontent.com/104141275/167280313-45f6bacf-3a69-429e-a3a8-0509e66cbd81.png)

Notice that the path is /mnt/c/Windows, which should be same as the path of _lab13_ while it's not.

The expected output should work like this

![image](https://user-images.githubusercontent.com/104141275/167280427-97a0b36e-0154-4f87-b974-4064e949b0a2.png)

to 

![image](https://user-images.githubusercontent.com/104141275/167280451-2f4b0615-a193-4353-b2b3-23cf4f2f4da7.png)

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.68GB free)|
|Process Argv|--crash-reporter-id 0b59fe9c-0dc2-4f28-a353-b25fa44fcf13|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
bloop|blo|0.17.0
vscode-pull-request-github|Git|0.42.0
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.78.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
scala|sca|0.5.5
metals|sca|1.16.0
vscode-scheme|sjh|0.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/167865

**Comment by Tyriar** [comment]
We actually disable this completely and use the integration terminal for remote cases now. Closing as wont fix
