### ISSUE TITLE
High CPU activtity of C++ Extension 

### ISSUE THREAD

**Issue by TwoLaid** [Microsoft/vscode#14908]
When loading a "big" workspace that contains some C++ files, the C++ Extension helper (`Microsoft.VSCode.CPP.Extension.darwin`) scans the entire workspace, including hidden files for C++ information to feed into their AutoCompletion.

For me, this can be detrimental when I for example have a remote folder mounted via SSH and VS Code is trying to scan it.

Is there any way to control which folders are scanned? `files.watcherExclude` does not seem to work.

- VSCode Version: 1.6.1 (1.6.1)
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1. Install recommended C++ Extension
2. Open a large workspace with C++ files

**Comment by rebornix** [comment]
Hey @TwoLaid , per your description, it looks like a C++ extension to me so I'd like to move it there.
