### ISSUE TITLE
One key sequence for start/restart

### ISSUE THREAD

**Issue by andrewfstratton** [Microsoft/vscode#14902]
Feature request (sorry - can't see how to tag at the moment)
- VSCode Version: Any (?)
- OS Version: n/a

Steps to Reproduce:

1. Start debug session (Node js in my case) with F5
2. Restart with Ctrl-Shift-F5

Could Ctrl-Shift-F5 also start a session, if one isn't running already - i.e. allow restart to start when necessary...

**Comment by rebornix** [comment]
add below to your keybindings.json

```
{ "key": "shift+cmd+f5",          "command": "workbench.action.debug.start",
                                     "when": "!inDebugMode" }
```
