### ISSUE TITLE
all of my intellisense suddenly stopped after the new update

### ISSUE THREAD

**Issue by melsayedgit** [microsoft/vscode#149051]
Issue Type: <b>Bug</b>

all of my intellisense suddenly stopped after the new update

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (7.72GB free)|
|Process Argv|C:\\iti\\projects\\Event Mangment System --crash-reporter-id ee9b4034-9e65-400f-92db-f33040472264|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bootstrap5-vscode|Anb|0.2.2
ng-template|Ang|13.3.2
node-snippets|chr|1.3.3
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
vscode-html-css|ecm|1.12.2
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
code-runner|for|0.11.7
bootstrap5-snippets|Han|1.2.5
reg|ion|1.1.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.0.1
data-workspace-vscode|ms-|0.2.0
mssql|ms-|1.14.1
sql-bindings-vscode|ms-|0.0.1
vscode-typescript-next|ms-|4.8.20220508
material-icon-theme|PKi|4.17.0
typescript-hero|rbb|3.0.0
vscode-xml|red|0.20.0
LiveServer|rit|5.7.5
vscodeintellicode|Vis|1.2.20
quokka-vscode|Wal|1.0.466
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.13.25
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to investigate whether this problem is being caused by one of your extensions.

**Comment by melsayedgit** [comment]
its seem that there was a problem of some kind that render the intellisense extension unusable, a couple of restered for all of the extension solved the problem but i couldn't figrue out if an extensions (using bisect )that caused the proeblem or the new update
