### ISSUE TITLE
Horizontal bracket guides break on wrapped lines in first column, if editor.wrappingIndent == "same"

### ISSUE THREAD

**Issue by ferdnyc** [microsoft/vscode#149074]
Issue Type: <b>Bug</b>

#### Demonstration
1. Set the editor language to C++
1. Set `editor.guides.bracketPairsHorizontal` to `true`
1. Set `editor.wrappingIndent` to `same`
1. Type/paste the Sample code below
1. Resize the editor window so that it is narrower than the line of code provided
1. Note that the horizontal bracket underline stops at the end of the first line, when the (soft-wrapped) line break occurs.

#### Verification
1. Change `editor.wrappingIndent` to `indent`
1. Note that the horizontal bracket underline now continues onto the wrapped second line.

#### Sample code demonstrating problem
```c++
void SomeClassImplementation::my_really_long_function_name(SomeClassImplementation input_instance, const SomeOtherClass& parameter_instance) { }
```

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:08:42.978Z)
OS version: Linux x64 5.17.4-200.fc35.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 6|
|Memory (System)|19.50GB (1.32GB free)|
|Process Argv|misc-utils/hardlink.1.adoc --crash-reporter-id 70502e77-0823-4a70-9602-0e2581de41fd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by ferdnyc** [comment]
#### `editor.wrappingIndent == "same"`
![image](https://user-images.githubusercontent.com/538020/167387360-46473ad0-e79e-4af6-8eca-22b107caeaa8.png)

#### `editor.wrappingIndent == "indent"`
![image](https://user-images.githubusercontent.com/538020/167387500-6abfdb11-f222-4a94-a4ec-4ad1d632c5a0.png)

**Comment by ferdnyc** [comment]
**Update:** Note that this only occurs if the wrapped line starts in the left-most column. Indented, wrapped lines are not affected, regardless of `editor.wrappingIndent` setting.

**Comment by MonadChains** [comment]
Hi, I found the snippet that produces the bug:
https://github.com/microsoft/vscode/blob/2e3c24c08b438335fbf663a05c35ce0afa792833/src/vs/editor/common/viewModel/viewModelLines.ts#L575-L580
The **if statement** controls if the first character of the wrapped line is in column 0. If so, then it ignores the guides for that line.
By simply removing the if statement the result is the following:

![Screenshot from 2022-06-14 01-11-15](https://user-images.githubusercontent.com/105170638/173462251-37e04f9c-1f4e-4538-9adc-09de120ab61d.png)

It seems that this solves the bug. Given my limited knowledge of the codebase, before opening a pull request, it would be better to clarify the purpose of the **if statement** as it is not fully clear to me. Should it suppress possible **vertical** bracket guides in case of wrapped lines? Was it added to address a specific bug?

**Comment by hediet** [comment]
>  it would be better to clarify the purpose of the if statement as it is not fully clear to me.

I don't know anymore. Since unfortunately I didn't link that comment against any issue nor git blame helps here, lets just remove it and see if someone complains.

**Comment by ferdnyc** [comment]
> > it would be better to clarify the purpose of the if statement as it is not fully clear to me.
> 
> I don't know anymore. Since unfortunately I didn't link that comment against any issue nor git blame helps here, lets just remove it and see if someone complains.

I think I've solved it. You added the comment in 14437a770e727bbc9e5c561f268da1fdec83dfbf ("Implement line scopes."), which was a month before the implementation of horizontal guides (in 4e7516f9e141a121d599616842f9a807abe0e216). So, at the time, it made sense, but _horizontal_ guides invalidated the logic the check was based on.

**Comment by ferdnyc** [comment]
(Oh, and nice find, @MonadChains! Thanks for finding _and_ fixing this.)
