### ISSUE TITLE
usage with css modues

### ISSUE THREAD

**Issue by Truedrog** [Microsoft/vscode#14903]
- VSCode Version: 1.7.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. in tsx file i write `import styles from './styles.css';` and editor marking with the message: "[ts] cannot find module './styles.css'.

The project compiling fine. I can omit this by this: `const styles = require('./styles.css');` But import style is working in jsx, why it doesn't work in tsx?

**Comment by rebornix** [comment]
dup of #14539
