### ISSUE TITLE
Window: Title Bar does not disappear when on full screen

### ISSUE THREAD

**Issue by Gabriel-Alves-Cunha** [microsoft/vscode#149044]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
``` shell
$ code --version
1.67.0
57fd6d0195bb9b9d1b49f6da5db789060795de47
x64
```
- OS Version: Fedora 35 Linux 5.16.18-200.fc35.x86_64 GNU/Linux

Steps to Reproduce:

1. Open VSCode
2. Press `F11` to go to full screen
3. See that the 'Title Bar' has not disappeared

Screenshots:

![Screenshot from 2022-05-08 17-23-14](https://user-images.githubusercontent.com/52057747/167314447-f91c221c-839b-49de-ac78-c4fc6d58e2e1.png)
On the screenshot above, we have the vscode window maximized, the title bar is there as it normally would.

![Screenshot from 2022-05-08 17-23-24](https://user-images.githubusercontent.com/52057747/167314523-bbb8efd2-e217-4de9-afdf-bd3020e5bd01.png)
On the screenshot above, we have the vscode window at full screen. Before the last update, it would have disappeared, but now it stays there. Am I the only one experiencing this? I've tried looking at the settings but nothing fixes this.

**Comment by Gabriel-Alves-Cunha** [comment]
Hey, I did it. Still the same... First tried it without doing anything on it, than tried it with both native and custom.

Is this happening just with me?

![Screenshot from 2022-05-09 14-26-12](https://user-images.githubusercontent.com/52057747/167464377-e3afdf48-3ad1-4a0d-a171-b5528f25c8fd.png)

**Comment by sbatten** [comment]
@deepak1556 @rzhao271 either of you can repro this in one of your fedora machines?

**Comment by Gabriel-Alves-Cunha** [comment]
I just found out that going on the title bar menu 'View' -> 'Appearance' -> 'Full Screen            F11'
works and the title bar disappears! but pressing 'F11' does not work.

**Comment by sbatten** [comment]
@deepak1556 sounds like fedora is probably eating the event from us

**Comment by ewerybody** [comment]
I just updated to the latest insider version `1.74.0-insider` and see this issue for the first time ever!
Currently unable to solve it

**Comment by ewerybody** [comment]
Oh luckily this can be solved buy `"window.titleBarStyle": "native"` Pcheeew!
Still this is quite a sudden change.

**Comment by Gabriel-Alves-Cunha** [comment]
I recently had to install the OS from the ground and, naturally, install everything from the ground up. And now it is working perfectly.

**Comment by sbatten** [comment]
There is a recent regression in insiders for this when using the default settings on macos/windows

**Comment by deepak1556** [comment]
Unable to repro with Fedora 34, closing per https://github.com/microsoft/vscode/issues/149044#issuecomment-1321930582
