### ISSUE TITLE
Markdown drop into editor to create link. Url-encoded paths in link markdown.

### ISSUE THREAD

**Issue by GHSVS-de** [microsoft/vscode#149010]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Tried new feature [Markdown: Drop into editor to create link](https://code.visualstudio.com/updates/v1_67#_markdown-drop-into-editor-to-create-link)
2. Tried images and `*.md` files (same behavior for both types), dropped from left explorer sidebar like advised.
3. Get url-encoded paths in the link markdown like 

```
[Same folder](Parameter.md)
[Other folder](..%5CAstroid%5CStoffsammlung.md)
```
instead of

```
[Same folder](Parameter.md)
[Other folder](../Astroid/Stoffsammlung.md)
```

**Comment by TylerLeonhardt** [comment]
FYI this needs to be verified on Windows.
