### ISSUE TITLE
Css for Firefox on vscode 1.67 color-adjust issue

### ISSUE THREAD

**Issue by GrosBourrin** [microsoft/vscode#149002]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: Windows 10 x64
- Firefox 100.0 x64
hello all, 

Firefox css issue since vscode 1.67 : warning issue on "color-adjust" !
![Code_CR2qgSjWEa](https://user-images.githubusercontent.com/40931468/167265684-27ff02d5-60e7-4243-a43c-2b9a999c6546.png)

terminal explanation :
![Code_6tj7js9imb](https://user-images.githubusercontent.com/40931468/167265740-b1cd05e0-96d9-4a74-b203-54d68b1e2c41.png)

**Comment by aeschli** [comment]
`color-adjust` has been deprecated. See https://www.w3.org/TR/css-color-adjust-1/#color-adjust

That's why it's also not on MDN where we get our data from.

**Comment by GrosBourrin** [comment]
oh ok, thanks for info :)
