### ISSUE TITLE
Add support for CSS in JS syntax highlighting

### ISSUE THREAD

**Issue by oscar-b** [Microsoft/vscode#14905]
- VSCode Version: 1.6.1
- OS Version: Windows 10

It would be nice to get syntax highlighting for CSS in JS files, for instance when using [styled-components](https://styled-components.com/)

Example:

```javascript
import styled from 'styled-components';

const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  color: ${props => props.primary ? 'white' : 'palevioletred'};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export default Button;
```

Support already exists for Atom and Sublime :)
https://github.com/styled-components/styled-components#syntax-highlighting

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#342
