### ISSUE TITLE
Split in Group forces full width in Zen mode

### ISSUE THREAD

**Issue by alancnet** [microsoft/vscode#149185]
Issue Type: <b>Bug</b>

- Open a text editor
- (Ctrl-Shift-P) >View: Toggle Zen Mode
- Resize editor so it is thinner than 100% width
- (Ctrl-Shift-P) >View: Toggle Split Editor In Group

Editor will be 100% width.

Expected: Editor retains width set by user.

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1018-aws
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 4.19.104-microsoft-standard
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.4.0-91-generic
Remote OS version: Linux x64 5.4.0-91-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (25.19GB free)|
|Process Argv|--crash-reporter-id 41a4bf76-d3b6-4f75-9ae6-ced41da52289|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lightsail2|
|OS|Linux x64 5.4.0-1018-aws|
|CPUs|Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz (8 x 2299)|
|Memory (System)|31.36GB (15.77GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (24 x 3792)|
|Memory (System)|50.14GB (44.28GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: wizulus-home|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: alco|
|OS|Linux x64 5.4.0-91-generic|
|CPUs|AMD FX-8370 Eight-Core Processor (8 x 1930)|
|Memory (System)|31.33GB (0.49GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.13
eml|lei|0.4.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-apollo|apo|1.19.11
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.6
workspace|Foo|1.1.3
copilot|Git|1.17.5850
go|gol|0.33.0
svg|joc|1.4.17
vscode-docker|ms-|1.22.0
vscode-typescript-next|ms-|4.8.20220509
resourcemonitor|mut|1.0.7
volar|Vue|0.34.12

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216

```

</details>

**Comment by mitsukuri** [comment]
Also occurs in non-Zen mode when centered layout is enabled.
