### ISSUE TITLE
OS X - When quitting in fullscreen mode, it should reopen in full screen mode

### ISSUE THREAD

**Issue by andrewhathaway** [Microsoft/vscode#1491]
Just something I've noticed that should be standard behaviour for a Mac app. I use Code in full screen mode, and when I quit code and re open it, it reopens in a none-fullscreen mode!

**Comment by bpasero** [comment]
I am closing this as wont fix because I find it very disturbing that an application on startup would restore full screen. I know Parallels seems to do that and it drives me nuts all the time.

**Comment by iamthemovie** [comment]
Sublime does this. A lot of Mac Applications do this and it's not disturbing to me at all. Potentially one for a configuration?

**Comment by bpasero** [comment]
Fair enough.

**Comment by bpasero** [comment]
...and you tricked me, my Sublime 3 does not reopen in full screen mode ;)

**Comment by bpasero** [comment]
Nor do other apps on my Mac, I wonder if this is some global setting.

**Comment by iamthemovie** [comment]
That is strange...  what version of OS X are you using?

**Comment by bpasero** [comment]
10.11 El Capitan.

**Comment by Murriouz** [comment]
Sublime remembers last non-fullscreen window size and restore it when reopen. VSCode won't remember last non-fullscreen window size and atom will restore fullscreen when reopen. I think the sublime's behavior is the best.

**Comment by bpasero** [comment]
I added a new setting `window.restoreFullscreen` which by default is false.

I also restore full screen independently from this setting if you apply an update and VS Code restarts after you had been in full screen mode.
