### ISSUE TITLE
Color Bracketing Fails on SystemVerilog in certain contexts

### ISSUE THREAD

**Issue by michael-etzkorn** [microsoft/vscode#149111]
Does this issue occur when all extensions are disabled?:  Requires an SV extension 

keywords like `interface` and `end` are used for bracketing in SystemVerilog, but in some context they aren't brackets. The bracket highlighter does not pick up on this nuance ~~(also: it looks ugly and should be disabled by default or allow users to change the colors)~~.

![image](https://user-images.githubusercontent.com/88842659/167475348-3f480976-9781-42c1-b796-58f4fa2c79db.png)
![image](https://user-images.githubusercontent.com/88842659/167475538-fc3a211f-e7b2-43ee-bdd7-a4dc488944df.png)

- VS Code Version: 1.67.0
- OS Version: Microsoft Widows 10.0.22000.556

Steps to reproduce: 
1. TerosHDL (or SystemVerilog -Language Support by Eirik Prestegardshus) installed
2. add the following code:
```systemverilog
module testbench;
  vif my_vif;
  initial begin
    uvm_config_db#(virtual interface vif)::set(uvm_root::get(), "*", "vif", my_vif);
  end

  typedef enum {
    START,
    END
  } bracket_coloring_failure_e;

endmodule

```

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/updates/v1_62#_customizable-bracket-pairs for information about how you can configure which bracket pairs (if any) should be colorized for a particular language.

The extension author can also do this in its `language-configuration.json` file. For example [this one](https://github.com/eirikpre/VSCode-SystemVerilog/blob/master/language-configuration.json) defines `"brackets"` pairs but doesn't define any `"colorizedBracketPairs"` ones, so VS Code colorizes all the pairs listed in `"brackets"`.

Maybe open an issue on the repo of the extension you are using.

**Comment by hediet** [comment]
> but in some context they aren't brackets

Extensions can now configure which textmate tokens contain brackets and which tokens don't. This feature can be used to fix this issue.
