### ISSUE TITLE
Command "Shell Command: Install 'code' command in PATH" not found

### ISSUE THREAD

**Issue by hjapha** [microsoft/vscode#149148]
When I open my command palette in VSC and type this in, the command does not exist. (I am trying to open a VSC window on an Ubuntu machine)

**Comment by Tyriar** [comment]
That command is only available on macOS. If it's not there on Ubuntu you either didn't install (tarball?) or you have issues with your PATH.

**Comment by hjapha** [comment]
I am working on an Ubuntu machine. Is there a different command that can be used for an ubuntu machine?

**Comment by Tyriar** [comment]
No there is not, it should be on the path automatically. Try running echo `$PATH` and investigating why `/usr/bin` is not on your path.
