### ISSUE TITLE
git in container not finding .git folder

### ISSUE THREAD

**Issue by DanTaranis** [microsoft/vscode#149101]
Does this issue occur when all extensions are disabled?: yes
assist with this. -->
- VS Code Version:
-1.67.0
- OS Version:
ubuntu 20.04
Steps to Reproduce:
1. clone repo from github with Dockerfile
2. build docker 
3. open in docker 
4. reboot computer 
5. open again 
6. go to git page - see "no git  folder ..." message

**Comment by lszomoru** [comment]
@DanTaranis, sorry for not getting back to you on this. Could you share a repo that I can use to repro this? Thanks!
