### ISSUE TITLE
Add view description to API

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#149183]
![image](https://user-images.githubusercontent.com/35271042/167700824-794f757e-4188-4690-9b7b-9d05ca22a2d2.png)

The timeline view uses this `description` property next to the view title but I don't see this show up in the extension API. This would be a great addition for extension authors to leverage as opposed to using another tree item entry to communicate this.

cc @isidorn

**Comment by usernamehw** [comment]
I think it's already available to extension authors

https://github.com/microsoft/vscode/blob/2a9f19d36fe90248dec2c382f8fa460f69af6dbd/src/vscode-dts/vscode.d.ts#L9965-L9969

**Comment by alexr00** [comment]
Indeed it is, thank you!

**Comment by misolori** [comment]
Somehow I missed that when I was testing out locally, thanks for the reminder 🙃
