### ISSUE TITLE
Very prominent "Go to review" button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#149157]
<img width="628" alt="image" src="https://user-images.githubusercontent.com/900690/162614941-0f87e571-48d5-45fd-a8ed-787ee5c37875.png">

I often by accident click on the wrong button when adding a comment, imho this action is way too prominent there because it seems like the primary button to add the comment.

//cc @daviddossett also because both buttons have the same color

<img width="306" alt="image" src="https://user-images.githubusercontent.com/900690/162614984-3eb28826-49d1-41f5-a9a4-491b1d3db7ab.png">

**Comment by alexr00** [comment]
The **Start Review** button is a **Go to Review** button once you have already started a review. But since you verified the button colors this is still verified.
