### ISSUE TITLE
Allow interpolation coloring in template literal strings when using new JS/TS grammar

### ISSUE THREAD

**Issue by zackschuster** [Microsoft/vscode#14917]
- VSCode Version: 1.7.0 (or pre-1.7 with new grammar extension)
- OS Version: Windows 10

Steps to Reproduce:

1. Write a template literal string with interpolation: <code>\`test ${var}\`</code>
2. Before the new grammar was introduced, interpolation received special coloring
3. Post new grammar, interpolation is colored the same as the rest of the string

Personally, I find this far less readable when scanning template strings; I have to look more carefully than before to pick out where I'm interpolating an expression. Is there a way we can return the old coloring while respecting the new design decisions behind the grammar rewrite?

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#341

**Comment by waderyan** [comment]
Migrated to grammar repo.
