### ISSUE TITLE
Absence of VScode Intellisense

### ISSUE THREAD

**Issue by GodsentMichael** [microsoft/vscode#149121]
Issue Type: <b>Performance Issue</b>

Most of the Intellisense features and tags are not coming up e.g the color and inline styling of my html even css. 
what do I do?

**Comment by Tevvek** [comment]
Same here for vscode insiders of May 2022 (version 1.68).

**Comment by aeschli** [comment]
Do you have a small code sample? Maybe also a screenshot.

What is the language mode (in the status bar)?

**Comment by Tevvek** [comment]
In my case I found this while working with `class-validator` and typescript (it is set as typescript in the status bar). If I type i.e `@IsNumber()` in the code it says it has no suggestions:
![image](https://user-images.githubusercontent.com/9537497/167596827-3f48e8c9-4b74-44a8-a208-0f3db24c45dd.png)
but if I type inside the imports itself then it sees all:
![image](https://user-images.githubusercontent.com/9537497/167596954-623b9497-7ace-44f5-9da1-a02428b7eb24.png)

**Comment by aeschli** [comment]
Every language is different as language support comes from extensions.
@Tevvek Please file a separate issue as the original issue is about html and css.

**Comment by GodsentMichael** [comment]
Thanks just looking at your screenshot I have gotten the hook of it

**Comment by aeschli** [comment]
What does that mean, @GodsentMichael ? Looking at the screenshot solved your issue?

**Comment by GodsentMichael** [comment]
@aeschli I viewed your screenshot and I figured from what I saw there, maybe I altered my settings in json so I had to restore all default settings and it corrected, I got my vscode intellisense back.

**Comment by aeschli** [comment]
Cool! Thanks for update. I close the issue then.
