### ISSUE TITLE
path environment variable load twice 

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#149135]
VSCode integrated terminal:

![image](https://user-images.githubusercontent.com/41773861/167533056-18eb6fef-1a93-4978-acc7-c1d722a8da36.png)

Iterm2:

<img width="810" alt="image" src="https://user-images.githubusercontent.com/41773861/167533126-77c20ab5-7987-4e0f-8e99-01d23c238501.png">

ls-path:

```bash
function ls-path() {
  echo -e ${PATH//:/\\n}
}
```

terminal settings:

```jsonc
{
    "terminal.integrated.defaultProfile.osx": "zsh",
    "terminal.integrated.gpuAcceleration": "on",
    "terminal.integrated.shellIntegration.enabled": false,
}
```

version:

```
MacOS: 12.3.1
VSCode: 1.68.0-insider
```

@Tyriar
@meganrogge

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed
