### ISSUE TITLE
Integrated debugger - highlight values for variables as 'popups' when value changes (mimic Chrome debugger)

### ISSUE THREAD

**Issue by Matt4880** [Microsoft/vscode#14910]
- VSCode Version: 1.6.1 
- OS Version: Win 10

It would be nice to replicate a feature in the Chrome debugger in the VS Code debugger if possible (it may be a requirement in the Chrome remote debug extension or the Chrome remote debug API, but not sure).

If you are stepping through code and some variables/parameters are set or change value then these values are displayed in a tooltip-like display next to the assignment. This is nice to have as it highlights where things are changing in code and saves having to manually set up watches in a lot of cases.

![image](https://cloud.githubusercontent.com/assets/23239416/19968775/de8228ba-a1cd-11e6-964a-617e168f27fa.png)

Steps to Reproduce:

1. Open developer tools in Chrome
2. Step through some code

**Comment by isidorn** [comment]
Completly agree this is useful, however this is already captured in https://github.com/Microsoft/vscode/issues/13424
