### ISSUE TITLE
Support formatting of entire ipynb notebook on save

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#149117]
Feedback from PyCon 2022

"It'd be awesome to have automatic Black formatting on save, like Python does! I can format each cell right now, but I want to be able to format the entire notebook on a command, for example, on notebook save."

Also (somewhat) related to:
- https://github.com/microsoft/vscode-jupyter/issues/7058

**Comment by greazer** [comment]
We believe support for formatting notebooks with Black exists. However, there's still a need to support a "format_on_save" event from the VS Code api to accomplish this.

**Comment by rebornix** [comment]
From tomorrow's Insiders, you should be able to format on save by turning on `"notebook.formatOnSave.enabled": true`. We are looking into supporting format modified ranges (if you use SCM) soon.
