### ISSUE TITLE
Use debug adapter completions to improve IntelliSense in editor

### ISSUE THREAD

**Issue by alnorris** [Microsoft/vscode#14911]
Currently your able to inspect the current scoped variables, and write code whilst you have hit a break point. Would be a neat idea do be able to complement these with Intellisense autocomplete, since your currently at a breakpoint and you can see the types of variables anyway.

**Comment by rebornix** [comment]
@alnorris sorry I didn't understand your request clearly, do you mind sharing in what kind of circumstances you want to have the autocomplete feature? A screenshot will be better.

**Comment by alnorris** [comment]
<img width="882" alt="screen shot 2016-11-03 at 18 54 18" src="https://cloud.githubusercontent.com/assets/882627/19980752/2071574a-a1f7-11e6-90fd-3e267c30e2df.png">
<img width="1101" alt="screen shot 2016-11-03 at 18 54 43" src="https://cloud.githubusercontent.com/assets/882627/19980751/20704dbe-a1f7-11e6-9b77-7bbcf566f00e.png">

The first screenshot is at a breakpoint, in the local variables on the left the VS Code knows its that "arg" is an array, so it would be possible to provide auto complete similar to the second screenshot, whilst your paused at that breakpoint. This is just a simple example, can involve lots of other types.

**Comment by alnorris** [comment]
Another future idea also could be that VS Code could remember this information afters it out of debug mode, and provide auto complete on variables that have none,  even though it might not be 100% correct.
