### ISSUE TITLE
vscode ignoring .conf files for permanent flags

### ISSUE THREAD

**Issue by skysantoroa** [microsoft/vscode#149102]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: Ubuntu 22.04 LTS

Steps to Reproduce:

1. Create a `code-flags.conf` with the following lines
```
--enable-features=UseOzonePlatform
--ozone-platform=wayland
```
2. The vscode fonts look blurry

Tried renaming the file as `electron17-flags`, `chrome-flags` and `electron-flags` without success.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/134612

VSCode has its own persistent flag store which can be opened with `> Configure Runtime Arguments`, the support for above flags will be added as part of the above issue.
