### ISSUE TITLE
VSCode failed to updated due to bootstrap-amd.js

### ISSUE THREAD

**Issue by moody31415** [microsoft/vscode#149129]
Issue Type: <b>Bug</b>

I closed VS code, and it initiated auto update - which eventually failed with a dialog stating that it could not get a handle on C:\\Users\\<me>\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\out\\bootstrap-amd.js. I retried a few times before cancelling out. Afterwards, VSCode did not attempt to auto-update.

Separately, I had to disable uploading both my A/B experiment info and my system information because the issue reporter said that was apparently too much data for github. :(

Attached log file 
[vscode-inno-updater-1652141429.log](https://github.com/microsoft/vscode/files/8656166/vscode-inno-updater-1652141429.log)

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.22616
Restricted Mode: No

<details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
cpptools|ms-|1.9.8
vs-keybindings|ms-|0.2.1
vscode-scope|yiw|0.0.26

</details>

<html>
<body>

CPUs | Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.91GB (19.35GB free)
Process Argv | --crash-reporter-id 29e6670f-3245-4c5f-8a23-e9e7be340757
Screen Reader | no
VM | 0%

</body>
</html>
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdf:30486550

**Comment by ShadowXVII** [comment]
Duplicates #148953
