### ISSUE TITLE
File search (ctrl+e) does not find many of the files

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#14913]
I have a relatively large project, that is on a remote drive (mounted in windows) and the file search (ctrl+e) does not find many of the files. Is there maybe a way to increase some timeouts on indexing or something like that, that might be causing this? Or is there a limit on number of indexed files?

VSCode Version: Code 1.6.1 (9e4e44c, 2016-10-13T16:21:53.542Z)
OS Version: Windows_NT ia32 10.0.14393

/cc @PunchyRascal

**Comment by chrmarti** [comment]
@PunchyRascal Are you saying it finds some but not all files? Anything special about those it finds / doesn't find, like permissions / flags / anything?

**Comment by PunchyRascal** [comment]
Can't say, it seems pretty random really. Are there any resource limitations that might affect the finder? Such as time/cpu...)

**Comment by chrmarti** [comment]
No, it should collect all files. Is it always missing the same files or does the list of files change after restarting VSCode?

**Comment by PunchyRascal** [comment]
I guess the key here is patience - it seems if I wait long enough, it indexes the files I am looking for and finds them. So it goes down to the slowness of the remote drive connection I guess. Sorry. You can close this.

**Comment by chrmarti** [comment]
Thanks.
