### ISSUE TITLE
vscode freezes because of Bracket Pair Colorization

### ISSUE THREAD

**Issue by jshinonome** [microsoft/vscode#149130]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.67.0
- OS Version: Windows 11

Steps to Reproduce:

1. install jshinonome.vscode-q
2. add a q file, e.g. test.q
3. input `{f[{key x} x;1;x]}` and press enter
4. vscode freezes

I detected this before when I try to use the Bracket Pair Colorization plugin, but this feature is enabled by default, so I have to raise this issue. Also, this happens even if I disable it `"editor.bracketPairColorization.enabled": false`
Look at this weird color.
![image](https://user-images.githubusercontent.com/64458591/167519510-9b849100-87b3-4ef1-9176-62ab1909c3da.png)

`{f[{key x};1;x]}` works,
`{f[{key x} x;1;x]}` freezes.

Related issue https://github.com/jshinonome/vscode-q/issues/70

**Comment by hediet** [comment]
Thanks for reporting this!

> I detected this before when I try to use the Bracket Pair Colorization plugin, but this feature is enabled by default, so I have to raise this issue. 

Please also report bugs for non-default configuration, as this helps us to improve the quality of the product.

I will look into this very soon.

**Comment by hediet** [comment]
I think this got fixed with https://github.com/microsoft/vscode/pull/148772.

**Comment by jshinonome** [comment]
Thank you very much. I will take a look semantic highlight on my side as well.

**Comment by alexdima** [comment]
@jshinonome If you investigate, please post here the semantic tokens that you were returning for this line. I would like to double check that #148772 does indeed fix this case too.

**Comment by jshinonome** [comment]
> @jshinonome If you investigate, please post here the semantic tokens that you were returning for this line. I would like to double check that #148772 does indeed fix this case too.

Sure, I will let you know.

**Comment by alexdima** [comment]
I was also curious so I added a breakpoint to investigate. When the document is empty, there are no semantic tokens (`{ resultId: "1", data: [] }`), and then after pasting `{f[{key x} x;1;x]}` we get back a document semantic tokens edit with the following data:

```js
{
  resultId: "2",
  edits: [{
    start: 0, deleteCount: 0, data: [0, 11, 1, 1, 0, 0, 4, 1, 1, 0, 0, 4294967289, 1, 1, 0]
  }]
}
```

**Comment by jshinonome** [comment]
My extension returns 3 semantic tokens for `{f[{key x} x;1;x]}` in following order
1. 0 10 1 1 0 -> 2nd x
2. 0 14 1 1 0 -> 3rd x
3. 0 8 1 1 0 -> 1st x

**Comment by jshinonome** [comment]
I am thinking maybe I should not use 0 as tokenModifiers, the last number

**Comment by jshinonome** [comment]
I have fixed semantic tokens on my side, and vscode doesn't freeze anymore. Thank you very much for your help!! @hediet @alexdima
