### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by albertevieites** [microsoft/vscode#149190]
Issue Type: <b>Bug</b>

When I tried to use the terminal, suddenly dissapears.

VS Code version: Code 1.67.1 (Universal) (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id eed80dfc-dfc4-49ba-bb5e-b5e8abfde737 --crash-reporter-id eed80dfc-dfc4-49ba-bb5e-b5e8abfde737|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
search-crates-io|bel|1.2.1
emojisense|bie|0.9.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
regex|chr|0.4.0
vscode-eslint|dba|2.2.2
vscode-deno|den|3.12.0
vscode-wasm|dts|1.3.1
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
vscode-express-snippets|Exp|1.1.1
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
shell-format|fox|7.2.2
copilot|Git|1.19.5865
vscode-test-explorer|hbe|2.21.1
vscode-env|Iro|0.1.0
solidity|Jua|0.0.139
rust-analyzer|mat|0.2.1048
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.17
mongodb-vscode|mon|0.9.3
python|ms-|2022.6.0
vscode-pylance|ms-|2022.4.3
test-adapter-converter|ms-|0.1.6
vscode-typescript-next|ms-|4.8.20220509
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.5561
indent-rainbow|ode|8.3.1
betterfountain|pie|1.10.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
code-snapshot|rob|0.2.1
hbs-snippets|Ruh|2.2.0
vsc-quokka-statusbar|ske|1.3.6
wav-preview|suk|2.0.2
lua|sum|3.2.2
sass-indented|syl|1.8.19
org-mode|too|0.5.0
errorlens|use|3.4.2
vscode-icons|vsc|11.11.0
material-ui-snippets|vsc|3.3.8
vim|vsc|1.22.2
whichkey|VSp|0.11.3
quokka-vscode|Wal|1.0.468
fig|wit|0.0.6
txt-syntax|xsh|0.2.0
luahelper|yin|0.2.15
material-theme|zhu|3.13.25

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"
