### ISSUE TITLE
Deep nested folders' titles are invisible

### ISSUE THREAD

**Issue by polkovnikov-ph** [microsoft/vscode#149136]
Issue Type: <b>Bug</b>

- Create 20 or so nested folders with more than 1 file inside of each
- Uncollapse them in tree view on the left

Expected: horizontal scroll or decreased tabulation
Result: nested file names are invisible

VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by polkovnikov-ph** [comment]
![image](https://user-images.githubusercontent.com/2983969/167575675-3496460d-d27a-4813-b8bb-436bf04813eb.png)

**Comment by gjsjohnmurray** [comment]
/duplicate

See https://github.com/microsoft/vscode/issues/144120#issuecomment-1057062232
