### ISSUE TITLE
Proxy configuration doesn't work in VSCode

### ISSUE THREAD

**Issue by pemola** [Microsoft/vscode#14912]
- VSCode Version: 1.6.1
- OS Version: Windows 10

I'm testing VSCode by first time and I configure my proxy in settings.json as recommended:

"http.proxy": "http://domain\\user:pass@myproxy:port/"

But it doesn't work when I try to install new extensions I get a connected timeout error. I also try to configure the proxy as system enviroment variable with the same result.
¿Could you help me?¿Is it a bug or I'm doing something wrong?
Is there another way to download extensions?

Thank you very much!

**Comment by vsxen** [comment]
If you are using a HTTP(S) proxy you can configure apm to use it by running:

apm config set https-proxy YOUR_PROXY_ADDRESS

**Comment by rebornix** [comment]
Please check those links @vsxen provided as this kind of issue has been reported multiple times, you can find a proper solution there.
