### ISSUE TITLE
Some Code Colouring Issues

### ISSUE THREAD

**Issue by WebSpectrum** [microsoft/vscode#149198]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.67.1
- OS Version: Windows 11

Steps to Reproduce:

1. select curly bracket => ctrl+shift+p => scope
2. scope colour is not matched by actual colour of curly bracket
3. This may also be an issue with some other code elements

In recent versions of VSCode my code theme is not being rendered entirely accurately anymore

**Comment by gjsjohnmurray** [comment]
Sounds like bracket pair colotization. See #148977

**Comment by WebSpectrum** [comment]
Yes, thanks JOHN ... that solved it - will teach me not to read release notes!

**Comment by gjsjohnmurray** [comment]
👍

./duplicate
