### ISSUE TITLE
Incorrect error message: Can't install extension because it is not compatible with the current version of Visual Studio Code (version 1.67.0).

### ISSUE THREAD

**Issue by Ark-kun** [microsoft/vscode#149151]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67
- OS Version: Web

Steps to Reproduce:

1. Find extension with **only** pre-release version published
2. Click "Install" button
3. Get error despite the extension being compatible with VSCode version: `Can't install 'cloud-pipelines.pipeline-editor-vscode' extension because it is not compatible with the current version of Visual Studio Code (version 1.67.0).`

![image](https://user-images.githubusercontent.com/1829149/167615821-9f13dad5-320c-4153-b48a-f03eec6ea3c8.png)
Install pre-release works. However clicking "Switch to release version results in same error".

![image](https://user-images.githubusercontent.com/1829149/167615884-6ce75d96-ca4c-4d52-802a-5839efb11cab.png)

**Comment by sandy081** [comment]
This is fixed to show proper error. Please check our insiders.
