### ISSUE TITLE
Allow "Insert Cursor" keybinding to be configurable

### ISSUE THREAD

**Issue by oste** [Microsoft/vscode#14918]
- VSCode Version: 1.7.1
- OS Version: OSX Sierra

It does not appear that the Insert Cursor keybinding can be configurable. I would like to map it to the Sublimetext equivalent which is ```cmd+click```

Thanks.

**Comment by rebornix** [comment]
AFAIK, we don't have `Click` support in keybindings.

**Comment by alexandrudima** [comment]
Let's track in #3130
