### ISSUE TITLE
"Add Configuration..." to add a debug configuration uses type: "node" while debug provider uses type: "node-terminal"

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#149257]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.67.1 
- OS Version: macOS 12.3.1 arm64

Steps to Reproduce:

1. Open some Node.js project.
2. Add a launch configuration by using the "Add configuration..." floating button when `launch.json` is opened.
   <img width="272" alt="image" src="https://user-images.githubusercontent.com/24731903/167864583-5e3d81d4-16ef-4d22-a2cd-dce98e003b25.png">

3. Add a launch configuration by opening the quick pick (`Ctrl/Cmd+P`), typing "debug", selecting "Node.js...", and clicking with the mouse on the cogwheel in one of the suggested configurations.
   <img width="620" alt="image" src="https://user-images.githubusercontent.com/24731903/167865703-297ad8db-b089-462c-9d11-2bb176257c49.png">
   <img width="614" alt="image" src="https://user-images.githubusercontent.com/24731903/167865781-0e6b58b7-6b8c-4757-8dd9-a45c4e9d8562.png">

The configuration added by "Add configuration..." uses `"type": "node"`, while the one added by the debug quick pick uses `"type": "node-terminal"`.

I couldn't find clear docs showing the difference between them or when you should use one or the other, and I find it weird that those two flows produce inconsistent results.

There is also the "pwa-node" (And possibly "pwa-node-terminal"?) debug/launch types which I'm also not sure if should be used or not, and I couldn't find any docs for them either.

**Comment by roblourens** [comment]
`node-terminal` is used when running a program in a "javascript debug terminal" that automatically attaches to any node program. `node` is what you would use in a launch.json. `pwa-` prefixed types are sort of a historical leftover from the old node debugger implementation that we had a few years ago. `pwa-node` is now the same as `node` by default.

**Comment by segevfiner** [comment]
@roblourens Might want to add this to the main VS Code documentation. Including a recommendation for what users should use.
