### ISSUE TITLE
Feature Request: Make paths/urls in terminal output clickable

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#14925]
- VSCode Version: 1.8 Insider

In iTerm you can Cmd-Click file and urls, like this:

![image](https://cloud.githubusercontent.com/assets/4033249/19980070/e88bcf5a-a1b9-11e6-8185-723e3e445bff.png)

Would be great if we can allow Cmd-Click for:

- File -> Open in new tab
- Url -> Open in system browser

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/7321
