### ISSUE TITLE
I am not able to run notebooks

### ISSUE THREAD

**Issue by sdaza** [microsoft/vscode#149258]
Issue Type: <b>Bug</b>

I am using Code -Insiders. 

Suddenly, I start having this notification when running previously working jupyter notebooks: 

> Illegal state: service accessor is only valid during the invocation of its target method

Every time I run a cell with code (R, python), I get that notification.

VS Code version: Code - Insiders 1.68.0-insider (Universal) (8c882677f947ef7ec748e7f031c7b5470aaf9be1, 2022-05-11T05:18:23.731Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 7b0afbd9-9a02-4810-9d5f-58276a6f0f69|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
preview-pdf|ana|1.0.0
path-intellisense|chr|2.8.0
bracket-pair-colorizer-2|Coe|0.2.4
git-project-manager|fel|1.8.2
duplicate|gee|1.0.2
copilot|Git|1.19.5865
todo-tree|Gru|0.0.215
r|Iku|2.4.0
path-autocomplete|ion|1.19.1
stan-vscode|iva|0.2.3
mysql-syntax|jak|1.3.1
latex-workshop|Jam|8.26.0
vscode-edit-csv|jan|0.6.9
vscode-insertdatestring|jsy|2.3.1
better-line-select|kai|1.1.1
vscode-dashboard|kru|2.5.2
stata-enhanced|kyl|1.6.1
rainbow-csv|mec|2.3.0
vscode-docker|ms-|1.22.0
python|ms-|2022.7.11311004
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.5.1001331008
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.235.0
push|njp|0.8.21
advanced-new-file|pat|1.2.2
emoji|Per|1.0.1
material-icon-theme|PKi|4.17.0
create-file-folder|rit|0.0.5
vscode-fileutils|sle|3.5.0
html-preview-vscode|tht|0.2.5
vscode-todo-highlight|way|1.0.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebug:30475216
vsclangdf:30480126

```

</details>

**Comment by gjsjohnmurray** [comment]
See also  #149242
