### ISSUE TITLE
Prevent quick pick from opening when dragging title bar over search input

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#149299]
https://user-images.githubusercontent.com/35271042/167963676-389beeb6-26b0-433f-a1ba-c3ee36adc989.mp4

Would be great if when the user starts dragging the window around when on the search input that we ignore the click to prevent the quick pick from opening

**Comment by jrieken** [comment]
To fix https://github.com/microsoft/vscode/issues/149290 I made the title menu not draggable. That change has also fixed this issue

**Comment by misolori** [comment]
I actually liked being able to drag the window around from the title menu 😂 [someone on twitter](https://twitter.com/koorogi/status/1524529403107102720) was complaining about this, which prompted this issue

**Comment by jrieken** [comment]
I don't know if there is a way to achieve both...  @sbatten Do you? Can an element be a "window drag handle" _and_ a clickable area? Issue #149290 gave me the impression that it isn't doable

**Comment by sbatten** [comment]
not on windows, if the region is draggable, we will never get mouse events from it
