### ISSUE TITLE
Last update broke things...

### ISSUE THREAD

**Issue by ewenmic** [microsoft/vscode#149232]
Issue Type: <b>Bug</b>

After updating to the latest update my color theme stopped being supported (only some colors are shown correctly - switching to different themes also has the same ugly color being shown for certain elements) 
I also randomly got VS studio code settings errors when saving a file (seems to have disappreared at the moment)

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1700X Eight-Core Processor          (16 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.93GB (25.42GB free)|
|Process Argv|--crash-reporter-id c21d2e72-42b5-4bb2-bfc5-e838104fbedf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
json-parse-validator|Adr|1.1.2
armview|ben|0.4.6
random-string-password-generator|bib|1.0.2
xslt-xpath|del|1.2.5
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.42.0
gitkraken-authentication|git|1.0.3
go|gol|0.33.0
terraform|has|2.22.0
randomeverything|hel|0.0.3
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
firebase-explorer|jsa|0.3.3
json2csv|kha|0.0.1
vscode-github|Kni|0.30.7
rainbow-csv|mec|2.3.0
vscode-language-babel|mgm|0.0.36
vscode-html-format|moh|0.0.4
vscode-azureresourcegroups|ms-|0.4.0
vscode-azurevirtualmachines|ms-|0.5.0
vscode-bicep|ms-|0.6.1
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.2.0
python|ms-|2022.6.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
azure-account|ms-|0.10.1
vscode-typescript-next|ms-|4.8.20220510
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-streamdeck|nic|4.1.6
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.7.0
glassit|s-n|0.2.4
vscode-scss-formatter|sib|2.4.2
swdc-vscode|sof|2.6.30
tech-debt-tracker|Ste|0.28.4
ms-teams-vscode-extension|Tea|3.8.0
pdf|tom|1.2.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment]
Did you see the release notes item about bracket pair colorization?

**Comment by lorand-horvath** [comment]
https://github.com/microsoft/vscode/issues/148977#issuecomment-1120139318

**Comment by hediet** [comment]
I'm sorry it doesn't work for you. Can you share a screenshot?

**Comment by Vishnu053** [comment]
After the last update, it seems the file changes watcher is not working. File save does not trigger hot-reloading in my vue.js application. I have to manually re-run my application after each save.

**Comment by gjsjohnmurray** [comment]
@Vishnu053 that sounds like a different issue.

**Comment by lorand-horvath** [comment]
@Vishnu053 I've just tried modifying main.js in a Vue CLI 5 app started in VSCode 1.67.1 terminal and hot reloading works just fine. You may be having other issues. If you're using @vue/cli 5, you might try re-installing it globally. Also notice the latest webpack update https://github.com/webpack/webpack/releases/tag/v5.72.1 mentions "fix __webpack_nonce__ with HMR" in the release notes... so that might be giving you issues. My app is still using using webpack 5.72.0.
If you're still having issues after updating your dependencies, you might want to open a new issue, as @gjsjohnmurray suggested and tag me there so we can test further.

**Comment by Vishnu053** [comment]
@lorand-horvath @gjsjohnmurray  reinstalling my vs-code did the trick! Maybe something broke while updating I guess. Thank you so much for your inputs.

**Comment by ewenmic** [comment]
> Did you see the release notes item about bracket pair colorization?

I did not - just disabled the feature and everything is working as normally. Thanks for the reply!
