### ISSUE TITLE
VS Code insiders freezes every time I lock my PC

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#149247]
I can only reproduce this on one of my Windows computers (the one that I access through Remote Desktop).

1. Open VS Code insiders
2. Lock PC
3. Unlock PC
4. VS Code insiders is frozen

I double checked with VS Code stable, and there is no freezing there.

**Comment by fmod-mathew** [comment]
I've been seeing this for a while now however I don't think it's specific to VS Code. I'm seeing the same behavior for Edge and Terminal, however all other apps are fine. It's possible all three share some common framework and root cause though.

**Comment by alexr00** [comment]
I still see this too, but only on one of my machines. The other is fine.

**Comment by learning310** [comment]
> I've been seeing this for a while now however I don't think it's specific to VS Code. I'm seeing the same behavior for Edge and Terminal, however all other apps are fine. It's possible all three share some common framework and root cause though. I've found a GitHub issue in the Terminal repo that looks similar to what I'm seeing [microsoft/terminal#12607](https://github.com/microsoft/terminal/issues/12607).

I also find same problem on my computer, every time when you reconnect remote desktop it will happen。

**Comment by liberize** [comment]
same here.

**Comment by willl** [comment]
> I also find same problem on my computer, every time when you reconnect remote desktop it will happen.

Local and Remote PC are both running Windows 11 22H2.

If I leave VS Code open, disconnect my remote desktop and reconnect I'll see VS Code be unresponsive and after a few seconds will say `The window is not responding. You can reopen or close the window or keep waiting.`

![image](https://user-images.githubusercontent.com/926823/200198572-61ff42b2-0ce4-4c69-850f-c6138b805522.png)

**Comment by hunterxueMS** [comment]
Same issue here, Microsoft Teams and Visual Studio Code are the most frequent ones, can be reproduced almost every time. Really annoying, must due to bugs in some kind of the rendering framework shared by these applications.

**Comment by danielkatusele** [comment]
I also see the same issue any time I log in to my remote computer on Windows 11. Also, sometimes, wsl2 does not reconnect after I wait for about 5 to 10 minutes

**Comment by talha5389** [comment]
- After upgrading to Windows 11, most of the time when I connect to windows 11 machine via RDP running VSCode or chrome (these are apps I noticed issue with), become non-interactable. It also happens most of time if I disconnect RDP connection and login to machine physical after RDP has disconnected.
- It does not happen if there was no RDP connection between user lock/unlock.
- Another thing I want to point out is that when I use RDP, my resolutions switched between 1080p and 4k and I can see windows being resized. Maybe something in windows 11 causes it to become unresponsive when adjusting windows sizes to new resolution.
- I can remember it happening for chrome and vscode. I don't think Windows explorer ever had this issue so maybe, issue is with chromium engine used by chrome and vscode (electron)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167556
