### ISSUE TITLE
Source control actions should be idempotent 

### ISSUE THREAD

**Issue by cgarrovillo** [microsoft/vscode#149204]
Issue Type: <b>Bug</b>

1. Add a git hook that is performed before a commit
2. Click "Commit" more than once in quick succession

<img width="206" alt="image" src="https://user-images.githubusercontent.com/6688713/167744762-8317e05d-00fd-43fa-a5a7-ecd326fb683c.png">

3. Notice that the commit hook runs more than once,  which can cause issues

<br/>

This issue came up through [this issue](https://github.com/okonet/lint-staged/issues/1151) I submitted for `lint-staged`.  But really the crux of the issue is that the buttons in source control should only trigger actions once -- increasing stability & predictability

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|admin.code-workspace --crash-reporter-id 1a30a612-716c-42e1-b5ad-acd2f84d2392|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
gitlens|eam|12.0.6
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.6
auto-rename-tag|for|0.1.10
go|gol|0.33.0
terraform|has|2.22.0
python|ms-|2022.6.1
vscode-pylance|ms-|2022.4.3
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.17.0
vscode-yaml|red|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by lszomoru** [comment]
This should be resolved as when "write" commands (ex: commit) are initiated, **all** commands are being disabled until the command completes. This should prevent multiple commit operations being initiated. I will close this issue but please feel free to reopen it in case you are still able to reproduce the problem. Thanks!
