### ISSUE TITLE
Settings editor resizes when focusing in and out

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#149216]
https://user-images.githubusercontent.com/35271042/167768281-b9eab3f5-79cb-407a-abb4-8bc695bf095f.mp4

Setup a 2x1 editor grid and have the settings editor on one side. When moving focus between the settings editor and another one, the settings editor will resize itself automatically.

Version: 1.68.0-insider (Universal)
Commit: ba8ced85c51569bbc2c51a24398c15ed6b61d8d3
Date: 2022-05-11T00:05:57.477Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

**Comment by rzhao271** [comment]
Closing as not planned since this issue occurs with split text editors in general when one text editor is much wider than another.
