### ISSUE TITLE
Some terminal launch config args are double-escaped

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#149283]
Run this launch config

```json
{
    "type": "node",
    "request": "launch",
    "name": "Run",
    "runtimeVersion": "16.4.0",
    "program": "${file}",
    "console": "integratedTerminal",
    "args": [">", "> hello.txt"]
},
```

This creates a file named `\> hello.txt` with a literal backslash, when it should be named `> hello.txt`

**Comment by roblourens** [comment]
Also, the scenario in https://github.com/microsoft/vscode/issues/149357

**Comment by StefanXhunga** [comment]
Thank you for this assistance

**Comment by MdJamilhasan** [comment]
my code runner launch just html code. how to fixed it? can't run css file with html
