### ISSUE TITLE
Typescript string interpolation syntax highlighting broken after 1.6 -> 1.7.1 upgrade

### ISSUE THREAD

**Issue by JohannesRudolph** [Microsoft/vscode#14926]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-docker|PeterJausovec|0.0.7|
|vscode-yaml-validation|djabraham|0.0.1|
|python|donjayamanne|0.5.0|
|vscode-style-formatter|dweber019|0.0.2|
|tslint|eg2|0.5.39|
|Go|lukehoban|0.6.47|
|csharp|ms-vscode|1.4.1|
|vscode-subword-navigation|ow|1.1.5|
|tsimporter|pmneo|1.2.9|
|Ruby|rebornix|0.10.1|

---

Steps to Reproduce:

1. Create a valid typescript file with string interpolation like below: 
![image](https://cloud.githubusercontent.com/assets/130103/19980427/4890d4d8-a1fe-11e6-999e-064bbfd57af2.png)

Notice that the string is "flat" and everything colored the same. Version 1.6 highlighted the `${}` expressions.

**Comment by JohannesRudolph** [comment]
Will this get reviewed for VSCode 1.8?

**Comment by rebornix** [comment]
Sorry for putting it on my list for too long. Assign it to correct owner.

**Comment by mjbvz** [comment]
@JohannesRudolph I believe this has since been fixed. Here's a test snippet in VScode 1.11 with Monokai:

![screen shot 2017-04-05 at 2 59 06 pm](https://cloud.githubusercontent.com/assets/12821956/24728829/811e4508-1a10-11e7-93f0-5a8f18dfacf4.png)


Please let me know if you still see this issue

**Comment by JohannesRudolph** [comment]
Indeed, it appears to be fixed in 1.11 (but wasn't in 1.10). Thank you!
