### ISSUE TITLE
Can't select the hit condition UI?

### ISSUE THREAD

**Issue by actboy168** [Microsoft/vscode#14927]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|lua-debug|actboy168|0.0.11|
|status-bar-tasks|GuardRex|0.1.0|
|cpptools|ms-vscode|0.9.2|
|color-highlight|naumovs|1.2.1|

---
![gif](https://cloud.githubusercontent.com/assets/1836844/19980895/c25662d8-a23a-11e6-8bcc-ad5faa132699.gif)

Steps to Reproduce:

1.
2.

**Comment by octref** [comment]
@actboy168 
Don't use `=2`. Use 2 instead.

But I think we should still do input validation.

**Comment by isidorn** [comment]
Input validation -> dup of https://github.com/Microsoft/vscode/issues/14364

**Comment by actboy168** [comment]
'2' is the same.
![gif](https://cloud.githubusercontent.com/assets/1836844/19995130/5de9a274-a28f-11e6-80f6-14c338171597.gif)
The UI tell me, '2'  is a condition and it is not a hit condition.

**Comment by actboy168** [comment]
http://code.visualstudio.com/docs/editor/debugging#_hit-count-condition
In the doc, '=2' is valid.

**Comment by octref** [comment]
@actboy168 
Sorry my bad. `=2` is valid. Haven't used much of this feature 😛 

Can you try setting conditional breakpoints **before** you start debugging?

@isidorn This happens if you set conditional breakpoints after you've started debugging.

**Comment by actboy168** [comment]
![gif2](https://cloud.githubusercontent.com/assets/1836844/19995947/c3e80e88-a296-11e6-81c1-a219c2fb7ee6.gif)

**Comment by octref** [comment]
Are you using `node2` in your `launch.json`? Can you change that to `node` and see if it works?

I'm also able to repro with this setup:

![image](https://cloud.githubusercontent.com/assets/4033249/19996240/65e354c6-a21b-11e6-8856-35b1f757cb29.png)

**Comment by actboy168** [comment]
Yes, node2. And the same to node.

**Comment by weinand** [comment]
@roblourens does node2 support hit count conditions?

**Comment by roblourens** [comment]
No, the UI doesn't get disabled in that case?

**Comment by weinand** [comment]
@roblourens breakpoint configuration is global and independent from a debug adapter. So the UI for configuring breakpoint conditions and hitcount expressions is always available.

@isidorn we need to find a UI that communicates to the user upon session start that a configured breakpoint condition and/or hitcount expression is actually ignored by a debug adapter.

**Comment by roblourens** [comment]
Ah right. They could go gray when you start debugging with a message, "Hit condition breakpoints aren't supported by XYZ". Also I filed an issue on myself to implement these. https://github.com/Microsoft/vscode-chrome-debug-core/issues/125

**Comment by weinand** [comment]
The breakpoint will probably work but the expressions are ignored. So we could show the red disk but remove the '=' from it.

**Comment by actboy168** [comment]
Which debugger adapter supports hit condition breakpoints?
I try to support hit condition breakpoints in my debugger adapter, but I found the vscode however will only give me a condition breakpoint not a hit condition breakpoint.

**Comment by weinand** [comment]
@actboy168 as far as I know only Node Debug (debug type = "node") supports hit conditions at the moment. But this can change at any time. Please check the release notes of the debug extensions you are interested in.

**Comment by weinand** [comment]
This works for me:

![2016-11-14_13-19-27](https://cloud.githubusercontent.com/assets/1898161/20264721/4c530c0e-aa6d-11e6-9a78-13bc5dc112c9.gif)
