### ISSUE TITLE
Word/symbol highlighting stays on when it absolutely should not

### ISSUE THREAD

**Issue by claytoneast** [microsoft/vscode#149210]
Does this issue occur when all extensions are disabled?: **Yes**

Versions: (from `About Visual Studio Code`)
Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

- VS Code Version: 1.67.1 (Universal)
- OS Version: Mac OSX Big Sur 11.5.2 (20G95)

Steps to Reproduce:

1. Write some code
2. Use default keyboard shortcut (`cmd+d`) to select/select multiple of a word
3. Text stays highlighted even when I click away or highlight other things (highlights keep stacking)
4. If the video doesn't explain this^ then I don't know what will

Please send help, I'm in a glass cage of highlighted emotion

https://user-images.githubusercontent.com/13628644/167756592-df4e8bbc-4b10-4370-89a1-703369ee8bd5.mov

**Comment by gjsjohnmurray** [comment]
Is this #148893?

If so it is scheduled to be fixed in upcoming 1.67.2

**Comment by claytoneast** [comment]
Yes it is. I will close this issue. Apparently I didn't search back far enough in the GH issues (so many issues on this repo...)
