### ISSUE TITLE
Source Control broken and some other issues

### ISSUE THREAD

**Issue by prinzhoefte** [microsoft/vscode#149297]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Code - OSS 1.67.1
- OS Version: x86_64 Linux 5.17.4-artix1-1

Since the last update my Source Control and some other things broke. 
Every time I start VS code, I am getting asked if I trust the authors of my Workspace. No matter how often I press okay, it always comes back. 
The layout also resets every time I start it up. 
My Source Control does not work at all anymore. I have had 6 GitHub and 1 GitLab Repos, and non of them show up anymore.
I also can not even click the "Initialize Repository" button, as it is greyed out.
And the last point is, that saving files, now takes ages. 

Please let me know, if you need any further information. 
I would really appreciate it, if you could fix the bug as fast as possible as I am unable to work at the moment.

**Comment by lszomoru** [comment]
@prinzhoefte, are you able to reproduce all these issues if you start VS Code using `code --disable-extensions`?

**Comment by prinzhoefte** [comment]
Yes, it still happens. I tried it on my Laptop with the same OS and it still happens on a clean installed OS/VS Code

**Comment by prinzhoefte** [comment]
Seems to be fixed in the new version.
