### ISSUE TITLE
Can't execute notebook cells

### ISSUE THREAD

**Issue by ghylander** [microsoft/vscode#149242]
Issue Type: <b>Bug</b>

Just updated VSC and I can no longer execute jupyter notebook cells

This happens when working both in local and connected to a SSH host, both with python and markdown cells

I get the following error:

`Illegal state: service accessor is only valid during the invocation of its target method`

Checked the output every extension and log, there's no errors or no clue as to what is happening.

VS Code version: Code - Insiders 1.68.0-insider (8c882677f947ef7ec748e7f031c7b5470aaf9be1, 2022-05-11T05:17:12.474Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.4.0-1072-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (1.88GB free)|
|Process Argv|--crash-reporter-id 4285aea8-8024-49ba-97f2-9d60622a70f0|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: AWS|
|OS|Linux x64 5.4.0-1072-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (8 x 2840)|
|Memory (System)|30.91GB (28.53GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.235.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
python|ms-|2022.6.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.5.1001331008
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebugcf:30475217
vsclangdc:30480125

```

</details>

**Comment by ghylander** [comment]
Snapshot of message:
![image](https://user-images.githubusercontent.com/74593034/167820768-9b4c165e-de6d-48dd-bac7-de67e38e4507.png)

I would post snapshots of the outputs of extensions and logs, but there is no output whatsoever generating when attempting to run a cell

**Comment by eo1989** [comment]
Same.

**Comment by scherp14** [comment]
I was able to workaround this issue by using the command "Notebook: Execute Cell".

**Comment by austinmw** [comment]
same

**Comment by eo1989** [comment]
> I was able to workaround this issue by using the command "Notebook: Execute Cell".

Via the command palette? (Cmd/Ctrl+shift+p)?

**Comment by scherp14** [comment]
> Via the command palette? (Cmd/Ctrl+shift+p)?

Yep, that's how I first found it. You can also invoke the command directly from a cell with ctrl+alt+enter.

**Comment by andrew-weisman** [comment]
Same problem here too, thanks in advance for addressing!

**Comment by msaminnorouzi** [comment]
I fixed it by determining the keyboard shortcut again. (ctrl + enter)
However, the run icon still does not work. But the shortcut works.

**Comment by ghylander** [comment]
run icon or regular shortcuts (shift+enter, ctrl+enter) did not work form me, only ctrl+alt+enter did

anyways, seems to be fixed with @roblourens PR, thanks for the quick response

**Comment by fschiffers** [comment]
@ghylander How can I activate the PR in Insiders?

**Comment by ghylander** [comment]
fix was already released for the VSC insiders build, update your installation

**Comment by wyh196646** [comment]
when I run jupyter notebook，i type three words  in it,the window can't response occur,then the vscode crushed,what should i dot to slove this problem
