### ISSUE TITLE
TS Server fatal error:  Debug Failure. False expression.

### ISSUE THREAD

**Issue by vire** [microsoft/vscode#149253]
Issue Type: <b>Bug</b>

❗️❗️❗️ Please fill in the sections below to help us diagnose the issue ❗️❗️❗️

**TypeScript Version:** 4.6.3-sdk

**Steps to reproduce crash**
1.
2.
3.

**TS Server Log**
❗️Server logging disabled. To help us fix crashes like this, please enable logging by setting:
```json
"typescript.tsserver.log": "verbose"
```
After enabling this setting, future crash reports will include the server log.

**TS Server Error Stack**
Server: `semantic`

VS Code version: Code 1.67.1 (Universal) (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 5|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|--crash-reporter-id bcfe9632-17b0-491f-8c63-2f82b1f5db2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
vscode-zipfs|arc|3.0.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
vscode-jest-runner|fir|0.4.48
auto-close-tag|for|0.5.14
vscode-graphql|Gra|0.4.4
search-node-modules|jas|1.3.0
yarn-lock-syntax|mar|0.1.3
ts-error-translator|mat|0.5.1
vscode-styled-components|mf|0.2.2
dotenv|mik|1.0.1
python|ms-|2022.6.1
vscode-pylance|ms-|2022.4.3
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
color-highlight|nau|2.5.0
angular-console|nrw|17.16.0
tsimporter|pmn|2.0.1
vscode-yaml|red|1.7.0
code-spell-checker|str|2.1.11
unique-window-colors|stu|1.0.51
tabnine-vscode|Tab|3.5.45
vim|vsc|1.22.2
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaat:30438848
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Closing as not useful without more information
