### ISSUE TITLE
Update Electron to 17.4.3

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#149223]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.1
- OS Version: Win 7 x64

Steps to Reproduce:

1. Please update Electron to 17.4.3 https://github.com/electron/electron/releases/tag/v17.4.3

**Comment by sneila** [comment]
Does this fix the high CPU usage on OSX? (introduced in 1.67.0)

**Comment by vhscom** [comment]
> Does this fix the high CPU usage on OSX?

God I hope so. This editor is starting to turn into a real heater on my 2019 MBP. And all of a sudden after the April update I've got major performance issues and downgrading doesn't help. Ugh.
