### ISSUE TITLE
Finalize notebookEditor API proposal 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#149271]
Splitting off from https://github.com/microsoft/vscode/issues/125758

The notebookEditor API proposal looks to be in good shape. We may revise a few names or functions, but otherwise I think it is ready for testing and finalization

**Comment by rchiodo** [comment]
Works fine for us. I don't think we'd need any changes.

**Comment by joyceerhl** [comment]
No further feedback, RemoteHub's use of `notebookEditor` is due to a change from @roblourens to contribute the continue on action to `notebook/cell/executePrimary`. This should eventually not be necessary due to https://github.com/microsoft/vscode/issues/141293

**Comment by tanhakabir** [comment]
No feedback from me as well.

**Comment by alyssajotice** [comment]
No further feedback.

**Comment by mjbvz** [comment]
Thanks for the feedback! We believe the API is ready for finalization so I've submitted a PR that moves it over. A few minor changes for adopting it:

- We've renamed `NotebookEditor.document` to `NotebookEditor.notebook`. The old property is kept for backcompat but marked deprecated

- We've removed the `showNotebookEditor` overload that takes a `Uri`. Instead you can use `openNotebookEditor` + `showNotebookEditor` with a `NotebookDocument`
