### ISSUE TITLE
Bug with Changing a Folder's name

### ISSUE THREAD

**Issue by mrgreen8** [microsoft/vscode#149287]
VC Code is not detecting to delete an older folder when a letter in the a folder's name is changed (renamed) to a capital letter, however it does work if characters are added to the original folder name.

**Comment by gjsjohnmurray** [comment]
Please also provide version and platform information.

**Comment by mrgreen8** [comment]
When I reported the bug, it was in an older version. My laptop has been updated to 1.65.2. OS is Windows_NT x64 10.0.19042.

When a folder, like an Angular Component folder’s name is changed from applicantnames to applicantNames (lowercase to lowerCamelCase), VS Code is not recognizing that the lowercase files and folder need to be deleted.

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/94307
