### ISSUE TITLE
Go > Go to definition / F12 broken for basic JS / npm

### ISSUE THREAD

**Issue by jjpepper** [microsoft/vscode#149229]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

two basic files:
```
// bar.js
const hello = 'hello';

module.exports = {
  hello
}
```
```
// foo.js
const bar = require('./bar');
```

package.json
```
{
  "name": "bar",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

![image](https://user-images.githubusercontent.com/10545251/167789410-b937a21d-359e-4c13-8b20-f67744da5e87.png)
I have reinstalled vscode and deleted the ~/.vscode-server directory

Note that the ctrl-click also doesn't work and right-click on the path to the file menu does not contain "go to definition"

Problem occurs in windows, wsl and inside a devcontainer.  Installing TS/JS Nightly has no impact.

This issue is just driving me crazy!!  Anyone with any tips, please help!

![image](https://user-images.githubusercontent.com/10545251/167791499-6d7a1497-beb5-4573-bf26-d1757e12066f.png)

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command in case one of your extensions is crashing the Extension Host process.

**Comment by jjpepper** [comment]
oh wow @mjbvz I have no idea how that got turned off, I didn't know it existed, but thanks sooooo much!  It means a lot, this has been such a pain.  I wonder if another extension could have turned that off or something?
