### ISSUE TITLE
Extensions workspaces manager

### ISSUE THREAD

**Issue by Juliapp** [microsoft/vscode#149274]
I'm a vscode extensions lover, and I can't handle myself searching for a bunch of new extensions to let my life easier. It happens that some of them costs a lot in the RAM to be enable, even tho I'm not currently using it. It's very boring to disable every extension I'm not using. It would be good if we could create extensions workspaces manager and enable a group of extensions whenever we want it.

**Comment by gjsjohnmurray** [comment]
I suggest you start using this 1.67 preview feature and provide feedback.

https://code.visualstudio.com/updates/v1_67#_settings-profile
