### ISSUE TITLE
Can't run my code at terminal

### ISSUE THREAD

**Issue by JustAnotherNick** [microsoft/vscode#149280]
ADD ISSUE DESCRIPTION HERE
I get a "permission denied" answer every time I'm trying to execute code at terminal. I have registered a new account and got the same problem. I tried to register an ssh key, it didn't help.

Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36
Embedder: codespaces

**Comment by Tyriar** [comment]
Please report Codespaces issues to [GitHub support](https://support.github.com/?tags=dotcom-footer)
