### ISSUE TITLE
VSCode Upgrade Linux 64bit tries to install 32bit deps

### ISSUE THREAD

**Issue by fcntl** [Microsoft/vscode#14928]
- VSCode Version: 1.7.1
- OS Version: Fedora 24 x64

Steps to Reproduce:

1. install previous version of vscode (e.g. 1.6.1)
2. download and upgrade rpm using 'yum install vscode171.rpm'

Observe packages to be isntalled/upgraded:
=========================
Installing:
 glibc                    i686         2.23.1-10.fc24             updates            4.3 M
 libX11                   i686         1.6.3-3.fc24               fedora             616 k
 libXScrnSaver            i686         1.2.2-10.fc24              fedora              28 k
 libXau                   i686         1.0.8-6.fc24               fedora              34 k
 libXext                  i686         1.3.3-4.fc24               fedora              43 k
 libxcb                   i686         1.11.1-2.fc24              fedora             205 k
 nss-softokn-freebl       i686         3.27.0-1.0.fc24            updates            209 k
Upgrading:
 code                     x86_64       1.7.1-1478180561.el7       @commandline        48 M
=========================

There is no good reason a 64bit package should be trying to install 32bit deps it can't possibly be linking against. This is annoying as I don't want to have any 32bit crap on my system.

**Comment by Alexhuszagh** [comment]
Confirming I have the same issue, and I should also add that it uses the 32-bit search (`/usr/lib`, rather than `/usr/lib64`) path by default (I'm assuming).

For example, one dependency, libXScrnSaver had the 64-bit version installed, however, VS Code would not install until a symlink or the 32-bit version of the library was installed. (`sudo dnf install libXScrnSaver-1.2.2-10.fc24.i686` or `sudo ln -s /usr/lib64/libXss.so.1 /usr/lib/libXss.so.1`).

**Comment by polygotdev** [comment]
@Alexhuszagh i did a run thru using the livecd of Fedora x64 and didn't come across the need to create any symlinks in this specific case. For future users that might come across this thread, here's the log of the steps taken to help others with any troubleshooting:

- Fedora-Workstation-Live-x86_64-24-1.2.iso

https://gist.github.com/polygotdev/e746e52346090300c20e1bbe16db780b

![about](https://cloud.githubusercontent.com/assets/18198056/19990991/9a28fec6-a1f7-11e6-8f2f-0c1772dd6add.png)

**Comment by Alexhuszagh** [comment]
Interesting, it's likely an issue on my end then. I did remove Gnome and most of Gnome's dependencies, and am using a KDE environment, but I would not expect you to cater to every Linux user's configurations to avoid making a symlink.

Thanks for the quick response.

**Comment by Jackson-soft** [comment]
I have the same issue,

![image](https://cloud.githubusercontent.com/assets/3928114/19993792/61acfcf4-a216-11e6-80d3-8c4caac0da2a.png)


![image](https://cloud.githubusercontent.com/assets/3928114/19993811/77976a22-a216-11e6-831f-e42417a6363e.png)
 
and i am using  KDE environment

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13616
