### ISSUE TITLE
Activating extension failed: ENOENT: no such file or directory, open '../../package.json'.

### ISSUE THREAD

**Issue by HaoboGu** [microsoft/vscode#149211]
Hello, I'm trying to develop a new extension but I encountered an error after I activated the extension:
<img width="398" alt="image" src="https://user-images.githubusercontent.com/8640918/167757809-cd4f6231-3aa6-424f-bac2-cda8b51c75f0.png">
My project is at `/Users/haobgu/Project/typescript/demo`, it seems webpack finds wrong `package.json`.

I tried to debug it, and in the generated `dist/extension.js`, I found this: 
<img width="980" alt="image" src="https://user-images.githubusercontent.com/8640918/167758208-4f12e5d5-a8f4-4cf4-8f17-8f406b2506fc.png">

change `'../../package.json'` to `../package.json` fixes this but everytime it rebuild, the error occurs again

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: MacOS

Steps to Reproduce:

1. use `yo code` create a demo project, use TypeScript/npm/webpack
2. install dependency 
```shell
npm install @alicloud/openapi-client -S
npm install --save @alicloud/devops20210625@1.1.14
```
3. call imported package from extension.ts:
```typescript
import * as devops from "@alicloud/devops20210625";
export function activate(context: vscode.ExtensionContext) {
	let r = new devops.AddRepositoryMemberRequest();
        // ...
        // ...
}

```
4. run extension, execute HelloWorld command

**Comment by aeschli** [comment]
`const pkg = kitx.loadJSONSync(path.join(__dirname, '../../package.json'));` is part of the source code of `node_modules/@alicloud/credentials/src/util/helper.ts`.

I think `@alicloud/credenials` should not be packaged as it relies on finding the `package.json` of its own node module at the given relative location. You can tell webpack not to package a module by adding it to the `externals` section in webpack.config.js.
