### ISSUE TITLE
Wildlife-Dark Theme Doesn't Look Right

### ISSUE THREAD

**Issue by phylliphamby** [Microsoft/vscode#14922]
- VSCode Version: 1.7.7
- OS Version: Windows 7 Professional

Steps to Reproduce:

1. I am not sure if this is for all themes, but the Wildlife-Dark theme totally changed after the update
2. I noticed this yesterday after the first update. It then went back to normal after the rollback, and is now totally changed again after the last update.

**Comment by rebornix** [comment]
I'll say please file issues against the theme you use as we make updates to TS/JS grammar so they may need to update their theme accordingly.
