### ISSUE TITLE
Variables pane disappeared

### ISSUE THREAD

**Issue by FionaLovett** [microsoft/vscode#149238]
Issue Type: <b>Bug</b>

Start debugging. 
In debugging panel, the only panes available are Watch, Call Stack, Loaded Scripts and Breakpoints. No Variables pane.
Right-clicking gives the same list as above, no option to switch on Variables.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) Gold G5500 CPU @ 3.80GHz (4 x 3792)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (12.92GB free)|
|Process Argv|--crash-reporter-id a37e7f14-48d3-4df7-84c6-438ef3911625|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-angular2-files|ale|1.6.4
ignoregit|And|1.0.1
npm-intellisense|chr|1.4.1
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
tslint|eg2|1.0.47
terraform-autocomplete|erd|0.0.8
vscode-firefox-debug|fir|2.9.6
terraform|has|2.22.0
vscode-codemetrics|kis|1.24.0
Angular-BeastCode|Mik|10.0.3
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
data-workspace-vscode|ms-|0.2.0
mssql|ms-|1.14.1
sql-database-projects-vscode|ms-|0.16.1
remote-containers|ms-|0.234.0
remote-wsl|ms-|0.66.2
azure-account|ms-|0.10.1
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
debugger-for-edge|msj|1.0.15
vscode-for-node-js-development-pack|nod|2.0.1
vscode-jest|Ort|4.4.0
code-settings-sync|Sha|3.4.3
vscode-import-cost|wix|3.3.0
zeplin|Zep|2.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe your Variables view has been moved elsewhere. Please use Command Palette to run `View: Focus on Variables View`. Assuming you find it, right-click on its title to get an option to `Reset Location` back to the RUN AND DEBUG view container.

**Comment by FionaLovett** [comment]
Aha! Thanks so much for this. It had somehow obviously ben dragged to its own side panel. Didn’t even know that was possible. I couldn’t find the “Reset Location” wherever I right-clicked on it, but I was able to simply drag it back to the Run and Debug container, so all is well with the world again!

Thanks again.

**Comment by gjsjohnmurray** [comment]
Sounds like you had made Variables into its own container, with a second icon on the Activity Bar. Context menu from that icon gives you `Reset Location`

![image](https://user-images.githubusercontent.com/6726799/167828758-12427b53-47eb-4c06-854c-9ddba035f30b.png)
