### ISSUE TITLE
Replace text with leading new-line: abnormal behaviour

### ISSUE THREAD

**Issue by keiranmraine** [microsoft/vscode#149243]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Enter some text that you want to reformat with new lines:

```
-x 1 -x 2 -x 3
```

2. Move cursor to start of file
3. Ctrl+H
4. In Find: `-x `
5. In Replace, type `Ctrl+Enter` then on new line `-x `

![image](https://user-images.githubusercontent.com/3740323/167819992-54e9d464-bd17-4d15-b8b0-96d314f18431.png)

6. Press `Enter` (or single replace button) 3 times (⚠️ replace all works correctly)

![image](https://user-images.githubusercontent.com/3740323/167820267-54bb63e8-f45f-4f46-97dc-a052891fbc2e.png)

New line is repeatedly applied to first match.

Expected result is:

![image](https://user-images.githubusercontent.com/3740323/167820503-f7824482-ae45-42da-a6a3-529144e2e6e1.png)

**Comment by amunger** [comment]
seems to be working now
