### ISSUE TITLE
Codelens is displayed in the top left of the editor

### ISSUE THREAD

**Issue by GatzJames** [Microsoft/vscode#14924]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open any file that has a codelens
2. The codelens is on the top left of the editor.

Dev tools error:
```
Cannot read property 'range' of undefined: TypeError: Cannot read property 'range' of undefined
located at .vscode\extensions\chrmarti.regex-0.0.6\out\src\extension.js:26:79
```

**Comment by chrmarti** [comment]
This issue was moved to chrmarti/vscode-regex#7
