### ISSUE TITLE
Async notebook controller connection

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#149201]
This is a follow up of API discussions around proxy controller https://github.com/microsoft/vscode/issues/146942. The original attempt was introducing a new type of controllers `NotebookProxyController` which offers a resolver handler `resolveHandler: () => NotebookController | Thenable<NotebookController>`.

As discussed offline with @jrieken, an alternative is allowing the existing `NotebookController` to be async by introducing an optional `connectionState` and making the proxy kernel a special scenario.

The `NotebookController` will have a new property

```ts
export interface NotebookController {
	connectionState?: NotebookConnectionState
}
``` 

## Existing controllers
For notebook controllers which don't have an async connecting/set-up phase, they can ignore the property (leaving it `undefined). This would be backwards compatible.

## Lazy/Async controllers
For notebook controllers which require some long running connection or setup, when users run cells, they

* Change the `connectionState` to `connecting`.
* When connection/setup finishes, flip back the `connectionState` to `connected` or `idle`.
* Create `NotebookCellExecution` to start the real cell execution.

## Proxy controllers
This would be a special case. The difference between lazy controller and proxy controller is, proxy controller represents a set of kernels which are only known after required steps (authentication, connecting to the server, detecting kernels on the server, etc), while lazy controller is representing an known kernel, but it requires additional steps to connect to the kernel.

Take the github workflow (described in https://github.com/microsoft/vscode/issues/146942) as example, we would create a controller called "GitHub" first and after doing authentication, spinning up jupyter server, we will get a real Python kernel. Currently the core relies on the `NotebookController.id` to be unique and meaningful (e.g., it stores which controller is used last time in global memento by controller id), to ensure that the real Python kernel can be remembered by VS Code and picked automatically if users reload the workbench, we want to pass the responsibility of cell execution from the GitHub controller to the Python controller.

To express this, we need to add a new state to `NotebookConnectionState` to differentiate proxy and lazy kernels 

```ts
export interface NotebookConnectionState {
	Idle,
	Connecting,
	Delegate
}
```

When current active notebook controller changes its state to `Delegate`, the core will then find another preferred controller (we can have limitations for this, like only searching in the controllers from the same extension) and use that to execute code.

**Comment by rebornix** [comment]
> To express this, we need to add a new state to NotebookConnectionState to differentiate proxy and lazy kernels

Another approach to tackle this, instead of introducing the `Delegate` state explicitly we could build some heuristics:

* If a notebook controller creates `NotebookCellExecution` after updating `connectionState`, then it's a real kernel
* if a notebook controller switches to `connecting` state, and then `disposed`, we treat it as a proxy controller

With this the proxy controller concept is like a hack though.

**Comment by jrieken** [comment]
* lazy controller makes sense, universal concept
* proxy/delegate controller is tricky cos it inherits more from controllers than needed, we only want to own the RUN and KERNEL PICKER ui
* let's allow extension to contribute to these "menus"
   * KERNEL PICKER: shows kernels and "kernel connect menu" (similar to todays "install from marketplace")
   * RUN: leave as is but show "kernel connect menu" when run is empty

**Comment by rebornix** [comment]
We moved towards kernel source commands so this is currently not needed. We could explore this again if we see new requirements.
