### ISSUE TITLE
about vscode for java ,underline error

### ISSUE THREAD

**Issue by MrYZhou** [microsoft/vscode#149226]
- VS Code Version: 1.67.0
- OS Version: windows_Nt x64 10.0.19043

this problem is that when i want to close the springboot banner by  " .bannerMode(Banner.Mode.OFF) " .
`ConfigurableApplicationContext context =
        new SpringApplicationBuilder()
            .sources(LarryApplication.class)
            .bannerMode(Banner.Mode.OFF).run(args);`

you can jump to the Banner interface ,but vscode editor will show error underline on it ，and no optional quikfix  to use.
can not start application normaly

**Comment by aeschli** [comment]
Please file this against the Java extension: https://github.com/redhat-developer/vscode-java/issues
