### ISSUE TITLE
Hygiene check on Windows fails due to CRLF even if core.autocrlf is set to true

### ISSUE THREAD

**Issue by golf1052** [Microsoft/vscode#14929]
- VSCode Version: 1.7.1
- OS Version: Windows 10 x64 version 1607

When trying to commit to the VSCode code base on Windows I recieve this error:
```
{file}: Missing or bad copyright statement
{file} is not formatted
```
This seems to have been fixed in the past (see https://github.com/Microsoft/vscode/pull/3835 and https://github.com/Microsoft/vscode/issues/1642) by checking if core.autocrlf is set to true but it looks like the recent addition of typescript-formatter (https://github.com/Microsoft/vscode/commit/81de8be588ff7f0e62f5e98be2a2c551b7f65d44) breaks this again. The copyright issue is pretty easily fixable by using `os.EOL` instead of `\n` in gulpfile.hygiene.js (https://github.com/Microsoft/vscode/blob/d14ee7613fcead91c5c3c2bddbf288c0462be876/build/gulpfile.hygiene.js#L99).

Steps to Reproduce:

1. Use Windows and make sure core.autocrlf is set to true
2. Make a code change that includes a new line
3. Attempt to commit the change
4. You will recieve the error
```
src\vs\workbench\electron-browser\workbench.ts: Missing or bad copyright statement
C:\Users\Sanders\Documents\GitHub\vscode\src\vs\workbench\electron-browser\workbench.ts is not formatted
```

I was able to work around this temporarily by setting core.autocrlf to `input` instead of `true` and then switching all the line endings for files I've changed to LF instead of CRLF.

**Comment by joaomoreno** [comment]
Could you just use `input` for the `vscode` repository?

**Comment by golf1052** [comment]
Yes that would work. It would also be good to note that potential contributors in the How to Contribute guide or in the Coding Guidelines that on Windows will need to make sure they're only creating LF new lines on Windows due to this.

**Comment by buzzzzer** [comment]
+1
Same issue on commit with core.autocrlf=true.

**Comment by joaomoreno** [comment]
Added to our contributing guide.

@buzzzzer Do you get that for new files or for existing files? Make sure the files are LF formatted.

![image](https://cloud.githubusercontent.com/assets/22350/20298763/02599658-ab18-11e6-9791-7b012975e0ac.png)

**Comment by letmaik** [comment]
I just had the same issue. This really has to be fixed and should work out of the box, it's very annoying especially for first-time users as this issue doesn't appear commonly on other open source repositories. I use autocrlf=true and it complained about the copyright header. So I had to disable autocrlf for the repo, change the relevant files I worked on manually to LF and then commit.
