### ISSUE TITLE
Monokai Theme bad-highlighting

### ISSUE THREAD

**Issue by MichaelFedora** [Microsoft/vscode#14921]
Dunno if this should be in [here](https://github.com/Microsoft/TypeScript-TmLanguage) instead, but as it is theme related (only, I think), I made it here.

- VSCode Version: 1.7.1
- OS Version: Win10 x64

Steps to Reproduce:

1. Typescript file, Monokai theme
2. Make a class with a function, use the `this` and `super` keyword, etc.
3. Recognize the lack of proper highlighting.

Quite a lot of things where changed between 1.6 and 1.7(.1), including the `=>` in lambdas being blue instead of red now, most methods being green when calling them (but sometimes they are blue, like `getAll`, `get`, `set`, `push`, `forEach`, `navigate`, `apply`, `sub`, `sup`, `anchor`, `big`, etc), some fields being blue (but not all; i.e. `x`, `y`, `z`, `length`, `title`, `all`, and `id` are blue, all of `console`'s methods, all of `document`'s methods, etc), and some lonely keywords being blue as well (i.e. `event`; I can understand the blue-ing of `document` and `console`).

A couple other issues I found was with the `instanceof` operator; `foo instanceof String` makes `String` blue (same with `Array`), whereas in `foo instanceof Class` (where Class is a user-made class) `Class` is still a standard white; not even an underlined green!

**I understand these are kind of standard with highlighting, as is shown by the markdown highlighted sample code below**. So perhaps not all of this is bugged, but only really these:
- Using the tick-strings and the `${var}` replacement is not colored correctly.
- Lambda `=>`'s are currently blue, they were red before
- `this` and `super` are standard white, previously they were purple.

Sample code:
```ts
class Parent {

    protected alpha: {[key: string]: number} = { 'hi': 200 };

    public bar(): void {
        console.log('hi');
    }
}

export class Class extends Parent {

    constructor(private parent: Parent) { super(); }

    fus = {
        ro: {
            da: (): void => {
                console.log('*shouts*');
            }
        }
    }

    public foo(): boolean {

        let event = null;
        event = undefined;

        let a: any = { };
        if(a instanceof String) console.log('instanceof string');
        else if(a instanceof Parent) console.log(`instanceof ${"parent"}`);
        var x = a.normal.keys.x.y.z.length.id.title.event.all.getAll().get().set().push().forEach().navigate().apply().sub().sup().anchor().big().normal().methods();

        this.fus.ro.da();
        super.bar();

        return false;
    }
}
```

**Comment by rebornix** [comment]
We made updates to TypeScript grammar so maybe the theme doesn't align with it anymore, which leads to the color change.

**Comment by itsmoirob** [comment]
I have had a similar issue, same theme. Formatting of text I had for template literals went from highlighting in 1.6, to no highlighting in 1.7 after restarting VSCode. Example would be `some text ${here}`. Previously the ${here} would be highlighted in 1.6, but in 1.7 ${here} is the same colour as standard string text.

@rebornix does this mean the update broke the themes? Was Monokai not the default theme?

**Comment by MichaelFedora** [comment]
dark/dark+, light/light+, high contrast, and some others work fine. It's mostly just Monokai (+ dimmed) and I *think* Solarized (light/dark) that's at issue here.

I thought so @rebornix . I'll wait patiently for the fix :wink:

**Comment by itsmoirob** [comment]
@MichaelFedora For me dark+ works, but dark does not, specifically for my example of seeing javasctipt vars inside template literals.

**Comment by aeschli** [comment]
This is due to changes in our TypeScript grammar. Besides many bug fixes, the goal was to align the scopes emitted to the Atom JavaScript and the TextMate original JavaScript grammar.

That results in changes, but now most of the Themes from the community (as the Monokai theme) should show closer to how they were designed.
Looking at Monokai in TextMate
![image](https://cloud.githubusercontent.com/assets/6461412/19986048/81b363ae-a215-11e6-8655-5190e42d08bf.png)

it seems that `this` is really designed to be white, and `instanceof` red.
The extra colors for the variables is something Atom added (indicating 'library' variables and functions).

We don't plan to revert the changes as aligning the scopes was an important fix for many of the themes. Maybe we can find a nicer version of Monokai. If you want something to look the same to  as did before, maybe the community is interested to provide a new theme as an extension? :-)

**Comment by MichaelFedora** [comment]
I see. Well if that is so, then yes, the previous theme will have to be remade as a modified version of the default Monokai.

Mostly then it's just a few inconsistencies left then (i.e. the "blued" keywords, and the lack of blue on others), I suppose, but then that's more grammar which is in the other project I assume.

Thanks for your help!

(I think, @rebornix , some of the other issues listed here and in #14941 should probably go into one large issue -- i.e. "Theme issues with grammar update" -- instead of here, as this was more or less just a misunderstanding of what the Monokai theme was actually supposed to be)

**Comment by crazytoucan** [comment]
The underlying change broke every version of the Ocean16 theme I could find; I would love a way to revert to the previous grammar in the interim before community maintainers can upgrade to the new grammar. (I also looked fruitlessly to find a way to downgrade vscode purely to fix my syntax highlighters.)

**Comment by CaselIT** [comment]
I would like to add that there seem to be a unnecessary `_` when wrapping on a class type. see the img :
![image](https://cloud.githubusercontent.com/assets/16175304/20457311/acc06cb6-ae88-11e6-8412-b7e260374835.png)

**Comment by CaselIT** [comment]
> some fields being blue (but not all; i.e. x, y, z, length, title, all, and id are blue ... )

`value` is also blue

**Comment by aeschli** [comment]
Closing, as explained above. Sorry for the changes, it really had to do with unconventional scopes that the old TypeScript/JavaScript grammar emitted and brings us closer to how the Monokai theme is supposed to colorize.

**Comment by aeschli** [comment]
@CaselIT That looks like a different issue. Cant you file a separate issue with the code sample?

**Comment by CaselIT** [comment]
@aeschli some fields are still blue btw.

I've opened another issue for the line wrapping bug
