### ISSUE TITLE
Some icons don't render in Safari

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#149256]
* open a codespace in Safari
* run `F1 > Codespaces: Details`
* observe that the gear icon does not load
* (we speculate that this is a Safari bug where Safari forgets to use the service worker for fetching the image)

<img width="310" alt="image" src="https://user-images.githubusercontent.com/5047891/167864818-96ad453b-9390-4529-9be8-2e2ea4a8fa7b.png">

**Comment by tanhakabir** [comment]
There was a small lag loading the gear icon but it showed up
