### ISSUE TITLE
File nesting: allow for non-existant root

### ISSUE THREAD

**Issue by pvinis** [microsoft/vscode#149262]
I love the file nesting feature, and I thought we could use it more generally. The idea I had was this:

files like `jest.config.js`, `babel.config.js` etc, I would group them in a `configs` root.
So if I have a `configs` file, they will all nest under there. but I would like to not have that file, and just vscode makes a fake dir in the explorer called `configs`, that then files can nest under.
This way the explorer would look much cleaner for me.

**Comment by lramos15** [comment]
\duplicate #157848
