### ISSUE TITLE
Formatters cannot be run on new files until they have been saved

### ISSUE THREAD

**Issue by akbyrd** [microsoft/vscode#149215]
Issue Type: <b>Bug</b>

When creating a new file, it can not be formatted until it is saved. 

An existing issue I found in the C++ extension repo indicated this is an problem with VS Code, not the extension
https://github.com/microsoft/vscode-cpptools/issues/8230

Steps to Reproduce:
1. Install an extension that supports formatting a specific file type
2. Create a new file, set its language to one the formatter supports
3. Open the command palette and type "Format"
4. Notice most of the formatting options are missing (Format Modified Lines, Format Selection, Format Document With...)
5. Select Format Document
6. Notice the error message: There is no formatter for 'language' files installed.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (23.65GB free)|
|Process Argv|--crash-reporter-id 478f35b5-a10c-4d20-a3c1-631ecbaf47b0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
unique-lines|bib|1.0.0
auto-align|bla|0.0.13
graphviz-preview|EFa|1.5.0
vsc-material-theme-icons|equ|2.3.1
vscode-pull-request-github|Git|0.42.0
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.16
vsc-space-block-jumper|jmf|1.2.2
polacode-fixed-edition|mrr|0.3.6
remote-containers|ms-|0.234.0
remote-wsl|ms-|0.66.2
cpptools|ms-|1.9.8
code-settings-sync|Sha|3.4.3
dot|Ste|0.0.1
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
> An existing issue I found in the C++ extension repo indicated this is an problem with VS Code, not the extension
https://github.com/microsoft/vscode-cpptools/issues/8230

It is an extension issue: they register for different kind of documents, e.g different languages like C++ or Java and different uri-schemes like `file` (for things stored on local disk), `http`, or `untitled` (for document that aren't saved yet). Extensions must explicitly opt-in to these schemes or they will be ignored

**Comment by jrieken** [comment]
> Notice the error message: There is no formatter for 'language' files installed.

And yes, the message is shown on purpose because. From muscle memory folks select the format document shortcut and we want to make them aware, e.g motivate them to install a formatter (that works everywhere)

**Comment by shieldfoss** [comment]
> the message is shown on purpose

I'm sorry could you repeat that?

You lie to the user on purpose to confuse them into thinking there's a different problem than the real one?

I spent 12 god damn hours trying to find out why, despite having an installed formatter, I got the error message "no formatter," and only after 12 god damn hours did it occur to me that maybe VSCode simply had a bug

(which, spoiler, it *does*, that is to say, it erroneously tells the user that there is no formatter installed for file format X when the fact of the matter is that there is no formatter installed for ***unsaved files*** of format X)

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/171982398-34943e5f-f56b-4d2a-8710-f3b648e85fc0.png)
The bug is not caused by extensions. The bug is caused by VS Code not being able to use extensions because of arbitrary restrictions (in this case, the file nees to be saved on disk first for the formatter to function, for SOME reason my brain is CLEARLY too puny to understand /s).
