### ISSUE TITLE
centos - ELFCLASS32 error when launching

### ISSUE THREAD

**Issue by cgross** [Microsoft/vscode#14923]
- VSCode Version: 1.6 and higher
- OS Version:  7.2

Steps to Reproduce:

1. Type code in bash
2. "error while loading shared libraries: libXss.so.1: wrong ELF class: ELFCLASS32"

No problem on 1.5. 1.6 and 1.7 both trigger this error.

**Comment by polygotdev** [comment]
Hi @cgross 

I have suspicion on the shared library being referenced, if you do a `file /usr/lib64/libXss.so.1`, does a symbolic link come up ?
```
[mm@localhost ~]$ file /usr/lib64/libXss.so.1
/usr/lib64/libXss.so.1: symbolic link to `/usr/lib/libXss.so.1'
```

if so, let's query if this *symlink* shows up in the rpm database....
```
[mm@localhost ~]$ rpm -qf /usr/lib64/libXss.so.1 
file /usr/lib64/libXss.so.1 is not owned by any package
```

if its not part of any rpm package, then there's a good possibility the symbolic link was put in place outside of a RPM package.

There is a 64-bit libXss.so.1 that comes with the RPM package `libXScrnSaver`..

Try doing a rpm query for the rpm package `libXScrnSaver`  if its installed locally:
```
[root@localhost mm]# rpm -q libXScrnSaver
libXScrnSaver-1.2.2-6.1.el7.i686
```

if only the **i686** architecture appears, you may wish to consider installing the **x86_64** architecture specific package

```
[root@localhost mm]# yum install libXScrnSaver.x86_64
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirror.its.sfu.ca
 * extras: muug.ca
 * updates: muug.ca
Resolving Dependencies
--> Running transaction check
---> Package libXScrnSaver.x86_64 0:1.2.2-6.1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================
 Package                         Arch                     Version                          Repository              Size
========================================================================================================================
Installing:
 libXScrnSaver                   x86_64                   1.2.2-6.1.el7                    base                    24 k

Transaction Summary
========================================================================================================================
Install  1 Package

Total download size: 24 k
Installed size: 40 k
Is this ok [y/d/N]: 
```

Try calling up code on terminal now:
```
mm@localhost ~]$ code --version
1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44
```

success ?

**Comment by cgross** [comment]
You da man. In fact I didn't have that shared library at all but I did have the 32bit libXScrnSaver installed.  Installing the 64bit version cleared everything up!  Code starts up fine now. 

Thanks for your detailed and very helpful answer!
