### ISSUE TITLE
Insert Line Above/Below keyboard shortcuts are swapped relative to Visual Studio

### ISSUE THREAD

**Issue by rkeithhill** [Microsoft/vscode#1493]
I use Ctrl+Enter and Ctrl+Shift+Enter to insert lines above and below respectively in Visual Studio **all the time**.  It drives me a bit bonkers that the shortcuts are swapped in VSCode.  

Given the name "Visual Studio Code" implies somewhat of a derivative of "Visual Studio", could you please change the keyboard shortcuts for these two commands to be consistent with Visual Studio?

**Comment by egamma** [comment]
We will consider this. In the meantime you can customize the key bindings for you to reduce the frustration, pls see https://code.visualstudio.com/docs/customization/keybindings

**Comment by bpasero** [comment]
@alexandrudima fyi

**Comment by rkeithhill** [comment]
FWIW the next update to PowerShell's line editor (PSReadline), which supports multiline editing, will support Ctrl+Enter to insert line above and Ctrl+Shift+Enter to insert line below. https://github.com/PowerShell/PSReadLine/pull/6

**Comment by alexandrudima** [comment]
@rkeithhill We do try to align with Visual Studio, but sometimes we diverge when we think it makes sense. Consider `F3` and `Shift-F3`, `Ctrl-F3` and `Ctrl-Shift-F3` for Visual Studio Find operations. The `Shift` changes the direction to find above, so I think `Ctrl-Enter` and `Ctrl-Shift-Enter` make sense (in that `Shift` changes the direction to insert above).

To get rid of the annoyance, you can use the following in your `keybindings.json`:
```
{ "key": "ctrl+enter",            "command": "editor.action.insertLineBefore",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+shift+enter",      "command": "editor.action.insertLineAfter",
                                     "when": "editorTextFocus" },
```

**Comment by landofjoe** [comment]
I use this feature extensively in Visual Studio - so much that it is muscle memory and I don't even think about it.  There have been multiple time when I've hit the same combination three or four times in a row in VSCode until I realize why the line is not appearing where I'm looking for it.  Thanks for the key binding settings snippet.  It's a good work around.

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

P.S. If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
