### ISSUE TITLE
git commit hover message inconsistently dissapears

### ISSUE THREAD

**Issue by Inuart** [microsoft/vscode#149338]
Issue Type: <b>Bug</b>

In the Source Control tab, Commits section, I am able to read a commit message by hovering the cursor over it. However, instead of the message staying there until I move the cursor somewhere else, the message disappears after what appears to be a random duration.

This makes it very annoying to read long commit messages, as I have to constantly move the cursor in and out of the commit area and I never know how many seconds do I get until the message will dissapear again.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

The message I'm refering to, on the bottom right:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/441979/168041699-dec7110a-4190-4987-8af7-a61ec98b728b.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 9a46fc0e-b9eb-4d20-8d52-177d1b1f4801|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
git-coauthors|drr|0.1.2
gitlens|eam|12.0.6
copilot|Git|1.19.5865
vscode-pull-request-github|Git|0.42.0
go|gol|0.33.0
vscode-docker|ms-|1.22.0
vscode-kubernetes-tools|ms-|1.3.8
live-server|ms-|0.2.12
sqltools|mtx|0.23.0
sqltools-driver-pg|mtx|0.2.0
vscode-yaml|red|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

I think this feature is contributed by GitLens
