### ISSUE TITLE
Plugin installation stalls when /tmp is full

### ISSUE THREAD

**Issue by janisozaur** [Microsoft/vscode#14935]
- VSCode Version: 1.7.1 02611b4
- OS Version: Arch

Steps to Reproduce:

1. Fill /tmp so that it has 0 bytes left
2. Try installing a plugin

Expected:

A message about being unable to install a plugin due to /tmp being full.

Actual:

Plugin installation stalls with button in `Installing` state without any progress or other feedback.

**Comment by joaomoreno** [comment]
It's safe to assume 99% of the users won't have `/tmp` full.

**Comment by joaomoreno** [comment]
What

**Comment by joaomoreno** [comment]
What other behaviour did you expect?

**Comment by janisozaur** [comment]
> Expected:

> A message about being unable to install a plugin due to /tmp being full.

**Comment by joaomoreno** [comment]
Doh! Sorry. 👍

**Comment by brandonrninefive** [comment]
I would like to work on this!

**Comment by joaomoreno** [comment]
Closing as won't fix.
