### ISSUE TITLE
Using web History API with pushState in webview leads to webview going blank

### ISSUE THREAD

**Issue by michaeljones** [microsoft/vscode#149333]
Does this issue occur when all extensions are disabled?: No (as it is for custom extensions)

- VS Code Version: 1.67.0
- OS Version: Ubuntu 20.04.4 LTS

When using the history API in a webview and restarting VS Code via the debugger, the webview can go blank.

I realise this seems like quite a niche issue. I guess I would be interested in being sure that it is related to the debugging instance of VS Code and to be sure that it won't happen in production if I ship a webview that uses the history API. It also makes it hard to develop an extension that uses a webview with the history API as it breaks.

I don't need to use links in the webview or load external pages so I can probably replace the use of the History API with some kind of internal stack of states so there is a work around. 

I just wanted to report it as it drove me a little crazy when I first encountered it.

## Steps:

- Checkout this branch for https://github.com/michaeljones/vscode-extension-samples/pull/2
- `cd vscode-extension-samples/webview-sample`
- `npm install`
- `npm run compile`
- `code .`
- Start debugging
- Run `Start cat coding session` command in debug instance of VSCode
- In the webview, click 'push state' button, then 'forward', then 'back' 
- Click debugger 'restart' button in the main instance of VS Code
- When the webview reloads, click 'forward' button, then 'back'

## Expected result

Webview continues to be visible

## Actual result

Webview goes blank

**Comment by mjbvz** [comment]
Thanks for the detailed issue

Yes we don't support browser navigation inside of webviews and don't have plans to as it breaks a lot of . I suggest finding a different way to accomplish this

**Comment by michaeljones** [comment]
Understandable. Thanks for the quick reply.
