### ISSUE TITLE
Pytest discovery error

### ISSUE THREAD

**Issue by mayakip** [microsoft/vscode#149347]
I get an error discovering pytest tests when working in VS code using an environment that was build  with a docker image. 
This error does not happen for my colleague who uses the same docker image with the same docker image (but an older extension version and an older VS code version, reverting to and older extension version did not help).

Here is the output I get: 

/usr/local/bin/python ~/.vscode-server/extensions/ms-python.python-2022.6.1/pythonFiles/testing_tools/run_adapter.py discover pytest -- --rootdir . -s --cache-clear Surgical
cwd: .
[ERROR 2022-4-12 11:53:37.529]: Error discovering pytest tests:
 [n [Error]: ============================= test session starts ==============================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
rootdir: /workspace/BeyeOnicsAlgoRND
collected 21 items / 1 error

<Package calibrations>
  <Module test_blobs_calibration.py>
    <Function test_blob_time_code_generation>
    <Function test_blobs_id_recovery>
  <Module test_calibration_utils.py>
    <Function test_calibrate_hand_eye[0-gt_fixture0]>
    <Function test_calibrate_hand_eye[0-gt_fixture1]>
    <Function test_calibrate_hand_eye[42-gt_fixture0]>
    <Function test_calibrate_hand_eye[42-gt_fixture1]>
    <Function test_calibrate_hand_eye[111-gt_fixture0]>
    <Function test_calibrate_hand_eye[111-gt_fixture1]>
    <Function test_calibrate_hand_eye[666-gt_fixture0]>
    <Function test_calibrate_hand_eye[666-gt_fixture1]>
    <Function test_find_pno[0]>
    <Function test_find_pno[42]>
    <Function test_find_pno[111]>
    <Function test_find_pno[666]>
  <Module test_pno2hTf_bi_direct.py>
    <Function test_calc_azelrollxyz_hTf_azelrollxyz[0]>
    <Function test_calc_azelrollxyz_hTf_azelrollxyz[42]>
    <Function test_calc_azelrollxyz_hTf_azelrollxyz[111]>
    <Function test_calc_azelrollxyz_hTf_azelrollxyz[666]>
    <Function test_calc_azelrollxyz_hTf_azelrollxyz[1512]>
<Module Surgical/tests/data/test_pandas_utils.py>
  <Function test_df_to_formatted_json>
<Module Surgical/tests/serialization/test_dataclass_serialization.py>
  <Function test>

==================================== ERRORS ====================================
_ ERROR collecting Surgical/tests/serialization/test_ot_recorder_serialization.py _
ImportError while importing test module '/workspace/BeyeOnicsAlgoRND/Surgical/tests/serialization/test_ot_recorder_serialization.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
Surgical/tests/serialization/test_ot_recorder_serialization.py:5: in <module>
    import Surgical.accuracy_study.accuracy_data_utils as accu
Surgical/accuracy_study/accuracy_data_utils.py:10: in <module>
    from Surgical.peripherals.zaber_utils.zaber_multiaxis import ZaberTrackerConfig
Surgical/peripherals/zaber_utils/zaber_multiaxis.py:19: in <module>
    from Surgical.peripherals.ot_utils.telemetry_recorder import OpticalTrackerTelemetryRecorder
Surgical/peripherals/ot_utils/telemetry_recorder.py:6: in <module>
    import pybeysurgical as pyot
E   ModuleNotFoundError: No module named 'pybeysurgical'
=============================== warnings summary ===============================
../../usr/local/lib/python3.8/site-packages/recordtype.py:35
  /usr/local/lib/python3.8/site-packages/recordtype.py:35: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    from collections import Mapping as _Mapping

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
ERROR Surgical/tests/serialization/test_ot_recorder_serialization.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
===================== 21 tests collected, 1 error in 2.42s =====================

Traceback (most recent call last):
  File "/root/.vscode-server/extensions/ms-python.python-2022.6.1/pythonFiles/testing_tools/run_adapter.py", line 22, in <module>
    main(tool, cmd, subargs, toolargs)
  File "/root/.vscode-server/extensions/ms-python.python-2022.6.1/pythonFiles/testing_tools/adapter/__main__.py", line 100, in main
    parents, result = run(toolargs, **subargs)
  File "/root/.vscode-server/extensions/ms-python.python-2022.6.1/pythonFiles/testing_tools/adapter/pytest/_discovery.py", line 44, in discover
    raise Exception("pytest discovery failed (exit code {})".format(ec))
Exception: pytest discovery failed (exit code 2)

	at ChildProcess.<anonymous> (/root/.vscode-server/extensions/ms-python.python-2022.6.1/out/client/extension.js:2:228675)
	at Object.onceWrapper (node:events:510:26)
	at ChildProcess.emit (node:events:390:28)
	at maybeClose (node:internal/child_process:1064:16)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)]

**Comment by roblourens** [comment]
Please file this on the Python extension repo: https://github.com/microsoft/vscode-python
