### ISSUE TITLE
Strange semantic hl bug, from recent update.

### ISSUE THREAD

**Issue by OneKnightOnly** [microsoft/vscode#149321]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.1
- OS Version: windows 10 x64

Steps to Reproduce:

1. Use rust analyzer with semantic highlighting
2. Use code from the image below.

![SemanticMess](https://user-images.githubusercontent.com/96325194/168003277-f7a143c7-1448-42dd-ba76-364182289038.png)

Strangely the semantic highlighting works, if you comment out the attribute.

![SemanticWorks](https://user-images.githubusercontent.com/96325194/168004036-0d408def-b926-4988-9ee9-96c2f34cb13e.png)

**Comment by gjsjohnmurray** [comment]
Please set the cursor on a location with the wrong color and run the `Developer: Inspect Editor Tokens and Scopes `command. What does the hover show, compared with what it shows when the trigger line is commented out?

**Comment by OneKnightOnly** [comment]
So, I have actually already done that, and it gives incorrect semantic tokens (but correct for the color shown), for example the inspect editor thinks the purple 'p' is a keyword, which it is not, and the green equals sign is a number, which is clearly not right.

**Comment by OneKnightOnly** [comment]
To be clear, when the attribute (trigger line) is commented out, the inspect editor shows all correct semantic tokens.

**Comment by gjsjohnmurray** [comment]
Sounds like a bug in the extension then. Please open an issue on its repository and link to this one, then close here.
