### ISSUE TITLE
high CPU just typing the code

### ISSUE THREAD

**Issue by Iamwangli** [microsoft/vscode#149311]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: April 2022 (version 1.67)
- OS Version: Ubuntu 20.04.4 LTS
Steps to Reproduce:

1. the vscode takes a high cpu just when I type the code.
![2022103619](https://user-images.githubusercontent.com/48752449/167980984-1cbab535-a38d-4319-b774-3669134ea077.png)
![2022103700](https://user-images.githubusercontent.com/48752449/167980992-5e3be84f-58f1-4621-b599-5dc6914b52fa.png)

**Comment by zouyonghao** [comment]
Same here with 1.67.1 on Ubuntu 22.04 LTS and docker extension (Ubuntu 18.04 inside the container)

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No

Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

/needsMoreInfo

**Comment by Iamwangli** [comment]
@gjsjohnmurray I am sorry I can't find any command about "Start Extension Bisect" in VS Code.
![image](https://user-images.githubusercontent.com/48752449/167997598-51f106dc-e287-4c7b-a798-4e4694d8be36.png)

**Comment by Iamwangli** [comment]
@gjsjohnmurray thanks. It's caused by Cpptools.
