### ISSUE TITLE
VSCode should not open browser on first start without user's say-so

### ISSUE THREAD

**Issue by janisozaur** [microsoft/vscode#14934]
- VSCode Version: 1.7.1 02611b40b
- OS Version: Arch

Steps to Reproduce:

1. Install `visual-studio-code` from AUR
2. Open installed application.

Upon first start vscode opens a web browser pointing to https://code.visualstudio.com/docs?start=true. It should not do that without getting a confirmation from user it is OK to do so.

Some editors choose to have a "welcome" page with links to documentation (cf. Eclipse, Qt Creator), it could be one possible solution.

Perhaps a MD/RST document could be opened upon first start with some brief info and helpful links (cf. Vim, Emacs).

Another option would be a prompt asking user to open a link could do as well, but personally I think this would be worse solution.

**Comment by rebornix** [comment]
Assign to @chrmarti as it's kind of getting started experience.

**Comment by dawsonbotsford** [comment]
Is this supposed to happen each time you open vscode? I'm finding the "Getting Started" docs annoying each and every time I want to edit with vscode.

**Comment by chrmarti** [comment]
@dawsonbotsford This should only happen once - on first startup. Please open an issue if it shows more than once.

**Comment by dawsonbotsford** [comment]
@chrmarti I swapped to the Insiders build and I haven't seen this issue anymore. Will let yall know if it arises again. I also got a reset color scheme each time I opened vscode, so clearly something was wonky with persistence.

**Comment by jmlntw** [comment]
**+1 in 2018.**

Opening browser pretty annoying when I re-install VS Code.
Now we have a welcome page to give user some guide and help, I think there's no need to open a browser.

**Comment by ThomasNigro** [comment]
+1 there should be at least a Command Line Option flag to disable the automatic opening of a browser window on first launch, to better comply with automated deployment scenarios.

**Comment by rkennesson** [comment]
I could have sworn there was a command line option posted to one of these issues but I can't find it.

**Comment by chrmarti** [comment]
`--skip-getting-started` will skip opening the browser until you start without that flag. You probably want to always pass it.

**Comment by rkennesson** [comment]
I don't know if this will survive updates but I'm going to try it. I'm on Kubuntu but if anyone is so inclined to try it it can be modified to suit your situation. I'm no expert so, until it's built into vscode, if there's a better way I'm willing to try it

#.bashrc

`alias code='code --skip-getting-started'

and then to edit the *.desktop files

`sudo sed -i 's|/usr/share/code/code|/usr/share/code/code --skip-getting-started|g' /usr/share/applications/code*`

**Comment by jmlntw** [comment]
VS Code reads `~/.config/vscode/globalStorage/state.vscdb` SQLite database which has `workbench.hide.welcometrue` key to determine whether show open browser. You can edit and backup this file to your dotfiles.

I have a `state.vscdb` that make VS Code skip welcome page and some notifications on first start up.
https://github.com/jmlntw/dotfiles/blob/master/vscode/globalStorage/state.vscdb

**Comment by rkennesson** [comment]
@jmlntw awesome. thanks. I took a look at it in sqlitebrowser and it's a nice simple fix. I'm going to add it to my vscode install script for later.

**Comment by jrieken** [comment]
Thanks to @bpasero we finally stopped doing this 👯‍♂ 👯

**Comment by bpasero** [comment]
Actually for September.
