### ISSUE TITLE
[1.67.1] Stuck and Crash in render thread

### ISSUE THREAD

**Issue by variantf** [microsoft/vscode#149314]
Hi, I'm using VSCode on Windows 11. when I open a particular .cpp file. it will suddenly unrepsonsive for whole vs code. after wait for a while. it shows:

![image](https://user-images.githubusercontent.com/2265407/167985352-eead8d09-d786-4be6-8d92-49ba2a3a1694.png)

I also checked from taskmgr, and here's the abnormal process:

![image](https://user-images.githubusercontent.com/2265407/167985312-5bad6a32-8de0-45a7-ad6c-91da85610435.png)

Any suggesstions for further debug?

**Comment by variantf** [comment]
Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by variantf** [comment]
Update: I've tried with a MacOS environment, same issue the latest vscode version: 1.67.1. but works find at 1.66.  How can I get a rollback?

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/docs/supporting/faq#_previous-release-versions

/extC++

**Comment by variantf** [comment]
@vscode-triage-bot I don't think it's caused by extension. Please have a look!! It's crashed at render thread!

**Comment by variantf** [comment]
How can I reopen this ticket ? @gjsjohnmurray

**Comment by variantf** [comment]
@gjsjohnmurray the only change is vscode's version. could you have a look at this?

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/145024#issuecomment-1066841446

https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

Can you provide a minimal repro as an attached cpp file?

**Comment by variantf** [comment]
Thanks @gjsjohnmurray. since I disabled the C/C++ Intelisense extension, the issue disappered. I submit another issue to extension's repo
