### ISSUE TITLE
VS Code bundled extensions not enabled on ssh

### ISSUE THREAD

**Issue by nganpu** [microsoft/vscode#149386]
My VS Code extension has an extension pack, bundled with 4 other extensions.

When I opened a remote SSH workspace in VSCode, although my main extension is enabled, the bundled extensions are not. (only shown in locally installed)
![image](https://user-images.githubusercontent.com/41269180/168147697-624adc59-787e-4ad5-a597-b0c7621c7f76.png)

I wonder what's the reason behind this. Since those bundled extensions are in the extension pack, shouldn't it be automatically enabled with the main extension?

Is there a way for me to fix it without [manually installing](https://stackoverflow.com/questions/55958395/why-arent-some-of-my-extensions-enabled-when-i-open-a-vs-code-remote-workspace/55958396#55958396), as it'll affect other extensions we'll bundle in future

**Comment by nganpu** [comment]
Hi there, do we have any update on this issue?

Thank you

**Comment by sandy081** [comment]
> I wonder what's the reason behind this. Since those bundled extensions are in the extension pack, shouldn't it be automatically enabled with the main extension?

Extension pack is meant for installing extension together and not for enabling. Enablement is completely related to the extension. In your case, you have to install these extension in the remote SSH to enable as the button mentions.
