### ISSUE TITLE
Python ModuleNotFoundError

### ISSUE THREAD

**Issue by TheEverglow** [microsoft/vscode#149356]
Issue Type: <b>Bug</b>

The setup is virtual environment.
Let us have similar directory structure
EXAMPLE-project
 |--/folder1
 |--/folder2
 |--/utils
    |--|-----launch.py
 |--args.py

launch.py (in /utils folder) contains for example such string as an import
`from args import ExampleClass` (or import any variable)

In previous versions I could execute any script from /utils being in root directory as following: python utils/launch.py

Visibility of from args import ExampleClass is actual exactly for exection from root directory, but now an error occurs: 

$ python utils/launch.py 
Traceback (most recent call last):
  File "utils/launch.py", line 3, in <module>
    from args import ExampleClass
ModuleNotFoundError: No module named 'args'

I make sure I've done and imported anything this way.
The setup is virtual environment of course.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.67.3
python|ms-|2022.6.1
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.4.1011282140
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
material-icon-theme|PKi|4.17.0

</details>

**Comment by roblourens** [comment]
This doesn't sound like an issue with vscode, it sounds like an issue with your project or python configuration. If you think it's an issue with the python extension, please file it on their repo.
