### ISSUE TITLE
formatting and some plugins stopped working after lates update

### ISSUE THREAD

**Issue by RomanHiden** [Microsoft/vscode#14931]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-tidyhtml|anweber|1.1.0|
|typings-installer|benjaminromano|0.2.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.5.40|
|format-on-save|gyuha|0.0.8|
|start-git-bash|McCarter|1.0.4|
|debugger-for-chrome|msjsdiag|2.1.3|
|language-vscode-javascript-angular2|nwallace|0.0.11|

---

Steps to Reproduce:

1. formatting stopped working
2.

**Comment by animeshb** [comment]
I updated to latest recovery build and have the exact same problem. I also can't expand and shrink selections using Alt-Shift-LeftArrow and Alt-Shift-RightArrow.


Version 1.7.1
Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
Date 2016-11-03T13:53:14.822Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

Steps to reproduce:

1. Press Alt-Shift-F

**Comment by rebornix** [comment]
@RomanHiden @animeshb do you mind helping me understand which extension leads to the problem? You can disable others and only enable one and then we can know which extensions is failing.

**Comment by RomanHiden** [comment]
I have identified two extensions that stopped workin
1) format-on-save
2) language-vscode-javascript-angular2

Thanks,
R.

**Comment by animeshb** [comment]
All my extensions seem to work, but when I format, nothing happens. I have found this happens in js files. I didn't get to test css or html.

The following snippet:

    if(1) {
    scope.render(data);
    }

does not get aligned as it should when I try to format the document. It just stays as is.

**Comment by dyliew** [comment]
Hi, I am having the same issue again. I think the IntelliSense for javascript isn't reliable in this version which causes other features to not work on js.

**Comment by rsaddey** [comment]
TSLint stopped working completely for me (OS X Yosemite): No more style violations, no more fixes, no nothing :-(

Still worse: 
* No helpful docs available on how to downgrade.
* No previous version available for download despite FAQ stating so.
* No choice available after clandestine upgrade download (now or later, but no choice to opt out).

I'm supposed to be on a plane tomorrow...

IMHO, this may be a show stopper for VSC in general.

**Comment by aeschli** [comment]
Many different issues have been mentioned here, which make it very hard to track and work on. Please file a new issue per problem with each a small code examples that demonstrate the issue.
For extension that don't work anymore, please file the issue against the extension's issue tracker system. 
https://github.com/gyuha/vscode-format-on-save, 
https://github.com/natewallace/language-vscode-javascript-angular2
