### ISSUE TITLE
2 files infected after updating to 1.7?

### ISSUE THREAD

**Issue by SaphiLC** [Microsoft/vscode#14932]
So i updated to 1.7 and my antivirus found "js.packed.dropper.c" in 2 files (typingInstaller.js and tsserver.js), should i be worried? :\

- VSCode Version: 1.7
- OS Version: Windows 10

Steps to Reproduce:

1. Update to 1.7
2. Run an antivirus scan

**Comment by rebornix** [comment]
@SaphiLC no worries :)
