### ISSUE TITLE
HTML attributes containing values with *.ref* break syntax highlighting

### ISSUE THREAD

**Issue by Krossmaskinen** [Microsoft/vscode#14938]
- VSCode Version: 1.7.1
- OS Version: Win 10

With HTML syntax highlighting, having a value of an element attribute that contains `*.ref*` breaks syntax highlighting as if the quotation containing the value never closes. This has only happened with the `*.ref*` so far.

This issue is likely to show up when using JS frameworks, like Aurelia, and you bind object properties to HTML attributes.

Steps to Reproduce:

1. Set syntax highlighting to HTML
2. Paste in `<div data-reference-id="client.referenceId">`

You can see that the quotation containing `client.referenceId` is never closed as for syntax highlighting. I've tested it in several color themes and it doesn't seem to be related to that.

![vscode-html-higlight-bug](https://cloud.githubusercontent.com/assets/1162364/19986133/c2069e6c-a215-11e6-8f75-8aaa00b5cc0d.jpg)

**Comment by aeschli** [comment]
@Krossmaskinen I'm not able to reproduce with a fresh 1.7.1 install. Can you paste a more complete example?

![image](https://cloud.githubusercontent.com/assets/6461412/19998992/28eb4240-a270-11e6-8c51-ae47cb15b8ec.png)

**Comment by Krossmaskinen** [comment]
Thanks for checking this out!

Since we have the same build and you don't get the same problem I figured it might be an extension lurking around and messing it up. And I was right! It's the 'aurelia'-extension that was causing it. I'll open this issue on their project instead.
