### ISSUE TITLE
New window opens behind existing windows

### ISSUE THREAD

**Issue by tschaub** [microsoft/vscode#149394]
Issue Type: <b>Bug</b>

* run `code one` in the terminal where `one` is the path to an existing directory
* see VSCode open the workspace as expected
* run `code two` in the terminal where `two` is the path to an existing directory
* focus changes back to VSCode, but showing the window for project `one` instead of project `two`

Here is a movie of the experience:

![open-behind](https://user-images.githubusercontent.com/41094/168166589-c56fa79c-3356-4ba5-9ee1-52c56cc66743.gif)

In previous versions of VSCode, when opening a new project with `code`, the new window would show up above any existing windows.  This is what I expected to happen.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:14.619Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.93GB free)|
|Process Argv|one --crash-reporter-id 89d47731-c956-41d6-bf2f-17af04d06d0e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.8.3
vscode-eslint|dba|2.2.2
copilot|Git|1.19.5865
go|gol|0.33.0
terraform|has|2.22.0
vscode-env|Iro|0.1.0
jsonnet-language|lia|1.0.0
vscode-docker|ms-|1.22.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
excalidraw-editor|pom|2.0.16
code-spell-checker|str|2.1.11
svelte-vscode|sve|105.16.0
cython|tcw|0.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by tschaub** [comment]
Looks similar to #929 and #13042.

**Comment by romain20100** [comment]
Same issue.
On Mac OS, VsCode 1.67

How to reproduce:

1. Use shortcut to open new window <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>N</kbd>
2. Use shortcut to open new file/folder <kbd>CMD</kbd> + <kbd>O</kbd>

The selected file/folder is now opened in the previously focused vscode window instead of the newly opened one.

To solve the problem, you have to think to click in the newly opened window.
When you do so, you see the focus takes effect, proving the window was not actually focused.

I can tell this is a relatively new issue (1 or 2 months max), because I'm doing the procedure above almost every day and it has been pissing me off since then (sorry, but truly annoying).

**Comment by bpasero** [comment]
Sounds a bit like https://github.com/microsoft/vscode/issues/149067 or https://github.com/microsoft/vscode/issues/149043

**Comment by bpasero** [comment]
This is a regression from https://github.com/electron/electron/pull/33536

**Comment by tschaub** [comment]
Thanks for the fix!
