### ISSUE TITLE
Add Intellisense Failure Repair module to VSCode

### ISSUE THREAD

**Issue by roschler** [microsoft/vscode#149390]
VSCode is an impressive work but the Intellisense module is constantly breaking and even a brief Web search shows this is a common problem.  I had this problem far less often in Visual Studio so something is amiss and this problem _really_ degrades the entire VSCode experience for me and others.  Also, this has been a problem for a few years now.

Please add a module/plug-in/upgrade whatever to VSCode that helps analyze the internal linkages required by Intellisense to function properly and then assist the developer in fixing their setup.  Right now everything is too silo'd and perhaps that is why no one has stepped forward and created a fix for nagging problem.

**Comment by mjbvz** [comment]
What languages are you seeing issues with?

**Comment by roschler** [comment]
C#/Omnisharp.

**Comment by mjbvz** [comment]
Please file this issue against that extension then so they can investigate potential IntelliSense instability 

/extC#

**Comment by roschler** [comment]
And back to square one.  I feel that is precisely why this issue has gone unsolved for so long.  It requires help from the VSCode team to actually get fixed since a "global" perspective is needed.  

"potential IntelliSense instability"

And if it it's not?  Or what if it's some interaction between the VSCode plug-in harness code and the Omnisharp DLL?  Simple flowchart.  (yet another) issue is posted to Omnisharp, they find no problem on their end, investigation stops dead, again.

Back to square one.
