### ISSUE TITLE
Cannot read property 'loadCell' of undefined

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#149308]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.when I open VSCode,  no reaction, and later the devtools opened;
2.the message is  [Cannot read property 'loadCell' of undefined];
3. this problems troubles me a long time, I was tired.
4. Can you tell me how to resolve it?

**Comment by gjsjohnmurray** [comment]
> Does this issue occur when all extensions are disabled?: Yes/No
> 
> * VS Code Version:
> * OS Version:

/needsMoreInfo

Also, please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by joyceerhl** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/154767
