### ISSUE TITLE
I am having problems with typing a specific letter

### ISSUE THREAD

**Issue by Hcuadro2326** [microsoft/vscode#149378]
The letter "b" wont type when I am trying to type it for code. I need help because I am not trying to copy and paste it every time.

**Comment by iagobruno** [comment]
Can you type the letter in other programs?
Have you set any keyboard shortcut that use the letter b?
Have you tried disabling all extensions to see if the problem persists?

**Comment by JacksonKearl** [comment]
Probably an extension contributing a keyboard shortcut for `b`. I recommend running `Toggle Keyboard Shortcuts Troubleshooting` and see what is logged when you press b.

**Comment by Hcuadro2326** [comment]
I checked and nothing, I am also new to this so I feel lost. And no, I can't type B at all in the program

**Comment by Hcuadro2326** [comment]
I figured it out, I had to check the Key binding entries and delete the shortcut. Thank you guys
