### ISSUE TITLE
vscode for java ,shortcut key (ctrl + . )

### ISSUE THREAD

**Issue by MrYZhou** [microsoft/vscode#149317]
- VS Code Version: 1.67
- OS Version: win10 19043

1. thisshortcut key (ctrl + . ) does't work

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by MrYZhou** [comment]
Thanks a lot ,it works now.The reson is shortcut key conflict

**Comment by MrYZhou** [comment]
shortcut key conflict
