### ISSUE TITLE
Allow "OPEN EDITORS" frame to be expanded down

### ISSUE THREAD

**Issue by fcntl** [Microsoft/vscode#14930]
- VSCode Version: all
- OS Version: all

In the absence of vertically arranged tabs, it would be nice if the "OPEN EDITORS" frame could be expanded downwards, thus shrinking the frame containing the project directory tree. Currently it is fixed at a fairly small level, meaning if you have lots of open files only a subset are displayed. It is strange the bar separating the two frames is not adjustable.

**Comment by gqshell** [comment]
The setting "explorer.openEditors.visible" controls the height of the top section.

**Comment by fcntl** [comment]
@gqshell OK thanks I will give it a try. Although it would be conventional in a GUI for this to be a sliding separator.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/491
