### ISSUE TITLE
Unable To view source control of git project

### ISSUE THREAD

**Issue by prafuliihglobal** [microsoft/vscode#149319]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: Ubuntu 20.04.4 LTS

Steps to Reproduce:

1. Unable to get source control. i have updated my system with apt update and apt upgrade after that i can't be able to view source control.
![image](https://user-images.githubusercontent.com/82135346/167997028-0cbf4689-35a5-4363-8a50-15b231b518cb.png)
2.

**Comment by JakobTischler** [comment]
- VS Code Version: 1.67.1
- OS Version: Windows 10 x64

I have the same problem, started ca. six hours ago. I have multiple repos that aren't recognized anymore. Both workspaces and direct folder views. The `.git` folders are all there. I "fixed" one of them by cloning it again to a new folder.

**Comment by lszomoru** [comment]
@prafuliihglobal, @JakobTischler apologies for not getting back to you on this until now. Is there a chance that you have started experiencing this issue after you have updated the version of git? Could you please use the steps from [the following wiki](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#log-level-setting) to enable `trace` logging, open the folder/workspace again, and then share the contents of [the git output channel](https://code.visualstudio.com/docs/editor/versioncontrol#_git-output-window). Thank you!

**Comment by prafuliihglobal** [comment]
hey, @lszomoru, i have fix this issues by running this command `git config --global --add safe.directory <you project path>`. i have found this command in suggestion of ATOM code editor which also unable to track git file changes and suggested me to run this command.

**Comment by prafuliihglobal** [comment]
Is there a chance that you have started experiencing this issue after you have updated the version of git? **i have setup existing github project on my new machine.**

**Comment by prafuliihglobal** [comment]
@JakobTischler try `git config --global --add safe.directory <you project path>` command

**Comment by lszomoru** [comment]
@prafuliihglobal, I am glad to hear that you were able to track down and fix this issue. We do have an issue tracking improvements to detect this particular error condition, and provide a meaningful error message to make things easier to troubleshoot and fix.
