### ISSUE TITLE
click the  `Sync Changes` will notify `command '' not found` when is syncing changes

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#149384]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/168143212-dfefeba0-c4f3-4a67-9dd5-60f20b35d87f.png">

versions:

- MacOS: 12.3.1
- VSCode: 1.68.0-insider

**Comment by lszomoru** [comment]
@tjx666, are you able to consistently reproduce this issue? If so, could you please share the steps? Thank you!

**Comment by lszomoru** [comment]
This issue has been fixed as now the action button is disabled while a sync operation is running.
