### ISSUE TITLE
Support `imports` and `exports` properties of `package.json`

### ISSUE THREAD

**Issue by dog-s-life** [microsoft/vscode#149310]
vscode doesn't look like supporting `imports` and `exports` to resolve `import` statement

https://github.com/jkrems/proposal-pkg-exports/

Currently, many bundlers, `node` and `typescript >= 4.7` are supporting it. I guess IDE also is supposed to follow them :)

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
