### ISSUE TITLE
document.getWordRangeAtPosition(position) not working properly in XML files.

### ISSUE THREAD

**Issue by sushant3524** [microsoft/vscode#149318]
Example:

```
<content> 
    <function>PostChangeLog</function> 
    <Value3>1644336660000</Value3> 
    <DeviceID>FA954A84D674FAE</DeviceID> 
    <EntryGUID>793FCA-50B-76D-FDB-3BC93E512</EntryGUID>   
</content>
```

Some particular observations:
-  When putting the position of any character of the word `PostChangeLog` in the function I get the Word Range of the word `PostChangeLog` which is correct.
- But when putting the position of any character of the word `1644336660000` in the function I get the Word Range of the _**whole document**_. (**This is the issue that I am concerned with**).
- Furthermore, I tried some more combinations, so that I can get why is it happening:
-- Any character of the word `FA954A84D674FAE`; Result - Word Range of the word `FA954A84D674FAE`
-- Any character of the word `793FCA-50B-76D-FDB-3BC93E512`; Result - Word Range of the word `793FCA-50B-76D-FDB-3BC93E512`

**Comment by alexdima** [comment]
I think this might be a problem with the XML word pattern, which came in via https://github.com/microsoft/vscode/pull/127334
