### ISSUE TITLE
Quiet Light theme: highlight for search result in comment is same color as text

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#14936]
- VSCode Version: 1.7.1
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Pick the "Quiet Light" color theme.
2. Open a JavaScript file.
3. Type "// I am a comment".
4. Ctrl-F to search for "am a".

![screnshot](https://cloud.githubusercontent.com/assets/19274678/19984186/66634fec-a1ca-11e6-9b05-b435d4a1b7e5.jpg)

**Comment by sandy081** [comment]
Duplicates #9891
