### ISSUE TITLE
Ctrl-Tab not working - have to press ENTER to switch window

### ISSUE THREAD

**Issue by damircolak** [microsoft/vscode#149372]
Steps to Reproduce:

1. Go into visual studio code
2. Hit ctrl+tab
3. Popup with windows list will be shown but windows will not be switched
4. Have to press enter in the window list to switch the window

Why?!

**Comment by u3b** [comment]
It seems to be working fine on Windows 11 - VSC 1.59.1

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by damircolak** [comment]
I am using MacOS and it still is not working. It is really frustrating.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by damircolak** [comment]
Abs() same thing, ctrl-tab is still not working.

**Comment by bpasero** [comment]
To clarify: you talk about switching an editor not the window right? Can you share a video?

/gifPlease

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/170736937-d8183485-50dc-494c-a229-f5c525b0a633.png)

**Comment by damircolak** [comment]
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/17295346/170737650-ecbf3053-01be-4783-9951-aae5d10e7949.png">

**Comment by bpasero** [comment]
Can you try to remove all your custom keybindings around `Ctrl+Tab`

**Comment by damircolak** [comment]
Awesome. It was kb-macro plugin that created the problem!

No idea why now, had it installed forever.

Thank you!
