### ISSUE TITLE
`.md` file syntax issue: Follow link

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#149475]
![Screenshot 2022-05-13 083513](https://user-images.githubusercontent.com/44144724/168318221-0f44e86f-cb25-462a-b813-9bd771c20918.png)

**Comment by mjbvz** [comment]
What markdown renderer are you using? I don't think the example is correct  according to common mark (see how `svelte:head` is rendered as a comment instead of an html tag): https://spec.commonmark.org/dingus/?text=%3Ctag%3Etext%3C%2Ftag%3E%0A%0A%3Csvelte%3Ahead%3Etext%3C%2Fsvelte%3Ahead%3E

**Comment by babakfp** [comment]
Doing something like `svelte:head` isn't a feature in MD files, as far as I know. But I'm using this tool called [mdsvex](https://mdsvex.pngwn.io) to render `.md` files in a framework called [Svelte](https://svelte.dev). So this [`svelte:head`](https://svelte.dev/tutorial/svelte-head) tag is a feature in Svelte.

**Comment by mjbvz** [comment]
Thanks

I think this should likely come from a Svelte specific [markdown plugin](https://code.visualstudio.com/api/extension-guides/markdown-extension) then. I'm going to close this as by-design as we align with how CommonMark parses these links

**Comment by babakfp** [comment]
@mjbvz

But it's not related to Svelte😐. It's an issue with vsCode that it doesn't know the difference between a tag and a link. I'm not saying add a feature or a fix, specific to Svelte, it's not about that. As you can see, it's not an issue in an HTML file:

![image](https://user-images.githubusercontent.com/44144724/168976057-4de84db1-2e7a-47e4-9982-5f167fd3ffc0.png)

.md file:

![image](https://user-images.githubusercontent.com/44144724/168976285-a27df2b7-8ce2-455a-886a-df335f363c64.png)

**Comment by babakfp** [comment]
Can someone reopen this issue?

**Comment by mjbvz** [comment]
You’re adding unsupported syntax in the markdown. As I explained, support for it would need to be added by Svelt extension. The current behavior matches standard markdown’s syntax

**Comment by babakfp** [comment]
So, `<svelte:head>` is an expected and supported syntax for creating a link in a markdown file? Is it?! No, it's not. vsCode is supporting something that shouldn't be supported! Because `<svelte:head>` isn't a valid code in markdown and it should not be recognized by vsCode as a link!😤

**Comment by babakfp** [comment]
Both of these look normal to you?

![Screenshot 2022-05-19 082627](https://user-images.githubusercontent.com/44144724/169335804-a2ece6b9-514d-4d15-bbd3-1dbb1e63b7d8.png)

**Comment by mjbvz** [comment]
https://spec.commonmark.org/dingus/?text=%3Ctag%3Etext%3C%2Ftag%3E%0A%0A%3Csvelte%3Ahead%3Etext%3C%2Fsvelte%3Ahead%3E

**Comment by babakfp** [comment]
You know what, you were right all the time, and I think this can be a better solution:

![169341988-ff65923f-bde2-4eb7-a672-19c877ea696a](https://user-images.githubusercontent.com/44144724/169376003-61d4191a-aae9-4c72-a6c3-2abf25ec2000.png)
