### ISSUE TITLE
Intellisense showing useless hints first, and useful hints last

### ISSUE THREAD

**Issue by gujiman** [Microsoft/vscode#14946]
- VSCode Version: 1.7.1
- OS Version: win 7

Steps to Reproduce:

1. Load a javascript file to test the 'for' loop
2. Enter 'for' (if Intellisense doesn't show then press cntrl+space)
3. The first entry in the Intellisense is 'for' and when selected doesn't do anything
4. However the last few entries in the Intellisense are useful, there is a 'for' entry towards the bottom of the list, when select will add the following snippet:

for (var index = 0; index < array.length; index++) {
    var element = array[index];
}

5. This is what i want but why is it right at the bottom of the list?

**Comment by ramya-rao-a** [comment]
See #13839 and #10467

To get the snippet suggestions on top you can add the following to your settings: `"editor.snippetSuggestions": "top"`

**Comment by rebornix** [comment]
Close as we do have an option for that.
