### ISSUE TITLE
I cannot use the letter 't' on my keyboard

### ISSUE THREAD

**Issue by ecemetinkaya** [microsoft/vscode#149465]
Issue Type: <b>Bug</b>

I cannot use the letter 't' on my keyboard while typing labels. I checked the key, the key is not broken, I can use it while searching on Google or typing this message, but I cannot use it in the program. What should I do to fix this?

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:36:59.805Z)
OS version: Windows_NT ia32 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (1.83GB free)|
|Process Argv|--crash-reporter-id af4f39e8-5e03-4c49-af3f-ddd2bb0b1e85|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-tr|MS-|1.67.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdf:30486550

```

</details>

**Comment by jrieken** [comment]
There is logging for what's happening. Do the following: 

* Select F1 > Toggle Keyboard Shortcuts Troubleshooting
* Notice how it reveal the log channel
* Now press `t` and look out for messages that mention the character (see below for a sample)

```
[2022-05-13 15:29:42.796] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [], code: KeyT, keyCode: 84, key: t
[2022-05-13 15:29:42.797] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [], code: KeyT, keyCode: 50 ('T')
[2022-05-13 15:29:42.797] [renderer1] [info] [KeybindingService]: | Resolving [KeyT]
[2022-05-13 15:29:42.797] [renderer1] [info] [KeybindingService]: \ No keybinding entries.
```

The logs show print `No keybinding entries.` but it might be a bad keybinding configuration got into your way

**Comment by alexdima** [comment]
> When I press 't' I get a warning like "(T) was pressed Waiting for second key of chord...". When I follow the steps you sent, I get an output like this.  
```
[KeybindingService]: / Received  keydown event - modifiers: [], code: KeyT, keyCode: 84, key: t
[KeybindingService]: | Converted keydown event - modifiers: [], code: KeyT, keyCode: 50 ('T')
[KeybindingService]: | Resolving T
[KeybindingService]: \ From 1 keybinding entries, matched chord, when: no when condition, source: user.
[KeybindingService]: / Received  keydown event - modifiers: [], code: KeyT, keyCode: 84, key: t
[KeybindingService]: | Converted keydown event - modifiers: [], code: KeyT, keyCode: 50 ('T')
[KeybindingService]: | Resolving T chorded from T
[KeybindingService]: \ From 0 keybinding entries, no when clauses matched the context.
```

Thank you for the extra information. It looks like you have configured a keybinding for `T`, maybe by accident. You can open your `keybindings.json` file and remove the unwanted keybinding using `F1 > Preferences: Open Keyboard Shortcuts (JSON)`.
