### ISSUE TITLE
Local history: Errors when restoring contents are silently swallowed

### ISSUE THREAD

**Issue by mystiquewolf** [microsoft/vscode#149459]
Issue Type: <b>Bug</b>

If a file has been opened in a location in which VS Code uses sudo to save the file, afterwards the timeline doesn't show diff between saved versions and doesn't restore the file upon request.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:08:42.978Z)
OS version: Linux x64 5.17.5-zen1-1-zen
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1263)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.64GB (0.40GB free)|
|Process Argv|--no-sandbox --enable-features=UseOzonePlatform --ozone-platform=wayland --unity-launch --crash-reporter-id 60c6773d-300e-41ae-af3b-fc69efc3d008|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
Bookmarks|ale|13.3.0
vscode-diff-viewer|cap|1.2.0
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
csharpier-vscode|csh|1.2.4
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.6
vscode-html-css|ecm|1.12.2
prettier-vscode|esb|9.5.0
shell-format|fox|7.2.2
copilot|Git|1.20.5902
cloudcode|goo|1.18.2
gc-excelviewer|Gra|4.2.54
output-colorizer|IBM|0.1.2
icon-fonts|idl|2.5.3
Ionide-fsharp|Ion|6.0.3
vscode-csharp-snippets|jor|1.1.0
roslynator|jos|4.1.0
docomment|k--|0.1.30
vscode-colorize|kam|0.11.1
vscode-gutter-preview|kis|0.30.0
csharpextensions|kre|1.7.0
vscode-jumpy|krn|1.0.2
cool-language-support|Lin|0.1.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
dotnet-interactive-vscode|ms-|1.0.3256010
vscode-dotnet-pack|ms-|1.0.8
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.9.8
live-server|ms-|0.2.12
idl|myt|0.3.1
es6-css-minify|olb|3.3.3
vscode-versionlens|pfl|1.0.9
vscode-xml|red|0.20.0
vscode-sort-json|ric|1.20.0
bash-debug|rog|0.3.9
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
indenticator|Sir|0.7.0
code-spell-checker|str|2.1.11
teamhub|Tea|15.0.6
vscode-pets|ton|1.10.0
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.21
vscode-icons|vsc|11.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by bpasero** [comment]
Yeah good catch, this is because we use a fast `CopyFile` operation that probably copies over file permissions instead of creating a new file and writing into it. We either need to fallback to such a copy operation or disable local history for files that are saved as sudo...

**Comment by bpasero** [comment]
Hm nevermind, I cannot reproduce and in fact it should work because you are able to open the file before making a change without having to be sudo so the local file history is also able to show a diff.

I just tested this with `/etc/hosts` and was able to see changes in the local history.

Anything I am missing?

**Comment by mystiquewolf** [comment]
Hmm actually it show the diff, it's only the first row/first change (which i see now is supposed to be the same as the most recent change) that doesn't show any differences.

Restoring however doesn't seem to work. Nothing happens on click.

**Comment by bpasero** [comment]
Splitting up into 2 issues:
* this here: we need to tell the user about the error and not behave as if restore worked
* https://github.com/microsoft/vscode/issues/150680
