### ISSUE TITLE
JavaScript Intellisense Not working

### ISSUE THREAD

**Issue by bilal-08** [microsoft/vscode#149480]
As of yesterday i opened my project and started writing some code, there wasn't any suggestion in vsc so i thought it would a be bug that could be resolved with restarting PC. i neglected that and today i facing same problem.
i have Re-installed Vscode but the problem is not resolved

- VS Code Version:
latest
- OS Version:
windows 10
> Please let me know if more Information is needed

**Comment by gjsjohnmurray** [comment]
Please launch the `Start Extension Bisect` command from the Command Palette (F1) to investigate whether one of your extensions is causing this.

**Comment by bilal-08** [comment]
I tried this. And some other extension were having conflicts, this resolved the problem 👍. Thanks!
