### ISSUE TITLE
Have to focus opened files manually since the last update

### ISSUE THREAD

**Issue by github-account1111** [microsoft/vscode#149425]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.0
- OS Version: Windows 11

Since the last update, after left-clicking a file in explorer, I have to left-click again on the text area in order to start typing.
Otherwise it starts doing something unknown to me inside the explorer, like searching for something or doing some sort of filtering.
Basically something that I would guess is not as useful to most users as the ability to edit the file immediately upon opening it.

Steps to Reproduce:

1. Open a file from Explorer
1. Start typing

**Comment by gjsjohnmurray** [comment]
I haven't checked what pre-1.67 behaviour was, but on 1.67 you can either double-click in the first place (if you know you want to start editing the file immediately), or press Enter after the single-click.

Until you do either of those focus remains on the Explorer tree so you can type characters to filter it.

@misolori is currently exploring filtering discoverability improvements in #146806

**Comment by github-account1111** [comment]
@gjsjohnmurray I've checked several versions back, and it looks like the behavior has been like this for a while.
Sorry for spreading fake news folks.
Thanks for the helpful tips!
