### ISSUE TITLE
Workspace Trust: Concept unsafe if one cannot add folders recursively

### ISSUE THREAD

**Issue by schittli** [microsoft/vscode#149447]
Does this issue occur when all extensions are disabled?: Yes

### This is a conceptual security issue:

In VS Code, our list of trusted directories now contains much more than 150 entries.

So here we have the typical concept of phishing attacks: one in a hundred thousand overlooks the error and clicks.
We now have exactly the same thing in VS Code "Workspace Trust": if the list is so long that nobody is able to validate it, then the security can easily get broken.

But because our source code is always in the same directory tree(s), this concept would be much simpler and transparent: We recursively trust project directories:
```
C:\git\Projects\<Project1>\* is trusted
C:\git\Projects\<Project3>\* is trusted
```

At least, it would be great to allow the user to trust directories recursively or if they like to have hundreds of directories in this "Trusted" List.

Thanks a lot, kind regards,
Thomas

- VS Code Version: Version: 1.66.2
- OS Version: Win 10, x64 10.0.19044

Steps to Reproduce:
1. Start using VS Code
2. Work for some month
3. Try to validate your list of trusted directories

**Comment by sbatten** [comment]
@schittli directories added to the workspace trust list are automatically trusted recursively. any files and folders under an entries are automatically trusted. This is why if you check the box "Trust parent", it will add the parent directory to the list. You can probably clean up you list by trusting a parent folder and deleting all of the directories underneath.
