### ISSUE TITLE
Add a command palette launcher to the title bar

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#149445]
The quick pick family, command palette, search etc, is very powerful but often overlooked. Esp new users don't know about its keybindings are rarely discover it. The idea is to render a "launcher" in the title bar part that simply triggers quick pick, like so

https://user-images.githubusercontent.com/1794099/168265125-201d288a-29c6-41c8-ab2c-6e7b2f64569a.mov

This is related to https://github.com/microsoft/vscode/issues/115641

**Comment by jrieken** [comment]
explore/experiment for May

**Comment by jrieken** [comment]
I guess we should also consider to update the height of the title bar part, right? This is how it could look with some extra height

<img width="725" alt="Screenshot 2022-05-13 at 12 41 28" src="https://user-images.githubusercontent.com/1794099/168267740-f23d8981-4e95-49ff-a79e-06215c37608b.png">

**Comment by jrieken** [comment]
With https://github.com/microsoft/vscode/pull/149468 I have added support for custom hover here. @sbatten if this sticks we should also do the same for the layout switcher

**Comment by jrieken** [comment]
https://user-images.githubusercontent.com/1794099/168294114-993d3a05-070f-44fa-bb4a-644211d90a1d.mov

**Comment by daviddossett** [comment]
> I guess we should also consider to update the height of the title bar part, right? This is how it could look with some extra height

How would this look on Windows or other platforms w/ the classic menu? Would those be centered vertically?

<img width="354" alt="CleanShot 2022-05-13 at 08 51 25@2x" src="https://user-images.githubusercontent.com/25163139/168320883-f941ed94-b4e3-446f-be1e-dc2d4398f233.png">

**Comment by jrieken** [comment]
> Are we able to align the window actions vertically on macOS? Ours are still aligned to the top of the container:

I would hope so but idk where that currently comes from...

**Comment by sbatten** [comment]
@jrieken we can control that with `trafficLightPosition` on `BrowserWindow` https://www.electronjs.org/docs/latest/api/browser-window https://github.com/microsoft/vscode/blob/2dff5deef71fed71f039f8064e4e6deb818b1e3d/src/vs/platform/windows/electron-main/window.ts#L244-L249

**Comment by imthenachoman** [comment]
Reading this thread, I'm a bit confused. Was this option added? I can't find it in the settings but I see it in y'all's screenshots?

**Comment by jrieken** [comment]
Yeah, we haven't decided how to name this thing yet. The current favourite is "command center"

**Comment by heartacker** [comment]
now we could click the textbox to launch global search.
and we could click the combo box style to get more action,
I suggest adding another button to launching the command panel directly

![image](https://user-images.githubusercontent.com/1876302/170607297-8cc19286-dbb1-4158-ac61-c28d3ffe35e9.png)

**Comment by tjx666** [comment]
The best solution may be an float panel? Is there still some tech limitation to using float panel?

**Comment by jrieken** [comment]
Closing as the main part of the feature has been implements. More feedback is very welcome but should be filed as new issues. Issues in this feature-area a label [`command-center`](https://github.com/microsoft/vscode/issues?q=is%3Aopen+sort%3Aupdated-desc+label%3Acommand-center)

**Comment by jrieken** [comment]
To verify:

* ensure the `window.commandCenter` toggles the command center
