### ISSUE TITLE
No More PowerShell Spinning Icon when Script is Running

### ISSUE THREAD

**Issue by shangles** [microsoft/vscode#149410]
Issue Type: <b>Bug</b>

I updated VS Code to 1.67.0 (April 2022 update for Windows) and when I run a PowerShell .ps1 script I no longer see a spinning icon (or any other kind of progress visual cue) to indicate the script is running.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.88GB free)|
|Process Argv|--crash-reporter-id 7f5af24f-293e-4150-8dc0-a1cf8b378ec7|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdc:30486549

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "needs more info" terminal

**Comment by shangles** [comment]
I'm not sure what you want me to capture as what used to be there is no longer there.  In previous versions when I would "Run Active File" from the Terminal menu, a spinning Powershell icon indicating that something was happening would appear at the bottom of the status bar.  Now, with the latest version, there is nothing anywhere on the screen (apart from no flashing cursor) to indicate that the script is actually in progress and running.

**Comment by Tyriar** [comment]
It's not clear where you're expecting the icon to be or how you're running the script. I'm guessing this is an extension problem; do you mean to be using the powershell extension?

**Comment by shangles** [comment]
Yes, I'm using the PowerShell extension.  Sorry I'm not more clear but I don't know how else to explain the issue.  What was once a thing is no longer a thing.  I found the thing helpful.

**Comment by shangles** [comment]
OK.. I just realized that there's another repository for reporting issues with the PowerShell extension.  My bad.  There appears to already be an issue reported there for this:

https://github.com/PowerShell/vscode-powershell/issues/3954
