### ISSUE TITLE
Fedora36 + Wayland + Nvidia not functional

### ISSUE THREAD

**Issue by rishubn** [microsoft/vscode#149497]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67
- OS Version: Fedora 36, Wayland, Nvidia, Gnome 42

VS code is unusable (extremely laggy) with the above set up. It seems to be exactly the same issues from #134255 came back up. Also tested on `code-insiders` and had same issues.

`code --verbose` output: 
[code_verbose.log](https://github.com/microsoft/vscode/files/8690717/code_verbose.log)

**Comment by arieljimenez** [comment]
same here. Using the same workaround (the `--enable-features=Vulkan` one) fixed the problem on my case. I had to created an alias with that flag; and, despite the fact that launching it with that flag appears a warning: `Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.`, it runs smoothly.

**Comment by NoTuxNoBux** [comment]
I'm wondering what I'm missing, as I have a poor experience with VSCode on Wayland and NVIDIA (and GNOME with GBM) no matter what I pass.

1. If I don't pass any flags (XWayland, I guess), I get https://github.com/NVIDIA/open-gpu-kernel-modules/issues/187 or the same issue with the proprietary kernel modules; I tried both (old frames reused, terminal input cursor jumping back temporarily, ...).
2. If I pass `--enable-features=UseOzonePlatform --ozone-platform=wayland` and move the cursor using ctrl+left and ctrl+right in editors, it often temporarily leaves a duplicate ghost cursor behind in the middle of the words.
3. If I pass `--enable-features=UseOzonePlatform --ozone-platform=wayland --disable-gpu-sandbox` 1 and 2 are solved, but panels such as the secondary side panel with Git view start glitch black every so often, until they redraw due to some other reason.
4. If I pass `--enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland` VSCode crashes most of the time, and when it doesn't it leaves a margin of about 25px around every part of the screen despite claiming it's "fullscreen". It also sometimes starts opening many more project windows than I had open on startup for some reason.
5. If I throw `--enable-features=Vulkan` in the mix, I'm back to 2 for some reason.

**Comment by H-G-Hristov** [comment]
It is also unusable on Ubuntu 22.04 under Xfce in VBox on macOS, regardless of acceleration. It maybe it's an electron issue.

**Comment by avila** [comment]
I think I am also affected by this issue, but `--enable-features=Vulkan` seems to fix it for me, although I get the same warning @arieljimenez mentioned. I didn't experience the "duplicate ghost cursor" mentioned by @NoTuxNoBux. 




```
my system: 

VSCode Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.18.9-200.fc36.x86_64

NVidia driver version: 515.57
Nvidia card: GeForce GT 1030
```

**Comment by dmitry-mightydevops** [comment]
I have experience a very bad typing experience in vscode + wayland + fedora36 + nvidia

When typing with a keyboard one would expect for the cursor to display the printed key and then wait for the next one to be typed. Instead, when I type a character the cursor moves backwards, then forward with noticeable delay, then it displays the character and then it waits for the new one. It exhibits a similar behavior when pressing the arrow keys to move the cursor to another position.

```
❯ code --version                                                                                  
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64

❯ echo $XDG_SESSION_TYPE
wayland

❯ dnf list installed "*nvidia*"  
Installed Packages
akmod-nvidia.x86_64                                                                                                          3:515.57-1.fc36                                                                                   @rpmfusion-nonfree-nvidia-driver
kmod-nvidia-5.18.11-200.fc36.x86_64.x86_64                                                                                   3:515.57-1.fc36                                                                                   @@commandline                   
nvidia-settings.x86_64                                                                                                       3:515.57-1.fc36                                                                                   @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia.x86_64                                                                                                   3:515.57-1.fc36                                                                                   @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-cuda-libs.x86_64                                                                                         3:515.57-1.fc36                                                                                   @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-kmodsrc.x86_64                                                                                           3:515.57-1.fc36                                                                                   @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-libs.x86_64                                                                                              3:515.57-1.fc36                                                                                   @rpmfusion-nonfree-nvidia-driver
xorg-x11-drv-nvidia-power.x86_64 

```

I have Nvidia Quadro P5000

the only way to fix for me is to pass the following args:

```
code --enable-features=Vulkan,UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```

**Comment by ahmafi** [comment]
I have an issue with Wayland that might be similar to this, my VSCode doesn't even open without passing the `Vulkan` in `--enable-features`.

This works:
```
code --enable-features=Vulkan,UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```

This doesn't:
```
code --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
```

```
Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:48.541Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.18.16-200.fc36.x86_64
```

**Comment by rjoelnorgren** [comment]
> the only way to fix for me is to pass the following args:
> 
> ```
> code --enable-features=Vulkan,UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
> ```

Until today, I was using the very helpful switches suggested by @dmitry-mightydevops to fix input lag weird/cursor jumping. However, code no longer opens when the --ozone-platform=wayland. That said, even without the switches code seems to run very smoothly now.

**Comment by deepak1556** [comment]
This should work with latest insiders https://code.visualstudio.com/insiders using `--enable-features=WaylandWindowDecorations --ozone-platform=wayland`, please comment if the issue is present with this version.

**Comment by sepehr** [comment]
Can confirm that `1.75.0-insider` works just fine under Fedora 37+Wayland as @deepak1556 [suggested](https://github.com/microsoft/vscode/issues/149497#issuecomment-1340358381) above.
