### ISSUE TITLE
Classic Menu Bar buttons don't open menus on Safari/vscode.dev

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#149476]
I noticed that the `classic` Menu Bar doesn't open the menus on vscode.dev when using Safari. 

## Safari

Note the explorer focus indicating that I'm clicking on the buttons to no effect:

![safari](https://user-images.githubusercontent.com/25163139/168322419-b15efa2f-47d1-4c89-b302-8e75c063213b.gif)

## Edge

![edge](https://user-images.githubusercontent.com/25163139/168322463-a2a45a50-083a-45e0-a934-4d04fccbdff1.gif)

**Comment by daviddossett** [comment]
Looks to work as expected on stable:

https://user-images.githubusercontent.com/25163139/168656909-4fa6edfe-b68e-4d86-afe4-3e700fb69e0c.mp4

**Comment by sbatten** [comment]
Thanks @daviddossett likely regression from updating styles for the WCO
