### ISSUE TITLE
The default selected item in completed items list is not consistent

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#14944]
- VSCode Version: 1.7.1
- OS Version: Windows and Mac
- Extension: Go
- Customized Settings: None
- User defined Snippets: None

Below is a sample Go code with variables whose name start with `f` or `m`

Type either `f` or `m`, auto complete gives a list of completion items alphabetically sorted as expected.
But, the default selected item is different.
In case of `m` it is the first completion item
In case of `f` it is the first completion item of type snippet.

The Go extension provides the completion items, but as far as I know, it doesn't have a say in which of the completion items is selected by default.

![image](https://cloud.githubusercontent.com/assets/16890566/19987804/33c4305a-a1da-11e6-8457-08ede9a0c379.png)

![image](https://cloud.githubusercontent.com/assets/16890566/19987823/4568a566-a1da-11e6-9473-af7e703bae5d.png)

**Comment by ramya-rao-a** [comment]
Am not sure if this is a bug. If the extension authors know how exactly such default selections are made, it would help

**Comment by jrieken** [comment]
when all matches are equal, the shortest wins because it has the highest coverage (for instance matches 50% of the suggestion vs 33%)

**Comment by ramya-rao-a** [comment]
Got it, Thanks!
