### ISSUE TITLE
CR in a LF scripts unexpectly replaced by LF

### ISSUE THREAD

**Issue by chensln** [microsoft/vscode#149433]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.68.0-insider (user setup)
- OS Version:Windows_NT x64 6.1.7601

Steps to Reproduce:

1.create a file, line end with LF and contain CR.
i.e. `echo -e 'aaa\rbbb\nccc\n' > 1`
![image](https://user-images.githubusercontent.com/51817614/168244535-f69f9345-de94-408e-995e-b5f26bc374df.png)
2. edit with vscode, input or delete words
![image](https://user-images.githubusercontent.com/51817614/168241955-d24cd283-a599-402e-a89a-6c3f5953c1f5.png)
3.save
4.CR was replaced by LF.
![image](https://user-images.githubusercontent.com/51817614/168244442-ac8ea6cb-509d-4b2b-859f-f94855689b6f.png)

usually, this replacement takes no effect. but I have a shell script in which CR is a separator of awk command. once CR was replaced by LF, the script run into error.

**Comment by alexdima** [comment]
VS Code is currently very opinionated about line endings and tries to "fix them" as best as possible to make the problem of mixed line endings a thing of the past. This, however, comes at the cost that it ends up touching areas of the text buffer that are not edited directly.

I suggest we track this in a not identical, but similar issues, #127 or #35797 .
