### ISSUE TITLE
Running node-sass inside an extension?

### ISSUE THREAD

**Issue by testerez** [Microsoft/vscode#14948]
I'm trying to use node-sass inside a vscode extension but I'm getting this error:

> Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (49)

I suppose that it's because I use my local node version to install node-sass but vscode executes it with it's own node version...

Is there any way to fix that?

**Comment by MarkSky** [comment]
I would like to know how to solve this problem in Visual Studio Code?
And, how to setting in Visual Studio Code to let all characters are encoded correctly?

**Comment by joaomoreno** [comment]
`node-sass` works by natively binding to libsass. Native dependencies are still an open issue: #6929
