### ISSUE TITLE
Feedback on `window.experimental.titleMenu`

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#149434]
Issue Type: <b>Feature Request</b>

Trying out this experimental feature and liking what I see so far.

A couple of points about the magnifier button on the right of the new field:

1. Tooltip says "Quick Pick". Is this text a placeholder waiting for something better?

2. For consistency the "Show All Commands" option should probably have an ellipsis.

3. I also wonder if "Find Command..." or "Run Command..." would be clearer. Or be consistent with the gearwheel menu on the Activity Bar and label it "Command Palette..."

4. Maybe append keybindings to these entries as a way of teaching people what they are.

![image](https://user-images.githubusercontent.com/6726799/168252712-55c36787-ae94-4a47-a626-a7210d1a4bfe.png)

VS Code version: Code - Insiders 1.68.0-insider (113287ccc3be52dc3409d451a9b3416d133dca1a, 2022-05-13T05:15:42.124Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

/assign @jrieken

**Comment by jrieken** [comment]
Thanks for early feedback. With https://github.com/microsoft/vscode/pull/149441 the search menu will be removed again. The title menu (input-like thing) will show a chevron that invoke "quick pick help", like so

https://user-images.githubusercontent.com/1794099/168263184-759e30a0-306a-43d3-9d10-b236ea9b1673.mov

What do you think? Makes sense?

**Comment by jrieken** [comment]
> Maybe append keybindings to these entries as a way of teaching people what they are.

That's still valid and we should show keybindings when using `?` mode with quick pick

**Comment by gjsjohnmurray** [comment]
Makes good sense. I'm following #149445 so you may want to close this one.

**Comment by jrieken** [comment]
check
