### ISSUE TITLE
`Marked as resolved` marking has poor visibility with high contrast color themes

### ISSUE THREAD

**Issue by vahvero** [microsoft/vscode#149464]
### Problem statement:

Currently, differences between resolved and unresolved icons is relatively poor with high contrast color themes. 

![Screenshot from 2022-05-13 15-56-27](https://user-images.githubusercontent.com/30704280/168287939-30a0495d-4e61-4099-b0d7-95adcc479da8.png)

compared to default theme

![Screenshot from 2022-05-13 15-57-17](https://user-images.githubusercontent.com/30704280/168288068-7189846b-f1ef-4f02-b21c-7c5b6808bee0.png)

It is difficult to tell conversations apart in high contrast color themes.

### Suggestion:

Change the icon of `marked as resolved` to an unique icon to differentiate the two conversation states.

**Comment by alexr00** [comment]
@daviddossett do you have any ideas for which icon I could use for resolved comments? I tried the "check" but it doesn't seem quite right.

![image](https://user-images.githubusercontent.com/38270282/175508636-fdfd4022-07e9-493f-8510-6c0b339ddbdd.png)

**Comment by hermannloose** [comment]
@alexr00 the original mocks from our side in #142081 used the `report` codicon for unresolved comments and `comment` for resolved comments, maybe that's an option? Not ideal long-term, if the `report` icon or `comment` icon are changed in isolation at some point by someone not aware of their use in the comments panel, but then the only really robust option would be specific icons for resolved and unresolved icons in codicons (or I guess SVGs?).

**Comment by daviddossett** [comment]
What about something like this? Not yet in codicons but we could add it.

<img width="1447" alt="CleanShot 2022-06-24 at 15 03 38@2x" src="https://user-images.githubusercontent.com/25163139/175698812-39f3eb3e-c7f4-41e2-9b58-634cf5c5cfbf.png">

cc @misolori when he's back from vacation.

**Comment by alexr00** [comment]
@daviddossett it looks like it will fit nicely in with both the comment and discussion icons. Can we add it to codicons?

**Comment by hermannloose** [comment]
@daviddossett While the icon in isolation looks perfectly fine, I wanted to point out that resolved comments are generally the ones *less* relevant to the user at a given time, and for workspaces with many resolved discussions, their icon is going to occur more frequently than the one for unresolved comments, so I am a bit worried that the proposed icon for these would be more visually busy than the icon for unresolved comments, which is what the user should focus on?

**Comment by daviddossett** [comment]
That framing makes sense to me. How about introducing an icon-with-dot pattern as we use that for a "this needs attention" pattern in multiple areas. Resolved comments could default to the regular comment icon.

<img width="1061" alt="CleanShot 2022-06-27 at 11 37 02@2x" src="https://user-images.githubusercontent.com/25163139/176012051-24176c54-02e0-41a8-98ca-a4ec1e8ced45.png">

**Comment by alexr00** [comment]
I'm happy with that too.

**Comment by daviddossett** [comment]
[Opened a PR](https://github.com/microsoft/vscode-codicons/pull/121) to add the icons in the codicons repo. Miguel is on vacation so it may take a bit to land.

**Comment by daviddossett** [comment]
Ok, added `comment-unresolved` to codicons 👍

**Comment by alexr00** [comment]
Thanks for the new icon! Adopted:

![image](https://user-images.githubusercontent.com/38270282/178482667-80914463-8011-4981-bc67-e79fe36a65f8.png)

**Comment by albertelo** [comment]
Would it make sense to add the dot treatment to the comment thread icon for unresolved comments in a thread? @daviddossett

**Comment by alexr00** [comment]
So long as the icon doesn't look too crowded then it sounds good.

**Comment by daviddossett** [comment]
Tried this and I don't think it will work quite as well with the current `comment-discussion` icon. @albertelo do you have any ideas for indicating that a thread has unresolved comments in it? 

<img width="402" alt="CleanShot 2022-07-14 at 11 11 33@2x" src="https://user-images.githubusercontent.com/25163139/179053161-258bf47d-f476-4c6f-88c1-547bdcc21b0a.png">

I wonder if we could instead could consider unread dots that are separated from the icon instead of built-in. Just a thought.

**Comment by albertelo** [comment]
An idea that comes to mind is changing the position of the message icons:
![comment](https://user-images.githubusercontent.com/26898237/179226546-0cbcc071-2451-4e06-9725-8779a4e0478c.png)

This way placing the circle is less disruptive: 
![comment](https://user-images.githubusercontent.com/26898237/179227215-457320d4-982a-4745-b760-8cda5a468eeb.png)

**Comment by hermannloose** [comment]
Can we reevaluate whether we actually need two separate icons for singleton comments and comment threads with replies? 

The current UI already prominently indicates when a thread has more than one message, with the "[indent] n comments, Last reply from someUser" treatment (which I understand the two icons might slightly predate):

<img width="603" alt="Screen Shot 2022-07-15 at 18 15 50" src="https://user-images.githubusercontent.com/163766/179264780-6bad666d-da3d-4085-83a7-6d8d1394d4c7.png">

In our experience, most if not all threads will have 2+ replies after the first review round (initial reviewer comments + author reply), meaning we have the busier icon of the two used for most entries in the panel.

I believe it would be completely fine to just use `comment` and `comment-unresolved` throughout, what do you think?

**Comment by daviddossett** [comment]
I was actually thinking about that myself when I saw this and had to think for a second to realize what was going on.

<img width="295" alt="CleanShot 2022-07-15 at 10 00 02@2x" src="https://user-images.githubusercontent.com/25163139/179272364-bbf180fe-419a-4195-921c-897d627133b3.png">

`comment-discussion` is a fairly busy icon already so I'd be open to such a change.

**Comment by alexr00** [comment]
👍I'll remove the uses of `comment-discussion`.
