### ISSUE TITLE
Git 

### ISSUE THREAD

**Issue by TheRivar** [microsoft/vscode#149477]
Issue Type: <b>Bug</b>

After cloning a new git repository or moving to an old one, Source Control can't find a git repository in any of those folders.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (19.30GB free)|
|Process Argv|--crash-reporter-id de7acc89-0a2d-48b2-b20a-8c94f164ecce|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-apollo|apo|1.19.11
intellij-theme|arz|1.11.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
emoji-snippets|dev|1.5.3
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
copilot|Git|1.20.5902
vscode-graphql|Gra|0.4.4
vscode-peacock|joh|4.0.1
mongodb-vscode|mon|0.9.3
azure-pipelines|ms-|1.205.0
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.22.0
vscode-language-pack-es|MS-|1.67.3
csharp|ms-|1.24.4
vscode-kubernetes-tools|ms-|1.3.8
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.2
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
powershell|ms-|2022.5.1
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
angular-console|nrw|17.16.0
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.17.0
polacode|pnp|0.3.4
vscode-yaml|red|1.7.0
LiveServer|rit|5.7.5
trailing-spaces|sha|0.3.1
sonarlint-vscode|Son|3.4.1
addDocComments|ste|0.0.8
errorlens|use|3.4.2
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.21
vscode-todo-highlight|way|1.0.5
bracket-lens|wra|1.5.1

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdf:30486550

```

</details>

**Comment by TheRivar** [comment]
After some research, I've found that behavior is probably related to an unsafe repository warning shown by the integrated terminal when I run "git status". Running the same command from the git bash works as expected without raising any exception.
Opening the project from the command line using "code ." works well but not when opening from the GUI.

**Comment by lszomoru** [comment]
@TheRivar, very interesting. Let me see if I understand things correctly:
* Running `git status` from git bash returns the status information as expected
* Running `git status` from the VS Code integrated terminal shows the unsafe repository warning
* Opening the folder/workspace using `code .`, VS Code to detect the repository
* Opening the folder/workspace from the GUI, VS Code does not detect the repository

**Comment by CourtneyAbraham** [comment]
Can confirm I am having the same issue, also getting the unsafe repository warning through the integrated Git Bash, unless opening Code from the command line, then Git Bash no longer reports it to be unsafe.
However then the source control tab fills up with infinite copies of the repository, as I scroll down more show up

**Comment by TheRivar** [comment]
@lszomoru that's just what's happening. You've described the scenario perfectly.

A folder/workspace opened from bash:
![folder_opened_from_bash](https://user-images.githubusercontent.com/48964586/169855397-28393d7f-08a5-4a92-8f97-2c32d06232a9.JPG)

A folder/workspace opened from GUI:
![folder_opened_from_GUI](https://user-images.githubusercontent.com/48964586/169855402-69552a5f-2526-48f1-a8a9-446630ea8a3a.JPG)

**Comment by lszomoru** [comment]
Thank you all for all the information. I will take a look at this today and I will update the issue with my findings.

**Comment by lszomoru** [comment]
@TheRivar, @CourtneyAbraham, the latest Insiders release contains some improvements to the git extensions's logging which should help us get closer to the root cause. Could you please use the steps outlined in [this wiki](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#log-level-setting) to enable `Trace` logging. After you have enabled logging, open the folder/workspace once from bash and once from the GUI and share the contents of [the git output channel](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#logging). Thank you!

**Comment by CourtneyAbraham** [comment]
I just launched the latest insiders release from the website and the issue no longer happens
