### ISSUE TITLE
Titlebar border does not render on high contrast themes

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#149474]
Looking at #149445. Seems like it works fine on all the other themes I have installed. I think the theme tokens ultimately inherit from a null value here:

```
export const MENUBAR_SELECTION_BACKGROUND = registerColor('menubar.selectionBackground', {
	dark: transparent(Color.white, 0.1),
	light: transparent(Color.black, 0.1),
	hcDark: null,
	hcLight: null,
}, localize('menubarSelectionBackground', "Background color of the selected menu item in the menubar."));
```

<img width="535" alt="CleanShot 2022-05-13 at 08 31 49@2x" src="https://user-images.githubusercontent.com/25163139/168317401-c65baf65-5059-4f29-8fbd-d90e084c4817.png">

<img width="567" alt="CleanShot 2022-05-13 at 08 31 56@2x" src="https://user-images.githubusercontent.com/25163139/168317409-f76506e8-705f-4f0e-90d7-00b1dc20d6af.png">

**Comment by jrieken** [comment]
@daviddossett Can you help me to define colors for this?

**Comment by daviddossett** [comment]
I think `var(--vscode-input-border)` makes the most sense here.

<img width="665" alt="CleanShot 2022-05-16 at 08 13 18@2x" src="https://user-images.githubusercontent.com/25163139/168625777-c3f49a72-a66f-4965-beed-59405d5308f7.png">

<img width="687" alt="CleanShot 2022-05-16 at 08 13 25@2x" src="https://user-images.githubusercontent.com/25163139/168625796-aaf085f0-c979-427e-9833-002d174e22a5.png">

I'll file a separate issue for this nested contrast border issue on hover:

<img width="100" alt="CleanShot 2022-05-16 at 08 14 11@2x" src="https://user-images.githubusercontent.com/25163139/168625892-6c373209-7477-4c0c-b2a8-dd756c4e4fca.png">
