### ISSUE TITLE
[coffeescript] syntax highlighting breaks on indented comment blocks

### ISSUE THREAD

**Issue by pzuraq** [Microsoft/vscode#14945]
- VSCode Version: 1.7.0
- OS Version: 10.11.6

Steps to Reproduce:

1. Add comment block (three hashtags in a row)
2. Indent comment block

![screen shot 2016-11-03 at 3 55 09 pm](https://cloud.githubusercontent.com/assets/685518/19988541/f5c36808-a1dd-11e6-92d0-b6afdd2eb678.png)

**Comment by pzuraq** [comment]
This appears to be caused by the lookbehind used in the regular expression marking the beginning of a comment block [here](https://github.com/Microsoft/vscode/blob/master/extensions/coffeescript/syntaxes/coffeescript.json#L173). For some reason, this expression matches all characters except for empty spaces.

A temporary fix on my machine is to change the expression from `(?<!#)###(?!#)` to `^[^#]*###(?!#)`, though this would possibly break for multiple block comments on a single line.

**Comment by tonythomson** [comment]
Per @aeschli, VSC's CoffeeScript grammar is from https://github.com/textmate/coffee-script.tmbundle. There is a [corresponding issue](https://github.com/textmate/coffee-script.tmbundle/issues/10) in that repo.

**Comment by pzuraq** [comment]
Any word on this and #15008? I've been fixing it manually but whenever VSCode updates it wipes that out. Really tedious for me, would love to fix it if I can help.

**Comment by drKnoxy** [comment]
They already have a PR in for the fix ... https://github.com/textmate/coffee-script.tmbundle/pull/11

**Comment by pzuraq** [comment]
@drKnoxy seems to be dead in the water, and there isn't a fix for #15008. Are we sure that the maintainers of that package are active?

**Comment by drKnoxy** [comment]
Probably inactive, I hear everyone is switching from textmate to vscode (har har har)

**Comment by aeschli** [comment]
Fixed by switching to the atom/language-coffee-script grammar.
