### ISSUE TITLE
CPU utilization of Code is near 99%

### ISSUE THREAD

**Issue by igor92128** [Microsoft/vscode#14943]
- VSCode Version: 1.7.1
- OS Version: Windows 2012 R2

Steps to Reproduce:

1. Install fresh copy of Windows 2012 R2
2. Disable your internet connection
3. Try running Code

**Comment by rebornix** [comment]
@igor92128 can you take a look at https://github.com/Microsoft/vscode/issues/14222 and see if you provide info we listed there :)

**Comment by aeschli** [comment]
Closing due to lack of information. Please reopen with data described above.
