### ISSUE TITLE
Can not open file from Problems tab

### ISSUE THREAD

**Issue by svinuesa** [microsoft/vscode#149444]
Issue Type: <b>Bug</b>

From the Problems tab, click an error
Visual Studio attempts to open a new tab with the file 
=> Error : The editor could not be opened because the file was not found

Expected results:
The current tab displays the Row in error.

VS Code version: Code 1.67.1 (Universal) (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 4b0bef0a-cffd-4b50-a8ca-3cfca84e4c99|
|Screen Reader|no|
|VM|0%|
</details>
<!-- generated by issue reporter --
![Screenshot 2022-05-13 at 12 14 09](https://user-images.githubusercontent.com/32143353/168264119-4b622fdf-3293-4bb3-9c49-2a47c63e68ce.png)
>

**Comment by rbwhitaker** [comment]
I'm having the same problem. When I open the file from the explorer tree, it works fine. But when I open it from the Problems tab, I get that error as well.

Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by sandy081** [comment]
This happens mainly because the errors generated by the extension are pointing to invalid or non-existing file. Please file an issue against the corresponding extension.
