### ISSUE TITLE
Visual studio becomes blurry in areas

### ISSUE THREAD

**Issue by Simomagy** [microsoft/vscode#149458]
Issue Type: <b>Performance Issue</b>

It happened randomly i don't know why and how to reproduce it but it's impossible to code like that

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.25115
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700K @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.63GB free)|
|Process Argv|--crash-reporter-id f32f0e3e-3b9b-4ee4-899c-25cf950e1feb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	  7848	code main
    0	    39	  3528	   utility-network-service
    0	   147	  6824	   extensionHost
    0	    76	 23516	     "C:\Users\msstu\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\msstu\.vscode\extensions\funkyremi.vscode-google-translate-1.4.13\server\out\server.js --node-ipc --clientProcessId=6824
    0	    76	 23904	     "C:\Users\msstu\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\msstu\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=6824
    0	    86	  9932	   issue-reporter
    0	   166	 12896	   window (Settings - Visual Studio Code)
    0	   105	 18256	   shared-process
    0	    74	  1496	     fileWatcher
    0	    70	  2252	     ptyHost
    0	    99	 19452	   gpu-process
    0	    26	 24372	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
jquerysnippets|don|0.0.1
vscode-google-translate|fun|1.4.13
yaclock|jam|1.0.1
kite|kit|0.147.0
vsliveshare|ms-|1.0.5561
color-highlight|nau|2.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by Igorgro** [comment]
I had the same issue, it was caused by the invalid version of Nvidia drviers. Try to upgrade or downgrade them to make the version march you GPU.

**Comment by deepak1556** [comment]
Try disabling hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration and see if the issue persists.
