### ISSUE TITLE
cannot install Azure DevOps add-in

### ISSUE THREAD

**Issue by ppschmi** [microsoft/vscode#149528]
Hello
I downloaded blueprint.vsts-open-work-items-in-excel-0.1.71.vsix from marketplace today

I just update VStudio Code before to Version 1.67.1
```
Version: 1.67.1 (system setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.18363
```

When I try to install vsix in vscode extensions - I get error: 
Error Message:
extension/package.json not found inside zip.

![grafik](https://user-images.githubusercontent.com/5331030/168418667-05ab0160-2085-403a-807a-842bee4b25c7.png)

Could you please look into that?

Best regards
Peter Schmidt

**Comment by ppschmi** [comment]
Hello sandy081
I installed azuredevops_inttooloffice2019_deu.exe (outside of VSCode).

It worked for Excel Add-in
Best regards
Peter

**Comment by sandy081** [comment]
It seems the VSIX is corrupted. 

What is the reason to download from Marketplace and install instead of installing directly from Marketplace from VS Code?

**Comment by ppschmi** [comment]
cannot give specific reason. just read something and tried to install
Best regards
Peter
