### ISSUE TITLE
expected to start vscode from one remote ssh client from terminal, but started on all client

### ISSUE THREAD

**Issue by can2049** [microsoft/vscode#149519]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version on windows:
Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

- Vs code Version: 1.67.1 on linux
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.4.0-109-generic

Remote SSH version: v0.80.0

Steps to Reproduce:

1. start a linux server
2. start vscode in a Ubuntu18.04 client. Open a project on the server vs Remote SSH
3. start vscode in a Windows10 client. Open a project on the server vs Remote SSH
4. on the windows or ubuntu vscode, on the terminal, cd into any dir, start new vscode project via this command `code .`

Result: this project opened on all clients
Expect: this project only open in this client

**Comment by aeschli** [comment]
I think this is caused by the same bug as for https://github.com/microsoft/vscode/issues/121926
