### ISSUE TITLE
Unable to log in to Microsoft or GitHub Account in mainland China

### ISSUE THREAD

**Issue by guoidou** [microsoft/vscode#149538]
When using the Microsoft account synchronization function, there is a problem with the login, and the data synchronization cannot be performed normally by jumping to vs code.

After the browser login is successful, the redirection fails, the information is as follows

![image](https://user-images.githubusercontent.com/82764266/168424584-c2a8fa5c-9248-4ca3-903c-190db18a32c5.png)

**Comment by guoidou** [comment]
And this

![image](https://user-images.githubusercontent.com/82764266/168426612-27767090-ffcb-4e7b-a0fd-74631c6097ae.png)

**Comment by seanbonjean** [comment]
the same problem occurred to my machine, both my Microsoft account and GitHub account have this problem

**Comment by TylerLeonhardt** [comment]
So it appears that vscode.dev is blocked in China? Does the same apply to github.dev? Can someone check for me (go to github.dev/microsoft/vscode)?

**Comment by JoshuaLiew** [comment]
> So it appears that vscode.dev is blocked in China? Does the same apply to github.dev? Can someone check for me (go to github.dev/microsoft/vscode)?
However, you can log in successfully with the Microsoft account using the old version.

**Comment by JoshuaLiew** [comment]
> So it appears that vscode.dev is blocked in China? Does the same apply to github.dev? Can someone check for me (go to github.dev/microsoft/vscode)?

However, you can log in successfully with the Microsoft account using the old version

**Comment by CodeZhangBorui** [comment]
> 所以看起来 vscode.dev 在中国被封锁了？这同样适用于 github.dev 吗？有人可以帮我检查（去 github.dev/microsoft/vscode）吗？

Yes, github.dev can't login with Microsoft, too. This is screenshot: 

![image](https://user-images.githubusercontent.com/61909157/170237565-86fd79fb-4160-42bf-bb4a-8508bee89afc.png)

**Comment by CodeZhangBorui** [comment]
`github.dev` isn't blocked now. But because `vscode.dev` is blocked, Github Web Editor unable to log in to Microsoft, too.

**Comment by Winzler-Botawar** [comment]
Same question, it doesn't work too while opening VPN and switch to other areas.

**Comment by CodeZhangBorui** [comment]
#149675 The same reason to the question

**Comment by TylerLeonhardt** [comment]
Thanks for all the info so far, I want to narrow down what works and what doesn't. Can you all give this a try?

1. Go to https://insiders.vscode.dev
1. if it does not resolve, add a screenshot to this issue with the error
1. If it resolves, Sign in to Settings Sync (the little person icon above the gear)
1. Report back if that works or not. If it does not, tell me where you get stuck
1. Go to https://vscode.dev
1. if it does not resolve, add a screenshot to this issue with the error
1. If it resolves, Sign in to Settings Sync (the little person icon above the gear)
1. Report back if that works or not. If it does not, tell me where you get stuck

**Comment by TylerLeonhardt** [comment]
Thanks @wenda84, can you also start at Step 5 and see have 5-8 go?

**Comment by seanbonjean** [comment]
and when I try to sign in using the insider version, the same error occurred
![image](https://user-images.githubusercontent.com/35868779/171448406-0a2d3721-3edc-4596-8dd5-e89c6b49e39e.png)

**Comment by wenda84** [comment]
> Thanks @wenda84, can you also start at Step 5 and see have 5-8 go?

emm, i can not open https://vscode.dev/, but i can ping it.  And I also tried use a proxy software, it helps me vist Github faster,  but it didn't help to VSCode login.

![step_5](https://user-images.githubusercontent.com/37608409/171447806-ea6b6c44-e586-4d4f-b7a2-ae5c238f0fb5.png)
![ping](https://user-images.githubusercontent.com/37608409/171447842-f592c95b-0b5a-4b97-854e-70b0c012faf6.png)

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/171455775-86f49f82-b81b-4468-886c-1bf049596c0a.png)

Online testing tool shows ISP DNS servers in many regions resolve `vscode.dev` to 127.0.0.1. Some other regions have a seemingly correct IP, but still can't establish TCP connections to it.

**Comment by wenda84** [comment]
I solved the problem by modifying the local DNS settings. 
国内的兄弟们试下修改本地DNS服务器为114.114.114.114，我改了就好了。 电信自带的不知道什么垃圾DNS。

**Comment by CodeZhangBorui** [comment]
You can use Edge Addon [Malus](https://microsoftedge.microsoft.com/addons/detail/malus%E5%8A%A0%E9%80%9F%E5%99%A8-%E5%85%8D%E8%B4%B9%E5%9B%9E%E5%9B%BD%E5%94%AF%E4%B8%80%E5%AE%98%E6%96%B9%E6%AD%A3%E7%89%88/mklimbcpglbjohihbpdmnfhlkciacbhm) VPN to connect to Chinese Network.

**Comment by UsernameKLNU** [comment]
> 我通过修改本地DNS设置解决了这个问题。 国内的兄弟们试下修改本地DNS服务器为114.114.114.114，我改了就好了。电信自带的不知道什么垃圾DNS。
确实，现在能用了

**Comment by GeekYang216** [comment]
> I solved the problem by modifying the local DNS settings. 国内的兄弟们试下修改本地DNS服务器为114.114.114.114，我改了就好了。 电信自带的不知道什么垃圾DNS。

我改了DNS服务器没有解决还是一样登录不了

**Comment by GeekYang216** [comment]
Please tell me how to solve the problem. I also encountered the same problem. Changing the DNS server to 114.114.114.114 cannot be solved

**Comment by GeekYang1993** [comment]
I have solved this problem. The operation method is as follows:

1. Modify DNS server to 114.114.114.114

2. Open CMD and enter ipconfig /flushdns to refresh DNS cache

3. Reopen vscode and log in using Microsoft or GitHub

Users in Chinese Mainland can try this method

**Comment by TylerLeonhardt** [comment]
Just to let everyone know, we are actively working on this. I can't provide too many updates as I have requested assistance from a team at Microsoft who is better suited to fix this problem, but I will ensure it is looked at and provide as many updates as I possibly can.

**Comment by summer-breeze123** [comment]
> I have solved this problem. The operation method is as follows:
> 
> 1. Modify DNS server to 114.114.114.114
> 2. Open CMD and enter ipconfig /flushdns to refresh DNS cache
> 3. Reopen vscode and log in using Microsoft or GitHub
> 
> Users in Chinese Mainland can try this method

it does work!thank you verk much!
折腾一天了都，真的是醍醐灌顶啊

**Comment by summer-breeze123** [comment]
> I have solved this problem. The operation method is as follows:
> 
> 1. Modify DNS server to 114.114.114.114
> 2. Open CMD and enter ipconfig /flushdns to refresh DNS cache
> 3. Reopen vscode and log in using Microsoft or GitHub
> 
> Users in Chinese Mainland can try this method

it does work!thank you very much!
感谢指点迷津，折腾好久了

**Comment by GeekYang1993** [comment]
The method of modifying the DNS server and refreshing the cache may not be 100% successful. I found that after successful login, the login will still fail if I log off.
通过修改DNS服务器并刷新缓存的方法不一定100%成功，我发现成功登录以后如果注销在登录也还是会失败。

**Comment by tsenghaipo226** [comment]
> 

+1

**Comment by tsenghaipo226** [comment]
> I solved the problem by modifying the local DNS settings. 国内的兄弟们试下修改本地DNS服务器为114.114.114.114，我改了就好了。 电信自带的不知道什么垃圾DNS。

+1 居然成功了

**Comment by TylerLeonhardt** [comment]
Hi all, we have done some work to get vscode.dev unblocked. Our tools say that 90% of China should be able to access the site now. Can you all give it a try again?

**Comment by CodeZhangBorui** [comment]
It works. I’m in Shandong, China, using China Unicom Network.

**Comment by CodeZhangBorui** [comment]
![image](https://user-images.githubusercontent.com/61909157/176361006-57df9dda-273f-4908-bb34-7aebba5b84ba.png)
It works on China Educational Network (be used in Chinese Schools), too. And it has Chinese translate now!

**Comment by TylerLeonhardt** [comment]
I believe we have "fixed" the problem at this point. It may take a little bit more time in some locations as this new policy propagates across China but I don't believe there's any more action on our part on the VS Code team so I'm going to close this as fixed.

Let us know if you're still having this issue and if you are, what your internet provider is and what region of China you are in.
