### ISSUE TITLE
shift+cmd+v keybings conflict

### ISSUE THREAD

**Issue by libaoxu** [Microsoft/vscode#14955]
- VSCode Version: Code 1.5.3 (5be4091987a98e3870d89d630eb87be6d9bafd27, 2016-09-22T13:06:49.879Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce:

1.shift+cmd+v :markdown.showPreview
2.shift+cmd+v: clipboardPasteAction

粘贴快捷键 即使markdownPreviewiew 也是 粘贴功能

**Comment by Tyriar** [comment]
Please update to 1.7.1, currently they're using different `when` clauses to prevent any conflicts from happening. You could also be having issues with an extension, you can launch code using
