### ISSUE TITLE
JavaScript template literals syntax is broken

### ISSUE THREAD

**Issue by dcefram** [Microsoft/vscode#14958]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. open vscode
2. open a JS file with template literals

Example Screenshot:
![capture](https://cloud.githubusercontent.com/assets/687325/19995934/a7c055bc-a296-11e6-93c7-1331c68eb488.PNG)

This issue does not occur on the previous version.

**Comment by rebornix** [comment]
We have tracked this issue here https://github.com/Microsoft/TypeScript-TmLanguage/issues/341
