### ISSUE TITLE
Clicking Activity Bar Icon Launches WebView Panel...

### ISSUE THREAD

**Issue by busticated** [microsoft/vscode#149556]
Hey there 👋 

Apologies in advance if this is a duplicate - I swear there was already another issue filed but despite digging around in here, i can't find it 🤷‍♂️ 

As the title of the issue states, i'd like to contribute an Activity Bar icon that when clicked by a user launches a WebView Panel.

I'm able to do this today by creatively hijacking the associated Tree Provider (see here: [1](https://github.com/auchenberg/vscode-browser-preview/blob/master/ext-src/targetTreeProvider.ts), [2](https://github.com/auchenberg/vscode-browser-preview/commit/9baebd6aac81737250d6dc86b045f6311861947d)). 

That approach works but is a bit clunky as the user can briefly see the tree ui open and close. How about adding full and formal support for this UX?

**Comment by gjsjohnmurray** [comment]
Does this UX exist elsewhere in the core product? I think Activity Bar icons on the upper region are all associated with view containers on the Side Bar.

Did you consider using a Status Bar panel as the way for users to open your extension's Webview Panel?

**Comment by mjbvz** [comment]
@gjsjohnmurray is correct: the activity bar switches between views and is not meant to be used for performing generic operations

You can use the activity bar if you have a `webview view`. Otherwise try finding a different way for users to open your webview panel

**Comment by busticated** [comment]
@mjbvz 

> You can use the activity bar if you have a webview view.

can you point me to some docs on this?

**Comment by jasongonzales23** [comment]
+1 for this issue please. We have a VSCode extension that truly does not work well in the sidebar. We know we can make a simple webapp to make the UX excellent but are constrained by the sidebar's size and TreeView API. We can get around the API by just putting webviews only in the sidebar, but even in that case we'd be trying to put "5lbs of sausage into a 1lb bag" (pardon the impolite saying).

**Comment by daviddossett** [comment]
I figured I should copy my reply from the original Slack thread here:

> Activity bar items are stateful and are closely coupled with the sidebar. There is an active item, and the rest are inactive. The active item displays the sidebar content associated with that tab. That’s one of the core navigation patterns in VS Code today. What happens when you click on an activity bar item and VS Code opens up a random webview panel, completely unrelated to the sidebar? What state is that item now in? Effectively it just acted like a link—which is not what users would expect, especially if they are used to using VS Code.  It’s almost as if a browser tab stole your click and instead opened up a dialog instead of displaying the expected website associated with that tab.
>
> Now, it could be considered that activity bar items could indeed be selected to show a completely new area in place of the typical sidebar/editor area (kind of like the Calendar view in Teams), but that would be a much larger discussion.
