### ISSUE TITLE
Go To Definition of Types In Hover in TypeScript

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#149592]
It would awesome if one could go to the definition of a type shown in the hover tooltip, ideally by using `Ctrl`+ `Click` in the hover:

![image](https://user-images.githubusercontent.com/2931520/168480329-75aab63a-cb27-4693-a8f8-6fe71c3ecaf9.png)

**Comment by mjbvz** [comment]
I've been tracking this under #64566 since we also want the same feature for diagnostic messages
