### ISSUE TITLE
ParseError: KaTeX parse error: Expected & or \\ or \cr or \end at end of input: ...

### ISSUE THREAD

**Issue by viocha** [microsoft/vscode#149593]
in vscode ,  the formula is rendered with katex, an KaTeX parse Error occurred
![image](https://user-images.githubusercontent.com/66580331/168478731-431ab9fd-64c9-4652-89cf-eb0059ce74c0.png)

in pycharm , it's rendered  properly with mathjax
![image](https://user-images.githubusercontent.com/66580331/168478619-5d8557ff-27ec-44ad-a68b-3fe0bdbbebf8.png)

latex code:

```
%%latex
\begin{gather}
        H(x)=\log{\left(\sqrt{2} \right)}h_1(x)+\log{\left(\frac{\sqrt{15}}{3} \right)}h_2(x)+\log{\left(\frac{\sqrt{21}}{3} \right)}h_3(x)
        \\
         \displaystyle
   h_1(x)=\begin{cases}
    1 \ & \mathrm{if} \  x>=5.5 \\
    -1 \ &\mathrm{if} \  x<5.5
    \end{cases}
    ,\quad \displaystyle
   h_2(x)=\begin{cases}
    -1 \ & \mathrm{if} \  x>=4.5 \\
    1 \ &\mathrm{if} \  x<4.5
    \end{cases}
    ,\quad \displaystyle
   h_3(x)=\begin{cases}
    1 \ & \mathrm{if} \  x>=3.5 \\
    -1 \ &\mathrm{if} \  x<3.5
    \end{cases}
\end{gather}

```

**Comment by mjbvz** [comment]
The equation renders fine if you wrap it in `$$` so I recon it's related to how we handle bare math blocks. Relevant code: https://github.com/mjbvz/markdown-it-katex

**Comment by KaniSuhan** [comment]
wow

**Comment by hsadia538** [comment]
Hi @viocha @mjbvz Can I work on this?

**Comment by viocha** [comment]
sure



---Original---
From: ***@***.***&gt;
Date: Thu, Jun 16, 2022 00:04 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/vscode] ParseError: KaTeX parse error: Expected &amp; or \\ or \cr or \end at end of input: ... (Issue #149593)




 
Hi @viocha @mjbvz Can I work on this?

**Comment by hsadia538** [comment]
@viocha Can you let me know where to get started?
As per the last comment, it works when wrapping with "$$" so I figure I need to look into how vscode is rendering lateX in general? any other pointers?

**Comment by viocha** [comment]
https://katex.org/docs/options.htmlhttp://docs.mathjax.org/en/latest/options/input/tex.html

the reason is probably katex can't process environments outside $$ , but i wonder if katex has a similar option 'processEnvironments' like MathJax provides



---Original---
From: ***@***.***&gt;
Date: Fri, Jun 17, 2022 19:33 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/vscode] ParseError: KaTeX parse error: Expected &amp; or \\ or \cr or \end at end of input: ... (Issue #149593)




 
@viocha Can you let me know where to get started?
 As per the last comment, it works when wrapping with "$$" so I figure I need to look into how vscode is rendering lateX in general? any other pointers?

**Comment by colombod** [comment]
This is the same for .NET Interactive
