### ISSUE TITLE
Download vscode very slow in China

### ISSUE THREAD

**Issue by NateLing** [Microsoft/vscode#14951]
FUCK GFW, I download vscode from https://code.visualstudio.com, The zip file put in s3 server.it is very very slow in China.
![s3](https://cloud.githubusercontent.com/assets/9606668/19991704/9fb33ebc-a272-11e6-9aa0-ddc609729226.png)

**Comment by lolotus** [comment]
Me too,but i have downloaded it from other website.So you can try too!

**Comment by Milewski** [comment]
Not only the software itself... all the extension market is helll slowww... i can never download any extension at first.. after a whole day trying.... eventually one or two get install....

**Comment by seanmcbreen** [comment]
Quick stupid question - how long does the core product take to download and on which OS.  We want to make this better.

**Comment by Milewski** [comment]
@seanmcbreen Using google chrome on mac at Shanghai -> 

Download doesn't go up 20kbps

![image](https://cloud.githubusercontent.com/assets/2874967/19998806/d148c8a2-a2a9-11e6-83ad-4623a41ce8d5.png)
 

and.. the extensions.. i am still trying to install and i still couldnt...

![image](https://cloud.githubusercontent.com/assets/2874967/19998874/2c6a5c78-a2aa-11e6-978a-ab36b4b835dc.png)

**Comment by twang281314** [comment]
the extensions  cannot  install now

**Comment by NateLing** [comment]
@seanmcbreen  we download vscode need 40 mins or 1 hour, amazon s3 server very very slow in china. maybe you can put the zip file on microsoft server.

**Comment by shynome** [comment]
when I recommend vscode to my workmate, it's so slowly to install extension so that I give up

**Comment by viradhamMS** [comment]
@Milewski, @twang281314,
We have fixed the slowness issue for extensions. I believe it is pretty fast now. Please check and reach out if that is not the case.

- Vishnu

**Comment by Milewski** [comment]
Great! download completes instantaneously now ~

**Comment by joaomoreno** [comment]
Closing as per CDN improvements from the Marketplace.

**Comment by solenovex** [comment]
The download speed is at about 0-10K/s in China using the CHINATELECOM broadband, the system is Ubuntu 16.04...  and after 2 hours only finished 59% using uGet....

**Comment by joaomoreno** [comment]
cc @hamenon @modigrv

**Comment by viradhamMS** [comment]
@solenovex - Is there a particular extension that takes longer to download (or) it is taking longer for all the extensions?
