### ISSUE TITLE
vscode.DocumentLink support for line/character position if URI scheme is "file" or possibility to Escape the resolveDocumentLink call

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#149523]
The object [`vscode.DocumentLink`](https://code.visualstudio.com/api/references/vscode-api#DocumentLink) does not allow to specify a `vscode.Position` (line and character).

If I open the file myself, in `resolveDocumentLink`, I get an error message **`Failed to open this link because its target is missing.`**. 

There is no way to Escape the `resolveDocumentLink` call by returning `undefined` or `null` (both valid `ProviderResult`).

If you return a `DocumentLink` without target the error message makes sense.

If it is allowed to Escape the `resolveDocumentLink` you can use it to do other things than `Follow Link` by supplying a different tooltip string.

In the default tooltip for https links the text `Follow link` is a clickable link. The tooltip of  `DocumentLink` does not allow me to use a `MarkDownString`. How can I create such a link in the tooltip?

**Comment by jrieken** [comment]
> you can use it to do other things than Follow Link by supplying a different tooltip string.

Yeah, that's whole point of "topic APIs". A link provider should only return links ;-)

To the problem of giving line and character. You should be able to pass them as uri fragments, e.g `file:///Users/jrieken/Code/_samples/abc/test.c#L3,3` will open `test.c` and reveal line 3 at column 3. Please note that these numbers are 1-offset based, not 0-offsets

**Comment by rioj7** [comment]
@jrieken How would I go about creating a Uri for `file:///Users/jrieken/Code/c#/abc/test.cs#L5,3`?

I can't use `vscode.Uri.file('/Users/jrieken/Code/c#/abc/test.cs#L5,3')`.

I used

```
let filePath = '/Users/jrieken/Code/c#/abc/test.cs';
let uri = vscode.Uri.file(filePath).with({fragment:'L5,3'});
```

> In the default tooltip for https links the text `Follow link` is a clickable link.

Is it possible for extensions to create a clickable link in the tooltip of a Document Link?
