### ISSUE TITLE
“Close folder” command

### ISSUE THREAD

**Issue by schuelermine** [microsoft/vscode#149551]
A command “Close folder” that closes the folder in the current window, but keeps the window open, returning it to the default start up state with no folder opened.

**Comment by schuelermine** [comment]
Wholly unnecessary sample diagram:
![vscode-close-folder-diagram](https://user-images.githubusercontent.com/48802534/168447899-1647c5aa-88f4-489a-ba52-e5f40586dd87.png)

**Comment by gjsjohnmurray** [comment]
`Workspaces: Close Workspace`

**Comment by schuelermine** [comment]
Oh

**Comment by schuelermine** [comment]
Thank you
