### ISSUE TITLE
Star Debugging

### ISSUE THREAD

**Issue by Thornton85** [microsoft/vscode#149512]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

I can't debug. I have a Gateway 64 bit laptop and OS Windows 7 Ultimate 64 bit. In the past it worked fine with MinGw64. Now, again I reinstalled it again with the MSYS2, as its documentation says. Starting debugging (F5) starts fine, but then doesn't follow to the debug console or external terminal (cmd). The path is correct: I check the versions of g++ and gdb and everything is fine.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Athlon(tm) II P320 Dual-Core Processor (2 x 2094)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|1.75GB (0.42GB free)|
|Process Argv|--crash-reporter-id ddb4a07f-fe9a-496d-aeb4-0cddb22bfdd6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.13
vscode-language-pack-es|MS-|1.67.3
cpptools|ms-|1.10.2
cpptools-extension-pack|ms-|1.2.0
printcode|nob|3.0.0
vscode-icons|vsc|11.11.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdc:30486549

```

</details>

**Comment by roblourens** [comment]
Please file this on the repo of the C++ extension
