### ISSUE TITLE
 When run build task, there are strange words in error message.

### ISSUE THREAD

**Issue by MarkSky** [Microsoft/vscode#14959]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|bower|donjayamanne|0.0.3|
|jquerysnippets|donjayamanne|0.0.1|
|xml|DotJoshJohnson|1.6.0|
|vscode-html-css|ecmel|0.0.30|
|emoji-code|idleberg|0.1.6|
|format-indent|Kasik96|1.3.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|phpcsfixer|makao|0.0.1|
|vscode-autoprefixer|mrmlnc|2.0.0|
|csharp|ms-vscode|1.4.1|
|js-atom-grammar|ms-vscode|0.1.10|
|debugger-for-chrome|msjsdiag|2.2.0|
|debugger-for-edge|msjsdiag|0.4.1|
|debugger-for-ios-web|msjsdiag|0.1.2|
|vscode-icons|robertohuertasm|3.0.7|
|code-bing|SirTobi|0.2.0|
|php-formatter|Sophisticode|0.1.3|
|cordova-tools|vsmobile|1.2.3|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

I try to transpiling Sass and Less into CSS by the steps from website:
[CSS, Sass and Less](https://code.visualstudio.com/Docs/languages/css)
but, on step 4, after I pressing Ctrl+Shift+B, the error message show:

> 'node-sass' ���O�����Υ~���R�O�B�i���檺�{���Χ妸�ɡC

I don't know what does it means. 
How could I do to let it shows the true language words?

**Comment by rebornix** [comment]
First of all, the reason that all characters are encoded incorrectly. Secondly, it's dup of #14948

**Comment by MarkSky** [comment]
I understand there is an error about Native dependencies.
But, my another question is how to solve all characters are encoded incorrectly in error message.
Is there any set should I do?
