### ISSUE TITLE
Comments panel not persisting state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#149503]
https://user-images.githubusercontent.com/35271042/168391537-6bc223d0-af63-4d9b-84fe-daa430cb8316.mp4

Steps to Reproduce:

1. open the panel, see the comments tab
2. hide the comments tab, reload the window
3. :bug: comments panel keeps re-appearing

Version: 1.68.0-insider (Universal)
Commit: 9c29becfad5f68270b9b23efeafb147722c5feba
Date: 2022-05-13T17:25:40.854Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

**Comment by alexr00** [comment]
@sbatten I'm not sure what's going on here, maybe you know. The Comments view is actually registered with `canToggleVisibility: false`, so I'm surprised it's even possible to hide the view. Is there anything else I need to do to prevent it from hiding or, even better, to respect the hide after reload?

https://github.com/microsoft/vscode/blob/02b59c6e3a2a346376eb067c93cbe01f28d71cee/src/vs/workbench/api/browser/mainThreadComments.ts#L582-L602

**Comment by sbatten** [comment]
The action @misolori takes is hiding the _View Container_ so that's why it is hideable. There isn't anything that you can set on the _View Container_ to prevent the hiding. I am also at a loss. 

@misolori can you "Export Settings as a Profile"? the profile should have the stored information about your views and view containers

**Comment by sbatten** [comment]
hmm I don't see anything alarming in there, but I can now reproduce it

**Comment by alexr00** [comment]
@sbatten is there any logging that can be added in views to help narrow this down? I don't think there's anything else I can do from comments.

**Comment by sbatten** [comment]
after lots of debugging, I think I have a fairly simple fix in the PR above.
