### ISSUE TITLE
workbench.editor.wrapTabs=true causing tabs to jump when typing text in editor

### ISSUE THREAD

**Issue by abriginets** [microsoft/vscode#149571]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: Windows 10 10.0.19044

https://user-images.githubusercontent.com/17240507/168477000-385d2f5d-356f-466e-a692-c11af0773f1b.mp4

Steps to Reproduce:

1. Set `workbench.editor.wrapTabs` value to `true`
2. Open multiple tabs that will be wrapped into multiple rows
3. The last tab will be wrapped into a new row while you are typing (this only happens when current row is full and the next tab you are about to open would appear in a new row)

**Comment by bpasero** [comment]
I believe this is a corner case in your specific case, can you provide access to the sources and steps for me to reproduce?
