### ISSUE TITLE
Terminal pops up after canceling the ipython console.

### ISSUE THREAD

**Issue by ibaris** [microsoft/vscode#149562]
Does this issue occur when all extensions are disabled?: Yes/No

<img width="284" alt="image" src="https://user-images.githubusercontent.com/15630368/168462632-17c4b98b-14a6-4196-aea6-db3b7c3ddf12.png">
Steps to Reproduce:

![Animation](https://user-images.githubusercontent.com/15630368/168462960-a8a9991a-b213-4bcc-a7ff-5f98967ca00e.gif)

This is annoying.

**Comment by meganrogge** [comment]
please file an issue with the extension
