### ISSUE TITLE
vscode-inputbox does not respect min/max attributes

### ISSUE THREAD

**Issue by SethFalco** [microsoft/vscode#149561]
Does this issue occur when all extensions are disabled?: N/A (Extension API)

- VS Code Version:  
Version: 1.68.0-insider
Commit: 624bbc4fb966bfa34e9486e320a64a138ac337fd
Date: 2022-05-12T05:21:29.328Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.10.0-14-amd64 snap

- OS Version:
Linux 5.10.0-14-amd64 SMP Debian 5.10.113-1 (2022-04-29) x86_64 GNU/Linux

Steps to Reproduce:

1. Make an extension with a webview that uses `vscode-inputbox` with a number type and min or max attribute, for example.

```html
<vscode-inputbox id="since-input" type="number" value="-1" min="-1"></vscode-inputbox>
```

Similar to Chromium, when the type is set to `number`, it only allows numerical characters. (i.e. `\d\.e` and I don't know what else, and it also adds an up/down arrow and lets user increment/decrement the number with their mouse.

However, the `min` and `max` attributes aren't being applied, usually a user can still type smaller numbers than the `min`, but using the buttons or scroll wheel should not. In this case, regardless of method, the user can always set the number below the minimum.

**Comment by mjbvz** [comment]
Please file this against webview toolkit: https://github.com/microsoft/vscode-webview-ui-toolkit
