### ISSUE TITLE
Cannot Open Command Prompt in Windows 10 Insider Preview Build 11082

### ISSUE THREAD

**Issue by MystK** [Microsoft/vscode#1495]
Just installed build 11082, and I can't open the command prompt from inside of VSCode. I right click the folder tree and click, "Open in Command Prompt." Is anyone else having this issue?

**Comment by egamma** [comment]
I cannot reproduce this and I'm on Win 10. Is there any error in the Chrome Dev Tools  Console (Help | Show Developer Tools | Console)
