### ISSUE TITLE
the markdown syntax highlight is broken

### ISSUE THREAD

**Issue by chiyx** [Microsoft/vscode#14956]
- VSCode Version: 1.7.1
- OS Version:  OS X Capitan 10.11

Steps to Reproduce:

1.  open vscode
2.  open a markdown file

![image](https://cloud.githubusercontent.com/assets/1563521/19993935/441a02ae-a284-11e6-93ec-076789a1480a.png)

now only the top list is highlight.

**Comment by mjbvz** [comment]
Thanks for the report.

#14634 should fix most cases around this. There's an older bug tracking highlighting of indented lists in markdown, but I can't find it at the moment so I'll keep this one open.

**Comment by mjbvz** [comment]
Confirmed that this was fixed by #14634 

![screen shot 2016-11-08 at 3 48 38 pm](https://cloud.githubusercontent.com/assets/12821956/20122200/db9982a0-a5ca-11e6-8f7f-f96c77fd32cc.png)

The fix should be available for testing in insiders builds shortly.
