### ISSUE TITLE
Typo in settings

### ISSUE THREAD

**Issue by Raymo111** [microsoft/vscode#149508]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest/Master branch
- OS Version: All

Steps to Reproduce:

1. Go to settings > `terminal.integrated.defaultProfile` > the one for your OS (with the dropdown set to `null` by default)
2. Hover over `JavaScript Debug Terminal`
3. Read the last line (notice how it says `idenfifier` instead of `identifier`

**Comment by Tyriar** [comment]
<img width="866" alt="Screen Shot 2022-05-16 at 7 56 38 am" src="https://user-images.githubusercontent.com/2193314/168622290-930507e3-c390-4576-89e1-0901ea38c3c1.png">
