### ISSUE TITLE
Get React Intellisense on this react-boilerplate in Visual Studio Code

### ISSUE THREAD

**Issue by abarcemas** [Microsoft/vscode#14952]
I am using this [react-boilerplate](https://github.com/mxstbr/react-boilerplate) and I want to have the inteliSense working on my Visual Studio Code.

I have installed the react typings `typings install react` and it installs on the `./typings/` folder of the root directory. While the `jsconfig.json` is set to ES6.

    {
      "compilerOptions": {
        "target": "es6"
      }
    }

when i try to create a component in the `./app/components/` directory, no intellisense when i type `class H4 extends React.`

**Comment by waderyan** [comment]
@abarcemas thank you for opening this issue. Can you try with [VS Code Insiders](https://code.visualstudio.com/insiders)? This should be fixed now.
