### ISSUE TITLE
Error of Crash

### ISSUE THREAD

**Issue by AFHiB** [microsoft/vscode#149515]
VS reported to have crashed several times in the passed 5 minutes, this holds true. Currently struggling to maintain connection with digital ocean - it runs Ubuntu and is securted with an SSHKey. I am currently building a working website, so it is a development area. The crashes mostly happen when I give the command "yarn run build". On "yarn run serve" connection is maintained. "yarn run dev" provides no issues either.

**Comment by roblourens** [comment]
Sorry I need some more details about exactly what you are doing, what error message you see, etc
