### ISSUE TITLE
Portable linux version starts a new X11 session

### ISSUE THREAD

**Issue by amfogor** [microsoft/vscode#149577]
- VS Code Version: 1.67
- OS Version: 5.4.48-gentoo
- Window Manager: dwm

When running `code` the effect is the same as running `code; startx`(with normal `code`)

Steps to reproduce:
- get https://update.code.visualstudio.com/1.67.1/linux-x64/stable
- 
```
su
chown root chrome-sandbox
chmod 4755 chrome-sandbox
exit
./code
```

An older version of vscode doesn't have this bug. The one that worked I deleted, when I downloaded the new one. I tried running versions `1.0 - 1.4`, but I'm getting `error while loading shared libraries: libnotify.so.4: cannot open shared object file: No such file or directory`

**Comment by deepak1556** [comment]
Please install the missing dependencies, they are required by the runtime.
