### ISSUE TITLE
Latex - Equation/Split-evironment cannot handle more than one '&' per line

### ISSUE THREAD

**Issue by ahudde** [microsoft/vscode#149564]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

The latex formula (in a markdown cell in jupyter notebook) 

\begin{equation}
\begin{split}
x &= 2 * 3 &= 6 \\\\
y &= 4 * 5 &= 20
\end{split}
\end{equation}

does not compile, but instead shows:

ParseError: KaTeX parse error: Too many tab character: & at position 43: ,,it} x &= 2 * 3 &= 6 \\ y &= 4 *...

Running this cell in an jupyter notebook via firefox works perfectly fine,

If this code is cotained in an .md-document, the same behaviour appears, whereas for example RStudio can render this formula correctly.

**Comment by mjbvz** [comment]
Opened https://github.com/KaTeX/KaTeX/issues/3634 to track this upstream
