### ISSUE TITLE
`code --remote ssh-remote+HOST REMOTE_FOLDER_PATH` fails when REMOTE_FOLDER_PATH contains dot

### ISSUE THREAD

**Issue by qx-juilliard** [microsoft/vscode#149583]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version:

```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-41-generic
```

OS Version:

```
Ubuntu 20.04.4 LTS x86_64
```

Steps to Reproduce:

1. On remote machine HOST, create any folder with dot. Sample code to reproduce: `mkdir /dev/shm/test.dir`
2. On local machine, open remote folder in command line. Sample code to reproduce: `code --remote ssh-remote+HOST /dev/shm/test.dir`

The remote folder is not opened automatically (when the intended behavior should be that with a folder name without dot).

**Comment by aeschli** [comment]
We have a heuristic to find out if the path is a file or a folder. If the path has a file extension, we try to open it as file.
To overrule that, add a `/` at the end.
Can you try that?

**Comment by qx-juilliard** [comment]
A trailing slash indeed make it work as intended, thanks!

Though the issue urgency is low, would it be possible to replace the heuristic by something more robust (such as the `vscode-server` checking `test -d` on remote)?

**Comment by aeschli** [comment]
We won't change the heuristic as it is documented as in use: https://code.visualstudio.com/docs/remote/troubleshooting#_connect-to-a-remote-host-from-the-terminal

You can alternatively use the `--file-uri` and `--folder-uri` syntax:
`code --folder-uri=vscode-remote://ssh-remote+HOST/dev/shm/test.dir

**Comment by qx-juilliard** [comment]
Good to know the `--folder-uri` flag. Will close the issue now. Thanks!
