### ISSUE TITLE
Need search feature for file explorer

### ISSUE THREAD

**Issue by mark-hahn** [microsoft/vscode#149554]
I usually have hundred of files nested in directories.  Often I look for files that don't have an obvious location.  It is quite painful to browse through files.  It is especially painful when I remember some of the file name but not the beginning so alphabetical listings don't help.

Looking in node_modules is the worst.  There can be upwards of a thousand files.

I would greatly appreciate a search feature with good file name matching.  Thanks for listening (reading).

**Comment by gjsjohnmurray** [comment]
Did you try [Quick Open](https://code.visualstudio.com/Docs/editor/editingevolved#_quick-file-navigation)?

**Comment by mark-hahn** [comment]
No, but the feature as described in the docs doesn't seem to help searching.  To the contrary it says "The Explorer is great for navigating between files when you are exploring a project".   I disagree with that statement which is why I'm asking for the search feature.

Quick Open deals with recently opened files and breadcrumbs.  Neither of these help explore a project.

Thanks for the suggestion though.

**Comment by mark-hahn** [comment]
I was wrong.  Ctrl-P gives the search I want.  Closing now.  Sorry if I bothered anyone.
