### ISSUE TITLE
Throw no commits yet error on `git stash`

### ISSUE THREAD

**Issue by liby** [microsoft/vscode#149547]
When I don't have any commits, running `git stash` doesn't do anything, there are no prompts and it can be confusing. In the output, you can see the hint given by Git.
<img width="2032" alt="Xnip2022-05-15_02-45-50" src="https://user-images.githubusercontent.com/38807139/168444623-94a6c723-9ac7-431b-bf52-e5cbdf9db471.png">

**Comment by gjsjohnmurray** [comment]
Instead of a notification maybe add a `when` clause to the `git.stash` command so that it is only enabled when there are changes to stash.
