### ISSUE TITLE
keybinding when !editorTextFocus not triggering when Output window has focus 

### ISSUE THREAD

**Issue by ericblade** [Microsoft/vscode#14950]
- VSCode Version: 1.7.1
- OS Version: Win10

Following keybinding:

   {
        "key": "ctrl+c",
        "command": "workbench.action.tasks.terminate",
        "when": "!editorTextFocus"
    }

In 1.6.0 and 1.6.1 this keybinding would allow me to ctrl-c if I had the Output pane focused.  Now I have to specifically unfocus all elements by clicking on some border, to be able to use this keybinding.

I am not positive if it worked in 1.7.0, but I believe it did. 

(i would also be happy to accept a "when" outputPaneFocused .. or outputPaneFocused && (buildTaskRunning || testTaskRunning) .. something like that. )

**Comment by alexandrudima** [comment]
@ericblade There was a regression in 1.6.0 and 1.6.1 that @isidorn has fixed where the output editor would not have the context `editorTextFocus`. e.g. the arrow keys were not working, many things were not working.

In 1.7.0 the regression has been fixed and the output editor has the key `editorTextFocus`. 

It also has the key `inOutput` so you should be able to "target" it:
```
   {
        "key": "ctrl+c",
        "command": "workbench.action.tasks.terminate",
        "when": "inOutput"
    }
```
