### ISSUE TITLE
`editorLangId` is not working for View `when` clause in `package.json`

### ISSUE THREAD

**Issue by rioj7** [microsoft/vscode#149522]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0-insider Commit: 9c29becfa  Date: 2022-05-13
- OS Version: Win8.1

I have a view in my extension that I only want to show if the active editor is HTML.

I add the following to `package.json`

```
  "contributes": {
    "views": {
      "explorer": [
        {
          "id": "someID",
          "name": "SomeName",
          "when": "editorLangId == html"
        }
      ]
    }
  }
```

This does not work.

If I create a new context variable and set its value in a `onDidChangeActiveTextEditor` event handler

```
  const onChangeActiveTextEditor = editor => {
    vscode.commands.executeCommand('setContext', 'myExt:fileIsHTML', editor && editor.document.languageId === 'html');
  };
  vscode.window.onDidChangeActiveTextEditor(onChangeActiveTextEditor, null, context.subscriptions);
  onChangeActiveTextEditor(vscode.window.activeTextEditor);
```

and change the `when` clause to

```
          "when": "myExt:fileIsHTML"
```

It works.

Why does `editorLangId` not work in a `when` clause for Views?

There is no mention in the [when clause contexts](https://code.visualstudio.com/api/references/when-clause-contexts) page that certain context variables can't be used in certain situations.

**Comment by gjsjohnmurray** [comment]
> Why does `editorLangId` not work in a `when` clause for Views?

Suppose you have more than one editor open and visible. Which one do you want to check? Probably the "active" one. But the built-in context key isn't named `activeEditorLangId`.

**Comment by rioj7** [comment]
@gjsjohnmurray In a keybinding `editorLangId` works and which editor does it apply to: the **active** editor, and in a keybinding I do not need to use `activeEditorLangId` or `editorGrp[1-9]LangId` or `editorCurrentGrpLangId`.

So which editor does `editorLangId` apply to if you have multiple groups/editors?

**Comment by jrieken** [comment]
> which editor does it apply to: the active editor, and in a keybinding I do not need to use activeEditorLangId or editorGrp[1-9]LangId or editorCurrentGrpLangId.

That only works because you trigger the keybinding from "within" the correct/focused editor, e.g it won't work if you invoke the keybinding when focusing a view. 


> There is no mention in the [when clause contexts](https://code.visualstudio.com/api/references/when-clause-contexts) page that certain context variables can't be used in certain situations.

That's correct, rule of thumb is that context keys starting with `editor...` only work inside an editor
