### ISSUE TITLE
No ejecuta mi archivo

### ISSUE THREAD

**Issue by itsdiego0o** [microsoft/vscode#149605]
Hemos escrito los datos necesarios en su Portapapeles porque eran demasiado grandes para enviarlos. Ahora debe pegarlos.
al precionar F5 para que se abra mi archivo en Chrome o Explorer, se queda en blanco la pagina que habia estando fiuncionando con anterioridad, necesito una solucion urgente, llevo trabajando en mi proyecto escolar y lo necesito.
Gracias por su atencion.

When pressing F5 to open my file in Chrome or Explorer, the page that had been working before remains blank, I need an urgent solution, I have been working on my school project and I need it.
Thank you for your time

**Comment by dbaeumer** [comment]
Can you please attach a screen cast that shows the problem. I am not sure I understand it correctly.

**Comment by dbaeumer** [comment]
Dups 149653
