### ISSUE TITLE
VSCode-Web is blocked in mainland China

### ISSUE THREAD

**Issue by CodeZhangBorui** [microsoft/vscode#149675]
VSCode-Web (vscode.dev) is blocked in mainland China and cannot be accessed. But turning on VPN can open it.

![](https://pic.imgdb.cn/item/6282e287094754312925cb68.png)

#### Visual Studio Code Information:

Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:52.619Z
Browser: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36 Edg/101.0.1210.47

**Comment by BBoyLong** [comment]
Is that means we can`t login in VS Code with Microsoft account in mainland China?being troubled by this problem.

**Comment by joaomoreno** [comment]
vscode.dev is still in preview. Once GA, we'll have to address the China firewall. Until then, there's not much we'll do.

**Comment by CodeZhangBorui** [comment]
I suggest making a VSCode-Web mirror on Github Pages because Github Pages is not blocked now.

**Comment by CodeZhangBorui** [comment]
Such as [vscode-web-cn.github.io](https://vscode-web-cn.github.io/) ("vscode-web-cn" is my other Github account). But it can't work.
