### ISSUE TITLE
Remote Debugger error 80131534

### ISSUE THREAD

**Issue by amadoa** [microsoft/vscode#149663]
Issue Type: <b>Bug</b>

When using the Docker .NET Core Launch task to debug inside a container I get the following error.

Starting: "docker" exec -i emsorders-dev /remote_debugger/vsdbg --interpreter=vscode
Error from pipe program 'docker': FATAL ERROR: Failed to initialize dispatcher with error 80131534
The pipe program 'docker' exited unexpectedly with code 255.

This is the configuration in the launch.json
{
            "name": "Docker .NET Core Launch",
            "type": "docker",
            "request": "launch",
            "preLaunchTask": "docker-run: debug",
            "netCore": {
                "appProject": "${workspaceFolder}/src/WebUI/WebUI.csproj"
            },
            "dockerServerReadyAction": {
                "uriFormat": "%s://localhost:%s/api"
            }
        }

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (3.58GB free)|
|Process Argv|. --crash-reporter-id 08891d5b-310b-4050-94db-46333b888533|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.0.6
prettier-vscode|esb|9.5.0
vscode-pull-request-github|Git|0.42.0
vscode-peacock|joh|4.0.1
docomment|k--|0.1.30
rainbow-csv|mec|2.3.0
vscode-azurefunctions|ms-|1.6.2
vscode-azureresourcegroups|ms-|0.4.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
vscode-kubernetes-tools|ms-|1.3.8
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
azure-account|ms-|0.10.1
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.17.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.7.0
LiveServer|rit|5.7.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by roblourens** [comment]
I think you want to file this on the Docker extension
