### ISSUE TITLE
Too many binary downloads/installations

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/vscode#14965]
Every two days or so there's a binary installer I have to download and install. The "restart and update" prompt is there almost every day. It's distracting.

I bet these updates are primarily updates to the scores of JS files in the package? e.g. not actually updates to any binaries, DLLs, etc.?

Can't you roll out the core JS updates a JS files, centrally, from a package repository, like you do with plugins? Does it really have to be a full binary distribution for every minor change?

**Comment by ffes** [comment]
Is that just because of this: http://code.visualstudio.com/blogs/2016/11/3/rollback

**Comment by rebornix** [comment]
@mindplay-dk could you please which versions you are using these days? We did release 1.7 but later on we found some issues with NPM site then we roll back real quick. That might lead to your concern.

**Comment by aeschli** [comment]
Closing due to lack of information.
