### ISSUE TITLE
Multiple target debugging: Not all targets started

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#14964]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|2.2.0|
|other extensions not|important for this issue|---|

---
When you set up your launch.json for multiple target debugging with **coreclr** and **chrome** configurations VSCode will - most of the time - only the **coreclr** application, and show the info bar, that I should configure my launch configuration but the configuration should be correct.

Steps to Reproduce:

1. Setup a core and chrome launch configuration similar to this
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch Core",
			"type": "coreclr",
			"request": "launch",
			"preLaunchTask": "build",
			"program": "${workspaceRoot}\\bin\\Debug\\netcoreapp1.0\\MyWebApp.dll",
			"args": [],
			"cwd": "${workspaceRoot}",
			"stopAtEntry": false,
			"internalConsoleOptions": "openOnSessionStart",
			"env": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			}
		},
		{
			"name": "Launch Chrome",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:5000",
			"sourceMaps": true,
			"webRoot": "${workspaceRoot}/wwwroot"
		},
		{
			"name": "dotnet + chrome",
			"type": "composite",
			"request": "launch",
			"configurationNames": [
				"Launch Core",
				"Launch Chrome"
			]
		}
	]
}
```
2. Run "dotnet + chrome"
3. You will see VSCodes info bar that I should set up the launch configuration

PS: It doesn't happen all the time. Sometimes it starts also the chrome configuration. But most of the time it shows the info.

![multiple target debugging](https://cloud.githubusercontent.com/assets/7260053/19999213/4bb64bd4-a271-11e6-9269-a1cf765c704f.gif)

**Comment by Adrienb16** [comment]
Hello,

i have a same problem when i try to debug two appliations in dotnet console.

My launch.json configuration : 

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch (console 1)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/ConsoleApp1/bin/Debug/netcoreapp1.0/ConsoleApp1.dll",
            "args": [],
            "cwd": "${workspaceRoot}/ConsoleApp1",
            "externalConsole": false,
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Launch (console 2)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/ConsoleApp2/bin/Debug/netcoreapp1.0/ConsoleApp2.dll",
            "args": [],
            "cwd": "${workspaceRoot}/ConsoleApp2",
            "externalConsole": false,
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart"
        },
        {
            "name": ".NET Core Attach",
            "type": "composite",
            "request": "launch",
            "configurationNames": [
                ".NET Core Launch (console 1)",
                ".NET Core Launch (console 2)"
            ],
            "cwd": "${workspaceRoot}"
        }
    ]
}
```

But when à run ".NET Core" i have a message for set up the launch configuration and ".NET Core Launch (console 1)" start only.

**Comment by davormas** [comment]
Same problem as Adrienb16

`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Launch",
            "type": "composite",
            "request": "launch",
            "configurationNames": [
                ".NET Core Launch (api)",
                ".NET Core Launch (web)"
            ],
            "cwd": "${workspaceRoot}"
        },
        {
            "name": ".NET Core Launch (api)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/src/MySQLCorePOC/bin/Debug/netcoreapp1.0/MySQLCorePOC.dll",
            "args": [],
            "cwd": "${workspaceRoot}/src/MySQLCorePOC",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Launch (web)",
            "type": "coreclr",
            "request": "launch",
            "preLaunchTask": "build",
            "program": "${workspaceRoot}/src/PortalPOC/bin/Debug/netcoreapp1.0/PortalPOC.dll",
            "args": [],
            "cwd": "${workspaceRoot}/src/PortalPOC",
            "stopAtEntry": false,
            "internalConsoleOptions": "openOnSessionStart",
            "launchBrowser": {
                "enabled": true,
                "args": "${auto-detect-url}",
                "windows": {
                    "command": "cmd.exe",
                    "args": "/C start ${auto-detect-url}"
                },
                "osx": {
                    "command": "open"
                },
                "linux": {
                    "command": "xdg-open"
                }
            },
            "env": {
                "ASPNETCORE_ENVIRONMENT": "Development"
            },
            "sourceFileMap": {
                "/Views": "${workspaceRoot}/Views"
            }
        },
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command.pickProcess}"
        }
    ]
}`

**Comment by isidorn** [comment]
The composite launch configuration was an experimental way of surfacing multi target debugging.
For now we have changed this approach to not require a special launch config but just by presisng launch a multiple number of times for each program -> you can try this out in the current insider release.

We will provide more reasoning in our next release notes.

![multidebug](https://cloud.githubusercontent.com/assets/1926584/20182651/c65199b6-a762-11e6-8e2a-b0f584966046.gif)
