### ISSUE TITLE
Kill Terminal using cmd-delete shortcut causes error

### ISSUE THREAD

**Issue by kenbankspeng** [microsoft/vscode#149689]
Issue Type: <b>Bug</b>

Reproduce
* create new terminal session
* select it in the terminal list and kill it using cmd-delete shortcut

Observed results:
* Terminal session terminated with error message displayed -  Illegal state: service accessor is only valid during the invocation of its target method

Expected results:
* No error message

Note:
* Error message does not occur when right-clicking on the terminal name in the list and selecting "Kill Terminal" from the popup menu.

VS Code version: Code 1.67.1 (Universal) (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id e06073d9-8a2c-444c-a18c-c3789a0a19ac|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/"needs-more-info"

**Comment by kenbankspeng** [comment]
Fixed indeed!
