### ISSUE TITLE
Markdown renderer does not unescape \. in a link

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14968]
According to
https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf
and
http://daringfireball.net/projects/markdown/syntax#backslash

\. should be used to escape a dot.

However, it looks like our hover renderer doesn't unescape the dot when in a link
![image](https://cloud.githubusercontent.com/assets/6461412/20001060/c705c6da-a27a-11e6-91ed-8a46fcd3821e.png)

**Comment by Sequoia** [comment]
Sorry to bother yall but is there an ETA on this? I'm hoping to release/publicize a project soon that relies heavily on json-schemas but I don't want to publicize it until this is fixed. Thanks 🐶

**Comment by mjbvz** [comment]
From a quick look, it the root cause may be the processing we do in the js extension for  package.jsons: https://github.com/Microsoft/vscode/blob/master/extensions/javascript/src/features/packageJSONContribution.ts#L216

@Sequoia Can you please share an example json file that shows this in the latest builds. Thanks.

**Comment by Sequoia** [comment]
Verifying bug on master, latest commit d167728610b75b5dbf9f744bbf5cf5cd90114f68

![screen shot 2016-12-06 at 3 41 49 pm](https://cloud.githubusercontent.com/assets/317498/20942709/9adf2862-bbca-11e6-8462-c4e68ead8c73.png)

See my original ticket for repro steps #12406

**Comment by dbaeumer** [comment]
Verified in code.

**Comment by aeschli** [comment]
I still see unescaped characters:
![image](https://cloud.githubusercontent.com/assets/6461412/21016803/4b0a3a90-bd67-11e6-870e-f66681a99b57.png)

I created #16936

**Comment by Sequoia** [comment]
Verified fix on master @ 0214d86253c0e1e9a2c7cf7776775693890ad179 👍  Thanks!
