### ISSUE TITLE
Executing run&debug via command palette

### ISSUE THREAD

**Issue by mataslib** [microsoft/vscode#149625]
I would like to be able to execute run&debug via command palette similarly as you can execute task (ctrl+shift+p > "Tasks: run task" > "foo task").

**Comment by gjsjohnmurray** [comment]
Did you try the commands `Debug: Select and Start Debugging` or `Debug: Start Debugging`?

**Comment by mataslib** [comment]
@gjsjohnmurray thank you very much 👍  `Debug: Select and Start Debugging` is exactly what I was looking for but somehow overlooked.
