### ISSUE TITLE
Integrated terminal keybindings don't work after adding new terminal

### ISSUE THREAD

**Issue by vladamx** [Microsoft/vscode#14969]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14931
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.0|
|vscode-node-readme|bengreenier|1.0.7|
|npm-intellisense|christian-kohler|0.1.4|
|path-intellisense|christian-kohler|1.1.0|
|regex|chrmarti|0.0.6|
|vscode-eslint|dbaeumer|1.0.8|
|vscode-npm-source|dkundel|0.0.3|
|githistory|donjayamanne|0.1.0|
|EditorConfig|EditorConfig|0.3.4|
|vscode-npm|fknop|3.3.0|
|bracketselection|guosong|0.0.1|
|output-colorizer|IBM|0.0.8|
|vscode-todo-parser|minhthai|1.8.3|
|vscode-exec-node|miramac|0.1.8|
|js-atom-grammar|ms-vscode|0.1.10|
|debugger-for-chrome|msjsdiag|2.2.0|
|fontsize-shortcuts|peterjuras|1.0.0|
|seti-icons|qinjia|0.1.3|
|view-in-browser|qinjia|0.0.3|
|vscode-paste-and-indent|Rubymaniac|0.0.6|
|code-settings-sync|Shan|2.3.6|
|searchdocsets-vscode|silverlakesoftware|0.5.2|
|change-case|wmaurer|1.0.0|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Add new integrated terminal
2. Try any terminal related keybindings before re-toggling terminal.

**Comment by Tyriar** [comment]
Can you go into a little more detail on:

- What do you mean by "Add new integrated terminal", are you referring to an extension here or a keybinding, if a keybinding which one?
- Do you have any errors in the dev tools console (Help > Toggle Developer Tools)?

**Comment by vladamx** [comment]
Sorry. 
More detailed explanation:
- Open up integrated terminal
- Set your own keybindings for focusNext/Previous, Kill etc... 
- Add new integrated terminal by hitting Ctrl+Shift+`
- Try focusNext/Previous or Kill terminal keybindings 
This will fail. Keybindings will recover only if you toggle the terminal.
P.S I'm not referring to any extension and Developer Tools show no error. 
Thanks.

**Comment by gigafied** [comment]
I can repro this as well on OSX. Shortcut for next/prev terminal works if you're on the first terminal, but after that prev/next shortcuts stop working.

**Comment by Tyriar** [comment]
@vladamx @gigafied do you have `terminal.integrated.commandsToSkipShell` set in your settings file?

**Comment by gigafied** [comment]
Nope, these are my shortcuts


````
[
    { "key": "cmd+y",           "command": "redo"},
    { "key": "cmd+shift+r",     "command": "npm-script.start"},
    { "key": "cmd+shift+t",     "command": "npm-script.test"},
    {
        "key": "cmd+k",
        "when": "terminalFocus",
        "command": "workbench.action.terminal.clear"
    },
    {
        "key": "cmd+n",
        "when": "terminalFocus",
        "command": "workbench.action.terminal.new"
    },
    {
        "key": "cmd+w",
        "when": "terminalFocus",
        "command": "workbench.action.terminal.kill"
    },
    {
        "key": "cmd+right",
        "when": "terminalFocus",
        "command": "workbench.action.terminal.focusNext"
    },
    {
        "key": "cmd+left",
        "when": "terminalFocus",
        "command": "workbench.action.terminal.focusPrevious"
    }
]
````

**Comment by Tyriar** [comment]
@gigafied `terminal.integrated.commandsToSkipShell` would be in your settings.json file

**Comment by gigafied** [comment]
Sorry, wasn't clear.... it's not in `settings.json`, I was just providing my shortcuts as well to hopefully provide a bit more info as to how to repro.
