### ISSUE TITLE
Crash when Batch replace

### ISSUE THREAD

**Issue by syj2010syj** [Microsoft/vscode#14967]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions: actboy168.lua-debug-0.0.11, formulahendry.code-runner-0.4.1, GuardRex.status-bar-tasks-0.1.0, naumovs.color-highlight-1.2.1

Steps to Reproduce:

1.Ctrl+Shift+H
2.select "regular match"
3.Replace "<(......):" to "<#(......):" (Just a sample)
4.Prompt me "Use "<#(......):" to replace 2048 in 58 files" (Not exactly because I use Chinese Language)
5.press OK then VSC crash

**Comment by sandy081** [comment]
@syj2010syj - Can you please try to reproduce by disabling all extensions. There is a command (Search for Disable all installed.. ) in the command pallette to disable all extensions.

**Comment by sandy081** [comment]
Closing this issue as there was no feedback
