### ISSUE TITLE
Only show folder name in  Windows Taskbar

### ISSUE THREAD

**Issue by NilsQuirmbach** [Microsoft/vscode#14963]
If the path in the windows taskbar gets too long it is hard to separate which folder is the selected one. It would help to shorten the path and reduce it to the last folder (see Screenshots)

![vs-code_before](https://cloud.githubusercontent.com/assets/22655797/19999024/613c3564-a270-11e6-95f9-ba5810c187e9.jpg)
![vs-code_after](https://cloud.githubusercontent.com/assets/22655797/19999026/650f8006-a270-11e6-9b56-319769ac5abe.jpg)

**Comment by bpasero** [comment]
I am now using the name of the folder as label instead of the full path. It seems the windows explorer is doing the same thing:

![image](https://cloud.githubusercontent.com/assets/900690/20012175/7815d2a2-a2ae-11e6-80ec-cbe847e28376.png)
