### ISSUE TITLE
Webview CSS: data-vscode-theme-name attribute changes when the language changes

### ISSUE THREAD

**Issue by pwang347** [microsoft/vscode#149661]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Write webview CSS depending on `data-vscode-theme-name`, e.g. see https://github.com/microsoft/vscode/issues/97663#issuecomment-630558320
2. Change the language by installing a language pack - the CSS will stop working

Would it be possible to use an ID instead of a name string for this attribute (e.g. a new attribute to prevent breaking changes), or perhaps to force this attribute to be English only?

**Comment by pingren** [comment]
@pwang347 @mjbvz 

I submitted a PR to address the issue. Please take a look when you have a moment.
