### ISSUE TITLE
Decorate .env.* files in the file explorer the same way as standard .env files

### ISSUE THREAD

**Issue by devuxer** [microsoft/vscode#149681]
I get that this is a really microscopic feature, but any chance we can get all .env.* files (like .env.development, env.production, .env.local, .env.local.development, etc.) to show the same cog wheel icon in the file explorer as files named .env? This would make them all appear like they belong together, and, well, it would look nicer (and not look like we named our file incorrectly).

![image](https://user-images.githubusercontent.com/1298521/168704887-cebe46f7-0722-4034-831a-d4a5842d8a82.png)

I suppose this is not currently done because .env is one of the few (only?) file extensions where the convention is to put it at the beginning rather than end (which I further suppose is a result of wanting them to alphabetize into a nice group).

**Comment by gjsjohnmurray** [comment]
Looks like a couple of years back the Docker extension authors went down a similar path and it wasn't entirely smooth.

https://github.com/microsoft/vscode-docker/pull/1908

**Comment by devuxer** [comment]
@gjsjohnmurray , Looks like it did ultimately get merged, though, right? And in this case, I don't think there's any special editor involved (.env files seem to be treated as plain text files).

**Comment by lramos15** [comment]
In the end I don't think they can do that without listing every possible .env we have this feature request actually which isn't easily implementable https://github.com/microsoft/vscode/issues/12493

**Comment by devuxer** [comment]
That issue is an interesting read. Perhaps just a list of the most common .env.* examples would be at least better than the status quo of *only* .env.
