### ISSUE TITLE
Dialog Verifying "Visual Studio Code.app" stuck

### ISSUE THREAD

**Issue by govindrai** [microsoft/vscode#149683]
Just updated visual studio code. The application is working fine. I have opened and quit multiple times but the verifying dialogue won't go away.

Version: 1.67.1 (Universal)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:16.526Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

Steps to Reproduce:

1. Update Visual Studio Code to 1.67.1

![Screen Shot 2022-05-16 at 6 07 02 PM](https://user-images.githubusercontent.com/13859249/168706908-e2a7f9a4-adb8-497b-9a24-cf48519e9667.png)

**Comment by dmtaub** [comment]
I had this issue as well. Workaround is to open "Activity Monitor" and force kill CoreServicesUIAgent

source: https://apple.stackexchange.com/questions/151571/what-is-the-verifying-xxx-app-dialog-and-how-do-i-get-passed-it

**Comment by JacksonKearl** [comment]
Doesn't appear to be anything we can do on our end. I recommend @dmtaub's suggestion

**Comment by mirogta** [comment]
I had the same issue and @dmtaub's suggestion has resolved it.

Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:43:24.900Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0
