### ISSUE TITLE
Multiple target debugging: Should be able to let targets depend on others

### ISSUE THREAD

**Issue by NCC1701M** [Microsoft/vscode#14960]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|debugger-for-chrome|msjsdiag|2.2.0|
|other extensions not|important for this issue|---|

---
When you configure multi target debugging you should be able to configure which configuration depends on others. When you configure to debug a **coreclr web** application and you want to debug also the javascript via **Debugger for chrome**, the **chrome** configuration should be started after the **coreclr** has started. Because otherwise the browser starts although there is no running web server.

Steps to Reproduce:

1. Setup a core and chrome launch configuration similar to this
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Launch Core",
			"type": "coreclr",
			"request": "launch",
			"preLaunchTask": "build",
			"program": "${workspaceRoot}\\bin\\Debug\\netcoreapp1.0\\MyWebApp.dll",
			"args": [],
			"cwd": "${workspaceRoot}",
			"stopAtEntry": false,
			"internalConsoleOptions": "openOnSessionStart",
			"env": {
				"ASPNETCORE_ENVIRONMENT": "Development"
			}
		},
		{
			"name": "Launch Chrome",
			"type": "chrome",
			"request": "launch",
			"url": "http://localhost:5000",
			"sourceMaps": true,
			"webRoot": "${workspaceRoot}/wwwroot"
		},
		{
			"name": "dotnet + chrome",
			"type": "composite",
			"request": "launch",
			"configurationNames": [
				"Launch Core",
				"Launch Chrome"
			]
		}
	]
}
```
2. Run "dotnet + chrome"
3. You will see that that browser starts although the core application is still compiling or starting

Expected behavior:
The chrome configuration should start after the dotnet app has compiled and started.

PS: Most of the times the browser doesn't even start. Then I get the message, that I should configure my launch.json see Bug #14964

**Comment by isidorn** [comment]
This is fixed in the vscode insider where you can manually launch one configuration after the other by pressing play multiple times. This will be in the december release ntoes
