### ISSUE TITLE
Attached pictures of the problem

### ISSUE THREAD

**Issue by itsdiego0o** [microsoft/vscode#149653]
![Diapositiva1](https://user-images.githubusercontent.com/105612018/168647139-db380182-1a2e-473d-b31e-ee0d3e7d02e2.PNG)
![Diapositiva2](https://user-images.githubusercontent.com/105612018/168647151-f8d92b9f-4969-407a-9465-63b78e812673.PNG)

**Comment by gjsjohnmurray** [comment]
@dbaeumer I guess this is for #149604

**Comment by MachineMitch21** [comment]
What is this showing?

**Comment by rzhao271** [comment]
Are you able to open the HTML file by first finding it in the file explorer, right clicking on it, and then choosing Open with > Edge? If yes, I wonder if the URL at the top appears different.

**Comment by dbaeumer** [comment]
From #149605 

> When pressing F5 to open my file in Chrome or Explorer, the page that had been working before remains blank, I need an urgent solution, I have been working on my school project and I need it.
Thank you for your time
