### ISSUE TITLE
JsDoc "@return {null | number}" hints only "@return number" in another file

### ISSUE THREAD

**Issue by MangoPomelo** [microsoft/vscode#149649]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Create a file named "a.js" with codes below:
```javascript
// @ts-check

/**
 * @param {number} a the first number
 * @param {number} b the second number
 * @return {number | null} return a divisible by b, or null if b equals 0
 */
export function divide(a, b) {
  if (b === 0) return null;
  return a / b;
}
```

2. It gives a correct hint in this scenario
![image](https://user-images.githubusercontent.com/40921434/168633417-21a757ba-b233-4b0d-8b89-6b0906a0c05b.png)

3. Create another file named "b.js" with the function imported
```javascript
// @ts-check

import { divide } from "./a";

divide(12, 0)
``` 

4. It gives a wrong hint that null disappears
![image](https://user-images.githubusercontent.com/40921434/168633587-64dc550b-7a5e-4395-84b1-d17353dba604.png)

**Comment by MangoPomelo** [comment]
Works fine with "void" though:
![image](https://user-images.githubusercontent.com/40921434/168635414-d3d0499c-eb26-45d3-9fbd-9010021f9c2b.png)

Is there any rule that null and undefined will be shadowed or something?

**Comment by mjbvz** [comment]
Try enabling strict null checking: https://www.typescriptlang.org/tsconfig#strictNullChecks
