### ISSUE TITLE
Debug console hyperlinks are not clickable

### ISSUE THREAD

**Issue by GordonSmith** [Microsoft/vscode#14961]
- VSCode Version: 1.7.1
- OS Version:  Windows 10

Steps to Reproduce:

1.   Output a hyperlink to the debug console
2.   Click on it

![image](https://cloud.githubusercontent.com/assets/966863/19998912/57c8c3ca-a267-11e6-8572-fa940fdfd22b.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/197
