### ISSUE TITLE
Emmet for jsx in js-file doesn't work anymore

### ISSUE THREAD

**Issue by perbergstrom12** [Microsoft/vscode#14962]
- VSCode Version: 1.71
- OS Version: Windows 10

Steps to Reproduce:

1. Open a .js file with language mode JavaScript React
2. type div and hit tab

**Comment by Maroon1** [comment]
I found tsx works well, but jsx doesn't work.

**Comment by mrmlnc** [comment]
Just a tip for those who will work on this issue: it is not related to Emmet.

VS Code defines the `JavaScript React` as `JavaScript`.

![image](https://cloud.githubusercontent.com/assets/7034281/20004898/0671e6ee-a2a0-11e6-8ee5-fd221142b463.png)

**Comment by alexandrudima** [comment]
To investigate: this most likely has the same root cause as #14661

**Comment by alexandrudima** [comment]
Same root cause as #14661

**Comment by alexandrudima** [comment]
To the verifier: Please see comment in #14661

**Comment by maximgatilin** [comment]
You can try this
```
"emmet.includeLanguages": {
    "javascript": "javascriptreact"
}
```
