### ISSUE TITLE
JSX auto quote style was changed to single quotes - should be double

### ISSUE THREAD

**Issue by distinctdan** [microsoft/vscode#149752]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: macOS Big Sur 11.6.6

Steps to Reproduce:

1. It looks like VSCode was recently change to default to single quotes for JSX attributes. Perhaps this was incorrectly linked to the setting for JavaScript or TypeScript quote style. This is incorrect, jsx attributes are a separate thing and should default to double quotes to match React's default style. They should be totally separate from the javascript or typescript quote setting. If you look at the React docs, they all use double quotes: https://reactjs.org/docs/components-and-props.html
2. Someone else brought this up and it looks like they were just ignored. This change is an annoying bug, could we please take another look at this? Here's the previous issue: https://github.com/microsoft/vscode/issues/143164

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by distinctdan** [comment]
Not sure, sorry, I'm not currently willing to be on the insiders build. However, it does reproduce in the current stable build with all extensions disabled.

**Comment by mjbvz** [comment]
Please provide example code and steps to reproduce the issue then

**Comment by distinctdan** [comment]
There are already examples in the issue I linked. Please read the first post in the thread: https://github.com/microsoft/vscode/issues/143164#issue-1139440441

**Comment by mjbvz** [comment]
See https://github.com/microsoft/vscode/issues/143164#issuecomment-1042113103. The default quote style is inferred from your existing code. We have not changed any defaults  AFAIK

If you want a new setting that is specific to JSX attributes, please [open a feature against TypeScript](https://github.com/microsoft/TypeScript/issues/new?assignees=&labels=&template=Feature_request.md&title=)

**Comment by distinctdan** [comment]
Well, from personal experience, it seems like this used to work correctly. Regardless, this is still a bug. VSCode with default settings is using double quotes for jsx. This is incorrect behavior. JSX should always default to double quotes because that's the preferred style for React. VSCode shouldn't be trying to infer anything from javascript because javascript strings are not the same as jsx attributes.
