### ISSUE TITLE
Traduction langue FR sous-menu incorrecte

### ISSUE THREAD

**Issue by olivMertens** [microsoft/vscode#149794]
Issue Type: <b>Bug</b>

Go to menu affichage >> apparence >> afficher la barre latérale secondaire
L'item indique ceci "  afficher la bar&re latérale secondaire" 
Un petit And & se balade
Have a nice day

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (17.62GB free)|
|Process Argv|--crash-reporter-id af34d290-01e2-4ba9-b8b4-99a361bad71f --crash-reporter-id af34d290-01e2-4ba9-b8b4-99a361bad71f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.20.5902
vscode-pull-request-github|Git|0.42.0
vscode-language-pack-fr|MS-|1.67.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30475216
vsclangdc:30486549
90j3a820:30491489

```

</details>

**Comment by sbatten** [comment]
@TylerLeonhardt I have the same comment in 275 places across the code base `['&& denotes a mnemonic']`

And this is the string `"Show Secondary Si&&de Bar"`

**Comment by TylerLeonhardt** [comment]
Best I can do is ask @cristianosuzuki77 for the string to be updated manually to ensure `&&` is not translated... but that won't prevent this from happening in the future due to human error.

better is using a locked comment like the one above...

could also have the `&&` be a runtime string instead...

but really we need language-aware mnemonics where the position of the `&&` changes based on the language but I'm not sure if there's a process for that. @cristianosuzuki77 do you know?

**Comment by sbatten** [comment]
so I add?
```
"{Locked='&&'}",
"Show Secondary Si&&de Bar"
```

what kind of enforcement does this do? does it just force that a mnemonic exists? its not really required that a translation contains a mnemonic even if the original does

**Comment by TylerLeonhardt** [comment]
I believe it forces that it exists, though @cristianosuzuki77 or @danyeh are experts here.

**Comment by TylerLeonhardt** [comment]
> what kind of enforcement does this do?

I know a little bit more... this _does_ basically "fail the string" until it meets the criteria of "there should be a `&&` somewhere in the string and a translator looks at this.

@sbatten did you get the chance to add this to the comments?
