### ISSUE TITLE
Allow file deletion without confirmation

### ISSUE THREAD

**Issue by charlie-amihan** [microsoft/vscode#149766]
Issue Type: <b>Feature Request</b>

The only settings toggle for file deletion confirmation is to suppress it when the recycle bin is being used.

You cannot use the recycle bin for file deletions when using Remote - WSL. Please allow me to delete files without confirmation.

Extension version: 0.66.2
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

**Comment by lramos15** [comment]
\duplicate #149771 please upvote that issue for us to consider it for our backlog 👍
