### ISSUE TITLE
Node Debugger occasionally will exit with code 3221225477 immediately after starting

### ISSUE THREAD

**Issue by hedgehog90** [microsoft/vscode#149708]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

This happens with a rather large and complex project that I'm working on & I can't provide the source files or a specific way to trigger the crash unfortunately.

It started happening in the last week or so, having not altered much of the code or modified any vs code settings.
I start the debugger and 50% of the time it will immediately exit with this code, with no caught or uncaught exceptions.
I have added trace:true to my launch configuration and it produced a log:

[vscode-debugadapter-d638d5c5.json.gz](https://github.com/microsoft/vscode/files/8707881/vscode-debugadapter-d638d5c5.json.gz)

Running the node process from command prompt does not appear to trigger the crash, only when it's run in VS Code with the nodejs debugger attached.

Any help would be appreciated.

EDIT: If I enable 'Caught Exceptions' or place a breakpoint at the entry point or anywhere close to the beginning of my script (triggering the debugger to pause), on continuing I avoid the crash.

EDIT: I've just been stripping a copy of my project down to find the root cause and it's tricky...
With the following script I can trigger the bug ~5% of the time I execute it:

```
const path = require('path');
console.log(1)
const express = require('express');
console.log(2)
const fs = require('fs-extra');
console.log(3)
const axios = require('axios').default;
console.log(4)
var utils = require("../lib/utils");
console.log(5)
setInterval(()=>{},1000)
```

And it'll trace: 
```
1
2
3
4
5
Process exited with code 3221225477
```

The utils file is just a simple script exporting some functions, but the only noteworthy detail about it is it's a symlink.
It appears to be executing the file successfully, then a moment later it'll exit.
However if I reduce the utils.js file to 'module.exports = {}' then I can't get it to crash.
Very odd!

FINAL EDIT:

The problem - bizarrely - appears to be connected to the length of utils.js... Symlink or not, doesn't matter.

https://gist.github.com/hedgehog90/e59318e3d9dc7220ed7c0c6817ac7428

If I delete a few of those functions (important to note none of them are being called), then the crash goes away.
And that also explains why the crash has only started happening recently, as the utils.js file has grown since.

FINAL FINAL EDIT:

The problem appears to be related to the last statements near the utils object closure...
Particularly these 2 functions:
```
		file_uri_to_path(uri) {
			if (typeof uri !== 'string' || uri.substring(0, 7) !== 'file://') {
				throw new TypeError('Must pass in a file:// URI to convert to a file path');
			}
			const rest = decodeURI(uri.substring(7));
			const firstSlash = rest.indexOf('/');
			let host = rest.substring(0, firstSlash);
			let path = rest.substring(firstSlash + 1);
			if (host === 'localhost') host = '';
			if (host) host = "//" + host;
			path = path.replace(/^(.+)\|/, '$1:');
			// path = path.replace(/\//g, '\\');
			// if not windows path...
			if (!/^.+:/.test(path)) {
				path = "/" + path;
			}
			return host + path;
		},
		try_file_uri_to_path(uri) {
			try {
				return utils.file_uri_to_path(uri);
			} catch (e) {
				return uri;
			}
		},
```

If I delete the last 2 functions (reducing the object to 123 keys/values) then I can stop the crash happening...
OR...
If I add a bunch of junk key/value pairs below:

```
utils = {
	<all my functions>,
	a:1,
	b:1,
	c:1,
	d1,
	e:1,
	f:1,
```

I found adding 1 or 2 key/value pairs below didn't help, but 3 or more - it never crashes when I run it now.

Try and make sense of that!

**Comment by connor4312** [comment]
Great investigative bug reporting! 😄 

Unfortunately I don't believe this bug is in VS Code, particularly with the symptoms you report. `3221225477` is an access violation (i.e. segfault) from native code, which indicates a bug in V8 or Node.js. The first thing I would do is try updating to the latest version of Node.js and see if it still happens. If so, I suggest using [`segfault-handler`](https://www.npmjs.com/package/segfault-handler) to get more information about the error. That should hopefully be useful to the Node.js folks to diagnose the issue. If all of the above turns out to be the case, I can help file an issue on Node or do so on your behalf.

**Comment by hedgehog90** [comment]
Updating to the latest version of node (18.2.0 64bit) fixes it.
Worth reiterating that if I run it in node 16.13.0 from command prompt it doesn't exit, it only occasionally exits when VS code is debugging.

**Comment by connor4312** [comment]
That makes sense, and it's fairly common to have a failure mode happen only under the debugger: both the act of debugging as well as tertiary information the debugger asks for invoke many more code paths than any given program is likely to.

Since this is fixed in the latest version of Node, it doesn't sound like there's any action for us. Regardless, thanks for the detailed report and follow up! 🙂
