### ISSUE TITLE
TypeScript syntax errors and auto complete not working

### ISSUE THREAD

**Issue by zurfluh** [Microsoft/vscode#14970]
With TypeScript versions 2.0.6 and 2.0.7 syntax errors and auto complete are not showing anymore. TypeScript versions 2.0.3 and 1.8 work. This issue appears when using either the workspace or the bundled TypeScript installation.

TypeScript compilation outside VS code works normal.

Occurs with the following configurations:
- TypeScript Version: 2.0.6-2.0.7
- VSCode Version: 1.6.1 - 1.7.1
- OS Version: Windows 8.1

tsconfig.json:
```
{
  "compilerOptions": {
    "noImplicitAny": false,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": false,
    "declaration": false,
    "noResolve": true,
    "target": "es5"
  }
}
```

Steps to Reproduce:

1. Install TypeScript version 2.0.6 or 2.0.7 in workspace, or use VS-code bundled (VS code 1.7.1)

**Comment by waderyan** [comment]
@zurfluh this is working for me. Can you share your workspace?

**Comment by zurfluh** [comment]
With the same code base but the following (changed) configuration, the issue does not appear:

- TypeScript 2.0.10
- VS Code 1.7.2
- Windows 10

I am closing the issue because (a) I am not able to access the above mentioned machine / configuration anymore, and (b) there has been no reports by other people.
