### ISSUE TITLE
window.experimental.titleMenu and window title

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#149783]
With that setting set, I am missing the "[Extension Development Host]" title on the window, which is helpful for identifying that special window. In general, I guess the whole `window.title` is missing - is there a plan to show that along with the menu? If not can we keep the [Extension Development Host] hint somewhere?

**Comment by jrieken** [comment]
Today it only shows on hover. I am open for suggestion but it isn't trivial as the static window title can be very long, is configurable. Maybe show the "special decorations", like [Extension Dev..] etc, in the title menu
