### ISSUE TITLE
"Show Quick Pick Options" wording could be improved

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#149743]
Hover over the down arrow in the title bar search -> "Show Quick Pick Options" shows up
Not convinced by the wording here, most new users might not know what is a quick pick. Instead I would have something like "Search Modes", or something more understandable. These are not really options imho

fyi @daviddossett @lychung7 for thoughts

![Screenshot 2022-05-17 at 19 39 00](https://user-images.githubusercontent.com/1926584/168876064-edb68a99-cfda-4c0e-9ba4-2bacdddaf0b7.png)

**Comment by jrieken** [comment]
"Show Search Modes..." is the winner
