### ISSUE TITLE
How to hide [•] indicator from the gutter?

### ISSUE THREAD

**Issue by derricck** [microsoft/vscode#149714]
I have searched a lot for how to disable/hide this thing and I couldn't find it, I also tried to search/replace in all vscode files `c5c5c`
(the background color of this thing) to the same color of the gutter, but this also didn't work, the color remains the same.

I'm talking about this above where the mouse hand is:
![AnyDesk_2022-05-17_10-40-22](https://user-images.githubusercontent.com/105561748/168824659-0aff5ca3-d9a7-4421-a583-6344809dd7bc.png)

What is the 'region' where this thing is called, I mean between the `5903` and the `[-]`?

If is not possible to hide this specific thing, disabling anything from this region or changing the background color as I tried, also helps.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether this is coming from one of your extensions.

**Comment by derricck** [comment]
@gjsjohnmurray yes its being caused by an extension, but I would like to hide or disable it, whats this region called? maybe there's an option to disable anything to be shown there?

**Comment by gjsjohnmurray** [comment]
Is #93887 relevant?

**Comment by gjsjohnmurray** [comment]
Though if you reduce your gutter width to zero I guess you may lose folding controls, change markers, etc.

Maybe better to get the extension author to make their gutter icon decorations optional.

**Comment by derricck** [comment]
I set it to 0 now it looks like this:
![Code_2022-05-17_13-23-52](https://user-images.githubusercontent.com/105561748/168861057-d89eadcd-c557-48ee-9f2e-01380da25047.png)

**Comment by ArturoDent** [comment]
That is the Comment add indicator. See, e.g., https://github.com/microsoft/vscode/issues/148048#issue-1214577506

@alexr00 will know if those are configurable.

**Comment by derricck** [comment]
```
editorCommentsWidget.rangeBackground, editorCommentsWidget.rangeBorder, editorCommentsWidget.rangeActiveBackground, editorCommentsWidget.rangeActiveBorder)
```
these options are not available yet?

**Comment by gjsjohnmurray** [comment]
These are available to [color theme](https://code.visualstudio.com/api/references/theme-color) authors, and to you for customization, e.g.

![image](https://user-images.githubusercontent.com/6726799/169105352-b5408e29-cfed-4b7d-aa65-748251c04112.png)

**Comment by derricck** [comment]
@gjsjohnmurray 

v1.67.1 i dont have these options in your picture
![AnyDesk_2022-05-18_15-58-37](https://user-images.githubusercontent.com/105561748/169133861-7cf7a07f-90fa-472f-9f2c-520e5c4cf7f4.png)
