### ISSUE TITLE
Set environment variable before starting a terminal

### ISSUE THREAD

**Issue by ffes** [Microsoft/vscode#14973]
- VSCode Version: 1.7.1
- OS Version: Win 10 Pro

Add an option to set environment variables before starting the terminal.
Something like:
```json
"terminal.integrated.envVars.windows": ["DEBUG=1", "LANG=C"],
```
Or maybe you want to split variable and value something like:
```json
"terminal.integrated.envVars.windows": {
    "DEBUG": "1",
    "LANG": "C"
}
```

Obviously the same goes for Linux and Mac

**Comment by Tyriar** [comment]
I'm curious what your use case is for wanting this in VS Code but not in Windows?

**Comment by ffes** [comment]
Here are some use cases (first two from personal experience):

* Different paths to libs per workbench
* Test your application with different languages/translations.
* It would also have made a much better work-around for #13834

You just don't want to set set the right vars every time you open a terminal.

**Comment by pandasjw** [comment]
![image](https://cloud.githubusercontent.com/assets/11087172/20354016/bd0dd5b4-ac57-11e6-8ec3-91d63eac8aee.png)

how should i fix this problem @ffes

**Comment by ffes** [comment]
@pandasjw If you are asking because I mentioned #13834 in my previous comment, I have no idea about that issue. That one is not my bug report.

I just ran into that issue when I was searching around if the request I wanted to submit was not a dup.

**Comment by dannystaple** [comment]
Its not hard to see in the Python context an app needing a specific PYTHON_PATH. My thoughts here is that the tasks may be the workaround  - a task can have associated env vars - and a make/rake/grunt/gulp/fabfile or something could be used to set it all up for your project.

**Comment by farfromrefug** [comment]
I would love to see that too. For me it's about setting workspace env variables to be used with node gyp. Like OPENCV location

**Comment by rfgamaral** [comment]
How does one configure this on the Insiders build?

**Comment by Tyriar** [comment]
It will be in the next build of Insiders, you will be able to use the new settings:

```
terminal.integrated.env.linux
terminal.integrated.env.osx
terminal.integrated.env.windows
```

**Comment by marekr** [comment]
There's some interesting case sensitivity for the environment variables on Windows.

  "terminal.integrated.env.windows": {
    "Path" : "blah"
  }


in the powershell:

$Env:Path will print "blah" and so will $Env:PATH


If you make it

{
  "typescript.tsdk": "./node_modules/typescript/lib",
  "terminal.integrated.env.windows": {
    "PATH" : "${workspaceRoot}"
  }
}

Then it'll fail to override path altogether....

**Comment by farfromrefug** [comment]
I can confirm that it works great for me, i now use it in almost all my projects
Thanks!

**Comment by robmuh** [comment]
Is there any way to make this project specific? I am using this now for GOPATH but would love if it changed to the current working directory, which the integrated terminal seems to be aware of when it starts up. Maybe there is a variable I could set the envs to that contains the same value used by the starting terminal.

**Comment by ramya-rao-a** [comment]
@robmuh Anything in `.vscode/settings.json` is already specific to the root folder that is open in VS Code. This is called the Workspace settings.

**Comment by Mistobaan** [comment]
how to specify the GOPATH env variable inside the integrated terminal to be the same as the one inside your `.vscode/settings.json` ?
I am trying this on 1.17.1 and does not seem to work:
```json
    "go.gopath": "$HOME/gopath",
    "terminal.integrated.env.osx": {
        "GOPATH": "$HOME/gopath"
    },
```

**Comment by robmuh** [comment]
Thanks @Mistobaan but in my case the following is what I'm after, but doesn't seem to be working. the `go.gopath` use of the variable seems to work because it stops the underlined errors in code related to gopath, but the env var on the terminal still is bork. I'm mostly good because I also setup an install task that works. Now if I could only get that to `buildOnSave` like the libraries do correctly.

![screen shot 2017-10-12 at 9 45 39 pm](https://user-images.githubusercontent.com/3749067/31526774-fbed50be-af96-11e7-913c-df25cc911cf2.png)

**Comment by ramya-rao-a** [comment]
@Mistobaan @robmuh  You are using `$workspaceRoot` in the env var for the `terminal.integrated.env.osx` which doesnt get resolved. 

@Tyriar Should we add resolution of such variables when using the `terminal.integrated.env.*` setting?

@robmuh For `workspaceFolder` vs ` workspaceRoot` see https://code.visualstudio.com/updates/v1_17#_workspacefolder-in-launchjson-and-tasksjson

**Comment by Tyriar** [comment]
Resolving variables in the setting is tracked in https://github.com/Microsoft/vscode/issues/34337

**Comment by rucciva** [comment]
After upgrading from 1.17 to 1.18, the setting doesn't work anymore (OS Version: OSX High Sierra)

version 1.18:
<img width="1064" alt="screen shot 2017-11-15 at 10 12 25" src="https://user-images.githubusercontent.com/4647473/32816981-0bc7406e-c9ee-11e7-856e-ee709286c935.png">


version 1.17:
<img width="442" alt="screen shot 2017-11-15 at 10 16 13" src="https://user-images.githubusercontent.com/4647473/32816989-1f12f988-c9ee-11e7-8ffe-ca16bfa42e1a.png">

**Comment by ramya-rao-a** [comment]
Just tried on my Mac, it works as expected.
One thing to keep in mind is that the env vars will not affect terminals that were created before the env vars were added to the setting.
Can you create a new terminal and check there?

**Comment by rucciva** [comment]
it was indeed on a new terminal after the env was added. I've retried it on two high sierra machines recently.

**Comment by ramya-rao-a** [comment]
I tried on a co-worker's high sierra machine. Works there as well.

Can you try on our Insiders? https://code.visualstudio.com/insiders
Can you try with extensions disabled?
