### ISSUE TITLE
VS Code freezes upon Adding Folder to Workspace

### ISSUE THREAD

**Issue by steven-chau** [microsoft/vscode#149788]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.1
- OS Version: Linux x64 5.4.0-110-generic snap

Steps to Reproduce:

1. Select File.
2. Click "Add Folder to Workspace ..."
3. VS Code freezes up.

20-second video clip: https://webmshare.com/play/5Kq8n

About my VS Code:
```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:39:22.915Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.4.0-110-generic snap
```

**Comment by gjsjohnmurray** [comment]
Does this also happen when you use the `Open Folder...` option from that menu?

**Comment by steven-chau** [comment]
> Does this also happen when you use the Open Folder... option from that menu?

Yes. Actually it happens with all of the following:
* Open Folder
* Open File
* Open Workspace from file

**Comment by steven-chau** [comment]
My OS Version:

![image](https://user-images.githubusercontent.com/16594679/169603010-d1e6a39b-78f2-4e33-90c5-10b07399c5ae.png)

**Comment by steven-chau** [comment]
This video shows that Atom is able to open files/folders on my Ubuntu while VS Code can't:
- https://webmshare.com/play/zOA9P

**Comment by steven-chau** [comment]
After downgrading to the version below, I became able to open files again.

```
Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:39:46.686Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-113-generic snap
```

https://webmshare.com/play/6e0JB

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146584
