### ISSUE TITLE
[css]Error messages will not disappear after the css code in <style> tag is deleted

### ISSUE THREAD

**Issue by Reedo0910** [Microsoft/vscode#14972]
- VSCode Version:1.7.1
- OS Version:Windows 10 x64

Steps to Reproduce:

1. Write something wrong in <style> tag in HTML file, error messages appear.
2. Delete the whole line or whole block of the code
3. Error messages (even color decorators) still exist.
(Error messages won't disappear even the file has been deleted)
![bug](https://cloud.githubusercontent.com/assets/19267441/20001664/3d682588-a2b8-11e6-8169-b56a02cd8ea2.PNG)

**Comment by Tekbr** [comment]
I have the same problem in version 1.8.0 - insider (dbf3ba7) in Windows 10.

**Comment by Tekbr** [comment]
@Reedo0910 It seems that the error no longer happens to the insider version 1.8.0 - insider (37532db) 2016-11-08T07:11:24.659Z

@aeschli  Any fix for version 1.7.1?

**Comment by aeschli** [comment]
I didn't make any fixes yet, so I guess it still is around in 1.8.0

**Comment by aeschli** [comment]
This got fixed for the January build.
