### ISSUE TITLE
CSS: aspect-ratio should no longer be considered experimental

### ISSUE THREAD

**Issue by Keyacom** [microsoft/vscode#149733]
According to the [MDN page about the CSS `aspect-ratio` property](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio), it is no longer considered experimental, but this has been overlooked in code suggestions in VSCode.
![obraz](https://user-images.githubusercontent.com/70766223/168862468-c6405037-dc0b-4072-9466-b4c5810d64b0.png)

**Comment by aeschli** [comment]
We get the data from the mdn-data node module where the property is still marked as experimental:
https://github.com/mdn/data/blob/7ad63b7a52b16415e9a67af700a0006300b69b7b/css/properties.json#L1995

**Comment by aeschli** [comment]
Created https://github.com/mdn/data/issues/582 as upstream issue.
