### ISSUE TITLE
The name ... is not valid as a file or folder name.

### ISSUE THREAD

**Issue by beebase** [microsoft/vscode#149707]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.1
- OS Version: Windows11 10.0.222000

Steps to Reproduce:

1. trying to create a typescript file
2. I get an error popup the moment I enter a "."
Why am I getting an error for every file name I come up with ??

![image](https://user-images.githubusercontent.com/446089/168802140-00560cf9-3944-465d-b1fd-f47876557554.png)

**Comment by Moatezz** [comment]
Having them same problem with bascially every file I create. any updates?

**Comment by shashank-afk** [comment]
anyone found a fix?

**Comment by windson** [comment]
same with me

**Comment by windson** [comment]
@Iramos15
https://user-images.githubusercontent.com/1826682/195385236-d31a3822-fb4f-4447-ada6-0585ff932ca2.mp4

**Comment by windson** [comment]
![Recording 2022-10-12 at 21 06 29](https://user-images.githubusercontent.com/1826682/195386690-2fe6025e-7063-4e69-b062-9d6daafb9cdb.gif)


> Can someone send me a gif? I don't see an issue on my end. You cannot end a file with a dot so it shows an error when you enter `test.` but if you enter `test.ts` that should work

**Comment by lramos15** [comment]
@windson Can you try launching with no extensions? `code --disable-extensions` via the CLI to see if that helps at all

**Comment by windson** [comment]
It's still the same.

**Comment by lramos15** [comment]
Nobody on the team can seem to reproduce this. Do you have a non standard file system setup?

**Comment by windson** [comment]
No. I haven't any non-standard file system.
It's brand new PC and this is the build
![image](https://user-images.githubusercontent.com/1826682/195649679-9aa9a6e8-0133-4f51-99f6-8e5ff42cbfaa.png)

**Comment by lramos15** [comment]
@windson Do you use any language inputs besides english?

**Comment by windson** [comment]
There are the list of extensions I have with VS Code
![image](https://user-images.githubusercontent.com/1826682/195661062-fbbc9729-4dca-4cb9-a95b-3794332f2cf9.png)

**Comment by lramos15** [comment]
Could you try our insiders version of VS Code? https://code.visualstudio.com/insiders/ 

Sorry, I'm a bit at a loss at the moment as it seems like this is a sporadic issue for a very small set of users

**Comment by windson** [comment]
Still the same with insiders version.
![Recording 2022-10-13 at 22 47 46](https://user-images.githubusercontent.com/1826682/195663286-c5bd1ab4-3c57-40dd-bc10-17a8ac27ff15.gif)

**Comment by At-Sky** [comment]
have the same porblem as well

**Comment by lramos15** [comment]
Ok, after some investigation these are all expected cases. Best way to test if it's a VS Code bug is to try and create the file in the native Windows Explorer if it doesn't tell you it's an invalid file but VS Code does, feel free to come here and comment that use case.

@beebase Your issue is that the file cannot end with a `.`
@windson Your issue is that `con` is a reserved windows file name.

**Comment by IhabSan** [comment]
Have you find the solution for this problem?
I have the same here!

**Comment by lramos15** [comment]
@IhabSan Please send a gif of your issue
