### ISSUE TITLE
title bar hover is too far to the right

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#149764]
Does this issue occur when all extensions are disabled?: Yes/No
Vërsïøñ: 1.68.0-insider (Universal)
Çømmït: 5f3e9c120a4407de3e55465588ce788618526eb0
Ðætë: 2022-05-17T05:18:39.842Z
Ëlëçtrøñ: 17.4.3
Çhrømïµm: 98.0.4758.141
Ñøðë.js: 16.13.0
V8: 9.8.177.13-electron.0
Ø§: Darwin arm64 21.4.0

Hover over the `v`
![Screen Shot 2022-05-17 at 1 00 10 PM](https://user-images.githubusercontent.com/2644648/168899787-a6e65ffa-f0a2-4703-962f-0266747fe558.png)

**Comment by gjsjohnmurray** [comment]
Maybe #149741 if you're Zoomed in.
