### ISSUE TITLE
Links in banner bar do not use the pointer cursor

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#149736]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.66.2
- OS Version: Web

Steps to Reproduce:

1. Have a banner set up with a link in it.
2. Mousing over the link still uses the arrow cursor, rather than switching to the pointer which is more commonly associated with links.

**Comment by dbaeumer** [comment]
@a-stewart can you please provide a screen shot. Which banner do you mean?
