### ISSUE TITLE
Title bar element hover off when zoomed

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#149741]
1. Zoom in
2. Hover over some title bar element (the search down arrow for example)
3. Notice hover is way off 🐛 

![Screenshot 2022-05-17 at 19 37 26](https://user-images.githubusercontent.com/1926584/168875923-189ec781-c913-4b32-917b-c7da98bdc9f1.png)

**Comment by sbatten** [comment]
This is tricky @jrieken. what's happening is the titlebar is counter-zoomed and therefore the pixel math is wrong when calculating the position of the context view for the hover. we had a similar problem with the native menu dropdown for the layout controls. a similar fix is probably needed for this:

https://github.com/microsoft/vscode/blob/78914e7dd3fcc695131a9c63666a3c63f5634116/src/vs/workbench/services/contextmenu/electron-sandbox/contextmenuService.ts#L104-L116

**Comment by jrieken** [comment]
This might involve @Tyriar for the hover service and its positioning

**Comment by Tyriar** [comment]
The standard way to use the hover service is by passing in a target element:

https://github.com/microsoft/vscode/blob/b984f039b56b0f965deb7fc85c741e41885add8f/src/vs/workbench/services/hover/browser/hover.ts#L53-L59

I'm guessing this is probably using absolute positioning instead so the workaround would be entirely outside the hover service:

https://github.com/microsoft/vscode/blob/b984f039b56b0f965deb7fc85c741e41885add8f/src/vs/workbench/services/hover/browser/hover.ts#L159-L169

**Comment by jrieken** [comment]
In fact it uses the element via [setupCustomHover](https://github.com/microsoft/vscode/blob/32cd2a6dfba0102d91c1bb285863ab61931c89f1/src/vs/base/browser/ui/iconLabel/iconLabelHover.ts#L145). Do you use the context view service further down?

**Comment by jrieken** [comment]
@Tyriar I figured that the hover service invoked the context view service with the wrong coordinates, e.g the hover widget is created for a dom element for which is computes coordinates which are passed down to the context view. Calling [`getBoundingClientRect`](https://github.com/microsoft/vscode/blob/d9e4815f6137f3cb2414874b757b9bbec484ea07/src/vs/workbench/services/hover/browser/hoverWidget.ts#L233) seems to already return the wrong values...

**Comment by jrieken** [comment]
Thanks @sbatten
