### ISSUE TITLE
editor.padding.top causes minimap inaccuracy

### ISSUE THREAD

**Issue by Jornexe** [microsoft/vscode#149753]
Issue Type: <b>Bug</b>

Higher padding causes higher inaccuracy.
More visible on longer pages.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by dbaeumer** [comment]
I checked that the padding and the minimap shows the same proportional padding
