### ISSUE TITLE
contributes.authentication in package.json file

### ISSUE THREAD

**Issue by AINASIR** [microsoft/vscode#149810]
I am writing this issue to make a request for a proper documention on working of contributes.authentication API. Somehow, this API is appearing on my VS Code but I do not know how it actually works. 

I may want to use this feature to write my authentication details in package.json file so that I am automatically connected to Jira custom site using Atlassian VS Code extension. I will higly appreciate any kind of help.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode-extension-samples/tree/main/authenticationprovider-sample for an example.

I agree that better documentation is needed.

/assign @TylerLeonhardt

**Comment by AINASIR** [comment]
Thank you so much @gjsjohnmurray

**Comment by AINASIR** [comment]
However, @gjsjohnmurray , What I am talking about here is contributes.authentication API for package.json file. I have already been using contributes.configurationDefaults API but I am not sure how to implement contributes.authentication as there is no proper documentation. Kindly see the link for reference:

[https://code.visualstudio.com/api/references/contribution-points](url)

**Comment by gjsjohnmurray** [comment]
When I search the page at https://code.visualstudio.com/api/references/contribution-points I don't find any matches for `authentication`

**Comment by gjsjohnmurray** [comment]
Extensions that implement an authentication provider don't declare this in the `contributes` section of their package.json. They **do** probably use the `onAuthenticationRequest` activation event.

**Comment by AINASIR** [comment]
It is appearing in my list

![image](https://user-images.githubusercontent.com/101951230/169048045-d599065f-46a5-4272-ba6a-8b676fdcd234.png)

**Comment by gjsjohnmurray** [comment]
@AINASIR now I see what you mean.

This code defines the contribution point and the schema for its contents:

https://github.com/microsoft/vscode/blob/ca280a1685a34207a8bcf4826f8294d824b3caf7/src/vs/workbench/services/authentication/browser/authenticationService.ts#L141-L163

Here's how the built-in GitHub Authentication extension uses it:

https://github.com/microsoft/vscode/blob/ca280a1685a34207a8bcf4826f8294d824b3caf7/extensions/github-authentication/package.json#L30-L40

The built-in Microsoft Authentication extension does similar, but for only one provider:

https://github.com/microsoft/vscode/blob/ca280a1685a34207a8bcf4826f8294d824b3caf7/extensions/microsoft-authentication/package.json#L31-L38

@TylerLeonhardt should the sample be doing similar in https://github.com/microsoft/vscode-extension-samples/blob/main/authenticationprovider-sample/package.json ? Does anything in VS Code yet make use of such declarations by extension of the authentication provider id(s) they contribute?

**Comment by gjsjohnmurray** [comment]
Partial answer to my own question. By declaring its authentication contributions these get listed in the Feature Contributions tab of the Extension's tab, e.g

![image](https://user-images.githubusercontent.com/6726799/169107462-9f6abeff-76dc-40c6-9bd8-cedd289f1fef.png)

Otherwise they are only visible there as suffixes to `onAuthenticationRequest:` activation events.

**Comment by AINASIR** [comment]
Thank you so much for the valuable information :)

**Comment by KamasamaK** [comment]
The docs issue corresponding to this is microsoft/vscode-docs#5230.
