### ISSUE TITLE
Ability to open folders on VSCode for Browsers on Android

### ISSUE THREAD

**Issue by linsaftw** [microsoft/vscode#149899]
It is not possible to open folders with VSCode when using it on Android from the browser. Add the ability to do this to compile stuff directly with Termux and control the repo via it.

**Comment by joaomoreno** [comment]
Do you mean vscode.dev? The browser you're using on Android probably doesn't support the Web File System API necessary for that feature to work.

**Comment by joaomoreno** [comment]
Here's the current compatibility by MDN: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility

**Comment by linsaftw** [comment]
> Here's the current compatibility by MDN: https://developer.mozilla.org/en-US/docs/Web/API/File_System_Access_API#browser_compatibility

How about brave? Isn't it a fork of chrome?

**Comment by joaomoreno** [comment]
I don't know. But it's a browser we don't officially support, so we can't help much here. Hopefully the adoption of this web API will move faster and catch up with Brave.

**Comment by linsaftw** [comment]
Okay thanks. I will talk to Brave Browser developers.
