### ISSUE TITLE
Allow to expand truncated source field in error notification

### ISSUE THREAD

**Issue by clocky** [microsoft/vscode#149840]
Does this issue occur when all extensions are disabled?: Yes/No (Didn't check, but it doesn't seem extension related).

- VS Code Version: 1.67.1
- OS Version: macOS 12.3.1

Steps to Reproduce:

1. Open up a Python file, with a missing formatter.
2. An error dialog appears offering alternate formatters.
3. The source of the error, "Source: Python (..." is truncated and cannot be expanded.
In this instance, I'm assuming it's telling me which version of Python on my machine is throwing the error, but I can't tell.

Expected behaviour:

1. The dialog outside of the buttons/actons has hover states and a click state, and even changes cursor to the "hand" icon to suggest some sort of interaction - I found myself clicking on it hoping it would expand and show the complete source string.

<img width="496" alt="image" src="https://user-images.githubusercontent.com/1550587/169101772-57bd35af-e4da-4380-a6cb-2b654530b0de.png">

(Ping for @daviddossett and @misolori 😉 )

**Comment by daviddossett** [comment]
Working on gardening leave, @clocky? 😉

This is always a challenge when notifications use lots of buttons. But even so the inline treatment makes this all but inevitable. FWIW you can hover to view the whole string in lieu of a better solution.

<img width="331" alt="CleanShot 2022-05-19 at 10 03 38@2x" src="https://user-images.githubusercontent.com/25163139/169357370-c9ab88d5-aaf4-42e3-bf3e-f4118ff93d1c.png">

Not sure where this could be relocated to have more horizontal room in the current notification design. The obvious risk here is adding a bunch of vertical height to each notification. It's worth exploring at some point though.

**Comment by clocky** [comment]
(I'll have you know I'm officially between jobs, like an actor. 🕶)

The main thing with the current approach is that there's an affordance with the mouseover state that _something_ should happen if you click on the notification, but nothing does. My assumption (read: hope) was that it was going to expand the notification vertically. Something like the below:

Default state:
![Untitled-2022-05-16-1335-4](https://user-images.githubusercontent.com/1550587/169371191-3c104441-9c6f-43fb-96e1-34ffde16f5ed.png)

Expanded state:
![Untitled-2022-05-16-1335-3](https://user-images.githubusercontent.com/1550587/169371198-e2254936-76dc-4d38-9488-20eea0828710.png)

I agree the tooltip unblocks this specific scenario I was having though.
