### ISSUE TITLE
Improving the UI for "step in targets"

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#149871]
On my plate is @hediet's [Debugger: Smart Step Into](https://github.com/microsoft/vscode/issues/123879) issue. We already support this in DAP via the [step in targets](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_StepInTargets), but the UI in VS Code could use some polish.

Today, step in targets is only surfaced through a context menu actions that are available when paused and `supportsStepInTargetsRequest` is true:

![image](https://user-images.githubusercontent.com/2230985/169168835-1091019b-5048-409d-ab98-19e7eea01f91.png)

The result of this is a context menu, which allows the user to select one of the targets by their `label`

![image](https://user-images.githubusercontent.com/2230985/169168873-f8c27264-c846-4e7e-b01a-5f0d22a6003f.png)

---

I suggest the following:

1. Add the command to the ~command palette~ (**added in https://github.com/microsoft/vscode/pull/152131**) and Debug toolbar. This is our "step in" icon 
![image](https://user-images.githubusercontent.com/2230985/169168942-325e089e-8a6d-4b8d-989c-e174e787186a.png)

     Maybe an icon like this would work:
     
     ![image](https://user-images.githubusercontent.com/2230985/169169339-84ca2915-89d7-4a50-9664-3c6c98937dbd.png)

     Alternatively we could use a dropdown button, but I'm not the biggest fan of throwing those around everywhere, especially for actions the user may want to repeat frequently.

1. Allow for the step in range to be correlated with a position on the line. Currently the [StepInTarget](https://microsoft.github.io/debug-adapter-protocol/specification#Types_StepInTarget) only has a label. We could match that as text to contents of the line, but this wouldn't work if there's repetitive content like `find` in `find(arr1, a => find(arr2, a => a == b)`

    Therefore, I suggest (and will if we agree on a direction!) making a proposal to add an option `line`, `column`, `endLine`, and `endColumn` options to the `StepInTarget` akin to the `GoToTarget`. **Proposed in https://github.com/microsoft/debug-adapter-protocol/issues/274**

1. ~With that change, we can now have commands to step into the target in the current cursor position. When the "step in targets" command/button is executed, it can open quickpick. As items in the quickpick are focused, the editor reveals and selects the document range that the target refers to.~  (**added in https://github.com/microsoft/vscode/pull/152131**)

**Comment by roblourens** [comment]
Makes sense to me 👍

**Comment by weinand** [comment]
@connor4312 yes, I was thinking of your option 2 when working on the DAP proposal initially. Ideally the cursor position would determine the target for the "step in". May be it is not even necessary to have a new "step in" action in the toolbar: if the cursor is in a valid "step-in-target" range, then VS Code will automatically use "step in target" instead of "step in". 

Since I didn't want to add additional "position" properties to the DAP request, I decided to start simple and add more properties when needed.

**Comment by roblourens** [comment]
> May be it is not even necessary to have a new "step in targets" action in the toolbar: if the cursor is in a valid "step-in-target" range, then VS Code will automatically use "step in target" instead of "step in".

I wouldn't want to trigger it on accident. Especially tricky since we move the cursor to the paused location as you step.

**Comment by weinand** [comment]
@roblourens @connor4312 you both have convinced me that a "step in targets" only based on caret position is too much magic and might be confusing.
So let's go with the separate command first and explore shortcuts like `alt`-clicking later.

**Comment by hediet** [comment]
Is this supported for JS already?

I would have expected to see "inner" there:

![image](https://user-images.githubusercontent.com/2931520/176399644-f7f24ed0-8d49-4218-80ac-611041bda92d.png)

**Comment by connor4312** [comment]
Yes, it's supported. We exclude the location you're _currently_ paused at, though we could special case that to just do an ordinary "step in". I'll make an issue for it.

**Comment by hediet** [comment]
> We exclude the location you're currently paused at, though we could special case that to just do an ordinary "step in". I'll make an issue for it.

Not sure I follow. *Step in* here would step into "bar", no? What I actually want and cannot do with the normal "Step in", is to step into "inner" (which I should have called "outer" btw).

**Comment by connor4312** [comment]
Agreed 🙂  Some polish next iteration I think
