### ISSUE TITLE
Sourcemap files in subfolders are ignored

### ISSUE THREAD

**Issue by lumaxis** [Microsoft/vscode#14988]
- VSCode Version: Version 1.8.0-insider (dbf3ba74e6cf3b33687b7d47e321e642fc1e7562)
- OS Version: macOS 10.12.1

I'm trying to add debugging support to one of our Node projects but VS Code is having trouble finding the sourcemaps of `.js` files that are located in subfolders of my `dist` directory. The `dist` directory mirrors the hierarchy structure of my `src` directory.

This is what my `gulp` task looks like:
```javascript
gulp.task('build-ts', function () {
  let tsResult = gulp.src(['src/**/*.ts', 'typings/**/*.d.ts'])
    .pipe(sourcemaps.init())
    .pipe(tsProject());

  return tsResult.js
    .pipe(sourcemaps.write())
    .pipe(gulp.dest('dist'));
});
```

And this is my `launch.json`:
```json
{
  "name": "Launch Program",
  "type": "node",
  "console": "integratedTerminal",
  "request": "launch",
  "program": "${workspaceRoot}/src/index.ts",
  "cwd": "${workspaceRoot}",
  "runtimeArgs": [
    "--nolazy"
  ],
  "args": [
    "login"
  ],
  "outFiles": ["${workspaceRoot}/dist/**/*.js"],
  "sourceMaps": true,
  "preLaunchTask": "build"
}
```

While I can easily set a breakpoint in my `src/index.ts` file, everything that is in a file that is not in the root directory of `src` or `dist` respectively does not work. Am I using `outFiles` wrong?
My problem feels kind of similar to https://github.com/Microsoft/vscode/issues/13499 but none of the suggested solutions there solved my issue.
Is there anything I can provide to help diagnose/troubleshoot this? Thanks!

**Comment by weinand** [comment]
@lumaxis
- make sure that all generated JavaScript files live in the locations specified by the "outFiles" glob patterns (the source maps don't have to live there).
- verify that the 'sourceMappingURL' path at the end of the generated JavaScript files points to the source map.
- verify that the paths in the source maps are pointing to the source files.

I suspect that the last item is the source of your problem. The paths in the source map are correct for 'src/index.ts' but not for other locations.

**Comment by lumaxis** [comment]
Looks like you were indeed right!
Adding `{ includeContent:false, sourceRoot: '.' }` so it becomes `.pipe(sourcemaps.write('.', { includeContent:false, sourceRoot: '.' }))` did the trick 🙌 
Thank you!

**Comment by weinand** [comment]
@lumaxis I'm glad to hear that you were able to solve this problem.
