### ISSUE TITLE
 launch config args are prevented expanison due to some characters are escaped

### ISSUE THREAD

**Issue by AlvinLaiPro** [microsoft/vscode#149888]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: macOS Monterey

Steps to Reproduce:
```json
"type": "node",
"request": "launch",
"name": "Launch Program",
"program": "${workspaceFolder}/runner.js",
"console": "integratedTerminal",
"env": {},
"args": [
   "run",
"--config",
".testringrc.js",
"--tests",
"./tests-src/{SW,MW,AW}/P?/{WEB-230,}/*.js",
 "--rc.run-number",
 "5",
 "--rc.chrome-extension",
 "false",
"--bail",
```
When I launch the program, VScode will escape the asterisk with the preceding config which will cause this parameter to be omitted.
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/19744126/169191830-3c29b5e0-b786-42f4-ae42-06d04e504e65.png">

I expected the bash shell to expand the file path with `./tests-src/SW/P1/WEB-230/web230.js` but it was disabled when VScode escaped the parameter.

**Comment by roblourens** [comment]
Can discuss in https://github.com/microsoft/vscode/issues/149910
