### ISSUE TITLE
"View> Toggle Menu Bar"  Stopped working VSCode 1.8.0

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#14987]
- VSCode Version: 1.8.0 - insider (dbf3ba7)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

The menu bar is not disabling, when we click. I have deactivated all extensions and the problem continues.

![gif4](https://cloud.githubusercontent.com/assets/19866231/20009824/0d8bcf3e-a28d-11e6-84e1-e196f8fbbdeb.gif)

**Comment by bpasero** [comment]
I suspect the IPC work.

**Comment by joaomoreno** [comment]
Great catch!
