### ISSUE TITLE
Show checkmarks in top level menu to indicate activity of a toggle

### ISSUE THREAD

**Issue by Tekbr** [microsoft/vscode#14986]
- VSCode Version: 1.8.0 - insider (dbf3ba7)
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Place a check in some menu to see if it is active or not. Similar to the Auto Save File> Auto Save

Mainly for options that do not change the text in the menu.

Example: Toggle Word Wrap, Toggle Render WhiteSpace, Toggle Full Screen, Toggle Developer Tools, among others.

![1](https://cloud.githubusercontent.com/assets/19866231/20008485/ee7ea058-a287-11e6-8a01-874d718a8a27.jpg)

**Comment by isidorn** [comment]
I like this idea since for consistency.
Here is a [code pointer](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/menus.ts#L544)
You can see how the 'auto save' option is added. And you should be able to read from the configuration service the current settings of word wrap, full sreen etc...

fyi @bpasero

**Comment by bpasero** [comment]
The only reason our menu is not more dynamic is because it lives on the main side whereas many of the commands execute on the renderer side and thus would need to send back to the main side that the state changed. Not an easy area for a PR I fear.

**Comment by misolori** [comment]
Verified that the checks show up when toggled, also found a bug with toggling word wrap (filed #62307)

**Comment by misolori** [comment]
Actually, I've found inconsistent behavior with all of the toggle items under Appearance, re-opening.

**Comment by bpasero** [comment]
Some UX feedback (@misolori): I think we should not mix "Toggle..." and showing a checkmark. Either it should read e.g. "Sidebar" or "Word Wrap" having a checkmark or not or we should not show a checkmark and it should be "Show Sidebar"/"Hide Sidebar" or "Enable Word Wrap"/"Disable Word Wrap".
