### ISSUE TITLE
Audio Call

### ISSUE THREAD

**Issue by basilbenaziz** [microsoft/vscode#149819]
Issue Type: <b>Performance Issue</b>

live share Audio Call not not working at all every time I try to run or do you call it sent me this message 

Live Share Audio failed to start due to a corrupted download. Ensure you have network connectivity then click `Repair` to restart VS Code and attempt recovery.

I am Mac OS in apple M1 max 

VS Code version: Code 1.67.1 (Universal) (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:16.526Z)
OS version: Darwin arm64 21.4.0
Restricted Mode: No

**Comment by SethFalco** [comment]
I think this more likely belong in [MicrosoftDocs/live-share](https://github.com/MicrosoftDocs/live-share)?

**Comment by roblourens** [comment]
Please file on the live share extension's repo

**Comment by thi-days** [comment]
Did anyone solve this problem? I'm still facing the same issue here.

I'm on Mac OS in apple M1 too.

Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z (2 wks ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
