### ISSUE TITLE
A task depends on a CustomExecution task does not stop when the CustomExecution task fails

### ISSUE THREAD

**Issue by a1exwang** [microsoft/vscode#149895]
Does this issue occur when all extensions are disabled?: n/a

```
Version: 1.67.1 (user setup)
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-06T12:37:03.389Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```
Steps to Reproduce:

1. `task.json`
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "test task 1",
            "dependsOn": [
                "teamsfx: ngrok start",
                "next task"
            ],
            "dependsOrder": "sequence"
        },
        {
            "label": "test task 2",
            "dependsOn": [
                "fail",
                "next task"
            ],
            "dependsOrder": "sequence"
        },
        {
            "label": "fail",
            "command": "exit 1",
            "type": "shell"
        },
        {
            "label": "next task",
            "command": "echo next task",
            "type": "shell"
        },
...
```

`teamsfx: ngrok start` implementation in my extension.
```
export class NgrokStartTaskTerminal implements vscode.Pseudoterminal {
  ...
  open(initialDimensions: vscode.TerminalDimensions | undefined): void {
    this.closeEmitter.fire(1); // exit 1 immediately
  }
}

  const execution = new vscode.CustomExecution(async (): Promise<vscode.Pseudoterminal> => {
    return new NgrokStartTaskTerminal();
  });

   // create the task
  const task = new vscode.Task(
    { type: "teamsfx" },
    workspaceFolder,
    "ngrok start",
    "teamsfx",
    execution,
    "custom problem matcher",
  );
  // The custom execution is a background task and uses problem matcher to finish.
  task.isBackground = true;
```

3. Run `test task 2`, it fails and `next task` is not executed. This is expected.
![image](https://user-images.githubusercontent.com/9698542/169204907-dc2f3b12-7c0c-4e44-96e7-ff76967af02f.png)

4. Run `test task 1`. `teamsfx: ngrok start` fails but `next task` is still executed.
<img width="934" alt="image" src="https://user-images.githubusercontent.com/9698542/169205460-49e6d9e7-2c44-4252-b757-be8f78873bae.png">

I assume `CustomExecution` will behave the same as `ShellExecution` in terms of failure behavior. So I expect `next task` will not be executed in this case.

**Comment by meganrogge** [comment]
You are right @alexr00 when it's a background task, this is what's getting returned and always has an exit code of 0 

https://github.com/microsoft/vscode/blob/4b7c904db174fbec85b2aaf5caa5fbe742b5d80d/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L594-L595

**Comment by alexr00** [comment]
Just tried it out and I also can't reproduce it. 

@a1exwang could you try this out in [VS Code insiders](https://code.visualstudio.com/insiders/) and see if the issue still occurs there?

**Comment by meganrogge** [comment]
@a1exwang could also be something with your setup - I noticed that if a task is missing a property - like label - it doesn't run or report failure. You'd need to look in the `Task` output channel
