### ISSUE TITLE
Can't drag an item and drop it to an empty treeview

### ISSUE THREAD

**Issue by 0x-jerry** [microsoft/vscode#149890]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 19.6.0

Sometimes, I can't drag an item and drop it into an empty tree view.

Reproduce step:

1. pnpm install.
2. Run `Launch Extension` task.
3. Drag all items from `viewA` and drop them to `viewB`
4. Then, drag any item from `viewB` and drop it to `viewA` (Can not drop it.)

[minimal code to reproduce](https://github.com/0x-jerry/test-vscode-dnd)

FYI, sometimes, it can drag an item and drop it to an empty tree view, but I didn't change any code.

https://user-images.githubusercontent.com/14226737/169193535-30448907-6145-4ee2-8815-21d32af2d7d5.mp4

**Comment by alexr00** [comment]
I can repro, thank you for the complete example!

**Comment by IanMatthewHuff** [comment]
Verified, thanks for providing the clear repro.
