### ISSUE TITLE
Can´t define breakpoints in code editor

### ISSUE THREAD

**Issue by Wampe** [Microsoft/vscode#14989]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Hello o/ 

Since the update to 1.7.1 I am not able to set breakpoints in the code editor (via mouse in the left column or via F9). And I don´t find any setting to fix.

**Comment by TheColorRed** [comment]
Code does not support breakpoints for all languages, so you might need to download a debugger to get breakpoints, it might be helpful to know what language you are using as well.

**Comment by Wampe** [comment]
@TheColorRed Currently I use Code for node.js and angular.js projects (in TypeScript) with the Debugger for Chrome extension. So if I understand this correctly the problem comes by the extension?

**Comment by roblourens** [comment]
What type of file are you trying to set a breakpoint in?

**Comment by Wampe** [comment]
It says "typescript" when a .ts file is open and "javascript" when a .js file is open etc.
So far I did set the breakpoints into the .js files. But I was also able to set them in a .ts (with no effects of course).

**Comment by roblourens** [comment]
What exactly are you seeing when you say you 'can't define breakpoints' - that they don't show up, or that you see the red circles but they aren't hit when you debug?

**Comment by Wampe** [comment]
Oh. After you´ve said it they don´t show up. 
I still can´t set them via mouse in the column (where the line number is showen...) but I can define a breakpoint (and it gets showen under debug->Breakpoints) via F9 when I am in the code line. But without the red circles in the editor.

**Comment by roblourens** [comment]
Did the breakpoint get moved to a different line after setting it? If you set the breakpoint and it shows up in the Breakpoints window like `app.ts 5 -> 100`, that means it was moved from line 5 to line 100, and the red circle will be down there.

Breakpoints can be moved if your source files are out of sync with what's actually running, or some other problem.

**Comment by Wampe** [comment]
The breakpoints don´t get moved. The red circle is not showing up on the left side (where the line numbers are).

Example (Screentshot):
![nobreakpointatline39](https://cloud.githubusercontent.com/assets/4699636/20026352/b6391a3a-a2f9-11e6-8c20-f72f9ca95bd4.jpg)

I defined a breakpoint in the .js file at line 39. This breakpoint entry is showen in the _debug_ context panel under _breakpoints_. But there is **no** red circle in the column with the line numbers. 
Before the last updates the red circle (for a breakpoints) did get displayed (on the right near by the line number).

**Comment by roblourens** [comment]
Ok, yeah, that's not right :). FYI @isidorn or @bpasero 

It looks like the margin between line numbers and the sidebar is too narrow so it might be hidden. Mine:
![image](https://cloud.githubusercontent.com/assets/323878/20026600/aa52d90c-a2ba-11e6-98cc-ac258a425e8d.png)

What if you hide the sidebar (ctrl+b) or drag it around, or resize the whole window?

**Comment by Wampe** [comment]
ctrl+b, drag and resize (areas and the whole window) don´t change it.

**Comment by smuuf** [comment]
Having the same problem here, also with`1.7.1` version. Can't click to define a breakpoint.

![image](https://cloud.githubusercontent.com/assets/6860713/20033590/2c1510ba-a3a4-11e6-8a3b-05572aaac423.png)

The previous `1.6` was working fine.
Using `felixfbecker.php-debug` extension for PHP debugging.

**Comment by isidorn** [comment]
Now we are respecting the setting `"editor.glyphMargin": false` - delete that setting from your settings file if you want to see the glyph margin.
Even if that setting is turned off you are still able to add / remove breakpoints.

**Comment by Wampe** [comment]
@isidorn Thank you for the note. 

When I create a custom _settings.json_ (didn´t before) and set the value of _editor.glyphMargin_ to _true_ then the glyph margin appears. That´s a solution. But in the general settings it´s already _true_? So why does it get ingnored?

**Comment by isidorn** [comment]
@Wampe maybe because it is set to false in your user settings. Note that we have both user and workspace settings and workspace take priority
