### ISSUE TITLE
impossible to update 

### ISSUE THREAD

**Issue by The-algar** [microsoft/vscode#149828]
Issue Type: <b>Bug</b>

Click "Check for updates" and then I have an access refused to \Microsoft VS Code\unins000.exe

VS Code version: Code 1.66.2 (dfd34e8260c270da74b5c2d86d61aee4b6d56977, 2022-04-11T07:46:01.075Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.89GB (4.67GB free)|
|Process Argv|--crash-reporter-id 34f8070c-6388-4883-a88f-fee19a51a7d3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
vscode-npm-script|eg2|0.3.25
vscode-firefox-debug|fir|2.9.6
code-runner|for|0.11.7
remotehub|Git|0.30.0
vscode-pull-request-github|Git|0.40.0
live-sass|gle|5.3.1
search-node-modules|jas|1.3.0
vscode-autoprefixer|mrm|3.0.1
remote-repositories|ms-|0.4.0
LiveServer|rit|5.7.5
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.

Also, you can try uninstalling and reinstalling.
