### ISSUE TITLE
Classic menu bar buttons clash with other titlebar elements

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#149834]
The existing "Classic" menubar buttons that fill the entire height of the titlebar don't align with the rest of the elements on the titlebar like the layout toggles and titlebar input. They also look somewhat strange with the new custom menu styling on hover.

<img width="741" alt="CleanShot 2022-05-18 at 08 58 45@2x" src="https://user-images.githubusercontent.com/25163139/169088398-67b1f29d-97b0-4af7-8918-0766a4e8475f.png">

**Comment by bpasero** [comment]
Mixed feelings about this change. If you hover over the window control buttons (which are now native), the hover feedback is still a square, so we are not consistent. On the other hand, I noticed how Notepad on Windows 11 draws similar round corners for the menu:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/900690/170631993-80378707-3622-45c6-88f3-b37d73afb0ce.png">

**Comment by doodlezucc** [comment]
Adding to @bpasero's concerns on the redesign, I feel like this takes away from the UI principle of _infinitely big hitboxes_, which suggests that buttons to the edge of a window are **much** more accessible if they reach the actual screen bounds. 
I more accurately display my arguments against this change in a [reply to the pull request](https://github.com/microsoft/vscode/pull/149835#issuecomment-1152927075).

**Comment by daviddossett** [comment]
@doodlezucc I hear you. This is being addressed in #151250.
