### ISSUE TITLE
Files automatically saved when restarting debugger, even though it is set not to

### ISSUE THREAD

**Issue by Hadakajime** [microsoft/vscode#149885]
Issue Type: <b>Bug</b>

Files are not set to save when starting the debugger, and this appears to work correctly only when doing a START, but not a RESTART.

I edit a file, then CTRL+F5 start debugger. File is not saved. Correct.

Then CTRL+SHIFT+F5 to restart debugger, and it automatically saves..... Incorrect.

very frustrating.

![image](https://user-images.githubusercontent.com/20448845/169182105-b79cc80a-8bfe-4897-a1e2-db6a6d3c8003.png)

![image](https://user-images.githubusercontent.com/20448845/169183022-eb43fb23-c2d6-4a59-b10b-e5385a3882f4.png)

![image](https://user-images.githubusercontent.com/20448845/169182197-0d4fb7ae-f491-43be-b0ae-8a04360ded10.png)

![image](https://user-images.githubusercontent.com/20448845/169182211-b7d284d2-781f-453e-9994-717048936c1d.png)

![image](https://user-images.githubusercontent.com/20448845/169182227-07912c7c-0a76-4022-95c3-2b315ff6d0f8.png)

![image](https://user-images.githubusercontent.com/20448845/169182256-432fd72a-7007-453e-9bda-da8f118f4c22.png)

![image](https://user-images.githubusercontent.com/20448845/169182270-b3f2c8e3-67b9-4d55-aac3-d503df096686.png)

![image](https://user-images.githubusercontent.com/20448845/169182301-c9f60013-e319-4657-85d4-69290fb2802e.png)

![image](https://user-images.githubusercontent.com/20448845/169182327-8dec0894-b7f4-4b37-bc0f-3a0c984506f1.png)

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (6.06GB free)|
|Process Argv|--crash-reporter-id 9d1b4a74-6c23-44d3-9db5-383def926efe|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|Memory (System)|24.91GB (9.54GB free)|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.2.4
remote-containers|ms-|0.234.0
remote-wsl|ms-|0.66.3
gitlens|eam|12.0.6
restore-terminals|Eth|1.1.7
vscode-graphql|Gra|0.4.4
vsliveshare|ms-|1.0.5561
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.35.0
prisma|Pri|3.14.0
indenticator|Sir|0.7.0
language-stylus|sys|1.15.0
vscodeintellicode|Vis|1.2.21

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by gjsjohnmurray** [comment]
What language are you coding and debugging?

**Comment by roblourens** [comment]
I see this, good catch
