### ISSUE TITLE
Unable to make "Activity Bar" visible

### ISSUE THREAD

**Issue by kcak11** [microsoft/vscode#149806]
I am using https://vscode.dev and noticed that if the "Activity Bar" is hidden via the menu i.e. "View -> Appearance -> Show Activity Bar"

<img width="562" alt="image" src="https://user-images.githubusercontent.com/703559/169008178-22763930-1f85-412c-adfc-6ef7cbc71356.png">

then there is no way to bring it back because the hamburger menu (3 horizontal lines) launcher is also hidden with the activity bar as below:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/703559/169009558-8e28d893-319c-4307-833c-8f9610b7ba66.png">

The only other way is to clear the browser's storage for vscode.dev domain so that all the settings for this domain are reset.

Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.0.0 Safari/537.36
Embedder: vscode.dev

**Comment by gjsjohnmurray** [comment]
Previously raised in #85124

**Comment by gjsjohnmurray** [comment]
Can you use a keyboard shortcut to open Command Palette and there run `View: Toggle Activity Bar Visibility`?

**Comment by kcak11** [comment]
> Can you use a keyboard shortcut to open Command Palette and there run `View: Toggle Activity Bar Visibility`?

Yes, that works!!

We can probably close this issue as there is an alternative.

**Comment by gjsjohnmurray** [comment]
@connor4312 maybe when Activity Bar is hidden the hamburger should move onto the title bar?

![image](https://user-images.githubusercontent.com/6726799/169024514-701d606d-acd3-4cab-be4a-d30b36d739a0.png)

**Comment by connor4312** [comment]
We don't have control over the title bar when running as a PWA

**Comment by sbatten** [comment]
maybe an easier fix is making it easier to bring back the activity bar. it would be strange to force a title bar if we don't have one because they hid the activity bar

**Comment by kcak11** [comment]
> maybe an easier fix is making it easier to bring back the activity bar. it would be strange to force a title bar if we don't have one because they hid the activity bar

On a similar thought, what if the option to toggle the "Activity Bar" is disabled/hidden when VSCode is ran in the WebEditor/PWA mode, as the "Activity Bar" takes a negligible width(48px) on the screen so not a big deal to let it always be visible.

**Comment by kcak11** [comment]
Currently, there are 2 possible alternatives:
1. Update settings:
```
{
    "window.menuBarVisibility": "classic"
}
```
2. Use Command Palette and there run View: Toggle Activity Bar Visibility

But both of the above options are kind of hidden.
What if we expose the "Show Activity Bar" option in the context-menu upon right click?

**Comment by sbatten** [comment]
With the command center now visible, a right click entry for showing the classic menu is now more prominent.
