### ISSUE TITLE
Feature Request : Context menu new functionality for open folders

### ISSUE THREAD

**Issue by jmar1998** [microsoft/vscode#149855]
Would be nice to have on the context menu for folders have this 2 buttons
1) Open folder on vscode
2) Open folder on wsl (This is related with the extension of Remote - WSL) -> Im submitting this on this issue, but i will relate this with the main extension repo microsoft/vscode-remote-release#6730

This would simplify alot the fact of clicking on file > Open Folder, after that showing the files on the file explorer (Not always on the right folder).
So we transform a four/five steps task into 2 step task :)

**Comment by lramos15** [comment]
Closing as https://github.com/microsoft/vscode-remote-release/issues/6730 did not receive enough upvotes
