### ISSUE TITLE
Terminal decorations aren't working properly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#149866]
Notice how the command is getting created in the console but not in the UI:

![image](https://user-images.githubusercontent.com/2193314/169167489-594d1f72-0ff4-47cd-81f2-b0169f40d545.png)

**Comment by meganrogge** [comment]
that's bc `handlCommandStarted` isn't happening again after the first time
![Screen Shot 2022-05-18 at 6 45 12 PM](https://user-images.githubusercontent.com/29464607/169186004-3f2601e3-4162-4cc6-8723-4756c91e37b6.png)

**Comment by meganrogge** [comment]
today, the decoration isn't even showing up for the first command/placeholder

**Comment by Tyriar** [comment]
Hoping this will be fixed when https://github.com/xtermjs/xterm.js/pull/3823 and related fixed land

**Comment by Tyriar** [comment]
Seems related to https://github.com/microsoft/vscode/pull/148972, the decoration addon is disposed of immediately on creation now:

![image](https://user-images.githubusercontent.com/2193314/169591483-5e38b130-ada9-4a2b-91cf-ecdd3517e205.png)

Working on a fix
