### ISSUE TITLE
Code lens influences wavy lines

### ISSUE THREAD

**Issue by klkq** [microsoft/vscode#149886]
Issue Type: <b>Bug</b>

Using VS Code with _Extension Pack for Java_ on my laptop. With the default scale, some combination of `editor.fontSize` and `editor.codeLensFontSize` causes the bottom of some wavy lines marking problems not displayed. For example, the former one 16 and the latter one default.
![image](https://user-images.githubusercontent.com/42540813/169041759-870f5808-eda5-47ec-a7c9-b815e683dd30.png)
The issue disappears if I change the scale by pressing `Ctrl` + `+` or `Ctrl` + `-`. And it only happens to lines with an even number. Also, setting `editor.codeLens` to `false` resolves the issue.

Steps to reproduce:
1. Install the Extension Pack for Java.
2. Open a Java source file with problems.

P.S.
This issue was first reported at [vscode-java-debug repo](https://github.com/microsoft/vscode-java-debug/issues/1165), but it now seems like an issue of VS Code.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.21GB free)|
|Process Argv|--crash-reporter-id be46c717-cfc1-4512-b3ff-cb752ac880fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
vscode-language-pack-zh-hans|MS-|1.67.3
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
powershell|ms-|2022.5.1
java|red|1.6.0
vscodeintellicode|Vis|1.2.21
vscode-gradle|vsc|3.12.0
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4

</details>

**Comment by alexdima** [comment]
This is most likely caused by using `window.zoomLevel` (i.e. ctrl+= or ctrl+-). @klkq Does this reproduce when configuring `"window.zoomLevel": 0` ?

**Comment by klkq** [comment]
Yes, this can be reproduced by following steps:
1. Set `editor.fontSize` to 16 and `editor.codeLensFontSize` to 0.
2. Set `window.zoomLevel` to `0`, `2` or `-2`, and the problem happens. But if set to `1` or `-1`, no problem.

**Comment by alexdima** [comment]
Here's a summary of my understanding in this area:

* when using a `window.zoomLevel` value which is non zero, or when using the scaling feature in Windows, Chromium internally creates a zoom factor, perhaps something like 1.25.
* we paint all our `<div>`s at integer coordinates and with integer widths and heights on our side.
* but Chromium begins multiplying all our integers with the zoom factor.
* this causes the nice integers to become floats and at one point there will be rounding errors or situations where a certain integer, based on how it aligns will round up or down and introduce a gap or jitter, etc (e.g. imagine a segment from 150-151 becoming 160.55-161.45 which will be rounded to 161-161, etc).

If you are sensitive about pixel perfect rendering, I recommend:
* close all instances of vscode
* execute ` code --force-device-scale-factor=1` (this will instruct Chromium to ignore the multiplier scale coming in from Windows). This can be persisted using `F1 > Preferences: Configure Runtime Arguments` or by modifying the shortcut.
* configure `window.zoomLevel: 2` or 3 and then reduce the fontSize and lineHeight. It could be that one of these zoom levels results in a better zoom factor with smaller (or more rare) rounding errors, given how floats are represented.

But that being said, I don't think there is any possible code change that we could do on our side.
