### ISSUE TITLE
Testing: Keep the test message view when back and forth

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#149892]
When user navigates to another class file from the test message view, if the user goes back, the view disappears.

![view](https://user-images.githubusercontent.com/6193897/169198521-4d103bc8-5075-4d24-8267-c2a8d9156e03.gif)

It would be better that the view could stay there, and remember the scroll bar location.

**Comment by connor4312** [comment]
I'm no longer planning to do this, since the peek is now an ephemeral supplement to the more concrete Test Results view.
