### ISSUE TITLE
C ++ Debugger Frequently Disconnects While Stepping

### ISSUE THREAD

**Issue by reasoning** [microsoft/vscode#149825]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Debug any C++ code remote or local.

Stepping through eventually results in "Stopping due to fatal error: ProtocolException: Cannot evaluate expression on the specified stack frame."

This did not happen with the previous version(s) of vscode.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:39:22.915Z)
OS version: Linux x64 5.17.5-76051705-generic
Restricted Mode: No
Connection to 'SSH: mainframe' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.59GB (1.04GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5fbb5169-0367-4f2f-bcc4-b836ec4f5014|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|

Connection to 'SSH: mainframe' could not be established  Canceled
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-fix-checksums|leh|1.1.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.9.8
makefile-tools|ms-|0.5.0
material-theme|zhu|3.13.29

(2 theme extensions excluded)

</details>

**Comment by ThreeZhiWang** [comment]
me too

**Comment by roblourens** [comment]
Please file this on the C++ extension repo
