### ISSUE TITLE
Format Code: func-call-spacing error?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#14983]
I have an Angular controller which is wrapped in an IIFE.  When I use VSCode's "format code" command, it adds a space between the function and parens, which is correct:

`_this.deploy = function () {...}`

But "format code" does this to the end of the IIFE, which is equally ok but eslint flags it as an error:

![screen shot 2016-11-03 at 10 54 56 am](https://cloud.githubusercontent.com/assets/835148/19971303/03256204-a1b5-11e6-8918-e2ee8610e8f3.jpg)

Can this be remedied via settings, or is this a bug?

- VSCode Version: Code - Insiders 1.8.0-insider (dbf3ba74e6cf3b33687b7d47e321e642fc1e7562, 2016-11-04T10:07:39.066Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.3.5|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.0|
|one-monokai|azemoh|0.1.15|
|htmltagwrap|bradgashler|0.0.3|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.0.8|
|tslint|eg2|0.5.40|
|auto-close-tag|formulahendry|0.3.4|
|auto-rename-tag|formulahendry|0.0.7|
|Angular1|johnpapa|0.1.16|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|7.4.0|
|vscode-stylefmt|mrmlnc|2.0.1|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|3.0.7|
|stylelint|shinnn|0.18.0|
|theme-tesla|smlombardi|0.0.1|
|autoimport|steoates|1.2.2|
|theme-onemonokai-alt|smlombardi|0.0.1|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1.
2.

**Comment by rebornix** [comment]
it looks like a bug to me as formatting should not adding the space.

**Comment by waderyan** [comment]
@smlombardi thanks for opening this issue. Can you give me some code I can copy and paste? Also can you run VS Code with no extensions to verify this is not an extension issue? You can do that by adding `--disable-extensions` option to the command line.

**Comment by smlombardi** [comment]
```
(function () {
  'use strict';

  app.controller('PMTController',
    function () {
      var _this = this;

      _this.foo = function () {
        console.log('hello world');
      };
    });
}());

```

**Comment by waderyan** [comment]
@smlombardi thank you. Reproduced on the latest bits. Migrating to TS Server repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12238
