### ISSUE TITLE
Search in files skips files that havenare open but have not been activated yet

### ISSUE THREAD

**Issue by bveldkamp** [microsoft/vscode#149820]
When multiple files are open, a global search will only return matches from files that have been activated since starting vscode (meaning: Clicking on the file's tab to make it visible) 

Steps to reproduce:
1. Open a number of files. For instance by dragging a selection from Windows Explorer
2. Open the Search window (Ctrl+Shift+F) and search for a text that is in some of the opened files
3. Notice that search returns only matches from the active file
4. Activate one of the other files
5. Repeat step 3, and notice that now results from 2 files are returned

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.84GB free)|
|Process Argv|--crash-reporter-id fe6ec923-5563-4e9b-8607-b38137618d79|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-m3u|af4|1.0.0
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
azure-pipelines|ms-|1.205.0
csharp|ms-|1.24.4
python|ms-|2022.6.2
azure-account|ms-|0.10.1
powershell|ms-|2022.5.1
vs-keybindings|ms-|0.2.1
log-analysis|Xin|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
testflightcf:30433671
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe you have clicked this?

![image](https://user-images.githubusercontent.com/6726799/169108554-2c4037db-f6d8-44dd-a935-e03ed50590e4.png)

If you have, you should see this extra message at the top of your results:

![image](https://user-images.githubusercontent.com/6726799/169108788-cf96284c-7dcb-4844-b169-939e3333ee96.png)

And after it a "(disable)" link with which to toggle that button and re-run the search.

**Comment by bveldkamp** [comment]
@gjsjohnmurray 

That options was off. If I turn it on, the search works as expected. But the issue is really something else: With this option turned off, only files that have been activated in the current vscode session are searched. So, initially one 1 file is searched, and after I Alt-Tab to another file and repeat the same search, 2 files are searched. This behavior is inconsistent. 

I also noticed that if I open a folder, rather than dragging random files in from Explorer, the search works in all files, at least if the _Search only in open editors_ option is off. With _Search only in open editors_ on, only open files are searched, as expected.

**Comment by gjsjohnmurray** [comment]
I think I understand what you are reporting.

1. With no VS Code instances running, open a new VS Code.
2. From Windows Explorer drag three individual files onto the VS Code window. Each one gets loaded in its own tab.
3. Use the Search view to find text which occurs in all of the files. The results show the matches correctly.
4. Close VS Code.
5. Launch VS Code again. You see tabs for each of the files you previously dragged into VS Code. One of these tabs is active, and the contents of the file are visible.
6. Use the Search view to find the same text as previously. This time it only reports matches from the file in the active tab.
7. Click on the next tab and repeat your search. Now it finds matches in this one as well, but still not in the third one.
8. Click on the third tab and repeat search. Now it finds matches in all three files.

Is that an accurate description of what this issue is about?

**Comment by bveldkamp** [comment]
Yes, that's pretty much it. You could skip steps 3–5 by dragging multiple files at once from Explorer, in which case only one file becomes active, and search will only see that file. When opening files one by one, each one will be activated already, and search works as it should.

Somewhat related: The _Search only in open editors_ makes sense when a folder is opened in VS Code, but IMO not so much when only separate files are opened. Should I file a new issue about that?

**Comment by roblourens** [comment]
I'm aware of this issue and thought it was covered by an open issue somewhere, but can't find it right now. You're right, files only get searched when they have been loaded in an editor in your scenario, or if they are in a folder that is open in the window.

> The Search only in open editors makes sense when a folder is opened in VS Code, but IMO not so much when only separate files are opened. Should I file a new issue about that?

I think in this scenario, the search should return the same results regardless of that option, and I consider that the same issue.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/62488
