### ISSUE TITLE
MY TERMINAL KEEPS CLOSING

### ISSUE THREAD

**Issue by demithehomie** [microsoft/vscode#149846]
Issue Type: <b>Bug</b>

Whenever I open the VSCode Terminal, it stays open for about 20-30 seconds, and then closes automatically. Always. By itself, automatically.

"The terminal process "C:\WINDOWS\System32\cmd.exe" was terminated with exit code: 4294967295."

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (2.00GB free)|
|Process Argv|--crash-reporter-id a3543708-7464-490d-b5b9-24b441e1acba|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.62
vscode-exec-node|mir|0.5.4
vscode-language-pack-pt-BR|MS-|1.67.3
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.1
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-react-native|msj|1.9.2
create-react-tsx-component|ric|1.6.0
LiveServer|rit|5.7.5
rocketseatreactjs|roc|3.0.2
rocketseatreactnative|roc|3.0.1
open-in-browser|tec|2.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by ChaseKnowlden** [comment]
Terminal stayed open on 1.67.2

**Comment by meganrogge** [comment]
have you tried this suggestion? https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141

**Comment by ChaseKnowlden** [comment]
Works on 1.67.2

**Comment by demithehomie** [comment]
> have you tried this suggestion? https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141

I'm actually trying right now. Just waiting the restart of the computer.

**Comment by demithehomie** [comment]
> have you tried this suggestion? https://github.com/microsoft/WSL/issues/5092#issuecomment-615545141

yup, didn't worked. Same problem.

**Comment by demithehomie** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.67.2. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

I don't understand. To me it says 1.67.2. Is updated.

![IMG_20220518_174533507.jpg](https://user-images.githubusercontent.com/68928535/169152760-133eda0d-13ce-48ed-ae66-951c7aa10ad3.jpg)

**Comment by meganrogge** [comment]
what are your settings?

**Comment by demithehomie** [comment]
> what are your settings?

It worked. I just needed to wait a little bit after your tip. Thank you very much.

**Comment by demithehomie** [comment]
Same issue
