### ISSUE TITLE
Codespace not loading + Terminal not working!

### ISSUE THREAD

**Issue by punitmalpani** [microsoft/vscode#149901]
ADD ISSUE DESCRIPTION HERE
Cosespace keeps loading and asks for reloading after5-10 mins. Also not able to type anything on the terminal window. The update50 command, which is meant to update the codespace, also fails every time reporting error with port 1337 and asks for reloading window. 

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.67 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
pls create an issue in the codespaces repo for this. 

regarding the terminal,

Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"
