### ISSUE TITLE
Add Search TextBox to Explorer Pane

### ISSUE THREAD

**Issue by drweb86** [Microsoft/vscode#14990]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 10.0.14393

Visual Studio has a nice search box (Ctrl + ;) shown in the picture below. When you type here some text it finds it across all file names and inside files showing each occurence.
![image](https://cloud.githubusercontent.com/assets/4712173/20009295/f93ae452-a2b4-11e6-80e4-7c750de01b72.png)

Could you please add that to explorer pane. It'll be more comfortable to search via it, not via Ctrl+Shift+F.

**Comment by TheColorRed** [comment]
If you press <kbd>ctrl+p</kbd> you can then search your files from the dropdown that appears.

**Comment by rebornix** [comment]
Command palate is our preferred way to navigate through/search files :)
