### ISSUE TITLE
Setup should broadcast WM_SETTINGCHANGE instead of restarting explorer.exe

### ISSUE THREAD

**Issue by jamiehankins** [microsoft/vscode#149965]
When the setup finishes, if you choose "Add to path", it tells you that explorer must be restarted for this to take effect.

Instead, when running on Windows, once the path has been updated in the registry, setup should broadcast a `WM_SETTINGCHANGE` message. This tells explorer to reload settings, which would result in the updated path being applied. Details [here](https://stackoverflow.com/a/48816308/645431).

**Comment by joaomoreno** [comment]
Closing per https://github.com/microsoft/vscode/issues/117627#issuecomment-937531322
