### ISSUE TITLE
Test Markdown link diagnostics 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#149979]
Test for #146303

- [x] Mac @chrmarti
- [x] Linux @TylerLeonhardt
- [x] Windows @joyceerhl

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23149979%0A%0A&assignees=mjbvz)

---

## Summary

#146303 Adds error reporting for broken markdown links. This includes:

- Links to headers in the current file that do not exist: `[text](#no-such-header)`
- Usage of reference links that don't exist: `[text][no-such-ref]` or `[no-such-ref]`
- Links to files that don't exist: `[text](/no-such-file)`
- Links to headers in markdown files that don't exist: `[text](/some-markdown#no-such-header)`

For this test plan item, try testing out this this error reporting and seeing if anything doesn't work as expected 

## Testing
Enable `markdown.experimental.validate.enabled` and then try testing out the error reporting.

Other areas to try out:

- There are other `markdown.experimental.validate.*` settings that control what is validated and what is not
- You can use the `skip paths` setting to tell VS Code to ignore certain file paths, even if they don't exist on disk
- We should watch linked to files so that if they are created or deleted, the diagnostics in the markdown files are automatically updated

**Comment by joyceerhl** [comment]
Caught a broken link in vscode-wiki with this feature :) https://github.com/microsoft/vscode-wiki/commit/6b9f87510df1ebc2fdd474444eacf7ca898008bb

**Comment by TylerLeonhardt** [comment]
Works really nicely!
