### ISSUE TITLE
Markdown preview does not refresh after git pull

### ISSUE THREAD

**Issue by Tiegris** [microsoft/vscode#149974]
Issue Type: <b>Bug</b>

## How to reproduce

- Open a markdown file for preview
- Close the actual file, so only the preview is opened
- git pull, (there are changes on the remote)
- open the preview and the markdown file side-by-side

The actual markdown file got updated, but the preview did not.

Screenshot:
![image](https://user-images.githubusercontent.com/33226948/169399500-bebebcd8-5022-471f-9a75-015ec4295b8f.png)

## Expected

I expected the preview to refresh and display the changes 

## Actual

The preview did not refresh, and kept displaying the old version even after closing the preview window and opening it again. Had to close and reopen VS Code for the update to happen.

## Generated report

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.35GB free)|
|Process Argv|F:\\UNI\\MSc_Onlab_1\\K8sMonitorNet --crash-reporter-id d027ceef-e0f7-4589-9ad7-6fe9c0753d01|
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.64
vscode-markdownlint|Dav|0.47.0
latex-workshop|Jam|8.26.0
Kotlin|mat|1.7.1
vscode-docker|ms-|1.22.0
vscode-kubernetes-tools|ms-|1.3.8
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
remote-wsl|ms-|0.66.3
cpptools|ms-|1.9.8
vscode-janus-debug|otr|1.5.8
vscode-yaml|red|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by Tiegris** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Downloaded from link, no extensions: Yes, it does reproduce:
![image](https://user-images.githubusercontent.com/33226948/169417455-16896de9-3034-42ca-8ebf-50534730d4a6.png)
