### ISSUE TITLE
Destructuring does not auto-format whitespace

### ISSUE THREAD

**Issue by marcomorain** [Microsoft/vscode#14996]
- VSCode Version: 1.7.1 `02611b40b24c9df2726ad8b33f5ef5f67ac30b44` 2016-11-03T13:44:00.572Z
- OS Version: OSX 10.12.1 (16B2657)

## Issue

The whitespace on the LHS of a destructuring assignment is not formatted.

## Steps to Reproduce:

1. Add the following to a typescript file:

```JS
const {NoSpaces} = { NoSpaces: 1 }
const { WithSpaces } = { WithSpaces: 1 }
const {OneSpace } = { OneSpace: 1 };
```

2. Format the document.

## Expected

I would expect the whitespace on the LHS of the assignment to be consistent. I would expect either:

```JS
const {NoSpaces} = { NoSpaces: 1 }
const {WithSpaces} = { WithSpaces: 1 }
const {OneSpace} = { OneSpace: 1 };
```

or 

```JS
const { NoSpaces } = { NoSpaces: 1 }
const { WithSpaces } = { WithSpaces: 1 }
const { OneSpace } = { OneSpace: 1 };
```

## Actual Output

Whitespace of the LHS is inconsistent:

```JS
const {NoSpaces} = { NoSpaces: 1 }
const { WithSpaces } = { WithSpaces: 1 }
const {OneSpace } = { OneSpace: 1 };
```

**Comment by waderyan** [comment]
@marcomorain thank you for opening this issue and apologize for the delay. This issue has to deal with functionality provided by TS Server. Migrating to that repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12239
