### ISSUE TITLE
True workspace level exclusion for problems view

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/vscode#149949]
Related to #22289 , which allows filtering problems  in the problem view, but a saveable, shareable, persistent setting that could be added to `./.vscode/settings.json`. 

Consider my personal scenario: the TOML extension reads all files of the format `.*rc`, but [it's actually INI format](https://coverage.readthedocs.io/en/6.3.1/config.html). Even changing the language retails the parser syntax highlighting for the error, and I don't want to disable it for the workspace -- I have real TOML files. I just want to ignore problems stated for this file.

Also, this workspace configuration is shared by others working on the project -- other users shouldn't have to do this independently. Not to mention telling them to filter `!**/.*rc` persists a message showing that they're viewing a subset, and doesn't change the badge count on the problems panel.

Essentially, this is reflective of all the comments after https://github.com/microsoft/vscode/issues/22289#issuecomment-380851049 

I'd suggest a setting nearly identical to `files.exclude`, but to _only_ exclude it from being evaluated in the problems panel.

**Comment by sandy081** [comment]
I would recommend to file a request against corresponding extension to expose a setting to configure for which files problems has to be generated.

**Comment by tigerhawkvok** [comment]
@sandy081 Are you seriously suggesting that, rather than VSCode adding a pattern match once (for which much of the infrastructure already exists), it's better for every person who encounters a reason, any reason, to want to exclude a file from the Problems view to petition that extension for that user's use case to have a configuration?

I mean, talk about making a mockery of DRY -- and even that mockery assumes that every extension has a perfectly active and responsive developer who is willing to implement that change. 

Your comment is only _slightly_ more reasonable than suggesting I contact the Windows team to visually filter VSCode's output. VSCode is the proximate provider of the panel, and the problem is not limited to a single project or extension; so VSCode should be the solution provider to the global problem, too.

**Comment by sandy081** [comment]
@tigerhawkvok I am sorry but this is what recommend users if they want to configure what kind of problems have to be generated. VS Code is just an UI for these problems generated by extensions and any filter provided by VS Code is an UI filter.
