### ISSUE TITLE
[loc][Query][VSCode[ Please clarify localizability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#14993]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Configurations that will be launched as part of this "composite" configuration. Only respected if type of this configuration is "composite".

File Name:
src\vs\workbench\parts\debug\node\debugAdapter.nls.resx

Resource ID:
".resx", 0; "debugConfigurationNames"

Query:
Please confirm if "composite" is localizable.	CnE_Developer_Moravia_ITA1@hotmail.com	11/2/2016 7:05:25 PM

**Comment by isidorn** [comment]
"Composite" is not localizable
