### ISSUE TITLE
Add Colorfull Icons for Folders and JS Files to Explorer Pane

### ISSUE THREAD

**Issue by drweb86** [Microsoft/vscode#14991]
When i open them in Visual Studio its easy to navigate through Solution Pane because of files and folders has icons.
Could you please review possibility to add such thing to your app aswell.
![image](https://cloud.githubusercontent.com/assets/4712173/20009498/ca4a9434-a2b5-11e6-81d0-0f7ac9e708f8.png)

**Comment by TheColorRed** [comment]
You can do this by pressing: <kbd>F1</kbd> Then typing: `File Icon Theme`

From there you can select an icon theme or download one from the marketplace

**Comment by rebornix** [comment]
We do have this feature as above :)
