### ISSUE TITLE
The bug of Command Prompt terminal

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode#149985]
I found the Command Prompt terminal have the extra blank lines at the first line. 

![image](https://user-images.githubusercontent.com/82581024/169421811-3848e027-766a-4a0a-aa21-bc28eb3f26b9.png)

**Comment by meganrogge** [comment]
what are your settings and does this repro in an external command prompt terminal?

**Comment by Vincent0706** [comment]
Thank you for your reminder. I found that this is the reason for this setting.
```
"terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": ["/K chcp 65001 >nul"], 
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash"
        }
    },
```
`"args": ["/K chcp 65001 >nul"], ` , I want to use this setting to solve Chinese garbled code problem, but it will change the Command Prompt terminal displays.
