### ISSUE TITLE
Support theme-conditioned extension icons

### ISSUE THREAD

**Issue by radeksimko** [microsoft/vscode#149936]
Extensions can use `galleryBanner` to adjust the font and background colours on the Marketplace today, although this is not reflected inside VS Code. I'm assuming this is intentional, since rendering each extension based on extension author's choice, rather than based on user's choice of a theme would likely look odd. (someone correct me if I'm wrong here)

In both VS Code and Marketplace there is only 1 icon so most icons have to have a solid light or dark background to provide the contrast for a light or dark icon. When a black icon with transparent background is used, this results in invisible icon either in dark or light theme.

<img width="604" alt="Screenshot 2022-05-19 at 14 27 48" src="https://user-images.githubusercontent.com/287584/169304540-135a7b31-7f69-42a6-ab71-12dc73ac2d98.png">

<img width="598" alt="Screenshot 2022-05-19 at 14 24 59" src="https://user-images.githubusercontent.com/287584/169304569-7fbd2451-b47e-473e-918c-686c2c457f3f.png">

The only way around it is to serve the icon with solid white background, but that doesn't seem like an ideal solution.

More importantly there are contexts within both Marketplace _and_ VS Code where rendering each extension differently just doesn't make sense - e.g. in [search results](https://marketplace.visualstudio.com/search?term=hashicorp&target=VSCode&category=All%20categories&sortBy=Relevance).

Slightly related to https://github.com/microsoft/vscode/issues/139556

FYI I also filed https://github.com/microsoft/vsmarketplace/issues/401

**Comment by isidorn** [comment]
For this we would need support from the marketplace to have multiple icon resources per theme.
So as upstream this requires https://github.com/microsoft/vsmarketplace/issues/401

fyi @anangaur @prashantvc

Unless I am missing something @sandy081
