### ISSUE TITLE
Can't change docker-build task shell

### ISSUE THREAD

**Issue by Fydon** [microsoft/vscode#149913]
Issue Type: <b>Bug</b>

On Windows 10 I'm trying to change the shell docker-build tasks use from cmd.exe to pwsh.exe. I would prefer to define this in the task. I've tried the following:

1. Defining options for the all task, defining options for all Windows tasks and defining options for a task, although it probably is not valid at the task level for docker-build.

```
{
  "version": "2.0.0",
  "options": {
    "shell": {
      "executable": "pwsh.exe",
      "args": ["-Command"]
    }
  },
  "windows": {
    "options": {
      "shell": {
        "executable": "pwsh.exe",
        "args": ["-Command"]
      }
    }
  },
  "tasks": [
    {
      "label": "docker build",
      "type": "docker-build",
      ...
      },
      "options": {
        "shell": {
          "executable": "pwsh.exe",
          "args": ["-Command"]
        }
      },
    },
  ]
}
```

2. In settings.json using `"terminal.integrated.automationShell.windows": "C:/Program Files/PowerShell/7/pwsh.exe"`, as documented [here](https://code.visualstudio.com/docs/editor/tasks#_can-a-task-use-a-different-shell-than-the-one-specified-for-the-integrated-terminal). I assume that I could use `"terminal.integrated.automationShell.windows": "pwsh.exe"` if it worked.
3. I looked at `terminal.integrated.automationProfile.windows` in settings, but could not see any documentation.
4. I've also tried using `"terminal.external.windowsExec": "C:\\Program Files\\PowerShell\\7\\pwsh.exe"` in settings.json.

Questions:
1. Does docker-build only work with cmd.exe or is there a way to choose another shell?
2. For `terminal.integrated.automationProfile.windows`, is `path` the path the task will execute in or is it the path of the shell I want?

VS Code version: Code - Insiders 1.68.0-insider (688c80245936b49b7ceca494d9edfe97cae06f8a, 2022-05-18T05:15:45.170Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (27.04GB free)|
|Process Argv|--crash-reporter-id 09295c6e-295b-4ff9-95ca-615dc584c0f4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (87)</summary>

Extension|Author (truncated)|Version
---|---|---
gitdiffer|aag|0.0.3
better-comments|aar|3.0.0
Bookmarks|ale|13.3.0
aws-toolkit-vscode|ama|1.38.0
ng-template|Ang|13.3.4
atlascode|atl|2.10.12
markdown-mermaid|bie|1.14.0
markdown-preview-github-styles|bie|1.0.1
vscode-intelephense-client|bme|1.8.2
turbo-console-log|Cha|2.1.7
path-intellisense|chr|2.8.0
angular-schematics|cyr|5.2.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
xml|Dot|2.5.1
vscode-wasm|dts|1.3.1
gitlens|eam|12.0.6
EditorConfig|Edi|0.16.4
apacheconf-snippets|eim|1.3.0
prettier-vscode|esb|9.5.0
url-encode|fle|1.1.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.7
vscode-lombok|Gab|1.0.1
remotehub|Git|0.32.0
vscode-pull-request-github|Git|0.42.0
go|gol|0.33.0
todo-tree|Gru|0.0.215
debug-visualizer|hed|2.3.1
output-colorizer|IBM|0.1.2
vscode-env|Iro|0.1.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.0.1
wordcounter|kir|2.4.2
file-downloader|min|1.0.12
mindaro|min|1.0.120220125
ecdc|mit|1.7.0
vscode-apache|mrm|1.2.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.24.4
vscode-kubernetes-tools|ms-|1.3.8
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
hexeditor|ms-|1.9.6
live-server|ms-|0.2.12
powershell|ms-|2022.5.1
remote-repositories|ms-|0.8.0
vs-keybindings|ms-|0.2.1
vscode-github-issue-notebooks|ms-|0.0.119
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5561
gradle-language|nac|0.2.3
indent-rainbow|ode|8.3.1
vscode-versionlens|pfl|1.0.10
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.33.0
material-icon-theme|PKi|4.17.0
material-product-icons|PKi|1.3.0
fabric8-analytics|red|0.3.5
java|red|1.6.0
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
vscode-yaml|red|1.7.0
perl|ric|2.3.0
preview-vscode|sea|2.2.5
sonarlint-vscode|Son|3.4.1
code-spell-checker|str|2.2.0
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vscode-spring-boot-dashboard|vsc|0.3.1
vscode-spring-initializr|vsc|0.9.0
vscode-import-cost|wix|3.3.0
php-debug|xde|1.26.1
markdown-all-in-one|yzh|3.4.3
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
pythonvsnew555:30438690
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506

```

</details>

**Comment by alexr00** [comment]
> Does docker-build only work with cmd.exe or is there a way to choose another shell?

This question would be best answered by the author of the extension you have installed that provides the `docker-build` task type.

> For terminal.integrated.automationProfile.windows, is path the path the task will execute in or is it the path of the shell I want?

It should be the path of the shell you want to use.
