### ISSUE TITLE
workspace-namespace/ window namespace tests integration tests failing

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#14995]
Linux, master
- run integration tests `./scripts/test-integration.sh`

 window namespace tests
    ✓ editor, active text editor (218ms)
    ✓ editor, UN-active text editor
    ✓ editor, assign and check view columns (827ms)
    1) "after each" hook: cleanUp for "editor, assign and check view columns"

  workspace-namespace
    ✓ configuration, defaults
    2) "after each" hook: cleanUp for "configuration, defaults"

  18 passing (25s)
  2 failing

  1) window namespace tests "after each" hook: cleanUp for "editor, assign and check view columns":
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
  

  2) workspace-namespace "after each" hook: cleanUp for "configuration, defaults":
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.

**Comment by bpasero** [comment]
`Das Pferd frisst kein Reis.` can only be @jrieken ;)

**Comment by jrieken** [comment]
They don't fail for me and also not on the build [machines](https://travis-ci.org/Microsoft/vscode/jobs/173309450#L6775)

**Comment by aeschli** [comment]
Fail for me consistently. Please come by to debug it...

**Comment by aeschli** [comment]
Found the problem. The tests [cleanUp](https://github.com/Microsoft/vscode/blob/master/extensions/vscode-api-tests/src/utils.ts#L52) closes all editors and waits with `onDidChangeVisibleTextEditors` until an empty editors array is returned.

On my machine always one editor stays open: The editors url is something like `inmemory://model/13` and has languageId 'Log'

It turns out it is the output view of the JSON language server that shows content as I have `"json.trace.server": "verbose"` set in the settings of my OSS Dev instance.

- The tests should not run as a OSS Dev instance, but run with their own (or clean) user settings
- the output view seems the leak through as an editor in `onDidChangeVisibleTextEditors` and `vscode.window.visibleTextEditors`

**Comment by jrieken** [comment]
Yeah - that's a known problem with the integration tests. They reuse the dev version workspace state
