### ISSUE TITLE
Terminal window needs to be closed twice after code.cmd invoked

### ISSUE THREAD

**Issue by latkin** [Microsoft/vscode#1499]
- Launch Code from the prompt via `%installdir%\bin\code.cmd`
 - Exit the prompt (via X-out, `exit` command, etc)

**Expected** Terminal exits
**Actual** Terminal does not exit, it becomes unresponsive.  Need to take exit action a second time to close the window.

```
Version 0.10.5
Commit dfc08dc9edf6607483b193bf934d3badc3fa2e11
Date 2015-12-17T16:08:04.766Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1
```

![close](https://cloud.githubusercontent.com/assets/5943573/11916733/39374578-a699-11e5-8dcd-81d3dcfd9dc6.gif)

**Comment by latkin** [comment]
Seems related to https://github.com/Microsoft/vscode/issues/1109. There are different quirks specific to launching with `code.exe` and `code.cmd`

**Comment by joaomoreno** [comment]
Likely a problem with the Command Prompt, won't do nothing here.
