### ISSUE TITLE
Support folder nesting with nested-files feature

### ISSUE THREAD

**Issue by NickBolles** [microsoft/vscode#149948]
Nested files in VSCode 1.67 ([release notes](https://code.visualstudio.com/updates/v1_67#_explorer-file-nesting)) is great (especially coupled with https://github.com/antfu/vscode-file-nesting-config), but I think a great enhancement would be to allow nesting folders under files. 

A great example of this is `package.json` and `node_modules/`. Similarly https://github.com/antfu/vscode-file-nesting-config nests "dotfiles" under the `package.json`, "dot folders" would be great for this too (`.github/`, `.vscode/` `.yarn/` etc.).

Are there any blockers in implementing it? Is it something that I could take a stab at?

**Comment by gjsjohnmurray** [comment]
Is this covered by #149431?

**Comment by NickBolles** [comment]
Yes it is! Not sure how that didn't come up in my search, link the PR to that issue instead and closing this one.
