### ISSUE TITLE
Git view not detect multiple project on root directory

### ISSUE THREAD

**Issue by Adrienb16** [Microsoft/vscode#14998]
- VSCode Version: 1.8.0 - insider
- OS Version: ubuntu 16.04 64bit

Steps to Reproduce:

I'have two projects in my worspace : 

```
.vscode 
ConsoleApp1
      .gitignore
      Program.cs
      project.json
ConsoleApp2
     .gitignore
      Program.cs
      project.json
```

Each project have specific repository but Git view not detecte there respository in root folder.

**Comment by rebornix** [comment]
Dup of #13709 . Sorry we don't have plan for this kind of scenario.
