### ISSUE TITLE
NPM Scripts should not show "install" script in every non-root monorepo package

### ISSUE THREAD

**Issue by aaronadamsCA** [microsoft/vscode#149924]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows 11 Pro 21H2

Steps to Reproduce:

1. Open a monorepo, in our case one that uses Yarn 3.
2. Look at any non-root package in the NPM Scripts pane.

The new unexpected behaviour is the appearance of an "install" script in every non-root package:

<img src="https://user-images.githubusercontent.com/1505561/169272766-d5feb883-b056-4531-8ae1-77d2c5a0e0c6.png" width="300">

I suppose a virtual "install" script might have been nice to have in the monorepo root; instead it appears everywhere except for the monorepo root.

Running the script just executes `yarn install`, which has the same behaviour regardless of the working directory in which it's invoked - it just installs all the dependencies for the full monorepo.

Adding `"install"` to `npm.scriptExplorerExclude` does not make this go away.

I haven't been able to find any mention of this new feature anywhere, so I'm not sure what the intended behaviour was; but I'm guessing it wasn't this!

**Comment by alexr00** [comment]
@meganrogge or @Tyriar do you want to take this?

**Comment by aaronadamsCA** [comment]
> We should exclude `install` when its in `scriptExplorerExclude`.

@alexr00 Just please note it's also strange that it shows up in every package except the monorepo root package. Since `yarn install` from anywhere in a monorepo will install the entire monorepo - I would hope an `install` script would only show up in the monorepo root package.

Obviously a minor bug, but also the kind of bug I can't fix myself since these parts are closed source :)
