### ISSUE TITLE
[loc][Query][VSCode] Please clarify the single-word string

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#14994]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Process

File Name:
src\vs\workbench\parts\debug\electron-browser\debugViewer.nls.resx

Resource ID:
".resx", 0; "process"

Query:

Is it a verb or a noun? Can you please provide more context? Thanks!	Cristina Carrasco	11/3/2016 8:45:42 AM

**Comment by rebornix** [comment]
It's dup of #14860.
