### ISSUE TITLE
Python-Flask false possitive problem 

### ISSUE THREAD

**Issue by FernandoBorea** [microsoft/vscode#149986]
Issue Type: <b>Bug</b>

I am working on a Flask web application (Repo: https://github.com/FernandoBorea/CS50X-Final-Project) and for some reason when I open any Python source file, VS Code reports a problem: 

"[{
	"resource": "/mnt/c/Users/Ferna/OneDrive/CS50X Final Project/solelectric/index/routes.py",
	"owner": "_generated_diagnostic_collection_name_#3",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"flask\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 6,
	"endLineNumber": 1,
	"endColumn": 11
}]"

As if I'm trying to import Flask but haven't installed it. However, if I "flask run", everything works just fine.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (6.56GB free)|
|Process Argv|--crash-reporter-id 5b3a38a7-e48a-495c-b253-d14c660c68dc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|Memory (System)|7.62GB (6.32GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.66.3
mq4|ner|1.0.4
material-icon-theme|PKi|4.17.0
vscode-icons|vsc|11.11.0
material-theme|zhu|3.13.29
vscode-sqlite|ale|0.14.0
file-tree-to-text-generator|d-k|1.4.0
gitlens|eam|12.0.6
go|gol|0.33.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
sqltools|mtx|0.23.0
mq4|ner|1.0.4
material-icon-theme|PKi|4.17.0
vscode-icons|vsc|11.11.0
material-theme|zhu|3.13.29

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by roblourens** [comment]
Please file this on the pylance extension
