### ISSUE TITLE
Question: where is the column number computed?

### ISSUE THREAD

**Issue by eric-wieser** [microsoft/vscode#149933]
This isn't really an issue, but instead a request for development help

In https://github.com/microsoft/vscode/issues/91990#issuecomment-594430323, @alexdima said:
> Thank you for following through with your reply. This is working as designed. The indicator in > the status bar works in the following way:
> * for a tab character, it counts the number of spaces the tab was rendered with
> * for any other Unicode code point, it counts 1, regardless of the character font render width.

I'm trying to work out exactly how vscode is performing this counting, as the column/position reported in the status bar diverge from that reported with `Position`s in the extension API. So far I've found where the data on the status bar is coming from:

https://github.com/microsoft/vscode/blob/bd95a8d4516d590256eefecfce465a2f10e8f5e5/src/vs/workbench/browser/parts/editor/editorStatus.ts#L613-L615

Would someone be able to point to where this unicode and tab normalization occurs?

Thanks!

**Comment by alexdima** [comment]
This is where the column value displayed in the status bar is computed: https://github.com/microsoft/vscode/blob/a00e1380401cb64023272c189772563f2885e8ab/src/vs/editor/common/core/cursorColumns.ts#L57-L77
