### ISSUE TITLE
XDG portal dialogs not used (Linux)

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode#149909]
Issue Type: <b>Bug</b>

vscode does not use the XDG portal dialogs, but "other" dialogs.

This means, for instance, that on an X11 KDE Desktop, the KDE dialogs are not used, but "something else" (apparently GTK / Gnome).

On this very same system, Firefox happily makes use of the XDG portal dialogs.

The screenshot shows Firefox (right) with the "Portal" dialog (see the title bar!); on the left, notice vscode bringing up something different (i.e. not the XDG portal dialog).

![image](https://user-images.githubusercontent.com/3868036/169245313-22dc56c3-99f3-4997-abee-5911b0ef17c0.png)

Both the installation of vscode and firefox are "native" (i.e. not flatpak, snap or anything) on Fedora 36.

As firefox (and chrome) do the right thing, I suppose the environment is configured correctly; specifically I do have
```
env | grep -E '(DESKTOP|PORTAL)'

IMSETTINGS_INTEGRATE_DESKTOP=yes
DESKTOP_SESSION=plasmax11
XDG_SESSION_DESKTOP=KDE
XDG_CURRENT_DESKTOP=KDE
CHROME_DESKTOP=code-url-handler.desktop
GTK_USE_PORTAL=1
ORIGINAL_XDG_CURRENT_DESKTOP=KDE
```
Further, electron is said to have support for this (https://github.com/electron/electron/issues/2911) as of version 14; vscode currently uses electron 17. See also for details at https://tristan.partin.io/blog/2021/04/01/electron-linux-and-your-file-chooser/

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.17.7-300.fc36.x86_64
Restricted Mode: No

**Comment by shoffmeister** [comment]
Ah, and minutes later it is clear what the problem is:

The author of the electron patch has created a helpful blog entry https://tristan.partin.io/blog/2021/04/01/electron-linux-and-your-file-chooser/ in which he writes: "I open a handle to libgtk-3.so"

The linked commit https://github.com/electron/electron/commit/fa65faa4b0221dfd6e5d64abcff01321640a19ad confirms that.

That's all nice and dandy **_if_** the Linux installation actually **_has_** `libgtk-3.so`.

Well, Fedora 36 does not have `libgtk-3.so`. Fedora 36 ships
* `/usr/lib64/libgtk-3.so.0.2404.29`
* `/usr/lib64/libgtk-3.so.0 -> libgtk-3.so.0.2404.29`

Solution:
```
cd /usr/lib64
sudo ln -s libgtk-3.so.0 libgtk-3.so
```

**Comment by shoffmeister** [comment]
Request to vscode folks: You are well-connected to electron. 

May I kindly ask that you relay the problem with the test for `libgtk-3.so` to the electron people? I'd think that it would be useful / helpful / good / conservative to also check for `libgtk-3.so.0`

**Comment by shoffmeister** [comment]
https://begriffs.com/posts/2021-07-04-shared-libraries.html has some word on .so-versioning:

> Standard practice is to create symlinks libfoo.so -> libfoo.so.x -> libfoo.so.x.y.z in a shared system directory. The first link (without the version number) is for linking at build time.

So, according to that, ".so" plain should be expected only at _build_ time, not as delivered on an installed (distribution) Linux. To that extent, the electron patch possibly really should be amended.

**Comment by shoffmeister** [comment]
FYI https://github.com/electron/electron/issues/31258 on the electron side documents their discovery.

**Comment by deepak1556** [comment]
Addressed in https://github.com/electron/electron/commit/37b7e347fce555836d694f36f6ee5e2ea67db049
