### ISSUE TITLE
Upgrading a zip deploy and keeping settings/extensions

### ISSUE THREAD

**Issue by dmcquiston** [Microsoft/vscode#14997]
- VSCode Version: 1.6
- OS Version: Windows 7

This is more of a question regarding instructions on how to upgrade 1.6 to 1.7 or any version when you download as a zip? I don't need two copies of VS Code I just want to upgrade my existing version to a new version and keep all of the settings (user, extensions, etc.) that I have configured.

**Comment by joaomoreno** [comment]
None of the settings and extensions are stored within the application folder, so you can simply replace it.
