### ISSUE TITLE
Feature request: more complete git integration

### ISSUE THREAD

**Issue by andersennl** [Microsoft/vscode#150]
I've tried out this new editor and find it very promising. Looking at the git integration, here's a list of features that would add a ton of usefulness if being integrated into the git screen: (I hope I didn't overlook something)
- add `git pull --rebase` additionally to `git pull`
- add keyboard shortcuts and (easy reachable) buttons to quickly `stage` and `unstage` `lines` and `chunks` in `diff view`
- add `git log`, `project` wise, `branch` wise and `file` wise with easy to view commit `file changes`

**Comment by unional** [comment]
For record, `git log` currently provided by: https://marketplace.visualstudio.com/items?itemName=donjayamanne.githistory

**Comment by joaomoreno** [comment]
Most of these things are now in, keyboard shortcuts are customizable, etc. There's another issue for git log (history).
