### ISSUE TITLE
Visual tears and lagginess on 4K monitor

### ISSUE THREAD

**Issue by BenSandeen** [Microsoft/vscode#15005]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|python|donjayamanne|0.5.0|
|code-runner|formulahendry|0.4.1|
|Hg|jake-coltman|0.0.4|
|vscode-clang|mitaki28|0.2.1|
|csharp|ms-vscode|1.4.1|
|sublime-keybindings|ms-vscode|1.5.12|
|indent-rainbow|oderwat|0.4.1|
|clang-format|xaver|0.11.0|

---

Steps to Reproduce:

1. Using a very powerful laptop and a connected 4K monitor, start VS Code
2. Open a file and move the mouse around and scroll up and down (i.e.: interact with VS Code)

**Comment by rebornix** [comment]
Dup of #9432 .
