### ISSUE TITLE
Adding load without consultation

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#15009]
Highlighted by the NPM load issue introduced in 1.7.

Going forward, can the VS Code team please set the default for all background network activity to **OFF**. Or, have the update ask for user input for these setting when first run. The ability for extensions to write to user settings has already been added, this (on first load) is the best use for that functionality. I'm perplexed that the VS Code team themselves wouldn't use it.

I'm an advocate for this software, and a contributor to many extensions, but I'm seriously disappointed that the team has decided on behalf of the user community to start using a third party endpoint without telling (or preferably asking) the user first. It is wholly justifiable that NPM would be upset about it as well. I'm sure they would have liked to have been consulted.

**Comment by joaomoreno** [comment]
We won't have a single setting for tuning off all network activity. You already have individual settings to disable updates and telemetry.

**Comment by HookyQR** [comment]
I'm not asking for a setting to turn off all network activity.

You added **NEW** network activity, without any advice to the user. All I'm saying is, allow them to change the setting (`"typescript.disableAutomaticTypeAcquisition"`) when you add the functionality. All you have to do is ask the user what they want when you first include the setting. Stop assuming everyone wants a particular thing. It's why the setting was added right? Just don't set a default - ask.

You're not instilling confidence in the product, or the company.

**Comment by joaomoreno** [comment]
cc @egamma @chrisdias @waderyan @dbaeumer

**Comment by seanmcbreen** [comment]
Hi @HookyQR 

First off thanks for the feedback here - we have for sure learnt a few things throughout this process.  

Right now we are getting close to shipping an update to 1.7.1.  In an attempt to address a few of your points we are going to add a few clarifications in the release notes i.e. how to turn off, how it works.

That said I'd welcome a chance to chat w/ you about this - so if you are interested let me know I'm smcbreen at microsoft.com.  Drop me a line and we can have a quick chat/a quick call as that will probably make it easier to discuss details/ask clarifying questions.

Finally - thanks for the great work on the extensions you have created - the work on formatters in particular was a factor in our formatting related updates in 1.7.x and the marketplace!

Sean
