### ISSUE TITLE
dash `-` does not work inside code snippet choices

### ISSUE THREAD

**Issue by leifmarcus** [microsoft/vscode#150014]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Mac OSX 12.3

## Steps to Reproduce:

1. create a snippet with choices like the following
```json
{
"snippetName": {
    "scope": "scss",
    "prefix": "my-snippet",
    "body": ["@include anything-${1|my-value-1,my-value-2,my-value-3|};"],
    "description": "example snippet for demo purpose"
  },
}
```
2. Type `my-` inside any scss file and select the snippet and press enter.
3. The selection box is empty and the first item is displayed correctly.

## Expected behavior

The defined choices should be shown in the suggestion box.

**Comment by jrieken** [comment]
This looks like https://github.com/microsoft/vscode/issues/148976. Can you try if this issue reproduces with  with [VS Code Insiders](https://code.visualstudio.com/insiders/)? Thanks!

**Comment by leifmarcus** [comment]
@jrieken Thank you for reaching out. I tested the VS Code Insider and this problem seems to be fixed. Everything works as expected.

**Comment by jrieken** [comment]
Closing as /duplicate of #148976
