### ISSUE TITLE
node-debug module doesn't compare script_name with path correctly on Windows platform

### ISSUE THREAD

**Issue by nakosung** [Microsoft/vscode#1500]
vscode seems to handle 'drive-letter' in both small letter and capital letter, this makes some conflict while dealing with breakpoints.

I would like to PR for this bug fix, but I don't know where to contribute.

**Comment by nakosung** [comment]
I found vscode-node-debug and opened a PR there.

**Comment by nakosung** [comment]
re-opened to discuss here.

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-node-debug#30
