### ISSUE TITLE
The window has crashed (reason: 'oom', code:'-536870904')

### ISSUE THREAD

**Issue by pablosnascimento** [microsoft/vscode#150020]
Issue Type: <b>Bug</b>

When run train model machine learning algorithm. Yolov5

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (4.84GB free)|
|Process Argv|--crash-reporter-id 21f7849e-11c2-4787-923f-69bf38fc59e4|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
clojure|avl|0.13.1
vscode-pull-request-github|Git|0.42.0
continuum|jam|1.2.0
csharp|ms-|1.24.4
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by aeschli** [comment]
Can you give steps? You run a command in the terminal and VS Code crashes?

**Comment by pablosnascimento** [comment]
Yeap, when run the command:

`!python train.py --batch 16 --epochs 120 --data custom_data.yaml --weights yolov5s.pt --cache`

it run during 60 to 80min and crash. 
How can I save more detals?
