### ISSUE TITLE
Coffeescript syntax highlighting breaks when embedding JS code

### ISSUE THREAD

**Issue by pzuraq** [Microsoft/vscode#15008]
- VSCode Version: 1.7.0
- OS Version: 10.11.6

Steps to Reproduce:

1. Create a coffeescript file
2. Paste the following into the file:

```
`import foo from './foo'`

bar = (baz) -> console.log(baz)
```

`bar...` will be highlighted as if it were embedded javascript. If a semicolon is added to the end of the embedded statement, then the syntax highlighting works correctly:

```
`import foo from './foo';`
```

**Comment by aeschli** [comment]
This issue was moved to textmate/coffee-script.tmbundle#12
