### ISSUE TITLE
GitHub Pull Request always ask for authentication

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#150060]
Issue Type: <b>Bug</b>

The Avatar badge always shows `1`

<img width="351" alt="image (7)" src="https://user-images.githubusercontent.com/876920/169617615-6c8a8f0d-7369-4660-b0b4-db057b596b05.png">

Clicking the action to authenticate doesn't dismiss it.

VS Code version: Code - Insiders 1.68.0-insider (17c75e11805103026b943c8dc4d50a35f245f76f, 2022-05-20T05:16:17.334Z)
OS version: Windows_NT x64 10.0.22616
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (11.46GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
kusto|don|0.3.8
gitlens-insiders|eam|2022.5.1705
prettier-vscode|esb|9.5.0
codespaces|Git|1.8.1
copilot|Git|1.22.5957
vscode-pull-request-github|Git|0.42.0
go|gol|0.33.0
vscode-language-pack-zh-hans|MS-|1.68.0
python|ms-|2022.7.11401005
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.5.1001421011
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-ai|ms-|0.11.2022052009
vscode-ai-remote|ms-|0.13.2022052009
remote-containers|ms-|0.236.1
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.6
js-debug-nightly|ms-|2022.5.1817
live-server|ms-|0.2.12
vscode-github-issue-notebooks|ms-|0.0.119
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.9
vsliveshare|ms-|1.0.5561
vetur|oct|0.35.0
colab-keymap|reb|0.0.4
github-issue-notebook-enhancement|reb|0.0.1
vscode-code-renderer|reb|0.0.2
vscode-jupyter-checkpoint|reb|0.0.1
notification-tester|svi|2.5.1
rest-book|tan|6.0.1
tldraw-vscode|tld|1.13.3
shell-runner-notebooks|tyl|0.0.2
luna-paint|Tyr|0.14.0
vscode-todo-highlight|way|1.0.5

(3 theme extensions excluded)

</details>

**Comment by TylerLeonhardt** [comment]
@rebornix after reloading, does the `(1)` go away?

**Comment by misolori** [comment]
Reloading fixes the issue for me
