### ISSUE TITLE
Add support for long watch expressions

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode#150081]
Add support for watch expression wrapping when the watch expression is consuming more space than the container. 

![image](https://user-images.githubusercontent.com/7471994/169646569-4deb3d27-db82-4448-906c-8fe9b9114a5a.png)

One way is to improve the layout of expression and value to make sure expression doesn't render beyond a certain portion of the container. But this introduce a challenge on how to see the full expression since current hover only shows details about the value.

Another more simple way is to introduce scrolling for such situation horizontally. The UX might not be really good, but its less complex solution to handle such edge cases.

**Comment by roblourens** [comment]
You can enable horizontal scrolling with `workbench.list.horizontalScrolling`. Note that some trees in vscode will handle this better than others. Does that help?

I could make it wrap although it would be a lot of work. You can hover to see the full expression, would it help if the tooltip for the left side also contained the value?

**Comment by gayanper** [comment]
Yes i can try the suggestion of horizontal scrolling.  The tooltip suggestion will also solve the issue as well. I think that is a much better solution that wrapping if it’s possible
