### ISSUE TITLE
Add option to disable searching in open editors in Find in Files searches

### ISSUE THREAD

**Issue by kkaja123** [microsoft/vscode#150032]
Right now, the Find in Files search can search in the open editors and it can search in the "files to include" selection. There's one option to *only* search in open editors. An option to *only* search in the "files to include" selection should be added (or alternatively, it could *ignore* the open editors).

Without this option, the search tool always searches in open editors, unless the open editor's file matches a "files to exclude" pattern. This could be confusing to some users, since the search window doesn't make it immediately clear that open editors are implicitly included in search results. In the case that the open editor file doesn't match the patterns in "files to include", users may think that their patterns are faulty (it took me a long time to figure out why a `.txt` file was showing up in my search results). An option that explicitly shows that the open editors can be excluded or that only includes the "files to include" matches in the search results would make this clearer.

(Note: I experienced this shortcoming in a multi-root workspace, so I don't know if that has a specific effect on the Find in Files behavior. Another strange behavior is that Find in Files only searches the open editors that have been "loaded". By "loaded", I mean that the editor has actually read the file on the disk and has displayed the contents. When the VSCode window is reloaded, the files of editor tabs are not immediately loaded. Instead, they are loaded when they are clicked on and viewed for the first time. This means that on reloads, the Find in Files search will not include those not-loaded-but-seems-like-it-would-be editors. This seems like it could further user confusion if results start to randomly appear when they didn't before with the same search settings.)

**Comment by roblourens** [comment]
Yes, sorry for the confusion. This is https://github.com/microsoft/vscode/issues/31819
