### ISSUE TITLE
Clickable file(+line number) in 'Debug Console' (for C#)

### ISSUE THREAD

**Issue by EdwinVanRooij** [microsoft/vscode#150023]
It would be greate to allow C# (and possibly other languages) developers to click a filename+line number combination to immediately navigate the cursor to the file and line within the file, e.g.:

![image](https://user-images.githubusercontent.com/16732313/169529098-926597cc-24fe-4f8c-873d-20b4cd27cf61.png)

Detecting the pieces of text which should be clickable should be fairly simple, maybe with this regex: 
```regex
\\[A-Za-z]+\.(cs|css|js)\:line\s[0-9]+$
```

Here it is in action (regex101.com):

![image](https://user-images.githubusercontent.com/16732313/169529290-b374661b-5737-416e-a8c2-d2ccbb8c8447.png)

My current workflow is to execute these steps to get to the file in question:
1. Search for the filename and line number where the problem occurs
2. Copy the filename
3. Remember the line number
4. Navigate to the file
5. Scroll to the line number

With this feature, it can be reduced to:
1. Search for the clickable links (easier if it'd be highlighted in another color)
2. (Control+) click it

---

Edit: If this is not something the maintainers of this repository would like to have in the standard VS Code distribution, would it be possible for me to create an extension for it? If so, any pointers would be appreciated!

**Comment by roblourens** [comment]
There are some issues with link detection in the debug console, I have this issue for that https://github.com/microsoft/vscode/issues/34026
