### ISSUE TITLE
GitLab "Open in VSCode (SSH)" no longer functional

### ISSUE THREAD

**Issue by kaedenbrinkman** [microsoft/vscode#150097]
Issue Type: <b>Bug</b>

In GitLab, you can click a button to directly open a repository in VSCode (vscode:// URI). Several weeks ago this appears to have stopped working. If VSCode is closed clicking the button in GitLab seemingly does nothing - but Task Manager shows several instances of VSCode opening. If VSCode is already open nothing appears to happen. I have tried disabling all extensions and the issue still occurs.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (9.36GB free)|
|Process Argv|--crash-reporter-id 3338bb23-4c9f-4785-92c6-71876f179bc2|
|Screen Reader|no|
|VM|50%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by lszomoru** [comment]
@kaedenbrinkman, this has been a regression that was introduced when we added URI validation for the git clone protocol handler. The regression has been fixed in the latest Insiders release (2022-06-17). Could you please download the Insiders release and test that the bug has been fixed? Thanks!
