### ISSUE TITLE
Keyboard Freeze

### ISSUE THREAD

**Issue by blueray453** [microsoft/vscode#150076]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Zorin Core 16.1 

The issue is similar to https://github.com/Microsoft/vscode/issues/67944

When I start working with the editor the keyboard suddenly stop working. The keyboard does not work inside or outside vscode. The mouse works. I am attaching a screenshot of  'Help > Report Issue' as I could not type. Just to be clear, it is without any extensions (fresh install).

![1](https://user-images.githubusercontent.com/855297/169642198-65d558f4-d031-4a00-aad3-45c8e8c66ddb.png)

Steps to Reproduce:

1. Start the editor and keep working. After some time the bug will show up.

**Comment by blueray453** [comment]
Just to be clear it happens with Linux Mint latest as well. This has been happening for a long time now (at least last 3-4 months). So, this is not a current version of vscode issue. Earlier I thought it was related to my Linux distribution. So, I changed it to Zorin. I also changed my keyboard. 

No other heavy process was running (only Firefox) when I had CPU Load Average 2,2,1

**Comment by deepak1556** [comment]
Can you try with latest insiders https://code.visualstudio.com/insiders and see if the issue persists.

**Comment by blueray453** [comment]
The issue is not there anymore. It was a hardware issue (faulty data cable).
