### ISSUE TITLE
Cloning not working

### ISSUE THREAD

**Issue by kingma-sbw** [microsoft/vscode#150024]
Issue Type: <b>Bug</b>

On a fresh installed vscode cloning does not respond. See video

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (2 x 2803)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.72GB (1.16GB free)|
|Process Argv|--crash-reporter-id 0161f9d4-03a7-4899-859d-13c481db07ca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-intelephense-client|bme|1.8.2
doxdocgen|csc|1.4.0
EditorConfig|Edi|0.16.4
classroom|git|0.0.3
copilot|Git|1.22.5957
vscode-pull-request-github|Git|0.42.0
live-sass|gle|5.4.0
vscode-dependency-cruiser|jua|0.0.1
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
vsliveshare-audio|ms-|0.1.91
vetur|oct|0.35.0
phpdoc-comment-vscode-plugin|rex|1.3.0
LiveServer|rit|5.7.5
vscode-javascript-booster|sbu|14.0.1
markdown-preview-enhanced|shd|0.6.3
sass-indented|syl|1.8.19
vscode-counter|uct|3.0.4
region-highlighter|Wie|1.0.1
php-debug|xde|1.26.1
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

https://user-images.githubusercontent.com/50140049/169529668-dff53e1d-b161-444e-b5cb-cd863b265560.mp4

After cancelling this appears:
![image](https://user-images.githubusercontent.com/50140049/169530535-ecc4b1f5-2f7d-476a-8dd5-8af928342bcb.png)

But not always

**Comment by kingma-sbw** [comment]
That would be this
```
[Info  - 14:23:49.717] Reading sessions from keychain...
[Info  - 14:23:50.355] Getting sessions for all scopes...
[Trace  - 14:23:50.356] Token acquired from secret storage.
[Info  - 14:23:50.356] Got stored sessions!
[Trace  - 14:23:50.356] Read the following session from the keychain with the following scopes: repo workflow
[Trace  - 14:23:50.356] Read the following session from the keychain with the following scopes: read:user repo user:email workflow
[Info  - 14:23:50.356] Got 2 verified sessions.
[Info  - 14:23:50.356] Got 2 sessions for ...
[Info  - 14:23:50.366] Getting sessions for read:user,repo,user:email,workflow...
[Info  - 14:23:50.368] Got 1 sessions for read:user,repo,user:email,workflow...
[Info  - 14:23:50.746] Getting sessions for user:email...
[Info  - 14:23:50.747] Got 0 sessions for user:email...
[Info  - 14:23:50.754] Getting sessions for all scopes...
[Info  - 14:23:50.754] Got 2 sessions for ...
[Info  - 14:23:52.565] Getting sessions for read:user...
[Info  - 14:23:52.565] Got 0 sessions for read:user...
```

**Comment by TylerLeonhardt** [comment]
@lszomoru the auth logs look ok to me. I don't think it's the problem here.

One thing I'm suspicious of is that this is an empty GitHub repo as I know GitHub treats those lazily (it doesn't actually initialize the repo until first commit or something)

Codespaces and RemoteHub have failed to handle this gracefully in the past...

Maybe this is another case of that? Is there a GitHub Output channel that would have useful info?
