### ISSUE TITLE
Capture replacement fails for global search and replace

### ISSUE THREAD

**Issue by lerwine** [microsoft/vscode#150070]
Issue Type: <b>Bug</b>

1. From VS Code, do Ctrl+Shift+F to open Search and Replace in primary side bar.
2. In the regex pattern text box, enter the pattern `(using [^:]+; *)(\r\n|\n)(?=namespace)`
3. In the replacement text box, enter `$1$2$2`
In the replacement results, it should replace `$1` with the statement captured in the first group, and each `$2` should contain the captured line break character sequence. However, it is actually replaced with the literal `$1$2$2` charcters.

![UsingPositiveLookahead](https://user-images.githubusercontent.com/6179909/169634955-69ad73e6-ba62-4481-8f5d-354c219b7392.png)

If I use a negative look-ahead rather than a positive look-ahead, such as `(using [^;]+; *)(\r\n|\n)(?!using|[\r\n\s])`, then it replaces the capture groups as expected. However, this not an optimal regex pattern, since it matches more than just the "using" namespace statements (such as the "using" statements for IDisposable classes).

![UsingNegativeLookahead](https://user-images.githubusercontent.com/6179909/169634932-13c3f06c-9af0-4f9d-a17b-5f1363129845.png)

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1155G7 @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.76GB (3.48GB free)|
|Process Argv|--crash-reporter-id d48414d3-e3fe-4977-9f4b-2a7394c9c24c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
toggle-hidden|adr|1.0.2
user-secrets|adr|2.0.1
project-manager|ale|12.5.0
devmate|Aut|1.0.1
path-intellisense|chr|2.8.0
gitignore|cod|0.7.0
vscode-markdownlint|Dav|0.47.0
netcore-editorconfiggenerator|dog|0.1.1
netcore-extension-pack|dog|1.7.0
netcore-snippets|dog|3.15.2
quicktype-refresh|dog|1.0.2
git-extension-pack|don|0.1.3
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.0.6
vscode-html-css|ecm|1.12.2
EditorConfig|Edi|0.16.4
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.7
vscode-nuget-package-manager|jmr|1.1.6
vscode-csharp-snippets|jor|1.1.0
docomment|k--|0.1.31
csharpextensions|kre|1.7.0
file-downloader|min|1.0.12
csharp|ms-|1.24.4
powershell|ms-|2022.5.1
vscode-nuget-gallery|pat|0.0.24
vscode-versionlens|pfl|1.0.10
msbuild-project-tools|tin|0.4.3
vscode-todo-highlight|way|1.0.5
vscode-open-in-github|ziy|1.3.6
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by roblourens** [comment]
This is essentially covered by https://github.com/microsoft/vscode/issues/128134
