### ISSUE TITLE
i can't execuite cpp codes

### ISSUE THREAD

**Issue by Jayakrishna112** [microsoft/vscode#150091]
Issue Type: <b>Feature Request</b>

there are no settings.josn

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by BixinFromThisRealm** [comment]
Hello!

VS Code wasn't *really* made with C or C++ in mind, so it doesn't have support for these, the most that you can get is some basic syntax highlighting. If you are looking for a more feature-complete, bulky C++ IDE, consider switching to [Visual Studio](https://visualstudio.microsoft.com/), or [Code::Blocks](https://www.codeblocks.org/).

However, if you still want to stick with VS Code there is a really good [C/C++](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) [extension](https://code.visualstudio.com/docs/editor/extension-marketplace) developed by Microsoft themselves. It doesn't come with a compiler though, so no executing projects, you will have to install one separately. I suggest [MinGW](https://www.mingw-w64.org/), which is a port of the [GNU Compiler Collection](https://pt.wikipedia.org/wiki/GNU_Compiler_Collection) for Windows, the C++ compiler in it is g++, so compiling is done by typing in the terminal `g++ filenamehere.cpp`.

Regarding settings.json, you can access it via the command pallet (`Ctrl+Shift+P`), just type "settings.json" there and you will find it.

**Comment by sandy081** [comment]
Please read this - https://code.visualstudio.com/docs/languages/cpp
