### ISSUE TITLE
Select Multiple file versions to compare

### ISSUE THREAD

**Issue by SajinPrince** [microsoft/vscode#150095]
Coming from A visual studio 2022 background Is it possible to add this Feature in VSCODE.
When you right click on a file in the project Explorer you view git history it  displays all the commits for that file only, You can hold the CTRL key and select any two versions  of the file to compare changes. VS CODE does not  let you  hold ctrl and  select specific versions to compare

![image](https://user-images.githubusercontent.com/46758679/169667460-de4a828e-fd4a-4fa7-b5b3-0f24d66d654f.png)

![CompareExample](https://user-images.githubusercontent.com/46758679/169667483-2f890e56-19c6-4b0a-bb8a-9398e938bf1c.JPG)

**Comment by gjsjohnmurray** [comment]
Did you find the Timeline View? If not, try using the Command Palette to `Focus on Timeline View`.

In that view you can use the context menu on a commit the `Select for Compare`, then on another commit to `Compare with Selected`.
