### ISSUE TITLE
Add 'explorerFocus` for keybinding `when` context

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#15002]
Atom provides keyboard shortcuts such as <kbd>a</kbd> and <kbd>shift</kbd>+<kbd>a</kbd> when in the file explorer context. As far as I can tell we do not have an `explorerFocus` value for `when`, when defining keybindings. This would be needed to implement user request [here](https://github.com/waderyan/vscode-atom-keybindings/issues/4#issuecomment-258022248). 

What we want to do is add something like this to the Atom Keymap extension. 

```json
{
    "mac": "a",
    "win": "a",
    "linux": "a",
    "key": "a",
    "command": "workbench.files.action.createNewFile",
    "when": "explorerFocus"
},
{
    "mac": "shift+a",
    "win": "shift+a",
    "linux": "shift+a",
    "key": "shift+a",
    "command": "workbench.files.action.createNewFolder",
    "when": "explorerFocus"
}
```

**Comment by alexandrudima** [comment]
The explorer hasn't fully adopted our keybindings story and at this point not all keybindings are customizable in there (e.g. `F2`).

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by waderyan** [comment]
@bpasero can you point the issue out to me? I did do a search but it looks like I can't find it. Its not easy to find related issues :)

**Comment by waderyan** [comment]
Maybe this one - https://github.com/Microsoft/vscode/issues/4557

**Comment by bpasero** [comment]
@waderyan thats it. sorry, I did not want to treat you any more special than I do any other user ;)

**Comment by bpasero** [comment]
I added new contexts that can be used to assign keybindings that only work when explorer or open editors have focus:
* `explorerFocus`
* `openEditorsFocus`

**Comment by waderyan** [comment]
Awesome!

**Comment by isidorn** [comment]
Does not work for me, my example:

```
{
            "key": "cmd+e",
            "command": "workbench.action.quickOpen",
            "when": "explorerFocus"
      },
```

**Comment by bpasero** [comment]
@isidorn sorry, the context key is: `explorerViewletFocus`

**Comment by isidorn** [comment]
@bpasero no worries, works now
