### ISSUE TITLE
issues using the new FileNesting feature 

### ISSUE THREAD

**Issue by farukg** [microsoft/vscode#150028]
Issue Type: <b>Bug</b>

I added 
```json
  "explorer.fileNesting.patterns": {
    "*.re": "${capture}.bs.js",
  }
```
and file nesting works as expected, but in collapsed state pressing F2 (my rename shortcut) on `Entry.re` i get ´TreeError [FileExplorer] Data tree node not found: ExplorerItem: Entry.bs.js´
<img width="466" alt="image" src="https://user-images.githubusercontent.com/1577842/169542030-75563331-0c86-4a42-a6cd-314db84f5fbb.png">

Only when not collapsed Im able to rename.

Edit: I just restart with all extensions disabled and the issue is still present.

VS Code version: Code - Insiders 1.68.0-insider (17c75e11805103026b943c8dc4d50a35f245f76f, 2022-05-20T05:16:17.334Z)
OS version: Windows_NT x64 10.0.25120
Restricted Mode: No
Remote OS version: Linux x64 5.17.8-mashalla-FG-own-built-linux-on-WSL2-dirty

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.83GB (17.22GB free)|
|Process Argv|--log off --log off|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.17.8-mashalla-FG-own-built-linux-on-WSL2-dirty|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (10 x 2592)|
|Memory (System)|21.51GB (17.03GB free)|
|VM|0%|
</details><details><summary>Extensions (69)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-custom-css|be5|6.0.2
vscode-toggle-quotes|Bri|0.3.6
postcss|css|1.0.9
LogFileHighlighter|emi|2.15.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
helium-icon-theme|hel|1.0.0
output-colorizer|IBM|0.1.2
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.16
dotenv|mik|1.0.1
remote-wsl|ms-|0.66.3
vscode-intellij-recent-files|per|1.1.1
multi-command|ryu|1.5.1
code-settings-sync|Sha|3.4.3
windows-terminal|Tyr|0.7.0
errorlens|use|3.5.0
highlight-matching-tag|vin|0.10.1
better-comments|aar|3.0.0
codesnap|adp|1.3.4
TabOut|alb|0.2.1
CustomColoring|Alt|1.4.4
conflict-squeezer|ang|1.0.1
convert-selection|Art|0.0.21
unique-lines|bib|1.0.0
vscode-toggle-quotes|Bri|0.3.6
rescript-vscode|che|1.3.0
npm-intellisense|chr|1.4.1
path-intellisense|chr|2.8.0
postcss|css|1.0.9
gitlens-insiders|eam|2022.5.1705
vscode-command-runner|edo|0.0.122
vscode-npm-script|eg2|0.3.25
LogFileHighlighter|emi|2.15.0
prettier-vscode|esb|9.5.0
vscode-highlight|fab|1.6.0
vscode-todo-plus|fab|4.18.4
vscode-graphiql-explorer|far|1.3.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-graphiql-explorer|Gab|1.3.1
vscode-rescript-relay|Gab|0.11.0
vscode-graphql|Gra|0.4.4
helium-icon-theme|hel|1.0.0
output-colorizer|IBM|0.1.2
monkey-patch|ioc|0.1.16
path-autocomplete|ion|1.19.1
reason-vscode|jar|1.8.14-fg
dupchecker|jia|0.1.7
custom-local-formatters|jki|0.0.6
vscode-colorize|kam|0.11.1
vscode-search-everywhere|kby|1.2.2
better-package-json|ldd|0.2.1
quick-switch|Lia|1.11.0
dotenv|mik|1.0.1
intellij-merge-tool|nom|0.0.1
ocaml-platform|oca|1.10.3
indent-rainbow|ode|8.3.1
explorer-exclude-vscode-extension|Red|1.2.0
vscode-sort-json|ric|1.20.0
multi-command|ryu|1.5.1
vscode-commentlinedown|sha|0.0.4
sort-json|Thi|8.0.0
better-search|tra|0.0.6
sort-lines|Tyr|1.9.1
errorlens|use|3.5.0
highlight-matching-tag|vin|0.10.1
change-case|wma|1.0.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
pythonvspyt200:30323110
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
pythonvspyt640:30438691
vscscmwlcmt:30465136
cppdebug:30492333
vsclangdf:30492506

```

</details>

**Comment by JacksonKearl** [comment]
Thanks, this seems to require `"explorer.fileNesting.expand": false`

**Comment by farukg** [comment]
> "explorer.fileNesting.expand": false

oh yes, i missed that, i had this setting set to false, thx for the impressive fast response and even fix 🚀 🤩

**Comment by farukg** [comment]
Hi @JacksonKearl ,
I tested the fix on the latest insiders version and found that it works good. But I also found a new case:
when I mark a collapsed file and press `ctrl+c` (copy) then i get the same error `TreeError [FileExplorer] Data tree node not found: ExplorerItem: ...`
Please let me know if i should have opened a new issue or post more details, if so I'm happy to do so 😄
