### ISSUE TITLE
Comments API: reply editor should not auto-close brackets unconditionally

### ISSUE THREAD

**Issue by hermannloose** [microsoft/vscode#150003]
When replying to a code review comment, the reply editor unconditionally auto-closes brackets. We have had complaints from users about `editor.autoClosingBrackets` not affecting this behavior (when set to `never`). We are not 100% convinced that `editor.autoClosingBrackets` *should* apply here, since conceptually, editing comments is different from editing code, so a separate setting for comments could be more flexible, but maybe also unnecessarily complex.

#145384 discusses specifying a `language` on `CommentController` to control other behavior like syntax highlighting (mainly plaintext vs Markdown). Since `editor.autoClosingBrackets` already supports using per-language settings, it might work well enough to just make `editor.autoClosingBrackets` also take effect in the comment reply editor.

**Comment by alexr00** [comment]
@hediet it seems that `"editor.autoClosingBrackets": "never"` only applies to the main editor and not also other editors. Is this expected? I took a look and from what I can see all `CodeEditorWidget` will respect language configurations for auto closing pairs. It's only when you try to set it something other than `languageDefined` that it get's ignored.

**Comment by hediet** [comment]
I don't know much about that setting, I'd need to debug too.

**Comment by alexdima** [comment]
@alexr00 To allow for most flexibility, the code editor doesn't listen to the `IConfigurationService` by itself. That job is always left to the place which instantiates editors. For example, the workbench listens to the `IConfigurationService` and forwards all `editor.*` values to the editor instaces.
