### ISSUE TITLE
Perl Syntax Highligting: Multi-line Logical Defined-Or operator corrupts highlighting for rest of file

### ISSUE THREAD

**Issue by perilstar** [microsoft/vscode#150040]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows 11

Steps to Reproduce:

1. Create a file with the extension .pl
2. Paste in the following code:
```perl
#!/usr/bin/perl

use feature 'say';

my $abc;
$abc //= 1;
# This bit looks right
say "\%abc: $abc";

my $xyz;
$xyz
  //= 1;
# This is coloured incorrectly
say "\%xyz: $xyz";
```

**Comment by perilstar** [comment]
Wow, it seems to be an issue in GitHub markdown highlighting too.

**Comment by alexr00** [comment]
Upstream issue: https://github.com/textmate/perl.tmbundle/issues/29
