### ISSUE TITLE
It is not autocompleting my html syntax 

### ISSUE THREAD

**Issue by binayak-tech** [microsoft/vscode#150051]
I am currently working on a django project but now vs code in not auto completing my html css syntaxes.  for eg h3 is not auto converted to 
`<h3></h3>`

but it is working completely fine on my other projects

**Comment by aeschli** [comment]
Do you use a Django extension? There are Django extensions that take over the HTML language mode, so the HTML extension is no longer active and you no longer get features like completions.
To test this, run VS Code with all extension disabled and try again.

The expandsion of `h3` to `<h3></h3>` is driven by emmet. You might solve the problem by configuring `emmet.includeLanguages`.
