### ISSUE TITLE
New Typescript grammar has alot of inconsistencies in the Dark+ theme

### ISSUE THREAD

**Issue by linusbrolin** [Microsoft/vscode#15001]
- VSCode Version: 1.7
- OS Version: Windows 10

Steps to Reproduce:

1. create a new typescript .ts file.
2. write the text according to the screenshot.

The new Typescript grammar and/or Dark+ theme has alot of inconsistencies.

- Some function calls are green and some are yellow. (I think it's the 'support.class' scope that makes some 'support.function''s green.)
- Some variables are light blue and some are green. (I think it's the 'support.class' scope that makes some 'support.variable''s green.)
- In arrays, constants are uncolored but variables are colored.
- Code inside a Promise has wrong syntax highlighting. For example 'let' is green, and the arrow '=>' is green.
- 'console.log', 'console.dir', etc is completely green, why?
- It's pretty much light blue everywhere, since all variables, parameters, interface keys, variablename.variablename2.variablename3, etc are light blue.
This makes almost all text light blue, which is not an improvement.
It would be better if a base variable is light blue, but all member keys in that base variable are either uncolored or have another color shade.

![image](https://cloud.githubusercontent.com/assets/3481784/20013979/75ed631c-a2b5-11e6-9dbc-da8e09303dfc.png)

**Comment by rebornix** [comment]
Dup of #14921.
