### ISSUE TITLE
jsconfig.json "files" not working

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#15003]
- VSCode Version: 1.7
- OS Version: Windows 10

I have the following `json` file:

```json
{
    "compilerOptions": {
        "target": "es6"
    },
    "files": [
        "dist/js/main.d.ts"
    ]
}
```

When I go to edit a javascript file, I would suspect that the autocompletion would work in my `.js` file, but it does not. In order for me to get autocompletion I have to put this at the top of the file:

```js
/// <reference path="../../dist/js/main.d.ts"/>
```

Am I doing something wrong here?

Without the reference (Should grab from `jsconfig.json`):

![no-suggest](https://cloud.githubusercontent.com/assets/1571806/20018254/037f56e8-a295-11e6-9e54-857d1e32c7fc.png)

With the reference:

![suggest](https://cloud.githubusercontent.com/assets/1571806/20018255/03807992-a295-11e6-8bf2-2ca5c0c8b0cd.png)

Here is the tree of the project

![no-suggest-tree](https://cloud.githubusercontent.com/assets/1571806/20018434/ac428e12-a295-11e6-8865-b224e9f34907.png)

Not sure if it matters, but my project is a mix of javascript and typescript. The javascript contains test files to test the typescript.

**Comment by waderyan** [comment]
Thank you for opening this issue. Can you share your workspace? 

From what I know about your project right now, you likely need to do the following:
1. Use only `tsconfig.json` and set `allowJs` to true
2. Add additional files to the `files` attribute. This attribute is meant to include all the files for your JavaScript project.  I would suggest switching from `files` to using `exclude` and then excluding the files you don't want as shown below. 

```
{
    "compilerOptions": {
        "target": "es6"
    },
    "exclude": [
        "dist"
    ]
}
```

Documentation for [tsconfig](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

**Comment by TheColorRed** [comment]
@waderyan The workspace can be found on github here: https://github.com/TheColorRed/web-framework

**Comment by waderyan** [comment]
This is working for me in the latest insiders build (you can download that [here](https://code.visualstudio.com/insiders)). 

![image](https://cloud.githubusercontent.com/assets/2449568/20849972/f051b656-b88d-11e6-85dc-91761dbfc461.png)

I recommend you follow the practices I outlined in my above comment.
