### ISSUE TITLE
"Are you sure you want to install deprecated extension" dialog should offer third option if there is an alternative

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150005]
1. VS Code, search for "bracket pair colorizer"
2. Notice how it is nicely rendered as deprecated
3. Click on install -> notice dialog

The dialog should offer a third button to configure built-in settings instead.
Same if an extension had an alternative extension. Example: 

![Screenshot 2022-05-20 at 10 20 09](https://user-images.githubusercontent.com/1926584/169486420-16c7e3ce-3d72-4f69-93ed-803172ffacb9.png)

fyi @hediet

**Comment by gjsjohnmurray** [comment]
@isidorn I assume you want the extra button to replicate this link in the hover tip, right?

![image](https://user-images.githubusercontent.com/6726799/169488428-0a11184a-50e2-4824-9f89-45a6e946e580.png)

As an aside, any doc yet about how an extension gets tagged as deprecated?

**Comment by isidorn** [comment]
@gjsjohnmurray yes, a button that will replicate that behaviour correct.

No docs yet written. I plan to add them soon. The process is to write an email to us or to ping us on GitHub. In the future we will have a more straightforward approach when MP adds UI.

**Comment by sandy081** [comment]
I feel, the third option would be a general options like  More Information... clicking on this shall open the extension editor. This will be consistent and useful so that user will get enough info before taking an action

**Comment by isidorn** [comment]
"More Information..." might work, but in order to have one less hop we could render:
* "Install EXTENSION_NAME Instead"
* "Enable Native Settings Instead"

That would just do the action right straight away.
I am not sure if those button names are too long.

So just a suggestion. Whatever you prefer...

**Comment by sandy081** [comment]
Yah I see your point, but going to extension editor gives user more information and an opportunity to look at the alternative extension before installing. And also I do not like that this button changes with extension. More Information... would be consistent.

**Comment by isidorn** [comment]
That's fair. We can start with your proposal and see how it goes.
My only concern with "More Information" is that the user might think it is more information about the deprecation. While we actually want to guide the user to a solution. So it is something like "More about the alternative". I am not sure if there is a good button label to represent this.

**Comment by sandy081** [comment]
<img width="308" alt="image (1)" src="https://user-images.githubusercontent.com/10746682/169895608-dacf92cd-848f-4fed-a209-c5daf9996f36.png">

**Comment by sandy081** [comment]
Changed the second button as follows

![image](https://user-images.githubusercontent.com/10746682/170049068-14ad9df2-824e-4510-8407-51a59c3e1261.png)


![image](https://user-images.githubusercontent.com/10746682/170048516-7f6ae20f-3bfc-4a6e-a3e5-57fe91bd27a6.png)

**Comment by isidorn** [comment]
Awesome!!
