### ISSUE TITLE
Getting invalid.illegal.name.python on valid python code from textmate

### ISSUE THREAD

**Issue by Bobronium** [microsoft/vscode#150199]
Issue Type: <b>Bug</b>

in `42and 2`, a valid python code, `42and` is marked as `invalid.illegal.name.python`
<img width="519" alt="image" src="https://user-images.githubusercontent.com/36469655/169860770-9ad0be02-277c-4f39-8dab-073d7d2eb238.png">

`42` should be marked as `constant.numeric.dec.python` and `and` should be marked as `keyword.control.flow.python`.

**Additional info:** semantic token highlighting is enabled and working as expected.

PyCharm is able to parse it correctly:
<img width="181" alt="image" src="https://user-images.githubusercontent.com/36469655/169860939-1991c1b2-10ca-49de-9341-52f13ab62a1e.png">

Output from inspector:
```
language	python
standard token type	Other
foreground	#BC3F3C
background	#2B2B2B
contrast ratio	2.64
textmate scopes	invalid.illegal.name.python
meta.function-call.arguments.python
meta.function-call.python
source.python
```

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

**Comment by alexr00** [comment]
I can also repro this. Moved to the repository that we get our python syntax highlighting grammar from: https://github.com/MagicStack/MagicPython/issues/252
