### ISSUE TITLE
Clearing the test explorer filter doesn't persist across sessions 

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#150120]
Does this issue occur when all extensions are disabled?: Yes with the exception for the Deno extension

Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0

**Steps to Reproduce**

1. Install an extension that makes use of the test explorer
2. Type some text in the test explorer filter
3. Remove the filter text
4. Restart VSCode

**Expected result**

The filter field stays empty after restart

**Actual result**

The filter field contains the text last entered before clearing it.

https://user-images.githubusercontent.com/2737650/169699248-e903c596-54c2-4f59-b031-749004384b0b.mov

Note that while I have tested this with all extensions disabled. I wasn't able to test without leaving the Deno extension enabled since I'm using this for running tests. I also wasn't able to quickly verify if other testing extensions show similar behaviour.
I'm not familiar with the test explorer api but I'm assuming filtering is done outside of this api, which is why I'm reporting this here first.

**Comment by taschmidt** [comment]
For anyone else annoyed by this, I got around it by just nuking my %CODEDIR%/User/workspaceStorage folder.

**Comment by amunger** [comment]
verified that the filter content is cleared after a reload, but I'm also hitting https://github.com/microsoft/vscode/issues/156127
