### ISSUE TITLE
Open file/folder dialog (linux)

### ISSUE THREAD

**Issue by DmitryAstafyev** [microsoft/vscode#150159]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```
code -v
1.67.2
c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
x64
```
- OS Version:
```
uname -a
Linux sunshinenet 5.15.40-1-lts #1 SMP Sun, 15 May 2022 19:07:59 +0000 x86_64 GNU/Linux
ArchLinux x64
Gnome 42.1
```

Steps to Reproduce:

1. Open vscode
2. Top menu / File / Open File - select some file or cancel (no matter)
3. Try again p.3

Bug:
Only the first time opening file/folder dialog will be shown correctly. Each next time it will show push-notification and dialog would not be focused.

![Screenshot from 2022-05-23 09-25-00](https://user-images.githubusercontent.com/12843747/169766849-3ea92527-f647-424b-92bb-152e52d434ef.png)

I'm pretty sure, it's related to: https://github.com/electron/electron/issues/20025

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
