### ISSUE TITLE
A weird solid border when hovering over classes

### ISSUE THREAD

**Issue by xshapira** [microsoft/vscode#150125]
After updating to the newest VS Code version, weird solid border springs when hovering over classes. I reverted to 1.66 and it seems to fix the issue.

**Steps to Reproduce:**

1. Open an HTML file
2. Hover over any class

![js-tailwind-playground-1653235025823](https://user-images.githubusercontent.com/48856190/169705052-db0bdc14-34ce-4744-9687-5abb103aa263.gif)

**Comment by xshapira** [comment]
**Quick update:** Reverting to the previous version doesn't help.

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to check whether this is being caused by an extension.

**Comment by xshapira** [comment]
Finally, found it! It was an extension called `Refactor CSS`.  I was driving myself insane with this issue. Thank you!

**Comment by aeschli** [comment]
Thanks for reporting back!
