### ISSUE TITLE
JavaScript syntax highlighting issue after latest update

### ISSUE THREAD

**Issue by literallylara** [Microsoft/vscode#15012]
- VSCode Version: 1.7.1
- OS Version: Windows 10 64-bit

**Steps to Reproduce**
Open the following in v1.7.1 with js syntax highlighting (huh, it even seems to break GitHub's highlighter) :

```js
function f()
{
	let t = 0
	let TAU440 = Math.PI*2 * 440

	onmessage = function(e)
	{
		let b = new Float64Array(e.data.bufferSize)
		let s = e.data.sampleRate

		for (let i = 0; i < b.length; i++) b[i] = Math.sin(TAU440 * t++/s * Math.sin(t++/s*.5))

		postMessage(b)
	}
}

let a = new AudioContext()
let s = a.createScriptProcessor(0,1,1)
let b = new Float64Array(s.bufferSize)
let w = new Worker(URL.createObjectURL(new Blob(["("+f+"())"],{type:"application/javascript"})))

w.onmessage = e => b = e.data
s.connect(a.destination)

s.onaudioprocess = function(e)
{
	w.postMessage({ bufferSize: s.bufferSize, sampleRate: a.sampleRate })
	e.outputBuffer.getChannelData(0).set(b)
}
```

![tretzreztre](https://cloud.githubusercontent.com/assets/21112862/20017765/4ae7321e-a2c5-11e6-9aa9-d8ec270c4906.PNG)

The issue seems to be with the `t++/s`, when you surround `t++` with parenthesis the highlighting works fine.

**Comment by waderyan** [comment]
@literallylara thanks for opening this issue. The repo for the grammar is actually here. I will migrate the issue there. https://github.com/Microsoft/TypeScript-TmLanguage

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#346
