### ISSUE TITLE
Cyclic dependency: `vs/workbench/contrib/tasks/common/tasks` and `vs/workbench/contrib/tasks/common/taskService`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#150178]
related https://github.com/microsoft/vscode/issues/150025

There is a cycling (runtime) dependency when not inlining/hoisting const enums between the mentioned files. The enum in question is: `TaskRunSource`

**Comment by alexr00** [comment]
Thank you for fixing!
