### ISSUE TITLE
Portable VS Code stores settings in the roaming profile

### ISSUE THREAD

**Issue by PetrKryslUCSD** [microsoft/vscode#150196]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.19044
Steps to Reproduce:

1. Portable installation. 

2. Locate the settings file. It is not in the portable-editor tree, but rather in the roaming profile.
![image](https://user-images.githubusercontent.com/9855832/169848987-e87494a0-b6dd-4134-a8a2-70602e9c726b.png)

This is clearly a problem: I can't take the settings with the portable editor. They are (a) left behind on the computer I have used, and (b) I have to recreate them on any computer on which I use the editor again and again.

**Comment by IllusionMH** [comment]
/needsMoreInfo

Have you followed all steps from https://code.visualstudio.com/docs/editor/portable ?

In particular section about `data` folder and it's location https://code.visualstudio.com/docs/editor/portable#_windows-linux

**Comment by PetrKryslUCSD** [comment]
Oops, I did not create that folder.

On that note: Why is it up to the user to "opt in" by creating that folder. After all, the user
downloaded a portable version, so the expectation would be for it to be set up as portable 
from the get to. The `data` folder should have been present in the zip!

Is there a rationale?

**Comment by joaomoreno** [comment]
> After all, the user downloaded a portable version, so the expectation would be for it to be set up as portable from the get-go.

We don't distribute a portable version. We just distribute a ZIP archive which can be made portable. The rationale is to reduce the amount of different distributables.
