### ISSUE TITLE
wrong terminal startup folder when open vscode with path param

### ISSUE THREAD

**Issue by unional** [microsoft/vscode#150153]
Issue Type: <b>Bug</b>

When open vscode from terminal with a path,
e.g. `code repo-x`,
the intergrated terminal will start at the original folder instead of from `repo-x`.

A typical use case:

```sh
# working on one repo, try to open another repo the first time

# open integrated terminal
repo-a> code ../repo-b
```

When open the integrated terminal in the new window, it still points to `repo-a`

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.94GB (51.22GB free)|
|Process Argv|--crash-reporter-id b492549b-40cf-406b-b510-34194e061545|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
codesnap|adp|1.3.4
vscode-css-formatter|aes|1.0.2
vscode-nginx-conf|ahm|0.1.3
vscode-zipfs|arc|3.0.0
solidjs|ber|3.0.7
emojisense|bie|0.9.0
vscode-tailwindcss|bra|0.8.2
better-toml|bun|0.3.2
postcss|css|1.0.9
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
eslint-disable-snippets|drK|1.3.0
gitlens|eam|12.0.6
filter-lines|ear|1.0.0
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.4.0
vsc-material-theme-icons|equ|2.2.1
prettier-vscode|esb|9.5.0
vscode-reveal|evi|4.1.3
code-runner|for|0.11.7
shell-format|fox|7.2.2
remotehub|Git|0.30.0
vscode-pull-request-github|Git|0.40.0
rest-client|hum|0.24.6
code-eol|jef|1.0.11
vscode-advanced-open-file|jit|0.3.0
svg|joc|1.4.18
vscode-random|jre|1.11.0
rust-analyzer|mat|0.2.1022
hex-hover-converter|maz|1.2.1
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
theme-monokai-pro-vscode|mon|1.1.20
vscode-json5|mrm|1.0.0
vscode-scss|mrm|0.10.0
remote-containers|ms-|0.231.6
remote-wsl|ms-|0.66.0
hexeditor|ms-|1.9.6
powershell|ms-|2021.12.0
remote-repositories|ms-|0.4.0
resourcemonitor|mut|1.0.7
indent-rainbow|ode|8.3.1
fix-json|oli|0.1.2
advanced-new-file|pat|1.2.2
emoji|Per|1.0.1
vscode-versionlens|pfl|1.0.9
material-icon-theme|PKi|4.16.0
vscode-xml|red|0.20.0
vscode-yaml|red|1.6.0
vscode-sort-json|ric|1.20.0
LiveServer|rit|5.7.5
vscode-open|san|0.1.0
vscode-scss-formatter|sib|2.4.2
mdx|sil|0.1.0
code-spell-checker|str|2.1.11
svelte-vscode|sve|105.16.0
html-preview-vscode|tht|0.2.5
sort-lines|Tyr|1.9.1
vscode-sort-package-json|uni|1.3.0
vscode-ltex|val|13.1.0
quokka-vscode|Wal|1.0.459
browserslist|web|1.1.0
vscode-mdx-preview|xyc|0.3.3
vscode-ol-syntax|yur|0.1.65
markdown-all-in-one|yzh|3.4.2
material-theme|zhu|3.13.24

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by meganrogge** [comment]
I can't reproduce this unless the folder I specify is non-existent. Can you provide a gif?

**Comment by meganrogge** [comment]
can I have your .vscode settings.json?

**Comment by unional** [comment]
The target repo? https://github.com/unional/global-store/blob/main/.vscode/settings.json

**Comment by meganrogge** [comment]
I'm unable to reproduce this. Did it just start happening or did it work in prior versions?

**Comment by unional** [comment]
I found out more information. This only happens when I use `nushell` as the terminal. It works fine in all other shells. Powershell, pwsh, git-bash, include wsl-bash.

I don't have any special setting:

```
  "terminal.integrated.profiles.windows": {
    "fish": {
      "args": [
        "fish"
      ],
      "icon": "terminal-bash",
      "overrideName": true,
      "path": "wsl"
    },
    "nu": {
      "color": "terminal.ansiMagenta",
      "icon": "terminal-bash",
      // "args": ["-l"],
      "path": "nu"
      // "path": "C:\\Program Files\\nu\\bin\\nu.exe"
    },
    "pwsh": {
      "icon": "terminal-powershell",
      "path": "pwsh"
    }
  },
```
And I have tried absolute path, adding `-l`, nothing works.

I have been using `nushell` for a few months. Never have problem until now.

**Comment by Tyriar** [comment]
@jntrnr does nushell do anything special when handling the cwd? This user is saying other shells works fine but nushell starts in an unexpected path.

**Comment by unional** [comment]
I think I have found the issue.

The `PWD` value is wrong.

For example:

```sh
D:\code\unional> code abc/def
```
This opens VS Code with the `D:\code\unional\abc\def` folder.
When opening a PowerShell terminal, it correctly start at that folder. But when looking at the environment:

```sh
> Get-ChildItem -Path Env:

...
PWD   D:\code\unional
...
```

You can see the PWD still points to the folder where I run the `code abc/def` from.
That's the value `nu` uses thus it starts at the `D:/code/unional`.

**Comment by unional** [comment]
PowerShell does not use `PWD` and does not update it when changing folder. My guess is that environment variable should not be set by VS Code, it should be handled by the shell.

**Comment by unional** [comment]
The latest version of `nu` will fix it. thx!
