### ISSUE TITLE
"Search only file names" feature in the Search tab

### ISSUE THREAD

**Issue by martinsuchan** [microsoft/vscode#150134]
In VS Code I really like the speed when using Search tab on the left when searching for a specific file content, optionally only in files matching specific file name string. But there is a feature I miss in VS almost on daily basis - **searching files only in file names** and getting the search results in a nice list of files that does not disappear when when I click through all of them.
Yes, I can use Ctrl+P on Windows to quickly find 'a' file with specific name, but if there are dozens of files with specific string in a name, this feature is almost useless.

### Reason why "Search only file names" feature should be considered for the VS Code Search tab:

I'm often using the VS Code to search in a git repo with about 100k of files. These files are very often cross-referencing each other using key words from some files as names in other files.
For instance, **when searching for "trade1234" I find about 50 files with "trade1234" in the file content, but there are also some files with "trade1234" in the file name but without "trade1234" in file content. And VS Code Search can't find these files, and that's a big problem for me.**
Usually I solve this by using Total Commander search side by side. As you can see the search in TC can be used to search files only using file names, or only using file content, or both. In any case I get nice list of files in the search results window that I can work with, export the list to file, etc. I can even use the list of files from my first search as a target for another search.

![total commander](https://user-images.githubusercontent.com/3041397/169716423-6935f636-2e90-4d32-8f61-b86c409693a3.png)

I can imagine this feature implemented in VS Code very easily as another "..." toggle, **where I can use either file content filter, or file name filter, or both.** Even better, having a nice "multi file rename tool" similar to the existing file content search and replace tool is another feature worth considering.
Thanks

**Comment by mark-hahn** [comment]
I posted the same request only to find out that searching file names already exists.  Try CTRL-R.

**Comment by martinsuchan** [comment]
> I posted the same request only to find out that searching file names already exists. Try CTRL-R.

Ctrl+R is a command to "Navigate between recently opened folders and workspaces", something completely different.

**Comment by Deezlw11** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Deezlw11** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mark-hahn** [comment]
It also has a search box.  Have you tried it?

**Comment by roblourens** [comment]
I think you are looking for ctrl+P

**Comment by martinsuchan** [comment]
> I think you are looking for ctrl+P

No, I'm not. As I mentioned at the start, Ctrl+P functionality is insufficient and NOT what I am looking for.
There is no way how to get list of files for specific file name search that does not disappear when I click elsewhere.

**Comment by roblourens** [comment]
This has been suggested a few times, https://github.com/microsoft/vscode/issues/127723 and https://github.com/microsoft/vscode/issues/84963 at least, but I don't think it's a good match for the find viewlet which goes for minimalism. It is a good extension candidate however
