### ISSUE TITLE
Code hangs on VMWare Workstation 11

### ISSUE THREAD

**Issue by goldbergjeffrey** [Microsoft/vscode#15014]
- VSCode Version: 1.7.1
- OS Version: Windows 2012 R2

Steps to Reproduce:

1. Create Windows Server 2012vm in VMware Workstation.
2. Install Visual Studio Code
3. Launch Visual Studio Code
4. Watch your system hang.

**Comment by mrmlnc** [comment]
Please, use search before create new issue.

Related to #13139, #13981, #13882, #14870

**Comment by rebornix** [comment]
Close as dup. Thanks @goldbergjeffrey and @mrmlnc
