### ISSUE TITLE
Windows title action hover is rounded

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#150185]
Accidental?

![image](https://user-images.githubusercontent.com/22350/169833384-0992ea10-136b-432d-9320-8a8457b8a4a8.png)

**Comment by sbatten** [comment]
@joaomoreno this was an intentional change to match the new context menu stylings. This matches what updated inbox apps on Windows are doing.

<img width="154" alt="image" src="https://user-images.githubusercontent.com/6561887/169847937-e4d1fce9-739f-47ee-bb83-0be606bcaab0.png">
