### ISSUE TITLE
Feature removal request: Don't auto-set case sensitivity in search.

### ISSUE THREAD

**Issue by mark-hahn** [microsoft/vscode#150139]
I quite often select some text and hit ctrl-shift-F to do a global search in the project.  When the text contains an uppercase letter the case-sensitivity is automatically turned on which often is not what I want.  I then have to go through and change each uppercase letter to lowercase which is a real PITA.  To add insult to injury, alt-C is broken and doesn't toggle it.  This should actually be considered a bug.

*Please* remove this feature.  I can decide for myself whether the search should be case-sensitive.

**Comment by gjsjohnmurray** [comment]
Does the `search.smartCase` setting help you?

**Comment by mark-hahn** [comment]
I'm sure it will.  I don't do my homework.  Thanks a bunch.
