### ISSUE TITLE
piping stderr and stdout to a file doesn't work

### ISSUE THREAD

**Issue by Nika-St** [microsoft/vscode#150162]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: Windows 10

Steps to Reproduce:

1. Create launch.json
2. Add
"args": ["&>", "./run.log"],
"cwd": "${fileDirname}",
3. Run a python script
Instead of being logged to the specified file, the output of the script is printed in the terminal
So essentially [this issue](https://github.com/microsoft/vscode/issues/148887) persists after an update to 1.67.2

**Comment by roblourens** [comment]
Will discuss this in https://github.com/microsoft/vscode/issues/149910
