### ISSUE TITLE
When was the last time you see a path with backslash in linux?

### ISSUE THREAD

**Issue by jefer94** [microsoft/vscode#150112]
For any weird reason, in this set up, the Visual Studio Code when I use `copy relative path` if copy to the clipboard a path with the useless  backslash

```
Version: 1.68.0-insider
Commit: 17c75e11805103026b943c8dc4d50a35f245f76f
Date: 2022-05-20T05:16:13.965Z
Electron: 17.4.4
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.38-1-MANJARO
```

**Comment by sbatten** [comment]
nothing I recall immediately

**Comment by lramos15** [comment]
I cannot reproduce on Ubuntu with latest insiders. Can you provide a gif please?

**Comment by jefer94** [comment]
https://drive.google.com/file/d/1nUT2pUWGJ8ymtPjBdHjXTYDCr2pG7aDx/view?usp=sharing

**Comment by jefer94** [comment]
I think to remember this occur after sync my vscode, the last installation had Windows 11

**Comment by jefer94** [comment]
This is the commit https://github.com/microsoft/vscode/commit/17c75e11805103026b943c8dc4d50a35f245f76f has 4 days ago

**Comment by lramos15** [comment]
In your video you can see the badge on the gear icon in the bottom left. Can you update to the latest insiders and give it a try?

**Comment by jefer94** [comment]
Same behavior, commit from last day

```
Version: 1.68.0-insider
Commit: c0769274fa136b45799edeccc0d0a2f645b75caf
Date: 2022-05-23T05:18:06.482Z
Electron: 17.4.4
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.38-1-MANJARO
```

**Comment by jefer94** [comment]
I can't update using the gear icon in Manjaro

**Comment by lramos15** [comment]
In your settings ensure you don't override the path separator the setting for `/` is as follows: `    "explorer.copyRelativePathSeparator": "/"`

**Comment by jefer94** [comment]
You are kidding me? 😂​

This is the most extravagant thing a team has said to me ​😂​
![image](https://user-images.githubusercontent.com/3018142/170421543-772373dc-5047-4a84-94c2-b9795c716750.png)

Whatever, proceed as you wish 😂​
![image](https://user-images.githubusercontent.com/3018142/170421581-7806754a-498a-47af-bc9c-95e17b7df77c.png)

Microsoft, king of software quality 😂​

**Comment by lramos15** [comment]
You can try changing that setting from auto to `/`. We of course want to help but there's only so many linux distributions I can test. I cannot reproduce this on `macOS` or `Ubuntu` and I do not have an Arch block nor does Azure VMs support one leaving me without a testing platform to dig deeper into your problem.

**Comment by jefer94** [comment]
If you investigate all about the settings `explorer.copyRelativePathSeparator`and the resources provide by me is impossible don't determine the cause of issue (Principle of sufficient reason), would be better ask the author of issue all the necessary to know how resolve it instead of write all extravagant thing I read, also exists a lot of solutions can run all the base distros, choice don't use it is a thing more of the will of the team than the possibility of see it for part of Microsoft, also the team ignore parts as `I think to remember this occur after sync my vscode, the last installation had Windows 11` that require the team ask me the settings file or my email to see my settings

And also, in the case of "blablabla so many linux distributions" you can provide a package of Flatpak, Snap or AppImage and test a least all the base distros, is absurd I has to see a useless backslash in linux using `explorer.copyRelativePathSeparator` set as `auto`, does not exist any criteria to inferred the path in linux should contains backslash

The problem is `"explorer.copyRelativePathSeparator": "/"` resolve my issue, but doesn't resolve the issue with the default, instead of it Microsoft prefer be rude saying `We closed this issue because we don't plan to address it in the foreseeable future.` and then process lying about they can't reproduce the issue, but this issue should never have happened, this is the things the testing team should catch before other people sent their issue to Microsoft and it prefers be rude with it

Thanks for the useless support to Linux I suppose a multimillionaire team not have sufficient money to provide this support
