### ISSUE TITLE
Allow OPEN EDITORS box to have a fixed height

### ISSUE THREAD

**Issue by imthenachoman** [microsoft/vscode#150143]
Right now, the `OPEN EDITORS` section shrinks/grows depending on the # of open files you have. This experience is very distracting for some folks with certain disabilities. Every time a new file is opened, the `OPEN EDITORS` box gets bigger and the files list/tree below it moves down one line. 

I am requesting  a feature that will allow us to set a fixed height for `OPEN EDITORS` like we can with the other sections. 

Users should be able to size the `OPEN EDITORS` box to their liking. If there are more open files then the viewport will allow, it'll add a scrollbar. 

Alternatively, another option is to allow a minimum height for the `OPEN EDITORS` box.

**Comment by gjsjohnmurray** [comment]
See `explorer.openEditors.minVisible`

**Comment by imthenachoman** [comment]
I. Am. An. Idiot. Thank you so much!
