### ISSUE TITLE
Do not active Replace mode when press ctrl+f to call Find

### ISSUE THREAD

**Issue by saatana97** [microsoft/vscode#150165]
keep it as it is！！！
I always press Enter to search next one after press ctrl+f.
now,this action will replace my keyword to nothing.
do some human affairs！！！

**Comment by saatana97** [comment]
版本: 1.67.2 (user setup)
提交: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
日期: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by saatana97** [comment]
![image](https://user-images.githubusercontent.com/34677730/169782436-205edc74-2316-4cde-9971-5eba38c98fbb.png)
press CTRL+F,
Replace will active and replace's input be focus,
press Enter,
replace first matched to nothing and goto next match.
Replace mode is not activated until update to new version.
This update has caused users to change their operating habits.

**Comment by saatana97** [comment]
sorry,I think it not vscode's problem.
I readed EclipseKeymap plugin's change log just now.
it's all its fault.
I'm so sorry for that.

**Comment by KarlGusta** [comment]
> sorry,I think it not vscode's problem. I readed EclipseKeymap plugin's change log just now. it's all its fault. I'm so sorry for that.

It's okay. All the best with your findings.
