### ISSUE TITLE
Visual Studio Code has crashed (0.10.5, os x el capitan)

### ISSUE THREAD

**Issue by meowtec** [Microsoft/vscode#1501]
I upgraded my vccode to 0.10.5, but I can not use it.
Every time I start the app, it will be like:
<img width="689" alt="2015-12-20 2 24 27" src="https://cloud.githubusercontent.com/assets/4006436/11916849/6e9be912-a725-11e5-975a-6176f2539111.png">
I tried restarting the app, but no help.

However I can run vscode from source.

Maybe something is wrong in `Visual Studio Code.app`

**Comment by rnordin100** [comment]
Visual studio code.app

**Comment by peiyucn** [comment]
I have the same problem with you.

**Comment by skyline75489** [comment]
Same here.

**Comment by stephenzl** [comment]
there have a temporary solution to fix this crash. u need to switch your input method to system default english(U.S.) before start vscode.  then start vscode, u can switch your input method u like.

**Comment by meowtec** [comment]
@stephenzl
Thanks, your solution does work.

**Comment by bpasero** [comment]
Duplicate of https://github.com/Microsoft/vscode/issues/1463

**Comment by lhCheung1991** [comment]
Switching the input method to system default english(U.S.) really works

**Comment by johnnian** [comment]
@stephenzl It works, :)

**Comment by Wyvern** [comment]
the same annoying issue

**Comment by lhCheung1991** [comment]
Is there any conflict between your inputing software with VS code? So weird...

**Comment by SiriusGuo** [comment]
same here. OSX 10.11.2, Code 0.10.5

**Comment by mono0926** [comment]
Same here :(

**Comment by xsstomy** [comment]
same here. OSX 10.10.2 , vs code 0.10.5

**Comment by otter668** [comment]
same here. OS X 10.11.2, VS Code 0.10.5 and 
Switching the input method to system default english(U.S.) really works
Thx for @lhCheung1991

**Comment by iiunknown** [comment]
same here. OSX 10.11.2 , vs code 0.10.5

**Comment by osser** [comment]
me too.

**Comment by meowtec** [comment]
@osser 
@iiunknown 
see https://github.com/Microsoft/vscode/issues/1501#issuecomment-166100445

**Comment by YvonneZhang** [comment]
> Switching the input method to system default english(U.S.) really works

It works for me. :+1:

**Comment by johnhoow** [comment]
Yes, it really work!

**Comment by zackexplosion** [comment]
> Switching the input method to system default english(U.S.) really works

This really works!

**Comment by SamuelGustafsson** [comment]
What do you mean with input method, computer language?

**Comment by lhCheung1991** [comment]
@SamuelGustafsson The software 
![image](https://cloud.githubusercontent.com/assets/8599885/15383032/401ddafa-1dc2-11e6-954f-36a19683f327.png)
default english(U.S.) really works

**Comment by SamuelGustafsson** [comment]
Im still having the same problem the on a windows computer. Is there anyone else with this problem on a windows computer??

**Comment by dojbraga** [comment]
I have the same problem the on a windows computer and change the input method don`t resolve

**Comment by lordgreg** [comment]
Still having this issue.

El Capitan 10.11.5 (15F34)
Visual Studio Code 1.2.1 (1.2.1)

**Comment by inkrh** [comment]
Issue is still present on Sierra with VS 1.5.3 - clicking reopen just goes to the same error again.


<img width="1041" alt="screen shot 2016-09-24 at 14 13 03" src="https://cloud.githubusercontent.com/assets/16457014/18810633/2b2e2c7c-8261-11e6-88bd-e0986b27c03a.png">

**Comment by mtebele** [comment]
Same with Sierra and VSC 1.6

**Comment by Masatoshi** [comment]
I got same issue on Sierra.
I found some logs which showed errors were caused by Electron.
But 10.12.1 update seemed to fix it.
