### ISSUE TITLE
Error message interrupt and frustrate 

### ISSUE THREAD

**Issue by WardDurossette** [Microsoft/vscode#15018]
- VSCode Version: 1.7
- OS Version: windows 8.1

Steps to Reproduce:
1. Open a Windows Explorer window to a remote share (I.e. \\server.dom2.dom1\share

2. Double click a file to open in VSCode. (Default.asp)
3. Start editing file.  As you type the output window will pop-up with the error text, covering the edit window, interrupting your work, causing you to become frustrated.
4. Close output window to get rid of useless error message that you can do nothing about.
5 Goto step 3.

**Comment by joaomoreno** [comment]
Can you show us a screenshot of that error text?

**Comment by WardDurossette** [comment]
Sure, here you go.  The annoying part is the output window covering the part of the file I was editing, and it seems like every keystroke, or every second this error is regenerated.

There is workaround for this - you can slide the output window down.  Closing the output window is not effective, as the next error opens it back up over your code.

Also, actual error text is:
[Error - 1:54:00 PM] Request textDocument/documentLink failed.
  Message: Request textDocument/documentLink failed with message: Path must be a string. Received undefined
  Code: -32603 



![capture](https://cloud.githubusercontent.com/assets/19767604/20073543/4d3e500e-a4f2-11e6-9e97-736880a62385.PNG)

**Comment by aeschli** [comment]
@WardDurossette Can you share the whole file, or construct a minimal example. Look out for html elements with 'src' or 'href' attributes.

**Comment by charlesgiroux** [comment]
`<!DOCTYPE html>
<html>
    <head>
        <title>VSCODE #15018</title>
    </head>
    <body>
         
        <img src="/somerandomurl/image1.jpg">
        
        <img src="http://www.something.com/somerandomurl/image1.jpg">
        
        <img src="somerandomurl/image1.jpg">
    </body>
</html>`

**Comment by xekri** [comment]
Same issue. The problem is caused by a source path that starts with "/". However, when opened a directory then open the html file, the problem solved.

**Comment by sktnetwork** [comment]
Is there any quick solution to this. It's very frustrating to work on VS code now. My whole day job is to directly work on server files from FileZilla with references to all kinds of paths.

Can we please somehow turn OFF this feature whatever it's trying to check?

**Comment by doncullen** [comment]
Is there at least a workaround until the update is released? @aeschli

**Comment by aeschli** [comment]
@doncullen The workaround is to open VSCode on a folder instead of a file.
