### ISSUE TITLE
Very high IO, causing the machine to hang. - -#

### ISSUE THREAD

**Issue by valord577** [microsoft/vscode#150189]
Does this issue occur when all extensions are disabled?: `Yes`

- VS Code Version:
  ```
  Version: 1.67.2
  Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
  Date: 2022-05-17T18:20:57.384Z
  Electron: 17.4.1
  Chromium: 98.0.4758.141
  Node.js: 16.13.0
  V8: 9.8.177.13-electron.0
  OS: Darwin x64 21.5.0
  ```
- Remote OS Version:
  ```
  [user@host ~]% uname -a
   Linux devops-0 5.17.9-arch1-1 #1 SMP PREEMPT Wed, 18 May 2022 17:30:11 +0000 x86_64 GNU/Linux
  [user@host ~]% 
  [user@host ~]% cat /etc/os-release
   NAME="Arch Linux"
   PRETTY_NAME="Arch Linux"
   ID=arch
   BUILD_ID=rolling
   ANSI_COLOR="38;2;23;147;209"
   HOME_URL="https://archlinux.org/"
   DOCUMENTATION_URL="https://wiki.archlinux.org/"
   SUPPORT_URL="https://bbs.archlinux.org/"
   BUG_REPORT_URL="https://bugs.archlinux.org/"
   LOGO=archlinux-logo
  ```

## IO with CMD `pidstat -d 1`:

<img width="611" alt="Screen Shot 2022-05-23 at 21 17 56" src="https://user-images.githubusercontent.com/30427460/169828481-167c2ccf-e490-4df0-86eb-bf91115c59be.png">

## Monitoring:

<details>
  <summary>
    Read/Write Byte/s
  </summary>

<img width="1098" alt="Screen Shot 2022-05-23 at 21 33 15" src="https://user-images.githubusercontent.com/30427460/169831111-547a00d3-8f5c-45b7-8b71-6d162a1bd7a0.png">
</details>

<details>
  <summary>
    IOPS
  </summary>

<img width="1098" alt="Screen Shot 2022-05-23 at 21 33 23" src="https://user-images.githubusercontent.com/30427460/169831135-7da0f1be-cb32-4589-80bc-8d3e583c9a44.png">
</details>

<details>
  <summary>
    CPU utilization
  </summary>

<img width="1098" alt="Screen Shot 2022-05-23 at 21 33 30" src="https://user-images.githubusercontent.com/30427460/169831155-b857b833-fb7d-4da0-96e1-e671cb75d6b4.png">
</details>

## Steps to Reproduce:

0. Download demo code: [vue3-demo.tar.gz](https://github.com/microsoft/vscode/files/8755037/vue3-demo.tar.gz)
1. Install deps: `npm cache clean -f && npm install`
2. Run dev mode: `npm run dev`
3. Crazy to modify the `src/main.js`, e.g. write, save, undo. When you are inspired, the speed of writing code is insane.

**Comment by valord577** [comment]
Anyone help?

**Comment by mjbvz** [comment]
Looks like this issue didn't get the correct attention when it was first opened

I'm closing it since there hasn't been any follow up. It's possible that an extension was causing this. If you are still seeing this issue with extensions disabled, let us know
