### ISSUE TITLE
Make the Terminal Command Line a Different Color

### ISSUE THREAD

**Issue by RoyKM** [microsoft/vscode#150182]
When working with the Terminal window, it is difficult to identify the command lines, especially when in redhat bash (OS=windows 10, VirtualBox, CentOS 7, vagrant ssh) scrolling backwards and forwards, trying to find the commands I entered.  It would be much easier to read if the command lines were always a different color than the displayed result

![Oracle_VirtualBox](https://user-images.githubusercontent.com/79272297/169826638-782a0075-eb62-454b-9405-ae57f5897527.png)

![VSC_Terminal_Example](https://user-images.githubusercontent.com/79272297/169827083-95532e6c-2dba-454c-82c5-d2d8a1c262ff.png)

**Comment by meganrogge** [comment]
thanks for the issue, but we don't intend to do this. you can add themes or use things like powerlevel10k to change how your terminal looks
