### ISSUE TITLE
Add "Tasks" side bar

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#15017]
Support of tasks needs a lot of improvement (a lot of feature requests). I think we have accumulated enough feature requests to promote tasks management to a separate side bar. The side bar should:

- Refreshes and lists all tasks when a new folder is opened
- Allows user to manually refresh task list when corresponding file (e.g. gulpfile.js) is modified. Or, watch the file so the list will be automatically updated.
- Shows the state of each task, e.g. "running". More than one task can be in "running" state.
- Provides a "Run" button for each task, or a "Terminate" button if the task is running.
- Show the path of the corresponding tasks definition file, and a button to open the file in editor.

**Comment by rebornix** [comment]
@octref is working on https://github.com/Microsoft/vscode/pull/14048 so this can be implemented as an extension.

**Comment by octref** [comment]
CC @dbaeumer

Think you might be interested as this is assigned to you.

>  Tasks - Explore future direction of task support @dbaeumer

**Comment by dbaeumer** [comment]
@cnshenj I fully agree that the task support needs improvement and especially alignment with other features in VS Code. We decided that during the next iteration we work on the future directions of the task support and will cycle the ideas back to the community.

**Comment by egamma** [comment]
There were many improvements to tasks. There now is an API, that is leveraged by the NPM Script Explorer, and there now is an extension that provides a Tasks explorer https://marketplace.visualstudio.com/items?itemName=BitLaboratory.task-panel.

Closing this issue.
