### ISSUE TITLE
Typing lag

### ISSUE THREAD

**Issue by j-zehnder** [microsoft/vscode#150107]
Issue Type: <b>Bug</b>

Just load VScode and start typing normally on a file. Eventually the characters will just not show up right away. Or sometimes they show up momentarily, then flicker to gone, then come back again. Using backspace while typing seems to make this worse. I also want to note that the attached memory profile shows 19.8G free (11.2 in use) while my system monitor only shows ~4.6G in use, with an additional 8.8G cache. As an additional note, the typing issues I described also occurred for me when typing this issue report in issue reporter, which made the task rather difficult.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.17.8-300.fc36.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.03GB (19.80GB free)|
|Process Argv|notes --crash-reporter-id a04969b4-1cc9-4428-80fc-15194709da49|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by alexdima** [comment]
The issue reporter is built with a simple `<textarea>`, so I don't think this is a code editor specific problem.

**Comment by j-zehnder** [comment]
I have started noticing this issue in other apps, I do not believe it to be specific to VSCode. I am closing
