### ISSUE TITLE
Javascript Formatting Broken in 1.7.1

### ISSUE THREAD

**Issue by cristianorvf** [Microsoft/vscode#15010]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Theme-azure|gerane|0.0.2|
|FlatUI|lkytal|1.0.0|

---

Steps to Reproduce:

1. Open any JS File (no TS)
2. Try to format, nothing happens
3. HTML files are formatting as usual

**Comment by rebornix** [comment]
I've see quite a few formatting issues. If it's an external extension, that makes sense as we changed the formatting command in 1.7 but `js` is an internal one.

**Comment by cristianorvf** [comment]
@rebornix its not an extension. The only ones installed are themes, and i've just removed them, and restarted, still with problem. I've a windows 10 machine here, tested it (1.7.1) and its ok, with the same project pulled from git. 

Well, thats really odd, ill try a full re-install.. strange nobody is running into this, i really dont mess with vs code, so it broke by itself.

**Comment by cristianorvf** [comment]
@rebornix I've just made it to work. The (apparent) problem is that when no external formatting provider is setup the formatting wont work, i didnt look at the source, but theres a constraint in the key binding "editorHasDocumentFormattingProvider" that i didnt see before, this might be involved when using JS files trying to use a "native formatter" (is there one right?).

Just to note, using the context menu in the JS files to format a the entire document or the selection didnt work also.

Im using the extension -> lonefy.vscode-JS-CSS-HTML-formatter

Im concerned that this extension formats differently than the previous (native?) one, so some Merges might occur in the code and i've more than 4 projects and "forced" the team tu use VS Code exactly because people used different code formatters for HTML and JS :(

**Comment by cristianorvf** [comment]
@rebornix 

I've found the problem, but maybe another issue should be open (?).

Having the file **jsconfig.json** in the project makes the formatting stop working.  **Actually, if the file IS EMPTY only with open/closing {} brackets it already stops working**.

My file contents were:

`{
	"compilerOptions": {
		"target": "ES6",
		"module": "commonjs",
		"allowSyntheticDefaultImports": true
	},
	
	"exclude": [
		"**/node_modules/**",
		"**/bower_modules/**",
		"**/dist/**",
		"jspm_packages",
		"tmp",
		"temp"
	]
}`

Changing ES6 to ES5 have no consequences at all.

Removing the file and starting again everything comes back to normal again, it formats ES5 and ES6 just fine!

Thanks.
