### ISSUE TITLE
Whole input charactors in same line flicker with Japanese IME 

### ISSUE THREAD

**Issue by hiromasat** [microsoft/vscode#150108]
Issue Type: Bug

Does this issue occur when all extensions are disabled?: Yes

When inputting Japanese charactors with Japanese IME, whole charactors in same line flickers during converting it to Japanese Kanji,  resulting in a bad typing experience.

https://user-images.githubusercontent.com/16264266/169677572-67fe565c-28f9-4056-a86b-9af30e00cf1f.mov

<details>
<summary>1.67.2 Verision info</summary>

Version: 1.67.2 
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5  
Date: 2022-05-17T18:20:04.972Z 
Electron: 17.4.1  
Chromium: 98.0.4758.141 
Node.js: 16.13.0  
V8: 9.8.177.13-electron.0 
OS: Darwin arm64 21.5.0 

</details>

## Steps to Reproduce:
Typing Japanese Charators and converting them in 1.67.2

## Confirmation with older version
1.63.2 does NOT have this bag.

<details>
<summary>1.63.2 Verision info</summary>

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:38:17.605Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.5.0

</details>

https://user-images.githubusercontent.com/16264266/169677564-193f14ab-ce0f-4088-b100-f9f388c22927.mov

## Environment
MacBook Pro(2021)
Chip:Apple M1 Pro
OS:macOS 12.4 (21F79)

**Comment by hiromasat** [comment]
@alexdima Thank you for a comment. I have checked it with the latest version.This symptom still seems to occur in the latest version.

https://user-images.githubusercontent.com/16264266/206885536-6b10467b-ca6b-4cd7-b118-e87f42834fe5.mov

Issue Type: Bug
Does this issue occur when all extensions are disabled?: Yes

**Environment**
MacBook Pro(2021)
Chip:Apple M1 Pro
OS:macOS 13.0.1

version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:37:54.581Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

**Comment by alexdima** [comment]
@hiromasat Could you please give steps on how to configure the Japanese input mode in the same way as you are using it? Also, could you please tell me the exact keys you are pressing? Some steps similar to https://github.com/microsoft/vscode/wiki/IME-Test#windowsmac-japanese would be helpful (note the level of detail in the steps)

**Comment by hiromasat** [comment]
Sorry for being late to reply. Here is information regarding this issue.
1.  Japanese text setting
     Mac setting>Keyboard>Input source>
     Press [+]button to add Japanese Input Source

2. Switch Input source

3. Typing keys
「日本語入力が揺れている」<- nihongonyuuryokugayureteiru

If you need any other information , I could share them.

**Comment by alexdima** [comment]
@hiromasat Which Japanese input mode should I add?
> <img width="507" alt="image" src="https://user-images.githubusercontent.com/5047891/208477789-99dc8305-cd54-4ab7-b4a5-2e569ab2525c.png">

I have tried with the first one and I can't observe flickering when typing 'nihongonyuuryokugayureteiru':

https://user-images.githubusercontent.com/5047891/208478231-198cfd46-9914-44a6-b4d8-65ceca551d22.mp4

**Comment by hiromasat** [comment]
I used Romaji mode.
Here is my setting about keyboard.

<img width="644" alt="スクリーンショット 2022-12-21 1 20 31" src="https://user-images.githubusercontent.com/16264266/208715277-43af93ad-4e00-4cf7-a986-25688cef3a01.png">

**Comment by hiromasat** [comment]
@alexdima 
I found the reason of the problem. It comes from extension "Vim"
I uninstall this extension and then the problem disapeared.

So I think that this issue can close.
I'm sorry to trouble you.

Name: Vim
ID: vscodevim.vim
Description Vim emulation for Visual Studio Code
Version: 1.24.3
Publisher: vscodevim
[VS Marketplace Link:](https://marketplace.visualstudio.com/items?itemName=vscodevim.vim)
