### ISSUE TITLE
Vscode. dev rejected our connection request

### ISSUE THREAD

**Issue by coplcptir** [microsoft/vscode#150149]
When I log in to Microsoft or GitHub browser prompts vscode. dev Rejected our Connection Request

**Comment by gjsjohnmurray** [comment]
Is #150121 relevant to you?

**Comment by coplcptir** [comment]
> #150121与您相关吗？

不是我的

**Comment by joaomoreno** [comment]
@coplcptir Can you share a screenshot of the issue?

**Comment by coplcptir** [comment]
@joaomoreno I have successfully logged in now. It seems that the login is not available in China. I can access it by proxy

**Comment by sisyphus1212** [comment]
> Is #150121 relevant to you?

it is seem to same

**Comment by sisyphus1212** [comment]
> @joaomoreno I have successfully logged in now. It seems that the login is not available in China. I can access it by proxy

我挂代理了都不可以
