### ISSUE TITLE
Testing: empty filter field is not persisted correctly

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#150123]
- VS Code Version: 1.68.0-insider (Universal) Commit: 17c75e1180
- OS Version: macOS 12.4

Steps to Reproduce:

1. Type "abc" into the filter field of the test browser
2. Reload the window -> "abc" comes back, nice
3. Clear the filter field
4. Reload the window again -> "abc" comes back again (expected an empty filter field instead)

Cc @connor4312

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/150120
