### ISSUE TITLE
My vscode as superuser does not work and display white page

### ISSUE THREAD

**Issue by Alireza67** [microsoft/vscode#150111]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  code_1.67.2
- OS Version: Ubuntu 18.04.1 LTS

Steps to Reproduce:

1. Vscode version ==> code_1.67.2-1652812855_amd64.deb (does not work)
2.  sudo code --user-data-dir="./" --no-sandbox 

when I down grade to "code_1.65.2" with "code_1.65.2-1646927742_amd64.deb", vscode is run as superuser corroctly.

**Comment by Alireza67** [comment]
Can I upgrade to new version?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/151187
