### ISSUE TITLE
heinous purple status bar when i do a clean install

### ISSUE THREAD

**Issue by thewintersolstice** [Microsoft/vscode#15025]
- VSCode Version: Code - Insiders 1.8.0-insider (dbf3ba74e6cf3b33687b7d47e321e642fc1e7562, 2016-11-04T10:15:01.593Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Steps to Reproduce:

1. Install VS Code.
2. See purple status bar.
3. Fill barf bag.
4. Thank you.

**Comment by bgse** [comment]
There is a fix for that:

File -> Open Folder

**Comment by thewintersolstice** [comment]
Thank you for your reply.
1: Are you joking?
2: In all VSCode screenshots statusbar is blue not purple. Why is mine purple?
3: Need to have option to set statusbar color, or have theme set/affect statusbar color.
4: Thank you.

**Comment by bgse** [comment]
Not joking. The status bar color does depend on what you are currently doing in vscode.

The blue status bar you see in screenshots means that you have a folder opened in vscode (when you are working on a project).

If you go into debug mode, the status bar will turn orange to show you are in debug mode.

**Comment by thewintersolstice** [comment]
Thank you for your answer. First, I salute your knowledge! (not joke, I do).
1: Due to nature of day job 95% of the time I work on individual files which are all over the place: html, css, javascript, sql, php, csv, xml, json, txt. (The other 5% is Powershell which is all in one folder) (Evenings are for C#/VStudio and GCC/NetBeans).
2: Does that mean that I'm stuck with the evil purple status bar?
3: Can we have an option to set status bar colors? I look at a monitor for 8-12hrs a day, I need to work with colors that don't burn my retinas. Soft pastels for example. Please?
4: Thank you.

**Comment by bgse** [comment]
As far as I know, theming the status bar is currently not supported directly.

However, vscode is very hackable, and at its core, the UI is HTML/CSS.

You could probably make your own override CSS for this:

    .monaco-workbench.no-workspace > .part.statusbar {
        background: #68217a;
    }

This is what makes it purple when no folder is open, you could replace that with any color you want.

Check out menu "Help -> Developer Tools", you basically get Chrome developer mode and can play around with the UI any way you want and try things out.

**Comment by rebornix** [comment]
Close as dup of #1884 and @bgse  it's not a bug.
