### ISSUE TITLE
Allow disabling Javascript & Typescript validation, but only for certain files

### ISSUE THREAD

**Issue by rheaditi** [microsoft/vscode#150277]
Use case: We have a monorepo which currently uses Flow as its type system but we will be migrating to Typescript soon. Today in order to use VSCode with Flow, we have the following in our `settings.json`:

```
 "javascript.validate.enable": false,
 "typescript.validate.enable": false,
```

But once we start introducing `*.ts` files, it would be good to have VSCode validate those without touching `*.js` files.

This could be possible by maybe allowing the setting to take a glob instead of just `true/false`:-
```
 "javascript.validate.enable": ['**/*.ts'],
 "typescript.validate.enable": ['**/*.ts'],
```

**Comment by mjbvz** [comment]
For your use case, shouldn't you be able to use ` "typescript.validate.enable": true` since you only want validation of the typescript files?

**Comment by rheaditi** [comment]
> For your use case, shouldn't you be able to use ` "typescript.validate.enable": true` since you only want validation of the typescript files?

From what I can see & understand Typescript validation runs on Javascript (.js) files as well..

**Comment by rheaditi** [comment]
Hey @mjbvz, thanks! I guess this could work..

Although – is Typescript validation a superset of Javascript validation? Do we lose anything from `javascript.validate.enable` being false for `.ts` files?

**Comment by mjbvz** [comment]
@rheaditi No, they are separate settings: `javascript.validate` only applies to javascript files, `typescript.validate` only applies to typescript files

Closing this issue since I believe our existing settings already cover it

**Comment by jrichardsz** [comment]
ts disable does not work

```
"typescript.validate.enable": false
```

I have this ugly warnings in my js file

![image](https://github.com/microsoft/vscode/assets/3322836/6063e5b5-3f9f-4fa3-ba1a-0c8fc3b8be7b)

I need to disable javascript and typescript

```
{
    "typescript.validate.enable": false,
    "javascript.validate.enable": false    
}
```

In order to hide the TYPESCRIPT ERROR

![image](https://github.com/microsoft/vscode/assets/3322836/c0a23dee-cf53-4cca-bf5f-8db52d33ff29)

Keep i mind that I'm not using typescript

Similar: 

https://stackoverflow.com/a/42633555/3957754

**Comment by alshdavid** [comment]
I have a case where I am trying to migrate from Flow to TypeScript however flow files use the `.js` extension.

Using `"javascript.validate.enable": false` disables type checking in genuine JavaScript files which is undesirable (build scripts and so on).

It would make it a lot easier to be able to rename the flow files to `a.flow.js` and use a setting like the following to exclude them from validation:

```
"javascript.validate.exclude": ["**/*.flow.js"] 
```
