### ISSUE TITLE
[css] restriction attribute in css-scheme.xml doesn't work as expected for some types

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1502]
If there is only one value listed in the values element, the **color** restriction will remove that value when compiling the browsers.js file. If two or more are listed then it works as expected.

I had to add an extra value that already exists in the color list to stop it removing the revert value from outline-color. 

Works:

      <entry name="outline-color" restriction="enum, color">
        <desc>The color of the outline</desc>
        <values>
           <value name="invert" version="2.0" browsers="E,IE8,O">
             <desc>Performs a color inversion on the pixels on the screen.</desc>
           </value>
           <value name="white" version="2.0" browsers="all" />
       </values>
     </entry>

Doesn't work:

      <entry name="outline-color" restriction="enum, color">
        <desc>The color of the outline</desc>
        <values>
          <value name="invert" version="2.0" browsers="E,IE8,O">
             <desc>Performs a color inversion on the pixels on the screen.</desc>
          </value>
       </values>
     </entry>

Also, the **url** restriction doesn't work at all. If you don't list url() in the values section, url will not show up, even when the url restriction is used.

**Comment by aeschli** [comment]
Good catch. That bug was hide multiple entries.
Fixed script, removed your workaround.
