### ISSUE TITLE
Trim trailing spaces should leave intentional double spaces at the end of lines in markdown documents

### ISSUE THREAD

**Issue by l0cky3r** [microsoft/vscode#150286]
The double space at the end of a line to specify an end of line gets stripped by default when saving.

``` markdown
**W** - Plugged In  
**X** - Standby  
**Y** - Charging  
**Z** - Un plugged  
```
becomes
``` markdown
**W** - Plugged In
**X** - Standby
**Y** - Charging
**Z** - Un plugged
```
Which results in the output being all on one line: **W** - Plugged In **X** - Standby **Y** - Charging **Z** - Un plugged

**Comment by mjbvz** [comment]
I don't think we want to get into the business of deciding when a trailing whitespace is intentional or not. A smarter version of the setting could be added by an extension though
