### ISSUE TITLE
Add jinja2 to the lib/snippets.json file for emmet support

### ISSUE THREAD

**Issue by MortalCatalyst** [Microsoft/vscode#15021]
- VSCode Version: August 2016 +
- OS Version: All

In #9500 it references that support for extra languages in emmet are available in the lib/snippets.json file. What would need to be done to add jinja2 as a listed member of that array so that available extensions could utilise emmet jinja2 together. 

Has a significant use case with Flask, Ansible, Pyramid etc as one of the most significant templating languages in python.

**Comment by rebornix** [comment]
It's an easy one, @MortalCatalyst you want to give it a try?

**Comment by mrmlnc** [comment]
Hello, @MortalCatalyst,

After the release of 1.6.0 VS Code has support for all languages that are supported by Emmet. Now you can:

## Create your own plugin

You can convert an existing solution, for example, https://atom.io/packages/atom-jinja2 or https://github.com/antal-bukos/sublimetext3_jinja2_syntax. Just convert `cson` to `json` or use `tmLanguage` files and create plugin for VS Code. 

**Most importantly**, don't forget to check out the scope of language:

**tmLanguage**

```plist
<key>scopeName</key>
<string>text.html.jinja</string>
```

**json**

```json
"scopeName": "text.html.jinja"
```

## Configure editor

You can use `files.associations` to associate `j2` extension with `html` mode:

```json
"files.associations": {
  "*.j2": "html"
}
```

**Comment by MortalCatalyst** [comment]
How can I help the author of the already existing jinja plugin [https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja ](https://marketplace.visualstudio.com/items?itemName=wholroyd.jinja )

It seems the only thing I needed to do was to add

```json
"files.associations": {
  "*.j2": "html"
}
```
to my user settings is there a way the plugin can implement that by default?

**Comment by MortalCatalyst** [comment]
Either way I have added snippets support to the vscode repo [https://github.com/wholroyd/vscode-jinja/pull/10](https://github.com/wholroyd/vscode-jinja/pull/10l)

**Comment by egamma** [comment]
Closing as upstream
