### ISSUE TITLE
Opening a folder in a dev container should not execute code outside the dev container.

### ISSUE THREAD

**Issue by fulldecent** [microsoft/vscode#150239]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.67.2
- OS Version: macOS 12.3.1 (21E258)

Steps to Reproduce:

1. Open a folder of random crap you download off the internet
1. Do not trust that folder
1. Install Remote — Containers extension
1. `> Remote-Containers: Rebuild and Reopen In Container`

Expected:

1. Dangerous things may happen inside your container
1. Only safe things happen on your local host
1. Anything that might be happen on your localhost should be explained clearly in a helpful, including all hypothetical situations

Actual:

1. Somehow VS Code is a vector for malicious container code escapes?

---

<img width="597" alt="Screen Shot 2022-05-23 at 21 35 26" src="https://user-images.githubusercontent.com/382183/169931330-de904c06-43f9-46fb-8414-b12a4653c410.png">
<img width="507" alt="Screen Shot 2022-05-23 at 21 34 55" src="https://user-images.githubusercontent.com/382183/169931521-266d6275-f142-43f1-8a90-7e0e25eb1016.png">

# Discussion

This issue is consistent of Microsoft's goal for this project:

> Visual Studio Code takes security seriously and wants to help you safely browse and edit code no matter the source or original authors.
>
> https://code.visualstudio.com/docs/remote/containers#_trusting-your-workspace

---

Using VS Code with GitHub Codespaces does work without warnings (or requesting "trust") and it seems to not be able to run any code locally. So this is safe.

**Comment by lszomoru** [comment]
I will defer to @chrmarti on whether the arbitrary code can execute outside the container.

**Comment by chrmarti** [comment]
Several reasons: Dev containers are not designed as a security boundary and containers are not considered a security boundary in general (there appear to be security hardened container engines). The devcontainer.json can have a `"initializeCommand"` that will run on the host. The devcontainer.json can bind mount any folder, making it accessible from the container. We forward Git credentials, ssh-agent and gpg-agent sockets into the dev container for convenience.

**Comment by fulldecent** [comment]
Can't anything in this world be good and holy? Like running untrusted code on my workstation can be safe in a container?

---

You are describing bugs of containers as implemented in VS Code. Thank you for helping to identify these.
