### ISSUE TITLE
no possibility to do a replace in selection only

### ISSUE THREAD

**Issue by thewintersolstice** [Microsoft/vscode#15026]
- VSCode Version: Code - Insiders 1.8.0-insider (dbf3ba74e6cf3b33687b7d47e321e642fc1e7562, 2016-11-04T10:15:01.593Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Steps to Reproduce:

1. Create a new document and write the following 4 lines:
hello text
this is text
one text
two text
2. now select line 2 and 3
3. >Edit >Replace
4. There is no way to limit the replace to the selection.
5. Thank you.

**Comment by kaiwood** [comment]
There's a small "Find in selection" button in the search&replace pane:

![selection](https://cloud.githubusercontent.com/assets/7542/20028896/bf0b616a-a33d-11e6-9146-1f87f59c211c.gif)

**Comment by thewintersolstice** [comment]
Thank you for your reply.
1: This option did not work in past tries. Glad to see it works now.
2: If text is selected, this option should be activated automatically. User may then disable if does not wish to limit replace to selection.
3: Thank you.

**Comment by alexandrudima** [comment]
The behaviour of step 2 was discussed in #12109 and it was changed in 79bc7a814603d541502a604e0f984aee7abba90f

**Comment by roblourens** [comment]
Yes, we changed this because it seems like it was triggered by accident more often than used on purpose. But the button is still there for people who want to use it.
