### ISSUE TITLE
terminal.integrated.env.linux is seeing a wrong value of $workspaceFolder with multi-root workspaces

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/vscode#150273]
Issue Type: <b>Bug</b>

I have a multi-root workspace with roughly this structure:

```
/code.code-workspace
/project1/...
/project2/
```
My workspace config contains:
```
{
  "folders": [
    {
      "path": "project1"
    },
    {
      "path": "project2"
    },
    "terminal.integrated.env.linux": {
      "PYTHONPATH": "${workspaceFolder}/project1/src:${workspaceFolder}/project2/src"
    },
}
```
When starting a new terminal, VSCode will first ask me if I want it to be located in either `project1` or `project2`. Irrespective of what I choose there, printing `PYTHONPATH` in the terminal will produce
```
<root>/project1/project1/src:<root>/project1/project2/src
```
It appears that the `$workspacefolder` variable is set to the folder of one of the two projects, rather than the location of the workspace config file, as I would have expected for a setting that lives in the workspace config file. I can't move `terminal.integrated.env.linux` to the project settings because VSCode then says that this is a setting that should be applied at workspace level.

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (5.79GB free)|
|Process Argv|--crash-reporter-id 1cf8a6d7-9b7a-4341-a1df-8c7d1d2c42be|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.42GB (6.55GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.42GB (6.55GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
vscode-ai-remote|ms-|0.12.0
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
rewrap|stk|1.16.3
errorlens|use|3.5.0
rainbow-brackets|2gu|0.0.6
vscode-markdownlint|Dav|0.47.0
fileheadercomment|doi|0.0.5
gitlens|eam|12.0.6
vscode-pull-request-github|Git|0.42.0
vsc-python-indent|Kev|1.16.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-ai|ms-|0.10.0
azure-account|ms-|0.10.1
makefile-tools|ms-|0.5.0
autodocstring|njp|0.6.1
unique-window-colors|stu|1.0.51

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by meganrogge** [comment]
same root cause as #147173
