### ISSUE TITLE
typescript word hightLight issue

### ISSUE THREAD

**Issue by baoziv587** [Microsoft/vscode#15029]
- VSCode Version:1.71
- OS Version: mac os

Word hight light not work  for these code which below `Map<any>`.
If Map<(any)> or Map<T,P> ,it works.
 
![image](https://cloud.githubusercontent.com/assets/7347513/20028571/57279b30-a370-11e6-9bd2-4c59c05367d6.png)

**Comment by TheColorRed** [comment]
Try installing this extension: 
https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar

It is a preview of what is to come in TypeScript syntax highlighting

**Comment by baoziv587** [comment]
Thank you ,but it's not work for me

**Comment by rebornix** [comment]
It's likely caused by #14921 as well.

**Comment by waderyan** [comment]
@aeschli can you look into this? If there is something I can do to help please let me know.

**Comment by aeschli** [comment]
@TheColorRed The https://marketplace.visualstudio.com/items?itemName=ms-vscode.typescript-javascript-grammar is no longer needed as we have now adopted the latest version of TS in VSCode 1.7.1.

**Comment by aeschli** [comment]
Reproduced with this minimal sample in a js or tsx file:
```typescript
this._blockRenderMap = Map<any>({});
this._eventsMap = {};
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#351
