### ISSUE TITLE
Terminal in a Window Tab

### ISSUE THREAD

**Issue by G4143** [Microsoft/vscode#15023]
- VSCode Version:Version 1.7.1
- OS Version: Linux

Not an issue but a request.

Could it be possible to have the terminal open on a separate tab like a new file? I don't like having the terminal located at the bottom of the editor taking up editor space and only providing a few lines of terminal space and thought it would be a great idea to have the option to open the terminal on its own tab so you have a full page for the terminal and its out of the way when you are editing code.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/2806
