### ISSUE TITLE
`vscode.NotebookCellOutputItem.text` linkifying, but not clickable

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#150283]
The text is colorized like a link, but cannot actually be clicked. 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/8586769/170058771-3f52568c-64ec-4f2c-a697-0a44e0193143.png">

**Comment by rebornix** [comment]
Interesting thing to tackle when we consolidate the text renderers.

**Comment by rebornix** [comment]
Let's track it there, we have changes coming in.
