### ISSUE TITLE
VS Code doesn't recognize the JS Date method toGMTString()

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [microsoft/vscode#150217]
The IDE doesn't recognize the Date object's `toGMTString()` method in JavaScript, even though said method is actually completely valid

I am using the last version of Visual Studio Code as of May 23, 2022

**Comment by mjbvz** [comment]
Duplicate of https://github.com/microsoft/TypeScript/issues/13622

We don't suggest this method because it is deprecated: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toGMTString
