### ISSUE TITLE
Feature request: Drag still drags window even over the title control

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#150208]
Love the new title control:
![image](https://user-images.githubusercontent.com/2644648/169872771-370bdb18-bdb3-4008-a5bf-4c896c087e4b.png)

My only problem is that I would often drag the window around by clicking and dragging the title bar. Since this takes up a large chunk of the title bar, I have less real estate to drag... but there's no reason the drag experience can't also apply to the area covered by the title control.

Can the drag of the title control bubble up to the title bar so that dragging the window works?

**Comment by jrieken** [comment]
> but there's no reason the drag experience can't also apply to the area covered by the title control.

There is a technical reason... Marking things as drag-region (`-webkit-app-region: drag;`) swallows all events and you won't be able to click onto things anymore... I can try adding the style while dragging but it might not be possible


<img width="113" alt="Screenshot 2022-05-24 at 09 15 34" src="https://user-images.githubusercontent.com/1794099/169971430-30660a44-14ff-4db6-b705-25538303ad2f.png">

🙃 that's more concerning here...

**Comment by jrieken** [comment]
>  I can try adding the style while dragging but it might not be possible

Yeah, I have tried to set the `drag` style during mouse down (with a delay) but that doesn't seem to have an effect 😢 Plan was to mark the element as app region drag when holding for 200ms

**Comment by jrieken** [comment]
related issue https://github.com/microsoft/vscode/issues/149290 (which caused this)

**Comment by Tyriar** [comment]
Can the top 1-2 pixels not be part of the drag element/target?

**Comment by jrieken** [comment]
yeah, it already should be like that, there is another PR in the works that increases the title bar height. with that merged, dragging be simpler again

**Comment by jrieken** [comment]
The title bar height is now aligned with the height of editor tabs. This allows to drag the window when clicking on the space above/below the CC.

https://user-images.githubusercontent.com/1794099/174738011-bc980c58-d4a9-4781-972a-cda9afe39acc.mov

That's the best I can do (and aligns with Slack etc). Set/unsetting the `-webkit-app-region: no-drag;` property while dragging isn't supported...

**Comment by jrieken** [comment]
To verify:

* enable CC via `"window.commandCenter": true`
* make sure you can drag the app window with the regions above/below the CC (see https://github.com/microsoft/vscode/issues/150208#issuecomment-1161349330)
