### ISSUE TITLE
Add a vertical ruler that follows the cursor

### ISSUE THREAD

**Issue by thewintersolstice** [microsoft/vscode#15027]
- VSCode Version: Code - Insiders 1.8.0-insider (dbf3ba74e6cf3b33687b7d47e321e642fc1e7562, 2016-11-04T10:15:01.593Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Steps to Reproduce:

1. No possibility to display a vertical ruler. See: SublimeText's "CursorRuler" and Atom's "Rulerz"
2. Thank you.

**Comment by kaiwood** [comment]
Those examples are all plugins, not options that should be built in. 

A quick search in the extension marketplace reveals: [cursoruler](https://marketplace.visualstudio.com/items?itemName=freakone.cursoruler)

There are a couple others that show all kinds of rulers/indent guides.

**Comment by thewintersolstice** [comment]
Thank you for your reply.
1: "CursorRuler" is a sad example. The line breaks where there is no text, also it's slow, also sometimes it falls behind. Do not know if this is due to limits of VSCode or extension itself.
2: Who decides what is an extension and what is part of core code? Why not make >File >Open an extension? Ability to create extensions is an option, not an excuse not to implement features in the core application. There are editors where having a vertical line is just a setting, just like showing the current line.
3: The "indent guide" feature is something different: it connects the beginning & end of blocks of code. Focus of my entry is to have vertical line that shows location of the cursor, just like there is a horizontal line - when both combined creates very useful "crosshair" effect.
4: Thank you.

**Comment by waldyrious** [comment]
I think it would make sense to tie this functionality with the current `editor.renderLineHighlight` configuration option -- i.e. it would make sense to add an `editor.renderColumnHighlight` option for this purpose -- which would be useful for the same reasons that the line highlight is.

Note that such a naming scheme would not only be more consistent with existing functionality, but it would also avoid confusion with terminology used for different purposes (i.e. indent guides and vertical rulers).

**Comment by waldyrious** [comment]
Also check out #30610, regarding the ambiguity of the term "ruler".

**Comment by rakkarage** [comment]
ya i recently set editor.lineHighlightBackground and expected to find a column highlight too - please & thanks

**Comment by alexandrudima** [comment]
There is `editor.rulers` e.g. `"editor.rulers": [10, 20, 40]`:

![image](https://user-images.githubusercontent.com/5047891/67412840-55970f80-f5c0-11e9-95a5-8125ed2ce5f2.png)

**Comment by waldyrious** [comment]
@alexandrudima please note that this request is for a _dynamic_ ruler that shows in what column the cursor is, the same way that `editor.renderLineHighlight` shows in what line the cursor is.

The misunderstanding is due to the conflicting meanings given to the term "ruler" (which was separately raised in #30610), but looking at the packages mentioned in the opening comment ([CursorRuler](https://libraries.io/sublime/CursorRuler) and [Rulerz](https://atom.io/packages/rulerz)) clarifies what OP meant.

**Comment by WhatsThatItsPat** [comment]
I'd like something of a "cursor crosshair." Just as the horizontal line is highlighted, I'd like the vertical to be as well.

**Comment by lilole** [comment]
How are the "upvotes" counted? Is it for all comments or just the top one? 

This seems like an obvious feature. I'm in some old HTML and JSP [sigh] files sometimes and this would save some of my sanity by helping me see open/close tags lining up.

And when it's time to factor code, top and bottom of "tall" blocks are much easier to see, even when I'm on a line somewhere inside the block. The indent guides help, but seeing line starts relative to my cursor helps more sometimes.

And 3.5 years is a long time. I just switched to Vscode from Atom and I'm surprised this simple basic useful thing isn't already here.

**Comment by lilole** [comment]
@alexdima does your bot count the upvotes on only the first comment? Or across all comments? I'll have to ask a few friends for some upvotes. Yay.
