### ISSUE TITLE
Why dont you add a shortkey for open folder?

### ISSUE THREAD

**Issue by ShangxuanWu** [Microsoft/vscode#15024]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|Lua|keyring|0.0.8|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1.
2.

**Comment by kaiwood** [comment]
Should be `ctrl+o` on Linux, the default open action (`workbench.action.files.openFileFolder`) which opens both – files **and** folders.
