### ISSUE TITLE
High CPU on startup

### ISSUE THREAD

**Issue by njmccann** [Microsoft/vscode#15020]
- VSCode Version: 1.7.1
- OS Version: Windows Server 2012 R2

Steps to Reproduce:

1. Open VS Code
2. CPU usage immediately climbs to max, even before the window is displayed, and remains in the 90% range.

This was not happening prior to running the update to 1.7.1 (I'm not sure what the previous version was).

![image](https://cloud.githubusercontent.com/assets/15730991/20026797/0f98a806-a2d8-11e6-8d68-68c5bc00aa90.png)

**Comment by mrmlnc** [comment]
Please, use search before create a new issue.

Related to #13139, #13981, #13882, #14870, #15014

**Comment by njmccann** [comment]
My apologies. This appears to be the same issue as #13981.
