### ISSUE TITLE
Add a setting to prompt before closing window

### ISSUE THREAD

**Issue by thewintersolstice** [Microsoft/vscode#15028]
- VSCode Version: Code - Insiders 1.8.0-insider (dbf3ba74e6cf3b33687b7d47e321e642fc1e7562, 2016-11-04T10:15:01.593Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Steps to Reproduce:

1. No matter what I choose, when I do either of the above, wanting to close all open files, I end up exiting the editor. What an annoyance! I'm just trying to close all files is all. Why is it exiting if I didn't ask it to exit? A program should not jump to conclusions. Is there a desire here to emulate Google Chrome's behavior? Chrome is not such a "perfect" browser, FYI, and closing the browser when I close all the tabs is not what I want. Don't assume. If I want to exit I'll do a >File >Exit.
2. Thank you.

**Comment by bpasero** [comment]
i am typically assigning this keybinding to close all files:

`{ "key": "cmd+shift+w", "command": "workbench.action.closeAllEditors" }`

**Comment by thewintersolstice** [comment]
Thank you for your reply.
1: If I understand correctly >View >Split Editor is like splitting the window into several viewports, for viewing different parts of same file, or different files in parallel. In the VSCode UI is the term "Editor" interchangeable with "Window" or is that another instance of the application? I'm not clear on that.
2: Why split limited to 3? 
3: Why split limited to vertical only? Because monitors are wide? What if I rotated my monitor? What if I did not rotate and want to see the full width of the code? I prefer to have the option to set the nature of the split.
4: Back to focus of this entry: there are cases where closing windows just closes the application, which is very very annoying. Closing the application should happen only if I do a >File >Exit. Or maybe there should be a setting: "Close application when all windows are closed: True/False",
5: Thank you.

**Comment by bpasero** [comment]
yeah, you can open up to 3 editors side by side. in 1.7 we added support to view the 3 editors either vertically or horizontally.

so what you want is to be able to close all editors and avoid that the window closes when you continue to press Ctrl+W?

**Comment by thewintersolstice** [comment]
Thank you for your answer.
1: Yes. (I'm saying "yes" when assuming that by "window" you mean "application".)
2: I hope my suggestion was pragmatic: "... maybe there should be a setting: "Close application when all windows are closed: True/False"..."
3: How do I set the horiz/vert view option? Where in the settings?
4: Thank you.

**Comment by bpasero** [comment]
@thewintersolstice see http://code.visualstudio.com/updates#_horizontal-layout

I will rename this issue to reflect what you are asking for.

**Comment by devrelm** [comment]
I would definitely like to see this, as well as a feature similar to Chrome's "Warn Before Quitting" setting.

What I would expect:

* Pressing `cmd+w` when no editors are open does nothing.
* Pressing `cmd+q` at any time prompts the user to hold `cmd+q` to exit
* Holding `cmd+q` at any time (whether or not the prompt is open) for a full second will exit

These would of course be configurable to have the existing behavior or the new behavior, and the existing behavior could be the default if it's what more people prefer. It could also be possible to have an option where holding `cmd+w` would also exit, though I expect that it would be overkill.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14710
