### ISSUE TITLE
Error during setup for ASCII/EBCDIC conversion

### ISSUE THREAD

**Issue by gnivet** [microsoft/vscode#150200]
![Screenshot at 2022-05-23 18-23-34](https://user-images.githubusercontent.com/10828978/169865850-f171ea99-0ab6-4006-b6cf-b7901c0ab36a.png)
Issue Type: <b>Feature Request</b>

When i try to get sources from filter i have an issue " Error during setup for ASCII/EBCDIC conversion"  this a  blocking  alert. 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.4.0-113-generic
Restricted Mode: No

**Comment by gnivet** [comment]
Before the previous bug " Error during setup for ASCII/EBCDIC conversion" i had this this warning message

Code for IBM i will not function correctly until the temporary library has been corrected in the settings. 
I don't have changed my temporary library.

**Comment by lszomoru** [comment]
@gnivet, can you please file an issue in [the extension's repository](https://github.com/halcyon-tech/vscode-ibmi/issues)? Thank you!

**Comment by KindSoftw** [comment]
Hello, I have the same problem and recently I did not have it and only when I access the PUB400, with another AS400 I do not have that problem 
![VScodeCssid](https://user-images.githubusercontent.com/68838891/170134304-3fe2336f-908e-4d6d-acd8-f6b70380513e.png)

**Comment by lszomoru** [comment]
@KindSoftw, please file an issue in [the extension's repository](https://github.com/halcyon-tech/vscode-ibmi/issues). Thanks!
