### ISSUE TITLE
[npm extension] top level npm_modules aren't excluded when detecting npm scripts in workspaces

### ISSUE THREAD

**Issue by jramsay** [microsoft/vscode#150204]
Does this issue occur when all extensions are disabled?: No

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.18363

In the course of investigating a Live Share performance issue we noticed an unusual amount of activity when we call: vscode.tasks.fetchTasks() against our Live Share workspace. The issue is that we include `node_modules` in the top level of our workspace file. The NPM extension isn't currently filtering this top level folder out - only node_module subfolders. I'm not sure if this is _by design_  as perhaps it was thought that users would never include this folder in their workspace? But we did - so perhaps others have too.  

Steps to Reproduce:

1. Open a workspace that contains a large _node_modules_ folder:

```
"folders": [
		{
			"path": "."
		},
		{
			"path": "../node_modules"
		}
	],
```
2. Call vscode.tasks.fetchTasks() from the extension.

**Comment by jramsay** [comment]
Here is a potential fix:

https://github.com/microsoft/vscode/pull/150205

**Comment by gjsjohnmurray** [comment]
Can't you use the `npm.autoDetect` setting at the folder level? Or a workspace-level `npm.exclude` pattern?

**Comment by jramsay** [comment]
Thanks for the ideas! Disabling auto-detect on our workspace will work for this particular instance of the issue. 

That said, wouldn't it make sense to filter top level _node_modules_ for everyone?  In our case it was causing about a minute perf slowdown as it was going through 2000 additional package.json files. It wasn't obvious what was causing the perf hit either or how to disable it.

The npm task detection code already applies as exclusion filter for node_modules under the relative folder. It just misses top level node_modules: 

```
let relativePattern = new RelativePattern(folder, '**/package.json');
let paths = await workspace.findFiles(relativePattern, '**/{node_modules,.vscode-test}/**');
```
