### ISSUE TITLE
VSCode updates fail with "Failed to create file handle" on Code.exe 

### ISSUE THREAD

**Issue by mkpi-pm** [microsoft/vscode#150294]
Issue Type: <b>Bug</b>

May 24 18:02:34.056 INFO Get file handle: "C:\\Users\\piotr\\AppData\\Local\\Programs\\Microsoft VS Code\\bin\\code" (attempt 16)
May 24 18:02:46.543 ERRO Failed to create file handle: Access is denied.

VS Code version: Code 1.67.0 (57fd6d0195bb9b9d1b49f6da5db789060795de47, 2022-05-04T12:06:02.889Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.70GB (1.52GB free)|
|Process Argv|--crash-reporter-id 54dd7099-a303-4c01-aa86-b8419efcd2e4|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|3.69GB (3.18GB free)|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
expressjs|ama|2.0.0
jest-snippets|and|1.8.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-chrome|msj|4.13.0
material-icon-theme|PKi|4.17.0
vscode-icons|vsc|11.12.0
material-theme|zhu|3.13.29
prettier-vscode|esb|9.5.0
LiveServer|rit|5.7.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by toddysm** [comment]
I am hitting the same error however the locked file is C:\Users\piotr\AppData\Local\Programs\Microsoft VS Code\policies\Code.admx

The bot's suggestion above is not good because this is happening during the upgrade process. Autoupgrade fails so we can't get from 1.67.0 to 1.67.2. Any suggestion for a fix?

**Comment by Montbra** [comment]
Try to run VS Code as admin. It worked here.

**Comment by ealva** [comment]
I'm getting variations of this access denied issue on multiple machines as well:

```
C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code\unins000.exe

An error occurred while trying to create a file in the destination directory:
Access is denied.

[Try again] [Skip this file (not recommended)] [Cancel installation]
```

I've never run VS Code as administrator so trying to do that seems like a workaround.

**Comment by JCoreMS** [comment]
Same issues for me with moving to 1.68 from the previous. Running as admin did the trick for me but was getting file handle error or file missing for the ADMX policy file in my profile.  Even after trying to close down every application running in the background including Teams, Office products, OneDrive, etc.
