### ISSUE TITLE
Editor-multicursor not working on Ubuntu

### ISSUE THREAD

**Issue by hamidufalke** [Microsoft/vscode#15022]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.8|
|debugger-for-chrome|msjsdiag|2.2.0|

---

Steps to Reproduce:

1. create a  file say index.html with a basic structure
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <header class="w3-container">
        
    </header>
    <main>
        <div class="main-top w3-container">

        </div>
    </main>
    <footer class="w3-large">
        
    </footer>
</body>
```
2. suppose i want to change the w3- prefix of the element classes to bk- using multicursor
3. click on the first occurrence of w3- which is the header element.
4. Alt+ click on the second occurrence in the div with class main-top
5. The second position is not select-able, with the cursor changing to pointer.

**Comment by smuuf** [comment]
Could it be that the default Ubuntu's default `alt+click` behaviour is causing this?

My problems with `alt+click` on **X**ubuntu were resolved with this: http://askubuntu.com/questions/270032/how-do-i-disable-window-move-with-alt-left-mouse-button-in-xubuntu

**Comment by hamidufalke** [comment]
Thank you for pointing me to the right direction, i used [gnome-tweak-tool]() and change the window action key setting to super, and it's working now.

**Comment by smuuf** [comment]
Glad I could help :)

This is related to this issue: https://github.com/Microsoft/vscode/issues/3091 and by extension to this: https://github.com/Microsoft/vscode/issues/3130.

I really hope the *vscode* team would try to enable customizing mouse shortcuts.

**Comment by BrOrlandi** [comment]
There's a similar workaround to GNOME Shell:
http://askubuntu.com/questions/118151/how-do-i-disable-window-move-with-alt-left-mouse-button-in-gnome-shell

**Comment by devils-ey3** [comment]
should I restart the pc after make the change ?

**Comment by devils-ey3** [comment]
@hamidufalke you just need to follow above processes. Then just restart your pc.
Then your current setting is `Alt+click` if you want to shift the short cut into `ctrl+click` then `selection>Switch to alter click for multi cursor`
