### ISSUE TITLE
VSCode crashes while trying to open file/folder/workspace

### ISSUE THREAD

**Issue by milan-r-shah** [microsoft/vscode#150215]
Does this issue occur when all extensions are disabled?: Yes/No --> YES

We have written the needed data into your clipboard because it was too large to send. Please paste.

---

Issue Type: <b>Bug</b>

Click on `File` and then click on either
- `Open FIle...` or
- `Open Folder...` or
- `Open Workspace from File...`

VSCode will do nothing. If you try to close (by clicking on the Close button/icon), it will crash.

(In my case, sometimes even my laptop gets restarted!)

Weirdly enough, the `Open Recent` option should/will work fine.

---

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.4.0-58-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2958)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 1|
|Memory (System)|31.01GB (19.89GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 1c4572df-1927-40c6-89dc-43d7aee6baf9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
githistory|don|0.6.19
gitlens|eam|12.0.6
vscode-pull-request-github|Git|0.42.0
vscode-edit-csv|jan|0.6.10
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.7.0
guides|spy|0.9.3
cmake|twx|0.0.17
clang-format|xav|1.9.0

</details>

**Comment by BryceVichiOJ** [comment]
Had the same issue. Reverting to v1.63.2 was sufficient for me.

**Comment by bpasero** [comment]
Sounds a bit like https://github.com/microsoft/vscode/issues/149788

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146584
