### ISSUE TITLE
Nodejs project intellisense not working

### ISSUE THREAD

**Issue by PrabhuKathiresan** [microsoft/vscode#150380]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Darwin x64 20.6.0
- Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
- Date: 2022-05-17T18:20:57.384Z
- Electron: 17.4.1
- Chromium: 98.0.4758.141
- Node.js: 16.13.0
- V8: 9.8.177.13-electron.0

Yesterday, My VScode got updated to version 1.67.2, and since then intellisense in my NodeJs Javascript project not working. I tired reinstalling vscode completely, still no luck.

Whenever I open any .js file, it goes to Loading intelliSense status and then no autocomplete is working.

**Comment by PrabhuKathiresan** [comment]
Yes, I am facing this even in insiders build with extensions disabled.

This time the intelliSense loads occasionally

https://user-images.githubusercontent.com/24243049/170317966-642ee2c6-113e-4453-9c51-7272b9774321.mov

.

**Comment by mjbvz** [comment]
Please try collecting the TS Server log:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 


 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by PrabhuKathiresan** [comment]
What other option do I have to send the tsserver.log?

**Comment by PrabhuKathiresan** [comment]
Hi,

removing node_modules and doing npm cache clean and installing the package dependencies, it works fine now.

Thanks for the help.
