### ISSUE TITLE
Looking for a way to hook the ClickLinkGesture from the TextEditor

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#150307]
I believe the ctrl+click gesture is implemented in ClickLinkGesture and this class has access to all kinds of goodies like ICodeEditor so it can listen to onKeyDown events and so on. I need the same capability (to listen to Control Key in TextEditor from my VS code extension) so I can build a consistent UI experience in my custom WebView. Any ideas how I can do that?

https://user-images.githubusercontent.com/18707114/170118103-09a1c428-29bd-4da4-b64d-a831500fff12.mp4

**Comment by mjbvz** [comment]
I think you're talking about just getting keypresses inside an unfocused webview, right? If so, this is by design. Webviews only get keypresses events if they are focused (much like normal dom elements).

They still get mouse events though and you can check the keyboard state on the mouse events (`e.ctrlKey`)

**Comment by lovettchris** [comment]
Yes I understand the webview is not getting keypress when it does not have the keyboard focus, that's why I'm asking for this new feature which is a way to get the ctrl key state from the VS code IDE via some new vscode api so that I can show an underline in my WebView when I Ctrl+Hover over a symbol that I'm showing there as shown in the video thereby making my WebView UI **consistent** with the text editor UI.

**Comment by mjbvz** [comment]
We don't expose low level information such as use key states to extensions. See https://code.visualstudio.com/api/extension-capabilities/overview for details

However as I noted you should be able to use `event.ctrlKey` on mouse events inside the webview to do what you are looking for

**Comment by lovettchris** [comment]
Yes, mouse move works and provides the ctrlKey state and I'm using that, but often people want to hit ctrl after they move the mouse over the symbol, and this is the customer complaint I'm trying to solve.
________________________________
