### ISSUE TITLE
Question: Does vscode support multi-line statements while debugging?

### ISSUE THREAD

**Issue by borgdylan** [Microsoft/vscode#15034]
If a debugger says that the current statement starts and ends on different lines, does vscode highlight the first line or all the lines in the range?

**Comment by isidorn** [comment]
VSCode uses a debug protocol to communicate to a debug extension which talks to the debugger. Currently the debug protocol supports stack frames only for a single line. More details about debug protocol can be found [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugProtocol.d.ts#L1015)
More details about debugger extensions [here](https://code.visualstudio.com/Docs/extensions/example-debuggers)

**Comment by borgdylan** [comment]
I was asking about a muti-line statement that is only represented by one sequence point in the pdb file.
