### ISSUE TITLE
Use "Run Python File" top-right buttom to run Python scripts with input arguments.

### ISSUE THREAD

**Issue by jazcarretao** [microsoft/vscode#150370]
Issue Type: <b>Bug</b>

When running this code:

```
import argparse

parser = argparse.ArgumentParser()

parser.add_argument("echo")
args = parser.parse_args()
print(args.echo)
```

With the following `launch.json`:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: hello",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": true,
            "args": ["hello"]
        }
    ]
}
```

Running pressing F5 works, but when clicking the "Run Python file" or "Debug Python file" buttom on the top-right corner of the GUI, this error persists:
```
usage: test.py [-h] echo
test.py: error: the following arguments are required: echo
```
The expected behaviour is that both ways to run the code should run the code on the same way (i.e. should be consistent with the way the code is run when pressing F5).

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 8, 7|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vim|vsc|1.22.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by roblourens** [comment]
Please file on the python extension. But I think that button runs your file directly without extra arguments.

**Comment by jazcarretao** [comment]
Thank you for your reply!
I am using Python 3.10.4.
Is it an expected behaviour that the button runs directly without arguments? If yes, why? I think this design decision should be documented clearly here, where the debugging configuration set up is explained:
https://code.visualstudio.com/docs/python/debugging
