### ISSUE TITLE
[html] closing tag intellisense always in lowercase

### ISSUE THREAD

**Issue by aboalwi** [Microsoft/vscode#15033]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|npm-intellisense|christian-kohler|0.1.3|
|text-transform|florianloch|0.0.2|
|Angular1|johnpapa|0.1.16|
|MDTools|seanmcbreen|1.0.0|
|code-settings-sync|Shan|2.2.3|
|nativescript-ng2-snippets|wwwalkerrun|1.2.0|

---
the problem simply is closing tag intellisense is always in lowercase
let's say i have:
 <StackLayout> ~~~~
 <
in this moment intillesense shows </stacklayout> 
this wasn't happening in the older versions plz fix it or give us the option to dos omething about it's frustrating :/
P.S. happens with any other element <P> -> </p> etc..

**Comment by aeschli** [comment]
fixed by https://github.com/Microsoft/vscode-html-languageservice/commit/e477a37194532bee648eaeff8cda9fa186fc91bd
