### ISSUE TITLE
Typescript language server dies unexpectedly

### ISSUE THREAD

**Issue by drodil** [microsoft/vscode#150361]
Issue Type: <b>Bug</b>

Opening up multiple projects (47 in my case) kills the Typescript language server from time to time. Apparently it's caused by low amount of free memory.

![image](https://user-images.githubusercontent.com/1178319/170242131-2f646633-465a-4e4d-b38a-4c73c0c311a0.png)

Steps to produce are:

1. Open very many typescript projects in the workspace
2. Wait

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id c3e28d05-a0b2-4adc-8196-0479ffd02448|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.1
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
gitlens|eam|12.0.7
vscode-html-css|ecm|1.12.2
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
go|gol|0.33.1
dupchecker|jia|0.1.7
eslint-language-service|man|1.1.3
vscode-docker|ms-|1.22.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
remote-containers|ms-|0.234.0
java|red|1.6.0
vscode-yaml|red|1.7.0
sonarlint-vscode|Son|3.5.3
autoimport|ste|1.5.4
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
vim|vsc|1.22.2
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment]
Please add some details on your setup. Do you need to be opening 47 projects?

**Comment by mjbvz** [comment]
You're likely running out of memory. Try restructuring your project so that not all of the project need to be loaded at once. You can also increase the memory limit once #151245 is addressed
