### ISSUE TITLE
Toggling split editor in group breaks centered layout mode

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode#150309]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: `1.67.2`
- OS Version: `Windows 10 x64 21H1`

Steps to Reproduce:

1. Make sure there's only one editor group in the workspace.
2. Toggle centered layout mode **on**.
3. Adjust the width of the editor to something less than 100%.
4. Toggle split editor in group **on**.
5. Observe that the editor **snaps back to 100% width** (**expected behaviour: width remains the same**).
6. Toggle split editor in group **off**.
7. Observe that the editor width reverts to that which was set in step 3.

**Comment by mitsukuri** [comment]
Still an issue in `1.70.1`

**Comment by mitsukuri** [comment]
And so is in `1.70.2`
What's worse, splitting an editor down also forces the resulting two occupy the full width of the viewport.

**Comment by ldelossa** [comment]
> What's worse, splitting an editor down also makes the resulting two occupy the full width of the viewport, thus aligning all text to to the left edge of the screen and forcing you to either turn your head or slant your eyes, which renders the very idea of centered layout useless.

This. 

I came here to see if this was an issue. It would be nice if *atleast* a split down could remain in centered zen mode, as there's enough space that it makes sense.

**Comment by mitsukuri** [comment]
So I think the correct resolution of this issue would be to retain the editor width and position after either horizontal or vertical split and let the user adjust the width of the centered layout manually if *e so deems necessary.

**Comment by mitsukuri** [comment]
A bit late to the party, but https://github.com/microsoft/vscode/issues/154738 fixed this!
