### ISSUE TITLE
make "format on save" toggleable

### ISSUE THREAD

**Issue by jamen** [microsoft/vscode#150348]
I use "format on save" with my projects, but if I make fixes in other projects that don't use formatting, I have to either temporarily disable format on save, or use "save without formatting" every time I save. It would be helpful if it could be toggled instead.

**Comment by jrieken** [comment]
> I use "format on save" with my projects, but if I make fixes in other projects that don't use formatting,

How about a project specific setting like we [do](https://github.com/microsoft/vscode/blob/3b4fb8e3b13e9ad5b49da04ee77817a636605417/.vscode/settings.json#L86)?

**Comment by jamen** [comment]
personally i dont do workspace or project settings, and i would have to add it to all my projects, so i still think having a togglable "format on save" would be better, but that's the best alternative yet.

**Comment by jrieken** [comment]
But how should toggle then work? Should it be persisted, e.g toggle the user setting, or do you want a volatile setting that doesn't stick around for long?

**Comment by jamen** [comment]
I was thinking toggle the user setting. I was basing this idea off "toggle word wrap", which I thought changed the setting too, but now that I look at it I guess it doesn't.
