### ISSUE TITLE
Test: Git ignore explorer exclusions

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#150383]
Refs: https://github.com/microsoft/vscode/issues/38878

- [x] macOS @tanhakabir
- [x] windows @rebornix
- [x] linux @alexr00

Complexity: 3

Authors: @lramos15,@JacksonKearl 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150383%0A%0A&assignees=lramos15,JacksonKearl)

---

We have finally closed out the highly upvoted #38878. Please test the feature in your local OS, connected to a remote of some kind, and opening a local folder in vscode.dev

The feature can be enabled via `files.excludeGitIgnore: "true"`

Some possible testing scenarios:

- Multiroot workspaces with different gitignore files in each
- Git ignores in sub directories
- Adding, deleting, modifying gitignore don't require reloads

The general theme is that if git excludes it then we hide it. The main caveat is git doesn't include something until the `gitignore` has been committed but the explorer will as it does not have access to the git process.

**Comment by rebornix** [comment]
This is working great! I like the fact that if a git-ignored file is opened in the editor, it will show up in the file explorer still. Neat!
