### ISSUE TITLE
Suggestion: Line selection Count

### ISSUE THREAD

**Issue by tehstun** [Microsoft/vscode#15036]
When selecting the lines within the file, a small count should appear along side the selected characters (bottom right hand corner) to display the amount of lines you have selected in your current like in some other popular text editors. 

Thanks,

**Comment by kaiwood** [comment]
That would be a perfect candidate to learn how to write a small extension…

Oh, wait… Here: [selectline-statusbar](https://marketplace.visualstudio.com/items?itemName=tomoki1207.selectline-statusbar) 😉

**Comment by tehstun** [comment]
Cheers Buddy!

**Comment by gandhis1** [comment]
Just because an extension exists doesn't necessarily mean it shouldn't be built-in functionality...just saying...

**Comment by tehstun** [comment]
@gandhis1  True, but because there is a extension, I doubt it will ever be a built-in function.

**Comment by gandhis1** [comment]
Not true...icons were an extension before they became built-in. The decision of extension vs. core should be made on the basis of what type of feature it is, I.e. fundamental vs optional. Showing the size of a selection seems fundamental to me.

**Comment by tehstun** [comment]
Well if we are working on that basis, I would of went back to atom if there was not this plugin, this feature is just too nice and handy sometimes when I like to follow some programming rules 👍

**Comment by t0neg** [comment]
Agree with @gandhis1 ,
Moveover VSCode already displays number of characters selected which makes less sense than displaying line count in many cases.
![image](https://cloud.githubusercontent.com/assets/1926448/22820166/e6041454-ef75-11e6-981e-d13c68798a1e.png)

Would be nice to have info as in notepad++:
![image](https://cloud.githubusercontent.com/assets/1926448/22820211/08f6b3e0-ef76-11e6-8cae-091756773999.png)

I would also consider it as an overkill to have a dedicated plugin for such basic functionality.
