### ISSUE TITLE
Allow for floating and/or movable sidebar views

### ISSUE THREAD

**Issue by gudvinr** [Microsoft/vscode#15038]
I'm using VS Code for a while (since 1.0 or so) and sometimes it's quite annoying that multiple sidebar views can't be used at once.

Most notable issue is that debugger view too tight and it's necessary to expand it every time. But then editor window becoming too narrow.
At the same time it's completely useless to have such wide view for explorer, git or search.
So, You have to drag or toggle sidebar every time when you need to debug.
If you have monitor that something less than 1080p it leads to real problems in usability.

The best solution in my opinion is to make at least debugger view detachable. Such approach is very convenient to use with dual-monitor configuration.

Other solution is to optionally move this watcher view to bottom panel where debug console located. Maybe it'll hard to use with debug console at the same time but JetBrains IDEs uses similar layout and it works fine.

**Comment by winseros** [comment]
+1 for this. 

Currently it is very annoying to constantly switch between "debug" and "explorer". Would be nice to see the "explorer" while debugging.

**Comment by eByte23** [comment]
+1 I feel this would be really awesome for console windows/(tray area) when debugging and other things!

**Comment by potz** [comment]
It would be awesome to have the debugger window on the right with the explorer/git on the left.

**Comment by RoyTinker** [comment]
Somewhat related: https://github.com/Microsoft/vscode/issues/10121
