### ISSUE TITLE
VScodeVim:  When type Chinese character, the editor appear blinking

### ISSUE THREAD

**Issue by yifan0414** [microsoft/vscode#150398]
**Describe the bug**
When I switch to Chinese input method and start inputing the character, The Chinese character is blinking.
**To Reproduce**
Just enter the insert mode, and switch the input method to Chinese, then type in some words.
**Expected behavior**
the normal visual performance
**Screenshots**
![iShot_2022-05-26_01 07 22](https://user-images.githubusercontent.com/45898625/170321133-fc17adc6-2c7a-478f-bc6b-f784cac75e61.gif)

**Environment (please complete the following information):**

- Extension (VsCodeVim) version: v1.22.2
- VSCode version: 1.67.2 (Universal)
- OS: Darwin arm64 21.4.0

**Additional context**
the english input method works normally

**Comment by SnakeHit** [comment]
When I uninstall the Vscode Vim extention, It's back to normal

**Comment by SnakeHit** [comment]
jupyternotebook appear the same issue

**Comment by VectorLu** [comment]
I test vscode 1.54.3 + vim 1.21.5, it's ok.
Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T11:00:52.911Z (1 yr ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin arm64 21.5.0

But 1.66+ this bug occurred.

Now I'm using the old version vscode, I hope this bug would be fixed soon and we who like vim could enjoy the newest version vscode as soon as possible :)

**Comment by zhanyeye** [comment]
**version: 1.63.2 is OK, but 1.64.2 this bug occurred**
+ https://github.com/microsoft/vscode/issues/154935
+ https://github.com/VSCodeVim/Vim/issues/7496

**Comment by hlovdal** [comment]
So since this is something that used to work but no longer is this sounds like a perfect use case for [`git bisect`](https://git-scm.com/docs/git-bisect).

Step 1: Verify that the issue occurs with the compiled development version in this repository.
Step 2: `git bisect start`
Step 3: `git bisect good 1.63.2`
Step 4: `git bisect bad 1.64.2`
Step 5...: investigate

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. This issue should be fixed with the new experimental setting `editor.experimentalEditContextEnabled` which will be made available in the next Insiders release. This issue will be closed.
