### ISSUE TITLE
Extension Icons are not visible in Extensions panel

### ISSUE THREAD

**Issue by andreagrandi** [Microsoft/vscode#15035]
- VSCode Version: 1.7.1
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Open the Extensions tab
2. I see this

![screenshot 2016-11-04 17 30 30](https://cloud.githubusercontent.com/assets/636391/20029464/82c22ba6-a344-11e6-9e87-13a6faba3561.png)

**Comment by mrmlnc** [comment]
Woooops 😉 

![2016-11-05_13-47-50](https://cloud.githubusercontent.com/assets/7034281/20029491/787f483a-a35e-11e6-95d0-b86b8b4635eb.gif)

**Comment by andreagrandi** [comment]
http://giphy.com/gifs/idiot-slapping-cat-j1zuL4htGTFQY
