### ISSUE TITLE
CSS mixin marked as error.

### ISSUE THREAD

**Issue by CDDelta** [Microsoft/vscode#15032]
Using Polymer sometimes requires the use of mixins to style certain elements but VSCode is marking it as an error although it is valid CSS.

- VSCode Version: 1.7.1
- OS Version: Windows 10.0.14393

Steps to Reproduce:
1. Create a css file add the following:
`.mixin-test {
        --mixin: {
          /* Rules */
        };
      };`

**Comment by mrmlnc** [comment]
Please, use search before create a new issue.

Related to: #14999

**Comment by octref** [comment]
Thanks @mrmlnc. Closing this in favor of #14999.
