### ISSUE TITLE
Windows: Broken installation after update

### ISSUE THREAD

**Issue by MiYanni** [microsoft/vscode#150330]
### Description
I am unable to open any files associated with VSCode when in this state. From my observation, it seems there is a *pending update* in Task Manager and for whatever reason, this causes issues with VSCode's ability to open new files via File Explorer. In VSCode, if I use `File` > `Open File...`, the file opens perfectly fine. My hunch this is some situation that is caused on Microsoft managed machines and something activates a VSCode update while it is running. My machine is **not** a SAW. It happens at random and I haven't determined an exact cause at this point. 

#### Other Notes
Closing VSCode in this state does not end any `Code.exe` instances in Task Manager. It also doesn't end the running `VSCodeSetup-x64-*.exe` either. Trying to run VSCode again while in this state also results in the same `main` JavaScript error (even after closing all `Code.exe` and `VSCodeSetup-x64-*.exe` instances(s). Only workaround listed at the bottom of the issue.

### Related Issue
https://github.com/microsoft/vscode/issues/126628

### Does this issue occur when all extensions are disabled?
Unknown. Restarting VSCode continues to cause the same issue. Thus, I cannot restart VSCode to see if an extension is to blame. Only workaround listed at the bottom of this issue.

#### VS Code Version
- Version: 1.66.2 (system setup)
- Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
- Date: 2022-04-11T07:46:01.075Z
- Electron: 17.2.0
- Chromium: 98.0.4758.109
- Node.js: 16.13.0
- V8: 9.8.177.11-electron.0
- OS: Windows_NT x64 10.0.19044

#### OS Version
Windows 10 Enterprise, 21H2, 19044.1706

### Steps to Reproduce
Exact steps to reproduce are unknown. However, I've only observed this on my *Microsoft office machine* (Redmond) over the last year or so. It has happened at least **half a dozen times**. It hasn't happened on any other machine.
1. While VSCode is open **and** a VSCode setup is pending in Task Manager, attempt to open a file with a file association to VSCode.
2. Observe the follow message appears and the file does not open in the current VSCode instance.

![image](https://user-images.githubusercontent.com/17788297/170159988-4581597b-41c4-470d-9a0a-ed7dbe59dfb8.png)

#### Update EXE in Task Manager
![image](https://user-images.githubusercontent.com/17788297/170161399-2cd4af6d-e12b-42c7-a12d-b3cc5071d083.png)

#### Update EXE file location
![image](https://user-images.githubusercontent.com/17788297/170163551-83bdb33e-b1dd-4525-9bcf-bed8620e6a1d.png)

### GIF of issue
![VSCode-JavaScriptError3](https://user-images.githubusercontent.com/17788297/170162616-0330aaec-e40c-4090-a238-cca152c45ec7.gif)

### Known Workaround
1. Close VSCode
2. Open Task Manager 
3. `End task` the currently running `VSCodeSetup-x64-*.exe`
4. `End task` all instances of `Code.exe`
5. Open the folder: `C:\Windows\SoftwareDistribution\Download\Install`
6. Run the `VSCodeSetup-x64-*.exe` located there and install VSCode
7. Launch VSCode

**Comment by aaaronic** [comment]
I also see this same issue on my Windows 10 Microsoft-owned desktop machine.

**Comment by MiYanni** [comment]
This is still happening for me. Just happened again today.
![image](https://user-images.githubusercontent.com/17788297/191391841-d85936ea-5cdb-45b3-acb0-eb17b953bd01.png)

Current version info:
```
Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

**Comment by MiYanni** [comment]
I've noticed within the last month or so, I come back to my work PC and now I have multiple of these dialogs appearing:
![image](https://user-images.githubusercontent.com/17788297/211105004-026a0b1c-8671-4d0a-a10d-6e4ce2a7c2e6.png)

> Setup has detected that Visual Studio Code is currently running. Please close all instances of it now, then click OK to continue, or Cancel to exit.

This prompt seems to have solved this particular issue since it is no longer trying to brute-force install VSCode while it is already running. For now, I'm going to close this issue since this prompt effectively blocks this issue from occurring.
CC @joaomoreno
