### ISSUE TITLE
vscode debug cannot step into typescript async function

### ISSUE THREAD

**Issue by thinking123** [microsoft/vscode#150352]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.67.2
- OS Version: mac OS  11.4
- Node.js: 16.13.0 
Steps to Reproduce:

1.
launch.json setting
```json
   {
      "name": "debugtsc",
      "program": "${workspaceFolder}/dist/index.js",
      "request": "launch",
      "skipFiles": ["<node_internals>/**"],
      "type": "node",
      "preLaunchTask": "build src/ts/index.ts"
    },
```

the test demo typescript file.
```ts
import fs from "fs/promises"

async function asyncFun() {
  const res = await fs.readFile("./src/ts/f.md")
  return res
}


function otherFunction(b) {
  console.log("bs", b)
}

async function run() {
  // debug :  step into can not goto asyncFun but skip it and step to otherFunction
  const b = await asyncFun()
  otherFunction(b)
}

run()
```

![image](https://user-images.githubusercontent.com/22145682/170222278-acdb7d46-d9d7-4a98-a181-f2412c877880.png)

**Comment by connor4312** [comment]
Please update your `target` in yours `tsconfig.json`. I'm guessing you have it set to ES6 or lower, which will cause TypeScript to downlevel async/await into iterators. This is much slower and also alters the control flow of your program, which is confusing when debugging.

Unless you're on Node 6, you can probably use a much more recent `target`: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

**Comment by thinking123** [comment]
tsconfig.json : { target : esnext}  works ,thanks
