### ISSUE TITLE
Test command center

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#150396]
Refs: https://github.com/microsoft/vscode/issues/149445

- [x] win @hediet
- [x] macos @misolori
- [x] linux @TylerLeonhardt

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150396%0A%0A&assignees=jrieken)

---

We have added a quick pick launcher that can be shown in the title bar, aka "Command Center". Please test that

* `window.experimental.commandCenter` enables/disables the command center
* the documentation for the setting points out what's required for the CC to show
* enabling the CC replaces the "textual window title" with fwd, bwd-buttons and an input-like button
* the input-like button triggers quick pick
* its text shows the current workspace name 
* its tooltip shows the full workspace title (as shown when disabling the command center, e.g current file and workspace)
* its dropdown opens quick pick in "help mode"
* the CC is centred unless space is tight (enable classic custom menu on win, linux, web)
* quick pick shows above the title bar when CC is enabled and below when disabled

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/170972694-79c9f0d4-bbec-437c-a35d-634f7902cc57.png)

Maybe add a placeholder when no folder is open

**Comment by bpasero** [comment]
Yeah I reported that as https://github.com/microsoft/vscode/issues/150786
