### ISSUE TITLE
Altair save as button doesn't work in the interactive window

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#150323]
Run this code:

```python
# %% Altair (vega)
import altair as alt
from vega_datasets import data

iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```
Click on the 'Save as' button on the plot

![image](https://user-images.githubusercontent.com/19672699/135346430-96f4a2f7-9506-4b02-94e6-d4fe2480d216.png)

Throws an error:

![image](https://user-images.githubusercontent.com/19672699/135346497-1a51e793-f4f9-4943-8361-7f162f7cf9a2.png)

**Comment by DonJayamanne** [comment]
The problem seems to be with the `simpleFileDialog.ts` class. We're unable to download files thats associated with Interactive Windows which has a custom scheme of `vscode-interactive` (which doesn't have any file system providers).

**Comment by DonJayamanne** [comment]
Related issue https://github.com/microsoft/vscode/issues/new?assignees=&labels=&template=bug_report.md

**Comment by rebornix** [comment]
@roblourens not sure if you know there is an easy fix for it. 

https://github.com/microsoft/vscode/blob/60c8307e9642d2d950584450efdd8bd240b056c9/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L862-L863

We generate `defaultDir` from `documentUri`, which is interactive notebook in this case, and using that as default dir for save dialog will lead to this exception.

**Comment by roblourens** [comment]
Seems similar to this case, like we should resolve it with the document path and the workspace URI

https://github.com/microsoft/vscode/blob/60c8307e9642d2d950584450efdd8bd240b056c9/src/vs/workbench/contrib/notebook/browser/view/renderers/backLayerWebView.ts#L703-L711
