### ISSUE TITLE
[MacOS] vscode didn't clean up child processes on exit

### ISSUE THREAD

**Issue by bdaduy** [microsoft/vscode#150369]
Issue Type: <b>Bug</b>

On MacOS, launch a typical (c#) .net core project, observing that several 'dotnet' processes are created in Activity Monitor. Neither stopping the debugging session nor exiting vscode program clean up those 'dotnet' processes.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 4b346ad9-3dad-4d65-af5d-63f9d794e6bb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
vscode-wasm|dts|1.3.1
vscode-great-icons|emm|2.1.86
vscode-solution-explorer|fer|0.4.5
shell-format|fox|7.2.2
csharp|ms-|1.25.0
cpptools|ms-|1.10.3
material-icon-theme|PKi|4.17.0
LiveServer|rit|5.7.5
vscode-icons|vsc|11.12.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by roblourens** [comment]
Please file the on C# extension repo
