### ISSUE TITLE
Make search results in terminal easier to spot

### ISSUE THREAD

**Issue by DanielSWolf** [microsoft/vscode#150345]
When I perform a search in the terminal window, the find results are highlighted by a very thin rectangle. In some places, this rectangle is orange, like this:

![image](https://user-images.githubusercontent.com/5963162/170202490-fd79b6e2-bcf5-4714-9692-eb993e4f6d90.png)

In other places (within the same search), it's gray, like this:

![image](https://user-images.githubusercontent.com/5963162/170202614-febf7e17-17f2-4619-a842-49d15d1ea517.png)

In both cases, I find these search results very hard to spot. It would help me a lot if they were more obvious, like they are within a text panel.

**Comment by Tyriar** [comment]
This is one of the big changes coming in the next version 👍 

![image](https://user-images.githubusercontent.com/2193314/170274373-be460ee3-2c7c-4403-afb5-9cbbe86b6a33.png)
