### ISSUE TITLE
Reenable localization tests once strings are translated

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#150324]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=172031&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=dc410bc6-42a7-5ad9-8707-fd38fc98382f

**Comment by rzhao271** [comment]
I'm building a custom Insiders to test one of the changes. The Linux localization smoke test seems to be failing consistently
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174937&view=logs&j=963754b8-394e-5caf-de5d-2790b068caec&t=f434ff82-bf7d-5375-d19c-a40b1bd2e1c5
