### ISSUE TITLE
`Toggle Line Comment` in Fenced code blocks for LaTeX doesn't work well

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [microsoft/vscode#150346]
This problem still occurs even if you disable all extensions and occurs in both stable and insider.

## Demonstration

Create the following Fenced code blocks for LaTeX in Markdown file.

````markdown
```latex
\documentclass{article}
\begin{document}
    Hello, \LaTeX{}!!
\end{document}
```
````

Then run `Toggle Line Comment` (<kbd>Ctrl+/</kbd>) on the line with `Hello, \LaTeX{}!!`.
You will get the following results:

````markdown
```latex
\documentclass{article}
\begin{document}
    <!-- Hello, \LaTeX{}!! -->
\end{document}
```
````

The correct result is:

````markdown
```latex
\documentclass{article}
\begin{document}
    % Hello, \LaTeX{}!!
\end{document}
```
````

### GIF animation

Execute `Ctrl+/` repeatedly

![toggleCommentOut-LaTeX](https://user-images.githubusercontent.com/75878492/170207101-e4905613-e604-4cab-a13e-8930c0718db1.gif)

## Version

```
 Version: 1.67.2 (user setup)
  Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
    Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
 Node.js: 16.13.0
      V8: 9.8.177.13-electron.0
      OS: Windows_NT x64 10.0.19043
```

```
 Version: 1.68.0-insider (user setup)
  Commit: c0769274fa136b45799edeccc0d0a2f645b75caf
    Date: 2022-05-23T05:17:12.256Z
Electron: 17.4.4
Chromium: 98.0.4758.141
 Node.js: 16.13.0
      V8: 9.8.177.13-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by nerdjfpb** [comment]
Hi @Yarakashi-Kikohshi 
Did you save the file? I disabled all my extensions for vscode insider and can't reproduce this issue. 

Is this still happening for you?

**Comment by Yarakashi-Kikohshi** [comment]
@nerdjfpb 

> Did you save the file? 

Yes. And all extensions are disabled.

> Is this still happening for you?

Yes.

-----

The insider version was updated to the following versions because has been available for updating. However, the problem continues to be reproduced.

```
 Version: 1.68.0-insider (user setup)
  Commit: 2260d7cca34384a2838c728850afdd38113ddb47
    Date: 2022-06-04T00:31:50.829Z
Electron: 17.4.6
Chromium: 98.0.4758.141
 Node.js: 16.13.0
      V8: 9.8.177.13-electron.0
      OS: Windows_NT x64 10.0.19043
```

**Comment by Priyankcoder** [comment]
@mjbvz Hi, I'm having the same issue. I'm new to the codebase. Can I try to solve this issue?

**Comment by Yarakashi-Kikohshi** [comment]
@nerdjfpb @Priyankcoder 

I had previously submitted similar issue. It may help to solve the issue. See <https://github.com/microsoft/vscode/issues/142960>.

**Comment by Priyankcoder** [comment]
@Yarakashi-Kikohshi thanks for this, It will help me solve this issue. I am working on this.

**Comment by Priyankcoder** [comment]
Hey @mjbvz, I made the PR. Could you please check it?
