### ISSUE TITLE
CSS Coloring issue

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15031]
![image](https://cloud.githubusercontent.com/assets/900690/20028902/e349528a-a33d-11e6-9427-fcb4aa814e30.png)

**Comment by wUFr** [comment]
similar in Less. Looks like problem is with both "user-select" and "-webkit-app-region"

![user-select_fail](https://cloud.githubusercontent.com/assets/10975377/20145093/0ac9e0e0-a69f-11e6-9799-1d91fe90d39c.png)

*also background should give me error, cuz invalid value :P*

**Comment by aeschli** [comment]
Fixed by 60bbe614895793f92d6a7fc21d29d068707f7ffb.

@wUFr The Less issue is unrelated. Each language has its own grammar. Please file a new issue.
