### ISSUE TITLE
DVORAK keyboard support

### ISSUE THREAD

**Issue by lewislepton** [Microsoft/vscode#15037]
- VSCode Version: latest 1.7.1
- OS Version: sieraa macOS 10.12.1

it would be nice if DVORAK key support was available.
so things like comment out hotkeys will be where your `/` is. now ive set it to something completely different.
plus many other hotkeys that are binded in completely different ways

so DVORAK support would be fantastic in general ;)

cheers

**Comment by harangue** [comment]
Isn't this an OS-level feature?

**Comment by lewislepton** [comment]
changing to DVORAK does do the regular keys, such as A-Z and everything else. but special keys such as commenting out, preferencesand a few others do not work.

i have rebinded them to something completely different.
typing ingeneral is fine, but certain special hotkeys are not usable in DVORAK

cheers

**Comment by mathiasvr** [comment]
This has been a problem for almost a year now #1492

**Comment by lewislepton** [comment]
cool. cheers for letting me know

**Comment by Tsmith18256** [comment]
I'm confused about what you are trying to accomplish here. Do you want the comment shortcut to be where the `/` is on QWERTY or where it is on DVORAK? Either way, these should both be achievable at the OS level and not be an issue of an application.

I use Programmer-DVORAK on Windows at home and OS X at work. I have the shortcut keys mapped to the QWERTY locations, but both of those operating systems let you use the shortcuts based on their DVORAK locations too (it was actually harder for me to get the QWERTY shortcuts).

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's upcoming Insiders build) appear to behave correctly for this keyboard layout

![image](https://cloud.githubusercontent.com/assets/5047891/24288943/8f2ce4dc-107f-11e7-8f48-162d2ea3a0aa.png)
