### ISSUE TITLE
Search over files input malformed or too small

### ISSUE THREAD

**Issue by waj-vx** [microsoft/vscode#150381]
Issue Type: <b>Bug</b>

While perfoming normal search. The input field stays single line even if longer content or is high enough but croped above. 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (8.23GB free)|
|Process Argv|--crash-reporter-id 4c56bc1f-8b4b-49ae-9527-2907f3f9fe5a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
calculate|aca|2.1.0
markdown-mermaid|bie|1.14.0
vscode-intelephense-client|bme|1.8.2
html-entities|chr|1.1.2
dendron|den|0.96.0
dendron-markdown-shortcuts|den|0.12.1
dendron-paste-image|den|1.1.0
githistory|don|0.6.19
foam-vscode|foa|0.18.3
google-translate|han|1.2.6
vscode-markdown-notes|kor|0.0.24
vscode-yaml|red|1.7.0
gotomanual|rha|0.2.32
partial-diff|ryu|1.4.3
change-case|wma|1.0.0
php-debug|xde|1.26.1
php-pack|xde|1.0.3
cursor-align|yo1|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by waj-vx** [comment]
![img](https://user-images.githubusercontent.com/76905608/170282854-60576495-72ab-49d1-b124-b972b96e75de.png)

**Comment by roblourens** [comment]
This is from [#136482](vscode-file://vscode-app/Applications/Visual%20Studio%20Code%20-%20Insiders.app/Contents/Resources/app/out/vs/code/electron-browser/workbench/workbench.html)

**Comment by kimadeline** [comment]
Verified: the input field expands if the search text is long enough:

<img width="350" alt="image" src="https://user-images.githubusercontent.com/51720070/171748841-f0c65063-5410-43ea-b556-9a05d83baf9d.png">
