### ISSUE TITLE
VSCode *integrated* terminal fails to execute command, but *system* terminal executes same command correctly

### ISSUE THREAD

**Issue by ultraGentle** [microsoft/vscode#150373]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:04.972Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.2.0

- OS Version: M1 MacOS 12.1

**Steps to Reproduce:**

1. Install `firebase-tools` (`npm install -g firebase-tools`)
2. Run `firebase` command from integrated terminal and system terminal

M1 Mac **system** terminal `firebase` command (e.g. `firebase emulators:start`) works as expected.

But VSCode **integrated** terminal errors on the same command (error given below).  

I use both Fish and Zsh, and the behavior is consistent for both: both Fish and Zsh run the `firebase` command in the Mac Terminal app, but not from VSCode's integrated terminal.  

Error given when running `firebase` from VSCode integrated terminal:
```
internal/modules/cjs/loader.js:59
const internalModuleStat = function (f) { return require('fs').internalModuleStat(f); };
                                                               ^

TypeError: require(...).internalModuleStat is not a function
    at internalModuleStat (internal/modules/cjs/loader.js:59:64)
    at stat (internal/modules/cjs/loader.js:143:18)
    at Function.Module._findPath (internal/modules/cjs/loader.js:645:16)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:951:27)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1024:19)
    at Module._preloadModules (internal/modules/cjs/loader.js:1276:12)
    at loadPreloadModules (internal/bootstrap/pre_execution.js:444:5)
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:76:3)
    at internal/bootstrap/pkg.js:7:1
```

I'm happy to do more troubleshooting, but I'm not sure where to start.  Thanks for suggestions!

**Comment by meganrogge** [comment]
Can you run `echo $PATH` in each of the terminals? If they differ, this should help

https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

**Comment by ultraGentle** [comment]
@meganrogge 

The `$PATH`s were the same except VSCode's was missing all the `:` between the paths.  

I followed the link you sent and tried the settings listed there, but that did not resolve the issue.  

Suggestions?

**Comment by ultraGentle** [comment]
@meganrogge There was a bug with a setting in `settings.json`: `"debug.javascript.autoAttachFilter": "onlyWithFlag",` caused the error above.  

I found this by iteratively bisecting my settings until I found the one that broke the `firebase` command.  

I suggest filing this as a bug, since there's no obvious reason that this setting should affect commands on the `$PATH` variable.
