### ISSUE TITLE
Nothing to build. 

### ISSUE THREAD

**Issue by chrispal136** [microsoft/vscode#150327]
Issue Type: <b>Performance Issue</b>

Nothing to build. Please put your source code files to 'C:\Users\User\3D Objects\BIGTREETECH-SKR-mini-E3-master\BIGTREETECH-SKR-mini-E3-master\firmware\V3.0\Marlin\Ender 3\Stock\Marlin' folder
============================================================================================ [FAILED] Took 0.75 seconds ============================================================================================
The terminal process "C:\Users\User\.platformio\penv\Scripts\platformio.exe 'run'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (10.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	  5904	code main
    0	    41	  4056	   utility-network-service
    0	   240	  5968	   window (Stock - Visual Studio Code)
    0	   176	  7740	   gpu-process
    0	   106	 11708	   shared-process
    0	    71	   660	     ptyHost
    0	    73	 11612	     fileWatcher
    1	    93	 11784	   issue-reporter
    0	   131	 11856	   extensionHost
    0	   113	   608	     c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\bin\cpptools.exe
    0	    11	  9916	       console-window-host (Windows internal process)
    0	    78	  7940	     "C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=11856
    0	     3	 12944	     C:\Users\User\.platformio\penv\Scripts\python.exe -m platformio -c vscode home --port 8010 --host 127.0.0.1 --session-id d9455d1ecd743cc5553021ceac8e96cd62166ad5 --shutdown-timeout 3600 --no-open
    0	    43	  5388	       C:\Users\User\AppData\Local\Programs\Python\Python310\python.exe -m platformio -c vscode home --port 8010 --host 127.0.0.1 --session-id d9455d1ecd743cc5553021ceac8e96cd62166ad5 --shutdown-timeout 3600 --no-open
    0	    11	  6180	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Stock - Visual Studio Code)
|    Folder (Stock): 7 files
|      File types: h(4) bin(1) ini(1) md(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.2
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
cpptools|ms-|1.9.8
platformio-ide|pla|2.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by roblourens** [comment]
This might be an issue with the platformio extension, please file on their repo
