### ISSUE TITLE
codicon-blank

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#150481]
Sometimes when you are building a custom UI in a vscode extension webview with codicons, it is handy to have a "blank" icon that is the same size as all other codicons so that you can get the correct alignment without having to hack a css style to create spacing the exact same number of pixels as the codicons.  For example, this dropdown filter widget has optional checkmarks:

![image](https://user-images.githubusercontent.com/18707114/170553479-b53a36ac-cde6-4566-a29e-6789e353b9c3.png)

![image](https://user-images.githubusercontent.com/18707114/170553458-5b76820e-e9b6-453f-b77a-73f0ef7c080e.png)

To make those checkmarks & text labels align correctly we had to do this ugly CSS hack:

```css
.codicon-blank {
    width: 20px;
    height: 16px;
}
```

it would be way better if you provided this CSS style in your codicon library...

**Comment by misolori** [comment]
Transferred issue to the codicons repo
