### ISSUE TITLE
Allow upgrading to a launch config from a terminal command

### ISSUE THREAD

**Issue by deostroll** [microsoft/vscode#150460]
For running a nodejs app, I would have set environment variables in my terminal session. Later I decide to debug it, but I have to open a separate JavaScript Debug Terminal and repeat the process of setting environment variables. 

There should be a way to convert an existing, say, powershell terminal, to a JavaScript Debug Terminal, so that I don't have to repeat setting my env variables again.

**Comment by connor4312** [comment]
I think the way I want to approach this scenario is to have a context menu action on shell commands that involve Node.js processes to "Save at launch configuration" (in this menu here, with shell integration on)

<img width="358" alt="image" src="https://user-images.githubusercontent.com/2230985/182725534-d6382eae-a45a-4b49-a77a-8ede96197e91.png">

I think that accomplishing the goal of wanting to "upgrade" from a normal shell into a debug environment, and also makes setting up launch configs quite easy.

**Comment by Tyriar** [comment]
This is blocked on https://github.com/microsoft/vscode/issues/151937 feature work

**Comment by Tyriar** [comment]
To elaborate on my comment above, I'm not a fan of adding a persistent "create launch.json" to the command decoration menu. Instead I think we should add it to the contextual menu as that's the purpose we're aiming to have for that (high quality suggestions).

**Comment by connor4312** [comment]
The generic path for this now is copilot-debug: https://code.visualstudio.com/updates/v1_96#_debugging-with-copilot
