### ISSUE TITLE
"editor.renderWhitespace": "boundary" does not work correctly

### ISSUE THREAD

**Issue by leomikezee** [Microsoft/vscode#15045]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra

Steps to Reproduce:

1. Set `"editor.renderWhitespace": "boundary"`

According to the description, the 'boundary' option does not render single spaces between words. However, this does not consistently.

<img width="247" alt="screen shot 2016-11-05 at 12 37 47 pm" src="https://cloud.githubusercontent.com/assets/7655600/20031859/cd507b4a-a354-11e6-84e4-3bb8d523cdb0.png">
<img width="246" alt="screen shot 2016-11-05 at 12 38 03 pm" src="https://cloud.githubusercontent.com/assets/7655600/20031860/cd528156-a354-11e6-9689-c6e783a762c9.png">

**Comment by alexandrudima** [comment]
Nice catch! There appears to be some issue in that code (that should be language agnostic) that is affected by the language tokens:

![image](https://cloud.githubusercontent.com/assets/5047891/20051088/69dd02ca-a4cd-11e6-96b6-9d458ed9e921.png)

**Comment by alexandrudima** [comment]
Looks like this is caused by a collision from the "fake" whitespace tokens we introduce and the tokens coming in from the grammar. The C grammar generates "whitespace leading" for the space between `int` and `size()`
