### ISSUE TITLE
Extension item height could be larger

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150449]
While helping Marketplace improve extension search I noticed that for most queries there are no more than 5 good results.
And we currently show an infinite list which depending on Monitor size would show 10 - 20 extensions.
Also we sometimes struggle with the small size of extension items in the list - not enough space for all the decorations we would like to render.

Based on the two above, I suggest we explore with increasing the vertical size of the extension items in the list.
Ideally this would allow to present the information in a cleaner way when users search for extensions.

I am not sure how this would effect the list of installed and recommended extensions. Ideally we would also increase the size of those to be consistent, but for those cases I am not convinced if it would be a win.

@sandy081 what do you think?

@daviddossett @misolori for ux thoughts

Example from my screen

![Screenshot 2022-05-26 at 15 45 18](https://user-images.githubusercontent.com/1926584/170500167-6660af7e-7c2c-4915-b132-f71f6f95c162.png)

**Comment by daviddossett** [comment]
From a visual standpoint it makes sense to explore giving these some breathing room. As far as solving for quality results, I don't know if making them bigger will necessarily solve that problem alone. It could be that we have a sort of "Top Results" section up top with the remaining results in another section. Just one idea off the top of my head.

**Comment by sandy081** [comment]
I agree its worth exploring it give more space for an extension in the viewlet. But this might impact if the size of the screen is smaller.

**Comment by isidorn** [comment]
I see this is merged and should be latest VS Code Insiders but I do not see any changes.
@esonnino am I missing something here?

**Comment by daviddossett** [comment]
@isidorn I'm seeing the latest after updating:

## Before
<img width="320" alt="CleanShot 2023-01-03 at 08 48 48@2x" src="https://user-images.githubusercontent.com/25163139/210402674-e6718e8c-5e9a-40e9-a300-ec6ff4d30a88.png">

## Current
<img width="328" alt="CleanShot 2023-01-03 at 08 49 32@2x" src="https://user-images.githubusercontent.com/25163139/210402742-1f04cb6b-fb2b-498b-8ce8-a1f571fd1b11.png">

**Comment by isidorn** [comment]
@daviddossett I just got the update. Looks ok to me - I will need some time to adjust.
Let's see what insiders users and the rest of the team says :)
