### ISSUE TITLE
.gitignore file not visible in file explorer

### ISSUE THREAD

**Issue by dotchev** [Microsoft/vscode#15047]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-node-readme|bengreenier|1.0.7|
|python|donjayamanne|0.3.24|
|vscode-exec-node|miramac|0.1.4|

---

Steps to Reproduce:

1. Open a directory with .gitignore file inside
2. .gitignore is not visible in file explorer
3. Go to File > type `.gitignore`
4. .gitignore is displayed in suggestions list
5. Select .gitgnore file,  it opens in the editor and appears in file explorer

Using default _files.exclude_.

**Comment by TheColorRed** [comment]
Strange, because I can see it in my editor, and I am also using the default `files.exclude`:

**Comment by bgse** [comment]
Can't reproduce either with 1.7.1 on Ubuntu, also default files.exclude being used.

**Comment by rebornix** [comment]
@dotchev can you help check with @bgse 's config?

**Comment by dotchev** [comment]
I could not reproduce it. Probably some temporary issue.

**Comment by intcreator** [comment]
For me this occurred right after I created the .gitignore file.  After opening the folder in the editor again, the .gitignore file appeared in the explorer.
