### ISSUE TITLE
The right mouse button fails in the py file

### ISSUE THREAD

**Issue by yutayouguan** [microsoft/vscode#150448]
Issue Type: <b>Bug</b>

When I write a py file, the right mouse click does not pop up the menu

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:04.972Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.25GB free)|
|Process Argv|--crash-reporter-id 3bcd8203-095a-4ba0-8497-9724b80d59b7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (45)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
html-snippets|abu|0.2.1
codesnap|adp|1.3.4
Bookmarks|ale|13.3.0
project-manager|ale|12.6.0
vscode-django|bat|1.10.0
path-intellisense|chr|2.8.0
githistory|don|0.6.19
python-environment-manager|don|1.0.4
vscode-html-css|ecm|1.12.2
prettier-vscode|esb|9.5.0
vscode-vibrancy|eyh|1.0.16
vscode-test-explorer|hbe|2.21.1
vsc-python-indent|Kev|1.16.0
krinql-vscode|Kri|0.1.1
vscode-leetcode|Lee|0.18.1
vscode-python-test-adapter|lit|0.7.1
document|min|2.1.21
vscode-filesize|mkx|3.1.0
vscode-language-pack-zh-hans|MS-|1.67.3
black-formatter|ms-|2022.1.11451003
gather|ms-|2022.3.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.3
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
vscode-jupyter-powertoys|ms-|0.0.3
test-adapter-converter|ms-|0.1.6
color-highlight|nau|2.5.0
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.4.1
korofileheader|OBK|4.9.1
material-icon-theme|PKi|4.17.0
material-product-icons|PKi|1.3.0
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|1.16.4
vscode-yaml|red|1.7.0
sourcegraph|sou|2.2.2
sourcery|sou|0.11.5
code-spell-checker|str|2.2.0
vscodeintellicode|Vis|1.2.21
url-navigation|Vit|0.0.15
code-translate|w88|1.0.19
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by karthiknadig** [comment]
@yutayouguan Please try with the latest verion of VS Code. If this continues to occur, please file a bug in the python extension repo. Sory for the delayed response on this.
