### ISSUE TITLE
IDE (Lint) issue

### ISSUE THREAD

**Issue by benlumia007** [microsoft/vscode#150472]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: Windows 10

Steps to Reproduce:

1. composer.json ( string does not match the pattern of 
```
^[a-z0-9]([_.-]?[a-z0-9]++)*+/[a-z0-9](([_.]|-{1,2})?[a-z0-9]++)*+$
```
I have tried multiple windows platform as well as my macOS
![Screenshot 2022-05-26 095225](https://user-images.githubusercontent.com/11844123/170542189-fbe2926e-89e3-461b-912a-53e659016786.png)

**Comment by jomino** [comment]
Same config, try without installed extensions, same issue,

Yesterday it was not there. No more extensions installed, none of change anything. Just re-open and voilà ....

**Comment by benlumia007** [comment]
would this be something be fixed and patched, I also tested older versions of VS code and they were all exactly the same issue.

**Comment by aeschli** [comment]
This needs to be fixed in https://github.com/composer/composer. The issue there is https://github.com/composer/composer/issues/10805
