### ISSUE TITLE
execution of unwanted code in terminal

### ISSUE THREAD

**Issue by f1atvoluntastua** [microsoft/vscode#150455]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Hello friends

in my terminal have I once written "conda activate spenv" and it gave an error message.
After running other files in terminal this "conda activate spenv" gets automatically running.

thank you for helping me with this.

Kind regards

**Comment by anibalsolon** [comment]
Hi @f1atvoluntastua 

From what I understood, you do not want that VSCode run the `conda activate` automatically, is that correct?

You can set this setting so it does not happen anymore:
`"python.terminal.activateEnvironment": false `

In the Settings UI, you can look for `Terminal: Activate Environment` and uncheck the Python one.
![image](https://user-images.githubusercontent.com/562525/170513014-f712a5ec-70f5-4925-9448-ebca7b642d04.png)

**Comment by karthiknadig** [comment]
The solution provided above is right. Sorry for this delayed response on this.
