### ISSUE TITLE
Remote explorer help and feedback section shows prompt

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#150426]
1. Using vscode.dev with the remote repositories and codespaces extensions installed
2. Open the remote explorer 
3. Make sure `Remote Repositories is` selected
4. Click on `Get started` under `help and feedback`

**Bug**
A picker opens 

![Screen Shot 2022-05-25 at 5 54 41 PM](https://user-images.githubusercontent.com/12821956/170393080-701ac41d-9b4a-468d-9f09-0bc5eb18482f.png)

I'm already in the `Remote repositories` section though so it should just take me to that extension's help

Version: 1.68.0-insider
Commit: d891b49fc0f8fc5e00591657ca225975952b09ca
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Embedder: vscode.dev

**Comment by alexr00** [comment]
@joyceerhl do you have a suggestion for https://github.com/microsoft/vscode/issues/150426#issuecomment-1151310921?

**Comment by joyceerhl** [comment]
Sorry I missed this--would `getVirtualWorkspaceLocation` help? 
https://github.com/microsoft/vscode/blob/2804f9884442d6c0f88d3ee0706f65e2ea4e2ade/src/vs/workbench/contrib/remote/browser/remoteIndicator.ts#L217

**Comment by alexr00** [comment]
I need something that will give me the `remoteName` that is listed in the `remoteHelp` of the extension. In this case that's `virtualfs`. `getVirtualWorkspaceLocation` gives me `github`. Any chance that the `remoteName` could be changed?

**Comment by joyceerhl** [comment]
`virtualfs` seems referenced in the remote indicator: https://github.com/microsoft/vscode/blob/0e20196eae2e98186c881b00de5eb6a9715264bf/src/vs/workbench/contrib/remote/browser/remoteIndicator.ts#L257 but we treat any resource that's not `file://` or `vscode-remote://` https://github.com/microsoft/vscode/blob/0e20196eae2e98186c881b00de5eb6a9715264bf/src/vs/platform/workspace/common/virtualWorkspace.ts#L11 as `virtualfs` so it seems a little inappropriate for Remote Repositories to claim `virtualfs` as the `remoteName`. (cc @aeschli in case I missed something WRT `virtualfs` in the remote indicator)

`getVirtualWorkspaceLocation(this.workspaceContextService.getWorkspace())` should evaluate to `{ scheme: 'vscode-vfs', authority: 'github' }`. Maybe `remoteName` should be `vscode-vfs` instead, and then you could check `getVirtualWorkspaceLocation(this.workspaceContextService.getWorkspace()).scheme`?

**Comment by alexr00** [comment]
@joyceerhl that sounds good to me!

**Comment by aeschli** [comment]
You can use `getVirtualWorkspaceAuthority()`

@alexr00 Maybe using `remoteName` for that is not super clean. The cleanest would be to add a second property `virtualWorkspace`

**Comment by joyceerhl** [comment]
That makes sense to me, so then the proposed fixes here are
1. Remote Repositories to declare `"virtualWorkspace": "vscode-vfs"` in its `remoteHelp` contribution rather than `remoteName`
2. Remote Help to pick up the value of `virtualWorkspace` and match it to `getVirtualWorkspaceLocation(this.workspaceContextService.getWorkspace()).scheme`

**Comment by alexr00** [comment]
This seems fine to me.
