### ISSUE TITLE
Filter for Terminal output

### ISSUE THREAD

**Issue by holtwick** [microsoft/vscode#150464]
The Debug Console has a nice filter feature:

<img width="908" alt="20220526-180828-capture-holtwick@2x" src="https://user-images.githubusercontent.com/49557/170528415-01622a65-23f1-47b4-b7ee-c5c444c3a79b.png">

**It would be great to have that in the Terminal view as well.**

Why?

In development often commands are started directly in the terminal and generate log output. It is hard to tell by the just using the "find" feature, how often certain outputs occurred and see at in a single glance how it developed.

**Comment by Tyriar** [comment]
We've made some improvements to find recently and it shows the number of occurrences. Currently this feature is out of scope due to the amount of changes that would be needed to make it happen.

**Comment by holtwick** [comment]
Ok, thanks for the feedback. It would really be a killer feature ;)

However, I found a workaround I'll leave here for others with the same needs. I ended up starting my project via VSCode Debugger and redirect the output to the Debug view, where I then can use the filter. See https://stackoverflow.com/a/51815414/140927 for details.

This is my config that does the same as `npm start` but redirects to Debug Console:

```json
{
  "version": "0.2.0",
  "configurations": [       
    {
      "name": "Start",
      "request": "launch",
      "runtimeArgs": [
        "start",        
      ],
      "runtimeExecutable": "npm",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "type": "node",
      "console": "internalConsole", 
      "outputCapture": "std",
    },   
```

**Comment by pradhyu** [comment]
when staring any command in terminal from VSCode you can pipe the putout to fzf, that provides full fuzzy finding capabilites in the terminal. 


example 
find .  | fzf 

this can be installed on windows or linux . please check https://github.com/junegunn/fzf
fzf is very powerful and handy tool  for development.

**Comment by CODEOrz** [comment]
> The Debug Console has a nice filter feature:
> 
> <img alt="20220526-180828-capture-holtwick@2x" width="908" src="https://user-images.githubusercontent.com/49557/170528415-01622a65-23f1-47b4-b7ee-c5c444c3a79b.png">
> 
> **It would be great to have that in the Terminal view as well.**
> 
> Why?
> 
> In development often commands are started directly in the terminal and generate log output. It is hard to tell by the just using the "find" feature, how often certain outputs occurred and see at in a single glance how it developed.


if in zsh, you can use 'grep' command to filter log manully.
`yarn start | grep 'video'`

then, the termial output will only remain the log lines contains 'video'

**Comment by holtwick** [comment]
> if in zsh, you can use 'grep' command to filter log manully. `yarn start | grep 'video'`
> 
> then, the termial output will only remain the log lines contains 'video'

This is certainly true, but it requires knowing what to filter for.

The feature I suggested is targeting “convenience”.

I usually start a long-running process and then figure out, something is going wrong. Filtering would allow me to investigate immediately instead of reproducing the situation.

However, I understand this is of the category “nice to have” and I probably should choose another workflow to achieve this. But since other IDEs like Xcode and JetBrains (as far as I remember) offer this feature, I believed it might make sense here too.

**Comment by cawoodmonads** [comment]
Unfortunately `"request": "attach",` doesn't support `"console": "internalConsole", `.
This really would be a helpful feature to filter the terminal.

**Comment by cawoodmonads** [comment]
For those looking for a C# config which works:
```jsonc
{
  "version": "0.2.0",
  "configurations": [
    {
      // Launches func.exe directly — stdout (incl. the child in-proc8\func.exe which
      // inherits the console handle) goes to the VS Code Debug Console, not the Terminal.
      // No breakpoints; use "DEBUG (DEV)" for that.
      "name": "RUN (Debug Console)",
      "type": "coreclr",
      "request": "launch",
      "program": "C:\\Program Files\\Microsoft\\Azure Functions Core Tools\\func.exe",
      "args": ["host", "start"],
      "cwd": "${workspaceFolder}/MyProject/bin/Debug/net8.0",
      "console": "internalConsole",
      "stopAtEntry": false,
      "preLaunchTask": "build (functions)"
    },
```
