### ISSUE TITLE
no touch response for close/minimize/maximize vscode window controls

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#150475]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

I can't touch the window controls to close/minimize/maximize in the Insiders Build on W11.  Note that it works in Stable v1.67.2.

The vscode window controls are responsive to a mouse however.

And, interestingly, the Layout Control button is touch-responsive.

Version: 1.68.0-insider (user setup)
Commit: 528ee1ae3daabe30c1307cf9dcd6e77eb96094bc
Date: 2022-05-26T05:16:43.433Z
Electron: 17.4.4
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.25120

**Comment by sbatten** [comment]
Can reproduce, thanks for reporting!

**Comment by sbatten** [comment]
The native layout controls from window controls overlay do not respond to touch events :(

**Comment by sbatten** [comment]
upstream issue filed https://github.com/electron/electron/issues/34364
