### ISSUE TITLE
Improve syntax highlighting for shell scripts

### ISSUE THREAD

**Issue by pdf** [microsoft/vscode#150428]
Currently highlighting for shell scripts is quite poor. Issue #23868 illustrates the issue quite clearly, however that was punted over to the textmate bundle and closed. On the tmbundle side, they claim that the bundle parsing works fine, and that the issue is that the theme does not implement the required targets, hence the issue there was also summarily closed, and the problem in VSCode remains unresolved.

Since _none_ of the VSCode themes work properly, including the default built-ins, and based on the feedback from the tmbundle authors, I have to conclude that the missing support is on the VSCode side, hence I'm re-reporting.

**Comment by JacksonKearl** [comment]
<img width="518" alt="image" src="https://user-images.githubusercontent.com/8586769/170533525-ad35f475-e9a9-476f-a7cb-f23b900a655d.png">
this is what I see with that snippet in the default theme. The issues mentioned in the original issue seem to be resolved.

**Comment by pdf** [comment]
I managed to reproduce your results by starting with a clean user-data-dir. Upon further investigation it appears that if you have ever applied a theme that does not support these code points, vscode will be forever unable to display them.

On launch with clean data dir:
![vscode001](https://user-images.githubusercontent.com/146192/170559000-c064b8a4-6697-4057-ac5f-7e896b6d44ff.png)
After applying an incompatible theme, then switching back to the default theme:
![vscode002](https://user-images.githubusercontent.com/146192/170559098-98810262-3d05-449c-9af0-57f8da3a6852.png)

From that point on, every subsequent launch displays as above, regardless of whether vscode has seen the buffer/file before, and whether extensions are enabled or disabled. I did manage to get correct output displayed once in this state, but never again.

**Comment by pdf** [comment]
Oh, I feel very foolish - when selecting a theme, I chose `Dark (Visual Studio)` because it looks like the correct and official theme. If I instead choose `Dark+ (default dark)` it does indeed highlight correctly. I will say that the distinction is somewhat confusing, and sent me down this rabit whole.

Sorry for the rest of the noise here.
