### ISSUE TITLE
Acesso negado

### ISSUE THREAD

**Issue by marcelovieiradesousa** [microsoft/vscode#150457]
Erro ao atualizar unins000.exe

**Comment by anibalsolon** [comment]
Oi @marcelovieiradesousa, voce deve tentar rodar o VSCode como Administrador. 

https://support.microsoft.com/pt-br/topic/executar-um-arquivo-em-lotes-com-privil%C3%A9gios-de-administrador-e1b4b29e-ce46-df49-a9eb-aa292d3d22c5

O problema esta relacionado a esse post no StackOverflow: https://stackoverflow.com/questions/64202257/visual-studio-code-access-denied-to-unins000-exe

Nesse post, tambem ha um PowerShell script que voce pode tentar rodar para nao precisar rodar VSCode como Administrador.

**Comment by joaomoreno** [comment]
/duplicate #47841

As a workaround, please disable Windows background updates by setting `update.enableWindowsBackgroundUpdates` to `false`.
