### ISSUE TITLE
Name in composer.json wrongly classified as invalid

### ISSUE THREAD

**Issue by bencresty** [microsoft/vscode#150444]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

VS Code thinks that name-value in composer.json is invalid, while it's perfectly valid according to the official `composer.json` schema doc (https://getcomposer.org/doc/04-schema.md#name) and even to NPM's `package.json` schema in case VS Code would like to force using that with composer.json.

Not sure at which version of VS Code this issue appeared for the first time. Just noticed it for the first time. And I'm 100% sure it's not caused by an extension as it's also throwing this issue when all extensions are disabled.

Also I cleared all editor cache with 'clear editor history' command and restarted VS Code and re-opened the file several times.

![image](https://user-images.githubusercontent.com/69322733/170467427-f47ac1bb-53d1-41b1-896a-bd6f016bb07f.png)

- VS Code Version: 1.67.2
- OS Version: Windows 10

Steps to Reproduce:

1. Start VS Code with or without extensions disabled and open the project with the composer.json
2. Open the composer.json in VS Code and see the wrong warning

[edit] The validation regEx VS Code uses for the name validation is invalid: the slash to divide vendor and projectname should be escaped with a backslash. I also don't think a `*` and `+` may follow after each other. Perhaps the `+` is a typo and should be a `/` here?

![image](https://user-images.githubusercontent.com/69322733/170479137-db5e1254-823d-4e30-b870-5b8f076dee99.png)

[Edit2] The regEx VS Code uses for the name is not the same as the official regEx as used by composer. This is what composer uses:
![image](https://user-images.githubusercontent.com/69322733/170480925-8b36b3d9-afe0-4348-b26e-9479471c4366.png)

**Comment by matronator** [comment]
Yep, I have the exact same issue. Doesn't matter what name I choose, it will always underline with warning it as invalid.

**Comment by aeschli** [comment]
We load the schema from https://raw.githubusercontent.com/composer/composer/main/res/composer-schema.json

The schema is maintained at https://github.com/composer/composer/blob/556450b15b6c47c55ffa46bd9048b410d56c3983/res/composer-schema.json#L9


There's already been an issue filed: https://github.com/composer/composer/issues/10805

Marking as duplicate

**Comment by bencresty** [comment]
> Marking as duplicate

Since when the first mentioned issue thread is marked as duplicate and should be closed in favour of the duplicate? Weird way of handling things

![image](https://user-images.githubusercontent.com/69322733/170966339-ed12d1b1-f0a3-4046-8ebf-76739e5ac972.png)

![image](https://user-images.githubusercontent.com/69322733/170966421-c9a7587c-9d84-4495-b2e5-729985c3f81b.png)

**Comment by aeschli** [comment]
The fix needs to be made in https://github.com/composer/composer/blob/556450b15b6c47c55ffa46bd9048b410d56c3983/res/composer-schema.json#L9

`/` needs to be escaped with `\`.

**Comment by bencresty** [comment]
@aeschli  Ah ok, I now see I had a misunderstanding. I didn't pay close enough attention. Otherwise I would've seen the link to the other issue was actually on the composer repo instead of on vs code. I understand now. Sorry for the misunderstanding and thanks for your action.
