### ISSUE TITLE
Format using custom keybinding no longer working

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#15040]
- VSCode Version: 1.7.1

- OS Version: Windows 10 Build 14959.rs_prerelease.161026-1700

Steps to Reproduce:

1.     { "key": "ctrl+e d", "command": "editor.action.format" }
2.  Use keycombo to format document

This worked in 1.6, stopped working in  @1.7.1.

I can make it work using editor.action.formatDocument, but I would expect the old command also still to work. (Or make it clear to the user they need to replace the old command as it no longer works)

**Comment by rebornix** [comment]
We've updated the command in 1.7.

**Comment by CoenraadS** [comment]
@rozzzly 

It is still listed in the keyboard shortcuts as an available command:

// Here are other available commands: 
// - editor.action.format

I agree about not spamming the user with popups for every minor change, but if it has been succeeded by another command, it should just be replaced with the new command.

**Comment by rozzzly** [comment]
@CoenraadS I agree, if they disabled it, then it should be removed from the list of available commands. But I guess this is being tracked in #15312 now.
