### ISSUE TITLE
Format Selection default to current line if no selection made

### ISSUE THREAD

**Issue by kinergy** [Microsoft/vscode#15043]
- VSCode Version: 1.7.1
- OS Version: 10.12.1

Steps to Reproduce:

1. Place cursor on a line without selecting a range
2. Choose Format Selection with keyboard shortcut

It would be nice if the current line is formatted instead of having to select the whole current line first.

**Comment by jrieken** [comment]
I like the feature (format line) but I am not so sure if this should be automagic or explicit.
