### ISSUE TITLE
Bracket pair colorization matches substrings of longer words

### ISSUE THREAD

**Issue by jlelong** [microsoft/vscode#150440]
I am the maintainer of VS Code basic latex language support.

The language defines `\langle` / `\rangle` as a bracket pair. This leads to wrongly highlight `\rangledot`

<img width="415" alt="Capture d’écran 2022-05-26 à 08 07 09" src="https://user-images.githubusercontent.com/2910140/170427478-5ae35179-44ac-4e3c-a515-bd02fefeae8a.png">

I believe this is related to https://github.com/microsoft/vscode/issues/132162. @hediet fixed it in e9e861fa4ead6529aefc84cf8004e7f9960576a4 by surrounding brackets using letters only with `\b .... \b`. However, in LaTeX every command starts with `\` and the fix does not apply.

This issue occurs on Version: 1.67.2 and also on Version: 1.68.0-insider (Universal)
Commit: d891b49fc0f8fc5e00591657ca225975952b09ca
Date: 2022-05-25T05:16:10.689Z
Electron: 17.4.4
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

This problem was originally reported at https://github.com/James-Yu/LaTeX-Workshop/issues/3304

**Comment by hediet** [comment]
https://github.com/microsoft/vscode/commit/e9e861fa4ead6529aefc84cf8004e7f9960576a4 should be extended to check if the bracket starts/ends with a word.
Only at those borders, `\b` should be added.

**Comment by Harshitr10** [comment]
hey @jlelong I am a beginner  in open source contributions . Could you  please  guide me how  too start contributing

**Comment by p4nu** [comment]
@Harshitr10 I'd start here: https://github.com/microsoft/vscode/wiki/How-to-Contribute

**Comment by Anthony-Eid** [comment]
Hi @jlelong I'm just starting out with open source contributions and just finished reading the how to guide you linked in this thread. 

I'm having some trouble understanding exactly what the issue is, could you please explain it a bit more? Is rangledot supposed to be highlighted as a whole?

**Comment by jlelong** [comment]
@Anthony-Eid This issue is actually already handled by PR #151204, which will be merged for the July 2022 release.

**Comment by hediet** [comment]
Verification steps:
* Install the LaTeX extension
* Verify that `\langle` and `\rangle` is matched, but not with `\rangle` in `\rangledot`

**Comment by RedCMD** [comment]
I would personally highly go against this fix
As it would disallow word based brackets inside word strings with no alternative (other than to reinvent the bracket highlighter again)
I have no example of any language being affected
But I would question the arbitration decesion to limit such function

Instead, I think LaTeX should fix the bug (which was present before coloured brackets) by just disallowing/allowing certain word based brackets via the `"balancedBracketScopes"` and `"unbalancedBracketScopes"` sections in `package.json`
![image](https://user-images.githubusercontent.com/33529441/180966233-77e85a77-d92f-4f97-b6c5-a07b51b9ef9d.png)

**Comment by hediet** [comment]
> I have no example of any language being affected

Let's discuss this in a separate issue once this actually is a problem!
