### ISSUE TITLE
Remote explorer getting started section still opens url even if you press escape

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#150427]
1. Using vscode.dev with the remote repositories and codespaces extensions installed
2. Open the remote explorer 
4. Click on `Get started` under `help and feedback`
5. See prompt (see #150426)
6. Press escape to close and cancel

**Bug**
A url is still opened 

Version: 1.68.0-insider
Commit: d891b49fc0f8fc5e00591657ca225975952b09ca
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36
Embedder: vscode.dev

**Comment by meganrogge** [comment]
I'm not seeing the section that Matt describes in the linked issue. 

![Screen Shot 2022-06-02 at 11 43 30 AM](https://user-images.githubusercontent.com/29464607/171703343-58b73215-4f65-4b60-a7cf-cb13e0a01349.png)

**Comment by joyceerhl** [comment]
The remote explorer is in the sidebar: 
![image](https://user-images.githubusercontent.com/30305945/171732517-d25a32ee-c30e-4e16-a185-2ffa26a6c274.png)
