### ISSUE TITLE
Gutter could not be themed

### ISSUE THREAD

**Issue by NoHomey** [Microsoft/vscode#15044]
- VSCode Version:
1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44
- OS Version:
Linux nohomey 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1.  Try to style gutter like in the [Kimbie dark theme](https://github.com/Microsoft/vscode/blob/be2143ddcb6bbc27bb2f04c04ecc308c1495fa0f/extensions/theme-kimbie-dark/themes/Kimbie_dark.tmTheme#L25-L37)

I used the following code:

```xml
<key>gutterSettings</key>
<dict>
    <key>background</key>
    <string>#ffffff</string>
    <key>divider</key>
    <string>#b3b3b3</string>
    <key>foreground</key>
    <string>#b3b3b3</string>
</dict>
```

But the gutter keeps beeing light blue:
![gutter](https://cloud.githubusercontent.com/assets/8791438/20031803/0a64a110-a386-11e6-809b-0b1d3fee083c.png)

**Comment by rebornix** [comment]
Close as part of #3112
