### ISSUE TITLE
i686 dependencies on x86_64 machine

### ISSUE THREAD

**Issue by r105m** [Microsoft/vscode#15041]
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. install code-1.7.1-1478180561.el7.x86_64.rpm package by yum on x64 

expected: sucessfully installed without 32 bit dependencies

result:
system tries to install i686 packages :

Установка:
 code                              x86_64                1.7.1-1478180561.el7                  /code-1.7.1-1478180561.el7.x86_64                141 M
Установка зависимостей:
 glibc                             i686                  2.17-157.el7                          rhel-7-server-rpms                               4.2 M
 libX11                            i686                  1.6.3-3.el7                           rhel-7-server-rpms                               610 k
 libXScrnSaver                     i686                  1.2.2-6.1.el7                         rhel-7-server-eus-rpms                            24 k
 libXau                            i686                  1.0.8-2.1.el7                         rhel-7-server-eus-rpms                            29 k
 libXext                           i686                  1.3.3-3.el7                           rhel-7-server-eus-rpms                            39 k
 libxcb                            i686                  1.11-4.el7                            rhel-7-server-eus-rpms                           202 k
 nss-softokn-freebl                i686                  3.16.2.3-14.4.el7                     rhel-7-server-rpms                               188 k

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13616
