### ISSUE TITLE
Parens matching seems to hang

### ISSUE THREAD

**Issue by nobody-famous** [microsoft/vscode#150470]
Issue Type: <b>Bug</b>

I'm working on a Lisp extension and have this code

    (write-string "April Compiler REPL
    Type )h for help
    Type ⎕off or press Ctrl-C to exit
      ")

If I try to comment it out, VSCode gets stuck, eventually giving an out of memory error. It didn't do that on 1.66.2.

    ; (write-string "April Compiler REPL
    ; Type )h for help
    ; Type ⎕off or press Ctrl-C to exit
    ;  ")

If I collapse it all down to one line, it works ok. Well, except that the parens are still highlighted inside the comment. That's a different issue.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (10.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
kotlin|fwc|0.2.26
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.6
alive|rhe|0.2.7

</details>

**Comment by hediet** [comment]
What file extension do you use for the lisp code snippet?

Also, it doesn't look like you have any lisp extensions installed.
It's hard to reproduce this when it depends on the extension that you develop.

Can you provide minimal reproduction steps?

Thank you!
