### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by youneskhouli** [Microsoft/vscode#15049]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

Would you kindly look into the annoyance that is writing contractions in strings and comments like "isn't, wasn't, ain't etc..." due to the automatic addition of a second ' character. Nothing big really, but really annoying none the less.

**Comment by 01000010** [comment]
Yea, it really gets annoying. Please fix it. :(

**Comment by rebornix** [comment]
Dup of #8850.
