### ISSUE TITLE
Emmet multiplication with multiple class names fails

### ISSUE THREAD

**Issue by wickyd** [Microsoft/vscode#15042]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|PowerShell|ms-vscode|0.7.2|

---

Steps to Reproduce:

1. Open an html document.
2. Type:

````
div.row>div.columns.large-6*2
````

The ouput is:

````
<div class="row">
  <div class="columns large-6"></div>
</div>*2
````

The output should be:

````
<div class="row">
  <div class="columns large-6"></div>
  <div class="columns large-6"></div>
</div>
````

**Comment by mrmlnc** [comment]
Hello, @wickyd,

I cannot reproduce your problem. You can provide a GIF or Video?

![2016-11-05_19-15-51](https://cloud.githubusercontent.com/assets/7034281/20031679/5a032e0c-a38c-11e6-9b5b-e0d24b16e4b1.gif)

**Comment by wickyd** [comment]
Well that is a first. I have experienced this in other software, but never a text editor.

I closed VS Code and re-opened it and it works.
