### ISSUE TITLE
Cannot run code

### ISSUE THREAD

**Issue by wheelfredie** [microsoft/vscode#150486]
Issue Type: <b>Bug</b>

Participants cannot run code on VS Code Live Share. Only host able to run.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by roblourens** [comment]
Please file this on the live share extension repo and explain some more.
