### ISSUE TITLE
Window controls are displayed over DevTools that are docked to the right side

### ISSUE THREAD

**Issue by IllusionMH** [microsoft/vscode#150521]
Issue Type: <b>Bug</b>

Looks like new WCO have static position and therefore overlap with DevTools controls in top right corner. And therefore block access to DevTools controls

Steps to reproduce:

0. Be on Windows
1. Open Developer Tools
2. Dock DevTools to the right side

![image](https://user-images.githubusercontent.com/1312662/170676418-682b5cd2-e663-4a58-8015-9f6bcbb5233a.png)

It would be ideally if it's possible to move those controls as before or at least force dev tools controls below windows controls if they are docked to the right and user is on Windows.

For those who want to move it (but cant't reach menu with dock options) use <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd> and type "Dock" to see available dock commands.

----

Another minor thing: When VS Code starts - I can see same green controls in the corner while while other window is just dark gray (background color).

VS Code version: Code - Insiders 1.68.0-insider (6428d0fc7dae5801cdaf2d160ac39a3dfc8f0c06, 2022-05-27T05:15:53.993Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (12.72GB free)|
|Process Argv|--crash-reporter-id 19aedffb-5c29-4248-9110-b5b20040c42f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by IllusionMH** [comment]
/assign sbatten -rebornix
as an author of #147947

**Comment by sbatten** [comment]
see https://github.com/electron/electron/issues/34129
