### ISSUE TITLE
Test: New `Configure Display Language` command

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#150567]
Refs: https://github.com/microsoft/vscode/issues/150565

- [x] anyOS @sana-ajani
- [ ] anyOS @alexr00
- [x] anyOS @brettcannon
- [x] anyOS @dbaeumer 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150567%0A%0A&assignees=TylerLeonhardt)

---

`Configure Display Language` use to look like this:
![image](https://user-images.githubusercontent.com/2644648/170779677-5ab96c1d-947b-41b6-a923-4a622f389599.png)

It needed some love. This iteration, we've improved the UX by:

* Including the localized language name in the quick pick item
* Adding an "available languages" section of language packs that aren't currently installed in the quick pick that will auto install the language pack

<img width="521" alt="image" src="https://user-images.githubusercontent.com/2644648/170780237-a2154f30-a1c5-4fc1-9dbc-1ca82841f889.png">

Go ahead and give the new experience a try and let me know what you think!

Additionally, we've added a `Clear Display Language Preference` command which will be more useful on the web... but still has some value here so it's also available on Desktop. This simply removes whatever you set previously.

The best way to see this change happen is by opening your runtime arguments file: `configure runtime arguments` command.

**Comment by alexr00** [comment]
Blocked by https://github.com/microsoft/vscode/issues/150860.
