### ISSUE TITLE
Test: Terminal find background and contrast improvements

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150554]
Refs: #147013, #149505, #149495

- [x] macOS @aeschli
- [x] linux @roblourens
- [x] windows @joyceerhl

Complexity: 4

Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150554%0A%0A&assignees=Tyriar,meganrogge)

---

In stable find results currently show using a border, this release adds the ability for "decorations" in the terminal (similar to monaco decorations) to change the background and foreground color of the cell. After this was done some related work happened including:

- Some bugs in the `terminal.integrated.minimumContrastRatio` color calculation
- Improving `terminal.integrated.minimumContrastRatio` to support moving luminance in the other direction, meaning if you have darker text on a dark background, the text can flip to be light instead of the previous `#000000`
- Terminal theme colors for find and selection are more closely aligned with the editor
- The terminal now uses the dotted/solid border style of find in high contrast themes
- New theme key `terminal.selectionForeground` which is set in the high contrast themes only by default

Some things to verify:

- Find match and highlights work as expected and look correct - one quirk here is that these colors are opaque in the terminal but transparent in the editor, so we need to handle showing/hiding the active match background specially
- The minimum contrast ratio feature still works as expected
  - Note that the experience is somewhat degraded when `terminal.integrated.gpuAcceleration` is not `on`. For example the foreground will not dynamically change after making a selection to respect `minimumContrastRatio` when `canvas` is set.
- Test high contrast themes and make sure selection foreground works

**Comment by roblourens** [comment]
`terminal.integrated.minimumContrastRatio` is cool, I hadn't seen that before. Everything seems to work great
