### ISSUE TITLE
Terminal File Link cannot jump to line of relative path in remote session

### ISSUE THREAD

**Issue by VALLIS-NERIA** [microsoft/vscode#150593]
Does this issue occur when all extensions are disabled?: Yes, with only remote-ssh left

- VS Code Version: 1.67.2 stable
- OS Version: Win10 20H2
- Remote OS Version: Ubuntu 20.04

This is similar to #148765, but only produces on remote sessions (tried remote-ssh, remote-wsl not tested).

Steps to Reproduce:

1. open a remote ssh session
2. 
![image](https://user-images.githubusercontent.com/13230610/170814594-16e51416-9f95-4de9-97c7-edcc9f034421.png)

ctrl + click on `memfs.cpp:12`, it jumps to the first line of memfs.cpp:
![image](https://user-images.githubusercontent.com/13230610/170814629-c64360a3-27c3-4e26-b1e2-e89335c23199.png)

3. ctrl + click on `/home/venn/code/task2-fileio-yitaooo-main/memfs.cpp:12`, it jumps to line 12 correctly:
![image](https://user-images.githubusercontent.com/13230610/170814657-88ef05ca-ef9e-48b1-874a-23d130f5ce9e.png)

Set log level to "Debug", seems their command differs slightly:
```
[2022-05-28 15:08:16.841] [renderer1] [debug] Opening link {"text":"memfs.cpp:12","bufferRange":{"start":{"x":1,"y":2},"end":{"x":12,"y":2}},"type":3}
[2022-05-28 15:08:17.144] [renderer1] [debug] User data changed
[2022-05-28 15:08:26.919] [renderer1] [debug] Opening link {"text":"/home/venn/code/task2-fileio-yitaooo-main/memfs.cpp:12","uri":{"$mid":1,"path":"/home/venn/code/task2-fileio-yitaooo-main/memfs.cpp","scheme":"vscode-remote","authority":"ssh-remote+vm"},"bufferRange":{"start":{"x":1,"y":4},"end":{"x":54,"y":4}},"type":0}
```

**Comment by leiysky** [comment]
Reproduced on my PC with remote wsl.

- VS Code Version: 1.69.1 stable

- OS Version: Win11 21H2

- Remote OS Version: Ubuntu 22.04 WSL

**Comment by dobos** [comment]
Same issue with remote ssh:

Version: 1.71.0 (system setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No

**Comment by Tyriar** [comment]
I tested this on WSL and it works, using the link `CodelensProvider.ts:12` opened the file on line 12 in the folder I had opened.

Note that it's expected the debug logs show different types of links, that's before the absolute link gets validated when the link is created and the one without slashes is a "word link" that gets validated on click.
