### ISSUE TITLE
No command to clear keybindings search history

### ISSUE THREAD

**Issue by SL-Lee** [microsoft/vscode#150544]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows 11

Steps to Reproduce:

1. Open the Keyboard Shortcuts editor (e.g., by using the `Ctrl+K Ctrl+S` keyboard shortcut).
2. Enter something into the search bar in the Keyboard Shortcuts editor.
3. Clear the search field (e.g., by pressing `escape`).
4. Press the up arrow key. The previously entered search term repopulates the search field.

Expected Result:

There should be a way (ideally through a command in the command palette) for users to clear the keybindings search history. This would provide a consistent experience with clearing search history for the find in files (`Ctrl+Shift+F`) view (where it is also possible to use the up/down arrow keys to cycle through search history), through the `Search: Clear Search History` command.

Actual Result:

Currently, the only way to clear the keybindings search history would be to open the global state database (located at `%APPDATA%\Code\User\globalStorage\state.vscdb`), locating the `momento/workbench.editor.keybindings` key in the `ItemTable` table, and clearing the `"searchHistory"` array (see screenshot below).

![image](https://user-images.githubusercontent.com/45960387/170724833-b170faf2-92ea-4723-bc98-098be861ec95.png)

**Comment by Daissy538** [comment]
Hey, I want to start with contributing to opensource projects. Is it okey if I look into this pr?

**Comment by sandy081** [comment]
Sure. That would be great.

**Comment by Newman1515** [comment]
# Microsoft Open Source Code of Conduct

This project has adopted the [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/).

Resources:

- [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/)
- [Microsoft Code of Conduct FAQ](https://opensource.microsoft.com/codeofconduct/faq/)
- Contact [opencode@microsoft.com](mailto:opencode@microsoft.com) with questions or concerns
