### ISSUE TITLE
Add command to move cursor to within the visible area of the viewport

### ISSUE THREAD

**Issue by joseph-iussa** [Microsoft/vscode#15058]
Feature request: Add a keyboard bind-able command to move to cursor to somewhere within (i.e. maybe the top or middle) the visible portion of the viewport.

I often navigate code by scrolling using `ctrl+up/down`. Once I've found the location I'm looking for the cursor is often by now off screen. The most convenient way presently available to then move the cursor to the desired location (i.e. somewhere around the middle of the viewport) is to note the desired line number and then use `ctrl+g`.

The desired feature would be a single keyboard bind-able command that moves the cursor so that it would then be within the visible area of the code editor.

**Comment by rebornix** [comment]
Our `cursorMove` command already support that

```
    {
        "key": "F4",
        "command": "cursorMove",
        "when": "editorTextFocus",
        "args": {
            "to": "viewPortCenter"
        }
    }
```
