### ISSUE TITLE
Test localized Core strings in insiders.vscode.dev

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#150577]
Refs: https://github.com/microsoft/vscode/issues/150578

- [x] web @tanhakabir (Edge or Chrome)
- [x] web @bamurtaugh (Safari or Firefox)

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150577%0A%0A&assignees=TylerLeonhardt)

---

This iteration we added support for localization of Core strings (not extensions) in vscode.dev. Just to say it one more time... Only Core strings for now. Not strings from extensions ... even if they're built-in extensions.

To try it, simply set your browser to a different language and go to https://insiders.vscode.dev

NOTE: we only support the languages listed in the [vscode-loc repo](https://github.com/microsoft/vscode-loc)

Try:
* Setting a supported language
* Setting a more specific supported language (so like `de-ch` (Swiss German) when we only have a `de` (German) language pack)
* Setting a language not supported (should default to English)

You should see most things localized. Keep in mind that if something isn't localized it's likely because:
* It comes from an extension
* It's a new string that hasn't been through the localization pipeline yet

If you feel confident something should be translated or have feedback on a particular string translation? Open that in https://github.com/microsoft/vscode-loc

**Comment by tanhakabir** [comment]
Am I expected to change my system language to reflect in browser or get a language pack? 
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/12758612/171216359-337ccafc-cd90-4661-9890-ae62e61f7bfa.png">

**Comment by bamurtaugh** [comment]
This is really neat to see, thanks @TylerLeonhardt!
