### ISSUE TITLE
Genie code runs in REPL but not with >Run>Run Without Debugging

### ISSUE THREAD

**Issue by davidstreader** [microsoft/vscode#150512]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.67.2 (Universal)
- OS Version: macOS 11.6.5

Steps to Reproduce:

1.  save in Julia file  test.jl:
2.  using Genie,  Genie.Renderer, Genie.Router
route("/David") do
    "Welcome VS-Code to Genie!"
end
println("*****");
up()
println("*****");
3.  This program fails to work when file is executed via >Run>Run Without Debugging
4. But works either when 4.a cut and paste the code into a Julia REPL  or 4.b in REPL type  include("test.jl");
5.

**Comment by roblourens** [comment]
Please file this on the debug extension you are using for julia

**Comment by davidstreader** [comment]
i am very old school and debug via print statements. But in this case the web pages being  available is a pass and the pages being unavailable is a fail.  Not to worry I decided to use websockets and side stepped Genie. I only submitted the report in the hope it might prove useful. The work around is simply to avoid using >Run>Run without debugging.  david
