### ISSUE TITLE
C++ 14 digit separators break C++ syntax highlighting.

### ISSUE THREAD

**Issue by tlemo** [Microsoft/vscode#15056]
- VSCode Version: 1.6.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a C++ source file
2. type:
int foo = 100'000;

**Comment by rebornix** [comment]
Are you using any extensions for C++ or just VS Code out of the box?

**Comment by aeschli** [comment]
duplicated of https://github.com/atom/language-c/issues/154
