### ISSUE TITLE
Last notebook cell is clipped with some notebook layout settings

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode#150573]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The last notebook cell rendering is clipped with these notebook layout settings:

```json
"notebook.insertToolbarLocation": "hidden",
"notebook.cellToolbarLocation": {
    "default": "hidden"
},
```

If I comment out these settings everything looks fine.

Notice how the scroll bar is fully scrolled to the bottom, but last cell is clipped. This happens irrespective if it has or not an output. Shown with output:

![2022-05-28_000147](https://user-images.githubusercontent.com/3753822/170789503-a05791cc-c60d-4da6-874a-64c5d05b92c8.png)

### VS Code Version

Version: 1.67.2 (user setup) Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19044

### Jupyter Extension Version

v2022.4.1021342353

**Comment by amunger** [comment]
This would be handled in the core.
I'm not able to reproduce this, do you have any other specific notebook settings?

**Comment by 2-5** [comment]
You are correct, there is one more setting required to reproduce: `"editor.scrollBeyondLastLine": false`

I can reproduce with all extensions except Python/Jupyter disabled and with just these three settings:

```json
"editor.scrollBeyondLastLine": false,

"notebook.insertToolbarLocation": "hidden",
"notebook.cellToolbarLocation": {
    "default": "hidden"
},
```
