### ISSUE TITLE
Syntax check error message duplicate

### ISSUE THREAD

**Issue by JohniFirst** [microsoft/vscode#150587]
Issue Type: <b>Bug</b>

When using the _dark high contrast_ theme that comes with the system，When there is an error in the grammar check, a wavy line and a double horizontal line will appear at the same time，Can't find entrance closed. I have all extentions turned off.
![image](https://user-images.githubusercontent.com/106364743/170835257-d15300bb-3819-475c-b69c-1a0a203244c5.png)

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (10.08GB free)|
|Process Argv|--crash-reporter-id c4553d57-53be-4f74-80a7-08a6d9633f0f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
path-intellisense|chr|2.8.0
javascript-ejs-support|Dig|1.3.1
jquerysnippets|don|0.0.1
threejs|En1|0.0.1
code-runner|for|0.11.7
vue-snippets|hol|1.0.4
easy-less|mrc|1.7.3
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.3
vetur|oct|0.35.0
material-icon-theme|PKi|4.17.0
java|red|1.6.0
LiveServer|rit|5.7.5
vue-vscode-snippets|sdr|3.1.1
tabnine-vscode|Tab|3.5.51
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.40.1
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.22.4
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.1
volar|Vue|0.34.16

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by JohniFirst** [comment]
I have install the VS Code version: Code 1.66.2 . This issue back to normal !

**Comment by hediet** [comment]
Can you provide the source as text, so I can copy it?
