### ISSUE TITLE
JavaScript Syntax Highlight: RegExp literals improperly parsed

### ISSUE THREAD

**Issue by zia-newversion** [Microsoft/vscode#15051]
- VSCode Version: 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44)
- OS Version: Linux Mint 17.2 (Ubuntu 14.04)

**Steps to Reproduce:**
1. In a JavaScript file, type a statement containing a division operation (`/`) followed by a RegExp literal (`/.*/`) as part of the same statement e.g. `var v = (a / b).toString().match(/\d*(\.\d+)?/)`
2. The code highlighter does not highlight the statement properly e.g. in the example provided in step 1, the code highlighter thinks that the `/` in `a / b` is where the RegExp literal `/\d*(\.\d+)?/` starts from and highlights the whole `/ b).toString().match(/\d*(\.\d+)?/` part one RegExp literal.
3. The same behaviour does not exhibit if the RegExp precedes a division operator in a similar fashion, e.g. in the statement `var v = parseFloat(s.match(/\d*(\.\d+)?/).toString(), 10) / 2.5`, the same RegExp literal is highlighted properly.

**Example:** (recreated from the "Steps to Reproduce" section)
![20160111-06-16060158-9091](https://cloud.githubusercontent.com/assets/4042217/20034648/9d651f02-a3e6-11e6-9a14-f010339b3437.png)

**Another example:** (this one is caught in the wild, free-range and organic)
![20160911-06-16060950-4ea9](https://cloud.githubusercontent.com/assets/4042217/20034666/d7f20968-a3e7-11e6-81ef-bc6776df1242.png)

Please forgive the obscene, blasphemic JavaScript in the above example(s?). The point is, it's syntactically valid. Also, in my experience, this did not happen before the recent VSCode upgrade to 1.7.1 so I'm presuming this relates to something that was changed in 1.7.1.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#349

**Comment by zia-newversion** [comment]
Sorry. I don't quite understand.

Microsoft/TypeScript-TmLanguage#349 was marked fixed, and closed. So the TypeScript-TmLanguage files are actually embedded into the VSCode resources archive? And I can only see this fix in the next update? Which is next month?
