### ISSUE TITLE
terminal link detection broken for file links with line numbers

### ISSUE THREAD

**Issue by bxantus** [microsoft/vscode#150526]
Issue Type: <b>Bug</b>

When you have a link with `file` scheme followed by line number (or optionally column info, like: `file:///C:/work/xdom/src/binding/lightBinding.ts:23`) the terminal will detect the link and open the file, but with an incorrect path (if you have the file already open in vscode, it will open the same file again).

This is pretty annoying when you have some files open, and try to jump to reported errors from the terminal (ex. deno reports errors in this format), then you'll have some files open twice, also the open file cache will be "dirty" (when you search for the file, it will be listed twice).
![image](https://user-images.githubusercontent.com/4958791/170686913-dda6810f-5682-439f-9f80-243ec11b824b.png)

### Example and steps to reproduce
Try to open a valid file link with and without filenumbers 
```
echo file:///C:/work/xdom/src/binding/lightBinding.ts
echo file:///C:/work/xdom/src/binding/lightBinding.ts:23
```

Clicking on the first link, will jump correctly to the file.

Clicking the second link, will open the file AGAIN showing a different name (or path for it), see screenshot below: 
![image](https://user-images.githubusercontent.com/4958791/170685784-9261c918-d828-4245-ac90-b08eeef9d948.png)

When you hover over the link with line number, only the path after `C:` is underlined (`/work/xdom/src/binding/lightBinding.ts:23`).

### Notes
The problems view is affected as well. When you check a file with deno, and enable deno problem matchers, problems view will open the file again (the same way as clicking from the terminal does).

### Additional Info

VS Code version: Code - Insiders 1.68.0-insider (6428d0fc7dae5801cdaf2d160ac39a3dfc8f0c06, 2022-05-27T05:15:53.993Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

Extensions: none

**Comment by Tyriar** [comment]
What's happening here: The uri link detector finds it but ends up parsing the path including the trailing :23 in the URI, which doesn't exist, similar to when you include a link like that in the editor

![image](https://user-images.githubusercontent.com/2193314/170717042-aaafe52a-7ce7-4ec7-8e36-35b82c5f432a.png)

It ends up falling back to the local link detector which gets confused with file:// links.
