### ISSUE TITLE
TitleBar Little Update

### ISSUE THREAD

**Issue by Samyak-Bumb** [microsoft/vscode#150529]
Please can you create **diffrent color's** for "_Minimize_", "_Restore Down_ / _Maximize_" & "_Close_" Btn's

---

![Screenshot (4)](https://user-images.githubusercontent.com/88429776/170699780-0473a193-3c07-45e3-b4a0-2b4515c1755a.png)
.

---

Reason :- 
  - It Will **Help Easly** to do the task without watching icon
  - If this will be added the **color's will match user theme** (The **theme Developer** can change color's)
  - It will give the user **New & Clean Look** 🤩

Thank You

**Comment by sbatten** [comment]
The control colors are controlled by the theme already using the title bar color. I am not sure what specifically you would like to change.

**Comment by Samyak-Bumb** [comment]
@sbatten 

I mean that the btn's **Hover clr** (Which I Mentioned Above)

Example:
  - Minimize = "#ff0000"
  - Restore Down = "#fff"
  - Close = "#fff000" (Default = Red)

**Comment by sbatten** [comment]
unfortunately, for the hover color this is not possible on the native controls provided by electron.
