### ISSUE TITLE
Spotify Control in VS-Code

### ISSUE THREAD

**Issue by iok-1s** [microsoft/vscode#150517]
It would be much better if we have a Spotify control in VS-Code with shortcuts.
Thank You

**Comment by gjsjohnmurray** [comment]
There seem to be several extensions that claim to do this.

**Comment by deepak1556** [comment]
There are extensions that seem to achieve the desired feature https://marketplace.visualstudio.com/search?term=spotify&target=VSCode&category=All%20categories&sortBy=Relevance . Closing as this is not in the current scope for VSCode core.
