### ISSUE TITLE
Option to remove [Run; Split Editor; Close; More actions] from top right

### ISSUE THREAD

**Issue by Hardaig** [microsoft/vscode#150585]
Feature suggestion: option to remove these UI elements.

![image](https://user-images.githubusercontent.com/104398879/170807053-b723729a-e272-4056-855b-06266ce7ae62.png)

Personally, I use them only rarely. This option would allow to have a slightly more minimal UI.

Also asked on [SO](https://stackoverflow.com/questions/72405740/remove-panels-in-vscode).

**Comment by sbatten** [comment]
#46403
