### ISSUE TITLE
Invisible symbol: right click to paste "€" in TERMINAL

### ISSUE THREAD

**Issue by zongwan** [microsoft/vscode#150589]
Does this issue occur when all extensions are disabled?: Yes/No
`Yes`

- VS Code Version: `1.67.2`
- OS Version: Windows X64 10.0.22000

Steps to Reproduce:

1. Open New Terminal: Menu Terminal-> New Terminal

2. Copy to clipboard
`echo "item=1000€"`

3. Right click in `TERMINAL`
✔ Command Prompt
`PS C:\Users\jeffery> echo "item=1000€"`
❌ PowerShell 7.2.3
`PS C:\Users\jeffery> echo "item=1000"`

4. Ctrl + V  in `TERMINAL`
✔ Command Prompt
`PS C:\Users\jeffery> echo "item=1000€"`
✔ PowerShell 7.2.3
`PS C:\Users\jeffery> echo "item=1000€"`

> PowerShell 7.2.3
![image](https://user-images.githubusercontent.com/1185694/170810470-f6b23d87-1c57-4182-a6a5-c33c48bda35f.png)

> Command Prompt
![image](https://user-images.githubusercontent.com/1185694/170810426-beacc237-91d6-457e-8a97-e967bd213cea.png)

---

https://github.com/PowerShell/PowerShell/issues/15418

**Comment by Tyriar** [comment]
I explained the problem in https://github.com/PowerShell/PowerShell/issues/15418#issuecomment-1143984462, let's track this as an upstream fix here.

**Comment by Tyriar** [comment]
The upstream issue is open again, let's close this now and track it there
