### ISSUE TITLE
Windows 10: Jump list no longer shows entries once you removed a single entry from "Recent Folders"

### ISSUE THREAD

**Issue by DanJ210** [Microsoft/vscode#15052]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14959
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vs-code-css-comments|ashhitch|1.0.2|
|python|donjayamanne|0.5.0|
|vscode-html-css|ecmel|0.0.30|
|php-intellisense|felixfbecker|0.0.11|
|auto-close-tag|formulahendry|0.3.4|
|auto-rename-tag|formulahendry|0.0.7|
|csharpextensions|jchannon|1.0.9|
|format-php|Kasik96|1.1.2|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|theme-railscasts|PaulOlteanu|1.0.0|
|vscode-icons|robertohuertasm|3.0.8|
|elise|schematrix|0.0.1|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---
I moved files from one directory to a whole new directory, so I removed all the recently opened folders because they all led to blank files, made sense as the paths didn't exist any longer but vscode did make the folders. Anyway, I removed them all and now when I open any and every folder in the new directory, nothing ever shows up under recently opened no matter what I do. Only blank windows with a blank untitled file shows up :(

Steps to Reproduce:

1. Remove from recently opened
2. Nothing comes back even if different directories.

**Comment by bpasero** [comment]
@DanJ210 from where exactly did you remove files? can you show a screenshot maybe for some more context?

**Comment by DanJ210** [comment]
Sure. I could have explained that better. I was installing an updated version of wamp server. I read that it was best to back up files and remove wamp to do a clean install. So that's why I changed directories. I removed the files, unistalled wamp, then re-installed wamp. The default directory wamp wants is C:/wamp64/ where all files go into the C:/wamp64/www. I wanted to try C:/Users/Danj/Wamp64/www... So that's why I moved directories. I suppose no screenshots are really needed as I could have explained that easily.
https://1drv.ms/i/s!AlnGeQSYLUVaooctpkePjjxxfRduzA

Also, I did get the folders to come back by unistalling and then reinstalling VScode.
https://1drv.ms/i/s!AlnGeQSYLUVaoocue5heGnkW7R1WRA

But that was the only way I got any recent files to show up as even new file paths didn't show up. Only individual files, not folders. Not only did the new file paths show up but the old ones did as well and I'm afraid to remove anything at all due to something not showing as recent when I open it. Some of the folders I have opened are not showing up either.

I know I didn't show screenshots of exactly what you were asking but I feel like explaining that like I should have was what was needed. If you've installed wamp before then you know the install paths. You don't need to know the exact install paths to know why I moved directories. But that's the only reason I moved directories. Let me know if there's anything else I can clear up. I'm afraid to remove from recent list now but I don't want the old stuff there either, no big deal but still would be nice.

**Comment by bpasero** [comment]
@DanJ210 does it help if you clear recent files (File > Open Recent) and then start opening things again?

**Comment by DanJ210** [comment]
@bpasero I didn't realize that was there! Well that does remove the old folders from recent in that list but it doesn't remove them when you right click the app icon. I did remove those manually but then the new paths wouldn't show up either. I did remove all of them to where I had nothing, then I cleared the recent files, and still nothing I opened would show up unless it was a file by itself or something. I didn't want to remove from the icon list forever, just to refresh what was showing up.

What I ended up doing was un-installing VScode again, then re-installed it, which then started showing up with the opened folders, the correct ones. So now I'm just not going to touch anything as I'm afraid what will happen without me knowing. As of now, the correct folders are showing up that I use and want. They only show up after I open them, then close them, then open a new window and open a folder that I hadn't yet opened. So idk what's going on but it seems a little hit and miss sometimes.

As of now I've got it back to the way I wanted but only after un-installing then re-installing. Figured I'd share in case this helped someone fine tune.

**Comment by bpasero** [comment]
I believe the issue here is that we do not update the list of recent folders while the application is running and you open folders or clear the list. You actually need to make the changes and then do a full restart before you see the recent folders changing. I think we could improve this by changing the list of recent folders while the application is running.

**Comment by bpasero** [comment]
I have updated this issue and extracted some work that I plan to do for November (https://github.com/Microsoft/vscode/issues/15093). For November we can improve the windows task list by:
* removing entries automatically when you try to open them and they do not exist anymore
* update the task list while the application is running instead of requiring a restart

This item here is still valid though and asks for doing a full validation of all paths right after startup.

**Comment by DanJ210** [comment]
Awesome! I love vscode I'm so thankful that it was made. I don't know if this is something that vscode already does but if I do remove something from the list that shows up from right clicking the icon, I don't want it permanently gone, I do want it to come back. I may just be cleaning up some. That may be what already happens and my experience is flawed because I had multiple Windows opened.

Otherwise that's it and you're welcome to close this issue! Thanks @bpasero for all your help and advisement!

**Comment by bpasero** [comment]
@DanJ210 so would you say that automatically checking on startup if the entries in the jump list still exist is not a good idea? I thought maybe it might be a good idea to not show the user paths to folders that do not exist anymore. Though I am not sure how other Windows apps behave here...

**Comment by DanJ210** [comment]
@bpasero Oh I would say that's a great idea! I don't mean to be confusing but sometimes I am. Yes that's a great idea. No one should want paths to remain that don't exist. 

I only meant that if I remove a folder path that does exist, whether intentional or accident, can or will the path come back the next time I open the folder? Not just in file>recent, but when I right click the icon?

**Comment by bpasero** [comment]
@DanJ210 the list of recently opened files and folders is always updated by your actions. So anytime you open a file or folder it should show up again in that list. For now you need a full restart, but I pushed a fix already for the next release so that this list updates live while the app is running.

**Comment by DanJ210** [comment]
@bpasero Well the reason I made this post initially was because I had removed everything from the list, from right clicking the icon, then I would open folders and it wouldn't come back. I would restart the computer but still wouldn't come back. Only way was after I uninstalled then reinstalled. Since all my settings and extensions are saved... I can make sure this is happening by trying to replicate the problem. So I'll remove everything from my list, I'll restart the app, try opening again and see if they show up. If not I'll then restart computer and repeat... If I still can't get them back then I'll uninstall and reinstall.

So I'll do this and make sure a user error isn't going on. I'm at school so I'll do this tonight and see what happens. But the features you came up with are still great so I'm glad they are coming up!

**Comment by bpasero** [comment]
@DanJ210 how do you remove an item from the list actually?

**Comment by DanJ210** [comment]
@bpasero You right click the icon, which I have pinned to my taskbar, and then you can right click everything in the list there.

**Comment by bpasero** [comment]
@DanJ210 wow, I can reproduce. The good news is that the entries come back as soon as I reinstall VS Code. However, without that the entries are all gone. I fear this is something to follow up with the Electron folks.

Let me finally rephrase this issue to capture that one :)

**Comment by bpasero** [comment]
I mentioned this in https://github.com/electron/electron/pull/6826

**Comment by DanJ210** [comment]
Awesome! I'm glad to have helped lol! Now I can feel like I've helped contribute to a program I love using! So should I close and comment this or how does that work?

**Comment by bpasero** [comment]
Thanks to some help from Electron, I was able to come up with a fix. The trick is to respect the choice of removed items in the jump list and not add them again, otherwise Windows will not show any entry in there.

@DanJ210 thanks for pushing on this issue, I think the behaviour now is really good.

**Comment by bpasero** [comment]
To verify:
* on Windows open some folders
* verify you see them in the "Recent Folders" list
* remove some entries from the list using right click
* verify the entries are gone
* verify the entries are still gone after a restart but other folders still show up

**Comment by DanJ210** [comment]
@bpasero Hey! I actually just had something strange happen where all of a sudden... All of my recent folders in my jump list went away, I have nothing there now. I didn't do anything at all, didn't remove anything, just went to open a folder and they were all gone. This was yesterday evening, after restarting program and computer, they still won't come back. Separate files will show up but not ones in those folders. So I may have to reinstall again. Should I be posting about this here?

**Comment by bpasero** [comment]
@DanJ210 that sounds exactly like the issue I fixed. I had the same issue and only a uninstall and reinstall helped.

Now if you want to give my fix a try, you could install our insider release to see how it behaves there: 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by DanJ210** [comment]
@bpasero Ok just making sure I did understand correctly. Yes I would love to try an insider release! I'll go ahead and install it now! I now that it says that I can use both the insider and stable build together but I may only need the insider build. Thanks for the heads up I will let you know what I experience!

**Comment by DanJ210** [comment]
@bpasero Perhaps you can help me with one more thing...

![vscode - github](https://cloud.githubusercontent.com/assets/16159685/20116315/c2a90bb8-a5c9-11e6-99a7-86aa722821c4.png)

Is there something I should have installed or am missing? Is this from an extension I may have installed without knowing exactly what it does? I'm still new to using all of this but am learning quickly. I could also Bing this and see what happens.

**Comment by bpasero** [comment]
Easy to see if this comes from an extension: From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions`

**Comment by DanJ210** [comment]
@bpasero Excellent. I will try it soon. I assume that the same thing but with enable will enable them all again! If I recall correctly, the message came up when I first launched the inside version without any extension installed so I don't know why I even mentioned extensions.

I feel like I'm being a little annoying here so I don't want to blow you up with silly things.

**Comment by DanJ210** [comment]
@bpasero One last thing, if certain extensions aren't working in the insider build. 1.8.0, should I report that or is this something that developers would have to update on their end?

**Comment by bpasero** [comment]
Extension issues should be reported against the extension GH repo 👍
