### ISSUE TITLE
Auto complete guided by remote ipython server

### ISSUE THREAD

**Issue by Hong-Xiang** [Microsoft/vscode#15054]
It would be great if we can develop simple *nix python programs in our windows PC. I'm working on Tensorflow, it has a good web based support via jupyter notebook and tensorboard. But they are not good enough for develop. I can access .py files in *nix system from VS Code in windows PC, but missing auto complete since I can not install TensorFlow on windows.

**Comment by rebornix** [comment]
I'm not sure whether it's a valid feature request for https://github.com/DonJayamanne/pythonVSCode but it's not a Code issue. Please file feature request there if you want or write a separate extension for it.
