### ISSUE TITLE
[css] provide class names as workspace symbols

### ISSUE THREAD

**Issue by saltcod** [microsoft/vscode#15053]
- VSCode Version: any
- OS Version: any

Hey all! Really starting to like VSCode over Sublime. Slow going but I'm getting there! 

One thing I really, really miss is goto anything, particularly as it pertains to sass / css writing.  In Sublime, I just do `goto anything`, and start typing the css classname I'm looking to edit and it brings instances of that selector in all files. Really handy for front-enders like me.

Appreciated!

**Comment by rebornix** [comment]
It looks like a good extension candidate

**Comment by benfrain** [comment]
Sad to see this closed as it really feels like goto anything SHOULD be part of the core product. It’s still an area where VSCODE is unable to compete with Sublime.

**Comment by saltcod** [comment]
Super sad to see this one closed. 

Polled all the front-end people at my company (~15 of us) and almost all use this feature in Sublime or other editors that have it. 

As a front-ender, I'd say I do 50% of my navigating throughout files via css selectors.  Would love a reconsideration on this one.  

Thanks all.

**Comment by aeschli** [comment]
Reopening then. Please vote with 👍 on the description.

**Comment by saltcod** [comment]
🙌 

Thank you!  Greatly appreciate that.

**Comment by emeaguiar** [comment]
👍🏽

**Comment by benfrain** [comment]
@aeschli Hello Martin, just curious, how many votes do we need to get this one into the queue?

**Comment by benfrain** [comment]
@aeschli is there any chance of getting this on a iteration plan? Seems odd to be able to search across workspace for JS functions but not CSS selectors. Remains a key shortfall for users used to Sublime's superiority in this area.

**Comment by aeschli** [comment]
@benfrain Me and @octref are lobbying to for https://github.com/Microsoft/vscode/issues/47331 which amongst other this would make the css & html language service multi-file aware. But so far other issues got higher priority. Also there are custom extensions that provide that functionality.

**Comment by benfrain** [comment]
Thanks for the update Martin. I’ll keep an eye on the related issue also then. 👍
