### ISSUE TITLE
Description is cut off when tabs are disabled and space is narrow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150533]
The "..." is missing:

![image](https://user-images.githubusercontent.com/900690/170702610-e41f567c-4e8b-4051-ac2f-d3efa5887664.png)

**Comment by rchiodo** [comment]
@bpasero do you have any verification steps? The original screenshot isn't clear to me what the problem is.

**Comment by bpasero** [comment]
Yeah: disable tabs, open a file where the description portion is long (e.g. a deep folder) and then make the editor narrow enough.

**Comment by sandy081** [comment]
@bpasero I still do not see `...`

![image](https://user-images.githubusercontent.com/10746682/171837139-869fed57-8f07-4b09-974b-9c3291d934d6.png)

**Comment by bpasero** [comment]
Yes sorry my bad, my fix is for when breadcrumbs are disabled, I think with breadcrumbs enabled the "..." makes little sense because you can scroll then.
