### ISSUE TITLE
Test: Hover lock feature

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150557]
Refs: #115034

- [x] macOS @chrmarti
- [x] linux @TylerLeonhardt
- [x] windows @luabud

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150557%0A%0A&assignees=Tyriar)

---

A new accessibility feature has been added that will lock a hover in place when the alt key is pressed, this allows the user to mouse over much easier in the extensions view for example which has a scroll bar and sash in-between it and the hover. This feature works on any hover, regardless of whether it's declared to allow the mouse to hover it (eg. extension view) or not (eg. activity bar icons). There's a somewhat subtle indicator for this where the border gets a width of 2px instead of 1px.

Normal hover:

![image](https://user-images.githubusercontent.com/2193314/170743417-ff1e1572-6331-4a9a-b3c0-ce3acb07427b.png)

Locked hover:

![image](https://user-images.githubusercontent.com/2193314/170743477-197a6d1a-ed07-489e-a2a4-926218fe1b29.png)

The current design is that alt will lock the current hover and it will not hide until either:

- Another hover is shown
- Alt is released when the cursor is not over the hover or hover target
- Alt is released on Windows as the event gets canceled by the file menu

Any ideas related to discoverability are welcome, currently we will rely on the accessibility page on the website to surface this feature to users who need it.

**Comment by chrmarti** [comment]
Are hovers in the editor also expected to support this? (Not seeing it on Mac.)

**Comment by Tyriar** [comment]
@chrmarti no hovers in the editor don't support this as they're handled by a different mechanism and are generally hoverable already.

**Comment by chrmarti** [comment]
Also not expected to work on simple tooltips (like on toolbar items in a viewlet), I assume. (Just to clarify "works on any hover" in the instructions.)

For discoverability: Maybe a hint could be shown when the mouse hovers on the hover or the hover gets focus (by a mouse click). Like `Hold Alt to keep` in the top left or bottom right corner inside the hover.

**Comment by Tyriar** [comment]
@chrmarti yep, I think the plan is to eventually transition all native hovers to the custom hover so they would get covered then.

> For discoverability: Maybe a hint could be shown when the mouse hovers on the hover or the hover gets focus (by a mouse click). Like Hold Alt to keep in the top left or bottom right corner inside the hover.

Bit worried about the amount of noise that would generate, let's put it out and see what feedback we get.
