### ISSUE TITLE
Debugging vscode extension in another IDE

### ISSUE THREAD

**Issue by MohammadMD1383** [microsoft/vscode#150597]
I had a look at `launch.json` the only thing I found was to start vscode with `--extensionDevelopmentPath` flag, but I couldn't debug the extension in intelliJ IDEA.

I'm wondering if there is a way to debug/run extensions with an IDE rather than vscode itself?

**Comment by roblourens** [comment]
You could probably get it to work with normal node debugging if you read our code to figure out how to get the debug pipe for the extension host, but that's not really a supported scenario that I'm going to try to troubleshoot.
