### ISSUE TITLE
Add an onEnterRule to SCSS language config for SassDoc documentation blocks to append `/// `

### ISSUE THREAD

**Issue by wkillerud** [microsoft/vscode#150598]
Issue Type: <b>Feature Request</b>

When I write documentation in JavaScript or TypeScript and hit Enter, VS Code appends ` * ` so I can keep writing documentation without dealing with comment syntax on the next line. I would love to have that opportunity when writing SassDoc as well.

I experimented with an updated `language-configuration.json` in an extension I maintain, which seems to do the trick. Would love to have this land upstream so I can avoid duplicating the whole language configuration for SCSS.

```jsonc
{
  "onEnterRules": [
    {
      // Continue with a docblock line when in that context
      "beforeText": "^[\\s]*///.*$",
      "action": {
        "indent": "none",
        "appendText": "/// "
      }
    }
  ]
}

```

Here's a screen recording demoing the difference in experience today.

https://user-images.githubusercontent.com/1223410/170819580-b71abf5a-0c77-4d4b-b138-c95d19736464.mp4

And here it is with the additional `onEnterRules`.

https://user-images.githubusercontent.com/1223410/170819903-5e98dce2-1b2e-4e28-a199-bc0c0b28e307.mp4

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

**Comment by rchiodo** [comment]
I'm not sure if this is working or not? Is it supposed to automatically add comments on hitting return?

I get this:
![scss](https://user-images.githubusercontent.com/19672699/171301857-178acf23-8400-4b5d-81b6-c98cf5bd79ab.gif)

**Comment by rchiodo** [comment]
Sorry my mistake. It's only doc comments that it does that. `///`
