### ISSUE TITLE
createStatusbarItem can not run "workbench.action.files.saveAll" command

### ISSUE THREAD

**Issue by AnWeber** [Microsoft/vscode#15059]
Command workbench.action.files.saveAll is not executed by statusbaritem. Issue is like #12214.

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

[saveall.zip](https://github.com/Microsoft/vscode/files/573780/saveall.zip)
1. Unzip extension saveAll
2. npm install
3. execute extension in VSCode
4. click on created StatusBarItem "Save All"

![image](https://cloud.githubusercontent.com/assets/13434739/20037274/e129f5a6-a41c-11e6-9dd7-5550f7a643c9.png)

Code needed to reproduce issue:
`
export function activate(context: vscode.ExtensionContext) {
    const statusBarItem = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left, 1);
    statusBarItem.command = 'workbench.action.files.saveAll';
    statusBarItem.text = 'Save All';
    statusBarItem.show();
    context.subscriptions.push(statusBarItem);
}
`

**Comment by bpasero** [comment]
@AnWeber the action will only work if you have dirty files. did you try that?

**Comment by AnWeber** [comment]
@bpasero ok thanks for your fast response. I didn't change any file. the message only appears with no dirty files. I will close the issue, but maybe someone can change the content of the message.
