### ISSUE TITLE
.jsbeautifyrc for default VSCode beautification

### ISSUE THREAD

**Issue by oshalygin** [Microsoft/vscode#15055]
- VSCode Version:
**1.7.1**
- OS Version:
10.12.1

Looking to get the base .jsbeautifyrc file for VSCode.  I promise I looked all over the web: stackoverflow, this repo, vscode docs, my girlfriend and I even asked my parents but they had no idea :)

Anyone have a copy of the base `.jsbeautifyrc` that VSCode uses under the hood?  I'd like to build on top of what comes out of the box, but it's hard when I cant quite figure out how the code formatting is going down. 

If anyone can point me to the source where thats happen that would be awesome too.  

I swear I'm not being lazy, I've looked through the repo and the only files that make any sense are these:

https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/format/common/formatActions.ts#L44-L70

**Comment by rebornix** [comment]
AFAIK, I don't know we have this `jsbeautifyrc`. Can you provide your extension list?

**Comment by oshalygin** [comment]
My extension list is a bit unrelated to the topic but here it is:
@rebornix 

- beautify
- Debugger for Chrome
- Document This
- EsLint
- GitLense
- Guides
- Material
- Material Icon Theme
- Material Neutral Theme
- Material-theme
- npm Intellisense
- One Dark Theme Improved
- One Monokai Theme
- Path Intellisense
- Project Manager
- Rainbow Brackets
- Simple icon theme
- Studio Icons
- Wallaby.js

**Comment by oshalygin** [comment]
Take a look at this from the jsBeautify docs
https://github.com/HookyQR/VSCodeBeautify

**VS Code uses js-beautify internally**, but it lacks the ability to modify the style you wish to use. This extension enables running js-beautify in VS Code, AND honouring any .jsbeautifyrc file in the open file's path tree to load your code styling. Run with F1 Beautify (to beautify a selection) or F1 Beautify file.

**Comment by aeschli** [comment]
We use https://github.com/beautify-web/js-beautify only for HTML. All HTML relevant options are available in the settings.
For JavaScript we use a formatter provided by TypeScript.
Format JavaScript embedded in HTML is not supported. Issue is #5076.
