### ISSUE TITLE
Test copy paste api proposal 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#150583]
Test for #30066 

- [x] Mac @lszomoru
- [x] Linux @karthiknadig
- [x] Windows @amunger

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150583%0A%0A&assignees=mjbvz)

---

## Summary

The new `documentPaste` api lets extensions hook into copy/paste. This can be used to modify the content being pasted or copy along other information (such as imports) that can then inserted on paste

The `prepareDocumentPaste` method is invoked on copy while `provideDocumentPasteEdits` is invoked on paste

## Testing
1. Enable this new behavior by setting `"editor.experimental.pasteActions.enabled": true`
1. In the extension samples, use the paste sample as your starting point: https://github.com/microsoft/vscode-extension-samples/tree/main/document-paste
2. This sample extension adds custom paste behavior in plaintext files

**Things to test:**

1. After enabling the setting, copy paste should still work normally in the rest of the editor
3. Confirm that `provideDocumentPasteEdits` and `prepareDocumentPaste` are invoke with the expected arguments
4. Confirm that data transfer set in `prepareDocumentPaste` can be accessed in `provideDocumentPasteEdits`
5. Confirm you can read a list of copied files  using the `text/uri-list` mime type (either copied in the VS Code explorer ~~or from the desktop~~)

**Known limitations**
- Data added in `prepareDocumentPaste` is currently only visible within the current VS Code window (it does not get shared across windows or into other apps)
- If there are multiple providers, we just invoke the first one. In the future we may instead show UI that lets user select which provider to use

**Comment by amunger** [comment]
@mjbvz - to clarify, in #4, I should be able to copy a set of files in Windows file explorer and then see that list of files with `const files = dataTransfer.get('text/uri-list');`? I was not able to do that (but it did work when copying files from vs code explorer)

Everything else works as expected.

**Comment by mjbvz** [comment]
@amunger Ah yes that currently doesn't work. You should see data transfers for the individual files, but not the uri-list. Will remove from test plan and revisit next iteration

**Comment by karthiknadig** [comment]
@mjbvz This is great!! Felt like allowing`TextEdit` to be retuned via `provideDocumentPasteEdits` can certainly help. See https://github.com/microsoft/vscode/issues/151047
