### ISSUE TITLE
xterm depends and work flow in yarn fails to compile, package.lock.json rules and yarn.lock regen

### ISSUE THREAD

**Issue by TomTravis** [microsoft/vscode#150689]
Does this issue occur when all extensions are disabled?: Yes/No yes

- VS Code Version: latest Github pull
- OS Version: linux bullseye not (Darwin)
- (wrk)coco@localhost:~$ npm -v
8.11.0
(wrk)coco@localhost:~$ yarn -v
1.22.18
(wrk)coco@localhost:~$ node -v
v16.15.0
(wrk)coco@localhost:~$ uname -a
Linux localhost 4.4.180-16566-g51163f4278d1 #1 SMP PREEMPT Tue Aug 27 17:13:36 PDT 2019 x86_64 GNU/Linux
(wrk)coco@localhost:~$ e -v
Checking for build-tools updates
Running "git pull --rebase --autostash" in /home/coco/.electron_build_tools
Applied autostash.
build-tools is up-to-date

Steps to Reproduce:

1. git clone vscode using build docs
2. yarn
![Screenshot at 2022-05-30 00-59-13](https://user-images.githubusercontent.com/46386261/170946349-efbd51b8-a146-4b67-aa87-ef6e2295f23a.png)

git log
(wrk)coco@localhost:~/vscode$ git add --all
(wrk)coco@localhost:~/vscode$ git commit --all -m up

> husky - npm run -s precommit
> husky - node v16.15.0
(wrk)coco@localhost:~$ npm run precommit
npm ERR! Missing script: "precommit"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coco/.npm/_logs/2022-05-30T08_42_34_449Z-debug-0.log
(wrk)coco@localhost:~$ npm run
(wrk)coco@localhost:~$ npm run precommit
npm ERR! Missing script: "precommit"
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coco/.npm/_logs/2022-05-30T08_43_20_514Z-debug-0.log

Reading git index versions...

Error: Cannot find module '@typescript-eslint/experimental-utils'
Require stack:
- /home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js
- /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/rules.js
- /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/linter.js
- /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/api.js
- /home/coco/vscode/node_modules/gulp-eslint/index.js
- /home/coco/vscode/build/hygiene.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js',
    '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/rules.js',
    '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/linter.js',
    '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/api.js',
    '/home/coco/vscode/node_modules/gulp-eslint/index.js',
    '/home/coco/vscode/build/hygiene.js'
  ]
}

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'
(wrk)coco@localhost:~/vscode$ git commit --all -m up --no-verify
[main 00243acaabe] up
 7 files changed, 76673 insertions(+), 15651 deletions(-)
 create mode 100644 .env
 rewrite .yarn/install-state.gz (80%)
 rename package-lock.json => package.lock.json (100%)
 rewrite yarn.txt (100%)
 create mode 100644 z/package.json.lock
 create mode 100644 z/yarn.lock
(wrk)coco@localhost:~/vscode$ git pull --all
Fetching origin
Already up to date.
(wrk)coco@localhost:~/vscode$

compile log
[yarn.txt](https://github.com/microsoft/vscode/files/8796704/yarn.txt)

**Comment by yume-chan** [comment]
Fixed the format

> - VS Code Version: latest Github pull
> - OS Version: linux bullseye not (Darwin)
> 
> ```
> (wrk)coco@localhost:~$ npm -v
> 8.11.0
> (wrk)coco@localhost:~$ yarn -v
> 1.22.18
> (wrk)coco@localhost:~$ node -v
> v16.15.0
> (wrk)coco@localhost:~$ uname -a
> Linux localhost 4.4.180-16566-g51163f4278d1 #1 SMP PREEMPT Tue Aug 27 17:13:36 PDT 2019 x86_64 GNU/Linux
> (wrk)coco@localhost:~$ e -v
> Checking for build-tools updates
> Running \"git pull --rebase --autostash\" in /home/coco/.electron_build_tools
> Applied autostash.
> build-tools is up-to-date
> ```
> 
> 
> Steps to Reproduce:
> 
> 1. git clone vscode using build docs
> 2. yarn
> ![Screenshot at 2022-05-30 00-59-13](https://user-images.githubusercontent.com/46386261/170946349-efbd51b8-a146-4b67-aa87-ef6e2295f23a.png)
> 
> git log
> 
> ```
> (wrk)coco@localhost:~/vscode$ git add --all
> (wrk)coco@localhost:~/vscode$ git commit --all -m up
> 
> > husky - npm run -s precommit
> > husky - node v16.15.0
> (wrk)coco@localhost:~$ npm run precommit
> npm ERR! Missing script: \"precommit\"
> npm ERR! 
> npm ERR! To see a list of scripts, run:
> npm ERR!   npm run
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/coco/.npm/_logs/2022-05-30T08_42_34_449Z-debug-0.log
> (wrk)coco@localhost:~$ npm run
> (wrk)coco@localhost:~$ npm run precommit
> npm ERR! Missing script: \"precommit\"
> npm ERR! 
> npm ERR! To see a list of scripts, run:
> npm ERR!   npm run
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/coco/.npm/_logs/2022-05-30T08_43_20_514Z-debug-0.log
> 
> 
> Reading git index versions...
> 
> Error: Cannot find module '@typescript-eslint/experimental-utils'
> Require stack:
> - /home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js
> - /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/rules.js
> - /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/linter.js
> - /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/api.js
> - /home/coco/vscode/node_modules/gulp-eslint/index.js
> - /home/coco/vscode/build/hygiene.js
>     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
>     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
>     at Module.require (node:internal/modules/cjs/loader:1005:19)
>     at require (node:internal/modules/cjs/helpers:102:18)
>     at Object.<anonymous> (/home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js:7:30)
>     at Module._compile (node:internal/modules/cjs/loader:1105:14)
>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
>     at Module.load (node:internal/modules/cjs/loader:981:32)
>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
>     at Module.require (node:internal/modules/cjs/loader:1005:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js',
>     '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/rules.js',
>     '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/linter.js',
>     '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/api.js',
>     '/home/coco/vscode/node_modules/gulp-eslint/index.js',
>     '/home/coco/vscode/build/hygiene.js'
>   ]
> }
> 
> > husky - pre-commit hook failed (add --no-verify to bypass)
> > husky - to debug, use 'npm run precommit'
> (wrk)coco@localhost:~/vscode$ git commit --all -m up --no-verify
> [main 00243acaabe] up
>  7 files changed, 76673 insertions(+), 15651 deletions(-)
>  create mode 100644 .env
>  rewrite .yarn/install-state.gz (80%)
>  rename package-lock.json => package.lock.json (100%)
>  rewrite yarn.txt (100%)
>  create mode 100644 z/package.json.lock
>  create mode 100644 z/yarn.lock
> (wrk)coco@localhost:~/vscode$ git pull --all
> Fetching origin
> Already up to date.
> (wrk)coco@localhost:~/vscode$
> ```
> 
> compile log
> [yarn.txt](https://github.com/microsoft/vscode/files/8796704/yarn.txt)

**Comment by yume-chan** [comment]
> node-pty@npm:0.11.0-beta11 couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-5ca64aba/build.log)
>
> code-oss-dev@workspace:. couldn't be built successfully (exit code 1, logs can be found here: /tmp/xfs-23eac36c/build.log)

What's in there?

**Comment by TomTravis** [comment]
yarn npm it not like me getting code and config/make make install 
see txt files
npm still wants xterm resolved. Resolved yarn has pages of reqs dependents.
git pull/push updated me local and remote for today

npm install https://www.npmjs.com/package/@typescript-eslint/experimental-utils
did not clear xterm Im missing .js files for eslint and a few others

this should be a simple install. The bin file for vscode resets my computer no method to debug

[yark_gen.txt](https://github.com/microsoft/vscode/files/8799675/yark_gen.txt)
[npm_update.txt](https://github.com/microsoft/vscode/files/8799677/npm_update.txt)
[req.txt](https://github.com/microsoft/vscode/files/8799679/req.txt)

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode/issues/150866#issuecomment-1142317904
