### ISSUE TITLE
Show "Surround with snippet" in quick fix menu

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150678]
I am not a big user of snippets, but I do really like them in the case where I want to surround some selected code with a snippet.

Could we not show an entry in the quick fix menu to surround the selection with a snippet?

<img width="833" alt="image" src="https://user-images.githubusercontent.com/900690/170927573-8e5577ee-2c4a-4496-9d1e-90f07c86c6c5.png">

**Comment by babakks** [comment]
@jrieken I'm taking this if it's okay.

**Comment by jrieken** [comment]
To verify

* make sure `editor.snippets.codeActions.enabled` is true
* open a TS file
* have a non empty selection
* trigger code actions (cmd+.) or wait for the light bulb
* make sure there is "surround with XYZ" actions
* select one which isn't the first
* trigger the same code action again
* make sure the surround actions are now sorted by recency
* disable the setting mention above
* make sure no surround-with actions are shown

**Comment by babakks** [comment]
@jrieken I tested this on the latest Insiders version. It seems working very well. Also tried using unlisted snippets, and they show up within the context menu the next time.

The only problem was that the `editor.snippets.codeActions.enabled` parameter was marked as unknown in the settings JSON and neither enabling nor disabling it had any effect on the feature (i.e., the feature is always enabled).

My setup was:

```
Version: 1.70.0-insider
Commit: 13ba7bb446a638d37ebccb1a7d74e31c32bb9790
Date: 2022-07-22T05:17:40.120Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.13.0-51-generic
```

**Comment by jrieken** [comment]
>  the editor.snippets.codeActions.enabled parameter was marked as unknown in the settings 

That change was only made today

**Comment by babakks** [comment]
@jrieken So it should work on the next Insiders build, right?

**Comment by babakks** [comment]
@jrieken One more thing, when I select any of the context menu "Surround With: X" items, except the first one, the next time they don't stand higher and keep their position. I tried to invoke them for several times, but they didn't move. Is this the desired behavior?
