### ISSUE TITLE
jsx function call should not trigger emmet

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#150671]
![image](https://user-images.githubusercontent.com/41773861/170913563-600f2569-33a2-49eb-846d-cc1386660f4f.png)

Versions:

```
MacOS: 12.4
VSCode: 1.68.0-insider
Typescript: 4.7.2
```

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/51537
