### ISSUE TITLE
Crash and need to reopen (lost some info) about every 3 days

### ISSUE THREAD

**Issue by yanghf71** [microsoft/vscode#150667]

**Comment by yanghf71** [comment]
Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by connor4312** [comment]
Please try collecting crash reports: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by deepak1556** [comment]
Closing as issue has been inactive.
