### ISSUE TITLE
How do I support new features added in Code 1.7 in my extension while still supporting users on Code 1.6?

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#15064]
- VSCode Version: 1.7
- OS Version: Windows 10

I can't find any good information on the relationship between the Code `engine` version in `package.json` and versions of other parts (like the `vscode` `devDependency`).

It seems that updating the `engine` number causes a new `vscode.d.ts` to be downloaded when I run `npm install`, however I believe that also sets the minimum required Code version to install the extension.

If that's correct, I'm not sure how I can get the latest `vscode.d.ts` so that I can (for example) add [`evaluateName`](https://github.com/Microsoft/vscode/issues/10210) support but still allow the extension to be installed by Code 1.6 users?

It's also not clear how the other versions relate - do I need to move the `vscode` `devDependency` version forwards whenever I update the `engine` version? If so, is there a table of the min versions that work together?

Apologies if this is covered somewhere - I can't find it. Maybe if it doesn't exist, it's worth a small page in the extension docs explaining the relationship between these versions and the process/implications of updating each one.

**Comment by joaomoreno** [comment]
Code will install the latest version of an extension which is compatible with the user's version of Code.

This means that if you publish a new version of your extension, specifying the vscode engine compatibility to be `^1.8.0`, this version won't get installed on users that are on a VSCode before `1.8.0`.

**Comment by DanTup** [comment]
@joaomoreno I understand that; though my question was about whether I can keep supporting old versions of Code while still taking advantage of new features for people using new versions?

Eg., if I wanted to do:

```ts
if (codeVersion >= 1.7)
  // set evaluateName
```

Currently to get `evaluateName` to "compile" I need the definition file for Code 1.7, but that also means not being able to install the extension in Code 1.6.

It might not be a big deal (people tend to update fairly quickly), but so far I've tried to avoid forcing a new version of Code where I can help it to ensure that even people that aren't updating Code quickly are still getting bugfixes.

**Comment by joaomoreno** [comment]
We currently do not support that.

Either you want to add features to your extension which benefit from new API, which old users can't use at all. Or you want to add features to your extension which benefit from current API, at which point you have to consider doing parallel versioning. (eg: releasing multiple versions at once).

Notice that ultimately, we want our users always on the latest version possible. If they refused to do so, it comes at the cost of not getting new features. You, as an extension developer, should do the same.

**Comment by DanTup** [comment]
> consider doing parallel versioning. (eg: releasing multiple versions at once)

Does the store keep all versions and serve up the correct ones if we did that? I figured it'd only "keep" the last one and if your Code was old, you'd get nothing?

> Notice that ultimately, we want our users always on the latest version possible
> 
> You, as an extension developer, should do the same

Yeah, I'd love to just keep updating; but I keep seeing Code 1.4 and 1.5 in my analytics. I don't know how many people aren't upgrading Code regularly (or what their reasons are) so I wanted to cover as many as possible.

Probably the reasons aren't well-founded, I should just add a note to the release notes/announcement that the Code version has been rolled and people need to be on latest.

**Comment by joaomoreno** [comment]
The Marketplace keeps all the versions you ever published and:

>Code will install the latest version of an extension which is compatible with the user's version of Code.

Sure, make sure people keep riding the latest, every bit helps. 👍
