### ISSUE TITLE
Error while fetching extension. XHR failed.(Code-OSS)

### ISSUE THREAD

**Issue by MalNEW** [microsoft/vscode#150629]
The extension could not be fetched, showing Error while fetching extension. XHR failed.

    VS Code Version: 1.67.2 Code-OSS (used Discover to install)
    OS Version: Arch Linux x86_64
    Kernel Version: 5.17.9-arch1-1 

Steps to Reproduce:

1.Freshly installed Code-OSS in Arch Linux x86_64 5.17.9-arch1-1 
2.Open the tool and go to extension tab. Search for an extension to install, and the error is seen.

Console Log:
  ERR RequestService#request (browser) - error https://open-vsx.org/vscode/gallery/extensionquery Error: XHR failed
    at XMLHttpRequest.S.onerror (workbench.desktop.main.js:83:27625)
workbench.desktop.main.js:83          POST https://open-vsx.org/vscode/gallery/extensionquery net::ERR_NETWORK_CHANGED
(anonymous) @ workbench.desktop.main.js:83
R @ workbench.desktop.main.js:83
request @ workbench.desktop.main.js:619
queryRawGalleryExtensions @ workbench.desktop.main.js:624
await in queryRawGalleryExtensions (async)
queryGalleryExtensions @ workbench.desktop.main.js:624
getExtensions @ workbench.desktop.main.js:624
checkForUpdates @ workbench.desktop.main.js:3162
await in checkForUpdates (async)
refresh @ workbench.desktop.main.js:3158
await in refresh (async)
run @ workbench.desktop.main.js:3162
run @ workbench.desktop.main.js:3167
handler @ workbench.desktop.main.js:687
invokeFunction @ workbench.desktop.main.js:591
_tryExecuteCommand @ workbench.desktop.main.js:1694
executeCommand @ workbench.desktop.main.js:1694
run @ workbench.desktop.main.js:687
runAction @ workbench.desktop.main.js:220
run @ workbench.desktop.main.js:220
onClick @ workbench.desktop.main.js:691
(anonymous) @ workbench.desktop.main.js:220
workbench.desktop.main.js:594   ERR RequestService#request (browser) - error https://open-vsx.org/vscode/gallery/extensionquery Error: XHR failed
    at XMLHttpRequest.S.onerror (workbench.desktop.main.js:83:27625)
workbench.desktop.main.js:594   ERR Error: XHR failed
    at XMLHttpRequest.S.onerror (workbench.desktop.main.js:83:27625)
workbench.desktop.main.js:83          POST https://open-vsx.org/vscode/gallery/extensionquery net::ERR_NETWORK_CHANGED
(anonymous) @ workbench.desktop.main.js:83
R @ workbench.desktop.main.js:83
request @ workbench.desktop.main.js:619
queryRawGalleryExtensions @ workbench.desktop.main.js:624
await in queryRawGalleryExtensions (async)
queryGalleryExtensions @ workbench.desktop.main.js:624
ae @ workbench.desktop.main.js:624
query @ workbench.desktop.main.js:624
queryGallery @ workbench.desktop.main.js:3162
await in queryGallery (async)
queryGallery @ workbench.desktop.main.js:3158
await in queryGallery (async)
query @ workbench.desktop.main.js:3158
(anonymous) @ workbench.desktop.main.js:3158
w @ workbench.desktop.main.js:71
show @ workbench.desktop.main.js:3158
(anonymous) @ workbench.desktop.main.js:3158
doSearch @ workbench.desktop.main.js:3158
refresh @ workbench.desktop.main.js:3158
await in refresh (async)
run @ workbench.desktop.main.js:3162
run @ workbench.desktop.main.js:3167
handler @ workbench.desktop.main.js:687
invokeFunction @ workbench.desktop.main.js:591
_tryExecuteCommand @ workbench.desktop.main.js:1694
executeCommand @ workbench.desktop.main.js:1694
run @ workbench.desktop.main.js:687
runAction @ workbench.desktop.main.js:220
run @ workbench.desktop.main.js:220
onClick @ workbench.desktop.main.js:691
(anonymous) @ workbench.desktop.main.js:220
workbench.desktop.main.js:594   ERR XHR failed: Error: XHR failed
    at XMLHttpRequest.S.onerror (vscode-file://vscode-app/usr/lib/code/out/vs/workbench/workbench.desktop.main.js:83:27625)

**Comment by gjsjohnmurray** [comment]
You have installed a build that has been modified to get extension from the [Open VSX Registry](https://open-vsx.org/) instead of from [Marketplace](https://marketplace.visualstudio.com/). Please consult the registry site for advice, or install a different build.

**Comment by MalNEW** [comment]
> You have installed a build that has been modified to get extension from the [Open VSX Registry](https://open-vsx.org/) instead of from [Marketplace](https://marketplace.visualstudio.com/). Please consult the registry site for advice, or install a different build.

I'm trying to install the vsix from[Open VSX Registry](https://open-vsx.org/),it's cannot be install

**Comment by sandy081** [comment]
VS Code does not support Open VSX Registry and also the code-oss version/package you installed. Please file issue against the owner distributing the package. 

Thanks
