### ISSUE TITLE
space after constructor name breaks syntax JS highlight 

### ISSUE THREAD

**Issue by hex13** [Microsoft/vscode#15061]
- VSCode Version: Version 1.7.1 (1.7.1)
- OS Version: OS X El Capitan 10.11.6 

Steps to Reproduce:
1. write somewhere in file:
```javascript
const a = new Promise(resolve => {
    const file = this.props.doc.file;
    resolve({
        abc: Math.random()
    });

    class Foo extends React.Component {
        render() {
        }
    }
    
});
```
syntax highlight below is correct for now:

![image](https://cloud.githubusercontent.com/assets/3883359/20038346/57f8a01e-a432-11e6-9343-9af1c9ce56b3.png)
2. Now add space between `Promise` and `(`
3. syntax highlight is now broken.

![image](https://cloud.githubusercontent.com/assets/3883359/20038336/2b894308-a432-11e6-83af-7c4bfbfc7f6c.png)

**Comment by waderyan** [comment]
Thanks for opening this. This is a grammar issue so moving to that repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#347
