### ISSUE TITLE
webview - webviews should be able to send and receive messages

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150682]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=172382&view=logs&j=306b2268-2a17-5e97-ab97-f41a26dc5206&t=f99521cb-b554-56f1-45de-e2bc176b0ad3&l=406

```
1 failing
  1) vscode API - webview
       webviews should be able to send and receive messages:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (D:\a\_work\1\s\extensions\vscode-api-tests\out\singlefolder-tests\webview.test.js)
      at listOnTimeout (node:internal/timers:557:17)

```

**Comment by bpasero** [comment]
Looks like previously reported in https://github.com/microsoft/vscode/issues/146272

**Comment by bpasero** [comment]
Failed again in https://dev.azure.com/monacotools/Monaco/_build/results?buildId=175392&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9fd0bccc-90ad-5118-165a-bb6fa0e94027&l=410. Pushing a change to disable.

**Comment by mjbvz** [comment]
Removed for now with #157155
