### ISSUE TITLE
Can't auto guess encoding sometimes

### ISSUE THREAD

**Issue by wang-xudong** [microsoft/vscode#150642]
Issue Type: <b>Bug</b>

When I open a file with gbk encoding, sometimes, vscode can't open it with right encoding , vscode open it with utf8. I have turn files.autoGuessEncoding to true

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 4900H with Radeon Graphics          (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.42GB (30.44GB free)|
|Process Argv|--crash-reporter-id 693247c6-0186-4b69-b849-55988de84769|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
python-image-preview|076|0.1.2
better-comments|aar|3.0.0
Bookmarks|ale|13.3.0
project-manager|ale|12.6.0
amd-aocc-extension-v|AMD|1.0.0
alignment|ann|0.3.0
beyond-debug|coo|0.9.6
Vsnips|cor|0.6.2
vscode-svgviewer|css|2.0.0
vscode-office|cwe|2.5.5
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.7
fortranbreaker|eki|0.0.4
vscode-statusbar-debugger|fab|2.1.0
vscode-solution-explorer|fer|0.4.5
code-runner|for|0.11.7
linter-gfortran|krv|3.0.2022042917
gc-excelviewer|Gra|4.2.54
fortran-ls|han|0.6.2
debug-visualizer|hed|2.3.1
vscode-drawio|hed|1.6.4
reg|ion|1.1.0
latex-workshop|Jam|8.26.0
plantuml|jeb|2.17.2
vscode-hacker-typer|jev|0.1.1
svg|joc|1.4.18
lsp-wl-client|lsp|0.1.9
autoconf|mae|0.1.0
vscode-language-pack-zh-hans|MS-|1.67.3
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.3
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.7
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cpptools|ms-|1.9.8
hexeditor|ms-|1.9.6
makefile-tools|ms-|0.5.0
powershell|ms-|2022.5.1
wordcount|ms-|0.1.0
vsliveshare|ms-|1.0.5597
vscode-python-typehint|njq|1.4.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.17.0
vscode-data-preview|Ran|2.3.0
r|REd|2.5.0
explorer-exclude-vscode-extension|Red|1.2.0
fortran-config-ini|she|0.0.2
vscode-autohotkey|sle|0.2.2
pip-manager|sli|1.1.1
code-eol|soh|0.3.3
remote-x11|spa|1.5.0
remote-x11-ssh|spa|1.5.0
vscode-counter|uct|3.0.4
codelf|unb|11.7.0
errorlens|use|3.5.1
vscode-ltex|val|13.1.0
vscodeintellicode|Vis|1.2.21
vscode-icons|vsc|11.12.0
wolfram|Wol|1.5.0
dictionary-completion|yzh|1.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding
