### ISSUE TITLE
Kotlin code block syntax highlighting in markdown preview is broken in some case.

### ISSUE THREAD

**Issue by kkangmj** [microsoft/vscode#150668]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Windows_NT x64 10.0.22000

<br>

Kotlin code block syntax highlighting in markdown preview is broken in below example. It seems index operator with class reference is not considered in highlighting. 

**[Code block in markdown file]**
<img width="494" alt="image" src="https://user-images.githubusercontent.com/52561963/170910035-7c73d9a5-ac73-4f43-8970-a16f4ff3f0b0.png">

**[Actual Preview]**
<img width="573" alt="image" src="https://user-images.githubusercontent.com/52561963/170910148-dafaa896-b93b-4ab6-b4cb-ca584640231b.png">

**[What I've expected]**
<img width="573" alt="170910148-dafaa896-b93b-4ab6-b4cb-ca584640231b (1)" src="https://user-images.githubusercontent.com/52561963/170910873-8edfb3f2-2e79-4469-9992-30fbee47f425.png">

Disabled all extensions in this case.

**Comment by mjbvz** [comment]
Please share that markdown as text too

**Comment by kkangmj** [comment]
```kotlin
val validators = mutableMapOf<KClass<*>, FieldValidator<*>>()
validators[String::class] = DefaultStringValidator
validators[Int::class] = DefaultIntValidator
```

This is the text of screenshot!

**Comment by mjbvz** [comment]
We use highlight.js in the preview. Please file this issue against them
