### ISSUE TITLE
Escape special characters like !,?,' ' in Terminal 

### ISSUE THREAD

**Issue by dominik0711** [Microsoft/vscode#15065]
- VSCode Version: Version 1.7.1 (1.7.1) 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
- OS Version: 10.12.1 (16B2555)

Steps to Reproduce:

1. Open Terminal in VSCode
2. Execute a gulp task with a **child_process.exec** command with a string like that:
`mkdir -p ../!deploy`
or
`mkdir -p ../\!deploy`

Neither of the two command/tasks above work as expected in the internal Terminal. In iTerm.app both examples are working as expected.

How do I have to escape special characters like **?**, **!** or **whitespace** in paths to be able to execute a gulp task with **child_process.exec**?

**Comment by Tyriar** [comment]
Could you go into a little more detail what are you expecting `mkdir -p ../!deploy` to do? And how it's related to gulp and node? Are you opening up node and running `require('cp').exec('mkdir -p ../!deploy');`?

Some screenshots would be useful to demonstrate the different between iTerm and the integrated terminal.

**Comment by dominik0711** [comment]
OK. On Mac special characters like ?,!,' ' has to be escaped by prefixing the character with '\'. This means. When I try to make a new directory one level above my current working directory and inside a folder with a special character like `!deploy/` I have to do the following: 

mkdir ../\!deploy/newFolder

Now when I try to execute the following task:

    import cp from 'child_process';

    export function dmg () {
      const cmdStr =
        `mkdir -p '../\!deploy/installer' && dmgbuild -s ../desktop/osx/install/test_installer.py "Install TestProject" '../\!deploy/installer/Test-1.0.0.dmg'`;
      return cp.exec(cmdStr, (error) => {
        if (error) {
          gutil.log(`exec error: ${error}`);
          return;
        }
      });
    }

I'll get the following error:

```
Error: exited with error code: 1
    at ChildProcess.onexit (/Users/TestUser/Projects/Test/build/node_modules/end-of-stream/index.js:39:23)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

It seems that escaping special characters is treated different/wrong in integrated-terminal then in iTerm etc.

**Comment by Tyriar** [comment]
In the default Mac terminal I tried `mkdir ../!deploy` and it tells me `-bash: !deploy: event not found`. Are you using `bash` inside the integrated terminal but not in iTerm?

Also remember you're wrapping your string inside a JavaScript string, ``mkdir -p '../\!deploy/installer'...` will get resolved to `mkdir -p '../!deploy/installer'...`.
