### ISSUE TITLE
Writing to `launch.json` via `WorkspaceConfiguration.update` doesn't format nicely

### ISSUE THREAD

**Issue by DanTup** [Microsoft/vscode#15062]
- VSCode Version: 1.7.1
- OS Version: Windows 10

I'm using `WorkspaceConfiguration.update` to try and update existing `launch.json` files due to a change in data passed to our debug adapter. Code looks like this (I don't know if there's a better way; although `update` supports dotted names, this is inside an array?):

```ts
function update_launch_json_change_sdk_to_settings() {
	// Read launch.json config.
	let launchFile = vs.workspace.getConfiguration("launch");

	let configs = launchFile.get<any[]>("configurations");
	if (!configs)
		return;

	let hasChanged = false;

	// Find Dart CLI items that might need upgrading.
	configs.filter(c => c.type == "dart-cli").map(d => {
		// Remove the old sdkPath.
		if (d.sdkPath) {
			console.log("Found old sdkPath, removing...");
			d.sdkPath = undefined;
			hasChanged = true;
		}

		// Add the new debugSettings.
		if (!d.debugSettings) {
			console.log("Didn't find debugSettings, adding...");
			d.debugSettings = "${command.debugSettings}";
			hasChanged = true;
		}
	});

	if (hasChanged)
		launchFile.update("configurations", configs);
}
```

When I look at the changes that were made, the formatting has been lost so it's not obvious what the change was. Since this change is somewhat destructive to the end user, it would be nice if the diff was clean and they could see exactly what was modified.

![Changes](https://cloud.githubusercontent.com/assets/1078012/20038440/d0ff7d90-a42b-11e6-8493-f8bc4de9548c.png)

Note: The original data was inserted from `initialConfigurations` in our `package.json`, we didn't manually format it.

**Comment by aeschli** [comment]
@bpasero @DanTup It's important to give the minimal change to the JSON edit rewriter. So for Dan, instead of replacing the full configuration object, make multiple changes on the particular property.
Otherwise @bpasero we should do a diff in our code to get smaller changes.
I see an bug in my code that cases the new object to be flattened, I'll fix that.

**Comment by DanTup** [comment]
@aeschli I'm not sure how to make a minimal change here - `update` accepts dotted names, but `configrations` is an array. Could you give an example of how I can modify a single value from the `dart-cli` launch configurations?

**Comment by bpasero** [comment]
@aeschli thanks for fixing. I often also notice some whitespace issues where the new key ends up in the beginning of the line and not indented to the previous values. Maybe it is also something to look into so that the contents of the file look "user edited" still.

**Comment by DanTup** [comment]
@aeschli 

> So for Dan, instead of replacing the full configuration object, make multiple changes on the particular property.

Could you give an example of how to do this? I only want to update `dart-cli` things inside the array but I'm not sure how to do this. The docs say dotted identifiers are supported, but I just tested using array indexes and it didn't work (it added a new item with the full string I provided as the name):

```ts
launchFile.update("configurations.0.debugSettings", "${command.debugSettings}");
launchFile.update("configurations[0].debugSettings", "${command.debugSettings}");
```

Resulted in:
```js
{
  // original stuff
  ,
  "configurations.0.debugSettings": "${command.debugSettings}"
  ,
  "configurations[0].debugSettings": "${command.debugSettings}"
}
```

If you're fixing this by doing a diff in Code then this might be irrelevant, though if there is an easy way for me to do it now (in 1.6) that would be better.

**Comment by aeschli** [comment]
I have to take back what I wrote. As this is an array its not possible. We would have to extend our API.

**Comment by DanTup** [comment]
Gotcha, thanks for confirming!

**Comment by eamodio** [comment]
I'm also using `WorkspaceConfiguration.update` in [Toggle Excluded Files](https://marketplace.visualstudio.com/items?itemName=eamodio.toggle-excluded-files) and am having the same issue. I am updating the `files.excludes` setting.

Before calling `update`:
```json
    "files.exclude": {
        "**/node_modules/": true,
        "**/jspm_packages/": true,
        "**/bin/": true,
        "**/obj/": true,
        "**/wwwroot/dist/": false
    },
```

After calling `update`:
```json
    "files.exclude": {"**/node_modules/":false,"**/jspm_packages/":false,"**/bin/":false,"**/obj/":false,"**/wwwroot/dist/":true},
```

It would be great if the setting was formatted before being replaced. That way there won't be contention between a user editing the file (and it being formatted) and the api.

**Comment by aeschli** [comment]
#13436 fixes the issue of the newly inserted code not being formatted.
