### ISSUE TITLE
The color of the keyword "#endif" is not as expected if you select Language as C

### ISSUE THREAD

**Issue by smcdef** [microsoft/vscode#150603]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2 (Universal)
- OS Version: macOS Monterey Version 12.4 (21F79)

Steps to Reproduce:

The colour of the keyword "#endif" is not as expected if you select Language as C.

```c
#ifdef CONFIG_CC_HAS_ASM_INLINE
#define asm_inline asm __inline
#else
#define asm_inline asm
#endif
```

<img width="378" alt="image" src="https://user-images.githubusercontent.com/26999519/170825579-d59e46df-b991-4072-98d1-1647b65ed0fe.png">

When you select the Language as C++, then the color is as expected.

<img width="417" alt="image" src="https://user-images.githubusercontent.com/26999519/170825927-5c939c12-4d9b-43da-9802-905c97fa75f0.png">

**Comment by alexr00** [comment]
I can repro. Moved to the upstream repo where we get the C syntax highlight grammar: https://github.com/jeff-hykin/better-cpp-syntax/issues/589.
