### ISSUE TITLE
Cannot open file path in warning with spaces in path

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#15063]
_From @tungvn on October 31, 2016 3:31_

OS: Window 10
VS Code: 1.6.1

When I click some warnings, vscode return an error "Unable to open 'common.php': File not found (e:\path\to\common\file\common.php)."

Like this
![error](https://cloud.githubusercontent.com/assets/7405101/19843454/2ae3d530-9f55-11e6-8ea1-7bef9ecf920a.JPG)

_Copied from original issue: felixfbecker/php-language-server#130_

**Comment by felixfbecker** [comment]
_From @tungvn on November 2, 2016 9:11_

Bug happens when path of file contains space, like `e:\Project\My Project\path\to\file` is converted to `e:\Project\My+Project\path\to\file`

**Comment by felixfbecker** [comment]
Seems like VS Code doesn't decode `+` to space.

**Comment by jrieken** [comment]
Yes, we don't support `application/x-www-form-urlencoded` and cannot because there is no second data field to hold the MIME type.

**Comment by felixfbecker** [comment]
@jrieken This is about the URI reported by an LS in a `textDocument/publishDiagnostics` request. If www-form-urlencoded Encoding is not supported for the URI, it would be nice if you could document somewhere what standard URIs need to follow, for example [RFC3986](http://www.faqs.org/rfcs/rfc3986)

**Comment by jrieken** [comment]
@dbaeumer fyi for the doc of the language server protocol - [uri](https://www.npmjs.com/package/vscode-uri) and/or [uri]( https://github.com/Microsoft/vscode/blob/joh/configInspect/src/vs/base/common/uri.ts#L40)

**Comment by dbaeumer** [comment]
Will add doc to the language server protocol.

**Comment by felixfbecker** [comment]
@jrieken Thanks, didn't know about that package. I only went by the language server protocol spec, which doesn't define this. Thanks @dbaeumer

**Comment by dbaeumer** [comment]
Documented in LSP: https://github.com/Microsoft/language-server-protocol/commit/05fc7559ad36ded597c4d471ab4c00404e136cb1
