### ISSUE TITLE
Test Run and Debug changes

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#150662]
Refs: #146338

- [x] macOS @sandy081
- [x] linux @dbaeumer
- [x] windows @luabud

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150662%0A%0A&assignees=roblourens)

---

This is about the behavior of the Run and Debug button in a workspace where

- There is no launch.json
- There is no open editor

When you click "Run and Debug", some debuggers will be put in a "Suggested" section at the top of the list. This includes debuggers from extensions that were already activated before the _first_ time Run and Debug was clicked, or that were used in this session. Debuggers might be activated by a workspaceContains clause or from having had a command run. Here are some ways to test it

- Use this build of the mock-debug extension which activates on having a `${workspaceFolder}/readme.md` file:
[mock-debug-0.50.0.zip](https://github.com/microsoft/vscode/files/8794894/mock-debug-0.50.0.zip)
- Install the dart/flutter extensions and open a flutter project - the dart debugger will activate with a workspaceContains
- Run the "Add Browser Breakpoint" command - this should activate the js-debug extension and now the chrome/edge/node debuggers should appear at the top of the list
- Remember, when testing with extension activation, this only applies to extensions that get activated before the first time you click Run and Debug
- Pick some debugger that starts running - the next time you click Run and Debug, it will also be in the Suggested list

**Comment by luabud** [comment]
It works as expected for Python 😊  but the experience can be improved on the Python extension side, so I opened https://github.com/microsoft/vscode-python/issues/19213.
