### ISSUE TITLE
search by regexp with lookbehind assertion returned error

### ISSUE THREAD

**Issue by sy19890515** [microsoft/vscode#150645]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:Version: 1.67.2 (system setup)
- OS Version:Windows_NT x64 10.0.19044

Steps to Reproduce:
(not sure if this will reproduce for all cases. but with the files im testing, I can reproduce it)
1. I have a bunch of subtitle files in one folder.
2. if I open this folder with vscode, and search this regexp:
`(?<=\\N.*)"`
I would get the error message: Regex parse error: lookbehind assertion is not fixed lenght.

I get what it means, it just asks me to rewrite the lookbehind assertion with fixed length. However, if I dont open the folder with vscode, instead, I open a new vscode window and open all those files from the folder in the new window, I can search the exact regexp with no problem.

![vscode error](https://user-images.githubusercontent.com/9069998/170872854-329d5abe-fe13-40b9-a41a-44f9691d9c11.png)
![not error](https://user-images.githubusercontent.com/9069998/170872857-39403b40-38fd-47a4-81d5-fdd14855864f.png)

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support

**Comment by sy19890515** [comment]
> See https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support

So basically if I opened the folder with vscode, it uses the Rust regex engine and it is designed to not allow me to search lookbehind assertion with un-fixed length. And if I open the files themselves with vscode, it uses JS regex engine which does allow me to search that?

**Comment by roblourens** [comment]
Yes, thanks for linking @gjsjohnmurray

**Comment by sy19890515** [comment]
> Yes, thanks for linking @gjsjohnmurray

May I ask why vscode uses different regexp engines regarding to different opening method? this seems inconsistent.
