### ISSUE TITLE
Extension explorer not going back to installed packages when removing filter.

### ISSUE THREAD

**Issue by byehack** [microsoft/vscode#150607]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.0 (user setup)
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:06:02.889Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. use a filter of extension explorer
2. double click on filter to remove it.

Expected return to installed packages but it goes to search packages.

https://user-images.githubusercontent.com/26390254/170830087-275b5cd6-6d6b-4920-8b57-bd2995d1dee4.mp4

**Comment by sandy081** [comment]
To verify:

- Open Extensions View
- Type `@builtin ` in the search input (make sure you have space at the end)
- Select `@builtin` term (do not select end space) and delete it
- Make sure Default (Installed Extensions) views are shown
