### ISSUE TITLE
Plugin feature request: new default setting value

### ISSUE THREAD

**Issue by rictic** [Microsoft/vscode#15066]
A plugin author may have knowledge about their users' development environments that could be productively expressed as new default values for some builtin vscode settings.

As one real world example, Polymer code makes use of a mix of CSS features which don't currently validate with the built in css language server. It would be useful if installing the polymer vscode plugin set the default value of `css.validate` to false, in a way that was still overridable by user or workspace settings.

**Comment by octref** [comment]
[`workspace.getConfiguration`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace) and [`WorkspaceConfiguration.update`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_a-nameworkspaceconfigurationaspan-classcodeitem-id800workspaceconfigurationspan).

Though I'd be very cautious about writing settings for user. I myself wouldn't want extensions to do that.

**Comment by rictic** [comment]
Agreed that updating a user's settings would be disruptive and probably not what someone wants.

The feature request here is to update the default value of the setting in a way that's overridable by user and workspace settings, which I think is less disruptive.

**Comment by octref** [comment]
Writing workspace setting is fine, global is not.
Users can override it by modifying `.vscode/settings.json` in workspace.

**Comment by jrieken** [comment]
Defaults are immutable (they are defined in code/schemas) but you can change *global* and *workpsace* configuration values using [this](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2721) API
