### ISSUE TITLE
C# Debugger not working - Breakpoints won't trigger 

### ISSUE THREAD

**Issue by AndrewKralovec** [Microsoft/vscode#15069]
- VSCode Version:
1.7 
- OS Version:

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Steps to Reproduce:
1. 
Attach the C# Mono debugger your project. 
2.
Write a simple C# script and attach a break point to it 
3. 
Run the debugger, you’ll notice the breakpoints wont trigger. 
![screenshot from 2016-11-06 12 10 56](https://cloud.githubusercontent.com/assets/6210337/20040310/654817d0-a41a-11e6-90f2-690d07276f85.png)
![screenshot from 2016-11-06 12 13 02](https://cloud.githubusercontent.com/assets/6210337/20040312/6cdeb80a-a41a-11e6-8d17-977360fb0c03.png)

**Comment by rebornix** [comment]
Please file issues to the C# extension project you are using as it sounds like its problem instead of Code per your description.
