### ISSUE TITLE
Provide workaround for the won't fix bug: code returns wrong file name after rename

### ISSUE THREAD

**Issue by matter-it-does** [microsoft/vscode#150698]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2

Steps to Reproduce:

Same as in https://github.com/microsoft/vscode/issues/123664

The issue was closed without fix since it'd cause slowness for other users.

Is there a workaround for those stuck with the bug ? Is there any cache to delete so that Code starts returning correct file name?

**Comment by matter-it-does** [comment]
Apparently closing all tabs and windows and restarting Code fixed it.

**Comment by alexr00** [comment]
@matter-it-does thank you for posting the workaround.
