### ISSUE TITLE
Incremental Replacement should not depend on focus. (No keybinding to replace current match.)

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#15068]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. In any file, highlight the text to find.
2. Trigger the `actions.find` command (`Ctrl+F`).
3. To replace the current match, move cursor focus to the "Replace" box of the Find+Replace dialog and press `ENTER`.

This is a problem because it is tedious to change focus (as compared to having a dedicated keybinding to replace the currently active target).

In the full Visual Studio this is done by hitting `Alt+R`, which works no matter where the focus is within the Find+Replace dialog.

**Comment by waynebloss** [comment]
See also: #9444

**Comment by waynebloss** [comment]
My workaround for this will be to:

1. Trigger `editor.action.startFindReplaceAction` instead of `actions.find`, so that focus is already on the "Replace" box of the Find+Replace dialog.
2. Use the dedicated (`F3`) binding for `editor.action.nextMatchFindAction` to find the next match.
3. Press `ENTER` whenever I want to replace a match, since focus has not changed while pressing `F3`.

**Comment by waynebloss** [comment]
Also semi-related issue: #15067

**Comment by sandy081** [comment]
@waynebloss Have you tried using the key binding <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>1</kbd> which will replace the current match when find widget is open.

**Comment by waynebloss** [comment]
@sandy081 That shortcut is not documented here - https://code.visualstudio.com/docs/customization/keybindings

Where else should I look for documentation on that?

**Comment by waynebloss** [comment]
OK, I guess I'll just forget about documentation and next time I'll look in the "Default Keyboard Shortcuts" file that is accessible from `File -> Preferences -> Keyboard Shortcuts`.

**Comment by sandy081** [comment]
@waynebloss Very good catch. Sorry for not having the document up to date. 

@gregvanl Don't we update all key bindings here https://code.visualstudio.com/docs/customization/keybindings or 
https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf
