### ISSUE TITLE
json string as launch argument broke in version 1.67.2

### ISSUE THREAD

**Issue by Willem-J-an** [microsoft/vscode#150774]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: Windows_NT x64 10.0.22000 (Debian Bullseye WSL2)

I think #149283 broke my workflow. I provide an escaped json string as arg to python application, but since version 1.67.2, the argument is split rather than maintained as json string.

Steps to Reproduce:

1.
```
# launch.json
{
            "name": "Python: launch",
            "type": "python",
            "request": "launch",
            "program": "./main.py",
            "cwd": "${workspaceFolder}/src",
            "args": [
                "{\"environment\":\"${input:environment}\",\"run_id\":\"${input:run_id}\",\"run_timestamp\":\"${input:run_timestamp}\"}"
            ],
            "console": "integratedTerminal"
        }
```
2. Rather than maintaining json string, the args are split
![image](https://user-images.githubusercontent.com/51120533/171121404-0a5d26fc-234f-4493-9bd5-20520a45e117.png)

**Comment by roblourens** [comment]
Sorry, I missed escaping `{}`

**Comment by rchiodo** [comment]
/verified
![image](https://user-images.githubusercontent.com/19672699/171727464-86500402-2632-4585-afff-b8fc3aa97f3c.png)
