### ISSUE TITLE
files.trimTrailingWhitespace should not trim indentation in snippets.

### ISSUE THREAD

**Issue by vilic** [Microsoft/vscode#15070]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Build 14959

Steps to Reproduce:

1. Configure `files.trimTrailingWhitespace` as `true`, and turn on auto save.
2. `setTimeout`, select `settimeout` snippet and enter.

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
