### ISSUE TITLE
Unicode box characters don't render correctly in terminal

### ISSUE THREAD

**Issue by willmcgugan** [microsoft/vscode#150777]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: Version: 1.67.2
- OS Version: macOS 12.4

My project uses unicode box characters to render scrollbars in the terminal. They don't render as expected in the vscode terminal. 

Here's the scrollbars in the VSCode terminal:

https://user-images.githubusercontent.com/554369/171123336-acb1dba0-417e-4c78-a5ef-2e6fd7b0a676.mov

Here's how the scrollbars look in iTerm on MacOS (and other terminal emulators):

https://user-images.githubusercontent.com/554369/171123621-0357eb73-c1d3-4033-9207-aaa620a91a54.mov

It looks as though these box characters render with the wrong color. The border around the window above is also rendered with the same box characters, and produces a darker color in VSCode. 

Steps to Reproduce:

I've isolated a string which demonstrates the issue (in Python)

```python
scrollbar = '\x1b[48;2;85;85;85m \x1b[0m\x1b[38;2;85;85;85;105m▋\x1b[0m\x1b[105m \x1b[0m\x1b[105m \x1b[0m\x1b[105m \x1b[0m\x1b[105m \x1b[0m\x1b[95;48;2;85;85;85m▋\x1b[0m\x1b[48;2;85;85;85m \x1b[0m\x1b[48;2;85;85;85m \x1b[0m\x1b[48;2;85;85;85m \x1b[0m\n'
print(scrollbar)
```

This produces the following in iTerm:

<img width="588" alt="Screenshot 2022-05-31 at 09 12 06" src="https://user-images.githubusercontent.com/554369/171125540-b682061d-3811-4564-a991-5b5fe377d4a3.png">

And in VSCode:

<img width="588" alt="Screenshot 2022-05-31 at 09 15 26" src="https://user-images.githubusercontent.com/554369/171126080-5fcfc964-76bf-47e1-b42e-3d72dc121ac8.png">

**Comment by yume-chan** [comment]
Another issue caused by `terminal.integrated.minimumContrastRatio`

1:

![image](https://user-images.githubusercontent.com/1330321/171136725-70422a20-37fb-4850-9a02-98333d788bc3.png)

4.5:

![image](https://user-images.githubusercontent.com/1330321/171136627-d5cd24b3-b0f3-439d-8cbc-cb6dd2920e96.png)

**Comment by Tyriar** [comment]
We should also exclude box drawing characters from the setting, anything decorative.

**Comment by Tyriar** [comment]
Upstream https://github.com/xtermjs/xterm.js/issues/3843

**Comment by aeschli** [comment]
After fix:
![image](https://user-images.githubusercontent.com/6461412/171856377-fde27e7e-95ad-4165-a903-6b0c83088355.png)
Marking as verified.

**Comment by willmcgugan** [comment]
You guys are awesome.
