### ISSUE TITLE
Command center: empty window only shows search icon

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150786]
Testing #150396

I am not sure if that is intentional, but in an empty window you only see the search icon:

![image](https://user-images.githubusercontent.com/900690/171131742-68211961-b81d-4600-94db-7ca89f5721ed.png)

**Comment by misolori** [comment]
At the minimum we should show a placeholder like "Search":

<img width="1024" alt="CleanShot 2022-05-31 at 12 51 37@2x" src="https://user-images.githubusercontent.com/35271042/171273229-6eaab7d9-509b-4ff5-9c4b-f78973bcbb96.png">
