### ISSUE TITLE
When are inclineCompletions shown?

### ISSUE THREAD

**Issue by DavidLangworthy** [microsoft/vscode#150734]
I see from the interface comments that inlineCompletions are requested whenever the users stops typing.  The question I have is how does the editor determine this?  Is there an existing setting that controls the quiescence period before the editor decides the user has stopped?  Is it possible to increase this or should I just wait in the handler?

@hediet

**Comment by DavidLangworthy** [comment]
Thank you.  Reading through your PR and #140557 there is a reference to some documentation of the delay service.  Could you share a pointer?

**Comment by DavidLangworthy** [comment]
I see from the code that the bounds are set to 50ms and 200ms.  How were these numbers chosen and what was the value before the adaptive debounce service was available?

**Comment by hediet** [comment]
Before it was always just 50ms

**Comment by DavidLangworthy** [comment]
I've opened an issue to tune these parameters with ExP #151447.  Please review.

**Comment by hediet** [comment]
Let's discuss this in #151447.
