### ISSUE TITLE
SnippetString.appendChoice() with placeholder=0 inserts snippet marked into the editor

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#150745]
The following code:

```ts
const a = new vs.SnippetString();
a.appendChoice(["test", "test2"], 0);
await editor.insertSnippet(a, new vs.Range(new vs.Position(0, 0), new vs.Position(0, 0)));
```

Inserts raw snippet markup into the document:

![Screenshot 2022-05-30 at 18 44 24](https://user-images.githubusercontent.com/1078012/171040274-775a4459-8bef-4b18-ae6d-9eb83a1f355f.png)

It's not very explicit in the docs/tooltips but I guess that the "final tabstop" does not support choices. If this is the case, it would be better if `appendChoice` throws if given an invalid value, or VS Code just does some default behaviour (like setting the tabstop, inserting the first choice, etc.) rather than inserting snippet markup into the document.

**Comment by babakks** [comment]
@jrieken I was working on this, but found a conflict with an old issue (#31599) in the tests ([snippetParser.test.ts#L644][test]):

```ts
test('Snippets: make parser ignore `${0|choice|}`, #31599', function () {
    assertTextAndMarker('${0|foo,bar|}', '${0|foo,bar|}', Text);
    assertTextAndMarker('${1|foo,bar|}', 'foo', Placeholder);
});
```

[test]: https://github.com/microsoft/vscode/blob/00574df08aac536a4262ce0ff975bd04a2768e80/src/vs/editor/contrib/snippet/test/browser/snippetParser.test.ts#L644

Anyway, I'll submit the PR to fix the current issue. Feel free to close it.

**Comment by jrieken** [comment]
Yeah, not supporting choice on the final tabstop is on purpose. Correctly me if I am wrong but I believe that's how it works in Textmate itself and we are using that as reference

**Comment by babakks** [comment]
@jrieken However, this was not much unfortunate. While checking the tests, I encountered a somehow paralyzed assertion that didn't surface until now. I'm now submitting a PR for them.

**Comment by jrieken** [comment]
closing because of https://github.com/microsoft/vscode/issues/150745#issuecomment-1156402023

**Comment by DanTup** [comment]
I understand why this might not be supported in snippet text (#31599) but I'm not sure I understand why `appendChoice` can't be made to `throw` in this case. If it's invalid to do this, it seems odd to silently do something strange rather than just throwing so it's clearer to the (extension) developer what they have done wrong?

**Comment by DanTup** [comment]
(and FWIW, you didn't actually close the issue if you intended to :-) )
