### ISSUE TITLE
Support piping text into the editor from the command line

### ISSUE THREAD

**Issue by natesilva** [Microsoft/vscode#15071]
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

With the `code` command installed in your PATH it should be possible to pipe text into the editor from the command line:

```
$ curl -L bing.com | code
```

In this example, I’d expect Code to open and show me the output of the `curl` command (which would be the HTML of the Bing home page).

This works with Sublime Text (`subl` command) and TextMate (`mate` command). It would be great if `code` did this too.

**Comment by viccie30** [comment]
👍

**Comment by melMass** [comment]
For now I use the following:

#### codepipe (file needs to be `chmod +x` and in your `$PATH`)
```bash
#!/bin/sh

#!/bin/sh

if [ ! -t 0 ]; then
    	#set -- "${@}" $(cat)
		out=$(cat)

else
	echo "no pipe detected"
	exit 0

fi
if [ -z "${1}" ]; then
	echo "no filename provided"
	exit 0
fi
if [ -f "${1}" ]; then
	echo "file exists."
	exit 0

fi

echo ${out} > "${1}"
code "${1}"

```

#### usage:
```bash
curl -L bing.com | codepipe bing.html
```

**Comment by natesilva** [comment]
Dupe of #6161 which was closed today. 🎉
