### ISSUE TITLE
Feature request for characters lower/upper.

### ISSUE THREAD

**Issue by rosrad** [Microsoft/vscode#15079]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

Feature request

the feature of upper or lower to the selected characters should be  very useful

**Comment by rebornix** [comment]
It's a good extension candidate. Feel free to contribute!

**Comment by bgse** [comment]
Looks like there already is an extension for this:

https://marketplace.visualstudio.com/items?itemName=florianloch.text-transform

**Comment by rebornix** [comment]
Yes, we are considering to have it builtin or make it a common package that different keymaps can leverage.

Stay tuned.

**Comment by ramya-rao-a** [comment]
There is another extension that does the same https://marketplace.visualstudio.com/items?itemName=wmaurer.change-case 

#3776 is tracking missing keyboard shortcuts for common commands which includes the upper/lower case scenario.

Closing this as there are 2 extensions and a tracking issue
