### ISSUE TITLE
WCO: background color updates at different pace from title bar background

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150780]
It looks like the background color of the title container updates different from the WCO:
![Recording 2022-05-31 at 10 24 36](https://user-images.githubusercontent.com/900690/171128031-fe7975a5-008e-4b16-b088-050f3a6e9f22.gif)

**Comment by sbatten** [comment]
I'm not sure there is really anything we can do here. We update with the same event but one happens in a separate process.

**Comment by bpasero** [comment]
Yeah understood, not a big deal I guess but wanted to file anyway...
