### ISSUE TITLE
Command center: impact on `window.title`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150789]
Testing #150396

I think we will soon turn command center on by default. What is the impact on `window.title` then? I see we are only showing the full title in the hover now, but I wonder if we need another setting (`window.compactTitle`?) so that users still can configure what we show in the command center?

![image](https://user-images.githubusercontent.com/900690/171133158-e0fd4b3e-452b-4ed4-aea6-7b387d983e42.png)

Or maybe we should find a way to show the `window.title` even in the command center with ellipsis if overflowing.

//cc @daviddossett @misolori

**Comment by BillDenton** [comment]
Enabling the command centre removes my custom window title, showing the full path of the currently focussed editor. I find this very useful especially when there are files with the same name but in different directories. Can't the command centre show the full custom window title (without having to hover over it)? Without this, I would permanently disable it.

**Comment by remote2** [comment]
Totally agree with @BillDenton

**Comment by jrieken** [comment]
We can say the default is different but a customisation is honoured

**Comment by jrieken** [comment]
To verify

* enable command center
* configure `window.title` and/or `window.titleSeparator`
* validate that any customization is picked up by the CC
* reset above settings
* validate that the CC uses a default

**Comment by bpasero** [comment]
Any reason we wouldn't also apply this with the default `window.title` setting? My worry is that when we eventually make command center on by default, the `window.title` setting would basically not work until you change it?

![image](https://user-images.githubusercontent.com/900690/192475644-fca2e31d-1728-4460-8f03-81669ee52704.png)

**Comment by jrieken** [comment]
> Any reason we wouldn't also apply this with the default window.title setting? 

The idea is that the CC shows an affordance to do something, like "Search vscode" - we replaced "search" with the icon which watered this down a bit. The worry is that the more title-stuff we put here the less likely it is that folks understand this as affordance
