### ISSUE TITLE
Performance drop on fullscreen with hardware acceleration enabled

### ISSUE THREAD

**Issue by eedahl** [Microsoft/vscode#15074]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:
Go fullscreen, as far as I can tell. Specs: gsync, 1070, 6700K.

When I go fullscreen, my framerate drops by a lot, to about 3-30 on the low side. This is fine when it's not drawing, but when I pick up my cursor to move, edit, etc., it's slow to kick into gear and feels laggy.

**Comment by bpasero** [comment]
Sounds a lot like: https://github.com/Microsoft/vscode/issues/5516

@eedahl does it change something if you run `code --disable-gpu`

**Comment by eedahl** [comment]
@bpasero That fixes it! :) What's up with that?

**Comment by bpasero** [comment]
@eedahl we have heard from problems before where disabling the native hardware acceleration in Chrome (using this command line flag) helps. That does not help us understand the underlying issue though...

**Comment by eedahl** [comment]
If it helps, Atom has this exact issue (except there I don't need fullscreen for it to happen), and atom --disable-gpu fixes it there as well.

**Comment by bpasero** [comment]
Sure, it is Electron related so it will happen in more and more apps :)

**Comment by eedahl** [comment]
Gotcha :)

**Comment by bpasero** [comment]
@eedahl we just updated Electron again, was wondering if that helps you: http://code.visualstudio.com/Download#insiders

**Comment by eedahl** [comment]
It looks fixed!

**Comment by bpasero** [comment]
That is pretty cool, thanks.

**Comment by eedahl** [comment]
Do you have any clue what the problem was?

**Comment by bpasero** [comment]
@eedahl no, but you might have some luck searching the chrome issues DB: https://bugs.chromium.org/p/chromium/issues/list
