### ISSUE TITLE
Linux: enable custom title by default

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150785]
I think now that the title bar becomes more powerful, including layout buttons and command center, we should enable custom title bar by default on Linux.

//cc @jrieken

**Comment by sbatten** [comment]
We did not get great feedback last time we did this. It would be nice if we had WCO on linux, but idk if that is reasonable to happen.

**Comment by bpasero** [comment]
@sbatten oh interesting, I somewhat had thought WCO was enabled on Linux, because when I zoom in, the title area enlarges, except for the buttons:

![image](https://user-images.githubusercontent.com/900690/171329684-17847a8f-238f-4d68-acc5-2c9af4707a28.png)

But now that I see how native buttons looks like, I see that these are just our custom buttons...

**Comment by sbatten** [comment]
yes , that's right, when I adopted the WCO, I refactored the custom controls to behave as close to the WCO as possible so they would be interchangeable until we ship fully on all platforms.

**Comment by sbatten** [comment]
closing for now as WCO is not yet available on Linux

**Comment by bpasero** [comment]
How is this related to WCO though? We still have a custom title implementation that works with our custom window controls, no?

**Comment by sbatten** [comment]
Without WCO, we will likely suffer the same negative feedback about our title bar on Linux. "too windows" "doesn't support window manager feature X"
