### ISSUE TITLE
Unable to find a .app or a .ipa to install

### ISSUE THREAD

**Issue by jlsuarezs** [Microsoft/vscode#15075]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra 10.12.1
- XCode: 8.1 (8B62)

Before install the last version of Xcode, its was working and I could debug my ionic 2/cordova app, but now I am alwasy getting this error:
[cordova-debug-adapter] Error: Unable to find a .app or a .ipa to install

Please, any help?
Thanks.

**Comment by johndpope** [comment]
you need to log ticket to cordova-debug-adapter plugin repo...
https://github.com/Microsoft/vscode-cordova

**Comment by jlsuarezs** [comment]
Ok, thanks.
