### ISSUE TITLE
Test task globs

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#150731]
Refs: https://github.com/microsoft/vscode/issues/88106

- [x] macOS @bpasero
- [x] linux @lramos15
- [x] windows @sbatten

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150731%0A%0A&assignees=alexr00)

---

You can now specify whether a task is the default task using file globs (which will match against the active file). Some examples:
```jsonc
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo txt",
            "type": "shell",
            "command": "echo TextFile",
            "group": {
                "kind": "build",
                "isDefault": "**.txt" // This is the glob
            }
        },
        {
            "label": "echo js",
            "type": "shell",
            "command": "echo JavascriptFile",
            "group": {
                "kind": "build",
                "isDefault": "**.js" // This is the glob
            },
        }
    ]
}
```

To test, open a workspace with several files in it and create a tasks.json file (can be created from the command Tasks: Configure Task) with some simple tasks that include a glob. From there, test out various file globs in the `isDefault` property of your tasks by running the "Run Build Task" command. Make sure that only the task you expect to run runs and that if there are multiple tasks that match you are always asked to confirm which one should be run.

**Comment by sbatten** [comment]
I spent quite a few minutes realizing that the `tasks.json` file does not match `**.json` blob pattern after being confused that it matched both **.json and **.txt
