### ISSUE TITLE
editor don't detect object and there methods (javascript)

### ISSUE THREAD

**Issue by dcz-switcher** [Microsoft/vscode#1507]
Hello,

I try to modified Material Theme and I can't set specific colors on objects and there attributs or methods
this is because there are not detected separately (see picture)

![vsc-editor](https://cloud.githubusercontent.com/assets/299807/11918092/26ad750a-a723-11e5-936a-957eb93ec0bc.png)

for exemple, I want to have something like that

window and setTimeout are in different colors and console and log too

![vsc-target](https://cloud.githubusercontent.com/assets/299807/11918096/71e22ff2-a723-11e5-979d-48259d8ad034.png)

**Comment by bpasero** [comment]
This seems TypeScript-TM specific.

**Comment by aeschli** [comment]
You have to file this as feature request against https://github.com/Microsoft/TypeScript-TmLanguage
