### ISSUE TITLE
Linux/Windows: title zooms in

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150783]
![image](https://user-images.githubusercontent.com/900690/171130843-07dae3e4-7f7c-4e32-acf8-2e970f1f225a.png)

With the new WCO this results in the WCO buttons to stay small. 

Somehow I had thought we disabled zooming in the title bar.

**Comment by sbatten** [comment]
we are being consistent here so there are not differences in behavior based on which controls we use. both controls will get updated to zoom in when that happens.
