### ISSUE TITLE
Enhancement - save anyway.

### ISSUE THREAD

**Issue by johndpope** [Microsoft/vscode#15076]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. work on file
2. silently delete file in background
3. save // this will throw an error message
4. Present Error alert [Save anyway? YES / NO?]

(you can try xcode to see similar behaviour)

**Comment by bpasero** [comment]
@johndpope I am not seeing an error message when trying to save a dirty file that meanwhile has been deleted from disk. Can you share screenshots?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
