### ISSUE TITLE
macOS: missing custom title bar when restoring multiple windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150790]
Steps to Reproduce:

1. configure in settings to restore fullscreen windows
2. open 2 windows fullscreen
3. quit
4. startup

=> only the one window goes into fullscreen, not the other (this is a electron limitation: https://github.com/microsoft/vscode/issues/148698). but the window that is not in fullscreen has misaligned control buttons:

![image](https://user-images.githubusercontent.com/900690/171133720-04681d8b-e367-4f3c-bcac-2fda6d7f3f69.png)

In fact the custom title bar seems to not be there.

**Comment by sbatten** [comment]
thanks for the repro, I've never seen this but I've seen it mentioned with no reliable repro.

**Comment by bpasero** [comment]
Yeah I think @jrieken was seeing this and reported it if I recall correctly.
