### ISSUE TITLE
launch.json args spiting on commas inside strings 

### ISSUE THREAD

**Issue by DanTaranis** [microsoft/vscode#150730]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.67.2
- OS Version: ubuntu2004/x86_64

Steps to Reproduce:

1. create a launch.json with "args":[
"--arg1=\"{'a':'a','b':'b'}\" "
]
2. run any python file with the above configuration. 
the command-line passed into the terminal is:
```
cd <cwd? ; /usr/bin/env /usr/bin/python3 /root/.vscode-server/extensions/ms-python.python-2022.6.2/pythonFiles/lib/python/debugpy/launcher 36981 -- some_python_file.py arg1=\"{\'a\':\'a\',\'b\':\'b\'}\" 
```
3. inside the python file 
```
import sys
print(sys.argv)
```
the print out will be :
```
["some_python_file.py", 'arg1="\'a\':\'a\'"', 'arg1="\'b\':\'b\'"']
```

if I replace 
```
\"{'a':'a','b':'b'}\" 
```
with 
```
\"{'a':'a'-'b':'b'}\" 
```
I get something a bit more expected:
```["some_python_file.py",'arg1="{\'a\':\'a\'-\'b\':\'b\'}"'```

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/150774
