### ISSUE TITLE
Node debugger does not stop at breakpoints in CoffeeScript source file of Meteor app

### ISSUE THREAD

**Issue by JacquesRobin** [microsoft/vscode#15078]
- VSCode Version: 1.7.1
- OS Version: Windows 7
- Meteor Version:  1.4.1.3

Steps to Reproduce:

I am trying to use sequentially the node debugger and the chrome debugger extension to debug a CoffeeScript leaderboard toy app using the dual, client and server sides, full-stack framework Meteor.
I put breakpoints in the server-side only code and in the client-side only code.

 I use the following VSCode Extensions:
- Meteor-Helper 0.1.1
- Debugger for Chrome 2.2.0

Since
1) Meteor is a dual side framework with
- client-side only code
- server-side only code
- isomorphic code running on both sides

and
2) According to Rob Lourens who is helping me with the chrome debugger extension issues, VSCode currently does **_not_** support **_launching simultaneously

_** both the server-side code built-in node debugger and the client-side code chrome debugger extension

I thus proceed as follow:
- I have an **Attach Server configuration in my launch.json file**
{
            "name": "Attach Server",
            "type": "node",
            "request": "attach",
            "port": 5858,
            "address": "localhost",
            "restart": false,
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/.meteor/local/build/programs/server/app/app.js"],
            "localRoot": "${workspaceRoot}",
            "remoteRoot": null
        },
- I have an **Attach Client configuration in my launch.json file**
{
            "name": "Attach Client",
            "type": "chrome",
            "request": "attach",
            "port": 9222,
            "address": "localhost",
            "sourceMaps": true,
            "outFiles": ["${workspaceRoot}/.meteor/local/build/programs/web.browser/app/app.js"],
            "diagnosticLogging": true,
            "webRoot": "${workspaceRoot}",
            "url": "http://localhost:3000/"
        }

I put breakpoints in the server-side only app startup function.

1. Using Meteor-Helper, I execute the meteor debug command

2. I  then attach the node debugger.
VSCode ignores the breakpoints and goes on to execute the entire app until the point when the app is waiting for a user action.

3. At that point the breakpoints have turned hollow and grey and a hovering message says:

> breakpoints ignored because generated code not found (soure map problem?)

4. The output window tells me that the app is running at: http://localhost:3000/

5. When I click on this url, VSCode opens the fs.js file (node file system) and stops before the return statement of the fs.statSync function defintion with the call stack saying "paused on exception and a blank page opens in my chrome browser saying "waiting for localhost"

![vscodenodedebuggernotstoppingatbreakpoints future js exception](https://cloud.githubusercontent.com/assets/8970048/20043529/262395aa-a48f-11e6-83bf-a20cddad83aa.jpeg)

6. Then when I click on the play icon of the node debugger, VSCode opens the future.js file, stopped at the  throw error line of the Future.prototype assignement statement and generating a Mongo Error connection time out

7. It is only when I pause the node debugger that the first page of my app finally appears in the browser
![vscodenodedebuggerissueafterpause](https://cloud.githubusercontent.com/assets/8970048/20043530/289a0a58-a48f-11e6-8dca-d0f37269b417.jpeg)

**The Meteor packages I used are:**
meteor-base@1.0.4             # Packages every Meteor app needs to have
mobile-experience@1.0.4       # Packages for a great mobile UX
mongo@1.1.12                   # The database Meteor supports right now
blaze-html-templates@1.0.4    # Compile .html files into Meteor Blaze views
reactive-var@1.0.10            # Reactive variable for tracker
jquery@1.11.9                  # Helpful client-side library
tracker@1.1.0                 # Meteor's client-side reactive programming library

standard-minifier-css@1.2.0   # CSS minifier run for production mode
standard-minifier-js@1.2.0    # JS minifier run for production mode
es5-shim@4.6.14                # ECMAScript 5 compatibility for older browsers.
ecmascript@0.5.8              # Enable ECMAScript2015+ syntax in app code
shell-server@0.2.1            # Server-side component of the `meteor shell` command

autopublish@1.0.7             # Publish all data to the clients (for prototyping)
insecure@1.0.7                # Allow all DB writes from clients (for prototyping)

coffeescript@1.11.1_1
mquandalle:jade@0.4.9
stylus@2.513.5

**The CoffeeScript source code is:**
(I chose Insert code, but it did not preserve the white spaces :( )
`class Player
  constructor: (@name, @score = Math.floor(Math.random() * 10)) ->

class Leaderboard extends Mongo.Collection
  insertNewPlayer: (playerName, score) ->
    player = new Player(playerName, score)
    @insert player

  insertPlayers: (nameList, scoreList) ->
    @insertNewPlayer(playerName) for playerName in nameList
    @insert(_id:player._id, score) for score in scoreList
    # self = @

  rank: =>
    [lead, followers...] = @find({}, {sort: {score: -1, name: 1}}).fetch()
    rank = 1
    @update {_id: lead._id}, {$set: {rank: rank}}
    previousScore = lead.score
    tiedCounter = 1
    for player in followers
      do (player) =>
        if player.score is previousScore
          tiedCounter = tiedCounter + 1
        else
          rank = rank + tiedCounter
          tiedCounter = 1
        @update _id: player._id, {$set: rank: rank}
        previousScore = player.score
    # self = @

aflLeaders = new Leaderboard("aflLeaders") unless aflLeaders?

if Meteor.isClient
  Template.leaderboard.helpers
    players: -> aflLeaders.find {}, {sort: {score: -1, name: 1}}

  Template.player.events
    'click tr>td>button': ->
      @score = @score + 1
      aflLeaders.update {_id: @_id}, @
      aflLeaders.rank()
      self = aflLeaders
     
if Meteor.isServer
  Meteor.startup ->
    if not (aflLeaders? and aflLeaders.findOne({})?)
      aflLeaders.insertPlayers([
        "Heath Shaw"
        "Alex Rance"
        "Easton Wood"
        "Shaun Burgoyne"
        "Jeremy McGovern"
        "Matthew Boyd"
        "Robbie Gray"
        "Josh P. Kennedy"
        "Patrick Dangerfield"
        "Callan Ward"
        "Max Gawn"
        "Rory Sloane"
        "Toby Greene"
        "Lance Franklin"
        "Cyril Rioli"
        "Eddie Betts"
        "Josh J. Kennedy"
        "Jack Gunston"
        "Josh Gibson"
        "Liam Picken"
        "Marcus Bontempelli"
        "Rory Lobb"
        ],
        []
      )
      aflLeaders.rank()
    self = aflLeaders`

**The jade template file I used is**:
` head
  title Leaderboard

body
  +leaderboard

template(name="leaderboard")
  tr
    th(colspan="4")
      h4 Leaderboard
  tr#sortButtonRaw
    th#sortButtonCell
      p rank
    th
      p player
    th
      p score
    th
  +each players
    +player

template(name="player")
  tr
    td
      p= rank
    td
      p= name
    td
      p= score
    td
      button vote` 

I don't know if this is:
- a node debugger bug, or
- a bug in the Attach Server configuration of my launch.json file.

But with the very limited documentation currently available concerning what attributes to use and with what values to obtain what debugging behavior in such file, I can't figure out how to set it up correctly for a Meteor app programmed in CoffeeScript with the many sources maps that the build process of such app generates.

Thanks in advance for helping out of this quicksand.

**Comment by weinand** [comment]
obsolete; won't fix
