### ISSUE TITLE
Test Extension Host as UtilityProcess

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#150753]
- [x] macOS @mjbvz
- [x] linux @lramos15
- [x] windows @sbatten

Complexity: 5

Authors: @alexdima, @deepak1556 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150753%0A%0A&assignees=alexdima,deepak1556)

---

* set the env variable `VSCODE_USE_UTILITY_PROCESS=1` and launch code insiders
* open any folder and open `Log (Main)` and **check** that the `UtilityProcess` is used:
  * `[main] [info] Creating new UtilityProcess to start extension host...`
* some areas to test:
  * activate a few popular extensions / check that they are running
  * extension host debugging: open a sample extension and debug it
  * open `Log (Extension Host)` and find the pid of the extension host. Kill it and check in the status bar / Developer Tools that it is restarted automatically
  * open `Log (Extension Host)` and find the pid of the extension host. Close the window and check that the extension host process has quit. 
  * quit vscode and check that it exits quickly (i.e. it doesn't take it 6s to exit. 6s is the timeout the main process installs to wait for all extension host processes to exit and waiting 6s most likely indicates that the extension host processes are not shutting down correctly).
  * try `F1` > `Developer: Show Running Extensions` > `Start Extension Host Profile` / `Start Debugging Extension Host` / `Save Extension Host Profile`

Known issues:
* the extension host process cannot be brought into debugging mode automatically, it requires a restart when using `F1` > `Developer: Show Running Extensions` > `Start Extension Host Profile` / `Start Debugging Extension Host`.

**Comment by lramos15** [comment]
Works great!

**Comment by mjbvz** [comment]
Looks good on MacOS. Also seeing the long close issue Ben reported: #150818
