### ISSUE TITLE
JavaScript syntax highlighting for new expressions w/ white spaces

### ISSUE THREAD

**Issue by danjoa** [Microsoft/vscode#15072]
- VSCode Version: 1.7
- OS Version: macOS Sierra

Steps to Reproduce:

var foo = new  Foo(whatever) → whatever is highlighted the standard way
var foo = new  Foo (whatever) → whatever is not highlighted (e.g. all teal in default light)

It's a minor thing but it'll be great if the white space before the opening parenthesis would be tolerated (some people format that way).

**Comment by hex13** [comment]
Duplicate, I've reported the same problem: #15061
