### ISSUE TITLE
Portuguese Translation

### ISSUE THREAD

**Issue by douglaseccker** [Microsoft/vscode#15077]
I wonder how I could help with the VS Code translation for Brazilian Portuguese?

**Comment by rebornix** [comment]
Assign to @joaomoreno first as he is our expert.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/4109

**Comment by SandHilt** [comment]
How we can help translations?

**Comment by dbaeumer** [comment]
Working on it... We will open up translations for contributions in the next months.

**Comment by dbaeumer** [comment]
This did happen. Translations are now available at Transifex.
