### ISSUE TITLE
Command center: back/forward should be conditionally enabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150782]
Testing #150396

The buttons for history navigation should probably leverage `canNavigateBack` and `canNavigateForward` context keys for proper enablement.

**PS:** this is probably more of a UX discussion to have, but I wonder if the go back / go forward buttons are too prominent now in the title bar. I see the case for quick open, but other buttons should maybe be configurable by the user or not be added by default. I believe we are close to then having a real toolbar with customizable entries in the title, which I think a lot of users ask for (https://github.com/microsoft/vscode/issues/41309).

**Comment by jrieken** [comment]
[this](https://github.com/microsoft/vscode/blob/23cbd089edff440353a29c6c373d368b84fa5ff5/src/vs/workbench/browser/parts/editor/editor.contribution.ts#L317) is where the menu is registered

**Comment by jrieken** [comment]
> Or are you suggesting to contribute the action to all menus from one place?

Yes, than the error won't be repeated all over again

**Comment by bpasero** [comment]
**Verification:**
The actions for go back / go forward properly indicate enablement in the main "Go" menu and in the command center. Going back is only enabled when another editor was opened and becomes disabled when navigated all the way to the beginning.
