### ISSUE TITLE
Search Feature Prematurely Changes Selection

### ISSUE THREAD

**Issue by ChaosOrdeal** [microsoft/vscode#150763]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

0.Use the settings Multiline or Never for "editor.find.autoFindInSelection"
1.Select an area of text in a single line
[so that the In Selection toggle will not already be on in the next step]
2.Ctl-H for Search/Replace
3.Type a character in the Search blank that exists multiple times in the selection
4.The Selection immediately changes to the first occurence of that character
and the results are "1 of 1" regardless of the number of occurences in the previous selection
5.Press "Replace All" and only the first occurrence (from my original selection when I pressed Ctl-H) is replaced

Workaround: Change "editor.find.autoFindInSelection" to "always" (which means that this "setting" only has one viable option)

**Comment by ChaosOrdeal** [comment]
I disabled ALL extensions -- no change, still an issue

**Comment by ChaosOrdeal** [comment]
Was just searching again, and perhaps this is a philosophical issue, but MANY actions in the search widget change the users' selection in unpredictable ways.  I really can't rely on the search/replace feature, which is making me consider uninstalling VSCode.  Personally, I would say:

**ANY changes to the user's selection (highlighted text) by the search widget is a [fairly serious] bug.**

**Comment by amunger** [comment]
covered in https://github.com/microsoft/vscode/issues/116827
