### ISSUE TITLE
Three way merge editor dependencies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150766]
@hediet I noticed a strange dependency to `vs/workbench/contrib/audioCues`, shouldn't that be a `base` thing to reuse and avoid tangles like that?

I also think we typically not call something `util.ts` to avoid a kitchen sink of sorts.

_Originally posted by @bpasero in https://github.com/microsoft/vscode/pull/150709#pullrequestreview-989346577_

**Comment by hediet** [comment]
The observables now live in common.
