### ISSUE TITLE
how can I change the cwd of notebook

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#150757]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.67.2 (system setup)
提交: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
日期: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621
Steps to Reproduce:

I'm using Jupyter notebook running python.
unlike python file, we can run py file with current workspacefolder as cwd, no matter where the py file is

but, when we use notebook to run python script, the cwd of py env is the folder of the ipynb file. if we move the ipynb file to another folder/subfolder, the cwd will change.

so how can we using notebook with python as runing python file.

we just want to storage my ipynb file everywhere in a single workspace and have only one top-cwd

**Comment by jackthepanisher** [comment]
Not really sure what you are trying to achieve (maybe an example would help) but you can also set the working directory for notebooks using the `jupyter.notebookFileRoot` configuration setting. So create a `.vscode` folder with a `settings.json` file containing the aforementioned setting to specifiy a fixed notebook working directory. If you open that folder with VS Code you can run any notebook with that fixed working directory independent of the notebook file location. Of course that setting can also be global but it would be better to provide that together with your actual workspace.

**Comment by heartacker** [comment]
@jackthepanisher thanks you 👍 
it works as expected
``` 
"jupyter.notebookFileRoot": "${workspaceFolder}"
```
