### ISSUE TITLE
auto detected target architecture

### ISSUE THREAD

**Issue by ioslh** [microsoft/vscode#150761]
Issue Type: <b>Bug</b>

I ran `gcc` in both vscode integrated terminal and a third party terminal(zsh) without extra options, but the target architecture are different.
Is that on purpose and is it configurable?

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|. --crash-reporter-id a6b41538-369d-4c8a-8a1a-88455504b107|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|2.7.0
cppincludeguard|aki|1.6.0
vscode-tailwindcss|bra|0.8.4
codestream|Cod|12.18.0
gitlens|eam|12.0.7
prettier-vscode|esb|9.5.0
codespaces|Git|1.8.1
copilot|Git|1.24.6022
go|gol|0.33.1
composer|ika|0.8.0
Kotlin|mat|1.7.1
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.9.8
vscode-commons|red|0.0.6
vscode-xml|red|0.20.0
volar|Vue|0.35.0
file-icons-mac|way|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by ioslh** [comment]
<img width="1507" alt="Screen Shot 2022-05-31 at 10 51 22" src="https://user-images.githubusercontent.com/3898898/171083613-5c3e97c7-80e1-45f6-bd1c-a3873607fc5f.png">

**Comment by deepak1556** [comment]
You are running intel version of VSCode via Rosetta, so the output is expected. Please use the universal version.
