### ISSUE TITLE
Test proxy kernel support

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#150738]
Refs: https://github.com/microsoft/vscode/issues/146942

- [x] anyOS @rchiodo 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23150738%0A%0A&assignees=rebornix)

---

We want to test the current proposal for proxy kernel support through menu contributions:

* Clone Repo https://github.com/rebornix/test-kernel-source
* Update Jupyter path in lauch file to ensure that we can test both the extension and Jupyter in Web https://github.com/rebornix/test-kernel-source/blob/main/.vscode/launch.json#L26 
* Launch a Jupyter server locally and update the token in https://github.com/rebornix/test-kernel-source/blob/main/src/extension.ts#L50
* Debug the extension through launch option `Run Extension (Web)`

Please test that you can pick the Connect To GitHub option from the kernel picker and run cells, or directly run cells and test if you can get auto kernel picking or kernel picker UI correctly.

**Comment by rchiodo** [comment]
@rebornix I'm having trouble getting the extension to load. I get this on debug launch:

![image](https://user-images.githubusercontent.com/19672699/171240581-3f9a1830-00aa-4bb1-baf2-57063e4fc80a.png)
