### ISSUE TITLE
VSCode select process hangs if "/bin/ps" doesn't exists

### ISSUE THREAD

**Issue by mikicho** [microsoft/vscode#150754]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. `sudo apt remove procps`
2. Run "Attach to Node process"

Expected:
Node processes will be shown and I could select one **OR** an appropriate error will appear.

Actual:
The search for processes never end and in the logs I see:
```
[2022-05-31 00:29:01.841] [renderer1] [error] spawn /bin/ps ENOENT: Error: spawn /bin/ps ENOENT
	at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
	at onErrorNT (node:internal/child_process:477:16)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|79.20GB (57.63GB free)|
|Process Argv|--file-uri vscode-remote://wsl%2Bdebian/home/michael/workspace.code-workspace --crash-reporter-id 9d1fd1f0-12df-4210-8d0c-1b2b936a3793|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|Memory (System)|62.18GB (57.54GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.66.3
vim|vsc|1.22.2
vscode-eslint|dba|2.2.2
gitlens|eam|12.0.7
code-spell-checker|str|2.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/pull/1291

**Comment by aeschli** [comment]
Verified that the process no longer hangs. The dialog message could be a bit more helpful, but this I'm not sure how often that case comes up.
![image](https://user-images.githubusercontent.com/6461412/176210358-2dd2d6ea-57d9-437b-87d7-72e3b7bac4dd.png)
