### ISSUE TITLE
ctrl+1 and ctrl+2 do not change focus.

### ISSUE THREAD

**Issue by eedahl** [Microsoft/vscode#15073]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:
On my computer they just don't work. Even with the following key config, ctrl+k j and ctrl+k l do what they're supposed to, but ctrl+1 and ctrl+2 do not.
[
{ "key": "ctrl+k ctrl+j",           "command": "workbench.action.moveActiveEditorGroupLeft" },
{ "key": "ctrl+k ctrl+l",          "command": "workbench.action.moveActiveEditorGroupRight" },
{ "key": "ctrl+1",     "command": "workbench.action.focusPreviousGroup" },
{ "key": "ctrl+2",      "command": "workbench.action.focusNextGroup" },
{ "key": "ctrl+k j",     "command": "workbench.action.focusPreviousGroup" },
{ "key": "ctrl+k l",      "command": "workbench.action.focusNextGroup" }
]

**Comment by bpasero** [comment]
@eedahl I cannot reproduce, can you maybe show screenshots or video how this behaves for you?

**Comment by eedahl** [comment]
I recorded with  Gyazo. As you can see, ctrl+k j and ctrl+k l changes the focus, while ctrl+1 and ctrl+2 do nothing. In fact it doesn't even record it on the lower status bar. It looks like the cursor is moving within a frame while i press them, but that seems to be an artifact of how I used Gyazo.
https://gyazo.com/7b21e1bfd9103529232b3616cf56c27c

**Comment by eedahl** [comment]
Note that I have this exact problem in Atom, except in Atom I don't have to full screen for it to happen. atom --disable-gpu did the exact same thing for Atom.

**Comment by bpasero** [comment]
@eedahl you seem to be switching between a readonly file on the left and an editable file to the right. It is expected that you do not see any feedback in the status bar for pressing `Ctrl+1`, you only see that when you press a chord (which is 2 keybindings like `Ctrl+k j`). 

Can you try this:
* open 2 editable files side by side
* put focus into the first file
* press Ctrl+2
* type something (do you see something typed in editor 2?)
* press Ctrl+1
* type something (do you see something typed in editor 1?)

**Comment by eedahl** [comment]
Ok, two editable files, I type something, switch, type something and switch.
https://gyazo.com/73eaa639c65155be653ee53c1e79f3ee

**Comment by bpasero** [comment]
@eedahl I am not convinced that the action is actually executed. instead of pressing ctrl+2 can you actually open the command palette (Ctrl+Shift+P) and pick "Focus Next Group"?

I suspect that another command is bound to Ctrl+2 and thus focus is never even triggered.

**Comment by eedahl** [comment]
Ctrl+Shift+P -> Focus Next Group works as expected.
https://gyazo.com/53b7a05298490862a702f034936cbaa2
As you can see, ctrl+1 is bound to exactly one thing in the default settings (that is, focusFirstEditorGroup, which is the one I'd like it to be but for which tells me to use focusPreviousGroup when I bind it to ctrl+k j. Ctrl+1 or ctrl+2 just do not trigger.)

**Comment by eedahl** [comment]
Incidentally, there are no other commands starting with ctrl+1 and ending with something else either.

**Comment by bpasero** [comment]
@eedahl is there something in the developer console when you press these keys? Help > Developer Tools > Console

**Comment by eedahl** [comment]
I cleared the console, went over to the editors and pressed the keys: no messages for either ctrl+1/2 or ctrl+k j/l.

**Comment by bpasero** [comment]
@eedahl can you bind another command to Ctrl+1 to see if it is the command behaving bad or the keybinding?

**Comment by eedahl** [comment]
I rebound ctrl+1 and ctrl+2 to copy and paste, respectively: they don't fire at all.

**Comment by bpasero** [comment]
@eedahl can you attach your keybindings.json file?

**Comment by eedahl** [comment]
It appears ctrl+1 through 3 do not work in either VSCode, Atom, Firefox or Slack, so it is not exclusive to VSCode.

keybindings.json:
// Place your key bindings in this file to overwrite the defaults
[
{ "key": "ctrl+k ctrl+j",           "command": "workbench.action.moveActiveEditorGroupLeft" },
{ "key": "ctrl+k ctrl+l",          "command": "workbench.action.moveActiveEditorGroupRight" },

{ "key": "ctrl+k j",     "command": "workbench.action.focusPreviousGroup" },
{ "key": "ctrl+k l",      "command": "workbench.action.focusNextGroup" },

//Useful default commands recorded here for quick recall.
{ "key": "ctrl+i",                "command": "expandLineSelection",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+u",                "command": "cursorUndo",
                                     "when": "editorTextFocus" },
//{ "key": "ctrl+1",     "command": "workbench.action.focusPreviousGroup" },
//{ "key": "ctrl+2",      "command": "workbench.action.focusNextGroup" },
{ "key": "ctrl+1",     "command": "editor.action.clipboardCopyAction",
                                     "when": "editorTextFocus" },
{ "key": "ctrl+2",     "command": "editor.action.clipboardPasteAction",
                                     "when": "editorTextFocus && !editorReadonly" }
]

**Comment by bpasero** [comment]
@eedahl thanks, it works for me on Windows and Mac, so I am out of ideas. 

@alexandrudima maybe this is a chance to let someone see your keybindings wiki? The issue is that the user assigned Ctrl+1 and Ctrl+2 to some commands but those are not being executed.

**Comment by alexandrudima** [comment]
@eedahl I've just written a wiki that explains in detail how keybindings are handled in VS Code -- https://github.com/Microsoft/vscode/wiki/Troubleshooting-Keybindings

May I ask you to give it a quick read such that we end up talking about the same things.

### 1. What's your keyboard layout?

### 2. Do we receive the key combination or is there some other software "stealing" it?

Use the define keybinding widget. What does it show when you press `ctrl+1`  ?

### 3. Is this an issue on your machine?

Open https://www.w3.org/2002/09/tests/keys.html in IE and press `ctrl+1`. Does IE get that keybinding? What is the output (screenshot)?

### 4. Is this a general Chrome issue?

If IE gets the keybinding, then try Chrome at https://www.w3.org/2002/09/tests/keys.html . What is the output (screenshot)? If Chrome does not get the keybinding, then this is a Chromium issue.

### 5. Have you used successfully this key combination in other software on your machine?

**Comment by eedahl** [comment]
1. I use a Norwegian keyboard layout.
https://gyazo.com/0393d86ad6f5c0392d8c08ed83f946f3

2. It shows ctrl+unknown. It could be snagged by something.

3., 4. You can see here that it only registers keyup events for ctrl+1 and ctrl+2.
https://gyazo.com/9478b713b362bcea823747fb6cd182de
It VSCode, Atom, Firefox, Slack and apparently Windows Explorer 11, so seems system wide.

5. Until recently, but not anymore. I can't pin down exactly when it happened.

**Comment by alexandrudima** [comment]
@eedahl Thank you!

Now we know it is not a vscode issue. 

I'm sorry I don't really know how you would find out what other software is "stealing" these keybindings, usually such software decides to pop up when invoked.

I suggest to close for now this issue on our side, since this is outside of our control.

**Comment by eedahl** [comment]
Okay, thanks for your help guys!

**Comment by eedahl** [comment]
@alexandrudima @bpasero In case anyone else reports this issue, it seems it was caused by Slack at Windows startup!
