### ISSUE TITLE
Merge editor: "Switch to 2 by 1 view"

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150812]
Testing #150389

Noticed that the hover does not change for both actions:

![Recording 2022-05-31 at 12 30 23](https://user-images.githubusercontent.com/900690/171153810-2a2c0f5d-50be-427d-bad7-d10ed94286eb.gif)

I also wonder about the name of the hover, maybe we align it with our editor layout names?

![image](https://user-images.githubusercontent.com/900690/171153869-7ea32002-7680-44d4-a63f-7f2ab36bb0dd.png)

**Comment by daviddossett** [comment]
Here's what I originally had:

<img width="486" alt="CleanShot 2022-06-02 at 08 51 35@2x" src="https://user-images.githubusercontent.com/25163139/171670888-b234da4e-61df-4a76-97bf-f277b484a8e6.png">

@jrieken @hediet are we omitting the stacked horizontal layout for now? If that's the case, I like the idea of having this layout icon as a toggle w/ an updating icon. I think we will need a new one for the mixed 2+1 layout. I'll create an issue over in the codicons repo.

**Comment by jrieken** [comment]
> @jrieken @hediet are we omitting the stacked horizontal layout for now? If that's the case, I like the idea of having this layout icon as a toggle w/ an updating icon.

Yeah, it looks like stacked horizontal layout isn't popular and something we shouldn't start with
