### ISSUE TITLE
Merge editor: minimal editor size?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150811]
Testing #150389

Currently it seems that the editors within have no minimal size as they do in the editor grid:

![Recording 2022-05-31 at 12 27 23](https://user-images.githubusercontent.com/900690/171153294-6ef1929f-27e5-459a-8d96-955602e7dc1f.gif)

**Comment by jrieken** [comment]
@bpasero What is the min-size for workbench editors?

**Comment by bpasero** [comment]
@jrieken here you go:

https://github.com/microsoft/vscode/blob/8d61a33e38e4f5da5b7b511471dd353ebd9b3d46/src/vs/workbench/browser/parts/editor/editor.ts#L23

This is for a single editor, and for diff editor we use twice that size:

https://github.com/microsoft/vscode/blob/cfaa9caf89b4854a126bab7f9c6ccaef57964907/src/vs/workbench/browser/parts/editor/sideBySideEditor.ts#L86-L89

**Comment by jrieken** [comment]
Thanks
