### ISSUE TITLE
undefined is not a JavaScript/TypeScript keyword

### ISSUE THREAD

**Issue by infinnie** [Microsoft/vscode#15083]
- VSCode Version: 1.7.1
- OS Version:

Steps to Reproduce:

1. Type `undefined` in a JavaScript/TypeScript file.
2. It would be highlighted as a keyword instead of a variable.

However as is specified, `undefined` is a global constant instead of a keyword.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#345
