### ISSUE TITLE
Failed to execute git - I don't use git!

### ISSUE THREAD

**Issue by jaminroe** [Microsoft/vscode#1508]
Why does my Visual Studio Code keep popping up this message?
<img width="181" alt="image" src="https://cloud.githubusercontent.com/assets/1559447/11918376/852a9170-a6fc-11e5-87cf-e7a8992da381.png">

I don't even use Git, and it started happening. Is it because I opened the Git panel?

Restarting does nothing, changing the settings/config doesn't help either. Super annoying and frustrated, please help. Thanks!

**Comment by Foysal94** [comment]
Really wish this is fixed ASAP. Its not breaking but it is incredibly annoying to work with. The error message blocks the top and the name of files and just a headache to view

**Comment by jaminroe** [comment]
@foysal94 I know right! They're working on it though based on the status changes

**Comment by joaomoreno** [comment]
Just to confirm: this **only** appears if you open the git panel, correct?

Do you have git installed? If so, which version? Which OS are you on?

What do you see once you open the **Git Output**?

![image](https://cloud.githubusercontent.com/assets/22350/12089266/59983826-b2e3-11e5-9461-a80f961b0135.png)

**Comment by jaminroe** [comment]
I do not have Git installed. I clicked the Git panel once, and it wouldn't go away even after a restart of Code. I haven't had it come up anymore, maybe because I installed an update since then?

**Comment by joaomoreno** [comment]
Can you open the git panel and show me what you see in there?

**Comment by joaomoreno** [comment]
Also, please let me know which OS you are on.

**Comment by jaminroe** [comment]
Don't see anything in Git panel. I'm on Mac 10.11.

**Comment by jaminroe** [comment]
Here's the screenshot. Looks like after the update, my Git config settings are finally being respected :tongue: 

![screen shot 2016-01-06 at 11 22 49 am](https://cloud.githubusercontent.com/assets/1559447/12147614/d46feaf0-b467-11e5-80eb-3c2ee005d189.png)

**Comment by joaomoreno** [comment]
What do you mean? You just got the update now?

**Comment by jaminroe** [comment]
No, sorry. I mean the last update, when ever that was. Earlier last month maybe? Or maybe even the one before that. Either way, it happened sometime during the last two updates.

**Comment by joaomoreno** [comment]
Can you remove the setting that disables git, make the error appear and show me what you see in the **Git Output**?

**Comment by jaminroe** [comment]
Doesn't stop showing this, including loading animation on left
![screen shot 2016-01-06 at 11 37 11 am](https://cloud.githubusercontent.com/assets/1559447/12148014/0e10e780-b46a-11e5-9cf8-4e8fd3fc5084.png)

**Comment by joaomoreno** [comment]
Please show me [what you see in the Git Output](https://github.com/Microsoft/vscode/issues/1508#issuecomment-168659280).

**Comment by jaminroe** [comment]
Sorry... bad multi-tasking today. It's blank:
![screen shot 2016-01-06 at 3 19 44 pm](https://cloud.githubusercontent.com/assets/1559447/12153649/f5856348-b488-11e5-8a7f-4bc84b433cd7.png)

**Comment by joaomoreno** [comment]
Interesting. Since you seem to be on a Mac, try opening Terminal and type `git` and `git --version`. Let me know what that yields.

**Comment by jaminroe** [comment]
I get:

`crun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun` Like I said, I don't have git installed :stuck_out_tongue_winking_eye:

**Comment by joaomoreno** [comment]
Ok, now we're getting somewhere. What do you get when you run `which git`?

You don't have `git` installed, but you do have `git` in your path somewhere, it is just broken. Pushing a fix.

**Comment by jaminroe** [comment]
I do? I haven't really used git before, so I wouldn't know 😄 I use SourceTree for my version control stuff.

**Comment by wisonye** [comment]
@jaminroe I have the same issue with you, but I solved it, I have git installed, but when you type "git --version" in the terminal, it will prompt this:

```javascript
Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.
```

And then you need to use "sudo git --version", the purpose it that show the license and you need to pull down( press space/enter ) to the end and type "agree" to end this:

```javascript
By typing 'agree' you are agreeing to the terms of the software license agreements. Type 'print' to print them or anything else to cancel, [agree, print, cancel] agree  

You can view the license agreements in Xcode's About Box, or at /Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf
```

After that, reopen visual studio code, your git and works fine( even you don't use it, it won't report error ) :)

I know more problems on MacOSX version for the "code", but ...I also keep using it right now, at least it's not bad, just sometimes the "intellisense not working"( not working perfect like their video show us, I have not idea on this, hope them can fix this ), and make a try on MacOSX, from open a Empty folder to setup Node.js/Nativescript project( add the tsconfig.js etc, ), otherwise "intellisense not working" IS VERY VERY VERY VERY SAD for Mac User ....:(

**Comment by jaminroe** [comment]
Ah! I don't have Xcode installed actually! I was going to install it today actually so I can use FileMerge. I'll follow up again once I do. 

---Sent from Boxer | http://getboxer.com

On January 11, 2016 at 12:35:09 AM EST, WisonYe <notifications@github.com> wrote:@jaminroe I have the same issue with you, but I solved it, I have git installed, but when you type "git --version" in the terminal, it will prompt this:  Agreeing to the Xcode/iOS license requires admin privileges, please re-run as root via sudo.   And then you need to use "sudo git --version", the purpose it that show the license and you need to pull down( press space/enter ) to the end and type "agree" to end this:  By typing 'agree' you are agreeing to the terms of the software license agreements. Type 'print' to print them or anything else to cancel, [agree, print, cancel] agree You can view the license agreements in Xcode's About Box, or at /Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf   After that, reopen visual studio code, your git and works fine( even you don't use it, it won't report error ) :)  I know more problems on MacOSX version for the "code", but ...I also keep using it right now, at least it's not bad, just sometimes the "intellisense not working"( not working perfect like their video show us, I have not idea on this, hope them can fix this ), and make a try on MacOSX, from open a Empty folder to setup Node.js/Nativescript project( add the tsconfig.js etc, ), otherwise "intellisense not working" IS VERY VERY VERY VERY SAD for Mac User ....:(  —Reply to this email directly or view it on GitHub.

**Comment by arnarp** [comment]
I got the same error message. I'm running 0.10.9 on Mac Yosemite. When I ran git in terminal I got prompted to re-run as sudo and accept Xcode licence. I did and the error messages stopped. Earlier today I noticed that my Xcode was updated.

**Comment by proweb** [comment]
got same error on Xubuntu 16.04  - Git installed in `/usr/bin/git` but VScode don't see it
How to solve it?

**Comment by linanwx** [comment]
I am using deepin and get same problem. Git is OK. Maybe using a chinese or another non-englist language system setting cause this problem.
