### ISSUE TITLE
bash debug trap doesn't work with shell integration for multi-word functions

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#150877]
1. add `trap "echo Hello" debug` to your `.bash_profile` with shell integration disabled -> `Hello` is echoed
2. enable shell integration and create a bash terminal
3. 🐛  `Hello` is not echoed

**Comment by meganrogge** [comment]
this is because `cut' ' -f3`  uses ' ' as the delimiter and -f3 gives only the 3rd field that results from that
![Screen Shot 2022-05-25 at 9 21 39 PM](https://user-images.githubusercontent.com/29464607/171225169-d3487e63-c6dc-4a88-af95-1d00f2182c01.png)

**Comment by Tyriar** [comment]
@meganrogge I'm not sure this case is particularly important since traps are typically always set to functions?

**Comment by meganrogge** [comment]
I don't think we should hope that is the case. They can be strings that are quite complicated

![Screen Shot 2022-05-31 at 9 51 22 AM](https://user-images.githubusercontent.com/29464607/171230018-3257ae98-9fce-4917-9f91-0f807380dbf9.png)

**Comment by meganrogge** [comment]
Spent several hours trying to get this to work to no avail.

**Comment by meganrogge** [comment]
this still doesn't work
