### ISSUE TITLE
Consider using color to show the user if she has reacted on a merge conflict

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150864]
Testing #150389

Similar like VS consider using colour to show a user if she has reacted on a merge conflict.

Also once Accept Merge button is clicked, if there are conflicts which have not been reacted on we should show a modal dialog "Are you sure... There are still N conflicts"

**Comment by hediet** [comment]
Implemented.

**Comment by isidorn** [comment]
Yeeey 👏 
Adding verification-needed so I try this out.
