### ISSUE TITLE
High CPU in shared process

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#150893]
I have seen this a few times, shared process CPU around 60% while nothing is going on

profile shows the worker is doing a lot of work but no stack
<img width="293" alt="image" src="https://user-images.githubusercontent.com/323878/171259775-f7265fc3-dd40-439e-8a88-dfecaf10f9c9.png">
[Profile-20220531T113345.json.zip](https://github.com/microsoft/vscode/files/8808186/Profile-20220531T113345.json.zip)
I'm not sure what all the shared process does right now, but maybe this is related to the fact that I have a lot of extensions installed?

I closed all vscode windows, and the issue persisted. I restarted vscode and it went away.

**Comment by bpasero** [comment]
Opening the attached profile unfortunately does not reveal much:

![image](https://user-images.githubusercontent.com/900690/171344022-416b51a4-f6b4-4f53-996e-e17287df3370.png)

Are you sure it was the shared process and not a process that is a child such as terminal or file watcher?

![image](https://user-images.githubusercontent.com/900690/171344098-c59e58bd-9e5a-4c0c-8d45-3294abe9d13d.png)

@sandy081 also assigning you because https://github.com/microsoft/vscode/issues/149980#issuecomment-1137701123 indicates it was related to settings sync extension

**Comment by bpasero** [comment]
Right, the file watcher is actually spawned as a worker but only within a process for file watching, so if CPU is high in the shared process but not file watcher, it would not be the file watcher. 

Would be interesting if you can check if the watcher process is spinning high CPU.

**Comment by roblourens** [comment]
I know that the process using 60% of cpu was the one that says `--vscode-window-kind=shared-process`, if that's what you're asking

**Comment by bpasero** [comment]
Yeah thanks, that means it is neither the file watcher nor the terminal for example.

But without any kind of trace or steps how to reproduce, I see no way how to continue.

**Comment by roblourens** [comment]
fwiw, this was happening again. Macbook fan working hard, the shared process using 60% cpu, profile shows the same pattern in the shared process workerMain.js. I disabled settings sync and nothing changed. But no steps or any other details.

**Comment by roblourens** [comment]
This keeps happening. Anything I can do to help debug?

**Comment by roblourens** [comment]
This is happening more and more often. This morning I restarted vscode 3 times in a row trying to make it stop. On the 4th try it went away

<img width="796" alt="image" src="https://user-images.githubusercontent.com/323878/188707934-d68d9e84-03b7-4093-9971-139cba40ef31.png">

**Comment by bpasero** [comment]
@roblourens when this happens just open shared process window and run a devtools perf trace?

**Comment by bpasero** [comment]
@deepak1556 with your knowledge around performance tooling, what would you recommend to use on macOS when devtools profiling does not reveal anything?

**Comment by Tyriar** [comment]
Another report: https://github.com/microsoft/vscode/issues/161265

**Comment by deepak1556** [comment]
Sorry for the delayed response, @roblourens @ctsstc can you follow the steps below to get more detailed profile.

* Launch vscode from the terminal with the following flags `--trace --trace-category-filter="devtools.timeline,v8,v8.execute,disabled-by-default-devtools.timeline,disabled-by-default-devtools.timeline.frame,disabled-by-default-devtools.timeline.stack.disabled-by-default-v8.cpu_profiler,disabled-by-default-v8.stack_trace,blink.user_timing,browser,content,renderer,electron,ipc,mojom"`
* Use the editor as you would normally and try to repro the high CPU usage
* Once the issue has been confirmed, open the command palette and run `Developer: Stop Tracing`
* A dialog will prompt with the location of generated trace file, please attach that file in this issue thread.

**Comment by roblourens** [comment]
I'll try that the next time I see it. Haven't seen it really recently, but when it's happening, it seems like I often still see it after restarting.

**Comment by ctsstc** [comment]
So far mine has been running good, but I feel like I'm in the same boat as @roblourens where when it happens it happens again, so I'll try to relaunch with tracing next time this happens, but it wouldn't make sense to run with tracing all the time 💀 

I do wonder if I fully closed all VSCode instances when I tried restarting it previously. I'm not sure if this tends to happen after a system restart in MacOS when it tries to reopen windows, or maybe after an update of VSCode when it tries to reopen everything 🤔

**Comment by bpasero** [comment]
Closing since users have not reported it since and we are cleaning up stale issues.

**Comment by roblourens** [comment]
I've still seen it since then but forgot you gave me tracing instructions, I'll try to remember for next time. It's easy to not notice this issue, I only notice when the fan starts, but it runs a lot anyway

**Comment by roblourens** [comment]
This was happening today, I restarted with the tracing flags, but when I use those, there is some level of CPU used by seemingly every process, is that right? That makes it hard to tell whether the CPU usage is from this issue or tracing.

**Comment by bpasero** [comment]
Some random thoughts:
* what kind of extensions do you run with and does it repro without?
* how large is your user data folder, anything large in there (thousands of files or large files)?

**Comment by roblourens** [comment]
I have 140 extensions installed currently 🤡 . Next time it is reproing stably I will try without extensions

My user-data-dir looks like this, I don't see anything unusual. 

<img width="342" alt="image" src="https://user-images.githubusercontent.com/323878/206962377-c41f3f70-be88-4677-8174-16177f2c9a4e.png">

**Comment by deepak1556** [comment]
> I restarted with the tracing flags, but when I use those, there is some level of CPU used by seemingly every process, is that right? That makes it hard to tell whether the CPU usage is from this issue or tracing.

Does the new CPU levels from all processes overshadow the high cpu usage from shared process ? Given our tracing flags invoke the cpu profiler from V8, it is expected to see a slight increase. I would recommend to attach the cpu usage output from activity monitor along with the trace next time this happens.

**Comment by gadgetmad** [comment]
I have this exact issue. I have attached a mahoosive trace file as suggested by deepak1556. Do I need to post this elsewhere?

**This is a 7zip file NOT a zip. Zip file was too large and .7z extension cannot be uploaded, So rename this to a .7z file and extract with 7zip. Apologies!**
[code-PHXIknSe.trace.txt.zip](https://github.com/microsoft/vscode/files/10435622/code-PHXIknSe.trace.txt.zip)
