### ISSUE TITLE
Process explorer: indicate extension host better?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150820]
Testing #150753

It looks like now it is harder to find the ext host process in the process explorer. I think we often ask users to look at that process so maybe we need to tweak process explorer to indicate the ext host better:

![image](https://user-images.githubusercontent.com/900690/171161377-82f8a0fe-45ea-4aae-a450-834b3f80cec9.png)

**Comment by bpasero** [comment]
Turns out this was not working on windows: looks like on windows, arguments passed to a process get lowercased, so `--vscode-utility-kind=extensionHost` became `--vscode-utility-kind=extensionhost`. I will push a fix to just pass `--vscode-utility-kind=extension-host`

That said, we still seem to pass in `--type=extensionHost`:

https://github.com/microsoft/vscode/blob/3104db414c8fedcf6e4493f14da7df0b7413853a/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L325

And I am not sure that is needed anymore?

**Comment by deepak1556** [comment]
`--type=extensionHost` is redundant, because chromium already attaches `--type=utility` when launching the process and it cannot be overwritten.

**Comment by bpasero** [comment]
We probably need to keep it until we have removed the other way of launching...

**Comment by deepak1556** [comment]
Oh yeah, missed that.
