### ISSUE TITLE
Initial language features in the Result editor would be great

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150868]
Testing #150389

For the future.

Initial language features in the result editor would be nice. Like intelli-sense and context menu language commands

**Comment by bpasero** [comment]
I wonder if this is a consequence of https://github.com/microsoft/vscode/issues/150791

To clarify: a diff editor right-hand side behaves in many ways like a normal editor. Let me open another issue to cover some more aspects of it.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/900690/171212863-e1c91a62-ceb5-4acd-a741-ff1f7c75d899.png">

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/150870

**Comment by hediet** [comment]
We turned off all editor contributions to avoid any surprises. We should turn some of them on again.

**Comment by jrieken** [comment]
To verify: 

* open merge editor
* ensure language feature like IntelliSense and mark occurrences work
