### ISSUE TITLE
Debug console lines cut off with word-wrap disabled

### ISSUE THREAD

**Issue by stroitzsch** [microsoft/vscode#150882]
Issue Type: <b>Bug</b>

# Behaviour

With `"debug.console.wordWrap": false`, the debug console displays lines cut off when printing or evaluating long multi-line variables.

Note that it works fine with `"debug.console.wordWrap": true`.

(Not sure if this an issue with VSCode or the Python extension, but just filing it here first in case.)

## Expected vs. Actual

Independent of `debug.console.wordWrap` setting, the debug console should show all lines when printing or evaluating long multi-line variables, but some lines are cut off when using `"debug.console.wordWrap": true`.

>Expected:
>![](https://i.imgur.com/E3iDuqP.png)

>Actual:
>![](https://i.imgur.com/z15ZALi.png)

## Steps to reproduce:

1. Add setting: `"debug.console.wordWrap": true
2. Add launch configuration:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "internalConsole",
            "justMyCode": true,
            "purpose": ["debug-in-terminal", "debug-test"],
        }
    ]
}
```
3. Example Python script:
```
import numpy as np

list_1 = [0, 1]
array_1 = np.transpose([list_1])

list_2 = list(range(20))
array_2 = np.transpose([list_2])
```
4. Enter debug console for above script (e.g. add breakpoint at the end).
5. Run print statements:
```
print('\n'.join(map(str, list_1)))
print(array_1)
print('\n'.join(map(str, list_2)))
print(array_2)
```
>Output:
>![](https://i.imgur.com/ddJbCCK.png)
6. Evaluate variables: `array_1`, `array_2`
>Output:
>![](https://i.imgur.com/z15ZALi.png)

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.12
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

condaPath: "<placeholder>"

languageServer: "Pylance"

```

</p>
</details>

Extension version: 2022.6.2
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.59GB (4.38GB free)|
|Process Argv|--crash-reporter-id 851521b6-18ab-45cb-b12c-619d4214f93c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by roblourens** [comment]
Should have been fixed with https://github.com/microsoft/vscode/issues/151768, let me know if you still see it
