### ISSUE TITLE
Add compare/diff options to File explorer context menu

### ISSUE THREAD

**Issue by gulshan** [Microsoft/vscode#15081]
It would be nice to have vscode working as a machine-wide file diff tool. It already has the capability. Just add "Select for Compare" and "Compare with ..." to file explorer context menu, like "Open with Code". Also this should be configurable with settings.

**Comment by gulshan** [comment]
Related- #5770

**Comment by isidorn** [comment]
This feature request will not be considered in the next 6-12 months roadmap and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
