### ISSUE TITLE
Timeline: uncheck Local History only with no Git commit doesn't clear entries

### ISSUE THREAD

**Issue by hsandt** [microsoft/vscode#150808]
Issue Type: <b>Bug</b>

When using the timeline on a project with git repository initialized but no commit at all (not even "initial commit"), unchecking Local History (but keeping Git checked) will keep showing the Local History. Only unchecking Git too will refresh the view, showing nothing.

1. Create a project and initialize .git but do not commit an "initial commit". Generally, repositories created via GitHub automatically commit an "initial commit", while repostiories created manually or via a tool like cargo init (for Rust projects) will not create an initial commit.

2. Open the project folder in VS Code and open the Timeline view. Make sure that the active filters are "Git" and "Local History".

3. Create some file and save it. You should see "File Saved" in the Timeline.

4. Click on Timeline filter icon > uncheck Local History.

Expected: Since there is no git commit, all Timeline entries disappear
Actual: All local history entries stay on place (until you also uncheck Git)

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.4.0-113-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz (8 x 2925)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|15.54GB (0.58GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1c0b12bc-3dbd-4f0d-acdc-d0a2de7634c0|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|unity|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|unity|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.58.0
increment-selection|alb|0.2.0
numbered-bookmarks|ale|8.3.0
better-toml|bun|0.3.2
doxdocgen|csc|1.4.0
clipboard-manager|Edg|1.4.2
EditorConfig|Edi|0.16.4
godot-tools|gee|1.3.0
better-cpp-syntax|jef|1.15.14
vscode-graphviz|joa|0.0.6
syntax-project-pbxproj|mar|0.1.3
csharp|ms-|1.25.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.3
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.7
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.2.0
incrementor|nms|1.0.3
cxx-set-next-statement-extension|nto|0.0.7
vscode-subword-navigation|ow|1.2.0
ravi-debug|rav|1.0.2
rust|rus|0.7.8
rust-analyzer|rus|0.3.1075
vscode-lua|tri|0.12.4
cmake|twx|0.0.17
unity-debug|Uni|3.0.2
vscode-lldb|vad|1.7.0
debug|web|0.26.0
change-case|wma|1.0.0
dictionary-completion|yzh|1.2.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by lramos15** [comment]
I think this may be partially caused by the git timeline @lszomoru doing `git init` and opening a timeline of a file in the repo you get a console error of `Failed to execute git`. This causes the git timeline to appear to infinitely load
