### ISSUE TITLE
"Open Changes" title area action is a no-op

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150867]
Testing #150389

"Open Changes" action in the Title Area is a no-op currently 🐛  
Instead of it we should have an action that opens the file with Git decorations in it (old way)

Old editor that shows Git conflicts should have a new action in the code lens "Open Merge Editor". Also one in the title area if possible.

That way these two would be inter-connected.

**Comment by daviddossett** [comment]
Agreed @isidorn 

I had this button in the toolbar (far left)

<img width="364" alt="CleanShot 2022-06-02 at 09 53 33@2x" src="https://user-images.githubusercontent.com/25163139/171683286-6fa07caf-5425-43d1-9ef7-2382037d1770.png">

..to toggle to the inline codelens format. There's also a toolbar action to flip back to the merge editor using the same icon. Open to better icons—kind of following the Settings/settings.json precedent for now.

<img width="1053" alt="CleanShot 2022-06-02 at 09 54 31@2x" src="https://user-images.githubusercontent.com/25163139/171683401-410bb229-e77c-48df-94af-563dd109d0d6.png">
