### ISSUE TITLE
Alt key behavior on Linux leads to awkward experience with new Alt hover behavior

### ISSUE THREAD

**Issue by TylerLeonhardt-alt** [microsoft/vscode#150885]
Testing #150557

![Recording 2022-05-31 at 10 12 20](https://user-images.githubusercontent.com/98423974/171233774-2ff790d5-01bb-4793-ace5-b4ea0d4b2d3d.gif)

On Linux with the native title bar, the first time you hold alt and move your cursor around, everything seems to work as expected... possibly unexpected is that the `File` menu is focused once the `Alt` key is unpressed.

Since the `File` menu is focused, pressing `Alt` again actually isn't registered at all by the editor (hence not seeing the `Alt` show up in screencast mode)... and instead all it does is "unfocus" the `File` menu.

The leads to an awkward experience as I was expecting the `Alt` hover behavior to "just work" but instead I have to try the `Alt` hover an extra time now that the `File` menu is no longer focused.

I think if there is any way we can avoid that initial focus to `File` when I didn't really want that, that would be ideal. Maybe only focus `File` if `Alt` isn't held down for some time? Maybe only focus `file` if there isn't a hover? 

I'm curious if this repros on Windows with the custom title bar disabled (if that's still an option)

> This is @TylerLeonhardt's alt account on Linux

**Comment by Tyriar** [comment]
It can also happen on Windows, this is just a side effect of using the feature right now because the file menu handles the event itself. I feel like any workaround here would be a hack and the impact is quite small anyway. Let's wait for more feedback before actioning.

**Comment by TylerLeonhardt** [comment]
Isn't the native file menu the default on Linux? That's decent impact

**Comment by Tyriar** [comment]
@TylerLeonhardt it happens in the custom menu too, the impact is there's a somewhat unexpected rectangle in the top left there using the mouse, I don't think focus is that important while locking the hover.
