### ISSUE TITLE
Renaming a file in explorer immediately after renaming another can fail

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150834]
The minimal repro isn't clear to me but this is what I was doing.
Repro:
1. Create 2 files, UTC24.TGA and TGC32.TGA
2. Rename UTC24.TGA to utc24.tga
3. Press in quick succession: enter, down, f2
4. The rename input will appear briefly and then close

I hit this many times in past 2 days when doing these types of renamed, gets pretty frustrating.

![Recording 2022-05-30 at 07 45 21](https://user-images.githubusercontent.com/2193314/171175697-f46a171e-fd82-46ab-9c09-616fc0095553.gif)

**Comment by lramos15** [comment]
Hmm, do you still see this today? I'm not fast enough on my mac to hit it

**Comment by Tyriar** [comment]
Seems to work now 🎉
