### ISSUE TITLE
Window titles in Window menu are not updating

### ISSUE THREAD

**Issue by sushil-propel** [microsoft/vscode#150852]
Issue Type: <b>Bug</b>

In the settings, it is possible to change the window title format. So I changed mine to `${rootName}${separator}${activeEditorShort}`. However, when I click on the Window menu, it shows the open workbench windows in the default manner: `${activeEditorShort}${separator}${rootName}`

I expect the window titles to update here as well. I tried quitting the app and restarting, but it still did not update.

I am on a MacBook Pro (14-inch, 2021) with the Apple M1 Pro chip. 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:04.972Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

**Comment by sbatten** [comment]
This does not repro for me on the latest builds. Please re-open if you still see this issue.
