### ISSUE TITLE
Although JavaScript debugger is activated no suggested debuggers show up

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#150801]
Testing #150662

<img width="707" alt="capture" src="https://user-images.githubusercontent.com/1931590/171150215-ebdcec4f-0c74-49e0-aa79-5c197d568ecc.png">

**Comment by luabud** [comment]
I was able to reproduce this (or at least I think I was 😅) with the C++ extension. 

Repro steps:
1. Create an empty `hi.cpp` file
1. Open it so the C++ extension activates
1. Close it
1. Click on the run and debug button

It doesn't show it on the suggestion list:

![image](https://user-images.githubusercontent.com/45497113/171289118-760295ff-9c90-4459-ba08-3b31e3810050.png)

**Comment by roblourens** [comment]
If it doesn't show up in the list at all, then that extension doesn't contribute a debug config provider, which seems to be the case for them, that's ok.

**Comment by dbaeumer** [comment]
@roblourens I followed the steps from the test plan item 

> Run the "Add Browser Breakpoint" command

**Comment by roblourens** [comment]
It works for me when I 

- Reload the window
- Run "Add Browser Breakpoints"
- Click the Run and Debug button

Are you sure you hadn't clicked the Run and Debug button or another action to start debugging before activating the js-debug extension?

**Comment by luabud** [comment]
FWIW this is also working for me:

![image](https://user-images.githubusercontent.com/45497113/171966753-5dea9cd7-5e97-46f2-83c0-f282daa91f61.png)


Although I'm not sure why I have two node.js options, maybe some other extension I have installed.

**Comment by roblourens** [comment]
Maybe you have both the js-debug nightly and non-nightly extensions enabled? Do they do the same thing?

**Comment by roblourens** [comment]
Or could be some other extension too

**Comment by dbaeumer** [comment]
Ran through the steps again on latest insider and now I see the suggested configurations.

**Comment by roblourens** [comment]
Thanks
