### ISSUE TITLE
Merge editor: show a diff for when a change is accepted

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150816]
Testing #150389

Imagine I have checked a change to be accepted from the one side:

![image](https://user-images.githubusercontent.com/900690/171159371-035e6889-9391-4ea7-95b2-36b5d0d4cfcb.png)

It would help me a lot if I then get to see a diff of my change to the ancestor to reason about the change. In fact, I would use this feature to understand the other side change too to learn what the other author had in mind.

Currently it seems that clicking the checkbox accepts the change from the one side into the editor. 

For this to work we would probably have to apply the diff editor decorations (word level diff).

![image](https://user-images.githubusercontent.com/900690/171159777-a65449d7-2fb3-43df-ac65-d10d2271940a.png)

**Comment by hediet** [comment]
> Currently it seems that clicking the checkbox accepts the change from the one side into the editor.

This is right. What should it do otherwise?

> For this to work we would probably have to apply the diff editor decorations (word level diff).

I like that! Didn't have time to implement it so far though.

Ideally, we can even show the diff of each side to the ancestor. I don't know how though.

**Comment by bpasero** [comment]
Yeah I think accepting a change when you click the checkbox makes sense, I am overall more referring to have some kind of diff support in the merge editor similar to when I actually use the diff editor to review a change. The merge editor so far seems to lack visual diffing which would be the cherry on the ice cake to make merging a pleasure.

**Comment by daviddossett** [comment]
@bpasero that's what I was roughly following in the original designs. Definitely helps with recognizing the actual change. 

<img width="730" alt="CleanShot 2022-06-02 at 09 50 33@2x" src="https://user-images.githubusercontent.com/25163139/171682744-57e53d0e-15b9-439a-a966-448bc6461f71.png">

**Comment by hediet** [comment]
Now there are word level diff decorations as well as commands to show a diff between input1/2 and base.

**Comment by hediet** [comment]
Verification steps:

## Preparation
```
git clone https://github.com/hediet/vscode-3wm-test-repo.git
cd vscode-3wm-test-repo
git fetch --all
git checkout input1
git merge input2
```

Open VS Code Insiders in that folder and open the 3 way merge editor:

![image](https://user-images.githubusercontent.com/2931520/175989511-a6288cd7-b855-4044-9404-b109d293af4e.png)

## Verification
* Observe that changes are highlighted
