### ISSUE TITLE
Merge editor: preserve view state

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150804]
Testing #150389

Similar to https://github.com/microsoft/vscode/issues/150791 where [`BaseTextEditor`](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/browser/parts/editor/textEditor.ts#L44) provides some helper methods for storing editor view state, the merge editor should associate view state like the diff editor does: e.g. selection, folding regions etc. so that they can restore after window reload.

One thing that is special about the diff editor: when you open a diff editor for the first time, we automatically reveal the first diff and ignore any previous view state. This helps focussing on what has actually changed. However, when a diff editor was opened before and is just made active again, we do restore the view state.

**Comment by jrieken** [comment]
To verify:

* open merge editor
* select something in input1, show the find widget in input2, etc
* reload the window or close/reopen the editor 
* ensure that the view state is restored

**Comment by isidorn** [comment]
I can still reproduce this, reopening. I am following steps from the above comment. Here's a gif:

![Recording 2022-06-28 at 20 21 23](https://user-images.githubusercontent.com/1926584/176254880-e6abaff9-78d8-476b-8c92-9a8a550c7b2d.gif)

**Comment by jrieken** [comment]
Sorry forgot to mention that it needs todays insiders.

**Comment by jrieken** [comment]
Still doesn't work... Need to investigate., sorry for the fuzz

**Comment by jrieken** [comment]
Sorry, my verification steps are bad. The find widget isn't part of any editor view state, selecting and folding etc is. So

To _verify_:

* open merge editor
* select something in input1, select something in input2, fold something input3
* reload the window or close/reopen the editor
* ensure that the view state is restored
