### ISSUE TITLE
linux chroot builds Readme update, vscode yarn errors, Husky error or git commit -all -m up, 

### ISSUE THREAD

**Issue by TomTravis** [microsoft/vscode#150866]
Does this issue occur when all extensions are disabled?: Yes/No yes

- VS Code Version: Current Github repo
- OS Version: Linux debian 
linux install
[readme_update](https://github.com/microsoft/vscode/wiki/How-to-Contribute)
<<---sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev python-is-python3
--->>sudo apt-get install build-essential g++ libx11-dev libxkbfile-dev libsecret* python3

root@coco:/home/coco/vscode# apt-cache search libsecret
gir1.2-secret-1 - Secret store (GObject-Introspection)
libsecret-1-0 - Secret store
libsecret-1-dev - Secret store (development files)
libsecret-common - Secret store (common files)
libsecret-tools - tool for storing and retrieving GObject passwords

root@coco:/home/coco/vscode# apt install libsecret-1-dev libsecret-1-0 libsecret-common build-essential g++ libx11-dev libxkbfile-dev libsecret-1-dev python3

Steps to Reproduce: git .. clone ..microsoft/vscode
[readme_linux](https://github.com/microsoft/vscode/wiki/How-to-Contribute)
1.#check install make sure you run as root not sudo to create a root passwd >>sudo passwd (new password, su (password) to change login ID, install from user account no errors
2. yarn -v
3. npm -v update npm install -g npm@latest
4. node -v curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
5. python3 -V
6.# start clean new build
7. ./scripts/npm.sh &>npm-sh.log
8. tail npm-sh.log

**this will be update for chroot Debian ./scripts/npm.sh &>npm-sh.log
non chroot works it appears** 

root@coco:/home/coco/vscode# apt-cache search libsecret
gir1.2-secret-1 - Secret store (GObject-Introspection)
libsecret-1-0 - Secret store
libsecret-1-dev - Secret store (development files)
libsecret-common - Secret store (common files)
libsecret-tools - tool for storing and retrieving GObject passwords
root@coco:/home/coco/vscode# git commit --all -m up

> husky - npm run -s precommit
> husky - node v16.15.0

Reading git index versions...

[main b54623e1d68] up
 Committer: root <root@coco>
Your name and email address were configured automatically based
on your username and hostname. Please check that they are accurate.
You can suppress this message by setting them explicitly. Run the
following command and follow the instructions in your editor to edit
your configuration file:

    git config --global --edit

After doing this, you may fix the identity used for this commit with:

    git commit --amend --reset-author

 1 file changed, 2000 insertions(+), 2606 deletions(-)
root@coco:/home/coco/vscode#

**Comment by TomTravis** [comment]
![Screenshot at 2022-05-31 08-25-16](https://user-images.githubusercontent.com/46386261/171211581-24238b2c-afdb-45be-9b9d-ba4a713c2caf.png)
![Screenshot at 2022-05-31 08-28-00](https://user-images.githubusercontent.com/46386261/171211623-50ce5ad5-486d-4e70-9c2b-eb9e912a9d8e.png)
new repo install 
git pull is clean
the build is progressing

**Comment by Tyriar** [comment]
Please stop spamming us with issues. Based on your other issues it seems to me you either did some setup wrong of have a problem with your environment. Note that this is not a support forum, if you're having a slew of issues related to the build it's probably your machine as we have many people building on Linux.

You might find it useful to see how we build the product in CI which is defined here:

https://github.com/microsoft/vscode/blob/717bb2892f32c298ec0b76b5d81d040330bd3c4a/.github/workflows/ci.yml#L97-L177

**Comment by TomTravis** [comment]
> Please stop spamming us with issues. Based on your other issues it seems to me you either did some setup wrong of have a problem with your environment. Note that this is not a support forum, if you're having a slew of issues related to the build it's probably your machine as we have many people building on Linux.
> 
> You might find it useful to see how we build the product in CI which is defined here:
> 
> https://github.com/microsoft/vscode/blob/717bb2892f32c298ec0b76b5d81d040330bd3c4a/.github/workflows/ci.yml#L97-L177
> 
> #150500, #150689, #150765

it not spam calm down
arm64 failed
[coco@localhost:~/vscode] $git commit --all -m up

> husky - npm run -s precommit
> husky - node v16.15.0

Reading git index versions...

Error: Cannot find module '@typescript-eslint/experimental-utils'
Require stack:
- /home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js
- /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/rules.js
- /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/linter.js
- /home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/api.js
- /home/coco/vscode/node_modules/gulp-eslint/index.js
- /home/coco/vscode/build/hygiene.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js:7:30)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/coco/vscode/build/lib/eslint/code-no-unexternalized-strings.js',
    '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/rules.js',
    '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/linter.js',
    '/home/coco/vscode/node_modules/gulp-eslint/node_modules/eslint/lib/api.js',
    '/home/coco/vscode/node_modules/gulp-eslint/index.js',
    '/home/coco/vscode/build/hygiene.js'
  ]
}

> husky - pre-commit hook failed (add --no-verify to bypass)
> husky - to debug, use 'npm run precommit'

**Comment by Tyriar** [comment]
That module is in the yarn.lock and it has been since January, it should work:

https://github.com/microsoft/vscode/blob/5854ef865c12cd0da295485dc676416779da106e/build/yarn.lock#L685-L690

Try `yarn add @typescript-eslint/experimental-utils@^5.10.0` to force it. Use `git commit --no-verify` if it still causes problems
