### ISSUE TITLE
Search results inaccurate after resizing terminal panel

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#150886]
Testing #150554

1. Create a new integrated terminal 
2. Type in `echo "foo"` and hit enter
3. Type in `echo "foo"` and hit enter again
4. Ctrl+F and search for "foo", you should see four results
5. Resize the integrated terminal so the first `echo "foo"` is out of view
6. Ctrl+F again 
7. :bug: there's only two results, not four

**Comment by Tyriar** [comment]
This is how conpty handles resize on Windows currently, if you resize to bring them back again you should see the `foo` lines are actually removed:

![image](https://user-images.githubusercontent.com/2193314/171842608-6a7b7e32-c130-4b51-915e-4d21be6cba20.png)
