### ISSUE TITLE
Deprecated extensions - warning message suggestions

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#150827]
Testing #150746

Old: 
This extension has been deprecated. Use Live Preview instead.
This extension is no longer being maintained and is deprecated.
This extension is deprecated and has become a native feature in VS Code. Configure these settings instead.

New:
This extension is deprecated. Install the Live Preview extension instead.
This extensions is deprecated as it is not longer being maintained.
This extension is deprecated as this functionality is now built-in to VS Code. Use these settings to enable the built-in functionality.

**Comment by sandy081** [comment]
Thanks for recommendations. Updated with slight changes:

This extension is deprecated. Use the Live Preview extension instead (goes well if Live Preview extension is already installed)
This extensions is deprecated as it is not longer being maintained.
This extension is deprecated as this functionality is now built-in to VS Code. Configure these settings to use this functionality.
