### ISSUE TITLE
Open sponsor link should ask user if they want to open an external URL

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150828]
Testing #150748

1. code-insiders with new user data dir
2. Search for my extension isidor-tryout https://marketplace.visualstudio.com/items?itemName=inikolic.isidor-tryout
3. Click on the sponsor link -> notice how the patreon link just opens

I would have expected that VS Code would ask me if I am sure I want to open an external link.
I think we should just re-use the service that @rzhao271 introduced

**Comment by sbatten** [comment]
This was introduced via https://github.com/microsoft/vscode/issues/124325 by @JacksonKearl. The logic is that the workspace is trusted and therefore we don't need to prompt, but I'm not sure we considered extension provided links.

**Comment by sandy081** [comment]
Good idea. I like that by default we show the dialog if the domain is not trusted. One can override that if they depend on workspace trust.

**Comment by sandy081** [comment]
Is it possible to get this into this milestone?

**Comment by sbatten** [comment]
Jackon's change was actually introduced a year ago (May '21). Should this change come from @bpasero @lramos15 ?

**Comment by isidorn** [comment]
Oh wrong May haha
Then it might be fine to do this in debt week. I leave it up to you to decide :)

**Comment by bpasero** [comment]
I suggest that this change is done by someone on the workspace trust team because the motivation for the change in the first place comes from you and you know best how you want to treat trust and link opening I would say. I can review the change though.

**Comment by sbatten** [comment]
I see 3 parts here:
1) The code in the opener service that correlates workspace trust and trusted domains
2) The opener service options bag that tells us where it should be correlated
3) The adoption of others to opt into this behavior

I can do 2 and update 1 if that's a reasonable property on the openerservice api

**Comment by sbatten** [comment]
sorry I didn't get to this in June, will tackle next week
