### ISSUE TITLE
updatable git menu (feature request)

### ISSUE THREAD

**Issue by SailorMax** [Microsoft/vscode#15085]
- VSCode Version: 1.7.1
- OS Version: Windows 10 64bit

Steps to Reproduce:

1. open Git tab
2. wait while git start refreshing
3. open "More" menu to make pull

Expected: "More" menu with mass of disabled items while git refreshing is active. But when it finished, disabled items start to be active. Or all items is active always, but if git refreshing is active all actions write in the queue.

Actual: "More" menu with mass of disabled items. User have to reopen it to catch moment when refreshing is done, when all required items will be active.

**Comment by joaomoreno** [comment]
Sorry, but the menu is a native one, which blocks the JavaScript stack. Closing as won't fix.

**Comment by SailorMax** [comment]
@joaomoreno "Or all items is active always, but if git refreshing is active all actions write in the queue"?

**Comment by joaomoreno** [comment]
We don't really have a _queue_ of actions. What would happen if the action really can't run when the _queue_ is allowed to run?

**Comment by SailorMax** [comment]
Then you can output standard error message at top of window. Like you did when git command return error code.

I think for user is much easer make action and wait result, than wait while some process will finish its job, make some action and, again, wait result. When I want make push / pull / pull rebase, I not interested in result of "refresh", but currently I have to wait..

I talk about commands, which disabled while refreshing in action. Not totally all commands.
