### ISSUE TITLE
No prompt with shell integration enabled on linux

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#150892]
Haven't tried this on Linux in a while. When I enable shell integration, there is no prompt and no shell integration decorations:

<img width="655" alt="image" src="https://user-images.githubusercontent.com/323878/171256433-bacc473c-58b0-47a6-ae82-fd2e4e1dad70.png">

With shell integration disabled, it looks like this:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/323878/171256475-c56b0829-2196-4232-952d-c04435efc1c2.png">

**Comment by Tyriar** [comment]
Think I broke it on Friday 😅

**Comment by meganrogge** [comment]
fixed with 7b264cb51fbbae2050e7f985813003adaf2b8952
