### ISSUE TITLE
Comment cards are too wide

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#150824]
When I use vscode fullscreen, with a single editor, the comment cards can be too long and get awkward:

![image](https://user-images.githubusercontent.com/485572/171162109-ffc812bb-aad0-4ccb-b20e-ae16e250f6a8.png)

Also, when a comment is long, it can be difficult to read a very long line.
Both problems could be fixed by using a maximum width for comment cards.

cc @albertelo

**Comment by daviddossett** [comment]
Is the mouse movement the issue? Or is it that you're having difficulty noticing the actions in the first place? It's worth thinking about how often comments are really edited and deleted in this context. 

It could also be worth exploring bringing those right-aligned actions closer to the main content. E.g. next to the timestamp. However I'd be somewhat wary of moving them there given the added noise.

**Comment by laurentlb** [comment]
One related issue is that we have other actions in the top-right corner. We are putting them there because it's the only place to have actions that affect the comment thread.
I think the situations would be better if the actions were moved to the left. Multiple users didn't see the icons on the right.

**Comment by misolori** [comment]
It's worth noting that this applies to all of our peek views as well since they are using the same widget/style. We'd want to have our header actions consistent but the individual comments can be responsive and align closer to the text and then stick to the right when the text is wider and the view is shorter.

<img width="3008" alt="CleanShot 2022-05-31 at 12 42 13@2x" src="https://user-images.githubusercontent.com/35271042/171271582-2aa2ec0d-5885-4474-a1a4-40583004b310.png">

**Comment by albertelo** [comment]
One issue with responsive behaviours and big screens is that a comment that is long will be rendered in a way that makes it hard to read. For example, a card with a 1200px width would fit 25 words (169 characters) in a single row, which makes it harder to read:
![Screen Shot 2022-06-07 at 11 04 12](https://user-images.githubusercontent.com/26898237/172341610-d8b663a1-9ef8-438c-a157-77f7b19a2bb7.png)

Reducing the width would improve readability

**Comment by daviddossett** [comment]
Ok, seems like there are a couple of related issues here. As @misolori pointed out, the parent widget (incl. header actions location) itself should likely remain as is given that it's shared across a bunch of components and scenarios. 

Do you have anything specific in mind for improving the comment actions and line lengths?

**Comment by misolori** [comment]
A short term solution would be to place a max-width on the comment section, cc @alexr00 for thoughts on this:

<img width="1328" alt="CleanShot 2022-06-07 at 09 49 13@2x" src="https://user-images.githubusercontent.com/35271042/172438464-e8487591-501e-4ab9-9632-51c3d8542149.png">

but ideally a shorter container would look better:

<img width="848" alt="CleanShot 2022-06-07 at 09 54 39@2x" src="https://user-images.githubusercontent.com/35271042/172439342-1102debc-80d8-4e5c-9b01-ff261b8f0a3a.png">

**Comment by albertelo** [comment]
I'm guessing this breaks the parent component, but you could also add the icons to the right of the time stamp
![5hCB7LGMo3rEAkK](https://user-images.githubusercontent.com/26898237/172439975-63795e21-d891-42b9-8525-770a5f236cf6.png)

@daviddossett: besides placing a max-width to the comments or the container, if there's a chance to edit the component like Miguel proposed then that's a reasonable solution IMO

I it possible to treat the comment card as a different component than peek views?

**Comment by laurentlb** [comment]
> Limiting the size of the comment body itself seems visually a little bit cleaner:

Note that there are actions on the top-right corner:
![image](https://user-images.githubusercontent.com/485572/172444491-a0ba9355-076f-4b4c-af40-05bb7882ac95.png)

If we limit the comment body and keep those icons on the far-right, they'll be easy to miss.

**Comment by daviddossett** [comment]
That's the tradeoff here. Moving the header actions is a larger change that affects all Peek views.

Are there other actions exposed here beyond collapse all comments/collapse?

**Comment by laurentlb** [comment]
Yes. It's the main extensibility point for custom actions (provided by extensions).

If we find a way to provide actions somewhere else (could be next to "Reply"), that would work very well, IMO.

**Comment by hermannloose** [comment]
Side note: since @daviddossett asked about mouse travel as an issue in https://github.com/microsoft/vscode/issues/150824#issuecomment-1142409051, I wanted to give some context that we currently have a "quick reply" action / command there in our extension, to easily mark a thread as resolved while not having to manually type out a reply. As @laurentlb pointed out, it's the only contribution point for actions relating to the thread (vs an individual reply / comment).

That means even when users know where the actions are found and the comment contents happen to be short and don't run into readability problems through long lines, usability will suffer on large screens because this combines a large amount of mouse travel with a small click target that requires precision (i.e. in direct conflict with Fitts's law).

**Comment by misolori** [comment]
It's worth noting that having the window maximized on a large monitor does make the entire experience harder to use, not just for comments, for example in the panel:

<img width="3008" alt="CleanShot 2022-06-08 at 08 45 39@2x" src="https://user-images.githubusercontent.com/35271042/172660315-7214e14f-0b35-4874-bc79-495771446a40.png">

I actually don't know how many people keep their windows at this size so let's take a look at the telemetry first to see how many users it's impacting and then we can go from there. We're all so focused on the comments/peek widget but there are so many other similar issues that I would be afraid to create a solution that only solves for a single area while making others inconsistent.

**Comment by daviddossett** [comment]
I did some digging into our telemetry to get a rough sense of window sizes across our active users:

| Percentile | Width |
| ------------- | ------|
| Average | ~1403px |
| 50th | 1366px |
| 75th | 1,713px |
| 90th | 1,920px |
| 95th | 2,133px |

Seeing that data, my sense is that while this is indeed a challenge on really large screens, it isn't something that the vast majority of users are likely struggling with. Panels toolbars, Editor toolbars, and other areas all have a similar challenge on very large screens.

That's not to say I would dismiss this is as an issue. @misolori: thoughts on adding an exploration item to our [UX backlog](https://github.com/microsoft/vscode/issues/146840) to explore how we might adapt this sort of challenge (i.e. right-aligned actions) to much larger screens?

**Comment by daviddossett** [comment]
> I agree, even that screen is displayed is inconsistent with the rest of the interface

That UI belongs to an extension FYI. I think that screenshot is better used as an example for the panel and editor actions being far away in the top right and bottom right, respectively. 

They might be reducing the size, but I'd venture a guess that it would be a minority statistically. We've added this effort to the [UX backlog](https://github.com/microsoft/vscode/issues/146840) so we can do some explorations to solve for this beyond just the Peek view. We would love any ideas in the meantime! 

I wonder what other apps have solved for problems like this? Here's a great example from Slack where they keep common actions right aligned despite the large screen width. It would be great to learn how and why different products solved for this—or why they let it be.

<img width="2252" alt="CleanShot 2022-06-10 at 09 10 41@2x" src="https://user-images.githubusercontent.com/25163139/173107460-57cf009c-4736-433d-9b66-f20680ffcfda.png">

**Comment by Aryan-Koul29** [comment]
I am new to open source contribution field and I think this is a good issue that I can start with. So can you please assign me this issue?

**Comment by alexr00** [comment]
@Aryan-Koul29 thank you for your interest but this is not a good issue to start with as we do not want to make a one-off change for comments and instead would try to solve this for all editor zone widgets. Please see https://github.com/microsoft/vscode/wiki/How-to-Contribute#where-to-contribute for guidance on where you could start.

**Comment by Aryan-Koul29** [comment]
Okay! Thank you mam for the help.

**Comment by JonasMa** [comment]
I had another look at this and wouldn't consider this a problem of the top 10% of screen widths. This comment on an average width editor is quite wide and already.
![image](https://github.com/microsoft/vscode/assets/6637517/ac6c8977-167a-4882-b2d1-976d61e3ba06)

Our users tell us on a regular basis that they are having problems with this, seemingly independent of screen size.

Are there any plans to move forward with this?

**Comment by alexr00** [comment]
Closing as no changes are currently planned.
