### ISSUE TITLE
global search can not search file of encoding utf-16 , it will ignore the file

### ISSUE THREAD

**Issue by fangngng** [Microsoft/vscode#15080]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|Theme-Afterglow|gerane|0.0.2|
|Theme-FlatlandDark|gerane|0.0.2|
|csharp|ms-vscode|1.4.1|
|vscode-mssql|sanagama|0.0.4|
|preview-vscode|searKing|1.1.1|

---

Steps to Reproduce:

1. global search can not search the file of encoding utf-16 
2.

**Comment by bpasero** [comment]
Lets continue in https://github.com/Microsoft/vscode/issues/17408
