### ISSUE TITLE
Render merge decorations in the editor scroll bar

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#150861]
Testing #150389

I suggest to have a nice decoration in the editor scroll bar for each merge conflict.
If the merge is multiline I would expect that we mark the center location in the scroll bar.

**Comment by rebornix** [comment]
This is currently my major pain point of using the merge editor as I don't know if I have more merge conflicts in a long file, I have to scroll all the way down (and slowly to ensure I don't miss any).

**Comment by isidorn** [comment]
Thanks for adding this 👏 
Adding verification-needed so I try it out this week.
