### ISSUE TITLE
Naming new folder "**" makes red text box turn bold

### ISSUE THREAD

**Issue by montw08** [microsoft/vscode#150856]
![The red dialog box with bold text](https://user-images.githubusercontent.com/87945447/171194649-7a539579-659a-4fea-9f84-98c103a0834c.png)

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: **1.67.2**
- OS Version: **Windows 11 10.0.22000 Build 22000**

Steps to Reproduce:

1. Click the *new folder* button in the explorer panel;
2. Name the new folder "**", without the quotation marks;
3. The text from red dialog box under the folder name is now bold, except for "The name ".

**Comment by montw08** [comment]
Probably because of markdown

**Comment by meganrogge** [comment]
The text box doesn't turn red or bold, so considering that a success @lramos15

**Comment by lramos15** [comment]
> The text box doesn't turn red or bold, so considering that a success @lramos15

The text box should still be read saying it's an invalid file name on windows. Just the text should not become bold

**Comment by montw-dev** [comment]
> The text box doesn't turn red or bold, so considering that a success @lramos15 

I think the box is supposed to be red

**Comment by meganrogge** [comment]
the box did not turn red for me with a folder name of `**`

**Comment by lramos15** [comment]
> the box did not turn red for me with a folder name of `**`

Was this on windows?

**Comment by meganrogge** [comment]
no it's working for me on windows. it wasn't working on mac

**Comment by lramos15** [comment]
> no it's working for me on windows. it wasn't working on mac

** just happens to be a valid file name on macOS 🤷 , thanks for verifying!
