### ISSUE TITLE
Spawn listener not disposed?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150821]
Testing #150753

Found that when opening multiple windows, the listener that prints about spawning increments over and over even though I would have expected that maybe this listener is being disposed after being used once and for sure when a window closes:

![Recording 2022-05-31 at 13 18 26](https://user-images.githubusercontent.com/900690/171161711-be0cb8c3-986f-4c28-a791-dcc02ef68619.gif)

**Comment by alexdima** [comment]
Yes, the `spawn` listener is not disposed, and I'll use this issue to fix that, but there is also a separate problem where the `spawn` event is emitted on all `UtilityProcess` instances when one `UtilityProcess` is created. Tracking that at https://github.com/microsoft/vscode/issues/153083
