### ISSUE TITLE
Merge editor: support selection for history navigation

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150805]
Testing #150389

When you implement `onDidChangeSelection` and `getSelection` from the merge `EditorPane` you can opt the merge editor into playing nice with "Go Back", "Go Forward" by supporting:
* navigation within a single editor
* navigation between the three editors

**Comment by jrieken** [comment]
This now works thanks to @bpasero's refactorings. We always return the main editor to the "outside" world and that nice contributes to the navigation world. Moving to July to decide if it's OK to only have this for the result editor or if all sides should contribute here

**Comment by jrieken** [comment]
Taking the diff-editor as reference and closing this as done

**Comment by bpasero** [comment]
**Verification:**
* open a merge editor and click into result editor
* move cursor around meaningful (> 10 lines apart)
* invoke Go back / Go forward and verify you stay within the result editor for editor history navigation
