### ISSUE TITLE
`BugIndicatingError` default message

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150806]
I came across the new `BugIndicatingError` and wonder whether the default error message should align with the default error message we had before.

Yours:

https://github.com/microsoft/vscode/blob/27fc8f70758943221c8a9c0a248b4a4f7b18b198/src/vs/base/common/errors.ts#L263

Our default:

https://github.com/microsoft/vscode/blob/897ab9567cc31477e5955a7f4b34750b6faacbaf/src/vs/base/common/errorMessage.ts#L45

The default error message is also localized.

**Comment by hediet** [comment]
I prefer "unexpected bug" over "unknown error". The former clearly indicates we are to blame. The latter could also be caused by a misbehaving file-system, connectivity issues or bad extensions.

**Comment by bpasero** [comment]
@hediet I think my intent was to preserve at least this part: `Please consult the log for more details.`
