### ISSUE TITLE
Merge editor: have a setting for default layout

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150813]
Testing #150389

I am a fan of the side by side layout with 3 columns so would be good to have a setting to drive this.

**Comment by isidorn** [comment]
I think we should remember the last layout a user used in user storage.
So I think it is the same if the user changes the layout once or changes the setting. So maybe a setting is not needed?

**Comment by bpasero** [comment]
Yeah also fine by me.

**Comment by jrieken** [comment]
This is now persisted/sync'd user state

**Comment by jrieken** [comment]
To verify:

* open merge editor
* make sure its overflow menu (`...`) shows actions for "Column Layout" and "Mixed Layout"
* make sure the current layout mode is reflected with a check box
* make sure the layout mode is presisted (and sync'd across machines)
