### ISSUE TITLE
Adopt custom hovers in view header toolbars

### ISSUE THREAD

**Issue by TylerLeonhardt-alt** [microsoft/vscode#150884]
Testing #150557

![Recording 2022-05-31 at 10 06 16](https://user-images.githubusercontent.com/98423974/171233047-4d20af22-e6f1-479d-9195-8407c4a9689e.gif)

When I press Alt after these hovers are displayed, they disappear (and cause `File` to be selected). This is confusing due to difference of behavior.

> This is @TylerLeonhardt's alt account on Linux

**Comment by Tyriar** [comment]
We have talked about this problem and I think the current plan is that we will move towards the custom hover everywhere. Moving to @sbatten as this is specifically about view headers.

**Comment by sbatten** [comment]
I think an adoption of custom hovers here would be an adoption for all action/toolbars, but maybe there is a flag. Is the recommendation to go ahead with this change?

**Comment by bpasero** [comment]
I think this should cover all action bars, not just in view headers to be consistent. It seems unpractical to ask every user of action bars to pass down the `IHoverDelegate`. We will only play catch-up game for users forgetting about this. For this, I would probably let the workbench set a default hover delegate on startup that is then being picked up by widgets in `base` automatically.

**Comment by bpasero** [comment]
I think this can be closed?
