### ISSUE TITLE
Empty parentheses are shown when there is no code

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#150832]
Testing #150750

![image](https://user-images.githubusercontent.com/10746682/171173649-ef94512d-2ab1-4d9d-8789-c42493edb729.png)

**Comment by lszomoru** [comment]
This is expected. In the original screenshot that was attached when the issue was filed, when the problem did not have a code we should show `()`. After implementing the fix, we show `-` when the code is missing.
