### ISSUE TITLE
Names of settings not translated

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#150891]
Testing https://github.com/microsoft/vscode/issues/150577 in Firefox, with Spanish (es-es) set

When I open the Settings UI, I notice the description of settings is translated, but not the actual settings names, i.e. `Files: Auto Save` and others shown in English below:

![image](https://user-images.githubusercontent.com/25310137/171232970-2e076a51-0617-4191-be1d-97d3f85f8d87.png)

**Comment by TylerLeonhardt** [comment]
@rzhao271 do you own settings all up or just the editor?

**Comment by rzhao271** [comment]
Also assigning Sandeep for now. Is the `label` field is for the Settings editor only, or will it also affect Settings JSON files?

**Comment by gjsjohnmurray** [comment]
Are you open to a PR for this? If so please add the `help wanted` label.

**Comment by isidorn** [comment]
Sometimes the auto computation of a setting label does not work. For example the Azure extension team has an old extension id that is used as a setting id prefix which they do not want surfaced in the UI. More details here https://github.com/microsoft/vscode-discussions/discussions/406#discussioncomment-4665168

**Comment by alexweininger** [comment]
> Sometimes the auto computation of a setting label does not work. For example the Azure extension team has an old extension id that is used as a setting id prefix which they do not want surfaced in the UI. More details here [microsoft/vscode-discussions#406 (comment)](https://github.com/microsoft/vscode-discussions/discussions/406#discussioncomment-4665168)

Yes if there was an optional property on a settings item where we could override the value used to compute the setting title, that'd be perfect.

**Comment by maxrandolph** [comment]
Any update on this issue? It seems this is still an issue.

**Comment by elijah-potter** [comment]
This is also an issue when the setting ID isn't camelCase.

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/191807
