### ISSUE TITLE
JS/TS language features keeps on reseting

### ISSUE THREAD

**Issue by jsonpj3wt** [microsoft/vscode#150883]
Issue Type: <b>Bug</b>

We have a decently large mono-repo with yarn workspaces (consisting of 3 libs and 7 nodejs backend apps).  No idea why the TS Server keeps on freaking out but a reset every now and then of VS Code resolves the issue

VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id b7df6376-a7d1-4824-9a40-4a3e3991e34c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
nestjs-files|Abh|0.5.1
csharp-to-typescript|adr|1.12.1
Bookmarks|ale|13.3.0
ng-template|Ang|13.3.4
vscode-eslint|dba|2.2.2
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.12.2
prettier-vscode|esb|9.5.0
vscode-env|Iro|0.1.0
xml-format|mik|1.1.2
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
python|ms-|2022.6.2
vscode-pylance|ms-|2022.5.3
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.7
vscode-react-native|msj|1.9.2
docthis|oou|0.8.2
prisma|Pri|3.14.0
quicktype|qui|12.0.46
vscode-icons|vsc|11.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by jsonpj3wt** [comment]
@mjbvz so far, the insiders build seems to be working better.  My colleague also is seeing this but we are not using the insiders build.  Attempting some stress tests on it now and will let you know what happens.
