### ISSUE TITLE
Problems view table - source column does not show `...`

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#150835]
Testing #150750

Create an extension that generate diagnostics without source set and you see following:

![image](https://user-images.githubusercontent.com/10746682/171175049-b4e59bd9-a243-48b6-a1cc-b70c673cfc48.png)

```ts
const diagnosticCollection = vscode.languages.createDiagnosticCollection();
const diagnostics: vscode.Diagnostic[] = [];
 diagnostics.push(new vscode.Diagnostic(new vscode.Range(new vscode.Position(0, 0), new vscode.Position(0, 0)), `test`, vscode.DiagnosticSeverity.Error));
diagnosticsCollection.set(uri, diagnostics);
```

Also if the source name is longer, it is trimmed off and can't resize the source column to see completely. 

I wonder if it is necessary to show source and I think we do not show it in tree mode

**Comment by lszomoru** [comment]
Pushed changes to:
- increase the maximum width of the "Code" and "Source" columns to have the ability to expand them
- fixed an issue where text overflow ellipsis was not showing correctly on the "Source" column
- there is now a tooltip which should help seeing the complete contents of a column
