### ISSUE TITLE
Application takes a long time to close now

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#150818]
Testing #150753

When I just launch and then quit VSCode, I see the black dot on the dock for quite some time. I have launched from CLI:

![Recording 2022-05-31 at 13 15 24](https://user-images.githubusercontent.com/900690/171161156-3dfc3ac2-1592-458b-99a8-6b2356f57b53.gif)

**Comment by bpasero** [comment]
Yeah, running with `--verbose`:

```
[main 2022-05-31T11:23:19.172Z] Extension host with pid 80858 did not exit within 6000ms.
```

**Comment by deepak1556** [comment]
This is a side effect of how we gracefully shutdown the utility process, previously the extension host was responsible for shutting itself down and we block the main process exit based on it https://github.com/microsoft/vscode/blob/45818d7c31c73dafc08e9ef3dbbdba502f8c1879/src/vs/platform/extensions/electron-main/extensionHostStarter.ts#L60

Utility process lifetimes are controlled by the main process, (i-e) on graceful shutdown of the application the main process will first try to quit the main message loop and the applications have a chance to block this exit based on `will-quit`, `before-quit` event listeners and we use that today to provide chance to shutdown our services https://github.com/microsoft/vscode/blob/45818d7c31c73dafc08e9ef3dbbdba502f8c1879/src/vs/platform/lifecycle/electron-main/lifecycleMainService.ts#L243-L302 and once message loop is good to exit, the main process will cleanup C++ handles to the JS objects https://github.com/electron/electron/blob/16db5a112e3cde7d9ee8ea817f52bf2b9af7568f/shell/browser/electron_browser_main_parts.cc#L510-L530 and only during this phase I also shutdown the running utility processes gracefully which will emit the `exit` event, after that the node environments, child process and threads in the main process will get shutdown one after other eventually exiting the main process itself.

So what we are currently seeing is a chicken and egg problem, where the main message loop exit is blocked for 6s by the extension host exit, but the extension host exit is blocked on `exit` event from the main message loop.


Solution:

The runtime can only cleanup the utility process once the main message loop is ready to exit, if the exit is blocked on the application end it is not possible to know when to gracefully shutdown the process from the runtime side. Thoughts ?

**Comment by alexdima** [comment]
@deepak1556 The extension host processes should exit by themselves when the MessageChannel is closed. My intuition here is that the `exit` event might not be firing on the `UtilityProcess` instance, but I need to debug it to confirm.

**Comment by deepak1556** [comment]
Ah yeah, I currently don't emit the `exit` event when `MessageChannel` gets disconnected however the process does exit.
