### ISSUE TITLE
Deprecated extensions - consistent UI

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#150822]
Testing #150746

When I run a search for "deprecated" I see a large list of extensions that are being deprecated. I also see that each extension uses it's own ways to indicate that the extension is deprecated: 
- `[DEPRECATED]` prefix
- `[Deprecated]` prefix
- `(Deprecated)` sufix
- `(deprecated)` sufix

Given that we control the list of deprecated extensions, and we have several established UI elements I am wondering if we could create a more unified and consistent look for all the deprecated extensions:
- In the extensions list, add a visual indicator in the upper left hand corner of the icon (similar to pre-release)
- In the extension details page, have a "deprecated" pill/badge after the name (similar to the pre-release and preview)

**Comment by sandy081** [comment]
Another idea would be strike out the title just like we strike out in code editor.

**Comment by sandy081** [comment]
@misolori any suggestions?

**Comment by misolori** [comment]
I like the strike-through on the title idea, it's simple (even though we already use the warning icon):

<img width="1138" alt="CleanShot 2022-05-31 at 12 40 26@2x" src="https://user-images.githubusercontent.com/35271042/171271365-e3d6114b-4cf5-4b13-bc56-892f5f411084.png">

**Comment by isidorn** [comment]
looks nice :)
