### ISSUE TITLE
Code snippets and other suggestions stop working

### ISSUE THREAD

**Issue by BlueOrange775** [Microsoft/vscode#15094]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Sometimes on creating a new file, code snippets, and other suggestions refuse to work.

Steps to Reproduce:

1. Create new file within VSCode
2. Try to use code snippet, or anything to get suggestions up

**Comment by rebornix** [comment]
@BlueOrange775 can you provide a project or file that you are working which reproduces this problem?

**Comment by wUFr** [comment]
could be related to https://github.com/Microsoft/vscode/issues/15105

**Comment by BlueOrange775** [comment]
Issue is related to an extension, which has been fixed.
