### ISSUE TITLE
SCM Reveal in File Explorer not working in WSL

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#150998]
Testing #150716

* Open a git repository from WSL
* Modify files and save
* Go to SCM view, right click on a change
* Click on "Reveal in File Explorer"

Nothing happens

**Comment by lszomoru** [comment]
The latest Insiders has been updated, so that the new menu item does not appear when connected to a remote.

**Comment by rebornix** [comment]
<img width="307" alt="image" src="https://user-images.githubusercontent.com/876920/171699171-4f4e20c8-c00c-400d-8d3c-2d8f99c8d60a.png">

**Reveal in File Explorer** is gone 👍 . However **Open Containing Folder** is there and it does do anything either.
