### ISSUE TITLE
Mac: allow for more custom title bar styles

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15098]
On Mac OS, modern applications typically take over control of the title bar. Some examples:

**Skype for Business:**

![image](https://cloud.githubusercontent.com/assets/900690/20060897/a4fb35ae-a4fd-11e6-8f0c-5960a9e99d5f.png)

**Outlook:** 

![image](https://cloud.githubusercontent.com/assets/900690/20060909/aeec297e-a4fd-11e6-81ea-5ff7084690b4.png)

VS Code so far is not leveraging this and thus the title appears like this:

![image](https://cloud.githubusercontent.com/assets/900690/20060963/f6146f78-a4fd-11e6-83f9-2632c77097c3.png)

Proposed solution introduces a new setting `window.titleBarStyle` that allows to switch to a custom title bar (and potentially also to a inline style as discussed in https://github.com/Microsoft/vscode/pull/12628).

![image](https://cloud.githubusercontent.com/assets/900690/20060949/eded5dfa-a4fd-11e6-9a6a-936d32ae9e97.png)

![image](https://cloud.githubusercontent.com/assets/900690/20060944/e7fd1e94-a4fd-11e6-8acc-1ef154c5c531.png)

**Comment by smlombardi** [comment]
Will this setting be in Insiders build soon?

**Comment by bpasero** [comment]
@smlombardi tomorrow 👍

**Comment by bgashler1** [comment]
@bpasero this is great.  It's exactly what I was going to propose for a conservative first step.  Thanks!

**Comment by bpasero** [comment]
@bgashler1 great. I was about to ask if you have ideas for which coloring to use. I just picked the ones for dark, light and high contrast theme.

They live in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/titlebar/media/titlebarpart.css#L55

**Comment by jtlowe** [comment]
Could this feature be wrapped up in an extension instead? This could give more flexibility to customize the color of the titlebar.

**Comment by bpasero** [comment]
We are not planning to give extensions a way to put stuff there. The main reason is that this feature is not available on Linux and Windows at the moment.

**Comment by jtlowe** [comment]
OK. Then how about a more specific name for the settings property, so it is easily recognized as applying to mac only?

**Comment by bpasero** [comment]
@jtlowe the setting will not show up on Windows and Linux. And it will eventually be supported across all OS.

**Comment by smlombardi** [comment]
The app looks much nicer with this enabled, thanks for adding this.

**Comment by wprater** [comment]
Note that on macOS when "window.titleBarStyle": "custom" is set, the usual behavior allowing one to see the path tree (while holding down the command key and clicking) of the file in the titlebar is not preserved. I realize this is a "custom" titlebar, but it would still be nice to keep this behavior.

**Comment by smlombardi** [comment]
@wprater Perhaps an option to display the entire path in the title bar?  I've seen that option in other editors.

**Comment by bpasero** [comment]
@wprater good point, I guess one thing I could do is open a context menu upon Cmd+click that contains entries for the path segments to open in the finder. What I will not be able to do is to show icons though...

**Comment by bpasero** [comment]
<img width="446" alt="screen shot 2016-11-09 at 07 37 17" src="https://cloud.githubusercontent.com/assets/900690/20129383/814bdb4c-a64f-11e6-9bc2-8466df3b8ae8.png">

**Comment by bpasero** [comment]
Btw we do also have a new option to show the full path in the title bar: 

`"window.showFullPath": true`

**Comment by wprater** [comment]
I think users will appreciate that.  I've used it many times over the years to open a directory from the title bar.

**Comment by bpasero** [comment]
It should be in insiders now.

**Comment by bpasero** [comment]
Closing, this is done minus bugs.

**Comment by mikaoelitiana** [comment]
Great job!! I am loving it

**Comment by wprater** [comment]
> Closing, this is done minus bugs.

where is the bug list?  thought I recalled you spelling them out?  just wanted to track https://github.com/Microsoft/vscode/issues/15098#issuecomment-259274919

**Comment by bpasero** [comment]
@wprater but that one is fixed in current insider builds.

Outstanding bugs are two I can think of right now:
* on sierra it can lead to a native crash (https://github.com/Microsoft/vscode/issues/15154)
* when dev tools are opened and docked into the window you cannot move the window (https://github.com/electron/electron/issues/3647)
