### ISSUE TITLE
Valid Markdown link using HTML syntax is not recognized

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#150915]
Testing #149979

Our vscode-wiki repo has a header like so:

```md
# <a name="closing-with-a-commit"></a>Closing Issues "With a Commit"
```

This link is valid https://github.com/microsoft/vscode-wiki/blob/89908e15bbba882528cd0bdc906482cb7923d1a3/Automated-Issue-Triaging.md#closing-with-a-commit but references to it in the same document are reported as invalid: 
![image](https://user-images.githubusercontent.com/30305945/171287849-a52da5e6-6860-4807-9e3f-fea5c56f7f08.png)

**Comment by mjbvz** [comment]
This is a known limitation. It is difficult to correctly parse html embedded in markdown to extract ids/names and just does not seem worth the engineering effort. Instead we assume all links are to MD headers and allow other anchor links to be excluded from validation
