### ISSUE TITLE
Terminal find match border width

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#150926]
Testing #150554

The terminal find match border has a different width than in the editor. Not a big deal but if you're going for consistency, this stands out to me. I use the border because the default highlight doesn't stand out enough to me, and I don't use a blinking cursor.

terminal

<img width="161" alt="image" src="https://user-images.githubusercontent.com/323878/171296145-a610accb-76ea-46c5-86f2-47dcd1264262.png">

editor

<img width="86" alt="image" src="https://user-images.githubusercontent.com/323878/171296170-61b60393-810d-4880-beae-1592b0a2b58b.png">

**Comment by meganrogge** [comment]
I actually prefer the look of the one in the terminal. The editor border makes it look crowded IMO
