### ISSUE TITLE
Link headers which are not `-` delimited do not get markdown link validation

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#150919]
Testing #149979

When looking at this file with markdown link validation enabled: https://github.com/microsoft/vscode-wiki/blob/44f0caa54e7ad18ef3cbb056e9eb375569d20784/December-Pre-Release.md

`[[Submitting-Bugs-and-Suggestions]]` is flagged as invalid (this is actually valid on GitHub and ought to be ignored), but `[[December Test Plan]]` is not flagged as invalid.

![image](https://user-images.githubusercontent.com/30305945/171289324-8d252913-6aae-4fef-8fbe-88bea7df79cf.png)

**Comment by mjbvz** [comment]
I think this is expected. GitHub's wiki's supports MediaWiki style links (`[[link]]`) which are not part of standard markdown. Right now those won't render properly in the md preview or work well with any of our other MD features

If you're seeing a lot of issues related to them with diagnostics, can you please open a generic: "support mediawiki links" issue so we can track support?

**Comment by TylerLeonhardt-alt** [comment]
Extensions like [foam](https://marketplace.visualstudio.com/items?itemName=foam.foam-vscode) depend on this MediaWiki style link.
