### ISSUE TITLE
Reveal in Explorer View and Reveal in Finder options both show up on Mac

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#150902]
Testing #150716

Even with extensions disabled, there's still reveal in explorer view on Mac:
<img width="287" alt="Screenshot showing context menu with both Reveal in Explorer View and Reveal in Finder options" src="https://user-images.githubusercontent.com/7199958/171274458-1d572c3d-29b8-4f72-a50d-e9ac8599b102.png">

**Comment by gjsjohnmurray** [comment]
Surely they do two different things, don't they?

**Comment by rzhao271** [comment]
True. I confused it with the "Reveal in File Explorer" from the TPI.
