### ISSUE TITLE
Unexpected result when dragging multiple files into editor with shift down

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#150996]
Testing #150321

It adds both files, the first just the file name, the second the full path:

![image](https://user-images.githubusercontent.com/2193314/171464690-dd1a2fce-6acb-4e8d-b2b3-b0846d82f144.png)

**Comment by mjbvz** [comment]
What language file are you dropping these into? Is this using the extension sample from #150321?

**Comment by Tyriar** [comment]
That was into a .gitignore file, this is without the example sample

**Comment by rchiodo** [comment]
/verified? I can't repro on the stable version but it does generate the full path on both.

**Comment by Tyriar** [comment]
Works for me too now 👍
