### ISSUE TITLE
Markdown link diagnostics: File Links setting also affects header links to other files

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#150949]
Testing #149979

E.g., `[a link](sub/sub2.md#hello)` is affected by `markdown.experimental.validate.fileLinks.enabled`, but not `markdown.experimental.validate.headerLinks.enabled`. Not sure that's expected.

**Comment by mjbvz** [comment]
Yes this is expected currently but I may split up these settings to make this more clear
