### ISSUE TITLE
Command center border has low contrast

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#150907]
Testing #150396

I believe the border contrast needs to be 3:1 between the border and bg color of the title bar. Something like `--vscode-sideBarSectionHeader-border` might be a little closer to what we want:

## Before
<img width="489" alt="CleanShot 2022-05-31 at 13 02 15@2x" src="https://user-images.githubusercontent.com/35271042/171274848-1054ce03-2389-4718-a172-58dad4712c71.png">

## After
<img width="520" alt="CleanShot 2022-05-31 at 13 01 04@2x" src="https://user-images.githubusercontent.com/35271042/171274669-2495df2a-bac0-497f-a663-f26f52531f26.png">

**Comment by jrieken** [comment]
@misolori Your suggested colors falls back to `contrastBorder` which actually aren't defined for for light/dark themes, only for HC themes... I went with variants of the foreground-color. The contrast-ratio tool in devtools seems broken... @misolori Do you mind making more directly in this branch: https://github.com/microsoft/vscode/pull/151747
