### ISSUE TITLE
Can't multi-select in problems view in table mode.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#150977]
Testing #150750

Not sure if this lack of functionality blocks anything truly useful, but at least in the treeview, you can multi-select problems and copy them to the clipboard. In the table view you can't.

**Comment by greazer** [comment]
This also has the side effect of losing a multi-select that you may have had in the treeview.

**Comment by lszomoru** [comment]
@sandy081, what was the thinking for enabling multi-select in the problems treeview?
Was there a particular scenario or this is what the default behaviour is for a treeview? 
If there is a real scenario, than we should enable multi-select in the table as well.

**Comment by sandy081** [comment]
You can copy multiple problems is the primary use case.
