### ISSUE TITLE
Comments view should have ability to filter by resolved/unresolved

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/vscode#150958]
Issue Type: <b>Feature Request</b>

In the Comments window, I see tons of comments on my PR, but I find it difficult to focus on the ones that are still open. There is a minor visual difference (blue/grey icon), but I would much rather have an ability to choose what is displayed (all/resolved/unresolved)

Extension version: 0.42.0
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

**Comment by hermannloose** [comment]
Related: #142081 has some mocks for distinguishing unresolved comments better in the comments panel through icons and color. I believe at the moment, only the comment views in the code editor are colored differently?

#127476 might be interesting to look at for designing the implementation, as it asked for more generic "tagging" of comment threads by the extensions that create them. I know that right now we only have resolved vs unresolved in the API, but it might make sense to keep the filtering logic slightly more generic in anticipation of more facets to filter by in the future (e.g. "only comment threads I am involved in, regardless of resolvedness" etc.).

**Comment by alexr00** [comment]
This is what the Problems view does (I clicked on the filter icon):

![image](https://user-images.githubusercontent.com/38270282/180435152-7d604031-4c5a-4ee7-a60f-dab4c01df0c1.png)

Something like this will allow for https://github.com/microsoft/vscode/issues/127476 too. If we add a `tag` like property to comment threads later, then we can read incorporate that into the list and maybe even add a filter input box too. 

For now though, I will add something similar to the filter menu in problems with "Show Resolved" and "Show Unresolved" options.
