### ISSUE TITLE
Lost problems tableview header

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#150982]
Testing #150750

Not sure what I did to get into this state, but I lost the header for the table view. Toggling back and forth between treeview restored it.

![Recording 2022-06-01 at 08 36 39](https://user-images.githubusercontent.com/11685408/171443915-27b2ed6d-60f0-4885-941c-b6c6a8e306bb.gif)

**Comment by greazer** [comment]
In trying to repro, I had found that everytime I created a new text file, the header would disappear before my eyes. I resized my VS Code window to make a gif out of it, and suddenly that repro stopped reproing. :( So now I don't know what happened.

**Comment by lszomoru** [comment]
I am unable to repro this with the latest VS Code release.
