### ISSUE TITLE
Prefrences: Open Workspace Settings (JSON) generate the error file name "settings.json"

### ISSUE THREAD

**Issue by codenoy** [microsoft/vscode#150943]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.64
- OS Version: MacOS 12.3.1

Steps to Reproduce:

1.Open Workspace Settings (JSON) CMD
2.generate ./vscode/settings.json,  the file doesn't work exactly , the correct file should be 'setting.json'

**Comment by rzhao271** [comment]
Just to confirm, the file generated should be `.vscode/settings.json`. Also, here's an example settings file you can try out:
```json
{
	"workbench.colorCustomizations": {
		"editor.background": "#800080"
	}
}
```

If the editor background colour suddenly changes to a reddish violet, then the settings file is working. If this settings file works, but your current settings file doesn't, feel free to paste your current settings file.

**Comment by codenoy** [comment]
> Just to confirm, the file generated should be `.vscode/settings.json`. Also, here's an example settings file you can try out:
> 
> ```json
> {
> 	"workbench.colorCustomizations": {
> 		"editor.background": "#800080"
> 	}
> }
> ```
> 
> If the editor background colour suddenly changes to a reddish violet, then the settings file is working. If this settings file works, but your current settings file doesn't, feel free to paste your current settings file.

it works
and there is a 'setting.json' in '.vscode' folder 
I get confused with the 'setting.json' and the 'settings.json' file
it's my mistake😰
