### ISSUE TITLE
Git explorer welcome view improperly localized

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#150990]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Install pseudo language pack
2. Open explorer view in empty window
3. :bug: the Clone Repository command should not be localized here:

![image](https://user-images.githubusercontent.com/30305945/171456148-142238f0-7896-4249-9938-cfcaba114d52.png)

I think the way we deal with this is with a comment to skip localization like this: https://github.com/microsoft/vscode/blob/d00e0f9f74e69991955f5e203bd50f5ff39e6245/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L309

**Comment by TylerLeonhardt** [comment]
Yes, removing the buttons from the string to be translated is a good way to do this... though to be honest, that `comment` in the example you gave isn't needed anymore since `commmand` (with 3 m's lol) was removed from the string :)

**Comment by lszomoru** [comment]
As far as I can tell, this issue should have been fixed with https://github.com/microsoft/vscode/commit/59cdc58ea05a4e34b0ac42e11fd275e1e5bf98bf.
@TylerLeonhardt, am I missing something or should we just nudge the translation team to fix the translation? Thank you!

**Comment by TylerLeonhardt** [comment]
This is on me. The comments are being dropped for some reason. I will investigate.

**Comment by lszomoru** [comment]
Thank you very much @TylerLeonhardt. Let me know if I can help in any way.
