### ISSUE TITLE
"Open Folder" not translated in walkthrough

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#150908]
Testing https://github.com/microsoft/vscode/issues/150577 in Firefox, with Spanish (es-es) set

- Open "Get Started with VS Code in the Web" walkthrough
- Select last step (open up your code), then first command ("Open Folder" in English, "Abrir carpeta" in Spanish)
- Modal is in English:

![image](https://user-images.githubusercontent.com/25310137/171230898-5c301eda-ac26-4e4c-bced-2d07221ed523.png)

It isn't a new string, and I didn't think getting started or this command would be from an extension, but perhaps that is the case.

**Comment by dbaeumer** [comment]
@TylerLeonhardt

might be a bug in the tool so that the localize call is not detected. When you generate the export is the string included.

**Comment by TylerLeonhardt** [comment]
Ok the web strings are now bundled in language packs. It may take a minute for all these new strings to make their way through the translation system... but by end game it should be good.
