### ISSUE TITLE
RPM should not list bundled librares as "provides"

### ISSUE THREAD

**Issue by kurumushi** [microsoft/vscode#150934]
Does this issue occur when all extensions are disabled?: Yes/No
N/A

- VS Code Version: 1.67.2-1652812909
- OS Version: openSUSE Tumbleweed (rolling)

The generated rpm hosted at https://packages.microsoft.com/yumrepos/vscode/ sets various libraries to "provides" in the metadata. This makes the package manager assume that these libraries are installed system-wide, so the actual libraries will not be installed if another package depends on them.

For example, I installed plasma-systemsettings. This package depends on libvulkan.so.1. The package manager found the first package (code) that "provides" libvulkan.so.1. However, code does _not_ provide this package system-wide, it's just bundled with the app in /opt. So the package manager pulled in code as a dependency, without installing the actual libvulkan1 package, after that my apps refuse to run because they cannot find the libvulkan.so.1 library in any proper system location.

**Comment by rzhao271** [comment]
Confirmed this issue has been there since 1.63.2 and is not a regression. I don't see any provides field for https://github.com/microsoft/vscode/blob/main/build/gulpfile.vscode.linux.js#L180, though, so I'm not yet sure what's going on.
