### ISSUE TITLE
Ability to create simple macros

### ISSUE THREAD

**Issue by slowmove** [Microsoft/vscode#15091]
It would be nice to be able to create some kind of simple "macros" which initially could be only a set of commands running together on a specified keyboard shortcut.

Example: **F5 - Start Debug**
* View -> Debug
* View -> Debug Console
* Start Debugging

**Comment by rebornix** [comment]
Thanks @slowmove . It's dup of #4490

**Comment by geddski** [comment]
@slowmove here you go https://marketplace.visualstudio.com/items?itemName=geddski.macros

**Comment by slowmove** [comment]
Saw that one. Thank you @geddski, will test it out.

**Comment by geddski** [comment]
cool. Feedback welcome

**Comment by alexcoroza** [comment]
@geddski I installed your extension for vs code. What I want is when I pressed "alt+1", "console.log();" will be typed in editor. I have that custom macro in sublime and I dont know how to recreate that using this extension.

**Comment by geddski** [comment]
@alexcoroza first create a JS snippet, I have one for console.log:

```json
{
  "Print object to console": {
		"prefix": "con",
		"body": [
			"console.log('$1', $1);$0"
		],
		"description": "console.log an object"
	}
}
```

And then in your macro execute that snippet:

```json
"macros": {
  "log": [
    {"command": "type", "args": {"text": "con"}},
    "insertSnippet"
  ]
}
```

And finally add a keybinding to run your macro:
```json
{
       "key": "alt+f1",
       "command": "macros.log"
 },
```
