### ISSUE TITLE
Allow right-click to hide command center

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#150916]
Testing #150396

We do this on other areas on the title bar and would be great for when we turn this on by default.

<img width="269" alt="CleanShot 2022-05-31 at 14 38 07@2x" src="https://user-images.githubusercontent.com/35271042/171288737-2bc92214-4864-4c1c-b0e8-0a66662817f0.png">

**Comment by jrieken** [comment]
@misolori When selecting "Hide Layout Control", how do I get it back?

**Comment by misolori** [comment]
You **should** get it back by right-clicking anywhere in the title bar (just like our other views), but doesn't work like that right now:

<img width="305" alt="CleanShot 2022-06-07 at 07 26 55@2x" src="https://user-images.githubusercontent.com/35271042/172405687-62f1e095-e23c-42b3-b7b0-0511b3934b81.png">

Would be great to have a single menu for the layout control and command center

**Comment by yume-chan** [comment]
Chrome extends the native Windows title bar context menu. IMO it works well if it's also possible in Electron.

![image](https://user-images.githubusercontent.com/1330321/179141174-571ba7f8-6ab6-495d-b1b8-661cb39dd279.png)

**Comment by jrieken** [comment]
This is what I have in https://github.com/microsoft/vscode/pull/155276. It uses the free space to show a context menu to toggle the CC and layout controls. 

https://user-images.githubusercontent.com/1794099/179165943-5a1016a3-475d-46e9-846e-89d14ea363eb.mov
