### ISSUE TITLE
Apt/Yum repositories for Linux users

### ISSUE THREAD

**Issue by mallardtheduck** [Microsoft/vscode#15092]
VSCode is provided as .deb and .rpm packages for Linux users, but these are only provided as a stand-alone download, rather than from a repository.

Since VSCode updates often, having to manually download the new package and install it every time gets very old very fast. I notice that Windows users do get automatic updates which significantly improves the user experience.

It would be very much appreciated if VSCode updates were provided via repositories, rather than just as stand-alone downloads.

**Comment by rebornix** [comment]
Dup of #2973 and #229
