### ISSUE TITLE
Some text in integrated terminal is invisible

### ISSUE THREAD

**Issue by 8Observer8** [microsoft/vscode#150959]
- VS Code Version: 1.67.2
- OS Version: Win10
- Laptop: Asus K53SV

Temporary solution:

- File > References > Settings (or Ctrl + ,)
- Type: terminal.integrated.gpu
- Set one to off

![terminal integrated gpuAcceleration](https://user-images.githubusercontent.com/3908473/171389378-93e95cff-aac0-4b8f-8578-f72633cafc22.gif)

**Comment by 8Observer8** [comment]
> what happens with the canvas renderer?
![terminal integrated gpuAcceleration - canvas](https://user-images.githubusercontent.com/3908473/171515361-36345ec9-b3b9-4a8b-a456-0a4a102277a9.gif)

> can you always reproduce this?
Yes, I can.

I'm pretty sure this happens because my laptop has two graphics cards: an integrated one and a discrete one. If I run with a more powerful one, then the graphics acceleration works:

![discrete-card](https://user-images.githubusercontent.com/3908473/171516825-51bd6941-4d41-4732-b96d-c664ba60f07c.gif)

![image](https://user-images.githubusercontent.com/3908473/171516891-9c6bcfba-37a2-4f28-a0cf-937aa482a86a.png)

**Comment by 8Observer8** [comment]
But now the problem is gone and I don't know why. I changed to `auto` and `on`. I ran the editor several times, I launched the editor several times, as usual with the command: `code .`

**Comment by Tyriar** [comment]
@8Observer8 thanks a bunch for the info! This in particular looks telling to me:

> I'm pretty sure this happens because my laptop has two graphics cards: an integrated one and a discrete one. If I run with a more powerful one, then the graphics acceleration works:

I've seen the occasional report for this type of issue but have always been unable to reproduce. Since it seems to works with the canvas renderer it points further to the fact that this is probably an issue with graphics hardware/drivers and some incompatibility with webgl in Chromium.

I'm still not sure how we can handle this though, detecting missing glyphs like this doesn't seem possible without checking every pixel of each character/style combination that it's valid. This may be one of the unfortunately cases of just having to disable the webgl renderer.

When you have webgl enabled and reproduce, I don't suppose you have any warnings/exceptions in the devtools console? (Help > Toggle Developer Tools > Console). Could you also go to Help > Report Issue, expand the "Include my system information" section and copy and paste it? (CPUs, GPU Status, etc.)

**Comment by 8Observer8** [comment]
> I've seen the occasional report for this type of issue but have always been unable to reproduce.

 I think you should just set the default to canvas. Yes, most likely, these are some problems with the drivers on my laptop. I tried to enable graphics acceleration and run with a second video card, but the problem with the text remained.

> When you have webgl enabled and reproduce, I don't suppose you have any warnings/exceptions in the devtools console? (Help > Toggle Developer Tools > Console).

![image](https://user-images.githubusercontent.com/3908473/171701493-703c66d7-6a9f-486a-9bb9-b46275bd2909.png)

> Could you also go to Help > Report Issue, expand the "Include my system information" section and copy and paste it? (CPUs, GPU Status, etc.)

```
<html>
<body>
<!--StartFragment-->

CPUs | Intel(R) Core(TM) i3-2330M CPU @ 2.20GHz (4 x 2195)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: unavailable_off opengl: enabled_on rasterization: unavailable_off raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 7.91GB (2.84GB free)
Process Argv | . --crash-reporter-id ebcfe5a6-a8cc-4588-a1b0-f8215953097e
Screen Reader | no
VM | 0%

<!--EndFragment-->
</body>
</html>
```

**Comment by 8Observer8** [comment]
When run like this, graphics-accelerated text draws fine, but my laptop gets noisier:

![image](https://user-images.githubusercontent.com/3908473/171722486-c697a4d7-f2cc-4141-826a-bf356ff8387e.png)

**Comment by Tyriar** [comment]
It's likely some edge case in our triggered by our specific webgl program that is causing the issue. Electron in VS Code is also using an older version of Chromium than in Chrome.

@deepak1556 fyi the bit about default graphics card might be useful to you?

**Comment by 8Observer8** [comment]
I've been using VSCode for over 3 years but I haven't seen this issue before. I noticed it a few weeks ago.

**Comment by 8Observer8** [comment]
![canvas-does-not-work](https://user-images.githubusercontent.com/3908473/171813506-de5f320e-a05f-4cfe-8937-5b171aeaa62e.gif)

**Comment by 8Observer8** [comment]
Yes, `canvas` does not work too. This only works if you set the canvas in the current run. I will turn this option `off`.

![image](https://user-images.githubusercontent.com/3908473/171961705-3f8af8d1-97e8-4d65-a291-d197ac958002.png)

**Comment by ahmad-511** [comment]
Version: 1.68.0 (user setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

<html>
<body>


CPUs | Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2295)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: unavailable_off opengl: enabled_on rasterization: unavailable_off raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 7.92GB (3.33GB free)
Process Argv | --crash-reporter-id 22dc607f-04f6-47ff-8407-6d647161d9f5
Screen Reader | no
VM | 0%


</body>
</html>

Hello,
I have the same problem reported about 2 months ago  #147610
I also have integrated Intel Graphic 3000 and Nvidia Optimus GT 520MX
the issue always appears after waking up from sleep or hibernate while the terminal is left opened (and gpu acceleration is set to "on")

If we select the missing/crumbled text it appears correctly but once unselected the text return the first state
anyways, resizing the terminal height solves the problem, it seems like the terminal needs to be refreshed
![vscode-terminal-rendering-problem](https://user-images.githubusercontent.com/22330112/173286506-1800a59d-d9fd-46b3-bc55-6ee2a21bf976.gif)

also, toggling the gpu acceleration setting off and on will fix it too,

**Comment by 8Observer8** [comment]
>> the issue always appears after waking up
I think it's a different issue. I have this one too. I have read that this issue is related to Chromium and not related to VSCode. I solved it by changing PowerShell to CMD:

- Ctrl + Shift + P
- Type: terminal and select "Terminal: Select Default Profile"
![image](https://user-images.githubusercontent.com/3908473/173356240-fc57d377-ef90-4422-8c97-c8c57c9b7df4.png)
- Select "Command Prompt":
![image](https://user-images.githubusercontent.com/3908473/173356459-23f76bc0-6987-418d-8701-65e4475da556.png)

**Comment by ahmad-511** [comment]
> I solved it by changing PowerShell to CMD

Maybe it's a different issue, but I tried switching to PowerShell, CMD and Git Bash and still having the same exact issue,
It's related to gpu acceleration setting as when it turned off the problem disappears (at least in my case)

Regards

**Comment by Tyriar** [comment]
I believe this is already fixed (in https://github.com/xtermjs/xterm.js/pull/4181), can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.

**Comment by ahmad-511** [comment]
I installed the insider and I can confirm the issue is solved 👍
Thanks
