### ISSUE TITLE
Support undo and redo in input fields

### ISSUE THREAD

**Issue by heqian** [Microsoft/vscode#151]
How to reproduce the bug:
1. Open a text file;
2. Edit something in the file;
3. Use Cmd+F to activate the search box on the top right;
4. Type a keyword you want to search in the box;
5. Change the keyword in the box; (e.g., add a character to the keyword)
5. Use Cmd+Z to undo;
6. You will notice that Visual Studio Code actually undos the text file edit, not the search keyword edit.

**Comment by alexandrudima** [comment]
This might be a mac only issue, I cannot reproduce it under windows

**Comment by heqian** [comment]
@alexandrudima My bad... I forgot to mention my platform: Mac OS X 10.10.5 + Visual Studio Code 0.10.1 (df352367df2efcfa9d602d471e4e2f42140a0f05)

**Comment by brunolemos** [comment]
Same problem. 
VS Code v1.0
OS X El Capitan

**Comment by dawsonbotsford** [comment]
Any resolution here? Hopping back and forth between which issue tracks this and not finding a solution.
