### ISSUE TITLE
"editor: insert spaces" does not work

### ISSUE THREAD

**Issue by samiam95124** [microsoft/vscode#151065]
Does this issue occur when all extensions are disabled?: Yes/No [don't know. This is a fresh install, no extensions]

- VS Code Version: 1.67.2
- OS Version: Ubuntu 20.04 LTS

Steps to Reproduce:

1. Open code file (C).
2. Enable "editor: insert spaces".
3. Hit tab key both at start of line and after any other character.

Result: if tab is hit at start of line, tab is inserted, regardless of "insert spaces" setting. After other character (not first on line), spaces are inserted as expected (is this a feature???).

**Comment by alexdima** [comment]
When pressing <kbd>Tab</kbd>, the editor will insert the current configured value (tab or spaces) depending on the current opened file. The current configured value is rendered in the status bar:
* e.g. For indenting with tabs:
![image](https://user-images.githubusercontent.com/5047891/120157727-9b33a980-c1f3-11eb-8153-26a6f2ea3286.png)
* e.g. For indenting with spaces:
![image](https://user-images.githubusercontent.com/5047891/120157764-a4bd1180-c1f3-11eb-9d0b-d3c15a698807.png)


The indentation settings can be controlled by 3 options:
```js
// The number of spaces a tab is equal to. This setting is overridden based
// on the file contents when `editor.detectIndentation` is on.
"editor.tabSize": 4,
// Insert spaces when pressing `Tab`. This setting is overridden based on 
// the file contents when `editor.detectIndentation` is on.
"editor.insertSpaces": true,
// Controls whether `editor.tabSize#` and `#editor.insertSpaces` will be 
// automatically detected when a file is opened based on the file contents.
"editor.detectIndentation": true,
```

The indentation settings can also be controlled by extensions, so please make sure to disable all extensions before trying.

**Comment by samiam95124** [comment]
The status bar reads: Spaces 4

Taking sample edit program:

#include <stdio.h>

int main()

{<---- hit tab here results in spaces
<---- hit tab here results in a tab
    printf("Hello, world\n");

}

This was verified by using another editor, say gedit, to see what the inserted space/tab was.

**Comment by alexdima** [comment]
@samiam95124 You can try tweaking the settings `editor.stickyTabStops`  and `editor.useTabStops`:

<img width="1001" alt="image" src="https://user-images.githubusercontent.com/5047891/171733294-c4b7a766-66df-4673-b9f0-e1b123d9db51.png">

**Comment by samiam95124** [comment]
Thanks, "use tab stops" did the job.
