### ISSUE TITLE
Add better message for markdown reference document link

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151017]
Works well, I was a bit confused to see this tooltip with 'Execute command' though, is there a way to make that more context-specific?

![image](https://user-images.githubusercontent.com/30305945/171469681-87d068a5-fca4-418a-802c-a0a9d927838e.png)

_Originally posted by @joyceerhl in https://github.com/microsoft/vscode/issues/146293#issuecomment-1143948256_

**Comment by rchiodo** [comment]
I'm not sure it's working? I get the same results:

![image](https://user-images.githubusercontent.com/19672699/171698919-f4b7a74c-8d93-4159-818d-457da9dd8044.png)

**Comment by mjbvz** [comment]
Since that is a command link, I think `execute command` still makes sense (as clicking it will execute the command)

For paths and https links, I see `follow link`:

![Screen Shot 2022-06-02 at 4 42 11 PM](https://user-images.githubusercontent.com/12821956/171757759-a7eddf26-c934-49f7-91d3-a5e11faa2c75.png)
![Screen Shot 2022-06-02 at 4 42 02 PM](https://user-images.githubusercontent.com/12821956/171757832-761e94cf-ba0d-42aa-bee3-9fd7e70e7803.png)
