### ISSUE TITLE
Cursor movement when typing spaces

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#151057]
Issue Type: <b>Bug</b>

This happens with all extensions disabled:

1) open a new untitled text file (plain text)
2) type as show

See gif here: https://share.cleanshot.com/uooY1T

-> the cursor does not stay at the end of line and cannot be moved to the end of the line

VS Code version: Code - Insiders 1.68.0-insider (4589815e4849499c67125ff68563fa102646b869, 2022-06-01T05:16:42.814Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|--disable-extensions --enable-proposed-api lszomoru.lszomoru-proposed-api-sample --enable-proposed-api donjayamanne.kusto --crash-reporter-id ef10dfea-3602-4c74-ba1a-109ce7da7825|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yume-chan** [comment]
Maybe related to #150968, both only happen when render white space is on.

**Comment by alexdima** [comment]
To reproduce, use the following settings to turn on whitespace and disable monospace optimizations:
```
"editor.renderWhitespace": "all",
"editor.fontLigatures": true
```

https://github.com/microsoft/vscode/issues/150968 also fixes this one, but leaving this as a bug to get independently verified.

**Comment by meganrogge** [comment]
I can still reproduce the issue with the settings you describe above

**Comment by alexdima** [comment]
@meganrogge I don't think an insiders with his fix has went out yet, as the PR was merged just 8hrs ago.
