### ISSUE TITLE
Renaming files in WSL from vscode.dev is EXTREMELY slow

### ISSUE THREAD

**Issue by FossPrime** [microsoft/vscode#151025]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version:  Mozilla/5.0 (Windows NT 10.0; Win64; x64)

Steps to Reproduce:

1. Open a folder in vscode.dev stored in a WSL folder, such as $HOME/test
2. Create a file in that folder and rename it

# Expected:
Rename should occur instantly

# Actual
Rename takes a whole minute and causes sync issues where changes are not saved and notfound errors are generated.

**Comment by lramos15** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by FossPrime** [comment]
> Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues
> 
> Thanks!

I gave up on Windows partially because of my issues... So I can no longer reproduce.
