### ISSUE TITLE
Dots for breakpoints render in weird spots

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#151049]
Testing #150583

This is unrelated to the paste API, but happened while testing the paste API.

Version: 1.68.0-insider
Commit: 4589815e4849499c67125ff68563fa102646b869
Date: 2022-06-01T07:44:20.468Z
Electron: 17.4.6
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.4.0-100-generic

![image](https://user-images.githubusercontent.com/3840081/171517167-660fae59-a03d-4ac0-b4d2-aaadca64e8f1.png)

![image](https://user-images.githubusercontent.com/3840081/171517280-70c98794-35c8-42d5-8b64-bd0641d42230.png)

**Comment by connor4312** [comment]
This is generally related to either your source code being out of date or your tooling creating invalid sourcemaps. Are you able to share a reproducable example?

**Comment by karthiknadig** [comment]
I just followed what was there in https://github.com/microsoft/vscode/issues/150583. Created an extension using `yo code` (with webpack and npm as selections), then followed the `paste example` extension.

**Comment by connor4312** [comment]
I'm not able to repro that

<img width="939" alt="image" src="https://user-images.githubusercontent.com/2230985/172118136-f3bdfcc7-5b84-46f4-999f-ebab274bc0fa.png">

**Comment by karthiknadig** [comment]
I am not able to repo this either.
