### ISSUE TITLE
`provideDocumentPasteEdits` should allow returning normal edits.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#151047]
Testing #150583

Consider a scenario of using custom mime type. Here returning `undefined` does not insert the text. What is the recommended way here?
```
class CopyCountPasteEditProvider implements vscode.DocumentPasteEditProvider {
    prepareDocumentPaste?(
        document: vscode.TextDocument,
        range: vscode.Range,
        dataTransfer: vscode.DataTransfer,
        _token: vscode.CancellationToken
    ): void | Thenable<void> {
        const text = document.getText(range);
        dataTransfer.set('text/python', new vscode.DataTransferItem(text));
    }
    async provideDocumentPasteEdits(
        document: vscode.TextDocument,
        range: vscode.Range,
        dataTransfer: vscode.DataTransfer,
        token: vscode.CancellationToken
    ) {
        const textDataTransferItem = dataTransfer.get('text/python');
        if (!textDataTransferItem) {
            return undefined;
        }
        const text = await textDataTransferItem.asString();
        return undefined;
    }
}
```

**Comment by mjbvz** [comment]
For this use case, you should be able to modify `text/plain` in the copy event. It looks like this is currently not working though. Taking a look now

**Comment by karthiknadig** [comment]
@mjbvz Any reason why TextEdits are not supported?

**Comment by mjbvz** [comment]
I don't understand. Can you explain what you expect to happen?

**Comment by karthiknadig** [comment]
When I was testing this out, it only supported `SnippetTextEdit` for returns.  So, I was wondering why it can't be just plain `TextEdit` why `SnippetTextEdit`. I see that now it handles this via `DocumentPasteEdit`.

**Comment by mjbvz** [comment]
Ah ok. Thanks yes it should be easier to return plain text now using the latest version of the API
