### ISSUE TITLE
Setting value not accepted for `"terminal.integrated.defaultProfile.windows"` in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151042]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Set `"terminal.integrated.defaultProfile.windows"` to any string value in settings.json
2. :bug: gets flagged as an invalid value 
![image](https://user-images.githubusercontent.com/30305945/171510771-46bde4e3-51d4-4212-b894-e44e07884fc3.png)

This only happens in web (e.g. https://insiders.vscode.dev or a repo like https://insiders.vscode.dev/github/microsoft/vscode), on desktop the setting value is not flagged as invalid.

**Comment by Tyriar** [comment]
Working as originally designed, but we could check if it's serverless web and use `null | string` instead?

**Comment by meganrogge** [comment]
Doesn't reproduce for me anymore 

![image (22)](https://github.com/microsoft/vscode/assets/29464607/648305c8-c3ec-4f99-956c-06a8e04a8f40)
