### ISSUE TITLE
Next terminal is not focused when a shell process dies on its own (then terminalFocus doesn't act as expected)

### ISSUE THREAD

**Issue by kaiwood** [Microsoft/vscode#15103]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra 10.12.1 (16B2555)

Steps to Reproduce for "open":

1. Toggle terminal pane
2. Start a second terminal (via shortcut or click on '+')
3. Try using a set shortcut for workbench.action.terminal.focusNext / workbench.action.terminal.focusPrevious
4. At this point, the values of setting `terminal.integrated.commandsToSkipShell` get ignored, shortcuts don't work and the pressed key reaches the terminal
5. Toggling terminal pane twice to ensure that terminalFocus ist set and everything works as expected.

![terminal_1](https://cloud.githubusercontent.com/assets/7542/20062045/84328e30-a502-11e6-8f55-b7decee89ae9.gif)

Steps to Reproduces for "close":
1. Open a terminal pane with 2+ terminals
2. Close a terminal (by typing "exit" or "ctrl-d")
3. terminalFocus is is lost and shortcuts get send to the editor instead (shortcuts for switching terminals in the animated screenshot are set to the same as  next/previous tab)
4. Notice that the cursor in the terminal even shows that it has no focus - unlike in the first example, where the cursor stays the same!
5. Toggle terminal pane twice to make everything work again

![terminal_2](https://cloud.githubusercontent.com/assets/7542/20062271/6b05b03a-a503-11e6-8903-6cca7667bbec.gif)

PS: Yes, --disable-extensions was used ;)

**Comment by Tyriar** [comment]
Do you mean that running `exit` inside the terminal to close a terminal instance does not focus the next instance, unlike the other ways terminals are focused (bin button, focus, etc.)?

**Comment by kaiwood** [comment]
@Tyriar Correct. If I use the bin button everything works as expected, the previous terminal instance gets selected, I can type and the shortcuts work. When using either `exit` or `ctrl-d` (The escape character for EOF, not a shortcut set in VSCode) the focus gets completely lost - no typing and the focus is somewhere in the editor pane.

What I'm doing in the GIF',s is switching terminals with the following shortcut's:

    {
       "key": "cmd+alt+left",
       "command": "workbench.action.terminal.focusPrevious",
       "when": "terminalFocus"
    },
    {
       "key": "cmd+alt+right",
       "command": "workbench.action.terminal.focusNext",
       "when": "terminalFocus"
    }    

They are set to the same keys as switching tabs, so I can tell that the focus is somewhere in the editor pane, because it reacts to pressed shortcuts and switches tabs instead of terminal instances.

---

And in the first example I gave - when opening a new terminal instance - the focus is somewhat intact, I can at least type commands. But it looks like the values of `"terminal.integrated.commandsToSkipShell"` get ignored. If I press the shortcuts, they reach the terminal (First GIF, the red '1D1C1D1C") and `workbench.action.terminal.focusPrevious` never happens.

In both cases, as soon as I toggle the terminal pane twice, everything works as expected again.

**Comment by Tyriar** [comment]
Ah ok, I don't use `"when": "terminalFocus"` in my focus prev/next keybindings but I can see how that would be annoying now.

**Comment by arusakov** [comment]
I have the same problem:
VSCode: 1.7.1
Mac OS X: 10.12.1

```
{
   "key": "cmd+left",
   "command": "workbench.action.terminal.focusPrevious",
   "when": "terminalFocus"
},
{
   "key": "cmd+right",
   "command": "workbench.action.terminal.focusNext",
   "when": "terminalFocus"
} 
```
