### ISSUE TITLE
Question: Why can some deprecated extensions be installed and not others?

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#151005]
Testing #150746

Not an issue, more of a question: Why can some deprecated extensions be installed (`Install` button available), and some cannot (no `Install` button)?

**Comment by sandy081** [comment]
@isidorn transferring this to you to answer.

**Comment by isidorn** [comment]
@kimadeline hehe good question. It is a decision which we make every time we deprecate an extension.
If we are 100% sure the alternative extension covers all the functionality of the original extension then we do not allow the original extension to still be installed. If we are not sure, and some functionality might not be supported we still allow users to install. We definitely lean towards not allowing.

I will go ahead and close this issue, and if you have more questions feel free to reach out. 
Thanks for testing this feature.
