### ISSUE TITLE
VSCode is horribly slow to start on Windows 7 Enterprise 64-bit

### ISSUE THREAD

**Issue by biker-linz** [Microsoft/vscode#15108]
- VSCode Version: 1.7.1
- OS Version: Windows 7 Pro SP1 64-bit

Hi there. I love VS code. Ironically it runs great on my Mac but is agonizingly slow on Win7.
Start time is approximately 2 minutes. Opening a file is instantaneous, but opening a folder = 2 minutes again.
I have tried running code --disable-extensions. Still 2 minutes.

My user profiles file looks like this:
// Place your settings in this file to overwrite the default settings
{
    
    "update.channel": "none",
    "files.exclude": {
        "**/largeFolder": true
    }

}

Steps to Reproduce:
1. Start VS Code
2. Watch entire episode of Big Bang Theory
3. Start coding

**Comment by bpasero** [comment]
@biker-linz is this running inside a VM?

**Comment by biker-linz** [comment]
No, running native.

**Comment by bpasero** [comment]
@biker-linz interesting, so you say a cold start on a single file is instant but a cold start on a folder takes 2 minutes?

**Comment by biker-linz** [comment]
Not quite. A cold start is always 2-minutes. Once started, opening a folder causes VSC to hang for 2-minutes. But opening a file is instantaneous.

**Comment by bpasero** [comment]
@biker-linz when a folder is finally opened, can you try to trigger "Reload Window" from the command palette and see if again it takes 2 minutes to load? If so, this would allow us to do some profiling...

**Comment by biker-linz** [comment]
Reload window is also very very slow

**Comment by bpasero** [comment]
Ok that is GOOD because that means we can try to profile:

To create a CPU profile using developer tools in VS Code:
* select Help > Toggle Developer Tools
* click on Profiles
* click the start button
* do whatever you need to do to get the CPU spin high
* wait for some time (10-20 seconds should be enough)
* stop the profiling 
* click the save button and attach the output file to this issue

**Comment by bpasero** [comment]
Actually be warned that saving does not work. But if you get it maybe you could drill down to see where time is spend? if you are not familiar with profiling, I can give you some more guidance.

**Comment by biker-linz** [comment]
I am not familiar with profiling, but have attached some output that might help??
![profile_output](https://cloud.githubusercontent.com/assets/6288586/20074215/40ce3868-a527-11e6-8896-184dfb6f7e58.PNG)
![profile_output2](https://cloud.githubusercontent.com/assets/6288586/20074214/40cd665e-a527-11e6-94b7-746b596de17b.PNG)

Thanks for your help Ben, much appreciated.

**Comment by bpasero** [comment]
@biker-linz this is great, I think you nailed it with that screen shot. All of the time is spend spawning processes and we have many to spawn. In the sceenshot I can see:
* the file watcher
* the git service
* the crash reporter

Now I wonder why spawning processes is so slow on your system. Are you running any anti virus / security software on this system or is there any other protection mechanism active maybe?

**Comment by bpasero** [comment]
@biker-linz ping

**Comment by bpasero** [comment]
@biker-linz I recently added support to log more information around the startup, was wondering if you could give it a try:
* use our insiders build (http://code.visualstudio.com/Download#insiders)
* start it
* when done, F1 > Startup performance
* send me the output from the "Console" in developer tools

**Comment by biker-linz** [comment]
Hi Ben,
Sorry for the radio silence. Yes, we have lots of enterprise-grade security.
I tried running as admin to see if that might help, but no...
I'll try the new build.
Thanks for your help,
L.

**Comment by bpasero** [comment]
@biker-linz thanks!

**Comment by mattrat** [comment]
Did y'all come to a conclusion? I have been dealing with the same thing. I have loved VSC but stopped using it when I had to start using a Windows machine at work. 

I followed the same debugging steps and came to the same conclusion. After starting the profile, using the quick open (ironic), waiting a while, then stopping. There were multiple internal/child_process.js that took a while.

I assume from recent comments that the assumption is that an antivirus program is causing the spawn process to take longer than desired. I that true?

**Comment by bpasero** [comment]
@mattrat how many CPUs does that machine have?

**Comment by mattrat** [comment]
It has 2 cpus with 4 cores each

**Comment by xeonx1** [comment]
I agree that VSCode takes way to long too open, to make it a feasible alternative to Notepad++ for opening text and code files.
It takes 11+ seconds for a cold startup and 7-8 seconds for Reload Window after that with fast SSD and CPU (Intel® Core™ i7-6700HQ, PCIe® NVMe™ M.2 SSD exclusively, 16GB RAM, Win 10 x64) with all extensions disabled, even with vscode added excluded by Webroot and Anti-Malware.
As a workaround, it would be very helpful if could launch VSCode on Windows startup, minimized to tray, as proposed for #11723

**Comment by csholmq** [comment]
I reckon this can be closed in favor of https://github.com/Microsoft/vscode/issues/15455.

**Comment by bpasero** [comment]
I am closing this and ask people that hit slow performance to run `code-insiders --prof-startup` (from our insiders build) which now supports to run CPU profiles so that we can have a closer look. Running with this argument will guide you through the process of creating a performance report here.
