### ISSUE TITLE
--jsx flag in .tsx files, weird behavior

### ISSUE THREAD

**Issue by huttarichard** [Microsoft/vscode#15109]
- VSCode Version: 1.7.1 (1.7.1) / 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
- OS Version: OSX 10.11.6

Guys I just update vscode and someting very weird is going on. Before works alright.

`tsconfig.json`
```javascript
{
    "compilerOptions": {
        "outDir": "./public/",
        "sourceMap": true,
        "noImplicitAny": false,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react"
    },
    "files": [
        "./typings/custom/sass.d.ts",
        "./client/index.tsx"
    ]
}
```

this is a first file indicating that --jsx flag missing which is not true. 

`routes.tsx`:
<img width="598" alt="screen shot 2016-11-07 at 16 54 32" src="https://cloud.githubusercontent.com/assets/1809268/20064520/59249c16-a50b-11e6-9f10-da4ef4f3e2e2.png">

second file in same directory:

`index.tsx`:
<img width="467" alt="screen shot 2016-11-07 at 16 55 32" src="https://cloud.githubusercontent.com/assets/1809268/20064521/592cbdc4-a50b-11e6-9dba-f36efac0bd36.png">

this file is ok with jsx syntax.

**Comment by huttarichard** [comment]
Im just fooling around with golang and react, so can share repository if you want to try reproducing issue.

**Comment by waderyan** [comment]
@huttarichard thanks for opening this. Yes if you can share your repo that would be great.

**Comment by huttarichard** [comment]
@waderyan https://github.com/huttarichard/fooling-around

**Comment by huttarichard** [comment]
Ok I just figure this out.... It is because the file `routes.tsx` wasn't in tsconfig.json files property. what a fool I am...
