### ISSUE TITLE
Extensions Not Working Behind Corporate Proxy

### ISSUE THREAD

**Issue by thomashoggard** [Microsoft/vscode#15101]
- VSCode Version: 1.6.1
- OS Version: Windows 7 (6.1.7601)

Steps to Reproduce:

1.  Open VSCode
2.  Click on the extensions button on the left hand pane.
3.  I receive the below error in the developer console.

```js
messageService.ts:128 Cannot read property 'call' of undefined: TypeError: Cannot read property 'call' of undefined,    at 
e.onCommonRequest (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:6:21919),    at 
e.onMessage (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:6:21756),    at 
c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:6:21549,    at e.invoke (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:4:26230),    at 
e.fire (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:5:4113),    at 
c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:6:25696,    at e.invoke (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:4:26230),    
at e.fire (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:5:4113),    at 
Socket.i (c:\program files (x86)\microsoft vs code\resources\app\out\vs\code\node\sharedProcessMain.js:6:11865),    at 
emitOne `(events.js:96:13)`
```

Here is my settings.json.  As you can see I configure the proxy so all should work.
```javascript
{
    "http.proxy": "http://oproxy.example.com:8080",
    "https.proxy": "http://oproxy.example.com:8080",
    "http.proxyStrictSSL": false
}
```

**Comment by joaomoreno** [comment]
Does it reproduce after restarting?

**Comment by thomashoggard** [comment]
After restarting the issue is still present.  I should mention I also tried setting the environmental variables fro the proxy and had the same problem.

**Comment by joaomoreno** [comment]
Sorry, I should've been clearer: I meant restarting your machine. This appears to be an issue in which a dangling process is still around. Alternatively, search for any Code.exe processes laying around and kill them. Let me know if that fixes it.

**Comment by thomashoggard** [comment]
I tried both restarting the machine and the application.  I confirmed that no Code.exe processes were running.  

I noticed that the update functionality in VSCode is working.  It prompted me that a new version was available.  I updated to version 1.7.1 and now the extension list is displayed.  However, when I click the Install button for ESLint, vccode-icons, etc... I get a new exception.

```js

```

**Comment by joaomoreno** [comment]
OK, it seems your issue was fixed by 1.7.

The socket hang up is strange, and indicates towards your system or firewall blocking outgoing connections.

**Comment by rafael-azevedo** [comment]
- VSCode Version: 1.6.1
- OS Version: OS X El Capitan


Issues:
- socket hang up message when opening vscode
- When I select "Check for updates" it says no new updates are found. 

Steps to Reproduce:

- Open VSCode


**Dev Console output when first opening**

```
socket hang up: Error: socket hang up      //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:93 
    at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
    at TLSSocket.g (events.js:286:16)
    at emitNone (events.js:91:20)
    at TLSSocket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    e.doShow @ //Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:93
```

**settings.json** 

```
{ 
    //"files.autoSave": "afterDelay",
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.formatOnSave": true,
    "go.buildFlags": ["-i"],
    "go.formatTool": "goreturns",
    "go.lintTool": "gometalinter",
    "go.gopath": "/Users/azera001/.go",
    "go.gocodeAutoBuild": true,
    "telemetry.enableTelemetry": false
}
```

**Comment by joaomoreno** [comment]
@rafael-azevedo Are you behind a proxy? If so, you need the `http.proxy` setting.

**Comment by rafael-azevedo** [comment]
@joaomoreno I am in a corporate office , but this traffic shouldn't be going through any proxies.

**Comment by joaomoreno** [comment]
Can you try our latest [Insiders release](http://code.visualstudio.com/insiders)?

**Comment by rafael-azevedo** [comment]
I attempted to download twice to make sure there was no corruption , but I get the following error 

"The application "Visual Studio Code -Insiders.app" can't be open

**Comment by rafael-azevedo** [comment]
Here is the message in console when attempting to open the app 

```

12/13/16 12:24:06.285 PM	com.apple.xpc.launchd[1]	(com.apple.xpc.launchd.oneshot.0x1000002a.Electron[7007]) Could not find and/or execute program specified by service: 13: Permission denied: /Users/azera001/Downloads/Visual Studio Code - Insiders.app/Contents/MacOS/Electron
12/13/16 12:24:06.285 PM	Finder[464]	spawn_via_launchd() failed, errno=111 label=[0x0-0xac0ac].com.microsoft.VSCodeInsiders path=/Users/azera001/Downloads/Visual Studio Code - Insiders.app/Contents/MacOS/Electron flags=1 : LaunchApplicationClient.cp #963 LaunchApplicationWithSpawnViaLaunchD() q=com.apple.root.default-qos
12/13/16 12:24:06.285 PM	Finder[464]	spawn_via_launchd() failed, errno=111 label=[0x0-0xac0ac].com.microsoft.VSCodeInsiders path=/Users/azera001/Downloads/Visual Studio Code - Insiders.app/Contents/MacOS/Electron flags=1

```

**Comment by rafael-azevedo** [comment]
It seems in the insiders preview the file "Visual Studio Code - Insiders.app/Contents/MacOS/Electron" does not have permissions set correctly. It is showing up as a text file and not an executable.

**Comment by joaomoreno** [comment]
What are you using to extract it?

**Comment by rafael-azevedo** [comment]
@joaomoreno Okay so I figured out what is going on with the socket hang up. Our corporate network was blocking https://marketplace.visualstudio.com/VSCode. As far as installing the insiders edition I did extract it using the default unarchiver. Also I get the same error on version 1.7 trying a clean install .

**Comment by rafael-azevedo** [comment]
@joaomoreno Just verified and I am having the same issue running the the 1.7 and the insider edition on another mac on a different network.

**Comment by joaomoreno** [comment]
This is very strange, since no one else seems to have that problem. I certainly seem to download it and extract it without problems. 

Try this link: https://az764295.vo.msecnd.net/insider/2abfc207828739bd5b10d0bb8dbfea13506cfc69/VSCode-darwin-insider.zip

Can you compute its MD5 hash so we compare?

**Comment by rafael-azevedo** [comment]
@joaomoreno It seems that it was something in the download. I realized the second computer was connected to my corporate network via vpn after removing both from the corporate network, I uninstalled , redownloaded and was able to open up both 1.7 and the insiders edition. 

Do you know what domains are required to be accessible for vscode to function properly I can verify with our firewall teams to make sure we stop blocking this tools for our devs.

**Comment by pcameron-** [comment]
I am getting a similar issue. VS Code version 1.8 or 1.7. Anytime I try to install or update an extension, I see this error in the console:

messageService.ts:126socket hang up: Error: socket hang up,    at TLSSocket.onHangUp (_tls_wrap.js:1092:19),    at TLSSocket.g (events.js:286:16),    at emitNone (events.js:91:20),    at TLSSocket.emit (events.js:185:7),    at endReadableNT (_stream_readable.js:974:12),    at _combinedTickCallback (internal/process/next_tick.js:74:11),    at process._tickCallback (internal/process/next_tick.js:98:9)

I am on a corporate network as well but I can access [https://marketplace.visualstudio.com/VSCode](https://marketplace.visualstudio.com/VSCode)

**Comment by pcameron-** [comment]
Figured out the issue. My corporate network was blocking vsassets.io

**Comment by thomashoggard** [comment]
I haven't had time to follow up with my original issue.  But it seems to have been "magically" resolved now.   I haven't touched VS Code in some time opting out for Sublime.  But today I decided to update VS Code to the latest version and it appears the issue has been resolved.  Not sure if this was resolved by a code change or an internal corporate proxy change.
