### ISSUE TITLE
Opening a new folder extension cannot be used

### ISSUE THREAD

**Issue by Z-Yun-H** [microsoft/vscode#151099]
Issue Type: <b>Bug</b>

It is not clear whether there is a computer problem or an editor problem. The editor cannot use the extension when opening a new folder. Sometimes you need to save and exit and reopen VsCode to use the extension

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (2.02GB free)|
|Process Argv|--crash-reporter-id 71c9509e-0738-46ca-9301-b1de6043057a|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
browse-lite|ant|0.3.0
file-nesting|ant|1.0.0
icons-carbon|ant|0.2.4
smart-clicks|ant|0.0.13
vite|ant|0.2.5
cssrem|cip|3.0.0
bracket-pair-colorizer-2|Coe|0.2.4
vscode-mysql-client2|cwe|5.3.7
vscode-html-css|ecm|1.12.2
prettier-vscode|esb|9.5.0
code-runner|for|0.11.7
codespaces|Git|1.8.1
copilot|Git|1.25.6056
google-translate|han|1.2.6
mysql-syntax|jak|1.3.1
vscode-gutter-preview|kis|0.30.0
px2vw|liu|1.4.3
dotenv|mik|1.0.1
mongodb-vscode|mon|0.9.3
vscode-language-pack-zh-hans|MS-|1.67.3
vscode-edge-devtools|ms-|2.0.0
python|ms-|2022.6.3
vscode-pylance|ms-|2022.6.0
jupyter|ms-|2022.5.1001311010
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-wsl|ms-|0.66.3
java|red|1.7.0
win-opacity|ska|1.1.5
html-to-css-autocompletion|sol|1.1.2
easysass|spo|0.0.6
open-in-browser|tec|2.0.0
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.41.0
vscode-java-dependency|vsc|0.19.1
vscode-maven|vsc|0.35.2
vscode-icons|vsc|11.12.0
volar|Vue|0.35.2
five-server|yan|0.1.5
material-theme|zhu|3.13.29

(2 theme extensions excluded)

</details>

**Comment by joaomoreno** [comment]
I'm unsure I understand the problem here. What do you mean by "folder extension"? The screenshots also don't make it very clear.

**Comment by Z-Yun-H** [comment]
![image](https://user-images.githubusercontent.com/88868011/172034313-40c9604c-a9c1-41e6-a5a1-2eb1ccc655cd.png)

**Comment by Z-Yun-H** [comment]
![image](https://user-images.githubusercontent.com/88868011/172034341-3a0f3071-5780-451e-8b62-cb02f7d30211.png)

**Comment by joaomoreno** [comment]
I'm sorry. I don't understand what the problem is. Please read our guide about [Submitting Bugs and Suggestions](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).
