### ISSUE TITLE
Show warning when trying to type in readonly merge editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151035]
Testing #150389

1. Open merge editor
2. Try typing in the top two editors

**Bug**
Nothing happens, which is expected but there is also no message about why nothing is happening

Instead we should show a message to the user though similar to what happens when you type in the wrong side of our existing diff editors:

![Screen Shot 2022-06-01 at 2 42 18 PM](https://user-images.githubusercontent.com/12821956/171506972-ae20fce4-930a-40bb-a3a4-d4e0e6acfcdd.png)

**Comment by jrieken** [comment]
@hediet pretty sure that this is also an editor contribution that's disabled (atm)

**Comment by bpasero** [comment]
Seems to be enabled now 👍

**Comment by jrieken** [comment]
Yeah, that happened with enabled all editor contribs again

/duplicate of https://github.com/microsoft/vscode/issues/150868
