### ISSUE TITLE
Renaming symbol is broken

### ISSUE THREAD

**Issue by acetrand** [Microsoft/vscode#15107]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|typings-installer|benjaminromano|0.2.0|
|jshint|dbaeumer|0.10.15|
|vscode-instant-markdown|dbankier|0.1.0|
|vscode-jasmine-es5|deerawan|1.0.1|
|Angular1|johnpapa|0.1.16|
|fuzzy-definitions|jrieken|0.0.3|
|csharp|ms-vscode|1.4.1|
|Theme-1337|ms-vscode|0.1.2|
|debugger-for-chrome|msjsdiag|2.2.0|
|todotasks|sandy081|0.4.0|
|vscode-open-in-github|sysoev|1.2.1|

---

Steps to Reproduce:

1. Open up a js file (in my case a file called `projectConnections.js`)
2. Right-click a variable and select Rename Symbol
3. Type something, click enter

Expected result:
The variable is changed in the same window/file where I did the change

Actual result:
A new file is opened containing the change. The filename of the new file is all in lowercase (`projectconnections.js`)

See clip here: http://recordit.co/kqkWTjicWU

**Comment by waderyan** [comment]
@acetrand thanks for opening this. I can't recreate on my own machine. Can you share your repo with me?

**Comment by acetrand** [comment]
I tried checking out my repo in another folder and now the issue seems to have resolved.

Perhaps it was something with file permissions that was incorrect. I tried to see if there were some obvious problems with permissions but couldn't find any. I also tried starting Code as administrator but that didn't help either.

Anyway, I can't recreate this issue anymore so from my side we can close this now.

**Comment by ffaubry** [comment]
I have this issue on my Mac, 10.12.1.
Go F2, try to rename the symbol and get an info bar 'No Result'.
My code is ES6.

**Comment by keawade** [comment]
I'm currently experiencing this issue when attempting to use Rename Symbol. It sometimes also occurs when copying text in vscode.

I tried @acetrand's solution by deleting my project files and recloning but it didn't resolve the issue.

**Comment by ratiotile** [comment]
This sometimes happens to me, and (ctrl+shift p) > Reload Window  is enough to fix it.
OS: Debian 8 Jessie
Version 1.10.2
Commit 8076a19fdcab7e1fc1707952d652f0bb6c6db331
Date 2017-03-08T14:00:46.854Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

**Comment by ylg** [comment]
Thanks @ratiotile, I've run into this issue more than a few times and the Reload Window command does work a treat for my cases.

**Comment by keawade** [comment]
I've recently resolved the issues I had. The issue for me was due to some weirdness between the case sensitivity of the Windows file system and Git.

I had somehow ended up with two copies of a parent folder in Git with the only difference being capitalization (eg: `Test/` and `test/`). Windows didn't see the difference and VSCode didn't see the difference when displaying the folder tree but I could see it I used the `Ctrl+P` action to search by file name.

However, when I attempted to use Rename Symbol in `Test/file.ts`, and sometimes other actions beyond manually editing the text, VSCode would open the other folder path, `test/file.ts`, with the edits being made in that file path rather than the one I had originally open.

I was able to resolve the issue by using the file explorer to copy all the files in the messed up folder to a temporary location, deleting the messed up folder, committing the changes to Git, recreating the folder with the correct name, copying the contents back in, and finally committing the changes to Git again.

I'm not certain if Git is actually part of the cause but it did make fixing the issue a bit more complicated. I suspect the initial folder corruption may have been caused by creating/renaming those folders through VSCode while my webpack dev server was running on those files.

**Comment by andyfriesen** [comment]
I'm running into this bug as well.  I'm running VS Code on OSX.

Turning on verbose logging reveals this from the editor:

```
Info 37   request: {"seq":7,"type":"request","command":"rename","arguments":{"file":"/Users/andy/src/path/to/MyDocument.tsx","line":179,"offset":10,"findInStrings":false,"findInComments":false}}
Perf 38   7::rename: elapsed time (in milliseconds) 4.5909
Info 39   response: {"seq":0,"type":"response","command":"rename","request_seq":7,"success":true,"body":{"info":{"canRename":true,"kind":"parameter","displayName":"idx","fullDisplayName":"idx","kindModifiers":"","triggerSpan":{"start":5324,"length":3}},"locs":[{"file":"/users/andy/src/path/to/MyDocument.tsx","locs":[{"start":{"line":199,"offset":14},"end":{"line":199,"offset":17}},{"start":{"line":198,"offset":37},"end":{"line":198,"offset":40}},{"start":{"line":186,"offset":13},"end":{"line":186,"offset":16}},{"start":{"line":180,"offset":7},"end":{"line":180,"offset":10}},{"start":{"line":179,"offset":9},"end":{"line":179,"offset":12}},{"start":{"line":174,"offset":28},"end":{"line":174,"offset":31}}]}]}}
```

For some reason, the language service is mangling the filename and coming back with `/users` in response to a request to rename a file in `/Users`.  VS Code then interprets this as a distinct file to be opened.

My best guess is that it's this function in core.ts

```typescript
    export function createGetCanonicalFileName(useCaseSensitiveFileNames: boolean): (fileName: string) => string {
        return useCaseSensitiveFileNames
            ? ((fileName) => fileName)
            : ((fileName) => fileName.toLowerCase());
    }
```

Case sensitivity is sensed in this function in sys.ts

```typescript
            function isFileSystemCaseSensitive(): boolean {
                // win32\win64 are case insensitive platforms
                if (platform === "win32" || platform === "win64") {
                    return false;
                }
                // convert current file name to upper case / lower case and check if file exists
                // (guards against cases when name is already all uppercase or lowercase)
                return !fileExists(__filename.toUpperCase()) || !fileExists(__filename.toLowerCase());
            }
```

Changing this function to report `true` on OSX as well as Linux causes the problem to disappear.  I'm not sure what other effects this would have, but the tests all seem to pass.

**Comment by hallids** [comment]
Can this issue be reopened? Several people, including myself, are still having this problem.

**Comment by ashish-amarnath** [comment]
I constantly experience this ~80% of the time. There are two modes of failure that I see:

1. Attempt to rename fails straight off and displays a banner on top indicating that the rename fails
2. Attempt to rename runs without showing an error banner, but the rename operation did not do what is expected. 

I am running vs code on mac and my code is in golang.
Please reopen and fix this issue.
<img width="1183" alt="screen shot 2017-09-17 at 9 51 30 am" src="https://user-images.githubusercontent.com/22872138/30523024-84dc56c6-9b8e-11e7-976f-e8e24e9b54d6.png">
