### ISSUE TITLE
Purpose of alwaysCommit?

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#151054]
Testing #150723

What is the value of having `alwaysCommit` when I have branch protection enabled? It's the behavior the same as if I'd have branch protection disabled?

<img width="972" alt="image" src="https://user-images.githubusercontent.com/4674940/171524385-335b95dd-2b25-45aa-9f15-028dd071580f.png">

**Comment by joaomoreno** [comment]
Yeah, I thought the same today. Let's just remove this option.

**Comment by lszomoru** [comment]
I will keep this options around and I will keep an eye out for similar feedback.
