### ISSUE TITLE
GraphQL Language Server crashed 5 times (Utility Process)

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#151015]
Testing #150753

I just happened to have the [Graph QL](https://marketplace.visualstudio.com/items?itemName=GraphQL.vscode-graphql) extension installed and got this notification while testing.

<img width="344" alt="image" src="https://user-images.githubusercontent.com/6561887/171475520-0e6de095-4d54-46f8-8c08-15b9e37447ea.png">

**Comment by deepak1556** [comment]
I am unable to repro the crash so far, if you are able to repro it consistently can you check for crash reports following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports
