### ISSUE TITLE
Cannot uninstall a deprecated extension from the editor viewlet

### ISSUE THREAD

**Issue by kimadeline** [microsoft/vscode#151013]
Testing #150746

1. Look for deprecated extensions by typing `deprecated` in the extensions search menu
2. Install `tyriar.terminal-tabs` or `glen-84.sass-lint` via the extensions viewlet button
3. Note that there is no `Uninstall` button afterwards, you have to open the extension page and click `Uninstall` from there.

**Comment by sandy081** [comment]
Uninstall action is available in the drop down when you click the gear icon

![image](https://user-images.githubusercontent.com/10746682/171570809-765fa4eb-4fe4-4dc4-8f2b-75ab211d6d1c.png)
