### ISSUE TITLE
Save file slowdown and intellisense not working

### ISSUE THREAD

**Issue by discomarra** [Microsoft/vscode#15105]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.0.8|
|beautify|HookyQR|0.5.4|
|debugger-for-chrome|msjsdiag|2.2.1|
|vscode-icons|robertohuertasm|4.0.0|
|html-css-class-completion|Zignd|1.0.3|

---
Today I noticed a lag (>2s) when saving a JS file and intellisense is not working in JS files.
Steps to Reproduce:

1. Open VSCode
2. Create a new JS file
3. Type custom JS code
4. Try ctrl + space 
5. Save a file
![intelisense](https://cloud.githubusercontent.com/assets/4774424/20063211/a4912e6c-a506-11e6-9f05-f33d37419d9d.PNG)

**Comment by wUFr** [comment]
yup, can confirm.... at least it will actually save files now, older versions would just freeze whole editor if you have big CSS/Less files :)

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by wUFr** [comment]
ok strange, i started editor with `code --disable-extensions` from cmd, it fixed it... but now it works even with extensions enabled

probably caused by something else i guess

**Comment by wUFr** [comment]
Ok i think i got it...will stop working after saving big CSS file (tested with 7K lines CSS)

probably related to my issue, files can be actually saved in this version tho: https://github.com/Microsoft/vscode/issues/13997

**Comment by discomarra** [comment]
@bpasero after running vscode without extensions the issue is gone, but unlike in @wUFr's case, running it again with extensions doesn't fix the issue.
I proceeded with turning off each extension and I found the culprit (in my case at least):  "HTML CSS Class Completion". When this one is turned off, everything works fine.

I will report this issue to the extension's repo.

Thanks for your help.

**Comment by aeschli** [comment]
@wUFr Please reopen #13997 if you still have issues with large CSS files.
