### ISSUE TITLE
TreeDataProvider: iconPath is ignored for items with resourceUri

### ISSUE THREAD

**Issue by kryops** [microsoft/vscode#151087]
- VS Code Version: 1.67.2 and Insiders 15253f1528573fc8f84e956b21af4bad57f38c07 (2022-06-02T05:16:30.515Z)
- OS Version: macOS 12.4

Steps to Reproduce:

```ts
class MyTreeViewProvider implements vscode.TreeDataProvider<vscode.Uri> {
  async getChildren(element?: vscode.Uri): Promise<vscode.Uri[]> {
    return element ? [] : [vscode.Uri.file('/foo/bar')];
  }

  getTreeItem(element: vscode.Uri): vscode.TreeItem {
    return {
      id: element.toString(),
      resourceUri: element,
      label: element.toString(),
      iconPath: new vscode.ThemeIcon('package'),
    };
  }
}
```

Expected:
![image](https://user-images.githubusercontent.com/1042594/171622098-cca1b119-6f5b-4726-b10f-5e9e7e254a2f.png)

Actual:
![image](https://user-images.githubusercontent.com/1042594/171622013-f6b8d770-4c29-4b3c-a248-dedd90946661.png)

This started happening in 1.67.0. The most likely candidate I found while searching for the cause is https://github.com/microsoft/vscode/issues/146479 / https://github.com/microsoft/vscode/commit/d79928be53a807a9bff45814b6dab65bae685879 (CC @alexr00)

Is this a bug or an intended effect of the above change? I need to set the `resourceUri` to be able to apply decorations, but I want to use custom icons. Is there a different way to achieve this?

Related: https://github.com/microsoft/vscode/issues/150610

Thanks for looking into it!

**Comment by alexr00** [comment]
This is a bug. If you set an iconPath then that should always take precedence.

**Comment by sdedic** [comment]
Joining the issue. This affects [Apache NetBeans Language Server Extension for VS Code](https://marketplace.visualstudio.com/items?itemName=ASF.apache-netbeans-java) -- we often mark especially folders with icons according to their semantics, e.g. role in a project.

The behaviour broke in vscode 1.67; see [NETBEANS-4113](https://github.com/apache/netbeans/issues/4113)

**Comment by alexr00** [comment]
Fix went too far in the other direction. Now we're not using file icons for files in extension trees:

![image](https://user-images.githubusercontent.com/38270282/171832969-c0f798aa-196f-4a7f-b3e2-e89d657f2a01.png)
