### ISSUE TITLE
build flag new and cross build status

### ISSUE THREAD

**Issue by TomTravis** [microsoft/vscode#151030]
update the build docs and shell / scripts for the current software 
this are the items

1. git clone ...microsoft/vscode 
2. cd vscode
3. yarn
4. yarn watch
the command need to be updated
yarn does not take vscode (arg) via cli
the ./script/npm.sh does take (arg) -flag
yarn -arm64 fails
./script/npm.sh -arm64 works it is now building
this flag -arm64 is critical for the build CPU and OS
ARM 64 is now building 
the yarn gulp task are ;
Gulp tasks
vscode-reh-linux-armhf-ci, vscode-reh-linux-armhf-min, vscode-reh-linux-arm64-ci, vscode-reh-linux-arm64, vscode-reh-linux-arm64-min-ci, vscode-reh-linux-arm64-min, vscode-reh-web-linux-arm64-min, vscode-win32-arm64-ci, vscode-win32-arm64, vscode-win32-arm64-min-ci, vscode-win32-arm64-min, vscode-linux-x64-ci, vscode-linux-x64-min, vscode-linux-armhf-ci, vscode-linux-armhf, vscode-linux-armhf-min-ci, vscode-linux-armhf-min, vscode-linux-arm64-ci, vscode-linux-arm64, vscode-linux-arm64-min-ci, vscode-linux-arm64-min, vscode-linux-x64-build-deb, vscode-linux-armhf-build-deb, vscode-linux-armhf-build-rpm, vscode-linux-arm64-build-deb, vscode-linux-arm64-build-rpm, vscode-linux-arm64-prepare-snap, vscode-linux-arm64-build-snap
attached is my writeup

[vscode.txt](https://github.com/microsoft/vscode/files/8818720/vscode.txt)

so finding 2
The x64 build  cross build yarn gulp vscode-linux-arm64 builds the package , when the command code-oss is entered, reset the machine take place. chroot and chrome book, the same as the binaries from [vscode market](https://code.visualstudio.com/)

the x64 build on x64 machine  yarn gulp vscode-linux-x64 work on the command code-oss functions the app works fine

the arm64 build via ./scripts/npm.sh -arm64 is now building so i report back

**Comment by TomTravis** [comment]
Update
the code-oss built with ARM however no change the machine resets, I have complied new nodejs v16.15.0 code and will try this same the x64 machine, Arm64 compiles now with no errors what the flag -arm64 on .script/npm.sh -arm64
also code-oss --debug to see what happens
i will also try a x64 build on the arm64 the cross complier is installed

I have no idea what the gulp tasks are maybe the readme will be updated

The x64 code runs great web extension are working now with a new product.json file the whole resources app folder is new

**Comment by Tyriar** [comment]
Here are the cross compile instructions which I don't think you're following based on what you're running: https://github.com/microsoft/vscode/wiki/Cross-Compiling-for-Debian-Based-Linux

This is how we do macOS cross compiling: https://github.com/microsoft/vscode/blob/98d9782b8bc77891135a5b295c9489e7ddf0d2a4/build/azure-pipelines/product-build.yml#L328-L398, we do not provide support or instructions for how to do this but how we do it is there.

> I have no idea what the gulp tasks are maybe the readme will be updated

This is intentional and we don't plan on providing further documentation, you should look at our CI/CD scripts to understand how to do things.

**Comment by TomTravis** [comment]
> This is intentional and we don't plan on providing further documentation, you should look at our CI/CD scripts to understand how to do things. it useless for cli. I'll post a issue about is OK ?

yes i have an I'm running them, on git hub.  this is in scope now
update you readme to match the CI/CD scripts
I did the cross compile it fails. you support many processors and os but provide no reference, just to write my env is wrong

2m 1s
Run yarn --frozen-lockfile --network-timeout [1](https://github.com/TomTravis/vscode/runs/6689304605?check_suite_focus=true#step:8:1)[8](https://github.com/TomTravis/vscode/runs/6689304605?check_suite_focus=true#step:8:9)0000
➤ YN0050: The --frozen-lockfile option is deprecated; use --immutable and/or --immutable-cache instead
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 0s 28[9](https://github.com/TomTravis/vscode/runs/6689304605?check_suite_focus=true#step:8:10)ms
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed in 38s 471ms
➤ YN0000: ┌ Link step
Link step
➤ YN0000: └ Completed in 1m [22](https://github.com/TomTravis/vscode/runs/6689304605?check_suite_focus=true#step:8:25)s
➤ YN0000: Failed with errors in 2m 1s
Error: Process completed with exit code 1.

**Comment by TomTravis** [comment]
chroots and building The cross compile activity is happen now on x86_x64 machine the gitbuild is also being tried.
Arm linux does not work with android studio, chromium and vscode. so the issue is not with vscode. src need to be built on ARCH chroots via x64 this seem to be the work around by the normal

I finally got link error message the nodejs need rebuild electron is also being rebuilt, python build failed do to linking

The yarn gulp compiles and link with no errors arm64 the debug has provided some assistance.

 vscode tries to run, the support code fails nodejs python java
i have input for the wiki when progress happens
