### ISSUE TITLE
Merge editor: result depends on the order checkboxes are check in

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151041]
Testing #150389

1. Open merge editor for a merge conflict
2. Start by checking the boxes on the left and then the box on the right for a conflict. This creates one result:

![Screen Shot 2022-06-01 at 2 59 40 PM](https://user-images.githubusercontent.com/12821956/171509050-abbfe96c-4408-4497-96b3-bb452ed5bc92.png)

3. Now uncheck everything and then check the boxes on the right side and then on the left. This creates a different result:4. 

![Screen Shot 2022-06-01 at 2 59 52 PM](https://user-images.githubusercontent.com/12821956/171509102-adb73d6e-4dce-463a-ac40-7b0f5fe1cd21.png)

**Bug**
Perhaps this is expected but it feels odd that I can end up with different results for the file contents when I have the same UI state

**Comment by hediet** [comment]
Fixed.
