### ISSUE TITLE
No prompt when accepting merges with conflicts

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#151024]
Testing #150389

Expected to see:

![image](https://user-images.githubusercontent.com/13199757/171483920-25fa225e-8cf6-49a5-aa0a-c7782a3cc105.png)

but changes were staged with conflicts.

**Comment by jrieken** [comment]
<img width="1102" alt="Screenshot 2022-06-25 at 18 22 22" src="https://user-images.githubusercontent.com/1794099/175782269-32e8710b-fbbd-4117-b256-0c72d1c4cb57.png">

⬆️ that's how it will look, with PR #153211. open for working tweaks

**Comment by jrieken** [comment]
To verify:

* open merge editor
* close the editor while having unhandled conflicts
* ensure a modal confirm message shows
* make sure the working makes sense
* make sure the message doesn't show when pressing 'Accept'
