### ISSUE TITLE
remove env var indicator from terminal

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151160]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have some task for which shell integration fails to activate
2. :bug: warning icon is rendered on top of task output
![image](https://user-images.githubusercontent.com/30305945/171739361-53d37444-da53-4d4a-9ae1-43030d679003.png)

**Comment by Tyriar** [comment]
@joyceerhl if you hover that does it talk about environment variables? I didn't think we mentioned shell integration there

**Comment by meganrogge** [comment]
from @joyceerhl, it's showing in the tab hover
![image (2)](https://user-images.githubusercontent.com/29464607/171747849-3410bb07-1ae6-46fc-82e7-f6552e905cff.png)
