### ISSUE TITLE
All export commands hidden from command palette after saving new untitled ipynb to virtual GitHub Repositories workspace

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151158]
Testing microsoft/vscode-jupyter#10183

1. Create untitled ipynb
2. Run cells
3. ✅ export commands are available in command palette
4. Save the untitled notebook as ipynb and give it a title
5. Open command palette
6. :bug: all the export commands are now hidden

**Comment by greazer** [comment]
Save As is handled by core. Need to transfer current controller to new ipynb.

**Comment by Tyriar** [comment]
Seems related to https://github.com/microsoft/vscode/issues/150890?

**Comment by roblourens** [comment]
Not sure @Tyriar - we are handling this the same way we persist selection and other view state. But the editor still gets reopened with a new model. Dunno how this concept works in custom editors.

**Comment by Tyriar** [comment]
Custom editors have one the untitled editor closed and a new one with another URI open, I want a signal that a custom editor can handle to upgrade it so no close/open needs to happen

**Comment by roblourens** [comment]
Steps:

- Open an untitled jupyter notebook
- Select a kernel
- Save the notebook
- The same kernel should be selected


The "Set kernel as default" gear icon in the kernel picker was also removed.

**Comment by jrieken** [comment]
Verified with this "kernel"

```
const ctrl = vscode.notebooks.createNotebookController('fff', 'jupyter-notebook', 'FOO');
	ctrl.executeHandler = (cells) => {
		for (let cell of cells) {
			const exec = ctrl.createNotebookCellExecution(cell)
			exec.start()
			exec.replaceOutput(new vscode.NotebookCellOutput([vscode.NotebookCellOutputItem.text(`hello@${Math.random()}`)]))
			exec.end(true)
		}
	}
```
