### ISSUE TITLE
Can't use cell run dropdown button unless focused on that cell

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#151179]
Open a notebook with multiple cells
Set focus in the first cell
Try to use the dropdown button in the run button to debug the second cell

actual:
dropdown closes immediately
![dropdown](https://user-images.githubusercontent.com/2019016/171751908-b0003937-11a6-4a15-b375-b4539ab0fd23.gif)

**Comment by roblourens** [comment]
Same as https://github.com/microsoft/vscode/issues/125109
