### ISSUE TITLE
Merge Editor: language status should show

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#151136]
Testing #150389

I assume we hide the language picker right now since it wouldn't make sense to switch. Should we hide the entire status bar item including the `{}` button?

<img width="237" alt="CleanShot 2022-06-02 at 10 05 30@2x" src="https://user-images.githubusercontent.com/25163139/171685259-ffb56223-c52f-430f-953e-e231f6158a1c.png">

**Comment by bpasero** [comment]
I think the editor status entries should reflect the full scale of the result editor, same as we do for diff editors. For example changing the language mode changes it for all editors inside.

**Comment by daviddossett** [comment]
That sounds reasonable then. Better than half of it being hidden, in any case.

**Comment by bpasero** [comment]
@jrieken fyi for the diff editor we apply the change to the language to both sides, maybe for merge editor it should apply to all 3 sides?

**Comment by jrieken** [comment]
Yeah, I wasn't sure about that and went with the minimum - it's unlikely that you have language features in those readonly editors anyways. Well, except for tokens...

**Comment by jrieken** [comment]
changed my mind: https://github.com/microsoft/vscode/pull/153278
