### ISSUE TITLE
Support <...> bracket matching in TypeScript

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#151196]
Mark `<` ... `>` in `punctuation.definition.typeparameters.begin.ts` and `punctuation.definition.typeparameters.end.ts` as brackets.

Should be very easy, given the new bracket matching feature to consider textmate scopes.

**Comment by KoushikSahu** [comment]
Hi @hediet 
I verified that the angular brackets aren't colourized in typescript files. I want to work on this issue. Can you please give me a briefing as to what needs to be done?

**Comment by hediet** [comment]
Add < and > as bracket pair in the typescript language configuration.
Also see here https://code.visualstudio.com/updates/v1_67#_textmate-grammars-can-mark-tokens-as-unbalanced

**Comment by hediet** [comment]
Maybe it actually is easier to just exclude `keyword.operator.relational.ts`.

**Comment by Rayzon3** [comment]
> Add < and > as bracket pair in the typescript language configuration. Also see here https://code.visualstudio.com/updates/v1_67#_textmate-grammars-can-mark-tokens-as-unbalanced

I added < and > as bracket pair in the typescript language configuration file.  But it doesn't seem to resolve the issue.

**Comment by KoushikSahu** [comment]
> > Add < and > as bracket pair in the typescript language configuration. Also see here https://code.visualstudio.com/updates/v1_67#_textmate-grammars-can-mark-tokens-as-unbalanced
> 
> I added < and > as bracket pair in the typescript language configuration file.  But it doesn't seem to resolve the issue.

I have the same issue. I observed that `yarn watch` is not watching for changes in `typescript-basic` extension in my setup. This might be an issue in my build and I am trying to fix it.

**Comment by Rayzon3** [comment]
> > > Add < and > as bracket pair in the typescript language configuration. Also see here https://code.visualstudio.com/updates/v1_67#_textmate-grammars-can-mark-tokens-as-unbalanced
> > 
> > 
> > I added < and > as bracket pair in the typescript language configuration file.  But it doesn't seem to resolve the issue.
> 
> I have the same issue. I observed that `yarn watch` is not watching for changes in `typescript-basic` extension in my setup. This might be an issue in my build and I am trying to fix it.

Yeah same thing happening with me also. `yarn watch` is not watching `typescript-basic`

**Comment by hediet** [comment]
Did you configure the pair as colorized bracket pair?

**Comment by KoushikSahu** [comment]
@hediet Can you please review my PR? Also, I would require approval for running the rest of the action workflows. I hope you can provide the necessary approval.

**Comment by hediet** [comment]
Verification steps:
* Verify that `<`...`>` is matched in TypeScript where it makes sense
* Verify that `<` is not matched against a bracket in `if (x <= y) { ... }` or in other places where it does not make sense

**Comment by karlhorky** [comment]
@hediet @liby are multi-line generic parameter lists also matched?

eg. 

```ts
type A = SomeLongerTypeName<
  AnotherFairlyLongTypeName,
  AndFinallyAReallyLongTypeName,
>;
```

Looking at the TextMate Scope Inspector, it seems like the `<` symbol is not matched as a `punctuation.definition.typeparameters.begin.ts` currently:

![Screen Shot 2022-08-02 at 16 29 11](https://user-images.githubusercontent.com/1935696/182401945-454718ed-5269-4471-a744-72e56fe4323d.png)

This would be helpful for extension development: https://github.com/frigus02/vscode-sql-tagged-template-literals/pull/21

cc @jrieken @sheetalkamat

**Comment by karlhorky** [comment]
Oh it looks like this may be a limitation of the TextMate single-line lookup: https://github.com/microsoft/TypeScript-TmLanguage/issues/761
