### ISSUE TITLE
Validation not working in settings JSON

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#151107]
Version: 1.68.0-insider
Commit: 15253f1528573fc8f84e956b21af4bad57f38c07
Date: 2022-06-02T05:17:01.962Z

- open the Settings JSON editor
- add some unnecessary commas
- no problems reported in the problems view.
- open the JSON Language Server log. Observe that there are no diagnostic requests. Other requests are sent and completed, so the language server is running.

**Comment by chrmarti** [comment]
Maybe unrelated: I was expecting "trailing comma" warnings in devcontainer.json (we recently changed the schema to not accept them), but they only started showing after I flushed the schema cache (using the UI command) and reloaded the window (I can't completely rule out that a window reload alone would have helped).

**Comment by aeschli** [comment]
@chrmarti I checked that with the fix the trailing commas are reported
