### ISSUE TITLE
When developer tools pane is expanded, window controls are overlaid 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151180]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open developer tools
2. :bug: layout controls render over dev tools pane in top right of window:
![image](https://user-images.githubusercontent.com/30305945/171753164-c02b25ff-f40e-448d-bd3e-084e11fb8bbd.png)

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/150521
