### ISSUE TITLE
Merge Editor: layout toggle should reflect current state, not target state 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#151137]
Testing #150389

Was confused when toggling between layout states. I expected the icon to reflect the layout mode I'm currently on, not the one that would result on click. Note the "Mixed Layout" icon showing here while viewing the "Column Layout" mode.

![CleanShot 2022-06-02 at 10 07 43@2x](https://user-images.githubusercontent.com/25163139/171685648-677b27b2-81bf-4887-9b2f-97bdd1541511.png)

**Comment by daviddossett** [comment]
@misolori any thoughts on icon ideas below? These are somewhat specific to the merge editor but have some overlap with the layout mode icons.

<img width="822" alt="CleanShot 2022-06-02 at 11 12 11@2x" src="https://user-images.githubusercontent.com/25163139/171698140-64f4ee68-dd09-44ad-a087-09b12b7ddf3d.png">

**Comment by misolori** [comment]
> I expected the icon to reflect the layout mode I'm currently on, not the one that would result on click

Agreed, the layout controls show the current state:

<img width="283" alt="CleanShot 2022-06-06 at 09 27 51@2x" src="https://user-images.githubusercontent.com/35271042/172203527-13a2d63f-fce3-4a49-a91b-af2aaf1c82ed.png">

@daviddossett those could work, the only downside I see is they are also similar to the editor split button where they'll be next to each other. Can you show them in context with a simple prototype to test out?

**Comment by daviddossett** [comment]
Trying it out. Definitely a lot of similar looking icons in one place. Especially with the split editor action right next to it which might be confused as a layout control. 

![CleanShot 2022-06-07 at 14 14 49](https://user-images.githubusercontent.com/25163139/172484086-e4ab17e9-e2ef-4400-87e4-d4c17800fdf1.gif)

**Comment by daviddossett** [comment]
If a layout toggle ends up being too confusing given the overlap with the workbench layout + split action, we could consider something closer to the original sketches where it's a static icon that opens up a context menu:

<img width="860" alt="CleanShot 2022-06-07 at 15 08 10@2x" src="https://user-images.githubusercontent.com/25163139/172492327-d230e476-4437-4c1e-b4b7-5f228e534528.png">

<img width="842" alt="CleanShot 2022-06-07 at 15 08 38@2x" src="https://user-images.githubusercontent.com/25163139/172492333-fe7f60a3-3d66-4380-864d-630780b75ec7.png">

Not sure what the right icon would be, but it's something to consider.

**Comment by misolori** [comment]
have you thought about using the ellipsis menu for this? We currently do this for the inline diff view and would match:

<img width="374" alt="CleanShot 2022-06-08 at 16 03 41@2x" src="https://user-images.githubusercontent.com/35271042/172731873-a1ddd964-6a30-4b63-b1df-747fba2344d0.png">

**Comment by daviddossett** [comment]
That's actually what I had in the original design, but I hadn't factored in the existing menu items. I'm a fan of that approach if not just for the noise reduction and consistency 👍 

<img width="1046" alt="CleanShot 2022-06-08 at 16 06 18@2x" src="https://user-images.githubusercontent.com/25163139/172732114-c72f5b31-441f-4ade-99e3-af8f902e9acc.png">

**Comment by misolori** [comment]
It can maybe be a bit less discoverable, but a lot of people know it from the diff view so there might be some familiarity.

**Comment by jrieken** [comment]
<img width="678" alt="Screenshot 2022-06-24 at 14 57 13" src="https://user-images.githubusercontent.com/1794099/175540593-7a25844c-a895-4a66-be02-5f471d3f0cce.png">

**Comment by daviddossett** [comment]
Looks great!
