### ISSUE TITLE
`editor.renderWhitespace` and `editor.fontLigatures` don't work well together

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#151166]
Issue Type: <b>Bug</b>

1. open vscode: `code-insiders --user-data-dir /tmp/blah --disable-extensions`
2. apply the following settings:
```
    "editor.renderWhitespace": "all",
    "editor.fontLigatures": true
```
3. type in the editor `asdf`  and then SPACE.

I expected the cursor to be after the space but for whatever reason I am seeing the cursor _before_ the space (as in the cursor doesn't move after I hit space)

VS Code version: Code - Insiders 1.68.0-insider (15253f1528573fc8f84e956b21af4bad57f38c07, 2022-06-02T05:16:30.515Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--user-data-dir=/tmp/foo12 --disable-extensions --log trace --crash-reporter-id 6c48ba9e-20ff-4f9a-a689-e30bdd294dc4|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912cf:30496797
vsclangdf:30492506

```

</details>

**Comment by TylerLeonhardt** [comment]
![Recording 2022-06-02 at 15 11 31](https://user-images.githubusercontent.com/2644648/171746893-5e3081ec-fd82-4406-9bd9-20b7d6b204e0.gif)

**Comment by alexdima** [comment]
@TylerLeonhardt I think you're running into https://github.com/microsoft/vscode/issues/150968 / https://github.com/microsoft/vscode/issues/151057 . PR https://github.com/microsoft/vscode/pull/151088 should fix this. Can you please try from source, the change will only make it to tomorrow's insiders.

**Comment by IllusionMH** [comment]
Also encountered problem with spaces at the end of the line (that were hardest 10 lines of comment to type for some reason) but with todays build looks OK

**Comment by alexdima** [comment]
@TylerLeonhardt I will optimistically close this. Please reopen if you still see it.

**Comment by TylerLeonhardt** [comment]
Working again :) thanks!
