### ISSUE TITLE
After running a case sensitive search, terminal find count is out of sync 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151181]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. `ls`
2. search for 'a'
3. change search to be case sensitive
4. :bug: current position exceeds number of available matches (159 of 109 in screenshot below)
![image](https://user-images.githubusercontent.com/30305945/171753736-6506a54c-b092-4640-b5d8-012a6f616daa.png)

**Comment by meganrogge** [comment]
Works when you press enter once, so think we should just update match count when one of the options (case sensitivity for ex) is toggled

**Comment by joyceerhl** [comment]
Still repros for me with the original steps:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/30305945/214718242-00cef004-5bbd-4af3-b3ca-6eba2b0cbb2a.png">

**Comment by meganrogge** [comment]
Cannot repro having an index higher than the result count, but do see a problem with the index updating as I toggle that on and off

https://user-images.githubusercontent.com/29464607/214899407-9f12d127-7e8d-42e6-959e-4fdc42696301.mov
