### ISSUE TITLE
Inappropriate rendering text "cells hidden ..."

### ISSUE THREAD

**Issue by bzielinskib** [microsoft/vscode#151150]
### Applies To

- [ ] Notebooks (.ipynb files)
- [X] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

During using folding and unfolding the text "cells hidden ..." is rendered inappropriate. The problems occur when many usages of folding are. There is an example:

![jupyter_cell_hideen](https://user-images.githubusercontent.com/49487573/170863164-9a63e52f-4f8a-4d98-b8f8-c73721875ca2.gif)

There is an example file:
[report_template copy.zip](https://github.com/microsoft/vscode-jupyter/files/8793107/report_template.copy.zip)

### VS Code Version

1.67.2

### Jupyter Extension Version

v2022.4.1021342353

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
> Thanks for filing this issue, we've run into similar issues in the past.

Have we? I don't remember seeing this before. But I can repro it
