### ISSUE TITLE
Warning: "Cannot validate the php file. The php program was not found...."

### ISSUE THREAD

**Issue by lvasilev1** [Microsoft/vscode#15114]
- VSCode Version: 1.7.1
- OS Version: Windows 8

Steps to Reproduce:

1. Go to File -> Preferences -> Workspace Settings
2. In the newly created settings.json enter the following line:

    `"php.validate.executablePath": "C:/PHP/php.exe"`

After I do that, I still get the following error:

    

> Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'.

I've verified the location of the PHP executable by using the following command line:

> where php.exe

as well checking the value of system variable PHPRC.

Why is VS Code still not finding the PHP executable?

**Comment by polygotdev** [comment]
Given ```php.exe``` can be found in the windows search ```PATH```, how about trying to set the configuration parameter back to ```null``` and let if fall back to this search PATH

```
// Place your settings in this file to overwrite the default settings
{
    "php.validate.executablePath": null
}
```
![2016-11-07_12-25-09](https://cloud.githubusercontent.com/assets/18198056/20072433/948d28d4-a4e5-11e6-9f5c-51b361c3f224.png)

![2016-11-07_12-26-08](https://cloud.githubusercontent.com/assets/18198056/20072435/96e145d4-a4e5-11e6-999d-85f9fdaad5e4.png)




reference: https://github.com/Microsoft/vscode/issues/251

**Comment by lvasilev1** [comment]
Looks like php.exe was on the windows search PATH all along:

![image](https://cloud.githubusercontent.com/assets/16479217/20074147/a696f49c-a4f4-11e6-99dd-9ce6afffc10a.png)

I tried what you suggested, i.e. setting the configuration parameter to **null** and still getting the same warning.

**Comment by polygotdev** [comment]
It may be a case of some local settings default in the workspace overwriting global settings.

Here are the steps I've take to validate vscode making use of the php linter using default search path:

1. Created a blank empty folder
2. open up a command prompt inside that new empty folder
3. set the PATH variable to temporarily include the php interpreter as it is not SET globally in the ENV.
3. type```code test.php```
 
this should open up vscode using global user defaults. No warning initially appears. Typed in some php code and then upon saving the file, the linter kicked in.


![2016-11-07_13-38-39](https://cloud.githubusercontent.com/assets/18198056/20075011/c5ad3d96-a4ef-11e6-916e-747729ddcfe6.png)

___

![2016-11-07_13-39-44](https://cloud.githubusercontent.com/assets/18198056/20075017/cf21847c-a4ef-11e6-820c-64ff4b431186.png)

**Comment by dbaeumer** [comment]
Does it work if you call php from a terminal for the give file ?

**Comment by lvasilev1** [comment]
@polygotdev From what I can tell, the PATH variable does include the PHP interpreter. Please look at my post above. I did try creating a new folder with a dummy PHP file in it and then opened it through VS Code, typed in the same thing you have on there and clicked on save, but the linter did not kick in.

@dbaeumer I am very new to PHP. I am a C# .NET developer and got assigned a bug to fix in a PHP code base, so I've been having to learn it in a very short amount of time. However, if I am understanding you correctly, I can't call PHP from a terminal for the given file because the PHP code base in question lives on a network share somewhere and I am running VS Code on my local machine. I tried the "net use" command just now to see if I can map the network drive to a new drive on my machine, but that didn't work.

**Comment by polygotdev** [comment]
@lvasilev1 how about linting a local dummy file on the windows command line?

```
C:\tmp>echo %PATH%
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\mm\AppData\Local\Microsoft\WindowsApps;;C:\Program Files (x86)\Microsoft VS Code\bin

C:\tmp>where php
INFO: Could not find files for the given pattern(s).

C:\tmp>set PATH=%PATH%;c:\php

C:\tmp>where php
c:\php\php.exe

C:\tmp>php --version
PHP 7.0.12 (cli) (built: Oct 13 2016 10:47:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

C:\tmp>dir
 Volume in drive C has no label.
 Volume Serial Number is 0C21-5771

 Directory of C:\tmp

11/08/2016  09:34 AM    <DIR>          .
11/08/2016  09:34 AM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  113,247,416,320 bytes free

C:\tmp>code test.php

C:\tmp>php -l test.php
No syntax errors detected in test.php

C:\tmp>php -l test.php

Parse error: syntax error, unexpected end of file in test.php on line 1
Errors parsing test.php

C:\tmp>code --version
1.7.1
02611b40b24c9df2726ad8b33f5ef5f67ac30b44

```

**Comment by dbaeumer** [comment]
@lvasilev1 thanks. That is exactly what I was try to say.

**Comment by lvasilev1** [comment]
@polygotdev Thanks, i am going to try that when I have some free time. I am against a deadline here and since i am technically able to use VS Code without intellisense, resolving this issue is not a priority.

**Comment by dbaeumer** [comment]
Without the additional information we can't work on this issue. Please ping when the information is available and we will reopen the issue.

**Comment by urbgimtam** [comment]
I know this was closed, but just wanted to add that the path written had the wrong syntax for VS Code.

Instead of 
`"php.validate.executablePath": "C:/PHP/php.exe"`

it should be written
`"php.validate.executablePath": "C:\\PHP\\php.exe"`

This should solve the problem.
