### ISSUE TITLE
Unclear how to run cells if in serverless untrusted workspace and trying to connect to remote server

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151156]
Testing microsoft/vscode-jupyter#10183

In restricted mode, I don't see the command to specify a Jupyter server, and if I click the run button I get this message (which maybe RemoteHub shouldn't contribute anymore? cc @roblourens)

Wondering if we want to show the command in the palette in restricted mode, but request workspace trust when it's invoked. Not sure if this has been discussed before so please forgive me if I'm rehashing an existing discussion.

![image](https://user-images.githubusercontent.com/30305945/171689022-0bb9dcba-1b83-42c7-ac7d-73e556ff803e.png)

**Comment by joyceerhl** [comment]
@greazer to clarify, the main pain point I have here is that the command to specify a Jupyter server shouldn't be hidden in an untrusted workspace if that is the entrypoint that users are looking for. In the same vein, the debug view is not hidden in an untrusted workspace, but if you attempt to launch + debug in restricted mode you get this dialog 
![image](https://user-images.githubusercontent.com/30305945/171737853-80e33e55-b122-4406-b92c-fdce13e7d3e5.png)

**Comment by roblourens** [comment]
Not sure how this experience is expected to work - why can't I connect to the remote in an untrusted workspace, then when I try to run a cell, I will be prompted to trust the workspace, like usual?

Besides that, currently there are no kernels contributed in web, whether or not the workspace is trusted, and the "Select kernel" button is hidden. Why do we hide it, is that something we hardcoded for web? @rebornix 

In the future, I think I will also see the "Github" or other option for lazy kernel appear. If there is something in that list, then the normal behavior for the run button will kick in - you click it and trigger vscode core's run command which asks you to trust the workspace, then pick a kernel.

But if lazy kernels aren't available, we probably want to still push them towards codespaces with "continue on"

**Comment by roblourens** [comment]
> why can't I connect to the remote in an untrusted workspace, then when I try to run a cell, I will be prompted to trust the workspace, like usual?

That is how it works now
