### ISSUE TITLE
Network share issues

### ISSUE THREAD

**Issue by dogmatic69** [Microsoft/vscode#15113]
- VSCode Version:
1.7.1
- OS Version:
Ubuntu 16.04

- Problem
Intermittent issue saving files on a network (samba / cifs) share. This share is between two PC's on the same internal network.

Now and again when saving a file it will pop up an error saying it could not save, it then pops up a notice saying file has changed on disk with option to compare

When comparing the "disk" version is empty. The save has cased saving a blank file.

Closing the file and reopen and I can continue saving and editing as per usual.

![image](https://cloud.githubusercontent.com/assets/94674/20066812/dc00aa04-a50a-11e6-86f9-46fcf3526594.png)

![image](https://cloud.githubusercontent.com/assets/94674/20066837/ead54c1a-a50a-11e6-948a-6542c6942aeb.png)

I have checked with `ls -al` when this happens and the file size is 0. As this has emptied the file, there is a real chance of losing work.

Today is the first day I have been using a network share and it has happened 3 times.

**Comment by wUFr** [comment]
I use SMB network share and don't have any problems so far
Windows 10 
Share from CentOS 7 over hyper-v local switch (local virtual machine)

**Comment by bpasero** [comment]
Would like to fold this into https://github.com/Microsoft/vscode/issues/13665

**Comment by bpasero** [comment]
@dogmatic69  does it still reproduce with our latest insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
