### ISSUE TITLE
Render Markdown of JSDoc 

### ISSUE THREAD

**Issue by mohsen1** [Microsoft/vscode#15117]
- VSCode Version: 1.7.1
- OS Version: macOS

I'm expecting 

```ts
/**
 * This is foo
 * Foo is great! Use it like this:
 * 
 * ```ts
 * const foo = new Foo(); 
 * ```
 */
function Foo() {

}


var f = new Fo
```

I was expecting my Markdown to be rendered here: 

![screen shot 2016-11-07 at 10 35 41 am](https://cloud.githubusercontent.com/assets/543633/20070625/f73a3fb8-a4d5-11e6-93f2-393b0d057e2f.png)

**Comment by Emeryao** [comment]
the code above works fine and the jsdoc displayed as markdown in a .ts file on insiders build :
```
Version 1.8.0-insider
Commit ce6d57875ab53309204cf12dc54d74956221cfc1
Date 2016-11-09T08:48:03.700Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
OS Windows 10 14393.447
```

**Comment by waderyan** [comment]
I am seeing the issue. 

![image](https://cloud.githubusercontent.com/assets/2449568/20232257/cf4ed33a-a81b-11e6-9b69-2572bc5b38c2.png)

This is a good feature request.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12185
