### ISSUE TITLE
PtyHost trace logs don't make it to the Remote Server output channel

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151159]
This doesn't get logged when creating a terminal with trace logging on https://github.com/microsoft/vscode/blob/331fa9017a7d7d2370d7fc628f66bdfb61363da8/src/vs/platform/terminal/node/terminalProcess.ts#L291

**Comment by meganrogge** [comment]
@roblourens I tried to do this like you and Jackson did for the `ripgrepSearchProvider` on the branch merogge/remote-inv, but i'm still not seeing the logs anywhere when using remote WSL. Thoughts?

https://github.com/microsoft/vscode/blob/2ba67b7b07530f0e48ba8dc44d382c521fe7b947/src/vs/workbench/services/search/node/ripgrepSearchUtils.ts#L47-L53

https://github.com/microsoft/vscode/blob/8afbbf643950e29dc916251771423cdfa59adc42/src/vs/platform/terminal/node/ptyService.ts#L76-L80

Need this to investigate remote terminal reconnection bc when ssh'ing to localhost, I can't repro the issue and don't want to have to setup a vm.

**Comment by meganrogge** [comment]
maybe bc it's in platform instead of workbench it's not working? can't be in workbench though for the ptyService

https://github.com/microsoft/vscode/blob/8afbbf643950e29dc916251771423cdfa59adc42/src/vs/platform/terminal/common/terminal.ts#L18-L26

**Comment by meganrogge** [comment]
now thinking the logs aren't showing up for the same reason that reconnection doesn't work for WSL.

**Comment by Tyriar** [comment]
@meganrogge instead of an output channel I think what we're after is something like this:

https://github.com/microsoft/vscode/blob/27e10113dc53dace848912a4975f15087e0c584e/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L195-L196

Here:

https://github.com/microsoft/vscode/blob/abf793d426578cbf2fc3e345313d0b3efe4bd932/src/vs/platform/terminal/node/ptyHostMain.ts#L19-L21

I thought that's what the LogLevelChannel was doing but maybe not? Or maybe that particular log service/channel type doesn't work on the server since it does in the shared process?

![image](https://user-images.githubusercontent.com/2193314/172897297-62d430c8-5d86-43ef-870d-d6d27a6fa6ec.png)
