### ISSUE TITLE
Allow ctrl+arrow to advance cursor to start of next character

### ISSUE THREAD

**Issue by sdeluca** [microsoft/vscode#151100]
I would like to change the behavior of the key combination: control+arrow(left/right) to advance the cursor past all whitespace characters, up to the first non-whitespace character. The current behavior is: when the cursor is located within whitespace, <ctrl>+<right arrow> will navigate to the _end_ of the next word and not the _beginning_. 
Essentially I'm asking for ctrl+arrow behavior that mimics web browsers and other text-entry apps.

**Comment by alexdima** [comment]
There are a few built-in variants for word navigation. Did you try them out?
```js
// - cursorWordEndLeft
// - cursorWordEndLeftSelect
// - cursorWordPartStartLeft
// - cursorWordPartStartLeftSelect
// - cursorWordRight
// - cursorWordRightSelect
// - cursorWordStartLeft
// - cursorWordStartLeftSelect
// - cursorWordStartRight
// - cursorWordStartRightSelect
```

**Comment by sdeluca** [comment]
Thank you @alexdima for the tip. I did not realize that this could be handled/overridden with custom key bindings, so I had to get educated on that. I ended up editing the keybindings.json and using cursorWordStartRight command from your list of suggestions.
Thanks again - problem solved!
