### ISSUE TITLE
Merge Editor: result should show remaining conflicts 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#151135]
Testing #150389

I found it hard to know where I still had conflicts while working on a merge. It could be something like this line/word highlight (doesn't need to be red) + the "n conflicts remaining" label to help clarify.

<img width="827" alt="CleanShot 2022-06-02 at 10 00 01@2x" src="https://user-images.githubusercontent.com/25163139/171684371-42d60b23-f582-4355-ac3d-bb09339a518d.png">

**Comment by hediet** [comment]
Implemented (but probably needs some polish).

**Comment by jrieken** [comment]
To verify:

* open a merge editor 
* notice the number of unhandled conflicts in the results editor
* verify the number updates when handling a conflict (note that the check box context menu allows to mark a conflict as un-handled)
