### ISSUE TITLE
CosmosDB documents won't load

### ISSUE THREAD

**Issue by brnwdrng** [microsoft/vscode#151155]
Connect to any CosmosDB database in Azure, then try to open/view any document.  

Displays a error flyup: 

"cannot open azureDatabases:/...-cosmos-document.json?id%3D%2FcosmosDBAttachedAccounts%2Fwest2-crp-nonprod-preference-dev-cosmosdb.documents.azure.com%3A443%2FPreferences%2FPhone%2F%24Documents%2Fi%2BUhAPEfvNACAAAAAAAAAA%3D%3D. Detail: Unable to read file 'azureDatabases:/...-cosmos-document.json?id=/cosmosDBAttachedAccounts/west2-crp-nonprod-preference-dev-cosmosdb.documents.azure.com:443/Preferences/Phone/$Documents/i+UhAPEfvNACAAAAAAAAAA==' (Error: Unable to resolve nonexistent file 'azureDatabases:/...-cosmos-document.json?id=/cosmosDBAttachedAccounts/west2-crp-nonprod-preference-dev-cosmosdb.documents.azure.com:443/Preferences/Phone/$Documents/i+UhAPEfvNACAAAAAAAAAA==')"

**Comment by brnwdrng** [comment]
![flyout](https://user-images.githubusercontent.com/3201523/171737256-82c493e7-a8be-4448-9377-da69414a485a.png)

**Comment by lszomoru** [comment]
Could you please file an issue in [the extension's repository](https://github.com/microsoft/vscode-cosmosdb/issues)? Thank you.
