### ISSUE TITLE
Merge Editor auto picks changes and do not show conflicts

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#151141]
Issue Type: <b>Bug</b>

I tried to use git stash or merge to trigger conflicts. After I get a conflict, I can see the conflict section in normal text editor, but the very moment I open it in the merge editor, the three merge editors show the same content (and the local file is updated too). 100% reproduce with my setup.

VS Code version: Code - Insiders 1.68.0-insider (15253f1528573fc8f84e956b21af4bad57f38c07, 2022-06-02T05:16:07.238Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (14.13GB free)|
|Process Argv|--enable-proposed-api joyceerhl.vscode-pyolite --enable-proposed-api rebornix.better-jupyter-errors --enable-proposed-api donjayamanne.kusto --crash-reporter-id e73ca734-e67c-473d-8c47-80c5407fc859|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
kusto|don|0.3.8
gitlens-insiders|eam|2022.6.105
prettier-vscode|esb|9.5.0
codespaces|Git|1.8.1
copilot|Git|1.25.6056
vscode-pull-request-github|Git|0.42.0
go|gol|0.33.1
vscode-language-pack-zh-hans|MS-|1.68.2
dotnet-interactive-vscode|ms-|1.0.3277041
python|ms-|2022.7.11521008
vscode-pylance|ms-|2022.6.0
jupyter|ms-|2022.5.1001551026
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.237.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.6
js-debug-nightly|ms-|2022.5.3017
live-server|ms-|0.2.12
vscode-github-issue-notebooks|ms-|0.0.119
vscode-markdown-notebook|ms-|0.0.26
vscode-selfhost-test-provider|ms-|0.3.9
vsliveshare|ms-|1.0.5597
vetur|oct|0.35.0
colab-keymap|reb|0.0.4
github-issue-notebook-enhancement|reb|0.0.1
vscode-code-renderer|reb|0.0.2
vscode-jupyter-checkpoint|reb|0.0.1
notification-tester|svi|2.5.1
rest-book|tan|6.0.1
tldraw-vscode|tld|1.14.1
shell-runner-notebooks|tyl|0.0.2
luna-paint|Tyr|0.14.0
vscode-todo-highlight|way|1.0.5

(3 theme extensions excluded)

</details>

**Comment by jrieken** [comment]
@rebornix Can you share more details please?

**Comment by rebornix** [comment]
Hope this gif and steps can help

* Open `notebookCellList.ts`, make changes to https://github.com/microsoft/vscode/blob/445d4aad1b0bf1e72f049a8d60a8791ff12336a2/src/vs/workbench/contrib/notebook/browser/view/notebookCellList.ts#L1244-L1245. `git stash save`
* Make changes to the same line but with different content
* Stage the change
* `git stash pop`
* Now it has conflicts
* With the merge editor disabled, I can open it and see the decorations for merge conflict
* Turn on merge editor, reload the editor
* Open the merge conflict file from SCM, now the changes are adopted automatically, and the merge editor is showing no changes

![merge-editor3](https://user-images.githubusercontent.com/876920/172496401-fad9bb34-8ae5-46dc-a559-61b2c15fe4e6.gif)

**Comment by jrieken** [comment]
@hediet I believe this isn't an issue anymore, right? It is true that we still change the "out" file right after open (and thereby changing all views of this model) but we now (1) shows conflicts nicer and (2) warn you when closing an editor with unhandled conflicts

**Comment by jrieken** [comment]
discussion about always dirty is https://github.com/microsoft/vscode/issues/151040
