### ISSUE TITLE
Codicon text is improperly localized for language override message in settings editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151164]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Follow steps for verifying https://github.com/microsoft/vscode/issues/150231
2. :bug: `$(replace)` codicon text is localized so doesn't get rendered
![image](https://user-images.githubusercontent.com/30305945/171743199-1087b2a7-a619-47ab-b322-c55c2c921454.png)

**Comment by rzhao271** [comment]
Verification steps:
1. Configure the display language to use the pseudo-language extension pack.
2. Navigate to the Settings editor and search for `@lang:markdown editor.wordWrap`.
3. Verify the info codicons render properly.

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/153743 to try catch these earlier
