### ISSUE TITLE
Terminal history for debugging is awful

### ISSUE THREAD

**Issue by AustinAngular** [microsoft/vscode#151145]
When debugging Angular code using the errors listed in the terminal window it is impossible to find the latest list of errors from the latest iteration of code changes / auto-recompile.  The terminal just continues to concatenate all the errors together from previous code changes / earlier code compilations.  For debugging you need to move up to the **first** error from the **latest** code change / auto-recompile but this is almost impossible to do because all of the old errors (which are now not helpful) are still there in the history.  

There needs to be a quick and easy way to start debugging your new list of errors **from the 1st error in the new list** inside the terminal window, without having to scroll up and down trying to find where the old errors end and the new errors begin.

Thank you.

**Comment by Tyriar** [comment]
@AustinAngular sounds like you're after tasks with problem matchers which extract the errors into the problems panel https://code.visualstudio.com/docs/editor/tasks

Also if you run regular commands not a watch command you should be able to hit ctrl/cmd+up to go to the start of the last command run.

**Comment by Tyriar** [comment]
We're also investigating next month the ability to do this with watch tasks for exactly the problem you mention as it's an annoyance for me too: https://github.com/microsoft/vscode/issues/150833
