### ISSUE TITLE
Merge Editor: Checkbox range borders should use 1px stroke

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#151124]
Testing #150389

## Current
<img width="179" alt="CleanShot 2022-06-02 at 08 47 36@2x" src="https://user-images.githubusercontent.com/25163139/171669665-1c92855c-ceaf-44d5-be91-d6922ba43e1b.png">

## 1px
<img width="248" alt="CleanShot 2022-06-02 at 08 48 17@2x" src="https://user-images.githubusercontent.com/25163139/171669743-f9cfb3ea-5fd2-4f8b-a620-63772fb1cb3d.png">

**Comment by hediet** [comment]
Thanks for fixing!
