### ISSUE TITLE
Using zsh theme for my terminal and I'm missing a font inconsolata for powerline

### ISSUE THREAD

**Issue by J-S-Thomas** [Microsoft/vscode#15119]
- VSCode Version:newest
- OS Version:Ubuntu

I have zsh theme(cobalt2 from wesbos) and my theme looks incomplete with strange characters in certain points. I know why this is happening because I have no powerline fonts installed in the vscode integrated terminal. How do I add the  inconsolata for powerline font to vscode terminal.

I added a screen shot to illustrate whats going on...
![vscodeshot](https://cloud.githubusercontent.com/assets/18559173/20071217/1d4d55ec-a4e9-11e6-820a-2f8b360420d5.png)
in my screenshot there should be an arrow at the end of the color indicator...

**Comment by J-S-Thomas** [comment]
This is what My regular terminal looks like.....
![terminatorshot](https://cloud.githubusercontent.com/assets/18559173/20071892/efa49940-a4eb-11e6-9358-8316202c5663.png)

**Comment by Tyriar** [comment]
@rebornix what did you need to do to get powerlines working again?

**Comment by rebornix** [comment]
If you have powerline font installed, you need to tell integrated terminal which one you are using. 

For me, I'm using Meslo, if you take a look at my Iterm2 configuration, it's like 

<img width="428" alt="screen shot 2016-11-08 at 12 18 32 pm" src="https://cloud.githubusercontent.com/assets/876920/20115548/839e60e2-a5ad-11e6-9cf5-c1913e7b8f16.png">

and my configuration is like
```
"terminal.integrated.fontFamily": "Meslo LG M DZ for Powerline",
```

Please note I removed `Regular` as it's not part of the font family name.

**Comment by J-S-Thomas** [comment]
Thanks I Just figured it out last night

**Comment by Tyriar** [comment]
Thanks @rebornix! I opened https://github.com/Microsoft/vscode-docs/issues/675 to follow up with some documentation on the website.

**Comment by looneym** [comment]
```
{
"terminal.integrated.fontFamily": "'inconsolata for powerline'",
"terminal.integrated.fontSize": 16
}
```

**Comment by Xtremefaith** [comment]
2 hours later @looneym you finally gave me the clue with the **'** wrapper, in case I need to find my own response some day, and for those using _SourceCodePro+Powerline+Awesome_ font here is what I had to use

`"terminal.integrated.fontFamily": "'SourceCodePro+Powerline+Awesome Regular'",`
