### ISSUE TITLE
VSCode returns empty string for non-existent configuration values

### ISSUE THREAD

**Issue by geajack** [microsoft/vscode#151167]
Does this issue occur when all extensions are disabled?: Sort of not applicable, but it happens with a fresh install of Insiders

- VS Code Version: 1.67.2 and Insiders
- OS Version: Ubuntu 20.04

Steps to Reproduce:

Clone [this repository](https://github.com/geajack/vscode-config-bug) that I made which contains a minimum example. It defines a VS Code extension. The important part is:

```
function activate(context)
{
    let configuration = vscode.workspace.getConfiguration("example");
    let value = configuration.get("value", "default");
    console.log(value);
    console.log(typeof value);
}
```

Press F5 to debug the extension. You should see logs in the debug console that confirm that the value of `value` is indeed the empty string, instead of `"default"`.

Looking at [the docs](https://code.visualstudio.com/api/references/vscode-api#WorkspaceConfiguration), I'm not 100% sure this isn't intended behavior, but it's surely problematic behavior. It means I have no way of knowing, as an extension author, if a string value isn't present or is actually set to the empty string.

**Comment by sandy081** [comment]
Default value of an string property type is empty string. To know if the value is set or not you can use the inspect API 

https://github.com/microsoft/vscode/blob/84241b284d49893ebd507b13d38fc4d8c4fe2a57/src/vscode-dts/vscode.d.ts#L5714
