### ISSUE TITLE
Shared process exception from applicationinsights: TypeError: setTimeout(...).unref is not a function

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151109]
I saw the pty host didn't connect this morning for some reason and when looking at the shared process it's filled with these exceptions which could be the reason.

![image](https://user-images.githubusercontent.com/2193314/171652396-6feca330-9250-4a3b-a5f3-d82ad7806c46.png)

![image](https://user-images.githubusercontent.com/2193314/171651933-ae56c35a-26be-4ec8-aa1c-e926d0797928.png)

![image](https://user-images.githubusercontent.com/2193314/171652166-f037c276-a740-4a0a-891d-f8002ee86e42.png)

**Comment by Tyriar** [comment]
fyi @meganrogge

**Comment by lramos15** [comment]
Most likely not the reason given this is a fairly old issue https://github.com/microsoft/vscode/issues/140624

**Comment by Tyriar** [comment]
@lramos15 is there a plan to get rid of the error here? I think we should keep an issue open here until the upstream is fixed as it's extremely noisy and errors being thrown could have other unexpected side effects.

It's not clear if anything came out of https://github.com/microsoft/ApplicationInsights-node.js/issues/367 but they could support both environments by casting:

```ts
const x = setTimeout(...) as number | NodeJS.Timeout;
if (typeof x !== 'number') {
  x.unref();
}
```

![image](https://user-images.githubusercontent.com/2193314/171653902-c4c3c9d2-0207-47af-945d-26e3fd393324.png)

**Comment by lramos15** [comment]
@Tyriar I reopened the tracking issue. Feel free to comment your solution on the upstream issue. It sounds like this error will resolve itself when the shared process becomes a full node process.

**Comment by lramos15** [comment]
We might be able to resolve this by switching to the browser package rather than the node package in the shared process but I'm worried that might introduce other unforeseen issues such as `window` not being available.

**Comment by Tyriar** [comment]
window should be available though as it's an electron window?

![image](https://user-images.githubusercontent.com/2193314/171660799-f6ce2d2f-4bf3-471e-9c19-ae131131aad0.png)

**Comment by lramos15** [comment]
Ok maybe the bug here is just that we should be using the web version of app insights within the shared process and not the node version. It is a bit weird then that you're allowed to import stuff from the node folder into the electron window if it ends up using Web APIs

**Comment by Tyriar** [comment]
In general node should work, setTimeout is one of the conflict cases. And unref is rarely used so we haven't seen that be a problem.
