### ISSUE TITLE
Unable to manually merge code snippets

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151154]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have some conflicts in code snippets (i.e. settings sync turned off locally and code snippets modified, then select to merge manually when reenabling settings sync)
2. :bug: clicking Accept Remote or Accept Local does nothing
![image](https://user-images.githubusercontent.com/30305945/171735977-92ccd3c7-1786-47fa-bfab-1f355a9e99cb.png)

**Comment by joyceerhl** [comment]
I then canceled the manual merge, retried the 'Turn on settings sync' flow, and selected to merge (not merge manually). Settings sync said I had a conflict in the settings.json file (which I already resolved conflicts in), and did not flag conflicts in code snippets. I'd expected settings sync to complain about conflicts in the code snippets file instead.

**Comment by sandy081** [comment]
This seems to be fixed now
