### ISSUE TITLE
No checkmarks showing in merge editor

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#151134]
Testing #150389

In the current insiders (15253f1528573fc8f84e956b21af4bad57f38c07), I no longer see any checkmarks in the merge editor:

![Screen Shot 2022-06-02 at 10 00 49 AM](https://user-images.githubusercontent.com/12821956/171684477-dd490f73-68b4-40aa-9435-9c224dd68f19.png)

This is for a new merge and I have not manually edited any of the files

**Comment by hediet** [comment]
You mean the checkbox is checked, but without the checkmark?

**Comment by mjbvz** [comment]
Yes the box is checked but I don't see a checkmark in it. I believe this only started happening in the latest insiders for me

**Comment by hediet** [comment]
Does this still happen? Never happened for me.

**Comment by mjbvz** [comment]
Not recently that I can recall
