### ISSUE TITLE
Add a CLI option to switch to fullscreen or maximize new or existing window

### ISSUE THREAD

**Issue by joelday** [Microsoft/vscode#15115]
- Feature request
Would like to have a CLI option to specify that any new instance/window is maximized/switched to fullscreen (depending on the OS). This would be convenient for a scenario in which (for macOS, for example) I want to launch from a shell script and have each window in its own space. (For macOS, I assume that the normally focused (last) instance will be switched to.)

If I can have an official opinion on what to call the CLI option, I'm happy to whip this up and do a PR.

Thanks!

**Comment by bpasero** [comment]
@joelday how about having a setting that each new window opens as fullscreen? I am thinking to add this as part of the options for https://github.com/Microsoft/vscode/issues/10864

**Comment by joelday** [comment]
@bpasero, that would be awesome!

What about defaulting to Seirra's new native window tabs? :)

**Comment by bpasero** [comment]
@joelday this landed in our insider builds (notes [here](https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_9.md#new-setting-to-control-dimensions-of-new-windows). Maybe you give it a try and report back how it goes.

You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

Re Sierra tabs: this is #15478

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
