### ISSUE TITLE
External file watcher fails for editors that do atomic saves

### ISSUE THREAD

**Issue by jzeferino** [Microsoft/vscode#15111]
- VSCode Version: 1.7.1
- OS Version: osx 10.11.6

Steps to Reproduce:

1. Create a file with random text.
2. Open it with vscode and TextEdit for example.
3. Edit the file in TextEdit and save it.
4. The file was refreshed in vscode.
5. Keep editing the file in TextEdit and save it.
6. vscode don't refresh the file only the first time, after that no more refresh occur.

side note: after editing the file in vscode and try to save it, and it shows a upper popup telling that the file has some diferences from the original and open a compare window.

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by jzeferino** [comment]
I did that and this is the output.

![screen shot 2016-11-09 at 4 18 46 pm](https://cloud.githubusercontent.com/assets/10722952/20145650/ceec9e7e-a698-11e6-8c86-ba7e16eee01a.png)

I've replicated exactly what I told above. Including the save in vscode after edited the file with external application, thats why the RED text appeared.

**Comment by bpasero** [comment]
@jzeferino and your settings?

**Comment by jzeferino** [comment]
@bpasero vscode settings? Or other settings?

**Comment by bpasero** [comment]
@jzeferino yeah your vscode settings.json (and if you have workspace settings in the .vscode folder). I wonder if you maybe configured the file watcher exclude rules.

**Comment by jzeferino** [comment]
@bpasero settings.json is empty and I didn't configured the file watcher exclude rules.

**Comment by bpasero** [comment]
I can reproduce and it is caused by the fact that TextEdit saves the file by first renaming it to another file (something that is called atomic save). The node file watcher we are using is probably stopping to watch at that time and gets disposed.

**Comment by bpasero** [comment]
I have an idea how to fix 👍

**Comment by jzeferino** [comment]
Good work. I was testing in on windows and it works good. There is any way to get a popup when the file is changed via external editor? Could I define it via settings?

**Comment by bpasero** [comment]
No, that is not supported atm.
