### ISSUE TITLE
What should renaming a filename do in a reference link?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#151117]
Follow up from https://github.com/microsoft/vscode/issues/148297

I tried renaming the filename portion of:

```
[ref2]

[yes][ref2]

[ref2]: /README.md#deployment
```
so `/README.md`

![image](https://user-images.githubusercontent.com/2644648/165589179-228da367-45da-42ec-97c2-7d178adde367.png)
(sorry currently using Pseudo language)
but then changing that to README2.md (both when README2.md exists and when it doesn't) just gives me a notification that says "No Results"

I tested this on Linux

**Comment by mjbvz** [comment]
The expected behavior is the following:

- If the file exists, then rename the file (plus all reference to it)
- If the file does not exist, just update all references to it
