### ISSUE TITLE
Show an error when changing display language results in broken `argv.json`

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#151200]
I was trying to test @TylerLeonhardt's display language picker changes but no matter what I tried the language pack I picked wouldn't get applied after restart.

This was in Log (Main):
```
[2022-06-02 16:11:03.860] [main] [error] SyntaxError: Unexpected token } in JSON at position 185
    at JSON.parse (<anonymous>)
    at yt.afterWindowOpen (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:75:75972)
```

Which lead me to 

https://github.com/microsoft/vscode/blob/d9373893583a1b78df346f4671bc24221d5e5aba/src/vs/code/electron-main/app.ts#L1164-L1166

My args file:
```
// This configuration file allows to pass permanent command line arguments to VSCode.
// Only a subset of arguments is currently supported to reduce the likelyhood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// If the command line argument does not have any values, simply assign
// it in the JSON below with a value of 'true'. Otherwise, put the value
// directly.
//
// If you see rendering issues in VSCode and have a better experience
// with software rendering, you can configure this by adding:
//
// 'disable-hardware-acceleration': true
//
// NOTE: Changing this file requires a restart of VSCode.
{
	// Enabled by default by VSCode to resolve color issues in the renderer
	// See https://github.com/Microsoft/vscode/issues/51791 for details
	"disable-color-correct-rendering": true,
	// Display language of VSCode
	"locale": "de",
	// Allows to disable crash reporting.
	// Should restart the app if the value is changed.
	"enable-crash-reporter": true,
	// Unique id used for correlating crash reports sent from this instance.
	// Do not edit this value.
	"crash-reporter-id": "9ca60cf1-0992-49ea-b103-33244d6da605",
}
```

After staring at this for a few minutes I noticed and removed the extra comma, which of course fixed everything.

I don't think I've ever edited this file by hand so I don't know how that comma ended up in there.

It also would have been very helpful to know that my args file was malformed.

**Comment by bpasero** [comment]
Yeah maybe an error toast in the window to explain the error and an action to open the file. 

To be honest, it is perfectly fine if this file is malformed for all of the things inside, besides the display language which has a quite visible effect on the application. The other flags will not result in degraded functionality.

@TylerLeonhardt interest in looking into this? I think the interesting question is how to forward knowledge about the malformed `argv.json` all the way to the window.

**Comment by bpasero** [comment]
Actually now that I think about it: we have a picker that allows to change the language and that somewhere writes into `argv.json`. Similar to what the settings editor does in that case, this should show an error when the file is then malformed 👍

**Comment by TylerLeonhardt** [comment]
@bpasero but what if the user already chose their language (Chinese) then modified their `argv.json` (to disable some electron thing) but did it wrong? They'd be given English again probably...

I guess they'd probably infer that the setting change they made probably got them in a bad state.... but why can't we have a diagnostic for this in the JSON extension?

Left is JSONC right is JSON
![image](https://user-images.githubusercontent.com/2644648/171920045-93a32e2a-ece2-44d3-bebb-51950669be74.png)

Or if JSONC spec allows for trailing `,` our `argv.json` parser handles this?

**Comment by TylerLeonhardt** [comment]
Interestingly, I do eventually get diagnostics showing up in JSONC files:
![Recording 2022-06-03 at 11 03 18](https://user-images.githubusercontent.com/2644648/171921029-2d241b6d-e526-4b4e-b869-bd9354691aa4.gif)

but it takes switching to another language and then back again...

@alexr00 did you experience the same? I feel like if you open up `argv.json` and it shows diagnostics, then that would be good enough to close this issue because at least you would know something is wrong with the `argv.json` file.

**Comment by bpasero** [comment]
An alternative would be to try to just fix the `argv.json` when we open the language picker and figure out the file is malformed. I would expect that a user that does not get the display language to change would try to change it again through the picker?

**Comment by TylerLeonhardt** [comment]
"Fix the JSON" seems easier said than done... Wouldn't that risk deleting settings the user has already applied?

What kind of fixing are you implying?

What if the user accidentally types a random character in their JSON file like:
```json
{
  "locale":"de"
}g
```

> the `g`

Which I personally have definitely done on accident numerous times (not specifically in the argv.json but generally)...

Should we delete the problematic character until we have valid JSON?

**Comment by bpasero** [comment]
@TylerLeonhardt yeah tricky, here is another thought: once you open the language picker, could we show a error dialog indicating that manual user action is required to fix `argv.json`? To clarify:
* user opens the language picker
* you do a `JSON.parse` on the `argv.json` to check for errors first
* in case of error, bring up a dialog informing the user
* show a button to open the file

I doubt this impacts a lot of users so I would keep this as simple as possible.

An alternative I thought was to show the input field in language picker in red to tell the user the file is malformed, but that might be a bit misleading because the input field decoration is more for validation errors in quick pick.

**Comment by bpasero** [comment]
Maybe `setLocale` should throw an error:

https://github.com/microsoft/vscode/blob/5e8550a48798d521eee24542ec0cfb9a6099538a/src/vs/workbench/contrib/localization/electron-sandbox/localeService.ts#L34

And then whoever calls it shows the dialog.

**Comment by TylerLeonhardt** [comment]
Yeah that sounds good. I don't remember if `JSON.parse` handles comments gracefully so I may need to use something else but I like using this flow to get the user to the argv.json.

I still think the JSONC files issue above where it doesn't show diagnostics needs to be fixed to pair nicely with this but I can get an issue going for that specifically.

**Comment by aeschli** [comment]
Use `parse` from `vs/base/common/json` for parsing JSONC files.. In extensions you can use the `jsonc-parser` node module.

**Comment by TylerLeonhardt** [comment]
@bpasero do you have a recommendation for which service I should use to get the content of the `argv.json` file from `electron-browser` in `contrib`?

**Comment by bpasero** [comment]
For example `ITextFileService` with `UTF-8`. The `IJsonEditingService` uses that as well.

**Comment by TylerLeonhardt** [comment]
Verification steps:

* Open `Runtime Arguments`
* Add some text that makes it malformed (like add `asdf` after the closing curly brace) and save
* Now try to change the language `Configure Display Language`

upon configuring you should get an error saying your argv.json is malformed.
