### ISSUE TITLE
no rename action in the file tab's context menu

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151243]
![Screen Shot 2022-06-03 at 12 22 55 PM](https://user-images.githubusercontent.com/29464607/171935114-e2b4c292-42dc-479e-ba5b-7a3a90975f6e.png)

We even have this for the terminal in the editor area where it's less used/important

![Screen Shot 2022-06-03 at 12 23 48 PM](https://user-images.githubusercontent.com/29464607/171935219-b6846a7d-d516-4fee-95d5-147aaf71bed6.png)

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/127087

**Comment by meganrogge** [comment]
@lramos15 can there at least be an action to do this in the command palette?

**Comment by meganrogge** [comment]
two steps feels cumbersome and unnecessary IE focus file in explorer view then F2 or right clicking
