### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by lyudmilpetrov** [Microsoft/vscode#15127]
Great job - suggestion, add commenting in/out line/s.It should be easy copy, refactoring and paste from visual studio

**Comment by aeschli** [comment]
@lyudmilpetrov Not sure what exactly you suggest. Is it comment and uncommenting a line? That would be `Ctrl + /`.
Maybe add a small code example that shows before and after.

**Comment by lyudmilpetrov** [comment]
Hi Martin,

Sorry for wasting your time, it is what you suggested, I just did not know
the short key for that.
Embarrassing and keep up the great work guys,

all the best,

Lyudmil

On Tue, Nov 8, 2016 at 9:20 AM, Martin Aeschlimann <notifications@github.com

**Comment by aeschli** [comment]
No problem, thanks for the quick reply.
