### ISSUE TITLE
Background CPU usage when opening a notebook with folded markdown cells

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#151252]
- Open a notebook, fold some markdown headers that include markdown cells
- Close and reopen the notebook so the folded cells are persisted as folded
- See the renderer process using CPU

I took a profile and saw that we keep trying to prerender a markdown cell, but then stop because it is folded:

https://github.com/microsoft/vscode/blob/97dddde1f742d43184bd8988958a5d9618dbc5f5/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L2628

so the code here:

https://github.com/microsoft/vscode/blob/97dddde1f742d43184bd8988958a5d9618dbc5f5/src/vs/workbench/contrib/notebook/browser/notebookEditorWidget.ts#L1198

should not retry the same cell over and over

Not any recent regression as far as I can tell

**Comment by rebornix** [comment]
@roblourens I guess we kept checking hidden ranges and then checking if a cell is visible. Good catch.
