### ISSUE TITLE
Improve definition GetLeadingNonServiceArgs to keep parameter names

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#151203]
This is the current definition of `GetLeadingNonServiceArgs`:
```ts
type GetLeadingNonServiceArgs<Args> =
	Args extends [...BrandedService[]] ? []
	: Args extends [infer A, ...BrandedService[]] ? [A]
	: Args extends [infer A, ...infer R] ? [A, ...GetLeadingNonServiceArgs<R>]
	: never;
```

Unfortunately, it loses the names of the parameters:

![image](https://user-images.githubusercontent.com/2931520/171830713-5c48c278-f2e0-4e2e-89ba-8431771d8e2f.png)

However, if we change the definition to this:
```ts
type GetLeadingNonServiceArgs<TArgs extends any[]> =
	TArgs extends [] ? []
	: TArgs extends [...infer TFirst, infer TLast] ? TLast extends BrandedService ? GetLeadingNonServiceArgs2<TFirst> : TArgs
	: never;
```

The parameter names are kept:

![image](https://user-images.githubusercontent.com/2931520/171830799-35d1ac8a-5a75-4d94-93bf-a6c5dbe33e66.png)

I don't know how this affects type-checking performance though.

**Comment by mjbvz** [comment]
@hediet I think you should just submit this as  a PR :)
