### ISSUE TITLE
Mac OSX warning: Launching Visual Studio Code will damage your computer. You should move it to Trash.

### ISSUE THREAD

**Issue by MrSkinny** [Microsoft/vscode#1512]
I get this message when I restarted Code after it auto-updated. It gives me no option other than to Move to Trash. I tried deleting the `.app` file from my Applications folder and reinstalling a new download. Same result.

I also tried installing via Brew Cask.  

```
$ brew cask install visual-studio-code
==> Downloading https://az764295.vo.msecnd.net/public/0.10.1-release/VSCode-darwin.zip
##################################################                        70.1%^C
```

I exited the process because when I searched for `az764295.vo.msecnd.net` it brings up info on a "google redirect virus/malware".  Can anyone confirm this is a legit domain?

**Comment by MrSkinny** [comment]
Adding sha256 of the file downloaded that I tried to clean install after deleting the .app from Applications:
`eab49cfce612f66e66816efbc5341415d2f25c1c7e5ae98d57cfb91016007af5  VSCode-darwin.zip`

**Comment by bpasero** [comment]
@MrSkinny make sure to download from https://code.visualstudio.com. For me the SHA-256:

<img width="769" alt="screen shot 2015-12-21 at 09 10 30" src="https://cloud.githubusercontent.com/assets/900690/11926156/c7ab0fd6-a7c2-11e5-9ea1-8840b2ab7d70.png">

**Comment by MrSkinny** [comment]
@bpasero Well, now I'm more than a bit concerned and not sure if you'd have any thoughts on what I should do.  I just downloaded again from code.visualstudio.com and get the same file with sha `eab49cfce612f66e66816efbc5341415d2f25c1c7e5ae98d57cfb91016007af5`

However, when I log into a private VPN and attempt download, I get the file with `0faafafed481652a059f04ab83c00161aed951a2414c6d5ef5363854ec4f0348`.  

In both situations I check the SSL in my browser at the code.visualstudio.com homepage, and it identifies as cert issued by Microsoft IT SSL SHA2.  

I tried downloading on VPN while in my Chrome browser normal profile and also incognito browser, and it gets the CORRECT file, which leads me to believe that if some kind of malicious redirect is occurring, it's not happening from Chrome, but at the network level?

And given I'm at home connecting directly via my ISP's router, there's some kind of man-in-the-middle happening?!  

I have Sophos AV installed on my Mac and it didn't detect any problems with the suspect file, which means the only way I even know about this is the Mac OS was somehow able to decide it was dangerous when attempting to launch the .app.

**Comment by bpasero** [comment]
@MrSkinny can you compare the 2 applications (unzip the zip) to see where the changes are? See http://stackoverflow.com/questions/7938477/is-there-any-tool-to-find-any-difference-between-two-xcode-projects for a tool on Mac that can be used.

**Comment by Elusive138** [comment]
@MrSkinny Can you confirm that the certificate [fingerprint](https://www.grc.com/fingerprints.htm) matches:

```
SHA-1
3F:C3:E6:B6:00:4D:E1:08:18:8C:AF:9B:BF:07:6C:86:E2:14:41:85
SHA-256
B4:AB:E7:FA:73:92:74:D2:AA:18:33:89:63:53:A0:D0:68:49:07:DE:46:B3:0A:07:B2:3D:1E:FA:D1:89:42:EA
```

**Comment by MrSkinny** [comment]
@Elusive138 The SHA1 fingerprint matches, don't know how to check the SHA-256 in Chrome, it's not in the cert details window.

I don't know if anything's changed but both on and off VPN now, the file is downloading from:
`https://az764295.vo.msecnd.net/public/0.10.5/VSCode-darwin.zip` (according to the Network tab)

Is this the correct location?

@bpasero This is probably a really dumb question but no execution happens or danger to my machine if I use the FileMerge.app to check the diff between the two containers?  I'd happily upload the one with the suspect hash to Dropbox or something for you to examine.

**Comment by bpasero** [comment]
@MrSkinny FileMerge is totally ok to use, it comes from Apple's XCode. You can also upload and I can take a look.

**Comment by bpasero** [comment]
@MrSkinny we now have 0.10.6 published, do you still get this?

**Comment by MrSkinny** [comment]
Sorry have been out of commission last few days.

@bpasero sha256 of file I am currently receiving from code.visualstudio.com - `78d333e1e7ae9bffc84fa1c6a0dbc3e8530d85b62c3b318e6687eefec2b3ddf9` - pls verify is 0.10.6?

I have uploaded the original 'suspect' file to Dropbox link below that initiated this thread and causes the 'damage your computer' install warning with sha256:  `eab49cfce612f66e66816efbc5341415d2f25c1c7e5ae98d57cfb91016007af5`. If you don't mind, please let me know if you experience same and what filemerge shows.

https://www.dropbox.com/s/q6w2ynpz3rwsj1g/VSCode-darwin-unknown-hash.zip?dl=0

**Comment by bpasero** [comment]
@MrSkinny I see a __MACOSX folder inside the zip file which I do not find in the latest release. I think this is a folder that some zip programs add. Could it be that you downloaded the release, unzipped it and then zipped it again to compute the MD5 hash? If so, please download the release and run the MD5 hash directly without unzipping.
