### ISSUE TITLE
after clearing, next command run is not correct

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151217]
![Screen Shot 2022-06-03 at 7 40 12 AM](https://user-images.githubusercontent.com/29464607/171876606-0354aaa4-0004-4636-b75a-291267720476.png)

**Comment by meganrogge** [comment]
probably same root cause as #145148

**Comment by meganrogge** [comment]
looks like on clear, we need to trigger `handlePromptStart` and `handleCommandStart`. neither of those are happening

**Comment by meganrogge** [comment]
PR incoming

**Comment by Tyriar** [comment]
@meganrogge that should be happening when the new prompt is written, do we need to somehow retain it instead?

**Comment by meganrogge** [comment]
when I run clear with escape sequence logging, nothing is parsed by xterm.js even though the prompt shows up

**Comment by meganrogge** [comment]
see discussion in my PR. I think I know what's happening. the first prompt isn't cleared when you run `clear`
