### ISSUE TITLE
Check for Updates button not doing anything on VSCode snap

### ISSUE THREAD

**Issue by joeljosedev** [microsoft/vscode#151281]
The Check for Updates button in the Manage menu does not do anything on the Snap version of VSCode.

![image](https://user-images.githubusercontent.com/53969297/172041081-9f673315-858f-4ae2-b0bf-8b2d3bf123a1.png)

### VSCode Info

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:23:40.286Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.15.41-1-MANJARO snap

**Comment by joaomoreno** [comment]
Can you run F1, `Developer: Show Logs...`, `Main` and then show me what comes up when you run `Check for Updates...`?

**Comment by joeljosedev** [comment]
It seems to be checking for updates in the background, but there is no visual feedback for the user.

Here are the logs:

```
[2022-06-08 19:39:41.890] [main] [info] update#setState checking for updates
[2022-06-08 19:39:41.893] [main] [info] update#setState idle
```

**Comment by joeljosedev** [comment]
Right, but other VSCode packages show a pop-up saying that the latest version of VSCode is installed when the ```Check for Updates``` button is clicked.

It would be nice if the Snap showed that pop-up as well imo. Or maybe remove that option entirely since all Snaps update automatically.
