### ISSUE TITLE
Icons don't load on Firefox with adblocker

### ISSUE THREAD

**Issue by DillonB07** [microsoft/vscode#151293]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: Web - vscode.dev
- OS Version: - macOS Catalina 10.15.7
- Browser - Firefox Dev Edition - 102.0b3

When I visit the online version, the icons don't load. Here's a screenshot of what I can see:
<img width="2045" alt="Screenshot 2022-06-05 at 16 59 09" src="https://user-images.githubusercontent.com/83948303/172059491-51f3d296-70b1-4c02-82fc-fad05a1aa076.png">

Steps to Reproduce:

1. Open vscode.dev in Firefox Dev ed
2. Icons don't load after waiting for the page to load.

**Comment by zurgeg** [comment]
Same here, FF Stable 100.0.0 on Windows 11

**Comment by sbatten** [comment]
are there any errors in the console? It looks like codicons specifically are not loading, but I don't repro this on FF on W11 myself

**Comment by DillonB07** [comment]
Sorry for the late response! I saw the response and completely forgot to reply. Here's an export of my FireFox logs.
[console-export-2022-6-12_19-53-15.txt](https://github.com/microsoft/vscode/files/8886547/console-export-2022-6-12_19-53-15.txt)

It's worth mentioning that I have the CorsEverywhere extension enabled because I'm unable to load a GH Codespace without it.
However, when I went to https://github.dev all of the icons loaded perfectly fine. This could just be an issue with Codespaces?

**Comment by sbatten** [comment]
Relevant line in log:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://main.vscode-cdn.net/stable/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6. (Reason: CORS request did not succeed). Status code: (null).
downloadable font: download failed (font-family: "codicon" style:normal weight:400 stretch:100 src index:0): bad URI or cross-site access not allowed source: https://main.vscode-cdn.net/stable/4af164ea3a06f701fe3e89a2bcbb421d2026b68f/out/vs/base/browser/ui/codicons/codicon/codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6```

**Comment by DillonB07** [comment]
No. https://insiders.vscode.dev <https://insiders.vscode.dev/> and https://vscode.dev <https://vscode.dev/> both work perfectly. I didn’t think to test these when posting the issue sorry. I thought that there wouldn’t be any difference between a GH Codespace and the official web version.

**Comment by DillonB07** [comment]
Sorry. I can see what the issue was with my last comment. I think I had my Cors Everywhere extension enabled. I've checked each version of online vscode and here are the results.

| Version | Works |
|-|-|
| https://vscode.dev | No |
| https://insiders.vscode.dev | No |
| https://github.dev| Yes |
| GitHub Codespaces | No |

**Comment by zurgeg** [comment]
> Sorry. I can see what the issue was with my last comment. I think I had my Cors Everywhere extension enabled. I've checked each version of online vscode and here are the results.
> Version 	Works
> https://vscode.dev 	No
> https://insiders.vscode.dev 	No
> https://github.dev 	Yes
> GitHub Codespaces 	No

Can replicate the same problem on my end.

**Comment by zurgeg** [comment]
> Apparently, this was an issue with an adblocker. Maybe a feature could be implemented asking the user to disable their adblocker for the online version if it detects that they're using one? I'm using [Adblocker Ultimate](https://addons.mozilla.org/en-US/firefox/addon/adblocker-ultimate/).

I use uBO, turning it off solves nothing 🤨

**Comment by zurgeg** [comment]
Cleared cookies, problem solved until next reload. I just blocked cookies for vscode.dev

**Comment by zurgeg** [comment]
Now I get a fatal error 🤨

**Comment by zurgeg** [comment]
Just says "Fatal error, please check devtools"

**Comment by DillonB07** [comment]
and what is in the devtools?

**Comment by zurgeg** [comment]
Seems to just be an issue with cookies being blocked and raising errors. Likely just a problem on my end.

**Comment by joaomoreno** [comment]
It doesn't make sense to write a feature that suggests users to disable ad blockers: that defeats the entire purpose of an ad blocker, which is supposed to block unwanted ads, including one promoting ad blocking disablement.

I suggest filling an issue to this specific ad blocker.
