### ISSUE TITLE
Don't backup text file when auto save is enabled

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15129]
Currently there is no conditional for this so backups are taken even when auto save is enabled.

**Comment by bpasero** [comment]
I wonder if this is true for all auto save configs we have. Some people might expect hot exit to work even if auto save is on (e.g. the auto save that only saves on focus lost).

**Comment by bpasero** [comment]
I pushed a change to not backup on shutdown when auto save is on but I guess we still need to decide what to do with backing up after a file gets dirty.

**Comment by Tyriar** [comment]
@bpasero good point with the focus lost case. I'm not sure I agree about the disabling hot exit completely change that you did, untitled files don't get auto saved and it would certainly be convenient to trigger hot exit in that case.

**Comment by bpasero** [comment]
@Tyriar I [fixed](https://github.com/Microsoft/vscode/commit/fff5e49ebc6d08b11038ff37633382cc8b5e9fdd) that

**Comment by Tyriar** [comment]
Here are the options I can think of:

a. Leave as is, always saving backups regardless of auto save configuration. If the auto save delay is smaller than the backup delay, the content change event will be canceled and no backup will occur. If the auto save delay is larger than the backup delay, this will delete the backup that was saved shortly.
b. Prevent backups presisting to disk at the `BackupFIleService` level when `"files.autoSave": "afterDelay"`. The only issue I see with this is if `files.autoSave` is changed to something other than `afterDelay`, current dirty files will not be backed up until a change is made or shutdown (when all files are backed up). So this edge case may would to be handled for crash recovery.

**Comment by bpasero** [comment]
I am ok with option a).

**Comment by Tyriar** [comment]
I think we can close this off then as the fix for https://github.com/Microsoft/vscode/issues/15748 properly cancels content change events after a save now.

**Comment by bpasero** [comment]
Sounds good.
