### ISSUE TITLE
Bash Version from inside the script is old and not what was explicitly defined in VSCODE settings

### ISSUE THREAD

**Issue by lamyergeier** [microsoft/vscode#151230]
Please refer: [[Bash Version from inside the script is old and not what was explicitly defined in VSCODE settings · Issue #150871 · microsoft/vscode](https://github.com/microsoft/vscode/issues/150871)](https://github.com/microsoft/vscode/issues/150871)

This issue was closed without any explanation and the issue is not the duplicate as mentioned by the assignee.  The assignee didn't even replicate the steps as written in the issue.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: MacOS 12.4

Steps to Reproduce:

1. Install Latest Bash from homebrew. Change the default terminal for MAC OS from System preferences and using chsh command on terminal
2. Change the terminal settings in VSCODE

```json
    "terminal.integrated.profiles.osx": {
        "new bash": { // profile name
            "path": "/usr/local/bin/bash"
        }
    },
    "terminal.integrated.defaultProfile.osx": "new bash",
```

3. Now VScode shows 

```bash
$ echo $BASH_VERSION
6.1.16(1)-release
```

4. Run a bash script from VSCODE terminal

```bash
cat a.sh
#!/usr/bin/env bash
echo $BASH_VERSION
```

It prints the old version 3 of Bash.

## Issues

The bashscript uses old version of Bash.

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/docs/editor/integrated-terminal#_why-are-there-duplicate-paths-in-the-terminals-path-environment-variable-andor-why-are-they-reversed

**Comment by lamyergeier** [comment]
@Tyriar  I read the URL that you referenced above, my ~/.bash_profile has just one line `[ -r "${HOME}/.bashrc" ] && . "${HOME}/.bashrc"`. And my new shell is defined as follows

```
    "terminal.integrated.profiles.osx": {
        "new bash": { // profile name
            "path": "/usr/local/bin/bash"
        }
    },
    "terminal.integrated.defaultProfile.osx": "new bash",
```

But I am still facing the problem.

**Comment by lamyergeier** [comment]
@Tyriar We can see that `$PATH` and `$SHELL` are the same in both of the cases. What should I do?

**Comment by lamyergeier** [comment]
@Tyriar  Could you please comment on this? I desparately need to switch to new bash on iterm used by VScode on MacOS.

**Comment by Tyriar** [comment]
When you run the script it uses the bash version you specify in the shebang:

```
#!/usr/bin/env bash
```

Remove that and it should use the outer shell. So you'd want to look into how shebangs work.
