### ISSUE TITLE
Programming/Markup language-specific uncommon character model

### ISSUE THREAD

**Issue by hb20007** [microsoft/vscode#151287]
I write a lot of markup files such as HTML and I often use typographic single (curly) quotation marks (`‘’`), which look better than just using `''`.

The implementation of the Unicode highlighting feature (#138071) has caused unwelcome warnings to appear in relation to these characters:

![Screenshot 1](https://user-images.githubusercontent.com/8860322/172048000-58a7b7c8-0f2c-4419-9d76-f64e092ba64b.png)

![Screenshot 2](https://user-images.githubusercontent.com/8860322/172048068-5f866dc4-df60-4cce-9a51-8bd4ac89bd05.png)

These are the current settings which I can adjust:

![Screenshot 3](https://user-images.githubusercontent.com/8860322/172048083-b9f6148a-63f7-4ee5-bf4a-0d65ca8a24a9.png)

Currently, there is no feature to exclude these characters from being highlighted only in certain file types, such as markup. I do not want these characters to be highlighted in `.html` files, where there is no chance of confusing them with characters like the backtick, however, I still want them to be highlighted in source code files like `.js`, where this feature is actually useful.

Also, ideally this should be the default configuration since these characters should not cause any issues in `.html` or other markup files.

**In general, I would like to propose programming/markup language-specific customization on top of the model of what are considered to be uncommon characters in source code. Just like these characters should be considered common to `.html` files, I suppose that other false positives might occur in other programming or markup languages that use unconventional characters as part of their syntax or as part of common usage.**

**Comment by hediet** [comment]
This is already supported - you can use Language-specific editor settings.
