### ISSUE TITLE
SCM view does not list repos in folder containing multiple git repos

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151249]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have a directory containing multiple cloned git repos (I have ~40), which is not itself a git repo
2. Open that directory in VS Code
3. :bug: 1: can't repro this anymore but I saw some strange behavior where, while the repos were being discovered and added to the SCM viewlet, occasionally the existing discovered repos would disappear from the list, and get replaced by a new set of repos
4. :bug: 2: after all repos have been discovered, all the repos disappear from the source control panel and the SCM view reflects just the last repo that was discovered

**Comment by elieux** [comment]
I'm seeing the same issue. I have a workspace mentioning around 25 directories, one of which isn't a repo, while the rest are each a Git repo. When I open the workspace and switch to the SCM panel, I see the repos being added one by one, but at a specific point the ones already loaded disappear. The process continues, so in the end, I see only the bottom "half" of the repos. The breaking point seems to be consistent, as observed during around 5 retries. The Git log doesn't seem to show anything too suspicious. I'm able to show the repositories again using View & Sort ⇾ Repositories, but after a restart, it's back to the half-shown state.

After I closed all the editor tabs and restarted, it seems to have fixed itself, so it might be related.

> Version: 1.67.2
> Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
> Date: 2022-05-17T18:15:52.058Z
> Electron: 17.4.1
> Chromium: 98.0.4758.141
> Node.js: 16.13.0
> V8: 9.8.177.13-electron.0
> OS: Windows_NT x64 10.0.19043

**Comment by lszomoru** [comment]
@elieux, are you still able to reproduce the issue?
If so, could you please create a recording (https://gifcap.dev)? Thank you!

**Comment by lszomoru** [comment]
Closing this as part of our housekeeping effort. @elieux, please feel free to reopen if you are still able to reproduce this issue.
