### ISSUE TITLE
render a warning indicator when an image path is not found

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151244]
![Screen Shot 2022-06-03 at 12 33 44 PM](https://user-images.githubusercontent.com/29464607/171937149-2852e5db-d7a9-4587-96ae-062449752ece.png)

It's clear that this is supposed to be an image, but I don't see it appearing in the preview. I wonder if we should show a warning instead of nothing here?

**Comment by mjbvz** [comment]
This is caused by markdown-it adding empty `alt` tags to images: https://github.com/markdown-it/markdown-it/issues/885
