### ISSUE TITLE
Visual Studio Code Arm 64 on Ubuntu 20.04.4 LTS Crashes on Start

### ISSUE THREAD

**Issue by atifhalim** [microsoft/vscode#151279]
Does this issue occur when all extensions are disabled?: I don't know what this means

- VS Code Version: code_1.67.2-1652811872_arm64.deb
- OS Version: Ubuntu 20.04.4 LTS

Steps to Reproduce:

1. Install the version code_1.67.2-1652811872_arm64.deb on Ubuntu 20.04.4 LTS
2. Click on the blue Visual Studio Icon.  Nothing happens however when I look at the processes running I see the following:

![image](https://user-images.githubusercontent.com/67847861/172034638-d7f3746b-8098-45b1-b733-17ad26694b68.png)

**Comment by deepak1556** [comment]
Does the issue happen with latest insiders https://code.visualstudio.com/insiders , should be addressed with https://github.com/microsoft/vscode/pull/145527
