### ISSUE TITLE
workspace.findFiles with exclude pattern behaves differently than documented

### ISSUE THREAD

**Issue by kryops** [microsoft/vscode#151211]
- VS Code Version: 1.67.2
- OS Version: macOS 12.4

The current API documentation for `workspace.findFiles()` contains the following description for the `exclude` param:

> A [glob pattern](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) that defines files and folders to exclude. The glob pattern will be matched against the file paths of resulting matches relative to their workspace. When `undefined`, default file-excludes (e.g. the `files.exclude`-setting but not search.exclude) will apply. When `null`, no excludes will apply.

(via https://code.visualstudio.com/api/references/vscode-api)

However, the `files.exclude` setting does not only seem to be applied by default (or when using `undefined` as documented), but also when specifying a string exclude pattern. Only when explicitly specifying `null`, the setting is not applied.

In my use case I want to find some files that are usually hidden from the developer (thus I don't want `files.exclude` to be applied), but I want to exclude some large directories like `node_modules` and `.git` from the search for better performance:

```ts
const files = await vscode.workspace.findFiles('**/.development/_typing.d.ts', '**/{node_modules,.git}');
```

This won't find my files - it only works after replacing my exclude pattern with `null`.

Is this a bug? Or is the documentation just not clear for this case?

Relevant code:
- https://github.com/microsoft/vscode/blob/1805df1a11c3f96775d3a9d00c9a420c5491711f/src/vs/workbench/api/common/extHostWorkspace.ts#L442
- https://github.com/microsoft/vscode/blob/1805df1a11c3f96775d3a9d00c9a420c5491711f/src/vs/workbench/api/browser/mainThreadWorkspace.ts#L149
- https://github.com/microsoft/vscode/blob/1805df1a11c3f96775d3a9d00c9a420c5491711f/src/vs/workbench/services/search/common/queryBuilder.ts#L334

Related issues:
- https://github.com/microsoft/vscode/issues/48674
- https://github.com/microsoft/vscode/issues/101889

Thanks for looking into it!

**Comment by roblourens** [comment]
To me, it's implied that `files.exclude` is applied by default, then we describe the difference between null/undefined. To me, it would be very confusing to not apply the default excludes when you specify a query, but then to add extra excludes when you pass undefined. In any case, this does lack flexibility for cases like yours, and we do need to revamp this API. I think that's covered by the other issues you found.
