### ISSUE TITLE
Opening a file should ignore casing if file already opened (Win, Mac)

### ISSUE THREAD

**Issue by jstarks** [Microsoft/vscode#15120]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Insider Preview

Steps to Reproduce:

1. Create a file Foo.cpp. Have it open in a tab.
2. Run a task that emits a problem for "foo.cpp" instead of "Foo.cpp".
3. Double click the problem in the error pane.

Expected: Window switches to the Foo.cpp tab.

Actual: Window creates a new foo.cpp tab and switches to it. Foo.cpp is still open, too.

**Comment by bpasero** [comment]
While we can fix this in VS Code with quite some work, I would argue that this should also be reported to any extension that produces errors in casing that does not match the casing on disk.

**Comment by jstarks** [comment]
@bpasero, I'd agree if this were an extension. But in this case, it's the output from my build tools, which I do not control.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
