### ISSUE TITLE
Revert changes by arrows in side-by-side diff editor

### ISSUE THREAD

**Issue by Mingpan** [microsoft/vscode#151206]
Currently reverting changes in side-by-side diff view requires more than one clicks and seems not very discoverable. Also, it's not available for delete changes (related issue #98096). 

Instead, I think we may be able to use the margin space and place some arrows to conveniently revert changes by one click. Example:
![arrow-revert](https://user-images.githubusercontent.com/15076498/171839710-b0f5eb4d-e9ae-44ca-9b7e-6423efe416d2.gif)

If the feature is considered helpful, I'd also be glad to send a PR for it.

**Comment by JamesHutchisonCarta** [comment]
I would love to see this feature.

@joaomoreno did you close this as "not planned" by mistake?

**Comment by JamesHutchisonCarta** [comment]
I do notice that 3-way merge is in-progress, will it address this issue?

https://github.com/microsoft/vscode/issues/37350#issuecomment-1098132423

**Comment by JamesHutchisonCarta** [comment]
I'm under the impression that @Mingpan already wrote the code and is offering to spend the time cleaning it up for a PR, based on the screen capture. What is the ETA on 3-way-merge? If it's months out, incorporating this would be helpful.

**Comment by Mingpan** [comment]
I think 3 way merge is for merging changes (from different branches). The feature I proposed is more for reverting changes in the same file. So in my opinion they seem to be solving different problems.
