### ISSUE TITLE
Terminal Auto focus

### ISSUE THREAD

**Issue by SilentJs** [microsoft/vscode#151288]
After creating 2+ terminal tabs It would be good if it would **focus on the terminal automatically** after clicking on the terminal tab 
currently we have to create new tabs , click on the terminal tab and then click on the terminal window
If the last step would be done automatically it would be amazing

**Comment by Tyriar** [comment]
Double clicking the tab will focus it, you can also set `"terminal.integrated.tabs.focusMode": "singleClick"` for what you're after
