### ISSUE TITLE
Can't find in selection when selection is a single line

### ISSUE THREAD

**Issue by bpaczkowski** [Microsoft/vscode#15125]
- VSCode Version: both 1.7.1 and 1.8.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Select part of text within a single line.
2. Find in selection is greyed out and cannot be clicked.

**Comment by alexandrudima** [comment]
Not sure if it's a feature request or a bug :). I don't think this ever worked.

**Comment by bpasero** [comment]
@alexandrudima seems to work ok but please see that we still seem to highlight the search results if matching in other lines above the line I am searching in (see the decoration):

![image](https://cloud.githubusercontent.com/assets/900690/23305869/166fe4d4-faa1-11e6-8993-d8c16324a449.png)

**Comment by bpasero** [comment]
We seem to do the same when selecting multiple lines.
