### ISSUE TITLE
Silicon M1 Can't load library: ~/.openjfx/cache/17-ea/libprism_es2.dylib

### ISSUE THREAD

**Issue by hasen6** [microsoft/vscode#151227]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: 12.3

Steps to Reproduce:

1. Open Java Project with javafx-controls version 17-ea+8 or higher

My projects all open fine in Intellij and everything works but in vscode they crash with error:

```
Loading library prism_es2 from resource failed: java.lang.UnsatisfiedLinkError: Can't load library: /Users/hasen/.openjfx/cache/17-ea/libprism_es2.dylib
java.lang.UnsatisfiedLinkError: Can't load library: /Users/hasen/.openjfx/cache/17-ea/libprism_es2.dylib
```
If I set javafx-controls version 17-ea+7 it manages to load but there is no sound playback from mediaplayer.

**Comment by sandy081** [comment]
Please file issue against Java extension
