### ISSUE TITLE
zsh: parse error: condition expected: != in Codespaces integrated terminal

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151257]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open a Codespace
2. Open an integrated terminal
3. :bug: see "zsh: parse error: condition expected: !="

![image](https://user-images.githubusercontent.com/30305945/171977113-45191f48-c06b-468a-8b2a-3a8af5f64689.png)

Note, I don't normally use zsh so have no idea if this is a regression. just happened to see this while verifying https://github.com/microsoft/vscode/issues/151214

**Comment by meganrogge** [comment]
Seeing `__vsc_update_prompt:3: PREFIX: parameter not set` in the latest insider's in desktop for `zsh`

**Comment by meganrogge** [comment]
Codespaces
![Screen Shot 2022-06-06 at 8 26 06 AM](https://user-images.githubusercontent.com/29464607/172192733-ec94c8c5-c3ad-45cb-bc6b-d71a95c95fe2.png)

Desktop
![Screen Shot 2022-06-06 at 8 27 13 AM](https://user-images.githubusercontent.com/29464607/172192744-50aebb7a-d2e0-42f3-b67a-05d66157f8d0.png)

**Comment by meganrogge** [comment]
Happens with any repo in codespaces when you create a `zsh` terminal 

@github/codespaces

**Comment by meganrogge** [comment]
This is not a new issue (reproduces in a codespace based on stable) and doesn't reproduces in all repositories.

**Comment by meganrogge** [comment]
`ZDOTDIR` being set to `''` is not the issue bc setting it to something does not resolve this

**Comment by Tyriar** [comment]
Tracked by codespaces team
