### ISSUE TITLE
Confusing shell integration decoration for enter

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#151239]
The decoration for `enter` is confusing as it shows dark dot and sometimes gray dot

<img width="629" alt="image" src="https://user-images.githubusercontent.com/876920/171924150-96eebca0-5207-443e-81b3-ec96093bd854.png">

<img width="634" alt="image" src="https://user-images.githubusercontent.com/876920/171924165-5d541087-b996-40fd-aaee-012445d79249.png">

<img width="656" alt="image" src="https://user-images.githubusercontent.com/876920/171924210-02d63c22-fd6d-4f80-b9e0-8e6396a592be.png">

Note that on the last image, the first two commands have gray dot decoration.

**Comment by meganrogge** [comment]
assuming this is bash, this will be fixed by #151232

**Comment by rebornix** [comment]
@meganrogge right, I was using bash. Feel free to close this issue if it's dup.

**Comment by meganrogge** [comment]
fixed with #151232

**Comment by meganrogge** [comment]
made it a bug so it gets verified

**Comment by joyceerhl** [comment]
@meganrogge I assume this should be closed?

**Comment by meganrogge** [comment]
@joyceerhl do you know if the above is the right syntax to ensure that it gets the `insiders-released` label when appropriate?

> fixed with https://github.com/microsoft/vscode/commit/36bedff2d1dc349047a0a241435874f4dbc17fef

**Comment by joyceerhl** [comment]
I think it's `\closedWith`:
https://github.com/microsoft/vscode/blob/1e5cffe81b696ea25420b1ce7ad15d577986cebc/.github/commands.json#L180
