### ISSUE TITLE
Cannot execute git

### ISSUE THREAD

**Issue by eedahl** [Microsoft/vscode#15124]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Attempting to use the integrated git interface. Here's a screenshot of my developer console
https://gyazo.com/3616bfe6b0ce0d45f0d6223805ca53a6
The path looks wrong, but I can't configure it.

**Comment by joaomoreno** [comment]
What's the name of the folder you have open in Code?

**Comment by eedahl** [comment]
The folder name is sge
Full path, D:/Dropbox/dev/sge

**Comment by joaomoreno** [comment]
Can you use Process Hacker (or another process monitor) to search for "git" in your list of running processes, find the Code.exe that matches it and show me the full command line it is running with?

**Comment by eedahl** [comment]
Here you go!
https://gyazo.com/7e57172983c3821bfe68399f71c866f7

**Comment by joaomoreno** [comment]
Odd, everything looks OK to me. Does `git status` work fine from a Command Prompt?

**Comment by eedahl** [comment]
https://gyazo.com/beb104cc573e452661f0d7a70245f9f1

**Comment by joaomoreno** [comment]
There seems to be an issue with your git. Which version do you have install? Can you make sure to get the latest? https://git-scm.com/

**Comment by eedahl** [comment]
Updating, I did it again:

Running git status from the git shell works fine:
https://gyazo.com/5f549025802561fcc867899095f5cb59
Running git status from vscode and cmd is bust:
https://gyazo.com/adb5f05e1b0de7425e72eacd1686ff15
Could it be %path% related?
https://gyazo.com/fde8f983e53308c60908ef23691f3de2

**Comment by joaomoreno** [comment]
http://stackoverflow.com/questions/14774159/git-warning-unable-to-access-p-gitconfig-invalid-argument

**Comment by eedahl** [comment]
"set HOME=" fixes it for the shell, but VSCode doesn't quite catch on
https://gyazo.com/346feab71d08e60a97acce88b5391f24

**Comment by eedahl** [comment]
Setting a global environment HOME to "D:\Dropbox\dev" resolved this issue. It was, for whatever reason, set globally to "D:\Dropbox\dev"" (sic), which must be on my end.

Maybe it would make sense if vscode provided some diag on the HOME variable, since googling around it seems others has this problem too. Thanks either way!

**Comment by joaomoreno** [comment]
Good to know you're out of it! Since it's not a problem with VS Code itself, but with Git itself, let's not do anything. The issue remains here for people to find it in searches in the future.
