### ISSUE TITLE
Selected files deletion

### ISSUE THREAD

**Issue by tetrys** [microsoft/vscode#151219]
Issue Type: <b>Bug</b>

1. Select multiple files in EXPLORER with "Shift" or/and "Ctrl".
2. Unselect one or more files with "Ctrl".
3. Try to delete the files by pressing "Del" or "Shift+Del".
4. The Dialog asks for confirmation of deletion of the last clicked (and unselected) file and deletes only this file.

> Right mouse click on the selected files and "Delete" on the menu does not reproduce that.

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6440HQ CPU @ 2.60GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (14.05GB free)|
|Process Argv|--crash-reporter-id 3c1c6cc1-986e-4d1c-996b-fe137da52f8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
pascal|ale|9.5.0
pascal-formatter|ale|2.6.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
scad|efb|1.0.1
prettier-vscode|esb|9.5.0
php-intellisense|fel|2.3.14
vscode-firefox-debug|fir|2.9.6
better-cpp-syntax|jef|1.15.14
csharp|ms-|1.25.0
python|ms-|2022.6.3
vscode-pylance|ms-|2022.6.0
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.10.5
cpptools|ms-|1.9.8
cpptools-extension-pack|ms-|1.2.0
hexeditor|ms-|1.9.6
powershell|ms-|2022.5.1
vscode-typescript-tslint-plugin|ms-|1.3.4
team|ms-|1.161.1
oracledevtools|Ora|21.4.0
java|red|1.7.0
vscode-xml|red|0.20.0
vscode-hexdump|sle|1.8.1
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.41.0
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.23.0
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.2
php-debug|xde|1.26.1

(1 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
This is because when you right click to delete you move focus to the selected item.

We try to delete the focused item. If the item that is focused is also selected we delete all selected items. Otherwise we delete just the selected items.

You can see this by pressing up the up arrow after unselecting an item to focus one your selected items. Then pressing the delete key will prompt you to delete all selected files.

**Comment by tetrys** [comment]
Thanx for your answer. It's not exactly the way it works in system file explorers (Windows File Explorer, Finder in macOS...) and in many other IDEs. I think it should at least be in accordance with its own right click menu command. But I have to adapt to that.
