### ISSUE TITLE
Make vscode.dev embeddable, using IFrame API for passing data

### ISSUE THREAD

**Issue by TJKoury** [microsoft/vscode#151369]
I am developing an in-browser editor app [that creates code from Flatbuffer IDLs](spacedatastandards.org).  Working on the next version that is supposed to have GitHub integration. Would make life much easier if I could just embed this site.  

The hooks in the editor take the source and then throw it into a WebAssembly version of the FlatBuffers compiler.  It would be much easier to just pass files from the GitHub repo, and allow people to submit pulls directly from the editor.

**Comment by joaomoreno** [comment]
This is beyond the scope of vscode.dev, we explicitly do not want it to be an iframe anywhere.

With that being said, we have work planned that will help you use vscode.dev as the entrypoint for your own experiences.
