### ISSUE TITLE
VS Code Freezes when launched in debug mode

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#151322]
Coming back from vacation, on main with everything fresh, I tried debugging with the "Launch VS Code" configuration on macOS. The window opens, but then almost immediately (when the debugger attaches?) freezes and must be force-quit.

This seems to be timing-related, since if I add `trace: true` to the launch config (which slows down the debugger slightly) then it runs without issues.

**Comment by deepak1556** [comment]
I think the root issue was identified to be stdout buffer getting filled and addressed since then.
