### ISSUE TITLE
`edit.delete` will move the cursor to the beginning of the line

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#15139]
- VSCode Version:
- OS Version:

`edit.delete` will move the cursor to the beginning of the line. As we hijacked Backspace in Vim ext so currently in Insiders build, Backspace is not usable.

A simple extension to demonstrate this issue is as below

```
export function activate(context: vscode.ExtensionContext) {

    let disposable = vscode.commands.registerCommand('extension.sayHello', async () => {
        vscode.window.activeTextEditor.edit((edit)=> {
            let pos = vscode.window.activeTextEditor.selection.active; 
            edit.delete(new vscode.Range(pos, new vscode.Position(pos.line, pos.character - 1)));
        });
    });
    
    context.subscriptions.push(disposable);
}
```

You can input `abcdef` and then run this command and you can see that cursor is put at the beginning of the line after it's executed.

**Comment by alexandrudima** [comment]
Sorry about that, it is already fixed on master. (fixed with 474aab0a18968059691ddff3d5ad5bc022805418)
