### ISSUE TITLE
Hot-exit should focus on previously focused file on restart

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15132]
- VSCode Version: c2418f46d20464a893dc5db6449e9d79766eadc4
- OS Version: macOS 10.11.6

![hot](https://cloud.githubusercontent.com/assets/4033249/20078290/c36be276-a4f4-11e6-943c-19f5caf9d9d5.gif)

**Comment by Tyriar** [comment]
Root cause in https://github.com/Microsoft/vscode/issues/14116
