### ISSUE TITLE
Windows/pwsh shell integration doesn't work when VS Code's install path has a space

### ISSUE THREAD

**Issue by frg2089** [microsoft/vscode#151323]
Issue Type: <b>Bug</b>

My VSCode was installed on "D:\Program Files\Microsoft VS Code".
And when I start a new terminal session. The PowerShell have an error message.

```json
{
  "terminal.integrated.shellIntegration.enabled": true
}
```

```
.: The term 'd:\Program' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I see the command arguments in Task Manager is:

```
path\to\pwsh.exe -noexit -command ". \"d:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\contrib\browser\media\shellIntegration.ps1\""
```

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.25131
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|17.94GB (4.74GB free)|
|Process Argv|--crash-reporter-id 22f0d1eb-04cb-4265-8cfa-3caac6ef1ed1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-caniuse|aka|0.5.4
preview-mp4|ana|0.0.1
file-nesting|ant|1.0.0
vscode-zipfs|arc|3.0.0
es6-string-css|bas|0.1.0
comment-tagged-templates|bie|0.3.1
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.47.0
ini-for-vscode|Dav|0.0.4
vscode-eslint|dba|2.2.2
docs-markdown|doc|0.2.111
gitlens-insiders|eam|2022.6.405
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.25
fast-tagged-templates|und|0.1.0
vscode-firefox-debug|fir|2.9.6
codespaces|Git|1.8.2
copilot|Git|1.25.6056
vscode-pull-request-github|Git|0.42.0
todo-tree|Gru|0.0.215
output-colorizer|IBM|0.1.2
comment-translate|int|2.1.0
reg|ion|1.1.0
vscode-edit-csv|jan|0.6.10
chat|kar|0.35.0
fast-snippets|kin|1.6.2
vscode-fix-checksums|leh|1.1.0
csharp-colors|log|0.1.8
eslint-rules-zh-plugin|mag|0.1.0
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.17
vscode-docker|ms-|1.22.0
vscode-language-pack-zh-hans|MS-|1.67.3
vscode-dotnet-runtime|ms-|1.5.0
vscode-edge-devtools|ms-|2.0.0
remote-ssh|ms-|0.80.0
remote-wsl|ms-|0.66.3
azure-account|ms-|0.10.1
hexeditor|ms-|1.9.6
live-server|ms-|0.2.12
vs-keybindings|ms-|0.2.1
vscode-typescript-next|ms-|4.8.20220605
vsliveshare|ms-|1.0.5597
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vscode-xml|red|0.20.0
vscode-yaml|red|1.7.0
background|sha|1.1.31
wav-preview|suk|2.0.2
vscode-icons|vsc|11.12.0
literally-html|web|0.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by Tyriar** [comment]
This seems to work fine for me, I tested on both 1.68.1 and latest insiders
