### ISSUE TITLE
Add separation between the text and the scroll bar on the right

### ISSUE THREAD

**Issue by dimitry-ishenko** [microsoft/vscode#151366]
## Environment data

-   VS Code version: 1.67.2
-   Jupyter Extension version (available under the Extensions sidebar): v2022.4.1021342353
-   Python Extension version (available under the Extensions sidebar): v2022.6.3
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22.04
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): N/A
-   Jupyter server running: Local

## Expected behaviour

Small separation between the text and the scroll bar on the right. For symmetry, it could be the same amount as on the left side.

## Actual behaviour

Text and other elements touch/spill onto the scroll bar. See below:

![overall](https://user-images.githubusercontent.com/2858291/172025683-3f379b8b-4d49-4258-8669-33c4b0c3cb32.png)

---
![1](https://user-images.githubusercontent.com/2858291/172025799-17c84a49-99ce-441b-a486-7cbfc58c43f4.png)

---
![2](https://user-images.githubusercontent.com/2858291/172025801-4388e1eb-9c9f-4339-8cff-e02ec1aef557.png)

---
![3](https://user-images.githubusercontent.com/2858291/172025802-b0d21258-741e-4b43-adfd-f32eb6bfcbcc.png)

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

1. Open any notebook that has markdown cells with a lot of text.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

**Comment by greazer** [comment]
scrollbar rendering is core code.

**Comment by greazer** [comment]
Is this only when running on vscode.dev? Or does it repro on desktop as well?

**Comment by dimitry-ishenko** [comment]
This is for desktop

**Comment by rebornix** [comment]
let's merge this issue into https://github.com/microsoft/vscode/issues/149264
