### ISSUE TITLE
Experimental Paste Action: Better Metadata

### ISSUE THREAD

**Issue by jinu-jang** [microsoft/vscode#151372]
Within the clipboard metadata is the sourceURL sometimes.
This seems to be an OS/Browser specific feature, and does not seem to be a universal protocol, so not sure how low level we have to go for this.

Taking a look at the clipboard data through the handy FreeClipboardViewer ([link](https://freeclipboardviewer.com/windowsclipboard/))
![image](https://user-images.githubusercontent.com/11640155/172251939-a9b44bf9-a882-4069-82fe-5efbfdf7c7f0.png)

The sourceURL is available for view, however doing `dataTransfer.get('text/html')` only retrieves the `<html>...</html>` section and not any of the other metadata on top.

**Comment by mjbvz** [comment]
Not sure what that other data is but I believe our existing behavior matches how `DataTransfer`from the DOM apis works. For `text/html` I only see a way to access the html content, not this additional metadata
