### ISSUE TITLE
Variables added in `vscode.window.createTerminal` are not included in the environment if shell integration is turned on

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#151343]
1. In a sample extension, add `vscode.window.createTerminal({ env: { HELLO: 'world' } }).show();`
2. Trigger that
3. Run `echo $HELLO` and notice the environment wasn't set

This also breaks the JS Debug Terminal and the node-terminal debug type. I hit this on zshell on OSX with shell integration turned on

**Comment by meganrogge** [comment]
`env` is missing from the slc when shell integration is enabled

![Image](https://user-images.githubusercontent.com/29464607/173089711-11c384f6-67bf-44a7-b9c9-95c61a1f39c0.png)

**Comment by meganrogge** [comment]
it's on the `processLaunchOptions` instead

**Comment by llgcode** [comment]
Hi,
I had a similar regression on our internal extension that open a terminal with preconfigured environement
