### ISSUE TITLE
Experimental Paste Action: View dataTransfer keys

### ISSUE THREAD

**Issue by jinu-jang** [microsoft/vscode#151371]
This is for the `dataTransfer` object passed in through the `DocumentPasteEditProvider.provideDocumentPasteEdits()` method.

Would be great if we could run `Object.keys(dataTransfer._map)` to view which keys the internal map for the object had.
Currently to find a property, I would just have to call `.get()` on the object with different MIME type strings until it returns a result.
This also makes it more or less impossible to find custom properties added on.

**Comment by mjbvz** [comment]
You can use `.forEach` to iterate through the data transfer item of all keys and values. Will consider adding a `.items` property to make it easier to iterate using a `for...of` loop

**Comment by mjbvz** [comment]
Duplicate of #151802
