### ISSUE TITLE
Experimental paste actions break some common cases

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#151326]
You may be aware of these, but just in case you aren't:

1. Turn on `"editor.experimental.pasteActions.enabled": true`
2. Have multiple selections, and paste. 🐛 Where previously the value was pasted into every selection, only the first selection gets the value
3. Without a selection, press ctrl+c to copy and line, then ctrl+v to paste it 🐛 Where previously the new line was pasted above the current line, it's now pasted at the cursor position

**Comment by jinu-jang** [comment]
Tagging on to this to report relevant copy-paste behavior bugs.
Apart from the full line copy paste scenario, there are problems with multi-cursor paste as well.

**Should:**
1. If number of lines of the text in the clipboard matches the number of selections active, one line of text is pasted per cursor.
2. Else, paste entire clipboard on every cursor location

**Current:**
1. Pastes full clipboard text to `activeSelections[0]`

**Comment by mjbvz** [comment]
The first issue should be mostly fixed. The one remaining problem is that multi-cursor copy+paste doesn't work as before (this is the case where you copy from X locations and the paste into X locations)

**Comment by liyuhang1997** [comment]
@mjbvz Another bug is that when turn on `"editor.experimental.pasteActions.enabled": true`

Open an md file, use the find command, and pasting some text.

The text will be pasted into the file instead of into the input box of the find command.

**Comment by mjbvz** [comment]
@liyuhang1997 Please open new issues for any other issues
