### ISSUE TITLE
Unclosable error message

### ISSUE THREAD

**Issue by jcward** [Microsoft/vscode#1513]
I've hit this error message (which could perhaps be a warning), and I know what's causing the error and don't really care about it. But there's no option to close the message.

![image](https://cloud.githubusercontent.com/assets/2192439/11921054/c468db0e-a73c-11e5-8a46-dd51e0de3072.png)

If it's easy, I'd add a 'Close' option to this error.

**Comment by bpasero** [comment]
@jcward we cannot provide a close action without user interaction because of data loss. When you click the compare button you can revert your changes with the one from disk.
