### ISSUE TITLE
Activity bar => disable; switch to zen mode; Esc; Activity bar always enabled

### ISSUE THREAD

**Issue by SamuelMarks** [microsoft/vscode#151302]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: Windows 10.0.19044

Steps to Reproduce:

1. Disable activity bar by clicking menu options;
2. Enable zen mode by clicking menu options;
3. Disable` zen mode by twice clicking <kbd>Esc</kdb>
4. See activity bar is back
5. See activity bar is unselected in menu option;
6. Try toggling (no change)

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/148862
