### ISSUE TITLE
Different coloured file icons for Golang just like TypeScript and JavaScript

### ISSUE THREAD

**Issue by Southclaws** [microsoft/vscode#151361]
I'm surprised I couldn't find any existing issues for this, TS/JS has this feature but Go does not.

<img width="130" alt="image" src="https://user-images.githubusercontent.com/1636971/172235230-32cdb77e-fa65-40f6-a15a-5064cc876540.png">

<img width="108" alt="image" src="https://user-images.githubusercontent.com/1636971/172235584-df1ded19-06ad-49f5-92f0-f0a2905ef9db.png">

Would be a huge help in large directories!

(I checked the vscode-icons extension and apparently it's impossible to implement via an extension...?)

**Comment by misolori** [comment]
This is handled by seti (see https://github.com/jesseweed/seti-ui/issues/514). Please file an issue over there and we can pull in the latest when it's in. Thanks!
