### ISSUE TITLE
Detect Indentation automatically after creating a new file and paste some code into it

### ISSUE THREAD

**Issue by mercury233** [microsoft/vscode#151304]
Issue Type: <b>Bug</b>

1. Turn _Editor: Insert Spaces_ and _Editor: Detect Indentation_ on
2. Create a new file, the indent mode is "Spaces: 4"
3. Paste some codes with tab as indentation
4. The language is automatically detected, but the indent mode is still "Spaces: 4"

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
copilot|Git|1.25.6056
format-html-in-php|rif|1.7.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by alexdima** [comment]
@mercury233 I'm having trouble reproducing:

https://user-images.githubusercontent.com/5047891/176767124-5b776f68-c64e-4968-b4d9-4bb730f3e5f5.mp4

**Comment by mercury233** [comment]
@alexdima I mean, the indent mode should be detected automatically on pasting to a blank file, at the same time as detecting language

**Comment by alexdima** [comment]
@bpasero The feature request here is that https://github.com/microsoft/vscode/blob/21ca44d35b0291a677188c70c70950aec47cb3ce/src/vs/workbench/browser/parts/editor/textResourceEditor.ts#L158 would also invoke `ITextModel.detectIndentation` (given the setting `editor.detectIndentation` is set to true).
