### ISSUE TITLE
Cannot exit empty workspace windows on Windows when hot exit is enabled

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15130]
May not be Windows-specific.

Steps to Reproduce:

1.  Open an empty workspace
2.  Try exit

![image](https://cloud.githubusercontent.com/assets/2193314/20077934/52f66fd0-a4f3-11e6-95c5-209ef905f2ba.png)

**Comment by octref** [comment]
Not really Win specific, I can repro on Mac:

![image](https://cloud.githubusercontent.com/assets/4033249/20078028/be43675c-a4f3-11e6-82c7-ceb706c2e2e2.png)

**Comment by rebornix** [comment]
Even if you have `hotExit` set as false, you can still run into this issue.

**Comment by Tyriar** [comment]
@rebornix yes that's expected as most of the backup logic still occurs when hot exit is on or off in order to support crash recovery. This issue is related to the recent change to enable multiple window restore not properly supporting the case when there is no current workspace.
