### ISSUE TITLE
vscode.dev Fatal Error due to CSP violation

### ISSUE THREAD

**Issue by oaustegard** [microsoft/vscode#151368]
Does this issue occur when all extensions are disabled?: NA - browser version

- VS Code Version: https://vscode.dev online browser version
- OS Version: Windows 10 Enterprise Version 21H2 OS Build 19044.1526
- Browser: Chrome Version 102.0.5005.63 (Official Build) (64-bit)

### Steps to Reproduce:

1. Launch https://vscode.dev

### Expected 
Should work,  online IDE should launch.

### Actual
Visual Studio Code
Fatal Error 🙈 Please check Developer Tools 🐱‍💻

![image](https://user-images.githubusercontent.com/3268739/172247923-8ef6cb0d-f889-4bd4-b4fb-3e544580d554.png)

In DevTools Console:
Refused to load the script 'https://main.vscode-cdn.net.x.692f2b430e656048a50a2610d95f3862f1c8.9270fa40.id.opendns.com/s/main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js?X-OpenDNS-Session=_692f2b430e656048a50a2610d95f3862f1c89270fa40_DMYBpK2k_' because it violates the following Content Security Policy directive: "script-src 'self' 'sha256-LRo4iyEUnhadNI3RM0L64AWQWqlyR8EkT2c7Nhq4WeA=' 'unsafe-eval' https://main.vscode-cdn.net https://vscodeweb.azureedge.net https://ms-vscode.vscode-unpkg.net https://ms-toolsai.vscode-unpkg.net http://localhost:*". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

and

(index):1 Error: Failed to load script: https://main.vscode-cdn.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/out/vs/loader.js
    at i.onerror ((index):1:3466)

![image](https://user-images.githubusercontent.com/3268739/172248114-9003887d-ee33-4150-9eac-671169ac0e89.png)

* Same error in Brave
* Same error in Edge
* IE just shows a blank page
* ![image](https://y.yarn.co/29a3f305-3766-43df-94aa-5987cedd6170_text.gif)

**Comment by joaomoreno** [comment]
@oaustegard Can you reproduce if you disable all your browser extensions? Particularly the one which rewrites URLs to use `*.x.*.id.opendns.com` instead of their original domain.

**Comment by oaustegard** [comment]
I don't have any extensions in Edge or Brave (unless Brave uses openDNS?)

But, ok - created a new profile in Chrome and removed their default offline Docs extension — now left with zero:
![image](https://user-images.githubusercontent.com/3268739/172388806-0c3587bd-96fc-4241-9894-119f488c3a4f.png)

vscode.dev still fails...
![image](https://user-images.githubusercontent.com/3268739/172389002-e753133d-2166-4889-b3ee-5f84d3710b3a.png)

**Comment by joaomoreno** [comment]
OK. If you have no browser extensions but it works on your phone, I have two theories:

- There's still something in your system altering the domain names of requests. This is obvious from your screenshots.
- Or, that thing lives in your network and affects anyone inside it. This would imply your phone isn't connected to the same network as your computer.

In any case, this isn't an issues with vscode.dev per-se or one that we can help you with. You have to find out what is changing the domain names in your requests.
