### ISSUE TITLE
Hot exit took Untitled-2 as Untitled-1

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15138]
- VSCode Version: c2418f46d20464a893dc5db6449e9d79766eadc4
- OS Version: macOS 10.11.6

![bug](https://cloud.githubusercontent.com/assets/4033249/20079410/63546b9c-a4f9-11e6-9507-7c23dfc7572d.gif)

**Comment by Tyriar** [comment]
This should be fixed by https://github.com/Microsoft/vscode/issues/14067#issuecomment-255542395
