### ISSUE TITLE
Replace all text within a selection

### ISSUE THREAD

**Issue by dominijk** [microsoft/vscode#151397]
Issue Type: <b>Bug</b>

This bug was found whilst working in a Jupyter notebook. 

Anticipated behaviour: Select all text Apple A, Opt+Apple F opens find replace box, then use the buttons to replace one or all.

Actual behvaiour: Can select all and open the dialogue box but no replacement made with either button

Select all text

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|64.00GB (5.36GB free)|
|Process Argv|--crash-reporter-id 175d79f6-ff1e-4595-9080-3c73d3b47db8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.39.0
boto3-ide|Bot|0.5.1
pgformatter|bra|1.18.0
vscode-postgres|cko|1.4.0
copilot|Git|1.25.6056
vscode-pull-request-github|Git|0.43.2022050511
gc-excelviewer|Gra|4.2.54
kite|kit|0.147.0
vscode-postgresql|ms-|0.3.0
black-formatter|ms-|2022.1.11521002
pylint|ms-|2022.1.11571003
python|ms-|2022.6.3
vscode-pylance|ms-|2022.6.0
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
geo-data-viewer|Ran|2.5.0
vscodeintellicode|Vis|1.2.21

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550

```

</details>

**Comment by rebornix** [comment]
@dominijk I'm not reproducing this locally? Can you offer a screen recording or anything similar to help troubleshoot?
