### ISSUE TITLE
Jumpy cursor in remote shell

### ISSUE THREAD

**Issue by cloudhan** [microsoft/vscode#151484]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.67.2 (user setup)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. On a remote machine, ~170ms delay.
2. Add following user setting:
   ```json
       "terminal.integrated.localEchoLatencyThreshold": 3,
   ```
3. Use `fish` shell 

<video src="https://user-images.githubusercontent.com/1279292/172542048-1ad934ee-299c-4920-bf9f-9d275ccca777.mp4"/>

**Comment by cloudhan** [comment]
@Tyriar I recently discover that this problem does not restrict to fish.

 Here is a bash reproduce:
<video src="https://user-images.githubusercontent.com/1279292/176599876-24634d65-5d2f-4290-8cf4-da035a1f2790.mp4"/>

**Comment by Tyriar** [comment]
Do you still have `"terminal.integrated.localEchoLatencyThreshold": 3` set or is it a higher value? If you have it that low I think you should be disabling the feature by setting it to -1.

**Comment by Tyriar** [comment]
Merging into https://github.com/microsoft/vscode/issues/126209
