### ISSUE TITLE
Control InlineCompletions Debounce Parameters from ExP

### ISSUE THREAD

**Issue by DavidLangworthy** [microsoft/vscode#151447]
The debounce settings for inlineCompletions are important for both user experience and system performance.  This feature request is to enable ExP experimentation over these parameters to determine the optimal setting.  

Adding control at this level is different from adding a delay in the provider in two ways.  First, There is an adaptive window protocol over the setting so adding delay within the provider adds delay to the debounce window and the experiment needs to get past this feedback cycle and figure out what the setting should actually be.  Second, adding delay in the provider increases the time for all users regardless of their individual network delay.  By modifying the minimum value the experiment can "set a floor" that does not impact users distant from the provider's underlying point of presence.  

Note that this issue is to enable the ability. There will be a separate issue to actually run the experiment.

This is the current state:
https://github.com/microsoft/vscode/blob/bb5215fff67fd9f40e247a353cc0e5e84a28f49f/src/vs/editor/contrib/inlineCompletions/browser/inlineCompletionsModel.ts#L47-L51

There are two approaches to adding this feature.  
- Promote these parameters to settings and use the existing settings to ExP as in: #134684
- Add specific logic to inlinecompletions for ExP as in: https://github.com/DavidLangworthy/vscode/tree/debounceexperiment

Both are equivalent from the experimentation standpoint.  The approach should be determined by what is best for the codebase.  

@digitarald @hediet 

(I can submit the branch as a PR but I need some help with the import.  It is violating the pattern in some way I can't figure out how to correct)

**Comment by jrieken** [comment]
We have adjusted the min/max interval on our end. Moving to July (maybe August) for the next steps

**Comment by hediet** [comment]
Not yet, there is a testing failure, I'm looking into that right now.

**Comment by DavidLangworthy** [comment]
Thank you for the update.

Independent of this experiment, have you had any ideas about how to expose the current debounce value to the providers?  We'd like to include it in telemetry.

**Comment by hediet** [comment]
Right now it is always 50. We can add a mechanism once we make it dynamic again (the release in a month).

**Comment by hediet** [comment]
@DavidLangworthy do you need us to do something here? Or can we close this issue?

**Comment by DavidLangworthy** [comment]
Please go ahead and close this.  

If there are any plans to change how debounce works within inline completions, please let us know.  It turns out to be a super important parameter for the copilot user experience.

Thank you
