### ISSUE TITLE
Formatting code

### ISSUE THREAD

**Issue by vamichael** [Microsoft/vscode#15145]
- VSCode Version:1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1.  When opening up files like XML or C#, the code is highlighted nicely, but there is no way to format the code.  Other types, like JS files allow me to to do a **format document** or **format selection**.  What is the secret to allowing me to format other file types?

**Comment by aeschli** [comment]
Check out the marketplace for extensions. https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp provides a formatter for C#.
