### ISSUE TITLE
Pasting into a template string may result in said string getting cut off

### ISSUE THREAD

**Issue by yay** [microsoft/vscode#151414]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version: 1.67.2 (Universal)
- OS Version: macOS 12.4, arm64

Steps to Reproduce:

1. Copy (as in the gif)
2. Paste (as in the gif)

![2022-06-07 11 11 18](https://user-images.githubusercontent.com/1799756/172355858-349e8d2a-5c0b-42e8-9670-b3f7a24bfffa.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by yay** [comment]
I would rather not install it.

**Comment by yay** [comment]
@mjbvz It's been fixed in the latest 1.68 update. Thank you.
