### ISSUE TITLE
Warning "Invalid abbreviation" in "Jade" Language Mode

### ISSUE THREAD

**Issue by natsu-k** [Microsoft/vscode#15141]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.16|
|npm-intellisense|christian-kohler|0.1.3|
|jquerysnippets|donjayamanne|0.0.1|
|live-html-previewer|hdg|0.0.1|
|vscode-jade-snippets|mrmlnc|1.0.1|
|ejs-language-support|QassimFarid|0.0.1|
|bootstrap-3-snippets|wcwhitehead|0.0.7|
|JavaScriptSnippets|xabikos|1.1.0|

---

Steps to Reproduce:

1. Create a new jade/pug document (e.g. test.pug or test.jade)
2. Ensure language mode is "Jade"
3. Type the vertical bar (pipe | ) character into the document
4. Press tab
5. Warning message is displayed and tab is **not** inserted.

Message is shown on pressing tab. "|{tab}" is a valid operation in jade and is used in cases like the example below:

```jade
button(ng-click='addUser()').btn.btn-primary
    i.ion-plus-round
    |   Add new user
```

**Comment by mrmlnc** [comment]
Oh, it's related to https://github.com/Microsoft/vscode/issues/11478

**Comment by ramya-rao-a** [comment]
@natsu-k @mrmlnc  I cannot repro this in the latest VS Code 1.10.2

Can either of you try again?

Closing for now, will re-open if you can still repro

**Comment by mrmlnc** [comment]
Confirm 👍

**Comment by ramya-rao-a** [comment]
@mrmlnc confirm which way :) ?

confirm no repro or confirm you can still repro ?

**Comment by mrmlnc** [comment]
Confirm that I can't repro this issue now ;)

**Comment by natsu-k** [comment]
I tested this today at work. I can also confirm this issue is fixed.
