### ISSUE TITLE
Assign a quit command from Ctrl+Q or Ctrl+Shift+Q

### ISSUE THREAD

**Issue by colemickens** [Microsoft/vscode#15142]
VSCode Version: 
```
Version 1.7.1
Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
Date 2016-11-03T13:46:46.244Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
```

**OS Version:** Arch Linux (w/ testing repo, up to date as of this very second)

**Steps to Reproduce:**
1. Press `Ctrl-Q` or `Ctrl-Shift-Q`

**Expected**: VS Code exits.

**Actual**: VS Code does not exit.

I tried to peak around. The other relevant open issue seemed to be more related to editor-specific keyboard shortcuts whereas this seems like an OS-integration issue.

I don't know if this should work on Windows, but it was something that basically every other app I use on Linux conforms to.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15261

**Comment by colemickens** [comment]
It's not really a dupe since it was opened before the actual dupe, but I'm happy as long as it's fixed either way. Thanks.

**Comment by bpasero** [comment]
@colemickens yes, sorry for that. I decided to take the other one because it already had 3 up votes. That is one more than yours ;)

**Comment by colemickens** [comment]
😆 sounds good! Cheers!
