### ISSUE TITLE
ipv6 split issue

### ISSUE THREAD

**Issue by wkr1423** [microsoft/vscode#151438]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Ubuntu 21.10

Steps to Reproduce:
1.using a project called "[openvscode-server](https://github.com/gitpod-io/openvscode-server)" which depends on vscode
2.The server binds the ipv6 address
3.Access it with the ipv6 address

Where is the problem:
in the core of vscode
for example: workbench

What causes the problem:
There are some omissions in vscode's address handling
VSCode uses ":" to split the address, the content before ":" is the domain and the numbers after the ":" is the port
but there are 7 ":" in the IPv6 address
![untitled](https://user-images.githubusercontent.com/57672685/172035876-e4b8ace0-2053-421a-8e4a-63b1ad574e41.png)
![2022-06-05 13-07-58 的屏幕截图](https://user-images.githubusercontent.com/57672685/172035939-438aa21c-2b3e-4d12-85a1-90753c10c492.png)

Solution:
use this to get address(this is for javascript)
```javascript
function getLocationByHref(rawLocation) {
  rawLocation = rawLocation.replace("http://", "").replace("https://", "");
  let pos = rawLocation.indexOf("/");
  let rightLocation = "";
  let IP = "", port = 0;
  let flag = true;
  if (pos == -1) {
    pos = rawLocation.indexOf("?");
    if (pos == -1) {
      rightLocation = rawLocation;
      flag = false;
    }
  }
  if(flag){
    for (let i = 0; i < pos; i++) {
      rightLocation += rawLocation[i];
    }
  }
  pos = 0;
  for (let i = rightLocation.length - 1; i >= 0; i--) {
    if(rightLocation[i] == ":"){
      pos = i;
      break;
    }
    if(isNaN(rightLocation[i])) break;
  }
  if(pos == 0){
    IP = rightLocation;
    port = "";
  }
  else{
    for (let i = 0; i < pos; i++) {
      IP += rightLocation[i];
    }
    for (let i = pos + 1; i < rightLocation.length; i++) {
      port = port * 10 + Number(rightLocation[i]);
    }
  }
  return [IP, port];
}
```

I hope you can fix it quickly.

**Comment by connor4312** [comment]
Verified in code review, @wkr1423 please let us know if this still presents a problem for you with the latest Insiders build
