### ISSUE TITLE
No option to Turn on Settings Sync (No accounts requested yet)

### ISSUE THREAD

**Issue by Lissy93** [microsoft/vscode#151434]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: Manjaro (Linux x64 5.9.16-1-MANJARO)

Steps to Reproduce:

1. Install VS Code via package manager
2. Click 'Accounts' 

**Expect State**
`You are not signed in to any accounts` and `Turn on Settings Sync...` <sup>Re: [Docs](https://code.visualstudio.com/docs/getstarted/settings#_settings-sync)</sup>

<img width="300" src="https://user-images.githubusercontent.com/1862727/172402425-47d66a30-1081-4397-9e7c-0a23f0107241.png" />

**Actual State**
`No accounts requested yet` and no option to add an account or sign in.

<img width="250" src="https://user-images.githubusercontent.com/1862727/172402340-12e3fd8b-bb10-4cbf-aa73-a00d122cadf2.png" />

There's also no option to turn on settings sync by right-clicking on the Manage gear menu at the bottom of the Activity Bar, [as explained in the docs](https://code.visualstudio.com/docs/editor/settings-sync#_turning-on-settings-sync). And the `settingsSync` key is totally missing from Preferences.

---

I'm guessing there is some extra component that I need to add, but I couldn't find anything about this in the docs.

I feel like I'm missing something obvious here, any help would be much appreciated.

**Comment by dzsquared** [comment]
I suspect this might be linked to https://github.com/microsoft/vscode/issues/151411 and a broader issue.

I'm currently on 
```
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```
and cannot sign into Github (or access the previously signed in github account) in vs code for codespaces, copilot, etc.

**Comment by TylerLeonhardt** [comment]
You probably installed the wrong vscode package. If you see this icon everywhere:
![image](https://user-images.githubusercontent.com/2644648/172462066-c168a543-1847-4b47-9b3c-c0df7cacbe92.png)
That's not the right one - it doesn't come with settings sync.

How did you install this package?

**Comment by Lissy93** [comment]
@TylerLeonhardt - You are absolutely correct.

I'd just installed it via the Software store without even thinking.
After uninstalling it, then building [`visual-studio-code-bin`](https://aur.archlinux.org/packages/visual-studio-code-bin) from Arch user repository, sync works as expected.

Dumb mistake on my part, sorry about that. And thank you very much for your help :)
