### ISSUE TITLE
Delay of dynamic notebook toolbar action label visibility change

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#151460]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/876920/172479775-4303af23-0b75-46e8-848f-08316604c358.png">

While rerunning cells, the actions on the notebook toolbar only render icons even when there are space in the toolbar. After the execution finishes, it re-renders properly.

<img width="718" alt="image" src="https://user-images.githubusercontent.com/876920/172480038-93cd6337-a6dc-4336-90d4-ca979546246e.png">

**Comment by roblourens** [comment]
I don't ever remember seeing this but I definitely don't see it now anyway
