### ISSUE TITLE
How to use multi-line in Custom Snippets body part?

### ISSUE THREAD

**Issue by kanlidy** [Microsoft/vscode#15140]
- VSCode Version: 1.7.1
- OS Version: window 10

Steps to Reproduce:

When I add some custom snippets into my *.json file, it's very inconvenient to use `""` in each line, is there any ways like use "`multi-line codes`" there?

**Comment by aeschli** [comment]
@kanlidy What do you mean by 'multi-line codes'? Can you add an example of a snippet you have?

**Comment by mrmlnc** [comment]
Hacky-solution: http://codepen.io/mrmlnc/pen/GqrqPg
Demo: 

![2016-11-08_17-22-41](https://cloud.githubusercontent.com/assets/7034281/20102679/00d50e7e-a5d8-11e6-83a9-c31d4c7ce4c1.gif)

**Comment by aeschli** [comment]
You can also have a single string that uses \n in it.

**Comment by jrieken** [comment]
Closing. Please return with more information on this

**Comment by jcrben** [comment]
This is still rather awkward. It seems like a clear step back from Sublime snippets, doesn't it? In Sublime, the code didn't really need to be messed with too much to get it into the snippet. Lots of examples at https://webdevstudios.com/2016/08/16/snippets-saved-life-how-sublime-text-3-snippets-changed-everything/

**Comment by jrieken** [comment]
@kanlidy What do you mean by 'multi-line codes'? Can you add an example of a snippet you have?

**Comment by jcrben** [comment]
Take the example on the documentation page [Creating your own Snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) which looks like this in the [jqAjax in this jQuery snippet collection](https://github.com/DonJayamanne/jquerysnippets/blob/master/snippets/javascript.json#L16-L30):

	"jqAjax": {
		"prefix": "jqAjax",
		"body": [
			"$.ajax({",
			"\ttype: \"${method}\",",
			"\turl: \"${url}\",",
			"\tdata: \"${data}\",",
			"\tdataType: \"${dataType}\",",
			"\tsuccess: function (response) {",
			"\t\t$0",
			"\t}",
			"});"
		],
		"description": "Perform an asynchronous HTTP (Ajax) request."
	},

Meanwhile, this is how it looks in a Sublime snippet:

    <snippet>
      <content><![CDATA[
    \$.ajax({
        type: "$1",
        url: "$2",
        data: "data",
        dataType: "dataType",
        success: function (response) {
            
        }
    });
     
     
      
    </body>
    </html>
    ]]></content>
      
      <tabTrigger>jqAjax</tabTrigger>
      
      
    </snippet>

In this case, you only have to escape the `$` in Sublime snippets, which makes it easier to tweak your code into snippets and easier to read the snippets. That blog post I linked above has some other examples.

**Comment by realappie** [comment]
@jrieken Why is this issue even closed. Snippets seriously need a refactor.

**Comment by smiled0g** [comment]
I agree. It's obviously too painful to write multi-line snippet this way.

**Comment by IljaDaderko** [comment]
Atom uses something like this

```
body: {
  """
  Your multiline stuff here
  """
}
```

**Comment by aeschli** [comment]
IMO I would not invent another flavor of JSON here, but use an existing and established syntax such as JSON5.
