### ISSUE TITLE
Incorrect intelligence and problem refreshing the error after correction

### ISSUE THREAD

**Issue by saurabhnachankar** [Microsoft/vscode#15143]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|net-core-project-manager|ksubedi|0.3.6|
|csharp|ms-vscode|1.4.1|

---

Steps to Reproduce:

1. Intelligence should be improved in Visual Studio Code. Proper suggestion are not specified in the intelligence
2. Error are not refreshed in code after correcting it.
3. Very poor approach for developing in code considering other IDE's

**Comment by aeschli** [comment]
@saurabhnachankar For what language is that? Can you also add a small code sample that demonstrated the issue?

**Comment by saurabhnachankar** [comment]
This was my controller's method invoking for creating XL file through
Epplus.

*Issue No. 1  :* This was my following using :  using
Microsoft.Net.Http.Headers; for ContentDispositionHeaderValue.
But i was not able to get it through intelligence in Visual Studio Code. so
i opened it in visual studio community and got the appropriate using.

*Eg :*
Response.Headers["Content-Disposition"] = new
ContentDispositionHeaderValue("attachment")

*Issue No 2 :* Even commented code is complied in debugger and later shows
the following error of commented code like

*Eg :*


*In Browser error:*
An error occurred during the compilation of a resource required to process
this request. Please review the following specific error details and modify
your source code appropriately.
Please fix the issue of VS-Code

Regards,
Saurabh Nachankar

On Tue, Nov 8, 2016 at 7:41 PM, Martin Aeschlimann <notifications@github.com

**Comment by aeschli** [comment]
Moving to C#

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#894
