### ISSUE TITLE
References view shows icons even though I have icons disabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151406]
Seeing this in the latest released builds, seems to me like a regression that is recent:

![image](https://user-images.githubusercontent.com/900690/172333016-bcf8a0da-cfd1-47b0-9890-45212614d7fc.png)

**Comment by rzhao271** [comment]
What are some verification steps for this issue? The icons also hide for me when I tried https://github.com/microsoft/vscode/issues/151406#issuecomment-1148381363

**Comment by alexr00** [comment]
@bpasero would you be able to verify this? I'm not sure why but I was only able to repro with your full settings.
