### ISSUE TITLE
I cannot use switch to quick fix enum,But in VS it's work well.

### ISSUE THREAD

**Issue by plmkojx** [microsoft/vscode#151485]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.    enum Animal{
        dog,cat,mouse
    }
    class Program
    {
      
      static  Animal animal;
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            switch (animal)
            {
                    
                default:
            }
        }
    }
2.like this ,can quick fix all the enum case

**Comment by plmkojx** [comment]
> /extC#

what is it

**Comment by mjbvz** [comment]
File this issue against the C# extension 

(it’s a command we use for the bot to close and add a comment with this info, but the commenting part failed here for some reason)
