### ISSUE TITLE
TypeScript code completion should suggest the enum name when typing the name of an enum member

### ISSUE THREAD

**Issue by boriskrisanov** [microsoft/vscode#151469]
In the code below, code completion should suggest `Test.TEST_1` when `TEST_1` is typed.
```typescript
enum Test {
	TEST_1
}

TEST_1
```

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
