### ISSUE TITLE
Feature Request: `auto_find_in_selection` option

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#15148]
On 12 Jul, I opened issue #9120 because VSCode got the behavior that `find in selection` is **off** by default if I press `ctrl+F` with a multiline selection. Then it was fixed soon at that time.
But now, VSCode got the behavior again in v1.7.1 because of #12109.

I prefer that `find in selection` is **on** by default if I press `ctrl+F` with a multiline selection.
I know some IDE/editors are behaving so.

- Visual Studio 2013
- eclipse
- Sublime Text

In Sublime Text case, it has `auto_find_in_selection` option. I can switch the behavior.
I think good if Visual Studio Code also has the option to configure the behavior.

Thank you.

**Comment by studoot** [comment]
I'll add my desire for this feature to be added - I run across this on a daily basis - several times a day, in fact... The fact that Visual Studio has this behaviour (find in selection autoselected with a pre-existing multiline selection) just exacerbates that...

**Comment by BigRedT** [comment]
Any update on this?

**Comment by roblourens** [comment]
It was fixed by adding the setting `'editor.find.autoFindInSelection'`
