### ISSUE TITLE
Use editor banner to advertise merge editor when in editor with git conflicts

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#151403]
When in a file with git conflicts consider to use the editor banner to advertise the 3-way merge editor. I am not fully convinced we should do this, but am leaning towards it. Would love to hear other opinions.

The nice thing about our editor banner is that it has an X so users can easily get rid of it.

![Screenshot 2022-06-07 at 09 46 03](https://user-images.githubusercontent.com/1926584/172325268-44adbe13-2d5d-469c-9f46-8dbb897a58b3.png)

Here's what VS does.

![image](https://user-images.githubusercontent.com/1926584/172322699-58cdf865-8a2d-4f42-be58-339ca8702703.png)

fyi @jrieken @daviddossett @bpasero

**Comment by jrieken** [comment]
The question is who should be doing this. Today, only extensions have the knowledge of merge markers and files-under-conflict but extensions don't have the capabilities to show such messages...

**Comment by daviddossett** [comment]
Would this replace the notification seen today?

<img width="517" alt="CleanShot 2022-06-06 at 14 32 10@2x" src="https://user-images.githubusercontent.com/25163139/172431142-d0188b83-1fd3-40e5-91e3-12473dee01dc.png">

**Comment by isidorn** [comment]
@daviddossett I think those are separate.
However the nice experience would be if that notification would be a modal dialog, and it only appears on commit.

fyi @lszomoru

**Comment by jrieken** [comment]
I have concerns allowing extensions to show the banner. This can be another source of annoyance and "advertising" which IMO we shouldn't have.

**Comment by isidorn** [comment]
@hediet I do not like introducing proposed API that we know we do not want to finalise.

Is there something about the conflict files which could be common in the SCM layer, and not on the Git later. For example to have a scheme which is common for conflict files across scm providers, or something like that

**Comment by hediet** [comment]
Let's discuss in #153800.

**Comment by gjsjohnmurray** [comment]
@jrieken wrote:
> I have concerns allowing extensions to show the banner. This can be another source of annoyance and "advertising" which IMO we shouldn't have.

As an extension author I would like to be able to use the file banner (not for advertising, I promise). Perhaps by adding a second control on the right of the Close button, with the eye-closed codicon and a "Never Show Again" hover tip it could become easy for users to nuke extension-contributed banners which they find annoying.

**Comment by hediet** [comment]
> As an extension author I would like to be able to use the file banner 

OT, but what would you want to use it for?

**Comment by gjsjohnmurray** [comment]
> OT, but what would you want to use it for?

Some of the extensions I work on handle files that generate other files in one or more intermediate formats (e.g. a .cls file generates a .mac which in turn generates a .int). Users sometimes want to view the intermediate files. Or they open an intermediate file and need to be advised to edit the originating source instead. I think the banner could provide a better UX for this than notifications in the bottom right, particularly for new users.
