### ISSUE TITLE
Unable to update extensions: "Command 'Extensions: Update All Extensions' is not enabled in the current context."

### ISSUE THREAD

**Issue by dbw9580** [Microsoft/vscode#15144]
- VSCode Version: 1.7.1
- OS Version: Windows 10 14393

I was unable to update any of my extensions after I updated to 1.7.1. Trying to execute "ext update" from the command palette I was prompted with "Command 'Extensions: Update All Extensions' is not enabled in the current context." And the command in contextual menu was grey and not clickable.
Googled the error message but there seems to be  no relevant mentions.

Steps to Reproduce:

1. Press F1 to bring up command palette and type "ext update" and choose " Update all extensions".
2. Click the "..." button on the extension tab and the command in the contextual menu is grey.

**Comment by joaomoreno** [comment]
The extensions appear like they have updates to install? Can you show us a screenshot?

**Comment by dbw9580** [comment]
Sorry, it appears I was having network issues. There was an error prompt saying "connect ETIMEDOUT 191.238.172.191:443" once I opened VS Code and did a extension search, and after I switched to another connection it went fine.
