### ISSUE TITLE
Debug Toolbar invisible, Shortcuts for debugging not working

### ISSUE THREAD

**Issue by clepet** [Microsoft/vscode#15147]
- VSCode Version: 1.7.1
- OS Version: Kubuntu 16.04.1 LTS

Since I updated my VSCode to 1.7.1 yesterday my debugging process is kinda buggy. Everytime I run (not debug!, Ctrl+F5) my application, the application is run but I don't see the debug toolbar. Besides that I also can't use my debug hotkeys to start/stop the application. What's weird about this is that as soon as I type anything into my debug console the debug toolbar gets visible and the debug hotkeys get usable again. 
I'm working with Python, therefore I'm using [this](https://marketplace.visualstudio.com/items?itemName=donjayamanne.python) extension.

Steps to Reproduce:

1. Run any Application. Default shortcut: Ctrl + F5

**UPDATE**

I tried to completely reinstall VSCode now, which didn't work unfortunately. I still had that bug.
After uninstalling VSCode 1.7.1 and reinstalling VSCode 1.6.1 it works again. So I am pretty sure it has to do something with the new Version 1.7.1.

**Comment by isidorn** [comment]
This work fine for me - though I only tried it for node debugging. Does regular debugging work for you all the time?
Forwarding to @DonJayamanne since he owns the python extension and can check if things are working fine on his end.

**Comment by DonJayamanne** [comment]
This issue was moved to DonJayamanne/pythonVSCode#503
