### ISSUE TITLE
[themes] Command for easy change of light / dark theme

### ISSUE THREAD

**Issue by AllanDaemon** [microsoft/vscode#151466]
Switching from dark to light themes and vice versa every day is annoying. A simple command like **Toggle Light / Dark Theme** would be great.

Today, when you try to change the theme through the command **Preference: Color theme**, it opens the pannel with the current theme in the focus of the selection. The themes are grouped by type (light, dark, high contrast, etc), so to find the light or dark theme of whatever you are using involves searching through the list, scrolling down and up. Today I don't even bother to go to the light/dark version of the theme I'm using, because it would consume more time.

Many themes exist in the light and dark theme, so for those, it should be easy to have a command that just toggles between the light or dark version. For example, the default theme, and the Github theme support this.

This may involve adding a field in the theme that lists what are the opposite version(s) of them to use them.

Using a list can be easier because you can list alternatives. This would allow a theme that doesn't have a light or dark version to suggest one opposite one. And the toggle command could change to the first theme in the list that is installed. Being able to overwrite the theme list in the user's settings could also be a nice feat.

With this, it could tackle other issues related to theme preferences. A few ones that I found that may benefit from this are:
https://github.com/microsoft/vscode/issues/100460
https://github.com/microsoft/vscode/issues/84486
https://github.com/microsoft/vscode/issues/114807
https://github.com/microsoft/vscode/issues/114751
https://github.com/microsoft/vscode/issues/112387
https://github.com/microsoft/vscode/issues/107669
https://github.com/microsoft/vscode/issues/91231

**Comment by aeschli** [comment]
Only a few themes comes in light/dark pairs and connecting these by name is not easy. But we have the `preferred light` and `preferred dark theme` setting that we could use.

Give that such an option would be quite easy to implement. If anyone want to give it a try with a PR, help is welcome.

**Comment by Balastrong** [comment]
I'd like to give it a try!

Could I get a code pointer to see where quick input commands are?
