### ISSUE TITLE
i lost all my data and my application load forever what should i do 

### ISSUE THREAD

**Issue by Frankkp** [microsoft/vscode#151470]
ADD ISSUE DESCRIPTION HERE

Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.63 Safari/537.36
Embedder: codespaces

This codespace is currently running in recovery mode due to a container error. Review the creation logs, update your devcontainer configuration as needed, and run the "Rebuild Container" command to retry. that the message

**Comment by Frankkp** [comment]
basicly what going on when ever i try to open visual code it load for ever and i lost all the date i store since i start the cours 
thank you in advance for helping me

**Comment by aeschli** [comment]
I see you closed the issue already, but in case of data loss, I'd suggest to create support ticket against Github.
https://docs.github.com/en/support/contacting-github-support/creating-a-support-ticket
