### ISSUE TITLE
Allow easy toggling between sourcemaps and compiled code in js-debug

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#151412]
@jrieken wanted the ability to easily disable sourcemaps in js-debug, and mentioned @alexdima and @bpasero also like debugging without sourcemaps. However, changing this in the launch config via `sourceMap: true/false` is burdensome and makes the decision for the whole team, where it should be a user choice.

He suggested a some button (an editor action? is that too prominent?) to toggle sourcemaps on off.

- The button should remember its state in the workspace between reloads
- Breakpoints should always be allowed to be set in the source code, but appear in (be moved to, since BPs can only appear in one location) the compiled code when sourcemaps are disabled, and should show in the source code otherwise.
    - Therefore in this mode, we don't fully "disable sourcemaps", more just control where the debugger steps in
    - However we can optimize some things and be extra-lazy about parsing sourcemaps when "disabled"

**Comment by isidorn** [comment]
Editor title action might be too prominent. Why not Call Stack title area action? I think extensions can not contribute to this place right now, but we could change this.

fyi @roblourens for ideas.

**Comment by jrieken** [comment]
> Why not Call Stack title area action?

Because it isn't an action that operates on call stacks but on the whole file/editor?

**Comment by roblourens** [comment]
I think this would operate on the whole debug session, not one editor. That makes me think it would make more sense as a context menu item on the debug session. I also don't think this will be commonly used enough to have a button for it. But, it should be really obvious somehow that this mode is activated.

**Comment by roblourens** [comment]
Also, you can maintain your own launch configs in a workspace config, I do this sometimes. But I get that it's a pain to clone our huge vscode launch.json

**Comment by roblourens** [comment]
I like that, it could also go into the editor title at that point

**Comment by isidorn** [comment]
@connor4312 sounds good to me.
