### ISSUE TITLE
Onboarding experience: Installing git does not get synced with onboarding task/built-in terminal

### ISSUE THREAD

**Issue by hawkticehurst** [microsoft/vscode#151457]
When trying to complete the "Install git" task in the VS Code onboarding process I had issues with VS Code recognizing that I did actually install git and could only fix the problem by closing and reopening VS Code entirely. 

It would be great if this synced without having to close the app because it breaks the flow of the onboarding experience.

Issue Type: <b>Bug</b>

0. (You might need a new unconfigured a machine without git installed)
1. Run "Developer: Reset Welcome Page Walkthrough Progress"
2. Find the "Install git" task in the "Boost your productivity" section (note that this might not show up if you have git installed)
3. Separately, open up the Powershell app in with Admin privileges 
4. Install chocolatey via Powershell
5. Use chocolatey to install git via Powershell
6. Go back to VS Code 

You should see that the "Install git" task is still rendered as not complete. On top of that if you open the built-in VS Code terminal and type "choco" or "git" it should report back errors saying that these commands do not exist.

To fix the problem, close and reopen VS Code entirely and you should see that the "Install git" task is now replaced with a new task for installing a repo and if you run the same commands in the built-in terminal they should succeed.

### Details

VS Code version: Code - Insiders 1.68.0-insider (87630a9122f88f5062fe9964839a92116c274a86, 2022-06-06T17:09:26.575Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (17.20GB free)|
|Process Argv|--crash-reporter-id f92bbe85-d251-4567-9fb4-e18928161621|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.12.2
python|ms-|2022.7.11581010
vscode-pylance|ms-|2022.6.0
jupyter|ms-|2022.6.1001601017
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912cf:30496797
vsclangdf:30492506

```

</details>

**Comment by daviddossett** [comment]
Not sure if this is formally related to the terminal. cc @Tyriar and @meganrogge just in case.

**Comment by hawkticehurst** [comment]
Managed to snag some screenshots in case it helps.

Powershell has git installed correctly, but VS Code still hasn't recognized the change.

<img width="1200" alt="vscode-git-install" src="https://user-images.githubusercontent.com/39639992/172497309-db5a734a-6a79-4911-8923-bf43ea28f942.png">

After closing and reopening VS Code, git now successfully runs in the built-in terminal and the "Install git" task has been replaced with a clone repo task.

<img width="897" alt="vscode-git-install-reopen-app" src="https://user-images.githubusercontent.com/39639992/172497314-4521c4b6-f3ad-4765-8d7e-5f40250ec8d8.png">

**Comment by hawkticehurst** [comment]
Oh, also it's probably worth noting that I double-checked that closing and reopening a new terminal session does not sync up the changes. VS Code itself must be closed and reopened for the changes to be picked up.

**Comment by hawkticehurst** [comment]
Yes totally, I love that idea. Even just having that line of text telling me to restart would be a huge win in keeping the onboarding process running smoothly imo

**Comment by misolori** [comment]
cc @lszomoru

**Comment by Tyriar** [comment]
If your `$Path` environment variable changes on Windows you need to restart the entire VS Code window unfortunately. The feature request to make this act better on Windows is https://github.com/microsoft/vscode/issues/47816.

Moving to @lszomoru for the restart note which should be Windows only.

**Comment by lszomoru** [comment]
@digitarald, can we update both the getting started item as well as the SCM welcome view to explicitly call out that VS Code should be restarted after git has been installed? I see this as a tactical change until we invest in streamlining the installation of git.

**Comment by digitarald** [comment]
I rather get to an install vs making the onboarding text more complex. Restarting VS Code is common for users after some setup; so I am not too worried as we didn't get any other reports.
