### ISSUE TITLE
macOS smoke test fails downloading VSCode

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151588]
It looks like we started to run smoke tests against OSS build, but latest runs seem to fail:

```
[2022-06-09T07:03:25.585Z] Running desktop smoke tests against /Users/runner/work/1/VSCode-darwin-x64/Code - OSS.app/Contents/MacOS/Electron
[2022-06-09T07:03:25.586Z] VS Code product quality: 4.
[2022-06-09T07:03:25.615Z] Test data path: /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/vscsmoke
[2022-06-09T07:03:25.616Z] Preparing smoketest setup...
[2022-06-09T07:03:25.637Z] Starting operation 'versionReq...
[2022-06-09T07:03:25.637Z] Starting operation 'ensureStableCode...
[2022-06-09T07:03:25.675Z] Finished operation 'versionReq' successfully after 38ms
[2022-06-09T07:03:25.676Z] Starting operation 'versionReq.json()...
[2022-06-09T07:03:25.681Z] Finished operation 'versionReq.json()' successfully after 5ms
[2022-06-09T07:03:25.681Z] Found VS Code v1.68.0, downloading previous VS Code version 1.67.2...
[2022-06-09T07:03:25.684Z] Starting operation 'download stable code...
[2022-06-09T07:03:25.702Z] download stable code progress: resolvedVersion
[2022-06-09T07:03:25.703Z] download stable code progress: resolvingCDNLocation
[2022-06-09T07:03:25.710Z] Starting operation 'rimraf(testDataPath)...
[2022-06-09T07:03:25.713Z] Finished operation 'rimraf(testDataPath)' successfully after 3ms
```

For example: https://dev.azure.com/vscode/VSCode/_build/results?buildId=65389&view=results

**Comment by lszomoru** [comment]
This seem to be an intermittent problem that happens both for the OSS pipeline as well as for the product pipeline.
- OSS - https://dev.azure.com/vscode/VSCode/_build?definitionId=46&_a=summary&branchFilter=9700%2C9700%2C9700%2C9700%2C9700%2C9700%2C9700%2C9700%2C9700%2C9700. Here is a successful run - https://dev.azure.com/vscode/VSCode/_build/results?buildId=65387&view=logs&s=a56e7651-4213-56af-9488-c25fe636c10c&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9
- CI - Here is a failed run https://dev.azure.com/monacotools/Monaco/_build/results?buildId=173603&view=results. Here is a successful run - https://dev.azure.com/monacotools/Monaco/_build/results?buildId=173598&view=logs&s=a56e7651-4213-56af-9488-c25fe636c10c&j=a5d99aad-4929-5289-bf4a-26b78032353d

**Comment by bpasero** [comment]
Fyi @connor4312 , we are using the vscode test module:

https://github.com/microsoft/vscode/blob/2a9f19d36fe90248dec2c382f8fa460f69af6dbd/test/smoke/src/main.ts#L14

**Comment by connor4312** [comment]
It looks like the failure was an `ECONNRESET` which is likely a transient network error. Maybe we should build in some basic retry logic to test-electron.

**Comment by connor4312** [comment]
Hm, I will play around with vscode-test later today or tomorrow and see if I can get an uncaught error.

**Comment by bpasero** [comment]
@connor4312 after a first look, maybe:

https://github.com/microsoft/vscode-test/blob/e9d2dca994ac3c87253d97e7f680860cab68ee10/lib/request.ts#L12

```ts
https.get(api, urlToOptions(api), res => resolve(res)).on('error', reject)
```

I am not entirely sure if the `error` handler in the end is sufficient to catch errors from the stream. Looking at the docs though it seems they suggest the same:

https://nodejs.org/docs/v16.13.0/api/http.html#httpgeturl-options-callback

But my feeling is that we hit an `on('error')` on a stream that bubbles up as a uncaught exception. 

Somewhere here:

https://github.com/microsoft/vscode-test/blob/c6092b087a9c795c6d2097e864ab13e89d825226/lib/download.ts#L69-L78

**Comment by bpasero** [comment]
Interestingly enough, now on Linux when downloading playwright we get this:

```
$ /__w/1/s/node_modules/.bin/npm-run-all -lp 'electron x64' playwright-install
[electron x64      ] $ node build/lib/electron x64
[playwright-install] $ node build/azure-pipelines/common/installPlaywright.js
[playwright-install] /__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:613
[playwright-install]       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
[playwright-install]             ^
[playwright-install] 
[playwright-install] Error: Failed to download chromium v1000, caused by
[playwright-install] Error: Client network socket disconnected before secure TLS connection was established
[playwright-install]     at connResetException (node:internal/errors:692:14)
[playwright-install]     at TLSSocket.onConnectEnd (node:_tls_wrap:1587:19)
[playwright-install]     at TLSSocket.emit (node:events:539:35)
[playwright-install]     at endReadableNT (node:internal/streams/readable:1345:12)
[playwright-install]     at processTicksAndRejections (node:internal/process/task_queues:83:21)
[playwright-install]     at /__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:613:13
[playwright-install]     at async Registry._downloadExecutable (/__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:612:5)
[playwright-install]     at async Registry.install (/__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:590:9)
[playwright-install]     at async installBrowsersForNpmInstall (/__w/1/s/node_modules/playwright-core/lib/server/registry/index.js:780:3)
[playwright-install]     at async retry (/__w/1/s/build/azure-pipelines/common/retry.js:12:20)
[playwright-install]     at async install (/__w/1/s/build/azure-pipelines/common/installPlaywright.js:10:5)
```

**Comment by connor4312** [comment]
I saw that playwright issue on Andre's machine the other day. I think something is up with Playwright, or Chromium's CDN.

**Comment by connor4312** [comment]
Fixed the uncaught error in https://github.com/microsoft/vscode-test/pull/152

**Comment by bpasero** [comment]
👍
