### ISSUE TITLE
"Visual Studio Code" is a horrible name

### ISSUE THREAD

**Issue by Garrett-Cox** [microsoft/vscode#151563]
Issue Type: <b>Feature Request</b>

I realize it's already far too late and the damage is irreversibly done, but I must vent: I hate the name. I hate hate hate it. I am a dev who primarily works in visual studio. Can you guess what happens when I try to google or bing or any other search engine for anything at all related to visual studio? If you guessed "you get an absolute ton of results about the entirely different product visual studio code", you are correct! I'm sure this works both ways, but it seems that vscode is now far more popular than VS, this has been really destroying my ability to augment VS to make it do what I want, because everyone on earth wants to do what I want in vscode instead and drowns out the results I want.

I know deep in my heart that this isn't really possible but please change the name of the product so that maybe in 10 years I can find search results about VS again.

/rant

VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:37:03.389Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: Yes

**Comment by mjbvz** [comment]
Glad you got the rant out :) but yes this is not something we plan on changing
