### ISSUE TITLE
"waiting for the socond key of chord" on back space.

### ISSUE THREAD

**Issue by abitcons** [microsoft/vscode#151514]
Issue Type: <b>Bug</b>

I had installed a flutter extension that I have removed now.
The problem I am facing is that I can't press backspace button on any text box or text window. THis is really embarracing. I have already done all the suggestions given on web. No luck. when I press backspace I get following error message.
"waiting for the second key of chord."
I am using vs code in ubuntu 20.4

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.15.0-35-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|31.14GB (6.37GB free)|
|Process Argv|--unity-launch --crash-reporter-id fbd24a39-f675-47d1-9c7c-d3d242db4cba|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.39.0
argutec-azure-repos|arg|1.2007.15
chef|che|2.1.0
gitignore|cod|0.7.0
devops-extension-pack|d4n|0.3.0
azure-devops-snippets|dam|1.0.6
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
vscode-solution-explorer|fer|0.4.7
dotnet|for|0.0.4
vscode-tfs|gen|2.0.0
vscode-hana|gui|0.1.5
vscode-test-explorer|hbe|2.21.1
output-colorizer|IBM|0.1.2
vscode-sprint-planner|ipa|0.6.0
diff-tool|jin|0.0.1
vscode-azureappservice|ms-|0.24.2
vscode-azureresourcegroups|ms-|0.5.2
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.234.0
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.1
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5615
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
gradle-language|nac|0.2.3
gitlink|qez|1.2.4
ruby|reb|0.28.1
partial-diff|ryu|1.4.3
shell-launcher|Tyr|0.4.1
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.41.0
gitblame|wad|8.2.2
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by lramos15** [comment]
Sounds like you have a keyboard shortcut that starts with backspace.

1. Open the command palette (Ctrl + shift + p)
2. type keyboard shortcuts
3. And select `Developer: Toggle Keyboard Shortcut Debugging` to figure out which one is causing the issue

**Comment by DanBerkness** [comment]
I am having the same issue, I am currently looking into troubleshooting.

**Comment by lramos15** [comment]
@DanBerkness Following the same steps but in the command palette typing `shortcuts JSON` you should see `Preferences: Open Keyboard Shortcuts (JSON)` opening that should reveal a JSON file with your user configured keybindings.

**Comment by DanBerkness** [comment]
> @DanBerkness Following the same steps but in the command palette typing `shortcuts JSON` you should see `Preferences: Open Keyboard Shortcuts (JSON)` opening that should reveal a JSON file with your user configured keybindings.

I pulled up the JSON and line 75 (for me), says : { "key": "backspace",             "command": "deleteLeft",
                                     "when": "textInputFocus" }

So that looks normal.

Searching for backspace in the JSON file it looks like there are 6 bindings that use backspace. None of them start with backspace aside from the one above, which is to be expected.
