### ISSUE TITLE
Code block highlighting for mini map

### ISSUE THREAD

**Issue by waleedrana777** [microsoft/vscode#151568]
https://user-images.githubusercontent.com/37755440/172731283-6cba111e-7ff6-40fa-b580-40801420700a.mp4

Can we get this kind of highlighting interesting outlining spans in the code's minimap?! Comments beginning with a special character like -- or # could be recognized as section headings or titles!

**Comment by shayv633** [comment]
I'd also love to see this feature, specifically the #Mark section headers!

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/74843
