### ISSUE TITLE
An extra title bar is shown for a second VS Code window in full screen mode

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#15153]
Steps to Reproduce:

1.  Open a VS code window. Make it full screen
2. Open a new VS Code window
3. New window opens a  second tab in full screen mode
A Title bar is shown for second window which is not there for first window

![image](https://cloud.githubusercontent.com/assets/10746682/20094164/51aa83ca-a5a0-11e6-9f98-6734fd6f5276.png)

**Comment by sandy081** [comment]
New window no longer opens as a tab

**Comment by PotterDai** [comment]
Hmmm, it will be such a pity to remove this accidental feature.
This tab is great for multi-project navigation, especially in Mac where mission control just sucks at navigating.
