### ISSUE TITLE
argv.json doesn't support trailing comma

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#151534]
Diagnostics don't seem to be working in JSONC sometimes:

Left is JSONC right is JSON
![image](https://user-images.githubusercontent.com/2644648/171920045-93a32e2a-ece2-44d3-bebb-51950669be74.png)

Interestingly, I do eventually get diagnostics showing up in JSONC files:
![Recording 2022-06-03 at 11 03 18](https://user-images.githubusercontent.com/2644648/171921029-2d241b6d-e526-4b4e-b869-bd9354691aa4.gif)

but it takes switching to another language and then back again...

_Originally posted by @TylerLeonhardt in https://github.com/microsoft/vscode/issues/151200#issuecomment-1146223289_

**Comment by aeschli** [comment]
I wasn't able to reproduce. What version of VS Code is it? There was a fix a week ago.

**Comment by TylerLeonhardt** [comment]
@aeschli latest insiders. Here's another repro:

1. `> Preferences: Configure Runtime Arguments` command
2. Add a `,` to the end of the last property in the json like:
```
{
  "locale": "de",
}
```

There should be a warning that says you can't have that... but no error is shown

**Comment by aeschli** [comment]
For some or our won configuration files we allow trailing commas.
If you wonder how we configure that, this is done through a property in the associated JSON schema. Click on `{ }` of the JSON 
language indicator, open the schema and look out for `allowTrailingCommas: true`

But Untitled files don't have a schema and can't set that. So they should always show a warning for a trailing comma.

**Comment by TylerLeonhardt** [comment]
@aeschli the argv.json doesn't seem to allow trailing commas. It caused this: https://github.com/microsoft/vscode/issues/151200

**Comment by TylerLeonhardt** [comment]
Diagnostics do appear to be working though, so this issue appears to be fixed. We just need to update the schema for argv.json

**Comment by aeschli** [comment]
You can change the schema here: https://github.com/microsoft/vscode/blob/24273bd759ec31e0ab469cdcd617c1e8921a789a/src/vs/workbench/electron-sandbox/desktop.contribution.ts#L287

but instead I recommend to fix this by using our JSONC parser.
A said, for our own settings files that are normally only read by us, we permit trailing commas to make the user's live easier.

**Comment by TylerLeonhardt** [comment]
>but instead I recommend to fix this by using our JSONC parser.

As in allow our `argv.json` to have trailing commas?

@bpasero thoughts?

**Comment by TylerLeonhardt** [comment]
Related: https://github.com/microsoft/vscode/pull/151659#discussion_r894024139

**Comment by bpasero** [comment]
We cannot unless we find a way to use the JSONC parser in common module land:

https://github.com/microsoft/vscode/blob/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc/src/main.js#L238-L246

**Comment by TylerLeonhardt** [comment]
I think a big help would be to strip that trailing comma on the last line of argv.json if one is there. Logic for that shouldn't be too bad right? What do you think?

**Comment by aeschli** [comment]
I made a PR for `stripComments` to also remove trailing commas: #151941

**Comment by TylerLeonhardt** [comment]
I think we can close this then. I'll rename this issue to be about the `,` in `argv.json`.
