### ISSUE TITLE
Can't quick open recent folder by press CTRL+R

### ISSUE THREAD

**Issue by saatana97** [microsoft/vscode#151595]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:
版本: 1.67.2 (user setup)
提交: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
日期: 2022-05-17T18:15:52.058Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19043
Steps to Reproduce:

1.press CTRL+R
2.can't quick open recent folder

I have to click setting icon and then hover [file]->[open recent folder] and then click [more]
I want press CTRL+R anywhere can quick open recent folder,I remember it used to worked

**Comment by saatana97** [comment]
or other way to quick open recent folder?

**Comment by TylerLeonhardt** [comment]
I’m suspicious of an extension causing this behavior. Can you open the Command Palette (<kbd>⌘</kbd>/<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and run the extension bisect command: `Help: Start Extension Bisect` and follow the prompts? ([More information about Extension Bisect here](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect))

**Comment by saatana97** [comment]
Thanks,
problom from ext eg2.vscode-npm-script
