### ISSUE TITLE
Search excluded files: VS reads .gitignore contents as case sensitive, but Git reads it as case insensitive

### ISSUE THREAD

**Issue by happycollision** [microsoft/vscode#151518]
Issue Type: <b>Bug</b>

1. create a .gitignore like the following
```
# Ignore everything
*
# Don't ignore this file!
.gitignore
# Don't ignore readme files
!readme.md
```
2. Create a `README.md` file (be sure it is all caps) containing:
```
You can't see me.
```
3. Close the file (VS Code searches open files no matter what)
4. Use VS Code's file search feature to find `see me`.

### Expected

The file is found.

### Actual

The file is not found.

<img width="603" alt="CleanShot 2022-06-08 at 10 40 51@2x" src="https://user-images.githubusercontent.com/3663628/172645034-26d53afd-3572-4c5a-885e-8035a6fcbba8.png">

(If you now open the file, you'll see it is found)

https://user-images.githubusercontent.com/3663628/172645512-9cb8ed76-533e-476f-9d0c-6744a7f9d3cf.mp4

## Additional info

My hypothesis: Git interprets `.gitignore` files as case insensitive, while VS Code reads the file as case sensitive. You can test this by changing the `.gitignore` to un-ignore `README.md` instead of `readme.md` and see that the search now finds the file. But in all cases, Git sees the file as available for version control.

The title of this issue implies my hypothesis, but perhaps there is a deeper issue where this only happens when you un-ignore a file using `!`.

## Versions

VS Code version: Code - Insiders 1.68.0-insider (b7faf235467dd56e4a62e52e7f1cacf875b67261, 2022-06-07T18:34:09.305Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by roblourens** [comment]
This comes from ripgrep. You can file an issue at http://github.com/burntsushi/ripgrep but there is some complexity, it looks like case-sensitivity is configurable in git, and I guess it depends on the case-sensitivity of your filesystem too.
