### ISSUE TITLE
importModuleSpecifier shortest vs relative

### ISSUE THREAD

**Issue by artola** [microsoft/vscode#151532]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.67.2
- OS Version: Darwin arm64 21.5.0

Steps to Reproduce:

Having this path alias in `tsconfig.json`:

```
    "paths": {
      "@/*": ["src/*"]
    }
```

And using `"typescript.preferences.importModuleSpecifier": "shortest"` and with this file structure:

```
src/
  - foo.ts
  - bar.ts
```

Working on `foo.ts` the  import suggestion same level file is `@/bar` when it will make more sense to use the relative `./bar`.

In my opinion, it is not "shortest" the `@/bar` that `./bar` therefore the last one should be used.

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
