### ISSUE TITLE
No highlights for changed lines in Git repo

### ISSUE THREAD

**Issue by arglog** [microsoft/vscode#151561]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.67.2
- OS Version: macOS Monterey 12.2.1
```
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.3.0
```

I am coding on a remote machine through the SSH extension of VSCode. I cloned a repo from GitHub and made a few changes. However, changed lines were not highlighted with colors near the line number (e.g., orange and green) as normal. The changed file was not labeld with a `M` symbol in the file tree (Explorer). The file was displayed as a modified file in the source contral panel though.

**Comment by arglog** [comment]
This issue still persists. Any updates about this issue? The issue is the same as a previous issue https://github.com/microsoft/vscode/issues/89104, but no solotion provided there.

**Comment by lszomoru** [comment]
@arglog, apologies for not getting back to you on this issue. At the moment there are various issues with folders/workspaces that have a symbolic link on their path. These issues mostly originate from the fact that the VS Code workbench maintains the symbolic link in the path, while `git` resolves it. This creates a path "discrepancy" between the "git world" and the "VS Code world".
