### ISSUE TITLE
Color theme guides should raise awareness about native bracket pair colorization

### ISSUE THREAD

**Issue by mitsukuri** [microsoft/vscode#151564]
Native bracket pair colorization was enabled by default in v1.67, but sadly there are too few color themes out there in the wild that actually customize those highlight colors. I personally know only of [Gruvbox Material](https://marketplace.visualstudio.com/items?itemName=sainnhe.gruvbox-material), [Remedy ](https://marketplace.visualstudio.com/items?itemName=robertrossmann.remedy) and [Nord](https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code) themes that do so. Others seem to be created too long ago when this feature wasn't a thing or their authors just don't seem to care to update. The problem with this is that - at least to to my eye - color themes with mostly pastel palettes are ruined by the default, too saturated colors of matching brackets and just don't look stylish or professional. Regretfully I ended up deleting/disabling all the themes that do not style matching bracket highlights, many of them perfectly fine and good looking otherwise. And I find the feature itself too useful to disable, uniformly colored bracket pairs feel like a step back now.

I'm aware that it's possible to customize their colors by hand in my `settings.json` via `workbench.colorCustomizations` but that must be repeated each time I switch to new color theme, and more importantly, doesn't solve the problem of inconsistency on a systematic level.

My proposal is that something should be added to the documentation, maybe at the [color theme guide](https://code.visualstudio.com/api/extension-guides/color-theme), maybe some other place, to somehow raise theme authors' awareness about this feature and remind them gently to update their themes to take account of bracket highlight colors.

**Comment by hediet** [comment]
You could try to file a pull request/issue to those themes!

**Comment by adityamwagh** [comment]
How about updating the default Dark+ theme with bracket matching? I believe this is relevant to this issue's conversation as Dark+ is built-in.

**Comment by hediet** [comment]
There are also other editor features that themes need to style (e.g. selected word background color, deprecated identifier color, indent guide color etc.).
I don't think bracket pair colorization is special, especially as it is standard now for a while.
The themable colors for bracket pair colorization are already documented in https://code.visualstudio.com/api/references/theme-color.

Thus closing.
