### ISSUE TITLE
Address UI scalability concerns in the face of contributeable explorers

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#15155]
Allowing custom explorers causes UI scalability concerns that need to be addressed. Among them are
- number if icons in the activity bar
- can the user control what is visible in the activity bar
- discoverability of custom explorers
- scalability of the view menu (should be choose to show custom explorers there)
- relationship to discoverability of panels

**Comment by bpasero** [comment]
![viewlet](https://cloud.githubusercontent.com/assets/900690/20798253/89d2cf6e-b7de-11e6-921b-b7810c6648b7.gif)
