### ISSUE TITLE
Introduce Selection menu

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#15156]
In orde to improve discoverability of available editor functionality we introduce a top level "Selection" menu.

- [x] Identify which commands should be in  the menu
- [x] How do we measure the success of the menu
- [x] Implementation

**Comment by chrmarti** [comment]
One proposal is:
- Add Cursor Above
- Add Cursor Below
- Add Selection to next match
- Add Selection to previous match
- -separator-
- Copy Line Up
- Copy Line Down
- Move Line Up
- Move Line Down
- -separator-
- Expand Selection
- Shrink Selection
- -separator-
- Emmet: Expand Abbreviation
- Emmet… (opens command palette focusd on Emmet:)
- Issue: Exposing 'Rectangular Selection' ALT+SHIFT+ DRAG

**Comment by chrmarti** [comment]
Pushed without addressing the rectangular selection issue.

**Comment by chrmarti** [comment]
Feedback in #16253
