### ISSUE TITLE
SCM viewlet publish button has icon accidentally localized

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#151529]
The `$(cloud-upload)` part of the button appears to be getting localized in the pseudo-language extension pack.

![A screenshot showing the icon of the Publish button failing to render due to being localized](https://user-images.githubusercontent.com/7199958/172662225-132d9739-f4ee-42ce-ae4b-5c8161a14752.PNG)

**Comment by joaomoreno** [comment]
Verified by code review.
