### ISSUE TITLE
PHP annoying auto-completion. 

### ISSUE THREAD

**Issue by dominikgorczyca** [microsoft/vscode#151538]
Snippets exist so you can do things faster, in html for example, you can write main and emmet snippet will create full main tag. 
I would like to do the same in php files but I have to use more effort because there are many snippets from phpGlobalFunctions that push emmet to the second option when typing some snippets, not a big deal but having to stop to click or press arrow down to select this snippet every time is mildly annoying and "main" snippet doesn't even do anything, when you click on it, it just gives you text "main", and it comes as the first choice only after you have completed writing "main" so it could as well not exist, because it brings completely no change after choosing it. 

I would suggest to delete this phpGlobalFunction from https://github.com/microsoft/vscode/blob/main/extensions/php-language-features/src/features/phpGlobalFunctions.ts

**Comment by roblourens** [comment]
I think the best thing to do would be to disable the php-language-features extension, if you don't want those features. You can find it in the extensions viewlet under "@builtin"

**Comment by dominikgorczyca** [comment]
Okay, switching "PHP > Suggest: Basic" off does the job, and it still allows me to see prompts on php functions.
