### ISSUE TITLE
`vscode.executeCompletionItemProvider` command does not correctly return `MarkdownString`s

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#151537]
To reproduce, please follow these steps:

1. Download this modified version of the [LSP request forwarding sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-embedded-request-forwarding/) and follow the steps in the README to run the extension.

[request-forwarding.zip](https://github.com/microsoft/vscode/files/8864200/request-forwarding.zip)

2. In the Extension Development Host window, create two files, `test.html` and `test.html1`, with the following content:
```html
<html>
<head>
<style>
body {background-color: powderblue;}
h1   {color: blue;}
p    {color: red;}
</style>
</head>
<body>

<h1>This is a heading</h1>
<p>This is a paragraph.</p>

</body>
</html>
```
3. Hover over `background-color` in `test.html`. Notice that a hover tooltip appears.
4. Hover over `background-color` in `test.html1`. Notice that no hover tooltip appears.

The expected behavior is that the hovers would be identical due to the request forwarding for embedded CSS in HTML1 files provided by the example extension.

**Comment by isc-bsaviano** [comment]
I'm seeing similar behavior with `vscode.executeCompletionItemProvider` with a version of my language server that I'm developing. If I set the resolve parameter to some high number like 1000 so all of the documentation is resolved, the HTML Language Server (which is the language  that I'm forwarding request for) shows the `CompletionItem`s with the documentation resolved but the completion tooltip is showing an error message:

<img width="790" alt="Screen Shot 2022-06-10 at 11 23 33 AM" src="https://user-images.githubusercontent.com/44776135/173098491-1520d958-4eed-46a8-8a73-b2299f8797f7.png">

**Comment by jrieken** [comment]
We have a test that [asserts](Markdonwhttps://github.com/microsoft/vscode/blob/3d6ab7cfe6d7ea8fc4170ef27bd82fbf16431692/src/vs/workbench/api/test/browser/extHostApiCommands.test.ts#L741) that MD strings work. A similar check exists for hovers so I assume this is specific to html

**Comment by isc-bsaviano** [comment]
@jrieken I was able to reproduce this with JavaScript in the dev version of my Language Server. When I hover over this line in my embedded JavaScript:

```javascript
	console.log('Hello World');
```

The `TypeScript` server's log shows the correct result:

```
[Trace  - 12:32:06.705] <semantic> Sending request: quickinfo (21). Response expected: yes. Current queue length: 0
Arguments: {
    "file": "^/isc-embedded-content/11:5-10/isfs://iris2:user/User/Test.cls.js",
    "line": 6,
    "offset": 11
}
[Trace  - 12:32:06.708] <semantic> Response received: quickinfo (21). Request took 16 ms. Success: true 
Result: {
    "kind": "method",
    "kindModifiers": "declare",
    "start": {
        "line": 6,
        "offset": 10
    },
    "end": {
        "line": 6,
        "offset": 13
    },
    "displayString": "(method) Console.log(...data: any[]): void",
    "documentation": "",
    "tags": []
}
```

But the `vscode.executeHoverProvider` command does not return the documentation:

```json
[
  {
    "contents": [
      {},
      {}
    ],
    "range": [
      {
        "line": 5,
        "character": 9
      },
      {
        "line": 5,
        "character": 12
      }
    ]
  }
]
```

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano in https://github.com/microsoft/vscode-extension-samples/issues/682 I have logged a uri-encoding issue with the sample you derived your repro from, and have provided a PR containing the simple fix. It might not resolve this issue, but probably worth checking if your actual use case has a similar fault.

**Comment by gjsjohnmurray** [comment]
@isc-bsaviano does this completion provider issue repro with the modified request-forwarding sample you originally attached as a zip, once you have applied the fix for [the issue](https://github.com/microsoft/vscode-extension-samples/issues/682) I raised in the sample you derived it from?

**Comment by isc-bsaviano** [comment]
@gjsjohnmurray I can't reproduce that issue using the modified sample, only my LS. I'm going to close this issue and open a new one if I have something that I can reproduce.
