### ISSUE TITLE
C# Code Folding Stops for Regions After Formatting Document

### ISSUE THREAD

**Issue by darrenparkinson** [Microsoft/vscode#15157]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a C# file
2. Insert #region and #endregion around a section
3. Code folding works
4. Press Ctrl+Shift+P and Select Format Document (or Shift+Alt+F)
5. #region and #endregion are now indented, code folding no longer works.

![image](https://cloud.githubusercontent.com/assets/4262917/20094826/e0a0b960-a59a-11e6-8791-8ea8c52bf983.png)
![image](https://cloud.githubusercontent.com/assets/4262917/20094876/11714f14-a59b-11e6-95bb-07d84e347218.png)

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#888
