### ISSUE TITLE
Viewing a hidden view does not implicitly "keep" it

### ISSUE THREAD

**Issue by gar1t** [microsoft/vscode#151608]
Does this issue occur when all extensions are disabled?: Yes

This is an elaboration of #95242. I'll argue in this issue that the intended behavior is a bug or a design flaw.

The issue is that when a view is hidden, it goes into a "Hide me now and ALSO hide me implicitly later and for all time when I lose focus in my container until someone explicitly 'keeps' me" state. If I didn't know about the surprising "keep" switch, I'd swear this was a bug - the view, as described in #95242, mysteriously disappears.

When a view is hidden and then later shown, I think the user is asking to show the view as it was before the hide (I think a very simple mental model). I can't speak for the whole world, but I've shown this behavior to others and they all scratch their head about this. Why does the view disappear when you click another tab in the container? It's a bug! Turns out, it's by design. But this is surprising, unintuitive behavior.

**Comment by sbatten** [comment]
When a user hides a view, the view can be re-shown for various reasons, a lot of which are ephemeral. The existing behavior has been around for quite some time, and while I can understand the mismatch of expectations, its not something I've seen a lot of complaints about and changing that behaviour would raise a lot of alarm.

@sandy081 if he has any thoughts here

**Comment by sandy081** [comment]
I share same thinking as @sbatten.

**Comment by gar1t** [comment]
Understandable - thanks for the clarification!
