### ISSUE TITLE
iPadOS: return key doesn’t work after some time

### ISSUE THREAD

**Issue by ZaharBozhok** [microsoft/vscode#151626]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: Codespaces
- OS Version: iPadOS15.5
- Browser: Safari PWA

Steps to Reproduce:

1. Use iPad with Magic Keyboard
2. Use vscode for some time (probably there are more specific steps, but I still can’t figure out which ones)

Return key doesn’t work neither in terminal nor in text editing. 
Reloading the page doesn’t help, BUT unplugging and plugging back the keyboard (just slightly pull iPad off the case)
Closing the application also doesn’t help.
Switching to the other app and back - doesn’t help (in another app return key works)

P.S.
Sometimes sth like this happens to arrow keys.
And I don’t know why similar thing happens with Ctrl+` (shortcut to open the terminal), it just works randomly

**Comment by alexdima** [comment]
Might be related to https://github.com/microsoft/vscode/issues/144232

**Comment by mraarone** [comment]
Both of these issues’ last comments point to each other. This one, https://github.com/microsoft/vscode/issues/144232, should be the primary and this one closed.
