### ISSUE TITLE
Mac: Double clicking the title bar doesn't maximize the window anymore

### ISSUE THREAD

**Issue by marvinhagemeister** [Microsoft/vscode#15167]
- VSCode Version: 1.8.0-insider 2016-11-08T07:53:03.250Z
- OS Version: Mac Sierra

Since today's insider build the window cannot be maximized anymore by double clicking the window's title bar.

Steps to Reproduce:

1. Open vscode insider build
2. double click the title bar

![double clicking the titlebar](http://i.imgur.com/JTehtY6.jpg)

**Comment by marvinhagemeister** [comment]
@bpasero Wow, that was quick! Already fixed in the latest insider build that was published just now. You're awesome 👍

**Comment by marvinhagemeister** [comment]
@bpasero The opposite doesn't yet. When a window is maximized it won't scale down to it's previous size. Should this issue be reopened or should I make a new one?

**Comment by bpasero** [comment]
@marvinhagemeister does it work for you (new insiders are out already)? I noticed that I can get into a situation where the window no longer unmaximizes. But I also have some tools installed that hook into the window management and that might be related.

**Comment by marvinhagemeister** [comment]
@bpasero It's already out. I noticed the same with [spectacle](https://github.com/eczarny/spectacle) (also hooks into the window management). Whenever I use a hotkey set by spectacle to maximize the window I can't unmaximize it anymore, same as you. 

Perhaps vscode/electron isn't aware that the window is in an already maximized state and tries to maximize it again which won't have a visible effect at this point?

**Comment by bpasero** [comment]
@marvinhagemeister I notice that I first need to resize the window to a smaller state before the double click turns the window from maximized into unmaximized mode. Not sure if that is something I do wrong in the window creation or general Mac behaviour...

**Comment by bpasero** [comment]
Actually no, I see the same behaviour with the native window title 👍

**Comment by marvinhagemeister** [comment]
@bpasero mh, I can reproduce this easily with spectacle:

1. Open vscode unmaximized
2. Maximize with spectacle (⌥⌘F)
3. Double-Click the title bar doesn't work anymore

This works fine with Finder. Not sure if this is an issue specific to spectacle though.

**Comment by bpasero** [comment]
@marvinhagemeister you can see if this is caused by the custom title by setting 

`"window.titleBarStyle": "native"`

And restarting and try again on the native title.

**Comment by marvinhagemeister** [comment]
@bpasero you're right. With `"window.titleBarStyle": "native"` it doesn't work either.

**Comment by wallverb** [comment]
I use BetterSnapTool with this settings:
![image](https://cloud.githubusercontent.com/assets/1723815/20152379/04e872bc-a68c-11e6-9dc0-aed13bae8993.png)

"window.titleBarStyle": "native" / old version works for double click (maximize / unmaximize)

without 'native' - i can only double click to maximize. No unmaximizing

**Comment by bpasero** [comment]
Yes, I would assume that external tools that hook into the native title bar are not supported in our custom title bar.

**Comment by samskiter** [comment]
Same problem - no external tools installed. My system setting is for double click to 'zoom'
