### ISSUE TITLE
cannot read properties of undefined, reading 'dispose'

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151641]
![Screen Shot 2022-06-09 at 1 12 23 PM](https://user-images.githubusercontent.com/29464607/172935774-009b0b05-ebfc-4196-b3ed-0d42de96c1ba.png)

**Comment by Tyriar** [comment]
Think I saw this today

**Comment by meganrogge** [comment]
found repro - clear the terminal twice

**Comment by meganrogge** [comment]
working on it

**Comment by meganrogge** [comment]
repro is to create some decorations via commands and then delete the terminal
