### ISSUE TITLE
Editor hovers sometimes show a line too high (and other rendering oddities)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#151683]
- VS Code Version: `1.68.0-insider`
- OS Version: `Windows_NT x64 10.0.22621`

I'm not sure exactly when this started -- could have been in 1.67, but certainly in 1.68, but the editor hovers sometimes a positioned too far (a full line height or more) from the line being hovered over.

The mouse was hovering where the arrow is pointing:
![image](https://user-images.githubusercontent.com/641685/172993358-e73d6604-66f5-44f8-ba11-be27f4421756.png)

This is very intermittent, but the odd thing is once it happens for a line, it is usually easy to get it to happen again (though not 100% more like 70%)

Related, I've also seen the hover position incorrectly similar to above, but they quickly jump down to the right position -- but that is much harder to replicate. When it happens though, it is hard to move the mouse onto the hover and it will often just hide. Though I see that behavior much more often with debug hovers, rather than strict editor/GitLens hovers -- but it still happens too often.

Additionally, there is some odd rendering sometimes when you move the mouse over different parts of a line (from left to right) where the icons in the GitLens hover seem to wiggle:

![wiggle](https://user-images.githubusercontent.com/641685/172992776-a67c1ff2-0acd-4c75-a1eb-c45681ee7b78.gif)

FYI, I have `"gitlens.hovers.currentLine.over": "line"` set so that the GitLens hovers show over the whole line rather than just the annotation

/cc @alexdima

**Comment by eamodio** [comment]
Here is the debug hover being very finicky -- making it really hard to copy any text out of it.
![hiding](https://user-images.githubusercontent.com/641685/172998990-915aa45f-c27f-42c6-bfad-69698a6de5e9.gif)

**Comment by alexdima** [comment]
The editor hover and the debug hover are implemented separately, so it might be best to split the issue up. I suggest to keep this issue around for the editor hover, which seems to have trouble when it needs to update its content as the mouse is moved on the same line or when it updates its content after the "Loading..." row (which shows up when a hover provider is slow) is removed.

**Comment by eamodio** [comment]
Split out the debug hover part into: https://github.com/microsoft/vscode/issues/151816

**Comment by roblourens** [comment]
I filed https://github.com/microsoft/vscode/issues/151235, and see this all the time. Happy to help debug
