### ISSUE TITLE
Can't contribute custom command to Report Issue remote experience

### ISSUE THREAD

**Issue by osortega** [microsoft/vscode#151636]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0
- OS Version: macOS Monterey 12.4
Steps to Reproduce:

1. On any remote extension contribute `remoteHelp.issues` value to any command id in `package.json`
2. Click on builtin `Report Issue` button.

This will try to execute the built in Report Issue service provided by VS Code which only supports GH issue urls.
The problem is that extension not necessarily want to redirect to a particular GH issue url but provide a different report url or a different experience all together.

Filing this as a bug since VS Code used to allow overrides of the `Report Issue` experience with a custom command just like `Get Started`, `Read Documentation`, `Provide Feedback` and `Review Issues`.

Note: you can reproduce this issue within Codespaces by connecting to any codespace and clicking the `Report Issue` button under the remote explorer view.

cc @TylerLeonhardt

**Comment by alexr00** [comment]
"Report Issue" was added with e0dd508, which includes the current behavior of opening the VS Code issue reporter. Having a `remoteHelp` contribution for reporting issues is a reasonable feature request.

**Comment by alexr00** [comment]
@osortega do you still need this?
