### ISSUE TITLE
Remove double quotes and setup an eslint rule requiring single quotes/backticks

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151633]
We have these rules which are a bit out of date: https://github.com/microsoft/vscode/wiki/Coding-Guidelines#strings

I don't think we enforce or use the double quotes anymore, should we replace them all with single quotes and setup an eslint rule?

**Comment by TylerLeonhardt** [comment]
Who usually does these eslint rules? I feel like @jrieken is the person I see doing it the most.

**Comment by jrieken** [comment]
I can help you with this. For `prefer-const` I followed this flow

* get team buy-in via offline chat message and issue-ping
* add new rule to our confict
* run eslint with `--fix` (assuming the rule is autofixable), e.g this is the correct invocation `npx eslint -c .eslintrc.json --rulesdir ./build/lib/eslint --fix --ignore-path .eslintignore "**/*.js" "**/*.ts"`
* prepare PR and hope for no merge conflicts

**Comment by jrieken** [comment]
Looks like interest in this got lost. @TylerLeonhardt Re-open if you still want to do this
