### ISSUE TITLE
Cannot uninstall some extension

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#15166]
- VSCode Version: 1.1.1
- OS Version: Windows 8.1 x64

Steps to Reproduce:

1. Install _npm Script Runner_ or _HTML Hint_ extension (I did not experience the same problem with other extensions)
2. Uninstall them and click OK to "Are you sure you want to uninstall 'npm Script Runner'"?
3. Restart VSCode

After "successful uninstall", I can see the extension with the "Update" button and then the "Reload" button. I can not remove them via the UI (had to do that via File System instead)

**Comment by wallverb** [comment]
I had something similar - where multiple folders existed for the same extension - https://github.com/Microsoft/vscode/issues/12761

**Comment by sandy081** [comment]
@tSte I am not able to find the extensions you reported the problem for. Can you please help me in finding them so that I can try to reproduce?

Thanks

**Comment by tSte** [comment]
Neither can I. Is it possible that those extension have been removed?

I tried to reproduce it with all available npm runner extensions, but they both seem to install and uninstall correctly.

**Comment by sandy081** [comment]
Possibly removed
