### ISSUE TITLE
View can be scrolled so much to present only last line at the top of the view

### ISSUE THREAD

**Issue by tomkowz** [Microsoft/vscode#15160]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.3.21|
|MagicPython|magicstack|0.5.15|
|cpptools|ms-vscode|0.9.2|
|python|tht13|0.2.3|

---

![screen shot 2016-11-08 at 11 33 07](https://cloud.githubusercontent.com/assets/2303177/20095821/55960f70-a5a7-11e6-9263-e90aa1a7576a.png)

Steps to Reproduce:

1. Create file with multiple lines so you can scroll them
2. Scroll to bottom as much as possible.

OBSERVED: See the last line of the file is on the top of the view.
EXPECTED: Scrolling should be prevented when last line of the file meets the bottom of the view.

IMO expected behaviour can be found in many top applications.

**Comment by DanTup** [comment]
I've seen this in a lot of editors and suspect it's by design. I actually got used to it and hate when something doesn't scroll this way - sometimes I'm reading the last function in a file and would rather have it on the top half of the screen than the bottom.

**Comment by tomkowz** [comment]
Is there any option to make it cusomizable via preferences?

**Comment by alexandrudima** [comment]
```
	// Controls if the editor will scroll beyond the last line
	"editor.scrollBeyondLastLine": true,
```

**Comment by tomkowz** [comment]
Thanks!
