### ISSUE TITLE
JavaScript intellisense with object parameter

### ISSUE THREAD

**Issue by huyqut** [Microsoft/vscode#15168]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Build 14393.351

In JavaScript, does intellisense support object parameter with JSdoc?
In this specific case, I want `foo` parameter inside `Bar.prototype.request` to be treated as `Foo` so that know that it suggests `x`, `y` for me. However, it only shows `any` which means it does not know what type of `foo` is. Will this be available in the future?

![vscode](https://cloud.githubusercontent.com/assets/22194121/20099729/afebdd34-a5ec-11e6-8370-2fb9464779cf.png)

**Comment by waderyan** [comment]
@huyqut thank you for opening this issue. There are some known limitations around this. I have confirmed what you are seeing in the latest insiders build. 

@bowdenk7 does prototype pattern == expando?

**Comment by mjbvz** [comment]
@huyqut, you'll likely have to add an `@class` to your jsdoc:

```js
/**
 * @class
 * 
 * @param {number} x
 * @param {string} y
 */
function Foo(x, y) {
    this.x = x;
    this.y = y;
}
``` 

It seems TypeScript does not yet support `@class` however. I've opened a TypeScript issue to track this: https://github.com/Microsoft/TypeScript/issues/12681

Closing as upstream
