### ISSUE TITLE
decorations get overlaid instead of cleared for first prompt line

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151645]
https://user-images.githubusercontent.com/29464607/172939179-23115c60-0c0b-4980-b0ae-778a04b458a0.mov

**Comment by Tyriar** [comment]
Related https://github.com/microsoft/vscode/issues/151161, https://github.com/microsoft/vscode/issues/151228

**Comment by meganrogge** [comment]
happening bc the first line's marker isn't disposed of (and thus the decoration isn't either)
![Screen Shot 2022-06-20 at 1 54 08 PM](https://user-images.githubusercontent.com/29464607/174676466-f15f692d-349a-40c4-ab98-442c9233efb2.png)

**Comment by meganrogge** [comment]
so maybe we should have some API on xterm like `onDidClear` so that can be handled specially?

**Comment by meganrogge** [comment]
oh here's the issue that solved https://github.com/microsoft/vscode/issues/144142

**Comment by rzhao271** [comment]
Just to confirm, to verify this issue, are you typing commands followed by the clear command in between? Or are you clearing the terminal another way?

**Comment by meganrogge** [comment]
Typing and clearing @rzhao271

**Comment by Tyriar** [comment]
Pretty sure this is the `Terminal: Clear` command, not `clear` run in the terminal
