### ISSUE TITLE
Visual Studio Code has crashed

### ISSUE THREAD

**Issue by Onlytanya** [Microsoft/vscode#1516]
I can't use code when i update it to 0.10.5 .To no avail I have uninstalled and reinstalled the application. OSX 10.11.2.

**Comment by IAMJ** [comment]
OS X 10.11.2, VSCode 0.10.5, crashed

**Comment by bgse** [comment]
You might be running into this one:

https://github.com/Microsoft/vscode/issues/1463

If that is the case, instructions on how to go back to 0.10.3 are near the top of the discussion, and a possible workaround is near the bottom.

**Comment by Onlytanya** [comment]
start up VS Code with a English-US keyboard layout，it works good!
Thanks all.

**Comment by bpasero** [comment]
Closing as duplicate.
