### ISSUE TITLE
Add 'offline_access' to default scopes for Microsoft Auth

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#151653]
Similar to https://github.com/microsoft/vscode-dev/blob/main/client/contrib/microsoftAuth.ts#L252-L255 add `'offline_access'` to get refresh tokens by default when using `vscode.authentication.getSession('microsoft'...)`

**Comment by TylerLeonhardt** [comment]
verification steps:
* in an extension, ask for:
```
await vscode.authentication.getSession('microsoft', ['Task.ReadWrite'], { createIfNone: true });
```
* run the extension and sign in when asked as a result of ^^^
* Restart vscode

Expected to not get asked for sign in again because `offline_access` was added automatically.

**Comment by alexr00** [comment]
I get this in my browser:

The request is blocked.
<long string of characters>

**Comment by joyceerhl** [comment]
I am also unable to complete the sign in flow in my browser.
