### ISSUE TITLE
WebViews are broken on github.dev on Firefox

### ISSUE THREAD

**Issue by andreafalzetti** [microsoft/vscode#151648]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.0 (commit 4af164ea3a06f701fe3e89a2bcbb421d2026b68f)
- OS Version: Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Firefox/102.0

Steps to Reproduce:

1. Open any repository using github.dev 
2. Open a WebView (e.g. any extension readme won't be visible, readme previews won't work either)

**Comment by andreafalzetti** [comment]
I also experienced a similar issue on VS Code Desktop 1.68.0. I am not sure if it's related.

<img width="1840" alt="Screenshot 2022-06-09 at 18 32 41" src="https://user-images.githubusercontent.com/2318450/172963929-daa8e7e4-d365-43e3-9644-0c65c397b9a8.png">

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode/pull/151679 fixing this

**Comment by joaomoreno** [comment]
![image](https://user-images.githubusercontent.com/22350/173582491-b17c219f-e7cb-4add-94e3-5ca2472ae54b.png)

**Comment by Anas-jaf** [comment]
I have similar issue , I tried to disable all extension but it help
OS Version: Browser: Mozilla/5.0 (X11; Linux x86_64; rv:91.0) Gecko/20100101 Firefox-esr/91.10.0
Kali GNU/Linux Rolling 2022.1
