### ISSUE TITLE
Run "Code OSS" CI tests against sources

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151677]
We currently run integration and smoke tests against a built version of "Code OSS". We never ship this product and thus shouldn't test it. Rather I suggest to run tests "out of sources", as a developer would do.

This will speed up the "Code OSS" CI build substantially, at least for smoke tests that don't require to download stable bits.

//cc @joaomoreno

**Comment by bpasero** [comment]
I think this is happening now?

**Comment by lszomoru** [comment]
That is correct. Closing the issue.
