### ISSUE TITLE
Tree view item's have lost file icons

### ISSUE THREAD

**Issue by mattseddon** [microsoft/vscode#151663]
Does this issue occur when all extensions are disabled?: Yes/No -N/A

Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:00.250Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

Hi, I am one of the authors of the [DVC extension for VS Code](https://marketplace.visualstudio.com/items?itemName=Iterative.dvc). Our public release is scheduled for next week.

After upgrading to `1.68.0` today I noticed that our "DVC Tracked" TreeView has lost all of its file icons:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/172966883-98ed0bef-e514-4dcc-805e-98a075ee58ce.png">

Up until today, the view looked like this:

![image](https://user-images.githubusercontent.com/37993418/172967278-8911d3b8-eba5-4948-9e21-f048cf7fb4f4.png)

Downgrading to `1.67.2` does bring the icons back too:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/172967655-d176a2e1-550a-4548-94e7-ba7591c2d9d8.png">

What can I do to get these icons back? Are there some code changes that I can make?

Appreciate any help that you can give me.

Thanks!

Steps to Reproduce:

1. Update to 1.68.0
2. View extension's file explorer TreeView

**Comment by mattseddon** [comment]
From `TreeItem` in the API:

```
        /**
         * The icon path or {@link ThemeIcon} for the tree item.
         * When `falsy`, {@link ThemeIcon.Folder Folder Theme Icon} is assigned, if item is collapsible otherwise {@link ThemeIcon.File File Theme Icon}.
         * When a file or folder {@link ThemeIcon} is specified, icon is derived from the current file icon theme for the specified theme icon using {@link TreeItem.resourceUri resourceUri} (if provided).
         */
        iconPath?: string | Uri | { light: string | Uri; dark: string | Uri } | ThemeIcon;
```

Looks like the default value was dropped for files. I can fix the issue by specifically setting:

```
treeItem.iconPath = isDirectory ? ThemeIcon.Folder : ThemeIcon.File
```

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/37993418/172969113-effa3335-148a-4e42-a79b-485a41ba1de8.png">

Will leave this here for anyone else that runs into the issue.

**Comment by KarimGhallab** [comment]
Same problem here, thank you for the solution ;)
