### ISSUE TITLE
Workbench - Explore improvements to settings 

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#15162]
- [x] Improve adjustment of common settings
- [x] Make it easier to find the settings that need adjustment and to adjust them

## Plan of actions
- [x] Improve actions and icons in Default settings editor.
- [x] Show Default settings and User/Workspace settings in the same editor side by side
- [x] Ability to filter in Default settings editor using a special Search box. 
- [x] Introduce similar actions in user/workspace settings files
- [x] Grouping settings as most commonly used

## Proposals
- [ ] Quick update of user/workspace settings through Command Pallette
- [ ] A quick picker to select/adjust a setting
- [ ] Introduce actions for keybinding settings
- [ ] Ability to sort/show top user used settings
- [ ] HTML preview for Default settings / keybinding settings ??
- [ ] Allowing features update the setting

**Comment by maxdeviant** [comment]
@sandy081 Would it be possible to add "Add ability to extend from other settings files" ([#15909](https://github.com/Microsoft/vscode/issues/15909)) to the proposals list? :smiley:

**Comment by sandy081** [comment]
@maxdeviant Main focus of this item is to improve the existing configuration space. I would not add things beyond this scope. We already provide extensibility of settings through extensions. So we need to see what more this will add. Please constraint the discussion about this in its item. Thanks.

**Comment by sandy081** [comment]
@chrmarti This is the plan item for exploring workbench configurations. Following list of things were prototyped till now

- Introducing actions to copy/select settings in Default Settings editor
- Introducing a settings related filter in Default Settings editor. This would only show matched settings upon filter.
- Inline Default settings in Settings editor with above functionality
- Quick pick functionality for adjusting settings through a command/action in UI.

As per last call, we decided to productise above.
