### ISSUE TITLE
pressing enter repeatedly results in decorations not showing up when using `oh-my-zsh`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151644]
![Screen Shot 2022-06-09 at 1 23 42 PM](https://user-images.githubusercontent.com/29464607/172937686-746637f7-dfdb-4eba-a3f7-25cd2d636193.png)

**Comment by Tyriar** [comment]
This happens because command executed happens but not command finished

**Comment by Tyriar** [comment]
And that's because of this: https://github.com/Microsoft/vscode/blob/ead690ec7b1855aa90b8ee67688c09d25fa17d61/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh#L71
