### ISSUE TITLE
Disabled extension list items don't use disabled foreground for description text

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#151650]
<img width="323" alt="CleanShot 2022-06-09 at 14 50 11@2x" src="https://user-images.githubusercontent.com/25163139/172951253-e4a3ea5e-f724-4b2d-9b2e-3ea63ff54c10.png">

**Comment by rzhao271** [comment]
The contrast ratio for the GitHub Codespaces text colour compared to the background colour appears to be 3.5:1, which is fine for minimum contrast requirements for large text. Will there be an issue if the description colour is also greyed out like that, though, assuming that's what the disabledForeground colour is?

**Comment by daviddossett** [comment]
This is a bit different than normal text contrast since the text is part of a disabled element. That would apply to all of the elements in the list item.

**Comment by aeschli** [comment]
Verified that the description now uses the disabledForeground.
It's still not very clean as the other parts seem to come from different color 

![image](https://user-images.githubusercontent.com/6461412/176220635-44981148-e5bd-498b-b171-8f463b75c52f.png)

The correct approach would be to introduce a set of colors just for extensions view `extensionsItemLabel.disabledLabelForeground`,`extensionsItemLabel.disabledDescriptionForeground`
