### ISSUE TITLE
[html] <pre> element should be formatted like <code> in editor, not like <p>!

### ISSUE THREAD

**Issue by loplopop** [Microsoft/vscode#15164]
- VSCode Version: 1.7.1
- OS Version:  Windows 7 Ulimate SP1

Steps to Reproduce:

1. Create a `<pre>` element with multiline content
2. Stock VSC HTML formatter will remove line breakes rendering `<pre>` useless. This behavious is not seen in `<code>` element. Obviously a `<pre>` must be auto formatted like `<code>` element. Fix this thing please.

**Comment by aeschli** [comment]
The list of elements that are not formatted are controlled by the setting:
`"html.format.unformatted"`. I added pre to the defaults.
In the meantime you can add it to the user settings.
