### ISSUE TITLE
`explorer.excludeGitIgnore` setting didn't hide file and folder in explorer tab correctly

### ISSUE THREAD

**Issue by Senbonzakura1234** [microsoft/vscode#151693]
Issue Type: <b>Bug</b>

1/ Step to reproduce
- update vscode to current latest version

- create a git repo using yarn version berry as it's package manager and create/update `.gitignore` with content below:
```
.pnp.*
.yarn/*
!.yarn/patches
!.yarn/plugins
!.yarn/releases
!.yarn/sdks
!.yarn/versions
```

- create `.vscode/settings.json` file and add the setting below:
   ` "explorer.excludeGitIgnore" = true `

- run `yarn install` 

2/ Expected behavior:
- `.yarn/cache` and `.yarn/install-state.gz` should be hidden in the explorer tab
- `.yarn/releases` and `.yarn/plugins` should be visible in the explorer tab

3/ Actual behavior:
- `.yarn/cache` and `.yarn/install-state.gz` are visible in the explorer tab
- `.yarn/releases` and `.yarn/plugins` are visible in the explorer tab

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.80GB free)|
|Process Argv|--crash-reporter-id 54f165fe-0a7b-4bbc-b873-9e228bff6d63|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.2.0
path-intellisense|chr|2.8.1
regex|chr|0.4.0
doxdocgen|csc|1.4.0
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.42.1
flutter|Dar|3.42.0
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
vscode-deno|den|3.12.0
vscode-gitignore-syntax|dun|0.1.2
gitlens|eam|12.0.7
vscode-html-css|ecm|1.12.2
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
codespaces|Git|1.8.3
rest-client|hum|0.24.6
output-colorizer|IBM|0.1.2
better-cpp-syntax|jef|1.15.14
intellij-idea-keybindings|k--|1.5.1
template-string-converter|meg|0.6.0
json2typescript|mic|1.2.1
vscode-ros|ms-|0.8.2
python|ms-|2022.8.0
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
cmake-tools|ms-|1.10.5
cpptools|ms-|1.10.5
cpptools-extension-pack|ms-|1.2.0
material-icon-theme|PKi|4.18.1
material-product-icons|PKi|1.3.0
prisma|Pri|3.15.0
vscode-yaml|red|1.8.0
vscode-sort-json|ric|1.20.0
trailing-spaces|sha|0.3.1
vscode-scss-formatter|sib|2.4.2
mdx|sil|0.1.0
code-spell-checker|str|2.2.2
cmake|twx|0.0.17
vscode-nextjs-snippets|wil|0.3.0
ReactSnippets|xab|2.4.0
html-css-class-completion|Zig|1.20.0

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by lramos15** [comment]
There is still definitely something fishy going on here. `.yarn/**` doesn't seem to hide it but `**/.yarn/**` does and so does `.yarn`. Will investigate it thank for trying this out!

**Comment by lramos15** [comment]
> I believe the rules for parsing `.gitignore` and the rules for VSCode's `files.exclude` are different. For example, `bin/` means `**/bin/` in `.gitignore` but means `/bin/` in `files.exclude`.

Thanks for these helpful pointers yeah we want to try to follow the parsing of what git does but we do not have the git process so we have to rewrite all the rules ourselves. Here's the file we do that in if you are interested in contributing https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/search/common/ignoreFile.ts

**Comment by GMbrianlaw** [comment]
I'm not very familiar with Javascript, but for starters I think if a path begins with `/`, we remove it, or else we put `**` in front of the path.

**Comment by michaelschufi** [comment]
I also have a similar issue with `explorer.excludeGitIgnore` not hiding all the `.gitignore`d files.

### Example
File content of `/app/.gitignore`:
```
/node_modules
```
ignores `/app/node_modules` but `explorer.excludeGitIgnore` does not.

Interestingly, if I remove the `/` from `/node_modules` in the above rule, `/app/node_modules` gets hidden correctly.

**Comment by lramos15** [comment]
> ignores `/app/node_modules` but `explorer.excludeGitIgnore` does not.
> 
> Interestingly, if I remove the `/` from `/node_modules` in the above rule, `/app/node_modules` gets hidden correctly.

It's because our glob matching at the moment does not perfectly match that of gits. It's still a work in progress refining it. We do not have access to the git executable in core and therefore have to reinvent the wheel so to speak.

**Comment by danielniccoli** [comment]
`explorer.excludeGitIgnore` does not work for leading slashes.

`node_modules` in .gitignore hides the folder in the VSCode Explorer.
`/node_modules` in .gitignore does **not** hide the folder in the VSCode Explorer.

However, in both cases `git check-ignore` returns `node_modules`

> git check-ignore node_modules
node_modules

**Comment by MonadChains** [comment]
Hi @Senbonzakura1234, @danielniccoli and @lramos15
I've submit a PR that should solve the problem both for the `node_modules` and `.yarn/*` cases. Let me know if it works 😃

**Comment by lramos15** [comment]
Merged @MonadChains PR, let me know if this fixes your issue.

**Comment by danielniccoli** [comment]
@lramos15 I'll check once the update comes to my computer. Sorry to ask, but what version of vscode will this be in?
