### ISSUE TITLE
 About preference file 

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#15169]
- VSCode Version:1.7.1
- OS Version:windows 8.1

Question about preference file [Check Stackoverflow](http://bit.ly/2eIvTM4)

**Comment by aeschli** [comment]
@MandarSant Please add a full description of the problem to the issue. What do you expect?

**Comment by MandarSant** [comment]
@aeschli check the link u will get it

**Comment by aeschli** [comment]
I see you got an answer, closing the issue. Stackoverflow is actually the best place for questions.

The issue tracking system is for bug and feature request. 
Please be as complete as you can in the description, steps, screenshots, expected result, so there has to be no guessing on our side. See the [Issue filing guidelines here](https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

Thanks a lot for your help and understanding!
