### ISSUE TITLE
Toggle Comments - ALT+/  ?

### ISSUE THREAD

**Issue by neildeighan** [microsoft/vscode#151723]
So we have CTRL + /   to comment a line, but some times I find myself toggling comments between lines i.e.

// a line/block of code
another line/block of code

.. and then CTRL + / on each line to switch i.e.

a line/block of code
// another line/block of code

... might be nice to have say a toggle comment to highlight both lines/blocks and switch comment accordingly 

ALT + / .. seems to be available ?

**Comment by ArturoDent** [comment]
Sounds like you could use this extension: [Toggle Comments](https://marketplace.visualstudio.com/items?itemName=ArturoDent.toggle-comments#review-details).

Use this keybinding after installation:

```jsonc
{
  "key": "alt+/",
  "command": "toggle-comments.toggleLineComments",
  "when": "editorTextFocus"
}
```
