### ISSUE TITLE
Make watermark themeable

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#151783]
Refs to #151623

Currently, the watermark is [split up](https://github.com/microsoft/vscode/tree/main/src/vs/workbench/browser/parts/editor/media) for the various themes: 

<img width="256" alt="CleanShot 2022-06-10 at 11 52 08@2x" src="https://user-images.githubusercontent.com/35271042/173131518-ec3ed55d-1506-45d3-aff8-b2b97b788c9f.png">

It would be easiest to have a single one and use color tokens to style this.

**Comment by daviddossett** [comment]
I looked into this once—adding CSS vars to the SVGs works fine on intitial render, but they don't update when the theme is changed unless the window is reloaded. Any ideas @aeschli?

**Comment by misolori** [comment]
the svg is used as a background image so it doesn't leverage the power like our walkthroughs that are inlined as SVG. [I started a branch](https://github.com/microsoft/vscode/tree/misolori/surprising-cockroach-watermark) to look into this but it was a bit more involved than a "quick fix".

**Comment by daviddossett** [comment]
Ah that explains it. I'm happy to take a crack on this if I have some downtime in the coming weeks.

**Comment by daviddossett** [comment]
Closing since it's unlikely I will get to this in the next six months. Will reopen as needed.
