### ISSUE TITLE
Support generic scroll bar mark sequences (OSC 1337 ; SetMark)

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151769]
Windows Terminal added this recently, there's a bunch of info/research available on https://github.com/microsoft/terminal/issues/11000 and https://github.com/microsoft/terminal/pull/12948

This may be useful in https://github.com/microsoft/vscode/issues/150833 depending on how clever we want the task integration to be.

https://iterm2.com/documentation-escape-codes.html

**Comment by zadjii-msft** [comment]
lmao I was largely inspired by you guys 😅 I saw https://code.visualstudio.com/updates/v1_65#_terminal-shell-integration and was like _yea now this is a good idea_

**Comment by Tyriar** [comment]
@zadjii-msft hehe. If you go down the full blown shell integration route I can walk you through all the hacks needed to get it working through conpty 😉, It's working quite well now for pwsh but it took a while to get right.

**Comment by Tyriar** [comment]
If we had a generic mark system we could use them in `PartialCommandDetectionCapability` so mark decorations show up in the buffer even when shell integration is disabled.

**Comment by Tyriar** [comment]
This would be a good icon for generic marks:

![image](https://user-images.githubusercontent.com/2193314/173870493-5aafcbd3-6a94-40b7-956b-b158f3447e2e.png)

@misolori should we add an alias for that and/or create a `dot` codicon?

**Comment by misolori** [comment]
@Tyriar that one is specific to the debug icon as it's overlayed and aligned to fit within another icon. we have other dots but also happy to introduce a smaller one if that is desired:

<img width="493" alt="CleanShot 2022-06-15 at 09 54 43@2x" src="https://user-images.githubusercontent.com/35271042/173883262-87dd2817-b9e2-4f58-a9ef-68d2c5b6ef7d.png">

**Comment by misolori** [comment]
Ok, I can add in a request to add a smaller one
