### ISSUE TITLE
Terminal abnormal  display

### ISSUE THREAD

**Issue by leosx** [microsoft/vscode#151708]
System version: Ubuntu 20.04.3 LTS

VSCode info: 
Version: 1.68.0
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:49:57.055Z

Electron: 17.4.7

Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 [5.13.0-48-generic]
![2022-06-10 02-41-00 的屏幕截图](https://user-images.githubusercontent.com/3094492/173038155-6b7939fe-e09d-4b39-90b4-6cc7f3862fd8.png)

I enter command is: pwd

**Comment by meganrogge** [comment]
did this just start happening recently?

does changing `terminal.integrated.gpuAcceleration` help?

**Comment by leosx** [comment]
> 

"terminal.integrated.gpuAcceleration": "off"  is useful
