### ISSUE TITLE
show task icon/colors in the task quick pick 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151758]
Once we have #145965, we should show them in the task quick pick like we do with the terminal profiles
![Screen Shot 2022-06-10 at 8 33 14 AM](https://user-images.githubusercontent.com/29464607/173100446-89015f5c-da40-4095-935a-b27445202b84.png)

**Comment by Tyriar** [comment]
Good idea, I guess use the default tools icon when they're not specified as it would probably look a bit off if some had icons and some not?

![image](https://user-images.githubusercontent.com/2193314/173127057-d1da6033-6722-4e31-9334-6d21dc6dae9c.png)

The downside is there will be a lot of repeated icons but it's consistent with terminal then.

**Comment by meganrogge** [comment]
We can also see how it looks. fyi @misolori

**Comment by misolori** [comment]
I can understand if someone configures their task to use icons (I use this in some projects) but i wouldn't necessarily add an icon for every single task as @Tyriar mentioned these would look necessarily busy. This doesn't look bad:

<img width="223" alt="CleanShot 2022-06-10 at 13 09 07@2x" src="https://user-images.githubusercontent.com/35271042/173143098-507e13b8-573b-4a2c-90ef-672a8b879f19.png">

**Comment by meganrogge** [comment]
I think it will be useful to quickly distinguish between tasks.

**Comment by Tyriar** [comment]
@misolori I'd love the ability to differentiate test tasks, especially test from build:

![image](https://user-images.githubusercontent.com/2193314/173150570-7842d724-0a7f-42db-b0c5-b27146aa826f.png)

**Comment by misolori** [comment]
Wouldn't you still be able to achieve this without the need of adding default icons for tasks, since those would be configurable? My main question about the problem this is solving was adding default icons for every task.

**Comment by Tyriar** [comment]
@misolori you'd need to set the icon whenever you launch the task though, don't know about you but I kill and create them a bunch each day. A related proposal I had was to configure a test vs build task icon (closed as out of scope I think?), that's an alternative approach to https://github.com/microsoft/vscode/issues/145965.

**Comment by misolori** [comment]
I think we're talking about different things. I'm in support of allowing icons to be configured for tasks. What I'm questioning is whether or not there would be default icons for all tasks.

**Comment by Tyriar** [comment]
I don't have strong feelings about the icons showing or not in the quickpick. Tasks do have the tools icon as the default is what I meant.

**Comment by meganrogge** [comment]
I was envisioning only showing icons if they're set to something - so excluding the default tools icons.

**Comment by meganrogge** [comment]
<img width="324" alt="Screen Shot 2022-06-13 at 12 47 03 PM" src="https://user-images.githubusercontent.com/29464607/173433730-4cefe46c-07b4-4658-be3d-51d930fe1797.png">

**Comment by meganrogge** [comment]
🤔 
<img width="645" alt="Screen Shot 2022-06-13 at 12 53 21 PM" src="https://user-images.githubusercontent.com/29464607/173434017-867e591b-8fdc-4981-88fb-d9201187ef85.png">

**Comment by meganrogge** [comment]
I'd like to have the others scoot over so their labels are all still aligned

**Comment by meganrogge** [comment]
<img width="618" alt="Screen Shot 2022-06-13 at 12 54 37 PM" src="https://user-images.githubusercontent.com/29464607/173434194-56a08643-f363-4894-b799-cced08c5d180.png">

**Comment by usernamehw** [comment]
Is there now api to show icon with color in quick pick?

**Comment by alexr00** [comment]
I still prefer @misolori's suggestion in https://github.com/microsoft/vscode/issues/151758#issuecomment-1152701677

**Comment by Tyriar** [comment]
@usernamehw this feature will let you set it in tasks.json:

![image](https://user-images.githubusercontent.com/2193314/173578903-6ceeeb9b-3184-4d37-a456-f1b668feb40c.png)

@misolori I think this might be the first quick pick that has mixed icons, outside of what was there for tasks before anyway:

![image](https://user-images.githubusercontent.com/2193314/173579187-b2f812b2-f3fb-48a5-bdcf-717963349df4.png)

Do you think we should we align the text?

**Comment by misolori** [comment]
I don't think we need to align the text because it can start to look like a parent/child tree node. We also don't currently do this in the quick pick where you can have a mix of icons and no icons.

**Comment by meganrogge** [comment]
@Tyriar what are you planning to tweak?
