### ISSUE TITLE
runtimeExecutable option for extensionHost type launch configuration not working

### ISSUE THREAD

**Issue by pasha009** [microsoft/vscode#151789]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0-insider
- OS Version: Windows_NT x64 10.0.19044

I followed the steps outlined [here](https://code.visualstudio.com/api/get-started/your-first-extension) to generate the hello-world extension. I downloaded an older version of VS Code and updated launch.json to use that version.

Steps to Reproduce:

1. Scaffold a hello-world code extension project using yeoman (`yo code`).
2. Download an older version of VS Code (say 1.51.1).
3. Update `runtimeExecutable` config option in `launch.json` to point to the executable
```json
{
	"version": "0.2.0",
	"configurations": [
		{
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "C:\\Users\\shrutepa\\src\\hello-world\\bin\\vscode-win32-archive-1.51.1\\Code.exe",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}"
			]
		},
		{
			"name": "Extension Tests",
			"type": "extensionHost",
			"request": "launch",
			"runtimeExecutable": "C:\\Users\\shrutepa\\src\\hello-world\\bin\\vscode-win32-archive-1.51.1\\Code.exe",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--extensionTestsPath=${workspaceFolder}/test/suite/index"
			]
		}
	]
}

```
4. Run the 'Run Extension' launch config. A new VS Code instance will open. Observe that it's version is not `1.51.1`.
<img width="904" alt="Screenshot 2022-06-11 at 1 18 06 AM" src="https://user-images.githubusercontent.com/42747197/173139733-5e6a22fc-1a00-4726-a77a-4066fcf9563f.png">

---

I have already verified that the specified executable is working.

**Comment by weinand** [comment]
The property `runtimeExecutable` is not supported for extension debugging.
Extension debugging always uses the VS Code version of the debugger.
