### ISSUE TITLE
Tasks no longer execute with Version: 1.68.0 (Universal)

### ISSUE THREAD

**Issue by arobinson** [microsoft/vscode#151759]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.68.0 (Universal) Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
- OS Version: Mac OSX 12.4 (21F79)

Steps to Reproduce:

1. Use a custom tasks.json file
2. Try to run a task
3. Says task is executing, but no evidence the program was run, no output
4. Was working until updating to 1.68.0

Example output:
```
> Executing task: /Users/andrew/development/work/client/work-copy/project-dir/node_modules/.bin/ng run project:clean <


Terminal will be reused by tasks, press any key to close it.
```

Task definition:
```
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
...
    {
      "type": "process",
      "label": "Clean",
      "detail": "Does a clean of the generated files",
      "command": "${workspaceFolder}/project-dir/node_modules/.bin/ng",
      "args": [ "run", "project:clean" ],
      "group": "build",
      "options": {
        "cwd": "${workspaceFolder}/project-dir"
      }
    },
...
}
```

**Comment by arobinson** [comment]
Potentially related?
https://github.com/microsoft/vscode/pull/141230

**Comment by alexr00** [comment]
It's very strange the simply re-downloading 1.68 solved the issue. Let's leave this issue open for a bit and see if anyone else sees the issue. Otherwise, this may have just been some transient OS issue.

**Comment by Jensderond** [comment]
I've tried to manually re-downloading and overwriting the old application, but I'm stuck in "Fetching build tasks" since the new update.

**Comment by alexr00** [comment]
@Jensderond can you disable all extensions and see if the issue persists?

**Comment by Jensderond** [comment]
@alexr00 That indeed does work, thanks!. I've tried turning extensions off one-by-one and it turns out that [formulahendry.auto-rename-tag](https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag), is causing this issue for me (it has 9+ mil installs though)
