### ISSUE TITLE
Last line of multiline strings in debug console not shown

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode#151768]
**To Reproduce**
1. Start a debug session and open the debug console
2. Type `"one\ntwo\nthree"` and press enter
3. Observe the echoed output is
   ```
   'one
   two
   ```

<img width="489" alt="image" src="https://user-images.githubusercontent.com/3277153/142686510-18ff44bc-5e33-4a18-8515-f66986ccd5af.png">

**Log File**

**VS Code Version:**

Version: 1.63.0-insider
Commit: d450b04c783dfa6f83dc439017767acccd4e9fac
Date: 2021-11-17T07:45:14.150Z (2 days ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

Node used in debug session: 16.13.0.

**Comment by andrewbranch** [comment]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/3277153/173134319-6f8c36d7-cf0e-41a1-a51d-6fa0e09971f7.png">

Line height is 0 (auto)

**Comment by andrewbranch** [comment]
Terminal-specific stuff:

<img width="981" alt="image" src="https://user-images.githubusercontent.com/3277153/173134455-36a2987f-ff3e-4015-a74f-c9dc5cdfe8e1.png">

**Comment by andrewbranch** [comment]
Sure enough, when I build VS Code from source, this doesn’t repro 😮 

It still does repro in Insiders with all my extensions disabled. Is there a way to launch a VS Code window with all default settings?

**Comment by andrewbranch** [comment]
It also doesn’t repro in my installation of VS Code stable, which I pretty much never use!! I even turned on Settings Sync and replaced the local settings with what was in the cloud. I can’t figure out what the difference is.

**Comment by roblourens** [comment]
The debug console has its own font/line height settings. 

You can start code-insiders with `--user-data-dir /tmp/codedata --extensions-dir /tmp/codeext` or just temporarily copy your settings into another file and clear out settings.json. Might help to share the original heights of the `.monaco-list-rows` and `.monaco-list-row` elements too

**Comment by andrewbranch** [comment]
This was the culprit.

<img width="439" alt="Debug Console Word Wrap is disabled" src="https://user-images.githubusercontent.com/3277153/173637296-0b30ad69-56af-4c96-8451-4d1446ad6881.png">

I don’t recall why I disabled it, but that’s still a bug, right?

**Comment by roblourens** [comment]
I can repro it now, thanks!

**Comment by roblourens** [comment]
Crap, this is not quite right

**Comment by roblourens** [comment]
It was fixed for an OutputEvent but still off by a line for an evaluation result

**Comment by alexr00** [comment]
What's the best way to verify this?

**Comment by roblourens** [comment]
- `"debug.console.wordWrap": false`
- Debug JS, enter `"one\ntwo\nthree"` and `console.log("one\ntwo\nthree")` in the debug console, make sure that all messages are sized correctly. You could check some other cases too.
