### ISSUE TITLE
update to v0.10.5 can't open 

### ISSUE THREAD

**Issue by looveu** [Microsoft/vscode#1517]
![2015-12-21 10 44 29](https://cloud.githubusercontent.com/assets/3917750/11922235/1570f750-a7d0-11e5-8aa8-02258e5b462b.png)

**Comment by cuigh** [comment]
same with me

**Comment by bgse** [comment]
Check here, might be your issue:

https://github.com/Microsoft/vscode/issues/1463

**Comment by looveu** [comment]
https://github.com/Microsoft/vscode/issues/1463
