### ISSUE TITLE
'Reload Required' which never goes away for builtin extensions

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#151770]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Open insiders.vscode.dev
2. Open the extensions view with the `@builtin` query
3. :bug: I see two extensions which say Reload Required (Codespaces and Remote Repositories say I have to reload to complete uninstallation.)
4. :bug: No amount of clicking reload actually gets the reload required button to go away

**Comment by sandy081** [comment]
I cannot repro it. May be fixed with latest insiders? Can you still see it>

**Comment by joyceerhl** [comment]
Seems fixed now. Thanks :)
