### ISSUE TITLE
Pure white color is displayed as black in the intergrated terminal.

### ISSUE THREAD

**Issue by Dan-Gamin** [microsoft/vscode#151719]
Does this issue occur when all extensions are disabled?: **\*Yes\***/No

I updated my vs code version and I noticed that my terminal's prompt is black for some reason. I opened it up in windows terminal but I saw white.

![Terminal colors being broken](https://user-images.githubusercontent.com/58695417/173049202-1a51078d-adbb-4390-9e0c-fcabc78b5d0a.png)

As you can see, the white color as shown in windows terminal is black in the vs code terminal. All extensions are disabled in the above screenshot.

**REMINDER:** This only applies to **pure** white color (`\e[38;5;231m`), not regular white. (`\e[37m`)

- VS Code Version: 1.68.0
- OS Version: Windows 10

Steps to Reproduce:

1. Open a terminal which shows pure white color in the integrated vscode terminal.
2. There is no step 2.

**Comment by meganrogge** [comment]
I cannot reproduce in insider's.

1. Can you?
2. If so, does changing `terminal.integrated.minimumContrastRatio` to 1 help?

![Screen Shot 2022-06-10 at 6 53 47 AM](https://user-images.githubusercontent.com/29464607/173080874-2d4ed4b8-4057-41e1-8033-6228935d4899.png)

**Comment by Dan-Gamin** [comment]
> I cannot reproduce in insider's.
> 
>     1. Can you?
> 
>     2. If so, does changing `terminal.integrated.minimumContrastRatio` to 1 help?
> 
> 
> ![Screen Shot 2022-06-10 at 6 53 47 AM](https://user-images.githubusercontent.com/29464607/173080874-2d4ed4b8-4057-41e1-8033-6228935d4899.png)

actually i believe it only happens when using a background color.

![image](https://user-images.githubusercontent.com/58695417/173088584-5205fb1e-184f-4f61-a97d-df66062855c0.png)

the color code of `48;5;48;38;5;231m` has 2 parts, the background color: `48;5;48;` (neon green) and the foreground color: `38;5;231m`.  (white)

**Comment by Tyriar** [comment]
@Dan-Gamin good to hear 👍 I also created https://github.com/microsoft/vscode/issues/151749 to improve the black in the inverted powerline symbols.
