### ISSUE TITLE
The `onDidUpdateKeybindings` doesn't set `keybindings`-property when resetting a KB

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#151712]
* subscribe to the `onDidUpdateKeybindings`-event
* redefine a built-in keybinding, you receive an event with the keybinding
* reset the custom keybinding
* 😕 you receive an event but it doesn't contain any `keybindings`

**Comment by jrieken** [comment]
Related to https://github.com/microsoft/vscode/blob/678f89cc446c293d55b7fe123f6c7657162a88f9/src/vs/workbench/browser/parts/titlebar/commandCenterControl.ts#L153 which made me update the command center more often than wanted

**Comment by alexdima** [comment]
The `.keybindings` property in that event makes no sense. It is either empty or contains all user keybindings and it was added via https://github.com/microsoft/vscode/commit/9ce4d4c80e97ada8799117559d7262b3ac8b2fdc#diff-bea327387abe7bd80757ccf10bf4fc036f7b85ed131cdb5605cd61c2a153c09dR54 . I suggest to not depend in any way on it, we should remove it.
