### ISSUE TITLE
PowerShell background colour issue

### ISSUE THREAD

**Issue by LordOfRaptor-max** [microsoft/vscode#151728]
Issue Type: <b>Bug</b>

The Foreground colour is not working anmore if you have another background colour than black
Same issue for both pwsh 7.2.4 and powershell 5.1

$Host.UI.RawUI.ForegroundColor = 'White'; $host.UI.RawUI.BackgroundColor = "Red"
#Above is just getting red with black foreground.

$Host.UI.RawUI.ForegroundColor = 'green'; $host.UI.RawUI.BackgroundColor = "Red"
#Still getting just black as foreground.

$Host.UI.RawUI.ForegroundColor = 'blue'; $host.UI.RawUI.BackgroundColor = "black"
#This is working, as long as I use black as background colour I can change foreground colour.

All above commands works in native 5.1 powershell and 7.2.4 pwsh

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.27GB free)|
|Process Argv|--crash-reporter-id 6c3edae6-7330-42cd-86ad-5d1e5550a26e|
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
xml|Dot|2.5.1
gc-excelviewer|Gra|4.2.54
rainbow-csv|mec|2.4.0
powershell|ms-|2022.5.1
vscode-typescript-next|ms-|4.8.20220609

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by Tyriar** [comment]
See https://code.visualstudio.com/updates/v1_68#_improvements-to-contrast-and-the-minimum-contrast-ratio
