### ISSUE TITLE
Hover on "this" says undefined, which is wrong

### ISSUE THREAD

**Issue by sylvainlap** [Microsoft/vscode#15173]
- VSCode Version: 1.7.1
- OS Version: Win10

Steps to Reproduce:

1. See the screenshot, "this" inside my arraow function is "undefined" when I put my cursor on it
![2016-11-08 1](https://cloud.githubusercontent.com/assets/8457604/20101710/73dab99c-a5c3-11e6-8fd7-e5a0a7d56ed8.png)

2. In the upper left corner, we can see this: undefined

3. However, if I evalute "this", I get the right "this" in the console (as you can see in the above screenshot)

Why the difference between the "this" when I hover it, and when I evaluate it ?

Regards,
Sylvain

**Comment by isidorn** [comment]
This is happening because hover does not have scope information when it is searching for the value to show. This is already captured in https://github.com/Microsoft/vscode/issues/15172 and this is planned to be tackled in november

**Comment by sylvainlap** [comment]
OK, thanks !
