### ISSUE TITLE
What happened to the Remote Explorer view?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#151755]
this seems to only happen on Codespaces when I only have Codespaces and no other Remote target

![image](https://user-images.githubusercontent.com/2644648/173097687-e64f5ed1-70cd-4a38-9471-f8577ca257f3.jpeg)
![image](https://user-images.githubusercontent.com/2644648/173097703-51eceb05-5f88-426f-b20b-fc07012f66a9.jpeg)

**Comment by alexr00** [comment]
This is done intentionally by Codespaces. They don't statically register any views in the Remote Explorer in the browser.
