### ISSUE TITLE
A black line under window control buttons when `window.experimental.windowControlsOverlay.enabled` is turned on

### ISSUE THREAD

**Issue by CodeCrazy-ywt** [microsoft/vscode#151834]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0
- OS Version: Windows 11 21H2

Steps to Reproduce:

1. Turn on `window.experimental.windowControlsOverlay.enabled` and restart VSCode
2. Observe what appears below window control buttons

Here are the screenshots with `window.experimental.windowControlsOverlay.enabled` turned off and on.
![屏幕截图 2022-06-11 214604](https://user-images.githubusercontent.com/62426149/173190528-e970d3f7-48ca-48bb-b2ee-4474581657de.jpg)
![屏幕截图 2022-06-11 214649](https://user-images.githubusercontent.com/62426149/173190562-032be914-3d16-46b5-8799-d8601a418d6e.jpg)

**Comment by gjsjohnmurray** [comment]
Also reported by @bpasero at https://github.com/microsoft/vscode/pull/147947#pullrequestreview-950923913

**Comment by ArturoDent** [comment]
And see Duplicate: https://github.com/microsoft/vscode/issues/150778
