### ISSUE TITLE
Vscode terminal showing nothing

### ISSUE THREAD

**Issue by kandoihanish** [microsoft/vscode#151844]
My code is running in terminal showing nothing .
I don't know what to do now.
I deleted complete vs code setup completely and downloaded it again but problem not solved.
![16549706180006480206804419507080](https://user-images.githubusercontent.com/105071613/173199671-62199699-5fdb-4c9e-a859-cec98a38eaef.jpg)

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"
