### ISSUE TITLE
remote-ssh connect error: "version mismatch"

### ISSUE THREAD

**Issue by yuwgle** [microsoft/vscode#151813]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
Version: 1.68.0 (user setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

- Extensions: Remote-SSH
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Simply connect to host. And it automatically downloads [4af164ea3a06f701fe3e89a2bcbb421d2026b68f] code-server.
2. Shows "version mismatch" error.
![image](https://user-images.githubusercontent.com/11690711/173170524-73aabe61-81f2-44aa-b804-a3bf87ccbf8c.png)

When I click [Open is browser], it cames up:
![image](https://user-images.githubusercontent.com/11690711/173170540-8faba596-3434-46f3-9e04-ef2fc1dd89de.png)

May be it's a version number update mistake ?

**Comment by yuwgle** [comment]
> When you say code-server are you using this code-server? https://github.com/coder/code-server This is not officially supported

No. The [code-server] is automatically download by remote-ssh  plugin. 
The download url is [https://update.code.visualstudio.com/commit:8dfae7a5cd50421d10cd99cb873990460525a898/server-linux-x64/stable].

**Comment by roblourens** [comment]
Not sure how this happened, it looks like we are forwarding the server from the previous vscode version. Can you share the Remote-SSH output channel log? But updating to 1.68.1 might fix it for you. Running "Kill VS Code server on host" would also kill it

**Comment by yuwgle** [comment]
> Not sure how this happened, it looks like we are forwarding the server from the previous vscode version. Can you share the Remote-SSH output channel log? But updating to 1.68.1 might fix it for you. Running "Kill VS Code server on host" would also fix it


Sorry, I want to continue my work, so I have downgraded my vscode to 1.67 and it works fine. 
I don't have ver1.68 any more, so  I can't take the ver1.68 's remote-ssh log.

But when I upgrade to  ver1.68.1, it works fine.

**Comment by roblourens** [comment]
That's ok - if it happens again, please share the log, thanks.
