### ISSUE TITLE
Bash (Windows Subsystem for Linux) - Running without the SUID sandbox!

### ISSUE THREAD

**Issue by mrichman** [Microsoft/vscode#15180]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Enterprise 1607 (OS Build 14393.0) running Windows Linux Subsystem beta

Steps to Reproduce:

1. Install VS Code 1.7.1 Debian package on Bash on Ubuntu on Windows (`dpkg -i code_1.7.1-1478180561_amd64.deb`)
2. Run code (`code --verbose` shows errors).

```
$ code --verbose
[27:1108/102524:ERROR:browser_main_loop.cc(231)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
[27:1108/102524:FATAL:render_sandbox_host_linux.cc(40)] Check failed: 0 == shutdown(renderer_socket_, SHUT_RD). shutdown: Invalid argument
#0 0x000001e0962e <unknown>
#1 0x000001e1f23b <unknown>
#2 0x000001e1f7fd <unknown>
#3 0x000002892e52 <unknown>
#4 0x00000265e2f9 <unknown>
#5 0x0000026648bf <unknown>
#6 0x00000265d996 <unknown>
#7 0x000001203e97 <unknown>
#8 0x000001202970 <unknown>
#9 0x0000033a9313 main
#10 0x7fd9a7ae1f45 __libc_start_main
#11 0x000000574d79 <unknown>
```

**Comment by mrichman** [comment]
Looks like this is an issue with WSL not implementing the `shutdown` socket syscall. https://github.com/electron/electron/issues/6722. Any workaround, or are we waiting on MSFT to fix WSL?

**Comment by bpasero** [comment]
I would say that we currently do not support to run Code on the Windows Linux subsystem, nor do we have plans to support this in the near term. Any low level issue you see there is likely caused by upstream components and nothing we can fix.

**Comment by mrichman** [comment]
Yep, looks like the latest Insider build of Windows 10 fixes this issue. I don't have access to that build yet though.
