### ISSUE TITLE
Github authorization and Python extension

### ISSUE THREAD

**Issue by DarthGoober** [microsoft/vscode#151805]
Issue Type: <b>Bug</b>

Hello, I have two problems but it very well could be user error. I am new to programming and just downloaded VS code a couple of days ago. My first problem is that I can't login to Github. I tried pressing the settings sync and following the promps as well as tried logging in through the github extension but I keep getting an error that I havn't finished setting up authorization. The second problem is that the python extension just loads forever. I followed all the steps for setting up python in vs code but it will never load. I have tried all the typical recommendations I have found online so far including uninstalling/reinstalling both the extensions and vs code itself. I can't figure out what to do. 

I have been able to login into github throught the cs50 codespace with no problem while I am taking that course, but I can't get the desktop version to work at all. 

Thank you for any help you may have!

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:00.250Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y32 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 6|
|Memory (System)|8.00GB (0.26GB free)|
|Process Argv|--crash-reporter-id e7509e9e-cb6a-4744-bb57-9dea78b49b49|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-mysql-client2|cwe|5.4.0
gitlens|eam|12.0.7
codespaces|Git|1.8.3
vscode-pull-request-github|Git|0.44.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by DarthGoober** [comment]
I figured out what it was!

**Comment by TylerLeonhardt** [comment]
@DarthGoober what was it? :)

**Comment by DarthGoober** [comment]
I had an app called canopy installed on my computer that blocks/monitors content for my family. I was thinking through every possible thing that could be affecting my computer and remembered that I had issues connecting to public WiFi when I first installed canopy. I uninstalled it, restarted my computer, and vs code immediately started working no problem!
