### ISSUE TITLE
Experimental paste actions prevent pasting in the find command

### ISSUE THREAD

**Issue by liyuhang1997** [microsoft/vscode#151801]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0
- OS Version: Windows 11

Steps to Reproduce:

1. Turn on `"editor.experimental.pasteActions.enabled": true`
2. Open an `.md` file, use the `find` command, and pasting some text.
3. The text will be pasted into the file instead of into the input box of the find command.

**Comment by ArturoDent** [comment]
Appears to be a markdown file specific.  Same behaviour in Insiders.

Version: 1.69.0-insider (user setup)
Commit: ab6ba241145bb81c8bc0f323453bbec45fd66109
Date: 2022-06-10T05:16:34.957Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.25136

**Comment by PabloLION** [comment]
Tested with M1 Mac. I got the same issue.

**Comment by PabloLION** [comment]
I tested with the latest insider version and it seems to be solved already. According to @mjbvz, we can close this issue as well?

Version: 1.69.0-insider
Commit: 173f4bea73601a31859372b409cac2c20fa91194
Date: 2022-06-24T06:32:21.351Z (2 days ago)
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.3.0
