### ISSUE TITLE
Modal dialog button's order is invalid on Ubuntu.

### ISSUE THREAD

**Issue by YoshihideShirai** [microsoft/vscode#151874]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0-1654690107
- OS Version: Ubuntu 22.04 LTS

I write vscode extension source, such as
~~~javascript
        const confirmYes = await vscode.window.showWarningMessage(
          'AsciiDoc extension will execute scripts in workspace(.asciidoctor/lib/*.js). Do you trust authors of scripts in workspace?',
          { modal: true },
          { title: 'Yes, I trust the authors.', value: true },
          { title: 'No, I don\'t trust the authors.', value: false })
~~~

I tried to test the following

On Windows:
![image](https://user-images.githubusercontent.com/19510962/173234740-29f27382-8c00-4f3d-b2c5-b0ea7b8dc672.png)

On Ubuntu:
![image](https://user-images.githubusercontent.com/19510962/173234747-d4384b7c-3e4e-4398-8fc6-b1809b520d12.png)

Button order is invalid on Ubuntu.
Is it possible to configure button order?

**Comment by sbatten** [comment]
The order is OS dependent and we add a Cancel button.

e.g. if you show a warning message with buttons A, B, that gives us the order A, B, C(ancel).  The first item is considered the primary action and cancel is the cancel action.

On Windows, the behaviour is: Primary, other actions, Cancel Action.
On Mac/Linux, the behaviour is: Other actions (reversed), Cancel Action, Primary Action.
