### ISSUE TITLE
Ability to publish prerelease build streams of extensions and opt-in

### ISSUE THREAD

**Issue by joelday** [microsoft/vscode#15188]
- Feature Request
I'd like to be able to publish a prerelease stream of my extension without publishing an entirely separate extension with a different ID. Would be ideal to have this be accessible to opt into in the extensions panel.

Thanks!

**Comment by joaomoreno** [comment]
There are two scenarios here:

One, you want to have new features of your extension available to only a subset of your users, using some opt-in mechanism. You should simply publish new versions of your extension with the new functionality behind configuration settings as an opt-in mechanism.

Two, you want to benefit from new vscode API which is not yet available in the current stable version, but is in the current insider release. For this, you'll need to change the `engines.vscode` value in your `package.json` to be compatible with the insider's version of Code, eg: `^1.8.0`.

Is there any other scenario I am missing here?

**Comment by joelday** [comment]
@joaomoreno Thanks for the reply!

This is what I'm thinking aside from whatever the right approach would be:
1. Users can easily opt into high-frequency updates that may be unstable.
2. Users can easily discover the option to switch to it.
3. A developer's CI process can publish this nightly build.
4. The nightly builds do not spam stable stream users with updates to install.
5. Developer can add and experiment with features with at a high frequency without potential destabilization of the stable build.
6. Users can help find issues with additions before pushing them to stable.
7. Developers can provide nightly builds without bloating the vsce published extension list with separate extension IDs, pages, reviews, etc.
8. Developers do not have to accommodate/protect against the scenario in which a user has inadvertently installed both the stable and nightly streams.

Put really simply, tons of projects have separate nightly builds. People can install nightly builds of NPM packages. The provided value of doing that can probably apply to extensions.

**Comment by joaomoreno** [comment]
Thanks for the very detailed points! 👍

**Comment by joelday** [comment]
Thank you!

**Comment by ntotten** [comment]
This is something that would be very helpful to us for the Salesforce extensions. We have a few scenarios:
1) Ability to have public opt-in previews
2) Ability to have public opt-in of daily builds
3) Ability to publish an extension that is only discoverable if you have the link - this would be for when we want to give a small group of people access to a preview feature.

Basically, this can be boiled down to supporting different streams. 1) Daily 2) Preview 3) Private Preview 4) GA
