### ISSUE TITLE
inlineValues setting causes breakpoints to jump to wrong line

### ISSUE THREAD

**Issue by jpike88** [microsoft/vscode#151822]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.68.0
- OS Version:macOS Monterey 12.4

Steps to Reproduce:

1. enable debug:inlinevalues setting
2. fire up an app using `pwa-chrome`
3. breakpoint, and trigger it4. 

Example: I breakpoint at line 166.

With inlineValues enabled, I jump ABOVE that line (see screenshot), I have to scroll down to find where the breakpoint is set
<img width="1068" alt="Screen Shot 2022-06-11 at 15 28 14" src="https://user-images.githubusercontent.com/9585787/173180097-ce34906d-6a83-4601-8328-3417c8ef8db0.png">

With inlineValues disabled, I always jump to correct line (see screenshot), and it's right in the middle.
<img width="1080" alt="Screen Shot 2022-06-11 at 15 29 03" src="https://user-images.githubusercontent.com/9585787/173180133-81a7584c-217b-40a3-910a-e354752bc2a3.png">

It looks like the inline values are multi-line, and this is causing the breakpoint focus to occur too early, which causes the lines to 'expand' pushing the correct one out of view.

only workaround is to disable inlineValues altogether until this is solved

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/150083
