### ISSUE TITLE
Debug hovers disappear often when trying to mouse into them

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#151816]
- VS Code Version: `1.68.0-insider`
- OS Version: `Windows_NT x64 10.0.22621`

Report split out of https://github.com/microsoft/vscode/issues/151683#issuecomment-1151972092

Here is the debug hover being very finicky -- making it really hard to copy any text out of it.
![hiding](https://user-images.githubusercontent.com/641685/172998990-915aa45f-c27f-42c6-bfad-69698a6de5e9.gif)

This seems to happen a LOT of the time for me, and it doesn't matter if it's a simple hover like above or one that has rich details:

![debug-hovers](https://user-images.githubusercontent.com/641685/173174950-5e3c0731-2774-4cd6-a246-83820f1300e6.gif)

You can also see even the times where the hover didn't hide by itself, it still moved

/cc @weinand @alexdima

**Comment by roblourens** [comment]
I was debugging suspicious code in that area in https://github.com/microsoft/vscode/issues/151019, I think this can be merged into that
