### ISSUE TITLE
Cannot debug a webextension that depends on another extension

### ISSUE THREAD

**Issue by ilyagr** [microsoft/vscode#151815]
Issue Type: <b>Bug</b>

This bug occurs in normal desktop Linux version of VS Code, but only for *web*extensions.

1. Check out the source of any webextension, for example the sample `helloworld-web-sample` (here is the [commit I used](https://github.com/microsoft/vscode-extension-samples/tree/52679f289a1ba34c27fd1504ae7b0a9275505586/helloworld-web-sample)).

	I also tried this with the boilerplate extension you get by using `yo code` as suggested in [the guide](https://code.visualstudio.com/api/extension-guides/web-extensions), with the same result.

2. Add an `extensionDependencies` field to `package.json`. For example, I added

	```
	 "extensionDependencies": ["ms-python.python"],
	 ```
	 
	I also tried this with `gregoire.dance` or `ms-python.vscode-pylance` instead of Python, with the same result.

3. Run `npm install` in that directory, open VS Code in it, make sure the `Python` extension is installed.
4. Debug the extension with `F5`. Try to activate the extension, e.g. by pressing `Ctrl+Shift+P` and running the `Hello, World` command the extension provides.

## Expected result:
The command works. (This is what happens if you started with a normal extension such as `helloworld-sample`, or if you skip step 2).

## Actual result:
You get two error messages "command helloworld-web-sample-helloWorld not found" and "Cannot activate the 'helloworld-web-sample' extension because it depends on the 'Pylance' extension which is not loaded." The latter message has a "Reload Window" button, but it doesn't help.

![Screenshot 2022-06-10 9 49 17 PM](https://user-images.githubusercontent.com/4123047/173173097-9ed29ed9-1dad-4038-be24-b0ee3d191ab1.png)

VS Code version: Code - Insiders 1.69.0-insider (ab6ba241145bb81c8bc0f323453bbec45fd66109, 2022-06-10T06:23:32.996Z)
OS version: Linux x64 5.10.110-15808-ge5740beba59b
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz (4 x 2591)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 1, 1|
|Memory (System)|6.45GB (6.43GB free)|
|Process Argv|. --crash-reporter-id 3cc33ccb-4c87-49cf-90e4-69944c0c944e|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|undefined|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|undefined|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by weinand** [comment]
@sandy081 Is it possible to have a web extension depend on a regular extension (here: "ms-python.python")?

**Comment by ilyagr** [comment]
As far as I understand, `ms-python.python` is both a normal extension and a webextension. It should have both `main` and `browser` entrypoints in `package.json`. This is certainly the case for `gregoire.dance`, you can try others.

**Comment by ilyagr** [comment]
Thank you very much for the suggestions! For future readers, it took me a second to figure out that  extension files live in `~/.vscode/extensions` and can be edited or copied from there.

Your second suggestion -- of a custom runner path -- seemed to work for me. In fact, I didn't even need to copy the files. On Linux, adding following to `launch.json` worked for me (though, this approach might be less robust than copying the files as you suggested):

```json
{
	"name": "Run Web Extension With Web dependencies",
	"type": "pwa-extensionHost",
	"debugWebWorkerHost": true,
	"request": "launch",
	"args": [
		"--extensionDevelopmentPath=${workspaceFolder}",
		"--extensionDevelopmentPath=${userHome}/.vscode/extensions/gregoire.dance-0.5.11",
		"--extensionDevelopmentKind=web"
	],
	"outFiles": [
		"${workspaceFolder}/dist/web/**/*.js"
	],
	"preLaunchTask": "npm: watch-web"
}
```

Strangely, the suggestion of editing `package.json` to remove the `main` entry only worked half the time. It worked for the Python extension, but did not work for `gregoire.dance`. Confusingly, after removing `main`, VS Code still seemed to try to load it as a normal extension according to the "Extensions Running" page. The extension ended up broken as VS code could no longer find the JS files for the Dance extension. 

I'm not sure why the behavior of the two extensions differs. I do know Dance works on `github.dev`, so it does function as a web extension. Also, the first approach did seem to work for it.
