### ISSUE TITLE
Change in AutoSave feature has broken with new insiders builds

### ISSUE THREAD

**Issue by vraravam** [microsoft/vscode#151884]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.0-insider (Commit: ab6ba241145bb81c8bc0f323453bbec45fd66109)
- OS Version: macos 12.4

Steps to Reproduce:

1. In Settings, for autosave, choose: `OnFocusChange`
2. Open a file
3. Edit it ie make some change
4. Alt+Tab to some other open application
5. See that though the window itself has lost focus (which should trigger the `focusChanged` event up above), but the file is still considered dirty and not yet saved

This used to work fine till a few days/weeks ago (not sure when I upgraded to the newer nightly). My guess is that this bug was introduced when the new option for `OnWindowChange` was introduced.

**Comment by bpasero** [comment]
I cannot reproduce.

> My guess is that this bug was introduced when the new option for OnWindowChange was introduced.

What means?

**Comment by vraravam** [comment]
I noticed this morning that this was not reproducible. Will try with one more item

**Comment by vraravam** [comment]
Figured out the issue. I use a window switcher called [AltTab](https://alt-tab-macos.netlify.app/) - and when that's running, the dirty editor is not saved on focus lost of the VSCode Window. Not sure if this is something that can be fixed in VSCode or not. I'm happy to close it or keep it open for this fix.
