### ISSUE TITLE
VSCode how do two developers compile code on their own PC?

### ISSUE THREAD

**Issue by VentureVex** [microsoft/vscode#151897]
I'm using VSCode to make a Java game with my friend. We are using the java.awt libraries. We are using live share so we can both work on the code, but when we compile the game window only shows up for me (the host) and not him. How do we go about working on this game together?

If it's not clear what I'm asking, please ask.

**Comment by sbatten** [comment]
Live share does not share windows that are not from VS Code. You will need to find an alternative for sharing the game application window. You can reach out to [Live Share](https://github.com/MicrosoftDocs/live-share) or the community to see if they have recommendations.
