### ISSUE TITLE
Usage of @var and @apply breaks css validation

### ISSUE THREAD

**Issue by sz332** [Microsoft/vscode#15182]
- VSCode Version: 1.7.2
- OS Version: Windows 7 SP 1

Steps to Reproduce:

1. Create a new html template file with basic dom module content
2. Open file 
3. Check validation errors...

<dom-module id="my-module">
    <style>
    
        .test{
            @apply(--my-setting);
            background-color: @var(--my-variable);
        }
    </style>

    <div class="test"></div>

</dom-module>

**Comment by mrmlnc** [comment]
It seems that this is fixed in the Insider version.

![image](https://cloud.githubusercontent.com/assets/7034281/20105521/eda74dac-a5e2-11e6-81ab-61c866d2b77e.png)


![image](https://cloud.githubusercontent.com/assets/7034281/20105517/e8c49a1a-a5e2-11e6-988f-944b1b474554.png)

**Comment by aeschli** [comment]
There hasn't been any fixes on that for 1.8. The request for @apply is https://github.com/Microsoft/vscode-css-languageservice/issues/8

**Comment by rictic** [comment]
`@var` isn't the right syntax, it should just be `var`. See: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables

VS Code doesn't seem to object to that syntax.

Another, related issue: https://github.com/Microsoft/vscode-css-languageservice/issues/7

**Comment by sz332** [comment]
rictic: yes, you are right, I changed the title...
