### ISSUE TITLE
Electron 18: `WebSwapCGLLayer` warning

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151818]
```
objc[76025]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x236713808) and /Users/bpasero/Development/Microsoft/vscode/.build/electron/Code - OSS.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x1058ed3c8). One of the two will be used. Which one is undefined.
```

Running out of sources.

**Comment by deepak1556** [comment]
Upstream issue https://github.com/electron/electron/issues/33685

CrBug: https://bugs.chromium.org/p/angleproject/issues/detail?id=5253, https://bugs.chromium.org/p/chromium/issues/detail?id=1217851

**Comment by rich1e** [comment]
@bpasero Recently, I have also been investigating this issue and found that someone from the official team has already fixed it. The problem has been resolved in versions 21/22/23.

Ref: https://github.com/electron/electron/pull/35961

**Comment by deepak1556** [comment]
Thanks, I forgot to close this out with E22 update.
