### ISSUE TITLE
Opening VSCode from cmd/PowerShell binds it to that terminal's lifespan

### ISSUE THREAD

**Issue by zackschuster** [Microsoft/vscode#15187]
- VSCode Version: 1.7.1
- OS Version:

Steps to Reproduce:

1. Open cmd.exe or PowerShell (user or admin mode)
2. Execute `code` (with or without parameters)
3. Once VSCode opens, close the terminal
4. VSCode will also close

Explicitly disconnecting the child process spawned from `bin/code.js` with `child.unref()` doesn't appear to resolve the issue, so it may not be tied to the Node.js initialization code.

**Comment by bpasero** [comment]
@zackschuster make sure your global code command points to the bin folder code.cmd and not code.exe.

**Comment by zackschuster** [comment]
@bpasero I'm using the out-of-the-box PATH setup, which points to bin.

**Comment by zackschuster** [comment]
Nevermind, turned out I had a duplicate PATH identifier that pointed at `code.exe`. Sorry to trouble you all!
