### ISSUE TITLE
TypeScript is broken for working on VSCode

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#151828]
Noticed this since a few days: TypeScript is broken when working on VSCode, I see stale errors, no errors, missing errors, late errors. For example the in-editor errors seem to be disconnect from the overall building errors.

![Recording 2022-06-11 at 12 29 25](https://user-images.githubusercontent.com/900690/173184085-8e541d49-c047-4b8a-b915-ac3caa000172.gif)

//cc @jrieken

**Comment by bpasero** [comment]
Log output:

```
[Info  - 10:30:41.463] Starting TS Server
[Info  - 10:30:41.463] Using tsserver from: /Users/bpasero/Development/Microsoft/vscode/node_modules/typescript/lib/tsserver.js
[Info  - 10:30:41.463] <syntax> Log file: /Users/bpasero/Library/Application Support/Code - Insiders/logs/20220610T095408/exthost3/vscode.typescript-language-features/tsserver-log-qUIkQE/tsserver.log
[Info  - 10:30:41.463] <syntax> Forking...
[Info  - 10:30:41.465] <syntax> Starting...
[Info  - 10:30:41.465] <semantic> Log file: /Users/bpasero/Library/Application Support/Code - Insiders/logs/20220610T095408/exthost3/vscode.typescript-language-features/tsserver-log-WVagqo/tsserver.log
[Info  - 10:30:41.465] <semantic> Forking...
[Info  - 10:30:41.466] <semantic> Starting...
```

**Comment by bpasero** [comment]
The reason seems to be https://github.com/microsoft/vscode/commit/ba66d68c760a9c0e0a05efc5d4169b408866e02b

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/tree/ben/151828 branch can be used to reproduce:
* run default build task in vscode and notice no errors
* open `src/vs/workbench/browser/parts/editor/textResourceEditor.ts` and see errors in editor

**Comment by bpasero** [comment]
Interestingly I think the errors appear briefly and then resolve when looking at the output:

![image](https://user-images.githubusercontent.com/900690/173184937-2bd0062f-5e2e-40ed-942b-3562f149b3ee.png)

**Comment by jrieken** [comment]
Errors in the editor and "errors on the console" have nothing to do with each other - it's completely different processes. I don't know (please clarify @bpasero) if some task that reports console errors in the editor is used or not..


> The reason seems to be https://github.com/microsoft/vscode/commit/ba66d68c760a9c0e0a05efc5d4169b408866e02b

Is that a guess or did you revert and retry? Would be very surprising because the change adds a function that don't (yet) call.

**Comment by bpasero** [comment]
@jrieken yes I did a revert and retried and saw the errors.

**Comment by bpasero** [comment]
🎩 for non-work day prompt fix 🍻

**Comment by w0o** [comment]
I'm seeing the same issue of stale errors on the latest insider version along with a terrible slowdown of TS completion (15sec+ for getting suggestions to appear) making it unusable. 
Don't know if both related but would be keen on trying out a fix when it's available.

Version: 1.69.0-insider
Commit: ab6ba241145bb81c8bc0f323453bbec45fd66109
Date: 2022-06-10T05:16:48.648Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.4.0
