### ISSUE TITLE
Microsoft sync account automatically logout

### ISSUE THREAD

**Issue by wu-pan** [microsoft/vscode#151867]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.69.0-insider
- OS Version:Windows_NT x64 10.0.22000

Steps to Reproduce:

1.To sync setting sign in with Microsoft account. And make a successfully sign in.
2.Restart vscode or open new vscode window, Microsoft account is sign out.

```
[Info  - 09:28:05.134] Reading sessions from secret storage...
[Error  - 09:28:05.180] Key was not found in SecretStorage.
[Info  - 09:28:05.182] Got 0 stored sessions
[Info  - 09:28:05.190] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 09:28:05.190] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 09:28:05.190] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 09:28:06.680] Getting sessions for all scopes...
[Info  - 09:28:06.680] Got 0 sessions for all scopes...
[Info  - 09:28:43.308] Getting sessions for all scopes...
[Info  - 09:28:43.308] Got 0 sessions for all scopes...
[Info  - 09:28:44.7] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 09:28:44.7] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 09:28:44.7] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 09:28:45.352] Logging in for the following scopes: email offline_access openid profile
[Info  - 09:28:48.100] Exchanging login code for token for scopes: email offline_access openid profile
[Info  - 09:28:49.873] Exchanging login code for token (for scopes: email offline_access openid profile) succeeded!
[Info  - 09:28:49.873] Setting token for scopes: email offline_access openid profile
[Info  - 09:28:49.874] Login successful for scopes: email offline_access openid profile
[Info  - 09:28:49.874] Token available from cache (for scopes email offline_access openid profile), expires in 5260999 milliseconds
[Info  - 09:28:49.876] Getting sessions for the following scopes: email offline_access openid profile
[Info  - 09:28:49.876] Got 1 sessions for scopes: email offline_access openid profile
[Info  - 09:28:49.876] Token available from cache (for scopes email offline_access openid profile), expires in 5260997 milliseconds
[Info  - 09:28:49.876] Getting sessions for the following scopes: email offline_access openid profile
[Info  - 09:28:49.876] Got 1 sessions for scopes: email offline_access openid profile
[Info  - 09:28:49.876] Token available from cache (for scopes email offline_access openid profile), expires in 5260997 milliseconds
[Error  - 09:28:50.557] Error: �ڴ���Դ���㣬�޷����������
```

Restart vscode or open new vscode window output
```
[Info  - 09:28:05.134] Reading sessions from secret storage...
[Error  - 09:28:05.180] Key was not found in SecretStorage.
[Info  - 09:28:05.182] Got 0 stored sessions
[Info  - 09:28:05.190] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 09:28:05.190] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 09:28:05.190] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 09:28:06.680] Getting sessions for all scopes...
[Info  - 09:28:06.680] Got 0 sessions for all scopes...
```

**Comment by TylerLeonhardt** [comment]
@wu-pan do you hit this issue always with the 1.69 insiders build? Or is it intermittent

**Comment by wu-pan** [comment]
> @wu-pan do you hit this issue always with the 1.69 insiders build? Or is it intermittent
@TylerLeonhardt 
This happened every time in the 1.68 and 1.69 insiders versions, and it was normal to set up synchronization without restarting vscode or creating a new window.

**Comment by wu-pan** [comment]
I reinstalled vscode and it didn't work. I reinstalled the system. Problem solved. No further information can be provided.

**Comment by wu-pan** [comment]
I reinstalled vscode and it didn't work. I reinstalled the system. Problem solved. No further information can be provided.

**Comment by szmcdull** [comment]
> Does this issue occur when all extensions are disabled?: Yes
> 
>     * VS Code Version:1.69.0-insider
> 
>     * OS Version:Windows_NT x64 10.0.22000
> 
> 
> Steps to Reproduce:
> 
> 1.To sync setting sign in with Microsoft account. And make a successfully sign in. 2.Restart vscode or open new vscode window, Microsoft account is sign out.
> 
> ```
> [Info  - 09:28:05.134] Reading sessions from secret storage...
> [Error  - 09:28:05.180] Key was not found in SecretStorage.
> [Info  - 09:28:05.182] Got 0 stored sessions
> [Info  - 09:28:05.190] Getting sessions for the following scopes: email offline_access openid profile
> [Trace  - 09:28:05.190] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
> [Info  - 09:28:05.190] Got 0 sessions for scopes: email offline_access openid profile
> [Info  - 09:28:06.680] Getting sessions for all scopes...
> [Info  - 09:28:06.680] Got 0 sessions for all scopes...
> [Info  - 09:28:43.308] Getting sessions for all scopes...
> [Info  - 09:28:43.308] Got 0 sessions for all scopes...
> [Info  - 09:28:44.7] Getting sessions for the following scopes: email offline_access openid profile
> [Trace  - 09:28:44.7] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
> [Info  - 09:28:44.7] Got 0 sessions for scopes: email offline_access openid profile
> [Info  - 09:28:45.352] Logging in for the following scopes: email offline_access openid profile
> [Info  - 09:28:48.100] Exchanging login code for token for scopes: email offline_access openid profile
> [Info  - 09:28:49.873] Exchanging login code for token (for scopes: email offline_access openid profile) succeeded!
> [Info  - 09:28:49.873] Setting token for scopes: email offline_access openid profile
> [Info  - 09:28:49.874] Login successful for scopes: email offline_access openid profile
> [Info  - 09:28:49.874] Token available from cache (for scopes email offline_access openid profile), expires in 5260999 milliseconds
> [Info  - 09:28:49.876] Getting sessions for the following scopes: email offline_access openid profile
> [Info  - 09:28:49.876] Got 1 sessions for scopes: email offline_access openid profile
> [Info  - 09:28:49.876] Token available from cache (for scopes email offline_access openid profile), expires in 5260997 milliseconds
> [Info  - 09:28:49.876] Getting sessions for the following scopes: email offline_access openid profile
> [Info  - 09:28:49.876] Got 1 sessions for scopes: email offline_access openid profile
> [Info  - 09:28:49.876] Token available from cache (for scopes email offline_access openid profile), expires in 5260997 milliseconds
> [Error  - 09:28:50.557] Error: �ڴ���Դ���㣬�޷����������
> ```
> 
> Restart vscode or open new vscode window output
> 
> ```
> [Info  - 09:28:05.134] Reading sessions from secret storage...
> [Error  - 09:28:05.180] Key was not found in SecretStorage.
> [Info  - 09:28:05.182] Got 0 stored sessions
> [Info  - 09:28:05.190] Getting sessions for the following scopes: email offline_access openid profile
> [Trace  - 09:28:05.190] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
> [Info  - 09:28:05.190] Got 0 sessions for scopes: email offline_access openid profile
> [Info  - 09:28:06.680] Getting sessions for all scopes...
> [Info  - 09:28:06.680] Got 0 sessions for all scopes...
> ```

I'm getting the exact logs, including the undisplayable Error message😭. I can sign in. But it will be out of sync after some time, or after vscode is restarted. Anything I can help?

**Comment by szmcdull** [comment]
logs of signing in:
```
[Info  - 07:26:09.311] Reading sessions from secret storage...
[Error  - 07:26:09.405] Key was not found in SecretStorage.
[Info  - 07:26:09.405] Got 0 stored sessions
[Info  - 07:26:09.412] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 07:26:09.412] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 07:26:09.412] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 07:28:46.373] Getting sessions for all scopes...
[Info  - 07:28:46.373] Got 0 sessions for all scopes...
[Info  - 07:31:11.999] Getting sessions for all scopes...
[Info  - 07:31:11.999] Got 0 sessions for all scopes...
[Info  - 07:31:14.101] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 07:31:14.101] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 07:31:14.101] Got 0 sessions for scopes: email offline_access openid profile
[Info  - 07:31:15.589] Logging in for the following scopes: email offline_access openid profile
[Info  - 07:31:18.346] Exchanging login code for token for scopes: email offline_access openid profile
[Info  - 07:31:19.68] Exchanging login code for token (for scopes: email offline_access openid profile) succeeded!
[Info  - 07:31:19.68] Setting token for scopes: email offline_access openid profile
[Info  - 07:31:19.69] Login successful for scopes: email offline_access openid profile
[Info  - 07:31:19.69] Token available from cache (for scopes email offline_access openid profile), expires in 3943999 milliseconds
[Info  - 07:31:19.72] Getting sessions for the following scopes: email offline_access openid profile
[Info  - 07:31:19.72] Got 1 sessions for scopes: email offline_access openid profile
[Info  - 07:31:19.72] Token available from cache (for scopes email offline_access openid profile), expires in 3943996 milliseconds
[Info  - 07:31:19.72] Getting sessions for the following scopes: email offline_access openid profile
[Info  - 07:31:19.72] Got 1 sessions for scopes: email offline_access openid profile
[Info  - 07:31:19.72] Token available from cache (for scopes email offline_access openid profile), expires in 3943996 milliseconds
[Error  - 07:31:19.753] Error: �ڴ���Դ���㣬�޷����������
```
logs after vscode restarted:
```
[Info  - 07:32:00.474] Reading sessions from secret storage...
[Error  - 07:32:00.581] Key was not found in SecretStorage.
[Info  - 07:32:00.581] Got 0 stored sessions
[Info  - 07:32:00.595] Getting sessions for the following scopes: email offline_access openid profile
[Trace  - 07:32:00.595] No session found with idtoken scopes... Using fallback scope list of: email offline_access openid profile
[Info  - 07:32:00.595] Got 0 sessions for scopes: email offline_access openid profile
```

**Comment by szmcdull** [comment]
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

Microsoft Windows [Version 10.0.19044.1826]

**Comment by szmcdull** [comment]
One more thing
![image](https://user-images.githubusercontent.com/2098590/180595682-a8dbaf39-eb17-4db9-ab0b-9309459768d2.png)
There are many tokens created in the windows credential manager. I deleted them in previous versions of vscode (like a month ago). But now they are created again.

**Comment by TylerLeonhardt** [comment]
Hi @wu-pan, this is a duplicate of https://github.com/microsoft/vscode/issues/130893 most likely
