### ISSUE TITLE
externalConsole dont support Chinese

### ISSUE THREAD

**Issue by lyj2576** [Microsoft/vscode#15189]
- VSCode Version: 1.7.1
- OS Version: windows 10 pro

When I tried to print Chinese on the externalConsole , it just showed me the garbled message:

![image](https://cloud.githubusercontent.com/assets/22914094/20109231/119777d2-a61a-11e6-83fc-db77f7f7c30e.png)

```
Console.WriteLine("Hello World!");
Console.WriteLine("世界，你好！");
```

but when I tried to print the same text on the debug console, it showed just as expected!
I cannot fix the problem by myself, and I need help!

**Comment by Tyriar** [comment]
It's a little unclear whether you're having the issue with:

- External terminal (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>c</kbd> to launch cmd.exe outside of VS Code)
- The debug console (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>d</kbd>)
- The integrated terminal (<kbd>ctrl</kbd>+<kbd>`</kbd>)

**Comment by lyj2576** [comment]
Tyriar, thank you for providing me with these shortcuts, and I am terrible sorry for my bad English expression.
I tried the following steps and met my problem:
1. Created a new project with `dotnet new` and `dotnet restore`,  and opened the directory in vs code. 
2. Added vs code configuration files(tasks.json and launch.json) to the workspace(they were generated by the c# extension)
3. Rewrote one launch configuration in the launch.json: 
    `"externalConsole": true`
4. my test code was:
```
using System;
namespace ConsoleApplication
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            Console.WriteLine("世界，你好！");
            Console.ReadKey();  
        }
    }
}
```

Compiled and ran the program，it launched a external terminal, and outputted the text  `Hello World!` and `世界，你好！`, but the chinese was garbled（e,, incorrect codes）
![image](https://cloud.githubusercontent.com/assets/22914094/20129233/5dbeefae-a689-11e6-8f06-90131e7bb757.png)

So, how can I output the chinese characters correctly to the external terminal?

**Comment by weinand** [comment]
@lyj2576 please try to run your 'Hello World' program outside of VS Code and see whether this makes a difference.

**Comment by King66** [comment]
He means that the code Console.WriteLine("世界，你好！"); works fun when using the debug console , but using "dotnet run" with integrated terminal and external terminal outputs not correctly....

**Comment by weinand** [comment]
The external terminal is not under our control.
