### ISSUE TITLE
Command center is not visible on compact mode in browser (vscode.dev)

### ISSUE THREAD

**Issue by idoprz** [microsoft/vscode#151892]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68
- OS Version: Browser (windows)

Steps to Reproduce:

1. Open vscode.dev
2. Turn on command center in settings.

Command center is not visible. If changing menu from compact to visible it is shown. In desktop it is shown in compact mode.

**Comment by jrieken** [comment]
We have revisited our decision and reverted this change. There is a lengthly discussion in https://github.com/microsoft/vscode/issues/161948.

In our "defence", the classic menu rendering has gotten more responsive and will become the compact burger when space is rare. I think we can tweak this further for an even better experience

https://user-images.githubusercontent.com/1794099/193260564-a204bf51-8138-407f-b58f-187dee331fda.mov

**Comment by idoprz** [comment]
@jrieken I don't really get this decision. This is not the default behavior, so if I decide to set it up like this, why can't I just have the command center without the other menus? It's like you do not support a certain setup which if a user like, why not provide him that?
I don't really use most of the menu items, if I need something I just use the command center to find the command. why does it have to be all or nothing?

**Comment by sbatten** [comment]
The title bar showing if CC is enabled has been brought back with other tweaks to improve the experience
