### ISSUE TITLE
Revert to using full-height menubar buttons

### ISSUE THREAD

**Issue by doodlezucc** [microsoft/vscode#151842]
From a UX point of view, the redesigned title bar buttons introduced in https://github.com/microsoft/vscode/pull/149835 make maneuvering of the IDE noticeably worse and less intuitive.

The hitbox of all buttons at the edge of your screen can be considered "infinite" in at least one direction. Every OS will clamp your mouse position to fit inside of the screen. If you move your cursor to the top right corner of your monitor, it is guaranteed to land on the same spot, no matter how long you decide to feed positive horizontal and vertical inputs. If you place a button in the corner of a window, you are therefore (infinitely) extending its physical size in two directions.

In theory, you want a hitbox to be bigger in size if its triggering function is important to the user. On Windows, you'll find that most GUI applications implement a "close window" button in the top right corner. Assuming you're using a single monitor and are working in a maximized window, you can confidently hit this button without even looking at the screen. You know that you only need to draw one straight line from your current position to the event target. That's what makes it so satisfying and intuitive.

Here's what the space of each button felt like before this change:

![titlebar_vscode_clamped](https://user-images.githubusercontent.com/15276029/173187157-8bd165df-490d-4f22-be68-719bff2f5913.png)
_Get to any title bar button by simply moving up (as far as possible) and then caring only about the horizontal coordinate of your cursor._

#

With https://github.com/microsoft/vscode/pull/149835, a padding to the top of each button has been introduced, basically discarding the entire UI principle of infinitely large buttons. There's now an upper bound to the hitboxes where there was none before. This adds a whole new step to the process of selecting a button from the top row, as you must now also pay close attention to the vertical position of your cursor.

Here's what the space of each button feels like after this change:

![titlebar_vscode_unclamped](https://user-images.githubusercontent.com/15276029/173187161-4b853598-5582-4da0-90e8-4a2f041c4a25.png)
_Get to any title bar button by moving to the top of the screen, moving horizontally, then adjusting for vertical padding._

https://user-images.githubusercontent.com/15276029/173197348-6b7c7499-6380-4646-ba4b-63727c734a39.mov

#

Regarding the styling itself, I'm not in any qualified position to complain, as beauty in design is very much a subjective preference. I'm merely expressing my concern for a change in user-machine interaction that I can confidently call a step backwards.

My proposal for a better user experience is to do one of the following:
- Keep the new styling and extend the menubar button hitbox to reach to the top of the screen.
- Revert to the previous full-height design (by undoing https://github.com/microsoft/vscode/commit/ca280a1685a34207a8bcf4826f8294d824b3caf7) and instead restyle the layout buttons accordingly.

The padding in question is defined here:
https://github.com/microsoft/vscode/blob/ca280a1685a34207a8bcf4826f8294d824b3caf7/src/vs/base/browser/ui/menu/menubar.css#L8-L16

- VS Code Version: 1.68.0 (2022-06-08)
- OS Version: Windows_NT x64 10.0.19043

**Comment by gjsjohnmurray** [comment]
Looks like @daviddossett is addressing this in #151250

**Comment by daviddossett** [comment]
> Looks like @daviddossett is addressing this in #151250

This. Just need to fix a deceptively tricky issue with this PR and we'll get this in.
