### ISSUE TITLE
Issue: Zoom Factor of Title bar

### ISSUE THREAD

**Issue by Blank-09** [microsoft/vscode#151877]
Issue Type: <b>Bug</b>

Greetings,
    I'm using VSCode in my laptop, so the screen is small. Due to the latest update on zooming, the title bar remains static. The problem is in the Menu List. I couldn't access File > Open Recent > More. As the options are out the window.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.83GB (3.04GB free)|
|Process Argv|--crash-reporter-id 16665a92-b1b2-427c-9273-24d9aab7f83a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.2
vscode-npm-script|eg2|0.3.25
prettier-vscode|esb|9.5.0
code-runner|for|0.11.8
material-icon-theme|PKi|4.18.1
LiveServer|rit|5.7.5
ayu|tea|1.0.5
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by sbatten** [comment]
Can you share a screen shot of your window?

**Comment by sbatten** [comment]
I'm guessing this is the same issue as https://github.com/microsoft/vscode/issues/151803
