### ISSUE TITLE
Visual Studio Code Windowing fails in multi monitor

### ISSUE THREAD

**Issue by JuanMejiaVelez** [microsoft/vscode#151893]
Issue Type: <b>Bug</b>

The IDE is unable to properly remember the window bounds where it should be when closed, the window always fallback to a very small size causing that all the content layout re-distributes, additionall moving the window across displays with different DPI's causes the layout to shrink.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (20.50GB free)|
|Process Argv|--folder-uri file:///c%3A/src/fbh --crash-reporter-id e152bca5-1b26-4365-bb42-b1d72323bdbf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
armview|ben|0.4.6
markdown-preview-github-styles|bie|1.0.1
doxdocgen|csc|1.4.0
docs-markdown|doc|0.2.113
docs-yaml|doc|0.2.8
better-cpp-syntax|jef|1.15.16
azure-pipelines|ms-|1.205.0
vscode-azureappservice|ms-|0.24.2
vscode-azurefunctions|ms-|1.7.3
vscode-azureresourcegroups|ms-|0.5.3
vscode-azurestorage|ms-|0.14.1
vscode-azurevirtualmachines|ms-|0.6.1
vscode-bicep|ms-|0.6.18
vscode-cosmosdb|ms-|0.19.1
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.80.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
azure-account|ms-|0.10.1
azurecli|ms-|0.5.0
cmake-tools|ms-|1.10.5
cpptools|ms-|1.10.5
cpptools-extension-pack|ms-|1.2.0
powershell|ms-|2022.5.1
azurerm-vscode-tools|msa|0.15.7
vscode-react-native|msj|1.9.2
material-icon-theme|PKi|4.18.1
vscode-yaml|red|1.8.0
code-spell-checker|str|2.2.3
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.21
vscode-icons|vsc|11.12.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by af4jm** [comment]
VSCode has always (since before v1) when any external monitor is plugged or unplugged, moved its window back to the primary monitor... I think it's an Electron issue... Electron, Windows, & performance/reliability are three things that just can't co-exist... you can have any 2 of the 3, but the only way to do it is to get rid of the 3rd one
