### ISSUE TITLE
Disabling and enabling extensions for the workspace when changing the "state.vscdb" file are not applied

### ISSUE THREAD

**Issue by evald24** [microsoft/vscode#151985]
I am an extension developer [Extension profiles](https://github.com/evald24/vscode-extensions-profiles) which allows you to enable and disable extensions for the workspace by pre-created profiles. Changes are made directly to the file `User/workspaceStorage/{uuid}/state_vscdb` in accordance with the required format `extensionsIdentifiers/disabled` and `extensionsIdentifiers/enabled`. After that, the command `workbench.action.reloadWindow` is executed and it worked, but with the latest release VS Code stopped working. Now, in order for this to work, after applying the profile, you need to completely close VS Code and restart it.

Do you have any suggestions on how it would be possible to restore the work of the extension?

**Comment by bpasero** [comment]
This can be correlated to a change I did a few weeks ago that workspace DBs no longer reload per window but only per application restart. 

In general though, we do not support writing to the DB directly, and it is dangerous anyway because the DBs do not allow concurrent writes from different processes.

**Comment by evald24** [comment]
Is there any way to resume the work of the extension? Is there an API for enabling and disabling extensions?

**Comment by sandy081** [comment]
I second @bpasero that writing into our internals is not recommended. 

> If there is no API for this, have you thought about adding native profile support in VS Code? I can rethink the necessary functionality, user experience and propose a new concept =)

Yes, we are exploring/working on this feature - https://github.com/microsoft/vscode/issues/116740
