### ISSUE TITLE
Changing Tab Endentation

### ISSUE THREAD

**Issue by rbiggs** [Microsoft/vscode#15195]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|riot-tag|crisward|0.1.7|
|vscode-svgviewer|cssho|1.2.0|
|vscode-instant-markdown|dbankier|0.1.0|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|view-in-browser|qinjia|0.0.3|

---

Steps to Reproduce:

1. Open A file with JavaScript
2. Edit some code.
3. Hit command Save

I have my user and workspace preferences set to use tabs as two spaces. When I save a JavaScript file after editing, Code changes the tabs to four spaces for the entire document. When I correct the tab spacing and save, Code again converts the tabs back to four spaces. This takes several tries before Code finally accepts the document as is, and then it start again after the next edit and save. Very frustrating. It looks like Code 1.7.1 is not respecting tab size in user and workspace preferences.

**Comment by waderyan** [comment]
Confirmed. @dbaeumer are you the right contact for this? 

Here is some code to copy and paste:

```
/**
 * This is foo
 * Foo is great! Use it like this:
 * 
 * ```ts
 * const foo = new Foo(); 
 * ```
 */
function Foo() {
	console.log('hello');
}


		var f = new Foo();
```

**Comment by rbiggs** [comment]
You can close this bug. I'm pretty sure the extension vscode-JS-CSS-HTML-formatter was causing the problem. Removed it from VS code and now everything is back to normal.
