### ISSUE TITLE
Add Setting for Output Window Word Wrap 

### ISSUE THREAD

**Issue by jjELT** [microsoft/vscode#151913]
Since VSC version 1.68.0, the text in the OUTPUT window (CTRL + Shift + U) is automatically wrapped and there does not seem to be an option in the preferences to disable this.

Possibly a regression of #21468.

I suggest to add a setting to allow toggling word wrapping in the OUTPUT window.

**Comment by sandy081** [comment]
I see it wraps automatically in older versions too. Can you please show us what difference you are seeing?

**Comment by jjELT** [comment]
# Screenshots
Here are two screenshots showing the different behavior.

Not wrapped line in the red box:
![NOT_Wrapped_OUTPUT_Window_Text](https://user-images.githubusercontent.com/28619105/174791828-9958c42d-9fa6-4f3c-87c7-174f5a93b407.png)

Single, wrapped line:
![Wrapped_OUTPUT_Window_Text](https://user-images.githubusercontent.com/28619105/174791839-4f284f15-b550-4059-a5b5-0cbef4ac95fa.png)

# Behavior in Previous Version

> I see it wraps automatically in older versions too.

That is weird. I also installed a previous version (1.64.0), but it did not revert the behavior to unwrapped text in the OUTPUT window.

I could have sworn the behavior was different in earlier versions?! 

Maybe I already had the manual setting:
```
"[Log]": {
"editor.wordWrap": "off"
}
```
which does exactly what I want, but somehow got deleted because of some glitch in the update to version 1.68.0?

Anyways, having added that option, the text is unwrapped, as I want it.
