### ISSUE TITLE
Multiroot smoke tests failed

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#151927]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174034&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a671546b-2469-5fb1-b2c9-08e628dcad6d

Both multi root folder tests failed.

**Comment by bpasero** [comment]
The log shows: `Target page, context or browser has been closed`, this seems to be something Playwright related, not under our control. We also do not get any traces as a result. 

🤷
