### ISSUE TITLE
Feature request: add config option for the new menu styles

### ISSUE THREAD

**Issue by Legend-Master** [microsoft/vscode#151968]
About the new menu styles from #149187, I'm really not a fan of it, 

1. Menu bb: before the change you can just swing your mouse to the top and click the menu button but you have aim it now

2. Rounded corner: it does not fit in windows 10 at all

    ![image](https://user-images.githubusercontent.com/68118705/173405438-50f57617-afce-4afd-9103-5cda26ea7b2e.png)
    ![image](https://user-images.githubusercontent.com/68118705/173405493-959f8731-fe42-46bd-878e-33f4a3ee8822.png)

3. New action item separator: it don't have left/right margin now, it used to be so elegant ( well, at least I prefer the old one )

    ![image](https://user-images.githubusercontent.com/68118705/173406946-abc21f47-1e28-4448-bbee-ef97d6910039.png)
    ![image](https://user-images.githubusercontent.com/68118705/173407453-80bf4d56-b5df-4dac-b991-9534deaa9d7d.png)

Can we make a setting for this?

**Comment by sbatten** [comment]
I do not foresee us supporting 2 css stylings of menus via settings. We are however working to address the usability issue you call out in 1.

**Comment by sbatten** [comment]
see https://github.com/microsoft/vscode/pull/151250
