### ISSUE TITLE
make task icon/color configuration more discoverable/ easier to set

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#151992]
on focus of a row, it would be nice if we had this pencil icon and, when pressed, it could let you set the color and icon for the task
<img width="624" alt="Screen Shot 2022-06-13 at 2 47 34 PM" src="https://user-images.githubusercontent.com/29464607/173450899-22b7cf69-60fe-4164-91ab-5ad5741731c4.png">

**Comment by alexr00** [comment]
This feels a bit like duplication to me since we already have the "configure" action that takes you to the task in tasks.json and you can set the color and icon there.

**Comment by Tyriar** [comment]
👍 icon and color shouldn't be elevated over the rest of the task configuration imo

**Comment by alexr00** [comment]
If you want to have nicer suggestions for tasks colors and icons in tasks.json you could add something in here: https://github.com/microsoft/vscode/blob/375681e51e14b2a1c6c2ad83d80663d2a65560d6/extensions/configuration-editing/src/configurationEditingMain.ts#L23-L24

**Comment by Tyriar** [comment]
Created https://github.com/microsoft/vscode/issues/152054

**Comment by meganrogge** [comment]
my argument for this is that people know of other task configuration already. how will they discover color and icon without this?

**Comment by meganrogge** [comment]
my other issue with setting the icon in the .json is there's no preview of it - so you're just guessing unless super familiar with codicons

**Comment by meganrogge** [comment]
after discussing, seems like adding the intellisense is sufficient
