### ISSUE TITLE
1.68.0 Open File/Folder dialogue fails to focus

### ISSUE THREAD

**Issue by Sierra1011** [microsoft/vscode#151923]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.0-1654690163.el7.x86_64
- OS Version: Linux/OpenSUSE Leap 15.3

Steps to Reproduce:

1. Open new instance of Code
2. Trigger Open File or Open Folder either by keyboard shortcut Ctrl+K+O or via window Menu
3. First instance opens the dialogue window in front of the Code window, as expected
4. Close the dialogue
5. Successive attempts will now open the dialogue behind other windows, with a pop-up notification that the dialogue is ready

Downgrading to 1.67.2-1652812909.el7.x86_64 with no other changes resolves issue.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
