### ISSUE TITLE
Follow up on profiles

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#151939]
From https://github.com/microsoft/vscode/pull/151702

- ~Make `protocolMainService` multi profile aware. -> this is probably only needed if extension global storage is profile aware~
- [x] Profile folder shall be the hash of profile name
- [x] Revisit initialising UserDataProfilesMainService
- [x] Profile state object shall be folder aware like workspace trust
- [x] Workbench shall support reading/writing application scoped settings from default profile
- [x] Migrate global storage while entering into a profile.
- [ ] Unit tests for profile management
- [ ] I was missing events and adoption to support transition of profile without window reload (i.e. what does it mean when a profile changes for where the profile paths are used)
- [ ] Shall extension storage shall be profile specific?

**Comment by bpasero** [comment]
Introduce an environment service path for the `storage.json` file so that we do not have to derive it from the default profile.

**Comment by bpasero** [comment]
- [ ] I think makeing extension global storage home profile aware (including remote)

**Comment by bpasero** [comment]
* [ ] I think `IUserDataProfilesService` should split up into a `main` service and renderer / workbench service

The main service does not have a "current profile", while the other one has it. The main service should have methods to know which path is associated to which profile though.
