### ISSUE TITLE
Support search/find within the terminal

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#15198]
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

Panels (debug, terminal, etc.) have ability to search for text. I expected cmd-F to work.

**Comment by aeschli** [comment]
Debug and terminal are different features. Can you file separate issues? I'll take this for the terminal

**Comment by atombender** [comment]
Done (#15210).

**Comment by Tyriar** [comment]
There would need to be hooks implemented [upstream](https://github.com/sourcelair/xterm.js) before this could be implemented within vscode.

**Comment by Tyriar** [comment]
@rebornix any thoughts on if could make monaco and xterm.js share code for the find widget? It would be cool if the find in the terminal panel was consistent with other panels and the editor (see https://github.com/Microsoft/vscode/issues/28333).

**Comment by Tyriar** [comment]
@rebornix and I worked on adding some basic find functionality. There are a bunch of limitations with it now but it works and it's seems really slick.

![image](https://user-images.githubusercontent.com/2193314/27163294-3b81de3a-513b-11e7-9b7b-5765d2796605.png)

**Showing the find widget**
Windows & Linux: ctrl+f (terminalFocus)
macOS: cmd+f (terminalFocus)

Check out https://github.com/Microsoft/vscode/issues/28768 for the limitations and future plans.
