### ISSUE TITLE
How to add buttons in sidebar

### ISSUE THREAD

**Issue by felipetesc** [Microsoft/vscode#15190]
It may be a feature request or a kinda of help, I wanted to know how can I add buttons at the sidebar. The closer feature request to this can be found in here: https://github.com/Microsoft/vscode/issues/15017 . However, I'm interested about a oficial way to create new buttons and call our own custom methods, rather than  the creation of default sidebar functionality   to allow processes control. In the matter of fact by constructing this official callable buttons from the sidebar, we will be capable of creating the functionality which egamma asked for.

I looked for this feature on the Git's Issues, and at the VS Code repository, and I found nothing. However, if you did found something about it, please post in here a link for us.  

Thank you.

**Comment by octref** [comment]
You can wait for #14048 to land. It'll allow you to create a tree-like explorer, and you can specify the label/children/onclick command for each node on it.

**Comment by octref** [comment]
I added a few pictures to https://github.com/octref/explorer-api-example. You can also read the [code](https://github.com/octref/explorer-api-example/blob/master/dep/src/extension.ts) which isn't too complicated.

**Comment by felipetesc** [comment]
Thank You for your answer, and for doing it so fast.
