### ISSUE TITLE
Git integration for committing not loading environment variables

### ISSUE THREAD

**Issue by scousino** [microsoft/vscode#151976]
Issue Type: <b>Bug</b>

1. Setup a repo with a .npmrc that references some environment variables (make sure the environment variable value exists)
1. Using the VS Code Source Control UI, attempt to commit.
1. You should get a error saying it failed to replace env in config

Screenshot of error received: 
![image](https://user-images.githubusercontent.com/8717527/173429463-312cd915-c53f-42bf-a9e0-a0101381b4de.png)

Additional context: My project uses direnv to load variables into the environment, and the code lives withing a WSL 2 Ubuntu distribution, accessed via the Remote Development extension

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (18.53GB free)|
|Process Argv|--crash-reporter-id ca5f95d3-3d20-44e4-8d80-08bb975b55ad|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|Memory (System)|15.49GB (11.39GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
terraform|has|2.23.0
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-eslint|dba|2.2.2
terraform|has|2.23.0
makefile-tools|ms-|0.5.0
java|red|1.7.0
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.41.0
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.23.0
vscode-java-test|vsc|0.35.0
vscode-maven|vsc|0.35.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by lszomoru** [comment]
@scousino, apologies for not getting back to you on this until now. I was wondering if you are still experiencing this problem with the latest version of VS Code? If so, would it be possible for you to reproduce the problem in a minimal repository so that I can reproduce and debug the issue there. Also I was wondering whether the environment variable resolution has ever worked? Thanks!

**Comment by cooperaustinj** [comment]
Not OP, but I did post a +1 above.

I no longer have this issue. As far as I know the only thing that changed is VS Code updating.
