### ISSUE TITLE
how to filter test method call hierarchy Visual studio

### ISSUE THREAD

**Issue by fuyou001** [microsoft/vscode#151906]
in any method ,right click and click call hierarchy, but some test method also display.
![image](https://user-images.githubusercontent.com/685537/173271913-fc88d870-4eb9-4a66-abe2-86a071810184.png)
how to hide these test method

**Comment by jrieken** [comment]
VSCOde itself doesn't know what these results mean and any filtering should be done by the extension providing the data. In this case the Java extensions

/extJava
