### ISSUE TITLE
Zooming causes strange behavior for Extension READMEs

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#15197]
- VSCode Version: 1.8 - Insiders
- OS Version: macOS

Steps to Reproduce:

1. Click Extension activity bar button
2. Click an extension
3. Zoom in

I expect to be able to see the entire README. 

Instead I see only a portion of the README with scroll bar positions far in towards the center. 

![image](https://cloud.githubusercontent.com/assets/2449568/20112667/1ce5be5a-a5a2-11e6-9da9-a6f723ad8bec.png)

> Note: I have searched for this issue but have not been able to find it in our repo.

**Comment by joaomoreno** [comment]
17 duplicates and counting 😮 

#5745

**Comment by waderyan** [comment]
Ha sorry about that.
