### ISSUE TITLE
The toggle terminal key combination doesn’t work when input language isn’t English

### ISSUE THREAD

**Issue by yakovmanshin** [microsoft/vscode#151900]
The toggle terminal key combination (<kbd>⌃</kbd> + <kbd>\`</kbd>) doesn’t work when keyboard input is set to a language other than English. For example, the tilde / backtick key produces a `<` in the German layout, and pressing this key in combination with <kbd>⌃</kbd> does nothing.

Other key combinations I tested work regardless of the characters their keys produce: <kbd>⇧</kbd> + <kbd>⌘</kbd> + <kbd>P</kbd> with the Russian layout selected still opens the command palette, even though the `P` key is mapped to the Cyrillic letter `З`.

Does this issue occur when all extensions are disabled?: Yes

* VS Code Version: 1.68.0
* OS Version: macOS 12.4

Steps to Reproduce:

1. Switch input to a language other than English;
2. Press <kbd>⌃</kbd> + <kbd>`</kbd>.

**Comment by yakovmanshin** [comment]
What’s even stranger, pressing the combination with the British - PC layout selected opens the terminal but doesn’t close it. The backtick key is mapped to `\`.

**Comment by Tyriar** [comment]
@alexdima any idea if this is a problem we can fix and if it would be an issue on my end or the keybindings system?

**Comment by alexdima** [comment]
By default, the toggle terminal keybinding is bound to `ctrl` + `` ` ``. That means `ctrl` plus the key or key combination that produces `` ` ``. On the US keyboard layout, `` ` `` is produced by the key to the left of `1`. On other keyboard layouts, `` ` `` is produced by some other key combination. @yakovmanshin What is the keyboard layout you are using?
