### ISSUE TITLE
Explore contextual actions in the terminal

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#151937]
Part of this will be building the foundation of listening to commands/args that would also get used in https://github.com/microsoft/vscode/issues/145234

**Comment by Tyriar** [comment]
Exploration is done, pushing to July

**Comment by meganrogge** [comment]
Exploration was here 

https://github.com/microsoft/vscode/commit/aea0be6ba7160e93d460a208ecdec7369855f9c5
