### ISSUE TITLE
Go to Definition within Interactive Window opens new tab

### ISSUE THREAD

**Issue by debonte** [microsoft/vscode#151986]
Issue Type: <b>Bug</b>

1. Create a new Interactive Window (Jupyter: Create Interactive Window)
2. Create a cell with the following content:
```python
def foo():
    return 42
```
3. Create a second cell:
```python
foo()
```
4. Right click on `foo` in the second cell and select "Go to Definition"

**Expected:** Definition of `foo` in the first cell is highlighted and the caret moves there. This is how Go to Definition acts when going to a definition within a Jupyter notebook.

![InteractiveWindowGoToDefinitionExpected](https://user-images.githubusercontent.com/12820898/173438261-4d5164b6-e5e9-4451-b67c-2519c3d8cbf8.gif)

**Actual:** A new `Interactive-1.interactive` document tab is opened containing the contents of the first cell.

![InteractiveWindowGoToDefinition](https://user-images.githubusercontent.com/12820898/173437850-e78af10d-c4e9-4784-8395-55175ac285f1.gif)

I believe there are a couple issues here:
1. When looking for the target document amongst the open editors, `InteractiveEditorInput.matches` returns false because `otherInput` is a `TextResourceEditorInput` instead of an `InteractiveEditorInput`.
2. If `InteractiveEditorInput.matches` is changed to return true, we no longer open the cell content in a separate document tab, however `CodeEditorService.doOpenCodeEditor` returns null which seems to prevent the expected navigation to the defintion of `foo` from happening. `doOpenCodeEditor` is returning null because `isCompositeEditor` returns false for `InteractiveEditor.getControl()`.

VS Code version: Code - Insiders 1.68.0-insider (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:37:22.322Z)
OS version: Windows_NT x64 10.0.22538
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (10.12GB free)|
|Process Argv|--crash-reporter-id c031ffde-fde4-40dc-8a32-5922dc21e570|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
csharp|ms-|1.25.0
python|ms-|2022.9.11611009
vscode-pylance|ms-|9999.0.0-dev
jupyter|ms-|2022.6.1001631011
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
vscode-typescript-tslint-plugin|ms-|1.3.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by amunger** [comment]
looks like stable does not have the `go to definition` enabled, so this hasn't worked previously either. We should just try to disable it for now
