### ISSUE TITLE
ES6. double letter with detect methods or var.

### ISSUE THREAD

**Issue by ElfenLiedGH** [Microsoft/vscode#1519]
all version vs code have bug with ES6 + Russian language

![1](https://cloud.githubusercontent.com/assets/9973357/11925242/b145c936-a7ca-11e5-84e3-91423ebf05e7.png)

then press tab or click

![2](https://cloud.githubusercontent.com/assets/9973357/11925269/e634d786-a7ca-11e5-8a4b-590c73b1cbac.png)

and we have ккомпонент in place компонент - double кк, first letter.

**Comment by jrieken** [comment]
is this our word definition?

**Comment by ElfenLiedGH** [comment]
word, class, property
![1](https://cloud.githubusercontent.com/assets/9973357/11927175/acbffe16-a7db-11e5-82cf-4cb6debd08e0.png)

tab
![2](https://cloud.githubusercontent.com/assets/9973357/11927129/5cf7abcc-a7db-11e5-93e4-f75ab50ad105.png)


class БазоваяВыборка {
    constructor(имяКлассаДиалогаЛиста) {
           }
}

**Comment by jrieken** [comment]
yeah, internally we have regular expression that defines a word. I guess we only match on a subset of the unicode characters. Thanks for pasting, with that I can play.

**Comment by jrieken** [comment]
This is an issue with the JS word def. Will take for Jan16
