### ISSUE TITLE
[sql] splunk spl syntax highlighting

### ISSUE THREAD

**Issue by df-dev** [Microsoft/vscode#15193]
- VSCode Version: 1.7.1 (1.7.1)
- OS Version: macOS 10.12.1

Feature enhancement: 
splunk spl syntax highlighting rather than just the splunk config syntax; I know I should be able to do build this on my own... but it would be really nice.

**Comment by mjbvz** [comment]
Closing as extension candidate. Please see [this guide](https://code.visualstudio.com/docs/extensions/overview) for information about authoring a language extension
