### ISSUE TITLE
Easily copy result of last command without having the command still in view

### ISSUE THREAD

**Issue by somewhatabstract** [microsoft/vscode#152097]
The awesome shell integration makes it really easy to rerun commands and copy the output from those commands. However, it seems one can only copy the output if the line the command was executed from is still within the scroll limit of the terminal. For some very long runs this is inconvenient. It would be really nice to be able to:

1. Copy output of last command from a terminal
2. Copy output of any command in the history of that terminal, if it is available to be copied

Both without having to scroll to the point the command was executed.

**Comment by Tyriar** [comment]
Once there is too much data we no longer have access to it. Sounds like you probably want to increase the size of your scrollback. This is what I use:

```
"terminal.integrated.scrollback": 50000
```

All the memory for the buffer gets reserved ahead of time for performance reasons so this will increase RAM usage by a fixed amount per terminal you have open.

I like the idea of having a command for copying the output of the last command that you could hook up to a keybinding 👍

**Comment by Tyriar** [comment]
@meganrogge I don't think so but we do lose access to their output

**Comment by lramos15** [comment]
@Tyriar I wonder if the command name should change `Terminal: Copy Last Command` makes you think the command would be copied but instead this is to copy the output
