### ISSUE TITLE
Copy (cmd+C) in panel removes selection after copy

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#15200]
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

Steps to Reproduce:

1. Select text in a panel (e.g. terminal)
2. cmd+C.
3. Text is copied, but selection disappears.

This is surprising and inconsistent with every UI widget ever made.

**Comment by mjbvz** [comment]
I believe this was fixed at some point. I'm no longer able to reproduce this

**Comment by atombender** [comment]
@mjbvz I'm still getting it in 1.13.1.

**Comment by atombender** [comment]
This is me selecting a word and hitting Cmd-C repeatedly:

![vsc](https://user-images.githubusercontent.com/50314/28032780-13992088-65ac-11e7-82b1-d09a7537bc49.gif)

**Comment by mjbvz** [comment]
@atombender Please try the current insiders build: https://code.visualstudio.com/insiders

**Comment by Tyriar** [comment]
Yes this is definitely fixed in Insiders :+1: 

Duplicate of https://github.com/Microsoft/vscode/issues/9761
