### ISSUE TITLE
SQL: single quotes Can't Display Right Color Mark

### ISSUE THREAD

**Issue by erikzhouxin** [Microsoft/vscode#1520]
--single quotes can not coupled  on sql language encoding With GB2312 or UTF-8,When i use "sys.sp_addextendedproperty" add a property.
--Such AS :
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'学校类型(小学、初中)' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'SchoolYearFiles', @level2type=N'COLUMN',@level2name=N'SchoolType'

**Comment by erikzhouxin** [comment]
is Wrong color marked
![image](https://cloud.githubusercontent.com/assets/5697068/11925731/732c7878-a7f9-11e5-8bbb-ed9ad43d5441.png)

**Comment by bpasero** [comment]
Seems to be the SQL language colorer.

**Comment by aeschli** [comment]
This issue was moved to textmate/sql.tmbundle#13
