### ISSUE TITLE
Moving settings editor to a new editor group removes the filter.

### ISSUE THREAD

**Issue by a5hk** [microsoft/vscode#152095]
Issue Type: <b>Bug</b>

After moving the settings editor using drag and drop, the filter will be removed. Bringing back the window to its original group will restore the filter. It happens with all extensions disabled and in the latest version of VS Code Insiders.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-scilla|a5h|0.2.1
tsl-problem-matcher|amo|0.6.2
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vimL|fal|0.0.3
mayukaithemevsc|Gul|3.2.2
Kotlin|mat|1.7.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-icons|vsc|11.12.0
vscode-ruby|win|0.28.0
material-theme|zhu|3.14.3
tabulate|a5h|0.5.0
vscode-tailwindcss|bra|0.8.6
better-toml|bun|0.3.2
crystal-lang|cry|0.8.4
markdown-table-prettify|dar|3.6.0
dart-code|Dar|3.42.1
vscode-eslint|dba|2.2.2
prettier-vscode|esb|9.5.0
shell-format|fox|7.2.2
go|gol|0.33.1
todo-tree|Gru|0.0.215
beautify|Hoo|1.5.0
elixir-ls|Jak|0.9.0
language-haskell|jus|3.6.0
language-gettext|mro|0.2.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
hexeditor|ms-|1.9.6
vetur|oct|0.35.0
synthwave-vscode|Rob|0.1.11
rust-analyzer|rus|0.3.1091
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.2.4
sort-lines|Tyr|1.9.1

(20 theme extensions excluded)

</details>

See the gif below:

![s](https://user-images.githubusercontent.com/5412540/173636798-cec6858d-f2ca-41cf-a645-5327e9ee7f74.gif)

**Comment by rzhao271** [comment]
Duplicate https://github.com/microsoft/vscode/issues/133444
