### ISSUE TITLE
Dynamically adding properties to an object doesn't show up in suggestions.

### ISSUE THREAD

**Issue by JoelEinbinder** [Microsoft/vscode#15204]
IntelliSense struggles on objects that get their properties after they are declared.

![vscode](https://cloud.githubusercontent.com/assets/4624233/20114045/c8288284-a5a7-11e6-8ab6-d6b1402c3ed7.png)
In this example I'd like to see charAt, indexOf, etc.

This problem was mentioned in #1685

**Comment by waderyan** [comment]
This is not supported today. 

@bowdenk7 can you confirm this is what we have talked about as "expando" pattern?

**Comment by bowdenk7** [comment]
@waderyan you're correct. How should we start tracking these as a whole? 

@JoelEinbinder can you give us a little more context on where you use this pattern? I know it is common, but it will help us make changes faster if we know what you are trying to do.

**Comment by JoelEinbinder** [comment]
We use this for organization. Every class gets added to a namespace.
```
UI.View = class {

}
UI.ListView = class {

}
```

It would be functionally equivalent if we removed the dot, like ` UIView = class {}`. But it would be nice if VSCode recognized `UI.ListView`.

**Comment by waderyan** [comment]
@bowdenk7 I'll create a label and start tracking the issues with a label (intellisense-expando). Can you do something similar on TS side?

**Comment by bowdenk7** [comment]
👍

**Comment by bowdenk7** [comment]
Thanks Joel, this is quite helpful!

**Comment by mjbvz** [comment]
Tracked upstream on the TS side by https://github.com/Microsoft/TypeScript/issues/10868
