### ISSUE TITLE
JS syntax variable highlighting only affecting some variables

### ISSUE THREAD

**Issue by NickHeiner** [Microsoft/vscode#15202]
- VSCode Version: e52fb0bc87e6f5c8f144e172639891d8d8c9aa55
- OS Version: OS X El Cap 10.11.6

When chaining variable assignments together, only the first variable name is colored:

![syntax highlighting screenshot](https://cloud.githubusercontent.com/assets/829827/20113804/e834f9fa-a5bf-11e6-878d-5fd5b082ae7e.png)

This is using the Dark+ theme, but I didn't see any theme in the default set that colors all three of the variable names.

Apologies if there's a different repo this belongs on.

Thanks!

**Comment by aeschli** [comment]
This got fixed in 1.7
