### ISSUE TITLE
Syntax highlighting messes up

### ISSUE THREAD

**Issue by thany** [microsoft/vscode#152032]
Issue Type: <b>Bug</b>

Sometimes after some kind of edit, the syntax highlight totally messes itself up, and becomes _really_ hard to read to people who rely on it to better understand code:

![image](https://user-images.githubusercontent.com/152227/173537701-7cc73424-d375-4801-af6f-ffc180184593.png)

Answers to questions I expect this to arise:

* This is a plain javascript file. Nothing special.
* This happens seemingly randomly, just while editing.
* Closing & reopening the file _keeps_ this messed up highlighting.
* Removing the change that caused this to happen doesn't fix it.
* I have no clue what exactly triggers this. Yes, editing, but what/how exactly?..
* Other files are fine, until they too become messed up.
* Reloading/restarting VScode "fixes" it, until it messes up again (which it will).

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (12.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
codesnap|adp|1.3.4
ng-template|Ang|14.0.1
font-preview|ctc|1.3.2
vscode-eslint|dba|2.2.2
xml|Dot|2.5.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.86
vscode-firefox-debug|fir|2.9.6
remotehub|Git|0.34.0
todo-tree|Gru|0.0.215
vscode-totalcommander|ipa|1.0.4
rainbow-csv|mec|2.4.0
document|min|2.1.22
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
remote-wsl|ms-|0.66.3
powershell|ms-|2022.5.1
remote-repositories|ms-|0.12.0
gremlins|nho|0.26.0
vetur|oct|0.35.0
vscode-versionlens|pfl|1.0.10
prisma|Pri|3.15.0
sqlite-viewer|qwt|0.1.5
geo-data-viewer|Ran|2.5.0
vscode-sort-json|ric|1.20.0
mdx|sil|0.1.0
vscode-svg-previewer|vit|0.7.0
volar|Vue|0.37.8
vscode-typescript-vue-plugin|Vue|0.37.8
vscode-import-cost|wix|3.3.0

</details>

Please refrain from calling "cannot reproduce" and be done with it. The *whole point* is that this issue seems random/intermittent and hard to reproduce on demand. And as such, it's not feasible to ascertain whether this problem comes from an extension or not.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by innomatica** [comment]
I encountered with a similar case. 

As he describes it, it is purely by chance. So I do not have any reproduceable steps nor any screen shots. In my case, comment lines were not greyed out but maintained their colors as if they were not commented out, which is very confusing. 

I restarted the vs code then it was gone.

----------
Color Theme: GitHub Dark Default

----------
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.18.5-200.fc36.x86_64

**Comment by thany** [comment]
@mjbvz 

> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

I don't know. As said, this is hard to reproduce on-demand. It may go a whole day without messing up, or it may happen within minutes. So hypothetically:
* If it DOES still happen in Insiders without extensions - what extra information have we gained? That it still happens? That, we already knew...
* If it DOESN'T still happen in Insiders without extensions - who's to say it's actually fixed? It's an intermittent issue, therefor it is mathmatically impossible to check for its absence (just like the famous teapot orbiting Mars).

If a problem concerning this issue hasn't been fixed anywhere between the current stable release, and the master branch, then we should assume it hasn't been fixed. Instead of narrowing down which branch this does and doesn't happen on, we should focus on how to reproduce it first. Then and only then, we can ascertain whether it truly doesn't happen anymore on any given version.

And again, how to reproduce, I don't have an answer to that. I was hoping the experts did.

**Comment by mjbvz** [comment]
Sorry but that's not actionable. If it doesn't happen in insiders with extensions disabled, then this issue should be closed. If it does, try narrowing down steps to reproduce the problem so we can investigate it

**Comment by johnsoncodehk** [comment]
FYI, `Vue.vscode-typescript-vue-plugin` has caused similar problems before.

**Comment by thany** [comment]
If I try Insiders without extensions, I'm not only testing 2 variables at once (Insiders AND disabling extensions), I'm also in the dark as to what I'm supposed to do. I don't know how to reproduce this reliably. I would need help with that first - then I can try the same steps in Insiders.

In the same way, if this issue doesn't happen for you, @mjbvz, you cannot possibly prove it either. We can only prove that it DOES occur, if it does occur. This is just how provability works, I can't help it either.

So, the question is: what could *possibly* lead to this problem? What sort of reproduction steps can I try, without changing any other variables?

**Comment by mjbvz** [comment]
I've already said what to try: disable extensions. Another user even reported that one of the extensions you had installed (`vscode-typescript-vue-plugin`) caused similar problem

**Comment by thany** [comment]
Just trying stuff is a very unscientific way to track down a problem. Imagine if aviation did troubleshoting like that.

I will repeat myself one more time then: I DO NOT KNOW what to do in order to cause the problem. So whatever it is you want me to try, will never hope to prove that the problem is gone. I can only prove if it still happens, were I to know how to reproduce.

So I ask again: what sort of steps do YOU think I can undertake to get this problem to relaibly reproduce itself?

In the mean time, sure. Fine. I'll disable that extension. And maybe the problem doesn't happen. But then what? The problem hasn't occurred for a few days with this extension enabled. So if the problem seems to be gone, what exactly do we know that we didn't know before?

Like I said, unscientific.
