### ISSUE TITLE
Uninstall/Disable Jupyter Support

### ISSUE THREAD

**Issue by AVividLight** [microsoft/vscode#152007]
Hello,

I have never installed any extensions relating to Python, but when clicking File>New File... I'm asked whether I want to make a file or a Jupyter notebook. I think it would be a great if Jupyter support was not installed/enabled by default, or at least if there was a way to uninstall/disable it. Even the keybinds cannot be removed.

I searched through the help documents, as well as issues [#105661](https://github.com/microsoft/vscode/issues/105661), [#103526](https://github.com/microsoft/vscode/issues/103526), and [#144722](https://github.com/microsoft/vscode/issues/144722), but no solution has been provided.

Just to be sure, I started VS Code with the `--disable-extensions` argument, but the Jupyter support is still active. Searching settings for "Jupyter" only brings up one option for me, "Default Binary Editor." Nothing comes up for "ipynb."

Thank you for your consideration.

**Comment by SoftOrangeTech** [comment]
Same for me too - everyone has it ever since Microsoft put Jupyter notebooks.

**Comment by rebornix** [comment]
@AVividLight any particular reason why you want this feature to be disabled? It allows ipynb files to be opened and viewed, so not sure how the existence of it has impact on your workflow.

**Comment by AVividLight** [comment]
Hello @rebornix thanks for taking the time to reply to me. There are a few reasons that I created this issue:

* Even launching with `--disable-extensions` does not disable Jupyter support, which looks like a defect since it disables all other language support for me.
* Similarly, Jupyter support stands out as an oddly unique always-enabled feature. I had to install extensions for XML, Markdown, C++, etc., but not for Jupyter.
* I did not expect to see it because I have never installed any extensions for python. Using it is not part of my workflow, so it adds an extra step when creating a new file.

Hopefully my explanation makes sense. I think it boils down to this: Jupyter support doesn't behave like an extension even though it is (I assume) not a core part of VS Code and essentially a language add-on. I think it would create a more consistent experience for users if Jupyter support aligned with all other extensions.

Please let me know if I can do anything to help clarify my Issue.

Thank you very much!

**Comment by AVividLight** [comment]
@rebornix Hello, I'm just circling back on this to make sure I provided enough information to answer your question. Please let me know if there is anything else I can do to help!

Thank you very much!

**Comment by rebornix** [comment]
@AVividLight thanks for your input, they are really helpful. Our current thinking is allowing users to view `ipynb` files in expected way. This is similar to how images (i.e., PNG file) are being opened/viewed in VS Code, when users click on a PNG file in the File Explorer, we don't open it in a text editor, instead it's opened in a custom image preview editor.

Since it's shipped with the core, `--disable-extensions` won't disable it, same as other builtin extensions.

With that said, I do agree that it's weird to see `ipynb` as an option when you try to create files and reopen editors. Will have this issue open (not being closed by bot) and look forward to see more feedback from others.

**Comment by rebornix** [comment]
@AVividLight I just realized that you can acutally disable the builtin ipynb extension from the extension viewlet.

**Comment by AVividLight** [comment]
@rebornix Oh, thank you for looking into it! For anyone else who is looking for this, you have to filter Extensions by built-in, then you can click the gear by .ipynb support to disable it.
