### ISSUE TITLE
Icons missing from extension trees with resource uris

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#152036]
https://github.com/microsoft/vscode-cmake-tools/issues/2595

To reproduce:
1. Run the tree-view-sample from microsoft/vscode-extension-samples.
2. Open a folder.
3. Look at the File Explorer view and see that there are no icons

**Comment by joaomoreno** [comment]
On 30d9c6cd9483b2cc586687151bcbcd635f373630:

![image](https://user-images.githubusercontent.com/22350/173770327-680a592b-3dfd-417b-a201-3f1a8daa46a5.png)
