### ISSUE TITLE
Suggestion Widget Hangs on Markdown

### ISSUE THREAD

**Issue by ssigwart** [microsoft/vscode#152010]
Using an extension that provides PHP intellisense, it creates a suggestion widget with documentation for each file in the namespace.  The documentation includes a php code snippet in markdown for each file.  When the completion shows and it goes to show the details, it hangs VS Code while rendering.  While the extension can be updated to reduce the documentation size, the issue can be triggered in VS Code directly too.  The contrived typescript file below simulates the same effect.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.68.0 (Universal)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:00.250Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 20.6.0

Steps to Reproduce:

1.  Open attached [markdownHang.ts.txt](https://github.com/microsoft/vscode/files/8895998/markdownHang.ts.txt) file, but rename to `.ts`.
2.  Type "test" at the bottom.
<img width="810" alt="image" src="https://user-images.githubusercontent.com/1426848/173485010-5261bba0-d648-47e1-8683-fda09aee942d.png">

It will hang while typing.  If it doesn't you can copy/paste the JSDoc to make it longer.

I will open a PR in a few minutes to fix this.  It looks like the following tries to re-render after each markdown snippet instead of at the end.
https://github.com/microsoft/vscode/blob/4501f83b1e477f13f3b4c226f36431d49121622d/src/vs/editor/contrib/suggest/browser/suggestWidgetDetails.ts#L176-L179

**Comment by jrieken** [comment]
This happens  because the codeblock rendering is reporting [many async updates](https://github.com/microsoft/vscode/blob/57037a722805136ca8b9f736d6a250d2433c43e5/src/vs/base/browser/markdownRenderer.ts#L161) which has a cascade of relayouts. This is happens with suggest (as OT describes) but also when just hovering of the `test`-function
