### ISSUE TITLE
Extension "ms-vscode.references-view" Request Error

### ISSUE THREAD

**Issue by jjqk** [microsoft/vscode#152009]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version:

Steps to Reproduce:
"Error: Request https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/references-view/0.0.30/vspackage failed with status code:404"
1. Find an Internet Explorer, input "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/references-view/0.0.30/vspackage";
2. The result: "{"$id":"1","innerException":null,"message":"Resource not found","typeName":"Microsoft.VisualStudio.Services.Gallery.WebApi.ExtensionAssetNotFoundException, Microsoft.VisualStudio.Services.Gallery.WebApi","typeKey":"ExtensionAssetNotFoundException","errorCode":0,"eventId":3000}"

**Comment by TylerLeonhardt** [comment]
@jjqk this package was recently unlisted from the marketplace because it ships inside of vscode now. Is there a reason you're doing this?

**Comment by jjqk** [comment]
Packaging command ”yarn gulp vscode-win32-x64“ will fail upon extension "ms-vscode.references-view" request error。As for packaging， refer to https://github.com/microsoft/vscode/wiki/How-to-Contribute

[log.txt](https://github.com/microsoft/vscode/files/8926869/log.txt)

**Comment by jrieken** [comment]
@jjqk please make sure to be on the latest commit of our main branch. the download step of the extension is there anymore

**Comment by jjqk** [comment]
@jrieken You're right, our code change is based on an old version of vscode main branch. Days ago, it went well with packaging. All of a sudden, packaging seems impossible. Migrating our code change to the latest may take a long time. Is there any way/walkaround to finish the packaging for now (passing GitHub account to "yarn gulp vscode-linux-x64" as a parameter for example?)?  Thanks in advance.

**Comment by jrieken** [comment]
I'd say the easiest is to copy this folder in your fork (https://github.com/microsoft/vscode/blob/main/extensions/references-view) and to remove the "download to retrieve extension" step from the build instructions

**Comment by jjqk** [comment]
Thanks for the help
