### ISSUE TITLE
add task API for icon/color

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#152006]
Now that we support this for tasks of type `shell` and `process`, I think it makes sense to support it for contributed tasks as well

**Comment by Tyriar** [comment]
Perhaps this falls in the camp where we should only add it if people ask for it? One concern here is that an extension then defines the color not the user and it could lead to confusion. Perhaps a user always wants the tools icon to make it clear they're tasks for example.

**Comment by meganrogge** [comment]
Okay, but we need API to support setting icon/color for the VS Code build task. That's something I'd like to do

**Comment by alexr00** [comment]
> figured out a workaround for the VS Code build task w @Tyriar.

Does setting it in the tasks.json not work?
