### ISSUE TITLE
Show terminal persistent sessions setting when searching for "history"

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#152087]
I'm always returning to projects and see the terminal messages filled with the same repeated message and would like to clean them up and not be shown as I see no value in them for myself.

## Current
<img width="630" alt="CleanShot 2022-06-14 at 09 10 55@2x" src="https://user-images.githubusercontent.com/35271042/173625121-aafa5da4-52b5-47c2-9819-4a1b52ec50e6.png">

## Desired
<img width="622" src="https://user-images.githubusercontent.com/35271042/173625310-6fac865d-ee88-4e2c-8c00-c8197645ddc3.png">

**Comment by Tyriar** [comment]
This bugs me too, https://github.com/microsoft/vscode/issues/142855 tracks only showing it once in this case by avoiding saving new parts if there is no terminal input, similar to how it only saves and restored in the first place if the terminal has been interacted with. I don't think we should be hiding the message all together as it's misleading what is part of this shell's session, command decorations would be broken for the ones that aren't part of this session (look like a bug) and it would show up like this which is a bit weird:

![image](https://user-images.githubusercontent.com/2193314/173627737-4d71ca6a-1d63-4c48-9cfa-0f7a0e88e95a.png)

**Comment by misolori** [comment]
Would it be possible to have an option to hide the previous session altogether and just show a new session? That would be a simple approach that would work for me personally

**Comment by meganrogge** [comment]
@misolori you can just create a new terminal altogether by setting `terminal.integrated.enablePersistentSessions` to false

**Comment by misolori** [comment]
@meganrogge thank you! I was searching for a setting and didn't ever find that one, kept looking for "terminal history" and "terminal clear"

**Comment by meganrogge** [comment]
the name is definitely not discoverable. I wonder if we should change it @Tyriar

**Comment by misolori** [comment]
or can we add any meta data or keywords to settings that will be picked up by search? cc @rzhao271

**Comment by Tyriar** [comment]
`tags` I guess?

https://github.com/microsoft/vscode/blob/82222d60c8599240d4caa07a6e85f18c4bceb2bf/src/vs/platform/configuration/common/configurationRegistry.ts#L164-L169

**Comment by Tyriar** [comment]
Oh that doesn't work, @rzhao271 do we have a way to do search keywords?

**Comment by Tyriar** [comment]
@misolori you actually want `terminal.integrated.persistentSessionReviveProcess`, the `enablePersistentSessions` setting will disable process reconnect across window reloads.
