### ISSUE TITLE
Should "executing task" be localized?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152076]
I noticed some task messages weren't localized:

https://github.com/microsoft/vscode/blob/742cea83c591270917b6986d896c98a23545ebb3/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1113-L1117

https://github.com/microsoft/vscode/blob/742cea83c591270917b6986d896c98a23545ebb3/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1145-L1149

https://github.com/microsoft/vscode/blob/742cea83c591270917b6986d896c98a23545ebb3/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1248

Terminal support for unicode is pretty great now so if we have issues with other languages here we should fix them.

**Comment by alexr00** [comment]
Seems like a good idea. Changing these would only be an issue if we have extensions that are reading terminal output and looking for these strings.
