### ISSUE TITLE
 Port language server implementation to TS 2.0

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#15201]
Debt Item for Nov/Dec

I'm not sure, but this work may have already been completed: https://github.com/Microsoft/vscode-languageserver-node/commit/d0dddc1a351f066fad135b5018abe7a60d4b39b7

@dbaeumer Can you please add some more context to this issue. Is https://github.com/Microsoft/vscode-languageserver-node/ the correct code, or does this item target something else?

**Comment by dbaeumer** [comment]
@mjbvz this has nothing to do with the TS server in general. I should own that item. It is about a library that currently uses TS 1.8.10 to use 2.0.

**Comment by dbaeumer** [comment]
This is now available in the 3.0.1-alpha releases of the library.
