### ISSUE TITLE
NativeScript CLI not found, please run 'npm -g install nativescript' to install it.

### ISSUE THREAD

**Issue by crimsonmouse** [Microsoft/vscode#15203]
Hi, 

I've just installed VSCode and get an error: 
_**NativeScript CLI not found, please run 'npm -g install nativescript' to install it.**_

I have no idea how to resolve it.

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|HTMLHint|mkaufman|0.0.3|
|code-settings-sync|Shan|2.3.7|
|nativescript|Telerik|0.3.1|
|JavaScriptSnippets|xabikos|1.2.0|

Help, please....

**Comment by mrmlnc** [comment]
Caused by extension: https://github.com/NativeScript/nativescript-vscode-extension.
See "Install NativeScript" section: https://github.com/NativeScript/nativescript-vscode-extension#install-nativescript

**Comment by crimsonmouse** [comment]
many thanks,

but now I have:

_**[NativeScript-Debug-Adapter] The debug process exited unexpectedly code:1**_

**Comment by aeschli** [comment]
Please file an issue against https://github.com/NativeScript/nativescript-vscode-extension.
