### ISSUE TITLE
Please bring back the old File -> Open behavior (that selects from the directory of the current file)

### ISSUE THREAD

**Issue by mnieber** [microsoft/vscode#152075]
Until recently the File -> Open command opened a dialog in the directory of the current file. I heavily rely on that behavior to quickly find files in the context of the currently edited file. Starting today, the same command opens a dialog in the Recent Files directory. AFAICT this behavior is not customizable in the settings. Could this be fixed?

**Comment by floriansimon1** [comment]
I had the same issue. I had to downgrade to go back to the previous behavior.

**Comment by sebastienroul** [comment]
Oh yes, please bring back the old File... or make it customizable.
For us, the new behaviour is time consuming, especially on opening folders

IMHO : Customizable is the best option

Regards

**Comment by Skyline124** [comment]
Yes please, this is pretty annoying, I just noticed this too...

See my build:

![image](https://user-images.githubusercontent.com/14185951/173691358-ea66e0b0-217a-4126-9554-e44ea61c479f.png)

**Comment by bpasero** [comment]
Already fixed in insiders: You can give our preview releases a try from: https://code.visualstudio.com/insiders/
