### ISSUE TITLE
4 bugs for Search and Replace that steadily worsen our experience

### ISSUE THREAD

**Issue by Saltsmart** [microsoft/vscode#152084]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

# Search tab is tiny
The search tab is **catastrophically tiny** compared to the one for Python Extension:
For Jupyter:
![image](https://user-images.githubusercontent.com/40828952/173585011-a8c7a3a9-c876-4a53-b62f-12259a186439.png)

For Python:
![image](https://user-images.githubusercontent.com/40828952/173585089-09bcecdc-ee4e-49c7-bc79-872a89d3fdc6.png)

# Not supporting "select → Ctrl + F" to find the words
Please see #146361. I’ve switched to pre-release edition and found this bug remains unfixed.
![image](https://user-images.githubusercontent.com/40828952/173581992-56cf3cf8-c937-4d96-8961-cfd7ded1cbcd.png)

# Rename symbol (F2) failed
In the stable edition the rename box appears normally, but nothing changes after renaming.
![1](https://user-images.githubusercontent.com/40828952/173587838-64a4de87-4d93-40ad-aabe-29a2429dc45e.gif)

In the pre-release edition, a message "the element can't be renamed" pops up.
![image](https://user-images.githubusercontent.com/40828952/173584382-4ced27a8-139f-4979-9b16-61a96d82337e.png)

# Replace all failed
Press "Replace all" button, and then nothing happens.
![2](https://user-images.githubusercontent.com/40828952/173587125-8d18fdc7-af49-4a0e-be6b-5778da69d2b2.gif)

### VS Code Version

Version: 1.67.2 (system setup) Submit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5 Date: 2022-05-17T18:15:52.058Z Electron: 17.4.1 Chromium: 98.0.4758.141 Node.js: 16.13.0 V8: 9.8.177.13-electron.0 OS: Windows_NT x64 10.0.19043

### Jupyter Extension Version

v2022.4.1021342353

### Coding Language and Runtime Version

Python v3.8.12

### Language Extension Version (if applicable)

v2022.6.2

### Anaconda Version (if applicable)

2020.07

### Running Jupyter locally or remotely?

Local

**Comment by Saltsmart** [comment]
My jupyter extension was updated to v2022.5.1001601848 and vscode to 1.68.1.
I'm glad that Find/Replace works well in notebook. That's pretty NICE! 😍👍
The tab remains tiny. `Rename symbol` is failed as before. Hope the next version much better!

**Comment by rebornix** [comment]
> Search tab is tiny

The search tab is now resizeable.

> Not supporting "select → Ctrl + F" to find the words
