### ISSUE TITLE
undefined value when dnd from file explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#152031]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.69.0-insider (user setup)
Commit: ca8a8376b46b63db7379cbcc827c75d92bf25e14
Date: 2022-06-14T05:15:51.831Z
Electron: 18.3.2
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Clone the dnd sample: https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample
2. Add `'text/uri-list'` to the `dropMimeTypes` of  `TestViewDragAndDrop`
3. Add some logs in `handleDrop(...)`:
```
sources.forEach((value, key) => {
    console.log(`${key} : ${value.value}`);
});
```
4. Launch the extension
5. Drag files and folders to the dnd sample view, some undefined value can be seen. And such value won't be seen when drag files from the system file explorer:

https://user-images.githubusercontent.com/6193897/173537671-d6852fe6-3dd5-4097-8d1e-677e9dd3ea05.mp4

**Comment by alexr00** [comment]
@jdneo `value` is expected to be undefined here. Instead, you should call `asString()` to get the data.

`value` is for custom data provided by extensions when dragging within a tree. Example:
1. Extension implements `handleDrag` and `handleDrop`.
2. In `handleDrag`, they add some `DataTransferItem`s to the `DataTransfer`. These items have a value that is a custom object.
3. In `handleDrop`, they get their items from the `DataTransfer` and use `value` to get their custom object back.

@mjbvz does this align with how you are using `value` in editor drag and drop?

**Comment by jdneo** [comment]
I changed the code to 

```
sources.forEach(async (value, key) => {
    console.log(`${key} : ${await value.asString()}`);
})
```

It's still undefined. Is there anything I missed?

**Comment by alexr00** [comment]
I'm seeing that mostly work. Console output:
```
[Extension Host] text/uri-list : undefined (at d:\repos\Microsoft\vscode-extension-samples\tree-view-sample\src\testViewDragAndDrop.ts:65:12)
console.ts:137
[Extension Host] text/uri-list : file:///d%3A/repos/alexr00/playground/no_extension
file:///d%3A/repos/alexr00/playground/not_in_ws
file:///d%3A/repos/alexr00/playground/test2.js 
```

There does appear to be an issue where text/uri-list is in there twice, which is a bug.

**Comment by alexr00** [comment]
Looks like the double text/uri-list bug will be fixed by https://github.com/microsoft/vscode/pull/150468 though.

**Comment by jdneo** [comment]
Have no idea why but on my machine, if I drag a folder, it still only has an undefined entry: (insider is updated to latest)

https://user-images.githubusercontent.com/6193897/173963598-33e571f4-5d4a-46b0-8b0c-364aeb369d7f.mp4

**Comment by alexr00** [comment]
I can repro when I drag a folder.

**Comment by alexr00** [comment]
Tested with https://github.com/microsoft/vscode/pull/150468, and the `undefined` issue is also resolved by that PR.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/pull/150468
