### ISSUE TITLE
Provide tooltip for gutter actions

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#152088]
Originally from testing out https://github.com/microsoft/vscode/issues/25887

When hovering items in the gutter, we don't provide any tooltip for additional information about what each item is and does (with the exception of an added breakpoint). We should provide this additional information as we already for other actions and for added breakpoints to give new users and indication of the action will do as well as a name for the given action:

- [x] Adding breakpoints
- [x] SCM decorators
- [x] Diff arrow decorators
- [x] Folding regions

https://user-images.githubusercontent.com/35271042/173626852-14bd4b48-bed5-49f7-b1fb-06ddc164c1d2.mp4

**Comment by hediet** [comment]
![Image](https://github.com/microsoft/vscode/assets/2931520/3c415ef4-bf63-4eb5-9362-9b4ba7049dae)

![Image](https://github.com/microsoft/vscode/assets/2931520/bf8fb1f2-f70c-43dc-85af-03b13d3cc407)

![Image](https://github.com/microsoft/vscode/assets/2931520/6c35f47d-9671-4904-97d4-3fea930d95d8)

![Image](https://github.com/microsoft/vscode/assets/2931520/edd6d46f-3f96-4135-85fd-471d8b8320a5)
