### ISSUE TITLE
[css] support @layers 

### ISSUE THREAD

**Issue by ScriptJayT** [microsoft/vscode#152058]
Issue Type: <b>Feature Request</b>

the use of css @layer is reported in the problems terminal as unknown.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by aeschli** [comment]
duplicate of #147354
