### ISSUE TITLE
Can't launch remote window from debugger

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#152083]
Version: 1.69.0-insider (Universal)
Commit: d8823e67a907b3fa176068ad802682ccd74f8083
Date: 2022-06-14T10:34:01.122Z
Electron: 18.3.2
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

I have this launch config:
```
{
	"name": "Extension Remote",
	"type": "extensionHost",
	"request": "launch",
	"runtimeExecutable": "${execPath}",
	"args": [
		"--extensionDevelopmentPath=${workspaceFolder}",
		"--remote=tunneling+silly-grosbeak:8000"
	],
	"outFiles": ["${workspaceFolder}/out/**/*.js"],
	"preLaunchTask": "npm: watch-web"
}
```

That I would expect to open the extension host window in a remote window just as opening VS Code from the terminal does:
```
code-insiders --extensionDevelopmentPath=/Users/tanha/Documents/GitHub/vscode-server-basis-utility/extension/ --remote=tunneling+silly-grosbeak:8000
```

The terminal command works but the launch config doesn't.

For easier testing I tried also with SSH remote authority like this:
```
code-insiders --extensionDevelopmentPath=/Users/tanha/Documents/GitHub/vscode-server-basis-utility/extension/ --remote=ssh-remote+tanha 
```

And 

```
{
	"name": "Extension Remote",
	"type": "extensionHost",
	"request": "launch",
	"runtimeExecutable": "${execPath}",
	"args": [
		"--extensionDevelopmentPath=${workspaceFolder}",
		"--remote=ssh-remote+tanha"
	],
	"outFiles": ["${workspaceFolder}/out/**/*.js"],
	"preLaunchTask": "npm: watch-web"
}
```

**Comment by tanhakabir** [comment]
Ah I see.

> Usually the recommended approach here is to debug the extension in the remote workspace

Could you clarify here?

**Comment by connor4312** [comment]
You can run/clone your extension on the remote machine and then debug normally from there; you'll get a second remote window when you do

**Comment by tanhakabir** [comment]
Ah got it

**Comment by connor4312** [comment]
Actually solved this, local development is okay. I'll close this for housekeeping since it only affects us and isn't a huge convenience imo 🙂
