### ISSUE TITLE
Should test tasks default to the $(beaker) icon?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152057]
This is the main thing I wanted from the task icons, if tasks of of kind `test` to use the beaker:

![image](https://user-images.githubusercontent.com/2193314/173583866-937c3696-a39d-437f-9843-09caec890f02.png)

I think this makes sense over a setting since we can now override them via the `icon` property and the beaker icon aligns with our testing pane

**Comment by alexr00** [comment]
I like it!
