### ISSUE TITLE
Git Pull Conflict: Accept/Reject Incoming and Current Pull

### ISSUE THREAD

**Issue by Abdul-ahmed** [microsoft/vscode#152033]
Issue Type: <b>Bug</b>

Hey VS, I notice current bug on our amiable VS Code Editor, this bug is related and attached to git/github. In details, this is just a bug/problem that comes after pulling from origin and there is conflict that arise. To fix it with the existing inbuilt function of Accept/Reject Incoming and Current Pull, notice it not working or there for use again. Kindly check on that, it's not working anymore, I've notice this from about 2-3 engineers in my organization here.

VS Code version: Code 1.68.0 (4af164ea3a06f701fe3e89a2bcbb421d2026b68f, 2022-06-08T11:44:16.822Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.62GB free)|
|Process Argv|. --crash-reporter-id 6f63692a-9823-4051-8945-124ba3134623|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
ionic4-snippets-vscode|4tr|1.4.0
vscode-sqlite|ale|0.14.1
ng-template|Ang|14.0.1
laravel-goto-view|cod|1.3.7
angular-schematics|cyr|5.2.3
ionic3-vs-ionView-snippets|dan|1.0.2
vue-peek|dar|1.0.2
phptools-vscode|DEV|1.9.9585
Vue2|duc|0.1.3
vscode-html-css|ecm|1.12.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vue-format|feb|0.1.8
file-icons|fil|1.0.29
vscode-ionic-snippets|fiv|2.2.2
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
laravel-create-view|gli|0.0.6
findfile|Has|0.0.4
vscode-test-explorer|hbe|2.21.1
vue-snippets|hol|1.0.4
laravel-blade-wrapper|IHu|1.0.1
ionic-preview|ion|0.0.20
vue|jcb|0.1.5
ionic2-vscode|jgw|1.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.0.1
vscode-phpfmt|kok|1.0.31
vue|liu|0.1.5
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-scss|mrm|0.10.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
powershell|ms-|2022.5.1
test-adapter-converter|ms-|0.1.6
vscode-typescript-tslint-plugin|ms-|1.3.4
cordova-tools|msj|2.4.1
debugger-for-chrome|msj|4.13.0
sqltools|mtx|0.23.0
sqltools-driver-sqlite|mtx|0.2.0
laravel-goto-components|nao|1.2.0
vetur|oct|0.35.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
rxjs-snippets|pko|0.0.2
sqlite-viewer|qwt|0.1.5
ionicons|rea|0.0.9
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.5
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.14.7
ionic3-snippets|sit|1.0.1
autoimport|ste|1.5.4
code-spell-checker|str|2.2.3
ionic2|Tha|3.0.2
Angular2|UVB|0.4.1
vscode-icons|vsc|11.12.0
vue|Wsc|1.0.26
php-debug|xde|1.27.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by lszomoru** [comment]
@Abdul-ahmed, could you please provide me with the exact repro steps that I should use the reproduce the issue? Also, if you have any screenshots of error messages that you are seeing, please share those as well. Thank you!
