### ISSUE TITLE
"scanning" indicator appears in status bar

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15207]
Does anyone know what this is?  

![screen shot 2016-11-08 at 3 10 25 pm](https://cloud.githubusercontent.com/assets/835148/20115311/d75b0d44-a5c5-11e6-8705-5a5933e00030.jpg)

I can't seem to track it down; clicking it does nothing and there's no tooltip. Not sure if it's core or an extension, or what it's scanning.  It never finishes.

- VSCode Version: Code - Insiders 1.8.0-insider (a3e85d60a32f91efccfe6161c3a4673ad909496e, 2016-11-08T15:02:34.236Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.3.7|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.1.15|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.0.8|
|tslint|eg2|0.5.40|
|auto-close-tag|formulahendry|0.3.4|
|auto-rename-tag|formulahendry|0.0.7|
|Angular1|johnpapa|0.1.16|
|theme-karyfoundation-themes|karyfoundation|7.4.0|
|vscode-stylefmt|mrmlnc|2.0.1|
|nonbreakingspace|smlombardi|0.0.1|
|stylelint|shinnn|0.18.1|
|theme-tesla|smlombardi|0.0.1|
|autoimport|steoates|1.2.2|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

**Comment by aeschli** [comment]
It's not part of VSCode.
Maybe do a text search inside your [extension folder](https://code.visualstudio.com/docs/extensions/install-extension)

**Comment by mrmlnc** [comment]
@smlombardi, this is 100% related to html-css-class-completion by Zignd.

**Comment by smlombardi** [comment]
@mrmlnc This persists after uninstalling that extension.

**Comment by smlombardi** [comment]
FWIW, it was not that extension.  Not sure which it was, but I uninstalled everything but essentials and so far it has stopped.  I have re-installed Zignd's extension and the problem did not return (yet).

**Comment by mrmlnc** [comment]
@smlombardi, Sorry, I could be wrong. In your set of extensions can have the capability of scanning:

  * autoimport (https://github.com/soates/Auto-Import/search?utf8=%E2%9C%93&q=scanning&type=Code)

**Comment by smlombardi** [comment]
yes I removed that.  i suspect it is the culprit.  thanks.
