### ISSUE TITLE
Unable to download vscode on ssh  remote host - wget download failed

### ISSUE THREAD

**Issue by guy0guy** [microsoft/vscode#152183]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.0
- OS Version: windows 10

After upgrading to vscode 1.68 I am no longer able to connect to my remote SSH Linux host. it keeps failing when it tries to do wget, returning with "wget download failed"
I had no such issues before.
I have tried killing the server on host and uninstalling the server on host but it did not help.
I have also tried clean uninstall of vscode and reinstall it - again did not help.
I can SSH into the host with no problems.
Also, I have downloaded latest code-insiders and with code-insiders version 1.69.0 it is WORKING and was able to do wget - so no problems with permissions on host.
appreciate any help you can provide to resolve it.
Thanks
Steps to Reproduce:

1. connect to host
2.

**Comment by roblourens** [comment]
This could be https://github.com/microsoft/vscode/issues/152185, but could you share the full log from the "Remote - SSH" output channel?

![image](https://user-images.githubusercontent.com/323878/58114233-2c56fb00-7bac-11e9-8b26-23053f14763f.png)

**Comment by guy0guy** [comment]
After upgrading to version 1.68.1, issue seem to have been resolved.
Thanks
