### ISSUE TITLE
Failed to connect to the remote extension host server (Error: Server returned 404)

### ISSUE THREAD

**Issue by stnorbi** [microsoft/vscode#152185]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.68.0
- OS Version: Windows 10

Approx. after one week after update to version 1.68.0 this issue happens.
 
Steps to Reproduce:

1. Connecting to remote host by Remote Development Extension
2. Time outing with the following error message: "Failed to connect to the remote extension host server (Error: Server returned 404)"

Log snippet:
[13:50:55.686] Downloading VS Code server locally...
[13:50:55.935] Resolver error: Error: Server returned 404

Thank you for your quick reply and resolution in advance.

Cheers,
Norbi

**Comment by aludkiew** [comment]
I'm experiencing this too. Looks like the same issue as https://github.com/microsoft/vscode/issues/147324

**Comment by chrisptree** [comment]
I have the same problem. I looked to debug window and I saw that the URL in the header is wrong:
Request URL: https://update.code.visualstudio.com/commit%3A4af164ea3a06f701fe3e89a2bcbb421d2026b68f/server-linux-x64/stable
Request Method: GET
Status Code: 404 Not Found
Remote Address: 40.64.128.224:443
Referrer Policy: strict-origin-when-cross-origin

The request URL should be instead:
Request URL: https://update.code.visualstudio.com/commit:4af164ea3a06f701fe3e89a2bcbb421d2026b68f/server-linux-x64/stable
where the %3A has been replaced by :

**Comment by roblourens** [comment]
Tracking this in https://github.com/microsoft/vscode-remote-release/issues/6804
