### ISSUE TITLE
MAC OS x el capitan vscode upgrade to 0.10.5 cannot be used

### ISSUE THREAD

**Issue by ryj438591419** [Microsoft/vscode#1521]
MAC OS x el capitan vscode upgrade to 0.10.5 cannot be used

**Comment by Onlytanya** [comment]
you can start up code  with a English-US keyboard layout.

**Comment by jrieken** [comment]
closing as duplicate of #1463

**Comment by ryj438591419** [comment]
@Onlytanya  oh ! thank

**Comment by jrieken** [comment]
sorry, for the hassle. we hope to get an update out soon
