### ISSUE TITLE
Polish language identified with its English name (unlike other languages)

### ISSUE THREAD

**Issue by tymtam2** [microsoft/vscode#152140]
Does this issue occur when all extensions are disabled?: Unknown

- VS Code Version:
Version: 1.68.0 (user setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
- OS Version:
10.0.19044
Steps to Reproduce:

1. Open command palette 
2. Find Activate "Configure Display Language"
    ![image](https://user-images.githubusercontent.com/1097613/173719915-418a9489-6284-4376-b4fe-e85adb9467ce.png)
    ![image](https://user-images.githubusercontent.com/1097613/173719968-5703c31b-ee03-4be0-ab5c-8676787f3364.png)
3. Type 'p'
    ![image](https://user-images.githubusercontent.com/1097613/173720017-0a797d01-f375-476b-bfc8-dc8c7961faff.png)

4. EXPECTED: Polish is identified with its Polish name 'polski'. 
    ACTUAL: Polish is identified using its English name. This is unlike other languages which use their name in that language (e.g. Deutsch, italiano, pусский, 中文, etc.)

**Comment by TylerLeonhardt** [comment]
Yep, this is incorrect here:
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-pl/package.json#L24

Would you like to submit a PR updating it to what it should be?

**Comment by tymtam2** [comment]
@TylerLeonhardt Thanks for looking into it, I'll submit a PR

**Comment by TylerLeonhardt** [comment]
This is now in but it is pending a publish of the language packs... So you can only verify this if:
https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-pl 
was `last updated` of a day after Jun 27th.
