### ISSUE TITLE
New arrow to revert changes in diff editor interferes with setting breakpoints from diff editor

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#152115]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have some diff
2. Notice that on all lines but the first, hovering in the gutter allows you to set a breakpoint. On the first line there is now an arrow, which appears to have come in through https://github.com/microsoft/vscode/pull/151826:
![image](https://user-images.githubusercontent.com/30305945/173687401-eba52a60-e813-4f8f-8c11-eb2a24ac8582.png)

3. :bug: the arrow doesn't have a tooltip which makes it hard to tell what it's for or where it came from (I figured it out by inspecting the element).
4. :bug: this makes it impossible to set breakpoints on the first line of a diff from the diff editor, which is something that I use a fair bit. Could we consider having this action show up somewhere else (e.g. in a codelens), or having a setting to disable this action?

Additionally, I'd like to suggest the [`discard` codicon](https://github.com/microsoft/vscode-codicons/blob/main/src/icons/discard.svg). We use this for git reverts, and IMO it's more intuitively related to reverting a change (I was initially a little surprised by what the right arrow button did)

**Comment by yume-chan** [comment]
refs #25887 

> the arrow doesn't have a tooltip 

#152088

**Comment by hediet** [comment]
@Mingpan do you have ideas for this?

**Comment by Mingpan** [comment]
> @Mingpan do you have ideas for this?

I don't know if there is a way to make both "revert change" and breakpoints work in the same line. But I think a setting to disable "revert change" sounds very reasonable. +1 to it.

> surprised by what the right arrow button did

I think the right arrow is supposed to indicate "move / copy what's on the left to the right side". I feel like it's a common practice when working with side-by-side views? But changing it could also be reasonable if more people prefer `discard` icon, or if it's a UX decision due to consistency reason within VS Code.

**Comment by hediet** [comment]
I actually prefer the arrow. But a tooltip and a setting to disable that might indeed be helpful. We are open for a PR here ;)

**Comment by AnrDaemon** [comment]
Ref to #3130

**Comment by hediet** [comment]
> Happy to add a setting for it :)

That would be great!

> Tooltip is definately helpful. I will also see if I might be able to do it - it feels like a general improvement needed, which is tracked by #152088

That would be very helpful if there is an easy fix.

Thanks a lot!
