### ISSUE TITLE
Notebook API tests editor editing event

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#152145]
```
  1) Notebook API tests
       editor editing event:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:132:11)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174304&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15&l=677

**Comment by bpasero** [comment]
Failed again, will skip.

**Comment by rebornix** [comment]
Very likely the share the same root cause as https://github.com/microsoft/vscode/issues/155587

**Comment by rebornix** [comment]
Should now be resolved. If we see it later we would create an issue and treat as bug.
