### ISSUE TITLE
Inconsistency in error/warning shown when trying to load markdown preview

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#15215]
- VSCode Version: Code - Insiders 1.8.0-insider (a3e85d60a32f91efccfe6161c3a4673ad909496e, 2016-11-08T15:09:13.902Z)
- OS Version: Windows_NT ia32 10.0.14959
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|PowerShell|ms-vscode|0.7.2|
|rewrap|stkb|0.6.3|

---

Steps to Reproduce:

1. Open md file
2. Ctrl+Shift+V to launch markdown preview:
![image](https://cloud.githubusercontent.com/assets/494055/20119257/a8314dac-a5bc-11e6-8c8f-eedb3c0efd75.png)
3. Click on icon to launch markdown preview 
![image](https://cloud.githubusercontent.com/assets/494055/20119266/b4225b1a-a5bc-11e6-9b64-ce4fb318f3f3.png)

**Comment by mjbvz** [comment]
I do not believe this is markdown specific. The difference here is also by design. We currently surface missing keybinding commands (such as Ctrl+Shift+V) as warnings, but we surface missing UI commands as errors.
