### ISSUE TITLE
Background tasks should drop their terminal status when they exit

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152141]
This situation below confuses me sometimes as it looks like the watch task is well and good but it actually exited with a code of 0:

<img width="1266" alt="Screen Shot 2022-06-14 at 7 18 39 pm" src="https://user-images.githubusercontent.com/2193314/173722602-8c83d591-71b3-4cd6-8669-f158f1ba2d6e.png">

I think the better behavior is to show the failure status if the exit code is non-zero and remove the status if the exit code is 0.

**Comment by alexr00** [comment]
Makes sense!
