### ISSUE TITLE
Can't revert change that deletes a single empty line in side-by-side diff editor

### ISSUE THREAD

**Issue by Mingpan** [microsoft/vscode#152165]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69-insider
- OS Version: MacOS Monterey

Steps to Reproduce:

1. Having a side-by-side diff editor
2. Make a change that removes a single empty line
3. Try to revert the change with the arrow #151826

![Screenshot 2022-06-15 at 10 56 31](https://user-images.githubusercontent.com/15076498/173788595-58933e55-c9e8-4dee-88af-bb1309ef97ca.png)

Due to an inaccurate if check in revertChange method [1], the delete of an empty line is not correctly recognized (sorry about that!)

@hediet 

[1] https://github.com/microsoft/vscode/blob/1bf95bcd9ec667f2f9d0a577e4383caf4073adae/src/vs/editor/browser/widget/diffEditorWidget.ts#L646 shoud be `... && originalContent != null)` instead of just checking `... && originalContent)`

**Comment by hediet** [comment]
Thanks! It would be awesome if we had some tests for this!
