### ISSUE TITLE
TypeScript language service died unexpectedly

### ISSUE THREAD

**Issue by cfjedimaster** [microsoft/vscode#152107]
Issue Type: <b>Bug</b>

I'm getting constant error notifications with: 

The TypeScript  language service died unexpectedly 5 times in the last 5 minutes.

Source: TypeScript and JavaScript Language features

I can dismiss this, but it just comes back.

VS Code version: Code - Insiders 1.69.0-insider (d8823e67a907b3fa176068ad802682ccd74f8083, 2022-06-14T12:13:57.353Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (5.21GB free)|
|Process Argv|--crash-reporter-id c444811d-cb40-4051-ac5d-3876d0238cbe|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|Memory (System)|15.46GB (9.95GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
javascript-ejs-support|Dig|1.3.1
vscode-peacock|joh|4.0.1
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.66.3
language-liquid|nei|0.1.1
material-icon-theme|PKi|4.18.1
alpinejs-syntax-highlight|spe|1.0.1
gistfs|vsl|0.4.1
codesnap|adp|1.3.4
spellright|ban|3.0.64
markdown-preview-github-styles|bie|1.0.1
flat|git|0.23.3
vscode-graphql|Gra|0.4.12
vscode-cfml|Kam|0.5.4
vscode-azurefunctions|ms-|1.7.3
vscode-azureresourcegroups|ms-|0.5.3
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
jupyter|ms-|2022.6.1001671126
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
azure-account|ms-|0.10.1
wordcount|ms-|0.1.0
gremlins|nho|0.26.0
vetur|oct|0.35.0
indent-rainbow|ode|8.3.1
polacode|pnp|0.3.4
code-spell-checker|str|2.2.4
svelte-vscode|sve|105.17.0
pdf|tom|1.2.0
volar|Vue|0.37.8
vscode-typescript-vue-plugin|Vue|0.37.8
markdown-pdf|yza|1.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by cfjedimaster** [comment]
I'm running latest Insiders. After disabling extensions, the error went away, but as it reports an _internal_ extension (built in I mean)... not sure what to do next. :)

**Comment by mjbvz** [comment]
If the error goes away when you disable all external extensions, then one of them is causing it. You can use [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) to track down which one is causing this

Is that the case?

**Comment by cfjedimaster** [comment]
Trying bisect now. So it's possible for another extension to cause a problem where an internal Code feature then throws an error?

**Comment by mjbvz** [comment]
Yes, most likely `vscode-typescript-vue-plugin`

**Comment by cfjedimaster** [comment]
Yeah, that was the culprit. I had trouble w/ bisect, but I got to a point where I could toggle it off and on and see it show up and go away. Thanks for your help!
