### ISSUE TITLE
"Switching to" Release Notes editor, even if it is already open, causes it to reload.

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#15214]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14959
- Extensions: (running with --disable-extensions)

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.0|
|cpptools|ms-vscode|0.9.2|
|PowerShell|ms-vscode|0.7.2|
|rewrap|stkb|0.6.3|

---

Steps to Reproduce:

1. Help > Release Notes
2. After it loads, click on the already-visible Release Notes tab => reloads the tab
3. Try using Ctrl+Tab to switch to the tab for the already-visible Release Notes editor => reloads
4. Try using the Open Editors panel to click on the already-open Release Notes tab => reloads

Expected behavior:

If nothing has changed (no change in which editor view is opened, and the content has not changed), there is no need for a reload. Even if a different editor is displayed and the content has not changed (and is all static and present on disk), a reload should not be necessary.

Notes:

The markdown preview has the behavior that when you click on or "switch to" the already opened view, it does not reload. However, if you switch away from it and back, it reloads dynamic content (like images hosted online).

**Comment by Noyabronok** [comment]
This is also a problem when looking at `.md` file previews

**Comment by dilijev** [comment]
Still repros in 1.11.1

**Comment by mjbvz** [comment]
8ef9c4b should address the release notes being reloaded when they are already showing. Switching away from a webview and then back to it does still require a reload. This currently by-design. I'm investigating a way to preserve scroll position even in these cases with #22995
