### ISSUE TITLE
Remote-SSH Error

### ISSUE THREAD

**Issue by HitachiWangNJU** [microsoft/vscode#152221]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68
- OS Version: WIN10 21H2

Steps to Reproduce:

1. update to ver 1.68 from 1.67 without any change in localhost and server
2. open any remote even which was opened yet
3. could not connect any remote which could use at last ver
4. bug report: Error: Server returned 404
5. refresh extension or .ssh files or update or reinstall could not make any use
6. reinstall the ver 1.67 and any problem could be solved
7. i dont know what happened

**Comment by abkarcher** [comment]
I am having this same issue after the update to 1.68.

Thanks,
Andrew

**Comment by roblourens** [comment]
Sorry for the trouble, this was https://github.com/microsoft/vscode-remote-release/issues/6804 but should now be resolved.
