### ISSUE TITLE
[i18n] Improve jpn locale

### ISSUE THREAD

**Issue by akimasa** [Microsoft/vscode#15223]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra 10.12.1
In  `vscode/i18n/jpn/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.i18n.json`
```
	"actions.previewDecl.label": "ピークの定義",
```
It should be
```
	"actions.previewDecl.label": "定義をここに表示",
```
Translation of [Visual Studio 2015](https://msdn.microsoft.com/ja-jp/library/dn160178.aspx) looks good.
Are you using different translation in Visual Studio Code?

**Comment by johnliu2016** [comment]
@lukaschal, file is /Localize/jpn/vscode/src/vs/editor/contrib/goToDeclaration/browser/goToDeclaration.nls.resx.lcl,

suggested JPN is "定義をここに表示"

       <Item ItemId=";actions.previewDecl.label" ItemType="0;.resx" PsrId="211" Leaf="true">
        <Str Cat="Text">
          <Val><![CDATA[Peek Definition]]></Val>
          <Tgt Cat="Text" Stat="Loc" Appr="PreApproved" Orig="New">
            <Val><![CDATA[ピークの定義]]></Val>
          </Tgt>
        </Str>
        <Disp Icon="Str" />
      </Item>

**Comment by lukaschal** [comment]
Waiting for linguistic input.

**Comment by lukaschal** [comment]
@akimasa  Please, is it possible to add ENU and JPN screenshot of mentioned issue ?

**Comment by akimasa** [comment]
<img width="293" alt="2016-11-11 20 20 41" src="https://cloud.githubusercontent.com/assets/4647736/20213577/a3d35e52-a84c-11e6-9e56-4a250a5099df.png">
<img width="417" alt="2016-11-11 20 21 38" src="https://cloud.githubusercontent.com/assets/4647736/20213576/a3d31ea6-a84c-11e6-909f-e69ee032cbee.png">

**Comment by lukaschal** [comment]
Fixed as suggested.

File: src\vs\editor\contrib\goToDeclaration\browser\goToDeclaration.nls.resx
ID: ".resx", 0; "actions.previewDecl.label"
SRC: Peek Definition
TGT: 定義をここに表示
