### ISSUE TITLE
Select files or forders by key pressed 

### ISSUE THREAD

**Issue by AbelaroJiang** [Microsoft/vscode#15226]
- VSCode Version:1.7.1
- OS Version: Win10

Steps to Reproduce:
In Explorer, make it can select the files or folders by key press. 
such as, we have files aaa.txt, aab.txt bbb.txt, ccc.txt in current workspace.
please help us to add the feature to quickly select file of which name start by 'c' when press key 'c'.

thanks.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/10839
