### ISSUE TITLE
remove usage of EventSource in favour of Event & Emitter

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#1522]
Event was a stepping stone towards the new event mechanism we now use. In favour for clarity and a compact codebase we should remove usages and implementation of EventSource et al. Staring with @bpasero

**Comment by bpasero** [comment]
:+1:

**Comment by bpasero** [comment]
<img width="502" alt="screen shot 2015-12-21 at 15 32 14" src="https://cloud.githubusercontent.com/assets/900690/11932767/08c989ea-a7f8-11e5-89c0-bad37288e80b.png">

**Comment by jrieken** [comment]
Yeah!
