### ISSUE TITLE
Show horizontal scroll bar when PR comments are too long.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#152273]
Issue Type: <b>Bug</b>

If a github comment is too long, for e.g a code comment, then the Comment view in the editor clips the text, there is no way to copy the code comment. 

![image](https://user-images.githubusercontent.com/3840081/173969089-8f086139-c169-4613-af05-9e6b10f8a4f2.png)

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (48.93GB free)|
|Process Argv|--crash-reporter-id 8a06823c-8219-469b-a5be-5ad36c5c7a1c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.2.2
gitlens|eam|12.1.0
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
codespaces|Git|1.9.0
remotehub|Git|0.34.0
vscode-pull-request-github|Git|0.44.0
azure-pipelines|ms-|1.205.0
vscode-docker|ms-|1.22.0
black-formatter|ms-|2022.3.11611002
isort|ms-|2022.3.11611002
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.20
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.10.1
live-server|ms-|0.2.12
remote-repositories|ms-|0.12.0
vsliveshare|ms-|1.0.5625
code-spell-checker|str|2.2.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by alexr00** [comment]
This has since been fixed.
