### ISSUE TITLE
Debug Console search

### ISSUE THREAD

**Issue by stevedekorte** [microsoft/vscode#152239]
I'd like to request a search feature in the Debug Console, like the one for searching code, as filter doesn't help when one needs to know the context of the occurrence. 

If a search feature isn't approved or may take some time, could the ability to copy the content of the debug console be quickly enabled (it's currently not in Version: 1.68.0), so we can search in an external editor? Thanks!

**Comment by roblourens** [comment]
> the ability to copy the content of the debug console be quickly enabled

You can right click > Copy All, is that what you are looking for?

**Comment by roblourens** [comment]
Also, this issue for search: https://github.com/microsoft/vscode/issues/4338
