### ISSUE TITLE
Provide workbench.action.nextEditor/previousEditor that cycle through current active group

### ISSUE THREAD

**Issue by cvax** [Microsoft/vscode#15225]
### Feature Request
As per this [comment in #7664](https://github.com/Microsoft/vscode/issues/7664#issuecomment-226469230), would like the ability to cycle through only the selected group. Currently it cycles through all editors in all groups. This isn't how it works in other editors like Sublime and is quite a bit counter intuitive.

**Comment by bpasero** [comment]
@cvax I do not understand, Ctrl+Tab will never cycle across groups unless you changed your keybindings?

**Comment by cvax** [comment]
Sorry, in the context of #7664, you [suggested](https://github.com/Microsoft/vscode/issues/7664#issuecomment-225895819) us to bind those to ```workbench.action.nextEditor``` and ```workbench.action.previousEditor```. The issue is that those commands are insufficient to achieve "like browser tab behavior" since they cycle through all groups instead of only currently active one.

**Comment by bpasero** [comment]
@cvax thanks, I remember now what this is about.

**Comment by bpasero** [comment]
@cvax to clarify, you expect this to go through the list of tabs in visible order and not most recently used order? So, if you have 5 tabs open, no matter how recently you opened them, you can navigate left and right in just that group with keybindings?

**Comment by cvax** [comment]
@bpasero That's correct.  Looking for option to go sequentially just like in Chrome/Firefox/etc. You press Ctrl+Tab to go to next tab in group regardless of last used and Ctrl+Shift+Tab to go to previous tab.

The reason MRU is a bit annoying is because when you have two files open you can't just tab over to what you want.

**Comment by bpasero** [comment]
Makes sense. Pushed to master. To configure what you want it would be:

```json
{ "key": "ctrl+tab", "command": "workbench.action.nextEditorInGroup" },
{ "key": "ctrl+shift+tab", "command": "workbench.action.previousEditorInGroup" }
```

**Comment by shanalikhan** [comment]
@bpasero i see you make this issue https://github.com/Microsoft/vscode/issues/15319 duplicate to this one, so if i want to switch to last opened tab without picker i can use command ?

**Comment by bpasero** [comment]
@shanalikhan yeah it should work already from our insiders release. 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by shanalikhan** [comment]
@bpasero are you sure, it will open the last tab ?
> That's correct. Looking for option to go sequentially just like in Chrome/Firefox/etc. You press Ctrl+Tab to go to next tab in group regardless of last used and Ctrl+Shift+Tab to go to previous tab.

My scenario is that issue is separate fro this one, what if user has opened 2 tab and my extension open tab in 6 location , i want to keep it in background and let user to switch to 2nd tab , not 5th tab by previous command neither 1st tab after moving to first one after last tab. I want to switch to last opened tab that is for example second tab.

**Comment by bpasero** [comment]
@shanalikhan so you want to navigate in MRU order? that would be via `Ctrl+Tab` and `Ctrl+Shift+Tab`.

**Comment by bpasero** [comment]
Verification: Configure

```json
{ "key": "ctrl+tab", "command": "workbench.action.nextEditorInGroup" },
{ "key": "ctrl+shift+tab", "command": "workbench.action.previousEditorInGroup" }
```

And verify this allows you to navigate in one group left or right through the list of opened tabs without seeing the picker.
