### ISSUE TITLE
Update vscode error

### ISSUE THREAD

**Issue by sevenzoe** [Microsoft/vscode#15224]
- VSCode Version: 1.0.0
- OS Version: Windows10

Steps to Reproduce:

1. VSCode auto update.
2. Update is complete, Click "update now" button.
3. System.Windows.MessageBox.Show("The setup files are corrupted, Please obtain a new copy of the program", "Error");

**Comment by joaomoreno** [comment]
Does this reproduce when attempting once again? If it does, please [manually download the setup](http://code.visualstudio.com/?utm_expid=101350005-31.YsqwCVJESWmc4UCMDLsNRw.0#alt-downloads).

**Comment by mjbvz** [comment]
Closing since we have not heard back on whether this is still an issue.

@sevenzoe Please let us know if you are still seeing this or if reinstalling VSCode fixed things

Thanks

**Comment by sevenzoe** [comment]
Yes, this problem has been solved,
Thanks
