### ISSUE TITLE
Yran install error

### ISSUE THREAD

**Issue by wanghuangyi** [microsoft/vscode#152282]
$ yarn --ignore-engines
error Command failed with exit code 1.
![QQ截图20220616110812](https://user-images.githubusercontent.com/73694443/173982747-9b517b51-95f5-40e0-818d-940bf4b44dc0.png)

**Comment by wanghuangyi** [comment]
Don't know how to deal with this problem

**Comment by joaomoreno** [comment]
Does this reproduce with just `yarn`?

**Comment by wanghuangyi** [comment]
之前那个问题已经解决了，现在出了一个新问题。我重新发一个
