### ISSUE TITLE
copy / paste not work if strings contains 'NUL' 0x00

### ISSUE THREAD

**Issue by qin-nz** [microsoft/vscode#152284]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows 11 21H2

Steps to Reproduce:

1. Select some strings that contains 0x00 , e.g. 
![image](https://user-images.githubusercontent.com/6998071/173983092-a24aa705-624f-47b2-b49f-8c380dd8cc36.png)

2. copy it & paste it at other tab.
3. got 
![image](https://user-images.githubusercontent.com/6998071/173983022-dc3b4cc6-45c7-4043-bcc4-2ca2e6f6e5f4.png)

**Comment by aeschli** [comment]
Is the first view a terminal? What about the tab you paste it in?

**Comment by qin-nz** [comment]
No, not a teminal. 
Copy from editor, and paste to ediotr.
I mean: 
![image](https://user-images.githubusercontent.com/6998071/174278085-f14f6a11-be53-4f89-be1b-30043916af82.png)

**Comment by alexdima** [comment]
This is a well known limitation of the Windows clipboard -> https://superuser.com/a/1071346
