### ISSUE TITLE
Add function preview summary window to editor

### ISSUE THREAD

**Issue by scmaverick** [Microsoft/vscode#15222]
- VSCode Version: 1.7.1
- OS Version: Windows 7 Ent

In netbeans, there is an internal panel that will show you all the classes and functions that are found in the file currently with the focus, if you click on the function or the class within the panel, it will take you right to the defining line in the file.
I find this so extremely useful for when you are searching through a file for any given function or just overlooking the file contents. This is an easy way to look at all the classes and their members that have been defined in the file. That for programming languages,
For HTML, CSS for example it will show the file tree and the classes. This a pretty smart file preview.
It'd be nice to have this feature in VSC as well.

**Comment by aeschli** [comment]
Can you add a screenshot of the panel that you propose?
To navigate to symbols in the current open editor we have `Ctrl + Shift + O`. To navigate to symbols in the workspace `Ctrl + T`, to file `Ctrl + P`

**Comment by wilferraz** [comment]
A similar feature is provided by the ctags + sidekick plugin. This particularly useful because it's static and you can look at the big picture in the same time that you are digging in the source code.
![siekick](https://cloud.githubusercontent.com/assets/22823004/20408159/3ef4409c-ace2-11e6-852b-2c38b5b4c29a.gif)

**Comment by scmaverick** [comment]
Hi, sorry for the late response but I was pulled away.
Here is a screenshot of the Navigator panel in Netbeans for a PHP file where it is listing all the functions contained in it:
![image](https://cloud.githubusercontent.com/assets/9893119/20418727/2adc4bca-ad16-11e6-8169-e373f23e1fa4.png)

This is what it looks like for CSS and HTML:

![image](https://cloud.githubusercontent.com/assets/9893119/20418756/69a2c38e-ad16-11e6-9852-2f51991093e8.png)

And this is for another PHP file that only contains a class, where SAF\Tables is the namespace, Entry_Relations is the name of the class, \Common\MyTable is the namespace:class that its extending, and the final 3 marked with triangles are constants:

![image](https://cloud.githubusercontent.com/assets/9893119/20418807/c747dc40-ad16-11e6-91c2-b95a660a68de.png)

Wilferraz, I couldn't find the sidekick plugin for VS Code, or were you talking about something that exists for another IDE?
Thanks

**Comment by wilferraz** [comment]
I was talking about a JEdit plugin. This is a simple editor I have used for years when developing code for industrial devices. I think that VS code is light years better than JEdit but this is a feature that I liked very much. And yes, it is similar to the netbeans navigator that you mentioned.

Will

Sent from my iPhone

On Nov 17, 2016, at 11:41 PM, scmaverick <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, sorry for the late response but I was pulled away.
Here is a screenshot of the Navigator panel in Netbeans for a PHP file where it is listing all the functions contained in it:
[image]<https://cloud.githubusercontent.com/assets/9893119/20418727/2adc4bca-ad16-11e6-8169-e373f23e1fa4.png>

This is what it looks like for CSS and HTML:

[image]<https://cloud.githubusercontent.com/assets/9893119/20418756/69a2c38e-ad16-11e6-9852-2f51991093e8.png>

And this is for another PHP file that only contains a class, where SAF\Tables is the namespace, Entry_Relations is the name of the class, \Common\MyTable is the namespace:class that its extending, and the final 3 marked with triangles are constants:

[image]<https://cloud.githubusercontent.com/assets/9893119/20418807/c747dc40-ad16-11e6-91c2-b95a660a68de.png>

Wilferraz, I couldn't find the sidekick plugin for VS Code, or were you talking about something that exists for another IDE?
Thanks

-

**Comment by ramya-rao-a** [comment]
@wilferraz @scmaverick Please go through the discussion in #15485 for current thoughts on hierarchical file outline view.

#15533 is tracking the api needed to implement this.

Will close the current issue in favor of #15533 and #15485
Please add your thoughts/upvotes in these tracking issues

**Comment by DanTup** [comment]
FWIW, #15533 is about type hierarchy (subclasses, superclasses etc. which may be in other files) and not about visualising the current file. #5605 is possible what's being asked for here?

**Comment by ramya-rao-a** [comment]
@DanTup Thanks! My mistake. You are right. #5605 is what is being asked here.
@wilferraz @scmaverick Please add your up votes to #5605
