### ISSUE TITLE
Declare property quick fix incorrectly escapes `$`

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#152272]
Issue Type: <b>Bug</b>

For the ts:

```ts
class Foo {
    bar() { 
        this.$prop 
    }
}
```

2. Trigger `declare property` on `this.$prop`

**Bug**:
`\$prop` is inserted instead of just `$prop`

```ts
class Foo {
    \$prop: any;
    bar() { 
        this.$prop
    }
}
```

VS Code version: Code - Insiders 1.69.0-insider (Universal) (0b74e15affc1b44a5b7cd671dd0a02d3ed6d51a7, 2022-06-15T05:20:12.417Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (0.25GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
@jrieken I believe this may be caused by the workspace snippet edit work. Here's how we build up the edit:

https://github.com/microsoft/vscode/blob/813c0b2178d091ac209e7e684261182ddafea856/extensions/typescript-language-features/src/utils/typeConverters.ts#L90

I confirmed that the incoming text does not have the `\`

**Comment by duncan-faulkner** [comment]
also adds slash on save
to get around this save without formatting ctrl +k ctrl + shft +s
I assume this is only on the insiders version
![image](https://user-images.githubusercontent.com/107635194/174105112-1e860fee-dffe-40a2-9218-f69c18af4c4a.png)

**Comment by JonWallsten** [comment]
@mjbvz: The extra slash is still added to import lines in latest VSCode Insiders. Not at the same frequency as before. But once every 5-10 minutes or so.
