### ISSUE TITLE
Document format is very slow | CPU | Any extention

### ISSUE THREAD

**Issue by justnonamenoname** [Microsoft/vscode#15221]
- VSCode Version: 1.5-1.7.1 (didn't tested <1.5)
- OS Version: Windows 7

Steps to Reproduce:

1. Check Format Document on this file - 40k lines
www.gta-samp.com/size.cpp

clang-format.exe works 1 second
but Code.exe stuck at CPU 100% for a minute

Visual Studio 2013 format this file in second

**Comment by aeschli** [comment]
Formatting for CPP is provided by an extension. What extensions do you use for c/c++? Can you file this issue against the extension directly?

**Comment by justnonamenoname** [comment]
If you delete ms-vscode.cpptools and install 
marketplace.visualstudio.com/items?itemName=ryannaddy.vscode-format
or change filename to .css Code.exe will stuck at CPU 100% too

Also run
extention dir\ms-vscode.cpptools-0.9.2\LLVM\bin
clang-format.exe size.cpp
it will format in 3 seconds too

It's not problem of extension

**Comment by sean-mcmanus** [comment]
This seems like a bug in VS Code. It looks like there's lots of processing occurring in Node.dll. Our extension process and clang-format.exe finish quickly.

**Comment by jrieken** [comment]
@sean-mcmanus Can you clarify how you have measured that? Can you check the activity monitor/process monitor and find the processes of VS Code with high load?

**Comment by sean-mcmanus** [comment]
Yeah, I just look at what is going on in Task Manager and optionally attached a debugger. After opening the file and waiting for the background processes to finish, and then formatting, our Microsoft.VSCode.CPP.Extension.exe runs and then causes clang-format.exe to runs both of which are quick and run fast while stepping through with the debugger, but then after returning the result of the formatting, Code.exe starts to do some CPU intensive operation for over a minute.

**Comment by jrieken** [comment]
Do you have a sample/repo steps?

**Comment by sean-mcmanus** [comment]
Yeah, I just used the repro steps and sample code provided by @justnonamenoname.

**Comment by jrieken** [comment]
Thanks. I can repo, it's the extension host that goes crazy, I guess because of the some extra work we do after format is done... 

![screen shot 2016-11-14 at 17 52 43](https://cloud.githubusercontent.com/assets/1794099/20273896/40f21668-aa93-11e6-89d7-b2a3fc11afe0.png)

**Comment by jrieken** [comment]
So, this is the problem... Formatters are supposed to describe their changes as [`TextEdits`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L2082) such that we can apply them. For various reasons formatters often problem only a single edit alá *select all text and replace it with this*. While that is valid it will cause cursors to collapse, decorations to be re-applied, the whole text to be redrawn etc... Bad. To counter that we re-diff text edits in the extension to ensure the result are minimal edits. Apparently, this takes a long time here...

```
[Extension Host] START, checking 1 edits now...
extensionHost.js:239 [Extension Host] DONE after 89448ms, with NEW 57098 edits
```

For the above sample, the extension computed a single edit which we broke down into almost 60 thousand smaller edits. It's a string-diff algorithm with square'ish runtime... We should cap it at some value.

**Comment by jrieken** [comment]
related to #15456 since this will make the extension host appear as dead

**Comment by jrieken** [comment]
Closing after two changes: (1) computing more minimal edits now happens in a separate worker thread and (2) we skip very large edits for which computing more minimal edits will take long

**Comment by roblourens** [comment]
If I make the document much smaller, I can see the effect of the format, so it will do something eventually. But full size one, I gave it 8 minutes...

**Comment by roblourens** [comment]
With a smaller cpp file, I can verify that @jrieken's two changes work as described. With the original size.cpp, we tell the extension to format and it doesn't return for a long time, so I assume it's just the extension being slow.
