### ISSUE TITLE
Replace with Regex broken in "Find in folder..."

### ISSUE THREAD

**Issue by Daijobou** [microsoft/vscode#152246]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
- OS Version:
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Extract this ZIP-folder with two files **with the same content**
[files.zip](https://github.com/microsoft/vscode/files/8912452/files.zip)
2. Call "Find in folder..."
3. Search as Regex this:
`=>\n([\t ]+)array\(`
Replace with
`=> array(`

Result is different: One time file1.php is fine and file2.php is broken. Than both files are fine or both files are broken.
Maybe it has something to do with the fact that sometimes the files were open and sometimes not?

file1.php fine
```
<?php

return array(
  'key1' => array(
    'key2' => 'text',
	'key3' => 'text',
  ),
  'key4' => array(
    'key5' => array(
    ),
  )
);
```
file2.php broken
```
<?php

return array(
  'key1' => array(
    'key2' => 'text',
	'key3' => 'text',
  ),
  'key4' => array(=> array( =>
    array(
    ),
  )
);
```

Addional information:
Same replace directly in file via STRG+F always working. Its only a issue with replace via "Files in folder..."

I hope that here is not somewhere my mistake. ;)

**Comment by roblourens** [comment]
This is another instance of https://github.com/microsoft/vscode/issues/131507
