### ISSUE TITLE
Remote extension host not disposed after closing vscode client

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#152204]
- VS Code Version: stable

Steps to Reproduce:

1. Connect to a remote vscode server using remote-ssh extension
2. Close the remote vscode window
3. In another terminal, ssh into the remote machine and use `ps aux` to list all processes, observer the extension host process keeps running 

You can also repro it from sources 
1. Launch `code-server.sh`
2. Connect to it using `vscode-test-resolver` extension
3. Close window
4. Observe remote extension host keeps running

**Comment by jeanp413** [comment]
This is the PR that caused the regresion https://github.com/microsoft/vscode/pull/150167/files
cc @alexdima

**Comment by gjsjohnmurray** [comment]
Is #152236 relevant?

**Comment by jeanp413** [comment]
@gjsjohnmurray I pulled latest changes and still can repro from sources

**Comment by jeanp413** [comment]
After some debugging I found that if you add a `timeout(..., 0)` around this [block if code here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/extensions/electron-browser/nativeLocalProcessExtensionHost.ts#L92-L99) fixes the issue though I have no clue why this change in the local extension host is affecting the remote extension host :sweat_smile:

**Comment by jeanp413** [comment]
After some debugging I found that if you add a `timeout(..., 0)` around this [block if code here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/extensions/electron-browser/nativeLocalProcessExtensionHost.ts#L92-L99) fixes the issue though I have no clue why this change in the local extension host is affecting the remote extension host :sweat_smile:
