### ISSUE TITLE
Flatpak's isolation breaks integrated terminal 

### ISSUE THREAD

**Issue by vadim0x60** [microsoft/vscode#152200]
Issue Type: <b>Bug</b>

I can't get the VS code integrated terminal to behave like my system terminal. The biggest issue is that the PATH variable is not set correctly and both me and VS code extentions that run terminal commands keep getting "command not found"s whenever we are trying to run anything.

I set the following profile:

```
"terminal.integrated.profiles.linux": {
        "bash": {
          "path": "bash",
          "args": ["--login", "-i"]
        }
      },
```
and some commands started working, but not all. After some investigation, I pinned down that the integrated terminal now runs my `/home/vadim/.profile` script, but does not run `/etc/profile`.
Moreover, if I run

```
cat /etc/profile
```

I get

```
cat: /etc/profile: No such file or directory
```

And if I run `ls /etc` I get a very short list of files in `/etc` that happen to be owned by my user and not by root. So my best guess is that all of this is some permissions issue. None of these issues are reproducible in my system terminal. 

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.17.5-76051705-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.07GB (0.44GB free)|
|Process Argv|--extensions-dir=/home/vadim0x60/.var/app/com.visualstudio.code/data/vscode/extensions --reuse-window --crash-reporter-id f9c21049-1822-4f55-8463-e01b3eda0e0e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.64
calva|bet|2.0.286
copilot|Git|1.29.6152
vscode-pull-request-github|Git|0.42.0
gc-excelviewer|Gra|4.2.55
vscode-git-add-and-commit|iva|2.1.1
latex-workshop|Jam|8.27.2
language-haskell|jus|3.6.0
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.10
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.10.1
cpptools|ms-|1.10.6
powershell|ms-|2022.5.1
win-ca|uko|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by vadim0x60** [comment]
OK, so after some more investingation I found out that I only have this problem if vscode is installed via flatpak. If I install it with `apt`, the issue is not there. So this is probably a consequence of flatpak's isolation system.

**Comment by vadim0x60** [comment]
Sorry, @VSCodeTriageBot, but the latest version of VS code on flathub is 1.67.0

**Comment by Tyriar** [comment]
The Flatpak is community maintained so you should go through the provider of that.
