### ISSUE TITLE
Inline code font ugly rendering

### ISSUE THREAD

**Issue by Ross-Li** [microsoft/vscode#152229]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

The rendering of my inline code is too ugly.
Before rendering:
![image](https://user-images.githubusercontent.com/61273074/173527263-69c3dbb8-5fd1-44e8-b717-ac494f85d7cb.png)
After rendering:
![image](https://user-images.githubusercontent.com/61273074/173527291-3ef70b96-300a-4250-8d5e-c01cab3e52ce.png)

I can't find the settings about changing the inline code rendering font to `Consolas`. Is there a way to do that? If currently such feature isn't available, can you please add this feature to later versions?

### VS Code Version

1.68.0

### Jupyter Extension Version

v2022.5.1001601848

### Coding Language and Runtime Version

Python v3.8.8

### Language Extension Version (if applicable)

v2022.8.0

### Anaconda Version (if applicable)

conda 4.12.0

### Running Jupyter locally or remotely?

Local

**Comment by mjbvz** [comment]
Right now you are creating a bunch of inline code snippets. Instead you should use a markdown code block:

~~~md
```sql
your code
```
~~~

**Comment by Ross-Li** [comment]
The code block can render the input as Consolas font

![image](https://user-images.githubusercontent.com/61273074/174025432-ba1a4bfc-cda4-4ee2-b8bb-11bfe9b7b3f4.png)
![image](https://user-images.githubusercontent.com/61273074/174025893-a304dca4-e584-4af7-aac3-18ef96faaefa.png)

But the inline code still won't render as Consolas font. I guess I try to use code blocks instead of inline code whenever possible.
