### ISSUE TITLE
Flickering in file recommendation

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#152226]
![Recording 2022-06-15 at 12 41 29](https://user-images.githubusercontent.com/4544166/173881099-bededaf6-a713-425e-a0d2-db423b08935f.gif)
File based extension recommendation notification appears to hide then reshow causing a flickering

**Comment by sandy081** [comment]
Can you please provide steps to repro?

**Comment by sandy081** [comment]
I am seeing following recommendation when I open `.ipynb` file. Do you have any extensions installed or anything special with your set up?

<img width="463" alt="image" src="https://user-images.githubusercontent.com/10746682/173909929-66bca686-68c2-4bd6-9dab-2c890c535f61.png">

**Comment by lramos15** [comment]
No this is with a fresh user data dir and extension dir

**Comment by sandy081** [comment]
I am also on clean slate 🤔

**Comment by lramos15** [comment]
Not sure, I tried to do it again this morning and am not getting it. Will close then
