### ISSUE TITLE
Centered Layout Cuts off the first letter on each wrapped line after first line

### ISSUE THREAD

**Issue by sahil48** [microsoft/vscode#152357]
Does this issue occur when all extensions are disabled?: Yes/No

Version Info:

![image](https://user-images.githubusercontent.com/6100774/174122729-1df74b60-b39e-49c8-ad12-b5d3961b9e3a.png)

Steps to Reproduce:

1. Unmaximize the window
2. Toggle the centered layout for a markdown document
3. Resize the layout. Sometimes, the letter will be cut off when the line wraps.

![image](https://user-images.githubusercontent.com/6100774/174122521-8c29e523-6560-4c52-9cee-ac552a18d715.png)

**Comment by sahil48** [comment]
Any update on this bug?

**Comment by alexdima** [comment]
@sahil48 Can you still reproduce this? I have tried for quite a while but couldn't trigger this issue:


https://user-images.githubusercontent.com/5047891/205254166-8bfc841e-072b-4cb3-9408-cc49f966868e.mp4

**Comment by sahil48** [comment]
@alexdima Thank you for looking into this. I cannot reproduce at my end either. Let's close this issue.
