### ISSUE TITLE
Render modifier only keybindings correctly

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#15233]
Today, pressing `cmd` is rendered as `cmd+unknown` in the define keybindings.

**Comment by alexandrudima** [comment]
Now we render `cmd+cmd`, which is better than `cmd+unknown`

**Comment by chrmarti** [comment]
Now just `cmd+` is shown. Somehow the display below the text field shows what looks like a small empty box where later the character goes. Maybe that could be improved by not showing that? Marking verified.

Here with `Shift + Cmd` from the screenshot shortcut:
![screen shot 2017-03-31 at 10 08 55 am](https://cloud.githubusercontent.com/assets/9205389/24561152/95cb7472-15fa-11e7-88d9-b22190da956f.png)
