### ISSUE TITLE
Provider event waits for `onDidChangeTextDocument` promise to resolve

### ISSUE THREAD

**Issue by Sarrus1** [microsoft/vscode#152352]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68
- OS Version: Windows 10

I have the following code:

```ts
// index.ts file
Workspace.onDidChangeTextDocument(
    providers.itemsRepository.handleDocumentChanges,
    providers.itemsRepository,
    context.subscriptions
);
```

```ts
// change event file
  public handleDocumentChanges(event: TextDocumentChangeEvent) {
    console.debug("Change event received", performance.now());
    handleDocumentChange(this, event).then((e) =>
      console.debug("Parsing done", performance.now())
    );
    console.debug("Change event handled", performance.now());
  }
```

```ts
// completion provider file
public async provideCompletionItems(
    document: TextDocument,
    position: Position,
    token: CancellationToken
  ): Promise<CompletionList> {
    console.debug("provider event", performance.now());
    return completionProvider(this.itemsRepository, document, position, token);
}
```

With this code, I expect "provider event" to appear almost instantly in my console when I edit a textdocument, however, it waits for `handleDocumentChange` to resolve:
![consolelog](https://user-images.githubusercontent.com/63302440/174114034-d8a653d1-5d81-4c57-8350-eab87f9ece32.PNG)

Replacing the call to `handleDocumentChange` to a `setTimeout` fixes the issue.

Is this intended behaviour?

**Comment by jrieken** [comment]
yeah, that's the designed/intended behaviour. document changes are processed before reaching out to extension/providers. thats to ensure everyone knows the latest and greatest state of the document
