### ISSUE TITLE
Indent to bracket option?? 

### ISSUE THREAD

**Issue by sewashinobi** [Microsoft/vscode#15237]
- VSCode Version: 1.7.1
- OS Version: Windows 7 

In Sublime Text settings we can set the indent_to_bracket option to indent the code to the starting bracket. What is the equal option for visual studio code settings.json?

**Comment by alexandrudima** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
