### ISSUE TITLE
Auto-import adds backslash to `}`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#152333]
https://user-images.githubusercontent.com/5047891/174086606-3fccfc5e-0d2b-4868-a7b3-c6e6410607cd.mp4

**Comment by Dovernh** [comment]
it also occurs when you select "Declare Method" from the "light bulb"

**Comment by mjbvz** [comment]
Duplicate of #152272 

/cc @jrieken

**Comment by duncan-faulkner** [comment]
also adds slash on save
