### ISSUE TITLE
Add command to 'Switch to Changes View' and 'Switch to Editor View'

### ISSUE THREAD

**Issue by sskogen** [Microsoft/vscode#15234]
Feature request: Add a keyboard bind-able command for the actions 'Switch to Changes View' and 'Switch to Editor View'.

From what I can see, these actions are only accessible by mouse in the top tight corner of the file being edited. In order to see the changes view for the file being edited with the keyboard only, one must open the git bar, then use tab, arrows and enter to switch to the 'Changes View' for the certain file.

**Comment by joaomoreno** [comment]
This makes for a great PR!

**Comment by sskogen** [comment]
The OpenInEditorAction ('Switch to Editor View') does not seem to have a keyboard bind-able command.
However, the GlobalOpenChangeAction  ('Git: Open Change'), which has a keyboard command, seems to open a diff view similar to OpenInDiffAction ('Switch to Editor View'). Is there any difference in these views?
If not, I only need a keyboard command for 'Switch to Editor View'.

**Comment by nicot** [comment]
Does the `workbench.action.git.globalOpenFile` action (`Git: Open File` command) do this?

**Comment by sskogen** [comment]
@nicot: thanks, I should have noticed that earlier! Unless there are any difference between the GIT commands 'Open Change' / 'Open File' and the buttons for 'Switch to Changes View' / 'Switch to Editor View', this feature request can be closed 😃

**Comment by joaomoreno** [comment]
Well spotted!
