### ISSUE TITLE
JSDoc syntax highlight. Not supported type '...*'

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#15239]
- VSCode Version:

![image](https://cloud.githubusercontent.com/assets/3082812/20135773/90c6cff4-a682-11e6-966f-848580ab35ba.png)

- OS Version: win7 pro

Steps to Reproduce:

I'm used a Google Closure-Type notation:
https://github.com/google/closure-compiler/wiki/Types-in-the-Closure-Type-System#template-types

![image](https://cloud.githubusercontent.com/assets/3082812/20135975/a625b9d6-a683-11e6-807d-d027ed7b5599.png)

Make JSDoc comments:

Not highlighted type and the argument name:

![image](https://cloud.githubusercontent.com/assets/3082812/20135849/f96b098a-a682-11e6-9222-74c46cf02314.png)

And how it works:

![image](https://cloud.githubusercontent.com/assets/3082812/20135869/14ca28f0-a683-11e6-833b-7535e78390d4.png)

And so:

![image](https://cloud.githubusercontent.com/assets/3082812/20135877/243e41a4-a683-11e6-8035-9f6b51536d08.png)

In the example from Google:

![image](https://cloud.githubusercontent.com/assets/3082812/20136076/156f7ebc-a684-11e6-9de3-3929639ca550.png)

I think `{function(this:T, ...)}` a wrong. Must be `{function(this:T, ...*)}`, but so, too, does not work

![image](https://cloud.githubusercontent.com/assets/3082812/20136156/761a1222-a684-11e6-8aed-4cef9c552aa4.png)

And so, too, does not work

![image](https://cloud.githubusercontent.com/assets/3082812/20136267/e335f5f6-a684-11e6-8fbe-56ac357656b3.png)

**Comment by waderyan** [comment]
@bowdenk7 we've talked about this a bit. Is this specific scenario on your radar? Do you have an issue to track this?

**Comment by IgorNovozhilov** [comment]
@waderyan, I have another example of a valid type combinations, which is not allocated:
```
@returns {Proxy<function(...args):Promise<string, Error>>}
```
it is a combination of: `Object<prop type>` and `function`

![image](https://cloud.githubusercontent.com/assets/3082812/20862049/86c4f2fa-b9b1-11e6-9d34-823bd91fef9a.png)

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#13797
