### ISSUE TITLE
MD file preview seems lost CRLF,pls check

### ISSUE THREAD

**Issue by wenbaofu** [Microsoft/vscode#15231]
- VSCode Version:1.7.1
- OS Version: Win7

Steps to Reproduce:

1. new file "test.md"
2. input  like below
test
test
3. click preview at the top of file(ctrl + shit +V)
4. I hope can get 
test 
test
but I get test test

I think lost one CRLF,when I add another CRLF,then like 
test 
test

pls check

**Comment by mjbvz** [comment]
The markdown preview targets Commonmark markdown, so this is the expected newline behavior. You can see this same behavior here: http://spec.commonmark.org/dingus/

Thanks.
