### ISSUE TITLE
Navigate to terminal error lists fuzzy matches

### ISSUE THREAD

**Issue by ivanschuetz** [microsoft/vscode#152306]
Error on terminal, e.g.:
```
warning: unused import: `Error`
  --> src/foo_bar.rs:10:14
```

If I cmd-click on `src/foo_bar.rs:10:14`, to navigate to it, VSCode shows a list with 
```
foo_bar.rs
foo_hello_bar.rs
```

It should navigate directly to `foo_bar.rs`.

I started experiencing this issue 2 weeks or so ago. Before that it navigated correctly.

VSCode version 1.68.0

**Comment by meganrogge** [comment]
works for me in insider's

**Comment by ivanschuetz** [comment]
Ok, it started working as expected after a restart (I think?)
