### ISSUE TITLE
vscode app bar in windows is not black anymore.

### ISSUE THREAD

**Issue by DarkHeros09** [microsoft/vscode#152393]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044

- OS Version: Win10 21H2

The issue:
the app bar was black before updating to the latest version 1.68.1, and now it's ugly.

Steps to Reproduce:

1. update to the latest version 1.68.1

![vscode app bar color](https://user-images.githubusercontent.com/39935182/174171264-a9714554-05b2-4e45-bff7-4bc4b89d7aac.png)

**Comment by sbatten** [comment]
@DarkHeros09 what part is the app bar? Can you clarify which part of the picture has changed?

**Comment by DarkHeros09** [comment]
![vscode app bar color](https://user-images.githubusercontent.com/39935182/174356393-911bc0ee-7ca4-4a6c-89b3-f39951c41fa9.png)

in comparison before
![build_gradle](https://user-images.githubusercontent.com/39935182/174356493-ad15e993-4cec-474e-b12a-0aaf3e27d8ca.PNG)
:

**Comment by sbatten** [comment]
it looks like you have enabled the native titlebar, please update your setting for `window.titleBarStyle` to `custom`

**Comment by DarkHeros09** [comment]
> window.titleBarStyle

YES thank you, FYI i have two laptops and both of them had the same issue after updating vscode, and i didn't change any settings. it happened right after updating.
again thank you.

**Comment by sbatten** [comment]
@DarkHeros09 that's very strange, i'll be keeping an eye for this
