### ISSUE TITLE
Auto language detection false positive for ini

### ISSUE THREAD

**Issue by Hacksore** [microsoft/vscode#152373]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: macOS

Currently, when pasting in a tree-like text payload the model is choosing `ini` as the language to switch to.

Steps to Reproduce:

1. Install the [tree plugin](https://marketplace.visualstudio.com/items?itemName=CTC.vscode-tree-extension)
2. Paste in text payload
```
├── functions
├── src
│    ├── articles
│    ├── components
│    ├── constants
│    ├── contexts
│    ├── data
│    ├── hooks
│    ├── i18n
│    │    └── locales
│    ├── modals
│    │    └── sections
│    ├── pages
│    │    ├── app
│    │    └── r
│    ├── styles
│    ├── templates
│    └── utils
└── static
    └── images
        ├── screenshots
        └── templates
```

Demo
![2022-06-16_13-40-41 (1)](https://user-images.githubusercontent.com/996134/174142816-8fbe61ac-570d-4704-a0f0-6a4ddd605800.gif)

Downstream issues:
https://github.com/microsoft/vscode-languagedetection/issues/9
https://github.com/structure-codes/vscode-tree-language/issues/13

cc @alex-oser

**Comment by djbusby** [comment]
Is this related to https://github.com/microsoft/vscode/issues/116729 where the INI files are sometimes read as a 'properties' type?  That's where INI then incorrectly chooses '#' as comment rather than ';' like it should

**Comment by Hacksore** [comment]
@TylerLeonhardt I'd love to keep this open if we can make forward progress otherwise might just need to close it out.

**Comment by TylerLeonhardt** [comment]
We can leave it open. It's on the Backlog meaning it's not actively being worked on... but it should be kept so we don't forget

**Comment by Hacksore** [comment]
@TylerLeonhardt I no longer use vscode so this is not relevant for me to keep open anymore. 

I'd suggest you aggregate this issue into a shared one with more issues related to language autodetection.

**Comment by TylerLeonhardt** [comment]
Fair enough. I'll link this to https://github.com/microsoft/vscode/issues/166332 and https://github.com/microsoft/vscode/issues/131450 which do call out issues that guess INI
