### ISSUE TITLE
Saving a large file says running TS/JS formatter, clicking configure says it's disabled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152354]
Repro:

1. Open bundled workbench.desktop.main.js
2. Save, the formatter progress notification shows
3. Click configure
4. Settings show up and say it's disabled?

![image](https://user-images.githubusercontent.com/2193314/174115533-d3a9eaf2-7350-4405-a14a-8768230a0f89.png)

This didn't happen every time I tried to save 🤷

**Comment by jrieken** [comment]
@Tyriar is this in the vscode repo? there we have a workspace setting to enable formatting on save

**Comment by Tyriar** [comment]
I had `microsoft/vscode` open but the file was `C:\Users\Daniel\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.js`. After looking at settings a little deeper this appears to be a problem in the settings UI:

![image](https://user-images.githubusercontent.com/2193314/174330959-991835e2-a1c2-42ea-9838-cce1b1873fcc.png)

![image](https://user-images.githubusercontent.com/2193314/174331011-2756da3a-cb8e-4a9a-bcff-f7ce8f6d99a8.png)

![image](https://user-images.githubusercontent.com/2193314/174331076-1433cce4-ade5-4b61-a874-ad79de836b43.png)

**Comment by rzhao271** [comment]
Is the problem that the Settings editor isn't showing the language override, or is the problem that the extension link didn't redirect to a query with the language filter? The first issue is tracked at https://github.com/microsoft/vscode/issues/145731

**Comment by Tyriar** [comment]
It's #145731 👍 thought it had already made it in
