### ISSUE TITLE
signatureHelp does not show parameters if signatures-documentation is null

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#152320]
With php-instellisense when a function does not have a php docblock, the parameter hint window will not be shown.

The following request and response will be sent:

```
[Trace - 13:04:06] Sending request 'textDocument/signatureHelp - (3)'.
Params: {
    "textDocument": {
        "uri": "file:///c:/local_disk/zobo/Projects/vscode-php-debug/vscode-php-debug/testproject/return.php"
    },
    "position": {
        "line": 10,
        "character": 3
    },
    "context": {
        "isRetrigger": false,
        "triggerCharacter": "(",
        "triggerKind": 2
    }
}
```

```
[Trace - 13:04:06] Received response 'textDocument/signatureHelp - (3)' in 32ms.
Result: {
    "signatures": [
        {
            "label": "(int $a, int $b, mixed $c)",
            "documentation": null,
            "parameters": [
                {
                    "label": "int $a",
                    "documentation": null
                },
                {
                    "label": "int $b",
                    "documentation": null
                },
                {
                    "label": "mixed $c",
                    "documentation": null
                }
            ],
            "activeParameter": null
        }
    ],
    "activeSignature": 0,
    "activeParameter": 0
}
```
No parameter hint window will be displayed.

However if I change the code so that the `documentation` field has an empty string it will work:

```
[Trace - 13:05:37] Received response 'textDocument/signatureHelp - (2)' in 46ms.
Result: {
    "signatures": [
        {
            "label": "(int $a, int $b, mixed $c)",
            "documentation": "",
            "parameters": [
                {
                    "label": "int $a",
                    "documentation": null
                },
                {
                    "label": "int $b",
                    "documentation": null
                },
                {
                    "label": "mixed $c",
                    "documentation": null
                }
            ],
            "activeParameter": null
        }
    ],
    "activeSignature": 0,
    "activeParameter": 0
}
```

![image](https://user-images.githubusercontent.com/2456026/174057159-f680b437-0807-47c1-b3cd-522275d83e8f.png)

According to https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_signatureHelp it should be allowed:

```
	/**
	 * The human-readable doc-comment of this signature. Will be shown
	 * in the UI but can be omitted.
	 */
	documentation?: string | MarkupContent;
```

**Comment by dbaeumer** [comment]
`null` is not a valid value for the documentation property. You need to leave the property out if no documentation is provided. See https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#signatureInformation.

In the LSP spec (as in JSON) there is a difference between a property being `null` and not present. When LSP started unnecessary properties are defined as `undefined`. Allowing `null` for them would be a breaking change for clients. This is why we stay with the approach that was taken at the beginning of LSP.

**Comment by zobo** [comment]
Hi @dbaeumer . Thanks for the feedback.

You are correct, in TypeScript `?` actually means optional, meaning JavaScript will give a `undefined` if looked up.

Since I'm working with PHP, this things are a bit different. I will work around it, thank you for clearing this up!
