### ISSUE TITLE
Smoke test failure: "verifies opened editors are restored"

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#152345]
See https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174571&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=5f0e9dbb-0df0-5bb0-f10b-78953999773d&l=71

**Comment by bpasero** [comment]
@deepak1556 again I find this in the logs:

```
[2022-06-16 14:59:28.735] [main] [error] CodeWindow: renderer process crashed (reason: killed, code: 15)
```

However unfortunately this time I see no crash dump produced...
