### ISSUE TITLE
Keyboard shortcut for `Format document` is inserting special character instead of formatting the document

### ISSUE THREAD

**Issue by jsjain** [microsoft/vscode#152360]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Darwin arm64 21.5.0
- Keyboard Input source: ABC / US/ US international => Have tried with multiple sources each time special character gets inserted.

Steps to Reproduce:

1. Press `shift + option + f` to format the document
2. Instead of document getting formatted, `Ï`   special character gets inserted.

Perviously I did not notice any such issue on my intel based Mac

**Comment by ArturoDent** [comment]
You should run the `Developer: Toggle Keyboards Shortcuts Troubleshooting` and see if that key combo is being used by some other command.

**Comment by jsjain** [comment]
Yes, found the issue had this command overriden in workspace settings.
```
  {
    "key": "shift+alt+f",
    "command": "-editor.action.formatDocument",
    "when": "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly && !inCompositeEditor"
  }
```

This was preventing from my doc getting formatted
