### ISSUE TITLE
Can not open file after opened folder

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#15241]
- VSCode Version: Code - Insiders 1.8.0-insider (6155c3cd1d983ba6029420d75400d8fcb132e588, 2016-11-09T07:12:28.915Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.0|
|tortoise-svn|fantasytyx|0.1.1|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.1|

---

Steps to Reproduce:

1. firstly,open any folder
2. open any file lonely ( not in VSCode )

The file can not be opened with VSCode.

https://github.com/ZCShou/Docs/blob/master/Errors/4.gif

**Comment by bpasero** [comment]
@ZCShou can you try with updating insiders to latest? I could reproduce once with your build, but not anymore. I think we fixed this yesterday 👍

**Comment by ZCShou** [comment]
@bpasero The latest works well,thanks!
