### ISSUE TITLE
Terminal: Letter clipping

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#152436]
Notice the `git` words in the following screenshot:

![image](https://user-images.githubusercontent.com/22350/174264475-b08a3b20-0791-4a7e-a449-39c038c1358a.png)

Does not reproduce in ca8a8376b46b63db7379cbcc827c75d92bf25e14, from 3 days ago.

---

I'm on Windows, using `CaskaydiaCove Nerd Font` as my font, default size, no zoom.

**Comment by Tyriar** [comment]
Caused by https://github.com/microsoft/vscode/pull/152347

**Comment by Tyriar** [comment]
https://github.com/xtermjs/xterm.js/pull/3866
