### ISSUE TITLE
Mouse wheel scroll deadzone on MacOS Sierra

### ISSUE THREAD

**Issue by ivancuric** [Microsoft/vscode#15240]
When using a 3rd party mouse with a scroll wheel, scrolling below the speed neccessary to accelerate to 1 line per tick or faster will not trigger scrolling.

In macOS scrolling at a speed below a certain treshold will use pseudo-per-pixel scrolling with acceleration eventually bumping it to 1 line per tick and faster, depending on the speed.

Using a 3rd party mouse driver such as SteerMouse and setting the scroll speed to a fixed 1 line / tick or higher fixes the issue.

This behaviour isn't exhibited in other Electron apps tested (Slack, Zeplin, Caprine, Discord) or in Google Chrome.

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0

**Comment by sp-1234** [comment]
This has nothing to do with vscode, this is Sierra bug (or maybe feature) that affects all applications.

**Comment by ivancuric** [comment]
Not here. This is me scrolling at a constant speed while moving the cursor between windows.
https://www.youtube.com/watch?v=lPKEPrbI8zI

**Comment by sp-1234** [comment]
@ivancuric this video is private, what's the point of posting it here?

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
