### ISSUE TITLE
Ctrl Shift P not working to show command pallete

### ISSUE THREAD

**Issue by markmycaliber** [microsoft/vscode#152448]
1. Hit Ctrl + Shift + P
2. Nothing happens

- Checked keyboard shortcuts: Show Command Pallete is configured for Ctrl + Shift + P
- No other commands use the same combination
- Searching for commands by recording keypresses does not record Ctrl + Shift + P at all
    > Ctrl + Shift is recognized
    > Ctrl + P is recognized
    > Shift + P is recognized

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `<key>`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by markmycaliber** [comment]
Hi there Alexandru!

Thanks for the response. Got the following output for Ctrl + Shift + P:

> [2022-06-18 13:12:08.611] [renderer1] [info] [KeybindingService]: /
> Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode:
> 17, key: Control
> [2022-06-18 13:12:08.612] [renderer1] [info] [KeybindingService]: |
> Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5
> ('Ctrl')
> [2022-06-18 13:12:08.612] [renderer1] [info] [KeybindingService]: \
> Keyboard event cannot be dispatched in keydown phase.
> [2022-06-18 13:12:08.654] [renderer1] [info] [KeybindingService]: /
> Received  keydown event - modifiers: [ctrl,shift], code: ShiftLeft,
> keyCode: 16, key: Shift
> [2022-06-18 13:12:08.655] [renderer1] [info] [KeybindingService]: |
> Converted keydown event - modifiers: [ctrl,shift], code: ShiftLeft,
> keyCode: 4 ('Shift')
> [2022-06-18 13:12:08.655] [renderer1] [info] [KeybindingService]: \
> Keyboard event cannot be dispatched in keydown phase.
> [2022-06-18 13:12:09.158] [renderer1] [info] [KeybindingService]: +
> Ignoring single modifier ctrl due to it being pressed together with other
> keys.
>

Seems like it cannot detect keydown for 'P'  for this combination.

As for Ctrl + P:

> [2022-06-18 13:13:11.569] [renderer1] [info] [KeybindingService]: /
> Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode:
> 17, key: Control
> [2022-06-18 13:13:11.569] [renderer1] [info] [KeybindingService]: |
> Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5
> ('Ctrl')
> [2022-06-18 13:13:11.569] [renderer1] [info] [KeybindingService]: \
> Keyboard event cannot be dispatched in keydown phase.
> [2022-06-18 13:13:11.857] [renderer1] [info] [KeybindingService]: /
> Received  keydown event - modifiers: [ctrl], code: KeyP, keyCode: 80,
> key: p
> [2022-06-18 13:13:11.857] [renderer1] [info] [KeybindingService]: |
> Converted keydown event - modifiers: [ctrl], code: KeyP, keyCode: 46 ('P')
> [2022-06-18 13:13:11.857] [renderer1] [info] [KeybindingService]: |
> Resolving ctrl+P
> [2022-06-18 13:13:11.857] [renderer1] [info] [KeybindingService]: \ From 2
> keybinding entries, matched workbench.action.quickOpen, when: no when
> condition, source: built-in.
> [2022-06-18 13:13:12.068] [renderer1] [info] [KeybindingService]: +
> Ignoring single modifier ctrl due to it being pressed together with other
> keys.
>

I hope you can help me with this one. This started happening just a few
days ago. Although I can still use F1 as an alternative, I'm really
accustomed to this.

Caleb

**Comment by jcford73** [comment]
Just had this problem. Troubleshooter showed vs code wasn't getting the keystroke, so something else was grabbing it. Seems it was the Razer Cortex app swallowing the keystroke. If you have that running, go to its settings and remap or unmap the CTRL-SHIFT-P key mapping

**Comment by adambirds** [comment]
I am also getting this issue, but I don't have this Razer Cortex app installed.

**Comment by adambirds** [comment]
I'm on Win 11, literally closed every app even in services and still an issue.

**Comment by alexdima** [comment]
Unfortunately, there is nothing we can do on our side if we don't receive the keybinding from OS. Most of the times, some other piece of software registers a global key listener and "steals" the keybinding.

**Comment by so1ve** [comment]
![](https://user-images.githubusercontent.com/58381667/176846164-3ef5260f-1313-4191-b200-c71d92a99a94.png)

Confirmed caused by Razer Cortex
