### ISSUE TITLE
windows git bash Ctrl-C doesn't terminate process

### ISSUE THREAD

**Issue by gregvis** [Microsoft/vscode#15249]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
2. Ctrl-C doesn't work for terminating a process (such as cordova run).

**Comment by Tyriar** [comment]
Moved upstream https://github.com/Tyriar/pty.js/issues/7
