### ISSUE TITLE
remote-ssh install vscode plugin in two computer will conflict

### ISSUE THREAD

**Issue by gland2015** [microsoft/vscode#152412]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.56
- OS Version: windows10

Steps to Reproduce:

1. ready a computer
2.use other computer remote ssh code it
3.ssh install pulgin `prettier`
4.use another again 2,3 step
5.you can find ssh `prettier` status is disabled  in other computer, unless reinstall

**Comment by gland2015** [comment]
> Thanks for creating this issue! It looks like you may be using an old version of VS Code, the latest stable release is 1.68.1. Please try upgrading to the latest version and checking whether this issue remains.
> 
> Happy Coding!

Obviously it will.

**Comment by sandy081** [comment]
Please try upgrading to the latest version and checking whether this issue remains.

**Comment by gland2015** [comment]
> Please try upgrading to the latest version and checking whether this issue remains.

Good, Disappeared after upgrade
