### ISSUE TITLE
The window has crashed (reason: 'crashed', code '-2147483645')

### ISSUE THREAD

**Issue by TheWyo** [microsoft/vscode#152482]
Issue Type: <b>Bug</b>

Having the same issue as #131714 with crashes (though I've never seen the crash at start up like mentioned there, just while working). I've manage to reproduce this with extensions disabled and within a relatively short time frame. I've only noticed this since the latest version, but it may just be down to what I was doing rather than any possible regression.

### Repro summary
I was skimming quite quickly through all the files of my TS codebase searching for stuff that I'd want to add to sideEffects in package.json, so possibly related to a lot of file switching quite quickly? Closest I can give to repro steps:

1. Launch VSCode (optionally with extensions disabled)
2. Start tasks for a local webserver and a webpack task in watch mode (not sure if these have any relevance but mentioning just in case)
3. Start clicking through files in the explorer (I was using the single click which opens the sort of 'preview' tab that's temporary and replaced if you single click another file).
4. Spend a few seconds skim reading that file, maybe folding some code blocks too
5. Move on to the next file
6. Repeat ad nauseam, when trying to repro I've generally had success in about 5-10 minutes.

Per https://github.com/microsoft/vscode/wiki/Native-Crash-Issues, here's a dump file for you as well:
[CrashDump.zip](https://github.com/microsoft/vscode/files/8928636/CrashDump.zip)

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700 @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (16.72GB free)|
|Process Argv|[ProjectDir] --crash-reporter-id 9ca2dd89-1db2-4c3c-9640-7411595ed984|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.2
gitlens|eam|12.1.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.25
vscode-todo-plus|fab|4.18.4
vscode-firefox-debug|fir|2.9.7
vscode-postfix-ts|ipa|1.10.0
svn-scm|joh|2.15.5
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.20
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.10.7
hexeditor|ms-|1.9.7
vsliveshare|ms-|1.0.5625
material-icon-theme|PKi|4.18.1
vscode-todo-highlight|way|1.0.5
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/153301
