### ISSUE TITLE
"protocol" is removed from "launch.json", but the official documentation still list it

### ISSUE THREAD

**Issue by jasonjiwork** [microsoft/vscode#152479]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Adding "protocol" configuration in launch.json, vscode warning: "Property protocol is not allowed".
2. https://code.visualstudio.com/docs/nodejs/nodejs-debugging, this document still mention it,  it doesn't even say clear which options it has.

**Comment by connor4312** [comment]
Updated the docs in the linked commit, thanks for pointing it out
