### ISSUE TITLE
in-window terminal not staying open

### ISSUE THREAD

**Issue by daniellercole** [microsoft/vscode#152487]
Issue Type: <b>Bug</b>

can't open terminal, it opens for a second then closes again

VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 36a94b93-e2f9-45ec-af84-3434726018a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
Bookmarks|ale|13.3.0
atlascode|atl|2.10.12
bracket-pair-colorizer|Coe|1.0.62
vscode-docker|ms-|1.22.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.18.1
vscode-commons|red|0.0.6
vscode-yaml|red|1.8.0
synthwave-vscode|Rob|0.1.11
gitblame|wad|8.2.3
material-theme|zhu|3.15.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by laurenyz** [comment]
I'm experiencing the same thing after updating today.

VS Code Version: 1.68.1
OS: Big Sur 11.6.4

`settings.json`:
```
{
    "files.autoSave": "afterDelay",
    "window.zoomLevel": 1,
    "editor.wordSeparators": "`~!@#$%^&*()=+[{]}\\|;:'\",.<>/?",
    "diffEditor.ignoreTrimWhitespace": false,
}
```

https://www.loom.com/share/0dc24b5fad72427ea0ae031da1e2799e

**Comment by meganrogge** [comment]
A trace log would be helpful https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging so I can see what's going on

**Comment by meganrogge** [comment]
Ok great. Pls open an issue w more info if you see it again
