### ISSUE TITLE
Intellisense, closing punctuation, and bracket matching stop working

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15248]
- VSCode Version: Code - Insiders 1.8.0-insider (ce6d57875ab53309204cf12dc54d74956221cfc1, 2016-11-09T08:41:36.673Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.3.7|
|sort-lines|Tyriar|1.1.0|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.1.15|
|vscode-eslint|dbaeumer|1.0.8|
|tslint|eg2|0.5.40|
|auto-close-tag|formulahendry|0.3.5|
|auto-rename-tag|formulahendry|0.0.8|
|Angular1|johnpapa|0.1.16|
|theme-karyfoundation-themes|karyfoundation|7.4.0|
|vscode-stylefmt|mrmlnc|2.0.1|
|nonbreakingspace|smlombardi|0.0.1|
|stylelint|shinnn|0.18.2|
|theme-tesla|smlombardi|0.0.1|
|autoimport|steoates|1.2.2|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. After using latest insider's build for  5-10 minutes, autocomplete (Intellisense) stops suggesting items.  In both HTML and SCSS files in workspace. No popup, nothing.
2. After this happens, html matching-bracket highlighting also ceases to function.
2. If I try to manually invoke it with ctrl-space, I get this:

![screen shot 2016-11-09 at 11 34 36 am](https://cloud.githubusercontent.com/assets/835148/20146114/a2d13aa2-a670-11e6-9f22-244b185ea3ab.jpg)

Eventually, the Intellisense panel appears and then everything works again.  This did not happen in previous builds.

![screen shot 2016-11-09 at 11 37 22 am](https://cloud.githubusercontent.com/assets/835148/20146199/f060a62c-a670-11e6-9542-c6c9b3b0e6d3.jpg)

**Comment by aeschli** [comment]
Can you see if the same thing happens without extensions? Start code with --disable-extensions to test this.

**Comment by ramya-rao-a** [comment]
@smlombardi Do you still see this with the latest insiders?

**Comment by smlombardi** [comment]
@ramya-rao-a  It hasn't recurred again yet.  I removed all extensions that did autocompletion as well.

**Comment by ramya-rao-a** [comment]
@smlombardi In that case, I'll close this issue for now. If you see this happening again, feel free to re-open this issue.
