### ISSUE TITLE
command center not appearing.

### ISSUE THREAD

**Issue by shekhars094** [microsoft/vscode#152405]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: macos 10.15

Steps to Reproduce:

if `"window.nativeTabs": true` then command center don't appear if the `"window.titleBarStyle": "custom",` is set to custom and experimental command center is also activated.

**Comment by jrieken** [comment]
Folding this into https://github.com/microsoft/vscode/issues/154422 which is about making the title bar part show under more condition
