### ISSUE TITLE
[Bug] Terminals can't be joined under certain circumstances

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#152476]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0-insider
- OS Version: Windows 10

Steps to Reproduce:

Two split terminals + one standalone terminal, select them all then join.

![STG 2022-06-17 22_21_15](https://user-images.githubusercontent.com/28700378/174317121-d0765b2d-9e8c-43d2-9757-33e705aa309c.gif)

**Comment by meganrogge** [comment]
this works now, must've been fixed

https://github.com/microsoft/vscode/assets/29464607/31ffa070-9bfe-41b1-82b7-2bbd4821c616

**Comment by wenfangdu** [comment]
@meganrogge I tried it in the latest insider build, still fails. Instead of selecting the terminal tabs one by one, can you try `ctrl/cmd+a` to select all, then join them?

https://github.com/microsoft/vscode/assets/28700378/41226cca-8b42-4763-be3f-3c3de2f67908
