### ISSUE TITLE
smoketest: VSCode Smoke Tests (Electron)        Terminal          Terminal splitCwd

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#152451]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=174719&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a671546b-2469-5fb1-b2c9-08e628dcad6d

**Comment by supremeQueen21** [comment]
Hi sorry to hear that you smoke test failed call  your council for smoke alarms checks

**Comment by Tyriar** [comment]
I guess it's not time to enable them for desktop/remote yet.

@supremeQueen21 thanks for the advice 👌
