### ISSUE TITLE
Format code doesn't work!

### ISSUE THREAD

**Issue by fbenvegna** [Microsoft/vscode#15243]
- VSCode Version: 1.7.1
- OS Version: Windows 7 Professional SP1

Steps to Reproduce:
I have a Node.js/Express/ExtJS large project with 19000 files and 3300 directory
1. create a new file on routes (or other) directory
2. insert few lines of unformatted code
3. format the code.... it's OK!
4. close and reopen VSCode
5. reopen the file
6. apply some change to the code
7. format the code.....  fails!!!!

No problem with vscode 1.6.
Now, it's impossible to format any existing file on project!

**Comment by aeschli** [comment]
What's the language of the file that you format? Does it matter what's the content of the file?

Also, can you list the extensions that you are using and also maybe try to run code without extensions?
Use  `code --disable-extensions` for that

**Comment by fbenvegna** [comment]
The language is JavaScript. It's a Node.JS / Express project.

**Comment by fbenvegna** [comment]
I tried `code --disable-extensions` but nothing is changed!

**Comment by fbenvegna** [comment]
I downgraded VSCode from 1.7.1 to 1.6.1 and formatting is OK!!!!
The problem is only on 1.7.X.
Please, correct the bug!

**Comment by lukaskj** [comment]
Same here. Angular project. After updating to 1.7.X formatting on javascript files stopped working

**Comment by waderyan** [comment]
@fbenvegna thank you for opening this issue. I cannot reproduce this on my end. Can you share your code?

**Comment by fbenvegna** [comment]
The project is very big. I'll try to compact and send a copy.

**Comment by fbenvegna** [comment]
After many trials, I found a solution to the problem... **jsconfig.json**.
If you delete the file... code formatting it's ok!
But I need **jsconfig.json**! 
In my case, I have to add the ExtJS directory ('public' on my project) to "exclude" section
`	
"exclude": [
		"node_modules",
		"public"
	]
`
Now, code formatting on 1.7.1 is OK!
I think that problem is related to Intellisense because another solution is to delete the ExtJS sources subdirectory and all is working.

**Comment by fbenvegna** [comment]
I created a very simple project as test case...
Download the zip file from [Google Drive link](https://drive.google.com/open?id=0B4t6DIuWG5JOV2FLZkpORC14RVU).
Try to format the file 'test-formatting.js'...

**Comment by waderyan** [comment]
@fbenvegna thank you for your thoroughness. Narrowing this down to a dependency with TypeScript language service (powers JavaScript and TypeScript). Migrating to that repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12178
