### ISSUE TITLE
Feature suggestion: Auto select the current word in "find in files" as it does in "find" 

### ISSUE THREAD

**Issue by mostergaard** [Microsoft/vscode#15244]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. In the code editor click "Ctrl+F" to find in the file without having any selection
2. The in-line search automatically searches for the word where the cursor is placed. If you already have a selection, that is used for the search, so this is only the case if you don't have a selection.
3. Try the same with the "find in files" (Ctrl+Shift+F) - the same "auto selection" of the current word is not applied here - you have to make a selection before opening the "find in files".

In Visual Studio both Find and Find In Files have the auto-selection behavior.

**Comment by roblourens** [comment]
#17974
