### ISSUE TITLE
Command to launch a specific tile in getting started for a particular extension is not working

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#152598]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.68.1 (user setup)
OS: Windows_NT x64 10.0.22518

Steps to Reproduce:

1. Here's a command link of jupyter opening a python walktrhough https://github.com/microsoft/vscode-jupyter/blob/main/package.json#L135, which does not open the mentioned tile.

This can also be observed when executing the command directly:

```typescript
vscode.commands.executeCommand(
    'workbench.action.openWalkthrough',
    { category: 'ms-python.python#pythonWelcome', step: 'ms-python.python#python.installPythonWin' },
    true,
);
```

Here're the instructions being used to call the command: https://github.com/microsoft/vscode/issues/119725#issuecomment-1159304113

cc/ @lramos15

**Comment by karrtikr** [comment]
Instead of opening a new tab with the tile, it would be great if we can reveal the tile in focus.

**Comment by lramos15** [comment]
Looks like this is possible with `'walkthroughs.selectStep'` and just passing the step portion i.e. `python.installPythonWin` but I have added a PR to allow for using `openWalkthrough` to either open it if it's not open and if it is to reveal them

**Comment by lramos15** [comment]
@karrtikr Please verify that `openWalkthrough` and `walkthroughs.selectSteps` works as expected now for you

**Comment by karrtikr** [comment]
Yep `walkthroughs.selectSteps` does the job when the walkthrough is opened. Is there a way to test out `openWalkthrough` as the fix hasn't been released yet?

**Comment by lramos15** [comment]
> Yep `walkthroughs.selectSteps` does the job when the walkthrough is opened. Is there a way to test out `openWalkthrough` as the fix hasn't been released yet?

There is not please try it tomorrow 👍
