### ISSUE TITLE
No path suggestions inside of angle bracet markdown link

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#152510]
Issue Type: <b>Bug</b>

Trigger path suggestions inside a markdown link that uses angle brackets:

```md
[text](<|>)
```

**Bug**
No suggestions show up

VS Code version: Code - Insiders 1.69.0-insider (Universal) (fbf1cf3832d43088e27837dbb68d24ab65a098c1, 2022-06-17T05:16:27.373Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.01GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Relevant code:

https://github.com/microsoft/vscode/blob/623f55f437ab31fa56e13acafa9b9e7d4b50c4bf/extensions/markdown-language-features/src/languageFeatures/pathCompletions.ts#L161

**Comment by DASchechtman** [comment]
So I'm new to this project. Do I ask if I can be assigned this bug? Or is it whoever submits an solution first makes the pull request?

**Comment by Harry-Hopkinson** [comment]
You can ask, I am currently working on this now - but you can try as well.

**Comment by DASchechtman** [comment]
Alright thanks. So in general I can just work on a problem that catches my attention and ask/answer questions when appropriate?

**Comment by Harry-Hopkinson** [comment]
Yes pretty much, you can work on any problem or issue that you would like.

**Comment by DASchechtman** [comment]
What specifically is the bug here? Is the desired behavior where when you type ```[text](<|>)``` a list of path links should appear?

**Comment by mjbvz** [comment]
Yes, it should work the same way it does if you remove the `<>` from the link

One extra: spaces should not be encoded inside `<>` links so for extra points make accepting a file suggestion with spaces in the name  inserts a real space instead of `%20`

**Comment by DASchechtman** [comment]
Is this the behavior you were looking for?
[link to screen recording](https://drive.google.com/file/d/1flfHACY3hE9K6MI-YIYZ8ZqtJCl29m0u/view?usp=sharing)
