### ISSUE TITLE
Interactive window scrolls after execute test is slow

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#152539]
This test takes 30 seconds for me when running locally 😱 .

![image](https://user-images.githubusercontent.com/900690/174423834-5a56e634-438e-4fc3-949b-8cb4cc6715e3.png)

**Comment by rchiodo** [comment]
Not sure why it takes you so long? It takes 6 seconds for me.

![image](https://user-images.githubusercontent.com/19672699/174859448-d24bb2b0-b285-4bfc-a0c6-751538018b20.png)

The test has to execute a number of cells to make sure the output scrolls off the screen. Right now that number is 20. Executing 10 cells is probably enough on most screens, but it's still going to take a bit.

**Comment by bpasero** [comment]
I think we should understand why execution time seems to get slower and slower the more cells there are. Check out this video, it looks as if things get slower and slower:

![Recording 2022-06-22 at 10 18 58](https://user-images.githubusercontent.com/900690/174980047-4b83e69b-9f7a-45d0-b167-aa0a268b76df.gif)

**Comment by bpasero** [comment]
Yeah, execution slows down, waiting for results.

**Comment by rchiodo** [comment]
Closing in favor of new issue.
