### ISSUE TITLE
Server seems to no longer shutdown in smoke tests sometimes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#152541]
Noticed a flaky web remote smoke test run:

```
  1) VSCode Smoke Tests (Web)
       Search
         "before all" hook for "searches for body & checks for correct result number":
     Error: [14:17:38] Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1520:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8000
}
```

Then diagnostics printed after shows this:

```
buildus+  1194     1  0 14:17 ?        00:00:00 sh /__w/1/vscode-reh-web-linux-x64/bin/code-server-oss --disable-telemetry --disable-workspace-trust --port9001 --enable-smoke-test-driver --extensions-dir=/tmp/vscsmoke/extensions-dir --server-data-dir=/tmp/vscsmoke/d-ho6qvz9k --accept-server-license-terms --logsPath=/__w/1/s/.build/logs/smoke-tests-browser/2_suite_Search
buildus+  1198  1194  0 14:17 ?        00:00:00 /__w/1/vscode-reh-web-linux-x64/node /__w/1/vscode-reh-web-linux-x64/out/server-main.js --disable-telemetry --disable-workspace-trust --port9001 --enable-smoke-test-driver --extensions-dir=/tmp/vscsmoke/extensions-dir --server-data-dir=/tmp/vscsmoke/d-ho6qvz9k --accept-server-license-terms --logsPath=/__w/1/s/.build/logs/smoke-tests-browser/2_suite_Search
buildus+  1209  1198  0 14:17 ?        00:00:00 /__w/1/vscode-reh-web-linux-x64/node /__w/1/vscode-reh-web-linux-x64/out/bootstrap-fork --type=ptyHost --logsPath /__w/1/s/.build/logs/smoke-tests-browser/2_suite_Search
```

Build: https://dev.azure.com/vscode/VSCode/_build/results?buildId=66327&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=122b2952-2cd2-5cd8-5590-35b99fa6e4d0

I think @Tyriar saw something similar.

Did anything change with the server and how it shuts down?

The server logs print MBs of this data:

```
[2022-06-17 14:19:50.880] [remoteagent] [error] Error: Unexpected SIGPIPE
    at process.<anonymous> (/__w/1/vscode-reh-web-linux-x64/out/vs/server/node/server.main.js:145:7926)
    at process.emit (node:events:390:28)
```

Full logs:

https://artprodcus3.artifacts.visualstudio.com/A56a7ea80-d977-493c-a5f1-30001999cd01/a4cdce18-a05c-4bb8-9476-5d07e63bfd76/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3ZzY29kZS9wcm9qZWN0SWQvYTRjZGNlMTgtYTA1Yy00YmI4LTk0NzYtNWQwN2U2M2JmZDc2L2J1aWxkSWQvNjYzMjcvYXJ0aWZhY3ROYW1lL2xvZ3MtbGludXgteDY0LXNtb2tlLTE1/content?format=zip&subPath=%2Fsmoke-tests-browser

**Comment by alexdima** [comment]
@bpasero Looking at the left-over process:
> `buildus+  1198  1194  0 14:17 ?        00:00:00 /__w/1/vscode-reh-web-linux-x64/node /__w/1/vscode-reh-web-linux-x64/out/server-main.js --disable-telemetry --disable-workspace-trust --port9001 --enable-smoke-test-driver --extensions-dir=/tmp/vscsmoke/extensions-dir --server-data-dir=/tmp/vscsmoke/d-ho6qvz9k --accept-server-license-terms --logsPath=/__w/1/s/.build/logs/smoke-tests-browser/2_suite_Search`

I notice that the server is spawned with the argument `--port9001`. From my local testing, I don't think this argument gets interpreted in any way. Note how the server starts on port 8000:
> <img width="988" alt="image" src="https://user-images.githubusercontent.com/5047891/174549585-1b68a8e1-c31d-45d4-a793-6564c4e318bd.png">

The server in the test also appears to want to start on port 8000:
```
[2022-06-17 14:17:38.626] [remoteagent] [error] Error: listen EADDRINUSE: address already in use 127.0.0.1:8000
    at Server.setupListenHandle [as _listen2] (node:net:1334:16)
    at listenInCluster (node:net:1382:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1520:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:73:8)
```

I think this might be caused by a missing `=` over here: https://github.com/microsoft/vscode/blob/4c72dedb4ad283a569f83a7389468c3ae2c642c3/test/automation/src/playwrightBrowser.ts#L47

**Comment by bpasero** [comment]
Yeah we do:

https://github.com/microsoft/vscode/blob/4c72dedb4ad283a569f83a7389468c3ae2c642c3/test/smoke/src/utils.ts#L114-L125

This is also relatively new, we have been running with this code for months now and only now I start to see this issue, but your fix will help nevertheless.
