### ISSUE TITLE
update deletes files

### ISSUE THREAD

**Issue by talminator2856791** [microsoft/vscode#152581]
Issue Type: <b>Bug</b>

i saved all my stuff in C:\Users\user\AppData\Local\Programs\Microsoft VS Code path whenever i worked with visual studio code. recently when i opened visual studio code it said there is an update and i clicked the update button. so visual studio code updated and i went to C:\Users\user\AppData\Local\Programs\Microsoft VS Code path and couldnt find any of my files or folders from before. did visual studio code delete all my work or does it still exist somewhere? even when i search for the names of some of those folders in "search this pc" in file explorer, file explorer finds the folders, but they are empty (i assume because it shows the size is only roughly 1 kb) and when i click on the folder it says path doesnt exist, which i thought was weird because it shows the path under the name and its not even the same path the folder was at before i updated visual studio code. what can i do to retrieve all the lost files and folders?

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.44GB free)|
|Process Argv|--crash-reporter-id f3d71148-c814-4292-b935-436cac5c5a21|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
batch-rename-extension|Jan|0.0.5
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.20
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
batch-runner|Nil|0.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment]
See #138815

I don't know if there is any way to recover your code.
