### ISSUE TITLE
Markdown Preview failure

### ISSUE THREAD

**Issue by JimiC** [Microsoft/vscode#15257]
- VSCode Version: 1.8.0-insider ce6d578 (2016-11-09T08:48:03.700Z)
- OS Version: Windows 10 (1607)

Steps to Reproduce:

1. Open a markdown file
2. Open Preview
3. Get error/warn `command 'markdown.showPreview' not found`

Bug or feature?

**Comment by eriktrom** [comment]
Same here: (Same steps to reproduce)

Error: `command 'markdown.showPreview' not found`

VSCode version: Version 1.8.0-insider (1.8.0-insider)
OS Version: macOS Sierra 10.12.1 (16B2555)



Hope its a bug not a feature :)

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/15184
