### ISSUE TITLE
Keyboard navigation in sidebar: jump to letter

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#15251]
A nice usability feature of select menus in browsers is, once focussed, you can start typing the name of an entry and the browser will select any matches. E.g, if I had options "foo", "bar", "baz", and I typed "ba" when the select is focussed, the browser would select "bar" for me.

It would be great to have the same accessibility feature in the sidebar.

**Comment by hesher** [comment]
+1
