### ISSUE TITLE
The manage workspace trust tab icon seems large/misaligned

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152509]
Not much padding between it and the word:

![image](https://user-images.githubusercontent.com/2193314/174387501-3873ae53-b4b4-4010-99c2-020656400f60.png)
![image](https://user-images.githubusercontent.com/2193314/174387552-8e007104-c746-4b11-96a8-3d593a184818.png)

**Comment by misolori** [comment]
Passing to @aeschli as this is a file icon but in the icon we actually have it designed at 14px scale and i know the file icons use different scaling styles

<img width="568" alt="CleanShot 2022-06-17 at 12 33 56@2x" src="https://user-images.githubusercontent.com/35271042/174390529-b6ec0dcc-ea0b-4075-a93e-5c61dfb8c3d1.png">
