### ISSUE TITLE
Editor scrolls downwards as I'm typing

### ISSUE THREAD

**Issue by Sidneys1** [Microsoft/vscode#15250]
- VSCode Version: Code - Insiders 1.8.0-insider (ce6d57875ab53309204cf12dc54d74956221cfc1, 2016-11-09T08:48:03.700Z)
- OS Version: Windows_NT ia32 10.0.14959
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|vscode-color|anseki|0.2.1|
|vscode-icontheme-nomo-dark|be5invis|1.1.5|
|gitignore|codezombiech|0.3.1|
|python|donjayamanne|0.5.1|
|gitlens|eamodio|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|flatbuffers|gaborv|0.1.0|
|beautify|HookyQR|0.5.4|
|nsis|idleberg|2.0.1|
|gitignore|michelemelluso|1.0.1|
|vscode-todo-parser|minhthai|1.8.3|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|resharper9-keybindings|ms-vscode|1.1.0|
|peep|nwallace|0.0.5|
|vscode-json-transform|octref|0.1.2|
|material-icon-theme|PKief|1.1.3|
|seti-icons|qinjia|0.1.3|
|annotator|ryu1kn|0.10.1|
|Spell|seanmcbreen|0.8.6|
|json-schema-validator|tberman|0.1.0|
|gitblame|waderyan|1.3.0|
|joinlines|webdokkeren|1.1.1|

---

Steps to Reproduce:

1. Open a file with multiple lines.
2. Insert the cursor in the top third or so of the document
3. Begin typing
4. The window should scroll downwards as you type, seemingly randomly.

**Comment by alexandrudima** [comment]
@Sidneys1 I cannot reproduce this

Does the issue still occur when you launch VS Code w/ extensions disabled? From the command line: `code --disable-extensions`

**Comment by Sidneys1** [comment]
The issue was resolved for me a few days after the initial issue; sorry for not updating the ticket!
