### ISSUE TITLE
Stop resetting default apps.

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#15252]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Install VS Code
2. Observe that it becomes the default for many file types without even asking.

**Comment by waynebloss** [comment]
This is going to be the final fucking straw for me that is going to make me move away from Windows. Sorry to be venting here, but this is fucking ridiculous. I should only have to set my DEFAULT FUCKING APPS ONCE!

**Comment by waynebloss** [comment]
The reason I'm not sure if this is a VSCode problem or a Windows 10 problem is because of the fact that I just installed VSCode the other day, but then there was also an update for Windows 10 yesterday. Today is when I started getting the "Always Open With" dialog when I went to open a file `(*.less, *.jade, *.css, *.js, *.xml, etc...)` that defaults to my Notepad replacement (Sublime Text).

I replace Notepad.exe with the [Notepad Replacer](https://www.binaryfortress.com/NotepadReplacer/)

Usually I use the full Visual Studio to work on my projects. I can't be sure if it was happening before Tuesday but after the VSCode install or not.

I don't know how default apps work in Windows 10, but perhaps it shows you that dialog now whenever you install a new app that can handle that file type? I'd really love to know what causes this because it it supremely annoying to have all your defaults reset.

**Comment by joaomoreno** [comment]
This is Windows 10.

**Comment by waynebloss** [comment]
@joaomoreno OK, I shall test that theory out then. I'm going to install VSCode on another Win10 machine and see what happens to my default settings for opening all the file types that I mentioned.

**Comment by waynebloss** [comment]
Test completed.

When installing VSCode, if I leave the checkbox checked for `Register as an editor for all supported file types` then Windows 10 will prompt me for every file type.

VSCode is responsible for leaving that checkbox checked by default without any warning about the SUPER annoying consequences. So, I will open a separate issue about that.
