### ISSUE TITLE
File changes watcher stopped unexpectedly. 

### ISSUE THREAD

**Issue by newbenji** [microsoft/vscode#152537]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: Windows_NT x64 10.0.22000
- WSL2: Linux benji 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:

1. Start visual code from wsl2 in the code path with command "code ."
2. It is not releasing the shell back 
3. The notification comes with file changes watcher stopped unexpectedly.. 
4. Tested with disable extensions same problem.
5. 
Errors from console
![image](https://user-images.githubusercontent.com/4226432/174423206-dd9c0479-0a88-4a7c-a1a4-6a6ced4bb920.png)

**Comment by aeschli** [comment]
You are opening VS Code on `\\ws.localhost\Ubuntu\..` which is a mount offered by WSL and doesn't seem to behave like other mounts. We have reported it against WSL as https://github.com/microsoft/WSL/issues/7674.

@newbenji The best way to open a WSL folder is using the `Remote-WSL` extension.
Install the extension, open a WSL terminal (e.g. Ubuntu), navigate to the folder you want to work on, and start `code` from there. This will open a Remote WSL window, where the VS Code backend runs in Lunix.
