### ISSUE TITLE
Official Linux AppImage

### ISSUE THREAD

**Issue by malkawimahdi** [microsoft/vscode#152574]
Possibly, a VSCode AppImage, for other Distros' that aren't Debian or Fedora based. As currently the only option for VSCode on unsupported distros', is by 3rd partys.

**Comment by relimS** [comment]
> Possibly, a VSCode AppImage, for other Distros' that aren't Debian or Fedora based. As currently the only option for VSCode on unsupported distros', is by 3rd partys.

![image](https://user-images.githubusercontent.com/66686057/174475165-25c37dfa-2102-4faa-8705-145f1ecf1936.png)

Do you need new pair of glasses?

If you want an AppImage, you can use [AppImageKit](https://github.com/AppImage/AppImageKit) to make one, you just need to extract the tarball, write a simple .desktop file in the VSCode-linux-<architecture> directory and execute AppImageKit specifying the executable code (VSCode executable) as runtime file to use
