### ISSUE TITLE
Using Windows 7 taskbar popup menu to open recent folder name containing spaces fails probably due to lack of quoting

### ISSUE THREAD

**Issue by mikecopperwhite** [Microsoft/vscode#15254]
- VSCode Version: 1.7.1 
- OS Version: Windows 7 x64 Professional N SP 1

Steps to Reproduce:

1. Create a folder containing a space in the name (e.g. "c:\temp\Test Folder")
2. Navigate to that folder in Windows Explorer
3. Right click in explorer to open that folder in VSCode
4. Close VSCode
5. Right click on VSCode icon on taskbar (created by pinning VSCode to taskbar but problem happens from non-pinned icon too).
6. From recent folders select c:\temp\Test Folder (no " characters shown in menu)
7. Instead of opening the folder VSCode opens 2 new files - c:\temp\Test and c:\Windows\system32\Folder

Same problem doesn't happen if:
1. selecting files with spaces in name using taskbar popup menu
2. selecting folder from File/Open Recent... menu inside VSCode
3. selecting folder names without spaces from taskbar popup menu

**Comment by mikecopperwhite** [comment]
Using --disable-extensions command line option doesn't fix the problem

**Comment by bpasero** [comment]
Thanks, I found this issue already and pushed a fix to insiders. 
You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders
