### ISSUE TITLE
Settings Sync should perform a basic cross-platform translation

### ISSUE THREAD

**Issue by runxel** [microsoft/vscode#152567]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1 (Universal)
- OS Version: Mac OS 12.4 "Monterey" / Darwin arm64 21.5.0

Settings Sync is an ingenius thing.  
However it falls short in one regard: Imagine you're happen to either switch systems (i.e. from Win to Mac) for once, or you happen to have different systems at hand (e.g. different work stations) which differ in their OS.  
Sync will fail to properly reuse the carefully defined shortcuts and just use the default.
From a user perspective this is bad. I expected to have all my shortcuts work, which was not the case.

I think there are some different ways to handle this:
- Settings Sync could ask to auto "translate" the keyboard shortcuts (so control would become command ⌘, etc.)
- There could be a dedicated command: "Please translate the shortcuts as good as you can"
- Both above.
- User made "translation" settings, where the user can define what e.g. "command" means.
- ... probably you'll have even better ideas for this.

Of course there must be some safeguard system in place for those circumstances where the shortcuts shall deliberately be different. BUT, and this is a big But, I still think that people out there would rather have their settings actually in sync, and not have to many differences between different OS's.

**Comment by sandy081** [comment]
Please check the setting `settingsSync.keybindingsPerPlatform` to avoid synchronising keyboard shortcuts across platforms.

**Comment by sandy081** [comment]
> this checkbox is ticked for me.

It means keyboard shortcuts are synced per platform. Mac shortcuts are synced only to Mac machines and same for Windows machine. 

We do not auto convert keyboard shortcuts say, changing from CTRL to CMD or vice versa.

Please refer to this issue for OS specific keybindings - https://github.com/microsoft/vscode/issues/8962
