### ISSUE TITLE
Minimized screen gets glitch when using it

### ISSUE THREAD

**Issue by 413UG** [microsoft/vscode#152524]
It happens while scrolling in another windows when Visual studio code is minimized o at least half screen is showing. 
![Captura de pantalla 2022-06-17 163112](https://user-images.githubusercontent.com/84651043/174408962-bab156d4-2515-4579-bac9-b661fb378eb1.jpg)

**Comment by deepak1556** [comment]
Please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Merging to https://github.com/microsoft/vscode/issues/124226
