### ISSUE TITLE
Add ability to lock in settings

### ISSUE THREAD

**Issue by adam-becker** [microsoft/vscode#152508]
I would love the ability to lock in my settings, and opt out of any new functionality. Frequently, I update VS Code and see that the editor is now different and not how I want it. I then have to hunt down the offending configuration setting(s) and turn them off, this has gotten frustrating enough that I am now opening an issue for it.

I have VS Code configured exactly how I want it, and new features being enabled by default is not ideal. I assume I'm not the only one that wants to opt out of new features that disturb our workflow or cause the editor to behave differently. The assumption that everyone will want these new features, or that it's "easy enough to disable" is becoming more and more unacceptable to me. I love VS Code, but enough is enough.

**Comment by rzhao271** [comment]
I understand how annoying changing default values and new features can be at times, but I don't believe that we can easily align our current development approach with your ask, so I'm marking this as out-of-scope.

The easiest mitigation is to switch the update mode to manual or off. A better mitigation could be to export the default settings file from an earlier version and merge that with your current user settings, but that doesn't help guard against new features, nor does it help with settings whose name or schema has changed.

**Comment by rzhao271** [comment]
Related: https://github.com/microsoft/vscode/issues/158144
