### ISSUE TITLE
Allow deleting watch entries with a single click

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152642]
I was an `x` on watch like there is on breakpoints.

![Recording 2022-06-19 at 09 40 34](https://user-images.githubusercontent.com/2193314/174610900-dea4937a-fc0d-4e79-afa9-5dcf2852b500.gif)

I notice that devtools has a `x` button on hover:

![image](https://user-images.githubusercontent.com/2193314/174610915-026086ae-b820-47d7-8e2d-30c5e0f42d9b.png)

**Comment by babakks** [comment]
@roblourens I take this if it's okay.

**Comment by roblourens** [comment]
I think you can copy the way this method override works in the variables tree: https://github.com/microsoft/vscode/blob/bbe7b54cf4ded1528b343789989a747450e08c6d/src/vs/workbench/contrib/debug/browser/variablesView.ts#L440

to the watch tree renderer: https://github.com/microsoft/vscode/blob/bbe7b54cf4ded1528b343789989a747450e08c6d/src/vs/workbench/contrib/debug/browser/watchExpressionsView.ts#L267

The actionbar doesn't show any actions in the variables view by default - the builtin actions only show up in the context menu. Maybe some extension contributes something to that actionbar. But in any case, looks like the `AbstractExpressionsRenderer` has the ability to render an actionbar already.

**Comment by babakks** [comment]
@roblourens Thanks for the hint. I've just submitted the PR. Could you please check it?
