### ISSUE TITLE
Raw string's scope error

### ISSUE THREAD

**Issue by Binaryify** [microsoft/vscode#152698]
## Environment data

Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

## Code Snippet

```python
import re

from cv2 import imread

img = imread(r"paper\cell_b.png")

print(r'paper\cell_b.png' == 'paper\\cell_b.png')
```
![image](https://user-images.githubusercontent.com/12221718/174427988-b202906d-d6bb-4cd1-94b9-1ec81052ce03.png)

`r'paper\cell_b.png' == 'paper\\cell_b.png'` is evaluated as True in Python.
Raw string has "r" before it, and it means string without backslash escape in Python. It's especially useful for handling paths in Windows.

the origin issue: https://github.com/Binaryify/OneDark-Pro/issues/749

**Comment by alexr00** [comment]
@Binaryify and @erictraut I am not a frequent Python user, so please correct me if I've misunderstood something, but I think this is a feature: https://github.com/MagicStack/MagicPython/issues/114#issuecomment-349115524 (that's the repo that VS Code pulls our Python syntax highlighting grammar from.

**Comment by Binaryify** [comment]
@Haoyu-UT

**Comment by Haoyu-UT** [comment]
@alexr00 Thank you for your comment. I now come to understand that for vscode (and MagicPython) r and R are interpreted differently. I'm sorry for my ignorance.
@Binaryify Thank you for your support. Please kindly close the original issue.
