### ISSUE TITLE
Testing: Space after codicon at start of label gets dropped

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#152630]
Testing #151613 in current Insiders.

Loss of space character originally reported at https://github.com/microsoft/vscode/issues/141271#issuecomment-1155884794 by @jdneo with screenshot 👍 

Verified by me. Opening this issue for better tracking.

/assign @connor4312

**Comment by jdneo** [comment]
Hi @connor4312 @gjsjohnmurray 

I found that in 1.69.0, it's still `nowrap` style for the label - the whitespace is still losing.

**Comment by jdneo** [comment]
Ok. I guess maybe it's because different codicons has different size?

![image](https://user-images.githubusercontent.com/6193897/178634138-857d5ff9-1bdd-4093-8723-be0b1ce0f71a.png)

At the top you can see, the character `j` looks very close to the square. Not a big issue though.

**Comment by connor4312** [comment]
Yea, I think just different sizes. We now have the label be flex and use its `gap`. Text alignment on the web is always fun...
