### ISSUE TITLE
Tag matching erratic in JSX javascript

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#15264]
- VSCode Version:
- OS Version:

From @vvatikiotis:
https://github.com/Microsoft/vscode/issues/12402#issuecomment-259362863

Steps to Reproduce:

HTML tag matching works in my theme, highlighting matching tags, _when there are no JSX javascript expressions within the tags_. However, tag highlighting works erratically when there are JSX javascript expressions within 2 enclosing HTML tags.

Works as intended:
![image](https://cloud.githubusercontent.com/assets/535853/20132214/877d6024-a66a-11e6-9a04-a1a4be5206a9.png)

Doesn't work:
![image](https://cloud.githubusercontent.com/assets/535853/20132234/9f3d0f20-a66a-11e6-8c2e-377addd5f347.png)

**Comment by waderyan** [comment]
@dbaeumer is matching tags provided by a language service (i.e. TS Server)? I can't see anything in the doc - http://code.visualstudio.com/docs/extensions/language-support

**Comment by dbaeumer** [comment]
Yes, the TS request message is called `occurrences`

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12271
