### ISSUE TITLE
add a command to hide/show file explorer using gitignore

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#152696]
there is a setting to hide ignore files. but it is inconvenience.

`explorer.excludeGitIgnore`

**Comment by gjsjohnmurray** [comment]
Maybe you are seeing #152543 which got fixed today. Please re-test when Tuesday's Insiders appears.

**Comment by heartacker** [comment]
What I mean is that I don't want to change the setting and then I can show or hide the files.

**Comment by heartacker** [comment]
> You can make an extension which registers a command which toggles the setting if you want to just toggle it on and off

no， This feature should not change the setting.  Otherwise, the scm tracking will find that the setting file changed in workspace or sync to user profile in user_setting😳
