### ISSUE TITLE
Descenders in Insiders terminal are being cut off

### ISSUE THREAD

**Issue by wardy3** [microsoft/vscode#152612]
Issue Type: <b>Bug</b>

I removed my settings.json from my `~/Library/Application\ Support/Code\ -\ Insiders/User/` and `~/Library/Application\ Support/Code/User/` folders so I know this isn't a setting error I've made 

I also started Insiders with `—disable-extensions`

VSCode:
```Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0
```

VSCode Insiders:
```Version: 1.69.0-insider (Universal)
Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1
Date: 2022-06-17T05:16:27.373Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

Then, comparing Code and Code Insiders, I can see the descenders ("g", "y", etc) are being cut off on Insiders, but not on Code

VS Code version: Code - Insiders 1.69.0-insider (Universal) (fbf1cf3832d43088e27837dbb68d24ab65a098c1, 2022-06-17T05:16:27.373Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (0.79GB free)|
|Process Argv|--disable-extensions --crash-reporter-id e45c21e3-3270-4be4-bf1b-d02853448a5e|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912cf:30496797
vsclangdf:30492506

```

</details>

**Comment by wardy3** [comment]
Insiders:
![image](https://user-images.githubusercontent.com/15006782/174526191-73402451-6ec4-4a90-8562-a2cdbaaf2f37.png)

VSCode:
![image](https://user-images.githubusercontent.com/15006782/174526241-bda6351c-4def-4dd8-a4f5-8934c0b29bf7.png)

**Comment by meganrogge** [comment]
fixed in today's insider's
