### ISSUE TITLE
tslint in ghooks coverage should be increased

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15263]
It appears that there is an implicit expectation that the tslint extension is used for the codebase, we should increase coverage of the tslint filter in ghooks to cover all cases we want as not all contributors will use the extension.

```js
const tslintFilter = [
	'src/**/*.ts',
	'extensions/**/*.ts',
	'!**/*.d.ts',
	'!**/typings/**',
	'!src/vs/base/**/*.test.ts', // < Why is this here?
	'!extensions/typescript/test/colorize-fixtures/**', // < Why is this here?
	'!extensions/vscode-api-tests/testWorkspace/**',
	'!src/vs/workbench/**/*.test.ts', // < Why is this here?
	'!extensions/**/*.test.ts' // < Why is this here?
];
```

I also suggest that in the future any exceptions to the rules have comments with the reasoning behind the decision.

Related fix for filters not being restored https://github.com/Microsoft/vscode/pull/15259

**Comment by joaomoreno** [comment]
Long story short: no one cares about linting tests. That was the overall opinion when tslint was introduced into the project.

@Microsoft/vscode

**Comment by alexandrudima** [comment]
@joaomoreno @jrieken I'd like for code in `vs/editor/test` to get linted, formatted, etc, i.e. apply all the rules of `vs/editor/common` to it. What do I need to do?

**Comment by joaomoreno** [comment]
@alexandrudima They are already under hygiene: d5e8fcf
