### ISSUE TITLE
newWithProfile doesn't support contributed terminal profiles

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152635]
Repro:

1. Add this keybinding `{ "key": "ctrl+alt+`", "command": "workbench.action.terminal.newWithProfile", "args": { "profileName": "JavaScript Debug Terminal" } }`
2. Hit ctrl+alt+`

![image](https://user-images.githubusercontent.com/2193314/174608567-58d76640-2b68-439d-94f2-454aea98ce00.png)

![image](https://user-images.githubusercontent.com/2193314/174608575-7a92dda1-722a-4dc5-b467-39b5dcdc8965.png)

![image](https://user-images.githubusercontent.com/2193314/174608587-d908cf9e-ed15-4bbf-8ffc-121738471887.png)

Version: 1.69.0-insider (user setup)
Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1
Date: 2022-06-17T05:16:33.731Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by meganrogge** [comment]
I haven't seen any requests for this or other reports, think we should close
