### ISSUE TITLE
Consider introducing ctrl+q to close all windows on Linux and Window to compliment hot exit

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15261]
Atom and Sublime both have this keybinding by default. I suggest we switch this on once hot exit is enabled by default.

@Microsoft/vscode any objections?

**Comment by bpasero** [comment]
I don't mind having it independent from hot exit, why would it be related?

**Comment by Tyriar** [comment]
Yeah no reason really.

**Comment by bpasero** [comment]
@Tyriar I pushed this, though did not assign `Ctrl+Q` on Windows because I could not find that to be the default. I am seeing some programs assigning `Alt+F4` but seems to be for closing a Windows, not quitting the app. I see Chrome assigns `Ctrl+Shift+Q` to exit, but that seems random too.

**Comment by Tyriar** [comment]
> `win: { primary: KeyMod.Alt | KeyCode.F4 }`

alt+f4 on windows needs to close the window, not all windows. This is a bug imo.

**Comment by bpasero** [comment]
@Tyriar yeah not my intent to push the keybinding for Windows, was an oversight. Feel free to remove it for Windows.

**Comment by bpasero** [comment]
Ah, I fixed that already right after: https://github.com/Microsoft/vscode/commit/77b44f3c5d6656d758f53f16d84a0f23637faa34

**Comment by Tyriar** [comment]
Great :smile:
