### ISSUE TITLE
Debug hover throws when trying to view buffer

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152636]
First notice in the gif how hovering will only let me hover over the info for the `originalData` variable, not `decodedPng` which I actually want (https://github.com/microsoft/vscode/issues/151019)

For this issue I click the `buffer` eye symbol and it throws a TreeError:

![Recording 2022-06-19 at 06 54 38](https://user-images.githubusercontent.com/2193314/174608759-ff39b78f-6cc5-46d6-83ce-7fdf4622fbb7.gif)

Here it is happening again without the hover problem:

![Recording 2022-06-19 at 06 59 21](https://user-images.githubusercontent.com/2193314/174608833-f0a50e28-2afd-4901-a1a2-e3aa29ee2357.gif)

Version: 1.69.0-insider (user setup)
Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1
Date: 2022-06-17T05:16:33.731Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by connor4312** [comment]
I tried to repro this yesterday, but was unsuccessful 😞 

@Tyriar have you still seen this and, if so, can you share a link to locations where you do?

**Comment by Tyriar** [comment]
Don't think I've seen since
