### ISSUE TITLE
Terminal quick pick shows unexpected terminal numbering

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#152697]
- VS Code Version: stable and from sources

Terminals within a terminal group of size 1 should not show a subindex like the terminal in the first group 

![image](https://user-images.githubusercontent.com/25115070/174709921-0f9b70d8-6481-4d23-becf-82045ab03349.png)

**Comment by ramanand-rv** [comment]
Hey @jeanp413 can I work in this issue if it's still open ?

**Comment by jeanp413** [comment]
Sorry @ramanand-rv but I already fixed it in this PR https://github.com/microsoft/vscode/pull/152699
