### ISSUE TITLE
UI: Add dock for switching viewlets/panels

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15262]
#1105  - Provide an option to hide the activity bar currently has 79 upvotes. 

Per today's discussion in UX meeting #15217, I came up with this idea:

(Ignore the blank part on the right, just a quick hack to get the idea across)

![dock](https://cloud.githubusercontent.com/assets/4033249/20151049/86d0f020-a66d-11e6-9f20-74ab987ac37d.png)

It'll work similarly to Windows's `Ctrl+Tab` or macOS's `Cmd+Tab`. Say if you have `Cmd+B` assigned to it:

## Workflow

- `Cmd+B` brings up this dock
  - If sidebar is hidden, also bring up the dimmed Viewlet
  - If sidebar is shown, dim active Viewlet

  ![dock](https://cloud.githubusercontent.com/assets/4033249/20151049/86d0f020-a66d-11e6-9f20-74ab987ac37d.png)

- While `Cmd` is pressed, additional `B` selects next Viewlet, both the highlight item on the dock and dimmed Viewlet background update

  ![flow 2](https://cloud.githubusercontent.com/assets/4033249/20151654/cd9c1bb8-a66f-11e6-8122-a9cba9711d9f.png)

- When `Cmd` is released, dock is gone. The last selected Viewlet is shown.

  ![image](https://cloud.githubusercontent.com/assets/4033249/20151695/063ac078-a670-11e6-88c9-49402ca27d1d.png)

## Additional

- This could also apply to panels, where we can have a horizontal dock.

---

What does everyone think?

@Microsoft/vscode

**Comment by joaomoreno** [comment]
Interesting idea.

But, instead of introducing new UI, why not reusing the pick API to switch between the viewlets? This is something we could benefit from today even without hiding the activity bar.

Also, <kbd>Cmd B</kbd> is the shortcut to show/hide the sidebar.

**Comment by octref** [comment]
> pick API to switch between the viewlets

That's a good idea. Let me give that a try as an extension. (Although I'd prefer some visual indication.)

**Comment by sandy081** [comment]
Looks good. I liked the idea of navigating the views with single key board shortcut / command. But how about following small suggestions?

- Toggle side bar: Toggles the visibility of side bar
- Navigating views: Navigates the views.  (If side bar is hidden, opens the sidebar and navigates)

**Comment by bpasero** [comment]
I would also follow our UX model we have for when navigating files and just open a picker with the views. I think this could be done as an extension but I also do not mind to having this as a core workbench command (especially now that I pushed the option to hide the activity bar).

@octref if you are interested in providing a PR on this, I can review it 👍

**Comment by octref** [comment]
@sandy081 Thanks for the suggestion. Will keep that in mind while doing the PR.

@bpasero Sure, I'll give it a try.

**Comment by bgashler1** [comment]
I'm also for the picker so that you can use a hotkey to open it, or you can find it in the Command Palette.

**Comment by jrieken** [comment]
👍 for picker and it should also contain the panels, not just flat but like *Problems*, *Debug Repl*, *TypeScript Output*, *Foo Output*, *Terminal 1*, *Terminal 2*. One picker to jump to all no-editor view.

**Comment by bpasero** [comment]
I introduce a new picker ("Open View") that shows all viewlets, panels, output channels and terminals:

![image](https://cloud.githubusercontent.com/assets/900690/20671268/fb02731a-b57c-11e6-8fd3-b568250e2c66.png)

**Comment by jrieken** [comment]
I like, but I see unneeded repetition of Output and Terminal - once as instances and once as category. I think I cannot open terminal without opening an instance of a terminal. likewise with output-channels

**Comment by bpasero** [comment]
Good point, I think we can merge them. For output that is straight forward, for terminals we can only do it if we also have an instance opened which requires to open a terminal panel first.
