### ISSUE TITLE
WebView add "scrolling" attribute to iframe options

### ISSUE THREAD

**Issue by kayazinc** [microsoft/vscode#152608]
### Feature Request
The ability to enable / disable "scrolling" as an attribute of the webview hosting iframe.

### Use-case
I am building a dashboard application with vscode that render scientific chart based on the json file opened (CustomTextEditor).  The scientific chart (content) is listening to webview resize event and will then render the view accordingly.  When user resize the layout (the webview), it will trigger the following steps:

1. iframe's scrolling bar will appear (due to webview resize while content size is fixed)
2. scientific chart content will resize / render in order to fit into the iframe
3. iframe's scrolling bar will disppear (due to content size adjusted)

It isn't a critical feature but it will be visually perfect if we can disable / customize the iframe's scrolling bar so that step 1 and 2 are invisible to the user.

### Proposed Solution
This would be similar to the "retainContextWhenHidden" options currently available in the `WebviewOptions`:
```
retainContextWhenHidden: true,
scrolling: false
```
to produce:
```
<iframe id="active-frame" frameborder="0" scrolling="no" ...>
```

**Comment by kayazinc** [comment]
Up for discussion.

If this is approved, i will submit a pull-request for the changes on the following files:
```
main/src/vs/workbench/contrib/webview/browser/webview.ts#L76
main/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L470
```

Thanks!

**Comment by mjbvz** [comment]
This is  possible using css. The webview doesn't introduce any new concepts around scrolling so just treat it like a normal html document
