### ISSUE TITLE
How can i see what i  sync to github in github website

### ISSUE THREAD

**Issue by WingDust** [microsoft/vscode#152692]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. if i turn on setting sync with github
2.How can i see what i  sync to github in github website

**Comment by gjsjohnmurray** [comment]
Per https://code.visualstudio.com/docs/editor/settings-sync#_can-i-use-a-different-backend-or-service-for-settings-sync the synced settings aren't actually stored on GitHub.

**Comment by WingDust** [comment]
@gjsjohnmurray where can i see the synced settings data in website

**Comment by sandy081** [comment]
@WingDust they are stored in a settings sync server from Microsoft. Please look at this doc to know how to view your data - https://code.visualstudio.com/docs/editor/settings-sync#_restoring-data
