### ISSUE TITLE
New options for every directory 

### ISSUE THREAD

**Issue by simpleneeraj** [microsoft/vscode#152644]
Hey developers this feature is very helpful for all vscode users, these days I am exploring remote IDE like.

> https://stackblitz.com

> https://codesandbox.io 

These ide have already that feature showing in image
![Screenshot_20220620-192317_Chrome](https://user-images.githubusercontent.com/69778720/174618200-7e1e6e51-ef7a-436e-b4ad-b3c8d6408181.png)

Show these icons for every directory recursive....
Add this feature as soon as possible.

**Comment by lramos15** [comment]
\duplicate #134043
