### ISSUE TITLE
Issue on debug in VS Code 

### ISSUE THREAD

**Issue by GuyChriqui** [Microsoft/vscode#15265]
- VSCode Version: Version 1.7.1
- OS Version: MacOS Sierra

Hey , Just download the VS Code (Version 1.7.1) for programming in C for collage (on my mac).

**When i try to debug that program :** 

![screen shot 2016-11-09 at 22 35 19](https://cloud.githubusercontent.com/assets/23366560/20153810/174ca1c6-a6cd-11e6-8b9f-b182de8e63da.png)

**Thats what i told to do :** 

![screen shot 2016-11-09 at 22 38 53](https://cloud.githubusercontent.com/assets/23366560/20153852/5c585e18-a6cd-11e6-9407-4a2361d9e7aa.png)

**After i Click "Lunch .json" its open that :**

![screen shot 2016-11-09 at 22 40 47](https://cloud.githubusercontent.com/assets/23366560/20153889/92a10eac-a6cd-11e6-98ec-f2d79aaac23f.png)

From here i really don't understand what i need to do to make this "Hello World" c program to debug . 

**I will be happy if you can guide me and teach me what to do to make a debugging.**

Thanks ,
Guy.

**Comment by rebornix** [comment]
The `program` property is wrong, it should just be `${workspaceRoot}/a.out`
