### ISSUE TITLE
"Toggle maximized panel" no longer un-maximizes it

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#15269]
- Run "toggle maximized panel" to maximize
- Run it again to un-maximize

This used to return the panel to a shorter size, but now it has no effect.

**Comment by Tyriar** [comment]
No repro here, what's you version/OS?

Here's mine:

- VSCode Version: Code - Insiders 1.8.0-insider (ce6d57875ab53309204cf12dc54d74956221cfc1, 2016-11-09T08:42:05.548Z)
- OS Version: Linux x64 4.8.0-26-generic, Ubuntu 16.10

**Comment by roblourens** [comment]
Yeah it's working now...
