### ISSUE TITLE
Enter in debug console should complete the active completion if it's active

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152637]
It's running it on enter, not completing like in the editor (or devtools):

![Recording 2022-06-19 at 07 00 30](https://user-images.githubusercontent.com/2193314/174609380-2ac0c34e-4e21-43c0-bc66-4aa13cbf83a4.gif)

Version: 1.69.0-insider (user setup)
Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1
Date: 2022-06-17T05:16:33.731Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by roblourens** [comment]
You can customize this with debug.console.acceptSuggestionOnEnter

**Comment by roblourens** [comment]
People keep filing issues about this so maybe, but it's annoying to type something, press enter, and the suggest widget pops up and accepts some random suggestion. This is why we have the `Insert (Tab)` hint at the bottom of the suggest widget
