### ISSUE TITLE
Task command decorations don't work when task echo: false

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152645]
![Recording 2022-06-20 at 07 00 23](https://user-images.githubusercontent.com/2193314/174618470-c48dcab4-4bdc-4fdd-8ecd-effa5c492fb7.gif)

**Comment by meganrogge** [comment]
works in OSS 
![Screen Shot 2022-06-20 at 9 12 09 AM](https://user-images.githubusercontent.com/29464607/174642802-1ee396f8-4fdd-42b8-afef-c3bb6566965e.png)

**Comment by meganrogge** [comment]
also works for me in insider's

**Comment by Tyriar** [comment]
It's because of this:

```json
  "presentation": {
    "echo": false,
  }
```

**Comment by meganrogge** [comment]
should still work. investigating https://github.com/microsoft/vscode/blob/5812177e290151fe77eb7e8dedb8e803ce2d0a40/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1134-L1139

**Comment by Tyriar** [comment]
This works but it adds an extra line because of initialText so it doesn't look quite right:

Before:

![image](https://user-images.githubusercontent.com/2193314/176493768-e45c420b-7b3c-4738-a255-d59dbd53d8ba.png)

After:

![image](https://user-images.githubusercontent.com/2193314/176493672-d7f24bba-d5c4-4234-b422-009d7175316d.png)
