### ISSUE TITLE
missing provider 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#152677]
I did `ctrl+C` in a terminal and saw this happen 
![Screen Shot 2022-06-20 at 1 56 17 PM](https://user-images.githubusercontent.com/29464607/174676804-1c03a736-118d-4781-8645-feaab3516e77.png)

**Comment by meganrogge** [comment]
the error is coming from here @jrieken https://github.com/microsoft/vscode/blob/2d4988b53b9d7d8c309ffe9f7ef457b4b8fd672e/extensions/references-view/src/tree.ts#L183-L188

**Comment by Tyriar** [comment]
@meganrogge anything in devtools console if you still have it up? That should give us a trace

**Comment by meganrogge** [comment]
![Screen Shot 2022-06-20 at 2 17 23 PM](https://user-images.githubusercontent.com/29464607/174678759-c05986ac-707c-478f-a366-3234137405c2.png)

**Comment by meganrogge** [comment]
haven't seen this recently
