### ISSUE TITLE
Don't show Stack frame not found while holding F5

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152638]
Debugging would feel a little more polished if the watch view didn't show Stack frame not found while continue is being held down.

![Recording 2022-06-19 at 07 08 32 (1)](https://user-images.githubusercontent.com/2193314/174609676-f35285c1-3741-4e66-ab61-5084165c68b0.gif)

Version: 1.69.0-insider (user setup)
Commit: fbf1cf3832d43088e27837dbb68d24ab65a098c1
Date: 2022-06-17T05:16:33.731Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by babakks** [comment]
@roblourens I'd like to take this but would need some hints.

**Comment by roblourens** [comment]
I don't have time to dig into this further, but there is some moment when the debugger is paused but we have not yet retrieved the stack frames, and maybe we try to evaluate the watch before the stack frames are retrieved.

**Comment by BamBamboozled** [comment]
Taking a look at this!

**Comment by connor4312** [comment]
This should be a lot better in https://github.com/microsoft/vscode/pull/197397. Let me know if not.
