### ISSUE TITLE
Apply on `Search` tab same tree structure for files like it is in Visual studio 2022

### ISSUE THREAD

**Issue by DainisVerdins** [microsoft/vscode#152629]
Greetings, in vscode sometimes search is very messy because no tree structure have in it for files. Would be nice to add option to see file structure/ tree dooring Search in vscode. 
Maybe as additional mode to search or like config prm in vscode configs.

Example of "mess"
![image](https://user-images.githubusercontent.com/55252915/174600586-b2dfa978-64b1-4444-b3f5-6c7ed77fe3f8.png)

example in visual studio 2022 on same request(how pretty is file structure on search)
![image](https://user-images.githubusercontent.com/55252915/174600738-f057cf72-9ef7-4fa3-b119-3ecd2f61aeb5.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20224
