### ISSUE TITLE
Update all button for all extensions, reload all updated extensions on restart

### ISSUE THREAD

**Issue by akankshagaur** [Microsoft/vscode#15275]
- VSCode Version: 1.7.1
- OS Version: Windows 7

Updating extensions becomes difficult as user needs to restart VSCode for each extension update.

**Steps to Reproduce:**

1.  Click Update for all extensions with update available.
2.  Click Reload for one of the updated extensions,  VS Code restarts.

**Desired Behavior**

VS code should reload all extensions which have been updated.

**Actual Behavior:**

Only the clicked extension is reloaded, remaining new extensions show update button.
User needs to update and reload each extension individually

**Comment by kaiwood** [comment]
Hmm, first, there is a little menu entry to update all in one step. Not sure if there is a problem with your installation, but even if you click every single one of them, when they are ready (you can tell if all show the blue reload button) you have to only restart **once**. 

Actually, you even don't have to use that button, they all do the same, reloading the window. You can have the same effect using the command `Reload Window` via the command palette.

![screen shot 2016-11-10 at 08 49 40](https://cloud.githubusercontent.com/assets/7542/20168525/f10e6fde-a722-11e6-90cf-a8b12377d304.png)

**Comment by sandy081** [comment]
@kaiwood Thanks for providing help to @akankshagaur 

@akankshagaur Please let me know if you still have issues with updating extensions. Reopen the issue with the concise problem.

Thanks
