### ISSUE TITLE
Shell integration failed to add capabilities within 10 seconds

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#152753]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows 10

Steps to Reproduce:

When I open a terminal in VSCode the following warning is logged within a few seconds: `Shell integration failed to add capabilities within 10 seconds`.
I take note of https://github.com/microsoft/vscode/issues/132669 that this issue is not a duplicate of.

**Comment by lorand-horvath** [comment]
@Tyriar It's in the devtools console. Not using any complex prompt. Just plain CMD.

**Comment by Tyriar** [comment]
Oh OK, that's unexpected if it's cmd, thanks for the info
