### ISSUE TITLE
Update split button styles

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#152758]
## Current
<img width="295" alt="CleanShot 2022-06-21 at 08 34 36@2x" src="https://user-images.githubusercontent.com/35271042/174840003-e49d0bb9-2e27-4948-9f8d-b5b1abc79edc.png">

We've used the split buttons in the past with little updates. When used in larger buttons, the separator can make it feel a bit more extreme. We'll use this issue to explore what it would look like if we adopted a smaller separator style.

## Proposed
<img width="269" src="https://user-images.githubusercontent.com/35271042/174842142-d1bf898f-1f62-4eb2-8700-e4b32402cc84.png">

Similar to other applications:

<img width="155" alt="CleanShot 2022-06-21 at 08 33 02@2x" src="https://user-images.githubusercontent.com/35271042/174839614-16d5e062-e3b0-4bb1-864c-01287af55b42.png">

![image](https://user-images.githubusercontent.com/35271042/174839740-30b07706-ddb6-4911-ac55-97e8649c1ae6.png)

<img width="250" alt="CleanShot 2022-06-21 at 08 37 11@2x" src="https://user-images.githubusercontent.com/35271042/174840409-a1302d2c-fd52-4e31-b46d-596c9b7a49af.png">

cc @lszomoru @bpasero @sandy081

**Comment by bpasero** [comment]
Works for me.

**Comment by lszomoru** [comment]
I have [a draft pull request](https://github.com/microsoft/vscode/pull/154109) that updates the `ButtonWithDropdown` widget, but it looks like there is another implementation that is being used in the action bar - `DropdownMenuActionViewItem`. Not sure who owns that.

**Comment by lszomoru** [comment]
@misolori, @daviddossett is it safe to follow some of the behaviours from [the split button](https://developer.microsoft.com/en-us/fluentui#/controls/web/button) in Fluent UI:
- hovering on the split button separator, the cursor switches to pointer 
- hovering on the split button separator, there is a small area in which none of the options are selected

**Comment by daviddossett** [comment]
> - hovering on the split button separator, the cursor switches to pointer
> - hovering on the split button separator, there is a small area in which none of the options are selected

For the first one do you mean hovering on the primary action + the secondary action button?

I think the behavior to show neither as hovered when hovering on the separator itself is good 👍

**Comment by lszomoru** [comment]
Sorry, I should have included a recording to provide more context for my questions:
* hovering on the split button separator, the cursor switches to default
* hovering on the split button separator, there is a small area in which none of the options are selected
* clicking on the split button separator is a no-op

![Recording 2022-07-12 at 22 22 38](https://user-images.githubusercontent.com/3372902/178588037-1306a375-5660-436b-a442-f13b3cbecedd.gif)

**Comment by lszomoru** [comment]
Today's Insiders's release contains these latest tweaks. @misolori, @daviddossett, could you please take a quick look to make sure that everything is working as expected. After that, I will work with @bpasero to apply the same layout to the split button that is being rendered in the action bar.

**Comment by misolori** [comment]
Everything looks good, I might tweak the separator color to be a little less transparent so it doesn't have such a strong contrast. But functionality wise it works great!

**Comment by bpasero** [comment]
Go for it.

**Comment by misolori** [comment]
This one is waiting on https://github.com/microsoft/vscode/pull/155166. @lszomoru do you anticipate having a fix this week or move to the next iteration?

**Comment by lszomoru** [comment]
@misolori, I did not get to this today so I think we should push this out to next milestone. One piece of feedback that came up today is related to the outline when each individual button of the dropdown button is focused. For the "Commit" action button we went with `outline-offset` of `-1px`. This worked fine for the large button but its not clear to me whether we should do the same for the smaller dropdown buttons in the Extension editor, and the Extension list. 

<img width="366" alt="image" src="https://user-images.githubusercontent.com/3372902/180815508-6dc8aece-c7ca-44ba-ab3c-2bc8ec119f3c.png">

**Comment by lszomoru** [comment]
@misolori, noticed that in the Fluent Design System, the outline appears inside the button. 
We could use the same approach for have consistent outline for all our buttons (default, split buttons, etc.)

Normal:
<img width="145" alt="image" src="https://user-images.githubusercontent.com/3372902/181056209-aa794fc4-2fe8-47af-a657-8762e11d0d17.png">

Focus
<img width="139" alt="image" src="https://user-images.githubusercontent.com/3372902/181056320-a88cb8e1-202b-449b-8404-6a53a40fa1d8.png">

**Comment by misolori** [comment]
That could work, the only downside is our focus color is a single color and we'd need a new color token for that. I believe we do that in the status bar as well:

<img width="231" alt="CleanShot 2022-07-26 at 09 22 41@2x" src="https://user-images.githubusercontent.com/35271042/181059280-e52b5e8d-8111-4f6d-8b6a-da32fc593352.png">

**Comment by lszomoru** [comment]
Looking at the Fluent Design System, they are using the button foreground for the focus color. Can we do the same?

**Comment by misolori** [comment]
We can try it out and see how it looks, some themes might look odd if they have a low contrasting foreground but nothing we can control there.

**Comment by lszomoru** [comment]
Today's Insiders release (2022-08-11) contains the update to the split button style in the Extensions list/editor. With that I will go ahead and close this issue. We can use https://github.com/microsoft/vscode/issues/157658 to continue the exploration for updating the outline for the button widgets.
