### ISSUE TITLE
Merge editor should support to diff yours/their against base

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#152733]

**Comment by jrieken** [comment]
stretch for June

* option a) show diff inplace with the 3wm editor
* option b) just open the "normal" diff editor

**Comment by hediet** [comment]
Basic functionality implemented in 08d36d9d.
Let's do the advanced feature when requested.

**Comment by hediet** [comment]
Verification steps:

## Preparation
```
git clone https://github.com/hediet/vscode-3wm-test-repo.git
cd vscode-3wm-test-repo
git fetch --all
git checkout input1
git merge input2
```

Open VS Code Insiders in that folder and open the 3 way merge editor:

![image](https://user-images.githubusercontent.com/2931520/175989511-a6288cd7-b855-4044-9404-b109d293af4e.png)

## Verification

Use this command (also for input2):
![image](https://user-images.githubusercontent.com/2931520/175989821-ecd9cb50-8c76-4de0-bce5-477b50efd6d0.png)

**Comment by sandy081** [comment]
It seems this command works only when the merge editor is active even though the commands are shown always. Some confusing behaviour:

- Using the command when no merge editor is open is not doing anything
- Using the command when the diff between Input 1 and Base is open is also not doing anything
- It would be nice if there is a UI gesture on these entries in the SCM view 

Let me know if you want me to open separate issue for this?

**Comment by hediet** [comment]
> Using the command when no merge editor is open is not doing anything

What would you expect to happen? Should an error message be shown?

**Comment by jrieken** [comment]
@hediet You can use the precondition-clause to control when the command shows in F1
