### ISSUE TITLE
Investigate regression to `code <folder> <path>` in hot exit

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15274]
From @bpasero in https://github.com/Microsoft/vscode/pull/14115#discussion_r87144113

> @Tyriar something is very broken here in this case:
> * have a window with a folder open that has a dirty untitled file
> * close that window without saving
> * from the command line start `code <path to that folder> <file in that folder>`
> => you are not seeing the file being opened 
> => instead the dirty untitled file is opened

> This is related to the comment I made in that one issue where I said that your restore logic will not work if someone opens Code like that.

**Comment by Tyriar** [comment]
@bpasero what do you expect to happen here? My concern with changing this is that it's makes `code <folder> <path>` work quite differently depending on whether hot exit is triggered. Normally if you open do `code <folder> <path>` it does not restore any files, however files must be restored for hot exit to work.

So we can either:

a. Leave it as is; if there are backups, restore them and ignore the requested path.
b. Open the requested file as well as restoring the editors back to their previous state. This however will be inconsistent to how it works when hot exit is not triggered.

**Comment by bpasero** [comment]
@Tyriar option a) cannot be an option. Imagine I double click on a file in the explorer and instead of opening that file, I see a window with my dirty files restored. The only option I see is b). Maybe also interesting to see what others are doing in that case?

**Comment by Tyriar** [comment]
Makes sense if that's the command that's run to open a file from the explorer context menu :+1:

**Comment by bpasero** [comment]
Yeah, windows just appends the path to the executable.

**Comment by Tyriar** [comment]
@bpasero to clarify, the following are fine:

- `code <file>`
- `code <file> <file>`
- `code <folder with backups being restored>`
- `code <folder with no backups>`
- `code <folder1> <folder2>`
- `code <folder with no backups> <file>`

It's just this case that doesn't:

- `code <folder with backups being restored> <file>`

Aren't only the following cases done via explorer as the folder isn't added to the CLI args?

- `code <file>`
- `code <file> <file>`
- `code <folder with backups being restored>`
- `code <folder with no backups>`
- `code <folder1> <folder2>`

**Comment by bpasero** [comment]
@Tyriar careful though, hot exit should also work in an empty workspace and then you have the problem for all the cases. Imagine:
* open without folder
* make some files dirty
* quit
* double click on a file to open

=> what should happen?
