### ISSUE TITLE
Remote Server Files Saves Close Tab

### ISSUE THREAD

**Issue by casonadams** [Microsoft/vscode#15271]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 3.13.0-100-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-theme-onedark|akamud|0.2.10|
|code-gnu-global|austin|0.2.1|
|cpptools|ms-vscode|0.9.2|
|Ruby|rebornix|0.10.1|

---

Steps to Reproduce:

1. open folder (git) on remote server
2. make edits
3. save (ctrl + s)

Expected Results:
File should save and remain open

Actual Results:
File saves but close (part of the time)

**Comment by bpasero** [comment]
@casonadams I suspect Code receives a file-delete event and as such we close the editor. https://github.com/Microsoft/vscode/issues/13665 is a collection of issues in that area.

Can you run "code --verbose" from the command line and then when a tab closes, send me the output you see when you toggle developer console (Help > Toggle Developer Tools > Console)?

**Comment by bpasero** [comment]
@casonadams ping

**Comment by casonadams** [comment]
@bpasero 

I change the filename, host, and user.  I don't think they were needed.

> [IPC Library: Watcher] [CHANGED] file.rb
ipc.cp.ts:141 [IPC Library: Watcher] [ADDED] host=hostname,user=user.giosave6P7TQY
ipc.cp.ts:141 [IPC Library: Watcher]  >> normalized [CHANGED] file.rb
ipc.cp.ts:141 [IPC Library: Watcher]  >> normalized [ADDED] host=hostname,user=user.giosave6P7TQY
ipc.cp.ts:141 [IPC Library: Watcher] [DELETED] file.rb
ipc.cp.ts:141 [IPC Library: Watcher] [DELETED] host=hostname,user=user.giosaveJKDWQY
ipc.cp.ts:141 [IPC Library: Watcher]  >> normalized [DELETED] file.rb
ipc.cp.ts:141 [IPC Library: Watcher]  >> normalized [DELETED] host=hostname,user=user.giosaveJKDWQY

**Comment by bpasero** [comment]
@casonadams thanks, moving into https://github.com/Microsoft/vscode/issues/13665

as a workaround, there is a way to disable file watching by setting `"files.watcherExclude": { "**": true }` in settings.
