### ISSUE TITLE
Find [inString/inComment/inCode]

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#152797]
Currently if I want to find the "foo" code (using VS Code's global search/find feature), I get results like ...

    const text = "Say hi to foo"

    const foo = 123

    // foo is great!

However, when I'm searching I almost always know that I'm either looking for the text *in a string*, or *in a comment*, or *in actual code*.  And I know I don't want results that are the other two types.

Now, I'm not sure how viable it would be for VS code to index things in a way that would make such a find possible ... but man, if you could figure it out, it'd be super convenient to be able to eliminate roughly 2/3 of the "wrong" results every time you do a find.

**Comment by IllusionMH** [comment]
Effectively duplicate of #125532. Unfortunately I doubt that there are changes in decision

/assign -rebornix roblourens

**Comment by machineghost** [comment]
To be fair, this is only *barely* language dependent.

What I mean is, while it would indeed depend on the language ... we're talking about regexes for "what's between `/*` and `*/`?" or "what's between `'` and `'`?"... not anything anyone would consider to be a true language parser.

But I can completely understand why even that level of parsing is more than the VS Code team wants to tackle, no matter how much it might improve the find feature :(  Thanks for the response!
