### ISSUE TITLE
Git - Empty Commits

### ISSUE THREAD

**Issue by Aadarsha2002** [microsoft/vscode#152702]
Issue Type: <b>Bug</b>

When I try to create an empty commit, this popup in the bottom-right comes up with the message "Commit operation was cancelled due to empty commit message.". This is after the latest Code Insiders update. Steps:
1. 1 whitespace in the commit message box
2. Click sync (check button in source control)
3. popup comes
This is a feature I use all the time, literally. I kindly request quick fixture of this issue.

VS Code version: Code - Insiders 1.69.0-insider (4c72dedb4ad283a569f83a7389468c3ae2c642c3, 2022-06-20T05:17:02.003Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (4.23GB free)|
|Process Argv|--crash-reporter-id 048985d6-7189-41d2-a30b-b488f7e8e2ee|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
jbart-studio|art|0.6.8
code-gnu-global|aus|0.2.2
vscode-intelephense-client|bme|1.8.2
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.2
vscode-html-css|ecm|1.13.0
vsc-material-theme-icons|equ|2.3.1
cshtml|fir|0.1.3
cshtml-tm|fir|1.0.0
code-runner|for|0.11.8
language-lava|Gar|1.1.11
ghoul007-puppeteer-snippet|gho|1.1.2
vscode-pull-request-github|Git|0.44.0
better-cpp-syntax|jef|1.15.18
vscode-JS-CSS-HTML-formatter|lon|0.2.3
file-downloader|min|1.0.12
vscode-docker|ms-|1.22.0
csharp|ms-|1.25.0
data-workspace-vscode|ms-|0.2.1
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.0
sql-database-projects-vscode|ms-|0.17.1
jupyter|ms-|2022.5.1001601848
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.240.0
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
atom-keybindings|ms-|3.0.9
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.0
cpptools-extension-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5625
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.23.0
puppeteer-snippets|nit|1.6.1
open-html-in-browser|pea|2.1.9
material-icon-theme|PKi|4.18.1
webfocus|pvp|0.2.3
aspx-html|QQZ|0.0.11
java|red|1.7.0
vscode-yaml|red|1.8.0
sql-snippets|sad|0.0.4
spgo|Sit|1.7.3
sonarlint-vscode|Son|3.5.4
codevalet-vscode|Sop|2.0.1
webfocus|ste|0.6.2
html-preview-vscode|tht|0.2.5
python|tht|0.2.3
pdf|tom|1.2.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.21
vscode-arduino|vsc|0.4.12
vscode-java-debug|vsc|0.41.0
vscode-java-dependency|vsc|0.19.1
vscode-java-pack|vsc|0.23.0
vscode-maven|vsc|0.35.2
php-debug|xde|1.27.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
pylanb8912:30496796
vsclangdf:30492506
841h4636:30513380

```

</details>

**Comment by rzhao271** [comment]
I tried clicking on the commit button without typing a message and the viewlet seems to be stuck.
I'm able to create a commit with a single space as a message, though.
