### ISSUE TITLE
Use the default search engine, not Bing

### ISSUE THREAD

**Issue by WhiteBlackGoose** [microsoft/vscode#152741]
Thanks for this great editor!

So here's a suggestion. When there's a pop-up about something missing, there's button "Search for help". It would be nice to have it search in the default search engine, not Bing.

**Comment by roblourens** [comment]
Which pop-up is this? Sounds like it is probably from an extension

**Comment by WhiteBlackGoose** [comment]
I got it when I ran a python cell with `pip` in a jupyter notebook (and it complained about `pip` being not installed)

**Comment by WhiteBlackGoose** [comment]
Thanks
