### ISSUE TITLE
Continuing to run a cell that was stopped at bp doesn't update status.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#152781]
Version: 1.69.0-insider (Universal)
Commit: 4c72dedb4ad283a569f83a7389468c3ae2c642c3
Date: 2022-06-20T05:17:11.836Z
Electron: 18.3.3
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

1. Open a notebook and enter a simple cell like:
```python
import time
time.sleep(10)
```
2. Set a bp on the first line and debug cell.
3. After the bp is hit, run to the end of cell via the debug toolbar or F5.

The cell status bar won't be updated until the cell is completed. It'll just be the spinner that doesn't spin.

<img width="273" alt="image" src="https://user-images.githubusercontent.com/11685408/174882090-a87fd25a-ce23-4f70-a0e5-1fe474e1b64d.png">

**Comment by DonJayamanne** [comment]
Closing this issue as no one else has reported this, and given the fact that we've had debugger for a few years and this issue open for a few years, its safe to close this as not planned.
