### ISSUE TITLE
vscode git push hangs forever when pushing to ssh remote

### ISSUE THREAD

**Issue by soredake** [microsoft/vscode#152720]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: Windows 11 Pro (22000.556)

Steps to Reproduce:

1. Installed git with `choco install -y git.install --params "/NoShellHereIntegration /NoOpenSSH"`
2. Setup ssh-agent as documented here https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent
3. Put my ssh keys to $HOME\.ssh
4. Cloned my test repo with `git clone git@gitlab.com:soredake/aadaddasdaadsad.git`
5. Edited a file in vscode, created commit
6. Tried to push commit to remote
7. It just hangs forever without asking for a password for my ssh key

This spinning thing is spinning forever:
![изображение](https://user-images.githubusercontent.com/5204968/174769095-2bda4dfe-e4e4-4e3e-b44d-626addb2bc2e.png)

No useful log here:
![изображение](https://user-images.githubusercontent.com/5204968/174769344-e454b0d6-9c03-433f-a96f-b3d4edaa7215.png)

**Comment by lszomoru** [comment]
Adding support for ssh keys with a passphrase is tracked by https://github.com/microsoft/vscode/issues/13680.
