### ISSUE TITLE
typescript intellisense not recommending node moule exports

### ISSUE THREAD

**Issue by saymck** [microsoft/vscode#152706]
Issue Type: <b>Bug</b>

@types/node is installed

required node modules while using typscript have no suggestion window for intellisense 

reproduce:
const fs = require("fs")

type fs.
Dir, Dirent, ReadStream should show up

do the same in js file for expected output

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.4.0-117-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 3099)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|31.23GB (15.97GB free)|
|Process Argv|--unity-launch --crash-reporter-id d4e59b55-f7de-4b17-992d-135b5415d4b6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-npm-script|eg2|0.3.25
vscode-typescript-next|ms-|4.8.20220620

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550
841h4636:30513380

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by saymck** [comment]
yes

**Comment by mjbvz** [comment]
Does other intellisense work?

**Comment by saymck** [comment]
yes, it seems to show for any variable that has a defined type

**Comment by saymck** [comment]
if you do 
import * as fs from "fs"
require("fs")
it works as expected? that's mostly a ts quirk but intellisense should still work the other way

**Comment by mjbvz** [comment]
yes if it's a ts file, then you need to use `import` instead of `require`. `require` still works but isn't typed

Closing as as-designed / question
