### ISSUE TITLE
Terminal: Set Fixed Dimensions crashes font size

### ISSUE THREAD

**Issue by simasch** [microsoft/vscode#152767]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1 and 
- OS Version: Windows 10 and 11 both latest versions

Steps to Reproduce:

1. Start and application that logs in the terminal (PowerShell)
2. Run Termina: Set Fixed Dimension and enter 6000 (it happens with values > 2000)

The resulting terminal looks like this:

![image](https://user-images.githubusercontent.com/593352/174856368-daa5e92e-b8c8-4688-a656-b82dfe7c3170.png)

**Comment by Tyriar** [comment]
Tracked upstream in https://github.com/xtermjs/xterm.js/issues/4186

**Comment by Tyriar** [comment]
Tracked upstream, we also have a cap of 4096 pixels now to prevent the canvas from stretching like this
