### ISSUE TITLE
Windows: Allow to open file paths that contain slashes

### ISSUE THREAD

**Issue by verysimplenick** [Microsoft/vscode#15270]
- VSCode Version: 1.7.1
- OS Version: Windows 10 pro 14393

Steps to Reproduce:

1. Try to open existing file with forward slash: C:/main.rs
2. See error.

It's abnormal at windows env. For example I can't see sources if set break at gdb:

![cant_open_file](https://cloud.githubusercontent.com/assets/922660/20157600/ef56a7ce-a6e6-11e6-9e66-8f83bcb6bfd8.jpg)

In some version ago (maybe previous 1.6) it's worked fine.

**Comment by aeschli** [comment]
How did you open the file?

**Comment by isidorn** [comment]
Ok, I see you responded on two issues, so just reposting my questions here. Also try not to duplicate your questions as it just duplicates work for us

@verysimplenick I see that the original fix for this issue is still in our source code. Can you provide some repro steps. E.g. on windows? Does this happen for all files that the adapter returns with forward slashes? You use your custom debugger?

**Comment by verysimplenick** [comment]
@isidorn sorry for duplicate, I deep searching after posting.

For bug don't need any debugger (but I found with gdb from msys2 + native debug ext (webfreak.debug).
You can reproduce without any debugger, I wrote gif for this:
![vs_slash_bug](https://cloud.githubusercontent.com/assets/922660/20174393/a8876316-a74e-11e6-929a-5a73c3fe4096.gif)

**Comment by verysimplenick** [comment]
It's electron behaviour(or bug :( ), I can reproduce it with `electron-quick-start` project

**Comment by verysimplenick** [comment]
they say that this default behaviour for open file dialog, but that about paths from debugger? where we need add `path.normalize`.

**Comment by isidorn** [comment]
We actually already call path.normalize in debug land [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/common/debugSource.ts#L18)

**Comment by verysimplenick** [comment]
Found solution, This error if I use msys2 build tools, If I change to mingw64 paths:
like `C:\vs_slash_bug/test.txt` from debugger works fine.
Looks like that gdb must be compiled with  `--host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32` (not with  `--host=x86_64-pc-msys --target=x86_64-pc-msys` as before)

thanks for help.
