### ISSUE TITLE
'>' in JSX in vscode are regarded as error by mistake

### ISSUE THREAD

**Issue by ccisman** [microsoft/vscode#152727]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
- OS Version: macOS Monterey 12.4
- Architecture: Apple M1, arm64

Steps to Reproduce:

1. Open a .jsx file in vscode
2. type JSX codes which contain '>' in the content of a tag.
3. vscode will report error and tell 'Unexpected token. Did you mean `{'>'}` or `&gt;`?ts(1382)'
<img width="747" alt="截屏2022-06-21 19 19 03" src="https://user-images.githubusercontent.com/37617396/174787375-0bdbb121-6e71-482a-8ce7-7945fb5335d2.png">

But it actually can compile and run in JSX syntax. It can be parsed correct in Babel.
<img width="1190" alt="截屏2022-06-21 19 20 54" src="https://user-images.githubusercontent.com/37617396/174787683-597f5902-1734-40ae-b93a-798967dbf71d.png">

 So is there any way to fix those mistakes?

**Comment by micnic** [comment]
This is an issue related to TypeScript, not VSCode, as it does not work in TS playground as well: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4w4BeOAHjAD4YkGXO4ADzYB6LhSA

As it's written there you should use `&gt;` instead

**Comment by IllusionMH** [comment]
AFAIK this it correct error, as `<`,`>`,`{`, and `}` are not expected as child text
https://facebook.github.io/jsx/#prod-JSXTextCharacter

**Comment by ccisman** [comment]
> This is an issue related to TypeScript, not VSCode, as it does not work in TS playground as well: https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4w4BeOAHjAD4YkGXO4ADzYB6LhSA
> 
> As it's written there you should use `&gt;` instead

Got it, thanks a lot.
