### ISSUE TITLE
Feature Request: Open an ssh vs code session directly from the command line

### ISSUE THREAD

**Issue by voltrevo** [microsoft/vscode#152820]
I'd like `code user@host:path/to/project` to launch a vs code ssh session connected as `user` at `host` in the directory `~/path/to/project`.

Currently it opens a new file called `user@host:path/to/project` instead 😉.

If needed, `--ssh` could be a required flag to make this work: `code --ssh user@host:path/to/project`

Right now, as far as I know, I'm required to launch a new vs code ssh window from an existing unrelated vs code window, and then change to the project directory on that server instead. If there's already a more streamlined way, I'd love to know :).

(PS: I absolutely love your ssh integration otherwise 💪.)

**Comment by voltrevo** [comment]
Amazing! Thank you 😁.

@roblourens I would have found this if it was documented in `code --help`. My suggestion then is to add it there?

**Comment by voltrevo** [comment]
Also, is it possible to specify the user you want to connect as?

**Comment by roblourens** [comment]
You can use `ssh-remote+username@remotename` or (recommended) set up an ssh config

cc @aeschli this question seems to come up somewhat often

**Comment by aeschli** [comment]
I can't just add `ssh-remote+username@remotename` to `code --help` as Remote-SSH is an extension.
Needs a new mechanism where as the `code --help` reads additional info from product.json.

**Comment by roblourens** [comment]
Maybe you can cheat in some way, like have `--help` say `--remote: Open vscode using an installed Remote extension. See http://some doc url for examples`
