### ISSUE TITLE
HTML Tag Matching doesnt work.

### ISSUE THREAD

**Issue by ankitrg** [Microsoft/vscode#15285]
- VSCode Version:
- OS Version:

Steps to Reproduce:
http://stackoverflow.com/questions/40522742/visual-studio-code-not-matching-html-tags

I've posted the question on StackOverflow also.

**Comment by wUFr** [comment]
are you editing your file as "html" ? i know it doesnt work with Smarty and i always have to switch to html at the bottom right

**Comment by ankitrg** [comment]
Yeah I tried that it works with `.html` file but not with `.html.erb` and `.jsx` files in my case.

**Comment by aeschli** [comment]
Tag matching is currently only supported for html files.
#2915 is for PHP tag matching.
https://github.com/Microsoft/TypeScript/issues/10138 is for tags in TSX/JSX.
