### ISSUE TITLE
When both are defined, vscode should prefer markdownDescription over description

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#152859]
When defining an extensions configuration, there are two fields extensions can set, `description` and `markdownDescription`.

If an extension defines both, VS Code will prefer the plain text value, rather than the markdown one. Would it be better to change this default?

Due to #88927 some extensions were forced to define the `description` field, whilst this is now fixed, the hangover from it is that some extensions do still specify both.

In general I think it makes sense to use the markdown string where one is available instead of the plain text one?

**Comment by rzhao271** [comment]
Verification steps:
1. Clone and run the following extension: https://github.com/rzhao271/vsc-152859
2. Open the Settings editor and search `vsc-152859.mySetting`
3. Verify that the description says "The markdown description. This description should show."
