### ISSUE TITLE
the command title of icon can not find in command panel

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#152854]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.68.1 (system setup)
提交: 30d9c6cd9483b2cc586687151bcbcd635f373630
日期: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.25140

Steps to Reproduce:

1. `却换布局`
![image](https://user-images.githubusercontent.com/1876302/175019507-50f06c9e-fa91-4360-9388-0513260118f7.png)

2. finally we find it named: `在组布局中切换拆分编辑器`

![image](https://user-images.githubusercontent.com/1876302/175019761-a178b494-2e9c-4879-96c6-d9701810bba3.png)

**Comment by sbatten** [comment]
I think the issue is that the alt text is so different from the command name so it doesn't show up in the command palette when searched.

**Comment by bpasero** [comment]
Maybe this is a translation issue then? In english the icon hover shows "Toggle Layout" and I can find it:

<img width="760" alt="image" src="https://user-images.githubusercontent.com/900690/175216507-7248fb1b-036e-49a3-8d9a-8a670125f7fe.png">

**Comment by heartacker** [comment]
IMOP, there are two diff commands named `toggle Layout` and `view: toggle split editor in group layout`.

anyway, in english you can search `toggle Layout` to match `view: toggle split editor in group layout`

----
and in chinese the icon tooltip is `切换布局`。

we could not search 在组**布局**中**切换**拆分编辑器 with **切换布局**、 **布局切换** 、布局 切换

we have to use **布局**中**切换** with full matching.

![image](https://user-images.githubusercontent.com/1876302/175339463-b017ba01-5c44-476e-ab51-f10d2b60962b.png)
![image](https://user-images.githubusercontent.com/1876302/175339477-f23a5404-544b-4bc2-99b5-aa15d05ff1bb.png)

![image](https://user-images.githubusercontent.com/1876302/175339493-b9b566ab-d69b-4201-b3d7-8cee450e76d2.png)

**Comment by bpasero** [comment]
Yeah but the name is intentionally different because in the one place it is in context and in the other it is not. We would have to put the full name even in context which seems odd?

**Comment by heartacker** [comment]
also please consider this issue: https://github.com/microsoft/vscode/issues/153060
thanks

**Comment by bpasero** [comment]
Rename goes into https://github.com/microsoft/vscode/pull/153069

For the fuzzy search, there are issues logged (see https://github.com/Microsoft/vscode/issues/27317).

**Comment by TylerLeonhardt** [comment]
@bpasero I assume you attempted to fix this by changing the English in hopes that the Chinese translation followed... that was... pretty close:
![image](https://user-images.githubusercontent.com/2644648/176783894-c4f11e78-8686-4623-8d7b-c6ac4544146e.png)

First two characters seem ok but then the 3rd and 4th don't align.

I will mark this as verified considering that this is now better than what it was but I think that @heartacker if you have a better suggestion for this translation, can you please open it in the https://github.com/Microsoft/vscode-loc repository? That repository is the location that we take feedback on translations.
