### ISSUE TITLE
Merge editor and auto save

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#152841]
(wasn't sure if we already had an issue for this)

In my mind, the merge editor should not auto save but stay dirty even when auto save is enabled. Especially since it opens dirty right when you click it, auto save fires right after.

Question is: should auto save still be supported if all conflicts are resolved? Maybe that would be a nice model:
* until there are conflicts, auto save ignores the editor
* once all conflicts are resolved, auto save kicks in

I think there is missing working copy support for this because currently auto save is driven by a capability:

https://github.com/microsoft/vscode/blob/75362a62685799fee8c5f3760d006705ca31a5d5/src/vs/workbench/browser/parts/editor/editorAutoSave.ts#L94-L96

We could introduce a new capability `CanAutoSave`. But unsure how to wire this through because currently the merge editor uses the same text file model working copy as a normal editor.

Thoughts?

**Comment by hediet** [comment]
> Question is: should auto save still be supported if all conflicts are resolved? Maybe that would be a nice model:
> 
> until there are conflicts, auto save ignores the editor
> once all conflicts are resolved, auto save kicks in

Sounds interesting, we should try it out!

**Comment by bpasero** [comment]
Looked into how such a change would look like and its not very elegant: basically the merge editor when resolving the text model reference would have to update the working copy's capabilities ad-hoc and keep it up to date based on conflicts. It would have make sure to restore the original capabilities when being disposed.

Might be a bit confusing for users because this also means that when you open the original file, auto save will not work, pending conflict resolution. But that is the price for sharing the same model I guess...

**Comment by bpasero** [comment]
> esp once we have the message to warn you when closing with unresolved conflicts

With auto save enabled, the editor would not have a way to override closing of the editor because the editor is not dirty. And even if we had a way to override closing, the fact that the editor opens dirty and is saved would still change the file right away. I think the problematic part is:
* as a user you just open a file with merge markers from scm view
* the merge editor removes all merge markers instantly
* auto save kicks in and saves the file

I see no other way solving this than blocking auto save for as long as there are conflicts, or at least as long as the merge editor is being used to edit the file.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/commit/60b75142de7e82b657ed89e87b0d71c26fa54cf8 makes this a lot better, editor remains dirty, even with auto save. I wonder if we could sell this without further changes...

**Comment by jrieken** [comment]
I was wondering about the same and I think it's OK except for the fact that we are actually saving the file... E.g you see dirty, you save successfully, and still see dirty. That doesn't sound right tbh

**Comment by jrieken** [comment]
@bpasero Given the "Discard" option I don't see a reason to do something special for preventing auto-save. Tho, what we would need is a way to trigger the `confirm` flow with the merge-editor being dirty. Can you help here?

**Comment by bpasero** [comment]
@jrieken maybe a new optional method/property on `EditorInput` such as `shouldConfirm?: boolean` which if not implemented will fallback to the `isDirty` check, would that be it? And then the merge editor would no longer mess with the dirty state but use that instead? Alternatively `shouldConfirm` could also just be implemented generic by checking for `isDirty` and you could override.

**Comment by jrieken** [comment]
> Alternatively shouldConfirm could also just be implemented generic by checking for isDirty and you could override.

Pro `shouldConfirm` but against marrying that with dirty states. Also, I would prefer a single-property that handles close-confirmation. The classes from which I inherit have gotten soo wide that it is super hard to correlate what belongs to what and how things are supposed to be used. IMO a `confirmHandler: { shouldConfirm: () => boolean, confirm:() => Promise<...> }` is better than a the current flat list

**Comment by bpasero** [comment]
Yeah I like the idea of having a single property to drive this. To clarify: I would not marry this with dirty states, but if an editor decides to not implement the confirm handler, we simply do what we did before: check if the editor is dirty and bring up a generic confirm dialog if it is dirty.

**Comment by jrieken** [comment]
Closing - there is now a revert command to go back to the opening-time state

**Comment by jrieken** [comment]
To verify

* open merge editor from a conflict
* notice how the file is dirty and how some edits have already been applied
* with any further changes close the editor
* verify that get a modal that offers to discard any merge change (restore to the state at which the editor was opened)
