### ISSUE TITLE
Allow scoped snippet

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15287]
Sublime allows snippet for particular scopes: http://docs.sublimetext.info/en/latest/extensibility/snippets.html

This is particularly useful for embedded languages like vue.js:

```vue
<template>
  <div id="app">
    Clicked: {{ $store.state.count }} times, count is {{ evenOrOdd }}.
    <button @click="increment">+</button>
    <button @click="decrement">-</button>
    <button @click="incrementIfOdd">Increment if odd</button>
    <button @click="incrementAsync">Increment async</button>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex'
export default {
  computed: mapGetters([
    'evenOrOdd'
  ]),
  methods: mapActions([
    'increment',
    'decrement',
    'incrementIfOdd',
    'incrementAsync'
  ])
}
</script>
```

**Comment by alexandrudima** [comment]
This can be implemented from an extension that registers a completion item provider that is smart enough to suggest certain snippets only in certain locations.

**Comment by siegebell** [comment]
@alexandrudima I see no *generic* way for an extension to do this until #580 is resolved.

**Comment by octref** [comment]
@alexandrudima Well, now the user who wants to make a snippet only available to a certain part of his code has to:

- Re-parse the code using vscode-textmate on each document change (which can be slow)
- Get a parser for the snippets (the one bundled with VS Code can't be easily used standalone)
- Write a `CompletionItemProvider` that provides the parsed snippets as `CompletionItem` if scope matches.

That's a lot of work and the extension will be slow.

**Comment by alexandrudima** [comment]
@octref It is not in our best interest to further leak TM scopes in APIs or build more and more features on top of TM scopes:

We want at one point to be able to colorize using something else that doesn't have the problems and baggage of TM.

**Comment by octref** [comment]
OK I'll close this as out-of-scope since I don't see we replacing TM anytime soon.
Sublime does have this since they have their own rule engine.
