### ISSUE TITLE
When formatting code, resulting in JS template engine language which can not be used to break

### ISSUE THREAD

**Issue by a526672351** [Microsoft/vscode#15284]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.1|
|debugger-for-chrome|msjsdiag|0.5.2|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
![image](https://cloud.githubusercontent.com/assets/5345266/20168629/2057a5fe-a75e-11e6-92a4-9163fbcf7cad.png)

2.
![image](https://cloud.githubusercontent.com/assets/5345266/20168640/32e3f510-a75e-11e6-9db0-e3d9c079e44a.png)

**Comment by a526672351** [comment]
When I use Format Document

**Comment by aeschli** [comment]
Can you paste the example code that you format?
I see you have a extension installed for formatting. You might have to file the issue to the repository of that extension.

**Comment by a526672351** [comment]
`<div class="ad_middle">
                            <div class="pro_list">
                                {{if taglist != ''}}
                                <ul class="clear">
                                    {{each taglist as list}}
                                        <input class="tagid" type="hidden" data-tagid="{{taglist[0].id}}">
                                        {{each list.goodslist as value index }}
                                        {{if index < 4}} 
                                        <li class="column_2 content" data-recid="{{value.recid}}" data-sortid="{{value.sortid}}">
                                        <div class="item_content">
                                            <div class="pro_type">
                                                <span></span>
                                            </div>
                                            <div class="pro_img">
                                                <a href="{{if value.id != null && value.id != ''}}{{value.goodslink}}{{else}}#{{/if}}">
                                                    <img src="{{if value.goodspic != null }}http://img3.wtoip.com{{value.goodspic}}{{else}}/static/img/template/pro_img-1.png{{/if}}">
                                                </a>
                                            </div>
                                            <div class="pro_text">
                                                <p class="name">
                                                    {{if value.goodsname != null}}{{value.goodsname}}{{else}}点击添加你想展示的文字内容{{/if}}
                                                </p>
                                                <p class="des">
                                                    {{if value.goodsdesc != null}}
                                                    {{=getGoodsIntro(value.goodsdesc)}}
                                                    {{else}}
                                                    点击添加你想展示的文字内容
                                                    {{/if}}
                                                </p>
                                                <p class="price">
                                                    {{if value.id != null && value.id != ''}}
                                                    {{if value.price > 0 }}
                                                    ￥{{value.price}}
                                                    {{else}}
                                                    面议
                                                    {{/if}}
                                                    {{else}}
                                                    价格：待定
                                                    {{/if}}
                                                </p>
                                            </div>
                                        </div>
                                        </li>
                                        {{/if}} 
                                        {{/each}}
                                    {{/each}}
                                </ul>
                                {{/if}}
                            </div>
                        </div>`

**Comment by a526672351** [comment]
Above is my code examples, when I have only the editor comes with the format is not possible, I have put the plug-in has been tested.

**Comment by a526672351** [comment]
![image](https://cloud.githubusercontent.com/assets/5345266/20169094/90377b0e-a760-11e6-9eb4-ccaddd520bce.png)
You can use this function to test

**Comment by jrieken** [comment]
we still need to know if what file type this happens and if it happens with extensions enabled (`code --disableExtensions`)

**Comment by a526672351** [comment]
file type is the html . when user use  the editor own format function  to format  JS template engine language,then the  JS template engine language will be  format  to linebreak state. that will make a problem , the browser cannot recognize   linebreak of  JS template engine language.

**Comment by a526672351** [comment]
webstorm  editor  can identify the template language , vscode cannot.

**Comment by aeschli** [comment]
We're using the html formatter of js-beautify here.

**Comment by aeschli** [comment]
This issue was moved to beautify-web/js-beautify#1066
