### ISSUE TITLE
Move selection to adjacent file when deleting files

### ISSUE THREAD

**Issue by ryan-archetype** [microsoft/vscode#152855]
When deleting a file, the navigator will jump to the last opened file, even if this is in another project or folder. Many times, I assume I'm still in the same place, but the view has confusingly shifted.

If possible could the selection either clear, or move to the file directly above or below the deleted one?

**Comment by lramos15** [comment]
You'll want to turn `explorer.autoReveal` off to prevent the explorer from revealing your opened files.

**Comment by ryan-archetype** [comment]
Thanks @lramos15!
