### ISSUE TITLE
Intellisense for C# does not work in multiproject environment

### ISSUE THREAD

**Issue by PradeepLoganathan** [Microsoft/vscode#15282]
- VSCode Version: 1.7.1 
- OS Version: Microsoft Windows [Version 10.0.14393]

Steps to Reproduce:

1. I have created a sample GIT repository at https://github.com/PradeepLoganathan/testvscode
2.  I have folders for source and tests and have initialized projects in these folders using dotnet new.
3. I have a global.json specifying the project folder structure.
4. Intellisense no longer works.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#904
