### ISSUE TITLE
in the side panel file explorer highlight current open file in the editor more to improve accessibility for all users not only with accessibility features

### ISSUE THREAD

**Issue by mohammedsalem97** [microsoft/vscode#152812]
in the side panel file explorer highlight current open file in the editor more to improve accessibility for all users not only with accessibility features.
the current highlight is so weak and i cannot recognize with it which file is open in the active editor.
in the screenshot below i currently open header_widget.dart file, which is slightly recognizble from other files in the list
i suggest adding obvious background color like yellow or green or blue
![image](https://user-images.githubusercontent.com/52335769/174914838-5dd2a2eb-3b48-4306-b552-91b50e638e94.png)

**Comment by lramos15** [comment]
This is a themeable token that themes can set.
