### ISSUE TITLE
e is backspace, r is tab running under x2go

### ISSUE THREAD

**Issue by chrisadamsonmcri** [microsoft/vscode#152857]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Ubuntu MATE 20.04

Steps to Reproduce:

1. Have an x2go session open on a workstation.
2. Create a new empty file.
3. The `e` key is interpreted as backspace and `r` is tab.

A similar issue was present in atom: https://github.com/atom/atom/issues/18480

**Comment by deepak1556** [comment]
Not actionable since we rely on the keycode from the runtime. This should be addressed in chromium.
