### ISSUE TITLE
Caret positioned too far left when clicking whitespace

### ISSUE THREAD

**Issue by 6twenty** [microsoft/vscode#152819]
Issue Type: <b>Bug</b>

This issue is more easily observed with "render whitespace" set to "all" so what space characters are shown with a dot in the centre. It is also easier to observe when zoomed in so that the characters are much larger.

Create a new file and type "hello world".
Using the mouse, try to place the caret in between the space character and the "w".
If you click more than a few pixels away from the "w", the caret will be placed to the *left* of the space character - even if the cursor is positioned on the right of the dot marking the centre of the space character.

I believe this is a recent change (last few weeks) because I never used to have trouble selecting text; recently though I always end up selecting an additional space character at the start.

I have tested with extensions disabled and also on the latest Insiders, and replicated the same behaviour both times.

Video:

https://user-images.githubusercontent.com/169607/174930087-4e5a3473-8146-43d7-a2d6-45d516d1a422.mov

-----

VS Code version: Code - Insiders 1.69.0-insider (Universal) (10e6e876822fa2da15fb68e8a6f1fb9aa8d94ce2, 2022-06-21T05:16:46.242Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506
841h4636:30513947

```

</details>

**Comment by alexdima** [comment]
Caused by the zwj characters introduced via https://github.com/microsoft/vscode/pull/150349
