### ISSUE TITLE
The mimes are not split by line separators when dnd from file explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#152836]
Version: 1.69.0-insider (user setup)
Commit: f361c5b71d6676cfc6de97cdb1cc40b08bf7d994
Date: 2022-06-22T05:17:09.661Z
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

This is a follow up of https://github.com/microsoft/vscode/issues/152031

Steps to Reproduce:

1. Clone the dnd sample: https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample
2. Add `'text/uri-list'` to the `dropMimeTypes` of  `TestViewDragAndDrop`
3. Add some logs in `handleDrop(...)`:
```
sources.forEach((value, key) => {
    console.log(`${key} : ${value.value}`);
});
```
4. Launch the extension
5. Drag multiple files to the dnd sample view, the uris in the data transfer are not split by line separators.

// cc @alexr00

**Comment by jdneo** [comment]
Sorry forgot to mention, it's from VS Code file explorer

**Comment by mjbvz** [comment]
@jdneo Can you check the actual value, not just the value printed by console.log?

I debugged this and oddly while `console.log` just prints:

```
text/uri-list : file:///Users/matb/projects/san/b.md
```

The actual value of `value.value` is:

```
file:///Users/matb/projects/san/b.md
file:///Users/matb/projects/san/index.js
file:///Users/matb/projects/san/package-lock.json
file:///Users/matb/projects/san/package.json
```

In this case each file name is separated by a `\r\n` pair

**Comment by jdneo** [comment]
Tested in:

Version: 1.69.0-insider (user setup)
Commit: 668c538b8d2fec1258ed786ae212124d6d68023c
Date: 2022-06-23T05:16:43.681Z
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

It's still stored in one line:

https://user-images.githubusercontent.com/6193897/175438263-37876d70-23cc-4c37-86a4-5d313816d26a.mp4

Is there anything I missed?

**Comment by mjbvz** [comment]
Thanks.  Only happens on windows for me. Taking a look now

**Comment by alexr00** [comment]
> Also we are possibly hitting https://bugs.chromium.org/p/chromium/issues/detail?id=239745

Nice find. I couldn't find us setting `text/uri-list` anywhere either.

**Comment by aeschli** [comment]
Verified on Windows and Linux in 1.69.0-insider (user setup) Commit: 0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce, 022-07-01T05:17:04.343Z
