### ISSUE TITLE
API extensions.onDidChange not firing upon changes made to extensions.all

### ISSUE THREAD

**Issue by Dayveed117** [microsoft/vscode#152805]
Issue Type: <b>Bug</b>

While developing my extension, I expect to use extensions.onDidChange to check if an extension dependency has been either disabled or uninstalled.

After I set up some logging in the event's callback to check its functionality, played around by disabling and uninstalling some Extension Development Host extensions, but the event's callback never got to run.

### Code in question:

```
context.subscriptions.push(vscode.extensions.onDidChange(() => {
  console.log("Changed!");
}));
```

### Steps to reproduce

- Have the above code inside `activate` function in main js/ts file;
- Run the extension, opening Extension Development Host instance;
- Enable, disable, install or uninstall any of the extensions Extension Development Host instance.

### Expected output

- In main instance of vscode get a "Changed!" in debug console anytime changes are made to extensions in Extension Development Host instance.

### Result

- Seeing no results in debug console despite reproducing the steps.

### System Info

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.13.0-51-generic

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.13.0-51-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3820 CPU @ 3.60GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|7.70GB (0.27GB free)|
|Process Argv|. --crash-reporter-id 17063add-523e-42e6-9f20-d259aa764e79|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
michelson|bak|0.1.0
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.2
githistory|don|0.6.19
vscode-npm-script|eg2|0.3.25
ligo-vscode|lig|0.4.12
compiler-explorer|Mat|0.5.0
ocaml-platform|oca|1.10.4
fix-json|oli|0.1.2
michelson-debugger|ser|0.2.0
trailing-spaces|sha|0.3.1
vscode-bnf|Val|0.0.1
vscodeintellicode|Vis|1.2.21
colonize|vms|2.2.2
better-align|wwm|1.1.6
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550
841h4636:30513947

```

</details>

**Comment by alexdima** [comment]
@Dayveed117 This works fine for me. Here are the complete extensions I try with:
* `152805A/package.json`:
```json
{
    "publisher": "alex",
    "name": "152805A",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": ["*"],
    "main": "index.js"
}
```
* `152805A/index.js`:
```js
const vscode = require('vscode');
exports.activate = function(context) {
	console.log(`152805A is now active! Available extensions: ${vscode.extensions.all.length}.`);
	vscode.extensions.onDidChange(() => {
		console.log(`received extensions change event! Available extensions: ${vscode.extensions.all.length}.`)
	})
}
```
* `152805B/package.json`:
```json
{
    "publisher": "alex",
    "name": "152805B",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": ["*"],
    "main": "index.js"
}
```
* `152805B/index.js`:
```js
const vscode = require('vscode');
exports.activate = function(context) {
	console.log(`152805B is now active!`);
}
```

* I then proceed to load VS Code and disable `152805B`
* I then reload the VS Code window (because an extension that is running cannot be disabled without a reload)
* in the new window I enable `152805B` and I can see the message being printed by `152805A`

https://user-images.githubusercontent.com/5047891/176778979-7b89537c-28de-45dd-9102-7ce66ec48f8e.mp4

**Comment by Dayveed117** [comment]
> I then reload the VS Code window (because an extension that is running cannot be disabled without a reload)

I see, seems I lacked this bit of information. This matter is resolved, thank you
