### ISSUE TITLE
Merge editor: focus behaviour not aligned with changes diff editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#152948]
Minor nit, but noticed that clicking the merge editor, focus moves out of the tree, so some `preserveFocus` thingy is probably missing:
![Recording 2022-06-23 at 09 00 38](https://user-images.githubusercontent.com/900690/175236039-7466e99f-a573-491e-bd9d-f71416e6f1ec.gif)

**Comment by bpasero** [comment]
There is now a slight inconsistency between merge editor and other diff editors from SCM changes view. The rules for preserving focus or not are:
* mouse click: preserve focus
* double click: move focus
* keyboard: move focus (i.e. `Cmd+Down` on macOS)

@alexr00 @joaomoreno  I remember a while ago we made this consistent in custom trees and SCM to behave like workbench core, do you remember how we solved this? I think we found a way that an extension author does not have to set the focus flag explicitly because we know better based on how the command was invoked.

**Comment by bpasero** [comment]
Debugging this, I remember now: by setting a command to run for the tree item: this allows the widget to forward the correct editor options based on how the item was clicked:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/900690/175759164-dac5644b-f849-43e2-9d37-71a4bc1d852d.png">

I guess because merge editor is behind a setting, we cannot use the same way?

**Comment by jrieken** [comment]
Let's continue this in another issue, which is exposing real API to open merge editors. For now, it never moves focus but once there is API the SCM viewlet (and others) should be able to control this.
