### ISSUE TITLE
clicking on the scrollbar should take you right to that part of the buffer

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#152911]
Now that we have scrollbar decorations, I often want to jump right to that part of the buffer. Esp when I have a lot of scrollback, it feels very cumbersome to wait for the scrolling to take me there. 

It's also a little hard to click on the scrollbar area which:
1. would prevent accidental jumps
2. means it's hard to hold down the click for a long time to get to the right area

https://user-images.githubusercontent.com/29464607/175132067-ac552c51-5ccb-41f9-9f62-7f832592d2c7.mov

**Comment by meganrogge** [comment]
the editor does this, which I guess is why I expect it

**Comment by meganrogge** [comment]
https://user-images.githubusercontent.com/29464607/175132560-3e0bbdbb-9f40-4af2-bfd6-c5d21fd67ee5.mov

**Comment by Tyriar** [comment]
I wish we could do this but it basically requires a full custom scroll bar like monaco has. The trouble is xterm.js can't depend on monaco and it would be a lot of effort for little pay off.

**Comment by meganrogge** [comment]
Couldn't we fake it though? Like create a dom element on top of where the scroll bar is and when clicked, scroll to the line that we calculate?

**Comment by Tyriar** [comment]
Maybe, the scroll bar is quite fragile atm as it's basically a hack to get it to work to begin with. I'm also careful with touching any scroll events as when websites normally do this the UX/performance suffers

**Comment by Tyriar** [comment]
Closing as out of scope for now, if we moved to a custom scroll bar we would do this as part of that work
