### ISSUE TITLE
editor.formatOnSave is within files section in Default settings

### ISSUE THREAD

**Issue by DasJott** [Microsoft/vscode#15290]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-simple-icons|LaurentTreguier|0.5.0|
|vscode-todo|MattiasPernhult|0.8.0|
|material-icon-theme|PKief|1.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|html-css-class-completion|Zignd|1.0.3|
|githistory|donjayamanne|0.1.0|
|phpunit|emallin|1.0.0|
|php-intellisense|felixfbecker|0.0.11|
|text-transform|florianloch|0.1.0|
|auto-close-tag|formulahendry|0.3.5|
|auto-rename-tag|formulahendry|0.0.8|
|php-symbols|linyang95|0.1.2|
|Go|lukehoban|0.6.48|
|csharp|ms-vscode|1.4.1|
|bootstrap-3-snippets|wcwhitehead|0.0.8|

---

Steps to Reproduce:

1. Open Workspace settings
2. Search for "editor.formatOnSave"
3. You'll find it under the files section

**Comment by bpasero** [comment]
From https://github.com/Microsoft/vscode/commit/f4735e525c282cb79ee29f56bb0a1bb5a57069b8

**Comment by jrieken** [comment]
@sandy081 I am contributing the `formatOnSave` setting into the `editor` category but it seems that the configuration editor now shows it twice. 

![screen shot 2016-11-14 at 13 07 59](https://cloud.githubusercontent.com/assets/1794099/20264364/77438792-aa6b-11e6-88c0-8c3521352ead.png)

**Comment by sandy081** [comment]
@jrieken Yes. It looks like there is a bug in generating the default settings content which is generating two sections for Editor settings

**Comment by sandy081** [comment]
@jrieken @aeschli 

Looks like this editor configuration `editor.formatOnSave` is registered separately than from other editor configurations. And while reading from the registry these come as two different groups but with same id and title. Hence they are being generated/shown as two different sections. 

It can be fixed in two ways
- Fix Configuration registry so that it does not duplicate groups.
- Fix the generation of default settings content given the fact that configuration registry can return such duplicate groups.

My option is to get it fixed in the registry.

**Comment by aeschli** [comment]
We had the same problem with the Telemetry settings
Right now this i solved that only one of the contributions includes a title. The other one pickes a order that is directly after that group

**Comment by sandy081** [comment]
Did the same workaround for this configuration

**Comment by jrieken** [comment]
Soft reopen - the setting is in the correct bucket but there is no obvious sorting. It comes after `diffEditor` entries but none of the setting seems to be sorted by name.

![screen shot 2016-12-08 at 12 12 52](https://cloud.githubusercontent.com/assets/1794099/21007960/c50353ae-bd3f-11e6-92b2-1ab8ca5f4dda.png)

**Comment by sandy081** [comment]
@jrieken Do you mind opening sorting as a separate issue and leave this just for grouping? Because sorting/ordering looks to me a generic issue in settings.
