### ISSUE TITLE
Please don't fold the menu bar into a hamburger menu when the command center is enabled

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#152906]
This actually forces me to navigate one level more when I want to get to a menu entry. I think that this is not necessary even not when running in the Web. Could we at least make this an options please.

<img width="706" alt="capture" src="https://user-images.githubusercontent.com/1931590/175124307-672827cd-0c6f-4b1a-babd-9082cc8ad76e.png">

**Comment by dbaeumer** [comment]
The hambuger menu made me disable the command center again.

**Comment by jrieken** [comment]
The colour of the burger doesn't look heathy either... @sbatten Can we make it dynamic? Show the menu when there is space and but use the burger when there isn't any?

**Comment by sbatten** [comment]
do you mean that we would not do our normal collapsing (one-by-one) and instead immediately collapse all?

**Comment by sbatten** [comment]
pushed a fix for the color issue

**Comment by jrieken** [comment]
> do you mean that we would not do our normal collapsing (one-by-one) and instead immediately collapse all?

Both 🤓 Do the normal collapse until a certain threshold is reached (3?) and then collapse into the burger menu

**Comment by heartacker** [comment]
1. show them if space is  enough.
2. reduce the length of command center while title length reducing IF no enough space for both，until the command center length  IS reaching LIMIT_MIN_LENGTH
3. LAST,collapse the least menu to the `…`

**Comment by JustinGrote** [comment]
As a side note, it has frustrated me enough to work harder on memorizing my keyboard shortcuts, so that's a sneaky benefit I guess? :)

**Comment by jimrandell** [comment]
I turn on the CC for 15 min, get all excited about it(!) but am now forced to turn it off again! (teaser)
its conveniences (as I perceive them after 15 min of use) pail in comparison to the inconvenience imposed by the hamburger!
(disappointing, hope we don't have to wait to long, or eternity, for a fix)

**Comment by JustinGrote** [comment]
@sbatten thank you very much!

**Comment by heartacker** [comment]
SEEM THAT there is little bug after click CC and exit
![CC](https://user-images.githubusercontent.com/1876302/179200403-891d1a09-bd53-4c9c-ab4b-4c99d15903fc.gif)
