### ISSUE TITLE
File open/save as dialogs open os 'file choice' window in the background and yield a pop-up notification

### ISSUE THREAD

**Issue by mpwilson-gh** [microsoft/vscode#152919]
When:

- Any activation requiring file choice from hotkey or menu navigation 
- - File open, open directory, save as, etc.

What:

- OS File Choice dialog opens behind the main VS Code window.
- an OS notification that "file open is ready" pops up momentarily.

I can click through or alt-tab around 'til I get to the window to perform my file operation.  But it's weirdly disruptive.

OS: Ubuntu 22.04 LTS

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
