### ISSUE TITLE
JSDoc annotations not autocompleting

### ISSUE THREAD

**Issue by seirdotexe** [microsoft/vscode#152970]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

![](https://s8.gifyu.com/images/2022-06-23-1450155.gif)

**Comment by mjbvz** [comment]
Quick suggestions are disabled by default in comments. Either change `editor.quickSuggestions` or trigger suggestions manually

**Comment by seirdotexe** [comment]
Right, interesting how this default setting suddenly got changed. Anyhow for anyone coming across, the following fixes it:
```json
  "editor.quickSuggestions": {
    "comments": true
  },
```

**Comment by bugfix2020** [comment]
> Right, interesting how this default setting suddenly got changed. Anyhow for anyone coming across, the following fixes it:
> 
> ```json
>   "editor.quickSuggestions": {
>     "comments": true
>   },
> ```
nice, it's working!
