### ISSUE TITLE
Shotcut preview of an item doesn't contain entire item's content

### ISSUE THREAD

**Issue by poliscukmykola** [microsoft/vscode#152985]
Issue Type: <b>Bug</b>

When you move mouse over and an item in editor like method or an object in code and hold "ctrl" key, preview of item's content is displayed. But when content of item like method is bigger than 9 rows or object bigger than 8 rows, other rows are not displayed. following rows are just cut-off

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by jrieken** [comment]
Yeah, we do that purpose because the hover would get very large otherwise
