### ISSUE TITLE
why is it hard for the users to change the text color

### ISSUE THREAD

**Issue by jozhuare99** [microsoft/vscode#152931]
Issue Type: <b>Bug</b>

im looking tor the setting to change the text color of software text and customise the editors text colors
i want to customized the
the tag text the code the comment text color
highlight text
selected text
pre selected text 
i found this difficult to find in setting and set in json setting
i cant change it at all. 

can you fix this issue

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (10.17GB free)|
|Process Argv|--crash-reporter-id 7d21a290-7594-48f1-af34-3ed2965e4b7d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
pascal|ale|9.5.0
bootstrap-5-snippets|bab|0.1.1
vscode-intelephense-client|bme|1.8.2
phpserver|bra|3.0.2
vscode-standardjs-snippets|cap|0.9.0
node-snippets|chr|1.3.3
bootstrap-5-snippets-by-coder-foundry|Cod|1.2.1
compulim-vscode-closetag|Com|1.2.0
the-powerful-bootstrap|Cro|1.2.4
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.0
prettier-vscode|esb|9.5.0
vs-code-xml-format|fab|0.1.5
ims-api-tool|Fao|4.1.0
vscode-language-babel|mgm|0.0.36
vscode-docker|ms-|1.22.0
vscode-edge-devtools|ms-|2.0.0
vscode-typescript-next|ms-|4.8.20220622
vscode-xml|red|0.20.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.5
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.27.0
php-pack|xde|1.0.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550
c4g48928:30513948

```

</details>

**Comment by alexr00** [comment]
https://github.com/microsoft/vscode/issues/152931#issuecomment-1163893711 should do the trick.
