### ISSUE TITLE
Visual studio code apresenta erro powershell foi terminado com o código de saída: 4294901760.

### ISSUE THREAD

**Issue by EVANDROMATOS2020** [microsoft/vscode#152916]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole.

**Comment by Tyriar** [comment]
Do you have anti-virus software that could be blocking the terminal? If so try following the instructions in https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch

/label "needs more info" terminal windows
