### ISSUE TITLE
Extension description renders misformatted workspace trust string

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#152984]
Steps to Reproduce:

1. Install the Volar extension in insiders.vscode.dev
2. :bug: see this workspaceTrust string below the Install / Disable buttons:
![image](https://user-images.githubusercontent.com/30305945/175338339-91dde7d6-f112-4185-92bb-34acb112ec0f.png)

**Comment by sandy081** [comment]
It seems the extension is not having nls value for this string. Hence transferred this issue - https://github.com/johnsoncodehk/volar/issues/1516
