### ISSUE TITLE
Text does not wrap properly when non-monospaced fonts are used

### ISSUE THREAD

**Issue by stullesha** [microsoft/vscode#152921]
Issue Type: <b>Bug</b>

Changing the default font in VS code (e.g. to 'Segoe UI' or Arial) makes it's word wrap to limit itself to 80 characters instead of the viewport width (see https://prnt.sc/fiGzMOCkNGNP)

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
language-hugo-vscode|bud|1.3.1
better-toml|bun|0.3.2
hugo-shortcode-syntax|kae|1.0.0

(1 theme extensions excluded)

</details>

**Comment by roblourens** [comment]
Probably a limitation of non-monospaced fonts
