### ISSUE TITLE
tree-work should be in `window` namespace

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15296]
The [proposed tree API](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.proposed.d.ts#L15) should be defined in the `window` name, but in `workspace`. The former is UX'is things (like status bar, editors eat) whereas the latter is for things that are related to currently open folder (like documents, search, settings)

**Comment by octref** [comment]
I feel it should be parallel to `workspace.registerTextDocumentContentProvider` though.

**Comment by jrieken** [comment]
Nope - it about UX not content
