### ISSUE TITLE
Control over CompletionItem for Snippet Choices

### ISSUE THREAD

**Issue by jinu-jang** [microsoft/vscode#152946]
Currently the Snippet supports a Choices syntax ([link here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice)).
The choices created this way do turn on a completion session, hence it would be great if we could actually control those CompletionItems being shown.

**Comment by jrieken** [comment]
>  hence it would be great if we could actually control those CompletionItems being shown.

I don't really know what you mean here?

**Comment by jinu-jang** [comment]
My bad. Going into further detail, currently in the Choices syntax, we can only provide a string value.
![image](https://user-images.githubusercontent.com/11640155/175666116-36fe561a-b123-4145-8ee9-fac71193c1bf.png)

However for regular CompletionItems, there are a lot more properties we can add to it. [link here](https://code.visualstudio.com/api/references/vscode-api#CompletionItem)

A couple examples would be being able to 
1. Add commands to run on acceptance of "normal" CompletionItems for telemetry purposes
2. Show a label different from the actual insert text
3. Add descriptions to the suggestion
![image](https://user-images.githubusercontent.com/11640155/175666918-64bf317f-c14e-42d5-a6d3-7781b75037d0.png)

**Comment by jrieken** [comment]
With snippets and its syntax we are sticking to Textmate itself - we don't want to be incompatible and extend the choice syntax. Therefore closing as-designed but you should know that you can always implement a completion item provider for such cases. Thanks
