### ISSUE TITLE
Word wrap falsly applied on load

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#15299]
- VSCode Version: 1.7.1
- OS Version: Sierra

Steps to Reproduce:

Default settings only

1. Open a file with a really long line (over 300 chars)

Expected: The line should not wrap as `editor.wordWrap` is set to `false` by default

Actual: The line does wrap. Toggling word wrap on and off again fixes the issue.

I was able to work around this by setting `"editor.wrappingColumn": -1`, but I'm not sure why this is necessary given the default setting of `editor.wordWrap`.

**Comment by alexandrudima** [comment]
| wordWrap | wrappingColumn | Behaviour
|-------------|--------------------|------------
| false | -1 | No wrapping whatsoever
| false | 0 | Wrap at column at viewport width
| false | N > 0 | Wrap at column N
| true | -1 | No wrapping whatsoever
| true | 0 | Wrap at column at viewport width
| true | N > 0 | Wrap at column `min(column at viewport width, N)`

We ship by default with `wordWrap = false and wrappingColumn = 300` which means wrap at column 300.
