### ISSUE TITLE
auto format js. spacing is wrong

### ISSUE THREAD

**Issue by relvao** [Microsoft/vscode#15292]
starting in v.1.7.1 auto format is going crazy. This happens after the editor has been open for some time. 

With the settings as spaces,2 it always formats as spaces,4. Restarting fixes the issue and code identifies that file as spaces,4 (which was never manually set) and changing it back now works again.

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-38-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.4|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.5.40|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
@relvao 'needs more info' Like, what file does this occur with?

**Comment by dylanparry** [comment]
I think this is describing the same issue as #15316

**Comment by jrieken** [comment]
ok - closing as dupe
