### ISSUE TITLE
Missing property "scope" in solarized light's package.json

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152972]
![image](https://user-images.githubusercontent.com/2193314/175305246-8893fa4f-f98e-4da6-8bb7-15017fb3db2f.png)

Version: 1.69.0-insider (user setup)
Commit: 668c538b8d2fec1258ed786ae212124d6d68023c
Date: 2022-06-23T05:16:43.681Z
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by aeschli** [comment]
It's actually allowed to have no scope (for the default fore/background), but the schema is too strict
