### ISSUE TITLE
the current version can't auto guess the right encoding 

### ISSUE THREAD

**Issue by scropothree** [microsoft/vscode#152944]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1 (user setup)
- OS Version: Windows_NT x64 10.0.19044

Issue Type: Bug 

Steps to Reproduce:

When I open a file with gbk encoding,  the current version vscode can't open it with right encoding,  and the old version works well.  I have both turn files.autoGuessEncoding to true.

I have noticed that the current version have new function "file.Encoding" in Files setting.  The default character set encoding to use when reading and writing files.
When i use the current version vscode, it has a strange phenomenon, When i turn a gbk file,  it will do one more refresh，before refresh, it guess the right encoding, after refresh, it goes wrong， It seem like use the  "file.Encoding" type finally.

I think when the "file.autoGuessEncoding" is true, the "file.encoding" should alse be automatically set to true. It will looks more reasonable.

**Comment by bpasero** [comment]
VS Code supports a wide range of file encodings. You can see the full list when you click on the lower right status bar where the encoding is shown and then choose to either reopen the file with a specific encoding or save the file with a specific encoding:

![image](https://user-images.githubusercontent.com/900690/33760971-db202986-dc07-11e7-8ca0-f8d8938cef7f.png)

There are two options how to configure the encoding for files

**Configure the encoding as a setting for all files or files of specific type**
We provide a `files.encoding` setting that you can use to set an encoding for all files. You can also configure this encoding for specific file types, e.g. like this:

```json
"[markdown]": {
    "files.encoding": "utf8"
}
```

**Configure VS Code to automatically detect the encoding when opening files**
We provide a `files.autoGuessEncoding` setting that you can enable to let VS Code detect the encoding of every file automatically. Note that this approach is known to not be accurate in all cases. This guessing of encoding is rather a heuristic that can produce wrong results (that is also why this setting is not enabled by default).

Please also check out issues that are already reported with the `files-encoding` label: https://github.com/Microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-encoding

**Comment by scropothree** [comment]
I know the `file.autoGuessEncoding ` function and it goes well in the past versions. Only the newest version dostn't work.

I found that int the April update, the `files.encoding` feature was added, which seems to conflict with `file.autoGuessEncoding`,
which is my problem.

**Comment by bpasero** [comment]
`files.encoding` was added ~6y ago, not in April.

**Comment by scropothree** [comment]
On. sorry, i got it wrong. the April version show some fixes with the `files.encoding`.
I will get more information for my question.

**Comment by scropothree** [comment]
I got a screen record for my question. video url: https://streamja.com/O4PAn

When I open the gb2312 file, it goes well first, it seem like it find the right encoding, but the vscode will refresh and then it show the wrong encoding utf-8.
Then I choose the encoding status bar manually,  it show gb2312(guessed from content). Choose it manually, the file looks well.
Check the settings, the `file.autoGuessEncoding` has been turned on.

**Comment by bpasero** [comment]
What are your settings exactly? Also maybe the workspace overrides some settings?

**Comment by scropothree** [comment]
I turned it on both workspace and user.

![image](https://user-images.githubusercontent.com/52093123/175244612-bd0b1081-fa22-4928-ba5a-acdb2b0716b6.png)

**Comment by bpasero** [comment]
Yeah I was wondering about `files.encoding` setting too.

**Comment by scropothree** [comment]
The question is happened when the file was on windows platform, I just try another clone of the same code, it was on linux samba shared,  the  `file.autoGuessEncoding` works quite well.
Both `file.autoGuessEncoding` and `files.encoding` setting are same.

This question looks like some setting overrides the environment. But i can't find it out.
Even I reinstall vscode, it looks same.

**Comment by scropothree** [comment]
OK， i will try and give feedback.

**Comment by scropothree** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

The insider version works well. Looking forward to the official release.

**Comment by scropothree** [comment]
This version has the same problem.

![image](https://user-images.githubusercontent.com/52093123/175257828-84a1c009-e611-42ea-8468-29382579ab97.png)

**Comment by bpasero** [comment]
How about in a different folder with a different project?

**Comment by EzWinner** [comment]
I encountered a similar situation. 
When I starting up VS Code and loading unclosed files, encoding guessing fails sometimes. Log window outputs "[renderer1] [info] Adjusting encoding based on configured language override to 'gb2312' for ...".
This failure does not happen every time, but if I start up VS Code after Visual Studio 2022, it happens almost every time.

**Comment by scropothree** [comment]
> How about in a different folder with a different project?

In my pc computer, it happened in every project, but the same file in other computer,  some will have happen the problem and others will not.I still can't find the regularity.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/127936#issuecomment-1084514937 might be relevant, a relatively recent change, but it needs a setting for encoding based on language and it requires opening a new instance of VSCode on a file.

**Comment by bpasero** [comment]
@scropothree can you send me the file where the encoding is guessed wrongly? and let me know what the correct encoding would be?

To clarify, encoding guessing is done via a 3rd party library and is not guaranteed to work in all cases: https://github.com/aadsm/jschardet

**Comment by scropothree** [comment]
Here is the file [netpt_app.h](https://drive.google.com/file/d/1zXOj4wOm4iBWFNaxFmm_hGjn6xpdypfo/view?usp=sharing).

And now I have installed version 1.66.2 ,  the "auto guess encoding" function works quite well.

**Comment by bpasero** [comment]
@scropothree thanks. To rule out this is related to settings can you do this:
* copy the file to a folder `C:\Users\scroppothree\Desktop\newfolder`
* close all instances of VSCode
* open a windows command prompt
* run `code --disable-extensions --user-data-dir <some other empty directory>`
* this should open a fresh unconfigured instance of VSCode
* in settings enable encoding guessing
* File - Open File - `netpt_app.h`

Does the encoding work?

**Comment by scropothree** [comment]
I have tried to uninstall the version 1.68.1 and delete the vscode config files, then reinstall, it doesn't work.
And now  I  just only uninstall the version 1.68.1,  reinstall the version 1.66.2, it works well.

Now I will be tend to use the version 1.66.2, thanks for you help.
