### ISSUE TITLE
Use "Option-key" in open recent on macOS

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#152989]
This seems more correct on macOS.
![image](https://user-images.githubusercontent.com/2193314/175340053-74d24dde-bf06-4d03-ae99-d41a01a786b8.png)

I'm adding a very similar placeholder in https://github.com/microsoft/vscode/pull/152988 so I'd like to make sure they're aligned.

**Comment by bpasero** [comment]
No, `Cmd` is being used as "alternate opening" also for quick pick, I would be careful to change muscle memory here.

Agree though that maybe `Cmd` was not the best choice for macOS. However the intent was to align it with the `Ctrl` key that is used on Windows/Linux.

**Comment by bpasero** [comment]
Hm, actually we support both `Cmd` and `Alt` key to open to the side in quick pick...

**Comment by bpasero** [comment]
I guess this picker is really special in that it has a keybinding modifier for the one action and for the other.

**Comment by bpasero** [comment]
Ah this is only about the string, fair enough 👍
