### ISSUE TITLE
Relative path to workspace in title bar

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode#15291]
Since a few days it seems to be possible to show the full path in the title bar in the insider builds.  
This is already really helpful when figuring out where I am currently at in my codebase but most of the times the full path seems to be too much information in my opinion. A solution to this problem could be another option to only show the path starting from the workspace directory.

Example: I have a folder called `my-app` which is located in the folder `~/Development`. When I open a file located in `src/foo/bar/index.js` for example, I can either display the full path (`~/Development/my-app/src/foo/bar/index.js`) or just the filename (`index.js`).  
With the proposed addition the title could be reduced to `src/foo/bar/index.js` which in a lot of cases contains the information I am looking for when I look at the path of a file.

**Comment by bpasero** [comment]
Lets merge into https://github.com/Microsoft/vscode/issues/1723. If we provide full control of the title, the relative path could be one of the variables to pick from.
