### ISSUE TITLE
Provide a command to create a new untitled file with a specific language set

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#152920]
VSCode provides `workbench.action.files.newUntitledFile` using which we can create a new untitled file, which then instructs to set a particular language:

![newcreatepythonfile](https://user-images.githubusercontent.com/13199757/174663063-ceba64af-1857-4df3-af6d-631c0ac80a84.gif)

We're working on our walkthrough in Python extension which directly offers to create a new python file, it would be great if the command supports an argument which accepts the language to create the file for.

cc/ @lramos15

Unfortunately we cannot use VSCode APIs to accomplish this as extension is not guaranteed to be activated when the walkthrough is opened, so the command isn't available when the button is clicked, see:

![weirdcreatepythonfileexp](https://user-images.githubusercontent.com/13199757/174662992-0640bfc6-8edf-4edb-aeb7-e4db44d30f2b.gif)

**Comment by bpasero** [comment]
Can you not use this API?

https://github.com/microsoft/vscode/blob/96ca51210fbacfd74a5f49917633389d9b89ca2b/src/vscode-dts/vscode.d.ts#L12290

**Comment by karrtikr** [comment]
Extension takes some while to activate, so any commands we register ourselves using the API aren't available at startup.

**Comment by bpasero** [comment]
I am a bit confused, how can there be a python specific welcome command without the python extension?

**Comment by karrtikr** [comment]
> I am a bit confused, how can there be a python specific welcome command without the python extension?

Opening python specific getting started doesn't require a command, it uses `package.json` directly so extension doesn't need to be activated.

**Comment by karrtikr** [comment]
> I think such a change would be relatively easy, similar to the view type argument:

That's great. Just to doublecheck, is it possible to call `workbench.action.files.newUntitledFile` with arguments in `package.json` directly?

**Comment by bpasero** [comment]
Hm, I am not entirely sure, @sandy081 do you know? Or @jrieken?

**Comment by jrieken** [comment]
> Just to doublecheck, is it possible to call workbench.action.files.newUntitledFile with arguments in package.json directly?

You mean define a keybinding for said command with arguments or how/where are the arguments defined? Technically you don't "call" a command from package.json, you can only reference them

**Comment by lramos15** [comment]
> > Just to doublecheck, is it possible to call workbench.action.files.newUntitledFile with arguments in package.json directly?
> 
> You mean define a keybinding for said command with arguments or how/where are the arguments defined? Technically you don't "call" a command from package.json, you can only reference them

I believe kartik is referring to a command link in the statically defined walkthroughs within the package.json

**Comment by karrtikr** [comment]
> I believe kartik is referring to a command link in the statically defined walkthroughs within the package.json

Yes

> Technically you don't "call" a command from package.json, you can only reference them

Right, can I reference such a command with arguments in walkthroughs within `package.json`? In this case it would be something like:
```
[Create Python File](command:toSide:workbench.action.files.newUntitledFile?<args>)
```
where `<args>` refers to args to command which instructs to open a python file.

**Comment by yume-chan** [comment]
> can I reference such a command with arguments in walkthroughs

Yes, for example GitLens does this:

https://github.com/gitkraken/vscode-gitlens/blob/7b5205412dc333b7bc744ca00011f73e3304cfa2/walkthroughs/getting-started/1-setup.md?plain=1#L9

```md
[GitLens: Welcome (Quick Setup)](command:gitlens.showWelcomePage?%22quick-setup%22)
```

---

> where <args> refers to args to command which instructs to open a python file.

No, `workbench.action.files.newUntitledFile` doesn't support specifying language in args.

https://github.com/microsoft/vscode/blob/c12c8c1a688ac7f64e862c6c950033cf2c7c7bee/src/vs/workbench/contrib/files/browser/fileCommands.ts#L625-L644

---

> as extension is not guaranteed to be activated when the walkthrough is opened

You can activate your extension when the command is invoked. GitLens also does this:

https://github.com/gitkraken/vscode-gitlens/blob/7b5205412dc333b7bc744ca00011f73e3304cfa2/package.json#L89

```
"activationEvents": [
    "...",
    "onCommand:gitlens.showWelcomePage",
    "..."
]
```

**Comment by karrtikr** [comment]
> Yes, for example GitLens does this:

Gotcha, thanks. I assume it's URI encoded.

> No, workbench.action.files.newUntitledFile doesn't support specifying language in args.

That is what this feature request is for :)

> You can activate your extension when the command is invoked. GitLens also does this:

We don't have our own specific open walkthrough command, so our walkthrough is opened before commands finish registering, i.e our command may not be registered by the time `Create Python File` is clicked.

**Comment by bpasero** [comment]
Open for a contribution after validation it works from welcome 👍

**Comment by jrieken** [comment]
@karrtikr Just fyi that the "format" of such arguments is the following: JSON.stringify the arguments, then  encodeURIComponent the result, and use that as URI query.
