### ISSUE TITLE
captouring group support in search and replace

### ISSUE THREAD

**Issue by NikosEfthias** [Microsoft/vscode#15295]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.8.0-27-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|calc|BorisA|0.0.1|
|vscode-qrcode|Compulim|0.2.0|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|code-settings-sync|Shan|2.3.7|
|vscode-wakatime|WakaTime|1.0.6|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.10.0|
|path-intellisense|christian-kohler|1.1.0|
|regex|chrmarti|0.0.6|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|vscode-hasher|deerawan|1.0.1|
|RelativePath|jakob101|0.11.0|
|Go|lukehoban|0.6.48|
|font-awesome-codes-html|medzhidov|0.0.3|
|gitignore|michelemelluso|1.0.1|
|prettify-json|mohsen1|0.0.3|
|easy-less|mrcrowl|1.2.5|
|partial-diff|ryu1kn|0.1.0|

---

Steps to Reproduce:

1.i have
 ```js
res.render("something",{
type:"error:"
code:1
})
```
2.i want to change code to errorCode on every occurance so i wrote the regex `render("something"[\s\S\n]*?(code)` 

3. when i click replace it replaces entire match including code with errorCode rather than just the match

**Comment by sandy081** [comment]
@NikosEfthias May I know if you are using Search view on the left, or Find widget in the Editor for this?

**Comment by NikosEfthias** [comment]
the find view by pressing `ctrl+f`

**Comment by alexandrudima** [comment]
This can be done with the search string:
* `(render\("something"[\s\S\n]*?)(code)`
* regex turned on
* replace string: `$1errorCode`

The first parathesis group captures everything up to `code` in $1 and that will be maintained and the `code` will be replaced with `errorCode`.
