### ISSUE TITLE
When can support Razor IntelliSense in ASP.NET 5?

### ISSUE THREAD

**Issue by gejinlove** [Microsoft/vscode#153]
When can support Razor IntelliSense in ASP.NET 5

**Comment by rhires** [comment]
+1 - chiming in so I can follow this one. Drives me crazy no razor help for .cshtml files. This is core for mvc cross platform stuff. I would really like to have it!

**Comment by gejinlove** [comment]
who can help me ..

**Comment by rhires** [comment]
This is Open Source, and "scratch your own itch" is definitely the way to go here. I don't have any answers, and currently I will live with it not working...perhaps you could go over to the razor repo and see if they have any thoughts on how to integrate razor with a now Open Source vscode...

**Comment by gejinlove** [comment]
@rhires ,thx!

**Comment by mjbvz** [comment]
Closing as razor support could be added by an extension
