### ISSUE TITLE
Intellisense space issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#15300]
- VSCode Version: Code - Insiders 1.8.0-insider (a28dc215af3146d827d4b2f46a3191e2d487efde, 2016-11-10T07:05:12.185Z)
- OS Version: Darwin x64 16.1.0

---

Steps to Reproduce:

Typescript file:

```ts
test()

/**
 * This
 * 
 * is a test
 */
function test() {

}
```

Notice how popup shows 'isa test' when you hover `test()` in first line:

![image](https://cloud.githubusercontent.com/assets/1723815/20180212/879501c6-a727-11e6-8e0b-e8eeee4ab149.png)

**Comment by waderyan** [comment]
Hmm.. I can't reproduce. Anything special about your project?

**Comment by wallverb** [comment]
@waderyan 

I just started vscode - no project and created Typescript file

![7w5mmcamb0](https://cloud.githubusercontent.com/assets/1723815/20234383/5e2fe2f2-a848-11e6-9b9f-1031b9614935.gif)

Not sure if related - but I'm using Typescript `2.2.0-dev.20161111`

**Comment by waderyan** [comment]
Confirmed with 2.2.0-dev.20161111

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12236
