### ISSUE TITLE
New window default position out of screen when an extern/secondary screen is connected

### ISSUE THREAD

**Issue by KarimH22** [microsoft/vscode#153086]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.68.1 (user setup)
- VS Code Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
- OS Version: Windows 10

Steps to Reproduce:

1. Connect to your laptop to a secondary screen (physically higher size that main screen)
2. Open Microsoft Visual Code (position the new window as full screen)
3. Go to File / New Window
![MSvisualcode_defaultnewwindow_withsecondaryscreen](https://user-images.githubusercontent.com/67599345/175500806-4e8165fb-cca7-4b7c-8a0b-f7dcee12df9f.jpg)

Issue:
With default New Window  dimensions, the top of the window is always out of screen (in the main screen 14"), it is really borring.
My screen is set to 1920x1080 and it is 14" size, the secondary screen is 23.8" and set also to 1920x1080.

To resolve it temporaly I changed settings to inherit.
I have not found on the Internet any clue to fix it, is the default value hard coded ? no possibilty to set its own default position ?

Looking the attached file, you can see in the screenshot (main screen 14"), the full window in the background underlines that the new window is out of screen.
The issue does not happen on the secondary screen (23.8").

thanks

**Comment by bpasero** [comment]
This is likely caused by different DPI settings on the secondary monitor, see https://github.com/microsoft/vscode/issues/115768 and friends.
