### ISSUE TITLE
Allow to copy workspace relative path of file from explorer

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15306]
- VSCode Version:  1.8.0-insider (1.8.0-insider)
- OS Version: 10.12.1 (16B2555

In addition to the Tree sidebar having "copy path" (which returns the entire disk path), it would be nice to additionally have "copy project path" (which would be the relative path from project root).

Atom has this, and it's very useful.

**Comment by rohmanhm** [comment]
Please work on this quickly.
I'm decide to love work using vscode, but when I know it can't copy relative project path maybe later

**Comment by sporto** [comment]
There is an extension for this https://marketplace.visualstudio.com/items?itemName=alexdima.copy-relative-path

But it doesn't work for me (Linux)

**Comment by rohmanhm** [comment]
@sporto This extension work for me (macOS) https://marketplace.visualstudio.com/items?itemName=bgse.relative-path-and-line

**Comment by sporto** [comment]
@rohmanhm 	thanks, doesn't work in linux unfortunatelly, VSCode at least shows an error instead of failing silently

**Comment by OliverJAsh** [comment]
I've tried all the extensions for this, and the best one I found was https://github.com/enochcheung/copy-relative-path

**Comment by smlombardi** [comment]
@OliverJAsh This is nice, but it can only copy the active file.  it cannot work in the tree with a right-click like the built-in "copy path".  So it requires you to open the file in question before you can copy the path.  

This doesn't save much time over right-click, copy path, paste in code, delete the extraneous start of path.

Also, and I'm not sure how this could work, but in most apps the root folder is not the actual path needed.  For example, our projects are similar to

> root
> -- build
> --app
> ---index.html
> ---js
> ----relevant-code.js

So, to link `relevant-code.js` to my index file, I need the relative path `js/relevant-code.js` but this extension returns `app/js/relevant-code.js`, which is wrong.  I need to edit the path anyway -- so I might as well stick to the default "copy path" command.

I hope at some point smarter minds than mine can come up with a way to simplify this process.

**Comment by artivilla** [comment]
Shouldn't this be an inbuilt feature? Happy to use an extension but imagine an extension for all keybindings. 🤔
