### ISSUE TITLE
VS code fails to authenticate with github via source control

### ISSUE THREAD

**Issue by mcunkelman** [microsoft/vscode#153015]
I have setup and verified the ssh keys to Github work. I can clone, pull (as evidenced in the terminal from my screen capture) in the terminal within VS Code. But the source control fails to pull from the same repo. This is via an SSH connection on the remote extension. The screen capture below shows me successfully sending a git pull command via terminal on the remote host, and the error I get when selecting pull from the same repo / host in source control. 

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/35158119/175376410-2d2d8e06-3647-4e3e-837a-2e1f2235801d.png">

**Comment by mcunkelman** [comment]
Is there something I am missing on where the Source Control module is looking for the ssh key?

**Comment by mcunkelman** [comment]
It looks like adding the following to ~/.ssh/config fixed this issue, I am still unclear on why terminal authentication worked and the source control failed.
`Host github.com
  HostName github.com
  IdentityFile <absolute path to private key`

**Comment by lszomoru** [comment]
@mcunkelman, apologies for not getting back to you on this until now. It seems to me based on your comments that you were able to resolve the issue so I will go ahead and close it as part of our yearly housekeeping effort. Please feel free to reopen the issue in case you still have any questions or concerns. Thanks!
