### ISSUE TITLE
Auto Format pasted/moved code

### ISSUE THREAD

**Issue by moyascii** [Microsoft/vscode#15301]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. When you move a line, sort the code

**Comment by aeschli** [comment]
Can you add a small code sample and the steps to reproduce.
Please also describe what you expect to see.

**Comment by wprater** [comment]
I think he may be referring to when you move lines in Atom it will ident the code as you're moving the text.  It's quite nice, actually.

**Comment by ramya-rao-a** [comment]
@jrieken Feature Request or extension candidate?

**Comment by jrieken** [comment]
actually a dupe of https://github.com/Microsoft/vscode/issues/13945
