### ISSUE TITLE
Feature Request: Vertical select at the end of line

### ISSUE THREAD

**Issue by ducdigital** [microsoft/vscode#15308]
- VSCode Version: Future
- OS Version: Mac OS X

**Sublime implementation:** 
![xzi4b](https://cloud.githubusercontent.com/assets/1712140/20185075/03fa2028-a76b-11e6-925e-a793d7851099.gif)

Hello vscode team, 

I really like the app however there are few things that really frustrate me. One of that is if you `Alt + Shift + left mouse`  and select the end of line, it will only select the end of line for longer line compare to the one you select.

Some time it is very furstrated to select lot of lines like this.

Thank you

**Comment by alexandrudima** [comment]
workaround: make a selection, press `alt+shift+i` (Create Multiple Cursors from Selected Lines or in the menu Add Cursors to Line Ends)
