### ISSUE TITLE
Open File/Folder/Workspace dialog opens in background after first time use

### ISSUE THREAD

**Issue by bahag-klickst** [microsoft/vscode#153072]
Issue Type: <b>Bug</b>

Hej all,

I am on Fedora Workstation 36 using the latest vscode version (1.68.1) and face a problem with the open dialogs opening in the background.
This error is reproducible all the time.
Steps to reproduce:
1. Open vscode
2. Open Folder/File/Workspace dialog. For the first time, it will open in the foreground and one can easily search the file/folder/workspace and open it.
3. Open Folder/File/Workspace dialog again. As this is the second time (or any other time after the first time usage), the dialog opens in the background and one has to switch the window to see it.

This is kind of annoying, as it worked with all previous versions on Fedora Workstation 36 like a charm.

Best Regards,
Tim

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.18.5-200.fc36.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.31GB (4.72GB free)|
|Process Argv|--unity-launch --crash-reporter-id b8e98bf0-3576-45d4-93f8-2edb058481a8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.47.0
gitlens|eam|12.1.1
vscode-pull-request-github|Git|0.44.0
terraform|has|2.23.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
vscode-yaml|red|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30515787
vsclangdf:30486550
c4g48928:30515882

```

</details>

**Comment by saiballo** [comment]
Same problem with Ubuntu Mate 20.4 and vscode 1.68.1

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
