### ISSUE TITLE
Jupyter Notebook automatically scrolls downwards upon cell execution (shift+enter)

### ISSUE THREAD

**Issue by davidleejy** [microsoft/vscode#153014]
Does this issue occur when all extensions are disabled?: require the Jupyter extension for this report.

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.5.0

**Jupyter Notebook automatically scrolls downwards upon cell execution** (see attached video):

https://user-images.githubusercontent.com/1690072/175372948-3cfa0e25-4391-4fe8-aa9e-6e24076a1e90.mov

I haven't found a way to disable this scrolling behavior and have experienced this for years. My mouse-wheel scrolling finger feels the strain from excessive scrolling when using vscode's notebook interface.

In the case where the cell after the executed one is a _short_ one, the user experience is _fine_ because the automatic scrolling kind of focuses on the output. However, if the cell after the executed one is _long_ (as is the case in the video), what tends to happen is that the scrolling makes the next cell's top border occupy the top of the view -- _troubling_ the user to scroll up to resume work on the executed cell. 

Over time, the _time & effort_ spent on scrolling back up adds up and can be _frustrating_ for a user working in notebooks for 8 hours+ daily.

Maybe of interest, this auto scrolling behavior does not occur when the play button is clicked (instead of using shift + enter to execute cell):

https://user-images.githubusercontent.com/1690072/175374939-e13b6f5d-a79a-4b44-9557-67ead22bd662.mov

Would be great if there were a way of disabling this behavior.

**Comment by roblourens** [comment]
You can use ctrl+enter to execute instead of shift+enter (and switch up your keybindings, if you want), is that what you want? Or do you still want it to select the next cell but not reveal it?

**Comment by davidleejy** [comment]
Thanks @roblourens. ctrl+enter is what I was looking for. Am happy to close this issue if there's nothing else.
