### ISSUE TITLE
Alert sound occurs when using keyboard shortcut on Mac

### ISSUE THREAD

**Issue by yamatsum** [microsoft/vscode#153061]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.68.1 (Universal)
- OS Version:macOS 12.4

Steps to Reproduce:

1. ctrl + /
2. alert sound occur

I want to comment out with `ctrl + /` as well as windows in mac environment.
Assigning a shortcut works but makes a sound.
Even if I didn't assign a shortcut, I heard a sound, so I don't think it's a setting issue.

Maybe it's a problem on the electron side

**Comment by omkarshinge** [comment]
I think this issue is similar to #44070 which has workaround to disable beep sound

**Comment by yamatsum** [comment]
The following settings worked fine.
Is there a plan to support it on the vscode side?

keybindngs.json
```
  {
    "key": "ctrl+/",
    "command": "editor.action.commentLine",
    "when": "editorTextFocus && !editorReadonly"
  }
```

~/Library/KeyBindings/DefaultKeyBinding.dict
```
{
  "^/" = "noop";
}
```

**Comment by rzhao271** [comment]
This issue is actually a macOS system issue; it also occurs in Finder. See this [Chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=916460) for details along with a workaround.
I'll be marking this issue as wontfix because it is not specific to this product.
