### ISSUE TITLE
Test: manual launching of multiple debug processes

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#15305]
- [x] OS X  **@jrieken** 
- [x] Windows **@roblourens** 

complexity: 4

As requested in https://github.com/Microsoft/vscode/issues/14338 we now support starting multiple debug sessions by clicking on the debug start action multiple times. Have a workspace with mutiple launch configurations and verify:
* You can start multiple debug sessions via debug start action (you can only do this if you try to launch different configurations)
* Once you are debugging two processes a dropdown appears in the floating debug actions widget
* Switching processes via this dropdown opens the appropriate stack frame in the editor and all debug actions get scoped for that process
* Clicking on the stack frames in the call stack view opens those stack frames in the editor and all actions get scoped for the process of that stack frame
* Each Process and Thread show their status in the call stack view

**Comment by jrieken** [comment]
I am not really able to test this because of #16596

**Comment by isidorn** [comment]
@jrieken makes sense, we should first fix that issue. Sorry about that

**Comment by isidorn** [comment]
That issue is now fixed, builds should be out of the oven soon so this can be tested
