### ISSUE TITLE
Experimental markdown validate doesn't work for local links without file extension specified if file name contains period `.` characters

### ISSUE THREAD

**Issue by krowlandson** [microsoft/vscode#153094]
Does this issue occur when all extensions are disabled?: `Yes`

- VS Code Version: (see below)
- OS Version: (see below)

```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22000
```

Steps to Reproduce:

1. Enable the markdown experimental validation feature: `"markdown.experimental.validate.enabled": true`

1. Create three markdown pages:
    1. `readme.md`
    3. `readme_test.md`
    4. `readme.test.md`

1. In `readme.md` add the following content:

    ```markdown
    - [link to readme_test with working validation](readme_test)
    - [link to readme_test.md with working validation](readme_test.md)
    - [link to readme.test with broken validation](readme.test)
    - [link to readme.test.md with working validation](readme.test.md)
    ```

1. Take note of the validation error as shown below:

    ![image showing markdown experimental validation error on link containing multiple period characters](https://user-images.githubusercontent.com/12268562/175515841-2d861316-40e6-4ac6-8f87-6c4f9c36c08c.png)

### More information

As you can see, this validation error only occurs in one scenario. Although the obvious answer may seem to just specify the file extension, unfortunately this isn't suitable in certain scenarios.

In my case, I am creating relative path links to pages within a Wiki on my GitHub repository. Specifying the file extension results in the `raw` page being displayed, rather than the rendered content.

Obviously, this isn't what we want when creating content, but I don't want to have to suppress these errors.

Your help resolving this issue would be greatly appreciated.

**Comment by babakks** [comment]
@mjbvz I take this.

**Comment by babakks** [comment]
@mjbvz I've just submitted the PR. Could you please check it?

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode-markdown-languageservice/commit/465847dc6dd26fcad4b47d8c35549f5b7eb4c02a

**Comment by roblourens** [comment]
If you are able to validate those links, then should clicking the link go to the right place? Clicking `readme.test` should go to `readme.test.md` but just tries to open `readme.test` 
<img width="477" alt="image" src="https://user-images.githubusercontent.com/323878/186286771-bf4e0568-9b89-4065-bebb-88e094b73cae.png">
