### ISSUE TITLE
Unsaved data lost upon using 'reload window' 

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#153018]
Issue Type: <b>Bug</b>

When using any file, if the 'developer: reload window' command is run, all unsaved data/code is lost. 

In settings I had autosave turned off, hotexit setting as `    "files.hotExit": "onExitAndWindowClose"`
Seems like issue maybe with hotexit?

VS Code version: Code - Insiders 1.69.0-insider (668c538b8d2fec1258ed786ae212124d6d68023c, 2022-06-23T05:16:43.681Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.66GB free)|
|Process Argv|. --crash-reporter-id 62122f1b-5534-43ca-aa21-fca29c482163|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.3
gitlens|eam|12.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.9.11741005
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.6.1001761035
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506
841h4636:30513947

```

</details>

**Comment by bpasero** [comment]
I cannot reproduce, did you do this from an extension development window?
