### ISSUE TITLE
High CPU usage of notebook renderer when reopening notebook with folded section 

### ISSUE THREAD

**Issue by TLouf** [microsoft/vscode#153021]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

Create a Jupyter notebook, add one markdown section cell (`# Test` let's say) and one subsection (`## Test`). Fold the section, close the tab, reopen, all the while monitoring CPU usage (with `htop` for instance). What I see is very high CPU usage from `code`'s notebook renderer (a whole core on my laptop) after reopening the notebook with the folded section, which seems never to go back down to a normal level. After unfolding, CPU usage goes back to normal.

I actually had to hunt down this issue because I saw high CPU usage without understanding why, and found out the origin I've just described above by chance. As I organize most of my notebooks with sections, this is an issue I encounter quite regularly. Now that I know a solution (unfolding the section) it's not too much of a bother, but I imagine that for other users experimenting this without knowing why, it must be frustrating.

### VS Code Version

Version: 1.68.1

### Jupyter Extension Version

v2022.5.1001610507

**Comment by bpasero** [comment]
@IanMatthewHuff when you transfer issues to VSCode repo, please also assign an owner, otherwise issues are not getting triaged.

**Comment by rebornix** [comment]
It's possible that for the notebooks being used by @TLouf is complex to scan for headers in the markdown content (which contributes to the computation of the folding model). However I'm not able to reproduce this issue. It would be great if @TLouf can share a notebook that can help me troubleshoot.

**Comment by TLouf** [comment]
Well same for me, I cannot reproduce anymore, it must have been fixed somehow. Sorry you spent time looking into it now it's not an issue anymore!
