### ISSUE TITLE
Select all files in search results and be able to copy, delete

### ISSUE THREAD

**Issue by u84six** [microsoft/vscode#153040]
I haven't been able to figure this out, but I would really like a way to be able to select all files from a search result. For example, if I want to delete all files that contain a certain string, I can do a search, then select all in the search pane and then right-click delete.

**Comment by roblourens** [comment]
I don't really want to include this kind of feature because I think it's unexpected and more likely to be triggered by accident. Some day an extension could implement this behavior - not currently possible, we need to finish search API first.
