### ISSUE TITLE
Warn users that their default editor will be affected when installing on Windows 10

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#15304]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Run the installer on Windows 10.
2. See that `Register Code as an editor for supported file types` is checked by default, with no warning about any consequences of leaving it checked.
3. After installation, try to open any affected file-type and your default editor will no longer open automatically. Instead you will receive the Windows dialog that asks what program to open the file type with.

I don't know if anybody at Microsoft is still using Windows, but it's really annoying to have all of your default file openers reset. Especially for a programming tool that affects about 20 or 30 different file types that I use on a regular basis like `*.js, *.css, *.less, *.jade, etc.`.

**Comment by waynebloss** [comment]
Original issue: #15252

**Comment by joaomoreno** [comment]
A quick google search shows that, unfortunately, this is a Windows issue which seems to hit many users:

http://www.tenforums.com/windows-updates-activation/40373-last-update-caused-all-custom-file-associations-reset-defaults.html

http://superuser.com/questions/1022063/windows-10-default-programs-keep-changing

It also shows that it is not entirely a Code issue. It applies to any application that has file associations. Think about VLC, iTunes, PowerPoint. Are all those affected by this?

**Comment by waynebloss** [comment]
There's something very simple that VS Code can do about it though.

Given the really, really annoying consequences of leaving that one checkbox checked - I would make VS Code either:

- Not leave the checkbox checked by default.
- Change the verbiage of the checkbox label to warn the user that simply "registering" Code as a handler will cause all affected file types to no longer automatically open with their previous default handler.

Or both.

**Comment by joaomoreno** [comment]
I've remove the checked by default.

I've also started an email thread internally to figure out who is screwing up here.

**Comment by roblourens** [comment]
@joaomoreno Still seeing this checked by default in the latest Insiders installer - 
![image](https://cloud.githubusercontent.com/assets/323878/21024362/0c6f5564-bd39-11e6-927b-9ab56a4cf1c5.png)

**Comment by roblourens** [comment]
Nvm, I removed my existing installation then ran the installer again, now that option and the context menu options are correctly unchecked.
