### ISSUE TITLE
Green light bulb not showing.

### ISSUE THREAD

**Issue by Viking1983** [Microsoft/vscode#15307]
Hello,
after last VSC update, green light bulb not showing when I create any js file in empty project folder. 
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04

Steps to Reproduce:
1. Open empty folder
2. Create js file.
![green_light_bulb](https://cloud.githubusercontent.com/assets/12736118/20185019/ceeb7544-a76a-11e6-802a-e442971c8c3d.png)

**Comment by jrieken** [comment]
@Viking1983 We are removing this feature

**Comment by mjbvz** [comment]
Yes, the removal work was tracked by #15205 with the actual removal going in with #15213

**Comment by seanfisher** [comment]
@jrieken @mjbvz Can the docs be updated? https://code.visualstudio.com/Docs/languages/javascript still shows using the light bulb.

**Comment by jsynowiec** [comment]
Does it means that `jsconfig.json` file is not required anymore for JavaScript-only projects?
