### ISSUE TITLE
Loss authenticate Sync/Github Copilot

### ISSUE THREAD

**Issue by und3fined** [microsoft/vscode#153064]
Does this issue occur when all extensions are disabled?: Not sure

- VS Code Version: 1.68.1 and 1.69.0 - Insider
- OS Version: macOS 13 dev beta 2

Steps to Reproduce:

1. Open VScode
2. Notification re-login to Github account.
3. Click to `Signin` and back to VScode. Authenticated.
4. Reload windows or Close and open VScode.
5. Re-login notify back.

<img width="338" alt="Screenshot 2022-06-24 at 10 41 48" src="https://user-images.githubusercontent.com/2163878/175457902-c8ef6dd3-1ef6-42bd-8e1a-9ebd2debf598.png">

**Comment by alexanderniebuhr** [comment]
@und3fined I just submitted another issue yesterday about this. https://github.com/microsoft/vscode/issues/152964, it could be beneficial for the team to know if this is a duplicate

**Comment by und3fined** [comment]
@alexanderniebuhr  thanks for map to your issue. I have same problem
