### ISSUE TITLE
How to get the "before" text from TextDocumentContentChangeEvent ?

### ISSUE THREAD

**Issue by lovettchris** [microsoft/vscode#153054]
I'm implementing something that needs "anchored selection" (a.k.a bookmarks) and I want the bookmarks to track the edits in the document so their line/char position moves correctly based on prior edits in the file.  See attached.

But when TextDocumentContentChangeEvent arrives, how do I get the previous text from the document that existed before this edit event?  Surely, I don't have to keep my own entire shadow copy of the document to compute this?  Does VS Code API already provide a bookmark/anchor/trackingselection kind of API?  If so, I couldn't find it...

Thanks

[bookmarks.zip](https://github.com/microsoft/vscode/files/8972014/bookmarks.zip)
.

**Comment by alexdima** [comment]
This has been requested before. Let's track at https://github.com/microsoft/vscode/issues/54147
