### ISSUE TITLE
When disable the Spell, you can't back to the "Enable" Mode

### ISSUE THREAD

**Issue by cidisaac** [Microsoft/vscode#15302]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|Spell|seanmcbreen|0.8.6|

---

Steps to Reproduce:

1.Click on Enable Spell to Diable it
2.Try to Enable again

**Comment by sandy081** [comment]
@cidisaac In the latest insiders, I improved the behaviour to revert back the action. It means, if you disable an extension and you can revert it back by clicking enable action before restarting VS Code.
