### ISSUE TITLE
Hope to add an Access Key to the right-click menu item

### ISSUE THREAD

**Issue by x7890** [microsoft/vscode#153075]
On Windows systems, menus such as "Open" have access keys such as "&O", so that right clicking and directly typing "O" can be equivalent to clicking the menu, eliminating the process of moving the mouse to click the menu twice as the position and length of the menu changes.

I hope to add an Access Key for "Open with VsCode", such as "&Q". I think this key is basically not occupied by other programs. In this way, I can right-click a file or folder and then directly press "Q" to open vscode. I don't need to find out where the VsCode menu is or move the mouse twice, which can improve efficiency.

Programmatically, I want to execute the following code (or equivalent registry form) in the installation package of vscode:
```
reg add "HKEY_CLASSES_ROOT\*\shell\VSCode" /ve /d "Open with Code(&Q)" /f
reg add "HKEY_CLASSES_ROOT\Directory\Background\shell\VSCode" /ve /d "Open with Code(&Q)" /f
```

The first line above is the right-click of the file, and the second line is the right-click of the folder. Please note that I simply added "(&Q)" Access Key after the original strings, which can achieve my goal.

Currently, I have created a batch file to rewrite them. This does not require administrator privileges. However, you are so diligent in updating that each update will overwrite the right-click menu. It's certainly commendable, but I still sincerely hope you can provide this convenient function.

Note: the above strings are in English, and I'm using the Simplified Chinese version.

**Comment by joaomoreno** [comment]
First, I'm happy that you found a nice workaround. Too bad you have to run it after every update, but I'm sure you'll find a way to automate it.

As a general concept, I really don't think this is a great idea:

1. Q might not be used by any other programs in your machine, but it will certainly be used by programs in other users' machines.
2. Doing this will display the menu item as `Open with Code(Q)`, which is awful default behavior and will surely spawn issues from users complaining about it.

For those reasons, I'll close this as won't implement. Sorry about that.

**Comment by x7890** [comment]
Thank you for your patient reply. Although your absolute reason cannot convince me in objectivity, it is your freedom. I respect your prudent decision and withdraw my unimportant suggestion. I also wish you can put your energy into something more important and make VSCode better.
Regards
