### ISSUE TITLE
Prevent scrolling to the selected file when you switch between tabs

### ISSUE THREAD

**Issue by benbesuijen** [Microsoft/vscode#15309]
- VSCode Version: 1.7.1
- OS Version: Windows, Linux

Steps to Reproduce:

1. A long list with files that cause a scrollbar in the explorer on the left
2. Open some files from a different location in the explorer
3. Switch tabs in the editor and see the explorer scrolling to the selected file

When you select a tab in the editor the explorer on the left will highlight the concerning file and scroll automatically to it. Sometimes the scroll behavior is very confusing. In some situations you want to switch between tabs but keep sight on the current file structure. 

It will be great if this behavior can be disabled with a workspace option like this:

`{"explorer.highlightFileFromTab": false}`

**Comment by bpasero** [comment]
`"explorer.autoReveal": false`

**Comment by benbesuijen** [comment]
Sorry Benjamin, I feel so stupid. I tested this option with a previous version of VS Code and it did not work. Now it is working. Thank you and thumbs up for this great code editor.

**Comment by wkrueger** [comment]
Could consider adding a link to explorer settings from the explorer menu. (comes in trade of bloat though)
![](http://i.imgur.com/YYiFiQ9.png)
