### ISSUE TITLE
Code outline/file structure

### ISSUE THREAD

**Issue by vegarringdal** [Microsoft/vscode#15311]
- VSCode Version:1.7.1
- OS Version:Win10

Is there plans for any code outline for visual studio code?
This could be very useful in big classes to get a overview of the file structure.

Maybe there is a expansion for this that I have not found ?

**Comment by aeschli** [comment]
You can use `Ctrl + Shift + O` to see all symbols in a file.

**Comment by aeschli** [comment]
duplicate of #5605

**Comment by vegarringdal** [comment]
@aeschli thank you :-)

Sorry for the duplicate, really tried to search, didnt know to search for symbol...
+1 the other one, would like something more powerful, like a panel under explorer, that showed types on variables,parms etc
