### ISSUE TITLE
Trying to start the debugger two times in a row ends in a "endless loop"

### ISSUE THREAD

**Issue by Gargo83** [Microsoft/vscode#15314]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.48|

There seems to be a problem with the debugger.
Once you try to start it two times it starts and will nerver end.

Note to the "Steps to Reproduce":
I do not do the exact same thing. In reality i try to resolve my bug between steps 2 and 3.
So i change and save one or more files. But the process in "Steps to Reprocuce" is the simplest way to reproduce.

---

Steps to Reproduce:

1. Produce a compile error in your golang project
2. Try to start the debugger. It will output a error in the DEBUG CONSOLE and nothing else happens.
3. Try to start the debugger a second time. The "Debug Toolbar" appears. The Progress blue line above the side bar is "spinning" and clicking on the stop symbol on the debug toolbar doesn't do anything

**Comment by isidorn** [comment]
This seems like an issue with our go extension, thus forwarding to @ramya-rao-a to try to reproduce. Since I do not get this with node debugging

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#770
