### ISSUE TITLE
Options for profile status bar item

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#153132]
<img width="192" alt="CleanShot 2022-06-24 at 07 50 02@2x" src="https://user-images.githubusercontent.com/35271042/175560823-b1c6ee08-9bfd-4acf-a645-235f5a450d60.png">

Personally, I'd love to see:
- An option to hide the status bar item or text for default profiles (I only want to know when I am in another profile)
- An option to use an icon instead of text for the profile
  <img width="139" alt="CleanShot 2022-06-24 at 07 52 25@2x" src="https://user-images.githubusercontent.com/35271042/175561160-6e94eead-63c5-4b20-b0a6-f98bf0aaea20.png">

**Comment by sandy081** [comment]
@daviddossett May I know if we have an icon for this already?

**Comment by sandy081** [comment]
Changed the profiles icon to following (same as the one @misolori used in his previous screenshots)

![image](https://user-images.githubusercontent.com/10746682/178430868-d04f1a29-7452-4569-8b44-0c943b9ac479.png)

Closing this as I think there is no further action needed here.
