### ISSUE TITLE
The pseudoterminal extension API latency seems much higher than it was before

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153182]
Not sure if something happened on the terminal or extension API but latency can easily hit 500ms+ on a keystroke which leads to a pretty bad experience.

**Comment by Tyriar** [comment]
@deepak1556 has something happened around message ports/ipc? This is super fast in v1.68 but very laggy in Insiders.

To repro run this extension sample https://github.com/microsoft/vscode-extension-samples/tree/main/extension-terminal-sample and run the `Extension Terminal Sample: Create` command.

**Comment by deepak1556** [comment]
Can confirm the issue only happens with `"extensions.experimental.useUtilityProcess": true`

/cc @alexdima

**Comment by deepak1556** [comment]
There was an issue in the timers interaction with event loop. Issue will be fixed in runtime tomorrow.
