### ISSUE TITLE
Keyboard Shortcut for editor.action.format not working

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#15312]
Smoke Testing 1.7.2

- VSCode Version: 1.7.2
- OS Version: Windows

Steps to Reproduce:

1. Add a keyboard shortcut for `editor.action.format`
```
{
   "key": "ctrl+shift+w",
   "command": "editor.action.format"
}
```

2. Use the shortcut on any js or ts file

Expected : File gets formatted
Actual     : No Change

The Right Click -> Format Document works though

**Comment by CoenraadS** [comment]
https://github.com/Microsoft/vscode/issues/15040

**Comment by ramya-rao-a** [comment]
I agree with https://github.com/Microsoft/vscode/issues/15040#issuecomment-259784832
`editor.action.format` should be removed from the list of available commands

![image](https://cloud.githubusercontent.com/assets/16890566/20191396/24443430-a73a-11e6-821c-db255ab13319.png)

**Comment by jrieken** [comment]
It's actually not doing anything anymore...
