### ISSUE TITLE
vscode multi-root workspace: open terminal asks me to choose cwd even if both have been set to same place

### ISSUE THREAD

**Issue by s6mike** [microsoft/vscode#153125]
Issue Type: <b>Feature Request</b>

Not sure if this is intended behaviour, but I have two root folders in my workspace, I've overriden one to use the other as the cwd, yet I still get asked which one to use when I open a new terminal:

![workflowy](https://user-images.githubusercontent.com/4956427/175555109-c7032e18-b9e6-4e6c-b0c4-9c086dab4195.png)

Please can you change this so that when cwds are identical there is no prompt?

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.10.110-15808-ge5740beba59b
Restricted Mode: No

**Comment by Tyriar** [comment]
We hadn't considered this case, good suggestion 👍

**Comment by babakks** [comment]
@Tyriar I take this.

**Comment by babakks** [comment]
@Tyriar I've just submitted the PR. Could you please check it?

**Comment by mcm-ham** [comment]
Thanks for implementing babakks, keen to see this once reviewed by Tyriar.
