### ISSUE TITLE
show them if setting has a language-specific value

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#153174]
hi all, I think that will be great to show the language-specific value-item if there are. 
![image](https://user-images.githubusercontent.com/1876302/173720486-b28db62f-748c-43c0-84cb-a18e640dfaa4.png)

_最初由 heartacker 在 https://github.com/microsoft/vscode/issues/145731#issuecomment-1155892881 发布_

**Comment by yume-chan** [comment]
Duplicate of #148674

**Comment by heartacker** [comment]
@yume-chan thx
