### ISSUE TITLE
Theme doesn't change

### ISSUE THREAD

**Issue by regevs** [microsoft/vscode#153156]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Immediately after the latest update, my theme switched to Dark+.
I manually went and set it to Light+. However, it just converts back to Dark+, e.g. after clicking on another file. 

VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.62.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.62.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 8f39c788-2611-420c-812e-8789278a6447|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: login-e-12|
|OS|Linux x64 3.10.0-1160.62.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (32 x 1012)|
|Memory (System)|187.37GB (93.92GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: login-e-12|
|OS|Linux x64 3.10.0-1160.62.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6142 CPU @ 2.60GHz (32 x 1012)|
|Memory (System)|187.37GB (93.92GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.15.18
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.10.7
cpptools-extension-pack|ms-|1.2.0
biosyntax|rea|0.0.11
snakemake-lang|sna|0.1.8
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549
841h4636:30516487

```

</details>

**Comment by aeschli** [comment]
Does it reproduce when running with extensions disabled? Some extension switch theme based on daylight?
What's in your settings? What's the value of `workbench.colorTheme`? Do you use settings sync?

**Comment by regevs** [comment]
It was the bioSyntax extension. After disabling it things went back to normal. Thanks for your help.
