### ISSUE TITLE
Feature Request: Hide Activity Bar

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#15310]
Would be cool to be able to hide the Activity Bar, for Zen mode or for Presentations.

I'm currently making videos about code and I use Markdown viewer too.

I would really like to hide the Activity bar during these videos, and sometimes just for me while coding.

**Comment by kube** [comment]
![screen shot 2016-11-10 at 22 50 31](https://cloud.githubusercontent.com/assets/2991143/20195854/712cfff8-a798-11e6-9ea8-103b8e729ba6.png)

![screen shot 2016-11-10 at 22 52 56](https://cloud.githubusercontent.com/assets/2991143/20195858/73caea68-a798-11e6-8e7d-da43c50219b0.png)

**Comment by kaiwood** [comment]
A quick search in the issue list reveals:

That option is already in Insiders so it's expected in the next release, see https://github.com/Microsoft/vscode/pull/14940

Complete Zen mode is discussed here: https://github.com/Microsoft/vscode/issues/12940

**Comment by rozzzly** [comment]
Kudos on the mockup @kube!! 

When this gets added _(I can't imagine it won't_,  please `vscode` make this into a command which I can bind to a key ccombo!

**Comment by kube** [comment]
Amazing.
Thanks.
And sorry for not finding the issue, was searching "Side bar" instead of "Activity Bar".
