### ISSUE TITLE
Have a good way to redirect open request into the merge editor

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153110]
continues 15a420fe9cdbe9111cc6d2cbec4b353048f5ca7d and https://github.com/microsoft/vscode/commit/15a420fe9cdbe9111cc6d2cbec4b353048f5ca7d#commitcomment-76896537

The merge editor integrates with the outside world via `getControl`. This make outline, breadcrumbs, breakpoint revealing/hitting (?) etc work. A hack was added to make sure open requests are redirected into the merge editor, e.g clicking on an outline entry should _not_ open a separate editor, likewise go-to-def etc... I know that the workbench has built-in knowledge of the diff-editor for similar cases but the merge editor is a contribution and needs a more offical way of doing this...

**Comment by bpasero** [comment]
Yeah to clarify what we do: there is a `ICodeEditorService` with a method `openCodeEditor` that somewhat serves as a replacement for `IEditorService.openEditor`. This service is being used from all contributions within monaco code editor as well as some workbench places. It encodes the knowledge about a diff editor to delegate the open request into the diff editor and not open a new editor.

I am not sure if we should use the editor resolver API for this or rather extend the code editor service to make it aware of text editors that have multiple sides. I think I lean towards the latter.

**Comment by jrieken** [comment]
> I am not sure if we should use the editor resolver API for this or rather extend the code editor service to make it aware of text editors that have multiple sides where one is the "main" side. I think I lean towards the latter.

I like that. Started the work in `joh/issue153110`. Things look quite promising but I am hitting a dead-end with the references viewlet. It uses normal, extension contributed, resource-opening and I don't really know how to intercept that. For (symbols) outline it can use the current code editor which works nicely
