### ISSUE TITLE
Merge editor: glitch with yellow box

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#153184]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/900690/175760150-1a181e90-e95c-4321-8708-ac48f5a9b874.png">

Should the yellow box not close until the end of line? Here the text continues in the overview ruler but the box closes.

**Comment by hediet** [comment]
This is by design. If we cut off the ends and you scroll vertically a bit, it is super hard to tell the region of a conflict...

**Comment by bpasero** [comment]
Maybe this should not be a box then but a solid background? Would have to see it more in action.

**Comment by hediet** [comment]
We tried with background colors, but it made highlighting the diff much more difficult. Thus closing.
