### ISSUE TITLE
Search is not excluding the folders in the "files excluded through settings"

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#15313]
Smoke Testing 1.7.2

- VSCode Version: 1.7.2
- OS Version: Windows

Steps to Reproduce:

![image](https://cloud.githubusercontent.com/assets/16890566/20190064/c414ae00-a734-11e6-92f2-462d8105c652.png)

**Comment by rebornix** [comment]
Not seeing this issue on macOS so likely Windows specific.

**Comment by roblourens** [comment]
And not on Linux

**Comment by ramya-rao-a** [comment]
Synced with @chrmarti 

I had one of the files from the said node_modules folder open while doing this search, in which case the folder is expected to be included in the file search.

Without the file from node_modules folder open, search does exclude the folders correctly.

**Comment by bpasero** [comment]
Is this https://github.com/Microsoft/vscode/issues/6904 ?

**Comment by chrmarti** [comment]
Closing as duplicate. Thanks.
