### ISSUE TITLE
VS Code doesn't send 'pause' request to the debug adapter when the button is hit

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/vscode#15315]
- VSCode Version: Version 1.8.0-insider, Commit 2583c1d1d2bb5430a899800523781c8d68cf98bb
(Though it is broken in the current live bits too)
- OS Version: Windows 10 (build 14393) though it is broken on other platforms also

Steps to Reproduce:

1. Install the C# extension
2. Install .NET Core per https://www.microsoft.com/net/core
3. Open the attached project
4. Hit F5 to launch
5. Hit the pause icon

Result:
VS Code doesn't send a 'pause' request to the C# debugger, and no error is shown.

**Comment by gregg-miskelly** [comment]
Adding project: [mytest.zip](https://github.com/Microsoft/vscode/files/584425/mytest.zip)

**Comment by isidorn** [comment]
This is fixed in the latest insiders and a workaround has been pushed to the stable recovery vscode (though not sure if we will release it)
