### ISSUE TITLE
Profiles: switching between profiles resets extension state

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#153122]
1. Create a new profile (empty)
2. Switch back to the default
3. :bug: extensions and states are reset

This is really annoying as I have +100 extensions and now have to go in and reset most of what I had. I would say that this is also a blocking bug where I won't be using the feature again until this is fixed.

## Before
![image](https://user-images.githubusercontent.com/35271042/175553205-5e75ac4b-762f-4781-a5d6-85c4ac191eb5.png)

## After
<img width="1232" alt="CleanShot 2022-06-24 at 07 10 30@2x" src="https://user-images.githubusercontent.com/35271042/175553385-2aab413e-4b05-4b1b-a9b9-1e64f5d19ff4.png">

**Comment by sandy081** [comment]
Sorry about it. This is an UI bug in extensions view that is not updating on profile switch. Will fix it.

**Comment by lramos15** [comment]
Think this is still happening

1. Have extension disabled
2. Switch profiles
3. Switch back
4. 🐛 Extension re-enabled. 

Please let me know if these aren't the verification steps for this issue

**Comment by sandy081** [comment]
It is working for me. Please see the following recording. I have ESLint disabled in **Empty Window** profile and enabled in other profiles. When I switch back to **Empty Window** profile, ESLint remains disabled.

https://user-images.githubusercontent.com/10746682/177046822-15357157-8a9e-4ba5-a295-656cc476e782.mp4

**Comment by misolori** [comment]
I've verified that this fixed
