### ISSUE TITLE
Experimental paste actions prevent pasting to multiple selection

### ISSUE THREAD

**Issue by PabloLION** [microsoft/vscode#153167]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: Darwin arm64 21.3.0

Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:37.209Z (1 wk ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0

Steps to Reproduce:

1. enter [Multiple selections mode](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor) with at least two selections
2. paste any text
3. the text will only be pasted on the first selection
4. comment out `"editor.experimental.pasteActions.enabled": true,` in the "settings.json" file
5. try step 1. and 2. again and the paste function with Multiple selections is back

related issue: https://github.com/microsoft/vscode/issues/151801

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/)?

**Comment by PabloLION** [comment]
@mjbvz I assume, since https://github.com/microsoft/vscode/issues/151801 does. Feel free to test. If you have insider version, you can test it in 1 minute.

**Comment by mjbvz** [comment]
If you tested it and it works, please close the issue

**Comment by PabloLION** [comment]
Resolved in:
Version: 1.69.0-insider
Commit: 173f4bea73601a31859372b409cac2c20fa91194
