### ISSUE TITLE
CSV File viewer

### ISSUE THREAD

**Issue by Morgy93** [Microsoft/vscode#1531]
I am not quite sure if it's even possible, but it would come in handy to have some csv features within VSCode - probably with some 3rd party extension.
Just some easy viewing possibilities so you don't have to rely on Excel, OpenOffice, LibreOffice or what else anymore.
I know that PhpStorm offers this feature already: https://www.jetbrains.com/phpstorm/help/editing-csv-and-similar-files-in-table-format.html
I'd love to see this in VSCode aswell.

**Comment by nmccready** [comment]
Should be possible as it is done in atom (which is very similar) https://atom.io/packages/tablr .

**Comment by bpasero** [comment]
See https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer

**Comment by bpasero** [comment]
Closing, it is not VS Code intent to support this. But there are extensions that can do it.

**Comment by garfieldbanks** [comment]
GrapeCity's Excel Viewer is nice but it doesn't support editing like [atom-tablr](https://github.com/abe33/atom-tablr).
  
Are there any other extensions out there that support editing CSV files?  
  
Are there any plans to make porting Atom extensions over to VS Code easier?  
  
Would it be possible to create an extension that acts as compatibility layer for Atom extensions?
