### ISSUE TITLE
Easily identify project by window skin/theming

### ISSUE THREAD

**Issue by res63661** [microsoft/vscode#153133]
I typically have > 6 separate instances of VS code running at one time.  Consequently, I waste a ton of time every day trying to figure out which project is which as I toggle back and forth through these different instances.  

I need a way to quickly visually identify project metadata about each window at a glance.  

I've been thinking about this for months - the easiest way would be if we could assign different colors to the outer window chrome and associate those with the project somehow.  A config file dedicated to this purpose local to the project would do the trick.

Here are some preliminary acceptance criteria for such a feature:
1. when I alt+tab I can clearly see the project/solution name in the window tile (currently this is almost always occluded bc of the way it's being rendered with other window meta)
2. when I alt+tab I can clearly discern the project/solution by the color of the window chrome (currently is all same color)
3. the above are also true for windows key+tab (desktops view)

**Comment by mroch** [comment]
this sounds a lot like the Peacock extension :)

https://www.peacockcode.dev/

**Comment by res63661** [comment]
@mroch great calll - big thanks.  Think that pretty much does it although didn't find a way yet to set peacock colors with a local config file (probably under my nose)
