### ISSUE TITLE
VS Code Insiders removes git functionality on network disconnect

### ISSUE THREAD

**Issue by nicolasvahidzein** [microsoft/vscode#153138]
For project stored on a network folder (my server in this case), VS Code Insiders removes the git functionality when the network experiences issues.

It never reconnects on its own.

Is this normal behaviour?

**Comment by lszomoru** [comment]
@nicolasvahidzein, could you share the exact steps that you followed as well as any errors that you are getting. Thanks!

**Comment by nicolasvahidzein** [comment]
Hello Ladislau,

well not much to do as i cannot explain what is going on but i am loosing
connection to the remote share and it disconnects vscode and the github
module inside of it.

**Comment by nicolasvahidzein** [comment]
Is there a tool i can use to send you my setup info?

I am not using any extensions to open up my remote folder but honestly i think it's my computer that is acting up, this is not making much sense. I keep losing my network connection. Let's close this for now. I don't want to waste your time.
