### ISSUE TITLE
Output pane is not updated while constantly fed with logs (encountered with CMake Tools build logs)

### ISSUE THREAD

**Issue by amurzeau** [microsoft/vscode#153159]
Does this issue occur when all extensions are disabled?: No (the issue is produced using CMake Tools extension)

- VS Code Version: Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 6.3.9600

- OS Version: Windows 8.1

## Description

When using the CMake Tools extension, the build output is shown in the "Output" tab.
And when the build is going fast (when there are many build log lines per second), the Output doesn't update until the end of the build.

See this video from https://github.com/microsoft/vscode-cmake-tools/issues/2337:

https://user-images.githubusercontent.com/43143191/150661038-8e90e1e8-f45a-410d-8739-b2e1c371dd29.mp4

The build output is not realtime.

## Steps to Reproduce

1. Install CMake Tools extension
2. Build a project that builds fast (less than 200ms per build log line)
CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.12)

project(test)

foreach(INDEX RANGE 500)
    add_executable(test_${INDEX} main.c)
    if(INDEX GREATER 0)
        math(EXPR PREVIOUS_INDEX "${INDEX}-1")
        set(PREVIOUS_INDEX test_${PREVIOUS_INDEX})
        add_dependencies(test_${INDEX} ${PREVIOUS_INDEX})
    endif()
endforeach()
```
main.c:
```c
#include <stdio.h>

int main() {
    printf("Hello world !\n");
    return 0;
}
```

Note: Build this CMake project using MSVC is faster and is more likely to reproduce the issue than building with clang/mingw.

## Investigations

After severals tests, I've found that:

 - The VSCode log file (inside `%APPDATA%\Code\logs\<timestamp>\exthost1\output_logging_<timestamp>\7-CMakeBuild.log` is constantly updated as expected, this can be checked with bash using `tail -s 0.1 -f 7-CMakeBuild.log`
 - The code that prevent the actual log to be printed in the Output pane is here:

https://github.com/microsoft/vscode/blob/648845d8692b5204254201b580f296cef9890abd/src/vs/workbench/contrib/output/common/outputChannelModel.ts#L210

This code uses `ThrottledDelayer.trigger` from here (with a default delay of 300ms):

https://github.com/microsoft/vscode/blob/648845d8692b5204254201b580f296cef9890abd/src/vs/base/common/async.ts#L391-L393

Which uses `Delayer.trigger` from here:

https://github.com/microsoft/vscode/blob/648845d8692b5204254201b580f296cef9890abd/src/vs/base/common/async.ts#L319-L347

And if I read this correctly, this means that:
Due to IPC between CMake Tools extension and the main Code thread, for every log line, `ThrottledDelayer.trigger` is called, and every call to that function will reset the Delayer timer of 200ms.
This means that as long as there are log lines every at most 200ms, the output pane won't be updated.

Which cause the "hang" as seen in the above video.

I guess that replacing the `appendContent` from `ThrottledDelayer` to a `Throttler` would solve that issue ?

**Comment by amurzeau** [comment]
Here are videos to compare the modification of using `Throttler` instead of `ThrottledDelayer` for the `appendThrottler` variable in `outputChannelMode.ts`.

Before modification (VSCode 1.68.1 unmodified):

https://user-images.githubusercontent.com/5435069/175768481-7131b0ed-e527-4d92-b74e-fb7488dd94fe.mp4

After modification (replaced the declaration of `appendThrottler` to `Throttler`, replaced call from `trigger()` to `queue()` and removed call to `cancel()`):

https://user-images.githubusercontent.com/5435069/175768487-af1d6125-b203-432b-9618-ab7fd01a1dc9.mp4

The CPU usage is a bit higher, but the log is shown in realtime (the CPU is a intel i5 3230m from 2013). Closing the Output pane while building takes less CPU (around 48% instead of 53% (when not recording), when not building I'm at 6%).

**Comment by sandy081** [comment]
@amurzeau Thanks for debugging it and coming up with the root cause. Your analysis is correct. But changing this to Throttler is not the right. We would still want to delay/debounce the updates if they do not need to be real time like log outputs. But for the output channels created by outputs we shall update the content immediately. 

Created a PR to fix it when immediate updates are needed like in this case.
