### ISSUE TITLE
No menus in latest insiders?

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#153170]
```
Version: 1.69.0-insider (user setup)
Commit: 173f4bea73601a31859372b409cac2c20fa91194
Date: 2022-06-24T06:32:08.615Z
Electron: 18.3.4
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```
Updated to latest and menus don't appear, even when turned on. 

![image](https://user-images.githubusercontent.com/1487073/175699139-1bb90f16-c986-4ab4-b245-1e83f7988fd8.png)

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/152906
