### ISSUE TITLE
Wrong files deleted when multi select (shift) and then unselect (control)

### ISSUE THREAD

**Issue by RoboticLi** [microsoft/vscode#153155]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: Windows 11 version 21H2

Steps to Reproduce:
1. Create a folder 'test'
2. Create 3 files in this folder 'a file.txt', 'other file.txt', 'do not delete file.txt'
3. Click the top file (a file.txt)
4. Press shift, click last file (other file.txt)
5. press CTRL and click the middle file (do not delete file.txt)
example:
![image](https://user-images.githubusercontent.com/105946622/175663649-673cdd53-9710-468f-9614-de48e67d868b.png)
The first and last file are now selected and marked with a blue bar.

6. press the delete button on the keyboard
⚠️ 'do not delete file.txt' is deleted

**Comment by lramos15** [comment]
This should be fixed now in VS code insiders https://code.visualstudio.com/insiders/
