### ISSUE TITLE
Branch protection lock should appear consistently in quick pick

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#153131]
## Status Bar
<img width="128" alt="CleanShot 2022-06-24 at 07 47 19@2x" src="https://user-images.githubusercontent.com/35271042/175560165-e473e131-b737-4f40-beb0-bbef32924d8c.png">

## Quick Pick
<img width="230" alt="CleanShot 2022-06-24 at 07 47 05@2x" src="https://user-images.githubusercontent.com/35271042/175560123-b49ba0cf-462a-4658-b73d-cc517300948e.png">

## Expected
<img width="209" alt="CleanShot 2022-06-24 at 07 48 13@2x" src="https://user-images.githubusercontent.com/35271042/175560356-970b24f2-f470-4338-9340-f1aa6f2d4220.png">

**Comment by lszomoru** [comment]
@misolori, should we include the branch icon for ranches that are not protected, and the tag icon for tags?

**Comment by misolori** [comment]
I wouldn't add icons for every entry as it can get busy/repetitive. @Tyriar and I were just discussing about reducing the repetition of icons in quick picks and only showing them for the ones that really warrant it.

<img width="488" alt="CleanShot 2022-06-24 at 12 23 12@2x" src="https://user-images.githubusercontent.com/35271042/175652262-0ad5e62b-6c49-4e9f-bd3e-a7413d4c2fc5.png">

**Comment by Tyriar** [comment]
@lszomoru FYI @misolori was suggesting removing the regular branch icons which it doesn't look like the change does. That would align closer with how tasks use icons (defaults are hidden) and the new debug console quick access for example.

**Comment by lszomoru** [comment]
This particular quick pick contains items of different types (ex: local branch, remote branch, tag). The only was to distinguish the type if to look at the description of the icon. I think that having an icon for each item based on its type is actually helpful here. I would like to keep it and see what the user feedback will be.

**Comment by misolori** [comment]
Just by looking at the icons, I'm only seeing the "locked" branch as the different one from the others. There is no difference between the local and remote branches here so I'm not seeing the benefit of showing the icon every single time and still feels very noisy:

<img width="335" alt="CleanShot 2022-07-11 at 08 19 54@2x" src="https://user-images.githubusercontent.com/35271042/178299068-75b9cba1-1e40-4559-b21d-5655e436c843.png">

**Comment by Tyriar** [comment]
Reopening to track discussion

**Comment by lszomoru** [comment]
Here is what I am seeing if I am running a search for "release". I can clearly differentiate between tags, locked branches, and branches. @misolori, if I would have a suitable icon for a remote branch, I would be happy to add it. I personally still feel that there is value in showing an icon for item, especially that I think the way people interract with the branch picker is that they open it and start typing in the input to filter down to the item that they would like to open. 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/3372902/178760932-2972c722-86a0-4aee-9123-03964cb77f7a.png">

**Comment by misolori** [comment]
We could try to add an overlay on the branch icon, similar to VS:

<img width="118" alt="CleanShot 2022-07-13 at 07 59 57@2x" src="https://user-images.githubusercontent.com/35271042/178765947-438f45f7-7e5c-4f50-9cc0-70641f48e5d4.png">

**Comment by lszomoru** [comment]
Love it! If you add this icon, I am happy to place this in the picker to indicate remote branches.
