### ISSUE TITLE
Windows VS Code will not traverse RHEL 7.2 Symlink (Really don't want to use sublime which CAN!!!)

### ISSUE THREAD

**Issue by jmcglaughlin** [Microsoft/vscode#15327]
- VSCode Version: 1.4.0
- OS Version: Win 7 Pro

Steps to Reproduce:

1.  any linux
2. target fs /opt/uid
3. ln -s /opt/uid /home/uid/myopt
4. SFTP Net Drive Win 7 to linuxserver:/home/uid
5. open folder symlink
    Path does not exist
    The path Z:/myopt does not seem to exist anymore on disk.

NOTE, sublime has NO TROUBLE traversing the symlink
I REALLY HOPE that MS does not give us the usual BS answer that it can't be done.
This is one of the most wonderful products out there.  I would hate to have to regress to sublime because I can not work in my clients secure work environment.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13359
