### ISSUE TITLE
Add option to remember directory of file opened via command line

### ISSUE THREAD

**Issue by mac-pro** [Microsoft/vscode#15326]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSC, open a file `D:\foo\a.txt` via menu File -> Open File. Close VSC.
2. Open Command Prompt, open a file `D:\bar\a.txt` via command line.
3. Close VSC and open it again. Try to open a file via menu File -> Open File, the file chooser dialog is opened with initial directory `D:\foo` (in step 1).

I think the file choose directory in step 3 should open with initial directory `D:\bar`. If you think so, please fix  `:-D`

Thank you,

**Comment by bpasero** [comment]
This should be fine now in 1.18.
