### ISSUE TITLE
explorer show files case-insensitively in case-sensitively volume

### ISSUE THREAD

**Issue by CyrilTaylor** [microsoft/vscode#153226]
There are file `BUILD` and folder `build` in android open source project 12, and I sync the project in case-sensitively volume，but the explorer can‘t access the folder `build`

<img width="1116" alt="image" src="https://user-images.githubusercontent.com/12631466/175797430-d4706445-fc22-4f3b-b027-7a81a03f2d72.png">

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/94307
