### ISSUE TITLE
View Menu Items are disabled inappropriately

### ISSUE THREAD

**Issue by waderyan** [Microsoft/vscode#15323]
- VSCode Version: 1.8-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Open a new Window
2. Click View menu

I expect to be able to open the command palatte. 

Instead it and all other menu items are grayed out.

![image](https://cloud.githubusercontent.com/assets/2449568/20201216/1d966cd0-a76b-11e6-83ef-044423f58d1c.png)

**Comment by bpasero** [comment]
@waderyan is that reproducible?

**Comment by octref** [comment]
Happened to me too.

![image](https://cloud.githubusercontent.com/assets/4033249/20205775/4cf46d7c-a790-11e6-9c3f-a60740be9511.png)

@bpasero 

Can you try repro this way:

1. Open VSCode
2. Cmd+Shift+N to create empty workspace
3. Close every window other than the empty workspace
4. Quit VSCode
5. Reopen VSCode
