### ISSUE TITLE
Fullscreen macOS windows do not support custom title bar

### ISSUE THREAD

**Issue by nickmccurdy** [microsoft/vscode#153221]
Issue Type: <b>Bug</b>

As as result, command center and layout control (when enabled) don't appear on fullscreen windows. This prevents me from using these features, as I always fullscreen all windows so I can easily navigate them with my keyboard using macOS Mission Control.

VS Code versions:

- 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
- 1.69.0-insider (173f4bea73601a31859372b409cac2c20fa91194, 2022-06-24T06:32:01.748Z)

OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 10, 12|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 858be5e5-b2d4-4f5e-a561-5403bbbc360c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

Steps to Reproduce:

1. Install stable or insiders on macOS
2. Use these settings:
```json
"window.experimental.commandCenter": true,
"window.nativeFullScreen": true,
"window.nativeTabs": false,
"window.titleBarStyle": "custom",
```
3. Restart VSCode if needed
4. Fullscreen the window
5. Mouse over the title bar at the top edge of the screen

Everything working on a normal window:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/927220/175792304-22303134-e990-45cc-8975-5b5e657e6cca.png">
Missing features on a fullscreen window:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/927220/175792314-0a55ac8d-f87b-4392-b81d-09242d1556d0.png">

**Comment by nickmccurdy** [comment]
Another thought, it would probably be a good idea to always support showing window controls outside of the title bar, since Linux doesn't have it enabled by default.

**Comment by ctf0** [comment]
i would like to add that when `"window.nativeFullScreen": false`, the layout control wont show up at all, even in normal view.
