### ISSUE TITLE
'cls' command doesn't work in the Visual Studio Code Integrated terminal

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode#153225]
Issue Type: <b>Bug</b>

please reopen #130190. this bug has nothing to do with any extensions and repros with all extensions disabled. that bug should never have been closed.

- on windows, open vscode terminal window
- put enough text in the terminal that a scrollbar appears
- run 'cls' command
- scroll up

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 4.4.0-19041-Microsoft
Connection to 'SSH: dropsy.corp.aetheros.com' could not be established  Canceled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (25.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (18.28GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (18.28GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (18.28GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.4.0-19041-Microsoft|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2901)|
|Memory (System)|47.66GB (25.18GB free)|
|VM|0%|

Connection to 'SSH: dropsy.corp.aetheros.com' could not be established  Canceled
</details>Extensions: none

**Comment by meganrogge** [comment]
I agree this isn't caused by an extension, but it is upstream of VS Code (conpty) and thus not something we can fix. the behavior you describe reproduces in an external terminal , correct?

**Comment by Spongman** [comment]
no. all of the {wsl,cmd,powershell} terminals clear the scrollback when i execute cls/clear.

**Comment by Tyriar** [comment]
@Spongman we do indeed test on Windows, no need to get condescending. I stated the reason this is happening in the other issue, *it is completely out of our control*. And as stated, Code Runner can work around this on their end, for example by running `workbench.action.terminal.clear` themselves instead of cls, which would be a better approach anyway.

**Comment by Tyriar** [comment]
@Spongman https://github.com/microsoft/vscode/issues/130190#issuecomment-902018918

> When cls is run, it's up to the backend (in this case conpty which is what Windows Terminal uses) to send instructions to the terminal to clear it.

Yes, it can happen when you run `cls` outside of Code Runner, that's the problem that is out of our control. Conpty sends us the wrong clear instruction and we listen to it.

**Comment by Tyriar** [comment]
Because they bundle the latest version of conpty and we use the API they ship to Windows. We hope to also bundle it but they need to make the library easier for us to consume first.
