### ISSUE TITLE
Javascript Array read as an error?

### ISSUE THREAD

**Issue by donnygunawan93** [Microsoft/vscode#15328]
Why vscode read this as an error? how to fix?

![untitled](https://cloud.githubusercontent.com/assets/10414213/20204835/a88c3730-a805-11e6-9e63-6fd3006c6db1.png)
- VSCode Version: Code 1.5.2 (66f37fd2a99eb9d628dd374d81d78835b410c39b, 2016-09-12T13:30:03.456Z)
- OS Version: Windows_NT ia32 10.0.10240

**Comment by aeschli** [comment]
Please always attach the source code sample.

What does the error say?

**Comment by ramya-rao-a** [comment]
Here is a simple example in a typescript file:

![image](https://cloud.githubusercontent.com/assets/16890566/20362340/06f79d76-abf0-11e6-820c-447b39b5e329.png)

Same code in javascript file does not give me any error
The example @donnygunawan93 has shared is in an javascript file.

@donnygunawan93 Can you confirm you see the same error?

**Comment by donnygunawan93** [comment]
@ramya-rao-a  No, I got "property assignment expected"

**Comment by donnygunawan93** [comment]
here the App
![untitled](https://cloud.githubusercontent.com/assets/10414213/20387117/3769fd6c-acf1-11e6-9cb4-347f3489f072.png)

**Comment by ramya-rao-a** [comment]
@donnygunawan93 `...` is a spread operator to be used on arrays.
Can you explain why you expect the `App` module to work with `...` ?

**Comment by jrieken** [comment]
Closing - there isn't enough information here.
