### ISSUE TITLE
Can't add a file

### ISSUE THREAD

**Issue by albu77** [microsoft/vscode#153241]
Issue Type: <b>Bug</b>

CLick on menu File "New File" enter toto.js and Enter nothing ahappen no file created 

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2294)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|5.98GB (1.03GB free)|
|Process Argv|--crash-reporter-id dd40267d-ef67-4c64-bd34-20e7d4f0cbbf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (47)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
Bookmarks|ale|11.3.1
classdiagram-ts|Ale|0.1.43
vscode-custom-css|be5|3.0.10
css-compressor|bes|0.0.2
copy-without-formatting|bma|0.2.0
vscode-intelephense-client|bme|1.8.0
open-html-in-browser|cod|0.1.21
vscode-mysql-client2|cwe|2.9.0
ecsstractor-port|diz|0.0.3
docs-markdown|doc|0.2.75
vscode-great-icons|emm|2.1.47
json-tools|eri|1.0.2
vscode-todo-plus|fab|4.18.4
php-pack|fel|1.0.2
vscode-firefox-debug|fir|2.9.0
vscode-svelte-snippets|fiv|0.5.0
vscode-mysql|for|0.4.0
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
tasks-context|jsa|1.0.0
classic-asp-html|jtj|0.1.2
typings-autoinstaller|jvi|1.2.0
vs-utils|Kyl|0.1.3
vscode-swissknife|lui|1.3.1
javascript-docstrings|Mas|1.1.1
gitexplorer|mfe|1.0.1
gitignore|mic|1.0.1
vscode-language-pack-fr|MS-|1.46.5
csharp|ms-|1.22.1
vscode-edge-devtools|ms-|1.3.0
test-adapter-converter|ms-|0.1.2
debugger-for-chrome|msj|4.12.8
sqltools|mtx|0.23.0
php-docblocker|nei|2.1.0
docthis|oou|0.8.2
git-file-history|pom|1.0.1
qub-xml-vscode|qub|1.2.8
vscode-yaml|red|0.8.0
markdown-preview-enhanced|shd|0.5.22
html5-boilerplate|sid|1.0.3
addDocComments|ste|0.0.8
svelte-vscode|sve|105.10.0
template-web-page|tfa|1.1.2
vsc-php-snippets|vsc|0.0.30
markdown-all-in-one|yzh|3.1.0
html-css-class-completion|Zig|1.19.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912cf:30515787
vsclangdc:30486549

```

</details>

**Comment by albu77** [comment]
CLick on menu File "New File" enter toto.js and Enter nothing ahappen no file created ?????

**Comment by lramos15** [comment]
Please try launching with extensions disabled.

Ctrl + shift + p > "Reload with extensions disabled"

**Comment by albu77** [comment]
I've tried just now by reloading with extensions disabled and it is same thing.

**Comment by lramos15** [comment]
\gifPlease

**Comment by albu77** [comment]
![Recording 2022-06-30 at 11 55 07](https://user-images.githubusercontent.com/624802/176649389-1f6196c4-76b2-4ce7-9fa2-d046693d7b3a.gif)

**Comment by lramos15** [comment]
When you click new file it's asking you the file type you want. In this case you want to click text file. There is also just an entry for New Text File.
