### ISSUE TITLE
integration-console: issue with background outside of text

### ISSUE THREAD

**Issue by MartinFinke0** [microsoft/vscode#153282]
Issue Type: <b>Performance Issue</b>

I have a simple program in Python:

print('\033[1;43m \n#########################\n \033[1;0m')

When I run the program, a line of characters that have a colored background is displayed. Colored backgrounds have only characters (see 175898885-db9062da-e901-44fa-88f4-494ff411550f.png).

When I resize the terminal window, the background color is colored with the rest of the line (see 175898880-211b78b6-98e0-4b84-b4cd-610bd3590efb.png).

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.12GB free)|
|Process Argv|--crash-reporter-id ff099b83-7939-4a61-bb36-fbb002bad152|
|Screen Reader|no|
|VM|0%|
</details>
![after](https://user-images.githubusercontent.com/108262212/175898880-211b78b6-98e0-4b84-b4cd-610bd3590efb.png)
![before](https://user-images.githubusercontent.com/108262212/175898885-db9062da-e901-44fa-88f4-494ff411550f.png)

**Comment by meganrogge** [comment]
looks like you tried to attach images and it didn't work. could you pls try again? A GIF would be more helpful

**Comment by MartinFinke0** [comment]
New attempt to add images as gifs:

![before](https://user-images.githubusercontent.com/108262212/175981562-461725fe-6a39-4257-b802-68c0790b667a.gif)
![after](https://user-images.githubusercontent.com/108262212/175981266-ff17fd76-4311-4c8b-b17e-0e7f208b3b63.gif)
