### ISSUE TITLE
VScode does not support large JS / TS project project with many files.

### ISSUE THREAD

**Issue by moonjoungyoung** [microsoft/vscode#153270]
Does this issue occur when all extensions are disabled?: No (JS / TS only)

- VS Code Version: 1.68.1
- OS Version: Windows 11

Steps to Reproduce:

1. Open large project (JS / TS) with many files.
2. A warning is displayed and code intellisense feature is not working.
![image](https://user-images.githubusercontent.com/31063573/175866343-065d00a9-fcb8-4144-ac9a-fd39a1e8c079.png)

The issue has been addressed at #31188 , but is has closed.
However, I think it is too bad that the functional support is not provided just because the project is large.
I think it is a problem that inevitably arises as more users use VSCode and the project grows.

**Comment by moonjoungyoung** [comment]
@mjbvz 

The project has about 2,000 files. Not includes node_modules.

**Comment by mjbvz** [comment]
Without an example or many additional reports of this happening, this sounds like a configuration issue with your project. Most likely it is including unexpected files (or perhaps is including some really large json/ auto generated js files)

See https://code.visualstudio.com/docs/typescript/typescript-compiling#_working-with-large-projects for some general tips
