### ISSUE TITLE
Editor crash with some time of use

### ISSUE THREAD

**Issue by albertoperezf** [Microsoft/vscode#15322]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|vscode-caniuse|akamud|0.5.3|
|vscode-color|anseki|0.2.1|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.0.8|
|vscode-instant-markdown|dbankier|0.1.0|
|tslint|eg2|0.5.40|
|docthis|joelday|0.3.5|
|Angular2|johnpapa|1.0.2|
|Theme-MaterialKit|ms-vscode|0.1.1|
|debugger-for-chrome|msjsdiag|2.2.2|
|vscode-icons|robertohuertasm|4.0.1|
|yo|samverschueren|0.9.2|

---

Steps to Reproduce:

1. Open the VS Code app.
2. Let it run in the background (until the crash point).

**Comment by aeschli** [comment]
Can you try to start without extensions? `code --disable-extensions`

**Comment by albertoperezf** [comment]
No, i will try and comment.

**Comment by ramya-rao-a** [comment]
Closing this as there has been no response in a week.

@albertoperezf Please feel free to re-open this issue if you see the crash with the extensions disabled
