### ISSUE TITLE
OTVAR fonts: fontWeight/wght conversion fails

### ISSUE THREAD

**Issue by MarcusSterz** [microsoft/vscode#153291]
Issue Type: <b>Bug</b>

Expected: editor.fontWeight will reproduce the wght setting of the font, 1-1000.

Errors: 
- [ ] Currently, **only instance steps 400, 500, 600, 700, 800, 900** are supported, but steps outside this range (1-300 and 1000) should work to according to [OT Spec for wght](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wght).
- [ ] All values are currently **rounded to full hundreds**, which defeats the purpose of variable fonts. For example, editor.fontWeight=650 will yield wght=700, but should yield wght=650.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 36, 27|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id eacbd859-6fed-4522-ad9e-69485b4219d2|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549

```

</details>

**Comment by alexdima** [comment]
In the editor, we delegate all font rendering to the browser rendering engine, in this case, Chromium. It looks like the CSS `font-weight` would support any value between `1` and `1000` in modern browsers -- https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight#variable_fonts . If Chromium doesn't implement the spec correctly, then please report as an issue directly to them at https://bugs.chromium.org/p/chromium/issues/list

**Comment by MarcusSterz** [comment]
It works fine, i.e., I can access any wght value 1-1000, in a simple HTML/CSS setup with the same font. Just the editor.fontWeight setting misbehaves.

I didn't test on Windows though. Is it limited to the Mac version?

I can provide sample files for recreating the bug if necessary.

**Comment by alexdima** [comment]
I have double checked, on our side, we just forward the value we're configured with to the CSS `font-weight` property. Here I'm setting `"editor.fontWeight": 440`:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/5047891/175947200-6c43ce0b-c890-4c62-b947-9b6ee7f06343.png">

@MarcusSterz VS Code Stable is on Chromium 98.0.4758.141 , which might be a bit behind compared to the latest Chromium/Edge. Given it is the same code-base, could you please also try at https://vscode.dev/ ?

**Comment by MarcusSterz** [comment]
I think I found the issue: For OTVARs, it should (additionally?) translate the setting into a `font-variations-settings` property for axis `wght`, not just the font-weight property. Like this:

```
font-variation-settings: "wght" 100;
```

Then it works

**Comment by chengluyu** [comment]
This is what I've been looking forward to for a long time. I made a prototype and it works. [changes](https://github.com/chengluyu/vscode/commit/609c4f69c1ce6ac11f0005fd9380fb5be5d1d990). Thanks to @MarcusSterz 's hint!

![CleanShot 2022-06-27 at 12 38 39@2x](https://user-images.githubusercontent.com/2239547/176022246-73fd4458-8d36-4b69-b22b-fa28fde8bcdc.png)

**Comment by chengluyu** [comment]
I'd like to implement this feature. Here's my pitch.

Like `fontLigatures`, VSCode should have an editor configuration item called `fontVariations`. It can be either a boolean to enable/disable font variations or a string for the value of the CSS `font-variation-settings` property.

- If `fontVariations` is `true`, we translate `fontWeight` to `"font-variation-settings: 'wght' ${value}"`.
- If `fontVariations` is `false`, we translate `fontWeigh` to `"font-weight: ${value}"`.
- If `fontVariations` is a string, we pass it as the value of `font-variation-settings` CSS property.

**Comment by bebraw** [comment]
From user point of view, setting the additional CSS automatically for a typeface with variable weight would be great as then it would simply work. For this, maybe you would have to detect if weight is variable. A flag seems possible but I am not sure if it's needed.

Exposing `fontVariations` is probably a good idea anyway to give access to any other possible axes.

There's one additional consideration: how to adjust italics/bold specifically? You have the same problem there probably.

**Comment by chengluyu** [comment]
> For this, maybe you would have to detect if weight is variable.

Do you mean detecting the font people are using is variable or not? That might be tricky.

**Comment by bebraw** [comment]
> Do you mean detecting the font people are using is variable or not? That might be tricky.

Yup. If there's any access to font metadata, there might be something. Likely it's specified at standard level somehow.

**Comment by chengluyu** [comment]
I just complete the prototype as [the plan above](https://github.com/microsoft/vscode/issues/153291#issuecomment-1168010038). Here is a set of screenshots.

![Issue](https://user-images.githubusercontent.com/2239547/176116645-0bf44e47-f22a-493e-b199-ec1625d533fd.png)

**Comment by chengluyu** [comment]
> Yup. If there's any access to font metadata, there might be something. Likely it's specified at standard level somehow.

That would be nice. But now VSCode just passes font settings to Chromium, I think this kind of checks will introduce a lot of new dependencies to VSCode and Monaco editor, which might be not worth.

**Comment by bebraw** [comment]
> That would be nice. But now VSCode just passes font settings to Chromium, I think this kind of checks will introduce a lot of new dependencies to VSCode and Monaco editor, which might be not worth.

Maybe one interesting option would be to apply the weight related CSS **anyway** and sort of discard the problem. The assumption here is that the CSS will work for non-variable fonts as well.

**Comment by MarcusSterz** [comment]
> Thanks to @MarcusSterz’s hint!

To be fair the praise should go 100% to @mekkablue who was helping me with this issue.

**Comment by chengluyu** [comment]
> Maybe one interesting option would be to apply the weight related CSS **anyway** and sort of discard the problem. The assumption here is that the CSS will work for non-variable fonts as well.

I agree. I tend to offer two choices and let people select.

- If people are using fonts support variable weights. They can either:
  - Use `fontWeight: <integer>` and `fontVariations: true`. This will translate `<integer>` to `font-variation-settings` CSS property.
  - Use `fontVariations: "'wght' <integer>"` directly, so they can actually other axes.
- If people are not using variable fonts, just use `fontWeight: <integer>`. This will set `font-weight` CSS property directly.

Do you have any problem with this?

**Comment by chengluyu** [comment]
I opened a PR for this issue. Suggestions are welcome!

**Comment by alexdima** [comment]
To verify, use a font family like Cascadia Code, configure `"editor.fontVariations": true` and `"editor.fontWeight": "450"`. Do an inspect element on the editor dom node and look for `font-variation-settings: "wght" 450` on the `view-lines` dom node:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/5047891/204399507-f20769c3-ab81-4a0a-9e74-efd9a978137d.png">

**Comment by mitsukuri** [comment]
While it does change css properties as described, it won't change the looks of a variable font at all.
See it in action in VSCode 1.74.0:

https://user-images.githubusercontent.com/88905839/206695769-37c033ed-d29c-4b5b-a348-10de320d0a09.mp4

The font itself is correctly identified by Windows as variable:


https://user-images.githubusercontent.com/88905839/206695886-f9d5cc9a-6b3f-45c4-9bbb-24e4cda36301.mp4

**Comment by alexdima** [comment]
@mitsukuri I can also reproduce on Windows with https://jsfiddle.net/9f27Lhax/ . The editor font rendering is delegated to the browser, which is Chromium in this case. Please report this directly against Chromium https://bugs.chromium.org/p/chromium/issues/list

in Chrome:
![image](https://user-images.githubusercontent.com/5047891/206732394-b1b1ee9c-bd68-4eb4-a52e-e54b7cfd3c84.png)

in Firefox:
![image](https://user-images.githubusercontent.com/5047891/206732457-b97852cb-3ff2-4f2b-ba13-a130ab699733.png)

**Comment by mitsukuri** [comment]
Oh, I was under the wrong impression that Chromium's rendering engine was ready for variable fonts and VSCode only lacked what this PR introduced, but it turns out that's not the case.

**Comment by alexdima** [comment]
> Chromium's rendering engine was ready for variable fonts

I think it is ready, but this is a bug. Please report it upstream to them. The same page https://jsfiddle.net/9f27Lhax/ on Chrome on macOS looks OK:
