### ISSUE TITLE
SelectionToWatchExpressionsAction shortcut should not require debug mode to invoke.

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#153223]
This action doesn't require debug mode. A user can optionally add it as a precondition to a keyboard shortcut if they so choose.

**Comment by weartist** [comment]
Can I work on this?

**Comment by roblourens** [comment]
Yes please!

**Comment by weartist** [comment]
> Yes please!

 I see that there is already a #153224 before, that pr modification is not quite right?

**Comment by roblourens** [comment]
I hadn't seen that, are you looking at it @weinand?
