### ISSUE TITLE
JSDoc syntax highlight. Not supported @prop name

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#15330]
- VSCode Version:

![image](https://cloud.githubusercontent.com/assets/3082812/20206152/8fc7664a-a7ef-11e6-825a-cf6c7214e08e.png)

- OS Version: win7 pro

Steps to Reproduce:

Don't highlight for property name

![image](https://cloud.githubusercontent.com/assets/3082812/20206099/40333e4c-a7ef-11e6-994a-dc8a6fdfbcec.png)

See:
http://usejsdoc.org/tags-param.html
http://usejsdoc.org/tags-property.html

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#353
