### ISSUE TITLE
Test: tasks with shell integration

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153365]
Refs #150833, #152391, #151769

- [x] Windows @alexr00 
- [x] macOS @sbatten 
- [x] Linux @karthiknadig 

Authors: @meganrogge @Tyriar 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23153365%0A%0A&assignees=meganrogge,Tyriar)

---
Tasks now make use of shell integration sequences to mark points of interest like the first problem found by problem matchers and command runs.

Verify that for:

Finite tasks IE ones that start and stop
- success / error decorations are shown when the task has a zero / non zero exit code, respectively
- there's no `Rerun command` action in the context menu

Watch tasks
- the first problem in a set of reported problems is marked with a decoration
- no decoration is shown when there are 0 errors
- the hover message makes sense to you

Both 
- command navigation using cmd/ctrl + up/down arrow navigates between the points of interest

Generic markers can be added:
- Run `echo -e "\x1b]1337;SetMark\x07"` and confirm that there's a generic decoration added

**Comment by karthiknadig** [comment]
That went well for me. I had a question about https://github.com/microsoft/vscode/issues/153600, left a comment there.

**Comment by jeanp413** [comment]
Is it intended to not be able to disable this? I expect it to respect `"terminal.integrated.shellIntegration.enabled"` or create another setting. created an issue https://github.com/microsoft/vscode/issues/153812
