### ISSUE TITLE
selecting the command should be easier

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153382]
I wanted to copy this command to a diff't window and see how the selection didn't work so well

https://user-images.githubusercontent.com/29464607/176035444-9b73d9a6-b9ad-43fc-bec6-dc84fe687628.mov

Since we know where the prompt ends, could we do something about this? If not, should we have a copy command action?

**Comment by Tyriar** [comment]
Sure we could do that, it would also be good to get some more order to this:

![image](https://user-images.githubusercontent.com/2193314/176234321-ddb025d2-20ca-4eb0-b741-bc083c2256cd.png)

Proposal:

- Rerun Command
- Copy Command
- `---`
- Copy Output
- Copy Output as HTML
- `---`
- How does this work?

**Comment by IanMatthewHuff** [comment]
Verified. Looks like the proposal to me.

<img width="277" alt="image" src="https://user-images.githubusercontent.com/812783/181108028-ef5fdee2-5053-4d25-9677-dc489a05a35f.png">
