### ISSUE TITLE
vscode won't update anymore

### ISSUE THREAD

**Issue by farfromrefug** [Microsoft/vscode#15338]
- VSCode Version: Version 1.8.0-insider (1.8.0-insider) 2016-11-10T07:03:10.419Z
- OS Version: MacOs Sierra

My vscode is in an 'update loop'.
When i start it it asks for my password to "add a new helper tool".
I put my password, then vscode tells me it s ready to update.
I choose "Update now" then Vscode closes itself, but does not restart.
Once i launch it again, the same process starts over.

I tried download vscode insider again but same issue.

**Comment by joaomoreno** [comment]
Try putting Code in another folder, like the Applications folder.

#3520

**Comment by joaomoreno** [comment]
Actually this might be something else.

**Comment by farfromrefug** [comment]
@joaomoreno i fixed it quite easily by removing the app settings. Though it is not a very good solution as i lost all my settings ...
I am wondering if VSCode did not manage to "kill" its helper before updating it?
May it be due to an extension ?

**Comment by joaomoreno** [comment]
It's #7426, let's comment there
