### ISSUE TITLE
Ctrl + shift + g to open gitViewlet?

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#15336]
Notice that on mac the shortcut to open the gitViewlet should be cmd + shit +g - for consistency with other viewlets. Currently it is ctrl + shift + g.

**Comment by joaomoreno** [comment]
#15281 Wow, actually one day apart. Are you the same person?

**Comment by isidorn** [comment]
One day apart because we are both hiding the activity bar and now need a shortcut to open git. That would be my guess
