### ISSUE TITLE
Windows seems to timeout checking out vscode.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#153394]
Windows build agent seems to timeout checking out VS code.

https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=175950
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=175942&view=results
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=175938&view=results

**Comment by deepak1556** [comment]
Closing as CI is healthy since then.
