### ISSUE TITLE
Remove `getExtension(...)` workaround

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153320]
continues https://github.com/microsoft/vscode/issues/152834

We need to ping extensions that use the old extension id and then remove the workaround we added

**Comment by jrieken** [comment]
These are the extensions that use the old extension identfier

-  [ ] byted-ide.gallery
-  [ ] Apex-TECH.apex-vsix-repo
-  [ ] Goldman-Sachs.secview-extension
-  [ ] vscjava.vscode-java-test
-  [ ] juliencroain.private-extension-manager
-  [ ] redhat.java

**Comment by jrieken** [comment]
@isidorn Can you help with the first three extensions?

**Comment by isidorn** [comment]
@jrieken I will email `byted-ide` since they are on the marketplace. 
We have no way to reach the second and third. So I suggest to go ahead and break them, and once things stop working they will ideally reach out to us and we can then advise them on how to update their extensions.
