### ISSUE TITLE
Changes in Source Control don't update if VS Code is opened to a subdirectory

### ISSUE THREAD

**Issue by MiguelGuthridge** [microsoft/vscode#153324]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Kubuntu 22.04

Steps to Reproduce:
1. Open a subfolder within a git repository
2. Notice that the git repository appears in the source control manager, and functions as expected
3. Edit a file, notice that the change indicators appear in the gutter, but that no changes are detected in the git repository in the source control panel
4. Manually reload the source control panel and observe that the changed file appears there

I'd expect the changes to update in the same way as they do when I open up the primary folder of a git repository, as manually reloading things every time I want to check which files have changed is frustrating.

**Comment by lszomoru** [comment]
@MiguelGuthridge, it looks like there might be a problem with the file system events that trigger the refresh of the "Source Control" viewlet. Could you please enable trace logging for the git extension as described in [this wiki](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#log-level-setting), and enable tracing for the file system watcher as described in [this wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local). After that try to reproduce the problem and share both logs. Thank you!

**Comment by MiguelGuthridge** [comment]
I can't seem to reproduce this anymore. I suppose it must have been a one-off
