### ISSUE TITLE
Merge Editor: Tweak Colors

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153316]
This is how it looks with a light theme:

![image](https://user-images.githubusercontent.com/2931520/175958171-47351dce-33c1-47b0-85bf-304323a12388.png)

Dark theme:

![image](https://user-images.githubusercontent.com/2931520/175958208-652d528c-1904-4f02-b96f-92bdbab78a9f.png)

These are the current customizable colors (subject to change):

* `mergeEditor.diff`
* `mergeEditor.diff.word`
* `mergeEditor.conflict-handled.minimapOverViewRuler`
* `mergeEditor.conflict-unhandled.minimapOverViewRuler`
* `mergeEditor.conflictBorder.handledFocused`
* `mergeEditor.conflictBorder.handledUnfocused`
* `mergeEditor.conflictBorder.unhandledFocused`
* `mergeEditor.conflictBorder.unhandledUnfocused`

*edit*: the names changed

**Comment by isidorn** [comment]
Created follow up https://github.com/microsoft/vscode/issues/159019
