### ISSUE TITLE
ÅÄÖ (and equally weird characters, in strings) get borked when formatting code.

### ISSUE THREAD

**Issue by Southgrove** [Microsoft/vscode#15332]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|unity-debug|Unity|1.0.3|
|Theme-8-Colour-Dark|gerane|0.0.2|
|Theme-red|gerane|0.0.2|
|Theme-x3-alpha|gerane|0.0.2|
|omnisharp|ms-vscode|0.3.3|
|red|red-auto|0.0.4|

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
For what language is that?

**Comment by Southgrove** [comment]
Oh, sorry. C#.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#916
