### ISSUE TITLE
Test Explorer Buggy decorations

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153304]
![recording](https://user-images.githubusercontent.com/2931520/175946832-a896a976-4b36-43d5-b535-003bce0d936d.gif)

**Comment by connor4312** [comment]
Do you recall how you got into the state where you saw only one X?

There's a deal of complexity in test decorations, but the selfhost test extension can sync tests to unsaved files so there should not be sync issues like this.

**Comment by hediet** [comment]
I think I formatted the entire file. For some reasons that seemed to have replaced the entire content of the text editor.

Thus, it was a very fast `Ctrl+A`, `Ctrl+X`, `Ctrl+V`.
