### ISSUE TITLE
Git: Checkout To...Create Branch From... fails with "fatal: '$(git-branch) main' is not a commit and a branch 'main2' cannot be created from it" (Insiders regression)

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#153368]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.69.0-insider (user setup)
Commit: e71b6105ebb4fbcfbf38a1b62bcbafdb048d3468
Date: 2022-06-27T07:59:47.622Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Open Folder (or workspace) with some Git repo project, such as from https://github.com/microsoft/vscode-cpptools.git . I've reproed this with multiple git repos.
2. Do command "Git: Checkout To...".
3. Select "Create Branch From...".
4. Type a new branch name, such as "main2".
5. Select an existing branch such "main".

Bug: It fails. Logging shows:
git checkout -q -b main2 --no-track $(git-branch) main
fatal: '$(git-branch) main' is not a commit and a branch 'main2' cannot be created from it.

The bug doesn't repro when I switch to the non-Insiders VS Code and it wasn't reproing last week, so I believe this is a recent Insiders regression.

**Comment by sean-mcmanus** [comment]
@lszomoru While looking through the recent commits that may have caused this, I found  https://github.com/microsoft/vscode/commit/45427b2346b33b2791a69b2413ad37c266581d9f, which may be the cause.

**Comment by lszomoru** [comment]
@sean-mcmanus, I will take a look at this first thing tomorrow morning.
