### ISSUE TITLE
can not involve 64bit powershell

### ISSUE THREAD

**Issue by rosrad** [Microsoft/vscode#15331]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version:  win10

Steps to Reproduce:
1. I have setup the the integrated.shell.windows as powershell
2. open the shell and check with "[Environment]::Is64BitProcess"
![image](https://cloud.githubusercontent.com/assets/2343640/20207448/36e4362e-a822-11e6-8be9-39dd8be07171.png)
![image](https://cloud.githubusercontent.com/assets/2343640/20207445/31bd0aea-a822-11e6-8299-0f77306899fa.png)

**Comment by Tyriar** [comment]
System32 points at the 32-bit version, see the documentation for 64-bit path https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration

**Comment by rosrad** [comment]
Thanks A lot!
