### ISSUE TITLE
Test: task icon / color customization

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153377]
Refs #151758, #145965

- [x] Windows @alexr00
- [x] macOS or Linux @rebornix 
- [x] WSL @rchiodo 

Authors: @meganrogge @Tyriar 

Complexity: 2

---
`icon` and `color` can now be set for tasks as configuration properties

Verify that these take effect and show up in the `Tasks: configure task` and `Tasks: run task` quick picks

**Comment by rchiodo** [comment]
I logged an issue but I can't get the icon or color to show up for configure at all?

**Comment by rebornix** [comment]
Did I miss anything it doesn't seem to work (after a few reloads)

![image](https://user-images.githubusercontent.com/876920/176256732-4778dddc-9753-481c-9658-ae48bf90d193.png)

**Comment by meganrogge** [comment]
I'd need a gif to see what's going on there. you also have a warning underline related to the problem matcher

**Comment by rebornix** [comment]
It seems now I'm seeing the same as https://github.com/microsoft/vscode/issues/153564 

https://user-images.githubusercontent.com/876920/176280854-acb5bb2c-ccc5-4ded-8276-02587ec41f3f.mov
