### ISSUE TITLE
SQL syntax highlighting breaks for escaped values

### ISSUE THREAD

**Issue by timint** [microsoft/vscode#153396]
Issue Type: <b>Bug</b>

Syntax highlighting for *.sql files breaks for escaped characters `\'`.

```
INSERT INTO `lc_countries` (`id`, `status`, `name`, `domestic_name`, `iso_code_1`, `iso_code_2`, `iso_code_3`, `tax_id_format`, `postcode_format`, `postcode_required`, `language_code`, `currency_code`, `phone_code`, `date_updated`, `date_created`) VALUES
(51, 1, 'Costa Rica', '', '188', 'CR', 'CRI', '', '[0-9]{4,5}|[0-9]{3}-[0-9]{4}', 0, 'es', 'CRC', '506', NOW(), NOW()),
(52, 1, 'Cote D\'Ivoire', '', '384', 'CI', 'CIV', '', '', 0, 'fr', 'XOF', '225', NOW(), NOW());
```

![image](https://user-images.githubusercontent.com/359192/176045149-b0b8dbd7-e378-4a65-a91a-737cb9ffed83.png)

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by yume-chan** [comment]
microsoft/vscode-mssql#17057

**Comment by alexr00** [comment]
Thank you for the upstream link @yume-chan!
