### ISSUE TITLE
Slowness in auto complete and lint fixes.

### ISSUE THREAD

**Issue by vishnuguhan** [microsoft/vscode#153323]
Issue Type: <b>Performance Issue</b>

Whenever the variable names are typed, VS code is taking some time to find autocompletable names from previous section of code and there is delay in suggestion of methods.

VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (0.77GB free)|
|Process Argv|--crash-reporter-id 76dc98d6-4825-43ba-a4af-0001ab1dfa78|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   16	   188	  1670	code main
    0	    33	  1675	   utility-network-service
    0	   295	  1678	   window (known_devices_screen.dart — app)
    0	   197	  1696	   shared-process
    0	    57	  1698	     ptyHost
    0	     0	  1721	       /bin/zsh -l
    0	    49	  1719	     fileWatcher
    0	     0	  3739	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   213	  1697	   extensionHost
    0	    49	  1759	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/vitalcoreapps/.vscode/extensions/redhat.vscode-yaml-1.8.0/dist/languageserver.js --node-ipc --clientProcessId=1697
    0	     0	  1760	     bash /Users/vitalcoreapps/Documents/flutter/bin/flutter daemon
    1	    82	  1781	       /Users/vitalcoreapps/Documents/flutter/bin/cache/dart-sdk/bin/dart --disable-dart-dev --packages=/Users/vitalcoreapps/Documents/flutter/packages/flutter_tools/.packages /Users/vitalcoreapps/Documents/flutter/bin/cache/flutter_tools.snapshot daemon
    0	     0	  1843	         /usr/bin/script -t 0 /dev/null /usr/bin/arch -arm64e xcrun xcdevice observe --both
    0	    57	  1844	           /Applications/Xcode.app/Contents/Developer/usr/bin/xcdevice observe --both
    0	    57	  1761	     /Users/vitalcoreapps/Documents/flutter/bin/cache/dart-sdk/bin/dart devtools --machine --try-ports 10 --allow-embedding
    0	   680	  1768	     /Users/vitalcoreapps/Documents/flutter/bin/cache/dart-sdk/bin/dart language-server --protocol=lsp --client-id=VS-Code --client-version=3.42.1
    0	    41	  1797	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=1697
    0	    74	  2804	   gpu-process
    2	    98	  3729	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (known_devices_screen.dart — app)
|    Folder (app): 6764 files
|      File types: xml(1227) json(743) flat(677) class(278) len(132) png(110)
|                  jar(78) txt(69) h(49) tab(48)
|      Conf files:;
```

</details>
<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
dart-code|Dar|3.42.1
flutter|Dar|3.42.0
linter|fna|0.0.11
plantuml|jeb|2.17.3
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
vscode-yaml|red|1.8.0
ayu|tea|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment]
What language is this for?

**Comment by vishnuguhan** [comment]
Hello Matt,

This for Dart for flutter development.

**Comment by mjbvz** [comment]
Please file an issue against the Dart/flutter extensions
