### ISSUE TITLE
JS high not correctly

### ISSUE THREAD

**Issue by bakso** [Microsoft/vscode#15334]
- VSCode Version:1.7.1
- OS Version:MacOS 10.11.6

Steps to Reproduce:

```js
function formatBigNum(num) {
  num = Number(num)
  if (num < 10000) {
    return num
  }
  return (num/10000).toString().replace(/(\.[\d]{1})\d+$/,"$1") + 'w '
}
let hbAnimIndex = 0;
let hbAnimNode = null;
```

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/20229278/cfb63ebe-a855-11e6-8179-e5e5c5bc8065.png)
Looks like the variables are not colored. It that what you meant?

**Comment by ramya-rao-a** [comment]
I see this in insiders: 
![image](https://cloud.githubusercontent.com/assets/16890566/20333145/83edf554-ab65-11e6-9bee-a63d9d353fa7.png)


With a space after `num` in line 6 its all fine

![image](https://cloud.githubusercontent.com/assets/16890566/20333146/8ae00744-ab65-11e6-9f43-5881739ab2e2.png)


This is 1.7.1 
![image](https://cloud.githubusercontent.com/assets/16890566/20333194/d12172d8-ab65-11e6-9774-53e3f7878b11.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#356
