### ISSUE TITLE
Notebook API tests  - edit API batch edits

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153321]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=175857&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15

**Comment by rebornix** [comment]
Not aware of any change to notebook recently cc @roblourens

**Comment by chrmarti** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=176858&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15&l=653

**Comment by rebornix** [comment]
Thank you all for the reports, merging into https://github.com/microsoft/vscode/issues/155587 and current thinking is it was introduced via https://github.com/microsoft/vscode/pull/151377 .
