### ISSUE TITLE
Test: Modified elsewhere indicator in the Settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#153351]
Refs: #145731

- [x] anyOS @mjbvz
- [x] anyOS @isidorn

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23153351%0A%0A&assignees=rzhao271)

---

The Modified elsewhere indicator is a new feature in the Settings editor that informs the user that the value of a setting has been modified elsewhere.

1. Navigate to the Settings editor.
2. Scroll through the settings.
3. Many settings should already have the Modified elsewhere indicator show up. Hovering over the indicator should reveal a custom hover that notes down where else the setting has been modified. Verify that the link text makes sense, and that where the link navigates to makes sense.
4. If a setting has only been modified in one other scope, and has no language-specific default overrides, then the Modified elsewhere indicator will not display. Instead, the old "Modified in/Also modified in" label will display. One way to test this out is to modify the `diffEditor.codeLens` setting only for the user scope of a specific language, and then change the scope and/or language filter and see what shows up.

Also verify that the current screenreader behaviour is as follows:
1. If the user focuses on a setting, the screenreader reads a custom string that gives information about the Modified elsewhere indicator.
2. If the user mouses over the indicator to show the custom hover, and then focuses on the hover contents by clicking on the hover, the screenreader currently reads off that text as-is.

Known issue: the user is currently unable to tab to any indicator specifically, or get the custom hover for the Modified elsewhere indicator to show up using the keyboard.

**Comment by isidorn** [comment]
Very cool work, I really like this 👏  I think this will bring a lot of value to our users and help with some confusions.
