### ISSUE TITLE
show command actions shows up in hover of generic marker when no message is provided

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153380]
https://user-images.githubusercontent.com/29464607/176034473-7b91a00b-abfd-453c-a826-ea17992cbac0.mov

**Comment by meganrogge** [comment]
also the `hoverMessage` option isn't documented

**Comment by TylerLeonhardt** [comment]
@meganrogge @Tyriar can we get some steps?

**Comment by Tyriar** [comment]
On bash or zsh on Linux or macOS type `echo -e '\x1b]1337;SetMark\x07" then hover the dot, it's cannot be interacted with so it should not show "Show command actions" in the hover.
