### ISSUE TITLE
the red squiggy lines are not appearing in my code.

### ISSUE THREAD

**Issue by rajraghuwanshi007** [microsoft/vscode#153300]
Issue Type: <b>Performance Issue</b>

I accidentialy turn off the red underlines which showed the error cause it was appearing in resolve the problem in the bulb .now i can turn them on again.
i even reset all the settings to default by deleting the contents in settings.json of my vs code .
please help

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|5.86GB (0.81GB free)|
|Process Argv|--crash-reporter-id 3673cf67-1106-4067-99c2-25db486fc38d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    91	  6476	code main
    0	   203	  5996	   window (Settings - 1000 - Visual Studio Code)
    0	    38	  7608	   utility-network-service
    0	   105	 14228	   shared-process
    0	    76	 22912	     fileWatcher
    0	    82	 32736	     ptyHost
    0	    65	 26776	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     8	 31132	       console-window-host (Windows internal process)
    0	   121	 15452	   extensionHost
    0	    60	 28392	     c:\Users\rajra\.vscode\extensions\ms-vscode.cpptools-1.10.7-win32-x64\bin\cpptools.exe
    0	     4	 17464	       "c:\Users\rajra\.vscode\extensions\ms-vscode.cpptools-1.10.7-win32-x64\bin\cpptools.exe"
    0	   207	 10504	         c:\Users\rajra\.vscode\extensions\ms-vscode.cpptools-1.10.7-win32-x64/bin/cpptools-srv.exe 28392 {00CB4C07-E712-4A4B-A241-E5E35D28D6F2}
    0	    10	 18052	           console-window-host (Windows internal process)
    0	    10	 29804	       console-window-host (Windows internal process)
    0	    83	 16044	   issue-reporter
    0	   149	 28428	   gpu-process
    0	    27	 31400	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Settings - 1000 - Visual Studio Code)
|    Folder (1000): 13 files
|      File types: cpp(8) CPP(2) json(1) exe(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
mongodb-vscode|mon|0.9.3
cpptools|ms-|1.10.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by rajraghuwanshi007** [comment]
Can you please provide the solution soon.

**Comment by roblourens** [comment]
How did you turn it off? Which language? Are you using an extension for this?

**Comment by rajraghuwanshi007** [comment]
I was writing code and it had some error in it,so there was this red line appearing on that error part and when i hover the courser over it.It showed fix the problem something and there was a bulb icon in that message ,so I clicked that icon and it turned off and now i cant turn it on(the red lines).
I m using c++ language .
No, I am not using any extension .

**Comment by roblourens** [comment]
That validation comes from the C++ extension. Looks like you have that extension installed. Please file this issue on their repo.

**Comment by rajraghuwanshi007** [comment]
Can you tell me the name of that extension as I cannot figure out what it is.

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode-cpptools/issues
