### ISSUE TITLE
Test: Do Not Disturb Mode

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#153330]
Refs #144324

- [x] macOS @lszomoru
- [x] linux @connor4312
- [x] windows @rchiodo

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23153330%0A%0A&assignees=daviddossett)

---

The Do Not Disturb mode was added to give users the option to hide info and warning notifications when enabled. Notifications configured as modals and error notifications will still show. 

1. Open the [hello world sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/helloworld-sample) and install dependencies
2. Replace the existing `showInformationMessage` call with these lines:

```
vscode.window.showInformationMessage('Info Notification As Modal', { modal: true });	
vscode.window.showInformationMessage('Info Notification');
vscode.window.showWarningMessage('Warning Notification'); 
vscode.window.showErrorMessage('Error Notification'); 
```
3. Launch the extension and run the `Hello World` command
5. Verify that both the modal notification pops up and the three info/warning/error notifications pop up
6. Clear all notifications from the notifications center
7. Turn on Do Not Disturb mode from the notification center toolbar
8. Run the "Hello World" command
9. Verify that **only** the info modal and error notification pop up.
10. Open the [progress sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/progress-sample) and install dependencies 
11. Turn off do not disturb mode
12. Launch the extension and run the `Show Progress` command
13. Verify the progress notification shows
14. Turn on do not disturb mode and run `Show Progress` again
15. Verify the progress displays in the status bar instead of a notification
16. Verify that clicking on the status bar progress item opens up the notification
17. Reload the window and redo steps 15-16 to ensure do not disturb works on startup

**Comment by lszomoru** [comment]
Awesome work! 👏🏻
