### ISSUE TITLE
find decorations remain after closing the find widget and clearing the input

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153338]
not sure on reproe yet
<img width="575" alt="Screen Shot 2022-06-27 at 12 49 46 PM" src="https://user-images.githubusercontent.com/29464607/175994213-6fac1ba9-0168-4456-a4f3-d3eea6fe052d.png">

**Comment by Tyriar** [comment]
I got into a similar state recently, not sure how to repro though:

![image](https://user-images.githubusercontent.com/2193314/176182876-4b84f06d-a52f-4b7b-9ef7-665758578dba.png)

**Comment by meganrogge** [comment]
looks like a diff't issue (though maybe related) bc you have no buffer decorations - only leftover overview ruler marks. in my case, both remained

**Comment by meganrogge** [comment]
haven't seen this in awhile
