### ISSUE TITLE
Enhance symbol indexing

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#15339]
- VSCode Version: 1.7.1
- OS Version: Linux

I am working on multiple projects and every time i change the workspace from one to another, i have to wait a lot 10-15m for VSCode to finish indexing. It would be great if he could store his indexing and just do a check whenever it opens the workspace (that is if the workspace has been opened before)

**Comment by aeschli** [comment]
Are you talking about symbol information from languages (TypeScript, C#...) or the file index?
If its symbol information from languages, what languages are you working on?
IMO the best would best be managed by the language

**Comment by dfroze** [comment]
File index if I am not mistaken the term. I am working with C. 
Compared to eclipse it takes too much when looking for symbols. And not only regarding the speed but also how flexible it can be, in eclipse you can use regex when searching a symbol. When having a big project with multiple classes, methods, global variables, etc, you can easily mistake the name, so it should be as flexible as possible.
Even the more when you get to open an open source project (already in progress) and you have no idea what kind of function are there.

**Comment by aeschli** [comment]
File index is Ctrl + P, Symbol index is Ctrl + T. Let me know which shortcut is is so I can assign the issue to the developer in charge.

**Comment by dfroze** [comment]
@aeschli Sorry for not being clear. Symbol index Ctrl+T is the one I am talking about

**Comment by aeschli** [comment]
@dfroze Thanks a lot for the clarification.
You need to file this then against the extension you use for C.
If its [cpptools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), then the place to file it is https://github.com/Microsoft/vscode-cpptools/issues
