### ISSUE TITLE
[git] push a branch to repo that has been deleted on remote fails

### ISSUE THREAD

**Issue by pwright08** [Microsoft/vscode#15342]
- VSCode Version: 1.7.1
- OS Version: OS X Yosemite 10.10.5

Steps to Reproduce:

1. Create branch in git repo locally
2. Publish branch
3. Merge and delete branch remotely (on github in this case)
4. Commit another change locally
5. Push

Output:
```
git fetch
git show HEAD:README.md
git show HEAD:README.md
git pull
Your configuration specifies to merge with the ref 'refs/heads/feature/apvs-754/add-csurf'
from the remote, but no such ref was fetched.
git show HEAD:README.md
git show HEAD:README.md
```

**Comment by joaomoreno** [comment]
What failed here is the `git pull`, since your local branch is configured to be merged with the upstream `refs/heads/feature/apvs-754/add-csurf`, which no longer exists. To remove that, run `git --unset-upstream BRANCH_NAME`.

This is not a Code issue, it's more of a git usage problem.
