### ISSUE TITLE
Add toolbars/menus for input1 and input2

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153489]
Theirs / Yours title area is currently quite empty.
We should consider to add an action bar for "Compare with Base" action. 
The title area should also have additional Git information in the future

fyi @jrieken @daviddossett @bpasero 

![Screenshot 2022-06-28 at 16 20 44](https://user-images.githubusercontent.com/1926584/176202638-36e1b338-a68a-4c8f-bc99-eaac93705a40.png)

**Comment by daviddossett** [comment]
I don't see a branch or commit id in your screenshot. Is that configured somehow? 

<img width="533" alt="CleanShot 2022-06-28 at 10 00 52@2x" src="https://user-images.githubusercontent.com/25163139/176239795-46c56aad-01ab-4d55-b7ae-631cfefe0a76.png">

In any case, we could introduce a toolbar somewhat like the editor. Icons are placeholder, but an example could look like:

<img width="1032" alt="CleanShot 2022-06-28 at 10 05 06@2x" src="https://user-images.githubusercontent.com/25163139/176241552-ab22215b-8d75-46a5-9ca8-796b41c8ee1d.png">

**Comment by jrieken** [comment]
To verify

* open a merge editor
* verify that it has `...` menus about yours/theirs
