### ISSUE TITLE
Sourcemap toggle button missing

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#153438]
Testing #153408

* open the vscode repo
* launch the "VS Code" debug config
* add a breakpoint e.g. in the ctor of `TextModel` at `src/vs/editor/common/model/textModel.ts#301`
* open a new file in the instance being debugged
* can't see a toggle sourcemap button in the call stack view

https://user-images.githubusercontent.com/5047891/176141429-bbb69411-d093-4d0e-9d17-2f563d39b788.mp4

```
Version: 1.69.0-insider
Commit: e7751367f79f327b8103bee33a07c16817a2c7cd
Date: 2022-06-28T05:32:33.068Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
```

**Comment by connor4312** [comment]
Please ensure you're using the [nightly js-debug build](https://github.com/microsoft/vscode-js-debug#nightly-extension), as the version bump for stable did not get merged in last night.
