### ISSUE TITLE
Do Not Disturb Mode - visual indicator for pending notifications

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#153483]
Testing #153330

Should the do not disturb icon in the status bar have a visual clue that there are pending notifications?

**Comment by daviddossett** [comment]
That also came up in the PR. Could be a combined icon like this. Thoughts? I'm somehwat concerned that the two states mixed together will be hard to understand. 

<img width="791" alt="CleanShot 2022-06-28 at 09 27 37@2x" src="https://user-images.githubusercontent.com/25163139/176231827-33f57991-170d-44d8-a070-6b8782e29c49.png">

**Comment by lszomoru** [comment]
I personally do like the combined icon, but that is my own personal preference.
Does macOS, Windows show a combined state in their own implementation of this mode?

**Comment by daviddossett** [comment]
Gave this a shot and here's how it looks: 

https://user-images.githubusercontent.com/25163139/176499927-d038767d-418b-4342-af7f-69179256fdfc.mp4

**Comment by lszomoru** [comment]
Looks great 👏🏻
