### ISSUE TITLE
Support snap layouts for desktop apps on Windows 11

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153442]
This currently is not supported, but would be great.

https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/apply-snap-layout-menu

**Comment by ArturoDent** [comment]
Enable `Window > Experimental > Window Controls Overlay: Enabled`

works for me on W11.

**Comment by deepak1556** [comment]
It is available under experimental setting today `"window.experimental.windowControlsOverlay.enabled"`, currently blocked by following runtime issues https://github.com/electron/electron/issues/34364, https://github.com/electron/electron/issues/34129 to enabled by default.
