### ISSUE TITLE
The command shall be called Debug: Go to Loaded Script...

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#153446]
Testing #153350

Command `Debug: Show Loaded Scripts` is confusing and overlapping with the Loaded Scripts view in Debug. I think the purpose of this command/quick pick is to easily access and open a loaded script just like  `Go to File...` command. Hence it makes it clear if we call this command **Go to Loaded Script...** or **Open Loaded Script...**

**Comment by andreamah** [comment]
I like `Open Loaded Script...`! Thanks for the suggestion!
