### ISSUE TITLE
Allow to remove files from the Open Recent list

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#15340]
- VSCode Version: 1.7.1
- OS Version: Linux

There is only Clear List  that will delete all  items  from Recent Open list. It would be great you could delete specific ones.
Even more, when using shortcut Ctrl+r, there is no button/option for clear.  It would be great to have an option for clear or even better to delete specific items from list

**Comment by bpasero** [comment]
@dfroze we have a command called "Remove from (Editor) History" which allows you to remove a recently opened file:

![image](https://cloud.githubusercontent.com/assets/900690/20218303/3141ddc8-a824-11e6-8b74-6212c1a2479b.png)

So far this command was not removing it from the list of recent files under the file menu but I pushed a fix to support this too.

It is not as elegant as having a real control next to the file to remove it, so I will leave this still open. But there will be at least a solution soon.

**Comment by dfroze** [comment]
@bpasero Thank you for the title change. Way better then what I wrote :D
Regarding the command "Remove from (Editor) History", the one I mentioned was for the workspace/directors history:
![img](https://cloud.githubusercontent.com/assets/7603482/20219806/b3184576-a833-11e6-990b-6e008a63b1fb.png)

And yes there is an option to clear: File->Open Recent->Clear Items. But can only remove all or nothing.

**Comment by bpasero** [comment]
Good point, my action does not work with folders.

**Comment by wildeyes** [comment]
I suggest doing what chrome does: `shift-delete` to delete the currently highlighted (but not yet selected), shouldn't be too hard?

**Comment by gdh1995** [comment]
My file list for `Ctrl-P` has been polluted after I opened another single file which is not in the project folder:
* now VS Code always shows the outside file on the shortcut bar
* I've cleaned the recent file history, restarted VS Code, but it's still there

Any easy way to clean my shortcut bar manually? I don't like to rebuild the `.vscode` folder.

**Comment by roblourens** [comment]
Would be awesome to have `shift-delete` for everywhere there is history - quickopen, "open recent", maybe "recently used" items in command palette.

**Comment by bpasero** [comment]
The recently opened picker now shows an action to remove entries:

![panel-red](https://user-images.githubusercontent.com/900690/28452585-a1acd4d8-6df3-11e7-9b37-a22591a11d69.gif)

I find the idea of allowing for shift+delete interesting, maybe create a new issue for that which should then also cover normal file quick open.
