### ISSUE TITLE
Test: sourcemap toggling in js-debug

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#153408]
Test for https://github.com/microsoft/vscode/issues/151412

- [x] anyOS @alexdima 
- [x] anyOS @hediet 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23153408%0A%0A&assignees=connor4312)

---

See the linked issue for background and context.

**Toggle state:**

1. Use a project with sourcemaps -- such as js-debug!
2. Debug something. There should be a 🧭 icon in the title of the call stack view. 
3. Clicking the 🧭  should toggle its state to the "sourcemaps off" mode, and additionally when in "sourcemaps off" mode a button should appear in the debug toolbar that also allows toggling them back on
4. The toggle state should be persisted in the workspace across debug sessions/reloads

**Behavior of "sourcemaps off"**

1. If you're paused on a line when breakpoints are toggled off or on, you should be automatically moved to the compiled or source code, respectively
2. Hitting a breakpoint or debugger statement should always open you into the correct file based on your mode
3. Breakpoints set in the source code should be moved into the compiled code when sourcemaps are off, and when they're toggled.

**Comment by connor4312** [comment]
For testing this, please ensure you're using the [nightly js-debug build](https://github.com/microsoft/vscode-js-debug#nightly-extension), as the version bump for stable did not get merged in last night.

**Comment by hediet** [comment]
Connor, I love you ❤️
