### ISSUE TITLE
Copy As / Share Confusion

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153498]
Testing #153319

![image](https://user-images.githubusercontent.com/2931520/176204525-df3ea6ff-8b05-4c0a-9943-2d09e6cfae80.png)

I would expect many of these "Copy as" commands to be in the share menu.

Also, *Copy GitHub Permalink* and *Copy Remote File Url* seem to do something very similar (but use different commits ids).

**Comment by alexr00** [comment]
GHPRI's "Copy" commands are in the share menu now.
