### ISSUE TITLE
Add "amend to last commit" option when commiting staged changes

### ISSUE THREAD

**Issue by lbssousa** [Microsoft/vscode#15343]
I would like to suggest you to include support to "amend to last commit" feature in VS Code's commit message box (equivalent to `git commit --amend` command).

**Comment by connerk** [comment]
When attempting to use the implemented feature in fix #15343, "Commit Staged (Amend)" in the sub ellipsis menu, it requires one to type a commit message instead of using the message that is being amended to.

**Comment by dspdesign** [comment]
@connerk @lbssousa 
maybe 'git commit --amend --no-edit' ?

**Comment by louisanb** [comment]
what s the different between git commit -m "xxx" and git commit -am "xxx"

**Comment by lbssousa** [comment]
@louisanb `git commit -am "xxx"` is some kind of equivalent to `git add . && git commit -m "xxx"` i.e. it automatically adds new/changed files to staging area while creating a new commit.
