### ISSUE TITLE
Move lines with multiple cursors is broken

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153471]
I couldn't really nail down the specifics of the bug, but attempting to move lines up/down when using multiple cursors appears broken. Notice in the following recording how at first it appears it only works in one of the cursors, but later it suddenly works on two of them.

![Recording 2022-06-28 at 15 10 50](https://user-images.githubusercontent.com/22350/176186917-21a491ff-e5c1-425b-a27a-a89cdb9b278a.gif)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/11809
