### ISSUE TITLE
Yours / Theirs input editors get empty

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153492]
1. Have a merge conflict. Open merge editor
2. Do not react on any conficts. Click on Accept Merge
3. Dialog shows up. The Yours / Theirs editors get empty in the background before I have reacted in the dialog 🐛 

If I click cancel now I am in a broken state.
I can repro 100%.

![Screenshot 2022-06-28 at 16 23 34](https://user-images.githubusercontent.com/1926584/176203413-3c416d2c-f3ba-43c6-b6ae-dbe32dec8ff4.png)

fyi @hediet @bpasero

**Comment by jrieken** [comment]
The accept command triggers a close of the merge editor and while that happens the confirm logic kicks in...

**Comment by isidorn** [comment]
Looks good now -> verified
