### ISSUE TITLE
a black line in window title 

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#153409]
![image](https://user-images.githubusercontent.com/1876302/176077626-a6f0daf4-80cd-48fa-b2e1-e0a265893c29.png)

版本: 1.69.0-insider (user setup)
提交: e71b6105ebb4fbcfbf38a1b62bcbafdb048d3468
日期: 2022-06-27T07:59:47.622Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.25145

**Comment by ArturoDent** [comment]
See duplicate: https://github.com/microsoft/vscode/issues/150778
