### ISSUE TITLE
Allow changing commands for inbuilt UI buttons for VSCode terminal

### ISSUE THREAD

**Issue by harshnitk17** [microsoft/vscode#153439]
I am developing an extension where I am creating a custom VSCode Terminal from the extension, for the delete/kill terminal button (trashcan icon) that appears on every terminal, I want to execute my own function when that trashcan icon is clicked, is there a way to override existing command ? I can't use the onTerminalClose listener as it runs when vscode closes too, which I don't want. If this can't be done is there a way to provide additional UI buttons for a VSCode terminal ?
![image](https://user-images.githubusercontent.com/32409726/176143176-b684bb79-29f3-4900-817e-f5457eed3f63.png)

**Comment by Tyriar** [comment]
We may allow the ability for extensions to contribute to the UI in the future, but no plans currently. https://github.com/microsoft/vscode/issues/9285 would need to be handled first so if extensions add many actions they can be hidden manually. There is also https://github.com/microsoft/vscode/issues/79034 which is similar.
