### ISSUE TITLE
Can't click on "Show Command actions..."

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#153450]
Testing #153365

![Recording 2022-06-28 at 13 19 52](https://user-images.githubusercontent.com/38270282/176166505-20da65d2-9c2a-4358-91f3-09b5820da4eb.gif)

**Comment by Tyriar** [comment]
That's actually a description of what clicking the button will do. This was as designed but maybe @misolori has a better idea?

**Comment by Tyriar** [comment]
Same feedback from @dbaeumer in https://github.com/microsoft/vscode/issues/153432

**Comment by alexr00** [comment]
The "..." in "Show Command Actions..." tells me it's clickable. Just removing the "..." would help, but it still looks like something I want to click on.
