### ISSUE TITLE
Quickpick debug consoles doesn't show paused state

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153466]
Testing #153344

![image](https://user-images.githubusercontent.com/22350/176183551-955211fc-1837-4a4f-a1cd-a32f47312d9e.png)

**Comment by roblourens** [comment]
@andreamah I just realized that `getStateLabel` is not localized and is not meant for display. That means that "Label" was not a good name for that function, but we can either just remove the state or find the code that drives the state label in the callstack.

**Comment by andreamah** [comment]
Actually, it seems that `getStateLabel` only displays `initializing`, `stopped`, or `running`, which is probably not super useful to the user anyways. It seems like the info like `paused` is only available on each thread, and a debug session can have multiple threads. Perhaps we should just remove the state for now.
