### ISSUE TITLE
Quickpick separators come and go when scrolling

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153468]
Testing #153344

Doesn't feel so much like a rendering glitch, but more like _everytime the list is rendered, the separators are toggled on/off_.

![Recording 2022-06-28 at 14 56 39 (1)](https://user-images.githubusercontent.com/22350/176184186-a711bd10-8c4c-44a0-a4cc-ba5b90cd70fc.gif)

**Comment by TylerLeonhardt** [comment]
@joaomoreno hmm I can't seem to repro this on macOS... are you scrolling with arrow keys or mouse wheel?

**Comment by joaomoreno** [comment]
Keys. Now that I see it again, maybe it is a rendering glitch...

**Comment by TylerLeonhardt** [comment]
rendering glitch makes the most sense... not sure if maybe @deepak1556 you have thoughts on this? How do we typically handle rendering glitches?

**Comment by TylerLeonhardt** [comment]
You still seeing this @joaomoreno?

**Comment by joaomoreno** [comment]
Nope!
