### ISSUE TITLE
Test: Extensible markdown renderer for notebooks

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153403]
Refs #121256

- [x] Mac @rebornix 
- [ ] Linux
- [x] Windows  @rchiodo

Complexity: 5

----

## Summary

#121256 allows one notebook renderer to extend another. We use this to add math support for the built-in notebook renderer. How this works is intentionally pretty opened ended since we don't actually specify how one renderer can extend another. You can test out the markdown renderer for this functionality 

## Basics

1. Clone the `notebook-extend-markdown-renderer-sample` sample (https://github.com/microsoft/vscode-extension-samples/)
2. In the `package.json` note the `notebookRenderer` contribution:

```
  "notebookRenderer": [
       {
         "id": "markdownItRenderer-emoji",
         "displayName": "Markdown it Emoji renderer",
         "entrypoint": {
           "extends": "markdownItRenderer",
           "path": "./out/emoji.js"
         }
       }
     ]
```

This special `entrypoint` specifies that this rendered extends the built-in `markdownItRenderer` (`markdownItRenderer` is simply the id that the built-in renderer registered itself with). It also specifies as file to load (`./out/emoji.js`)

3. Now open `src/emoji.ts`. Here's how the extension works:

    - Our rendered will be activated automatically whenever the `markdownItRenderer` is.
    - On activation, our custom renderer retrieves the other renderer using `ctx.getRenderer`
    - The built-in markdown-it renderer specifies a `extendMarkdownIt` function that lets our custom rendered extend the [markdown-it](https://github.com/markdown-it/markdown-it) instance it uses.
    - We use this function to extend markdown-it with emoji support

    Note that this `extendMarkdownIt` is not part of the notebook renderer API, instead it is just a function that one renderer exposes that allows it to be extended. Other renderers may expose their own extension points

## Testing
- Explore the sample and note any issues. Make sure it works
- Look over the contribution point documentation and make sure it makes sense
- Try customizing the extending renderer and ensure it does what you expect

**Comment by rchiodo** [comment]
@mjbvz do you have a link to the contribution point documentation?

**Comment by mjbvz** [comment]
@rchiodo  For documentation, try hovering over the contribution points in the `package.json` and making sure those make sense

We don't have formal documentation but you can use the sample: https://github.com/microsoft/vscode-extension-samples/tree/main/notebook-extend-markdown-renderer-sample

**Comment by rebornix** [comment]
It works as expected, great work!

@mjbvz what's the recommended way to contributing styles along with the markdown-it plugin?
