### ISSUE TITLE
Undo doesn't work well with emmet inline suggestions

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#153421]
Testing #152237

* in an html file, type `ul>li*3>p`
* press backspace twice i.e. `ul>li*3`
* the emmet inline suggestion should appear
* press <kbd>tab</kbd>
* press <kbd>cmd</kbd>+<kbd>z</kbd>
* 🐛 the content should be `ul>li*3` but it is empty
* press <kbd>cmd</kbd>+<kbd>z</kbd> again
* 🐛 the content is now `ul>li*3>p`, the state before accepting the emmet completion is not reached

https://user-images.githubusercontent.com/5047891/176109297-bb435524-408d-4d97-8bb7-718807243946.mp4

**Comment by rzhao271** [comment]
Labelling this issue as out of scope now that we have new inline completion providers.
