### ISSUE TITLE
Hide glyph margin in Merge Editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153488]
Can we hide the Glyph Margin in the Merge editor. Reasoning:
* I believe users are highly unlike to add breakpoints in the merge editor
* horizontal space is needed, especially in the side by side by side view
* Makes UI simpler since merge editor already adds quite some things. The current double margin looks a bit ugly

![Screenshot 2022-06-28 at 16 18 51](https://user-images.githubusercontent.com/1926584/176202206-e94d2499-50f2-4186-b298-176d12d65f58.png)

**Comment by hediet** [comment]
Lets remove it for input1/2.

**Comment by isidorn** [comment]
Awesome, looks much better now 👏
