### ISSUE TITLE
Breakpoint takes 6 seconds to be set

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153470]
Testing #153344

In our selfhosting setup, on Windows:

1. Start debugging
2. Place a breakpoint in `quickInputList.ts#605`

🐛 The breakpoint takes ~6 seconds to be set. If I unset and set it again it's instant. If I unset it, restart debugging and set it again, it takes ~6 seconds again.

![image](https://user-images.githubusercontent.com/22350/176185250-e46f76d7-0717-4ba7-a4f6-00021334269d.png)

**Comment by andreamah** [comment]
Not too sure how this should be tested, but I tried the same steps that Joao mentioned above and it still seemed to take ~8 seconds or so for the breakpoint to be confirmed

**Comment by connor4312** [comment]
@andreamah are you using [js-debug nightly](https://github.com/microsoft/vscode-js-debug#nightly-extension)? If not you'll need to wait for the next Insiders where js-debug is bumped.

**Comment by andreamah** [comment]
Oh oops, I wasn't using nightly. Just tried it again with nightly and it works!
