### ISSUE TITLE
Git repo in sub folder or project

### ISSUE THREAD

**Issue by mattiashallstrom** [Microsoft/vscode#15341]
- VSCode Version: 1.7.1
- OS Version: win10

I have a project in vscode based on folder: myproject/
In this folder there is a git repo: myproject/gitfolder/
I can't find a way to use the built in git function of vscode because my base folder is not a git repo.

**Comment by SarthakYadav** [comment]
Same here. I work in a virtualenv which has several different git repositories in different subdirectories. VSCode's inbuilt git functionality is not sensing them and rather asks me to "Initialize Git repository".

**Comment by josephspurrier** [comment]
I'm working in Go and each of my subfolders are git repositories.

**Comment by xiaoski** [comment]
+1
In a large project, there are many independent git repo in different folder. But VS code can not deal with this situation. I need this feature too.

**Comment by joaomoreno** [comment]
VS Code now supports this. Just open a single file within those folders.
