### ISSUE TITLE
Turning on do not disturb closes notifications but the opposite isn't true

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#153557]
Testing #153330
![notificationClose](https://user-images.githubusercontent.com/19672699/176246351-ed328f2e-e824-4191-873d-d0e40ebe590b.gif)

**Comment by rchiodo** [comment]
Just to make sure I understand, 

- Setting 'Do not disturb' to on means the user doesn't want to see notifications so you might as well close the notifications tab.
- Setting 'Do not disturb' to off means the user DOES want to see notifications so you should keep the list open.

I guess that makes sense but the UX still feels broken. I think the button should behave consistently (either close or not close)

**Comment by rchiodo** [comment]
It's unpredictable and personally I find that jarring. Maybe other people would be okay with it.

**Comment by rchiodo** [comment]
The other alternative is to have neither close the window. They merely toggle the state of 'Do not disturb'

**Comment by daviddossett** [comment]
I'll have it hide for now since I think it makes it much more obvious what's happening when it closes when the mode is enabled. I'll take the trade off 👍
