### ISSUE TITLE
Testing 153377 - Color and Icon don't seem to work for configuring?

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#153564]
Testing #153377

Configuring:

![image](https://user-images.githubusercontent.com/19672699/176252227-2676922e-3a7c-42e6-a751-0f5c6c3a458a.png)

Running:

![image](https://user-images.githubusercontent.com/19672699/176252539-296e474d-0fa6-4c9d-a361-de45e43417e8.png)

**Comment by meganrogge** [comment]
@rchiodo if you close and reopen the quickpick does it show up?

**Comment by meganrogge** [comment]
can reproduce when the problem matcher is extension contributed, IE `$tsc`

**Comment by meganrogge** [comment]
just was able to repro - not sure yet what the pattern is for working vs not

**Comment by meganrogge** [comment]
in the case of the run task command, the tasks each get resolved

https://github.com/microsoft/vscode/blob/0cca4092d3266ad816d67cd158d9bd4f81c7ddd9/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2669

in the case of the configure task command, the extension provided tasks don't get resolved - assuming this is by design

**Comment by meganrogge** [comment]
@alexr00 I think that the contributed tasks shown in the configuring tasks quickpick are not yet resolved (per their config) and are taken directly from the provider, thus missing the icon. meanwhile, the tasks for the run quickpick have been resolved. is this by design?

**Comment by meganrogge** [comment]
getting closer the configuring task has the icon
<img width="723" alt="Screen Shot 2022-06-28 at 5 10 58 PM" src="https://user-images.githubusercontent.com/29464607/176288628-aa9d5597-982f-4449-b13e-c6c2d832cb44.png">
