### ISSUE TITLE
Cmd + K, Cmd + I should trigger custom hover in settings editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153589]
Testing #153351

When the user triggers the custom hover in this way we should pass focus to the hover.
That way it is aligned with the editor and other vs code parts and it would be more accessible.

fyi @Tyriar for custom hover since we had similar discussions

**Comment by mjbvz** [comment]
Also ran into this. I could not find a way to open the hover using just the keyboard

**Comment by rzhao271** [comment]
Closing in favour of https://github.com/microsoft/vscode/issues/159088
