### ISSUE TITLE
Share link from File Menu did not match expectations

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#153537]
Testing #153319

Of course, there may have been discussions and reasons for the current behavior, but I was surprised that the share action in the File menu linked to the line number of the currently opened editor. I was expecting a link to the workspace/repository only.

**Comment by alexr00** [comment]
@sbatten would you expect the same command from the editor context menu to use file+line number?

**Comment by sbatten** [comment]
yes, my expectation would be the context menu has the "context" and therefore does have the file/line associated with it.
