### ISSUE TITLE
unclear what sync does

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153547]
Testing #153317

This description could be improved to explain what `sync` means
<img width="641" alt="Screen Shot 2022-06-28 at 1 11 46 PM" src="https://user-images.githubusercontent.com/29464607/176242615-7fb996f2-1f18-4bf7-9366-be65341a0805.png">

**Comment by lszomoru** [comment]
Fixed with 3cfc74c52ec734017900847e2fe376546fdb7e2b.

**Comment by meganrogge** [comment]
@lszomoru do you want this verified?

**Comment by lszomoru** [comment]
thanks @meganrogge. I have added the missing label.
