### ISSUE TITLE
SCM commit button: Codicons should not be localized

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153502]
Testing #153366

I noticed this:

https://github.com/microsoft/vscode/blob/ade80ca128741e2aa97e836a1ff0ad7cf8d67fa7/extensions/git/src/actionButton.ts#L80-L100

The proper way to localize here would be:

```ts
title = '$(arrow-up) ' + localize('scm button commit and push title', "Commit & Push");
```

Otherwise localization extensions could change the icon or mess up the syntax.

**Comment by Tyriar** [comment]
I'd also recommend pulling the icons out of the localize strings all together in other spots like:

https://github.com/microsoft/vscode/blob/ade80ca128741e2aa97e836a1ff0ad7cf8d67fa7/extensions/git/src/actionButton.ts#L144

https://github.com/microsoft/vscode/blob/ade80ca128741e2aa97e836a1ff0ad7cf8d67fa7/extensions/git/src/actionButton.ts#L177

They should be within the localize string only if you want the _position_ of the icon localized.

**Comment by lszomoru** [comment]
Closing this issue as this work is being tracked by a debt item - https://github.com/microsoft/vscode/issues/153743
