### ISSUE TITLE
JSdoc+Intellisense. @typedef include in function description

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#15351]
- VSCode Version:

![image](https://cloud.githubusercontent.com/assets/3082812/20215225/e5e3d728-a823-11e6-89c9-db4eaa451d90.png)

- OS Version: win7 pro

Steps to Reproduce:

`@typedef` tag include in a first function description after `@typedef`, and is not included in the function which describes this type
`@typedef` can be re used in other functions, and describe the same type before each function is incorrect.

code:

![image](https://cloud.githubusercontent.com/assets/3082812/20215242/fc99a36c-a823-11e6-8d26-f003f6043abf.png)

functions:

![image](https://cloud.githubusercontent.com/assets/3082812/20215367/bb9c83ce-a824-11e6-8823-a5486dd00876.png)

![image](https://cloud.githubusercontent.com/assets/3082812/20215336/8d44f8ee-a824-11e6-847b-2559d501226f.png)

**Comment by waderyan** [comment]
Can you share your code so I can copy and paste? 

(I know it seems lazy, but I have a lot of issues to go through :) )

**Comment by IgorNovozhilov** [comment]
Океюшки
```js
/**
 * @typedef {Object} MyType1
 * @prop {string} name
 * @prop {string} type
 */

/**
 * @typedef {Object} MyType2
 * @prop {string} name
 * @prop {string} type
 */

/**
 * @param {MyType1} param1 MyParamPype
 * @returns {boolean}
 */
function MyFunc1(param1) {

}

/**
 * @param {MyType2} param2 MyParamPype
 * @returns {boolean}
 */
function MyFunc2(param1) {

}
```

**Comment by waderyan** [comment]
@IgorNovozhilov thank you. Migrating to TS Server repo.

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12233
