### ISSUE TITLE
Hovering the gray circle breakpoint in the editor does not show warning message about not being able to set bks

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#153554]
Testing #150664

* Create a file named `one.js`
```js
console.log('1234')

function hellothere(){
	const x = require('./two.js');
	x.saySomething();
}

hellothere();
```
* Create a file named `two.js`
```js
exports.saySomething = function () {
  console.log("Said somethign");
  return "1234";
};

```
* Add a break point to the last line `hellothere` in `one.js`
* Add a breakpoint to the secod line (inside `saySomething` fn) in `two.js`
* Start debugging
* The `warning icon` appears as expected and displays the right message
* However the following does not work
`Hovering the gray circle breakpoint in the editor shows the same message`

**Comment by roblourens** [comment]
It works for me

<img width="551" alt="image" src="https://user-images.githubusercontent.com/323878/176246600-674cb090-d4b0-44d6-b511-b9a03f94a4ad.png">

Are you sure?

**Comment by DonJayamanne** [comment]
Oh wait you meant in the editor, i thought you were referring to the grey circle against the bk in the bk panel.
Works as expected
