### ISSUE TITLE
Detected indentation is lost when switching from/to opened files

### ISSUE THREAD

**Issue by scorphus** [Microsoft/vscode#15352]
- VSCode Version: 1.7.1
- OS Version: OS X El Capitan 10.11.6

Steps to Reproduce:

1. Open any file
1. Open another file with 2 spaces indentation (i.e. a JS file)
3. Status bar states `Spaces: 4` the latter
4. Press `Cmd`+`Shift`+`P` and select `Detect Indentation from Content`
5. Indentation is correctly detected 🎉 
6. Switch to the former file
7. Switch back 💣
8. 💥  Indentation is back to incorrectly detected

**Comment by isidorn** [comment]
`Detect indentation from content` does not persist the detected indentation, you can use the `convert indentation` commands to actually change the content of the file. 
Also try using setting `"editor.detectIndentation": true` which should automatically detect indentation on each file opened.

I know this is a bit confusing but it is hard finding a correct belance between comlexity and aligning all the indentation feature requests we have been getting.

@alexandrudima can also comment more
For now I am closing as designed. @scorphus let me know if our indentation actions / settins do not solve the issue for you and I will reopen

**Comment by scorphus** [comment]
> let me know if our indentation actions / settins do not solve the issue for you and I will reopen

Perhaps a screencast will show it better?

![vscode-issue-15352](https://cloud.githubusercontent.com/assets/2112697/20355015/0f1de32c-ac07-11e6-8ebf-a97480463dbc.gif)
