### ISSUE TITLE
Button Does Not Show When There Is No Changed File

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153504]
Testing #153317

I would expect the button to be visible, but disabled.

**Comment by lszomoru** [comment]
Assuming that all settings are enabled, I am in favour of the following:
- There are pending changes
  - `Commit Changes` (enabled)
- There are no pending changes
  - Branch not published - `Publish Branch`
  - Incoming/Outgoing changes - `Sync Changes`
  - Else - `Commit Changes` (disabled)

@joaomoreno, what do you think?

**Comment by hediet** [comment]
Btw. why is it "Publish Branch", and not just "Push Branch"?
Afaik, "Publish" is not git terminology and might be confusing, especially for private repositories.

**Comment by lszomoru** [comment]
@hediet, not really sure as the "Publish Branch" label was put in place before I have taken ownership of the area.

**Comment by lszomoru** [comment]
The change to address this feedback has been checked in with https://github.com/microsoft/vscode/pull/153662.
After speaking with @joaomoreno, we have decided that in case there are no changed files, we would show the "Sync Changes" action button (assuming that there is a remote) as that seems more valuable than a disabled "Commit Changes" action button.
