### ISSUE TITLE
No feedback when hovering over the 'Also modified elsewhere' setting indicator

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153578]
Testing #153351

It's difficult to discover that the `Also modified elsewhere` setting indicator is hoverable as there is currently no feedback on hover. I suggest:

- Changing the text/icon some way on hover
- Allow click to open the hover info more quickly
- Potentially also changing the cursor on hover

**Comment by rzhao271** [comment]
How does adding a dotted underline to indicate that the label can be hovered over sound? Currently, only indicators with info icons can be hovered over, but that association isn't clear, so I'm thinking the dotted underline or some other decoration could work.

**Comment by mjbvz** [comment]
@rzhao271 yes an underline on hover sounds good to me

**Comment by isidorn** [comment]
Adding verified because now we have the underline.
However is it possible to also on click show the hover and change the icon to be a pointer? Only if it is low hanging :)
