### ISSUE TITLE
"File: Reveal in File Explorer" focuses the column bar instead of the selected file (Windows)

### ISSUE THREAD

**Issue by g-thomasr** [microsoft/vscode#153567]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows_NT x64 10.0.19044

Opening file explorer from vscode in Windows focuses the column bar instead of the selected file.  User must press `shift+tab` to switch to selected file.  See attached screenshot.
![vscode-file-explorer-wrong-focus](https://user-images.githubusercontent.com/6250871/176250099-f9b93604-279d-4ba2-8855-4c25f4b5150e.png)

## Steps to Reproduce:
1. Create a new temporary folder
2. Set the folder layout in Windows File Explorer to "list" (`ctrl+shift+5`)
3. Open temporary folder in vscode
4. Create and save a new file to temporary folder in vscode
5. Run the command `File: Reveal in File Explorer` in vscode
6. Pressing the context menu key or `shift+F10` SHOULD reveal the context menu for the selected file
7. Repeat the test after setting the folder layout in Windows File Explorer to "details" (`ctrl+shift+6`)
8. Run the command `File: Reveal in File Explorer` on the new file in vscode
9. Pressing the context menu DOES NOT reveal the context menu for the selected file, but the context menu for the first selected column

User can work around the issue by pressing `shift+tab` after the window is opened.

I suspect there must be a missing command line argument to windows file explorer.

**Comment by bpasero** [comment]
Not under our control.
