### ISSUE TITLE
Edit session - Account selector

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#153526]
Testing #153386

I am seeing weird behaviour related to the account selector when trying to create and result edit sessions. the behaviour is pretty random but I am signed in to VS Code Desktop with both GitHub and Microsoft, and I am signed in to https://insiders.vscode.dev with GitHub:
1. On web, I am asked to pick an account to use for the edit session even though I am signed in with one account
2. On desktop, there are times when I am asked to pick an account when creating an edit session and there are times when that does not happen
3. On desktop, i have seen a case when I tried to restore an edit session, the account picker showed up, even though I was seeing in the background that the edit session was successfully restored

Apologies if this is not helpful, but I am happy to either set up a screen share, or collect additional logs if available.

**Comment by joyceerhl** [comment]
> On web, I am asked to pick an account to use for the edit session even though I am signed in with one account

Do you mean that after signing into edit sessions once on web, you are asked to sign in again to apply edit sessions on web?

> On desktop, there are times when I am asked to pick an account when creating an edit session and there are times when that does not happen

This should happen the first time that you do anything with edit sessions on desktop, or any subsequent occasion when auth fails (e.g. an expired token). If you see this happen unexpectedly, the Log (Window) channel might help.

> On desktop, i have seen a case when I tried to restore an edit session, the account picker showed up, even though I was seeing in the background that the edit session was successfully restored

This definitely shouldn't happen, again I would love to see the logs if this happens again.

**Comment by joyceerhl** [comment]
Verification steps: 
1. Sign out of edit sessions via the accounts menu on insiders.vscode.dev and desktop VS Code Insiders
2. Store an edit session from desktop, sign in when prompted
3. Restore edit session from web, sign in when prompted
4. Store edit session from web, ensure you are not prompted to auth
5. Restore edit session from desktop, ensure you are not prompted to auth as well
