### ISSUE TITLE
process revive doesn't work on remote

### ISSUE THREAD

**Issue by BrianPittVP** [microsoft/vscode#153517]
Issue Type: <b>Feature Request</b>

Every time I launch VS Code I go through the same process of opening 3 terminal windows and naming them the same every time.  It would be great if this was something you could save so that it would restore the same terminals every time.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-1031-aws
Remote OS version: Linux x64 4.4.0-1128-aws

**Comment by Tyriar** [comment]
Looks like process revive doesn't work on remote

**Comment by meganrogge** [comment]
locally, terminal name isn't persisted on reload or restart

**Comment by Tyriar** [comment]
@meganrogge oh the name persisted for me when I tested in a local window, only no in remote windows 🤔

**Comment by meganrogge** [comment]
this is only a seamless relaunch issue. I hadn't typed here when it does not persist 

https://user-images.githubusercontent.com/29464607/176243372-8841ebbd-dbb5-47a6-bce8-41dc94982a06.mov

**Comment by Tyriar** [comment]
The relevant part of the code is here, where we set interaction state if the title was via API (command should be included with this):

https://github.com/microsoft/vscode/blob/6f902cde5b49dadbb9ccf136d8b7258740edaff3/src/vs/platform/terminal/node/ptyService.ts#L474-L477

**Comment by Tyriar** [comment]
Cannot reproduce:

![Image](https://user-images.githubusercontent.com/2193314/207073948-883c51fc-cbcc-48a7-aa3e-8ae9b92733d2.gif)
