### ISSUE TITLE
Shell status indicators clipped when terminal is in sidebar

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153570]
Testing #153398

1. With shell integration enabled
1. Move the terminal to the sidebar
1. Run some commands

**bug**
The command status icons are clipped:

<img width="421" alt="Screen Shot 2022-06-28 at 11 14 39 AM" src="https://user-images.githubusercontent.com/12821956/176253855-85b57fee-d5ac-4c7d-af3e-c641314799c7.png">

**Comment by Tyriar** [comment]
I saw a similar problem in a the right split pane in the panel:

![image](https://user-images.githubusercontent.com/2193314/176745369-956c97f9-04fd-46c3-851a-3645972ff776.png)
