### ISSUE TITLE
"Show matching extensions" in settings - weird experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153585]
Testing #153351

1. Open settings UI
2. Search for "@id:editor.fontSize fontsize"
3. Notice "Show matching extensions" blue button 🐛 
4. Click no it - no effect 🐛 

fyi @roblourens 

![Screenshot 2022-06-28 at 20 40 47](https://user-images.githubusercontent.com/1926584/176258207-f93d1d26-07f3-41b9-8352-1aef9a2a51fe.png)

**Comment by roblourens** [comment]
It shouldn't show up when the @id filter is present, I guess
