### ISSUE TITLE
Error while installing 'ES7+ React/Redux/React-Native snippets' extension. Please check the log for more details.

### ISSUE THREAD

**Issue by mdgolammafuz** [microsoft/vscode#153516]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by mdgolammafuz** [comment]
VS Code Version: May 2022 (version 1.68)
OS Version: WINDOWS 11

I can't install any extension.
Following is an example (Having the same problem for any extension)

1) Tried installing directly by selecting the install option
2) Tried from the CLI: $ code --install-extension dsznajder.es7-react-js-snippets
3) Also from VSIX: $ code --install-extension C:\Users\golam\Downloads\dsznajder.es7-react-js-snippets-4.4.3.vsix

Error messages:

PS C:\Users\golam\my_projects\react-native-nft-marketplace> code --install-extension dsznajder.es7-react-js-snippets
Installing extensions...
Installing extension 'dsznajder.es7-react-js-snippets'...
EPERM: operation not permitted, rename 'c:\Users\golam\AppData\Roaming\Code\CachedExtensionVSIXs\.47bca06d-03f3-49b0-b6f1-c91e5ef62a55' -> 'c:\Users\golam\AppData\Roaming\Code\CachedExtensionVSIXs\dsznajder.es7-react-js-snippets-4.4.3'
Failed Installing Extensions: dsznajder.es7-react-js-snippets
PS C:\Users\golam\my_projects\react-native-nft-marketplace> code --install-extension C:\Users\golam\Downloads\dsznajder.es7-react-js-snippets-4.4.3.vsix
Installing extensions...
(node:22848) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
EPERM: operation not permitted, mkdir 'c:\Users\golam\.vscode\extensions\.bf5fbc11-e7cf-43a6-b072-8f423e0bf5b7'
Failed Installing Extensions: file:///c%3A/Users/golam/Downloads/dsznajder.es7-react-js-snippets-4.4.3.vsix
PS C:\Users\golam\my_projects\react-native-nft-marketplace>

**Comment by sandy081** [comment]
> EPERM: operation not permitted, mkdir 'c:\Users\golam.vscode\extensions.bf5fbc11-e7cf-43a6-b072-8f423e0bf5b7'

Can you please check if you have write access for this folder `c:\Users\golam\vscode\extensions` and `c:\Users\golam\AppData\Roaming\Code\CachedExtensionVSIXs\`

**Comment by mdgolammafuz** [comment]
1) I don't have the write access for the folder: c:\Users\golam\vscode\extensions

2) I have the write access for the folder: c:\Users\golam\AppData\Roaming\Code\CachedExtensionVSIXs\

**Comment by sandy081** [comment]
> I don't have the write access for the folder: c:\Users\golam\vscode\extensions

You need to have write access to the folder for extensions to be installed. Please fix the access permissions which will fix this issue.
