### ISSUE TITLE
IntelliSense lost when developing with C# for Unity

### ISSUE THREAD

**Issue by cluo85** [Microsoft/vscode#1535]
The IntelliSense worked fine at the beginning when I started the VS code. Sometimes after I used it for a little while, The IntelliSense would lost. 
I have two ways to fix this: One is to type the command "Restart Omnisharp" and I will get IntelliSense again. Most of time this way will work, But sometimes it won't. Another way is to close vs code and reopen it. This way worked every time. 
I guess the IntelliSense lost usually happened when I write comments in Chinese. But sometimes it didn't happen. I'm not sure.
I'm using C# language. Windows 10. Newest version of Unity and VS code and dotbunny unity tool.

**Comment by VinditCo** [comment]
IntelliSense keeps restarting for me whilst I'm coding - it's very annoying as the lines jump up and down as references are found.
Any suggestions on how to debug this?

**Comment by BazIdle** [comment]
Can confirm the same issue with VSCode + C# + Unity. Omnisharp keeps restarting.

This is what I managed to get from embedded developer tools:
https://gist.github.com/BazIdle/df424cb5cd2b065a2618

("potentially unhandled rejected promise" and "Error: Canceled: Error: Canceled" are looping on every Omnisharp restart)

**Comment by VinditCo** [comment]
@BazIdle good find. Which Unity version are you on? 

Figured a downgrade might fix it. I've tried to find previous versions of vscode for OSX with no joy. Any ideas where to find one? 

(The builds on the Wiki are auto-trashed by OSX claiming they're corrupted - so I have to look elsewhere...)

**Comment by BazIdle** [comment]
@VinditCo 5.2.3f1

Are you, perchance, getting the same errors in Dev. Tools?

**Comment by VinditCo** [comment]
Looks like it ! Like 91 of Workbench causing an issue 

```
Error: Canceled: Error: Canceled
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/out/omnisharpServer.js:235:31
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:20571)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:21929)
    at e.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:22756)
    at e.cancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:23366)
    at DiagnosticsProvider._validateDocument (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/out/features/diagnosticsProvider.js:129:44)
    at DiagnosticsProvider._onDocumentAddOrChange (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/out/features/diagnosticsProvider.js:101:18)
    at DiagnosticsProvider.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/jrieken.vscode-omnisharp/out/features/diagnosticsProvider.js:86:93)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:20571)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/pluginHostProcess.js:7:21929)
```

**Comment by VinditCo** [comment]
After this and the disastrous Unity update I'm going to have a new rule: Don't download *any* software updates pushed during December. 

All devs are on the egg-nog...

**Comment by jrieken** [comment]
That stack trace is unhappy but won't be the cause of this issue. Can check your omnisharp log (Cmd+L, L) and paste it here?

**Comment by cluo85** [comment]
Here is my omnisharp log. I don't know why there are some strange characters. I'm not using any Chinese characters in the directory names and project names.  There are only Chinese characters in comments.
-----------------------------------------------------------------
[INFO] Starting OmniSharp at 'd:\Work\AlienTown\AlienTown.sln'...
[INFO] Started OmniSharp from 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\bin\omnisharp.cmd' with process id 15484...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'd:\Work\AlienTown' on host 4100.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime 'C:\Users\Luochong\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta8'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning 'd:\Work\AlienTown' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No project.json based projects found
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Detecting projects in 'd:\Work\AlienTown\AlienTown.sln'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'd:\Work\AlienTown\Assembly-CSharp.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for d:\Work\AlienTown\Assembly-CSharp.csproj
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'd:\Work\AlienTown\Assembly-CSharp-Editor-firstpass.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for d:\Work\AlienTown\Assembly-CSharp-Editor-firstpass.csproj
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'd:\Work\AlienTown'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
[ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
System.ArgumentOutOfRangeException: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
   �� Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   �� Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   �� OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.<Handle>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware.<Invoke>d__4.MoveNext()
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 32ms
[ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
System.ArgumentOutOfRangeException: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
   �� Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   �� Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   �� OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.<Handle>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware.<Invoke>d__4.MoveNext()
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 1ms
[ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
System.ArgumentOutOfRangeException: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
   �� Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   �� Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   �� OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.<Handle>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware.<Invoke>d__4.MoveNext()
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 1ms
[ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
System.ArgumentOutOfRangeException: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
   �� Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   �� Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   �� OmniSharp.Roslyn.CSharp.Services.Navigation.FindUsagesService.<Handle>d__2.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware.<Invoke>d__4.MoveNext()
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /findusages: 500 28ms
[ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
System.ArgumentOutOfRangeException: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��
������: index
   �� Microsoft.CodeAnalysis.Text.SourceText.LineInfo.get_Item(Int32 index)
   �� Microsoft.CodeAnalysis.Text.TextLineCollection.GetPosition(LinePosition position)
   �� OmniSharp.Roslyn.CSharp.Services.Intellisense.IntellisenseService.<Handle>d__3.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<HandleSingleRequest>d__18.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.Endpoint.EndpointHandler`2.<Process>d__16.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� OmniSharp.Middleware.EndpointMiddleware.<Invoke>d__7.MoveNext()
--- �����쳣����һλ���ж�ջ���ٵ�ĩβ ---
   �� System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   �� System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   �� Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware.<Invoke>d__4.MoveNext()
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /autocomplete: 500 1ms
[ERROR:Microsoft.AspNet.Diagnostics.ErrorHandlerMiddleware] An unhandled exception has occurred: ָ���Ĳ����ѳ�����Чֵ�ķ�Χ��

**Comment by BazIdle** [comment]
@jrieken here you go: https://gist.github.com/BazIdle/c1aae81f1fc6d6e0122d
(I copied only the error)

**Comment by jrieken** [comment]
This seems to be an issue with omnisharp. Moving there and see what we can do

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#371
