### ISSUE TITLE
Voiceover reads file path for setting section buttons

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153593]
Issue Type: <b>Bug</b>

1. Using voiceover
1. Open settings editor
1. Tab between the `User` and `workspace` sections

**Bug**
It reads out the full path to the settings file instead of something more helpful like `User settings`:

<img width="705" alt="Screen Shot 2022-06-28 at 11 58 19 AM" src="https://user-images.githubusercontent.com/12821956/176261295-e693aa27-ea40-42da-a3de-fe36a2ee2fb7.png">

VS Code version: Code - Insiders 1.69.0-insider (Universal) (e7751367f79f327b8103bee33a07c16817a2c7cd, 2022-06-28T05:17:52.688Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by pingren** [comment]
I can't reproduce the issue on the latest insider. (https://github.com/microsoft/vscode/commit/13ba7bb446a638d37ebccb1a7d74e31c32bb9790, Date: 2022-07-22T05:30:08.726Z)
Is it fixed? 

Recording:
https://user-images.githubusercontent.com/5123601/180708663-a8757929-c27e-444e-97d9-ca5c005b2e52.mp4

**Comment by rzhao271** [comment]
Hm, looks like I also can't reproduce the issue now.
