### ISSUE TITLE
It has been moved to #15431

### ISSUE THREAD

**Issue by xDarkMan1** [Microsoft/vscode#15355]
- VSCode Version: 1.7.2
- OS Version: Windows 7 Professional

live view for html~php pages like brackets Code editor

**Comment by aeschli** [comment]
Can you add more description what exactly that does? Maybe add a screenshot as well.

**Comment by xDarkMan1** [comment]
Okay,tomorrow :+1:

**Comment by xDarkMan1** [comment]
I want to delete the issue, then i'll create new issue with explain what does i mean

xDarkMan
Regards.

**Comment by aeschli** [comment]
duplicate of #15431
