### ISSUE TITLE
Switching profiles auto updates extension

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#153530]
Testing #153384

1. Have two profiles one with  an older version of the extension manually installed (i.e. Hex editor 1.0.0 and 1.9.7).
2. 🐛 Switch from the higher versioned profile to the lower versioned one. It updates even though you manually selected that version to install

**Comment by lramos15** [comment]
Wasn't able to test because if I install hex editor version 1.0.0 and then open and close VS Code it is uninstalled. All within the same profile too

**Comment by sandy081** [comment]
Not sure what you mean by it is uninstalled - May be you are hitting a different bug - https://github.com/microsoft/vscode/issues/153797

I tried with following steps and it seems to work

- Create two profiles
- In one profile install latest version of an extension and in another install older version of the same extension
- Switch between profiles and versions are retained in the respective profiles

**Comment by lramos15** [comment]
Yes seems to be #153797. Will try again today to verify
