### ISSUE TITLE
No clear progress when switching profiles

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#153518]
Testing #153384

1. Have two profiles
2. Try to switch between them
3. 🐛  Note there is no clear progress clicking the switcher again while the profile is being switched does nothing

**Comment by gjsjohnmurray** [comment]
See also https://github.com/microsoft/vscode/issues/116740#issuecomment-1173668698

**Comment by sandy081** [comment]
From @gjsjohnmurray 

After switching to a different profile it can take a few seconds before all the changes have been applied. It would be good to have a progress indicator. Perhaps a spinner in the status bar item. Or a progress notification, which could perhaps also inform us a seach part of the switchover is being performed.

**Comment by sandy081** [comment]
I just tried this and it seems profile switching is always instantaneous and the progress indicator is hardly visible. So, I do not think it is worth showing the progress.

**Comment by carlocardella** [comment]
Maybe it depends on the size of the profile you are testing with? I have quite a few extensions, some of then a bit slow to load and profile switching is _definitely_ slow, nothing seems to happen for a few seconds then extensions and views start to be loaded/unloaded. I have to just live it alonefor 30-60 seconds to make sure everything is switched properly

**Comment by sandy081** [comment]
Can you please share your profile so that I can try to reproduce?

**Comment by carlocardella** [comment]
Sure, attached

[default_export.zip](https://github.com/microsoft/vscode/files/10337995/default_export.zip)

**Comment by sandy081** [comment]
Switching profiles was instant to me with the above profile. For loading and activating extensions, we already show progress so I think that is good enough. Lets wait for more feedback.
