### ISSUE TITLE
Enabling source maps doesn't jump from JS to TS

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#153584]
Testing #153408

* open the vscode repo
* disable source map stepping
* set a breakpoint at `out/vs/editor/common/model/textModel.js#142`
* launch the "VS Code" debug config
* open an editor
* when the breakpoint is hit, enable source maps
* observe that all stacks get transformed to `.ts`, but the current stack does not:

https://user-images.githubusercontent.com/5047891/176257971-b863ee91-3476-49d7-8d8b-ac694fde0547.mp4

**Comment by connor4312** [comment]
Currently the behavior is "one way" for breakpoints -- breakpoints set in the source files are moved to compiled files, but not vise versa. We also had existing behavior that if a breakpoint was set and hit in compiled code, that we would continue stepping in compiled code.

A point fix would be to disable this behavior only for breakpoints set when source map mode was turned off, but especially across reloads we don't know when the breakpoint was set. Or we can remove the feature entirely and tell people to use the sourcemap mode toggle instead. Not sure I'm a fan of either, but I could be convinced.
