### ISSUE TITLE
Feature request: Floobits extension

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#15357]
Reopen a question already asked in #2411.

It would be a great thing to permit **real-time collaboration on code** between users.

I used Floobits in Sublime, and they also created a great extension for Atom. https://github.com/Floobits/floobits-atom

I know that VSCode team is working on some third party extensions, so would it be conceivable for you to work on a Floobits extension, or at least check that VSCode API has all necessary features for it?

(Not necessarily video chat, just enable code sync)

**Comment by NikosEfthias** [comment]
wow this would be amazing

**Comment by NikosEfthias** [comment]
is there any plan about this @aeschli ?

**Comment by aeschli** [comment]
Sorry, I'm not aware of any plans to add real-time collaboration functionality. Looks like a great opportunity for an extension...

**Comment by damienstanton** [comment]
FYI this extension looks like it accomplishes the pair programming goal: https://github.com/sockscode/sockscode-vscode

**Comment by mjbvz** [comment]
Duplicate of #15916
