### ISSUE TITLE
git extensions: Improve gpg signing failure handling

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153510]
Testing #153366

Repro:

1. Try commit something when gpg signing is setup on Windows
2. Cancel gpg signing dialog

Result:

![image](https://user-images.githubusercontent.com/2193314/176209999-2b59c6c9-db41-400d-8895-1f74daa8f7d1.png)

The log shows:

```
[2022-06-28T14:49:14.708Z] > git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - [4775ms]
[2022-06-28T14:49:14.708Z] 
> husky - npm run -s precommit
> husky - node v16.15.1

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
Reading git index versions...

gpg: signing failed: Operation cancelled
gpg: signing failed: Operation cancelled
error: gpg failed to sign the data
fatal: failed to write commit object
```

Can we detect the gpg related failure messages and provide a nicer message?

**Comment by joaomoreno** [comment]
We sure can: https://github.com/microsoft/vscode/blob/5ab9f868e3fa3d573b0e44456afd34695af56978/extensions/git/src/git.ts#L1476-L1501

**Comment by joaomoreno** [comment]
Merging into https://github.com/microsoft/vscode/issues/64409
