### ISSUE TITLE
Commit & Push Does Not Publish Unpublished Branch

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#153511]
Testing #153317

*Commit & Push* does not publish unpublished branch.
I would expect this to happen.
Currently, when on an unpublished branch, *Commit & Push* behaves as *Commit*.

**Comment by lszomoru** [comment]
This seems to be a problem with both the "Commit & Push" action button as well as the `push` post commit command setting. "Commit & Sync" does work as expected, as well as invoking the "Git Push" command from the "Source Control" viewlet also works.

**Comment by rzhao271** [comment]
I'm unable to verify this issue right now because clicking on the chevron doesn't work

**Comment by TylerLeonhardt** [comment]
Chevron seemed to work for me so I'm marking verified.
