### ISSUE TITLE
Improve hover feedback for insert toolbar

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#153559]
![image](https://user-images.githubusercontent.com/876920/176248563-2a90e09a-bb7b-494d-b1fa-636afc613870.png)

While testing https://github.com/microsoft/vscode-jupyter/issues/10598, I was following a [blog post](https://coderzcolumn.com/tutorials/python/interactive-widgets-in-jupyter-notebook-using-ipywidgets) to test ipywidgets, my workflow is more or less

* have two browser pages side by side
* copy code from the blog post
* hover on the end of the notebook document in vscode.dev, move around to trigger the insert toolbar to show up, click the `+ code` button and then paste code into it
* click the run button

Hover to show the insert toolbar is hard, I don't have confidence that I can have it to show up easily so at the end I started to use keyboard shortcut. I tried to do the same with Google Colab and found myself more successful in inserting cells through the insert toolbar.

**Comment by roblourens** [comment]
Is this specifically about the one at the end of the document, like when you scroll into empty space?

**Comment by rebornix** [comment]
@roblourens not necessarily the last one, I have a bit trouble hovering on all insert cell toolbars. Colab one feels more responsive to me.

**Comment by roblourens** [comment]
Any idea what is different or why it feels that way?

**Comment by roblourens** [comment]
Can revisit this if we have something concrete
