### ISSUE TITLE
Cannot view terminal warning when only a single terminal is open

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153565]
Testing #153398

1. With a single terminal open
1. Run `exit 1` in a terminal 
2. Try to hover over the warning icon in the bar

**bug**
I can't see what the warning is about:

![image](https://user-images.githubusercontent.com/12821956/176252704-a268b473-9cbd-45bc-8bf3-111d14e182b9.png)

**Comment by Tyriar** [comment]
The longer hover is macOS only to align with the OS tooltips, here's the issue for that https://github.com/microsoft/vscode/issues/123851

**Comment by meganrogge** [comment]
This was fixed at some point

![Screenshot 2023-10-02 at 10 15 36 AM](https://github.com/microsoft/vscode/assets/29464607/3cb7fad1-ae07-40e5-b874-415eae5b7829)
