### ISSUE TITLE
Incomplete English translation

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#153538]
Testing https://github.com/microsoft/vscode/issues/153391 in Firefox with de-ch (Swiss German) set.

- Open command palette and search for Remote Repositories commands
- :bug: The first command has a partly English, partly de-ch line under it (`Focus on` and `View` in English, `Remoterepositorys` seems to be de-ch translated)
![image](https://user-images.githubusercontent.com/25310137/176228983-d58c65d3-0241-4889-b3b3-6529264dd8b3.png)

**Comment by TylerLeonhardt** [comment]
Just found out about these functions on the desktop side:
https://github.com/microsoft/vscode/blob/71b996eff4cef4405d1d1cc4fe308545dac0b255/src/vs/platform/extensionManagement/common/extensionsScannerService.ts#L640-L822

Which seems to go through the manifest and turn some `string`s into `ILocalizedString`s. I followed up with @sandy081 to understand how this works.

**Comment by alexdima** [comment]
> This code was originally written by @alexdima 

Not quite, it was originally written by @dbaeumer , but I'm happy to try and help. My understanding is that the code is taking a JSON object that looks like this:
```
{ "some": { "deep": { "property": "%some.key%", "bar": ["%some.key2%"] } } }
```
Together with another JSON object that looks like this:
```
{ "some.key": "My string value", "some.key2": "My second string value" }
```
And produces a JSON object that looks like this:
```
{ "some": { "deep": { "property": "My string value", "bar": ["My second string value"] } } }
```

**Comment by andreamah** [comment]
I still see this on firefox:

![image](https://user-images.githubusercontent.com/31675041/186545694-54b5311e-f971-4bb3-b077-a1ba5f647181.png)

The first option's english translation still looks wrong?

**Comment by TylerLeonhardt** [comment]
The first one is still wrong because of https://github.com/microsoft/vscode/issues/157015 so we'll track that there.

However, the rest now have the English string underneath which they use to not have, which means this is fixed and verified 😃
