### ISSUE TITLE
Add a ✅ editor action in COMMIT_EDITMSG and MERGE_MSG?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153505]
Testing #153366

I think I saw feedback somewhere suggesting it's not clear what to do with the commit message editor. Should we have an "accept commit message" editor action in the top right as an additional hint here?

![image](https://user-images.githubusercontent.com/2193314/176208127-e945e12e-0727-40da-9f02-e14cc83769d1.png)

**Comment by joaomoreno** [comment]
I really like that.

**Comment by lszomoru** [comment]
I really like that as well. Would it make sense to also add a cancel commit button there?

**Comment by lszomoru** [comment]
Add the actions with https://github.com/microsoft/vscode/pull/153692.

<img width="905" alt="image" src="https://user-images.githubusercontent.com/3372902/176457331-dcf801a7-d23e-40b9-8cf5-276c846959df.png">

**Comment by rzhao271** [comment]
\closedWith 8045df1
