### ISSUE TITLE
Notebook folding state is getting lost on change

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153531]
* open `.vscode/notebooks/my-work.github-issues`
* collapse the "config" cell
* run `touch .vscode/notebooks/my-work.github-issues`
* :bug: the collapse state is lost

https://user-images.githubusercontent.com/1794099/176227204-f9bbed28-b152-4558-9fde-03ba24a997c6.mov

/cc @kieferrm - we talk about this case

**Comment by roblourens** [comment]
I think @rebornix fixed this
