### ISSUE TITLE
Voice over in settings editor reads markdown text

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153590]
Issue Type: <b>Bug</b>

1. Using voiceover
1. Open settings editor
1. View the `files.exclude` setting which contains a link

**Bug**
The raw markdown is read (including the markdown formatting)

<img width="610" alt="Screen Shot 2022-06-28 at 11 54 21 AM" src="https://user-images.githubusercontent.com/12821956/176260431-20a42b7a-45a2-4237-8bef-c76e48c62b9b.png">

VS Code version: Code - Insiders 1.69.0-insider (Universal) (e7751367f79f327b8103bee33a07c16817a2c7cd, 2022-06-28T05:17:52.688Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by rzhao271** [comment]
## Code pointers

There is a function called `renderMarkdownAsPlaintext` exported from `markdownRenderer.ts`.
https://github.com/microsoft/vscode/blob/725f83a711bc34049dbe8eb518110051e515ac74/src/vs/base/browser/markdownRenderer.ts#L466

The accessible text that uses the setting description is created in `settingsTree.ts` near line 2315. That line is part of the function `SettingsTreeAccessibilityProvider#getAriaLabel`.
https://github.com/microsoft/vscode/blob/725f83a711bc34049dbe8eb518110051e515ac74/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L2315

**Comment by weartist** [comment]
I'll fix that

**Comment by sandy081** [comment]
Verified that the text is read without mentioning the links.
