### ISSUE TITLE
both ctrl + click and F12 don`t work

### ISSUE THREAD

**Issue by pangxiaoli** [microsoft/vscode#153636]
```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-15T02:58:26.441Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.18.5-arch1-1
```

for example:
for this javascript code:
```javascript
const test = () => {};

test()
```
when `ctrl + click` the tset on line 3, go to defination don`t work, but it work on some past versions.

i had try run code with `--disable-extensions`, but useless.

**Comment by pangxiaoli** [comment]
> What if you run `go to definition` by right clicking on `test`?
Nothing happens, and the right click does not have the option `go to definition`, i just click it by `go -> go to definition`. i had clear all cache and reinstall vscode, it useless.

**Comment by mjbvz** [comment]
You've likely disabled the built-in JS/TS extension (or have changed the language mode of the file to something besides `javascsript` or `typescript`). Search `@builtin typescript` in the extensions view to make sure `TypeScript and JavaScript Language Features` is enabled
