### ISSUE TITLE
Allow us to control the internal VSCode terminal/bash (not integratedTerminal)

### ISSUE THREAD

**Issue by cbprosser** [microsoft/vscode#153635]
Hello!

I would love if we could set the internal VSCode terminal/git bash to some other terminal. This is different from the integrated terminal that we can already modify, I'm speaking about the internal terminal used by VSCode itself to perform things like git operations.

### **Why though?**
At my work environment, all users have a dedicated virtual machine, that way we can log in through any computer on or off campus and have the same work environment.

This is great for ensuring we can work on any machine, no matter how powerful it is, but it's terrible in some unfortunate ways. One of them being that every weekend, the virtual machine is re-set, which removes all of our PATH variables.

Because of this, post-installed apps like node/NPM/pnpm/etc don't work unless we go in every Monday and re-set our path variables.

To get around this, we use cmder, so we can set anything we need for our terminal in our hard storage that is persisted across VM refreshes.

I've successfully integrated cmder into VSCode's integrated terminal, so I can at minimum have a usable terminal in the application, BUT, I can't use several of VSCode's features because our projects have a pre-commit hook that requires npm to be in my PATH.

**Comment by Tyriar** [comment]
You can use cmder's _shell_ in vscode, but you can't embed/integrate cmder the _terminal_ into vscode. While it may be possible to embed another terminal in VS Code, there would be no actual integration and it wouldn't work in many of the places VS Code works, it would essentially just be positioning the other terminal on top of the window.

> To get around this, we use cmder, so we can set anything we need for our terminal in our hard storage that is persisted across VM refreshes.

If it's just about environment changes you could probably use one of these to get it working:

- Custom environment for all terminals via the `terminal.integrated.env.windows` setting
- A custom profile via the `terminal.integrated.profiles.windows` setting
- An extension to do this for you
- Some keybinding for the command `workbench.action.terminal.sendSequence` which could send the repetitive text

**Comment by cbprosser** [comment]
The problem with all of those suggestions is that they only set the environment variables for the integrated terminal, not the underlying terminals.

We **need** this feature in order to be able to use VSCode. It's a feature that other IDEs achieve (IntelliJ is the IDE the rest of the company uses, and it allows this functionality), which means it's difficult to get people to switch over without it. If we can't handle source control with the IDE, it makes it unappealing for most users.

**Comment by Tyriar** [comment]
> is that they only set the environment variables for the integrated terminal, not the underlying terminals.

I don't know what you mean by underlying terminals?

**Comment by cbprosser** [comment]
> > is that they only set the environment variables for the integrated terminal, not the underlying terminals.
> 
> I don't know what you mean by underlying terminals?

The terminals used in the output window, not the terminal window (View -> Output). The git terminal here that is used for git operations via the Source Control sidebar uses some git bash that is internal to VSCode. Because of this, it misses out on the environment variables set by cmder, which means I can't perform a git commit with a pre-commit hook that uses npm, because npm is unrecognized by that internal terminal.

These terminals need to also be configurable, so that in situations like this, VSCode can be configured to work in such environments where local PATH is transient.

I'm aware of workarounds, but expecting a team of developers to all remember to re-set path variables or start the program via a command line, and never use the "reload window" feature, is unreasonable, and migrating to VSCode from an IDE that **does** implement this sort of functionality is very difficult.

**Comment by Tyriar** [comment]
Ah ok, it sounds like you want to modify the extension host's environment which is tracked in https://github.com/microsoft/vscode/issues/152806.

> and never use the "reload window" feature

Reload window should be fine, once you create the first VS Code window the "main process" is created with that environment and all windows and extension host processes inherit that environment.

> I'm aware of workarounds, but expecting a team of developers to all remember to re-set path variables or start the program via a command line

If this is a big issue you could write an extension that checked the environment and popped up a notification with a button when it's not correct that could do all the setup for the user. Then just include that extension in the VM image.
