### ISSUE TITLE
Feature Request 

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#15367]
I use dreamweaver for coding i also like VSCode but what makes me to stick to dreamweaver is its color picker/pallet(**While Coding CSS**) so i request VSCode dev to create the dreamweaver like color picker/pallet for VSCode

![023ae1475cd7b60329f3ef6be1f7c17ce1de7680](https://cloud.githubusercontent.com/assets/20091634/20222176/47aa920e-a85a-11e6-8ff5-0cd918fdf0e3.png)

**Comment by aeschli** [comment]
duplicate of #625

**Comment by MandarSant** [comment]
@aeschli i think dreamweaver colorpicker is more User friendly
