### ISSUE TITLE
New shortcut interceptions?

### ISSUE THREAD

**Issue by CharlonTank** [microsoft/vscode#153601]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.69.0-insider (Universal)
Commit: e7751367f79f327b8103bee33a07c16817a2c7cd
Date: 2022-06-28T05:17:52.688Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
Mac OS: 12.4

Steps to Reproduce:

1. Have latest Spectacle installed https://github.com/eczarny/spectacle/releases/tag/1.2
2. The shortcuts I used were control+option+command+(left/right/down/up) to move and resize, and option+command+f to toggle fullscreen(not fullscreen but resized as fullscreen).
3. Every applications I use behave normally and resize, VSCode included until yesterday, now these shortcuts do nothing.

**Comment by alexdima** [comment]
We had an Electron update, it might be related to that.

**Comment by lucasreppewelander** [comment]
I'm seeing the same in version 1.72.1 (with spectacle 1.2 installed)
```
Version: 1.72.1 (Universal)
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:25:13.482Z (2 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```
And to add some information, other electron apps like discord spectacle is still able to change the window like expected

**Comment by deepak1556** [comment]
Unable to repro the issue with latest stable `1.74` and spectacle 1.2
