### ISSUE TITLE
Clear the content of terminal does not work

### ISSUE THREAD

**Issue by gedenata** [microsoft/vscode#153643]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

```bash
Version: 1.68.1 (Universal)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z (2 wks ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.3.0
```

Steps to Reproduce:

1. Open vscode
2. Command + J
3. Try to hint some cli command
4. Command + K (Not working)

https://user-images.githubusercontent.com/1158185/176363941-11987a15-32eb-41db-b511-a567f1b37b82.mov

**Comment by alesmenzel** [comment]
An immediate workaround for this issue is to rebind the key from default to user settings - basically set the keybind to the same "Command + K" and then it has higher priority.

**Comment by RP-alissonpaschoal** [comment]
Same problem here... @alesmenzel the workaround worked, thanks!
