### ISSUE TITLE
Allow settings.json to be Array of objects that get merged

### ISSUE THREAD

**Issue by dali546** [microsoft/vscode#153673]
`settings.json` only accepts a top level `{}` object. It is sometimes difficult to keep this file orderly.
Is it possible to allow a `[]` Array of objects which get merged, so keys are better organised.

Related file that parses the Configuration
https://github.com/microsoft/vscode/blob/2936e8f5d2fea4655fdae2e0210b3fbb00e9f639/src/vs/platform/configuration/common/configurationModels.ts#L349-L357

As I'm writing this, I can see that writing configuration back to the file might be a bit more difficult.

Thoughts?

**Comment by rzhao271** [comment]
Right now, the fact that the setting is an array would mean that there's no merging behaviour, only overriding behavior. Maybe you want an object of objects? That way there can be keys, though at this point, those types of settings are not supported in the Settings editor.
