### ISSUE TITLE
"Undo last commit" should also be disabled while commit editor is open

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153668]
Testing #153366

Currently the "Undo last commit" command has not effect while the commit editor is open. It should either:
1. Be disabled
2. Be enabled and on execution close the editor and abandon the current commit

I think option 1 is better

![Screenshot 2022-06-29 at 12 48 20](https://user-images.githubusercontent.com/1926584/176419046-dba16e12-3a54-45ae-b51d-7641698860ae.png)

**Comment by joaomoreno** [comment]
Part of disablement story.

**Comment by TylerLeonhardt** [comment]
It also shows up in command palette 
![image](https://user-images.githubusercontent.com/2644648/176489309-3596f2ab-49d1-4f0b-a863-e1040d73a79f.png)
