### ISSUE TITLE
macOS Sierra , get the Error when to open the Integrated Terminal

### ISSUE THREAD

**Issue by yuankeyang** [Microsoft/vscode#15366]
- VSCode Version: **1.7.1** 
- OS Version: **macOS Sierra (10.12.1)**

> I get the error message **"The terminal process terminated with exit code: 1"**, when I try to open the **Integrated Terminal**.

![img](http://d.hiphotos.baidu.com/image/pic/item/902397dda144ad34cab663b5d9a20cf431ad85f3.jpg)

**Comment by Tyriar** [comment]
Does your username have no ascii-characters in it? If so this is fixed in Insiders.

**Comment by yuankeyang** [comment]
My username is Yakir, not Chinese characters.

**Comment by Tyriar** [comment]
Can you try this out in the [Insiders build](https://code.visualstudio.com/insiders) and post a screenshot of the error if it still occurs?

**Comment by yuankeyang** [comment]
I uninstall and reload it, and it's OK!
