### ISSUE TITLE
Profiles: Extension viewlet shows that 1 extension needs to be update, but the profile has no extensions

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode#153644]
- created and switched to a Testing profile with no extensions installed
--> The extensions viewlet shows a badge that 1 extension needs to be updated

![image](https://user-images.githubusercontent.com/172399/176364048-8b35ad0f-df47-4fad-bb55-4a446f911b63.png)

**Comment by egamma** [comment]
@sandy081 I remember that I had an extension that needed an update when I switched the profile.

**Comment by sandy081** [comment]
No worries and I see that screenshoot shows there is a problem but I do not know how to repro from the screenshot. I will close it.

If you get into this state again, please hover on the extensions viewlet icon and see what is says

**Comment by egamma** [comment]
>If you get into this state again, please hover on the extensions viewlet icon and see what is says

Actually I did that and the hover said that one extension needs to be updated, but the hover did not say which one.
