### ISSUE TITLE
Two "Accept Merge" buttons in Settings Sync merge

### ISSUE THREAD

**Issue by sana-ajani** [microsoft/vscode#153627]
Testing #153383

Steps:
1. Open two VS Code insiders with different user data dirs. 
2. Configure settings sync in one window, uncheck UI state and Settings. Change theme and editor layout in that window. Change theme and UI state in other window. 
3. Get Merge Conflict notification and click on "Show Conflicts"
4. Toggle the terminal a few times which will hide/show the "accept remote/merge" buttons and then you see two "accept merges" and "accept merge" buttons in different locations. 

<img width="1444" alt="image" src="https://user-images.githubusercontent.com/9721254/176324852-d9a13dbd-a1d8-4264-80df-6b09e93be43f.png">

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/commit/cf0cb66d0e7ebc6e18ad53d6242e4f8cba7a076d
