### ISSUE TITLE
Make tabs smaller when `workbench.editor.showTabCloseButton: false`

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#15364]
If user does not want the close button to be visible - vscode could make tabs more narrow to show more tabs. Tabs with changed content could get wider to show the 'dot' denoting unsaved file

![image](https://cloud.githubusercontent.com/assets/1723815/20220777/d73534aa-a7fc-11e6-886c-d2332096537d.png)

![image](https://cloud.githubusercontent.com/assets/1723815/20220927/5f687990-a7fd-11e6-8274-f63de471b237.png)

**Comment by bpasero** [comment]
* [ ] **Verify**: when the tab close button is disabled, the tabs are not leaving room for the dirty indicator until the editor is actually dirty.
