### ISSUE TITLE
VS Code does not work with Gstreamer, python 3.8

### ISSUE THREAD

**Issue by mgabell** [microsoft/vscode#153676]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Install python 2.7 3.8 and 3.9
2. Install gstreamer
3. Connect webcam into Jetson Jetpack 5.0.1 DP (might work on x86 too)
4. Try run basic opencv program to read from /dev/video0
5. sudo python3.8 main.py (does the trick)
6. Running from VS-code does not work

**Comment by bpasero** [comment]
That does not seem like a supported platform, please see https://code.visualstudio.com/docs/supporting/requirements
