### ISSUE TITLE
Ability to add Activity Bar inside Side Bar

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#15362]
Just adding this request as suggested by @bpasero in https://github.com/Microsoft/vscode/issues/1105#issuecomment-259721480

For example setting:

`workbench.activityBar.location = "sideBar"`

![image](https://cloud.githubusercontent.com/assets/1723815/20220215/a3f94ad8-a7fa-11e6-912d-3f65d5e7c7eb.png)

Benefit would be that `Cmd+B` would hide both at the same time - right now one need to hide them separately - they are both related so would make sense to be able to dock Activity Bar inside Side Bar - especially for someone who wants more horizontal space (when working with multiple editor groups)

**Comment by octref** [comment]
Not very likely to happen as we will let extensions contribute custom explorer views:

![](https://github.com/octref/explorer-api-example/raw/master/assets/deps.png)

However, this might be a good candidate for "chaining commands" described in #6617

/cc @Tyriar fyi.

**Comment by Tyriar** [comment]
Yes you could probably write an extension that provides a command that does this, #6617 would allow you to get around needing an extension.

**Comment by zelein** [comment]
@octref Can you link to the relevant issue regarding the custom explorer views in the activity bar that's in your image? I can't seem to find any documentation regarding that feature addition.

**Comment by octref** [comment]
https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample
https://github.com/Microsoft/vscode-extension-samples/blob/master/tree-explorer-sample/USAGE.md
