### ISSUE TITLE
Autocomplete deletes existing text in HTML

### ISSUE THREAD

**Issue by bminaji** [Microsoft/vscode#15365]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Place cursor in front of text
2. Begin typing a open tag
3. When autocomplete appears, press Enter to select it, the first word is deleted
4. In the gif below, the word First will be deleted when the autocomplete is selected

![autocompletebug](https://cloud.githubusercontent.com/assets/1375424/20220880/394369e6-a7fd-11e6-8b34-2889efcbe938.gif)

**Comment by aeschli** [comment]
The behaviour is intended. When using code assist on an exiting tag this help quickly replacing it.
<|span to change it to <div

Closing for now, will reopen of more users don't like the replace.

**Comment by bminaji** [comment]
Thanks for your reply. But, it didn't work this way in 1.6. And in the example that I submitted a tag isn't being replaced, but text.
