### ISSUE TITLE
Support free trial label for extensions in the Marketplace

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#153652]
Ref: https://github.com/microsoft/vscode-vsce/issues/748

Allow extension authors to indicate extensions are Free or Free Trial in the Marketplace
Marketplace will read pricing value from the manifest property Microsoft.VisualStudio.Services.Content.Pricing

CC @prashantvc @isidorn

**Comment by isidorn** [comment]
Let's assign to August, so we do not lose track of this.

**Comment by isidorn** [comment]
This should be done. And does not require any changes in VS Code. Thus closing
