### ISSUE TITLE
Shift + enter shows kernel selector on web

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153617]
1. on https://insiders.vscode.dev
2. Open a jupyter notebook
3. Try pressing the run icon on a python cell
4. See
![Screen Shot 2022-06-28 at 3 57 06 PM](https://user-images.githubusercontent.com/12821956/176317944-e101c6fc-6e78-44c8-a21a-bcfc95200730.png)

5. Now try pressing shift enter while editing the cell to execute it

**Bug**
This brings up the kernel select screen:

![Screen Shot 2022-06-28 at 3 56 08 PM](https://user-images.githubusercontent.com/12821956/176317979-28efb4a5-4ceb-4d22-ae1b-625e9c3049b9.png)

I can't find a way to install a kernels using this

Version: 1.69.0-insider
Commit: e7751367f79f327b8103bee33a07c16817a2c7cd
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Embedder: vscode.dev

**Comment by mjbvz** [comment]
@lramos15 Are you clicking the green arrow? I also have the Jupyter and python extensions installed if that helps  (nightly versions of each)

**Comment by lramos15** [comment]
Hmmm still no popup with extensions installed.

@rebornix any ideas. I don't see a run button even with extensions installed shift + enter does bring up the quick pick though which is probably unexpected 
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/4544166/176515153-206d8040-8c50-4b38-861e-c47134a39875.png">

**Comment by roblourens** [comment]
I think that dialog is gone. I think showing the kernel picker is expected now that we are trying to enable executing python in the web.
