### ISSUE TITLE
modify launch.json Zoom back to 100%

### ISSUE THREAD

**Issue by lisa0621** [Microsoft/vscode#1536]
When I modified launch.json, windows Zoom back to 100%.

**Comment by bpasero** [comment]
@lisa0621 could it be you mean settings.json?

**Comment by lisa0621** [comment]
Debug Node.js then produce .vscode/launch.json

**Comment by bpasero** [comment]
@lisa0621 so to clarify, you zoomed in (from the view menu), then changed launch.json and the zoom was reset?

**Comment by lisa0621** [comment]
Yes!That is what I mean.

**Comment by bpasero** [comment]
Nice catch. You can configure fixed zoom levels in settings to avoid using the view menu each time.
