### ISSUE TITLE
Merge editor should offer action to open regular file

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153690]
Same as when opening a diff editor, a merge editor should offer a way to open the regular file (not in 3 way merge mode).
Same as diff editor it could use an action in the editor title area

![Screenshot 2022-06-29 at 15 31 15](https://user-images.githubusercontent.com/1926584/176448981-01a0b0e4-5261-4ec3-9e27-1efb68c6b39a.png)

**Comment by jrieken** [comment]
Let's move this to July

**Comment by jrieken** [comment]
To verify: 

* open a merge editor
* verify its title bar has a command to open the result file

**Comment by bpasero** [comment]
I wonder if "Open Changes" button should go back to the merge editor then?

![image](https://user-images.githubusercontent.com/900690/181045111-a2396655-c199-4144-8a6e-b49ef8eafc75.png)
