### ISSUE TITLE
The label First Error is uninformative and kind of confusing

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#153600]
Testing #153365

**Comment by Tyriar** [comment]
@sbatten what would you expect it to say?

**Comment by sbatten** [comment]
I'm not sure exactly. something more verbose like "Beginning of list of errors in output"

**Comment by Tyriar** [comment]
How about "Beginning of detected errors for this run"? Can't use something more natural like "compile" or "tests" as a watch/background task could be doing anything

**Comment by sbatten** [comment]
yea i think that's better. yea i started to see the challenge when thinking about it and the fact that it needs to be pretty generic

**Comment by karthiknadig** [comment]
I am a bit late for this, but what is the reason for the first error message label?

**Comment by Tyriar** [comment]
@karthiknadig it's a marker in the buffer so you can quickly jump to it via ctrl/cmd+up, this is more useful in tests when using verbose assertions.

**Comment by Tyriar** [comment]
Example:

![Recording 2022-06-29 at 03 29 32](https://user-images.githubusercontent.com/2193314/176415569-d856a1c2-0f07-41d3-b915-2afa5c03615b.gif)

**Comment by meganrogge** [comment]
there are some issues on windows with the decorations when the terminal gets resized. it looks like a few decorations are getting overlaid in your first and last image #153476
