### ISSUE TITLE
Poor IntelliSense in debug console

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153651]
* stop at a breakpoint
* type the prefix of a variable in scope (`suffi` here)
* quick suggest shows which is nice
* hit escape
* continue typing :bug: no more quick suggest
* manually trigger suggestion via ctrl+space: :bug: no suggestions

https://user-images.githubusercontent.com/1794099/176383072-61822c2a-f5dc-48d7-ba8d-3856ea757a69.mov

**Comment by jrieken** [comment]
My guess is that the completion item provider doesn't take the current prefix into account (when triggered). Let me know if you need consulting

**Comment by roblourens** [comment]
It looks like vscode sent the right request but js-debug didn't return any completions
