### ISSUE TITLE
`"serverReadyAction"` works incorrectly with `"console": "integratedTerminal"` in launch.json with dotnet projects

### ISSUE THREAD

**Issue by tvardero** [microsoft/vscode#153648]
**Does this issue occur when all extensions are disabled?:** Omnisharp is the only extension required

- **VS Code Version:** 1.68.1
- **OS Version:** Win10 Pro x64 21H2 19044.1766
- **.NET Version:** 6.0.5
- **C# Extension Version:** v1.25.0

Bug can be reproduced with `settings.json` empty.

**Setup:**
1. `dotnet new web` to create new clean web project
2. Command palette: `.NET: Generate Assets for Build and Debug` to generate `launch.json` and `tasks.json`.

**Reproduce:**
1. Add line `"console": "integratedTerminal"` to launch configuration.
2. Launch project. First time it will be ok, a browser with `localhost:port` url will be opened.
3. Launch project second time. Now Windows Explorer opens. Each time, until VS Code is restarted.
4. If you change `"action"` to `"debugWithChrome"` in `"serverReadyAction"` section, launching project will open `about:blank` url in Chrome.
5. If you restart your VS Code, you can go back to step 2 of reproduce. In other words, you can successfully launch project only once after each restart of VS Code.

**Video (including setup):**
https://user-images.githubusercontent.com/45442278/176376728-23d9891c-6485-44a4-9554-dfcbdcfe609e.mp4

**Comment by connor4312** [comment]
Ah ha, the key was using mingw64 (git bash works for this)
