### ISSUE TITLE
feat: add a way to debug extension inside a dev container

### ISSUE THREAD

**Issue by mazikiou** [microsoft/vscode#153665]
I have an extension that launches a devcontainer. This extension must be ran inside and outside the devcontainer. It is possible to debug the extension when outside the devcontainer but it is very hard to debug when it is inside the devcontainer. I can only log to the console but can't use breakpoints (vscode debug tools in general).

**Comment by weinand** [comment]
By using the "Remote Development" extensions you can easily debug extension running in a devcontainer.
Just open the extension in the container and press F5.

For details see: https://code.visualstudio.com/docs/remote/containers#_debugging-in-a-container
