### ISSUE TITLE
[scss] highlighting for css variables

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#15368]
- VSCode Version: 1.7.1
- OS Version: Windows 10

When I create a css variable in scss, I get the following syntax issue:

![scss](https://cloud.githubusercontent.com/assets/1571806/20224471/360eb7e2-a804-11e6-8c01-6698e5eeea87.PNG)

When I convert the file to css, the syntax is correct:

![css](https://cloud.githubusercontent.com/assets/1571806/20224472/361376ba-a804-11e6-8b10-c7435cc9c095.PNG)

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#188
