### ISSUE TITLE
UI stops responding while replacing text in a very big file

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#15369]
Open a very big file (28 MB in my case). Replace a text with another text, and the UI stops responding:
![image](https://cloud.githubusercontent.com/assets/14098140/20225464/6f7811ec-a7f8-11e6-8ffd-1644aa939cf8.png)

The file has very long lines, in case that matters...

**Comment by alexandrudima** [comment]
@digeff Every hang is different. Can you please point us to the actual file or to a file that is very similar and reproduces the issue. We would also appreciate the exact search phrase / replace phrase you are using such that we can investigate.

**Comment by alexandrudima** [comment]
Closing until more information is provided.
