### ISSUE TITLE
Wrong "Set Theme" button toggling

### ISSUE THREAD

**Issue by kirushyk** [microsoft/vscode#153663]
Issue Type: <b>Bug</b>

I opened theme extension and click enable / disable fast.
I see "Set Theme" button when extension is disabled and no "Set Theme" when it is enabled.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:37.209Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No
Remote OS version: Linux arm64 4.9.253-tegra

**Comment by isidorn** [comment]
I can repro this. First assigning to @sandy081 for extension details page.

**Comment by kirushyk** [comment]
Cool, thanks @sandy081!
