### ISSUE TITLE
Insertion line overlaps with color preview in CSS

### ISSUE THREAD

**Issue by LarryTheFatCat** [microsoft/vscode#153613]
Does this issue occur when all extensions are disabled?: **Yes**/No

when I was trying to set the background color of my site using CSS, vscode's color preview overlaps with the insertion point causing it to blink and 
![image](https://user-images.githubusercontent.com/83801755/176314360-40ffb44a-957c-4c98-87af-5db2b92d80dd.png)

- VS Code Version: 1.68.1
- OS Version: Windows 11

Steps to Reproduce:

1. Run VsCode
2. Open a CSS file
3. create a class
4. inside the CSS class do background-color: hsl(228, 45%, 44%)(225, 100%, 98%);
5. Put the insertion point on h
6. Press the arrow key left

**Comment by aeschli** [comment]
I can reproduce in Version: 1.69.0-insider, e7751367f79f327b8103bee33a07c16817a2c7cd

Happens with any color value e.g. `foo { background-color: #ff00ff }`

Set the cursor to the column, then do cursor right on the keyboard.

**Comment by alexdima** [comment]
`vscode-bisect` points to https://github.com/microsoft/vscode/compare/b614fb5db84b3ac07fc3e8b12c69c1dd581924ce...93ce4397a2cbc88707c3ed8b34a813b87457568c . @hediet I think we could get the old behavior if we remove the cursor stop before the injected text.

**Comment by LarryTheFatCat** [comment]
I've just noticed that this is fixed, closing this issue because I cannot replicate it anymore... assuming it's been unknowingly fixed
