### ISSUE TITLE
Introduce actions in Default settings to copy/select settings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#15361]
Related #15162 

- Ability to copy/select a setting from default settings

In Default settings editor, If a setting is of boolean or an enum type, provide a dropdown to select the value and copy it. Otherwise just copy it to user/workspace settings.

**Comment by sandy081** [comment]
@bgashler1 @stevencl 

I would need your assistance on the following. I am working on settings story to improve on various aspects. One of those is to provide user a simpler way of copying a setting. Please see the following video and and feedback is very much appreciated and helpful.

Basically there are two kinds of actions
- Select and copy: if a setting is of enum or boolean type, user can select to copy the setting.
- Copy: Otherwise, setting will be copied with empty value.

![nov-11-2016 16-21-54](https://cloud.githubusercontent.com/assets/10746682/20219744/0cef6a74-a82b-11e6-8736-7b84f7dfaf78.gif)

**Comment by sandy081** [comment]
@bgashler1 @stevencl I just pushed the changes. You can see the actions in the default settings editor if you run VS Code out of dev.

**Comment by s130059660** [comment]
Oh, sweet addition.

Is it possible to also copy the comments of descriptors and structures! So that we can immediately know each setting belong to which.
