### ISSUE TITLE
Ability to expand all collapsed regions

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#15363]
In the past it was nice to just scroll and read about all possible settings.
Right now they are all collapsed and one need to click a lot of boxes to open them.
Right click to see the option to expand all would be very useful

![image](https://cloud.githubusercontent.com/assets/1723815/20220684/76d0f0ae-a7fc-11e6-8920-d1759a7b8811.png)

**Comment by aeschli** [comment]
Use Unfold all (Ctrl+K Ctrl+J) to unfold all.

**Comment by sandy081** [comment]
@wallverb Reason to collapse all is to show all available sections of configurations. Given the number of configurations, one can seldom browse through all the configurations. I think `Find` is the only option to look for something in the default settings. Given everything is collapse, it might let user to navigate sections easily than before.

Any other ideas are much welcome.

Thanks

**Comment by wallverb** [comment]
@sandy081 That's a great reason/idea.

What I was only saying that it would be great if there was a right click here:
![image](https://cloud.githubusercontent.com/assets/1723815/20266174/f673ee4a-aa42-11e6-9b2c-e1c9ae1c3cbb.png)

(on `+` itself or collapsed region) to show the `Unfold All / Fold All` option - this would be also helpful in other files as well (not only vscode settings).

I will be ok now knowing there is 'Unfold All / Fold All` command / keyboard shortcut. Thanks

**Comment by sandy081** [comment]
FYI @aeschli
