### ISSUE TITLE
'No elements found' overlaps with source control button

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153612]
Issue Type: <b>Bug</b>

1. Open scm view
2. Start typing to filter down list of commits

**bug**

The `no elements found` overlaps with the commit button

![Screen Shot 2022-06-28 at 3 18 42 PM](https://user-images.githubusercontent.com/12821956/176313229-5aa8414c-0adc-481d-a127-1c6bf82beaf3.png)

VS Code version: Code - Insiders 1.69.0-insider (Universal) (e7751367f79f327b8103bee33a07c16817a2c7cd, 2022-06-28T05:17:52.688Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|11, 6, 5|
|Memory (System)|32.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lszomoru** [comment]
@joaomoreno, I see that the DOM element for the message has [a CSS class](https://github.com/microsoft/vscode/blob/a424998dfd7cd3043c558f0f4b64994f601c1981/src/vs/base/browser/ui/list/list.css#L142-L143) that has a top padding of `40px` hardcoded. This is enough in case there is no action button but it clearly does not work in case we have one. Should we got for a tactical fix to just increase the padding, even though this is also used in other trees?

**Comment by joaomoreno** [comment]
Let's not do anything here. I plan on nuking this message with https://github.com/microsoft/vscode/issues/146806
