### ISSUE TITLE
Extension walkthroughs from extensions in other profiles shown in welcome page.

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#153647]
Testing #153384

Have one profile with GitLens installed and other without. Notice how walkthrough shows up in Welcome page on profile without GitLens

<img width="1653" alt="image" src="https://user-images.githubusercontent.com/12758612/176367825-e2a486d4-c990-442c-9975-9fc2471c41ca.png">

**Comment by lramos15** [comment]
@sandy081 It appears we are handling it correctly here https://github.com/microsoft/vscode/blob/caca6ddb79143cc5c5f244a8fcd527036152fcb4/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedService.ts#L175-L181

**Comment by sandy081** [comment]
@lramos15 I see `unregisterExtensionWalkthroughContributions` is being invoked for gitlens extension when switching profiles, but I do not know why the walk through page is still showing it. I do not know the implementation of it. Can you please investigate from walk through component perspective first to see why it is still being shown?

**Comment by meganrogge** [comment]
I disabled gitlens and used the `reload required` button to reload the window. The walkthrough is no longer there. is that expected? @lramos15

**Comment by meganrogge** [comment]
![Screen Shot 2022-07-28 at 1 34 01 PM](https://user-images.githubusercontent.com/29464607/181632228-56bfad6f-5e67-4046-be84-05cbe06838ca.png)

**Comment by meganrogge** [comment]
I changed profiles to the one with Gitlens still enabled and there's still no walkthrough

**Comment by lramos15** [comment]
> I disabled gitlens and used the `reload required` button to reload the window. The walkthrough is no longer there. is that expected? @lramos15

Hmmm I cannot repro this. Can you provide a gif? If I have the walkthrough open and reload my window the walkthrough page doesn't dissapear

**Comment by meganrogge** [comment]
@lramos15 https://user-images.githubusercontent.com/29464607/181801916-050ac776-7fad-4c5f-9b92-61b0f0c70899.mov
