### ISSUE TITLE
"Toggle Active Conflict In Input 1" confusing name

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#153688]
"Toggle Active Conflict In Input 1" should be called "Accept Current Conflict from Left"
"Toggle Active Conflict In Input 2" should be called "Accept Current Conflict from Right"

When the conflict is accepted you will have to introduce a context menu and then have different command titles:
"Revert Current Conflict from Left"
"Revet Current Conflict from Right"

My worry is that the current naming is too confusing for users.

**Comment by hediet** [comment]
Can you check tomorrows insiders? Do you mean the context menu or the commands?

Didn't get the "Revert" thing - there is a checkbox in the context menu that should indicate its state.

**Comment by hediet** [comment]
Fixed in d04edca5174f5dc14550a32c535f08107534baa7:
![image](https://user-images.githubusercontent.com/2931520/181301751-ff3f1150-6289-4d5e-8854-b3c86b856062.png)

**Comment by isidorn** [comment]
Thanks 👏 
p.s if you want me to verify issues make sure they have the bug label :)

**Comment by hediet** [comment]
I think here it doesn't make much sense to verify, as the screenshot already proves that it works :)
