### ISSUE TITLE
Merge Editor does not having preview merge 

### ISSUE THREAD

**Issue by antaradas94** [microsoft/vscode#153793]
Hi all, have been waiting for this feature for quite sometime.
Tried it out today but unfortunately i dont get the preview merge option as shown. i have updated the git mergeEditor to true. 
Do i need to do some more additional settings ? 
 
A screenshot of the same 
![grafik](https://user-images.githubusercontent.com/29475679/176643817-7a7997ce-9e91-49ae-ab14-7796f7b95a42.png)

Thanks

**Comment by isidorn** [comment]
This should work now, please try it out and let us know what you think about it.
