### ISSUE TITLE
Ctrl+Tab not working when integrated terminal has focus

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15373]
- VSCode Version: Code - Insiders 1.8.0-insider (fb8939b09460ff9fbd40d39056b54c88d5aad9c8, 2016-11-11T13:12:38.741Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-docker|PeterJausovec|0.0.7|
|regex|chrmarti|0.0.6|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|gitlens|eamodio|0.5.5|
|tslint|eg2|0.5.40|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|kustovscode|seanmcbreen|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

---

Steps to Reproduce:

1. Open 2 editors
2. Focus integrated terminal
3. Try to use Ctrl+Tab to cycle through the editors
4. -> bash will interprets it as 'Tab' it seems

**Comment by Tyriar** [comment]
As designed, but I've been wanting to include it in commandsToSkipShell by default for a while now, along with ctrl+shift+tab.
