### ISSUE TITLE
Error Telemetry has errors from processes run inside the extension that may contain PII

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#15374]

**Comment by jrieken** [comment]
This might actually be me... I places I call the [`onUnexpectedError`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/errors.ts#L79)-method. Mostly, when I invoke a language feature provider that fails, like [so](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/suggest/common/suggest.ts#L109). Do those error end up in telemetry or do they just get locked on the console as in dev?

**Comment by ramya-rao-a** [comment]
Yes, the errors do end up in telemetry.

The Error telemetry service gets instantiated for every workbench [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/shell.ts#L276)

The Error telemetry service in turn adds a listener to the `unexpectederrors` . This listener logs the telemetry for the unexpected errors.

Example:  
`Command failed: /*****/go/bin/gocode -f=json autocomplete /****/go/main.go c839
/*******/go/bin/gocode: /*******/go/bin/gocode: cannot execute binary file`

The tool `gocode` is run in a child node process by the Go extension to get completion items

**Comment by ramya-rao-a** [comment]
I'll add an `onUnexpectedExternalError` that does not call the listeners. Using this in place of `onUnexpectedError` in the language feature providers should ensure that errors get logged to console but do not end up in the telemetry.
Thoughts?

**Comment by jrieken** [comment]
I like
