### ISSUE TITLE
Offer an easy way to view the Message on failed tests from the Testing explorer

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#153789]
The request comes from: https://github.com/microsoft/vscode-java-test/issues/1280#issuecomment-903091171

User wants to have a tooltip for the test items showing in the test explorer, displaying some error messages for the failed tests:

**Comment by connor4312** [comment]
There's now a Test Results view, which is the place to go for all your errors and error-related needs.

**Comment by jdneo** [comment]
Hi @connor4312, 

By the way I have an issue about the styling of the test results view, and it's not resolved yet: https://github.com/microsoft/vscode/issues/196521.

Sorry I tried to find some easy reproduce steps with the test sample extension but failed.

**Comment by connor4312** [comment]
That's a general bug in terminal land, it's not unique to the test results panel https://github.com/microsoft/vscode/issues/194156
