### ISSUE TITLE
Debugging extensions in codespaces not working

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#153767]
- Open a codespace for any extension, for example a vscode-extension-samples folder
- Build and run the extension launch config
- A tab with this url opens and 404s: `https://github.com/codespaces/roblourens-vscode-kusto-grwc?folder=%2Fhome%2Fcodespace&payload=%5B%5B%22extensionDevelopmentPath%22%2C%22vscode-remote%3A%2F%2Fcodespaces%252Broblourens-microsoft-vscode-extension-samples-9vj55ghx599%2Fworkspaces%2Fvscode-extension-samples%2Fcodelens-sample%22%5D%2C%5B%22extensionEnvironment%22%2C%22%7B%7D%22%5D%2C%5B%22debugId%22%2C%22b5379fc5-11b0-418b-a85c-163602e2ebe2%22%5D%2C%5B%22inspect-brk-extensions%22%2C%2253601%22%5D%5D`
- That url is suspicious, what is `roblourens-vscode-kusto-grwc`?

I am not sure how extension dev works in codespaces, whose side this would be on, codespaces or us? cc @weinand @connor4312

**Comment by weinand** [comment]
This looks like codespaces. Nothing has changed on our side.
