### ISSUE TITLE
Show git tag instead of sha1

### ISSUE THREAD

**Issue by robsonpeixoto** [Microsoft/vscode#15372]
- VSCode Version: 1.7.1 (1.7.1)
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1. Choose a branch:
![image](https://cloud.githubusercontent.com/assets/124390/20226997/2f7ceea6-a829-11e6-9362-b2e4cd6026a8.png)

2. Show the `sha1` of the last commit, but IMO should be the `tag`
![image](https://cloud.githubusercontent.com/assets/124390/20226974/1574031e-a829-11e6-97cc-a54f767ed437.png)

**Comment by joaomoreno** [comment]
This was fixed in #12584.

The commits in your screenshots don't match. The first indicates `af942df4`, while the second `15a0c2d9`.

**Comment by robsonpeixoto** [comment]
Thanks @joaomoreno
