### ISSUE TITLE
SCM viewlet stuck when creating a commit with empty message

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#153756]
On the latest Insiders on Windows, I tried clicking on the commit button without typing a message and the viewlet seems to be stuck.
I'm able to create a commit with a single space as a message, though.

_Originally posted by @rzhao271 in https://github.com/microsoft/vscode/issues/152702#issuecomment-1170483539_

**Comment by lszomoru** [comment]
Du you have any files that were changed or that are staged? When you click on the button, does an editor open so that your enter a commit message?

**Comment by rzhao271** [comment]
Nothing happens other than the progress bar and the button and input becoming disabled

![Screenshot showing minimal diff along with SCM viewlet being stuck](https://user-images.githubusercontent.com/7199958/176546361-f994f8a6-803d-49c4-bdf4-ee137d16c7d6.PNG)

**Comment by lszomoru** [comment]
Are you able to repro using the same steps when running out of sources? There are couple of fixes that were checked in today. Thanks!

**Comment by rzhao271** [comment]
LGTM on OSS. I see the COMMIT_EDITMSG editor on there, and closing the tab cancels the operation.

**Comment by lszomoru** [comment]
@rzhao271, do you mind testing the same in today's Insiders to make sure that you cannot repro. I want to make sure that there might be an issue that only surfaces when you have particular settings configured. Thank you!

**Comment by rzhao271** [comment]
LGTM, though it took a while for the editor tab to pop up the first time.

**Comment by lszomoru** [comment]
Thank you!
