### ISSUE TITLE
No visual feedback when selecting main button in delete file popup

### ISSUE THREAD

**Issue by dorshinar** [microsoft/vscode#153704]
Issue Type: <b>Bug</b>

There is an accessibility issue in VSCode on MacOS when deleting files. 
When navigating with tabs, the "Cancel" button is wrapped with a clear blue focus ring and so is the "Do not ask me again" checkbox. 
But when tabbing to "Move to Trash" there is no focus ring, and it appears as though no button is focused, even though it is. 

![image](https://user-images.githubusercontent.com/17943918/176474285-d027f70b-feac-49e2-b46b-15b2c1b90f5e.png)
![image](https://user-images.githubusercontent.com/17943918/176474346-18f356ea-898e-4196-9e3c-09794f7ab281.png)
![image](https://user-images.githubusercontent.com/17943918/176474397-8ddc78e0-8852-4eb5-a319-0d01fa05fe19.png)

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 5|
|Memory (System)|32.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id e34c2eee-0215-4c4f-9e50-1910a1e7225b|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.8.6
turbo-console-log|Cha|2.3.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.2
vscode-deno|den|3.13.0
gitlens|eam|12.1.1
prettier-vscode|esb|9.5.0
vscode-pull-request-github|Git|0.44.0
svg|joc|1.4.18
vscode-styled-components|jpo|1.7.0
python|ms-|2022.8.0
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
polacode|pnp|0.3.4
prisma|Pri|4.0.0
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.2.5
svelte-vscode|sve|105.18.1
vscode-icons|vsc|11.12.0
fig|wit|0.0.6
change-case|wma|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30515786
vsclangdf:30486550

```

</details>

**Comment by TylerLeonhardt** [comment]
This appears to be an upstream Electron issue. Assigning to @deepak1556 to handle.

**Comment by deepak1556** [comment]
Not actionable, since the runtime just calls into https://developer.apple.com/documentation/foundation/nsfilemanager/1414306-trashitematurl
