### ISSUE TITLE
Inline Completion API HandleDidShowCompletion is not called as expected when the Intellisense menu is open

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#153754]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: 

Steps to Reproduce:

If an inline completion item is shown when the Intellisense menu is open, the HandleDidShowCompletionItem function does not get called until the completion is accepted. This impacts our telemetry because we send telemetry for completion shown in the HandleDidCompletionItem function. 

I created an extension that can help repro this bug easily - https://github.com/juihanamshet1/HandleDidShowCompletionItem-bug/tree/main/inline-completions

To repro, run the extension linked. Make sure the debug console is open. If the inlineCompletionProvider is called, it'll print a message "inlineCompletionProvider triggered" and if the HandleDidShowCompletionItem is called, it'll print "HandleDidShowCompletion called". In the experimental instance, create a new .ts file and type `// [0,5):` in Line 1. In Line 2, start typing `co`. You'll see an inline completion and a message "inlineCompletionProvider triggered" in the debug console but you won't see handleDidShowCompletion called. This process is documented in the below gif. 

![handleDidShowCompletionItem_bug](https://user-images.githubusercontent.com/86270736/176540493-9e9ea15f-a609-40ac-949b-f7828c361557.gif)

Ideally, the HandleDidShowCompletion should be called as soon as grey text pops up on the screen. If the user scrolls up and down the intellisense menu, the HandleDidShowCompletion should not be called multiple times, just the first time.

Please let me know if I can provide any other info that will be useful here. Thank you!

**Comment by juihanamshet1** [comment]
cc @hediet

**Comment by hediet** [comment]
Verification steps:

* Go to the [monaco playground](https://microsoft.github.io/monaco-editor/playground.html?source=v0.38.0-dev.20230420#XQAAAALTHAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscx0nsh36DddtbtyhsOtw_oZuoS-bntDRvUjkOwcRtcHNwKoOpD9hqF1FLGw7nCYILel_D51TxC02-4FHVi8hAGrk2k0eDf65lWed4cPa_Rg2E4fnivDXhpOU3LxjvUsxFQuRQP78JAs3LeN9EvgxRQiXt-BkmVM5a7umd11908FmletI3P-iV83m1mlbUuDiRj_mtBtCTcoB4wtOil6qGJ2k99U-HEg3od8cphohYH6zWqgpcyYD4mwjlmc0Otp5utG3z5M1OV-00vKTAeBC9kmv9jfwI0QgCg-t9VcgWKgsctUxUU1E9WmTNRAkPc4Q__UHv2RaSG1xuY-17A6PSCK6-ni6JGUlcBjyPEjL3Jx7TjC59pqYD-7nT08IfDTmucCMQCLEP70z-GFyy7w9vYFnb5YtsmAYlq2buOw3OuM2bebDUdVnNsLatFKJtcecCIH5-5O-IIh26aFZ0eS3deDsyOiDc2eqFN4Mybg_vVEI82cuYdWyfx-Id6JYx5s6F5-3X7bIZprZLoDZvi4rZzxjx2muu_zr9lPIOWaGrpStr51CJS8AvF_iCxFynoJkwF5WQtHfNVqwfqUxVNYf1dssxv5YLB-0Tm55npFTtlVWv8mMEFyvNdI0xDC3JcrWQpGty2b0OfPRZF1tEgGEPkCnYasIwJVob_Fq0ysua-2ddeiGbKKUiAEciDdb0YWWFJcq4nQ9izcqzIeCgx4OZSDzg6fUdqp-BJDDlVQByMoGRfG6u1-L_hfBUj0TbrzLGd608ABUjxhvZ1De3g0GBQbCTiDn3mehzuZ6URmXJUKHyMOFt7YYRfd2uuut8PDAm8DCHHy9T3xXuBLCgdG6Mxv7J6joShKdzPoYMl7baLwaOKOloB0Xgg0flP8I0ItZ4CqH62yWvcQLMU4F7U7gxdweS3pNto7ZId-FbwcnrK4GeZOOqFgXGbMwODhKOudCKRjnm4RQe0mPjsQsHGFq64e9RiKgcKX09iJj_YHXRuJ07xz7cG8nNlbBX_AsxZTfuG3WfxV_gubgJdXx70pRrlwscLTUeOOSzyLI6OWBSKetl98haSDoJFzJTTNy6fpNznCQfBN3cxJPaisMuoczP2XO-uPLFA9F5VcTCHEvwheOIfOxLIEHwB7Cp1W2MxY_4_hV5sjox3HrehWUZZJflCiY9B7P8drYPV6CbO6I71mIJyt1WiC3roW3ubKUxKVVFEfrSa0GSXIvuHCTLwe6lpETLG1311riW_-HIXdSSA2d2E94z7KqdBaXzQcFmXV4Erjw7IoLilS5_0fohRA3h80h6sjDFtE1VUb3c0sj-1KjjGtTMnvg9FGT7GBauDC4VbxW4DIU0foLYirQhPipfqtRXoOp6OQEzmPYIbbz6-LLizS4DQg3reFXWA1glIGokcrcueR-uS9cwRcca3QRSQA3XVDoKv90b-zMMzwCBOJWJIwkdNHe72V7jk5vt_hk0RcZhYP5aKp6VQwQLgCnDHgCINXOtvv-iulZqb340G2mFfaj1Z8AmBtfyP-XGvIqXC1C-FZf3rJWodnDXR5NVHqakOMHc9utnXYAEA53arddOk3pT7hb6_AhM7Q-nJmfUJN7C5Q7jdEu0W3Rd3XryJ8YWxtvAzDibVmh7DnULHO2G2K5Zita1G7kavAm5IphVSVjuGyMPPB1GSSVZkwo-TWHL0_6xCCRQYgQws4sbK9p0k_oZ40BYsgvyQiaAp3FTQue4nXHaIEbKQM2GtLnh3N7NpCWjQHNIX_g37Vnox_Woe5SNAORRgkfU6DySQ3o24zF3RSZ4ZxKpJI_6LqjWL0BgjdCcsl7csSnLo6k8eWw2u172bftIporsuMy4w2_XAYyexJCrP-ktDgAZKkYi7avc6ZIlrdq6AqZZKbv8yrsA0mAub3qTWin4WIm8-0rTon0fpTknu6LS3S3g7asxBICueqVMsIJqMzFFiyJd0RBE6ZvJ0LUn0Fygx49xJYBs1tbAIkVAKereZLNb9We6JLo4NAAtAb-cs6Lbv0eZezD__T1m4LuQMIs3q1k1eZuxDipxK4lCrW0dlMTCrfrlSYKvQGINW8F378HsUBB-WN3Nn6ep_q5zDKuZJA6Ge5-W8sCTx38PieIhIRO6uQlW7lo5R45YZK4wKbM0MRB4p7JG5zVejD21fRllLOxUgeT92yy67KjcOPLihqZa6RhEXVx6zLi0A_pG_OPc8W2FNhW_Vy4CcGZs2yC1ftFCq6nxqIkDnG9ij2p8XsZRzbox5jKmRSqKtPWhYq6vSJw4AUVisq8_MYx5Cza-C6BATgrB10gWANisKFIjGZSGv8aDBHUnoqg4hE3YMXDkXf9qA2KURk7ooDgc-qidne0V26BqRCFBNsW-_4S4bg56X_px9zponxbVyGhXKNojkx9Lx3cUQ2Tiw0Flaa93rYbMDQGb6l4xd6_6MARG4csIxpgsG6WXy4Mtc-2J5iYfDggyE7IiWS4wc_423DkxHStTr8f1areX4t12r1C1_tSjsrSECUPXda9ekTlbQgTC-1wEE67agpetNtNj0nAGQQFEOjpd9FPpwz5qLUU0hiP1VcJksYsZET9yX8Lv_u9NeVfQ1PESpsUMkGvRlfple722Pa4wKiGtbPwQP718yN8p6ZQOWJyo1fzNKyMXinxqOysQX9ZAfbMbmvSQngxf5VDttjjhaGiynsccIyKWV94aUZnJVMx_E5wcJ6KaOXi4vXtXTEh6NgbpYpEDzPwBY81__738zsQ)
* Click "save"
* Chose a recent version of the monaco editor (>dev.20230421)
* Verify that "Did show item" shows up in the log when an inline completion item is shown
