### ISSUE TITLE
F2 to rename a link in form `[label](link)` doesn't work correctly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153741]
![image](https://user-images.githubusercontent.com/2193314/176514968-6974f1ac-d786-4737-ae4d-987ee4afab54.png)

Version: 1.69.0-insider (user setup)
Commit: 0e3304bca9e862eddc7e437e2bab8a4a4a4f33c9
Date: 2022-06-29T05:20:28.364Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by mjbvz** [comment]
@Tyriar Can you please share the markdown you are using?

**Comment by Tyriar** [comment]
It's the README.md in vscode repo's root

**Comment by mjbvz** [comment]
How and where are you triggering the rename?

![Screen Shot 2022-06-29 at 12 22 26 PM](https://user-images.githubusercontent.com/12821956/176518982-8f794d73-4600-4201-9c8e-cff65d53dc19.png)

**Comment by Tyriar** [comment]
It's not reproducing now after undoing a bunch of times:

![image](https://user-images.githubusercontent.com/2193314/176519689-f6362953-2905-426a-b890-016d2c01d96e.png)

When it was happening it happened several times in a row. Perhaps the AST was out of date? I also notice that it's 29 characters in my screenshot which matches exactly the `[Visual Studio Code](https://code.visualstudio.com)` on the following paragraph.

**Comment by mjbvz** [comment]
I haven't been able to repo this. Let me know if you still are seeing this in some cases
