### ISSUE TITLE
Built-in PHP validation produces invalid diagnostics

### ISSUE THREAD

**Issue by BladeMF** [microsoft/vscode#153713]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version:
Version: 1.69.0-insider (user setup)
Commit: 0e3304bca9e862eddc7e437e2bab8a4a4a4f33c9
Date: 2022-06-29T05:20:28.364Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
- OS Version:
Windows 11 21H2 22000.739
Steps to Reproduce:

1. Create the following file:
```php
<?php

$asd = 5;
$<>
```
2. Save file
The built in PHP validation (controlled by `"php.validate.enable": false,`) creates these diagnostics:
```
            {
                "range": {
                    "start": {
                        "line": 3,
                        "character": 0
                    },
                    "end": {
                        "line": 3,
                        "character": 1.7976931348623157e+308
                    }
                },
                "message": "syntax error, unexpected end of file, expecting variable or \"{\" or \"$\"",
                "severity": 1
            },
```
`character` must be an integer. Disabling the PHP validation solves that problem.

**Comment by roblourens** [comment]
What problem is that causing? I suppose it is an integer, just a big one

**Comment by BladeMF** [comment]
Apart from them just being wrong, these diagnostics are then sent to the language server which then crashes.

**Comment by roblourens** [comment]
Weirdly enough, a range from 0 to `Number. MAX_VALUE` has special treatment to be rendered from the first non-whitespace character: https://github.com/microsoft/vscode/blob/6d24a019d8784650fe1a63b7d7326f2d206104af/src/vs/editor/common/services/markerDecorationsService.ts#L168

This line has existed since day 1 so it has no history, but tells me that this kind of diagnostic range is expected to exist.

Just to help me understand the problem, can you tell me which language server, and crashes in which way? Overflowing an int? This is definitely weird, yes, but doesn't feel completely wrong.

**Comment by BladeMF** [comment]
The language server in question is `phpactor` (there is a git hub repo), and I think it crashes tyring to find that offset in the document. It will be difficult to do a replication of that bug since it was a while ago. What does this specific case do? Can you find the relevant LSP specification?

**Comment by roblourens** [comment]
When does one LSP server pull diagnostics from the client? I don't understand that scenario

**Comment by BladeMF** [comment]
I think when code actions are requested and diagnostics are sent as a context.

**Comment by roblourens** [comment]
I could change the code but I don't think that even solves the problem

- LSP doesn't forbid this, and phpactor should be able to handle it even though it's odd
- phpactor should not crash for totally invalid data anyway
