### ISSUE TITLE
explorer.sortOrder is wrong

### ISSUE THREAD

**Issue by xialvjun** [microsoft/vscode#153780]
Issue Type: <b>Bug</b>

I set `explorer.sortOrder="default"`, and it should sort by names and folder is before files. But I got this order:

```
dist\assets\index.0a012862.js
dist\assets\index.0c1e1f16.js
dist\assets\index.1bc03fc5.js
dist\assets\index.2c1b5fb4.js
dist\assets\index.02c8339f.js
dist\assets\index.2e9b4d47.js
dist\assets\index.03b116d0.css
dist\assets\index.3f3edc51.css
dist\assets\index.4cc7e324.css
dist\assets\index.4f05da49.js
dist\assets\index.5b4b210f.js
dist\assets\index.5ba44327.js
dist\assets\index.6c7ccfbd.css
dist\assets\index.6f609b4b.js
dist\assets\index.7b2a9cef.js
dist\assets\index.7dc79cce.css
dist\assets\index.7f0ddbda.js
dist\assets\index.8b248b8e.css
dist\assets\index.8dc964ab.js
dist\assets\index.10a10903.css
dist\assets\index.10cf7294.js
dist\assets\index.12c0b60f.js
dist\assets\index.37d9ab81.js
dist\assets\index.40b7db5b.js
dist\assets\index.41b4f80a.js
dist\assets\index.46af096c.js
dist\assets\index.48d6443d.js
dist\assets\index.58d18182.js
dist\assets\index.67f5a963.js
dist\assets\index.88b51573.js
dist\assets\index.106b7466.css
dist\assets\index.162a5617.js
dist\assets\index.317e4ee0.js
dist\assets\index.323afc53.js
dist\assets\index.535a6e4a.js
dist\assets\index.625bec67.js
dist\assets\index.762f35cd.js
dist\assets\index.903e8bae.js
dist\assets\index.3419cae6.css
dist\assets\index.3594c09f.js
dist\assets\index.4172b307.js
dist\assets\index.5756e493.css
dist\assets\index.9673cf07.js
dist\assets\index.31463c1a.js
dist\assets\index.19360229.js
dist\assets\index.65666843.js
dist\assets\index.a2e0fdaf.js
dist\assets\index.a98f4dee.js
dist\assets\index.a35067a8.js
dist\assets\index.a2590129.js
dist\assets\index.a9543255.js
dist\assets\index.aec2a17c.js
dist\assets\index.b17b552a.js
dist\assets\index.bb13c31f.js
dist\assets\index.beb3d251.css
dist\assets\index.c6ceeef1.js
dist\assets\index.c1637c9a.js
dist\assets\index.ca1d9afa.js
dist\assets\index.ceae3f6f.js
dist\assets\index.d0b29815.js
dist\assets\index.d6ba090b.js
dist\assets\index.db66d5eb.css
dist\assets\index.e8d57a9c.css
dist\assets\index.e677ab36.js
dist\assets\index.e8806e59.js
dist\assets\index.eede9162.js
```

You recognize the number value in file name ? That's rediculous. Treat file name as a string. Don't try to recognize the int value in it, it's meaningless.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (5.11GB free)|
|Process Argv|--crash-reporter-id 324cbe38-ee0e-4cbc-9ab4-e3273d31941c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
slidev|ant|0.3.3
markdown-mermaid|bie|1.14.2
better-toml|bun|0.3.2
gitlens|eam|12.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
foam-vscode|foa|0.18.5
vscode-graphql|Gra|0.4.13
todo-tree|Gru|0.0.215
RelativePath|jak|1.5.0
svg|joc|1.4.18
svn-scm|joh|2.15.5
language-koka|kok|2.0.4
vscode-format-context-menu|lac|1.0.4
caddyfile-support|mat|0.2.0
vscode-language-babel|mgm|0.0.36
import-sorter|mik|3.3.1
dotenv|mik|1.0.1
compare-folders|mos|0.22.2
vscode-less|mrm|0.6.3
remote-containers|ms-|0.238.2
remote-ssh|ms-|0.82.1
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-jest|Ort|4.6.0
vscode-template-literal-editor|pli|0.10.0
vscode-yaml|red|1.8.0
rust-analyzer|rus|0.3.1107
sort-lines|Tyr|1.9.1
codelf|unb|11.7.0
vscode-lldb|vad|1.7.0
blox|vsb|1.0.5
volar|Vue|0.38.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by xialvjun** [comment]
In above order, `dist\assets\index.4172b307.js` is under `dist\assets\index.67f5a963.js`.

But:

```js
['dist\assets\index.4172b307.js', 'dist\assets\index.67f5a963.js'].sort((a, b) => a.localeCompare(b));   // you'll get 4172b307 is above 67f5a963
```

**Comment by lramos15** [comment]
This is because we use a numeric international collator https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator for simple sort the way you described please add the following to your settings: `"explorer.sortOrderLexicographicOptions": "unicode"`
