### ISSUE TITLE
pls help

### ISSUE THREAD

**Issue by Shino933** [microsoft/vscode#153784]
Issue Type: <b>Feature Request</b>

i accidenty deleted code written in a css file how can i recover it back,the file itself is not deleted but all of the code is deleted , pls help

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Maybe look at https://code.visualstudio.com/updates/v1_66#_local-history

To get to the Timeline view, open Command Palette (F1) and type "timeline"
