### ISSUE TITLE
Markdown: HTML Coloring regression?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#1537]
<img width="473" alt="screen shot 2015-12-21 at 14 12 57" src="https://cloud.githubusercontent.com/assets/900690/11931410/f8f583bc-a7ec-11e5-87fb-5f17874d9e2e.png">

**Comment by aeschli** [comment]
Seems to work in the latest
![image](https://cloud.githubusercontent.com/assets/6461412/12296590/fa821ea6-ba08-11e5-9e69-0a3e8a7b119e.png)

**Comment by bpasero** [comment]
![screen shot 2016-01-29 at 12 22 44](https://cloud.githubusercontent.com/assets/900690/12674391/0febcfea-c683-11e5-959e-11f2b85da98c.png)

**Comment by bpasero** [comment]
@aeschli still seeing red coloring in markdown files

**Comment by aeschli** [comment]
It has to do with the 4 spaces ahead of the html code. The tokenizer decides it is a code block.
It's not a regression, has been like that also in Monaco
![image](https://cloud.githubusercontent.com/assets/6461412/12676519/37faeb78-c693-11e5-8a42-d98f9a1e77f6.png)

Assigning to you, @bpasero , as you maintain Markdown support.

**Comment by bpasero** [comment]
OK!
