### ISSUE TITLE
Does not detect repository if the media is not formatted in NTFS

### ISSUE THREAD

**Issue by omidshojaee** [microsoft/vscode#153795]
Does this issue occur when all extensions are disabled?: Yes/No Extensions have no impact on this issue.

- VS Code Version: 1.69.0-insider
- OS Version: Windows 10 Pro 21H2 build 19044.1766

Steps to Reproduce:

1. Have a USB drive formatted in anything but NTFS
2. Create a folder, initialize git inside it, open the folder in VS Code
3. VS Code does not detect the repository
4. Reformat the drive in NTFS and repeat the above steps
5. Everything is ok.

I've tested this with 2 USB drives, with exFAT and NTFS.

This creates issue when I need to use my USB drive on Mac and Windows because Mac does not support NTFS out of the box.

**Comment by lszomoru** [comment]
Could you please use [the following steps](https://github.com/microsoft/vscode/wiki/Git-&-SCM-Issues#set-log-level-command) to enable trace logging, and then reopen the repository. After that could you please share the contents of [the Git output channel](https://code.visualstudio.com/docs/editor/versioncontrol#_git-output-window)? Thank you!

**Comment by omidshojaee** [comment]
It works on exFAT partition formatted by Disk Utility of macOS.

It doesn't work on exFAT partition formatted by Windows.

Right now I don't have access to a Windows machine for a week. Please keep
this issue open.

**Comment by omidshojaee** [comment]
Apparently the issue is that Git is dubious about the ownership of the directory on exFAT partition if it is created by Windows, so I have to add an exception.
