### ISSUE TITLE
Edit Session: Warn before applying if the branch commit hash does not match the one where the edit session was saved

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#153759]
Testing #153386

In my case I had the wrong branch checked out, and the saved session got applied to it.

**Comment by joyceerhl** [comment]
It's no longer possible to apply an edit session to a branch with a mismatched SHA.

**Comment by joyceerhl** [comment]
Verification
1. Open https://insiders.vscode.dev/github/microsoft/vscode, make some changes and run `Store Current Edit Session` from palette
2. Open https://insiders.vscode.dev/github/microsoft/vscode/tree/release/1.71, run `Resume Latest Edit Session`
3. Verify that the edits are not applied
