### ISSUE TITLE
Commit Action button - label should be adopted for protected branches

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#153787]
Testing #153317

**Comment by lszomoru** [comment]
Fixed with https://github.com/microsoft/vscode/commit/57609a19dad75b0c1fa324578888fa0ceedb53e7

**Comment by lszomoru** [comment]
Verification steps:
* Launch the latest VS Code Insiders
* Open a folder/workspace that contains a git repository 
* Ensure that the `scm.showActionButton` setting is enabled
* Ensure that all three properties of the `git.showActionButton` setting are enabled
* Use the `git.branchProtection` setting to enable branch protection for the current branch
* Make a change to a file:
  * Confirm that the "Commit" action button is shown and it has the `$(check)` codicon 
* Set the `git.branchProtectionPrompt` setting to `alwaysCommitToNewBranch`
  * Confirm that the "Commit" action button is shown and it has the `$(git-branch)` codicon

**Comment by DonJayamanne** [comment]
@lszomoru not sure what I'm doing wrong, but this doesn't seem to work for me.
**See below.**

Version: 1.70.0-insider (Universal)
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:17:37.262Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

![Screen Shot 2022-07-27 at 10 57 52](https://user-images.githubusercontent.com/1948812/181137613-cb048c2f-8c81-4f6e-9f7e-45368853f4f0.png)

**Comment by lszomoru** [comment]
@DonJayamanne, this looks like a regression. Re-opening the bug.
