### ISSUE TITLE
should the commit button be hidden when there are no staged changes?

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#153707]
Testing #153317
I noticed this bc the button made me think that I had forgotten to commit changes I had staged
<img width="1585" alt="Screen Shot 2022-06-29 at 11 32 53 AM" src="https://user-images.githubusercontent.com/29464607/176476966-3c96c453-6644-4e80-9719-1cd8d55f86b7.png">

**Comment by lszomoru** [comment]
One thing to keep in mind is that depending on user settings one can commit changes that are not yet staged. Next milestone I will take a look at the various settings and I will factor in the settings value in the logic that displays the commit action button.

**Comment by heartacker** [comment]
this would address 
https://github.com/microsoft/vscode/issues/135992#issuecomment-1169373862

👍

**Comment by lszomoru** [comment]
@meganrogge, could you please share the following user settings:
- git.enableSmartCommit
- git.suggestSmartCommit
- git.smartCommitChanges

**Comment by meganrogge** [comment]
Not sure what they were when i encountered this (probably whatever is specified in the TPI), but they're currently

1. false
2. true
3. all

**Comment by lszomoru** [comment]
The `git.enableSmartCommit`, `git.suggestSmartCommit`, and `git.smartCommitChanges` settings are now factored in when deciding whether to enable/disable the "Commit" action button. The "Commit" action button will show as enabled in case one of the following commands is true:
* git.enableSmartCommit === true && git.smartCommitChanges === 'all'
* git.enableSmartCommit === true && git.smartCommitChanges === 'tracked' && stagedChanges > 0
* git.enableSmartCommit === false && git.suggestSmartCommit === true

**Comment by heartacker** [comment]
@lszomoru could it be hide entirely(not just disable) when git.enableSmartCommit === false && git.suggestSmartCommit === false

![image](https://user-images.githubusercontent.com/1876302/180728506-c17b2db4-637b-4deb-a844-c503c01a7a75.png)

and show them when there are staged files

**Comment by lszomoru** [comment]
@heartacker, I will continue to monitor customer feedback and will adjust the behaviour accordingly.
