### ISSUE TITLE
Same issue using Arch and KDE Plasma(Wayland).

### ISSUE THREAD

**Issue by Ikaberry202** [microsoft/vscode#153801]
Same issue using Arch and KDE Plasma(Wayland).
But, this error does not appear when opening it for the first time. (Delete all configuration files or reboot the system and open vscode for the first time)
@deepak1556 
```
Version: 1.67.1
Commit: da15b6fd3ef856477bf6f4fb29ba1b7af717770d
Date: 2022-05-10T21:35:59.370Z
Electron: 17.4.3
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 5.17.7-arch1-1
```

_Originally posted by @wc7086 in https://github.com/microsoft/vscode/issues/146422#issuecomment-1126973297_

**Comment by roblourens** [comment]
Why is this a new issue when the previous one is still open?
