### ISSUE TITLE
Opening untrusted files in a trusted workspace gets remembered forever, without the user's awareness

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153816]
The first time I attempt to open a file which is in an untrusted location, in a trusted workspace (can simply happen by running `code FILE` in a terminal), I get this:

![image](https://user-images.githubusercontent.com/22350/176683893-6655cbd7-5727-4191-930a-110a97a57475.png)

Once I click `Open`, pretty much *any* file in untrusted locations will be openable in this workspace without prompt. This decision persists across Code restarts.

---

A few things are problematic here:

- The dialog isn't explicit in declaring that my decision applies to *any* file in untrusted locations.
- The dialog isn't explicit that my decision to open will automatically be made for me in the future.
- I couldn't find any way to revert this decision. Shouldn't the Workspace Trust editor have a checkbox for this? 

I had to resort to the `Developer: Log Storage Database Contents` command to find why this was happening, it was very confusing.

**Comment by sbatten** [comment]
fair feedback, we could definitely hook this up in the workspace trust editor and tweak the wording of the dialog. trying to keep the dialog as concise as possible would be ideal. let me know if you have a suggestion that would make this clear.
