### ISSUE TITLE
Viewing derived class variables while hovering the cursor over a base class pointer (C++)

### ISSUE THREAD

**Issue by dhiraj113** [Microsoft/vscode#15388]
Is it possible to view the member variables of a derived class during debugging by hovering the cursor over a base class pointer that points to an object of the derived class. 

Curious to know if visual studio code or debuggers in general support this feature.

Currently, visual studio code only shows the base class variables when I hover the cursor over the base class pointer pointing to a derived class object.

Any help is greatly appreciated.

- VSCode Version: 1.7.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. 
2.

**Comment by aeschli** [comment]
Please file this issue against the extension that you use to debug C++.

For https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools this would be https://github.com/Microsoft/vscode-cpptools/issues
