### ISSUE TITLE
Simple file picker isn't showing directories when I clear everything except C:/

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153828]
Repro:

1. On Windows open test resolver window
2. Open folder
3. Delete everything except `C:/`

![Recording 2022-06-30 at 07 46 21](https://user-images.githubusercontent.com/2193314/176707246-3e2bf5d2-f6c7-4df3-818a-20ca429b41d2.gif)

**Comment by alexr00** [comment]
I'm not able to reproduce this, even when I select the entire series of subfolders before `C:/` before deleting. Is this on a VM?

**Comment by Tyriar** [comment]
No folder, just test resolver. It's an easy repro for me:
![Recording 2022-07-06 at 05 35 45](https://user-images.githubusercontent.com/2193314/177551373-740fa8be-8582-48bb-a874-e1eb003c8f73.gif)

Code - OSS about:

Version: 1.69.0
Commit: Unknown
Date: Unknown
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by alexr00** [comment]
Your slashes are going the wrong way, which is suspicious. How do you launch Code - OSS?

**Comment by alexr00** [comment]
I've repro'd the slashes, but nothing I try will cause the missing directories to repro. Only difference I see is that I am on Windows 11 and you are on 10. Can you try swapping the separator on the resource label formatter?

https://github.com/microsoft/vscode/blob/e12b04eb82f92243350baeb1c91ec6baa71afebe/extensions/vscode-test-resolver/package.json#L44-L55

If that doesn't resolve it then we'll set up some time to debug.

**Comment by Tyriar** [comment]
Regardless of the `separator` value above it doesn't work for both `\` and `/`. Is there anywhere of interest I can debug into? Where does the trigger character code live?

**Comment by Tyriar** [comment]
We debugged into this together, seems related to the URI.path being `/C:` (or `/c:`) and not `/c:/`

**Comment by alexr00** [comment]
After our debugging yesterday this started to feel familiar: https://github.com/microsoft/vscode/issues/143308
