### ISSUE TITLE
Delete should respect user preferences regarding confirmation

### ISSUE THREAD

**Issue by papadi** [Microsoft/vscode#1538]
I have windows configured so that I don't need to confirm deletions. So on Windows explorer, when I hit DEL, the selected file is moved to the recycle bin directly. Many applications respect this and do not ask for confirmation either (eg. Visual Studio). It seems that VS Code does not respect this setting and ask for confirmation. This is wrong behavior.

**Comment by nonbeing** [comment]
+1

**Comment by papadi** [comment]
I wouldn't go that way, but maybe. VS Code seems to be very configurable anyway. But default behavior should be to use Windows settings.

**Comment by michaeldaw** [comment]
I'd like to see a setting for this as well.

**Comment by bpasero** [comment]
Introduced a new `explorer.confirmDelete` setting that allows to disable the confirmation dialog if the delete is using the trash. 

This can also be set via the dialog by checking the "Do not ask me again" checkbox:

![image](https://user-images.githubusercontent.com/900690/31275975-d700530c-aa99-11e7-95da-c76fc14dc4f8.png)
