### ISSUE TITLE
Commit Acton button - disable button while merge is in progress

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#153888]
1. Open a folder/workspace that contains a git repository
2. Create a topic branch
3. Make changes to main and the topic branch that would result in a merge conflict
4. Merge main into the topic branch to get a conflict
Expected: commit action button is disabled
Actual: commit action button is enabled

**Comment by joyceerhl** [comment]
Also, while the commit action button is disabled, the commit button above the input box is not:

![image](https://user-images.githubusercontent.com/30305945/177419777-5f72bf87-4566-4d1b-bd8c-c908f17da6a5.png)

**Comment by lszomoru** [comment]
That is expected. At the moment the enablement is only toggled for the commit action button and not the commit action in the toolbar.
