### ISSUE TITLE
CodeLens is not on the correct place

### ISSUE THREAD

**Issue by kisstkondoros** [Microsoft/vscode#15389]
- VSCode Version: 1.8.0-insider (d3f14897)
- OS Version: any

Steps to Reproduce:

1. install an extension with codelens provider
2. have codelens in the active text editor 
3. change the zoom level to 2 (view menu -> zoom in)
4. the codelens is not in the correct place

Related issue and commit in vscode repo
#13241
39f6fded66f6401b5cbda928e14bdcdd25c5c7b9

Forwarded from https://github.com/kisstkondoros/codemetrics/issues/8

![image](https://cloud.githubusercontent.com/assets/14231157/20233966/c1ed4492-a875-11e6-8b1c-732650cfc200.png)

**Comment by eamodio** [comment]
@kisstkondoros fwiw I can't repro this on fb8939b09460ff9fbd40d39056b54c88d5aad9c8. Can you?

**Comment by kisstkondoros** [comment]
🎆 me neither, was fixed in the meantime
