### ISSUE TITLE
Improve inlay hints background color contrasts

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#153889]
We have received feedback that inlay hints blend in with the code too much. We aren't eager to tackle that with changing font sizes because that can "harm" readability. Instead we should tweak the colors, esp for our default themes

**Comment by daviddossett** [comment]
Looking at a combination of slight color changes and some minor padding/border radius tweaks to make them look like a visibly different element and less like highlighted regular code. An example for dark+:

<img width="337" alt="CleanShot 2022-07-22 at 13 45 31@2x" src="https://user-images.githubusercontent.com/25163139/180565350-ffd0f1d4-c235-4041-a7af-24a8ef60cef8.png">

**Comment by misolori** [comment]
Adding to the list to make sure we look at the current line highlight color in relation to the inlay hints:

![image](https://user-images.githubusercontent.com/35271042/185179719-d5201c10-b43e-4067-88bd-0f62f6f80af7.png)

**Comment by jrieken** [comment]
@daviddossett Did you push these changes or are these changes anywhere to be applied for August? Otherwise I'll move this to September

**Comment by daviddossett** [comment]
Moved to September—I have the draft PR but I didn't consider the compact settings yet.

**Comment by jrieken** [comment]
ping @daviddossett

**Comment by daviddossett** [comment]
Made changes to all four base theme types. The most noticeable changes will be in the high contrast and light themes. The dark had decent contrast already but I tweaked it a bit. Let me know what you think.
