### ISSUE TITLE
Workbench - Improve experience for first time users

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15383]

**Comment by sandy081** [comment]
@chrmarti Let me know what are the expectations from me here and how I can be helpful.

Also there is some work I am doing to improve various aspects of Settings/Keybindings management (here)[#15162) which might in-line with improving UX in general in this area.

**Comment by chrmarti** [comment]
I'd like to let you know what I'm up to and get your feedback and also the feedback you get in discussions in your lab, if there is any. The idea, I understand, is to build more awareness of what the other lab is working on. E.g., there might be opportunities to briefly talk about what I'm doing at your standup meetings.

**Comment by chrmarti** [comment]
Also: #207, #17119 (opening without folder)
