### ISSUE TITLE
SCM: Button list row should never focus on click

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153808]
This should not be a valid state:

![image](https://user-images.githubusercontent.com/22350/176677634-46d5d0f8-8565-4d59-9986-b380c58c09fa.png)

It should automatically switch to this:

![image](https://user-images.githubusercontent.com/22350/176677670-b3951d90-5dc5-4dfe-a23f-429cc0ec30c6.png)

[This](https://github.com/microsoft/vscode/blob/8045df1b9423e233a79306a90257c28fc7e39a4e/src/vs/workbench/contrib/scm/browser/scmViewPane.ts#L2385-L2386) is how the SCM Input does it.

**Comment by sandy081** [comment]
I am seeing this state when I am navigating using up/down buttons. Is it expected?

![image](https://user-images.githubusercontent.com/10746682/176861304-a7c2e8f4-fe46-4cc5-86ec-2ad8e320f4d2.png)

![image](https://user-images.githubusercontent.com/10746682/176861335-50fed15f-e1e4-4ebf-b3ae-46e7f3a256a1.png)

**Comment by lszomoru** [comment]
That is probably unexpected, but I will let @joaomoreno confirm that.

**Comment by joaomoreno** [comment]
Yeah, just like the text box. The list doesn't support completely disabling it at the model layer. We can only disable it at the click operation.
