### ISSUE TITLE
git fetch error

### ISSUE THREAD

**Issue by siteseer** [microsoft/vscode#153848]
[2022-06-30 18:32:51.418] /xxx/.vscode/extensions/eamodio.gitlens-12.1.1/dist/webpack:/gitlens/src/env/node/git/shell.ts:209:6
Error: Command failed: /opt/rh/rh-git227/root/usr/bin/git -c core.quotepath=false -c color.ui=false fetch
/opt/rh/rh-git227/root/usr/libexec/git-core/git-remote-https: error while loading shared libraries: libcurl-httpd24.so.4: cannot open shared object file: No such file or directory

git is loaded correctly
i can run this command from outside vscode
and from inside vscode from a terminal
any ideas why this is failing when i fetch from the gitlens plugin ?

**Comment by lszomoru** [comment]
@siteseer, could you please file this issue in [the extension's repository](https://github.com/gitkraken/vscode-gitlens/issues)? Thank you!
