### ISSUE TITLE
Copying files always hangs at vulkan-1.dll

### ISSUE THREAD

**Issue by VanHoevenTR** [microsoft/vscode#153837]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.68.1
- OS Version: Windows 11

**Decscription:**
When I extract files to my disk, it always hangs at vulkan-1.dll for 5 minutes, even VS Code is not running. It also happens on Windows 10. 

Why is it always happen like that?

I'm using portable version. 

![image](https://user-images.githubusercontent.com/70694330/176728266-f731b33b-ef36-4bd7-a5b3-3da48efc1ebd.png)

**Steps to Reproduce:**
1. Download .zip 64-bit https://code.visualstudio.com/download
2. Extract all to desired location

**Comment by lramos15** [comment]
@bpasero Any ideas here? I feel like this would be file system or electron related.

**Comment by bpasero** [comment]
How can it be Electron related?

**Comment by lramos15** [comment]
> How can it be Electron related?

Apologies you're right there is no way it can be electron related. I'm confused if it is even VS Code related since the user states VS Code isn't even running. Do you have any suggestions for how to diagnosis this?

**Comment by bpasero** [comment]
Possibly some AV software running?

**Comment by lramos15** [comment]
Closing as this seems unrelated to VS Code since it happens when VS Code is not open

**Comment by lramos15** [comment]
> Where should I report this issue then?

May want to contact windows support. I just tried on a fresh install of W11 and extract portable without issue
