### ISSUE TITLE
Improve Merge Editor Story For Files Having/Getting Conflict Markers

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153800]
![Recording 2022-06-30 at 12 44 23](https://user-images.githubusercontent.com/22350/176658566-13cbf14d-1178-4f04-bb12-66d5e43312d1.gif)

**Comment by hediet** [comment]
Related: #151403

**Comment by lszomoru** [comment]
@hediet, I believe that this can also be closed as a duplicate, no?

**Comment by hediet** [comment]
This is not a duplicate, as this is about opening the 3 way merge editor from the decorations.

**Comment by misolori** [comment]
Didn't we previously have an option in the codelens to open the merge editor or did that not get added?

**Comment by jrieken** [comment]
No, that didn't get added. We have the "normal/old" lenses to resolve individual conflicts but @hediet and I weren't sold on the idea of repeating a "open in merge editor"-command there. Code lens should be contextual and not global commands.

**Comment by misolori** [comment]
Tried this out today and it definitely feels strange with just the label, I think an icon might help it go a long way:

![CleanShot 2022-08-18 at 10 25 20](https://user-images.githubusercontent.com/35271042/185457257-fb817dda-ffe0-476e-bf4e-1f4292dd7534.png)

**Comment by daviddossett** [comment]
👍 for using an icon to at least be consistent with other icon buttons w/ labels (e.g. notebooks toolbar). Originally we had this icon along to toggle between the raw file and merge editor views. Could use it with this new label too. `git-merge` felt out of place as an icon choice to my eyes.

<img width="644" alt="CleanShot 2022-08-18 at 10 42 57@2x" src="https://user-images.githubusercontent.com/25163139/185460190-0d652b9c-a4a7-4cb6-8958-80e42a72f0f7.png">

**Comment by daviddossett** [comment]
> or ultimately use the "blue" in-editor button

This was my next idea too. I like this since even with text I'm not sure I'd always notice the button in the toolbar.

I do think it would be interesting to explore the notion of a single prominent action in the editor toolbar for use beyond just this scenario. Another example: I think the Python extension uses a green "run" icon but I recall that being hard for users to spot. I'll create an issue to explore this as a general pattern.

**Comment by jrieken** [comment]
Re-opening and fixing this with the "blue button"

**Comment by jrieken** [comment]
The blue button feels more natural. This is what I'll be PR'ing

https://user-images.githubusercontent.com/1794099/185897823-c5a50712-c39a-4098-8893-817badfb03c4.mov

**Comment by gjsjohnmurray** [comment]
Looks good but is there a risk that if I accidentally click twice, slowly, over "Open in Merge Editor" I'll inadvertently trigger "Accept Merge" on the merge editor?

**Comment by jrieken** [comment]
> Looks good but is there a risk that if I accidentally click twice,

🤷 don't click twice? I see the risk but it's also not unique to this UX but possible with any button that causes an in-place change

**Comment by IllusionMH** [comment]
@jrieken is there a chance to hide/disable Accept Merge button for couple of seconds after switch?

**Comment by jrieken** [comment]
To verify (see https://github.com/microsoft/vscode/issues/153800#issuecomment-1222147149)

* open a file
* cause a merge conflict in that file
* make sure the blue button with "Open in Merge Editor" shows

**Comment by hediet** [comment]
> 🤷 don't click twice?

Actually it happens to me from time to time that I accidentally double-click, especially after the gym and with a sensitive mouse ;)

**Comment by daviddossett** [comment]
After using this for a few days I think I actually preferred the toolbar option. Opened #159195 to explore this further as a general pattern.

**Comment by vai0** [comment]
also finding it a bit annoying there's a big blue "Open in Merge Editor" button when I already know about it, and prefer not to use it.
