### ISSUE TITLE
Creating Interactive Window fails in VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#153850]
`
Failed to request creation of interactive window from VS Code.
`

https://github.com/microsoft/vscode-jupyter/runs/7137313499?check_suite_focus=true

The following code fails in Jupyter extesnion
```typescript
        const { inputUri, notebookEditor } = (await commands.executeCommand(
            'interactive.open',
            { viewColumn: ViewColumn.Beside, preserveFocus: hasOwningFile },
            undefined,
            controllerId,
            resource && mode === 'perFile' ? getInteractiveWindowTitle(resource) : undefined
        if (!notebookEditor) {
            throw new Error('Failed to request creation of interactive window from VS Code.');
        }
```

**Comment by DonJayamanne** [comment]
@rebornix isn't it possible this is a regression, we haven't run into this in the past.
Discussed in standup and we feel this might have to be addressed before the release (at least until we know its not a regression).

**Comment by rebornix** [comment]
I'm not seeing any change that we pushed in notebook/iw land potentially related to this. It looks like a racing issue when IWs are created and deleted then re-created quickly. I couldn't reproduce this manually right now. Added logs to the iw creation so we can't debug what's going on if we have more reliable reproduce.
