### ISSUE TITLE
Finalize debugger.uiMessages API

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#153842]
Continuing https://github.com/microsoft/vscode/issues/142870

This is just a flag in package.json

Example:

```
"uiMessages": {
  "unverifiedBreakpoints": "There was a problem configuring your breakpoints. Click [here](command:js-debug.showTroubleshootingView) to troubleshoot your launch configuration."
}
```

In this case, vscode is in control of when and where to show this message.

**Comment by jrieken** [comment]
Is `uiMessages` a good name? Drop the `ui`?

**Comment by roblourens** [comment]
If I see some "messages" related to a debugger, I first think of something like DAP messages. But if `uiMessages` feels awkward I don't have a strong opinion.

**Comment by jrieken** [comment]
`strings` 🏅
