### ISSUE TITLE
Proposal: Remove ES5 Class Compatibility to speed up Extension APIs

### ISSUE THREAD

**Issue by qingpeng9802** [microsoft/vscode#153852]
### Motivation:
Through experiments, we found that the current implementation (decorators solution  https://github.com/microsoft/vscode/pull/68121) which is introduced by (ES6 API issue https://github.com/microsoft/vscode/issues/68698) for ES5 compatibility has a great impact on the extension APIs' performance.

### Experiments:
In this [demo extension](https://github.com/qingpeng9802/demo), the extension calls `new Position()`. In general, the bottleneck should be the search of prefixSum, however, we found the bottleneck appears in the assignment operator `=`:
![EXRXBE 7IO{$YNPKD%R)}HM](https://user-images.githubusercontent.com/43924785/176748207-d80e54fb-642e-417f-a610-9c73de4c9083.png)

https://github.com/microsoft/vscode/blob/f24d09f05a9759facb8d3dcd2ebe004d39edfeaf/src/vs/workbench/api/common/extHostTypes.ts#L127-L136

After remove:
![_V$VOOY4UQZKTTTAF2$10}T](https://user-images.githubusercontent.com/43924785/176749288-8847139b-97a4-42da-ad2d-9f9b5a5ab935.png)

On Windows 10 19043.1766, AMD Ryzen 5 3600, open [file](https://github.com/qingpeng9802/demo/blob/master/asdf.lisp) in demo extension, then, we measure the time to generate all `DocumentSymbol` (got 20x faster):
||Open file first time (Cold)|Add newline to file (Hot)|
|-|-|-|
|removed|20ms|40ms|
|es5|400ms|800ms|

### Proposed Reason
Then, we found [The_performance_hazards_of_prototype_mutation](https://github.com/mdn/content/blob/41595b3aea787e9c04dfb7eb96fd586befbf9318/files/en-us/web/javascript/the_performance_hazards_of_prototype_mutation/index.md) may explain the performance difference.  
TD;DR: JavaScript engines optimize property accesses by assuming there is no `[[Prototype]]` mutation, so `[[Prototype]]` mutation will destroy the optimization. We believe that this should be the correct explanation.

### Alternatives
We haven't come up with any other mitigation plan. To maintain ES5 compatibility, we still need to consider modifying the prototype anyway. While removing compatibility is a hard decision, the performance benefits shown here are worth making it an option.

**Comment by jrieken** [comment]
@qingpeng9802 Thanks for the investigation. I like this. That compat-util has shown up as impacting perf before. I'll discuss in the team as removing it, can technically break extension that don't transpile to ES6 - you cannot extend from the API types (`class Foo extends vscode.Position`) and transpile that to a function-statement. This was an issue 3 years ago but is likely something we can now ignore. One strategy would be use try this in insiders and see how it goes

**Comment by qingpeng9802** [comment]
@jrieken We have come up a solution that keeps ES5 compatibility but resolves the performance issue on it. See https://github.com/microsoft/vscode/pull/155390. (Per my test, [codemetrics](https://github.com/kisstkondoros/codemetrics) you mentioned should work, but please double check it.)

This solution is inspired by
```js
function es5ClassCompat(target: Function): any {
	const interceptFunctions = {
		apply: function (targetClass: Function, thisArg: Object, argumentsList: any) {
			return Reflect.construct(targetClass, argumentsList, thisArg.constructor);
		}
	}
	return new Proxy(target, interceptFunctions);
}
```
We can just intercept the calls and use our customized function for the calls. This `Proxy` solution can avoid prototypical inheritance. However, the performance loss caused by the `Proxy` is almost the same as the original solution (even by a empty `Proxy`).

Thus, we have to turn to a more *hacky* way,
```js
function es5ClassCompat(target: Function): any {
	const interceptFunctions = {
		apply: function () {
			const args = arguments.length === 1 ? [] : arguments[1];
			return Reflect.construct(target, args, arguments[0].constructor);
		},
		call: function () {
			if (arguments.length === 0) {
				return Reflect.construct(target, []);
			} else {
				const [thisArg, ...restArgs] = arguments;
				return Reflect.construct(target, restArgs, thisArg.constructor);
			}
		}
	};
	return Object.assign(target, interceptFunctions);
}
```
We intercept the calls at the `property`-level of the API and use our customized function for the calls. Note that only `APIClass.call()/apply()` is affected and other usage like `new APIClass()` is not affected at all.  

*hacky*, but acceptable:
VSCode side: The API Class cannot expect to define `call` and `apply` properties.
Client side: Client who is using ES5-style cannot modify `call` and `apply` properties on the APIs.

By the way, after further investigation, it seems that the performance issue is not only caused by the prototype mutation. The performance issue seems to be due to a secret combination of `Reflect.construct()` and prototype mutation, which means that `Reflect.construct()` might also contribute to performance loss. By ECMAScript, `Reflect.construct()` should not have performance issue so the issue might be caused by some optimization failure.
