### ISSUE TITLE
Localized commands with configured display language don't show up when searched in English

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#153865]
1. Configure a display language e.g. pseudolang
2. Search for the edit sessions commands or the settings sync: turn on command in English (fyi @sandy081)
3. :bug: commands don't show up

This is because all actions which are registered via `registerAction2` and which use a pre-localized string for the title instead of `ILocalizedString` only get the localized string displayed in the command palette

We probably shouldn't allow the use of `string` here for actions which are contributed to the command palette

https://github.com/microsoft/vscode/blob/b286094d6ceaf8e4e2a8dc635425bbdf2296c215/src/vs/platform/action/common/action.ts#L36

| Errors | Files                                                                                     | Owner           |
| ------ | ----------------------------------------------------------------------------------------- | --------------- |
| 1      | vs/workbench/api/browser/mainThreadFileSystemEventService.ts:186                          | @jrieken        |
| ~1~      | ~vs/workbench/browser/actions/layoutActions.ts:1183~                                        | ~@sbatten~        |
| ~1~      | ~vs/workbench/contrib/extensions/browser/extensionsViewlet.ts:159~                          | ~@sandy081~       |
| 2      | vs/workbench/contrib/inlayHints/browser/inlayHintsAccessibilty.ts:175                     | @jrieken        |
| ~1~      | ~vs/workbench/contrib/languageDetection/browser/languageDetection.contribution.ts:124~      | ~@TylerLeonhardt~ |
| 1      | vs/workbench/contrib/languageStatus/browser/languageStatus.contribution.ts:399            | @jrieken        |
| 6      | vs/workbench/contrib/mergeEditor/browser/commands/commands.ts:160                         | ~@hediet~         |
| 2      | vs/workbench/contrib/mergeEditor/browser/commands/devCommands.ts:34                       | ~@hediet~         |
| ~4~      | vs/workbench/contrib/notebook/browser/contrib/cellCommands/cellCommands.ts:458            | ~@roblourens~     |
| 1      | vs/workbench/contrib/notebook/browser/contrib/gettingStarted/notebookGettingStarted.ts:82 | @rebornix       |
| 3      | vs/workbench/contrib/notebook/browser/contrib/troubleshoot/layout.ts:122                  | @rebornix       |
| ~1~      | ~vs/workbench/contrib/notebook/browser/controller/editActions.ts:470~                       | ~@TylerLeonhardt~ |
| 3      | vs/workbench/contrib/notebook/browser/controller/layoutActions.ts:22                      | @rebornix       |
| ~5~      | vs/workbench/contrib/search/browser/search.contribution.ts:366                            | ~@roblourens~     |
| ~1~      | ~vs/workbench/contrib/sessionSync/browser/sessionSync.contribution.ts:148~                  | ~@joyceerhl~      |
| ~1~      | vs/workbench/contrib/testing/browser/testExplorerActions.ts:250                           | @connor4312     |
| ~3~      | vs/workbench/contrib/testing/browser/testingOutputPeek.ts:1666                            | @connor4312     |
| ~3~      | ~vs/workbench/contrib/update/browser/update.contribution.ts:35~                             | ~@joaomoreno~     |
| ~1~      | ~vs/workbench/contrib/welcomeGettingStarted/browser/gettingStartedService.ts:692~           | ~@lramos15~       |

### Recommendation

* The `title` property AND the `category` property should not be set to a `string` and should be set to an `ILocalizedString`:
https://github.com/microsoft/vscode/blob/f24d09f05a9759facb8d3dcd2ebe004d39edfeaf/src/vs/platform/action/common/action.ts#L11-L22

**Comment by TylerLeonhardt** [comment]
Here's why..

The edit session ones don't use ILocalizedString so they appear as just pseudolang.
The other two _do_ use ILocalizedString so the English string shows up underneath.
<img width="499" alt="image" src="https://user-images.githubusercontent.com/2644648/176804360-357d54bc-4ed7-4188-b03c-ffc19aa46952.png">

We do this so users can still use the English command if they find it on StackOverflow or other places.

**Comment by hediet** [comment]
This is very subtle. I suggest to change
```ts
title: string | ICommandActionTitle;
```
to 
```ts
title: ICommandActionTitle;
```

**Comment by TylerLeonhardt** [comment]
@hediet I am planning on doing that once we get through some of these.

It's a little more complicated because only the ones that use `f1: true` need to be an `ICommandAction`. If you are targeting something else with this action, like the file/edit/view menu, then the `ICommandAction` doesn't really do much... so I'll have to do some fun stuff with types (which I did in order to generate this list in the first place).

**Comment by connor4312** [comment]
These changes could probable be done with a clever regex. Though I also kind of want a "code transformation notebook" that would let me write a function that operates on the TS AST and is easily applied throughout the codebase.

**Comment by TylerLeonhardt** [comment]
@connor4312 maybe even a tree-sitter notebook?

**Comment by connor4312** [comment]
Maybe a project for the long weekend if I finally finish building my dining table...

**Comment by TylerLeonhardt** [comment]
Feel free to cross yourself off and unassign when done.

**Comment by TylerLeonhardt** [comment]
verification:

I've already checked all of the commands except for the one I just fixed... so all you have to do is:

* wait for tomorrow's insiders
* change to any language pack
* seach for `Configure Test Profiles` in the command palette

ensure that it has the translated string _and_ the English string
