### ISSUE TITLE
Difficult to reach the top on OS X fullscreen

### ISSUE THREAD

**Issue by Trebor-Huang** [microsoft/vscode#153896]
Issue Type: <b>Bug</b>

- Go to fullscreen.
- Take any layout with, e.g. the terminal on the bottom half, and an text editor tab on the top half.
- Drag the separator to the top so that the terminal becomes fullscreen within the VSCode window. Let go.
- Try to drag back, OS X will automatically reveal the system menu bar at the top when the mouse goes near, covering the top of the window.

When it is not fullscreen, it works fine and the original text editor tab comes back.

VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id 51bac6f0-a15a-4951-95ba-8e047d430bb5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by TylerLeonhardt** [comment]
Simple workaround would be to use the `^` to maximize the panel instead of dragging it.

![Screen Shot 2022-07-01 at 2 43 27 PM](https://user-images.githubusercontent.com/2644648/176971160-674b6fa6-0dd8-4ca7-ac6b-0af3df77dd70.png)

**Comment by sbatten** [comment]
@deepak1556 I don't think there is anything we can do about this, right? certainly not outside of electron

**Comment by deepak1556** [comment]
Not actionable, since runtime doesn't control the native menu.
