### ISSUE TITLE
File Search - Improve performance of file search 

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15384]
Part of #55.

We will focus on simple text search. Regex text searches might be more difficult to optimize and are used less often than simple text searches. We will initially explore our options (e.g., refining our own implementation, command line tools, text search libraries/engines).

We will include full-text search libraries/engines in our investigation and see if any of these can do simple text searches while at the same time open the door for also supporting a more natural 'fuzzy' text search at a later time.

The goal is raw search performance with library size (if any) and disk usage of an index (if any) being potential trade-offs.

**Comment by roblourens** [comment]
Investigate alternative indexed filesystem search tools
	- Access to macos spotlight or windows equivalent?
	- Google Desktop is discontinued

Investigate Postgres fuzzy text search
	- Any blocking issues… solution for packing and shipping with a client app?
	- If feasible, prototype

Try CLucene
	- It's not consistently maintained anymore but are people using it in production?

Stress test lunr.js and Norch
	- Norch is built on LevelDB
	- What happens when they are fed a very large workspace?

**Comment by roblourens** [comment]
These results come from running the `TextSearch.performance` test a couple times and averaging (where each run averages 3 runs of the same search). It tests doing the search and returning results to the frontend process, but not doing UI things with them.

| |MacOS|Win|
|---|---|---|
|With Buffer.slice (original code)|100s|125.5s|
|Replacing Buffer.slice with buffer.toString(null, start, end)|71.1s|97.05s|
|With 4 worker processes (for a total of  5 (very very rough))|26.4|19.0
