### ISSUE TITLE
Weird autocomplete behavior when `"editor.autoClosingQuotes": "never"`

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#153875]
Version: 1.69.0-insider (Universal)
Commit: f1abeeab7e51df997bbb0f1ff900321ad2f21ac0
Date: 2022-06-30T05:17:23.222Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

Testing https://github.com/microsoft/vscode/issues/147006

I noticed that I ended up a weird state that looks like this:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/12758612/176792755-f85268aa-24d1-4617-9900-e9e5f24d6d79.png">

![Recording 2022-06-30 at 16 04 22](https://user-images.githubusercontent.com/12758612/176792771-a243feb3-3309-41b7-a886-44190942dc6e.gif)

**Comment by aeschli** [comment]
In this step
![image](https://user-images.githubusercontent.com/6461412/176851519-04fec08e-296f-4332-9f2e-0fd6e31ee031.png)

`},` are part of the string literal, which then is replaced by the value from the completion.

You would have to press `Shift` when selecting the completion, to insert the completion instead.

Not sure how we can improve this. Any reason why to turn off autoClosingQuotes ?

**Comment by tanhakabir** [comment]
Ah I see. Oh no I only tried that setting for the issue I was verifying but I was confused why my closing brace disappeared

**Comment by aeschli** [comment]
I'm closing the issue then.
