### ISSUE TITLE
Built-in renders should use vscode scoped id

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#153873]
Issue Type: <b>Bug</b>

Currently we our built-in markdown renderer is called `markdownItRenderer`

This was fine for internal use, but now that renderers are being exposed publically, this becomes api. I propose we change it to:

```
vscode.markdown-it-renderer
```

VS Code version: Code - Insiders 1.69.0-insider (Universal) (f1abeeab7e51df997bbb0f1ff900321ad2f21ac0, 2022-06-30T05:17:23.222Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sandy081** [comment]
verified by code review
