### ISSUE TITLE
Quick Open - Invesigate the costs of persisting our file cache

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15382]

**Comment by eddy-geek** [comment]
I am currently using vscode on an sshfs fuse filesystem, and I think this feature would help a lot for navigation in such cases (currently quick open is too slow so I have to navigate in the project explorer tree). Is the cost analysis still ongoing?

**Comment by 1st** [comment]
Please look into Sublime Text to see how it works. I also use sshfs and with Sublime it works perfectly. Inside the VS Code it's very slow to go to file or go to definition inside the workspace.

Any estimates about when will it be done?

P.S. And please, save all cache and settings fole in one place - ~/.vscode folder, to avoid spreading configs and cace files on differen locations.
