### ISSUE TITLE
"Execute the restore command to continue" messages in large projects cycle continuously 

### ISSUE THREAD

**Issue by ryanbrandenburg** [Microsoft/vscode#15387]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Clone an AspNet Core repo with lots of projects (like aspnet/Mvc).
2. Open that folder in VS Code and wait for all the messages reading `There are unresolved dependencies from 'project'. Please execute the restore command to continue.` to appear.
3. From the command line run `dotnet restore`.
4. Observe the rapid scroll of the restore messages.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#928
