### ISSUE TITLE
JCL1 member does not exist

### ISSUE THREAD

**Issue by JHLLOR** [microsoft/vscode#153845]
Issue Type: <b>Bug</b>

Hello,
I am trying to run challenge 3, but I have the problem that member JCL1 does not exist in my file list: Z14245,ZXP.PUBLIC.
My name is Juan Hernandez, I am from Mexico City and my assigned user is: Z14245.
Thank you in advance for your support.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by jrieken** [comment]
This seems unrelated to VS Code
