### ISSUE TITLE
Font issues with problem hover

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#15381]
Problem hover's font usage is inconsistent: uses both fixedwidth and variable font:

![](https://cloud.githubusercontent.com/assets/1898161/20221909/91a6ade2-a833-11e6-924b-269f84a4525a.png)

I don't see a need to use a fixedwidth font at all.

(see https://github.com/Microsoft/vscode/issues/14260 for additional informational)

**Comment by joaomoreno** [comment]
Unfortunately, as designed.

The first block comes from an error provider, many of which provide ASCII decorations like the one below, which we must preserve monospace for. @jrieken 

```
this is a error
        ^ should be `an`
```
