### ISSUE TITLE
can not find `source control repositories` when move scm view to right side bar

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#153928]
1. side bar 
![image](https://user-images.githubusercontent.com/1876302/176933866-30174c1e-eba9-45c4-90d4-999b234ed074.png)
2. right side bar
![image](https://user-images.githubusercontent.com/1876302/176933896-d7f9b250-0dd0-480f-8943-e56703bbfc4b.png)

how can we see `source control repositories`?

**Comment by lszomoru** [comment]
If you have both the "Source Control" and "Source Control Repositories" views visible in the view container, you can drag the view container into the secondary sidebar and both of the views will be visible in the secondary sidebar (see the screenshot below). I will go ahead and close this issue but please feel free to reopen it in case you still have any questions or concerns. Thanks! 

![Image](https://user-images.githubusercontent.com/3372902/206707743-0dc3ebc5-d5fe-499d-9b8a-739fed1feb2e.png)

**Comment by heartacker** [comment]
I know this, but I still believe this is a bug.

otherwise, I have to show them in the side bar and then drag to second bar
