### ISSUE TITLE
Error loading webview

### ISSUE THREAD

**Issue by CraftyMiner1971** [microsoft/vscode#153955]
Issue Type: <b>Bug</b>

Every time I try to open an extension, I get the above error, with the following text included:

Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..

I am not able to view any details page for any extension.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700U with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.95GB (4.25GB free)|
|Process Argv|--crash-reporter-id 2b51a314-a531-4030-b7f9-7f14e884c01b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
Bookmarks|ale|13.3.0
tailwindcss-extension-pack|and|1.1.4
clock|ang|1.0.1
spellright|ban|3.0.64
color-info|bie|0.7.0
docs-view|bie|0.0.11
converttoasciiart|Bit|1.0.3
npm-intellisense|chr|1.4.2
vscode-eslint|dba|2.2.2
amstradbasic|dfr|0.0.1
vscode-html-css|ecm|1.13.0
prettier-vscode|esb|9.5.0
pip-packages|etm|0.4.3
vsc-figlet|fer|0.0.9
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
html-preview-vscode|geo|0.2.5
vscode-pull-request-github|Git|0.44.0
live-sass|gle|5.4.0
headwind|hey|1.7.0
rest-client|hum|0.25.0
RelativePath|jak|1.5.0
vscode-gutter-preview|kis|0.30.0
comment-styler|kre|1.0.2
vscode-language-babel|mgm|0.0.36
HTMLHint|mka|0.10.0
vscode-autoprefixer|mrm|3.0.1
python|ms-|2022.8.1
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
debugger-for-edge|msj|1.0.15
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
colorful-comments|Par|0.7.0
mit-license-adder|pet|0.3.0
material-icon-theme|PKi|4.18.1
vscode-css-navigation|puc|1.13.3
java|red|1.8.0
r|REd|2.5.0
LiveServer|rit|5.7.5
color-manager|roy|0.7.5
fpack|Sey|0.2.0
vscode-scss-formatter|sib|2.4.3
html5-boilerplate|sid|1.1.1
pip-manager|sli|1.1.1
sourcegraph|sou|2.2.7
code-spell-checker|str|2.2.5
lua|sum|3.4.0
w3css|Suv|0.0.3
vscodeintellicode|Vis|1.2.22
JavaScriptSnippets|xab|1.8.0
five-server|yan|0.1.5
file-size|zh9|1.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30519255
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by CraftyMiner1971** [comment]
This was the first thing I tried, and it still did the same thing, even turning all the extensions off didn't make any difference. Any further advice on what I can try next, please let me know

**Comment by gjsjohnmurray** [comment]
Maybe #122951

**Comment by CraftyMiner1971** [comment]
It's fixed! I appreciate your responding to my complaint. Thanks

**Comment by hrboyceiii** [comment]
I don't know if this was truly the problem, however, I'm sharing so that others may find this helpful.  The markdown preview tool suddenly stopped working for me when I modified my settings such that the terminal used `CaskaydiaCove Nerd Font Mono` so that my prompt displayed correctly.  When I reverted this setting back to the default, the preview tool began working again...

YMMV
