### ISSUE TITLE
Should tasks "Building" status bar entry be using spin codicon instead of sync?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153935]
Currently the icon doesn't match the terminal tab:

<img width="242" alt="Screen Shot 2022-07-01 at 10 40 29 am" src="https://user-images.githubusercontent.com/2193314/176944458-32907182-38d0-443e-8b31-95f4fbe5e03d.png">

![Recording 2022-07-01 at 10 39 44](https://user-images.githubusercontent.com/2193314/176944436-6bfc4424-e26e-436b-bee1-3bd94aaceaf5.gif)

**Comment by meganrogge** [comment]
Yes I think so. Only downside is it seems louder

**Comment by Tyriar** [comment]
Let's bring to the UX sync, should be a quick one

**Comment by Tyriar** [comment]
The sync icon is used for a few things in the status bar:

![image](https://user-images.githubusercontent.com/2193314/177611850-5624b8f8-8520-4144-bc2a-e5768d1444f4.png)
