### ISSUE TITLE
Multiple searchs in search sidebar

### ISSUE THREAD

**Issue by pa0694** [microsoft/vscode#153908]
In the sidebar, we can only sarch for one field.
For starting a new search without removing the previous search, the button ""Open New Search Editor" opens an editor. It would be great if the new search could dock also in the search sidebar, and not in a editor, edited pic for example:
![multiple_search](https://user-images.githubusercontent.com/70905569/176892461-72c540ef-0d13-476f-8129-bb767bea320f.png)

**Comment by roblourens** [comment]
You can use the Search Editor for this - you can keep multiple tabs open to manage multiple searches.

**Comment by pa0694** [comment]
> You can use the Search Editor for this - you can keep multiple tabs open to manage multiple searches.

hi and thanks for this response. 
I know it can be done like this, but I think it could be great to have this multiple search feature in the sidebar, to avoid switching tabs for each research, because the sidebar is always on screen!
