### ISSUE TITLE
Got an untitled dirty file on startup

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15397]
Not sure how to reproduce: I was on master before accepting your changes, then did a pull to fetch latest and then I started out of sources. Right on startup I noticed a dirty untitled file showing up even though hot exit was not enabled.

Maybe this happens when you have no hot exit data whatsoever and its the first time you launch with those changes?

**Comment by Tyriar** [comment]
This is expected if you had a left over Untitled file to restore when you were testing (hot exit enabled), and then switched back to master and disabled hot exit. Do you think that could have happened?

**Comment by bpasero** [comment]
Yes, Sir 👍
