### ISSUE TITLE
large ghost emmets/snippets haunting my code

### ISSUE THREAD

**Issue by wookiehangover** [microsoft/vscode#153931]
Issue Type: <b>Bug</b>

Howdy 🤠

@digitarald saw me [tweeting](https://twitter.com/sambreed/status/1542574021304123392) about this yesterday and suggested I opened an issue.

I recently noticed that emmet suggestions are being inlined as ghost text. The issue is that a lot of times those suggestions are very distracting in their new format compared to the old. For example, typing a single exclamation point at certain places in a JSX file inline suggests to insert and entire HTML5 doctype + document, which is a multi-line insert, and very, very distracting (not to mention, completely unhelpful in that context.

Note, there is a settting to disable this "Emmet: Use Inline Completions" but I reckon that anything this aggressive should likely be switched "off" by default.

Also noteworthy, I had originally thought these were co-pilot suggestions, which have similar UI. It was only when I disabled all plugins that I determined it was emmet giving the unhelpful distraction.

Here's a video of the behavior:

https://user-images.githubusercontent.com/84644/176937551-af85e8b8-17e2-4122-a049-013d53bdf251.mp4

Thanks for your time!

VS Code version: Code - Insiders 1.69.0-insider (0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce, 2022-07-01T05:20:30.328Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 4, 11|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--disable-extensions --crash-reporter-id e88297f9-534c-423d-88f3-2fe32f0f3b78|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30519255
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30496796
vsclangdf:30492506

```

</details>

**Comment by rzhao271** [comment]
Hi, I saw the tweet this morning.
I have already merged in a fix to switch off the setting by default here https://github.com/microsoft/vscode/pull/153926.
Thanks for using Insiders!

\closedWith 623cde6

**Comment by rzhao271** [comment]
\closedWith https://github.com/microsoft/vscode/commit/623cde6b38b8238dbe33a7e4536f5917a69df1b3

**Comment by rzhao271** [comment]
Verification steps for the next Insiders release:
1. Navigate to the Settings editor.
2. `emmet.useInlineCompletions` should be unchecked by default.
