### ISSUE TITLE
Configurable titles for menu extension points

### ISSUE THREAD

**Issue by gar1t** [microsoft/vscode#153915]
This is related to #147746, which is closed for comment.

It appears that menu items (contribution points) now support a `title` attribute. But those title values do not appear to be used by the menus - the command titles are used.

As #147746 points out, commands run in different contexts can have different meanings. E.g. when a 'Delete' command is applied to a tree node via a context menu, the context is a single item and the command is usually spelled 'Delete' or 'Delete {singular form}'. When that same command is run from the command palette, it might provide a pick list and support multiple items and so the command is spelled 'Delete {plural form}'.

Example:

``` json
{
  "contributes": {
    "commands": [
      {
        "command": "sample.delete",
        "title": "Delete Samples"
      }
    ],
    "views": {
      "explorer": [
        {
          "id": "samples"
        }
      ]
    },
    "menus": {
      "view/item/context": [
        {
          "command": "sample.delete",
          "when": "view == samples",
          "title": "Delete"
        }
      ]
    }
  }
}
```

In this example, a right-click on a node in the `samples` view shows 'Delete Samples' rather than 'Delete'.

It's possible to create multiple commands as a work-around, but this is quite a bit more complexity as the additional commands must be removed from the command palette, in addition to the additional configuration. And this just to modify the title shown in a particular context.

I'm not sure if the current behavior is intentional or not so I'm opening this as a feature request.

**Comment by jrieken** [comment]
> It appears that menu items (contribution points) now support a title attribute

That is not correct. All UI related properties must be defined for the command, not for a possible rendering location. However, when defining a `command` you specify a `shortTitle`. Menus (as consumer of these UI properties) will then decide to use the long or short title
