### ISSUE TITLE
Git stash behavior varies depending on staged changes

### ISSUE THREAD

**Issue by jessdwitch** [microsoft/vscode#153920]
Issue Type: <b>Bug</b>

1. Have multiple uncommitted changes. Stage none of them.
1. From the Source Control panel, highlight some, but not all of the files.
1. Right-click and click "Stash Changes"

The highlighted files are stashed, leaving behind the unhighlighted files. "Untracked" status is irrelevant. This is behaving as expected.

Now do it again, but this time with a few files staged. Instead, _all_ tracked files are stashed, ignoring highlighting. These should behave the same regardless of whether there are staged changes.

VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 3b1eb426-a969-4b8c-aa6e-148bc1354bd8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.9.5
atlascode|atl|2.10.12
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
solargraph|cas|0.23.0
doxdocgen|csc|1.4.0
gitlens|eam|12.1.1
vscode-pull-request-github|Git|0.44.0
go|gol|0.34.1
cloudcode|goo|1.18.3
vscode-graphql|Gra|0.4.13
terraform|has|2.23.0
vscode-drawio|hed|1.6.4
better-cpp-syntax|jef|1.15.18
cmake-language-support-vscode|jos|0.0.4
endwise|kai|1.5.1
rainbow-csv|mec|2.4.0
dotenv|mik|1.0.1
file-downloader|min|1.0.12
mindaro|min|1.0.120220125
prettify-json|moh|0.0.3
vscode-docker|ms-|1.22.0
vscode-dotnet-runtime|ms-|1.5.0
vscode-kubernetes-tools|ms-|1.3.10
python|ms-|2022.8.1
vscode-pylance|ms-|2022.6.30
jupyter|ms-|2022.5.1001601848
remote-containers|ms-|0.238.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.10.7
cpptools-extension-pack|ms-|1.2.0
makefile-tools|ms-|0.5.0
sqltools|mtx|0.23.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.36.0
material-icon-theme|PKi|4.18.1
ruby|reb|0.28.1
java|red|1.8.0
vscode-yaml|red|1.8.0
r|REd|2.5.0
openapi-vs-code|Red|0.2.10
slim|sia|0.1.2
sonarlint-vscode|Son|3.5.4
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.21
vscode-java-debug|vsc|0.42.0
vscode-java-dependency|vsc|0.20.0
vscode-java-pack|vsc|0.24.0
vscode-java-test|vsc|0.35.1
vscode-maven|vsc|0.36.0
vscode-spring-boot-dashboard|vsc|0.5.0
vscode-spring-initializr|vsc|0.10.0
vscode-ruby|win|0.28.0
clang-format|xav|1.9.0
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550

```

</details>

**Comment by lszomoru** [comment]
@jessdwitch, the "Stash Changes" command is being contributed by [the GitLens extension](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens).
Could you please file this issue in [the extension's repository](https://github.com/gitkraken/vscode-gitlens/issues)? Thank you!
