### ISSUE TITLE
Git initialize repository view links improperly localized

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#153934]
Testing https://github.com/microsoft/vscode/issues/150990

With the pseudolanguage pack, on an open folder with no initialized repository, the links in the SCM viewlet do not render properly:

![A screenshot demonstrating the issue above](https://user-images.githubusercontent.com/7199958/176940098-346a7077-ab58-4ccd-9980-7ec5a52183a5.PNG)

**Comment by lszomoru** [comment]
@rzhao271, this is what I see in today's Insiders release (2022-07-06):

<img width="411" alt="image" src="https://user-images.githubusercontent.com/3372902/177543904-ba8369b1-0e62-4038-a2f1-721fbcce9cab.png">
 
Looks like the buttons appear correctly, though it looks like the icon in the "Publish to GitHub" button has been translated.

**Comment by lszomoru** [comment]
@TylerLeonhardt, what would be the best way to indicate in a `.nls.json` file that the icon should not be translated. I see that there is already a pattern to indicate that the `command:*'` should not be translated. Can we establish something similar for icons as well? 

https://vscode.dev/github/microsoft/vscode/blob/0432931581cd27a5ee61dc454099253727a0726d/extensions/github/package.nls.json#L6

**Comment by TylerLeonhardt** [comment]
@lszomoru you can add more comments that lock the icons as well:

```
"{Locked='$(github)'}",
"$(...) will be rendered as an icon and should not be translated"
```
