### ISSUE TITLE
Search with fields separated by spaces as keywords without using regex search mode.

### ISSUE THREAD

**Issue by hongyi-zhao** [microsoft/vscode#153997]
I want vscode to search with fields separated by spaces as keywords  without using regex search mode. For example, when I type `foo bar baz` in the search box, any lines that include all of these keywords will be matched.

Regards,
Zhao

**Comment by ArturoDent** [comment]
How would the editor know that you don't want to search for `foo bar baz` literally then?

**Comment by hongyi-zhao** [comment]
To restate or clarify my intentions, I mean, match the lines that include `foo.*bar.*baz` by just typing `foo bar baz`.

**Comment by ArturoDent** [comment]
Yes, but some people are going to want to search for a sentence like `asdasdad foo bar baz 23424234` and find that only with that strict sequence with nothing between the words.  Which is the current result.  So how to know which type of search is desired?

**Comment by hongyi-zhao** [comment]
You can add fuzzy/unordered matching options to what is discussed here.

**Comment by roblourens** [comment]
This is basically a concept for a "fuzzy text search" which has come up before, but I don't think it fits into vscode at the moment
