### ISSUE TITLE
Merge Editor: Double `Accept Merge` button in settings sync conflict resolution

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#153986]
1. Hit a conflict in Settings Sync and choose to resolve conflicts withe the merge editor

🐛 There are two buttons and one is very weirdly laid out

![Recording 2022-07-02 at 20 46 06 (1)](https://user-images.githubusercontent.com/22350/177012871-e1f06959-71e5-45e3-b9ed-e0e1892c0b28.gif)

**Comment by gjsjohnmurray** [comment]
Looks like #153627 but that one is supposed to have been fixed a few days ago.

**Comment by joaomoreno** [comment]
Oh, I did have a pending update. Thanks @gjsjohnmurray!
