### ISSUE TITLE
Blank Screen on iOS Safari 14.3

### ISSUE THREAD

**Issue by Idefix2020** [microsoft/vscode#153906]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: >=1.66.0
- OS Version: iOS 14.3

Steps to Reproduce:

1. Open Safari on iOS 14.3
2. Navigate to any vscode server (e.g. [github.dev](https://github.dev/), [vscode.dev](https://vscode.dev/) or [code-server](https://github.com/coder/code-server))

The Safari developer tools console shows the following error:

```
Unhandled Promise Rejection: ReferenceError: Can't find variable: BigInt64Array
```

**Comment by joaomoreno** [comment]
[The user is right](https://caniuse.com/?search=BigInt64Array).

I see references to `BigInt64Array` in the following commits:

- https://github.com/microsoft/vscode/commit/4ac1fc2d8e9cbe9c09ec1410557d1969d442f6dd @rchiodo 
- https://github.com/microsoft/vscode/commit/3499f63dc1cf094b53c48552589cb06d7fa8d472 @mjbvz 
- https://github.com/microsoft/vscode/commit/32d40cf44e893e87ac33ac4f08de1e5f7fe077fc @deepak1556  (soft reference)

@jrieken Thoughts?

**Comment by connor4312** [comment]
Fyi this has been supported since iOS 15 (June 2021). https://caniuse.com/mdn-javascript_builtins_bigint64array_bigint64array

**Comment by connor4312** [comment]
As this has been supported since iOS 15, do we want to change this?

**Comment by Idefix2020** [comment]
The changes introduced in https://github.com/microsoft/vscode/commit/4ac1fc2d8e9cbe9c09ec1410557d1969d442f6dd completely break vs code for all devices below iOS/iPadOS 15, the other occurrences of `BigInt64Array` don't seem to have any negative impact according to my testing (anything below 1.66.0 works). The fix I proposed in #153929 is a more elegant solution that supports all browsers and does not break anything.

**Comment by jrieken** [comment]
> @jrieken Thoughts?

We are generally only aiming for latest and greatest browser version. The use of `BigInt64Array` seems small enough to justify a special case but we shouldn't target a lower version nor is there any guarantee that other things won't break, e.g "fixing" this might just reveal another bunch of blocker etc pp.

**Comment by joaomoreno** [comment]
Sounds good, forwarding to @rchiodo to evaluate the PR.
