### ISSUE TITLE
Arrow keys navigate through cells not suggestions

### ISSUE THREAD

**Issue by antonavy** [microsoft/vscode#153923]
Issue Type: Bug
Steps:
1. Type an unfinished command in a line (e.g. pandas.read)
2. Get suggestions and try to navigate through them using arrows (e.g. to scroll down)

Expected: 
And it always worked this way until recently.
You can scroll up and down using arrow up and arrow down, respectively. Then press enter to select a suggestion.

Actual:
If there is a next cell below (arrow down), then it switches to the next cell.
If there is no cell below or above, then nothing happens.

Version: 1.69.0-insider
Commit: e7751367f79f327b8103bee33a07c16817a2c7cd
Date: 2022-06-28T05:17:52.688Z (3 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by roblourens** [comment]
This was just fixed: https://github.com/microsoft/vscode/issues/152770
