### ISSUE TITLE
Go (golang) Auto Complete (Half) Works

### ISSUE THREAD

**Issue by dc0d** [Microsoft/vscode#15399]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 14.04

Steps to Reproduce:

Can't provide steps to reproduce. It happens spontaneously. Others had this issue too (on gitter).

The default gocode auto built option is not changed: `"go.gocodeAutoBuild": true`.
And I have these personal settings (just FYI; and I do not know if they matter in this matter):
```
// Place your settings in this file to overwrite the default settings
{
    // Is git enabled
    "git.enabled": false

    , // Migrated from previous "File | Auto Save" setting:
    "files.autoSave": "afterDelay",

    // Controls the delay in ms after which a dirty file is saved automatically. Only applies when "files.autoSave" is set to "afterDelay"
    "files.autoSaveDelay": 2000
}
```

And I have this script `rs-gocode`:
```
#!/bin/bash

gocode close
gocode
```
But it does not help (Should I run it inside current directory?).

Sometimes after login/logout or restart, the problem goes away and the problem is mostly with code that is currently being written (it compiles & passes the tests - not broken).

**Comment by gertcuykens** [comment]
https://github.com/Microsoft/vscode-go is the golang plugin repositorie

PS maybe some screenshots for when it happens? Anyway it works for me on osx but i do remember i had to do the gocode close and empty my golang path and reinstall the tools the go plugin is using

**Comment by aeschli** [comment]
Please file against https://github.com/Microsoft/vscode-go  (thanks @gertcuykens )
