### ISSUE TITLE
Merge editor and editor resolver

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#153963]
This is somewhat related to https://github.com/microsoft/vscode/issues/153110 and also https://github.com/microsoft/vscode/issues/153340: today the new merge editor is not registering itself to the `IEditorResolverService`, except for that hack to enable opening the merge editor ad-hoc:

https://github.com/microsoft/vscode/blob/71b996eff4cef4405d1d1cc4fe308545dac0b255/src/vs/workbench/contrib/mergeEditor/browser/view/mergeEditor.ts#L412

This brings up a more general question: how would the merge editor register to the resolver, ideally I would like to do run this code to open a merge editor:

```ts
const mergeEditor = { input1: {resource: URI}, input2: {resource: URI}, base: { resource: URI}};
editorService.openEditor(mergeEditor);
```

This follows our pattern of untyped editor inputs for opening. 

We have similar support for opening diff editors via the untyped `IResourceDiffEditorInput`:

https://github.com/microsoft/vscode/blob/71b996eff4cef4405d1d1cc4fe308545dac0b255/src/vs/workbench/common/editor.ts#L474-L485

Following the factory method of the resolver, I think we almost need to introduce a new factory method `createMergeEditorInput`, specifically for merge editors, which would then also theoretically enable us to do a merge editor for notebooks:

https://github.com/microsoft/vscode/blob/71b996eff4cef4405d1d1cc4fe308545dac0b255/src/vs/workbench/services/editor/common/editorResolverService.ts#L142-L149

Btw: Untyped editor inputs enable a few nice features, such as dragging an editor and dropping it into a new window to "move" it there. Since we cannot serialize a typed editor input to the target window, we have to use the untyped variant. This works by calling the method `toUntyped` on a typed editor input (e.g. [here](https://github.com/microsoft/vscode/blob/71b996eff4cef4405d1d1cc4fe308545dac0b255/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L393) for file inputs):

![Recording 2022-07-02 at 07 18 25](https://user-images.githubusercontent.com/900690/176987614-542bfb4b-52b2-499f-a7f6-be2b47d8913f.gif)

**Comment by jrieken** [comment]
> how would the merge editor register to the resolver, ideally I would like to do run this code to open a merge editor:

IDK - that means we push the notion of merge editors into workbench as a built-in concept. I am fine with that but IMO we are already paying much for abstractions and registrations (`registerEditorPane`, `registerEditorSerializer`, input to editor mapping etc...) and I really wonder what they are for then?

> Since we cannot serialize a typed editor input to the target window, we have to use the untyped variant. This works by calling the method toUntyped on a typed editor input (e.g. [here](https://github.com/microsoft/vscode/blob/71b996eff4cef4405d1d1cc4fe308545dac0b255/src/vs/workbench/contrib/files/browser/editors/fileEditorInput.ts#L393) for file inputs):

@bpasero Why isn't this using the `IEditorSerializer`-concept?

**Comment by bpasero** [comment]
> and I really wonder what they are for then

They are for creating an editor out of a `{ resource: URI}` lightweight input. We do not have to introduce the notion of merge editors if we can encode a merge editor input as a single resource, which is doable, but is a bit inconsistent with how diff editors work. Maybe Logan has an idea here how to proceed.

> Why isn't this using the `IEditorSerializer`-concept

Will check and see what the reasons are.

**Comment by lramos15** [comment]
> We do not have to introduce the notion of merge editors if we can encode a merge editor input as a single resource, which is doable, but is a bit inconsistent with how diff editors work. Maybe Logan has an idea here how to proceed.

We thought about doing this for diff for the tabs API but it sounds messy. I think adding `createMergeEditorInput` factory is the best way to proceed, there wouldn't be a new registration in this case though as the text registration would just have its factory called when three inputs are passed in via the appropriate untyped editor. There are tons of benefits to untype editors that make this worthwhile especially as we deprecate typed editors more and more. This should also easily enable other three-way merge scenarios as @bpasero has pointed out

**Comment by jrieken** [comment]
> I think adding createMergeEditorInput factory is the best way to proceed, 

Where would that happen - in the `workbench` or `contrib`?

**Comment by lramos15** [comment]
> Where would that happen - in the `workbench` or `contrib`?
We would add it to the register editor type and I would integrate it in such that we choose to create that editor in the case of an untyped merge editor input. Here's we would add the factory function https://github.com/microsoft/vscode/blob/a72212f1f4950dac3bcb7dbfcf805d96adf3c564/src/vs/workbench/services/textfile/common/textEditorService.ts#L69-L81

**Comment by jrieken** [comment]
So, that would mean we cannot be a contribution anymore and move into the core, right? I not really sure I see the grand scheme of things and why we need to register an editor in the first place. I  know, I have done it for some very special in-merge-editor-code-navigation-logic (https://github.com/microsoft/vscode/issues/153110) but it is not that we want to open a merge editor from the explorer or so

**Comment by lramos15** [comment]
> So, that would mean we cannot be a contribution anymore and move into the core, right? I not really sure I see the grand scheme of things and why we need to register an editor in the first place. I know, I have done it for some very special in-merge-editor-code-navigation-logic (#153110) but it is not that we want to open a merge editor from the explorer or so

You could keep it as a contrib if merge editors have a special schema that you would register instead. The reason I suggested it here as that would allow any arbitrary three resources to be opened in a three way merge. Registration also would enable `vscode.open` and in the future the tabs API `open` calls to function properly since they resolve on taking a lightweight untyped input passing it through the resolver and getting a fully fledged `EditorInput` out in the end

**Comment by bpasero** [comment]
The only reason merge editor would move into core is because text editors are registered in core and the merge editor is a text editor. We always had text editors in workbench core and never in `contrib`. That does not mean that the editor resolver is not fullfilling its purpose, we could as well move all text editors out into `contrib` if we wanted to.

The editor resolver abstracts underlying implementation by introducing the notion of untyped inputs. It does so by exposing the intent of an editor, but not its implementation: normal editor, diff editor, merge editor, untitled editor. I think having a merge editor as another kind is good, because - as I had said before - once we have a merge editor for notebooks, we could allow resolving a merge conflict in a dedicated notebook merge editor if the file is a notebook.

When I look at the sources of the merge editor, I think the following structure could work:
* `vs/workbench/contrib/mergeEditor/common/mergeEditor.ts` moves into `vs/workbench/common/editor`
* `vs/workbench/contrib/mergeEditor/browser` renames to `vs/workbench/browser/parts/editor/mergeEditor`

**Comment by bpasero** [comment]
This somewhat blocks https://github.com/microsoft/vscode/issues/5770 because CLI support requires some generic untyped input to open on startup or into an existing window. If 👍 I can maybe work with Logan to get this in, but it would need the suggested move to `core` unless the editor resolver could provide a way to "enrich" an existing contribution with another capability (merge editors):

https://github.com/microsoft/vscode/blob/e69176aafd282090e18f558c2b2ac9b3d5b606f5/src/vs/workbench/services/textfile/common/textEditorService.ts#L68-L82

Not sure whether that would be possible Logan?

**Comment by jrieken** [comment]
Let's set up a sync to talk about this first. I am not really understanding the whole picture yet (e.g I wonder if notebooks, assuming they will have a merge editor, also move to core)

**Comment by bpasero** [comment]
**From our meeting:**
* introduce `IUntypedMergeEditorInput: { base: URI; remote: URI; local: URI; result: URI }`
* add new method on editor resolver registration: `createMergeEditor`
* allow multiple registrations on the same glob and pick the one that provides the right editor class (normal, diff, untitled, merge)
* change the editor registration to an object to avoid repeated `undefined`
* check if we then can remove the redundant `canHandleDiff` option

**Some follow up ideas:**
* rename untyped input to unresolved input

**Comment by bpasero** [comment]
This was reverted and will re-land in August, @lramos15 can you recreate the PR?

**Comment by lramos15** [comment]
Recreated https://github.com/microsoft/vscode/pull/156672 will keep as draft until I can ensure merge is working and the perf issues are ironed out
