### ISSUE TITLE
Menu contributions with alt command won't trigger

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#15395]
- VSCode Version: `Version 1.8.0-insider (1.8.0-insider)` fb8939b09460ff9fbd40d39056b54c88d5aad9c8
- OS Version: macOS Sierra `10.12.1 (16B2555)`

Steps to Reproduce:

1. Using an extension that provides an `alt` command to a menu, press `alt` while clicking the menu
2. The `alt` command never seems to trigger, just the main `command`

**Comment by jrieken** [comment]
This currently only works when menu item appear in the editor title, e.g when we render them. When showing them in the native context menu we cannot get the `alt`-behaviour to work because opening a menu stops the whole JS event loop

**Comment by eamodio** [comment]
Instead of providing `alt` on click of a menu item -- what if the support was holding `alt` when opening the menu and then the menu would actually show the alternative options?

**Comment by eamodio** [comment]
@jrieken I've finally gotten around to check this out -- and am loving the new behavior. Although I have noticed that intermittently the `alt` menu choices "stick" meaning, I open the context menu with `alt` pressed and the alternates show up correctly, and then I close the menu and without pressing `alt`, I open the menu again and sometimes the same menu with the alternates is shown.

Also, it would be really awesome if this new behavior was supported across all the context menus, not just the editor one.

**Comment by jrieken** [comment]
Yeah, thanks for getting back on this. I reverted my changes and reopened this issue. It isn't as easy as I thought... The challenge is that as soon as the context menu opens we are blind and deaf, in particular we miss when the `alt`-key is being released. Since there is no API as *is alt key pressed right now* and since we emulate that by listening to various events it's quite bad that we miss those events...

Unsure how to fix this without getting more support from electron.

**Comment by eamodio** [comment]
@jrieken Nooooo. ;) Damn, that sucks -- was really loving the behavior. This should still be opened though right?

**Comment by jrieken** [comment]
I know... the new year shouldn't start with such bad news ;-)

**Comment by jrieken** [comment]
Thanks to @isidorn this now works. We added a big global event that unsets the alt-state before a menu is showing. With that we can now populate any menu with alternative action when clicking alt before opening them.
