### ISSUE TITLE
Unlabeled controls in the issue reporter.

### ISSUE THREAD

**Issue by TheQuinbox** [microsoft/vscode#153998]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows 10 21H2 (x64) build 19044.1706

Steps to Reproduce:
1. Start a Windows screen reader.
2. Go to help -> Report Issue
3. Tab between the controls.

Certain ones are labeled, for example, issue title, but a lot of the combo boxes aren't, and none of the links are, they all just say show. I can generally gather what things do based on context, but not always.

**Comment by TheQuinbox** [comment]
Hi @TylerLeonhardt, was this fixed recently? I don't have a Windows machine to test from, which is where I initially reported the issue, at the moment, but at least on the Mac, everything seems to read now using the latest Insiders.

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/140222

Thanks @TheQuinbox :)
