### ISSUE TITLE
Show errors in pop-ups before docs

### ISSUE THREAD

**Issue by antoscha** [microsoft/vscode#153979]
Hello,

I'd like to suggest a feature showing errors on cursor point before documentation unlike here:
![Screenshot_20220702_170641](https://user-images.githubusercontent.com/29676285/177004251-3b898e95-b089-41f6-b172-bb3a984779e2.png)
Usually a user would like to look at errors rather than read docs. Currently he has to scroll down the whole pop-up to look what's going wrong. Unfortunately, I have failed to find a way to fix it by existing tools.

Anton K.

**Comment by dbaeumer** [comment]
@jrieken not sure if you are the right person here.

**Comment by aiday-mar** [comment]
Recently fixed.
