### ISSUE TITLE
Why are we not allowed to open giant .txt files?

### ISSUE THREAD

**Issue by rogersachan** [Microsoft/vscode#15393]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Home 14393.447

Steps to Reproduce:

1. Open large text file
2. Crash

Seriously, why is this not allowed? I can use the inferior Notepad or Notepad++ and not have any issues whatsoever.

**Comment by gertcuykens** [comment]
Because vscode has multiple plugins that do more then just display characters on screen. Imagine a plugin that is doing parsing, analyzing, syntax checking autocomplete etc, and then give it a 1gb file... not going to happen is it? unless you have 2000$ workstation or something. Consider it as a fail save for people who accidentally open a bin file or movie file. Happens allot more then you think :)

**Comment by rogersachan** [comment]
I meant .txt in general, which doesn't bog down the system even on a RPi3 with the text file open in Chrome.

**Comment by gertcuykens** [comment]
vscode nature is to always try to do deep analysing on it. Don't know if there is a option to go in notepad mode and disable all parsing even on a txt file for example spelling check plugins etcetera. If you really feel like some files need to be handled with vscode try to make a more specific use case for it. But keep in mind vscode is ment for app development, for example if you want to edit a huge csv file then excel is going to work better for you.

Last time I got into trouble with a 4gb csv file i wrote something to put it in a sql database and edited it that way. Anyway in short I don't think vscode is the right tool to handle something large even if it is just txt.

But feel free to convince the vscode developers with a more specific example use case, thanks.

**Comment by aeschli** [comment]
@rogersachan How big is your file? Is it with a .txt file extension?

**Comment by ramya-rao-a** [comment]
_From @ilovesusu_ 

1. Generate a 50mb file, about 2000000 lines
> $:bash
> $:i= 0
> $:while [ $i -le 3000000 ]; do echo "asdfghjjklooiyerqwuhgsdjg" >>hello; i=$(($i + 1)); done
2. Open a 50mb file

**Comment by rogersachan** [comment]
Maybe a switch could be added to `settings.json` that would allow overriding the message?

**Comment by alexandrudima** [comment]
Let's track in #9832 . Generating a file with the provided script (translated to nodejs):
```
var fs = require('fs');

var str = '';
for (var i = 0; i < 3000000; i++) {
	str += 'asdfghjjklooiyerqwuhgsdjg\n';
}
fs.writeFileSync('hello', str);
```

yields a 70MB file which is above our large file threshold
