### ISSUE TITLE
Dragging list element keeps rendering the hover decoration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#153977]
See the grey row that moves up when it scrolls

![Recording 2022-07-02 at 06 34 20](https://user-images.githubusercontent.com/2193314/177003137-edc021f0-14b9-4ad9-ad26-a6a93673faa6.gif)

**Comment by lramos15** [comment]
@joaomoreno I looked into this a bit, but is this something that is within the tree code? Nothing sticks out to be surrounding us registering the drag and drop handlers when it comes to a focus, or hover rendering https://github.com/microsoft/vscode/blob/15bf7a3b4a752b510c97f7ef6eeea23c9183c84c/src/vs/workbench/contrib/files/browser/views/explorerViewer.ts#L1126

**Comment by lramos15** [comment]
> @lramos15 Having both `bug` and `polish` labels is a bit confusing. Those are mutually exclusive.

Oh I always used polish to indicate something that is a small change (at least to the user) and then it's a bug because it shouldn't happen 🤷 . Idk, I guess I'll stick with just bug
