### ISSUE TITLE
自己修改的emmet的snippets被更新掉了

### ISSUE THREAD

**Issue by karl20888** [Microsoft/vscode#154]
自己修改了emmet的snippets，更新后snippets被覆盖了，还要自己重新修改一下，是不是也能像settings那样加写自己的设置比较好？

**Comment by bpasero** [comment]
@karl20888 can you edit your post into english please?

**Comment by karl20888** [comment]
Sorry, I'm Chinese and poor English, I just said, The 0.10.1 update cover the file what I edited the snippets.json in the Emmet. So I need to edit it again. Is it can improve?

**Comment by karl20888** [comment]
@bpasero Sorry, I'm Chinese and poor English, I just said, The 0.10.1 update cover the file what I edited the snippets.json in the Emmet. So I need to edit it again. Is it can improve?

**Comment by ywmail** [comment]
Hi @bpasero , @karl20888 has modified the default snippets. After he updated the vs code to version 0.10.1, he lost the modification. He suggests that could he overwrite the default snippets using "User" or "Workplace" snippets,  just like the way we overwrite the default settings.

**Comment by karl20888** [comment]
@ywmail Thank you for your translation!

**Comment by aeschli** [comment]
Yes, don't modify files inside the VS Code installation. They will be replaced on every update.
We have user definable snippets. Go to File > Preferences > User Snippets. 
They appear on Ctrl + Space.
