### ISSUE TITLE
When in Run/Debug Mode, Stop does not switch back to Design Mode

### ISSUE THREAD

**Issue by bluntcoder** [Microsoft/vscode#15402]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1.  Load up any well formed, error free, node.js Typescript project.
2. Fit F5. VS.Code switches to Debug Mode
3. Hit the red Stop button on the debug transport.

BUG: We're still in Run/Debug Mode, even though program execution has stopped.

**Comment by isidorn** [comment]
This is configuratble via settings, please set
	`"debug.openExplorerOnEnd": true`

**Comment by bluntcoder** [comment]
Thanks! Now for some reason it doesn't open debug windows on F5 anymore.. there doesn't seem to be a configuration for that though.

**Comment by isidorn** [comment]
Welcome. By default we only open the debug window on first start of a debug session and yes this is not currently configurable. But we might introduce a setting.
Would you expect a setting in your user / workspace settings that would get applied to all your debug launch configurations. Or would you expect a setting in launch.json that you could specify per your launch configuration. Or both?

fyi @weinand

**Comment by bluntcoder** [comment]
Thanks for your question. Simply put: Although I understand VS.Code is a
separate product, I would expect it to work like Visual Studio: have two
window configuration modes, a Debug/Run mode and a Design mode. As you
toggle F5 you would be toggling between these two windowing modes. Perhaps
put that in as a configuration option.
ᐧ

* Mark Mikulec*
 Chief Technical Consultant

<http://www.mikutech.com/> London - Hamilton - Toronto
http://www.mikutech.com
Find us: LinkedIn <https://www.linkedin.com/company/4990614>  - Twitter
<https://twitter.com/MikutechTips>

This e-mail  may contain information that is privileged or confidential. If
you are not the intended recipient, please delete the e-mail and any
attachments and notify us immediately.
