### ISSUE TITLE
Support for empty editor groups

### ISSUE THREAD

**Issue by piotrek-k** [Microsoft/vscode#15405]
- VSCode Version: 1.7.1

Really annoying thing: I want to open new file [to the side](https://code.visualstudio.com/Docs/editor/codebasics#_side-by-side-editing). When I do that, it shows the same file. When I use `Ctrl+P`, newly created, duplicated file, stays in background.

Steps to Reproduce:

1.  Go to any file
2.  Press `Ctrl+\`
3. The same file opens up as I've been to. When I then use `Ctrl+P` to open another one, it stays in background.

[Video of how it looks like](https://gfycat.com/GreatShabbyGoldeneye)

What I propose:

1. Don't open the same file after using `Ctrl+\` (why would I want to have a file opened two times?). Show blank space instead.
2. Or at least close this file when I use `Ctrl+P` to open another one.

**Comment by bpasero** [comment]
This requires a new concept of empty editor groups. It should still be configurable if splitting an editor should open an empty group or the same file.

**Comment by jakealbaugh** [comment]
An in-between solution that wouldn't require empty editor groups would be a separate command to _move_ the active file instead of duplicating it when there are at least two files in the active group.

**Comment by ProLoser** [comment]
Could also just make this configurable that if there's more than one file open, the one currently focused is moved to the new group, and if there's only one file open, the duplication occurs. This prevents the need for creating a concept of empty groups entirely yet still covers most people's use-cases.
