### ISSUE TITLE
Settings Profiles - discoverability of how to create them

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#154077]
Clicking on the Settings Profiles item in the status bar opens a quickpick, but gives no clue that to create a new profile I need to use a submenu from the Manage gearwheel.

Ideas:
- Add a hint to the placeholder text
- Add a set of management options at the end of the list
- Add a single "Manage..." option which produces a secondary quickpick replicating options from the submenu already available from the gearwheel.

**Comment by daviddossett** [comment]
This is a good point. I'm slightly worried about adding clutter here but I agree its hard to find in the activity bar. There could be value in surfacing some of those options here. Roughly sketching those ideas:

<img width="1127" alt="CleanShot 2022-07-11 at 13 56 02@2x" src="https://user-images.githubusercontent.com/25163139/178356677-003e724d-7e21-4239-a94c-259b3f37d0d9.png">

**Comment by sandy081** [comment]
I replicated the actions everywhere to make them consistent

<img width="593" alt="image" src="https://user-images.githubusercontent.com/10746682/182549838-ec054d24-37fd-4cbb-b7d3-2789144bd3f6.png">
