### ISSUE TITLE
Git Extension: (WSL) Unable to clone, push, pull with a password protected SSH key

### ISSUE THREAD

**Issue by flipkickmedia** [microsoft/vscode#154019]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: v1.68.1
- OS Version: Windows 11 21H2 (OS Build 22000. 778)

Steps to Reproduce:
- Clean WSL install using Ubuntu 22.04 from the Microsoft store
- Create ed25519 key with a password
- Set permissions of .ssh folder, keys and config:
```
chmod 700 ~/.ssh
chmod 600 ~/.ssh/config
chmod 600 ~/.ssh/authorized_keys
chmod 600 ~/.ssh/known_hosts
chmod 400 ~/.ssh/id_ed25519
chmod 400 ~/.ssh/id_ed25519.pub
```

- ~/.ssh/config
```
Host github.com
    User git
    Hostname github.com
    IdentityFile ~/.ssh/id_ed25519
    PreferredAuthentications publickey
    PubkeyAuthentication yes
```

- ~/.gitconfig
```
[user]
        name = Tom Shaw
        email = tom@flipkick.media
[credential]
        helper = manager-core
```

- git/clone/push/pull via command line: works ok, requests password.
- enable ssh-agent
```
eval `ssh-agent`
ssh-add ~/.ssh/id_ed25519
<enter password>
```
- git/clone/push/pull via command line: works ok, no longer asks for password
- any git operation using VSCode hangs.
- repeat steps above, replace key with one without a password and it works.
- tried with keychain - same bad result
- ~/.ssh/config is being used as I get an error when I add invalid config lines
- followed the instructions: https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases

This is a show stopper for us.  There are no visible logs from a git push/pull. The repository URL format being used is ssh://git@github.com/flipkickmedia/test.git

This is a serious security issue. pub key protection without a password is very insecure. There are other open tickets with this problem.

https://github.com/microsoft/vscode/issues/121231 - this looks like a similar issue but having tried all of the suggestions that ticket remains open and the suggestions don't work.

Some more testing reveals that in order for the SSH agent forwarding to work you need to ensure that you run a task when VSCode first opens up.  This allows the keychain command:
```
eval `keychain --eval /home/tshaw/.ssh/id_ed25519`
```
..to ask for a password and Ive set this to run in my .bashrc.  I tried in .profile 
and it didn't work there. This cannot be done, inside a terminal that isn't opened up outside of VSCode, and it has to be opened, after all the extensions are loaded once the UI has settled down.

If you have more than one repo open (in two folders attachged to the workspace), the forwarding breaks.

If you do anything other than pull as the first thing you do after you type the password (e.g. push, save a file etc) the forwarding breaks.

However, if I repeat this process in an existing WSL instance (not a freshly installed one from the Microsoft Store) this method does not work in any situation.  There is something strange happening somewhere and there is some sort of race condition.

**Comment by flipkickmedia** [comment]
Some more details and a possible solution.

My WSL instance which was failing to work, with the unreliable process of launching ssh-agent had a system user created and was generated from a rootfs tarball directly from Ubuntu.  The process of creating a system user, does not copy over the files held in /etc/skel (namely .profile and .bashrc).

It looks like if you copy over those files from /etc/skel into the users home folder, and add keychain to load inside .bashrc VSCode and launch a terminal before you open VSCode, git push/pull/clone will start to work, as the ssh-agent is running before VSCode launches.

If you open up VSCode whilst the WSL instance is shutdown (wsl --shutdown, then open VSCode), keychain will ask you for your password, if you then enter it, and then try a push/pull/clone, VSCode will still hang. If you then close VSCode and open it up again push/pull/clone work properly as expected.

If I try the same thing with eval `ssh-agent` inside .bashrc, VSCode still fails to work.  Keychain and a copy of the files from /etc/skel are the keys to making it work.

This is not an ideal solution. I would expect VSCode to pick up the SSH_AUTH_SOCK sock file and a running ssh-agent for the current user.  Id also expect some timeout for the remote repo operations and logging which are missing. There is something else in .profile and .bashrc that VSCode needs, aside from the keychain instance running.

I certainly don't want to leave authorized credentials left in a shell session for someone to trip over accidentally and make use of.

To help anyone else, if you put keychain.sh file somewhere safe (/usr/local/bin) chmod +x and add it to your .bashrc, things should work as long as you copy over the files in /etc/skel to your home dir.  This method works if you open a terminal before VSCode opens your WSL session. It will not work if VSCode launches WSL first.

keychain.sh
```
KEYS=($(find ${HOME}/.ssh -perm 400 -type f -not -name "*.*"))
eval `keychain --eval ${KEYS[*]}`
```

**Comment by lszomoru** [comment]
@flipkickmedia, apologies for not getting back to you on this until now. VS Code 1.72 released in September 2022 has added support for [SSH keys with a passphrase](https://code.visualstudio.com/updates/v1_72#_add-support-for-ssh-keys-with-a-passphrase). Not sure if you have had the chance to try it out but I would really appreciate if you would. I will optimistically close this issue for now but please feel free to reopen in case you are still seeing any issues. Thanks!
