### ISSUE TITLE
Settings Profiles - should status bar item label be singular?

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#154074]
![image](https://user-images.githubusercontent.com/6726799/177145073-e69af577-28d2-44bb-a69d-0723c9d5114c.png)

![image](https://user-images.githubusercontent.com/6726799/177145182-a5c7a72d-e5a6-4016-a73c-7195e1619db2.png)

Might be clearer as "Settings Profile" rather than "Settings Profiles".

If so, for consistency the color customizations should perhaps get renamed as well:

![image](https://user-images.githubusercontent.com/6726799/177145538-4e35fd07-e766-4a4f-8605-787f5a0f4c38.png)

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for the feedback, very much appreciated 👏 

**Settings Profiles** is the feature name and is used everywhere like in command pallette. So to be consistent used that everywhere.

**Comment by gjsjohnmurray** [comment]
Fair enough.
