### ISSUE TITLE
File explorer fails when creating new file in folder with "File Nesting" enabled 

### ISSUE THREAD

**Issue by ahkhanjani** [microsoft/vscode#154073]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Windows 11 (Windows_NT x64 10.0.22000)

Bug description:

When "File Nesting" is enabled, if I try to create a new file in a folder that contains nested files, the explorer does not show an input field for file name, but instead it shows a red text field on the upper right corner of file explorer, just like when you try to search for file names after clicking on Explorer tab. In the meantime, explorer stays in its low opacity state and while clicking on files does select them, it doesn't open them and even choosing "Reveal in file explorer" on the right click menu doesn't do anything. Pressing Esc doesn't fix this and the only escape route seems to be pressing "New File" button in a folder that doesn't contain nested files.

![Screenshot (14)](https://user-images.githubusercontent.com/72540492/177145216-071093ca-1976-42a8-83bb-8a8230555bf3.png) ![Screenshot (15)](https://user-images.githubusercontent.com/72540492/177145224-5d213784-63cf-4575-9280-ca08fc463e56.png)

**Comment by lramos15** [comment]
I tried to reproduce this but could not. How nested is your file? If you disable your extensions does it still repro? Can you provide a gif please. Thanks!

**Comment by ahkhanjani** [comment]
Seems to be working fine at the moment. I don't know what fixed it. Thank you
