### ISSUE TITLE
I reloaded the left window again, and it reattached to the correct terminal.

### ISSUE THREAD

**Issue by Ikaberry202** [microsoft/vscode#154058]
I reloaded the left window again, and it reattached to the correct terminal.

![image](https://user-images.githubusercontent.com/323878/134214094-d97a2fd4-0f27-4064-bbdc-48d7db664adb.png)

_Originally posted by @roblourens in https://github.com/microsoft/vscode/issues/133542#issuecomment-924173570_

**Comment by meganrogge** [comment]
Have you been able to reproduce this in insider's?
