### ISSUE TITLE
Settings Profiles quickpick improvements

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#154072]
Issue Type: <b>Feature Request</b>

![image](https://user-images.githubusercontent.com/6726799/177144434-8832f8cf-fdd9-4f0d-bf2f-ea7d4c31f79d.png)

Profiles seem to get listed in order of creation. Is that intentional?

Could "Current" suffix on currently selected one be replaced by a checkmark, similar to how the "Customize Layout..." quickpick indicates currently-selected items?

![image](https://user-images.githubusercontent.com/6726799/177144589-c8b4f6f1-153c-4b85-b02d-e559aa7375ae.png)

VS Code version: Code - Insiders 1.69.0-insider (0b3574dcef8f35fec4ee4f83dc958c1f16ef6fce, 2022-07-01T05:17:04.343Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by sandy081** [comment]
> Profiles seem to get listed in order of creation. Is that intentional?

Nope. Let me know what is the order you expect?

> Could "Current" suffix on currently selected one be replaced by a checkmark, similar to how the "Customize Layout..." quickpick indicates currently-selected items?

That's a good idea.

**Comment by gjsjohnmurray** [comment]
> Nope. Let me know what is the order you expect?

This submenu used alpha sorting, which makes sense except perhaps "Default" deserves to get pushed to the top or the bottom:

![image](https://user-images.githubusercontent.com/6726799/177183387-9c721998-32d4-487f-8e7a-bfad37d18a42.png)
