### ISSUE TITLE
Debug - StreamDebugAdapter

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#154051]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=67591&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=cb28bb6e-8e39-5e89-2bed-f852c76efa16&l=9741

```
1) Debug - StreamDebugAdapter
       StreamDebugAdapter (NamedPipeDebugAdapter) can initialize a connection:

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.




```

**Comment by bpasero** [comment]
Prior: https://github.com/microsoft/vscode/issues/143967

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/155801
