### ISSUE TITLE
Find in files is broken

### ISSUE THREAD

**Issue by garfieldbanks** [Microsoft/vscode#15409]
- VSCode Version: 1.7.1
- OS Version: Windows 14393

Steps to Reproduce:

1. Open a folder with many files
2. Search for known text in files
3. Zero files are found

**Comment by garfieldbanks** [comment]
The issue might be UTF-16 LE.

**Comment by garfieldbanks** [comment]
Created more specific issue: #17408

**Comment by bpasero** [comment]
@garfieldbanks sorry for not being very active on this issue we should have looked into it right when you reported it...
