### ISSUE TITLE
FIle content not show in workspace

### ISSUE THREAD

**Issue by JainamShah3008** [microsoft/vscode#154045]
Issue Type: <b>Performance Issue</b>

In workspace(when codes are writing) the file contents are not showing

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.15.0-33-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 0|
|Memory (System)|31.20GB (24.23GB free)|
|Process Argv|--no-sandbox --force-user-env --open-url /opt/lampp/htdocs/coocu --crash-reporter-id a2f00e02-7348-4b88-b9eb-b8b0eef09778|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   128	  8858	code main
    0	    32	  8860	   zygote
    0	    64	  8916	     gpu-process
    0	    32	  8861	   zygote
    0	    64	  9943	     issue-reporter
    0	    32	  8914	   utility-network-service
    0	   128	  8983	   shared-process
    0	    64	  9014	     ptyHost
    0	    64	  9731	     fileWatcher
    0	     0	  9960	     /bin/sh -c /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	  9961	       /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   256	  9672	   window (Visual Studio Code)
    0	   160	  9756	   extensionHost
    0	    64	  9771	     /snap/code/99/usr/share/code/code --ms-enable-electron-run-as-node /home/ajay-groovy/.vscode/extensions/formulahendry.auto-rename-tag-0.1.10/packages/server/dist/serverMain.js --node-ipc --clientProcessId=9756
    0	    64	  9817	     /snap/code/99/usr/share/code/code --ms-enable-electron-run-as-node /snap/code/99/usr/share/code/resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=9756
    0	    64	  9828	     /snap/code/99/usr/share/code/code --ms-enable-electron-run-as-node /home/ajay-groovy/.vscode/extensions/ms-azuretools.vscode-docker-1.22.0/dist/dockerfile-language-server-nodejs/lib/server.js --node-ipc --node-ipc --clientProcessId=9756
    0	    64	  9829	     /snap/code/99/usr/share/code/code --ms-enable-electron-run-as-node /home/ajay-groovy/.vscode/extensions/ms-azuretools.vscode-docker-1.22.0/dist/compose-language-service/lib/server.js --node-ipc --node-ipc --clientProcessId=9756
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
ACF-Snippet|ant|1.9.0
print-it|bma|0.1.5
vscode-intelephense-client|bme|1.8.2
path-intellisense|chr|2.8.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.1
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
wordpress|hri|1.0.1
vscode-peacock|joh|4.0.1
vscode-colorize|kam|0.11.1
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.0
debugger-for-chrome|msj|4.13.0
vetur|oct|0.35.0
vscode-css-peek|pra|4.2.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.5
change-case|wma|1.0.0
php-debug|xde|1.27.0

(6 theme extensions excluded)

</details>

**Comment by JainamShah3008** [comment]
So, I said the project file will be show but the files all content are not
showing, pls fix my issue
Thank you.

**Comment by bpasero** [comment]
:-/

**Comment by JainamShah3008** [comment]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/66919264/177124100-0fbb73f5-569e-4289-b629-90993562bd3f.gif)
As I am say , The file and folders show in the explorer but the file contents (where we will bw write the code ) not show .

**Comment by bpasero** [comment]
Interesting, thanks for the screenshot!

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by JainamShah3008** [comment]
I have already uninstall vs code and install vs code
Pls fix my issue

**Comment by bpasero** [comment]
insiders is a different flavour of VSCode though did you try? https://code.visualstudio.com/insiders/

**Comment by JainamShah3008** [comment]
But I used vs code not insider. Pls solve my issue

**Comment by bpasero** [comment]
Please see if you can find any logged output that could help us find the source of the issue:
* run `code --verbose` from the command line and attach the output
* in Code select **Help | Toggle Developer Tools** and select the **Console**
* attach any output you see in the **Console** you can find

Thanks!

**Comment by JainamShah3008** [comment]
Yes In workbench.desktop.main.js filw show the error

**Comment by bpasero** [comment]
Can you share it?

**Comment by JainamShah3008** [comment]
I run command code --verbose then the issue will be solve.
Thnaks.

**Comment by bpasero** [comment]
Ok weird, I cannot explain that 😕

**Comment by JainamShah3008** [comment]
Ok Not a problem my issue was fixed.
Thnak u for the appreciations
