### ISSUE TITLE
Remove check of PIOS in adding sources list for deb

### ISSUE THREAD

**Issue by theofficialgman** [microsoft/vscode#154038]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: all
- OS Version: Raspberry PiOS

Steps to Reproduce:

1. install using deb
2. expect to get the vscode deb repo

The problem is the code contains the check for piOS
```
	if [ ! -f $CODE_SOURCE_PART ] && [ ! -f /etc/rpi-issue ]; then
		# Write source list if it does not exist and we're not running on Raspberry Pi OS
		WRITE_SOURCE=1
```
piOS developers have STOPPED distributing code in the repos (they only contain code up to March 2022, 1.66 )
https://archive.raspberrypi.org/debian/pool/main/c/code/

it appears that they do NOT plan to distribute code anymore, so this check should be removed and the sources list should be added when installing the deb on piOS, like all other platforms

**Comment by Tyriar** [comment]
@XECDesign any comment on this?

**Comment by XECDesign** [comment]
Thanks for the ping. Looks like the system that pulls in the files had an issue.

It's fixed and everything should be up and running as normal now.

**Comment by Tyriar** [comment]
@XECDesign just making sure, we can close this off right?

**Comment by XECDesign** [comment]
Yup

**Comment by theofficialgman** [comment]
seems to be fixed (verified the repos have the updated packages now)
closing
