### ISSUE TITLE
File explorer freezes | unable to open/close files | on close message "Discarding backups is taking a bit longer"

### ISSUE THREAD

**Issue by clemens-zauchner** [microsoft/vscode#154085]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1 / 30d9c6cd9483b2cc586687151bcbcd635f373630 / x64

- OS Version: Pop!_OS 22.04 LTS

Steps to Reproduce:

1. Open VSCode
2. Open / Close File

A few days ago, VSCode started to not be able to open / close files in my project and the explorer indicates to be busy:

![image](https://user-images.githubusercontent.com/29435287/177157103-7403feaa-de78-42e0-aa99-cfe8bf0a5e2d.png)

When trying to close the application, there is a popup "Dicarding backups is taking a bit longer..." 

![image](https://user-images.githubusercontent.com/29435287/177157998-6747fb5c-e000-482e-8da9-34038fa84ff4.png)

When hitting Cancel, another popup appears saying "Reloading the window is taking a bit longer", but actually never reopens or shuts down, so I am forced to`pkill code` from the CLI.

![image](https://user-images.githubusercontent.com/29435287/177156997-eddf362c-2568-4a1f-9f90-ffeb8a804dc5.png)

I have tried to remedy the issue with no success by deleting contents of several folder in `~/.config/Code`:

- Cache
- Code Cache
- CachedConfigurations
- CachedData
- CachedExtensions
- CachedExtensionVSIXs
- Session Storage
- Workspaces
- Backups

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by clemens-zauchner** [comment]
I have tried it, but it persists with that option.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by clemens-zauchner** [comment]
I have worked with the nightly inside build `1.69.0-1657047388_amd64` for a couple of days now and everything runs smoothly.

**Comment by eahenle** [comment]
I have this exact problem with a freshly updated installation:
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-46-generic

This bug has rendered VSCode nearly impossible to use.  After some time, all active instances of the application will cease reading/writing files and the only way to restore function is to kill the application in such a way that no backups are provided anyway.  Is there any way to completely disable this backups feature?  It is presently counter-productive.
