### ISSUE TITLE
Add default workspace for the lightness of the editor

### ISSUE THREAD

**Issue by MrShnaider** [microsoft/vscode#154070]
## Problem

I use vscode for two use cases: developing a full-fledged project or editing text files. For projects, I need heavy-weight extensions that load when vscode starts. Sometimes it takes 30 seconds and completely hangs the system. But when I open a file (most often markdown) I don't want to wait until all the extensions I don't need are initialized.

This behavior forces me to edit text files in lightweight programs such as notepad++. And it is more convenient to work with heavy applications in full-fledged large IDEs that require the same loading time, which completely kills the concept of modularity of vscode.

## Possible solution

The editor already has the ability to disable extensions for certain workspaces. But there is no way to deploy the same workspace by default. If you forget to close the workspace with heavy extensions, you will have to wait for them to load while the editor is turned on. I suggest adding an optional setting in which you can prescribe a workspace that opens by default. Something like `"workspace.default.path": "~/workspaces/markdown.code-workspace"`. If the path is set, then this workspace and, as a result, its extensions will be loaded by default

## Result

Just one optional setting will allow us to cover both vscode use cases, which will allow us not to switch between third-party editors and use a single ecosystem for all text edits.

**Comment by gjsjohnmurray** [comment]
The upcoming Settings Profiles feature of 1.69 (scheduled to release by Thursday this week) should help here.

You can already try it on Insiders and read about it in the upcoming release notes at https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_69.md#settings-profiles

**Comment by dbaeumer** [comment]
@sandy081 can you comment on whether profiles will help here?

**Comment by sandy081** [comment]
Yeah it can be possible by configuring an empty profile for empty window.

@MrShnaider Can you please give a try and let us know the feedback?
