### ISSUE TITLE
VSCode debugger panel overlaps tabs 

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#15418]
- VSCode Version: Version 1.7.1 (1.7.1)
- OS Version:  OSX 10.9

![image](https://cloud.githubusercontent.com/assets/1018196/20243651/a7b63cdc-a915-11e6-84bc-4bfa3fca6ea2.png)

It would make sense for panel to not obstruct tabs and be just above the variables tab and below launch.

I have to move that panel every now and then to access other tabs via mouse. The usability could be improved.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/9093, https://github.com/Microsoft/vscode/issues/2513
