### ISSUE TITLE
VScode 1.68.1 : freezes

### ISSUE THREAD

**Issue by LeHibou2** [microsoft/vscode#154106]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.68.1
- OS Version: Debian 11 stable. VSCode installed via snap --classic. System up to date.

Steps to Reproduce:

1. Open the app
2. Hover the status bar and primary side bar multiple times. At a point, the cursor will switch very rapidly between the hand and the arrow and no commands are active. Minimizing just get things worse with a black application window.

Note:
It appears that hovering a certain number of times the status bar and primary side bar will make VSCode to hang with the symptoms above.
All extensions disabled.
It is really annoying because I cannot work a long time (a few minutes), since I often hover those bars.

Then I must kill the app to reload it. Sometimes, it will hang almost immediately on restart.

I experienced the same issue on another computer, running the same OS.
I cannot say for the Windows version.

The app has been installed via snap with the --classic switch.

No other app do that on my system.

Thanks,

**Comment by LeHibou2** [comment]
hmmmm. I am currently trying the official version, which seems not to suffer from the symptoms above found in the snap version..
Let me two hours I will report back.

**Comment by LeHibou2** [comment]
No, does the same.
Moving the window around, when possible, temporarily solve the issue. But the issue comes back moments later..

**Comment by LeHibou2** [comment]
Apparently, zoom level was the culprit. It was set to -1. Since I put it back to 0, no more issue.

To be confirmed at the end of the day.

**Comment by LeHibou2** [comment]
No. Just started again..
What is going on?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/152843
