### ISSUE TITLE
Remove collects.forEach

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#154195]
This tracks removing the `forEach` function defined in `collections.ts`. Instead you should use `Object.entries()` with a `for...of` loop
 
Current consumers: 

- [ ] `src/vs/base/test/common/collections.test.ts` @mjbvz
- [x] `src/vs/editor/browser/config/migrateOptions.ts` @alexdima 
- [x] `src/vs/platform/extensionManagement/common/extensionTipsService.ts` @sandy081 
- [x] `src/vs/platform/extensionManagement/electron-sandbox/extensionTipsService.ts` @sandy081 
- [x] `src/vs/workbench/api/browser/mainThreadDialogs.ts` @jrieken 
- [x] `src/vs/workbench/api/browser/mainThreadTask.ts` @meganrogge 
- [x] `src/vs/workbench/api/browser/viewsExtensionPoint.ts` @sandy081 
- [x] `src/vs/workbench/api/test/browser/extHostTypeConverter.test.ts` @mjbvz 
- [x] `src/vs/workbench/contrib/extensions/browser/fileBasedRecommendations.ts` @sandy081 
- [x] `src/vs/workbench/contrib/snippets/browser/snippetsFile.ts` @jrieken 
- [x] `src/vs/workbench/contrib/tasks/browser/runAutomaticTasks.ts` @meganrogge 
- [x] `src/vs/workbench/services/actions/common/menusExtensionPoint.ts` @sbatten 
- [x] `src/vs/workbench/services/configuration/browser/configurationService.ts` @sandy081 
- [x] `src/vs/workbench/services/configurationResolver/browser/baseConfigurationResolverService.ts` @meganrogge   
- [x] `src/vs/workbench/services/extensionManagement/browser/webExtensionsScannerService.ts` @sandy081 
- [ ] `src/vs/workbench/services/extensions/common/abstractExtensionService.ts` @alexdima

**Comment by sandy081** [comment]
@alexr00 Assigned this item `src/vs/workbench/services/configurationResolver/browser/baseConfigurationResolverService.ts` to you, assuming you own it.

**Comment by meganrogge** [comment]
@sandy081 I now own tasks, so can take care of that one
