### ISSUE TITLE
I would like to replace the computer after the synchronization of all the configuration and plug-ins

### ISSUE THREAD

**Issue by lifetin** [Microsoft/vscode#15417]
- VSCode Version:1.7
- OS Version: win10

I would like to replace the computer after the synchronization of all the configuration and plug-ins
When can the user login?
And then synchronize the configuration and extension?
So I can replace the computer at any time you can use the same operation

**Comment by kaiwood** [comment]
VSCode doesn't support syncing by itself currently. But there is a pretty good working extension for this: https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync

**Comment by lifetin** [comment]
I am the Chinese area, visit GitHub a bit slow, why Microsoft does not add this feature, you can use Microsoft account login, use OneDrive to automatically upload?
I very much like the chrome automatic synchronization function, so I change the computer, will automatically download all of my configuration

**Comment by lifetin** [comment]
Use Shan.code-settings-sync
I'll be in trouble.

**Comment by aeschli** [comment]
duplicate of #7311
