### ISSUE TITLE
Error: EROFS: read-only file system

### ISSUE THREAD

**Issue by dcsan** [microsoft/vscode#154113]
Does this issue occur when all extensions are disabled?: Yes/No
Hard to be sure since it is intermittent

- VS Code Version: Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:37.209Z (2 wks ago)
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.4.0

Steps to Reproduce:

1. work on a file, hit save
2. intermittently will get a new empty "Untitled" file created, and VSCode is trying to save it to the root of my file system. eg `/Untitled` - which of course it cannot write to.

Once this error happens it will happen every time I try and save. The only way to continue is close the Untitled file and the dialog...

![image](https://user-images.githubusercontent.com/514002/177223516-8999b966-ff6e-4352-a9dc-e98f50f60ae8.png)

This has been going on for months so I finally logged a bug.

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by dcsan** [comment]
its hard to test, as I'm not quite sure what triggers the situation. I can work for hours and it's ok other times it just keeps happening on every save.

is there a command to list what extensions are in use for a bug report?

**Comment by bpasero** [comment]
![image](https://user-images.githubusercontent.com/900690/179688346-a519d7b3-2b82-4d62-af9c-07f4305ca8ae.png)

**Comment by bpasero** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
