### ISSUE TITLE
Screen Reader focus lost when moving into VS Code window from outside

### ISSUE THREAD

**Issue by leonardder** [microsoft/vscode#154137]
Issue Type: <b>Bug</b>

Steps to reproduce:

1. Open a fresh document in VS Code Insiders
2. Press Win+D to go to the desktop
3. Press Alt+Tab to get back to VS Code

observe that according to the screen reader (NVDA in this case), the focus doesn't return to the document and is in fact trapped. Even going to the menu bar doesn't help. Maximizing sometimes helps, sometimes it doesn't either.

VS Code version: Code - Insiders 1.69.0-insider (2932e29645f12f08235b7560b3f7d763b8a1cf25, 2022-07-04T10:51:04.591Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by leonardder** [comment]
Can also repro with Narrator

CC @isidorn

**Comment by GabrieleBattaglia** [comment]
I also having this issue. I can't use VSCode any longer.
VSCode insider + NVDA 2021.1 + Win11 64B

**Comment by deepak1556** [comment]
Thanks for the repro, it was helpful to confirmed the issue. Merging to https://github.com/microsoft/vscode/issues/152291, please follow the issue for updates.

In the meantime, please revert to `1.68` release which you can download from https://code.visualstudio.com/updates/v1_68 and ensure the setting `update.mode: "none"` is set.
