### ISSUE TITLE
VS Code Freeze

### ISSUE THREAD

**Issue by bob452628419** [microsoft/vscode#154140]
Issue Type: <b>Performance Issue</b>

No specific action, it occurs periodically whenever I'm coding or just reviewing the code. VS Code just say it's not responding and waiting for 10 or 20 secs will recover.

VS Code version: Code 1.68.1 (Universal) (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:52:13.188Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 3.10.0-1160.49.1.el7.x86_64
Remote OS version: Linux x64 3.10.0-1160.49.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id cb9a1c41-9560-42dc-83e8-51b7fe20d272|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: h202|
|OS|Linux x64 3.10.0-1160.49.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 799)|
|Memory (System)|251.21GB (14.75GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: h202|
|OS|Linux x64 3.10.0-1160.49.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz (64 x 799)|
|Memory (System)|251.21GB (14.74GB free)|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   164	 16768	code main
    0	    66	 16773	   gpu-process
    0	    33	 16775	   utility-network-service
    0	   115	 16812	   shared-process
    0	    33	 16816	     ptyHost
    0	     0	 19986	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    33	 47257	     fileWatcher
    0	    33	 47339	     fileWatcher
    1	    66	 19982	   issue-reporter
    0	   459	 47238	   window (gw_ltt_mgr.h — crc202 (Workspace) [SSH: h202])
    0	    82	 47244	   extensionHost
    0	    33	 47251	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/BoberDong/.vscode/extensions/ms-vscode-remote.remote-ssh-0.82.1/out/localServer.js {"serverId":1,"ipcHandlePath":"/var/folders/tx/jc1qjgyd78j1slx7s59xgcvw0000gq/T/vscode-ssh-askpass-6be7216422373fbb75e5332b106c96853ad63f8a.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","54087","-o","ConnectTimeout=15","h202"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/BoberDong/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-2997023d-30d9c6cd9483b2cc586687151bcbcd635f373630-0.82.1/data.json"}
    0	     0	 47256	       ssh -v -T -D 54087 -o ConnectTimeout=15 h202
    0	   508	 47319	   window (SBConfUI.cpp — client-all (Workspace) [SSH: h202])
    0	    98	 47334	   extensionHost

Remote: SSH: h202
CPU %	Mem MB	   PID	Process
    0	     0	182311	remote agent
    0	     0	182355	   ptyHost
    0	     0	193293	     /bin/zsh
    0	     0	246913	       sh docker_make.sh -f Makefile.rc RELEASE=1
    0	     0	246933	         docker run -e CRC_BUILDER_ENV=docker -it -v/home/bober:/home/bober -w /home/bober/code/tex --rm --privileged tex-32-builder:v2 sh -c make -f Makefile.rc RELEASE=1
    0	     0	229294	     /usr/bin/zsh
    0	     0	245036	       ssh h91
    0	     0	249695	   /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=

Remote: SSH: h202
CPU %	Mem MB	   PID	Process
    0	     0	182311	remote agent
    0	     0	182355	   ptyHost
    0	     0	193293	     /bin/zsh
    0	     0	246913	       sh docker_make.sh -f Makefile.rc RELEASE=1
    0	     0	246933	         docker run -e TEX_BUILDER_ENV=docker -it -v/home/bober:/home/bober -w /home/bober/code/tex --rm --privileged tex-32-builder:v2 sh -c make -f Makefile.rc RELEASE=1
    0	     0	229294	     /usr/bin/zsh
    0	     0	245036	       ssh h91
    0	     0	249696	   /usr/bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```

|  Remote: SSH: h202
|  Remote: SSH: h202;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.4
remote-containers|ms-|0.238.3
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vim|vsc|1.23.1
gitlens|eam|12.1.1
git-graph|mhu|1.30.0
cpptools|ms-|1.10.7
cpptools-extension-pack|ms-|1.2.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Looks like this issue didn't get the correct attention when it was first opened

I'm closing it since there hasn't been any follow up.  If you are still seeing this issue with extensions disabled in the latest stable version, let us know
