### ISSUE TITLE
files.exclude doesn't work for .gitignore files since updating to 1.6.8

### ISSUE THREAD

**Issue by dlgombert** [microsoft/vscode#154186]
Issue Type: <b>Bug</b>

Since the latest update, the "files.exclude" setting at both workspace and folder level won't hide .gitignore  files.  Tried with explorer.excludeGitIgnore settings both true and false, and doesn't seem to have an impact.  Also, tried a bunch of variations of globbing, e.g. `.gitignore, **/.gitignore, ./*.gitignore`, etc etc.  Just won't hide 'em.   I also checked for accidental settings overrides, but couldn't find any.

All other excluded files are hidden as normal.  

Also, for what it's worth, this is a multi-root workspace. 

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.65GB free)|
|Process Argv|mapd.conf --crash-reporter-id 18a61146-edd4-4e4d-9691-e3e49348ecdc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
vscode-nginx-conf|ahm|0.1.3
vscode-custom-css|be5|6.0.2
unique-lines|bib|1.0.0
vscode-intelephense-client|bme|1.8.2
vue-docblocker|BoW|2.1.0
split-line|che|1.0.2
sql-keyword-uppercase|chu|0.0.1
indent4to2|Com|0.1.2
split-html-attributes|dan|1.0.10
vscode-eslint|dba|2.2.6
hscopes|dra|0.0.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
laravel-ide-helper|geo|0.0.5
lintlens|ghm|3.0.3
selected-lines-count|gur|1.4.0
helium-icon-theme|hel|1.0.0
jsx|Hen|1.3.0
vscode-sort|hen|0.2.5
vscode-es6-string-html|hjb|1.1.1
beautify|Hoo|1.5.0
vscode-favorites|how|1.10.2
easy-icons|jam|0.3.1
gruvbox-material-icon-theme|Jon|1.1.5
pop-n-lock-theme-vscode|Lux|3.32.7
xml-format|mik|1.1.2
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.22.0
powershell|ms-|2022.6.3
vscode-typescript-next|ms-|4.8.20220704
reload|nat|0.0.6
php-docblocker|nei|2.7.0
title|nil|0.1.0
vetur|oct|0.35.0
vscode-versionlens|pfl|1.0.10
material-icon-theme|PKi|4.19.0
material-product-icons|PKi|1.3.0
vscode-template-literal-editor|pli|0.10.0
nginx-formatter|ray|0.0.13
ActiveFileInStatusBar|Ros|1.0.3
bootstrap-product-icons|rub|1.0.2
vs-code-prettier-eslint|rve|5.0.3
multi-command|ryu|1.5.1
gruvbox-material|sai|6.5.0
vscode-blade-formatter|shu|0.16.1
vscode-scss-formatter|sib|2.4.3
vscode-phpsab|val|0.0.15
vscode-wpcs-whitelist-flags|vij|1.0.3
rainbow-tags|vol|0.4.1
vscode-nginx|wil|0.7.2
explicit-folding|zok|0.21.0

(11 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
This should be fixed in the upcoming update. It will release end of this week so please try again on Friday after updating. Thank you!
