### ISSUE TITLE
Hotkey for dotnet.test.debug command doesn't work

### ISSUE THREAD

**Issue by nick-korsakov** [Microsoft/vscode#15413]
## Steps to reproduce
Use this keybindings.json:
```json
[
    {
        "key": "alt+f5",
        "command": "dotnet.test.debug"
    }
]
```
Set breakpoint inside test method, point the cursor inside the test method and hit Alt+F5.

P.S.: Don't offer me to use mouse and click "debug test" link. I like to hide reference info links and use hotkeys to execute an actions.

## Expected  behavior
Current test executed in debug mode as it happes when I click "debug test" link above this test method.

## Actual behavior
Debug session doesn't started.

## Environment data
`dotnet --info` output:
.NET Command Line Tools (1.0.0-preview2-003133)

Product Information:
 Version:            1.0.0-preview2-003133
 Commit SHA-1 hash:  74df06500c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x64

**Comment by aeschli** [comment]
Are you using the C# extension (https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp)? Please file the issue directly against https://github.com/OmniSharp/omnisharp-vscode/issues
