### ISSUE TITLE
Have more relaxed suggest matching algorithm

### ISSUE THREAD

**Issue by godblesshugh** [Microsoft/vscode#15419]
- VSCode Version:1.7.1 (1.7.1) 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
- OS Version:OSX 10.12

Steps to Reproduce:

more like fix than autocomplete the wrong typing, accidentally typed 'rlut' for 'result'.
likes this in sublime.
![image](https://cloud.githubusercontent.com/assets/7351942/20244242/c90a27e6-a9b4-11e6-8077-5a337d773a75.png)

**Comment by jrieken** [comment]
<img width="427" alt="screen shot 2017-11-24 at 15 52 39" src="https://user-images.githubusercontent.com/1794099/33215309-8c92da12-d12f-11e7-9139-888f4c6efded.png">

I have something I think it's pretty cool. The logic by running a few simple permutations when compute scores. So, with above sample not just `rlut` but also `rult` and `rltu`. That yield pretty good results, as visible in the screen shot. Question if we should do this always or only when the original search, e.g. with `rlut` didn't produce a match...

**Comment by jrieken** [comment]
Closing, please keep an eye open so we can tweak this
