### ISSUE TITLE
copyLinesDownAction is not working.

### ISSUE THREAD

**Issue by pratikborsadiya** [microsoft/vscode#154160]
Issue Type: <b>Bug</b>

copyLinesDownAction shortcut key is not working.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (4.99GB free)|
|Process Argv|--crash-reporter-id f53560f7-6af8-4998-8e52-9c545d4e78e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
sublime-keybindings|ms-|4.0.10
vsliveshare|ms-|1.0.5625

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdc:30486549

```

</details>

**Comment by ArturoDent** [comment]
When you run the `Toggle Keyboard Shortcuts Troubleshooting` command what do you see when you trigger the shortcut key you are using?

**Comment by pratikborsadiya** [comment]
![image](https://user-images.githubusercontent.com/7806891/177473428-8fc7974a-e8c6-4655-9533-486f1502e428.png)

I am trying to press `ctrl + shift + d` key combination. It's not working.

**Comment by alexdima** [comment]
@pratikborsadiya This log indicates that VS Code is not receiving the keypress `ctrl + shift + D` from the OS. There is nothing we can do on our side when we don't receive a keypress from the OS. If you haven't manually configured it for an OS level feature, most likely there is some other piece of software on your machine that is "eating it up".
