### ISSUE TITLE
Format document with conditional compilation in C# will not format code ignored by condition

### ISSUE THREAD

**Issue by PeterHimschoot** [Microsoft/vscode#15423]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. For example, this code:
#define WITH_DISPOSE

using System;

namespace HiddenIDisposables
{
#if WITH_DISPOSE
    public class SomeResource : ISomeResource, IDisposable
    {
        public string Foo()
        {
            return "Foo";
        }

        void IDisposable.Dispose()
        {
            System.Console.WriteLine("Resource has been disposed");
        }
    }
#else
    public class SomeResource : ISomeResource
    {
        public string Foo()
    {
                      return "Foo";
              }
    }
#endif
}

2. Format document ignores the #else part

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#926
