### ISSUE TITLE
Format document in a C# file does not use the configured tab-size (while inserting spaces)

### ISSUE THREAD

**Issue by PeterHimschoot** [Microsoft/vscode#15422]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.4|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.5.40|
|vscode-npm-script|eg2|0.0.21|
|sass-lint|glen-84|0.0.3|
|Angular2|johnpapa|1.0.2|
|docomment|k--kato|0.0.7|
|csharp|ms-vscode|1.4.1|
|mono-debug|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|2.2.1|
|sass-indented|robinbentley|1.2.1|
|yo|samverschueren|0.9.2|
|bootstrap-3-snippets|wcwhitehead|0.0.8|

---

Steps to Reproduce:

1. configure code as follows 
  "editor.tabSize": 2,
  "editor.useTabStops": false,
  "editor.insertSpaces": true,
 
2. Select C# file and choose Format Document. Editor still inserts 4 spaces.

**Comment by aeschli** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#927
