### ISSUE TITLE
Extensibility: Typed Commands

### ISSUE THREAD

**Issue by hediet** [Microsoft/vscode#15426]
It seems that vscodes prefererred way of offering API endpoints to extensions is through commands.
For example, vscode.TextEditor's method `hide` is deprecated in favor of the command `workbench.action.closeActiveEditor`. While there might be good reasons to do so, it has the huge disadvantage of loosing types, as there is only the function executeCommand:
`function executeCommand<T>(command: string, ...rest: any[]): Thenable<T>;`

Are there any plans to improve that?

**Comment by jrieken** [comment]
We are not planning to use commands over typed API. We are constantly extending the API. We have some [API commands](http://code.visualstudio.com/docs/extensionAPI/vscode-api-commands) for less commonly used parts and generally all commands that can be used via keybindings.
