### ISSUE TITLE
Error 500 When Trying To Access phpMyAdmin

### ISSUE THREAD

**Issue by hmccafferty** [microsoft/vscode#154271]
I'm a newbie so I apologize if I'm doing this wrong.  

When clicking on my sqlite3 db file in the codespace IDE navigation pane, I get the white page with the URL to authorize GitHub Preview.  When I click on the URL, it results in Error 500.  This had previously worked when I first began but stopped working shortly after and only resulted in Error 500 from then on.

I've tried finding web resources to fix this issue but haven't been successful finding anyone with the same issue. I'm only asking for help in '

Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36 Edg/103.0.1264.37
Embedder: codespaces

**Comment by hmccafferty** [comment]
![Screenshot 2022-07-06 103847](https://user-images.githubusercontent.com/42415758/177614452-a34cc86d-b8dc-4544-8020-b1d9dcdb0850.png)
![Screenshot 2022-07-06 104112](https://user-images.githubusercontent.com/42415758/177614458-e160ecb4-50a7-4bfa-9b5c-11ad69c91678.png)

**Comment by TylerLeonhardt** [comment]
Seems like it may be a GitHub issue since you're trying to load a `.githubpreview.dev` url. @jkeech are you aware of any outages in this space?

**Comment by hmccafferty** [comment]
@TylerLeonhardt unfortunately, yes - still persisting.  It's been like this for maybe a week/week and a half or so.  It worked fine previously, both of all other projects and even worked for a day or two with this same project where it went bad.  It seems to have coincided with my altering the db by adding new tables to cs50's finance.db file.

**Comment by TylerLeonhardt** [comment]
This doesn't seem related to VS Code itself... and I think GitHub had this past week off so @jkeech might not respond til next  next... but my recommendation is to open this over in: https://support.github.com/features/codespaces they might be able to help you more than I since this seems related to Codespaces

**Comment by jkeech** [comment]
Apologies for the delayed response -- A GitHub support ticket or posting on the GitHub Community discussions in the [Codespaces category](https://github.com/github-community/community/discussions/categories/codespaces) is the best way to ask for help with Codespaces.

The page that is shown in the screenshot with the "Please visit the following link to authorize GitHub Preview" message appears to be coming from the CS50 source code: https://github.com/cs50/phpliteadmin.vsix/blob/684087fd0802cd9eeea1a037178de13185aae14d/src/phpLiteAdmin.ts#L122. I'm not sure why the link would result in a 500 when clicking on it, but we can investigate that. One thing worth double checking is that the port 8082 is forwarded and visible in the Ports tab in VS Code. The port would need to be forwarded first before it's accessible over that url.

**Comment by hmccafferty** [comment]
My apologies right back at you.  That's a great diagnosis - port 8082 is no longer forwarded whereas it had been previously.  I don't know enough to know what changed or why though.
