### ISSUE TITLE
Question - Will using white as editor background cause issues?

### ISSUE THREAD

**Issue by M-Willett** [microsoft/vscode#154257]
Please could someone provide a summary of what this bug is and why the color white cannot be used? (I'm wondering if using it will cause problems in our project)

I'm unable to view the link in the comment as I don't have access to the project:
https://github.com/microsoft/vscode/blob/b1eab983e40dfdca90d0f9833b00afe4233c12c3/src/vs/platform/theme/common/colorRegistry.ts#L306

Screenshot:
![image](https://user-images.githubusercontent.com/2579403/177544795-0f4d2b54-362e-417f-9e4b-989b7c999e26.png)

Many thanks

**Comment by aeschli** [comment]
@jrieken Do you remember more about https://monacotools.visualstudio.com/Monaco/_workitems/edit/13254?

**Comment by jrieken** [comment]
I believe that was some IE limitation from back in the days and not needed anymore. Adding @alexdima for a trip down memory-lane. 

@M-Willett do answer you question: No, using white shouldn't cause any issue

**Comment by alexdima** [comment]
Yes, this was a workaround for an old IE version. We can remove this safely.
