### ISSUE TITLE
Error when using bash for windows in tasks

### ISSUE THREAD

**Issue by lkempf** [Microsoft/vscode#15427]
- VSCode Version: 1.7.1
- OS Version: Windows 10 AU

Steps to Reproduce:

1. Create a tasks.json with the command "C:\\Windows\\sysnative\\bash.exe" and the parameters "-c" and "help"
2. Launch the task

The output now shows Error 0x80070057 with � after each character. Changing "isShellCommand" does nothing.

When executing the same command in cmd it works as expected.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/6579
