### ISSUE TITLE
Unable to close.

### ISSUE THREAD

**Issue by profiler-bg** [Microsoft/vscode#1542]
I created a new file. Pasted some content (setting the right file type with the console). And closed the file with Ctrl + W. I did not get a prompt to save changes and the file was not active anymore, although I can see it in "Working files section" and if I click on it the file with pasted content can be seen. At that point when I try to close the file (pressing X in "Working files" pane) or closing Code, it asks me if I want to save the file. Selecting "Don't save" doesn't close the file/application but selecting "Cancel" does. That was on 0.10.4

**Comment by bpasero** [comment]
@profiler-bg should be fixed with 0.10.5
