### ISSUE TITLE
API: vscode.workspace.findfiles() no longer works with subfolders (since version 1.7.1)

### ISSUE THREAD

**Issue by zabel-xyz** [Microsoft/vscode#15424]
- VSCode Version:  1.7.1
- OS Version: Windows 10

Steps to Reproduce:
**Structure**
```
   D:\Develop\GIT\Test_2 (workspace)
       |- folder
           |- abc.txt
           |- subfolder
              |- test.txt

```
**with the character / it no longer works in subfolder:**
```
  vscode.workspace.findfiles('folder/abc.txt', {.history,.vscode,**/node_modules,typings,out}); // return 1 file ok
  vscode.workspace.findfiles('folder/subfolder/test.txt', {.history,.vscode,**/node_modules,typings,out});  // return 0 file => error it must be 1
```

**with the character \ it works:**
```
  vscode.workspace.findfiles('folder\abc.txt', {.history,.vscode,**/node_modules,typings,out}); // return 1 file ok
  vscode.workspace.findfiles('folder\subfolder\test.txt', {.history,.vscode,**/node_modules,typings,out});  // return 1 file ok
```

Previously, it doesn't work, with character \ so, **what is the correct character to use now (in Windows)** ?

**Comment by bpasero** [comment]
When using the search viewlet I can use wither `/` or `\` on Windows to specify where to search in, so I am not sure if this is an issue with the way this travels from the API side or a bug in the search service.

**Comment by jrieken** [comment]
@chrmarti [This](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/mainThreadWorkspace.ts#L48) is how it's wired-up to the extension host. Code hasn't changed in a while, unsure if it should now use something else or normalise in some otherway?

**Comment by chrmarti** [comment]
A bug on my side.

**Comment by roblourens** [comment]
@jrieken verified?
