### ISSUE TITLE
Syntax highlighting does not work when project is in folder called Templates

### ISSUE THREAD

**Issue by etekweb** [microsoft/vscode#154282]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1 (Universal)
- OS Version: macOS 12.4

Steps to Reproduce:

1. Create a folder called Templates (full path: /Users/24g/Projects/Templates)
2. In that folder, clone a project repository (full path to project: /Users/24g/Projects/Templates/vue-template)
3. Open that project in VS Code
4. Syntax highlighting does not work. All files are recognized as "Plain Text", even though the file association is set to the correct type.

Workaround: Move project outside of Templates directory (full path to project: /Users/24g/Projects/vue-template). Syntax highlighting then works properly.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by etekweb** [comment]
@bpasero 
I downloaded the latest Insider build and the issue does not occur there.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by etekweb** [comment]
I fixed the issue - it was a bad file type association designed for Django templates.
