### ISSUE TITLE
Editor text not rendering when horizontal scrolling

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#154291]
I'm just scrolling horizontally here with my mouse wheel. The editor text that is scrolled into view sometimes is slow to appear or doesn't actually appear at all until I interact with it.

![Recording 2022-07-06 at 11 02 15](https://user-images.githubusercontent.com/323878/177614343-470d47ab-5c5e-4188-b2c4-cae8473f5b99.gif)

**Comment by roblourens** [comment]
Seems like it doesn't repro in a smaller window

**Comment by alexdima** [comment]
@roblourens Does this reproduce consistently for you? Does it reproduce when launching with `--disable-gpu`?

**Comment by roblourens** [comment]
I can't repro it right now but I have seen it more than once in the past. Will keep watching for it

**Comment by alexdima** [comment]
cc @bpasero I think you mentioned you're aware of Electron struggling sometimes on 4k monitors, maybe you have an issue somewhere for it.

**Comment by bpasero** [comment]
I think we have had 4 kinds of high resolution issues:
* generally slow, lagging
* flickering: https://github.com/microsoft/vscode/issues/47787
* grey squares ("tiles") rendering at random: https://github.com/microsoft/vscode/issues/35527
* parts of the UI not rendering: https://github.com/microsoft/vscode/issues/35527

One experiment would be to see if it reproduces when you run with `--disable-gpu`

@deepak1556 for thoughts

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/129309
