### ISSUE TITLE
VS Code becomes unresponsive after upgrading to 1.68.1

### ISSUE THREAD

**Issue by Harsha-Yalagach** [microsoft/vscode#154236]
Issue Type: <b>Bug</b>

I am running CentOS7 on a VirtualBox VM.

Till recently I was running VS Code 1.63, and it was running perfectly.

Recently, I upgraded to 1.68, and after that VS Code can become sluggish, to the point of being useless.

There is input lag. There is refresh lag of almost 5-8 secs.

I tried runnng with code --disable-features=CalculateNativeWinOcclusion, code --disable-renderer-accessibility, code --disable-features=LayoutNG, but the problem still persists.

Also to be noted is that the CPU usage is negligible, and its **not** like VS Code is hogging the CPU.

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 3.10.0-1160.53.1.el7.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v5 @ 2.90GHz (4 x 2903)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 0, 0|
|Memory (System)|15.51GB (9.33GB free)|
|Process Argv|--disable-renderer-accessibility --crash-reporter-id 4b370e74-df1f-4665-bc19-692dc23451bf|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|i3|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdf:30486550

```

</details>

**Comment by connor4312** [comment]
Please collect a profile using the instructions here: https://github.com/microsoft/vscode/wiki/Performance-Issues#sluggish-ui

**Comment by Harsha-Yalagach** [comment]
[CPU-20220708T162340.cpuprofile.zip](https://github.com/microsoft/vscode/files/9071457/CPU-20220708T162340.cpuprofile.zip)

Uploaded the collected CPU Profile.

**Comment by Harsha-Yalagach** [comment]
Another observation. 

Even the _Developer Tools_ was sluggish. I had to wait 6-8 seconds after every click for the display to update.

**Comment by Harsha-Yalagach** [comment]
It happens
1. with **no files opened**, and 
2. with C/C++ files opened.

When no files are opened, the simple act of clicking on a primary menu-bar item, let's say "Help" menu, is going to take 6-8 secs for the VS Code to display the Help Menu.

I have tested it on 2 different setups.

1. On a VS Code installation with all the plugins and customizations done.

3. On a vanilla VS Code installation with no additional plugins installed.


In both the cases, the simple act of opening the VS Code, **without** any files opened causes this issue.

For the vanilla installation, I removed the VS Code using YUM REMOVE, then deleted all the configurations and intermediate files by deleting the VS Code directories ($HOME/.config/Code and ~/.vscode) as mentioned in https://code.visualstudio.com/docs/setup/uninstall.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by bpasero** [comment]
And what Linux distro is this?

**Comment by Harsha-Yalagach** [comment]
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

The same problem persists in VS Code - Insiders edition.

**Comment by Harsha-Yalagach** [comment]
> And what Linux distro is this?

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

**Comment by bpasero** [comment]
Can you see if it still reproduces when disabling the GPU support in VSCode? You can do that by running VSCode from the command line like this: `code --disable-gpu`

If that helps, you can permanently configure this option via:
* Command Palette search for "Configure Runtime Arguments"
* Set `disable-hardware-acceleration: true`
* Restart

**Comment by Harsha-Yalagach** [comment]
Tried that and it didn't help. I _still face the same issue_ when I run with `code --disable-gpu`.

**Comment by bpasero** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
