### ISSUE TITLE
Support Syncing Settings Profiles

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#154243]
Support Syncing Settings Profiles

CC @Tyriar

**Comment by sandy081** [comment]
@Tyriar Assigning to July to start discussing about the implementation design in server & client.

**Comment by femto-code** [comment]
I am interested: where are the currently available user profiles located?
Maybe letting the user choose the path for `.code-profile`s would be an option?

**Comment by sandy081** [comment]
> where are the currently available user profiles located?

They are located next to where user settings are

> Maybe letting the user choose the path for .code-profiles would be an option?

What is the use case? User can already select where user data can be stored using option `--user-data-dir`
