### ISSUE TITLE
Use wrappedLines for realtive line numbers.

### ISSUE THREAD

**Issue by tobealive** [microsoft/vscode#154298]
Relative line numbers currently get obscured by folded lines. But I'm not quiet sure if that's intended. Therefore this issue opening is yet to be classified as a bug report or as a feature request.

The common mechanic of relative line numbers is to show the distance from the cursors position but without adding folded sections. 

If this shall be implemented, maybe a solution can be as simple as counting "wrappedLines" instead of "lines". Alternatively not using wrappedLines and substracting the folded visualRanges.

A video showing the mentioned issue:

https://user-images.githubusercontent.com/34311583/177620633-692f8cd4-bbad-4b23-894b-452a82c675ee.mp4

---

edit: remove video with sound

**Comment by alexdima** [comment]
Lets' track in #138787
