### ISSUE TITLE
Flaky tests: TernarySearchTree

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154237]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=177004&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=c64bf68a-a40a-513c-efca-4af37a9b3e94

```
The followings tests are failing:
 - Map TernarySearchTree: Cannot read property '1' of undefined #138284 (random)
 - Map TernarySearchTree (PathSegments) - delete_superstr
```

**Comment by chrmarti** [comment]
Another instance: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=177523&view=logs&j=da48166e-7b5a-5795-baad-2da069a28643&t=d41cdc04-e485-5b88-7da2-2df1106b5076

**Comment by bpasero** [comment]
Something is weird:

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/900690/180391854-56f475a9-6fbb-44b9-9d38-25cddb49de68.png">

This looks somewhat like https://github.com/microsoft/vscode/issues/155760#issuecomment-1192288537. Why is there no stack trace on what the assertion is that failed? And why does the task timeout?

**Comment by jrieken** [comment]
@bpasero link to CI run?

**Comment by bpasero** [comment]
@jrieken oh I was just clicking on the first one from this issue: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=177004&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=c64bf68a-a40a-513c-efca-4af37a9b3e94

**Comment by jrieken** [comment]
Oh, super old one without my logging yet

**Comment by jrieken** [comment]
This didn't happen again
