### ISSUE TITLE
Extension host terminates when sandbox enabled

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#154235]
**Steps:**
* you can run out of sources from `main` provided you have setup `.build` folder to pull in our internal builds
* enable sandbox mode via `window.experimental.useSandbox: true`
* restart VSCode

The extension host crashes right on startup:

```
abstractExtensionService.ts:902 Extension host (LocalProcess) terminated unexpectedly. Code: 0, Signal: 
```

We need to better understand why that is, as this would block sandbox work for Linux at least.

I tried running with `--crash-reporter-directory` but did not get any crash dump, which could either mean that this is not a native crash or that crash reporting does not work for utility processes yet?

**Comment by bpasero** [comment]
When running locally with `sandbox: true`, I was able to get the extension host to work properly after commenting out these lines:

https://github.com/microsoft/vscode/blob/2936058b31acc795e5e4bae0040be40134d771d9/src/vs/workbench/api/node/extensionHostProcess.ts#L290-L320

So it seems to be a combination of `native-watchdog` and `process.kill`. I think both of the issues are somewhat independent from each other, they probably cause issues each:
* `process.kill` seems to self-terminate the extension host
* `native-watchdog` turns the extension host process into a `defunct` process

**Comment by alexdima** [comment]
Thanks a lot for figuring this out. The root cause was that `process.pid` is always `1` in a sandboxed renderer and Linux didn't like it when we tried polling for the existance of the `/init` process.

**Comment by deepak1556** [comment]
Sounds good, created https://github.com/microsoft/vscode/issues/155810
