### ISSUE TITLE
Sidebar size keeps increases when clicking on right edge of Explorer panel

### ISSUE THREAD

**Issue by itsakt** [Microsoft/vscode#15421]
- VSCode Version: 1.7.1 stable
- OS Version: Win 10

This only happens if Explorer panel is open. Other panel like Search, Extensions work as expected. But if I keep double clicking the right edge while Explorer is open the width keeps increasing.
Steps to Reproduce:

1. Open Explorer side panel
2. Double click on panel right edge
3. Repeat step 2

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15242
