### ISSUE TITLE
Rant; Search and Replace is Impossible to Use

### ISSUE THREAD

**Issue by PhmAnthony** [microsoft/vscode#154351]
Issue Type: <b>Bug</b>

This is a rant. Can you please just make search and replace work. No gimmicks. No digging through settings trying to find the correct combinations only to discover they don't work in all situations. Search and Replace need to work like the feature did in all pre-Visual Studio 2019 versions.

I am tired of coding in Visual Studio Code then having to use Text Pad to do search and replace operations.

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz (8 x 2100)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.95GB free)|
|Process Argv|A:\\WsPSDev1\\EpicDevOpsService.Wip\\PowerShell.Wip\\_Scratch\\Exchange\\Demo-EwsAttachment_Downloader.ps1 --crash-reporter-id 57131b0d-284a-4698-8f9c-fa9826318080|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
autoit|Dam|1.0.8
xml|Dot|2.5.1
prettier-vscode|esb|9.5.0
vscode-newfile-languagemode|hoo|1.1.0
powershell-universal|iro|3.0.0
vscode-autohotkey-plus-plus|mar|2.8.3
csharp|ms-|1.25.0
data-workspace-vscode|ms-|0.2.1
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.0
sql-database-projects-vscode|ms-|0.17.1
azurecli|ms-|0.5.0
live-server|ms-|0.2.12
powershell|ms-|2022.6.3
vs-keybindings|ms-|0.2.1
team|ms-|1.161.1
vetur|oct|0.35.0
fabric8-analytics|red|0.3.6
java|red|1.8.0
vscode-xml|red|0.21.2022062916
vscode-scheme|sjh|0.4.0
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.42.0
vscode-java-dependency|vsc|0.20.0
vscode-java-pack|vsc|0.24.0
vscode-java-test|vsc|0.35.2
vscode-maven|vsc|0.36.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by PhmAnthony** [comment]
The problem is search and replace is painful in Visual Studio Code. Search and Replace in Visual Studio 2019 was made more difficult when they replaced the search and replace engine and user-interface.  Now both VS2019 and VSC share same interface and it is painful. Search and Replace in Visual Studio 2017 and earlier worked as expected in all situations.

If I select text, I expect the search and replace works in the editor selected characters. If I don’t select text then I expect the search and replace to use the symbol under the cursor in the editor.

Instead, in Visual Studio Code, I get “no results”. The only way to “fix” this is to close the user-interface element and try again. There is no “communication” between the editor and the feature.

I could go on but I really don’t want to troubleshoot something that should just work.

***@***.***

**Comment by roblourens** [comment]
vscode has its own codebase, and there is no relationship between search in vscode and in Visual Studio

> Instead, in Visual Studio Code, I get “no results”. The only way to “fix” this is to close the user-interface element and try again. There is no “communication” between the editor and the feature.

Sorry, I just don't really understand what the issue is

**Comment by PhmAnthony** [comment]
The issue is that the search interface is inconsistent. Per the screenshot I sent, you can see it is not working. This is just one of many cases where the search and replace fails. . The issues are enough to cause me to use a different editor for search and replace.

Both VSCode and VS2019 have the same difficulties because they share the same user-interface design. Do we really need these search widgets in the editor window? I think that is where the problem starts.

As I said in the subject line, this is a rant, rant, rant, rant. 😊

**Comment by gjsjohnmurray** [comment]
@PhmAnthony screenshots sent to GitHub by email do not survive. Please paste into the Web UI.
