### ISSUE TITLE
Git commit messages are handled differently to the command line tools

### ISSUE THREAD

**Issue by Echo-8-ERA** [Microsoft/vscode#15439]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Pro 64-bit

Steps to Reproduce:
1. Set a git template with comments in it
2. Make changes to a project using git
3. Make a commit using VS Code with comments in the message

Expected Behaviour:
1. Git commit template is displayed as is
2. Comment lines are stripped when commit is made

Actual Behaviour:
1. Comments are stripped from the template before being displayed
2. Comment lines are included when commit is made

**Comment by joaomoreno** [comment]
The text in the input box is not supposed to be _verbatim_ to what gets fed into git. Every input in there will go into the message.

**Comment by Echo-8-ERA** [comment]
What's the point of using the template used by the command line tools when you don't follow the conventions set by said tools?

**Comment by joaomoreno** [comment]
Oh. I misread the following part:

> Comment lines are included when commit is made

Sorry, will investigate.

**Comment by Echo-8-ERA** [comment]
No problem. Thanks for looking into it.

**Comment by joaomoreno** [comment]
@Echo-8-ERA I can't reproduce what you meant by 

> Comment lines are included when commit is made

Here's the behaviour I observe:

1. The commit box is pre-populated with the message template, stripped out of all the comments.
2. After commit, the commit message does not include the stripped out comments.

**Comment by Echo-8-ERA** [comment]
This is how the command line tools vs VS Code behaves: https://youtu.be/xM0uwCioBn0

**Comment by joaomoreno** [comment]
This is exactly what I meant by _verbatim_. The text you put in the input box is literally what goes in as a message. It does not get parsed into filtering out comments. Why would you ever want to do that?
