### ISSUE TITLE
When saving a Go file (with either Ctrl-S or from menu) a line near to my cursor position is removed. Does not seem to happen on plain text, just Go, so far.

### ISSUE THREAD

**Issue by theescapers** [Microsoft/vscode#15436]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.49|

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/vscode-go#615
