### ISSUE TITLE
Feature request: Live Preview as a Web Server

### ISSUE THREAD

**Issue by xDarkMan1** [Microsoft/vscode#15431]
- VSCode Version: 1.7.1
- OS Version: Windows 7 64-bit

first: big love to VS_code team.

the feature are missing is (Live Preview as a Web Server) like Brackets Code Editor.

for example look at the video by click [**here**](https://www.youtube.com/watch?v=KsMj3cAZMaU)

I think it could be a good idea.

regards,
xDarkMan.

@aeschli , this is the new issue :smile: 

delete this issue : https://github.com/Microsoft/vscode/issues/15355

**Comment by aeschli** [comment]
For previewing a static HTML page, search for 'html preview' in the marketplace.
https://marketplace.visualstudio.com/items?itemName=hdg.live-html-previewer is an extension that does that.

The reloading dynamic web pages is mostly a external setup: Check out:  https://scotch.io/tutorials/how-to-use-browsersync-for-faster-development.

Please reopen the issue if this is not what you meant.

**Comment by xDarkMan1** [comment]
thank you @aeschli :heart: .

**Comment by aeschli** [comment]
also see #12080 as request for live preview

**Comment by Vuneu** [comment]
@aeschli BrowserSync doesn't allow for live preview highlighting of the elements you're working on, as Brackets does.
