### ISSUE TITLE
Move editor to next/previous group keyboard shortcuts do not work on Ubuntu

### ISSUE THREAD

**Issue by Hurtak** [Microsoft/vscode#15432]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.10

Steps to Reproduce:

- Default move editor to next/previous group keyboard shortcuts do not work on Ubuntu.
- At other computer with Windows, where I use the same vscode settings (I sync them with VS Code Settings Sync plugin), these shortcuts work.
- Broken keyboard shortcuts:
```json
{ "key": "ctrl+alt+right",        "command": "workbench.action.moveEditorToNextGroup" },
{ "key": "ctrl+alt+left",         "command": "workbench.action.moveEditorToPreviousGroup" },
```

- If I rebind to `ctrl+left/right` or `alt+left/right` it works so it is probably something with `ctrl+alt` detection
- I am using default English (US) keyboard layout, switching to Czech layout also doesen't help.
- I tested these other "similar" shortcuts and they work as expected:
```json
{ "key": "ctrl+alt+enter",        "command": "editor.action.replaceAll",
                                     "when": "editorFocus && findWidgetVisible" },
{ "key": "shift+alt+right",       "command": "editor.action.smartSelect.grow",
                                     "when": "editorTextFocus" },
{ "key": "shift+alt+left",        "command": "editor.action.smartSelect.shrink",
                                     "when": "editorTextFocus" },
```

**Comment by bpasero** [comment]
Since these keybindings work for me on my german keyboard on Ubuntu 15, I suspect an issue with the keyboard layout or maybe some other tool that interferes with the keybinding.

**Comment by Hurtak** [comment]
Interesting, once I get home I will try to investigate more. I googled a little and found `--disable-extensions` so that will be a good start. It probably is not keyboard layout issue, I tried switching to English keyboard layout and it did not help.

**Comment by Hurtak** [comment]
I played with Keyboard layout map on Ubuntu and it seems that when I hold ctrl+alt, key presses on cursor keys are not registred for some reason. As a workaround I first press cursor keys and then ctrl+alt, which seems to work but is more clunky.

I am closing this since it is not related to VS Code but seems to be more of an Ubuntu / my local setup issue.
