### ISSUE TITLE
Key highlight links in GitHub release notes are incorrect

### ISSUE THREAD

**Issue by cj81499** [microsoft/vscode#154394]
Does this issue occur when all extensions are disabled?: n/a

- VS Code Version: 1.69
- OS Version: n/a

Steps to Reproduce:

1. Visit https://github.com/microsoft/vscode/releases/tag/1.69.0
2. Observe that "[3-way merge editor](https://code.visualstudio.com/updates/v1_68#3-way-merge-editor)" links to https://code.visualstudio.com/updates/v1_68#3-way-merge-editor, rather than https://code.visualstudio.com/updates/v1_69#_3-way-merge-editor (wrong version # and missing `_` in header id).

**Comment by lszomoru** [comment]
@gregvanl could you please fix the link? Thank you!

**Comment by lramos15** [comment]
I noticed this before seeing this issue and went ahead and fixed the links

**Comment by lramos15** [comment]
> @lszomoru @lramos15 I'm not sure how this section of the tag is created. Is it a manual cut, paste, and URL fixup from the release notes? Or is this auto generated?

It's manually copied and pasted from the top section of the release note in the vscode-docs repo. Not sure how the links were incorrect, maybe it was copy and pasted before they were updated

**Comment by gregvanl** [comment]
OK, since the release notes highlight links are relative to the page, someone must have put the wrong prefix (https://code.visualstudio.com/updates/v1_68) in front to create absolute links. They also left out the underscore for the website header link format.
Is this written up somewhere for the Endgame Champion?

**Comment by lramos15** [comment]
> Is this written up somewhere for the Endgame Champion?

The endgame template includes this 
<img width="835" alt="image" src="https://user-images.githubusercontent.com/4544166/178031448-c1ad88fd-0ec6-4ee8-8ef2-df27284463e3.png">
