### ISSUE TITLE
Scaling mismatch

### ISSUE THREAD

**Issue by contracourse** [microsoft/vscode#154391]
Issue Type: <b>Bug</b>

I'm using a high resolution laptop and since you made the big menu bar, the sub menu is all to small.
When I click for example on the big help, it shows the dropdown option at a much smaller scale

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:58.525Z)
OS version: Windows_NT ia32 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (1.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (3 x 1799)|
|Memory (System)|1.88GB (1.12GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
material-icon-theme|PKi|4.19.0
rewrap|stk|1.16.3
latex-support|tor|3.10.0
latex-workshop|Jam|8.27.2
vscode-edit-csv|jan|0.7.1
rainbow-csv|mec|2.4.0
vscode-docker|ms-|1.22.0
python|ms-|2022.8.1
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1001901851
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
r|REd|2.5.0

(1 theme extensions excluded)

</details>

**Comment by sbatten** [comment]
Is the scaling of the menu matching context menus? for example, right click in a file?

**Comment by bitrate16** [comment]
VSCODE 1.69.1 / 2022-07.12T08:21:24:514Z on windows 10
Menu bar & menu itself scale does not change causing excess on-screen space usage.

Before update:
![Screenshot (1460)](https://user-images.githubusercontent.com/9000114/179361204-ae3ff265-c5b7-4539-aa40-b15c05a5d2a9.png)

After update:
![Screenshot (1461)](https://user-images.githubusercontent.com/9000114/179361206-59c6f1c5-2c31-41f0-81b2-28baa8db9403.png)

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/151803
