### ISSUE TITLE
Shell Integration wrong exit code if run same command for multiple times

### ISSUE THREAD

**Issue by FindDefinition** [microsoft/vscode#154343]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.68.1
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. enable shell integration in bash
2. run ```python -c $'import random\nif (random.randint(0, 1000) % 2 == 0):\n  raise NotImplementedError \n'``` for multiple times
![image](https://user-images.githubusercontent.com/73811981/177729325-f2963405-2391-4b7a-9e72-47589be79945.png)

I believe this is caused by [this line](https://github.com/microsoft/vscode/blob/1.68.1/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L70). bash history index won't be increased if we run same command.

**Comment by Tyriar** [comment]
Very observant 😅 

This is tracked in https://github.com/microsoft/vscode/issues/143766, I'll see if we can get this covered for v1.70

/duplicate
