### ISSUE TITLE
Add context key for run recent command open

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#154306]
The views picker (ctrl+q) lets you hit ctrl+q again to go down the list:

```json
{ "key": "ctrl+q",                "command": "workbench.action.quickOpenNavigateNextInViewPicker",
                                     "when": "inQuickOpen && inViewsPicker" },
```

This is behavior we could copy in the run recent command to make it act even more like ctrl+r in the shell

**Comment by sandy081** [comment]
Please provide steps to verify

**Comment by Tyriar** [comment]
This is covered by a tpi
