### ISSUE TITLE
How to add the WesBos vscode-theme-cobalt2

### ISSUE THREAD

**Issue by J-S-Thomas** [Microsoft/vscode#15434]
I'm trying to add the wesbos cobalt2 theme to vscode which is different from the vscode cobalt2 extension placed in the marketplace. can somebody map out some definitive steps to doing so?

**Comment by aeschli** [comment]
Check out https://code.visualstudio.com/docs/customization/themes.

In general, for questions better use http://stackoverflow.com/questions/tagged/vscode.
That way more users can help and benefit from an answer.
