### ISSUE TITLE
Support semi-circle powerline symbols

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#154324]
@sbatten fixed in xterm.js: https://github.com/xtermjs/xterm.js/pull/3891

Need to update xterm to pull it in:

![image](https://user-images.githubusercontent.com/2193314/177672234-85039a8c-172f-4882-b15d-9c09813a37c3.png)

**Comment by rzhao271** [comment]
What's a way to verify this issue on Windows?

**Comment by sbatten** [comment]
With Powershell on Windows in the integrated terminal without a powerline font enabled:

```
Write-Host "`u{e0b4} `u{e0b5} `u{e0b6} `u{e0b7}"
```

**Comment by rzhao271** [comment]
They seem a bit clipped to me:
![Screenshot showing the semi-circle powerline symbols are clipped a bit on the right side](https://user-images.githubusercontent.com/7199958/181309524-dd07c9ad-043f-4c75-830f-7b294921b0d1.PNG)

**Comment by Tyriar** [comment]
@rzhao271 tracked in https://github.com/microsoft/vscode/issues/156988
