### ISSUE TITLE
Add a setting to have VS Code always on top of other windows

### ISSUE THREAD

**Issue by mbennette68** [Microsoft/vscode#15430]
- VSCode Version: 1.7.1
- OS Version: Win 10 64 Bit

Sometimes I need the code editor to be on top of other windows but can't seem to find an extension that will allow the editor window to stay on top.

I think it could be a good idea to add an Always On Top Feature to VSC any version.

**Comment by xDarkMan1** [comment]
My Opinion: Not good enough.

kind regards,
xDarkMan. :smile:

**Comment by mbennette68** [comment]
It seems that most Windows-based apps lack this feature, of Windows Always On Top.  I know you don't like the idea, but it's universal in Linux, which I also use, but also like Windows.  As Microsoft does not appear to ever be willing to add this feature as a default to their GUI, I figured this would be another rout.  I also use Sublime Text, on occasions and Cmder.exe (based on ConEmu) console. 
[Cmder with Sublime Text Integration](https://github.com/cmderdev/cmder/wiki/Seamless-Sublime-Text-3-Integration)
Cmder has this, Windows On Top) feature, transparency, and allows one to integrate an app (e.g. sublime, VSC) into a second split console.  I normally would prefer to use Cmder with an embedded app, but the new console that is generated is added to the bottom or right side of the main console window where as I'd prefer the editor to be on top and the console at the bottom hence my reason for the Feature Request.

I, do, appreciate the feedback :)

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
