### ISSUE TITLE
 "Native hovers":The tool tip for buttons "join and start collaboration " are not hoverable 

### ISSUE THREAD

**Issue by fsteffi** [microsoft/vscode#154359]
GitHubTags: #A11yMAS;#A11yTCS;#A11ySev2;#A11y_VSCode;#CAITestPass_May2020;#FTP;#DesktopApp;#WCAG1.4.13;#Visual Studio Code;#Hover;#Win32;#A11yWAG2.1;#LinkedBug;#Linked:Bug1214910;

## Environment Details:​

Application Name:  Visual Studio Live Share
Application version: 1.49.0
Windows Version: Win10 

## Repro Steps:

1.Launch VSCode
2.  Navigate to the “sign-in” button using tab .
3.  Tab to share button and use enter key.
4.  Tan to Session Details dropdown
5. Hover over the buttons "join and start collaboration"

## Actual:
On hovering over the buttons "join and start collaboration" the tooltip get displayed but on moving the pointer to the tooltip they get dismissed.

### Same issue observed in the following screens:

1. no collaboration Planned Sessions
2. no collaboration Contacts
3. with collaboration Session Details
4. with collaboration  Contacts
5. with collaboration help
6. More Info Tab
7. Audio Call-End Audio Call
8. Contacts-Change Your Own availability Status
9. Contacts-Collaborate with  a recent contact
10. Contacts-Collaborate with suggested contact

## Expected:
The pointer should move to the tooltip without the tooltip getting dismissed.

## User Impact:
Keyboard users that zoom the screen to view data will not get a chance to view the tooltip information if it dismisses before moving to it

**Comment by fsteffi** [comment]
opened as comment from primary bughttps://devdiv.visualstudio.com/DevDiv/_workitems/edit/1214910

So to summarize :  VS Code team says,  eventually, the fix will come to native hovers in long term but for now we need to open a bug for native hovers. I am going to resolve this as external. Please file a bug on VS Code side so it will show up on their s360 and please add a note that this is for "Native hovers"

**Comment by TylerLeonhardt** [comment]
@Tyriar  the 2nd comment talks about hovers. My guess is that this issue was moved from LiveShare to us.
