### ISSUE TITLE
Lightning Bulb icon for QuickFix type code actions spilling over to next line.

### ISSUE THREAD

**Issue by nikhil-dubey** [microsoft/vscode#154346]
In case where quick fixes are available for any location and the line is starting from column 1 without any leading whitespace characters, the quick fix icon is shown in next or previous line. 
Example 
![image](https://user-images.githubusercontent.com/7306663/177745792-634f575b-2c13-4ee2-95c0-2552303ba536.png)

Expected : it should show up in same line as the requested location.

**Comment by mjbvz** [comment]
This look by-design

We try to avoid covering up the line with the cursor on it as you are likely reading it or editing it. This means the lightbulb may show above or below the current line if there is not space for it
