### ISSUE TITLE
html emmet suggestion not automatically display

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#154375]
Does this issue occur when all extensions are disabled?: Yes

- MacOS: 12.4
- VSCode: 1.69.0-insider

I need manulay trigger the suggestion:

https://user-images.githubusercontent.com/41773861/177828482-15311df8-4ce6-419a-a8d9-9430c3446fcb.mov

**Comment by jjchandru** [comment]
The * emmet abbreviation as well is not working. For example, after typing div*3, the drop down is not appearing and we have to force the appearance of drop down by pressing Ctrl+Space, earlier the drop down is used to appear by default.

**Comment by ConanGoodwin** [comment]
Same here, but

Versão: 1.69.0
OS: Linux x64 5.4.0-121-generic

li*3 not work too

only li + tab, ok
html + tab, ok

but ! + tab or p*3 + tab not

**Comment by IbrahimDarwish** [comment]
! + tab also isnt working with me
version: 1.69.0
OS. Windows 11

**Comment by GabrielFTeles** [comment]
![image](https://user-images.githubusercontent.com/101151753/178080994-adfda0a3-9cca-49a8-9da6-e559eab96b0b.png)

You need to check this option or put `"emmet.triggerExpansionOnTab": true` in settings.json to use the  emmet abbreviation pressing TAB. I realized this ones what is not working: **!**, **lorem**, **>**, and *****. 
Examples of use: ul>li, li*3, ul>li*3.

None of them shows the preview of the emmet, and you can't use them pressing TAB without enabling the option that I sayed above.

**Comment by HerbOwen** [comment]
! tab not working for skeleton. 
another example:
li*5 not working

**Comment by developermamoon** [comment]
isn't there any solution to solve this problem ?

**Comment by HerbOwen** [comment]
Went settings>Emmet> Show Abbreviation Suggestions (Turn on through checkmark)

worked.

**Comment by HAMZAIMRAN5080** [comment]
Yes, I am facing this issue too since the latest update.

Somehow the solution I have got is: You can check the box “Emmet: Use Inline Completions” In settings by typing “emmet” in the setting’s search. You can see the suggestion now and choose it by pressing the tab.

This is the solution I have got till now but hoping that we could have the previous version back.

**Comment by naveenkrdy** [comment]
Needed to enable these two settings to fix it.
 
```json
 "emmet.triggerExpansionOnTab": true,
 "emmet.useInlineCompletions": true
```

**Comment by jenyach87** [comment]
thanks

**Comment by block-hunter** [comment]
I don't think this is a bug. they closed this shortcut. 👎🏻

**Comment by gjsjohnmurray** [comment]
@rzhao271 this probably deserves to be a candidate for June Recovery 1, seeing how many people have logged duplicates of it.

**Comment by rzhao271** [comment]
The fix will be available in tomorrow's Insiders.
Verification steps:
1. Create a new HTML file
2. Type `!`
3. Completions such as `!` and `!!!` should appear.

**Comment by UczenBlood** [comment]
emmet still not working

**Comment by gjsjohnmurray** [comment]
> emmet still not working

@UczenBlood unless you are using Insiders you will need to wait for 1.69.2 to release.

**Comment by PrakharGupta36** [comment]
What's your font

**Comment by HAMZAIMRAN5080** [comment]
I have news that with the latest update of vs code 1.69.2 the emmet problem is now resolved.
