### ISSUE TITLE
`previous session` commands are still shown when `enablePersistentSessions` is disabled

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#154373]
<img width="714" alt="Screen Shot 2022-07-07 at 12 47 09 PM" src="https://user-images.githubusercontent.com/29464607/177827488-18a51839-41f7-42d2-9892-bc29abe7e8af.png">

**Comment by Tyriar** [comment]
This is by design, persistent sessions is about reconnect and process revive, previous session is controlled by `terminal.integrated.shellIntegration.history` and also remains when shell integration is disabled

**Comment by meganrogge** [comment]
Ok makes sense 👍🏼
