### ISSUE TITLE
There are lots of errors about less style in .vue 

### ISSUE THREAD

**Issue by ideal123** [Microsoft/vscode#15438]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|beautify|HookyQR|0.5.4|
|weex|jaylinwang|0.4.0|
|docthis|joelday|0.3.5|
|ejs-language-support|QassimFarid|0.0.1|
|vue|seanwash|0.4.2|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by aeschli** [comment]
You have to file this against the 'vue' extension that you use.

**Comment by ripper234** [comment]
Hmm, I don't have any vue extensions installed, and I still get vue highlighting (with LESS errors).
None of my extensions do anything related to syntax highlighting.

![image](https://cloud.githubusercontent.com/assets/172282/23116042/11ece45a-f751-11e6-9d43-9dfd7483e7b8.png)

```
abusaidm.html-snippets-0.1.0
lefragnani.project-manager-0.13.2
nseki.vscode-color-0.2.3
hristian-kohler.path-intellisense-1.2.0
mstead.jsrefactor-0.5.3
avidAnson.vscode-markdownlint-0.6.2
onjayamanne.githistory-0.1.5
otJoshJohnson.xml-1.7.0
g2.tslint-0.8.1
g2.vscode-npm-script-0.1.8
ormulahendry.code-runner-0.6.9
yu1kn.annotator-0.10.1
eanmcbreen.Spell-0.9.1
han.code-settings-sync-2.4.3
ilicvane.es-quotes-0.2.4
cwhitehead.bootstrap-3-snippets-0.0.9
abikos.JavaScriptSnippets-1.4.0
Zignd.html-css-class-completion-1.0.3
```

**Comment by ripper234** [comment]
P.S the same syntax highlighting works when I ran `code --disable-extensions`

**Comment by aeschli** [comment]
The problem is that vue files are not valid HTML files.
I'll remove the vue association from html. We recommend the [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) extension.

**Comment by ripper234** [comment]
I wouldn't remove the vue association - as it is, the default syntax highlighting works pretty damn well. For me, it's just LESS that's giving it issues.

In fact, while vueter fixes the highlighting, it breaks auto formatting the document for me for the ```<style>``` section.
