### ISSUE TITLE
Timeline contribution point

### ISSUE THREAD

**Issue by gar1t** [microsoft/vscode#154362]
This covers topics in #84297.

I'd like to extend the information displayed in the timeline beyond local changes and version control commits. In my case, our extension generated machine learning experiments for a project. I'd like to include a reference to each experiment that contains the active (or pinned) file. This would let the user easily compare an experiment version of a file to the current version.

The timeline for a file is already generalized to support local and version control events. IMO it ought to be opened to extensions to add value here. E.g. data versioning is now a topic, with various systems tracking changes to data set sources outside of version control (these files are often quite large and are not stored in git/etc but still need to be version controlled).

**Comment by gjsjohnmurray** [comment]
Proposed API is already available at https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.timeline.d.ts

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/84297
