### ISSUE TITLE
vscode bad rendering after update to 1.69.0

### ISSUE THREAD

**Issue by farbodVand** [microsoft/vscode#154387]
I updated VScode today, first time opening the editor I faced this rendering.
Does this issue occur when all extensions are disabled?: Yes

Version: 1.69.0
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:41.511Z (13 hrs ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

Steps to Reproduce:

1. Just install the new version on Intel mac
2. I disabled all extensions and JSON configurations but issue persists.

https://user-images.githubusercontent.com/13926209/177847827-d12c8853-fcc8-48ff-bb0c-dc38fe1bd370.mov

**Comment by ClaireDuSoleil** [comment]
I am also seeing this but if I launch with --disable-gpu it works again.

**Comment by rdong25** [comment]
I had same issue 
<img width="2073" alt="image" src="https://user-images.githubusercontent.com/39985006/177853921-823083d1-b9bf-4ef2-967e-ed51597c4d19.png">

**Comment by heshuimu** [comment]
Can confirm this also happens on an M1 Mac (M1 Max MacBook Pro). I rolled back to 1.68 because of this visual inconsistency.

**Comment by tillig** [comment]
Verified - I see the same thing and `--disable-gpu` does fix the weird rendering issue. Intel MacBook Pro, macOS 12.4.

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/152816 

cc @deepak1556
