### ISSUE TITLE
Reload problem with `previewHtml` 

### ISSUE THREAD

**Issue by tulayang** [Microsoft/vscode#15437]
- VSCode Version:1.0.3
- OS Version: ubuntu 14.04

I'm writting some visualization capabilities via `vscode.previewHtml`. I found that my page will be reloaded when toggling editors. Here is a gif which recording the process:

![vscode.previewHtml](https://github.com/tulayang/tulayang.github.io/blob/master/qs/recode.gif?raw=true)

How can I disable it?

**Comment by jrieken** [comment]
You cannot. The `previewHtml` isn't designed to build custom UI but to render a document. When not visible (like changing tabs) we will dispose the state.

**Comment by tulayang** [comment]
@jrieken 

Is there other way to write HTML document?

**Comment by jrieken** [comment]
No, we don't have an UI-extensibility story
