### ISSUE TITLE
Extension Issue - It is not taking any value automatically.

### ISSUE THREAD

**Issue by agrawalrajat310** [microsoft/vscode#154416]
- Issue Type: `Bug`
- Extension Name: `html-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.22000`
- VS Code version: `1.69.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by aeschli** [comment]
Please add more details with steps to reproduce...

**Comment by agrawalrajat310** [comment]
Hello Sir, 

When we create .html file and start writing in the file, then I first press the "Shift" + "!" + "Enter" -> to get the basic DOCTYPE HTML layout of the html page and inside this I write all my code. But from last update. what I did both of vs code and git bash, the VS Code is giving no prompt while I press the same what I was pressing after creating the new html file i.e. "Shift" + "!" + "Enter".

Now, I have to press the "Shift" + "!" + "Ctrl" + "Space" + "Enter" -> to get the layout what I am getting earlier.

This is the layout for what I am talking about :- 

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
<style></style>
</head>
<body>
  <-- My code here -->
</body>
</html>

I have just now confirmed this with my two friends just now. Now, they are also facing the same issue. I tried all methods from past 2 days doing all google search, tried installing previous versions, installing again the vs code fully again and also the extensions what I am having but bad luck till now.

This is called as "Emmet Abbreviation".

I don't know what to do now. But if you understand my query. Please resolve it. 
I think so that this is a little bug and you can correct it.

If any other information is required, I am ready to help.


Regards
RAJAT AGRAWAL.

**Comment by agrawalrajat310** [comment]
Can, I know will it be correct to back as normal earlier one or remains same as of now ? 
Because some other "Emmet Abbreviation" are also not working.


Regards
Rajat Agrawal

**Comment by aeschli** [comment]
@agrawalrajat310 You can see in https://github.com/microsoft/vscode/issues/154375 that a fix has been released for June 2022 Recovery 2, which us coming out soon.
If you see additional bugs, please file new issues with steps to reproduce.

**Comment by agrawalrajat310** [comment]
Thank you @aeschli for hearing out our issues and resolving them.
Thank You.
