### ISSUE TITLE
After updating to the latest version, my terminal and vscode background are with a bug

### ISSUE THREAD

**Issue by lucasfcm9** [microsoft/vscode#154406]
Issue type: Bug
 
After updating to the latest version, my vscode is weird. Look this:

<img width="1680" alt="Screen Shot 2022-07-07 at 6 07 34 PM" src="https://user-images.githubusercontent.com/40740008/177871559-1a9d019d-16c4-4f14-816c-3f9b4470bfe1.png">

<img width="1680" alt="Screen Shot 2022-07-07 at 6 07 50 PM" src="https://user-images.githubusercontent.com/40740008/177871588-cb0a5ab5-2d47-495d-b0b4-da2fec307828.png">

My terminal and the background of my vscode are with some spots.

Settings of my laptop:
- MacBook Pro 2020
- Apple chip M1

**Comment by Igorgro** [comment]
Dulplicate of https://github.com/microsoft/vscode/issues/152816
