### ISSUE TITLE
Question: How to Enable These Git Features

### ISSUE THREAD

**Issue by edwin-egalite** [microsoft/vscode#154440]
Sorry if this is off topic. May I know how to enable those Git features in below screenshot?

![image](https://user-images.githubusercontent.com/10771300/177909610-f06526db-4603-49a8-b82a-820313553b56.png)

Thank you.

**Comment by hirishu10** [comment]
HI, @edwin-egalite please configure your GitHub account to use the same feature.
Read this to understand more https://code.visualstudio.com/docs/editor/github.
Regards,

**Comment by edwin-egalite** [comment]
Thank you so much for the answer.

**Comment by hirishu10** [comment]
You're welcome
Happy Coding :)

**Comment by hirishu10** [comment]
> Thank you so much for the answer.

You're welcome
Happy Coding :)
