### ISSUE TITLE
I can't sync mine extensions from vscode stable(1.69.0) to insiders(1.69.0-insider)

### ISSUE THREAD

**Issue by wegi8** [microsoft/vscode#154441]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.0
- OS Version: Windows 11 Insider Preview Build 25151.rs_prerelease.220625-1835

Steps to Reproduce:

1.Emmmmm I just saw that some new features have been updated in the version of `insider` in vscode changelog. I want to download `insider` to experience it, and find that the plug-ins and some configurations in my vscode stable have not been synchronized. It's strange.

I can synchronize them manually, but as a preview, and I have logged in to my account, I think it should be synchronized.

**Comment by sandy081** [comment]
Please check this to sync stable with insiders - https://code.visualstudio.com/docs/editor/settings-sync#_syncing-stable-versus-insiders

**Comment by wegi8** [comment]
@sandy081 OK, Thank you!!! it's worked
