### ISSUE TITLE
 Why do not the path IntelliSense features built into it?

### ISSUE THREAD

**Issue by crper** [Microsoft/vscode#15443]
- VSCode Version: 1.7.1
- OS Version: win 10 redstone 

Steps to Reproduce:

1.  Why do not the path IntelliSense features built into it?
We need the help of plug-ins  Path Intellisense;

Thanks

**Comment by aeschli** [comment]
@crper For what language is this? I ask because it's up to each language to implement intellisense.

**Comment by mjbvz** [comment]
Closing as we need more info here.

1.8 added path intellisense for JS imports. Extensions can  provides much more functionality if you need it
