### ISSUE TITLE
Profiles: Support transient profiles

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#154460]
We could introduce the concept of a transient profile which gets automatically deleted once the last window which uses it is closed.

Additionally, combined with https://github.com/microsoft/vscode/issues/151301, we could have a CLI way to start VS Code on a transient profile.

cc @weinand

**Comment by weinand** [comment]
@sandy081 
I've tried the `--profile-transient` CLI for extension debugging, but that had no effect.
But creating an empty profile "mock" and then using `--profile=mock` in the launch config works great.

(Yes, I've turned on the "profile preview" flag and I'm running latest out of source)

Here is the launch config that didn't work for me:
```json
		{
			"name": "Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--profile-transient",
				"--extensionDevelopmentPath=${workspaceFolder}",
				"${workspaceFolder}/sampleWorkspace"
			],
			"outFiles": [
				"${workspaceFolder}/dist/**/*.js"
			],
			"preLaunchTask": "npm: watch"
		},
```

**Comment by weinand** [comment]
Using the `--profile-transient` flag in extension debugging works fine as long as a workspace folder is specified in `args`.
If no workspace folder is specified `--profile-transient` is silently ignored.
