### ISSUE TITLE
Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 9, signal null)

### ISSUE THREAD

**Issue by kirvedx** [microsoft/vscode#154410]
Search indicated that this specific issue has not been reported - a related one that does occur because of timeout does exist, is well known, and as such I'm creating a new issue as [documentation suggests](https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails)

![image](https://user-images.githubusercontent.com/6693085/177852652-fb224234-2d49-47ff-bcc0-3ca61acaec5f.png)

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/6693085/177852403-8241acea-75b5-4f1d-9143-0c0cdf04e0e9.png)

- VS Code Version:
  ![image](https://user-images.githubusercontent.com/6693085/177879046-210e7dbe-c522-45c9-a48d-1ba1ee912ec7.png)

- OS Version:
  [![asciicast](https://asciinema.org/a/kdK8my0uerQJMd0nKgIsgtaZe.svg)](https://asciinema.org/a/kdK8my0uerQJMd0nKgIsgtaZe)

Steps to Reproduce:

1. Using the following `~/.bashrc`, add the last export for resolving some issues with `node v18` (i.e. `NODE_OPTIONS=--no-experimental-fetching`
  ```bash
  rik@devrikx:~$ cat ~/.bashrc
# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
#[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    #alias grep='grep --color=auto'
    #alias fgrep='fgrep --color=auto'
    #alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
#alias ll='ls -l'
#alias la='ls -A'
#alias l='ls -CF'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Add the GPG key to our profile
export GPG_TTY=$(tty)

# Modify the path variable to contain paths to executables we'd like
# added

# Set the npm global path (prepend it so its found first!)
NPM_PACKAGES="${HOME}/.npm-global"

export PATH=$NPM_PACKAGES/bin:$PATH

# Preserve MANPATH if you already defined it somewhere in your config.
# Otherwise, fall back to `manpath` so we can inherit from `/etc/manpath`.
export MANPATH="${MANPATH-$(manpath)}:$NPM_PACKAGES/share/man"

# Set the android-studio binaries path
export PATH=$PATH:/opt/android-studio-canary/bin
export PATH=$PATH:/opt/android-studio/bin

# Set the android-studio platform tools path
export PATH=$PATH:~/Android/Sdk/platform-tools
#export PATH=$PATH:~/Android/Sdk/platform-tools


# Set the android-studio tools path (don't really need these from terminal)
# export PATH=$PATH:~/Android/Sdk/tools/bin

# Set the GOPATH
export PATH=$PATH:/usr/local/go/bin
export PATH=$PATH:/home/rik/go/bin


# Fix some issues with Node.js v18 while we wait for resolution:
# (Added 6-2022, after there was an error trying to build @kwaeri/filesystem module)
export NODE_OPTIONS=--no-experimental-fetch
  ```
2. Start Visual Studio Code in Gnome DE, leveraging the gui icon (either from panel or favorites):
`/usr/share/code/code --unity-launch %F `

## Useful Information:

The only other thing I can think of, is that at one point in time I did take some steps to try and change the terminal that was opened by opening terminal to a directory from nautilus (file-roller), from gnome-terminal to terminology.

None of the steps did manage to make that happen:

1. Using `update-alternatives`:
![image](https://user-images.githubusercontent.com/6693085/177881102-de628ee2-0e31-452d-9ca9-b3a8484a5fa1.png)

2. Using dconf configuration:
```bash
gsettings set org.gnome.desktop.default-applications.terminal exec /usr/bin/terminology
gsettings set org.gnome.desktop.default-applications.terminal exec-arg "--current-directory"
```

3. Using `nautilus-configuration-tool`

4. Using `filemanager-actions`

However, none worked - so I've put (1) back to `gnome-terminal`, undone the steps in (2), and uninstalled both (3) and (4).

The issue has started since last update after I updated Node.js from 16 (LTS) to 18, and added the `NODE_OPTIONS` fix (`--no-experimental-fetch`).

#### System Information:

CPUs | Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 1300)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: disabled_off opengl: enabled_on rasterization: disabled_software raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 0, 0, 0
Memory (System) | 62.72GB (48.43GB free)
Process Argv | --unity-launch
Screen Reader | no
VM | 0%

#### Enabled Extensions

Extension | Author (truncated) | Version
-- | -- | --
texinfo | cis | 0.2.4
doxdocgen | csc | 1.4.0
dart-code | Dar | 3.44.0
flutter | Dar | 3.44.0
vscode-eslint | dba | 2.2.6
githistory | don | 0.6.19
gitlens | eam | 12.1.1
vscode-html-css | ecm | 1.13.0
vscode-npm-script | eg2 | 0.3.28
vsc-material-theme | Equ | 33.2.0
vsc-material-theme-icons | equ | 1.2.2
php-intellisense | fel | 2.3.14
code-runner | for | 0.11.8
kotlin | fwc | 0.2.26
gitlab-workflow | Git | 3.47.2
go | gol | 0.34.1
beautify | Hoo | 1.5.0
minify | Hoo | 0.4.3
better-cpp-syntax | jef | 1.15.19
vscode-peacock | joh | 4.0.1
cmake-language-support-vscode | jos | 0.0.4
chat | kar | 0.35.0
sftp | lix | 1.12.10
autoconf | mae | 0.1.0
Kotlin | mat | 1.7.1
vscode-scss | mrm | 0.10.0
language-gettext | mro | 0.2.0
vscode-docker | ms- | 1.22.0
vscode-language-pack-ja | MS- | 1.68.6150906
vscode-dotnet-runtime | ms- | 1.5.0
vscode-kubernetes-tools | ms- | 1.3.10
python | ms- | 2022.8.1
vscode-pylance | ms- | 2022.7.20
jupyter | ms- | 2022.5.1001601848
jupyter-keymap | ms- | 1.0.0
jupyter-renderers | ms- | 1.0.8
remote-containers | ms- | 0.238.3
remote-ssh | ms- | 0.82.1
remote-ssh-edit | ms- | 0.80.0
remote-wsl | ms- | 0.66.3
vscode-remote-extensionpack | ms- | 0.21.0
azure-account | ms- | 0.11.0
cmake-tools | ms- | 1.11.26
cpptools | ms- | 1.11.0
cpptools-extension-pack | ms- | 1.2.0
typescript-javascript-grammar | ms- | 0.0.55
vscode-typescript-tslint-plugin | ms- | 1.3.4
vsliveshare | ms- | 1.0.5641
vsliveshare-audio | ms- | 0.1.91
vsliveshare-pack | ms- | 0.4.0
debugger-for-chrome | msj | 4.13.0
debugger-for-edge | msj | 1.0.15
vscode-react-native | msj | 1.9.2
gradle-language | nac | 0.2.3
vscode-jest | Ort | 4.6.0
vscode-html-scss | P-d | 0.0.42
material-icon-theme | PKi | 4.19.0
java | red | 1.8.0
vscode-commons | red | 0.0.6
vscode-xml | red | 0.21.0
vscode-yaml | red | 1.8.0
ms-teams-vscode-extension | Tea | 4.0.1
cmake | twx | 0.0.17
vscodeintellicode | Vis | 1.2.22
vscode-arduino | vsc | 0.4.12
vscode-java-debug | vsc | 0.42.0
vscode-java-dependency | vsc | 0.20.0
vscode-java-pack | vsc | 0.24.0
vscode-java-test | vsc | 0.35.2
vscode-maven | vsc | 0.36.0
vscode-icons | vsc | 11.12.0
browserslist | web | 1.1.0
php-debug | xde | 1.27.0
php-pack | xde | 1.0.3
php-intellisense | zob | 1.0.11

<span style="color: rgb(238, 255, 255); font-family: system-ui, Ubuntu, &quot;Droid Sans&quot;, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(43, 43, 43); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(2 theme extensions excluded)</span>

#### A/B Experiment Info

No current experiments.

**Comment by Tyriar** [comment]
Looks like exit code 9 is a `EBADF` (bad file descriptor). Here's what is actually called on startup to fetch the shell environment:

https://github.com/microsoft/vscode/blob/96f310e3ebee05189f03e974713ec1c666b15b6a/src/vs/platform/shell/node/shellEnv.ts#L126-L151

Which runs something close to:

```sh
$SHELL -ilc "'<vscode binary path>' --ms-enable-electron-run-as-node -p 'JSON.stringify(process.env)'"
```

Does removing the `--no-experimental-fetch` thing fix it? Changes to NODE_OPTIONS will affect the command above.

**Comment by kirvedx** [comment]
It does fix it, but that's unfortunate because on Node v18 (at least for now) several modules aren't building when leveraging the latest module versions - with the following error:

![image](https://user-images.githubusercontent.com/6693085/178098796-78576ad0-1824-43a2-92d0-e0a0b2bd055e.png)

Which requires me to `export NODE_OPTIONS=--no-experimental-fetch` with a follow-up `unset NODE_OPTIONS` to resolve issues for a successful build.

I tried to change my `~/.bashrc` entry to:

```bash
# ...
# Set no experimental fetching for resolving node v18 issues:
export NODE_OPTIONS="$NODE_OPTIONS --no-experimental-fetch"
```

So as not to unset options that vscode might be setting, but that did not resolve the error.  Is that not going to be something that can be avoided?

**Comment by kirvedx** [comment]
Though the above also seems like a very odd behavior, considering that according to the [official docs](https://nodejs.org/api/cli.html):

> Options from the command line take precedence over options passed through the NODE_OPTIONS environment variable.

**Comment by Tyriar** [comment]
This is just how `NODE_OPTIONS` works, it overrides options for any node instance that gets run, and that includes VS Code. The approach I'd take here is to set `NODE_OPTIONS` conditionally depending on what the purpose of the shell is being run is. For example you could do this:

```sh
if [ "$TERM_PROGRAM" == "vscode" ]; then
  export NODE_OPTIONS="$NODE_OPTIONS --no-experimental-fetch"
fi
```

That will set it only when running in VS Code's terminal, this won't work for other terminals of course but it should fix the problem of VS Code's environment being tampered with.
