### ISSUE TITLE
Refactor with preview isn't working for full file.

### ISSUE THREAD

**Issue by abhijitchikane** [microsoft/vscode#154451]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. I try to refactor the entire file with newly added "Refactor with preview..." command but it is giving me the indivisual line context menu to refactor as shown in below image
![image](https://user-images.githubusercontent.com/50770619/177920536-d25e73f2-8f92-4c16-9875-19de0c491ab5.png)

**Comment by justschen** [comment]
@abhijitchikane I can't seem to be able to reproduce. Are you highlighting the entire file?

**Comment by abhijitchikane** [comment]
Do i have to select entire file explicitly?
I think if thats the case vscode must consider the whole file if nothing is selected.

**Comment by justschen** [comment]
If nothing is selected, no refactorings/code actions will be available. Refactorings (using `Ctrl + Shift + R` or with `Refactoring with preview...` will only work when something is highlighted or if the cursor is on a valid variable. 

This is a bit different then with Quick Fixes, where if your cursor or typing location is on some variable/function/etc, it will have some code actions that can be triggered on it.
