### ISSUE TITLE
Terminal name and split/delete icons shouldn't show when hideCondition=never.

### ISSUE THREAD

**Issue by GollyJer** [microsoft/vscode#154411]
Often I have two editors open (in tab mode), and I use the trash icon to delete one, then the plus icon to add one back (as a fast way to clear anything out).

I hoped by turning on `"terminal.integrated.tabs.hideCondition": "never"` it would keep the title bar section from changing when only one terminal is active.

It looks like this with two terminals.
![image](https://user-images.githubusercontent.com/689204/177884907-c695c701-c74e-48fc-9027-ad3a766c3ea5.png)

But like this with one.
![image](https://user-images.githubusercontent.com/689204/177884639-9f652b0a-9231-4617-95c8-fcefe0f6b9fa.png)

I know this is nitpicky, but it would be great if the title bar didn't change (and thus the `+` button doesn't move) in the title bar when the tabbar is set to never hide.

**Comment by Tyriar** [comment]
I like it 👍

**Comment by sandy081** [comment]
Terminal name is still shown not sure if it is expected?

<img width="245" alt="image" src="https://user-images.githubusercontent.com/10746682/180985795-ab5b492e-6f89-46a5-b913-d02ab4b5db0a.png">
