### ISSUE TITLE
Source Control 'Commit' is not working as expected in latest release

### ISSUE THREAD

**Issue by jkretsch** [microsoft/vscode#154419]
Issue Type: <b>Bug</b>

A 'Commit' button is now always displayed in the Source Control left nav and when you click on it it opens up a new tab that says COMMIT_EDITMSG.  Please this back to the way it was previously.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.20GB free)|
|Process Argv|--crash-reporter-id 413726c7-b010-43ef-9ef0-e4db033fd00e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
vscode-ansi|ili|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by jkretsch** [comment]
Thanks.
    On Friday, July 8, 2022 at 05:38:42 AM PDT, Ladislau Szomoru ***@***.***> wrote:  
 
 


@jkretsch, you can restore the previous behaviour by disabling the git.useEditorAsCommitInput setting.

**Comment by lszomoru** [comment]
@jkretsch, thanks for getting back to me. I will close this issue for now.
