### ISSUE TITLE
how to close auto format?

### ISSUE THREAD

**Issue by GITHON** [Microsoft/vscode#15446]
- VSCode Version:1.7

when i save the changes,vscode allways auto format my code

**Comment by 389605438** [comment]
My vscode is OK ,you are so ugly that your vscode is bad

**Comment by kuang1055wei** [comment]
你猜

**Comment by aeschli** [comment]
@389605438 Please follow our code of conduct guidelines https://opensource.microsoft.com/codeofconduct/. Thanks a lot!

**Comment by GITHON** [comment]
@aeschli thank you!
