### ISSUE TITLE
Limit the amount of open editors

### ISSUE THREAD

**Issue by dan-gamble** [Microsoft/vscode#15449]
- VSCode Version: 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44)
- OS Version: OSX (10.11.6 (15G1108))

I'm coming from PyCharm and am used to working without tabs and the sidebar. In PyCharm i can limit it so when i open one document the other document previously opened gets closed (But it doesn't prompt to save any changes as these persist, not sure how though, and remain there when i re-open).

Is there something similar for VS Code?

**Comment by ramya-rao-a** [comment]
@dan-gamble [Working without tabs](https://code.visualstudio.com/docs/editor/tabs#_working-without-tabs) should help

**Comment by dan-gamble** [comment]
I've followed this :). The main problem is when I close my current document all the other tabs still exist. It's just the tab bar is hidden. I wondered if it's possible to have only one document open at a time. Not just viewing 1 at a time

**Comment by ramya-rao-a** [comment]
Interesting, so you want to have only one editor open at any time. 

@bpasero A setting to limit the number of editors open ?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/9872

**Comment by dan-gamble** [comment]
#9872 explains it much better than me
