### ISSUE TITLE
Tasks batch space in directory problem

### ISSUE THREAD

**Issue by justnonamenoname** [Microsoft/vscode#15444]
- VSCode Version: 1.7.1 (seems all versions)
- OS Version: Windows 7

Steps to Reproduce:

1. Create directory with space: C:/project test
2. Create start.bat in this dir with text: echo 1
3. Create empty text.txt in this dir
4. Run VSCode & Open this dir as workspace
5. Ctrl+Shift+P -> Tasks -> Configure Task Runner -> Others
6. Import this configuration & save
{
	"version": "0.1.0",
	"command": "${workspaceRoot}/start.bat",
	"args": ["${file}"]
}
7. Open text.txt and compile Ctrl+Shift+B
8. Result
"c:\project" �� ����� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� �������� 䠩���.

**Comment by dbaeumer** [comment]
Dups https://github.com/Microsoft/vscode/issues/3550
