### ISSUE TITLE
Terminal cursor issues on older mac version.

### ISSUE THREAD

**Issue by dhowlett99** [microsoft/vscode#154480]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69 & 1.70 insider
- OS Version: Darwin Dereks-iMac.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64

Steps to Reproduce:

1. Open a terminal and hit return a few times. The cursor is flashing in multiple places.
![image](https://user-images.githubusercontent.com/78086928/177966086-0e073e85-b4c8-4a18-80fb-b4b80a986c5b.png)

Note I don't have this issue with version 1.68.1
```
Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:52:13.188Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 15.6.0
```

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by dhowlett99** [comment]
Yes disabling the GPU acceleration does fix this issue. Is this is the release notes someplace ?

**Comment by dhowlett99** [comment]
Closing as workaround provided.
Many thanks.
