### ISSUE TITLE
README not updating in VSC extension in both marketplace and VSC

### ISSUE THREAD

**Issue by plowsjordan** [microsoft/vscode#154444]
This is a based on a previous ticket. I noticed that the original issue had been closed due to lack of info. Our extension is updating in the repo but not in both VSC or the marketplace. 

Any thoughts on how this can be fixed?

Original Response:
> Readme file was in the extension project folder before I converted it into .vsix format. I uploaded the latest version a couple of days ago and the overview is still not updated. The first time when I released the extension a year ago, I uploaded the .vsix file and within few hours I could see the overview. May I know how can I update the overview of my extension, since it didn't happen when uploaded the new version of the same extension.

_Originally posted by @SidHeg in https://github.com/microsoft/vscode/issues/136463#issuecomment-964228431_

**Comment by sandy081** [comment]
> Our extension is updating in the repo but not in both VSC or the marketplace.

VSC or Marketplace does not read the contents of Read me from the repository. Any changes shall have to be published to the marketplace.

**Comment by plowsjordan** [comment]
It appears you didn't understand my question. I am publishing my changes to the marketplace and they were only partially updating.

**Comment by sandy081** [comment]
> Our extension is updating in the repo but not in both VSC or the marketplace.

>  It appears you didn't understand my question. I am publishing my changes to the marketplace and they were only partially updating.

Yes, its not clear what you are trying to report. Can you please explain clearly what you are trying to do and what you are expecting and is not working?
