### ISSUE TITLE
Search not finding all occurrences - unreliable results each search 

### ISSUE THREAD

**Issue by Zainzzkk** [microsoft/vscode#154468]
Issue Type: <b>Bug</b>

1) search for variable across codebase
2) search results sometimes come back empty or not with all the results present for that variable
3) search again and more appear or different ones
4) Makes search unreliable and also bad for application if trying to find and replace all

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.55GB free)|
|Process Argv|--crash-reporter-id 18b9592e-85ea-472e-90cc-39ce1ea9f468|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
govuk-elements-snippets|abb|0.2.1
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.1
EditorConfig|Edi|0.16.4
nunjucks-template|ese|0.5.1
nodejs-snippets|piy|0.0.2
vs-code-prettier-eslint|rve|5.0.3
sonarlint-vscode|Son|3.6.0
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by roblourens** [comment]
Please see https://github.com/microsoft/vscode/wiki/Search-Issues for tips, if that doesn't help, you could share the logs or a repo/folder where this happens

**Comment by Zainzzkk** [comment]
It seems to be fixed in the latest release
