### ISSUE TITLE
Task Switcher icon is missing on Plasma Wayland

### ISSUE THREAD

**Issue by mamantoha** [microsoft/vscode#154495]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.0
- OS Version: Manjaro Linux 21.3.2
- DE: Plasma 5.24.5

Steps to Reproduce:

1. Install vscode from AUR https://aur.archlinux.org/packages/visual-studio-code-bin
2. Icon in Task Switcher (Alt+Tab) is shown as a fallback Wayland icon
 
![Screenshot_20220708_141653](https://user-images.githubusercontent.com/61285/177983221-d5baa225-c160-4baf-bbc2-4d11215b5d8f.png)

However, an icon in Task Manager is ok.

Probably this issue is because vscode window missing property "desktopFileName"
Kwin Debug Console:
![Screenshot_20220708_141909](https://user-images.githubusercontent.com/61285/177983640-c4a9535e-a7eb-47fe-8aa5-f92d8cc08706.png)

But I'm not sure, it can be an issue because of something else.

See https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon for reference:

> If for some reason your application is not using KAboutData, you need to manually call QGuiApplication::setDesktopFileName(). 

I believe there is something similar for Electron apps.

Related Electron issue: https://github.com/electron/electron/issues/34852

**Comment by nocturnalmc** [comment]
Have the same issue on Gnome too where launching it on Wayland causing the icon on the dock to be missing

**Comment by edipangi** [comment]
It is also present in insiders build.

**Comment by Merrit** [comment]
Seems very easy to test:

- Running `code`: normal
- Running `code --ozone-platform=wayland`: generic icon in taskbar / overview

**Comment by sysoev-dev** [comment]
@Merrit 
Fedora 36, Gnome (Wayland)
`code` - starting on Xwayland. Icon present
`code --ozone-platform=wayland` - Using wayland. Icon missing

**Comment by Merrit** [comment]
> @Merrit Fedora 36, Gnome (Wayland) `code` - starting on Xwayland. Icon present `code --ozone-platform=wayland` - Using wayland. Icon missing

Yes, exactly.

**Comment by sysoev-dev** [comment]
> Yes, exactly.

I'm annoyed by the lack of an icon. But, I still choose wayland because it is more productive. On xwayland I get subtle artifacts

**Comment by nocturnalmc** [comment]
> > Yes, exactly.
> 
> I'm annoyed by the lack of an icon. But, I still choose wayland because it is more productive. On xwayland I get subtle artifacts

For me on xwayland the cursor is lagging a lot. On wayland the cursor move snappier

**Comment by ReillyBrogan** [comment]
I just updated Electron to 19.0.10 locally (by applying a slightly modified #154092), and it appears that this behavior is caused because in Wayland the app_id is set to `code-oss-url-handler` while in X11 the WMClass is set to `Code - OSS`. These need to be identical for the window manager to correctly correlate the running applications to the desktop file so that it will show the correct icon in the task manager and any task switcher applications.

**Comment by ReillyBrogan** [comment]
For instance if you change the StartupWMClass field (despite the name this is matched to the app_id in Wayland) in the desktop file to `code-oss-url-handler` and reload the application database then the icon will be shown correctly when VSCode is launched in Wayland but the icon will be broken when launched under X11.

**Comment by mamantoha** [comment]
This is already fixed in Electron https://github.com/electron/electron/pull/34877 v18.3.6 and v19.0.9.

**Comment by ReillyBrogan** [comment]
> This is already fixed in Electron [electron/electron#34877](https://github.com/electron/electron/pull/34877) v18.3.6 and v19.0.9.

Who are you replying to? Because if you're replying to me I already stated that my observations came from testing 19.0.10

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/154693
