### ISSUE TITLE
Git: Revert Selected Ranges broken

### ISSUE THREAD

**Issue by vulkman** [microsoft/vscode#154477]
Version: 1.69.0

All extensions disabled.

Steps to reproduce:

1. Make changes at multiple areas in a file
2. Stage everything
3. Open diff view
4. Mark one area, right-click and select "Revert selected ranges"
5. Nothing happens

**Comment by lszomoru** [comment]
Closing as duplicate of [156748](https://github.com/microsoft/vscode/issues/156748)
