### ISSUE TITLE
Tabs wrap: visual glitch with pinned tabs and shrink sizing

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#154432]
Does this issue occur when all extensions are disabled?: Yes

版本: 1.69.0 (system setup)
提交: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
日期: 2022-07-07T05:28:36.503Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.25151

Steps to Reproduce:
pin many tabs

1. there is 3 tabs
![image](https://user-images.githubusercontent.com/1876302/177903542-329a0a52-cf2a-4550-a071-69e5191ac620.png)

2. bug show(eg: show ths side bar to reduce the editor length)
    a. right align
    b. just one tab

![image](https://user-images.githubusercontent.com/1876302/177903612-16f9c6e7-191c-4452-a164-fbee8831b524.png)

**Comment by bpasero** [comment]
How do you right align tabs? What settings do you have configured that impact this?

I tried with tabs wrapping enabled and cannot see an issue so far:

<img width="869" alt="image" src="https://user-images.githubusercontent.com/900690/177915796-67c0be6c-e2cc-4ec6-b5b5-1f32dad8645a.png">

**Comment by heartacker** [comment]
> How do you right align tabs? What settings do you have configured that impact this?
> 
> I tried with tabs wrapping enabled and cannot see an issue so far:
> 
> <img width="869" alt="image" src="https://user-images.githubusercontent.com/900690/177915796-67c0be6c-e2cc-4ec6-b5b5-1f32dad8645a.png">
> 

that is the point. I had do nothing/setting
and that is also my question

**Comment by bpasero** [comment]
Ah I see, yes it is currently intentional that tabs wrap when you pin them because the idea is that pinned tabs are always visible.

**Comment by heartacker** [comment]
![pin_tabs](https://user-images.githubusercontent.com/1876302/178882950-75966474-a876-4f24-948b-c733176de0f8.gif)

when I reload the window

**Comment by bpasero** [comment]
@heartacker can you share your settings?

**Comment by heartacker** [comment]
which items do you need?

and can it be repro while you pin lots of tabs?

**Comment by bpasero** [comment]
I cannot reproduce it when I pin lots of tabs, contradicting to what I had said, tabs do not wrap unless you enable wrapping.

**Comment by heartacker** [comment]
follow may step
![pin_tabs_repro](https://user-images.githubusercontent.com/1876302/179130174-a18243e0-6ffe-4c61-a5f7-22a39d255719.gif)

**Comment by bpasero** [comment]
![Recording 2022-07-15 at 07 38 46](https://user-images.githubusercontent.com/900690/179158039-912d4427-420b-4cc4-8a24-33754ab14b65.gif)

**Comment by heartacker** [comment]
except pinning many tabs, I also open many unpined tab,
accourding to you gif, you just only pin many tabs, could you please try,  I meet this 100% and I don't know why

**Comment by bpasero** [comment]
Yes I also tried with normal tabs.

Going forward I would need step by step instructions how to reproduce, including:
* all settings
* the workspace you open
* the files you open and pin in the right order

**Comment by heartacker** [comment]
![image](https://user-images.githubusercontent.com/1876302/179684392-c5ecfd41-c7ec-44f0-a26c-e0e61bbec439.png)

- GIF:

![PTREPRO](https://user-images.githubusercontent.com/1876302/179684372-2999ff1f-9870-4293-b545-88ba4dbe6478.gif)

**Comment by bpasero** [comment]
Thanks, I see it now. I wonder if this is a recent regression :O

**Comment by bpasero** [comment]
I can reproduce this for a long time, it was probably never working 🤔
