### ISSUE TITLE
Colors washed out after upgrade to v1.69.0

### ISSUE THREAD

**Issue by jhuckaby** [microsoft/vscode#154596]
Issue Type: <b>Bug</b>

- Set color theme to something dark like "One Dark Pro".
- Upgrade to VS Code v1.69.0
- Notice all the colors are more "washed out" and/or dull compared to previous version.
- See attached screenshots (below) for comparison.
- Also happens in Insiders build v1.70.0-insider

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:46.408Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (3.70GB free)|
|Process Argv|--crash-reporter-id bb8f29d5-8631-4571-84a5-eb72eadd2676|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
sublime-keybindings|ms-|4.0.10
savebackup|pur|0.0.4
code-spell-checker|str|2.3.0
vscode-icons|vsc|11.12.0
vscode-todo-highlight|way|1.0.5
material-theme|zhu|3.15.2

</details>

### Screenshots

Screenshot before upgrade:

<img width="1705" alt="vscode-1 68 1" src="https://user-images.githubusercontent.com/700765/178093820-7f842058-19a7-4070-b5a6-3c64d3afeb68.png">

Screenshot after upgrade to v1.69.0:

<img width="1705" alt="vscode-1 69 0" src="https://user-images.githubusercontent.com/700765/178093828-359f3052-bee9-40af-8d6b-29c321bdc647.png">

Screenshot from Insiders build (v1.170.0) with no extensions except "One Dark Pro" color theme:

<img width="1491" alt="vscode-insiders-1 70 0" src="https://user-images.githubusercontent.com/700765/178093836-30752a51-c7e3-4144-a80d-14eb765a4f5e.png">

**Comment by jhuckaby** [comment]
It's difficult to see the difference when the screenshots are stacked like this.  Try opening each one in a tab, and switch back & forth between the tabs.  It's clearly visible when you A/B flip between them.

**Comment by levymetal** [comment]
This was immediately noticeable to me after upgrading to 1.69.0 (I use [Firefox Dark](https://marketplace.visualstudio.com/items?itemName=Heron.firefox-devtools-theme)). The theme is now very dull. I've tried all combinations of `disable-color-correct-rendering` and `force-color-profile` in `argv.json` and see no differences - it's as if these settings no longer have any effect.

The follow issues are somewhat related: https://github.com/microsoft/vscode/issues/51791, https://github.com/microsoft/vscode/issues/65816, https://github.com/microsoft/vscode/issues/88491.

I've been digging through the [diff](https://github.com/microsoft/vscode/compare/1.68.1...1.69.0) but it's a big one and haven't found anything concrete yet. Electron was bumped from `17.4.6` to `18.3.5` which could be a potential culprit. There is also this issue on Electron which might be relevant: https://github.com/electron/electron/issues/34592

**Comment by jhuckaby** [comment]
Here's an MP4 of the two screenshots, each at 1 second duration:

https://user-images.githubusercontent.com/700765/178127135-ae5f250e-fcc0-458d-9877-0b38383ccfe1.mp4

**Comment by littlecxm** [comment]
+1, same problem

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/152816
