### ISSUE TITLE
Signed commits fail

### ISSUE THREAD

**Issue by KotonBads** [microsoft/vscode#154503]
Issue Type: <b>Bug</b>

Trying to sign a commit with gpg fails

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T08:29:47.439Z)
OS version: Linux x64 5.18.9-200.fc36.x86_64
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|7.24GB (0.51GB free)|
|Process Argv|--unity-launch --crash-reporter-id 5ea4ba82-b095-4406-a121-0693cba70501|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
gitlens|eam|12.1.1
code-runner|for|0.11.8
go|gol|0.34.1
discord-vscode|icr|5.8.0
better-cpp-syntax|jef|1.15.19
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
cpptools|ms-|1.10.8
material-icon-theme|PKi|4.19.0
material-product-icons|PKi|1.3.0
sqlite-viewer|qwt|0.1.5
sourcery|sou|0.12.2
vscode-vlang|vla|0.1.13
carbon|who|0.3.1
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by KotonBads** [comment]
clicking on show command output shows this
![image](https://user-images.githubusercontent.com/66117568/177995714-442a572b-ef95-487a-b235-6d573d99901c.png)

```
> git -c user.useConfigOnly=true commit --quiet --allow-empty-message --file - -S
error: gpg failed to sign the data
fatal: failed to write commit object```

**Comment by hyoretsu** [comment]
Bump, this is pretty important.

**Comment by lszomoru** [comment]
@KotonBads, @hyoretsu,  sorry for not getting back to you on this until now.
Are you still able to reproduce this issue with the latest version of VS Code? Thanks!

**Comment by KotonBads** [comment]
@lszomoru still doesn't work on the latest version, different error this time however
![2023-12-14_23-26-02s](https://github.com/microsoft/vscode/assets/66117568/09f0236a-9192-497c-9306-127680d7f7ab)

signing commits does work when I do it manually (`git commit -S -m "message"`)

this problem also only happens when signing with gpg keys, my ssh keys work perfectly fine

**Comment by lszomoru** [comment]
@KotonBads, VS Code does not current support displaying a prompt when trying to sign a commit using a GPG key. That is currently being tracked in this issue https://github.com/microsoft/vscode/issues/43809. Here is some guidance that our team has put together of signing commits on various platforms - https://github.com/microsoft/vscode/wiki/Commit-Signing. We are adding support for signing commits with an SSH key and passphrase. That work is tracked here: https://github.com/microsoft/vscode/issues/179517.
