### ISSUE TITLE
Editor hovers shift when they appear

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#154577]
I see this happening in different workspaces and files - the hover flickers and shifts a bit as it appears. A little hard to see in the gif. I can debug if you can't repro it

![Recording 2022-07-08 at 15 56 34](https://user-images.githubusercontent.com/323878/178079847-1bfeed25-fbf7-4740-83fe-d115f19de24a.gif)

**Comment by alexdima** [comment]
Caused by https://github.com/microsoft/vscode/pull/152011/files
