### ISSUE TITLE
Command Center stays open on clicking on the window title bar

### ISSUE THREAD

**Issue by jayantdhawan** [microsoft/vscode#154541]
Issue Type: <b>Bug</b>

1. Enable the new Command Center feature available with the June 2022 update.
2. Open the command/file list flyout by clicking in the command center.
3. Click outside the flyout on the VS Code window title bar. See that the flyout does not get dismissed.
4. Click outside the flyout in the VS Code editor. This time the flyout gets dismissed.

Expected: Command Center flyout should get dismissed when clicking anywhere outside the flyout.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (40.21GB free)|
|Process Argv|--crash-reporter-id f5824b19-814b-479d-9f84-0e0dac677fb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
icons-carbon|ant|0.2.5
markdown-emoji|bie|0.2.1
custom-window-zoom|cra|1.1.4
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.1
plantuml|jeb|2.17.3
fluent-icons|mig|0.0.17
cpptools|ms-|1.10.8
vscode-jest|Ort|4.6.0
vscode-xml|red|0.21.2022062916
bootstrap-product-icons|rub|1.0.2
santacodes-region-viewer|San|1.1.1
code-spell-checker|str|2.3.0
vscode-icons|vsc|11.12.0
gitblame|wad|8.2.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
pylanb8912:30520716
vsclangdc:30486549

```

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/153910
