### ISSUE TITLE
workbench.editorAssociations is ignoring declared values

### ISSUE THREAD

**Issue by TGiles** [microsoft/vscode#154527]
Issue Type: <b>Bug</b>

It seems like `workbench.editorAssociations` is ignoring declared values, at least in the GitLens interactive rebase editor case.

STR:
1. Install GitLens
1. After installing GitLens, ensure you have the following object in settings.json
  `"workbench.editorAssociations": { "git-rebase-todo": "gitlens.rebase"}`
1. Have a git repository
1. Have two branches in git repository
1. Interactively rebase one branch onto another `git rebase -i branch`

Expected results:
The GitLens interactive rebase editor appears

Actual results:
The text based git-rebase-todo file appears

This was working as expected with the May 2022 release of vscode and immediately changed when I installed the new June 2022 release. I don't believe this is an issue with the extension as the `gitlens.rebase` value is a valid option.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (16.40GB free)|
|Process Argv|--crash-reporter-id 378d1d3f-91d7-47dc-87c5-fadb350100ea|
|Screen Reader|no|
|VM|36%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdc:30486549

```

</details>

**Comment by lramos15** [comment]
I cannot reproduce, can you try https://code.visualstudio.com/insiders/ and just installing the gitlens extension. You can name a file just "git-rebase-todo" and it should work the same way

**Comment by TGiles** [comment]
So if I use insiders and install the gitlens extension, opening the `git-rebase-todo` file will open the gitlens interactive rebase correctly. I guess it's something to do with my particular workspace set up or something as I'm unable to reproduce when using `git rebase -i HEAD~` on a newly initialized git repo on insiders using just the gitlens extension.

I guess we can go ahead and close this out, seems to just be a quirk with my workspace set up or something. Not sure what I should be looking for to ensure the gitlens interactive rebase is used over the default text one that gets launched in a new tab though

**Comment by TGiles** [comment]
Hmm, it seems switching `git.terminalGitEditor` from `true` to `false` fixed my situation. Not entirely sure why, but good enough for me I suppose
