### ISSUE TITLE
Rulers no longer showing in editor

### ISSUE THREAD

**Issue by dylan-brackett** [microsoft/vscode#154538]
Issue Type: <b>Bug</b>

editor.rulers no longer produces ruler on my vscode window. I've tried running without extensions, and clearing my settings file to just contain the editor.rulers settings. I've tested with both single, and multiple rulers, and none show up.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (10.30GB free)|
|Process Argv|--crash-reporter-id aed9bee0-aa1e-4b48-98ee-cabd36e2e39b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
Bookmarks|ale|13.3.0
gitlens|eam|12.1.1
code-runner|for|0.11.8
copilot|Git|1.31.6194
vscode-pull-request-github|Git|0.46.0
todo-tree|Gru|0.0.215
rest-client|hum|0.25.0
vsc-python-indent|Kev|1.17.0
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1001902341
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.82.1
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.1
hexeditor|ms-|1.9.7
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
keyboard-quickfix|pas|0.0.6
material-icon-theme|PKi|4.19.0
sourcery|sou|0.12.3
code-spell-checker|str|2.3.0
cmake|twx|0.0.17
win-ca|uko|3.5.0
vscodeintellicode|Vis|1.2.22
vscode-arduino|vsc|0.4.12
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
pylanb8912:30520716
vsclangdf:30486550

```

</details>

**Comment by ArturoDent** [comment]
`rulers` work for me in both v1.69 Stable and v1.70 Insiders - but - I do have to focus another editor besides settings to get them to show.  Then when going back to settings.json the rulers show there as well.

**Comment by dylan-brackett** [comment]
I tried that as well, but still no rulers for me.

**Comment by dylan-brackett** [comment]
I was able to determine that the project I was in had a built in VSCode setting disabling rulers project wide, overwriting my settings.
