### ISSUE TITLE
Shell Integration Does Not Work When Swapping Terminal Types

### ISSUE THREAD

**Issue by phildaniels** [microsoft/vscode#154547]
Issue Type: <b>Bug</b>

On a linux based system (wsl in my case) with zsh installed, start up a new bash terminal. Enter command "zsh" to enter zsh. Shell integration is non functional

To get the shell integration working with zsh I must explicitly create a new terminal window specifying "zsh", or have zsh specified as my default shell for my linux system

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Remote OS version: Linux x64 5.10.60.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.14GB free)|
|Process Argv|--crash-reporter-id cae8f516-9950-4565-8ceb-faf5b442efab|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.60.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|Memory (System)|24.84GB (21.00GB free)|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
chalice-icon-theme|art|1.2.20
vscode-icontheme-nomo-dark|be5|1.3.6
remotehub|Git|0.36.0
vscode-drawio|hed|1.6.4
vscode-azurevirtualmachines|ms-|0.6.2
remote-containers|ms-|0.241.3
remote-wsl|ms-|0.66.3
remote-repositories|ms-|0.14.0
rose-pine|mvl|2.3.0
developer-theme-dark|Raj|4.0.0
ng-template|Ang|14.0.1
azurenodeessentials|azu|0.2.6
azurite|Azu|3.18.0
armview|ben|0.4.6
turbo-console-log|Cha|2.3.2
apex-pmd|chu|0.5.9
vscode-svgviewer|css|2.0.0
githistory|don|0.6.19
gitlens|eam|12.1.1
prettier-vscode|esb|9.5.0
vs-code-xml-format|fab|0.1.5
lana|Fin|1.4.2
code-runner|for|0.11.8
copilot|Git|1.31.6194
gc-excelviewer|Gra|4.2.55
rest-client|hum|0.25.0
vscode-postfix-ts|ipa|1.10.1
csharpextensions|kre|1.7.0
vscode-leetcode|Lee|0.18.1
file-downloader|min|1.0.12
mindaro|min|1.0.120220125
azure-pipelines|ms-|1.205.0
vscode-apimanagement|ms-|1.0.5
vscode-azureappservice|ms-|0.24.3
vscode-azurecognitivesearch|ms-|0.3.1
vscode-azureeventgrid|ms-|0.1.1
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.4
vscode-azureserverlesspack|ms-|0.1.0
vscode-azurestaticwebapps|ms-|0.11.2
vscode-azurestorage|ms-|0.14.2
vscode-azurevirtualmachines|ms-|0.6.2
vscode-bicep|ms-|0.8.9
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.0
vscode-logicapps|ms-|1.1.8
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
vscode-kubernetes-tools|ms-|1.3.10
data-workspace-vscode|ms-|0.2.1
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.0
sql-database-projects-vscode|ms-|0.17.1
azure-account|ms-|0.11.0
azurecli|ms-|0.5.0
cpptools|ms-|1.10.8
vscode-node-azure-pack|ms-|1.0.0
vsliveshare|ms-|1.0.5641
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
azurerm-vscode-tools|msa|0.15.7
vscode-react-native|msj|1.9.2
hardhat-solidity|Nom|0.4.3
vscode-commons|red|0.0.6
vscode-xml|red|0.21.0
vscode-yaml|red|1.8.0
salesforce-vscode-slds|sal|1.4.8
salesforcedx-vscode|sal|55.4.0
salesforcedx-vscode-apex|sal|55.4.0
salesforcedx-vscode-apex-debugger|sal|55.4.0
salesforcedx-vscode-apex-replay-debugger|sal|55.4.0
salesforcedx-vscode-core|sal|55.4.0
salesforcedx-vscode-expanded|sal|55.4.0
salesforcedx-vscode-lightning|sal|55.4.0
salesforcedx-vscode-soql|sal|55.4.0
salesforcedx-vscode-visualforce|sal|55.4.0
yo|sam|0.9.3
intellicode-api-usage-examples|Vis|0.1.2
vscodeintellicode|Vis|1.2.22
application-insights|Vis|0.4.2
quokka-vscode|Wal|1.0.487

(7 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550

```

</details>

**Comment by phildaniels** [comment]
Here is a screenshot of the behavior

![image](https://user-images.githubusercontent.com/11820265/178053392-3cd16234-e513-4e47-85e2-2655d1ca98c9.png)

**Comment by meganrogge** [comment]
this is expected bc we don't currently support subshells. You can install shell integration manually to get this to work. https://code.visualstudio.com/docs/editor/terminal-shell-integration#_manual-installation

**Comment by phildaniels** [comment]
> this is expected bc we don't currently support shell integration injection into subshells
> 
> You can install shell integration manually to get this to work. https://code.visualstudio.com/docs/editor/terminal-shell-integration#_manual-installation

This worked perfectly, thank you Megan!
