### ISSUE TITLE
running `exit` isn't closing the terminal

### ISSUE THREAD

**Issue by imranbarbhuiya** [microsoft/vscode#154586]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 1.69.0
- OS Version: windows 11

Steps to Reproduce:

1. enable shell integration
```json
  "terminal.integrated.shellIntegration.enabled": true,
```
2. run `exit` in the terminal

**Comment by Tyriar** [comment]
Spotted this yesterday, I think it's annoying enough to get into the recovery build. I'll reopen https://github.com/microsoft/vscode/issues/154421

/duplicate
