### ISSUE TITLE
Why does `:` get highlighted when you type `.`?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#154533]
![image](https://user-images.githubusercontent.com/2644648/178033949-8b7c55cf-3b60-45df-84ec-d405c1e30eaa.png)

Turns out this is because we treat whitespace and some special characters as the same:
https://github.com/microsoft/vscode/blob/f5a2bc1eff140ddecb5f67933649556b229dd0f3/src/vs/base/common/filters.ts#L123-L127

When generating matches:
https://github.com/microsoft/vscode/blob/f5a2bc1eff140ddecb5f67933649556b229dd0f3/src/vs/base/common/filters.ts#L309

**Comment by TylerLeonhardt** [comment]
Really we may want to ask the question... if you type `.`, should `Git: Push` match? The answer might be "no" but it's worked like that for a longgggg time so I'm cautious to make that change.

To be iterative, let's at least only _highlight_ the characters that make sense. So: `.` would not cause `:` to be highlighted, but typing `:` would cause `:` to be highlighted.

**Comment by lramos15** [comment]
Maybe unrelated but the highlight behavior surrounding these characters is a bit weird. See how sum lines have all periods highlighted and others don't 
<img width="457" alt="image" src="https://user-images.githubusercontent.com/4544166/186434142-bd8bd2b4-1909-4818-8973-f08a3bbd0112.png">
