### ISSUE TITLE
EH debugging: reload window or open project results in two reloads 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#15450]
- VSCode Version: Insider
- OS Version: macOS

Steps to Reproduce:

1. run Hello World extension from VS Code
2. in EH window reload window (e.g. 'Cmd-R') or open another project

Observe: EH reloads twice

VS Code stable does not show this behaviour.

**Comment by bpasero** [comment]
@weinand I think this is what I reported in https://github.com/Microsoft/vscode/issues/14895

lets continue there
