### ISSUE TITLE
Typescript crashes

### ISSUE THREAD

**Issue by rsivan** [microsoft/vscode#154554]
Issue Type: <b>Bug</b>

Not sure

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id b62a9bb9-6677-47f0-93e4-6f28212cb4d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.0.1
turbo-console-log|Cha|2.3.2
npm-intellisense|chr|1.4.2
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.1.1
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
vscode-ionic-snippets|fiv|2.2.2
vscode-jasmine-test-adapter|hbe|1.8.1
vscode-test-explorer|hbe|2.21.1
beautify|Hoo|1.5.0
circleci-vscode|jod|0.2.2
Angular2|joh|13.0.0
json-to-ts|Mar|1.7.5
vscode-scss|mrm|0.10.0
test-adapter-converter|ms-|0.1.6
vscode-typescript-tslint-plugin|ms-|1.3.4
java|red|1.8.0
vscode-multiclip|sle|0.1.5
autoimport|ste|1.5.4
vsfire|tob|1.4.1
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.42.0
vscode-java-dependency|vsc|0.20.0
vscode-java-pack|vsc|0.24.0
vscode-java-test|vsc|0.35.2
vscode-maven|vsc|0.36.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30519255
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by rsivan** [comment]
I was just editing

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

Most likely this is caused by the deprecated tslint plugin
