### ISSUE TITLE
Extensions in devcontainer.json get installed in the wrong host on codespaces

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#154563]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.69.0 (codespaces)
- OS Version: MacOS 12.4 (chrome)

Steps to Reproduce:

1. Use/identify an extension which can run in different extension hosts depending on host availability following the pattern agreed in https://github.com/microsoft/vscode/issues/141322 (e.g. [arm.device-manager](https://marketplace.visualstudio.com/items?itemName=Arm.device-manager))
2. Create a GitHub repository containing a `devcontainer.json` file with this extension (e.g. [this one](https://github.com/thegecko/getting-started))
3. Create a codespace on that repository and observe all extensions are installed in the remote host as `codespace` extensions

<img width="344" alt="Screenshot 2022-07-08 at 21 55 00" src="https://user-images.githubusercontent.com/61341/178068995-b894f8d6-be57-4a8b-bfce-96417ec9a158.png">

Expected behaviour - the multi-host extension should install as a web extension into `browser` extensions.

When installing this extension manually, it behaves correctly:

<img width="350" alt="Screenshot 2022-07-08 at 21 53 12" src="https://user-images.githubusercontent.com/61341/178068761-042508fe-9e74-4617-ba9a-dc5bfad9f271.png">

**Comment by sandy081** [comment]
This is designed by the codespaces to read the devcontainer.json on server side and  install extensions there. Please file the issue against the codespaces if you think otherwise.

**Comment by thegecko** [comment]
@sandy081 Where is the repo/issues for codespaces, please?

**Comment by sandy081** [comment]
Here it is https://support.github.com/features/codespaces

**Comment by thegecko** [comment]
Moved to: https://github.com/orgs/community/discussions/41636
