### ISSUE TITLE
Telemetry for Settings

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#15451]
Just an hypothesis that Following are the two flows which users majorly follow to update a setting

- Find/Copy/Paste : Find the setting in Default settings using Find functionality. Copy and paste it in `Settings.json`. Update it.
- Intelli-sense: Completely use intelli-sense in `Settings.json` to find and update the setting.

Others:
- Navigate through Default settings to find a setting. Copy/Paste/Manually type to update the setting.
- Discover a setting from external source and update it.

We would need some telemetry data to support this hypothesis. This will give some input to improve the UX for managing settings.

**Comment by sandy081** [comment]
@seanmcbreen Is there any telemetry data that can give us above information?

**Comment by chrmarti** [comment]
There is telemetry for reading a file and for the clipboard actions. It will need some guessing about the targets of the clipboard actions, we currently don't log these.

**Comment by sandy081** [comment]
@chrmarti You mean to say currently we cannot get this information with the telemetry data we have now.

How about adding additional necessary telemetry entries particularly for settings files so that we can get needed information?

**Comment by chrmarti** [comment]
There is no simple way to get at that information currently. You could look at how often copy&paste is used after opening the settings, but you'd also count some cases where the user has moved away from settings I guess.

You should be able to add specific telemetry, I haven't looked into how you would do that. Maybe the code logging editor actions could also log the document type?

**Comment by sandy081** [comment]
Thanks for the information. I would see if I can play around with that telemetry and also think about adding specific log.
