### ISSUE TITLE
Wrong translation - Branch publish

### ISSUE THREAD

**Issue by CuzImBisonratte** [microsoft/vscode#154576]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0-insider
- OS Version: Win11 21H2 (22000.778)

Steps to Reproduce:

1. Set language to German
2. Clone a repo
3. Create a new branch with the branch-creation-dialogue fom vscode
4. Go into source control
5. There you can see "Filiale veröffentlichen" which is "Publish shop" when it should be "Zweigstelle veröffentlichen" or better "Branch veröffentlichen". You can see it below:

**Comment by TylerLeonhardt** [comment]
@lszomoru in order to ensure Branch is not change, you need to lock in via a comment. Once that's all good, we can submit the feedback on the rest of the translation.

**Comment by AlCalzone** [comment]
Not sure if the tooltip was considered here, since it is using a third (okayish) translation:
![image](https://user-images.githubusercontent.com/17641229/179680688-7e982e88-dee4-4b67-a05b-03a34ad0bc2a.png)
I agree that this should just be called Branch though.

**Comment by lszomoru** [comment]
Yes, commit https://github.com/microsoft/vscode/commit/bc51adde6f10583b37c4e1face82224860a2db30 covers both the button label and the tooltip.
