### ISSUE TITLE
Intermittent empty white space in open editors and other sections

### ISSUE THREAD

**Issue by yizjak** [microsoft/vscode#154641]
Issue Type: <b>Performance Issue</b>

1. Minimize / Maximize any window in front of a VS Code's active window with an open file.
2. Change the current window with Alt + Tab keys, go back to VS Code.
3. Sometimes you will see a white box in front of "open editors" or other places in the VS Code window, when you put the mouse hover it, that box will disappear temporaly until release it.

(It happens to me when using Google Chrome and VS Code at the same time)

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (3.58GB free)|
|Process Argv|--crash-reporter-id b7dbf2f5-6319-4546-a640-3226528542ef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	  4188	code main
    1	   102	  1964	   issue-reporter
    0	   262	  2272	   window (AjusteDatos.vue - flamebark - Visual Studio Code)
    0	    40	  4476	   utility-network-service
    0	    81	  6108	   gpu-process
    0	   107	  8820	   shared-process
    0	    72	 11800	     ptyHost
    0	     6	  4800	       console-window-host (Windows internal process)
    0	    36	  8652	       C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command npm run dev
    0	     4	  9300	         C:\Windows\system32\cmd.exe /c ""C:\Program Files\nodejs\npm.cmd" run dev"
    0	    21	 10624	           "C:\Program Files\nodejs\\node.exe"  "C:\Program Files\nodejs\\node_modules\npm\bin\npm-cli.js" run dev
    0	     4	  1288	             C:\Windows\system32\cmd.exe /d /s /c vite
    0	   115	 10936	               electron_node vite.js 
    0	    14	  4484	                 C:\Users\Isaac\Documents\Web\flamebark\node_modules\esbuild-windows-64\esbuild.exe --service=0.14.48 --ping
    0	    69	 12872	     fileWatcher
    0	   132	 11700	   extensionHost
    0	   107	  2720	     "C:\Users\Isaac\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Isaac\.vscode\extensions\dbaeumer.vscode-eslint-2.2.6\server\out\eslintServer.js --node-ipc --clientProcessId=11700
    0	   549	  4456	     "C:\Users\Isaac\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Isaac\.vscode\extensions\vue.volar-0.38.3-win32-x64\server --node-ipc --clientProcessId=11700
    0	   155	  4772	     "C:\Users\Isaac\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Isaac\.vscode\extensions\vue.volar-0.38.3-win32-x64\server --node-ipc --clientProcessId=11700
    0	    70	 11616	     "C:\Users\Isaac\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Isaac\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=11700
    0	    25	 12780	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (AjusteDatos.vue - flamebark - Visual Studio Code)
|    Folder (flamebark): 205 files
|      File types: png(50) vue(50) js(8) css(7) svg(6) jpg(6) json(6) ttf(3)
|                  woff(3) html(3)
|      Conf files: package.json(1) tsconfig.json(1);
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
beardedicons|Bea|0.21.0
vscode-intelephense-client|bme|1.8.2
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.1
prettier-vscode|esb|9.5.0
composer|ika|0.8.0
smarty|imp|0.3.0
vscode-apache|mrm|1.2.0
volar|Vue|0.38.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30519256
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdf:30486550

```

</details>

**Comment by tanhakabir** [comment]
Do you have any gifs of this behavior?

**Comment by deepak1556** [comment]
Please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
