### ISSUE TITLE
Themes: Dynamic theme installation needs polish

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#154651]
Pre-req: Settings Sync on

1. Create brand new empty profile
2. Run `Preferences: Color Theme`
3. Pick `Browse Additional Color Themes`
4. Pick a theme

🐛 Settings sync asks this strange question:

![image](https://user-images.githubusercontent.com/22350/178119880-15475d66-7dbd-46aa-9a5a-7d71f6845404.png)

---

Additionally:

5. Cancel this dialog

🐛 Theme is still applied but not installed

**Comment by meganrogge** [comment]
@aeschli were there specific steps to repro this?

**Comment by joaomoreno** [comment]
I can verify that cancelling the dialog no longer leaves the theme applied, thanks @aeschli.

@sandy081  I can still reproduce the main issue though. Why would I not want to synchronize the theme I just picked for my brand new profile, given the profile is being synced?

**Comment by sandy081** [comment]
I think @aeschli is using the general extension install command that will ask user to sync or not before installing. If it is in core, one can use the API directly to install.

**Comment by aeschli** [comment]
I think we still want an install confirmation dialog, but I agree that there should be no question about syncing.
