### ISSUE TITLE
comand ! not working

### ISSUE THREAD

**Issue by santiagosod** [microsoft/vscode#154661]
Issue Type: <b>Bug</b>

The comand ! to open up the menu of the html is not working, is not even poping up

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by 842072627** [comment]
We are the same!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
