### ISSUE TITLE
vscode extensions are not able to be installed on container - version 1.69

### ISSUE THREAD

**Issue by guy0guy** [microsoft/vscode#154672]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version:
- OS Version:
vscode version 1.69
windows/ linux ubuntu
Steps to Reproduce:

1. connecting to remote linux SSH host form windows
2. installing extensions work ok
3. attaching to docker container inside the remote linux host
4. trying to install extensions on the attached vscode - extensions are never installed - hangs forever

In version 1.68.1 it works ok (although very slow).

**Comment by sandy081** [comment]
Can you please provide following logs while installing extension on the attached VS Code.

- Enable Log Level to Trace (F1 > Set Log Level...)
- Share F1 > Open View... > Log (Remote)
- Share F1 > Open View... > Log (Window)

**Comment by guy0guy** [comment]
![image](https://user-images.githubusercontent.com/107554435/179981808-1eca84b0-494f-4ee2-bf35-18cb0972037d.png)

attached image with the trace logs (it keeps retrying with the same trace a few times and then give up)
