### ISSUE TITLE
Signed commits broken?

### ISSUE THREAD

**Issue by lamarqua** [Microsoft/vscode#15469]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|RustyCode|saviorisdead|0.19.1|
|vscode-lldb|vadimcn|0.3.1|
|debug|webfreak|0.12.2|

---

Steps to Reproduce:

1. Setup signed commits with GPG
2. Try to commit something within VSCode.

Here's the relevant git log message:
```
git add -A -- .
git commit --quiet --allow-empty-message --file - --all
error: gpg failed to sign the data
fatal: failed to write commit object
```

**Comment by joaomoreno** [comment]
Please check suggestion in https://github.com/Microsoft/vscode/issues/5065#issuecomment-207960831
