### ISSUE TITLE
Problem with blocked-empty space in editor area

### ISSUE THREAD

**Issue by mxcdh** [microsoft/vscode#154610]
Hello

  
I noticed yesterday, that my vscode editor has empty-blocked space in bottom area on editor.

Bellow screenshot: 
https://i.imgur.com/dOMOKCD.gif

I remove all plugins, restart setting and still have this problem.  
Anyone have idea, how I can fix it?

My version os vscode:

```
Version: 1.69.0 (Universal)

Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9

Date: 2022-07-07T05:28:41.511Z (2 days ago)

Electron: 18.3.5

Chromium: 100.0.4896.160

Node.js: 16.13.2

V8: 10.0.139.17-electron.0

OS: Darwin arm64 21.4.0

&#x200B;
```

**Comment by mxcdh** [comment]
btw:
```disable-hardware-acceleration": true```
&
```
code  --disable-gpu```

Not working on MacBook 16 M1.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/152816
