### ISSUE TITLE
New Git editor experience from code --wait and external terminals

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#154604]
v1.69 inteoduced the new commit editor experience, yet it is only integrated with the commint message input box, and the integrated terminal. Prior to it being introduced we used `code --wait` as the Git editor for code to be used in both the integrated terminal and external terminals. I think it makes sense to unify both experiences once the new commit editor is considered stable and polished enough. As it currently stands, you can't use the new experience from external terminals as far as I can tell.

**Comment by yanedev** [comment]
Does this bug still happen? If not, I suggest closing this post...
