### ISSUE TITLE
Scrolling behavior has changed dramatically

### ISSUE THREAD

**Issue by benignant** [microsoft/vscode#154665]
Issue Type: <b>Bug</b>

After I updated to 1.69, the scrolling has changed dramatically. I can't find any mention of a scrolling change in the release notes. I have confirmed that the issue is not present in 1.68.1, so something must have changed.

When switching from VS Code to any other maximized window and back, the scrolling becomes much more abrupt. This does not happen when switching away from VS Code to a window that is not maximized and back.

I made a screen recording, but it's hard to tell from a video. In the video, I am using a trackpad the same way both before and after.

1.  After opening VS Code, the recording starts.
2. I demonstrate normal scrolling. Note how each scroll slows down to a halt.
3. I switch to a different maximized window, and then I switch back to VS Code.
4. I demonstrate abrupt scrolling. Note how each scroll stops suddenly, rather than gradually.

[VS Code 1.69 Scrolling bug.webm](https://user-images.githubusercontent.com/19580651/178130128-07253018-fc16-4d92-af14-777518b48acd.webm)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (9.13GB free)|
|Process Argv|--crash-reporter-id 72b62142-e405-4989-b597-e4c6a82d4ee3|
|Screen Reader|no|
|VM|50%|
</details>

**Comment by jc9108** [comment]
i am having the same issue post-update. also using a touchpad same as before. editor scrolling is very stuttery (have tried smooth scrolling, does not help), and on the other hand scrolling the release notes page feels too fast/unresponsive compared to before.

**Comment by benignant** [comment]
Version 1.69.1 seems to have somehow fixed the issue, so I'm closing this for now.

@jc9108 Is it fixed for you too?

**Comment by jc9108** [comment]
yep, its good now. thanks

**Comment by alexdima** [comment]
fyi @deepak1556
