### ISSUE TITLE
Ctrl + backspace improvement for snake case

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#15468]
- VSCode Version: 1.7.1
- OS Version: Linux

When using Ctrl+backspace on code written in snake case, it doesn't stop on '_'  and deletes the hole variable/method.
It would be great to have this shortcut work for all cases:
- snake case: n_count
- camel case:  nCount 
- Kebab case: n-count (this one i found on the web, just adding it to the list)
etc

**Comment by ramya-rao-a** [comment]
You can add `_` to the `editor.wordSeparators` setting this would treat the words delimited by `_` as separate words.

**Comment by dfroze** [comment]
@ramya-rao-a Thank you, didn't know there was something like this

**Comment by ramya-rao-a** [comment]
@dfroze You are welcome :) Don't worry, I keep finding new things about VS Code every other day too!

**Comment by prattpratt** [comment]
but this still does not work for words in camel case names

**Comment by ramya-rao-a** [comment]
cc @alexandrudima @rebornix
