### ISSUE TITLE
Does the VSCode support such debug situation: "Python script call c function, and we want to debug this c function"?

### ISSUE THREAD

**Issue by xiaoxiongli** [Microsoft/vscode#15461]
- VSCode Version: 1.7.1
- OS Version:Ubuntu 15.04

Steps to Reproduce:

1. in launch.json i set like this:

        {
            "name": "C++ Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "${workspaceRoot}/example.so",
            "processId": "${command.pickProcess}",
            "linux": {
                "MIMode": "gdb"
            },
            "osx": {
                "MIMode": "lldb"
            },
            "windows": {
                "MIMode": "gdb"
            }
        }

2. And then we run a python script which will call a C function writen in the example.so

3. We attach the python script's process and set a breakpoint in the example.cpp

I hope that it can break in the line which i set a breakpoint, but it is not. So i feel confuse that does the VSCode support such situation: "Python script call c function, and we want to debug this c function"?

**Comment by ramya-rao-a** [comment]
@xiaoxiongli 
This would be a question for the C++ extension being used for debugging. Which extension are you using?

@weinand Any insights before moving this to extension repo?

**Comment by weinand** [comment]
@ramya-rao-a yes, this is a question for the C++ extension.

**Comment by ramya-rao-a** [comment]
@xiaoxiongli Please open an issue in the repo of the extension that you are using for C++ debugging
