### ISSUE TITLE
There are two color blocks displaying before the text

### ISSUE THREAD

**Issue by awxiaoxian2020** [microsoft/vscode#154688]
Does this issue occur when all extensions are disabled?: No

About information
```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:48:58.283Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```
![issue](https://user-images.githubusercontent.com/69554233/178144963-a5948f3b-2e8f-4fa6-9b17-f0152b1582d8.png)

**Comment by connor4312** [comment]
Does this occur when you run with **Disable All Installed Extensions**?

**Comment by awxiaoxian2020** [comment]
> Does this occur when you run with **Disable All Installed Extensions**?

I found it's caused by `Language support for Vue 3` Extension, I will look into it.
