### ISSUE TITLE
Customize visibility of command center & titlebar elements in full screen mode

### ISSUE THREAD

**Issue by OpatrilPeter** [microsoft/vscode#154650]
Without using the new Command Center feature, title bar area is hidden in full screen mode.
Command Center does not respect that and is active always, unconditionally taking up more screen space.

Additionaly, the titlebar area offers less utility than in conventional mode despite taking same space, as the usual menus and buttons aren't rendered.

I'd love to see a option to toggle Command Center off in the full screen / zen mode and an evaluation if not rendering menus etc. while the space for them is already there is truly intended.

**Comment by jrieken** [comment]
related/same https://github.com/microsoft/vscode/issues/154422

**Comment by OpatrilPeter** [comment]
The October 2023 update added an option for showing activity bar horizontally on the top, with profile and config buttons unconditionally part of the title bar. They suffer from same problem - with this activity bar layout, we can't hide titlebar area in fullscreen. I'd consider adding an option to keep showing these buttons in the activity bar area if more systematic solution to title bar element visibility isn't on the table.

**Comment by benibenj** [comment]
You can hide the title bar when in full screen when setting `window.customTitleBarVisibility` to `windowed`
