### ISSUE TITLE
File completer should score contiguous matches higher

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#15474]
Here's an example:

<img width="678" alt="screen shot 2016-11-14 at 13 11 12" src="https://cloud.githubusercontent.com/assets/50314/20276811/e8b7bd8a-aa6b-11e6-8188-78c294ce5efd.png">

The file `cmd/gradient/main.go` is scored lower even though the text I typed matches contiguously. The top matches have matched random characters in other file names which seem to have accidentally have bumped their score up, even though the matches make less sense.

**Comment by ramya-rao-a** [comment]
Closing in favor of #14727
