### ISSUE TITLE
command center UI is broken

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#154794]
![image](https://user-images.githubusercontent.com/1876302/178251055-f4a962d3-0b00-4527-ab62-9e993ca69514.png)
版本: 1.70.0-insider (system setup)
提交: e69176aafd282090e18f558c2b2ac9b3d5b606f5
日期: 2022-07-11T05:16:19.597Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.25151

**Comment by gjsjohnmurray** [comment]
Works OK for me. What steps do you take?

![image](https://user-images.githubusercontent.com/6726799/178253793-91c33820-b11e-4018-903c-0b200fa071a7.png)

Version: 1.70.0-insider (user setup)
Commit: e69176aafd282090e18f558c2b2ac9b3d5b606f5
Date: 2022-07-11T05:16:19.597Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by heartacker** [comment]
> Works OK for me. What steps do you take?
> 
> ![image](https://user-images.githubusercontent.com/6726799/178253793-91c33820-b11e-4018-903c-0b200fa071a7.png)
> 
> Version: 1.70.0-insider (user setup)
> Commit: e69176aafd282090e18f558c2b2ac9b3d5b606f5
> Date: 2022-07-11T05:16:19.597Z
> Electron: 18.3.5
> Chromium: 100.0.4896.160
> Node.js: 16.13.2
> V8: 10.0.139.17-electron.0
> OS: Windows_NT x64 10.0.22000

I don't know.
I just start vscode

That's all.

**Comment by heartacker** [comment]
> @heartacker was this fixed for you? I am wondering why you closed this.

https://github.com/microsoft/vscode/issues/154840

it is fixed
ᵗʱᵃᵑᵏઽ*♡
