### ISSUE TITLE
Integrated terminal does not work after an update

### ISSUE THREAD

**Issue by martinajiresova** [microsoft/vscode#154792]
Issue Type: <b>Bug</b>

Hi, my integrated terminal does not work after an latest update of VScode, it is crushing imidiately after I open it. I have MacOS Monterey 12.3

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by JeffReisch** [comment]
Solved it by going to an earlier version of the Python extension e.g. 2022.10.0 instead of 2022.11.0

**Comment by meganrogge** [comment]
Fyi @karthiknadig
