### ISSUE TITLE
Centered layout and merge editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#154738]
Just came across this code that conditionally leaves zen mode when side by side or diff editors are opened:

https://github.com/microsoft/vscode/blob/e69176aafd282090e18f558c2b2ac9b3d5b606f5/src/vs/workbench/browser/layout.ts#L1314-L1319

We probably want something similar when a merge editor is opened.

**Comment by bpasero** [comment]
* enable centered editor layout
* open a merge editor
* verify centered editor layout exits

**Comment by DonJayamanne** [comment]
Verified
