### ISSUE TITLE
VS Code stops responding to any keystroke after switching windows user and switching back

### ISSUE THREAD

**Issue by Silver-Fang** [microsoft/vscode#154759]
Type: <b>Bug</b>

1. Create a text file with any filename and open it. (You must name and save it. A new file named "untitled" won't reproduce the bug.)
2. Switch to another windows user. Do some random mouse clicks (must) before switching back.
3. Back to the original windows user. Then type in the text file. No characters appear in the file. VS Code does not respond to your typing.

More details:
- My problem is 100% reproducible, not intermittently.
- Switching to another app and back doesn't fix the problem.
- When my problem occurs, VS Code doesn't accept any keyboard input, including letters, directions, backspaces, spaces, or returns.
- You don't need a fast computer to trigger any race condition.
- `--disable-features=CalculateNativeWinOcclusion` can't fix my problem.
- When just returning from another Windows user or app, VS Code can respond to the mouse but not the keyboard. But after any keystrokes, VS Code doesn't even respond to the mouse anymore. The difference is that this kind of unresponsiveness to the mouse can be fixed by switching applications and then returning.
- (Update 20220803) This issue won't reproduce with DevTools window open. You must keep DevTools closed to reproduce it.
- (Update 20220803) This is not reproduceable on the web version of VS Code.

VS Code version: Code - Insiders 1.70.0-insider (e69176aafd282090e18f558c2b2ac9b3d5b606f5, 2022-07-11T05:16:19.597Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.91GB (15.03GB free)|
|Process Argv|--crash-reporter-id 91d36273-7689-4d19-a64e-fee0e43fddd9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.19
vscode-language-pack-zh-hans|MS-|1.69.7060951
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.242.0
remote-ssh|ms-|0.85.2022070815
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
markdown-preview-enhanced|shd|0.6.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30519256
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by alexdima** [comment]
Might be https://github.com/microsoft/vscode/issues/148661#issuecomment-1128933176

**Comment by Silver-Fang** [comment]
> Might be [#148661 (comment)](https://github.com/microsoft/vscode/issues/148661#issuecomment-1128933176)

Not likely.
- My problem is 100% reproducible, not intermittently.
- Switching to another app and back doesn't fix the problem.
- When my problem occurs, VS Code doesn't accept any keyboard input, including letters, directions, backspaces, spaces, or returns.
- You don't need a fast computer to trigger any race condition.
- `--disable-features=CalculateNativeWinOcclusion` can't fix my problem.

**Comment by deepak1556** [comment]
Does this still happen with latest insiders https://code.visualstudio.com/insiders/ ?

**Comment by Silver-Fang** [comment]
> Does this still happen with latest insiders https://code.visualstudio.com/insiders/ ?

Yes. Still happens. Not fixed.

**Comment by deepak1556** [comment]
Unable to repro with the steps provided on Windows 11 Build 22621, closing as not actionable.
