### ISSUE TITLE
Add schema support for jsconfig.json to TypeScript extension

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#15472]
- VSCode Version: 1.7.2

**Comment by mjbvz** [comment]
Looks like this has already been added to the JavaScript extension: https://github.com/Microsoft/vscode/blob/master/extensions/javascript/package.json#L101

I confirmed that we get validation for `jsconfig.json` files.

**Comment by dbaeumer** [comment]
Cool. Thanks.

**Comment by dbaeumer** [comment]
Verified that this is in `vscode\extensions\javascript\package.json`
