### ISSUE TITLE
Error: TreeError [FileExplorer] Data tree node not found: ExplorerItem

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154744]
From [error telemetry](https://vscode-errors.azurewebsites.net/card?ch=92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9&bH=38e51a6b-c40c-af96-1c89-9348ed5d19b6):

Error: TreeError [FileExplorer] Data tree node not found: ExplorerItem: 

 [at ie.getDataNode in src/vs/base/browser/ui/tree/asyncDataTree.ts:707:10](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L707:10) 

 [at ie.getRelativeTop in src/vs/base/browser/ui/tree/asyncDataTree.ts:685:40](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/tree/asyncDataTree.ts#L685:40) 

 [at <anonymous> in src/vs/workbench/contrib/files/browser/views/explorerView.ts:483:52](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L483:52) 

 [at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17) 

 [at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22) 

 [at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24) 

 [at <anonymous> in src/vs/base/browser/ui/scrollbar/scrollableElement.ts:191:19](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L191:19) 

 [at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L572:17) 

 [at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L774:22) 

 [at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/event.ts#L735:24) 

 [at k._setState in src/vs/base/common/scrollable.ts:389:18](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/scrollable.ts#L389:18) 

 [at k.setScrollPositionNow in src/vs/base/common/scrollable.ts:303:8](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/scrollable.ts#L303:8) 

 [at k.setScrollPositionSmooth in src/vs/base/common/scrollable.ts:309:16](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/common/scrollable.ts#L309:16) 

 [at l._onMouseWheel in src/vs/base/browser/ui/scrollbar/scrollableElement.ts:440:23](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L440:23) 

 [at HTMLDivElement.C in src/vs/base/browser/ui/scrollbar/scrollableElement.ts:357:10](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/base/browser/ui/scrollbar/scrollableElement.ts#L357:10)

**Comment by lramos15** [comment]
@joaomoreno Any idea here because there's no explorer stack involved this might be a tree issue

**Comment by smallp** [comment]
@lramos15 
You can try this. Enable fileNesting and select a file with nesting, control+c, the error would appear.
The chosen file should be in preview.

**Comment by joaomoreno** [comment]
@lramos15, third line in the stack frame:

[at in src/vs/workbench/contrib/files/browser/views/explorerView.ts:483:52](https://vscode.dev/github/microsoft/vscode/blob/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/src/vs/workbench/contrib/files/browser/views/explorerView.ts#L483:52)

**Comment by lramos15** [comment]
Thanks for the repro @yy0931
