### ISSUE TITLE
nie poprawne działanie emmetu

### ISSUE THREAD

**Issue by KrystianPV** [microsoft/vscode#154721]
Issue Type: <b>Bug</b>

Witam,
Emmet nie dizała prawidłowo, brak możliwości wykorzystania ! do stworzenia html5 , oraz nie mozna mnozyc elementów

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
/duplicate of https://github.com/microsoft/vscode/issues/154375
