### ISSUE TITLE
 Illegal argument: character must be positive

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#15475]
Issue Id: <b>74e45894-c881-6285-ce4c-11be050035d1</b><br /><br />*Versions* <br />- 1.7.1<br />-  9e7d70052908b633e0d4f71e70b26714bd1d2f10<br />*Stack* <br />Error: Illegal argument: character must be positive<br />[/vs/base/common/errors.ts#L134:9](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/errors.ts#L134:9)<br />[/vs/workbench/api/node/extHostTypes.ts#L97:9 (illegalArgument)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostTypes.ts#L97:9 (illegalArgument))<br />[/vs/workbench/api/node/extHostTypes.ts#L239:11](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostTypes.ts#L239:11)<br />[/vs/workbench/api/node/extHostTypeConverters.ts#L62:8](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostTypeConverters.ts#L62:8)<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L224:29 (toRange)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L224:29 (toRange))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L704:71 (provideCodeActions)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L704:71 (provideCodeActions))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L609:9 (callback)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L609:9 (callback))<br />[/vs/workbench/api/node/extHostLanguageFeatures.ts#L704:14 (_withAdapter)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/api/node/extHostLanguageFeatures.ts#L704:14 (_withAdapter))<br />[/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/workbench/services/thread/common/abstractThreadService.ts#L34:16 (apply))<br />[/vs/platform/extensions/common/ipcRemoteCom.ts#L269:39 (handle)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/platform/extensions/common/ipcRemoteCom.ts#L269:39 (handle))<br />

**Comment by ramya-rao-a** [comment]
@jrieken Related to #13862 ?
