### ISSUE TITLE
Regular expression breaks syntax highlighting

### ISSUE THREAD

**Issue by zaharazod** [microsoft/vscode#154706]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0
- OS Version: Debian unstable, Linux 5.18.0

Regular expression breaks syntax highlighting for remainder of the file.  The offending line (perl) is here:
```
if ((($var, $val) = /^\s*([_a-zA-Z0-9]+)\s*=\s*(.*)/) != 2) {
```

The *'s after each \s seem to be relevant; deleting one fixes the formatting (but deleting two breaks it again).

Steps to Reproduce:

1. Do above
2. See error

**Comment by RedCMD** [comment]
Looking at the highlighter code
It looks like regex strings can only come after `(`, `{`, `~`, `&`, `|`, `if`, `unless` or a newline.
in your example, the regex is after a `=`, which isn't supported
![image](https://user-images.githubusercontent.com/33529441/178209697-e1b9b981-ef4f-47c4-b1ae-6a2650314889.png)


As a temp work around, you can just surround the regex with brackets (or any of the other valid character)
![image](https://user-images.githubusercontent.com/33529441/178209700-906bb136-aa5e-421b-b642-4833d4fcf70c.png)


Or add `=` to the list of allowed characters
![image](https://user-images.githubusercontent.com/33529441/178210360-5658d202-e901-4ffe-aab6-07ad80213fb0.png)
![image](https://user-images.githubusercontent.com/33529441/178210367-47c8f228-608a-43ef-9c11-6d7adf2a547b.png)
https://github.com/textmate/perl.tmbundle/blob/a85927a902d6e5d7805f56a653f324d34dfad53a/Syntaxes/Perl.plist#L1174

Should make report to: https://github.com/textmate/perl.tmbundle

**Comment by alexr00** [comment]
Thanks for the investigation @RedCMD. I've opened an issue in the upstream repo: https://github.com/textmate/perl.tmbundle/issues/52
