### ISSUE TITLE
Unchecking "Uncaught Exceptions" in debugger does nothing

### ISSUE THREAD

**Issue by klick-barakgall** [Microsoft/vscode#15479]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.9.7|
|docthis|joelday|0.3.5|
|debugger-for-chrome|msjsdiag|2.2.2|

---

Steps to Reproduce:

1. Have some code that throws an exception.
2. Place breakpoint before the exception.
3. Uncheck "Uncaught Exceptions" from breakpoints panel.
4. Run program.

Despite "Uncaught Exceptions" being deselected VSCode still seems to break on it. Am I doing something wrong?

**Comment by ramya-rao-a** [comment]
> Despite "Uncaught Exceptions" being deselected VSCode still seems to break on it

Is it breaking on the breakpoint or at the line from where the exception is being thrown?

**Comment by ramya-rao-a** [comment]
Unchecking "Uncaught Exceptions" will only stop debugger from breaking when the exception is thrown. But in your case, it breaks on the breakpoint BEFORE the point from where the exception is thrown which is expected.

Closing this for now.

Please feel free to re-open this if you see debugger breaking on the exception
