### ISSUE TITLE
Remote 'origin' already exists when it does not

### ISSUE THREAD

**Issue by flipkickmedia** [microsoft/vscode#154778]
Does this issue occur when all extensions are disabled?: n/a Needs Git extension

- VS Code Version: 1.69.0
- OS Version: Windows 11 - Version 10.0.22000 Build 22000

Steps to Reproduce:

1. Initalise a new repository
2. Open git repo in sourcecode panel
3. Remote -> Add Remote
4. use origin as the remote name
5. Error Remote 'origin' already exists
6. Confirm origin doesn't exist `git remote get-url --all origin -> error: No such remote 'origin'`
7. Use terminal to add remote git remote add origin <url> 

You can then remove the origin remote using the Remote -> Remove Remote, and then try adding it using the UI and it still fails.

![image](https://user-images.githubusercontent.com/15732784/178227848-8cefe0a7-9489-4644-81c4-1d4f52959be5.png)

**Comment by flipkickmedia** [comment]
As it happens...Ive just gone through this process again...

1. delete origin using menu Remote->remove remote
![image](https://user-images.githubusercontent.com/15732784/208324677-4bd5f0cb-b1b8-441e-873a-32f4fefd9575.png)

2. add Remote
![image](https://user-images.githubusercontent.com/15732784/208324712-a4dddc2f-ba50-40dd-828e-57dfc01ab44a.png)

3. type in url, then origin
![image](https://user-images.githubusercontent.com/15732784/208324651-adf8d082-9f92-4901-b13f-75f18f6b7f2e.png)

**Comment by lszomoru** [comment]
@flipkickmedia, thanks for the update. I will further investigate this and will work on a fix.

**Comment by flipkickmedia** [comment]
great stuff! It seems that when you remove the remote, `git remote -v` shows that origin still exists, but has no URL. This would explain the origin already exists message so the failure appears to be in the remote removal.

**Comment by lszomoru** [comment]
@flipkickmedia, thanks for the additional information. I have tried to reproduce the issue with a simple repository on GitHub and I was unable to do so. When running the "Remove Remote" command, the removes were completely removed and I was able to successfully add back a new remote called "origin". 

VS Code uses two strategies to determine the list of remotes (in order of precedence):
1) Contents of the git config file in the repository
2) The output of the `git remote -v` command

Couple of things that I would like to ask you to try:
1) Can you see if you are able to reproduce the same with a GitHub repository?
2) Can you share the contents of the git config file after you have removed *all* remotes?

**Comment by flipkickmedia** [comment]
Ok so things to try:

1. use an ssh://git@github.com/<user>/<repo>.git formatted url
2. I'm inside a WSL instance, maybe this is the source of the issue?

config before removal
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = ssh://git@git.flipkick.media/entitywind.npm/svelte-boilerplate-edgedev.git
	fetch = +refs/heads/*:refs/remotes/origin/*

```
config after removal
```
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
```

So it seems that VS code is doing the correct thing.

After confirming remotes removed from config:
```
tshaw@laptop-x280:~/Documents/svelte-boilerplate-edgedev$ git remote -v
origin
tshaw@laptop-x280:~/Documents/svelte-boilerplate-edgedev$ git remote get-url --all origin
error: No such remote 'origin'
```

I've tried this on both a linux box and WSL instance and git returns the same results for both.  If as you say VSCode uses `git remote -v` to establish the remotes and git returns origin regardless of a url being set for origin, then this problem should happen for you.  If it doesn't what do you get when you do a `git remote -v`?

**Comment by lszomoru** [comment]
@flipkickmedia, thanks for the running the tests and for providing the additional information. Based on the provided data, it does look like VS Code correctly removes the "remote" section from the repository's git config file. Having said that I just checked and if we cannot find any [remotes in the repository's git config file](https://github.com/microsoft/vscode/blob/d957d2ca58ded0ab70ed7fadc8a1f6a36fcf2d1e/extensions/git/src/git.ts#L2222-L2223), we will always fallback to the output of `git remote -v`. 

I believe that what we have to understand is why `git remote -v` returns a remote even though all remotes have been deleted. The only think that I can think of is that somehow either the system or the global git config has a "origin" remote defined and that is what is being returns by the `git remote -v` command. Could you please run these commands and see if the config files contain the "origin" remote:
- `git config --system -e`
- `git config --global -e`

**Comment by flipkickmedia** [comment]
The worst part about that was it opening nano.....vim till I die.

Ok so yes there is config defined, but this config is required to prune from origin when I fetch.  This is another issue with VSCode, it ignores this config and doesn't prune but that aside (Ill open another ticket for that) this config is needed.

I'd suggest reworking the handling of remotes, and only when there is a URL should you complain about it existing.

```
[user]
        name = Tom Shaw
        email = tom@flipkick.media
[credential]
        helper = manager-core
[pull]
        rebase = false
[remote "origin"]
        prune = true
[core]
        fileMode = true
[url "ssh://git@git.flipkick.media"]
        insteadOf = https://git.flipkick.media
```
