### ISSUE TITLE
 Cannot read property 'incomplete' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#15476]
Issue Id: <b>409b4d37-61b8-544c-fe61-a24e91501d0c</b><br /><br />*Versions* <br />- 1.7.1<br />-  9e7d70052908b633e0d4f71e70b26714bd1d2f10<br />-  9550097782acdd2425241f16946da2fb3d32489f<br />*Stack* <br />TypeError: Cannot read property 'incomplete' of null<br />[/vs/editor/contrib/suggest/common/suggestModel.ts#L388:24 (incomplete)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/editor/contrib/suggest/common/suggestModel.ts#L388:24 (incomplete))<br />[/vs/editor/contrib/suggest/common/suggestModel.ts#L327:8 (triggerFromIncomplete)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/editor/contrib/suggest/common/suggestModel.ts#L327:8 (triggerFromIncomplete))<br />[/vs/editor/contrib/suggest/common/suggestModel.ts#L192:8 (onCursorChange)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/editor/contrib/suggest/common/suggestModel.ts#L192:8 (onCursorChange))<br />[/vs/base/common/event.ts#L155:12 (apply)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/event.ts#L155:12 (apply))<br />[/vs/base/common/eventEmitter.ts#L303:9 (func)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/eventEmitter.ts#L303:9 (func))<br />[/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents))<br />[/vs/editor/common/commonCodeEditor.ts#L888:12 (emit)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/editor/common/commonCodeEditor.ts#L888:12 (emit))<br />[/vs/base/common/eventEmitter.ts#L303:9 (func)](https://github.com/microsoft/vscode/blob/02611b40b24c9df2726ad8b33f5ef5f67ac30b44/src/vs/base/common/eventEmitter.ts#L303:9 (func))<br />

**Comment by jrieken** [comment]
We removed that code
