### ISSUE TITLE
Missing Feature: File parser, element index, function list.

### ISSUE THREAD

**Issue by wilferraz** [Microsoft/vscode#15471]
- VSCode Version: 1.7.1
- OS Version: Windows 7 SP1

I'm missing a feature that lists all the elements (or tags) in a file like function, variables, etc. in a similar way that is provided by the CTags/Sidekick plugins do for other code editors. This is especially useful when one is trying to understand an undocumented part of the source code, file structure or assembly package.

**Comment by ramya-rao-a** [comment]
Try Ctrl+Shift+O or just type `@` in the command palette. That should give you the file outline.

**Comment by wilferraz** [comment]
Thank you. Although the file outline is helpful, It is not the same thing I mentioned in the issue. The file parser can have a better interface to allow the user to navigate into the functions, structures and its memebers.

Sent from my iPhone

On Nov 15, 2016, at 5:54 PM, Ramya Rao <notifications@github.com<mailto:notifications@github.com>> wrote:


Try Ctrl+Shift+O or just type @ in the command palette. That should give you the file outline.

-

**Comment by ramya-rao-a** [comment]
In the file outline, when you select a function/struct/variable, you get navigated to the chosen function/struct/variable. 
You can try symbol search. Type `@` and then type the function/variable you are looking for.

**Comment by ramya-rao-a** [comment]
Also, #15222 also talks about something similar. I don't know what CTags/Sidekick has to offer, but can you chime in #15222 with a screenshot?

**Comment by wilferraz** [comment]
Yes, sure. I'll do it.
