### ISSUE TITLE
0.10.5 update causes editor focus resizing to break

### ISSUE THREAD

**Issue by stephenlaughton** [Microsoft/vscode#1547]
Before I updated to 0.10.5, whenever I focused a new editor with cmd+1,2,3 the editor in 'focus' would maintain a constant width that I set and the other open editors would resize to fit. I really enjoyed this behaviour as it meant I could maximize real estate for my focused editor and quickly jump between open splits. The behaviour is broken now and as a toggle focus between editors they all maintain whatever width they are set to. Is there any way to get the old behaviour back? I checked the settings.json for something obvious but nothing is popping out.

**Comment by bpasero** [comment]
@stephenlaughton can you provide some steps what you are doing? I cannot remember we changed something there....

**Comment by stephenlaughton** [comment]
@bpasero I did some digging around and it looks like this might be related to adding workbench.action.maximizeEditor as an available command ac9540de4f7775e27548c7142130ae2dfe1a2dd2.

The previous functionality with multiple editors open was:
1. Resize the editor that is in focus
2. Switch focus using cmd+1, cmd+2 or cmd+3
3. Whichever editor comes into focus adopts the size of the previously focused editor and the other editors shrink to accommodate.

I much preferred this behaviour.

**Comment by bpasero** [comment]
@stephenlaughton that action should not have an impact on the existing behaviour. VS Code has the concept of minimized editors. A minimized editor is an editor at its minimum width. You can resize one editor in a way that the other editors get minimized, or you use the action (Minimize other editors). Once in minimized state, switching with cmd+1, 2 or 3 will make the current active one maximized and the others minimized.

**Comment by stephenlaughton** [comment]
@bpasero you are totally right, I am beginning to think I dreamed up the behaviour I initially described. But in looking at the code I am wondering if it wouldn't be too difficult to enhance the minimized editors concept. I can see in [sideBySideEditorControl.ts](https://github.com/Microsoft/vscode/blob/f44a183bd5cb6510ad668fa5a3fc963eabd02973/src/vs/workbench/browser/parts/editor/sideBySideEditorControl.ts) that MIN_EDITOR_WIDTH = 170. 

Maybe it would be nice to be able to adjust this setting in settings.json? So on larger displays minimized editors could be more useful as open references for the editor you have in focus? Perhaps the MIN_EDITOR_WIDTH could be a percentage rather than a fixed value? 

I know this is a non-issue for many people so I understand if there are way more important features/improvements that need attention, but I have been thinking about how useful minimized editors could be if there was a little bit more control over them. Either way, thanks for replying to my previous posts.
