### ISSUE TITLE
Build failure: The requested name is valid, but no data of the requested type was found.

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#154783]
[Build failure](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=177590&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=6848c1bf-c5e8-44b5-b32e-23167b0fefbc):
```
ApplicationInsightsTelemetrySender will correlate events with X-TFS-Session 4abdd05b-4c4c-4da9-aec9-572701862cd0
Getting a pipeline cache artifact with one of the following fingerprints:
Fingerprint: `nodeModules|Windows_NT|eWVudKXrLiBRCDbjH0NyQGVy5TIA6VRze7vpFcsh0q4=`
ApplicationInsightsTelemetrySender correlated 2 events with X-TFS-Session 4abdd05b-4c4c-4da9-aec9-572701862cd0
##[error]The requested name is valid, but no data of the requested type was found.
Finishing: Restore node_modules cache
```

Maybe related: https://github.com/microsoft/vscode/issues/141862

**Comment by lszomoru** [comment]
yeah, this could be related. I will continue to monitor this and reach out to the Azure DevOps team if needed.

**Comment by chrmarti** [comment]
Same error: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=177636&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=66b5cdfd-9b63-4b37-9bec-cadbef21ab22

**Comment by lszomoru** [comment]
Thanks!
