### ISSUE TITLE
vscode.git when save some files, getCommitTemplate exec need more time

### ISSUE THREAD

**Issue by LittleControl** [microsoft/vscode#154735]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0
- OS Version: Windows 11 Pro latest

Steps to Reproduce:

1. toggle vscode developer tools
2. modify some files, then `ctrl + s` to save  
3. watch developer tools log, find a cupprofile
4. 
![image](https://user-images.githubusercontent.com/40530069/178178739-766ebd8f-2ae2-49d8-bb56-57ef3786c3b5.png)
5. open the cpuprofile, watch the info
6. 
![image](https://user-images.githubusercontent.com/40530069/178178849-1d323faf-4c18-474f-9cee-b7c0cc380bb4.png)
Maybe it's a bug. Or Someone can help me to solve it ?

Thanks in advance!

**Comment by lszomoru** [comment]
@LittleControl, apologies for not getting back to you on this. Are you still able to reproduce this issue with the latest VS Code Insiders build?
In recent releases we have made some improvements so some of the tasks that keep the data model up-to-date is being executed in parallel.

**Comment by lszomoru** [comment]
I will optimistically close this issue given the work that was done recently. 
In case you are still able to reproduce this issue please feel free to reopen the issue. Thank you!
