### ISSUE TITLE
Remove pixels from glyph that are below some threshold of difference to the background color

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#154702]
xterm.js issue https://github.com/xtermjs/xterm.js/issues/3892

This bad overlapping can occur sometimes:

<img width="84" alt="Screen Shot 2022-07-07 at 10 58 29 am" src="https://user-images.githubusercontent.com/2193314/177838927-fd4afb1c-993f-4ab6-b05c-1e80312c7ed0.png">

I think this is because the white pixels don't match the background exactly but are close enough to it that they should be treated as transparent.

cc @sbatten 

Related: https://github.com/microsoft/vscode/issues/154700

**Comment by connor4312** [comment]
@sbatten can you verify?

**Comment by Drerootz1** [comment]
Not a problem.
