### ISSUE TITLE
Support dependencies for VSIX extensions

### ISSUE THREAD

**Issue by balajikris** [Microsoft/vscode#15477]
- VSCode Version:
~~~
Version 1.7.1
Commit 02611b40b24c9df2726ad8b33f5ef5f67ac30b44
Date 2016-11-03T13:53:14.822Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
~~~

- OS Version: `Microsoft Windows [Version 10.0.14393]`

**Problem**:  specifying “extensionDependencies” in the extension manifest does not work as intended.

**Steps to Reproduce:**

1.  Open a simple VS Code extension project
2.  In package.json, specify `extensionDependencies`

In my case, I had this code:
```
    "extensionDependencies": [
        "samverschueren.yo"
    ]
```
3. package the extension as .vsix and import it in another instance of VSCode.

**Expected**: VSCode extension dependencies are installed
**Actual**: extension dependencies aren't installed.

Furthermore, if i uninstall my extension, VSCode asks if it should uninstall dependencies as well and if answered yes, extension dependencies are properly removed. This tells me I got the extension name `$publisher.$name` right. So, it seems to me that, uninstall flow works as expected and install does not. Unless, I'm missing something.

**Comment by ramya-rao-a** [comment]
@balajikris 
> Furthermore, if i uninstall my extension, VSCode asks if it should uninstall dependencies as well and if answered yes, extension dependencies are properly removed

How are the extension dependencies being removed if they were not installed with the extension which has dependency on it? Was the dependency already installed?

**Comment by balajikris** [comment]
No, I installed the dependency by hand to test my extension's functionality. While uninstalling mine, I noticed that it asks me for a bundle removal, so I tested that path and found that to work.

**Comment by balajikris** [comment]
I also looked at https://github.com/Microsoft/vscode-extension-samples/tree/master/extension-deps-sample and tried the examples suggested there and it didn't help. I still observe the same behavior.

**Comment by sandy081** [comment]
@balajikris Installing extension dependencies is not supported when installing as VSIX and not from market place.

**Comment by balajikris** [comment]
@sandy081 ah I see. thanks for clarifying that. For now, I'll try to test dependency installation in realtime after i upload my extension to the marketplace. I do appreciate you taking this into the backlog, as it just seems to be missing with the vsix workflow.

**Comment by stef-levesque** [comment]
Any update on this? I really wish 'extensionDependencies' would work with .vsix, as this is the only way we can deploy our tools at work.
