### ISSUE TITLE
Test: TerminalExitStatus.reason proposed API

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#154809]
Refs: #130231

- [x] macOS @aeschli
- [x] linux @connor4312
- [x] windows @luabud

Complexity: 2
Authors: @Tyriar, @meganrogge 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23154809%0A%0A&assignees=Tyriar,meganrogge)

---

Test this new extension API by checking `Terminal.exitStatus.reason` after exiting a terminal in different ways. The terminal doesn't necessarily need to be created by an extension

```ts
declare module 'vscode' {

	// https://github.com/microsoft/vscode/issues/130231

	/**
	 * Terminal exit reason kind.
	 */
	export enum TerminalExitReason {
		/**
		 * Unknow reason.
		 */
		Unknown = 0,

		/**
		 * The window closed/reloaded.
		 */
		Shutdown = 1,

		/**
		 * The shell process exited.
		 */
		Process = 2,

		/**
		 * The user closed the terminal.
		 */
		User = 3,

		/**
		 * An extension disposed the terminal.
		 */
		Extension = 4,
	}

	export interface TerminalExitStatus {
		/**
		 * The reason that triggered the exit of a terminal.
		 */
		readonly reason: TerminalExitReason;
	}

}
```

**Comment by luabud** [comment]
I wasn't able to generate the test unknown case but other than that, looked great to me :)
