### ISSUE TITLE
Code Action Light Bulb Only Shows up when Cursor Is On First Character of an Error

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#15488]
@dbaeumer and I have been working on adding code action support for TS, and we noticed that code action light bulb only shows when the cursor is on the first character of the error. Here's quick example:

![nov-14-2016 16-50-53](https://cloud.githubusercontent.com/assets/12821956/20288757/88c33660-aa8a-11e6-960f-8eeb2373783b.gif)

The lightbulb only shows when the cursor is touching the character where the error begins, in this case the `c` from `constructor`. Hitting command + period anywhere in the error can trigger the code actions, but I believe the lightbulb should also show up when the cursor is anywhere in the error.

**Comment by jrieken** [comment]
Like [this](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/quickFixModel.ts#L71). We compare start and end column but acknowledge that they are on different lines

**Comment by dbaeumer** [comment]
Thanks !
