### ISSUE TITLE
Searching with multiline regex not working properly

### ISSUE THREAD

**Issue by WEGFan** [microsoft/vscode#154826]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0-insider (9925e5d4d3d355758cd09d26868f0c12a0006828, 2022-07-11T12:20:21.684Z)
- OS Version: Windows_NT x64 10.0.19042

Suppose we have this text:

```
1
2
3
4
```

It can't be matched with original text using regex:

![](https://user-images.githubusercontent.com/7558201/178312817-3e28e597-d6e6-4c1f-be69-8262a4fe0bf9.png)

But if we join the first line and second line with a `\n`, it can be matched:

![](https://user-images.githubusercontent.com/7558201/178312639-f3fb5aa1-3c6c-4ef6-8413-31adadeec8b3.png)

**Comment by ArturoDent** [comment]
@roblourens 

For some background info, see https://github.com/microsoft/vscode/issues/36309#issuecomment-433579519 and https://github.com/microsoft/vscode/issues/62102#issue-375268259
