### ISSUE TITLE
Zooming causing "reference" indicator to become misplaced

### ISSUE THREAD

**Issue by EricJFisher** [Microsoft/vscode#15482]
- VSCode Version: 1.7.1
- OS Version: OSX

Steps to Reproduce:

1. Open any project in VS Code
2. Zoom in
3. Note Reference Indicators get shifted under the left panes

![screen shot 2016-11-14 at 3 04 31 pm](https://cloud.githubusercontent.com/assets/5638847/20281896/58f719b0-aa80-11e6-936f-e24c3bfdc065.png)

**Comment by kisstkondoros** [comment]
Duplicate of #15389

**Comment by ramya-rao-a** [comment]
Closing as duplicate. Please use the insiders build until the next VS Code update
