### ISSUE TITLE
JS Intellisense based on prototype method

### ISSUE THREAD

**Issue by fsmaia** [Microsoft/vscode#1548]
Just like Tern.js, would be nice if Intellisense could recognize JavaScript prototypal inheritance, as suggested in [UserVoice](https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/9535698-js-intellisense-based-on-prototype-methods).

Despite of multi-file injections (most times discovered only in runtime), static analysis is enough to solve single-file cases like in this example:
    
    function MyThing() {
        // ...
    }
    
    MyThing.prototype.example = function () {
        // ...
    };

    var thing = new MyThing();
    thing. // should suggest "example"

**Comment by jrieken** [comment]
This was done with the adoption of Salsa in the Feb release

**Comment by spacegoing** [comment]
Would you please clarify how to use this feature?
For example
``` javascript
    const b = { a: 234 };
    b. // nothing but "a"
```
I defined `b` as an object has property `"a"`. Intellisense only shows `"a"`, properties on `Object` are not shown. How to fix this?
