### ISSUE TITLE
Extensions fail to spawn subprocess 

### ISSUE THREAD

**Issue by kevinslin** [microsoft/vscode#154886]
Issue Type: <b>Bug</b>

## Repro
1. install [dendron](https://marketplace.visualstudio.com/items?itemName=dendron.dendron) using latest insider build
1. get error on startup

## Details
It looks there's been a regression when spawning a new shell in the latest insiders build.
Dendron (our vscode plugin), spawns a separate process to help index files. This is now failing with the following trace
```js
'DendronError: disconnect
	at ChildProcess.<anonymous> (/Users/kevinlin/code/dendron/packages/api-server/lib/utils.js:172:24)
	at ChildProcess.emit (node:events:390:28)
	at ChildProcess.emit (node:domain:475:12)
	at finish (node:internal/child_process:902:14)
	at processTicksAndRejections (node:internal/process/task_queues:78:11)'
```

Error is being thrown [here](https://github.com/dendronhq/dendron/blob/release/0.103.0/packages/api-server/src/utils.ts#L191).
Tried switching to `child_process.spwan` which results in the same issue.

Our users are seeing the same issue in the latest insider, see [Receiving "disconnect" message  · Issue #3212 · dendronhq/dendron](https://github.com/dendronhq/dendron/issues/3212).
I can confirm that launching dendron without spawning a separate process works as expected.

I also tried setting `ELECTRON_RUN_AS_NODE` prop as mentioned in https://github.com/microsoft/vscode/issues/151012 but looks like this is a different issue(?)

Extension version: 0.102.1
VS Code version: Code - Insiders 1.70.0-insider (Universal) (3104db414c8fedcf6e4493f14da7df0b7413853a, 2022-07-08T05:16:29.757Z)
OS version: Darwin arm64 20.5.0
Modes:

VS Code version: Code - Insiders 1.69.0-insider (668c538b8d2fec1258ed786ae212124d6d68023c, 2022-06-23T05:16:19.393Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 7, 10|
|Memory (System)|32.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id db45e752-8726-4584-899f-3d8ab21c2f18|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (53)</summary>

Extension|Author (truncated)|Version
---|---|---
string-converter|ada|0.1.2
project-manager|ale|12.6.0
ascii-tree-generator|apr|1.2.4
sidebar-markdown-notes|ass|1.0.4
markdown-checkbox|bie|0.3.2
LinkCheckMD|bla|0.3.1
vscode-url-title-resolver|cap|1.1.1
codestream|Cod|13.2.0
vscode-jq|dan|1.2.0
dendron-markdown-shortcuts|den|0.12.1
dendron-snippet-maker|den|0.1.6
nightly|den|0.102.5
docs-images|doc|0.0.10
typescript-notebook|don|2.0.6
gitlens|eam|12.1.1
macros|ged|1.2.1
vertical-limit|gen|1.9.1
gc-excelviewer|Gra|4.2.55
vscode-graphql|Gra|0.5.0
vscode-guid|hea|1.4.20
search-editor-apply-changes|jak|0.1.1
vscode-graphviz|joa|0.0.6
vscode-peacock|joh|4.0.1
open-in-vim|jon|0.6.0
character-position|kyr|1.0.0
vscode-uuid|lud|1.0.6
string-manipulation|mar|0.5.6
change-string-case|max|1.1.2
markdown-formatter|mer|0.9.7
wordcount|ms-|0.1.0
advanced-new-file|pat|1.2.2
emoji|Per|1.0.1
markdown-checkbox|PKi|1.8.0
vscode-css-peek|pra|4.2.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.8.0
elastic|ria|0.13.3
vscode-text-tables|Rom|0.1.5
vscode-paste-and-indent|Rub|0.0.8
Encryptor|Rus|0.3.1
partial-diff|ryu|1.4.3
markdown-link-expander|skn|0.2.1
markdown-tweet-expander|skn|0.1.1
vscode-fileutils|sle|3.5.0
timestamp-converter|Sta|0.0.1
code-spell-checker|str|2.3.0
s3uploader-vscode|tea|1.0.0
vscode-tidymarkdown|teh|0.0.5
graphviz-interactive-preview|tin|0.3.0
org-mode|too|0.5.0
remove-empty-lines|use|0.0.11
vim|vsc|1.23.1
gitdoc|vsl|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/154549
