### ISSUE TITLE
Shift + L key Error

### ISSUE THREAD

**Issue by dttan90** [microsoft/vscode#154884]
Issue Type: <b>Bug</b>

hi Team,
I get an error that Shift + L cannot be used for all my keyboards using windows 10.
The error encountered since updating new version.
Please check this error and fix it if it happens like I describe that.
Thank you.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 PRO 2400G with Radeon Vega Graphics (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|14.93GB (6.07GB free)|
|Process Argv|--crash-reporter-id 0855ae8c-25a2-4f0f-a35e-2f53d527384c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
aessoft-class-autocomplete|AES|0.1.0
html-class-suggestions|And|1.1.1
vscode-intelephense-client|bme|1.8.2
simple-react-snippets|bur|1.2.6
node-snippets|chr|1.3.3
npm-intellisense|chr|1.4.2
react-template|dab|0.1.1
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.0
vscode-npm-script|eg2|0.3.28
vscode-file-header|epi|1.0.8
node-version|fiv|0.0.1
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
html-snippets|gey|0.2.3
go|gol|0.34.1
cloudcode|goo|1.19.0
gc-excelviewer|Gra|4.2.55
vscode-power-mode|hoo|3.0.2
fontawesome-autocomplete|Jan|1.3.1
auto-comment-blocks|kev|1.0.1
rainbow-csv|mec|2.4.0
vscode-azureappservice|ms-|0.24.3
vscode-azureresourcegroups|ms-|0.5.4
vscode-docker|ms-|1.22.1
remote-containers|ms-|0.241.3
azure-account|ms-|0.11.0
live-server|ms-|0.2.12
vscode-react-native|msj|1.9.2
java-prettier-formatter|mwp|0.1.4
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
csv-to-table|php|1.4.0
java|red|1.8.0
format-html-in-php|rif|1.7.0
LiveServer|rit|5.7.5
css-auto-prefix|spo|0.1.7
indent-one-space|use|0.2.8
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.42.2022062902
vscode-java-dependency|vsc|0.20.0
vscode-java-pack|vsc|0.24.0
vscode-java-test|vsc|0.35.2
vscode-maven|vsc|0.36.0
vscode-icons|vsc|11.13.0
WebTemplateStudio-dev-nightly|WAS|0.7.2117301
ReactSnippets|xab|2.4.0
local-history|xyz|1.8.1
vscode-java-saber|You|0.1.2
json|Zai|2.0.2
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.

**Comment by dttan90** [comment]
I didn't find a solution for my case at the link https://github.com/microsoft/vscode/wiki/Keybinding-Issues

![image](https://user-images.githubusercontent.com/30839622/178427064-c78be35b-f929-4a1f-aad9-b33d9535b698.png)
But I type on VS and the result is nothing
![image](https://user-images.githubusercontent.com/30839622/178428097-906f38db-05ba-4e9e-8bab-b986895a2b49.png)

My OS and keyboard work fine. So is it the fault of VS Code?

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by dttan90** [comment]
I have used the Start Extension Bisect command and the result is still the same. I think I will close this issue because it can not be handled and takes too much of everyone's time. Thank you for the support' [gjsjohnmurray](https://github.com/gjsjohnmurray)
