### ISSUE TITLE
Wrong Comment Syntax for TSX/JSX

### ISSUE THREAD

**Issue by sheetalkamat** [Microsoft/vscode#15487]
From @daslicht on Microsoft/TypeScript-TmLanguage#355
When we open a ```*.tsx``` file,  VS Code shows TypeScript React in the bottom right corner.

If we now  highlight some text and call the comment shortcut, the block should be wrapped into the following:
```
	{/* ... */}
```

Currently there are just ```//``` inserted, which is wrong

**Comment by ramya-rao-a** [comment]
Duplicate of https://github.com/Microsoft/TypeScript/issues/9210
