### ISSUE TITLE
Syntax highlighting of HTML comments inside .md files fails with multi-paragraph or list-like comments.

### ISSUE THREAD

**Issue by KirkMunro** [Microsoft/vscode#15486]
- VSCode Version: 1.7.1
- OS Version: 10.0.14931

Steps to Reproduce:

1.  Open the attached markdown document that's in the zip file.
2.  Note how the syntax highlighting is broken inside of HTML comment blocks when you have multiple paragraphs or prefix any line with a dash.
[HtmlCommentHighlightingIssues.zip](https://github.com/Microsoft/vscode/files/590773/HtmlCommentHighlightingIssues.zip)

**Comment by mjbvz** [comment]
Thank you for the quick follow up. I believe #12696 fixed this recently by adding a special case for html comments.

![screen shot 2016-11-14 at 3 58 53 pm](https://cloud.githubusercontent.com/assets/12821956/20287744/38301d96-aa83-11e6-8d5c-1423515074e8.png)

The [latest insiders builds](https://code.visualstudio.com/insiders) should have this fix already, and the fix will become more broadly available in 1.8. Please let me know if something is still not rendering properly. 

Thanks.

**Comment by KirkMunro** [comment]
Excellent, thanks for letting me know!

--
*Kirk Munro *
Poshoholic, Microsoft MVP
Blog <http://poshoholic.com/> | Twitter <http://twitter.com/poshoholic> |
LinkedIn <http://ca.linkedin.com/in/kirkmunro> | GitHub
<http://github.com/KirkMunro> | Facebook
<http://www.facebook.com/#%21/kirk.munro>

Need a PowerShell SME for a project at work? Contact me
<http://poshoholic.com/contact-me/>!
