### ISSUE TITLE
Terminal sequences no longer working

### ISSUE THREAD

**Issue by andrewbranch** [microsoft/vscode#154863]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.70.0-insider
Commit: 9925e5d4d3d355758cd09d26868f0c12a0006828
Date: 2022-07-11T12:21:25.342Z (10 hrs ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

Something changed in Insiders between Friday and now: <kbd>⌥</kbd>+<kbd>backspace</kbd> and <kbd>⌘</kbd>+<kbd>backspace</kbd> now render their corresponding sequences in text rather than actually sending them, e.g. typing <kbd>a</kbd><kbd>s</kbd><kbd>d</kbd><kbd>f</kbd> <kbd>⌥</kbd>+<kbd>backspace</kbd> results in:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/3277153/178370584-2953869e-709c-4191-9bbe-92ed73c1b5d4.png">

Actually pressing <kbd>⌃</kbd>+<kbd>w</kbd> does delete a word. I haven’t changed any settings and the behavior I get from iTerm2 and Terminal.app hasn’t changed. VS Code’s terminal was working as I expect throughout last week.

**Comment by Tyriar** [comment]
I broke this in https://github.com/microsoft/vscode/pull/154567, will fix today
