### ISSUE TITLE
shellIntegration not working

### ISSUE THREAD

**Issue by danieltodor** [microsoft/vscode#154833]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.0
- OS Version: Archlinux (Linux x64 5.18.10-arch1-1)

I wanted to try out the shellintegration, so i enabled it with `"terminal.integrated.shellIntegration.enabled": true` but it does not worked. I use bash with a dead simple prompt `PS1='[\u@\h \W]\$ '`, other than this i just have a few alias in `.bashrc`.\
I tried it on an ubuntu VM with bash and it worked on it without any problem (exact same bash version).

Steps to Reproduce:

1. Turn on shellintegration
2. Close all integrated terminals, and then open a new one.

Tell me what log should i include.

**Comment by danieltodor** [comment]
I was able to get it to work by installing the [starship](https://github.com/starship/starship) prompt.\
I don\`t understand why it doesn\`t work with the above mentioned simple prompt.\
No error message in the terminal, nor in the debug level logs (as far as i can see), but it still doesn\`t work for me without starship.

**Comment by danieltodor** [comment]
I figured it out.\
In archlinux the PROMPT_COMMAND was set in `/etc/bash.bashrc` (by default), but it wasn\`t obvious because env not printed it out, so i thought it wasn\`t set.\
Moving it into a function like it\`s stated in the vscode docs had weird side effects for me, so i just "emptied" it in my .bashrc.

BTW this error message from vscode docs `Shell integration cannot be activated due to complex PROMPT_COMMAND: ...` wasn`t printed for me. Otherwise i would figured it out much earlier.

**Comment by Tyriar** [comment]
This is actually tracked in https://github.com/microsoft/vscode/issues/146197, thanks for reporting
