### ISSUE TITLE
Support folding / hiding an arbitrary region of the buffer

### ISSUE THREAD

**Issue by ihdavids** [microsoft/vscode#154869]
In emacs I can narrow a window to an arbitrary portion of a buffer. This is like a string view into a string. This feature is used for a ton of different things. Everything from facilitating user focus to some fancy buffer prettifying etc. 

My particular application is improving markdown and org mode visualization. I can hide the link and show just the link name in the buffer. Here is an example from Org Roam where the system is showing backlinks. The links are actually in org mode format:

[[HREF][NAME]] But are shown visually as you would expect in a web page as underlined text. Backspacing into the text stops the hiding and shows the link text again and of course emacs offers fancy tools for editing these.

![image](https://www.orgroam.com/img/screenshot.png)

This is a dynamic process, as soon as emacs recognizes that the text is a link it folds it for you which can really clean up a buffer.

Here is an example of someone using one of the ways of inserting a link other than typing that shows the link collapsed:
![image](https://i.stack.imgur.com/bFepF.gif)

In sublime text I can't quite do the same thing, I always have an ellipses ... but I can fold an arbitrary region. 
![image](https://user-images.githubusercontent.com/1059210/178375928-d93ed037-4da6-40da-aee4-eba2d2719d7d.png)
 
Here is a snapshot from [orgextended](https://packagecontrol.io/packages/OrgExtended) which is my plugin for sublime text for org mode. Because of the ... I can't quite hide the full link but I auto collapse them so they are not quite as visually jarring in the text:

[...[My Link]]

This is about as close as I can get today in sublime. I am working on extending [vscode-org-mode ](https://github.com/vscode-org-mode/vscode-org-mode) (my fork of it at least) and would really like to be able to clean up the buffer in a similar fashion at least or preferably take this even further and make org an amazing experience in vscode, but do not have any ideas on how I can proceed with my current understanding of the API.

I have autofolding and manual folding with tab working in my version of the plugin. It will automatically folder :PROPERTY: drawers and headings, which is a start. But I would love to take this much further and am blocked by the limitations of the folding and outline provider API I have been able to locate. Ideally I would love an API to fold arbitrary regions of a buffer and have control over whether or not there is a visual indicator (ellipses).

**Comment by aeschli** [comment]
In VS Code we don't have the capability to fold only part of a line. The feature request for that is https://github.com/microsoft/vscode/issues/50840

**Comment by moalamri** [comment]
@ihdavids I think an (extension I made)[https://github.com/moalamri/vscode-inline-fold] could make that possible (in a "hacky" way), you can implement the code in your plugin as I think such API to fold inline code won't be supported soon.
