### ISSUE TITLE
Update error telemetry website to add links to source code from deminified call stack

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#15483]
Currently, you can get the deminified call stack in the error telemetry website.
When you create a bug from there, the repro steps has links to the source code.
Without creating the bug, there is no direct way to open the source code from the error telemetry website making triaging just a little bit more harder

**Comment by ramya-rao-a** [comment]
Fixed with https://monacotools.visualstudio.com/Monaco/_git/VSCodeInternal/commit/19e2b0fc6c0bf825c7f42e10ae29c7875fa35575

**Comment by bpasero** [comment]
@ramya-rao-a this is very cool. I suggest however to `target=_blank` when clicking because otherwise you loose your error telemetry context.

**Comment by ramya-rao-a** [comment]
Done
