### ISSUE TITLE
Unlabelled Commit Type Button

### ISSUE THREAD

**Issue by justas2481** [microsoft/vscode#154800]
Issue Type: <b>Bug</b>

There is unlabelled button which has arrow down icon that expands the menu of three items - commiting (Commit, Commit & Push and Commit & Sync). Because of this, screen readers do not read / inform what does this button do. Also there is a problem with it's expand / collapse attribute, because this button isn't represented as expandable in the first place. After the first click, it opens the menu with items mentioned and then presents itself as collapsable.

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.15.0-39-generic

**Comment by lszomoru** [comment]
@justas2481, do you mind sharing a screenshot? Thank you!

**Comment by justas2481** [comment]
@lszomoru here you go:
<img width="960" alt="1" src="https://user-images.githubusercontent.com/34254634/178279845-d6c46a8d-5049-479e-bad2-22755fcf7834.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/34254634/178279897-8074fc5b-5ad9-4e86-960b-4dd806c013fd.png">

**Comment by lszomoru** [comment]
Thank you very much. I will take a look at improving the accessibility of the button this milestone.

**Comment by Dopeman31** [comment]
Fix

**Comment by lszomoru** [comment]
@Dopeman31, are you also experiencing this issue as well?

@justas2481, would it be possible for your the try the latest VS Code Insiders release (2022-07-13 or later), as I have made some improvements to the "action button" and I would like to make sure that all your concerns have been addressed. Thank you very much in advamce.

**Comment by lszomoru** [comment]
Closing this issue for now. Please feel free to reopen in case you still experience problems with the button. Thanks!

**Comment by justas2481** [comment]
@lszomoru It is fixed, sorry for delay, I was really busy.
