### ISSUE TITLE
3 way merge. You keep using that word...

### ISSUE THREAD

**Issue by ruffin--** [microsoft/vscode#154877]
I'm going to remove the bug template. This bug applies for "any version of VS Code with the merge editor that markets itself as a 3-way merge", and it's a bug with the description of the merge tool.

As far as I can tell, at best (at least in the [images in the release notes](https://code.visualstudio.com/assets/updates/1_69/merge-editor.gif)), you have what I might generously call a 2.5 way merge. It's one better than WinMerge in that you keep Theirs and Yours untouched as you merge in the middle, but that's not really what a 3-way merge is.

Why not? **Because you can't see the original ancestor Theirs and Yours have in common.** And that's really the most important part of the three-way merge, the ability to see the differences of both versions versus the common ancestor.

As someone has [helpfully put on Wikipedia](https://en.wikipedia.org/wiki/Merge_(version_control)#Three-way_merge)...
> A three-way merge is performed after an automated difference analysis between a file "A" and a file "B" while also considering the origin, or common ancestor, of both files "C"

And here's [a good explanation of why an ancestor is important from a SO answer about 3-way merges](https://stackoverflow.com/a/4129145/1028230):
> If you were doing a two-way merge (in other words, a diff), the tool could compare the two files, and see that the first and last lines are different. But how would it know what to do with the differences? Should the merged version include the first line? Should it include the last line?
>
> With a three-way merge, it can compare the two files, but it can also compare each of them against the original copy (before either of you changed it). So it can see that you removed the first line, and that your friend added the last line. And it can use that information to produce the merged version.

Or from another [great answer from VonC](https://stackoverflow.com/a/4130766/1028230):
> You may be asking what advantage a 3-way merge offers over a 2-way merge. Actually, there is no such thing as a two-way merge, only tools that diff two files and allow you to "merge" by picking chunks from one file or the other.
>
> Only a 3-way merge gives you the ability to know whether or not a chunk is a change from the origin and whether or not changes conflict.

2-way is like a baseless merge; you don't know what takes priority (TFS version control flashbacks! :scream:) In a two-way, you're stuck asking, "Did NewA match Old and NewB made all these changes? Or did NewA churn this code dangerously and NewB matches what we had before?" That seems to be what VS Code has now.

[kdiff3 has an excellent three-way merge UI](http://kdiff3.sourceforge.net/doc/screenshots.html):

> 3-way-merging is fully supported. This is useful if two people change code independently. The original file (the base) is used to help KDiff3 to automatically select the correct changes. The merge-editor below the diff-windows allows you to solve conflicts, while showing you the output you will get. You can even edit the output. This screenshot shows three input files being merged:
![sample screenshot of a 3-way merge from kdiff3's screenshots collection](https://user-images.githubusercontent.com/5659878/178385625-81622204-7458-4d79-9b58-55f211c1eeba.png)

You know you've got a three-way merge when you can see all three files _plus_ the merge result. The merge result doesn't count as "one way".

Thanks for attending my TEDx talk! :wink:

**Comment by gjsjohnmurray** [comment]
pinging @hediet

**Comment by hediet** [comment]
> As far as I can tell, at best (at least in the images in the release notes), you have what I might generously call a 2.5 way merge. 

I have to disagree here.
We take the base into account and compute the changes by diffing everything (even the result) against base.

Changes in the result file we don't understand are reset to base.
So basically, you start with base and click the checkboxes to combine the changes (relative to base) from both inputs.

There are also commands to open a diff editor between right/left and base.

> "Did NewA match Old and NewB made all these changes? Or did NewA churn this code dangerously and NewB matches what we had before?" That seems to be what VS Code has now.

The checkboxes clearly indicate that: When only one input has a change, the other one does not have a checkbox.

> at least in the images in the release notes

Please try out the merge editor before giving feedback.
