### ISSUE TITLE
Make the Spacing between Icons on the SCM Title Consistent

### ISSUE THREAD

**Issue by Alecton4** [microsoft/vscode#154883]
Is it possible to make the spacing between icons on the SCM title consistent when working on a multi-root workspace? Currently the spacing is different as shown below.

![image](https://user-images.githubusercontent.com/43232804/178397369-3ef49155-ff1c-41cf-a7f8-4c666783a148.png)

**Comment by lszomoru** [comment]
//cc @misolori, @daviddossett

**Comment by misolori** [comment]
This is intentional to make the spacing responsive as the view gets narrower and the repo/branch text is longer:

https://user-images.githubusercontent.com/35271042/178531582-ff74100a-3f09-4be2-8598-812bde5332c9.mp4

**Comment by lszomoru** [comment]
Thanks @misolori for the context. Apart from the inconsistency, I also see that some of the codicons get cut off when the spacing is being reduced (ex: create pull requests). I do not think that there is much to gain by reducing the spacing, so I would argue that we should not shrink the spacing. Are we doing the same in other action bars or just the "Source Control Repositories" one?

**Comment by misolori** [comment]
It's just the SCM view w/ the source control repositories, it's the only view that crams so much information. it gets more complicated when there are really long repository names and branch names:

<img width="371" alt="CleanShot 2022-07-12 at 08 57 24@2x" src="https://user-images.githubusercontent.com/35271042/178537695-50894b40-2ffe-4aa0-ac7a-3a552b04d5d2.png">

and if you want to get really picky, a really narrow view makes it hard to use:

<img width="196" alt="CleanShot 2022-07-12 at 08 58 01@2x" src="https://user-images.githubusercontent.com/35271042/178538062-8c3cd834-a30d-4af9-968e-7c8ba665f80d.png">


We've always had an issue with handling the responsiveness of this view and I a fine if we remove the special spacing adjustments, though it's not going to make a difference with the spacing issues overall.

**Comment by daviddossett** [comment]
IMO a formal setting for such a specific situation is overkill in this case.

If anything I wonder if all actions should switch to the condensed view rather than just the one that has the long title. Assuming the icon cutoff is fixed, that is.

**Comment by lszomoru** [comment]
I fully agree that this does not warrant a setting. Having said that, I would actually go the other way, and rather than making all action bars condensed, I would make the action bar in the Source Control Repositories view consistent with the rest of the workbench. I also belive that I read feedback in one of the issues that the condensed action bar in the Source Control Repositories view is an accessibility issue.

As far as usability of the Source Control Repositories action bar, I would argue that if there is not enough space rather than condensing the actions, we should move all action buttons into the `...` menu and only keep the repository, branch, sync.

**Comment by fitojb** [comment]
I think, if one sidebar pane compresses its icons at one given width, the other should too. That is the gripe I have with OP’s screenshot.

**Comment by Alecton4** [comment]
I would also like to ask if there is a way to completely remove those icons from the SCM title. This is useful for displaying the full repo names, especially when we have similarly named repos in a multi-root workspace as shown below.

![image](https://user-images.githubusercontent.com/43232804/190135629-a8de29e7-58fb-428f-8b8c-f5286ff43a2b.png)

**Comment by lszomoru** [comment]
Starting with VS Code 1.86, I have made the following changes:
* The action bar in the Source Control repositories view is not adaptive any more (it was the only one doing this)
* Users have the ability to hide all actions other than (checkout, and sync) independently in the "Source Control Repositories" and "Source Control" views
