### ISSUE TITLE
Terminal closes when executing command

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#154810]
Type: <b>Bug</b>

Clean insider install session without any extensions installed.

STR:
- Open Terminal
- Type yarn or npm – hit Enter

ER: Command executes

AR: Terminal closes and session is lost.

https://user-images.githubusercontent.com/8599/178287498-f8d51acb-db14-479a-81f4-19e353e03780.mp4

VS Code version: Code - Insiders 1.70.0-insider (9925e5d4d3d355758cd09d26868f0c12a0006828, 2022-07-11T12:21:25.342Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (14.87GB free)|
|Process Argv|--user-data-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/data-16-15-09 --extensions-dir=/var/folders/cq/2lmpsmc53m500qtgyyrlzhz80000gn/T//cleanvsi/ext-16-15-09 --log=trace --enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.2.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551cf:30291413
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
vscaac:30438845
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by rockingdice** [comment]
Same issue. I cannot run any scripts and it's blocking my work. 
control + shift + ` to create a new terminal will close immediately.

**Comment by meganrogge** [comment]
@rockingdice or @digitarald pls provide the info requested above and also does it happen if you use a diff't shell type too?

**Comment by rockingdice** [comment]
@meganrogge ...it's strange. After a nap, I restart the app and it's working now... All I did is following the steps of trace logging. Did you guys push another update to fix it?

**Comment by digitarald** [comment]
@meganrogge updated to latest insider and this is still happening. Fresh VS Code Insiders without settings and extensions. Tried with 2 folders.

Logs: https://gist.github.com/digitarald/ba96caedb3a732268271b3fea5c5e6be

**Comment by meganrogge** [comment]
@digitarald does it happen when using all shell types?

**Comment by digitarald** [comment]
iTerm2 also closes when typing `yarn`. But in my default Insiders profile (not the fresh one), executing `yarn` works. Why would 2 environments be affected but not the 3rd? Feel free to close this though if you think VS Code couldn't be involved.

**Comment by meganrogge** [comment]
what is the result of running `echo $PATH` in the good vs bad envs?

**Comment by digitarald** [comment]
`echo $PATH` closes the terminal, both VS Code and iTerm2 😭

PATH for the working VS Code installation is `/usr/local/opt/node@16/bin:/Users/digitarald/.poetry/bin:/usr/local/opt/python/libexec/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/usr/local/opt/node@16/bin:/Users/digitarald/.poetry/bin:/usr/local/opt/python/libexec/bin:/Users/digitarald/.cargo/bin:/Users/digitarald/miniconda3/bin:/Users/digitarald/miniconda3/condabin` (needs some spring-cleaning I see)

**Comment by meganrogge** [comment]
what happens if you type `bash` in the terminal?

**Comment by Tyriar** [comment]
> iTerm2 also closes when typing yarn

@digitarald if this happens in iterm as well something is definitely wrong with your environment/shell outside of VS Code. I've never seen this happen or reported before. If you turn on escape sequence logging via the command palette you might get some info if something gets printed immediately before it closes but I'm not sure what you could do outside that.
