### ISSUE TITLE
Ability to hide menu items

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#154804]
This is a (small) step towards https://github.com/microsoft/vscode/issues/9285 and about be able to hide/re-show menu items from toolbars. Very similar to how it works with view headers or the activity bar. This isn't about rearranging items, changing the conditions under which they show, or a textual configuration format (like keybindings.json)

**Comment by jrieken** [comment]
Happening here: https://github.com/microsoft/vscode/pull/154801

**Comment by jrieken** [comment]
We have explored this but aren't happy with the current solution. Because vacation times are started I will pull out the feature again and make it proper in August/September.

**Comment by phgmacedo** [comment]
Yes, it would be great to have this feature to avoid problems with extensions like I reported in [this comment](https://github.com/microsoft/vscode/issues/9285#issuecomment-1203112789).

**Comment by jrieken** [comment]
This is now done. You can right-click toolbar items to hide them. They either move into the overflow menu or hide completely. There is a global "Reset hidden menus" command and an optional "Reset Menu" context command
