### ISSUE TITLE
June 2022 Recovery 2

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#154956]
- [x] Create a milestone `June 2022 Recovery 2` @connor4312
- [x] Bump the version number @connor4312
- [x] [🔖candidate issues](https://github.com/issues?q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22June+2022+Recovery+2%22+)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch @connor4312 
- [x] Issues are verified on `stable` build and the `verified` label is added @connor4312 
- [ ] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch @connor4312 
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit @connor4312 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit @joyceerhl 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit @connor4312
  - [x] Windows ARM64 @sbatten 
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS @roblourens 
    - [x] Universal
    - [x] Intel 
    - [x] Intel server 
    - [x] Apple Silicon @kieferrm 
  - [x] Linux x64 
    - [x] deb @connor4312 
    - [x] rpm @rzhao271 
    - [x] archives @rzhao271 
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) @connor4312 
  - [x] Linux server @rzhao271 
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
- [x] Publish website **@gregvanl**
- [x] Publish stable build @connor4312
- [x] Create an official release @connor4312
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) @connor4312

**Comment by teoelena** [comment]
i still have the same isuess like before the Version: 1.69.2

here is the proof

![image](https://user-images.githubusercontent.com/109028310/179617647-4e69e569-894f-4893-b3c0-fdb8a5af8931.png)
![image](https://user-images.githubusercontent.com/109028310/179617656-0590ebe5-9ce5-4ee2-86e1-2a3b900df55c.png)
![image](https://user-images.githubusercontent.com/109028310/179617676-621ae1f9-f9c6-4fcd-a2a7-3f45eea2a526.png)
I'm no longer getting autocomplete suggestions either

ty
