### ISSUE TITLE
Check and clean up backup workspaces that don't have any files backed up on launch

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15499]
Since the storage for backup workspaces is independent from the actual backups inside that workspace, I think we need to be smarter about when to open a window for backups to restore. 

Today upon first startup we basically open a window for each of:

`const workspacesWithBackups = this.backupService.getWorkspaceBackupPaths();`

We only check if the backup workspace still exists but I think we also should check if it has backups or not. If not, it should be deleted.

I think this will be a more resilient experience in cases of random crashes where a backup workspace might get ouf of sync with its backups.

**Comment by Tyriar** [comment]
> We only check if the backup workspace still exists but I think we also should check if it has backups or not. If not, it should be deleted.

This clean up (deleting the workspace's backup folder) is done during on window is closed, this is done in `IBackupFileService.discardAllWorkspaceBackups`, called from `IBackupService.cleanupBackupsBeforeShutdown`.

Wouldn't you still want to restore a crashed workspace even if it didn't have backups to restore? It would be inconsistent if crash recovery worked differently depending on whether file(s) were dirty or not?

**Comment by bpasero** [comment]
My only concern was that I see a chance that we open workspaces because we think it contains backups, even though that is not the case. While we try to clean up backup workspaces, there can always be a case of a stale backup workspace entry that does not have any backups (thats just reality if you talk to a file system and not a DB without transactions).

So I was thinking: why not guard against this case by doing another check if the backup workspace contains entries after all.

**Comment by Tyriar** [comment]
Probably a good idea to make sure there, this may cause crash recovery to not be consistent based on if the workspace was dirty though.

**Comment by bpasero** [comment]
@Tyriar can you explain the thought you have on inconsistency with an example to me, I am not sure I follow.

**Comment by Tyriar** [comment]
I always envisioned a prompt after a crash asking if you want to restore (mainly to avoid a relaunch loop if it crashes due to the workspace characteristics). Thinking about it a bit more, I haven't seen any code that handles crashes on the main process. If the main process knew a particular window crashed then this could be handled easily there.

**Comment by bpasero** [comment]
We have this and show a dialog: https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/windows.ts#L778

However I noticed that the reload button in most cases does not work if the window is crashed. This seems like an upstream issue to me.

**Comment by Tyriar** [comment]
https://github.com/Microsoft/vscode/issues/15571 seems to be caused by performing actions too quickly such that the backup dir is not cleaned up properly at the end.

**Comment by Tyriar** [comment]
@bpasero the file already changed too much so I had to find it manually. FYI if you press <kbd>y</kbd> when viewing a file in github, the URL will get pinned to a commit.

That removes my only concern with doing this confirm/cleanup :+1:

**Comment by bpasero** [comment]
@Tyriar I suggest to just do the following: when the backup main service is created, do the checks: you already load the JSON into memory, just also check that each backup folder has contents. That way, it is absolutely clear that `getWorkspaceBackupPaths()` returns something that is not stale and we do not have to add the cleanup logic to the `windows.ts` where logically it does not belong. Put logic that only the backup service knows into the backup service. Also has the additional benefit of making this easily testable 👍
