### ISSUE TITLE
No longer auto-focus the save file window after the first time

### ISSUE THREAD

**Issue by TonyXia2001** [microsoft/vscode#154966]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.1
- OS Version: Ubuntu 20.04.4 LTS

Steps to Reproduce:

1. Open vscode
2. Ctrl + n to open a new file
3. Ctrl + s to open the save window
4. Esc to close the save window without saving the file
5. Ctrl + s to open the save window again, the save window always appears behind the editor itself

I believe this bug exists in vscode version 1.68 as well. It still worked in version 1.67.

**Comment by boltex** [comment]
I also encountered this bug. I wrote an extension that pops up the save-as dialog, and it sometimes appear behind.
