### ISSUE TITLE
Intellisense not working correctly

### ISSUE THREAD

**Issue by ammarsabir26** [Microsoft/vscode#15497]
![working](https://cloud.githubusercontent.com/assets/12556439/20294750/6be66542-ab22-11e6-8a1e-b52ccb2ea19f.png)
![not working](https://cloud.githubusercontent.com/assets/12556439/20294751/6becc342-ab22-11e6-8e28-301a39c75c25.png)

- VSCode Version:
- OS Version:

Steps to Reproduce:

1.  I just installed c# 1.5.1 and withing time span of every 5 seconds . i am facing this issue , intellisense works for couple of seconds and then automatically gets disabled some how.
It goes off usually when i am about to edit a saved file.
2. You can see the attached screenshots when it is working and when it is not

**Comment by ramya-rao-a** [comment]
As mentioned in the other issue that you logged #15495, intellisense comes from the C# extension. Please log an issue in the repo for the extension.
