### ISSUE TITLE
Right click 'Find in workspace'

### ISSUE THREAD

**Issue by entonio** [Microsoft/vscode#15490]
As a user I'd like to be able to select a word, right-click on it, choose 'Find in workspace' and have VSCode put the word in the 'Find in files' text field and immediately perform the search for it.

This would work like in Xcode.

Currently, I have to select the word (mouse task), then cmd+shift+F (keyboard task), then enter. That's not optimal for repetitive use.

**Comment by ramya-rao-a** [comment]
@sandy081 Would this be a feature request or an extension candidate?

One more thing I found is that ctrl/cmd+shift+F only works if the word is explicitly selected either by dragging using mouse or using shift + arrow.  
If we just have the cursor on a word,  ctrl/cmd+shift+F does not pick up the word.

**Comment by sandy081** [comment]
IMO this is an extension candidate. 
User can already get this behaviour (only through mouse) by 
- Select text in the editor
- Click on `Edit` menu
- Click on `Find in Files` 

User can also build an extension easily by registering following menu command

```package.json
"activationEvents": [
		"onCommand:myMenu.command.findInFiles"
	],
	"main": "./out/src/extension",
	"contributes": {
		"commands": [
			{
				"command": "myMenu.command.findInFiles",
				"title": "Find in Files..."
			}
		],
		"menus": {
			"editor/context": [
				{
					"when": "editorHasSelection",
					"command": "myMenu.command.findInFiles"
				}
			]
		}
	}
```

```
export function activate(context: vscode.ExtensionContext) {
	context.subscriptions.push(vscode.commands.registerCommand('myMenu.command.findInFiles', () => {
		vscode.commands.executeCommand('workbench.action.findInFiles');
	}));
}
```

**Comment by entonio** [comment]
The reason I didn't specify right away that this could be an extension was that the base product does include 'Find All References', which to me somewhat belongs in the same family.

Thanks for the extension code, @sandy081. This, however, doesn't perform the search, it opens the 'Find in files...' input field with the selected text, but the user still has to start the search manually. Is there a way to start the search automatically? I couldn't find an API for that (admittedly, I'm new to this).
Also, if the 'Find in files...' input is in 'replace' mode, it won't be reset back to just 'find'. That's something I have no idea how to do either.

(Is there anywhere one can specifically ask for extensions rather than opening issues here?)

Thanks!

**Comment by ramya-rao-a** [comment]
@sandy081 Also what about the below?

> ctrl/cmd+shift+F only works if the word is explicitly selected either by dragging using mouse or using shift + arrow.  
If we just have the cursor on a word,  ctrl/cmd+shift+F does not pick up the word.

**Comment by sandy081** [comment]
@ramya-rao-a There is an already an issue tracking this - #15244
>
If we just have the cursor on a word, ctrl/cmd+shift+F does not pick up the word.

**Comment by sandy081** [comment]
@entonio 
1. There is no command/api to trigger search automatically
2. There is also no command to toggle/close the replace. It always remembers the previous state of Search/Find and shows/hides replace accordingly
3. You can search for extensions either in VS Code extensions view or in [Market Place](https://marketplace.visualstudio.com/VSCode). If you do not find for what you are looking you can always open an issue and we will help you.

Thanks

**Comment by entonio** [comment]
@ramya-rao-a when there is no selection and you right-click a word, Apple's Xcode automatically selects it (as well as showing the context menu). That's why I didn't even think of it, but yes, it would be nice (as a default behaviour for right-click and/or for selection-specific actions).

@sandy081 from your reply I gather there is no way to implement the desired behaviour (Xcode-like 'Find Selected Text in Workspace') via an extension?
- if it can't be done via an extension, then how can I place the feature request? This one has been closed.
- if it can be done via an extension, then what can I do about it? I've opened the issue here and it's been closed.

Thanks.

**Comment by sandy081** [comment]
@entonio Scope of the extension I suggested is to provide an action `Find in Files` as a context menu action in the editor when text is selected. 

If you need to trigger search automatically this needs a new command. If you are keen on building the extension, I would reopen for implementing the missing command. If you are interested you can also submit a PR for this.

Thanks.

**Comment by entonio** [comment]
AIUI then the desired behaviour cannot be implemented via an extension; that calls a bit into question its being closed as an extension candidate - a wontfix or leaving it open would seem a more logical option. The key part of this request is not so much 'how to have a context menu option to the existing Find in Files' as 'how to start it all with just one action, like Xcode does'.

To wit, the following seems to be needed in order to do this via an extension:
- (missing) Select words on right-clicking on them
- (existing) Open Find in Files with the selection
- (missing) Dismiss 'Replace' and 'Files to Include' if currently open
- (missing) Start search

You certainly don't have to find Xcode's feature great, it's just that this is the place for such requests.
