### ISSUE TITLE
Slight tweak to notebook toolbar actions

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#154986]
I've noticed that the notebook toolbar has a lot of actions that can make it hard to scan. I also noticed that some actions appear to be disabled when not available (like the interrupt action). Here are some minor proposals.

## Current
<img width="985" alt="CleanShot 2022-07-12 at 14 04 05@2x" src="https://user-images.githubusercontent.com/35271042/178595126-3990047c-733c-4092-8b80-805307f681f3.png">

## Proposal
<img width="987" alt="CleanShot 2022-07-12 at 14 05 11@2x" src="https://user-images.githubusercontent.com/35271042/178595180-2fcb12cd-0a0f-40e4-ac5c-6b27014dce59.png">

1. Rename "Clear Outputs of All Cells" to "Clear All Outputs"
2. Hide the "Interrupt" action when not available

**Comment by rebornix** [comment]
👍 both makes sense to me. "Clear All Outputs" is much easier to read.

A disabled action on the toolbar is not great, since users can't really do anything about it. Not sure if we hide it or merge it with "Restart" (making it a dropdown like what we did for the Run button on cells)

**Comment by misolori** [comment]
Related to this is sticking to the principle of only showing actions when they are available instead of showing them as enabled/disabled https://github.com/microsoft/vscode-jupyter/issues/9912
