### ISSUE TITLE
Don't extend or instantiate `MenuItemAction`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#154948]
The [MenuItemAction](https://github.com/microsoft/vscode/blob/56ae202f830e1c98221e2842d189c18434d75e45/src/vs/platform/actions/common/actions.ts#L385)-object is the action-world representation of menu items, e.g menus return `MenuItemAction`-instances. The objects aren't meant to be subclassed or instantiated outside the menu-world. 

Instead menu-contribution or, better, `registerAction2` should be used. Bogous usages that need cleanup

- [x] src/vs/workbench/contrib/notebook/browser/controller/editActions.ts @rebornix  @roblourens 
- [ ] src/vs/workbench/contrib/terminal/browser/terminalMenus.ts @Tyriar @meganrogge 
- [ ] src/vs/workbench/contrib/terminal/browser/terminalView.ts @Tyriar @meganrogge

**Comment by Tyriar** [comment]
@jrieken I can't remember exactly why we went that route but the terminalView one is for this special button which has a menu on click, can be dragged into the editor and has a very dynamic title.

![image](https://user-images.githubusercontent.com/2193314/178543034-60019646-ec5e-4ca5-899c-dba17b14d99c.png)

Should that be achievable using menu contributions or `registerAction2`?

**Comment by jrieken** [comment]
> Should that be achievable using menu contributions or registerAction2?

Yeah, that should be possible. The way to achieve is the use of a special [IActionViewItemProvider](https://github.com/microsoft/vscode/blob/764d22738fcdeaa7b02b384f2d8e67f47e47d115/src/vs/base/browser/ui/actionbar/actionbar.ts#L27). They allow to do special rendering of `IAction`-instances and infrastructure to plug a view item provider should be available everywhere. The birds eye view is: `Action2` is the domain model, `IAction` is the view model, and `ActionViewItem` is the rendering logic of the former
