### ISSUE TITLE
Clicking in the scrollbar gutter in the side panel causes light show

### ISSUE THREAD

**Issue by romainmenke** [microsoft/vscode#154906]
Does this issue occur when all extensions are disabled?: Yes/No

Yes

- VS Code Version:

```
Version: 1.69.0
Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
Date: 2022-07-07T05:28:46.408Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
```

- OS Version:

CPUs | Apple M1 (8 x 24)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 16.00GB (0.08GB free)
Screen Reader | no
VM | 0%

Steps to Reproduce:

1. Search in extensions
2. Click the scroll gutter

https://user-images.githubusercontent.com/11521496/178446201-c05f140d-ae50-4c07-924b-bd3a16be0039.mov

**Comment by sandy081** [comment]
Using the list widget underneath, hence assigning to @joaomoreno

**Comment by joaomoreno** [comment]
This happens because the list is paged and is loading each element from the network.

@misolori Want to provide a better loading animation here?

**Comment by misolori** [comment]
Can we do something simple and use the loading icon animation?

https://user-images.githubusercontent.com/35271042/187319794-f3ba95d0-c882-4612-ac27-ea58601efd5f.mp4

**Comment by joaomoreno** [comment]
What do you think @romainmenke?

**Comment by romainmenke** [comment]
This is much better!
Thank you for looking into this
