### ISSUE TITLE
Integrated shell is broken

### ISSUE THREAD

**Issue by evanliomain** [microsoft/vscode#154937]
Issue Type: <b>Bug</b>

My zsh shell integration don't work anymore in 1.69

I open a new terminal, and it closes itself just second after.

VS Code version: Code 1.69.0 (Universal) (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:41.511Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.77GB free)|
|Process Argv|--crash-reporter-id 16b3e1a8-512e-4606-b85a-49dba1a7a7fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.0.1
multi-cursor-case-preserve|Car|1.0.5
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.1
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
auto-rename-tag|for|0.1.10
gitlab-workflow|Git|3.47.2
vscode-postfix-ts|ipa|1.10.1
svg|joc|1.4.18
angular-file-changer|joh|0.0.4
copy-json-path|Mal|1.0.2
template-string-converter|meg|0.6.0
git-graph|mhu|1.30.0
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1101950301
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
abracadabra|nic|6.14.4
angular-console|nrw|17.18.7
advanced-new-file|pat|1.2.2
project-snippets|reb|0.5.0
export-this|rog|1.0.0
gitmoji-vscode|sea|1.1.2
vscode-fileutils|sle|3.5.0
vscode-stylelint|sty|1.2.2
even-better-toml|tam|0.16.4
lorem-ipsum|Tyr|1.3.1
change-case|wma|1.0.0
vscode-jumpy|wma|0.3.1
map-replace-js|Yuk|0.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdc:30486549

```

</details>

**Comment by Tyriar** [comment]
> zsh shell integration

Do you mean vscode's shell integration feature here? ie. setting `terminal.integrated.shellIntegration.enabled` to false fixes the problem?

**Comment by evanliomain** [comment]
Hi @Tyriar,
The 1.69.1 patch version **fixes** this issue.

Do not known much more about this.

Thanks for the answer.
