### ISSUE TITLE
Configuring launch.json

### ISSUE THREAD

**Issue by iflores782** [Microsoft/vscode#15494]
- VSCode Version: 1.7.1
- OS Version: mac os 10.12.1

Steps to Reproduce:
I'm teaching myself C#. I wrote a simple hello world, when I try to debug it says I have to change 'program' to the path to the executable file. The .cs file is in a vscode folder in my documents folder. Any help?

**Comment by ramya-rao-a** [comment]
@iflores782 VS Code does not support C# debugging out of the box. That is done via extensions. You must be using an extension to help you code in C# in VS Code. We suggest you open issues in the repo for that extension, as they will be able to help you better.
