### ISSUE TITLE
Localized keybindings mismatched

### ISSUE THREAD

**Issue by marinabilles** [Microsoft/vscode#1549]
The "navigateBack" command is listed in my config file as:

```
{ "key": "ctrl+alt+-",            "command": "workbench.action.navigateBack" }
```

I am using the German keyboard layout with Visual Studio Code. I get a tooltip over "ctrl+alt+-" telling me to press "ctrl+alt+ß" instead (the ß key of the German keyboard is at the position of the - key on the English keyboard)

However, the command I actually have to press in order to navigate backwards is ctrl+alt+-, using the - key of the German keyboard, which is somewhere else entirely.

Thus, the tooltip is incorrect while the key as it is stated in the config file is correct.

Edit: my operating system is Linux x64 (Ubuntu 14.04)

**Comment by alexandrudima** [comment]
I can reproduce the problem, but it needs an investigation inside node-native-keymap

**Comment by alexandrudima** [comment]
I have validated that we now (i.e. after PR #22894 aka #17521 -- in today's Insiders build) appear to behave correctly for this keybinding under the German keyboard layout on Ubuntu:

![image](https://cloud.githubusercontent.com/assets/5047891/24304623/4c5c10d4-10ba-11e7-975a-4ad4b4bc8893.png)
