### ISSUE TITLE
Make sure markdown links execute an ext-host `vscode.open` command always

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#154993]
I'm trying to use `vscode.open` with `DocumentLinkProvider`. At present, only the first argument of `vscode.open` (the resource) seems to be respected. The other arguments are ignored.

Here's an example extension that demonstrates this issue:

```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	// Open `abc.md` from workspace root and select a range in it
	const commandUriWithOptions = vscode.Uri.parse(
		createCommandUri('vscode.open', vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'abc.md'), {
			selection: new vscode.Range(2, 0, 5, 0),
		})
	);

	// Open `abc.md` from workspace root besides the current file
	const commandUriWithViewCol = vscode.Uri.parse(
		createCommandUri('vscode.open', vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'abc.md'), vscode.ViewColumn.Beside)
	);

	// Make sure basic command run on ext host side works
	//vscode.commands.executeCommand('vscode.open', vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'abc.md'), vscode.ViewColumn.Beside);

	vscode.languages.registerDocumentLinkProvider('markdown', {
		provideDocumentLinks: (doc) => {
			return [
				new vscode.DocumentLink(new vscode.Range(0, 0, 100, 0), commandUriWithViewCol)
			];
		}
	});
}

function createCommandUri(command: string, ...args: any[]): string {
	return `command:${command}?${encodeURIComponent(JSON.stringify(args))}`;
}
```

To repo:

1. Create `abc.md` in the root of your workspace. Add a few lines of content to it
1. Open another md file  and open it
2. Click on the link from the provider

**Expected**

This should open `abc.md` besides the current editor

**Actual**
`abc.md` is opened in the same view column

**Comment by mjbvz** [comment]
I believe the root cause is that this ends invoking the renderer version of `vscode.open`:

https://github.com/microsoft/vscode/blob/2c036d15d83916055d20c7f0d7ec6c867a6e2ef5/src/vs/workbench/browser/parts/editor/editorCommands.ts#L486

Instead of the one on the extension host that  supports all the additional arguments

**Comment by mjbvz** [comment]
I also tried using `_workbench.open` directly. That doesn't work well since we don't go through the ext host type conversions. This means that the `selection` argument in the first example doesn't work since it has the wrong shape

**Comment by jrieken** [comment]
This needs special handling, like done for tree views etc, but that also means extensions cannot (and should not) be able to control the opening details but that the user-gesture (ctrl+click vs normal click) determines the "to the side" behaviour

**Comment by bpasero** [comment]
Took me a while to understand. First of all, `vscode.open` is clearly supporting an argument to open to the side:

https://github.com/microsoft/vscode/blob/4404dc63561a286e13f9ba5a669e5403a367425a/src/vs/workbench/api/common/extHostApiCommands.ts#L381-L392

This particular issue seems to be around command links in a document (which I am not aware of how they work). If I understand correctly, these links execute on the renderer and not on the extension host and as such, the additional arguments are not supported:

https://github.com/microsoft/vscode/blob/4404dc63561a286e13f9ba5a669e5403a367425a/src/vs/workbench/browser/parts/editor/editorCommands.ts#L484-L495

Why can the renderer side not simply allow for the same options?

**Comment by jrieken** [comment]
> Why can the renderer side not simply allow for the same options?

Because those are API objects and no one transforms them into internal objects

**Comment by bpasero** [comment]
> but that the user-gesture (ctrl+click vs normal click) determines the "to the side" behaviour

It seems to me that Matt wants to always open to the side, irrespective to the user-gesture?

If so, I believe this is a feature request for document links to:
* either execute from the ext host side
* or to add simple arguments to the renderer side for this particular scenario that does not drag in API types

**Comment by bpasero** [comment]
Let's maybe sync the three of us in August.

**Comment by bpasero** [comment]
As discussed, the suggested fix is to call a `vscode.open` clone that ensures ext-host side execution and argument conversion.
