### ISSUE TITLE
How to change parameter hints windows size or enable auto wrapping?

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#154965]
### Discussed in https://github.com/microsoft/vscode-jupyter/discussions/10662

<div type='discussions-op-text'>

<sup>Originally posted by **GF-Huang** June 30, 2022</sup>
![image](https://user-images.githubusercontent.com/4510984/176818583-11a09598-9de8-4456-8ae9-d1ef94114601.png)

As you see, the hints window too small, which can not show all docs of `np.concatenate`. And it's not auto wrap the line.</div>

**Comment by rchiodo** [comment]
This would be controlled by VS code itself. The jupyter extension does not determine the height of the parameter hints.

**Comment by mjbvz** [comment]
Duplicate of #14165
