### ISSUE TITLE
Extension API: icon support in walkthroughs is inconsistent

### ISSUE THREAD

**Issue by shinypb** [microsoft/vscode#154963]
This is a bug in the [walkthroughs contribution point](https://code.visualstudio.com/api/references/contribution-points#contributes.walkthroughs).

In general, the extension API allows icons to be embedded in text by referencing them inside of `$(...)`. This functionality does not work consistently in the walkthroughs API.

Does this issue occur when all extensions are disabled?: N/A; this is a bug in the extension API

- VS Code Version: 1.69
- OS Version: macOS 12.4

Steps to Reproduce:

1. Create a walkthrough step in your extension, e.g.

		"walkthroughs": [
			{
				"id": "welcome",
				"title": "Example $(github)",
				"description": "See? The icon looks nice, doesn't it?",
				"steps": [
					{
						"id": "example-step",
						"title": "Example step",
						"description": "Example description",
						"media": {
							"image": "icon.png",
							"altText": ""
						}
					}
				]
			}
		]

2 Observe that the icon in the title (`$(github)` in the example above) renders correctly in the Open Walkthrough… quickpick list:

<img width="372" alt="Screen Shot 2022-07-12 at 10 21 08 AM" src="https://user-images.githubusercontent.com/41654/178554741-8854ad73-8c79-432e-8572-62330f2777b7.png">

3. Open up the walkthrough and observe that the icon is not rendered, and instead you see the literal string `$(github)`: 
<img width="508" alt="Screen Shot 2022-07-12 at 10 22 09 AM" src="https://user-images.githubusercontent.com/41654/178554820-0fa6cd62-2270-411e-80cb-d78f0be346b0.png">

**Comment by shinypb** [comment]
Yes, it still exists in 1.69.1.

**Comment by shinypb** [comment]
Thanks for the remarkably fast turnaround time, @lramos15—I appreciate you. 👏

**Comment by aeschli** [comment]
Still see this in
Version: 1.70.0-insider (user setup)
Commit: 9cf2fabdd600c7d8e3230803acb246405321e8dd
Date: 2022-07-27T05:16:37.759Z
OS: Windows_NT x64 10.0.22622

![image](https://user-images.githubusercontent.com/6461412/181366377-6c406644-e564-4154-9f53-3507dd08b1a0.png)
![Screenshot 2022-07-27 223734](https://user-images.githubusercontent.com/6461412/181367671-2b80fb6e-855e-4f3a-986c-ea2de53f35d6.png)
![Screenshot 2022-07-27 223814](https://user-images.githubusercontent.com/6461412/181367672-38a451a9-e9d6-4b95-882c-d13699d93050.png)


- generate a new TypeScript extension with `yo code`
- add the `walkthroughs` snippet from the issue description to the package.json

**Comment by lramos15** [comment]
I only fixed the icon in the place that it didn't work in the issue description, sound like I have a few more places to fix :)

**Comment by IanMatthewHuff** [comment]
LGTM in the menu, in the walkthrough title, and in a step.
<img width="984" alt="image" src="https://user-images.githubusercontent.com/812783/186499191-005c1d3a-a2ef-4c35-a96b-a51b0a2cc5d7.png">
