### ISSUE TITLE
Bug due to "c# 1.5.1"

### ISSUE THREAD

**Issue by ammarsabir26** [Microsoft/vscode#15495]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|
|csharp|ms-vscode|1.5.1|
|mono-debug|ms-vscode|0.11.0|
|omnisharp|ms-vscode|0.3.3|
|colonize|vmsynkov|1.0.1|

---

Two Bugs:

1. Recently i updated my vscode to c# 1.5.1 and i am facing jerks in my IntelliSense. Intellisense works for few seconds and then goes off. It is random and constant, works for few seconds then not and then again magically works. Same with the references shown above ,then appears and disappears
2. The second bug is , the number of references shown is not appearing properly. I can only see "erences" and the rest is being cut off from the left side.

**Comment by ramya-rao-a** [comment]
@ammarsabir26 

For the first issue, intellisense comes from the C# extension. Please log an issue in the repo for the extension.

For the second issue, which you have logged separately as #15496, the fix is in the insiders build. Please use that until then next VS Code update
