### ISSUE TITLE
Text jitter while typing

### ISSUE THREAD

**Issue by BTBMan** [microsoft/vscode#154935]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.69.0 (Universal)
- OS Version:Darwin x64 20.6.0

Steps to Reproduce:

![good](https://raw.githubusercontent.com/Edge-coordinates/PicBed/master/imgs_for_blogs/2022-02-14%2016-36-28_Trim.gif)

It happend caused by `default:replacePreviousChar`, When I use some like VSCodeVim extension, It use `default:replacePreviousChar` method inside.

It was fine before version 1.63.2.

[https://github.com/VSCodeVim/Vim/issues/7496](https://github.com/VSCodeVim/Vim/issues/7496)

**Comment by aiday-mar** [comment]
This should no longer happen with the setting `editor.experimentalEditContextEnabled` which should be available in the next Insiders release. This issue will be closed.
