### ISSUE TITLE
Terminal handles stdin when vs code is resized.

### ISSUE THREAD

**Issue by devOramaMan** [microsoft/vscode#155029]
Issue Type: <b>Bug</b>

GCC compiled programs return from scanf, getch etc (like for stdin io eol) when VS code GUI is receized. 

VS Code version: Code 1.69.0 (92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9, 2022-07-07T05:28:36.503Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2540M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.05GB free)|
|Process Argv|--crash-reporter-id 5e8b672d-750c-48e1-a055-193ab05c3f9e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.0
gitignore|cod|0.8.0
doxdocgen|csc|1.4.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.1.2
vscode-pull-request-github|Git|0.46.0
githd|hui|2.2.4
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.20
jupyter|ms-|2022.6.1101950301
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.10.8
cpptools-extension-pack|ms-|1.2.0
svg-preview|Sim|2.8.3
cmake|twx|0.0.17
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdf:30486550

```

</details>

**Comment by meganrogge** [comment]
not sure what you mean, could you provide an example or a gif that illustrated the problem?

**Comment by Tyriar** [comment]
Since this also happens in conhost I recommend reporting to https://github.com/microsoft/terminal as they maintain the backend we use to manage the processes. I tried here and I don't see anything getting sent when resizing, except for the pty resize event.
