### ISSUE TITLE
Syntax breaking

### ISSUE THREAD

**Issue by Pszek** [Microsoft/vscode#15508]
- VSCode Version: 1.7.1
- OS Version: 10.11.6 (El Capitan)

After ternary operators ES6 string templates tend to break syntax highlighting (like the one below):
![zrzut ekranu 2016-11-15 o 12 31 47](https://cloud.githubusercontent.com/assets/10253750/20304317/c30ae2c8-ab2f-11e6-8ae6-cfc3c28fa738.png)

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#357
