### ISSUE TITLE
Provide a meaningful binary-file preview and "diff"

### ISSUE THREAD

**Issue by Kroc** [Microsoft/vscode#15506]
Clicking on a binary file in the explorer should provide something better than an error page.

A 'pretty-print' preview of the selected file should appear, including:

- file creation / modifcation / access times, file size
- Any metadata attached
- An image preview and dimensions for image files
- An icon for executable files (perhaps even showing the different icon sizes embedded), as well as the exe-specific metadata (Version, Company, Description &c.)

Now this would _really_ useful if the same appeared when selecting a binary file in the changes panel. The two sides of the diff viewer would display the page described above, allowing you to see what metadata changed between versions.

**Comment by bpasero** [comment]
Works for me:

![image](https://cloud.githubusercontent.com/assets/900690/20831675/70c2ccc4-b886-11e6-8508-1d3c948c0d48.png)

Note that we will refuse to open images > 1 MB due to memory reasons.
