### ISSUE TITLE
Reloading window with dirty files shows save dialog

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15509]
I hope I did not break this, but when I reload the window with dirty files and hot exit enabled, I am getting prompted to save.

**Comment by Tyriar** [comment]
Was it an empty workspace? Can't repro on today's insiders or master?

**Comment by bpasero** [comment]
@Tyriar yes, reproduces in insiders for me:
* enable hot exit
* have a new untitled file with changes
* Cmd/Ctrl+R

**Comment by Tyriar** [comment]
Ah, this is Mac-specific due to it only triggering hot exit when you close all windows.
