### ISSUE TITLE
setting c_cpp_properities invalid

### ISSUE THREAD

**Issue by westfish** [Microsoft/vscode#15505]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|GBKtoUTF8|bukas|0.0.1|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|

---

Steps to Reproduce:

1.change the includePath in c_cpp_properties.json
2.use the new intelliense with a new includePath

sample:
original
![image](https://cloud.githubusercontent.com/assets/20476674/20300573/c69c1e0e-ab5a-11e6-8694-0924124737e0.png)

![image](https://cloud.githubusercontent.com/assets/20476674/20300584/d0ea53bc-ab5a-11e6-860b-62a9968b1a34.png)

now i change the includePath
![image](https://cloud.githubusercontent.com/assets/20476674/20300613/f82b5b9c-ab5a-11e6-8f6d-9eebc1e2d36f.png)

the intelliense  tell me the includepath is still the original path
![image](https://cloud.githubusercontent.com/assets/20476674/20300700/452099e4-ab5b-11e6-82e5-df7ca3a2c30c.png)

**Comment by ramya-rao-a** [comment]
Intellisense is provided by the extensions. Please log an issue in the repo of the corresponding extension that you are using for C++
