### ISSUE TITLE
Top Menubar Resizable feature

### ISSUE THREAD

**Issue by sujancse5bu** [microsoft/vscode#155082]
Issue Type: <b>Feature Request</b>

Previously, we could resize the height of the top menubar with changing the zoom level. 
But now this remains the same height. 
Please Please Please we need this feature badly.

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:48.474Z)
OS version: Windows_NT ia32 10.0.18363
Restricted Mode: No

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/153401
