### ISSUE TITLE
Untitled files restored from backup issues

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15500]
To restore an untitled file from a backup we currently just do this:

`this.textFileService.resolveTextContent(this.restoreResource)`

That however will take the configured workspace encoding (which can easily be UTF-16) and thus might cause a corrupt content to return. 

I suggest to use the same options as for restoring files.

**Comment by Tyriar** [comment]
I'll action this after the https://github.com/Microsoft/vscode/issues/14067 PR is merged to reduce reworks due to conflicts.

**Comment by Tyriar** [comment]
Fixing in https://github.com/Microsoft/vscode/issues/15514
