### ISSUE TITLE
Add horizontal scrolling support

### ISSUE THREAD

**Issue by dorianclay** [microsoft/vscode#155097]
Please add support for horizontal mouse scrolling! I often use the editor in split screen mode, so some lines are cut off. On the trackpad, I can scroll horizontally fine. However, on a mouse with horizontal scrolling, scrolling horizontally does nothing.

_Info:_
- VSCode Version: 1.69.1
- OS: Windows 11 22000.795

**Comment by akrea** [comment]
up this one - really annoying

**Comment by alexdima** [comment]
We react to all `scroll` events we receive. The problem is that we don't receive a `scroll` event from Chromium. There is nothing we can do on our side, there is no possible code change we can do since we're not receiving these scroll events.
