### ISSUE TITLE
 `TerminalOptions.iconPath` not consistently used

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/vscode#155071]
Does this issue occur when all extensions are disabled?: Probably

- VS Code Version: 1.70.0-insider (3104db414c8fedcf6e4493f14da7df0b7413853a)
- OS Version: Linux x64 5.18.5-1-MANJARO

Steps to Reproduce:

1. Download [this branch](https://github.com/microsoft/vscode-extension-samples/compare/main...pfitzseb:vscode-extension-samples:sp/iconPath-createTerminal) of vscode-extension-samples
2. Run the terminal-sample extension
3. Use the `Terminal API: Create Terminal With Icon` command and check where the custom icon is applied

![Peek 2022-07-13 15-39](https://user-images.githubusercontent.com/6735977/178748252-30a46dca-10b3-475f-9043-dd04afacd8ab.gif)

**Comment by isc-bsaviano** [comment]
I'm seeing this issue in 1.75.1. Is this something that is likely to be fixed? I'm trying to decide if it's worth using a custom icon if it's not going to render properly for the foreseeable future.

**Comment by isc-bsaviano** [comment]
@meganrogge Any updates on this?

**Comment by DavyLandman** [comment]
I was on VS Code 1.79.0 and it was still broken, but VS Code 1.80.2 seems to have fixed this.

I was using a svg icon, if that helps.

**Comment by isc-bsaviano** [comment]
I'm using an SVG as well and it works for me too on 1.80.2. What a nice surprise
