### ISSUE TITLE
Ctrl clicking a deep link from the terminal no longer highlights the right line/col

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155065]
Ctrl clicking an error from our selfhost build no longer sends me to the right location of the file. It simply opens the file and highlights position (0,0).

![image](https://user-images.githubusercontent.com/22350/178739819-2f8f4334-9581-4250-901b-4783eae0c228.png)

**Comment by meganrogge** [comment]
Pretty sure i've seen this too
