### ISSUE TITLE
Editor and terminal color disunity

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#155037]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.1
- OS Version: MACOS M1Pro 12.4

Steps to Reproduce:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/13031838/178693814-c664bb18-e0cf-4f96-8e85-f324358ff40f.png">

<img width="554" alt="image" src="https://user-images.githubusercontent.com/13031838/178694066-09de337b-9237-43e8-945a-7a033e00ca13.png">

<img width="559" alt="image" src="https://user-images.githubusercontent.com/13031838/178694206-88ffddae-1a7e-40ef-8c8a-ebb1d07176ac.png">

There are some light-colored blocks in my editor and terminal

**Comment by gjsjohnmurray** [comment]
Maybe #152816

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/152816
