### ISSUE TITLE
Finalize Profiles UX

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#155067]
I like the profile functionality, but don't like the profile selector at all. It's too prominent, confusing as it looks generic.

![image](https://user-images.githubusercontent.com/6461412/178699021-a54d2bca-2f0e-4e1c-bd2a-1b128d7a08de.png)

- I don't associate this with profiles, nor with settings. 'Default' is not enough, nor is the icon meaningful to me.
A better icon would be the settings gear icon

- The right side of the status bar is typically for workspace related information (git branch, warning.errors). Settings related information belong to the bottom of the activity bar.
- Instead of using the status bar, I suggest to use the settings gear in the activity bar. It should look different if a profile is active. Maybe a letter icon as an overlay (the first letter of the profile name, `T` for testing) or a short text below it. The rich hover should then show more information and would even some links to configure the profile.

- Don't show any information when in the default profile. IMO profiles are an advanced feature.

**Comment by sandy081** [comment]
> Don't show any information when in the default profile. IMO profiles are an advanced feature.

Default profile is shown only when you have more than one profile. You can always hide the profiles status bar entry in the default profile if you do not want default profile to be shown.

**Comment by daviddossett** [comment]
Thanks for the feedback—I agree that the status bar still doesn't feel like the aboslute correct place for this.

We have actually explored variations of that proposal re: the settings gear. Ignoring the actual styling of this (we were exploring giving users the choice to use an image) one obvious challenge here is the conflict with the update badge:

<img width="326" alt="CleanShot 2022-07-14 at 11 03 21@2x" src="https://user-images.githubusercontent.com/25163139/179051835-3f0c1a0d-5960-47ee-9a32-1e4278a75e9c.png">

@sandy081 I think it's worth digging into this one more now that I've had some time away from it. I think it would be a valid option if we can figure out a clean way to work around the update badge.

**Comment by daviddossett** [comment]
This is a really rough idea but it could be a unique activity entry just below the settings icon. 

<img width="387" alt="CleanShot 2022-07-14 at 12 05 59@2x" src="https://user-images.githubusercontent.com/25163139/179063368-55005249-9f36-4acc-9cce-1f7d2975f4f2.png">

We could use the first two letters if the profile name is a single word (e.g. CS50 -> CS). If there are 2+ words, we could use the first letters of the each words (e.g. Web Development -> WD). 

<img width="420" alt="CleanShot 2022-07-14 at 12 06 48@2x" src="https://user-images.githubusercontent.com/25163139/179063606-a8a8b196-923a-49f4-9107-63d5a0b01851.png">

Profile names with many words would eventually need to overflow (e.g. React Native Test Settings):

<img width="434" alt="CleanShot 2022-07-14 at 12 09 26@2x" src="https://user-images.githubusercontent.com/25163139/179063966-436d5fdc-d3f2-4952-8f2a-4b968817c860.png">

**Comment by aeschli** [comment]
Cool, looks good!
Maybe move it a bit closer to the gear so the appear as one?
I wouldn't use the overflow. Two (or a max of 3) letters will be enough to distinguish the profiles. Hovering over the marker would show the full name.

**Comment by daviddossett** [comment]
If they are separate elements, this is about as close as they can get given the activity bar item's footprint. Haven't yet found a clean way to integrate it with the settings gear without stomping on the update badge.

<img width="291" alt="CleanShot 2022-07-15 at 10 02 56@2x" src="https://user-images.githubusercontent.com/25163139/179272861-df17ff17-5c3c-45ff-922b-d13cb36b08d2.png">

I'm fine with the two letters 👍

**Comment by daviddossett** [comment]
Played around with this a bit more:

<img width="321" alt="CleanShot 2022-07-15 at 10 59 07@2x" src="https://user-images.githubusercontent.com/25163139/179283688-b78c5e05-7b0d-49d1-bfec-f8dfeafc0a5b.png">

With update badge:

<img width="357" alt="CleanShot 2022-07-15 at 10 58 49@2x" src="https://user-images.githubusercontent.com/25163139/179283702-52418317-378c-4442-b866-a8ea2b9be08d.png">

**Comment by daviddossett** [comment]
Presented some ideas at the ux sync. Here's where I've arrived:

- Adds special activity bar item below the settings gear
- Users can change the color of the item (see: terminal colors for similar experience)
- Themes can override color defaults (e.g. `profile.blue`)

https://user-images.githubusercontent.com/25163139/183989890-63a50ebf-06cd-454b-988b-d2d5bd46adfe.mp4

cc @misolori
