### ISSUE TITLE
Put the "Discard Changes" button on the left

### ISSUE THREAD

**Issue by programming2012** [microsoft/vscode#155004]
Hi
   On the "Source Control" Window, Put the "Discard Changes" button on the left of the file name or folder name.
   In the current situation, when you click to Open File or Stage Changes, it is easy to click on Discard Changes, resulting in misoperation

                Thanks

**Comment by lszomoru** [comment]
Thank you very much for your feedback. Placing buttons both before and after the folder/file name in a list is not possible given the current design system. Having said that, we can certainly look to see whether we can reorder the buttons that appear after the file/folder name.

//cc @misolori, @daviddossett
