### ISSUE TITLE
Markdown fenced blocks should be highlighted in a similar way to single line code blocks

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#155056]
When highlighting code inside markdown, single line code blocks are highlighted, but fenced blocks are not, unless they are a supported language, in which case only the contents are highlighted, which is inconsistent with single line blocks where the backticks are highlighted too:

![image](https://user-images.githubusercontent.com/150152/178728584-55d8db03-5f40-400e-a11d-66f9b2c39de9.png)

For a more consistent view, I think the triple backticks should always be highlighted, and if no language is provided then the contents should also be highlighted, eg:

![image](https://user-images.githubusercontent.com/150152/178728624-61112ded-502a-4a0b-820f-33a8dee9ea2b.png)

**Comment by mjbvz** [comment]
Closing this based on https://github.com/microsoft/vscode/pull/155057#issuecomment-1212596372

This is something a third party theme can easily customize (or you can even do it yourself with user settings). However it feels too drastic of a change as is for the built-in themes
