### ISSUE TITLE
[yaml] keys with hyphens break syntax highlighting

### ISSUE THREAD

**Issue by weevilgenius** [Microsoft/vscode#1550]
![yaml_screenshot](https://cloud.githubusercontent.com/assets/931455/11938450/c765958e-a7cf-11e5-958d-5cbf0ff3ecba.png)

Editing a yaml file which has a hyphen in an unquoted key name seems to break syntax highlighting for the value of that key

Tested in 0.10.5

**Comment by aeschli** [comment]
Reproduced. Snippet
```
----
test1  : dsd
test2  : abc-def
test-3  : abcdef
test-4  : abc-def
```

**Comment by aeschli** [comment]
This issue was moved to textmate/yaml.tmbundle#11

**Comment by hxlnt** [comment]
Noting that this applies not only to strings but also to negative numbers.

<img width="326" alt="screen shot 2016-07-14 at 5 20 06 pm" src="https://cloud.githubusercontent.com/assets/9647195/16857745/7049b428-49e7-11e6-9739-efe8d6ca7c15.png">
