### ISSUE TITLE
Interactive window needs to check notebook URI from execution state service

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#155092]
https://github.com/microsoft/vscode/blob/a1f2dae7b6fce98d68c7393bf64ceb632e98df59/src/vs/workbench/contrib/interactive/browser/interactiveEditor.ts#L151-L153

I just randomly noticed this - the notebookExecutionStateService is a global service and this event will be fired for any notebook. The event object has a notebook URI on it, and this handler needs to check that the event is fired for this notebook, otherwise executions in other notebooks with a cell handle overlap could affect this interactive window

**Comment by rchiodo** [comment]
Good catch. I'll look into it.
