### ISSUE TITLE
Cannot open webview in Firefox

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#155033]
1. Open insiders.vscode.dev
2. New Text file
3. Write some markdown
4. Markdown: Open preview

An error notification shows: "Error loading webview: Error: Could not register service workers: SecurityError: The operation is insecure.."
This doesn't occur in vscode.dev, only in insiders.vscode.dev.

**Comment by alexr00** [comment]
Error in console upon opening a webview:
```
Failed to register/update a ServiceWorker for scope ‘https://0ek3bbl1lmkc4n7falg65hlqlb313tdsphtuh3mm9virmtitlhs6.vscode-cdn.net/insider/052d5b0027f6c9d64c8ca35955cb5117ba94d5d7/out/vs/workbench/contrib/webview/browser/pre/’: Storage access is restricted in this context due to user settings or private browsing mode.
```

**Comment by alexr00** [comment]
I disabled cross-site cookie blocking, which is one of the standard privacy options that Firefox has turned on, and then it worked. Not sure if there's anything to be done here.

**Comment by pfitzseb** [comment]
It'd be cool if VS Code would show a notification when service workers are unavailable (due to whatever reason). Otherwise extensions with webviews silently (well, kinda) break and users are confused.

**Comment by mjbvz** [comment]
Duplicate of #142813

@pfitzseb We already do show an error in these cases
