### ISSUE TITLE
Pop-ups of "About" and "Check for updates" don't match the theme on VS Code/ VS Code Insiders. 

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#155013]
Whether I use VS Code or VS Code Insiders, the "About" or "Check for updates" popups do not match the theme. The background is always white and does not match the theme colors.

* VS Code Insiders:
![about-insiders](https://user-images.githubusercontent.com/24303680/178653802-2b62234a-226c-4145-940b-3303d51143a3.png)
![updaters-insiders](https://user-images.githubusercontent.com/24303680/178653816-5d2d0e4b-296a-4e84-9464-479fb1ff9fd4.png)

* VS Code:
![about-vs](https://user-images.githubusercontent.com/24303680/178654069-5a9cf0b1-b964-43d8-b2a3-e17f951bf9a8.png)
![updates-vs](https://user-images.githubusercontent.com/24303680/178653776-b041d724-8c50-491d-b409-0c63e98de4c5.png)

**Comment by tb0513** [comment]
https://tb0513.github.io/jump

**Comment by gjsjohnmurray** [comment]
`"window.dialogStyle": "custom"` will resolve the second case but not the first one.

**Comment by aeschli** [comment]
Yes, these are system dialogs, controlled by the OS.

**Comment by aeschli** [comment]
No changes planned. OS dialogs will be themed by the OS color settings
