### ISSUE TITLE
Snap Package missing GLIBCXX_3.4.22 (bundled libstdc++ version too old)

### ISSUE THREAD

**Issue by PixlRainbow** [microsoft/vscode#155094]
Issue Type: <b>Bug</b>

Python Jupyter extension requires GLIBCXX_3.4.22 in order to load dependency ZMQ. The Jupyter extension works fine without ZMQ for most use cases, but when environment variables are needed for certain Jupyter functionality, ZMQ is required (the alternative is restarting vscode). See https://github.com/microsoft/vscode-jupyter/issues/9774#issuecomment-1109149495

However, the copy of libstdc++ inside of a snap package cannot be updated except via a snap package update.

Related #147440 #147166 

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:28:29.328Z)
OS version: Linux x64 5.15.0-40-generic snap
Restricted Mode: No

**Comment by rchiodo** [comment]
@meganrogge does vs code update snap packages? Not sure we'd want to ship a new GLIBCXX in the VS code snap package.

**Comment by PixlRainbow** [comment]
I had thought snapcrafters updated snap packages, but when I checked, the snapcrafters vscode repo was archived and the current version of the snap package (1.69.1) indicates vscode official as the point of contact.

**Comment by meganrogge** [comment]
I believe @joaomoreno would know that

**Comment by rchiodo** [comment]
Sorry I'm not really sure how snap packages work. 

Does the vscode process run isolated from everything else? As in all of the packages it would use are installed next to it? Or does it use packages already installed on the system?

I would expect the later, and if that's so, it would be up to the user to install a newer version of GLIBCXX

**Comment by rchiodo** [comment]
Oh looks like it's the former:
https://askubuntu.com/questions/787149/how-do-snap-packages-handle-shared-dependencies

So the libstdc++ has to be in the snap package itself.

**Comment by PixlRainbow** [comment]
The debug log seems to indicate it is loading `libstdc++.so.6` out of a sandboxed directory. (`/snap/core/current/lib/x86_64-linux-gnu/libstdc++.so.6`)

**Comment by rchiodo** [comment]
That sounds like the snap core package? 
https://snapcraft.io/core

Perhaps the core package on your OS doesn't support the needed libstdc++?

**Comment by rchiodo** [comment]
Oh no it's VS code's core package that would have to be updated. Similar problem here:
https://forum.snapcraft.io/t/vscode-glibc-6-needs-update/21088/3

**Comment by deepak1556** [comment]
Our current snap core is based on Ubuntu16.04 hence the `GLIBCXX` support is quite old, we have attempted to update the core version https://github.com/microsoft/vscode/pull/127320 but there are issues described in that PR which has put a pause on it. I will have to revisit the update at some in the near future but don't have any concrete timeline yet.

Python ZMQ can either statically link with `libstdc++` or build the module on an older toolchain `ex: centos7-devtoolset8` to lower the `GLIBCXX` requirement as an interim fix.
