### ISSUE TITLE
Feature Request: Option to sync cursor when using command `workbench.action.compareEditor.focusOtherSide`

### ISSUE THREAD

**Issue by boboRAY** [microsoft/vscode#155036]
When using commands
`workbench.action.compareEditor.focusPrimarySide`
`workbench.action.compareEditor.focusSecondarySide`
`workbench.action.compareEditor.focusOtherSide`
to switch between sides on diff view, the cursor will be at the position when last focused on that side.

It would be great to have an option to make the cursor to be synced on the same line (or maybe somewhere around if the line doesn't exist) when switching between two sides.

**Comment by Balastrong** [comment]
I'd like to give this a try, I'll submit a PR as soon as I'll have something to share :)

**Comment by boboRAY** [comment]
Thanks @Balastrong! 
Looking foward to see your PR 🙂

**Comment by ashutosh887** [comment]
I'm willing to work on this

**Comment by hediet** [comment]
Implemented in https://github.com/microsoft/vscode/pull/188291
