### ISSUE TITLE
can a feature disable?

### ISSUE THREAD

**Issue by Babailan** [microsoft/vscode#155069]
I wish you we can turn off some feature like source control so space complexity will improve for low end user.
we can manage source control on CLI if we want I think it's a great idea. even though I hide it's still running on background while im coding.

**Comment by lszomoru** [comment]
@Babailan, the source control functionality in VS Code is being powered by the `vscode.git` extension. If you switch to the "Extensions" viewlet, and you search for "@builtin" you will get a list of the built-in extensions. You can manually disable the "Git Base" and "Git" extensions to essentially turn off the source control functionality in VS Code.
