### ISSUE TITLE
Comments panel: css issue causing the position of "Ln" to be shifted

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#155198]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.1

In the Comments panel, the position of the `[Ln]` is sometimes shifted:
![image](https://user-images.githubusercontent.com/485572/179004792-41f2c18c-41af-4506-a7e2-9bad53d16f78.png)

This happens when a comment has multiple lines. In the DOM, the div contains the full comment, even though only the first line is displayed. If a line within the comment is longer than the first line, the div will be larger, causing the issue visible in the screenshot.

I've reproduced the issue on github.dev with the GitHub comments.

cc @hermannloose @alexr00

**Comment by meganrogge** [comment]
Tried to repro with a multiline comment and didn't see any shifting.
