### ISSUE TITLE
CodeLens doesn't scale together with editor

### ISSUE THREAD

**Issue by lynkx** [Microsoft/vscode#15519]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|typings-installer|benjaminromano|0.2.0|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.1|
|vscode-icons|robertohuertasm|4.0.1|
|vscode-typings|typings|0.0.5|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Create a new dotnet core C# project
2. Open up any C# file
3. Zoom in

CodeLens isn't scaling properly resulting in: 
![image](https://cloud.githubusercontent.com/assets/6179005/20311347/bd6a1882-ab4f-11e6-9776-fce88e926b56.png)

**Comment by eamodio** [comment]
I believe this is a dup of https://github.com/Microsoft/vscode/issues/15389 which isn't reproducible on the insiders 1.8

**Comment by ramya-rao-a** [comment]
Closing as duplicate. Please use the insiders build until the next VS Code update
