### ISSUE TITLE
In remote development integrated terminal closes when run command returns error

### ISSUE THREAD

**Issue by DrLoboto** [microsoft/vscode#155141]
Type: <b>Bug</b>

On Windows 10 open WSL2 project. Open integrated terminal and run command that will fail (like "pytest" with failing tests). Upon command completion terminal unexpectedly closes (with code "-1" in case of pytest). Open terminal again. Run the exactly same command. Terminal stays open as expected after command fail.

VS Code version: Code - Insiders 1.70.0-insider (052d5b0027f6c9d64c8ca35955cb5117ba94d5d7, 2022-07-13T05:16:18.401Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (6.82GB free)|
|Process Argv|--crash-reporter-id fed17fac-27e7-4122-9b91-2bf04ee8b6f7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Amazon2|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.86GB (5.17GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
thrift|cdu|0.0.1
systemd-unit-file|coo|1.0.6
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.242.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
aws-toolkit-vscode|ama|1.45.0
gitlens|eam|12.1.2
vscode-pull-request-github|Git|0.47.2022071309
vscode-docker|ms-|1.22.1
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.31
jupyter|ms-|2022.7.1001961050
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
live-server|ms-|0.2.12
vscode-coverage-gutters|rya|2.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal
