### ISSUE TITLE
Wrong order of sorting line ascending

### ISSUE THREAD

**Issue by TiagoSousa26** [Microsoft/vscode#15516]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Home Version 1607

Steps to Reproduce:

1.  Have a css file with the following code:
```
height: 100px;
margin: 0;
margin-bottom: auto;
width: 100px;
```
2.  Select the the previous code.
3. Press F1 (default key), write "sort lines ascending" and choose the option writed before.

And it will switch the `margin` with `margin-bottom` and it should be how it started.

**Comment by alexandrudima** [comment]
The sort lines command is language agnostic and follows the standard lexicographic order. 

i.e.

```js
['margin: 0;', 'margin-bottom: auto;'].sort();
// results in
["margin-bottom: auto;", "margin: 0;"]
```

In this case:
 * `margin-bottom: auto` < `margin: 0;`
 * because `margin-` < `margin:`
 * because `-` < `:`
 * because 45 < 58
