### ISSUE TITLE
File open dialog does not get focus when opening for the second and next times 

### ISSUE THREAD

**Issue by Racer84** [microsoft/vscode#155186]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:28:29.328Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.13.0-52-generic
```

- OS Version: `Linux 5.13.0-52-generic #59~20.04.1-Ubuntu SMP`

Steps to Reproduce:

1. start vscode
2. move vscode windows to left side of the screen with `master key + left arrow`; when vscode is in full screen mode problem does not appear
3. invoke file open dialog with `CTRL+O` - dialog gets focus
4. close file open dialog
5. invoke file open dialog with `CTRL+O` again - dialog does not get focus, which is very annoying

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
