### ISSUE TITLE
Backups are stored with user configured encoding

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15514]
I noticed in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/backup/node/backupFileService.ts#L73 you are not passing any encoding. This means backups are potentially stored with a user choice of encoding which is not good because we should assume UTF-8 when reading backups.

I suggest to be consistent and use UTF-8 for reading and writing of all backups.

**Comment by Tyriar** [comment]
I thought `IFileService` always default to UTF-8 is no options are provided, is this not true?

**Comment by bpasero** [comment]
@Tyriar no, the default is to pick the encoding as picked by the user via settings. The only exception is:
* if the file contains a BOM (UTF-8 or UTF-16), we use it to detect the right encoding
* if the file is settings.json either inside or outside the workspace we use UTF-8

**Comment by Tyriar** [comment]
Thanks for clarifying :smile:
