### ISSUE TITLE
typescript language service dies

### ISSUE THREAD

**Issue by F-a-u-x-L** [microsoft/vscode#155168]
Issue Type: <b>Bug</b>

The app is throwing a warning that the typescript and javascript language service died 5 times in last 5 minutes

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.21GB free)|
|Process Argv|--crash-reporter-id 35afb58d-1cb1-46df-a1f3-2595351d9ac4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
doxdocgen|csc|1.4.0
javascript-ejs-support|Dig|1.3.1
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.3.1
vscode-pull-request-github|Git|0.46.0
rest-client|hum|0.25.0
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1101950301
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.10.8
cpptools-extension-pack|ms-|1.2.0
vsliveshare|ms-|1.0.5641
vsliveshare-audio|ms-|0.1.91
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
