### ISSUE TITLE
Very slow start up time

### ISSUE THREAD

**Issue by rippo** [microsoft/vscode#155164]
Hi

I have looked at this page and can confirm I have tried everything in this article
https://github.com/microsoft/vscode/wiki/Performance-Issues#visual-studio-code-starts-up-slowly

My VScode takes @10 seconds to start even with extensions disabled 

**clipboard**
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
The clipboard just contains "Loading"

**Files attached**
[prof-zGFeEwBg.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/9110474/prof-zGFeEwBg.extHost.cpuprofile.txt)
[prof-zGFeEwBg.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9110475/prof-zGFeEwBg.main.cpuprofile.txt)
[prof-zGFeEwBg.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9110477/prof-zGFeEwBg.renderer.cpuprofile.txt)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by jrieken** [comment]
@bpasero Looks like the [call](https://github.com/microsoft/vscode/blob/0656d21d11910e1b241d7d6c52761d89c0ba23a4/src/vs/platform/backup/electron-main/backupMainService.ts#L192) to taking 10+ sec

<img width="702" alt="Screenshot 2022-07-14 at 14 33 34" src="https://user-images.githubusercontent.com/1794099/178983276-6cd345fc-356f-4beb-b35d-d60769f94c50.png">

**Comment by rippo** [comment]
looked at LOC could this be a AV issue?

**Comment by bpasero** [comment]
Yeah can easily be a AV issue, if you exclude data dirs of VSCode does it change?

**Comment by bpasero** [comment]
Yes: `c:\Users\richa\AppData\Roaming\Code - Insiders\`

**Comment by rippo** [comment]
Have tried disabling AV and adding folders as exclusions but it does not help.
Still really slow opening

**Comment by rippo** [comment]
Still same, it seems snappy aqt first then goes slower and slower

**Comment by bpasero** [comment]
I am sorry, but I am out of ideas what this could be.
