### ISSUE TITLE
JSDoc+Intellisense. Not supported @method in auto-completion

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#15511]
- VSCode Version:

![image](https://cloud.githubusercontent.com/assets/3082812/20308211/e15b23ae-ab53-11e6-8af4-7b3af3ba9c1b.png)

- OS Version: win7 pro

Steps to Reproduce:

See: http://usejsdoc.org/tags-function.html
JSDoc tag `@method` not found in auto-completion:
![image](https://cloud.githubusercontent.com/assets/3082812/20308297/46a50e46-ab54-11e6-8a73-de8fcc1edc55.png)

Code:
```js
/**
 * @class MyClass
 */
class MyClass {
   /**
    * @method func1
    */
   func1() {

   }
   /**
    * @method
    */
   func2() {

   }
}
```

**Comment by waderyan** [comment]
@bowdenk7 would you call this a bug or a feature request?

**Comment by waderyan** [comment]
This issue was moved to Microsoft/TypeScript#12316
