### ISSUE TITLE
Explorer shows "Expand All" with expanded folders

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155131]
Lately (since a few days) I see the explorer show an expand all icon even though some folders are expanded (in a multi root workspace):

<img width="300" alt="image" src="https://user-images.githubusercontent.com/900690/178894245-469c3877-2507-45f4-9926-dbea9c1b75de.png">

This must be a recent regression, not sure if in explorer or tree widget.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/pull/153614#issuecomment-1183136724

**Comment by bpasero** [comment]
This breaks my muscle memory, I always collapse the explorer to start a new task and the new behaviour breaks this. I really see no value of this new behaviour?

**Comment by bpasero** [comment]
As a suggestion: only show the expand button when really all nodes are collapsed, but keep the collapse button when any node is expanded.

**Comment by StickNitro** [comment]
I'm with @bpasero, this is quite different behavior in a multi-root workspace, I have one workspace with 5 root folders and another with 10+, prior to this change clicking the expand/collapse button in explorer would collapse all the folders in each root folder, clicking again would then collapse all the root folders. What I get now is the following:

* If all root folders are collapsed, clicking the expand/collapse button does nothing
* If one root folder is open the expand/collapse button expands and collapses folders within that root folder
* More than one root folder open the same as before for all of the open root folders

Perhaps we could have an option to opt-in to this new behavior, I can't think of a single reason why I would want to expand every folder in a project.

**Comment by bpasero** [comment]
Feature got removed.
