### ISSUE TITLE
Button for minimizing the terminal panel(& shortcuts)

### ISSUE THREAD

**Issue by teddywaweru** [microsoft/vscode#155106]
Given that we are able to maximize the terminal panel, an additional feature for minimizing it would also be handy(rather than closing them down).
Also, key combinations for this would be an efficient addition(rather than aiming at the up or down(potential) arrow & hitting the 'X' instead.
![image](https://user-images.githubusercontent.com/57697272/178821666-e883bf93-1535-4edd-8de9-608d2cb5dae0.png)

**Comment by sbatten** [comment]
Keybindings already exist (can be modified for these commands) in the keyindings editor. 
`workbench.action.toggleMaximizedPanel` and `workbench.action.closePanel` ... Minimizing the panel is effectively the same as restoring panel down when it is maximized which is covered by the first command. If the panel is not maximized, closing is effectively the same as minimizing. Feel free to comment if I have missed something.

**Comment by teddywaweru** [comment]
Very clearly put. I'll work on my own key bindings. & I hadn't done my research on minimizing/restoring the terminal. Thank you.
