### ISSUE TITLE
API to determine whether a TextEditor is a diff view

### ISSUE THREAD

**Issue by siegebell** [microsoft/vscode#15513]
Feature request: API support to determine if a document is open in a diff-editor. In particular, I want my extension to apply styles and provide certain language features when a document is loaded in a TextEditor, but not when its only editor is a diff-editor.

Looking at vscode.window.visibleTextEditors and vscode.workspace.textDocuments, I can't see any way to tell the difference.

**Comment by jrieken** [comment]
I believe each editor side is represented as an editor right now

**Comment by joaomoreno** [comment]
@siegebell Besides knowing whether a TextEditor is inside a DiffEditor, can you think of any other features around this area that would be useful to you?

**Comment by eamodio** [comment]
I would also LOVE this. This is related to https://github.com/Microsoft/vscode/issues/36019 and https://github.com/Microsoft/vscode/issues/16707

From https://github.com/Microsoft/vscode/issues/16707#issuecomment-305016864
>Just to add even more color to this request. I would love this feature for GitLens, so that I could control which pane was focused depending on the command.

>For example, alt+, in GitLens opens the a diff with the previous version, so if I could focus the left pane (i.e. previous), you could just keep pressing alt+, to navigate backward. And then I would leave focus on the right pane when navigating forwards alt+. to allow that smooth navigation as well.

>But right now, since the right pane is always focused, the forward navigation works, but the backward navigation requires you to press alt+,, focus the left pane, rinse repeat :)

**Comment by eamodio** [comment]
Any chance this can be bumped up? I hit this limitation very often in trying to provide GitLens features.

Something like a `inDiffEditor` property on the `TextEditor`, and then maybe reuse `viewColumn` to be 1 = left, 2 = right, 2 = not side by side -- or add a new property for that.

The above would alleviate most of the issues, but additionally it would be nice if there was a way to get at the other editor that is part of the diff "group"

**Comment by jrieken** [comment]
@pokey Thanks. There is also `TabInputTextDiff` which can be `instanceof`-checked to narrow down on the types of tabs. Closing this issue as implemented since the new API is the answer here :-)

**Comment by eamodio** [comment]
@jrieken I don't think this can really be closed by the Tab api -- since if I have an editor, `TextEditor` object, I can't rely on the URI match being the same editor, it could be a split editor, or a URI open in both an editor and a diff view. And since diff editors don't have view column information there isn't a good way to verify that.

I think the offered solution can definitely tell you IF a URI is open in a diff editor, but it can't tell you (definitively) that a particular `TextEditor` is in a diff editor -- which imo is the more valuable case when executing commands.
