### ISSUE TITLE
Surface shell integration configuration on command decoration button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155118]
I saw some feedback of a user not knowing how to disable shell integration on stable, they likely had shell integration from another terminal running in the shell. Added a FAQ to the docs on this but this seems like a good thing to add to the command decoration menu:
<img width="252" alt="Screen Shot 2022-07-13 at 3 56 07 pm" src="https://user-images.githubusercontent.com/2193314/178851003-0bd1c92b-7125-4d74-92fa-c93f8297e7d3.png">
<img width="224" alt="Screen Shot 2022-07-13 at 3 57 45 pm" src="https://user-images.githubusercontent.com/2193314/178851018-db681803-c409-4301-8913-e5cc46b3f436.png">

**Comment by meganrogge** [comment]
Since this menu is getting kind of long, should we allow ppl to configure which entries show up?

**Comment by Tyriar** [comment]
Still seems like a good size, it's got nothing on the editor one
