### ISSUE TITLE
Impossible to see VS Code GUI

### ISSUE THREAD

**Issue by cirmic** [microsoft/vscode#155170]
![image](https://user-images.githubusercontent.com/5978540/178960791-382f4cd9-9ead-4360-a39b-893617dfc1c5.png)

I'm running VS Code in a Ubuntu virtual machine and the Visual Studio Code GUI is totally not visible, see the image above.
All the other software works correctly and there are no graphic errors

Attached the VS Report:

Issue Type: <b>Bug</b>

test

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:28:29.328Z)
OS version: Linux x64 4.15.0-188-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz (4 x 2095)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.67GB (0.75GB free)|
|Process Argv|--user-data-dir /home/USER/.anaconda/navigator/Code --crash-reporter-id c3d0f876-45e6-41d0-b204-463d2b6cacd4|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1101950301
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by fgclue** [comment]
i am very scared of this image


very scared

**Comment by cirmic** [comment]
Issue persist with:
- VS Code version: Code 1.69.2

**Comment by rzhao271** [comment]
Does this issue persist on the latest version of VS Code?
If yes, does running code from the command line with the `--disable-gpu` flag help?
