### ISSUE TITLE
Hide explorer view after switching back to editor in Zen Mode

### ISSUE THREAD

**Issue by TheButlah** [microsoft/vscode#155121]
I just discovered zen mode, and am using vim motions to avoid using the mouse. I can hit CTRL+SHIFT+E ("show explorer" command) to view the file explorer, browse the files, and then hit CTRL+SHIFT+E again to return to the editor. However, when returning to the editor, the explorer view remains, cluttering the previously very zen screen.

It would be cool if a setting were added that hides the explorer and other windows in the left toolbar, once returning back to the editor when in zen mode.

**Comment by sbatten** [comment]
I think this is similar enough if not the same as https://github.com/microsoft/vscode/issues/3742

**Comment by TheButlah** [comment]
Its related but I'm not confident its the same thing - the feature I am asking for is zen-specific
