### ISSUE TITLE
Expose EOL sequence in API and allow to change it

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15510]
We should expose the EOL sequence of a `TextDocument` and extend the `TextEdit` such that it can be changed.

**Comment by jrieken** [comment]
@alexandrudima makes sense, right?

**Comment by jedmao** [comment]
EditorConfig desperately needs this!

**Comment by jrieken** [comment]
Work did start here: https://github.com/Microsoft/vscode/tree/joh/eol

**Comment by jrieken** [comment]
The API idea is

```ts

export class TextDocument {
  // ...

  readonly eol: EndOfLine; 
}

// eol edit
export class EndOfLineEdit {
  static readonly LF: EndOfLineEdit;
  static readonly CRLF: EndOfLineEdit;
}
```

and to allow changing it via the `WillSaveTextDocumentEvent`, like so 

```
workspace.onWillSaveTextDocument(e => e.waitUntil(Promise.resolve(EndOfLineEdit.LF)))
```

**Comment by jedmao** [comment]
Looks good to me! That would definitely make my life easier :)

**Comment by jedmao** [comment]
@jrieken w/o this, [I'm forced to modify the file contents *after* save](https://github.com/editorconfig/editorconfig-vscode/pull/116), but I really don't want to release that implementation because – well, I don't think I have to tell you why. It's pretty crappy!

**Comment by jrieken** [comment]
@jedmao No worries, this will happen for March

**Comment by jrieken** [comment]
Api will an extension of the existing `TextEdit` like so: 

```ts
class TextEdit {
// ...
		range: Range;

		newText: string;

		newEol: EndOfLine;
}
```

and a static utility like so:

```ts
class TextEdit {
  static setEndOfLine(eol: EndOfLine):TextEdit
}
```
