### ISSUE TITLE
Improve Situation for Users of the (Unpublished) Bracket Pair Colorizer 1 

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#155179]
## Problem
Despite [Bracket Pair Colorizer 1](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) has been removed from the marketplace by the author, telemetry suggests that there are still hundred thousands of active users using the extension.

Because the extension causes the extension host to freeze (degrading the entire VS Code experience) and there is both a newer version of the extension and [a native re-implementation of this feature](#128465) that does not suffer performance problems (which is actually enabled by default), we should try to push users to move away from this unpublished extension.

## Actionable

* We should disable the Bracket Pair Colorizer 1 extension for all users.
    * This should happen only once per installation, so that users can still re-enable the extension.
    * We should also show a notification that we disabled the extension. When a user disabled the native bracket pair colorization feature, the notification should include an option to enable the native colorization feature.

**Comment by hediet** [comment]
Verification steps:
* Install [CoenraadS.bracket-pair-colorizer-1.0.62.vsix.zip](https://github.com/microsoft/vscode/files/9122150/CoenraadS.bracket-pair-colorizer-1.0.62.vsix.zip)
* Reload
* Verify that the extension got disabled and a notification is shown.
* Try out the various options of the notification.
* Enable the extension again and reload. Verify that the extension is not disabled again.

**Comment by bpasero** [comment]
@hediet are we in a position to remove this notification by now?

https://github.com/microsoft/vscode/blob/fa63d292e4320e46a30cd16ff9c2c615e1fb3891/src/vs/workbench/contrib/deprecatedExtensionMigrator/browser/deprecatedExtensionMigrator.contribution.ts#L59-L77

**Comment by hediet** [comment]
Yes!
