### ISSUE TITLE
Whitescreen

### ISSUE THREAD

**Issue by kents00** [microsoft/vscode#155190]
Issue Type: <b>Bug</b>

It lately experienced a white screen if I switch to chrome or any other program and then return to vscode; I had never seen this bug prior to the update. 

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (3.25GB free)|
|Process Argv|--crash-reporter-id ffc8a846-1989-47cc-a585-d340b845bfd3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.0
doxdocgen|csc|1.4.0
vscode-terminal-for-ubuntu|Doc|0.0.2
vscode-html-css|ecm|1.13.0
pip-packages|etm|0.4.3
terminal|for|0.0.10
copilot|Git|1.31.6194
remotehub|Git|0.36.0
vscode-pull-request-github|Git|0.46.0
vscode-heroku|iva|1.2.6
better-cpp-syntax|jef|1.15.19
solidity|Jua|0.0.139
fluent-icons|mig|0.0.17
file-downloader|min|1.0.12
python|ms-|2022.10.0
vscode-pylance|ms-|2022.7.30
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cpptools|ms-|1.10.8
cpptools-extension-pack|ms-|1.2.0
remote-repositories|ms-|0.14.0
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.19.0
heroku-command|pko|0.0.8
lua|sum|3.4.2
gitblame|wad|8.2.3
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdc:30486549

```

</details>

**Comment by rzhao271** [comment]
Sorry for the slow response, but does this issue still occur for you on the latest version of VS Code?

**Comment by kents00** [comment]
This issue fixed from latest version of Vscode, Thank you!
