### ISSUE TITLE
Windows: Support file watching over samba share

### ISSUE THREAD

**Issue by FinnStutzenstein** [Microsoft/vscode#1551]
Hi Guys!
If I create a new file in my workingdirectory ist doesn't show up. I have to refresh the list and then there is my new file. In a previous version the refresh was automatically there when I create a new file. The same thing applies to folders.
My version of VSCode is 0.10.5

**Comment by bpasero** [comment]
@FinnStutzenstein which OS? And where do you create the file, inside or outside VSCode?

**Comment by FinnStutzenstein** [comment]
My OS is Windows 8.1 and I create the file with VSCode. I forgot to mention that my workingdirectory is a samba network share mounted as a network drive. When I create a file on my harddrive, it shows up directy in Code.

**Comment by bpasero** [comment]
Ok, it is likely that file watching fails for network shares.
