### ISSUE TITLE
Tab icons look to similar to toolbar icons in secondary sidebar

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#155126]
Steps to Reproduce:

1. show the side bar
![image](https://user-images.githubusercontent.com/1876302/178869585-04737cc7-867f-4a9e-a180-7c753d663044.png)

2. drap the recent editors to side panel and active them
![image](https://user-images.githubusercontent.com/1876302/178869641-b0898cc6-8f1d-4398-84bd-7d619bc7b315.png)

**Comment by heartacker** [comment]
I think that we should not lay the view icon and action icons to the same row, that make us confuse

**Comment by sbatten** [comment]
cc @daviddossett

**Comment by daviddossett** [comment]
While I agree this is confusing in isolation, this is following the same pattern used in all other panels. The actions on the right depend on the currently selected tab:

## Panel

<img width="680" alt="CleanShot 2022-10-18 at 09 11 43@2x" src="https://user-images.githubusercontent.com/25163139/196485400-478bc527-8068-471e-b468-ae2a29145dfb.png">

<img width="683" alt="CleanShot 2022-10-18 at 09 11 49@2x" src="https://user-images.githubusercontent.com/25163139/196485411-c9a16a21-43b5-4831-8159-3f1fc31a25fb.png">

## Secondary Sidebar

<img width="552" alt="CleanShot 2022-10-18 at 09 12 59@2x" src="https://user-images.githubusercontent.com/25163139/196485602-62c1926b-9d4c-492c-97c1-c93d43dc8eb1.png">

<img width="539" alt="CleanShot 2022-10-18 at 09 13 04@2x" src="https://user-images.githubusercontent.com/25163139/196485612-6f2f0b32-07ac-4089-b374-c21cd7d9bc27.png">

@heartacker what would you have expected to see?

**Comment by heartacker** [comment]
I have no idea,

 Maybe
![image](https://user-images.githubusercontent.com/1876302/196680368-e401ebd0-b7c2-4811-aebd-79d607a1a6e6.png)

**Comment by daviddossett** [comment]
@sbatten was there discussion on using regular tabs like we do in the panel here? I've heard this general feedback a couple of times now. I wonder if a `compact` density mode could use the current style while the default could be normal tabs for easier readability.

**Comment by sbatten** [comment]
We've considered allowing a switch between both options for the panel and secondary side bar

**Comment by daviddossett** [comment]
I think that might be ok depending on how many views people are really adding here. If 80%+ only add one or two, it could be ok. And we see with Fleet that scrolling tabs isn't such a bad thing either 🤷

**Comment by sbatten** [comment]
I don't think the inline any actions though so we have to wrestle with scrolling tabs and actions

**Comment by sbatten** [comment]
resolving to https://github.com/microsoft/vscode/issues/155126
