### ISSUE TITLE
IBackupFileService: less IO?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15515]
I wonder if the `IBackupFileService` could do less IO and read more out of memory. My understanding is that only one process will write to the backup files overall because we can only open one window per workspace. As such why not read the data into memory and have sync methods to get information about backups?

One thing you can always avoid is to check if a file exists. Just read it and handle the error case (e.g. https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/backup/node/backupFileService.ts#L92

**Comment by Tyriar** [comment]
Yes the `fileExists` call could be avoided. I'm not sure the other IO, actual backups and removal of backups, could be avoided though (outside of buffering content change events). One of the big use cases for this is crash recovery so anything that is kept in memory would be out of date on disk.

**Comment by bpasero** [comment]
@Tyriar but this IBackupFileService is scoped to a single window and workspace anyways right? So when there is a crash, there is no stale data because the memory goes down with the window anyways?

**Comment by Tyriar** [comment]
@bpasero which call are you suggesting could change outside of the `pfs.fileExists` in `loadWorkspaces`?

**Comment by bpasero** [comment]
All of the methods that hit the fs to read from disk. Of course this would require some means of sending the configuration over from the main side to this service so that it is initialized with the correct data.

**Comment by Tyriar** [comment]
@bpasero 

- `pfs.exists` in `hasTextFileBackup` (soon to be `hasBackup`): Needed unless we send state over from the main process, we've been moving away from this thinking (discussing in #14038).
- `pfs.readFile` in `loadWorkspaces`: Needed to get an up to date snapshot of backup workspaces during shutdown.
- `fileService.updateContent` in `backupResource`: Needed to ensure up to date backups are restored post-crash, this is buffered to ensure it doesn't fire too often.
- `fileService.del` in `discardResourceBackup`: Needed to ensure up to date backups are restored post-crash, this could be fired in quick succession is the user dirties and reverts over and over (which is not a case we care about optimizing).
- `fileService.del` in `discardAllWorkspaceBackups`: Needed to delete the backups directory before shutdown, this could potentially be checked and cleaned up on start up (discussing in #15499).

Shall I close off this issue just cleaning up `pfs.exists` in `loadWorkspaces` and follow up the other points in #14038 and #15499?

**Comment by bpasero** [comment]
Yeah, fine by me. Since I had my revealing moment in https://github.com/Microsoft/vscode/issues/14038#issuecomment-260724405 I am not sure a more sync `IBackupFileService` would help me after all.
