### ISSUE TITLE
"Virtual Folders" like those in Visual Studio, to help organize multi-project solutions

### ISSUE THREAD

**Issue by LazieWouters** [microsoft/vscode#155105]
"Virtual Folders" or some similar feature would help to better organize the project structure in the Explorer tab.
In the image, the comparison of the same solution opened in Visual Studio and VS Code:
![image](https://user-images.githubusercontent.com/77227512/178819927-b1e1d985-e925-47c9-9afb-595408e539a4.png)

**Comment by afrizal0** [comment]
Yeah, it would be great feature
