### ISSUE TITLE
Main Request service is throwing errors for valid requests

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#155204]
When requests from shared process are redirected to main, the main request service is throwing errors for some valid requests.

`[2022-07-14 17:09:57.274] [main] [trace] RequestService#request (node) - error https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery {}`

`[error] ["Error: net::ERR_INVALID_ARGUMENT","    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)","    at SimpleURLLoaderWrapper.emit (node:events:390:28)"]`

The same request is working when using browser XHR  in shared process.

To reproduce:

- Start VS Code using fresh user data dir and extensions dir
- Enable this setting `developer.sharedProcess.redirectRequestsToMain` - this is an internal developer setting, so you have to set manually in the settings.json file
- Turn on settings sync using your insiders settings sync service (Disable syncing settings)
🐛 Extensions Syncing fails because of above error

cc @bpasero

**Comment by bpasero** [comment]
What is the exact request URL and headers? We should be able to reproduce in a Electron fiddle maybe.

**Comment by sandy081** [comment]
Here is the request info 

URL: `https://marketplace.visualstudio.com/_apis/public/gallery/extensionquery`

Headers:

```
:authority: marketplace.visualstudio.com
:method: POST
:path: /_apis/public/gallery/extensionquery
:scheme: https
accept: application/json;api-version=3.0-preview.1
accept-encoding: gzip, deflate, br
accept-language: en-GB
content-length: 274
content-type: application/json
origin: vscode-file://vscode-app
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: cross-site
user-agent: VSCode 1.70.0 (Code - OSS Dev)
vscode-sessionid: 82585f7a-3ae5-491b-8db0-abfff4dea0ac1657812359083
x-market-client-id: VSCode 1.70.0
x-market-user-id: 901cfca6-8f3f-40f3-a0ee-cc4aaf37b1b8
```

Payload:

```
{"filters":[{"criteria":[{"filterType":7,"value":"undefined_publisher.msteams-liveshare-integration"},{"filterType":8,"value":"Microsoft.VisualStudio.Code"},{"filterType":12,"value":"4096"}],"pageNumber":1,"pageSize":1,"sortBy":0,"sortOrder":0}],"assetTypes":[],"flags":950}
```

**Comment by deepak1556** [comment]
Are we setting the `content-length` header ? The runtime will add that during payload upload, but if we override it then it will cause the above error.

**Comment by sandy081** [comment]
Yes, we are [here](https://github.com/microsoft/vscode/blob/44b7c86844f22f7bafe28fd88b24697a651dc284/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L938)

**Comment by sandy081** [comment]
BTW we do the same request also in the renderer for querying extensions, so does removing the `content-length` impacts the request in the renderer that uses XHR ?

**Comment by sandy081** [comment]
Just tried removing the `content-length` header and I am getting following error

```
[error] ["Error: incorrect header check","    at Zlib.zlibOnError [as onerror] (node:zlib:190:17)"]
```

**Comment by deepak1556** [comment]
> BTW we do the same request also in the renderer for querying extensions, so does removing the content-length impacts the request in the renderer that uses XHR ?

The header will get added by the runtime for payload requests, you should be able to confirm after removing the header. So, I don't think it will impact requests from renderer via XHR

> Just tried removing the content-length header and I am getting following error

Hmm, why is Node.js zlib module being involved ? Are we using Node.js request API by any chance ?

**Comment by sandy081** [comment]
We are not using `Node.js` request. Request service in main extends Node request service and pass electron net request API to Node request service for making request. See here:

https://github.com/microsoft/vscode/blob/18785833193553da8235a0768716d317bb67175d/src/vs/platform/request/electron-main/requestMainService.ts#L11-L20

While handling the response, Node request service is checking for `content-encoding` header and using zlib if it is set to `gzip`. See here:

https://github.com/microsoft/vscode/blob/18785833193553da8235a0768716d317bb67175d/src/vs/platform/request/node/requestService.ts#L149-L152

May be main request service shall not use node request service at all?

**Comment by bpasero** [comment]
@sandy081 Can we now also make sure to go back to the Electron solution for maybe insiders to validate it works?

**Comment by sandy081** [comment]
Enabled - https://github.com/microsoft/vscode/pull/167190
