### ISSUE TITLE
VScode remote completely ignores the Environment variables from the terminal from which it was opened in the first place

### ISSUE THREAD

**Issue by aammfe** [microsoft/vscode#155255]
Hello!
as mentioned in the Title, VScode remote completely ignores the Environment variables from the terminal from which it was opened in the first place.

Steps to Reproduce:
1. connect remote host using VS Code
2. open a terminal and run _export Hello = "Hello"_
3. navigate to another directory and write **code .**  it will open up a new  VScode instance 
4. open a terminal in it and run _echo $Hello_ you should be able to see _Hello_ in the output. 

this behavior is working on a local machine, but when connected with a remote host Environment variables are not being exported to the new instance of VS.

the issue is **haskell.haskell**  Extention needs a **PATH** variable, it is being configured from a script that has been run in the previous terminal, so in the new VSCode Instance Bcs **PATH** is not the configured one, it does not work.

local : 
OS: macOS Monterey
Code:     1.69.1        b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a        arm64 
Extensions : 
        arrterian.nix-env-selector
        bbenoist.Nix
        eamodio.gitlens
        GoNZooo.environment-injector
        haskell.haskell
        jnoortheen.nix-ide
        justusadam.language-haskell
        mhutchie.git-graph
        ms-vscode-remote.remote-containers
        ms-vscode-remote.remote-ssh
        ms-vscode-remote.remote-ssh-edit
        ms-vscode-remote.remote-wsl
        ms-vscode-remote.vscode-remote-extensionpack**
        ms-vsliveshare.vsliveshare
        naumovs.color-highlight
        tamasfe.even-better-toml

Remote : 
OS :         nixos-22.05
Code :     1.69.1        b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a      x64
Extensions :  
        arrterian.nix-env-selector 
        eamodio.gitlens
        haskell.haskell
        jnoortheen.nix-ide
        justusadam.language-haskell
        mhutchie.git-graph
        ms-vsliveshare.vsliveshare
        naumovs.color-highlight
        tamasfe.even-better-toml

**Comment by roblourens** [comment]
This scenario isn't supported, because you're connecting to an instance of the vscode server which was already started in another environment

**Comment by aammfe** [comment]
is there any workaround?
BCS sometimes its necessary.

**Comment by roblourens** [comment]
There is probably another way to configure the extension

**Comment by roblourens** [comment]
You can also change your user environment via .bashrc and run the "Kill VS Code Server on Host" command, and reconnect, to start a new instance of the server with the new environment
