### ISSUE TITLE
3 way merge *editor* only edits 2 ways.

### ISSUE THREAD

**Issue by ruffin--** [microsoft/vscode#155251]
Re: [3 way merge. You keep using that word...](https://github.com/microsoft/vscode/issues/154877#event-6997465320)

> Please try out the merge editor before giving feedback.

@hediet -- I have now tried VS Code's tool, and it's my turn to request you read my [previous bug report](https://github.com/microsoft/vscode/issues/154877) more carefully before closing it without checking in for clarification.

We both want a better tool, right? Let's learn together.

> I have to disagree here.  
> We take the base into account and compute the changes by diffing everything (even the result) against base.

That describes _your merge algorithm_. You advertise a [_three-way merge **editor**_](https://code.visualstudio.com/updates/v1_69#_3-way-merge-editor).  

<img width="484" alt="marketing screenshot from the VS Code website advertising a three-way merge" src="https://user-images.githubusercontent.com/5659878/179118415-24934b62-9741-4abb-a957-b0e12780f1b7.png">

I apologize that I elided the word "editor" from my initial report, as I had assumed it was clear in context. 

## kdiff3, a 3-way merge editor

Again, a _three-way merge editor_ allows you to choose NewA, NewB, **or the original file**. Again, kdiff3 is a _three-way merge editor_.  I can see **all four** at once while performing a merge. :chef's kiss:

kdiff3 has a pane for editA, editB, **base**, _and_ the result:

![image](https://user-images.githubusercontent.com/5659878/179118207-03548bc7-2424-45f5-9933-71fd04e23638.png)

## VS Code's 2-way merge editor

> The merge editor allows you to quickly resolve Git merge conflicts. When enabled, the merge editor can be opened by clicking on a conflicting file in the Source Control view. Checkboxes are available to accept and combine changes in Theirs or Yours:

Theirs or Yours displayed in the editor with the result, no [permanently displayed] base. That's 2-way. 

**Note:** WinMerge does 2-way too. And that's why WinMerge isn't an option in SourceTree as a conflict tool, just as a diff tool.

Here is the simplest-case merge conflict I set up to demonstrate in the VS Code merge editor:

![VS Code merge editor has editA, editB, and the result, but no base](https://user-images.githubusercontent.com/5659878/179118091-1254bcf2-b39f-4741-b982-f1e715618647.png)

That matches your marketing gif exactly. If I missed something that required me trying it out, tell me. I don't think I did.

If that's confusing, please feel free to ask questions. If it's not confusing and you claim you do have a three-way merge editor, you're wrong. No big deal, but your marketing material is -- and you are -- wrong. 

I'm just trying to make a tool I enjoy better. I've put over an hour into this bug report, and the last 45 minutes I didn't need to, as the original report was bang on. Not great user support.

cc: @gjsjohnmurray

---

```
Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:51.333Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

**Comment by yume-chan** [comment]
In #154877 you said _ Because you can't see the original ancestor Theirs and Yours have in common._, but the merge editor shows base version when both checkboxes are unchecked, so I guess this is what _no [permanently displayed] base_ means, right?

I admit I rarely use any merge editor, so I think you should clarify why this "temporary base display" is worse than permanent ones like KDiff, because IMO if I want to see the base, I can uncheck both, and after I made a decision, I no longer need to see the base.

Also, I only see comparison and facts from you, but not solutions. Are you proposing to make the merge editor similar to KDiff by showing 4 editors, or you have other better solutions?

**Comment by joaomoreno** [comment]
> Again, a three-way merge editor allows you to choose NewA, NewB, or the original file. Again, kdiff3 is a three-way merge editor. I can see all four at once while performing a merge. :chef's kiss:

@ruffin-- I think you nailed it here. This is about _seeing_ the base version as well. But just because we don't render the base version, that doesn't mean this isn't a 3-way merge editor.

A simpler feature request for the same thing can be found here: https://github.com/microsoft/vscode/issues/155277

**Comment by hediet** [comment]
> Merge editor appears to work just for git. Can we have it for any two files? I can select and compare two files but can I use a merge editor to merge them?

Unfortunately, this feature has been designed as 3-way merge editor, so you cannot use it to merge just two files (we need the base file). But I think there is a feature request for it.

**Comment by ruffin--** [comment]
> Also, I only see comparison and facts from you, but not solutions. Are you proposing to make the merge editor similar to KDiff by showing 4 editors, or you have other better solutions?

I'm not sure what I'm doing wrong here.

**The current marketing material for VS Code is wrong.** 

VS _Code does not provide a three-way merge editor_, the same way WinMerge is not a three-way merge editor, even though it shows Yours, Theirs, and Current [though slightly differently than VS Code's].

I'm going to give up at this point after saying...

 **This is _not_  dupe of "[create a three-way merge editor](https://github.com/microsoft/vscode/issues/155277)**  [which requests VS Code provide a 4-editor view, which is, ontologically, **what it means to be a three-way merge editor**]". _That's_ a feature request. This bug describes a mistake. You could fix this by implementing that feature request immediately or... you could fix the marketing to match the actual product.

I was really excited to see VS Code had added a 3-way editor, as kdiff3 is a little long in the tooth, and then exceptionally disappointed when that editor was missing the base file display.

from @yume-chan
> so I think you should clarify why this "temporary base display" is worse than permanent ones like KDiff,

Because 3-way diffs tools like kdiff3 (kdiff _3_ :wink:) provide more information. 

How do I scan a conflict and know what the original looked like if I selected Yours or Theirs and that's all I can see [now] in the "temporary base display"?

Without the base, you can't manually display a three-way merge to another human, for instance. 

* Ashley asks, "Hey Pat! Take a look. Did I merge this correctly?" 
* Pat looks at the VS Code merge tool in front of Ashley, but can't tell. 
    * Did Theirs just add a space over the original so Ashley ignored it and took Yours? 
    * Or did Theirs, like Yours, also blast a line from the base and Ashley chose Yours over Theirs? 
* PAT CAN'T DEAL WITH THE PRESSURE AND TAKES UP PROFESSIONAL [JAI ALAI](https://en.wikipedia.org/wiki/Jai_alai) INSTEAD!!!

**The current diff implementation makes review a lossy process without a permanent base to check against.** And believe me, with a complicated enough file, Pat is Ashley! (that is, you're going to wonder about your own conflict resolution)

And why was the base gone again? That's because that bottom pane is  _not_ a "temporary base display". It's _the result_. There is no cake!^H^H^H^H I mean result -- here. 

Why would VS Code provide a 2-way UI for a 3-way conflict resolution algorithm? It doesn't make any sense.

Try using [kdiff3](http://kdiff3.sourceforge.net) (a newer version is [here[(https://github.com/KDE/kdiff3) by a different developer, but I haven't tried it) for a while to resolve complicated conflicts and let me know if you can't at least see why some might prefer that UI.

My request is that MS fix one or the other, marketing or the app, so that they match accurately. My guess is that fixing the marketing is going to be easier for now -- and then you can change it back when you're actually providing a 3-way editor in the future.

I mean, I know we're an increasingly postmodern society, but taxonomies and definitions still matter. 

Thank you for attending my second off-TEDx talk. 😩

**Comment by ruffin--** [comment]
> But just because we don't render the base version, that doesn't mean this isn't a 3-way merge editor.

@joaomoreno kdiff3 (and industry standards) would disagree.

See the Pat & Ashley routine above for why it's crucial to have a base in a 3-way merge editor. Otherwise you're not doing a 3-way edit.

(yes, I guess I lied about giving up earlier)

**Comment by cadsuara** [comment]
I already suggested something similar in previous exploratory tickets like Explore UX for three-way merge #146091

My comment:
https://github.com/microsoft/vscode/issues/146091#issuecomment-1089029759

Check also this [blog](https://www.rosipov.com/blog/use-vimdiff-as-git-mergetool/)

**Comment by phiresky** [comment]
> That describes your merge algorithm. You advertise a three-way merge editor. I apologize that I elided the word "editor" from my initial report,

Well it's a "(3-way merge) editor" not a "3-way (merge editor)" in the same way that vscode is a "(shitty code) editor" not a "shitty (code editor)". Maybe this problem could be fixed by naming it `3-way-merge editor` instead of `3-way merge editor`
