### ISSUE TITLE
Feature Request: Button to clear old errors and warnings output

### ISSUE THREAD

**Issue by atishpatel** [Microsoft/vscode#15524]
It would be very helpful to have a button to clear all the errors generated by linters. I leave VSCode running on a project for weeks and sometimes linters give errors or warnings that can't be fixed at the moment and clutter the error and warning panel when I'm trying to debug other packages in the project. 

Some linters also do weird things like lint Untitled files where I'm temporarily storing some text. These errors/warnings end up create an output for a random number file.  For example, I have 6 errors for file `1270 /`, and i can't remove that text until I close VSCode.

Thank you.

**Comment by meshula** [comment]
Similar to this request, I would also like to be able to clear errors from the build system.

**Comment by sandy081** [comment]
Problems panel is built only to show the problems generated by various background linters/tasks. If there are errors, it makes sense to always show them. Not showing them would leave to invalid state. 

Instead, you should be able to configure linters/tasks in the way you wanted.

**Comment by atishpatel** [comment]
@sandy081 
I'm sorry if my description wasn't clear enough. You have a good point, but configuring the linters doesn't cover all the cases and it depends on the developer to allow the option. 

I believe this is an issue that can't be solved by linter configurations. If a file is linted then deleted, renamed, or was Untitled, the linter can't possibly know that was the case. So, the linter will print errors for that filename, but unless the issues are fixed before the file is discarded, the editor has to be restarted to clear the error screen.

I'm not suggesting the errors be removed automatically. I'm just looking for a way to clear them via a menu option or button by the collapse button.

**Comment by sandy081** [comment]
>
I believe this is an issue that can't be solved by linter configurations. If a file is linted then deleted, renamed, or was Untitled, the linter can't possibly know that was the case.

@atishpatel Linter is responsible to handle such cases and clear the markers it generated. I assume extensions are notified when such things happen.

**Comment by gerrywastaken** [comment]
This reminds me of the problems I had with Atom linters all over again. The linter core would claim that linter plugins were not doing things correctly and that was the cause of the problem. Trouble is, most of the plugin authors we apparently not doing one thing or another correctly and in the end it's the user that ends up in the frustrating situation.

Perhaps there could be checks for when a plugin author isn't implementing something correctly (such as never cleaning up after files are closed) and a warning could then be displayed?

**Comment by pmunin** [comment]
Current behavior is poorly designed. Most of the time I run webpack task which also execs lint and displays its warning, but once in a while I need to execute just lint only task. After I do it - problems found during lint only task never go away, displaying merged with webpack duplicates until I restart vscode.
Please reconsider this suggestion.
