### ISSUE TITLE
Node debug gives stale variables if evaluation happened

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#15520]
1. Debug the following program
```javascript
var text = "some text";
debugger;
```
2. In repl or watch expressions do `text = "new value"`
3. Notice how the variables view shows a stale value for `text` - VSCode is sending a `variables` request but the node debug is responding with stale results

Also happening for node2 @roblourens 
We would need to drop all cached variables on evaluation request, though not sure how expensive that is.

**Comment by roblourens** [comment]
vscode is sending a new variables request after an eval, but the wrong values are returned? node2 definitely doesn't cache any values. I'll try it out though.

**Comment by isidorn** [comment]
exactly - but get latest vscode source for that. Or on insiders switch focused stack frame - that should always send new variables requests

**Comment by roblourens** [comment]
It seems like these are being cached by Node/Chrome, so I don't think there's anything I can do there. It returns the same values until a step happens.

**Comment by weinand** [comment]
Same for node-debug. If I turn off caching, I still see the same behavior.

The only workaround I could imagine would be to update all values in the cache by doing an 'evaluate'. 
But this doesn't seem practical as the cache might become large.
