### ISSUE TITLE
Improve Scroll to bottom behavior

### ISSUE THREAD

**Issue by daslicht** [Microsoft/vscode#15523]
- VSCode Version:

- OS Version:
OS X 10.11.6

When we currently fully scroll down to the bottom of an document we get this presented:

![](http://i.imgur.com/2Z6YbVa.png)

This would be more useful:

![](http://i.imgur.com/s1i4hgB.png)

**Comment by bgse** [comment]
There's already an issue for this somewhere, but both variants have their uses.

Assume you want to have a specific line of code in the middle of your screen (say line 37 in your screenshot), e.g. side-by-side comparison or just for easy reading. With a fixed scroll-to-bottom, you can't have that.

**Comment by daslicht** [comment]
Sounds logical, but how often do you scroll to the bottom and how often you compare.

I think this behavior should be switchable

**Comment by bgse** [comment]
It is, sorry I didn'T mention:

`"editor.scrollBeyondLastLine": false`

**Comment by ramya-rao-a** [comment]
Thanks @bgse .

@daslicht The setting @bgse mentioned should solve your problem

**Comment by daslicht** [comment]
AWESOME!
