### ISSUE TITLE
unable to add terminal

### ISSUE THREAD

**Issue by Asu1996** [microsoft/vscode#155259]
Issue Type: <b>Bug</b>

i use multiple terminals for multiple repos. so i click on the + icon on the right top of terminal. then i select which repo to open terminal for. i select and then it closes automatically. not sure if somethings wrong in my system or vscode settings.

VS Code version: Code 1.69.1 (Universal) (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:51.333Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id e587f0bd-1a4e-4838-9dd6-d59c8eee73d5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
django-html|bib|1.3.0
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.46.0
gc-excelviewer|Gra|4.2.55
latex-workshop|Jam|8.27.2
ecdc|mit|1.8.0
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.4
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.1
data-workspace-vscode|ms-|0.2.2
mssql|ms-|1.15.0
sql-bindings-vscode|ms-|0.2.1
sql-database-projects-vscode|ms-|0.17.2
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1101950301
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.241.3
azure-account|ms-|0.11.0
material-icon-theme|PKi|4.19.0
vscode-thunder-client|ran|1.16.6
eno|Wsc|2.3.53
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdc:30486549

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needs-more-info"

**Comment by Asu1996** [comment]
seems to be working now.
