### ISSUE TITLE
Tasks are requesting workspace trust on startup

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#155227]
Type: <b>Bug</b>

This just started happening in today's insiders but affects insiders.vscode.dev as well. It seems that tasks are requesting workspace trust on launch which causes a double prompt in some cases.

VS Code version: Code - Insiders 1.70.0-insider (e0a65a97d4f349cf11a7cae804a5553ccb412528, 2022-07-14T05:17:15.290Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.80GB free)|
|Process Argv|--crash-reporter-id 3434a1e9-60b7-446b-986c-27c6457bc73d|
|Screen Reader|no|
|VM|21%|
</details>

**Comment by meganrogge** [comment]
Since we want tasks to reconnect on window reload and tasks require workspace trust, I am not sure what to do about this. @Tyriar or @alexr00 thoughts?

**Comment by Tyriar** [comment]
@sbatten shouldn't the double prompt be prevented and shared inside the workspace trust code?

**Comment by meganrogge** [comment]
this will happen if there are any recently used tasks atm

**Comment by meganrogge** [comment]
because we don't know ahead of time which of those should be reconnected to (has a corresponding terminal that will be revived)

**Comment by sbatten** [comment]
in most web scenarios there is not terminal? http://insiders.vscode.dev/https://github.com/microsoft/vscode/pull/155223 I get prompted in this case

**Comment by meganrogge** [comment]
yeah I should be checking that - I'm surprised the task service even gets created in the web context

**Comment by meganrogge** [comment]
fixed it from a task/terminal perspective 
https://github.com/microsoft/vscode/pull/155233

**Comment by meganrogge** [comment]
actually that will not fix it - here's where it's called currently https://github.com/amanasifkhalid/vscode/blob/cb1c894367692b72218ea4cc27eb93f5a2252dc2/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L340-L343

and this calls `tryResolveTask` which requires trust

**Comment by meganrogge** [comment]
so need to check a context key there

**Comment by meganrogge** [comment]
this is now checked before reconnecting

https://github.com/amanasifkhalid/vscode/blob/cb1c894367692b72218ea4cc27eb93f5a2252dc2/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2175-L2178

**Comment by sbatten** [comment]
should this be fixed in todays build? still seeing this in web https://insiders.vscode.dev/github/microsoft/vscode/pull/149187

**Comment by meganrogge** [comment]
related https://github.com/microsoft/vscode/issues/155336#issuecomment-1185851921 and will fix - missed a few places where this context key is needed to prevent it from happening

**Comment by meganrogge** [comment]
Oh I think this is happening because these have default values of false and I believe `!!` just checks if it's not undefined

https://github.com/microsoft/vscode/blob/015d6b8e622e41b0e73539f3976b6f7d02012b4c/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2177

**Comment by joaomoreno** [comment]
Related: https://github.com/microsoft/vscode/issues/155383

**Comment by alexr00** [comment]
> yeah I should be checking that - I'm surprised the task service even gets created in the web context

The task system can run `CustomExecution` tasks in the web. We hide most tasks entry points in the web though because we don't have a great use case for this yet, but they do run.

**Comment by joaomoreno** [comment]
Reopen due to revert: https://github.com/microsoft/vscode/pull/155468

**Comment by meganrogge** [comment]
@sbatten can you still reproduce this?

**Comment by meganrogge** [comment]
Confirmed that it can't be reproduced
