### ISSUE TITLE
Feature Requet: Open git integration for usage from commands-api

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#15525]
Please make the git integration resuable by the [commands-api](https://code.visualstudio.com/docs/extensionAPI/vscode-api-commands).

It is really cumbersome to reimplement that parts and as well the UI gets kind of laggy. Since when I checkout a branch (in my case a [github pull request](https://marketplace.visualstudio.com/items?itemName=KnisterPeter.vscode-github)) it needs a few seconds until the 'current branch' status entry updates.

**Comment by joaomoreno** [comment]
I'll merge this in #15246, which can't be accomplished without this.

**Comment by KnisterPeter** [comment]
Hi @joaomoreno ,

I would like to reopen this discussion.
With the integration of SCM and the git commands available it would be great to get the benefit and better user experience of reusing the git SCM for my github extension (KnisterPeter/vscode-github#18).

The current git commands are executable via the commands api, but the commands are not exactly what I need. The most valueable integration for me would be to have a `git.checkout` with an optional given branch name. Then I could reuse your command and checkout the ref of a github pull-request with the instant updates on e.g. the status bar.

**Comment by joaomoreno** [comment]
Hi @KnisterPeter. Awesome, can you file a feature request for that and ping me?
