### ISSUE TITLE
TypeScript service

### ISSUE THREAD

**Issue by brucemackenzie** [microsoft/vscode#155247]
Issue Type: <b>Bug</b>

Open vs.code with my project.
Wait...

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:28:29.328Z)
OS version: Linux x64 5.15.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics (16 x 4425)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|62.18GB (29.88GB free)|
|Process Argv|--unity-launch --crash-reporter-id 0f5db1f9-e19c-40e2-a9f5-fa661f41eecd|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
vscode-base64|ada|0.1.0
vscode-json|and|1.5.0
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
gitlens|eam|12.1.2
terraform-autocomplete|erd|0.0.8
url-encode|fle|1.1.0
terraform|has|2.23.0
vscode-mocha-test-adapter|hbe|2.14.0
vscode-test-explorer|hbe|2.21.1
rest-client|hum|0.25.0
openvpn|idl|0.2.3
json2csv|kha|0.0.1
markdown-shortcuts|mdi|0.12.0
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
mongodb-vscode|mon|0.9.3
vscode-docker|ms-|1.22.1
vscode-kubernetes-tools|ms-|1.3.10
remote-containers|ms-|0.241.3
test-adapter-converter|ms-|0.1.6
vscode-groovy-lint|Nic|1.9.0
indent-rainbow|ode|8.3.1
vscode-data-preview|Ran|2.3.0
vscode-yaml|red|1.9.1
vscode-sort-json|ric|1.20.0
vscode-direnv|Rub|0.0.2
partial-diff|ryu|1.4.3
jenkinsfile-support|sec|0.1.0
vscode-taskexplorer|spm|2.9.1
jenkins-jack|tab|1.2.1
email-viewer|Tom|5.0.0
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdc:30486549

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
