### ISSUE TITLE
Skipped edit sessions are deleted

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#155217]
Originally reported by @TylerLeonhardt 

1. Create an edit session in microsoft/vscode 
2. Create an edit session in microsoft/vscode-pull-request-github
3.  Apply Latest Edit Session in microsoft/vscode (which attempts to apply the most recently stored edit session, i.e. the one for vscode-pull-request-github
4. :bug: edit session is not applied, also more importantly the edit session for vscode-pull-request-github is deleted

**Comment by joyceerhl** [comment]
Verification:
1. Create an edit session for e.g. in insiders.vscode.dev/github/microsoft/vscode-pull-request-github
2. Attempt to apply it in insiders.vscode.dev/github/microsoft/vscode
3. Open the Edit Sessions output channel
4. You should not see a message about the edit session being deleted
5. If you open github.dev/microsoft/vscode-pull-request-github and try to apply the edit session there, it should succeed

**Comment by meganrogge** [comment]
by `apply it` do you mean `store current edit session` @joyceerhl ?
