### ISSUE TITLE
Allow me to disable debug status bar treatment

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#155294]
I am becoming a power-user of our debugger (yeah, finally). This means that most of my "VS Code time" I have some kind of debuggee running or connected. So, I am seeing the ugly orange debug status bar treatment a lot. I don't like it and for me it's enough to see the activitybar icon decorations. So, pretty please give me an option to disable this

**Comment by roblourens** [comment]
Is it enough to set `statusBar.debuggingBackground` in `workbench.colorCustomizations`? Or do you think we need a dedicated setting?

**Comment by jrieken** [comment]
A dedicated setting because the color customizations don't allow to reference another color (AFAIK)

**Comment by roblourens** [comment]
Just need a setting checked here https://github.com/microsoft/vscode/blob/83c1fda46e572427571418f2a2437c27a0c1e0b5/src/vs/workbench/contrib/debug/browser/statusbarColorProvider.ts#L72

**Comment by shaiguelman** [comment]
Can I work on this?

**Comment by gjsjohnmurray** [comment]
> A dedicated setting because the color customizations don't allow to reference another color (AFAIK)

A good use case for https://github.com/microsoft/vscode/issues/56855#issuecomment-952762391

**Comment by roblourens** [comment]
@KoushikSahu Someone had already expressed interest in this, please let them take it next time. I'll look at your PR but don't have time in July due to vacation, I'll review it in August.

**Comment by KoushikSahu** [comment]
> @KoushikSahu Someone had already expressed interest in this, please let them take it next time. I'll look at your PR but don't have time in July due to vacation, I'll review it in August.

Apologies for the inconvenience caused. I will take into account any prior interests from here on.

**Comment by utkarsh867** [comment]
Is this issue still active? I'd like to have this feature too! So if no one is taking it, I'm more than happy to give it a shot :)

**Comment by KoushikSahu** [comment]
> Is this issue still active? I'd like to have this feature too! So if no one is taking it, I'm more than happy to give it a shot :)

Not getting the time to work on this. Please go ahead and take this up if you want to.

**Comment by weartist** [comment]
Can I also add pr for this question? There seems to be no progress

**Comment by modeware** [comment]
Are we talking about  the bottom pink colour bar? A dedicated setting to change that color?

![image](https://user-images.githubusercontent.com/25425426/202911679-f17fdf0f-d2e9-4b41-a6c4-884191584fd5.png)

**Comment by antonioprudenzano** [comment]
I don't see any recent activity on this so i'm linking a PR, waiting for review.
