### ISSUE TITLE
curl latest deb file

### ISSUE THREAD

**Issue by jrock2004** [Microsoft/vscode#15529]
This is not a bug but more a question of how to download the latest deb file via command line in Linux. I have tried the following but it downloads the html file and not the file itself

```
# curl -o code.deb http://go.microsoft.com/fwlink/?LinkID=760868 
```

I want to do this as I have a setup script that I run when I setup my linux environment. Thanks

**Comment by Tyriar** [comment]
You need to follow the redirects using `-L`:

```
curl -o code.deb -L http://go.microsoft.com/fwlink/?LinkID=760868
```
