### ISSUE TITLE
Notebook markdown cell selection indicators don't line up

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#155222]
Type: <b>Bug</b>

create a couple markdown cells and render them
click one to select it and shift click another

result: blue bar spills out of the gray selection area
![image](https://user-images.githubusercontent.com/2019016/179056334-4c4c8419-c1d2-4f47-b8f7-720f10bb17c9.png)

VS Code version: Code - Insiders 1.70.0-insider (3104db414c8fedcf6e4493f14da7df0b7413853a, 2022-07-08T05:20:13.606Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (14.45GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.0
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.2.6
python-environment-manager|don|1.0.4
gitlens-insiders|eam|2022.7.1305
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
copilot|Git|1.31.6194
vscode-pull-request-github|Git|0.47.2022071415
vscode-mocha-test-adapter|hbe|2.14.0
vscode-test-explorer|hbe|2.21.1
vscode-language-pack-de|MS-|1.69.7130931
dotnet-interactive-vscode|ms-|1.0.3362041
python|ms-|2022.11.11951004
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1001882251
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.242.0
remote-ssh|ms-|0.85.2022071315
remote-wsl|ms-|0.66.3
js-debug-nightly|ms-|2022.7.1117
test-adapter-converter|ms-|0.1.6
vscode-github-issue-notebooks|ms-|0.0.119
vscode-js-profile-flame|ms-|1.0.4
vscode-yaml|red|1.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506

```

</details>

**Comment by rebornix** [comment]
Fixed in main.
