### ISSUE TITLE
Bracket Pair Colorization is not working

### ISSUE THREAD

**Issue by xdesign-diegodiniz** [microsoft/vscode#155239]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.1
- OS Version: MacOS 12.3.1 (21E258)

Steps to Reproduce:

The native VSCode bracket pair colorization suddenly stop working.  All brackets (curly, square, round) on my code are gray now. Screenshoots below of the `settings.json` and the code:

![image](https://user-images.githubusercontent.com/102035460/179086450-2c78f6b9-39c8-413f-b07d-6e19ebb1cd63.png)
![image](https://user-images.githubusercontent.com/102035460/179086542-afc5e727-dd1f-464d-9ec2-e836f20dc8cc.png)
![image](https://user-images.githubusercontent.com/102035460/179086982-ea9fca55-f244-4965-a4f7-d3144bbd7d36.png)

**Comment by hediet** [comment]
Do you use language specific overrides?

Can you check this for the insiders build of VS Code in a fresh workspace?
Can you share the entire code snippet?

**Comment by RedCMD** [comment]
Does clicking a on bracket show bracket pair match highlights?
![image](https://user-images.githubusercontent.com/33529441/179129930-bf8c23ef-5591-4c69-9df8-6e9cd2b87056.png)

**Comment by xdesign-diegodiniz** [comment]
@hediet I don't think so. I never had it. Like I said, I was working and suddenly the bracket colorzation stopped working.

Example in a fresh workspace:
![image](https://user-images.githubusercontent.com/102035460/179180022-40e81383-8d8a-4327-b34d-763cf5903ad4.png)

My config file `settings.json`:
![image](https://user-images.githubusercontent.com/102035460/179180492-4115293f-464a-4f4c-a6b1-6bccbd550e67.png)
 
Thanks for your help. 😊

**Comment by xdesign-diegodiniz** [comment]
@RedCMD it does, but as you see all brackets are gray 🤦🏻‍♂️

Example in a fresh workspace:
![image](https://user-images.githubusercontent.com/102035460/179180022-40e81383-8d8a-4327-b34d-763cf5903ad4.png)

**Comment by xdesign-diegodiniz** [comment]
@hediet All fixed now. Thanks for you help. I'm going to close this issue now.
