### ISSUE TITLE
In the extension test code, extension and extensionContext are undefined in most cases.

### ISSUE THREAD

**Issue by loin3** [microsoft/vscode#155206]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: vscode-darwin-1.69.1
- OS Version: macOs Monterey 12.1

Steps to Reproduce:
1. set vscode extension context when activate extension.
```
import * as vscode from 'vscode';

export function activate(_context: vscode.ExtensionContext) {
	// Set context as a global as some tests depend on it
	(global as any).testExtensionContext = _context;
}
```
2. activate extension in suiteSetup and check extension and extensionContext exist.
```
import { expect } from 'chai';
import 'mocha';
import { ExtensionContext, extensions } from 'vscode';

suite('vscode API - globalState / workspaceState', () => {

	let extensionContext: ExtensionContext;
	suiteSetup(async () => {
		await extensions.getExtension('vscode.vscode-api-tests')?.activate();
	        extensionContext = (global as any).testExtensionContext;
	});

	test('state', () => {
		const extension = vscode.extensions.getExtension(
                        'vscode.vscode-api-tests',
                );
                expect(extension).not.to.be.undefined;

                expect(extensionContext).not.to.be.undefined;
                expect(extensionContext.globalState).not.to.be.undefined;
	});
});
```
3. Sometimes the extension and extensionContext are not undefined, but in most cases, the test code fails because it is undefined.

I followed `vscode/extensions/vscode-api-test/src/singlefolder-tests/state.test.ts` and `vscode/extensions/vscode-api-test/src/extension.ts`

**Comment by alexdima** [comment]
@loin3 Please reopen if there is new information on how to reproduce.
