### ISSUE TITLE
[ts] Property 'indexOf' does not exist on type 'string' 

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode#15521]
- VSCode Version:1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open a typescript file in the editor
2. I see errors on string methods

```
[ts] Property 'indexOf' does not exist on type 'string'
[ts] Property 'substring' does not exist on type 'string'
[ts] Property 'lastIndexOf' does not exist on type 'string'

```
Any thoughts?

Thx

**Comment by waderyan** [comment]
Can you share your code? I am not seeing this on my end.

**Comment by riteshatsencha** [comment]
Yeah so attached image is what I am referring to. Are there any documented steps on how to fix these errors after upgrading vscode? (which is once a month or more).  

After upgrading vscode one of the most common error I see is "vscode not found". I ran npm uninstall and install. I also ran npm run postinstall. Still same errors.

What's weird is, I don't see these errors on OS X. It's always Windows.

Thx

<img width="679" alt="code-errors-windows" src="https://cloud.githubusercontent.com/assets/14277904/20398430/6e570e90-acbb-11e6-90f0-a992a4a78cef.png">

**Comment by waderyan** [comment]
Can you share a link to your workspace so I can run this on my machine? My guess is there is an issue with the config file in your workspace.

**Comment by riteshatsencha** [comment]
here is the tsconfig.json

```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "outDir": "out",
        "noLib": true,
        "sourceMap": true,
        "allowJs": true,
        "rootDir": "."
    },
    "exclude": [
        "node_modules",
        "out",
        ".vscode-test",
        "test"
    ]
}
```

Is this what you are referring to when you say config file?

**Comment by waderyan** [comment]
Yes it is. Can you share a link or a zip of your workspace?

**Comment by riteshatsencha** [comment]
See if you can access this link. I could not share code for the project and therefore used the same workspace but put HelloWorld.ts which shows these errors. 

[zipped workspace](https://drive.google.com/open?id=0B_O5MJlzi5ulZllyNUhRcWhmWFE)

Thx

**Comment by riteshatsencha** [comment]
I have sent you zipped workspace through email. 

See if you can access it. I could not share code for the project and therefore used the same workspace but put HelloWorld.ts which shows these errors.

**Comment by waderyan** [comment]
@riteshatsencha apologize for the delay. This fell through my inbox for a time. 

I opened your project and recreated the behavior you described. I changed one line in the tsconfig.json file to solve the issue. 

```
// set this to false
"noLib": false,
```
