### ISSUE TITLE
Stick tab stop mouse selection slightly broken

### ISSUE THREAD

**Issue by Timmmm** [microsoft/vscode#155299]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.1
- OS Version: Mac 11.6

Steps to Reproduce:

1. Enable `"editor.stickyTabStops": true`

2. Start a mouse selection at the start of an indented line and gradually move the mouse to the right.

The cursor should jump through positions 0, 4, 8, etc. (with 4-space indentation). Actually it goes 0, 1, 0, 3, 4, 5, 4, 7, 8, ...

Sorry I wrote this code. :-/ Actually I feel like I would have noticed if it didn't work when I wrote it so maybe this broke in the last couple of releases.

**Comment by hediet** [comment]
Can you look into why this happens? Maybe even provide a bugfix PR? Thanks!

**Comment by Timmmm** [comment]
The error was introduced by this commit: 451c9a636fe063970f3b6baafbbd61b98d35fd3b

I haven't understood why exactly yet, but I guess it's just doing things in the wrong order - fixing up the cursor position after sticky tabs have snapped it to a tab instead of before.

I'll keep digging.

**Comment by Timmmm** [comment]
@hediet Any chance you could get someone to review my PR?

**Comment by hediet** [comment]
Sorry, I was busy with the merge editor. I try to look into it next milestone!
