### ISSUE TITLE
OVER and PARTITION BY keywords in SQL are not highlighted

### ISSUE THREAD

**Issue by bradley-fastorientation** [Microsoft/vscode#15522]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

![image](https://cloud.githubusercontent.com/assets/14201124/20312867/fd0fcb8a-ab22-11e6-99f0-ee07ce4d0bc7.png)

**Comment by aeschli** [comment]
This issue was moved to textmate/sql.tmbundle#19
