### ISSUE TITLE
White boxes on screen since last update

### ISSUE THREAD

**Issue by IslamChemirik** [microsoft/vscode#155393]
Issue Type: <b>Bug</b>

Since the last update i have white boxes on screen, i had similar problem on Microsoft Edge few months ago and i resolved it by disabling hardware acceleration

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2410M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.13GB free)|
|Process Argv|--crash-reporter-id c3e6d538-c697-4f1c-ab0e-d65d47731442|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
javascript-ejs-support|Dig|1.3.1
vscode-toggle-column-selection|eri|1.0.6
prettier-vscode|esb|9.5.0
file-icons|fil|1.0.29
auto-close-tag|for|0.5.14
stylelint-plus|hex|0.56.6
fluent-icons|mig|0.0.17
vscode-docker|ms-|1.22.1
vscode-language-pack-fr|MS-|1.69.7130919
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.241.3
color-highlight|nau|2.5.0
laravel-blade|one|1.32.0
material-icon-theme|PKi|4.19.0
material-product-icons|PKi|1.3.0
vscode-thunder-client|ran|1.16.6
java|red|1.8.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.5
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.42.0
vscode-java-dependency|vsc|0.20.0
vscode-java-pack|vsc|0.24.0
vscode-java-test|vsc|0.35.2
vscode-maven|vsc|0.36.0
vscode-icons|vsc|11.13.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30520716
vsclangdf:30486550

```

</details>

**Comment by Raheemshah2809** [comment]
I am now seeing this as well

**Comment by Trard** [comment]
same

**Comment by realpdm** [comment]
I have the same problem (but black boxes for me because of dark theme maybe?) 

This worked around the problem:
open command pallete ( cmd+shift+p )
select configure runtime arguments
add 
```
"disable-hardware-acceleration": true
```

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/154910
