### ISSUE TITLE
Align git command palette interaction with command line

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15534]
- VSCode Version: 1.7

Intuitively I'd expect `git branch -d some_name` to allow me to delete a branch. Other subcommands could be supported the same way, for some the completion item might tell you what it does (like when creating a branch), for others it's fine if it doesn't.

I like how it supports creating a new branch by assuming an unknown name after `git checkout` is a branch to be created. That could be kept almost the same, except the completion item would tell you that it will insert the `-b` option for you.

**Comment by joaomoreno** [comment]
We will very likely go away from this whole feature, as git turns to an extension.
