### ISSUE TITLE
SCM: Strange border around button

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155305]
1. Mouse down in the button, then move outside the button and mouse up

🐛 You get this border:

![image](https://user-images.githubusercontent.com/22350/179243752-5a28e03d-d9b9-4d5b-adb8-ce73b3fcbdcd.png)

Weirdly enough that's not the same border you get when tabbing onto the button:

![image](https://user-images.githubusercontent.com/22350/179243903-fd7e5919-0d76-44de-8e2c-88dfed06a2b3.png)

**Comment by lszomoru** [comment]
Weird, by performing this gesture you get to focus the `div` inside the button itself. Will see what the best fix is.

**Comment by lszomoru** [comment]
It's a bug in the `ButtonWithDescription` as it does not happen with the "Publish Branch" or "Commit" buttons.
