### ISSUE TITLE
Test: runTask args

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#155350]
Refs  #153145 and #154201

- [x] Windows @rchiodo 
- [x] macOS @bpasero or Linux
- [x] WSL @brettcannon

The run task command can result in a lot of entries/options. Users want to be able to setup a keybinding to trigger a more refined search of this list. The old way of doing this was to provide a string as the `args` in the form of the task's label (for example, `VS Code - Build`). 

There are two new arguments we support:

`taskName`: the task's label (for example, `VS Code - Build`) if there's an exact match or will be used as a filter. Note that this will take precedence over the `type`

`type`: the task's type that corresponds to the `type` property found in the `tasks.json` file that indicates the extension owner, `shell`, or `process`.

The format is `args: { taskName?: string, type?: string}`

Setup some keybindings and verify that the old and new arguments work.

Authors: @meganrogge @Tyriar 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23155350%0A%0A&assignees=meganrogge,Tyriar)

---

Known issues:
- https://github.com/microsoft/vscode/issues/155087

**Comment by rchiodo** [comment]
Minor nit, but it doesn't seem like the type has to match?

I have this in the keybindings:

```json
  {
    "command": "workbench.action.tasks.runTask",
    "args": { "taskName": "TestTask", "type": "process" },
    "key": "ctrl+shift+t"
  }
```

And a task like so:

```
    {
      "label": "TestTask",
      "type": "shell",
      "command": "echo Hello from user",
      "problemMatcher": [],
      "group": "build"
    }
```

And it still runs the task even though the type is different.

**Comment by meganrogge** [comment]
yeah @rchiodo when a `taskName` is provided, it takes precedence over and ignores `type`
