### ISSUE TITLE
[UI/UX Bug] Broken Open Folder button

### ISSUE THREAD

**Issue by gusbemacbe** [microsoft/vscode#155388]
I have searched the issues before, but I didn't find a similar issue related to this problem. 

Does this issue occur when all extensions are disabled?
Yes

- VS Code Version: Insiders 1.70.0
- OS Version: Arch Linux KDE

Steps to Reproduce:

1. Save as a workspace
2. Remove the folder from the workspace
3. Here is the result (notice the `[Add Folder](command:Open Folder)`)

I remember it used to be a normal blue button before. 

![image](https://user-images.githubusercontent.com/2257024/179359015-288e3b28-0257-4db1-8c68-5a6bbb1d4f86.png)

**Comment by gjsjohnmurray** [comment]
Works OK for me:
![image](https://user-images.githubusercontent.com/6726799/179359822-42f64994-00b2-4ecb-aa04-49b31f542898.png)

What are your exact version details?

**Comment by gusbemacbe** [comment]
@gjsjohnmurray 

```
Version: 1.70.0-insider
Commit: 1cd90cceddf3c413673963ab6f154d2ff294b17c
Date: 2022-07-15T05:17:44.161Z
Electron: 18.3.5
Chrome: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.18.10-arch1-1
```

**Comment by gusbemacbe** [comment]
@gjsjohnmurray 

I replicated the bug.

The button gets broken only when you remove or close the folder from a normal window or a workspace. It also still get broken when you close the workspace. 

The button UI resets only when you create a new file or open a file:

![image](https://user-images.githubusercontent.com/2257024/179360318-1e377767-135a-44bd-a6b5-c1874ad2a1cd.png)

But when you close the file, the button UI gets broken.

**Comment by yume-chan** [comment]
https://github.com/microsoft/vscode/commit/ae86e4c50532d12309dbc1bb7c9579b962fbe42e#diff-342217dc04206248b0fdb1cc61838ebd433e97efd1937fcbdd5dfc346e2155cdL286

This is the last commit with the button being named "Add Folder", unless you have some very obsolete language pack extension installed.

**Comment by gusbemacbe** [comment]
> [ae86e4c#diff-342217dc04206248b0fdb1cc61838ebd433e97efd1937fcbdd5dfc346e2155cdL286](https://github.com/microsoft/vscode/commit/ae86e4c50532d12309dbc1bb7c9579b962fbe42e#diff-342217dc04206248b0fdb1cc61838ebd433e97efd1937fcbdd5dfc346e2155cdL286)
> 
> This is the last commit with the button being named "Add Folder", unless you have some very obsolete language pack extension installed.

@yume-chan, I've tested this bug with all disabled extensions. The button still always gets broken when you close the folder, the workspace, or the file.

**Comment by yume-chan** [comment]
I tried that `Reload With Extensions Disabled` command won't disable language packs.

**Comment by gjsjohnmurray** [comment]
I think the Arch Linux distributions are rebuilds and maybe do something weird to add the "built-in" Git extension.

**Comment by gusbemacbe** [comment]
I saw two languages packs were installed and enabled:

![image](https://user-images.githubusercontent.com/2257024/179361577-4fd0089d-917c-483c-8806-2e6ed86f3b80.png)

I uninstalled them and replicated the bug, then the button still gets broken:

![image](https://user-images.githubusercontent.com/2257024/179361599-f8629d11-dc08-46f3-a8d6-a871065bd7c8.png)

I ran the command `Configure Display Language` and selected again English. I replicated the bug. The button doesn't get broken when you close the file.

It seems to turn that the problem is in the foreign language packs.

**Comment by gusbemacbe** [comment]
@TylerLeonhardt 

I have tested. It worked. The problem was in British English language extension. 

> The English (UK) language pack was deprecated and unlisted on the marketplace because it hasn't been updated in a very very long time.

How can I contribute with the repository, translating VSCode to British English and European Portuguese?

**Comment by TylerLeonhardt** [comment]
> How can I contribute with the repository, translating VSCode to British English and European Portuguese?

At the moment, we don't have a good procedure for this as strings in the codebase can be volatile. However, we do want to make it easy for folks to contribute new languages that we can't cover so stay tuned.
