### ISSUE TITLE
Code asks for git credentials even with a credential helper set up

### ISSUE THREAD

**Issue by brudgers** [Microsoft/vscode#15530]
Constantly getting popups asking for my login. I don't want to turn off fetch.

I've got credential caching turned enabled in the Git's credential-helper. It doesn't make any difference. I get a modal dialog box asking for my credentials every few minutes.

On top of that, the dialog box doesn't scale to my 4k display, so it's really tiny (as in unreadable) with Xmonad and steals focus from whatever application I'm in.

Googling for answers doesn't provide Visual Studio Code help, just random internet advice that may be for Linux or may be for Windows with ptty.

Really it's pretty bad. At least put up a help page and get it ranked.

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-emacs|hiro-sun|0.1.1|

---

Steps to Reproduce:

1. Install Visual Studio Code
2. Start it in a repository under Git version control with a remote source
3. Type in password for SSH key
4. Repeat a few minutes later
5. Repeat a few minutes later
6. Google for a solution
7. Try solution
8. Type in password
9. Try restarting VS Code
10. Type in password
11. Type in password
12. GOTO 6

**Comment by bgse** [comment]
What specific Linux are you using? I only ever get asked once for my ssh key passphrase, worked on Fedora21, Fedora23 and Ubuntu16.04 for me.

**Comment by brudgers** [comment]
Ubuntu 16.04

**Comment by joaomoreno** [comment]
This is strange. You shouldn't see a credential dialog at all, if you have a credential manager correctly set up. Which credential manager are you using? How did you set it up? When you `git fetch` from the command line, does git ask you for you password all the time too?

**Comment by brudgers** [comment]
João

What would be the technically correct way to determine that and provide the
accurate information in answer to your request?

Ben

**Comment by joaomoreno** [comment]
Open a terminal (eg gnome terminal) window, `cd` to the git controlled workspace and run `git fetch` from there. Does it ask for your credentials?

**Comment by brudgers** [comment]
There was a keyring issue related to changing Linux logins.

**Comment by davidcoleman007** [comment]
this is happening on windows too.  Today, with the latest version of vsc.

**Comment by PeterOsama** [comment]
i am facing this problem for 2 days 
can`t find any working solution

**Comment by yamcenutzer** [comment]
same here broken in windows and linux incarnations of 1.13, 1.14
