### ISSUE TITLE
matching bracktes and quotes auto replace

### ISSUE THREAD

**Issue by efirvida** [microsoft/vscode#15532]
Hi,

Here’s a feature request for a thing that I alwys want to have, and I think that may be part of the auto creation of the closed brackets.
It's really coll that when I open a brcket or quotes auto appear its closing pair. but wat I want is taht I cant change the created/auto created bracket by another even if there is code/text in betwen them, without having to jumpe to its matching pair.

some usages example for a exa mple turn python list into a generator or set comprehensions
```python
list_ = [x for x in rage(5)]  # -> list
gen_ = (x for x in rage(5))  # -> generator
set_ = {x for x in rage(5)}  # -> generator
```
or a quoted example:
```
"The quick brown fox jumps over the lazy dog" -> double cuotes
'The quick brown fox jumps over the lazy dog' -> single cuotes
```

**Comment by ramya-rao-a** [comment]
So you are saying that you want a way to change for example `[abc]` to `{abc}` ?

**Comment by efirvida** [comment]
yes that is it, "abc" to 'abc' and so on

**Comment by ramya-rao-a** [comment]
@aeschli @alexandrudima Feature Request ?

**Comment by diegoandresalvarez** [comment]
+1 for this
