### ISSUE TITLE
Updating a terminal's width affects its status icon

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155308]
I wasn't sure if there was already an issue for this: https://github.com/microsoft/vscode/issues/155163#issuecomment-1184872077

Here's the recording:

![Recording 2022-07-15 at 16 44 45](https://user-images.githubusercontent.com/22350/179247148-c0931d87-72ad-4d18-8017-7cd6c92f819d.gif)

**Comment by joaomoreno** [comment]
It's interesting that I only noticed it last Friday. Is it a coincidence?

**Comment by Tyriar** [comment]
@joaomoreno I think it's more likely to happen here because of the reconnect, pretty sure it's the same underlying cause though.

**Comment by joaomoreno** [comment]
Makes sense thanks!
