### ISSUE TITLE
Double workspace trust prompt, after making a decision

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#155383]
1. Open a trusted workspace
2. `File > Open File` and pick a file outside the workspace
3. You'll get a dialog asking `Do you trust the authors of these files?`, choose `Open in Restricted Mode`

🐛 A new window comes up with a dialog asking pretty much the same in a different way:

![image](https://user-images.githubusercontent.com/22350/179353462-6efddb5f-f86c-454b-83e9-c639d2eaa22c.png)

**Comment by sbatten** [comment]
this is being tracked in this issue https://github.com/microsoft/vscode/issues/155227 which while closed still needs work
