### ISSUE TITLE
Allow showing and hiding individual items in the title bar with a right-click menu

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#155345]
This presents a special challenge on Windows as we do not receive mouse events when right clicking draggable regions: https://github.com/electron/electron/issues/24893

I've leveraged [this PR](https://github.com/microsoft/vscode/pull/155276) to try out intercepting the events in the main thread and passing the necessary information to the render process.

**Comment by tjx666** [comment]
@sbatten
How to restore the toolbar item after I remove it...
I find I can't find a way to restore it even restore settings sync data

**Comment by sbatten** [comment]
This particular issue refers to this menu 
<img width="250" alt="image" src="https://user-images.githubusercontent.com/6561887/180264920-09aa423d-876b-4ece-883b-c6498a4a65b2.png">


You can right click to restore any unchecked item. If you are referring to individual toolbar items e.g. the layout controls items menu below, you can right click any other item in the toolbar to restore unchecked items.
<img width="185" alt="image" src="https://user-images.githubusercontent.com/6561887/180265113-f0fdbed4-66b8-482d-81e5-d997013b28ac.png">

**Comment by tjx666** [comment]
@sbatten

I hide the codeRunner icon, but can't find it after I hide it.

![Snipaste_2022-07-21_14-16-22](https://user-images.githubusercontent.com/41773861/180273955-0df50e5e-37e0-4b5b-a816-ecd0e4c00bb8.png)


<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/180273779-ba6e0429-46d9-4583-bf46-73f1ce857d1a.png">
