### ISSUE TITLE
after reload, task terminals don't have the `Task` type

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#155306]
Also `waitOnExit` is not happening 

![Screen Shot 2022-07-15 at 7 37 12 AM](https://user-images.githubusercontent.com/29464607/179245891-a61c587a-f8df-408d-ad6b-8885b039e443.png)

**Comment by meganrogge** [comment]
also, seeing this after deleting one of the task terminals and now the build command does not work
![Screen Shot 2022-07-15 at 7 39 04 AM](https://user-images.githubusercontent.com/29464607/179246118-4e1a6ac5-0e5f-434e-948e-f097bcaae390.png)

**Comment by meganrogge** [comment]
works again after reloading
![Screen Shot 2022-07-15 at 7 40 37 AM](https://user-images.githubusercontent.com/29464607/179246423-e85bbea5-3945-4342-bdf3-db582a6d1df9.png)

**Comment by meganrogge** [comment]
The fix will actually be pretty involved and the `type` missing is the least of our concerns actually.

Right now, we create the terminal using only `attachPersistentProcess` on revive which does not have slc like `waitOnExit` or `type`. should we save `shellLaunchConfig` on that ? @Tyriar thoughts would be appreciated.

the other idea would be to just re-run the tasks on window reload and kill the old terminals.

the trade-off is retaining layout info for most of the shell launch config

**Comment by meganrogge** [comment]
I think we've got to save more state on `attachPersistentProcess`

**Comment by meganrogge** [comment]
at the least, `type` and `waitOnExit`

**Comment by meganrogge** [comment]
also `isFeatureTerminal` and `hideFromUser` probably

**Comment by Tyriar** [comment]
> make those properties settable after creation instead of readonly?

This seems like the right approach as we can't persist functions. More details in https://github.com/microsoft/vscode/pull/155346#discussion_r923790979
