### ISSUE TITLE
Create a "TypeHierarchyProvider" api for visualising type hierarchies

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#15533]
(Split from #15485)

Dart Code has had requests for viewing/navigating [type hierarchies](https://github.com/Dart-Code/Dart-Code/issues/133). We've [implemented](https://github.com/Dart-Code/Dart-Code/pull/190) this for now using the pick-list, but we had to make compromises to fit it into a flat list.

Some other editors have this functionality and it's a concept that's not specific to Dart, so it might make sense as a provider that can be implemented by extensions.

Here's an image of it in another editor and also how we've managed to implement it currently.

![687474703a2f2f68656c702e65636c697073652e6f72672f6e656f6e2f746f7069632f6f72672e65636c697073652e6a64742e646f632e757365722f67657474](https://cloud.githubusercontent.com/assets/1078012/20324242/b2c545f0-ab77-11e6-9cbb-f107c940a09c.png)
![c26454f6-8e17-11e6-9df1-046930178341](https://cloud.githubusercontent.com/assets/1078012/20324241/b2c55da6-ab77-11e6-8c1d-423c903e8b43.png)

**Comment by fwcd** [comment]
Any progress on this one? I would really love to have this feature in VSCode.

**Comment by KamasamaK** [comment]
@fwcd Not for VS Code native yet, but there has been recent activity on the LSP implementation at Microsoft/vscode-languageserver-node#426, which when completed generally translates into a very similar native API. Of course, there's also a matter of the UI.

**Comment by tomhanax** [comment]
We have call hierarchy now, which is perfect. How it is going with type hierarchy? This is IMHO somewhat essential functionality in typed languages like TypeScript, Java...

**Comment by akaroml** [comment]
+1 from Java perspective. Type Hierarchy is also super useful for Java users.

**Comment by jrieken** [comment]
fyi - we do have an API proposal for this, the LSP counter part is quite far already, and the UI is being worked on: https://github.com/microsoft/vscode/blob/cf77875d5c3aac2a7fe83e64c4310ab27213d512/src/vs/vscode.proposed.d.ts#L3070

**Comment by jrieken** [comment]
Keeping this issue open to finalize the API

**Comment by jrieken** [comment]
Done. The API is now finalized, there is "Peek Type Hierarchy" and "Show Type Hierarchy" command. Special thanks to @Eskibear who did all of this 👏

**Comment by jrieken** [comment]
To verify make sure that latest<sup>1</sup> `vscode.d.ts` contains [`vscode.languages.registerTypeHierarchyProvider`](https://github.com/microsoft/vscode/blob/9a21b536639c2d986c50fb51b7da67bafdb50c9b/src/vs/vscode.d.ts#L11659-L11659) and that it is fully documented
