### ISSUE TITLE
Provide ability to prioritize language extensions for intellisense

### ISSUE THREAD

**Issue by merddyin** [microsoft/vscode#155324]
First, while I am aware that I can disable different extensions, I routinely have multiple windows open with different projects, and often needing different languages. As I am sure is the case with most languages though, I often need support for a lot of different file types and languages, such that it would be difficult to effectively get all the right ones every time when selecting individually. The challenge with this is in the performance of intellisense and auto-complete, where often times I will need to wait up to 20-30 seconds before the editor figures out what to show me, and often times it never does show me the right thing.

What would be really helpful to me would be the ability to prioritize extensions, in terms of intellisense, in addition to whatever processing it does automatically based on the file type. For example, with PowerShell, I obviously have PowerShell itself, but I also will possibly use XML, HTML, YAML, C#, and dozens of other languages, and it won't always be in a language specific file. That said, I personally don't often us much in terms of YAML or XML, but I have increasingly been leveraging C#, and I occasionally use HTML when formatting a report or something. With this capability, I could set the priorities so that the first things that come up for intellisense would be the items I most use. If it's supposed to prioritize on it's own, then it does a poor job of it. 

An alternative approach that might be viable is to provide a 'profile' based approach, where I can specify a set of enabled/disabled extensions and save it as a 'profile' that I can access quickly. I can then at least set up several profiles for different focuses and improve the experience that way.

**Comment by jrieken** [comment]
closing this as dupe
