### ISSUE TITLE
Notebook does not scroll when dragging a cell

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode#155309]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0-insider Commit: e0a65a97d4f349cf11a7cae804a5553ccb412528
- OS Version: MacOS 12.4

Steps to Reproduce:

1. Open the Titanic.ipynb notebook located at https://github.com/claudiaregio/data-science.
2. Drag a cell in the middle of the notebook either up or down.
3. Notice that the notebook does not scroll when dragging.

https://user-images.githubusercontent.com/686963/179248794-fce34332-2a7e-4e39-b24b-91fb12568f33.mp4

**Comment by roblourens** [comment]
This has been the case for a while apparently.

@mjbvz I think you have made some editor dnd changes in the past couple months, could that have affected this? We rely on normal listView dnd behavior for the scrolling.

**Comment by roblourens** [comment]
Thanks @mjbvz!
