### ISSUE TITLE
Task command not registered on load

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#155336]
1. Open a folder
2. Immediately try to run task
3. 🐛 Says task command not found

![Recording 2022-07-15 at 14 48 02](https://user-images.githubusercontent.com/4544166/179291293-822382b7-c47e-44bd-8c73-2b429a0a9488.gif)

**Comment by meganrogge** [comment]
What commit is that insiders based on? I believe I fixed this yesterday.

**Comment by lramos15** [comment]
It says there is no updates for me but this is 1cd90cceddf3c413673963ab6f154d2ff294b17c

**Comment by lramos15** [comment]
> Is that in oss? Hard to tell

No this is just todays insiders. I can test again on monday if you'd like

**Comment by meganrogge** [comment]
Thanks can you repro in oss?

**Comment by meganrogge** [comment]
Can repro when running the task command but not ctrl+shift+b. so this is a diff't bug

**Comment by joaomoreno** [comment]
Reopen due to revert: https://github.com/microsoft/vscode/pull/155468
