### ISSUE TITLE
Ability to limit which processes the debugger attaches to in launch.json

### ISSUE THREAD

**Issue by davecardwell** [microsoft/vscode#155300]
I would like a configuration option in `launch.json` to limit the processes the debugger will attach to when using _Debug: Start Debugging_.

For example, in a Node.js project my launch config runs a `script` from `package.json` which in turn runs another couple of `script`s. It is not necessary for the debugger to attach to the three `pnpm` processes, `swc`, or `nodemon`, all of which slow down the launch.

Ideally I would be able to add a filter like the `debug.javascript.autoAttachSmartPattern` setting, where I would perhaps limit to attaching to `"${workspaceFolder}/dist/**"`.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode-js-debug/issues/1246 🙂
