### ISSUE TITLE
Multiple restarts of TSServer

### ISSUE THREAD

**Issue by michaelo-spindance** [microsoft/vscode#155328]
Issue Type: <b>Bug</b>

Received a warning notification that the typescript extension was restarted a number of times.

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:51.333Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.15.40-0-virt

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 431ae70f-ee3f-463d-81e2-7e540d0b4944|
|Screen Reader|yes|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Dopple Infra @ rancher-desktop|
|OS|Linux x64 5.15.40-0-virt|
|CPUs|06/9e (4 x 2303)|
|Memory (System)|3.85GB (1.29GB free)|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
docs-visual-areas|doc|0.2.1
terraform|has|2.23.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
material-icon-theme|PKi|4.19.0
vscode-icons|vsc|11.13.0
aws-toolkit-vscode|ama|1.45.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.14.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.5.0
copilot|Git|1.31.6194
rest-client|hum|0.25.0
vscode-docker|ms-|1.22.1
vscode-jest|Ort|4.6.0
code-spell-checker|str|2.3.0
vscodeintellicode|Vis|1.2.22

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30520717
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
