### ISSUE TITLE
Translations in Debug viewlet

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15537]
- VSCode Version: 1.7.2 smoke test
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open code with locale DE, open debug viewlet
2. "All Exceptions", "Uncaught Exceptions" are not translated
3. A watch expression that can't be evaluated shows an untranslated: "not available"

**Comment by weinand** [comment]
The options "All Exception" and "Uncaught Exceptions" are created with the correct translations when a debug extension is used for the first time:

![2016-11-16_09-01-50](https://cloud.githubusercontent.com/assets/1898161/20339207/5984718c-abdb-11e6-99a5-f7208e14ca99.png)

If the locale is changed later, the options are not updated.
@isidorn could you update the options if you notice that the labels don't match any more?

"not available" message: when the debug adapter is running a correct error message is shown (see screenshot above). But when debug session terminates, VS Code shows an untranslated message:

![2016-11-16_09-05-22](https://cloud.githubusercontent.com/assets/1898161/20339298/d1d12e82-abdb-11e6-95a7-92514d3f9de2.png)

**Comment by isidorn** [comment]
'Not available' was missing a localize call - fixed that.
As for the labels of exception breakpoints I always update them on the ux side once a debug session is started - since these labels are coming from the debug adapter.
So if the locale is changed later the labes should update once a debug session is started.

**Comment by weinand** [comment]
@isidorn indeed, the exception options turned to English when starting a new debug session with English locale. So this works as designed.
