### ISSUE TITLE
vscode configuring new shell to open in the current project directory

### ISSUE THREAD

**Issue by efirvida** [Microsoft/vscode#15531]
Hi i´m trying to reconfigure the terminal of my vscode proyect to use a terminal provided by a .bat script that works like this:

`shell.bat CHANGE_PATH <path where the shell open>`

and I configure my tterminal like this

```
{
    "terminal.integrated.shell.windows": "<path to shell.bat>",
    "terminal.integrated.shellArgs.windows": ["CHANGE_PATH","${workspaceRoot}"]
}
```

but the ${workspaceRoot} variable did't work and the shell is opened on its default path

**Comment by Tyriar** [comment]
This is currently not built-in. I did make an extension that exposes a command that does just this though https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here
