### ISSUE TITLE
Some cell output is missing when a cell is deleted and then restored

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode#155320]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0-insider e0a65a97d4f349cf11a7cae804a5553ccb412528
- OS Version: MacOS 12.4

Steps to Reproduce:

1. Clone the notebook at https://github.com/claudiaregio/data-science
2. Run the notebook
3. Remove cell 5 (pandas profiling report)
4. Restore cell 5 with Cmd+Z
5. Notice that the status items from the profiling report are gone, but the output format selector is still there

https://user-images.githubusercontent.com/686963/179258641-18a5c4e6-95fd-4842-ab80-ed05127e7a44.mp4

**Comment by rebornix** [comment]
This issue is gone now.
