### ISSUE TITLE
Menu item not translated

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15538]
While smoke testing 1.7.2 eb1f17eff8393fa2ab0b1bd7d12bd63fc99146b6

![image](https://cloud.githubusercontent.com/assets/4033249/20326881/874f7298-ab3f-11e6-8dca-2bed97fe75b5.png)

![image](https://cloud.githubusercontent.com/assets/4033249/20326884/8c717866-ab3f-11e6-955f-1e813322624a.png)

**Comment by ramya-rao-a** [comment]
These are Mac specific menu items, am not sure if these are tracked in our list of localization strings.
@dbaeumer Thoughts?

**Comment by dbaeumer** [comment]
Actually they are not in our translation DB. I will close this issue. To have them translated you need to switch Mac OS to the language of choice.
