### ISSUE TITLE
[json] command to sort JSON document by property name

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#155312]
Especially when working the the settings JSON file I'd love to have a way to sort the file by property name

**Comment by tjx666** [comment]
I have something suggestion about this:

1.this command should support sort selection fields, not only whole json/jsonc
2.should keep the comments position with the property after sorted

**Comment by tjx666** [comment]
@aiday-mar any plan to support sort selected fileds?

You can see my seeting.json, it would be more useful to support only sort selected fields.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/220980181-a5fe03ec-0061-48e1-b5e5-46aedbc17124.png">
