### ISSUE TITLE
Support OSC 8 hyperlink support

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155445]
Running the following in bash/zsh should give special links with dashed underlines:

```sh
printf '\e]8;id=abc;http://example.com/\e\\This is a link中国\e]8;;\e\\\n'
```

Upstream issue: https://github.com/xtermjs/xterm.js/issues/1134
WIP: https://github.com/xtermjs/xterm.js/pull/3904

**Comment by ssbarnea** [comment]
Errata, correct PR is https://github.com/xtermjs/xterm.js/pull/4005

**Comment by Tyriar** [comment]
Oh this already existed: https://github.com/microsoft/vscode/issues/39278
