### ISSUE TITLE
Tab Key Does not work when in editor section

### ISSUE THREAD

**Issue by Greggles182** [microsoft/vscode#155428]
Issue Type: <b>Bug</b>

Title a file something ending in .py
Write some code
Accidentally de-tab a tabbed in object using backspace
Try to re-tab it
I Can't.

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 6.1.7601
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (23.74GB free)|
|Process Argv|--crash-reporter-id 2219e212-8675-4c1e-8d00-2939b3fdc657|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-database|baj|2.2.3
vscode-eslint|dba|2.2.6
vscode-html-css|ecm|1.13.0
magick-image-reader|ely|0.5.0
discode|eve|2.0.0
vscode-firefox-debug|fir|2.9.7
terminal|for|0.0.10
video|kan|1.0.5
vscode-JS-CSS-HTML-formatter|lon|0.2.3
rainbow-csv|mec|2.4.0
csharp|ms-|1.25.0
mssql|ms-|1.15.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1201981810
cpptools|ms-|1.10.8
open-php-html-js-in-browser|Pri|2.2.0
ruby|reb|0.28.1
git-merger|sha|0.4.1
html5-boilerplate|sid|1.1.1
vscode-zipexplorer|sle|0.3.1
wav-preview|suk|2.0.4
zip-file-system|Tom|2.0.0
pdf|tom|1.2.0
cmake|twx|0.0.17
luna-paint|Tyr|0.15.0
vscode-arduino|vsc|0.4.12
vscode-ruby|win|0.28.0
markdown-pdf|yza|1.4.4
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30520717
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? If not, this is caused by one of them
