### ISSUE TITLE
Unable to read file errors are being localized and showing up in telemetry

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155492]
https://github.com/microsoft/vscode/blob/8f58d9df260144d72545f66a964e88232d751f5f/src/vs/platform/files/common/fileService.ts#L569-L574

This shows up in telemetry: `无法读取文件`

Should `FileOperationError` extend `NoErrorTelemetry`?

https://vscode-errors.azurewebsites.net/card?ch=f3528d481b366b24321c382d5e5849f4c7d65248&bH=aa9e18ff-8c8f-1c63-d265-d1d3cb2ba855
https://vscode-errors.azurewebsites.net/card?ch=f3528d481b366b24321c382d5e5849f4c7d65248&bH=749131eb-6952-232e-4533-df818832582b

**Comment by bpasero** [comment]
As discussed, I can review a PR. One interesting aspect of file errors are that we use the error name as a way to deserialise errors from extensions on the renderer:

https://github.com/microsoft/vscode/blob/b3218963c4819162c87ff90606eec5294e32d28d/src/vs/platform/files/common/files.ts#L582-L593
