### ISSUE TITLE
Intellisense popup suggestions are too invasive/frequent, impact productivity, and mangle my code

### ISSUE THREAD

**Issue by mikeburdick** [microsoft/vscode#155410]
Issue Type: <b>Feature Request</b>

When I write code in VS Code I am constantly closing down intellisense popup suggestions.  Worst case is when a popup will actually update the code I am writing and mangle it.

If I want intellisense help I'll press Ctrl+space or Ctrl+shift+space when I want it.

Give me a easy setting to disable ALL intellisense popups unless I press Ctrl+space and ask for help.

I am a experienced developer and touch typist who does not need intellisense help.  Having to constantly press the Esc key to close a intellisense popup menu while I am writing code is killing my productivity and making me hate VS Code.

I have tried to disable this by having this in my settings.json but it doesn't stop the popups while I am writing code:

    "editor.quickSuggestions":{
      "other": "off",
      "comments": "off",
      "strings": "off"
    }

After some more searching it looks like adding this to settings.json stops that jarring parameter window popping up and covering up the code I want to see.

"editor.parameterHints.enabled": false,

But I still get suggestions for Properties Names and so on.

What do I need to do to stop ALL intellisense suggestions from popping up?

I understand how this is useful for more beginning programmers but while I am programming I really don't want anything popping up covering code I may be looking at as I write code.

I think having a single setting to disable all Intellisense  popups while writing code would be useful.  From searching the internet I don't think I am alone in this thinking.

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:21:24.514Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by jrieken** [comment]
> What do I need to do to stop ALL intellisense suggestions from popping up?

Also configure this setting: `editor.suggestOnTriggerCharacters`

**Comment by mikeburdick** [comment]
Thanks that last setting is perfect,  Ctrl+Space and Ctrl+Shift+Space still work when I need them and I can write code without being disturbed and stay in the zone...
