### ISSUE TITLE
Change the comments highlighting color from dark green to light green

### ISSUE THREAD

**Issue by stech11845** [microsoft/vscode#155447]
The comments highlighting color is a bit hard to look at since it is dark. I want it to be light.

If there's a different usage for light green  already please forgive me.

**Comment by gjsjohnmurray** [comment]
If you can't find a color theme that suits you better then you can customize individual colors of any theme. See https://code.visualstudio.com/api/extension-guides/color-theme#syntax-colors and subsequent sections.

**Comment by aeschli** [comment]
Is this for the Dark+ (Default) Theme?
Sorry, no changes planned there as changes affect many users that might not like the change.

As mentioned by John, you can customize the theme in the settings or check out one of the many themes available on the marketplace.

**Comment by stech11845** [comment]
> Is this for the Dark+ (Default) Theme? ![image](https://user-images.githubusercontent.com/6461412/179965747-ff04a3a9-090c-4f58-9e75-4d3b51607faa.png) Sorry, no changes planned there as changes affect many users that might not like the change.
> 
> As mentioned by John, you can customize the theme in the settings or check out one of the many themes available on the marketplace.

I'll make an extension for those who are interested: https://github.com/colors-extension-vscode
