### ISSUE TITLE
Error telemetry: Cannot read properties of null (reading 'replace')

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155498]
Deminified Stack
TypeError: Cannot read properties of null (reading 'replace')
[at n.rewriteVsCodeResourceUrls in src/vs/workbench/contrib/webview/browser/webviewElement.ts:636:5](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L636:5)
[at n.set html [as html] in src/vs/workbench/contrib/webview/browser/webviewElement.ts:623:30](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/contrib/webview/browser/webviewElement.ts#L623:30)
at <anonymous> in out/vs/workbench/workbench.desktop.main.js:1293:41283
[at withWebview in src/vs/workbench/contrib/webview/browser/overlayWebview.ts:352:4](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/contrib/webview/browser/overlayWebview.ts#L352:4)
[at w.set html [as html] in src/vs/workbench/contrib/webview/browser/overlayWebview.ts:254:8](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/contrib/webview/browser/overlayWebview.ts#L254:8)
at Pa.$setHtml in out/vs/workbench/workbench.desktop.main.js:1698:75452
[at v._doInvokeHandler in src/vs/workbench/services/extensions/common/rpcProtocol.ts:455:17](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L455:17)
[at v._invokeHandler in src/vs/workbench/services/extensions/common/rpcProtocol.ts:440:32](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L440:32)
[at v._receiveRequest in src/vs/workbench/services/extensions/common/rpcProtocol.ts:370:19](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L370:19)
[at v._receiveOneMessage in src/vs/workbench/services/extensions/common/rpcProtocol.ts:296:10](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L296:10)
[at <anonymous> in src/vs/workbench/services/extensions/common/rpcProtocol.ts:161:42](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/extensions/common/rpcProtocol.ts#L161:42)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/common/event.ts#L735:24)
[at a.fire in src/vs/base/parts/ipc/common/ipc.net.ts:638:19](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/parts/ipc/common/ipc.net.ts#L638:19)
[at g._receiveMessage in src/vs/base/parts/ipc/common/ipc.net.ts:959:23](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/parts/ipc/common/ipc.net.ts#L959:23)
[at <anonymous> in src/vs/base/parts/ipc/common/ipc.net.ts:832:73](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/parts/ipc/common/ipc.net.ts#L832:73)
[at b.invoke in src/vs/base/common/event.ts:572:17](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/common/event.ts#L572:17)
[at r.deliver in src/vs/base/common/event.ts:774:22](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/common/event.ts#L774:22)
[at o.fire in src/vs/base/common/event.ts:735:24](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/common/event.ts#L735:24)
[at o.acceptChunk in src/vs/base/parts/ipc/common/ipc.net.ts:382:21](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/parts/ipc/common/ipc.net.ts#L382:21)
[at <anonymous> in src/vs/base/parts/ipc/common/ipc.net.ts:338:51](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/parts/ipc/common/ipc.net.ts#L338:51)
[at Socket.O in src/vs/base/parts/ipc/node/ipc.net.ts:60:4](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/parts/ipc/node/ipc.net.ts#L60:4)
at Socket.emit (node:events:390:28)
at addChunk (node:internal/streams/readable:315:12)
at readableAddChunk (node:internal/streams/readable:289:9)
at Socket.Readable.push (node:internal/streams/readable:228:10)
at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)

https://vscode-errors.azurewebsites.net/card?ch=b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a&bH=3e104e4f-c261-b459-0922-8c95d5a5f85c

**Comment by mjbvz** [comment]
Only 2 machines are hitting this and I suspect they are using custom builds of VS Code. Will update this to throw an error instead of having the null access crash
