### ISSUE TITLE
Error telemetry: WebAssembly is not defined

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155494]
https://vscode-errors.azurewebsites.net/card?ch=b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a&bH=d8cd3fcd-4951-5768-671e-5eca06beb352

Deminified Stack
ReferenceError: WebAssembly is not defined
at z in https://main.vscode-cdn.net/stable/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/node_modules/vscode-oniguruma/release/main.js:1:7821
at Object.n [as default] in https://main.vscode-cdn.net/stable/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/node_modules/vscode-oniguruma/release/main.js:1:6044
at <anonymous> in https://main.vscode-cdn.net/stable/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/node_modules/vscode-oniguruma/release/main.js:1:4636
at n.loadWASM in https://main.vscode-cdn.net/stable/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/node_modules/vscode-oniguruma/release/main.js:1:4868
[at k._doGetVSCodeOniguruma in src/vs/workbench/services/textMate/browser/abstractTextMateService.ts:410:25](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L410:25)
at async Promise.all (index 1)
[at async k._getOrCreateGrammarFactory in src/vs/workbench/services/textMate/browser/abstractTextMateService.ts:229:45](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L229:45)
[at async Object.createTokenizationSupport in src/vs/workbench/services/textMate/browser/abstractTextMateService.ts:264:29](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/textMate/browser/abstractTextMateService.ts#L264:29)
[at async R._create in src/vs/editor/common/tokenizationRegistry.ts:146:17](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/editor/common/tokenizationRegistry.ts#L146:17)
[at async A.getOrCreate in src/vs/editor/common/tokenizationRegistry.ts:72:3](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/editor/common/tokenizationRegistry.ts#L72:3)

**Comment by alexdima** [comment]
It looks like we get loaded on a browser which is not supported (doesn't have `WebAssembly`).

**Comment by Tyriar** [comment]
@alexdima if this is expected, we should handle the error so it no longer shows up in error telemetry

**Comment by alexdima** [comment]
@Tyriar Please see https://caniuse.com/wasm . We support modern browsers and they all support wasm. So it is unexpected that `WebAssembly` is not present. What I assume is happening is that `https://vscode.dev` is opened on an unsupported browser, like for example someone decides to open it in a 5 yo browser shipped with a TV or something. We do not add try-catch around our DOM APIs. I see how this is annoying on the error telemetry website, but I think we should simply not report error telemetry from unsupported browsers instead of polluting our code with unnecessary checks.

**Comment by Tyriar** [comment]
> but I think we should simply not report error telemetry from unsupported browsers instead of polluting our code with unnecessary checks.

@lramos15 thoughts?

**Comment by lramos15** [comment]
> > but I think we should simply not report error telemetry from unsupported browsers instead of polluting our code with unnecessary checks.
> 
> @lramos15 thoughts?

Makes sense, do we have a `isSupportedBrowser` check we can place in the error handler?

**Comment by alexdima** [comment]
> Makes sense, do we have a `isSupportedBrowser` check we can place in the error handler?

Not that I'm aware of. cc @bpasero in case we have something like that

**Comment by bpasero** [comment]
I am not aware of such a function.

**Comment by lramos15** [comment]
I have't seen this in awhile and due to lack of an easy check, I'm going to close for now. I think the hype of opening vscode.dev on your toaster has died down and more browsers will continue to adopt WASM support.
