### ISSUE TITLE
Add "Open Side Bar View" action

### ISSUE THREAD

**Issue by chenjianhua** [microsoft/vscode#155454]
Analogically to "Next Primary Side Bar View", "Previous Primary Side Bar View" commands it should open the specified sidebar view based on the provided viewid.

I think the Focus List command is very good, it can quickly display the search view through the command。

Therefore, I am working on an extension with a similar function, which also requires users to quickly display the extended view through commands, which can help users quickly use the extended view we provide, especially if there are too many views installed in the sidebar when.

Motivation: with increasing versatility of Action Bar being filled with items contributed by extensions it is desirable to navigate quickly among them using this command.

Also, when I develop two extensions, I also need to use a command in one of them to open the view of the other extension, which is a great requirement.

And I've made a sketch for the code, don't know if this will work.

src/vs/workbench/browser/parts/activitybar/activitybarActions.ts

```
registerAction2(
	class OpenSideBarViewAction extends Action2 {
		constructor() {
			super({
				id: 'workbench.action.openSideBarView',
				title: { value: localize('openSideBarView', "Open Side Bar View"), original: 'Open Side Bar View' },
				category: CATEGORIES.View,
				f1: true
			});
		}

		async run(accessor: ServicesAccessor, viewId: string): Promise<void> {
			const viewsService = accessor.get(IViewsService);
			viewsService.openView(viewId, true);
		}
	}
);

```

**Comment by chenjianhua** [comment]
```
registerAction2(
	class OpenSideBarViewAction extends Action2 {
		constructor() {
			super({
				id: 'workbench.action.openSideBarView',
				title: { value: localize('openSideBarView', "Open Side Bar View"), original: 'Open Side Bar View' },
				category: CATEGORIES.View,
				f1: true
			});
		}

		async run(accessor: ServicesAccessor, viewId: string): Promise<void> {
			const viewsService = accessor.get(IViewsService);
			viewsService.openView(viewId, true);
		}
	}
);
```

**Comment by sandy081** [comment]
Why is it specific to Sidebar? A view is location agnostic and I think it has to be generic open view command that takes view id.

**Comment by chenjianhua** [comment]
For example the show run and debug(workbench.view.debug) command, which can quickly open the debug sidebar through the command.I have also developed a plugin and want to quickly open the sidebar of my plugin in the sidebar by creating a command.Is it possible to provide a public command for the plugin to quickly display the plugin's activity bar through commands?Does workbench.action.openSideBarView need to be changed to workbench.action.showSideBarView or workbench.action.selectSideBarView? or other. @sandy081

**Comment by sandy081** [comment]
> I have also developed a plugin and want to quickly open the sidebar of my plugin in the sidebar by creating a command.

We already have commands to open the view you contributed. ID is as follows: `${viewId}.focus`. So I do not think you need any other commands.

**Comment by chenjianhua** [comment]
Thank you very much, this solution solved my big trouble. Thanks again. @sandy081 

`vscode.commands.executeCommand(`${viewId}.focus`);`
