### ISSUE TITLE
Terminal shell integration copy output doesn't respect wrapped lines

### ISSUE THREAD

**Issue by Yanpas** [microsoft/vscode#155402]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.1
- OS Version: arch

Steps to Reproduce:

1. Enable shell integration
2. Open terminal, run this command `python -c 'print ("abc"*80)'`. Most likely it will output 2-3 lines of text
3. Select the output using cursor, paste it to editor -> You've pasted one line of text.
4. Click on blue dot and press copy output, paste-> You've pasted 2-3 lines instead of one! That's the issue.

**Comment by Tyriar** [comment]
Nice find!
