### ISSUE TITLE
Add setting to disable floating cell toolbar

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#155438]
Was scrolling in my notebook to compare the output to my code to check what I was seeing and the cell toolbar is broken and moving with the scroll and covering the code. 
![image](https://user-images.githubusercontent.com/19276747/179421332-9e4ef88b-dc17-40aa-9ae4-587e1ffdaa7e.png)

**Comment by roblourens** [comment]
This is a feature from a few months ago, so that now you can still access the run button and toolbar even when scrolling down to the outputs.

**Comment by roblourens** [comment]
We could have a setting to disable this for people who don't find it useful

**Comment by DonJayamanne** [comment]
A setting has been added to disable/hide the floating cell toolbar
