### ISSUE TITLE
Error telemetry: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155495]
https://vscode-errors.azurewebsites.net/card?ch=b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a&bH=1f3cd9e3-6043-1e1d-97d9-100a8d076600

Deminified Stack
Error: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
[at I.runInTransaction in src/vs/base/browser/indexedDB.ts:121:37](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/base/browser/indexedDB.ts#L121:37)
[at i.doUpdateItems in src/vs/workbench/services/storage/browser/storageService.ts:401:12](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/storage/browser/storageService.ts#L401:12)
[at async i.updateItems in src/vs/workbench/services/storage/browser/storageService.ts:372:16](https://vscode.dev/github/microsoft/vscode/blob/b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a/src/vs/workbench/services/storage/browser/storageService.ts#L372:16)

**Comment by bpasero** [comment]
This could be upstream and https://bugs.chromium.org/p/chromium/issues/detail?id=146284 suggests it could be from running out of disk space. Should we maybe not log these indexed DB errors to telemetry @sandy081 ?

**Comment by Tyriar** [comment]
👍 if we expect the failure e should either catch the error and handle or catch and rethrow as `ErrorNoTelemetry`
