### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by saleesh4u** [microsoft/vscode#155460]
- Issue Type: `Bug`
- Extension Name: `microsoft-authentication`
- Extension Version: `0.0.1`
- OS Version: `Linux x64 5.4.0-122-generic`
- VS Code version: `1.69.1`
- VS Code is starting very slow. This extension is causing the delay.

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1060,
		"activateCallTime": 2,
		"activateResolvedTime": 2029,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.microsoft-authentication",
				"_lower": "vscode.microsoft-authentication"
			},
			"activationEvent": "onAuthenticationRequest:microsoft"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by TylerLeonhardt** [comment]
Can you please follow the instructions for filing a performance issue: https://github.com/microsoft/vscode/wiki/Performance-Issues

That'll help us a ton so we can get to the bottom of this.

**Comment by TylerLeonhardt** [comment]
Closing this now since I linked the doc.
