### ISSUE TITLE
Powerline for WSL terminal (bash) fails

### ISSUE THREAD

**Issue by tjanga** [microsoft/vscode#155463]
Version: 1.70.0-insider (system setup)
Commit: 1cd90cceddf3c413673963ab6f154d2ff294b17c
Date: 2022-07-15T05:16:39.110Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043

I use Powerline to show git status in the terminal window. The last insider's build broke powerline for me. Specifically, it seems to fail when running the powerline script specified in .bashrc

Starting VSCode with a remote WSL session, and attempting to bring up a terminal results in the following error:
```
0: command not found
usage: powerline-daemon [-h] [-r MODULE] [-w WIDTH] [--last-exit-code INT]
                        [--last-pipe-status LIST] [--jobnum INT]
                        [-c KEY.KEY=VALUE] [-t THEME.KEY.KEY=VALUE]
                        [-R KEY=VAL] [-p PATH] [--socket ADDRESS]
                        ext [{left,right,above,aboveleft}]
```

Relevant .bashrc line:

`source $HOME/.local/lib/python3.6/site-packages/powerline/bindings/bash/powerline.sh`

However, starting bash in a external WSL bash terminal works fine, and gives the expected result.

Also, commenting the `source` call in .bashrc and *manually* calling source in the resulting integrated terminal works as well.

So something about the way .bashrc is run in the integrated terminal is breaking. I rolled back VS Code Insiders to 1.69.0 and things are working again. VSCode 1.69.1 stable is also working fine.

**Comment by tjanga** [comment]
This may actually be a dup of https://github.com/microsoft/vscode/issues/155221 

Looking at `powerline.sh`, I think I've narrowed down the problem to the setting of `$PROMPT_COMMAND`

```
VIRTUAL_ENV_DISABLE_PROMPT=1
	if test -z "${POWERLINE_COMMAND}" ; then
		POWERLINE_COMMAND="$("$POWERLINE_CONFIG_COMMAND" shell command)"
	fi
	test "$PROMPT_COMMAND" != "${PROMPT_COMMAND%_powerline_set_prompt*}" \
		|| _powerline_add_status_wrapped_command prepend _powerline_set_prompt
	PS2="$(_powerline_local_prompt left -r.bash 0 0 0 continuation)"
	PS3="$(_powerline_local_prompt left '' 0 0 0 select)"
``` 

Commenting out the || line solves the issue (but for obvious reasons, breaks the script)

**Comment by meganrogge** [comment]
@tjanga what are your terminal settings? sounds like you have enabled the experimental shell integration, correct?

**Comment by tjanga** [comment]
this issue is resolved in:

Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9

Thanks!
