### ISSUE TITLE
Open Recent should show exact match first

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15541]
While smoke testing 1.7.2 eb1f17eff8393fa2ab0b1bd7d12bd63fc99146b6

![image](https://cloud.githubusercontent.com/assets/4033249/20327308/60030b1c-ab41-11e6-9273-da623b4fbc9d.png)

**Comment by bpasero** [comment]
Fixed for January via https://github.com/Microsoft/vscode/commit/8b834d0f890f62ce25684f6b371559b4f4f6a223

**Comment by bpasero** [comment]
* [ ] **To verify:** 
Verify the picker for recent files and folders shows more relevant matches to the top.
