### ISSUE TITLE
Static functions can't be found with typedef

### ISSUE THREAD

**Issue by seirdotexe** [microsoft/vscode#155440]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.70.0 (Insiders)
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

We have the following code:

```js
// server.js
export default class Server {
  constructor() {
    this.a = 1;
  }

  static test() {
    return 1;
  }

  abc() {
    return 1;
  }
}
```

```js
// client.js
export default class Client {
  /**
   *
   * @param {import('./server.js').default} server
   */
  constructor(server) {
    this.server = server;
  }
}
```

Now, this is the result when importing the type of server:
![image](https://user-images.githubusercontent.com/80536518/179421741-aa70f51f-3bda-4793-a264-ac428783e52b.png)

Why is `test` not showing?

**Comment by IllusionMH** [comment]
Looks like it works as expected. Type that is exported from file is type of class instance and therefore only instance fields are available/suggested while static properties/methods are part of constructor function signature.

You need to use `typeof ConstructorFunction` to get type of constructor function that has static properties on it.
You can try `@param {typeof import('./server.js').default} server`

**Comment by seirdotexe** [comment]
Thank you! That sounds about right, learned something new 😅
