### ISSUE TITLE
Explore improvements to Command Center mode switching

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#155458]
The command center interaction to switch modes could be more discoverable and intuitive to use. Tracking UX explorations here.

<img width="515" alt="CleanShot 2022-07-17 at 21 03 28@2x" src="https://user-images.githubusercontent.com/25163139/179443690-b05f7e10-4f73-43ad-a680-b874acbfe71b.png">

**Comment by daviddossett** [comment]
A couple of explorations:

## With Tabs

Probably the most significant departure from what we have. This would make it much more discoverable to switch to the most often used modes. 

![with-tabs](https://user-images.githubusercontent.com/25163139/180492422-e3b3f55e-5602-456d-a0d8-05872db395a0.gif)

## With Icon In Text Field

Since users may miss the existing icon given that the quick pick covers it once the command center is opened, we could move the icon to instead be nested with or nearby the input itself. Icon used here is a placeholder. Not yet sure what would the best to use here.

![with-icon-in-text-field](https://user-images.githubusercontent.com/25163139/180492472-68c79be4-17cf-4026-a601-772a9038a066.gif)

## Change Existing Icon

Simply uses a different icon with the same UX we have today to indicate that there are more options. Icon used here is a placeholder as before.

![change-existing-icon](https://user-images.githubusercontent.com/25163139/180492523-ba0741c0-7e4c-4058-9f4f-afdc2d50501e.gif)

@misolori @jrieken thoughts? I'm most interested in the tabs idea despite it being a bigger change.

**Comment by eamodio** [comment]
I like the direction of the Tabs design, though I'm not entirely sure why but I'm not a fan of exactly how it looks. I think I'd prefer the tabs under the input, but hierarchically that wouldn't really be correct, as the input changes too. Maybe its the left alignment or size/style of the tabs.

**Comment by misolori** [comment]
Agreed that the tab approach feels stronger but I think it's missing the ability to switch modes based on the first character (empty for file search, > for command palette, @ for symbols, etc.) Would definitely be curious to iterate on that concept and making it seamless between switching modes.

Have you considered pinning entries into the quick pick for the modes?

**Comment by daviddossett** [comment]
> I think it's missing the ability to switch modes based on the first character (empty for file search, > for command palette, @ for symbols, etc.)

I've been thinking about ways to handle this. For the permanently pinned tabs, we could just switch to that tab when the character was entered. For options folded into more, we coudl do something slick like hiding the tabs or even just temporarily adding a tab for the active mode. Kind of like how tab overflows tend to work. I'll try a few options and will come back with some examples.

> Have you considered pinning entries into the quick pick for the modes?

I had a sketch for something like this—similar to what you had in mind? Not sure about the input filtering behavior given the pinned mode entries but curious to hear what you had in mind here.

<img width="506" alt="CleanShot 2022-07-26 at 11 33 26@2x" src="https://user-images.githubusercontent.com/25163139/181084776-3a74cd20-6ab6-4e85-9871-7bdb4bfeb828.png">

**Comment by daviddossett** [comment]
## With Tabs

Here's a more complete idea of how tabs could work:
- Common modes are available as visible tabs
- Other modes can be entered by selecting from the "More" list
- Can use the input to automatically switch between modes (instead of manually clicking tabs)
- Clearing the input defaults to the "Go to File" list
- Tabs hide when the current mode isn't available as a visible tab

I also wonder if we could enable users to pin/unpin their own set of tabs. 

https://user-images.githubusercontent.com/25163139/181119176-c8d33fa9-9017-4cf7-a41c-2674fa7cf5d2.mp4

## With Pinned Entries

Also explored how this could work. Definitely a bit lighter and cleaner with the tradeoff that you would have to explictly select the files list now instead of it being the default list. That said, I like that the default view includes a flat list of recent searches/commands.

https://user-images.githubusercontent.com/25163139/181120863-ee758dab-3182-4bf3-b24b-6ac0bff2f0d5.mp4

**Comment by misolori** [comment]
Dropping some additional feedback even though we already talked about this offline:

**Tabs**
- I think, overall, this is a good direction to aim for the future with a possible setting to disable the tabs (for those who don't want them)
- I'd try to style them just like our panel tabs and use the tooltip for the keyboard shortcut
- Would be worth to think about how to tab between the different modes, I remember in Sketch Runner this was smooth, but it gets a little tricky with the first character indicator
- The tabs appear to take up a decent amount of vertical real estate, i wonder if we'd want to have a "compact" version of the tabs? We do that in the secondary side bar but use icons (less helpful here i think). 

**Pinned Entries**
- This feels like a practical thing we could introduce today
- The first entry usually is "selected" in the quick pick, do you envision this starting at the file or modes section?
- A setting for this would also be nice

**Comment by daviddossett** [comment]
Latest options from this week. I have a strong lean towards the first one as something we could do today.

## Prefix Pill + Placeholder Text

https://user-images.githubusercontent.com/25163139/185502225-ee1d6405-2604-491c-bf73-94f06e46ec0f.mp4

A nice bonus here would be showing the name + keybinding on hover:

![CleanShot 2022-08-18 at 14 57 00](https://user-images.githubusercontent.com/25163139/185502419-0f46a78a-e88a-42ca-a7ee-b8b813b83035.gif)

## Tabs

https://user-images.githubusercontent.com/25163139/185501933-71aba1ba-0c62-4237-845c-25cdbce77a01.mp4

cc @TylerLeonhardt

**Comment by misolori** [comment]
Love the simplicity of the character "badge" or "pill", makes it clear that it's the "mode" and can be easier to learn for new users.

**Comment by daviddossett** [comment]
Pushing the pill idea bit further with an idea from @TylerLeonhardt to show other mode optoins on click of the pill + a quick way to see more via the `?` mode.

![CleanShot 2022-08-19 at 10 58 50](https://user-images.githubusercontent.com/25163139/185679684-01944afa-dfce-4698-be4c-f8c5773f694f.gif)

**Comment by Kroc** [comment]
The command centre's clickable region doesn't extend to the top of the window when VSCode is maximized; so it's not a good click-target. Enabling it also increases the title-bar height; which might be okay on HD screens but is yet more lost screen real estate on 1366x768!

**Comment by daviddossett** [comment]
> The command centre's clickable region doesn't extend to the top of the window when VSCode is maximized; so it's not a good click-target. Enabling it also increases the title-bar height; which might be okay on HD screens but is yet more lost screen real estate on 1366x768!

@Kroc could you open a separate issue? I've scoped this one to the mode switching interaction now that there are several active command center UX efforts.

**Comment by daviddossett** [comment]
Cross-posting a demo from #158638 to showcase the latest ideas here:
- Use a "home" view of the command center to showcase available modes w/ friendly names
- Continue to use pills for prefixes, but only show friendly mode name + keybinding on hover/focus. No need for the context menu on click given the above change.

https://user-images.githubusercontent.com/25163139/188745576-d3337aba-db82-4c79-a142-1882f18743b5.mp4

**Comment by daviddossett** [comment]
Closing given the convergence with #158638. Will continue tracking the pill prefix idea specifically in #158064.
