### ISSUE TITLE
new js language extension breaking the core js grammar

### ISSUE THREAD

**Issue by ricmed205** [Microsoft/vscode#1554]
I tried to make an extension to support this js grammar (https://github.com/Benvie/JavaScriptNext.tmLanguage) following the instructions with the yo code module. Not only it does not work, it breaks the core javascript highlighting. Why is that?

**Comment by aeschli** [comment]
@ricmed205 You have to give more information on what was in your package.json.

**Comment by ricmed205** [comment]
@aeschli 

```json
{
	"name": "js-next",
	"displayName": "Javascript Next",
	"description": "Javascript Next Highlighting",
	"version": "0.0.1",
	"publisher": "ricmed205",
	"engines": {
		"vscode": "^0.10.1"
	},
	"categories": [
		"Languages"
	],
	"contributes": {
		"languages": [{
			"id": "js",
			"aliases": ["JavaScript Next", "js"],
			"extensions": [".js",".htc",".jsx"],
			"configuration": "./js.configuration.json"
		}],
		"grammars": [{
			"language": "js",
			"scopeName": "source.js",
			"path": "./syntaxes/js.tmLanguage"
		}]
	}
}
```

Excuse my ignorance (I'm a github newbie), why close the issue when needs more info?

**Comment by aeschli** [comment]
The problem is, your extension registers the same extension as the built-in JavaScript extension under a different language id.
Since the December release we have a better Javascript grammar that also supports ES6.
If you still want to replace the grammar, all you have is an section 'grammar'
Note that the built-in JavaScript has id `javascript`
```json
{
	"name": "js-next",
	"displayName": "Javascript Next",
	"description": "Javascript Next Highlighting",
	"version": "0.0.1",
	"publisher": "ricmed205",
	"engines": {
		"vscode": "^0.10.1"
	},
	"categories": [
		"Languages"
	],
	"contributes": {
		"grammars": [{
			"language": "javascript",
			"scopeName": "source.js",
			"path": "./syntaxes/js.tmLanguage"
		}]
	},
	"extensionDependencies": [
		"vscode.javascript"
	],
}
```

**Comment by rickmed** [comment]
@aeschli I got an expected value error so I removed the last comma but I don't the option in the language mode options and if I select javascript it breaks (the whole highlighting is off).

**Comment by aeschli** [comment]
Ah, of course if you want own option in the language dropdown, then having your own id is the right thing to do.
Highlighting is off: Sounds like an issue in the grammar, or a bug in our TextMate engine.
Did you check the console in the dev tools?

**Comment by rickmed** [comment]
@aeschli  Thank you for help!

So this is my package.json

```javascript
{
	"name": "js-next",
	"displayName": "js-next",
	"description": "Javascript Next Highlighting",
	"version": "0.0.1",
	"publisher": "rickmed",
	"engines": {
		"vscode": "^0.10.1"
	},
	"categories": [
		"Languages"
	],
	"contributes": {
		"languages": [{
			"id": "js-next",
			"aliases": ["JavaScript Next"],
			"extensions": [".js",".htc",".jsx"],
			"configuration": "./javascript.configuration.json"
		}],
		"grammars": [{
			"language": "javascript",
			"scopeName": "source.js",
			"path": "./syntaxes/js-next.tmLanguage"
		}]
	}
}
```

When a place my extension folder in the vscode's extension folder I get these messages (the new js language is selected by default):

![image](https://cloud.githubusercontent.com/assets/7104786/12949359/9349a0a6-cfd9-11e5-952d-ee56c8e0c95e.png)

When I select the core javascript language, I get this:

![image](https://cloud.githubusercontent.com/assets/7104786/12949446/0d67865a-cfda-11e5-9e51-b893ceb21957.png)
