### ISSUE TITLE
Css linting not showing errors/warnings

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#15548]
- VSCode Version: 1.8.0 insiders 
- OS Version: Windows and Mac OS X

Steps to Reproduce:

1. Create an empty ruleset in a css file

In VSCode 1.7.1 and earlier, you would see the below
![image](https://cloud.githubusercontent.com/assets/16890566/20332561/92b3e494-ab61-11e6-8817-737053d52d6a.png)

In the Insiders there are no squigglies and the Problems view is empty as well

**Comment by aeschli** [comment]
duplicate of #15504
