### ISSUE TITLE
Opening search result replaces tab with the same file name

### ISSUE THREAD

**Issue by EddieTheHead** [microsoft/vscode#155483]
Issue Type: <b>Bug</b>

1. Create project with two files with the same filename (Kcofig) in separete folders and main.c file.
.
├── main.c
├── module1
│   └── Kconfig
└── module2
    └── Kconfig

2. Open main.c and module1/Kconfig in separate tabs. 
3. Swich focus to main.c tab and search for content of module2/Kconfig file
4. Select search result
5. Observe how vscode closes tab with module1/Kconfig and replaces it with module2/Kconfig

Expected  behaviour:
vscode should create thrid tab with module2/Kconfig or replace main.c tab with module2/Kconfig, retaining module1/Kconfig tab.  

See attached video.

VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:28:29.328Z)
OS version: Linux x64 5.4.0-121-generic snap
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz (4 x 2947)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 1|
|Memory (System)|7.69GB (0.40GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 4896029a-445d-4244-a21e-3380369c76e1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
arm|dan|1.7.4
gtest-adapter|Dav|1.8.3
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
cortex-debug|mar|1.4.4
vscode-catch2-test-adapter|mat|4.2.2
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.10.8
cpptools-extension-pack|ms-|1.2.0
hexeditor|ms-|1.9.7
nrf-kconfig|nor|2022.7.24
open-in-new-window|ona|1.1.0
code-spell-checker|str|2.3.1
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.5
markdown-pdf|yza|1.4.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714

https://user-images.githubusercontent.com/7189283/179501968-bd3c24ed-1afc-4c17-9e11-e0aa67ee5526.mp4


vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vsclangdf:30486550

```

</details>

**Comment by EddieTheHead** [comment]
https://user-images.githubusercontent.com/7189283/179502169-7ecbef99-db14-4ed7-b73b-0b05d160a3e3.mp4

**Comment by gjsjohnmurray** [comment]
When a tab's label is displayed in italics it is operating in preview mode. This means its contents will be replaced when you open another file in preview mode.

**Comment by gjsjohnmurray** [comment]
Doubleclick the tab. Or use its context menu.
