### ISSUE TITLE
Workspace trust commands confusing

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#155510]
<img width="368" alt="CleanShot 2022-07-18 at 08 28 16@2x" src="https://user-images.githubusercontent.com/35271042/179546843-8a7eb560-7f82-464f-b39a-952127ea549d.png">

"Configure" and "Manage" are really similar to each other and I had a hard time knowing which one opened what, which caused me to open the wrong one. "Configure" opens the settings UI with a query, and "Manage" opens a custom editor. 

My proposal would be to change "Configure Workspace Trust" to "Workspace Trust Settings" to make it explicit.

**Comment by sbatten** [comment]
I'd actually like to tweak your proposal to "Manage Trusted Workspaces" and "Configure Workspace Trust Settings"
