### ISSUE TITLE
[Request] [Notebook] Allow notebook cell language picker to be removed.

### ISSUE THREAD

**Issue by brettfo** [microsoft/vscode#155548]
.NET Interactive would like the ability to have full control over a notebook cell's language picker (see #142133), but full control isn't really possible.

Example:

If the `NotebookController.supportedLanguages` property is set to a single value (e.g., `['csharp']`) then there are really 2 values shown to the user: C# and Markdown.  If that property is "falsy" (according to the documentation, either `null` or an empty array `[]`), then all languages known by VS Code will be visible, which is also not what we want.  Related to the issue linked above, custom items can't be added to the list unless they correspond to a language registered in an extension's `package.json`, which means arbitrary values can't be added at runtime.

The suggestion is that a new property be added, `NotebookController.hideLanguagePicker` which defaults to `false` (or `showLanguagePicker` which defaults to `true`) so that we can remove that picker and then manually expose our desired functionality through a notebook cell status bar item provider.

**Comment by roblourens** [comment]
Lets continue this discussion in https://github.com/microsoft/vscode/issues/142133 since that has the full context and we can use the one issue for discussing different possible solutions.
