### ISSUE TITLE
Picker title shows grey border

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155566]
![image](https://user-images.githubusercontent.com/900690/179692641-309ab92b-97e4-4d99-8dca-86a781c0c323.png)

Not sure if this is recent, but shouldn't the title background go all the way?

**Comment by TylerLeonhardt** [comment]
It should. I didn't change anything recently but I'll take a look

**Comment by TylerLeonhardt** [comment]
verification (Using tomorrow's build):

* Using GHPR extension open a PR webview
* Select the milestone
* using the default theme you should be able to not see any border on the title bar

verification that this didn't break https://github.com/microsoft/vscode/issues/107737

* Turn off settings sync if you have it on
* Turn on settings sync to see:
![image](https://user-images.githubusercontent.com/2644648/181625101-b439c90a-dbab-4278-8991-3ae43ea909fb.png)
* Tab to select a Quick pick item row
* Click with your mouse on the "Please sign in to synchronize..." text which will cause the focus to be entirely around the qp (like in the above screenshot)
* verify there is still a solid border around the entire qp.
