### ISSUE TITLE
Zoomed title needs to update traffic lights position

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155557]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/900690/179665373-d9e3dae3-5b39-4e52-9c28-47bebef791af.png">

**Comment by bpasero** [comment]
There already is this method to adjust for command center:

https://github.com/microsoft/vscode/blob/a74adedba8fb56d14f01f7950340dab33cfeae57/src/vs/platform/windows/electron-main/window.ts#L1311

**Comment by sbatten** [comment]
not having my mac with me today, will tackle this later in the week.
