### ISSUE TITLE
Starting VS Code extensions with zsh

### ISSUE THREAD

**Issue by Ninzero** [microsoft/vscode#155542]
I am using [vscode-leetcode](https://github.com/LeetCode-OpenSource/vscode-leetcode) extension. Which requires node.js. I use nvm-zsh as a plugin of oh-my-zsh. Long story short, node command is in $PATH only when you are using zsh.

Unfortunately, vscode-leetcode cannot start because it cannot find node.js. It will show:
`/bin/sh: node: command not found` which means it use `/bin/sh` to start.

However, when I start VS Code from terminal, i.e. use `code` command, this extension can start without a problem. This means now it's stating with zsh.

I wonder if it is possible to set VS Code to start extensions with zsh as default? I have tried set `"terminal.integrated.defaultProfile.osx"` to `"zsh"`, which did not help.

PS: I know there is "leetcode.nodePath" setting. But there are so many similar situations and setting path for them one by one can make my setting.json long and messy. Also, I will have to change these settings one by one whenever I decide to change my node.js version.

**Comment by Ninzero** [comment]
> Where are you seeing this?

From the output of leetcode extension, like this:
<img width="1043" alt="CleanShot 2022-07-19 at 13 44 14" src="https://user-images.githubusercontent.com/20299935/179753883-15774be5-581d-4827-bd77-c146edfdc91e.png">

**Comment by alexr00** [comment]
Thanks! Have you already set zsh as the default shell for your OS?

**Comment by Ninzero** [comment]
In terminal, ` echo $SHELL` gives `/bin/zsh`. And in system preference, the login shell has been set to `/bin/zsh`. Does that mean zsh is the default shell for macOS? Also, my macOS version is 12.4 (21F79). I think nowadays, zsh is always the default shell for macOS unless you explicitly change it?

**Comment by alexr00** [comment]
Ok, let's see if VS Code knows the location of node. What is the install location of node in a zsh terminal? If you open the developer tools in VS Code (command: Developer: Toggle Developer Tools) and enter `process.env.PATH` in the console, is the install location listed there?

**Comment by Ninzero** [comment]
The output various depend on how you open VS Code. If you start the normal way (click on the icon), the output of `process.env.PATH` is :

> '/usr/bin:/bin:/usr/sbin:/sbin'

However, if you start VS Code from terminal, the output become:

>'/Users/Ninzero/.nvm/versions/node/v16.16.0/bin:/Users/Ninzero/.cargo/bin:/Users/Ninzero/.pyenv/shims:/Users/Ninzero/.pyenv/bin:/Users/Ninzero/.local/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/Ninzero/.local/bin'

where node is intalled in the first location of PATH. I am not sure what happened here. Why start VS Code in different will result in different output?

**Comment by joaomoreno** [comment]
@Ninzero Do you get a warning on startup that your shell was unable to be resolved?

**Comment by Ninzero** [comment]
> Do you get a warning on startup that your shell was unable to be resolved?

No, that did not happen.

**Comment by joaomoreno** [comment]
Can you share your .zshrc file?

**Comment by Ninzero** [comment]
OK, I have figured out which part has caused the problem. I am using [zsh-nvm](https://github.com/lukechilds/zsh-nvm) to control node version. I also enabled lazy load feature. It seems like lazy load is what cause the problem. As long as I remove the lazy load mode, the problem is solved. Thank you for your time, I will close this issue now.
