### ISSUE TITLE
Sometimes, don't support using the TAB indent style format js code

### ISSUE THREAD

**Issue by hxfdarling** [Microsoft/vscode#15555]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-css-formatter|aeschli|0.0.2|
|vscode-caniuse|akamud|0.5.3|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-theme-onedark|akamud|0.2.13|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|vscode-color|anseki|0.2.1|
|one-monokai|azemoh|0.1.15|
|tortoise-svn-for-vscode|cdsama|0.0.2|
|path-intellisense|christian-kohler|1.1.0|
|jshint|dbaeumer|0.10.15|
|vscode-instant-markdown|dbankier|0.1.0|
|githistory|donjayamanne|0.1.0|
|theme-dracula|dracula-theme|1.2.5|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.5.40|
|vscode-npm-script|eg2|0.0.21|
|tortoise-svn|fantasytyx|0.1.1|
|vscode-npm|fknop|3.3.0|
|docthis|joelday|0.3.5|
|Angular2|johnpapa|1.0.2|
|format-indent|Kasik96|1.3.0|
|ftp-sync|lukasz-wronski|0.3.1|
|debugger-for-chrome|msjsdiag|2.2.2|
|color-highlight|naumovs|1.2.1|
|promise-snippets|progre|0.2.3|
|vscode-icons|robertohuertasm|4.0.1|
|code-settings-sync|Shan|2.3.8|
|theme-cobalt0|sharksym|0.0.5|
|addDocComments|stevencl|0.0.8|
|js-complexity-analysis|TomiTurtiainen|1.0.4|
|Angular2|UVBrain|0.3.5|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|
|local-history|xyz|1.0.2|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@hxfdarling Can you provide some information on the issue you are facing? Am not able to understand much from just the title.
Please include repro steps, screenshots and sample code

**Comment by hxfdarling** [comment]
This is my config

       "editor.mouseWheelScrollSensitivity": 1.8,
	"editor.fontSize": 22,
	"editor.renderWhitespace": "boundary",
	"editor.mouseWheelZoom": true,
	"editor.insertSpaces": false,
	"editor.renderIndentGuides": false,
	"editor.detectIndentation": false,

I have some code files can't according to the format TAB indent style,always use  space indentation
I can't reappear that when uninstall JS-CSS-HTML-formatter extensions after
Now I installed the JS-CSS-HTML-formatter extensions, solved this problem by this extensions

**Comment by ramya-rao-a** [comment]
So installing  JS-CSS-HTML-formatter extension solved the problem?

Can you see the problem with all extensions disabled?
