### ISSUE TITLE
Explorer: Expand button on multiroot workspace results in two highlighted rows

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#155574]
Type: <b>Bug</b>

1. Set up a multiroot workspace (I used fsconsumer-sample and fsprovider-sample from the vscode-extension-samples repo).
2. Expand both roots.
3. Select a folder in the first root (I used .vscode).
4. Click 'Collapse Folders in Explorer'. The folders collapse to their roots and the button changes to 'Expand Folders in Explorer'. The second root gets a highlight - why?
5. Click 'Expand Folders in Explorer'

:bug: both the originally-selected folder in the first root and the root folder of the second roots are highlighted.

![junk](https://user-images.githubusercontent.com/6726799/179706618-61b4f48c-b0cb-4fbe-ba22-7409e3696ce0.gif)

VS Code version: Code - Insiders 1.70.0-insider (a74adedba8fb56d14f01f7950340dab33cfeae57, 2022-07-19T05:16:01.922Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by lramos15** [comment]
Closing as this was reverted due to a lot of unknowns surrounding the UX.
