### ISSUE TITLE
New Remote Connect UI: Connect to XXXX server command can get lost at the bottom of the kernel picker.

### ISSUE THREAD

**Issue by greazer** [microsoft/vscode#155541]
After using new remote connection Ux, I found it to be confusing when I cannot see that I can connect back to local or another remote. The commands at the bottom should either be on the top, or at least somewhere discoverable.

<img width="621" alt="image" src="https://user-images.githubusercontent.com/11685408/179324694-c59406e8-0abe-42c0-b949-7e31091a7d85.png">

**Comment by greazer** [comment]
The Jupyter extension cannot control this placement.

**Comment by rebornix** [comment]
This is now handled by the new MRU kernel picker.
