### ISSUE TITLE
Enhance on-open workflow to run commands

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#155582]
https://github.com/microsoft/vscode/blob/a8444a04712ff1bf9b83d1670f2e78733c327f3b/.github/workflows/on-open.yml#L10-L19

In comparison, on-comment workflow acts on any /commands it finds:

https://github.com/microsoft/vscode/blob/a8444a04712ff1bf9b83d1670f2e78733c327f3b/.github/workflows/on-comment.yml#L11-L25

By changing this the following line in this new issue would get actioned:

/assign @JacksonKearl 

As things stand I will need to add it as a comment after creating the issue.

**Comment by gjsjohnmurray** [comment]
Adding the following command which didn't get detected in the original comment.

/assign @JacksonKearl

**Comment by gjsjohnmurray** [comment]
@lramos15 if I put `/assign @lramos15` or other slash-commands in the text I enter when **creating** a new issue I don't think it gets actioned by the bot. Instead I have to put them in a comment.

**Comment by lramos15** [comment]
Hmm, I guess we could add it. I think the general idea was to keep the actions as lean as possible to avoid unnecessary compute and since the only people who would ever need a command on open would be for `/assign` by our small set of triagers it never felt worthwhile

**Comment by gjsjohnmurray** [comment]
I don't feel strongly about it, so feel free to close.

**Comment by lramos15** [comment]
Closing for now, will revisit if we find this use case being attempted to be used often.
