### ISSUE TITLE
Cannot place breakpoints

### ISSUE THREAD

**Issue by stevenmwade** [Microsoft/vscode#1555]
Using 10.5 on Ubuntu 15.4 and docs say you can add a breakpoint by selecting one in the margins which it allowed me to do the first time, but haven't been able to since. It's been reinstalled a few times because it first installed without any snippets.

**Comment by bpasero** [comment]
@stevenmwade so you say you cannot click to create breakpoints, or they just dont work?

**Comment by stevenmwade** [comment]
I can't even place them anymore. Using Node v5.0.

**Comment by isidorn** [comment]
Can you please provide reproducable steps. In what file are you trying to place them?
Clicking on the margin does not show the breakpoint in the margin?
Do you try to place them during a debug session or before starting to debug.

Can you place them by clicking F9?

**Comment by stevenmwade** [comment]
I am trying to place them in a router file (which has worked).
Neither clicking or hovering in the margin shows the breakpoints.
Both.

No.

**Comment by isidorn** [comment]
What is the extension of the file? Can you attach that file so we try to reproduce the issue on our side?
What language mode do you see in the bottom right corner when you open that file?

**Comment by stevenmwade** [comment]
Aha, it was set to Javascript React, which is strange because it was set to that the first time it worked. I'll need to get rid of that extension, apparently.
