### ISSUE TITLE
Notebook API tests edit API batch edits

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155587]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178552&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=2f009c1d-81d8-5a7e-ba44-a6542d1f1704&l=652

```
1) Notebook API tests
       edit API batch edits:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:132:11)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

```

**Comment by bpasero** [comment]
Similar to https://github.com/microsoft/vscode/issues/152145

**Comment by rebornix** [comment]
From https://github.com/microsoft/vscode/issues/155808

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=178865&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=c61a688d-0a79-5b1f-223b-9376911e515d&l=641

**Comment by rebornix** [comment]
Most recent change to the test and related notebook code https://github.com/microsoft/vscode/pull/151377

**Comment by rebornix** [comment]
In https://github.com/microsoft/vscode/pull/155920, I was removing `asPromise` and started to use the new notebook workspace edit API for integration test. Not sure yet if that really fixes the problem, but it is wrong to test the effects of commands by asserting `onDidNotebookDocumentChange` events.

The PR passes but I don't have 100% confidence that it is no longer flaky. My plan is enabling it next week and keeping an eye on it, if it's flaky then have it disabled again. I'll also move the `skip`ed command tests to unit tests.

**Comment by rebornix** [comment]
We are also using commands extensively, but the notebook commands rely on `activeNotebookEditor` to be valid when there is no argument. This will be flaky as long as any component in the workbench mess up with focus (even if that component steals and restores focus in a short period).

Will move off those commands to unit tests since document changes are now all handled by workspace edits.

**Comment by rebornix** [comment]
Batch Edit api tests are now replaced by unit tests, and we moved off `executeCommand` and `asPromise` which are meant to be flaky when focus is messed up in the UI side.
