### ISSUE TITLE
Flag an install to prevent a vscode version from updating

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#155547]
In the CLI, we want to be able to manage VS Code versions. Among the options is installing a specific version of VS Code (e.g. `code version use 1.68.1`). If a mode is selected and installed in this way, we should not auto update.

There is `update.mode: none`, but this is a user setting, and we don't want to have a separate user-data-dir for each install. Is there a way the CLI could flag the VS Code install to not update itself? Perhaps by writing a file in the installed directory, for example.

**Comment by joaomoreno** [comment]
Here's the logic that sets up the update service state: https://github.com/microsoft/vscode/blob/b5a63973e920382b3c25b563933ee7443105c0c0/src/vs/platform/update/electron-main/abstractUpdateService.ts#L62-L107

We could certainly add some new property to `product.json` and detect it here.

**Comment by connor4312** [comment]
I think we don't need this, at least right now, with the direction that we're heading. May reopen it in the future.
