### ISSUE TITLE
Polish command navigation for "empty commands"

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155543]
Currently ctrl/cmd+arrows and ctrl/cmd+shift+arrows treats "empty commands" (the circle outlines) like every other command. This would feel much nicer if they were completely skipped such that ctrl+shift+up would select the output of the previous non-empty command.

Problem case:

![Recording 2022-07-18 at 13 42 56 (1)](https://user-images.githubusercontent.com/2193314/179614068-1a2fde2c-fd42-43e1-b957-7009bb72480b.gif)

**Comment by BamBamboozled** [comment]
Taking a look at this!

**Comment by Tyriar** [comment]
@BamBamboozled there's a WIP PR for this fyi https://github.com/microsoft/vscode/pull/155551

**Comment by BamBamboozled** [comment]
Jokes. Thanks for the heads up

**Comment by lramos15** [comment]
I tried to verify this, but it still appears to select empty lines. I'm not sure if I'm verifying correctly though so please provide some steps

**Comment by meganrogge** [comment]
Yeah I can reproduce the original issue

**Comment by meganrogge** [comment]
@Tyriar something you want to look at having just fixed other issues in that area?

**Comment by Tyriar** [comment]
This ended up feeling a little weird as it was just a special edge case behavior for when the most recent command was empty. Instead keeping this out and doing https://github.com/microsoft/vscode/issues/198041 instead will make things simpler.
