### ISSUE TITLE
Error on run code from source

### ISSUE THREAD

**Issue by buzzzzer** [Microsoft/vscode#15553]
- VSCode Version: master
- OS Version: Win 10, node 6.9.1
Two days ago after update from git I cant build source correctly.
compilation 0 error but after scripts\code I got Error:

`>scripts\code

[7736:1116/091234:INFO:CONSOLE(136)] "Loading "gc-signals" failed", source: file:///vscode/out/vs/loader.js (136)
[7736:1116/091234:INFO:CONSOLE(137)] "Detail: ", source: file:///vscode/out/vs/loader.js (137)
[7736:1116/091234:INFO:CONSOLE(139)] "Error: Module version mismatch. Expected 50, got 49.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (vscode\node_modules\gc-signals\src\index.js:8:18)", source: file:///vscode/out/vs/loader.js (139)
[7736:1116/091234:INFO:CONSOLE(141)] "Here are the modules that depend on it:", source: file:///vscode/out/vs/loader.js (141)
[7736:1116/091234:INFO:CONSOLE(142)] "vs/workbench/api/node/mainThreadHeapService", source: file:///vscode/out/vs/loader.js (142)
`
Steps to Reproduce:
1. clone repo
2. script\install
3. npm run watch
4. script\code

**Comment by ramya-rao-a** [comment]
On the Nov 14th, we updated to use Electron 1.4.6. You need to recompile your modules to get the native ones working.

**Comment by aozgaa** [comment]
How do you recompile the modules?

Doing this doesn't work (on Ubuntu 16.04):
```
rm -rf node_modules/
./scripts/npm.sh install --arch=x64
```

**Comment by aozgaa** [comment]
It appears running
```
npm install -g gulp
gulp clean
gulp clean-electron
```
from a shell fixes the issue.

**Comment by ramya-rao-a** [comment]
Thats interesting, clearing the node_nodules and doing a fresh npm install should have worked...

@Tyriar Any thoughts on why that wouldnt work in ubuntu?

**Comment by Tyriar** [comment]
This happens when you run `npm install` instead of `./scripts/npm.sh install --arch=x64` because Electron uses a newer version of V8 (v50) than the latest node (v49). Let us know if this doesn't solve your issue.

**Comment by buzzzzer** [comment]
@ramya-rao-a 
> Thats interesting, clearing the node_nodules and doing a fresh npm install should have worked...

dont work for me

@Tyriar 
> This happens when you run npm install instead of ./scripts/npm.sh install --arch=x64 because Electron uses a newer version of V8 (v50) than the latest node (v49). Let us know if this doesn't solve your issue.

No. I use ./scripts/npm install instead ./npm install

1. I deleted node_modules, 
2. npm install -g gulp
3. gulp clean
4. gulp clean-electron
5. scripts\npm install
6. npm run watch
Аll steps are no errors

7. scripts\code gives an error and open two windows vscoder

@ramya-rao-a 
> Thats interesting, clearing the node_nodules and doing a fresh npm install should have worked...

dont work for me

@Tyriar 
> This happens when you run npm install instead of ./scripts/npm.sh install --arch=x64 because Electron uses a newer version of V8 (v50) than the latest node (v49). Let us know if this doesn't solve your issue.

No. I use ./scripts/npm install instead ./npm install

```
1. I deleted node_modules, 
2. npm install -g gulp
3. gulp clean
4. gulp clean-electron
5. scripts\npm install
6. npm run watch
```
Аll steps are no errors

7. scripts\code gives an error and open two windows vscode

![image](https://cloud.githubusercontent.com/assets/1981785/20377452/a7c69d6e-aca0-11e6-8fef-a319d24adc27.png)
![image](https://cloud.githubusercontent.com/assets/1981785/20377466/c9ce0b68-aca0-11e6-8539-5f1f82647f2f.png)

**Comment by ramya-rao-a** [comment]
@bpasero Would the recent change to use the newer electron version cause this?

**Comment by bpasero** [comment]
@buzzzzer can you try this:
* `git clean -xfd`
* `scripts\npm.bat install`
* `gulp watch`
* new terminal: `scripts\code.bat`

**Comment by buzzzzer** [comment]
@bpasero 
Done. It seems to work. 
first run scripts\code.bat open 2 instances with 2 different workspace. (Earlier explorer tree was not visible)
second and next runs opened one instance. Look ok. Thanks !

p.s. Possible #15571  ?

**Comment by bpasero** [comment]
@joaomoreno I speculate that @buzzzzer was doing the npm install correctly, but in the `.build` folder there was still the old electron version laying around. I also sometimes hit this. Maybe the npm.bat script should delete the .build folder so that we do not run into this issue everytime?

**Comment by joaomoreno** [comment]
This is strange. `gulp electron` used to compare the version inside `.build` with the intended one... and only download them if they mismatched. I don't find this code anymore... not sure why and how it's gone.
