### ISSUE TITLE
Layer breakers in our code

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15558]
There is `https://github.com/Microsoft/vscode/blob/master/src/vs/platform/textmodelResolver/common/resolver.ts` with a dependency onto `import { IModel } from 'vs/editor/common/editorCommon';` which isn't legal. It should live in `editor/common/services`

**Comment by bpasero** [comment]
@jrieken good catch. I found more though:
* `vs/platform/actions/common/resourceContextKey` => `vs/editor/common/services/modeService`
* `vs/platform/extensionManagement/test/common/extensionEnablementService.test` => `vs/workbench/services/storage/common/storageService`
* `vs/editor/contrib/indentation/common/indentation.ts` => `vs/workbench/services/quickopen/common/quickOpenService`
* `vs/editor/contrib/suggest/electron-browser/snippetCompletion.ts` => `vs/workbench/services/quickopen/common/quickOpenService`

Maybe we could enrich the layeringRule to more rules:
* base: []
* platform: [base]
* editor: [platform, base]
* workbench: [platform, base, editor]

**Comment by jrieken** [comment]
> * vs/editor/contrib/suggest/electron-browser/snippetCompletion.ts => vs/workbench/services/quickopen/common/quickOpenService

I think that shows a nice problem with our layering. We somehow don't only separate between target runtimes (JS, browser, electron-main,browser) but also between platform, editor, workbench, base. This is like a 2-dimensional layering and I wonder if that makes things artificially complicated. 

In the sample above I wanna contain all *suggest*-related features in one folder. That makes it easy to find/navigate/understand. Also I have structured it along the runtimes (common/browser/electron) but it conflicts with the goal of also structuring along workbench-editor et al. Somehow conflicting goals and abstraction for little gain. I wonder if we can give/reduce the 2 layer in some way

**Comment by bpasero** [comment]
I think what we used to do in that case is to put the editor contribution into the vs/workbench/parts folder because it can only work if the workbench is there. But yeah, that moves it away from snippets in general.

**Comment by jrieken** [comment]
To express the same intent I have put into the `electron-browser` folder. The workbench in the only thing that runs from there.

**Comment by sandy081** [comment]
I am not sure what is the good solution for tests here. For eg `extensionEnablementService` has a dependency on `storageService` where both interfaces are in platform. But implementation of `storageService` lies in workbench. 

Either,
- Exclude this for tests because they need to instantiate the implementations themselves.
- Create a mock of such services in tests. This would be tedious. Tests will be more reliable if using real implementations
- Make sure definitions and implementations remain in the same layer. I think `StorageService` implementation can be moved as all its dependencies are in platform.

In this case, I would go for last option. But in general I would allow tests to instantiate the implementations.

**Comment by alexandrudima** [comment]
`src/vs/editor/contrib/indentation/common/indentation.ts` layer break introduced by @isidorn in f01ee9854050254fa55865c6380a50f56171700b

**Comment by jrieken** [comment]
@joaomoreno and @bpasero: [`product.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/product.ts#L59) and [`package.ts`](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/package.ts#L16) layering issues. Requires nodejs and respective json files.

**Comment by joaomoreno** [comment]
@jrieken Fixed those.

**Comment by sandy081** [comment]
Moved storage service to package layer.

@jrieken All issues reported here are fixed. You can close this.
