### ISSUE TITLE
Multiple cursor shortcuts don't work in 1.8.0

### ISSUE THREAD

**Issue by HookyQR** [Microsoft/vscode#15560]
- VSCode Version: 1.8.0
- OS Version: MacOS

Steps to Reproduce:

1. Open any file with multiple lines.
2. Press `Alt+Cmd+up` or `Alt+Cmd+down`

Additional cursors are not added.

**Comment by ramya-rao-a** [comment]
@HookyQR I do see the multiple cursors on  `Alt+Cmd+up` or `Alt+Cmd+down` in the latest insiders 1.8.0

Can you try disabling extensions?

**Comment by HookyQR** [comment]
Not an VS Code extension issue. It was caused by [Spectacle](https://github.com/eczarny/spectacle). I have it disabled for Code, but it that obviously didn't migrate to Insiders. Sorry.
