### ISSUE TITLE
Explorer shows expand icon after reload in multi root

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155636]
![image](https://user-images.githubusercontent.com/900690/179798909-2b9c3865-1a4b-41ba-85f2-1a3e08373b38.png)

**Comment by bpasero** [comment]
Here I would not expect it because 1 node is expanded (the first folder).

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/155570
