### ISSUE TITLE
run in terminal

### ISSUE THREAD

**Issue by NEERAJ-003** [microsoft/vscode#155619]
Issue Type: <b>Feature Request</b>

Run in terminal is missing so i am not able to run the code please fix this problem for smooth experience , so please help me as soon as possible for smooth work

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by meganrogge** [comment]
We have run  selected text and selected file in active terminal as commands you can use
