### ISSUE TITLE
Watermark using wrong asset on stable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#155654]
It seems that this has been broken for a few versions so far, on Stable we see the Insiders version of the watermark

<img width="806" alt="CleanShot 2022-07-19 at 13 20 13@2x" src="https://user-images.githubusercontent.com/35271042/179841423-47136ef5-1f91-403a-b40b-2a44640eec7c.png">

<img width="806" alt="CleanShot 2022-07-19 at 13 23 24@2x" src="https://user-images.githubusercontent.com/35271042/179841467-71d1b529-8890-4312-919c-3a75811a1ecf.png">

cc @bpasero @daviddossett

**Comment by bpasero** [comment]
A regression from @daviddossett https://github.com/microsoft/vscode-distro/commit/769675d504bb2d1db718bd742e3e3f934d69b64b it seems.

**Comment by misolori** [comment]
For verification: download a stable version of 1.70 (I have a build ready via `361215a16876075d6fce78f98ba39c903df68b83`) and verify that the empty editor shows the non-insiders logo on all dark/light/hc themes
