### ISSUE TITLE
VSCode crashes when using custom CTRL+O keybindings

### ISSUE THREAD

**Issue by ekehoe32** [microsoft/vscode#155677]
Issue Type: <b>Bug</b>

I have transfered my keybindings to my home PC, have installed all the same extensions with a fresh .vscode and settings.json, and vscode will randomly crash when using CTRL+O keybindings.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3593)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.58GB free)|
|Process Argv|--crash-reporter-id 5f9e2500-7b4c-4ba2-96bd-4fdfa947f110|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
project-manager|ale|12.6.1
docs-view|bie|0.0.11
path-intellisense|chr|2.8.1
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
gc-excelviewer|Gra|4.2.55
copy-filename|jac|2.3.2
language-julia|jul|1.6.24
magit|kah|0.6.29
vscode-docker|ms-|1.22.1
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
resourcemonitor|mut|1.0.7
vscode-css-peek|pra|4.2.0
vscode-yaml|red|1.9.1
rust-analyzer|rus|0.3.1131
glassit|s-n|0.2.4
copy-path-linux|sai|1.1.2
preview-vscode|sea|2.2.5
vscode-fileutils|sle|3.5.0
snakemake-lang|sna|0.1.8
remote-x11|spa|1.5.0
remote-x11-ssh|spa|1.5.0
vscode-icons|vsc|11.13.0
org-mode|vsc|1.0.0
vim|vsc|1.23.1
vscode-todo-highlight|way|1.0.5
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550

```

</details>

**Comment by bpasero** [comment]
Can you please follow the steps in https://github.com/Microsoft/vscode/wiki/Native-Crash-Issues to get at more details around the crash and attach the result here? Thanks!

**Comment by bpasero** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
