### ISSUE TITLE
Disabled commit button still clickable

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#155644]
https://user-images.githubusercontent.com/35271042/179813745-c8edf122-6592-4a57-9c40-c61d04bf0729.mp4

I wonder if we just need to add `pointer-events: none` on the disabled class?

**Comment by lszomoru** [comment]
Can you try the latest Insiders release as today I have checked in a fix related to the button background when the button is disabled by focused. I am happy to add additional things if you think that we should do it.

**Comment by misolori** [comment]
Ah you are right, I must've captured this before I had updated it as it's now fixed. Thanks for double-checking!

**Comment by rzhao271** [comment]
The border still changes colours

![Screenshot showing the border having a different colour after it was clicked](https://user-images.githubusercontent.com/7199958/181389519-b18435b0-8fad-4f93-a4f7-9d3fe5233496.PNG)

**Comment by lszomoru** [comment]
As of right now it is expected to see the outline when the button gets focused. 
I will reopen this issue as we are currently discussing in https://github.com/microsoft/vscode/issues/156443 how a disabled button should behave.

**Comment by lszomoru** [comment]
Closing this issue as we agreed that disabled buttons still need to have the focus outline.
