### ISSUE TITLE
source control view closes

### ISSUE THREAD

**Issue by jessewriter** [microsoft/vscode#155659]
Issue Type: <b>Bug</b>

click on another view and source control view closes.  i keep having to re-open this view.  it is the only view currently doing this behvaior.

system win 10

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
path-intellisense|chr|2.8.1
gitlens|eam|12.1.2
svn-scm|joh|2.15.5
vscode-spring-boot|Piv|1.36.0
material-icon-theme|PKi|4.19.0
vscode-jsp|pth|0.0.3
fabric8-analytics|red|0.3.6
java|red|1.8.0
vscode-xml|red|0.21.2022062916
vscode-yaml|red|1.9.1
vscode-checkstyle|she|1.4.1
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.42.0
vscode-java-dependency|vsc|0.20.0
vscode-java-pack|vsc|0.24.0
vscode-java-test|vsc|0.35.2
vscode-maven|vsc|0.36.0
easypathconverter|Yuk|1.2.1

(2 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
@jessewriter, could you please share a recording (https://gifcap.dev) so that I better understand the behaviour that you are describing.

**Comment by jessewriter** [comment]
![Recording 2022-07-21 at 09 36 50](https://user-images.githubusercontent.com/16365134/180267574-e8b191f1-3467-45fa-be5f-05adb259b4b7.gif)

see how source view keeps disappearing for no reason.

**Comment by jessewriter** [comment]
![Recording 2022-07-21 at 09 40 24](https://user-images.githubusercontent.com/16365134/180268210-5ffea00f-75a5-45f0-9ae8-ebd6121cf119.gif)

**Comment by jessewriter** [comment]
solved.  i must have right clicked in the left hand gutter and unchecked 'source control' 
![image](https://user-images.githubusercontent.com/16365134/180513941-418f29ee-4700-40e8-b2f6-eec62d3e4299.png)

user error :/
