### ISSUE TITLE
Can not use "Accounts-Sign in to Sync Setting"

### ISSUE THREAD

**Issue by weijuer** [microsoft/vscode#155681]
Issue Type: <b>Bug</b>

1.Click the "Accounts-Sign in to Sync Setting" button;
![image](https://user-images.githubusercontent.com/12313268/179891512-4c88b5ba-343e-401f-86cc-5a9f2b063514.png)

2.Choose "Sign in to Sync Setting";
![image](https://user-images.githubusercontent.com/12313268/179891556-d5e19cf7-0913-4d4e-8435-7e5c29c4c1c6.png)

3.Choose "Sign in with Github", go to brower to oauth;

4.Turn to vscode, click the "open" button with THE "Allow an extension to open this URI?" dialog, and then I got 2 errors as follow:
![image](https://user-images.githubusercontent.com/12313268/179891638-d541a88c-98a9-4595-8094-e1cf22a6315f.png)

1) invalid json response body at https://github.com/user reason: Unexpected token < in JSON at position 2

2) Sign in failed: FetchError: invalid json response body at https://github.com/user reason: Unexpected token < in JSON at position 2
Source: GitHub Authentication (Extension)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (8.60GB free)|
|Process Argv|--open-url --crash-reporter-id 427fd4e9-daf9-45b0-ba2d-726b48f78fd4 -- vscode://vscode.github-authentication/did-authenticate?nonce=1131707b-9d00-4140-8aea-a584aaaeac2b&windowId=3&code=c03ab8c05a7d5a56c357&state=vscode%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253D1131707b-9d00-4140-8aea-a584aaaeac2b%2526windowId%253D3|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
Bookmarks|ale|13.3.1
vscode-sqlite|ale|0.14.1
ascii-tree-generator|apr|1.2.4
emojisense|bie|0.9.1
converttoasciiart|Bit|1.0.3
wechat-snippet|Cha|0.4.11
wxml-vscode|cny|0.1.2
coderoad|Cod|0.17.2
miniprogram-vscode-extension|cra|1.4.11
native-ascii-converter|cwa|1.0.9
vscode-typora|cwe|2.6.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.1.2
remotehub|eam|0.5.0
easymock|Eas|1.0.14
prettier-vscode|esb|9.5.0
front-end-daily-question|eve|1.1.7
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
codespaces|Git|1.9.3
remotehub|Git|0.38.0
live-sass|gle|5.5.1
vscode-drawio|hed|1.6.4
vue-snippets|hol|1.0.4
rest-client|hum|0.25.0
comment-translate|int|2.2.4
vscode-gutter-preview|kis|0.30.0
vscode-leetcode|Lee|0.18.1
sftp|lix|1.12.10
i18n-ally|lok|2.8.1
git-emoji-zh|mai|1.1.9
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
easy-less|mrc|1.7.4
vscode-goto-node-modules|mrl|1.2.1
vscode-docker|ms-|1.22.1
remote-repositories|ms-|0.16.0
vsliveshare|ms-|1.0.5641
vscode-versionlens|pfl|1.0.10
minapp-vscode|qiu|2.4.8
LiveServer|rit|5.7.5
partial-diff|ryu|1.4.3
esdoc-mdn|sam|0.11.0
vscode-javascript-booster|sbu|14.0.1
language-stylus|sys|1.16.0
stylus-supremacy|thi|2.16.0
codelf|unb|11.7.0
vscode-icons|vsc|11.13.0
volar|Vue|0.38.9
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
swig-tpl|zha|0.0.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550

```

</details>

**Comment by TylerLeonhardt** [comment]
@weijuer can you provide the contents of the _GitHub_ Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by weijuer** [comment]
> @weijuer can you provide the contents of the _GitHub_ Authentication output pane: ![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)
> 
> And also anything that shows up in Dev Tools:
> 
> * ctrl + shift + P
> * "Dev Tools"

![image](https://user-images.githubusercontent.com/12313268/180115585-30c80d76-bedd-4f1d-837f-a589f81527f8.png)

[vscode-app-1658369821067.log](https://github.com/microsoft/vscode/files/9155655/vscode-app-1658369821067.log)
[vscode-app-1658369837686.log](https://github.com/microsoft/vscode/files/9155656/vscode-app-1658369837686.log)

**Comment by weijuer** [comment]
I reinstall the app right now, and it works.
