### ISSUE TITLE
[Feature-request] File Explorer extensions API

### ISSUE THREAD

**Issue by Igmat** [Microsoft/vscode#15565]
## Motivation
I was looking for extension that enables working with `node_modules` in way that looks like it done in Visual Studio:
![solution explorer](https://cloud.githubusercontent.com/assets/15427508/20345514/c3ba8c8c-abf7-11e6-87d8-fc679412749b.png)
And I haven't found any. Then I investigated `vscode API` and realized that there is no way provided for extending File Explorer, so I can't create such extension also.
## What this feature offers?
This API could be useful for providing a way to restructure appearance of files and folders in File Explorer in order to organize it in more useful way depending on platform. It also could be used for extensions that change file appearance e.g. makes one folder-like group from `file.ts`, `file.js`, `file.d.ts`, `file.js.map`.
## Implementation ideas
I'm not very familiar with `vscode API` for now, but it seems that it could be reached by adding API for registering function that looks like this:
```TypeScript
TransformFolderStructure(structure: IFolderStructure): IFolderStructure
```
which would be called by vscode, when folder structure changed. And because of that this function has same return type as argument type, we are able to apply several transform functions, where each one uses result of previous. So in most cases different extensions that uses this API wouldn't conflict.
## P.S.
If this idea doesn't conflict with plans of vscode team, I would love to participate in its implementation.

**Comment by ramya-rao-a** [comment]
@Igmat What nice timing! You should read the work done by @octref recently at #15485 and the issues linked there.

**Comment by octref** [comment]
@Igmat Take a look at: https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample

Also here are some doc, although we haven't decided where to put it: https://github.com/Microsoft/vscode-docs/blob/0d5e75bf7fdea241e8b86da734bfda03d9d4c1de/docs/extensions/example-tree-explorer.md
