### ISSUE TITLE
Can extensions use async/await

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1556]
Using async/await works fine in a simple samples: https://github.com/egamma/vscode-extension-async  (target set to `ES6`).

This extension  https://github.com/aaronpowell/vscode-espruino (branch async-await) compiles without errors but failes to load with:
```
Loading development extension at c:/Users/egamma/Projects/vscode-espruino
Activating extension `aaronpowell.vscode-espruino` failed: Unexpected token {.
[Plugin Host] Activating extension `aaronpowell.vscode-espruino` failed: Unexpected token {.
[Plugin Host] Activating extension `aaronpowell.vscode-espruino` failed:  Unexpected token {
[Plugin Host] Here is the error stack:  SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.n._load (c:\Program Files (x86)\Microsoft VS Code\resources\app\out\vs\workbench\node\pluginHostProcess.js:19:14947)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\Users\egamma\Projects\vscode-espruino\out\src\extension.js:15:28)
    at Module._compile (module.js:434:26)
```

**Comment by egamma** [comment]
Since the target is set to ES6, the typescript compiler doesn't down level compile to ES5 and emits ES6 code. 

While Node 4.1.1 supports generators required for async/await it doesn't support the full ES6 yet https://kangax.github.io/compat-table/es6/#node4. 

So I suspect the code is using other ES6 features that are not supported by node 4.1.1.

**Comment by aaronpowell** [comment]
just had a quick scan through the code, I can't see any ES6 features that I'm using that aren't supported, what I'm using is:

* Promises
* Arrow functions
* Object literals
* String interpolation
* `let`

**Comment by bpasero** [comment]
My first suspect would be: `export default {` in connection-manager.ts.

**Comment by aaronpowell** [comment]
Ah, found it:

```js
let { Serial } = Espruino.Core;
```

Node.js doesn't support destructuring assignment yet. That's annoying, I wish there was a way in TS to select how low to compile things. Maybe running babel after the fact and use its plugin approach to not transform anything but that could work.

Or I could not use that feature...

**Comment by egamma** [comment]
CC @jrieken 

Glad we found the limitation, I was about to update the docs and describe that extensions can use async/await... 

This doesn't help immediately, but TS 2.0 will support `async/await support for ES5/ES3` see the [roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

**Comment by aaronpowell** [comment]
Wonder if it's worth mentioning that you _can_ use it, but you need to compile to ES6 so check what ES6 features are used and their Node.js support.

**Comment by egamma** [comment]
Yes, we should mention that you can use async/await, but with constraints.

**Comment by jrieken** [comment]
This is a good reference: https://nodejs.org/en/docs/es6/. Someone should implement a tslint/eslint rule that checks with that list
