### ISSUE TITLE
Highlighting bug?

### ISSUE THREAD

**Issue by zachbpd** [Microsoft/vscode#15562]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
---

Any idea why there seems to be a strange block highlight in the editor? I've tried reinstalling it, changing the theme and I've removed all the extensions, but I'm still experiencing this issue.

![screen shot 2016-11-16 at 10 04 36](https://cloud.githubusercontent.com/assets/12386518/20343062/e0d3b98c-abe4-11e6-928b-f6fad0a10f5a.png)

**Comment by ramya-rao-a** [comment]
@zachbpd Do you see this non empty files as well?

**Comment by zachbpd** [comment]
Yes and even if there's this one point in the code where it's not obvious the left margin (where the search and extension library icons are) still contains on extra shade of grey.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
