### ISSUE TITLE
React Js, js/jsx Classname intellisense support not available

### ISSUE THREAD

**Issue by MVSTEJA** [Microsoft/vscode#15568]
- VSCode Version: 1.7.1
- OS Version: Windows 7 PC.

I have installed react, bootstrap typings but still nothing. Even added few html css completions extensions, but i believe they work only on html files.

Steps to Reproduce:

1. No extension or typings support exist to offer code completions for css inside of js/jsx

![image](https://cloud.githubusercontent.com/assets/15942077/20349938/a2e6159a-ac32-11e6-89c6-fa642e2567a3.png)

**Comment by aeschli** [comment]
It's also something we don't have in HTML.

**Comment by waderyan** [comment]
FWIW This feature is in WebStorm.

**Comment by MVSTEJA** [comment]
@waderyan , oh that' cool, But since i am a big fan of vs-code , was hoping to get the feature in code editor. Atom does has this feature. But both Atom and Webstorm lag behind in speed and features , that i found in vscode. IMHO for react development, this is the only hurdle that i face. But bar this one feature, i love vscode :), super awesome editor.

@aeschli , Yes , i agree, But like my comment above, I love vs-code bar for this one feature, Please try to create a plugin , by using sourcemaps, or whichever , but you guys are great. Awesome editor! , hope to see this one feature , soon in the editor .

**Comment by waderyan** [comment]
@MVSTEJA thanks for your comment and your support of our editor! My comment was to make a stronger case for having this feature in VS Code :)

**Comment by mjbvz** [comment]
Closing as extension candidate. Please try this extension: https://marketplace.visualstudio.com/items?itemName=Zignd.html-css-class-completion
