### ISSUE TITLE
change properties for `runTask` to match `ITaskIdentifier`

### ISSUE THREAD

**Issue by ivankravets** [microsoft/vscode#155635]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

```
Version: 1.70.0-insider (Universal)
Commit: 92fd228156aafeb326b23f6604028d342152313b
Date: 2022-07-19T13:01:49.834Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

- OS Version: macOS

Steps to Reproduce:

1. Register tasks
2. Call with 

```
    vscode.commands.executeCommand('workbench.action.tasks.runTask', {
      type: "PlatformIO",
      task: task.id,
    });
```

---

- Related discussion https://community.platformio.org/t/shortcut-at-bottom-of-ide-not-working/28773
- Source code https://github.com/platformio/platformio-vscode-ide/blob/develop/src/project/tasks.js#L159

**Comment by yume-chan** [comment]
refs #154854

**Comment by ArturoDent** [comment]
> The format is args: { taskName?: string, type?: string}

from https://github.com/microsoft/vscode/issues/155350

Are you asking to change the arg to `task` instead of `taskName`?

**Comment by igorskyflyer** [comment]
Please don't spread panic and use bold and capitalized words. Also, don't use hypothetical statistics. Regarding your issue, the properties of your arguments you passed to the function are wrong. The property is `taskName`, not `task`.

**Comment by ivankravets** [comment]
@igorskyflyer, are you the VSCode dev? What was the goal of this issue?

**Comment by yume-chan** [comment]
Your code depends on an undocumented implementation detail of this command. Now it standards and properly exposes its argument, which is different from the old format.

**Comment by ivankravets** [comment]
Yes, this code has been working since 2017. Do you know in which version of VSCode API it was standardized?

**Comment by meganrogge** [comment]
Supported args are `string` (the old way) | `{taskName?: string, type?:string}`

both of those work for me

**Comment by ivankravets** [comment]
```
Version: 1.70.0-insider (Universal)
Commit: 3cbf3063281410d21951877eb628551809d70c6b
Date: 2022-07-25T05:27:27.755Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
```

Didn't work for me. Works well with any VSCode version from 2016 to 1.69.2 (including). When did you rename `task` to the `taskName`? Does it mean that VSCode v1.70 will break PlatformIO?

**Comment by ivankravets** [comment]
@meganrogge, where did you find that API? I've just checked the [TaskDefinition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aa746eb8ba6eb078b5ed186e1049fc85329f62f6/types/vscode/index.d.ts#L7206):

```js
    /**
     * A structure that defines a task kind in the system.
     * The value must be JSON-stringifyable.
     */
    export interface TaskDefinition {
        /**
         * The task definition describing the task provided by an extension.
         * Usually a task provider defines more properties to identify
         * a task. They need to be defined in the package.json of the
         * extension under the 'taskDefinitions' extension point. The npm
         * task definition for example looks like this
         * ```typescript
         * interface NpmTaskDefinition extends TaskDefinition {
         *     script: string;
         * }
         * ```
         *
         * Note that type identifier starting with a '$' are reserved for internal
         * usages and shouldn't be used by extensions.
         */
        readonly type: string;

        /**
         * Additional attributes of a concrete task definition.
         */
        [name: string]: any;
    }
```

The API has not been changed since the @dbaeumer defined it. See https://github.com/microsoft/vscode/issues/29855

**Comment by meganrogge** [comment]
This is not an API change. It's just arguments that can be provided to the command `runTask`

**Comment by meganrogge** [comment]
Described here
https://github.com/microsoft/vscode/blob/1a73ce68ae43d25491724ebef591dcb488bb746e/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L374-L418

**Comment by ivankravets** [comment]
@dbaeumer, what are your thoughts here? Now we have 2 interfaces for “task” entity/definition. What is the benefit to maintain 2 of them and make things complex? I even don’t say that existing extensions are broken with v1.70.

**Comment by ivankravets** [comment]
> Supported args are string (the old way) | {taskName?: string, type?:string}

No, see the scheme for the latest stable 1.69 and "the old way":

https://github.com/microsoft/vscode/blob/1.69.0/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L348:L365

@meganrogge, @Tyriar, could you reopen this issue and implement:

```js
schema: {
  anyOf: [
    {
      type: 'string',
      description: nls.localize('runTask.label', "The task's label or a term to filter by")
    },
    {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          description: nls.localize('runTask.type', "The contributed task type")
        },
        task: {
          type: 'string',
          description: nls.localize('runTask.taskName', "The task's label or a term to filter by")
        }
      }
    },
    {
      type: 'object',
      properties: {
        type: {
          type: 'string',
          description: nls.localize('runTask.type', "The contributed task type")
        },
        taskName: {
          type: 'string',
          description: nls.localize('runTask.taskName', "The task's label or a term to filter by")
        }
      }
    }
  ]
}
```

**Comment by meganrogge** [comment]
are you requesting that `taskName` be changed to `task`? @ivankravets 

the old schema did not have a `task` property either.

**Comment by ivankravets** [comment]
Sorry, I don't want to disturb people anymore in this thread. We will refactor our codebase to the legacy form `PlatformIO: ${task.name}` and make the PlatformIO extension compatible with any VSCode versions. We don't know how it will affect the performance while searching for the matching tasks. We typically contribute 20-30 tasks depending on the user's project complexity.

----

But! Being on the API side, I don't like introducing a new task definition. If you want to rename "undocumented" `task` property, maybe, the better candidate is `name`? In this case, `export interface TaskDefinition` will be unified across VSCode's codebase.

> the old schema did not have a task property either.

Yes, it was my typo, sorry. We got `task`-based definition many years ago from @dbaeumer. Maybe, that was the workaround to something else. I don't remember all details. It was 201 or 2018.

**Comment by alexr00** [comment]
It looks like the run task command used to support taking an `ITaskIdentifier`. The `task` argument mentioned in this issue doesn't need to be explicitly supported because it was implicitly supported through the `ITaskIdentifier` interface, which only requires a `type` property:

https://github.com/microsoft/vscode/blob/e4ed3e085524e3947308126fab86cb6ebee85675/src/vs/workbench/contrib/tasks/common/tasks.ts#L472-L475

Now, the run task command doesn't support taking an `ITaskIdentifier`. While this wasn't defined as API, it was used as such. Given that this has been stable for years, my opinion is that we should continue to support taking an `ITaskIdentifier`.

Details about how `ITaskIdentifier` used to be supported:

`any` arg here gets passed to `this._getTaskIdentifier()`:

https://github.com/microsoft/vscode/blob/2f5b5626e7d55a9972ad881aae48dc229083900c/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2657-L2661

`_getTaskIdentifier` checks if the `any` looks like an `ITaskIdentifier` then creates an identifier from it. This is where the `task` from the original issue comes from. It is a property of the `ITaskIdentifier`:

https://github.com/microsoft/vscode/blob/2f5b5626e7d55a9972ad881aae48dc229083900c/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3058-L3066

**Comment by ivankravets** [comment]
Thanks, @meganrogge, and @alexr00, for keeping compatibility with existing extensions 🙏
