### ISSUE TITLE
QuickInput pick - basecase

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155611]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178575&view=logs&j=b599f925-57da-5b26-3abb-63aa7efd9fc6&t=911d52ed-2b87-5c35-1118-7c19c9674aae&l=9761

```
1) QuickInput
       pick - basecase:

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```

**Comment by TylerLeonhardt** [comment]
all out of ideas on this one. I'm not relying on setTimeouts or anything. It's a totally responsive test:
```ts
// Sets up an `onShow` listener to allow us to wait until the quick pick is shown (useful when triggering an `accept()` right after launching a quick pick)
// kick this off before you launch the picker and then await the promise returned after you launch the picker.
async function setupWaitTilShownListener(controller: QuickInputController): Promise<void> {
	const result = await raceTimeout(new Promise<boolean>(resolve => {
		const event = controller.onShow(_ => {
			event.dispose();
			resolve(true);
		});
	}), 2000);

	if (!result) {
		throw new Error('Cancelled');
	}
}
```

```ts
	test('pick - basecase', async () => {
		const item = { label: 'foo' };

		const wait = setupWaitTilShownListener(controller);
		const pickPromise = controller.pick([item, { label: 'bar' }]);
		await wait;

		controller.accept();
		const pick = await pickPromise;

		assert.strictEqual(pick, item);
	});
```

**Comment by bpasero** [comment]
Maybe add some logging that only prints if the event does not fire in 4 seconds.

**Comment by TylerLeonhardt** [comment]
Ok I've added better logging in the form of... if `await pickPromise` takes too long, the test failure will be different.

Additionally, just in case this is a weird focus artifact, I have set ignoreFocusOut

**Comment by TylerLeonhardt** [comment]
I've not heard any reports of this failing recently... once it fails again, I'll revisit now that I have extra logging. With that said, it's possible that because of `ignoreFocusOut` I have fixed the test failure.
