### ISSUE TITLE
Task reloading seems to duplicate the task on window reload

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#155683]
Refs #155349

It seems to happen most of the time, but when I have my GitLens watch task running and I reload the window, I end up with 2 watch tasks running.

I've also seen some strange behavior (not very reproducible) where I had GitLens running a watch task in one window, and vscode repo open in another window, and when I reloaded the vscode repo window, I ended up with a GitLens watch task running in that vscode window.

/cc @meganrogge

**Comment by bpasero** [comment]
I think I am hitting this as well with the build task.

**Comment by meganrogge** [comment]
yes I've seen this too in insider's. Can't repro in oss w the above changes
