### ISSUE TITLE
Linux/Mac: Navigate on text and files by mouse "prev/next" button

### ISSUE THREAD

**Issue by FateNiki** [microsoft/vscode#15561]
This feature already exists in the JetBrains products.

**Comment by bpasero** [comment]
@FateNiki what OS are you on? we do have some support for mouse buttons 4 and 5 to navigate back and forth. But it might not work across all OS yet.

**Comment by FateNiki** [comment]
Hi, i use Arch Linux (Linux version 4.8.2-1-ARCH) with Gnome 3.22.1

ср, 16 нояб. 2016 г. в 17:11, Benjamin Pasero <notifications@github.com>:

**Comment by bpasero** [comment]
Right, looks like we only support it on Windows via https://github.com/electron/electron/blob/master/docs/api/browser-window.md#event-app-command-windows

**Comment by luckydonald** [comment]
Just checked JetBrains PyCharm 2016.3.1 on Mac OS 10.9.5, it works there.

**Comment by Naereen** [comment]
This feature would be really useful!

**Comment by verner-lall** [comment]
Can we get this working please!

Someone made this a while ago:
https://github.com/jostrander/mouse-forward-back

**Comment by CNaiko** [comment]
Sny progress? This feature would be really useful

**Comment by sharifza** [comment]
This is a no-go for many users, I was considering switching from PyCharm but lacking this feature highly reduces the efficiency in navigating through the code if you are used to it. The issue has been open since 2016s and I haven't even found a well documented workout for it yet.

**Comment by luckydonald** [comment]
On Mac you can bind those mouse buttons to execute some prev/next keyboard commands with BetterTouchTool.

**Comment by sabrehagen** [comment]
For reference: Solution using `xbindkeys` and `xdotool`.

Place in `~/.xbindkeysrc`:
```sh
# Mouse Button 8: Code Back
"xdotool key ctrl+alt+minus"
b:8

# Mouse Button 9: Code Forward
"xdotool key ctrl+shift+minus"
b:9
```
Install dependencies and load `~/.xbindkeysrc` config.
```
sudo apt install xdotool xbindkeys -y && \
  xbindkeys -p
```

**Comment by JoseFMP** [comment]
This was already filed in few months before this issue: https://github.com/Microsoft/vscode/issues/8641

Still few years elapsed. No work or intention to fix this apparently.

**Comment by britalmeida** [comment]
(re-posting from #8641 since there has been no reply there for a while)
The electron version of this bug has been closed as there already being a way to achieve mouse navigation functionality with electron. electron/electron#6996 (comment)
Could this be implemented in VSCode as well?

This is a severely annoying issue, given that it's a standard and habituated functionality in desktop applications. There should be no need for user configuration or shady workarounds, it should work by default.

**Comment by Yanpas** [comment]
I have a feeling that these buttons used to work before on linux https://github.com/Microsoft/vscode/issues/71318

Am I wrong?

**Comment by richardchien** [comment]
On Windows 10, it works on Visual Studio Code 1.35.1, but not on 1.36.0-insider. Did this feature have been removed or there is some bug?
