### ISSUE TITLE
Code Navigation by ctrl+click on the result of "grep" command in the terminal view failed

### ISSUE THREAD

**Issue by hsinyinfu** [microsoft/vscode#155694]
Does this issue occur when all extensions are disabled?: Yes (I only used `Remote-SSH` extension to connect to the remote Linux server, and there is no other extension running)

- VS Code Version: 1.69.2
- Local OS Version: Windows 10 Enterprise 20H2 19042.1083
- Remote OS Version: Ubuntu 18.04.5 LTS
- Remote Extension/Connection Type: SSH

Steps to Reproduce:

1. Remote-ssh to a remote Ubuntu server
2. Create a sample directory
3. In that directory, create the following three sample source code
  - hello.h
  ```
  extern void hello([] name);
  ```
  - hello.c
  ```
  #include<stdio.h>
  #include "hello.h"
  
  void hello(char[] name) {
      printf("%s\n", name);
  }
  ```
  - main.c
  ```
  #include "a.h"
  
  int main() {
      hello("Peter");
      return 0;
  }
  ```
4. In the Explorer view, click the button "open directory" and choose this sample directory. Open the terminal view, now your current working directory would be in this sample directory
5. Run the command `grep -nr "hello"` in your terminal view, the result would be as followed:
```
hello.h:1:extern void hello(char[] name);
main.c:4:    hello("Peter");
hello.c:4:void hello(char[] name) {
```
6. press and hold `ctrl` button, and use your mouse to hover over this three lines, you will find that in the first line, the underscore appears under `hello.h:1:extern`, and it appears under `main.c:4` in the second line, and `hello.c:4:void` in the last line.
7. press `ctrl` button and left click these three lines, only the `main.c:4` could jump to the correct file and the correct line of the source code, but others can't.
(BTW, sometimes it navigates to the correct file, but the first line of the source file instead of the correct line of code. For example, `ctrl`+click on the `main.c:4` mentioned above sometimes navigates to the first line of the `main.c` instead of the fourth line)

**Comment by Mingun** [comment]
I affected this bug too. VS Code no longer jumps to the line by Ctrl+clicking on the line in terminal (`cargo test` output in my case). It opens file and jumps to the first line of it. This is very serious bug!

It happens after upgrade to 1.70.0 from 1.69:
```
Версия: 1.70.0 (system setup)
Фиксация: da76f93349a72022ca4670c1b84860304616aaa2
Дата: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
ОС: Windows_NT x64 10.0.22000
```

**Comment by Mingun** [comment]
It seems that it is fixed there:
```
Версия: 1.70.2 (system setup)
Фиксация: e4503b30fc78200f846c62cf8091b76ff5547662
Дата: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
ОС: Windows_NT x64 10.0.22000
```

**Comment by Mingun** [comment]
Unfortunately, there still no end of this story. Correct jump only performed, if after clicking link in the terminal there is select file popup is shown. If the candidate only one, the popup is not shown and jump performed to the first line instead of desired.
