### ISSUE TITLE
Finalize shell integration sequences

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155639]
This issue tracks cleaning up the shell integration sequences, documenting and encouraging third parties to use the sequences.

Possible users:

- Windows Terminal (cc @zadjii-msft)
- Powershell vscode ext (cc @andschwa, @SeeminglyScience)
- Julia vscode ext (cc @pfitzseb)
- powerlevel10k (cc @romkatv)
- Python vscode ext
- Third party shell integration scripts (eg. if the fish community wanted to create a script #139400)

Some things to look into:

- [x] The continuation (`F`, `G`) and right prompt (`H`, `I`) sequences are not thoroughly tested, we should investigate whether we need these at all considering.
- [x] Review and document all known properties (`P`)?
  - [x] Should we support one of the common cwd properties instead of roll our own? Hostname and different sequences for different operating systems were some of the complications here.
  - [x] How should cwds be treated in ssh where VS Code's shell integration is installed?
  - [x] The `Task` should should be more generic
- [x] Improve command line (`E`) serialization of special characters
- [x] Should `633 A`-`D` be removed in favor of `133 A`-`D`? p10k works in a degraded state when sending these, if it also sent `E` (and `P`?) would it be fully functional?

The current sequences are lightly documented in code here:

https://github.com/microsoft/vscode/blob/f8aeb2013e6184b64bfd7455f5df6799c7c30a11/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L54-L118

**Comment by Tyriar** [comment]
PR is out for the VS Code side of this https://github.com/microsoft/vscode/pull/157571

Here are the answers to the questions above:

- **The continuation (F, G) and right prompt (H, I) sequences are not thoroughly tested, we should investigate whether we need these at all considering.**
  - These are no being finalized as they're barely used right now
- Review and document all known properties (P)?
  - IsWindows and Cwd will be finalized only
- Should we support one of the common cwd properties instead of roll our own? Hostname and different sequences for different operating systems were some of the complications here.
  - Yes, we should support these in addition to our own (see #157571)
- How should cwds be treated in ssh where VS Code's shell integration is installed?
  - This is a problem we can solve in time with backwards compatible changes
- The Task should should be more generic
  - This will not be finalized
- Improve command line (E) serialization of special characters
  - Moving to `\xAB` hex representation as most developers are aware of
- Should 633 A-D be removed in favor of 133 A-D? p10k works in a degraded state when sending these, if it also sent E (and P?) would it be fully functional?
  - The justification to keep these is in #157571

**Comment by andschwa** [comment]
Thanks for doing this @Tyriar!

**Comment by pfitzseb** [comment]
#15751 makes it sounds like *all* ASCII chars should be replaced by their char codes, but that's only strictly necessary for `'\n'` and `';'`, plus escaping of backslashes. Would it make sense to specify that in the docs?

**Comment by Tyriar** [comment]
@pfitzseb will clarify 👍

**Comment by Tyriar** [comment]
With the 2 PRs I'll call this closed, still open to feedback. The website docs will be covered in https://github.com/microsoft/vscode-docs/issues/4809, until then the in code comments are the main documentation.
