### ISSUE TITLE
The terminal process terminated with exit code: 2147483651 in visual code studio

### ISSUE THREAD

**Issue by nishant0131** [Microsoft/vscode#15567]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by Tyriar** [comment]
You need to provide a little more information than this if you need some help. Things to try:

- Update vscode to the latest version
- Check if it's working in the [Insiders](https://code.visualstudio.com/insiders) build (the absolute latest)
- Add a screenshot

**Comment by rprokhorov** [comment]
Actually, I have the same problem. As far as I understood, this problem connected with SRP (Software Restriction Policy) and path like "\\?\C:\..."
In Event log I have message like this:
"Access to  \\?\c:\Program Files (x86)\Microsoft VS Code\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe was restricred by SRP policy."

![2017-04-05_15-14-14](https://cloud.githubusercontent.com/assets/2035505/24705110/154deaec-1a13-11e7-9af3-e8f058ddb0c5.png)

In SRP i have trusted path like "Program Files"

**Comment by Tyriar** [comment]
Thanks @rprokhorov that's really helpful 😃, did you get the same error code 2147483651?

> Sorry for native language in screenshot. In SRP i have trusted path like "Program Files"

Did you have Program Files (x86) specified too? I wonder why the VS Code executable is fine to run but not `winpty-agent.exe`, maybe because of signing?

@rprichard FYI

**Comment by sdktr** [comment]
I have the same issue running the Powershell Debugger with VSCode on a SRP (Software Restriction Policy) enabled system. SRP kick in when VSCode wants to access:
`\\?\c:\Apps\VSCode\VSCode-win32-x64-1.14.2\resources\app\node_modules\node-pty\build\Release\winpty-agent.exe `

The C:\Apps -folder is excluded from SRP, but it seems VSCode tries to access the folder using a network-like syntax with \\?\ prefixed.

**Comment by sdktr** [comment]
Adding the special prefixed path to SRP as an additional allowed path provides a workaround.
