### ISSUE TITLE
darwin arm64 kernel panic after restart to update to 1.69.2 (Universal)

### ISSUE THREAD

**Issue by kaovilai** [microsoft/vscode#155656]
Does this issue occur when all extensions are disabled?: Not sure

Posting to keep track of this issue since it have appeared in the past on a different configuration.

Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z (1 day ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0
- OS Version: macOS Monterey 12.4

Steps to Reproduce:

1. Restart to update to 1.69.2 (Universal)
2. Kernel panic and device restarts

Related:
#114226
#123903

Problem details
<details>
<summary>Problem Details and System Configuration</summary>

> panic(cpu 2 caller 0xfffffe00111f76cc): Kernel data abort. at pc 0xfffffe0010c7e794, lr 0x0ef37e0010c7e790 (saved state: 0xfffffe4fbc5db0e0)
> 	  x0:  0x0000000000000000 x1:  0xfffffe200c904001  x2:  0x0000000000000000  x3:  0x0000000000000001
> 	  x4:  0x00000fc35dc0eb1e x5:  0x0000000000000001  x6:  0x0000000000000000  x7:  0xfffffe4fbc5daf60
> 	  x8:  0xfffffe0014469000 x9:  0x0000000000000000  x10: 0x0000000000000002  x11: 0xfffffe0013791210
> 	  x12: 0xfffffe00144a2118 x13: 0xfffffe200c904000  x14: 0xfffffe0014468000  x15: 0xfffffe00143f8000
> 	  x16: 0x0000000000000003 x17: 0xfffffe0014468430  x18: 0x0000000000000000  x19: 0xfffffe4fbc5db520
> 	  x20: 0xfffffe4fbc5db520 x21: 0xfffffe1b3540ce00  x22: 0x0000000000000000  x23: 0x00000090000002b0
> 	  x24: 0xfffffe1b3540ced8 x25: 0xfffffe4f6864b828  x26: 0x0000000000000298  x27: 0xfffffe4fbc5db8e0
> 	  x28: 0x0000000000000000 fp:  0xfffffe4fbc5db480  lr:  0x0ef37e0010c7e790  sp:  0xfffffe4fbc5db430
> 	  pc:  0xfffffe0010c7e794 cpsr: 0x60401208         esr: 0x96000006          far: 0x0000000000000008
> 
> Debugger message: panic
> Memory ID: 0x6
> OS release type: User
> OS version: 21F79
> Kernel version: Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000
> Fileset Kernelcache UUID: 77B58D4501F17D9FA036CFE982C6B773
> Kernel UUID: C44613B0-01A6-3609-A18D-29AC6CE3DAAF
> iBoot version: iBoot-7459.121.3
> secure boot?: YES
> Paniclog version: 13
> KernelCache slide: 0x00000000090c8000
> KernelCache base:  0xfffffe00100cc000
> Kernel slide:      0x0000000009884000
> Kernel text base:  0xfffffe0010888000
> Kernel text exec slide: 0x000000000996c000
> Kernel text exec base:  0xfffffe0010970000
> mach_absolute_time: 0xfc35dcb62c2
> Epoch Time:        sec       usec
>   Boot    : 0x62ba92e0 0x0003edb6
>   Sleep   : 0x62d6f859 0x00011807
>   Wake    : 0x62d6f859 0x000729ed
>   Calendar: 0x62d7180f 0x000ce829
> 
> Zone info:
>   Zone map: 0xfffffe10004f4000 - 0xfffffe30004f4000
>   . VM    : 0xfffffe10004f4000 - 0xfffffe14cd1c0000
>   . RO    : 0xfffffe14cd1c0000 - 0xfffffe1666b58000
>   . GEN0  : 0xfffffe1666b58000 - 0xfffffe1b33824000
>   . GEN1  : 0xfffffe1b33824000 - 0xfffffe20004f0000
>   . GEN2  : 0xfffffe20004f0000 - 0xfffffe24cd1bc000
>   . GEN3  : 0xfffffe24cd1bc000 - 0xfffffe2999e88000
>   . DATA  : 0xfffffe2999e88000 - 0xfffffe30004f4000
>   Metadata: 0xfffffe8fec280000 - 0xfffffe8ff4280000
>   Bitmaps : 0xfffffe8ff4280000 - 0xfffffe8fffdec000
> 
> CORE 0 PVH locks held: None
> CORE 1 PVH locks held: None
> CORE 2 PVH locks held: None
> CORE 3 PVH locks held: None
> CORE 4 PVH locks held: None
> CORE 5 PVH locks held: None
> CORE 6 PVH locks held: None
> CORE 7 PVH locks held: None
> CORE 8 PVH locks held: None
> CORE 9 PVH locks held: None
> CORE 0: PC=0xfffffe0010a35950, LR=0xfffffe00111ec0ac, FP=0xfffffe4fbf183c30
> CORE 1: PC=0xfffffe00109e42f8, LR=0xfffffe0010ebd278, FP=0xfffffe4fbf3d3f20
> CORE 2 is the one that panicked. Check the full backtrace for details.
> CORE 3: PC=0x0000000195fa59c8, LR=0x0000000195fa5c14, FP=0x000000016f9ce9f0
> CORE 4: PC=0xfffffe00109ac794, LR=0xfffffe00109ac78c, FP=0xfffffe4fc02fbb50
> CORE 5: PC=0x000000019398bc70, LR=0x00000001939ba954, FP=0x000000016fd13930
> CORE 6: PC=0x0000000193be4d28, LR=0x000000011327b9bc, FP=0x000000016d4c8180
> CORE 7: PC=0xfffffe00132f1658, LR=0xfffffe00132f1640, FP=0xfffffe4fc04aba60
> CORE 8: PC=0x0000000113763914, LR=0x0000000113c0ae5c, FP=0x000000016cff4040
> CORE 9: PC=0xfffffe0010af2538, LR=0xfffffe0011217774, FP=0xfffffe0015f37f40
> Compressor Info: 5% of compressed pages limit (OK) and 10% of segments limit (OK) with 1 swapfiles and OK swap space
> Panicked task 0xfffffe166d149418: 0 pages, 1 threads: pid 65920: renice
> Panicked thread: 0xfffffe200c904000, backtrace: 0xfffffe4fbc5da7a0, tid: 8335799
> 		  lr: 0xfffffe00109c9124  fp: 0xfffffe4fbc5da810
> 		  lr: 0xfffffe00109c8dec  fp: 0xfffffe4fbc5da880
> 		  lr: 0xfffffe0010b0df2c  fp: 0xfffffe4fbc5da8a0
> 		  lr: 0xfffffe0010affd00  fp: 0xfffffe4fbc5da910
> 		  lr: 0xfffffe0010afd9ac  fp: 0xfffffe4fbc5da9d0
> 		  lr: 0xfffffe00109777f8  fp: 0xfffffe4fbc5da9e0
> 		  lr: 0xfffffe00109c8a70  fp: 0xfffffe4fbc5dad80
> 		  lr: 0xfffffe00109c8a70  fp: 0xfffffe4fbc5dadf0
> 		  lr: 0xfffffe00111ef120  fp: 0xfffffe4fbc5dae10
> 		  lr: 0xfffffe00111f76cc  fp: 0xfffffe4fbc5daf90
> 		  lr: 0xfffffe0010affb00  fp: 0xfffffe4fbc5db000
> 		  lr: 0xfffffe0010afdb1c  fp: 0xfffffe4fbc5db0c0
> 		  lr: 0xfffffe00109777f8  fp: 0xfffffe4fbc5db0d0
> 		  lr: 0xfffffe0010c7e790  fp: 0xfffffe4fbc5db480
> 		  lr: 0xfffffe0010c68cf8  fp: 0xfffffe4fbc5db500
> 		  lr: 0xfffffe00124752f4  fp: 0xfffffe4fbc5db720
> 		  lr: 0xfffffe0012469318  fp: 0xfffffe4fbc5db7b0
> 		  lr: 0xfffffe001245aebc  fp: 0xfffffe4fbc5db870
> 		  lr: 0xfffffe0012452134  fp: 0xfffffe4fbc5dba50
> 		  lr: 0xfffffe001245b024  fp: 0xfffffe4fbc5dbad0
> 		  lr: 0xfffffe00111e7f08  fp: 0xfffffe4fbc5dbb50
> 		  lr: 0xfffffe0010eda678  fp: 0xfffffe4fbc5dbc20
> 		  lr: 0xfffffe0010edb340  fp: 0xfffffe4fbc5dbc90
> 		  lr: 0xfffffe0010f03e98  fp: 0xfffffe4fbc5dbd70
> 		  lr: 0xfffffe0010a17564  fp: 0xfffffe4fbc5dbe60
> 		  lr: 0xfffffe0010a1b2ec  fp: 0xfffffe4fbc5dbe90
> 		  lr: 0xfffffe00109c1068  fp: 0xfffffe4fbc5dbec0
> 		  lr: 0xfffffe0010977d6c  fp: 0xfffffe4fbc5dbed0
> 		  lr: 0xfffffe0010977ad0  fp: 0xfffffe4fbc5dbf20
> 		  lr: 0xfffffe0010980e78  fp: 0x0000000000000000
>       Kernel Extensions in backtrace:
>          com.apple.iokit.EndpointSecurity(1.0)[A269A219-43F0-3703-8AFB-7A1B811F0C05]@0xfffffe0012444300->0xfffffe001249a16b
>             dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[A9F6E230-0390-32A4-AFED-C6D734A41B54]@0xfffffe0011ce6430->0xfffffe0011d0122f
>             dependency: com.apple.security.quarantine(4)[9738A764-B59B-332B-8E05-F3D9EA5799AE]@0xfffffe001328b570->0xfffffe00132931c3
> 
> last started kext at 12629114999226: com.apple.driver.usb.cdc.ncm	5.0.0 (addr 0xfffffe00104cd280, size 5071)
> loaded kexts:
> com.apple.filesystems.autofs	3.0
> com.apple.UVCService	1
> com.apple.driver.AppleTopCaseHIDEventDriver	5450.8
> com.apple.driver.AppleBiometricServices	1
> com.apple.driver.CoreKDL	1
> com.apple.driver.usb.realtek8153patcher	5.0.0
> com.apple.driver.usb.AppleUSBHostBillboardDevice	1.0
> com.apple.driver.SEPHibernation	1
> com.apple.driver.BCMWLANFirmware4387.Hashstore	1
> com.apple.driver.DiskImages.ReadWriteDiskImage	493.0.0
> com.apple.driver.DiskImages.UDIFDiskImage	493.0.0
> com.apple.driver.DiskImages.RAMBackingStore	493.0.0
> com.apple.driver.DiskImages.FileBackingStore	493.0.0
> com.apple.driver.AppleUSBDeviceNCM	5.0.0
> com.apple.driver.AppleThunderboltIP	4.0.3
> com.apple.driver.AppleFileSystemDriver	3.0.1
> com.apple.nke.l2tp	1.9
> com.apple.filesystems.tmpfs	1
> com.apple.filesystems.lifs	1
> com.apple.filesystems.apfs	1934.121.2
> com.apple.IOTextEncryptionFamily	1.0.0
> com.apple.filesystems.hfs.kext	583.100.10
> com.apple.security.BootPolicy	1
> com.apple.BootCache	40
> com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
> com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
> com.apple.driver.AppleSmartIO2	1
> com.apple.driver.ApplePMP	1
> com.apple.driver.AppleCS42L84Audio	550.3
> com.apple.AppleEmbeddedSimpleSPINORFlasher	1
> com.apple.driver.AppleSN012776Amp	550.3
> com.apple.driver.AppleT6000SOCTuner	1
> com.apple.driver.AppleT6000CLPCv3	1
> com.apple.driver.AppleSmartBatteryManager	161.0.0
> com.apple.driver.AppleALSColorSensor	1.0.0d1
> com.apple.driver.AppleAOPVoiceTrigger	140.1
> com.apple.driver.ApplePMPFirmware	1
> com.apple.driver.AppleDPDisplayTCON	1
> com.apple.driver.AppleS8000AES	1
> com.apple.driver.AppleT6000PMGR	1
> com.apple.driver.AppleEventLogHandler	1
> com.apple.driver.AppleM68Buttons	1.0.0d1
> com.apple.driver.AppleS5L8960XNCO	1
> com.apple.driver.AppleSDXC	3.2.1
> com.apple.driver.AppleAVE2	550.16.0
> com.apple.driver.AppleAVD	564
> com.apple.AGXG13X	190.20
> com.apple.driver.AppleJPEGDriver	4.8.1
> com.apple.driver.AppleProResHW	176.6.0
> com.apple.driver.AppleMobileDispT600X-DCP	140.0
> com.apple.driver.AppleSPMIPMU	1.0.1
> com.apple.driver.usb.AppleSynopsysUSB40XHCI	1
> com.apple.driver.AppleMCDP29XXUpdateSupport	1
> com.apple.driver.AppleSamsungSerial	1.0.0d1
> com.apple.driver.AppleSerialShim	1
> com.apple.driver.AppleS8000DWI	1.0.0d1
> com.apple.driver.AppleInterruptControllerV2	1.0.0d1
> com.apple.driver.AppleT8110DART	1
> com.apple.driver.AppleBluetoothModule	1
> com.apple.driver.AppleBCMWLANBusInterfacePCIe	1
> com.apple.driver.AppleS5L8920XPWM	1.0.0d1
> com.apple.driver.AudioDMAController-T600x	150.1
> com.apple.driver.AppleT6000DART	1
> com.apple.driver.AppleSPIMC	1
> com.apple.driver.AppleS5L8940XI2C	1.0.0d2
> com.apple.driver.AppleT6000	1
> com.apple.iokit.IOUserEthernet	1.0.1
> com.apple.driver.usb.AppleUSBUserHCI	1
> com.apple.iokit.IOKitRegistryCompatibility	1
> com.apple.iokit.EndpointSecurity	1
> com.apple.driver.AppleDiskImages2	126.100.13
> com.apple.AppleSystemPolicy	2.0.0
> com.apple.nke.applicationfirewall	402
> com.apple.kec.InvalidateHmac	1
> com.apple.kec.AppleEncryptedArchive	1
> com.apple.driver.usb.cdc.ncm	5.0.0
> com.apple.driver.driverkit.serial	6.0.0
> com.apple.kext.triggers	1.0
> com.apple.iokit.IOAVBFamily	1040.6
> com.apple.plugin.IOgPTPPlugin	1040.3
> com.apple.iokit.IOEthernetAVBController	1.1.0
> com.apple.driver.AppleHSBluetoothDriver	5450.8
> com.apple.driver.IOBluetoothHIDDriver	9.0.0
> com.apple.driver.AppleActuatorDriver	5450.14
> com.apple.driver.AppleMultitouchDriver	5450.14
> com.apple.driver.AppleHIDKeyboard	228.2
> com.apple.driver.AppleMesaSEPDriver	100.99
> com.apple.iokit.IOBiometricFamily	1
> com.apple.driver.usb.IOUSBHostHIDDevice	1.2
> com.apple.driver.usb.cdc.ecm	5.0.0
> com.apple.driver.usb.cdc.acm	5.0.0
> com.apple.driver.usb.serial	6.0.0
> com.apple.driver.usb.cdc	5.0.0
> com.apple.driver.AppleUSBAudio	416.2
> com.apple.iokit.IOAudioFamily	340.2
> com.apple.vecLib.kext	1.2.0
> com.apple.driver.AppleTrustedAccessory	1
> com.apple.iokit.AppleSEPGenericTransfer	1
> com.apple.driver.AppleSEPHDCPManager	1.0.1
> com.apple.driver.DiskImages.KernelBacked	493.0.0
> com.apple.driver.AppleXsanScheme	3
> com.apple.driver.usb.networking	5.0.0
> com.apple.driver.AppleThunderboltUSBDownAdapter	1.0.4
> com.apple.driver.AppleThunderboltDPInAdapter	8.5.1
> com.apple.driver.AppleThunderboltDPAdapterFamily	8.5.1
> com.apple.driver.AppleThunderboltPCIDownAdapter	4.1.1
> com.apple.nke.ppp	1.9
> com.apple.driver.AppleHIDTransportSPI	5450.4
> com.apple.driver.AppleHIDTransport	5450.4
> com.apple.driver.AppleInputDeviceSupport	5450.4
> com.apple.driver.AppleBSDKextStarter	3
> com.apple.filesystems.hfs.encodings.kext	1
> com.apple.driver.AppleBTM	1.0.1
> com.apple.driver.AppleConvergedIPCOLYBTControl	1
> com.apple.driver.AppleConvergedPCI	1
> com.apple.driver.AppleBluetoothDebug	1
> com.apple.driver.AppleDCPDPTXProxy	1.0.0
> com.apple.driver.DCPDPFamilyProxy	1
> com.apple.driver.AppleDiagnosticDataAccessReadOnly	1.0.0
> com.apple.driver.AppleCSEmbeddedAudio	550.3
> com.apple.driver.ApplePassthroughPPM	3.0
> com.apple.driver.AppleAOPAudio	150.2
> com.apple.driver.AppleEmbeddedAudio	550.3
> com.apple.iokit.AppleARMIISAudio	140.2
> com.apple.AGXFirmwareKextG13XRTBuddy	190.20
> com.apple.AGXFirmwareKextRTBuddy64	190.20
> com.apple.driver.AppleSPU	1
> com.apple.iokit.IONVMeFamily	2.1.0
> com.apple.driver.AppleNANDConfigAccess	1.0.0
> com.apple.driver.AppleStockholmControl	1.0.0
> com.apple.driver.ApplePMGR	1
> com.apple.driver.AppleSART	1
> com.apple.iokit.IOGPUFamily	35.29
> com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
> com.apple.driver.DCPAVFamilyProxy	1
> com.apple.iokit.IOMobileGraphicsFamily-DCP	343.0.0
> com.apple.driver.AppleDCP	1
> com.apple.driver.AppleFirmwareKit	1
> com.apple.iokit.IOMobileGraphicsFamily	343.0.0
> com.apple.driver.AppleDialogPMU	1.0.1
> com.apple.driver.AppleSPMI	1.0.1
> com.apple.driver.AppleUSBXDCIARM	1.0
> com.apple.driver.AppleUSBXDCI	1.0
> com.apple.iokit.IOUSBDeviceFamily	2.0.0
> com.apple.driver.usb.AppleSynopsysUSBXHCI	1
> com.apple.driver.usb.AppleUSBXHCI	1.2
> com.apple.driver.AppleEmbeddedUSBHost	1
> com.apple.driver.usb.AppleUSBHub	1.2
> com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
> com.apple.driver.AppleT6000TypeCPhy	1
> com.apple.driver.AppleT8103TypeCPhy	1
> com.apple.driver.AppleHPM	3.4.4
> com.apple.driver.AppleARMWatchdogTimer	1
> com.apple.driver.AppleDisplayCrossbar	1.0.0
> com.apple.iokit.IODisplayPortFamily	1.0.0
> com.apple.driver.AppleTypeCPhy	1
> com.apple.driver.AppleThunderboltNHI	7.2.81
> com.apple.driver.AppleT6000PCIeC	1
> com.apple.iokit.IOThunderboltFamily	9.3.3
> com.apple.driver.ApplePIODMA	1
> com.apple.driver.AppleT600xPCIe	1
> com.apple.driver.AppleMultiFunctionManager	1
> com.apple.driver.AppleBluetoothDebugService	1
> com.apple.driver.AppleBCMWLANCore	1.0.0
> com.apple.iokit.IO80211Family	1200.12.2b2
> com.apple.driver.IOImageLoader	1.0.0
> com.apple.driver.AppleOLYHAL	1
> com.apple.driver.corecapture	1.0.4
> com.apple.driver.AppleEmbeddedPCIE	1
> com.apple.driver.AppleMCA2-T600x	640.5
> com.apple.driver.AppleEmbeddedAudioLibs	140.1
> com.apple.driver.AppleFirmwareUpdateKext	1
> com.apple.driver.AppleH13CameraInterface	6.51.1
> com.apple.driver.AppleH10PearlCameraInterface	17.0.6
> com.apple.driver.AppleGPIOICController	1.0.2
> com.apple.driver.AppleFireStormErrorHandler	1
> com.apple.driver.AppleMobileApNonce	1
> com.apple.iokit.IOTimeSyncFamily	1040.3
> com.apple.driver.DiskImages	493.0.0
> com.apple.iokit.IOGraphicsFamily	597
> com.apple.iokit.IOBluetoothSerialManager	9.0.0
> com.apple.iokit.IOBluetoothHostControllerUSBTransport	9.0.0
> com.apple.iokit.IOBluetoothHostControllerUARTTransport	9.0.0
> com.apple.iokit.IOBluetoothHostControllerTransport	9.0.0
> com.apple.driver.IOBluetoothHostControllerPCIeTransport	9.0.0
> com.apple.iokit.IOBluetoothFamily	9.0.0
> com.apple.driver.FairPlayIOKit	68.16.0
> com.apple.iokit.CSRBluetoothHostControllerUSBTransport	9.0.0
> com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	9.0.0
> com.apple.driver.AppleSSE	1.0
> com.apple.driver.AppleSEPKeyStore	2
> com.apple.driver.AppleUSBTDM	533.120.2
> com.apple.iokit.IOUSBMassStorageDriver	210.120.3
> com.apple.iokit.IOPCIFamily	2.9
> com.apple.iokit.IOSCSIBlockCommandsDevice	456.121.3
> com.apple.iokit.IOSCSIArchitectureModelFamily	456.121.3
> com.apple.driver.AppleIPAppender	1.0
> com.apple.driver.AppleFDEKeyStore	28.30
> com.apple.driver.AppleEffaceableStorage	1.0
> com.apple.driver.AppleCredentialManager	1.0
> com.apple.driver.KernelRelayHost	1
> com.apple.iokit.IOUSBHostFamily	1.2
> com.apple.driver.AppleUSBHostMergeProperties	1.2
> com.apple.driver.usb.AppleUSBCommon	1.0
> com.apple.driver.AppleSMC	3.1.9
> com.apple.driver.RTBuddy	1.0.0
> com.apple.driver.AppleEmbeddedTempSensor	1.0.0
> com.apple.driver.AppleARMPMU	1.0
> com.apple.iokit.IOAccessoryManager	1.0.0
> com.apple.driver.AppleOnboardSerial	1.0
> com.apple.iokit.IOSkywalkFamily	1.0
> com.apple.driver.mDNSOffloadUserClient	1.0.1b8
> com.apple.iokit.IONetworkingFamily	3.4
> com.apple.iokit.IOSerialFamily	11
> com.apple.driver.AppleSEPManager	1.0.1
> com.apple.driver.AppleA7IOP	1.0.2
> com.apple.driver.IOSlaveProcessor	1
> com.apple.driver.AppleBiometricSensor	2
> com.apple.iokit.IOHIDFamily	2.0.0
> com.apple.iokit.CoreAnalyticsFamily	1
> com.apple.driver.AppleANELoadBalancer	5.65.2
> com.apple.driver.AppleH11ANEInterface	5.65.2
> com.apple.AUC	1.0
> com.apple.iokit.IOAVFamily	1.0.0
> com.apple.iokit.IOHDCPFamily	1.0.0
> com.apple.iokit.IOCECFamily	1
> com.apple.iokit.IOAudio2Family	1.0
> com.apple.driver.AppleIISController	140.1
> com.apple.driver.AppleAudioClockLibs	140.1
> com.apple.driver.AppleM2ScalerCSCDriver	265.0.0
> com.apple.iokit.IOSurface	302.14
> com.apple.driver.IODARTFamily	1
> com.apple.security.quarantine	4
> com.apple.security.sandbox	300.0
> com.apple.kext.AppleMatch	1.0.0d1
> com.apple.driver.AppleMobileFileIntegrity	1.0.5
> com.apple.security.AppleImage4	4.2.0
> com.apple.kext.CoreTrust	1
> com.apple.iokit.IOCryptoAcceleratorFamily	1.0.1
> com.apple.driver.AppleARMPlatform	1.0.2
> com.apple.iokit.IOStorageFamily	2.1
> com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
> com.apple.iokit.IOReportFamily	47
> com.apple.kec.pthread	1
> com.apple.kec.Libm	1
> com.apple.kec.corecrypto	12.0
> 
> 
> 
> ** Stackshot Succeeded ** Bytes Traced 803873 (Uncompressed 2243184) **
> 

</details>

**Comment by deepak1556** [comment]
Does the issue happen with latest insiders https://code.visualstudio.com/insiders/ ?
