### ISSUE TITLE
Appearance of white squares in vs code

### ISSUE THREAD

**Issue by Rus85** [microsoft/vscode#155756]
Issue Type: <b>Bug</b>

In vs code, white squares periodically appear in different parts of the window. After some time of work, these white pieces no longer appear. But if you close and reopen vs code, the white shapes reappear.

![image](https://user-images.githubusercontent.com/38270282/180185393-8703de50-51e9-40a4-940a-38a000e87030.png)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/154910
