### ISSUE TITLE
Selected File in Search opens after closing and files and coming back to search

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#15574]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|vscode-eslint|dbaeumer|1.1.0|

---

Steps to Reproduce:

1. In search tab, conduct a search that reveals at least one match
1. Go back to "Explorer" tab
1. Close all open files
1. Go to "Search" tab, or hit ⌘-⬆️ -F
1. Note that input focus is no longer in the search input as expected, instead the file of the first match was opened, and the match is highlighted

Rationale:

This bugged me for the _longest_ time because I had no idea why _sometimes_ my flow could be "_toggle search, start typing_", and other times it was "_toggle search, move to mouse to select search input, start typing_". Especially in the latter case, if you start typing, then you're modifying a file (which requires additional effort to undo and re-select the proper control)

The expectation is that opening the search field will **always** change focus to the search input, but if you have no files open, then this is no longer the case.

Thanks for a fantastic editor!

**Comment by ramya-rao-a** [comment]
@julianlam I am not able to repro this. I tried in Mac OS X El Capitan and Windows 10

Whenever I toggle back to the Search tab, the search input box is always highlighted. Even if there are search results already and no files are open before toggling back to Search.

Can you share your user and workspace settings if any?

**Comment by julianlam** [comment]
Thanks @ramya-rao-a for shooting down my reproduction steps. They really weren't complete.

Here is version 2 😉 

1. In search tab, conduct a search that reveals at least one match
1. Click on that match to open the file
1. Go back to "Explorer" tab
1. Close all open files
1. Go to "Search" tab, or hit ⌘-⬆️ -F
1. Note that input focus is no longer in the search input as expected, instead the file of the first match was opened, and the match is highlighted

**Comment by ramya-rao-a** [comment]
Now I can repro, thanks!

**Comment by sandy081** [comment]
@julianlam It's a feature that to open the focussed match. But I see the buggy behaviour of loosing the focus. 

IMO the bug here is that typing Ctrl+Shift+F from Explorer, focus should be in Search input but not in the opened editor.
