### ISSUE TITLE
creating new branch with uncommitted changes in vscode.dev

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#155791]
I found it strange that when I create a new branch with uncommitted changes (getting ready to create a PR) I get asked if i want to switch to this branch. I found this a little unnecessary as we already do this in desktop and felt like it got in the way.

<img width="580" alt="CleanShot 2022-07-20 at 16 12 40@2x" src="https://user-images.githubusercontent.com/35271042/180098081-02faa824-2269-40b5-93bd-f7268fe71d44.png">

Steps:
1. create uncommitted changes
2. create new branch
3. :bug: dialog asks if you want to switch to branch

Expected branch to automatically switch with uncommitted changes

Version: 1.70.0-insider
Commit: 3da2d669a4dcf93938a262ba92f50b128ca7262a
Date: 2022-07-20T05:29:19.430Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36

**Comment by joyceerhl** [comment]
Switching to the new branch requires a window reload since in RemoteHub when we change the branch we are also changing the workspace URI, so it might be disconcerting if we did the reload without prompting. Would it be useful to introduce a setting controlling whether we prompt when switching branches?

**Comment by joyceerhl** [comment]
@misolori just to confirm, would you still want a setting to switch branches after creating them if it causes the tab to reload? We can't avoid the reload without extensive changes in core: https://github.com/microsoft/vscode-remote-repositories-github/issues/228

**Comment by misolori** [comment]
I don't mind the reload, just would rather avoid the dialog as that's what I imagine users would typically do right after creating a branch and closely matches desktop.

Would this be a setting or the default experience?
