### ISSUE TITLE
Extensions with `onTaskType` activation event are prematurely activated in Insiders 1.70.0-insider

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#155740]
Does this issue occur when all extensions are disabled?: N/A

Version: 1.70.0-insider (user setup)
Commit: 3da2d669a4dcf93938a262ba92f50b128ca7262a
Date: 2022-07-20T05:16:09.131Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Install an extension that has an `onTaskType` activation event. For example, the Docker extension has this.
2. Set up a task matching the above activation event.
3. Launch VSCode to a workspace containing the task.

Expected:
The extension will not be activated until the task is executed.

Actual:
The extension will be immediately activated.

This is a regression from the current stable release (1.69.2), which does not exhibit this behavior.

**Comment by bwateratmsft** [comment]
/cc @alexr00

I looked at telemetry and this has resulted in a very large spike to activations of the Docker extension in Insiders:
![image](https://user-images.githubusercontent.com/36966225/180012178-838db541-3f11-49dd-899b-0bc389e612fb.png)

**Comment by alexr00** [comment]
I'm still available for consulting, but @meganrogge and @Tyriar have taken over tasks!

**Comment by bwateratmsft** [comment]
Good to know, thanks!

**Comment by Tyriar** [comment]
Might be fixed by https://github.com/microsoft/vscode/pull/155606

**Comment by bwateratmsft** [comment]
@Tyriar I tried out today's build and it seems to no longer reproduce, so I'm inclined to agree that #155606 fixes it. I'll keep an eye on the telemetry data and see if the activations return to reasonable levels as folks get the latest build.

**Comment by Tyriar** [comment]
@bwateratmsft awesome, thanks for confirming. I expect some bad activations will remain for those that don't update Insiders asap, let me know if there's still an issue

**Comment by bwateratmsft** [comment]
Been watching the telemetry and it's dropped off by over 90% from the peak, so I'm confident it's fixed.

**Comment by bwateratmsft** [comment]
@Tyriar this seems to have regressed. I got an alert again for the machine count on Insiders, and the `onTaskType:docker-build` activation reason has spiked again:
![image](https://user-images.githubusercontent.com/36966225/186429281-44bbdfe1-5171-482f-9199-3bb91e25e589.png)

(The larger spike in the middle is when this originally broke.)

**Comment by meganrogge** [comment]
@bwateratmsft does it go down if you set `task.reconnection` to false? 

with that set to true, the activation is intentional because we need to restore the tasks

**Comment by bwateratmsft** [comment]
I'm not sure what you mean.

**Comment by meganrogge** [comment]
Trying to figure out if this is because of the recently added task reconnection which can be disabled via the `task.reconnection` setting

**Comment by bwateratmsft** [comment]
Ah, setting. It looks like it does only repro with `task.reconnection` set to `true`. This is not desirable behavior though, this results in a huge increase to activations of the Docker extension that do not need to happen. The extension only needs to be activated when the task has been run.

**Comment by meganrogge** [comment]
> The extension only needs to be activated when the task has been run.

That's not true from a task reconnections standpoint atm. 

>huge increase to activations of the Docker extension

I will look into this next iteration

For now, you have a workaround - to keep it disabled

**Comment by bwateratmsft** [comment]
Edited; the setting is not working. Additionally, we can't ask every user to apply this setting.

**Comment by meganrogge** [comment]
> the setting is not working

meaning disabling it does not improve performance or the setting doesn't get applied?

**Comment by bwateratmsft** [comment]
> > the setting is not working
> 
> meaning disabling it does not improve performance or the setting doesn't get applied?

Disabling it seems to have no effect on whether the extension is activated prematurely or not.

**Comment by bwateratmsft** [comment]
I tested today's Insiders build and the issue appears fixed. I'll keep an eye on the telemetry again.

**Comment by bwateratmsft** [comment]
> I tested today's Insiders build and the issue appears fixed. I'll keep an eye on the telemetry again.

Telemetry looks good, the values came way down after the fix on the 24th. The circled values are the weekend and can be disregarded (there is normally a significant drop over the weekend):
![image](https://user-images.githubusercontent.com/36966225/187452819-c79b5a57-e9e9-4cc8-9fe7-279d77f25c03.png)
