### ISSUE TITLE
Debug object information not readable ([object Object])

### ISSUE THREAD

**Issue by asbrum** [microsoft/vscode#155718]
Issue Type: <b>Bug</b>

Development environment is an angular workspace

Since VS Code Update 1.69.x debug information are not properly shown. All objects are displayed as [object Object]. (see screenshots to compare Versions)

Steps to reproduce:
Debug any Angular component
After breakpoints hits, hover a variable or put it in watch

// Edit: it still occurs in 1.69.2

Version 1.68.1
![grafik](https://user-images.githubusercontent.com/58296725/179969338-e0e6d0a8-14b3-4bf1-9218-05b3a81c2e06.png)
Version 1.69.1
![grafik](https://user-images.githubusercontent.com/58296725/179969357-53a27b9f-51b2-4680-9e2a-9f42b368e7ff.png)

VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-14T12:48:58.283Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.87GB (16.23GB free)|
|Process Argv|--crash-reporter-id 6fea4f18-8398-46dc-a561-6c8b76b117c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp-to-typescript|adr|1.12.1
ng-template|Ang|14.0.1
path-intellisense|chr|2.8.1
angular-schematics|cyr|5.2.5
git-diff-and-merge-tool|dav|1.0.5
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-highlight|fab|1.6.0
vscode-todo-plus|fab|4.18.4
vscode-firefox-debug|fir|2.9.7
vscode-jest-runner|fir|0.4.48
vscode-angular-html|gha|1.8.0
vscode-commandbar|gsp|0.3.1
vscode-guid|hea|1.4.20
git-assistant|iva|1.3.14
run-in-terminal|kor|0.0.5
git-graph|mhu|1.30.0
vscode-scss|mrm|0.10.0
vs-keybindings|ms-|0.2.1
color-highlight|nau|2.5.0
angular-console|nrw|17.18.8
vscode-jest|Ort|4.6.0
vscode-versionlens|pfl|1.0.10
vscode-css-navigation|puc|1.13.3
vscode-smoothtype|spi|1.2.0
sass-indented|syl|1.8.22
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.13.0

(2 theme extensions excluded)

</details>

**Comment by connor4312** [comment]
In 1.69, if a type has a non-native code `toString()` method, we call that to render the preview. I'm guessing Angular does have a custom toString but delegates to the native code in the base case. We should double check and not use `[object *]` for previews.

**Comment by Balastrong** [comment]
To add some more info, under `VARIABLES` it works fine, only under `WATCH` shows `[Object object]`.


![image](https://user-images.githubusercontent.com/7253929/180454565-cd663ed0-b86a-421b-9ef0-ec0605cae6fd.png)

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode-js-debug/pull/1339

**Comment by TylerLeonhardt** [comment]
@connor4312 any steps?

**Comment by connor4312** [comment]
1. `npm install -g @angular/cli && ng new hello-world && cd hello-world && code-insiders . && npm start` (accepting the defaults is fine)
2. Add this to `app.component.ts`:
```
  constructor() {
    debugger;
  }
```
4. Run `Debug: Open Link` to localhost:4200
5. Add `this` to the **WATCH** view and verify that you get an object preview instead of `[object Object]`

**Comment by TylerLeonhardt** [comment]
![image](https://user-images.githubusercontent.com/2644648/181823794-eeb7d4de-3b7e-43ba-ace2-7f59174467c7.png)

LGTM!
