### ISSUE TITLE
JS debugger session terminates while inspecting `this` inside `<instance_member_initializer>`

### ISSUE THREAD

**Issue by robertrossmann** [microsoft/vscode#155708]
Does this issue occur when all extensions are disabled?: Yes/No

While debugging a JavaScript project (TS-compiled) my debugging session crashes / stops unexpectedly when I try to inspect contents of `this` inside an instance member's initializer step. I do not see any error logs in the debug console nor in the `OUTPUT` panel's various streams. Video demonstrating the problem attached.

```
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

Steps to Reproduce:

1. Define a class that has instance members with an initial value which somehow uses `this` value
2. Add breakpoint at the member initialization line
3. Start debugging session
4. Observe debugger properly breaks at the breakpoint
6. Hover over `this` value in the initializer
7. Observe debug session abruptly ends

"Proof" 😄 

https://user-images.githubusercontent.com/3058150/179950207-4f0f57fb-2ca2-488b-ba90-ccfe299e7597.mov

**Comment by connor4312** [comment]
That's exciting. Can you confirm what version of Node.js you're running?

**Comment by robertrossmann** [comment]
This is Node.js v18.2.0. Let me know if I should try with a different one! 🕵️

**Comment by connor4312** [comment]
Thanks, I will investigate this after I get over COVID

**Comment by connor4312** [comment]
Thanks for the issue. This appears to be an upstream Node.js bug, which reproduced in both VS Code and the native inspector in the latest Node.js version (18.7.0). I've therefore opened an issue here: https://github.com/nodejs/node/issues/44124
