### ISSUE TITLE
VSC shows an error when using PHP mixed with HTML 

### ISSUE THREAD

**Issue by RafaelLinux** [microsoft/vscode#155730]
Issue Type: <b>Bug</b>

Usually we need to mix PHP code with HMTL. We have a php file with that kind of mix, but we discovered that VSC shows a "'}' expected.  ", but the code below is correct and working:

```
<!-- HTML code -->
<?php 
	if (true) 
{?>
<!-- HTML code -->
<? } ?>
<!-- HTML code -->
```

VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:23:40.286Z)
OS version: Linux x64 5.18.1-1-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 4425)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|12, 11, 10|
|Memory (System)|15.47GB (3.16GB free)|
|Process Argv|--unity-launch /run/user/1000/kio-fuse-OwtzwC/ftp/adminweb@10.162.0.27/var/www/cultura/ceex/cont_donaciones.inc.php --crash-reporter-id 2ace93db-d4f2-4e01-b308-fccb644a463c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (38)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
jsonviewer|cci|1.2.3
split-line|che|1.0.2
vscode-svgviewer|css|2.0.0
githistory|don|0.6.19
vscode-html-css|ecm|1.13.0
prettier-vscode|esb|9.5.0
php-intellisense|fel|2.3.14
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
beautify|Hoo|1.5.0
minify|Hoo|0.4.3
mysql-syntax|jak|1.3.1
vscode-view-charset|lon|0.0.9
banner-comments-plus|lun|0.3.1
json|Mee|0.0.1
prettify-json|moh|0.0.3
vscode-language-pack-es|MS-|1.67.3
python|ms-|2022.8.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.4.1021342353
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.8
remote-containers|ms-|0.241.3
vscode-json-editor|nic|0.3.0
linux-desktop-file|nic|0.0.21
live-preview|pro|0.0.3
format-html-in-php|rif|1.7.0
preview-vscode|sea|2.2.5
code-settings-sync|Sha|3.4.3
comment-box|Sly|2.2.0
html-to-css-autocompletion|sol|1.1.2
php-formatter|Sop|0.2.4
insert-special-symbol|swi|1.3.0
vscode-icons|vsc|11.13.0
php-debug|xde|1.27.0
json|Zai|2.0.2

(2 theme extensions excluded)

</details>

**Comment by RafaelLinux** [comment]
Excellent, you have reason. I should have been installed latest version before notifying nothing here.
Issue is solved 2 versions later, so THANK YOU!!

**Comment by RafaelLinux** [comment]
I wrote too fast. Issue is still there in latest version!!! (it is showed after a while)
![imagen](https://user-images.githubusercontent.com/13048959/180171397-76cec9ef-e5b3-4274-b01b-3c47844fd22b.png)

**Comment by RafaelLinux** [comment]
I observed that this issue doesn't appear when the VSC window is in "restricted mode". 

![imagen](https://user-images.githubusercontent.com/13048959/181717364-52002497-6d19-4aaa-9030-14daf07dbee2.png)

If I just click left down in "Restricted mode" and trust in that window, is when issue happens.

![imagen](https://user-images.githubusercontent.com/13048959/181717795-c3680da0-2807-4a6b-b396-066b99a34486.png)

**Comment by roblourens** [comment]
Is this coming from the "php-intellisense" extension that you have installed?

**Comment by RafaelLinux** [comment]
I'm sorry, I was on vacation. I disabled that plugin and issue disappeared so I'm sorry for opening this thread.
I'll write to php-intellisense developers about this issue.

Thank you!!!
