### ISSUE TITLE
Unable to programmatically write a file in vscode.dev

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#155787]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69 (Web)
- OS Version: MacOS

Issue:

We have an extension which creates build files from a users source files, but we've noticed that writing these files when a folder is first opened in vscode.dev doesn't work.

We are using the `vscode.workspace.fs.writeFile()` function, but don't see a prompt from the FileSystem API in the browser to confirm write permission to the folder. Does the `writeFile()` functionality invoke the permissions API in the same way as other automated functionality which does show this prompt (e.g. autosave)?

Calling `vscode.workspace.fs.isWritableFileSystem()` returns true, it looks like the function succeeds, but files are not created.

Once the user has edited a file causing the permissions prompt to appear, our programatic save then works.

Steps to Reproduce:

1. Have a Web Extension which uses the `vscode.workspace.fs.writeFile()` function to create a file
2. Use this extension in vscode.dev and open a local folder (confirming the `read` permissions prompt)
3. Have the extension programatically write a file
4. Observe no prompt for `write` permissions to the folder and no error is thrown
5. Files are not created

Expectation: using the `vscode.workspace.fs.*` API would trigger any relevant permissions prompt to appear.

**Comment by jrieken** [comment]
@bpasero likely an issue with the local-file system provider for web

**Comment by bpasero** [comment]
@thegecko can you share sample code for this issue and explain exactly how you locally run the extension to reproduce for me in the same setup.

**Comment by thegecko** [comment]
> @thegecko can you share sample code for this issue and explain exactly how you locally run the extension to reproduce for me in the same setup.

I can!

**Comment by thegecko** [comment]
Ha! A simple example of this works, so I suspect the FileSystem API write needs to be connected to a user interaction which is lost somewhere along the way. I'll dig a little deeper...

**Comment by bpasero** [comment]
> FileSystem API write needs to be connected to a user interaction

Yes it does, it is unlikely we can trigger a file system call without user interaction.

**Comment by thegecko** [comment]
OK, I've managed to prove that this is a timing issue.

With a delay of >30s between the user interaction and the files being written (e.g. a build running), the write prompt will not appear.

I fear this is part of the FileSystem API security model so can't be changed. However a workaround is to write and delete a temporary file earlier to force the workspace to be "writeable".

Happy to close this issue.
