### ISSUE TITLE
Can not change comment body and enter edit mode at the same time

### ISSUE THREAD

**Issue by joscol** [microsoft/vscode#155764]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Windows 11

Steps to Reproduce:

1. Create an extension that uses `CommentNode`
2. Attempt to change the comment body and switch to edit mode at the same time

Expectation:
Comment should switch to edit mode with the new content

Result:
Text box shows older comment body

Additional details:
When rendering the comment normally, the extension replaces work item mentions ( #number ) with clickable links to the work item.  When the user clicks the edit button, the extension is attempting to restore the original #number text for the user to edit but is instead being presented with the markdown link `[title](url)`.

**Comment by TylerLeonhardt** [comment]
@joscol  can you try out the latest insider build of VS Code: http://code.visualstudio.com/insiders if the issue is fixed there, can you please respond with `/verified` so we can mark this issue as verified to be fixed?

**Comment by TylerLeonhardt** [comment]
@alexr00

**Comment by alexr00** [comment]
You should be able to verify with the comments sample extension by adding a line here:

https://github.com/microsoft/vscode-extension-samples/blob/039da585afdb164282ea9a8d1f73dae4f9912319/comment-sample/src/extension.ts#L123-L125

such that there are consecutive calls to set the `body` and then `mode` of the comment. Then, build and run the extension, execute the command, and verify that the comment body is updated when the comment widget goes into edit mode.
