### ISSUE TITLE
Markdown preview will not show relative image in Submodule

### ISSUE THREAD

**Issue by Alice52** [microsoft/vscode#155700]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: windows10

Steps to Reproduce:

1. Create a repo with name A
    ```shell
   images/
      a.png
    ```
2. Create another repo with name B: submodule
    ```shell
   images/
      b.png
    ```
3. Add second repo (B) as submodule in A repo
4. when open markdown preview in B repo, the image cannot display correctly
    - readme.md contains b.png: `![avatar](/images/b.png)`, which is not work
    - and `![avatar](/b/image/b.png)` is worked, but if I just open b repo alone as markdown preview, the image will not be shown.

**Comment by mjbvz** [comment]
Can you please share a small GitHub project with this setup?

**Comment by Alice52** [comment]
> Can you please share a small GitHub project with this setup?

Hi, this is a small [project](https://github.com/Alice52/a) with above setup. 

1. If I open b repo alone in vscode, which is submodule repo, and everything is work finely
    ![image](https://user-images.githubusercontent.com/42330329/180116682-1a0861d3-9432-48f3-a37a-198dad644331.png)

2. But if I open a repo alone, which contains submodule b repo, then do markdown preview of b's `readme.md`
    ![image](https://user-images.githubusercontent.com/42330329/180116827-611f3422-2153-4441-9262-d93bbeca57a5.png)
    - As shown in fig, the image cannot be shown correct.

**Comment by mjbvz** [comment]
Thanks! 

This is expected. When you use `/`, that refers to the root of the current workspace. The markdown extension doesn't have any understanding of git submodules and that you intend `/` paths to be resolved absolute to the submodule (and I don't think it should either)

You can fix this by adding the submodule as a workspace folder to the workspace: https://code.visualstudio.com/docs/editor/multi-root-workspaces

![Screen Shot 2022-07-22 at 3 26 06 PM](https://user-images.githubusercontent.com/12821956/180576482-e2254cd3-50ee-47e0-8082-d086243078f2.png)
