### ISSUE TITLE
Support shell integration even when 133 B/633 B doesn't come in

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155775]
Playing around with nushell which has basic shell integration but doesn't fire B yet. Should we support registering command markers even when B doesn't happen?

**Comment by wmstack** [comment]
I was playing around in Nushell, and these dots appear even after clearing the shell:
![image](https://user-images.githubusercontent.com/58462210/181732675-2597d260-ce45-45ae-b63d-f8a19579c218.png)

**Comment by Tyriar** [comment]
@wmstack whay version of nushell are you on and how did you clear the terminal?

**Comment by wmstack** [comment]
I am using Nushell `0.66.2`, I cleared the terminal with Nushell's built-in `clear` command, and I am using Windows 10, 64 bit.

**Comment by wmstack** [comment]
I think this issue is hard to find as the name doesn't suggest the error in question here. So maybe some people might discover this issue if the title is changed.

**Comment by meganrogge** [comment]
@Tyriar isn't this more of a feature request than a bug?

**Comment by Tyriar** [comment]
I think nushell is working fine now, a new more targeted issue should be opened if there's still a problem
