### ISSUE TITLE
Unable to install extensions on attached docker container

### ISSUE THREAD

**Issue by guy0guy** [microsoft/vscode#155728]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:1.69.2
- OS Version:Linux

Steps to Reproduce:

1.install vscode version 1.69.2
2. open vscode
3. using docker extension, attach vscode to running container
4. choose to install local extensions in container

(on version 1.68.1 it is working)

below is an image with the trace logs (it keeps retrying with the same trace a few times and then give up)

![image](https://user-images.githubusercontent.com/107554435/179982713-f0860f7c-8ab8-4957-a61b-81d23bdbdf2e.png)

below is the remote server trace log:
![image](https://user-images.githubusercontent.com/107554435/179985518-d4b34421-cf58-4530-8111-53288aad7cfe.png)

**Comment by sandy081** [comment]
Seems proxy related

**Comment by guy0guy** [comment]
The issue is involving proxy problems - the container does not have proper proxy settings so it cannot access outside.
But even so, in previous versions 1.68.1 and before - it was still able to work (probably the host would download the needed data and than transfer it to the container without the container directly access outside network).
Is there a change in some default settings in the new versions that could cause the change in behavior  (if so what were these and how to change them), or could it be that there is some new bug/issue that prevents this to work properly now?

**Comment by chrmarti** [comment]
Maybe it worked because the Dev Containers extension copies previously downloaded VSIXs to the container. Not sure why this would stop working, can you confirm it still works with 1.68.1 today? Could you append the full log from when it fails? (`F1` > `Dev Containers: Show Container Log`)
