### ISSUE TITLE
When you click status bar, there will be a white border.

### ISSUE THREAD

**Issue by hua03** [microsoft/vscode#155799]
Issue Type: <b>Bug</b>

repoduce: 
    Click on the blank area of status bar.

![image](https://user-images.githubusercontent.com/19561959/180121611-e23a9f4e-0fc1-4c11-ba70-9f5b9c8c77a6.png)

![image](https://user-images.githubusercontent.com/19561959/180121751-1addf141-ed1e-4697-b606-0ee992e0718f.png)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (12.15GB free)|
|Process Argv|--crash-reporter-id 25337f27-0fd6-4ad2-a343-d23e45e01d53|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.69.7130921

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30531698

```

</details>

**Comment by gjsjohnmurray** [comment]
Perhaps this is the focus indicator. What happens if you then press Tab?

**Comment by hua03** [comment]
When  the area which is not status bar is focusing, press tab will not change status bar. When status bar is focusing, press tab, the white border will disappear.

**Comment by gjsjohnmurray** [comment]
After you click and get the white border do the left and right arrow keys move you between status bar items?

**Comment by hua03** [comment]
Yes, when it appear, press left or right keys, the white border also changed. 

Uploading 屏幕录制2022-07-21 16.40.12.mov…

**Comment by gjsjohnmurray** [comment]
That is an accessibility aid. Command Palette includes `View: Focus Status Bar` so keyboard-only users can quickly focus onto it, after which they use left and right to go to the item they want to trigger, then press Enter or spacebar to "click" it.

**Comment by hua03** [comment]
thanks for you answer.
