### ISSUE TITLE
Reveal in Finder doesn't work for file with file nesting

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#155766]
Type: <b>Bug</b>

@sbatten

https://user-images.githubusercontent.com/41773861/180045825-2ead9f5b-ca48-49a0-b34e-5c75f22f3628.mov

VS Code version: Code - Insiders 1.70.0-insider (Universal) (3da2d669a4dcf93938a262ba92f50b128ca7262a, 2022-07-20T05:16:19.460Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv|--crash-reporter-id a6dbd290-6b39-42a4-b4c8-4df35290a499|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (71)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
extendscript-debug|Ado|2.0.3
tsl-problem-matcher|amo|0.6.2
file-nesting|ant|1.0.0
color-info|bie|0.7.0
github-markdown-preview|bie|0.3.0
jsdoc-markdown-highlighting|bie|0.0.1
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.14.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
file-browser|bod|0.2.10
vscode-translation|cai|2.0.6
vscode-url-title-resolver|cap|1.1.1
compare-view|che|0.7.0
vscode-opennewinstance|chr|0.0.12
gitignore|cod|0.8.0
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
tsimportsorter|doz|7.4.19
css-flexbox-cheatsheet|dzh|3.3.1
css-initial-value|dzh|0.2.6
gitlens-insiders|eam|2022.7.2005
vscode-html-css|ecm|1.13.0
prettier-vscode|esb|9.5.0
code-runner|for|0.11.8
shell-format|fox|7.2.2
todo-tree|Gru|0.0.215
vscode-nginx-conf-hint|han|0.3.0
path-autocomplete|ion|1.19.1
vscode-env|Iro|0.1.0
markdown-kbd|jja|0.4.2
svg|joc|1.4.19
vscode-gutter-preview|kis|0.30.0
template-string-converter|meg|0.6.0
hexeditor|ms-|1.9.7
js-debug-nightly|ms-|2022.7.1117
live-server|ms-|0.2.12
test-adapter-converter|ms-|0.1.6
vscode-js-profile-flame|ms-|1.0.4
vscode-typescript-next|ms-|4.8.20220719
vetur|oct|0.35.0
vscode-twoslash-queries|Ort|1.0.2
vscode-versionlens|pfl|1.0.10
git-file-history|pom|1.0.1
text-power-tools|qcz|1.34.0
vscode-xml|red|0.21.0
vscode-yaml|red|1.9.1
vue-vscode-snippets|sdr|3.1.1
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.3.1
vscode-stylelint|sty|1.2.2
markdowntable|Tak|0.10.0
hosts|tom|1.2.0
vscode-choosealicense|ult|0.7.0
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.13.0
snippet-generator|wen|0.3.2
modify-file-warning|YuT|0.0.2
open-in-external-app|YuT|0.5.0
regexp-tools|YuT|0.0.1
scripting-listener|YuT|0.0.3
view-github-repository|YuT|1.1.0
vscode-archive|YuT|0.1.2
vscode-fe-helper|YuT|0.2.1
ytj-snippets|YuT|0.0.5
markdown-all-in-one|yzh|3.4.3
node-modules|zyr|1.4.1

(1 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
Mine reveals but it reveals the child and not the parent so definitely a bug

**Comment by sbatten** [comment]
@lramos15 if you ensure that no item in the explorer view has focus, then right click the parent, nothing will happen when you reveal in explorer/finder
