### ISSUE TITLE
Regex search issue

### ISSUE THREAD

**Issue by crayment** [Microsoft/vscode#15579]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|calc|BorisA|0.0.1|
|MyExtensions|none|0.0.1|
|erb|CraigMaslowski|0.0.1|
|swift|Kasik96|0.0.2|
|calculate|acarreiro|1.1.0|
|githistory|donjayamanne|0.1.0|
|prettify-json|mohsen1|0.0.3|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|Ruby|rebornix|0.10.1|
|move-fast|selbh|0.1.0|
|swiftlint|shinnn|0.1.3|

---

Steps to Reproduce:

1. Hit cmd+f to start a search and toggle on the regex button
2. Perform a search that has multiple matches
3. Hit option+enter to place multiple cursors on all matches
4. Press cmd+f again to refocus the find bar
5. Notice that the regex you types is now gone! Replaced by a match or a previous search or something.

**Comment by ramya-rao-a** [comment]
@alexandrudima Related to #10386 ?

**Comment by rebornix** [comment]
This is already fixed in Insiders.
