### ISSUE TITLE
Render whitespaces only when text is selected

### ISSUE THREAD

**Issue by raztd** [Microsoft/vscode#15578]
I would like an option to render whitespaces only when text is selected.
Like the default behavior in SublimeText 3

![ws](https://cloud.githubusercontent.com/assets/6805609/20357351/49afa740-ac30-11e6-98f6-aa622967290b.png)

**Comment by ramya-rao-a** [comment]
Do you mean the indent guides?

![image](https://cloud.githubusercontent.com/assets/16890566/20361078/193a1360-abeb-11e6-8c9c-4cd4240b9958.png)

**Comment by raztd** [comment]
Yes. In VSCode they always appear when "editor.renderWhitespace" is set to "boundary" or "all"

**Comment by Hurtak** [comment]
Probably duplicate of https://github.com/Microsoft/vscode/issues/1477

**Comment by ramya-rao-a** [comment]
Thanks @Hurtak !

Closing as duplicate of #1477

@raztd Can you upvote #1477 ?
