### ISSUE TITLE
code.cmd <file> should be able to open in a new instance of code.exe rather than recycle an existing instance

### ISSUE THREAD

**Issue by NickVH-MS** [microsoft/vscode#155798]
When I open from the command line via code.cmd, I'm distressed to find it reusing an existing vscode instance somehow. This is not the behavior I want. Please launch in a new window, or at least add a command-line switch for this.

**Comment by joaomoreno** [comment]
Running `code --help` will show you many options. One of them is `-n --new-window`.

**Comment by NickVH-MS** [comment]
I see, thanks!
