### ISSUE TITLE
Adopt Snippet support in completion items in LSP

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#15577]
VSCode Version: 1.8.x

**Comment by dbaeumer** [comment]
See https://github.com/Microsoft/vscode/issues/3210#issuecomment-260959818

**Comment by aeschli** [comment]
Added in master https://github.com/Microsoft/vscode-languageserver-node/commit/08d578b42916a368c1d4a7321a384a569bbd560f as well as for 2.6
(https://github.com/Microsoft/vscode-languageserver-node/tree/2.6-next)

Published to npm as 2.6.4-next.1 (client), 2.6.2-next.1 (server), 1.0.5-next.1 (types)

**Comment by dbaeumer** [comment]
Thanks Martin !

**Comment by svenefftinge** [comment]
I don't get why the protocol needs the SnippetString which just wraps a single string?
Also leveraging union types in the protocol is problematic for languages that don't support them (like Java).
