### ISSUE TITLE
Git decorator colors not consistently appearing

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#155755]
Noticed that the git decorator colors are not consistently showing up in either the explorer or SCM view:

<img width="257" alt="CleanShot 2022-07-20 at 08 56 47@2x" src="https://user-images.githubusercontent.com/35271042/180028212-f95a5639-3512-49d8-8e6a-72b958da837f.png">

<img width="254" alt="CleanShot 2022-07-20 at 08 57 53@2x" src="https://user-images.githubusercontent.com/35271042/180028410-24b43937-c555-40d3-81a7-92638acf826e.png">

And when I open the file, the decorators finally show up:

<img width="262" alt="CleanShot 2022-07-20 at 08 57 17@2x" src="https://user-images.githubusercontent.com/35271042/180028297-65f9889c-4493-45e4-8e52-983e4d1404a0.png">

<img width="255" alt="CleanShot 2022-07-20 at 08 57 42@2x" src="https://user-images.githubusercontent.com/35271042/180028355-a85775b7-f2a2-4f84-9261-c1185227f060.png">

Version: 1.70.0-insider (Universal)
Commit: 3da2d669a4dcf93938a262ba92f50b128ca7262a
Date: 2022-07-20T05:16:19.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

**Comment by ocup0311** [comment]
same here.

That's the git decorator colors also not showed  in the file as below (the blue decorator ):

<img width="60" alt="截圖 2022-07-21 下午12 23 16" src="https://user-images.githubusercontent.com/51013776/180146893-aeb4e93f-c8e0-4ead-b9c9-c853dd3d4751.png">

**Comment by ocup0311** [comment]
## Share my situation:
For some reason, it took me to disable the built-in git extension, and then I can't find that extension again.

## Solution:
To search built-in extension, you need to add a tag `@builtin`.

## For example:
a. search `git`, you can't get the built-in git:
<img width="355" alt="截圖 2022-07-22 上午10 11 31" src="https://user-images.githubusercontent.com/51013776/180347860-9acdb92e-764d-40b0-b3e0-1c563db93fce.png">

b. search `@builtin git`:
<img width="363" alt="截圖 2022-07-22 上午10 11 49" src="https://user-images.githubusercontent.com/51013776/180347870-f7008e36-6042-450d-861d-f7f4003a8429.png">

## And maybe you also need to setup some configs in "settings.json":

```json
  "git.enabled": true,
  "git.decorations.enabled": true
```

how to open "settings.json": 
1. `F1` or `ctr` + `shift` + `p` ( mac: `command` + `shift` + `p` )
2. type `settings.json`

**Comment by lszomoru** [comment]
There are probably two issues here: 
1. The error decorators (`3`) do not show up in Explorer and the Source Control view.  @mjbvz is there a known issue for that?
2. A file that contains errors is represented differently in the Source Control view. @joaomoreno, is that by design or a bug?

**Comment by mjbvz** [comment]
@lszomoru I think @jrieken may own file decorations
