### ISSUE TITLE
Synchronization for settings

### ISSUE THREAD

**Issue by MuNaiYi520** [Microsoft/vscode#15575]
- VSCode Version:1.7.1
- OS Version:win10 14959

Steps to Reproduce:

1. Add synchronization for both settings and extensions

**Comment by rebornix** [comment]
For settings, there is already an extension out there, try `ext install EditorConfig` in command palette.

**Comment by ramya-rao-a** [comment]
@MuNaiYi520 Can you add more details? Sync across workspaces? Machines ?

**Comment by MuNaiYi520** [comment]
@ramya-rao-a I hope to be able to synchronize the settings on different computers, work is a computer, home to continue to work is another computer.

**Comment by ramya-rao-a** [comment]
There are quite a few issues logged for this purpose.
#10114
#9999
#2743

Please add your thoughts/upvotes there
