### ISSUE TITLE
The 'ext install' command is unavailable after compiling from the sources

### ISSUE THREAD

**Issue by markbook2** [Microsoft/vscode#1557]
I compiled the VSCode as described [here](https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run-from-source). After that I have created the `code` script with the following content:
```
(cd /some/path/vscode/src/scripts && ./code.sh)
```
and made it executable:
```
chmod +x /usr/local/bin/code
```
After that when I run the VSCode, hit Ctrl-Shift-p and type `ext install` I see the 'No extensions found' message, please see the attached file.
![vscode bug](https://cloud.githubusercontent.com/assets/9556817/11943974/21af2cc0-a853-11e5-90d2-f22a6ae37c17.png)

When I type the `extension` I see the only 'Extensions: Show Installed Extensions' message, please see the next attached file.
![vscode bug1](https://cloud.githubusercontent.com/assets/9556817/11944040/b4bf7db2-a853-11e5-9036-a54ede1e8604.png)

Expected behaviour: show the 'Extensions: Install Extension' item in the list or suggest to install an extension.
Actual behaviour: empty list or the only one 'Extensions: Show Installed Extensions' item.
***

OS: Arch Linux, 64-bit

**Comment by bpasero** [comment]
The extension feature is only enabled in Microsoft VS Code builds. @egamma I think you documented distributions somewhere?

**Comment by bgse** [comment]
@bpasero Is this restriction set in stone, or is there a possibility that it might be reviewed at some point?

I'm asking since I can see having vscode readily available across the many different Linux distributions being a lot easier if it is left to the distributor to simply ship the OSS build from their repos, but still in such a case I'd prefer extensions coming from the official marketplace and not making distributing extensions overly complicated where we have to upload our extensions to many different places.

**Comment by egamma** [comment]
@bgse more [background](https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005) on this topic.

CC @chrisdias

**Comment by rezonant** [comment]
Could one simply configure their product.json to point to the official extension repositories? Is that allowed? In the analog of Chrome/Chromium, referenced in the split license issue by @chrisdias, Chromium is allowed to install Chrome Web Store extensions. Also, the actual README.md of the vscode repository includes a screenshot of the extension installer UI via F1, so if that's not allowed, I'd recommend the screenshot be changed to show a feature which is available when the repository is actually built.

**Comment by chrisdias** [comment]
@rezonant yes, you can configure product.json to point to the official marketplace. look in the product.json that is installed with the visual studio code distro for the url.
