### ISSUE TITLE
Allow to compare untitled documents

### ISSUE THREAD

**Issue by 802Tophat** [microsoft/vscode#155773]
Previous fulfilled task - Allow to compare untitled documents #14501

Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.5.0

Allow two untitled and unsaved files to be compared for quick comparisons on data without having to save files.

Steps to Reproduce:

1. Create new file
2. Create new file again
3. Context menu doesnt show options to compare

<img width="1025" alt="Screen Shot 2022-07-20 at 2 46 14 PM" src="https://user-images.githubusercontent.com/17958149/180059178-f0ad3480-0802-406a-8bc6-62ada2dca390.png">

**Comment by lramos15** [comment]
This is already implemented you need the open editors view open though. This can be access via `CMD + K` followed by the `E` key
