### ISSUE TITLE
Ability to force close unsaved files

### ISSUE THREAD

**Issue by kodiriys** [microsoft/vscode#155769]
Can we have a shortcut to close a modified or an unsaved file without being prompted "Do you want to save"? In this case, I do not want to save if I am closing a file that I did not already save (I always use Ctrl+S, never the UI). Something like Ctrl+Alt+W...

This is especially useful when working with tens of SQL autogenerated queries that are one-offs.

**Comment by bpasero** [comment]
`workbench.action.revertAndCloseActiveEditor`
