### ISSUE TITLE
TSX file with custom jsxFactory

### ISSUE THREAD

**Issue by tomburger** [microsoft/vscode#155709]
Issue Type: <b>Bug</b>

We are using TSX files with our own custom jsx factory, set in tsconfig.json file. TSX files do compile fine using TSC.
VS Code started recently to report use of HTML in TSX files as error saying "Cannot find name 'React'. ts(2304)", however we are not using React, but our own custom rendering function, which is properly imported into the TSX file.
How can we tweak VS Code syntax check for TSX file to accept custom jsxFactory?

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.69GB (31.89GB free)|
|Process Argv|--crash-reporter-id 2b0a21cb-e7f9-432a-8779-69128417ccc1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.47.0
gitlens|eam|12.1.2
vscode-npm-script|eg2|0.3.28
gc-excelviewer|Gra|4.2.55
vscode-jasmine-test-adapter|hbe|1.8.1
vscode-test-explorer|hbe|2.21.1
vscode-edit-csv|jan|0.7.1
Kotlin|mat|1.7.1
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.4
vscode-azurestaticwebapps|ms-|0.11.2
vscode-azurestorage|ms-|0.14.2
csharp|ms-|1.25.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.30
jupyter|ms-|2022.6.1201981810
azure-account|ms-|0.11.0
cpptools|ms-|1.10.8
powershell|ms-|2022.6.3
test-adapter-converter|ms-|0.1.6
cordova-tools|msj|2.4.1
LiveServer|rit|5.7.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30525688
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912:30529769
vsclangdf:30486550

```

</details>

**Comment by mjbvz** [comment]
Are the files part of the correct project. Run `TypeScript: Go to project configuration` in them to check

**Comment by mjbvz** [comment]
Thanks for checking

Currently you need a file called `tsconfig.json` exactly for the tooling to pick it up. However this file can extend one of your existing tsconfigs

Related: https://github.com/microsoft/vscode-webview-ui-toolkit
