### ISSUE TITLE
Cannot view or create a file with scf extension in VSCode Web

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#155704]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69 (Web)
- OS Version: MacOS

Issue:

We have a workspace containing scatterfiles which are text based embedded source files. These use the extension `scf`.
These can be opened and edited in VS Code desktop, but using the web version (ie vscode.dev), the files do not appear in the explorer.
Furthermore it's not possible to create a new file in vscode.dev with this extension, a `name is not allowed` error appears.

Steps to Reproduce:

1. Open a folder in vscode.dev
2. Try to create a new file with the extension `scf`
3. Observe an error message:

<img width="469" alt="Screenshot 2022-07-20 at 09 46 52" src="https://user-images.githubusercontent.com/61341/179939414-a5db1b03-ec6c-4d66-82a8-739993e7ce31.png">

I have confirmed this works as expected on github.dev, so could be an issue with the web file system API

**Comment by bpasero** [comment]
Probably not allowed by the file system. See also https://www.bleepingcomputer.com/news/security/you-can-steal-windows-login-credentials-via-google-chrome-and-scf-files/

**Comment by thegecko** [comment]
Probably not allowed by the file system. See also https://www.bleepingcomputer.com/news/security/you-can-steal-windows-login-credentials-via-google-chrome-and-scf-files/

Agreed, this seems to be a limitation to the FileSystem API. Will see if we can rename these source files...
