### ISSUE TITLE
getting two windows of the workbench after running tests

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15571]
(don't have hot exit enabled)
* run `scripts/code.sh` have only one window open
* run `scripts/test-integration`
* run `scripts/code.sh` again
* 🐛 it now opens two windows - the test workspace and the formerly used one

**Comment by bpasero** [comment]
@Tyriar I can reproduce and I can see the following in the Backups folder after the integration tests are done:

![image](https://cloud.githubusercontent.com/assets/900690/20352912/5f5f22ee-ac19-11e6-9985-07a2b7e60b7a.png)

**Comment by Tyriar** [comment]
Looking into it now

**Comment by Tyriar** [comment]
With hot exit enabled:

```
❯ cat ~/.config/code-oss-dev/Backups/workspaces.json
{"folderWorkspaces":["/home/daimms/dev/Microsoft/vscode/extensions/vscode-api-tests/testWorkspace"]}

❯ cat ~/.config/code-oss-dev/Backups/5897f59d46ccbac8e742f844597d7484/file/735e24620b763a3e27a4579f428e6d1b 
hello world!
```

Without:

```
❯ cat ~/.config/code-oss-dev/Backups/workspaces.json 
{"folderWorkspaces":["/home/daimms/dev/Microsoft/vscode/extensions/vscode-api-tests/testWorkspace"]}

❯ ls ~/.config/code-oss-dev/Backups/
workspaces.json
```

The results seem to vary somewhat. For the first case (when hot exit is enabled) we should probably just disable backups all together (hot exit and crash recovery) when an extension is being run/debugged.

The second case would be fixed if we did an additional check and cleaned up paths in workspaces.json (#15499) which I'm leaning more towards now.

**Comment by bpasero** [comment]
@Tyriar just to clarify, even when hot exit is disabled you backup for each modification of a file and will restore it even when hot exit is disabled?
