### ISSUE TITLE
Fuzzy score shouldn't boost lower-case match over upper-case match

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#155757]
* have the sample below
* invoke suggest -> `Cluster` is before `cluster`
* type `c` 
* 😕 the order changes

```js
let a = {
    cluster: 1,
    Cluster:2,
}

a. // type `c`
```

https://user-images.githubusercontent.com/1794099/180031628-2fb2d14b-1416-4a38-a2f4-dcda4456a2f2.mov

**Comment by d3chapma** [comment]
@jrieken I'm interested in taking a look at this issue. However, I'm surprised this is actually a desired change. The behaviour displayed in the video feels correct to me. Why do you prefer to not have case influence the fuzzy score?

**Comment by jrieken** [comment]
I gave this a try and I am now sharing @d3chapma concerns - there are cases in which this is favourable but also contradicting cases, like `lines` should match better on `linesCollection` than on `lineStarts`. 

I will abandon this but the good news is that extensions have control over this via case-normalized `filterText`-properties and via the `sortText`-property
