### ISSUE TITLE
Ship bash/zsh completions on macOS and automatically activate them when shell integration is enabled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155733]
Context: https://github.com/microsoft/vscode-docs/issues/5482

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/154662

**Comment by meganrogge** [comment]
duplicate of #226562?

**Comment by Tyriar** [comment]
Using the approach in #226562 instead 👍 

/duplicate
