### ISSUE TITLE
Very high CPU + memory usage by "watcherService" service process + possible cause

### ISSUE THREAD

**Issue by iivvoo** [Microsoft/vscode#15572]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04.1 64bit

There have been some (unresolved) reports about high CPU load: #14222 #10439

I'm experiencing a similar high load on Ubuntu. It's always the "--type=watcherService" process. It even happens with --extensions-disabled

top output:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND     
29275 ivo       20   0 2546512 1,579g  33836 R 115,3 10,1   2:36.30 code  
```

ps output:
```
ivo      29275  115 10.1 2588532 1667120 ?     Rl   16:40   3:06 /usr/share/code/code /usr/share/code/resources/app/out/bootstrap --type=watcherService
```

When `strace`-ing the process I noticed the following output:

```
(lots of)
futex(0x7f7c4ef2c9e0, FUTEX_WAKE_PRIVATE, 1) = 1
futex(0x7f7c4ef2ca0c, FUTEX_WAKE_OP_PRIVATE, 1, 1, 0x7f7c4ef2ca08, {FUTEX_OP_SET, 0, FUTEX_OP_CMP_GT, 1}) = 1
futex(0x7f7c4ef2c9e0, FUTEX_WAKE_PRIVATE, 1) = 1
(and then)
inotify_add_watch(35, "/home/ivo/m3r/projects/Guts/viscera/tmp/broccoli_merge_trees-output_path-rsLThmVz.tmp/modules/ember-getowner-polyfill", IN_MODIFY|IN_ATTRIB|IN_MOVED_FROM|IN_MOVED_TO|IN_CREATE|IN_DELETE|IN_DELETE_SELF|IN_MOVE_SELF) = 68357
```

Specifically the `inotify_add_watch` on some file in tmp/ which was loaded with (old) files caught my attention. There's no need to watch these files and watching all of them could very well cause the problem.

After removing tmp/ entirely the problem disappeared. After filling tmp/ again with about 20 copies of itself (resulting in appr. 400.000 files), the problem reappeared. And after removing the issue is gone again.

This happens even with 

```
    "files.exclude": {
        "tmp/": true
    }
```

Conclusion: could it be the watcherService ignores `files.exclude` and tmp/ folders in general and will happily attempt to monitor 400K+ files?

**Comment by bpasero** [comment]
@iivvoo yes, you should use "`files.watcherExclude"`

**Comment by iivvoo** [comment]
Why would you (still) want to watch files that are in `files.exclude`? In other words, why is this a separate setting and/or doesn't it default to `files.exclude`?

**Comment by bpasero** [comment]
@iivvoo this is a risky thing to take out files from watching. there could be extensions relying on the fact that events are being sent for certain folders. By making it a very explicit thing to configure, it reduces this risk.

As for Linux, we need a better watching mechanism that does not run into this issue.

**Comment by bpasero** [comment]
Merging into https://github.com/Microsoft/vscode/issues/3998
