### ISSUE TITLE
Test: Electron sandbox

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155827]
Refs: #154006

- [x] macOS @mjbvz
- [x] linux @lramos15
- [x] windows @benibenj

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23155827%0A%0A&assignees=bpasero)

---

For the sandbox testing, make sure to configure `"window.experimental.useSandbox": true` and restart. You can check devtools for when sandbox is really enabled:

![image](https://user-images.githubusercontent.com/900690/180170193-bd2059d7-1fc3-4ed2-b4ee-a7c98b4f5c5d.png)

This is an exploratory test plan item while running with sandbox enabled.

**Note:** keep the setting also enabled in your selfhost build for broader coverage 🚀  

**Functionality**
* open files and folders and do basic editing, including language features and watch the Developer Tools console for suspicious errors or general issues while doing so
* go through all our views and panels and check they open and work for the intent they are made for
* also try non standard editors like a notebook and a custom editor for they work fine
* open multiple windows, close some and verify you always have 1 extension host process per window (use the Help > Open Process Explorer to find the processes)
* develop a simple hello world extension (`yo code`) and verify debugging and extension tests work 
* watch out for actions that seem slow or cause spinners to appear, overall VSCode should not run any noticeably slower when sandbox is enabled but it will have a slight performance impact because of process isolation
* briefly test that screen reader works and announces the focused element properly ([documentation](https://code.visualstudio.com/docs/editor/accessibility#_screen-readers))
* _macOS/Windows_: run VSCode as admin with a fresh `--user-data-dir` and verify the window opens and generally it works without crashes

**Development**
* use Developer Tools for setting a breakpoint and verify you can debug VSCode insiders as before
* similar, run a performance trace and verify it works and it can be displayed in Developer Tols

**Comment by mjbvz** [comment]
Amazing work! I went through the test plan and have also been running with this setting enabled for a few days. Works great

One question: when I tried to profile my extensions using the `running extensions` view, I saw a notification that a restart was required. Is this new? I feel like I have not seen it before enabling the sandbox flag

**Comment by bpasero** [comment]
@mjbvz thanks, you probably saw https://github.com/microsoft/vscode/issues/155987
