### ISSUE TITLE
Task Quick Pick

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155802]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178862&view=logs&j=e5bbec05-0f06-558d-ebe9-5973d52063d2&t=a671546b-2469-5fb1-b2c9-08e628dcad6d&l=129

```
1) VSCode Smoke Tests (Web)
       Task
         Task Quick Pick
           "after each" hook for "hide property - undefined":
     Error: Timeout: get elements '#terminal .terminal-wrapper' after 20 seconds.
      at Code.poll (/__w/1/s/test/automation/src/code.ts:256:11)
      at Code.waitForElements (/__w/1/s/test/automation/src/code.ts:205:10)
      at Terminal.runCommand (/__w/1/s/test/automation/src/terminal.ts:96:5)
      at Context.<anonymous> (src/areas/task/task-quick-pick.test.ts:23:4)
```

**Comment by bpasero** [comment]
Similar https://github.com/microsoft/vscode/issues/155573, maybe the new tasks smoke tests are flaky.

**Comment by lszomoru** [comment]
Another failed pipeline - https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178883&view=logs&j=4801dce2-64f3-53d6-b366-d49a1977c639&t=525606ab-8bc1-59bd-2d29-e98f94fa71fe

**Comment by Tyriar** [comment]
Same failure just a different target

/duplicate https://github.com/microsoft/vscode/issues/155573
