### ISSUE TITLE
Diff indication for wrapped lines should only show in last line

### ISSUE THREAD

**Issue by octref** [Microsoft/vscode#15581]
- VSCode Version: 1.8 Insiders
- OS Version: OS X 10.11.6

Diff:

![image](https://cloud.githubusercontent.com/assets/4033249/20361377/357fcbc2-abec-11e6-8f90-a5bf51b55a76.png)

Editor:

![image](https://cloud.githubusercontent.com/assets/4033249/20361390/3eeb9f38-abec-11e6-830b-b61d244453bb.png)

**Comment by joaomoreno** [comment]
Oh great catch!

**Comment by alexandrudima** [comment]
Well, the new lines (the green bar) I think would like to get the full range of the text. @joaomoreno have you tried adding the deleted decoration to only a subset of the line range (i.e. column 1-> column 2) (or without using isWholeLine?)

**Comment by joaomoreno** [comment]
Actually, on the other hand, here's the outcome of using `isWholeLine: false`:

![screenshot from 2018-09-19 09-43-22](https://user-images.githubusercontent.com/22350/45738373-8607bf80-bbf0-11e8-8173-61e16d1a2371.png)

It is still not ideal, since the twistie should be rendered on the last wrapped line. Any thoughts @alexandrudima?

**Comment by alexandrudima** [comment]
@joaomoreno This depends on your range. If the range is from column 1 to column 2, then the model range is transformed to a view range and rendered in the gutter area corresponding to that view range.

Perhaps you can place the decorator on the last character in the line?

**Comment by joaomoreno** [comment]
Love it! I'm using `Number.MAX_VALUE` instead of checking for the line's length, works pretty well.

**Comment by alexandrudima** [comment]
To avoid doubles, I always use `Constants.MAX_SAFE_SMALL_INTEGER` which is kinda large even though it's called small integer.
