### ISSUE TITLE
variables resolution in windows: normalized or not normalized?

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#155883]
Sorry for asking questions in the issue tracker.

Reading https://github.com/microsoft/vscode/issues/100875#issuecomment-648657817
> yes, by design we are normalizing drive letters. More about why we do this can be found in this and the related issues #43959

I originally assumed vscode was normalizing the drive letter casing. 
`normalizeDriveLetter` uses upper case drive letter.

https://github.com/microsoft/vscode/blob/f17b33faf21feba942e4663e40226456b081ae5d/src/vs/base/common/labels.ts#L143

However, I noticed that variables like `${file}`, `${fileDirname}`, `${workspaceFolderBasename}` on my Windows 
are resolved to file paths with lower case drive name, e.g. `c:\Users\me\code\foo.go`. 

`nomarlizeDriveLetter` is not consistently applied from this part of the code but I am not sure if they are supposed to be handled elsewhere.

https://github.com/microsoft/vscode/blob/f17b33faf21feba942e4663e40226456b081ae5d/src/vs/workbench/services/configurationResolver/common/variableResolver.ts#L284-L378

Is there a documentation on what is normalized or not normalized, and if normalized, it will be upper case or lower case.
(It's not clear to me what's the final conclusion of length discussions like https://github.com/microsoft/vscode/issues/43959) 

And, for debugging requests, can we assume all requests that carry the absolute file paths use normalized file path?

**Comment by hyangah** [comment]
Another fun finding is, `URI.file` normalizes the drive casing to lower-case

https://github.com/microsoft/vscode/blob/dce493cb6e36346ef2714e82c42ce14fc461b15c/src/vs/base/common/uri.ts#L595

As a result, our extension ends up _normalizing_ a path to use upper case drive letter, converting it to URI.file which uses lower-case in fsPath, and at some point, translating fsPath to upper case, ...

**Comment by roblourens** [comment]
I think the conclusion is that we should try to be consistent with URIs coming from vscode, but remember that we can't control the whole environment- e.g. the runtime may do something different than URIs that come from DAP.

I don't know  why `file` would have a different drive letter case than `workspaceRoot`. Seems wrong. Do you know anything about that @alexr00?

**Comment by alexr00** [comment]
I think it's just an oversight that the drive letter isn't always normalized. I'm happy to make this change during the next debt week so that it has plenty of time in insiders for folks to notice if it breaks anything.
