### ISSUE TITLE
Linux: process.pid is invalid in sandboxed renderer

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#155810]
Refs https://github.com/microsoft/vscode/issues/154235#issuecomment-1190340760

**Comment by bpasero** [comment]
To clarify: we can also just drop `process.pid` from the set of supported sandbox globals. The extension host maybe the only user and its not needed once we fully enable sandbox.

**Comment by deepak1556** [comment]
Electron mocks the property for sandboxed renderers https://github.com/electron/electron/blob/main/shell/renderer/electron_sandboxed_renderer_client.cc#L147, the Chromium api eventually calls `getpid` and this syscall is allowed from sandboxed renderer process https://source.chromium.org/chromium/chromium/src/+/main:sandbox/linux/seccomp-bpf-helpers/syscall_sets.cc;l=262-285.

A bit more closer look at the sandbox code, shows that chromium spawns renderer with `CLONE_NEWPID` flag with both namespace sandbox as well as the setuid sandbox. This actually causes the process to be hosted in a new namespace https://man7.org/linux/man-pages/man7/pid_namespaces.7.html and if it is the first process of the namespace then a pid value of `1` will be assigned to it. Electron should first try read pid from the namespace similar to https://source.chromium.org/chromium/chromium/src/+/main:base/process/process_linux.cc;l=257-294 and only if it fails fallback to calling `getpid`. I will get this fixed in upstream.

**Comment by deepak1556** [comment]
This requires reading NSpid from `/proc/self/status` from sandboxed renderer process which cannot happen. Closing as won't fix.

https://lwn.net/Articles/602987/ could have helped, but didn't make it into the kernel.
