### ISSUE TITLE
Insiders Settings Profiles: Profiles to not persist layout settings

### ISSUE THREAD

**Issue by weaversam8** [microsoft/vscode#155881]
When switching profiles using the new experimental Settings Profiles feature ([background blog post](https://code.visualstudio.com/updates/v1_69#_settings-profiles), background issue: #116740), layout specific settings (like which sidebars are open) are not preserved.

View customizations _are_ preserved, which is ideal, since a user can choose to move the views from the primary sidebar to the secondary sidebar, but if a user _isn't using_ the secondary sidebar in one profile but is in another, the "open/closed" state of that sidebar isn't preserved as of now.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0-insider (Universal)
- Commit: 62469028a6dce9db5b7c4639be7f447f4ab0e35c
- Date: 2022-07-21T05:17:20.056Z
- Electron: 18.3.5
- Chromium: 100.0.4896.160
- Node.js: 16.13.2
- V8: 10.0.139.17-electron.0
- OS: Darwin arm64 21.2.0

Steps to Reproduce:

1. Open an install of VS Code Insiders
2. Enable the experimental Settings Profiles feature
3. Create a settings profile using `Settings Profiles: Create an Empty Settings Profile...`
4. Switch to that profile (this should happen automatically)
5. Customize the layout in a nonstandard way. The easiest way to do this is to click the `Toggle Secondary Side Bar` button in the upper-right hand corner of the window.
6. Switch back to the default profile. Your layout customizations will not return to default.

**Comment by sandy081** [comment]
It is as per design now. Open/collapsed state of an view is workspace specific and hence is not stored in profile.
