### ISSUE TITLE
Notebook API tests

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155825]
```
1 failing
  1) Notebook API tests
       edit API batch edits undo/redo:
     Error: asPromise TIMEOUT reached
      at Timeout._onTimeout (extensions/vscode-api-tests/src/utils.ts:132:11)
      at listOnTimeout (node:internal/timers:557:17)
      at processTimers (node:internal/timers:500:7)

```

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178904&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=2f009c1d-81d8-5a7e-ba44-a6542d1f1704&l=641

**Comment by rebornix** [comment]
Can be related to https://github.com/microsoft/vscode/issues/155587

**Comment by rebornix** [comment]
It's due to the same `asPromise` wrapper for `NotebookDocumentChange` event, let's merge it into https://github.com/microsoft/vscode/issues/155587
