### ISSUE TITLE
Regular expression multiple cursors bug

### ISSUE THREAD

**Issue by crayment** [Microsoft/vscode#15580]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|calc|BorisA|0.0.1|
|MyExtensions|none|0.0.1|
|erb|CraigMaslowski|0.0.1|
|swift|Kasik96|0.0.2|
|calculate|acarreiro|1.1.0|
|githistory|donjayamanne|0.1.0|
|prettify-json|mohsen1|0.0.3|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|Ruby|rebornix|0.10.1|
|move-fast|selbh|0.1.0|
|swiftlint|shinnn|0.1.3|

---

Steps to Reproduce:

1. Open a new file and type `112233445566` into it.
2. Open the find dialog and enable regex search.
3. Type `\d\d` into the search box.
4. Notice there is correctly 6 matches and hitting enter cycles through them.
5. Hit option+enter with the intention of placing 6 cursors - one on each match: `11`, `22`, `33`, `44`, `55`, `66`
6. Notice you only get 3 cursors - one on `1122` one on `3344` and one on `5566`

![image 2016-11-16 at 10 55 21 am](https://cloud.githubusercontent.com/assets/78082/20359088/8df9a8aa-abeb-11e6-903a-259d042737d1.png)

**Comment by alexandrudima** [comment]
Dup of #11150
