### ISSUE TITLE
StreamDebugAdapter (NamedPipeDebugAdapter) can initialize a connection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155801]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=178847&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=0beb721c-bc23-58b2-a0a2-2fceaa3e6b2b&l=9776

```
1) Debug - StreamDebugAdapter
       StreamDebugAdapter (NamedPipeDebugAdapter) can initialize a connection:

      
      + expected - actual
```

**Comment by bpasero** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=181793&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=65769c9f-3383-5c2e-eedc-910df4a0c5f1&l=9824

**Comment by connor4312** [comment]
Please ping me if this failure is seen again, as I've added additional debug information which may be helpful

**Comment by connor4312** [comment]
This does not seem to have happened recently, please reopen if encountered.
