### ISSUE TITLE
Powerlevel10k dotted lines colors are all the same

### ISSUE THREAD

**Issue by felipecrs** [microsoft/vscode#155843]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: Windows 11 22H2

Windows Terminal:

![image](https://user-images.githubusercontent.com/29582865/180217709-7cad8e51-1d39-4c8f-b909-066f83fde0e9.png)

VS Code:

![image](https://user-images.githubusercontent.com/29582865/180217728-9cae7478-994d-464d-a7e3-74e4cd5aea07.png)

Steps to Reproduce:

1. Have a Powerlevel10k shell
2. Run `p10k configure` as in the demo below:

https://user-images.githubusercontent.com/29582865/180217454-e61e4003-7e21-42b0-9db6-a4f7e4ee8336.mp4

**Comment by Tyriar** [comment]
This is working fine for me now:

![Image](https://user-images.githubusercontent.com/2193314/206476755-491ea5d7-da6a-43d2-8f6e-9b8fa6c6bf2f.png)

FWIW it looks like the change is meant to be pretty subtle based on what colors they chose.
