### ISSUE TITLE
Focus goes to bottom of list on search replace

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#155879]
When replacing the last match in a file, the focus jumps to the end of the file.

Steps to Reproduce:

1. Select a match that is the last in a file.
2. Focus jumps to the end of the file instead of jumping to the next file. :bug:

[![Image from Gyazo](https://i.gyazo.com/34dcb9fd0a75f9ed474293d3ee875529.gif)](https://gyazo.com/34dcb9fd0a75f9ed474293d3ee875529)

It should act like remove, which does this:
[![Image from Gyazo](https://i.gyazo.com/8034d9aa284af95027997caa3a181264.gif)](https://gyazo.com/8034d9aa284af95027997caa3a181264)

I suspect that it is because of the code [here](https://github.com/microsoft/vscode/blob/fe5f1aef61160d49b6bc97f34c430aa020c6d789/src/vs/workbench/contrib/search/browser/searchActions.ts#L571), which was originally written 6 years ago and seems to have a bug.

**Comment by meganrogge** [comment]
maybe i'm missing something, but in trying to test this, I don't see the search results showing both matches 🤔 

<img width="1678" alt="Screen Shot 2022-10-26 at 4 27 03 PM" src="https://user-images.githubusercontent.com/29464607/198130160-8ea22ea0-7b2a-41b2-93f4-394632eaa2b0.png">

**Comment by meganrogge** [comment]
I clicked `enable` and then it found all matches... though not sure why as `terminalProfileQuickPick.ts` should not be ignored

**Comment by meganrogge** [comment]
verified that this particular bug is fixed though 👏🏼

**Comment by andreamah** [comment]
> I clicked `enable` and then it found all matches... though not sure why as `terminalProfileQuickPick.ts` should not be ignored



> `terminalProfileQuickPick.ts`

Did you press enter on the searchbox to manually search again after adding the string to the unsaved file? We won't be automatically refreshing/rerunning the search for changes in files that didn't previously have a match. I think what might have happened was that enabling the setting caused a search to run and catch the new changes on the dirty file.
