### ISSUE TITLE
Test: Merge editor CLI support

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#155819]
Refs: #5770

- [x] anyOS @misolori
- [x] anyOS @aiday-mar

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23155819%0A%0A&assignees=bpasero)

---

A new command line flag `--merge` was added to bring up a merge editor. Verify it works as you would expect.

You can see https://github.com/microsoft/vscode/issues/5770#issuecomment-1188658476 for help how to configure Git to use the merge editor.

**Comment by doggy8088** [comment]
It's not working. Here are steps I do.

1. edit `.gitconfig` file

    ```sh
    git config --global --edit
    ```

    ```ini
    [merge]
        tool = code
    [mergetool]
        writeToTemp = true
        keepBackup = false
    [mergetool "code"]
        cmd = code --wait --merge $REMOTE $LOCAL $BASE $MERGED
    ```

2. Execute `git mergetool`

3. VSCode show up but opened 3 tabs.

    ![image](https://user-images.githubusercontent.com/88981/181156750-7e643b75-0950-457f-befa-2e5f2a60aa78.png)

---

```log
Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```
