### ISSUE TITLE
Contents in "variables in devcontainer.json" section - spelling mistake

### ISSUE THREAD

**Issue by jjpinto** [microsoft/vscode#155864]
Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:
The documentation has a spelling mistake

LINK: https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_variables-in-devcontainerjson
-> Value of an environment variable on the host machine (in this case, called VARIABLE_NAME). Unset variables are left blank. **To for** example, this would set a variable to your local home folder on Linux / macOS or the user folder on Windows:

**Comment by Mariangela** [comment]
@chrmarti , can you please point me to the GitHub page that corresponds to this page.

**Comment by chrmarti** [comment]
Thanks for pointing this out. @bamurtaugh It looks like we fixed the typo (https://github.com/devcontainers/spec/commit/69d6e736c8ce08109c4fd87bbdbb27561d489a15) but have not yet deployed the latest changes.

**Comment by bamurtaugh** [comment]
Thanks for looping me in! Opened a PR in https://github.com/devcontainers/devcontainers.github.io/pull/61.

@Mariangela https://github.com/devcontainers/devcontainers.github.io is the repo for https://containers.dev/.
