### ISSUE TITLE
Test: Settings editor application-scoped settings with Settings profiles

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#155899]
Refs: https://github.com/microsoft/vscode/issues/152888

- [x] anyOS @paulacamargo25
- [x] anyOS @alexr00

Complexity: 4

Authors: @rzhao271, @sandy081

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23155899%0A%0A&assignees=rzhao271,sandy081)

---

There's a lot of text, but most of the steps are short.

1. Enable the experimental Settings profiles feature.
2. Create another profile so that you don't only have a default profile.
3. Navigate to the GUI Settings editor.
4. Navigate to an application-scoped setting such as `update.showReleaseNotes`. It should have an indicator that indicates that the setting applies to all profiles.
5. Verify that the indicator text, custom hover text, and screenreader text for it make sense. Note that this indicator should only show up when the Settings profile feature is enabled.

While on the default profile:
1. Verify that the command palette has a command to open the user settings JSON but no command to open the current profile settings JSON.
2. In the GUI Settings editor, there is an icon in the top-right corner that switches between the GUI Settings editor and JSON Settings editor. 
3. While on the User tab, clicking on that icon should bring the user to the user settings JSON. 
4. While on the Workspace tab (there needs to be a workspace open), clicking on that icon should bring the user to the workspace settings JSON.

While not on the default profile:
1. Verify that the command palette has commands to open the user settings JSON and the current profile settings JSON.
2. In the GUI Settings editor, there is an icon in the top-right corner that switches between the GUI Settings editor and JSON Settings editor. 
3. While on the User tab, clicking on that icon should bring up a menu that allows the user to navigate to either the user settings JSON or the current profile settings JSON.
4. The user settings JSON file allows the user to modify application-scoped settings. Other settings should be greyed out with a hint saying that they don't apply while the user is in a non-default profile. 
5. The current profile settings JSON file allows the user to modify non-application-scoped settings. Attempting to modify an application-scoped setting such as `update.enableWindowsBackgroundUpdates` should result in a greyed-out setting with a hint saying that the setting cannot be set in that file.
6. While on the Workspace tab (there needs to be a workspace open), clicking on that icon should bring the user to the workspace settings JSON.

Other things to consider:
1. Are there glitches when navigating between the default profile and the non-default profile with respect to the GUI and JSON Settings editors?
2. Are there glitches when navigating between two non-default profiles with respect to the GUI and JSON Settings editors?

**Comment by paulacamargo25** [comment]
Everything works fine, great job!
