### ISSUE TITLE
Expose a terminal API option to pause when the shell is exited

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15583]
This is a requirement for the tasks framework to be moved to using the integrated terminal. The idea is to allow extensions to optionally specify they don't want the terminal to go away immediately after the shell process is exited but instead wait for input.

This would allow the tasks framework (and other extensions) to run a command that exits the shell immediately afterwards, and then wait for a keystroke or for the terminal to be killed manually, for example:

```
gulp build
...
...

Press and key to close the terminal...
```

Proposed API:

```ts
export function createTerminal(name?: string, shellPath?: string, shellArgs?: string[], waitOnExit?: boolean): Terminal;
```

/cc @jrieken @dbaeumer

**Comment by jrieken** [comment]
We might have reached a point where it makes sense to talk about a second overload with an options bag. Like

```ts
export function createTerminal(name?: string, shellPath?: string, shellArgs?: string[]): Terminal;

export function createTerminal(options: {name?: string; shellPath?: string; shellArgs?: string[]; waitOnExit?: boolean }): Terminal;
```

**Comment by Tyriar** [comment]
Upstream issue to implement disableStdin (prereq) https://github.com/sourcelair/xterm.js/issues/452

**Comment by Tyriar** [comment]
Upstream PR is merged in

**Comment by Tyriar** [comment]
PR that exposes the new `waitOnExit` option to API: https://github.com/Microsoft/vscode/pull/18336
Example usage: https://github.com/Microsoft/vscode-extension-samples/commit/9b46d6b7943ca2700c80d2d74ace794d30a8d25d

**Comment by Tyriar** [comment]
@dbaeumer FYI currently if a waitOnExit shell exits with a non-0 code I print the message that would normally go in the message box inside the terminal:

![image](https://cloud.githubusercontent.com/assets/2193314/21781026/9473f3d8-d662-11e6-977c-933d1034ccda.png)

**Comment by Tyriar** [comment]
FYI @dbaeumer @jrieken I've pulled the `waitOnExit` option out of the API for now as it might become an enum (see https://github.com/Microsoft/vscode/issues/18661). I've left `TerminalOptions` in as it will come later anyhow.

**Comment by Tyriar** [comment]
No longer needed (yet), closing off.

**Comment by jrieken** [comment]
I hope we still have use for `TerminalOptions`...

**Comment by Tyriar** [comment]
@jrieken the hope is still to move tasks to an extension, it's not the priority now though. A lot of the stuff that tasks need would be great for extensions to be able to hook into eventually as well, now we're just not rushed in pushing the APIs out. Some things that I can see us adding soon:

- A more focused `waitOnExit` after we've received more feedback from tasks
- Ability to set the terminal environment
