### ISSUE TITLE
Code action menu stays fixed on scroll

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#155890]
Type: <b>Bug</b>

1. Using `Using editor.experimental.useCustomCodeActionMenu`
2. Open menu
3. Scroll the editor

**Bug**
The menu remains fixed in screen space. Here I triggered using the lightbulb and then scrolled 

<img width="499" alt="Screen Shot 2022-07-21 at 1 17 40 PM" src="https://user-images.githubusercontent.com/12821956/180307854-d364a1a8-3187-4d5f-b3ae-9530666c419b.png">

I suggest that it should either:

- Stay fixed where it was triggered, similar to the suggest widget
- Prevent editor scrolling, like MacOS native context menus

VS Code version: Code - Insiders 1.70.0-insider (Universal) (62469028a6dce9db5b7c4639be7f447f4ab0e35c, 2022-07-21T05:17:20.056Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.70GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by justschen** [comment]
I think this might be the intended behavior - although we _could_ choose to close the widget when the scroll happens which may make more sense.

![Recording 2022-07-21 at 15 22 55](https://user-images.githubusercontent.com/54879025/180327196-836cab54-f59f-4978-9f43-caaedb313dbd.gif)
