### ISSUE TITLE
Branch protection not enabled if you open a subfolder of git repo

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#155897]
Type: <b>Bug</b>

1. For a repo with a branch protection (such as the vscode repo)
2. Open a subfolder of the repo as your workspace

**Bug**
Branch protection doesn't apply

I understand this happens because the `git.branchProtection` workspace settings are not picked up from the parent folder, but it still feels unexpected

VS Code version: Code - Insiders 1.70.0-insider (Universal) (62469028a6dce9db5b7c4639be7f447f4ab0e35c, 2022-07-21T05:17:20.056Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lszomoru** [comment]
While this is indeed annoying, my understanding is that VS Code core does not have the possibility to expose the workspace setting when a subfolder of the workspace is being opened. I will close this issue for now, but I will continue to explore options to see if this is something that we can improve upon.
