### ISSUE TITLE
Two divisions in the same line tricks the code highlighting into thinking there's a regex.

### ISSUE THREAD

**Issue by coreyog** [Microsoft/vscode#15582]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.2|
|Go|lukehoban|0.6.49|
|debugger-for-chrome|msjsdiag|2.2.2|
|vscode-icons|robertohuertasm|4.0.1|
|code-settings-sync|Shan|2.3.8|

---

Steps to Reproduce:

1. I have a TypeScript file containing the following code:

```
  lngLatToXY(b: number, c: number): number[] {
    var u = 0.017453292519943;
    var a = 6378137;
    var d = c * u;
    return [b * u * a, a / 2 * Math.log((1 + Math.sin(d)) / (1 - Math.sin(d)))];
  }

  xyToLngLat(b: number, c: number, d?: number): number[] {
    var a = 6378137;
    var l = 57.29577951308232;
    var e = 3.141592653589793;
    b = b / a * l;
    if (d) {
      c = e / 2 - 2 * Math.atan(Math.exp(-1 * c / a));
      return [b, c * l];
    }
    d = b - 360 * Math.floor((b + 180) / 360);
    c = e / 2 - 2 * Math.atan(Math.exp(-1 * c / a));
    return [d, c * l];
  }
```

2. Note that the return statement in lngLatToXY contains two divisions. This seems to trigger the highlighting for regular expressions and it looks like this:

![regex-highlight](https://cloud.githubusercontent.com/assets/2836207/20361314/677ff0b8-abf4-11e6-96e6-9644755fcf15.png)

Because of the parentheses that are used in the math operations (note that 3 are opened but only 2 are closed between the two /) the regex highlighter thinks the regex continues on to the next line across many lines until it reaches the next / in the next function. Although it's not valid TS, if I close the paren the style then stops at the second / like so:

![regex-highlight-fix-not-a-fix](https://cloud.githubusercontent.com/assets/2836207/20361318/6c0187b4-abf4-11e6-9fd4-da5184317921.png)

This is not a regex and should not be colored as one.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#358
