### ISSUE TITLE
"Go to file" when one name is a subset of another

### ISSUE THREAD

**Issue by andy-ms** [Microsoft/vscode#15589]
- VSCode Version: 1.7.1
- OS Version: Linux Mint 18

Steps to Reproduce:

1. Create `abc.txt`, `alpha-beta-cappa.txt`, `xyz/index.js`, and `xerxes-yak-zubba/index.js`.
2. Hit Ctrl-P, type "abc", and hit enter. This opens `abc.txt`.
3. Hit Ctrl-P, type "xyz", and hit enter. This opens "xerxes-yak-zubba/index.js".

Also, open [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) and search for `ace/index.d.ts`. Even though this is exactly the name of a file, I get taken to `cordova-plugin-email-composer/index.d.ts` instead. I can't reproduce that in a small project.

**Comment by ramya-rao-a** [comment]
Closing in favor of #14727
