### ISSUE TITLE
Remove redundant styles for underlined links

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#155891]
I think there is 1 rule that then could be removed as being redundant:

https://github.com/microsoft/vscode/blob/78397428676e15782e253261358b0398c2a1149e/src/vs/workbench/browser/parts/editor/media/editorplaceholder.css#L40

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/151499#issuecomment-1186084982_

**Comment by misolori** [comment]
https://user-images.githubusercontent.com/35271042/180313440-4469c849-55ab-470b-bc6e-fd71c0a5b974.mp4

**Comment by rzhao271** [comment]
What are some verification steps for this issue?

**Comment by misolori** [comment]
Verification steps: 

1. open a file and quite VS Code
2. delete the file from disk
3. re-open VS Code
4. verify that the link text in the error message (pictured above) shows a underlines on hover
