### ISSUE TITLE
Pressing Escape key in explorer does not focus editor

### ISSUE THREAD

**Issue by ygoe** [microsoft/vscode#155823]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: Windows 10

Follow-up to #24232

Steps to Reproduce:

1. Click once on a file in the explorer panel
2. Press the Escape key

The focus remains in the explorer where I can't do anything useful. I could select another file with the arrow keys, but why would I press Esc before that?

In Visual Studio, the current editor is focused when pressing Esc in any panel. That would be useful.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/24232#issuecomment-294681010 for how you can make this happen.
