### ISSUE TITLE
Custom code action menu looks too large

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#155889]
Type: <b>Bug</b>

Using `editor.experimental.useCustomCodeActionMenu`, the menu looks quite large compared to UI other elements, such as the suggest widget

<img width="625" alt="Screen Shot 2022-07-21 at 1 11 15 PM" src="https://user-images.githubusercontent.com/12821956/180306938-9d6390ad-797b-448a-89cd-486681cff65a.png">

VS Code version: Code - Insiders 1.70.0-insider (Universal) (62469028a6dce9db5b7c4639be7f447f4ab0e35c, 2022-07-21T05:17:20.056Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.72GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by justschen** [comment]
Here's a quick comparison of the old vs. the new menu. I think there are a differences in the padding, which I'll go ahead and fix in the time being.

I also feel that the menu is quite large, but with the added code actions for `Surround With....` which are availale in pretty much every single `Refactor` and Lightbulb action, the menu does look quite bloated.

New menu using the list widget:
![new-menu](https://user-images.githubusercontent.com/54879025/180326623-b2661a33-bbfb-426f-9542-697094c0edff.png)

Old menu using the context menu:
![old-menu](https://user-images.githubusercontent.com/54879025/180326626-9b1de623-0ed1-4aa6-bae0-23abad53b9f8.png)

Viewing the differences, I'm also working on the styling and colors to match the theme (#155907)

**Comment by mjbvz** [comment]
Ah yes this may be because I'm used to the native context menus on Mac (which are much smaller)
