### ISSUE TITLE
How to assign keyboard shortcut to command with argument?

### ISSUE THREAD

**Issue by OliverJAsh** [Microsoft/vscode#15587]
How does one create a keyboard shortcut for a command that receives an argument? I can't seem to find any examples of keyboard shortcuts doing this. I'm presuming the `when` context handles this.

For context, here is the command:

``` ts
	vscode.commands.registerCommand('copyRelativePath', function (uri) {
		copy(vscode.workspace.asRelativePath(uri));
	});
```

Taken from https://github.com/alexandrudima/vscode-copy-relative-path/blob/293f389d9b8afc20eb0e66b8003abc131e519333/extension.js#L5

I tried the following:

``` JSON
{ "key": "alt+cmd+p", "command": "copyRelativePath", "when": "editorTextFocus" }
```

But running this shortcut gives me an error:

```
Running the contributed command:'copyRelativePath' failed.
```

Would love to know where this is documented 😄

**Comment by ramya-rao-a** [comment]
You can update the command's callback function to open an inputbox/quickpick if the argument is not provided

``` ts
vscode.commands.registerCommand('copyRelativePath', function (uri) {
        if (!uri) {
             vscode.window.showInputBox().then(value => copy(vscode.workspace.asRelativePath(uri)));	
        } else {copy(vscode.workspace.asRelativePath(uri))}
});
```

**Comment by ramya-rao-a** [comment]
Or if you want to run the command on a selected text, you can use `editor.activeWindow.selection`

``` ts
vscode.commands.registerCommand('copyRelativePath', function (uri) {
        if (!uri) {
             uri = vscode.window.activeTextEditor.document.getText(vscode.window.activeTextEditor.selection);
        }
	copy(vscode.workspace.asRelativePath(uri));
});
```

**Comment by ramya-rao-a** [comment]
Do these help?

**Comment by OliverJAsh** [comment]
That helps, thank you!

This command is currently used in the context menu, which appears to provide the `uri` argument. Is this documented anywhere?

**Comment by ramya-rao-a** [comment]
https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus

**Comment by OliverJAsh** [comment]
Could the new feature to invoke commands with arguments help here?

**Comment by ramya-rao-a** [comment]
You mean this? https://code.visualstudio.com/updates#_key-binding-command-arguments ?

If your argument is static then yes, this will help you.
If your argument can change every time you want to use it, then this might not help much
