### ISSUE TITLE
Integrated Terminal is not Starting

### ISSUE THREAD

**Issue by benton-gray** [microsoft/vscode#155869]
Issue Type: <b>Bug</b>

Hey Microsoft,

I enabled the newest integrated terminal setting for terminal.integrated.shellIntegration.enabled as true, and since then my integrated terminal is failing to start with a kernel and triangle symbol thingy. (sorry for the bad description)

I do have oh-my-zsh and zshell installed by default. However on disabling the setting and restarting vscode. I could only get one successful terminal to pop up. My Terminal is starting successfully from other clients, like Mac OSX Terminal etc. 

VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 20.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|--crash-reporter-id 3fc5de7d-dfca-4a2e-98fb-9e5d49f78d2e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
packer|4op|0.3.0
html-snippets|abu|0.2.1
vscode-base64|ada|0.1.0
atlascode|atl|2.10.12
path-intellisense|chr|2.8.1
vscode-markdownlint|Dav|0.47.0
gitlens|eam|12.1.2
vscode-html-css|ecm|1.13.0
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.3.1
vscode-firefox-debug|fir|2.9.8
shell-format|fox|7.2.2
go|gol|0.35.1
vscode-jsonnet|Gra|0.2.4
hcl|has|0.2.1
jsonnet|hep|0.1.0
vsc-python-indent|Kev|1.17.0
saltstack|kor|0.0.9
bash-ide-vscode|mad|1.14.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.22.1
vscode-kubernetes-tools|ms-|1.3.10
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
vsliveshare|ms-|1.0.5641
ocaml-platform|oca|1.10.7
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
rust|rus|0.7.8
bash-beautify|sha|0.1.1
umlet|the|15.0.0
html-preview-vscode|tht|0.2.5
shellcheck|tim|0.19.6
json2yaml|tux|0.2.0
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.13.0
salt-lint|war|0.1.0
material-theme|zhu|3.15.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30531698

```

</details>

**Comment by bgray-wish** [comment]
On renable and restart the terminals are starting successfully.

**Comment by meganrogge** [comment]
Do you see an error when creating subsequent terminals? A screenshot would be helpful. 


Also, can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/"needsMoreInfo"
