### ISSUE TITLE
You cannot increase the height of the terminal output in Code Share

### ISSUE THREAD

**Issue by gsmcdonald** [microsoft/vscode#155972]
1. Have user A host a code share session
2. Have user B join the session
3. Have user B open the terminal along the bottom of the screen
4. Have user A run a command that will output multiple lines of text
5. User B will be able to decrease the height of the terminal output, but increasing the height will not work

The area highlighted in green is the height increase.
![image](https://user-images.githubusercontent.com/36003378/180454115-95746690-d211-463b-9c05-90037315dd68.png)

If user A runs another command, it will be at the new height.
It isn't a huge deal, but it does seem like a bug.

**Comment by Tyriar** [comment]
This is by design to have shared terminals use the smallest terminal size. If the terminal was a different size the it would be all messed up when it gets replayed on the guest as printing characters depend on the cols and rows of the pty/terminal.
