### ISSUE TITLE
When running task links to files open with an absolute path instead of relative

### ISSUE THREAD

**Issue by meskill** [microsoft/vscode#155979]
Issue Type: <b>Bug</b>

1. Add new task to `tasks.json` file
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "watch",
      "group": "build",
      "problemMatcher": [
        "$tsc-watch"
      ],
      "isBackground": true,
      "label": "Watch",
      "detail": "tsc -b --watch"
    }
  ]
}
```
2. Run task on a project with errors
3. Click on any file link

**Actual result**: file is opened in vs code with an absolute path instead of relative, on first line instead of line with the error and no errors is shown editor as file is considered outside of project scope

**Expected result**: file is opened with relative path on the line with error.

It works as expected if I just open integrated terminal and run `npm run watch` command by myself. The problem only appears if I'm running command through tasks

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (13.92GB free)|
|Process Argv|--crash-reporter-id 7fd55500-bc16-43f0-8e6a-d91549b8330d|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: unic-workspace|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|Memory (System)|15.63GB (8.95GB free)|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.6.1
jest-snippets|and|1.8.0
vscode-toggle-quotes|Bri|0.3.6
codeswing|cod|0.0.21
postcss|css|1.0.9
es7-react-js-snippets|dsz|4.4.3
remotehub|Git|0.38.0
vscode-drawio|hed|1.6.4
remote-containers|ms-|0.241.3
remote-wsl|ms-|0.66.3
remote-repositories|ms-|0.16.0
fish-vscode|sky|0.2.1
swdc-vscode|sof|2.6.32
errorlens|use|3.5.2
vscode-icons|vsc|11.13.0
gistfs|vsl|0.4.1
vscode-todo-highlight|way|1.0.5
Bookmarks|ale|13.3.1
vscode-toggle-quotes|Bri|0.3.6
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
debug-visualizer|hed|2.3.1
vscode-drawio|hed|1.6.4
ts-error-translator|mat|0.5.1
git-graph|mhu|1.30.0
vscode-kubernetes-tools|ms-|1.3.10
resourcemonitor|mut|1.0.7
color-highlight|nau|2.5.0
color-tabs-vscode-ext|ore|0.12.1
text-power-tools|qcz|1.34.0
vscode-yaml|red|1.9.1
blueprints|Rud|4.0.13
vscode-taskexplorer|spm|2.9.1
code-spell-checker|str|2.3.1
code-spell-checker-russian|str|2.0.5
html-preview-vscode|tht|0.2.5
vscode-conventional-commits|viv|1.24.1
quokka-vscode|Wal|1.0.494
wallaby-vscode|Wal|1.0.345
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30532337

```

</details>

**Comment by meganrogge** [comment]
could you pls provide a gif?

**Comment by meskill** [comment]
Sure

<details>
<summary>Big gif</summary>

![VsCodeTasksBug](https://user-images.githubusercontent.com/8974488/182691046-9334d9f5-13c0-47d8-9e20-f7fdcc928732.gif)

</details>

**Comment by meskill** [comment]
Closing the issue as it is not a problem anymore for me after last updates
