### ISSUE TITLE
Expose zen mode settings in drop-down menu

### ISSUE THREAD

**Issue by connorjclark** [microsoft/vscode#155999]
<img width="350" alt="image" src="https://user-images.githubusercontent.com/4071474/180558342-aaeb846e-87a0-4a93-b4fb-dbaa11160b71.png">

It'd be nice if there were a quick-link to the "Zen mode" settings here.

I just discovered zen mode and love it, but hated that I could only see one tab at a time. Took awhile to consider that there could be [settings](https://stackoverflow.com/questions/49196146/how-do-you-show-tabs-in-zen-mode-of-visual-studio-code) to disable that. I would have found it much quicker if this drop down menu pointed me to it.

**Comment by sbatten** [comment]
cc @bpasero @misolori

**Comment by misolori** [comment]
I think this could be an awesome addition if we ever allow custom user actions in the new title bar cc @jrieken

**Comment by bpasero** [comment]
I think Zen mode is generally discoverable:

<img width="622" alt="image" src="https://user-images.githubusercontent.com/900690/180590693-475d472d-30c0-4885-bca2-2c312bbef618.png">

**Comment by connorjclark** [comment]
I'm not taking about the feature, but the settings.
