### ISSUE TITLE
Server returned 503. extension marketplace

### ISSUE THREAD

**Issue by DevProd-MH** [microsoft/vscode#155969]
Does this issue occur when all extensions are disabled?: Yes 

extension marketplace is returning `Server returned 503` after the last update which i did 3 days ago<br>
- checked my network connection but it seems great.
- checked marketplace page and it is online and working.
- VS Code Version: 1.69.2
- OS Version: Linux x64 5.18.12-arch1-1

Steps to Reproduce:

1.
2.
![image](https://user-images.githubusercontent.com/45941938/180452912-279084b1-7187-4e07-9413-fb64d163a502.png)
![image](https://user-images.githubusercontent.com/45941938/180453094-58fe6b95-cf29-486e-bfd7-254dca73220a.png)

**Comment by gjsjohnmurray** [comment]
Which Linux distro are you using? AFAIK at least one of them repackages VS Code to point to a different marketplace.

**Comment by DevProd-MH** [comment]
i'm using Arch Linux

**Comment by wmir1** [comment]
I had the same problem (I think that the problem is that the [Open VSX ](https://open-vsx.org/) is not available) and solved it like this:
in file `/usr/lib/code/product.json` I replace

`	"extensionsGallery": {
		"serviceUrl": "https://open-vsx.org/vscode/gallery",
		"itemUrl": "https://open-vsx.org/vscode/item"
	},`
with 
`	"extensionsGallery": {
		"serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery",
		"itemUrl": "https://marketplace.visualstudio.com/items"
	},`

**Comment by DevProd-MH** [comment]
> I had the same problem (I think that the problem is that the [Open VSX ](https://open-vsx.org/) is not available) and solved it like this: in file `/usr/lib/code/product.json` I replace
> 
> ` "extensionsGallery": { "serviceUrl": "https://open-vsx.org/vscode/gallery", "itemUrl": "https://open-vsx.org/vscode/item" },` with ` "extensionsGallery": { "serviceUrl": "https://marketplace.visualstudio.com/_apis/public/gallery", "itemUrl": "https://marketplace.visualstudio.com/items" },`

thanks the problem is fixed now
