### ISSUE TITLE
Test optional shell escaping args in terminal launch configs

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#155988]
Refs: #149910

Note, this TPI should only be run if https://github.com/microsoft/vscode-js-debug/pull/1341 was merged and released. cc @connor4312 

- [x] macOS @IanMatthewHuff
- [x] linux @deepak1556
- [x] windows @sbatten

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23155988%0A%0A&assignees=roblourens)

---

- Create a node launch config that will start in an integrated terminal:

```
{
    "type": "node",
    "request": "launch",
    "name": "Run",
    "program": "${workspaceFolder}/test.js",
    "console": "integratedTerminal",
    // "args": [ "`echo hello` > outfile" ],
    // "args": "`echo hello` > outfile",
},
```

- When you run it with the array form of `args`, the args should be escaped for the shell and passed verbatim to the debuggee
- When you run it with the single string form of `args`, the args should not be escaped, so that the subcommand executes and output is redirected to `outfile`
- Note that this is currently only implemented for integratedTerminal, not externalTerminal

**Comment by IanMatthewHuff** [comment]
@roblourens given the merge date of https://github.com/microsoft/vscode-js-debug/pull/1341 I was expecting this to be in the build today, but maybe I'm off on that? I'm on current insiders and it doesn't like the string args:
<img width="493" alt="image" src="https://user-images.githubusercontent.com/812783/181017342-e21521ab-25a1-4d60-8606-a814000dc352.png">

**Comment by connor4312** [comment]
Please use the nightly build https://github.com/microsoft/vscode-js-debug#nightly-extension

**Comment by IanMatthewHuff** [comment]
Looks good from my end.

**Comment by sbatten** [comment]
use "$(echo hello) > outfile" for pwsh
