### ISSUE TITLE
I have Error massage  appear every 30m  after I open VS code 

### ISSUE THREAD

**Issue by GAbdulWahab** [microsoft/vscode#155994]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:
- OS Version: yes

Steps to Reproduce:

![Error-massage](https://user-images.githubusercontent.com/108471229/180515447-a6e6d031-b347-4bf0-a6f3-968bc98c2241.png)

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/147408
