### ISSUE TITLE
Add custom ordering to title menu items.

### ISSUE THREAD

**Issue by mdickin** [Microsoft/vscode#15596]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Create a new VSCode extension
2. Define commands in the package.json for "Toggle Bold", "Toggle Italics", and "Toggle Bullets", complete with icons.
3. Add these commands to the "editor/title" menu
4. Load Code with this extension installed
5. Note that the order of icons is changed, with the Bullets icon between Bold and Italic.

![image](https://cloud.githubusercontent.com/assets/16612667/20369687/22fd6304-ac20-11e6-89c7-69c529751e47.png)

From what I can tell, the ordering of items is strictly by the name of the command. However, this is less than ideal, as it looks strange having Bold and Italic separated. I considered changing the names of the commands to control order, but this would look strange when presented to the user.

I ran into this issue with [my extension](https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts). I ended up removing the Bullets icon until I can define the order.

**Comment by jrieken** [comment]
There is way to define the order and I am surprised we haven't properly documented that... What you can do is adding an order to the group-attribute like so `group: name@number`. In your case

```json
{
                    "command": "md-shortcut.toggleBold",
                    "when": "editorLangId == 'markdown'",
                    "group": "2_markdown_1@1"
 }
```

**Comment by jrieken** [comment]
I'll make sure to update the doc for this

**Comment by mdickin** [comment]
Great, thank you so much!
