### ISSUE TITLE
no suggestions

### ISSUE THREAD

**Issue by Alexander781** [microsoft/vscode#155913]
Issue Type: <b>Performance Issue</b>

I suddently stopped getting suggestions in my .css file when im styling. Why is that?

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (8.26GB free)|
|Process Argv|--crash-reporter-id 30d84f2a-783c-4836-8f9e-9e1603334f73|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    96	  5492	code main
    0	    98	  2000	   gpu-process
    0	    39	  2740	   utility-network-service
    0	    26	  6624	   crashpad-handler
    0	    87	 12512	   issue-reporter
    0	   178	 16300	   window (style.css - öva css - Visual Studio Code)
    0	   119	 20344	   extensionHost
    0	    77	 12396	     "C:\Users\OMEN1\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\OMEN1\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\css-language-features\server\dist\node\cssServerMain" --node-ipc --clientProcessId=20344
    0	   103	 19144	     "C:\Users\OMEN1\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\OMEN1\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=20344
    0	   103	 29444	   shared-process
    0	    71	 10636	     ptyHost
    0	    76	 28876	     fileWatcher
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (style.css - öva css - Visual Studio Code)
|    Folder (öva css): 2 files
|      File types: css(1) html(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
code-runner|for|0.11.8
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
LiveServer|rit|5.7.5
vscode-icons|vsc|11.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30532338

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by aeschli** [comment]
It is very likely an extension that took over the HTML mode.
