### ISSUE TITLE
Adopt loading progress when running tests

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#155955]
![image](https://user-images.githubusercontent.com/2193314/180437571-194ba6dd-7edc-4615-ae80-32a12f88f8a7.png)

This support was added for tasks:

![179767680-8b52615a-8f37-4dde-a4fe-0a8d7b6f4666 (1)](https://user-images.githubusercontent.com/2193314/180437924-e0842c96-fbae-459d-909b-8c73c2452cb0.gif)

We should use the sync icon when we're synchronizing something (git fetch, checking tasks.json, etc.) and loading when work is happening that wouldn't be classified as syncing.

**Comment by lramos15** [comment]
Running unit tests in the vscode repo I still see the sync icon.
