### ISSUE TITLE
Multi-line indents do not preserve partial indents

### ISSUE THREAD

**Issue by lewisl9029** [microsoft/vscode#15598]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra 10.12.1

I'm using VSCode for Clojure editing right now and have been running into this issue a lot. This seems to be a general problem with VSCode's indentation mechanism though, and not a language specific problem. I've also verified that it's reproducible on the latest master build without any extensions or customizations applied.

Steps to Reproduce:

1. Set indentation to 2 spaces
2. Paste the following into an empty editor:
```
  {:key1 :value1
   :key2 :value2}
```
3. Select both lines and press tab

Expected: 

Both lines are indented by the standard indentation size of 2 spaces. This is the standard behavior in Atom, as well as most other editors I've worked with: 

![nov-16-2016 15-33-50](https://cloud.githubusercontent.com/assets/6934200/20370170/1a904a8c-ac12-11e6-86ee-ec50a0fddb93.gif)

Actual:

Both lines are indented to the same indentation level, and the partial indent on the second line is discarded:

![nov-16-2016 15-16-03](https://cloud.githubusercontent.com/assets/6934200/20369751/a1fe5926-ac0f-11e6-92c0-f9e4ae39b090.gif)

I tried poking around in the source code a bit but couldn't quite figure out where this functionality lives. If someone could just point me in a general direction, I can try giving it another shot.

**Comment by wallverb** [comment]
Something similar: https://github.com/Microsoft/vscode/issues/9409

**Comment by ramya-rao-a** [comment]
@alexandrudima Would this be tracked as part of #15598 or separate?

**Comment by alexandrudima** [comment]
Today, indenting and unindenting always tries to "snap" the text to tab stops.

I think we could piggy back on the existing setting `editor.useTabStops` and "snap" the text to tab stops only when the setting is off.

**Comment by alexandrudima** [comment]
This works as expected when using `"editor.useTabStops": false`.
