### ISSUE TITLE
Extension host sits at high CPU (macOS)

### ISSUE THREAD

**Issue by nebbles** [microsoft/vscode#155936]
Issue Type: <b>Performance Issue</b>

This occurs on starting VS Code. A Code Helper sits at about 50-60% CPU when idling.

Tried profiling extensions but couldn't see anything with lots of activity.

Took the PID of the Code Helper process and ran `ps aux | grep <PID>` and then disabled all the extensions shown under that process. Made no difference. The CPU is attributed to this path: 
```
26352  65.3  1.0 55257996 673792   ??  S     9:47am   2:51.21 /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --inspect-port=0 /Applications/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork --type=extensionHost --skipWorkspaceStorageLock
```

When reloading the window with extensions disabled, the Code Helper process disappears and doesn't return. However if it is an extension I really can't pin it down - but doesn't this command also disable the extension host itself?

---

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (15.19GB free)|
|Process Argv|--crash-reporter-id 56ab5a67-1b26-4efc-8ce2-1525395e8fbb|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   197	 25503	code main
    3	   131	 25506	   gpu-process
    0	     0	 25514	   utility-network-service
   81	   459	 25515	   window (Extension: JSON Tools — app)
   48	   262	 25856	   shared-process
    0	    66	 25961	     ptyHost
    0	     0	 26751	       /bin/zsh -l
    0	     0	 26755	       /bin/zsh -l
    0	    66	 26351	     fileWatcher
    0	     0	 29158	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
   50	   655	 26352	   extensionHost
    0	    66	 26697	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=26352
    0	   131	 28720	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/6j/42gylfys1c9bb0tn3zxg378h0000gn/T/vscode-typescript501/8d4d2b7ccde1230596b8/tscancellation-06a5225047d6b0c0a100.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations /Users/bengreenberg/.vscode/extensions/styled-components.vscode-styled-components-1.7.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	   459	 28721	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/6j/42gylfys1c9bb0tn3zxg378h0000gn/T/vscode-typescript501/8d4d2b7ccde1230596b8/tscancellation-5355f5b4d73f003017e6.tmp* --globalPlugins typescript-styled-plugin --pluginProbeLocations /Users/bengreenberg/.vscode/extensions/styled-components.vscode-styled-components-1.7.4 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    66	 28725	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/bengreenberg/Library/Caches/typescript/4.7 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    66	 28771	   window (undefined)
   16	    66	 29156	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Extension: JSON Tools — app)
|    Folder (app): 1104 files
|      File types: svg(289) tsx(181) ts(134) png(95) js(40) json(23)
|                  DS_Store(22) woff2(20) woff(20) map(12)
|      Conf files: github-actions(3) settings.json(1) package.json(1)
|                  tsconfig.json(1);
```

</details>
<details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.0
color-info|bie|0.7.0
better-toml|bun|0.3.2
bazel-code|Dev|0.1.9
binary-plist|dni|0.9.1
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.2
json-tools|eri|1.0.2
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
code-runner|for|0.11.8
codespaces|Git|1.9.4
remotehub|Git|0.38.0
vscode-pull-request-github|Git|0.46.0
gc-excelviewer|Gra|4.2.55
todo-tree|Gru|0.0.215
beautify|Hoo|1.5.0
plantuml|jeb|2.17.3
cmake-language-support-vscode|jos|0.0.4
node-module-intellisense|lei|1.5.0
restructuredtext|lex|189.1.0
rainbow-csv|mec|2.4.0
template-string-converter|meg|0.6.0
selected-character-count|mou|0.0.1
vscode-docker|ms-|1.22.1
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-repositories|ms-|0.16.0
vsliveshare|ms-|1.0.5641
autodocstring|njp|0.6.1
advanced-new-file|pat|1.2.2
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
LiveServer|rit|5.7.5
platform-settings|run|1.0.0
rust|rus|0.7.8
code-settings-sync|Sha|3.4.3
vscode-brewfile|sha|1.0.0
mdx|sil|0.1.0
vscode-taskexplorer|spm|2.9.1
rewrap|stk|1.16.3
vscode-styled-components|sty|1.7.4
vscode-open-in-github|sys|1.16.0
gcode|Ton|0.4.0
vscode-icons|vsc|11.13.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.2

</details>

**Comment by gjsjohnmurray** [comment]
Does the Start Extension Bisect command help?

**Comment by nebbles** [comment]
That is a phenomenal command! Thanks for sharing @gjsjohnmurray 

It took a little while working through them all, with each test checking activity monitor, waiting to settle, and seeing if the CPU usage was present. 

Can confirm now that the issue is narrowed to the Settings Sync extension. From taking a brief look at [the issues page](https://github.com/shanalikhan/code-settings-sync/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), this is a heavily reported issue.
