### ISSUE TITLE
 Cannot read property 'state' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#15597]
Issue Id: <b>a1f4af8c-5202-6830-05ae-b3ff274b0b0d</b><br /><br />*Versions* <br />- 1.8.0 Insiders (11/11/2016)<br />-  fb8939b09460ff9fbd40d39056b54c88d5aad9c8<br />*Stack* <br />

TypeError: Cannot read property 'state' of null<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName))<br />[/vs/base/common/actions.ts#L210:28 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/actions.ts#L210:28 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L31:7 (updateOptions)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L31:7 (updateOptions))<br />[/vs/base/browser/ui/actionbar/actionbar.ts#L520:8 (render)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/browser/ui/actionbar/actionbar.ts#L520:8 (render))<br />

**Comment by vscodeerrors** [comment]
hello again

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'state' of null<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName))<br />[/vs/base/common/actions.ts#L210:28 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/actions.ts#L210:28 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L31:7 (updateOptions)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L31:7 (updateOptions))<br />[/vs/base/browser/ui/actionbar/actionbar.ts#L520:8 (render)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/browser/ui/actionbar/actionbar.ts#L520:8 (render))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'state' of null<br />    at t.updateEnablement (out/vs/workbench/electron-browser/workbench.main.js:93:9200)<br />    at out/vs/workbench/electron-browser/workbench.main.js:93:10941<br />    at e.invoke (out/vs/workbench/electron-browser/workbench.main.js:30:22801)<br />    at e.fire (out/vs/workbench/electron-browser/workbench.main.js:31:1364)<br />    at e.setSelectedConfigurationName (out/vs/workbench/electron-browser/workbench.main.js:83:23620)<br />    at t.run (out/vs/workbench/electron-browser/workbench.main.js:93:10521)<br />    at t.run (out/vs/workbench/electron-browser/workbench.main.js:32:24893)<br />    at t.updateOptions (out/vs/workbench/electron-browser/workbench.main.js:82:24694)<br />    at t.render (out/vs/workbench/electron-browser/workbench.main.js:82:24268)<br />    at out/vs/workbench/electron-browser/workbench.main.js:45:23621<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'state' of null<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName))<br />[/vs/base/common/actions.ts#L210:28 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/actions.ts#L210:28 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L31:7 (updateOptions)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L31:7 (updateOptions))<br />[/vs/base/browser/ui/actionbar/actionbar.ts#L520:8 (render)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/browser/ui/actionbar/actionbar.ts#L520:8 (render))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'state' of null<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L56:50 (state))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L120:8 (updateEnablement))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/common/debugViewModel.ts#L100:37 (fire))<br />[/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActions.ts#L108:35 (setSelectedConfigurationName))<br />[/vs/base/common/actions.ts#L210:28 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/actions.ts#L210:28 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L45:21 (run))<br />[/vs/workbench/parts/debug/browser/debugActionItems.ts#L22:8 (updateOptions)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/workbench/parts/debug/browser/debugActionItems.ts#L22:8 (updateOptions))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/fb8939b09460ff9fbd40d39056b54c88d5aad9c8/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />

**Comment by isidorn** [comment]
Fixed in master
