### ISSUE TITLE
Show enabled extensions isolated 

### ISSUE THREAD

**Issue by efirvida** [Microsoft/vscode#15590]
Hello, I have a new request for the vscode team.
After installing several extensions, and disabling some, I have been uncomfortable with the fact that I can´t see isolated the extensions that I have enabled. Instead with the extensions disabled the opposite happens.

In my opinion should appear by default only the extensions enabled when the extensions panel opens, and the user decides whether or not to see the disabled, which for some reason disabled them

**Comment by sandy081** [comment]
An action to show only enabled extensions was made available.
