### ISSUE TITLE
[jade] Syntax Highlighting Stops Working on Unbuffered Code

### ISSUE THREAD

**Issue by phillipwei** [Microsoft/vscode#1559]
As soon as I use unbuffered code, the syntax highlighting stops working.

In the attached, `.row.source-of-income-row` has lost syntax highlighting -- and the rest of the jade file too.

![jade_syntax](https://cloud.githubusercontent.com/assets/557873/11944365/90f27cda-a7fa-11e5-8460-88d989f4af9a.PNG)

**Comment by exp0nge** [comment]
Also having this issue, especially when using `else`.
![image](https://cloud.githubusercontent.com/assets/11747245/12000204/8d9ea20a-aa9f-11e5-9b66-7332283fc5cc.png)

**Comment by aeschli** [comment]
Can you paste a code sample where you see this?

**Comment by exp0nge** [comment]
After `else`:   

    extends layout

    block content
        .row
            .col-sm-6
                h3 Search
        .row
            .col-sm-12
                form(method='get', action='/customer/search/')
                    .row
                        .col-sm-12
                            .form-group
                                if q
                                    input(type='text', id='q', value='#{q}', name='q', class='form-control', placeholder='e.g., brooklyn coffee', required)
                                else
                                    input(type='text', id='q', name='q', class='form-control', placeholder='e.g., brooklyn coffee', required)
                            .form-group
                                input(type='submit', value='search', class='btn btn-success pull-xs-right')
        | <br>                        
        if restaurants
            if q && restaurants.length == 0
                .row
                    .col-sm-12
                        .alert.alert-danger(role='alert')
                            | <strong> 0 results </strong> Try to make your search term broader...
            else
                .row
                    .col-sm-12
                        if q
                            .alert.alert-success(role='alert')
                                | <strong> #{ restaurants.length } results </strong> Enjoy!
                include restaurants-loop

**Comment by WakeskaterX** [comment]
I'm also seeing this after the else statement in a Jade template.  Notably, right after the else statement where no IF statement is also included.  Leaving a blank line seems to reset the syntax, but both after the  if statement and else statement look incorrect compared to syntax highlighting outside the if statement.

Also there seems to be a weird issue with blank lines before comments too

![screen shot 2016-04-04 at 2 06 44 pm](https://cloud.githubusercontent.com/assets/6043886/14258024/840cc068-fa6e-11e5-840c-18fb70e7ed58.png)

Version 0.10.11 (0.10.11)

That's the monokai theme, but also tested with Dark+, dark, etc looks the same for them all.

**Comment by mrmlnc** [comment]
Fixed by VS Code version 1.5.0.
