### ISSUE TITLE
Find symbols, find references, format code does not work on Ubuntu 15.04

### ISSUE THREAD

**Issue by khagesh** [Microsoft/vscode#156]
I am still using 0.8.0 and these things works fine on this version. However, all the releases after it does not work properly.

Kudos to whole team for creating a fast editor that works cross platform.

**Comment by bpasero** [comment]
@khagesh what language you are writing?

**Comment by khagesh** [comment]
@bpasero TypeScript and .tsx files does not support find symbols and find references and format code does not work for .html, .scss, .ts or .tsx. These are the only file types that I have tried.

**Comment by aeschli** [comment]
.scss has no formatting support. I just tried HTML, TS ans TSX, all seem to work.
- put some unnessary indent in a file
- put the cursor in the file, or select the range to be formatted
- call format from the context menu
Does your code have syntax errors that might prevent the formatter from parsing the file?

**Comment by khagesh** [comment]
@aeschli thanks for taking time for this issue. I ran ts compiler (1.7) on both .ts and .tsx files and it did not throw any error. Do you want any extra information (node version, any Ubuntu logs, etc.) that might be helpful for fixing this issue?

**Comment by aeschli** [comment]
@khagesh Are the menu actions enabled, but just have no effect?
Is it with all files, or a specific one?
Can you open the dev tools ( F1 > Toggle Developper Tools ) and check for any messages in the Console tab?

**Comment by alexandrudima** [comment]
@khagesh ping. Any more information you can provide to help us reproduce this issue?

**Comment by khagesh** [comment]
I am sorry for not replying earlier. I have checked console tab as well, there is no message/error printed. I  checked it on my colleague's machine as well and he is also having same issue.
This happens only for .ts and .tsx files, I downloaded latest version today as well and it had same issue.
Please let me know, if there is anything that I can do to help you.

**Comment by egamma** [comment]
We cannot reproduce this in the December update that will be published end of this week. Please file a new issue if the problem persists.

**Comment by khagesh** [comment]
I tried it in the latest version and I still can't get it to work for .ts or .tsx files. 
I am using Ubuntu 15.04 with 64 bit version of vscode. Find all references, find symbols, go to definition, intellisense, nothing works. I have tried it in 3-4 machines in our office and it does not work on those machines as well.

I can lookup the code and try to debug the issue, can you please point me to some location in code which is either an starting point or somewhere related to these functionalities.

**Comment by egamma** [comment]
>I tried it in the latest version and I still can't get it to work for .ts or .tsx files. 

Are you referring to format or find references?

When it is find references I suspect something with your setup. Do you have tsconfig.json defined (https://code.visualstudio.com/docs/languages/typescript)?

Can you try this project https://github.com/Microsoft/vscode-samples/tree/master/node-express-typescript and do a reference search in `src`\app.ts.
