### ISSUE TITLE
A way to pause rolling out a new version

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#15602]
Not sure how simple and useful this would be, but if we had had a way to pause the rollout of 1.7.0, we could have bought us some time to make a decision and possibly build a 1.7.1 to continue the rollout with.

/cc @seanmcbreen @kieferrm @joaomoreno

**Comment by kieferrm** [comment]
One of the discussions that emerged is that we should start rolling out in chunks rather than to everyone at the same time. That would allow us to monitor the roll-out and potentially stop it if needed.

**Comment by bpasero** [comment]
@chrmarti what is wrong with unchecking the "released" checkbox on the builds page?

![image](https://cloud.githubusercontent.com/assets/900690/20859369/721c5342-b95d-11e6-8ea2-c8b59fae0517.png)

**Comment by chrmarti** [comment]
@bpasero My understanding is that unchecking that, will let those clients that already updated downgrade. Depending on how many clients these are and what the problem with the new version is, that might be undesirable. Having a way to pause the rollout to get time to decide if, e.g., a fix in a `.1` version would make sense, could lessen the disruption for early updaters.

**Comment by bpasero** [comment]
Got it, you are right.

**Comment by chrmarti** [comment]
Tracked with #26200
