### ISSUE TITLE
Auto reveal does not work when open the soft link fold 

### ISSUE THREAD

**Issue by iccsmart** [microsoft/vscode#156089]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
1. Open the soft link fold of the c++ project
2. enable the cpp extension or clangd extension
3. generate the compile_command.json and configure the cpp extesion or clang extension of the with the compile_command.json
4. use the goto definition and the related cpp file opened
5. the opened file does not auto reveal in the vscode exploer

Is it a known issue or any configuration can fix it?

**Comment by aeschli** [comment]
This issue needs to be filed against 
https://github.com/Microsoft/vscode-cpptools/issues
Would you mind filing the issue there? (Unfortunately, the issue-transfer tool only works with write access on both repos, which I haven't)
