### ISSUE TITLE
Fira Code font support for web-based VS code

### ISSUE THREAD

**Issue by necropolina** [microsoft/vscode#156067]
Android users have limited capacity to install fonts on Android devices. I'd like to use [Fira Code](https://github.com/tonsky/FiraCode) while working from an android tablet. 

I'm able to use Fira Code in vscode for the web (including ligatures and without it being installed on my host machine) by injecting this css line using dev tools: `@import url(https://cdn.jsdelivr.net/npm/firacode@6.2.0/distr/fira_code.css);`

Would be great if Fira Code could get native support for browser-based VS code. Fira Code is a popular open-source monospace font that's already supported by some other web-based dev projects like CodePen.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/83294
