### ISSUE TITLE
navigate search box after replace all closes search box 

### ISSUE THREAD

**Issue by rob-miller** [microsoft/vscode#156090]
Issue Type: <b>Bug</b>

on MacOS
command-f to open search box
enter string
open drop-down for replace
enter string
click 'replace all' icon
[search box now says '0 results']
click in text string in search box
keyboard back arrow key
result:
search box closes
desired result:
navigate in string to edit and start new search and replace

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No
Remote OS version: Linux x64 5.15.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (0.90GB free)|
|Process Argv|--crash-reporter-id 7c28fe66-0681-43dd-9fae-486d73d81fcc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: hal.rtm.home|
|OS|Linux x64 5.15.0-40-generic|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4000)|
|Memory (System)|62.74GB (18.11GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
scad|efb|1.0.1
language-cython|guy|0.0.7
vscode-emacs|hir|0.1.1
better-cpp-syntax|jef|1.15.19
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
arduino-snippets|ron|1.0.2
cython|tcw|0.1.0
emacs-mcx|tut|0.44.0
vscode-icons|vsc|11.13.0
vscode-emacs-friendly|lfs|0.9.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
emacs|nis|0.0.9
codemap|ole|1.16.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30532338

```

</details>

**Comment by rebornix** [comment]
> keyboard back arrow key
result:
search box closes

@rob-miller can you help me understand what "keyboard back arrow key" here means? I'm not able to reproduce it with arrow-left, or delete, or other keyboard shortcuts.

**Comment by rob-miller** [comment]
Sorry!  It's a documented part of 'Awesome Emacs Keymap' extension
