### ISSUE TITLE
Having trouble with my code space

### ISSUE THREAD

**Issue by ShadowX028** [microsoft/vscode#156063]
I'm having trouble with my code space for some reason I keep getting this error and I have no idea on how to fix it or what to do, is this something that will go away on its own? or is there something that needs to be done?
Cause I'm not really sure what to do here. If you could please help me out I would really appreciate it.
![Screenshot 2022-07-23 152044](https://user-images.githubusercontent.com/89418547/180621578-82607975-ccfd-4823-bc5e-2b20800ed9a3.png)

Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Tyriar** [comment]
Please report Codespaces issues to [GitHub support](https://support.github.com/?tags=dotcom-footer)
