### ISSUE TITLE
全局替换结果与预期不一样,与neovim也不一样(This is simplified Chinese ,not Japanese)

### ISSUE THREAD

**Issue by a15355447898a** [microsoft/vscode#156024]
Issue Type: <b>Bug</b>

[这是我使用的文本](https://github.com/a15355447898a/book-japan/blob/main/%E7%88%AC%E5%8F%96%E4%B8%8B%E6%9D%A5%E7%9A%84%E5%B0%8F%E8%AF%B4/%E6%97%A5%E6%9C%AC%E3%81%B8%E3%82%88%E3%81%86%E3%81%93%E3%81%9D%E3%82%A8%E3%83%AB%E3%83%95%E3%81%95%E3%82%93%E3%80%82.md)

使用正则`^[^#].*`替换为``(空)

![vscode,全局替换前](https://s1.ax1x.com/2022/07/23/jXpOKA.png)

`## 序章`和`### 第１話　こんにちは、エルフさん`之类的本应该不被删除

但是在全局替换后

![vscode,全局替换后](https://s1.ax1x.com/2022/07/23/jX9ZV0.png)

在neovim中使用命令`:%s/^[^#].*//g`

![neovim,全局替换前](https://s1.ax1x.com/2022/07/23/jX9DsA.png)

![neovim,全局替换后](https://s1.ax1x.com/2022/07/23/jX9yZt.png)

可以看到`## 序章`和`### 第１話　こんにちは、エルフさん`之类的未被删除

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:14:10.636Z)
OS version: Linux x64 5.14.21-150400.22-default
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G3240 @ 3.10GHz (2 x 3092)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|11.50GB (0.50GB free)|
|Process Argv|--unity-launch --crash-reporter-id 58d96ba3-7d60-4153-9a62-7460223a0726|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|/usr/share/xsessions/plasma5|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
Nix|bbe|1.0.1
vscode-office|cwe|2.6.5
Lisp|mat|0.1.12
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.69.7130921
partial-diff|ryu|1.4.3
errorlens|use|3.5.2
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30532337

```

</details>

**Comment by ArcticLampyrid** [comment]
#### Translation
The result of replacing globally is not the same as expected, nor the same as [Neovim](https://neovim.io/).
When I tried to replace `^[^#].*` (regex) with `(empty)`, it removed `## 序章` and `### 第１話　こんにちは、エルフさん`, which is not expected.
Neovim did it properly.

BTW, I can't reproduce this probleam.

#### Plus
请用英语。
English please.
