### ISSUE TITLE
Test: Shell integration manual install

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#156001]
Refs: #153921

- [x] macOS @tanhakabir
- [x] linux @deepak1556
- [x] windows @hediet
- [x] WSL @joyceerhl (or any remote)

Complexity: 3

Authors: @Tyriar, @meganrogge 
Roles: Developer, Engineering Manager

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156001%0A%0A&assignees=Tyriar,meganrogge)

---

Shell integration should be activated manually for the original shell launched in the terminal, but not in sub-shells. To workaround this you can manually install shell integration in your init scripts which will activate it even when launched outside VS Code. To test, read the updated documentation at https://github.com/microsoft/vscode-docs/blob/vnext/docs/terminal/shell-integration.md#manual-installation.

Some things to test in particular:

- Shell integration still works when manually installed _and_ automatic injection is enabled and working
- Manual install doesn't break other terminals (the if condition blocks that)
- Try inlining the script https://github.com/microsoft/vscode-docs/blob/vnext/docs/terminal/shell-integration.md#portability-vs-performance

**Comment by hediet** [comment]
Shell integration is easily one of the coolest recent VS Code features 🤯

But I don't fully understand what I should test for this testplan-item. Can you give some concrete steps?

**Comment by meganrogge** [comment]
created https://github.com/microsoft/vscode/issues/156330 bc was going to ask if you'd seen that there's a learn more about shell integration action in the command decoration's context menu, but that link is wrong ATM

**Comment by joyceerhl** [comment]
I installed shell activation for bash on WSL and verified that
- automatic script injection continued to work for terminals created in VS Code with Remote-WSL
  
![image](https://user-images.githubusercontent.com/30305945/181130518-338514df-0bc5-4097-bd38-0dae50ea3ece.png)

- manual script injection worked for subshells, i.e. if I ran `bash` in the integrated terminal, command decorations continued to work (e.g. I could use them to rerun a command)
  
![image](https://user-images.githubusercontent.com/30305945/181130555-66601878-8928-4f2f-9f77-caeff4960786.png)

- I could still create a WSL bash terminal outside of VS Code and the terminal wasn't bricked
- inlining the script path worked (though I didn't see a perf hit in the first place)

Let me know if I missed anything in the setup, as I'm not a terminal power user and went off of the docs that @meganrogge shared 🙂

**Comment by meganrogge** [comment]
@hediet could you pls clarify what you mean above?
