### ISSUE TITLE
I want to copy the file bower path when copying the path in the File menu bar right mouse button.

### ISSUE THREAD

**Issue by strongant** [Microsoft/vscode#15609]
- VSCode Version:v1.7.1
- OS Version:Linux

**Comment by ramya-rao-a** [comment]
what is a "file bower path" ?

**Comment by jrieken** [comment]
Please provide the requested information

**Comment by strongant** [comment]
In fact, I hope you can be the right mouse button copy files relative paths, rather than the absolute path, each finished copy need to delete the redundant characters.
