### ISSUE TITLE
[css] Remove deprecated CSS colorKeywords

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1560]
When completing CSS values, there is a very long list of named colours, keywords, functions, etc. Included are a whole host of CSS System Colours, which have been deprecated for a long time. 

“Earlier versions of CSS defined several additional named color keywords, the <deprecated-system-color>s, which were meant to take their value from operating system themes. These color names have been deprecated, however, as they are insufficient for their original purpose (making website elements look like their native OS counterparts), and represent a security risk, as it makes it easier for a webpage to "spoof" a native OS dialog.” – https://drafts.csswg.org/css-color/#system-colors

While it is easy to skim read through the named colours, these system colours hide some of the more valuable values, such as transparent and currentColor. 

As the system colours are deprecated, arguably of little value, and probably not used very much, should we remove them from the completion list?

**Comment by Tyriar** [comment]
They're also deprecated in the [W3C recommendation spec](http://www.w3.org/TR/2011/REC-css3-color-20110607/#system-colors-def). Makes perfect sense to remove them imo.
