### ISSUE TITLE
github badges from private repos are not shown

### ISSUE THREAD

**Issue by uishon** [microsoft/vscode#156091]
Issue Type: <b>Bug</b>

1. Add a github badge to some github action from a private repo to a a README.md file inside that very same repo.
2. Open the preview pane of that README.md file.
3. Badge is shown as an image place holder.

Note that when viewing the README on github website - it's shown OK, but if I'm going into vscode web on github, the image is broken just like on the desktop.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (4.48GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/uri/smoke-test --remote=wsl+Ubuntu --crash-reporter-id 962d7448-ca31-461b-a2ff-976e5bc5ff51|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.51GB (10.34GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: fabric|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1497)|
|Memory (System)|15.51GB (10.34GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.38.0
AWK|lug|0.0.2
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
remote-repositories|ms-|0.16.0
debugger-for-chrome|msj|4.13.0
gitlens|eam|12.1.2
go|gol|0.35.1
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
makefile-tools|ms-|0.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30532337

```

</details>

**Comment by lszomoru** [comment]
@mjbvz, is this something that falls in your area of ownership? Thanks!

**Comment by mjbvz** [comment]
If the repo is private, you can only view it when logged into GitHub. I don't think VS Code isn't going to be able to show the badges in this case because we'd also have to send along your GitHub creds when making the request for the badge
