### ISSUE TITLE
Ustawienia, ogólny przycisk aby dostać się do settings.json

### ISSUE THREAD

**Issue by PatrykSitko** [microsoft/vscode#156012]
Issue Type: <b>Feature Request</b>

Kiedy otwieram Ustawienia to muszę szukać przycisku aby otworzyć plik settings.json.
Fajnie by było jeżeli by można było wcisknąć jakiś ogólno dostępny gużik który otworzy ten plik bez przeszukiwania wszystkich opcji w liśćie aż się znajdzie któryś który to umożliwia.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by PatrykSitko** [comment]
When I open Settings, I have to look trough the settings to find a button to open the settings.json file.
It would be nice if you could press a general button that will open this file without going through all the options in the settins until I find one that allows to open it.

**Comment by sbatten** [comment]
Any of the following commands support custom keybindings for opening the settings.json file directly
<img width="468" alt="image" src="https://user-images.githubusercontent.com/6561887/180837256-2a15d7e7-630b-4b81-b537-b268199c6f46.png">

**Comment by PatrykSitko** [comment]
I didn't ask for a command, but for a button that triggers this command inside of the settings panel.

**Comment by sbatten** [comment]
This button? 
<img width="150" alt="image" src="https://user-images.githubusercontent.com/6561887/180864008-e8378cde-b0b0-4fb7-b2ad-212855eeecbf.png">

**Comment by PatrykSitko** [comment]
Exactly this button! Thx.
