### ISSUE TITLE
Search and quick open exclude tracked files when in .gitignore

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#156076]
Does this issue occur when all extensions are disabled?: Yes

In https://git-scm.com/docs/git-check-ignore it's stated that:

> By default, tracked files are not shown at all since they are not subject to exclude rules; but see ‘--no-index’.

Indeed, `git check-ignore` won't consider a tracked file as ignored, even if its name matches some pattern in .gitignore, except when passed the flag `--no-index`. This only makes sense, since the file was explicitly added to the repository. It also allows to implement a workflow of selective inclusion without having to enter each included file (and all its parent directories!) in .gitignore.

But vscode quick open and search exclude tracked files when their names match some pattern in .gitignore.

- VS Code Version: 1.69.2
- OS Version: macOS Monterey 

Steps to Reproduce:

1. Create a git repo
2. Create a file (foo) inside the repo with some contents (bar) in it
3. Add the file to .gitignore
4. Force add the file to the repo and commit
5. Run vscode on the repo
6. Press C-p and search for foo
7. There are no matches
8. Press C-S-f to open the search UI and search for bar
10. There are no matches
11. Remove the file from .gitignore
12. Repeat 6 and 8 above
13. In both cases, there are matches

```bash
cd /tmp
mkdir test-repo
cd test-repo
echo bar > foo
echo foo > .gitignore
git init
git add -f foo
git commit -m foo
code .
```

Maybe related: https://github.com/microsoft/vscode/issues/156077

**Comment by TylerLeonhardt** [comment]
@roblourens/@lramos15 one of you owns search, right?

**Comment by TylerLeonhardt** [comment]
My suspicion is that we don't run get to determine if a file is truly tracked or not because that would be too expensive. Instead we parse the .gitignore ourselves and then include/exclude files accordingly.

Without a huge perf impact on search, I'm not sure how we can do this... but maybe @roblourens or @lramos15  knows something.

**Comment by memeplex** [comment]
It seems to me that there are two kind of inconsistencies:

1. External: between vscode and git, because vscode tries to replicate git behavior.
2. Internal: between the file explorer and search/quick-open (https://github.com/microsoft/vscode/issues/156077)

Search and quick-open seem to understand more about !-patterns than the file explorer does, yet they are unable to cope with the ignored-but-tracked situation.

**Comment by roblourens** [comment]
ripgrep reads .gitignore files for search, and that tool doesn't plan to support reading the actual git index: https://github.com/BurntSushi/ripgrep/issues/743#issuecomment-357092554

Then to my knowledge, for the explorer we parse the gitignore file but as far as I know internally we still don't support negative glob patterns

**Comment by memeplex** [comment]
> doesn't plan to support reading the actual git index

A bit disappointing but I surely can understand. My use case is to keep dotfiles in git, so I have a repo sitting at my home, from the command line it's enough to just set git to not list untracked files, other tools including VSCode will have a hard time trying to list every file so a global ignore pattern is in order, then not having to force adds of tracked files each time is an elegant solution, otherwise explicit unignore patterns like !/a !/a/b !/a/b/.c etc have to be used, not terrible for a handful of dotfiles but not so nice either. And VSCode file explorer fails to understand those anyway.

**Comment by TylerLeonhardt** [comment]
Given our dependency on ripgrep, I don't think we can do anything here for quick open or search, unfortunately and I don't think we wanna be in the business of re-implementing what ripgrep offers.

Since the explorer side is tracked with https://github.com/microsoft/vscode/pull/158907 I think I will close this as `upstream` and `out of scope`

**Comment by memeplex** [comment]
I agree, thank you for taking a look at it anyway!
