### ISSUE TITLE
How to remove the top-left structure guide line?

### ISSUE THREAD

**Issue by TanvirArjel** [microsoft/vscode#156050]
How to remove the following top-left structure guild line?

![image](https://user-images.githubusercontent.com/14342773/180611797-adbbef97-e30a-4ac1-92e6-aa8be334c6af.png)

Thanks!

**Comment by gjsjohnmurray** [comment]
Change the `editor.guides.bracketPairs` and/or `editor.guides.bracketPairsHorizontal` settings.

**Comment by TanvirArjel** [comment]
@gjsjohnmurray Thanks a lot! `editor.guides.bracketPairsHorizontal : false` worked.
