### ISSUE TITLE
Merge editor: really hard to know where the conflicts are

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156037]
Here I am merging `yarn.lock` from `distro` and i am having a hard time figuring out where exactly the conflicts are because there are decorations for each change:

![image](https://user-images.githubusercontent.com/900690/180597169-881b6eb0-d45d-40b3-b134-3be892ff23ec.png)

[merge.json.zip](https://github.com/microsoft/vscode/files/9173382/merge.json.zip)

**Comment by bpasero** [comment]
Now I figured out that there are editor actions to navigate between conflicts, so maybe the fix here would be to make the overview ruler show the conflict areas much stronger.

**Comment by eamodio** [comment]
I've had the same issue -- in my theme I've made the conflicts stand out much more, but I've still had issues seeing/getting to the remaining conflicts (might be a separate issue)

**Comment by hediet** [comment]
I created https://github.com/microsoft/vscode/pull/156482 to address this.

There are no diff highlights and no minimap-decorations for non-conflicting changes anymore:

![image](https://user-images.githubusercontent.com/2931520/181322636-748291ce-5f34-4770-8374-d79cc98fc1e1.png)

Before:

![image](https://user-images.githubusercontent.com/2931520/181325192-87ba33a7-d97d-44ab-904d-bef301577505.png)
