### ISSUE TITLE
offline install and "last disk of Multi-Volume set"

### ISSUE THREAD

**Issue by nancym** [Microsoft/vscode#15606]
I'm installing VSCodeSetup-1.7.1.exe on a Windows 10 device that is not connected to the internet. Lots of files were installed and now I'm looking at a dialog box that is titled ***Compressed (zipped) Folders***

and says this:

> Please insert the last disk of the Multi-Volume set and click OK to coninue.

What file(s) do I need to download on another device and then copy to this offline device to completely install VS Code 1.7.1?

Thank you.

**Comment by joaomoreno** [comment]
Can you show us a screenshot of that window?

**Comment by nancym** [comment]
Here's a screenshot. When it happened the smaller window was covering the largerone.

![screenshot-multi-volume-set](https://cloud.githubusercontent.com/assets/161490/20399147/c2ef3098-aca4-11e6-8a44-d8b1d5ab6b49.png)

I'm using:

> Windows 10 Home Insider Preview 
> Evaluation copy. Build 14965.rs_prerelease.161104-1700

Thank you for looking into this.

**Comment by joaomoreno** [comment]
Does this always reproduce? If you redownload and reinstall, does it still happen?

**Comment by nancym** [comment]
To test this, I put the USB stick into my Windows 7 device and almost immediately (before trying to run VSCodeSetup) got the ***Compressed (zipped) Folders*** error message. That was my first clue that this message has nothing to do with VSCodeSetup. Here's info about the error:

http://answers.microsoft.com/en-us/windows/forum/windows_7-files/stopfix-please-insert-the-last-disk-of-the-multi/4f45fa10-0908-4acb-a074-d564d69716c5

It seems that my USB stick probably has a corrupted .zip file on it. It's weird that on my Windows 10 device I didn't see that error message until the moment that VSCode was almost done installing. My guess is that this is a Windows 7/10 bug or misleading error message and doesn't have anything to do with VSCode.

Thanks for you help. VSCode 1.7.1 seems to be running fine on both my Windows 10 and Windows 7 devices, which I'm mostly using offline at the moment.

**Comment by joaomoreno** [comment]
Thanks for letting us know.
