### ISSUE TITLE
Multi root: json.schema setting relative url doesnt get resolved to folder

### ISSUE THREAD

**Issue by Shelim** [microsoft/vscode#156006]
Type: <b>Bug</b>

1. In non multi root mode create .vscode/settings.json file with following content:

```
{
    "json.schemas": [  {
            "fileMatch": [
                "Example/*.json",
            ], "url": "./Schema/Json.schema.json"
       }
    ]
}
```
Observe that schema is correctly applied to any json file in the workspace.

2. Add folder to workspace to make it multi root

Observe that shema is no longer applied to json files in the same folder as in step 1.

Expected result: schema should be applied based on the folder in mutli root environment.

Additional info:
 - There was a bug reported in 2017 for the same issue: #33453

VS Code version: Code - Insiders 1.70.0-insider (13ba7bb446a638d37ebccb1a7d74e31c32bb9790, 2022-07-22T05:17:00.353Z)
OS version: Windows_NT x64 10.0.19044
Modes:

Extensions disabled

**Comment by ajcool2k** [comment]
@Shelim it could be #147865

**Comment by Shelim** [comment]
Yes, it is most likely a duplicate of that issue, thank you. Too bad the problem is known since April and it is still in the backlog...

**Comment by GabenGar** [comment]
Is it? The latest version turned it back for me.

**Comment by Shelim** [comment]
> Is it? The latest version turned it back for me.
@GabenGar 
Just updated to vscode-insiders to 1.71 and confirm that the issue is resolved. Thank you!
