### ISSUE TITLE
Add Find Command To Public Command API

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#15607]
- VSCode Version: 1.8

**Request**
Add a command that opens the workspace file search control and pre-populates some of the fields (optionally triggering a search as well).

**Reason**
I wanted to put together a simple extension to do a file search only within the directory of the currently active file. To implement this in a way that is consistent with the rest of vscode, I see using a command that pop ups the find control and prepopualtes the 'files to include' section. To my knowledge, no such command currently exists. There are many other use cases for triggering searches programmatically as well.

**Comment by alefragnani** [comment]
That's great! And I would suggest one more thing: 

* Suggest the _selected text_ (if any) as _search for_. 

This is handy if you want to find other occurences of the text that you are editing/viewing.

**Comment by mjbvz** [comment]
Closing as the original "find in folder" command has since been implemented in VS Code core
