### ISSUE TITLE
Screen crash

### ISSUE THREAD

**Issue by ToothlessMonkey** [microsoft/vscode#156027]
Issue Type: <b>Bug</b>

Regular screen crashes since last few updates. They are random and often when switching applications or hover over them.
(viow color theme is an excluded extension)
edit- recently when file deletion task was completed in the background, it crashed

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000,    Windows 11 Home Single Language,21H2,22000.652
Restricted Mode: No

[image](https://github.com/ToothlessMonkey/images/blob/main/Screenshot%20(11).png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.86GB (7.63GB free)|
|Process Argv|--crash-reporter-id 215b0ea7-3221-48fb-a29b-c5dc37e12247|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.8.6
postcss|css|1.0.9
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.5.0
material-icon-theme|PKi|4.19.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30532337

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226
