### ISSUE TITLE
Debug console fails to auto-scroll

### ISSUE THREAD

**Issue by chaindrive** [microsoft/vscode#156073]
Issue Type: <b>Bug</b>

Since the latest update, console prints from NodeJS may or may not trigger the scroll-to-end on the Debug Console. Clearing the console allows it to scroll to end for about 10s, then it gets stuck on a line.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3410)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.94GB (10.40GB free)|
|Process Argv|--crash-reporter-id 34faf259-14be-4213-8adc-0bcd0485d5cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|2.0.3
vscode-custom-css|be5|6.0.2
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
jsx|Hen|1.3.0
beautify|Hoo|1.5.0
vscode-types-for-adobe|il-|0.1.1
nims|Jun|0.1.2
vscode-codemetrics|kis|1.24.0
regionfolder|map|1.0.17
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.4
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
azure-account|ms-|0.11.0
vsliveshare|ms-|1.0.5641
vsliveshare-audio|ms-|0.1.91
debugger-for-chrome|msj|4.13.0
vscode-for-node-js-development-pack|nod|2.0.1
code-settings-sync|Sha|3.4.3
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
841h4636:30532337

```

</details>

**Comment by roblourens** [comment]
Have discussed this in https://github.com/microsoft/vscode/issues/117674, but I have not seen this and am in need of details and repro steps if you can provide more info
