### ISSUE TITLE
Switching editor loses scroll (caret) position

### ISSUE THREAD

**Issue by cnshenj** [Microsoft/vscode#15601]
- VSCode Version: 1.7.1
- OS Version: Windows 10 1607

Steps to Reproduce:

1. Click an extension in "Extensions" side bar so its description is opened in an editor
  Or, click a changed file in "Git" side bar to open the diff in an editor
2. Double click the tab so the editor is kept open
3. Scroll down to some location that is not the top. Or move caret down.
4. Switch to a different editor, then switch back. The scroll position is lost and the editor shows the top of the content

**Comment by ramya-rao-a** [comment]
Doesn't happen on other normal editors.
Only happens in a diff editor, markdown preview and the extension details view

**Comment by alexandrudima** [comment]
@aeschli Is this issue sharing the same root cause as the folding restore view state issue?

**Comment by aeschli** [comment]
I don't think so. The other issue was only with normal editors that have at least one section folded.

**Comment by bpasero** [comment]
This is using the <webview> and I do not think we do store any view state for those editors.

**Comment by cnshenj** [comment]
This issue is partially fixed. 1.13 now restore the scroll position of webview (e.g. Release Notes) when switching back. But it does this in 3 steps: 1) show an empty tab; 2) render the content assuming the scroll position is content top; 3) jump to the previous scroll position.
So it works, but in a way that looks like screen flickering.

**Comment by mjbvz** [comment]
We're tracking restore of the scroll position in the extension editor with #27498

The jitter in restoring the scroll position is tracked by #27524 . The root cause is that we set the scroll position after the `onload` event is fired but we show the page content before this after the `DomContentLoaded` event
