### ISSUE TITLE
The shell script regex color rendering is wrong, causing other lines to also display the wrong color

### ISSUE THREAD

**Issue by mylovesaber** [microsoft/vscode#156054]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:
版本(version?): 1.69.2 (system setup)
提交(commit id?): 3b889b090b5ad5793f524b5d1d39fda662b96a2a
日期(date?): 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

- disable all the plugins
- change different themes

Shell code(Test if ipv4 address is valid):
```shell
ERROR_IP_ADDRESS=()
for i in "${IP_ADDRESS[@]}"; do
    if [[ ! "${i}" =~ ^[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]\.[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]$ ]]; then
        ERROR_IP_ADDRESS+=("$i")
    fi
    if [[ ! "${i}" =~ ^[0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5]\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then
        ERROR_IP_ADDRESS+=("$i")
    fi
    if [[ ! "${i}" =~ ^([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then
        ERROR_IP_ADDRESS+=("$i")
    fi
    if [[ ! "${i}" =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.)([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then
        ERROR_IP_ADDRESS+=("$i")
    fi
    if [[ ! "${i}" =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then
        ERROR_IP_ADDRESS+=("$i")
    fi
    for j in "${ERROR_NODE_ALIAS[@]}"; do  # test if this line color is normal
        echo "$j"                          # test if this line color is normal
    done                                   # test if this line color is normal. They're normal
done
```

Picture(a little mistake in it and fixed in the code above. * shouldn't exist.):
![image](https://user-images.githubusercontent.com/36480362/180614477-ada0a5f9-7e13-44e4-adef-8e503e00149c.png)

Terminal output:
```bash
root@108 ~ $ i="1.1.1.9999"
root@108 ~ $ if [[ ! "${i}" =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then echo no;fi
no
root@108 ~ $ i="1.1.1.99"
root@108 ~ $ if [[ ! "${i}" =~ ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$ ]]; then echo no;fi
root@108 ~ $ 
```

**Comment by mylovesaber** [comment]
Wait a minute. I'm doing more test....

**Comment by alexr00** [comment]
Minimal repro:

```sh
x = ^(([0]))$
```

**Comment by alexr00** [comment]
The repository that we get our current shell script syntax highlighting grammar from is no longer maintained. We are considering adopting a new shell script grammar here: https://github.com/microsoft/vscode/issues/77675

Duping to https://github.com/microsoft/vscode/issues/77675 so that we know to check if this issue is fixed if we adopt a new grammar.
