### ISSUE TITLE
Clicking failed mocha test file (via VSC debug) doesn't open the file.

### ISSUE THREAD

**Issue by vlod** [Microsoft/vscode#15605]
- VSCode Version: 1.7.1
- OS Version: macOS 10.12.1

Steps to Reproduce:

See project: https://github.com/vlod/hello-test

1. Click the debug icon in the left sidebar, make sure 'Test' is selected and hit run 
2. Clicking on the failed error: 'hello-test.js:7:24' should open the file.

Above github project has screenshots.

**Comment by isidorn** [comment]
@vlod thanks you for the great reproducable steps, however can you please try this in latest vscode insiders since we have improved our relative link detection.
fyi @felixfbecker

**Comment by vlod** [comment]
Oh.. I didn't realize you had a beta-version of the VSC.

Trying it with Version 1.8.0-insider, I can confirm that my test case doesn't fail any more.

Fabulous.. thanks for all your hard work!

**Comment by isidorn** [comment]
@vlod great! You can thank @felixfbecker
