### ISSUE TITLE
Call `vscode.openFolder` command with profile/set of extensions (similar to #151301)

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#156173]
Today, the `vscode.openFolder` command only supports an `Uri` describing the folder/workspace path to be opened. 

It would be interesting to allow adding the set of extensions to be used as well, or at least the profile, just like the CLI interface created in #151301.

Thank you

**Comment by sandy081** [comment]
To verify:

- Verify passing the profile name as an argument to the `vscode.openFolder` command from the extension and make sure the folder is opened in that profile.
