### ISSUE TITLE
Server returned 407 

### ISSUE THREAD

**Issue by vipinneemamnit** [Microsoft/vscode#15619]
- VSCode Version:latest 
- OS Version:ubuntu

Steps to Reproduce:

1. it is not working behind proxy server

2. how to setup proxy of our collage in visual studio code

**Comment by ramya-rao-a** [comment]
@vipinneemamnit What exactly is not working?

Are you able to install VS Code?
Are you able to open folders and work on files in VS Code?
Are you able to install extensions?

**Comment by jrieken** [comment]
Please provide the requested information
