### ISSUE TITLE
Test Debug Sessions Picker

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156193]
Refs #153347

- [x] anyOS @isidorn
- [x] anyOS @minsa110
- [x] anyOS @connor4312

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156193%0A%0A&assignees=andreamah)

---
## Set up:
Open up a folder that has files that you can run a debugger on (e.g. Python, JS). **It would be amazing if people could try different debuggers!**

## Testing:
Start a debug session. **If you can, please run multiple debug sessions at once and/or run sessions that spawn other sessions (running sessions that spawn child sessions will usually require you to write code within the program).**

The command `Debug: Select Debug Session` should be present in the command palette when you search for it.

![image](https://user-images.githubusercontent.com/31675041/180833445-79b2d7cc-01c5-4851-93f1-f3538da7eb19.png)

Select this option and this should show your debug sessions, including any children that are attached to debugging. 

![image](https://user-images.githubusercontent.com/31675041/180833855-34fc5613-3ac9-449f-a3e4-a1ff3d8f6dae.png)

For each session in the list, the description (in slightly more faint text to the right of the name of the session) should be the parent session name if it has a parent. Also, _depending on the debugger_, there might be a section title that correspond to the group of sessions (in blue in the screenshot).

For example, the list of sessions that I showed above should correspond to this list of sessions the call stack view:

![image](https://user-images.githubusercontent.com/31675041/180833678-642fecc9-1986-456a-9ab8-e404a8a08aa6.png)

Clicking on any of the sesions should **show the debug console** in the context of that session. 

You will be able to tell that the debug console is in the correct context if the call stack has highlighted the session that you selected.

![Recording 2022-07-25 at 10 04 37](https://user-images.githubusercontent.com/31675041/180834612-10a42cef-495f-4c22-8f98-d8344ba0650e.gif)

## Extra tips: 
Note that, in order to attach the debugger to children in Python, you need to specify `"subProcess": true` in the launch config for the debug session.

![image](https://user-images.githubusercontent.com/31675041/180831618-b1d957c9-9101-442f-9b68-73fb1e644bc3.png)

To run a subprocess in Python, I used the following code: 

```python
import subprocess as sp
sp.Popen([sys.executable, "test2.py"])
```

Where `test2.py` was another file in the same directory.

**Comment by isidorn** [comment]
Nice work 👏
