### ISSUE TITLE
If No Staged Files, Changed Files are Added to Commit

### ISSUE THREAD

**Issue by atolken** [Microsoft/vscode#15613]
- VSCode Version: 1.71
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. make changes / have changed files
2. do not stage any files
3. write commit message
4. submit commit

problem: all files that were changed (even though none were staged) are added to the commit.
expected: if no files are staged, the commit will not add any files (similar to other git tools).

**Comment by siegebell** [comment]
This behavior is likely intentional, but after many revert-last-commit operations, I've come to really hate it.

**Comment by joaomoreno** [comment]
This is intended.

- when there are no changes, nothing happens
- when there are no staged changes, all working tree changes are committed
- when there are staged changes, only those are committed

Would you like a setting to disable that?

**Comment by atolken** [comment]
I would definitely like a setting to disable that, please.

**Comment by MaxfieldWalker** [comment]
In the case of Visual Studio, when there are no staged changes, but some changes, the content of the commit button comes "Commit All". So, user can know all changes will be committed even no changes staged.

vscode doesn't have button to commit (use ctrl+Enter instead), and it is difficult to know what happens when commit done.

I would like to add a setting to disable the behavior when no changes staged, or add some ingenuity to let user know what will happen.


![image](https://cloud.githubusercontent.com/assets/7913793/20626697/bfadc03c-b35e-11e6-91b1-f6fb574e9c56.png)

![image](https://cloud.githubusercontent.com/assets/7913793/20626896/fcd0bb12-b35f-11e6-9ea7-21971c2d7162.png)

**Comment by seesemichaelj** [comment]
Despite the fact that this is easily revertible after an accidental mass commit, the git CLI does not allow you to commit without staged files.

If it's not a setting that disables this functionality, then if there are no staged files, prompt the user that you cannot commit without staged changes and ask if the user would like to stage and commit all changes (with the default option to be No).

Forcing the user to look at the files and intentionally stage them is good practice.

**Comment by mozram** [comment]
Any progress on this issue? As @siegebell said before, I had to revert commit many times already as I either accidentally pressed CTRL+S or forgot to stage file. I'm hating it now.

@seesemichaelj suggestion is very good actually.

**Comment by joaomoreno** [comment]
We're gonna go with the setting. Any one care to contribute a PR?

**Comment by seesemichaelj** [comment]
I'll give this a shot

**Comment by ashirley** [comment]
I have been looking at this and related issues (before I saw you were too @seesemichaelj , sorry!) and have attempted a solution from a slightly different direction and I have raised PR #25855. I think there is value in trying to merge our two solutions which I will have a look at tomorrow if I can.

**Comment by joaomoreno** [comment]
Sorry @ashirley, I've closed your PR. I really liked @seesemichaelj's fix, it's simpler to understand and maintain.

**Comment by joaomoreno** [comment]
Fixed by #25364

**Comment by ashirley** [comment]
No worries. I am a bit concerned that when you press "Always", it changes a file in the directory and then immediately commits it. I wouldn't be expecting this as a user and would want a chance to add the (potentially new) file to .gitignore. Even if I did want to commit this config change, I would want it in a separate commit.

**Comment by seesemichaelj** [comment]
@ashirley I agree and verified what you said. I have opened Issue #26169 to address this

**Comment by joaomoreno** [comment]
Good detective work @seesemichaelj 😉
