### ISSUE TITLE
Test sharing notebook vscode.dev links

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#156153]
Refs: https://github.com/microsoft/vscode/issues/153944

- [x] anyOS @misolori
- [x] anyOS @bpasero

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156153%0A%0A&assignees=alexr00)

---

1. Open a notebook that's in a GitHub repository.
2. Right click in a cell editor -> Share -> Copy vscode.dev Link
3. Paste the link into your browser and verify that the correct notebook cell is shown

Repeat with a different notebook.

**Comment by rebornix** [comment]
Originally from @bpasero 

> shouldn’t the link point to [insiders.vscode.dev](http://insiders.vscode.dev/) when I copy it from insiders

👍 and we got similar feedback from redmond's standup.

**Comment by misolori** [comment]
Maybe I'm doing something wrong but I don't see a "Share" menu item in the notebook editor context menu?

<img width="1248" alt="CleanShot 2022-07-27 at 15 10 28@2x" src="https://user-images.githubusercontent.com/35271042/181381324-73f3f44e-1e38-4c0b-907f-d1225ebfe3fa.png">

**Comment by bpasero** [comment]
@misolori share from desktop app only
