### ISSUE TITLE
Task names are displayed incorrectly

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode#156166]
Type: <b>Bug</b>

Originally from https://github.com/microsoft/vscode-docker/issues/3580.

When executing a new task, the displayed name is incorrect. Potentially related to #154146?

VS Code version: Code - Insiders 1.70.0-insider (3cbf3063281410d21951877eb628551809d70c6b, 2022-07-25T05:27:52.229Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|126.84GB (110.05GB free)|
|Process Argv|--crash-reporter-id a639fe75-6727-46d4-bc6c-acdb3cb6366a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-eslint|dba|2.2.6
vscode-docker|ms-|1.22.5-alpha
remote-containers|ms-|0.243.0
azure-account|ms-|0.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
841h4636:30532337

```

</details>

**Comment by meganrogge** [comment]
yes looks like the same as #154146

**Comment by bwateratmsft** [comment]
The Docker extension is not using the task name change emitter, though. Previously for all our tasks, it was just displaying the task type.

**Comment by bwateratmsft** [comment]
@meganrogge are you sure this is the same as #154146? The more I look into it, the less it seems so. In the original bug, the user ran one task that executes as a `CustomExecution`--this one displays its task name correctly--and then runs another task that executes as a `ShellExecution`--and this one keeps the title from the `CustomExecution`.

**Comment by meganrogge** [comment]
@bwateratmsft what is it displaying if not the task type?

**Comment by Tyriar** [comment]
@meganrogge just a guess; could this be only a problem on reconnected terminals where we restore the title but not the fact that the title source was "API", so title sequences override it?

**Comment by bwateratmsft** [comment]
> @bwateratmsft what is it displaying if not the task type?

It was showing the name of the previous task, instead of the new one.

Actual:
![image](https://user-images.githubusercontent.com/36966225/182620291-a8f5b343-86f8-4f94-9a9f-50311a8e52ca.png)

Expected:
![image](https://user-images.githubusercontent.com/36966225/182620323-88ce2b67-a761-4e7d-a518-16a020ce7a5d.png)

**Comment by jscissr** [comment]
I have the same problem. Here is a simple way to reproduce it:
Create a file `.vscode/tasks.json` with the following content in a new folder:
```
{
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Task 1",
      "type": "shell",
      "command": "echo Hello 1",
      "problemMatcher": []
    },
    {
      "label": "Task 2",
      "type": "shell",
      "command": "echo Hello 2",
      "problemMatcher": []
    }
  ]
}
```
Then open the folder in vscode, and run task 1, then task 2. This is the output:
```
 *  Executing task: echo Hello 1 

Hello 1
 *  Terminal will be reused by tasks, press any key to close it. 

 *  Executing task: echo Hello 1 

Hello 2
 *  Terminal will be reused by tasks, press any key to close it. 
 ```

It looks like this regression was caused by https://github.com/microsoft/vscode/issues/154513 @Tyriar.

https://github.com/microsoft/vscode/blob/9e0db45b1ede5be7f7be300328a6baebbb21f967/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1671
https://github.com/microsoft/vscode/blob/9e0db45b1ede5be7f7be300328a6baebbb21f967/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L1698

`_writeInitialText` is called before the line `this._shellLaunchConfig = shell;`, so it uses the old `initialText`.
