### ISSUE TITLE
[Feature request]Hot reload for extensions

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#15614]
- VSCode Version: Code - Insiders 1.8.0-insider (3408691c13470346a119141e57aa74b302464a4a, 2016-11-14T07:05:07.232Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|python|donjayamanne|0.5.2|
|tslint|eg2|0.5.40|
|Go|lukehoban|0.6.49|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.2|

---
In current version, after install extension must restart or reload window. So I suggest hot reload for extension and no need reload window. Just like atom does.

**Comment by schmuli** [comment]
Actually, recently Atom has started recommending reloading the window after making extension changes, especially when updating an existing extension.

This has something to do with how difficult it is to remove JS that is already loaded in the VM.

If anything, to make life easier, I would ask that there just be one Reload button, no matter how many extensions have been added/updated/removed. Currently, each extension has its own Reload button, and clicking it will show a popup message for that specific extension, even though reloading will automatically affect all updated extensions.

**Comment by joaomoreno** [comment]
#5675
