### ISSUE TITLE
HTML <p> tag does not let pasted text be inside it

### ISSUE THREAD

**Issue by WadieBenabdouh** [microsoft/vscode#156103]
Issue Type: <b>Bug</b>

So I am trying to paste text into a `<p>` tag, once I hit CTRL+V  the code gets pasted above the `<p>` tag.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3437U CPU @ 1.90GHz (4 x 2395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.87GB (0.93GB free)|
|Process Argv|--crash-reporter-id 5307afa4-26ed-404d-9f63-6d54fa8ef956|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aeschli** [comment]
I can't reproduce
- open https://vscode.dev
- create a HTML file with a `<p>` tag.
- Copy some text, place the curser after the `p` and paste
![htmlpaste](https://user-images.githubusercontent.com/6461412/180736109-db7d3e3a-7b91-4a5d-967f-b60c515beaa5.gif)


Can you provide similar steps?

**Comment by WadieBenabdouh** [comment]
Hi thanks for reaching back, the bug has disappeared after restarting VSCode and now I can paste anything inside a `<p>``` tag with no issues.``

**Comment by WadieBenabdouh** [comment]
Fixed
