### ISSUE TITLE
Test: Sticky Scroll

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#156175]
Refs: https://github.com/microsoft/vscode/issues/26757

- [x] any OS @bpasero
- [x] any OS @andreamah

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156175%0A%0A&assignees=aiday-mar)

---

It is possible to enable the sticky scroll and see in which class/method/constructor/interface/function you are in. You can also click on the sticky item to jump to the line.

- Go to the settings and enable sticky scroll under `Editor > Sticky Scroll : Enable`
- Open a file (so far I only tested on JavaScript files, so it would be a good idea to test other file types)
- Scroll the file and check that the beginning lines corresponding to class/method/constructor/interface/function stick to the top of the editor correctly on the scrolling event, and appear and disappear smoothly. 
- Check the redirection on the onclick is correct.  

Any feedback is greatly appreciated.

**Note** : Since the build, the code has been updated outside of the merge, in my personal repo, in an attempt to solve the following.

- Incorrect indentation in the files. The indentation takes into account both tabs and spaces now.

This is something I will continue working on this week. If interested, my updated personal repo is here : `https://github.com/aiday-mar/vscode/tree/aiday/semanticScroll` under the branch `aiday/semanticScroll`

**Comment by bpasero** [comment]
Nice 👍

**Comment by andreamah** [comment]
Awesome job! This is such a cool feature 😁

**Comment by aiday-mar** [comment]
Thanks ! I will be working on solving the bugs.

**Comment by mjbvz** [comment]
Nice work! I opened a few issues from testing this. I think #156606  and #156616  should be candidates to fix in this iteration

**Comment by MohanVallivedu** [comment]
This looks like a cool feature. I cannot find this option Sticky Scroll in my VS Code (version: 1.69.2). How do I find and test this feature?

**Comment by gjsjohnmurray** [comment]
It's in Insiders (1.70) and is expected to reach the Stable version by the end of next week.

**Comment by aiday-mar** [comment]
Thanks for the feedback! I'll make sure to work on fixing the bugs

**Comment by mtsh1000** [comment]
Thanks for this cool feature! I think this should also work for: if, for and switch blocks or even unnamed blocks like just {...} js objects etc.

**Comment by Jacobify** [comment]
hi there, i just updated my editor , but the sticky scroll does not work on any file i have in my projects ( .js and .cs files and etc )

**Comment by danielgroen** [comment]
Also for me! .vue files don't work for me. It got stuck on the `<template>`

**Comment by Jacobify** [comment]
> Also for me! .vue files don't work for me. It got stuck on the `<template>`

same thing for me. thanks for mentioning your problem

**Comment by Jacobify** [comment]
@aiday-mar can this issue be rechecked for .vue files too ? so that it works properly ?

**Comment by gjsjohnmurray** [comment]
@Jacobify when the next Insiders appears a few hours from now please re-check your case. If the problem remains I suggest you open a new issue (ideally via the Report Problem option on the Help menu) and paste into it some repro code.

**Comment by danielgroen** [comment]
@gjsjohnmurray i still see it hanging on the `<template>` in the .vue files. I updated my vscode to the newest version but without succes. i'll open a  new issue

**Comment by danielgroen** [comment]
Snap i am on 1.70.1 stable. How can i  update to 1.71? @gjsjohnmurray

**Comment by mattheworris** [comment]
This is an awesome feature. 

Any plans to add C++ support? 

It works for me in .js files, but not .cpp.
I have VIM key bindings enabled, running on Windows, remote SSH to a linux server, with github co-pilot.

Version: 1.70.1 (user setup)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by gjsjohnmurray** [comment]
@mattheworris which C++ extensions have you installed? You need one that implements `DocumentSymbolProvider`. Evidence you've got that is that VS Code's Outline view gets populated for your .cpp files.

**Comment by mattheworris** [comment]
@gjsjohnmurray  I do have Outline view populated for my cpp files. Sticky scroll still works for python and js files.
Here's a list of my extensions for this workspace.

> code --list-extensions
Extensions installed on SSH: 10.XXX.XXX.XXX:
ChaunceyKiwi.json-tree-view
cschlosser.doxdocgen
eamodio.gitlens
GitHub.copilot
GitHub.copilot-labs
jeff-hykin.better-cpp-syntax
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
twxs.cmake

**Comment by gjsjohnmurray** [comment]
Please re-test with [Insiders edition](https://code.visualstudio.com/insiders), which you can safely install alongside the regular edition (aka Stable).

**Comment by Jacobify** [comment]
> Please re-test with [Insiders edition](https://code.visualstudio.com/insiders), which you can safely install alongside the regular edition (aka Stable). @gjsjohnmurray 

i downloaded the insiders edition and i noticed something. As seen below , some times when i am scrolling the upper part of sticky scroll is exactly duplicated.

![image](https://user-images.githubusercontent.com/39615077/184529471-1b11b4e5-2a62-44de-b9a1-d5f5cb32fe1e.png)

**Comment by danielgroen** [comment]
> > Please re-test with [Insiders edition](https://code.visualstudio.com/insiders), which you can safely install alongside the regular edition (aka Stable). @gjsjohnmurray 
> 
> i downloaded the insiders edition and i noticed something. As seen below , some times when i am scrolling the upper part of sticky scroll is exactly duplicated.
> 
> ![1401-05-23 13_19_40-index vue - mdm (Workspace) - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/39615077/184529557-5ba9633f-1e58-4b89-8360-ad8fc4a6624d.png)
> 
> 
> 

This is because you have volar and the newer extension installed. If you remove volar it works properly

**Comment by Jacobify** [comment]
> > > Please re-test with [Insiders edition](https://code.visualstudio.com/insiders), which you can safely install alongside the regular edition (aka Stable). @gjsjohnmurray
> > 
> > 
> > i downloaded the insiders edition and i noticed something. As seen below , some times when i am scrolling the upper part of sticky scroll is exactly duplicated.
> > ![1401-05-23 13_19_40-index vue - mdm (Workspace) - Visual Studio Code - Insiders](https://user-images.githubusercontent.com/39615077/184529557-5ba9633f-1e58-4b89-8360-ad8fc4a6624d.png)
> 
> This is because you have volar and the newer extension installed. If you remove volar it works properly

you are right , thanks for clearing it for me.

**Comment by mattheworris** [comment]
> Please re-test with [Insiders edition](https://code.visualstudio.com/insiders), which you can safely install alongside the regular edition (aka Stable).

Thanks, it is working with Insiders edition.
