### ISSUE TITLE
merge editor fails to open macos ventura vs code insiders

### ISSUE THREAD

**Issue by alexanderniebuhr** [microsoft/vscode#156121]
Type: <b>Bug</b>

Doing a rebase and got merge changes with conflicts.
With the latest insider update the merge editor does not open in the editor pane. Nothing happens. Once I disable the merge editor the file does open without any issue. Happens with all extensions disabled as well.

VS Code version: Code - Insiders 1.70.0-insider (3cbf3063281410d21951877eb628551809d70c6b, 2022-07-25T05:41:37.019Z)
OS version: Darwin arm64 22.0.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 5|
|Memory (System)|64.00GB (4.72GB free)|
|Process Argv|--crash-reporter-id 092694b8-f2ad-4473-8608-b513d685cc96|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30525688
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30532338

```

</details>

**Comment by alexanderniebuhr** [comment]
https://user-images.githubusercontent.com/45965090/180733657-9ed392dc-d66a-4f43-92ab-e9b73976f593.mov

**Comment by jrieken** [comment]
Please retry with latest insiders and if this still reproduces provide exact steps

**Comment by alexanderniebuhr** [comment]
latest insider version seems to work for now.
