### ISSUE TITLE
Test "Go To Most Recently Failed Cell"

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156194]
Refs #142898

- [x] macOS @IanMatthewHuff
- [x] linux @gregvanl
- [x] windows @hediet

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156194%0A%0A&assignees=andreamah)

---
## Set up:
Open up a notebook where you can run cells that run into errors (e.g. a Jupyter notebook).

## Testing:
1. Intentionally insert code that will trigger a runtime error into one of the cells. 
2. Run the cell. There should be a button on the toolbar to go to the most recently failed cell. It will say **"Go To"** and have an **error icon**. There should also be a command called `Notebook: Go to Most Recently Failed Cell`.

![image](https://user-images.githubusercontent.com/31675041/180836385-dddde563-b395-4de8-ac12-cc879eb23f52.png)

![image](https://user-images.githubusercontent.com/31675041/180836544-886731a8-ffc2-480e-a125-2518f7f1064b.png)

Note that the "Go To" button with the loading icon is actually a **different** button that is only visible when the cell is running. The button that says "Go To" with an error icon should replace it if the cell runs into an error. Otherwise, neither button should be visible.

![Recording 2022-07-25 at 10 20 02](https://user-images.githubusercontent.com/31675041/180837046-b1da17da-dd06-44a4-b092-e0f18af1ed06.gif)

3. Try scrolling away from the cell that you just ran and pressing the button. The button should always take you to the cell that you ran. Running the `Notebook: Go to Most Recently Failed Cell` command should also do the same thing 

![Recording 2022-07-25 at 10 22 20](https://user-images.githubusercontent.com/31675041/180837458-e6c6c248-c65d-4468-9da9-315dc8e5b1ea.gif)

4. Now, run a cell that should run successfully. The button and command mentioned above should not be there.

The main use case for this is for if you run your whole notebook and run into an error in the middle somewhere. This command/button will take you to the cell that failed and stopped the run so that you don't need to search through the whole notebook. 

Try inserting error-inducing code in a cell in the middle of your notebook, clicking the `Run All` button in the toolbar, and then using the command/button to navigate to the failed cell. The notebook should jump to the failed cell correctly.

![Recording 2022-07-11 at 16 02 11](https://user-images.githubusercontent.com/31675041/178373158-db24523a-d136-4ca7-b945-5b5757cbe3e8.gif)

**Comment by IanMatthewHuff** [comment]
Nice! I can already see using this in my notebook dogfooding. Great work @andreamah . I tried a few extra things to break it (checking when the command palette command showed up, adding multiple different error cells, ect...) and didn't get any behavior that I didn't like.
