### ISSUE TITLE
Test Search Mutiselect

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156196]
Refs #47166

- [x] macOS @alexdima
- [x] linux @connor4312
- [x] windows @brettcannon

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156196%0A%0A&assignees=andreamah)

---
## Set up:
Open a workspace with files that you can search through (one that you probably don't mind editing).

## Testing:
Search through a word that has multiple instances within a file and/or across files. Multi-select search results (either by holding down `ctrl`/`cmd` and selecting your desired items or using `shift` and selecting a range) and perform actions on them. 

Selecting remove for one item within the selection should perform a remove for all of them. The same should work for replace, even if you've selected different types of items (selecting some single instances and some files). You should be able to do this using the action bar buttons or the context menu.

Otherwise, if you perform an action for something outside of the selection, it should just ignore what you have selected and perform as expected.

![Recording 2022-07-11 at 12 53 13](https://user-images.githubusercontent.com/31675041/178347470-174e2b08-307e-47ac-a0c2-0a726738b5c5.gif)

Also, try using both the context menu and action bar to perform your actions.

action bar buttons:
![image](https://user-images.githubusercontent.com/31675041/180846885-61cd3bdc-fad9-4920-ac79-c9b7057d297b.png)

context menu (by right-clicking):
![image](https://user-images.githubusercontent.com/31675041/180846956-1aeaf989-9f65-4e08-9976-62dac1de9a10.png)

### Notes about focus after replacing/removing
Also, make sure that the focus jumps to the right place once you've performed your action. Replacing and removing a group will move to the next item that is the same type as the last in the selection (ie: if the bottom-most thing that you selected was a filename, then the focus moves to the next filename).

When replacing something outside of your multi-selection, replacing the item will make the focus and selection jump to the next item after the item you replaced. 

[![Image from Gyazo](https://i.gyazo.com/470371b752718e17a4785dbfa47fffa8.gif)](https://gyazo.com/470371b752718e17a4785dbfa47fffa8)

Removing something outside of your multi-selection will not change your focus or selection.

[![Image from Gyazo](https://i.gyazo.com/6258670a40153d0ea0a2b6859f552186.gif)](https://gyazo.com/6258670a40153d0ea0a2b6859f552186)

You should also be able to use arrow keys and see the replace preview to the side, even if multiselect is present.

[![Image from Gyazo](https://i.gyazo.com/0ec8dbf38f2702130a74b7c007181156.gif)](https://gyazo.com/0ec8dbf38f2702130a74b7c007181156)
Overall, search should work with multi-select in the same way as regular single-selection.

**Comment by Eskibear** [comment]
Multiselect in Search works well! One feedback is that I cannot batch undo the replacement in different files. Imagine I replaced multiple files with wrong text, it's painful for me to undo the changes one by one.
