### ISSUE TITLE
Test: Fold selection

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#156161]
Refs: https://github.com/microsoft/vscode/issues/18805

- [x] anyOS @rzhao271
- [x] anyOS @aiday-mar

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156161%0A%0A&assignees=aeschli)

---

You can now create a manual (user defined) folding range
- select a range, use the `Create Manual Folding Range From Selection` command
- the selected range will become a (collapsed) folding range and get a special fold marker (ellipses)
- if it overlaps with the provider folded ranges, the provider folded ranges will be ignored. E.g. you can create a user defined folding range over two other folding ranges
- it can be expanded and collapsed again
- the manual range can be removed with the command `Remove Manual Folding Range`
- the manual folding range is persisted across editor close and reopen

**Comment by Eldair** [comment]
Remove Manual Folding Range doesn't work
