### ISSUE TITLE
Hygiene & Layering are no longer required for merging PR

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156114]
It was possible to merge https://github.com/microsoft/vscode/pull/155502 even though it had a red check:

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/900690/180702884-a66ff089-9304-488b-9123-5ee44bc1a3aa.png">

**Comment by lszomoru** [comment]
🤔 @alexdima, @joaomoreno, have we made any changes to the branch policy?

**Comment by alexdima** [comment]
This is unchecked but I can't say who unchecked it or why:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/5047891/180782014-57df07ef-1e54-4967-abe5-8b77855d5c88.png">

**Comment by bpasero** [comment]
Can we turn it back on at least for tomorrows testing day?

**Comment by alexdima** [comment]
> Can we turn it back on at least for tomorrows testing day?

Sorry I didn't update this issue. `Code - OSS` being a required check is back on

**Comment by bpasero** [comment]
It would also be important to have the GH workflow checks be required, that was the original issue about.

**Comment by lszomoru** [comment]
The `Code OSS` pipeline runs the same compile/hygiene/layering check as the product build.

**Comment by bpasero** [comment]
Ah nice! Then it would be great if we could simply remove the GH checks to have just one.

**Comment by lszomoru** [comment]
That is the plan! We kept the GH checks running to allow us to quickly switch back to them if needed.

**Comment by joaomoreno** [comment]
This is fixed now.
