### ISSUE TITLE
`workbench.files.action.showActiveFileInExplorer` not working when Explorer is hidden

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#156112]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:32:39.000Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

Steps to Reproduce:

1. Open any file that's listed somewhere in the Explorer view
2. Hide Explorer view ("View: Toggle Primary Side Bar Visibility" command)
3. Run "File: Reveal Active File in Explorer View" command

Expected:

Active file is focused in Explorer view

Actual:

Primary Side Bar view opens and the whole Explorer box is focused (it has outline border)

| This (Actual)  | Instead of this (Expected) |
| ------------- | ------------- |
| ![Screen Shot 2022-07-25 at 11 52 30](https://user-images.githubusercontent.com/67437/180701132-2a759927-169d-4a3f-bb81-6884c75e5256.jpg)  | ![Screen Shot 2022-07-25 at 11 52 39](https://user-images.githubusercontent.com/67437/180701143-d221751c-0080-49a6-8798-fcc6726c338d.jpg)  |

**Comment by lramos15** [comment]
Do you have auto reveal disabled?

**Comment by vfonic** [comment]
How can I check that and/or toggle that? I couldn't find any "auto reveal" or similar command, setting, nor menu item.

If you know what to look for, you could just try it out for both cases:

1. With auto reveal enabled
2. With auto reveal disabled

This should take you less time than it would take you to reply here to tell me how to enable/disable auto reveal. In this case, I suggest you just try it yourself and report here.
