### ISSUE TITLE
Test: New tree filter UX

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#156100]
Refs: https://github.com/microsoft/vscode/issues/70646

- [x] macOS @paulacamargo25
- [x] linux @bpasero
- [x] windows @justschen

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156100%0A%0A&assignees=joaomoreno)

---

The tree type filter function has been replaced with a **find widget**. Please refer to the PR for the full details: https://github.com/microsoft/vscode/pull/152481#issue-1275131738

Please test:

1. Typing on a tree will now navigate to the next element which matches the typed string
1. Pressing <kbd>CtrlCmd-F</kbd> when focused on a list/tree should open the find widget
2. You can toggle between highlight and filter modes using the inline action inside the find widget text box
4. Changing `workbench.list.defaultFindMode` changes the default mode across all tree find widgets
3. You should be able to drag the widget to the left, so you get access to potential inline actions which might be behind it
4. Install the VIM extension and:
    1. Press <kbd>j/k</kbd> to navigate down/up
    2. Press <kbd>/</kbd> and type to navigate to the next element which matches the typed string
    3. Press <kbd>CtrlCmd-F</kbd> to open the find widget

**Comment by sanket-bhalerao** [comment]
i want to list all the .scss files in my workspace, I was hoping this feature will be helpful in that.
is there something I can try to achieve this?

**Comment by justschen** [comment]
@sanket-bhalerao Recursive works when filtering though! (Hitting the filter button on the widget will only leave folders/files open with the inclusive string)
