### ISSUE TITLE
"We are sorry for the inconvenience! Please restart Visual Studio Code." pop out every time when I open VSC

### ISSUE THREAD

**Issue by g0ne150** [Microsoft/vscode#1561]
After update VSC to 0.10.5, it crashed so many times. I use VSC nothing special, like usual.

By the way, the new JavaScript Syntax Highlighting is ...................

**Comment by bgse** [comment]
Look here, you might be having this issue:

https://github.com/Microsoft/vscode/issues/1463

**Comment by g0ne150** [comment]
@bgse  Thanks.

**Comment by bpasero** [comment]
Closing as duplicate of #1463
