### ISSUE TITLE
Git - diff editor issue when opening file from the root of the network drive

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#156172]
Copy comment from https://github.com/microsoft/vscode/issues/142842#issuecomment-1192043255

Hi, I'm also having this issue, even on the insiders build.

```
Version: 1.70.0-insider (user setup)
Commit: 62469028a6dce9db5b7c4639be7f447f4ab0e35c
Date: 2022-07-21T05:17:27.580Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044
```

I disabled all installed extensions.

Expected Git Output:
```
[2022-07-21T23:45:50.001Z] > git ls-tree -l HEAD -- Z:\custom.php [86ms]
[2022-07-21T23:45:50.009Z] > git show --textconv HEAD:custom.php [99ms]
```

Actual Git Output:
```
[2022-07-21T23:45:50.001Z] > git ls-tree -l HEAD -- Z:\custom.php [86ms]
[2022-07-21T23:45:50.009Z] > git show --textconv HEAD:ustom.php [99ms]
```

The `Z:` drive in question is a mapped network drive. Whenever I try to view the file diff, the previous file is blank. This problem applies to all files on the network drive, even ones in subdirectories. Let me know if there's any other information I should provide.

**Comment by striker4150** [comment]
Running `git rev-parse --show-toplevel` in my terminal returns the path `Z:/`.

My git version is `2.37.1.windows.1`.

**Comment by TylerLeonhardt** [comment]
@striker4150 can you give this a try in the latest Insider build and let us know if it's working for you?

**Comment by striker4150** [comment]
Yes, the diff editor works in the latest insider build. Thanks for the fix!
