### ISSUE TITLE
Test: Preserve folded ranges

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#156163]
Refs: https://github.com/microsoft/vscode/issues/137890

- [x] anyOS @alexdima
- [x] anyOS @justschen

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156163%0A%0A&assignees=aeschli)

---

We now persists folded ranges, even if the folding range is no longer part of the ranges computed by a folding provider. An typical example is when the user comments out the file, starts a string literal, or creates a syntax error that makes it impossible to create all the ranges. Such folded ranges are becoming 'recovered' ranges and get a special folding marker (`...`). They are removed once the folding provider comes back with ranges at the same location.

- open a file with folding provider such as TypeScript or Python
- fold some ranges
- add an open comment token above the folded ranges: `/*`
- verify that ranges go way, except the folded ranges that are now getting a special folding marker (`...`)
- verify that can be opened and expanded like normal folding ranges
- verify that when the open comment is removed, the folding range is replaced by a regular range. If the range is collapsed it stays collapsed
- the manual folding range is persisted across editor close and reopen
- if needed, the manual range can be removed with the command `Remove Manual Folding Ranges`

**Comment by alexdima** [comment]
👏 Very nice!

**Comment by justschen** [comment]
Looks really great 🔥
