### ISSUE TITLE
Test Search File Decorations

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156195]
Refs #115741

- [x] macOS @isidorn
- [x] linux @sadasant
- [x] windows @bamurtaugh

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156195%0A%0A&assignees=andreamah)

---
## Set up:
Open up a workspace that has modified and untracked files according to git, in addition to some files that have errors or warnings.

## Testing:
Search for a word or phrase that is found in different files that are in a variety states (e.g. modified, untracked, has warnings, has errors). 

The color of the search result's file should reflect the state. The rightside icon should express its git status if it's untracked/modified/etc, in addition to the number of errors/warnings if applicable. Essentially, it should have the same decorations as in the file explorer.

It should look something like this:

![image](https://user-images.githubusercontent.com/31675041/180843847-b4f8e0f3-04e3-4855-92a0-a8f8d036a6b3.png)

Note: for me, the file explorer looks like:

![image](https://user-images.githubusercontent.com/31675041/180844096-74ca9e48-0382-4413-aff0-73b233d2da50.png)

The colors varies based on the color theme. For example, on default dark, _modified_ should be an orange/yellow color and _untracked_ should be green. Regardless, the file colors should match its color in the explorer and "Open Editors" viewlet.

**Comment by sadasant** [comment]
[Linux] Looks good to me!

<img width="1440" alt="Screen Shot 2022-07-26 at 10 43 07 AM" src="https://user-images.githubusercontent.com/417016/181036709-ccca2580-a707-47e8-bb01-92c80d8e45c4.png">

**Comment by bamurtaugh** [comment]
LGTM!
