### ISSUE TITLE
Test Comments view icons

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#156159]
Refs: https://github.com/microsoft/vscode/issues/149464

- [x] anyOS @gregvanl
- [x] anyOS @hediet

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156159%0A%0A&assignees=alexr00)

---

We changed a few icons in the Comments view. Specifically, the icons for resolved, unresolved, and discussion threads have changed:
- There is no longer a specific icon for discussions (a discussion is a comment thread with more than 1 comment). Discussions just us the resolved and unresolved icons now.
- Unresolved threads use this icon: 
![image](https://user-images.githubusercontent.com/38270282/180788535-e468282a-1e09-4f55-bacf-502bf87eb26c.png)
- Resolved threads use this icon:
![image](https://user-images.githubusercontent.com/38270282/180788624-113ca4e3-2401-4904-b653-ec92bd98512f.png)

1. Install the GitHub Pull Requests and Issues extension.
2. Open a folder with a GitHub repository that has a pull request with both resolved and unresolved comments (or create a pull request)
3. Open the Comments view. Verify that the icons are used as described above.

**Comment by hediet** [comment]
There is still this icon in the pull request pane on the left:

![image](https://user-images.githubusercontent.com/2931520/180977475-dcf627c4-c5d6-44f7-bd65-241f33038f58.png)

The icons in the "comments" pane look right though.

**Comment by alexr00** [comment]
The icon in the pull request pane is correct. Only the icons in the Comments view have changed.
