### ISSUE TITLE
Sticky scroll setting could explain what it does

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156269]
Testing #156175

![image](https://user-images.githubusercontent.com/900690/180980878-9f16f117-3606-4142-ac04-c0ffdea4a847.png)

Maybe throw in some words what sticky scroll actually means, as people might not know what it does.

**Comment by aiday-mar** [comment]
Fixed: https://github.com/microsoft/vscode/pull/156306/commits/69d1f955d1ea0cc56f63a06c3b3bbab037971475
