### ISSUE TITLE
Test: htmlLanguageParticipants contribution point

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#156200]
Refs: https://github.com/microsoft/vscode/issues/146730

- [x] anyOS @tanhakabir
- [x] anyOS @benibenj

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156200%0A%0A&assignees=aeschli)

---

The html language support now supports a new contribution point that allows other languages to participate in the html language server features.
```
   "htmlLanguageParticipants": [
      {
        "languageId": "handlebars"
      }
    ]
```
In the samp,e above, the `handlebars` language registers to get all HTML features. 

- Test that a handlebars file gets code completion, hovers...
- Set `"html.trace.server": "messages"` in the settings
- Disable the handlebar basic extension (`Handlebars Language Basics`), find it with `@builtin handlebar`
- Test that a handlebars file no longer get code completion, hovers.
- Verify that the `HTML Language Server` output view contains the log entry `Extensions have changed, restarting HTML server...`

- Open vscode repo and open the `package.json` from the handlebars extension
- Verify that you get hovers and code completions for the `htmlLanguageParticipants` contribution point

**Comment by tanhakabir** [comment]
```
"htmlLanguageParticipants": [
      {
        "languageId": "handlebars"
      }
    ]
```

This setting doesn't seem to be active for me. Is there somewhere else I should be using this instead of inside user settings?

**Comment by aeschli** [comment]
@tanhakabir It's a contribution point for 'package.json'. Example is here: https://github.com/microsoft/vscode/blob/e210bbfea4a2ccf7dc3334df162084f379a9ac48/extensions/handlebars/package.json#L40

**Comment by angelozerr** [comment]
@aeschli I tested on Windows OS, and everything works perfectly.

As you report custom message like `Extensions have changed, restarting HTML server...`, I think it could be a good idea to report when HTML language server is started/restarted the list of `htmlLanguageParticipants`. It can be helpfull for custom extension to check that the custom language is registered as htmlLanguageParticipants.

And just for your information, we use this html language participant with our Qute support https://github.com/microsoft/vscode/pull/146731#issuecomment-1193892922 and it works perfectly.

**Comment by aeschli** [comment]
Thanks @angelozerr, good suggestion. I'll add it when I'm back from vacation...
