### ISSUE TITLE
Restored tasks do not show in status bar

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156284]
I do not see the build task decoration in status bar after restart or reload:

![image](https://user-images.githubusercontent.com/900690/181001309-2110bc9d-ab11-4d96-98b4-38643f1100de.png)

**Comment by meganrogge** [comment]
Testing https://github.com/microsoft/vscode/issues/155349

**Comment by bpasero** [comment]
Slightly related, when a task spins in the terminal, it does not spin after reload.

**Comment by meganrogge** [comment]
I cannot reproduce the building indicator not being in the status bar. Can you still repro that?

Regarding the spinner, that's tracked in https://github.com/microsoft/vscode/issues/155246

**Comment by meganrogge** [comment]
Alex could repro what you're talking abt related to the status bar yesterday but can't any longer 

https://github.com/microsoft/vscode/issues/156295#issuecomment-1196438543

**Comment by bpasero** [comment]
Yes I can still reproduce.

**Comment by meganrogge** [comment]
With the vscode build task @bpasero ?

**Comment by bpasero** [comment]
Yeah, I run this command: `workbench.action.tasks.build`.

You can actually see in this video how:
* tasks still duplicate
* the status message is lost
![Recording 2022-07-29 at 06 40 05](https://user-images.githubusercontent.com/900690/181684039-e72539c4-fa4e-4d11-a96a-69dedc2e46fb.gif)

MR workspace, 2 folders.

**Comment by meganrogge** [comment]
can't repro them duplicating 😢

**Comment by bpasero** [comment]
But when you reload window while this shows:

![image](https://user-images.githubusercontent.com/900690/181807047-0391dc9d-0338-4639-9047-0d435a736c9a.png)

Does it show the same in the status bar after the window reloaded?

**Comment by meganrogge** [comment]
Not sure I understand what you mean. The VS Code build task has never worked for me - something I should probably investigate at some pt 😓 which is why I am using the xterm.js build task instead.

https://user-images.githubusercontent.com/29464607/181809882-54024e6e-f7ae-472f-8aee-8e6ba2b62c2a.mov

**Comment by meganrogge** [comment]
We are tracking the issue with the status not updating in a diff't issue already

**Comment by bpasero** [comment]
Ah ok, yeah I am only using the build task in my setup for the issues I have reported with tasks 👍

**Comment by connor4312** [comment]
This still seems present for me on web:

https://user-images.githubusercontent.com/2230985/186737984-ea6be9ba-127d-495e-a64c-364074ee8732.mp4

(disregard the long reload time--running the CLI in verbose debug mode 😛 )

**Comment by meganrogge** [comment]
@connor4312 I cannot reproduce in desktop - could you try that?

I'll open an issue about web

**Comment by meganrogge** [comment]
keeping this one about desktop

**Comment by connor4312** [comment]
This does work on desktop 🙂
