### ISSUE TITLE
Sticky scroll line height issue

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156258]
Testing #156175

It feels to me that the sticky line has not sufficient height to fully show:

![image](https://user-images.githubusercontent.com/900690/180976857-eb1c39fe-6d26-407c-8bf1-f3ac3eb7202a.png)

**Comment by bpasero** [comment]
Oh actually nevermind, the line was not fully scrolled into view. I wonder if in the case of a line not being fully scrolled into view we should already show it like a sticky line or not 🤔

**Comment by aiday-mar** [comment]
I think the idea was to make the last line appear from behind the widget in a smooth fashion as you scroll over the end of the scope. I'll talk about it with Alex.
