### ISSUE TITLE
Working directory bleed between windows when restoring terminal

### ISSUE THREAD

**Issue by lobsterkatie** [microsoft/vscode#156207]
Issue Type: <b>Bug</b>

1. Have multiple windows open, the result of having run `code someDir` on a number of different directories.
2. Have the terminal open in all of them.
3. Either restart VSCode or use the `Reload Window` command from the command palette.
4. See the reloaded terminals (sometimes, not always) get restored to the wrong working directories.

For example, I currently have the following windows open:

![image](https://user-images.githubusercontent.com/14812505/180867980-8c227a04-e745-4c5b-9a9e-77fe72377e99.png)

In the `sentry-javascript` window, I had a number of terminals open, each to a different subdirectory  of `sentry-javascript/packages`. I changed branches, intellisense got stuck refreshing itself, and so I eventually pulled up the command palette and reloaded the window. When I did, this is what the restored terminals looked like:

![image](https://user-images.githubusercontent.com/14812505/180869743-1c789176-e401-46df-80e7-ac65d769e957.png)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|29, 27, 34|
|Memory (System)|32.00GB (0.53GB free)|
|Process Argv|--crash-reporter-id b0279d3b-8393-4b25-b76f-67c5cd50b58e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
tasks-shell-input|aug|1.7.3
shifty|bme|2.0.1
multi-cursor-case-preserve|Car|1.0.5
solargraph|cas|0.23.0
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
bracket-select|chu|2.0.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
vscode-npm-source|dku|1.0.0
githistory|don|0.6.19
typescript-notebook|don|2.0.6
nunjucks-vscode-extensionpack|dou|0.0.1
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.8
code-runner|for|0.11.8
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.46.1
vscode-test-explorer|hbe|2.21.1
npm-dependency-links|her|1.2.0
background-terminal-notifier|jar|1.0.3
search-node-modules|jas|1.3.0
code-eol|jef|1.0.12
vscode-case-shifter|Jin|1.1.0
docthis|joe|0.7.1
vscode-peacock|joh|4.0.1
bracket-peek|jom|1.4.4
vscode-jest-test-adapter|kav|0.8.1
vsc-python-indent|Kev|1.17.0
yarn-lock-syntax|mar|0.1.3
template-string-converter|meg|0.6.0
xcodestrings|mhc|1.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
playwright|ms-|0.2.6
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.6
tsserver-live-reload|rbu|1.0.1
vscode-yaml|red|1.9.1
vscode-gitweblinks|red|2.7.0
vscode-sort-json|ric|1.20.0
bash-debug|rog|0.3.9
rust|rus|0.7.8
crates|ser|0.5.10
mdx|sil|0.1.0
swdc-vscode|sof|2.6.32
sonarlint-vscode|Son|3.7.0
ascii-plist|spe|1.0.3
rewrap|stk|1.16.3
open-in-browser|tec|2.0.0
ghosttext|tok|1.1.0
tab-groups|usa|2.0.1
errorlens|use|3.6.0
vscodeintellicode|Vis|1.2.22
txt-syntax|xsh|0.2.0
vscode-mdx-preview|xyc|0.3.3
vscode-open-in-github|ziy|1.3.6

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
841h4636:30534092

```

</details>

**Comment by gjsjohnmurray** [comment]
Looks like #133542

**Comment by lobsterkatie** [comment]
So it does. Will close in favor of that one. Thanks.
