### ISSUE TITLE
Extra quotes in settings json editor of non-current profile

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#156290]
Testing #155899

1. Create 2 profiles, A and B.
2. Switch to A. Open the settings.json file for the profile. Keep this file open.
3. Switch to B. 
4. Use suggest to modify the value of a setting in A's json file.
5. An extra quote will appear.

![Recording 2022-07-26 at 14 23 19](https://user-images.githubusercontent.com/38270282/181004920-2413d4c9-ae08-4691-80f3-0f332622d96f.gif)

**Comment by sandy081** [comment]
I cannot reproduce it. Anyway this comes from JSON language server.

CC @aeschli

**Comment by aeschli** [comment]
I'm also not able to reproduce
Did you press shift when selecting the completion (insert mode)?

**Comment by alexr00** [comment]
No, I just hit enter.

**Comment by aeschli** [comment]
Can you open the settings and see what `editor.suggest.insertMode` is configured?
It's default setting is `insert` but `json` and `jsonc` overwrite the default to `replace`. I wonder if there's some problem with the configuration store.

**Comment by alexr00** [comment]
It started as an empty profile, so theme is the only thing I have set. Value of `editor.suggest.insertMode`:
![image](https://user-images.githubusercontent.com/38270282/181471345-1a400593-0b18-4910-b6e4-1b4907bbe622.png)

**Comment by aeschli** [comment]
JSON and JSONC should also be in that list.
I just tested again, switching to a Test profile and I even get less entries:
![image](https://user-images.githubusercontent.com/6461412/181523305-c0a872f3-8d2e-4e9e-9c68-2f5d9f8316c2.png)

Looks like there's something off.

**Comment by sandy081** [comment]
@aeschli Do you think it is related to profiles? If so can you please share any insights on what would have caused it?

**Comment by aeschli** [comment]
Not clear if it's the settings UI that shows incomplete information, but after switching a profile, not all default language overwrites are shown. If the [JSONC language overwrite for editor.suggest.insertMode](https://github.com/microsoft/vscode/blob/e45b7a5a426802fb475b3a0856b80b313f2c9411/extensions/json-language-features/package.json#L132) is not loaded, that would explain what Alex is seeing.

**Comment by rzhao271** [comment]
I am able to repro the issue and my settings look like https://github.com/microsoft/vscode/issues/156290#issuecomment-1198179169

**Comment by rzhao271** [comment]
I'm unable to repro the issue now. I notice when I switch profiles and hover again over the label that it changes the list of languages depending on the extensions installed, but I always manage to have JSON and JSONC in the list.

@alexr00 are you able to repro the issue in the latest Insiders?

**Comment by alexr00** [comment]
I cannot repro with the latest insiders, though I could still repro with an insiders from some time last week. Looks like it's fixed.
