### ISSUE TITLE
Committing with empty message freezes source control

### ISSUE THREAD

**Issue by Dinoraptor101** [microsoft/vscode#156206]
Issue Type: <b>Bug</b>

If you attempt to commit without writing a message, VS Code is stuck in a loop of attempting to make the commit.

Fix: do not allow to commit with the message field being empty, or default that to amending to last commit (if applicable)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.71GB free)|
|Process Argv|--crash-reporter-id 2d581da7-0a87-4ca6-bec5-e5714787055b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.5.0
azurecli|ms-|0.5.0
salesforcedx-vscode-soql|sal|55.6.0
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.42.0
vscode-java-dependency|vsc|0.20.0
vscode-icons|vsc|11.13.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30534093

```

</details>

**Comment by lszomoru** [comment]
@Dinoraptor101, when attempting to commit without specifying a commit message you should see an editor being opened as described [here](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor). You can also disable this experience by setting the `git.useEditorAsCommitInput` to `false`.

**Comment by Dinoraptor101** [comment]
Thanks
