### ISSUE TITLE
Sticky scroll: removing code that appears in sticky scroll leaves empty line

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156267]
Testing #156175

![image](https://user-images.githubusercontent.com/900690/180980343-a9b0ce84-bb23-489a-928e-e7627fd7a831.png)

When you open the same editor side by side and leave the left editor with sticky scroll and remove that code from the other editor, I am left with an empty sticky scroll line.

**Comment by aiday-mar** [comment]
Fixed by recent changes, I can no longer reproduce
