### ISSUE TITLE
autoClosingBrackets and (

### ISSUE THREAD

**Issue by alarcl** [Microsoft/vscode#15625]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1 64

I have `"editor.autoClosingBrackets": false`
If type `(` then auto insert `)`.
If type any other brackets all work ok - no auto close for `[{"`

**Comment by ramya-rao-a** [comment]
@alarcl I cannot repro this in Windows in  VS Code 1.7.1
I tried on a typescript file.

Which file type are you seeing this on?

**Comment by alarcl** [comment]
It was on any file type, even "plain text".
I install VSCode (no plugins) on new machine and no such behavior.
Make little investigation on plugins.
[xDrivenDevelopment.language-1c-bsl](https://marketplace.visualstudio.com/items?itemName=xDrivenDevelopment.language-1c-bsl) plugin is the culprit, after choose this file type, in this file and all others, after type `(` auto insert `)`.

**Comment by ramya-rao-a** [comment]
In that case, please log an issue in the repo for the extension that is causing this.
