### ISSUE TITLE
Sticky line color contrast issue

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156257]
Testing #156175

I think the background color of the sticky lines has not sufficient color contrast to make it readable:

![image](https://user-images.githubusercontent.com/900690/180976599-0b3f2662-882b-4fa9-9013-db9310428a44.png)

I suggest to connect with @misolori or @daviddossett for advice

**Comment by misolori** [comment]
Have we considered using the editor bg color for this area, similar to the breadcrumbs? And that would make it easier to use existing hover styles like the list hover:

https://user-images.githubusercontent.com/35271042/181053111-326b0b81-07ff-4e3b-9a82-0491db00674f.mp4

I would just treat the sticky lines as an extension of the tab header area where the breadcrumbs area and if you can add a shadow on scroll (like breadcrumbs) that would be a nice touch:

<img width="601" alt="CleanShot 2022-07-26 at 08 58 04@2x" src="https://user-images.githubusercontent.com/35271042/181053695-3b746e85-67c2-463c-961b-a3d3a1a6a7c2.png">

**Comment by aiday-mar** [comment]
Great thanks for the feedback I'll implement that!
