### ISSUE TITLE
Search is always case-sensitive

### ISSUE THREAD

**Issue by Eternal-Rise** [microsoft/vscode#156243]
Issue Type: <b>Bug</b>

After the latest updates global search is always case-sensitive

![image](https://user-images.githubusercontent.com/34982358/180968545-d888e38d-d37b-4e6e-b8ce-6f0c446c10ef.png)
![image](https://user-images.githubusercontent.com/34982358/180968760-02231cd4-4c9e-4cd8-97cf-c2cb0accc624.png)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3187)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.82GB (47.45GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/eternal/dev/mstrade/feature/centrifugo-order --remote=wsl+Ubuntu --crash-reporter-id 07df9f40-59dc-444a-9e49-94f760aef6ae|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900KF (24 x 3187)|
|Memory (System)|31.26GB (25.54GB free)|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
postcss|css|1.0.9
graphql|mqu|0.1.2
remote-wsl|ms-|0.66.3
vscode-todo-highlight|way|1.0.5
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
i18n-ally|lok|2.8.1
vetur|oct|0.35.0
code-spell-checker|str|2.3.1
code-spell-checker-russian|str|2.0.5
code-spell-checker-ukrainian|str|0.1.14
tabnine-vscode|Tab|3.6.5
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.22

(5 theme extensions excluded)

</details>

**Comment by rbolsius** [comment]
I have observed the same issue in 1.69.2 with the "Search: Find in Files" command. If the search string contains any uppercase letters, then the search is always performed case-sensitively regardless whether the Match Case option is set. The Match Case option only works as it should when all the letters in the search string are lowercase.

It is also broken in 1.68.1, but not in the latest 1.70.0-insider build (1259bfe0090ac90afbf5d53335c43761de6bb19f, 2022-08-02T05:46:05.299Z).

**Comment by roblourens** [comment]
Did you set `search.smartCase`?

**Comment by Eternal-Rise** [comment]
@roblourens, first time here about this setting, but it enabled for some reason. Thanks!

**Comment by maic0n** [comment]
I checked the setting `search.smartCase` and in my case it was not enabled. I noticed the same problem in this version (1.69.2) when I tried to search for the text "rnew" and vs-code showed me only 2 results and the text "rNew" appeared more than two hundred times in the text.
After exiting and re-entering the application and/or clicking the "Match Case" on/off button, the problem stopped occurring.

**Comment by rbolsius** [comment]
@roblourens, I didn't realize that `search.smartCase` was enabled since the editor find doesn't implement smart case. That explains why the Find in Files did not find matches that the editor find did. It would be nice to have a UI like the one you described in https://github.com/microsoft/vscode/issues/42687 to make it more apparent when smart case is enabled.
