### ISSUE TITLE
Non-background tasks are sort of reattached to

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#156295]
Testing #155349

1. Open a selfhost setup.
2. Run the task "npm: tsec-compile-check"
3. Note that the task starts and has a spinner.
4. Reload the window.
5. The terminal reconnects, but the spinner is gone. The Building... spinner in the status bar is also gone.

**Comment by meganrogge** [comment]
@alexr00 by selfhost, do you mean in OSS?

I cannot reproduce in insider's

**Comment by meganrogge** [comment]
github won't let me upload the gif

**Comment by alexr00** [comment]
@meganrogge I do see the "Building..." status bar spinner now, but I still don't see the terminal tab spinner.
![Uploading Recording 2022-07-27 at 10.46.25.gif…]()

**Comment by meganrogge** [comment]
Tracking the spinner in this https://github.com/microsoft/vscode/issues/155246 @alexr00 and closing this as now you're seeing it in the status bar
