### ISSUE TITLE
Allow system context menu with custom title bar as well

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#156222]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70 insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open VS Code Insiders release
2. Right Click at VS Code Insiders icon in Title Bar
3. The expected behavior is to show the Title Bar Context Menu with a few _useful_ options _(print from Stable)_

![Screen Shot 2022-07-25 at 20 15 23](https://user-images.githubusercontent.com/3781424/180891079-ef60292d-322e-4242-9930-0aafc0b9adb0.png)

3.1. But instead, it displays:

![Screen Shot 2022-07-25 at 20 14 19](https://user-images.githubusercontent.com/3781424/180890901-ef9ae63b-556f-4a80-8c65-946d1e790386.png)

5. Not only the default Context Menu items were removed/replaced, but the <kbd>Alt</kbd> + <kbd>Space</kbd> keyboard shortcut is not working anymore either.

It seems this new behavior was caused by #155345. Based on a quick look, I didn't find any way to turn it off and return to the original behavior.

I'm a big fan of <kbd>Alt</kbd> + <kbd>Space</kbd> keyboard shortcut, specially to maximize/restore windows. With this new context menu, I've lost this.

Thank you

**Comment by sbatten** [comment]
Yea I think I will try to detect if the click is in the top left portion

**Comment by alefragnani** [comment]
Thank you! 

And please, don't forget the <kbd>Alt</kbd> + <kbd>Space</kbd> keyboard shortcut 😉

**Comment by clshortfuse** [comment]
Hi, nice work on the new feature!

Just to note, the actual Windows functionality is both left and right click on the title bar icon should present the context-menu. Also double clicking the title bar icon should the same as Close.

**Comment by ravindUwU** [comment]
Just auto-updated to 1.70 on Windows 10, and I'm so glad that the changes to how <kbd>Alt</kbd>+<kbd>Space</kbd> behaves, have been brought up!

I use the same shortcut to _resize windows_, i.e., 
1. Press <kbd>Alt</kbd>+<kbd>Space</kbd> to open the system context menu.
2. Press <kbd>S</kbd> (if your language is set to English, at least) to invoke its "Size" option. The pointer moves to the centre of the window.
3. Press the arrow keys to focus the pointer on a resize handle along an edge or at the corner of the window (e.g., <kbd>↑</kbd>, <kbd>←</kbd> for the top left hand corner).
4. Use the mouse for the rest.

Way easier & faster than trying to drag resize handles that are only a couple pixels wide (on Windows 10, at least).

https://user-images.githubusercontent.com/7352580/183315495-7361e0f4-bd55-4109-84b3-015e1ad4f2db.mp4

---

This doesn't _always_ work on 1.70.

* If the cursor rests close to the top edge of the window even below the title bar, the title bar customisation menu shows up.
* Or, steps 1 & 2 work, but 3 doesn't.

**Comment by yume-chan** [comment]
> Also double clicking the title bar icon should the same as Close. Right now it's maximizing. 

Set `"window.doubleClickIconToClose": true`

---

@sbatten When this is enabled, right click on window icon still shows custom context menu, do you want me to file a separate issue?

![image](https://user-images.githubusercontent.com/1330321/184507202-e9151576-a63f-4049-a9f5-bb1975aeb886.png)

```text
Version: 1.71.0-insider (user setup)
Commit: eebdf8174b087979ae6af103f6f2e2f6f9062056
Date: 2022-08-12T05:17:00.323Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25179
Sandboxed: Yes
```
