### ISSUE TITLE
Sticky scroll: unexpected line becoming sticky

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156262]
Testing #156175
![Recording 2022-07-26 at 11 54 17](https://user-images.githubusercontent.com/900690/180978699-d9f3c59b-948f-4042-a3c5-edb3c849d911.gif)

Here I found it weird that the last line would become a sticky line actually.

**Comment by aiday-mar** [comment]
The reason the last line becomes sticky is because it is a function and all functions are stuck to the top. But I think what I will do is stick to the top only outline element when they span more than a certain number of lines.

**Comment by aiday-mar** [comment]
Fixed with : https://github.com/microsoft/vscode/pull/156306/commits/9f331b70b668621f90ba9517b6fe335d8f6b4ef0
