### ISSUE TITLE
Sorting of languages in picker

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156254]
Shouldn't the sorting be alphabetical?

![image](https://user-images.githubusercontent.com/900690/180975193-4b53575f-af9c-4a0b-ab58-895100d3b82b.png)

**Comment by TylerLeonhardt** [comment]
Right now, those are sorted by installs... which seems like a better metric than alphabetically. If I were to sort alpha - Traditional Chinese ends up on the bottom:

![image](https://user-images.githubusercontent.com/2644648/181650677-9691896a-5d60-48b0-98fa-0937f67dea45.png)

Even though it's the most popular language pack.

That doesn't seem desirable.

**Comment by bpasero** [comment]
Yeah I would still sort installed above non-installed.

**Comment by TylerLeonhardt** [comment]
Like this?:
I think this is fine but it does feel a bit cramped:
![image](https://user-images.githubusercontent.com/2644648/181813992-5624924d-f84b-4971-8418-daf83dbeb89c.png)

**Comment by TylerLeonhardt** [comment]
this is an option...though it makes the qp scroll which I don't like...
![image](https://user-images.githubusercontent.com/2644648/181817302-b9b1a945-3371-4ef7-81ac-050ade201066.png)

and I could remove the use of the language id:
![image](https://user-images.githubusercontent.com/2644648/181817692-0e4c40dc-0dff-447f-86b8-4398a621be57.png)

**Comment by bpasero** [comment]
Yeah pretty cool 👍
