### ISSUE TITLE
Test: Code Action Widget

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#156219]
Refs: https://github.com/microsoft/vscode/issues/152913

- [x] Windows @karrtikr
- [x] macOS @sandy081
- [x] Linux @sadasant

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156219%0A%0A&assignees=justschen)

---

Shipped a drop-in replacement for the Code Action Menu. The Code Action Widget is a list widget using the context view service and can support additional features such as custom key bindings, hovers, symbols, and more. At the moment, we'd like to test to ensure that there are no regressions in how the menu functions and feels. 

## Set up:
Enable the experimental setting by going to Editor › Experimental: Use Custom Code Action Menu or by adding the setting `"editor.contrib.experimental.codeActionWidget.enabled": true`.

The widget can be accessed from the following places:
- Context Menu (Refactor, Source Action)
- Lightbulb
- Quickfix

![Recording 2022-07-25 at 15 49 47](https://user-images.githubusercontent.com/54879025/180888234-22fda6c2-84fa-4997-83c3-f98313e677eb.gif)

## Testing:
Some things to take a look at:
- Opening the widget from the Context Menu. (from `Refactor` or `Souce Action`).
- Opening the widget directly from hotkeys (`Ctrl + Shift + R`  and `Ctrl + .`)
- Opening the widget from the Lightbulb.
- Opening the widget from Quickfix.
- Ensure that various color themes match the context menu.
- Keybindings (`Esc`, `UpArrow`, `DownArrow`, `Enter`)
- Anything going off DOM (changing window size, opening another menu, etc)

## Questions:
- Any thoughts on the styling and accessibility of the new widget vs. the old context menu.
- Suppose hover were added to each list element - would it become to cluttered? (ref. https://github.com/microsoft/vscode/issues/145058)

**Comment by sandy081** [comment]
> Enable the experimental setting by going to Editor › Experimental: Use Custom Code Action Menu or by adding the setting "editor.contrib.experimental.codeActionWidget.enabled": true.

@justschen  I do not find above setting.

<img width="744" alt="image" src="https://user-images.githubusercontent.com/10746682/180942962-75eae7b8-a73a-4574-a245-3c5932badf84.png">

**Comment by sadasant** [comment]
I don't see the setting either! Thought it doesn't give me an error (like @sandy081 's screenshot above). Is that expected?

**Comment by justschen** [comment]
Sorry we had updated the naming convention, but I had copy and pasted from an earlier announcement about this. The correct name is 	`"editor.experimental.useCustomCodeActionMenu": true`. Can also be found by going to Editor › Experimental: Use Custom Code Action Menu!
