### ISSUE TITLE
Test: edit sessions view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#156211]
Refs: https://github.com/microsoft/vscode/issues/141293

- [x] Windows @bamurtaugh
- [x] macOS @misolori
- [x] Linux @alexdima

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156211%0A%0A&assignees=joyceerhl)

---

Last milestone we shipped a preview of edit sessions, which let you transfer your working changes for a given repository across different VS Code clients. There is now a view to make it easier to view and manage your existing edit sessions. Please run the Focus on Edit Sessions View command to set focus to the view, and test the following:
- Edit sessions which you have created using the Store Current Edit Session command across various machines or browsers (e.g. github.dev, insiders.vscode.dev, VS Code) show up in the view
- You can use the tree view to preview the working changes which are tracked in each edit session
- You can delete or resume specific edit sessions from the inline tree view actions

**Comment by alexdima** [comment]
I wasn't able to store an edit session (see https://github.com/microsoft/vscode/issues/156250), so I am blocked with testing for now
