### ISSUE TITLE
integrated terminal detect wrong link range

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#156241]
![image](https://user-images.githubusercontent.com/41773861/180961663-fe40f5c7-0c6e-461e-844b-4b738c7dc624.png)

@Tyriar

test code:

```bash
echo '安装包路径：/Users/yutengjing/code/hammer/packages/app/dist'
```

Versions:

```
Version: 1.70.0-insider (Universal)
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:17:37.262Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
```

**Comment by Tyriar** [comment]
I worry if we will never be able to capture all these potential path separating characters while at the same time not breaking links that may use them. I think this sort of customization should be done on the users end by modifying this setting:

```
"terminal.integrated.wordSeparators": " ()[]{}',\"`─‘’："
```
