### ISSUE TITLE
Electron Sandbox Workspace Setting

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#156263]
Testing #155827

Sandbox is meant to be a global setting, but when setting it in the workplace settings, it doesn't show that it is not allowed and suggests to restart vscode. When it then restarts, it does not start in sandbox mode (No Sandbox message in DevTools). 

I believe that the setting should actually be showing an error when set in the workplace settings (red squiggly line) and should not prompt to restart.

**Comment by bpasero** [comment]
I guess I am missing `'scope': ConfigurationScope.APPLICATION,`
