### ISSUE TITLE
Tasks duplicate after restart

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156285]
![image](https://user-images.githubusercontent.com/900690/181001424-43124efa-2164-4231-9242-801980c7f7a0.png)

**Comment by meganrogge** [comment]
I cannot reproduce this. 

Can you reproduce every time? Any task settings or tasks that run on folder open?

**Comment by bpasero** [comment]
I am running `workbench.action.tasks.build` in a multi root workspace with `vscode` and `vscode-docs` repo. I have set `"task.experimental.reconnection": true`.

But now indeed I do not see this anymore, strange. Will keep an eye open.

**Comment by bpasero** [comment]
Another thing I notice is that the spinner does not show when I reload while the task is running and spinning:

<img width="235" alt="image" src="https://user-images.githubusercontent.com/900690/181158339-230f65dd-0664-4f0d-8467-0b12d4999d8a.png">

**Comment by meganrogge** [comment]
ok pls reopen this if you see it again - we are tracking the issue w the status IE spinner here https://github.com/microsoft/vscode/issues/155246
