### ISSUE TITLE
Tree: Remember find widget input across usages

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156248]
Testing #156100

When find box is not visible and I just type but there are multiple results, then maybe allow me via keybindings (F3?) to go to next/prev result?

**Comment by joaomoreno** [comment]
You mean using the _type navigation_ feature? I think this would be too implicit. I don't know of any other native widget doing something like this.

**Comment by bpasero** [comment]
I think the editor has a way to navigate in find results even without showing find. i think in that mode it only puts the search toggles up in a little overlay.

**Comment by bpasero** [comment]
I think the tree does the same, I had tried `F3` and it showed the input box, but it was empty though.

**Comment by joaomoreno** [comment]
Yeah. Renamed this to remember the input across usages, which is what the editor does.
