### ISSUE TITLE
Remove Manual Folding Range doesn't work

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#156277]
Remove Manual Folding Range doesn't work

_Originally posted by @Eldair in https://github.com/microsoft/vscode/issues/156161#issuecomment-1195229970_

- select a range in the editor
- invoke `Create Manual Folding Range from Selection`. Selection turns into a folding range
- put the cursor at the beginning of the collapsed line
- invoke `Remove Manual Folding Range`. Should remove the manual folding range

**Comment by rzhao271** [comment]
It works when the cursor is at the second column or to the right of that, but not when it's right at the beginning of the line, which is exactly where it is placed after running the create manual folding range command.
