### ISSUE TITLE
Test finalized drop in editor api 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156223]
Test for #142990

- [x] Mac @alexdima
- [x] Linux @karthiknadig
- [x] Windows @andreamah

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23156223%0A%0A&assignees=mjbvz)

--- 
## Summary 
The drop into editor api has been finalized! [This api](https://github.com/microsoft/vscode/blob/8f10b21033161e235e9c14767c21efb550319848/src/vscode-dts/vscode.d.ts#L5435) lets extension hook into when something is dropped on a text editor

## Testing

Use the [drop into editor sample extension](https://github.com/microsoft/vscode-extension-samples/tree/main/drop-on-document) to test this API. Some things to test:

- Check the documentation of the various api types
- Check that you can handle drops from the VS Code explorer and from the OS
- Try returning a workspace edit on `DocumentDropEdit` (for example, creating a new file)
- Check that setting `workbench.editor.dropIntoEditor.enabled` disabled dropping into the editor
- Try dropping into notebook cells

**Comment by andreamah** [comment]
Works super well! 😊
