### ISSUE TITLE
Editor lacks with crazy amounts of decorations

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15629]
I use the [Rainbow](https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets)-brackets extension that adds a colourful decoration per bracket-pair. When typing in large files that causes the editor to stall from time to time. This is what I did for the attached profile

* install rainbow brackets
* open `vscode.d.ts`
* start profiling
* spend some time to write jsdoc comments
* from time to time you'll notice the editor taking a pause, the profile hints to `_deltaDecorationsImpl`

Two things we should consider

1. As with other decorations (find, diagnostics, occurrences) we should maybe cap the number of decorations
2. The profile shows warning about `detaDecorations` being not optimised by too often optimised. 

![screen shot 2016-11-17 at 11 03 55](https://cloud.githubusercontent.com/assets/1794099/20384854/8e658c12-acb5-11e6-9835-d094a3a701c2.png)

**Comment by jrieken** [comment]
[CPU-20161117T110434.cpuprofile.zip](https://github.com/Microsoft/vscode/files/597026/CPU-20161117T110434.cpuprofile.zip)

**Comment by CoenraadS** [comment]
It also has to do with batching calls. The rainbow brackets extension does a ```this.textEditor.setDecorations(key, value);``` for every decoration/range. If the ranges of same decorations are concatenated to reduce calls, it is much faster.

From my tests:

Batched: 7.501ms
Non-batched: 34.828ms

**Comment by alexandrudima** [comment]
We need to add a maximum decoration count in the extension host side (similar to how we cut off errors...)

**Comment by alexandrudima** [comment]
This has been improved substantially with the interval tree reimplementation of decorations, so closing for now...
