### ISSUE TITLE
Preview pane does not show output [SQL Results, Markdown Preview, etc]

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/vscode#15623]
- VSCode Version:
Version 1.8.0-insider
Commit 1b95a2f7a7e8858c5612807522a6f8cd8e03c1dc
Date 2016-11-17T00:36:45.332Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1.  Open Markdown file `.md`
2.  Choose Open Preview command

Expected: 
The rendered Markdown preview is shown
Actual:
Blank pane is rendered (no content)

The Markdown issue is the quickest to reproduce. Similar issue with vscode-mssql extension (Connect 2016 thing):
Microsoft/vscode-mssql#361

Thanks!

**Comment by bpasero** [comment]
This is probably https://github.com/Microsoft/vscode/commit/0cef61f4f4d8a73a00f8da28bdf9b7af0a11e4ef

**Comment by jrieken** [comment]
same for extension. open extension viewlet, select extension, detail-tab stays empty

**Comment by jrieken** [comment]
@mjbvz Pretty sure this happens because when building you must explicitly include the `pre`-file as we do it with [`webview.html`](https://github.com/Microsoft/vscode/blob/master/build/gulpfile.vscode.js#L68). Sorry for not spotting that

**Comment by jrieken** [comment]
fyi - I have pushed a change to *master* and triggered new insiders builds for this

**Comment by bpasero** [comment]
@jrieken should also be added to the release/1.7 branch where I think @mjbvz change also landed?

**Comment by jrieken** [comment]
I leave that to @mjbvz

**Comment by peterblazejewicz** [comment]
This seems to be published and fixed at least on the OS X (I have yet to verify this at Win machine at work). Thanks!

**Comment by mjbvz** [comment]
Thanks for catching this.  @jrieken, I've cherry-picked the fix into 1.7 as well: https://github.com/Microsoft/vscode/commit/07e605ea7f24f66ac2ffb6a9ffa7d54c2eed21aa
