### ISSUE TITLE
Invalid wordbasedsuggressions setting

### ISSUE THREAD

**Issue by wuqiyin** [microsoft/vscode#156225]
This setting is effective in other programming languages, such as JS. But when writing PHP, it has no effect.
![VeryCapture_20220726093016](https://user-images.githubusercontent.com/26370779/180903775-99a2b00d-9c2e-4bd1-9c83-972d52cb96e2.gif)

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/21611
