### ISSUE TITLE
[folding] Consider renaming "Create manual folding range from selection"

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#156280]
Testing #156163

You could remove "manual" from the action name, i.e. "Create folding range from selection" or maybe even "Fold selection".

**Comment by aeschli** [comment]
Fold selection could be confusing if there are already folding ranges at the selection position. 
- it's more than just folding (it creates a range)
- sounds too similar than the commands that just collapse (`Fold`, `Fold All`,...)

**Comment by aeschli** [comment]
I'm not opposed to remove the 'Manual'
