### ISSUE TITLE
Test: `New File...` picker feedback

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#156253]
Testing #155731

<img width="728" alt="image" src="https://user-images.githubusercontent.com/3372902/180974183-7c04b61f-fd86-4022-abb3-23fc88441599.png">

- I would suggest that we update the placeholder to indicate that you can type in a name to create a new file
- Is there any reason why we have `Built-In` description for the capabilities that are included in VS Code? 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/3372902/180974710-49266d98-a253-4dba-aa34-76f40f36dc93.png">

- I would suggest that we update the quick pick item to something like "Create New File" and remove the "Built-In" description

<img width="728" alt="image" src="https://user-images.githubusercontent.com/3372902/180975403-fd5d10af-5f02-417b-b2e2-40124ddfc1a9.png">

- I would suggest to place the "New File" quick pick item at the end of the list separated from the file types

**Comment by lramos15** [comment]
> * Is there any reason why we have `Built-In` description for the capabilities that are included in VS Code?

It's just been the precedent whenever we have some features that are contributed in a list with built-in features there as well. The Reopen With... picker does the same thing.



> * I would suggest to place the "New File" quick pick item at the end of the list separated from the file types

I think the division here is built-in vs non built-in and not necessarily file types vs not file types. The New File (name) will actually choose a file type based off of the file extension
