### ISSUE TITLE
Console.ReadLine Not Working

### ISSUE THREAD

**Issue by ChristianRRL** [Microsoft/vscode#15620]
- VSCode Version: Preview 1 (7.0 build 347)
- OS Version: OSX El Capitan 10.11.6

Steps to Reproduce:

1. Write the following code:
class MainClass
{
	public static void Main()
	{
		System.Console.WriteLine("Begin Test");
		System.Console.WriteLine("ReadLine: ");
		System.Console.ReadLine();
		System.Console.WriteLine("End Test");
	}
}
2. Run the program
3. The lines "Begin Test" and "ReadLine" pop up in the Application Output, but there is no way to input text and/or press enter.
![vsmac-readline-errorreport](https://cloud.githubusercontent.com/assets/6551085/20378004/62629370-ac61-11e6-8daa-869f4ea725cb.png)

**Comment by ramya-rao-a** [comment]
@ChristianRRL Is that Visual Studio for Mac?

This repo is for Visual Studio Code. Am not sure where to redirect you to. There must be a way to provide feedback from the product itself.

**Comment by mhutch** [comment]
Please use the "Report a Problem" command to report issues in Visual Studio for Mac. Thanks!

This specific issue is a known limitation, so [our UserVoice](https://aka.ms/vs/mac/provide-suggestion) would be in this case. The integrated application output simply displays stdout/stderr, it is not a full terminal. If you need a full terminal, you can can set your project to use an external terminal in Project Options > Run Configurations.

**Comment by akhilanair94** [comment]
I am not able to type in "Application Output" while coding in "Console Application" in VS17 preview for mac. Every time i have to choose a custom run configuration.

**Comment by ramya-rao-a** [comment]
@akhilanair94 This is the repo for Visual Studio Code.

For issues with Visual Studio for Mac, please follow https://github.com/Microsoft/vscode/issues/15620#issuecomment-261383543
