### ISSUE TITLE
to should be capitalized in the command "Go to..."

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#156297]
Testing #156194

Just a small change. Believe the casing is off in the hover hint for the button. When going to a running cell it's "Go To.." and in the new error command its "Go to..." with the rest all caps. I believe the "to" should be "To."

**Comment by gregvanl** [comment]
The convention for commands is to use "Go to...." lowercase "to".

![image](https://user-images.githubusercontent.com/12818376/181032047-a53a3d7d-fdc5-46b2-ad6b-7145b155db43.png)

**Comment by IanMatthewHuff** [comment]
@gregvanl Got it. I was basing it off of seeing this for the other Go to cell command. So is the bug on that text instead?

<img width="191" alt="image" src="https://user-images.githubusercontent.com/812783/181046870-286df47e-2a55-425d-8b7d-4859eadea18b.png">

**Comment by andreamah** [comment]
@gregvanl @IanMatthewHuff just checking, but would be proper fix for this to change the casing in "Go To Running Cell" to "Go to Running Cell"?
