### ISSUE TITLE
QuickFix Generate a class for 'class name' in 'namespace' (in a new file) doesn't work

### ISSUE THREAD

**Issue by Taraweesh** [Microsoft/vscode#1562]
no files get created and omnisharp needs restart to function.
here is omnisharp log.

 [INFO] Starting OmniSharp at 'd:\c\Work\vscodeunity\vscodeunity-csharp.sln'...
[INFO] Started OmniSharp from 'c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\jrieken.vscode-omnisharp\bin\omnisharp.cmd' with process id 2768...
[INFORMATION:OmniSharp.Startup] Omnisharp server running using stdio at location 'd:\c\Work\vscodeunity' on host 7196.
[INFORMATION:OmniSharp.Dnx.DnxPaths] Using runtime 'C:\Users\Taraweesh\.dnx\runtimes\dnx-clr-win-x86.1.0.0-rc1-update1'.
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] Scanning 'd:\c\Work\vscodeunity' for DNX projects
[INFORMATION:OmniSharp.Dnx.DnxProjectSystem] No project.json based projects found
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Detecting projects in 'd:\c\Work\vscodeunity\vscodeunity-csharp.sln'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for d:\c\Work\vscodeunity\Assembly-CSharp-vs.csproj
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'd:\c\Work\vscodeunity\Assembly-CSharp-vs.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Loading project from 'd:\c\Work\vscodeunity\Assembly-CSharp-Editor-vs.csproj'.
[INFORMATION:OmniSharp.MSBuild.MSBuildProjectSystem] Using toolset 2.0 for d:\c\Work\vscodeunity\Assembly-CSharp-Editor-vs.csproj
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Detecting CSX files in 'd:\c\Work\vscodeunity'.
[INFORMATION:OmniSharp.ScriptCs.ScriptCsProjectSystem] Could not find any CSX files
[INFORMATION:OmniSharp.Startup] Solution has finished loading
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/getcodeactions: 200 1114ms
[INFORMATION:OmniSharp.Roslyn.CSharp.Services.Refactoring.V2.RunCodeActionService] Applying Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6+GenerateTypeCodeAction[Microsoft.CodeAnalysis.CSharp.GenerateType.CSharpGenerateTypeService,Microsoft.CodeAnalysis.CSharp.Syntax.SimpleNameSyntax,Microsoft.CodeAnalysis.CSharp.Syntax.ObjectCreationExpressionSyntax,Microsoft.CodeAnalysis.CSharp.Syntax.ExpressionSyntax,Microsoft.CodeAnalysis.CSharp.Syntax.TypeDeclarationSyntax,Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax]
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/runcodeaction: 200 522ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/runcodeaction: 200 8ms
[INFORMATION:OmniSharp.Middleware.LoggingMiddleware] /v2/runcodeaction: 200 4ms

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-roslyn#381
