### ISSUE TITLE
Merge Editor: Align terminology

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#156229]
Currently in merge conflict and in the SCM view we talk about `Incoming` and `Current` changes, but the new Merge Editor talks about `Theirs` and `Mine` -- IMO we should align to the `Incoming` and `Current` terms.

**Comment by hediet** [comment]
The opener of the merge editor is in control of the labels. Thus, this can easily be changed in the git extension.

Incoming and Current makes sense for conflicts when merging in a remote branch, but not when applying stashes (though in that case "Theirs" and "Mine" also doesn't make much sense).

**Comment by eamodio** [comment]
I always just think of it as there are always changes (from a merge, stash, etc) that are being incorporated (incoming) into the current state.
