### ISSUE TITLE
Sticky scroll: line numbers jump into lines

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156259]
Testing #156175

It looks like the line numbers drop in weirdly when resized with sticky scrolled lines:

![Recording 2022-07-26 at 11 49 13](https://user-images.githubusercontent.com/900690/180977736-3605ba31-ea2f-4da7-b87e-1f730ab07b54.gif)

**Comment by aiday-mar** [comment]
Solved with https://github.com/microsoft/vscode/pull/156306/commits/42f2178106b708a85c12d356450fc2c729f9f8a4

**Comment by bpasero** [comment]
Thanks! Please make sure to assign `bug` label and move to current milestone so that during endgame all issues found can also directly get verified 👍

**Comment by aiday-mar** [comment]
Sure
