### ISSUE TITLE
New File... - creating a new file brings up the OS file dialog

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#156256]
Testing #155731

On macOS I did the following:
- File -> New File...
- Put in a valid file name that does not already exist
- Hit Enter

Expected: File would be created and opened
Actual: The OS file dialog is being displayed

**Comment by lramos15** [comment]
@lszomoru How would we know where to save / create the file if you do not select a path?

**Comment by lszomoru** [comment]
@lramos15 I was expecting that if it's a folder/workspace, the file would be placed in the root of the folder/workspace. 
In case of a multi-root workspace, it does make sense to show the dialog.

**Comment by lramos15** [comment]
After looking into this more and discussing with SteVen, I don't believe we should do this. It would be very confusing to pick a random save location and this feature was always just meant to unblock people who are having difficulties creating new files. The suggested save location is normally good and is the folder you're currently viewing so more times than not the user could just hit create or make a file via the explorer
