### ISSUE TITLE
Task dialog could benefit from separation of title and details

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156287]
Testing #155350

![image](https://user-images.githubusercontent.com/900690/181002849-c2706409-a15f-4543-a873-b5e422effd08.png)

**Comment by bpasero** [comment]
I also wonder why none of the buttons are focused by default?

**Comment by meganrogge** [comment]
I think the volume of words can be reduced and the message can be improved.

**Comment by meganrogge** [comment]
@bpasero I don't see a way via the `dialogService.show` to indicate which should be pre-selected

**Comment by bpasero** [comment]
Try setting the `cancelId` option as well.
