### ISSUE TITLE
Incorrect handling of unicode markers - Backspace splits Ideographic Variation Sequence 

### ISSUE THREAD

**Issue by JoshVarty** [microsoft/vscode#15622]
- VSCode Version: 1.6.1
- OS Version: Windows 10

We've got this bug in Visual Studio for Windows and I noticed that VS Code has it as well. 

Steps to Reproduce:
1. Paste following code in VSCode. It's C# code, but it repros in any file. 
```CSharp
List<string> test = new List<string>();
test.Add("辻󠄁"); // 辻󠄁 8FBB DB40 DD01
test.Add("辻"); // 辻 8FBB
test.Add("辻󠄀"); // 辻󠄀 8FBB DB40 DD00
```

2. Place cursor to right of either first or third 辻󠄀

3. Press backspace

**Expected behavior**: The entire character should be removed as it does in Notepad and Microsoft Word

**Actual Behavior**: The right two bytes are removed from the buffer but 8FBB remains.

These characters are not valid within the context of most C# code (variable/method names) but are legal within comments and strings where they may be more likely to occur in the future.

It's also worth noting that these characters cause issues with left and right arrow movements. I'm not sure if it's worth opening a separate issue for this, though.

**Comment by alexandrudima** [comment]
Variation Selectors are not treated special in any way

```js
// 辻󠄁 8FBB DB40 DD01
"辻󠄁".codePointAt(0).toString(16) // 8fbb
"辻󠄁".codePointAt(1).toString(16) // e0101
```

http://www.unicode.org/charts/PDF/UE0100.pdf

![image](https://cloud.githubusercontent.com/assets/5047891/20757595/3d6c338a-b717-11e6-82a4-d385d542f674.png)

**Comment by alexandrudima** [comment]
The same issue exists with combining diacritics - e.g. `ã`

**Comment by alexandrudima** [comment]
To verify, paste the following snippet:
```
List<string> test = new List<string>();
test.Add("辻󠄁"); // 辻󠄁 8FBB DB40 DD01
test.Add("辻"); // 辻 8FBB
test.Add("辻󠄀"); // 辻󠄀 8FBB DB40 DD00
// ããã
// புன்சிரிப்போடு
```

Attempt to move the cursor around in between characters (left/up/right/down arrows), enable the block cursor. You can compare with the stable version to see the multitude of issues that were addressed...

**Comment by vomout** [comment]
This, or at least the incorrect rendering of combining characters in #79067, seems to be related to the font: With the default `Menlo, Monaco, 'Courier New', monospace` Font Family setting, σ̃ renders correctly, however with `Source Code Pro`, everything is messed up.

**Comment by alexandrudima** [comment]
@vomout Yes, in this case it appears that the font `Source Code Pro` does not handle combining marks correctly:

![image](https://user-images.githubusercontent.com/5047891/69219371-fc94aa00-0b72-11ea-8d55-833adba77164.png)

![image](https://user-images.githubusercontent.com/5047891/69219395-074f3f00-0b73-11ea-9ed3-bae9b9646dd1.png)
