### ISSUE TITLE
Search in files doesn't find

### ISSUE THREAD

**Issue by khmseu** [microsoft/vscode#156332]
Issue Type: <b>Bug</b>

I'm attaching a directory with three Textfiles. For a search of "ENDST", grep tells me there should be four results:
BIMISC.ASM:74: PUBLIC  STPEND,CONT,ENDST,GTMPRT,RUNC,STPEND,ENDCON,RESTORE
BIMISC.ASM:573:ENDST:  JZ      SHORT $+3
GWDATA.ASM:117:        EXTRN   ENDST:NEAR,NEXT:NEAR,RESTORE:NEAR,SCRATH:NEAR,CONT:NEAR
IBMRES.ASM:59: R2      END,ENDST

However, search [ctrl-shift-F] only finds the last of these. 

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:14:10.636Z)
OS version: Linux x64 4.18.0-26-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A10-6800K APU with Radeon(tm) HD Graphics (4 x 4092)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|30.89GB (7.39GB free)|
|Process Argv|--unity-launch --crash-reporter-id 06bd71bb-c67b-4dfa-9928-3c5b02277686|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
svelte-intellisense|ard|0.7.1
vuejs-helper|Att|1.2.2
code-gnu-global|aus|0.2.2
simple-react-snippets|bur|1.2.6
cmake-format|che|0.6.11
codebook|cod|0.3.0
systemd-unit-file|coo|1.0.6
vscode-svgviewer|css|2.0.0
vscode-markdownlint|Dav|0.47.0
vuejs-component-creator|Dev|0.0.3
typescript-notebook|don|2.0.6
vscode-firefox-debug|fir|2.9.8
vscode-svelte-snippets|fiv|0.5.0
memi-quasar-snippets|fkk|0.0.6
cmake-integration-vscode|go2|0.7.1
todo-tree|Gru|0.0.215
vscode-systemd-support|han|1.0.1
notejs|hen|0.0.24
crontab-syntax-highlight|hog|0.0.2
vue-snippets|hol|1.0.4
rest-client|hum|0.25.0
vscode-ansi|ili|1.1.2
vue-autoimport|ish|1.0.5
handydandy-notebook|jak|0.1.4
javascript-notebooks|joa|0.0.2
svn-scm|joh|2.15.5
vscode-github|Kni|0.30.7
vscode-format-context-menu|lac|1.0.4
vue|liu|0.1.5
vscode-typescript-to-json-schema|mar|0.0.16
cmake-extension-pack|mis|0.0.1
vscode-html-format|moh|0.0.4
vscode-attrs-sorter|mrm|2.1.0
vscode-autoprefixer|mrm|3.0.1
vscode-json5|mrm|1.0.0
vscode-scss|mrm|0.10.0
vscode-language-pack-de|MS-|1.69.7130931
vscode-postgresql|ms-|0.3.0
anycode-kotlin|ms-|0.0.5
mono-debug|ms-|0.16.2
vscode-react-native|msj|1.9.2
vs-html-to-css|nep|1.0.0
svelte-autoimport|piv|1.0.4
vscode-css-peek|pra|4.2.0
react-on-the-fly|raz|0.0.6
java|red|1.9.0
bash-debug|rog|0.3.9
vue-vscode-snippets|sdr|3.1.1
vscode-zipexplorer|sle|0.3.1
html-to-css-autocompletion|sol|1.1.2
svelte-vscode|sve|105.19.0
language-stylus|sys|1.16.0
rest-book|tan|6.2.1
cmantic|tde|0.9.0
code-ca65|tlg|1.2.3
cxx-compiler-explorer|tra|0.3.4
luna-paint|Tyr|0.15.0
vscode-java-debug|vsc|0.42.0
vscode-java-test|vsc|0.36.0
vscode-icons|vsc|11.13.0
vscode-todo-highlight|way|1.0.5
open-in-external-app|YuT|0.5.0
html-css-class-completion|Zig|1.20.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30534093

```

</details>

**Comment by khmseu** [comment]
[ttt.zip](https://github.com/microsoft/vscode/files/9192170/ttt.zip)

**Comment by roblourens** [comment]
Seems that these files contain null bytes and get detected as binary files. We have this feature request, but I don't expect to support this. https://github.com/microsoft/vscode/issues/151456
