### ISSUE TITLE
Unclear how to save a session

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#156342]
Testing #156211

When searching for "Edit Sessions" I see both a "Continue Edit Session" and "Store Current Edit Session" and it's not exactly clear which one I should use. Am I actively in an edit session? The latter command implies I am in one, so does that mean I need to save or store it? Does continue just open the current session in my local experience?

<img width="424" alt="CleanShot 2022-07-26 at 11 16 47@2x" src="https://user-images.githubusercontent.com/35271042/181081691-fe6aeb1c-9daa-49ae-a1ed-254c0591455d.png">

## Continue Edit Session
I decide to try to the first option and then see the opens to "Open in Local Folder", which I assume this opens as a local folder using desktop? Still unsure

<img width="423" alt="CleanShot 2022-07-26 at 11 19 08@2x" src="https://user-images.githubusercontent.com/35271042/181082030-2922231e-f9bb-4e1c-8e77-558d3434cb2c.png">

And this leads me to a dead-end, which I wish the option before was disabled with a description of why

<img width="586" alt="CleanShot 2022-07-26 at 11 19 47@2x" src="https://user-images.githubusercontent.com/35271042/181082166-983e7562-f42e-46d7-a6a8-3449a312d226.png">

## Store Edit Session

I select this option but then nothing happens. It's unclear what I should do next. Did it save? Should I then open this in desktop? How do I open this in desktop? I open the "Focus on All Sessions view" and it's blank, so I'm really at a loss:

<img width="417" alt="CleanShot 2022-07-26 at 11 21 40@2x" src="https://user-images.githubusercontent.com/35271042/181082538-5225d841-76cf-49ed-aba7-68ac61b5b9cc.png">

**Comment by joyceerhl** [comment]
Sorry I missed this--the issue with local folders is https://github.com/microsoft/vscode/issues/156345. The empty sessions view is https://github.com/microsoft/vscode/issues/156339. The Continue Edit Session vs Store Current Edit Session confusion is https://github.com/microsoft/vscode/issues/156350. Closing as I think the feedback in this issue is tracked by those other issues, but please reopen otherwise!
