### ISSUE TITLE
Right clicking view title expands/collapses it

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156341]
Type: <b>Bug</b>

1. In the explorer view
2. Enable open editors
2. Right click open editors view section to hide it

**bug**
The open editors section collapses and the context menu shows up

I expect just to see the context menu in this case

VS Code version: Code - Insiders 1.70.0-insider (Universal) (cc098faebd320a2eea3da6ae154b7e2e1347a4b9, 2022-07-26T05:17:37.262Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by sbatten** [comment]
interesting, doesn't repro on Windows either, so I'll have to test on my macbook

**Comment by sbatten** [comment]
hmm just tested on my mac, no repro with latest insiders

**Comment by mjbvz** [comment]
🤷 Only seeing this in my oss build now. Will reopen if I start seeing this again
