### ISSUE TITLE
Testing drop-in-editor: no screen hint when dragging in text

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156374]
Testing #156223

Not sure if this would be possible, but it would be nice to have the same screen hint with dragging highlighted text as with files.
![Recording 2022-07-26 at 14 49 16](https://user-images.githubusercontent.com/31675041/181118734-0367be87-df1d-4165-94f9-5bfa0c9c9196.gif)

Ideally, above would have something like this too:
<img width="807" alt="image" src="https://user-images.githubusercontent.com/31675041/181118845-3f64d280-caba-4799-a7a7-aa4821f825bf.png">

EDIT: realized that this is a difference in behavior between files and text, but would still be good to see a hint for text.

**Comment by karthiknadig** [comment]
I ran into the same issue as well.

**Comment by mjbvz** [comment]
This is by-design. With files, the default drop opens the file instead of inserting it. However when dragging text, you can only drop it into the editor. It's not worth showing an overlay IMO in these cases (and this is consistent with how other apps work)
