### ISSUE TITLE
"Use Fuzzy Search" button toggle - a weird UI pattern

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#156322]
Testing #156002

I find it weird that the "Use Fuzzy Search" is a big blue button. I think it would be styled more like the toggles in the editor find widget. Or it should be a checkbox. 
The blue button is too strong, and I would expect that it executes something a closes the quick pick

fyi @misolori

![Screenshot 2022-07-26 at 18 51 40](https://user-images.githubusercontent.com/1926584/181064800-86481597-4bde-4647-8816-5f60828820dd.png)

**Comment by meganrogge** [comment]
Yes we agree and have had discussions about a better icon that aligns with other toggles

**Comment by misolori** [comment]
This is also being tracked in https://github.com/microsoft/vscode/issues/156179 where we're looking at all of the inputs w/ actions/toggles

**Comment by Tyriar** [comment]
Depends on https://github.com/microsoft/vscode/issues/156179

**Comment by Tyriar** [comment]
UX sync feedback:

Prefer a toggle over a dropdown as it's a search mode/how it's search, vs a dropdown which is typically what is searched/filtered.

It seems the consensus was some icon similar to this to mean "fuzzy search", we can also avoid mentioning "default"/"continuous"/"contiguous" if it's a toggle.

![image](https://user-images.githubusercontent.com/2193314/185187871-0c0fed59-5a61-4373-8790-df6851f10fa8.png)

We may want the fuzzy search toggle to be remembered and/or in a setting, fzf users may want fuzzy search by default.

**Comment by meganrogge** [comment]
Wouldn't it be better to display what it actually does like we do with the `Aa` case specific search toggle?

**Comment by Tyriar** [comment]
Icon request: https://github.com/microsoft/vscode-codicons/issues/132

**Comment by meganrogge** [comment]
By having it underline either a continuous segment or separate ones

**Comment by Tyriar** [comment]
@meganrogge that was the idea behind these ones:

![image](https://user-images.githubusercontent.com/2193314/185190703-68e856f3-d3d7-451e-99b9-9881b3897a9e.png)
![image](https://user-images.githubusercontent.com/2193314/185190721-92cfc471-2e16-4fc4-a72c-a5531454d297.png)
![image](https://user-images.githubusercontent.com/2193314/185190741-7b9b8643-587b-4240-ba13-ebe362facc54.png)

The idea seemed solid but I think in practice they are pretty ugly

**Comment by meganrogge** [comment]
I far prefer those because it tells me what's going on. The other makes me think of zoom

**Comment by Tyriar** [comment]
While the magnifying glass can mean zoom, it's only used for search in VS Code afaik

![image](https://user-images.githubusercontent.com/2193314/185208473-b50e0fc6-9aa6-46de-a1ba-8d72da842f90.png)

**Comment by meganrogge** [comment]
Yeah but a button's icon should indicate what it does - the button doesn't search - it changes the type of filter used

**Comment by meganrogge** [comment]
IMO, that's precisely why it's confusing - I'm already searching via the input box - not sure what a search with a squiggly line will do

**Comment by Tyriar** [comment]
@meganrogge fuzzy search is more of a search mode which are typically represented as toggled. Usually _filters_ (the dropdown) refine the search space, so a filter-like icon isn't appropriate here imo.

> the button doesn't search - it changes the type of filter used

It defines how a search happens, so the icon indicates search + a modifier which is a fuzzy line.

@misolori revisiting those ideas that @meganrogge prefers, the second one seems decent and not too busy, what do you think? Maybe better with `a-c` or `a-d` as `b` could indicate it comes after `a`? We could do a team poll

![image](https://user-images.githubusercontent.com/2193314/185457764-ba5c2dbc-d8fe-4eca-9917-36d4d295fe7f.png)

**Comment by Tyriar** [comment]
Some more iterations on that idea:

![image](https://user-images.githubusercontent.com/2193314/185458438-25f6d796-e496-477c-88ca-885727505bdc.png)

**Comment by misolori** [comment]
I think those are very minor/small changes that users might confuse them with "Match Whole Word", and I think the feedback from the UX sync was those wouldn't work as best. 

Are we trying to re-visit the icon itself again? I don't think we're going to find an icon that best represents it as it's a hard concept to encapsulate in an icon. I think we should try the one we just merged in and see what the feedback is.

**Comment by Tyriar** [comment]
To verifier: Verify the toggle works as expected/like the button before it
