### ISSUE TITLE
on windows, placeholder decorations after error commands are one line too high

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156375]
![windows-error (1)](https://user-images.githubusercontent.com/29464607/181120382-423a6972-4617-468c-95cb-f872f678c11f.png)

**Comment by meganrogge** [comment]
This looks related to resizing - doesn't repro in an unsplit terminal

**Comment by Tyriar** [comment]
Same root cause: https://github.com/microsoft/vscode/issues/153476
