### ISSUE TITLE
Test drop-in-editor: Press `shift` to drop in editor does not go away after pressing `shift`

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode#156382]
Testing #156223

Press `shift` to drop in editor does not go away after pressing `shift`. It does go away if I move the mouse. 

Should there be a similar note about when happens when you release shift?

**Comment by mjbvz** [comment]
What os? Works fine for me on macOS 

Previously reported in #150995

**Comment by karthiknadig** [comment]
LinuxMint 20.3
