### ISSUE TITLE
Test drop-in-editor: API description wording nitpick

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#156376]
Testing #156223

I read the part that said "The user can drop into a text editor by holding down `shift` while dragging." in the API comment and kept doing a `shift` then a `drag` because I'm used to actions being a `press key` + `mouse action`. Is there a way to emphasize more that you press shift once your left mouse button is down? Like perhaps "The user can drop into a text editor by holding down shift when you are already dragging your file (`drag`+`shift`)". Not too sure what the best wording would be.

**Comment by mjbvz** [comment]
Agreed but it's kind of hard to express this in a concise way. I'll update this to try to make two points more clear:

1. Only files require holding down shift. Dropping normal text does not
2. You hold shift **while** dragging, not shift+drag
