### ISSUE TITLE
No title bar context menu on Linux

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#156397]
Testing #156220

On Ubuntu with Window: Title Bar Style set to `custom`, I can't bring up the title bar context menu, neither with a mouse, trackpad, or Shift+F10.

**Comment by sbatten** [comment]
Assigning to this milestone to investigate, may get pushed back

**Comment by sbatten** [comment]
After investigation, it looks like Linux suffers from the same issue as Windows did (no mouse events in draggable regions). I implemented the window hook for Windows but this is not an option on Linux (at least the hook is a Windows-only thing). As the custom title bar is not the default for Linux, we can live with this, as you can still right click the menu bar, command center, or layout controls to hide them.

**Comment by gregvanl** [comment]
I can bring up the context menu if the cursor is over the menu bar.

**Comment by lukins** [comment]
> Testing #156220
> 
> On Ubuntu with Window: Title Bar Style set to `custom`, I can't bring up the title bar context menu, neither with a mouse, trackpad, or Shift+F10.

**Comment by deepak1556** [comment]
Closing as this doesn't seem to be a blocker and is more of a good to have. Can revisit if there is need in the future.
