### ISSUE TITLE
"Contigous" should be "Continuous"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#156324]
Testing #156002

English is not my native language but I think "continuous" is better fitting here.

Just my suggestion. Feel free to ignore.

![Screenshot 2022-07-26 at 18 55 49](https://user-images.githubusercontent.com/1926584/181065588-3a37abf3-711c-4518-9ff9-c66ed1cc3cc3.png)

![Screenshot 2022-07-26 at 18 56 17](https://user-images.githubusercontent.com/1926584/181065719-05abb518-7d35-4bf0-be22-b089f92d4e57.png)

![Screenshot 2022-07-26 at 18 54 03](https://user-images.githubusercontent.com/1926584/181065541-74fb8f64-9177-45f7-9ef3-790ee5e5076d.png)

**Comment by meganrogge** [comment]
I found `Contiguous` confusing as well

**Comment by meganrogge** [comment]
Actually, we're just using what others use https://github.com/microsoft/vscode/blob/189950f732aad4ab864e6b68efce5d25bfc9a8d9/src/vs/base/parts/quickinput/common/quickInput.ts#L300

so this change would need the input of @TylerLeonhardt

**Comment by Tyriar** [comment]
I think contiguous is the right word, though I admit its meaning may not be clear to a lot of people. Continuous is equally confusing if not more though imo

**Comment by Tyriar** [comment]
@meganrogge i added that option to quick pick FYI

**Comment by Tyriar** [comment]
I'm the future this will probably be a mode button like in the find widget and we could probably avoid using contiguous at all outside of docs ad the button will toggle fuzzy search

**Comment by Tyriar** [comment]
Let's solve this in https://github.com/microsoft/vscode/issues/156322
