### ISSUE TITLE
Continue working on desktop action does not work

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#156345]
Steps:
1. Make some changes on vscode.dev
2. Use the "continue working on..." command and open in desktop
3. :bug: VS Code opens but nothing loads

https://user-images.githubusercontent.com/35271042/181089282-c2097610-ea14-4383-ac0f-0e29982dbb11.mp4

**Desktop**
Version: 1.70.0-insider (Universal)
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:17:37.262Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

**Web**
Version: 1.70.0-insider
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:17:04.193Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36

**Comment by joyceerhl** [comment]
This action should be disabled in vscode.dev since we cannot access the local filesystem from the browser.

**Comment by rzhao271** [comment]
I'm still able to run the `remoteHub.continueOn` command from insiders vscode dev in Firefox. My Desktop Insiders then opens the repo using remote repositories but on the main branch instead of the branch I was working on. I'm not sure if this is the expected behaviour

**Comment by misolori** [comment]
I verified that this now works as expected

https://user-images.githubusercontent.com/35271042/181860180-4d9e0d87-4c82-4d4f-84d0-1137bb353885.mp4
