### ISSUE TITLE
C# code snippet for constructor doesn't reflect class name

### ISSUE THREAD

**Issue by sophistyx** [Microsoft/vscode#15636]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.2|
|debugger-for-chrome|msjsdiag|2.2.2|

---

Steps to Reproduce:

1.Create a C# class - Foo.cs
2.In the code editor for this class, type ctor and press the tab key.

The generated constructor is called 'ClassName' and injects what appears to be a placeholder for Parameters.

**Comment by ramya-rao-a** [comment]
Language features for C# are implemented by the C# extension and not VS Code. Please log the bug in the repo for the extension that you are using for C#
