### ISSUE TITLE
learn more about shell integration goes to the wrong link

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156330]
It goes here https://code.visualstudio.com/docs/terminal/basics#_shell-integration

**Comment by meganrogge** [comment]
should go here https://code.visualstudio.com/docs/terminal/shell-integration

**Comment by meganrogge** [comment]
or perhaps better https://code.visualstudio.com/docs/terminal/shell-integration#_features

**Comment by Tyriar** [comment]
We should fix this one for July, small change with big impact
