### ISSUE TITLE
Rerunning `ls` appends `--color=auto` to executed command

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#156385]
Testing #156001

In Remote-WSL + bash + subshell, if I run `ls` and then use the command decoration to rerun the command, it instead runs `ls --color=auto`.

![image](https://user-images.githubusercontent.com/30305945/181131346-70626e1b-275d-453d-91d3-2da2da2b1355.png)

**Comment by Tyriar** [comment]
This is also the reason `git` may be replaced by `hub`; we're sending the alias resolved command line instead of the raw command line as input.

**Comment by Tyriar** [comment]
We should also verify this doesn't happen with aliases in zsh

**Comment by meganrogge** [comment]
fyi verifier, reproduces in normal `bash` in a non-subshell

**Comment by meganrogge** [comment]
to reproduce:
1. run `alias` in a `bash` terminal to see the ones you've defined
2. run the part to the left of `=`
3. via the command decoration menu, `rerun command`
4. 🐛 the command's alias (part to the right of `=`) is the input

**Comment by meganrogge** [comment]
> We should also verify this doesn't happen with aliases in zsh

it does not

**Comment by meganrogge** [comment]
the alias value is also displayed in the `run recent command` quickpick atm

**Comment by Tyriar** [comment]
I thought of an even better idea to what we talked about, we could use the old history method to supplement our current better method; if there are no problematic histcontrol settings and the latest history command changed between precious and now, assume it was an alias and use that?

**Comment by Tyriar** [comment]
@joyceerhl could you verify this one when you get a chance?

**Comment by joyceerhl** [comment]
🤔 still seems to repro in Remote-WSL 
![image](https://user-images.githubusercontent.com/30305945/186205342-a457799a-cf3c-4f0d-90f7-082874dd79fb.png)

Version: 1.71.0-insider (user setup)
Commit: e3043ebbc6f73fe66beb80ce6312818ae0e66798
Date: 2022-08-23T10:56:12.685Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

**Comment by Tyriar** [comment]
Does `echo $HISTCONTROL` show anything? My Ubuntu wsl shows `ignoreboth` in which case we cannot use that history method which is a known issue.

**Comment by joyceerhl** [comment]
Yeah the output is `ignoreboth`. Is there a value I can change that to which would allow me to verify the fix?

**Comment by Tyriar** [comment]
@joyceerhl it can be set to the empty string or `ignorespace`

**Comment by joyceerhl** [comment]
✅ 
<img width="278" alt="image" src="https://user-images.githubusercontent.com/30305945/186211423-9329043d-6688-4c7f-9319-045f32dd5cdc.png">
