### ISSUE TITLE
Select debug session "Search for debug session by name" -> "Search debug session by name"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#156311]
Testing #156193

Placeholder could be more concise, for example 
"Search for debug session by name" -> "Search debug session by name"

![Screenshot 2022-07-26 at 17 56 36](https://user-images.githubusercontent.com/1926584/181053460-98028dc9-8e5d-4c7e-9eab-bffc21fd12e5.png)

**Comment by andreamah** [comment]
Would it be better to have "Search debug sessions by name"? I noticed that the loaded script view says "Search loaded scripts by name".
<img width="754" alt="image" src="https://user-images.githubusercontent.com/31675041/181126868-c49b3b7b-be68-4384-9dfd-b25048f9ae62.png">

**Comment by isidorn** [comment]
The plural makes sense to me :)
Thanks
