### ISSUE TITLE
Terminal Editor file drag and drop tried to open file instead of pasting path

### ISSUE THREAD

**Issue by ssigwart** [microsoft/vscode#156390]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: MacOS BigSur and Monterey

Steps to Reproduce:

1.  Open a terminal editor.
2. Drag a file from Finder into the terminal.  This tries to open the file (unlike when the terminal is in the panel, which will paste the path).

**Comment by Matrixx420** [comment]
> 
> 
> 
> 
> 
> 
> 
> Does this issue occur when all extensions are disabled?: Yes
> 
> 
> 
> - VS Code Version: 1.69.2
> - OS Version: MacOS BigSur and Monterey
> 
> Steps to Reproduce:
> 
> 1.  Open a terminal editor.
> 2. Drag a file from Finder into the terminal.  This tries to open the file (unlike when the terminal is in the panel, which will paste the path).
>

**Comment by ssigwart** [comment]
I found that if I prevent the following code from executing, it works.
https://github.com/microsoft/vscode/blob/8f25356ff191f125332b00c64dd169d7273d1cec/src/vs/workbench/browser/parts/editor/editorDropTarget.ts#L146-L213

So it seems like `editorDropTarget.ts` prevents the following code to handle pasting the file path.
https://github.com/microsoft/vscode/blob/8f25356ff191f125332b00c64dd169d7273d1cec/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L2595-L2633

I did find that if you hold Shift before starting to drag the file, it will paste due to this code:
https://github.com/microsoft/vscode/blob/8f25356ff191f125332b00c64dd169d7273d1cec/src/vs/workbench/browser/parts/editor/editorDropTarget.ts#L149-L152

I'm guessing there's some way to get that to realize it's a terminal editor and return as well.

**Comment by ssigwart** [comment]
I submitted PR #156398 for this.

**Comment by lramos15** [comment]
File is still opened

**Comment by Tyriar** [comment]
@lramos15 did you hold shift? That's the method of passing the file through to the editor

**Comment by amunger** [comment]
works correctly with shift held
