### ISSUE TITLE
Javascript syntax highliting issue

### ISSUE THREAD

**Issue by iMasoud** [Microsoft/vscode#15639]
- VSCode Version: 1.7.1
- OS Version: linuxMint KDE 18

Steps to Reproduce:

1. create new js file in vscode
2. paste attached js code in that file

![screenshot_ _](https://cloud.githubusercontent.com/assets/9999208/20389749/7d3a5690-ace0-11e6-9f4d-6321139eb4dc.png)

Attention to url property of message_intity which has different color than it's siblings.

[mongoose.txt](https://github.com/Microsoft/vscode/files/597331/mongoose.txt)

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#360

**Comment by ramya-rao-a** [comment]
@aeschli Moving this to Typescript-TmLanguage repo
