### ISSUE TITLE
Provide syntax highlighting for edit session file preview

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#156336]
Testing #156211

I saved multiple edit sessions for the same repo:

![image](https://user-images.githubusercontent.com/25310137/181079477-1f185480-5703-48bf-b830-13b21370b7fe.png)

Could we provide any more info about the edit session? Just looking at the 3 top-level options, I wasn't sure which session was most recent, or what repo they were for.

When I click on the file that was changed (the `README` in this case), I don't get any highlighting - is it possible to provide some highlight of what was changed (like we'd see if this was a change in GH)?

![image](https://user-images.githubusercontent.com/25310137/181079782-3fb27370-6314-4da7-87ec-e795221530c2.png)

**Comment by bamurtaugh** [comment]
I think this is a dupe of https://github.com/microsoft/vscode/issues/156334, so I'll close this.

**Comment by joyceerhl** [comment]
Closing as this appears to be fixed now.
