### ISSUE TITLE
Resuming edit session flow is odd

### ISSUE THREAD

**Issue by misolori** [microsoft/vscode#156368]
Testing #156211

Steps:
1. Have some edit sessions saved from a previous session
2. Open sessions view
3. Resume edit sessions
4. :bug: Session is removed from list and it's unclear what happened

I expected for 1) edit sessions to persist or at least ask if I want to keep them saved and 2) to open the SCM view that has the list of changes. It feels like I am dropped off at a dead-end.

https://user-images.githubusercontent.com/35271042/181111229-0c5d615a-2910-45c2-83d6-617db533e4cf.mp4

**Comment by joyceerhl** [comment]
Closing as not planned since we are moving towards automatic rather than manual edit session management starting with Continue Working On.
