### ISSUE TITLE
Configurable/Themable squiggles

### ISSUE THREAD

**Issue by felixsanz** [Microsoft/vscode#15633]
When you click on a variable, all variables with the same name are highlighted. It is possible to change that background color? I can't find it anywhere in the source (but anyway there is alpha opacity for sure, so i don't know the real color) and looks like is not themeable. It doesn't appear in the devtools also.

The same happens for the red line of errors and green line of warnings, i know this is not themeable but there is no way to change it even messing with core files?

**Comment by alexandrudima** [comment]
The selection highlight color is configurable from a theme file via the setting named `selectionHighlight`.

Due to them being painted as images, currently the squiggles style or color are not configurable from a theme.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/9819
