### ISSUE TITLE
Watch tasks not reconnecting/restarting in WSL

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#156363]
Testing #155349

I used the compile task in https://github.com/Microsoft/vscode-python, and set
```json
{
    "task.experimental.reconnection": true
}
```
in remote settings. The compile task simply disappeared on Windows reload.

**Comment by meganrogge** [comment]
believe this is a duplicate of #156899, so will have been fixed

**Comment by roblourens** [comment]
If it's a duplicate, you can tag it as such so it doesn't get verified twice
