### ISSUE TITLE
settings revert to prior value when focus is changed on `insiders.vscode.dev`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156355]
Testing #156188

On edge and safari
https://user-images.githubusercontent.com/29464607/181098982-bfe71299-8ff2-41aa-98bc-0e99adbd17f4.mov

https://user-images.githubusercontent.com/29464607/181099136-4664eac5-46cc-49f6-821a-28fd861125ae.mov

**Comment by meganrogge** [comment]
does not reproduce in Chrome

**Comment by sandy081** [comment]
Can't repro in Safari. Can you please check if there are any errors in the dev tools/console and Log (Window). Can you also please open the corresponding settings.json file and see if the value is getting written?

**Comment by meganrogge** [comment]
@sandy081 it is getting written to the settings.json file correctly. 

Error in the console:

```
workbench.web.main.js:83 
 Uncaught (in promise) Canceled: Canceled
    at l.cancel (https://main.vscode-cdn.net/insider/9cf2fab…/out/vs/workbench/workbench.web.main.js:83:13728)
    at Qt.onSearchInputChanged (https://main.vscode-cdn.net/insider/9cf2fab…/out/vs/workbench/workbench.web.main.js:2721:83866)
    at https://main.vscode-cdn.net/insider/9cf2fab…/out/vs/workbench/workbench.web.main.js:2721:67106
    at https://main.vscode-cdn.net/insider/9cf2fab…/out/vs/workbench/workbench.web.main.js:83:13464
```

no errors in the output log for the window

**Comment by sandy081** [comment]
> it is getting written to the settings.json file correctly.

@rzhao271 Seems UI issue?

**Comment by rzhao271** [comment]
The settings profiles enabled setting should now ask the user to reload when its value is toggled. @meganrogge I'm wondering if you're able to repro the issue with other settings, still?

**Comment by meganrogge** [comment]
yes @rzhao271 still can repro in edge

**Comment by meganrogge** [comment]
https://user-images.githubusercontent.com/29464607/181842152-8aa81f5b-e174-403f-8b64-2db331e33a10.mov

**Comment by rzhao271** [comment]
I just noticed that your Settings editor doesn't seem to have either scope selected. Is it still in that state on the latest Insiders, or do you remember how the editor got to that state?

**Comment by meganrogge** [comment]
cannot repro
