### ISSUE TITLE
Dropping in editor doesn't work anymore

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#156352]
Testing #156223

* open the emoji picker (ctrl+cmd+space)
* drag an emoji into the code editor
* observe that nothing happens
* from adding a breakpoint, I can observe that [`onDrop`](https://github.com/microsoft/vscode/blob/f3ce5b3a508610f73527e481a76ab011560db5b9/src/vs/editor/browser/widget/codeEditorWidget.ts#L383) is never invoked
* I'm not sure what's wrong, the same steps work fine when loading the editor by itself in a browser using `monaco-editor`.

https://user-images.githubusercontent.com/5047891/181095870-314ff05c-abbf-4684-8686-6bdffdc40bda.mp4

**Comment by mjbvz** [comment]
Seems to require holding down shift at the moment even though there is no overlay saying this

**Comment by bpasero** [comment]
I cannot drop an emoji into the monaco playground and also not into the TS playground. It also does not work in insiders.vscode.dev. 

However it works on stable vscode.dev when holding Shift as Matt suggested.

**Comment by bpasero** [comment]
Sorry, I think I got confused because in my insiders I have configured `"editor.dragAndDrop": false`, so I do not see the drop indicator.

I see no difference in behaviour between VSCode stable and insiders, so it is not a regression as far as I can tell.

I can confirm that pressing `Shift` makes this work 🤷

**Comment by bpasero** [comment]
On our playground it does not work either but I am not even seeing the drop indicator:
![Recording 2022-07-27 at 06 52 27](https://user-images.githubusercontent.com/900690/181164205-d7cebab1-7f7f-42df-a163-793bf6ef6771.gif)

**Comment by alexdima** [comment]
The editor at https://microsoft.github.io/monaco-editor/ is around 6 months old, so there it doesn't work at all, I acknowledge that. In my original screen recording I was running the editor from sources. I am quite certain this used to work at some time (when Matt first did the PR at https://github.com/microsoft/vscode/pull/147049). I'll try bisecting to see if that points to anything.

**Comment by alexdima** [comment]
`git bisect` points to 23c073031e5fb172a69b566dd33cac9d740981f1
```
23c073031e5fb172a69b566dd33cac9d740981f1 is the first bad commit
commit 23c073031e5fb172a69b566dd33cac9d740981f1
Author: Matt Bierner <matb@microsoft.com>
Date:   Wed Jun 8 16:09:36 2022 -0700

    Show drag uis as soon as shift is released (#151569)

    Fixes #150995

 src/vs/workbench/browser/parts/editor/editorDropTarget.ts | 1 +
 1 file changed, 1 insertion(+)
```

**Comment by alexdima** [comment]
If I comment out the following lines, then dropping text from TextEdit works, otherwise it doesn't:

```diff
diff --git a/src/vs/workbench/browser/parts/editor/editorDropTarget.ts b/src/vs/workbench/browser/parts/editor/editorDropTarget.ts
index 947f4475f3b..a8d974bc4c8 100644
--- a/src/vs/workbench/browser/parts/editor/editorDropTarget.ts
+++ b/src/vs/workbench/browser/parts/editor/editorDropTarget.ts
@@ -597,11 +597,11 @@ export class EditorDropTarget extends Themable {
 	private registerListeners(): void {
 		this._register(addDisposableListener(this.container, EventType.DRAG_ENTER, e => this.onDragEnter(e)));
 		this._register(addDisposableListener(this.container, EventType.DRAG_LEAVE, () => this.onDragLeave()));
-		this._register(addDisposableListener(this.container, EventType.DRAG_OVER, e => {
-			if (!this.overlay) {
-				this.onDragEnter(e);
-			}
-		}));
+		// this._register(addDisposableListener(this.container, EventType.DRAG_OVER, e => {
+		// 	if (!this.overlay) {
+		// 		this.onDragEnter(e);
+		// 	}
+		// }));
 		[this.container, window].forEach(node => this._register(addDisposableListener(node as HTMLElement, EventType.DRAG_END, () => this.onDragEnd())));
 	}
 ```

### without the change, running from source:


https://user-images.githubusercontent.com/5047891/181194245-e5e17c0f-3d80-4ab0-aaaa-701ee78682d8.mp4



### with the change, running from source:

https://user-images.githubusercontent.com/5047891/181194122-4a53fb0a-807e-4f02-ab96-11ebc6c27d01.mp4

**Comment by mjbvz** [comment]
The safest if seems to be reverting the fix for #150995 by commenting out the block of code. Will push that for July and then investigate a proper solution that also fixes #150995 in August

**Comment by joyceerhl** [comment]
Can't seem to get this to work with the Windows emoji picker and the drag/drop extension sample. Does this only work on mac?

**Comment by mjbvz** [comment]
@joyceerhl I only tested on Mac and don't know if this is supported on windows. Can you drag emoji into other apps, such as notepad?

**Comment by joyceerhl** [comment]
Doesn't look like it. Will close and leave for someone on mac to verify then.
