### ISSUE TITLE
Tree node names not clear

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#156337]
Testing #156211

When working with a single repo, it's a little annoying that there is a parent node for the repo name when I don't have other siblings. It's also odd

<img width="348" alt="CleanShot 2022-07-26 at 11 01 15@2x" src="https://user-images.githubusercontent.com/35271042/181078681-2eb6e130-5a9a-463c-898b-85e4740d4672.png">

## Suggestion

I'd suggest to maybe using another identifier, like the machine name, and moving the repo name to the details:

<img width="328" alt="CleanShot 2022-07-26 at 11 06 58@2x" src="https://user-images.githubusercontent.com/35271042/181079972-b8c52981-39fc-4a36-a59f-738011c6f321.png">

**Comment by joyceerhl** [comment]
\closedWith f3fbdc328ff8f22f579608cb4429813d8aaaecf3
