### ISSUE TITLE
Scary 'Files within the installation' notification shown when navigating into built-in d.ts

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156370]
1. Create a JS file: 

```js
fetch('http://example.com')
```

2. Go to definition on `fetch`

**Bug**
I see this scary notification:

<img width="671" alt="Screen Shot 2022-07-26 at 2 31 10 PM" src="https://user-images.githubusercontent.com/12821956/181115799-1890ff0f-6e62-47fc-8895-b279d0d24b57.png">

In this case, the user was likely just trying to view the file 

Would it be possible to either:

1. Only show this notification when saving?
2. Always open these `d.ts` file as `readonly`?

**Comment by bpasero** [comment]
This came in via https://github.com/microsoft/vscode/pull/155443 from @gjsjohnmurray and I think is not good. This also reminds me that when debugging you may end up in a file from the installation dir.

I think we should probably revert the change for now and think about a better solution unless there are objections.

**Comment by gjsjohnmurray** [comment]
@bpasero I agree. Maybe pursue your earlier suggestion of opening all installation directory files in readonly mode. Perhaps combine with a scary warning if you save a new file in there.
