### ISSUE TITLE
No feedback on no network connectivity when I tried to install an extension

### ISSUE THREAD

**Issue by ricardoferreira1980** [Microsoft/vscode#15630]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Install latest VS Code
2. Clicked on Extensions
3. Selected "Debugger for Chrome"
4. Clicked "Install"
5. The button says "Installing" forever, and no feedback is given on the progress or success of the operation.

**Comment by ricardoferreira1980** [comment]
I was with connectivity problems. I am keeping the case, since tool should state that instead of "installing" forever and show no feedback to the user.

**Comment by joaomoreno** [comment]
Code was very likely still installing, due to the connectivity problems.
