### ISSUE TITLE
The C# 'Generate variable' feature produces nothing

### ISSUE THREAD

**Issue by sophistyx** [Microsoft/vscode#15637]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.2|
|debugger-for-chrome|msjsdiag|2.2.2|

---

Steps to Reproduce:

1.Create a new C# class
2.In any method or constructor introduce a new variable, e.g. _foo = 10;
3.Place the cursor on the variable name and Ctrl + .
4. Select 'Generate variable'

The expectation is that there will be a class-level field, e.g. private int _foo but there is nothing whatsoever.

**Comment by sophistyx** [comment]
also, might want to rename the option 'Generate field'

**Comment by ramya-rao-a** [comment]
Language features for C# are implemented by the C# extension and not VS Code. Please log the bug in the repo for the extension that you are using for C#
