### ISSUE TITLE
Title bar context menu action name polish

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#156308]
Testing #156220

I suggest that:

"Show Command Center" should be renamed to "Command Center"
"Show Layout Controls" should be renamed to "Layout Controls"

That way it would be easier to read and would align with Status Bar and Activity Bar where we do not use the verb "Show".

![Screenshot 2022-07-26 at 17 16 05](https://user-images.githubusercontent.com/1926584/181044311-dff2deb7-766f-4d1d-af9a-65e7d8067dc2.png)

**Comment by misolori** [comment]
I also think the main difference is the activity/status bars are one-way actions vs the title bar that has the ability to show AND hide items. It closer maps to the view menus:

<img width="554" alt="CleanShot 2022-07-26 at 10 48 19@2x" src="https://user-images.githubusercontent.com/35271042/181075993-3890ade9-7e4c-4163-beea-1cdb63380190.png">
