### ISSUE TITLE
Unagle to read file: cellAttachmentRenderer

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156346]
Type: <b>Bug</b>

1. Open ipynb notebook

**bug**
In dev tools, see:

```
Error: Unable to read file '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/out/cellAttachmentRenderer.js' (Error: Unable to resolve nonexistent file '/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ipynb/out/cellAttachmentRenderer.js')
    at h.doReadFileStream (fileService.ts:573:11)
    at async w (resourceLoading.ts:68:18)
    at async n.loadResource (webviewElement.ts:820:19)
```

VS Code version: Code - Insiders 1.70.0-insider (Universal) (cc098faebd320a2eea3da6ae154b7e2e1347a4b9, 2022-07-26T05:17:37.262Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 4, 4|
|Memory (System)|32.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d --inspect-extensions=25732 --crash-reporter-id 48781ca2-1705-4f64-9bab-325055aab55d|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mjbvz** [comment]
Looks like the `out` directory is excluded from publish: 

https://github.com/microsoft/vscode/blob/db9e8fba63e4478dc512ee63ec08fb537283d01c/extensions/ipynb/.vscodeignore#L3

@Yoyokrazy You likely want to have the notebook code go to a different directory, such as `notebook-out` instead of the `out` dir

**Comment by Yoyokrazy** [comment]
Just changed that inside esbuild, didn't realize that out wasn't included. I had been having an issue with needing to run `npm run build-notebook` while using OSS, could that be related?

I'll make a PR to adjust `package.json` and `esbuild.js`
