### ISSUE TITLE
Reformatting breaks code syntax or deletes chars since this mornings update.

### ISSUE THREAD

**Issue by mredbishop** [Microsoft/vscode#15635]
- VSCode Version:
**Version 1.8.0-insider
Commit 1b95a2f7a7e8858c5612807522a6f8cd8e03c1dc
Date 2016-11-17T07:19:20.285Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0**

- OS Version: **Ubuntu 16.04 fully updated.**

Steps to Reproduce:

![peek 2016-11-17 11-58](https://cloud.githubusercontent.com/assets/1096293/20388578/6ea11ae2-acbd-11e6-8ab5-d38ebb3590a8.gif)

![peek 2016-11-17 12-03](https://cloud.githubusercontent.com/assets/1096293/20388725/19414c60-acbe-11e6-9bf0-ecc2bc066035.gif)

1. Go to code
2. Format code

Seems to happen regardless of whether format is required?

Let me know if you need any more info.

Cheers,

Ed

**Comment by jrieken** [comment]
fixed with 8bb00429823dcad95b9945e88e84924f47a4f2ca
