### ISSUE TITLE
opening `settings.json` with the button does not work on `insiders.vscode.dev`

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156357]
Testing #156188
On edge and safari
Clicking the open settings.json button doesn't do anything unless I split the settings editor

https://user-images.githubusercontent.com/29464607/181099408-786a21cf-03df-47d1-9b55-3a0a75668d0d.mov

**Comment by meganrogge** [comment]
Does not reproduce in Chrome

**Comment by rzhao271** [comment]
Resolved
