### ISSUE TITLE
masOS $SHELL variable still /bin/zsh

### ISSUE THREAD

**Issue by Mercbot7** [microsoft/vscode#156442]
Issue Type: <b>Bug</b>

I have installed bash using brew and desire that to be my default shell. I hvae run `chsh -s /opt/homebrew/bin/bash` to set my default shell for my user and my `/etc/shells` looks like this:

```
/bin/bash
/bin/csh
/bin/dash
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/pwsh
/opt/homebrew/bin/bash
```

When I open a new terminal in VSCode and run `echo $SHELL` it get `/bin/zsh` and my `$PATH` variable includes the `$PATH` config from my `.zshrc` file. This is not the desired outcome. I would expect the default system shell to be used as the base. 

Is there a hardcoded shell for VSCode? if not why is it not honoring the default system config. If so, why? This does nto really give me the flexibility to have different shell environemnts and control of my dev environment.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:32:39.000Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.43GB free)|
|Process Argv|--crash-reporter-id 3b79998c-1229-4c1d-aecf-9aa62998845e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.14.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
gitlab-workflow|Git|3.47.2
go|gol|0.35.1
terraform|has|2.23.0
vscode-drawio|hed|1.6.4
jsonnet|hep|0.1.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.22.1
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
makefile-tools|ms-|0.5.0
powershell|ms-|2022.6.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
scala|sca|0.5.5
markdown-preview-enhanced|shd|0.6.3
shellcheck|tim|0.19.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
841h4636:30534993

```

</details>

**Comment by juliuscc** [comment]
I am also getting issues with this. For me I want to use zsh but VS-Code insists on using sh. My workaround is to add `"terminal.integrated.defaultProfile.osx": "zsh",` to the settings.

What is worse is that even though the terminal uses zsh, the git-commands that I run through VS-Code do not use the correct shell. So if I press "Commit" in the source control tab VS-Code runs `git commit` using `sh` i the background.

We run some git hooks that don't work in my sh-shell (only in zsh) and therefore I get errors when I try to commit.

**Comment by juliuscc** [comment]
Here is my debug information:

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:39:20.716Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

**Comment by juliuscc** [comment]
I also use a Mac M1 processor (specifically Apple M1 Pro)

**Comment by meganrogge** [comment]
is it also `/bin/zsh` for the second terminal you create?

**Comment by Mercbot7** [comment]
So for me. When I open a "bash" terminal in VSCode it a bash session, however, as mentioned above, it seems to be a subshell of zsh regardless of changing the system default to bash and to top it off the `.zshrc` file is evaluated for the parent shell and then the `.bashrc` is being evaluated and the subshell inherits the ENV variables from the parent shell. This is not the desired functionality. At the least VSCode should use the default shell of the user as it's base shell and better yet it will just spin up the desired shell based on the configured selection, not as a subshell. also, the mentioned "bash" ENZv variable `$SHELL` is not set to the appropriate shell, rather it is to the parent.

**Comment by juliuscc** [comment]
> is it also /bin/zsh for the second terminal you create?

- My system default is `/bin/zsh`
- Whenever I open a new terminal in VS-Code it opens `/bin/sh` (before changing any settings)
- I have changed the default in settings so that new terminals open `/bin/zsh`
- Git-commands in VS-Code (not terminal) still uses `/bin/sh`

My teammate got the exact same problem at the same time, which was around two-three weeks ago.

Here is my settings file:

<details>
  <summary>Settings file</summary>

```json
{
  "workbench.colorTheme": "Default Dark+",
  "editor.formatOnSave": true,
  "window.restoreFullscreen": true,
  "[jsonc]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "workbench.sideBar.location": "right",
  "workbench.startupEditor": "none",
  "editor.minimap.enabled": false,
  "gitlens.hovers.currentLine.over": "line",
  "gitlens.codeLens.enabled": false,
  "gitlens.currentLine.enabled": false,
  "githubPullRequests.fileListLayout": "tree",
  "git.autofetch": true,
  "editor.experimental.stickyScroll.enabled": true,
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "terminal.integrated.defaultProfile.osx": "zsh",
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "githubPullRequests.terminalLinksHandler": "github",
  "window.zoomLevel": 1,
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```

</details>

**Comment by meganrogge** [comment]
When vscode starts up, we run `$SHELL -ilc` to source the environment in which to create the terminal. This only happens when you open VS Code from the dock. 

Can you try to reproduce the issue when you:
1. close all windows and open it from the dock
2. close all windows and run code from an external terminal to launch it

**Comment by Mercbot7** [comment]
@meganrogge I also used "terminal.integrated.defaultProfile.osx" to set my default to "bash" and it now uses the appropriate shell, however the docs indicate to me that this is being deprecated or not the desired way to configure shells in VSCode. I will remove that setting and try what you recommend and see respond back with results.

**Comment by ladyrick** [comment]
me too.

**Comment by meganrogge** [comment]
I can reproduce this issue in an external terminal (Iterm), so believe this is set by macOS somehow. @Tyriar pls lmk if you have other thoughts.
