### ISSUE TITLE
Test: zen mode

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#15647]
- [x] win @seanmcbreen 
- [x] os x @chrisdias 
- [ ] linux @bgashler1 

Complexity: 3
Refs: https://github.com/Microsoft/vscode/issues/12940

As per popular demand we have added zen mode to vscode. Verify:
* Going in and out of zen mode is a smooth process (view menu, command palette, keybinding)
* Zen mode hides all workbench parts and goes into full screen
* You are still able to open workbench parts (sidebar, panel...) in zen mode
* Going out of full screen while in zen mode takes you out of zen mode
* Setting `workbench.fullScreenZenMode` is respected

**Comment by jochenvw** [comment]
Sweet ! Looking forward to this feature 👍

**Comment by isidorn** [comment]
@jochenvw you can use the insiders build as it has it right now (though shortcut key is going to be changed in the tomorrow's build)

**Comment by jochenvw** [comment]
@isidorn Excellent - I'm a preview user now :)

**Comment by isidorn** [comment]
@bgashler1 I know you tested this item but not sure if you finished -> if yes just check off your checkbox here so we can close this test item.

**Comment by bgashler1** [comment]
✅ just found one little issue that may be by design (above).
