### ISSUE TITLE
Terminal file links and go to file with columns take a tab as multiple columns

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#156439]
Testing https://github.com/microsoft/vscode/issues/140780

1. Have a file link in the terminal with a line number and a column
2. Click it to open and reveal the file
3. 🐛 The line number is correct but the column is off by two
![Recording 2022-07-27 at 09 55 21](https://user-images.githubusercontent.com/4544166/181265084-39691b29-0448-40d1-8f98-b92b99ab9485.gif)

**Comment by Tyriar** [comment]
This works fine for me now

**Comment by Tyriar** [comment]
@lramos15 that's because tabs consume multiple columns

**Comment by Tyriar** [comment]
@alexdima navigating to `/Users/daimms/dev/microsoft/vscode/.eslintrc.json:50:40` in the quick pick opens up line 50, col 46 for me. Guessing this might be related to recent tab size work? You might need to pass this on to Ben?

**Comment by alexdima** [comment]
Yes, we interpret the second value as the character offset. This is explained better in the go to line dialog `ctrl+g`:
>  <img width="614" alt="image" src="https://user-images.githubusercontent.com/5047891/205866448-f8428a1e-407a-41fe-9779-d468156891b2.png">

So when going to `.eslintrc:50:40` we will set the cursor in front of character 40. This is visible in the selected count:

> <img width="422" alt="image" src="https://user-images.githubusercontent.com/5047891/205866626-5d9c90b6-a694-40f9-b602-53e54a6a387a.png">

The reason for this is that such links are usually produced by tools which deal with characters (e.g. compilers) and these tools will not be aware of the configured tab size, etc.

The value shown in the status bar is more the "visible column" not the character offset. Also, this hasn't been changed with the `indentSize` work.

**Comment by Tyriar** [comment]
> The reason for this is that such links are usually produced by tools which deal with characters (e.g. compilers) and these tools will not be aware of the configured tab size, etc.

@alexdima if tools that give you the link are not aware of the tab size, I would think we should be treating a tab as a single column in links? @lramos15 and I see different results for the link because he has 2 and I have 4 set?

**Comment by alexdima** [comment]
> I would think we should be treating a tab as a single column in links?

Yes, that's what it does today. That is what I wrote above in my comment

> So when going to .eslintrc:50:40 we will set the cursor in front of character 40

Please let me know if you observe something different, using steps to reproduce.

**Comment by Tyriar** [comment]
You're right sorry, I mixed up the col/row
