### ISSUE TITLE
show accessibility help does nothing when not in accessibility mode

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156498]
I'd expect it to at least take me to the accessibility mode setting

**Comment by isidorn** [comment]
@meganrogge thanks for filling this, however I can not reproduce this. Whatever the value of the setting `editor.accessibilitySupport` triggering the command "show accessibility helps" opens the accessibility help widget.
Is this not what you get? If not can you provide repro steps (maybe gif)? Thanks!


![Screenshot 2022-08-05 at 12 22 25](https://user-images.githubusercontent.com/1926584/183057748-ef224b38-8e29-4a0f-9dfe-25c60896ac4b.png)

**Comment by meganrogge** [comment]
Hey Isidor, I have tried to reproduce and can't. It was definitely happening though before I ever enabled that setting. Maybe can repro w a brand new settings profile?

**Comment by meganrogge** [comment]
Okay I'll reopen if I see it again
