### ISSUE TITLE
Windows: All .node files should have Product Name 

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#156408]
Related to https://github.com/microsoft/vscode/issues/73805

> MS VS Code application is getting blocked by AppLocker. 
> [...] the VS Code application which our customer executing on the managed devices doesn't contain product name. 

<img width="304" alt="image" src="https://user-images.githubusercontent.com/22350/181174292-24d53083-b125-4951-be37-ba5293f144f8.png">

**Comment by rzhao271** [comment]
The product name row still doesn't show up.

![Screenshot showing foreground_love.node file properties. There's no product name row](https://user-images.githubusercontent.com/7199958/186249932-1bb56d0f-4afd-45a1-a68e-1f475c49760f.PNG)

**Comment by joaomoreno** [comment]
@rzhao271 You need to rename to `foreground_love.dll` and then check properties.
