### ISSUE TITLE
Zen mode: title broken in this case

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15643]
Steps to Reproduce:

1. go full screen
2. enable zen mode
3. leave full screen

=> for me the custom title is not showing anymore

![image](https://cloud.githubusercontent.com/assets/900690/20390406/05812db0-accf-11e6-85c2-e77b3da4de60.png)

**Comment by isidorn** [comment]
Can not repro 😭

**Comment by isidorn** [comment]
Ahaa I can not repro in out of source since there it is not possible to have the custom title bar for some reasone you menitoned in the standup

**Comment by bpasero** [comment]
Yeah, custom title disabled running out of sources due to some issues with dev tools.

**Comment by isidorn** [comment]
By the way would you in this scenario expect to get out of zen mode or stay in zen mode?

**Comment by bpasero** [comment]
@isidorn I agree with you
