### ISSUE TITLE
wslCode.sh not found

### ISSUE THREAD

**Issue by jovair** [microsoft/vscode#156441]
Issue Type: <b>Feature Request</b>

I´ve reinstalled my wsl ubuntu and it do not found the "/mnt/c/Users/my_user/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh". I tried uninstall and install the Remote - WSL to sove the problem, but it´s worong yet.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Connection to 'WSL: Ubuntu' could not be established  VS Code Server for WSL closed unexpectedly.
Check WSL terminal for more details.

**Comment by aeschli** [comment]
Can you access that location from the Ubuntu side?
