### ISSUE TITLE
Create and remove manual folding range use the same shortcut

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#156489]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/41773861/181278578-efc25747-fa51-4793-8524-01ad0ca29493.png">

_Originally posted by @tjx666 in https://github.com/microsoft/vscode/issues/155302#issuecomment-1196862961_

**Comment by connor4312** [comment]
This doesn't work for me: as soon as I assign the same keybinding to both add and remove the folding range, then creating the folding range no longer works. I can create the folding range from the command palette and then remove it using the keybinding, but cannot create it.

**Comment by alexdima** [comment]
I think the bug was that the two commands are using the same shortcut, and the fix was to assign a different shortcut to one of the commands. Leaving this up to Martin to clarify during August, but I don't think there is anything to be done for July.

**Comment by connor4312** [comment]
It'd be handy if one command worked for both so I could toggle the folded region.

**Comment by aeschli** [comment]
That would be a separate feature request. Closing this issue (fixing the conflict) as fixed.
