### ISSUE TITLE
Add setting to not focus the panel when running selected text in terminal

### ISSUE THREAD

**Issue by zioroboco** [microsoft/vscode#156434]
Currently, the `Run Selected Text In Active Terminal` command always expands and focuses the terminal in the panel.

There are cases where this behaviour is not desirable, e.g. after connecting to a tmux session and then viewing the terminal in the editor area with `Terminal: Create New Terminal in Editor Area`. When sending text to the terminal in this case, a second instance of the same terminal will pop open in the panel (see below).

https://user-images.githubusercontent.com/156733/181252066-72fcb4b5-ef99-4cf9-8800-397987d595a4.mp4

There is no way to configure this at the moment. My suggestion would be a setting like:

```
"terminal.integrated.showPanelOnRunSelectedText": "never",
```

**Comment by Tyriar** [comment]
This should focus the terminal editor in this case, not open the panel

**Comment by meganrogge** [comment]
@Tyriar yep I think we just need to check the terminal's target here which we aren't currently
