### ISSUE TITLE
Integrated Terminal Opens wrong folder from Terminal Pane Button

### ISSUE THREAD

**Issue by ascentcreative** [microsoft/vscode#156461]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2 (Universal)
- OS Version: MacOS Monterey 

Steps to Reproduce:

1. Set a value for Terminal > Integrated: Cwd
2. Click the "+" in the integrated terminal pane
3. Dropdown at the top asks you to select the folder to open in the integrated terminal
4. Terminal tab opens, but at the default directory for the workspace, not the one selected

Note - right clicking the folder from the explorer pane and selecting "Open in Integrated Terminal" works as expected

Seems to have started since the 1.69.2 release.

https://user-images.githubusercontent.com/8314873/181294070-c6c8df36-6550-4530-aa01-c10b1382fe7a.mov

**Comment by meganrogge** [comment]
what happens if you click the settings gear next to `terminal.integrated.cwd` in the settings editor and reset to default?

**Comment by meganrogge** [comment]
also, what are your terminal settings?

**Comment by ascentcreative** [comment]
Hi Megan

If I reset to default (or indeed just remove the path) then it works as expected (as in the video posted)

However, I have a need for a value in there for each of my workspaces - 90% of the time, I need the CWD in a specific place. Just occasionally, I need to get the CWD in a secondary folder (to run a task against that module / package) and this bug stops that working. It seems like the CWD path setting has started overriding the selection from the "+" button - previously, it was just the path used when the Integrated Terminal was opened with no other instructions.

Where would I find the terminal settings you're needing? if you mean the ones from settings.json, they're very basic - all as follows (but with relevant paths for the cwd, based on the project workspace).

 "settings": {
        "terminal.integrated.cwd": "/users/kieran/documents/ascent/kmphoto/kmphoto",
        "terminal.integrated.automationProfile.windows": {
        
        }
    }
    
  Hope that helps?

**Comment by meganrogge** [comment]
I recommend creating a profile where you set that cwd for your 90% and make that your default terminal. Then remove the `terminal.integrated.cwd` setting.

**Comment by ascentcreative** [comment]
Hmm - I disagree.

The operation of the Cwd setting has changed in this last release, and is now broken such that an operation which should override it no longer does. 

When I overtly select the folder I want a new terminal, it should give me that. It makes a mockery of having that dropdown option if the software doesn't respect it.

**Comment by meganrogge** [comment]
Oh I think I understand what's going on here. You're in a multi root repo (multiple folders) so it's by design asking you to choose which to use.

**Comment by ascentcreative** [comment]
Yes, correct. But when I choose one, it doesn't honour it... it gives me whatever is in the Settings. 

This wasn't the operation previously - selecting a folder from the dropdown would be respected.

**Comment by meganrogge** [comment]
Yeah we should either not be showing the quickpick or not be overriding the selected entry

**Comment by ascentcreative** [comment]
Yeah, that would be great. Thanks for re-opening this. The QuickPick worked previously, and is *really* useful. If possible, please keep that going forward :)

**Comment by meganrogge** [comment]
We should not be showing the quick-pick

**Comment by ascentcreative** [comment]
I think you should be showing it - you always used to show it and its much quicker to find a package root in there than it is to scroll through the file explorer pane to find it. Please preserve the existing functionality. Sent from my Galaxy
-------- Original message --------From: Megan Rogge ***@***.***> Date: 03/08/2022  19:15  (GMT+00:00) To: microsoft/vscode ***@***.***> Cc: Kieran Metcalfe ***@***.***>, Author ***@***.***> Subject: Re: [microsoft/vscode] Integrated Terminal Opens wrong folder from Terminal Pane Button (Issue #156461) 
We should not be showing the quick-pick

**Comment by meganrogge** [comment]
We won't show it if you've set `terminal.integrated.cwd` bc that setting is meant to override all other values.

**Comment by ascentcreative** [comment]
That's not much help really. If that's value is not set, then when you open a workspace, the terminal opens to what ever folder you last used. That might not be the main project root. I use the terminal cwd setting to force the *default* to be that folder. After that, I need to be able to simply override the folders I'm opening - the quick pick is a really useful way to do that. The only other option is to scroll through the folder pane, which is cumbersome when you have many expanded tree items. Also, the inference in your post is that even right clicking a folder in the explorer pane should now not allow a folder to override the cwd setting. If this was lost too, vscode would be utterly unusable. As I have said before, the above operation is how it has worked since I started using vscode. It has only become an issue in this recent release. Please do not make the software less usable. If you want a blanket, forced cwd path, please can you also provide a second default option then which allows the quick pick to override it? Sent from my Galaxy
-------- Original message --------From: Megan Rogge ***@***.***> Date: 04/08/2022  16:45  (GMT+00:00) To: microsoft/vscode ***@***.***> Cc: Kieran Metcalfe ***@***.***>, Author ***@***.***> Subject: Re: [microsoft/vscode] Integrated Terminal Opens wrong folder from Terminal Pane Button (Issue #156461) 
We won't show it if you've set terminal.integrated.cwd bc that setting is meant to override all other values.

**Comment by Tyriar** [comment]
This is currently working as designed, if you have a cwd set in the workspace, that will be always used. If not, you get the folder selector and it opens based on that folder's settings.

**Comment by ascentcreative** [comment]
But that's not how it used to work, and now it's a massive pain in the neck.

How can I set a default CWD for a project, but with a picker to select a different one? Currently, I can't, so this update has broken the existing functionality.
