### ISSUE TITLE
Unable to resume edit session in desktop

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#156476]
Testing #156211

This was working yesterday but stopped working today. Started an edit session from the web, went to desktop to try and resume and nothing happens when clicking the action.

https://user-images.githubusercontent.com/35271042/181307544-6b3d2d65-64b0-4ef5-8647-59542d39df4b.mp4

Version: 1.70.0-insider (Universal)
Commit: 9cf2fabdd600c7d8e3230803acb246405321e8dd
Date: 2022-07-27T05:17:51.709Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

**Comment by joyceerhl** [comment]
This is by design--that edit session was created in a different repo (`notebooks`) than you are trying to apply it to (`vscode`). I'm curious about the motivation for wanting to do this?

**Comment by misolori** [comment]
Oh, my expectation is that it would open that repo + changes, like switching workspaces. I see edit sessions as this container in the cloud that I can jump to from any device or project.
