### ISSUE TITLE
Modal Save dialog dismissed in page reload

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#156459]
https://insiders.vscode.dev

Version: 1.70.0-insider
Commit: 9cf2fabdd600c7d8e3230803acb246405321e8dd
Date: 2022-07-27T05:14:49.987Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.0 Safari/537.36 Edg/105.0.1300.0

1) Open an empty window on insiders.vscode.dev
2) Create an untitled file
3) Open a remote repository

You briefly see a Save dialog for the untitled file but the page reload continues. This is not a data loss scenario as the untitled file restores when I go back to step 1.

![CleanShot 2022-07-27 at 08 51 29](https://user-images.githubusercontent.com/4674940/181293381-7bc918d3-4baa-4af3-8071-66b43b7b9c43.gif)

**Comment by bpasero** [comment]
Traced it down to notebook disposing editors on shutdown:

```
closeEditors Error
    at EditorGroupView.closeEditors (http://localhost:8080/static/sources/out/vs/workbench/browser/parts/editor/editorGroupView.js:1267:41)
    at http://localhost:8080/static/sources/out/vs/workbench/contrib/notebook/browser/notebook.contribution.js:367:27
    at Listener.invoke (http://localhost:8080/static/sources/out/vs/base/common/event.js:457:27)
    at PrivateEventDeliveryQueue.deliver (http://localhost:8080/static/sources/out/vs/base/common/event.js:627:38)
    at Emitter.fire (http://localhost:8080/static/sources/out/vs/base/common/event.js:592:37)
    at http://localhost:8080/static/sources/out/vs/workbench/contrib/notebook/browser/notebookServiceImpl.js:483:44
    at http://localhost:8080/static/sources/out/vs/base/common/lifecycle.js:130:17
    at Object.dispose (http://localhost:8080/static/sources/out/vs/base/common/functional.js:18:25)
    at dispose (http://localhost:8080/static/sources/out/vs/base/common/lifecycle.js:99:27)
    at DisposableStore.clear (http://localhost:8080/static/sources/out/vs/base/common/lifecycle.js:166:17)
```

If an editor is disposed, the editor will be closed because it is invalid from that moment on and thus the dialog opens.

This does not reproduce with normal text editors.

**Comment by rebornix** [comment]
https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/notebook/browser/notebook.contribution.ts#L557-L563

The editors are disposed as the serializers are disposed (they run in web extension host). If we are using a file system provider contributed by extensions, we would see the same for text editors too?

**Comment by bpasero** [comment]
Yeah I think when a provider of an editor goes away it is good to ask the user how to proceed when data has not been saved to prevent data loss. But in this case I think we hit the following `dispose` simply because the extension host stops before navigating away from the page:

https://github.com/microsoft/vscode/blob/dbae720630e5996cc4d05c14649480a19b077d78/src/vs/workbench/api/browser/mainThreadNotebook.ts#L48

**Comment by amunger** [comment]
just verifying that the modal does not pop-up for dirty untitled ipynb files, it should behave the same way as an untitled text file.
