### ISSUE TITLE
cant type letter Y

### ISSUE THREAD

**Issue by Przemo1500** [microsoft/vscode#156499]
Issue Type: <b>Bug</b>

Simple as that.  I cant type letter Y. When i do this in right down corner i got message "command python create new file not found". 

I cant type letter Y only when i push windows and Y together. 

What is wrong? 

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Please review https://github.com/microsoft/vscode/wiki/Keybinding-Issues

You might have accidentally defined a keybinding.

**Comment by Przemo1500** [comment]
i found half solution... and possibly fault. 

Im installed kite extension.... I disable it. and uninstal. Then i have the issue with letter Y and warning. 

Solution. 
Uninstal VSC and manually delete configuration files in Users/"your computer name"/Appdata/roaming/code. 
install again VSC.
Works perfectly but now i have configure VSC again... 

This is only half a solution. Somewhere in kite ext is a problem. The configuration file still exists and make bug even when i  uninstall vsc and install again. 
Maybe kite changes bindings ? I dont know. I will try when kite site are back online.
