### ISSUE TITLE
web view context menu: context keys don't seem to work

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#156416]
Testing #156224

Version: 1.70.0-insider
Commit: 9cf2fabdd600c7d8e3230803acb246405321e8dd
Date: 2022-07-27T05:17:51.709Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

Following the steps from #156224, I get context menus in web views, but using the context from `data-vscode-context` doesn't seem to work. Hope I didn't misunderstand the way this should work.

Find the complete sample code here: https://github.com/microsoft/vscode-extension-samples/tree/aeschli/webviewtesting

- using the [webview-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample)
- added
```
				<div class="menu" data-vscode-context='{"webviewSection": "menu", "countOfThing": 123}'>
					<h1>Menu</h1>
					<div class="nav" data-vscode-context='{"webviewSection: "nav", "preventDefaultContextMenuItems": true}'>
						NavNavnavNav22
					</div>
				</div>
```

to the HTML body
- defining two context menu entries:
```
		"menus": {
			"webview/context": [
				{
					"command": "catCoding.foo",
					"when": "webview == 'catCoding' && webviewSection == nav"
				},
				{
					"command": "catCoding.doRefactor",
					"when": "webview == 'catCoding'"
				}
			]
		},
```
- run the sample, run the `Start cat coding session` command
- Right click on `NavNavnavNav22`. 
-> `doRefactor` appears, but not `foo`. Also are all the default commands are present on `NavNavnavNav22`

**Comment by mjbvz** [comment]
This is because the json is invalid (it probably was just copied from from the example). There needs to be a closing quote on `webviewSection`

I'll add some logging to make this error more clear

**Comment by aeschli** [comment]
Thanks, now all works great!
