### ISSUE TITLE
Git Bash doesn't work when selected as a "terminal.integrated.shell.windows"

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#15649]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|theme-monokaiextended|Scatolina|0.0.1|

---

Steps to Reproduce:

1. Set setting: "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\git-bash.exe"
2. Open a terminal with shortcuts [Ctrl+`]
3. See the bug

**Comment by Tyriar** [comment]
@wzup could you install the [Insiders build](https://code.visualstudio.com/insiders) and see if this is fixed? I'm interested to see the error message you get on Insiders as well as it's more useful than stable's message.

**Comment by schmuli** [comment]
As per https://code.visualstudio.com/docs/editor/integrated-terminal, you should use `C:\\Program Files\\Git\\bin\\bash.exe`.

**Comment by wzup** [comment]
@Tyriar 
The answer of @schmuli is correct. Changing the path of `bash` terminal fixed the issue. So you can remove `needs more info` tag if it matters.
However I didn't try [Insiders build](https://code.visualstudio.com/insiders) yet. Will try it out and add comments some time later.
