### ISSUE TITLE
Button - disabled button appears as enabled when focused

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#156443]
I have noticed that a disabled button widget appears as enabled when it receives focus. Is that expected?

Disabled button:

<img width="324" alt="image" src="https://user-images.githubusercontent.com/3372902/181277936-823b08d7-bcb4-4f76-8a4b-060b0c3537e5.png">

Disabled button with focus:

<img width="333" alt="image" src="https://user-images.githubusercontent.com/3372902/181278023-6076e14c-511f-4cb8-b1ca-43d6cbe4b995.png">

I have tracked this down to [this style](https://vscode.dev/github/microsoft/vscode/blob/079c49ed1277fc42d8a49823dc6fbab473223503/src/vs/workbench/browser/media/style.css#L188-L189). I think that the disabled button should display the outline but do not change the opacity.

**Comment by misolori** [comment]
I don't think disabled buttons should get focus because that indicates that you can perform an action, similar to why we don't show the pointer on hover for disabled items. One way to get around this issue is to add a `:not(.disabled)` rule to ignore disabled buttons.

**Comment by bpasero** [comment]
Looks like Isi changed widgets to not remove `tabIndex` when disabled in https://github.com/microsoft/vscode/commit/3479bb35904eb046c0974090794cac9c76173796#diff-66a07df088d0eb0a5f86befb962cf52e893a8cc3ae2fc716968effb45c485185, so I refer to him why that is so.

**Comment by isidorn** [comment]
Yeah, I am the culprit :)
I changed it because the accessibility guidance says that even disabled buttons should be focusable, so users can discover them. Example toolbar that demonstrates this https://www.w3.org/WAI/ARIA/apg/example-index/toolbar/toolbar.html

However I am not 100% convinced this is the right way. And we can change this.
Let me know what you think. Thanks

**Comment by daviddossett** [comment]
![CleanShot 2022-07-28 at 09 17 17](https://user-images.githubusercontent.com/25163139/181587746-1f9aaabe-663a-4c53-bec1-5498053a46b0.gif)

Feels strange to have background colors changing despite allowing disabled elements to have focus. Can we just use the focus border without changing the backgroud for our case(s)?

**Comment by lszomoru** [comment]
I think that it does make sense for the button to be focusable and have an outline even when disabled. But the disabled button should "look" disabled in all states (normal, hover, focused).

**Comment by lszomoru** [comment]
Not sure who owns the widget to make this change, though.
I am happy to make the change in about two weeks after I am back from vacation.

**Comment by isidorn** [comment]
I think the button widget has no direct owner. Since this is not urgent, let's assign to you based on your kind offer :)
