### ISSUE TITLE
Add a "Beginner" or "Newbie" label to issues

### ISSUE THREAD

**Issue by arimourao** [Microsoft/vscode#15645]
In an effort to attract many unexperienced programmers into open source projects, many have been adopting the approach of labeling the issues as "Beginner Friendly" or "Newbie" when appropriated so newcomers can jump into open source dev without much hassle. 

More on this:
http://contributor-covenant.org/
https://opensource.com/life/16/1/6-beginner-open-source

**Comment by ramya-rao-a** [comment]
@arimourao We have the labels `help-wanted` and `effort easy` which serve the similar purpose.

@Microsoft/vscode Thoughts on including labels for `beginner` ? Something that is `easy effort` need not necessarily be the right fit for beginners.

**Comment by Tyriar** [comment]
I think we should just rename `effort easy` to something clearer like beginner or newbie. Thoughts @waderyan?

**Comment by octref** [comment]
For beginner, I'd say it's better to start by writing extensions instead of trying to contribute to the editor.

**Comment by Tyriar** [comment]
@octref the label would mean beginner in the context of vscode contributions. It's hard to know which issues labeled `help wanted` are good issues for your first PR without something like this.

**Comment by waderyan** [comment]
I'm in favor. When this was initially brought up I liked `good first bug` from React the best. There was some push back and then we landed on `effort easy`.

**Comment by arimourao** [comment]
@waderyan `good first bug` indeed seems great. Something that is quite simple, maybe just a refactor and them people that feels intimidated by the size and complexity of vscode can successfully make a PR and slowly dwelve into deeper problems.

**Comment by joaomoreno** [comment]
👍  On just renaming `effort easy` to `beginner`, like [electron](https://github.com/electron/electron/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner).

**Comment by Tyriar** [comment]
Lots of :+1:s so I renamed it to beginner which is also my favorite. https://github.com/Microsoft/vscode/labels/beginner
