### ISSUE TITLE
Open folder requires 2enters to open

### ISSUE THREAD

**Issue by mrx23dot** [microsoft/vscode#156414]
Issue Type: <b>Bug</b>

- Go to File->Open Folder
- Ctrl+V folder name
- press enter
- sometimes it requires a **2nd enter,** which is odd on Windows.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.16.1
linter|fna|0.0.11
copilot|Git|1.35.6319
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.6.30
cpptools|ms-|1.11.4
code-spell-checker|str|2.3.2
vscodeintellicode-completions|Vis|1.0.15
vscodeintellicode-insiders|Vis|1.1.10

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by lramos15** [comment]
Please add `"files.simpleDialog.enable": true` to your settings to accomplish what you wish.
