### ISSUE TITLE
Renaming files before saving deletes contents

### ISSUE THREAD

**Issue by steveareeno** [Microsoft/vscode#15646]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|typescript-react-snippets|abotteram|0.1.9|
|Theme-azure|gerane|0.0.2|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.2|
|Material-theme|zhuangtongfa|1.0.3|

---
Although this may be by design, it is different behavior compared to Visual Studio and other editors I have used. I typed a lot of code into a js file and when I renamed it prior to saving it, it wiped out all my code. It happened to me a couple times and now that I understand what is happening I'll be more careful in the future, but it would be nice if behavior didn't occur.

Steps to Reproduce:

1. Create a js file and type code in it
2. Before saving, rename the file
3. Acknowledge the prompt

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11997
