### ISSUE TITLE
v.1.69.2 appearance problem

### ISSUE THREAD

**Issue by ahmadSbaih** [microsoft/vscode#156405]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version:  macOS Monterey V12.5

I update my VS code on my MAC to v.1.69.2 when I open it I can't see the icons on the activity bar the icons are still hidden then when mouse over I can see also when I select my file code I can't see without putting the mouse over it
any advice to return back my IDE work correctly

![OS X Mavericks - VMware Workstation 07_27_2022 8_36_46 AM](https://user-images.githubusercontent.com/15274660/181170578-18aaf64c-bd2b-4c1a-9821-e3195eda9beb.png)

**Comment by deepak1556** [comment]
Can you try disabling hardware acceleration and check if it resolves the issue,

* Open command palette and search for "Configure Runtime Arguments"
* Set `"disable-hardware-acceleration": true`
* Restart

**Comment by ahmadSbaih** [comment]
> Can you try disabling hardware acceleration and check if it resolves the issue,
> 
> * Open command palette and search for "Configure Runtime Arguments"
> * Set `"disable-hardware-acceleration": true`
> * Restart

Thank you sir that solve my problem :)

**Comment by phatpaul** [comment]
I am also experiencing this problem.  Mine is macOS 11.1 within VMware (linux host).
I can't even get the command palette to show up.
How can I set that option before launching the app?

**Comment by ahmadSbaih** [comment]
> I am also experiencing this problem. Mine is macOS 11.1 within VMware (linux host). I can't even get the command palette to show up. How can I set that option before launching the app?
> 
> EDIT: nm, found it here: #152816

Hi Phatpul,
you can follow this link https://stackoverflow.com/a/73132799/8902756
