### ISSUE TITLE
Find widget for trees - down arrow key focuses entire File Explorer or open file 

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#156474]
Testing #156100

1.  If you have an open file, after searching, if you have a highlighted file in the file explorer, the down arrow will select that first before finding the first instance of what was searched.
![Recording 2022-07-27 at 09 58 25](https://user-images.githubusercontent.com/54879025/181305958-009dfeb7-9c5e-4d5e-9c15-bd78fecf7198.gif)

3. Similarly, if you have no file selected (and focus is changed), after searching, the down arrow will select the entire file explorer before finding the first instance of what was searched.

![Recording 2022-07-27 at 10 02 04](https://user-images.githubusercontent.com/54879025/181306594-8016a79f-c551-41e3-91b4-92a761608bfc.gif)

![Recording 2022-07-27 at 10 01 06](https://user-images.githubusercontent.com/54879025/181306619-5903eaaa-8369-400c-8c40-b294665b469a.gif)

**Comment by joaomoreno** [comment]
I can't repro these any more.
