### ISSUE TITLE
Sticky scroll reveal and jump feel a bit off

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#156586]
![Recording 2022-07-28 at 11 07 08](https://user-images.githubusercontent.com/4544166/181572660-cc7c375a-87ed-4920-838f-94004ea023eb.gif)

I really like sticky scroll but I found a few things confusing when using it especially because the lines share the same background as the editor they feel like just another section of editor text. I've included a gif to hopefully also depict the issues I've listed below.
1. You cannot hover text in the sticky scroll.
2. The sticky scroll lines can be present even when that line is already in my viewport causing a doubling sort of effect where the line in the editor is more feature rich (such as supports hover) than the line in the sticky scroll
3. It seems hit or miss whether or not clicking the sticky scroll would reveal the line. My expectation is it would jump to that line and then remove it from the sticky scroll so I would be able to edit it for example.

**Comment by aiday-mar** [comment]
Hi, thank you for your feedback. 

1. It's an interesting idea to be able to hover over text in sticky scroll. Perhaps I will make this into a feature request. 
2. This should be fixed after the build with commit : https://github.com/microsoft/vscode/commit/0397ca4a4843cca225a88810c95bc60da537ca45
3. This should be fixed after the build with PR : https://github.com/microsoft/vscode/pull/156578

**Comment by lramos15** [comment]
#1 has further implications too. Like hover is just one thing (probably not even the most important one). You also cannot use the editor context menu. I definitely think the background colorization makes it the most difficult to me for it to not feel like the editor and that everything should work the same way as the editor does.

**Comment by jrieken** [comment]
Closing as work is done or shelled out to other issues
