### ISSUE TITLE
Garbage and weird behavior in VSCode terminal on macOS High Sierra

### ISSUE THREAD

**Issue by Onwrikbaar** [microsoft/vscode#156548]
Issue Type: <b>Bug</b>

Since update to VSCode 1.69.2, typing in a VSCode terminal window makes the window contents appear and disappear and inserts block characters seemingly random. This makes the VSCode terminal effectively unusable.
The macOS native Terminal program works fine.

To reproduce:
1. Open some project
2. Open a terminal window and give it focus
3. Start typing a command, like "ls -l" (see attachment)

Thank you,
Mark

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 17.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|4.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 32a5f5d1-bec9-421d-8026-122dac4015ca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
githistory|don|0.6.19
gitlens|eam|12.1.2
go|gol|0.35.1
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```
![Screen Shot 2022-07-28 at 10 27 56](https://user-images.githubusercontent.com/26547598/181459348-559d67b6-6d06-49db-b78e-3d51920c84ca.png)

</details>

**Comment by coherent17** [comment]
Same as me I got a garbage file named 2 and there is some trash in side the file

**Comment by gjsjohnmurray** [comment]
No attachment. Please attach or paste.

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by Onwrikbaar** [comment]
Yes, changing it from `auto` to `off` fixes the problem.

Thank you for your swift response and solution!
