### ISSUE TITLE
VSCode inline diff peek view doesn't show whitespace difference

### ISSUE THREAD

**Issue by abgnwl** [microsoft/vscode#156523]
Issue Type: <b>Bug</b>

When I change the indentation, Diff Decorations Gutter shows that this line is modified, and "open changes" shows the whitespace difference.

However, when I click the decoration gutter, there is no diff in peek view. 

My settings:
SCM: Diff Decorations Ignore Trim Whitespace - false
Diff Editor: Ignore Trim Whitespace - false

Diff Decorations Gutter  & peek view:
![image](https://user-images.githubusercontent.com/9429734/181416784-5cffdb58-e0b7-4024-854c-a0b36cc3c35e.png)

open changes:
![image](https://user-images.githubusercontent.com/9429734/181416814-22cf463f-afbb-4fe9-99c9-0e16afbc6108.png)

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.18GB free)|
|Process Argv|C:\\Users\\zijueli\\Desktop\\test\\1.cpp --crash-reporter-id 887f76a1-42a5-4491-a127-ae98a413d02b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.8
better-cpp-syntax|jef|1.15.19
vscode-leetcode|Lee|0.18.1
sftp|lix|1.12.10
vscode-language-pack-zh-hans|MS-|1.69.7130921
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.11.4
markdown-preview-enhanced|shd|0.6.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728

```

</details>

**Comment by joaomoreno** [comment]
There's a setting to control this: `scm.diffDecorationsIgnoreTrimWhitespace`

**Comment by abgnwl** [comment]
> There's a setting to control this: `scm.diffDecorationsIgnoreTrimWhitespace`

No. This setting affects whether to display the gutter, not the difference in peek view window.

SCM: Diff Decorations Ignore Trim Whitespace - false:
![image](https://user-images.githubusercontent.com/9429734/186893246-9685a119-460b-48eb-ae09-293f60334f77.png)

SCM: Diff Decorations Ignore Trim Whitespace - true:
![image](https://user-images.githubusercontent.com/9429734/186893294-5fbac9de-6e42-41bf-9af6-468fcf43603d.png)

**Comment by joaomoreno** [comment]
You're right! Thanks for the ping!

**Comment by abgnwl** [comment]
this issue still exists after updating to 1.81.1

**Comment by lszomoru** [comment]
@abgnwl, apologies for not getting back to you on this until now. I just tried to reproduce this with the latest VS Code Insiders release without any luck. The whitespace differences are being shown correctly both in the in-line diff editor as well as in the side-by-side diff editor. Could you please give it a try and reopen the issue in case you are still able to reproduce? Thanks!

**Comment by abgnwl** [comment]
This issue no longer exists after upgrading from 1.81.1 to 1.96.2. Thanks!
