### ISSUE TITLE
"Reveal in Explorer View" fails for nested files

### ISSUE THREAD

**Issue by OldStarchy** [microsoft/vscode#156531]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0-insider (user setup)
- Commit: 9cf2fabdd600c7d8e3230803acb246405321e8dd
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Enable file nesting `"explorer.fileNesting.enabled": true`
2. Create two files, `foo.js` and `foo.min.js`
3. With the `foo.min.js` editor tab open the "Reveal in Explorer View" command
4. The `foo.min.js` file is not revealed in the explorer view

Once you manually expand the `foo.js` nesting to reveal `foo.min.js` the command will start working, even if you collapse the tree under `foo.js` again.

It will stop working again if any change to the tree view is made (creating, deleting, or renaming a file) while the nested tree is collapsed.

Maybe related: #155766

**Comment by lramos15** [comment]
This is most likely caused by the tree being async. It does not know that node exists because it has not been resolved yet. You having the file open is not a guarantee that the file is in the explorer (think outside files).
