### ISSUE TITLE
ES 6 highlighting break after "_"

### ISSUE THREAD

**Issue by ElfenLiedGH** [Microsoft/vscode#1565]
![1](https://cloud.githubusercontent.com/assets/9973357/11949847/6a869096-a894-11e5-911e-86b842acc8eb.png)
![2](https://cloud.githubusercontent.com/assets/9973357/11949850/6d07103e-a894-11e5-9d54-02ef38000d10.png)
![3](https://cloud.githubusercontent.com/assets/9973357/11949851/6ecff3e0-a894-11e5-99f6-6423dccd0694.png)
1.Связные_серверы - don't work break "extends"
2.Связныесерверы - ok
3.Базовая_выборка break this. super... to the second ""

**Comment by aeschli** [comment]
I can't exactly reproduce the shown example, but I see other issues with Cyrillic characters in the identifier.

![image](https://cloud.githubusercontent.com/assets/6461412/12238144/d1f06bc8-b882-11e5-9a2e-e5b7ac62105f.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#45
