### ISSUE TITLE
Keystrokes delayed when using git bash as terminal

### ISSUE THREAD

**Issue by wadewalker25** [Microsoft/vscode#15655]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|MochaSnippets|Alan|0.0.1|
|vscode-angular2-files|alexiv|1.3.2|
|typings-installer|benjaminromano|0.2.0|
|npm-intellisense|christian-kohler|0.1.4|
|path-intellisense|christian-kohler|1.1.0|
|vscode-mocha|Compulim|0.1.1|
|angular2-snippets|danwahlin|1.0.5|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-protractor-snippets|deerawan|1.0.5|
|bower|donjayamanne|0.0.3|
|githistory|donjayamanne|0.1.0|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.5.40|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.3.5|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-Monokai|gerane|0.0.2|
|Angular2|johnpapa|1.0.2|
|vscode-simple-icons|LaurentTreguier|0.7.0|
|chai-snippets|nwhatt|0.1.0|
|view-in-browser|qinjia|0.0.3|
|vscode-icons|robertohuertasm|4.0.1|
|annotator|ryu1kn|0.10.1|
|yo|samverschueren|0.9.1|
|html5-boilerplate|sidthesloth|1.0.1|
|autoimport|steoates|1.2.2|
|vscode-gulp|tanato|0.0.4|
|create-jsconfig|TomiTurtiainen|0.2.0|
|sort-lines|Tyriar|1.1.0|
|ng2-dg|web-dave|0.1.7|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Use git bash as terminal: 
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "terminal.integrated.shellArgs.windows": [
        "-l"
    ],
2. See that when you enter commands quickly as well as backspacing causes rendering to not match keystrokes entered such that what you see on the screen will not actually be sent through the bash terminal.

**Comment by kidlj** [comment]
The same.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14613
