### ISSUE TITLE
Bracket completions doesn't work when Intellisense menu is open 

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#156597]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.70.0-insider (user setup)
Commit: b4d5b4ed69af953901051b1f049851b9dca3563e
Date: 2022-07-28T05:16:28.624Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

When Intellisense menu and a grey text prediction are shown at the same, bracket completion doesn't work. 

Example 1: 
![intellisense-bc-bug1](https://user-images.githubusercontent.com/86270736/181594676-458fc943-0b40-4652-856d-b5c2a5e2c6c2.gif)

Code in file 
from tkinter import font
import turtle
import random
import time

screen = turtle.Screen()
screen.title("DATA")
screen.setup(width = 700, height = 700)

Example 2
![intellisense-bc-bug2](https://user-images.githubusercontent.com/86270736/181595395-00b5dbbf-d9e4-4d84-8d14-737a0eda57c3.gif)

Example 3
![intellisense-bc-bug3](https://user-images.githubusercontent.com/86270736/181596400-13982088-a90f-4681-90ee-9ce3fc446d62.gif)

cc @hediet

**Comment by hediet** [comment]
![chrome_QLlHBW4hxA](https://user-images.githubusercontent.com/2931520/233649252-89758990-c43b-4991-af00-a15a4065f101.png)

[This works now](https://microsoft.github.io/monaco-editor/playground.html?source=http%3A%2F%2Flocalhost%3A5001%2Fout%2Fvs#XQAAAAIqHAAAAAAAAABBqQkHQ5NjdMjwa-jY7SIQ9S7DNlzs5W-mwj0fe1ZCDRFc9ws9XQE0SJE1jc2VKxhaLFIw9vEWSxW3yscxyx-6HVciAKctgAboa7AaZZDHLgrLqPRv_fRv2RyIokydlTdTYccsu6v6jDrc8jQ8utukPwKUQ2RhhDEWkiejwvhCv6mI9f-mMWJ901Y9mnfbO1g9WbURsQKLj7If1bEqyfxshEfYmMsEBsZWDcvtviGwczYH-bGaY1q1RTksWprUaeb-7D9qk8sSZzNt4rv4OI9tPsXri4WDjMgCqcbDuFokXJzKy2gqmGmSPqpHgQIM0u8P3kyl2iDyOLRX7pffC0wtHHJbtk5Wp_jyMrpJQhlh4zrZoEKisNLyVy6r7velG7BULVOfeVyuQwec9LaEKXOW7WsrPRvPUXd6Mc-6NCjumphLE7e7qlpuD4U8a3tyNqUafePM05t3TUd5jHLGWAyJNlKsFrchjXEoUumGQ_461dRDaztbiGlpCzR3VJTXFCmH8oScjafsl5jj5eIzfi2-915tKakSFDv27UiLkjCItKT-Behj3gK9SSTNPzqj3unV95iGA4PZXZOJNQGsRDRZ1b5Nln9zL4YZ6TUSLpBxoj-eFljivVriY81Vm9c9VCNrpzx0_t9np7-g4X1rdNmxxz3sEGZhRg6DE31OlRMuU4nNu-arXPjKs0K56snZteJ29YKdWq3FI3ETCVzZ_TwZoTOhOEhkr7mI1LNtezFmBIDTjgucW_w_uPk3czeE-k65Ul-k-3GcSMG9Y03EPMKdoaPPAet1ikRlMobg0nPnFn5XqlzZcnKiqimCQs86lrbOOeQNMBnfVD41RVH6p_mZs-8THqT7j6gPzIfTAJ7jZ3SC7bTRxBAuHNkXJK6lb8AO0gcJcjyilwM7_tYTWwVg-D0YbPG4HvzaC9-egJJ3CbHm50VUKSTJCoQptXhBbrnVEa6Q7F8MOnVrWyKusAP-eX8NNss24XQQhdz2GB5j6ELJ66eekSIHt7cCN2-FUEmx1tf-VR8t3cmW5FgBznDeQAAojFzZ4jgSPW_bvVwIbg0Mk1SyEh7MEeOuegjfBj6FEUI9yKfuNMR7jF5PA87fx7-xB6ydHB-OWm14uH_9sXFn6P0n5dGDZEVoGBMZWb-sF9Jn9hdhrASGcmTcHSz9fzv9vgAaAF9u5Ubn4XJSp_bgfDGUTOSATxIDgRj9DHkvF8tIRugFPJPGxhd7vZj0lcm0ZemuP751sgqmj8FLicEcFHn43q-MMFP1urjATCDS_VMwLR_L4YvAx-GEVWxLqxRmb6bR00fdVr9D88t0Xb20bejJe7SBvM_vMEzqqInPlIC5JWJshR3OtmnNrE9boka4xJpnUy0YyD1yEi63j1TeYzSjL2WInktcJj7_M5L6jCyYg0fIH6_hmVZRaPH9PkMowCOEoFW-ftqpMXNpW7MFVRiZ4PLXAEDAFvgSfpJKu16sO-p2iVaDPCHM5R3Sq-Lu_kdXooT8qcAagpMyNL5ZdLF-q-8fRgWadzoklGONplwoU3J0ngeG5JQNTX3G4IWblQHnR3xAmw_ZZp9qg640zarmwbdbBfP9erXzv31t3Mo6TS6CpjCC2NNGpBEoYYuU-SXPPrpoaQ27etcZOl4lONdpp8y2j7OXF24RCjsk8B5LRjERL2t4dZ5wK0RDZvuTG9FL4G6loWAXX6yc3bCUaMYnh-Kb6DMKFgbOwo52NWadVksCNtG4pjIZBEBIhU41JPXcwf9Z55FdT6IUOgcUK_K1EXEzDKL5Zn9hu_lOeE7HtD5geYKcYn3e0eNZMC6r0bwHsP4T57DruS0kwbr2jy2EqVsg_GGfB1AHmIdrsSFTJz4wanEynUBmaVD4U4pihuQfvVpfCMkT2OKlH41ejHCzPyItLZGoYBVOA2pYBfUjdDd2bTbhGsJmYvCw8M4OPJ60ifu3emYNWQZTlDcEUTXB2q-1_kD86m-424P77lzmtdswcorbKu4SEKaunXRXdwSXieCiguZTacHbgZ8CqeWRI9b0vJYx9CQX7Al8lXAoLd3Hwr_2kb2HHIRW6qFDHnyGnX7CojYBtnQRM1-pxMz5vzPlz96AQcxdFS_2FKIVfzftLjmR3eraFQQtynlWFhgOEyL7mc-ptHvBLe748Rw__zX1Ca3Po5o2kYUli-dwpZBRocw-It0hp-joU62EKgQri1Q6ZyL5E_NHDuanyhr-_hZNB4XlLHRZdegtyFWwmcmBgbgh1kL5ZPx9IleapAVnE0fIMoaK2thH7mz51VcsSKbvmVbMu9QBcWDkbfGmWeAB_dqqC02YJLzzBCmTxcSu4T9MH7qlwsYKhumektALWnlInzMc_R427vBnYSvXhBpX0w2KkdzqCdAc7-WvOkQ2Ci8V1eEPkgdLnvci0qGqxE6dXJ1N-zuq5FlBmQTjpdy0nVKDkE1141me54IRy-t1_I4KR7rW1AUStUKvnIzKwWJ1wMppJ3lqh_vjwvVN5Fhsb3WHLRHhvLSafTLkgwpW2DQH_XSu2nBKkvHREbiyKiJAaeG86XPZMn-ek1k3MPsuaJkdYimQcctD6kRaPI6LBKkxK_4bHpU4mzPvXfva8rntn_MEhOheUi4WgtA8Db_QZAagvWozQIpJ9Y8NBlGPWJjFeEdJlBsvTu-_Thek_oXprxFSFP1Z6XYJcdPR1W90Fm-GKT2zDANNRGVRMMDJGwaXQg-GWuDuxdBzFbEXBHokVC_JUvYwSmEDLB7mSjFSJIvATVgZAwuWCY0LjPtqh3tqXqBKFEfQNzqfhf0fUrlOVdC1O8xqVAB-w_J_7LGwQGKWt2wFMvVtCbi0_3iphAA).
