### ISSUE TITLE
TS server dies

### ISSUE THREAD

**Issue by dan-iliescu** [microsoft/vscode#156593]
Issue Type: <b>Bug</b>

I have a project with multiple file types. Its a node backend with typescript but if I open up a js file or another extension the ts server dies and my pc fan just goes crazy unless I restart vscode.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (2.25GB free)|
|Process Argv|--crash-reporter-id 93bb1f02-61ec-40f0-aa26-9ae2da8d95ac|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
htmltagwrap|bra|0.0.7
prettier-vscode|esb|9.5.0
vscode-styled-components|jpo|1.7.0
vsliveshare|ms-|1.0.5667
material-icon-theme|PKi|4.19.0
nbsp-vscode|pos|0.0.1
LiveServer|rit|5.7.5
material-theme|zhu|3.15.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
