### ISSUE TITLE
Merge IBackupService and IBackupModelService

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15650]
I am not sure why IBackupModelService exists, it does not have any methods. Imho we should not add services that do not provide any functionality. If you need something to start listening and do work, just use a workbench contribution instead.

**Comment by Tyriar** [comment]
It exists because `BackupModelService` depends on `TextFileService` (listening to models) and `TextFileService` depends on `BackupService` (shutdown stuff). Can we get around this with a contribution?

**Comment by bpasero** [comment]
@Tyriar well yeah, a workbench contribution is a piece of code that gets instantiated after all services are there. A good example is my https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/electron-browser/dirtyFilesTracker.ts#L26 which looks very similar to yours.
