### ISSUE TITLE
Terminal colors are muted with gpuAcceleration on

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#156507]
I noticed terminal colors were off the other day; I thought it was the new ultrawide monitors we got in the office, but it's not. Top is with 

**"terminal.integrated.gpuAcceleration": "off",**

<img width="270" alt="image" src="https://user-images.githubusercontent.com/2230985/181380197-d3b0dcea-3baf-47a5-9f30-b24c5a74ce54.png">

**"terminal.integrated.gpuAcceleration": "auto",**

<img width="250" alt="image" src="https://user-images.githubusercontent.com/2230985/181380239-d1f7dcda-b9fb-48bb-b49b-68f13b7e15d2.png">

Notice the red is much less vibrant. It appears to go away if I set `terminal.integrated.minimumContrastRatio: 0`, but I had thought that was supposed to be the same for all rendering modes.

**Comment by meganrogge** [comment]
what happens if you set it to `on`?

**Comment by meganrogge** [comment]
changing that setting doesn't change the color for me 🤔

**Comment by meganrogge** [comment]
my min contrast ratio is the default - 4.5

**Comment by meganrogge** [comment]
contrast gets worse when I change contrast ratio from 0 to 4.5 🤔 .... that seems wrong

**Comment by Tyriar** [comment]
Previous reports like this have had the canvas colors correct to the theme and the dom not due to electron bugs. Could be it?

**Comment by meganrogge** [comment]
@deepak1556 have you seen reports like this?

**Comment by Tyriar** [comment]
Upstream

**Comment by Tyriar** [comment]
Cannot reproduce
