### ISSUE TITLE
The identifier 'constructor', when used as a shorthand property name in an object initializer, is highlighted

### ISSUE THREAD

**Issue by tuespetre** [Microsoft/vscode#15652]
- VSCode Version: Code 1.7.0 (9e7d70052908b633e0d4f71e70b26714bd1d2f10, 2016-11-02T14:34:01.691Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|cpptools|ms-vscode|0.9.1|
|csharp|ms-vscode|1.0.3-rc2|

---

Steps to Reproduce:

1. Type this in the editor:
   ```
    const constructor = someObject.prototype.constructor;
    const objectLiteral = { constructor };
    ```

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#361

**Comment by ramya-rao-a** [comment]
@aeschli FYI, Moving this to Typescript-TmLanguage repo based on other similar coloring issues that were moved
