### ISSUE TITLE
Open files in respective windows that have parent folder open

### ISSUE THREAD

**Issue by laggingreflex** [Microsoft/vscode#15654]
- VSCode Version: 1.7.1
- OS Version: 10

If you have two folders open in Code, say

    C:\project1
    C:\project2

And you opened a file from Windows File Explorer (either though context menu, or default associated application)

    C:\project2\some-file.js

It opens in the last Code window that was active. If it was the `C:\project1` Code windows, it opens in that. 

Expected behavior:

For the files being opened, Code should check to see if there's a project window open corresponding to the file's parent folder (walking up the parents as needed), and if it find such a Code window already opened it should open that file in that window.

In this case the `C:\project2\some-file.js` should open in `C:\project2` Code window, regardless of whether it was the `C:\project1` that was last active.

**Comment by Tyriar** [comment]
This should have some clearly defined behavior around what happens when windows exist and when not. Is the latest window always reused or does the folder always open?

**Comment by chrmarti** [comment]
No new folders will be opened. The current behavior will be changed to reuse an existing window that is open on a folder containing the file to open if there is such a window (and "window.openFilesInNewWindow" is not "on").

**Comment by jrieken** [comment]
Maybe I misunderstood how this is supposed to work but I have opened a folder (`ConsoleAppDnx`) and when I tell Finder to open a file from within there is opens in a new window:

![feb-23-2017 16-11-51](https://cloud.githubusercontent.com/assets/1794099/23264796/edd58e98-f9e2-11e6-954c-d7a1033ecbc0.gif)

**Comment by chrmarti** [comment]
@jrieken On Mac you need to set `"window.openFilesInNewWindow"` to `"off"` to enable this from Finder. This is due to the Mac having a more document oriented default.

**Comment by jrieken** [comment]
That did it. Thanks
