### ISSUE TITLE
Avoid checking for backups on each resolve() of file/untitled

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15653]
I see we only use it to find out if we should load a backup from disk when opening a file. Can we not just always try to load the backup and handle the error case? That should save us 1 IO operation.

**Comment by Tyriar** [comment]
It changes in one of my open PRs to `hasBackup` as it's used for untitled files. Wouldn't that throw a lot of exceptions which are expensive as it's triggered whenever files are opened?

**Comment by bpasero** [comment]
@Tyriar I would bet that any exception is less expensive than talking to a disk. And it will only be one error that will be thrown from here I think: https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/stream.ts#L50

Because the very first call of `resolveContent` is `mime.detectMimesFromFile` in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/node/fileService.ts#L164

**Comment by Tyriar** [comment]
If that's the preferred way when the typical case is it failing  :+1:

**Comment by Tyriar** [comment]
Let's not move on this until https://github.com/Microsoft/vscode/issues/14186 is done

**Comment by bpasero** [comment]
@Tyriar actually maybe there is a better solution that could prevent us from always checking for a backup. What I am mainly interested in is to not having to ALWAYS check for backups each time you open a file. Because there is really only 1 time when a backup can be present: That is the very FIRST time you open a file (or am I wrong?). 

It seems odd to check for backups all the time when we know it can only be after initial startup. I know for this particular reason you added the `restoreResource` and I did not like it. But the concept was good, I think it can be achieved without the need for `restoreResource`.

**Comment by Tyriar** [comment]
The original intent was to only ever check for backups on launch as you say using `restoreResource`, and yes on launch is the only case we care about. So currently backups could theoretically restore in the middle of a session if a backup file doesn't get cleaned up somehow from a previous session (bug) or if it does not get persisted to the workspace state in local storage (crash).
