### ISSUE TITLE
Group Policy to deactivate extentions?

### ISSUE THREAD

**Issue by caBattista** [microsoft/vscode#156568]
Hello VS Code Team, 

we are using VS Code in our company. Unfortunately we have serious security concerns regarding the VS Code extensions. As mentioned here https://snyk.io/blog/visual-studio-code-extension-security-vulnerabilities-deep-dive/.

Is there a group policy to disable the ability to install these extensions or only allow certain ones?
We could only find a policy regarding the updating behavior in the .admx file included with the installation.

Otherwise we might have to abandon VS Code altogether.

**Comment by isidorn** [comment]
Currently there is no policy to control which extensions can be installed.
We might introduce this in the future, thus for marking this as a feature request and assigning to backlog.

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/84756
