### ISSUE TITLE
Support to call debug adapter API from extension

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#15656]

**Comment by isidorn** [comment]
Assigning to november to investigate

**Comment by roblourens** [comment]
Whats the current thinking about the extension/debug adapter communication for skipFiles?

**Comment by weinand** [comment]
@roblourens since the skip-files-ui-feature is a one-off private feature, you are free to introduce whatever protocol you need. Only your debug adapter will use it.

**Comment by isidorn** [comment]
We have added a first version for this. After discussing with @weinand we have decided that the first step for allowing this is for the extension to simply pass the request to vscode which would forward it to the debug adapter.
In the future we should consider making this official API in vscode.d.ts, currently it is simply a workbench command.

 Each extension can exectue the command `"workbench.customDebugRequest"` and pass the request and arguments. Here's an example:
```javascript
vscode.commands.executeCommand('workbench.action.customDebugRequest', 'myRequest', { test: 5 });
```

Closing this issue as there is a seperate issue #14728 for tracking the implementation in skip files.
@roblourens let me know if you need anything else on the vscode side or ping if you have any feedback on how we exposed this

**Comment by roblourens** [comment]
Looks like exactly what I need, I'll try it out.

**Comment by weinand** [comment]
@DanTup please see https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/extension.ts#L42 for sending a request from the extension to the DA, and  https://github.com/Microsoft/vscode-node-debug/blob/master/src/node/nodeDebug.ts#L3716 fro how to handle the request in the DA.

**Comment by DanTup** [comment]
@weinand Thanks! I managed to find that (and this issue) after commenting last night; looks like it should do exactly what I need, thanks!
