### ISSUE TITLE
Debug console: Accepting a suggestion with Enter submits the entire input

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#156565]
1. Start debugging
2. Break somewhere
3. Type something like `console.`, this should open the suggest widget
4. Use <kbd>Up/Down</kbd> to pick something from the widget, press <kbd>Enter</kbd> to accept it

🐛 The input gets submitted for evaluation, as opposed to having the suggestion be accepted

<img width="500" alt="image" src="https://user-images.githubusercontent.com/22350/181505312-2215a1ce-7c59-4e5c-9841-aa21601725e5.png">

**Comment by connor4312** [comment]
duplicates https://github.com/microsoft/vscode/issues/145955, there's a setting to configure tab/enter behavior
