### ISSUE TITLE
Unable to share vscode.dev from the web

### ISSUE THREAD

**Issue by miguelsolorio** [microsoft/vscode#156628]
Testing #156153

## Desktop
<img width="530" alt="CleanShot 2022-07-28 at 13 13 23@2x" src="https://user-images.githubusercontent.com/35271042/181628715-605d4709-f6e2-4f69-8379-d28000b9f18d.png">

## Web
<img width="355" alt="CleanShot 2022-07-28 at 13 12 33@2x" src="https://user-images.githubusercontent.com/35271042/181628628-d243a635-ab8c-4a7c-b94d-a920bc77d79b.png">

I kept expecting to be able to share a vscode.dev URL from either the web or desktop and don't see an option on the web. While I can easily cop the URL, having a direct link to the notebook cell is far more valuable.

**Comment by alexr00** [comment]
The share currently depends on the built in git extension, which we don't have in the web.
