### ISSUE TITLE
enable terminal.integrated.enableFileLinks only in local terminals/drives

### ISSUE THREAD

**Issue by laralove143** [microsoft/vscode#156679]
the setting description itself says

> Links can be slow when working on a network drive in particular because each file link is verified against the file system.

so wouldn't it make more sense to be able to disable this for negatively affected terminals (remote terminals/network drives)?

**Comment by Tyriar** [comment]
To verify:

1. Set log level to debug
2. Open a local folder
3. Write a link in the form `./file` that exists
4. Click the link
5. Check the devtools console and ensure the link type logged is LocalFile
6. Open a remote folder
7. Repeat 3-5 but ensure the link type of Search
  ![image](https://user-images.githubusercontent.com/2193314/206735012-43cfa7b9-95c0-4283-b117-cc506864adb1.png)
