### ISSUE TITLE
Message (loading...) didn't get externalized correctly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#156684]
1. Open devtools.
2. Open the vscode repo and open a TS file.
3. Restart.
4. Hover over an expression while the TS extension loads.
5. The `(loading...)` hover appears.
6. :bug: In the devtools console, the "didn't get externalized correctly" warning shows up.

**Comment by mjbvz** [comment]
@TylerLeonhardt Any ideas what would cause this?

**Comment by TylerLeonhardt** [comment]
This would happen if the `localize(...)` call wasn't rewritten by the webpack loader defined here:
https://github.com/microsoft/vscode/blob/9274dff58bb4e5f6aa38187cf42e4811bd9dc7f4/extensions/shared.webpack.config.js#L35-L40

can you look at the built version of typescript-language-features and tell me what the `localize` call looks like?

**Comment by mjbvz** [comment]
Ah looks like we're incorrectly importing `localize` from another file. Here's the compiled call (which doesn't appear to be rewritten):

```
a.push((0,i.localize)({key:"loadingPrefix",comment:["Prefix displayed for hover entries while the server is still loading"]},"(loading...)"))
```

Will push a PR with a fix

**Comment by TylerLeonhardt** [comment]
That'll do it. loadMessageBundle is actually responsible for giving you your strings for that specific file so you need to have one of those everywhere you have a localize call
