### ISSUE TITLE
Request to https://api.nuget.org/v3/index.json failed: Not Found. The requested location could not be found.

### ISSUE THREAD

**Issue by garoyeri** [Microsoft/vscode#15669]
- VSCode Version: 1.7.1
- OS Version: Windows 7 SP1
- OmniSharp 1.5.2

Steps to Reproduce:

1. Behind a corporate SSL proxy.
2. Set http.proxyStrictSSL = false, no proxy URL Set
3. Using .net core, do: dotnet new -t web
4. Open project.json, navigate to version number of a package, hit CTRL+space to try and get completion options.
5. Observe that output pane shows these error messages, drop down list says "JSON Language Server"

**Comment by joaomoreno** [comment]
Have you tried setting the proxy URL?

**Comment by garoyeri** [comment]
No, it's not that kind of proxy I think. All traffic is already routed through it and it'll intercept SSL as well. The fix may be similar to related issues in cpptools and omnisharp plugins for VSCODE. I'll try and fish out the relates issues.

**Comment by joaomoreno** [comment]
#12588
