### ISSUE TITLE
Quickpick filter does not apply on promise resolution

### ISSUE THREAD

**Issue by felipecaputo** [Microsoft/vscode#15662]
- VSCode Version: 1.7.1
- OS Version: Windows 10 / Ubuntu 16.04

Relative to https://github.com/felipecaputo/git-project-manager/issues/30

Steps to Reproduce:

1. Show QuickPick of the Git Project Manager extension
2. Before the promise resolve, type part of the project name in the quickpick input box
3. The list is not filtered, but if you type anything else, the filter starts

**Comment by bpasero** [comment]
@felipecaputo can you distill a simple hello world extension that demonstrates this problem and share it here?

**Comment by felipecaputo** [comment]
@bpasero sure, I will make it later today

**Comment by felipecaputo** [comment]
@bpasero Here it is. I've also recorded a gif to show the behavior

[hello-world-quickpick.zip](https://github.com/Microsoft/vscode/files/600560/hello-world-quickpick.zip)
![issue](https://cloud.githubusercontent.com/assets/7751449/20439803/7b224eb6-ada4-11e6-9010-bb44e5b5eb93.gif)

**Comment by bpasero** [comment]
@felipecaputo very helpful, thanks 👍
