### ISSUE TITLE
java run erorr

### ISSUE THREAD

**Issue by lukelwai** [microsoft/vscode#156648]
When running the program in the figure, I found that the running result was wrong. The following is the result comparison of the same program running in idea

![image](https://user-images.githubusercontent.com/55864530/181717894-d7b961be-376a-4f5c-b1f4-615d0fc6bc3c.png)
![image](https://user-images.githubusercontent.com/55864530/181717970-1b4dee7c-b8b3-436b-b0f5-dd88dc1d499e.png)

**Comment by FantasqueX** [comment]
vscode is just an editor. It won't change results of Java code. You can try to copy those commands and run them in powershell or something else, and you'll get the same results. I don't think it's a flaw of vscode.

**Comment by lukelwai** [comment]
> vscode is just an editor. It won't change results of Java code. You can try to copy those commands and run them in powershell or something else, and you'll get the same results. I don't think it's a flaw of vscode.

Thanks for your reply, it's exactly as you said
