### ISSUE TITLE
Find in Notebook/Settings/Keybindings stops working

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#156604]
* Open a notebook
* Put focus into a cell editor
* Ctrl/Cmd+F, Find Widget doesn't show up
* Put focus on cell container (out of Monaco editor), Ctrl+Cmd +F, Find Widget shows up

It's a regression, and my guess is we introduced `list.find` recently for File Explorer. @joaomoreno what's the best way to allow us override it?

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/commit/e45b7a5a426802fb475b3a0856b80b313f2c9411 will help?

**Comment by rebornix** [comment]
@gjsjohnmurray thanks for the pointer, it doesn't seem to fix the problem.

Moreover Ctrl+F in Keybindings Editor doesn't work either.
