### ISSUE TITLE
Ability to select all checkboxes on each side with one click (3 Way Merge Editor)

### ISSUE THREAD

**Issue by zeusstl** [microsoft/vscode#156617]
(I searched through everything with merge editor and didn't find this feature. Hope I'm not duplicating.)

There are still many cases in which I would want to select all the checkboxes.
Seems like an option to select all on each side would be beneficial. Probably with an alert that this would override your existing changes.

Use case: 50 changes on the right and only 1 change on the left. I want to accept all changes on the right besides one. I want to select all and then uncheck 1.

**Comment by hediet** [comment]
Behind the three dots on each side there is a command to accept all.
