### ISSUE TITLE
Remote development: Zombie file watcher processes not cleaned up on remote host

### ISSUE THREAD

**Issue by jvilk-stripe** [microsoft/vscode#156690]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version:
  - Host: Mac OS 12.4
  - Remote host: Ubuntu 20.04.4

Steps to Reproduce:

1. Open VS Code to a remote workspace over SSH with `--disable-extensions`.
2. Reload the window.
3. Observe that there are now _two_ fileWatcher processes. You can run [this program](https://github.com/bdowling/fatso83-dotfiles/blob/master/utils/scripts/inotify-consumers) to see that they are both running and consuming inotify watchers.
4. Close VS Code. Observe that the fileWatchers are still present.

Here's the proof of them still consuming watches via [this script](https://github.com/bdowling/fatso83-dotfiles/blob/master/utils/scripts/inotify-consumers):

```
   INOTIFY
   WATCHES
    COUNT     PID USER     COMMAND
--------------------------------------
 [censored]    1344 jvilk    /pay/home/jvilk/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node /pay/home/jvilk/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/bootstrap-fork --type=fileWatcher
  [censored]  130881 jvilk    /pay/home/jvilk/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/node /pay/home/jvilk/.vscode-server/bin/3b889b090b5ad5793f524b5d1d39fda662b96a2a/out/bootstrap-fork --type=fileWatcher
```

They both have the same parent process:

```
$ ps -o ppid= -p 1344
130615
$ ps -o ppid= -p 130881
130615
```

If you reload 5 times, you end up with 5 processes.

In 1.68, the fileWatcher process closes when the window is reloaded or closed. This appears to be a new bug.

This bug is causing Stripe engineers to consume all inotify watches on their development machines.

**Comment by jvilk-stripe** [comment]
Updated to indicate that I tested w/ extensions disabled.

**Comment by jvilk-stripe** [comment]
Validated that this does _not_ happen when VS Code is open locally. Will update title/description to reflect that this is a remote development issue.

**Comment by jvilk-stripe** [comment]
The processes do seem to go away eventually, but it takes many minutes.

**Comment by bpasero** [comment]
> In 1.68, the fileWatcher process closes when the window is reloaded or closed. This appears to be a new bug.

@alexdima can you chime in, my understanding is that each client starts a management process and an extension host process which both should go away when the client disconnects (closes window, quits or reloads window). Did something change here?

**Comment by jvilk-stripe** [comment]
> It is possible to configure excludes in settings (via files.watcherExcludes) to reduce impact on inotify handles, did you try that?

@bpasero Yup, I have already configured excludes to remove all third-party and codegenned artifacts in the repo. There's no more clear fat to trim there. VS Code watches far fewer files than Watchman or Bazel (which also run in the monorepo), but due to the size of our monorepo it is still a fair number of files.

**Comment by bpasero** [comment]
Its funny you mention that because under the hood we do use https://github.com/parcel-bundler/watcher and that has support for Watchman as a backend, we just never allowed to enable this because we have literally 0 testing on this backend since nobody is using Watchman here and could say if it actually works or not...

**Comment by jvilk-stripe** [comment]
@bpasero Oh, you are? For some reason, I thought I saw some commits by you that replaced this with some other watcher by default?

Well, if there is a way to somehow experiment with using watchman as the backend, please let me know!

**Comment by alexdima** [comment]
Bisect points to https://github.com/microsoft/vscode/compare/e71b6105ebb4fbcfbf38a1b62bcbafdb048d3468...e7751367f79f327b8103bee33a07c16817a2c7cd , with the most likely culprit being https://github.com/microsoft/vscode/commit/9396199ba5dbec22a298e0a4933da0d300405247 which fixes leaking extension host connections (and most likely introduces leaking management connections).

**Comment by jvilk-stripe** [comment]
Thank you all for your quick response to this issue! I look forward to the next stable release with this fix. :)

**Comment by bpasero** [comment]
@alexdima can you also put this to the `release/1.70` branch?

**Comment by alexdima** [comment]
Done! --> https://github.com/microsoft/vscode/pull/157557

**Comment by alexdima** [comment]
Steps to verify:
* use the `Remote-SSH` extension to connect to `localhost`
* open a folder (trust it if a prompt is shown)
* in an external terminal run `ps aux | grep vscode-server | grep fileWatcher`
* check that a file watcher process is running
* go to the VS Code window and run `F1 > Developer: Reload Window`
* in an external terminal run `ps aux | grep vscode-server | grep fileWatcher`
* check that a new file watcher is running and the old one no longer shows up

**Comment by weinand** [comment]
I could reproduce the leaked watcher processes in VS Code 1.70 and I've verified that no watcher processes are leaked with the fix.
