### ISSUE TITLE
Changing content in a virtual document

### ISSUE THREAD

**Issue by Keller18306** [microsoft/vscode#156629]
I'm making an extension to download a file into memory, edit it and upload it to the server. However, the file is opened in readonly mode. In the parameters for opening the file, I did not find a disable for this. The documentation doesn't say anything either. However, I found implementations of my own file system, but I do not need it and it seems redundant. I need to receive only file change.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: win11

Steps to Reproduce:

1. Use examle: https://github.com/microsoft/vscode-extension-samples/tree/main/virtual-document-sample
2. Try to change the data in the file

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/api/references/vscode-api#TextDocumentContentProvider is explicit that the document is read-only. For an editable one I recommend implementing a FileSystemProvider

I also https://github.com/microsoft/vscode-discussions for questions like this.

**Comment by Keller18306** [comment]
Yes, I temporarily implemented on the file system. In my opinion, this is a waste of resources.
![image](https://user-images.githubusercontent.com/23178771/181800555-235e8f6b-4873-4535-b0d8-89ba622450b4.png)
![image](https://user-images.githubusercontent.com/23178771/181800983-f20bc370-212f-4e12-8bfd-637c036479cc.png)
