### ISSUE TITLE
Panel at bottom doesn't closes automatically after closing the last terminal window.

### ISSUE THREAD

**Issue by VaibhavMishra950** [microsoft/vscode#156659]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Windows 11 - 21H2 - 22000.832

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by VaibhavMishra950** [comment]
It was only on my computer, So I Reinstalled VS Code deleting all its config files, and now its working fine.
