### ISSUE TITLE
Bracket completion removes `>` in `=>` in JS/TS

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#156601]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.70.0-insider (user setup)
Commit: b4d5b4ed69af953901051b1f049851b9dca3563e
Date: 2022-07-28T05:16:28.624Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

For completions in TS where there is a "=>", the ">" is being read as an unopened closing bracket so it gets removed from the completion. 
Completion provided by Intellicode: `notebook.getCells().some((cell) => cell.`
After bracket completion: `notebook.getCells().some((cell) = cell.)`

![removing non-bracket 1](https://user-images.githubusercontent.com/86270736/181601503-3af2fc26-c620-4f9f-8c56-5f18e98b961a.gif)

This bug causes the following behavior where after you accept the completion, it changes to something else than what was shown in grey. Note: After accepting, the text added in the buffer is what Intellicode returned as a completion instead of what was displayed in grey.

cc @hediet

**Comment by hediet** [comment]
I wonder why `>` in `=>` is red in your case, that shouldn't be the case.

**Comment by juihanamshet1** [comment]
Good catch Henning! I was only able to test my changes in Code-OSS until now and I think that may have been the cause of it. I tested it in Insiders today since it was updated and not running into this bug anymore :)
