### ISSUE TITLE
No sticky scrolling for markdown headers

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156609]
Testing #156175

1. Enable sticky scrolling
1. Open a md file with headers and scroll through it

**Bug**
Nothing shows up for sticky scrolling

I'd expect the headers to stick (notice how they are present in the outline view)

**Comment by hugows** [comment]
I just tried this and had the same expectation!

**Comment by aiday-mar** [comment]
Fixed by https://github.com/microsoft/vscode/pull/157483

**Comment by IanMatthewHuff** [comment]
Looks good now. Verified.
