### ISSUE TITLE
[folding] organize imports on save expands minimized imports

### ISSUE THREAD

**Issue by emiomacollins** [microsoft/vscode#156675]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: windows

Steps to Reproduce:

1.  add this to settings.json 
        "editor.codeActionsOnSave": {
		"source.organizeImports": true
	},
2. minimize your imports
3. save 
4. imports get expanded automatically

it's a bit annoying to manually minimize imports every time I save. and I also like having my imports get organized on save, it helps remove unused imports.

**Comment by mjbvz** [comment]
Also partially caused by https://github.com/microsoft/TypeScript/issues/39823 but that's only for cases where the imports are already sorted
