### ISSUE TITLE
No sticky scrolling for JavaScript inside of html

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156610]
Testing #156175

1. Enable sticky scrolling
1. with an html file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
class Foo {



















    
}
    </script>
</body>
</html>
```

**Bug**

When scrolling though the file, `Foo` does not stick. The same code work in a plain JS file

**Comment by aiday-mar** [comment]
Thanks for the bug. This should be fixed with PR https://github.com/microsoft/vscode/pull/157483.

![Uploading sticky-scroll-js-html.gif…]()

**Comment by aiday-mar** [comment]
Test

- Open an HTML file with JavaScript code inside as in the examples above. 
- Verify that sticky scrolling works as expected inside of the JavaScript code block

**Comment by luabud** [comment]
Looking good!
 
![StickyScroll156610](https://user-images.githubusercontent.com/45497113/186261532-6e877d9f-4e27-4f1c-8b6b-1566926d1d72.gif)
