### ISSUE TITLE
3 way merge works poorly with git.openDiffOnClick disabled

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#156642]
Steps to Reproduce
1. Set `git.openDiffOnClick` to `false`
2. Trigger a merge conflict
3. Click to open merge conflict from SCM view

🐛 => A regular editor with merge markers appears but no code lenses.

Previously the code lenses were automatic so handling the merge conflict was not affected by this setting. Now, this seemingly unrelated setting interrupts handling the merge conflict and its not obvious you need to click the open diff icon.

**Comment by sbatten** [comment]
Sorry for the spam I wasn't sure who owns this part

**Comment by isidorn** [comment]
Thanks for reporting but will be fixed as part of https://github.com/microsoft/vscode/issues/157691
Thus closing as duplicate
