### ISSUE TITLE
The white border of Code’s icon is too thin, inconsistent with Visual Studio

### ISSUE THREAD

**Issue by be5invis** [Microsoft/vscode#15664]
Compare:
![](https://pbs.twimg.com/media/Cxal5FQUkAAuwzh.jpg:large)
(cc @rebornix)

**Comment by bgashler1** [comment]
We've got an updated icon coming soon that addresses your issue here.  Thanks for sharing your feedback :)

**Comment by weinand** [comment]
Actually, I prefer the thin line of VS Code.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6607
