### ISSUE TITLE
Memory leak in mainThreadTerminalsService

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#156687]
Testing https://github.com/microsoft/vscode/issues/155232. The original big leak seems to be fixed, but I think I found another. Using the following code:

```
for (	let i = 0; i < 10; i++) {
	const terms = [];
	for (let i = 0; i < 50; i++) {
		const t = vscode.window.createTerminal(`Ext Terminal #${NEXT_TERM_ID++}`);
		t.show();
		terms.push(t);
		await new Promise(r => setTimeout(r, 50));
	}

	await new Promise(r => setTimeout(r, 1000));

	for (const term of terms) {
		term.dispose();
	}
}
```

I ended with a 400MB heap in the renderer. that never went down. I notice that `_extHostTerminals` in the mainThreadTerminalService still has 500 entries even a few minutes after all terminals were disposed.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/2230985/181818051-f2b76878-67ac-45fe-9fed-aae1838aab3d.png">

Let me know if you want the heap snapshot, it's 100MB compressed so a bit big to share here.

**Comment by gjsjohnmurray** [comment]
Maybe this is what #156326 is fixing.

**Comment by SvanT** [comment]
Yes exactly https://github.com/microsoft/vscode/pull/156326 should fix it.

**Comment by SvanT** [comment]
Also I think https://github.com/xtermjs/xterm.js/pull/3919 isn't released to vscode yet. it fixes a few more missing terminal disposals.
