### ISSUE TITLE
Electron update: DND from explorer to editor area no longer works

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15663]
- VSCode Version: Code - Insiders 1.8.0-insider (3408691c13470346a119141e57aa74b302464a4a, 2016-11-14T07:19:10.587Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.5.40|
|git-project-manager|felipecaputo|0.1.17|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.5.0|
|csharp|ms-vscode|1.5.2|
|typescript-javascript-grammar|ms-vscode|0.0.9|
|sass-indented|robinbentley|1.2.1|

---

Related: https://github.com/Microsoft/vscode/issues/13260

Steps to Reproduce:

1. Drag and drop on explorer or tab

![image](https://cloud.githubusercontent.com/assets/2193314/20400138/6a33a746-aca8-11e6-8bae-aaff94f6aabb.png)
![image](https://cloud.githubusercontent.com/assets/2193314/20400269/dd3811be-aca8-11e6-9d65-855e1db08073.png)

**Comment by bpasero** [comment]
damn it, looks like what https://github.com/atom/atom/pull/12696#issuecomment-260907987 says hits us too now...

**Comment by Tyriar** [comment]
After trying to reproduce this again it seems to be gone. I restarted and updated since.

```
Version 1.8.0-insider
Commit 043310affe454f94c665494b77818c1425cbe8db
Date 2016-11-17T12:27:28.054Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
```

Probably safe to close, if you have an explanation of why it would fix that would make me feel better though  :stuck_out_tongue:

**Comment by bpasero** [comment]
I can easily reproduce on Mac, I would be surprised if this issue is at random...
