### ISSUE TITLE
installed PowerShell-6.2.7-win-x64.msi, cannot launch terminal, Exit Code 1

### ISSUE THREAD

**Issue by WilliamDAssafMSFT** [microsoft/vscode#156636]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22622

Steps to Reproduce:

1. installed PowerShell-6.2.7-win-x64.msi
2. reboot
3. Try to switch PowerShell terminal to PS6 terminal.
(These aren't labeled by version frustratingly, but the one without Windows is PS6.)
![image](https://user-images.githubusercontent.com/74387232/181658135-fb11b683-3f08-4fa7-99d1-8ad2544c10ac.png)

Error code: The terminal process "C:\Program Files\PowerShell\6\pwsh.exe '-NoProfile', '-ExecutionPolicy', 'Bypass', '-Command', 'Import-Module 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.6.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2022.6.3 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\logs\1659053935-a657fa8b-c22b-4198-950b-cd0951ad52431659053486679\EditorServices.log' -SessionDetailsPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\sessions\PSES-VSCode-20060-847851' -FeatureFlags @() '" terminated with exit code: 1.

Notes: 
PowerShell v5.1 launches terminal fine.
PowerShell v6 launches fine in Windows Terminal.
I see that [feedback about error code 1](https://code.visualstudio.com/docs/supporting/troubleshoot-terminal-launch#_the-terminal-exited-with-code-1-on-windows-10-with-wsl-as-the-default-shell) and am not trying to use WSL, but nevertheless I don't see a problem here with a default distro:

```powershell
PS C:\windows\system32> wsl --list --online
The following is a list of valid distributions that can be installed.
The default distribution is denoted by '*'.
Install using 'wsl --install -d <Distro>'.

  NAME               FRIENDLY NAME
* Ubuntu             Ubuntu
  Debian             Debian GNU/Linux
  kali-linux         Kali Linux Rolling
  openSUSE-42        openSUSE Leap 42
  SLES-12            SUSE Linux Enterprise Server v12
  SLES-15            SUSE Linux Enterprise Server v15
  Ubuntu-18.04       Ubuntu 18.04 LTS
  Ubuntu-20.04       Ubuntu 20.04 LTS
  OracleLinux_8_5    Oracle Linux 8.5
  OracleLinux_7_9    Oracle Linux 7.9
```

I uninstalled these two extensions https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl and https://marketplace.visualstudio.com/items?itemName=redhat.vscode-commons and I could now start an integrated terminal in powershell 6, however VS Code indicated that powershell was still starting the whole time:
![image](https://user-images.githubusercontent.com/74387232/181659124-1dcfa171-7826-40ed-afd3-2b7ee76e0abd.png)
and but could not load:

7/28/2022 5:30:47 PM [NORMAL] - Visual Studio Code v1.69.2 64-bit
7/28/2022 5:30:47 PM [NORMAL] - PowerShell Extension v2022.6.3
7/28/2022 5:30:47 PM [NORMAL] - Operating System: Windows 64-bit
7/28/2022 5:30:47 PM [NORMAL] - Language server starting --
7/28/2022 5:30:47 PM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\6\pwsh.exe
7/28/2022 5:30:47 PM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.6.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2022.6.3 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\logs\1659054647-6331cf5f-75d8-48a3-b77d-edf5cc92d2521659054645541\EditorServices.log' -SessionDetailsPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\sessions\PSES-VSCode-5108-328142' -FeatureFlags @() 
7/28/2022 5:30:47 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.6.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2022.6.3 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\logs\1659054647-6331cf5f-75d8-48a3-b77d-edf5cc92d2521659054645541\EditorServices.log' -SessionDetailsPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\sessions\PSES-VSCode-5108-328142' -FeatureFlags @() 
7/28/2022 5:30:47 PM [NORMAL] - pwsh.exe started.
7/28/2022 5:30:47 PM [NORMAL] - Waiting for session file
7/28/2022 5:31:01 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:31:04 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:31:11 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:31:14 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:31:50 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:00 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:06 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:16 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:28 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:33 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:34 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:36 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:39 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:32:51 PM [NORMAL] - PSIC is not active terminal. Running in active terminal using 'runSelectedText'
7/28/2022 5:34:49 PM [NORMAL] - Timed out waiting for session file to appear.
7/28/2022 5:34:49 PM [NORMAL] - Language server startup failed.
7/28/2022 5:34:49 PM [ERROR] - The language service could not be started: 
7/28/2022 5:34:49 PM [ERROR] - Error: Timed out waiting for session file to appear.

The problem also occurs on immediate startup of VSCode with a .ps1 file, 

7/28/2022 5:42:12 PM [NORMAL] - Visual Studio Code v1.69.2 64-bit
7/28/2022 5:42:12 PM [NORMAL] - PowerShell Extension v2022.6.3
7/28/2022 5:42:12 PM [NORMAL] - Operating System: Windows 64-bit
7/28/2022 5:42:12 PM [NORMAL] - Language server starting --
7/28/2022 5:42:12 PM [NORMAL] -     PowerShell executable: C:\Program Files\PowerShell\6\pwsh.exe
7/28/2022 5:42:12 PM [NORMAL] -     PowerShell args: -NoProfile -ExecutionPolicy Bypass -Command Import-Module 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.6.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2022.6.3 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\logs\1659055332-fb3c26e8-969c-4762-b704-1f088bb577c21659055330464\EditorServices.log' -SessionDetailsPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\sessions\PSES-VSCode-13132-743911' -FeatureFlags @() 
7/28/2022 5:42:12 PM [NORMAL] -     PowerShell Editor Services args: Import-Module 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.6.3' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\modules' -EnableConsoleRepl -StartupBanner '=====> PowerShell Integrated Console v2022.6.3 <=====
' -LogLevel 'Normal' -LogPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\logs\1659055332-fb3c26e8-969c-4762-b704-1f088bb577c21659055330464\EditorServices.log' -SessionDetailsPath 'c:\Users\wiassaf\.vscode\extensions\ms-vscode.powershell-2022.6.3\sessions\PSES-VSCode-13132-743911' -FeatureFlags @() 
7/28/2022 5:42:12 PM [NORMAL] - pwsh.exe started.
7/28/2022 5:42:12 PM [NORMAL] - Waiting for session file

even though I have a PS6 terminal: 
![image](https://user-images.githubusercontent.com/74387232/181659846-53b27e1c-894e-4878-be15-9046e48cce70.png)

**Comment by WilliamDAssafMSFT** [comment]
Note: Installed PowerShell 7.2.5, no problems with that. Seems to be limited to PS6.

**Comment by meganrogge** [comment]
the status bar indicator you reference above is coming from the powershell extension. pls create an issue in that repo.
