### ISSUE TITLE
Where is the most vital feature - drag and drop of source code???

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#15666]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10240
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|theme-monokaiextended|Scatolina|0.0.1|
|theme-setimonokai|SmukkeKim|0.0.1|

---

Steps to Reproduce:

1. Select some part of your source code.
2. Try to drag and drop it to other line or place.
3. FAIL! It is not possible!

HOW could it happen that it is not possible yet?

**Comment by rebornix** [comment]
Dup of https://github.com/Microsoft/vscode/issues/1046.
