### ISSUE TITLE
Add separate theme color(s) for comments in overview ruler / scrollbar

### ISSUE THREAD

**Issue by hermannloose** [microsoft/vscode#156653]
Decorations for lines with review comments are currently drawn in the center lane of the overview ruler / scrollbar using the same color as the editor gutter decorations for commenting ranges, `editorGutter.commentRangeForeground` ([source](https://github.com/microsoft/vscode/blob/84dc769b20d232daa03472cb29d3ccc67b91e3e7/src/vs/workbench/contrib/comments/browser/commentGlyphWidget.ts#L38)). The bright gray used for the editor gutter decorations is not very distinct from the color used for search results or occurrences of the current token under the cursor, which are drawn in the same lane.

We would like the flexibility of a new theme color (which can by default inherit from `editorGutter.commentRangeForeground`) to allow users to have the comments be more noticeable, while not affecting the editor gutter decorations.

As #127473 is being finalized, it might also make sense to go for two new theme colors right away, one for unresolved comment threads (which users likely want more prominent) and one for resolved comment threads (which can probably be more subtle), e.g. `editorOverviewRuler.unresolvedComment` and `editorOverviewRuler.resolvedComment`.

Alternatively, if new colors should be kept to a minimum, we could also work with the overview ruler reusing `editorCommentsWidget.unresolvedBorder` and `editorCommentsWidget.resolvedBorder`, although that starts to erode the scope that those color names suggest.

cc @alexr00 @laurentlb @albertelo

**Comment by hermannloose** [comment]
In the example screenshot, bright gray are comments, slightly darker gray are token occurrences.

<img width="174" alt="Screen Shot 2022-07-29 at 11 30 26" src="https://user-images.githubusercontent.com/163766/181730080-af016d18-6299-4b79-90d1-068b0fa64a17.png">

For our internal user base being used to "unresolved" = "warning yellow", we would like to highlight unresolved comments in the overview ruler with a similar treatment, but this would make the editor gutter decorations misleading, as not every comment glyph widget in the editor gutter is for an unresolved comment.

I assume that on a technical level, `CommentGlyphWidget` will need information about the `CommentThreadState` of the comment for the `lineNumber` it's being rendered at anyway to pass to the overview ruler decoration, so while we are at it, we could consider two additional colors to draw `CommentGlyphWidget` in a color that reflects resolved / unresolved state.

**Comment by alexr00** [comment]
@hermannloose this is a reasonable request, but not something we're likely to work on soon. I would accept a PR if you wanted to make one.
