### ISSUE TITLE
Code lenses mess up sticky scroll

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#156606]
Testing #156175

1. Enable sticky scroll 
1. Enable code lenses (I'm using the code lenses from gitlens)
2. Scroll through a large TS file with code lenses

**Bug**
The sticky headers are incorrect

Here for example `NotebookData` is sticky but the breadcrumbs show the class at the top of the file is `NotebookCellExecutionSummary`

![Screen Shot 2022-07-28 at 11 09 01 AM](https://user-images.githubusercontent.com/12821956/181607950-6d755e6d-f25d-41ea-a4a6-ae86fb27d42f.png)

**Comment by aiday-mar** [comment]
Fixed by https://github.com/microsoft/vscode/commit/463d53f24eac85c81e57371135c3bc744157d5e1
