### ISSUE TITLE
Build issue with nodejs 18

### ISSUE THREAD

**Issue by FantasqueX** [microsoft/vscode#156647]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: main branch
- OS Version: ArchLinux 5.18.14-arch1-1

Steps to Reproduce:

1. yarn install --ignore-engines

Hi, I would like to build vscode with nodejs 18, although I know "Warning: Versions of node.js >= 17 have not been tested." very well and I don't expect official support for nodejs 18. Currently, build failed at https://github.com/microsoft/vscode/blob/e8ee2cf78ffe38e878fc0faa652f9515502fe58c/build/npm/postinstall.js#L50
I wonder is it possible to pass "--ignore-engines" parameter to `yarn install` in build if there is a such argument in command line?

I expect something like https://github.com/microsoft/vscode/blob/e8ee2cf78ffe38e878fc0faa652f9515502fe58c/build/npm/postinstall.js#L70

**Comment by joaomoreno** [comment]
> I don't expect official support for nodejs 18

There's no official support for nodejs 18, sorry.
