### ISSUE TITLE
Restricted Mode banner: Add 'Do not show again' button

### ISSUE THREAD

**Issue by mbelsky** [microsoft/vscode#156743]
Hi vscode people,

Every time I open a new folder and enable Restricted Mode for the folder I see the `Restricted Mode is intended for safe code browsing…` banner and have to close it manually:

<img width="512" alt="Screenshot 2022-07-31 at 13 03 11" src="https://user-images.githubusercontent.com/3923527/182023087-bb9e008f-53ba-46cc-b436-ca4603e598e5.png">

As a user I would like to have ability to hide this banner for all new folders, projects, and workspaces.

What do you think about adding `Do not show again` button to this banner which may help reach described behaviour?

If it looks like a valid feature I'd like to help implementing it.

**Comment by sbatten** [comment]
@mbelsky we have such a setting here `security.workspace.trust.banner`
