### ISSUE TITLE
Intialize repository

### ISSUE THREAD

**Issue by medmad03** [microsoft/vscode#156765]
Issue Type: <b>Performance Issue</b>

My intialize repository is not working so also my source control. Please what can I do? I can't upload my folders to my git hub 

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8700  @ 2.53GHz (2 x 2527)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: unavailable_off<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|3.93GB (0.95GB free)|
|Process Argv|--crash-reporter-id 333115b1-8630-4121-bc94-bbd734cdcd6b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   100	  2408	code main
    3	    89	  1020	   issue-reporter
    1	    91	  4152	   gpu-process
    0	   148	  4876	   "C:\Program Files\Google\Chrome\Application\chrome.exe" --single-argument https://github.com/login/oauth/authorize?client_id=01ab8ac9400c4e429b23&redirect_uri=https://vscode.dev/redirect&scope=read:user+repo+user:email+workflow&state=vscode%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%253D01832b2c-7898-47d9-a480-5b66e3067652%2526windowId%253D1
    0	   101	  1480	     window (undefined)
    0	    58	  1500	     window (undefined)
    0	   351	  4728	     window (undefined)
    0	    28	  5308	     window (undefined)
    0	    64	  8136	     gpu-process
    0	    17	  8188	     utility
    0	     7	  9212	     crashpad-handler
    0	    33	  9996	     utility-network-service
    0	    25	  5508	   crashpad-handler
    2	   101	  8096	   shared-process
    0	    73	  4824	     fileWatcher
    0	    68	  7920	     ptyHost
    0	   219	  8780	   window (Get Started - iSPAK - Visual Studio Code)
    0	    41	  8804	   utility-network-service
    0	   119	 10120	   extensionHost
    0	    74	  9064	     "C:\Users\new pc\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\new pc\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=10120
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Get Started - iSPAK - Visual Studio Code)
|    Folder (iSPAK): 3 files
|      File types: html(1) css(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.1
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.1.2
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
LiveServer|rit|5.7.5
vscode-icons|vsc|11.13.0
vscode-open-in-github|ziy|1.3.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
vscaac:30438847
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the Git channel of the Output panel give any messages?

What version of Git for Windows did you install?

**Comment by medmad03** [comment]
No there's no response.
Git version: 2.37.1

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gjsjohnmurray** [comment]
Please run the Start Extension Bisect command from the Command Palette to investigate whether the problem is being caused by one of your extensions.

**Comment by medmad03** [comment]
Done it's showing nothing and it says no source control providers registered

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stempelo** [comment]
Check in the extensions and filter @builtin
Then check if "Git" is enabled

**Comment by lszomoru** [comment]
@medmad03, after launching VS Code, can you also invoke the `Developer: Show Running Extensions` command from the command palette, and see if you see the `Git` and `Git Base` extensions in the list of running extensions? If these extensions are not running you will have to open the "Extensions" viewlet, search for `@builtin` and make sure that both the `Git` and `Git Base` extensions are enabled.
