### ISSUE TITLE
Enabled the VSCodeVim plugin to use Microsoft Pinyin (IME), the prompt bar keeps moving

### ISSUE THREAD

**Issue by zhanyeye** [microsoft/vscode#156780]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: `1.70.0-insider, This problem has existed since v1.64.2`
- OS Version: windows11

similar to https://github.com/microsoft/vscode/issues/154935#issue-1302130405

**Describe the bug**
+ When enabled the [VSCodeVim](https://github.com/VSCodeVim/Vim) plugin to use Microsoft Pinyin (IME), the prompt bar keeps moving, making the content unclear.

+ But if the **VSCode** version is before 1.63.2 or when **VSCodeVim**  is disabled, the prompt bar will not move.
+ **It may be that the version update after v1.63.2 caused this problem.**

**To Reproduce**
+ **[VSCodeVim Enabled]** The prompt bar of Microsoft Pinyin keeps moving 

https://user-images.githubusercontent.com/35565811/182103490-0093155e-5883-4300-a687-11c824bd57e3.mp4

**Expected behavior**
+ **[VSCodeVim Disabled or VSCode version is before 1.63.2]** The prompt bar of Microsoft Pinyin is fixed 

https://user-images.githubusercontent.com/35565811/182103531-3dd7b497-7144-4d4b-a2a3-4c7140c184b0.mp4

**Comment by aiday-mar** [comment]
Hi thank you for filing this issue. This issue should be fixed with the new experimental setting `editor.experimentalEditContextEnabled` which should be made available in the next Insiders release. This issue will be closed.
