### ISSUE TITLE
Wayland Zoom in/out types +/- when vscode is in the background and some other app with wayland natural zoom capabilities in the background

### ISSUE THREAD

**Issue by realKarthikNair** [microsoft/vscode#156761]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Pop!_OS 22.04

Note: The team can actually ignore this bug since it's not a big deal and prolly don't even affect 5% of the vscode users out there since the issue is reproducible (partially) only on laptops running linux on Wayland display protocol. Still reporting this as my responsibility.

**This issue can only be reproduced in wayland sessions. Also that it doesn't always occur**

Steps to Reproduce:

1. Open VSCode and some file 
2. Open Chrome with ozone platform as Wayland and try pinch natural zoom in out or using laptop touchpad
3. Instead of the expected behaviour of web page zoom, the WIndow manager switches to vscode and types + for pinch in gesture and - for pinch out (or the vice versa) untill I lift my fingers. Lifting the fingers and retrying finger gestures of vscode actually changes the text size/ scaling in vscode which is expected. But if i switch back to chrome and retry those same gestures, the bug is most of the time reproducible. 

Browser gestures work fine after closing vscode from the background.

This behaviour doesnt also occur if browser is open in a different workspace and vscode in another

**Comment by deepak1556** [comment]
Does the issue repro with other Electron apps like Slack or Teams in the background ? Seems like a generic issue to the Electron runtime.

**Comment by realKarthikNair** [comment]
Yep I've seen it occur with other electron apps too

**Comment by deepak1556** [comment]
Unable to repro with the steps provided on Ubuntu 22.04 using latest stable `1.74`, are you also running VSCode with `--ozone-platform=wayland --enable-features=WaylandWindowDecorations` ?

**Comment by realKarthikNair** [comment]
No I'm not using those options
