### ISSUE TITLE
being able to change speed of editor.cursorSmoothCaretAnimation

### ISSUE THREAD

**Issue by laralove143** [microsoft/vscode#156700]
thats a cool setting but i think being able to speed up the animation would make it used by more people, especially when completing long suggestions the text is inserted instantly then you can see the caret move over it

maybe an option to make the text appear smooth would be cool too so its in sync with the caret, this would only be practical when we can make the animation faster

**Comment by alexdima** [comment]
I agree that typing and seeing the cursor animate over the newly typed letters is super annoying. I think the fix should be to not animate the cursor in the typing case.

**Comment by laralove143** [comment]
that could be a way to do it but i think that'd be more inconsistent, it could just animate the text too, is this not possible?

**Comment by alexdima** [comment]
> that could be a way to do it but i think that'd be more inconsistent, it could just animate the text too, is this not possible?

No, I don't think this is possible because our rendering deals with a line entirely, so the whole line would animate if any animation is added. Let's track in #109787
