### ISSUE TITLE
Local extension fails to activate with `Activating extension '...' failed: Failed to fetch.`

### ISSUE THREAD

**Issue by leep-frog** [microsoft/vscode#156770]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 

```
> code --version
1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64
```

- OS Version:
```
OS Name:	Microsoft Windows 11 Home
Version:		10.0.22000 Build 22000
```

Steps to Reproduce:

While running [this extension](https://marketplace.visualstudio.com/items?itemName=groogle.groog) locally (through `Run And Debug` script), I started to encounter the following error:

```
[38;5;21m[Extension Host] STOPPED on first line for debugging on port 53183
[38;5;63m INFO Loading development extension at c:\Users\gleep\OneDrive\Desktop\Coding\vs-code\vs-extension
[38;5;143m WARN [twxs.cmake]: Cannot register 'cmake.cmakePath'. This property is already registered.
Overwriting grammar scope name to file mapping for scope source.cpp.embedded.macro.
Old grammar file: file:///c%3A/Users/gleep/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.embedded.macro.tmLanguage.json.
New grammar file: file:///c%3A/Users/gleep/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.embedded.macro.tmLanguage.json
Overwriting grammar scope name to file mapping for scope source.cpp.
Old grammar file: file:///c%3A/Users/gleep/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/extensions/cpp/syntaxes/cpp.tmLanguage.json.
New grammar file: file:///c%3A/Users/gleep/.vscode/extensions/jeff-hykin.better-cpp-syntax-1.15.19/autogenerated/cpp.tmLanguage.json


TypeError: Failed to fetch
	at self.fetch (../../../vs/workbench/api/worker/extensionHostWorker.js:78:1898)
	at R._loadCommonJSModule (../../../vs/workbench/api/worker/extensionHostWorker.js:77:63236)
	at async Promise.all (index 0)
	at async g._activate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8180)
	at async g._waitForDepsThenActivate (../../../vs/workbench/api/worker/extensionHostWorker.js:69:8122)
	at async g._initialize (../../../vs/workbench/api/worker/extensionHostWorker.js:69:7486) {name: 'TypeError', message: 'Activating extension 'groogle.groog' failed: Failed to fetch.', stack: 'TypeError: Failed to fetch
	at self.fetch (..…ch/api/worker/extensionHostWorker.js:69:7486)'}

```

The only error message that displays in the window is 

```
Activating extension 'groogle.groog' failed: Failed to fetch.
```

This error randomly started happening for me, and doesn't appear to be linked with any of the extension's actual code.  Below are fixes I already tried to no avail:

- reverted to earlier commits locally to see if a new commit was the issue
- uninstalled and reinstalled vscode
- verified the actual extension wasn't enabled (so only the locally built one was being used)

**Comment by gjsjohnmurray** [comment]
The repository link from your extension's Marketplace entry gives a 404 error.

Anyway, as an extension developer you might find https://github.com/microsoft/vscode-discussions a better place for questions like this one.

**Comment by leep-frog** [comment]
Thanks for the redirection.

Fortunately, I ended up figuring out the issue. I recently changed the `terminal.integrated.defaultProfile.windows` setting to an Msys2 MinGW profile.  Changing the default profile back to `null` did the trick.

However, do you know if it's possible to have two separate terminal profiles configured--one for default profile and one specifically for extension development processes?

**Comment by gjsjohnmurray** [comment]
> do you know if it's possible to have two separate terminal profiles configured...

I don't, but this sounds like a good question for the other place.

**Comment by leep-frog** [comment]
for anyone else who stumbles on this post, the following settings worked:
```
  "terminal.integrated.defaultProfile.windows": "MinGW",
  "terminal.integrated.automationProfile.windows": {
    "path": "C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
  },
```
