### ISSUE TITLE
enable html autocomplete for a different language

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#15677]
I see that you can associate html emmet with other languages (as shown below), but is there some way to do the same for auto-complete?

```
"emmet.syntaxProfiles": {
     "visualforce": "html"
}
```

Seems like there are a 100 (and growing) variants of html, all which use the same core syntax.  It would be very nice to be able to configure html/css auto-complete to work with other variants.

**Comment by aeschli** [comment]
You can add a file association in the settings
```
    //Configure file associations to languages (e.g. "*.extension": "html"). These have precedence over the default associations of the languages installed.
    "files.associations": {
        "*.extension": "html"
    },
```

**Comment by ChuckJonas** [comment]
Won't this overwrite the existing language setting for the file extension? (and thus break any extensions that are working off it's language id)

**Comment by ramya-rao-a** [comment]
@ChuckJonas 

![image](https://user-images.githubusercontent.com/16890566/29182341-60442c74-7db3-11e7-9d0a-26ed000a3695.png)
