### ISSUE TITLE
[Fixed] Web page issue on https://code.visualstudio.com/download#

### ISSUE THREAD

**Issue by localhost61** [microsoft/vscode#156714]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: v169.2
- OS Version: All

Steps to Reproduce:
Try to download latest VSCode setup in whatever version from the official webpage https://code.visualstudio.com/download#
... it doesn't work
Change to https://code.visualstudio.com/insiders/#win and there it works. Click a button of whatever version and you get redirected to a new page like https://code.visualstudio.com/docs/?dv=winzip&build=insiders (if you click on zip) and a popup to download the very file.
[Workaround]
As I didn't want insider build, I just removed '&build=insiders' from the URL and got the one I wanted : 
https://az764295.vo.msecnd.net/stable/3b889b090b5ad5793f524b5d1d39fda662b96a2a/VSCode-win32-x64-1.69.2.zip
instead of :
https://az764295.vo.msecnd.net/insider/12b08be500f8a307f30e92cbc3ee39ba115eab69/VSCode-win32-x64-1.70.0-insider.zip

**Comment by bpasero** [comment]
fyi @gregvanl

**Comment by localhost61** [comment]
I'm very sorry to bother,
It was a cookie story. I feel concerned with privacy but am fed up with cookies notifications and use "I don't care about cookies" plugin on Waterfox to automatically dismiss  the notifications. It leads sometimes to a weird behavior. It was the case on this page.
Added an exception for VScode and refused cookies. The magic works again now. ;-).

**Comment by localhost61** [comment]
I'm very sorry to bother,
It was a cookie story. I feel concerned with privacy but am fed up with cookies notifications and use "I don't care about cookies" plugin on Waterfox to automatically dismiss  the notifications. It leads sometimes to a weird behavior. It was the case on this page.
Added an exception for VScode and refused cookies. The magic works now. ;-).
