### ISSUE TITLE
Ender 5 Pro XYZ homing + Z height constantly changing! Terrible Marlin 'Bugfixed'2.1 

### ISSUE THREAD

**Issue by Alectronics** [microsoft/vscode#156740]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.Bybye Marlin. After days of constantly solving problems while getting new ones I quit and go to TH3D. Marlin is extremely bugged!
2.

**Comment by Alectronics** [comment]
Sure. Closed but not solved.
________________________________
Van: Joyce Er ***@***.***>
Verzonden: maandag 1 augustus 2022 23:39
Aan: microsoft/vscode ***@***.***>
CC: Alectronics ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/vscode] Ender 5 Pro XYZ homing + Z height constantly changing! Terrible Marlin 'Bugfixed'2.1 (Issue #156740)


Closed #156740<https://github.com/microsoft/vscode/issues/156740> as completed.

**Comment by joyceerhl** [comment]
@Alectronics could you please provide additional information about the issue you are experiencing, if it is related to VS Code? Thank you!

**Comment by Alectronics** [comment]
I will try to find a log file or maybe send you my config.h and confid.adv.h files?

________________________________
Van: Joyce Er ***@***.***>
Verzonden: dinsdag 2 augustus 2022 23:05
Aan: microsoft/vscode ***@***.***>
CC: Alectronics ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [microsoft/vscode] Ender 5 Pro XYZ homing + Z height constantly changing! Terrible Marlin 'Bugfixed'2.1 (Issue #156740)


@Alectronics<https://github.com/Alectronics> could you please provide additional information about the issue you are experiencing, if it is related to VS Code? Thank you!

**Comment by joyceerhl** [comment]
Please provide steps to reproduce the problem in VS Code--without that we can't diagnose the issue. Thanks!

**Comment by Alectronics** [comment]
Thanks but maybe the problem is just the wrong Marlin code? Because the TH3D apparently had the same Z height unwanted annoying changing issue after homing XYZ. And they only used the Configurator.h file of Marlin for my Ender 5 Pro. Whereas the Marlin Ender 5 Pro firmware used both Configurator.h and adv.h files in VS Code.
And is why I kept the still annoying Marlin Firmware on my with CR-Touch and Runout detector upgraded Ender 5 Pro 3D printer.

Best regards.

Albert.

________________________________
Van: Joyce Er ***@***.***>
Verzonden: dinsdag 2 augustus 2022 23:35
Aan: microsoft/vscode ***@***.***>
CC: Alectronics ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [microsoft/vscode] Ender 5 Pro XYZ homing + Z height constantly changing! Terrible Marlin 'Bugfixed'2.1 (Issue #156740)


Please provide steps to reproduce the problem in VS Code--without that we can't diagnose the issue. Thanks!
