### ISSUE TITLE
Source Control Stuck with Clock Sign When Commit without message

### ISSUE THREAD

**Issue by yiang-li** [microsoft/vscode#156706]
Issue Type: <b>Bug</b>

Hi, when commiting changes to Source Control for Git without putting message, the VS Code Source Control will forever have a clock on the side and stuck there. VS Code could learn from the Github Desktop commit function that put message as required field before clicking commit.

VS Code version: Code 1.69.2 (Universal) (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|276, 138, 58|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 094037af-f4b5-4626-92ac-f23d650be8fa|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
foam-vscode|foa|0.19.1
copilot|Git|1.36.6340
vscode-pull-request-github|Git|0.46.1
vsc-python-indent|Kev|1.17.0
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
autodocstring|njp|0.6.1
vscode-yaml|red|1.9.1
r|REd|2.5.2
pdf|tom|1.2.0
vscodeintellicode|Vis|1.2.22
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by lszomoru** [comment]
@yiang-li, VS Code 1.69 contains a new feature that enables users to use a full editor to author a commit message as described in [the release notes](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor). Is that not the behaviour that you are seeing? This new behaviour can also be disabled by toggling the `git.useEditorAsCommitInput` setting.
