### ISSUE TITLE
Input focus on terminal when launching terminal

### ISSUE THREAD

**Issue by TheKingEagle** [microsoft/vscode#156767]
Issue Type: <b>Feature Request</b>

I've screwed up and had to panic undo mistaken edits or searches 30 times now, every time I open the terminal, thinking it had focus. When the terminal is open, can we have input focus automatically sent to the terminal?

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by gjsjohnmurray** [comment]
Try searching for the words terminal and focus in the Settings Ede.

**Comment by TheKingEagle** [comment]
I see what you are saying, Perhaps the issue is more of how I use terminal. rather than opening it from the menu, I've just been dragging it up from the bottom of the screen, and it relaunches that way.
