### ISSUE TITLE
Git: Support stashing before sync/pull

### ISSUE THREAD

**Issue by scgm11** [Microsoft/vscode#15671]
- VSCode Version: 1.7.1
- OS Version: MacOS Sierra

Steps to Reproduce:

Be able to use shelving or stashing when syncing so if we have uncomited changes we can update from origin, this is how intelliJ does it and is very useful.

**Comment by noamyogev84** [comment]
Hi, Can I try to contribute here? New to this repo.

**Comment by joaomoreno** [comment]
**Verification**

1. Enable `git.autoStash`
2. Make sure changes get stashed before pull/sync and restored afterwards
