### ISSUE TITLE
Bug report: "Commit Staged (amend)" seems broken

### ISSUE THREAD

**Issue by bonjourjoel** [microsoft/vscode#156771]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.69.2 (user setup)
- OS Version:Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Source control must initially be in a state where everything is commited and there are no changes, and there is at least one previous commit.
2. Change a file
3. Open source control panel
4. menu > commit > Commit Staged (amend)

What happens:

- It's weird. It opens a sort of fake file called .git\COMMIT_EDITMSG. The file doesn't seem to really be there, i'm not sure.
- It prevents the commit/amend to complete. It hangs in a buggy state.
- It happens since the last update. Before it would just amend the last commit, which i believe it is supposed to do.

Sorry if i'm not clear, but what happens is not clear to me neither. Is it a new feature?
Here is a screenshot of what happens.

![COMMIT_EDITMSG_weard_bug](https://user-images.githubusercontent.com/78134277/182059710-6b220a9d-1077-4af7-834e-e0b6e12e0211.png)

Oh and here is another (maybe useful) information: If i repeat the last commit message in the commit message box, and do "commit staged (amend)", then it works correctly like before. But i'd rather not have to do this as I use the amend feature quite a lot.

**Comment by gjsjohnmurray** [comment]
Does information in #154449 help?

**Comment by bonjourjoel** [comment]
No, it's another issue. I use the vscode interface, not command line. And I shouldn't have to seizure a commit message, as i'm amending the previous commit.
I think the last update introduced the following bug: **If commit/amend, then it should use the previous commit message, and not request a new one.**

**Comment by gjsjohnmurray** [comment]
Isn't that what it is doing? Is the text in the first line of that editor tab your previous message? Did you try clicking the checkmark button in the upper right?

**Comment by bonjourjoel** [comment]
Thanks. If it was doing it, i wouldn't post a bug report. Maybe you try to reproduce the issue ?

**Comment by gjsjohnmurray** [comment]
Your problem description didn't mention that you clicked the button. It also implied that you weren't familiar with 1.69 change in this area.

https://github.com/microsoft/vscode/issues/154449#issuecomment-1178880918 includes a screenshot of the setting.

That issue claims to have been fixed in the 1.69.2 version you have, so maybe another problem remains. Are you able to test with Insiders (upcoming 1.70)?

**Comment by bonjourjoel** [comment]
Oh i see. This setting removes the issue indeed: "Use Editor As Commit Input" set to false.
And no, the checkmark button was blocked and everything stuck, so this is pretty much a bug IMO because commit/amend does not require a message normally. But nevermind with this setting it works like before.
Sorry i didn't understand. And thank you. Cheers.
