### ISSUE TITLE
how to debug python code with parameter?

### ISSUE THREAD

**Issue by civilmanxx** [Microsoft/vscode#15676]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04

I installed python extension and want to debug .py code. My .py file needs input parameters for running.

How can I assign values for input parameters during debug?

such as **_app.py --param1="value1" --param2="value2"_** for a debug session

**Comment by ramya-rao-a** [comment]
Debugging for Python is provided by the extension. Please log your issue/question in the repo of the extension that you are using
