### ISSUE TITLE
Menus don't always display correctly in Ubuntu guest in VMware with GPU acceleration disabled

### ISSUE THREAD

**Issue by jeremyn** [microsoft/vscode#156719]
Issue Type: <b>Bug</b>

I'm using an Ubuntu 22.04 guest in VMware with GPU acceleration disabled. Sometimes when I open a menu dropdown, the options don't display until I move my mouse over them. See the attached webm file for an example.

I originally reported this problem at https://github.com/microsoft/vscode/issues/154705#issuecomment-1182208733. Disabling GPU acceleration works around the different problem described in that issue.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:14:10.636Z)
OS version: Linux x64 5.15.0-43-generic
Restricted Mode: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor (2 x 3600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|0, 0, 1|
|Memory (System)|7.76GB (2.08GB free)|
|Process Argv|--disable-gpu --disable-extensions --crash-reporter-id 0ddd5c78-f440-4dee-bff2-c646a50f1eda|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled

[vscode_menu_display_bug.webm](https://user-images.githubusercontent.com/299895/181933322-b0f1fc06-e427-44ca-b135-e653bdbd889d.webm)

**Comment by deepak1556** [comment]
Looks like you are using native titlebar ? What is the value of the setting `"window.titleBarStyle"` in your setup ?

Can you try with custom titlebar `"window.titleBarStyle": "custom"` and see if the issue persists ?

**Comment by jeremyn** [comment]
@hermidalc asked at https://github.com/microsoft/vscode/issues/154705#issuecomment-1200425794:

> @jeremyn are you getting the issue #156719 in the clean Fedora 36 guest VM you spooled up?

No, I can't reproduce this menu problem in Fedora 36 using either v1.69.2 stable or the v1.70 exploration build provided at https://github.com/microsoft/vscode/issues/154705#issuecomment-1189334979.

@deepak1556 Yes the title bar setting was set to `native`, the default. I've changed it to `custom` and this problem doesn't happen there. Thanks very much! That's a totally decent workaround until this problem is properly fixed. (Actually the `custom` menus look better to me so I'll probably keep that setting permanently.)

**Comment by deepak1556** [comment]
Based on your comment from https://github.com/microsoft/vscode/issues/154705#issuecomment-1200251432, the problem only occurs when hardware acceleration is disabled. Given chromium disables hardware acceleration for VMWare and this is an issue with the native titlebar which we don't control, marking as `out-of-scope`. Please switch to use custom titlebar as workaround `"window.titleBarStyle": "custom"`.
