### ISSUE TITLE
Screencast Mode always on

### ISSUE THREAD

**Issue by crashmax-dev** [microsoft/vscode#156789]
It would be great to be able to set the settings so that screencast mode always on.

```json
{
  "screencastMode.enabled": "always",
}
```

**Comment by Suven-p** [comment]
![image](https://user-images.githubusercontent.com/47393058/186834456-24c7a03d-a4e1-47ee-b72c-4ec0f3a002bf.png)
Something like this.
Can an action listen for changeConfiguration even when its not running?

**Comment by crashmax-dev** [comment]
@Suven-p 

> ![image](https://user-images.githubusercontent.com/47393058/186834456-24c7a03d-a4e1-47ee-b72c-4ec0f3a002bf.png) > Something like this?

Yes, this is a setting in the UI.
The setting value will be written `settings.json`.

> Can an action listen for changeConfiguration even when its not running?

Why not.

**Comment by Suven-p** [comment]
I tried using https://github.com/microsoft/vscode/blob/b5a1bb34e9c6b77c2a8ccf54bcdbb4bac4d420cb/src/vs/platform/configuration/common/configurationRegistry.ts#L81
but it is triggered only at the beginning and not when settings change. I could not find any example of event listener for configuration change in action outside of run function.

**Comment by Suven-p** [comment]
Should screencastmode be a service instead of a action?

**Comment by joaomoreno** [comment]
We'd need a simple workbench contribution that listens for that setting and sets screencast mode accordingly. Here's a good example: https://github.com/microsoft/vscode/blob/918dd8994786ded70b458ca8b2351412d5692080/src/vs/workbench/contrib/offline/browser/offline.contribution.ts#L96-L97

**Comment by joaomoreno** [comment]
This extension can run a command on startup: https://marketplace.visualstudio.com/items?itemName=gabrielgrinberg.auto-run-command. So, all a user needs to do is configure it to run the `workbench.action.toggleScreencastMode` command in order to achieve this.

Closing as out of scope.

**Comment by klimhammet62** [comment]
ВЫ ОБИДЕЛИ МОЕГО ПОВЕЛИТЕЛЯ! ВЫ БУДЕТЕ ЗА ЭТО НАКАЗАНЫ!
