### ISSUE TITLE
Builtin terminal doesn't redraw line if terminal size is too small

### ISSUE THREAD

**Issue by BLucky-gh** [microsoft/vscode#156713]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: MacOS 12.3.1

Steps to Reproduce:

1. start a python app that shows a progress bar
2. split the terminal window so that the progress bar doesn't fit on one line
3. the progress bar now repeats instead of redrawing until the terminal is resized

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal
