### ISSUE TITLE
Provide an action to navigate to derived resource

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#1567]
I have an ancient visual studio habit of pressing `ctrl ~` to flip between the `.cpp` and `.h` files.
In my projects, I also often have `.inl` files, and it's always annoyed me that ctrl-~ doesn't include those while flipping between files.

Could I suggest, adding ctrl-~, but cycling between all associated files (that is, files with the same name, but different file extension).

**Comment by bpasero** [comment]
:+1:

**Comment by mjbvz** [comment]
Closing as this can be implemented by an extension
