### ISSUE TITLE
TS debugging: vscode shows extensionHostProcess.js and stops working.

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#156741]
VS Code Version:
Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 20.6.0

Description:
I have created a simple project to reproduce the problem. It is based on the [your first extension](https://code.visualstudio.com/api/get-started/your-first-extension) example. Just an async function call added at the end of the activate function (line 26-36 in extension.ts).

**If the program is paused once, it is not possible to re-start the debug session or even stop it.
After that it is required to close the window and open it again.**

Steps to Reproduce:

1. Compile the attached TS extension.
2. Press "Run extension"
3. The extension starts . (The extension is immediately activated through activationEvents: "*")
4.  Let it run a few seconds (e.g. 10s).  
5. Pause the extension:  
![Bildschirmfoto 2022-07-31 um 11 09 52](https://user-images.githubusercontent.com/3081973/182019230-c3d88485-cbeb-4f36-b192-d9409a8e310d.jpg)
6. vscode breaks and shows
![Bildschirmfoto 2022-07-31 um 11 04 38](https://user-images.githubusercontent.com/3081973/182019051-dba11cc0-804b-4743-92ab-10c4c8f6fc29.jpg)
7. Now press stop 
![Bildschirmfoto 2022-07-31 um 11 10 55](https://user-images.githubusercontent.com/3081973/182019277-100d7a33-e596-4a22-b015-fee049a8a577.jpg) to end the debug session.

**Result:**
Nothing happens. It is not possible to end or restart the debug session.
The only way to get out of this situation is to close the window and re-open it.

Note:
This problem seems to last for some longer. (A few months, maybe even longer). Today I decided to create a simple project and report an error.
The problem also occurs in other situations. Often when I try use breakpoints "Un/caught Exceptions". 
What is always similar: if the extensionHostProcess.js is shown by vscode it is not possible anymore to continue or restart the debug session.

[debug_problem.zip](https://github.com/microsoft/vscode/files/9228560/debug_problem.zip)

**Comment by connor4312** [comment]
I'm not able to reproduce this. If you can still reproduce this, please do the following:

1. Hit this case
2. In the windows _doing the debugging_, run the "Show Running Extensions" command
3. Hit the record button on the upper right corner to start collecting a CPU profile.
4. After 10 seconds or so, stop it. Click the save 💾  button and share the resulting profile file

**Comment by maziac** [comment]
I did an extension bisect and found that vscode-todo-highlight is the cause for this behavior.
We can close the issue here (I created a new one [here](https://github.com/wayou/vscode-todo-highlight/issues/220)).
