### ISSUE TITLE
Keep checkboxes in viewport

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#156787]
@hediet I think this is a good example 
<img width="640" alt="image" src="https://user-images.githubusercontent.com/6561887/181792448-d2ffcb10-7f29-4bf6-a6a9-067f4cb402e2.png">

I got feedback from a friend who hit this same behavior. They had several coworkers look at this screen and they could not discover what to do the first time. Only after finding a tutorial on YouTube did they figure out that checkmarks were the mechanism.

Essentially we should show the checkmarks always even if the chunks are larger than the viewport, they should probably float. Another idea discussed was allowing you to right click in the chunk to accept it

_Originally posted by @sbatten in https://github.com/microsoft/vscode/issues/155911#issuecomment-1199539654_

**Comment by isidorn** [comment]
Closing as duplicate
