### ISSUE TITLE
Task decoration not enabled when `"task.showDecorations": true` and `"terminal.integrated.shellIntegration.decorationsEnabled": "never"`

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#156728]
Version: 1.70.0-insider (Universal)
Commit: 12b08be500f8a307f30e92cbc3ee39ba115eab69
Date: 2022-07-29T10:50:40.282Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 20.6.0

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Set Task decoration not enabled when `"task.showDecorations": true` and `"terminal.integrated.shellIntegration.decorationsEnabled": "never"`
2. Run a task
3. Task decorations are not shown.

![taskdeco](https://user-images.githubusercontent.com/10665499/182003578-725ed70a-d5e4-45a7-a5b8-ca3c9d840ca8.png)

When `"terminal.integrated.shellIntegration.decorationsEnabled": "both"`

![taskdeconormal](https://user-images.githubusercontent.com/10665499/182003629-826741ef-e2a0-4e0e-b873-7fd616c138e0.png)

Ref: https://github.com/microsoft/vscode/issues/153812#issuecomment-1171555376

**Comment by meganrogge** [comment]
@Tyriar and I discussed it and we will update the setting description to indicate that it will respect `terminal.integrated.shellIntegration.decorationsEnabled`.
