### ISSUE TITLE
The top margin of Terminal is large when `"window.zoomLevel": 1` and  `"terminal.integrated.gpuAcceleration": "off"`

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#156701]
The top margin of Terminal is large when `"window.zoomLevel": 1` and  `"terminal.integrated.gpuAcceleration": "off"`

Version: 1.70.0-insider (Universal)
Commit: 12b08be500f8a307f30e92cbc3ee39ba115eab69
Date: 2022-07-29T10:50:40.282Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 20.6.0

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Set `"window.zoomLevel": 1` and  `"terminal.integrated.gpuAcceleration": "off"`.
2. Put Terminal on Secondary Side Bar.
3. Drag up and down the top of Terminal.
4. The top margin of Terminal is ridiculously large sometimes.

Sometimes too large:

![terminaltop](https://user-images.githubusercontent.com/10665499/181862284-7cbd1c3f-5b3a-4cb0-9906-23e137d989ff.png)

Sometimes  good:

![terminaltop2](https://user-images.githubusercontent.com/10665499/181862378-7707ebcf-3cba-4673-93ad-cffad5f28eb8.png)

**Comment by meganrogge** [comment]
I believe this has the same root cause as #134448, @Tyriar thoughts?

**Comment by Tyriar** [comment]
@meganrogge that one is Windows only, this is on mac.

I believe this is zsh telling the terminal to write new lines at the top, @tamuratak when you see this could you run the `Terminal: Select All` command? That will show the true dimensions of the terminal, if there are lines above it selected it was zsh that wrote the new lines and I don't think we can do anything here.

**Comment by tamuratak** [comment]
There is no line:

![terminalselectall](https://user-images.githubusercontent.com/10665499/182725673-c4229db6-eb49-43f9-9d29-33e11d50ee02.png)

**Comment by tamuratak** [comment]
I hope the following video would help:

https://user-images.githubusercontent.com/10665499/182730278-3e7841d7-8f76-4b50-aedf-dbbf0b263875.mov

**Comment by Tyriar** [comment]
I polished the top margin in the past year and can no longer see a problem.
