### ISSUE TITLE
Very slow startup

### ISSUE THREAD

**Issue by KodornaRocks** [microsoft/vscode#156702]
Hello, I'm experiencing a very very slow startup.
On a older, slower computer it is starting up sub-second, and here is over 20 seconds to finish openning and being ready to type-in.

Exactly the same problem occurs in the same machine using a brand new Insiders installation.

## System Info

* Code: 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a)
* OS: win32(10.0.22621)
* CPUs: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz(12 x 2592)
* Memory(System): 31.71 GB(22.08GB free)
* Memory(Process): 242.20 MB working set(201.50MB private, 1.11MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 135     
[prof-2XkB9XsO.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/9224118/prof-2XkB9XsO.extHost.cpuprofile.txt)
[prof-2XkB9XsO.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9224119/prof-2XkB9XsO.main.cpuprofile.txt)
[prof-2XkB9XsO.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9224120/prof-2XkB9XsO.renderer.cpuprofile.txt)
 | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 237      | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 33       | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 5        | [main]                    | initial startup: true                                       |
| create window                                                   | 55       | [main]                    | initial startup: true, state: 0ms, widget: 19ms, show: 32ms |
| app.isReady => window.loadUrl()                                 | 421      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 4560     | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 1269     | [renderer]                | cached data: NO, node_modules took 0ms                      |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 30       | [renderer]                | -                                                           |
| init workspace service                                          | 102      | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 5366     | [renderer]                | -                                                           |
| restore viewlet                                                 | 0        | [renderer]                | -                                                           |
| restore panel                                                   | 73       | [renderer]                | terminal                                                    |
| restore & resolve visible editors                               | 104      | [renderer]                | 1: workbench.runtimeExtensions.input                        |
| overall workbench load                                          | 796      | [renderer]                | -                                                           |
| workbench ready                                                 | 7311     | [main->renderer]          | -                                                           |
| renderer ready                                                  | 2210     | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 12842    | [renderer]                | -                                                           |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                              | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | ---------------------------------- | --------------------------------------- |
| vscode.git                              | true  | 199       | 31            | 95              | *                                  | vscode.git                              |
| vscode.git-base                         | true  | 14        | 0             | 20              | *                                  | vscode.git                              |
| vscode.github                           | true  | 40        | 0             | 0               | *                                  | vscode.github                           |
| vscode.ipynb                            | true  | 35        | 4             | 16              | *                                  | vscode.ipynb                            |
| ms-python.python                        | true  | 784       | 16            | 1791            | workspaceContains:requirements.txt | ms-python.python                        |
| vscode.configuration-editing            | false | 11        | 1             | 0               | onLanguage:jsonc                   | vscode.configuration-editing            |
| vscode.emmet                            | false | 82        | 9             | 275             | onStartupFinished                  | vscode.emmet                            |
| vscode.github-authentication            | false | 60        | 13            | 0               | onAuthenticationRequest:github     | vscode.github-authentication            |
| vscode.json-language-features           | false | 102       | 0             | 357             | onLanguage:jsonc                   | vscode.json-language-features           |
| vscode.merge-conflict                   | false | 15        | 3             | 272             | onStartupFinished                  | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 126       | 25            | 1108            | onAuthenticationRequest:microsoft  | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 112       | 32            | 241             | onStartupFinished                  | ms-vscode-remote.remote-wsl-recommender |
| bradlc.vscode-tailwindcss               | false | 106       | 0             | 340             | onStartupFinished                  | bradlc.vscode-tailwindcss               |
| GitHub.copilot                          | false | 409       | 230           | 536             | onStartupFinished                  | GitHub.copilot                          |
| GrapeCity.gc-excelviewer                | false | 16        | 3             | 284             | onLanguage:plaintext               | GrapeCity.gc-excelviewer                |
| ms-vscode-remote.remote-containers      | false | 391       | 0             | 235             | onStartupFinished                  | ms-vscode-remote.remote-containers      |
| ms-vscode-remote.remote-wsl             | false | 103       | 8             | 2               | onStartupFinished                  | ms-vscode-remote.remote-wsl             |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1659144899237	0	0
code/didStartMain	1659144899448	211	211
code/willStartCrashReporter	1659144899488	40	251
code/didStartCrashReporter	1659144899521	33	284
code/mainAppReady	1659144899583	62	346
code/willLoadMainBundle	1659144899588	5	351
code/fork/willLoadCode	1659144899626	38	389
code/registerFilesystem/file	1659144899812	186	575
code/didLoadMainBundle	1659144899825	13	588
code/willStartMainServer	1659144899849	24	612
code/didStartMainServer	1659144899854	5	617
code/willCreateCodeWindow	1659144899945	91	708
code/willRestoreCodeWindowState	1659144899946	1	709
code/didRestoreCodeWindowState	1659144899946	0	709
code/willCreateCodeBrowserWindow	1659144899947	1	710
code/didCreateCodeBrowserWindow	1659144899966	19	729
code/willMaximizeCodeWindow	1659144899966	0	729
code/didMaximizeCodeWindow	1659144899998	32	761
code/didCreateCodeWindow	1659144900000	2	763
code/willOpenNewWindow	1659144900004	4	767
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1659144900006	0	0
code/didStartRenderer	1659144904549	4543	4543
code/willWaitForWindowConfig	1659144904550	1	4544
code/didWaitForWindowConfig	1659144904550	0	4544
code/willShowPartsSplash	1659144904551	1	4545
code/didShowPartsSplash	1659144904552	1	4546
code/willLoadWorkbenchMain	1659144904564	12	4558
code/didLoadWorkbenchMain	1659144905833	1269	5827
code/registerFilesystem/file	1659144905843	10	5837
code/registerFilesystem/vscode-userdata	1659144905844	1	5838
code/willInitWorkspaceService	1659144905853	9	5847
code/willInitStorage	1659144905857	4	5851
code/didInitStorage	1659144905887	30	5881
code/willInitUserConfiguration	1659144905895	8	5889
code/didInitUserConfiguration	1659144905918	23	5912
code/willInitWorkspaceConfiguration	1659144905918	0	5912
code/didInitWorkspaceConfiguration	1659144905954	36	5948
code/didInitWorkspaceService	1659144905955	1	5949
code/willStartWorkbench	1659144905963	8	5957
code/LifecyclePhase/Ready	1659144906109	146	6103
code/registerFilesystem/trustedDomains	1659144906172	63	6166
code/registerFilesystem/vscode-local-history	1659144906177	5	6171
code/willRestoreEditors	1659144906655	478	6649
code/willRestorePanel	1659144906675	20	6669
code/didRestorePanel	1659144906748	73	6742
code/didRestoreEditors	1659144906759	11	6753
code/LifecyclePhase/Restored	1659144906759	0	6753
code/didStartWorkbench	1659144906759	0	6753
code/didRemovePartsSplash	1659144906759	0	6753
code/registerFilesystem/vscode-debug-memory	1659144906772	13	6766
code/willConnectSharedProcess	1659144906824	52	6818
code/willLoadExtensions	1659144906924	100	6918
code/LifecyclePhase/Eventually	1659144909268	2344	9262
code/willHandleExtensionPoints	1659144911782	2514	11776
code/didHandleExtensionPoints	1659144912273	491	12267
code/didLoadExtensions	1659144912290	17	12284
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1659144911616	0	0
code/fork/start	1659144911930	314	314
code/fork/willLoadCode	1659144912004	74	388
code/extHost/willConnectToRenderer	1659144912801	797	1185
code/extHost/didConnectToRenderer	1659144912833	32	1217
code/extHost/didWaitForInitData	1659144912922	89	1306
code/extHost/didCreateServices	1659144912937	15	1321
code/extHost/willWaitForConfig	1659144912951	14	1335
code/extHost/didWaitForConfig	1659144913073	122	1457
code/extHost/didInitAPI	1659144913074	1	1458
code/extHost/didInitProxyResolver	1659144913086	12	1470
code/extHost/ready	1659144913086	0	1470
code/extHost/willLoadExtensionCode/vscode.git-base	1659144913160	74	1544
code/extHost/didLoadExtensionCode/vscode.git-base	1659144913174	14	1558
code/extHost/willLoadExtensionCode/vscode.ipynb	1659144913175	1	1559
code/extHost/didLoadExtensionCode/vscode.ipynb	1659144913210	35	1594
code/extHost/willLoadExtensionCode/ms-python.python	1659144913211	1	1595
code/extHost/didLoadExtensionCode/ms-python.python	1659144913995	784	2379
code/extHost/willActivateExtension/vscode.git-base	1659144920126	6131	8510
code/extHost/willActivateExtension/vscode.ipynb	1659144920126	0	8510
code/extHost/willActivateExtension/ms-python.python	1659144920130	4	8514
code/extHost/didActivateExtension/vscode.git-base	1659144920204	74	8588
code/extHost/didActivateExtension/vscode.ipynb	1659144920204	0	8588
code/extHost/willLoadExtensionCode/vscode.git	1659144920311	107	8695
code/extHost/didLoadExtensionCode/vscode.git	1659144920510	199	8894
code/extHost/willLoadExtensionCode/vscode.github	1659144920511	1	8895
code/extHost/didLoadExtensionCode/vscode.github	1659144920551	40	8935
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1659144920553	2	8937
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1659144920679	126	9063
code/extHost/willActivateExtension/vscode.git	1659144920680	1	9064
code/extHost/willActivateExtension/vscode.github	1659144920711	31	9095
code/extHost/didActivateExtension/vscode.github	1659144920725	14	9109
code/extHost/willActivateExtension/vscode.microsoft-authentication	1659144920747	22	9131
code/extHost/didActivateExtension/vscode.git	1659144920806	59	9190
code/extHost/didActivateExtension/vscode.microsoft-authentication	1659144921881	1075	10265
code/extHost/didActivateExtension/ms-python.python	1659144921938	57	10322
```

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by bpasero** [comment]
Everything seems somewhat slow but there is a ton of time spend in the main process resolving the list of recently opened files and folders:

<img width="1465" alt="image" src="https://user-images.githubusercontent.com/900690/182296338-0a291c4f-729a-4920-852b-478a2eddf776.png">

I wonder if that list is huge?

**Comment by KodornaRocks** [comment]
Oh, I'm sorry by the delay, and by loosing the problematic system, in the end, I did a windows fresh installation.

I didn't had any 'gigantic' folders, but I was always using either a wsl2 folders or some SharePoint synchronized folder, maybe that could be the problem.

But, my windows was a mess, I was on the insider's dev channel for the past three years or so (Even my excel now is working better).

For me, the issue is closed, but if this could assist you guys in any way, below are the tests after a fresh windows installation, point to three kinds of folder.

[Common Folder - prof-BrAD6tZ3.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249192/Common.Folder.-.prof-BrAD6tZ3.extHost.cpuprofile.txt)
[Common Folder - prof-BrAD6tZ3.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249193/Common.Folder.-.prof-BrAD6tZ3.main.cpuprofile.txt)
[Common Folder - prof-BrAD6tZ3.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249194/Common.Folder.-.prof-BrAD6tZ3.renderer.cpuprofile.txt)
[OneDrive Folder - prof-FzC0tngv.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249195/OneDrive.Folder.-.prof-FzC0tngv.extHost.cpuprofile.txt)
[OneDrive Folder - prof-FzC0tngv.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249196/OneDrive.Folder.-.prof-FzC0tngv.main.cpuprofile.txt)
[OneDrive Folder - prof-FzC0tngv.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249197/OneDrive.Folder.-.prof-FzC0tngv.renderer.cpuprofile.txt)
[WSL2 Folder - prof-0LfyAmon.extHost.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249198/WSL2.Folder.-.prof-0LfyAmon.extHost.cpuprofile.txt)
[WSL2 Folder - prof-0LfyAmon.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249199/WSL2.Folder.-.prof-0LfyAmon.main.cpuprofile.txt)
[WSL2 Folder - prof-0LfyAmon.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9249200/WSL2.Folder.-.prof-0LfyAmon.renderer.cpuprofile.txt)
