### ISSUE TITLE
C language file view

### ISSUE THREAD

**Issue by ArturCordeiro-jAssy** [microsoft/vscode#156794]
Workspace is slow when viewing files that have very long lines. Some of the lines are at least 15000 characters long, with up to 21000 characters. In notepad++ there is no performance problem.

It's a macro that represents an image, there are several lines for that. like the example below

MACRO(FINISHED_OK, 	      8BIT_COLOR, RUN_LENGTH, TRANSPARENT, 	 NORMAL, BLACK,    26, 22, 0x0E, 0x00, 0x01, 0x96, 0x01, 0x6B, 0x01, 0x96, 0x16, 0x00, 0x01, 0x96, 0x03, 0x47, 0x15, 0x00, 0x01, 0x96, 0x04, 0x47, 0x01, 0x96, 0x13, 0x00, 0x01, 0x96, 0x05, 0x47, 0x01, 0x96, 0x12, 0x00, 0x01, 0x96, 0x06, 0x47, 0x12, 0x00, 0x01, 0x96, 0x06, 0x47, 0x01, 0x6B, 0x11, 0x00, 0x01, 0x96, 0x07, 0x47, 0x01, 0x96, 0x10, 0x00, 0x01, 0x96, 0x08, 0x47, 0x01, 0x71, 0x08, 0x96, 0x01, 0x00, 0x05, 0x96, 0x02, 0x00, 0x12, 0x47, 0x01, 0x96, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x17, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x17, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x17, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x12, 0x47, 0x01, 0x6B, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x12, 0x47, 0x01, 0x96, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x12, 0x47, 0x01, 0x00, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x11, 0x47, 0x01, 0x72, 0x01, 0x00, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x11, 0x47, 0x02, 0x00, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x10, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x10, 0x47, 0x01, 0x96, 0x02, 0x00, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x0F, 0x47, 0x01, 0x6B, 0x03, 0x00, 0x04, 0x47, 0x01, 0x6B, 0x02, 0x00, 0x01, 0x6B, 0x0E, 0x47, 0x01, 0x96, 0x03, 0x00, 0x04, 0x6B, 0x01, 0x71, 0x03, 0x00, 0x01, 0x71, 0x0C, 0x6B, 0x01, 0x96, 0x04, 0x00) \

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/7772
