### ISSUE TITLE
Consider improving tooltip UX.

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#156749]
Often when I want to copy something from the end of a tooltip, the tooltip disappears before I get a chance to select the text:

https://user-images.githubusercontent.com/2737650/182026215-09300f08-91c8-4310-8841-3c13312f1766.mov

This makes it feel like I'm playing level 3 of the scary maze game:
![image](https://user-images.githubusercontent.com/2737650/182026330-ea2c5df8-4833-49f8-9149-343fa877b9ee.png)

Consider making UX a bit better in regards to tooltips by doing one of the following:
- Add a small configurable delay before tooltips disappear. This way it would be possible to move the cursor away from the tooltip briefly without it disappearing.
- Make tooltips stay visible until the user clicks the background
- Increase the area required for tooltips to disappear, this is the current approach in Blender:

https://user-images.githubusercontent.com/2737650/182026732-6f3f55f7-81e5-42bb-b6eb-2d876105f50e.mov

**Comment by rahul-s-bhatt** [comment]
What do you think of adding a small pin button that would pin this to your screen for few seconds or until you un pin it? @jespertheend

**Comment by jespertheend** [comment]
@rahul-s-bhatt Not sure how useful that would be in this scenario to be honest. Often I want to just copy some selected text and then forget about it. If I have to click a pin button twice every time I need to copy something, I'd probably not pin it at all.

Also the pin button would have to be strategically placed for it to not suffer from the same problem, otherwise the tooltip would just disappear before you get a chance to move the cursor to the pin button.

Don't get me wrong, I definitely think a pin button could be useful for certain use cases. But I'm not sure how useful it would be for the use case shown in the first video above.

**Comment by yume-chan** [comment]
The lock option has already been tested and abandoned in https://github.com/microsoft/vscode/issues/115034#issuecomment-987984412

The final solution is holding Alt to keep the hover open. However, editor hovers are handled differently so doesn't has this feature added.

Seems no one complains about that. The only one I can find is #151763, but that one still doesn't request Alt key to keep editor hovers open by default.

**Comment by jespertheend** [comment]
Holding alt to lock tooltips would work for me as well. Although I think the way Blender handles it would be preferable for new users, since holding alt isn't really a well known way to deal with this (I didn't know about this).

**Comment by yume-chan** [comment]
#159384 now tracks the `alt` locking feature, but I also agree increasing the hover response area is a good idea.

**Comment by PEZ** [comment]
I think that the October release had some improvements for the hovers that might address this issue. Sorry for not linking or being more specific. I'm in a hurry, but wanted to point this out anyway.

**Comment by jespertheend** [comment]
I've been using the `editor.hover.hidingDelay` setting for a while now and this indeed mostly fixes my issue.
I'll leave this open because I think the blender approach is really nice and I'd still like to see that at some point.

I find myself spamming the escape key a lot now because sometimes the tooltip is kind of in the way.
The problem is that the escape key closes a bunch of other things as well and I'm never sure in what order, so being able to instantly hide tooltips by moving the cursor out of reach would be a very good alternative for this.
