### ISSUE TITLE
Second workspace window not visible after Mac Screen-Lock (or Sleep)

### ISSUE THREAD

**Issue by ea167** [microsoft/vscode#156836]
Issue Type: <b>Bug</b>

Hi,
I have a second workspace window on an external monitor, using full-screen view.

At first it works perfectly, but when I lock my screen and come back, this 2nd window is not visible anymore. "Switching to" this window brings me to my laptop main screen, but with this window still invisible. 

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:32:39.000Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|64.00GB (18.44GB free)|
|Process Argv|--crash-reporter-id b67f15ef-f120-4a09-ba85-78a42395b651|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
flow-for-vscode|flo|2.2.0
todo-tree|Gru|0.0.215
banner-comments|hey|0.3.0
customize-ui|ioc|0.1.61
monkey-patch|ioc|0.1.18
better-cpp-syntax|jef|1.15.19
vscode-docker|ms-|1.22.1
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
jupyter|ms-|2022.6.1201981810
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
atom-keybindings|ms-|3.0.9
cmake-tools|ms-|1.11.26
cpptools-extension-pack|ms-|1.2.0
jinjahtml|sam|0.17.0
pdf|tom|1.2.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.14.0

(2 theme extensions excluded)

</details>

**Comment by ea167** [comment]
Workaround is to (menu) Window > select 2nd-workspace window, then uncheck (menu) View > Appearance > Full-screen, and move the window back to the external monitor.

**Comment by bpasero** [comment]
That sounds like a setup problem to me and nothing VSCode can fix from within, sorry.
