### ISSUE TITLE
terminal.integrated.inheritEnv setting not working

### ISSUE THREAD

**Issue by alecramsay** [microsoft/vscode#156800]
Issue Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

terminal.integrated.inheritEnv is set to false (not checked), but $PATH in Terminal inside VS Code is wrong. 

## Steps to reproduce:

1. Make sure the setting is off, open VS Code (not just reload), open a Terminal, type echo $PATH.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.4
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

See screenshots

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

venvFolders: "<placeholder>"

languageServer: "Pylance"

formatting
• provider: "black"

terminal
• activateEnvironment: false

```

</p>
</details>

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:57.074Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|. --crash-reporter-id 13eab17c-98ea-4f98-b8d0-695a94888d2f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.36.6340
python|ms-|2022.10.1
vscode-pylance|ms-|2022.7.40
r-debugger|RDe|0.4.7
r|REd|2.5.2
vscode-scheme|sjh|0.4.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by alecramsay** [comment]
I've been working with kartikr on [an issue](https://github.com/microsoft/vscode-python/issues/19238). He asked me to open this one.

Settings
<img width="708" alt="setting" src="https://user-images.githubusercontent.com/4155251/182157001-174d4fa4-4abf-4fdb-92d5-b66ce8a1b00c.png">

$PATH outside VS Code
<img width="708" alt="outside" src="https://user-images.githubusercontent.com/4155251/182157034-e4a83cd1-cbb1-4fad-aa1f-ab2707dc38b7.png">

$PATH inside VS Code
<img width="1015" alt="inside" src="https://user-images.githubusercontent.com/4155251/182157059-27c3138f-5d0a-41ae-bdca-f66a151cfff1.png">

**Comment by meganrogge** [comment]
you could try no longer running a login shell in the terminal by creating a terminal profile and setting its args to []. If you go with this fix, you will want to make sure any aliases in your profile scripts are moved over to your ~/.bashrc/~/.zshrc file since aliases only apply to the shell they're set in

**Comment by karrtikr** [comment]
@alecramsay Here're the step by step instructions for you:

- ![image](https://user-images.githubusercontent.com/13199757/182208154-ca2b74ee-cf85-4390-86b4-be10314fc66b.png)
- ![image](https://user-images.githubusercontent.com/13199757/182209185-a393ecc3-b7cf-4d51-8fb7-9eebca234369.png)
- ![image](https://user-images.githubusercontent.com/13199757/182208349-5cde2a8b-b903-45cc-a98a-1d619ac9301e.png)

Use `Open User settings (JSON)` command.
Set args to `[]`:
```
        "bashwithnoargs": {
            "path": "/usr/bin/bash",
            "args": []
        }
```
- Use ![image](https://user-images.githubusercontent.com/13199757/182208154-ca2b74ee-cf85-4390-86b4-be10314fc66b.png) to select your created profile now.

**Comment by alecramsay** [comment]
The issue I was having that motivated opening this issue -- https://github.com/microsoft/vscode-python/issues/19238 -- has been resolved. I unwittingly had a non-universal / non-Apple silicon version of VS Code installed.
