### ISSUE TITLE
Folding Only Works If File Formatted

### ISSUE THREAD

**Issue by BrianPittVP** [microsoft/vscode#156832]
Issue Type: <b>Bug</b>

Code folding for PHP does not work properly if you have some areas of the file that are not tabbed-in correctly.  This happens if you have an HTML block within a PHP method and you want that HTML block to output left-justified.  When you attempt to Fold/Unfold, VSC doesn't know where the function block ends.  Some parts of the system DO understand it, such as brace matching.  So if brace matching works, why doesn't code folding use the same logic?
NOTE: apologies if this is not native functionality, I can not recall

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.13.0-1031-aws
Remote OS version: Linux x64 4.4.0-1128-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.82GB free)|
|Process Argv|--crash-reporter-id a306a1bd-3e7b-4917-a64e-69b7ab976500|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: blah1|
|OS|Linux x64 5.13.0-1031-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz (2 x 3630)|
|Memory (System)|3.63GB (0.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: blah2|
|OS|Linux x64 4.4.0-1128-aws|
|CPUs|Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz (2 x 2500)|
|Memory (System)|7.59GB (0.94GB free)|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
compare-helper|kee|1.1.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
vscode-intelephense-client|bme|1.8.2
githistory|don|0.6.19
xml|Dot|2.5.1
php-docblocker|nei|2.7.0
vscode-php-getters-setters|php|1.2.3
vscode-xml|red|0.21.0
php-debug|xde|1.27.0
php-pack|xde|1.0.3

</details>

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/api/language-extensions/language-configuration-guide#folding

By default, folding is indent-based. If you have a language server extension that registers a [FoldingRangeProvider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider) you have the option of smarter folding.

I understand that the premium edition of the `vscode-intelephense-client` extension offers this. Are you using that?

**Comment by BrianPittVP** [comment]
Thank you @gjsjohnmurray!  I could not recall what provided that functionality.  I have purchased a license for Intelephense, I should be all set now.

**Comment by aeschli** [comment]
Closing the issue
