### ISSUE TITLE
Background square artefacts wrapping text on non-retina display

### ISSUE THREAD

**Issue by Gil80** [Microsoft/vscode#15681]
- VSCode Version: 1.7.1
- OS Version: macSierra

Steps to Reproduce:

1. Use Dell U2412M calibrated monitor (using calibrated colour profile, a dedicated .icc file created by x-rite colour meter and its software).
2. Connect to macbook pro early 2015 via thuderbolt or HDMI
3. Open a text file in VS Code

Issue:
Text appear to have a background square shapes wrapping it.
Moving the window to the Retina display, the issue disappears.
Moving back to the Dell monitor, the issue reappears.

Using alias 'code --disable-gpu' in .bash_profile solves the background issue.
However, if in command line interface, VScode cannot open a specific file. It will always default to last used file.
Example:
> code someFile.groovy
Vscode will open the previous opened file, instead of someFile.groovy

Another example:
> code .
VScode won't show current working directory. Instead, it will display previous working file.

Removing the alias from .bash_profile fixes the issues in the examples BUT brings back the background shapes artefacts.

See screenshot.

Is it possible to pass the --disable-gpu argument without breaking the function of opening specific file / folder with VScode?

![_bash_profile_-_gillevy](https://cloud.githubusercontent.com/assets/8454919/20414670/b70750a6-ad87-11e6-8bd8-9189c2428252.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473

**Comment by Gil80** [comment]
thanks for the reference.

how can I run Vs code with the argument **--force-gpu-rasterization** just by typing > **code** in terminal or when I click on the icon app?
(using macSierra).

**Comment by Gil80** [comment]
Still waiting on a reply for my last comment.

**Comment by Jacky-Lei** [comment]
Was this issue ever solved?

**Comment by rupamroy** [comment]
was this issue fixed ?

**Comment by rupamroy** [comment]
I found a work around for this problem . In your .bashrc/.profile file create a function instead of an alias
```bash
code() {
    nohup /path/to/code $1 --disable-gpu >/dev/null 2>&1  &
}
```

Then restart shell and then on you can open visual studio code using
```
code .
```

And it will open the current folder in VSCode

**Comment by Jacky-Lei** [comment]
@rupamroy I tried pasting that into my .zsh_profile and .zshrc and it didn't work
