### ISSUE TITLE
can not change display language in vscode insiders web

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#156854]
Version: 1.70.0-insider
Commit: 12b08be500f8a307f30e92cbc3ee39ba115eab69
Date: 2022-07-29T10:46:38.950Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.134 Safari/537.36 Edg/103.0.1264.77

![vscodedisplaylang](https://user-images.githubusercontent.com/1876302/182275578-a80dbaf0-323f-4d2a-ac87-93d949e51421.gif)

**Comment by TylerLeonhardt** [comment]
@heartacker is this vscode.dev or github.dev?

If it's github.dev, can you try replacing `github.dev` with `insiders.vscode.dev/github` in your address bar?

**Comment by heartacker** [comment]
thanks，I do not realize that I am in github.dev

vscode.dev works fine
