### ISSUE TITLE
Shortcut CTRL + # Stop working

### ISSUE THREAD

**Issue by edlixstudios** [microsoft/vscode#156898]
Issue Type: <b>Bug</b>

I cant say why, but my Shortcut for comment a line CTRL + # doesnt work anymore. I can type # and CTRL and all other combination of keys but vscode dont effect in any way when I am typing CTRL + #

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.25GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu-22.04/home/ealbrecht --remote=wsl+Ubuntu-22.04 --crash-reporter-id 8e3c17c3-1ff0-4720-b764-a4c6c60306ad|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-22.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3696)|
|Memory (System)|7.74GB (6.86GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
postcss|css|1.0.9
javascript-ejs-support|Dig|1.3.1
es7-react-js-snippets|dsz|4.4.3
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
unity-code-snippets|kle|1.3.0
sequelize-snippets|kvc|1.0.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
debugger-for-edge|msj|1.0.15
awesome-flutter-snippets|Nas|3.0.3
nativebase-v3-vscode-extension|Nat|0.1.3
material-icon-theme|PKi|4.19.0
vscode-icons|vsc|11.14.0
material-theme|zhu|3.15.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by joyceerhl** [comment]
If you open your keyboard shortcuts and search for ctrl+# are there other commands registered to that keybinding?

![image](https://user-images.githubusercontent.com/30305945/182433177-3bdfbde7-7207-4691-8169-5f9833b27a2f.png)

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl + #`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by edlixstudios** [comment]
Hey @joyceerhl yes it is in there, and now after 3 weeks it works again. I didnt do anything but open the Keyboard Shortcut JSON.

@alexdima a few days ago vscode didnt fired an error message when I typed ctrl + # in the Shortcur Troubleshooting, now it seems working again.

I had the Shortcut Problem for several weeks but only on this device. But for why I was so confused, I use the Logitech MX Keys on all of my devices and on the other devices my shortcut were working.

Thank you both.

[2022-08-03 12:49:06.755] [renderer3] [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
[2022-08-03 12:49:13.332] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2022-08-03 12:49:13.333] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2022-08-03 12:49:13.333] [renderer3] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2022-08-03 12:49:13.558] [renderer3] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: Backslash, keyCode: 191, key: #
[2022-08-03 12:49:13.558] [renderer3] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: Backslash, keyCode: 85 ('/')
[2022-08-03 12:49:13.558] [renderer3] [info] [KeybindingService]: | Resolving ctrl+/
[2022-08-03 12:49:13.558] [renderer3] [info] [KeybindingService]: \ From 1 keybinding entries, no when clauses matched the context.
