### ISSUE TITLE
Add Copy File Name to context menu to the files sidebar

### ISSUE THREAD

**Issue by novialriptide** [microsoft/vscode#156870]
Similar to the "Copy File Path" button, instead of just copying the entire file path, just copy the file's name

**Comment by gjsjohnmurray** [comment]
If you want the extra item in that context menu, extension `ouweiya.copy-file-name` looks like it will do this for you.

IMO adding more options to everyone's context menu is likely to cause complaints, at least until users can customize what options they see.

**Comment by novialriptide** [comment]
> If you want the extra item in that context menu, extension `ouweiya.copy-file-name` looks like it will do this for you.
> 
> IMO adding more options to everyone's context menu is likely to cause complaints, at least until users can customize what options they see.

May I add an option to whether or not "Copy File Name" will show or not?

**Comment by gjsjohnmurray** [comment]
> May I add an option to whether or not "Copy File Name" will show or not?

@novialriptide the decision about whether to accept your PR, even with a config option, will have to be made by someone in the core team. @lramos15 please advise.

**Comment by lramos15** [comment]
Thanks @gjsjohnmurray, yes please install an extension for this if you wish to include this behavior. We already have `Copy Path` and `Copy Relative Path` and `Copy` for copying the file itself. We do not currently have plans to add additional copy functions to the menu.
