### ISSUE TITLE
Invalid ctrl+click links

### ISSUE THREAD

**Issue by RedCMD** [microsoft/vscode#156875]
Vscodes ctrl+click links now consumes `"`, causing it to open an invalid url
(unless the link starts right after a `"` )
Notice how the `"` at the end of the first link is underlined
clicking it takes me to `https://github.com/jeff-hykin/better-c-syntax/blob/master/autogenerated/c.tmLanguage.json"`, which is invalid

![image](https://user-images.githubusercontent.com/33529441/182323225-3f0f6d83-e9ea-4e7d-993e-b4e5db126f98.png)

**Comment by aeschli** [comment]
The links are generated by the textual link detector

What's interesting here is:
If the string is just a link
```
		"https://github.com/jeff-hykin/better-c-syntax/blob/master/autogenerated/c.tmLanguage.json"
```
the link does not include the quote.

If it has content after the starting quote, it includes the final quote.

```
		" https://github.com/jeff-hykin/better-c-syntax/blob/master/autogenerated/c.tmLanguage.json"
```

![image](https://user-images.githubusercontent.com/6461412/186411067-cec5e747-c244-495b-a26c-c600a7d37df4.png)

**Comment by jessejensen** [comment]
I am experiencing the same thing, with single quotes in the terminal. Here are some tests/replication steps you can run in a bash terminal:
```
echo "URL: http://example.com works because it is bare"
echo "URL: 'http://example.com' works because it is wrapped in single quotes"
echo "URL: http://example.com' DOES NOT WORK because the trailing single quote is attached"
```

It's not clear to me if this an error in vscode or [xterm](https://github.com/xtermjs/xterm.js).

**Comment by alexdima** [comment]
The current implementation of the link parser considers `"` or `'` to be stop characters only when the link began with such a quote character. Making quotes always be stop characters in link parsing would end up re-opening https://github.com/microsoft/vscode/issues/17939 where the request was that:
```
let url = `http://***/_api/web/lists/GetByTitle('Teambuildingaanvragen')/items`
```
be identified as a link

**Comment by RedCMD** [comment]
Hmm.. very tricky indeed

that link is surrounded by backticks 
so you could* prioritize finding surrounding quotes/backticks over stopping on a quote

that way
if there is no starting quote/backtick, it can then stop on any quote like before

how often does https://github.com/microsoft/vscode/issues/17939 come up?
and is that link even valid to click tho?
opening it in chrome just takes me google search

my problem affects almost every single `.tmlanguage.json` file in every extension inside the vscode repo

![image](https://user-images.githubusercontent.com/33529441/182323225-3f0f6d83-e9ea-4e7d-993e-b4e5db126f98.png)
this is taken directly from vscodes C extension
clicking the top link gives: 
![Screenshot_20221024_123722](https://user-images.githubusercontent.com/33529441/197423825-85a9f18c-1731-4e00-83f2-4848e807869e.jpg)

**Comment by alexdima** [comment]
I'm trying to make the change discussed here but my local change ends up breaking another test case, the one for https://github.com/microsoft/vscode/issues/151631

In other words, I can't come up with a rule to distinguish:
```
aa https://regexper.com/#%2F''%2F aa
"This file has been converted from https://github.com/jeff-hykin/better-c-syntax/blob/master/autogenerated/c.tmLanguage.json",
```

In both cases, the syntax agnostic link detector encounters quotes (`'` or `"`) and in one case it is desirable that the quote continue the link, while in the other case it is desirable that the quote ends the link. For a parser that is programming language agnostic, these two cases look pretty much identical.
