### ISSUE TITLE
Debugger adapter's "runtimeArgs" parameter is ignored

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#1568]
I am trying to use native ES6 features like `Promise` and `Map` in my debug adapter.   To enable these features, I've created this configuration for my debugger extension:
```
    ...
	"contributes": {
		"debuggers": [
			{
				"program": "./out/DebugSession.js",
				"runtime": "node",
				"runtimeArgs": ["--harmony"],
    ...
```
However the `--harmony` parameter never seems to make it to the command line of the launched code subprocess, so it fails upon encountering ES6 features in the code.

**Comment by isidorn** [comment]
Yup, this had been fixed couple of days ago but will only be available with the January update
