### ISSUE TITLE
Typo in function name

### ISSUE THREAD

**Issue by drtheuns** [microsoft/vscode#156895]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

In `src/vs/editor/contrib/gotoError/browser/gotoError.ts` there's a function: `nagivate`. Presumably this was meant to be `navigate`?

https://github.com/microsoft/vscode/blob/main/src/vs/editor/contrib/gotoError/browser/gotoError.ts#L141

**Comment by mjbvz** [comment]
Please submit a PR
