### ISSUE TITLE
Jupyter notebook in remote ssh slows down, becomes unresponsive, and gets stuck in a reconnection loop

### ISSUE THREAD

**Issue by aroyphillips** [microsoft/vscode#156829]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: MacOS Monterey 12.4

Steps to Reproduce:

1.  Connected to remote server with jupyter notebook. Environment is setup using conda.
2.  Working with a large amount of data. 
3.  Run a function that took <3 minutes to run.
4. Try running the function again with a new set of parameters -- now it's taking over an hour, and hasn't even entered the program since there's a print statement when it starts.

Code snippets and console log are shown below. I have tried triggering reconnect already.
![image](https://user-images.githubusercontent.com/45011712/182241958-8e910dbf-e300-4b3c-9eb0-c23d836b517f.png)
![image](https://user-images.githubusercontent.com/45011712/182242005-9faeea17-1481-4ace-a12c-aae65efff78d.png)

` INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:80 [85h] potential listener LEAK detected, having 256 listeners already. MOST frequent listener (71):
check @ workbench.desktop.main.js:80
workbench.desktop.main.js:80 Error
    at Function.create (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:80:27742)
    at E._event._event [as onDidChange] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1056)
    at r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:92539)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:102295
    at w (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:86:10532)
    at u._signalChange (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:102271)
    at u._createEventAndSignalChange (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:100520)
    at u.trigger (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:99255)
    at o._update (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:102520)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:697:101518
    at b.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at Tn.setModel (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:752:517)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1966:15555
check @ workbench.desktop.main.js:80
workbench.desktop.main.js:80 [e57] potential listener LEAK detected, having 1407 listeners already. MOST frequent listener (1229):
check @ workbench.desktop.main.js:80
workbench.desktop.main.js:80 Error
    at Function.create (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:80:27742)
    at c._event._event [as onDidChange] (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1056)
    at j (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:749:6831)
    at new Ki (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:749:6896)
    at q (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:749:4100)
    at vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:749:4358
    at b.invoke (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:145)
    at r.deliver (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:2266)
    at o.fire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:82:1844)
    at b.createModel (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:749:1095)
    at De.provideTextContent (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2754:456)
    at async o.resolveTextModelContent (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:79186)
    at async o.doCreateReferencedObject (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:77904)
    at async c.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:19:32624)
    at async d.createModelReference (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2741:79923)
    at async o.resolveTextModel (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1731:84174)
check @ workbench.desktop.main.js:80
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/webviews/webview-side/errorRenderer/errorRenderer.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.9/out/client_renderer/renderers.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-2022.6.1201981810/out/webviews/webview-side/errorRenderer/errorRenderer.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] received socket timeout event.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] resolving connection...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] connecting to 127.0.0.1:54321...
workbench.desktop.main.js:602  INFO [remote-connection][ExtensionHost][6b493…][reconnect] reconnected!`

**Comment by aroyphillips** [comment]
This issue continues to persist using jupyter notebooks in VSCode. Please advise.

Console log below:
```
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.12/out/client_renderer/preload.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.12/out/client_renderer/builtinRendererHooks.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.12/out/client_renderer/preload.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/webviews/webview-side/ipywidgetsKernel/ipywidgetsKernel.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://vscode-remote+ssh-002dremote-002bdestroyer-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/roy/.vscode-server/extensions/ms-toolsai.jupyter-renderers-1.0.12/out/client_renderer/builtinRendererHooks.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1190, timeSinceOldestUnacknowledgedMsg: 20001, timeSinceLastReceivedSomeData: 20001).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6261075646f055b99068d3688932416f2346dd3b/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1190, timeSinceOldestUnacknowledgedMsg: 20002, timeSinceLastReceivedSomeData: 20002).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
workbench.desktop.main.js:609  WARN SettingsEditor2: Settings not included in settingsLayout.ts: application.experimental.rendererProfiling
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1197, timeSinceOldestUnacknowledgedMsg: 20001, timeSinceLastReceivedSomeData: 20001).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1198, timeSinceOldestUnacknowledgedMsg: 20002, timeSinceLastReceivedSomeData: 20003).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1198, timeSinceOldestUnacknowledgedMsg: 20003, timeSinceLastReceivedSomeData: 20003).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1198, timeSinceOldestUnacknowledgedMsg: 20002, timeSinceLastReceivedSomeData: 20002).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1198, timeSinceOldestUnacknowledgedMsg: 20005, timeSinceLastReceivedSomeData: 20005).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] received socket timeout event (unacknowledgedMsgCount: 1206, timeSinceOldestUnacknowledgedMsg: 20004, timeSinceLastReceivedSomeData: 20004).
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] starting reconnecting loop. You can get more information with the trace log level.
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] resolving connection...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] connecting to 127.0.0.1:52237...
workbench.desktop.main.js:609  INFO [remote-connection][ExtensionHost][97660…][reconnect] reconnected!
```

**Comment by roblourens** [comment]
Merging this into https://github.com/microsoft/vscode/issues/138784
