### ISSUE TITLE
Should rename `treeSupportsFind` to `listSupportsFind`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#156878]
I think this came up during the standup today, why is the context key called `treeSupportsFind` and not `listSupportsFind`?

//cc @alexdima

**Comment by alexdima** [comment]
This context key came in quite late via a fix -- https://github.com/microsoft/vscode/pull/156637
I noticed this standing out because of the default keybindings which seem to mix things up:

```
{ "key": "f3",                    "command": "list.find",
                                     "when": "listFocus && treeSupportsFind" },
{ "key": "cmd+f",                 "command": "list.find",
                                     "when": "listFocus && treeSupportsFind" },
```

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/commit/e8ee2cf78ffe38e878fc0faa652f9515502fe58c
