### ISSUE TITLE
Whether can unify the style of list and paragraph indentation

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode#156952]
In markdown file, the vscode will show like this:
for list:
![image](https://user-images.githubusercontent.com/82581024/182514298-139cfd2c-f7ff-4da9-9be8-5ad62fb731ff.png)

for paragraph indentation:
![image](https://user-images.githubusercontent.com/82581024/182514337-623cbf32-d479-49ec-b48f-0554e8b143e2.png)

I think the symbol of list is like the paragraph indentation. I think the the symbol of list also need indent like the paragraph indentation.

**Comment by mjbvz** [comment]
Duplicate of #94674
