### ISSUE TITLE
Can't change save all to ctrl+shift+s

### ISSUE THREAD

**Issue by MarioF84** [microsoft/vscode#156997]
Issue Type: <b>Bug</b>

I tried to change the key binding of save all to the win standard ctrl+shift+s, but it does not work.

In the visual editor I am not able to enter ctrl+shift+s at all, if I do so in the json, it still does not work.
I can set it to every other command (e.g. ctrl+shift+a) and it works.

On another system, I did the same and it worked without any problems, same VS Code and Windows versions there...

Reproduction is simple:
- go to the key binding editor
- search for "save all"
- remove existing bindings
- try to add ctrl+shift+s to save all
(I have no extensions installed)

That's the contents of my keybindings.json:
```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+shift+s",
        "command": "workbench.action.files.saveAll"
    },
    {
        "key": "ctrl+k s",
        "command": "-saveAll"
    },
    {
        "key": "ctrl+shift+s",
        "command": "workbench.action.files.saveFiles"
    }
]
```

And that's the simplified keybindings.json from my other system (where it works), but that also does not work here:
```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+shift+s",
        "command": "workbench.action.files.saveAll"
    }
]
```

I also tried to remove all other ctrl+shift+s bindings, but that does not change the behaviour.

With this version, the binding at least gets displayed in the file menu, but still does not work:
```
// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+shift+s",
        "command": "workbench.action.files.saveAll"
    },
    {
        "key": "ctrl+k s",
        "command": "-saveAll"
    },
    {(s)
        "key": "ctrl+shift+s",
        "command": "saveAll"
    },
    {
        "key": "ctrl+k ctrl+shift+s",
        "command": "-workbench.action.files.saveWithoutFormatting"
    },
    {
        "key": "ctrl+shift+s",
        "command": "-workbench.action.files.saveAs"
    },
    {
        "key": "ctrl+shift+s",
        "command": "-workbench.action.files.saveLocalFile",
        "when": "remoteFileDialogVisible"
    }
]
```

On the other system, the menu still shows ctrl+k s, while both are working there.

VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (26.59GB free)|
|Process Argv|--crash-reporter-id defa8b15-1f2c-4a9a-bb73-d29a22e7ff14|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30525689
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728

```

</details>

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+shift+s`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by MarioF84** [comment]
Hi.
I activated the logging, and when I press CTRL+SHIFT+S, I get the following output:
`[2022-08-23 12:56:31.529] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2022-08-23 12:56:31.529] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2022-08-23 12:56:31.529] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2022-08-23 12:56:31.624] [renderer1] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 16, key: Shift
[2022-08-23 12:56:31.625] [renderer1] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,shift], code: ShiftLeft, keyCode: 4 ('Shift')
[2022-08-23 12:56:31.625] [renderer1] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2022-08-23 12:56:32.376] [renderer1] [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.`

Current content of my keybindings.json:
`// Place your key bindings in this file to override the defaultsauto[]
[
    {
        "key": "ctrl+shift+s",
        "command": "saveAll"
    },
    {
        "key": "ctrl+k s",
        "command": "-saveAll"
    },
    {
        "key": "ctrl+shift+s",
        "command": "-workbench.action.files.saveLocalFile",
        "when": "remoteFileDialogVisible"
    },
    {
        "key": "ctrl+shift+s",
        "command": "-workbench.action.files.saveAs"
    }
]`

When I remove it from the json and try to add it in the shortcut editor, I am still not able to enter CTRL+SHIFT+S. It enters CTRL+SHIFT and as when I press S, it ignores it and I only get the following output:
`[2022-08-23 13:00:31.273] [renderer1] [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.`

**Comment by alexdima** [comment]
Thank you for the extra information. It looks like `ctrl+shift+s` is not reaching VS Code, therefore it cannot be dispatched by us to execute `saveAll`. Usually this happens when the OS is configured to do something on that particular keybinding or when there is some other software installed on the machine which listens globally on that keybinding. Unfortunately, there is nothing we can do on our side.

**Comment by MarioF84** [comment]
You're right. I tested it in notepad++ and it didn't work there too.
This shortcut (and some more) have been blocked globally by AMD Software: Adrenalin Edition
I disabled the shortcuts there and now it works as expected.

Many thanks for your input, without I would not have solved it.
