### ISSUE TITLE
Don't *generate* the pair symbols when I am writing comments. 

### ISSUE THREAD

**Issue by QueenYoung** [Microsoft/vscode#15696]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.3.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.5|
|html-snippets|abusaidm|0.0.18|
|materialcolorsnippets|brunnerlivio|0.1.1|
|npm-intellisense|christian-kohler|0.1.4|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|code-runner|formulahendry|0.5.0|
|docthis|joelday|0.3.5|
|HTMLHint|mkaufman|0.0.3|
|Theme-MaterialKit|ms-vscode|0.1.1|
|atom-keybindings|ms-vscode|1.2.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|vscode-swift-language|rlovelett|0.0.5|
|vscode-icons|robertohuertasm|4.0.1|
|Spell|seanmcbreen|0.8.6|
|vim|vscodevim|0.4.2|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. open a .js file
2. write comments and use some symbols like `' ( { [`

**Comment by ramya-rao-a** [comment]
Am just curious... why not? Would there be a case where you open a bracket and do not want to close it?

**Comment by QueenYoung** [comment]
@ramya-rao-a I am not a professional writer, so I generally use `'` replacement `’`.
And I don't want to write something like `It's`when I have to delete another `'`.
If you can provide a *whitelist* for this feature, it might be better.🌚

**Comment by ramya-rao-a** [comment]
At the moment, you can add this to your settings:  `"editor.autoClosingBrackets": false`
this will disable the closing symbols for ' " [ { (

@alexandrudima Thoughts on adding a setting to disable these only in the comments section?

**Comment by QueenYoung** [comment]
Another point, the paired symbols should be able to delete together. I don't want press `Ctrl-K` anymore.
