### ISSUE TITLE
Powershell Terminal stops displaying command output

### ISSUE THREAD

**Issue by Fimlore** [microsoft/vscode#156972]
Hi All,

in VSCode, when I am developing a Powershell script, the first time the Terminal is connected etc, I get command output just fine.
However, as soon as I put the output of said command into a variable, and try to 'echo' the variable (by just referencing it) no output is shown. When I then run the command without putting it into a variable, no output is shown. When I put it in the terminal itself, no output is shown.. Untill I kill the terminal, reconnect with the sessions required and run the command again..

I hope the screenshot makes some sense, the red rectangle is the first two times I ran the script.
Blue rectangle is when I tried putting the output into a variable, and echoing said variable,
green rectangle is everything reverted -- still no output

![VSCodeBroken](https://user-images.githubusercontent.com/20944149/182548306-cab31cb6-eb30-4c03-8b36-7eb00829c377.png)

**Comment by Fimlore** [comment]
it appears to happen when I safe my script?

**Comment by meganrogge** [comment]
Are you using a powershell integrated console terminal or just `pwsh` ? 

Also, can you reproduce this in an external pwsh terminal?

**Comment by Fimlore** [comment]
I am using the Powershell Extension - I guess the issue is related to this more than to Visual Studio code?
