### ISSUE TITLE
add a smoke test for task run build and run test commands

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#156945]
Almost missed that the error thrown here would have been wrong bc there was no test for this
https://github.com/microsoft/vscode/pull/156634#discussion_r935095882

@alexr00 what is the idea behind the `workbench.action.tasks.test` command? I don't see it referenced anywhere for testing, so is it how you quickly/manually check things?

**Comment by alexr00** [comment]
Just as you can set a task to be a build task or a default build task, you can set a task to be a test task or a default test task. It's basically just a quick way to run test tasks, just as `workbench.action.tasks.build` is a quick way to run build tasks.
