### ISSUE TITLE
no vscode.workspace.onDidCreateFiles Event for Discard All Changes in Source Control 

### ISSUE THREAD

**Issue by AnWeber** [microsoft/vscode#156925]
- VS Code Version: 1.69.2
- OS Version: Win11

I want to use the event `vscode.workspace.onDidCreateFiles` to determine all newly created files. Unfortunately the `Discard All Changes` in Source Control View does not seem to trigger the event. Using `vscode.workspace.createFileSystemWatcher().onDidCreate` would work though.

Steps to Reproduce:

1. Create simple Extension
```ts
import * as vscode from 'vscode';

export function activate(context: vscode.ExtensionContext) {
	const outputChannel = vscode.window.createOutputChannel(`FileEvents Tester`);
        outputChannel.show(true);
	const fileSystemWatcher = vscode.workspace.createFileSystemWatcher("**/*.json");
	const log = (text: string) => {
		console.info(`[File Watcher Test] ${text}`);
		outputChannel.appendLine(text);
	};
	context.subscriptions.push(...[
		vscode.workspace.onDidCreateFiles(() => {
			log("onDidCreateFiles called");
		}),
		vscode.workspace.onDidDeleteFiles(() => {
			log("onDidDeleteFiles called");
		}),
		vscode.workspace.onDidRenameFiles(() => {
			log("onDidDeleteFiles called");
		}),
		fileSystemWatcher.onDidCreate(() => log("FileSystemWatcher onDidCreate called")),
		fileSystemWatcher.onDidDelete(() => log("FileSystemWatcher onDidDelete called")),
		fileSystemWatcher
	]);
}
```
2. start Debugging and open Workspace with Git Integration. 
3. delete a JSON File
4. restore JSON File in SourceControl View - `Discard All Changes`

![onDidCreateFiles](https://user-images.githubusercontent.com/13434739/182465027-3f4c1ef4-74ce-44e9-9e4b-fe61587009f9.gif)

**Comment by lszomoru** [comment]
@bpasero, would you be able to help triage this issue? Thank you!

**Comment by bpasero** [comment]
This issue could originate from a problem with file watching. Let me explain how file watching works in VSCode first and then provide some details how to get more logging data from how file watching behaves in your case.

**Synopsis**
VSCode has different strategies for file watching depending on your workspace and setup:
* no folder opened: files in opened editors are watched via node.js `fs.watch`
* folder opened: folder is watched recursively for all changes via [parcel](https://github.com/parcel-bundler/watcher), opened editors with files not within the folder are watched via node.js `fs.watch`

If you are connected to a remote (SSH, WSL, Docker), the file watcher will run within the target file system. As such, even though you maybe on Windows where VSCode runs, if the remote is Linux, the file watcher will run in the Linux environment.

**Platforms**
Depending on the platform you are on, file watching is differently implemented:
* macOS: using `fsevents` services
* Windows: using `ReadDirectoryChangesW` method
* Linux: using `inotify`

Specifically on Linux, watching a large folder recursively can result in VSCode consuming too many file handles. If that is the case, you will see a warning notification with instructions how to solve that.

**Limitations**
File watching comes with a set of limitations:
* symbolic links are not followed automatically but you can explicitly add symbolic links to be watched via the `files.watcherInclude` setting
* mapped network drives or third party file system drivers are not guaranteed to produce file events
* in general, the operating system may decide to drop file events at any time, there is no 100% guarantee

**Settings**
Please review your settings to see if maybe a folder is excluded by accident. Specifically, the `files.watcherExclude` setting is relevant.

**Logging (local)**
!!! This is ONLY when you open a local workspace, for remote see below !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the local workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `Help | Toggle Developer Tools`
* select `Console`
* filter the output by typing `File Watcher` into the filter box
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323290-f3ba6470-dfed-4066-a19c-951395611738.png)

**Logging (remote)**
!!! This is ONLY when you open a remote workspace (WSL, Docker, SSH), for local see above !!!
We provide logging for file events when you enable verbose logging. Steps are:
* open VSCode on the remote workspace that shows the issue
* select `View | Command Palette...`
* select `Developer - Set Log Level...`
* pick `Trace`
* select `View | Output`
* select `Log (Remote Server)` from the dropdown
* attach the output when doing the operation that exhibits the issue

![image](https://user-images.githubusercontent.com/900690/156323886-6b7dfa25-d6ac-4316-9150-80e5c8104d04.png)

**Comment by AnWeber** [comment]
@bpasero I was able to recreate the error both in my normal environment under WSL and just locally under Windows 11. I used this vsix extension ([filetester-0.0.2.zip](https://github.com/microsoft/vscode/files/9424741/filetester-0.0.2.zip)) and followed the steps as described. File Operation are the same as in the description (File delete and restore with git). I only added additional [File Watcher Test] console.info calls to get a log with both outputs (see updated code sample in description).

#### Settings
`files.watcherExclude` setting has this value.
```
  "files.watcherExclude": {
    "**/.git/objects/**": true,
    "**/node_modules/**": true
  },
```
I removed the setting and ran the test again.  However, nothing has changed.

#### Logging Local
- Win 11 Home (Version 22000)
- VSCode 1.70.2
- Open Folder
[win_only.txt](https://github.com/microsoft/vscode/files/9424763/win_only.txt)

#### Logging (remote)
- Win 11 Home (Version 22000)
- WSL Ubuntu 22.04.1 LTS
- VSCode 1.70.2
- Open Folder
[win_wsl.txt](https://github.com/microsoft/vscode/files/9424837/win_wsl.txt)

**Comment by bpasero** [comment]
I am a little bit confused, in the above gif you restore a `package.json` and I see output in the console, so where is the bug?

From the logs I also see `>> normalized [ADDED] c:\Users\Andreas\Desktop\httpyac.github.io\package.json`, so the file watcher seems to detect this.

**Comment by AnWeber** [comment]
I get in FileSystemWatcher also correctly the event only the `vscode.workspace.onDidCreateFiles` is not triggered.. I uploaded my test project to https://github.com/AnWeber/filetester. If I can provide any more logs or help, I'd be happy to.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/blob/150dbe4dd608ff3b987923c24f38ce9e5d8f97af/src/vscode-dts/vscode.d.ts#L12184-L12192

**Comment by bpasero** [comment]
This sounds as designed, even though you do a user gesture, this is not really going through any code of us.

**Comment by AnWeber** [comment]
Thank you for the explanation. At first it is surprising to me that `Discard All Files` is not interpreted as a user gesture, but that makes perfect sense. 
I thought `vscode.workspace.onDidCreateFiles` would be a resource saving alternative to monitor changes, but unfortunately this is very limited in this way and there is also the risk to fall into this trap ([same error in Jest Extension](https://github.com/jest-community/vscode-jest/blob/022a7f3fa7e37b4597beec182b1c84477cf6f061/src/extension.ts#L136)).
