### ISSUE TITLE
Missing "editor.action.toggleComment" feature

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#15694]
- VSCode Version:
- OS Version:

Steps to Reproduce:

Not possible to reproduce. VSCode simply doesn't have the feature.

Add a feature `Toggle line comment`, say as a `editor.action.toggleComment` option

`Ctrl+[some key]` comments or comments out a line
```
// email: 'foo@example.com',
email: 'foo@example.com',
```

**Comment by kaiwood** [comment]
`editor.action.commentLine` is a toggle.

**Comment by wzup** [comment]
@kaiwood 
Excellent! Exactly what I was searching for.

Also possible for block comments:
`editor.action.commentLine`
`editor.action.blockComment`
