### ISSUE TITLE
The rendering of mathematical formulas a little crowded

### ISSUE THREAD

**Issue by Vincent0706** [microsoft/vscode#156950]
I find the rendering of mathematical formulas seems a little crowded. I hope the row spacing can be bigger.

Katex code:
```
$$
  J=\dfrac{\partial(F,G)}{\partial(u,v)}=
  \left|
    \begin{matrix}
      \dfrac{\partial F}{\partial u} & \dfrac{\partial F}{\partial v} \\
      \dfrac{\partial G}{\partial u} & \dfrac{\partial G}{\partial v}
    \end{matrix}
  \right|
$$
```

Current display:
![image](https://user-images.githubusercontent.com/82581024/182508718-34164c1e-fc7d-4386-939c-88213ed66939.png)

Hope display (refer to the typora):
![image](https://user-images.githubusercontent.com/82581024/182508747-a5fa7ac1-0772-4eb9-b67a-687a6533ced6.png)

**Comment by mjbvz** [comment]
We use Katex for rendering so I believe this is https://github.com/KaTeX/KaTeX/issues/2031
