### ISSUE TITLE
Can't set installation path , which prevent me a fresh installlaion after remove drive which vscode installed.

### ISSUE THREAD

**Issue by eromoe** [microsoft/vscode#156976]
Steps to Reproduce:

1. remove `drive D:` from my PC,  which vscode installed
2. install vscode 
![image](https://user-images.githubusercontent.com/3938751/182552936-92c7fea2-8fcb-4039-97cc-deff42e2e255.png)

It thinks itself is in `drive D`  ,  and doesn't allow me choose installation path.

**Comment by joaomoreno** [comment]
Can you uninstall and reinstall VS Code?

**Comment by eromoe** [comment]
Yes,  I just report this issue ,  it shouldn't fail here .

**Comment by joaomoreno** [comment]
Can you translate the error message for me?

But in any case, if you install Code on a location and then remove that location from disk, there's not much we can do. You have to uninstall VS Code and then reinstall.

**Comment by eromoe** [comment]
I have save I remove `drive D: `   the hard disk from my PC,   installation / unstallation both  can't find the path !  unstall would alert same error .  

Usually , a installation program would auto choose the previous installation path , but allow you to choose a new path . 
Vscode doesn't , it force to install in previous path and you don't check existetng got this exception .

**Comment by joaomoreno** [comment]
> unstall would alert same error .

Can you show me uninstall alerting the same error? I'm curious because since the `D:` drive is removed, you shouldn't even have the uninstaller in disk... so, if you go into the Control Panel and try to uninstall VS Code, what error shows up?

**Comment by eromoe** [comment]
@joaomoreno I have reinstalled vscode after I post this issue .
Before remove `D:` ,  I moved vscode folder to another drive ,  either the uninstaller in moved folder or Control Panel  took effect. 
Sorry, I don't remember which worked and which failed with error above.

**Comment by joaomoreno** [comment]
Good to know you're unblocked. 👌
