### ISSUE TITLE
Sticky scroll header shows when the rest of the function is out of view

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#156999]
Repro:

Scroll to the bottom of a function such that 1/2 the `}` is in view

![image](https://user-images.githubusercontent.com/2193314/182598836-b03badc3-d345-4ee2-94a3-6b9a50f6ee46.png)

My expectation here is that the sticky header should stop on the line above the function's closing `}` (ie. on line 1072)

**Comment by gjsjohnmurray** [comment]
This makes sense for languages in which the end-of-scope line typically doesn't contain useful information (e.g. just a `}`). But there are likely to be languages in which this isn't the case, and I may not want to lost the header when on the last line.

**Comment by aiday-mar** [comment]
Currently the suggested idea by @Tyriar gives this.

![sticky-scroll](https://user-images.githubusercontent.com/61460952/182897938-a6cbae15-67f5-4715-9171-2f94589b569a.gif)

In this case at one point, the header disappears and we are left with a closing tag with no associated header.

**Comment by Tyriar** [comment]
I like it! It would need to play nice with Python that uses indentation based blocks is all

**Comment by alexdima** [comment]
@aiday-mar To tell languages similar to Python apart, there is a language configuration property used by folding called `foldingRanges.offSide`. [Here](https://github.com/microsoft/vscode/blob/73fd3f11032e7b83c2ae011b5516e6ddd19e3db2/src/vs/editor/contrib/folding/browser/indentRangeProvider.ts#L30-L31) is an example how you can read that. Languages like Python have this boolean set to true so you could use that to distinguish these cases.

**Comment by aiday-mar** [comment]
Test:

Open a file, enable sticky scroll and scroll down
Check that when you scroll down, the header disappears on the line before its enclosing tag
