### ISSUE TITLE
Terminal sizeToContentWidth not working for current line buffer

### ISSUE THREAD

**Issue by pingren** [microsoft/vscode#156971]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0-insider(e9bda7aa4ff76648cfccc1a7bde465443803da71)

- OS Version: macOS Monterey 12.3.1

#### Steps to Reproduce

1. Open a terminal, **type** to make the current line wrap.
2. Use `workbench.action.terminal.sizeToContentWidth` (Option + Z on macOS) to resize terminal column.
3. Nothing happens (however, if we're **pasting**  instead of **typing**, it will work).

#### Expected Results
Terminal resizes successfully.

![CleanShot 2022-08-03 at 14 41 25](https://user-images.githubusercontent.com/5123601/182542091-e654ae87-05c8-40bd-93c1-ab4f4da84872.gif)

**Comment by pingren** [comment]
I found `line.isWrapped` is `false` (expected `true` when typing a long line and wrap. Is it a xterm.js issue?
 https://github.com/microsoft/vscode/blob/bcfdcf57e3131dc728772251606e913d160ec8c0/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L363

**Comment by Tyriar** [comment]
I think this is actually by design because the shell input line isn't marking the line as wrapped
