### ISSUE TITLE
Missing directory in Web editor

### ISSUE THREAD

**Issue by andrewsgreene** [microsoft/vscode#156923]
Embedded vscode from github [project](https://github.com/defenseunicorns/zarf) is missing a directory, specifically 'packages' in this case. 

![image](https://user-images.githubusercontent.com/46836330/182462371-b09a3281-e116-4a4a-a5e1-6a9f147e29ba.png)
![image](https://user-images.githubusercontent.com/46836330/182462425-aad3e9f4-2de4-4181-a5db-2f9982a17552.png)

Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Embedder: github.dev

**Comment by joyceerhl** [comment]
Apologies for the delayed follow up. I suspect that there is some stale metadata here which is preventing github.dev from fetching the latest filesystem contents. Would you mind enabling debug logging with the following settings:

```
"remoteHub.logLevel": "debug",
"githubRepositories.logLevel": "debug"
```

and providing the full debug logs? Thank you!

**Comment by andrewsgreene** [comment]
Looks like the directory exists now in the editor, can't reproduce.
