### ISSUE TITLE
When double-clicking the mouse in the terminal to select, in the Chinese environment, the first word is ignored

### ISSUE THREAD

**Issue by seryte** [microsoft/vscode#156962]
Does this issue occur when all extensions are disabled?: Yes/No

版本: 1.69.2 (Universal)
提交: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
日期: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0
Steps to Reproduce:

1. Prerequisite: I have enabled the mouse selection and copy function in the terminal, and the right mouse button paste function
<img width="439" alt="image" src="https://user-images.githubusercontent.com/17977783/182525208-466fc14d-41a2-474a-9aaa-868cd32f7641.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/17977783/182525241-7b0af9db-50c7-4c35-ad06-08e4043a7497.png">

2.
When I double-click to select "我是一个中国人" and paste it, the word "我" is lost

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4001
