### ISSUE TITLE
Ability to "Lock" a Folder from Opening in the Explorer Tree View

### ISSUE THREAD

**Issue by skl131313** [Microsoft/vscode#15691]
I have a folder that has a lot of files in it, that are auto generated. Sometimes I need to go into the files, but not very often. When I do it is usually through a "goto definition" command or other method. When you open this file in the editor though, it automatically opens the tree view folder for where the file resides and goes to it. If it's It would be nice to have a feature where you can lock specific folders to stay closed instead of automatically opening and flooding the explorer view with all the files.

**Comment by bpasero** [comment]
You can always set `"explorer.autoReveal": false` to disable this globally.

**Comment by sprinkle131313** [comment]
It's a useful feature, just not when I open a file in a certain folder.
