### ISSUE TITLE
All open editors closes on File | Exit

### ISSUE THREAD

**Issue by hpephoto** [Microsoft/vscode#15699]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Enterprise v. 1511 build 10586.633

Steps to Reproduce:

1. Open a bunch of editors
2. File | exit on one of them and all of them closes

**Comment by bpasero** [comment]
@hpephoto that works as designed, what would you expect? There is a separate command to close a window.

**Comment by hpephoto** [comment]
Well, I did not expect  that all of my editors would close when I closed that one editor (with the Exit command).

No big deal, I use Ctrl + Shift + W from now on.

hp
