### ISSUE TITLE
"Open containing folder..." context menu option

### ISSUE THREAD

**Issue by wzup** [Microsoft/vscode#15693]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. In the code editor click left mouse button to open options menu (for left-handed mouse, don't know what vice-versa)
2. Observe missing `Open containing folder...` option

![vscode menu](https://cloud.githubusercontent.com/assets/3880497/20419517/07c2043c-ad92-11e6-98af-2a5a2da9ecad.png)

An example. Menu from ST3 or how it should be. Also other options would be very good to have:

![vscode menu st3 example](https://cloud.githubusercontent.com/assets/3880497/20419599/938e11e0-ad92-11e6-8e60-e28c6efbd8fc.png)

**Comment by ramya-rao-a** [comment]
You have both those options in the context menu in the explorer

![image](https://cloud.githubusercontent.com/assets/16890566/20440784/52b4b2da-ad76-11e6-9a07-0e4aafddcc16.png)

Having them again in the editor would be redundant.

**Comment by wzup** [comment]
Haha, very well. 

Now we have to:

1. Open explorer (nobody keeps it open all the time for sure)
2. Find that file in `OPEN EDITORS` sub list (might include scrolling and will take hefty number of seconds if one has many files open, which is almost always so).
3. Click left mouse button on the file to open a context menu.
4. Eventually select that `Reveal in Explorer` option. 

Veeery good UI and UX. You've just forced everybody to take 4 (four!) steps instead of loosely speaking only one.

I'm curious who's that genius UX designer who takes such mind-blowing brilliant decisions:
> _since that would be redundant we will force everybody waste their time taking four steps towards the goal instead of one_

👏👏👍

**Comment by ramya-rao-a** [comment]
Point taken

What do you feel about doing these actions via the command pallet or keyboard shortcuts?

![image](https://cloud.githubusercontent.com/assets/16890566/20449214/e1a5c422-ad9c-11e6-9a45-87f9ad54413e.png)

**Comment by ramya-rao-a** [comment]
![image](https://cloud.githubusercontent.com/assets/16890566/20449999/d8b68c20-ada1-11e6-9be9-2e1b8845b633.png)


This one (open in terminal) should open the folder containing current file, but doesn't. That's a bug, filed an issue for that

#15742
