### ISSUE TITLE
Can't debug failed tasks in terminals

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#156941]
- Something is wrong with my setup so the "Ensure prelaunch dependencies" task fails
- All I see is this:

<img width="494" alt="image" src="https://user-images.githubusercontent.com/323878/182486583-066f0264-6e6f-4da3-a171-a5e68e78efb5.png">

The task terminal was removed when the task finished. The terminal has all the useful error output in it. Can you leave the terminal open so I can see it?

**Comment by alexr00** [comment]
This task is configured to close the terminal when the task exits. You can set the `close` property on the task to `false` if you don't want it to close:

https://github.com/microsoft/vscode/blob/e8ee2cf78ffe38e878fc0faa652f9515502fe58c/.vscode/tasks.json#L214-L222

**Comment by roblourens** [comment]
Oh, that works for me, thanks
