### ISSUE TITLE
unable to verify the first certificate

### ISSUE THREAD

**Issue by hujin2016** [Microsoft/vscode#15690]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. 
2.

**Comment by ramya-rao-a** [comment]
@hujin2016 We need details to understand the issue you are facing.

**Comment by Kaldiris** [comment]
I have Same Problem...

**Comment by ramya-rao-a** [comment]
@Kaldiris Please elaborate

**Comment by jilaokang** [comment]
me too ! when i install extend , That's return a wrong sentence .
"unable to verify the first certificate"

**Comment by ramya-rao-a** [comment]
@jilaokang Do you mean when you install extension you are getting this error?

cc @joaomoreno

**Comment by jilaokang** [comment]
Thanks for your review !
Yes !
Now , I have to install extension with classmate's computer to download and put into my extension mkdir  . It could solve this question , but not convenient .

**Comment by jilaokang** [comment]
@ramya-rao-a  That is may the registry have problem in a named "porxy" .
Registry positon: [HKEY_CURRENT_USER/Software/Microsoft/Windows/CurrentVersion/Internet Settings] .
I don't have mind to solve .

**Comment by joaomoreno** [comment]
Fix will come in #22214

**Comment by jilaokang** [comment]
@joaomoreno 
Great！　Ｔｈａｎｋ　ｙｏｕ！

**Comment by FlorianLeitgeb** [comment]
Got the same problem with "Upsource for VSCode" extension when connecting to my reviews.
