### ISSUE TITLE
WCO buttons not aligned

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#157086]
I am running from Electron 19 branch, out of sources and see this:

<img width="425" alt="image" src="https://user-images.githubusercontent.com/900690/182831337-922edae7-e164-41f3-91fc-962117dcb82a.png">

Btw why is WCO disabled when running out of sources?

//cc @deepak1556

**Comment by sbatten** [comment]
WCO is disabled out of sources since you are likely to open dev tools and there is this issue https://github.com/electron/electron/issues/34129

**Comment by sbatten** [comment]
@deepak1556 looks to be on the electron side => 
<img width="181" alt="image" src="https://user-images.githubusercontent.com/6561887/182920768-b7816fdc-ca35-49f6-8adc-66dece5a67a9.png">

Yes we have a slight pixel buffer underneath the controls to account for window border, but even within the bounds of the controls, the restore down icon is quite off

**Comment by deepak1556** [comment]
Upstream issue https://github.com/electron/electron/issues/35038

**Comment by gjsjohnmurray** [comment]
> WCO is disabled out of sources since you are likely to open dev tools and there is this issue [electron/electron#34129](https://github.com/electron/electron/issues/34129)

@sbatten now that #161027 has merged can WCO be permitted when running out of sources?

**Comment by rzhao271** [comment]
There's still https://github.com/microsoft/vscode/issues/159813, but manually enabling the setting in Code-OSS should be fine.

**Comment by gjsjohnmurray** [comment]
@rzhao271 I tried enabling it in my Code-OSS settings but it didn't seem to work. The sentence from @sbatten that I quoted make me think it had been hardwired off in Code-OSS. I haven't searched the codebase yet though.

**Comment by rzhao271** [comment]
Verification steps:
1. Enable the WCO by enabling the `window.experimental.windowControlsOverlay.enabled` setting.
2. Restart VS Code when prompted and confirm that the restore button is aligned with the minimize and close buttons.
