### ISSUE TITLE
VSCode Workspace Markdown Preview Disappear

### ISSUE THREAD

**Issue by Anthonykung** [microsoft/vscode#157012]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.69.2
- OS Version: Windows x64 10.0.19044

Hello,

I'm having a strange issue as stated, the built in Markdown support for VSCode has disappeared from my VSCode Workspace. All the other workspace are unaffected, just this single workspace that is doing the strange thing.

What I did:

- Disabled certain extensions in Workspace only (nothing to the Global)
- Create Workspace specific extensions.json
- Use the `Disable All Installed Extensions for this Workspace` command
- Use the `Show Recommended Extensions` command
- Enabled recommended extensions in Workspace only (nothing to the Global)
- Tried to do `Ctrl`+`Shift`+`V` to bring up Markdown Preview
- Nothing happened and Markdown Preview disappear from Keybindings
- Tried reproducing the error by duplicating the folder and open a new Workspace
- **_Unable to reproduce error, neither reload nor restart help fixing the error_**

Bad Keybindings

![image](https://user-images.githubusercontent.com/33201499/182647701-767c9471-01e1-44d9-a723-72e15ec257b5.png)

Good Keybindings

![image](https://user-images.githubusercontent.com/33201499/182647761-84b9d6ec-c161-45b1-8ba6-b0cbb8ae26ae.png)

Does anyone know what's going on with this?

**Comment by mjbvz** [comment]
Have you disabled the built-in markdown extension (or is another extension disable it) ? Search `@builtin markdown` in the extensions view to check

**Comment by Anthonykung** [comment]
Oh yes, that was the cause of it, `vscode.markdown-language-features` was disabled by something. It is probably one of the extensions I installed but I just couldn't reproduce the issue no matter what I did.

Thank you so much for solving this mystery for me!
