### ISSUE TITLE
invoking code inside bash WSL results an extra cli.js

### ISSUE THREAD

**Issue by g0ld3lux** [Microsoft/vscode#15701]
- VSCode Version: 1.7.1
- OS Version: Windows 10 14965 

Steps to Reproduce:

Im Running code command inside bash without trouble...
But it always open extra cli.js everytime i open it On Windows 10 Bash.
I dont exprience anything Funky when i run code command in CMD terminal...

may i know how to fix this?

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/13138
