### ISSUE TITLE
Post commit does not work

### ISSUE THREAD

**Issue by ViniciusRed** [microsoft/vscode#157002]
Type: <b>Bug</b>

When I apply commit the post commit does not work
I already reinstalled Vscode Insiders and Git

VS Code version: Code - Insiders 1.70.0-insider (12b08be500f8a307f30e92cbc3ee39ba115eab69, 2022-07-29T10:47:14.408Z)
OS version: Windows_NT x64 6.3.9600
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Celeron(R) CPU  N3010  @ 1.04GHz (2 x 1040)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.42GB (1.10GB free)|
|Process Argv|--crash-reporter-id 5e0ae9ed-3fa0-4d50-825e-abdd137166db|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-pt-BR|MS-|1.70.8030907

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728

```

</details>

**Comment by schaumtier** [comment]
i also have the problem that push is no longer executed after commit. at first on my office computer with windows 10 (since a month ago) and now also on my private computer (with ubuntu linux).

my configured "Post Commit Command" is "push".

**Comment by Gregorek85** [comment]
👍
Type: Bug

After installing latest release VS Code no longer automatically sync my repositories after successfull commits, despite that being set in settings.

Expected: VS Code does what it is suppossed to do do after successfull commits.

VS Code version: Code 1.70.0 (https://github.com/microsoft/vscode/commit/da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19044

**Comment by lszomoru** [comment]
Apologies for the inconvenience. 

This issue has been fixed in the latest Insiders release:
```
Version: 1.71.0-insider
Commit: fe946068ba8ed2c4db200483dbec89210fea1332
Date: 2022-08-09T09:41:36.494Z
```

We are also planning on including the fix in the recovery release planned for later this week.

**Comment by lszomoru** [comment]
The fix has been checked in to the release branch and should be included in the upcoming recovery release.

**Comment by schaumtier** [comment]
@lszomoru i can use "command + enter" in the source control view and it works now
![image](https://user-images.githubusercontent.com/10027198/183663384-46928137-e363-4c12-89a9-1c7acdd352fe.png)


but it doesn't work if i use the command palette with "Git: Commit All"
![image](https://user-images.githubusercontent.com/10027198/183663482-494ca46f-f2b6-4487-acdb-4f2d465fb387.png)

previously it worked also by using the command palette...

**Comment by lszomoru** [comment]
@schaumtier, I have filed https://github.com/microsoft/vscode/issues/157644 to track the problem with the command.

**Comment by schaumtier** [comment]
> @schaumtier, I have filed #157644 to track the problem with the command.

thank you!

**Comment by lszomoru** [comment]
To verify:

1. Set git.postCommitCommand to push or sync
2. Make a change to one or more files
3. Type in a commit message
4. Hit Command + Enter

Before this fix, Command + Enter would only commit but not honour the post commit command setting
