### ISSUE TITLE
It is invalid to pass args for Command variables in "tasks.json"

### ISSUE THREAD

**Issue by KeJunMao** [microsoft/vscode#157082]
- VS Code Version: 1.69.2
- OS Version: Windows_NTx64 10.0.19044

Steps to Reproduce:

1. create a task in `task.json`
```json
{
  "tasks": [
    {
      "label": "Before Debug",
      "type": "npm",
      "script": "dev",
      "isBackground": true,
      "problemMatcher": {...},
    },
    {
      "label": "After Debug",
      "command": "${command:workbench.action.tasks.terminate}",
      "args": ["terminateAll"]
    }
  ]
}
```
2. run Before Debug
3. run After Debug, but it's only show pick
4. and try to set args to string:
```json
    {
      "label": "After Debug",
      "command": "${command:workbench.action.tasks.terminate}",
      "args": "terminateAll"
    }
```
5. it's only show pick again

I'm find source code, it like a string `"terminateAll"`, How should I set `args`?

https://github.com/microsoft/vscode/blob/9f8e6e9a51c36f5d01a40293b018369c9169efac/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L3064-L3067

Forgive my English.

**Comment by meganrogge** [comment]
This works for me

```
	{
		"key": "ctrl+3",
		"command": "workbench.action.tasks.terminate",
		"args": "terminateAll"
	}
```

**Comment by KeJunMao** [comment]
@meganrogge hi, i'm try aging.
it not work for me
<img width="655" alt="ch07_2022-09-25 02 29 25" src="https://user-images.githubusercontent.com/18414281/192113336-86eba296-58ef-4e17-af29-8eb45294ad36.png">
