### ISSUE TITLE
Supporting syncing specific extension installed version 

### ISSUE THREAD

**Issue by WeslyG** [microsoft/vscode#157079]
Some extensions change the distribution model over time (Database Client) or have a license for a while (quokka/wallaby) or may simply break on the current vscode version. 
Because of this, we are installing a separate Extension version. However, coming in the morning I see that all my extensions are again the latest version. 
I don't want to completely disable extensions using `extensions.autoCheckUpdates` because my other extensions work fine and I don't want to switch to manually updating all extensions. 

Maybe it's worth setting up exceptions from auto-updating extensions? And even better, look at which extension differs from the latest version, and do not update it automatically at all.

**Comment by gjsjohnmurray** [comment]
According to #73766, after you use the "Install Another Version..." option on an extension's gearwheel menu to install a version earlier than the latest release, it shouldn't autoupdate.

**Comment by WeslyG** [comment]
In my case, I wanted the Quokka extension version.js was 1.0.469 I installed it and then got a new one every day. Today I went into the vscode sync files, and saw extensions in the files.json 496 (not 469) version. I reinstalled the extension of the desired version, and tried to force sync settings, expecting to see that the extension version will change during synchronization. However, everything remained as before. The sync files contain the latest version of the extension for today. That's probably why I get it over and over again.

extentions.json
```json
....
	{
		"identifier": {
			"id": "wallabyjs.quokka-vscode",
			"uuid": "aae0701b-111f-49c1-9000-ooooooooo"
		},
		"preRelease": false,
		"version": "1.0.496",
		"installed": true,
		"state": {
....
```
Unfortunately, I haven't found a way to change this extensions file.json I tried to enable and disable synchronization of both a specific package and all extensions, but this did not create a new file, even with forced synchronization.

It seems the extension will update again soon...

**Comment by WeslyG** [comment]
Only on one. I expected my new changes to be delivered to the rest of the computers. I can try to do it synchronously on all my devices if it will make a difference.

**Comment by gjsjohnmurray** [comment]
Let's see what @sandy081 says.

**Comment by Interesting6** [comment]
> Let's see what @sandy081 says.

I still don't understand how to solve it.

**Comment by sandy081** [comment]
Fixed by https://github.com/microsoft/vscode/pull/171325
