### ISSUE TITLE
Extension-contributed file systems can't show File Modified Since error on Save

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#157024]
The built in file: URI has this error when the mtime of the file has changed unexpectedly:

`throw new FileOperationError(localize('fileModifiedError', "File Modified Since"), FileOperationResult.FILE_MODIFIED_SINCE, options);`

Which displays:

``Failed to save '{0}': The content of the file is newer. Please compare your version with the file contents or overwrite the content of the file with your changes. [Compare] [Overwrite]``

But, there is no way for an extension to create this error.

Extensions can only create a couple of errors which are listed here-

https://github.com/microsoft/vscode/blob/61e8687fa3ee8e4d90ff8254d39e6fc167945728/src/vs/workbench/api/common/extHostFileSystemConsumer.ts#L154-L163

https://github.com/microsoft/vscode/blob/61e8687fa3ee8e4d90ff8254d39e6fc167945728/src/vs/platform/files/common/files.ts#L582-L593

**Comment by r3m0t** [comment]
I realise this might be considered pretty obscure by VS Code team, so would you accept PRs?

**Comment by tanhakabir** [comment]
Feel free to create a PR if you're interested in doing so! We'll review it when we get a chance to :)

**Comment by bpasero** [comment]
I do not understand the ask here, the error is not meant to be thrown by anyone, the error is created from the file service when the `mtime` advanced after the editor was opened to prevent dirty overwrites.

**Comment by r3m0t** [comment]
Ah thanks @bpasero , my `stat` wasn't implemented correctly, and my backend has an atomic check-and-write (like HTTP `PUT If-None-Match`) so I thought it should raise the error from `writeFile`. I'll try making `stat` contact the server every time.
