### ISSUE TITLE
[Enhancement] Improve git status of symlinks

### ISSUE THREAD

**Issue by jnooree** [microsoft/vscode#157078]
## Feature description

If a symlink is opened, show the git status of the symlink's target instead of itself.

## Rationale

Currently, the git status of symlinks is displayed as if the link is a regular file at the path of itself.

<img width="704" alt="status of symlink" src="https://user-images.githubusercontent.com/63093572/182796663-928766a0-a154-4d28-9f26-6f51899c8f3c.png">

However, it is much more desirable to show the target file's status:

<img width="697" alt="status of target" src="https://user-images.githubusercontent.com/63093572/182796730-fd7887af-45d7-408c-9f19-b4eab946b034.png">

**Comment by lszomoru** [comment]
Adding symlink support is currently tracked with https://github.com/microsoft/vscode/issues/5970. Closing this issue as duplicate.
