### ISSUE TITLE
Document new color keys

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#157069]
"`editorStickyScroll.background`: Sticky scroll background color for the editor"
"`editorStickyScrollHover.background`: Sticky scroll on hover background color for the editor"

See https://github.com/microsoft/vscode-docs/pull/5515 for example

**Comment by aiday-mar** [comment]
Ah yes, sorry I just saw your other comment in the July 2022 Endgame plan. I'll get down to it.

**Comment by bpasero** [comment]
Thanks!
