### ISSUE TITLE
Let me ctrl/cmd+click symbols in the sticky header

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157055]
One of the first things I tried to do was ctrl+click an interface in the sticky header, but it just takes you to the header line like a regular click

**Comment by jrieken** [comment]
To verify

* have sticky scroll lines that show return types, extends or implements causes, arguments types etc
* ctrl/cmd hover over them and make sure valid targets turn into links
* make sure clicking them reveals respective target

**Comment by Tyriar** [comment]
Unexpected behavior here:

It seems to be scrolling to the right spot but the peek view is partially out of view:

![Recording 2022-08-22 at 11 36 02](https://user-images.githubusercontent.com/2193314/185994266-86f83a48-a586-48f3-86f6-daaa3738a418.gif)


The file https://github.com/xtermjs/xterm.js/blob/master/src/browser/Clipboard.ts

**Comment by jrieken** [comment]
__

**Comment by jrieken** [comment]
@Tyriar please file separate issues
