### ISSUE TITLE
Allow `TextMate` to set rule priority

### ISSUE THREAD

**Issue by A-kirami** [microsoft/vscode#157087]
Hi, I am using `Ayu mirage bordered` in the `Ayu` theme.

In Python, colors of constants are inconsistent.

![image](https://user-images.githubusercontent.com/66513481/182838780-f3b6934b-bed6-4fee-aa18-59dfeda82139.png)

So I tried to customize the settings, but it is overwritten by the theme.

![image](https://user-images.githubusercontent.com/66513481/182839304-599565b1-016d-4f92-91e0-39b39e08eb81.png)

![image](https://user-images.githubusercontent.com/66513481/182839486-7dafb072-c2b4-4027-ae23-995f0a0cfa03.png)

Can we set priority for rules?

**Comment by RedCMD** [comment]
Currently Semantic highlighting (which is done by the extensions language server) overwrites TextMates highlighting

**Comment by aeschli** [comment]
You can customize the semantic highlighting like that:
```json
	"editor.semanticTokenColorCustomizations": {
		"[Ayu Mirage Bordered]": {
			"rules": {
				"veriable.readonly": "#95E6CD"
			}
		}
	}
```
You can also turn off semantic highlighting for a theme:
```json
	"editor.semanticTokenColorCustomizations": {
		"[Ayu Mirage Bordered]": {
			"enabled": false
		}
	}
```

We have no plans for TextMate/Semantic highlighting priority settings
