### ISSUE TITLE
Multiple of the same sticky header appeared

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157054]
No repro, I just switched back to this editor that I opened in a different session and this is what I saw:

<img width="828" alt="Screen Shot 2022-08-03 at 7 02 47 pm" src="https://user-images.githubusercontent.com/2193314/182747063-2056b471-ecb4-4f93-9797-ab9a5a464fa9.png">

Version: 1.70.0-insider
Commit: a7cb6851ea2fe94740fea17c9acb6f4c612e8026
Date: 2022-08-03T16:53:11.332Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

**Comment by Tyriar** [comment]
It kept happening, even after closing and reopening the file

![Recording 2022-08-03 at 19 05 34](https://user-images.githubusercontent.com/2193314/182747325-7631b10d-ed04-4c39-8bde-ece0d29aa78f.gif)

**Comment by aiday-mar** [comment]
Thanks for the bug, I'll look into it

**Comment by Tyriar** [comment]
First thing today 🤯 

![image](https://user-images.githubusercontent.com/2193314/182843485-12ef65a7-4ea0-4086-b1c3-326464a49b56.png)

**Comment by aiday-mar** [comment]
Hi Daniel, thank you for the communicating the bug. I had meetings today so only got down to working on it now. It seems like my changes from yesterday may have caused this. I have created a new pull request referencing this issue, which should solve this unexpected behavior.
