### ISSUE TITLE
Terminal error when starting VS Code from zip on Windows

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#157083]
1. Download zip of VS Code 1.70 to your Downloads folder on Windows.
2. Unzip into the default location (Downloads folder) and run Code.exe
3. See the following error in the terminal:
```
.: File C:\Users\alros\Downloads\VSCode-win32-x64-1.70.0\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1 canno
t be loaded. The file C:\Users\alros\Downloads\VSCode-win32-x64-1.70.0\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegra
tion.ps1 is not digitally signed. You cannot run this script on the current system. For more information about running scripts and setting execut
ion policy, see about_Execution_Policies at https://go.microsoft.com/fwlink/?LinkID=135170.
```
![image](https://user-images.githubusercontent.com/38270282/182823540-0b294dde-8148-4695-97d4-1f2e1687ccd8.png)

**Comment by Tender-hjd** [comment]
Me, too...

**Comment by Tender-hjd** [comment]
- They seem to have forgotten to sign a new ps1 script added in this version update, which beautifies the integrated terminal. 
- You have to modify the 'ExecutionPolicy' from 'RemoteSigned' to 'Bypass' if you don't want to see this error message.
    - The powershell code is `Set-ExecutionPolicy Bypass`

**Comment by Tyriar** [comment]
@TylerLeonhardt any idea how to sign the file properly? It's included in our signing job but `Get-AuthenticodeSignature` results in:

![image](https://user-images.githubusercontent.com/2193314/183093487-06c77422-6c9c-4bf1-9b2c-55e61b80b173.png)

This issue only affects the zip install as it's treated as a potentially unsafe file downloaded from the internet. In the meantime I'm going to add a try catch which is good to have anyway.
