### ISSUE TITLE
Add custom mark API

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#157026]
Requested by @connor4312 for testing purposes, we want to support registering a custom mark like:

```
ITerminalInstance.scrollToMark(begins: string, ends: string, highlight?: boolean)
```

with the sequence:
```
OSC 633 ; SetMark ; Id=? ; Visibility=?
```

We'll also need some API from terminal contrib for getting shell integration sequences.

**Comment by Tyriar** [comment]
@connor4312 FYI this is ready to use, there's this new `ITerminalInstance` API:

https://github.com/microsoft/vscode/blob/e73cd82227fe1c468dd4ccd9df91b6df86dced69/src/vs/workbench/contrib/terminal/browser/terminal.ts#L666-L673

Which you can use the scroll to marks with ID as set by `OSC 633 ; SetMark [; Id=?] [; Hidden] ST`, for example: `\x1b]633;SetMark;Id=test1start;Hidden\x07`

Can you link the testing issue that will use this if it exists?

**Comment by meganrogge** [comment]
@connor4312 can you pls verify this?

**Comment by connor4312** [comment]
Seems to work well in my provisional testing 🙂
