### ISSUE TITLE
Bad line number margin in diff editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#15707]
The line number gutter seems to have been squeezed out of any padding it had. IMO the line number gutter shouldn't look any different than from a regular editor.

![image](https://cloud.githubusercontent.com/assets/22350/20423704/2f1a8b3c-ad72-11e6-991e-96c9829b98a5.png)

**Comment by alexandrudima** [comment]
Same root cause as #15704 (glyph margin was disabled in the diff editor)
