### ISSUE TITLE
Installation is corrupted

### ISSUE THREAD

**Issue by benqcc** [Microsoft/vscode#15703]
- VSCode Version: Code 1.7.1 **[Unsupported]** (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-eslint|dbaeumer|1.1.0|
|python|donjayamanne|0.5.2|
|EditorConfig|EditorConfig|0.3.4|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|java|redhat|0.0.6|
|vscode-icons|robertohuertasm|4.0.1|
|background|shalldie|1.1.7|
|go|TwentyChung|0.0.1|

---

Steps to Reproduce:

1.
2.

**Comment by ramya-rao-a** [comment]
@benqcc We would need more details

**Comment by jrieken** [comment]
Will reopen when steps are provided
