### ISSUE TITLE
Highlight unused symbols

### ISSUE THREAD

**Issue by mindplay-dk** [Microsoft/vscode#15710]
I'd like to request an improvement to Typescript support: highlighting of unused symbols.

Refactoring and moving things around between files often leads to a lot of manual analysis, for example to find imports that are no longer in use.

This doesn't need to be a big, complex feature - I don't expect this to trawl through the entire codebase and figure out what is or isn't in use.

I'd be happy with just file-local highlighting - e.g. gray out variable and constant declarations if they aren't exported or used in any expression or statement anywhere in the file.

**Comment by mindplay-dk** [comment]
If possible, in addition, a right-click option to clean up unused symbols would be useful :-)

**Comment by waderyan** [comment]
Thank you for your feature request! We have discussed this internally and have considered adding it soon.

**Comment by jschlieber** [comment]
Webstorm has it and it is really really handy! Would love to have it in VSCode for TypeScript and JavaScript.

**Comment by mjbvz** [comment]
Related API request #20219

**Comment by mjbvz** [comment]
#23805 Notes that we could also investigating graying out unreachable code

**Comment by PDS42** [comment]
Sorry if that's not the right place to ask this, but is this being implemented anytime soon? It would be a huge improvement IMO. This is the only reason that makes me consider switching to WebStorm, though I really enjoy VS!

**Comment by mindplay-dk** [comment]
Storm is generally awful at Typescript, but yes, I occasionally find myself opening Storm just to check for unused symbols. Would be great to have this.

**Comment by cute-angelia** [comment]
today one unused variables make me error, i hope vs can support it

**Comment by justnewbee** [comment]
i'm reading through this issue for i want this too, please make it happen.
and also, highlighting exports that are not referenced anywhere in the project would be much better

**Comment by WeiGrand** [comment]
I think i could get rid of Storm with this feature~

**Comment by demisx** [comment]
Would love this feature as well. A major hiccup in refactoring that forces me to switch to WebStorm to run these checks. I'd rather stay in VS Code the entire time. Please, please, make this happen.

**Comment by Zephir77167** [comment]
I am also using Webstorm just for this feature. Would make switching a breeze! Thanks for the work put into VSCode

**Comment by Ccz-Chen** [comment]
Two of our projects in JavaScript. I am interested in the feature. Thanks,

**Comment by kubante** [comment]
+1

**Comment by sshmyg** [comment]
+1

**Comment by janakact** [comment]
+1

**Comment by PDS42** [comment]
If you guys could just use thumbs up emojis instead of flooding issues with `+1`, my inbox and I 
 would be super grateful.

**Comment by jcezarms** [comment]
Would like to add my support to this feature. To some developers, it is not particularly a personal preference, but a requirement coming from the enterprise Quality Gates, that may detect and reject code containing unused variables (my current scenario).

**Comment by gharibi** [comment]
I will surely get rid of WebStorm as soon as this gets implemented!

**Comment by vlodko** [comment]
@here to everyone who is using VS Code for TypeScript development.
Put this two properties to`tsconfig.json` in `compilerOptions` section:
```
{
  "compilerOptions": {
    "noUnusedLocals": true,
    "noUnusedParameters": true,
....
```
It will highlight the variable or class member with green curly line (at least it looks like that with my color theme):
![image](https://user-images.githubusercontent.com/2395824/36510172-6619755e-171f-11e8-9a5e-781a748182bb.png)

Also in Problems panel you will see a warning:
![image](https://user-images.githubusercontent.com/2395824/36510278-b2194dda-171f-11e8-81c7-65a317f70fac.png)

Read more about compiler options [here](https://www.typescriptlang.org/docs/handbook/compiler-options.html)

**Comment by erezLieberman** [comment]
+1

**Comment by dominique-mueller** [comment]
Hey to all, look what I've found a few days ago: This _awesome_ extension not only allows to remove unused imports, but - following my feature request - now also highlights them: **[TypeScript / JavaScript Deporter](https://marketplace.visualstudio.com/items?itemName=Acr0most.ts-deporter#overview)**.

The visuals could use some improvements, but overall it it works like a charm in my projects!

**Comment by dominique-mueller** [comment]
Also: https://twitter.com/mattbierner/status/976548673457856512?s=19

**Comment by mjbvz** [comment]
Depends on https://github.com/Microsoft/TypeScript/pull/22361

[As already noted](https://github.com/Microsoft/vscode/issues/15710#issuecomment-367508529), you an already enable using settings in your `jsconfig` / `tsconfig`. This issue specifically is now tracking:

- Allowing this you to see unused symbols even when you don't have a `jsconfig` or `tsconfig` and have not configured these settings
 
- Possibly presenting unused symbols in a different way. Graying out these symbols is one idea

**Comment by andy-ms** [comment]
There's now a `...` under unused symbols. Graying out might be a good idea though.
@mjbvz I notice that some unused diagnostics are red and others are green. The diagnostics should all have `reportsUnnecessary`, so if you are still matching against a list of error codes, I would change to using that property instead.

![green_red](https://user-images.githubusercontent.com/19274678/39841549-f914f266-5397-11e8-88ea-1c877fbae7f8.jpg)

**Comment by Zx-EvM** [comment]
Is this works only for JavaScript and TypeScript?

**Comment by andy-ms** [comment]
@Zx-EvM Just JS/TS, maybe you should open an issue with a language plugin that you think should support this too. But it would be a lot of work if that language doesn't support unused variables yet; for this issue TypeScript already supported detecting unused variables and all we had to do was send that info to the editor.
