### ISSUE TITLE
Invalid js formatting

### ISSUE THREAD

**Issue by moritz-t-w** [microsoft/vscode#157146]
[`??`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) becomes `? ?`, which is not valid.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
> 1.69.2
3b889b090b5ad5793f524b5d1d39fda662b96a2a
x64
- OS Version:
Windows 10
Steps to Reproduce:

1. type some js that includes the Nullish coalescing operator (`??`)
2. select `Format Document` from command pallete

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by moritz-t-w** [comment]
weird, I had went through 2 suspect extensions and it was none of them, I tried it with all disabled and turns out it must have been some other extension. Thanks
