### ISSUE TITLE
If a file is already open in a tab, don't open it again when clicking the file explorer

### ISSUE THREAD

**Issue by userpixel** [Microsoft/vscode#1571]
This is a UX issue but let's say I have two files open and my cursor is on the right tab:

```
+-------------------------+
|   File 1   |  *File 2   |
+-------------------------+
```

if I click on `File 1` in the file explorer, I end up with something like this:

```
+-------------------------+
|   File 1   |  *File 1   |
+-------------------------+
```

This is probably useful in some scenarios but most often it's not. Then I have to click on top of the tab and select the `File 2` manually to end up with what I had before.

I suggest that if a file is already open in a tab, you don't load it in the active tab but simply change the active tab to the file that is open:

```
+-------------------------+
|  *File 1   |   File 2   |
+-------------------------+
```

**Comment by bpasero** [comment]
We decided to not do this due to UX concerns where for a user it might seem unpredictable that sometimes the file is replaced and sometimes not. The current behaviour is more consistent at the cost of having to manage more things.

@stevencl fyi

**Comment by jayrosen1576** [comment]
> This is a UX issue but let's say I have two files open and my cursor is on the right **_tab_**:

Wait! Tabs? What!? Where?

just kidding...

**Comment by ianwesterfield** [comment]
@bpasero I agree, I vote for the current behavior. When I have split view and I activate one of them, I expect my selection in the tree view to open there. Not to say I've never accidentally opened the same file a few times now, but I don't think I would change it.

**Comment by userpixel** [comment]
if refocusing on the active tab (read "pane" or whatever the technical term is in VSC) can be indicated with a flash, I'd be glad. 

PS. I am a UX designer for what it's worth ;-)

**Comment by bpasero** [comment]
I am closing this, we choose consistent behaviour over too much smartness.
