### ISSUE TITLE
Git: error on startup (ENOENT, no such file or directory, scandir)

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15714]
- VSCode Version: latest insider
- OS Version: Windows 2012 inside a VM

Steps to Reproduce:

1. download insider
2. just start it

=> you get an error right away showing up that %APPLICATIONDATA%\GitHub cannot be found
=> seems to be originating from https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/git/electron-browser/electronGitService.ts#L96

**Comment by joaomoreno** [comment]
Great catch!
