### ISSUE TITLE
Timeline usability issues

### ISSUE THREAD

**Issue by JamesHutchisonCarta** [microsoft/vscode#157168]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: MacOS 12.3.1

Steps to Reproduce:

1. Make a change to a git committed file
2. Save

Here's the issues:
- `File Saved` history records seem to not function when using `select for compare` with a git entry. There is no UI feedback to indicate this shouldn't work. Effectively, `File Saved` and git entries cannot be compared.
- There is no UI feedback to indicate what record is selected for compare, making things very confusing
- In `File Saved` entries, there is `Compare with File`, but it's missing for git entries, meaning there's no easy way to copy in changes in the diff like you can in source control under changes
- `Compare with File` is an ambiguous, vague, name. It seems it compares with the file's (possibly unsaved) state in the window.
- `Compare with previous` on the first file save entry just shows a read-only view of the first save (only one pane), which is not helpful.
- `Compare with previous` only works if you left-click on a row first, and then select `Compare with previous`. it seems it always does the same comparison, and that comparison is based on the selected row and not the one you right-clicked on.
- The single click behavior is inconsistent. For git files, it does the `Compare with File` behavior. For Git, it does `Open Changes` which is equivalent to `Compare with Previous` with the file history

**Comment by bpasero** [comment]
Thanks for the feedback, please open 1 issue per issue. See also our issue reporting guidelines: https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions#writing-good-bug-reports-and-feature-requests

**Comment by JamesHutchisonCarta** [comment]
Thanks, I feel like I've enough time figuring out how the Timeline works, and also feel pretty strongly that someone should just use it and ask themselves if it's working like one would expect, regardless of how many little changes it takes to get there. As such, I'll leave that up to someone else, if they wish to break apart this ticket. Thanks!

**Comment by bpasero** [comment]
You have spend valuable time on figuring out all these issues and now you are not able to create individual issues out of it? Do you need help with it, I would not mind doing it, but feel its better you do it to have some tracability when issues get resolved or closed?
