### ISSUE TITLE
Sticky scroll: support relative line number 

### ISSUE THREAD

**Issue by RoRep1ay** [microsoft/vscode#157196]
Currently, the sticky scroll only supports `absolute` line number. Would be nice to support `relative` number as well. 
(Probably this setting should be in respect to `editor.lineNumbers` setting)

<img width="846" alt="image" src="https://user-images.githubusercontent.com/37890287/182989136-3bc7627a-7ced-4940-950a-966457313919.png">

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/pull/156992
