### ISSUE TITLE
"Open Folder..." in Windows 11 unexpectedly opens a File Explorer

### ISSUE THREAD

**Issue by tjprescott** [microsoft/vscode#157139]
1. Select "Open Folder..." from the File Menu
2. Windows opens a File Explorer instead of a dialouge to choose a folder.

Instead I have to navigate in the File Explorer to some folder and then right-click, choose "Show More Options" and then select "Open With Code". I did not used to have to do this and it's really annoying. I'm not sure if its a Windows 11 thing or something I have set wrong in my configuration. I tried removing and reinstalling VSCode and it still does the same thing.

**Comment by tjprescott** [comment]
Nevermind. It turns out the "Open Folder" dialogue on Windows 11 looks exactly like a File Explorer. Closing.

**Comment by gjsjohnmurray** [comment]
You might want to subscribe to #127365
