### ISSUE TITLE
Revealing in editor is not aware of sticky lines

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157175]
It should be either disabled or maybe better have very limited context (a single line max?)

Find references:

<img width="907" alt="Screen Shot 2022-08-04 at 5 01 05 pm" src="https://user-images.githubusercontent.com/2193314/182974887-7a55cf6c-3620-4782-bf56-8dd4e0e8f7e4.png">

**Comment by alexdima** [comment]
This is a general problem with revealing ranges in the editor. The code that reveals ranges is not aware of the sticky scroll sitting at the top of the viewport and doesn't scroll sufficiently.

In the original screenshot, I also noticed that line 153 is repeated 3 times, I think that is already solved on `main` via 2ecea7fa70b94d44b8bd2bf9b5b25c00f213bc53
