### ISSUE TITLE
activeDebugSession still defined when onDidTerminateDebugSession invoked

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode#157144]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.70.0-insider
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. This only repros in code-insiders on Ubuntu, starting between July 7th - 11th. Not sure about the exact date but this has been reproing consistently since then, and never reproed on Windows.
2. In an extension, write something like this:
    ```ts
    sub = vscode.debug.onDidTerminateDebugSession(() => {
        if (!vscode.debug.activeDebugSession) { // <- Break here
            ...
        }
    });
    ```
3. Start debugging and then stop debugging, observe that, when the breakpoint hits, activeDebugSession is still defined.

**Comment by weinand** [comment]
I'm not aware of any changes in that area but most likely the expected previous behavior was only working by accident.

**Comment by xisui-MSFT** [comment]
@weinand I don't think this is accidental, since it worked before, and it's still working on windows and in non-insiders version.

**Comment by xisui-MSFT** [comment]
Also - if this is accidental, on*Did*TerminateDebugSession seems to be a bad name... And how do we get notified on ALL debug sessions terminated? I.e., if activeDebugSession is not guaranteed to be undefined when all debug sessions terminate, is there a way to decide if it's one of the debug sessions terminated or all?

**Comment by xisui-MSFT** [comment]
@weinand Looks like the active session should be changed after the event is fired? https://github.com/microsoft/vscode/blob/cebad239e88e15b3738844e77cf26955d6b4d1a7/src/vs/workbench/contrib/debug/browser/debugService.ts#L675-L681

Or did I miss anything? Is activeDebugSession changed anywhere else on session termination? We have been depending on active session being undefined in onDidTerminateDebugSession for the past 3 years and didn't see any issues...

If this is the order by design, can we ask changing it, since looks like it has been behaved in the reverse order in the past?

**Comment by weinand** [comment]
@xisui-MSFT you said:
> We have been depending on active session being undefined in onDidTerminateDebugSession for the past 3 years and didn't see any issues...

Just to be clear: you cannot rely on the "active session being undefined in onDidTerminateDebugSession" because the **terminated** session is not necessarily the **active** session.
If the active session is different from the terminated session, then the active session will not change.

In addition, be aware that the active session reflects the user's notion of "activate session". Since the user can switch to another session at any time, you cannot rely on "active session being undefined" at any point in time.

However, I agree that it makes sense that the "active session" should never point to a "terminated session".

**Comment by xisui-MSFT** [comment]
> Just to be clear: you cannot rely on the "active session being undefined in onDidTerminateDebugSession" because the terminated session in an onDidTerminateDebugSession handler is not necessarily the active session.

No, we use this to decide if ALL debug sessions terminate.

I guess we can add a counter for debug sessions or just listen to active sessions and check undefined, but since this (on terminate + active sessions check) has been working for us for the past 3 years on all platforms, I'm expecting this continue to work.

**Comment by weinand** [comment]
If the user has another unrelated but long running debug session running, `activeDebugSession` might never transition to "untitled". So yes, tracking (or counting) the debug sessions you are interested in with ´onDidStartDebugSession´ and ´onDidTerminateDebugSession´ is the suggested approach.
 
@roblourens @connor4312 are you aware of any changes in the area of "active debug session management" that could explain the different behavior?

**Comment by roblourens** [comment]
No. I see this happening on Mac. I agree that given the names of the events, we should fire the terminate event after fixing the active debug session, but I'm pretty confident that this isn't new, I can repro in 1.67. You are pointing at the right code, and nothing around there has changed recently. Would take a PR though.

If you are debugging js, the event is fired twice because js-debug actually has two sessions. It seems like sometimes on the second instance, activeDebugSession has gone to undefined. That just seems to be random timing or maybe the ordering of the two sessions' terminated events can change.

**Comment by xisui-MSFT** [comment]
> If you are debugging js, the event is fired twice because js-debug actually has two sessions. It seems like sometimes on the second instance, activeDebugSession has gone to undefined. That just seems to be random timing or maybe the ordering of the two sessions' terminated events can change.

I'm debugging C/C++, which should only have one debug session (if VS Code doesn't create 2 internally). I'll try to change the order and see if that makes any difference. Thanks!

**Comment by weinand** [comment]
@xisui-MSFT you said:
> "I'm debugging C/C++, which should only have one debug session"

Please don't assume that all users are only debugging C/C++ at a time. Some users debug Python or node.js natives and they have concurrent Python and C/C++ sessions.

**Comment by xisui-MSFT** [comment]
Today, I used vscode-mock-debug to test this. I don't have a Mac here, so I only tested Ubuntu 20. The public release 1.70.1, which I believe was released yesterday, doesn't have this issue. I then tried to debug VS Code, and oss dev doesn't have this issue as well. And yet it repros consistently in VS Code insiders.

I want to change the order onDidTerminateDebugSession fires and the active debug session changes, but seems like I don't have a way to test... Any thoughts?

**Comment by roblourens** [comment]
Because it's a timing issue, you're going to see some randomness like that. You pointed at the right code to be looking at in DebugService above. Maybe if you add some logpoints you can get an understanding of where the randomness is coming from.

**Comment by roblourens** [comment]
Did you look into this? Is it still an issue?

**Comment by xisui-MSFT** [comment]
I didn't get time to work on this in depth. Only worked around this by running the listener on start debugging and extension deactivation. I think this is an acceptable workaround for us, but not sure if this will cause issues for others.

I would suggest at least add a way to listen to when all debug sessions terminate. But you can close this ticket if this is considered lower priority.
