### ISSUE TITLE
Show keyboard shortcuts in Code Action Widget

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#157129]
"Is there a plan to show the keyboard shortcuts as well (similar to the old code action context menu)? 

This is helpful when there are different more detailed shortcuts for code actions, for example:

Old:
![image](https://user-images.githubusercontent.com/205036/182922158-8b8f8857-4a57-465e-868e-f338b522b24e.png)

New:
![image](https://user-images.githubusercontent.com/205036/182922206-424170d6-6b18-4b37-b8f4-cce6ab9e3479.png)

The 2 shortcuts are not shown in the new version."

_Originally posted by @lgrammel in https://github.com/microsoft/vscode/issues/152913#issuecomment-1205610643_

**Comment by mjbvz** [comment]
To verify:

1. Create a keybinding for a specific kind of refactoring:

```
{
        "key": "ctrl+shift+e",
        "command": "editor.action.refactor",
        "args": {
            "kind": "refactor.extract",
            "preferred": true,
            "apply": "ifSingle"
        }
    },
```

2. Open the code action widget so a refactoring of the kind above is visible (`refactor.extract` for example)
3. Confirm the keybinding shows in the widget next to extract actions
