### ISSUE TITLE
Documentation for manual pwsh terminal integration is incorrect in macOS

### ISSUE THREAD

**Issue by yobyot** [microsoft/vscode#157131]
If you:
1. Use the PowerShell VS Code extension and 
2. Want to use terminal integration in the terminal created by the PowerShell VS Code extension

Then on macOS even if `terminal.integrated.shellIntegration.enabled` is set to `true`, it is still necessary to update the VS Code PowerShell extension's `$PROFILE` (`$HOME/.config/powershell/Microsoft.VSCode_profile.ps1`) to execute `shellIntegration.ps1`. 

In any case, the [documentation](https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation) for macOS shows an invalid path for manual activation in any pwsh terminal.

Here's what worked for me on macOS 12.5:
`
if ($env:TERM_PROGRAM -eq "vscode")
{
    . "/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration.ps1"
}
`

It should also be noted that the `$PROFILE` executed by the VS Code PowerShell extension is _not_ the same as the `$PROFILE` executed in a macOS terminal session or a VS Code terminal which isn't running the VS Code PowerShell extension. However, a non-VS Code PowerShell extension console does not offer services that pwsh devs use, like IntelliSense and debugging.

I'm not sure where the distinctions between a "real" PowerShell console and the one created by the VS Code PowerShell extension are documented but when VS Code talks about a PowerShell terminal, it rarely (if ever) makes this distinction clear. Yet pwsh devs will almost always choose to work in the terminal session created by the VS Code PowerShell extension since it is the replacement for the PowerShell ISE.

<img width="1193" alt="shellintegration" src="https://user-images.githubusercontent.com/14332263/182930908-dd49c277-de14-4d23-a404-2867eacfedf2.png">

**Comment by Tyriar** [comment]
I don't think we need to say anything about the wrong location as you run $Profile in the "PowerShell Extension" terminal and it will give you the correct path. This is essentially the same request as https://github.com/PowerShell/vscode-powershell/issues/3901, we have been talking and I'm sure this will happen soon 👍
