### ISSUE TITLE
openTextDocument with uri scheme "file" is treated as uri scheme "untitled"

### ISSUE THREAD

**Issue by MichaelHindley** [microsoft/vscode#157141]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.69.2
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z (2 wks ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

Steps to Reproduce:
```typescript
uri variable example: {
  $mid: 1,
  fsPath: "/Users/username/Documents/project/file.js",
  external: "file:///Users/username/Documents/project/file.js",
  path: "/Users/username/Documents/project/file.js",
  scheme: "file",
}
export const goToRouteSourceCommand = async (uri: vscode.Uri) => {
  // this is not going to the correct place, but instead opening a file named "Untitled"
  const document = await vscode.workspace.openTextDocument(uri)
  // this also does not work, though it should
  await vscode.window.showTextDocument(uri)
  // both options above behave as if scheme on the URI is untitled, but it's "file"

  // this works, using the same uri variable as above
  const document = await vscode.workspace.openTextDocument(vscode.Uri.file(uri.path).with({ scheme: uri.scheme }))
  await vscode.window.showTextDocument(document)
}
```

**Comment by jrieken** [comment]
The uri-data from your sample isn't considered a URI-instance (it looks like uri data, e.g what you get from toJSON) and therefore we fallback to a default case. Use `vscode.Uri.from(...)` or `.parse` instead

**Comment by MichaelHindley** [comment]
> The uri-data from your sample isn't considered a URI-instance (it looks like uri data, e.g what you get from toJSON) and therefore we fallback to a default case. Use `vscode.Uri.from(...)` or `.parse` instead

This was indeed the case, thanks for clarifying that data for the type signature alone is not sufficient to work with the openTextDocument api, but it actually requires an active instance based on the data.
