### ISSUE TITLE
Syntax Highlighting broken with Microsoft Edge

### ISSUE THREAD

**Issue by JtMotoX** [microsoft/vscode#157154]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:23:08.357Z (16 hrs ago)
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.44

Steps to Reproduce:

1. Run [Visual Studio Code Server](https://code.visualstudio.com/docs/remote/vscode-server) `serve-local`
2. Enable the Basic security within Microsoft Edge.
3. Open a json/bash/yml/etc.. file and there will be no syntax highlighting.

I have tried this while using the built-in http as well as behind a nginx reverse proxy with SSL termination (valid cert).  I have tried with every version of the Visual Studio Code Server release.  I have also tried with a fresh setup (no extensions/settings/etc..).  It took me 3 hours to figure this out.  I finally realized it was an Edge issue when I noticed it worked perfectly fine in Chrome.

---

![image](https://user-images.githubusercontent.com/7191259/182955640-1a007c66-f6ca-4205-acbf-1ee9945b7957.png)
![image](https://user-images.githubusercontent.com/7191259/182955685-889ec8bf-03b7-4c8b-8ea9-15efa2c43f2d.png)

---

![image](https://user-images.githubusercontent.com/7191259/182955704-9118ec5b-574e-4700-8c97-dd815cfc6702.png)
![image](https://user-images.githubusercontent.com/7191259/182955727-5b1a9502-0541-4f6b-998c-9e186f093113.png)

---

**Comment by alexdima** [comment]
@JtMotoX Are there any errors in developer tools?

**Comment by JtMotoX** [comment]
With Enhanced Security off, there are no errors.

With Enhanced Security on, this is the error I am getting:
```
ERR WebAssembly is not defined: ReferenceError: WebAssembly is not defined
    at z (https://vsc:4443/stable-da76f93349a72022ca4670c1b84860304616aaa2/static/node_modules/vscode-oniguruma/release/main.js:1:7821)
    at Object.n [as default] (https://vsc:4443/stable-da76f93349a72022ca4670c1b84860304616aaa2/static/node_modules/vscode-oniguruma/release/main.js:1:6044)
    at https://vsc:4443/stable-da76f93349a72022ca4670c1b84860304616aaa2/static/node_modules/vscode-oniguruma/release/main.js:1:4636
    at n.loadWASM (https://vsc:4443/stable-da76f93349a72022ca4670c1b84860304616aaa2/static/node_modules/vscode-oniguruma/release/main.js:1:4868)
    at k._doGetVSCodeOniguruma (https://vsc:4443/stable-da76f93349a72022ca4670c1b84860304616aaa2/static/out/vs/workbench/workbench.web.main.js:2300:48945)
```

**Comment by alexdima** [comment]
There's nothing we can do on our side. Syntax highlighting uses WebAssembly and WebAssembly is not available when configuring Edge in this mode.
