### ISSUE TITLE
Backup service: provide a list of available backups for a workspace

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15718]
This is a requirement to properly restore backups after a crash (https://github.com/Microsoft/vscode/issues/12327): Upon restart we automatically open folders that contain backups, however we miss information about the files that have backups.

The backup service should provide a method to get all untitled and file backups for a workspace so that we can reopen them. To minimize disk access and chances of staleness, I suggest to include the path within the backup file itself. E.g. the first N-bytes (up to a specific delimiter that is not allowed in file paths) can be the path and the rest is the file content. I would NOT use JSON for this and also NOT store this separately to avoid staleness issues.

**Comment by bpasero** [comment]
Marking as important because this is an area of potential data loss if hot exit is enabled.

**Comment by Tyriar** [comment]
@bpasero we can do something like this easily https://github.com/Microsoft/vscode/commit/928abc43770d1eb37a90edece5d36efb865ca5a2, but that would mean you need to first read the dir to get the list of files and then open up every backup file to get the resource it's associated with. Wouldn't that be bad if there are many large files included?

Would local storage be better?

**Comment by bpasero** [comment]
@Tyriar local storage is not an option because that is the first thing that will get stale when a crash happens. 

I agree that we should not read the entire file, but that can be solved easily: see the code we have for detecting if a file is binary (https://github.com/Microsoft/vscode/blob/ben/hot-exit-restore/src/vs/base/node/mime.ts#L67), it opens the file and only reads the first N bytes. The same should be possible here: only read until you find the first \n and then return. This should have stable performance only depending on the number of files, not their size. 

I think we need to minimize the risk of stale content in the backup folder. If we start to add a files.json file in the backup directory we have the issue of updating 2 files each time a backup changes.

An alternative approach would be to convert a file path to a file name in a way that you can restore the file path out of it. Instead of hashing the file path, use an algorithm that encrypts it so that it produces a valid file name. Naively, use base64?

**Comment by Tyriar** [comment]
@bpasero https://github.com/Microsoft/vscode/blob/a50aefd489c2a3f98ab52b44fdedef5766271c28/src/vs/base/node/mime.ts#L67 is just what I needed :+1: 

I think storing some metadata with the file is probably the way to go since recording the etag also seems necessary in #15749

**Comment by bpasero** [comment]
@Tyriar sounds good. another idea would be to use base64 for the file name and set the mtime to the value of where the backup started from. That way all the meta data would be outside of the file contents. I am not sure though if it is valid to set a mtime to a value in the past after changing the file.

**Comment by Tyriar** [comment]
I like the idea to store the metadata in the filename itself and using 2 way encryption. This does still have the same issues of why I hashed the path in the first place though; the troublesome 260 character limit on file paths on (legacy) Windows. The fact that the base64 string is even longer than the source string and Windows path case-insensitivity certainly doesn't help either.

How about keeping the file path as a one-way hash but including the number of bytes to read at the end, eg: `626e7164eb6877d5c945916b6ed08f68-73` where an example of the first 73 bytes is: `/home/daimms/dev/Microsoft/vscode/src/vs/code/common/windows.ts\n<etag>\n`

**Comment by Tyriar** [comment]
Alternatively keeping a metadata file alongside the backup, eg. `626e7164eb6877d5c945916b6ed08f68-metadata.json`:

```json
{
  "filepath": "/home/daimms/dev/Microsoft/vscode/src/vs/code/common/windows.ts",
  "etag": "..."
}
```

This is more future proof in case we need to keep more data but would involve an extra read.

**Comment by bpasero** [comment]
@Tyriar so to summarise, the problems with Base64 are:
* bigger chance to hit 260 path length issues because the encrypted version is longer than what we have now
* bigger chance of collisions because the same Base64 value can appear more often with different casing?

I do not see the value of adding the position of the metadata to the file name? It should just be separated to the content with some character. Think of HTTP protocol and them using a newline to start the body of the message, we can do the very same (just read the first line).

I think starting to store this in a separate file screams for issues with stale writes on a crash shutdown :-/

**Comment by Tyriar** [comment]
@bpasero the position was so `stream.readExactlyByFile` could be used with knowing the number of bytes to read in. Is there a nice way to read in x lines or do we have to estimate the number of bytes and try again if it wasn't enough?

**Comment by bpasero** [comment]
@Tyriar I see what you mean. not sure if it helps but we have some code when doing fulltext search that can split a file content up by lines: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/search/node/textSearch.ts#L154

though I must admit it is very complicated to understand ;)

In any way I would start by reading some 2k bytes, find the newline and if not continue reading.
