### ISSUE TITLE
bread crum for functions and classes in the editor

### ISSUE THREAD

**Issue by keyboy250** [microsoft/vscode#157152]
Type: <b>Feature Request</b>

i do not want to scroll to see what i am editing some code libraries are real long and scroll, this would make it intuitive to see where we are in the code showing the function that the cursor is in and the class. similar to the way css is in the chrome browser at the bottom of the editor / inspector

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22621
Modes:

**Comment by jrieken** [comment]
There is "View > Breadcrumbs"
<img width="1094" alt="Screenshot 2022-08-15 at 17 42 34" src="https://user-images.githubusercontent.com/1794099/184667980-cf21a316-b143-4ffb-b61b-ec251f8ca04d.png">
