### ISSUE TITLE
Allow search to show files in the "View as tree" mode

### ISSUE THREAD

**Issue by paustint** [microsoft/vscode#157133]
I would like the global search to behave just like git commits where I can choose to display the files as a tree instead of just as a flat list.

When I am doing a global search, it would be awesome if I could see where the search results are coming from in the codebase using a tree view. Oftentimes I am trying to find something in specific folders or areas and it would be awesome to be able to collapse or remove search results based on their root or partial path (again, exactly like I can do with files from git) 

Thank you 🙏 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/5461649/182933349-4156ff7f-e12a-4e22-8c98-e30e14233faa.png">

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/20224
