### ISSUE TITLE
Stick Scroll sticks python function's decorator line instead of the declaration line

### ISSUE THREAD

**Issue by lephuongbg** [microsoft/vscode#157180]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0
- OS Version: Windows 11

Steps to Reproduce:

1. Enable sticky scroll
2. Scroll through a python function with decorator

The function:
![image](https://user-images.githubusercontent.com/1001176/182976811-a3c396ad-e304-4633-b007-613c2e7771a6.png)

When the view is scrolled, sticky line should show the definition instead of the decorator. This is what it's like currently:
![image](https://user-images.githubusercontent.com/1001176/182976851-62702d2e-f85e-4a8e-8853-96151ab2a75e.png)

**Comment by nicok1** [comment]
Thank you for creating this topic. I have the same problem with all kinds of Spring Boot annotations.  One function is sometimes also annotated with multiple annotations, which should also be taken into account.

**Comment by pxlrbt** [comment]
Same for PHP Docblocks:

<img width="196" alt="Bildschirmfoto 2022-08-05 um 12 23 03" src="https://user-images.githubusercontent.com/22632550/183057864-f0bf7b66-3c18-4e47-9c51-00ef4f609102.png">

instead of

<img width="549" alt="Bildschirmfoto 2022-08-05 um 12 23 28" src="https://user-images.githubusercontent.com/22632550/183057952-f136ab60-780d-4dd7-964c-62dcc8c42cbe.png">

**Comment by IllusionMH** [comment]
It this issue specific to language or decorators? If yes, I'll create separate issue

"Similar" problems can be noticed in Java files where sticky scroll picks start of javadoc comment instead of class/method declarations
![image](https://user-images.githubusercontent.com/1312662/183092026-134c1b4b-72c1-46b2-9987-548ded38f245.png)

**Comment by pxlrbt** [comment]
I don't have any issues with docblocks in JS. But apparently a lot of other langauges.

**Comment by IllusionMH** [comment]
Looks like same problem with decorators is reproducible in JS/TS, but not with comments (as in Java above)
![image](https://user-images.githubusercontent.com/1312662/183104352-f4d96d18-784e-4b73-93fd-c564dba20754.png)

**Comment by RadsammyT** [comment]
This also happens with rust doc blocks, either with the triple slash (`///`) or the usual doc block ( `/** */`)
```rust
/// All elements of the vector are set to a random number from 0 to the length of the vector (Exclusive)
/// # Example
/// ```
/// vec = shuffle(&mut vec).to_vec();
/// ```
fn shuffle(v: &mut Vec<i32>) -> Vec<i32>{
    let test = v.len() as i32;
    for i in 0..v.len() as i32 {
        v[i as usize] = rand::thread_rng().gen_range(0..test);
    }
    return v.to_vec();
}
```
![RRXxtc2TFc](https://user-images.githubusercontent.com/32146976/183140086-f02e23cf-29ee-4d72-a4a5-9859f9b2a7b5.png)

What is interesting to note is that C++ (and very likely C) is not affected by this.

**Comment by dfarley1** [comment]
This is happening in C code where the function declarations are split over multiple lines as well:
<img width="318" alt="image" src="https://user-images.githubusercontent.com/5204693/183210346-4c3b5854-f79a-4f4c-a25e-211e55536dd6.png">
<img width="318" alt="image" src="https://user-images.githubusercontent.com/5204693/183210498-535433c8-b7fd-4ede-ad23-741d63341291.png">

**Comment by aiday-mar** [comment]
Hi thanks for all your feedback. I will be looking into all these issues.

**Comment by TheColorRed** [comment]
I am seeing this in TypeScript as well, so it looks like it is most/all languages.

**Comment by alexdima** [comment]
This might be improved if we would have a custom sticky ranges provider. A language server might tweak the results it would return from a sticky ranges provider to exclude decorators/comments/etc. Also related https://github.com/microsoft/vscode/issues/157165

**Comment by alexdima** [comment]
Another example for C# from 157284

> When using the new Sticky Scroll with a .NET API project, scrolling in a controller will only show any attributes as the "sticky" heading - [ApiController] - [HttpPost], etc. 
> ![image](https://user-images.githubusercontent.com/13488/183124906-333dc373-e47c-4c20-b0cb-ed8af11e80b5.png)
> ![image](https://user-images.githubusercontent.com/13488/183125026-c7a21206-2aaa-4f66-b230-094fe3873e73.png)

**Comment by paulojcdev** [comment]
Hi,
Similar issue happens with AL language, 

Sticky:
![image](https://user-images.githubusercontent.com/90965438/183591286-ec8e5eec-3454-40c4-89d1-d7112b397157.png)

expected:
![image](https://user-images.githubusercontent.com/90965438/183591807-c5c94864-bf3b-43a8-958d-843879eb300d.png)

procedure:
![image](https://user-images.githubusercontent.com/90965438/183591341-928128fa-d70f-483f-851e-817fa22eea1a.png)

Thanks for this feature!

**Comment by aiday-mar** [comment]
Thank you for all the feedback. These issues should be solved with https://github.com/microsoft/vscode/pull/157763.

New behavior:

![sticky-scroll-python](https://user-images.githubusercontent.com/61460952/183893324-aad78753-639b-4bf7-9135-ee7bc4ed1bca.gif)

![sticky-scroll-spring](https://user-images.githubusercontent.com/61460952/183893353-45964abd-e7bb-455b-bc54-14c24d3ebbdc.gif)

![sticky-scroll-php](https://user-images.githubusercontent.com/61460952/183893421-7fd1bc56-3e24-43c5-a6d0-356b7341f3c2.gif)

![sticky-scroll-rust](https://user-images.githubusercontent.com/61460952/183893441-4c1eaba2-1e3b-4d03-8d33-8384c17da239.gif)

![sticky-scroll-c](https://user-images.githubusercontent.com/61460952/183893480-f9c76975-9b54-4f01-9f52-44e897dc50ee.gif)

![sticky-scroll-cs](https://user-images.githubusercontent.com/61460952/183893502-0297bfe4-f585-4aab-b3f8-c37591951b5e.gif)

**Comment by Grueslayer** [comment]
@aiday-mar This seems not to be fixed for AL as posted by @paulojcdev in https://github.com/microsoft/vscode/issues/157180#issuecomment-1209023603 some comments before you commited the fix.

**Comment by aiday-mar** [comment]
Hi thanks for the feedback. Are you using an extension which provides a language server for AL? The sticky scroll depends on this. If you are, what extension are you using? I will test on my computer.

**Comment by Grueslayer** [comment]
I’m on insiders. AL comes from MS and uses a language server. https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Comment by DonJayamanne** [comment]
Verified, however I now run into another issue, not sure if its related though https://github.com/microsoft/vscode/issues/159118
