### ISSUE TITLE
Show visual indicator for repos with uncommited changes in Source Control panel

### ISSUE THREAD

**Issue by anakinsleftleg** [microsoft/vscode#157137]
## **Current**
When many repos are in a workspace, there is no visual indicator to quickly see which one has uncommited changes. There is the indicator over the Source Control icon (in the image here shown as 1 in the pink dot), but that's it. It leaves you to guess which repo has the uncommited change when the repos are cleanly folded up. In order to find the repo with the uncommited change, you much unfold every repo until you find it. For more than 1 uncommited change, you may have to open and visually scan each repo. 

![image](https://user-images.githubusercontent.com/77084568/182935283-59f620cd-75b2-4788-9a7a-db176595dd7b.png)

## **Desired**
There should be a visual indicator for each repo showing how many uncommited changes there are in it, even when folded. Then it is perfectly clear and unambiguous. It allows users to have a tidier workspace and not have to search many repos for which has a change.

![image](https://user-images.githubusercontent.com/77084568/182936665-0cf27e63-14f8-4be8-a7ef-3c9c6d9b1349.png)

## **Solemn Plea**
This has been bothering me for so long, and I'm finally submitting a request to fix it. I know it's technically not a bug, but it really sucks.

Please consider it. The software already knows which repos have changes, it already has the count indicator on the icon, so it knows which and how many and totals them up. That same logic just needs to be used to put an indicator on each repo line itself.

**Comment by gjsjohnmurray** [comment]
Did you try the `scm.providerCountBadge` setting?

**Comment by anakinsleftleg** [comment]
@gjsjohnmurray That is EXACTLY what I want! Thank you! I can't believe the default value is `none`. Why would anyone want that to be the default? Well I have now changed it and it is exactly what I described. Thank you very much
