### ISSUE TITLE
Automatic language detection fails to detect any language when first-detected language is disabled

### ISSUE THREAD

**Issue by vfonic** [microsoft/vscode#157199]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: macOS 12.5

I have a code snippet that I often copy-paste to a new untitled file. I have language detection enabled as I like the functionality. However, the functionality is buggy.

This code snippet is always recognized as groovy:

```ruby
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
CloudImageUrlSwapper.call('s3','r2',1)
```

 I have never used nor have ever seen any groovy code in my life.

----

Steps to Reproduce:

1. Press CMD+N to open new untitled file
2. Paste in the following code snippet:

  ```groovy
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  CloudImageUrlSwapper.call('s3','r2',1)
  ```
3. The text will be recognized as groovy language

----

Now try to disable Groovy in any way possible:

Add this to your `settings.json` and retry the steps above:

```json
"[groovy]": { "workbench.editor.languageDetection": false },
```

----

Next I tried to disable "Groovy Language Basics" built-in extension:

Go to Extensions, type `@builtin`, click on "Groovy Language Basics" and Disable.
Repeat the steps from above.

This time, there's no language detected. I'd argue that language detection should detect the "first available language", even though if it's not the "first detected language".
Here's what I mean by "first detected language" vs "first available language":

```json
[
  {
    "languageDetected": "groovy",
    "available": false
  },
  {
    "languageDetected": "ruby",
    "available": true
  }
]
```

In the example above, when Groovy is disabled, Ruby language should be detected.

Related: #131450

**Comment by TylerLeonhardt** [comment]
That setting is like... once you're on that language, don't switch off of it.

We need a setting that says "ignore these languages" in other words ... "don't ever guess these"

**Comment by TylerLeonhardt** [comment]
Thinking on it some more, I think rather than having a setting, we should just only guess something that makes sense for the open workspace. If you don't have a single Groovy file in your repo, then Groovy should be negatively boosted unless we are 99% certain that the code is Groovy.

**Comment by vfonic** [comment]
Fully agree! On top of that, if Groovy is disabled, it should _never_ be guessed.
