### ISSUE TITLE
Local image preview using built in Markdown Preview

### ISSUE THREAD

**Issue by rafr3** [Microsoft/vscode#15715]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Built-in Markdown Preview|

---

Steps to Reproduce:

1. add line `![img](i/example.jpg)` to `file.md`
2. Open markdown preview `CTRL+SHIFT+V`

Adding images using remote, full url works well. The problem is with loading local images only.  
I also tried to set full path to the file though it is quite impractical.

**Comment by mjbvz** [comment]
Relative image paths are currently resolved local to the markdown file itself, so relative paths should work. For example, with the following workspace:

```
posts/
    entry.md
images/
   cat.gif
```

in `entry.md`, the following image will work `![](../images/cat.gif)`

Can you try this out. We may want to consider adding an option to resolve resource relative to the workspace root instead.

**Comment by rafr3** [comment]
I noticed that the problem occurs only when the file contains spaces. That's not problem with relative local paths as we assumed. I was just surprised because I had no problems with attaching image files containing spaces using Atom editor.

Summarizing  
- works well `![](i/cat.gif)`
- doesn't work `![](i/cat 1.gif)`

**Comment by mjbvz** [comment]
That behavior is by design. According to the markdown spec, you have to precent encode urls in links and images. We could add special logic to automatically do this for local files paths, but any non-encoded paths would be broken once the markdown is uploaded to github or anywhere else. Replace the space with `%20` to fix this.

Thanks.
