### ISSUE TITLE
Sorting is wrong in explorer file pane

### ISSUE THREAD

**Issue by shanimal** [microsoft/vscode#157186]
Type: <b>Bug</b>

Sorting is wrong in explorer file pane

result
'video-stock.jpg' is before 'video.jpg'.

expected
'video-stock.jpg' should come after 'video.jpg'.

VS Code version: Code - Insiders 1.70.0-insider (12b08be500f8a307f30e92cbc3ee39ba115eab69, 2022-07-29T10:50:40.282Z)
OS version: Darwin x64 19.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 9, 10|
|Memory (System)|16.00GB (0.30GB free)|
|Process Argv|--crash-reporter-id 451718aa-c85b-47e7-b213-cb5e640c7c47|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
marko-beautify|bus|2.0.0
prettier-vscode|esb|9.5.0
vscode-open-in-github|fab|1.3.0
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
vscode-edit-csv|jan|0.7.1
marko-formatter|Mag|0.0.9
marko-vscode|Mar|0.17.34
vscode-marko-peek|mar|1.1.1
cpptools|ms-|1.11.4
hexeditor|ms-|1.9.8
test-adapter-converter|ms-|0.1.6
marko|pca|0.4.0
platformio-ide|pla|2.5.1
LiveServer|rit|5.7.5
gitblame|wad|9.0.1
qf|Wsc|6.8.122

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
vscscmwlcmt:30465136
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe try changing your `explorer.sortOrderLexicographicOptions` setting.

**Comment by lramos15** [comment]
As @gjsjohnmurray I find that most "sorting is incorrect" issues end up being fixed by `    "explorer.sortOrderLexicographicOptions": "unicode"`. Please give this a try

**Comment by rm-hull** [comment]
Not sure that this is "as-designed"...

Looking at the MDN docs, the localCompare API says `video-stock` comes AFTER `video`:

```javascript
const a = 'video'; 
const b = 'video-storage';

console.log(a.localeCompare(b));
// expected output: -1
```
<img width="304" alt="Screenshot 2022-08-14 at 14 53 10" src="https://user-images.githubusercontent.com/1915543/184540198-aa6bc97d-df56-4670-94ea-705756a23558.png">

> [Return value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#return_value)
A negative number if `referenceStr` occurs before `compareString`; positive if the `referenceStr` occurs after `compareString`; 0 if they are equivalent.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/184544856-878fba2c-ad00-4b2a-9985-d4b25196a361.png)

This looks odd for me.

**Comment by lramos15** [comment]
> Not sure that this is "as-designed"...
> 
> Looking at the MDN docs, the localCompare API says `video-stock` comes AFTER `video`:
> 
> ```js
> const a = 'video'; 
> const b = 'video-storage';
> 
> console.log(a.localeCompare(b));
> // expected output: -1
> ```
> 
> <img alt="Screenshot 2022-08-14 at 14 53 10" width="304" src="https://user-images.githubusercontent.com/1915543/184540198-aa6bc97d-df56-4670-94ea-705756a23558.png">
> 
> > [Return value](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare#return_value)
> > A negative number if `referenceStr` occurs before `compareString`; positive if the `referenceStr` occurs after `compareString`; 0 if they are equivalent.

This isn't the same case as the one mentioned in the original issue. Here's that case

<img width="541" alt="image" src="https://user-images.githubusercontent.com/4544166/184623298-2c102baf-ef04-42a4-acae-70fd5df4bfdf.png">


As @yume-chan localeCompare seems to behave differently with the file extensions than just with the names
