### ISSUE TITLE
[css] new at-rules such as `@property` are not yet recognized

### ISSUE THREAD

**Issue by Keyacom** [microsoft/vscode#157267]
Type: <b>Bug</b>

1. Copy-paste the following snippet to a CSS stylesheet (this example is taken from MDN):
```css
@property --my-color {
  syntax: '<color>';
  inherits: false;
  initial-value: #c0ffee;
}
```

**Expected**: VSCode won't see `@property` as an unknown at-rule.
**Actual**: VSCode sees `@property` as an unknown at-rule.
![obraz](https://user-images.githubusercontent.com/70766223/183085795-fd98fde0-6968-4b6b-a2b0-30a4a3d248ef.png)

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.45GB free)|
|Process Argv|--crash-reporter-id 57c06a69-98ac-4fc4-8225-c3db59f39ccc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.6
rainbow-csv|mec|2.4.0
vscode-language-pack-pl|MS-|1.70.8030912
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
material-icon-theme|PKi|4.19.0
LiveServer|rit|5.7.5
wikitext|Row|3.6.5
sass-indented|syl|1.8.22
open-in-github-desktop|wra|1.4.3

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30525688
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
hb751961:30541207
dsvsc012cf:30540253

```

</details>

**Comment by Keyacom** [comment]
`@property` at MDN: https://developer.mozilla.org/en-US/docs/Web/CSS/@property

**Comment by Keyacom** [comment]
The following CSS properties should also receive syntax highlighting:
- `@property`'s properties
    - `syntax`
    - `inherits`
    - `initial-value`
    - the custom property's name (just like for `@counter-style`)

This also applies to other new at-rules:
- `@layer` (can have other at-rules except `@charset`, `@import` and `@namespace` nested, including other `@layer`s)
- `@color-profile` and its properties:
    - `src`
    - `rendering-intent`
- `@import` can now import layers as well through `layer(<layer-name>)`
- `@scroll-timeline` and its properties:
    - `source`
    - `orientation`
    - `scroll-offsets`

**Comment by aeschli** [comment]
Syntax highlighting issues need to be filed against https://github.com/atom/language-css

**Comment by Keyacom** [comment]
This isn't just about syntax highlighting, but VSCode actually reporting these at-rules as unknown.
