### ISSUE TITLE
Sticky Scroll: Go to definition jumps to definitions but stay hidden behind sticky scroll layout

### ISSUE THREAD

**Issue by achhapolia10** [microsoft/vscode#157225]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: Ubuntu 20.04.2 LTS

Steps to Reproduce:

1. Have a definition just hidden under the sticky scroll layout. 
2. If you try to jump to that particular definition the cursor jumps to that position but the definition stays hidden under the layout.

**Comment by alexdima** [comment]
Similar to https://github.com/microsoft/vscode/issues/157394 and https://github.com/microsoft/vscode/issues/157175

**Comment by aiday-mar** [comment]
Solved by current changes, visible during the next release

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/157175
