### ISSUE TITLE
Policies: Error downloading language pack

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#157219]
```
Error: [404] Error downloading language pack ru@1.69.0
    at getSpecificNLS (D:\a\_work\1\s\build\lib\policies.js:426:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async getNLS (D:\a\_work\1\s\build\lib\policies.js:442:20)
    at async Promise.all (index 4)
    at async getTranslations (D:\a\_work\1\s\build\lib\policies.js:476:12)
    at async Promise.all (index 1)
    at async main (D:\a\_work\1\s\build\lib\policies.js:480:38)
```

https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=180793&view=logs&j=ca7250c6-0e2d-5a52-28a2-5c6aea023c92&t=a704f971-fb7e-553d-39e9-08631f8eece9

**Comment by bpasero** [comment]
Workaround https://github.com/microsoft/vscode/commit/73fd3f11032e7b83c2ae011b5516e6ddd19e3db2

**Comment by TylerLeonhardt** [comment]
That language pack version doesn't exist. Ever since we moved to the extension build pipelines, the patch version is random, not incremental.

My guess is that there's a bad Marketplace query here

**Comment by joaomoreno** [comment]
> That language pack version doesn't exist. Ever since we moved to the extension build pipelines, the patch version is random, not incremental.

Oh :( How do we guarantee versions within the same `major.minor` have incremental patch numbers then?

**Comment by TylerLeonhardt** [comment]
They're not totally random, the patch version is the date+time.

There is prior art in the unpkg service for fetching the correct language pack:

https://github.com/microsoft/vscode-unpkg/blob/main/src/marketplace.ts#L171

This, given a vscode engine version and a locale, will return the highest compatible version of a language pack for that locale.

Can you use this?
