### ISSUE TITLE
Executing `vscode.executeDocumentSymbolProvider` for multiple files or for a folder

### ISSUE THREAD

**Issue by Blaiski** [microsoft/vscode#157203]
I am developing a vscode extension that needs to obtain `DocumentSymbols[]`s for large number of source files in an open workspace. Ideally, for a selected set of folders in a workspace.

I am currently using the method below, and by some extreme workaround I am able to retrieve the `DocumentSymbols[]`s for all files I want. 
```TypeScript
const result: vscode.DocumentSymbol[] = await vscode.commands.executeCommand('vscode.executeDocumentSymbolProvider', uri);
```

</br>
However, my current solution is far from perfect and I wonder if it is possible to introduce a command similar to the above but that accepts a **folder uri** instead of a **file uri**. I understand such command would need a lengthy backend processing but that is fine. 

I suppose this is something that has to be supported at the LSP level first?

I did try the alternative method of requesting WorkSpace symbols like this:
```TypeScript
 constant result = await vscode.commands.executeCommand('vscode.executeWorkspaceSymbolProvider', '*');
```
but unfortunately the above command returns `SymbolInformation[]` only, and these are lacking the data structure (i.e., hierarchy) which I depend on for my extension.

</br>
Maybe I am approaching the problem wrongly? I'll be grateful for any tips or help. Otherwise, would such feature be possible in the near future? Or should this request be addressed to LSP specification/project in the first place?

Thank you very much!
Max

**Comment by jrieken** [comment]
This is unlikely to happen. Assuming this makes it into LSP, how should a language service implement this if not file by file? Maybe some little optimisation in loading can be done but ultimately it's an operation that works file by file and per folder. 

> Maybe I am approaching the problem wrongly?

IDK - you haven't told me what you are trying to achieve...

**Comment by Blaiski** [comment]
Thank you very much, I realised this is currently not supported by LSP so my question/request above is definitely irrelevant at this point.

I also probably didn't describe it well. I didn't mean it to be other than file by file. Internally, the server will have to process it file by file. My point was for a mechanism to efficiently send a request to the server for a larger number of files (and without files having necessarily to be open in the editor).

>>Maybe I am approaching the problem wrongly?

>IDK - you haven't told me what you are trying to achieve...

I basically need to capture information about all the document symbols along with their hierarchical structure.

**Comment by jrieken** [comment]
> My point was for a mechanism to efficiently send a request to the server for a larger number of files (and without files having necessarily to be open in the editor).

There should be no need to have the file open in an editor, the API command should work on any file - the command will make sure the file is loaded (!== shown) first. I think it's fair to send requests one by one, sure batching them will be faster but the sending of a request isn't the bottleneck in the process. 

Overall, when doing this be very mindful about other things, e.g pause reasonably between requests because otherwise "aggressive" requesting can saturate the whole extension host process

**Comment by Blaiski** [comment]
> Overall, when doing this be very mindful about other things, e.g pause reasonably between requests because otherwise "aggressive" requesting can saturate the whole extension host process

Thank you so much, this is very helpful really! I ended up indeed having to pause if a server was not responding, but hearing you saying this, I actually now realised I can refine my implementation better! --Thank you for the tip!

> There should be no need to have the file open in an editor, the API command should work on any file - the command will make sure the file is loaded (!== shown) first. I think it's fair to send requests one by one, sure batching them will be faster but the sending of a request isn't the bottleneck in the process.

This is very true for TypeScript and JavaScript, but unfortunately what I found is some other lang servers refuse to answer when a file is closed (even after ensuring that the client-server have been loaded by the extension host). OmniSharp for example, takes long to provide the response (even the Outline viewlet itself populates very late) and often (but not always) will not respond if the file is not open. Python's lang server also behaves a bit similar but not as bad as OmniSharp.

Anyhow, this was really helpful and thanks for your time!

**Comment by Blaiski** [comment]
Thank you, @jrieken very much for your earlier response! 
Just wanted to share with you that I have put out an extension on the marketplace [Grappl](https://marketplace.visualstudio.com/items?itemName=grappl.grappl)
I would love to hear what you think of it and also if you have any advice/recommendations, I would be so grateful!

Thank you!
Mujtaba
![grappl_vscode](https://github.com/microsoft/vscode/assets/31612240/a4bae8e3-b4a3-4961-bf1f-75f63e736185)

I tried having it produce a visual city of the Vscode repository and it surprisingly worked (but currently takes way too long and is horribly slow for such large codebase). Here is a pic (produced with an older version), and there're more on the extension page.
![vscode](https://user-images.githubusercontent.com/31612240/178550039-61cfc5ad-39b0-4f53-b838-36589f193b22.png)
