### ISSUE TITLE
bash: printf: `C': invalid format character error in bash terminal

### ISSUE THREAD

**Issue by dude0001** [microsoft/vscode#157278]
Type: <b>Bug</b>

I am running VS Code on a Windows host with a WSL (Ubuntu) remote session. I am seeing the error "bash: printf: `C': invalid format character" in bash terminals inside the IDE. I don't get the error every time, but I'm seeing it frequently for various commands and tools. When I get the error, the command also seems to hang until I kill it. I also do not get the error if I go and run the same command in a Windows Terminal bash shell from the same folder and same user inside my WSL environment.

I noticed the error started happening after the July 2022 update. There was a new feature automatically enabled that does some kind of shell integration and decorates command lines with a default/success/error icon. I am suspicious if this is causing the new error. I have not seen the error when having the decorators disabled.

I can include more information, logs, settings, environment, etc. if needed but I am not sure what else is relevant. Below is the information from the generated issue report.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (44.94GB free)|
|Process Argv|--folder-uri vscode-remote://wsl%2Bubuntu/mnt/d/Code/git/{redacted}/{redacted} --crash-reporter-id c92034d1-a12a-4e4c-9ca0-437f5b534928|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|Memory (System)|50.03GB (47.81GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|Memory (System)|50.03GB (47.81GB free)|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|has|2.23.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.241.3
remote-wsl|ms-|0.66.3
vscode-markdownlint|Dav|0.47.0
EditorConfig|Edi|0.16.4
terraform|has|2.23.0
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
azure-account|ms-|0.11.1
makefile-tools|ms-|0.5.0
java|red|1.9.0
vscode-yaml|red|1.9.1
markdown-preview-enhanced|shd|0.6.3
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0

</details>

**Comment by sburlappp** [comment]
Running with "set -x" shows the command line isn't being escaped during a call to printf. Simple test case:

```
$ date +%m
bash: printf: `m': invalid format character
$ $SHELL
$ date +%m
08

**Comment by thekendog** [comment]
Getting a similar issue on Mac with the latest July update.  Glad to know it's not just me.

**Comment by meganrogge** [comment]
Yes disabling shell integration will fix this until we have resolved it `terminal.integrated.shellIntegration.enabled`

**Comment by tpberntsen** [comment]
Getting this error when executing a statement including the following expression `date +'%Y%m%d-%H%M'`.
