### ISSUE TITLE
Mac OS: Support file info popup when clicking on file in title

### ISSUE THREAD

**Issue by zaichang** [Microsoft/vscode#15721]
- VSCode Version: 1.6.1
- OS Version: macOS 10.2 and OS X 10.1

There are several behaviors related 
Steps to Reproduce:
1. Open a file in VS Code
2. Rename that file in Finder
3. Note that VS Code now closes that tab instead of pointing the tab to the file with the new name
4. Also try single left-clicking on the window title where the filename is located, this does not pop up a file info dialog like in other apps

## For Step 3:
Other apps detect and follow the renaming of a file in Finder, and the opened document now point to the new file path.

## For Step 4:
Most document-based apps on OS X support this, and this allows easy renaming and tagging.

I was also going to write about the default keybinding for switching tabs not corresponding to the platform standard, but setting Cmd-Shift-[ and Cmd-Shift-] as the prev or next tab wasn't too hard in the end. Still wish it was by default though since platform defaults supersedes product defaults.

**Comment by bpasero** [comment]
@zaichang please read and understand https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

We do not manage multiple issues in one issue. 

I also suggest you use the search function first before filing issues.

Can you explain this: 

> Also try single left-clicking on the window title where the filename is located, this does not pop up a file info dialog like in other apps

How does that work? have a video or screenshot?

**Comment by zaichang** [comment]
@bpasero I'll keep that in mind when filing future issues. Thanks.

Regarding the feature here's a youtube video which describes it until around 0:50, the later menu bar items aren't as necessary:

https://www.youtube.com/watch?v=ulPJmuxQX8s

FYI it's great that right-clicking on the header brings up the file path crumbs menu, which I use often.

**Comment by bpasero** [comment]
This should work fine now, even when using custom title bar and you right click.

**Comment by zaichang** [comment]
Works great. Thanks a lot, this is most helpful!
