### ISSUE TITLE
Connections to mobile.events.data.microsoft.com

### ISSUE THREAD

**Issue by pcjmfranken** [microsoft/vscode#157228]
Type: <b>Bug</b>

VSCode connects unexpectedly to "mobile.events.data.microsoft.com" on startup.

This is a clean VSCode installation on a freshly wiped system.

All telemetry, updates and update checks, suggestions, and other external service dependant components have been disabled using the settings listed below, but no further customisations were made, no extensions installed, and no (settings sync) accounts have been logged into.

```jsonc
{
  "extensions.ignoreRecommendations": true,
  "extensions.autoCheckUpdates": false,
  "extensions.autoUpdate": false,
  "update.mode": "none",
  "workbench.startupEditor": "newUntitledFile",
  "telemetry.enableTelemetry": false,
  "telemetry.enableCrashReporter": false,
  "telemetry.telemetryLevel": "off",
  "typescript.surveys.enabled": false,
  "workbench.settings.enableNaturalLanguageSearch": false,
  "workbench.enableExperiments": false,
  "remote.autoForwardPorts": false,
  "remote.restoreForwardedPorts": false,
  "npm.autoDetect": "off",
  "npm.fetchOnlinePackageInfo": false,
  "typescript.disableAutomaticTypeAcquisition": true,
  "typescript.check.npmIsInstalled": false,
  "workbench.trustedDomains.promptInTrustedWorkspace": true,
  "workbench.welcomePage.walkthroughs.openOnInstall": false,
  "workbench.tips.enabled": false
}
```

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|32.00GB (23.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gjsjohnmurray** [comment]
Seems to originate here:

https://github.com/microsoft/vscode/blob/73fd3f11032e7b83c2ae011b5516e6ddd19e3db2/src/vs/platform/telemetry/common/1dsAppender.ts#L12

/assign @lramos15

**Comment by lramos15** [comment]
To verify:
1. Turn telemetry off
2. Reload
3. Toggle shared process dev tools
4. You should no longer see a 415 error request to mobile.events.data.microsoft.com in the console.

**Comment by bpasero** [comment]
There was one more request when I toggled the setting and reloaded, but then it was good.
