### ISSUE TITLE
Colors dull (washed out) after update at v1.70.0

### ISSUE THREAD

**Issue by MichaelLucca** [microsoft/vscode#157238]
Hi! After updating to version 1.70.0 (on the left) the colors seems to be washed out (on the right version 1.69.2).
![Schermata 2022-08-05 alle 11 40 11](https://user-images.githubusercontent.com/89570547/183050327-9adc3b9f-44b9-404f-910a-26830cd087fa.png)

I have already tried different combination of values in the argv.json but nothing seems to be working.

**Comment by azhiv** [comment]
The issue is still relevant for me as of v1.73.
