### ISSUE TITLE
confuse tooltip and command about kill terminal

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#157216]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

- in terminal tab，the ![image](https://user-images.githubusercontent.com/1876302/183013088-e8575468-e22f-4a16-895c-86c2a2551921.png) icon action is termination(终止)，and Specifically marked （delete）
![image](https://user-images.githubusercontent.com/1876302/182997880-645517ae-a413-4d38-b8bb-1cebd83cd117.png)
- but in command palette， the command is kill
![image](https://user-images.githubusercontent.com/1876302/182997891-916eac23-59eb-4483-8f99-b358fdbdb169.png)

should they be unified

1. termination？
2. kill？
3. delete？
4. Terminate terminal

**Comment by heartacker** [comment]
when there is only one terminal，the tip is `terminate terminal`(终止终端) 
![image](https://user-images.githubusercontent.com/1876302/183015731-d26125b5-f2be-4161-a666-6d2276bac169.png)
😖

**Comment by yume-chan** [comment]
I believe "Delete" is the keyboard shortcut for that operation.

**Comment by heartacker** [comment]
agree,
![image](https://user-images.githubusercontent.com/1876302/183057075-a3d03a1c-7074-4bde-9c6b-bdc7edec4ea9.png)

but we have to focus the terminal List frist, and then can use delete.

**Comment by Tyriar** [comment]
Yes the delete part is the keybinding which is correct. For unifying the wording I think our current process is to report issues to https://github.com/Microsoft/vscode-loc/issues with suggestions

**Comment by heartacker** [comment]
> Yes the delete part is the keybinding which is correct. For unifying the wording I think our current process is to report issues to https://github.com/Microsoft/vscode-loc/issues with suggestions

I don't think so.
I think we have to change the original English string  before  Improving translation.

**Comment by Tyriar** [comment]
@heartacker it's "kill" everywhere in terminal I believe, "delete" is the key on your keyboard
