### ISSUE TITLE
Quickfix doesn't work

### ISSUE THREAD

**Issue by michaeljota** [Microsoft/vscode#15728]
- VSCode Version: 1.7.1
- OS Version: Windows 10 AU

Steps to Reproduce:

1. I don't know.

Quick fix lightbulbs aren't showing. I just realize this, I don't know what cause that behavior. 

Typescript Hero auto import feature, should highlight this and show a QuickFix to import the missing module. 
![screen_one](https://cloud.githubusercontent.com/assets/10507776/20431808/60dcaba0-ad72-11e6-9219-b1ae78a9b239.jpg)

TSLint trailing comma rule, should highlight this and show a QuickFix to add the missing comma.
Also, it should highlight in the whole document all errors that the linter would throw. 
![screen_two](https://cloud.githubusercontent.com/assets/10507776/20431898/f61a024e-ad72-11e6-873b-f976a081dd85.jpg)

Linter errors in the document
![screen_three](https://cloud.githubusercontent.com/assets/10507776/20432061/be6f06f4-ad73-11e6-8c06-5f4d54ee36c0.png)

**Comment by waderyan** [comment]
Looks like this issue is specific to [TypeScript Hero](https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero). 

Please open an issue on the extension's repo.

**Comment by michaeljota** [comment]
No. It's not. In the second screen you should see a TSLint quickfix suggest, but it doesn't show up either.

**Comment by waderyan** [comment]
@michaelchiche Looks like I was mistaken. This issue belongs in the TS Lint repo - https://github.com/Microsoft/vscode-tslint/issues
