### ISSUE TITLE
Folder-Wide text search

### ISSUE THREAD

**Issue by okezieokpara** [Microsoft/vscode#15720]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Folder-wide search. The Ctrl F search should have options for search single files or  across the whole folder
2.

**Comment by kaiwood** [comment]
It has. If you click on the marked symbol here in the screenshot, you have additional fields for including/excluding files/folders:

![screen shot 2016-11-18 at 14 01 34](https://cloud.githubusercontent.com/assets/7542/20430977/c9e42054-ad97-11e6-91d7-a67a793de248.png)

Additionally, you can right-click on a folder in the file explorer and use the option `Find in Folder`.

**Comment by ramya-rao-a** [comment]
Thanks @kaiwood for jumping in.

@okezieokpara Also, you can open the search bar shown above by Ctrl + Shift + F
