### ISSUE TITLE
Ctrl+Click rustc error message no longer jumps to the location

### ISSUE THREAD

**Issue by CrendKing** [microsoft/vscode#157232]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: Windows 11 Build 22000.795

Steps to Reproduce:

When running `cargo check` task in VSCode inside a Rust project, if there is error, the integrated terminal would output something like this:
```
Checking <redacted> v0.1.0 (<redacted>)
error: expected one of `(` or `<`, found `foobar`
  --> <redacted>\src\main.rs:82:42
   |
82 | 123
   | ^^^ expected item

error: could not compile `<redacted>` due to previous error
```
The error location (`<redacted>\src\main.rs:82:42`) is linkable to the source code location when Ctrl+Click in previous versions (such as 1.69.2). In VSCode 1.70.0, it always jumps to the first line of the file.

1. Open a Rust project with errors in main.rs.
2. Run task `cargo check`.
3. Ctrl+Click the error location.

**Comment by coder-mike** [comment]
I'm seeing this issue as well in TypeScript code after upgrading to 1.70.0, but **my path's do not contain spaces**, so I'm not sure that this is really a duplicate of https://github.com/microsoft/vscode/issues/155532
