### ISSUE TITLE
VSCode and starship prompt not working as expected after the latest update V1.70.0

### ISSUE THREAD

**Issue by diningPhilosopher64** [microsoft/vscode#157206]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: V1.70.0
- OS Version: Ubuntu 20.04

Steps to Reproduce:

1. Update to latest V1.70.0 version of VSCode
2. Use starship prompt for the bash shell.

I have my starship prompt configured to update if the previous command execution failed for unknown reasons.

After the latest update, every command execution seems to fail only in VSCode's terminal.

Below is the expected behaviour, in a bash terminal:
```bash
skondapa@hyd-skondapa-l [~] 
❯❯❯ echo "Hello world"
Hello world

skondapa@hyd-skondapa-l [~] 
❯❯❯ 
```
The screenshot of the same with colors:
![image](https://user-images.githubusercontent.com/12293878/183003690-f09af4e8-2cf7-41ee-9654-991357d92c2c.png)

Now in the VSCode's terminal (running bash):
(It shows the error condition even in a brand new instance of the terminal)
```bash
skondapa@hyd-skondapa-l [~] 
Error in prev cmd ✗ echo "Hello World"
Hello World

skondapa@hyd-skondapa-l [~] 
Error in prev cmd ✗ 

```

A screenshot of the same with colors:
![image](https://user-images.githubusercontent.com/12293878/183003517-2b9a09e8-9eec-462f-b152-a8ec4eb2c8fc.png)

This behaviour of always erroring out even for a successful command execution started today after VSCode auto updated to V1.70.0

Below is the information I got from `Help -> About` menu:

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:48.541Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-43-generic snap

**Comment by gjsjohnmurray** [comment]
Did you notice https://code.visualstudio.com/updates/v1_70#_shell-integration-enabled-by-default?

**Comment by diningPhilosopher64** [comment]
@gjsjohnmurray , thanks for the prompt response! 

Yes, by disabling shell-integration, starship prompt started behaving as expected.  Shall I close this issue or consider this a bug with shell-integration ?

**Comment by anoushk1234** [comment]
I don't see why there was a need to enable Shell Integration by default, spent the last 2 hours trying to figure out what was wrong

**Comment by BMBurstein** [comment]
This probably has nothing to do with starship (I have the same issue without starship). This is just a specific case of #157294 and should probably be closed as a duplicate
