### ISSUE TITLE
workbench.list.openMode  is only valid for opening files, not valid for opening folders

### ISSUE THREAD

**Issue by zimocc** [microsoft/vscode#157204]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: win10

Steps to Reproduce:
1. set "workbench.list.openMode": "doubleClick"

 I think this configuration should work for files and folders

**Comment by gjsjohnmurray** [comment]
Please use the `workbench.tree.expandMode` setting.

**Comment by zimocc** [comment]
> 

thanks
