### ISSUE TITLE
Text buffer memory leak

### ISSUE THREAD

**Issue by cynecx** [microsoft/vscode#157297]
Does this issue occur when all extensions are disabled?: Yes

```
Version: 1.71.0-insider
Commit: 73fd3f11032e7b83c2ae011b5516e6ddd19e3db2
Date: 2022-08-05T07:36:08.599Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

Steps to Reproduce:

Same as in https://github.com/microsoft/vscode/issues/142933.

1. Prepare a large text file (Citylots.json is ~190MB):

```sh
wget -O citylots.json "https://raw.githubusercontent.com/zemirco/sf-city-lots-json/master/citylots.json?raw=true"
cp citylots.json evenlarger.json
cat citylots.json citylots.json >> evenlarger.json
```

2. Open evenlarger.json in vscode.
3. Scroll around. Make some small edits here and there.
4. Close the file.
5. Observe the memory usage through  "Activity Monitor".

Even minutes after closing the file, the file buffer remains in memory:

<img width="1677" alt="image" src="https://user-images.githubusercontent.com/5961244/183127197-d8cf5a60-e676-4b53-8bdd-fe35d35968ad.png">

**Comment by hediet** [comment]
Does this happen with default settings / no installed extensions?

**Comment by cynecx** [comment]
Yes, It did happen with no extensions enabled. However, it seems that I can't reproduce this with the latest nightly (b0895f9fcc5b49587a2b187a92bbe6d7efae35fa), so I guess closing this then. Sorry about the noise.

**Comment by hediet** [comment]
Memory leaks can be very subtle and even depend on the browser engine (e.g. which variables a closure captures).
