### ISSUE TITLE
Bash shell script issue with "%" sign

### ISSUE THREAD

**Issue by 502107** [microsoft/vscode#157226]
I'm using VSCODE for my ssh sessions. Since the July 2022 update, whenever I try to execute a command that has the % sign I get one of those two print errors:
`bash: printf: '\': invalid format character`
`bash: printf: 'Z': invalid format character`

I tried a different ssh client and the issue doesn't appear, so it's something with this update. Is anyone aware of a solution?

**Comment by gjsjohnmurray** [comment]
Did you notice https://code.visualstudio.com/updates/v1_70#_shell-integration-enabled-by-default? Please try disabling shell integration to see if this change to the default has triggered your issue.

**Comment by 502107** [comment]
Yes, that did the trick. Thanks!

**Comment by Tyriar** [comment]
![Recording 2022-08-05 at 07 22 10](https://user-images.githubusercontent.com/2193314/183097017-024cfcf6-4227-400d-b3d9-b6166c6cbd69.gif)

**Comment by Tyriar** [comment]
It's to do with 633 E:

```
builtin printf '\033]633;E;echo '\''%'\''\007'
bash: printf: `\': invalid format character
```

**Comment by Tyriar** [comment]
Same problem in zsh:

![image](https://user-images.githubusercontent.com/2193314/183118455-93d0a9ea-3b86-464a-9216-0411938fe8bf.png)

**Comment by ryenus** [comment]
@Tyriar, there's actually a simpler way to fix this issue than escaping the `%` char ending up in the printf format string, by passing it as a separate parameter to `printf`.

I have left a comment in the linked pr as well: https://github.com/microsoft/vscode/pull/157352/files#r939627065

> We don't have to escape if `$__vsc_current_command` is passed as a separate parameter to `printf`, avoiding the need for the sub-shell and sed, like this:

```sh
builtin printf "\033]633;E;%s\007" "$__vsc_current_command"
```

**Comment by Tyriar** [comment]
@ryenus that's much nicer if it works 👍

**Comment by ryenus** [comment]
> @ryenus that's much nicer if it works 👍

It should, as the same approach is already used in [`__vsc_update_cwd()`][1], and [`__vsc_command_complete()`][2].

BTW, thank you for being open and kind 👍 

[1]: https://github.com/microsoft/vscode/blob/324c3e7eea4d22d15904d10b43f6f958bfbeff93/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L56-L57
[2]: https://github.com/microsoft/vscode/blob/324c3e7eea4d22d15904d10b43f6f958bfbeff93/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L73-L77
