### ISSUE TITLE
SIGSEGV in Firefox Unit Tests on macOS

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#157245]
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=180673&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb&l=16933
* https://dev.azure.com/monacotools/Monaco/_build/results?buildId=180660&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb

**Comment by bpasero** [comment]
Fixed with disabling Firefox as unit test target: https://github.com/microsoft/vscode/commit/ede1cd6a388a52e08d2dd64c73e590f96436c480
