### ISSUE TITLE
Can not open large files

### ISSUE THREAD

**Issue by ilovesusu** [Microsoft/vscode#15729]
- VSCode Version:1.7.1
- OS Version:Debian Testing

Steps to Reproduce:

1. Generate a 50mb file, about 2000000 lines
> $:bash
> $:i= 0
> $:while [ $i -le 3000000 ]; do echo "asdfghjjklooiyerqwuhgsdjg" >>hello; i=$(($i + 1)); done
2. Open a 50mb file

**Comment by ramya-rao-a** [comment]
Closing as duplicate of #15393
