### ISSUE TITLE
Merge editor needs a way to accept all yours/theirs

### ISSUE THREAD

**Issue by DJackman123** [microsoft/vscode#157277]
Love the new 3-way merge editor feature.  But when I'm merging a file with lots of conflicts and all I want to do is accept all of "yours" or "theirs" changes, it's a real pain to have to scroll through the whole file and check every box one by one.  Please add a button to the top of the editor window that lets me take all of the "yours" or "theirs" changes at once.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/156617#issuecomment-1198990192

**Comment by DJackman123** [comment]
Ah yes, the functionality I want is there.  I guess since more than one person has asked for this it's more an issue of discoverability.  Way too many "..." menus here and plenty of space for buttons.
