### ISSUE TITLE
How to disable Ctrl + R refresh function when using react to develop plug-ins

### ISSUE THREAD

**Issue by dengyushuai** [microsoft/vscode#157236]
Starting debugging under extension.js will launch a new vscode window, and CTRL +R will refresh the page of this window

**Comment by ArturoDent** [comment]
```jsonc
  {
    "key": "ctrl+r",
    "command": "-workbench.action.reloadWindow",
    "when": "isDevelopment"
  }
```

Then you can set `Ctrl+R` to whatever you want.

**Comment by weinand** [comment]
@ArturoDent thanks for providing an excellent.

**Comment by dengyushuai** [comment]
> ```js
>   {
>     "key": "ctrl+r",
>     "command": "-workbench.action.reloadWindow",
>     "when": "isDevelopment"
>   }
> ```
> 
> Then you can set `Ctrl+R` to whatever you want.

thank you

**Comment by dengyushuai** [comment]
> @ArturoDent thanks for providing an excellent.

thank you
