### ISSUE TITLE
Cannot save files named in Chinese

### ISSUE THREAD

**Issue by gintamamadao** [microsoft/vscode#157386]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0 (Universal)
- OS Version: Darwin x64 21.6.0

Steps to Reproduce:

1.
2.

**Comment by gintamamadao** [comment]
I don't know why but after the update, sometimes files named in Chinese can be saved and sometimes not

**Comment by gintamamadao** [comment]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/51436276/183260110-f890a22c-8abb-441e-893e-b0f49a507073.png">

The left sidebar shows that a file has been modified, but the editor list indicates that it has not been modified

**Comment by Semesse** [comment]
Have you noticed any error notifications on the bottom right? If a file cannot be saved when you hit `ctrl+s,` there should be a notification reporting the problem. Or if you have configured "format on save" or "code actions on save", they will block until the specified actions are finished.

**Comment by gintamamadao** [comment]
> Have you noticed any error notifications on the bottom right? If a file cannot be saved when you hit `ctrl+s,` there should be a notification reporting the problem. Or if you have configured "format on save" or "code actions on save", they will block until the specified actions are finished.

when I hit ctrl+s, no notification show, and  I didn't configured "format on save" or "code actions on save".

<img width="673" alt="image" src="https://user-images.githubusercontent.com/51436276/183279552-165fa0ff-ae04-41ed-96a3-f349cfb9f479.png">

**Comment by gintamamadao** [comment]
<img width="250" alt="image" src="https://user-images.githubusercontent.com/51436276/183279580-7dd47304-4b1b-44dd-b2cc-70e9b5ba2ee0.png">

If I open the Auto Save , vscode will automatically save the changes to the file. if I dont and just hit ctrl+s, nothing will happen

**Comment by gintamamadao** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/51436276/183279823-260d731e-7c28-4bcb-8752-8b9dd3cc8430.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/51436276/183279855-46f9d03b-7602-44e8-b7bc-dc8dcfb63467.png">

If I modify a file named in English, as usual, there are three places where it shows that this file has same new change  waiting to be saved. But if I modify a file named in Chinese, only the left sidebar shows that there are a file has been changed waiting to be saved

**Comment by Semesse** [comment]
I get your point, the file seems already written to disk. The dirty indicator (that solid circle) shows the file already saved, but the badge count does not update. It will be helpful providing more detailed steps or screen records since I cannot reproduce it.

There are some existing issues you can refer to:
https://github.com/microsoft/vscode/issues/65417
https://github.com/microsoft/vscode/issues/93627
https://github.com/microsoft/vscode/issues/137720

**Comment by gintamamadao** [comment]
> I get your point, the file seems already written to disk. The dirty indicator (that solid circle) shows the file already saved, but the badge count does not update. It will be helpful providing more detailed steps or screen records since I cannot reproduce it.
> 
> There are some existing issues you can refer to: #65417 #93627 #137720

It doesn't seem to be the same problem, and I can guarantee that the file is not being written to disk, because the dir is belong to a git  repository also, if I run command 'git status' under the dir, it shows that the file has not been modified.

**Comment by Semesse** [comment]
> > I get your point, the file seems already written to disk. The dirty indicator (that solid circle) shows the file already saved, but the badge count does not update. It will be helpful providing more detailed steps or screen records since I cannot reproduce it.
> > There are some existing issues you can refer to: #65417 #93627 #137720
> 
> It doesn't seem to be the same problem, and I can guarantee that the file is not being written to disk, because the dir is belong to a git repository also, if I run command 'git status' under the dir, it shows that the file has not been modified.

I'm sorry I misunderstood the situation... But as I tried on my own Mac with different approaches (local/remote, creating the file inside explorer/using cmd+N, auto save/manual save) I still can't reproduce the problem

**Comment by bpasero** [comment]
Steps to reliably reproduce please on a fresh user data dir (launch with `--user-data-dir <empty folder>`).

**Comment by gintamamadao** [comment]
> Detailed concise steps to reliably reproduce please on a fresh user data dir (launch with `--user-data-dir <empty folder>`).

I once deleted version 1.70.0 and re-downloaded the version 1.69.2 , and it solved my problem.

to reproduce the issue,  I re-downloaded  1.70.0,  but can not reproduce it now....I'm not sure why

thank you for all your help!
