### ISSUE TITLE
Terminal indicator for pwsh doesn't get clear if use shortcut Ctrl+L.

### ISSUE THREAD

**Issue by vunhatchuong** [microsoft/vscode#157385]
Steps to Reproduce:
1.Use pwsh
2. Clear it using Ctrl+L instead of clear command

![Animation](https://user-images.githubusercontent.com/20581504/183245935-4b51bf71-1e06-4806-96dd-2ad4dff1519d.gif)

**Comment by meganrogge** [comment]
it works for me for pwsh on macOS

**Comment by Tyriar** [comment]
The fix for this is probably the same as suggested in https://github.com/microsoft/vscode/issues/153476#issuecomment-1203813334
