### ISSUE TITLE
Angular2 templates : use () and [] to surround text

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#15731]
- VSCode Version: 1.7.1
- OS Version: MacOs X

This is more a question than a bug.

I'm working with **Angular2** and in **html** templates i got some problem of productivity.

When i select some text like this : 
![capture d ecran 2016-11-18 a 17 21 45](https://cloud.githubusercontent.com/assets/5599375/20437370/f133418c-adb3-11e6-9643-642154ea2712.png)

Then i press the quote **"** , it surround the text : 
![capture d ecran 2016-11-18 a 17 22 09](https://cloud.githubusercontent.com/assets/5599375/20437330/d6c15d84-adb3-11e6-8352-4fd5ed89206e.png)

If i press instead parenthesis **(** or this bracket **[** it just simply delete the text :
![capture d ecran 2016-11-18 a 17 22 22](https://cloud.githubusercontent.com/assets/5599375/20437521/87d0f1c0-adb4-11e6-9106-1dfbdd40fd67.png)
![capture d ecran 2016-11-18 a 17 22 31](https://cloud.githubusercontent.com/assets/5599375/20437520/87d085aa-adb4-11e6-8892-3ff83a9ab01c.png)

I'm looking for a config or something to allow me to surround text with more than simple or double quotes.
Or maybe an extension can help doing that ?

Thanks for considerating

**Comment by ramya-rao-a** [comment]
This happens in a normal html file as well.

**Comment by rebornix** [comment]
This feature is decided by language configuration `surroundingPairs`, see code here https://github.com/Microsoft/vscode/blob/master/extensions/html/language-configuration.json#L18. IMHO brackets surrounding is not a generic thing for HTML, it would be better to customize this setting in a specific Angular 2 extension, make sense?

I'd like to close it first here and you may want to file feature request to existing Angular extensions out there https://marketplace.visualstudio.com/search?term=angular&target=VSCode&sortBy=Relevance or even create your own extension! Thanks!
