### ISSUE TITLE
VoiceOver doesn't identify buttons in toolbars

### ISSUE THREAD

**Issue by hasanrefaeiah** [microsoft/vscode#157397]
as stated in the title, voiceover screen reader doesn't identify buttons on tool bars except for the manage toolbar. I use the latest version of VsCode as well as macOS version.

**Comment by gjsjohnmurray** [comment]
Probably  #155880 which is scheduled to be fixed in 1.70.1

**Comment by isidorn** [comment]
@hasanrefaeiah I appologise about this breakage, as @gjsjohnmurray this is a duplicate and will soon be fixed (most likely Thursday).
As a workaround you can use VS Code insiders https://code.visualstudio.com/insiders/ which already has the fix
