### ISSUE TITLE
Typo in splitview.ts

### ISSUE THREAD

**Issue by avi-gitkraken** [microsoft/vscode#157310]
Type: <b>Bug</b>

The comment in line 55 of splitview.ts mentions a minimum size when it should be referring to a maximum size.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.6.0
Modes:

**Comment by mjbvz** [comment]
Please open PRs for simple typos
