### ISSUE TITLE
Recognize typedoc.json support for jsonc

### ISSUE THREAD

**Issue by Gerrit0** [microsoft/vscode#157363]
since version 0.23 released about a month ago, TypeDoc supports jsonc in its configuration file. VSCode should allow comments without errors without additional user configuration, much like it does for tsconfig.json files.

#157362

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)

**Comment by Gerrit0** [comment]
@mjbvz this doesn't seem to be correct, given that the PR linked above adds it to a list of other jsonc files.

Note: typedoc.json != tsconfig.json. TypeScript shouldn't have anything to do with this.

**Comment by mjbvz** [comment]
Oh ok, you just want a file called `typedoc.json` to be  `jsonc` automatically. I'll reopen but this should be a very simply PR if you want to take a look

**Comment by Gerrit0** [comment]
Yes, I think I did it in #157362, then opened this issue when the PR template asked me for an issue.
