### ISSUE TITLE
listeners aren't registered in terminal service

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#157340]
for instance:

https://github.com/microsoft/vscode/blob/774340f96c9d6457c22d1064cdab71ccb17bba47/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L214-L216

**Comment by bpasero** [comment]
Its probably not causing leaks though because these listeners fire before the process terminates (renderer). Anyway, its a good idea to check components for listeners that are not registered and I wish we had better tooling for that...
