### ISSUE TITLE
Terminal tab title flicker

### ISSUE THREAD

**Issue by lobsterkatie** [microsoft/vscode#157321]
Type: <b>Bug</b>

Just updated and now when I run a watch process in my terminal, the tab title flickers between the name of the process (`volta-shim` in my case) and the type of shell (`zsh`). (It used to just always show the name of the process.) When I try to rename it, it just goes back to saying `zsh` (no more flicker, but also no ability to actually rename the tab).

https://user-images.githubusercontent.com/14812505/183151556-8db8ce8f-931a-4a05-8477-d2f3c09e27ff.mov

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 12, 14|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id b0279d3b-8393-4b25-b76f-67c5cd50b58e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (65)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
tasks-shell-input|aug|1.7.4
shifty|bme|2.0.1
multi-cursor-case-preserve|Car|1.0.5
solargraph|cas|0.23.0
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
bracket-select|chu|2.0.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
vscode-npm-source|dku|1.0.0
githistory|don|0.6.19
typescript-notebook|don|2.0.6
nunjucks-vscode-extensionpack|dou|0.0.1
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
vscode-firefox-debug|fir|2.9.8
code-runner|for|0.11.8
shell-format|fox|7.2.2
vscode-pull-request-github|Git|0.48.0
vscode-test-explorer|hbe|2.21.1
npm-dependency-links|her|1.2.0
background-terminal-notifier|jar|1.0.3
search-node-modules|jas|1.3.0
code-eol|jef|1.0.12
vscode-case-shifter|Jin|1.1.0
docthis|joe|0.7.1
vscode-peacock|joh|4.0.1
bracket-peek|jom|1.4.4
vscode-jest-test-adapter|kav|0.8.1
vsc-python-indent|Kev|1.17.0
yarn-lock-syntax|mar|0.1.3
template-string-converter|meg|0.6.0
xcodestrings|mhc|1.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
playwright|ms-|0.2.6
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.6
tsserver-live-reload|rbu|1.0.1
vscode-yaml|red|1.9.1
vscode-gitweblinks|red|2.7.0
vscode-sort-json|ric|1.20.0
bash-debug|rog|0.3.9
rust|rus|0.7.8
crates|ser|0.5.10
mdx|sil|0.1.0
swdc-vscode|sof|2.6.33
sonarlint-vscode|Son|3.7.0
ascii-plist|spe|1.0.3
rewrap|stk|1.16.3
open-in-browser|tec|2.0.0
ghosttext|tok|1.1.0
tab-groups|usa|2.0.1
errorlens|use|3.6.0
vscodeintellicode|Vis|1.2.22
txt-syntax|xsh|0.2.0
vscode-mdx-preview|xyc|0.3.3
vscode-open-in-github|ziy|1.3.6

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by Tyriar** [comment]
I'd guessing this is just what the tool you're running does. Try changing `terminal.integrated.tabs.title` to something other than `"${process}"` to stop this.

**Comment by Tyriar** [comment]
No worries, the reason I say that is we just pull the "title of the process" via this call and present it: https://github.com/microsoft/node-pty/blob/a141a9dc23186a0634e8981af31af4e478322259/src/unix/pty.cc#L440-L466
