### ISSUE TITLE
Terminal starts at ~

### ISSUE THREAD

**Issue by ragokan** [microsoft/vscode#157379]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.70.0 and Version: 1.71.0-insider
- OS Version: MacOS Monterey 12.5

Steps to Reproduce:

1. Start the VSCode
2. Open the terminal
3. Its path is ~ instead of current directory.
![image](https://user-images.githubusercontent.com/63511519/183242247-ef36860f-89af-43f7-95a7-334580a0c586.png)

I tried doing these:
`"terminal.integrated.cwd": "${workspaceFolder}"` -> it did not work
`"terminal.integrated.cwd": ""` -> it did not work
`"terminal.integrated.cwd": "${workspaceFolder}/something"` -> it opened ~/something

**Comment by rajeshberwal** [comment]
Have you tried to set it to  ```"terminal.integrated.cwd": ""```

**Comment by wladiston** [comment]
Same here.

> Have you tried to set it to `"terminal.integrated.cwd": ""`

Yeap, same issue. Funny thing I've tried `"terminal.integrated.cwd": "~/"` and it gives me an error showing like it was in the correct path and I was appending another incorrect path.
<img width="470" alt="Screen Shot 2022-08-06 at 3 45 14 PM" src="https://user-images.githubusercontent.com/1843792/183262056-49406fc1-f9b5-4931-b15b-770b3c24dcd2.png">

**Comment by ragokan** [comment]
> Have you tried to set it to `"terminal.integrated.cwd": ""`

Yeah, this also does not work, I added it above.

**Comment by mwarger** [comment]
I'm having this problem as well.  I also tried right-clicking a file or folder in one of my projects and choosing "Open in integrated terminal" - this opened a terminal at `~` instead of the selected folder location.

**Comment by ragokan** [comment]
Thanks VSCode team for such a fast fix. I am closing this issue thinking everyone's bugs get fixed or at least being fixed very soon.
https://github.com/microsoft/vscode/commit/62bf2bfb89b083ba500bf9d1a09cb5674b8e84a4

**Comment by dstoyanoff** [comment]
Btw, I am still on an older commit, but the issue got fixed for me. I am guessing it was not related to vscode after all. 

Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:55.829Z (6 days ago)
