### ISSUE TITLE
Process explorer double scrolling

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#157301]
![process-explorer-scrolling](https://user-images.githubusercontent.com/876920/183132613-61208620-9dca-42e3-9330-578c8d6acaed.gif)

The process explorer has both the window scrolling and list view scrolling. When window resizes, the list/tree view is not laid out properly and it's then impossible to view some rows.

**Comment by rebornix** [comment]
Should be fixed now.

**Comment by Tyriar** [comment]
This was part of https://github.com/microsoft/vscode/issues/114040
