### ISSUE TITLE
`width: fit-content;` is not supported

### ISSUE THREAD

**Issue by johnjroby** [microsoft/vscode#157372]
Type: <b>Bug</b>

[{
	"resource": "/c:/Users/",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": {
		"value": "compat-api/css",
		"target": {
			"$mid": 1,
			"external": "https://developer.mozilla.org/docs/Web/CSS/width",
			"path": "/docs/Web/CSS/width",
			"scheme": "https",
			"authority": "developer.mozilla.org"
		}
	},
	"severity": 8,
	"message": "'width: fit-content' is not supported by Firefox, Firefox for Android. Add 'width: -moz-fit-content' to support Firefox 3+, Firefox for Android 4+.",
	"source": "Microsoft Edge Tools",
	"startLineNumber": 105,
	"startColumn": 12,
	"endLineNumber": 105,
	"endColumn": 23
}]

'width: fit-content' is not supported by Firefox, Firefox for Android. Add 'width: -moz-fit-content' to support Firefox 3+, Firefox for Android 4+.

https://developer.mozilla.org/en-US/docs/Web/CSS/width says:
Firefox 94 supported.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (8.45GB free)|
|Process Argv|--crash-reporter-id fcd7e9fb-f87d-4bf6-be93-a5e3a9dc6a72|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
javascript-ejs-support|Dig|1.3.1
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
remotehub|Git|0.40.0
live-sass|gle|5.5.1
rest-client|hum|0.25.0
better-cpp-syntax|jef|1.15.19
vscode-edge-devtools|ms-|2.1.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
live-server|ms-|0.2.13
remote-repositories|ms-|0.18.0
vsliveshare|ms-|1.0.5679
sqltools|mtx|0.23.0
LiveServer|rit|5.7.5
cmake|twx|0.0.17
vscode-icons|vsc|11.14.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30525688
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by aeschli** [comment]
This error is generated by an extension, very likely the 'vscode-edge-devtools'.

Please file the issue there.
