### ISSUE TITLE
Peek window doesn't allow ctrl-s to save

### ISSUE THREAD

**Issue by abierbaum** [Microsoft/vscode#15733]
- VSCode Version: 1.6
- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Open any code file that has a symbol that can be "peeked" (Ctrl+Shift+F10)
2. View the code in the peek window and make a change in the peek window
3. Try to save from within the window (ctrl+s)
4. It does not save.  The change only saves when the user switches focus away from the peek window.

Note: I have settings with:
"files.autoSave": "onFocusChange"
"editor.stablePeek": true

Not sure if that changes the behavior.

**Comment by rebornix** [comment]
@abierbaum I didn't reproduce this on our latest insider build, do you mind giving our latest Stable 1.7.2 or Insider a try to see if it still exists?

**Comment by abierbaum** [comment]
@rebornix Looks like it does work with 1.7.2.  Thanks.
