### ISSUE TITLE
Open folder in new window

### ISSUE THREAD

**Issue by micnic** [Microsoft/vscode#15730]
This is a feature request

I use a lot the "Open folder" option and it is annoying when you want to open a folder in a new window you have to open a new window, wait until it is open, and then open the folder in that window. In Sublime Text every folder is opened in a new window. It would be nice to have this option too in VSCode, or better to have a dialog to chose between "open folder in current window" and "open folder in a new window" how it is in WebStorm.

Thank you :)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/371
