### ISSUE TITLE
Don't grab all (or any!) file associations upon install

### ISSUE THREAD

**Issue by KjellMorgenstern** [microsoft/vscode#157387]
Does this issue occur when all extensions are disabled?:  Not applicable (VS Code is expected to not start up at all, and I don't have influence on the CLI params)

- VS Code Version: http://packages.microsoft.com/repos/code stable InRelease  (1.70.0-1659589288 and others)
- OS Version: Ubuntu 20.04

Note: I don't think the issue is in VS Code itself, but in the setup routine that ships with the apt packaging.

A similar issue #41768 was closed without further information.

Steps to Reproduce:

- add http://packages.microsoft.com/repos/code stable InRelease
- sudo apt install code
- Open a folder from anywhere -> 'code' is started instead of 'files'
- Open a .svg file from anywhere -> 'code' is started instead of a dialog which asks for a program
- Open a .txt file from anywhere -> 'code' is started instead of the default editor

The only solution I found so far: `apt remove code`, so this issue makes visual studio code unusable.

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode/issues/122064 for some past context on this. I still believe this is a problem with the distribution, not what vscode is doing.
