### ISSUE TITLE
Go to definition messes up cursor history stack (go back)

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15735]
I want to go to `ITextFileService.resolveTextContent`.

![image](https://cloud.githubusercontent.com/assets/2193314/20440534/6d796760-ad75-11e6-80ab-4ba26bf14f82.png)

<kbd>F12</kbd>, I got there:

![image](https://cloud.githubusercontent.com/assets/2193314/20440555/7c04c306-ad75-11e6-8dd5-a4e3505f6bd2.png)

I now want to go back, `Go > Back`. It sends me here for some reason in `textfiles.ts`

![image](https://cloud.githubusercontent.com/assets/2193314/20440567/87c41d7c-ad75-11e6-96ee-1ce28e720f94.png)

Go back again sends me to correct spot, `Go > Back`.

![image](https://cloud.githubusercontent.com/assets/2193314/20440577/902f30fa-ad75-11e6-88f4-59e8b01fdfff.png)

@bpasero @dbaeumer @waderyan not sure who owns this and whether or not its an issue with TypeScript or the workbench.

**Comment by dbaeumer** [comment]
TS doesn't do anything special here.

**Comment by bpasero** [comment]
I can reproduce some weirdness here.

**Comment by kaiwood** [comment]
@bpasero Played with Insider from today, which includes 5081a59, but I have still exactly the same false behaviour as described above. "Go to Definition" seems to not register the jump in the history stack. Reopen this one or should I open a fresh Issue?

**Comment by bpasero** [comment]
@kaiwood can you share exact steps?

**Comment by kaiwood** [comment]
@bpasero Sure. Simplest case I could come up with:

This is how it works **correctly**, example recorded with 1.7.2:

![go_to_definition_1 7 2](https://cloud.githubusercontent.com/assets/7542/20622287/6b3d4538-b302-11e6-8c17-ca5587e55465.gif)

This is the same **non working** example recorded in 1.8 / Insiders:

![go_to_definition_1 8_current](https://cloud.githubusercontent.com/assets/7542/20622320/9cd160ca-b302-11e6-91f3-a418e5a63599.gif)


Additional Info:

- Fails no matter what input method use for the jump (Palette, command bound to shortcut, cmd+click)
- Fails with extensions disabled
- If you try to go back multiple times, you will notice that none of the positions are in the stack
- The commit that implemented the correct behaviour was f02c44d371d500b129c283a022724922f7473ac4, Issue was #11727 (see your comment at the bottom)
- As far as I understand it, the weird behaviour described in **this** issue above is not random jumping, but exactly what we had before the feature got implemented (where the history stack only got triggered by certain movements and therefor `Go Back` jumped back to "somewhere near" the position where `Go to Definition` was executed.

**Comment by bpasero** [comment]
Thanks 👍

**Comment by roblourens** [comment]
Verified but found #16881
