### ISSUE TITLE
Debugger for `.bat` files

### ISSUE THREAD

**Issue by astrohart** [microsoft/vscode#157303]
I request the ability to step through and debug, line by line, `.bat` files within the VSCode editor.

This is related to [Issue #20882](https://github.com/microsoft/vscode/issues/20882) because the team, I think erroneously, is doing a shoulder shrug.

I once again want to advocate for the feature described in the issue.

Please be aware, that there is a piece of software in existence called [JPSoft TakeCommand](https://jpsoft.com/).  Billing itself as an upgrade for the Windows Command Prompt, it also [includes a somewhat powerful IDE and batch file debugger.](https://jpsoft.com/help/index.htm?ide__batch_debugger.htm). 

Their [IDE attempts to replicate the look and feel of Visual Studio](https://jpsoft.com/templates/yootheme/cache/cmdebug-c8fdf1ba.png) but I can't fathom why it is not rewritten as a Visual Studio extension.

**Comment by gjsjohnmurray** [comment]
All VS Code debuggers are implemented as extensions. If one doesn't already exist for the case you want, perhaps an extension developer will step up and implement it.

**Comment by astrohart** [comment]
I've been thinking, for quite a while now, that I would take this project on.  Perhaps I just might!  I also have the idea of developing a full-blown Visual Studio extension to debug batch files.

I know, I know -- `.bat` files have been around since immemorial.  They're so antiquated -- I get it.  But sometimes, you know, when you just want to bash out a quick series of commands and don't want to fuss with a higher-level language, they come in handy for quick-and-dirty scripting.

Brian
