### ISSUE TITLE
Formally support multiple repositories nested under root workspace

### ISSUE THREAD

**Issue by nteymory** [microsoft/vscode#157347]
I searched for a similar issue and did not find one, apologies if a similar request has already been made.

I have a workspace that has a git repository in it's root. The root contains a subfolder that has it's own repository. The subfolder's repository is ignored by the root's repository:
```
Root (repo1)
 |- Subfolder (repo2)
 |- Other subfolders under repo1
```
What I would like is to open the workspace and see both repositories under source control. What happens is that vscode only shows the root's repository. Based on what I have read, this seems to be _intentional_ behavior; however:

If you temporarily move the root .git folder elsewhere, then re-open the workspace, vscode will now show the subfolder repository instead (makes sense). If you then move the above .git folder back into the root of the workspace, vscode detects the root repository as a second repository and shows both repositories under source control (exactly what I want!)

I'm currently using this workaround whenever I need to reopen my workspace:
- Move the root .git folder up one directory
- Open the root workspace
- Move the root .git folder back
- I can now see both repos and work the way I want

So my feature request is, can there be a configuration option added to support this more formally? It seems to me there is some kind of check that occurs when a workspace is first opened that will ignore scanning for any other repos if it finds one in the root. I basically want an option to disable that check on a per workspace basis. Or, honestly, just change the default to show all the repositories, which I personally think is more intuitive.

Thanks!

**Comment by lszomoru** [comment]
Thank you very much for filing this issue. This feature request is tracked by https://github.com/microsoft/vscode/issues/37947. Closing as duplicate.
