### ISSUE TITLE
No matching version found for `@types/vscode@^1.70.0.`

### ISSUE THREAD

**Issue by lxcyha** [microsoft/vscode#157304]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:1.70.0
- OS Version:macOS 12.5

Steps to Reproduce:

1. npm i -g yo generator-code
2. yo code
3. enter -> enter -> enter -> when 'npm install'

**Comment by cocoanaut** [comment]
@lxcyha a workaround until the update is published is to change the devDependency `package.json` to `"@types/vscode": "^1.69.1"`.

**Comment by inadarei** [comment]
FWIW, getting same exact error here.

**Comment by jiaqidegege** [comment]
Same issue here.

**Comment by bpasero** [comment]
This should have happened as part of the release, apologies if it did not, will investigate, but might take until tomorrow.

**Comment by bpasero** [comment]
Should work fine now.
