### ISSUE TITLE
Sticky Scroll: In C#, namespace, struct, property should stick, attributes shouldn't stick

### ISSUE THREAD

**Issue by CookieHCl** [microsoft/vscode#157375]
Does this issue occur when all extensions are disabled?: Almost yes (you need C# extension to make sticky scroll work, and issue happens when only C# extension is enabled)

- VS Code Version: 1.70.0 (system setup), commit: da76f93349a72022ca4670c1b84860304616aaa2
- OS Version: Windows 11 21H2 (22000.832)

### Code:
<img width="392" alt="code" src="https://user-images.githubusercontent.com/28638469/183240382-82c65e4a-81eb-4dd5-8efa-02669e033f1a.png">

### Actual:
<img width="392" alt="actual" src="https://user-images.githubusercontent.com/28638469/183240384-8ccad679-8196-43c1-8f26-b73dc091b3d3.png">

Namespace, property doesn't appear, and attributes appear instead of actual class.

### Expected:
<img width="392" alt="expected" src="https://user-images.githubusercontent.com/28638469/183240389-c888a527-2f8d-4933-bfdf-06ddabb47295.png">

Namespace, property, and actual class should appear.

### Code:
<img width="198" alt="code2" src="https://user-images.githubusercontent.com/28638469/183240444-7a34a360-10ce-41ba-8e5a-0fde21ffdc45.png">

### Actual:
<img width="182" alt="actual2" src="https://user-images.githubusercontent.com/28638469/183240448-5c195ddf-8bd8-4e95-92e1-e7b8d0f1af59.png">

When you scroll down, Struct doesn't appear.

### Expected:
![expected2](https://user-images.githubusercontent.com/28638469/183240451-b0586702-087d-4def-a513-641116dc5d23.png)

Struct should appear.

**Comment by DingWeizhe** [comment]
same problem in TypeScript decorator.
Code: 
<img width="584" alt="image" src="https://user-images.githubusercontent.com/6461899/183273399-a2420e72-f136-4f62-b389-80b6bd862847.png">

Actual:
<img width="488" alt="image" src="https://user-images.githubusercontent.com/6461899/183273407-2927898e-6904-4e1a-bb3c-280e5e04f584.png">

**Comment by aiday-mar** [comment]
Thank you for the feedback. This issue should be solved with https://github.com/microsoft/vscode/pull/157763. 

New behavior:

![sticky-scroll-cs2](https://user-images.githubusercontent.com/61460952/183896045-cd7133a3-f92e-4d6c-9588-defd342e1f3b.gif)

![sticky-scroll-cs3](https://user-images.githubusercontent.com/61460952/183896053-f86c92a4-069e-4a76-9155-e481fd38e4fb.gif)

![sticky-scroll-ts](https://user-images.githubusercontent.com/61460952/183896538-e780ad14-f9e6-4d97-8ef0-d4c5b8bde414.gif)
