### ISSUE TITLE
Unable to change variables in debug mode of PowerShell

### ISSUE THREAD

**Issue by ZamElek** [Microsoft/vscode#15732]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|VisualStudioDarkTheme|Adrien|1.0.1|
|vscode-theme-onedark|akamud|0.2.14|
|git-easy|bibhasdn|1.9.0|
|githistory|donjayamanne|0.1.0|
|xml|DotJoshJohnson|1.6.0|
|Theme-3024Night|gerane|0.0.3|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-TomorrowNight|gerane|0.0.2|
|Theme-TomorrowNightBright|gerane|0.0.2|
|Theme-TomorrowNightEighties|gerane|0.0.2|
|vscode-theme-onedark|gnhuy91|0.0.2|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|expand-region|letrieu|0.0.2|
|start-git-bash|McCarter|1.0.4|
|prettify-json|mohsen1|0.0.3|
|PowerShell|ms-vscode|0.7.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|Theme-TomorrowKit|ms-vscode|0.1.3|
|team|ms-vsts|1.108.0|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|4.0.1|
|theme-monokai-black|vip32bit|0.1.0|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. Try to run any command (e.g. $Script:LogRecords = get-aduser -filter * | select -first 1) in debug console got the error:
An attempt was made to transition a task to a final state when it had already completed.

**Comment by ramya-rao-a** [comment]
Please log this issue in the repo of the extension that you are using for Powershell features

**Comment by ZamElek** [comment]
Thank you, I'll do it.
