### ISSUE TITLE
Sticky Scroll: nested array keys are not shown in YAML

### ISSUE THREAD

**Issue by adammw** [microsoft/vscode#157481]
Does this issue occur when all extensions are disabled?: N/A - Sticky Scroll does not work YAML with extensions disabled. (Requires redhat.vscode-yaml extension)

- VS Code Version: Version: 1.71.0-insider (Universal)
Commit: b0895f9fcc5b49587a2b187a92bbe6d7efae35fa
- OS Version: macOS 12.5 (21G72)

Steps to Reproduce:

1. Install YAML extension
2. Turn on sticky scroll
3. Open a deeply nested YAML file such as https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/deploy/updater-deployment.yaml 
4. Notice that array keys are not shown, nor any subkeys of the array

Screen recording: https://user-images.githubusercontent.com/153219/183355737-8e5b9ca9-8cd1-4f0f-aa50-e97a034dcfcf.mov

**Comment by aiday-mar** [comment]
Fixed by https://github.com/microsoft/vscode/pull/15748

![sticky-scroll-yaml](https://user-images.githubusercontent.com/61460952/183887724-bd5b007d-2209-41fa-a2a1-c813cabe4550.gif)
3
