### ISSUE TITLE
Install extension to all existing profiles

### ISSUE THREAD

**Issue by exxmen** [microsoft/vscode#157492]
A "**Install - All Profile**s"  dropdown option when installing an extension will be a great addition

**Comment by exxmen** [comment]
Let's say you have a "**Base**" profile and a "**Python**" profile already created. While using the Python profile, you had the need to install an extension, for this example let's say the **XML** extension, but this extension can also be used by other profiles so you install the extension to the current profile (_Python_), then switch to the _Base_ profile and install the extension again.

If this feature is available, there will be no need to switch profiles if the extension you want to install is applicable to all existing profiles.

**Comment by exxmen** [comment]
@sandy081 where should I start if I want to help?

**Comment by RichardLuo0** [comment]
I think a better approach would be a tree-like structure:
- Base
  - Python
    - AI
    - CV
  - C++
  - Whatever

Each line represents a profile. The child profile only tracks the difference between itself and the parent. So installing any extension or changing settings to the parent profile automatically applies to the child profiles.

**Comment by Eitheages** [comment]
Hello @sandy081, I just find a problem about this feature: when make an extension pack "Apply Extension to all Profiles", its containing extensions aren't applied to all profiles. For example, I've make *GitHub Markdown Preview* "Apply Extension to all Profiles", 

![image](https://github.com/microsoft/vscode/assets/93167100/0d4ccaa4-0c56-42d3-8967-6662542c37de)

But these extensions are not.

![image](https://github.com/microsoft/vscode/assets/93167100/78432d82-0af1-4796-b9cf-6fb89321c024)

In my opinion it should be consistent. Thanks for you!

**Comment by sandy081** [comment]
Can you please file a separate issue for this usecase?

**Comment by Eitheages** [comment]
@sandy081 I've open the issue #190992. Thanks!
