### ISSUE TITLE
ventana pixeleada

### ISSUE THREAD

**Issue by LaRata300** [microsoft/vscode#157446]
We have written the needed data into your clipbo
![2022-08-07_13h51_03](https://user-images.githubusercontent.com/99001269/183306712-35b8b679-e0c1-479e-bed7-8b24c14e40da.png)
![2022-08-07_13h53_07](https://user-images.githubusercontent.com/99001269/183306714-38a4f361-f4b7-41d1-903c-1ad35554e565.png)
ard because it was too large to send. Please paste.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226
