### ISSUE TITLE
JavaScript Syntax Error for valid syntax: new.target

### ISSUE THREAD

**Issue by dilijev** [Microsoft/vscode#15746]
- VSCode Version: Code - Insiders 1.8.0-insider (043310affe454f94c665494b77818c1425cbe8db, 2016-11-17T12:04:45.677Z)
- OS Version: Windows_NT ia32 10.0.14965
- Extensions (running with --disable-extensions):

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.2|
|PowerShell|ms-vscode|0.7.2|
|rewrap|stkb|0.6.4|

---

Steps to Reproduce:

1. Load a javascript file with a script like the following:

```js
function foo() {
    console.log(new.target)
};
new foo;
```

2. Observe the error:

![image](https://cloud.githubusercontent.com/assets/494055/20452498/dd9dbdf8-adbf-11e6-8e8b-4be2d2b1ab2a.png)

**Comment by mjbvz** [comment]
Thanks. This is a known limitation of TypeScript (which we also use to power our JavaScript language support). I believe this is being tracked by: https://github.com/Microsoft/TypeScript/issues/2551

**Comment by dilijev** [comment]
@mjbvz gotcha, thanks.

**Comment by mjbvz** [comment]
Closing this since it is being tracked upstream on the TypeScript side.
