### ISSUE TITLE
Command executed and failed in terminal

### ISSUE THREAD

**Issue by alex-00-pixel** [microsoft/vscode#157450]
In, c++, program is correct but became fail. It shows command executed and failed. I am running code in terminal>
But in C, it working properly on any code. I am working in window11.
![Screenshot (79)](https://user-images.githubusercontent.com/110787720/183309463-bfd838b4-f283-41e1-87d4-59d2656c8206.png)
![Screenshot (79)](https://user-images.githubusercontent.com/110787720/183309488-a3934e59-7b43-4a00-9885-524bb559f729.png)

**Comment by meganrogge** [comment]
what is the exit code (hover the lightbulb) associated with the first run?

**Comment by alex-00-pixel** [comment]
Problem solved
