### ISSUE TITLE
Terminal font rendering not correct when launching

### ISSUE THREAD

**Issue by BigfootN** [microsoft/vscode#157426]
Hello,

I am facing an issue when setting:

```json
"terminal.integrated.fontFamily": "Iosevka Term",
"terminal.integrated.fontSize": 16,
"terminal.integrated.shellIntegration.decorationIcon": "",
```

When setting the font while `vscode` is running, there is no problem, I can see the font rendering in the terminal without any problems:

![image](https://user-images.githubusercontent.com/1183923/183285383-dd7f96d7-573a-48b0-9e1a-9bddb7457473.png)

Unfortunately, when I close and relaunch `vscode` I can see this:

![image](https://user-images.githubusercontent.com/1183923/183285467-5c09d937-9d37-47f8-9e74-6e87a1a62bb7.png)

In order to get the correct rendering I have to modify the `settings.json` file and save it modify it back again with the same font in order for `vscode` to take it into account. It's as if the font isn't taken into account when launching `vscode`.

- VS Code Version: `1.70.0`
- OS Version: `Debian testing - Kernel 5.18.0-3-amd64`

Thank you very much in advance for any help.

**Comment by Tyriar** [comment]
This is probably a race condition somewhere on our end, or Electron taking too long to load in the fonts. https://github.com/microsoft/vscode/issues/166701 should make the situation much better

**Comment by Tyriar** [comment]
I can't reproduce this, please let us know if you see if in 1.75+
