### ISSUE TITLE
copy html code have problem

### ISSUE THREAD

**Issue by everywan** [Microsoft/vscode#15745]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-sql|code-sql|0.0.3|
|vscode-instant-markdown|dbankier|0.1.0|
|python|donjayamanne|0.5.2|
|language-vscode-javascript-angular2|nwallace|0.0.11|

---

Steps to Reproduce:

1.打开html文档（从新浪微博拿下来的页面）
2.源码中的js代码复制不能自由选定

**Comment by jrieken** [comment]
@everywan Please report issues in English
