### ISSUE TITLE
Add a command to "fully" collapse a tree item (maybe expand too)

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#157410]
Refs: #92176
Split out from https://github.com/microsoft/vscode/issues/92176#issuecomment-1207281028

Can we a new command `list.collapseAllTo` (or something along those lines) to fully collapse the current item (e.g. deep collapse)?

We currently have `list.collapseAll` here:

https://github.com/Microsoft/vscode/blob/4b0d6f3bbcd9630d97a0622e2ed41af29054183b/src/vs/workbench/browser/actions/listCommands.ts#L291-L307

Which calls `collapseAll` here: https://github.com/Microsoft/vscode/blob/ca8c68b380e2a131f4003d188e60b93d81a601b7/src/vs/base/browser/ui/tree/abstractTree.ts#L1608-L1610

And it looks like `this.model.setCollapsed` takes a "rootRef", now I don't know if you could "root" the collapse all to any item (or if it *has* to be a root one), but if you could, it should be pretty simple to get the "active" item and collapse all to that point.

The benefit of a command, is that users could set a keyboard shortcut to it for use on any tree -- just like `list.collapseAll` today. I would personally would want to bind the current `Ctrl+LeftArrow` (for `list.collapseAll`) to use the new `list.collapseAllTo`.

Related it would also be great if there were an opposite `list.expandFrom` so that you could have `Ctrl+LeftArrow` to fully collapse an item, and `Ctrl+RightArrow` to expand it to some depth (maybe 2 or 3 by default, but could be passed to the command).

/cc @joaomoreno

**Comment by BamBamboozled** [comment]
Taking a look at this (if that's okay)!

**Comment by joaomoreno** [comment]
### Verification

1. Open a directory with folders several layers deep, for example `code path/to/your/vscode/repo`.
2. Open the Keyboard Shortcut panel (by default, `Cmd-K Cmd-S` or `Ctrl-K Ctrl-S`). Assign a shortcut to `list.collapseAllToFocus` (an option without collisions is `Alt-V` or `Opt-V`).
3. In the file sidebar on the left, expand a directory tree until it's several layers deep.
4. Select a folder near the top level but not at the top level of your tree (either with arrow keys or by double clicking) and press the shortcut you assigned `list.collapseAll` to.
    - Confirm that the directory is collapsed and stays collapsed.
    - Confirm that re-running the command does not toggle the collapsed status of the directory.
    - Confirm that when you reopen the directory by clicking it, its children remain recursively collapsed.
