### ISSUE TITLE
Terminal overlaps context menu if context menu is called in Peek editor

### ISSUE THREAD

**Issue by riskoviv** [microsoft/vscode#157431]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: Windows 10 Pro 21H2

Steps to Reproduce:

1. Open some .js file, for instance
2. Right-click on any identifier -> Peek -> Peek references
3. Open any terminal on the panel view on window's bottom _(the issue occurs with any terminal, I used git bash, powershell, command prompt)_
4. Scroll file so peeked editor is close to the terminal (if not yet) or shrink vscode window
5. In peeked editor right-click anywhere to show context menu
6. Context menu will be overlapped by terminal as in example below. Also as you can see in this example context menu's last option is visible below terminal
![image](https://user-images.githubusercontent.com/44531490/183290000-165aacc4-1d58-4df5-b66e-cafe0458612d.png)

**Comment by gjsjohnmurray** [comment]
You are talking about [Peeks](https://code.visualstudio.com/Docs/editor/editingevolved#_peek), not [CodeLenses](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup).

**Comment by riskoviv** [comment]
> You are talking about [Peeks](https://code.visualstudio.com/Docs/editor/editingevolved#_peek), not [CodeLenses](https://code.visualstudio.com/blogs/2017/02/12/code-lens-roundup).

Yes, of course, thank you, I just confused one with the other

**Comment by riskoviv** [comment]
I just found another issue #146638 that describes similar problem, so my issue may be a duplicate.
