### ISSUE TITLE
Visual Studio Code not highlighting #if.. in C

### ISSUE THREAD

**Issue by skybank00** [microsoft/vscode#157458]
Type: <b>Bug</b>

"#if 0//" >>> OK, but "if0    //" >> not highlighting

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
monokai-charcoal-high-contrast|74t|3.4.0
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.15.19
vscode-language-pack-ko|MS-|1.70.8030922
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
hexeditor|ms-|1.9.8
LiveServer|rit|5.7.5
vscode-autohotkey|sle|0.2.2
cmake|twx|0.0.17
material-theme|zhu|3.15.2

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by RedCMD** [comment]
I would have thought `if0` is just a variable?
and `#if0` is invalid

Should make report to https://github.com/jeff-hykin/better-cpp-syntax
@jeff-hykin

**Comment by alexr00** [comment]
Thanks @RedCMD! 

@skybank00 we get our C syntax highlighting grammar from https://github.com/jeff-hykin/better-cpp-syntax. I've copied the issue there: https://github.com/jeff-hykin/better-cpp-syntax/issues/602
