### ISSUE TITLE
Clicking stick headers should provide some context above and highlight the resulting destination

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157443]
Current behavior:

![Recording 2022-08-07 at 11 26 34](https://user-images.githubusercontent.com/2193314/183305615-3df709d7-cae7-4fce-b179-b7430e838e5d.gif)

I expect it to work just like ctrl+clicking a symbol, where we highlight the result briefly and scroll it to ~25% down the viewport so there's some context.

![Recording 2022-08-07 at 11 27 44](https://user-images.githubusercontent.com/2193314/183305663-a85174e3-ce05-4f28-8f2f-89d9b4efb675.gif)

**Comment by alexdima** [comment]
The current behavior helps with clicking/interacting with the line. The line scrolls in such a way that it positions itself under the mouse cursor. So a click can be immediately followed by a subsequent click, right click, etc.

**Comment by Tyriar** [comment]
I created an issue to support ctrl/cmd+click on the sticky header which would improve that further @alexdima

**Comment by alexdima** [comment]
Supporting only ctrl/cmd+click is arbitrary. I think there are two different ways to view sticky lines:
1. they are regular editor lines. That means all moue operations work like in the editor: clicking on them will move the cursor there, double clicking will do word selection, clicking the line number will select the line, cmd+click will jump to definition, alt+click will add a new cursor, right click will show the context menu on the symbol, etc.
2. they are like a vertical breadcrumb and clicking them reveals the line. This is what is currently implemented.

I don't think we should have a mixed mode, where clicking reveals the line in the center, but cmd+clicking jumps to definition like on a regular editor line. I think we should support all mouse gestures like a regular line or none.

**Comment by Tyriar** [comment]
I think 2 is what we want but the way I see it wrt mixed is if the user ctrl/cmd+clicks, it's pretty obvious what they want to do, so we should do it. This is one of the first things I tried to do with sticky headers intuitively. Here's the issue for that fyi https://github.com/microsoft/vscode/issues/157055
