### ISSUE TITLE
Improve error message for UTF-8 with BOM

### ISSUE THREAD

**Issue by g-jozsef** [microsoft/vscode#157411]
Type: <b>Bug</b>

I just updated my VSCode and (all of!!) my local JSON Schemas stopped working after with the following warning message
`˙'path/to/schemafile.json': Parse error at offset 0.(768)`

The message appears in the JSON file being edited, **not** in the schema!

The schemafile is specified in the settings.json:
```
    {
      "fileMatch": ["path/to/file/where/warning/is/shown"],
      "url": "./path/to/schemafile.json"
    },
```

Why do I think it's connected to the update? I restarted vscode and got the July update just now, after this, opening JSON files with schemas results in the above warning (& schemas not working).

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3950)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.19GB free)|
|Process Argv|--crash-reporter-id 6b5c6ce5-a5f8-45ad-9f33-fdd10cc4fbca|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.2
doxdocgen|csc|1.4.0
csharpier-vscode|csh|1.3.0
gitlens|eam|12.1.2
RunOnSave|eme|0.2.0
prettier-vscode|esb|9.5.0
vs-sharper|ese|0.2.0
go|gol|0.35.1
todo-tree|Gru|0.0.215
vscode-guid|hea|1.4.20
latex-workshop|Jam|8.28.0
csharpextensions|jch|1.3.1
better-cpp-syntax|jef|1.15.19
diff-tool|jin|0.0.1
vscode-graphviz|joa|0.0.6
cmake-language-support-vscode|jos|0.0.4
docomment|k--|0.1.31
chmod-command|lab|0.0.1
linecounter|lyz|0.2.7
git-graph|mhu|1.30.0
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
vscode-typescript-tslint-plugin|ms-|1.3.4
material-icon-theme|PKi|4.19.0
HOCON|sab|0.0.1
code-spell-checker|str|2.3.5
ayu|tea|1.0.5
cmake|twx|0.0.17
unity-debug|Uni|3.0.2
errorlens|use|3.6.0
intellicode-api-usage-examples|Vis|0.2.0
vscodeintellicode|Vis|1.2.22
vscodeintellicode-completions|Vis|1.0.16

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012cf:30540253

```

</details>

**Comment by aeschli** [comment]
The schema file seems to found, but could not be correctly read. Can open it in VS Code and see what the encoding is (in the status bar)?

**Comment by g-jozsef** [comment]
@aeschli Thanks for picking this up, the encoding is `UTF-8 with BOM`, I changed it back to `UTF-8` and the schemas are correctly working now!

I'm going to leave this issue open in case you find that something significant caused this or we might have a bit more accurate error message, otherwise please feel free to close it as resolved!

**Comment by aeschli** [comment]
To verify:
Create a a schema `foo.schema.json`, create it with URF8 with BOM
````
{
    "type": "object",
    "properties": {
        "foo": {
            "type": "boolean"
        }
    }
}
```
Create a JSON file `foo.json`:
```
{
    "$schema": "./foo.schema.json",
    
}
```
The error on the file should mention that UTFG 8 BOM is not allowed.

**Comment by lramos15** [comment]
I attempted to verify but didn't get any errors when having a schema with UTF8-BOM encoding to a UTF8 or UFT8-BOM JSON file

**Comment by TylerLeonhardt** [comment]
I got this:
![image](https://user-images.githubusercontent.com/2644648/192908723-a9db4495-3950-44d7-b172-f062d7ee3f9d.png)
my setup:
* in `/Users/tyleonha/Desktop/Untitled-1.json`:
```
{
    "type": "object",
    "properties": {
        "foo": {
            "type": "boolean"
        }
    }
}
```
Saved with UTF-8 with BOM
* in `/Users/tyleonha/Desktop/myFile.json`:
```
{
    "$schema": "/Users/tyleonha/Desktop/Untitled-1.json"
}
```

**Comment by TylerLeonhardt** [comment]
I will mark as verified but @lramos15 if that doesn't help maybe reopen.
