### ISSUE TITLE
Code Helper uses 30% or so CPU consistently

### ISSUE THREAD

**Issue by lukaso** [microsoft/vscode#157436]
Type: <b>Performance Issue</b>

Whenever I run VSCode, all the Code Helper processes consume between 20-40% CPU.

Disabling extensions doesn't have any effect. Removing extensions may fix tihngs for a short amount of time.

VS Code version: Code 1.70.0 (Universal) (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|.. --crash-reporter-id 7d85bcf2-332c-486b-a24c-61708fcac986|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	   147	 65724	code main
    0	    66	 65732	   gpu-process
    0	    33	 65733	   utility-network-service
    0	   213	 65735	   window (brew_2_build_gimp.sh — project)
   35	    98	 65740	   extensionHost
    0	    33	 65780	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/lukasoberhuber/.vscode/extensions/alexkrechik.cucumberautocomplete-2.15.2/node_modules/vscode-languageclient/lib/utils/electronForkStart /Users/lukasoberhuber/.vscode/extensions/alexkrechik.cucumberautocomplete-2.15.2/server/server.js --node-ipc --clientProcessId=65740
    0	     0	 65887	     /Users/lukasoberhuber/.vscode/extensions/ms-vscode.cpptools-1.11.4-darwin-arm64/bin/cpptools
    0	    33	 65891	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=65740
    0	    33	 65893	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/lukasoberhuber/.vscode/extensions/ms-python.vscode-pylance-2022.8.10/dist/server.bundle.js --cancellationReceive=file:6f0bc7fee9da4731f7b3a2643ee0f7600a89f8662c --node-ipc --clientProcessId=65740
    0	    33	 66120	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/lukasoberhuber/.vscode/extensions/streetsidesoftware.code-spell-checker-2.3.5/packages/_server/dist/main.js --node-ipc --clientProcessId=65740
    0	   131	 65744	   shared-process
    0	    33	 65745	     ptyHost
    0	     0	 66031	       /bin/zsh -l
    0	    33	 65747	     fileWatcher
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (brew_2_build_gimp.sh — project)
|    Folder (project): 201 files
|      File types: patch(99) sh(14) modules(9) md(7) rb(5) gitignore(3) log(3)
|                  diff(3) txt(2) doap(2)
|      Conf files: settings.json(1) makefile(1);
```

</details>
<details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.2
vscode-unison|Ben|0.4.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.3.2
markdown-emoji|bie|0.3.0
markdown-mermaid|bie|1.14.3
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-toggle-quotes|Bri|0.3.6
solargraph|cas|0.23.0
vscode-ruby-test-adapter|con|0.9.1
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.47.0
mustache|daw|1.1.1
xml|Dot|2.5.1
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.5.0
shell-format|fox|7.2.2
copilot|Git|1.38.6394
vscode-pull-request-github|Git|0.48.0
go|gol|0.35.1
ruby|gro|0.1.0
vscode-test-explorer|hbe|2.21.1
ruby-linter|hoo|1.0.0
rails-snippets|Hri|1.0.8
applescript|idl|0.21.1
better-cpp-syntax|jef|1.15.19
bats|jet|0.1.9
endwise|kai|1.5.1
vscode-rdbg|Koi|0.0.11
lldb-vscode|lan|0.2.3
autoconf|mae|0.1.0
ruby-symbols|mig|0.1.8
ruby-rubocop|mis|0.8.6
compare-folders|mos|0.22.2
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.4
cpptools-extension-pack|ms-|1.2.0
hexeditor|ms-|1.9.8
makefile-tools|ms-|0.5.0
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5679
vsliveshare-audio|ms-|0.1.91
ruby|reb|0.28.1
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.4.1
code-spell-checker|str|2.3.5
shellcheck|tim|0.19.6
pdf|tom|1.2.0
cmake|twx|0.0.17
vscode-lldb|vad|1.7.3
haml|vay|1.0.1
simple-ruby-erb|vor|0.2.1
vscode-ruby|win|0.28.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
hb751961:30541207
dsvsc012cf:30540253

```

</details>

**Comment by lukaso** [comment]
After having disabled all the extensions listed in `extensionHost`, the problem persists.

<details>

<Summary>High usage even though all listed extensions are disabled</Summary>

```
Version:          Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS Version:       Darwin arm64 21.6.0
CPUs:             Apple M1 Pro (10 x 24)
Memory (System):  16.00GB (0.08GB free)
Load (avg):       4, 4, 4
VM:               0%
Screen Reader:    no
Process Argv:     . --crash-reporter-id 7d85bcf2-332c-486b-a24c-61708fcac986
GPU Status:       2d_canvas:                              enabled
                  canvas_oop_rasterization:               disabled_off
                  direct_rendering_display_compositor:    disabled_off_ok
                  gpu_compositing:                        enabled
                  metal:                                  disabled_off
                  multiple_raster_threads:                enabled_on
                  opengl:                                 enabled_on
                  rasterization:                          enabled
                  raw_draw:                               disabled_off_ok
                  skia_renderer:                          enabled_on
                  video_decode:                           enabled
                  video_encode:                           enabled
                  webgl:                                  enabled
                  webgl2:                                 enabled

CPU %	Mem MB	   PID	Process
    0	   164	 14973	code main
    0	    66	 14986	   gpu-process
    0	    33	 14987	   utility-network-service
    0	   295	 14989	   window (brew_2_build_gimp.sh — project)
   23	   311	 14992	   extensionHost
    0	   147	 14993	   shared-process
    0	    49	 14994	     ptyHost
    0	     0	 15189	       /bin/zsh -l
    0	    49	 14995	     fileWatcher

Workspace Stats:
|  Window (brew_2_build_gimp.sh — project)
|    Folder (project): 201 files
|      File types: patch(99) sh(14) modules(9) md(7) rb(5) gitignore(3) log(3)
|                  diff(3) txt(2) doap(2)
|      Conf files: settings.json(1) makefile(1)
```

</details>

**Comment by lukaso** [comment]
I've determined that the culprit was Settings Sync extension. This was not showing  in the list of extensions, but was the problem.

**Comment by hezhongfeng** [comment]
@lukaso thanks for your help.
