### ISSUE TITLE
keyword alignas is not ricognized 

### ISSUE THREAD

**Issue by AlessandroScrem** [microsoft/vscode#157439]
![image](https://user-images.githubusercontent.com/48774358/183298462-095e0edc-398b-4643-849c-c7ed6a1181d0.png)

c++ Keyword alignas afert struct declaration is not ricognized , as Visualstudio can do.

Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

thanks

**Comment by RedCMD** [comment]
Should make report to https://github.com/jeff-hykin/better-cpp-syntax
@jeff-hykin

**Comment by alexr00** [comment]
Closing as upstream.
