### ISSUE TITLE
Ask the user if he wants to run tasks configured to run on folderOpen when a task with this configuration is found

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#157456]
We have this feature already in VSCode that asks us if we want to trust the folder we open to avoid running these tasks automatically. I tend to trust most folders because I don't usually go to check whether the project has any code anywhere that could be executed automatically or not and because the vast majority of them don't have anything like this. I think it would be much better if instead VSCode asked us permissions to execute any code automatically before executing it instead of just asking us if we trust the folder. This way you won't annoy the user asking him over and over again if he trust the folder. Instead you annoy him only when there is an actual reason to do so, such as when there is some code that will execute automatically.

**Comment by meganrogge** [comment]
what version of VS Code are you using?

**Comment by adriancuadrado** [comment]
@meganrogge

Version: 1.70.1 (user setup)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by meganrogge** [comment]
we only ask for trust when there's a reason to do so. Are you asking for more info about why trust is requested? cc @sbatten

**Comment by adriancuadrado** [comment]
@meganrogge No, I just wanted to have VSCode ask me if I want VSCode to run tasks that are programmed to run on folder open independently of whether I trust the folder or not.

**Comment by meganrogge** [comment]
Thanks, I understand your perspective. You can manage automated tasks with the new setting `task.allowAutomaticTasks`

**Comment by meganrogge** [comment]
Closing this as designed and the setting above should help you
