### ISSUE TITLE
Allow code to open directories in nautilus file manager

### ISSUE THREAD

**Issue by jamesbo13** [Microsoft/vscode#15741]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04

The nautilus file manager in Ubuntu and other GNOME-based Linux distros has a right click "Open with" option available for opening files and or directories. Currently, vscode supports open with for text files but not directories. Since I often open code repositories with vscode, it would be nice to be able to right click and select "open with ... " and then chose "code" to open a new instance of vscode using the directory.

Steps to Reproduce:

1. In nautilus, choose a folder. Right click and select "open with" submenu
2. Visual Studio Code is not listed in submenu.

If you repeat above with a plain text file, it works.

Nautilus uses the MimeType defined in the *.desktop file for associating applications with a particular file type. For directories, the desired mime-type is inode/directory. Simply changing the following line in code.desktop from

`MimeType=text/plain;`
to
`MimeType=text/plain;inode/directory;`

should suffice (though it may be necessary to log in/log out to have change take effect ... alternatively running update-desktop-database and restarting nautilus may work.

**Comment by Tyriar** [comment]
Thanks @jamesbo13 this works perfectly! You shouldn't need to log in/out for it to apply as we call `desktop-file-install` in the postinst step. This is coming in 1.8.0.

**Comment by aeschli** [comment]
verified on Elementary OS Freya

**Comment by jonasnordlund** [comment]
Just adding a note that I have turn off this feature because it's extremely invasive throughout at least Debian & Xfce. It's not just VS Code getting added to a context menu. Most commands opening a folder in Xfce now opens VS Code. For example, opening the folder of a downloaded photo in Firefox -> Opens in VS Code.

**Comment by Tyriar** [comment]
@jonasnordlund are you sure something else in your setup isn't affecting this? I believe the only change made here though was indicating to the OS that VS Code *can* open directories. You should be able to then configure which application is preferred for that mimetype (`inode/directory`).

What is the output of this command?

```
xdg-mime query default inode/directory
```

Mine points at `nautilus-folder-handler.desktop` which is why nautilus opens.

**Comment by jamesbo13** [comment]
[This post](http://unix.stackexchange.com/questions/296418/audacious-run-when-i-press-open-with-or-show-in-folder-in-xfce-in-arch-for-any-k) seems like a similar issue ... I am suspecting that xfce has made VS Code the default rather than an option (as Tyriar also hints at).

**Comment by Tyriar** [comment]
Thanks @jamesbo13. We certainly don't do anything to indicate VS Code would be the default so this seems like an issue in xfce to me.

**Comment by rzhao271** [comment]
Reopening after merging in https://github.com/microsoft/vscode/pull/209510

**Comment by Tyriar** [comment]
@rzhao271 I'd just make this out of scope now

**Comment by rzhao271** [comment]
I'd like to try running some xdg commands over debt week to see if manually modifying the mimeinfo file makes sense or not. If the xdg commands auto-sort the entries even after they've been manually modified, then I'll mark this issue out of scope.

**Comment by MaddyGuthridge** [comment]
Very frustrated by this feature being removed. After every update, I need to manually register `inode/directory` as a mime type for VS Code. Surely VS Code doesn't become the default file manager unless a system doesn't already have one installed? I know VS Code has never been set as the default for any desktop or WM I've ever used.
