### ISSUE TITLE
Ctrl/Cmd+Shift+C should opens workspace instead of the folder containing current file in terminal

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#15742]
- VSCode Version: 1.7.1 and 1.8 insiders
- OS Version: Windows and Mac OS X

Steps to Reproduce:

1. Open a workspace in VSCode, open a file in the workspace
2. Hit Cmd/Ctrl+Shift+C in the active editor

**Expected**: The folder containing the current file should open in the terminal/command prompt
**Actual**:      The workspace is opened in the terminal/command prompt

**Comment by ramya-rao-a** [comment]
Also, this keyboard shortcut is displayed in the context menu in the explorer only if the file is in the Opened Editors section.

![image](https://cloud.githubusercontent.com/assets/16890566/20449590/39542f4a-ad9f-11e6-8ab6-728c8e23e412.png)

![image](https://cloud.githubusercontent.com/assets/16890566/20449617/60fa4a84-ad9f-11e6-88e7-b211135dcf32.png)

**Comment by bpasero** [comment]
I have a fix for the missing keybinding. I leave this up as feature request to change the behaviour of the "Open New Terminal" action. I do not see a bug here but rather an explicit decision that the global "Open New Terminal" action opens the workspace. Changing this would mean breaking behaviour for everyone.

**Comment by bpasero** [comment]
Seems to work fine now.
