### ISSUE TITLE
Easy way to see new available settings 

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#15740]
It would be great if it was easy to discover what new settings were added to VSCode,

Right now I have about 1000 lines in `Deafult Settings` which equals more or less 333 settings.

The simplest probably would be to add "link" in top comments section or improve already existing `http://go.microsoft.com/fwlink/?LinkId=808995` with something like:

```js
//New options in VSCode 1.8-insiders:

    //Controls whether unsaved files are restored after relaunching. If this is enabled there will be no prompt to save when exiting the editor.
    "files.hotExit": false,
...

// New options in VSCode 1.7:
....

etc.
```

**Comment by sandy081** [comment]
@wallverb We have done considerable improvement in Settings area. So, I would ask you to try the latest insiders and share your experience. In short, main target is to make settings easily discoverable. 

Your idea of showing newly added settings is also a good one which we will think going forward.

**Comment by sandy081** [comment]
Assuming the current settings editor is helpful for this, closing it.
