### ISSUE TITLE
PHP constant parse error

### ISSUE THREAD

**Issue by Binaryify** [microsoft/vscode#157470]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.0 
- OS Version:MacOS 12.4 

PHP constants code have different scope and it cause it show two color

Steps to Reproduce:

1.
```PHP
<?php
echo date(DATE_RFC7231, time());
echo date(DATE_RFC1123, time());
```

![image](https://user-images.githubusercontent.com/12221718/183333610-63d7d86b-d172-420d-a94e-10c138af2a85.png)
<img width="707" alt="image" src="https://user-images.githubusercontent.com/12221718/183333626-10a5742b-0a4f-410b-abe0-4cced5b8c453.png">
<img width="738" alt="image" src="https://user-images.githubusercontent.com/12221718/183333632-f39a9498-43e6-499d-9e70-0e5f689cdada.png">

**Comment by Machou** [comment]
flag

**Comment by roblourens** [comment]
Filed upstream: https://github.com/atom/language-php/issues/459
