### ISSUE TITLE
Multiple cursor selection not working on VSCode mac

### ISSUE THREAD

**Issue by sam-w** [microsoft/vscode#157475]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: macOS Monterey 12.5 (21G72)

Steps to Reproduce:

Preparation:
1. Disable all extensions
2. Comment out ~/.../User/settings.json
3. Comment out <project>/.vsccode/settings.json
4. Comment out ~/Library/.../keybindings.json

Issue:
1. Use alt-click to attempt to add multiple cursors
Observe that multiple cursors do not appear, as expected.

Background:
I first noticed this issue appear in VSCode 1.69.x and assumed a bug had been introduced. Noone has reported similar issues since then, so I'm guessing it's something specific to my system. As you can see from my preparation steps though, I've disabled anything I can think of which might be causing the problem. Does anyone have other suggestions?

**Comment by alexdima** [comment]
I cannot reproduce, using `alt+click` to add multiple cursors works fine for me. Does this reproduce when using our [Insiders build](https://code.visualstudio.com/insiders/)?

**Comment by sam-w** [comment]
@alexdima yes indeed - still happens on 1.70.1 and on the insiders build. Makes sense that you can't reproduce - none of my colleagues can either. It must be something to do with my system then, but what 🤔?

Feel free to close this issue, but I'd appreciate any suggestions you might have on things which might be interfering with the multiple cursor behaviour.

**Comment by sam-w** [comment]
@alexdima found the problem - I use [Karabiner Elements](https://karabiner-elements.pqrs.org/) to map an external macropad. Quitting it restores the multiple cursor functionality in VSCode. Apologies for wasting your time - I'll take it up with them.

Just for your interest, I only have Karabiner set up to map numpad keys to function keys, nothing touches the Option key in macOS. I've also had the current Karabiner settings configured for well over a year with no issue. Something must have changed in an update somewhere 🤷🏻 .
