### ISSUE TITLE
vscode terminal error

### ISSUE THREAD

**Issue by xxc-zsz** [microsoft/vscode#157484]
Type: <b>Bug</b>

I used kotlin in vscode some time ago and everything was working fine and the code ran successfully. But today I opened vscode again to run the kotlin code and got the error 

```
kotlinc : The term 'kotlinc' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

![image](https://user-images.githubusercontent.com/108051416/183373423-a0362bc4-680e-40d0-ba29-67670cb18ae5.png)

I run the code using command in external cmd window and it runs successfully. But it always gives an error in vscode

![image](https://user-images.githubusercontent.com/108051416/183373537-6248ee8d-6f43-416f-9318-dfffc83eaec1.png)

I tried rolling back the vscode version to version 1.69.2 which was working fine some time ago, but the error persists.

After trying many times, I updated vscode version to 1.70 again. The code can run successfully again.

What is the problem?

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.17763
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v2 @ 2.60GHz (8 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (2.62GB free)|
|Process Argv|--crash-reporter-id eff41e00-9cca-49eb-98d7-445f3a050d2c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.47.0
code-runner|for|0.11.8
kotlin|fwc|0.2.26
vscode-sshfs|Kel|1.25.0
Kotlin|mat|1.7.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.22.1
vscode-language-pack-zh-hans|MS-|1.70.8030922
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
powershell|ms-|2022.7.2
indent-rainbow|ode|8.3.1
vscode-nuget-gallery|pat|0.0.24
material-icon-theme|PKi|4.19.0
fabric8-analytics|red|0.3.6
java|red|1.9.0
vscode-commons|red|0.0.6
vscode-xml|red|0.21.2022062916
my-code-actions|rio|1.0.0
vscode-pets|ton|1.11.0
vscodeintellicode|Vis|1.2.22
vscode-gradle|vsc|3.12.3
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0
vscode-spring-initializr|vsc|0.10.1
vscode-icons|vsc|11.15.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by meganrogge** [comment]
This type of issue usually means that program was missing from your `PATH`. You can verify this if you can reproduce it again by echoing the value of that

**Comment by xxc-zsz** [comment]
Of course I know it's a problem with the path. But I can run successfully in external cmd window and fail in vscode. Does this have nothing to do with vscode?
