### ISSUE TITLE
Webview find widget hangs around when retain context enabled

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode#157424]
1. Create webview editor with find widget & retain context:

```js
const panel = window.createWebviewPanel(
	'...',
	'...',
	ViewColumn.One,
	{
		enableScripts: true,
		enableFindWidget: true,
		retainContextWhenHidden: true,
		localResourceRoots: [Uri.joinPath(context.extensionUri, 'media')],
	},
);
```

2. Open webview editor
3. Open find widget
4. Switch to another tab
5. Webview find is still shown

---

- VS Code Version: 1.70.0 (user setup)
- OS Version: Windows_NT x64 10.0.19044

**Comment by MachineMitch21** [comment]
@mjbvz Hi Matt, I am trying to take a look at this, but I am unsure how to test my changes.  I noted the problems I was having in the PR I submitted that's linked to this Issue #161174.  It looks like showFind() and hideFind() were added, but the find widget code wasn't updated to use those when we're "retaining context"

**Comment by mjbvz** [comment]
Fixed by https://github.com/microsoft/vscode/pull/161174
