### ISSUE TITLE
the buttons in the upper left corner of the interface will appear incompletely displayed.

### ISSUE THREAD

**Issue by hzbd** [microsoft/vscode#157440]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 

        $ code --version
        1.70.0
        da76f93349a72022ca4670c1b84860304616aaa2
        x64

- OS Version:

        $ uname -a
        Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu- 
        6153.141.2.2~1/RELEASE_X86_64 x86_64
         
        macos version: 10.15.7 (catalina)

Steps to Reproduce:

**When full screen is enabled, occasionally the three buttons in the upper left corner of the interface will appear incompletely displayed. I don't know if this is a bug.**

<img width="365" alt="image" src="https://user-images.githubusercontent.com/3000843/183299300-97d4b6bf-2c74-4fe5-83b6-5154af1e11f5.png">

**Comment by hzbd** [comment]
I have upgraded to the latest version of vscode, but this problem occurs when I use it in full screen.

```
code --version
1.71.0
784b0177c56c607789f9638da7b6bf3230d47a8c
x64

MacBook Pro Version: 10.15.7 
```

![20220903-105341@2x](https://user-images.githubusercontent.com/3000843/188253204-4a126f3f-30cc-42bc-9104-f4f570f0de09.png)

**Comment by rzhao271** [comment]
Tracking in https://github.com/microsoft/vscode/issues/159862
