### ISSUE TITLE
Shell integration: bash and zsh don't serialize \n and ; characters

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157546]
Part of https://github.com/microsoft/vscode/issues/155639

Repro:

1. Open a bash or zsh session
2. Run:
  ```sh
  echo "a
  … b"
  ```
  ![image](https://github.com/microsoft/vscode/assets/2193314/95ce755b-cec5-4da1-8791-75923a088efa)
3. ctrl+alt+r to run recent command, select the last command, 🐛 it's run without the new line
  ![image](https://github.com/microsoft/vscode/assets/2193314/98e81851-3a68-422c-94e8-e3e4bb21ef53)

**Comment by Tyriar** [comment]
Code pointers to shell integration scripts:

https://github.com/microsoft/vscode/blob/d70a46b6bd65aade0248f900a6e67a85f1c2cde2/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
https://github.com/microsoft/vscode/blob/d70a46b6bd65aade0248f900a6e67a85f1c2cde2/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh

**Comment by Ditoo29** [comment]
Hey, I'm looking forward to work on this issue. Is it possible to be assigned to me? I'm new to open source and eager to contribute with my first PR.

**Comment by Ditoo29** [comment]
Hey, I've opened a pull request related to this issue! Let me know your feedback 😄
