### ISSUE TITLE
Shell integration: Support `OSC 9 ; 9 ; <cwd> ST` for CWD on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157569]
Part of #155639

We want to support other common shell integration sequences as fallbacks to the VS Code specific one (`OSC 633 ; P ; Cwd=<Cwd> ST`)

https://github.com/microsoft/vscode/blob/4f0b05cd9872132d0d59282326ef7f6ef2d7af08/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L338-L347

**Comment by connor4312** [comment]
@Tyriar can you add verification steps for this?

**Comment by Tyriar** [comment]
- Disable shell integration
- Run the following:

```
[Console]::Write("`e]633;A`a")
[Console]::Write("`e]633;B`a")
[Console]::Write("`e]633;C`a")
[Console]::Write("`e]633;D`a")
[Console]::Write("`e]9;9;C:\Test`a")
```

It should change the terminal tab's description to `C:\Test`.
