### ISSUE TITLE
Program to decimal to binary doesn't work properly in C++ language

### ISSUE THREAD

**Issue by gamertech1** [microsoft/vscode#157549]
The program doesn't show accurate result 
Example:
Binary of 5 
Expected 101
Actual 100
and also with other numbers
![Screenshot 2022-08-08 235427](https://user-images.githubusercontent.com/97377147/183487196-7957f8c2-1251-4318-bec7-81eff8b5beea.png)

**Comment by kartikver15gr8** [comment]
@gamertech1 
I would love to solve this issue 
Please give me access to that!

**Comment by gjsjohnmurray** [comment]
Please eliminate VS Code from the story. Use Notepad to create your C++program. Use a command shell to run the tools that turn this into an executable. Run it. If the result isn't what you expect, consult your C++ tutor.

**Comment by gamertech1** [comment]
> Please eliminate VS Code from the story. Use Notepad to create your C++program. Use a command shell to run the tools that turn this into an executable. Run it. If the result isn't what you expect, consult your C++ tutor.

Hey old folk I don't have time for that don't be a lazy person solve the issue and you should change your glasses because you don't see the program is right or maybe you should learn  how code properly

**Comment by gamertech1** [comment]
> /question

decimal to binary in c++

**Comment by yusancky** [comment]
@gamertech1 Line 10 should be `ans = bit + 10 * ans`.

**Comment by gamertech1** [comment]
> @gamertech1 Line 10 should be `ans = bit + 10 * ans`.

yes,you are also right but it show wrong ans  when I print mine but it work fine in other compiler

**Comment by yusancky** [comment]
> @gamertech1 : your code is wrong

I'm sorry to hear that. Could you please copy your code here?

**Comment by gamertech1** [comment]
> > @gamertech1 : your code is wrong
> 
> I'm sorry to hear that. Could you please copy your code here?

#include <iostream>
#include<cmath>
using namespace std;

void print(int n){
    int ans=0;
    int i=0;
    while(n!=0){
        int bit = n&1;
        ans= bit*pow(10,i)+ans;
        cout<<" elements ="<<ans<<endl;
        n=n/2;
        i++;
    }
  cout<<ans;
}
int main(){
  int n;
  cin>>n;
  print(n);

}

**Comment by yusancky** [comment]
Oh, I found out the reason now. You need not only [change the L10](https://github.com/microsoft/vscode/issues/157549#issuecomment-1209033896), but also reverse the number (e.g. $\texttt{1101} \gets \texttt{1011} $).

**Comment by gamertech1** [comment]
> Oh, I found out the reason now.
> 
> You need not only [change the L10](https://github.com/microsoft/vscode/issues/157549#issuecomment-1209033896), but also reverse the number (e.g. 1101←1011).
> 
> ```c++
> #include <algorithm>
> #include <cmath>
> #include <iostream>
> using namespace std;
> 
> int n,ans,i,bit;
> string ans_str;
> 
> int main(){
>     int n;
>     cin >> n;
>     while (n != 0){
>         bit = n & 1;
>         ans = 10 * ans + bit;
>         n >>= 1;
>         i++;
>     }
>     ans_str = to_string(ans);
>     reverse(ans_str.begin(),ans_str.end());
>     cout << ans_str;
>     return 0;
> }
> ```

Bro it is still wrong
