### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by grazza98** [microsoft/vscode#157538]
- Issue Type: `Bug`
- Extension Name: `typescript-language-features`
- Extension Version: `1.0.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.0`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 34,
		"activateCallTime": 20090,
		"activateResolvedTime": 7,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.typescript-language-features",
				"_lower": "vscode.typescript-language-features"
			},
			"activationEvent": "onLanguage:typescript"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

Hi, the activation time is over 20 seconds for this extention, i wondered if there is an issue with it or a setting i may need to change. Please could you advise?
Thank you

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by grazza98** [comment]
Hi Matt

Thanks for your prompt response!

I’ve tried those suggestions and it’s still slow. Perhaps it’s an issue with my machine/environment, I’ll do some further diagnostics and update the Issue later.

Thank you

**Comment by grazza98** [comment]
Hi Matt, sorry this is working ok now, we think it was a issue a package we had installed or a dependancy conflict. I'll close this issue.
Thanks for responding.
