### ISSUE TITLE
Screen Reader detection on Windows

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#157504]
We have changed how we detect screen readers on Windows. Everything should work as before, but we removed an outdated approach.

I have verified the following:
- mac behaves as before ✅ 
- NVDA on windows gets nicely detected ✅ 
- narrator, jaws and zoomtext on Windows do not get auto detected, but they also did not get auto detected with our VS Code stable. So it seems nothing changed here.

@zersiax @leonardder @Menelion @neurrone If you have time to try out [VS Code insiders](https://code.visualstudio.com/insiders/) with `"editor.accessibilitySupport"` set to `"auto"` and let us know the experience it would be really great.

Also, in general we are open to ideas on how to improve this "first detection" experience for use.

**Comment by leonardder** [comment]
Could you elaborate on what has changed under the hood? May be there's a branch/pr to look at?

**Comment by isidorn** [comment]
@leonardder On Windows, for legacy assistive clients that don't use the `IAccessible2` interface, Electron provides the `WM_GetObject` [hack](https://github.com/electron/electron/blob/37d93b04824d4f0151b36edb867209b53272457f/shell/browser/native_window_views_win.cc#L224-L252) and this one is prone to be false positive because of the `IsScreenReaderActive` check and puts chromium into accessibility mode when it is not the case.

To decrease the false positive rate we should remove the `WM_GetObject` hack from our electron builds.

The change is to just remove the `WM_GetObject` hack.

**Comment by leonardder** [comment]
Thanks, that makes sense.

It makes me wonder though how JAWS and Narrator are missed here. I'm 
pretty sure JAWS uses IA2 directly. Narrator will probably use the 
bridge that makes IA2 available to UIA clients.

**Comment by isidorn** [comment]
@leonardder I am not sure, it might be my machine, since even before this change JAWS does not get detected on my Win VM.

For now closing this issue as the planned work is done, and we will keep our eyes open for feedback in case there are regressions in detection which we do not expect to happen.

**Comment by bpasero** [comment]
Just fyi, I am not 100% sure if related, but I thought a few times in my Windows VM I was asked whether a screen reader is attached or not. I then tried to reproduce but could not. Are we maybe now thinking a screen reader might be attached when it is not in some more cases?

**Comment by isidorn** [comment]
@bpasero I do not think it is related, since previously we were doing the same detection we do now plus additional legacy detection. We just removed that additional legacy detection. Though it would be interesting to find out why we seem to think there is a screen reader on your vm.
@deepak1556 can correct me if I am wrong.

**Comment by deepak1556** [comment]
@isidorn the touch screen related issues are already closed as part of https://github.com/electron/electron/issues/7208, the left over would be https://github.com/microsoft/vscode/issues/107016 but I would keep this open since the root issue about slow scroll with accessibility enabled was a concern, although I should check if this is an issue with current insiders.
