### ISSUE TITLE
using ~20kbps up and down on files opened via sftp.. forever

### ISSUE THREAD

**Issue by G2G2G2G** [microsoft/vscode#157588]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: latest
- OS Version:
arch linux latest
Steps to Reproduce:

1. mount something via sftp (SSH FILE TRANSFER)
2. open it in vscode.. it uses a lot of data, assuming it's to check if the file still exists

**Comment by bpasero** [comment]
From the description the issue sounds like a setup / configuration problem outside of VSCode and nothing VSCode itself could fix.

VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

We also have a large community over at https://stackoverflow.com/questions/tagged/visual-studio-code to ask for advice.

Happy Coding!

**Comment by G2G2G2G** [comment]
chromium & electron don't do this. As I said it's most likely due to vscode's aggressive watching of the file's existence. You can manipulate the file on the server side and data usage will spike and vscode immediately notices. This should be tunable
