### ISSUE TITLE
Shell integration: Support `OSC 1337 ; CurrentDir=<cwd> ST` for updating cwd

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157567]
Part of #155639

We want to support other common shell integration sequences as fallbacks to the VS Code specific one (`OSC 633 ; P ; Cwd=<Cwd> ST`)

Code pointer:

https://github.com/microsoft/vscode/blob/4f0b05cd9872132d0d59282326ef7f6ef2d7af08/src/vs/platform/terminal/common/xterm/shellIntegrationAddon.ts#L338-L347

**Comment by babakks** [comment]
@Tyriar I'm taking this.

**Comment by Tyriar** [comment]
@babakks sounds good 👍

**Comment by babakks** [comment]
@Tyriar I've just submitted the PR. You can check it anytime you want.

**Comment by connor4312** [comment]
@Tyriar can you add verification steps for this?

**Comment by Tyriar** [comment]
- Disable shell integration
- Open pwsh 7+
- Run the following:

```
[Console]::Write("`e]633;A`a")
[Console]::Write("`e]633;B`a")
[Console]::Write("`e]633;C`a")
[Console]::Write("`e]633;D`a")
[Console]::Write("`e]1337;CurrentDir=/home/something`a")
```

It should change the terminal tab's description to `/home/something`.
