### ISSUE TITLE
Also enable dropping of images into notebook cells to create attachments

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#157577]
In addition to copy paste, I expect to be able to drag and drop to insert attachments in notebooks

**Comment by DonJayamanne** [comment]
This is what i tried
* Opened an ipynb file
* Created a markdown cell
* Attempted to drag a *.png file into this markdown cell from an external file explorer, didn't work, the image opened in VSC (as an image)
* Attempted to drag a *.png file into this markdown cell from an vsc  file explorer, didn't work, the image opened in VSC (as an image)

Basically I'm unable to drag and insert an image into a markdown cell.

**Comment by Yoyokrazy** [comment]
@DonJayamanne Just to double check, are you holding shift while dropping into the editor? That is what allows you to drop directly into the editor. If you are, I can double check if there are settings you need to enable, I think there might be one or two to use the drop provider.

**Comment by DonJayamanne** [comment]
Got it, thats what i missed, holding the `shift` key
