### ISSUE TITLE
Need better documentation for Edge debugger launch config

### ISSUE THREAD

**Issue by akrantz** [microsoft/vscode#157587]
Type: <b>Bug</b>

The documentation about the launch config for Edge browser/webview debugging seems to be outdated.

A warning is shown in launch.json that "type": "pwa-msedge" should be changed to "type": "msedge". However, when doing so, the "useWebView": "true" is no longer the correct syntax. I cannot find any documentation about how this should be changed.

This is the first place I expected to find the correct info:
https://code.visualstudio.com/docs/nodejs/browser-debugging

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900HK (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (10.14GB free)|
|Process Argv|. --crash-reporter-id dd73e8d0-a07f-4a5f-a386-bf7930a83f94|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
mustache|daw|1.1.1
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
prettier-vscode|esb|9.5.0
remotehub|Git|0.40.0
gzipdecompressor|Hyu|1.2.0
azure-pipelines|ms-|1.208.0
csharp|ms-|1.25.0
vscode-edge-devtools|ms-|2.1.0
remote-wsl|ms-|0.66.3
azure-account|ms-|0.11.1
cpptools|ms-|1.11.4
powershell|ms-|2022.7.2
remote-repositories|ms-|0.18.0
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5683
microsoft-office-add-in-debugger|mso|0.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
vscode-hexdump|sle|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by connor4312** [comment]
`"useWebView": "true"` is not the correct syntax for any debug type, it should be `true`, a boolean without quotes.

A complete set of options for all debug types can be found on https://github.com/microsoft/vscode-js-debug/blob/main/OPTIONS.md

**Comment by akrantz** [comment]
@connor4312 I wrote true in quotes in the bug report, but actually I was correctly try to use true as a boolean. The intellisense highlights it as needing to be an object. See the yellow squiggly underline in this picture:

![image](https://user-images.githubusercontent.com/741153/189700081-cdb26cbf-4633-4024-925c-a86324ea89b1.png)

**Comment by akrantz** [comment]
Can you reactivate this? I'm not sure how to do it.

**Comment by connor4312** [comment]
`useWebview: true` can only be applied to launch type configs since we must launch the application in a special way in order to attach to it.

**Comment by akrantz** [comment]
Yes, the Office app has a way to tell the WebView2 to enable debugging, so it sounds like this option is no longer needed.
