### ISSUE TITLE
Editor option for more strict highlighting

### ISSUE THREAD

**Issue by 5tr1k3r** [Microsoft/vscode#15759]
- VSCode Version: 1.7.1
- OS Version: Windows 7

I would like to ask for an **editor option** to enable stricter and/or more intelligent highlighting.

What I mean is this: whenever I click on any name or string, it attempts to highlight all occurences of it in the code. Usually it highlights too many of them:
![prav](https://cloud.githubusercontent.com/assets/11004850/20456649/8e41363a-ae9c-11e6-9504-f3e95205bde3.png)

I would like it to check for exact match, so in this example there would be no other occurences selected.

Also, would be good to disable this occurence highlighting for strings/parts of strings, so it doesn't do this:
![otr](https://cloud.githubusercontent.com/assets/11004850/20456689/28d312cc-ae9d-11e6-91fb-33228ecba8d8.png)

Hopefully it's within the scope of this feature request as well.

Thanks for all your work.

**Comment by justnonamenoname** [comment]
If you open search Ctrl+F it will check for exact match

But I suggest to add 2 options:
1) Enable highlight when you just click word
2) Enable highlight exact match (for just click and for select word) (default: true)

**Comment by rebornix** [comment]
It looks like a theme issue to me as we are using different css for exact match and partial match.

![screen shot 2016-11-28 at 3 27 08 pm](https://cloud.githubusercontent.com/assets/876920/20690387/29111b06-b57f-11e6-8986-ad145cfab919.png)

@5tr1k3r can you share which theme you are using then we can see what's blocking you here?

**Comment by alexandrudima** [comment]
No answer => closing
