### ISSUE TITLE
Crash reporting: include crash details 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15754]
Would it be possible to add the actual details of the crash dump to the crash page so that we get an idea what kind of crashes are happening? I think it would be cool if we could:
* group crashes by crash details
* try to find similarities from the telemetry in terms of user interaction

I guess depending on the OS we would need different strategies to extract the actual error from the dump, but I think we do this already for the crash telemetry drashboard if I remember correctly.

**Comment by ramya-rao-a** [comment]
We do have a process in place that has analyzed the dump and created human readable txt file.
I'll see how I can get that hooked up to the website with the crash details

**Comment by ramya-rao-a** [comment]
Moved to internal backlog
