### ISSUE TITLE
Keyboard shortcut to collapse active folder

### ISSUE THREAD

**Issue by nihirv** [microsoft/vscode#157501]
Sometimes I work with folders which have thousands of items in them. When I open a file in that folder in the editor, VS Code expands that folder by default. This causes Code to perform slowly (I guess because it's storing all these items in memory).

My current workflow is to scroll up, to where the folder containing the files is. But I normally have multiple related projects in my workspace which may sit above it. So I waste a few seconds scrolling up and then scrolling down to find where the folder is located

Some time would be saved if I could:
1. Have a keyboard shortcut which collapses the folder I'm currently in
2. Collapse folders from the bottom of the file list.

**Comment by IllusionMH** [comment]
If you have file selected you can just use <kbd>ArrowLeft</kbd> to navigate to folder and <kbd>ArrowLeft</kbd> again to close folder.

Is it what you are looking for in first item?

**Comment by nihirv** [comment]
> If you have file selected you can just use ArrowLeft to navigate to folder and ArrowLeft again to close folder.
> 
> Is it what you are looking for in first item?

Thanks for letting me know this! Surprised it didn't float through my mind. It's a good enough solution.
