### ISSUE TITLE
"Accept All" for merge conflicts does nothing

### ISSUE THREAD

**Issue by tcobbs-bentley** [microsoft/vscode#157574]
Type: <b>Bug</b>

The "Accept All" (Incoming/Current) functionality for merge conflicts no longer works AT ALL with the new "better" merge conflict UI. As far as I can tell, it now does absolutely nothing.

Steps:
1. Make changes to a local git repository.
2. Stash your changes.
3. Pull changes from the remote repository that conflict with the local changes.
4. git stash pop.
5. Right click on a file that has merge conflicts in the Source Control pane.
6. Select "Accept All Incoming" (or "Accept All Current")
7. Nothing happens

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (6.68GB free)|
|Process Argv|. --crash-reporter-id 5391ea14-4424-4673-8f75-c8dd4de77b0f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
alphabeta|Car|1.2.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
git-difftool|elp|0.1.0
LogFileHighlighter|emi|2.16.0
json-tools|eri|1.0.2
vscode-pull-request-github|Git|0.48.0
gitkraken-authentication|git|1.0.3
swift|Kas|0.2.0
syntax-project-pbxproj|mar|0.1.3
Kotlin|mat|1.7.1
xcodestrings|mhc|1.0.0
vscode-clang|mit|0.2.4
vscode-json5|mrm|1.0.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
cpptools|ms-|1.11.4
svg-preview|Sim|2.8.3
gitblame|wad|9.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012:30540252

```

</details>

**Comment by tcobbs-bentley** [comment]
This apparently only happens if the new merge UI is open for the file in question. So above step 5 above was a step that I missed: click on the file (which shows the merge UI).

**Comment by hediet** [comment]
@jrieken I'm certain this is because we remove the merge markers.

@lszomoru do you have ideas of how to address this?

**Comment by isidorn** [comment]
Dup of https://github.com/microsoft/vscode/issues/156230

**Comment by alexr00** [comment]
Marking as verified because the duplicate is verified.
