### ISSUE TITLE
JSON schema download is not working

### ISSUE THREAD

**Issue by iamyoki** [microsoft/vscode#157591]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0
- OS Version: Darwin arm64 20.6.0

## Bug
Vscode cannot automatically pull the corresponding schema from the schemastore for the json format file normally.

What's even weirder is that it can pull schema for `.babelrc`, but not other files those also in schemastore.

## Screenshot

My settings are correct

![image](https://user-images.githubusercontent.com/74389358/183553358-798311f9-daff-4e65-9d4d-e75a98685a34.png)

`graphql.config.json` file is defined in schemastore

![image](https://user-images.githubusercontent.com/74389358/183552738-0b991e0c-9814-47ad-bcdf-794704b72a49.png)

and it's not fetching the schema automatically, no [IntelliSense](https://code.visualstudio.com/docs/editor/intellisense) appears

![image](https://user-images.githubusercontent.com/74389358/183552819-cd90b4dd-bddb-43ee-8908-49ee519b6da3.png)

`.babelrc.json` is fine

![image](https://user-images.githubusercontent.com/74389358/183553126-4fdffc67-5a25-49f5-98ae-d87938b8b199.png)

and if manually associate schemas to JSON files in vscode settings is fine.

**Comment by aeschli** [comment]
Only YAML has that feature, but not JSON. The feature request is https://github.com/microsoft/vscode/issues/26289
