### ISSUE TITLE
Space 2 in the right bottom, but Ctrl+Alt+F(Fomat) will use 4 spaces to format code.

### ISSUE THREAD

**Issue by hstarorg** [Microsoft/vscode#15750]
- VSCode Version:1.7.1
- OS Version: Win10

Steps to Reproduce:

1. Set default indent to two spaces.
2. Open some file
3. Format code will use four spaces anytime

**Comment by DanTup** [comment]
I'm seeing this too. There are other cases I can find (#13563, #14899, #15329, #15422) but most are closed and/or say it's fixed in 1.7.

I'm editing a TypeScript file, the status bar shows "Tab Size: 4", but when I save or format, all my tabs get swapped with spaces :-(

**Comment by cihancil** [comment]
Exactly same issue.

After I set tab size again, edit some text and hit save it formats the code to correct indent. 

But still it is an issue.

**Comment by ramya-rao-a** [comment]
Does this happen on all file types or only typescript and javascript?

**Comment by DanTup** [comment]
I've only noticed it on TypeScript but I only currently use Code for TypeScript and Dart (it doesn't seem to happen in Dart but the formatting there is done via Dart Code + the Dart analysis server).

**Comment by HexWrench** [comment]
I have the same issue with .cs files. Changing the indentation from 3 spaces to 4 and back won't help.
Version 1.7.1, Win 10

Typescript and Javascript files work fine though (3 spaces indentation too).

**Comment by nilshartmann** [comment]
Same here with .jsx ("JavaScript React") files. Not all files are affected and the problem occurs only "sometimes". Sometimes also the formatting doesn't do anything at all (no changes after `Format Document`). In both cases restarting VCS seems to fix the problem (temporarily).

BTW I've set tab size in my settings.json in my project:
```
{
	"editor.tabSize": 2,
	"editor.detectIndentation": false
}
```

Code Version 1.7.1, MacOS 10.11.6

**Comment by kevintechie** [comment]
I'm experiencing the same problem with JSON files. The editor ignores personal and workspace settings and always formats with 4 spaces. I have also tried turning off detectIndentation, but it has no effect.

**Comment by kevintechie** [comment]
It turns out I had the js-css-html formatter pluging installed. It has its own configuration file that was overriding the one in VSCode.

**Comment by DanTup** [comment]
I don't have that plugin (I don't think I have any extensions at all except my own, Dart Code, which isn't activated when I'm working on it itself (it's written in TypeScript)) so I don't think it's isolated to that.

**Comment by hstarorg** [comment]
@ramya-rao-a  Only some file, include ``.js`` and ``.html``.

**Comment by jrieken** [comment]
This is a know TypeScript issue

**Comment by jrieken** [comment]
Please do not comment on this issue if you are seeing strange formatting behaviour with other languages then JS or TS.

**Comment by DanTup** [comment]
@jrieken Do you happen to know if there's a TypeScript issue we can subscribe to for updates on this? The only one I could find is https://github.com/Microsoft/TypeScript/issues/11199 but that was closed on 28th Sept but the last comment by @dbaeumer doesn't make it clear whether there was a fix yet.

**Comment by jrieken** [comment]
Should be this one: https://github.com/Microsoft/TypeScript/issues/12175
