### ISSUE TITLE
dropped support for relative paths in launch.json: UX problems 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1575]
When using old launch.jsons with relative paths, VSCode throws warnings into the users face.
I don't think that we can ship with this in January.
 
* the warning doesn't specify what attributes are affected, instead I see only the value that I will have to fix. Since the fix has already been applied to the value, it is difficult to locate the value in the lunch.json.
![2015-12-22 13-48-36](https://cloud.githubusercontent.com/assets/1898161/11955516/d9c076b6-a8b2-11e5-9eef-c71b204361b5.png)
 
* "${workspaceRoot}/." (and variants) look a bit silly. This is just "${workspaceRoot}"

* Sometimes it is impossible to figure out what to do. This launch.json looks OK but VSCode still complains that there is a "." somewhere. I couldn't spot the error: ![2015-12-22 13-40-40](https://cloud.githubusercontent.com/assets/1898161/11955595/80af0a32-a8b3-11e5-991d-26a406536855.png).

In general I think that we should not show warnings in this way because it is annoying and unhelpful. Instead we should show warning (later "error") squigglies in the json editor and offer intellisense to help the user inserting the missing "${workspaceRoot}" and have a "light bulb" action for fixing the whole launch json (as an example use the validation that got introduced for the Keyboard Shortcuts json).

If this is not possible for January, I suggest that we only fix our intellisense, templates, samples, etc. but show no warnings in the launch.json editor.

**Comment by isidorn** [comment]
:+1: we should improve this, I will look into how to make this experience nicer

**Comment by egamma** [comment]
Do we need to update the yo code generator as well?

**Comment by isidorn** [comment]
Yes, I will update it.

**Comment by isidorn** [comment]
All yo code generator templates use `${execPath}` for their program attributes, so no updates are needed.

**Comment by isidorn** [comment]
What exact keyboard shortcut validation are you refering to?
For inserting squiggles into the editor I am not even sure our json schema can support that. @aeschli is it possible to provide validation rules based on the value of a string field.

I propose that instead of having smart inteli-sense and light bulbs, we just automatically update the content of the launch.json for the user and show an info message such that he is aware of what is going on.

**Comment by weinand** [comment]
@isidorn switch your OS X keyboard layout on to Swiss German and open the keyboard shortcuts. Then scroll through the list and you will see that some bindings show adornments (he basically looks at the keyboard strings and validates that they can be produced by the current keyboard layout) . Alex demoed this in the standup last week. @aeschli is out of the loop because this is semantic validation which is not covered by the json schema. But since we need this anyway in the future we should support semantic validation and Alex has implemented it in a day or so...

**Comment by isidorn** [comment]
We are now showing a warning message in the launch.json if the user uses a relative paths and we do not spam with msgs on top of screen.
Please note that the shown message is not a good one since @aeschli has to start supporting `.errorMessage` field in schema which he plans to do this sprint.
