### ISSUE TITLE
Auto Keyword is not recognized in c++ program

### ISSUE THREAD

**Issue by anirudh18113** [microsoft/vscode#157696]
Below is the code that I am trying to run :

#include<bits/stdc++.h>
using namespace std;

int main(){
set<string> s;
int n;
cin>>n;
while(n--){
    string str;
    cin>>str;
    s.insert(str);
      }
for(auto value : s){
cout<< value<<endl;
} }

But this throws an error :

cde.cc: In function 'int main(

cde.cc:17:10: error: 'value' does not name a type
cde.cc:23:1: error: expected primary-expression before '}' token
cde.cc:23:1: error: expected ';' before '}' token
cde.cc:23:1: error: expected ';' before '}' token
}

![image](https://user-images.githubusercontent.com/83227172/183736544-d6e6756c-ed16-4a2b-b3a0-6d8c3446c296.png)

**Comment by sandy081** [comment]
Please file the issue against the c++ extension
