### ISSUE TITLE
Items from extensions in status bar do not react to clicks

### ISSUE THREAD

**Issue by nickkarandejs1** [microsoft/vscode#157613]
Type: <b>Bug</b>

Not sure how to reproduce.

After months of using the app, first spotted that "Git Blame" extension stopped handling the click in status bar.

Later found out that Go extension that shows "Go Update Available" stopped responding to clicks in status bar too.

Reinstalling the application did not help (all config was preserved)

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:39:20.716Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 31adfbee-f1dc-43f0-bcb6-67c83408cd68|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
go|gol|0.35.1
terraform|has|2.23.0
ruby|reb|0.28.1
vscode-lldb|vad|1.7.3
vim|vsc|1.23.2
gitblame|wad|9.0.1
vscode-ruby|win|0.28.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30541207
dsvsc012cf:30540253

```

</details>

**Comment by bpasero** [comment]
Sounds a bit like https://github.com/microsoft/vscode/issues/153831

Would need steps how to reproduce on my machine and any info you can provide on your setup and machine.

**Comment by bpasero** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
