### ISSUE TITLE
Explorer Open Editors Visible setting behavior changed

### ISSUE THREAD

**Issue by dottools** [microsoft/vscode#157668]
In Explorer Open Editors panel behavior changed for setting `explorer.openEditors.visible`. Now Open Editors panel cannot be resized smaller than `explorer.openEditors.visible` slots in size (defaulted to 9 it looks like) as it is now retreated as forced minimum visible slots to display even though `explorer.openEditors.minVisible` value set to 0.

This change was not noted in July 2022 (version 1.70) release notes.

Previously Open Editors panel could be resized smaller than `explorer.openEditors.visible` slots for well over three years that I have been using VSCode now.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Upgraded from 1.69.0 to 1.70.0.
- OS Version: Windows 10 21H2 64bit
- About Info:
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Have open 9 or more editors.
2. Try to resize Explorer: Open Editors panel less than `explorer.openEditors.visible` (value of 9) slots visible (I generally had it around 4).

**Comment by lramos15** [comment]
This code has not changed in the last iteration so I'm not positive that the behavior has changed.

You can set `explorer.openEditors.visible` is the smallest you can set the panel size to, so feel free to set that to 4 if you want the panel to be 4 editors. The `explorer.openEditors.minVisible` setting was added to prevent some of the dynamic resizing that occurs when you open and close editors. So for example if you set both values to 4 even with all editors closed 4 slots would always be present just blank.
