### ISSUE TITLE
Preview window not expanding to available space

### ISSUE THREAD

**Issue by bhosale-ajay** [Microsoft/vscode#15763]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. Create a markdown file
2. Open Preview
3. The preview window does not use full screen
4. The vertical scroll bar appears in middle
![markdownpreviewwindow](https://cloud.githubusercontent.com/assets/1799587/20457972/d72110f0-ae4c-11e6-9e41-0896e01eb1f5.png)

**Comment by NiekPas** [comment]
Can confirm, I am having the same problem.

OS: Windows 10 build 14393.447
VS Code version: 1.7.1

**Comment by mjbvz** [comment]
I believe this is another manifestation of #5745. We're tracking a bug on the electron side related to this, and also investigating some potential workarounds for the issue.
