### ISSUE TITLE
Check for update menu is missing when running as admin

### ISSUE THREAD

**Issue by IgorKozarchuk** [microsoft/vscode#157624]
Type: <b>Bug</b>

"Check for update" is missing if Settings and Help menus. Even after ucncheking "Enable Windows Background Updates" and setting Update Mode to manual is Settings.

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:16.462Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (9.52GB free)|
|Process Argv|--crash-reporter-id a61b9de4-afba-4ad2-a42d-cbfa86a6d05b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
select-highlight-minimap|mde|0.1.0
formate|Mik|1.2.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
sqlite-viewer|qwt|0.1.5

(3 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Are you running VS Code as an administrator? If so, please close all instances and start one without elevation.

**Comment by IgorKozarchuk** [comment]
Yes, I am using it as Admin. How do I start one without elevation?

**Comment by gjsjohnmurray** [comment]
On my Windows, starting an app from the Start button starts it unelected by default, and I have to take extra action if I want it to run as administrator.

**Comment by IgorKozarchuk** [comment]
I guess they just removed this menu item in v 1.70.0 of VS Code.

**Comment by gjsjohnmurray** [comment]
It is no longer offered on a user-type Windows install (as opposed to a system-type install) if you are running it as administrator. See #155631

**Comment by IgorKozarchuk** [comment]
OK, thanks!

**Comment by yume-chan** [comment]
Maybe it's better to show an error message and documentation link, instead of hiding the menu item. The number of issues related to this makes me feel running Code with Admin is pretty common.

**Comment by gjsjohnmurray** [comment]
> Maybe it's better to show an error message and documentation link, instead of hiding the menu item. The number of issues related to this makes me feel running Code with Admin is pretty common.

Pinging @joaomoreno

**Comment by b5414** [comment]
Same here

Am I get it right - if a user installed vscode using the user installer, so he will no longer be able to update unless he turns off admin rights or unless he installs the system version? // _Genius, some programmers have windows garbage disabled, like uac and admin's prompts, so there is no option to run programs without elevation,_ whatever..

---

System setup: https://code.visualstudio.com/docs/?dv=win64 

Just installed it with overwriting the user version, it solves the problem and saves the settings & extensions 👍

**Comment by wayaway-jtm** [comment]
Just want to add my unique case.

VS Code is installed in `C:\Program Files(x86)\`. Files in that directory can't be accessed without admin permission. Thus I can't install the update normally because it results in an `Access denied` error and I can't update as admin because yeah there's no way to check. It also doesn't automatically check when run in admin mode

**Comment by gjsjohnmurray** [comment]
@wayaway-jtm why did you install from the User Installer and not from the System Installer, which is listed at https://code.visualstudio.com/#alt-downloads ?

**Comment by gjsjohnmurray** [comment]
More info at https://code.visualstudio.com/docs/setup/windows#_user-setup-versus-system-setup

**Comment by zqy233** [comment]
thanks，this issuse helps me

**Comment by joaomoreno** [comment]
Using the User Setup, updates will be disabled if Code is launched as an Administrator. You need to launch as your usual user in order to get the background updates, so the permissions are respected.

Alternatively, you can install the System Setup.
