### ISSUE TITLE
 I'd like a shortcut to find open editors.

### ISSUE THREAD

**Issue by y-yasuaki** [Microsoft/vscode#15766]
- VSCode Version: 1.7.1
- OS Version: windows10

Currently, you can search all files with CTRL + P.
But I also want a shortcut that already has "edt" entered. It is used very often.
![alt](http://i.imgur.com/PdeSkO5.png)

**Comment by sprinkle131313** [comment]
Looks like the shortcut already exists:

```json
{ "key": "ctrl+k ctrl+p",         "command": "workbench.action.showAllEditors" }
```

You can also change the shortcut if you want as well.

**Comment by y-yasuaki** [comment]
thanks
