### ISSUE TITLE
Button: Improve outline focus affordance

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#157658]
I have been looking at experimenting with the outline so that it appears "inside" the button widget instead of "outside" of the button widget. Such an approach would enable us to have a consistent outline for the button and dropdown button widget.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/3372902/183694554-b345a35a-9921-4004-a787-c7b9a3619463.png">

<img width="251" alt="image" src="https://user-images.githubusercontent.com/3372902/183694406-1628db21-fe4d-4892-a245-f979c48fa73f.png">

This matches the button outline in the Fluent UI design system:

<img width="136" alt="image" src="https://user-images.githubusercontent.com/3372902/183695804-d8d1fd50-70fc-4cae-98b4-62876f5e6d93.png">

If you would like to try out the code, it is pushed to the `lszomoru/button-widget-outline` branch.

**Comment by lszomoru** [comment]
@daviddossett, any thoughts on this? Thank you!

**Comment by daviddossett** [comment]
Looks good to me! One thing to consider is whether we want to use a border radius for the outline now that we've done the same for the button itself.
