### ISSUE TITLE
When entering Japanese with an editor and breaking the line, the last typed characters are duplicated

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#15765]
- VSCode Version: 
1.8.0-insider (1.8.0-insider) 9b06d4392aeac3af2e9da58838a518bba325d23a
2016-11-18T08:57:27.676Z
code-insiders --disable-extensions

- OS Version: macOS Sierra 10.12.1（16B2657）

When entering Japanese with an editor and breaking the line, the last typed characters are duplicated.

Steps to Reproduce:

1. Enter Japanese characters in the Editor.
2. make a line break.

![japanese_input_issue_licecap](https://cloud.githubusercontent.com/assets/13635244/20458980/37038076-aef6-11e6-8a2c-f7dc8e2b20c8.gif)

**Comment by melito00** [comment]
I have same issue

**Comment by satokaz** [comment]
#16133

**Comment by bpasero** [comment]
@rebornix @alexandrudima fyi the recent Electron update backported a fix for this issue from Chrome, so I am not sure our workarounds are still needed. The related fix was https://github.com/electron/libchromiumcontent/pull/293
