### ISSUE TITLE
The integrated terminal can't input a character continuously by pressing and holding a key

### ISSUE THREAD

**Issue by heroperseus** [Microsoft/vscode#15768]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1.open up the integrated terminal
2.press and hold a key, it will only echo one character

**Comment by kaiwood** [comment]
@heroperseus See this answer, as you are on OSX too: http://stackoverflow.com/questions/39972335/how-do-i-press-and-hold-a-key-and-have-it-repeat-in-vscode

Not really VSCode related, it's a "feature" of the OS.

**Comment by Tyriar** [comment]
I reopened the upstream issue for this, I think it would be good to support since Mac's default Terminal does https://github.com/sourcelair/xterm.js/issues/265
