### ISSUE TITLE
on Print "123"

### ISSUE THREAD

**Issue by mackyo** [Microsoft/vscode#15762]
on "print "123" .. it says "Code language not supported or defined."

- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14965
- Extensions:

|Extension|Author|Version|
|---|---|---|
|tornado|abdelouahab|0.0.1|
|scanner-js-twain-wia-javascript-browser-scan|asprise-scan-ocr|2.0.2|
|python|donjayamanne|0.5.2|
|theme-nosferatu|dr-rockso|1.0.1|
|code-runner|formulahendry|0.5.1|
|docker-linter|henriiik|0.2.0|
|Python-autopep8|himanoa|1.0.2|
|emoji-code|idleberg|0.1.8|
|sendtomaya|ivancheung7|0.1.0|
|vscode-flake8|jaysonsantos|0.0.4|
|odoo-snippets|jeffery9|0.2.5|
|mayaport|JonMacey|1.0.0|
|MagicPython|magicstack|0.5.17|
|quicksnippet|mousetraps|0.0.1|
|theme-notepadplusplusremixed|sh4dow|1.0.2|
|python|tht13|0.2.3|
|pygame-snippets|tushortz|0.0.1|
|python-extended-snippets|tushortz|0.0.1|
|theme-wildlife|tushortz|0.0.3|

---

Steps to Reproduce:

1. Language python
2. Print "123"
3. Select all
4. right click "Run code"

**Comment by ramya-rao-a** [comment]
That error must be coming from which ever extension that is providing you the `Run code` feature.
Please log the issue in the repo for that extension.
