### ISSUE TITLE
Unable to write file 

### ISSUE THREAD

**Issue by ulugbek02** [microsoft/vscode#157683]
ADD ISSUE DESCRIPTION HERE

Unable to write file 'vscode-remote://codespaces+ulugbek02-code50-72005730-r449j4x6pfpj7x/home/ubuntu/.vscode-remote/data/Machine/settings.json' (Canceled: Canceled)

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
Embedder: codespaces

**Comment by bpasero** [comment]
This sounds like an issue for Codespaces. Please post issues here: http://aka.ms/ghcs-feedback
