### ISSUE TITLE
provideDefinition trigger twice when cmd + click

### ISSUE THREAD

**Issue by godkite** [microsoft/vscode#157629]
When implementing the `provideDefinition` api in the extension, I found that when I `hold down the cmd key` and then `click the mouse`, the `provideDefinition` method will be triggered **twice**. Once triggered by `cmd + hover`, and once by `cmd + click`.

Both events are necessary, but how do I differentiate them in code? I printed the three parameters of this method `callback` and there is no way to tell them apart.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/13809539/183642453-83fce10d-23fc-4e3b-8801-7f7466a58783.png">

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/13809539/183642378-ae34e8b8-f39b-44c8-b518-d80b1d3241ba.png">

So, I have two questions:
1. Is there a way to distinguish between the two behaviors?
2. Is there a way to configure it to fire only once?

**Comment by jrieken** [comment]
> but how do I differentiate them in code?

That sounds 🐟y. Why would you need to differentiate them?

**Comment by RedCMD** [comment]
> Why would you need to differentiate them?

I assume for performance reasons
as he wants to disable one of them (prob the 2nd)

**Comment by godkite** [comment]
> > but how do I differentiate them in code?
> 
> That sounds 🐟y. Why would you need to differentiate them?

If there is no distinction in my business logic, it is triggered twice, and there is a performance problem. Just f12 or right click works fine, but I can't expect all users to give up cmd+click

**Comment by jrieken** [comment]
> it is triggered twice, and there is a performance problem

I see calling twice isn't ideal but the unfortunate development reality is that we something need to call twice - once to know if you are over something "go-to-able" and second, on click, to see the actual results. Are you saying performance of go-to is generally a problem or just the repeated call?

**Comment by RedCMD** [comment]
Why can't the location be saved and reused when ctrl+clicking rather than reasking the extension for it?

or why doesn't vscode tell the extension if it's a hover or click event? 
then the extension can do its own thing, like temporary saving its output

**Comment by jrieken** [comment]
I hear you but it's not as easy as it sounds. Also note that we don't discard the information that's used for hovering, we (1) know that something is a clickable target and (2) show a preview-hover of the target. For us, go to definition is a fast operation and feedback from other language services back this assumption. I know that there are exceptions, like yours, but caching and reusing a result can be done on your level with much more confidence - you know all the factors that contribute to the result of go to definition.

**Comment by godkite** [comment]
so sad.....
