### ISSUE TITLE
VS Code pre-release does not reload code on restart of the debugger

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#157655]
### Discussed in https://github.com/microsoft/vscode-python/discussions/19600

<div type='discussions-op-text'>

<sup>Originally posted by **Emergency5779** August  1, 2022</sup>
All of a sudden VS Code (preview) does not load changes made to the code, when restarting the debugger.

I have spent hours googling, but I have come up empty-handed. Can anyone enlighten me on what is going on. Is there a new config option to set whether the code is to be reloaded when restarting the debugger?

If I stop the execution of the script, and run the debugger again, the latest code changes are loaded. </div>

**Comment by weinand** [comment]
@roblourens has something changed in Insiders that could explain this?

**Comment by kuroodo** [comment]
I hope it's related: Having the same issue on two different computers. Clicking restart would normally save everything and restarts with the changed code, but now it only restarts. Same with Java projects as well. Happens if I run both as Start Debugging and Run Without Debugging.
![plsfix](https://user-images.githubusercontent.com/9257713/183912770-d50697f0-4b7e-447e-8f52-b17f762ffca1.gif)

**Comment by collinmccarthy** [comment]
Same issue here, when debugging Python code clicking restart like @kuroodo shows used to auto-save my files now I need to manually save them before debugging it's a huge pain (mostly because I never had to do this so I never remember). 

```
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000
```

**Comment by weinand** [comment]
@roblourens 
I can easily reproduce this with js-debug in VS Code 1.70:
- use this hello.js:
  ```js
   setInterval(() => console.log("hello world"), 1000);
  ```
- and create a node.js launch config for hello.js
- set "Auto Save" setting to "off"
- make sure to have "Save Before Start" enabled
- F5
- modify the "hello world" string
- press Restart button

Observe:
hello.js is not saved; program logs the old message.

This problem does not occur in VS Code 1.70

**Comment by weinand** [comment]
Even reverting the fix for #149885 would be an option for the next recovery release because I suspect that more users are affected by the new problem than by #149885.

**Comment by Emergency5779** [comment]
Update: My release version just updated, and now doesn't autosave before debug either.

**Comment by rtetsoacrsf** [comment]
Work around
Install [multi-command extension](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)
Then replace the hotkey for Debug: Restart in keybindings.json, in my case:
```
    {
        "key": "ctrl+shift+f5",
        "command": "extension.multiCommand.execute",
        "args": 
        {
            "command": "multiCommand.restartDebug",
            "interval": 30,
            "sequence": [
                "saveAll",
                "workbench.action.debug.restart",
            ]
        }
    }
```

**Comment by andreamah** [comment]
@weinand could you verify that this is fixed in insiders?

**Comment by weinand** [comment]
@andreamah sure

**Comment by alon1samuel** [comment]
Thanks! Works for me as well
