### ISSUE TITLE
Provide a mechanism for using the legacy merge conflict view

### ISSUE THREAD

**Issue by kboucher** [microsoft/vscode#157691]
After the June (or July) 2022 update, the merge conflict view no longer looks like the one in the documentation: https://code.visualstudio.com/Docs/editor/versioncontrol#_merge-conflicts

<img width="701" alt="image" src="https://user-images.githubusercontent.com/1943568/183740654-a3ce2820-5f75-46e8-82b6-ebbcdb6d1ba5.png">

I do not like the new 3-way view at all. Is there any way to go back to the previous merge conflict view (as it appears in the above image and documentation link)?

I tried adding the following to settings.json, but the result was no diff decoration at all:

`"git.mergeEditor": false,`

**Comment by gjsjohnmurray** [comment]
Maybe you also need "diffEditor.codeLens": true

**Comment by kboucher** [comment]
@gjsjohnmurray Sadly, that does not seem to work.

**Comment by prettyGoo** [comment]
@kboucher I managed to rollback to the previous merge conflict view by setting `git.mergeEditor` to `false`. It looks like it's necessary to restart the app after updating `settings.json`

**Comment by SimonSchick** [comment]
This should be noted in the release blog article, I generally enjoy new features being introduced but this is a relatively strong UI change and will trip up many, this should've been opt-in.
