### ISSUE TITLE
How to setup Python to compile using Windows Bash

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#15764]
I want to use Ubuntu Environment for Compiling Python in Code, and i have installed Bash on Windows.

Is there any way i can compile the python using the Python in Bash and use all the libraries of python that are installed in Bash.
If anyone has JSON i can use, please share

**Comment by jrieken** [comment]
This isn't the right place to ask those questions

**Comment by csholmq** [comment]
@jrieken Why not? Looks to me like a more general question;

"How do I redirect calls to Bash on Windows instead of cmd.exe?". E.g a call to Python should use Bash on Windows when `"terminal.integrated.shell.windows": "C:/Windows/sysnative/bash.exe"`.
