### ISSUE TITLE
Don't preselect menu from mouse when open via keyboard

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#157694]
This is actually something that I run into quite often:

![recording](https://user-images.githubusercontent.com/2931520/183732000-4b816e17-b053-42dc-8557-8ec717dc9d92.gif)

I want to select the first item, but the mouse happens to be where the context menu shows.

**Comment by justschen** [comment]
@hediet Actually working on a PR for this at the moment! Will link this issue though since I hadn't created an issue for this yet.
