### ISSUE TITLE
DEbug console link detection

### ISSUE THREAD

**Issue by cedricnicolas** [Microsoft/vscode#15760]
- VSCode Version: Version 1.7.1 (1.7.1)
- OS Version: Mac os X 10,11,4

Steps to Reproduce:

1. Run mocha tests with configuration like that :
```
        {
            "name": "MesTests",
            "type": "node",
            "sourceMaps": true,
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/mocha/bin/_mocha",
            "stopOnEntry": false,
            "env": {
                "NODE_ENV": "unit_test",
                "MONGO_URI":"cedric:cedric01@localhost:27017/unitTests?authSource=add_gen",
                "DEBUG":"tests,renderer"
            },
            "cwd": "${workspaceRoot}/",
            "runtimeExecutable": null,
            "args": ["test/register.js"],
            "outDir": null
        },
```
2.  Debug output on error is like this :

```
     Uncaught TypeError: postInstance.setValue is not a function
      at model.newPostInstance (schemas/**customerSchema.ts:1870:22**)
      at schemas**/customerSchema.ts:1915:26**
      at tryCatcher (node_modules/**bluebird/js/release/util.js:16:23**)
```

I have put between **  the underlined lines, the first part is not. Result is it is not possible to click on the links. Maybe a bad setting on my side, but i was unable to find how to change that issue, all the first subdirectories of my project are not underlined, means not integrated in the link.

**Comment by isidorn** [comment]
@cedricnicolas can you please try this on the latest vscode insiders?
@felixfbecker has done some improvements on the debug repl link detection

**Comment by cedricnicolas** [comment]
Downloaded insiders, and tried again. There is a change, but still not working.

Output seems better as the full path is underlined :

` at model.getProductInstanceForProductId (/private/var/www/nodeApps/finamatic/schemas/customerSchema.ts:922:68)`

but when i click on the link i have an error message :

` File not found : (/private/var/www/nodeApps/finamatic/private/var/www/nodeApps/finamatic/schemas/customerSchema.ts`

in fact, seems the link is build with duplicate of my project home path (/private/var/www/nodeApps/finamatic/)

**Comment by felixfbecker** [comment]
@cedricnicolas That issue is described in #15464

**Comment by cedricnicolas** [comment]
Thanks felix !
I suppose I'll get it in next insider release ?

**Comment by isidorn** [comment]
Closing as dup

**Comment by cedricnicolas** [comment]
Sorry to open it again, but there is still a small issue. Now link is correctly underlined, but only for the first line :
![image](https://cloud.githubusercontent.com/assets/2274006/20794624/71c54eb2-b7cd-11e6-82b7-9a98fce0049b.png)

Following lines are not.. it would help to have all lines underlined...

**Comment by felixfbecker** [comment]
weird...

**Comment by gkTim** [comment]
Still not working in the current release. Should it work with the current release (1.9.1)?

**Comment by isidorn** [comment]
@gkTim no, it should not since this issue is still open. Will most probably be tackled in the march release

**Comment by izikl** [comment]
@isidorn when is the next release of VSCode that will include this fix? I am really looking forward for this feature. 😄

**Comment by isidorn** [comment]
@izikl this issue is still open and not on the immediate plan to be fixed

**Comment by felixfbecker** [comment]
This is one of the little things that really slows down productivity:

- test fails
- <kbd>Cmd</kbd>+<kbd>P</kbd>, search file shown in stack trace
- <kbd>Cmd</kbd>+<kbd>G</kbd>, go to line shown in stack trace

this was so much quicker when you were able to just click the links :(

**Comment by roblourens** [comment]
Verified - it looks like paths from internal node modules are now incorrectly handled as relative paths, but from the PR discussion it seems to be expected.

**Comment by michelkaporin** [comment]
@roblourens exactly. Blacklisting would mean that we have to either stat them or to have a set of all possible links from stack traces that are not discoverable, which is impossible to come up with due to variety of debug adapters.
