### ISSUE TITLE
(Request) Translucident minimap

### ISSUE THREAD

**Issue by Jonatandb** [microsoft/vscode#157674]
Hi! 🙋🏻‍♂️ I just want to suggest that, translucident minimap would allow us to see code behind minimap column (today that column hides code even when its not showing minified code).

Sample:
![image](https://user-images.githubusercontent.com/8082172/183711864-f196ae4f-a089-4bf8-b66a-1f91ef6193a4.png)

Thanks!

**Comment by vince-fugnitto** [comment]
@Jonatandb you should be able to set the `minimap.background` color in your `settings.json` to change the opacity:

For example:

```json
"workbench.colorCustomizations": {
    "minimap.background": "#1c1c1c3D"
},
```

![Screen Shot 2022-08-09 at 1 07 34 PM](https://user-images.githubusercontent.com/40359487/183714005-73ad27a3-cd7a-409c-9adb-215e22050fc5.png)
