### ISSUE TITLE
Cursor doesn't move in a redo operation

### ISSUE THREAD

**Issue by stkb** [Microsoft/vscode#15761]
- VSCode Version: 1.7.1
- OS Version: Win 10 AU 

1) Any text file, cursor positioned between the two 'l's of hello
<img width="400" alt="1" src="https://cloud.githubusercontent.com/assets/6125444/20457369/19c5fe24-ae8a-11e6-8d0c-3febcd29be6c.png">

2) Extension does an edit operation, eg `edit.insert(new vscode.Position(0, 0), "*")`. Cursor moves with the text as expected
<img width="400" alt="2" src="https://cloud.githubusercontent.com/assets/6125444/20457401/04d630e6-ae8b-11e6-87d6-93023d6584b4.png">

3) Ctrl+Z to undo, cursor moves back, as expected
<img width="400" alt="3" src="https://cloud.githubusercontent.com/assets/6125444/20457402/06442118-ae8b-11e6-9e29-92a124042cf8.png">

4) Ctrl+Y to redo, would expect cursor to move back to the same position as in 2), but it doesn't move 

<img width="400" alt="4" src="https://cloud.githubusercontent.com/assets/6125444/20457403/081280fc-ae8b-11e6-94a5-8e02f604f6dc.png">

**Comment by alexandrudima** [comment]
For verification:
* `package.json`:
```json
{
    "publisher": "alex",
    "name": "15761",
    "version": "0.0.0",
    "engines": {
        "vscode": "^1.0.0"
    },
    "activationEvents": ["*"],
    "contributes": {
        "commands": [
            {
                "command": "changeCursor",
                "title": "Change cursor"
            }
        ]
    },
    "main": "index.js"
}
```

* `index.js`:
```
const vscode = require('vscode');

exports.activate = function () {
    vscode.window.activeTextEditor.edit((editBuilder) => {
        editBuilder.insert(new vscode.Position(0, 0), "*");
    });
}
```
* Open a file with the contents `hello` and place the cursor between the two `l`s and reload.

**Comment by stkb** [comment]
Thanks!
