### ISSUE TITLE
The "Run Test at Cursor" should save the file and rediscover tests before executing

### ISSUE THREAD

**Issue by shaperilio** [microsoft/vscode#157656]
# Behaviour
The "Run Test at Cursor" command doesn't save the file first.

## Expected vs. Actual
Two notable things happen when this command is executed immediately after making changes to the test in which the cursor lies:
1. The changes you just made will not be executed. The file is saved, though, so if you repeat the command, they will be.
2. If this is the last test in the file, and you've added lines at the end of the file and the cursor is in one of the new lines, the test doesn't execute at all because "the cursor is not inside a test".

The command should save the file and wait for test discovery before checking the cursor position to decide which test to run.

(I am using Pytest)

## Steps to reproduce:

1. Create a test file and create two unit tests. Save the file.
2. Add a new line in the top unit test. Do not save the file. Put the cusor on the first line of the test and execute the command. This new line will not have run.
3. Execute the command again. The line you added will be included.
4. Go to the second unit test in the file. Add a line. Do not save the file. Leave the cursor on that line. Execute the command. You'll observe the test does not execute at all.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.10
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Default

languageServer: "Pylance"

linting
• flake8Enabled: true
• flake8Path: "<placeholder>"
• mypyEnabled: true
• mypyPath: "<placeholder>"

formatting
• autopep8Args: "<placeholder>"
• autopep8Path: "<placeholder>"

testing
• pytestEnabled: true

```

</p>
</details>

**Comment by connor4312** [comment]
I've now implemented this. At the time tests are run, we'll save the file, and then afterwards wait for any tests whose UI is equal to or a parent of the file to have `busy = false`. This means you'll want to set the busy state in `onWillSaveTextDocument` so that business is set prior to that happening.

**Comment by connor4312** [comment]
Verification steps:

1. Apply the following diff to the `test-provider-sample` of the vscode-extension-samples-repo

	<details>

	```diff
	diff --git a/test-provider-sample/src/extension.ts b/test-provider-sample/src/extension.ts
	index 815e314..5ce9cdc 100644
	--- a/test-provider-sample/src/extension.ts
	+++ b/test-provider-sample/src/extension.ts
	@@ -104,7 +104,7 @@ export async function activate(context: vscode.ExtensionContext) {
			}
		};
	
	-	function updateNodeForDocument(e: vscode.TextDocument) {
	+	async function updateNodeForDocument(e: vscode.TextDocument) {
			if (e.uri.scheme !== 'file') {
				return;
			}
	@@ -114,7 +114,10 @@ export async function activate(context: vscode.ExtensionContext) {
			}
	
			const { file, data } = getOrCreateFile(ctrl, e.uri);
	+		file.busy = true;
	+		await new Promise(r => setTimeout(r, 1000));
			data.updateFromContents(ctrl, e.getText(), file);
	+		file.busy = false;
		}
	
		for (const document of vscode.workspace.textDocuments) {
	@@ -123,7 +126,7 @@ export async function activate(context: vscode.ExtensionContext) {
	
		context.subscriptions.push(
			vscode.workspace.onDidOpenTextDocument(updateNodeForDocument),
	-		vscode.workspace.onDidChangeTextDocument(e => updateNodeForDocument(e.document)),
	+		vscode.workspace.onWillSaveTextDocument(e => updateNodeForDocument(e.document)),
		);
	}
	```

	</details>

2. Run the extension.
3. Add a new test case to the bottom of one of the `test.md` files, and _do not save it_.
4. No play button should show up beside the test yet
5. Run the "Run Test at Cursor" command
6. Verify the new test case gets a play button and runs
