### ISSUE TITLE
In markdown ligature works for `<-` only if it is backtick quoted.

### ISSUE THREAD

**Issue by colinfang** [Microsoft/vscode#15767]
- VSCode Version: 1.7.1
- OS Version: Windows 10

    "editor.fontFamily": "'Inziu Iosevka CL'",
    "editor.fontLigatures": true

In `markdown` language, `<-` forms a ligature only if it is quoted by backtick. (I guess it is the color that triggers ligature?) However `->` works well.

![capture](https://cloud.githubusercontent.com/assets/1499555/20459467/28f9256c-aeba-11e6-8b80-78d048a185f8.PNG)

@be5invis

**Comment by be5invis** [comment]
It is completely correct, because in MarkDown, `<-` SHOULD be two tokens, `<` for HTML tag bracket, `-` for tag name.

**Comment by colinfang** [comment]
Thx.
I don't know ligature is applied after tokenization.
