### ISSUE TITLE
Title bar does not appear in one of the windows after restarting

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#157605]
On Mac Arm64

- I have two windows opened in full screen mode
- I restarted VS Code after update
- One of the windows does not go into full screen (This used to be the case always)
🐛 For this window title bar is not appearing. Title bar appears for other windows I opened after.

![Screenshot 2022-08-09 at 08 59 15](https://user-images.githubusercontent.com/10746682/183584764-7e3140b8-59d2-4c76-b02d-5566431460c3.png)

**Comment by bpasero** [comment]
Likely the same as https://github.com/microsoft/vscode/issues/150790

Note that Electron does not allow us to restore multiple fullscreen windows: https://github.com/electron/electron/issues/34367
