### ISSUE TITLE
Latest VSCode Insiders build (1.71.0) doesn't run under Windows 7

### ISSUE THREAD

**Issue by incastea** [microsoft/vscode#157616]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0 Insiders (Aug. 8)
- OS Version: Windows 7 (6.1.7601)

VSCode does not start under Windows 7. Code-Insiders.exe process briefly appears in Processes in Task Manager and quits without any response.

Steps to Reproduce:

1. Install latest Insiders build.
2. Run VSCode

Latest 1.70.0 Insiders build runs without problems.

**Comment by deepak1556** [comment]
VSCode desktop is not officially supported on Windows 7 https://code.visualstudio.com/docs/supporting/requirements#_platforms

You can you use our [web version](https://code.visualstudio.com/docs/editor/vscode-web) https://vscode.dev/ as alternative on this system.

**Comment by fireattack** [comment]
Should probably note it somewhere in the changelog

**Comment by lorand-horvath** [comment]
Worth mentioning https://github.com/microsoft/vscode/issues/158362
The issue with VSCode 1.71 not starting is Electron 19, which seems to be broken on Windows 7 according to https://github.com/electron/electron/issues/35219
