### ISSUE TITLE
Copilot suggestions sometimes block IntelliSense suggestions

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/vscode#157675]
Type: <b>Bug</b>

Open any notebook (I am using [this one](https://gist.github.com/crazy4pi314/9460a817b8008976841cb79ebf7e1399) with just pandas in a basic Anaconda env `conda install -c pandas`) and execute/type things until you are at a point when IntelliSense can make suggestions. This isn't 100% reproducible, but about half the time if the code cell is started by accepting a Copilot suggestion, or you start typing the current Copilot suggestion, IntelliSense in the expression won't pop up. If I disable entirely Copilot, then there are not problems with the IntelliSense prompts.

This seems more like a conflict in the behaviors than a bug, i.e. if I am typing an expression which is part of the current Copilot suggestion (but am actually looking for something else) can I still get IntelliSense? If I stop for a min or in any other way manage to dismiss the Copilot suggestion, the IntelliSense suggestions come back.

**With Copilot disabled globally**
<img width="913" alt="image" src="https://user-images.githubusercontent.com/6486256/183710248-9c61ad08-1e02-4927-9011-6849da45974b.png">

*With Copilot enabled**

<img width="913" alt="image" src="https://user-images.githubusercontent.com/6486256/183711335-ee8e39b3-9cb6-42ae-9b76-97cd2d0413e5.png">

VS Code version: Code - Insiders 1.70.0-insider (1cd90cceddf3c413673963ab6f154d2ff294b17c, 2022-07-15T05:16:39.110Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (7.40GB free)|
|Process Argv|--crash-reporter-id e36d14e7-7164-42ea-b99a-e94bf6f3ac5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot-nightly|Git|1.39.6439
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.13.12171009
vscode-pylance|ms-|2022.8.12
data-wrangler|ms-|0.0.336
jupyter|ms-|2022.8.1002231050
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by MarcusOtter** [comment]
Also happens for me, for example in TypeScript

Intellisense
![image](https://user-images.githubusercontent.com/35617441/184748305-a9925498-10b6-49fd-9cf6-0c503c7bf688.png)

Copilot (no intellisense)
![image](https://user-images.githubusercontent.com/35617441/184748389-382c490b-7a40-4d87-a05c-98e3b1c4e808.png)

**Comment by kimwlsgh33** [comment]
i have same problem ..

**Comment by jkaye2012** [comment]
Is there any workaround to this issue in the mean time?

**Comment by alekkowalczyk** [comment]
Sometimes pressing `Esc` and writing the `.` again helps as a workaround (VSCode+TypeScript), but definately not ideal.

**Comment by jkaye2012** [comment]
I turned off inline editor suggestions and use Alt-\ to trigger Copilot
when I want it. Also not ideal, but a fine workaround for the time being.

**Comment by jonahkagan** [comment]
Another good workaround is to type `Ctrl+Space` when a Copilot suggestion comes up, which seems to cancel the Copilot suggestion and show Intellisense instead (credit: https://github.com/community/community/discussions/9430#discussioncomment-4395354)

**Comment by isidorn** [comment]
Just to let you know that we have pushed a fix so that now suggest widget is NOT suppressed by default.
So this should work better with VS Code Insiders from tomorrow. And this will be included in next stable (start of September). Try it out and let us know what you think. Thank you!
