### ISSUE TITLE
Use tab to select next snippet in complete list 

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#15769]
- VSCode Version: Code - Insiders 1.8.0-insider (9b06d4392aeac3af2e9da58838a518bba325d23a, 2016-11-18T08:59:27.025Z)
- OS Version: Darwin x64 16.3.0

In current version, when we are typing, we can only use `arrow up` or `arrow down` to select one snippet in complete list. (Not complete it, meanwhile use tab to complete it). 
So i suggest provide an option to use `tab` as a key to select next snippet in complete list.

**Comment by jrieken** [comment]
>select one snippet in complete list

@leaxoy Do you mean the IntelliSense widget that shows *inside* the editor or the snippet-selection that shows as quick pick box over the editor?

**Comment by leaxoy** [comment]
IntelliSense widget.
And we should have an option to select next IntelliSense item use `tab` as an alternative choise.

**Comment by jrieken** [comment]
You can configure that using this snippet in `keybinding.json`

```
{ "key": "tab",                  "command": "selectNextSuggestion",
                                     "when": "editorTextFocus && suggestWidgetMultipleSuggestions && suggestWidgetVisible" },
{ "key": "tab",                   "command": "-acceptSelectedSuggestion"},
```

**Comment by leaxoy** [comment]
Great!!! Thank you!
