### ISSUE TITLE
Sometimes the terminal loads with the wrong color set

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157715]
I've seen this a few times recently (gpu on) when switching to an already existing terminal

<img width="1009" alt="Screen Shot 2022-08-09 at 2 32 25 pm" src="https://user-images.githubusercontent.com/2193314/183765619-324af568-0732-4e83-8d2b-c65a2e98c8a6.png">

**Comment by Tyriar** [comment]
This might be causing the problems
<img width="583" alt="Screen Shot 2022-08-09 at 3 25 16 pm" src="https://user-images.githubusercontent.com/2193314/183772505-eac0addd-e241-464d-b78f-9f74563511f5.png">

**Comment by Tyriar** [comment]
It's not clear how `extended` can be undefined: https://github.com/xtermjs/xterm.js/blob/face97d012fd1abbc543f11ed32334f264065fc7/addons/xterm-addon-webgl/src/WebglRenderer.ts#L404

**Comment by meganrogge** [comment]
I looked as well and don't know how that's possible

**Comment by Tyriar** [comment]
Haven't seen this since
