### ISSUE TITLE
Can't select multiple notebook cells at once

### ISSUE THREAD

**Issue by crazy4pi314** [microsoft/vscode#157712]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

It seems like I cannot select more than one notebook cell, either by clicking on the left padding/gutter next to the cell or by trying to select text in multiple cells with my mouse. In Jupyter Classic (and I think Lab) you can hold shift and select multiple cells with the left padding/gutter and then use actions like cut/paste/move up/move down on the group. 

Repro:
Open any notebook with multiple cells, and click on the left padding next to the cell. While holding shift, try and select more cells.

### VS Code Version

Version: 1.70.0 (user setup) Commit: da76f93349a72022ca4670c1b84860304616aaa2 Date: 2022-08-04T04:38:16.462Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.22000

### Jupyter Extension Version

v2022.7.1002181843

### Coding Language and Runtime Version

Python 3.7.12

### Language Extension Version (if applicable)

v2022.12.0

### Anaconda Version (if applicable)

conda 4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
shift+click should work to select multiple cells. What happens when you do that?

**Comment by crazy4pi314** [comment]
> shift+click should work to select multiple cells. What happens when you do that?

Ohhhhhhhhhhh I just realized what was happening. The selection works, but the UI only shows the selection frame around the last one clicked. There is no indication that other cells were still selected 🤦‍♀️ So probably not a bug, but UI feedback 👍
