### ISSUE TITLE
Creating and running a shell task results in errors in output

### ISSUE THREAD

**Issue by gnikit** [microsoft/vscode#157756]
Type: <b>Bug</b>

I believe this is a resurface of https://github.com/microsoft/vscode/issues/95876

Again, the task runs to completion it just pollutes the Tasks Output. Am I missing something?
For me it triggers with the relatively simple snippet

```typescript
export async function shellTask(command: string, args: string[], name: string) {
  const task = new vscode.Task(
    { type: 'shell' },
    vscode.TaskScope.Workspace,
    name,
    'Modern Fortran',
    new vscode.ShellExecution(command, args)
  );
  // (<vscode.Task>task).definition = { type: 'shell', command: command };
  const execution = await vscode.tasks.executeTask(task);
  return await new Promise<void>((resolve, reject) => {
    const disposable = vscode.tasks.onDidEndTask(e => {
      if (e.execution === execution) {
        disposable.dispose();
        resolve();
      } else reject();
    });
  });
}
```

The only way to supress the Tasks output is by uncommenting the `(<vscode.Task>task)...` line

Tasks output is again similar to issue [95876](https://github.com/microsoft/vscode/issues/95876)

```log
Error: the task 'Modern Fortran: pip' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,python3,-m,pip,install,--user,--upgrade,fortls,",
    "problemMatcher": [],
    "label": "Modern Fortran: pip"
}
```

VS Code version: Code - Insiders 1.71.0-insider (b0895f9fcc5b49587a2b187a92bbe6d7efae35fa, 2022-08-08T05:19:04.908Z)
OS version: Linux x64 5.4.0-122-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 3447)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.21GB (20.56GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6298fe7a-017f-49f3-97ec-87f419e63426|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by github0null** [comment]
Same problem:

- VSCode Version: `1.72.2`

My Code:

```ts
const task = new vscode.Task({ type: 'shell', command: commandLine }, vscode.TaskScope.Workspace,
                title, 'eide', new vscode.ShellExecution(commandLine, shellOption), []);
task.group = vscode.TaskGroup.Build;
task.isBackground = false;
task.presentationOptions = { echo: true, focus: false, clear: true };
vscode.tasks.executeTask(task);
```

Task works but have output tell me error:

```log
Error: the task 'eide: build:Release' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,\"unify_builder -p xxxxxxx",",
    "group": "build",
    "problemMatcher": [],
    "label": "eide: build:Release"
}
```

**Comment by bwateratmsft** [comment]
The Docker extension uses tasks built on-the-fly like this extensively and we see these error messages too.

**Comment by adriancostin6** [comment]
VS Code Version: 

- 1.77.1
- b7886d7461186a5eac768481578c1d7ca80e2d21
- x64

This affects me as well, the following snippet produces similar errors to the ones described above:

```ts
await tasks.executeTask(
        new Task(
            { type: 'shell' },
            TaskScope.Workspace,
            'Start GDB server',
            'debugger',
             new ShellExecution(
                `\"${resolveGdbExecutable(profile, 'gdbserver').fsPath}\"`.concat(
                    ` localhost:${port} --attach ${processId}`
                ), {
                    executable: 'cmd',
                    shellArgs: ['/d', '/c'],
                }
    )));
```
```
Error: the task 'debugger: Start GDB server' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,\"c:\\Users\\adrian\\common\\tools\\mingw32\\bin\\gdbserver.exe\" localhost:2002 --attach 19360,",
    "problemMatcher": [],
    "label": "debugger: Start GDB server"
}
Error: the task 'debugger: Start GDB server' neither specifies a command nor a dependsOn property. The task will be ignored. Its definition is:
{
    "type": "shell",
    "id": "shell,\"c:\\Users\\adrian\\common\\tools\\mingw32\\bin\\gdbserver.exe\" localhost:2002 --attach 19360,",
    "problemMatcher": [],
    "label": "debugger: Start GDB server"
}
```
As you can see, in this case the errors double up, further cluttering the "Output " window. Would appreciate this bug being addressed. Let me know if I can help :)

**Comment by edwinbradford** [comment]
As someone who's not a developer by profession this issue cost me a lot of time trying to find out if it was my error or something else. It would be helpful if the error message could at least be changed to clarify the cause for those who aren't advanced enough to track it down to a bug with the Docker extension.
