### ISSUE TITLE
Allow to delete multiple entries in `Terminal: Run Recent Command...`

### ISSUE THREAD

**Issue by kidonng** [microsoft/vscode#157726]
Now if one try to delete an entry in `Terminal: Run Recent Command...`, the panel is then closed automatically:

https://user-images.githubusercontent.com/44045911/183799731-6c473f5a-f1a2-43bf-8b78-1f69cb9926e0.mov

This is very frustrating. Every other history panel (e.g. browsers) allows you to perform delete action as much as you like. Also, it does not distinguish from actually entering the command if the terminal is already open.

I suggest the panel stay open after deleting an entry, which is more conventional and intutive.

**Comment by meganrogge** [comment]
I noticed this too. I can fix it while working on #154388
