### ISSUE TITLE
Auto-quoting of context keys prevents removal of keybindings via UI

### ISSUE THREAD

**Issue by pfitzseb** [microsoft/vscode#157751]
Does this issue occur when all extensions are disabled?: Probably, but hard to reproduce

- VS Code Version: 1.70.0 and insiders
- OS Version: Linux x64 5.18.16-1-MANJARO

Steps to Reproduce:

1. Install an extension that contributes a keybinding with a `when` clause containing an `foo in extension.bar` check (e.g. the Julia extension).
2. Go to the Keyboard Shortcuts UI via `workbench.action.openGlobalKeybindings`
3. Right click -> remove the keybinding.
4. VS Code tries to remove the keybinding by inserting  a new one into the `User/keybindings.json`, where the command is prefixed with a minus and, crucially, all complex context keys are quoted:
```
[
    {
        "key": "ctrl+enter",
        "command": "-extension.my-command",
        "when": "foo in 'extension.bar'"
    }
]
```
5. This doesn't actually remove the keybinding from the UI or prevent VS Code from resolving it.
6. Remove the single quotes around `'extension.bar'`
7. The keybinding is properly removed from the UI and cannot be used anymore, as expected.

As far as I can tell, this behaviour is specific to `in` clauses; it's also hard to repro this without an extension because user-supplied keybindings are just removed outright from keybindings.json instead of adding an additional negated entry.

![Peek 2022-08-10 11-53](https://user-images.githubusercontent.com/6735977/183872750-e4118c6e-5c95-442f-8a63-2c3441175b9c.gif)

**Comment by alexr00** [comment]
The quotes are still in the `when`, but the keybinding is effectively removed.
