### ISSUE TITLE
doubling of accented foreign characters

### ISSUE THREAD

**Issue by alexisargyris** [Microsoft/vscode#15772]
- VSCode Version: Code - Insiders 1.8.0-insider (9b06d4392aeac3af2e9da58838a518bba325d23a, 2016-11-18T08:59:27.025Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.1.10|
|vscode-eslint|dbaeumer|1.1.0|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|wordcount|ms-vscode|0.1.0|

---

Steps to Reproduce:

1. on a mac switch to the greek keyboard
2. press the two-key combination to produce the accented version of any vowel of the greek alphabet (e.g. ά, έ, ί, ό, ή, ύ, ώ)
3. you get the expected accented character
4. now press any other character or space
5. you get another copy of the accented character, followed by the character you just entered

This behaviour first appeared very recently (no more than a week, I would say) and renders VS Code nearly unusable. I'll try to check if it is also happens on Windows.

Thanks in advance for your attention

**Comment by alexisargyris** [comment]
The Windows version (1.8.0-insider) doesn't seem to have this problem.

**Comment by rebornix** [comment]
Dup of #15765.
