### ISSUE TITLE
MX Master mouses horizontal scroll to work properly

### ISSUE THREAD

**Issue by TamirCode** [microsoft/vscode#157741]
when I horizontally scroll with my MX Master 3 mouse, only the first scroll jump works and then i can't scroll.

This is not only a VSCode issue, but many other applications as discussed here in this closed issue https://github.com/microsoft/vscode/issues/56964

The way I currently get around this is by running VSCode as administrator, then the scrolling works fine. Other proposals including changing logitech options to zoomin/zoomout instead of scrolling do not work.

So maybe VSCode can do something on their part to allow horizontal scrolling? It seems Notepad++ have done something on their side to fix the issue despite it probably being a logitech problem. Please consider:
https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10490

**Comment by alexdima** [comment]
Duplicate of #84136
