### ISSUE TITLE
[sticky scroll] distinguish the sticky lines better

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#157732]
I love this new feature, I just started to try it and it seems useful.

I thought maybe sticky lines should have some sort of visual distinction. Right now, they look the same as other lines. When smooth scrolling (f.e. inertial scroll with animation) it is obvious. When performing actions that trigger single-frame scroll (no animation) we might not immediately realize lines at the top are not actually at that position.

What could be the solution? Maybe highlight the line number of the sticky line a little, or maybe the whole line. Or maybe a subtle underline below the last stick line.

**Comment by gjsjohnmurray** [comment]
See https://github.com/microsoft/vscode/issues/157185#issuecomment-1207288806

**Comment by alexdima** [comment]
Let's continue discussion in #157185
