### ISSUE TITLE
Merge conflict highlighting

### ISSUE THREAD

**Issue by rohennes** [microsoft/vscode#157767]
Type: <b>Bug</b>

Hi

I am using VS Code 1.7. I opened a local git branch and rebased against the upstream master. There was a merge conflict on a file that I needed to manually edit. I opened the file, I only see the raw merge text, e.g.
<<<<<<<<<<<<<<<< HEAD

some content

>>>>>>>>>>>>>>>> >> acd698fdhjf (<branch commit message>)

Usually I see highlighting with the open to ACCEPT INCOMING CHANGE or ACCEPT CURRENT CHANGE with highlighting to help visually understand the merge conflicts. Now there are no options in the UI to accepting and incoming change, and there is no highlight, just the raw text as described in above sample. 

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:48.541Z)
OS version: Linux x64 4.18.0-372.16.1.el8_6.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|30.86GB (17.51GB free)|
|Process Argv|--crash-reporter-id f0703bbc-94a3-4094-a039-6798b619e8d2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
vale-server|err|0.15.1
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

**Comment by mentero** [comment]
I think this is the same case I reported a moment ago https://github.com/microsoft/vscode/issues/157766

In the recent release they've enabled 3-way editor by default but it only works whey you open a file via `source control` sidebar. Otherwise it just shows raw file. You can turn off `merge editor` in settings at get the old behaviour

**Comment by gjsjohnmurray** [comment]
What is your `diffEditor.codeLens` setting?

**Comment by rohennes** [comment]
> What is your `diffEditor.codeLens` setting?

False

**Comment by gjsjohnmurray** [comment]
Try setting it to true, then see if the familiar codelenses appear.

**Comment by michael-etzkorn** [comment]
> Try setting it to true, then see if the familiar codelenses appear.


Why the change to disable this by default? it's very useful to have the codelenses

**Comment by gjsjohnmurray** [comment]
> Why the change to disable this by default? it's very useful to have the codelenses

pinging @hediet

**Comment by mastern2k3** [comment]
> I think this is the same case I reported a moment ago #157766
> 
> In the recent release they've enabled 3-way editor by default but it only works whey you open a file via `source control` sidebar. Otherwise it just shows raw file. You can turn off `merge editor` in settings and get the old behaviour

This works, but why is this mutually exclusive?
Cant there be a 3-way editor **and** display highlighting for merge-conflict markup?
