### ISSUE TITLE
can't ctrl+v to console on win10 onscreen keyboard 

### ISSUE THREAD

**Issue by pmlopes** [Microsoft/vscode#15771]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|java|redhat|0.0.6|

---

Steps to Reproduce:

1. Copy some text 
2. Open terminal
3. Try to paste ctrl+v
4. Console shows ’^V’

**Comment by MeetmeLeave** [comment]
You should use Ctrl+Shift+V instead, as this is a normal Win console behavior.

**Comment by pmlopes** [comment]
I see this is a limitation of the on-screen keyboard I cannot press both Shift + Ctrl they are mutually exclusive. I noticed that it applies to all applications.

**Comment by Tyriar** [comment]
@pmlopes interesting, I guess that will be fixed when https://github.com/Microsoft/vscode/issues/8818 gets done though. In the meantime ctrl+ins should copy and shift+ins should paste now.
