### ISSUE TITLE
Visual Studio Code Disappeared on My Windows 10 Machine

### ISSUE THREAD

**Issue by JoelGross** [microsoft/vscode#157799]
I tried clicking the Visual Studio Code shortcut this morning like usual and it said the object the shortcut points to was moved or deleted.

I went trying to find the program in Program Files, but it's not there. I did a search for it in C: drive and nothing came up. 

In Add or Remove Programs, I see it still being installed. 

I have no idea what happened, but I did see a couple of users with similar issues from past years that had it happen after some sort of automatic update. What should I do?

I am using Windows 10.

**Comment by JoelGross** [comment]
Status? Do you need more information? I am stuck and need to work on my project. What should I do?

**Comment by JoelGross** [comment]
Thank you Insiders works!

**Comment by joaomoreno** [comment]
Very likely related to #147408. Please reinstall stable as well.
