### ISSUE TITLE
Diff options & highlighting not working when merging or rebasing

### ISSUE THREAD

**Issue by gigamesh** [microsoft/vscode#157717]
Type: <b>Bug</b>

This is happening when I try to merge or rebase:

<img width="604" alt="image" src="https://user-images.githubusercontent.com/32403632/183768582-de5769f0-5587-4885-9c5c-53f67ee65bac.png">

I'm on the latest version of VSCode. It's happening in Solidity files, but I've had this working in Solidity before. 

VS Code version: Code 1.70.0 (da76f93349a72022ca4670c1b84860304616aaa2, 2022-08-04T04:38:55.829Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 10|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id 4e0316d9-1572-4836-8bf8-be937943453b|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (64)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
vscode-apollo|apo|1.19.11
vscode-zipfs|arc|3.0.0
markdown-mermaid|bie|1.14.3
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.2.0
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.5.0
vscode-commands|fab|1.4.3
vscode-terminals|fab|1.13.0
flow-for-vscode|flo|2.2.0
auto-close-tag|for|0.5.14
copilot|Git|1.39.6432
vscode-pull-request-github|Git|0.48.0
gitpod-desktop|git|0.0.49
go|gol|0.35.1
gc-excelviewer|Gra|4.2.55
vscode-graphql-syntax|Gra|1.0.4
githd|hui|2.3.3
rest-client|hum|0.25.0
mysql-syntax|jak|1.3.1
vscode-styled-components|jpo|1.7.0
jsdoc|lll|1.0.3
git-graph|mhu|1.30.0
theme-monokai-pro-vscode|mon|1.1.20
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.10
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5683
debugger-for-chrome|msj|4.13.0
color-highlight|nau|2.5.0
hardhat-solidity|Nom|0.4.6
vetur|oct|0.36.0
prisma|Pri|4.2.0
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
px-to-rem|sai|1.3.1
code-settings-sync|Sha|3.4.3
svelte-vscode|sve|105.20.0
language-stylus|sys|1.16.0
graphviz-interactive-preview|tin|0.3.1
vscode-solidity-language|tin|0.0.6
lorem-ipsum|Tyr|1.3.1
vscode-icons|vsc|11.15.0
codedox|wig|1.3.1
fig|wit|0.0.6
ReactSnippets|xab|2.4.0
material-theme|zhu|3.15.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

**Comment by gjsjohnmurray** [comment]
What are your settings for `git.mergeEditor` and `diffEditor.codeLens`?

**Comment by abdulkareemnalband** [comment]
I'm also having same issue 
 `git.mergeEditor` and `diffEditor.codeLens` are no set to any value , aka they have default value

**Comment by YueLu0116** [comment]
Same issue here
```
Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19042
```

**Comment by gjsjohnmurray** [comment]
To return to the pre-1.70 behaviour you need to set git.mergeEditor false and maybe also set diffEditor.codeLens true. Some people have also reported that they needed to restart VS Code after making the changes.

**Comment by fschrempf** [comment]
> To return to the pre-1.70 behaviour you need to set git.mergeEditor false and maybe also set diffEditor.codeLens true. Some people have also reported that they needed to restart VS Code after making the changes.

Same issue here. It stopped working after a recent update. Disabling `git.mergeEditor` to false seems to fix the issue.

**Comment by gigamesh** [comment]
> Disabling git.mergeEditor seems to fix the issue.

Same! thanks @gjsjohnmurray
