### ISSUE TITLE
Dark+ theme not render the self-defined struct in Go

### ISSUE THREAD

**Issue by Alfons0329** [microsoft/vscode#157739]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

![image](https://user-images.githubusercontent.com/22470089/183835724-d1bab09c-bc08-470c-8783-a12a8db61ec9.png)

Somehow my VSCode Dark+ theme does not render the text properly.
(it used to be OK a few days ago, the self-defined struct (userData) should be emerald green (same as the "string" below)  and the var name (in) should be light blue in the function argument)

![image](https://user-images.githubusercontent.com/22470089/183836367-24b8508e-f674-4732-893a-73ccd714034a.png)

This issue seems to happen in C++ as well.

Thank you for the help.

**Comment by aeschli** [comment]
The go grammar does not seem to tokenize that correctly
![image](https://user-images.githubusercontent.com/6461412/186876737-35a18640-22ec-430f-923b-5389045a80b2.png)
```
type userData struct {
	name string
	id int
}
```

**Comment by aeschli** [comment]
I created https://github.com/jeff-hykin/better-go-syntax/issues/37
