### ISSUE TITLE
Main menu auto-closes after it's opened with a new VS Code instance

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#157710]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.71.0-insider (user setup)
Commit: bcb31b9cfb2261ddbabfb73defed9ae78680b9b2
Date: 2022-08-09T16:47:56.993Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
- OS Version:

Steps to Reproduce:

1. Open a new VS Code instance.
2. Click/expand main menu option like File->Open Recent immediately after the UI appears.

Bug: The main menu collapses a few seconds later before I'm able to use it.

Expected. The menu would either not collapse or not be available to expand until it's in a state where it won't collapse.

Using Ctrl+R to expand the recently used UI is a workaround for the File->Open Recent case, i.e. that UI doesn't collapse.

**Comment by bpasero** [comment]
I also notice that and believe it is related to us updating the menu with commands and enablement but ideally that would not cause the menu to close.
