### ISSUE TITLE
Copy lines (Up/Down) doesn't work on Ubuntu for me !

### ISSUE THREAD

**Issue by ahmed-taj** [Microsoft/vscode#15773]
Hey,

I can't get copy lines (Up/Down) functionality to work on Ubuntu, I don't know exactly why. Obviously, I tried `ctrl+shift+alt+down/up` but nothing happens!

It does work when I change the key mapping (i.e. `shift+alt-down/up`), though.

May be it worth mentioning that I have installed Ubuntu few days ago, so any setting or something are on its default.

- VSCode Version: 1.7.1
- OS Version: Ubuntu 16.04.1

Steps to Reproduce:

1.  Just have some text in VS Code.
2.  Press `ctrl+shift+alt+down` or `ctrl+shift+alt+up`.

**Comment by soulomoon** [comment]
Possibly conflict with some other keyboard Shortcut in your Os, 
it was what actually happens to me on fedora 24 while the gnome short cut for changing workspace of current running window is `ctrl+shift+alt+up` and `ctrl+shift+alt+down` 
then I was able to use this shortcut after I change my shortcut key for my window environment

**Comment by alexandrudima** [comment]
@ahmed-taj Most likely the OS is eating up that key combination. Please check if we even receive these keybindings by following the steps explained in https://github.com/Microsoft/vscode/issues/15967#issuecomment-263832863

**Comment by ahmed-taj** [comment]
@soulomoon  @alexandrudima you are absolutely right, Ubuntu uses `ctrl+shift+alt+arrow keys` for moving a window between workspaces.

![selection_001](https://cloud.githubusercontent.com/assets/12673605/20792816/ed6f0632-b7d4-11e6-940a-eb59bb0dbb53.png)


@alexandrudima we don't receive the key-bindings, but `ctrl+shift+alt` !

For now I changed the keys `shift+alt+arrow keys` and it works fine (I'm already familiar with VS code for windows shortcuts).

Regards.
