### ISSUE TITLE
Alt+Space behavior

### ISSUE THREAD

**Issue by AKrasheninnikov** [microsoft/vscode#157796]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: any
- OS Version: any Windows

This may be a rare case, but please consider:

1. Application window my by some unknown reason be hidden, collapsed into few-by-few pixels, removed almost outside the viewport
2. Usually, Alt+Space would easily resolve the issue, allowing to maximize the window and drag it to a better position. 

You now say that "Mouse position is used to determine the behavior when triggering with Alt+Space, so the custom menu will appear if it sits on top of the title bar." - this might mean that the trick above would not work. Maybe this behavior could be applied also to cases when the cursor is outside the window or when the window has just received focus by Alt+[Shift]+Tab or Win+[Shift]+Tab, too? Please discuss this internally and decide how to proceed.

**Comment by sbatten** [comment]
The behavior of alt-space with mouse position detection is explicitly designed to handle that case. When the window is off-screen or really small, the mouse is unlikely to be over the window, therefore, alt-space will trigger the native context menu which allows recovering/resizing/repositioning it.
