### ISSUE TITLE
Sticky scrolling doesn't work well with C++ template class/function

### ISSUE THREAD

**Issue by xiezhaokai** [microsoft/vscode#157750]
Env:
    VS Code Version: 1.70.0
    OS Version: Ubuntu 20.04

Steps to Reproduce:

Open a C++ file with template class/function
scroll down to the template function

what we expect is the class/function name , not the " template \<typename T\>" declaration .

![2022-08-10 17-13-31 的屏幕截图](https://user-images.githubusercontent.com/15663840/183866384-1b0df5cf-3a3e-4a17-886b-9b05fca0c63a.png)

**Comment by alexdima** [comment]
@xiezhaokai Do you have a copy-paste friendly sample that reproduces the problem? We would like to verify, but we think this might be also fixed by https://github.com/microsoft/vscode/pull/157466

**Comment by xiezhaokai** [comment]
Below is the sample code for you to verify.
just copy it to an empty file and rename it with "test.h"

```cpp
#include <string>

template <typename T >
class ProtocolVarField
{
public:
    typedef T internalVarType;
    size_t offsetInProtocol = 0;
    std::string description;
    std::string fieldName1;
    // several members to make the class body long enough
    // to test sticky-scrolling
    std::string fieldName2;
    std::string fieldName3;
    std::string fieldName4;
    std::string fieldName5;
    std::string fieldName6;
    std::string fieldName7;
    std::string fieldName8;
    //***
    //
};
```


![2022-08-11 08-58-22 的屏幕截图](https://user-images.githubusercontent.com/15663840/184047665-2baa3d0a-3fa0-4c70-bdbf-593633532daa.png)

**Comment by aiday-mar** [comment]
Hi, thanks for the feedback, I just verified on the new insiders version, and I have the following behavior:

![sticky-scroll-type-cpp](https://user-images.githubusercontent.com/61460952/184081703-d23d167b-5c3d-429a-8740-15bde069f3f8.gif)
