### ISSUE TITLE
Why does the greater than sign of the arrow function turn red when Vue TS is used

### ISSUE THREAD

**Issue by liyuhui653139137** [microsoft/vscode#157748]
Vscode 1.7.0 enables "editor.bracketpaircolorization When "enabled" and Vue TS is used, the greater than sign of the arrow function will turn red. It will not be like this if lang = "ts" is removed. It looks very uncomfortable
![1121660097161_ pic](https://user-images.githubusercontent.com/51697465/183863867-12c79fd1-3113-464b-853f-616d41359959.jpg)
![1111660097068_ pic](https://user-images.githubusercontent.com/51697465/183863895-04b3373e-4b5e-4f1e-a37f-c889e7ce6400.jpg)

**Comment by RedCMD** [comment]
https://github.com/microsoft/vscode-typescript-next/pull/35

**Comment by hediet** [comment]
Duplicate of another issue.
