### ISSUE TITLE
`code-insiders` waits instead of returning immediately

### ISSUE THREAD

**Issue by chrisdias** [microsoft/vscode#157724]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.71.0-insider (user setup)
Commit: bcb31b9cfb2261ddbabfb73defed9ae78680b9b2
Date: 2022-08-09T16:47:56.993Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

Steps to Reproduce:

1. from a terminal, run `code-insiders . -r`. I'm using Windows, the new Windows terminal, and an Ubuntu WSL distro

Result: the command never returns until VS Code is closed, it seems to behave as if the `--wait` flag is on by default

![image](https://user-images.githubusercontent.com/1487073/183791427-c61dd509-76dc-400c-88e0-4cc639a666fc.png)

Once you close VS Code, the command terminates and I can use the terminal again.  

Doesn't reproduce in Stable and has never behaved like this.

**Comment by chrisdias** [comment]
does not repro i latest insiders build 

Version: 1.71.0-insider (user setup)
Commit: ef65ac1ba57f57f2a3961bfe94aa20481caca4c6
Date: 2022-08-11T05:16:46.298Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

**Comment by SidBlack** [comment]
unfortunately I don't have a computer

śr., 10 sie 2022, 03:40 użytkownik Chris Dias ***@***.***>
napisał:
