### ISSUE TITLE
Manjaro-keyring not supported on manjaro.

### ISSUE THREAD

**Issue by pointer-to-bios-wout-addr** [microsoft/vscode#157745]
- VS Code Version:1.70.0
- OS Version:Linux x64 5.19.0-2-MANJARO
About keyring:
After login,it says it cannot write login information into keyring,
But on my system,it has a keyring named manjaro-keyring(i'm sure i have installed it).
![](https://user-images.githubusercontent.com/84652600/183849301-175e28cb-9e5f-4b0d-aa5f-7b627fcd5740.png)
Seeing issue 92972,I didn't get any useful information.
This problem makes me login every restart vscode.

**Comment by TylerLeonhardt** [comment]
Manjaro keyring needs to support Secret Storage API talked about here:

https://code.visualstudio.com/docs/editor/settings-sync#_linux

> If the error is "The name org.freedesktop.secrets was not provided by any .service files", make sure that you have a package that implements the [Secret Storage API](https://www.gnu.org/software/emacs/manual/html_node/auth/Secret-Service-API.html) installed, such as gnome-keyring. VS Code expects such a package for storing credentials on the machine. More information can be found in issue #104319.

Can you get an issue going on Manjaro to support this in their keyring?

**Comment by TylerLeonhardt** [comment]
Is `manjaro-keyring` an app that you can open and store credentials into? Everything I'm reading online says it is just for `pacman`... in which case you'll need a Secret Storage compatible keyring like `gnome-keyring`

**Comment by pointer-to-bios-wout-addr** [comment]
oh i see, i read it's doc, it's really just for pacman.
maybe i must try to install another keyring.
thank you!
