### ISSUE TITLE
gbk to utf-8

### ISSUE THREAD

**Issue by liuyi-it** [Microsoft/vscode#15770]
- VSCode Version:1.7.1
- OS Version: windows 10

Steps to Reproduce:

1. 不能自动根据文件的编码使用相同的编码打开文件；
2.不能批量转换文本编码

**Comment by ramya-rao-a** [comment]
Translation:
1. Can not automatically open the file according to the encoding of the file using the same encoding;
2. Text encoding can not be converted in batches

**Comment by ramya-rao-a** [comment]
I can repro the first issue.

**Comment by bingzheyuan** [comment]
I believe the second means that it is not possible to open files with same encode ( say GBK) for a single project.

**Comment by bpasero** [comment]
Encodings can be configured in settings.json for the project and for files we support UTF-8 and 16 detection via BOM.
