### ISSUE TITLE
Scrollbar in grid layout is not correct

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#157737]
I found the easiest to reproduce is with this integration test:

```ts
test.only('editor, assign and check view columns', async () => {
	const doc = await workspace.openTextDocument(join(workspace.rootPath || '', './far.js'));
	const p1 = window.showTextDocument(doc, ViewColumn.Nine).then(editor => {
		assert.strictEqual(editor.viewColumn, ViewColumn.Nine);
	});

	await new Promise(resolve => { });

	await p1;
});
```

This correctly opens a group at the ninth column but the scrollbar is still showing as if it was not scrolled even though it is.

![image](https://user-images.githubusercontent.com/900690/183834791-fae9a5a3-40fd-4bd9-9f2a-5c513eed3c66.png)

**Comment by joaomoreno** [comment]
Very likely an issue in `vs/base/common/scrollable` et al.

**Comment by babakks** [comment]
@joaomoreno Just submitted a PR.

**Comment by joyceerhl** [comment]
I see the scrollbar on the right, but it also looks like there is a second shorter scrollbar behind it 
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/30305945/198359676-1b24c3b2-8758-453e-9384-afa78ed52204.png">
