### ISSUE TITLE
Find and replace limited to 999 lines?

### ISSUE THREAD

**Issue by themccallister** [Microsoft/vscode#15778]
- VSCode Version: 1.7.1
- OS Version: 10.12.1

Steps to Reproduce:

1. Open a file with an excessive amount of duplicates, in my case - 19000 line CSV with `,,,,,,,,,,,,,,,,,,,,`
2. `cmd+shit+h` or `edit -> replace`
3. Using replace all will only select the first 999 occurrences 

I assume this is a performance constraint, so this may not be an issue at all. However, it makes a monthly task of mine consume more time or I have to use another editor - which I would prefer not to.

<img width="427" alt="image 2016-11-20 at 10 23 11 am" src="https://cloud.githubusercontent.com/assets/5354908/20463916/73b29132-af0b-11e6-9c80-35a42802e7b0.png">

**Comment by sandy081** [comment]
@themccallister We have an hard-limit of 2048 for search results and replace also has the same limit, but not 999. Can you please let me know how many results are returned in the Search viewlet?

**Comment by schwarzie2478** [comment]
I did a test build of the current code and changed the limit to 19999.
It seemed to still work with no noticable performance loss ( fairly recent desktop pc)

Maybe this could be turned into a user setting?  I'm new to Typescript development and unfamiliar with the code base.  If it is obvious how to do it, i could try to add it, but I can't promise anything usefull

**Comment by roblourens** [comment]
There's a find limit coming from the editor, which does the search on open files. Workaround: have a folder open containing your file, but close the file, do the find/replace, and there will be no limit.

**Comment by alexandrudima** [comment]
@roblourens The model find API has an argument (the last one) that can be used to replace more than 1k. i.e. the find widget replace all can replace more than 1k.

**Comment by chrmarti** [comment]
- VSCode Version: Code - Insiders 1.12.0-insider (d8a1d8b8a7c886547ba6bc0d81fc2ff639d4c9f5, 2017-04-27T06:05:48.177Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none

Still an issue:
![screen shot 2017-04-27 at 4 01 41 pm](https://cloud.githubusercontent.com/assets/9205389/25507748/d7e79caa-2b62-11e7-8816-bf8637d918e5.png)

**Comment by indrakaw** [comment]
Latest version's limit is 10,000. 
![screenshot from 2017-05-07 12-44-03](https://cloud.githubusercontent.com/assets/9590878/25778271/9127e522-3323-11e7-8ea4-c2740e6ce8f5.png)

It was 999 (had to update it this afternoon).
![screenshot from 2017-05-07 12-31-44](https://cloud.githubusercontent.com/assets/9590878/25778278/b3ede8ae-3323-11e7-9e52-03b71492bd48.png)

And it's little bothering if I have to replace all coma into slash of a CSV. 150k lines of CSV!!

**Comment by ToMakeSense** [comment]
[ #496](https://github.com/Microsoft/vscode/issues/496)

**Comment by skol-pro** [comment]
Still limited to 999... 👎

**Comment by roblourens** [comment]
@skol-pro It shouldn't be, can you open a new issue with some more details about what you're trying?
