### ISSUE TITLE
Show option 'Try Again' on Windows, when editable file is locked.

### ISSUE THREAD

**Issue by ernado-x** [Microsoft/vscode#1577]

**Comment by bpasero** [comment]
If save fails for any reason, we offer the ability to try again. 

![image](https://cloud.githubusercontent.com/assets/900690/12844328/f004b6ac-cbfe-11e5-9ab8-2fb502ca3682.png)

**Comment by ernado-x** [comment]
@bpasero , it is true for Mac, but not for Windows.

**Comment by bpasero** [comment]
@ernado-x in that case "Retry" is replaced with "Overwrite" and will do exactly the same as "Retry" but will also try to change the permissions as needed.
