### ISSUE TITLE
[css] option to hide all CSS vendor prefixes in intellisense

### ISSUE THREAD

**Issue by Ollie-w** [Microsoft/vscode#15776]
A lot of people now use Post CSS autoprefixer rather than going to the bother of manually writing out prefixes themselves. It's a far better workflow. As such, prefixes being in-your-face as code auto-completion suggestions is a very annoying feature of VSCode. Is there an easy way to remove prefixes from appearing in the code-completion suggestions? If there is not then there should be.

**Comment by aeschli** [comment]
Vendor specific properties are now sorted after the regular properties.
