### ISSUE TITLE
Make git SCM provider aware of terminal operations

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#157740]
1. Start drafting a commit in the SCM input box
2. Finish committing from the terminal
3. :bug: the SCM view doesn't know the commit has already happened and displays the stale tracked changes until explicitly refreshed

It would be great if the SCM view could use terminal shell integration to figure out that a commit has already happened and trigger a refresh in this scenario.

**Comment by Tyriar** [comment]
Should be easy to accomplish after https://github.com/microsoft/vscode/issues/145234 is done. You will be able to subscribe to certain commands and just refresh after `git*`, `hub*`, etc. happens
