### ISSUE TITLE
Display gitignored files/folders in gray (inactive) color (in left explorer tree)

### ISSUE THREAD

**Issue by jurosh** [Microsoft/vscode#15775]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Even that GIT integration is good in @code but in explorer it's not possible to see which **files are marked as ignored** and will not be pushed to git.
In other editors these ignored files are **displayed in gray** - so you know which are not relevant to edit (eg. some generated files, configs etc).

Probably best would be if icon themes for explorer will have ability to change look of this feature.

Example in phpstorm:
![Example in phpstorm](https://screen.jurosh.com/i16/2016_11_20_72261702821567312.png)

..having .gitignore:
```
vendor
.env
```

**Comment by aniddan** [comment]
explorer-excluded-files

**Comment by jurosh** [comment]
@aniddan that's like answer ?

You probably mean `explorer-excluded-files` extension, but it doesn't look like it's doing what I explained...

**Comment by bpasero** [comment]
This issue has already been reported. Please use the search function next time before reporting an issue and/or this time if you are curious about the progress of the issue.

**Comment by jurosh** [comment]
Why not post link to issue directly....
But I found https://github.com/Microsoft/vscode/issues/15370 - description seems to be different, but first comment is talking about gitignore so it's probably what you mean...

**Comment by pedzed** [comment]
@bpasero Could you at least add references to the other issue(s)?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/23804
