### ISSUE TITLE
Can I set the app's user language to English while system Language is Chinese?

### ISSUE THREAD

**Issue by sjf0213** [Microsoft/vscode#15786]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

I am an iOS developer in China now, while I used to be a .Net developer using C#. I am familiar with the English Menu and some other setting items in Xcode and other tools on Mac OS X, since most of the software on Mac OS X does not support Chinese. 

Now i found VSCode can NOT set the app's menu language as English while my Mac OS X is Chinese Language. the app's language is the same with the OS language

The good side of using English is that,  there is no ambiguity for every menu item.  Now, even when some menu item are in Chinese(my mother tongue), I am confused with its meaning. 

So, would you please give us an option to set the app's runtime language?

**Comment by Tyriar** [comment]
You can read about how to do this in the documentation https://code.visualstudio.com/docs/customization/locales
