### ISSUE TITLE
How to mention member in editor with extension API CommentThread

### ISSUE THREAD

**Issue by roerossh** [microsoft/vscode#157860]
When I use createCommentController createCommentThread to create code discussion input box,  I want to use @ keyword to popup team members in that editor box like the behavior in web👇
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/48474392/184063427-1daebb0d-caba-46a0-8413-3a3f1eee7508.png">
But current API doesn't seem to support this feature，current👇
![image](https://user-images.githubusercontent.com/48474392/184063357-bc0d8575-034e-4ba3-9ee4-2fd7f77df93a.png)

Can you guys implement this，it's very useful in daily scenes

**Comment by alexr00** [comment]
@roerossh it looks like you're using the GitHub Pull Requests and Issues extension, is this correct? What version of that extension are you using?
