### ISSUE TITLE
custom control the vscode's terminal print log length 

### ISSUE THREAD

**Issue by xgqfrms** [microsoft/vscode#157801]
> I want to custom control the vscode's terminal print log length.

## situation

In my case, it would be easier compared to multiple logs if each log was displayed on one line.

<img width="1397" alt="image" src="https://user-images.githubusercontent.com/7291672/183940491-8f897c03-09ec-491b-aa6d-fd3c350cb5c4.png">

## current, auto break to multi lines

```code
// ...
test case i result:  passed ✅ [
   1,  2,  3, 4, 8,
  12, 11, 10, 9, 5,
   6,  7
]
test case i result:  passed ✅ [ 2, 5, 8, -1, 0, 4 ]
// ...
```

## wanted, no need break if the right space is enough.

```code
test case i result:  passed ✅ [ 1,  2,  3, 4, 8, 12, 11, 10, 9, 5, 6,  7]
test case i result:  passed ✅ [ 2, 5, 8, -1, 0, 4 ]
// ...
```

**Comment by meganrogge** [comment]
looks like you're using an extension provided terminal - thus the name `zsh-js-solutions`. I believe that extension's repo is where you need to file this bug.

**Comment by xgqfrms** [comment]
> looks like you're using an extension provided terminal - thus the name `zsh-js-solutions`. I believe that extension's repo is where you need to file this bug.

not right.

the shell is `zsh`, and the folder is named `js-solution`, so it looks `zsh-js-solutions`, but not  is a extension.
