### ISSUE TITLE
Improper rendering of unicode surrogate pairs in terminal

### ISSUE THREAD

**Issue by agentultra** [Microsoft/vscode#15782]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|python|donjayamanne|0.5.2|
|ocaml|hackwaly|0.6.9|
|haskell-linter|hoovercj|0.0.6|
|vscode-ghc-mod|hoovercj|1.0.1|
|language-haskell|justusadam|1.2.2|
|vscode-clang|mitaki28|0.2.1|

---

The terminal seems to render both characters of a surrogate pair instead of rendering it as a single glyph. This causes alignment issues in my ncurses-based project (not a blocker, just something odd I noticed).

See screenshot

<img width="912" alt="vscode_bug" src="https://cloud.githubusercontent.com/assets/120574/20466336/7afd7450-af3f-11e6-8273-a0f81d1c13db.png">

**Comment by Tyriar** [comment]
@agentultra do you have some minimal repro steps? I have a feeling it's related to the width of the character being wrong.

**Comment by Tyriar** [comment]
Upstream issue https://github.com/sourcelair/xterm.js/issues/467

**Comment by Tyriar** [comment]
I think this is fixed now in stable
