### ISSUE TITLE
Sticky scroll hides input

### ISSUE THREAD

**Issue by riskoviv** [microsoft/vscode#157809]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: Windows 10 Pro 21H2

Editor automatically scrolls to show active line when input is performed and current line is not in viewport, but sticky scroll overlaps it. I think in this case editor should scroll more lines to show active line below sticky scroll.

Steps to Reproduce:

1. Focus on editor
2. Scroll a few lines down so that the current line is above the viewport
3. Start typing
4. Editor scrolls so that the current line is at the top of viewport, but sticky scroll overlaps it

https://user-images.githubusercontent.com/44531490/183957097-29a4edc3-af7a-4ff4-83d4-53268df72fec.mp4

**Comment by alexdima** [comment]
Let's track in #157175
