### ISSUE TITLE
Add onWillSaveNotebookDocument

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#157844]
This would match `onWillSaveTextDocument` but for notebook docs instead

As parts of this, we should allow extensions to perform notebook edits before the save happens

**Comment by jrieken** [comment]
Is anyone asking for this specifically?

**Comment by mjbvz** [comment]
@Yoyokrazy and I discussed as a way to clean up unused attachments in notebooks. For this we need to loop through all attachments in the notebook and remove them from the metadata if they are not referenced in the cell's markdown 

We also talked about cleaning up these attachments when the notebook is closed. However that means we would need an api to modify notebooks when they are closed, which raises many more questions

**Comment by worksofliam** [comment]
@jrieken I am asking for it. 

Related PR/issue: https://github.com/halcyon-tech/vscode-ibmi/pull/818#issuecomment-1220733058

**Comment by jrieken** [comment]
@bpasero do we have a generic save participants for any working copy? `onWillSaveTextDocument` is done via `ITextFileService.files.addSaveParticipant` but for notebook we need something same, same but different

**Comment by bpasero** [comment]
@jrieken yeah I think I had added that even though no client yet, can you try via `IWorkingCopyFileService.addSaveParticipant` and `IWorkingCopyFileService.runSaveParticipants`.

**Comment by mjbvz** [comment]
Note from API discussion: when looking into this, we should also look into format on save for notebooks

**Comment by seeM** [comment]
We would use this in nbdev (tracking here: https://github.com/fastai/nbdev/issues/952). We remove unneeded metadata from notebooks on-save, for cleaner diffs and less chance of merge conflicts. It's very easy to implement with Jupyter Notebook/Lab via `ContentsManager.pre_save_hook`. We add this to the relevant config file:

```python
def nbdev_clean_jupyter(**kwargs):
    try: from nbdev.clean import clean_jupyter
    except ModuleNotFoundError: return
    clean_jupyter(**kwargs)

c.ContentsManager.pre_save_hook = nbdev_clean_jupyter
```

How could we get similar behaviour for our VSCode users? Is there any workaround while `onWillSaveNotebookDocument` doesn't exist?

**Comment by rebornix** [comment]
Latest API https://insiders.vscode.dev/github/microsoft/vscode/blob/d3c2dcacf39c2a25c06547945ae13da4c8cf9f82/src/vscode-dts/vscode.proposed.notebookDocumentWillSave.d.ts

**Comment by rebornix** [comment]
Based on the comment from @mjbvz , we can simply the API to

```
	export interface NotebookDocumentWillSaveEvent {
		/**
		 * A cancellation token.
		 */
		readonly token: CancellationToken;

		/**
		 * The document that will be saved.
		 */
		readonly document: NotebookDocument;

		/**
		 * The reason why save was triggered.
		 */
		readonly reason: TextDocumentSaveReason;

		waitUntil(thenable: Thenable<readonly WorkspaceEdit>): void;

		waitUntil(thenable: Thenable<any>): void;
	}
```

Two changes:

* Reuse `TextDocumentSaveReason` despite the name is talking about `TextDocument`, it's generic and applied to all documents
* Use single `WorkspaceEdit` as it can contain multiple edits already, also we can validate if the workspace edit is only applied in the target notebook document or its cells

**Comment by rebornix** [comment]
The API is finalized and merged into `vscode.d.ts`.
