### ISSUE TITLE
provideCellStatusBarItems  Test Fail on MacOS

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#157828]
From https://dev.azure.com/monacotools/Monaco/_build/results?buildId=181401&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15
```
  1) statusbar
       provideCellStatusBarItems called on metadata change:
     Error: asPromise TIMEOUT reached
      at asPromise (extensions/vscode-api-tests/src/utils.ts:128:16)
      at Context.<anonymous> (extensions/vscode-api-tests/src/singlefolder-tests/notebook.api.test.ts:291:34)
      at processImmediate (node:internal/timers:466:21)

```

**Comment by roblourens** [comment]
Was just looking at this. That might make sense too, but it also seems to make sense to test this as an API contract.

**Comment by roblourens** [comment]
Is it going to make a difference if I move off the deprecated WorkspaceEdit api?

**Comment by roblourens** [comment]
The issue you have mentioned with the editor service, I wonder if that could be in play here because this failure is just implying that the cell did not get rendered and initially request statusbar items.
