### ISSUE TITLE
Search only includes open files when "files to include" is populated

### ISSUE THREAD

**Issue by DustinTabist** [microsoft/vscode#157871]
Type: <b>Bug</b>

When searching for a string containing Japanese characters, no results are returned if I have something in "files to include".

If "files to include" is empty, then the search term is found.
If "files to include" is not empty, but I am searching for an ASCII string, then the search term can be found.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-tailwindcss|bra|0.8.6
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
remotehub|Git|0.40.0
vscode-pull-request-github|Git|0.48.0
vscode-env|Iro|0.1.0
vscode-edit-csv|jan|0.7.2
rainbow-csv|mec|2.4.0
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-repositories|ms-|0.18.0
excalidraw-editor|pom|3.2.0
quicktype|qui|12.0.46
vscode-yaml|red|1.9.1
vscode-paste-and-indent|Rub|0.0.8
partial-diff|ryu|1.4.3
svg-preview|Sim|2.8.3
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.15.0
copy-hover-type|You|0.0.6

</details>

**Comment by roblourens** [comment]
Could you give a specific example, and share logs following these steps? https://github.com/microsoft/vscode/wiki/Search-Issues#filing-a-search-issue

And it might help to figure out whether there is something about the specific files/folder you are searching in

**Comment by DustinTabist** [comment]
I created a new project to try and reproduce the issue.
The issue also happened for ASCII strings.  I see that global search is done by ripgrep.  Maybe the issue is there.
Below is a video of the issue.
[Screen Recording.webm](https://user-images.githubusercontent.com/105257792/184558851-e6ff6a64-515c-4624-8878-5fa1ba3fa856.webm)

**Comment by DustinTabist** [comment]
I changed the title to:
"Search only includes open files when "files to include" is populated"

**Comment by roblourens** [comment]
That search include pattern won't work to include files in the folder, it's evaluated from inside the folder, so it shouldn't include the folder's name.

But when a file is open, it is always searched regardless of include/exclude patterns (have an open issue for this). I don't think Japanese characters have anything to do with this

**Comment by DustinTabist** [comment]
> I don't think Japanese characters have anything to do with this

No, it doesn't seem related to Japanese anymore, as I was also able to reproduce it using ASCII characters.  I noted this above and changed the title of the ticket.

> That search include pattern won't work to include files in the folder, it's evaluated from inside the folder, so it shouldn't include the folder's name.

I'm not sure what you mean.
In some cases, my open workspace contains multiple folders, in which case sometimes I need to filter results to only include certain folders in the workspace.
Also, in the test I did, which I recorded and pasted into my comment above, I show that the "include folder" filter does have an effect on what search results are returned.  When the folder name matches the folder the files are in, search hits in those files are shown in the search results.  When I change the "include folder" string to *not* match the name of the folder that the files are in, then matches in files in that folder are *not* shown in the search results.  Again, this is shown in the video.

**Comment by roblourens** [comment]
> In some cases, my open workspace contains multiple folders, in which case sometimes I need to filter results to only include certain folders in the workspace.

If you have a workspace with multiple folders, you can target a single one like `./foldername/pattern`, but when you have a single folder open like in the demo, you shouldn't include the folder name.

However you are right, for open files, we actually match the full path against the pattern. I forgot about that problem, there is an open issue for it.
