### ISSUE TITLE
Error about 'Git Base extension is not loaded' when running in remote extension host and activating GitHub Repositories

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#157817]
1. Have a Remote-* window open in desktop VS Code stable and GitHub Repositories installed locally
2. From https://vscode.dev/github/microsoft/vscode, execute the Continue Working On command and choose 'Reopen on the Desktop'. What should happen is that this reopens the repo with GitHub Repositories extension in a new desktop VS Code window as opposed to vscode.dev 
3. :bug: see this dialog, and the new GitHub Repositories window is not opened. Also, reloading the window does nothing here
![image](https://user-images.githubusercontent.com/30305945/183967730-f5757959-8016-495d-ae44-b98d1b4bf6a7.png)

I reproduced this issue with Remote-WSL and @kieferrm also reproduces it with Remote-SSH.

**Comment by joyceerhl** [comment]
Reopen on the Desktop invokes an extension URI handler `code://ms-vscode.remote-repositories/open?=<repo URI>` which then launches a new VS Code window with that virtual repo. My current understanding for why this fails when there is an existing remote window is that GitHub Repositories favors running in the local extension host, whereas in Remote-WSL/Remote-SSH, the Git Base extension is running in the remote extension host. GitHub Repositories has a dependency on Git Base that is reported as not satisfied in this case. 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/30305945/184416516-4887404b-2633-4ff3-9d44-36c6e78c13f4.png">


This seems related to https://github.com/microsoft/vscode/issues/138282 @aeschli. I wonder if it would be possible to activate the GitHub Repositories extension on the remote side just for the purposes of resolving the extension dependency, but continue to open the new window with the RemoteHub window on the local extension host?

**Comment by joyceerhl** [comment]
Ah @aeschli is out. @alexdima or @sandy081 would you happen to have context on how extension dependencies are resolved across the local and remote extension hosts?

**Comment by tanhakabir** [comment]
I believe I'm facing the same issue here: https://github.com/microsoft/vscode-remote-release/issues/7084

I notice in the local window before the remote window I have everything installed but when I'm switching over to the remote window, it says the local no longer has the extension dependency I need installed

**Comment by alexdima** [comment]
> Ah @aeschli is out. @alexdima or @sandy081 would you happen to have context on how extension dependencies are resolved across the local and remote extension hosts?

Yes, the `extensionDependencies` for a certain extension are considered satisfied iff for each extension listed as an extension dependency any of the following is true:
* the extension is installed and enabled and it doesn't have a `main` nor `browser` property (i.e. descriptive extensions)
* the extension is installed and enabled and it has a `main` or `browser` property, but also defines a property called `"api":"none"` and has activated correctly on any extension host. See https://code.visualstudio.com/api/advanced-topics/remote-extensions#handling-dependencies-with-remote-extensions
* the extension is installed and enabled and it has a `main` or `browser` property and has activated correctly on the same extension host.

**Comment by aeschli** [comment]
In a remote window, `git-base` runs remotly, because it is needed by git which wants to be remote as it runs on the remote file system.
remote-repositories is `extensionKind: ui` and can only run in a local window. 

What's the reason that remote-repositories can only run pmn the ui? I undertstand that's preferrable.

**Comment by joyceerhl** [comment]
Oh good point @aeschli. I think the intention was to force Remote Repositories to only run in a local window. `['ui', 'workspace']` seems more appropriate given the git-base dependency. But also, we do not strictly need the git-base extension to have activated first, so I have removed that hard dependency in the package.json as a workaround for this issue. Ultimately though we would ideally want https://github.com/microsoft/vscode/issues/145307 as you say.

**Comment by aeschli** [comment]
In order to access the 'git-base' API [link(https://github.com/microsoft/vscode-remotehub/blob/93d35ec1738a440b6c9cd37cecbcba8e1c89a4a2/extensions/remotehub/src/commands.ts#L44), the git-base extension and your extension need to run in the same extension host. The extensionDependency is needed for that to happen.
