### ISSUE TITLE
Multiple workspaces not restored : OSX

### ISSUE THREAD

**Issue by DaveAppleton** [Microsoft/vscode#15784]
- VSCode Version:  1.7.1
- OS Version: 10.11.6

VS Code does not restore previous environments

Steps to Reproduce:

1.  Open half a dozen folders in different workspaces do some work 
2. Reboot Mac

A maximum of ONE workspace is restored.

**Comment by bpasero** [comment]
Set `"window.reopenFolders": "all"`
