### ISSUE TITLE
VSCODE crashes for unknown reasons

### ISSUE THREAD

**Issue by SuperPowerLF2** [microsoft/vscode#157862]
Type: <b>Bug</b>

Reproduction steps

1. Remote desktop the computer and open VSCODE on that machine 
2. Close the remote connection
3. Connect to the computer remotely again
The VSCODE screen on the remote desktop will appear to be stuck and unresponsive. It will not close.
I'm using Win 11, I don't know how to fix it

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22622
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.95GB (34.07GB free)|
|Process Argv|--crash-reporter-id 94a3f35e-0644-4294-b70c-812702e1c0cd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.22.1
vscode-language-pack-zh-hans|MS-|1.70.8100912
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.241.3
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.11.5
hexeditor|ms-|1.9.8
pdf|tom|1.2.0
sshtools|XPL|1.0.79

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaac:30438847
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

**Comment by aladdin-add** [comment]
having the same issue on macos: 13.0 Beta (22A5295i). and I'm not using remote connection.

**Comment by gjsjohnmurray** [comment]
@SuperPowerLF2 please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

@aladdin-add since you are not using Remote Desktop onto a Windows machine why do you think yours is the same problem?

**Comment by aladdin-add** [comment]
it's getting unresponsive for unknown reasons. I have to force-kill it.

**Comment by SuperPowerLF2** [comment]
> @SuperPowerLF2 please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
> 
> @aladdin-add since you are not using Remote Desktop onto a Windows machine why do you think yours is the same problem?

I have tried closing all the plugins, the problem still persists
