### ISSUE TITLE
Source Control causes vscode to be unresponsive

### ISSUE THREAD

**Issue by ChnMig** [microsoft/vscode#157873]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
date: 2022-08-10T06:09:06.916Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.6.0

Steps to Reproduce:
When I click on the Source Control button, vscode is unresponsive until the system prompts for a popup.
<img width="260" alt="image" src="https://user-images.githubusercontent.com/44669684/184091805-cda11ffa-3ec8-42b7-b400-9468fdd5637d.png">
BUG will be 100% reproduced
He looks similar to https://github.com/microsoft/vscode/issues/157752

**Comment by ChnMig** [comment]
I tried to follow the instructions at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports to get the crash report, but I didn't get ` .dmp` file
``` bash
➜  vscode ls
attachments  completed    new          pending      settings.dat
```

**Comment by lszomoru** [comment]
Merging this issue into #147854.
