### ISSUE TITLE
Downloading package 'Mono Framework Assemblies' Failed at stage: downloadPackages

### ISSUE THREAD

**Issue by w548544375** [Microsoft/vscode#15781]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-45-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.2|

---

Steps to Reproduce:

1.Updating C/C++ dependencies...

Downloading package 'Mono Framework Assemblies' Failed at stage: downloadPackages
Error: read ECONNRESET

Finished

**Comment by jrieken** [comment]
@w548544375 Please file this against the extension in question
