### ISSUE TITLE
Support clicking on file paths where line infos are separated from the path by a space if the file path is not relative to the workspace

### ISSUE THREAD

**Issue by rrousselGit** [microsoft/vscode#157822]
Hello! For more background, cf the related "Dart Code" issue: https://github.com/Dart-Code/Dart-Code/issues/4100

Long story short, in Dart, stack traces have the format:

```
  test/providers/state_provider/state_provider_test.dart 89:15  main.<fn>
```

The problem with this format is, when clicking on the file path within the embed terminal, VScode in some cases (mono-repos apparently?) does not redirect to the correct line/column (and instead goes to 1:1)

This issue seems to appear if the file path is not related to the workspace root. In the example given, the actual path relative to workspace root is `packages/riverpod/test/providers/state_provider/state_provider_test.dart`

Surprisingly, if instead of a space `:` is used, then this issue seems to disappear:

```
  test/providers/state_provider/state_provider_test.dart:89:15  main.<fn>
```

**Comment by Tyriar** [comment]
This actually works now:



![Image](https://user-images.githubusercontent.com/2193314/205717074-e892f961-e9af-412b-8f53-2c5e4c3648c8.png)
