### ISSUE TITLE
No context menu in any input field

### ISSUE THREAD

**Issue by coty-crg** [Microsoft/vscode#1578]
On OSX. I usually CTRL+C, CTRL+V; but this time I happened to right click and noticed it wouldn't work.

**Comment by Tyriar** [comment]
This repros on Ubuntu 12.04 in both the find in file (<kbd>ctrl</kbd>+<kbd>f</kbd>) and search (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd>) dialogs.

**Comment by bpasero** [comment]
Hm, I wonder if we prevent the native menu from showing up in these places. @alexandrudima fyi

**Comment by alexandrudima** [comment]
@bpasero I think Electron shows no context menu whatsoever on `<input>` fields. I've tried the:
* find widget inputs
* search viewlet input
* git commit message input
* quick open input
* rename variable input

**Comment by Tyriar** [comment]
@alexandrudima That's a little strange since it's just the Chromium content API underneath everything. Maybe it's disabled and can be turned on somehow? That also might be the reason why all text fields in Atom are `atom-text-editor.mini` as opposed to `input` elements.

**Comment by bpasero** [comment]
@alexandrudima can you try in a standalone electron sample, maybe we are eating the right click event to prevent showing the native context menu?

**Comment by alexandrudima** [comment]
@bpasero Just tried in the default electron app in a textarea, no context menu shows.

**Comment by bpasero** [comment]
@alexandrudima since you have tried it, can you report this to electron and link the issue here?
