### ISSUE TITLE
Disable "There's an update available: Visual Studio Code ..." popup window spamming

### ISSUE THREAD

**Issue by RobIsHere** [microsoft/vscode#157879]
Please provide a way to disable the Popup Window "There's an update available: Visual Studio Code ...". 

Reasons:
- At the moment it's only possible to get rid of this nagging message is to disable automatic updates completely - that is not what I want
- the updates are signalled by the blue (1) badge in the lower right corner anyway
- i do not want to restart my whole dev-env every week in the middle of the day just because of an update that will get installed at the start of the next day anyway, when i open vscode the first time
- the notification is a real hassle because it appears everytime you open a new folder/workspace/project which is every 15 minutes if you are working on normal multiple repos per microservice - which is still the standard in spite of the monorepo-hypetrain.

**Comment by gjsjohnmurray** [comment]
This comment implies you shouldn't see it right away:

https://github.com/microsoft/vscode/blob/ec5da8afee68b1b0d813028b6d95fb49a42f5ca4/src/vs/workbench/contrib/update/browser/update.ts#L218-L224

Indeed I don't think I have ever seen that notification.

What platform are you on? What version of VS Code are you currently running? When you use Settings editor to search for `update.` does it show any of yours as changed from their defaults?

**Comment by RobIsHere** [comment]
Hi! The pointer to the code, that enables me to debug it myself when it happens again. I'll watch out for this 5 day limit and reopen with debugging info when/if it appears too early next time and I have more information. Thanks for your help!
