### ISSUE TITLE
Allow editing the git index

### ISSUE THREAD

**Issue by FSMaxB** [Microsoft/vscode#15785]
Using vim with the [fugitive](https://github.com/tpope/vim-fugitive) plugin, I can edit the index in the diff-view directly, instead of it being readonly. I would like to see this feature in VSCode as well!

This is really useful for making partial commits. If I do more than one change at the time, sometimes it is impossible to split these changes into distinct commits with just the current feature of being able to stage selected lines.

Let me give you an example:

Before the changes:
```cs
functionCall(argument);
```

After both changes:
```cs
functionCall(argument, changeA, changeB);
```

Although change A and change B can be independent from each other, you cannot do separate commits easily. If I could edit the index directly however, I could do this:
```cs
functionCall(argument, changeA);
```
Then commit change A and only after that commit change B as well.

**Comment by joaomoreno** [comment]
It's impressive that fugitive offers that feature. Can you show me a screencast?

**Comment by FSMaxB** [comment]
I will make a short video as soon as I find the time.

**Comment by FSMaxB** [comment]
[here](https://youtu.be/VsDSUZID8LU)

**Comment by joaomoreno** [comment]
Uff, that's pretty cool!

**Comment by joaomoreno** [comment]
I'm gonna go with the template reply: this can be done by an extension now. It's the best way to go.

**Comment by FSMaxB** [comment]
Is there an extension that can do this or do you only mean that it is possible with the current APIs to write such an extension?

**Comment by joaomoreno** [comment]
I meant it as it's possible to do with the current API. 👍

**Comment by cameron-martin** [comment]
Does an extension exist that enables this?
