### ISSUE TITLE
Click anywhere on an outline heading to expand

### ISSUE THREAD

**Issue by shortorian** [microsoft/vscode#157820]
Not a major issue but it would be helpful if I could click anywhere on the line for a heading in the outline section of the explorer sidebar to expand that section of the outline. Currently I have to click on the arrow to the left of the heading to expand it. This would make the outline headings behave the same as the major section headings of the sidebar itself (the file tree, outline, and timeline section headings) and directories in the file tree section.

Since the outline doesn't remember it's previous state when moving between files, I spend a lot of time clicking Collapse All and then expanding individual sections. The Collapse All button is on the right while the arrow for expanding a section is on the left, and it's annoying to have to mouse over. 

The issue could be resolved by making the entire bar for a heading clickable to expand, by adding an expand button on the right (preferably aligned with the Collapse All button), or by moving the expand button to the right side of the column. It would also be much less of a problem if the outline remembered it's state when moving between files, but there are other issues open on that.

In case this is actually a bug, I'm working with Python files and my version information is below.

Version: 1.70.0 (user setup)
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:16.462Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by jrieken** [comment]
This can be configured via the `workbench.tree.expandMode` setting

**Comment by shortorian** [comment]
As far as I can tell, this doesn't address the issue I describe above. The options I can find for `workbench.tree.expandMode` are `singleClick` or `doubleClick`, neither of which is relevant to the issue. When I change that setting to `doubleClick` (from the default `singleClick`) it also only affects the file tree in the left-hand sidebar, not the outline.
