### ISSUE TITLE
Sticky scroll not working in ruby files

### ISSUE THREAD

**Issue by coderhs** [microsoft/vscode#157811]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.70.0
- OS Version: Linux x64 5.15.0-43-generic (Kubuntu 22.04)

Steps to Reproduce:

1. Open a .rb file, I was inside a rails project as well.

I have a rails project I can see the stick scroll working on my `.ts` files perfectly, but on `.rb` files it does nothing.

**Comment by coderhs** [comment]
I upgraded to `1.70.1` after reporting this issue.

Scroll wasn't working even after that, but due to a missing description on the extension description page i ran `killall code`, and then opened vscode and noticed that the scroll is now working in my ruby files.

We can close this issue now.

**Comment by coderhs** [comment]
Looks like i spoke too soon, and god of coding didn't like my happiness. 

I like to update my previous comment, it worked and now after i rebooted my os, it stopped working. Ruby files no longer have sticky scroll.

**Comment by coderhs** [comment]
I am going to close this issue, as I feel like its more local to my machine and not to VS Code in general.

**Comment by mjmjelde** [comment]
I'm having the same issue you are, so it is not only your local machine having an issue

**Comment by navidemad** [comment]
Same here, working well with js files but not on ruby files

**Comment by coderhs** [comment]
@navidemad @mjmjelde 

Did `killall code` and restarting vscode? You have to killall and then it take a time to initialize like currently it is working for me, but once my vscode start it takes a while to initialize. (I have seen a delay of 5 minutes, another reason i thought something local to my system - extensions might be delaying it).

I am re-opening the issue.

**Comment by mjmjelde** [comment]
> @navidemad @mjmjelde
> 
> Did `killall code` and restarting vscode? You have to killall and then it take a time to initialize like currently it is working for me, but once my vscode start it takes a while to initialize. (I have seen a delay of 5 minutes, another reason i thought something local to my system - extensions might be delaying it).
> 
> I am re-opening the issue.

Yes.  I had restarted my computer completely overnight and still did not work.  Disabled all extensions and still doesn't work properly

**Comment by navidemad** [comment]
Same I had killed all the process, waited more than 30 minutes, still not working

**Comment by carlosherrera1113** [comment]
I am having this issue as well in my rails project--not working on .rb files, but works on .js.

**Comment by aiday-mar** [comment]
In order to make sticky scroll work you need to have a language service provider extension installed. For Ruby, this may be the Ruby extension developed by Peng Lv in the marketplace. After this is installed, you need to enable the `Ruby : Use Language Server` setting in VSCode. 

![sticky-scroll-ruby](https://user-images.githubusercontent.com/61460952/184310744-8e67e0d6-f3df-4fec-b2ce-07a8d5576e01.gif)

**Comment by timriley** [comment]
FWIW, I noticed this happening too, and found this issue.

Like the comments above, I had to restart vscode in order for the feature to work the first time. But interestingly, I then saw it work for 10 seconds or so, before it then disappeared again!

One simple way I've been able to keep this feature working is to disable the "Ruby Solargraph" extension (`castwide.solargraph`) that I also have installed. Could it be that there's some conflict between Solargraph and the regular Ruby extension (`rebornix.ruby`) in terms of providing the language server support required for this feature to work?

My hunch is that solargraph takes a moment to initialise, and then after it does, it steals control (or something) from the Ruby extension, and then must not provide the right capabilities for the sticky scroll feature to display anymore.

Would love it if anyone more knowledgeable on these matters could weigh in :) Thank you!

**Comment by coderhs** [comment]
@timriley I can confirm your hunch. I had solargraph and bust-a-gem extensions, both of them were providing language service to VS Code

![image](https://user-images.githubusercontent.com/979321/185227436-518571e2-ea04-415a-a4aa-a91d43706b05.png)

So when I have them both, the sticky scroll doesn't work. When I have just solargraph it works, after it gets initialized.
