### ISSUE TITLE
Git built-in extension is unresponsive when developing in C++

### ISSUE THREAD

**Issue by usrFWQWZ** [microsoft/vscode#157858]
- Issue Type: `Bug`
- Extension Name: `git`
- Extension Version: `1.0.0`
- OS Version: `Linux x64 5.15.0-46-generic`
- VS Code version: `1.70.1`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 49,
		"activateCallTime": 16,
		"activateResolvedTime": 38,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "vscode.github",
				"_lower": "vscode.github"
			},
			"activationEvent": "api"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

I mentioned the problem here in details:
https://stackoverflow.com/questions/72913745/vs-code-takes-several-seconds-to-save-a-document-in-c/73313271#73313271

**Comment by lszomoru** [comment]
@usrFWQWZ, sorry for not getting back to you on this until now. I have read all your updates on Stackoverflow  so I was wondering if there are still any outstanding questions as it looks like you were able to track down the root cause of the problem.

**Comment by lszomoru** [comment]
Closing this issue as part of our yearly housekeeping. @usrFWQWZ, please feel free to re-open it. Thanks!
