### ISSUE TITLE
The sticky header shadow should remain when it's being scrolled off the screen

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#157838]
The function has content, so the shadow should still remain to indicate that

![image](https://user-images.githubusercontent.com/2193314/184018661-b3fa7a1e-c7ce-4e87-9869-98a68c254c7b.png)

Version: 1.71.0-insider (user setup)
Commit: dced70bbf36d3c53c08e791da1791ac7fc42519b
Date: 2022-08-10T05:17:53.560Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

**Comment by jrieken** [comment]
<img width="479" alt="Screenshot 2022-12-07 at 15 18 53" src="https://user-images.githubusercontent.com/1794099/206202896-2d9aa506-37aa-4f30-8df7-20bbe6ee6816.png">
