### ISSUE TITLE
I called two quickOpenService.input methods in sequence. But only the first appeared.

### ISSUE THREAD

**Issue by uli2k** [Microsoft/vscode#15783]
- VSCode Version:1.7.1
- OS Version:

		let host: string;
		let user: string;
		return this.quickOpenService.input({prompt: nls.localize('inputAddress', 'Enter Address or IP of the remote host')}).then(value => {
			if (!value) {
				return;
			};
			host = value;
			return this.quickOpenService.input({prompt: nls.localize('inputUser', 'Enter user name of the remote host')}).then(value => {
				if (!value) {
					return;
				};
				user = value;
			});
		});

I called two quickOpenService.input methods in sequence. But only the first appeared.

**Comment by bpasero** [comment]
This is https://github.com/Microsoft/vscode/issues/6146. As a workaround you would have to add a timeout before showing the second picker.
