### ISSUE TITLE
cannot copy tab key from terminal output

### ISSUE THREAD

**Issue by kaala** [microsoft/vscode#157863]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1 (Universal)
- OS Version: macOS big sur 11.6.8

Steps to Reproduce:

1. open integrated terminal
2. execute command echo -e "a\tb\tc\t"
3. copy the terminal output
4. paste into other text editor

I would like to keep tabs as is, but tabs are translated into spaces.
this issue happens on both local machine and remote ssh connection.

<img width="367" alt="图片" src="https://user-images.githubusercontent.com/246542/184068518-cfefd327-a091-493f-bf53-0669b195d7ee.png">

**Comment by Tyriar** [comment]
We're not planning on doing this, see https://github.com/xtermjs/xterm.js/issues/734
