### ISSUE TITLE
Git - Merge editor doesn't shows rename/rename merge conflict

### ISSUE THREAD

**Issue by CookieHCl** [microsoft/vscode#157818]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.0 (system setup), commit: da76f93349a72022ca4670c1b84860304616aaa2
- OS Version: Windows 11 21H2 (22000.832)

## Steps to Reproduce:

1. Create new file **old.txt** and commit it.
2. From 1's commit, rename **old.txt** to **new.txt** and create a new branch A.
3. From 1's commit, rename **old.txt** to **very new.txt** and create a new branch B.
4. From branch A, `git merge B`.
5. You get a rename/rename merge conflict.
```
CONFLICT (rename/rename): old.txt renamed to new.txt in HEAD and to very new.txt in B.
Automatic merge failed; fix conflicts and then commit the result.
```
`git status` look like this.
```
added by us:     new.txt
both deleted:    old.txt
added by them:   very new.txt
```
6. Now try to see the conflict in source control.

## Actual behaviour

![image](https://user-images.githubusercontent.com/28638469/183963534-eb037eb0-d7d5-4ebf-aa48-dda3c155a5a7.png)

Merge editor doesn't shows conflict; Instead it opens file `\null` and shows **Unable to open editor because file not found**.  
Selecting any file (old.txt, new.txt, very new.txt) results sme behaviour.

## Expected behaviour

I'm not sure about what the expected behaviour should be...

But at least we should be able see each file's content.

**Comment by jrieken** [comment]
For now this isn't even related to the merge editor, we don't even attempt to open it...

**Comment by lszomoru** [comment]
@CookieHCl, could you please try to reproduce with the latest VS Code release and reopen the issue if you can still reproduce.
