### ISSUE TITLE
Please, correct the position of traffic lights when command center is enabled on titlebar

### ISSUE THREAD

**Issue by widersky** [microsoft/vscode#157895]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: macOS 12.5

Steps to Reproduce:

1. Use macOS
2. Enable `window.commandCenter` setting
3. Look at traffic lights 
4. Think "ugh"

I think traffic lights position should be corrected a little bit. At the moment they are a bit too low and too close to the left edge of the window. I think the screenshots below illustrate the expected fix best :)

| Without red lines | With red lines |
| ------ | ------- |
| ![Frame 2](https://user-images.githubusercontent.com/45122321/184132651-1d5e5ebf-2e2d-4e61-aa05-b705d0caee64.png) | ![Frame 1](https://user-images.githubusercontent.com/45122321/184132702-cc4e3173-d09a-4e37-9ea6-05c6191da4b6.png) |

**Comment by stephen-ullom** [comment]
Created a pull request to fix this issue. It was bothering me as well :)

https://github.com/microsoft/vscode/pull/164246
