### ISSUE TITLE
VSCode intellisense — TypeScript type Promise<> displays its contents as if awaited

### ISSUE THREAD

**Issue by Refzlund** [microsoft/vscode#157854]
Does this issue occur when all extensions are disabled?: **Yes — Tested with browser incognito at https://vscode.dev**

- VS Code Version: 1.70.1
- OS Version: Windows 11 Pro 64-bit

I must admit that I cannot fathom the core of this problem. A `Promise` in **TypeScript** is displayed in VSCode's intellisense, as if its awaited like seen on these images:

In TypeScript Playground I get following result:
![image](https://user-images.githubusercontent.com/21252096/184053567-0fd02c6b-3b90-432e-b36d-ef41cec987ab.png)

However inside VSCode, the promise is as if its awaited:
![image](https://user-images.githubusercontent.com/21252096/184052875-87ec11c0-b4a6-41d9-9556-2c44be7487a5.png)

I cannot replicate a simple version of my issue, but you can experience same phenomenon by following the reproduction

Because of the `Promise` being displayed correctly in the TypeScript Playground, I add this issue @ VSCode

Steps to Reproduce:

1. Open an incognito browser and visit https://vscode.dev/ and open a new tab
2. Visit my reproduction from [TypeScript Playground](https://www.typescriptlang.org/play?target=99&jsx=0&ssl=192&ssc=1&pln=184&pc=1#code/PQKhAIGUDcFMBsAusDSBLR4TAFA4CawDG8AhgE6zgB2pAtrAM4AOpRVAgs8+AN44BINNWTkAZmyoAZAPZFS8Rn3ABfQcNET24AAplEYmeTrK1QkbHGTd5NNFLIAotWin1Fq9p0BXAEbw0ImdXXlV3TWtIJkY0GWo3cwjtSERvMTE3NRwNSy0qACVYAEdvJkRHOBEAHh0KeiVYAA9kanwlQqIjfCrGRFtqAHMAGnBe-oGAPnAAXnAOrp6+4WHRpcGJkZk6DAApRjiZ8AlFWCn+ARI0WBEOfHxKRkYALlXxwXg5BWfwLmYAOlk8kUglY5HqL1qYLojBB+kMxhehVI+Di8AAnlVfn89A54XQJoJKCUyi8trt9vEmi02uA+qVwAB+cAAeW2iCqhWJvRGAHIAFYUnlTRHFUq9QkybzIACS+BeY2W4AAPjRvPB4IJvOR4C8AKr5KQ4LI4YDALBgcAAWVIA0CeEQaOYVF11Fi1AAKjJpR5GMREG6qrqptNBAAKXXgKnXGmkahoxngUMAaz1AEoZlNoDI0PhwC9qLA4OR01HWkpQ8mXsIxJZwNL09NM9n8OmmdK8zRC5Y8E1mEZMDlPFRIGg6MwAmI0czmP64kpzqAQIIACIyWkACyoMTHE8CDjd4EoRC1MTg6L+ggAAoQJGrMMdfYJsIJCLBmAyXr4ZDJ4LBY0a8FNcAADF9BacBSFpR0qAAdwwddJUwGCjHINFFVIL8pQ3KgHjvC8HSdECwOuKpBA4ON3WgoZBGnWdqAaZpoyUEcdzQSdaLdJRZl4FRqIEYMWRnTiAG0eVfZgeQAXUjRiy1pchSkEJlQmElBYDRSjCOEcAk3UmQMnIjToMkl4WPHNiMUMzTYFU9TrMkkYOLnKYzBeFS1KMrT4l0tF9J+CjjJeKzoNszzYGkrJe37KDCLMicMTIgKnT4pz6Jk6lmNHcz2KEudDh4viBNAhwWkxJLTnSpj-LCpSiJKkjguSwS6MYAkBCC8q8BNM0wAgGAEGQdBMAALUsNcOB0aU8EHPJwGXWBbyQQoWDnKhzl6BxvG+ahvDoXxuwEL98DREVOnIbpYzREZLqmFVLsETdkUsb55nOqpLuuuM2qOtFdV9OVwC-H8-2oQQZBTQHv1-f8BEofA0CPZAAaB6HQYEDbUkYd0qXlNYBkEAjYFxt4BC1HVXmWACcEJqAz2QZa+3o2AqndSq5Nei640+tEBJu-LBFU8BtJ8vz5sWxAGdWkzwBQNmaRFjJWaZd1VOkl4xdIO9JaZ1WqZp7XfQAYQUeBfDYJMWbl9piAWD6IK+w4+dmUMiF8F5QweRnfQhcgyV9Kp+qQWADeZ90JgmBsmxzSPwCzHMuqAgAhc3ox+SaYqYaaPFmibpW9ZgpXnQQfo-e2rsEYlUNL+6siAnRfe2f3QnB92Y9ZlQCRp3OQ8t0saRUnzieWaXQz+MeKAGb5LuEySY8u1QBPrv3Q4JanoLT6UqnzrC+6UXPt8QLi+A7w5OTFcpKnZDnFnGEYFXWEY6QqgAyZQiXPtzwAFOJW4zGxl63tQAuiBRI-Ski5MI9p14AE0A6IE2gxDKqo9qWBGKzXecwbZvTtjdEYssMH30mIcbuTAvbM3cupIW8QUAjzbuAV+oQMZbVMvAzGmwIZP1UAvNehEABycCEFW2QftcgaChHXxwV9PBQjCECRIStJmVQKHxm0jQ3+jZwCswYasBBLCEHsJeA+KgKhuE4E6PRTAzIkzgBsbYux9iHH2NmCzCYoYZC+D5C8d0MdQyMNYcw8AAAmAADMEkYY8-juL5KodMpAlDeGoEmagMgYLxDieAWBISwmaN5ODIUZi5yYENpQBwsBcyOIqU48ALi3EeK8T4vxuignBIAIzhLHlEmJEF4mJOSak7pGSqghLaTk8APIiAlKRvk8xvQfhEHYDOMplTlmHBqVE+pf9fE6Mxi8EJgT2mRI8V09JCSkkpLSUoTJwT9mjJ5GwBZUyCQzMwLwuIHApQIVsKwuwsBvR4n3AcZxYdameM0Q07ZASQkAGYDmdJULEnpZz+npKuTC25yTqDvMQJ8jA+44B-KMHQAF1BpmFPAK8w2cQWiYBWY4oFrj1lgs2Y0nZzSAAssKjnwoGacvpFzBkhI5eimQlKLAiFJRYzBvpECiupbSux9KQUbI0Vsph3wQkAFZOXRO5Sc3p5yBlXK1bch4sAZVUuuIgCVszIT+gULKy18rVnAsZd45lEL1XBIAGzauOYivlhqhnerQbyUEdr4AOvFU8sllo7xoBSIIp1NjFWuvBWq3ZwSADsvrdX+oNSioN2bbl0DjQmzG1rMAcHgCU46hQ+zkCRvKlNdSmUqpZZC4JAAOHNCLwC8vzZcoN3bbkKBrWiOt-YykVrrJaP6Syk0OObaCt1baPW7MCT68AES4W9v7ciwdgSN0hrGaOOd+B8kFMlcnfAZ8yjOoZS2ldUxVX+O+Gy0JPaF02L1Ui-l-D33ZPdLyM2N7RRlAvTTS0ZqEK5mdu-MoFRLVBUmu9L6McOAwVIBgMpmJJo9xuqvGa1hnD4D7BoPgAtB4U0GNLKD2KZD4Cpt1K0pBdIbwTmaQodAZBwCUJdbFipsUOHACiJgJLMBbSoNizgKGbo8KoDoQISY6MwcYByMoucBIqWAgkogdEqE6T0hkZaiBc7SxM7nYSOnqB6bdNJDBHswO9EQyIZDm8bpzzjAmCzk0rO6bomrTsRZIFAQAOJmqUNJ8Alc0TAB+oeUUCNYAMBEEoFgxA2JXFzMIGIhAN5VE7uvA+amOBCNzqhnmciysoerLWYrUw2xAMLh2AsRYuo02NuqM2RALaFFSOQSkskYwO1mH1rUg2kGj3HuQSeLxp6zz-vPJkjmFHe1pgNYOpDVrqf6x6aCO3xvhxjnHXM+YuzkEAmaa0ulIubg3gl3bGcEvHnIKeWA8nMEvbeyphjY2BtVEtEIn7oHdvWTUwR-mAhhJ-fiMLIzVoR6u1Lp1025sAfQ7NeNySEc-4dBPD84HMOAdTFfkvRuzNA70y20zAkJiGGCAACRuUEFDmHBmFYI5eFUfBQ3ywRMunNuMM9PM8xdr4UustX4o+6xbS0GPdvY5jmTtA-sYfWW5+HQQaha6ccxwNvjsOfR+gPH5E2D3xsZyUH5KLPn2wMHo4xoCzcIahjoXT5QIHb29HUVMduH3Cd67206NTgOHP85m1PIXC2VXh9m2XYXi2RvgBdG6T03pRC+ls3ETEmHsPdDV-ty04dV7MdFUWQ+2EpWVvTvb1TVDctUEgn8CvYg0C-ioYgNcUWABeY0ILMDQE9yT2X4hRbEL7MVjuzSOHyuAPsvRXduZDvQjeIcRgDDNa7iJYQgKA9mDyefVrlRjI30fiJ-vWOwHKzPjBJGyMiC0wLQHcPfIZEcCPeD3uoBZXioA4BanIR6AzVnoqhHBhJLRsdhJglscccNFQA8dXsCdoNftA8AdkCQdxswdQDwCYCV9sB-5ycA46ZNtVtTg9Z153R1NehNNDhrsr8UNFMetgc1NbdNdLtzQIBk4etU5c4s4kgFMZBZlzgfpmcBABAGBHgbQiZqNhgWcBhvxkYoYQYtcqYooG1wBnk59BDMBZg4k0QbNExP8L4kN8sdBtDYCzhBBNDQh5CGMRgJDGApCuFdDc9MAjCXNEA-gjC-hv5qBXd1AMhQxrRsUvDYwUQ6BXdwAphgk-gNVUwWdKBHsrFfEWdDoGMToKMxCxCHCpCXgeQAAJBAD4cAAAdSMHgHwAAEIeRUizABB4VCRA9wBr0vdEBfEGjjRL1ZlhBCBGhIdD8mN2Deo5ouwPhmAUt7wJ9qR2MgIABaTRaCPjSgcADfAsMERtD4IEdEcAGCTceIQgM8GQAfQYaiICGxfYbCeMZCcTQGKgKKf6OfPwAIEgNEKBQibGWZbidwXorxKoQmPyHopoWnPATQ0gAffKExdJD4xAPAPQgwsQfzA8MQPw9MfgQQICd0dcFXDQowKgFXRgekGmbEwwBJXMYTAIAscAFpKFTtKwslT2VaR2AfP4QExoP4Q-LZEQ5QWwgGJ+ew6IXIsZOJc9LheFC8QQCUtQIAA)
3. Copy the contents of the playground into the VSCode tab
4. At the bottom of the file (at line 187), add a period and use VSCode intellisense to get results - which should display as the image above

I apologize for the complexity of the situation, for I am not exactly sure what causes the bug.

**Comment by imranbarbhuiya** [comment]
ig this is working as intended. Vscode shows properties that'll be available after u resolve the promise. If you accept the IntelliSense, vscode will add `await` automatically for you.

**Comment by yume-chan** [comment]
I also remember this as a feature. Properties of `Promise` (`.then`, `.catch` and `.finally`) are still there if you need.

**Comment by Refzlund** [comment]
> ig this is working as intended. Vscode shows properties that'll be available after u resolve the promise. If you accept the IntelliSense, vscode will add `await` automatically for you.

The statement is not awaited at all. Hence `Promise<>` — so if I were to actually use one of the suggested options from the VSCode intellisense, I would get an error — because the Promise is not fulfilled; it has not been awaited.

If this is feature of VSCode, can you perhaps tell me how to turn it off, to avoid confusion of unfulfilled promises?

**Comment by Refzlund** [comment]
This is the behaviour I am expecting (from TS Playground)

Here's what I would've expected; the promise is not fulfilled, and will not suggest unavailable properties:
![image](https://user-images.githubusercontent.com/21252096/184164633-cf92f192-adee-4293-9dd3-f4e90b0c31d9.png)

Notice that it does not show properties that would be undefined, from an unawaited/unfulfilled promise.

Here's an awaited statement
![image](https://user-images.githubusercontent.com/21252096/184164900-892ccd16-8eff-4187-8372-f6f29c49c73a.png)

The reason this is important to me, is to not confuse new developers to the API, and to throw intellisense errors to avoid having to debug after compile-time.

**Comment by IllusionMH** [comment]
As mentioned above - accepting this suggestion should add `(await promiseExpr).acceptedProperty` and not just `promiseExpr.acceptedProperty` (which would be an error).

Do you see some other behavior when you accept these suggestions in async functions?

**Comment by Refzlund** [comment]
> As mentioned above - accepting this suggestion should add `(await promiseExpr).acceptedProperty` and not just `promiseExpr.acceptedProperty` (which would be an error).
> 
> Do you see some other behavior when you accept these suggestions in async functions?

I don't — but as you mention, it seems to be a bug within `async function` or `async () =>`

Works as expected:
![image](https://user-images.githubusercontent.com/21252096/184180692-39b515e8-9b3d-472c-91dd-ca9c5eaf3611.png)

Combines `Promise<T>` with `T`:
![image](https://user-images.githubusercontent.com/21252096/184180844-d5334495-48f7-4a93-ab13-8174da770ada.png)
\* When I say combine, notice that it shows `then`, `catch`, `finally`, but also the result of the promise; `T`

Awaiting the promise `(await promise).` works as expected
![image](https://user-images.githubusercontent.com/21252096/184181157-5bf37102-5c94-4ba9-a0d7-39e22142cd8c.png)

And with that said, the issue seems to be, that it combines the `Promise<T>` with `T` inside `async function`'s when they're not awaited:
![image](https://user-images.githubusercontent.com/21252096/184181927-e9243624-40f2-4f15-bfcc-b97180344562.png)

Back to "this is a feature", if it was a feature, then shouldn't `foo` be `undefined` (and not `true`), since the promise has not been fulfilled?

**Comment by IllusionMH** [comment]
> shouldn't foo be undefined (and not true), since the promise has not been fulfilled?

Not sure how what do you mean under "has not been fulfilled" here? At code edit time there are no pendings/fullilled/rejected promises, but there are are code and types.

`t` has declared promise type and  `foo` should be `true` according to declaration for awaited promise. It's inside of async function therefore showed in suggestions with it's supposed type (when awaited, because suggestion is for awaited type, otherwise all these suggestions would be `undefined`).

See https://github.com/microsoft/TypeScript/issues/31450 tracking issue that was implemented in TS 3.7

**Comment by Refzlund** [comment]
> > shouldn't foo be undefined (and not true), since the promise has not been fulfilled?
> 
> Not sure how what do you mean under "has not been fulfilled" here? At code edit time there are no pending/fullilled/rejected promises, but there are are code and types.
> 
> `t` has declared promise type and `foo` should be `true` according to declaration for awaited promise. It's inside of async function therefore showed in suggestions with it's supposed type (when awaited, because suggestion is for awaited type, otherwise all these suggestions would be `undefined`).
> 
> See [microsoft/TypeScript#31450](https://github.com/microsoft/TypeScript/issues/31450) tracking issue that was implemented in TS 3.7

My bad, I overread the "automatically adds await"

Now I know this goes from bug to opinion — it seems to act more of a distraction and diminishes fast interpretation of the type:

![image](https://user-images.githubusercontent.com/21252096/184219406-61a4c625-a105-4bda-8b1a-42ee50676f7f.png)

The type in my case is `K & Promise<T>`, and so there will be more properties than external to what can be awaited. In the picture above you see 2× `ok`, where one is a function derived from said type `K`, and another is a boolean found in the `Response` type from the Promise.

The types describe what status-codes are returned from from a backend which is generated locally.

Unfortunately, I don't see any way to turn this off at the moment. And I cannot use a utility type like `Omit` to get rid of the extra suggestions. Maybe an option where it will only suggests to _auto-await_ if it only consists of a Promise type, and no intersection/union.

Thanks for the clarification
