### ISSUE TITLE
No types can seem to be found in a brand new project

### ISSUE THREAD

**Issue by sunny-mittal** [microsoft/vscode#157870]
Type: <b>Bug</b>

In a brand new project, all my modules are saying "Cannot find module '\<module\>' or its corresponding type declarations." I scaffolded a new React project with no changes using:
```
$ yarn create react-app . --template=typescript
```
and verified all @types modules that are needed are installed but am not having any luck. This is _not_ an issue with React because it's happening with other modules as well, even those written in TS that have no corresponding @types modules.

VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 7, 7|
|Memory (System)|32.00GB (6.93GB free)|
|Process Argv|--disable-extensions . --crash-reporter-id b5227310-8c05-4a58-b9e1-97d90874b53a|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252

```

</details>

**Comment by mjbvz** [comment]
I can't reproduce this. Are you opening the entire project in VS Code?

Can you also please try collecting the TS Server log for a new project:

1. Set `"typescript.tsserver.log": "verbose",`
1. Restart VS Code and reproduce the problem
1. In VS Code, run the `TypeScript: Open TS Server log` command
1. This should open a large log file called `tsserver.log` 

If you can share the log, I can take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by sunny-mittal** [comment]
@mjbvz I should have followed up and apologize for not doing so. I still have no idea why it's happening but it only happens in one folder on my computer. If I create a new project in another directory, everything works fine. It's very strange and the folder doesn't have anything in it but this one directory alone exhibits the issue.
