### ISSUE TITLE
The cursor position in the terminal is wrong, after the upgrade

### ISSUE THREAD

**Issue by supperODU** [microsoft/vscode#157868]
The cursor position in the terminal is wrong, after the upgrade
![image](https://user-images.githubusercontent.com/29697677/184081926-82bc0421-6e87-4aff-bae1-81cba9ff18aa.png)

**Comment by supperODU** [comment]
I use iTerm2 and zsh
![image](https://user-images.githubusercontent.com/29697677/184082247-2059f6bb-6783-4171-b470-f9406288e27b.png)

**Comment by gjsjohnmurray** [comment]
Please follow the advice at https://code.visualstudio.com/updates/v1_70#_shell-integration-enabled-by-default to disable shell integration. Does this solve your issue?

**Comment by supperODU** [comment]
It works, thank you very much.
