### ISSUE TITLE
Install app dialog is no longer available

### ISSUE THREAD

**Issue by mohammedabdoh** [microsoft/vscode#157928]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Android/Chrome or Samsung Internet browser

Steps to Reproduce:

1.Open your github codespaces and click  on any active ld codespace
2.During loading or connecting to the codespace you  should be asked to install the codespace as a single PWA (progressive web app).

This does not show any more either in chrome or samsung internet browsers

**Comment by joaomoreno** [comment]
Please submit here: https://support.github.com/request/codespaces
