### ISSUE TITLE
VS Code won't load snippet extension in Extension Development Host

### ISSUE THREAD

**Issue by MisterMunchkin** [microsoft/vscode#157994]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: Darwin arm64 21.5.0

### List of extensions
1tontech.angular-material
alexiv.vscode-angular2-files
Angular.ng-template
byCedric.vscode-expo
ChFlick.firecode
christian-kohler.path-intellisense
cschlosser.doxdocgen
cssho.vscode-svgviewer
cyrilletuzi.angular-schematics
dbaeumer.vscode-eslint
dsznajder.es7-react-js-snippets
eamodio.gitlens
EditorConfig.EditorConfig
Equinusocio.vsc-community-material-theme
Equinusocio.vsc-material-theme
equinusocio.vsc-material-theme-icons
esbenp.prettier-vscode
formulahendry.auto-close-tag
formulahendry.auto-rename-tag
Fudge.auto-using
ginfuru.ginfuru-vscode-jekyll-syntax
henoc.svgeditor
infeng.vscode-react-typescript
infinity1207.angular2-switcher
jeff-hykin.better-cpp-syntax
jmrog.vscode-nuget-package-manager
johnpapa.Angular2
johnstoncode.svn-scm
k--kato.docomment
kargware.vscode-extension-jekyll-kw
Kasik96.swift
kreativ-software.csharpextensions
loiane.angular-extension-pack
mathiasfrohlich.Kotlin
ms-dotnettools.csharp
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-vscode-remote.remote-containers
ms-vscode-remote.remote-ssh
ms-vscode-remote.remote-ssh-edit
ms-vscode-remote.remote-wsl
ms-vscode.cmake-tools
ms-vscode.cpptools
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-vscode.hexeditor
obenjiro.arrr
pmneo.tsimporter
PrateekMahendrakar.prettyxml
quicktype.quicktype
rbbit.typescript-hero
rctay.karma-problem-matcher
redhat.java
redhat.vscode-xml
RobbOwen.synthwave-vscode
segerdekort.angular-cli
SimonTest.simontest
stringham.move-ts
syler.sass-indented
twxs.cmake
VisualStudioExptTeam.vscodeintellicode
vscjava.vscode-java-debug
vscjava.vscode-java-dependency
vscjava.vscode-java-pack
vscjava.vscode-java-test
vscjava.vscode-maven
wart.ariake-dark
zhouronghui.propertylist

### Steps to Reproduce:

1. run 'npm install -g yo generator-code'
2. run 'yo code'
3. answered questions for extension generator:
 ? What type of extension do you want to create? New Code Snippets
Folder location that contains Text Mate (.tmSnippet) and Sublime snippets (.sublime-snippet) or press ENTER to start with a new snippet file.
? Folder name for import or none for new: 
? What's the name of your extension? simple-markdown-snippets
? What's the identifier of your extension? simple-markdown-snippets
? What's the description of your extension? Snippets for simple markdown like bold, code, frontmatter, etc.
Enter the language for which the snippets should appear. The id is an identifier and is single, lower-case name such as 'php', 'javascript'
? Language id: markdown
? Initialize a git repository? Yes
5. Added object in snippets.code-snippets
6. fn + f5
7. create .md file and try out the snippet

### Expected Behavior
See the snippet I made

### Actual Behavior
It does nothing

### Additional Info
I also tried adding the extension folder into my .vscode/extensions folder but no changes. In the debug console I saw the angular-folder-switcher extension load, so I tried disabling the extension but yea, nothing happens. No errors displayed in debug console.

The JSON in my snippets.code-snippets
`{
    "Markdown Code Snippet": {
        "prefix": "!code",
        "body": [
            "```<language> title='Title'",
            "```"
        ],
        "description": "Markdown 'code' template for docusaurus"
    }
}`

**Comment by jrieken** [comment]
> create .md file and try out the snippet

How do you try it out? Via F1 > Insert Snippet? Via suggest?

**Comment by MisterMunchkin** [comment]
Oh... doing > Insert Snippet showed my snippet. I tested by going to a .md file and typing '!code' to see if a suggestion would pop up.

**Comment by MisterMunchkin** [comment]
Got it to show in intellisense, needed to add this to my settings.json before running the dev host
`    "[markdown]": {
        "editor.quickSuggestions": {
            "other": "on",
            "comments": "inline",
            "strings": "inline"
        }
    }`

Thanks for leading me to the right direction 😂
