### ISSUE TITLE
[Linux] EACCES on temporary socket with custom temp dir

### ISSUE THREAD

**Issue by anatoli26** [Microsoft/vscode#15790]
- VSCode Version: 1.7.1-1478180561
- OS Version: Ubuntu 16.04.1
- Custom temp dir for the user is defined: `cat /etc/environment`: `TMP=~/.tmp`

Steps to reproduce: try starting code, e.g. from terminal: `/usr/share/code/code`, getting:
```
Error: listen EACCES ~/.tmp/Code-eaa8ce-1.7.1.sock
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1378:5)
    at /usr/share/code/resources/app/out/vs/code/electron-main/main.js:6:31339
    at new n.Class.derive._oncancel (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:6:5711)
    at Object.c [as serve] (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:6:31269)
    at i (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:11:19705)
    at q (/usr/share/code/resources/app/out/vs/code/electron-main/main.js:11:20776)
```

If I redefine TMP dir, e.g. `export TMP=/tmp`, code starts.

The per-user TMP dir has the following permissions:
`drwx------ 34 userX userX 4,0K nov 21 04:08 /home/userX/.tmp/`

Changing its mode and the mode of the user's home dir to 777 doesn't help.

**Comment by joaomoreno** [comment]
Try expanding the `~` by setting `TMP=/home/userX/.tmp`.

**Comment by anatoli26** [comment]
It's a global setting in /etc/environment, this is what each user inherits, can't put there a fixed path.

**Comment by joaomoreno** [comment]
It's wrongly set.

`~` only means `$HOME` when evaluated inside a shell.

To prove it, just open a terminal and try to run `mkdir $TMP`. It will attempt to create a folder called `~` instead of attempting to create `/homer/userX/.tmp`.

**Comment by joaomoreno** [comment]
It seems to be incorrectly set then. What do you get when running `echo $TMP` in a terminal? You should see `/home/userX/.tmp` and not `~/.tmp`.

**Comment by anatoli26** [comment]
```
echo $TMP
~/.tmp
```
All other apps understand it. The first app that had a problem with this setting was code.

**Comment by joaomoreno** [comment]
I very much doubt that. The special character `~` is only understood to be your home folder by a shell. Applications don't know what it means and will handle it as a folder literally named `~`.

What do you get from running this?

```
node -p "os.tmpdir()"
```

**Comment by anatoli26** [comment]
I don't have node installed, but I see that the TMP value as specified could be an issue. One other node-based app (atom editor) also fails to create temp socket in the path (though it was not failing completely, it was just silently writing the error to the logs and continuing without a temp socket), though other non-node apps (Thunderberd, etc.) work well.

I believe we can close this issue, I'll adapt my settings and VSCode doesn't have much to do with the error, and I believe it doesn't make sense to ask node devs to support such an edge case, though other apps do support it.
