### ISSUE TITLE
[php] Syntax highlighting breaks for <?php ?> between <script></script> tags

### ISSUE THREAD

**Issue by dinuionut** [Microsoft/vscode#15792]
- VSCode Version: 1.7.0 / 1.7.1 / 1.8.0
- OS Version: macOS Sierra / Windows

Steps to Reproduce:

1. Open any .php file
2. Insert &lt;script&gt;&lt;?php ?&gt;&lt;/script&gt; anywhere
3. The syntax highlighting for the rest of the .php code breaks

Description:

We have a lot of .php files containing HTML and sometimes &lt;script&gt; tags with PHP variables inside them. If the PHP variable is echoed in one line inside the &lt;script&gt;, like &lt;script&gt;&lt;?php echo $var; ?&gt;&lt;/script&gt;, the syntax highlighting breaks for the rest of the PHP code after that line. 
However, it seems to work if you move the closing ?&gt; tag inside the &lt;script&gt; on a new line. It also works fine on VS Code 1.6.1.

Example:

&lt;?php 
&nbsp;&nbsp;&nbsp;&nbsp;echo $test; 
&nbsp;&nbsp;&nbsp;&nbsp;// syntax highlighting ok 
?&gt; 
&lt;script&gt; 
&nbsp;&nbsp;&nbsp;&nbsp;&lt;?php echo $test; ?&gt; 
&lt;/script&gt; 
&lt;?php 
&nbsp;&nbsp;&nbsp;&nbsp;echo $test; 
&nbsp;&nbsp;&nbsp;&nbsp;// syntax highlighting broken 
?&gt;

**Comment by aeschli** [comment]
This issue was moved to atom/language-php#172

**Comment by Tyriar** [comment]
Opening as it's not fixed and it's a problem with VS Code. I think @alexandrudima was working on fixing the root cause.

**Comment by alexandrudima** [comment]
@aeschli This looks like it has something to do with L: prefixes in injections

**Comment by SilvioLobo** [comment]
- VSCode Version: Code 1.12.2
- OS Version: Windows 10 x64
- Color Theme: Monokai

Still happening for me.
Also, if you try to insert HTML inside of a PHP's curly braces, the HTML syntax highlighting breaks too.

**Example updated**:
```
<?php
    echo $test;
    // syntax highlighting ok
?>
<script>
    <?php echo $test; ?>
</script>
<?php
    echo $test;
    // syntax highlighting broken
?>
    <input></input>
     <!-- HTML syntax highlighting ok -->
<?php if(true) { ?>
    <input id="test"></input>
    <!-- HTML syntax highlighting broken -->
<?php } ?>
```

Removing <script></script> will also fix this HTML syntax highlighting.
