### ISSUE TITLE
Current line decoration bleeds onto line numbers

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#15799]
![image](https://cloud.githubusercontent.com/assets/22350/20481161/12348682-afe6-11e6-934b-2a099de1949d.png)

![image](https://cloud.githubusercontent.com/assets/22350/20481168/19a13960-afe6-11e6-9815-2359b2c70d84.png)

**Comment by rebornix** [comment]
Current line highlight in gutter makes this problem more explicit but it's not the only cause. 

Part of the git delete indicator is outside the containing dom node visually, which means any line decorations of the following line can override/cover the outside part of the delete indicator, whether the decoration is created by us or extensions.

Take below code into consideration, there is a delete indicator between line 16 and 17, and there is an addition indicator before line 27.

![screen shot 2016-11-21 at 1 48 28 pm](https://cloud.githubusercontent.com/assets/876920/20502037/376645c0-aff1-11e6-9416-1a9b396a3d41.png)


If we fold `function includes`, we can see the addition indicator eats the bottom half of the delete indication

![screen shot 2016-11-21 at 1 48 52 pm](https://cloud.githubusercontent.com/assets/876920/20502052/444caa54-aff1-11e6-8a7f-e2f91970b90b.png)

So now we have a more generic problem: how to deal with decorations which visually sit on top of two or more lines.
