### ISSUE TITLE
Moving a file to trash that is in use does not indicate error

### ISSUE THREAD

**Issue by tSte** [microsoft/vscode#15793]
- VSCode Version:
- OS Version: 1.7.1

Steps to Reproduce:

1. Create "file in use"
2. Delete that file via VS Code
3. Refresh the explorer

My case: I have selenium standalone server and web drivers. My selenium server is running and drivers are in use, so they cannot be removed. However if I attempt to remove such a file via VS Code, it will be successfully deleted from explorer without any warning. After I refresh the VS Code explorer, "removed" file is still present.

**Comment by bpasero** [comment]
@tSte what is the issue you want to report here? the fact that you cannot remove the file or the fact that you do not see an error when trying to remove a file that is in use? What OS are you on?

**Comment by tSte** [comment]
VS Code removes a file from the Explorer without any warning. I would expect VS Code both not to remove a file and warn that it is not possible to remove that file because of some reason.

**Comment by bpasero** [comment]
I can reproduce and the issue seems to be that `shell.moveItemToTrash()` in the case of a file in use does not return an error.
