### ISSUE TITLE
Integrated Terminal Shell Integration powerline last_pipeline_status always 1

### ISSUE THREAD

**Issue by branic** [microsoft/vscode#157990]
Type: <b>Bug</b>

With Shell Integration enabled for the integrated terminal `powerline.segments.shell.last_pipe_status` always shows as `1`.

In my [powerline theme](https://github.com/branic/dotfiles/blob/master/.config/powerline/themes/shell/brant.json) I have the following setting:

```
			{
				"function": "powerline.segments.shell.last_pipe_status",
				"priority": 10
			}
```

Commands return the proper code, shell integration correctly sets the indicator, and the return code is the proper code as can be seen in the below pictures:

**Return Code 0:**
![image](https://user-images.githubusercontent.com/13800082/184320363-9ef3a427-c508-4ccf-b260-6c8aadb319e5.png)

**Return Code 2:**
![image](https://user-images.githubusercontent.com/13800082/184320397-4dc8f249-5a83-4f5e-b6ca-fa70bc933aed.png)

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)
OS version: Linux x64 5.18.15-200.fc36.x86_64
Modes:
Remote OS version: Linux x64 5.18.15-200.fc36.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|62.56GB (2.69GB free)|
|Process Argv|--unity-launch --crash-reporter-id 57fdd0a5-4103-4bed-9134-70c1dcd69cc9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-xorg|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Python 2.7|
|OS|Linux x64 5.18.15-200.fc36.x86_64|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2700)|
|Memory (System)|62.56GB (2.69GB free)|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
scratchpads|bue|0.0.7
solargraph|cas|0.23.0
vscode-markdownlint|Dav|0.47.0
ansible-vault|dho|0.1.3
docs-markdown|doc|0.2.113
githistory|don|0.6.19
gitlens|eam|12.1.2
json-tools|eri|1.0.2
opensslutils|ffa|1.1.1
shell-format|fox|7.2.2
gc-excelviewer|Gra|4.2.55
todo-tree|Gru|0.0.215
rest-client|hum|0.25.0
vscode-jmespath|jos|0.0.6
bash-ide-vscode|mad|1.14.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.1
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.245.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.11.5
ruby|reb|0.28.1
ansible|red|0.11.29
vscode-commons|red|0.0.6
vscode-yaml|red|1.9.1
bash-debug|rog|0.3.9
rufo-vscode|sil|0.0.3
code-spell-checker|str|2.5.4
shellcheck|tim|0.19.6
pdf|tom|1.2.0
vscode-icons|vsc|11.15.0
vim|vsc|1.23.2
jinja|who|0.0.8
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912cf:30529770
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253

```

</details>

**Comment by evanlin96069** [comment]
Got the same issue.

Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

Also, there's a typo in the topic. It should be powerline, not powershell.
