### ISSUE TITLE
The code suddenly retreats, which is likely to be a bug

### ISSUE THREAD

**Issue by ooijopk** [microsoft/vscode#157984]
The version is 1.70.0. The previous versions also have this problem. It can't be reproduced. Press Ctrl + Z to restore the latest code. Pictures can't be added here. I'm sorry, but the problem really exists. It's not a plug-in problem, because I closed all the plug-ins. It seems that I suddenly fell back when I reopened them.

**Comment by hediet** [comment]
Can you provide reproduction steps or a screen recording?

**Comment by ooijopk** [comment]
When saving, the code will be automatically formatted, and the code will disappear. I should be the formatting problem here
