### ISSUE TITLE
Timeline for the resolvers proposal (or parts thereof) to make it main

### ISSUE THREAD

**Issue by jeremie-stripe** [microsoft/vscode#157958]
Hello!

We are interested in leveraging the [resolvers proposed API](https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.resolvers.d.ts) and specifically the part that adds [`workspace.registerResourceLabelFormatter`](https://github.com/microsoft/vscode/blob/cad50f2b13c9d09e9f693b2d039507216496aaa0/src/vscode-dts/vscode.proposed.resolvers.d.ts#L211) to improve the experience of our users when using VSCode remote support.

Our fleet of dev machines have fairly abstract hostnames that do not mean much and so instead of showing that hostname in the remote badge in the bottom left of the UI (the one that says "SSH: [hostname]:[port]") and instead we would like to show the friendly name that we have attached to the machine separately.

The normal resource label formatter extension point does not allow us to do this easily as to be able to [override the resolution step more easily](https://github.com/microsoft/vscode/blob/cad50f2b13c9d09e9f693b2d039507216496aaa0/src/vs/workbench/services/label/common/labelService.ts#L179-L185) we need to ideally be able to specify the whole hostname as the `authority` section. Additionally we have to actually read the friendly name from an external source meaning we need to execute some code to compute it. With this part of the proposed API this becomes a breeze to implement and works excellently however as with all proposed API it's a [pain for us to use in practice](https://code.visualstudio.com/api/advanced-topics/using-proposed-api#sharing-extensions-using-the-proposed-api).

[Going back in time](https://github.com/microsoft/vscode/blame/4e8450ad93346ef2b6c4a78cfe5e58ed623ddd37/src/vscode-dts/vscode.proposed.d.ts), this API has been in the proposed bucket for more than 4 years. Can we expect this API to become part of the mainline at any point soon?

Thanks!

**Comment by jvilk-stripe** [comment]
For backstory:
* Stripe is beginning to roll out remote development.
* Stripe engineers can have multiple remote development machines. Each has a friendly internal name that the engineer chooses, but a random-ish hostname.
* We have no good place in the VS Code UI to display the friendly name. When engineers are working on multiple machines at once, it is hard for them to know which window is pointed to which machine.

The proposed API allows us to register a resource label formatter for vscode-remote that displays the friendly name in the bottom left corner instead of the unfriendly hostname.

**Comment by lramos15** [comment]
Will discuss this with the team and see where we stand on the state of things here. Expect an update in Late January / Early February just due to the fact that we're cleaning up issues at the moment and the upcoming holiday season. Thank you for your patience.

**Comment by jeremie-stripe** [comment]
OK. We ended up going a different route to do what we wanted to do so I'm also fine if you want to close this issue (I already closed the attached PR).
