### ISSUE TITLE
code conflict does not show highlight

### ISSUE THREAD

**Issue by ArthurChi** [microsoft/vscode#157997]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.1
- OS Version: macos 12.5

Steps to Reproduce:

1. open a code conflict file

**Comment by gjsjohnmurray** [comment]
In 1.70 the new merge editor, introduced in [1.69](https://code.visualstudio.com/updates/v1_69#_3-way-merge-editor) became the [default](https://code.visualstudio.com/updates/v1_70#_3way-merge-editor-improvements).

Is that what you are seeing?

Are you able to paste a screenshot to help explain your issue?

**Comment by ejaazkhan** [comment]
![image](https://user-images.githubusercontent.com/67804911/184355010-96e12af3-ef17-4349-a68a-9248467aa564.png)
Same issue not showing highlight, Instead It highlighted whole file
