### ISSUE TITLE
Right click duplicated context menu

### ISSUE THREAD

**Issue by zhdaniel** [microsoft/vscode#157973]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.70.1
Date: 2022-08-10T06:09:06.916Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.3.0
- OS Version: macOS 12.2.1

Steps to Reproduce:

1. right click, duplicate context menu
![image](https://user-images.githubusercontent.com/1702329/184275841-b6e0054d-7e68-4d84-8b67-8b6edf6157c6.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by zhdaniel** [comment]
Thanks a lot, I figured out it caused by the extension.
