### ISSUE TITLE
visual studio code for CS50

### ISSUE THREAD

**Issue by Xeeshan85** [microsoft/vscode#157906]
I'm having a serious problem in running the code spaces. Every i try so the code spaces collapse and restart. kindly give me sugestion to solve this issue.

**Comment by gjsjohnmurray** [comment]
Assuming CS50 is a computer science course I suggest you consult your course helpdesk.

**Comment by rongxin-liu** [comment]
You could also post issues on https://github.com/orgs/community/discussions/new and choose "Codespace" category to get proper attention. @Xeeshan85
