### ISSUE TITLE
Sticky scroll header covering top line

### ISSUE THREAD

**Issue by jsartelle** [microsoft/vscode#157967]
Type: <b>Bug</b>

Enable Sticky Scroll, and create a new file with the following contents:

```js
exports.up = async (knex) => {
	await knex.schema.alterTable('abc', (t) => {
		t.varchar('abc', 64).nullable().after('abc')
	})
}
```

The sticky scroll header covers up the first line of code with a duplicate of the second line. This was tested on vscode.dev with no extensions installed.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:46.959Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.05GB free)|
|Process Argv|--crash-reporter-id 1b832d67-fc36-4de1-aadd-fbe418426a38|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (92)</summary>

Extension|Author (truncated)|Version
---|---|---
blocksort|1nV|0.9.0
http-status-codes|bea|1.0.5
vscode-node-readme|ben|3.0.2
vscode-fish|bma|1.0.29
vscode-tailwindcss|bra|0.8.6
vscode-toggle-quotes|Bri|0.3.6
file-properties-viewer|bru|1.0.0
quill-icons|cdo|0.0.2
vscode-margin-colours|chi|1.4.0
visubezier|chr|1.4.0
npm-intellisense|chr|1.4.2
gitignore|cod|0.9.0
disableligatures|Coe|0.0.10
activitybar-separator|ctf|0.0.1
snippetier|daf|0.1.0
dakara-foldplus|dak|1.5.2
transformer|dak|1.12.1
vue-peek|dar|1.0.2
swap-word|dav|0.1.2
ini-for-vscode|Dav|0.0.4
jshint|dba|0.11.0
vscode-eslint|dba|2.2.6
synonym-finder|Dig|1.0.1
yarn-task-provider|dkn|0.2.2
xml|Dot|2.5.1
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
sweet-vscode-icons|Eli|0.0.1
moxer-icons|Equ|5.8.0
prettier-vscode|esb|9.5.0
vscode-eval|exp|1.2.1
vscode-browser-refresh|fab|1.2.0
vscode-commands|fab|1.4.3
vscode-open-multiple-files|fab|1.4.0
vscode-search-open-all-results|fab|1.0.3
shell-format|fox|7.2.2
vscode-icontheme-nomo-dark-macos|Gau|1.0.3
vscode-pull-request-github|Git|0.48.1
todo-tree|Gru|0.0.215
mnemonicons|hec|1.3.0
vscode-power-mode|hoo|3.0.2
smartmulticursor|ida|0.0.4
path-autocomplete|ion|1.20.2
vs-focus|Ivo|0.0.6
search-editor-apply-changes|jak|0.1.1
mysql-syntax|jak|1.3.1
vscode-text-pastry|jkj|1.3.1
svg|joc|1.4.19
bracket-peek|jom|1.4.4
vscode-random|jre|1.11.0
web-clipper|jsa|1.0.1
center-editor-window|kai|2.3.0
vscode-colorize|kam|0.11.1
openwithcode|kev|1.0.4
l13-diff|L13|1.0.3
vue-discovery|maa|1.4.0
template-string-converter|meg|0.6.0
dotenv|mik|1.0.1
ecdc|mit|1.8.0
vscode-attrs-sorter|mrm|2.1.0
vscode-autoprefixer|mrm|3.0.1
vscode-postcss-sorting|mrm|3.0.1
vsliveshare|ms-|1.0.5683
vscode-react-native|msj|1.9.2
vetur|oct|0.36.0
linesinfostatusbar|pet|0.0.7
nested-comments|phi|3.0.3
material-product-icons|PKi|1.4.0
vscode-seedling-icon-theme|ras|0.10.0
tabster|rib|0.0.6
json-organizer|rin|0.0.4
multi-command|ryu|1.6.0
multiple-entry|sam|1.0.0
vscode-open|san|0.1.0
vscode-sanity|san|0.1.4
vscode-fileutils|sle|3.5.0
numbermonger|sof|0.5.0
html-to-css-autocompletion|sol|1.1.2
vscode-open-in-gitfork|spa|1.0.3
vscode-stylelint|sty|1.2.2
find-then-jump|tra|2.0.5
lorem-ipsum|Tyr|1.3.1
errorlens|use|3.6.0
sensitive-replace|vil|0.1.1
quokka-vscode|Wal|1.0.497
ws-rainmeter|wil|0.2.7
in-any-case|wil|2.0.0
vscode-nonicons|yam|0.0.12
five-server|yan|0.1.5
cursor-align|yo1|1.1.0
markdown-all-in-one|yzh|3.4.3
sort-js-object-keys|zen|1.0.6

(10 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyonecf:30545436

```

</details>

**Comment by aiday-mar** [comment]
Hi, on my computer I tested and see the following:

![sticky-scroll-ts](https://user-images.githubusercontent.com/61460952/184320059-0574aedc-52a1-46e5-b8d6-004429c3df54.gif)

You may reproduce this new behavior by installing VSCode Insiders. These changes will be available in the stable versionof VSCode in next month's release.
