### ISSUE TITLE
Documentation: Add option to return to the previous Git resolver

### ISSUE THREAD

**Issue by bichotll** [microsoft/vscode#157913]
It would be nice if you could document how to return to the previous source resolver.

**Context:**
The new 3-way git resolver is not clear enough when you have multiple conflicts.

It was difficult for me to find out how to return to the old system one.

For the record, for others who wish to do the same:
- Disable Git: Merge Editor
- Enable Git > Decorations: Enabled

![image](https://user-images.githubusercontent.com/643359/184172204-0f603bc5-9a79-4c82-a9cf-c5f5856719ad.png)

**Comment by gjsjohnmurray** [comment]
I am surprised you needed to change `git.decorations.enabled`

I expected you to have to enable `diffEditor.codeLens`

**Comment by bichotll** [comment]
@gjsjohnmurray From what I saw, decorators glow the area in two different colours, right? That it's just a nice add.
I'm on a different computer atm. I'll take a look tomorrow.

It's just that it took me a fair amount of time to figure out how to revert to the non-3-ways resolver.

**Comment by zigang93** [comment]
I really don't like how the 3-way resolver look. I don't understand that why don't let the user to choose the which resolver to use ?
