### ISSUE TITLE
Suggest to allow specific the file type manually 

### ISSUE THREAD

**Issue by zealitude** [Microsoft/vscode#15791]
Most of the plugin only trigger under specific file type.
It would be best if I can define what is the current file type, so that I don't need to change the file type to fulfill the condition of those plugin/syntax highlight.

Especially, I would like to have a syntax highlight feature in a temporary 'new file'(ctrl+N) without save it into real file.

**Comment by jrieken** [comment]
@zealitude Do you mean this?

<img width="876" alt="screen shot 2016-11-22 at 08 58 27" src="https://cloud.githubusercontent.com/assets/1794099/20515424/e1ae6990-b091-11e6-955a-84d258b3fed5.png">

**Comment by zealitude** [comment]
Oh, yes...it is exactly what I want except it is a command.
please close this issue, thank you.

**Comment by jrieken** [comment]
Great!
