### ISSUE TITLE
Integrated terminal is broken

### ISSUE THREAD

**Issue by givehug** [microsoft/vscode#157910]
Type: <b>Bug</b>

Cannot open more than 1 tab in the integrated terminal since morning update.

VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.61GB free)|
|Process Argv|--crash-reporter-id 2c1cf49e-c2b0-4b72-a361-7b8959436d9a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.1
codestream|Cod|13.4.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
vscode-jest-runner|fir|0.4.48
go|gol|0.35.1
terraform|has|2.23.0
vscode-env|Iro|0.1.0
Kotlin|mat|1.7.1
ts-error-translator|mat|0.5.1
vscode-react-native|msj|1.9.2
project-snippets|reb|0.5.0
sonarlint-vscode|Son|3.8.0
code-spell-checker|str|2.5.4

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912cf:30529770
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by givehug** [comment]
Can't reproduce anymore today 🤷‍♂️... Friday. Will keep an eye on it.
