### ISSUE TITLE
Tree dosen't display all items

### ISSUE THREAD

**Issue by lgund** [microsoft/vscode#157943]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.70.1 (user setup)
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Datum: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
Betriebssystem: Windows_NT x64 10.0.22621
- OS Version:
Windows 11 22H2

Steps to Reproduce:
If you have a normal tree provider and create a tree with more items then ~5 like this:

```
   async getChildren(element?: BaseTreeItem | undefined): Promise<BaseTreeItem[] | null | undefined> {
      if (element === undefined) {
         const items = new Array<BaseTreeItem>();
         const projects = await this.gitService?.getProjekte();
         if (projects !== undefined) {
            for (const project of projects) {
               console.log(project);

               items.push({
                  label: project.name,
                  iconPath: new vscode.ThemeIcon("project"),
                  collapsibleState: vscode.TreeItemCollapsibleState.None,
                  command: {
                     title: "Projekt auswählen",
                     command: "git-manager-internal.select-project",
                     arguments: [project],
                  },
                  tooltip: project.description,
                  id: project.webUrl,
                  description: project.id.toString(),
               });
            }
         }
         console.log("ITEMS", items);
         return items;
      }

      return Promise.resolve([]);
   }
```

In this example above the  `console.log("ITEMS", items);` get this result for me:
![image](https://user-images.githubusercontent.com/13957661/184215761-bc6fc512-57ed-47e4-8d72-94c2851735c0.png)

After I launch the extension I got my list looks like this:
![image](https://user-images.githubusercontent.com/13957661/184216126-febc3f61-52d6-4e2b-9a94-e1ddda1c12a4.png)
Even under the `Phoenix Bot` element is a hidden element....

After I scroll the "Projekte" tab to the minimal height and back again I got this result:
![image](https://user-images.githubusercontent.com/13957661/184216294-5157ae77-4327-4247-bc9a-70f66f28c49c.png)

**Comment by alexr00** [comment]
@lgund thank you for the example, but I'm not able to reproduce this issue. Are you able to reproduce it using the [tree view sample](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample), maybe with the json outline sample there?

**Comment by lgund** [comment]
After I tried to create you the example I found the problem. The invisible element does destroy the rendering. After checking the tree properties i got the error. The property tooltip was in the invisible element _NULL_ . And _NULL_ is not allowed. It would be nice if there will be a warning from vscode that the value can't be _NULL_

**Comment by alexr00** [comment]
Starting with version 1.70, we do have an error that shows in the console for your case:
```
[Extension Host] INVALID tree item, invalid tooltip null 
```
In 1.71 or 1.72 we'll start throwing an error earlier.
