### ISSUE TITLE
Inspect Editor Tokens and Scopes does not appear in the Ctrl-Shift-P search.

### ISSUE THREAD

**Issue by ableunable** [microsoft/vscode#157926]
Type: <b>Bug</b>

Greetings.

I was looking to customise my setup by altering fonts based on the scope (e.g. different font on keywords). I was following a guide [here](https://www.stefanjudis.com/blog/how-to-enable-beautiful-cursive-fonts-in-your-vs-code-theme/) and it said to go to Inspect Editor Tokens and Scopes. However, looking it up in VSCode, it does not appear, unlike the screenshot in the guide. This happens without extensions as well as with them. If I knew how to add a screenshot here, I would. You will just have to imagine the entry missing in the search.

Edit: I have searched already on the internet as well as within the issues on this repo. No luck. Maybe it's due to not being a native speaker and thus being unable to precisely phrase the search text required to find the solution.

Please, help me to resolve this issue.

Steps to reproduce:

1. Press Ctrl-Shift-P to focus on the search bar.
2. Type in "insp" or the full string "Inspect Editor Tokens and Scopes".

Expected behaviour: Find it.

What happens instead: It does not appear in the list.

I had to make part of the line below into inline code because otherwise GitHub thought I was referring to another issue with part of the long string. Other than that, I have made no changes to the auto-generated text.

VS Code version: `Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)`
OS version: Linux x64 5.18.16-arch1-1
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Quad CPU    Q6600  @ 2.40GHz (4 x 2136)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|3.83GB (0.41GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1f1d80c3-04a8-493a-95c1-dad988f2edf2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|i3|
|XDG_CURRENT_DESKTOP|i3|
|XDG_SESSION_DESKTOP|undefined|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.7.1002181843
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vsliveshare|ms-|1.0.5683

</details>

**Comment by hediet** [comment]
Cannot reproduce in latest insiders:

![image](https://user-images.githubusercontent.com/2931520/184357239-1fe4b6ab-2d33-43af-a829-e3b53667ac59.png)

**Comment by ableunable** [comment]
Greetings, Hediet. What info do you need (regarding the label you added)? VSCode provided some info automatically, I can provide more if you like, but I can't without knowing what you need.

I have installed the latest binary from AUR (I did not use the OSS version due to it not having Live Share). You as an employee may have access to those insiders' builds but I as a user and outsider only have the releases, which logically are behind the latest non-released builds. Please provide some info if you know, about how to fix this issue on the release. Alternatively, instruct me on how to approach the inspection of tokens and scopes in another way than the search bar.

**Comment by Drerootz1** [comment]
My Money

**Comment by yume-chan** [comment]
Note that an opened file is required to use inspect tokens and scopes.

**Comment by ableunable** [comment]
Thank you, yume-chan! That was very helpful, as I was able to access the inspection with an opened file. My problem is resolved.
