### ISSUE TITLE
Snippet variables not detected after double backslash

### ISSUE THREAD

**Issue by maxlorenz** [Microsoft/vscode#158]
In a LaTeX snippet, it is not possible to declare a variable after a double backslash.
Example:
```json
    "section": {
		"prefix": "sec",
		"body": [
			"\\${1:sub}section${2:*}{${3:label}}",
			"\n\t$4"
		],
		"description": "Start a subsection"
    }
```

expands to
```tex
    \${1:sub}section*{label}
```

**Comment by alexandrudima** [comment]
@maxlorenz 

Since this is JSON, `"\\${1:sub}section${2:*}{${3:label}}"` becomes `\${1:sub}section${2:*}{${3:label}}` at runtime. We need to have a way for a snippet to insert an actual `$` and that is `\$`. 

The following does the right thing:
```json
    "section": {
        "prefix": "sec",
        "body": [
            "\\\\${1:sub}section${2:*}{${3:label}}",
            "\n\t$4"
        ],
        "description": "Start a subsection"
    }
```
