### ISSUE TITLE
"Cannot clone recursive data-structure" error occurs when the quick fix code action menu collapses

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#158054]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:Version: 1.71.0-insider (user setup)
Commit: eebdf8174b087979ae6af103f6f2e2f6f9062056
Date: 2022-08-12T05:17:00.323Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

Steps to Reproduce:

1. Expand/collapse the code action lightbulb menu with code at https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/main.ts#L192 or use some other code repro to make the quick fix lighbulb menu appear/disappear.

Toggle developer tools console shows: "Cannot clone recursive data-structure". It doesn't repro with non-Insiders.

**Comment by justschen** [comment]
Seems to be an issue with disposables - looking into this as well atm!
