### ISSUE TITLE
VSCode extremely slow to launch

### ISSUE THREAD

**Issue by techthoughts2** [microsoft/vscode#158059]
After I updated recently VSCode now launches extremely slowly.
During launch I get the following warning prompt:

```
The window is not responding
You can reopen or close the window or keep waiting.
```

If I click Keep Waiting it does open in about 48s.

I have tried running ```code --disable-extensions``` and it has the same behavior.

## System Info

* Code: 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda)
* OS: win32(10.0.22000)
* CPUs: 11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz(8 x 2995)
* Memory(System): 63.69 GB(52.82GB free)
* Memory(Process): 198.12 MB working set(173.06MB private, 0.08MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                        |
| --------------------------------------------------------------- | -------- | ------------------------- | ----------------------------------------------------------- |
| start => app.isReady                                            | 65       | [main]                    | initial startup: true                                       |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                       |
| require(main.bundle.js)                                         | 99       | [main]                    | initial startup: true                                       |
| start crash reporter                                            | 0        | [main]                    | initial startup: true                                       |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                       |
| create window                                                   | 45       | [main]                    | initial startup: true, state: 1ms, widget: 14ms, show: 28ms |
| app.isReady => window.loadUrl()                                 | 207      | [main]                    | initial startup: true                                       |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 79896    | [main->renderer]          | NewWindow                                                   |
| require(workbench.desktop.main.js)                              | 833      | [renderer]                | cached data: NO, node_modules took 0ms                      |
| wait for window config                                          | 0        | [renderer]                | -                                                           |
| init storage (global & workspace)                               | 70       | [renderer]                | -                                                           |
| init workspace service                                          | 69       | [renderer]                | -                                                           |
| register extensions & spawn extension host                      | 411      | [renderer]                | -                                                           |
| restore viewlet                                                 | 112      | [renderer]                | workbench.view.explorer                                     |
| restore panel                                                   | 68       | [renderer]                | terminal                                                    |
| restore & resolve visible editors                               | 10768    | [renderer]                | 1: workbench.editors.untitledEditorInput                    |
| overall workbench load                                          | 11225    | [renderer]                | -                                                           |
| workbench ready                                                 | 92317    | [main->renderer]          | -                                                           |
| renderer ready                                                  | 12156    | [renderer]                | -                                                           |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                           |
| extensions registered                                           | 82213    | [renderer]                | -                                                           |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1660362441910	0	0
code/didStartMain	1660362442064	154	154
code/willStartCrashReporter	1660362442084	20	174
code/didStartCrashReporter	1660362442084	0	174
code/mainAppReady	1660362442129	45	219
code/willLoadMainBundle	1660362442130	1	220
code/fork/willLoadCode	1660362442146	16	236
code/registerFilesystem/file	1660362442224	78	314
code/didLoadMainBundle	1660362442229	5	319
code/willStartMainServer	1660362442242	13	332
code/didStartMainServer	1660362442244	2	334
code/willCreateCodeWindow	1660362442289	45	379
code/willRestoreCodeWindowState	1660362442289	0	379
code/didRestoreCodeWindowState	1660362442290	1	380
code/willCreateCodeBrowserWindow	1660362442290	0	380
code/didCreateCodeBrowserWindow	1660362442304	14	394
code/willMaximizeCodeWindow	1660362442305	1	395
code/didMaximizeCodeWindow	1660362442333	28	423
code/didCreateCodeWindow	1660362442334	1	424
code/willOpenNewWindow	1660362442336	2	426
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1660362442337	0	0
code/didStartRenderer	1660362522225	79888	79888
code/willWaitForWindowConfig	1660362522225	0	79888
code/didWaitForWindowConfig	1660362522225	0	79888
code/willShowPartsSplash	1660362522225	0	79888
code/didShowPartsSplash	1660362522226	1	79889
code/willLoadWorkbenchMain	1660362522232	6	79895
code/didLoadWorkbenchMain	1660362523065	833	80728
code/registerFilesystem/file	1660362523073	8	80736
code/registerFilesystem/vscode-userdata	1660362523073	0	80736
code/willInitWorkspaceService	1660362523079	6	80742
code/willInitStorage	1660362523080	1	80743
code/willInitUserConfiguration	1660362523087	7	80750
code/didInitUserConfiguration	1660362523129	42	80792
code/willInitWorkspaceConfiguration	1660362523129	0	80792
code/didInitWorkspaceConfiguration	1660362523148	19	80811
code/didInitWorkspaceService	1660362523148	0	80811
code/didInitStorage	1660362523150	2	80813
code/willStartWorkbench	1660362523156	6	80819
code/LifecyclePhase/Ready	1660362523262	106	80925
code/registerFilesystem/trustedDomains	1660362523300	38	80963
code/registerFilesystem/vscode-local-history	1660362523303	3	80966
code/registerFilesystem/vscode-debug-memory	1660362523455	152	81118
code/willRestoreEditors	1660362523613	158	81276
code/willRestoreViewlet	1660362523626	13	81289
code/willRestorePanel	1660362523670	44	81333
code/didRestoreViewlet	1660362523738	68	81401
code/didRestorePanel	1660362523738	0	81401
code/willLoadExtensions	1660362523866	128	81529
code/willHandleExtensionPoints	1660362523980	114	81643
code/didHandleExtensionPoints	1660362524269	289	81932
code/didLoadExtensions	1660362524277	8	81940
code/willConnectSharedProcess	1660362525073	796	82736
code/LifecyclePhase/Restored	1660362525785	712	83448
code/didRemovePartsSplash	1660362525785	0	83448
code/LifecyclePhase/Eventually	1660362530788	5003	88451
code/didRestoreEditors	1660362534381	3593	92044
code/didStartWorkbench	1660362534381	0	92044
```

### cached data created (lazy, might need refreshes)

Uploaded files:

[prof-1l2wsHNY.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9330748/prof-1l2wsHNY.main.cpuprofile.txt)

[prof-1l2wsHNY.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9330747/prof-1l2wsHNY.renderer.cpuprofile.txt)

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by techthoughts2** [comment]
```
Version: 1.71.0-insider (system setup)
Commit: 1a582f7c079d1eb4c89d4f637da2fc2fcb688b31
Date: 2022-08-15T05:17:18.259Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```

Behavior persists in the nightly build as well.

```
The window is not responding
You can reopen or close the window or keep waiting.
```

If I click Keep Waiting it does open in about 48s.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by techthoughts2** [comment]
```
New-Item -Path C:\test\vscodedir -ItemType Directory -Force

        Directory: C:\test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d----         8/15/2022  10:23 AM                   vscodedir

code --disable-extensions --user-data-dir C:\test\vscodedir
```

Fresh directory - same behavior.

Let me know if there is a deeper diagnostic I can run to provide any additional insight.

**Comment by bpasero** [comment]
Is it possible you have some AntiVirus / Defender software running that could block VSCode from starting?

**Comment by techthoughts2** [comment]
Confirmed. Disabling Crowdstrike resolves the issue.

Will work with vendor to determine why Crowdstrike suddenly delays VSCode startup by 40s+ if VSCode is higher than v1.70.1

*Side note: downgrading to VSCode below this version also rectified the issue.*
