### ISSUE TITLE
Running web extension-contributed commands in insiders.vscode.dev fails

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#158019]
1. Go to insiders.vscode.dev/github/microsoft/vscode
2. Run Open Remote Repository
3. :bug: nothing happens, see this error message in console

```
Externalized strings were not present in the environment.: Error: Externalized strings were not present in the environment.
    at s._executeContributedCommand (../../../vs/workbench/api/worker/extensionHostWorker.js:68:64568)
```

Reported by @kieferrm

**Comment by joyceerhl** [comment]
I also see this preceding message in console:

```
Loading vscode-nls-web-data failed. Are you running this outside of VS Code? If so, you may need to intercept the import call with your bundled NLS data.
```

**Comment by TylerLeonhardt** [comment]
fixed in https://github.com/microsoft/vscode-remotehub/pull/524

**Comment by joyceerhl** [comment]
Should be fixed in insiders now with latest Azure Repos pre-release. Needed to go back from 5.1.0 to 5.0.1 of vscode-nls. Thanks @TylerLeonhardt for the quick PR ✨
