### ISSUE TITLE
Code action menu cmd+enter only works for refactorings

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#158031]
1. Using the new code action menu
2. Trigger quick fixes (for example on a spelling issue)
4. Arrow through the list and then try using cmd+enter to preview one of the fixes

**Bug**
The code action is applied without opening the preview

I found that cmd+enter only works if the code action is marked as `refactor.*`

**Comment by justschen** [comment]
Taking a look right now in insiders, but it seems to be fine with spellings + other quickfixes I've tried w/arrowing through. What was the context/which code action was being triggered?

![Recording 2022-08-12 at 11 35 00](https://user-images.githubusercontent.com/54879025/184422257-da4a172b-d9fe-4011-851c-96caf39d17f0.gif)

**Comment by mjbvz** [comment]
Also requires arrowing through the list first. Will update the steps above

**Comment by sean-mcmanus** [comment]
Our C/C++ extension is hitting this -- our code actions are not refactors (i.e. they include other commands that don't even cause edits) so the UI that mentions refactors shouldn't appear (like it doesn't with non-Insiders):
![image](https://user-images.githubusercontent.com/19859882/184446608-c70edf67-c9b8-4e93-9f8c-b932495e5404.png)

**Comment by justschen** [comment]
Our wording for this changed in our latest PR, changing it to `Enter to Apply...` 

In regard to commands that don't even cause edits, I'll double check with Code Actions in general to see if I can make a more refined hover/no hover determination based on the kinds of options that are available in the widget.
