### ISSUE TITLE
The "godoc" command is not available

### ISSUE THREAD

**Issue by iOSwang** [Microsoft/vscode#15805]
- VSCode Version:October 2016 (version 1.7)
- OS Version:Ubuntu kyllin 16.04 LTS
 
Steps to Reproduce:

1. i don`t know ,when i first install VScode，I  go get -u -v the Extension, when i finish it,vscode  tip "The "godoc" command is not available."

**Comment by iOSwang** [comment]
i try install it again ,but it can`t work,other function can work,they tip the message "The "godoc" command is not available."

**Comment by ramya-rao-a** [comment]
@iOSwang Read through https://github.com/Microsoft/vscode-go/issues/446. That should help.
If you still have issues, open one in the [vscode-go](https://github.com/Microsoft/vscode-go/issues) repo
