### ISSUE TITLE
Escape key no longer closes command palette or find/replace

### ISSUE THREAD

**Issue by jmotes** [microsoft/vscode#158056]
Type: <b>Bug</b>

1. Hit Cmd+F to open find. 
2. Hit esc key

1. Hit Cmd+Shift+P to launch the command palette.
2. Hit esc key

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:46.959Z)
OS version: Darwin arm64 21.4.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|--disable-extensions --crash-reporter-id ca7111a9-3049-4bbb-a453-6923a217fca8|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyonecf:30545436

```

</details>

**Comment by jmotes-lapero** [comment]
Update: I noticed that the esc key no longer dismisses the file search (launched via Cmd+P) or command palette (Cmd+Shift+P) either.

**Comment by jmotes** [comment]
Update: I just noticed that the Esc key is not working at all on my computer. I'll close this since it's probably not VS Code related.
