### ISSUE TITLE
"Damaged"/corrupted glyphs in integrated terminal on Lubuntu

### ISSUE THREAD

**Issue by benblank** [microsoft/vscode#158086]
**Does this issue occur when all extensions are disabled?:** Unknown (see below)

**Version:** 1.70.1
**Commit:** 6d9b74a70ca9c7733b29f0456fd8195364076dda
**Date:** 2022-08-10T06:09:15.055Z
**Electron:** 18.3.5
**Chromium:** 100.0.4896.160
**Node.js:** 16.13.2
**V8:** 10.0.139.17-electron.0
**OS:** Linux x64 5.15.0-46-generic (Lubuntu 22.04)

### Steps to Reproduce

1. Launch VS Code
2. Open a terminal
3. Use the editor and terminal for a few hours 😭

### Description

This has been occurring for a little while. After having Code running for some time (usually several hours), some of the font glyphs in the integrated terminal stop displaying correctly. Not the font or terminal as a whole; only specific characters, though *which* characters is not consistent.

For example, in the screenshot below, you can see that the glyph for the number "6" has a chunk missing, as though the entire upper-right portion has been deleted. In the past, among others, I've seen the entire exclamation mark glyph disappear, so that it was rendered as if it were a space.

![screenshot of damaged "6" glyph](https://user-images.githubusercontent.com/275142/184503819-165cd608-7b80-4f3d-8304-867464403fcc.png)

Resizing the terminal doesn't affect the issue, but changing the `terminal.integrated.fontFamily` setting does; even simply changing it and changing back to the original font. The system is not going to sleep, turning its screen off, or similar.

I have not attempted to reproduce the issue without extensions (the issue often takes hours to appear), but to the best of my knowledge, I don't have any extensions installed which should affect the integrated terminal.

The only terminal setting I have changed from default is `terminal.integrated.fontFamily`, which is set to `'Droid Sans Mono for Powerline'` (including single quotes).

I have observed this issue on 1.69.?, 1.70, 1.70.1, and probably earlier as well, but can't say for certain.

I could not get the Issue Reporter to work, but here is the information it would have included:

<details>
<summary>System information</summary>

CPUs | Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 3091)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: disabled_software video_encode: disabled_software vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) | 1, 1, 1
Memory (System) | 7.64GB (0.67GB free)
Process Argv | --unity-launch --crash-reporter-id 4a9a5c2d-da67-4c51-9e57-6326ef577338
Screen Reader | no
VM | 0%

</details>

<details>
<summary>Enabled extensions</summary>

Extension | Author (truncated) | Version
-- | -- | --
linter-actionlint | ara | 0.1.0
vscode-eslint | dba | 2.2.6
gitlens | eam | 12.1.2
EditorConfig | Edi | 0.16.4
vscode-npm-script | eg2 | 0.3.28
prettier-vscode | esb | 9.5.0
linter | fna | 0.0.13
ecdc | mit | 1.8.0
python | ms- | 2022.12.0
vscode-pylance | ms- | 2022.8.20
jupyter | ms- | 2022.7.1102252217
jupyter-keymap | ms- | 1.0.0
remote-containers | ms- | 0.245.0
remote-ssh | ms- | 0.84.0
remote-ssh-edit | ms- | 0.80.0
remote-wsl | ms- | 0.66.3
hexeditor | ms- | 1.9.8
powershell | ms- | 2022.7.2
rewrap | stk | 1.16.3
shellcheck | tim | 0.19.6
jestRunIt | ves | 0.6.0

</details>

<details>
<summary>A/B experiment info</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyonecf:30545436
```

</details>

(Edit: fixed formatting of collapsed sections; apologies for that 😅)

**Comment by meganrogge** [comment]
Does changing the `terminal.integrated.gpuAcceleration` setting help?

**Comment by benblank** [comment]
The capital letter D disappeared from the terminal this morning, so I can confirm that changing `terminal.integrated.gpuAcceleration` from "auto" to "off" does bring the broken/missing glyphs back, at least in the short term. I'll leave it there so that next time I'm using the laptop long enough, I can tell whether the issue is still present with that setting.

**Comment by benblank** [comment]
Apologies! I though I responded to this on Sunday.

After using my laptop all weekend, I didn't encounter any issues with the terminal display with `terminal.integrated.gpuAcceleration` set to "off", so that seems to work around the problem.

**Comment by Tyriar** [comment]
This should be fixed now
