### ISSUE TITLE
Sticky Scroll doesn't work with JSON lists

### ISSUE THREAD

**Issue by ostappus** [microsoft/vscode#158018]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1
- OS Version: Windows 10, Debian 11

Steps to Reproduce:

1. `"editor.experimental.stickyScroll.enabled": true`
2. Use the following JSON:

```
{
    "container": {
        "another-container": {
            "list": [
                {
                    "leaf": "value",
                    "deep-container": {
                        "deep-list": [
                            {
                                "deep-leaf": "deep-value"
                            }
                        ]
                    }
                }
            ]
        }
    }
}
```
Result:
`container` and `another-container` are visible in the sticky, but starting from the top-level `list`, there are no new lines added.

![image](https://user-images.githubusercontent.com/3604544/184390772-c92b4579-928f-4013-aabf-13673f99c224.png)

**Comment by gjsjohnmurray** [comment]
Please install [Insiders](https://code.visualstudio.com/insiders) and try your use-case there. Insiders happily coexists with the regular version (aka Stable). It usually gets updated every weekday, and it's where you'll get to see improvements to sticky scroll as they land.

**Comment by ostappus** [comment]
Thanks, it seems to be working okay in 1.71.0-insider.
