### ISSUE TITLE
Problems panel vs problems status

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#158062]
Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/26315643/184469420-4d564a9f-5cc0-42cf-adfd-36a9cf913ae1.png)

I have one file open. The problems side panel reports 22 info-level errors from the cSpell extension. But the problems status bar also reports 4 warnings. Why this inconsistency?

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx   (8 x 2296)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (5.34GB free)|
|Process Argv|--crash-reporter-id f4d11365-b8df-4076-a7d2-5647e124f85c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
Bookmarks|ale|13.3.1
rtf|ale|2.5.1
icons-carbon|ant|0.2.5
vscode-open-file-folder|auc|0.0.4
insert-unicode|bru|0.13.3
markdown-toc|Cha|1.5.6
reverse-search|Dan|2.0.2
vscode-markdownlint|Dav|0.47.0
vscode-dotnet-adapter|der|1.4.3
xml|Dot|2.5.1
vsc-material-theme-icons|equ|2.3.1
prettier-vscode|esb|9.5.0
font-switcher|eva|4.1.0
macros|ged|1.2.1
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
docomment|k--|0.1.31
markdown-link-updater|mat|2.2.0
markdown-shortcuts|mdi|0.12.0
render-crlf|med|1.6.0
fluent-icons|mig|0.0.18
ecdc|mit|1.8.0
HTMLHint|mka|0.10.0
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
powershell|ms-|2022.7.2
test-adapter-converter|ms-|0.1.6
fix-json|oli|0.1.2
material-icon-theme|PKi|4.19.0
material-product-icons|PKi|1.4.0
word-counter|plu|0.0.1
toggle|reb|0.0.2
vscode-sort-json|ric|1.20.0
block-travel|sas|0.0.2
MDTools|sea|1.0.1
vscode-table-formatter|shu|1.2.1
vscode-fileutils|sle|3.5.0
vscode-autohotkey|sle|0.2.2
character-count|ste|0.1.1
code-spell-checker|str|2.5.4
code-spell-checker-french|str|0.2.2
code-spell-checker-german|str|2.0.4
code-spell-checker-greek|str|0.1.13
code-spell-checker-italian|str|0.1.13
code-spell-checker-spanish|str|2.1.2
html-preview-vscode|tht|0.2.5
duplicate-finder|tle|0.0.6
vscode-w3cvalidation|Umo|2.9.1
vscode-icons|vsc|11.15.0
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30545435

```

</details>

**Comment by billyeatcookies** [comment]
I think this is an extension specific issue, the extension you are using `code-spell-checker`, isn't built in. So I think this issue may be made there.

**Comment by gmccullo** [comment]
I don't think so. Note that both the panel and the status report 22 info problems. Those are the spelling errors. But only the status bar reports 4 warnings. I have no idea what those are. Even with no files open I see warnings in the status bar and none in the panel.

**Comment by gjsjohnmurray** [comment]
Does anything happen if you click on the filter button at the right-hand end of the filter field of the Problems view?

**Comment by gmccullo** [comment]
I have everything enabled. And I hit "Clear filters" nothing changes.

**Comment by yume-chan** [comment]
![image](https://user-images.githubusercontent.com/1330321/184508347-c678b47e-9401-4a08-96c8-b3d15250ea61.png)

Not sure what "Clear filters" you are mentioning, but this button indicates a filter is enabled.

**Comment by gmccullo** [comment]
Clear filters: you only see it when the active filters are hiding some reports:

![image](https://user-images.githubusercontent.com/26315643/184523744-99e5629b-7d58-4d90-93e9-0be7e962faa2.png)

The reason the filter is enabled is because I have "Show active file only" checked:

![image](https://user-images.githubusercontent.com/26315643/184523762-aec6c749-c989-48ff-b2a8-f5946c5c6d6c.png)

However, turning that off, which is what "Clear filters" does, will not change the issue. 

And now that I'm playing around with this more I think the issue is that problems are not updating reliably. For example, I opened editors on about 30 files. In the panel only 5 of them are showing up with 12 warnings and 373 infos. Matches the status bar counts. 

Now if I activate one of the 25 _other_ files, that file suddenly appears in the problem panel too, and the problems in that file are added to the totals in both panel and status bar. 

Now if close all editors, I still see _3_ files listed in problems and the counts in the panel and status bar match. 

So, from having 30 files open to having 0 files open:

- If it was only counting active files (which I disabled for this experiment) nothing should have changed. (In fact, with no filters, shouldn't it show all files in the _project_?) 
- If it was only showing recently edited files (e.g. in the current session), shouldn't the problems panel and status bar remain unchanged? 
- If the active file filter _was_ enabled and no files are open shouldn't there be no files in panel and zero counts in panel and status bar?

**Comment by gjsjohnmurray** [comment]
Problems are contributed by extensions, and extensions are responsible for removing their contributed problems when they should no longer be there.

Please run the Start Extension Bisect command, then follow its notification instructions, at each step repeating your tests. This procedure might identify an extension that is malfunctioning with regard to how it handles Diagnostics (which is what the API calls the entities).

**Comment by alex-pezzati** [comment]
> Start Extension Bisect command

I was having a similar issue and I was able to identify the offending extension with the process you recommended. Thank you!

**Comment by sandy081** [comment]
Clearing the filters shall show all problems including warnings. Is it possible to provide a sample repro using which I can reproduce this?

**Comment by sandy081** [comment]
Closing this issue as there is not enough information provided. Please reopen it with requested info. Thanks.
