### ISSUE TITLE
Test: new option to insert final new line

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15807]
- [x] anyOS - @mjbvz 
- [x] anyOS - @jrieken 

Refs: https://github.com/Microsoft/vscode/issues/1666

Complexity: 1

There is a new setting `files.insertFinalNewline` that can be enabled to adding a final empty new line at the end of files.

Verify this feature works as expected.

**Comment by mjbvz** [comment]
Opened #16557

**Comment by mjbvz** [comment]
Besides the unexpected cursor behavior noted in #16557, everything else seems to check out

**Comment by ronak1009** [comment]
"files.insertFinalNewline" = true
@bpasero I added this parameter to the user settings and workspace settings, but it is still not working onVSC 1.12.1 version. Do I need to add some more configuration done? I am not using any plugin for this. If I add plugin, then it go into infinite loop as I reported in my previous comment

**Comment by bpasero** [comment]
@ronak1009 `"files.insertFinalNewline": true` works.
