### ISSUE TITLE
Cursor is  not working

### ISSUE THREAD

**Issue by sabariask** [microsoft/vscode#158096]
Type: <b>Bug</b>

When I type a code in editor, it will suddenly come down to next line without click enter button. I tried after restart, after some time it will do again same.
please help to solve this problem.

Thank you.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
