### ISSUE TITLE
Create file and nested directories at once

### ISSUE THREAD

**Issue by ddramone** [Microsoft/vscode#15802]
It would be great, if you could create number of nested directories specifying their names separated with slashes in the dialog that opens while creating new file.

For example if you create file entering following string into dialog: `/app/some/module/api.ts`
It should create folder structure like this:
```
app/
  some/
    module/
      api.ts
```

If `some` folder  already exists, it should just create subfolder `module` into it and put `api.ts` file into it.

**Comment by kaiwood** [comment]
As usual, there is an extension that does this :)

[File Utils](https://marketplace.visualstudio.com/items?itemName=sleistner.vscode-fileutils) has a 2 commands for creating files, if you specify directories in front of the name it creates them recursively for you (and skips the existing ones as well)

**Comment by ddramone** [comment]
I always prefer native functionalities for this kind of features.
Never thought installing external plugin for creating files in any IDE, But thank you for that reference.

If this "improvement" (not actually issue) isn't relevant, someone will close it.

**Comment by wallverb** [comment]
Related: https://github.com/Microsoft/vscode/issues/12893

**Comment by ddramone** [comment]
Thank you @wallverb . I was looking for similar issues, but missed that one probably.
