### ISSUE TITLE
Option to Hide Errors in the Overview Ruler

### ISSUE THREAD

**Issue by jagdishrajan** [microsoft/vscode#158089]
Add a feature to hide errors in the Overview Ruler much like editor.hideCursorInOverviewRuler hides the cursor in the Overview Ruler.
This setting could be editor.hideErrorsInOverviewRuler

**Comment by alexdima** [comment]
You can use transparent colors for them which results in them being hidden:
```
"workbench.colorCustomizations": {
	"editorOverviewRuler.warningForeground": "#00000000",
	"editorOverviewRuler.errorForeground": "#00000000",
}
```
