### ISSUE TITLE
leftovers at terminal after deleting commands like this

### ISSUE THREAD

**Issue by devhiko** [microsoft/vscode#158010]
Type: <b>Performance Issue</b>

when i enter a command at terminal and it finished or after deleting command, there are leftovers at there like dead pixels
and also when i tried setting gpu acceleration to OFF it cleared and error gone, there may be a solution or any ?

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by devhiko** [comment]
yes, i figured out that with a way, it stems from gpu acc settings in terminal, edited that and worked properly. Here is ss of this.
![a](https://user-images.githubusercontent.com/99843102/184556275-26713ec6-5adc-48e8-9ddb-5d2d24972179.png)
And i am congratulating you for developing an app like this.

**Comment by devhiko** [comment]
occur again

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by devhiko** [comment]
No, it seems working but anytime at a time occurs again so magical, i changed it auto, canvas, off -> current auto but no help.  Windows için Posta ile gönderildi Kimden: Megan RoggeGönderilme: 15 Ağustos 2022 Pazartesi 17:43Kime: microsoft/vscodeBilgi: Hikmet; State changeKonu: Re: [microsoft/vscode] leftovers at terminal after deleting commands like this (Issue #158010) does changing terminal.integrated.gpuAcceleration help?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>

**Comment by meganrogge** [comment]
we need to be able to reproduce this to look into it further

**Comment by devhiko** [comment]
when i open an empty terminal at any project or dir, after writing something and ran them, the thing occurs. i cannot capture it for now, not for everytime it occurs sometimes. but steps to reproduce
-> open a terminal with **gpuacc:on** setting write sth and run it, or clear terminal and for further solution how can i reproduce it and any info required ?
