### ISSUE TITLE
Rename function searches through documentation

### ISSUE THREAD

**Issue by CaedenPH** [microsoft/vscode#158083]
I'm not sure if this should be built into visual studio code, or an extension, or even in Github CoPilot. When renaming a variable, visual studio code parses all instances in which this variable is called. The parser searches in the local scope and global scope. However, I am wondering if there is a way to parse documentation, ie docstrings/comments to rename the function within this documentation.

For example:
```py
def add(a: int, b: int):
    """Adds two integers.

    :param a: The first first operand.
    :param b: The second operand. 
    :return: The sum of the operands 
    """
    return a+b
```
If I were to rename `a` to `operand_one`, the parses would only change the literal code to `operand_one`, missing the documentation. I am wondering if this feature is possible, there would be multiple challenges.

These challenges would include: 
- The differences in documentation, not all languages have global standards in which documentation is unified.
- Whether or not this documentation is for the current scope, for example in python class documentation is not held within the `__init__` but in the class itself.

**Comment by yume-chan** [comment]
The language extension needs to support that. For example, the C# extension does this:

![Recording 2022-08-14 at 03 26 58](https://user-images.githubusercontent.com/1330321/184508029-18615807-8de9-42f6-b1ba-f4e2c146b9e9.gif)

**Comment by CaedenPH** [comment]
> The language extension needs to support that. For example, the C# extension does this:
> 
> ![Recording 2022-08-14 at 03 26 58](https://user-images.githubusercontent.com/1330321/184508029-18615807-8de9-42f6-b1ba-f4e2c146b9e9.gif) [ ![Recording 2022-08-14 at 03 26 58](https://user-images.githubusercontent.com/1330321/184508029-18615807-8de9-42f6-b1ba-f4e2c146b9e9.gif) ](https://user-images.githubusercontent.com/1330321/184508029-18615807-8de9-42f6-b1ba-f4e2c146b9e9.gif) [ ](https://user-images.githubusercontent.com/1330321/184508029-18615807-8de9-42f6-b1ba-f4e2c146b9e9.gif)

Okay, perhaps I should make issues on these specific extensions?
