### ISSUE TITLE
Discord Rich Presence not working on VS Code (After update, not extension or Discord issue)

### ISSUE THREAD

**Issue by ThatError404** [microsoft/vscode#158047]
Type: <b>Bug</b>

Discord Rich Presence (Not the extension) not working on VS Code

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.56GB free)|
|Process Argv|--folder-uri file:///d%3A/3D%20Objects/Downloads/DPL --crash-reporter-id 1167b65f-4874-483f-b0f6-bc3175483e9e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-rbxlua|Ama|0.5.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-rojo|eva|1.13.4
copilot|Git|1.40.6471
copilot-labs|Git|0.2.221
krnl-execute|kai|0.0.2
vscord|Leo|4.5.0
regionfolder|map|1.0.18
python|ms-|2022.13.12241007
vscode-pylance|ms-|2022.8.20
robloxlsp|Nig|1.5.12
batch-runner|Nil|0.0.6
lua-indent|rin|0.0.1
LiveServer|rit|5.7.5
bash-debug|rog|0.3.9
markdown-preview-enhanced|shd|0.6.3
luahelper|yin|0.2.19

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyone:30545435

```

</details>

**Comment by gjsjohnmurray** [comment]
have you already reported it to the extension authors? If they think VS Code has broken something at 1.70 they will need to raise an issue here with technical details.

**Comment by ThatError404** [comment]
Ok
