### ISSUE TITLE
Use recommended storage locations for app and user data

### ISSUE THREAD

**Issue by danielniccoli** [microsoft/vscode#158071]
Type: <b>Bug</b>

On Windows, VSCode is putting application data directly in the user profile at `$env:userprofile\.vscode`. This violates Microsoft recommendations for Windows operating systems and should be moved to the recommended locations.

![grafik](https://user-images.githubusercontent.com/2971735/184478723-41f08335-6863-4190-9500-089a54e61f77.png)

The application and user data should be moved to storage locations recommended by Microsoft. A selection of recommended storage locations are

- ApplicationData (roaming)
- LocalApplicationData (non-roaming e.g., Local/LocalLow)
- CommonApplicationData (non-roaming)
- CommonProgramFiles (non-roaming)

Source and details about recommended storage locations:  
https://docs.microsoft.com/en-us/dotnet/api/system.environment.specialfolder?view=net-6.0

---

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (6.29GB free)|
|Process Argv|--crash-reporter-id 0042d240-2478-49b5-84e1-386a67589bc7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-markdownlint|Dav|0.47.0
xml|Dot|2.5.1
gitlens|eam|12.1.2
vscode-diff|fab|1.4.2
vscode-firefox-debug|fir|2.9.8
vscode-pull-request-github|Git|0.48.1
git-graph|mhu|1.30.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
remote-wsl|ms-|0.66.3
hexeditor|ms-|1.9.8
vscode-typescript-next|ms-|4.9.20220812
vscode-yaml|red|1.9.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyonecf:30545436

```

</details>

**Comment by gjsjohnmurray** [comment]
See also #3884

**Comment by danielniccoli** [comment]
Duplicate of #3884
