### ISSUE TITLE
[Feature Request] Debugger - add restart option to request:"launch"

### ISSUE THREAD

**Issue by matusszabo** [Microsoft/vscode#15804]
- VSCode Version: 1.7.1
- OS Version: OSX

When debugging with request:"attach" there is "restart":true/false option, which is very useful when launching "child_process restarting on file change solution". But still have to start app in console, or vscode command, and kill it manually. It will be very nice to have only one button to start/stop app with debugger. This can be done via request:"launch" and port:{my_custom_child_process_debugger_port}, but when child_process restarts, debugger is detached and need to be re-attached same way like "restart":true option when request:"attach".

Thank you very much

**Comment by weinand** [comment]
This will be available in tomorrows Insiders build.
For more info pls see https://github.com/Microsoft/vscode/issues/17381

**Comment by matusszabo** [comment]
Ooo, lovely, thanks :)
