### ISSUE TITLE
Additions to trusted domains

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#158015]
I used the integrated terminal to setup a machine to be accessible to vscode.dev. When I clicked the link I was asked if I trust the domain.  We should add 
- `https://insiders.vscode.dev/+ms-vscode.remote-server/*` and
- `https://vscode.dev/+ms-vscode.remote-server/*`
to trusted domains.

**Comment by kieferrm** [comment]
And I was unsuccessful adding the entry myself. None of those two worked 
```
  "https://insiders.vscode.dev/%2Bms-vscode.remote-server",
  "https://insiders.vscode.dev/+ms-vscode.remote-server"
```

**Comment by TylerLeonhardt** [comment]
After that PR goes in ^ You should be able to add:
```
"https://insiders.vscode.dev/+ms-vscode.remote-server/*"
```

I will also add to the built-in ones

**Comment by TylerLeonhardt** [comment]
I've added these to the list that ships with vscode.
