### ISSUE TITLE
Terminal won't open due to `EACCESS` error when shell integration is enabled

### ISSUE THREAD

**Issue by austinbutler** [microsoft/vscode#158052]
Does this issue occur when all extensions are disabled?: Yes

# Versions

Version: 1.70.0
Commit: da76f93349a72022ca4670c1b84860304616aaa2
Date: 2022-08-04T04:38:48.541Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.19.0

# Steps to Reproduce

1. Have source `shellIntegration-rc.zsh` file that is read-only
2.  Set `"terminal.integrated.shellIntegration.enabled": true`
3. Open terminal, notice it's stuck at the blank cursor before the shell appears

# Discussion

I think this is possibly the same cause as https://github.com/microsoft/vscode-js-debug/issues/1057. If I set `"terminal.integrated.shellIntegration.enabled": false` the terminal launches normally.

Output from `Log (Window)`:
```
[2022-08-12 14:32:38.758] [renderer1] [error] EACCES: permission denied, copyfile '/nix/store/4h27ykw8vrllfxv0wlrvgl00frfjv6q5-vscode-1.70.0/lib/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh' -> '/tmp/vscode-zsh/.zshrc': Error: EACCES: permission denied, copyfile '/nix/store/4h27ykw8vrllfxv0wlrvgl00frfjv6q5-vscode-1.70.0/lib/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh' -> '/tmp/vscode-zsh/.zshrc'
```

File permissions:
```console
❯ ls -lah /nix/store/4h27ykw8vrllfxv0wlrvgl00frfjv6q5-vscode-1.70.0/lib/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-profile.zsh
-r--r--r-- 1 root root 536 Dec 31  1969 /nix/store/4h27ykw8vrllfxv0wlrvgl00frfjv6q5-vscode-1.70.0/lib/vscode/resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-profile.zsh
❯ ls -lah /tmp/vscode-zsh/.zshrc
-r--r--r-- 1 austin users 3.2K Aug 12 14:22 /tmp/vscode-zsh/.zshrc
```

**Comment by ritvik1512** [comment]
Same issue here with the latest version

**Comment by Co1lin** [comment]
I think it's the same issue as [this](https://github.com/microsoft/vscode/issues/157611#issuecomment-1209528676). The fix is merged but it seems that it isn't released now.

**Comment by austinbutler** [comment]
> I think it's the same issue as [this](https://github.com/microsoft/vscode/issues/157611#issuecomment-1209528676). The fix is merged but it seems that it isn't released now.

The fix there doesn't quite seem sufficient. It's assumed that the copy is working for one of the multiple users, but in my case there's only one user, so if the script ever changes the new script will never be copied.
