### ISSUE TITLE
Test: new option to show full path in window title

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15808]
- [x] Linux (Ubuntu) - @chrisdias 
- [x] OSX - @chrisdias
- [x] anyOS - @seanmcbreen 

Refs: https://github.com/Microsoft/vscode/issues/3119

Complexity: 1

There is a new setting `window.showFullPath` that once enabled will show the full path to the currently opened file instead of the workspace relative path.

Verify this works as expected for:
* folder opened in VS Code
* no folder opened in VS Code

**Comment by myst729** [comment]
Very nice feature! Would love to have it in the coming release.

**Comment by bpasero** [comment]
It will be in our next release 👍

**Comment by chrisdias** [comment]
tested on mac and linux

**Comment by seanmcbreen** [comment]
Done and done :)
