### ISSUE TITLE
code insiders: outline view no longer highlights heading matching current cursor position

### ISSUE THREAD

**Issue by nohallcaesars** [microsoft/vscode#158007]
related to #154645

the current cursor position  in the document, e.g. within `#### this heading` use to be highlighted in the outline view

**Comment by gjsjohnmurray** [comment]
Have you set the `Follow Cursor` option from the `...` menu on the Outline view's header?

**Comment by nohallcaesars** [comment]
I owe you a beer @gjsjohnmurray
