### ISSUE TITLE
terminal file source jump link error

### ISSUE THREAD

**Issue by boltyu** [microsoft/vscode#158066]
![1](https://user-images.githubusercontent.com/10321820/184473966-775c5d43-bb39-4bff-bcd8-04a943fcb9f1.jpg)

'void' should not as column num

Version: 1.70.0-insider (user setup)
Commit: cc098faebd320a2eea3da6ae154b7e2e1347a4b9
Date: 2022-07-26T05:16:55.337Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by gjsjohnmurray** [comment]
Your Insiders is outdated. Please update and retest.

**Comment by boltyu** [comment]
> Your Insiders is outdated. Please update and retest.

Version: 1.71.0-insider (user setup)
Commit: eebdf8174b087979ae6af103f6f2e2f6f9062056
Date: 2022-08-12T05:17:00.323Z
Electron: 19.0.11
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

still have problem

**Comment by boltyu** [comment]
sorry for mistake close

**Comment by Tyriar** [comment]
Tricky edge case, perhaps we should parse the col/row and remove col if invalid and col+row if they're both invalid?
