### ISSUE TITLE
Keyboard shortcut to highlight/select text between single or double quotes

### ISSUE THREAD

**Issue by ziebam** [microsoft/vscode#158069]
Hello and thanks for your work on this awesome editor!

Recently I found myself often copying links from `.json` strings to paste them elsewhere, but found no quick, reliable way to do that. Double-clicking only highlights parts of them, and it seems like there's no keyboard shortcut to select everything between single (`'`) or double (`"`) quotes without using extensions like [Quick and Simple Text Selection](https://marketplace.visualstudio.com/items?itemName=dbankier.vscode-quick-select). I believe such feature would naturally have more use cases, e.g. copying connection strings.

Please let me know what you think! I am willing to help and try to provide a PR should the idea be accepted. Thanks again for your great work. 😄

**Comment by gjsjohnmurray** [comment]
Please try the `editor.action.smartSelect.expand` command (Expand Selection), which by default is bound to <kbd>Shift</kbd>+<kbd>Alt</kbd>+<kbd>RightArrow</kbd>, on Windows at least.

**Comment by ziebam** [comment]
I don't know how I missed that. Thanks a ton @gjsjohnmurray!
