### ISSUE TITLE
Allow to make "backups" of a VS Code instance

### ISSUE THREAD

**Issue by softorangetech1122** [microsoft/vscode#158063]
**What do I mean by "backups"?**
I mean, saving a backup of the `.vscode` directory, which holds a lot of VS Code related files, such as extensions.
**Where do I think this option will be put?**
Similar to workspaces, they will have an option in the "File" menu. Maybe also a command in Control Palette.

**Comment by bpasero** [comment]
This to me sounds like what profiles provide.

**Comment by softorangetech200** [comment]
> This to me sounds like what profiles provide.

"Profiles" are just the different modes. "Backups" provide the almost whole VS Code instance. You can export profiles, but backups of the main instance only.

**Comment by sandy081** [comment]
Please try out our Settings Profiles feature - https://code.visualstudio.com/updates/v1_69#_settings-profiles and see if it suffice what you are looking for.

**Comment by softorangetech200** [comment]
> Please try out our Settings Profiles feature - https://code.visualstudio.com/updates/v1_69#_settings-profiles and see if it suffice what you are looking for.

Settings Profiles has its own import/export menus, but I want this for people who don't use Settings Profiles.

**Comment by sandy081** [comment]
I think not all settings profiles features are enabled in stable. Can you please use latest insiders and try again - https://code.visualstudio.com/insiders/

**Comment by softorangetech200** [comment]
> I think not all settings profiles features are enabled in stable. Can you please use latest insiders and try again - https://code.visualstudio.com/insiders/

Insiders only has a new temporary option (myself hasn't used this in stable). Nothing else.

![image](https://user-images.githubusercontent.com/111031232/188023261-2477e0c1-00e0-4759-ad5d-50c2ea3f7bcc.png)

**Comment by sandy081** [comment]
There are other options too for creating a settings profile (an empty one or from the existing one). May I know if you are expecting more and if so, can you please let me know your use case and requirement?

**Comment by softorangetech1122** [comment]
> There are other options too for creating a settings profile (an empty one or from the existing one). May I know if you are expecting more and if so, can you please let me know your use case and requirement?

I'm expecting this for individuals who are not utilizing Settings Profiles, and those that do. Import/Export is something (importing and exporting in again implies copying), however I need something that you can like, select from an order range highlight. My utilization case is start new briefly (to test something) and afterward return to my unique state (after I'm finished trying).

**Comment by sandy081** [comment]
> My utilization case is start new briefly (to test something) and afterward return to my unique state (after I'm finished trying).

Please try using Temporary Settings Profile - `Settings Profiles: Create a Temporary Settings Profile`. I think this will help for your scenario.

**Comment by softorangetech1122** [comment]
> > My utilization case is start new briefly (to test something) and afterward return to my unique state (after I'm finished trying).
> 
> Please try using Temporary Settings Profile - `Settings Profiles: Create a Temporary Settings Profile`. I think this will help for your scenario.

Yes it does!

*temp profile*
![image](https://user-images.githubusercontent.com/111031232/189236058-40cb9899-c1ad-4742-ac6b-5ba0faf3a8ed.png)

*old profile*
![image](https://user-images.githubusercontent.com/111031232/189236155-9b0053ea-b6a9-46b9-8697-f60371cd417d.png)

**off-topic note: please disregard bitdefender
