### ISSUE TITLE
`StoredFileWorkingCopy` is captured preventing it to be GCed

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#158038]
* Open a new window without open editors
* Open a text editor, close
* Do a heap snapshot
<img width="433" alt="image" src="https://user-images.githubusercontent.com/876920/184431121-4c895537-22f1-4b63-bd73-7cb134748e59.png">

* Open a notebook document, close
* Do another heap snapshot
<img width="684" alt="image" src="https://user-images.githubusercontent.com/876920/184431198-61975d0d-d610-457f-ac99-40fb61e8c87b.png">

There is a long lived `StoredFileWorkingCopy`, which seems to be trapped in https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/workingCopy/common/workingCopyBackupTracker.ts#L239-L254 . The `StoredFileWorkingCopy` holds reference to a `_model`, in above scenario is a `NotebookTextModel`.

**Comment by bpasero** [comment]
@rebornix may I ask how you figured out it would be the code you linked to? If I comment out the relevant contribution that brings `WorkingCopyBackupTracker` to life, I can still reproduce.

https://github.com/microsoft/vscode/blob/1a582f7c079d1eb4c89d4f637da2fc2fcb688b31/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupService.ts#L44-L45

Furthermore, when I use an in-memory backup service by commenting out these lines here:

https://github.com/microsoft/vscode/blob/1a582f7c079d1eb4c89d4f637da2fc2fcb688b31/src/vs/workbench/services/workingCopy/common/workingCopyBackupService.ts#L142-L144

And open and close a notebook, there is still a notebook model leaking:

<img width="965" alt="image" src="https://user-images.githubusercontent.com/900690/184526449-4303cafa-b093-45c3-bf42-2b85fe38f5bb.png">

So I wonder if this is the actual leak somewhere in notebook land and the working copy backup service is a red herring?

**Comment by rebornix** [comment]
@bpasero I commented out the code you linked 

https://github.com/microsoft/vscode/blob/1a582f7c079d1eb4c89d4f637da2fc2fcb688b31/src/vs/workbench/services/workingCopy/electron-sandbox/workingCopyBackupService.ts#L44-L45

and also comment out below code at the same time

https://github.com/microsoft/vscode/blob/1a582f7c079d1eb4c89d4f637da2fc2fcb688b31/src/vs/workbench/services/workingCopy/common/workingCopyBackupService.ts#L142-L144

With both code commented out

* Open a notebook
* Close it
* Heap snapshot
* no `NotebookTextModel`
  <img width="527" alt="image" src="https://user-images.githubusercontent.com/876920/184712616-ed3a24b7-8ab2-4436-874b-f3d1bd8565db.png">
* no `StoredFileWorkingCopy`
  <img width="775" alt="image" src="https://user-images.githubusercontent.com/876920/184712694-c11c13fc-5704-42fb-8acf-ec95bf64675f.png">

However, with both code enabled, `StoredFileWorkingCopy` is not gc'ed which leaks the `NotebookTextModel` object.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/876920/184712760-a2075c62-24f7-4c18-8830-2fff5947f756.png">

---

In both cases, `NotebookTextModel` gets disposed (`dipose()`) so the ref counting is correct. However, I'm not able to get what you showed in with commit  a5755925ca4765bb015b628c58116bedb2b990fa though

![](https://user-images.githubusercontent.com/900690/184526449-4303cafa-b093-45c3-bf42-2b85fe38f5bb.png)

May I ask how did you get to that? Since the leaking is gone with backup commented out, does it mean that there is potential leaking with how is `StoredFileWorkingCopy` is being used?

**Comment by bpasero** [comment]
Is this maybe a red herring? If there was a leak, why are there no 3 stored file working copies when I open and close 3. But I only get 1 appearing. Even on the allocation timeline.

I did manual debugging and confirmed that the working copy is being disposed so I see no real trace of a leak here, but still curious why the heap monitor reports it...

**Comment by bpasero** [comment]
@rebornix I have pushed https://github.com/microsoft/vscode/commit/4df200310d0fd4db0e314f7717863a02fd3728b6 which will:
* set the `_model` in stored file working copy to `undefined` on `dispose` which is somewhat symmetric to what we have been doing in the `TextFileEditorModel` as well so I think that is a good change
* updated `WorkingCopyBackupTracker` to not capture the `WorkingCopy` in the closure by using `IWorkingCopyIdentifier` instead. its a somewhat ugly change, but I am willing to take it

When I run the steps again, I am now presented with what seems like a captured `StoredFileWorkingCopy` somewhere in notebook land:

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/900690/185065302-085974e7-a01a-473c-8d78-0e0c6b5b90a1.png">

It seems less critical now that the model is no longer captured, but maybe if you have energy to continue to investigate if the capturing can be avoided.

I feel this is not really a leak but rather how Chrome decides to GC or not: if the object is captured in a `async` closure, it survives one round of GC but then gets cleaned up in the next round. I do not have sufficient understanding of how GC works in Chrome to dig deeper and it is quite possible that this is still an issue on our end somehow, even though my change seems a bit weird...

**Comment by rebornix** [comment]
> I feel this is not really a leak but rather how Chrome decides to GC or not

@bpasero you are correct. It explains why we are seeing different snapshots: I'm on Windows and I guess you are on macOS. With your latest change, I'm no longer seeing `StoredFileWorkingCopy` instance at all on Windows but seeing the same snapshot as you did on macOS. I'll tackle the rest (since it's only ref'ed by notebook land and only on macOS). Thanks for your help on this!

**Comment by bpasero** [comment]
Oh wow that is super interesting! So weird that the OS behave differently.
