### ISSUE TITLE
Source Control stuck on "Initialize Repository"

### ISSUE THREAD

**Issue by Gtrixz** [microsoft/vscode#158077]
Type: <b>Bug</b>

I have a git repository but in the Source Control tab it tells me the currently opened folder doesn't have a git repository.

This applies to all the repositories I have.

Also when clicking "Initialize Repository" in folders that don't have a git repo, it creates the .git folder but the Source Control panel stays the way it is.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3693)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|15.95GB (10.07GB free)|
|Process Argv|E:\\Coding\\Arc Transpiler --crash-reporter-id 107777c7-a9ca-4bd6-878b-12baa02c6458|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyone:30545435

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you running VS Code elevated (i.e. 'Run as administrator')? If so, were the repositories originally created when running elevated?

Or is the opposite true (repositories created while elevated, VS Code running unelevated)?

**Comment by Gtrixz** [comment]
VS Code was running unelevated and the same for when I created the repositories.
I gave it a try just now and nothing changed

**Comment by gjsjohnmurray** [comment]
OK, so it's not a problem related to elevation. Please continue to launch VS Code normally (ie unelevated). 

Does the Git channel of the Output panel give any clues about what is happening?

**Comment by Gtrixz** [comment]
the output gives me `fatal: unsafe repository` and a git command
I ran the command and now it works again.
Thank you!
