### ISSUE TITLE
change in source control functionality

### ISSUE THREAD

**Issue by darwintnt** [microsoft/vscode#158024]
Type: <b>Bug</b>

Please leave the source control functionality as it was, the new change they made in version 1.70 is a disaster, it is not intuitive, this was one of the features that vscode had that was simple and worked perfect.

VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin arm64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id 921e7a12-8dfc-44bd-8a13-dd88f3392374|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (100)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
laravel-extra-intellisense|ami|0.6.2
ng-template|Ang|14.1.0
swagger-viewer|Arj|3.1.2
vscode-intelephense-client|bme|1.8.2
vscode-tailwindcss|bra|0.8.6
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
regex|chr|0.4.0
vscode-markdownlint|Dav|0.47.0
jshint|dba|0.11.0
vscode-eslint|dba|2.2.6
emoji-snippets|dev|1.5.3
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
phpunit|ema|4.1.1
json-tools|eri|1.0.2
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
docker-explorer|for|0.1.7
docker-extension-pack|for|0.0.1
terminal|for|0.0.10
go|gol|0.35.1
vue-snippets|hol|1.0.4
rest-client|hum|0.25.0
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
Angular2|joh|13.0.0
auto-comment-blocks|kev|1.0.1
vsc-python-indent|Kev|1.17.0
vscode-gutter-preview|kis|0.30.0
json-to-ts|Mar|1.7.5
php-namespace-resolver|Meh|1.1.9
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
document|min|2.1.23
vscode-docker|ms-|1.22.1
mssql|ms-|1.15.0
python|ms-|2022.13.12241007
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.245.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-typescript-next|ms-|4.9.20220811
laravel-goto-components|nao|1.2.0
color-highlight|nau|2.5.0
php-docblocker|nei|2.7.0
vetur|oct|0.36.0
indent-rainbow|ode|8.3.1
mysql-inline-decorator|odu|0.0.5
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
docthis|oou|0.8.2
vscode-versionlens|pfl|1.0.10
vscode-php-getters-setters|php|1.2.3
material-icon-theme|PKi|4.19.0
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
vscode-rapidapi-client|Rap|1.4.1
ruby|reb|0.28.1
java|red|1.9.0
vscode-yaml|red|1.9.1
LiveServer|rit|5.7.5
synthwave-vscode|Rob|0.1.14
laravel-artisan|rya|0.0.28
code-settings-sync|Sha|3.4.3
trailing-spaces|sha|0.4.1
vscode-blade-formatter|shu|0.17.0
sonarlint-vscode|Son|3.8.0
autoimport|ste|1.5.4
code-spell-checker|str|2.5.4
errorlens|use|3.6.0
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0
vscode-icons|vsc|11.15.0
volar|Vue|0.40.1
jinja|who|0.0.8
vscode-ruby|win|0.28.0
fig|wit|0.0.6
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.27.0
php-pack|xde|1.0.3
material-theme|zhu|3.15.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30545435

```

</details>

**Comment by gjsjohnmurray** [comment]
Are you specifically referring to the new merge editor having been enabled by default?

**Comment by tstackhouse** [comment]
I'm inclined to think that's what they meant, I just ran into this today and turned the setting off, changes to default settings like this, especially that change existing installations, should be prominently called out in the release notes.

**Comment by gjsjohnmurray** [comment]
@tstackhouse it got top billing in the previous month's release notes, when it was opt-in. I agree the switch to it becoming the default deserved greater prominence that it received at https://code.visualstudio.com/updates/v1_70#_3 way-merge-editor-improvements

**Comment by stevenbrix** [comment]
how do you revert back? this is painful.

**Comment by stevenbrix** [comment]
ideally the ui should inform the user of the new experience and tell me how to revert back

**Comment by toddwyl** [comment]
> ideally the ui should inform the user of the new experience and tell me how to revert back

![image](https://user-images.githubusercontent.com/20945688/184791246-d4d9d7db-82cb-424d-9d80-cea97711d750.png)

```
git.mergeEditor: false
```
I take a lot of time to disable it ...

**Comment by hediet** [comment]
Closing, as the default changed back.
