### ISSUE TITLE
Changes in line endings are not correctly reflected in the extension host, leading to invalid offsets sent to external refactoring tools

### ISSUE THREAD

**Issue by rotemdan** [Microsoft/vscode#1580]
See https://github.com/Microsoft/vscode-go/issues/165 for how this was discovered and how it effects the go extension, where I initially encountered the problem (reproduction instructions are available in [this comment](https://github.com/Microsoft/vscode-go/issues/165#issuecomment-166618653)).

In short: since the `gorename` tool seems to always convert the document's line endings to `LF`, running it once when the endings are initially `CRLF` may seem to work at first, but at the second time, (when the endings are changed to `LF`) since the extension host still calculates offsets based on `CRLF` the tool would give what seemed like 'strange' errors about invalid offsets that didn't seem to make sense at first. Changing line endings using the UI itself didn't seem to matter, but reopening the file 'magically' fixed it.

Tracing this into the vscode source: in `extHostDocuments.ts`, within the `BaseTextDocument` class it seems like the [`_eol` property](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L185) is not updated when the line endings change. This means that the [`offsetAt` function](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L185) may return invalid values. Fixing this might not be sufficient. In order to force the [`_ensureLineStarts` function](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L329) to recalculate the line offsets it seems that the [`_lineStarts` object](https://github.com/Microsoft/vscode/blob/70ee90dcc1c9a3094ae2ba94f8d0c210a72e499e/src/vs/workbench/api/common/extHostDocuments.ts#L190) needs to be reset every time that the line endings change (this includes cases where they are changed by an external tool or editor). I would recommend this should also handle the case where only a _single_ (or some) line ending changes (meaning the line endings are inconsistent), as in some rare cases some external tools may modify the text in this way.

**Comment by lukehoban** [comment]
The specific problem that I observed with this was that after changing the line endings in VS Code UI, the offsets reported back from `document.offsetAt` appear to be incorrect.  As far as I can tell extensions can't reliably work around this.

**Comment by alexandrudima** [comment]
This is horrible!
Very sorry about it!

**Comment by aeschli** [comment]
I verified that extensions (and the language server) get a document change event with the correct content.
