### ISSUE TITLE
Executing VSCode as superuser will stuck VSCode with a white overlay screen

### ISSUE THREAD

**Issue by kiwimoe** [microsoft/vscode#158067]
### Version
- VS Code Version: 1.70.1
- OS Version: Debian 11

### Steps to Reproduce:

1. Open terminal
2. Issue `code --no-sandbox --user-data-dir /etc`

Trying to opening any kind directory with these parameters, VSCode always show a white overlay screen. 

### Image
Tried with `--disable-extensions` param, still stuck with a white screen
![image](https://user-images.githubusercontent.com/71683721/184474682-06501a4c-4962-4714-8222-7483a2a294ac.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/151187
