### ISSUE TITLE
Some keyboard shortcuts appear odd in menu

### ISSUE THREAD

**Issue by JohnVeness** [microsoft/vscode#158079]
Type: <b>Bug</b>

Some menu items show the corresponding keyboard shortcuts in an odd manner. Specifically, some of the shortcuts are shown in [] brackets and left-aligned, rather than in faded text and right-aligned.

For example:

- File, Open Folder
- Edit, Toggle Line Comment
- View, Output and View, Terminal

![image](https://user-images.githubusercontent.com/2512915/184498816-d9ad065f-15be-4db1-912c-0d44fb18273f.png)

![image](https://user-images.githubusercontent.com/2512915/184498825-f219eadc-45f6-4361-8343-4e4f7c353a53.png)

![image](https://user-images.githubusercontent.com/2512915/184498850-13838a29-9f9c-464a-84ad-a172425e4b42.png)

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:15.055Z)
OS version: Linux x64 5.19.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz (8 x 2176)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|15.52GB (0.42GB free)|
|Process Argv|--unity-launch --crash-reporter-id 8e1a43e7-bb5d-4fd7-9246-f68459569487 --crash-reporter-id 8e1a43e7-bb5d-4fd7-9246-f68459569487 --crash-reporter-id 8e1a43e7-bb5d-4fd7-9246-f68459569487|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|mate|
|XDG_CURRENT_DESKTOP|MATE|
|XDG_SESSION_DESKTOP|mate|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.22.1
remote-containers|ms-|0.245.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0

</details>

**Comment by yume-chan** [comment]
Duplicate of #21722.

The native menu doesn't support displaying chorded keybindings, this is a workaround.

**Comment by JohnVeness** [comment]
Ah, thanks. I did try to search for a duplicate but obviously failed!

**Comment by yume-chan** [comment]
https://github.com/electron/electron/issues/5448

**Comment by JohnVeness** [comment]
Thanks all.
