### ISSUE TITLE
Improve Transition Story From New Merge Editor To Single File With Conflict Markers

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#158006]
Some users prefer the conflict marker decorations, others the new merge editor.

There should be an easier mechanism to switch between both.

**Comment by LucasHillDex** [comment]
Is there a mechanism at all right now to switch back?

**Comment by gjsjohnmurray** [comment]
@LucasHillDex see the `git.mergeEditor` setting.

**Comment by kg-currenxie** [comment]
> @LucasHillDex see the `git.mergeEditor` setting.

Thanks a lot! Thought it was broken 😅

**Comment by jrieken** [comment]
We fixed the setting (sometimes requiring a restart) and there a command to open the file from the 3wm editor.
