### ISSUE TITLE
Support SGR ANSI escape sequences in quick pick labels

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158192]
Would be nice to allow some styling of quick picks, I mainly just want the "dim" style. Blocked on https://github.com/microsoft/vscode/issues/151963

**Comment by TylerLeonhardt** [comment]
My hope is that this goes into `IconLabel` or something and QP gets this for free... but before that work happens it would be good to have this issue to make sure we track it.

**Comment by Tyriar** [comment]
I think some debug/test stuff is using xterm.js for this now, you can close this if you want

**Comment by TylerLeonhardt** [comment]
Yeah I don't think I'll get to it.
