### ISSUE TITLE
Open recent shortcut not working on Ubuntu

### ISSUE THREAD

**Issue by jespertheend** [microsoft/vscode#158195]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.70.1
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:09:15.055Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-46-generic

Steps to Reproduce:

1. Press `Ctrl` + `R`
2. Observe that nothing is happening
3. Change the open recent keybinding to `Meta` + `Ctrl` + `R` and then back to `Ctrl` + `R` to make it a "user" binding.
4. Press `Ctrl` + `R` again
5. Observe that the shortcut is now working

Also note that the command center entry shows no shortcut next to "open recent" unless a user shortcut has been specified.

[Screencast from 15-08-22 21:17:04.webm](https://user-images.githubusercontent.com/2737650/184702602-2e1d7069-cbaf-4d0d-9faa-17077f189a7e.webm)

**Comment by bpasero** [comment]
I cannot reproduce, so I suspect this is a configuration and/or extension problem.

**Comment by jespertheend** [comment]
Seems like I had `ctrl r` + `ctrl t` configured for another command 🤦
Sorry about that!
