### ISSUE TITLE
Test: new setting to remove tab close buttons

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15810]
- [x] anyOS - @joaomoreno 
- [x] anyOS - @sandy081 

Refs: https://github.com/Microsoft/vscode/issues/10739

Complexity: 1

We added a new setting `workbench.editor.showTabCloseButton` that allows to hide the close button on tabs. 

Verify
* when hiding you still see dirty indicators but you cannot close the tab anymore by left click to that area

**Comment by ramya-rao-a** [comment]
Closing as the assigned testers are done testing
