### ISSUE TITLE
Conflict between "editor.quickSuggestionsDelay" and Emmet

### ISSUE THREAD

**Issue by zessx** [Microsoft/vscode#15817]
- VSCode Version: 1.8.0-insiders
- OS Version: windows-x64

**Steps to Reproduce:**

1. Create a new CSS/SCSS/LESS file
2. Type: <kbd>d</kbd><kbd>b</kbd><kbd>Tab</kbd>

**Expected result:**

`display: block;` appears and replaces `db`.  
Same issue with HTML files, and this is big stuff for front-end people.

**Current result:**

The quick suggestion dropdown appears and you need to hide it with <kbd>Esc</kbd> to work with Emmet.

**Possible improvement:**

Set the default value of `editor.quickSuggestionsDelay` to 300 instead of 10.

**Comment by jrieken** [comment]
Yes - they are conflicting but we see a lot more user for IntelliSense/quick suggestion than for emmet. Because of that our recommendation for emmet users is to change the delay or to turn automatic IntelliSense off (`"editor.quickSuggestions": false`)

**Comment by zessx** [comment]
Seems reasonable to preset VSCode for IntelliSense/Quick Suggestion, but as Emmet is enabled by default, it may be useful to specify your recommendations in `editor.quickSuggestionsDelay`'s comment.
