### ISSUE TITLE
'Files: Default Language' wrongly associates ruby with .arb

### ISSUE THREAD

**Issue by ShalokShalom** [microsoft/vscode#158187]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: current
- OS Version: rolling

Steps to Reproduce:

1. Open Settings
2. Look out for Files: Default Language
3. Put ruby in 
4. Open a new file

This should open a .rb file. Instead, it opens an .arb, which is from an unrelated library. 

See also: https://stackoverflow.com/questions/69471158/what-are-the-differences-between-rb-and-arb-files

**Comment by weinand** [comment]
I cannot reproduce this in VS Code 1.70.1: for me newly created files get a ".rb" extension.
Please try to find the extension that does this.

**Comment by ShalokShalom** [comment]
I found the extension and reported it.
