### ISSUE TITLE
Shift+tab from the "replace" textbox doesn't bring to to the "find" textbox

### ISSUE THREAD

**Issue by FremyCompany** [Microsoft/vscode#1581]
Actually, you cannot even reach that textbox using tab from the replace text box in a reasonable way, as I found out.

Repro steps:
- Open a text file
- Hit Ctrl+H
- Hit Tab
- Hit Shift+Tab (once, but also as much as you want)

**Comment by Tyriar** [comment]
Can't repro with <kbd>ctrl</kbd>+<kbd>f</kbd>, I think you mean <kbd>ctrl</kbd>+<kbd>h</kbd> for find and replace.

The tab order seems screwed up:

**Case 1:**

1. <kbd>ctrl</kbd>+<kbd>h</kbd> focus search term
2. <kbd>tab</kbd> focus replace textbox
3. <kbd>shift</kbd>+<kbd>tab</kbd> **focus close dialog button, expected to focus search term**

**Case 2:**

1. <kbd>ctrl</kbd>+<kbd>h</kbd> focus search term
2. <kbd>tab</kbd> focus replace textbox
3. <kbd>tab</kbd> focus match case
3. <kbd>shift</kbd>+<kbd>tab</kbd> **focus search term, expected to focus replace textbox**

**Comment by FremyCompany** [comment]
Good catch. I meant CTRL+H indeed.

**Comment by bpasero** [comment]
+1 for shit tab to move back to input field!

**Comment by FremyCompany** [comment]
:+1:
