### ISSUE TITLE
Avoid ImmortalReference (file models, untitled models)

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15815]
It seems like the workbench fails to dispose models that are requested via the `ITextModelResolverService#resolve`-method. I was always under the assumption this happens after ~5minutes, but with the snippet below I never see a *CLOSE* message. 

Do the following

* open workbench with any editor open
* run the extension command below
* see messages about models being opened/created
* 🐛 never see messages about them disappearing

```
    vscode.workspace.onDidOpenTextDocument(e => console.log('OPEN ' + e.uri.toString()));
    vscode.workspace.onDidCloseTextDocument(e => console.log('CLOSE ' + e.uri.toString()));

    vscode.commands.registerCommand('extension.sayHello', () => {

        vscode.workspace.findFiles('**/*.{json,ts,js}', undefined, 5).then(resources => {

            return Promise.all(resources.map(r => {
                console.log('fetch ' + r.toString())
                vscode.workspace.openTextDocument(r);
            }))
        });
    })
```

**Comment by jrieken** [comment]
Ok, when I open another file I see them being disposed. Is that the rule?

**Comment by bpasero** [comment]
@jrieken correct, here is what I do in textFileEditorModelManager.ts:

```
private onEditorsChanged(): void {
	this.disposeUnusedModels();
}

private onEditorClosed(): void {
	this.disposeUnusedModels();
}
```

Which basically runs over any model with `file://` scheme and dispose those that are not used. There are some rules what it means to have a model in use and one of it is that it is in use if it is showing inside an editor or viewzone.

This is an area of debt that I wanted to revisit when adopting the resolver service reference acquire/release. 

Though I do believe today we do not have a leak, it might just not be instant to dispose a model inside a zone when it closes.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/17073
