### ISSUE TITLE
Vs code

### ISSUE THREAD

**Issue by MarkertMax** [microsoft/vscode#158110]

**Comment by fuka-g** [comment]
Hello and thank you for your contribution to microsoft/vscode !

However, our team of workers have detected that this issue does not conform to the code of conduct and is unhelpful to the development of this product.

To help fight bad contributors and encourage high-quality issues reports, we have decided to communicate your personal information to third parties, including but not limited to, your name, your home address and your visual appearence to allow our contributors to terminate what we believe is an active threat to the integrity of the open source community.

Have a blessed day, don't forget to lock your front door this evening.
