### ISSUE TITLE
Debian repository contains unneeded "linuxconfig"

### ISSUE THREAD

**Issue by vmeurisse** [microsoft/vscode#158106]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: Any
- OS Version: Any

Steps to Reproduce:
1. Install vscode apt repository
2. A package linuxconfig is available on the system (but not installed)

Issue #70611 was closed as vscode doesn't depends on linuxconfig, however it is not a problem of dependencies. The problem is that packages unrelated to vscode are present in the repo.

```
$ apt-cache policy linuxconfig
linuxconfig:
  Installed: (none)
  Candidate: (none)
  Version table:
     1.0 500
        500 https://packages.microsoft.com/repos/vscode stable/main amd64 Packages
```
```
$ curl -s https://packages.microsoft.com/repos/vscode/dists/stable/main/binary-amd64/Packages | grep linuxconfig                                                                                                                                                                                    
Package: linuxconfig
Maintainer: linuxconfig.org
Filename: pool/main/l/linuxconfig/linuxconfig_1.0_amd64.deb
Description: Print linuxconfig.org on the screen
```
The package itself is present at https://packages.microsoft.com/repos/vscode/pool/main/l/linuxconfig/linuxconfig_1.0_amd64.deb

**Comment by rzhao271** [comment]
Removed.

Verification steps:
1. Navigate to https://packages.microsoft.com/repos/vscode/pool/main/l/linuxconfig
2. Confirm you get a 404 error
