### ISSUE TITLE
While Publishing Csharp snippet getting error 

### ISSUE THREAD

**Issue by rahulsahay19** [Microsoft/vscode#15816]
- VSCode Version: 1.7.1
- OS Version: Win 10. 64 Bit (Pro Edition)

Steps to Reproduce:

1. I have attached two files. Package.json and csharp.json.
2.  I am using vsce commands to publish the same.

package.json link:- [package.json](https://gist.github.com/rahulsahay19/216476659e713082ed8a6c85725e9d88)
csharp.json link:- [csharp.json](https://gist.github.com/rahulsahay19/d3e27b3720de1efed27be4d2e725adf3)

I am executing command vsce publish. All pre-requisties with vsce publish, I have already done. 
Error coming:- C:\>vsce publish
glob error { Error: EPERM: operation not permitted, scandir 'C:\Documents and Settings'
    at Error (native)
  errno: -4048,
  code: 'EPERM',
  syscall: 'scandir',
  path: 'C:\\Documents and Settings' }
Error: EPERM: operation not permitted, scandir 'C:\Documents and Settings'

Kindly correct me if I am doing any mistake. This is I am doing for 1st time. Thanks in advance. 

Thanks,
Rahul

**Comment by joaomoreno** [comment]
Moved to Microsoft/vscode-vsce#141
