### ISSUE TITLE
refactoring window empty (light bulb refactor etc)

### ISSUE THREAD

**Issue by solrevdev** [microsoft/vscode#158148]
Type: <b>Bug</b>

This works in Visual Studio Code but not Visual Studio Code Insiders. 

When I click the lightbulb I expect a refactoring or issue fixing selection dropdown to be visible but its not. 

**This is what I see in vscode insiders** 

![vscode-insiders](https://i.imgur.com/7oBzDEU.jpg)

**And this is what I exepect to see (this is vscode)**

![vscode](https://i.imgur.com/1KZgiBC.jpg)

VS Code version: Code - Insiders 1.71.0-insider (Universal) (1a582f7c079d1eb4c89d4f637da2fc2fcb688b31, 2022-08-15T05:18:12.495Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 8, 11|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|--crash-reporter-id 5d0d121e-4fd7-480f-9d89-754f35cbb27e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (125)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.12.0
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
user-secrets|adr|2.0.1
razor-snippets-for-asp-net-core|ale|0.0.3
nugetpackagemanagergui|ali|2.0.4
aws-toolkit-vscode|ama|1.47.0
swagger-viewer|Arj|3.1.2
atlascode|atl|2.10.12
vagrant|bbe|0.5.0
markdown-checkbox|bie|0.3.2
cake-vscode|cak|2.0.0
path-intellisense|chr|2.8.1
gitignore|cod|0.9.0
csharp-interpolated-string-converter|cor|0.1.6
supersharp|cra|0.1.4
doxdocgen|csc|1.4.0
csharpier-vscode|csh|1.3.0
vscode-svgviewer|css|2.0.0
vscode-mysql-client2|cwe|5.7.0
transformer|dak|1.12.1
split-html-attributes|dan|1.0.10
vscode-eslint|dba|2.2.6
vscode-faker|dee|2.0.0
docs-markdown|doc|0.2.113
docs-yaml|doc|0.2.8
netcore-editorconfiggenerator|dog|0.1.1
netcore-extension-pack|dog|1.7.0
netcore-snippets|dog|3.15.2
quicktype-refresh|dog|1.0.2
xml|Dot|2.5.1
gitlens|eam|12.1.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.16.0
vscode-nupkg|eri|1.0.1
prettier-vscode|esb|9.5.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
dotnet-test-explorer|for|0.7.7
shell-format|fox|7.2.2
copilot-nightly|Git|1.40.6483
live-sass|gle|5.5.1
gc-excelviewer|Gra|4.2.55
vscode-drawio|hed|1.6.4
vscode-trello-viewer|Ho-|0.6.0
rest-client|hum|0.25.0
TextTemplating|jac|0.15.0
vscode-edit-csv|jan|0.7.2
better-cpp-syntax|jef|1.15.19
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
svg|joc|1.4.19
roslynator|jos|4.1.1
vscode-commitizen|Kni|1.1.0
wrapSelection|kon|0.10.0
csharpextensions|kre|1.7.1
dotnet|leo|1.3.0
bash-ide-vscode|mad|1.14.0
VS-code-vagrantfile|mar|0.0.7
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.22.1
vscode-language-pack-en-GB|MS-|1.54.1
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.25.0
dotnet-interactive-vscode|ms-|1.0.3405011
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.8.1002261021
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.247.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.11.26
cpptools-extension-pack|ms-|1.2.0
live-server|ms-|0.2.13
mono-debug|ms-|0.16.3
powershell|ms-|2022.7.2
sqltools|mtx|0.23.0
editorconfiggenerator|nep|0.2.1
vetur|oct|0.36.0
vscode-nuget-gallery|pat|0.0.24
explorer-exclude|Pet|1.3.1
vscode-versionlens|pfl|1.0.10
vscode-css-peek|pra|4.2.0
csharp-extensions|rai|0.0.6
ansible|red|0.11.10
vscode-yaml|red|1.9.1
explorer-exclude-vscode-extension|Red|1.2.2
vscode-sort-json|ric|1.20.0
bash-debug|rog|0.3.9
vscode-coverage-gutters|rya|2.10.1
partial-diff|ryu|1.4.3
aspnet-helper|sch|0.6.4
blazorsnippets|Sco|1.5.1
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.5.4
msbuild-project-tools|tin|0.4.6
pdf|tom|1.2.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
vscode-coverlet|urb|1.1.5
vscodeintellicode|Vis|1.2.22
vscode-icons|vsc|11.15.0
gistfs|vsl|0.4.1
volar|Vue|0.40.1
vscode-typescript-vue-plugin|Vue|0.40.1
vscode-wakatime|Wak|19.0.0
quokka-vscode|Wal|1.0.497
vscode-surround|yat|1.5.0
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.3
t4-support|zbe|0.5.0
html-css-class-completion|Zig|1.20.0
vscode-proto3|zxh|0.5.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by justschen** [comment]
Related to https://github.com/microsoft/vscode/issues/158129. PR for this will be out today!
