### ISSUE TITLE
Access to file system from lsp server

### ISSUE THREAD

**Issue by elena-pudovkina** [microsoft/vscode#158189]
Hi,
Not having [vscode.workspace.fs](https://code.visualstudio.com/api/references/vscode-api#:~:text=VARIABLES-,fs%3A%20FileSystem,-isTrusted%3A%20boolean) on the server side of an extension poses quite a challenge. 

One way I see to overcome this is the way [anycode](https://github.com/microsoft/vscode-anycode) does it:
Add a [handler](https://github.com/microsoft/vscode-anycode/blob/main/anycode/client/src/node/main.ts#:~:text=client.onRequest(%27persisted/read,%7D)%3B) to the client for fetching file contents:
``` 
client.onRequest('persisted/read', async (): Promise<string> => {
  if (!persistUri) {
     return '';
  }
  try {
     const data = await vscode.workspace.fs.readFile(persistUri);
     return decoder.decode(data);
  } catch {
     return '';
  }
});
```
And [send a request](https://github.com/microsoft/vscode-anycode/blob/main/anycode/server/src/node/storage.ts#:~:text=const%20raw%20%3D%20await%20this._connection.sendRequest%3Cstring%3E(%27persisted/read%27)%3B) from the server whenever you need to read files:
```
const raw = await this._connection.sendRequest<string>('persisted/read');
```

But I noticed that anycode only does this in the node runtime. Does it mean that this won’t work in the browser?
Is there a more direct way to allow the server access to the file system or will there be one in the future?

I’m asking because I’m working on migrating the [Wake lsp extension](https://marketplace.visualstudio.com/items?itemName=sifive.wake) to the browser. Its server is compiled from C++ to wasm and it requires access to the file system, so I'm struggling to make the transition.

**Comment by dbaeumer** [comment]
Dups https://github.com/microsoft/vscode-languageserver-node/pull/782.
