### ISSUE TITLE
Light bulb menu appears as thin horizontal bar

### ISSUE THREAD

**Issue by mctDeveloperCode** [microsoft/vscode#158101]
Type: <b>Bug</b>

When I click the light bulb instead of getting a menu I see a thin, dark gray, horizontal bar. I have tried restarting the application.

VS Code version: Code - Insiders 1.71.0-insider (eebdf8174b087979ae6af103f6f2e2f6f9062056, 2022-08-12T05:17:00.323Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (24.15GB free)|
|Process Argv|--crash-reporter-id bdd00023-f5b6-46fc-92a9-5e8ad83beebb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
vscode-markdownlint|Dav|0.47.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
prettier-vscode|esb|9.5.0
dotnet-test-explorer|for|0.7.7
vscode-guid|hea|1.4.20
vscode-azurefunctions|ms-|1.7.4
vscode-azureresourcegroups|ms-|0.5.5
csharp|ms-|1.25.0
python|ms-|2022.12.0
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.7.1102252217
remote-wsl|ms-|0.66.3
azure-account|ms-|0.11.1
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.5
powershell|ms-|2022.7.2
test-adapter-converter|ms-|0.1.6
rust|rus|0.7.8
code-spell-checker|str|2.5.4
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
vscaac:30438845
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by mctDeveloperCode** [comment]
![image](https://user-images.githubusercontent.com/1445251/184524010-c0508993-aa2e-4dc3-b7ec-9b3da8804a1a.png)

Here is an image of what I am seeing.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by justschen** [comment]
Related to: https://github.com/microsoft/vscode/issues/158129. This is most likely because of an extension which uses non-VS Code specific code actions. PR for this is out rn!

**Comment by mctDeveloperCode** [comment]
Confirming fixed on:
Version: 1.71.0-insider (user setup)
Commit: f5c96e2db885f43fe1adb4a6ebbdfecf095430a8
Date: 2022-08-18T05:15:52.904Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22622
Sandboxed: Yes

Thank you!
