### ISSUE TITLE
can't open terminal in ssh remote

### ISSUE THREAD

**Issue by kmivan** [microsoft/vscode#158146]
Type: <b>Bug</b>

can't open terminal in ssh remote in stable version. But this doesn't happen with insiders version

VS Code version: Code - Insiders 1.71.0-insider (Universal) (1a582f7c079d1eb4c89d4f637da2fc2fcb688b31, 2022-08-15T05:18:12.495Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 3.10.0-1160.66.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--crash-reporter-id cd5664dd-461b-4b61-a400-ae72d5f54cba|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: hemu|
|OS|Linux x64 3.10.0-1160.66.1.el7.x86_64|
|CPUs|Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz (96 x 999)|
|Memory (System)|503.24GB (495.10GB free)|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.247.0
remote-ssh|ms-|0.85.2022071315
remote-ssh-edit|ms-|0.80.0
cmake-tools|ms-|1.12.22
cpptools|ms-|1.12.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal
