### ISSUE TITLE
Latex not rendered correctly

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#158133]
Should be a single line not multiple
![Screen Shot 2020-05-27 at 15 45 08](https://user-images.githubusercontent.com/1948812/83079654-27375200-a031-11ea-9905-3c60c1ea1765.png)

Here's what it should look like (single line latex output)
![Screen Shot 2020-05-27 at 16 07 10](https://user-images.githubusercontent.com/1948812/83080852-294ee000-a034-11ea-9ad9-027bdac38169.png)

# This needs to be done in the renderer extension repo
Update nteract and related libraries

**Comment by mjbvz** [comment]
Here's the current rendering of:

```md
a b ($c$ = 1) x y z
```

<img width="192" alt="Screen Shot 2022-09-22 at 8 19 58 PM" src="https://user-images.githubusercontent.com/12821956/191886213-1d217a55-29b6-4c0a-a52a-1808b60a8daa.png">

If something still doesn't look right, please share the markdown and I'll take a look (I think it's expected that we center the math blocks here while they are right aligned in some other editors)
