### ISSUE TITLE
Settings Profiles commands should not show in Command Palette of Stable edition

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#158149]
Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/6726799/184614208-f5a34dd5-ea1e-4152-8612-2e5049b95c3c.png)

I can provide a PR.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:

**Comment by sandy081** [comment]
This is intended as this feature was enabled in stable before Settings Profiles are introduced as first class resources.
