### ISSUE TITLE
Shortcut to open file from Source Control tab

### ISSUE THREAD

**Issue by paragkatoch** [microsoft/vscode#158138]
Currently when I click on a file in `Source Control` tab it shows the changes made to that file. 

But to open a file listed in `Source Control` tab, I have to either open it from `Explorer` or by right clicking on the file and selecting `open file`

<img width="405" alt="image" src="https://user-images.githubusercontent.com/61873006/184573592-99251e68-92c0-4970-a6f2-c7680717bd1c.png">

It would be nice if I can just `cmd/ctrl` click on the file in the `Source Control` tab and it opens the file instead of showing the changes made to that file.

**Comment by gjsjohnmurray** [comment]
Did you try clicking on the first button on the file's row? For me the hover tip is "Open File" and it does exactly that.
