### ISSUE TITLE
VSCode extension: refactor options not shown in custom code action menu

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#158129]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Describe the bug
- The refactor options like "Wrap with...", "Remove this widget", etc. do not show up in the new code action menu.

To Reproduce
- Steps to reproduce the behavior:

1. Enable editor.experimental.useCustomCodeActionMenu
2. Open the refactor menu somewhere

Expected behavior
- The refactor options should appear in the new menu.

From https://github.com/Dart-Code/Dart-Code/issues/4104#issue-1338214770

**Comment by LuquinhasSG** [comment]
For me too, I'll have to migrate to normal vscode...
![image](https://user-images.githubusercontent.com/55420795/184641324-b4056220-0080-446d-8be8-eabc7a8a3e07.png)

**Comment by DanTup** [comment]
@justschen Thanks! :)
