### ISSUE TITLE
The extension version cannot be fixed in "devcontainer.json"

### ISSUE THREAD

**Issue by avraam-inside** [microsoft/vscode#158143]
Read the instructions in the extensions section and specify the extension version with "v":
![image](https://user-images.githubusercontent.com/52919010/184599790-48899b6a-9cb9-4942-9493-fbb0f3951ca0.png)

Specify the extension version without "v":
![image](https://user-images.githubusercontent.com/52919010/184600051-4948433b-357b-4fd3-80ab-f77573463395.png)

Both options do not work, after reassembling the container, vscode continues to persistently install the latest version of the extension, and not the requested one.

Please fix it.

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode/issues/63903.
