### ISSUE TITLE
Test: hide the activity bar

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15812]
- [x ] Windows -  @ramya-rao-a
- [x] macOS -  @isidorn 
- [x] Linux -  @Tyriar 

Complexity: 1

A new setting `workbench.activityBar.visible` allows to control the visibility of the activity bar. 

Verify:
* this setting works as expected
* you can toggle visibility from the View menu
* you can toggle visibility from the command palette

**Comment by ramya-rao-a** [comment]
Testing #1105
