### ISSUE TITLE
Strange right-click menu on files in Explorer after closing them

### ISSUE THREAD

**Issue by studyingegret** [microsoft/vscode#158114]
Type: <b>Bug</b>

Steps to reproduce:
1. Open a new folder with VS Code (with at least one file in it).
2. Click to open the file in the Explorer.
3. Close the opened tab.
4. Right click on the file again in the Explorer.

Expected behavior: A "normal" menu appears, such as:

![Expected context menu](https://user-images.githubusercontent.com/110317665/184532969-62ac87ab-35d4-4f8c-8841-1af26cd0af73.png)

Actual behavior: The menu below appears.

![Actual context menu seen](https://user-images.githubusercontent.com/110317665/184532906-5eac799c-57df-4dbd-b68a-b728bd6c6ee3.png)

In addition, clicking on the "Download" option would actually pop out a dialog to download the file, even though the file is local.

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19042
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.78GB free)|
|Process Argv|C:\\Users\\Gareth\\Desktop\\test --crash-reporter-id 0ca47609-b826-438d-be24-b5589e9edec2|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by studyingegret** [comment]
I am able to reproduce the issue with all extensions disabled (using "Reload With Extensions Disabled").

**Comment by lramos15** [comment]
I cannot reproduce, but @bpasero my guess is that the web or remote context key are reporting incorrectly here.

**Comment by bpasero** [comment]
I cannot reproduce so I suspect this is maybe a setup or configuration issue.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by studyingegret** [comment]
I cannot reproduce with the latest Insider build...

VS Code version: Code - Insiders 1.71.0-insider (1a582f7c079d1eb4c89d4f637da2fc2fcb688b31, 2022-08-15T05:17:18.259Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.82GB free)|
|Process Argv|--crash-reporter-id adc3af8c-0978-48bc-aa94-fbd604e9e143|
|Screen Reader|no|
|VM|0%|
</details>

Extensions: none

<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonvspyt551:30291412
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>
