### ISSUE TITLE
Can open an ipynb notebook integration test failure

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#158278]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=181930&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9bc48eac-eb66-52c8-7250-d6490c5f3a15&l=297

**Comment by roblourens** [comment]
Unfortunately it seems not really actionable since the tests crashed or timed out partway through, so we don't have the error result from the test.
