### ISSUE TITLE
Settings Profile: Include remote settings

### ISSUE THREAD

**Issue by DatGuyJonathan** [microsoft/vscode#158292]
There's an extension called SonarLint with a `sonarlint.ls.javaHome` setting that is machine scoped: https://github.com/SonarSource/sonarlint-vscode/blob/master/package.json#L265. When I install this extension in SSH remote, the setting is classified as "Remote".

![Screen Shot 2022-08-16 at 10 33 00 AM](https://user-images.githubusercontent.com/7286437/184932034-deaeeb8f-fc10-457c-98b9-d0d5de000f0b.png)

This setting is ignored if I specify in a `.code-workspace` file. I tried exporting a settings profile and the remote setting isn't included. Is it possible to include remote settings in the profile?

**Comment by sandy081** [comment]
Thanks for using profiles feature and giving feedback. This feature is still in preview mode and we do not have plans to work on this specific request. After launching profiles feature, we would collect more feedback and see if this request is wanted y more users and will address this. Until then, I would like to close this feature as out of scope. Thanks.
