### ISSUE TITLE
Add progress bar to multiselect in search

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#158293]
> When I'm waiting for 1000s of items to be replaced, there is no feedback that anything is happening. We should show the viewlet progress bar, like when you click "Replace All"

from https://github.com/microsoft/vscode/pull/156963#issuecomment-1215608144

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue. PRs are welcome so you can create a PR that fixes this if you are passionate about getting this feature across the finish line. Thanks!
