### ISSUE TITLE
Add Breakpoint Conditions

### ISSUE THREAD

**Issue by westy92** [Microsoft/vscode#1582]
It would be nice to be able to specify a condition for a breakpoint to be hit.

Similar to https://msdn.microsoft.com/en-us/library/5557y8b4.aspx#Anchor_8 and http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Freference%2Fbreakpoints%2Fref-condition_option.htm

**Comment by bpasero** [comment]
@isidorn fyi

**Comment by isidorn** [comment]
This is in progress
