### ISSUE TITLE
scroll Terminal/console

### ISSUE THREAD

**Issue by 1C0D** [microsoft/vscode#158215]
Type: <b>Performance Issue</b>

Le scroll dans la zone où se trouve le Terminal est trop  sensible

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.19044
Modes:

**Comment by 1C0D** [comment]
The scroll in the terminal panel is too sensitive

**Comment by meganrogge** [comment]
setting this should help 

`terminal.integrated.mouseWheelScrollSensitivity`
