### ISSUE TITLE
Renaming file closes open editors when Kaspersky endpoint security is running

### ISSUE THREAD

**Issue by LEMinhViet** [Microsoft/vscode#15822]
- VSCode Version: 1.7.1
- OS Version: Windows 7

Steps to Reproduce:

1. Open a folder `Test` in VSCode 
2. Open some files in `Test` for editing
3. Rename file `Test\test.ts`
4. Problem : VSCode closes all open editors

Expected:
Files should stay open
Thanks

**Comment by bpasero** [comment]
@LEMinhViet do you rename inside VSCode or outside in the windows explorer?

**Comment by LEMinhViet** [comment]
@bpasero it happens in both cases (inside and outside VSCode)

**Comment by bpasero** [comment]
@LEMinhViet are the files dirty when you rename the folder?

**Comment by LEMinhViet** [comment]
@bpasero dirty files are still open, only saved files closed

**Comment by bpasero** [comment]
@LEMinhViet are you on a network share? can you share a video how this looks like?

**Comment by LEMinhViet** [comment]
@bpasero https://youtu.be/NZFNFYO-fwY
I'm on just a normal folder

**Comment by bpasero** [comment]
@LEMinhViet can you run with "`code --verbose`" from the command line and attach the output from the developer console when you do this? I cannot reproduce it on my Windows machine when I tried. Here is how it looks like for me, maybe I am doing something different?

![untitled](https://cloud.githubusercontent.com/assets/900690/21139132/b7605972-c131-11e6-85d8-1ef227b733ef.gif)

**Comment by LEMinhViet** [comment]
![vscode](https://cloud.githubusercontent.com/assets/6697001/21144961/d622eeea-c14c-11e6-8924-98914e46c3d9.gif)
@bpasero 
Don't know if it helps but i have Kaspersky endpoint security 10 on my machine. I tried VSCode on an other pc without Kaspersky and it works perfectly.

**Comment by bpasero** [comment]
@LEMinhViet very good point, yes it might cause timing issues (e.g. anti virus holding on to the file for longer and that makes our logic harder to update).

**Comment by bpasero** [comment]
This should work ok now if you set `workbench.editor.closeOnFileDelete: false`
