### ISSUE TITLE
Cursor is put after a double quoted string 

### ISSUE THREAD

**Issue by danfma** [Microsoft/vscode#15825]
- VSCode Version: Code - Insiders 1.8.0-insider (4ac353bfb3c3598338dad6ce8e162c67650cf2cc, 2016-11-21T07:05:04.218Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|aurelia|AureliaEffect|0.1.10|
|EditorConfig|EditorConfig|0.3.4|
|Ionide-FAKE|Ionide|1.2.1|
|Ionide-Paket|Ionide|1.4.0|
|Ionide-fsharp|Ionide|2.10.1|
|swift|Kasik96|0.0.2|
|material-icon-theme|PKief|1.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|indenticator|SirTori|0.2.1|
|wallaby-vscode|WallabyJs|1.0.30|
|elm-format|abadi199|0.1.0|
|toml|be5invis|0.0.3|
|vscode-icontheme-nomo-dark|be5invis|1.2.0|
|gitignore|codezombiech|0.4.0|
|githistory|donjayamanne|0.1.0|
|gitlens|eamodio|1.0.2|
|tslint|eg2|0.6.0|
|auto-rename-tag|formulahendry|0.0.8|
|Kotlin|mathiasfrohlich|1.2.0|
|easy-less|mrcrowl|1.2.5|
|csharp|ms-vscode|1.5.2|
|mono-debug|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|2.2.2|
|tsimporter|pmneo|1.2.11|
|seti-icons|qinjia|0.1.3|
|sass-indented|robinbentley|1.2.1|
|RustyCode|saviorisdead|0.19.1|
|elm|sbrink|0.8.3|
|gitflow|vector-of-bool|0.1.0|

---

Steps to Reproduce:

1. In a TypeScript file or C# file, try to open a double quoted string `"`;
2. Then try to write something;

Desired behavior:

When you open a double quoted string, the editor will auto close it and put the cursor between the quotes, so when you write anything, you will write the content of the string itself.

The problem:

After some updates of the vscode, when opening a double quoted string, the cursor will be put after the last quote `"" |here|`, then when you try to press some keys, you will write outside the string;

**Comment by ramya-rao-a** [comment]
@danfma Does this happen when the extensions are disabled as well? Try running VS Code from terminal `code --disable-extensions .`

**Comment by danfma** [comment]
Ok, I will check.

**Comment by danfma** [comment]
Ok, you can close it because I can't reproduce anymore, but maybe is some extension, like you said! ;)
Thank you!

**Comment by danfma** [comment]
I removed all my plugins and the problem is there, but apparently it is happening only on my mac. I put a video to show the issue bellow. I just opened the double quotes and then I pressed space after it.

http://www.screencast.com/t/kCZQGZW5

**Comment by danfma** [comment]
Apparently, it's a problem with any key that is triggered with a modifier key, for example: "", latéx, coração etc

**Comment by alexandrudima** [comment]
@danfma Can you please let me know exactly:
* your configured keyboard layout
* the exact keys you press

**Comment by danfma** [comment]
I just tried to write the following sequence just typing one character after other:

```
Coração
"Isto
'hello

public class Teste
{
    constructor() {
      console.log("Hello);
    }
}
```

Look at the behavior here: http://www.screencast.com/t/yi0HsGQIlOQ

* At first, I thought that was a problem with the auto-close for quotes, but it doesn't;
* If I write coração, by typing (c)-(o)-(r)-(a)-(acude)-(c)-(shift)-(`)-(a)-(o), it will complete as before:
  * By the way:
    * (acute)-(c) => ç;
    * (shift)-(`)-(a) => ã;
* If I open a quote, it will close the pair, but put the cursor after the quotes;

PS: I only have this problem on my macOS Sierra 10.12.1 and I tried to disable all my extensions too and the behavior is the same.
