### ISSUE TITLE
apt-install of vscode: gpg: no valid OpenPGP data found

### ISSUE THREAD

**Issue by Ekmansoft** [microsoft/vscode#158263]
I'm running

wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg

but get this response

"gpg: no valid OpenPGP data found."

What does it mean?

**Comment by Tyriar** [comment]
Looks like it might be related to security policies of your environment? https://linuxhint.com/solve-gpg-no-valid-openpgp-data-found-error/

**Comment by Ekmansoft** [comment]
Yes I could do it but wget didn't work for me.

I had to download the file using Chrome then install it to apt

Den tis 16 aug. 2022 15:41Daniel Imms ***@***.***> skrev:

**Comment by Ekmansoft** [comment]
It's probably due to our proxy
