### ISSUE TITLE
what`s wrong with the git add operation?

### ISSUE THREAD

**Issue by 635613589** [microsoft/vscode#158258]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.1
- OS Version: Darwin x64 20.3.0

Steps to Reproduce:

1.

https://user-images.githubusercontent.com/63730157/184861822-23e6f797-2b2f-43c2-a091-ed2a1d1bc5eb.mp4

2.

**Comment by 635613589** [comment]
git add operation doesn`t work well ！

**Comment by 635613589** [comment]
this is torturing me , I cant not add my changes smoothly !

**Comment by lszomoru** [comment]
@635613589, the button in question is supposed to stage the changes but in you recording I can't really tell what is happening in the "Source Control" view. Would it be possible to create a recording in which the "Source Control" view on the left hand side is visible as well? Thank you!

**Comment by 635613589** [comment]
ok thanks，I will try to reproduce and record it~
and I found this usually happens when my computer is in high CPU occupancy, but not everytime, weird

**Comment by lszomoru** [comment]
@635613589, since I did not hear from you for some time I will go ahead and close this issue as part of our housekeeping iteration.
Please feel free to reopen the issue in case you are still able to reproduce the problem. Thank you very much!
