### ISSUE TITLE
Explore what it takes to ship VS Code as a UWP application 

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#15820]
Goals:
* what does it take to convert VS Code to UWP
* what are issues we see when running Code from the store

/cc @kieferrm @egamma @seanmcbreen @chrisdias

**Comment by bpasero** [comment]
Needs a proper done criteria. Also no longer seems to be on the January plan.

**Comment by be5invis** [comment]
Do something for your company, you are Microsoft, right?
Just like Nintendo should release its latest Mario on Switch.

**Comment by felixrieseberg** [comment]
@bpasero Yo, check out `electron-windows-store` - even if you don't end up using it, I'd love to hear why it wouldn't work for y'all!

https://github.com/felixrieseberg/electron-windows-store

**Comment by sean-clayton** [comment]
@felixrieseberg I was _just_ going to refer them to that project after I read your blog post. 😛

**Comment by bpasero** [comment]
Investigation is done. Closing (and duplicates https://github.com/Microsoft/vscode/issues/10759)

**Comment by gulshan** [comment]
Any decision or observations based on the investigation?

**Comment by bpasero** [comment]
For those interested in the results of the investigation…  We used the [desktop app converter](https://developer.microsoft.com/en-us/windows/bridges/desktop) to convert VS Code to a UWP app that uses the Desktop Bridge (aka a “Centennial” application) that provides a Windows Store setup experience and access to a subset of the full UWP API. The conversion worked quite well and we were able to side load VS Code as a Windows Store application with no loss of functionality.
 
So, this closes the investigation for the product itself. The next investigation we would need to do is understand how to adapt our internal build systems to produce daily/monthly builds that can be published through the Store. Once that is understood, we will decide if and when it makes sense to move forward with this effort and actually put it on the backlog.

**Comment by OrbintSoft** [comment]
Awesome! 👍 😄 😺 ❤️ 
The UWP App, works even on Windows 10 Mobile and continuum?

**Comment by chrisdias** [comment]
@OrbintSoft no, it is still a win32 application that runs node and spawns non-UWP processes.  The desktop conversion does not mean it automatically runs on mobile/continuum.

**Comment by rogersachan** [comment]
@bpasero Will we be able to follow this investigation/see more updates on this in the future?

Best Regards,

Roger Sachan

**Comment by rwiedower** [comment]
Any updates here? Would love to be able to ensure VS Code gets into the store...
