### ISSUE TITLE
SCM decorations are single pixel wide and sometimes not visible at all

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158276]
Not sure if this was intentional but it's very small now:

![image](https://user-images.githubusercontent.com/2193314/184897188-0e146322-6674-4c67-a786-4a948583f729.png)

They are invisible when zooming out once:

![image](https://user-images.githubusercontent.com/2193314/184897372-6ca6e20c-d45d-4b11-af54-fcc91f0a0732.png)

Version: 1.71.0-insider (user setup)
Commit: 8e42bda5487a953d59fab7792eedd4ca209cabba
Date: 2022-08-16T05:18:32.502Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

---

I preferred the old style:

![image](https://user-images.githubusercontent.com/2193314/184897599-42c9981e-64ff-4003-a81e-9fe6590e0f57.png)

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by Tyriar** [comment]
The mouse target is also 1 pixel wide now

**Comment by Tyriar** [comment]
Deleted lines are much harder to see and use now

![image](https://user-images.githubusercontent.com/2193314/185468202-b1d1e4bd-a8a2-40bd-a2d4-2e30fab118a7.png)

**Comment by misolori** [comment]
do you have any repro steps? I can't seem to see that, assume it was unintentional:

![CleanShot 2022-08-18 at 11 42 55](https://user-images.githubusercontent.com/35271042/185470451-492c5ffa-d3bc-4ff9-994e-a3391d516001.png)

![CleanShot 2022-08-18 at 11 43 31](https://user-images.githubusercontent.com/35271042/185470471-6f766f1c-eca2-48c9-89bf-a0403942ee8d.png)

**Comment by Tyriar** [comment]
This is in a PR so likely related to the comments changes

**Comment by Tyriar** [comment]
Still an issue after https://github.com/microsoft/vscode/issues/158299 and https://github.com/microsoft/vscode/issues/158521 fixes:

![Recording 2022-08-22 at 07 58 06](https://user-images.githubusercontent.com/2193314/185953104-1c4013c8-ab10-4e84-a075-d1dcc502ad62.gif)

**Comment by alexr00** [comment]
This does seem likely to be related to the comments changes. I'm looking into it.

**Comment by Tyriar** [comment]
I have `"editor.folding": false` set, it works fine when I enable folding again
