### ISSUE TITLE
Terminal `ViewColumn` handling is wrong

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#158274]
I noticed terminals can accept `ViewColumn`:

https://github.com/microsoft/vscode/blob/3e9aab1f555a58b1db1b40ddbdfe3d267cdb771b/src/vscode-dts/vscode.d.ts#L6543

Note that this does not map 1 to 1 to `EditorGroup`, you have to:
* offset properly: [code](https://github.com/microsoft/vscode/blob/3e9aab1f555a58b1db1b40ddbdfe3d267cdb771b/src/vs/workbench/api/common/extHostTypeConverters.ts#L275-L285)
* convert properly: [code](https://github.com/microsoft/vscode/blob/3e9aab1f555a58b1db1b40ddbdfe3d267cdb771b/src/vs/workbench/services/editor/common/editorGroupColumn.ts#L18)

//cc @jrieken

**Comment by bpasero** [comment]
**Steps:**
* open 2 empty editor groups, focus the first group
* execute a command that triggers below code [1]
* 🐛 terminal opens in first group not second

```ts
vscode.window.createTerminal({
	location: {
		viewColumn: vscode.ViewColumn.Two
	}
});
```

**Comment by bpasero** [comment]
//cc @sandy081 @joshaber

**Comment by Tyriar** [comment]
It's not handled properly here:

https://github.com/microsoft/vscode/blob/4987750f9205398226481dc4bda276e603d7d0cb/src/vs/workbench/contrib/terminal/browser/terminalService.ts#L1103-L1110
