### ISSUE TITLE
Share RequestType between client and server

### ISSUE THREAD

**Issue by xferra** [Microsoft/vscode#15829]
I hope that sharing common request types between Language client and Language server should be simpler. Imagine we have a very simple request type:

```
interface MyRequestParams {
    message: string;
}

interface MyRequestResult {
    data: string[];
}

namespace MyRequest {
    export const type: RequestType<MyRequestParams, MyRequestResult, void> = { get method() { return 'extension/name'; } };
}
```

To make it work we need to import `vscode-languageserver` in the server and import `vscode-languageclient` in the client. So, it's not possible to share .ts file with `MyRequest, MyRequestParams, MyRequestResult` between client and server (which of course will be preferred because nobody wants to update 2 files when changing a `MyRequestResult` for example).

**Comment by dbaeumer** [comment]
This is possible with TS 2.0 since it allows to specify multiple rootPath values. You can add the interface to a common folder which is used in both client and server. Alternatively you can move them to a separate npm package. But that might be overkill :-)
