### ISSUE TITLE
Feature: Git: option for open editor windows to change with branch

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#15824]
- VSCode Version: 1.7.1
- OS Version: OS X, 10.11.6

I wish that I could tie the open editor windows to my git branch.  Usually, each branch corresponds with a different task, and each task requires a different set of open files.

I would imagine that in such a feature, when switching to a branch not previously handled by vscode, the state would be seeded by the current set of open editors.  Further, I would imagine that upon deleting a branch, that vscode's window state for that branch would be deleted.

If someone wants to work on a plugin to implement this, I'm happy to contribute, but I don't have the bandwidth or the vscode expertise to lead such an effort at this time.

**Comment by KnisterPeter** [comment]
Shouldn't that be possible with an extension? An extensions could get the open files for the current branch and when a branch is switched the open files are persisted and if there are already persisted files for the new branch that could be opened. Am I wrong?

**Comment by josh-tepper** [comment]
I believe so, but I'm not sure.  In addition to your description, it would have also to update the windows on startup as the git branch could be changed from the previous invokation of vscode.  And, of course, the extension would need to be able to get some sort of event when the git branch is changed (or poll for such a change).

I'm not enough of a vscode expert to say if it should or should be implemented as an extension.  I'll leave that to other people here to decide.  In any event, happy to contribute to any effort to build such an extension.

**Comment by josh-tepper** [comment]
Can anyone provide some guidance on this?  Is anyone interested in working on an extension?  Again, happy to contribute :-)

**Comment by joaomoreno** [comment]
This is now fixed.
