### ISSUE TITLE
Allow floating debugger controls to be draggable to the title bar

### ISSUE THREAD

**Issue by usamazansari** [microsoft/vscode#158256]
Can we please have the floating debugger panel to be able to move to the empty space in the title bar?

Cause: The floating debugger panel sometimes obstructs the window elements while debugging any flow which traverses through multiple files.

Why this suggestion?: There is an ample amount of space available in the title bar between the window title and the layout customization panel. The space in between can be used faithfully to place the floating debugger panel.

Another suggestion: Is it possible for the command center to be transformed to debugger panel while in debug mode?

**Comment by weinand** [comment]
Did you try the Debug Toolbar Location settings?

![2022-08-16_15-27-14](https://user-images.githubusercontent.com/1898161/184891232-ef901c7e-91e8-4165-bcc8-9340f1e0b527.png)

**Comment by roblourens** [comment]
With the command center, I don't actually think we should be adding new controls to the window title, there will often not be enough room. And I don't think we should remove the command center when debugging.

**Comment by usamazansari** [comment]
> Did you try the other Debug Toolbar Location settings?
> 
> ![2022-08-16_15-27-14](https://user-images.githubusercontent.com/1898161/184891232-ef901c7e-91e8-4165-bcc8-9340f1e0b527.png)

This has helped me out. Thanks a ton @weinand!

@roblourens The command center takes up significant space indeed, but for wider screens, there is a lot of empty space which can be used.

![image](https://user-images.githubusercontent.com/98811057/185039492-dfd002d9-7f4a-4a13-8643-435f68c00216.png)

I agree to not replace the command center with debug tools, but I was wondering if the command center could be modified to hold the buttons for debugging... Apologies, I cannot visualize this 😅
