### ISSUE TITLE
New comment overlay is distracting

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158299]
I often develop while I have a draft PR, the way these new buttons show up is a lot of distracting noise, especially when selecting multiple lines. I use draft PRs like this so I can view the entire diff on github.com as well, perform CI runs and get the (approximate atm https://github.com/microsoft/vscode-pull-request-github/issues/392) changed line range.

![Recording 2022-08-16 at 09 51 54](https://user-images.githubusercontent.com/2193314/184935228-dafbcc7c-1cc2-4b15-a5a6-914060eea65e.gif)

Also it looks unpolished how the icon backgrounds are transparent and the line underneath bleeds through.

One possible solution for this is to not show these hover/selection gutter decorations when the current user is the author of the PR.

**Comment by alexr00** [comment]
@Tyriar have you tried the "Comments: Toggle Editor Commenting" command?

**Comment by alexr00** [comment]
I often leave comments on my own PR (ex. to give extra context to the reviewer) so hiding the gutter for the author wouldn't work well for me.

**Comment by alexr00** [comment]
The transparent icon looks bad, but I don't see that on the Dark+ theme. What theme are you using?

**Comment by Tyriar** [comment]
The animation seems to have them slide in from the left which doesn't look right either:

![Recording 2022-08-17 at 06 59 03](https://user-images.githubusercontent.com/2193314/185153185-00fafec3-5e05-4ea5-989f-babbac56f141.gif)

This is my theme Sapphire https://marketplace.visualstudio.com/items?itemName=Tyriar.theme-sapphire

**Comment by Tyriar** [comment]
> have you tried the "Comments: Toggle Editor Commenting" command?

This hides that section of the gutter but I like the line to show me what areas of code have been modified by the PR, it's just the + icon popping up on the cursor line and selection is distracting. Personally I rarely leave comments on my own PR like that (and use .com when I do). I tried searching for a setting first, this seems similar to `editor.folding` so an `editor.comments` setting would make sense?

It's also very noisy with a selection:

![image](https://user-images.githubusercontent.com/2193314/185153818-1ff6a816-c22a-4e66-86cb-5d3b448ae453.png)

I like GH's approach to multi-line comments:

![Recording 2022-08-17 at 07 03 09](https://user-images.githubusercontent.com/2193314/185154141-883ffa3c-0c33-49b7-9b0f-b5c8921524af.gif)

**Comment by alexr00** [comment]
@daviddossett or @misolori I'd love to get your feedback on the multiline behavior. I originally had it like GitHub's, but I though it looked a bit funning so I changed it to show a + on ever line. 

@Tyriar your "+" buttons also don't look very square (they're supposed to be square). Do you have any zoom settings set?

**Comment by misolori** [comment]
I agree that the multi-line `+` can feel like too much, we could try to add a new color or at least try a different treatment for multi-selection:

<img width="472" alt="CleanShot 2022-08-17 at 07 28 39@2x" src="https://user-images.githubusercontent.com/35271042/185160385-75a34516-e093-4f1e-ba2b-1c14c026fb26.png">

<img width="590" alt="CleanShot 2022-08-17 at 07 29 48@2x" src="https://user-images.githubusercontent.com/35271042/185160735-00ab27af-9598-4bac-bc5b-ce374fa2abc0.png">

I'd also maybe only show the `+` on line hover instead of every line

**Comment by Tyriar** [comment]
An alternative as color draws the eye as well and we don't use it for single line comments:

![image](https://user-images.githubusercontent.com/2193314/185165239-e16a230e-93a7-46be-b42a-649f8f5ee562.png)

I'd be happy with the above and then only showing the + when the mouse hovers, not the cursor line changing. For selection I'd also prefer the comment buttons to only show when the mouse hovers the lines containing the selection.

Editing code with this big button jumping around isn't the best experience:

![Recording 2022-08-17 at 07 40 30](https://user-images.githubusercontent.com/2193314/185166510-5720eedd-61c1-4be1-85e6-3e76211dae9c.gif)

**Comment by Tyriar** [comment]
Another:

![image](https://user-images.githubusercontent.com/2193314/185168561-c7df535c-1e4f-4228-a34e-a0dad268e03a.png)

**Comment by misolori** [comment]
Not a big fan of the thicker line. What if we simply selected the text at the same time to keep it simple?

<img width="531" alt="CleanShot 2022-08-17 at 08 06 19@2x" src="https://user-images.githubusercontent.com/35271042/185174930-4010c53f-8976-4139-9017-8c33ce1f04a5.png">

> Editing code with this big button jumping around isn't the best experience:

Would a setting help alleviate this scenario? I'd imagine that editing in a PR is less common as reviewing PRs?

**Comment by Tyriar** [comment]
@misolori it's always better if we can avoid a setting. I think the most natural thing is to de-emphasis _new_ comments on your own PR. If we need a setting with `"auto" | "on" | "off"` (where auto only shows the button when the gutter is hovered when you're the author?) then I'd be happy. I believe you're more likely to edit code than comment on your own code if it's your branch/PR. Again I don't want the commenting to go away, I just don't want it to be so distracting while writing code.

**Comment by Tyriar** [comment]
> Not a big fan of the thicker line. What if we simply selected the text at the same time to keep it simple?

Oh I think I was misunderstanding before, my suggestion was to show the comment range button when text is selected, so the circles represent selection start line and selection end line:

![image](https://user-images.githubusercontent.com/2193314/185192930-028f0aa0-be25-469d-9c78-de1a3f1aaea8.png)

I think your suggestion was when dragging which I do like, where circle is where mousedown happened. The blue is less of a concern here as well then as it's had some direct interaction:

![image](https://user-images.githubusercontent.com/2193314/185192783-6e4716bb-39d2-4ced-a887-718a7d4fe8d6.png)

**Comment by alexr00** [comment]
I actually really like the dotted line from one of the earlier proposals, though without the blue color as I worry that it will also be too distracting:

![image](https://user-images.githubusercontent.com/38270282/185436866-e5b42571-8c4f-4c98-92d1-b908487feb98.png)

**Comment by Tyriar** [comment]
@alexr00 thanks for the fixes, I made a reminder to verify next week

**Comment by alexr00** [comment]
👍There's 1 transparency issue left that I know of: the commenting range bar shows under the comment thread button. All the range math is getting a bit complicated, so I would prefer to tackle any further improvements during debt week.

**Comment by Tyriar** [comment]
FYI patterns like this are hard to get right since they need to be repeated at the height of a cell which differs depending on various settings and the environment:

![image](https://user-images.githubusercontent.com/2193314/185948066-a2cb0d35-d597-4b05-a05b-56b88537673c.png)

One idea to make it a consistent pattern is to fill the top half of the cell. Regardless I think the circle at the other end to signify the start would look good.
