### ISSUE TITLE
VS Code Terminal Alt + Click didn't work in Linux Mint Cinnamon 

### ISSUE THREAD

**Issue by thanhtutzaw** [microsoft/vscode#158332]
- VS Code Version:VS Code (Linux Version)
- OS Version:Linux Mint 21

I can use Follow Link button but cannot use Alt + Click shortcut .
![follow link vs code](https://user-images.githubusercontent.com/71011043/185024532-70eab410-1cd6-492a-a1db-273b81936a61.png)

**Comment by meganrogge** [comment]
did this recently start happening for you or has it always occurred?

**Comment by thanhtutzaw** [comment]
> did this recently start happening for you or has it always occurred?

Only happened in Linux Mint . I use alt + ctrl + click to work this in linux vs code. But some features still don't work like alt + shift + down arrow ( copy line ) and go to function by clicking function name  and  etc ...
