### ISSUE TITLE
How to access web inspector to work on VSCode themes?

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15831]
- VSCode Version: Version 1.8.0-insider
- OS Version: 10.12.1

There used to be a way to access the web inspector to inspect VSCode itself.   It seems to be gone now.

As a theme author, how do I inspect the scope of items on the screen in order for me to color the scopes in my tmTheme file? Is there a new method?

**Comment by mjbvz** [comment]
You still should be able to go to the `Help -> Toggle Developer Tools` menu item to inspect the vscode dom. Is that menu item missing for you?
