### ISSUE TITLE
html despite working, it does not seem to be recognized as an html file, but as a file with no extension assigned

### ISSUE THREAD

**Issue by MarceloKade** [microsoft/vscode#158339]
I don't know when this happened, but when I tried using emmet in the html, I realized it didn't work, but when I changed it to htm, it worked, like vscode changed html to htm, but htm doesn't work in my Angular application
![image](https://user-images.githubusercontent.com/98852912/185060190-70328601-bd08-430b-a396-0be1eabc87cf.png)

**Comment by joeljosedev** [comment]
Can you check your Emmett configuration? It should work with HTML files with the default configuration.

As for the icon, you seem to be using an icon theme that doesn't have an icon for HTML files. Press `F1` and type `Preferences: File Icon Theme` to use a different theme for file icons.

**Comment by MarceloKade** [comment]
> Can you check your Emmett configuration? It should work with HTML files with the default configuration.
> 
> As for the icon, you seem to be using an icon theme that doesn't have an icon for HTML files. Press `F1` and type `Preferences: File Icon Theme` to select a different theme for file icons.

emmet doesn't recognize html, vscode itself is not recognizing either, but when I switch to htm, emmet works, but htm file doesn't work in Angular framework. I pressed F1 but I couldn't find anything that changed the way emmet works from htm to html

**Comment by MarceloKade** [comment]
How do I set vscode to html back to default?

**Comment by joeljosedev** [comment]
You can reset Emmett by deleting the Emmett options in `settings.json`. You can edit this file by opening the Command Palette and typing `Preferences: Open User Settings (JSON)`.

Try commenting out Emmett options one at a time to see what's causing the problem.

**Comment by MarceloKade** [comment]
> You can reset Emmett by deleting the Emmett options in `settings.json`. You can edit this file by opening the Command Palette and typing `Preferences: Open User Settings (JSON)`.
> 
> Try commenting out Emmett options one at a time to see what's causing the problem.

![image](https://user-images.githubusercontent.com/98852912/185208967-b0c285eb-8bac-44ea-9dea-05f4f207a398.png)
![image](https://user-images.githubusercontent.com/98852912/185209006-a72d3faa-49ae-4cae-90f7-c12f54ec6e0f.png)
![image](https://user-images.githubusercontent.com/98852912/185209368-e97a06ea-1837-40e3-832a-054e28815bcb.png)
![image](https://user-images.githubusercontent.com/98852912/185209458-25e13489-3b72-42f3-a62c-1cf68d1a157d.png)
![image](https://user-images.githubusercontent.com/98852912/185209589-ef2ab440-ea91-478c-a8ea-15fac74747c4.png)
![image](https://user-images.githubusercontent.com/98852912/185209646-d9590769-4315-4a08-9a8c-d1db67678738.png)

html não está funcionando, quando mudo para htm funciona, mas htm não funciona no framework Angular.
html não está sendo reconhecido no vscode e emmet

**Comment by MarceloKade** [comment]
i uninstalled and installed again but the problem is not resolved

**Comment by MarceloKade** [comment]
after uninstalling vscode completely I was able to solve the problem.
Installing the extensions again in my vscode, I noticed that the pyscript extension caused interference in the html file
