### ISSUE TITLE
Git uri handler clone should preserve branch

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#158386]
1. Invoke vscode-insiders://git.clone?https://github.com/microsoft/vscode/tree/release/1.70
2. Select a directory to clone your repo into
3. Open cloned repo
4. :bug: branch context is not preserved

This impacts Continue Working On--branch context is preserved for Clone in Container and Create New Codespace.
 
I propose adding a new optional query parameter to the uri handler here:
https://github.com/microsoft/vscode/blob/6cc52565f2ca557a3b0919aee29ac259be02c02f/extensions/git/src/protocolHandler.ts#L26-L33

and passing that to the `git.clone` command as an optional argument here
https://github.com/microsoft/vscode/blob/6cc52565f2ca557a3b0919aee29ac259be02c02f/extensions/git/src/protocolHandler.ts#L59

Then after cloning here:
https://github.com/microsoft/vscode/blob/6cc52565f2ca557a3b0919aee29ac259be02c02f/extensions/git/src/commands.ts#L517-L521
and before opening the repo in a new window, we would perform the ref checkout:
```ts
if (ref) {
    const repository = this.model.getRepository(Uri.file(repositoryPath));
    await repository?.checkout(ref);
}
```

**Comment by lszomoru** [comment]
@joyceerhl, will you create a test plan item/verification steps for this feature?

**Comment by joyceerhl** [comment]
@lszomoru yes I will!
