### ISSUE TITLE
I disabled 'Markdown Language Features' in Running Extensions window, How can I get it back

### ISSUE THREAD

**Issue by haanamomo** [microsoft/vscode#158335]
Type: <b>Bug</b>

1. Open Running Extensions
2. Click Markdown Language Features and Disable
3. Can't find it anywhere

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 20.6.0
Modes:

Extensions: none

**Comment by gjsjohnmurray** [comment]
Does it show when you use the "Built-in" option from the filter button of the Extensions view?

**Comment by haanamomo** [comment]
Thanks , it showed up, I found it.
