### ISSUE TITLE
Persistent tasks were not updated correctly - no terminals for reconnection

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#158385]
Did a reload of insiders after having the default build task run (Cmd+Shift+B):

![image](https://user-images.githubusercontent.com/900690/185190272-d7ee84aa-e199-4c12-bbc7-f2440ee274ad.png)

**Comment by meganrogge** [comment]
had you deleted the terminals before reloading or done anything else of interest? cannot reproduce

**Comment by meganrogge** [comment]
I can reproduce after reloading the window twice

**Comment by meganrogge** [comment]
Cannot reproduce in OSS 😭 only insider's

**Comment by meganrogge** [comment]
Debugged in dev tools and this happens when the terminal service reconnection state changes after `reconnect` is called in the tasks service

**Comment by meganrogge** [comment]
so seems like I should cache the requests for task reconnection until terminal service is connected. not sure why this only happens on 2nd and beyond reload of the window and only in insider's - not OSS
