### ISSUE TITLE
"files to exclude filter"  disable button does not disable properly

### ISSUE THREAD

**Issue by stan-ac** [microsoft/vscode#158345]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

filter info:
google/,tf_micro/,ssd_pipe/  

if the button is disabled this is still hidden:
C:\...\worktree_debug\library\cv\google\tensorflow\lite\micro\kernels\arc_mli\conv.cc
  79,5: #if FORCE_MLI_NOT_APPLICABLE

if the filter is completely removed it appears

VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.6.1
doxdocgen|csc|1.4.0
arm|dan|1.7.4
flatbuffers|gab|0.1.0
todo-tree|Gru|0.0.215
vscode-peacock|joh|4.1.0
python|ms-|2022.13.12281011
vscode-pylance|ms-|2022.8.20
jupyter|ms-|2022.7.1102252217
remote-containers|ms-|0.245.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.5
cpptools-extension-pack|ms-|1.2.0
vs-keybindings|ms-|0.2.1
text-power-tools|qcz|1.35.0
gnu-mapfiles|tro|1.1.0
cmake|twx|0.0.17
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30545435

```

</details>

**Comment by gjsjohnmurray** [comment]
I assume you mean this button:

![image](https://user-images.githubusercontent.com/6726799/185083608-a02eb071-c605-4ec2-be04-cd925fd69725.png)

I think you are misunderstanding its function. It does not affect whether or not the contents of the adjacent "files to exclude" field affect the search. It only affects whether or not certain exclude / ignore settings made elsewhere should do so.

See https://github.com/microsoft/vscode/wiki/Search-Issues#missing-search-results for more information.

**Comment by gjsjohnmurray** [comment]
If you want the field contents not to apply, delete them. Afterwards you can reinstate them by pressing the <kbd>UpArrow</kbd> key.

**Comment by stan-ac** [comment]
Got it, thanks.
