### ISSUE TITLE
need a shorcut to open file in current editorGroup other than open to the side?

### ISSUE THREAD

**Issue by wangsongiam** [Microsoft/vscode#15836]
- VSCode Version: 1.7.1
- OS Version: 10.11.6

Steps to Reproduce:
### lookes like we don't have a shortcut to open file in current editorGroup. need a key for that other than left click
<img width="243" alt="screen shot 2016-11-21 at 3 41 20 pm" src="https://cloud.githubusercontent.com/assets/19645990/20499948/a0fbc48c-b001-11e6-9ace-95d4466eb1a3.png">

**Comment by bpasero** [comment]
`Cmd+Down`
