### ISSUE TITLE
command 'xxx' not found error for newly created extension

### ISSUE THREAD

**Issue by 20percent** [Microsoft/vscode#15837]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1 Enterprise N

Steps to Reproduce:

1. Edited Hello World example a little bit (extension.js and package.json)
2. Installed node packages for the project
3. Changed the name of extension and command (package.json)
4. Changed activationEvents(package.json)
5. Changed registerCommand accordingly
6. Installed vsce and run "vsce package" command in my extension's directory
7. Installed extension using "Install from vsix" option
8. Package is installed and vs code is restarted
9. Pressed "Ctrl + Shift + P", typed extension name, pressed "Enter"
10. (BUG) Following error is shown: 
    command 'extension.createTasksFileForDevices' not found

P.S. Extension is working correctly in debug mode. In other words, while developing, I have never encountered an error.

"Package.json":

`{
    "name": "devicesbuildtools",
    "displayName": "devicesBuildTools",
    "description": "Create tasks for build tools",
    "version": "0.0.5",
    "publisher": "pubname",
    "engines": {
        "vscode": "^1.5.0"
    },
    "categories": [
        "Other"
    ],
    "activationEvents": [
        "*"
    ],
    "main": "./extension",
    "contributes": {
        "commands": [{
            "command": "extension.createTasksFileForDevices",
            "title": "devices Build Env"
        }]
    },
    "scripts": {
        "postinstall": "node ./node_modules/vscode/bin/install"
    },
    "devDependencies": {
        "typescript": "^2.0.3",
        "vscode": "^1.0.0",
        "mocha": "^2.3.3",
        "eslint": "^3.6.0",
        "@types/node": "^6.0.40",
        "@types/mocha": "^2.2.32",
        "mkdirp": "^0.5.1",
        "fs": "^0.0.2"
    }
}`

extension.js:
`let vscode = require('vscode');
let mkdir = require('mkdirp');
let fs = require('fs');

function activate(context) {

    let disposable = vscode.commands.registerCommand('extension.createTasksFileForDevices', function () {

        vscode.window.showQuickPick(['abc', 'def'])
        .then( (op1) => {
            vscode.window.showInputBox({prompt: "give:"})
            .then( (op2) => {
                mkdir(vscode.workspace.rootPath + '\\.vscode', function(err) {
                    if( err )
                    {
                        vscode.window.showErrorMessage('Could not create directory');
                        console.log(err);
                    }
                });
            })
        })
    });

    context.subscriptions.push(disposable);
}
exports.activate = activate;

function deactivate() {
}
exports.deactivate = deactivate;`

**Comment by 20percent** [comment]
Issue is related with https://github.com/Microsoft/vscode/issues/12002

**Comment by jrieken** [comment]
Please attach the reading from the console from  the dev tools

**Comment by 20percent** [comment]
I have solved the problem. It is related with node_modules folder. When I package the extension, node_modules folder wasn't included. I have removed following part in 'jsconfig.json' and problem resolved.
`    
    "exclude": [
        "node_modules"
    ]
`
Problem can also be resolved by manually installing npm packages in "%USER%\.vscode\extensions\{extension_name} " directory

**Comment by jrieken** [comment]
Ok. Thanks for getting back to us
