### ISSUE TITLE
TypeScript Language Server failing - VS Code getting modified - macOS

### ISSUE THREAD

**Issue by bgibb95** [microsoft/vscode#158367]
Type: <b>Bug</b>

After opening a TypeScript file in Visual Studio Code (V1.70.1) in my project on macOS Monterey V12.5 (21G72), a system dialog will occasionally briefly appear saying **Verifying "Visual Studio Code.app"** and then disappear, this results in the TypeScript Language Server failing and causes missing and incorrect type information in the TypeScript file.

![Screenshot 2022-08-17 at 3 11 06 PM](https://user-images.githubusercontent.com/25341501/185142814-158570e6-ff39-4582-a70c-3efb6f3a53bc.png)

It appears that something is modifying the application at random regular intervals (~every 10 minutes) as the **Modified** timestamp is frequently updated.

![Screenshot 2022-08-17 at 3 13 32 PM](https://user-images.githubusercontent.com/25341501/185143187-3df603cc-c9e4-4a42-bace-33a2e4156ee3.png)

I have tried a system reboot and deleting the application (including deleting user data) and installing clean version of Visual Studio Code but the problem persists.

VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 43d0c62b-5756-49eb-8fe6-8555f5fa4c4b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.1.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
vscode-great-icons|emm|2.1.86
vsc-material-theme-icons|equ|2.3.1
file-icons|fil|1.0.29
fluent-icons|mig|0.0.18
material-icon-theme|PKi|4.19.0
gitblame|wad|9.0.1
material-theme|zhu|3.15.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by mjbvz** [comment]
This sounds like something external to VS Code, such as misbehaving anti-virus software

Since we haven't see more reports of this and don't have any leads on what is going wrong, I'm close this issue
