### ISSUE TITLE
user setup unable to auto-update in multi-user environment

### ISSUE THREAD

**Issue by AndCycle** [microsoft/vscode#158329]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.1 (user setup)
- OS Version: Windows Server 2022 Datacenter

Steps to Reproduce:

1. multiple user login with RDP
2. other user open Visual Studio Code for their own project.
3. CodeSetup auto-update, trying to close other user's ongoing Code.exe process, failed to auto-update

**Comment by AndCycle** [comment]
![image](https://user-images.githubusercontent.com/4460370/185005665-ab0b1cca-670a-4661-ad87-e63fd03ecde4.png)

**Comment by gjsjohnmurray** [comment]
I think the third bullet point at https://code.visualstudio.com/docs/supporting/requirements#_not-supported applies to your scenario.

**Comment by AndCycle** [comment]
@gjsjohnmurray thanks for point that out, I never thought a user setup would be an issue in this case, guess this will never get fixed.
