### ISSUE TITLE
Keep separate sizes for each viewlet (helps to read extensions better)

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#15832]
This is an simple **Enhancement proposal**.

The current behaviour for all the panel tabs (explorer / git / extension etc ...) is to keep its size permanently whatever the active tab is. But it's very annoying when you like extensions.

Here is a small workflow example :

So, when i'm working on my files on **explorer** i give the tab a reasonable small size to maximise my workspace size : 

<img width="267" alt="capture d ecran 2016-11-21 a 19 57 08" src="https://cloud.githubusercontent.com/assets/5599375/20496315/f7d68c4c-b024-11e6-9fe0-0239a6956425.png">

Then, if i go to the "Extension" tab, the same size is preserved (current default behaviour) : 

<img width="258" alt="capture d ecran 2016-11-21 a 19 57 21" src="https://cloud.githubusercontent.com/assets/5599375/20496339/11c4d0aa-b025-11e6-90b7-6a861875fab1.png">

But it hide all the most important things i want to know about extensions including icon, notes, version and for most cases, number of downloads. Which is a bunch of needed informations to judge the popularity of an extension.
At this moment in my workflow, i manually size up the tab to obtains this, which is very more comfortable and pretty : 

<img width="435" alt="capture d ecran 2016-11-21 a 19 56 48" src="https://cloud.githubusercontent.com/assets/5599375/20496392/46ca8f92-b025-11e6-9100-7fd5dfbf6c22.png">

When i'm done this my extensions, i get back to my "explorer" tab, and get this result with so many space lost : 

<img width="468" alt="capture d ecran 2016-11-21 a 19 56 38" src="https://cloud.githubusercontent.com/assets/5599375/20496519/cf2a4f58-b025-11e6-9d18-3cf0f53e7de0.png">

And i have to reduce the size again.
A good alternative for that could be to save the tab sizes, at least for the extension tab.

It's not a big deal, but small details makes great editors ;)

David B.

**Comment by ramya-rao-a** [comment]
@bpasero Maybe a setting to specify width for each of the viewlets?
```
"workbench.viewlet.width": {
    "explorer": 200,
    "extensions": 400
}
```

**Comment by bpasero** [comment]
Rather maybe we need to introduce the concept of a minimum width for each viewlet. Though the extensions viewlet does a really nice job of being readable even in the smallest size of the sidebar.

**Comment by DavidBabel** [comment]
Best approach may be to keep the current behaviour, but add options like @ramya-rao-a proposed for those who wants a more specific size customisation.

The more i think about it, the more i found it can be a simple but great visual optimisation.
