### ISSUE TITLE
Multiline edit cursors from find (`ctrl+f`) result

### ISSUE THREAD

**Issue by Kieran-Bacon** [microsoft/vscode#158394]
I love using the multiline editing feature, it is super powerful for many things, especially updating data and converting from one format to another.

The biggest fear you have when you use it is making sure you've done everything (or as much as possible) you wanted to do before you exit the multiline edit mode. Once you add new lines into the mix, it becomes impossible to reacquire the multiple cursor locations you had.

**If it were possible to use the results of a  `ctrl+f` search as the starting points of new multiline cursors**, in lots of situations you will be able to jump back into the edit. And this feature would have a minimal visual impact.

e.g. I converted a list file paths into a json file

```
/path/to/file1.txt
/path/to/file2.txt
/path/to/file3.txt
```
```
{
    "filepath": "/path/to/file1.txt",
    "var1":...
    ...
},
{
    "filepath": "/path/to/file2.txt",
    "var1":...
    ...
},
{
    "filepath": "/path/to/file3.txt",
    "var1":...
    ...
},
```
and forgot I need to set another key with a default. I can find the `},` and then move back to where I need to be and crack on.

I understand that this could be dangerous if this were being done in a much larger file, (so look forward to searching in a selection as a new feature request coming soon :P) but there are ways to get around this like taking it out of the file which would still make this a useful feature.

And yes, the find method does have to replace with regex which could be used in an equivalent way in this example but those expressions could be quite complicated to create in comparison.

**Comment by mjbvz** [comment]
Unless I am misunderstanding, this already exists: `Select all occurrences` of find match. It add cursors at every find match location
