### ISSUE TITLE
[Ctrl]+[D] adjacent text extends selection instead of selecting seperately

### ISSUE THREAD

**Issue by martin-wiseweb** [Microsoft/vscode#15835]
- VSCode Version: 1.8.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Type `aaaaa`
2. Select the first character
3. Press <kbd>Ctrl</kbd>+<kbd>D</kbd> several times

Expected Behaviour:

- The editor will select the following occurrences of `a` until all individual `a`'s are selected.

Actual Behaviour:

- The editor adds the following `a` to the current selection on each time that <kbd>Ctrl</kbd>+<kbd>D</kbd> is pressed. **This means that the second time, you are not selecting the next occurrence `a` but `aa` and the third time you are adding `aaaa` to your selection**

This is important. A common use case would be when you want to change the characters individually, or when you want to add characters _in between_ them.

With Sublime, you can select all the characters (individually) as expected:

![image](https://cloud.githubusercontent.com/assets/3329959/20498517/798e8386-affb-11e6-9120-65355521d064.png)

With VS Code, you can't even select them all, and it's one long selection (rather than several distinct ones):

![image](https://cloud.githubusercontent.com/assets/3329959/20498527/87c7aa86-affb-11e6-80c1-47e4df64c036.png)

**Comment by alexandrudima** [comment]
Dup of #11150
