### ISSUE TITLE
VSCode Insiders 1.71 wouldn't start

### ISSUE THREAD

**Issue by lorand-horvath** [microsoft/vscode#158362]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71 Insiders
- OS Version: Win 7 x64

Steps to Reproduce:

1. Since 1.71 Insiders, VSCode won't start, even though it installed without issues
2.

**Comment by bpasero** [comment]
We are possibly not supporting Windows 7 anymore with the Electron update.

See https://code.visualstudio.com/docs/supporting/requirements#_platforms

**Comment by deepak1556** [comment]
Yup it is known issue in Electron https://github.com/electron/electron/issues/35219

Also, we don't officially support Windows 7, you can instead use our web version https://code.visualstudio.com/blogs/2021/10/20/vscode-dev

**Comment by bpasero** [comment]
We might want to release note that.

**Comment by tomato013** [comment]
Could you please tell me what's the latest version that supports Windows 7? Thank you.

**Comment by deepak1556** [comment]
> We might want to release note that.

Yup will do that.

I think `1.70` which is based on `Electron 18` should still work on windows 7 but haven't verified it.

**Comment by lorand-horvath** [comment]
@deepak1556 In my other bug reports I've been told by @Tyriar that Windows 7 has been dropped since about April 2022... but I haven't been able to find information about the silence removal of Windows 7 support.
Point is 1.70 still works for me, so I'm not sure why support has been dropped at least since 1.66, but it has still been allowed to install on Windows 7. Doesn't really make sense and this needs to be addressed in some way or form.

I would, however, very much like to see 1.71 (with the new Electron 19) work on Windows 7.

**Comment by lorand-horvath** [comment]
@bpasero If Electron 19 fixes the broken Windows 7 support as per https://github.com/electron/electron/issues/35219
will VSCode 1.71 continue supporting Windows 7, will it start working again? Would like to have your thoughts on this. Thanks.

**Comment by lorand-horvath** [comment]
If anyone is interested, here's the error log when trying to start VSCode 1.71 Insiders on Windows 7 x64
```
[main] [error] SystemError [ERR_SYSTEM_ERROR]: A system error occurred: uv_os_gethostname returned ENOSYS (function not implemented)
    at Et.initServices (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:77:68046)
    at Et.startup (C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:77:63904)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bpasero** [comment]
Since we have made the decision to not list Windows 7 as supported platform anymore, consider it unsupported. We are not investing specifically to make it work in Electron 19, at least we have no plan for it at the moment.

**Comment by Tyriar** [comment]
@lorand-horvath here is where our supported OS's are declared: https://code.visualstudio.com/docs/supporting/requirements. Windows 7 is end of life and no longer even gets security updates, you should really upgrade to a newer version of Windows or some other OS to protect yourself.

**Comment by zbyna** [comment]
[Bug in Electron 19]( https://github.com/electron/electron/issues/35219) seems to be [patched](https://github.com/electron/electron/pull/35702.) Are there any other obstacles for running future vscode version in win7 at present?

**Comment by lorand-horvath** [comment]
@zbyna We'll know when VSCode updates to at least Electron [19.1](https://github.com/electron/electron/releases/tag/v19.1.0) or [20.2](https://github.com/electron/electron/releases/tag/v20.2.0)
I wouldn't hold my breath though.

**Comment by Tyriar** [comment]
We've shipped the last version of VS Code for Windows 7, see the release notes for details: https://code.visualstudio.com/updates/v1_71#_windows-7-support-has-ended
