### ISSUE TITLE
Do not prompt to sign into edit sessions if already signed into settings sync

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#158384]
1. Start from github.dev or RemoteHub on desktop with edit sessions and settings sync enabled
2. Continue Working On in a Codespace
3. :bug: Resuming edit session results in a prompt to sign in even if settings sync successfully synced

**Comment by lramos15** [comment]
I was unable to verify due to https://github.com/microsoft/vscode/issues/159287 but might be using the feature wrong so going to leave it to someone else to try as well.

**Comment by andreamah** [comment]
I'm not given the option to open in codespaces in insiders.vscode.dev? 
<img width="464" alt="image" src="https://user-images.githubusercontent.com/31675041/186970415-d4636208-0ec6-4fc2-a7fa-1509c3b289bb.png">

**Comment by joyceerhl** [comment]
You'll need to run the `Codespaces: Sign In` command first and reload the window.

**Comment by andreamah** [comment]
works awesome, thanks!!
