### ISSUE TITLE
debug console cropping is way to aggressive and poorly done

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#158374]
* debug something
* try to log/inspect some values on the console, esp with `JSON.stringify`
* 🙄 note that only around 35 lines are shown...

This is hardly useful. I learned from @connor4312 that I can copy values to the clipboard but that's insufficient. Ideas

1. use a realistic limit, maybe something that respects the perf of the machine 
2. show an indication that cropping happened (something like `...`)
3. give me an easy way to open the whole thing inside a temp editor (this is what notebook long outputs do) 

<img width="1211" alt="Screenshot 2022-08-17 at 16 07 23" src="https://user-images.githubusercontent.com/1794099/185155124-f456f73e-a603-40a5-8b43-12d53ed32e96.png">

**Comment by roblourens** [comment]
This is just a bad height calculation, has been an issue in the past

**Comment by roblourens** [comment]
Had another issue for this: https://github.com/microsoft/vscode/issues/151768
