### ISSUE TITLE
Text in terminal has a visible baseline

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#158326]
I've been seeing a lot of this since last week. I assume there's another issue for it but I don't see it
![image](https://user-images.githubusercontent.com/323878/185000620-b8eb288e-1da0-430f-90d3-0bae8babd78a.png)

**Comment by roblourens** [comment]
![Recording 2022-08-16 at 16 27 14](https://user-images.githubusercontent.com/323878/185002332-d1ddc816-774f-448e-8f43-405de5dfe00c.gif)

Is this related? It keeps happening too

**Comment by Tyriar** [comment]
@roblourens that's because of our improved underlining, it doesn't look at good on your font because it's drawn a bit lower in the cell though. What font is it?

**Comment by roblourens** [comment]
Cascadia Code

**Comment by roblourens** [comment]
With the default, still a bit off
<img width="179" alt="image" src="https://user-images.githubusercontent.com/323878/185218693-e4553fba-167e-43d9-98ed-1c3bfb902846.png">

**Comment by Tyriar** [comment]
@roblourens thanks, that's macOS with zoom level 0?

**Comment by roblourens** [comment]
Yeah

**Comment by Tyriar** [comment]
Default font on macOS (Menlo):

<img width="228" alt="Screen Shot 2022-08-19 at 1 04 24 pm" src="https://user-images.githubusercontent.com/2193314/185698800-e98a8b50-dc20-4fd7-ac8f-cd8f142d289f.png">

**Comment by Tyriar** [comment]
Font size 12:
<img width="148" alt="Screen Shot 2022-08-19 at 1 06 40 pm" src="https://user-images.githubusercontent.com/2193314/185699000-b6b4e5f1-ba6f-4161-902d-fcf63b84437c.png">

Font size 14:
<img width="167" alt="Screen Shot 2022-08-19 at 1 07 06 pm" src="https://user-images.githubusercontent.com/2193314/185699051-5f8ac7f8-ad1a-4238-b206-ccc5f8e78857.png">

**Comment by Tyriar** [comment]
Can also happen on dpr 1 (Windows 11, Hack):

![image](https://user-images.githubusercontent.com/2193314/185699521-252a9b2e-da5e-4116-806f-e066cce91035.png)
