### ISSUE TITLE
How to rollback GIT conflict resolution

### ISSUE THREAD

**Issue by wyh888888** [microsoft/vscode#158333]
Type: <b>Feature Request</b>

Now Git conflict resolution is very difficult to use, the previous one is very good, why change it

VS Code version: Code 1.70.1 (Universal) (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:09:06.916Z)
OS version: Darwin x64 20.6.0
Modes:

![image](https://user-images.githubusercontent.com/37473663/185031277-dcb5b867-696a-4a83-93fd-e6697bde9a78.png)

**Comment by gjsjohnmurray** [comment]
You can switch back by changing the `git.mergeEditor` setting.

**Comment by wyh888888** [comment]
> You can switch back by changing the `git.mergeEditor` setting.

thanks! That helped resolve this.
