### ISSUE TITLE
Ignored custom php executable path

### ISSUE THREAD

**Issue by Brakkar** [Microsoft/vscode#15830]
- VSCode Version: 1.7
- OS Version: macOS current version

Steps to Reproduce:
hi,
Tried to use php, so set the php 7 executable path to:

"php.validate.executablePath": "/Applications/MAMP/bin/php/php7.0.12/bin/php",

which is a path that works with other ide.

Still vscode ignore this setting and goes for /usr/bin/php which is php5

**Comment by daniel-lahoz** [comment]
Exact same problem here.

Always get Error: "The language server needs at least PHP 7 installed and in your PATH. Version found: 5.6.25"

VSCode Version: 1.8.0-insider (1.8.0-insider)
OS Version: macOS 10.12.1
MAMP 4.0.6 with PHP 7.0.12

**Comment by eyalsk** [comment]
Maybe related to #15447

**Comment by mousetraps** [comment]
I included a full run down of potential failure modes here, so see resolution steps there: https://github.com/Microsoft/vscode/issues/13356#issuecomment-252541241

@daniel-lahoz, you're in CASE 3.2, so as detailed, I suggest doing the following:
> Add the path to PHP7 to your environment variables, run where php and php --version to verify. You'll also need to relaunch VSCode (and the cmd line you are launching it from if you changed the environment variables)

@Brakkar when you say "vscode ignores this setting", how do you know that the setting is being ignored? Mind taking a screenshot and providing the full error text? Are you getting squigglies on otherwise valid PHP7 code?

**Comment by ytn3rd** [comment]
@mousetraps this is the setting being set, but is being ignored. Unless the setting doesn't do what we think it does? Full path set does exist as you can see in the second screenshot, but terminal  window still tries to use the default CLI version of php not the one set in executable path.

<img width="2044" alt="screen shot 2017-03-04 at 3 25 24 pm" src="https://cloud.githubusercontent.com/assets/904737/23576061/eba731fe-00ee-11e7-9677-301a585e7f6a.png">

<img width="569" alt="screen shot 2017-03-04 at 3 27 28 pm" src="https://cloud.githubusercontent.com/assets/904737/23576069/1e9f30de-00ef-11e7-90c2-ea8e6f5ec3c5.png">

**Comment by gihanshp** [comment]
@Brakkar Try updating the`php.executablePath` if you are using **phpIntelliSense** plugin

**Comment by roblourens** [comment]
Is this still an issue for anyone? This is a bit old and I'm not aware of a bug here.

Troubleshooting tips from Sara are here: https://github.com/Microsoft/vscode/issues/13356#issuecomment-252541241
