### ISSUE TITLE
Move tab close "x" to left-side for easy access

### ISSUE THREAD

**Issue by brendandixon** [Microsoft/vscode#15833]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|vscode-docker|PeterJausovec|0.0.7|
|code-settings-sync|Shan|2.3.8|
|githistory|donjayamanne|0.1.0|
|python|donjayamanne|0.5.2|
|haml|groksrc|0.0.2|
|Go|lukehoban|0.6.49|
|csharp|ms-vscode|1.5.2|
|Ruby|rebornix|0.10.2|

---

Steps to Reproduce:

1. Open multiple tabs
2. See how the closing "x" in on the right-side? Move it to the left-side.

One of the things Safari gets right is its placement of the tab close "x". By placing it on the left, you can quickly close tabs without moving the pointer about (since the left-side remains constant, while the right-side moves about based on tab name). It would be nice if VSCode did likewise. :)

**Comment by TheColorRed** [comment]
Why not just "Right click" and select "Close to the right"?

**Comment by brendandixon** [comment]
@TheColorRed Far, far less obvious and it is more clicks: One right-click to bring up the menu, second click to select "Close to the right." Better a single click on a left-justified "x". It's why Safari works this way.

**Comment by TheColorRed** [comment]
I don't see where you get more clicks from...

- Option 1 (middle mouse click): 1 click per tab
- Option 2 (close to the right): 2 clicks for unlimited number of tabs

**Comment by brendandixon** [comment]
@TheColorRed Try Safari and you'll see the feature I'm after. I don't want to always close all tabs to the right.

**Comment by TheColorRed** [comment]
@brendandixon I understand what you're saying... What I am saying is just place your mouse on the left side of the tab (or anywhere on the tab), and just middle mouse click it. You will get the same close effect.

**Comment by reaktivo** [comment]
@bpasero @jrieken Would a external contributor's PR for this feature be considered?

**Comment by bpasero** [comment]
@reaktivo yes, we are always open to PRs as long as they make sense 👍

**Comment by bpasero** [comment]
Verify: there is a new setting `workbench.editor.tabCloseButton` with the options `left`, `right` and `off`.  Changes update live and the dirty indicator is still always visible.
