### ISSUE TITLE
Two instances of task launched after reloading

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#158305]
I see this in the vscode-jupyter repo with their "Compile" task but it is not fancy so probably a general issue

- Start the Compile task
- Reload the window
- Start debugging, which has `"preLaunchTask": "Compile",`
- Now there are two instances of the Compile task running

**Comment by meganrogge** [comment]
probably fixed by https://github.com/microsoft/vscode/pull/158298, so should be fixed in tomorrow's insider's. pls reopen if not
