### ISSUE TITLE
tab scrollbar is possessed 😵

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15849]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

See gif below - zoom level is moderately high, and many tabs exist in the left tab wells. After dragging a file from right to left tab well, the tab scrollbar moves all the way to the left. any further attempts to scroll back to the right will fail, as the scrollbar has taken on a life of its own. 
![2016-11-21_17-38-03](https://cloud.githubusercontent.com/assets/762848/20507739/719d0164-b011-11e6-88e9-dd02146318c6.gif)

**Comment by bpasero** [comment]
@mousetraps hard to reproduce for me in insiders, I wonder if this got fixed with the Electron update. Can you try with insiders to reproduce?

**Comment by bpasero** [comment]
@mousetraps ping

**Comment by mousetraps** [comment]
@bpasero sorry for the late reply - just validated that I can no longer repro, so looks like it got fixed
