### ISSUE TITLE
http://127.0.0.1:xxxx/ Access to the application？

### ISSUE THREAD

**Issue by Cyclone77** [Microsoft/vscode#15843]
- VSCode Version: all
- OS Version:

Can you add this functionality？

**Comment by jrieken** [comment]
@Cyclone77 what?

**Comment by Cyclone77** [comment]
@jrieken A simple HTML page access, you can use 'http://127.0.0.1:xxxx/' way, good, what do you think?

**Comment by jrieken** [comment]
You can implement that as extension. From there start up a web server, serving the files in the workspace, add commands to open a resource from the workspace in a browser

**Comment by Cyclone77** [comment]
@jrieken Thank you, Now through the iis web server configuration.But, to write a simple HTML example, inconvenient, I think.

**Comment by jrieken** [comment]
Since the extension host is like nodejs you can use only of the many existing packages that are available there

**Comment by Cyclone77** [comment]
Thank you for
