### ISSUE TITLE
problem in the terminal 

### ISSUE THREAD

**Issue by marcelsev** [microsoft/vscode#158462]
Type: <b>Performance Issue</b>

The terminal malfunctions because vertical bars appear that hide the content and do not allow to work correctly with it. 

VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 17.7.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     P8600  @ 2.40GHz (2 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 12, 36|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_544901 --crash-reporter-id 6e48c269-7c63-4e52-a068-5623eaf67f1e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   18	    98	  7876	code main
    0	    49	  7879	   gpu-process
    0	    25	  7881	   utility-network-service
    0	   197	  7882	   window (Iniciar — Web-Developer-P6-master)
    0	   131	  7887	   shared-process
    0	    49	  7889	     ptyHost
    0	     0	  7908	       /bin/bash --init-file /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	     0	  7923	       /bin/bash --init-file /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh
    0	    41	  7893	     fileWatcher
    0	     0	  7992	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   287	  7888	   extensionHost
    0	    82	  7982	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Iniciar — Web-Developer-P6-master)
|    Folder (Web-Developer-P6-master): 74 files
|      File types: ts(19) json(9) scss(9) html(8) DS_Store(2)
|                  browserslistrc(1) editorconfig(1) gitignore(1) md(1) js(1)
|      Conf files: launch.json(1) tasks.json(1) package.json(1)
|                  tsconfig.json(1)
|      Launch Configs: pwa-chrome chrome;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.1.0
gitlens|eam|12.1.2
live-sass|gle|5.5.1
vscode-language-pack-es|MS-|1.70.8170911
vsliveshare|ms-|1.0.5690
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
LiveServer|rit|5.7.5
code-snapshot|rob|0.2.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by marcelsev** [comment]
![Captura de pantalla 2022-08-18 a las 11 34 30](https://user-images.githubusercontent.com/101347684/185363142-ba79f5d9-f891-416f-ac20-e032131ef52d.png)
in the image you can see the problem of the bars that appear and cover the content and also the whole content of the terminal is not well visualized.

**Comment by marcelsev** [comment]
![Captura de pantalla 2022-08-18 a las 11 38 14](https://user-images.githubusercontent.com/101347684/185363726-9017c8c7-e3c9-45e3-a59d-c5b313b0a3eb.png)

**Comment by meganrogge** [comment]
Does changing terminal.integrated.gpuAcceleration help?

**Comment by marcelsev** [comment]
OMG thank you very much I searched all over the internet for the solution and nothing until I thought of putting it here and finally it was solved. thank you very much.  :)

**Comment by Tyriar** [comment]
I believe this is already fixed (in https://github.com/xtermjs/xterm.js/pull/4102 or https://github.com/xtermjs/xterm.js/pull/4181) , can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.
