### ISSUE TITLE
Snippet \^2 doesn't work

### ISSUE THREAD

**Issue by davidanthoff** [Microsoft/vscode#15841]
- VSCode Version: 1.7.1
- OS Version: Windows 10

The following snippet definition doesn't seem to work:
````
"^2": {
		"prefix": "\\^2",
		"body": [ "²" ],
		"description": "^2",
		"scope": "source.julia"
	}
````
Is that a known limitation of VS Code at the moment? When I am in a julia file and try to type ``\^2``, I don't get any list of things that I could complete.

**Comment by jrieken** [comment]
@davidanthoff What does 'doesn't work' mean? It doesn't show up in the 'insert snippet' quick pick, it doesn't show up in the IntelliSense, it shows but fails to insert?
