### ISSUE TITLE
vscode not opening

### ISSUE THREAD

**Issue by Phylex1** [microsoft/vscode#158426]
Does this issue occur when all extensions are disabled?: dont know i get "access is denied"

- VS Code Version: latest
- OS Version: win 10 

How it happened:

Update bugged out and vscode closed down.
Now when tryed to open, nothing happened, so i went and ran Code.exe where it spat out:
Windows cannot access the specified device,path or file. You may not have the appropriate permissions to access the item.
I then ran Code.exe in cmd and also again with --verbose and it just says "access is denied".
I tried uninstalling vscode and it will not uninstall Code.exe
i tried reinstalling where it said that it could not rewrite Code.exe.

What should I do to fix this?

**Comment by joaomoreno** [comment]
> I tried uninstalling vscode and it will not uninstall Code.exe

What happens when you try uninstalling it? Can you share a screenshot?

**Comment by Phylex1** [comment]
> > I tried uninstalling vscode and it will not uninstall Code.exe
> 
> What happens when you try uninstalling it? Can you share a screenshot?

it just says it cant overwrite it and when i try again it sends the same let me send a screenshot
![image](https://user-images.githubusercontent.com/108032441/185815584-cf336475-4cf1-43ca-ad67-148364fdc49e.png)
and also with this:
![image](https://user-images.githubusercontent.com/108032441/185815635-6dfcd5d0-2393-4ea9-a9ee-c089cb91805f.png)

**Comment by Phylex1** [comment]
update: 

I checked again today and the Code.exe was gone randomly & I managed to reinstall and it works fine now. Not sure what happened, but I do know it was from a update that failed or glitched.
