### ISSUE TITLE
Slow Intellisense (vs code last version) on mac

### ISSUE THREAD

**Issue by amanna7** [microsoft/vscode#158463]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.70.2 (I tried both Universal and M1 chip version)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z (2 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0
- OS Version: Monterey 12.5 M1 chip

Steps to Reproduce:

1. Open a typescript file
2. Try to use intellisense
3. wait 1 min to have it...

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by amanna7** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

yes as I wrote on the first comment, but it seems to be a repository issue, everything works smooth on another repo, so you can close this (sorry about that, I should think about this before xD)
