### ISSUE TITLE
Allow to drop a folder from outside into the explorer to copy it

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15847]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

Currently, the behavior is that VSCode will open the folder in the workspace, no matter where you drag it. But sometimes, you want to copy a folder into the current workspace.

**Comment by bpasero** [comment]
We disable this to prevent accident large file copy operations. There is no real technical reason otherwise.
