### ISSUE TITLE
Markdown section folding interrupted by python comments

### ISSUE THREAD

**Issue by kpblackatverisk** [microsoft/vscode#158440]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### Summary

I expected that folding cells per a markdown header level would collapse all of the markdown and code cells under that header, per the VS Code Outline view of the notebook.

In practice though, if there is a markdown cell with a python code block, then the comments in that python code block are considered the next top-level markdown section which interrupts the code folding.

### Steps

1. Make a new `.ipynb` file and set the interpreter
2. Make markdown cell with content: `# Cell 1`
3. Make markdown cell: `Cell 2: Some markdown content`
4. Make code cell:
```python
# cell 3: print a friendly message
print('hello world')
```
5. Make markdown cell:
```markdown
Cell 4: Execute the following:

```python
# print a friendly message
print('hello world')
```<end the code block>
```
6. Collapse the `# Cell 1` cell
7. Note that cells 2 and 3 are collapsed and hidden, but cell 4 is not

### Work around
Add additional `#`'s to the embedded python comment so that its not at the same level of the makrdown section it is under; e.g.,
```markdown
Cell 4: Execute the following:

```python
## print a friendly message
print('hello world')
```<end the code block>
```

### VS Code Version

1.70.0

### Jupyter Extension Version

v2022.7.1102252217

### Jupyter logs

```shell
Not applicable, since there is no output when folding or unfolding a markdown section.
```

### Coding Language and Runtime Version

Python 3.8.13

### Language Extension Version (if applicable)

v2022.12.0

### Anaconda Version (if applicable)

conda 4.13.0

### Running Jupyter locally or remotely?

Local

**Comment by eleanorjboyd** [comment]
still seeing this issue- lmk if my setup is wrong. thanks!
<img width="1322" alt="Screenshot 2023-01-25 at 1 11 16 PM" src="https://user-images.githubusercontent.com/26030610/214691806-8d6a7a2a-4e0f-44ba-99e7-00a9fc7287d2.png">
<img width="1314" alt="Screenshot 2023-01-25 at 1 11 11 PM" src="https://user-images.githubusercontent.com/26030610/214691808-c3b2272d-e227-4177-98fc-ae26c1534f4d.png">

**Comment by mjbvz** [comment]
@eleanorjboyd Can you try finishing editing the cells to put them into render mode:

![Screenshot 2023-01-25 at 1 18 48 PM](https://user-images.githubusercontent.com/12821956/214693180-d5ac3dca-bd3d-4e5a-807a-8f6a4a28a36b.png)

I don't think we update the folding until the cell is no longer being edited

**Comment by eleanorjboyd** [comment]
was verifying another issue and this works now!
