### ISSUE TITLE
Show better drop feedback when trying to drop files on areas that are not allowed

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15845]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

Actual: "Move" icon
> ![image](https://cloud.githubusercontent.com/assets/762848/20506954/844475fe-b00c-11e6-827b-0145d2ebda8b.png)

Expected: "Not allowed" icon
> ![image](https://cloud.githubusercontent.com/assets/762848/20506965/abc28efe-b00c-11e6-942d-6d5f5f313396.png)

**Comment by bpasero** [comment]
This is probably electrons (rather Chromes) default feedback so that you can drop a file into a window to open it in there. Not sure how best to disable it.
