### ISSUE TITLE
Multifile replace breaks with multiline regex `\n\s*\{`

### ISSUE THREAD

**Issue by blaumeise20** [microsoft/vscode#158489]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.70.1
Commit: 6d9b74a70ca9c7733b29f0456fd8195364076dda
Date: 2022-08-10T06:09:06.916Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:
1. Create an empty folder and open it in VS Code.
2. Create two files `test_1.php` and `test_2.php` in that folder.
3. Put this in both files:
    ```php
    <?php
    if ($v_hello)
    {
        if ($v_world)
        {
            echo "Hello World";
        }
    }
    if ($v_hello)
    {
        if ($v_world)
        {
            echo "Hello World";
        }
    }
    if ($v_hello)
    {
        if ($v_world)
        {
            echo "Hello World";
        }
    }
    if ($v_hello)
    {
        if ($v_world)
        {
            echo "Hello World";
        }
    }
    if ($v_hello)
    {
        if ($v_world)
        {
            echo "Hello World";
        }
    }
    if ($v_hello)
    {
        if ($v_world)
        {
            echo "Hello World";
        }
    }
    ```
4. Close both files and reload the window.
5. Without opening the files, go to Search and enter this:
    Search: `\n\s*\{` (enable regex mode)
    Replace: <code>&nbsp;{</code>
6. Press Enter.

You can clearly see the bug. It should be able to replace all braces to be on the line above, but in one of the two files it breaks:
![Bildschirmfoto 2022-08-18 um 15 32 22](https://user-images.githubusercontent.com/62756994/185407681-cd22b5c6-6a1b-4f23-a754-63858eb6ba72.png)

This wouldn't be a problem with a few files, but I have about a 800 files with probably 30k-40k occurrences of such a brace in total.

-------
<sup>Please don't ask why I even want to replace those braces.</sub>

**Comment by roblourens** [comment]
I believe this is another case of https://github.com/microsoft/vscode/issues/131507, which we need to take a look at, sorry for the trouble
