### ISSUE TITLE
Test updating markdown paths on file move/rename

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#158416]
Test for #148146

- [x] Mac @rzhao271
- [x] Linux @connor4312
- [x] Windows @Yoyokrazy

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158416%0A%0A&assignees=mjbvz)

---

## Overview
This new feature allows markdown to automatically update all markdown links when a file is renamed/moved in the workspace. This is only supported for file moves/renames that happen within VS Code's explorer. It is also only supported for markdown style links (not html `<a>` links inside markdown)

## Testing
- Enable this new behavior using `"markdown.experimental.updateLinksOnFileMove.enabled": "prompt"`
- Create some markdown links to local files:

     For this, try out some of these variants:

    - `[text](/workspace/root/path/to/file.md)`
    - `[text](relative/path/to/file.md)`
    - `[text](path/fileNoExt)` (should reference `path/fileNoExt.md`)
    -  `[text](path/file.md#some-header)`
    -  `![alt](path/img.png)`
    -  `[definition]: /path/to/file.md`
    
- Ensure that with `prompt`, renaming or moving any `md` or image file triggers a dialog that lets you update all markdown links

- Now try renaming some directories that contain the referenced files. Ensure this also triggers a update

- Finally try changing `markdown.experimental.updateLinksOnFileMove.externalFileGlobs`. This setting controls the types of files we try updating paths for (we always enable it for markdown files).

    The default value enables it for common image file names. Try enabling it for `.js` files or some other format too

**Comment by mjbvz** [comment]
Yes something is broken so please hold off on testing this

**Comment by mjbvz** [comment]
Should by fixed by https://github.com/microsoft/vscode/pull/158965 but you'll need to be on tomorrow's insiders build to test

**Comment by Yoyokrazy** [comment]
Same user vs workspace setting issue as connor in #159084 

Otherwise working as intended
