### ISSUE TITLE
tsconfig not being detected

### ISSUE THREAD

**Issue by krisscox** [microsoft/vscode#158465]
Type: <b>Bug</b>

As of the most recent VS Code version (1.70.2), my tsconfig files are not being detected with VSC just displaying "No tsconfig" in spite of there being one in the project root.

I am using Pop! OS 22.04 LTS if it helps

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:25.715Z)
OS version: Linux x64 5.18.10-76051810-generic
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|31.27GB (24.74GB free)|
|Process Argv|--unity-launch --crash-reporter-id 34b47547-fe82-410d-b545-6925ce668c92|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
EditorConfig|Edi|0.16.4
file-icons|fil|1.0.29
vscode-env|Iro|0.1.0
vscode-duplicate|mrm|1.2.1
volar|Vue|0.40.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by krisscox** [comment]
I have tried apt purge code, and then reinstalling the .deb from the website, with no luck

**Comment by IllusionMH** [comment]
Are you sure your `tsconfig.json` has these files included? And if it is for JS files - if it has 
 `"allowJS": true`

**Comment by krisscox** [comment]
Sorry for the confusion, it's the tsconfig.json itself that's not being detected by VS Code, not files listed within the tsconfig

**Comment by krisscox** [comment]
It's just fixed itself somehow - for anyone who finds this, I'm using Serverless Stack (SST) which comes with two tsconfig files, the second is in the /services folder and extends the first. I opened a .ts file that would use the primary tsconfig (outside of the services folder) and it then detected it, I then opened a .ts file in the /services folder, which would use the child tsconfig and it now detects it.

I think VS Code for whatever reason wasn't able to detect the parent until it was used, and then allowed for the child tsconfig to be used.

**Comment by IllusionMH** [comment]
You had clear description.

It's just first step of troubleshooting as "No tsconfig" status would be shown for files in workspace if they are simply not included in `tsconfig.json` and therefore not included in TS project.

Or specify what do you mean under `tsconfig.json` not being detected
