### ISSUE TITLE
NPM Script Explorer side panel has vanished

### ISSUE THREAD

**Issue by GU0FORY1** [microsoft/vscode#158448]
like #120279
vscode version: 1.70.2
OS: Darwin arm64 21.6.0
<img width="408" alt="image" src="https://user-images.githubusercontent.com/42399180/185333092-cd5b2f2d-4d27-4fd8-bd2c-5e1738f963c9.png">

**Comment by gjsjohnmurray** [comment]
Please try running `Explorer: Focus on NPM Scripts View` from Command Palette.

**Comment by GU0FORY1** [comment]
> Please try running `Explorer: Focus on NPM Scripts View` from Command Palette.

The panel still disappears
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/42399180/185341580-d58712e6-c8a8-4d1f-9cd7-a1a07504bb8a.png">

**Comment by ArturoDent** [comment]
You can also try the `View/Open View...` option from the main menu and then search for `NPM Scripts` to see if it comes back.

**Comment by GU0FORY1** [comment]
> You can also try the `View/Open View...` option from the main menu and then search for `NPM Scripts` to see if it comes back.

thks！！it worked
