### ISSUE TITLE
Search within breadcrumbs no longer works

### ISSUE THREAD

**Issue by dcmills2** [microsoft/vscode#158499]
Version: 1.70
Operating System: Windows 10 AND Ubuntu 20.04
Extensions: C/C++ themes, Remote - SSH, Remote - SSH: Editing configuration Files, Remote - WSL
This is reproducible after disabling all extensions.

Issue description:
Before 1.70, you could click on a directory in the breadcrumbs view, and start typing to search for a file within that directory. That feature was originally added here: https://github.com/microsoft/vscode/issues/55004
Now, nothing shows up when you start typing. The list of files will automatically highlight a file which starts with the character you type in, but you cannot fully search the directory.

Attached is a screenshot showing the breadcrumb menu I'm talking about. I pressed the "f" key on my keyboard. You can see it highlighted the first file starting with 'f' but did not pull up a search box like it used to before 1.70.
![image](https://user-images.githubusercontent.com/47228354/185427467-03be05db-745d-4d7b-a542-a467a1dec195.png)

**Comment by gjsjohnmurray** [comment]
In all the trees and lists, including the one used in breadcrumbs, you now need to begin a search/filter operation by pressing Ctrl/Cmd + F

**Comment by dcmills2** [comment]
Thanks @gjsjohnmurray, I did not realize that
