### ISSUE TITLE
View menu consistency and length

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#158458]
We are filling the "View" menu more and more with text editor specific things:

![image](https://user-images.githubusercontent.com/900690/185352190-ac81c871-f67f-4b8c-836d-a874a8524e98.png)

Bringing this up as a UX issue to think about if this is scaling going forward. Especially in the context of VSCode supporting custom editors and notebooks, I think this may not be the right solution, at the minimum maybe have a sub menu?

//cc @hediet

**Comment by misolori** [comment]
Would a menu item like `Editor Features >` make sense either in the first group or at the end?

**Comment by daviddossett** [comment]
> Would a menu item like `Editor Features >` make sense either in the first group or at the end?

To clarify, would that capture just these items? 👍 if so. Seems like it would fit nicely under `Editor Layout >`.

<img width="285" alt="CleanShot 2022-08-18 at 11 08 21@2x" src="https://user-images.githubusercontent.com/25163139/185464429-19e082b3-3d9b-4fe5-a8c2-3f45d2c2605e.png">

**Comment by misolori** [comment]
Here's to clarify what I meant: if we look at the "categories" it makes sense to be placed in the first group:

![CleanShot 2022-08-18 at 11 48 12](https://user-images.githubusercontent.com/35271042/185471303-76cd24f3-c065-444a-ac7f-474fcdcc8699.png)

but, it also seems like it would fit inside of the other submenu groups even though they are different categories:

![CleanShot 2022-08-18 at 11 48 46](https://user-images.githubusercontent.com/35271042/185471412-adad551a-25c2-4485-ab96-6d2a247871bb.png)

**Comment by daviddossett** [comment]
The second option is what I had in mind since it feels more closely aligned to how the editor is configured. The first section roughly seems like a place to do something once vs. toggling elements on/off.

**Comment by misolori** [comment]
The argument against that is those two items (Appearance and Editor Layout) are layout specific, whereas these would be feature toggles, so a little different.

**Comment by bpasero** [comment]
Yes, +1 for grouping into a category. I think somewhere close to "Editor Layout" is OK since that applies to editors. 

One thing to consider is that afaik these toggles only apply to text editors, not all editors.

**Comment by sbatten** [comment]
As @jrieken pointed out, this has a high chance of causing anger for a minor beautification. Based on his experience, he would not move forward with this for the most popular commands in the menu. This looks to be Word Wrap.

Should we keep word wrap where it is and add a  submenu entry below that named: "Additional Editor Options"

**Comment by daviddossett** [comment]
As a gut reaction it feels strange to split these out into a single option + all others folded into a submenu. Would these still be in this section?

<img width="223" alt="CleanShot 2022-10-20 at 08 45 18@2x" src="https://user-images.githubusercontent.com/25163139/196996034-2fa56a98-625b-47fe-9f33-22fd7319befa.png">

Or would everything be put back at the bottom like it was before? If so I might argue for us to simply revert to what was there before vs. some in-between solution. 

<img width="319" alt="CleanShot 2022-10-20 at 08 46 14@2x" src="https://user-images.githubusercontent.com/25163139/196996243-2b5069f5-3a11-4871-a942-ee090e30e694.png">

**Comment by sbatten** [comment]
I would guess it makes sense to keep it on the bottom. It seems the original problem is that we keep adding to this list so we cannot scale it. So having the top/high-use ones in the main entry and overflowing has some merit, but I agree that in between feels strange.

**Comment by sbatten** [comment]
@jrieken was your experience in the top level menu or for a context menu entry? if it was a context menu, I would imagine the usage was significantly higher, but I'd like to verify that through data. Could you share the command id?

**Comment by jrieken** [comment]
Yeah, those was the editor context menu. It's already one or two years ago but I remember folks missed some but not all peek actions. Like peek references/definition are popular but peek implementation isn't etc. We decided all go-to commands are more popular than any peek command. That looks nice/stable but wasn't a good choice. That's why I am in favour of a hybrid approach

**Comment by bpasero** [comment]
Works for me, thanks!
