### ISSUE TITLE
Auto-store edit sessions on window close

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#158409]
https://github.com/microsoft/vscode/pull/157733 introduces `workbench.experimental.editSessions.autoResume` which controls when we attempt to restore an edit session for the current workspace. The user still has to remember to store their edit session or use the explicit Continue Working On trigger.

In order to make it harder to lose edit sessions across github.dev, insiders.vscode.dev, vscode.dev, and RemoteHub on desktop, we should introduce a setting `workbench.experimental.editSessions.autoStore` with initial setting values `off` and `onClose`. When set to `onClose`, we'll attempt to store the current edit session (if any) before a workbench unload. 

This will only really reliably work in desktop because in web we cannot run long running tasks in the onbeforeunload handler (https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/147, tracked in https://github.com/microsoft/vscode/issues/150744). To mitigate this we should also explore introducing an `afterDelay` option to continuously sync edit sessions. That first requires tolerance of edit sessions originating from multiple VS Code clients concurrently.

**Comment by connor4312** [comment]
On vscode.dev, we do have a service worker which is used primarily for caching. Service workers can outlive their associated pages, and can be synchronously `postMessage`'d to like other workers. Perhaps we can use that service worker (or a new one) to allow the workbench to send information to save before it unloads.
