### ISSUE TITLE
Disable import organization on individual files

### ISSUE THREAD

**Issue by ian-weir** [microsoft/vscode#158507]
Similar to prettier having // prettier-ignore or TypeScript having // @ts-expect-error it would be nice if we could have something like // disabled-import-organization.

This stems from an issue I had where the order of some imports in the project resulted in an error when the imports were organized alphabetically and it caused an error which was fixed by rearranging the import statements. Obviously the better fix would to be to change the structure of the system to eliminate this error regardless of the order. In the meantime it would be nice to ignore that individual file

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
