### ISSUE TITLE
Tree: Support moving the find widget vertically

### ISSUE THREAD

**Issue by memeplex** [microsoft/vscode#158549]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macOS Monterey

Steps to Reproduce:

1. In the file explorer press cmd-f
2. Write something such that only one match remains in the tree
3. Now the filter partially hides the match and there's no way to get rid of it without destroying the filter:

<img width="278" alt="image" src="https://user-images.githubusercontent.com/2845433/185545788-75f40db1-ad7f-440c-a8d5-9ff9eecafb6e.png">

**Comment by gjsjohnmurray** [comment]
Maybe we should allow one row of vertical movement for the floating find widget.

![junk](https://user-images.githubusercontent.com/6726799/185565573-2b0a8166-2c11-4872-a43a-95fd48c9de5b.gif)

@joaomoreno what do you think? If you agree I can provide a PR.

**Comment by joaomoreno** [comment]
Sure why not!

**Comment by mitsukuri** [comment]
Moving the widget manually doesn't seem like good UX, it would be better to shift all text content below the widget.
