### ISSUE TITLE
Sticky scroll for salesforce apex (.cls) code

### ISSUE THREAD

**Issue by puenteNicholas21** [microsoft/vscode#158542]
Loving the new sticky scroll feature in vscode.  I understand its still preview but wanted to just nudge salesforce apex (.cls) code get added to the mix if not already for this feature

**Comment by gjsjohnmurray** [comment]
Does that code already get handled well by the Outline view? If so, once you are using 1.71 (currently Insiders) you should have a good experience with sticky scroll.

**Comment by puenteNicholas21** [comment]
@gjsjohnmurray, yes it does appear to properly outline the file.  thanks for the reply.  i'll be on the lookout for 1.71
