### ISSUE TITLE
Put more emphasis on keyboard selected items

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#158566]
I really like the work on the new context menu!

I think here the contrast for the active element could be increased though:
![image](https://user-images.githubusercontent.com/2931520/185585132-c0870602-3c1b-45c8-861c-275ae0314b5c.png)

Maybe some background color?

Maybe the full blue background one should be swapped with the keyboard selected one?

**Comment by justschen** [comment]
This actually got fixed in a PR yesterday where the colors are swapped and the main highlight stays on keybinding until the cursor moves again.
