### ISSUE TITLE
Simple browser opener doesn't work with IPv6 hosts

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#158599]
Pretty sure the problem is here:

https://github.com/microsoft/vscode/blob/82fce9f053fda71dd7d0f89ef32f2b5748eabe19/extensions/simple-browser/src/extension.ts#L70-L71

When passed the string `"http://0:0:0:0:0:0:0:0:3000/"`, `new URL` throws. You can reproduce the issue by trying to "open in preview" the auto detected port that you get when running the server in https://github.com/joshaber/simple-server/tree/devcontainer-preview from a codespace.

**Comment by gjsjohnmurray** [comment]
Is this related to #158469?

**Comment by alexr00** [comment]
It's similar, but the `URL` in this issue in the extension, whereas that PR relates to the internal `URI` class.

**Comment by mjbvz** [comment]
After reviewing this again, Is `http://0:0:0:0:0:0:0:0:3000/` actually a valid url that we should support?

I thought you had to wrap ipv6 addresses in `[ ]`, e.g. `http://[0:0:0:0:0:0:0:0]:3000/`. I can confirm that works in browsers and that `new URL` already was parsing that correctly. @alexr00 Do you think the PR is still needed?

**Comment by alexr00** [comment]
Some change is needed here, even if it's not the one that I made. Should `uri.toString()` include the `[ ]`?

**Comment by mjbvz** [comment]
@alexr00 I think we may be hitting: #154048

We likely should skip encoding of the uri, which I believe should fix this (provided the uri is correct in the first place). Tentatively pushing to October though since this is a more dangerous change
