### ISSUE TITLE
Focusing activity bar with high contrast theme isn't very visible

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#15857]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.8.0-26-generic

Focus on debug:

![image](https://cloud.githubusercontent.com/assets/2193314/20511065/e4e02ada-b029-11e6-8e0e-0714a47f6b92.png)

Focus on extensions:

![image](https://cloud.githubusercontent.com/assets/2193314/20511096/137261a6-b02a-11e6-8aa7-2fd80ddb77eb.png)

Can the bright one be on debug as well?

**Comment by bpasero** [comment]
For me all viewlets show the same feedback once focussed:

![editors](https://cloud.githubusercontent.com/assets/900690/20512615/d8c5ed3c-b080-11e6-94b1-00a66919d7f5.gif)

Please clarify the issue you see.

**Comment by Tyriar** [comment]
Oh I mean `:active` via tab focus.

**Comment by bpasero** [comment]
![editors](https://cloud.githubusercontent.com/assets/900690/20513148/5e7465b4-b084-11e6-8fa1-b871b3b0afbf.gif)

@Tyriar still they all look the same to me?

**Comment by bpasero** [comment]
@Tyriar I see what you mean, when you focus into the current active viewlet, the orange bar to the left shows up stronger. I am not sure who added this, I think @bgashler1 might be the one?

**Comment by bpasero** [comment]
Closing as designed, no plans to change it currently.
