### ISSUE TITLE
command editor.action.triggerSuggest support fromOnly option

### ISSUE THREAD

**Issue by ssddi456** [microsoft/vscode#158554]
https://github.com/microsoft/vscode/blob/aca007480559ff91fcecd31cafe01955e433b379/src/vs/editor/contrib/suggest/browser/suggestController.ts#L706-L724

the command editor.action.triggerSuggest do not support caller select a provider to provide suggestion,

consider this scens:
1. a typed yaml file, extension provide property key suggestion, 
2. user select a key suggestion,
3. then there could be a immdiate suggestion for value from enums

at current state, unlike vscode itself, extension can only call up suggest  for all provider.

**Comment by jrieken** [comment]
> at current state, unlike vscode itself, extension can only call up suggest for all provider.

Yeah, I also don't see how extension can enumerate other providers to fulfil this contract. The option works on object-instances which only live inside the renderer process, not the extension process. 


What is it that you want to achieve here?

**Comment by ssddi456** [comment]
> 1. a typed yaml file, extension provide property key suggestion,
> 1. user select a key suggestion,
> 1. then there could be a immdiate suggestion for value from enums

for a more fluent experience, when user pick a suggestion provided by my SuggestionProvider, how can i provide advanced suggestions from this extension only?
```ts
if (key === LABEL_FLOW) {
    ret.push(
        ...(await this.flowS.getAllFlowId()).map(x => ({
            label: `aviable flow: ${x}`,
            insertText: x,
            command: this.suggestProvider,// how?
        }))
    );
}
```

**Comment by jrieken** [comment]
> how can i provide advanced suggestions from this extension only?

You cannot and we won't enable that because suppressing other extensions is not what we want. We want a fair playing field and extensions should be able to contribute good completions in all cases.
