### ISSUE TITLE
[Bug] `treeFindOpen` is `false` when search widget is focused

### ISSUE THREAD

**Issue by wenfangdu** [microsoft/vscode#158553]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open the search widget and focus on the input box.

![image](https://user-images.githubusercontent.com/28700378/185555280-018a0aaa-b323-4cc3-8223-6dcf2f8c48bb.png)

2. Press `Esc`, `list.closeFind` is not triggered, it appears that `treeFindOpen` is `false` when the input box is focused.

**Comment by joaomoreno** [comment]
I can't reproduce this. Do you have any custom keyboard shortcuts set up?

**Comment by wenfangdu** [comment]
@joaomoreno Sorry, it actually conflicts with a shortcut from vscode-neovim, removing that one solved this.
