### ISSUE TITLE
Auto-JSDoc comments not working

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#15850]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14931

Expected: Typing `/**` auto completes JSDoc comment
Actual: Sadness
![image](https://cloud.githubusercontent.com/assets/762848/20508023/83fdbbd0-b013-11e6-87f6-d3c77c15daa2.png)

**Comment by alexandrudima** [comment]
@mousetraps Do you mean you'd like typing `/**` to result in:

```js
/**
 * @param a
 * @param b
 * @returns
 */
function multiply(a,b) {

}
```

i.e. The language pre-fills the doc comment block with information from the element being "doc-commented"?

**Comment by mousetraps** [comment]
@alexandrudima Yep! That's the expected behavior.

**Comment by alexandrudima** [comment]
I think there's an extension that does that from @stevencl . 

Since this would be language specific, it would need a call to a language smartness provider, so it cannot be done synchronously while typing.

Not sure if it could be done with completion items or if it would need a new type of provider.

fyi @mjbvz @jrieken

**Comment by stevencl** [comment]
If you are looking for an extension for this, https://marketplace.visualstudio.com/items?itemName=joelday.docthis is the one to use.

**Comment by mjbvz** [comment]
TSServer has a `docCommentTemplate` command that we may be able to leverage here

**Comment by mjbvz** [comment]
Should be in current insiders builds

**Comment by alexandrudima** [comment]
@mjbvz It is not a good idea to do it through keybindings. Doing it through keybindings has the following problems:
1. indefinite times: if the extension host is busy for whatever reason (e.g. another installed extension) there is no time guarantee until the extension host processes the message and executes the type.
2. the above point might lead to out of order situations where pressing Enter followed by quickly typing something else might result in the something else being typed first and the newline afterwards.

IMHO this should be implemented as I suggest in my above comment, via a language smartness provider of sorts where we can, in the UI thread, ensure "in-order" typing and timeliness.

**Comment by jrieken** [comment]
fyi @alexandrudima https://github.com/Microsoft/vscode/issues/20990

**Comment by alexandrudima** [comment]
Oh nice!
