### ISSUE TITLE
No Shell Integration or Decorations:  macOS // M1 // ZSH

### ISSUE THREAD

**Issue by kartzke** [microsoft/vscode#158594]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macOS Monterey 12.5.1 (21G83), Apple Silicon M1

I've been trying to get the new shell integration and decorations working, but to no avail.  Things I have tried:

1. Enabling Shell Integration and Decorations in VS Code preferences
2. Enabling it in my workspace settings.json (below)
3. [Manually installing](https://code.visualstudio.com/docs/terminal/shell-integration#_installation) in my `.zshrc` file, with both the provided shortcut snippet and with the actual shell integration path provided by `code --locate-shell-integration-path zsh`

```
settings.json:
  "terminal.integrated.shellIntegration.enabled": true,
  "terminal.integrated.shellIntegration.decorationsEnabled": "both"
}
```
But the integration and decorations never appear.  I've double checked that ZSH is set for the integrated shell in VSCode preferences.  And I have tried the following troubleshooting steps:

1. Disabling all extensions by launching `code --disable-extensions` from terminal 
2. Removing **everything** from `.zshrc` file
3. Only having this in the .zshrc file:  `[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"`
4. Disabling conda's prompt command, which adds the conda environment to the terminal line.  Added `{changeps1: False}` to the `.condarc` file

And I still can't get this feature working.  Any ideas on how to further troubleshoot this?  

FWIW, I was using this in my `.zshrc` file to decorate terminal and it works without issue in VS Code.  
```
setopt PROMPT_SUBST
export PROMPT='%{%F{243}%}%n %{%F{197}%}%2~ %{%F{39}%}$(parse_git_branch) %{%F{normal}%}$%{%f%} '
```

**Comment by Tyriar** [comment]
@kartzke I'm not sure what's happening here and don't have an M1 to test. You could try make a copy of the shell integration script from `code --locate-shell-integration-path zsh` into your home directory and then source that directly. That will let you tweak the script (eg. add a bunch of echo statements or enable set mode) to see what the issue is

**Comment by kartzke** [comment]
Thanks for the quick reply.  I got this sorted out... PEBCAK.  😅
