### ISSUE TITLE
Add more refined code action group separators

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#158515]
Looking into adding additional separators that are more common, so that all the additional refactorings are not just clumped under `More Acitons`

From comment:

I was wondering if you would consider adding 2 code action classes that are I think quite common:

* `refactor.inline` (Inline)
* `refactor.move` (Move)

This would be super valuable for the extension that I'm developing (P42 JavaScript Assistant), but I think also for other extensions. Afaik the TS language server also has `refactor.move` actions for example.

_Originally posted by @lgrammel in https://github.com/microsoft/vscode/issues/132109#issuecomment-1219538441_

**Comment by CsCherrYY** [comment]
Hey @justschen , the new code action widget looks great, and I really like the new code action grouping, I'm wondering if we can define custom code action groups besides the pre-defined groups.

![image](https://user-images.githubusercontent.com/45906942/186562323-0e5b81c1-463c-472e-8ac4-ce7e59e64b62.png)

you can see the java extension contributes a code action (in the light bulb) named "add Javadoc" and it's now under "More Actions..." menu. If we can define a new group like "Sources" via extension, it would be great and more clear that we can put this action in that group.

**Comment by matthewjamesadam** [comment]
We have an extension that publishes some code actions.  With the latest VSCode, our actions are grouped under 'More Actions...' which in our context is not ideal.  We would prefer to be able to define our own grouping for our actions (in extension parlance, I think this means to be able to create our own `CodeActionKind`).  Thanks!
