### ISSUE TITLE
It's very hard to use SCM gutter decoration with new comment button

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158521]
Related: https://github.com/microsoft/vscode/issues/158276, https://github.com/microsoft/vscode/issues/158299

![Recording 2022-08-18 at 11 12 31](https://user-images.githubusercontent.com/2193314/185465122-4e24fa51-d65a-4b70-8f67-b2aa1edd5d1f.gif)

Version: 1.71.0-insider (user setup)
Commit: f5c96e2db885f43fe1adb4a6ebbdfecf095430a8
Date: 2022-08-18T05:15:52.904Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

**Comment by alexr00** [comment]
I would love to understand why your "+" button is so wide. It should be a square.

![Recording 2022-08-19 at 09 37 45](https://user-images.githubusercontent.com/38270282/185568578-53861be8-ef36-4e10-9c50-4edcdd7c77e7.gif)

Looks like I missed ~1px of overlap. Will fix.

**Comment by alexr00** [comment]
Adjusted by 1px to remove the overlap. Let's see if that combined with the other gutter improvements from yester resolve you extra wide "+".

**Comment by Tyriar** [comment]
Overlap is improved, https://github.com/microsoft/vscode/issues/158276 is still an issue though
