### ISSUE TITLE
Directory navigation feature

### ISSUE THREAD

**Issue by nahushfcc** [Microsoft/vscode#15856]
- VSCode Version: 1.7.1
- OS Version: Ubuntu 14.04
  Is there any faster way to navigate the directory tree? I am working on a project with around 300 node_modules and everytime I need to search for one of the node_modules i need to expand the node_modules directory and manually scroll all the way to the required module. As my project goes on increasing this becomes more and more of a pain. Can there be a way to search a directory the way it works in Intellij? i.e. we focus on the directory tree and type the name of the directory we want to go to and intellij searches for and takes us to the corresponding directory. 
P.S I am aware of the `Ctrl+P` command which opens a file, but that doesn't seem to work so well with directories

**Comment by kaiwood** [comment]
Duplicate, can be found here: #10026
