### ISSUE TITLE
Disable or remove options in new file 

### ISSUE THREAD

**Issue by Johannes-Esseling** [microsoft/vscode#158551]
Hello everyone, 

When creating a new file in Visual Studio Code with the Python Extension installed, you will get prompted to create a Jupyter Notebook. However there's no way to disable this option. This has resulted in me pasting text into the "Select File Type..."-Dialog many times. 

As a user I don't want to spend time and an additional click making a selection here. I just want to create a plain text file. 

Existing issues that all referenced the issues (excerpt). 
https://github.com/microsoft/vscode/issues/103526
https://github.com/microsoft/vscode/issues/105661

The issue that was referenced as containing the solution: 
https://github.com/microsoft/vscode/issues/102289

**However** as far as my understanding of the issue, it only addresses the bug, but not the expected behavior: 
I have the python plugins installed + I don't want the "Select File Type..." Dialog to show up. 

Could please point me in the direction of resolving this, or open up a change request. 

Things I tried that didn't help disable the option:
``` 
"workbench.editor.defaultBinaryEditor": "default",
"files.defaultLanguage": "plaintext",
"python.dataScience.useNotebookEditor" : false,
"python.pylanceLspNotebooksEnabled": false,
"python.dataScience.sendSelectionToInteractiveWindow": false
```

Any help in this regard is appreciated.

**Comment by Johannes-Esseling** [comment]
For the people that are facing the same issue as me: 

Visual Studio Code has two ways to create new files: 
<img width="139" alt="image" src="https://user-images.githubusercontent.com/7209465/185555823-9bb41881-1e32-4c61-a81b-89cffadd1ff5.png">

On MacOS CMD + N always opened the "New  File..." - Dialog

To change this behavior I just changed the shortcut for the create new file. 
<img width="708" alt="image" src="https://user-images.githubusercontent.com/7209465/185556035-23bf4810-3470-4f03-9793-53c9d110d49a.png">

Create: New File ... (`welcome.showNewFileEntries`) 

Now the File: New Untitled File (`workbench.action. files.newUntitledFile`) is free and will be mapped to my default create shortcut. 

This has resolved the issue beautifully. 

The change request for changing the new file dialog can be closed.

**Comment by gjsjohnmurray** [comment]
:+1: @Johannes-Esseling please close the issue yourself.
