### ISSUE TITLE
Support `socks5h://` in http.proxy.

### ISSUE THREAD

**Issue by jmjoy** [microsoft/vscode#158669]
The environment variable `http_proxy` starts with `socks5h://` means resolve domain via proxy server.

But the setting `http.proxy` is only allow `socks5://` (`socks5h://` doesn't match the regex).

When `http_proxy` is setted starts with `socks5h://`, the network in vscode is not work.

Maybe support it?

**Comment by sky5454** [comment]
really important, dns hostname lookup through the socks5 proxy.

**Comment by chrmarti** [comment]
This is in the latest VS Code Insiders now (part of @vscode/proxy-agent 0.15.0). Would be great if you could give it a try and let us know if it works for you. Thanks!

**Comment by gerroon** [comment]
> This is in the latest VS Code Insiders now (part of @vscode/proxy-agent 0.15.0). Would be great if you could give it a try and let us know if it works for you. Thanks!

How do we use it? I need to use socks proxy in Code.

**Comment by qupig** [comment]
@chrmarti `socks5h` still seems to be unsupported and unless I use `socks5` I see errors in the network:
```
(failed) net::ERR_NO_SUPPORTED_PROXIES
```

The inability to properly support DNS via SOCKS5 is a headache.
