### ISSUE TITLE
Clicking File button on startup results in wrong menu showing up

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#158624]
On Windows 10:

1. Reload the window.
2. As soon as the titlebar loads in, click "File".
3. :bug: The File > Preferences menu shows up.

**Comment by sbatten** [comment]
@rzhao271 was this with the native or custom title bar?

**Comment by rzhao271** [comment]
This is with the custom titlebar

**Comment by sbatten** [comment]
This is because the menus are registered after the menu is shown. I don't think its something we can address reasonably
