### ISSUE TITLE
Not able to find modules/types for tsx files after recent updates.

### ISSUE THREAD

**Issue by harshil93** [Microsoft/vscode#15863]
- VSCode Version: 1.7.1
- OS Version: Windows
- Typescript version: 2.0.6
Steps to Reproduce:

1. We have a project for which VS code was working perfectly fine ( before some updates). Here is the tsconfig.json ( this is there just to support vscode, we a separate build system)
```
{
    "compilerOptions": {
        "module": "amd",
        "target": "es5",
        "jsx": "react"

    },
    "exclude": [
        "node_modules"
    ]

}
```

The project structure looks something like this

```
Foo/**
VSS/
        @types/**
         .....
tsconfig.json
```
VSS folder here is a hard link. 

2. I have two files in Foo i.e Temp.ts and Temp1.tsx . 
![image](https://cloud.githubusercontent.com/assets/1177554/20514131/4edf4656-b0b0-11e6-9953-787cebe64954.png)

Any hints on resolving this ? I can help you with more info if required. I cannot share the code since this is Microsoft Internal (VSTS), but we can have a skype session if you want.

Also any hints on debugging this on my own ?

**Comment by harshil93** [comment]
Related issue in Typescript https://github.com/Microsoft/TypeScript/issues/10346

**Comment by waderyan** [comment]
@harshil93 thanks for opening this issue. Sorry this seems to have fallen through the cracks on my end. I know you can't share the code but can you share a simplified repo where the problem exists? This will help us in diagnosing and debugging. 

Can you also try using the latest bits with the insiders build [here](https://code.visualstudio.com/insiders)?

**Comment by harshil93** [comment]
@waderyan Hi Wade, since you are in DEVDIV, you will have access to the source code at mseng.visualstudio.com I will mail you the details regarding project on mail and would probably have a machine for you to repro.

I will first try the insider bits and will then proceed with this.

**Comment by harshil93** [comment]
@waderyan Mailed you the details for the repro

**Comment by waderyan** [comment]
@harshil93 thanks. Can you confirm you tried with Insider bits and the problem exists? 

Also does the problem only exist with your current project setup? It would be most helpful (especially when handing off to TypeScript team) if we can narrow down the bug to a simpler scenario.

**Comment by harshil93** [comment]
@waderyan Yes, it is happening with insiders bits also on a fresh machine. I will try to narrow down to a simple scenario. I already have vscode source code and dev build setup. Any hints in debugging this on my own.

**Comment by harshil93** [comment]
[ReleasePipeline.zip](https://github.com/Microsoft/vscode/files/652245/ReleasePipeline.zip)

This project is the repro. The same code is there in temp.tsx and temp/ts

The error comes in tsx but not in ts.

P.S. - Open the folder which has tsconfig.json at its root.

**Comment by harshil93** [comment]
The solution was to include tsx in include files.
