### ISSUE TITLE
Symbolically linked folders are pathed differently in the File Browser verses Source Control

### ISSUE THREAD

**Issue by nightness** [microsoft/vscode#158637]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Stable and Insider
- OS Version: Ubuntu 20.14

Folders that have followed a symbol link (Linux, maybe other OS's) are treated differently in the File Explorer verse Source Control's 'Open File' button. The browser opens the symbolic path '~/src/project' (example) while source control uses the full 'true path', like /mnt/volume/source. It should just open one window, not two windows pointing to the same file.

Steps to Reproduce:

1. Create an empty folder
2. Create a symbolic link to that folder
3. Open the symbolic link in vscode
4. Initialize git with: git init
5. Add a file to the folder
6. Open the file in File Browser
7. Open the file via Source Control's open file.

**Comment by nightness** [comment]
Fixing this would probably fix 15 other bugs that seem related

**Comment by nightness** [comment]
Video showing steps 6 and 7... [YouTube](https://youtu.be/K2BUy9vPAoY)

**Comment by lramos15** [comment]
@lszomoru Do you have access to the relative path in the workspace through git? My guess is Git sees the actual tracked file as the full path

**Comment by MoyuScript** [comment]
This problem also lead to Git GUI (icon 'M', 'U' in explorer, etc.) disappeared in my computer (MacOS Monterey 12.5.1).

```
code ./project
```

<img width="889" alt="image" src="https://user-images.githubusercontent.com/45550579/187888206-07df43be-86a8-4fc4-8051-9e84971c7c8c.png">

```
ln -s ./project ./project-sym
code ./project-sym
```

<img width="920" alt="image" src="https://user-images.githubusercontent.com/45550579/187888394-c1ef6e4b-4f52-4098-8b70-19ba5daad0b6.png">

**Comment by lszomoru** [comment]
Thank you very much for filing this issue. This behaviour boils down to the fact that at the moment the git extension  does not support repositories that have a symbolic link on their path. Adding this capability is tracking in [this issue](https://github.com/microsoft/vscode/issues/5970). Please subscribe to the issue to get updates. I will close this issue as a duplicate.
