### ISSUE TITLE
Editor Playground Multi-Cursor crash

### ISSUE THREAD

**Issue by petertill** [microsoft/vscode#158691]
Type: <b>Bug</b>

Visual Studio and your machine will be crashed when using the multi-cursor feature without any text selected.

1. Open Interactive Editor Playground
2. Click at the end of any line (do not select anything)
3. Press Shift+Alt+DownArrow
4. Visual Studio Code and your machine will be crashed

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:26.145Z)
OS version: Linux arm64 5.15.56-v8+
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|unknown (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 1, 0|
|Memory (System)|3.71GB (1.44GB free)|
|Process Argv|--unity-launch --crash-reporter-id f5e27c8c-c716-47f5-aa8c-09a297f7261e|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|LXDE-pi|
|XDG_CURRENT_DESKTOP|LXDE|
|XDG_SESSION_DESKTOP|lightdm-xsession|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
captain-stack|cap|0.0.6
vscode-plugin|cod|0.6.4
vscode-pull-request-github|Git|0.48.1
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
java|red|1.9.0
tabnine-vscode|Tab|3.6.12
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0
php-debug|xde|1.27.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by chrmarti** [comment]
Cannot reproduce on Ubuntu 20.04 arm64. Does this also happen when you disable all extensions? (See https://github.com/Microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)

**Comment by petertill** [comment]
Yes, the problem is present anyway. I personally use a Raspberry pi with the latest raspbian (64-bit, desktop) system. Is it possible that it is causing the problem? If necessary, I can send you a screen recording.

**Comment by petertill** [comment]
Update: Apparently, the latest linux system/package update has solved the problem.
