### ISSUE TITLE
Sudden crash while coding in VS code editor

### ISSUE THREAD

**Issue by PriyanshuMallick** [microsoft/vscode#158677]
Type: <b>Bug</b>

While coding a simple JS file for test website VS code is behaving very slug-ish and is crashing own its own. I have live server running to live preview the website in FireFox and its also displaying me alert that "The current website is making FireFox slow do you want to close the website or wait"(paraphrased). Even while writing this issue VS code went and recoved from "Not Responding" 3 times. 
It started from today, I didn't have any issue yesterday or the day before.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600X 6-Core Processor              (12 x 3693)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.02GB free)|
|Process Argv|--crash-reporter-id 21df86d5-0880-4ecf-b871-c7a0b6ffd1c8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.5.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
live-sass|gle|5.5.1
vscode-auto-open-markdown-preview|hnw|0.0.4
blender-development|Jac|0.0.17
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
cpptools|ms-|1.12.1
java|red|1.9.0
LiveServer|rit|5.7.5
sass-indented|syl|1.8.22
tabnine-vscode|Tab|3.6.12
ayu|tea|1.0.5
intellicode-api-usage-examples|Vis|0.2.1
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by andreamah** [comment]
It seems that you have the third-party live server running, which is supported [elsewhere](https://github.com/ritwickdey/vscode-live-server). 

However, we have our own first-party extension that can also preview web files similarly called [Live Preview](http://aka.ms/live-preview) that we can help you out with a little more if you run into bugs! 🙂
