### ISSUE TITLE
Quick Open "Ctrl + P" not working

### ISSUE THREAD

**Issue by JuanCarlosV** [microsoft/vscode#158613]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Bug</b>

Quick open is not working, I have the shortcut listed in my default keybindings  but its not working. 

I've been googling for solutions all leading to erase USER keybinding.json.
I've tried editing default kb json file but its read only

any suggestions?

thanks in advance.
JC

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Remote OS version: Linux x64 4.19.104-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.14GB free)|
|Process Argv|--crash-reporter-id 76f6bf63-5a5d-4390-b8c9-6136cd88910a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.104-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|Memory (System)|7.71GB (5.69GB free)|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.245.1
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-django|bat|1.10.0
gitlens|eam|12.1.2
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
java|red|1.9.0
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by gjsjohnmurray** [comment]
Two suggestions:

1. Use the `Start Extension Bisect` command to see if one of your extensions is causing this.
2. Follow the steps at https://github.com/microsoft/vscode/wiki/Keybinding-Issues

**Comment by JuanCarlosV** [comment]
@gjsjohnmurray bisect didn't find any problems although the problem was fixed. thank you.
