### ISSUE TITLE
alt+shift+f   can't format css file

### ISSUE THREAD

**Issue by herrdu** [Microsoft/vscode#15860]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular-material-snippets|4tron|0.3.1|
|beautify|HookyQR|0.5.5|
|theme-dreamweaverweb|Persephona|1.5.4|
|html-snippets|abusaidm|0.0.18|
|angular2-snippets|danwahlin|1.0.5|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.0|
|theme-dracula|dracula-theme|1.2.5|
|theme-etinum|euntaik|0.1.3|
|theme-jo-light|ivanzusko|0.0.1|
|RelativePath|jakob101|0.11.0|
|docthis|joelday|0.3.5|
|vscode-csscomb|mrmlnc|3.2.4|
|Theme-1337|ms-vscode|0.1.2|
|language-stylus|sysoev|1.6.0|
|vscode-react-native|vsmobile|0.2.2|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by jrieken** [comment]
Do you see `Format` in the context menu?

**Comment by jrieken** [comment]
Closing because not enough information has been provided.
