### ISSUE TITLE
Can't commit without writing a message.

### ISSUE THREAD

**Issue by Jaideep25** [microsoft/vscode#158698]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: 22000.856

Steps to Reproduce:

1. When we try to commit a file without writing a message, the source control gets hanged.
2. Which makes the source control unusable, & we need to restart VS Code.

I'm having a solution for it,
Either we can create an additional dialog box, & ask the user to type up a message, or we can create a default message, which shall be committed.

Thanks!
Regards,
Jaideep.

**Comment by lszomoru** [comment]
When you attempt to commit without specifying a commit message, a new editor tab will open and you can use the power of a full editor to author the commit message. This behaviour is described in details in [the release notes](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor). You can disable this capability by toggling the `git.useEditorAsCommitInput` setting.
