### ISSUE TITLE
git bash displays wrong input characters

### ISSUE THREAD

**Issue by NiuZhuang** [Microsoft/vscode#15869]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Set git bash as default terminal:
    File -> Preferences -> User Settings, add 
        "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
    at settings.json.
2. Open git bash by Ctrl + `.
3. Type some characters wrapped with ""

Expected:
 "123123123123"
Result: 
"12312"3123"123"

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/14613

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.
