### ISSUE TITLE
Mode for F7 diff to scroll

### ISSUE THREAD

**Issue by funnym0nk3y** [microsoft/vscode#158619]
Using the compare mode and then using the command `go to next difference` opens a different kind of diff view (not side by side, just three liness above and below).
![grafik](https://user-images.githubusercontent.com/41870754/185685545-e1f737a6-0ebd-4734-9c6c-1036488fd7cc.png)
This makes it difficult to get a good overview. 
On the other hand jumping from difference to difference in a large, mostly unchanged file would benefit from a command, which instead of opening that restricted diff view, would just scroll the editor to that line.

**Comment by alexdima** [comment]
We have such commands! You can try out the following rules in your `keybindings.json`:
```
// navigate through diffs
{ "key": "f10",       "command": "workbench.action.editor.nextChange",
                         "when": "!inDebugMode && editorTextFocus" },
{ "key": "shift+f10", "command": "workbench.action.editor.previousChange",
                         "when": "!inDebugMode && editorTextFocus" },
{ "key": "f10",       "command": "workbench.action.compareEditor.nextChange",
                         "when": "textCompareEditorVisible" },
{ "key": "shift+f10", "command": "workbench.action.compareEditor.previousChange",
                         "when": "textCompareEditorVisible" },
```

The command you executed, `editor.action.diffReview.next` enters a mode especially created for Screen Reader users, which allows screen readers to read out the diff hunks in a format similar to the one present on the command line.
