### ISSUE TITLE
Terminal: Select Default Profile fails to locate Git Bash and include as dropdown option

### ISSUE THREAD

**Issue by arwhyte** [microsoft/vscode#158627]
Does this issue occur when all extensions are disabled?: Python extension not disabled in order to test workaround.

- VS Code Version: 1.70.2
- OS Version: Windows 11 Home version 21H2 OS build 22000.856 Windows Feature Experience Pack 1000.22000.856.0

Steps to Reproduce:

1. Install gitforwindows (git version 2.37.2.windows.2)
2. CTL-SHIFT-P to activate the control palette
3. Select Terminal: Select Default Profile
4. Git Bash is not listed in dropdown
5. File > Preferences > Settings > terminal.integrated.profile.windows
6. Git Bash "source" is listed but is ignored.

```json
"Git Bash": {
    "source": "Git Bash"
}
```

Issue discussed on stackoverflow: https://stackoverflow.com/questions/68068359/gitbash-not-showing-up-as-a-terminal-option-in-visual-studio-code

Workaround:

I replaced the key-value pair above with the following key-value pair (note that the path could vary if a different git for windows install location was chosen):

```json
"GitBash": {
    "path": [
        "C:\\Program Files (x86)\\Git\\bin\\bash.exe"
    ],
    "args": [],
    "icon": "terminal-bash"
}
```

Restarted VS Code, activated the command palette, selected Terminal: Select Default Profile and Git Bash appeared as a dropdown option.  Selected Git Bash as the default terminal.  Ran python file.  Terminal pane opened Git Bash and code executed successfully.

Context: I teach at the University of Michigan School of Information and we use VS Code to introduce students to programming fundamentals.  For new students this is a non-trivial workaround. Class starts in a week. :)

**Comment by arwhyte** [comment]
Issue also reported here: https://github.com/microsoft/vscode/issues/126023

**Comment by meganrogge** [comment]
Thanks for the issue. Perhaps we should be showing a warning when `Git Bash` is not detected at the standard paths we check with instructions or a shortcut to configure it. Thoughts @Tyriar ?

/duplicate #https://github.com/microsoft/vscode/issues/126023
