### ISSUE TITLE
`--prof-startup` paths are slightly off

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#158646]
<img width="242" alt="image" src="https://user-images.githubusercontent.com/900690/185730562-6fe85d56-19c8-4039-bf0a-8f448da296d3.png">

In above, there seems to be `~` prefixed to the absolute path?

**Comment by jrieken** [comment]
@bpasero Uses your(?) label service: https://github.com/microsoft/vscode/blob/78224b9b9e9cb7bfe2ef65697bccfe46750dd080/src/vs/workbench/contrib/performance/electron-sandbox/startupProfiler.ts#L79

**Comment by bpasero** [comment]
@jrieken quickly debugged this and it seems the call to `joinPath(dir, cur)` results in paths such as `/Users/bpasero/Users/bpasero/prof-OkouwKIO.extHost.cpuprofile`, so the label service is actually doing the right thing. 

Maybe a while ago the code before returned just the file name and now it returns the full path so the joining is not needed anymore?

**Comment by bpasero** [comment]
From https://github.com/microsoft/vscode/commit/78224b9b9e9cb7bfe2ef65697bccfe46750dd080#diff-dd7d7d6a2e81d2b3981bb54cde89646b99b21f82b3fec913a24b5085529abc96L73

When replacing `fs.readdir` with `IFileService.resolve` note that the former returns the names of the entries of the folder but the latter returns the full resource.

**Comment by bpasero** [comment]
I think https://github.com/microsoft/vscode/pull/159410 addresses this and also related issues, such as revealing the files on the native explorer and putting the right names into the issue when reported.
