### ISSUE TITLE
not write string

### ISSUE THREAD

**Issue by anchai** [microsoft/vscode#158693]
I can't write stirng 's' 
buy i can write shift+s

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `s`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by anchai** [comment]
I done ,got it
I config add Device Emulator Key fig string s and cancel config
I thank you

ในวันที่ อ. 23 ส.ค. 2022 เวลา 01:31 Alexandru Dima ***@***.***>
เขียนว่า:
