### ISSUE TITLE
configurationDoneRequest never called

### ISSUE THREAD

**Issue by APerricone** [microsoft/vscode#158687]
Type: <b>Bug</b>

With latest version of VSCode [my extension](https://github.com/APerricone/harbourCodeExtension) has some issue with debugger, the application starts but de debugger is unresponsive.
I tryied to debug my extension, and the sequence is:
```
> 1 - C initialize - {"clientID":"vscode","clientName":"Visual Studio C
< 1 - C initialize - {"supportsConfigurationDoneRequest":true,"supports
> 2 - C launch - {"type":"harbour-dbg","request":"launch","name":"L
< 2 - C launch - no-body
< 3 - E initialized - no-body
> 3 - C setBreakpoints - {"source":{"name":"minimal.prg","path":"d:\\Docume
< 4 - C setBreakpoints - {"breakpoints":[{"verified":true,"line":7},{"verif
> 4 - C setExceptionBreakpoints - {"filters":["notSeq"]}
< 5 - C setExceptionBreakpoints - no-body
< 6 - E stopped - {"reason":"step","threadId":1}
```
What I notice is that "configurationDone" is absent.
So the debugger does not works anymore..

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx   (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.90GB (0.89GB free)|
|Process Argv|--crash-reporter-id 16bc8c7e-027f-4165-8229-92f97b9f44b4|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
harbour|ape|1.0.3
regexper-unofficial|ape|0.0.3
doxdocgen|csc|1.4.0
typescript-notebook|don|2.0.6
vscode-npm-script|eg2|0.3.28
better-cpp-syntax|jef|1.15.19
vscode-language-pack-it|MS-|1.70.8170916
csharp|ms-|1.25.0
vscode-edge-devtools|ms-|2.1.0
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.245.1
remote-ssh|ms-|0.84.0
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.5
cpptools-extension-pack|ms-|1.2.0
hexeditor|ms-|1.9.8
notepadplusplus-keybindings|ms-|1.0.7
vscode-yaml|red|1.9.1
LiveServer|rit|5.7.5
cmake|twx|0.0.17
unity-debug|Uni|3.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by weinand** [comment]
@APerricone I cannot reproduce this in VS Code 1.70.2.
In Mock Debug `configurationDoneRequest()` is called just fine:

<img width="1845" alt="CleanShot 2022-08-21 at 19 15 17@2x" src="https://user-images.githubusercontent.com/1898161/185802994-583c1827-1ab1-48e4-87ea-c40744c3235b.png">

Make sure to have the corresponding capability set:

<img width="714" alt="CleanShot 2022-08-21 at 19 17 19@2x" src="https://user-images.githubusercontent.com/1898161/185803043-6a3b4769-e9fe-4704-8dff-ef951445fb66.png">

**Comment by APerricone** [comment]
sure supportConfigurationDoneRequest is setted fine, it is on [this line]( https://github.com/APerricone/harbourCodeExtension/blob/dbd79a8bc80858f1b0fc1dcca849529448647fc5/client/src/debugger.js#L129)
Is the sequence of request and event correct?

**Comment by weinand** [comment]
What's the purpose of the second `setExceptionBreakpoints - no-body` in your sequence above?

**Comment by APerricone** [comment]
I added AdapterTracker as explained on [https://code.visualstudio.com/updates/v1_30](https://code.visualstudio.com/updates/v1_30#:~:text=Finalized%20Debug%20Adapter%20Tracker%20API)

in this line https://github.com/APerricone/harbourCodeExtension/blob/dbd79a8bc80858f1b0fc1dcca849529448647fc5/client/src/extension.js#L45

**Comment by APerricone** [comment]
I just tried to remove createDebugAdapterTracker and looks the debugger works again, is it the expected behavior?

**Comment by APerricone** [comment]
ok, the problem was my Adapter Tracker:
![image](https://user-images.githubusercontent.com/22457168/185834691-48bdc77c-3515-4957-9dc3-12d698e279b3.png)

Close this issue

**Comment by weinand** [comment]
@APerricone great that could you find the problem.
