### ISSUE TITLE
Add setting to disable ALL formatting on save

### ISSUE THREAD

**Issue by nathanrpage97** [microsoft/vscode#158675]
## Description

When working on third party repos that do not use formatting tools, it is important that the git diffs are kept as small as possible. But when I use vscode some form of auto-formatting will be done on save.

`editor.formatOnSave: false` is not enough to prevent this:
- Certain plugins may ignore this value
- Is commonly overridden in language specific settings:
   ```json
   "[python]": {
        "editor.formatOnSave": true
    }
   ```
- Certain vscode features ignore this setting: 
   - `editor.trimAutoWhitespace"`
   - `"editor.insertSpaces"`

## Current workaround

Always run the `save without formatting` command or its equivalent keyboard shortcut.

## Proposed Solution

Vscode add an option to disable any and all formatting on save? Something along the lines of:

`editor.forceSaveWithoutFormatting`

that will make the default save operation use the save without formatting method.

**Comment by jrieken** [comment]
This is a problem of how language-specific overrides work.

**Comment by sandy081** [comment]
This is as per design for Lang specific overrides.

**Comment by nathanrpage97** [comment]
Ok, any other pointers to make this easier? I can’t do per project keybindings. An extension seems a bit overkill and unsure if it would even be possible to change such a low level operation.
