### ISSUE TITLE
C_Cpp.clang_format_style: IndentWidth is invaild

### ISSUE THREAD

**Issue by yayuntian** [Microsoft/vscode#15866]
- VSCode Version:1.7.1
- OS Version:windows 10 1607

Steps to Reproduce:

1. install c/c++ plugins
2. edit settings.json

`
{
    "C_Cpp.clang_format_style": "{BasedOnStyle: Google, IndentWidth: 4}"
}`

but c/c++ code indentwidth always display 2

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-cpptools#360
