### ISSUE TITLE
Cannot set a breakpoint on a child file - instead debugs "read-only inlined content from source map"

### ISSUE THREAD

**Issue by kevjames3** [Microsoft/vscode#15861]
Sup?  So I am trying to debug files in Typescript and I am ok, but I am having difficulty setting a breakpoint on a file that is inside a folder.  However, if I step into the function from `main.ts`, it shows the file with the message "read-only inlined content from source map".  I would like to figure out what I did wrong or if it is not supported to be able to go to a lower file directly yet.  

- VSCode Version: 1.7.1
- OS Version: OSX 10.12.1 (macOS Sierra)

Steps to Reproduce:
-----
**package.json**
```json
    "babel-preset-es2015": "^6.18.0",
    "babelify": "^7.3.0",
    "browserify": "^13.1.1",
    "gulp": "^3.9.1",
    "gulp-sourcemaps": "^2.2.0",
    "gulp-typescript": "^3.1.3",
    "tsify": "^2.0.2",
    "typescript": "^2.0.9",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
```

**Layout**
```
dest
 \ main.js
 \ common
    \ sorting.js
src
  \ main.ts
  \ common
     \ sorting.ts 
node_modules (etc)
```

**tsconfig.json**
```json
{
    "files": [
        "src/**/*.ts"
    ],
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "rootDir": "./src",
        "sourceMap": true,
        "preserveConstEnums": true
    },
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
}
```

**Main.ts**
```typescript
import Sort from './common/sorting';

let anArray:Array<number> = [];

for(let i:number = 0; i < 10; i++){
    anArray.push(Math.floor(Math.random() * 100));
} 
let newArray = Sort.MergeSort(anArray, (a: number, b: number) => {return a - b});

console.log("Old Array: " + anArray);
console.log("New Array: " + newArray); 
```

**sorting.ts**
```typescript
type Comparitor<F> = (a: F, b: F) => number;
export default class Sort {    
    public static MergeSort<T>(input:T[], comparitor:Comparitor<T>) : T[] {        
        return input;
    }
}
```

**Launch.json**
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/src/main.ts",
            "cwd": "${workspaceRoot}/src",
            "outFiles": ["${workspaceRoot}/dest/**/*.js"],
            "sourceMaps": true
        }
    ]
}
```

**Gulp** (know you guys don't support, but figure I should put it here just incase)
```javascript
var gulp = require("gulp");
var ts = require("gulp-typescript");
var sourcemaps = require('gulp-sourcemaps');
var tsProject = ts.createProject("tsconfig.json");

gulp.task("default", function () {
    var tsResult = tsProject.src()
        .pipe(sourcemaps.init())
        .pipe(tsProject())

    return tsResult.js
        .pipe(sourcemaps.write({sourceRoot: '../src'})) 
        .pipe(gulp.dest('dest'));
});

gulp.task('watch', ['default'], function() {
    gulp.watch('src/**/*.ts', ['default']);
});
```

**Screenshots**
Before trying to step into the function...
![screen shot 2016-11-21 at 10 41 32 pm](https://cloud.githubusercontent.com/assets/440138/20513588/baf60b7e-b03b-11e6-9426-979c69c32aca.png)

After trying to step into the function...
![screen shot 2016-11-21 at 10 41 42 pm](https://cloud.githubusercontent.com/assets/440138/20513593/c64db94a-b03b-11e6-974b-0b8da24f3f1e.png)

**Comment by kevjames3** [comment]
FYI - I simplified the "MergeSort.ts" function as I found this issue while I was attempting to debug.  The screenshot with the message "read-only inlined content from source map" is here: 
![screen shot 2016-11-21 at 10 46 22 pm](https://cloud.githubusercontent.com/assets/440138/20513665/5453a542-b03c-11e6-9e4a-fa1c56d9abc6.png)

I just figured I would simplify it so code would not take up most of the issue page

**Comment by isidorn** [comment]
Please clarify something for me, the title says that you can not set any breakpoints but in the steps you do not mention anything about breakpoints?
Do you see a red circle hover when you go over the glyph margin? Does the breakpoint appear as unverified? What is exactly wrong with the breakpoint?

As for the step in that seems like expected behavior to me? You just stepped in the inlined content from a source map as the title says. If you step out and step in again you might step in to where you expect

**Comment by kevjames3** [comment]
@isidorn that is fair, let me elaborate.

I have taken the liberty of [creating a branch](https://github.com/kevjames3/TypeScript_Learning/tree/VSCode_Debugging) in my repository so you are able to debug it directly if you wish.  See README.md for setup.

The entry point to my code is `main.ts`.  I set a breakpoint in `common/sorting.ts` at line 30, specifically the line `if(input.length == 0){`.  Example below:

```typescript
if(input.length == 0){
    return input;
}
let middle = Math.floor(input.length/2);
let sortA = Sort.MergeSort(input.slice(0, middle), comparitor);
let sortB = Sort.MergeSort(input.slice(middle, input.length), comparitor);
return Merge(sortA, sortB);
```

When running the configuration "Launch Program", I get a stackoverflow (due to my bad QuickSort alg), and the breakpoint is not hit.  I then put a breakpoint on `main.ts` at line 9, specifically the line `let newArray = Sort.MergeSort(anArray, (a: number, b: number) => {return a - b});`.  Example below:

```typescript
//Sort.QuickSort(anArray, (a: number, b: number) => {return a - b});
let newArray = Sort.MergeSort(anArray, (a: number, b: number) => {return a - b});

console.log("Old Array: " + anArray);
console.log("New Array: " + newArray); 
```

I then run "Launch Program" again and the breakpoint is hit in `main.ts`.  In debugging further, I step into line 9 on `main.ts`.  I then get `sorting.ts`, but not the file I wrote - instead it is a file that is a duplicate but instead with the line "read-only inlined content from source map"

![screen shot 2016-11-22 at 9 39 37 am](https://cloud.githubusercontent.com/assets/440138/20534806/696aa75e-b097-11e6-9651-3d0ee30a5d64.png)

**Expected Behavior**
I instead would like to be able to debug the file by setting a breakpoint on a file that I wrote instead of having to write the `debugger` keyword in order to trigger a breakpoint.  I have checked and my inline-source maps do look correct, but I could be mistaken.

**Comment by isidorn** [comment]
@kevjames3 thanks for more details - though being concise would also be great. 
Forwarding to @weinand as this behavior is handled by the node debug adapter

**Comment by kevjames3** [comment]
@isidorn fair enough, will try to consolidate my comments next time

**Comment by kevjames3** [comment]
@weinand any word on this one?

**Comment by kevjames3** [comment]
Issue solved, problem was in using gulp-sourcemaps, thus the issue was not with VSCode.

More info: stackoverflow link: http://stackoverflow.com/questions/34218374/vscode-breakpoint-not-working-in-typescript-with-sourcemap-generated-by-gulp-sou

The issue was that when I was writing my source maps, I was not setting the source root correctly.

```javascript
.pipe(sourcemaps.write({sourceRoot: '../src'})) 
```

should have been 

```javascript
sourceRoot: function(file){ 
   return file.cwd + '/src'; }
}
```

as the source root needs to be resolved differently for each file.
