### ISSUE TITLE
Git Hub Preview Timing out

### ISSUE THREAD

**Issue by WillWilliams1010** [microsoft/vscode#158680]
I run the Finance app (Lesson 9) using 'flask run'. I get the link. I CTRL-click on it, and I wait and wait.... then it says it timed out. 

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by gcsiapn** [comment]
me too

**Comment by gjsjohnmurray** [comment]
Please report this to the course admin people, not to the people who produce one of the tools you are using on your course.
