### ISSUE TITLE
No separation between item details in command pallet when using Voice Over

### ISSUE THREAD

**Issue by mikolysz** [microsoft/vscode#158633]
Type: <b>Bug</b>

1. Turn On Voice Over with Command + f5
2. Press Command+Shift+P
3. Type "keyboard shortcuts" and select "Open Keyboard Shortcuts preferences". You can use any other command, this is just an example.
4. Dismiss the dialog that appears.
5. Press Command + Shift + p, and Voice Over will say: "Preferences: Open Keyboard Shortcuts⌘K⌘Srecently used selected". Notice that there's no separator, not even a space, between the command name, the shortcut and the 'recently used" annotation. As a result, Voice Over will say "Command K Command srecently used" instead of "Command K, Command s, recently used". The s won't be spelled out, but pronounced as if it was part of the word "recently".
6. A similar story occurs with other commands, for example, "Go to DefinitionF12 selected" is pronounced in. way where the "F" from "F12" is part of the word "Definition".

This might be related to #133649, but it occurs for all items, not just the first, so not sure.

VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin arm64 21.5.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 0a0a4d05-10b5-444e-817f-e34805adc4dd|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gotemplate|cas|0.4.0
copilot|Git|1.42.6544
go|gol|0.35.2
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.245.1
java|red|1.9.0
indent-nav|Ton|1.0.3
vscodeintellicode|Vis|1.2.22
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012cf:30540253
azure-dev_surveyone:30548225

```

</details>

**Comment by isidorn** [comment]
Thanks for filling this issue but it is upstream. Dup of https://github.com/microsoft/vscode/issues/133649
