### ISSUE TITLE
Diff Doesn't Show Changes for New Line Characters

### ISSUE THREAD

**Issue by sprinkle131313** [Microsoft/vscode#15864]
Initialize a new Git repo, commit a file with some text. Change the line endings to something else and save. It will show that the file was modified but will not show the lines that have changed.

![change](https://cloud.githubusercontent.com/assets/8701667/20514769/ef5baad4-b05b-11e6-8617-0778f85b596f.png)

**Comment by jrieken** [comment]
You can control that with the `"diffEditor.ignoreTrimWhitespace"`-setting
