### ISSUE TITLE
Inconsistent display of bare indented code blocks and fenced code blocks (```) in Markdown preview

### ISSUE THREAD

**Issue by studyingegret** [microsoft/vscode#158682]
Type: <b>Bug</b>

Steps to reproduce:

1. Open a Markdown editor.
2. Enter the following code:
   `````

       [short|long] [signed|unsigned] int
       [signed|unsigned] char
       float
       [long] double

   ```
   [short|long] [signed|unsigned] int
   [signed|unsigned] char
   float
   [long] double
   ```
   `````
3. Preview the Markdown, for example by clicking the "Open Preview to the Side" button.

Expected behavior: The two code blocks are rendered the same.

Actual behavior: The two code blocks are rendered with slightly different margins and line heights:

![Screenshot](https://user-images.githubusercontent.com/110317665/185771695-e91d55db-9714-456e-ac0d-adb64fbd3277.png)

Does this issue occur when all extensions are disabled?: Yes

VS Code version: Code - Insiders 1.71.0-insider (28f604dec81b609dd7e69362585f7a99d4c48f88, 2022-08-19T05:17:14.894Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.90GB (0.46GB free)|
|Process Argv|--crash-reporter-id adc3af8c-0978-48bc-aa94-fbd604e9e143|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by weartist** [comment]
I will try to solve this problem immediately

**Comment by weartist** [comment]
![image](https://user-images.githubusercontent.com/17105034/185980197-c21d0d79-7bb5-440e-be4d-712268b3017e.png)

@mjbvz It looks like the spacing between <code> and <div> is different due to them using different layers, for this case, should we both use <code><div>xxx</div><code>?

**Comment by philecker** [comment]
Is this issue still available? I'd like to fix it, but I have never contributed to an open source project before. Are there any instructions I can follow to submit a PR for this issue?

**Comment by JordyVlassembrouck** [comment]
@weartist, I would use <code> xxx </code> for 2 reasons:
- I don't see a reason why there should be a <div> between the <code> tags
- the styling looks better when only using the <code> tags

**Comment by gauthampkrishnan** [comment]
Hi I can give it a try if someone can guide me like where should I start to solve this issue.

**Comment by studyingegret** [comment]
@weartist No, it's actually `<pre [source line info]><code>...</code></pre>` vs. `<pre><code [source line info]><code><div>...</div></code></code></pre>`

I observed that the first structure doesn't show a side marker when hovered, while the second one does:


https://user-images.githubusercontent.com/110317665/188794638-25856812-3b52-40d6-b26a-7f95c0d0a0a3.mp4

**Comment by studyingegret** [comment]
I found the bug in the source code: 

https://github.com/microsoft/vscode/blob/7b5e82ebcfaa165b1446ae81df19f71c9ea821d7/extensions/markdown-language-features/src/markdownEngine.ts#L413

and

https://github.com/microsoft/vscode/blob/7b5e82ebcfaa165b1446ae81df19f71c9ea821d7/extensions/markdown-language-features/src/markdownEngine.ts#L409

But the problem about the border also needs to be solved.

It is added by `.code-line`, which is inconsistently set on the `<pre>` (for indented code) and the `<code>` (for fenced code). The latter works because it lies inside the `<pre>`, and setting it on the `<pre>` causes it to be squeezed out of place:

![Screenshot](https://user-images.githubusercontent.com/110317665/189462427-f6d8c35d-c14a-424f-9414-b2a7857ba01b.png)

So in my opinion, we can use `<pre><code></code></pre>` for both, but we need to set the `.code-line` (and line info) on the inner `<code>` for both.

**Comment by studyingegret** [comment]
Here's the code that sets the properties:

https://github.com/microsoft/vscode/blob/7b5e82ebcfaa165b1446ae81df19f71c9ea821d7/extensions/markdown-language-features/src/markdownEngine.ts#L24-L34

I wonder if it's a bug of Markdown-it...

**Comment by StephenChips** [comment]
@studyingegret Don't understand why we need a scrollbar-like element aside the fenced code, can somebody explain it?

**Comment by StephenChips** [comment]
@studyingegret Don't understand why we need a scrollbar-like element next to the fenced code, can somebody explain it?

**Comment by Chanmoro** [comment]
I tried to fix this bug by overriding default rule of code_block.
This makes the rendered DOM of code_block and fence are same.

``` diff
--- a/extensions/markdown-language-features/src/markdownEngine.ts
+++ b/extensions/markdown-language-features/src/markdownEngine.ts
@@ -38,6 +38,10 @@ const pluginSourceMap: MarkdownIt.PluginSimple = (md): void => {
                        originalHtmlBlockRenderer(tokens, idx, options, env, self)
                );
        }
+
+       if (md.renderer.rules['code_block'] && md.renderer.rules['fence']) {
+               md.renderer.rules['code_block'] = md.renderer.rules['fence'];
+       }
 };
```

Render rule is defined at markdown-it and rule of code_block and fence are differ.
It causes make difference of rendered DOM between these.


- code_block
https://github.com/markdown-it/markdown-it/blob/2b6cac25823af011ff3bc7628bc9b06e483c5a08/lib/renderer.js#L30-L36

- fence
https://github.com/markdown-it/markdown-it/blob/2b6cac25823af011ff3bc7628bc9b06e483c5a08/lib/renderer.js#L39-L90

**Comment by studyingegret** [comment]
@Chanmoro Are you thinking of fileing an issue against Markdown-it?

**Comment by nkumawat34** [comment]
Can I work on this issue?

**Comment by studyingegret** [comment]
Alright, I am okay to accept this, personally I'm not going to have time to work on this in the forseeable future anyway 😂 But I'll put my work here if I make any
