### ISSUE TITLE
conflict highlights no longer have resolution options

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode#158674]
Type: <b>Bug</b>

1. Turn off the new merge editor
2. Create a merge conflict (e.g. with git rebase) 
3. Open a conflict file and navigate to a conflict.

Expected:
A. Current and Incoming portions are highlighted
B. A clickable resolution option is available (Accept Current; Accept Incoming; Accept Both)

Actual:
A. Same
B. Button is no longer present.

Please bring back the old merge functionality as an option for those who find the new 3-panel experience less efficient.

screenshot:
![image](https://user-images.githubusercontent.com/49081806/185756868-5aae84da-29f5-40a6-9ea6-4c2387c46537.png)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (4.43GB free)|
|Process Argv|--crash-reporter-id 142d2241-6057-4ccc-84bd-36797d6a7081|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
unique-lines|bib|1.0.0
markdown-mermaid|bie|1.14.3
markdown-preview-github-styles|bie|1.0.1
sarif-viewer-fix|br4|3.1.7
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.47.0
vscode-codeql|Git|1.6.10
vscode-test-explorer|hbe|2.21.1
cmake-language-support-vscode|jos|0.0.4
git-graph|mhu|1.30.0
wavework|Mic|1.2022.620008
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.5
hexeditor|ms-|1.9.8
test-adapter-converter|ms-|0.1.6
hide-gitignored|npx|1.1.0
vscode-text-tables|Rom|0.1.5
rewrap|stk|1.16.3
markdowntable|Tak|0.10.1
vscode-mermaid-editor|tom|0.15.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.3
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyonecf:30548226

```

</details>

**Comment by gjsjohnmurray** [comment]
Does it help to set `"diffEditor.codeLens": true`?

**Comment by brothatru** [comment]
@bradlitterell Same here, this has been driving me crazy, thought i was the only one.

@gjsjohnmurray I just tried updating my settings with that, but unfortunately it didn't help.

<img width="964" alt="Screen Shot 2022-08-20 at 9 54 31 PM" src="https://user-images.githubusercontent.com/898744/185776169-39b5cd77-dd3b-4d2e-91d4-2c8f4c91464a.png">


**Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0**

**Comment by usahai** [comment]
Seconded. The old system made it very clear where the bugs were, and the methods provided to resolve the conflicts were also very solid. This new method seems to be locked onto either merging it from left or right. I enjoyed the freedom to copy from the left and paste it to the right in the color-coded system.

**Comment by EmilNordling** [comment]
> Does it help to set `"diffEditor.codeLens": true`?

![image](https://user-images.githubusercontent.com/8842821/185925665-5e6d0321-c7a6-4576-a601-eb824b9252bf.png)

It remains the same 😔

**Comment by RalfJung** [comment]
For me, git conflict handling seems to have been broken entirely. There are not even conflict highlights any more. The [documentation](https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts) still describes things the way they used to be so maybe this is just a bug?

**Comment by RalfJung** [comment]
Oh, I am supposed to go to some *other* tab on the left, click the offending file there, and then resolve the conflict in a UI where I don't even know which of the views corresponds to which version of the code (merge base, incoming, current)? Wow that's really unintuitive. I would never even have guessed to look there, I just open the file with a conflict in the regular editor view and go from there. And that used to work very well, but it seems that feature was removed? :(

**Comment by bjorn3** [comment]
You can use `"git.mergeEditor": false` to get back the old behavior. That is what I did after I updated vscode and got presented the extremely unintuitive new merge editor.

**Comment by mindlessroman** [comment]
> You can use `"git.mergeEditor": false` to get back the old behavior. That is what I did after I updated vscode and got presented the extremely unintuitive new merge editor.

Thank you !!! Solved it for me as well.

**Comment by fathonyfath** [comment]
> You can use `"git.mergeEditor": false` to get back the old behavior. That is what I did after I updated vscode and got presented the extremely unintuitive new merge editor.

Thank you! One of my VSCode usecase is to solve merge conflicts and I set vscode as my mergetool for my git. Why would they adds a toggle to this features?

**Comment by hediet** [comment]
/duplicate

We will restore the old behavior while keeping the new merge editor.
