### ISSUE TITLE
Style bug when workbench.editor.tabCloseButton is set to "left"

### ISSUE THREAD

**Issue by wavygecko** [microsoft/vscode#158625]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: macOS 12.5

Steps to Reproduce:

1. Set `workbench.editor.tabCloseButton` to `left`
2. Look at the tab's close button - it's too far to the left, butting up against the start of the tab (especially noticeable when hovered over) compared to when set to `right`

Comparison:

<img width="148" alt="image" src="https://user-images.githubusercontent.com/110956608/185702023-4fafce6a-9ad8-40df-aee1-3dc9f53d1a22.png">

<img width="137" alt="image" src="https://user-images.githubusercontent.com/110956608/185702056-319fd79c-a974-403d-9d70-e60496add89a.png">

**Comment by bpasero** [comment]
Agree. I think @misolori the change in https://github.com/microsoft/vscode/commit/10375e8c124fbfe7ab35dafa16b1f18d5d78f581 pushes the close button more to the left, can you elaborate why that was done?

**Comment by misolori** [comment]
I'm trying to remember why that was changed and can't remember, happy to remove if it doesn't appear to break anything.
