### ISSUE TITLE
Add support for rendering HTML outputs in Notebooks inside an iframe

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#158714]
Jupyter has the ability to render HTML output inside iframes based on a metadata named `isolated`.
I.e. when this is `true`, output is inside an iframe.

Currently HTML is rendered within the same DOM, and this can cause a few issues (in one case the HTML output is not generated at all), see https://github.com/microsoft/vscode-jupyter/issues/8446

Proposal:
* Add support for a metadata named `isolated`, similar to the one proposed here https://github.com/microsoft/vscode/issues/157076

**Comment by DonJayamanne** [comment]
@rebornix @mjbvz /cc

**Comment by mjbvz** [comment]
@DonJayamanne Does the iframe inherit styling or other features from the parent notebook?

**Comment by rebornix** [comment]
Make sense to me to add this support in the builtin html renderer, in the same approach as we take for the image attachment rendering.

**Comment by DonJayamanne** [comment]
> oes the iframe inherit styling or other features from the parent notebook?

Do you mean vscode theme styles.
I would say no.

**Comment by DonJayamanne** [comment]
Closing this issue as out of scope, as this hasn't received any upvotes for a few years. now.
