### ISSUE TITLE
Let audio cues work on the web (e.g. vscode.dev)

### ISSUE THREAD

**Issue by leonardder** [microsoft/vscode#158749]
## Steps to reproduce
1. Go to vscode.dev
2. Open a new file
3. Press f1
4. Search for cues and open the audio cues list
5. Observe that moving through the list doesn't play the cues.

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 Edg/104.0.1293.63
Embedder: vscode.dev

**Comment by isidorn** [comment]
@leonardder thanks for reporting but this is fixed now. Closing as dup of https://github.com/microsoft/vscode/issues/147190
