### ISSUE TITLE
Add support to detect whether a notebook cell has had the input/output collapsed

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#158716]
Jupyter notebook file format support:
* Defining whether the input/output can be collapsed and this state is stored in the file 

Suggestion:
* Can we have a way to detect whether the cell intput has been collapsed
* Can we have a way to detect whether the cell output has been collapsed
* Can we have a way (for serializer) to control this UI state when opening a notebook, e.g. the notebook serializer will control the initial UI state of the cell & output

**Comment by rebornix** [comment]
I'm closing this for now as we are not exploring this API in the near future.
