### ISSUE TITLE
Search does not find all results

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#158753]
1. code-insiders new user data dir
2. Open this repository https://github.com/microsoft/vscode-tools
3. Download top 500 extensions from the marketplace following these steps https://github.com/microsoft/vscode-tools#downloading-extensions-from-marketplace
4. Search for "webview" in the vscode-tools repository
5. No results found (first image) 🐛 

Open VS stable on the same repository and notice that results get found for "webview" (second image). Adding label "regression" since it feels that way.

Maybe you do not have to follow the exact steps from above, but at least that is how I can reproduce it.

![Screenshot 2022-08-22 at 14 59 09](https://user-images.githubusercontent.com/1926584/185927076-96d914c9-657c-4484-86f5-c455c333c7df.png)

![Screenshot 2022-08-22 at 14 59 01](https://user-images.githubusercontent.com/1926584/185927062-f91cc67c-f42f-4fc3-ad88-d9d6c77c7654.png)

**Comment by roblourens** [comment]
I think that folder is gitignored, which you can override with include patterns

**Comment by isidorn** [comment]
@roblourens yes, that is the case. Thanks!
But how come that on Stable I get the results for the same `gitignore`? Did we only start to respect the `gitignore` this milestone (I would be surprised)?

Feel free to close this as designed.

**Comment by roblourens** [comment]
Because you have a string in "files to include" which can override gitignore patterns.

**Comment by isidorn** [comment]
Got it, thanks! Closing this as invalid
