### ISSUE TITLE
pwsh terminal scrolling infinitely

### ISSUE THREAD

**Issue by jdholbrook81** [microsoft/vscode#158777]
Type: <b>Bug</b>

When I open vscode my pwsh terminal is scrolling infinitely, it shows:

PS>
PS>
PS>
PS>

... and keeps repeating that. I can't type anything. If I try to double click it briefly shows a selection bar that scrolls off the screen. I have tried killing the terminal and restarting, restarting vs code, disabling all extensions, and uninstalling and reinstalling vscode, but the issue persists. If I open the cmd terminal it works as expected.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.27GB free)|
|Process Argv|--crash-reporter-id 747d68e1-62ac-4f67-877f-54258fe59f6b|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30543456
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by gjsjohnmurray** [comment]
Does the setting `"terminal.integrated.shellIntegration.enabled": "false"` resolve this?
