### ISSUE TITLE
Cannot browse extensions gallery behind corporate proxy

### ISSUE THREAD

**Issue by akerd** [Microsoft/vscode#15879]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Build 14393

This is another issue related to access the extensions gallery behind a proxy. I read all previous post here and on the web but I was not able to find a fix for my environment.

I tried to setup proxy in settings without authorization
```
    "http.proxy": "http://proxy_address:8080",
    "https.proxy": "http://proxy_address:8080",
    "http.proxyStrictSSL": false
```
and I tried also with authorization, that is usually required by our corporate proxy (BlueCoat)
```
    "http.proxy": "http://domain%5Cusername:password@proxy_address:8080",
    "https.proxy": "http://domain%5Cusername:password@proxy_address:8080",        
    "http.proxyStrictSSL": false
```
In both in this case the error message : **Error read ECONNRESET**

The very strange thing is that with Visual Studio 2015 Enterprise I can browser the extensions.
I decide so to monitor the HTTP traffic using WireShark but I was not able to find the differences the two call looks very similar but in case of VS Code the connection is dropped, in the other case it works.

I checked the two destination addresses and I can open both in HTTPS without problem with the browser on the same machine.

### WireShark Monitoring VS Code Extension Gallery HTTP Request

![image](https://cloud.githubusercontent.com/assets/1030305/20521185/47acf88e-b0aa-11e6-81d3-a302605ed89d.png)

![image](https://cloud.githubusercontent.com/assets/1030305/20521188/4bdb0e3c-b0aa-11e6-917c-b3251af56de7.png)

### WireShark Monitoring Visual Studio 2015 Extension Gallery HTTP Request

![image](https://cloud.githubusercontent.com/assets/1030305/20521192/50a69d82-b0aa-11e6-9623-a42d361b790d.png)

![image](https://cloud.githubusercontent.com/assets/1030305/20521196/556f5c64-b0aa-11e6-9b29-33bc383f46c5.png)

If you have some suggestions or you need some more debug information just let me know.

Thank you,
Marco

**Comment by joaomoreno** [comment]
Have you checked with your network administrator if he needs to whitelist `marketplace.visualstudio.com`?

Did you restart Code every time you changed the proxy settings?

**Comment by akerd** [comment]
Thank you for answering.

Yes, at every change of settings I restarted VS Code.

About whitelisting I didn't contact our IT organization, it is a little complicated (I work in a big company). But using any browsers, configured to pass through the same proxy, the website is working without any problems.

**Comment by joaomoreno** [comment]
Hm... do you know which type of proxy authentication is being used in your network?

**Comment by akerd** [comment]
Mm good question, usually in order to exit with other programs I just need to specify DOMAIN\USERNAME and the same password I use to login to my domain account. But I suppose this is not enough, I will try to contact some IT to get some details about which proxy authentication we are using.

**Comment by akerd** [comment]
Ok finally they answer my request, but the only technical information that I received is that the proxy authentication is NTLM based. Is it enough?

**Comment by joaomoreno** [comment]
It's enough just to flag it as a duplicate. 😢 

#10461
