### ISSUE TITLE
August Insiders incompatible with old Ubuntu 18.04

### ISSUE THREAD

**Issue by ngollan** [microsoft/vscode#158734]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Insiders 1.71
- OS Version: Ubuntu 18.04 amd64

Steps to Reproduce:

1. Try to install latest code-insiders packages from MS repository (`apt install code-insiders`)

```
The following packages have unmet dependencies:
 code-insiders : Depends: libgcc-s1 (>= 3.0) but it is not installable
```

The issue is that with 82f6cbd6b5755f856951f4f011e41c0ed95990f0 the `libgcc1` dependency on Debian derivatives changed to `libgcc-s1` which only exists on newer releases (20.04 and later I think).

I realise that support for Ubuntu-Ancient is low on the priority list, but I am sadly stuck with it, and would appreciate if there was a workaround. Installing newer libgcc releases as suggested in some places easily leads to a very broken system.

**Comment by deepak1556** [comment]
This is a side effect of now using bullseye sysroot, we should apply the following change https://chromium-review.googlesource.com/c/chromium/src/+/3572926/3/chrome/installer/linux/debian/calculate_package_deps.py to our debian calculate package deps.
