### ISSUE TITLE
Test: Continue Working On to desktop VS Code

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#158798]
Refs https://github.com/microsoft/vscode/issues/156833

- [x] Windows @karrtikr 
- [ ] macOS @jrieken
- [x] Linux @karthiknadig

Authors: @joyceerhl

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158798%0A%0A&assignees=joyceerhl)

---

The original version of the Continue Working On feature shipped over a year ago and allows you to continue a "virtual"/"serverless" GitHub or Azure Repos repository in a different context such as a codespace, desktop clone, or container. With https://github.com/microsoft/vscode/issues/141293 we have been working to 1. expand Continue Working On to make it easy to work on the same repo across desktop and web VS Code instances and 2. integrate Edit Sessions into Continue Working On transitions so that your uncommitted changes come with you whenever you switch contexts.

Last milestone, we added support for resuming edit sessions when you Continue Working On a repository in VS Code for the Web (vscode.dev and GitHub Codespaces). This milestone, we also added support for resuming edit sessions when you Continue Working On a repository in desktop VS Code.

**Pre-requisites**:
1. Install the following extensions:
    - GitHub Repositories (latest pre-release)
    - Azure Repos (latest pre-release)
    - Remote Repositories (latest pre-release v0.19.2022082301)
    - Remote-Containers (0.248.0-rc)
    - GitHub Codespaces (1.10.2)
2. Ensure you have the latest VS Code Insiders build installed.
3. Ensure you have `"workbench.experimental.editSessions.enabled": true` in your settings on both insiders.vscode.dev and desktop VS Code. This is enabled by default in Insiders at the moment.
4. Also ensure you have `"workbench.experimental.editSessions.autoResume": "onReload"` in your settings on both insiders.vscode.dev and desktop VS Code
5. Run `Edit Sessions: Sign In` and `Codespaces: Sign In` from the command palette in your settings on both insiders.vscode.dev and desktop VS Code

**Test plan**:
1. From the remote indicator or command palette, choose the Continue Working On item.
2. When you are in a GitHub repository in https://insiders.vscode.dev, ensure that you see the following options for Continue Working On:
    <img width="1620" alt="image" src="https://user-images.githubusercontent.com/30305945/185987422-1abf678e-090d-4bb3-bd32-d1c61ec74b70.png">

3. Create some uncommitted changes in the source workspace, and test that your uncommitted changes come with you when using Continue Working On in the following scenarios:

> | Source | Destination |
> | -- | -- |
> | https://insiders.vscode.dev/github/microsoft/vscode-wasm | Clone repository locally and open on desktop |
> | https://insiders.vscode.dev/azurerepos/Monacotools/Monaco/Sandbox | Clone repository locally and open on desktop |
> | https://insiders.vscode.dev/github/microsoft/vscode-wasm | Reopen on the desktop in RemoteHub |
> | https://insiders.vscode.dev/azurerepos/Monacotools/Monaco/Sandbox | Reopen on the desktop in RemoteHub |

6. When in desktop VS Code, use the Open Remote Repository action from the remote indicator or command palette to browse a GitHub or Azure Repos repository without cloning:
    <img width="548" alt="image" src="https://user-images.githubusercontent.com/30305945/185987574-1e5671c4-5825-4b71-847d-6bb1d2c513f3.png">

7. When you are in a virtual GitHub repository on desktop, ensure that you see the following options for Continue Working On:
    <img width="1620" alt="image" src="https://user-images.githubusercontent.com/30305945/185989012-90b76f19-9a92-4f47-be52-b4ae24df5668.png">

8. Create some uncommitted changes in the source workspace, and test that your uncommitted changes come with you when using Continue Working On in the following scenarios:

> | Source | Destination |
> | -- | -- |
> | Open Remote Repository > https://github.com/microsoft/vscode-wasm | Clone repository locally and open on desktop |
> | Open Remote Repository > https://dev.azure.com/monacotools/Monaco/_git/Sandbox | Clone repository locally and open on desktop |
> | Open Remote Repository > https://github.com/microsoft/vscode-wasm | Clone repository in a container volume |
> | Open Remote Repository > https://dev.azure.com/monacotools/Monaco/_git/Sandbox | Clone repository in a container volume |

**Known issues**:
1. https://github.com/microsoft/vscode-remote-repositories-github/issues/223
2. https://github.com/microsoft/vscode/issues/158384
3. https://github.com/microsoft/vscode/issues/158386
4. https://github.com/microsoft/vscode/issues/123492

**Comment by karrtikr** [comment]
> Remote-Containers (0.248.0-rc)
GitHub Codespaces (1.10.2)

I assume these need to be updated to:

> Remote-Containers (0.248.0)
GitHub Codespaces (1.10.3)

- Renamed `"workbench.ezperimental.editSessions.autoResume": "onReload'` to `"workbench.experimental.editSessions.autoResume": "onReload"`
- Renamed `GitHub Codespaces: Sign In` to `Codespaces: Sign In`
