### ISSUE TITLE
Test: new codecs

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#158759]
Refs: https://github.com/microsoft/vscode/issues/156558

- [x] Windows @hediet
- [x] macOS @meganrogge
- [x] Linux @roblourens

Complexity: 4
Authors: @deepak1556 @isidorn 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158759%0A%0A&assignees=isidorn,deepak1556)

---

We are now shipping more codecs as part of our electron build. Verify the following:
* F1 > Help: List Audio Cues > you can hear all the audio cues being played
* You can play audio signals from python. Code sample:
```
import IPython.display as ipd
import numpy as np
fs = 16000.
ipd.Audio(np.sin(2*np.pi*440*np.arange(5 * fs)/fs), rate=fs)
```
* You can play audio files from notebooks. Code sample:
```
import IPython.display as ipd
ipd.audio('PATH_TO_SOME_WAV_FILE')
ipd.audio('PATH_TO_SOME_MP3_FILE')
```
~~* Try to [embed a YouTube video](https://stackoverflow.com/a/59474408) into a notebook and verify you can play the video from the notebook~~
* Try to create an extension that embeds a video in the markdown preview. [Code example](https://stackoverflow.com/questions/48321919/show-html5-video-on-previewhtml-command-in-vscode-extension/51735036#51735036)

**Comment by hediet** [comment]
I think
> * You can play audio signals from python. Code sample:

and

> * You can play audio files from notebooks. Code sample:

shouldn't be affected by this, is the python process doesn't use the electron codecs?

**Comment by deepak1556** [comment]
I think the output renderer for the above two cases are HTML renderer from VSCode core and these renderers will rely on the codec support from ffmpeg shipped with the runtime. @mjbvz @rebornix can clarify more on the renderer part since I am not familiar with it.

**Comment by mjbvz** [comment]
Yes @deepak1556  is correct. The rendered output (and markdown) are shown inside a webview so they use electron's ffmpeg for audio / video

**Comment by roblourens** [comment]
I can't get the ogg file to work in vscode, but it does in Jupyter lab.

I can't get an mp4 to play in vscode, but it also doesn't work in Jupyter lab, any idea?

```
import IPython.display as ipd
ipd.Video('/Users/roblou/Downloads/PXL_20220222_170759513.mp4')
```


<img width="588" alt="image" src="https://user-images.githubusercontent.com/323878/186240693-e8e1b446-81a9-4ae0-8027-06012acb6d1b.png">

**Comment by roblourens** [comment]
My mp4 in an extension webview worked great, however.
