### ISSUE TITLE
New "Merge Editor" setting defaults to on but doesn't show merge editor, nor previous CodeLens

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#158763]
After updating to the latest VS Code, files with conflicts no longer show CodeLens links but instead just render like this:

<img width="433" alt="Screenshot 2022-08-22 at 14 51 34" src="https://user-images.githubusercontent.com/1078012/185937570-c603871a-2b53-4d4f-b938-e579634d2d61.png">

This was raised in https://github.com/microsoft/vscode/issues/157717 and the solution suggested was to disable this setting:

<img width="590" alt="Screenshot 2022-08-22 at 14 52 20" src="https://user-images.githubusercontent.com/1078012/185937682-8db1e1a8-af49-4210-902b-bd09e265d1dc.png">

Disabling this setting does resolve the issue, and things now look like:

<img width="604" alt="Screenshot 2022-08-22 at 14 52 53" src="https://user-images.githubusercontent.com/1078012/185937783-e5dbde17-1fb1-465b-b840-558e7458f6d9.png">

However, I'm not convinced this is intended behaviour. When the tickbox was ticked, there was no "merge editor" being shown, just the normal text version of the file. Perhaps this is because I have built-in Git support disabled in VS Code, but if that's the case it doesn't seem correct that this tickbox should just disable the previous functionality when it itself is not available/enabled. These settings are still enabled:

<img width="535" alt="Screenshot 2022-08-22 at 14 55 07" src="https://user-images.githubusercontent.com/1078012/185938327-aa01e2a1-25b9-4945-b66e-4e1e8056a3ca.png">

**Comment by IllusionMH** [comment]
Similar to other issue that were marked as duplicates.

There are 2 main issues mentioned in https://github.com/microsoft/vscode/issues/157766#issuecomment-1213079772

> Duplicate of #157691 and/or #153800

/assign @hediet -tanhakabir

**Comment by DanTup** [comment]
Oh nice, I didn't find those ones. Looks like perhaps this is being handled by https://github.com/microsoft/vscode/issues/153800 which - if I understand correctly - will show the CodeLens/decorations even if the new merge editor is enabled? If so, this can be closed. Thanks!

**Comment by jrieken** [comment]
> When the tickbox was ticked, there was no "merge editor" being shown, just the normal text version of the file. Perhaps this is because I have built-in Git support disabled in VS Code

Confused... The setting comes from Git support so when you have disabled that one (assuming you mean extension) than the whole setting shouldn't exist. @DanTup What and how have you disabled. Also, try with latest insiders please because we fixed a bunch of issues there
