### ISSUE TITLE
Debugging impossible

### ISSUE THREAD

**Issue by AnjaP7** [Microsoft/vscode#15874]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.0.5|

---

Steps to Reproduce:

1. Run a node module
2. Try to watch a variable in debug
3. Node is telling to be unresponsive and gets timeouts retrieving the variable value

**Comment by weinand** [comment]
@AnjaP7 please try our new experimental node debugger by setting the `type` attribute to '"node2"'.

**Comment by weinand** [comment]
no repsonse. Closing.
