### ISSUE TITLE
Odd current line decoration border between line and gutter in our themes

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#15876]
![screen shot 2016-11-22 at 11 18 07](https://cloud.githubusercontent.com/assets/22350/20520043/934fb074-b0a5-11e6-8f9c-b3c37dc58ba4.png)

Only our 5 themes seem affected by it:

- Light
- Light+
- Dark
- Dark+
- High Contrast

**Comment by alexandrudima** [comment]
I will reduce the width, but there will still be a border between the two. I think that helps with letting users knows where the first char would start, especially when having indent guides off:

Before:
![image](https://user-images.githubusercontent.com/5047891/30913580-09806958-a391-11e7-9856-73e7d4471109.png)

After:
![image](https://user-images.githubusercontent.com/5047891/30913620-2bb54b24-a391-11e7-9ad2-49321943dd6f.png)
