### ISSUE TITLE
Add git force push command

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [microsoft/vscode#158704]
Right now there are only commands for normal push:
![screenshot](https://user-images.githubusercontent.com/52586855/185803912-bbe509d0-7aa3-46f9-a9f9-9e03872d5e38.png)

It would be nice to have a command called "Force push" which uses `--force`.

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/pull/53286#issuecomment-428178860 implies you should already be able to opt in to having this on your Command Palette.

**Comment by ChocolateLoverRaj** [comment]
@gjsjohnmurray I didn't know that was a setting. I turned it on now after I found out.
