### ISSUE TITLE
Red text in console

### ISSUE THREAD

**Issue by danirb** [Microsoft/vscode#15871]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-generate-getter-setter|DSKWRK|0.4.1|
|vscode-style-formatter|dweber019|0.0.2|
|ionic2-vscode|jgw9617|1.0.0|
|autoimport|steoates|1.2.2|
|ionic2|Thavarajan|2.3.2|
|cordova-tools|vsmobile|1.2.3|

---

Steps to Reproduce:

1. In the console, I use the command :"ionic run android"
2.In the error output (red text) I cancel it with (Cntrl + C)
then the console always are red (text)

**Comment by Tyriar** [comment]
This is likely an issue with the ionic extension you're using not clearing the red style from the error, coupled with the fact that the Windows prompt has no styling. Please file this against the extension :smiley:
