### ISSUE TITLE
Test comment filtering

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#158773]
Refs: https://github.com/microsoft/vscode/issues/150958

- [x] macOS @digitarald
- [x] linux @aeschli
- [x] windows @Yoyokrazy

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158773%0A%0A&assignees=alexr00)

---

There's a new filter input box and menu in the Comments view. You can use GitHub Pull Requests and Issues (or a comment providing extension of your choice) to verify.
1. Open a workspace with comments
  a. If you don't have one, you can use GitHub Pull Requests and Issues to open a pull request with comments
2. Open the Comments view and verify the following:
- that you can filter based on text in the body of the comment, including text that isn't visible in the comments view
- that you can use usernames to filter
- that you can filter by resolved/unresolved using the filter menu (note that not all extensions will support resolved/unresolved).
- that the showing "x of y" text in the filter input box is always correct
- that your filter state is preserved across reloads

**Comment by digitarald** [comment]
Tested with https://github.com/microsoft/vscode/pull/158313 which has 23 comments to search through.

**Comment by PabloLION** [comment]
Hi @digitarald . I'm with VS Code 1.71.0 on macOS. I saw the "comment filtering" in the release note but I cannot see it even with `--disable-extensions` flag. 
![image](https://user-images.githubusercontent.com/36828324/188748883-f7c426fc-af9e-41c0-8af9-40f47c4bff20.png)

Does it only work for PR? And if not, could you tell me where to enable it? I see here it's said "Open a workspace with comments". The comment filtering does work in a PR from GitHub extension for me

<details><summary> About VSCode
</summary>
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:25.516Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.3.0
Sandboxed: No
</details>

Thanks in advance.

**Comment by alexr00** [comment]
The "Comments" view is only available when there is an extension providing comments.
