### ISSUE TITLE
"Conflicting Lines" label should be "N Conflicting Lines"

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#158723]
It would be nice if the "Conflicting Lines" label on the right would specify how many lines are actually conflicting. This way the users would more easily discover that multiple lines are collapsed into that one line. So "N Conflicting Lines", for example "22 Conflicting Lines" for this case:

![Screenshot 2022-08-22 at 10 15 52](https://user-images.githubusercontent.com/1926584/185873628-a768a208-82cd-4bb0-8dbf-9b3962ce6807.png)

Should also make more clear the @sandy081 question in standup

**Comment by hediet** [comment]
![image](https://user-images.githubusercontent.com/2931520/186386626-fe5f6739-9936-4b4c-a2c3-7ed39a9770f5.png)

**Comment by isidorn** [comment]
Thanks for doing this!
I was wondering if this example should be 7 Conflicting Lines or 5. I see that you do not count the merge decorations - which makes sense.
