### ISSUE TITLE
Search result tree drawing glitches

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#158785]
I have seen the below a few times now. What happens is:
- select "Find in Folder..." from the context menu in the explorer
- What you see in the search and replace input boxes is remembered state
- some items have the replace text in them, some don't
- scroll items that don't have the replace text out of the viewport and back in repairs the presentation

<img width="168" alt="image" src="https://user-images.githubusercontent.com/4674940/185978152-abfa1cfa-5d0c-4892-8595-eac536c9396f.png">

**Comment by andreamah** [comment]
repro steps:
1. go to search viewlet and set the fields for search and replace; leave the files to include to blank
2. switch to explorer viewlet
3. reload the window
4. use the context menu to search a folder
5. Some search results don't reflect replace :bug:

<img width="306" alt="image" src="https://user-images.githubusercontent.com/31675041/186280332-7b06c826-3443-4281-86ae-d9e51a6da213.png">
