### ISSUE TITLE
"Find All References" not working in latest build or Insiders

### ISSUE THREAD

**Issue by loganpowell** [microsoft/vscode#158765]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Windows 10

I've tried this on both the latest release and a clean install of "Insiders" (no extensions) and it's broken on both. The "Find All References" function only works on open files.

Steps to Reproduce:

1. Create a file: `./src/sum.js`
```js
export const sum = (a, b) => {
  return a + b;
};
```
2. Create a second file: `./test/tests.js`
```js
import { sum } from "../src/sum"

const result = sum(1, 2)
```
3. Close the second file and - in the first file - right-click on the `sum` function and select "Find All References"
4. You'll see that only one reference (in the current open file) is found instead of both references.

**Comment by IllusionMH** [comment]
Do you have `jsconfig.json`/`tsconfig.json` available? 

AFAIK VS Code doesn't build project with all files unless there is config.

/assign mjbvz

**Comment by loganpowell** [comment]
I don't have a config, no, is that a prereq? If so, I'd be happy to add one. In my current (hairy) project it's not .ts even though it probably should be at this stage.

**Comment by mjbvz** [comment]
@loganpowell Yes it's required if you don't have both files open. Otherwise we won't know to look in `tests.js` for references

This is not new behavior so it's unlikely this is related to insiders

**Comment by IllusionMH** [comment]
@mjbvz 

Maybe it make sense to make some clarification in
https://code.visualstudio.com/Docs/languages/javascript#_javascript-projects-jsconfigjson and 
https://code.visualstudio.com/docs/nodejs/working-with-javascript#_javascript-projects-jsconfigjson related to including not only opened files?

Because reading items where you need it doesn't look like it's required to include all files (bold italics are mine). Reading these reasons it doesn't look like you need to create `jsconfig.json` to include "all" files into project, and it looks implied that everything will be included as you have to create config to *exclude* files.

> JavaScript projects (jsconfig.json)
> A [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig) file defines a JavaScript project in VS Code. While ***`jsconfig.json` files are not required***, you will want to create one in cases such as:
>
> * ***If not all JavaScript files in your workspace should be considered part of a single JavaScript project.*** jsconfig.json files let you exclude some files from showing up in IntelliSense.
> * ***To ensure that a subset of JavaScript files in your workspace is treated as a single project.*** This is useful if you are working with legacy code that uses implicit globals dependencies instead of imports for dependencies.
> * ***If your workspace contains more than one project context***, such as front-end and back-end JavaScript code. For multi-project workspaces, create a jsconfig.json at the root folder of each project.

**Comment by loganpowell** [comment]
@mjbvz thank you for the clarification. I can confirm setting up a `jsconfig.json` with the proper `"include"` field got me up and running as hoped!
