### ISSUE TITLE
Source Control feature seems very buggy

### ISSUE THREAD

**Issue by maxxheth** [microsoft/vscode#158712]
The Source Control feature seems to take forever to update whenever I try to sync my changes or just do a simple git push or git pull. It just lags and doesn't seem to reach a point at which it recognizes that the working tree is clean and all changes have been pushed or pulled.

I'm not using any git nor Github-related extensions of any kind.

Here is the link to my Github feed: https://vscode.dev/github/LuminousCoder/paperless-tall/blob/66e9149cddf3dc4f30a15adb39ba92dbe755ce62.git-#1-Git#L1-L188

**Comment by maxxheth** [comment]
Turned off all my extensions out of curiosity, which fixed the issue. I can't say which extension was the culprit (and I don't really have time to look into it because I'm under the gun atm), but I'll close this out nonetheless.

**Comment by lszomoru** [comment]
@maxxheth, when you find the time to further investigate the issue, please take a look at [the extension bisect tool](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect).
