### ISSUE TITLE
Merge Editor: Unexpected result for deletion test case

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#158889]
Testing #158819

* Clone https://github.com/hediet/diff-merge-dataset
* Use the `Load Merge Editor State From Folder` command and select the `merges/deletion` folder
* Select `result` in the quick pick
  <img width="1016" alt="image" src="https://user-images.githubusercontent.com/3372902/186157476-a1f3a162-8d26-4916-b053-73d6183fcdf5.png">

**Comment by hediet** [comment]
This is because the result initially didn't have conflict markers.
This does not happen in the git scenario.
