### ISSUE TITLE
Ctrl + ] on Linux works like ctrl +

### ISSUE THREAD

**Issue by voylinux** [Microsoft/vscode#15887]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:46.244Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|crane|HvyIndustries|0.2.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|0.0.12|
|php-pack|felixfbecker|1.0.0|
|php-symbols|linyang95|0.1.2|
|gitblame|waderyan|1.3.0|

---

Steps to Reproduce:

1. Press Ctrl + ]
2. It should indent lines but is zooming in

**Comment by alexandrudima** [comment]
@voylinux What keyboard layout are you on? What is the keybinding rendered when pressing `F1` and typing `Indent Line`?

If you are using a different keyboard layout, please have a quick read of our documentation:
https://code.visualstudio.com/docs/customization/keybindings#_keyboard-layouts
https://github.com/Microsoft/vscode/wiki/Troubleshooting-Keybindings

**Comment by alexandrudima** [comment]
Without further information about the exact keyboard layout used, I cannot validate, but simply assume that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) behave correctly for this keyboard layout.
