### ISSUE TITLE
Terminal: Zoom changes cause wrongly rendered terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#158878]
Testing https://github.com/microsoft/vscode/issues/158827

Version: 1.71.0-insider
Commit: https://github.com/microsoft/vscode/commit/bd6107301dc9a6200bd8d4f64a9b198438b3f1d6
Date: 2022-08-23T05:19:02.563Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

- set setting terminal.integrated.gpuAcceleration: on
- in the terminal type (not sure the text really matters)
```
echo -e "\x1b[4:3m"  # curly underline
echo -e "\x1b[4:4m"  # dotted underline
echo -e "\x1b[4:5m"  # dashed underline
```
- change the VS Code zoom level a few times (up and down)
- note that the terminal can get out of order
<img width="642" alt="Screenshot 2022-08-23 at 12 42 44" src="https://user-images.githubusercontent.com/6461412/186139060-7be1385a-aad4-42d2-85ae-878400db6c6a.png">

**Comment by aeschli** [comment]
The same bugs can be produced by resizing the terminal view horizontally

**Comment by Tyriar** [comment]
Looks like https://github.com/microsoft/vscode/issues/157585

/duplicate
