### ISSUE TITLE
"Rename failed to apply edits" in monorepo with pnpm

### ISSUE THREAD

**Issue by guansss** [microsoft/vscode#158845]
Type: <b>Bug</b>

Same as #55606 (locked), but I managed to find a stable reproduction.

1. Clone [this repo](https://github.com/guansss/vscode-rename-repro)
2. Run `pnpm i`
3. Open `packages/utils/src/index.ts`
4. Rename the `log` function more than two times

For the first time it works (sometimes not), but starting from the second time renaming any symbol will fail in such ways:

- If you insert new characters, they will be duplicated.
- If you remove characters, an error will occur saying "Rename failed to apply edits".

![record](https://user-images.githubusercontent.com/46285865/185901039-16035f57-d617-4a4d-a89d-88a51865a1e5.gif)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (4.50GB free)|
|Process Argv|--crash-reporter-id ef2611e6-be94-4ae2-b742-8aed3dc65886|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by guansss** [comment]
Here's what I found while trying to investigate this, hope that helps.

I debugged into VSCode's TypeScript extension and it turned out that tsserver's `rename` command was returning two locations where the paths only differ in the case of drive letter, which eventually caused VS Code's rename operation to misbehave.

![capture](https://user-images.githubusercontent.com/46285865/186068764-c63b8aa2-1170-48bb-b1bf-0cf5f0642cb7.png)

So I guess it's a bug of TypeScript, what do you think?

**Comment by jrieken** [comment]
TypeScript could do better but the drive letter shouldn't matter. Internally we have ways to treat such URIs as equal and we should use that for the workspace edit too

**Comment by jrieken** [comment]
Moving to September, might take a different route to fix this
