### ISSUE TITLE
Ctrl+Left Click to open a path start with ~ in terminal is not working

### ISSUE THREAD

**Issue by zheng-fan** [microsoft/vscode#158807]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- Local OS Version: Windows 10 Pro for Workstations 21H2 19044.1889
- Remote OS Version: WSL1 - Debian 11 / SSH - Debian 9

Steps to Reproduce:

1. Remote-WSL/SSH to a server.
2. Open the integrated terminal and type a path start with `~` like `~/.ssh` then left click to the path in terminal. VSCode shows that no matching results.
3. But if we type an absolute path like `/home/fz/.ssh` then it works.

Considering that there may be files or directories starting with `~` in the current directory, VSCode has changed the file path parsing method since v1.69 (If I remember correctly). But can we continue to parse `~` as home directory(like `~/.ssh` as `/home/fz/.ssh`, `~root/.ssh` as `/root/.ssh`) after judging that the files or directories in the current directory does not exist?

**Comment by Tyriar** [comment]
This actually happens on local workspaces as well, at least on Windows

**Comment by Tyriar** [comment]
It's being treated as a search link because of this:

![image](https://user-images.githubusercontent.com/2193314/206740037-66882cb9-fb3d-4077-8bb7-8ef008c6d696.png)
