### ISSUE TITLE
Variable '${defaultBuildTask}' not reliably found

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#158817]
Recently I'm seeing this problem in Insiders:

When debugging a plain "hello world" extension, sometimes the `${defaultBuildTask}` does not resolve to the default task defined in tasks.json:

```
{
	"type": "npm",
	"script": "watch",
	"problemMatcher": "$tsc-watch",
	"isBackground": true,
	"presentation": {
		"reveal": "never"
	},
	"group": {
		"kind": "build",
		"isDefault": true
	}
}
```

Instead the npm scripts from the package.json are shown in a Quickpick: 

<img width="1162" alt="CleanShot 2022-08-22 at 21 38 59@2x" src="https://user-images.githubusercontent.com/1898161/186004753-ca466948-5377-4f29-b11f-680f0329aa3f.png">

Restarting VS Code does not help, but changing a single character in the tasks.json or launch.json fixes the problem.

**Comment by alexr00** [comment]
@meganrogge the task service contributes the variable `defaultBuildTask` here: https://github.com/microsoft/vscode/blob/49de874e5fcf25df4aa84cc0f2e00a2f40bea223/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L298-L299

**Comment by meganrogge** [comment]
When I `Run Task`, I see that the default build task isn't in the dropdown for about 10 seconds

**Comment by meganrogge** [comment]
could be the root cause: https://github.com/microsoft/vscode/issues/157814

**Comment by weinand** [comment]
Yes, the 10 second delay could explain the problem. And my workaround "to change a single character in tasks.json or launch.json" only helps because it takes longer than 10 seconds...

**Comment by meganrogge** [comment]
what's odd is I don't see this happening in oss, only insider's

**Comment by meganrogge** [comment]
I am actually no longer able to reproduce the issue I mentioned above and it's working for me in an extension 🤔. @weinand a gif would be super helpful if possible

**Comment by meganrogge** [comment]
@weinand are you still able to repro?

**Comment by weinand** [comment]
@meganrogge in today's Insiders I'm no longer able to reproduce the issue.

**Comment by meganrogge** [comment]
great, pls reopen this if you see it again

**Comment by rzhao271** [comment]
Marking as not-reproducible
