### ISSUE TITLE
Save and Open window not working

### ISSUE THREAD

**Issue by sachinphogat1** [microsoft/vscode#158843]
Operating system: MacOS Monterey 
OS Version: 12.5.1

Whenever I try to save or open existing files on vscode, related window opens but all buttons are disabled and just dont work.

**Comment by bpasero** [comment]
From the description the issue sounds like a setup / configuration problem outside of VSCode and nothing VSCode itself could fix.

VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

We also have a large community over at https://stackoverflow.com/questions/tagged/visual-studio-code to ask for advice.

Happy Coding!
