### ISSUE TITLE
Test: Terminal smooth scrolling

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158826]
Refs: #125950

- [x] macOS @lszomoru 
- [x] linux @sadasant
- [x] windows @luabud

Complexity: 1

Authors: @meganrogge @Tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158826%0A%0A&assignees=Tyriar,meganrogge)

---

The terminal now features smooth scrolling like in the editor. To test, enable `"terminal.integrated.smoothScrolling": true` and see if it acts like the editor.

Note that it's expected that all rows in the terminal are still "snapped" to the grid.

**Comment by lszomoru** [comment]
@Tyriar, should the terminal match the editor when it comes to page up/page down, as well as jumping between search results? Even though I have enabled the setting, reloaded the window, the experience for these two scenarios does not match the editor. Happy to get on a call and screen share if you want.

**Comment by Tyriar** [comment]
@lszomoru yes it should, that's a bug. Could you create an issue? I suppose ctrl/cmd+up/down is similar to jumping to definition so it should also animate scroll

**Comment by sadasant** [comment]
Works on Linux!

**Comment by luabud** [comment]
I'm not able to notice a difference but it doesn't mean it isn't working 😅 I'm happy to record a GIF with more or less movements if that would help? 

![TerminalScrollTP1588262](https://user-images.githubusercontent.com/45497113/186259506-8f695250-ad2c-41df-ab7c-ef734247272b.gif)

**Comment by Tyriar** [comment]
@luabud when it's off, scrolling should "snap" immediately to the row, otherwise it would animate the scroll over 125ms. If you're using a scroll pad instead of a mouse it's much harder to notice as scroll pads have a feature called "ballistic scrolling" which does something similar already

**Comment by luabud** [comment]
@Tyriar ahh that makes sense, thank you! I was indeed using a scroll pad. I tested with the mouse now and was able to notice the difference.
