### ISSUE TITLE
'Find all references'  not working

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#15881]
- VSCode Version: 1.7.1
- OS Version: Linux Mint

Hy,
Not sure if I should have posted here or in vscode-cpp. 
Regarding the the feature "Find all references", it doesn't work at all. Every time I use it I receive empty results.
Do I need to configure or install something?

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-cpptools#361
