### ISSUE TITLE
When several definitions revealed, the arrow in the peek view should point to the correct element 

### ISSUE THREAD

**Issue by aiday-mar** [microsoft/vscode#158871]
The issue can be seen in the gif below. Notice how despite the fact that right definitions are shown the arrow points to the wrong definition in the sticky scroll line.

![sticky-scroll-incorrect-arrow](https://user-images.githubusercontent.com/61460952/186131754-18f3e7e6-09f7-4cda-8c7d-90cc4e850ba0.gif)

**Comment by ryihan** [comment]
it's not a bug.

**Comment by Perea98** [comment]
Que es más recomendable hacer al respecto
