### ISSUE TITLE
Changing theme loses terminal selection

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#158898]
Testing #158828

1. Select something in the terminal
2. F1 > change theme. 
3. Selection is not preserved in the terminal 🐛 

Notice how we nicely preserve selection in the editor on theme change.

fyi @alexr00

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4057

**Comment by Tyriar** [comment]
Fixed
