### ISSUE TITLE
Terminal: Underline with canvas uses less spacing

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#158874]
Testing #158827

Version: 1.71.0-insider
Commit: bd61073
Date: 2022-08-23T05:19:02.563Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

- set setting `terminal.integrated.gpuAcceleration: canvas`
- in a terminal type
```
echo -e "\x1b[4:3m"  # curly underline
echo -e "\x1b[4:4m"  # dotted underline
echo -e "\x1b[4:5m"  # dashed underline
```

<img width="594" alt="Screenshot 2022-08-23 at 12 18 35" src="https://user-images.githubusercontent.com/6461412/186134108-84eceeb8-2ce3-4bbd-856b-ac958f59adc7.png">

- set setting `terminal.integrated.gpuAcceleration: on`
<img width="549" alt="Screenshot 2022-08-23 at 12 21 56" src="https://user-images.githubusercontent.com/6461412/186134697-06507ccd-7383-4d8a-aa20-ad7a94e48ec7.png">

Note that the spacing of the underline differs: with canvas it is a bit too close to the text

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4058
