### ISSUE TITLE
'Find' silently fails after 1000 results

### ISSUE THREAD

**Issue by latkin** [Microsoft/vscode#1588]
If you search for something, Code only finds the first 1000 instances - it silently fails to navigate and/or highlight further instances.

This makes viewing/searching log files (which often have 10Ks or more instances) pretty much a no-go with Code.

![find1000](https://cloud.githubusercontent.com/assets/5943573/11964591/ac91a020-a8a3-11e5-8be0-c5a4f7331a91.gif)

**Comment by latkin** [comment]
This also leads to interesting results with 'Replace':

![replace1000](https://cloud.githubusercontent.com/assets/5943573/11964775/bdb1fb42-a8a4-11e5-98cb-8901cd420c5b.gif)

**Comment by Tyriar** [comment]
Related: https://github.com/Microsoft/vscode/issues/331, https://github.com/Microsoft/vscode/issues/1110

**Comment by mathiask88** [comment]
@latkin I know this is unrelated but can u tell me the program you used to create the animated gif? I am searching for a good one on windows machines :)

**Comment by Tyriar** [comment]
@mathiask88 I use [LICEcap](http://www.cockos.com/licecap/) on Windows.

**Comment by latkin** [comment]
@Tyriar "Screen 2 Gif" https://screentogif.codeplex.com/, it's awesome! I recommend the pre-release version, especially if you have DPI-scaled displays.

**Comment by alexandrudima** [comment]
Starting with 587854a5bcae72950da0e9412ab773933a350e6b, the find next/prev and replace actions no longer use the decorations for their logic, so the functionality of the widget works regardless of the 1k limit, it is only the visual hints now that end after 1k:

![find1k](https://cloud.githubusercontent.com/assets/5047891/12213196/a9c57b4e-b674-11e5-9141-1a00c616c80e.gif)
