### ISSUE TITLE
Dirty diff decorations show up in diff editor

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#15888]
![image](https://cloud.githubusercontent.com/assets/22350/20527393/88ec2ac2-b0c8-11e6-8384-cc7180ff9062.png)

**Comment by joaomoreno** [comment]
This only reproduces when the file is also open in the single editor!

cc @alexandrudima

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!

**Comment by alexandrudima** [comment]
I made a comment, so now this is an issue that has gained traction.

**Comment by joaomoreno** [comment]
Not any more!
