### ISSUE TITLE
Should the default inactive terminal selection background be the same one as used by the editor

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#158899]
Testing #158828

I think currently the default terminal and the editor selection colours are different.
Should we use the same default inactive selection background both in the editor and the terminal (for consistency and less different colours on the screen)?

**Comment by Tyriar** [comment]
That's the intention, they are derived by the terminal.selection key and not the editor one though so it might depend on the theme.

If you're not seeing https://github.com/microsoft/vscode/issues/158896, was this using any particular theme we ship?

**Comment by isidorn** [comment]
In the default light theme they look pretty different to me (editor is greyish, terminal is blueish).
https://github.com/microsoft/vscode/issues/158896 is unrelated to this, I have changed the gpu acceleration setting back to auto.

Feel free to close if by design. I thought that editor and terminal selection colour should align more, but I understand that they use a different background colour so that might not always work.

![Screenshot 2022-08-23 at 18 09 56](https://user-images.githubusercontent.com/1926584/186208121-aef8d439-fa13-4018-aff2-c90da0b303eb.png)

**Comment by daviddossett** [comment]
Light (Visual Studio) defines `"editor.inactiveSelectionBackground": "#E5EBF1"` which is picked up by Light+. I think inheriting `editor.inactiveSelectionBackground` for the terminal color as we do for regular selection via `terminal.selectionBackground` makes the most sense here. We're copying over the transparency rules already anyway.

**Comment by daviddossett** [comment]
Ended up just explictly defining `terminal.inactiveSelectionBackground` for any default theme that specifies `editor.inactiveSelectionBackground` to keep them in sync.
