### ISSUE TITLE
Abnormal display of Menlo font in editor

### ISSUE THREAD

**Issue by XiaLiChao82** [microsoft/vscode#158842]
Type: <b>Bug</b>

Menlo fonts When 'fi' combinations are encountered in the editor, the 'i' in 'fi' is not a Menlo font

VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Host OS version: MacOS 12.5
Modes:
Remote OS version: Linux x64 5.4.0-124-generic
Remote OS version: Linux x64 5.4.0-124-generic
Remote OS version: Linux x64 5.4.0-124-generic

**Comment by IllusionMH** [comment]
Do you have ligatures enabled?

Please provide screenshots of VS Code's and expected behaviors.

**Comment by XiaLiChao82** [comment]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/35571249/186566359-be1f0992-2061-48f6-ba2e-22591a0210cd.png">

**Comment by XiaLiChao82** [comment]
Thank you very much. The problem was solved when i disabled ligature
