### ISSUE TITLE
Format JSON does not work on insider (1.8)

### ISSUE THREAD

**Issue by akharsh-tr** [Microsoft/vscode#15882]
- VSCode Version: 1.8 insider
- OS Version: Windows 7

Steps to Reproduce:

1. change language mode to JSON
2. paste json and use "Format Document" from command pane 

same thing work on stable VS code

**Comment by aeschli** [comment]
It seems to work from me. Can you paste a code example where is doesn't?
Any extensions that might replace the format functionality?

**Comment by akharsh-tr** [comment]
To Reproduce :-
so , I pasted following line on document and used "Format Document" from command pane

{"id": "0001","type": "donut","name": "Cake","image":{"url": "images/0001.jpg","width": 200,"height": 200},"thumbnail":{"url": "images/thumbnails/0001.jpg","width": 32,"height": 32}}

Interesting bit is json data should be linearized (w/o any line breaks).

**Comment by aeschli** [comment]
I was able to reproduce with a docuent containing the content above on just one line.

Problem seems to be in workerService.computeMoreMinimalEdits, all edits ranges are modified to the end of the line.
