### ISSUE TITLE
Terminal: Dotted looks more like dashed

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#158872]
Testing https://github.com/microsoft/vscode/issues/158827

Version: 1.71.0-insider
Commit: https://github.com/microsoft/vscode/commit/bd6107301dc9a6200bd8d4f64a9b198438b3f1d6
Date: 2022-08-23T05:19:02.563Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

- open a terminal and enter `echo -e "\x1b[4:4m"  # dotted underline`

![image](https://user-images.githubusercontent.com/6461412/186132008-617d2569-8a2d-4735-848e-c3f5830bb1a4.png)

Note that it's not really dots, but lines of various length

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4060

**Comment by Tyriar** [comment]
This is fixed 🎉
