### ISSUE TITLE
Commands via CodeLenses no longer working

### ISSUE THREAD

**Issue by DFelten** [microsoft/vscode#158875]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

Commands via CodeLenses are no longer working. For example when trying to run an inline test the button is doing nothing.

![CleanShot 2022-08-23 at 12 31 00](https://user-images.githubusercontent.com/1169185/186136486-1eea2202-3a21-42e0-9549-a3bbdfab196b.png)

VS Code version: Code - Insiders 1.71.0-insider (bd6107301dc9a6200bd8d4f64a9b198438b3f1d6, 2022-08-23T05:21:44.168Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.24GB free)|
|Process Argv|--crash-reporter-id 511166e9-0c5e-4225-a6af-efd2d90c3f8d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-m3u|af4|1.0.0
project-manager|ale|12.6.1
flutter-snippets|ale|3.0.0
toggle-excluded-files|eam|1.7.0
clipboard-history|Anj|1.0.7
melos-code|bla|0.4.3
vscode-intelephense-client|bme|1.8.2
ccs-flutter-color|cir|1.0.2
gitignore|cod|0.9.0
php-namespace-resolver|ctf|0.0.8
vscode-mysql-client2|cwe|5.7.3
vscode-mac-color-picker|dae|1.1.0
dart-code|Dar|3.47.20220808
flutter|Dar|3.46.0
git-diff-and-merge-tool|dav|1.0.5
vscode-markdownlint|Dav|0.47.0
vscode-new-file|dku|4.0.2
githistory|don|0.6.19
gitlens|eam|12.1.2
bloc|Fel|6.6.1
mason|Fel|0.1.5
flutter-coverage|flu|0.0.4
vscode-pull-request-github|Git|0.48.1
todo-tree|Gru|0.0.215
terraform|has|2.23.0
json-to-dart|hir|3.5.8
rest-client|hum|0.25.1
monkey-patch|ioc|0.1.19
pubspec-assist|jer|2.3.2
shortcut-menu-bar|jer|3.0.4
intellij-idea-keybindings|k--|1.5.2
indent-to-bracket|LAK|1.2.2
flutter-intl|loc|1.18.2
flutter-tree|mar|1.0.0
syntax-project-pbxproj|mar|0.1.3
Kotlin|mat|1.7.1
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
dart-barrel-file-generator|miq|4.0.0
diff-merge|mos|0.7.0
vscode-docker|ms-|1.22.1
vscode-language-pack-de|MS-|1.70.8170921
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.8.1002371040
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.248.0
live-server|ms-|0.2.13
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.24.0
sqltools-driver-mysql|mtx|0.3.0
awesome-flutter-snippets|Nas|4.0.1
vscode-versionlens|pfl|1.0.10
material-icon-theme|PKi|4.20.0
remove-comments|pli|1.2.2
vscode-thunder-client|ran|1.18.7
vscode-yaml|red|1.9.1
vscode-sort-json|ric|1.20.0
vscode-coverage-gutters|rya|2.10.1
lcov-lang|Ser|1.0.1
reveal|smu|1.2.7
swift-lang|ssw|0.7.0
better-search|tra|0.0.6
errorlens|use|3.6.0
vscode-lldb|vad|1.7.4
vscode-todo-highlight|way|1.0.5
php-debug|xde|1.27.0
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253

```

</details>

**Comment by jrieken** [comment]
New insider is on its way...

**Comment by hediet** [comment]
Fixed now. Sorry for the inconvenience!
