### ISSUE TITLE
Enable more Settings to be configured per policies

### ISSUE THREAD

**Issue by ASDFGamer** [microsoft/vscode#158820]
The support for policies was added with the Issue #147756 and in particular the Pull-Request #148632.
But until now only one Setting ([UpdateMode (Line 31)](https://github.com/microsoft/vscode/blob/main/src/vs/platform/update/common/update.config.contribution.ts) supports this new feature.

I would like that this feature is supported by more Settings and would also implement the changes.
My thoughts are that the following settings should also be configurable per policies:

- Extensions: Auto Check Updates
- Extensions: Auto Update
- Extensions: Ignore Recommendations
- Extensions: Support Untrusted Workspaces
- Extensions Web Worker
- Terminal: Explorer Kind
- Terminal: External: Linux Exec
- Terminal: External: OSx Exec
- Terminal: External: Windows Exec
- Terminal: Integrated > Env: Linux
- Terminal: Integrated > Env: OSx
- Terminal: Integrated > Env: Windows
- Telemetry: Telemetry Level
- Remote: Auto Forward Ports
- Remote: Auto Forward Ports Source
- Remote: Download Extensions Locally
- Remote: Extension Kind
- Remote: Local Port Host
- Remote: Restore Forwarded Ports
- Proxy: Proxy
- Proxy: Proxy Authorization
- Proxy: Proxy Strict SLL
- Proxy: Proxy Support
- Proxy: System Certificates
- Updates: Enable Windows Background Updates
- Security: Trust: Banner
- Security: Trust: Empty Window
- Security: Trust: Enabled
- Security: Trust: Startup Prompt
- Security: Trust: Untrusted Files

**Comment by joaomoreno** [comment]
While it's great to know there is specific demand for this, there's no value in keeping a list of settings that should be promoted as policies for now. Nor for a `Have more Settings as policies` issue. We know there is demand for this, but we are taking some time to decide where we want to go with this feature and how to position it... until then we won't promote any settings as policies.

Thanks for the issue anyway!
