### ISSUE TITLE
Caret returns view to its last position after scrolling with Ctrl+Up or Ctrl+Down.

### ISSUE THREAD

**Issue by datio** [Microsoft/vscode#15889]
- VSCode Version: Version 1.7.1
- OS Version: Ubuntu 16.04

This is an enhancement request for a setting to emulate the behavior of Sublime Text.

Reproduce:
1. Scroll a multi-line file until you can no longer see the cursor, using the 'Ctrl+Up' or 'Ctrl+Down' keys.
2. Hit 'Up' or 'Down'.
3. The view returns.

My muscle memory expects the cursor to follow the current view.

**Comment by alexandrudima** [comment]
It is possible to configure the keybindings to get this desired behaviour:

e.g.
```
    {
        "key": "ctrl+down",
        "command": "editorScroll",
        "args": {
            "to": "down",
            "by": "line",
            "revealCursor": true,
            "value": 3
        }
    }
```
