### ISSUE TITLE
vscode:// URLs not called when ctrl+clicking terminal output

### ISSUE THREAD

**Issue by vogelsgesang** [microsoft/vscode#158810]
Type: <b>Bug</b>

**Context**

I want to use vscode-URLs to directly drop into a debugging session. My script can be found at https://gist.github.com/vogelsgesang/d803377b8b143164961e08e58f5186c0

**Expected behavior**

When cmd-clicking this link from inside VSCode, I would expect to be dropped into the debugging session

<img width="1287" alt="Screenshot 2022-08-22 at 10 25 59" src="https://user-images.githubusercontent.com/6820896/185875277-3f40bd9a-ccdc-4ac5-8a66-d7a07bd137c9.png">

**Actual behavior**

Instead, the link gets opened in VS Code's search bar

<img width="904" alt="Screenshot 2022-08-22 at 10 27 17" src="https://user-images.githubusercontent.com/6820896/185875587-cd4839e3-cf70-45ef-a3c4-977a237847c6.png">

**Additional information**

I am sure the link itself is fine, because when I copy it from the console and paste it into Chrome's address bar, then VSCode opens my debugging session as expected.

Also see https://github.com/vadimcn/vscode-lldb/issues/755

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Modes:
Remote OS version: Linux x64 5.15.0-30-generic
Remote OS version: Linux x64 5.15.0-30-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|32.00GB (6.22GB free)|
|Process Argv|--crash-reporter-id 4660c967-d47d-475b-9e6c-050e56749010|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: avogels-lx|
|OS|Linux x64 5.15.0-30-generic|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (40 x 2200)|
|Memory (System)|62.50GB (33.73GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: avogels-lx|
|OS|Linux x64 5.15.0-30-generic|
|CPUs|Intel(R) Xeon(R) Silver 4114 CPU @ 2.20GHz (40 x 2200)|
|Memory (System)|62.50GB (33.73GB free)|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.19
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
llvm|RRe|0.1.1
vscode-clangd|llv|0.1.21
vscode-lldb|vad|1.7.4

</details>

**Comment by weinand** [comment]
@connor4312 since the url would need to open a JS/browser debug session, would the JavaScript Debugger Companion Extension be of help here?

**Comment by connor4312** [comment]
This is debugging with lldb, so it's not in the domain of js-debug

**Comment by Tyriar** [comment]
This is a request to essentially hook up the terminal link detector to whatever handles external custom protocol links. We may be able to just add vscode:// and vscode-insiders:// to the uri detection? This may need changes in the editor's link detector 🤔
