### ISSUE TITLE
Typing a character cannot trigger a search

### ISSUE THREAD

**Issue by 377960738** [microsoft/vscode#158866]
Type: <b>Bug</b>

1. Focus the mouse on the file list window area;
2. Try typing letters;

Now, you will notice that the file search mechanism is not triggered

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (12.13GB free)|
|Process Argv|--crash-reporter-id 3ac5d4aa-e0d9-4377-820c-b495552af323|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2903)|
|Memory (System)|7.76GB (2.01GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2903)|
|Memory (System)|7.76GB (2.01GB free)|
|VM|0%|
</details><details><summary>Extensions (134)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-icontheme-nomo-dark|be5|1.3.6
color-info|bie|0.7.0
vscode-firefox-debug|fir|2.9.8
codespaces|Git|1.10.2
autoconf|mae|0.1.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-language-pack-zh-hans|MS-|1.70.8170916
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.245.2
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
sublime-keybindings|ms-|4.0.10
php-docblocker|nei|2.7.0
material-icon-theme|PKi|4.20.0
vscode-nginx|sha|0.6.0
vscode-icons|vsc|11.15.0
emoji|Wsc|0.0.4
JavaScriptSnippets|xab|1.8.0
cursor-align|yo1|1.1.0
cloudmusic|YXL|9.13.3
vscode-sqlite|ale|0.14.1
laravel-extra-intellisense|ami|0.6.2
preview-mp4|ana|0.0.1
z-reader|aoo|1.1.7
vscode-zipfs|arc|3.0.0
gitstash|art|5.1.0
vscode-intelephense-client|bme|1.8.2
path-intellisense|chr|2.8.1
laravel-goto-view|cod|1.3.7
doxdocgen|csc|1.4.0
vscode-office|cwe|2.6.6
vscode-redis-client|cwe|5.7.2
dart-code|Dar|3.46.1
flutter|Dar|3.46.0
vscode-markdownlint|Dav|0.47.0
tp5-snippet|dax|1.0.0
vscode-eslint|dba|2.2.6
phptools-vscode|DEV|1.13.10324
githistory|don|0.6.19
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.8.0
tortoise-svn|fan|0.1.1
code-runner|for|0.11.8
vscode-lombok|Gab|1.0.1
anes|gam|0.0.2
vscode-pull-request-github|Git|0.48.1
go|gol|0.35.2
gc-excelviewer|Gra|4.2.55
todo-tree|Gru|0.0.215
google-translate|han|1.2.6
openvpn|idl|0.2.3
composer|ika|0.8.0
comment-translate|int|2.2.4
form-generator-plugin|jak|1.0.4
cmake-language-support-vscode|jos|0.0.4
twig-language|jun|0.10.10
vscode-colorize|kam|0.11.1
git-emoji-zh|mai|1.1.9
json-to-go|mar|0.3.1
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
gitignore|mic|1.0.1
mp-rest-client-generator-vscode-ext|Mic|0.1.2
mp-starter-vscode-ext|Mic|0.2.8
vscode-microprofile-pack|Mic|0.1.3
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
mongodb-vscode|mon|0.9.3
vscode-docker|ms-|1.22.1
vscode-language-pack-zh-hans|MS-|1.70.8170916
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.5
hexeditor|ms-|1.9.8
sqltools|mtx|0.24.0
sqltools-driver-pg|mtx|0.3.0
sqltools-driver-sqlite|mtx|0.3.0
symfony-code-snippets|nad|1.2.8
laravel-goto-components|nao|1.2.0
php-docblocker|nei|2.7.0
vscode-zhihu|niu|0.5.1
vetur|oct|0.36.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
vscode-print|pdc|0.9.28
laravel-jump-controller|pgl|0.0.29
csv-to-table|php|1.4.0
vscode-boot-dev-pack|Piv|0.1.0
vscode-concourse|Piv|1.38.0
vscode-manifest-yaml|Piv|1.38.0
vscode-spring-boot|Piv|1.38.0
minapp-vscode|qiu|2.4.8
vscode-thunder-client|ran|1.18.7
vscode-flexbox-picker|Rax|0.0.1
fabric8-analytics|red|0.3.6
java|red|1.9.0
vscode-commons|red|0.0.6
vscode-microprofile|red|0.5.0
vscode-quarkus|red|1.11.0
vscode-xml|red|0.21.0
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.17.2
devuihelper|ssp|4.4.1
pcinfobar|tak|0.0.1
cmake|twx|0.0.17
vscode-counter|uct|3.0.5
intellicode-api-usage-examples|Vis|0.2.1
vscodeintellicode|Vis|1.2.23
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0
vscode-spring-boot-dashboard|vsc|0.6.0
vscode-spring-initializr|vsc|0.10.1
volar|Vue|0.40.1
vscode-typescript-vue-plugin|Vue|0.40.1
jar-viewer|wma|1.1.1
better-align|wwm|1.1.6
corgi-lowcode|xlu|0.0.4
local-history|xyz|1.8.1
markdown-all-in-one|yzh|3.4.3
json|Zai|2.0.2
svn-helper|Zlo|1.1.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30552240

```

</details>

**Comment by 377960738** [comment]
![image](https://user-images.githubusercontent.com/25890436/186126864-013ca3ee-5277-4c4a-b714-4316a7a65346.png)

**Comment by gjsjohnmurray** [comment]
Starting with 1.70 you must first press Ctrl+F or Cmd+F on   MacOS.

**Comment by 377960738** [comment]
thinks
