### ISSUE TITLE
Outline is broken in the toolbar actions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#158855]
Testing #158636

![image](https://user-images.githubusercontent.com/10746682/186096801-f75bde66-78cc-40d4-926c-a6820554d587.png)

**Comment by mjbvz** [comment]
Sorry but what is the issue?

**Comment by mjbvz** [comment]
Thanks. Also moving to September because I want to fix this by moving the action bar outside of the main list

**Comment by justschen** [comment]
@mjbvz @sandy081 I wasn't able to repro in insiders - how are you interacting with it (by clicking or with keyboard)?

**Comment by sandy081** [comment]
Using keyboard, by TAB

**Comment by rzhao271** [comment]
I accidentally found a way to verify the issue.
If one presses Ctrl+. on a private class field, the code action widget comes up with the "Learn more" link.
