### ISSUE TITLE
Test: Terminal inactive selection background

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158828]
Refs: #156985

- [x] macOS @isidorn
- [x] linux @alexr00
- [x] windows @dbaeumer 

Complexity: 2

Authors: @meganrogge @Tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158828%0A%0A&assignees=Tyriar,meganrogge)

---

An inaction (unfocused) selection background color is now supported in the terminal, similar to the editor. Please test:

- The feature works with all values of `terminal.integrated.gpuAcceleration`
- The selection background color works as expected (same as in the editor) on all built-in themes
- Setting `terminal.inactiveSelectionBackground` in `workbench.colorCustomizations` works with both opaque (`#rrggbb`) and transparent (`#rrggbbaa`) colors

**Comment by alexr00** [comment]
Interestingly, my terminal selection is lost when I change themes. Not sure if that's a bug though.

**Comment by Tyriar** [comment]
@alexr00 good polish change we could make 👍
