### ISSUE TITLE
Tooltip delay ? Does anyone sometimes have trouble to grab the tip with the mouse ?

### ISSUE THREAD

**Issue by nicolasmol** [microsoft/vscode#158894]
Hi
As requested by the Flutter team: https://github.com/Dart-Code/Dart-Code/issues/4113#issuecomment-1222671301

I looked briefly on this board if I'm alone to feel bothered by this little inconvenience but I found nothing and I am surprised.

I often find it difficult to catch the tooltip as you can see in this capture:
![Peek 22-08-2022 16-15](https://user-images.githubusercontent.com/61077647/185970794-4d8b4aa7-8d04-478a-899d-aa57cfeeb13d.gif)
Wouldn't it be wise to have a few milliseconds delay when moving the cursor out of box before closing it?
There is a delay setting for "displaying" the tooltip...so why not one for "hiding" too ?

NOTE: maintaining ALT does nothing here (Linux mint)

**Comment by alexdima** [comment]
Done via https://github.com/microsoft/vscode/pull/161407
