### ISSUE TITLE
Terminal: Underline is not continuous

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#158868]
Testing #158827

Version: 1.71.0-insider
Commit: bd6107301dc9a6200bd8d4f64a9b198438b3f1d6
Date: 2022-08-23T05:19:02.563Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

- set setting terminal.integrated.gpuAcceleration: on
- in a terminal type: `echo -e "\x1b[4:2m"  # double underline` followed by `echo -e "\x1b[4:3m"  # curly underline` and a new line

![image](https://user-images.githubusercontent.com/6461412/186127623-de5f87fb-9463-49cc-9606-a97e55595c00.png)

Especially under the `w` there's a lot of space so I would say it can't be antialiasing that interferes

**Comment by Tyriar** [comment]
Good find, the stroke seems oddly large on the `w` here.

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4059

**Comment by aeschli** [comment]
Looks better on the Mac now. 
![image](https://user-images.githubusercontent.com/6461412/192796126-549cfceb-b603-42d0-bed6-b35acea2df95.png)
