### ISSUE TITLE
The window is not responding

### ISSUE THREAD

**Issue by brianjmurrell** [microsoft/vscode#158804]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.18.16-200.fc36.x86_64

Steps to Reproduce:

1. Start VS Code with extensions disabled (in my case I have about 10 workspaces open): `$ code --disable-extensions`
2. Wait for workspaces to open
3. On particular workspace that is causing Code to go unresponsive click on Source Control
4. Observe that the window is now unresponsive
5. Wait a few (10s?) of seconds for "The window is not responding" dialog
6. Click _Close_ button
7. All VS Code workspaces close

Selecting _Souce Control_ in the specific workspace only makes that workspace unresponsive and all other workspace windows continue to operate as usual.

This of course however is making VS Code quite unusable for me as the affected workspace is my most used workspace, but a huge amount.

**Comment by brianjmurrell** [comment]
Is there any way we can make progress on this?  This issue is not just a minor inconvenience.  It makes VS Code **completely** unusable for me.

I am happy to provide whatever info is needed or run tests/debug/etc.  I just don't know what else is needed.

**Comment by lszomoru** [comment]
@deepak1556, is there any information that we can collect in this case to investigate the problem? Thanks!
