### ISSUE TITLE
Shift+Tab from toolbar is running the code action

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#158857]
Testing #158636

https://user-images.githubusercontent.com/10746682/186101386-003cf9a6-a355-40d0-a79a-414df61735d9.mp4

**Comment by mjbvz** [comment]
@justschen Do you remember why we added the `shift + tab` keybinding? The suggest widget  uses it to accept suggestions in alternative mode, not normal suggestions

**Comment by justschen** [comment]
@mjbvz I think I might have accidentally added it in when templating `registerEditorCommand` functions. It has the secondary keybindings, but I think can just get removed entirely.

https://github.com/microsoft/vscode/blob/f00fde0f2401b6cab737136b3622ff4aa7e6db2f/src/vs/editor/contrib/codeAction/browser/codeActionCommands.ts#L563


``` typescript
registerEditorCommand(new CodeActionContribution({
	id: 'onEnterSelectCodeAction',
	precondition: Context.Visible,
	handler(x) {
		x.selectedOption();
	},
	kbOpts: {
		weight: weight + 100000,
		primary: KeyCode.Enter,
		secondary: [KeyMod.Shift | KeyCode.Tab],
	}
}));
