### ISSUE TITLE
Terminal inactive selection stronger than active for Gpu acceleration: Canvas

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#158896]
Testing #158828

1. VS Code insiders, set `"terminal.integrated.gpuAcceleration": "canvas"`
2. Notice how the inactive selection colour is stronger than the active selection colour 🐛 

I can only reproduce this with "canvas", all other gpu acceleration options work fine.

Terminal focused

![Screenshot 2022-08-23 at 15 15 00](https://user-images.githubusercontent.com/1926584/186167474-c64a4864-f2d5-4fb2-974e-0f429794d4d1.png)

Terminal not focused

![Screenshot 2022-08-23 at 15 15 31](https://user-images.githubusercontent.com/1926584/186167559-424dd57e-8b62-42f5-bbf3-4ab4b2022e6c.png)

**Comment by Tyriar** [comment]
Upstream: https://github.com/xtermjs/xterm.js/issues/4056
