### ISSUE TITLE
visual studio code...cannot open vs code....Unable to write program user data.......A system error occurred (EPERM: operation not permitted, mkdir 'C:\Users\ ......Please make sure the following directories are writeable:

### ISSUE THREAD

**Issue by jaytheblogger** [microsoft/vscode#158884]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by gjsjohnmurray** [comment]
Is this a new installation, or one that used to work OK?

Did you install from the Windows User Installer (the default download) or from the System Installer?

If the User Installer did you simply run it, or use "Run as administrator"?

What Windows version?
