### ISSUE TITLE
Screen cheese when using Ctrl+F filter in breadcrumb dropdown within file

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#158824]
Type: <b>Bug</b>

1. Open a file for which a DocumentSymbolProvider will return some items, for example settings.json
2. Click on the filename in the breadcrumb, then type Ctrl/Cmd+F. The list filter widget looks OK, though it hides the first filename in the list (#158583 ought to help with this once merged).
3. Do the same but one item to the right in the breadcrumb. The filter widget is transparent.

![junk](https://user-images.githubusercontent.com/6726799/186025119-5ecd821a-ea2f-4526-b9aa-94a2725bf1f5.gif)

VS Code version: Code - Insiders 1.71.0-insider (235a92a3693176fbf9af16ec5b829c458a1d682f, 2022-08-22T05:16:19.478Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by joaomoreno** [comment]
Easier steps:

1. <kbd>Ctrl F</kbd> on an outline breadcrumb

**Comment by mjbvz** [comment]
I still see this. It looks like the background of the find widget gets removed, but the contents still scroll up out of the breadcrumbs widget

**Comment by joaomoreno** [comment]
@mjbvz Did you test this in dev? Because we still didn't get an Insiders build with the fix.
