### ISSUE TITLE
"Dynamic-Link Library with exports (DLL)" project template isn't tagged in MSVS

### ISSUE THREAD

**Issue by TishSerg** [microsoft/vscode#158803]
- VS Version: 17.3.1
- OS Version: Windows 10 x64 22H2 19045.1889

Hello. This issue isn't about VisualStudio Code, but about Visual Studio. I couldn't find where to post this issue, so I post it here. Sorry for posting it here. I believe the VSCode team can forward this report to the MSVS team :)

Issue:
The `Dynamic-Link Library with exports (DLL)` project template isn't tagged with any tag:
![image](https://user-images.githubusercontent.com/11420785/185989360-7fce213e-972c-4737-94d0-9565c5f157a8.png)

Because of that it isn't shown if any of template filters are applied. I didn't even know about this template because it wasn't shown when I applied `C++` language filter. So I had to use `Dynamic-Link Library (DLL)` that is tagged properly:
![image](https://user-images.githubusercontent.com/11420785/185990125-c265cd2f-7b9c-4fe8-9490-bc197193d887.png)

Solution:
The `Dynamic-Link Library with exports (DLL)` project template must be tagged the same way as the `Dynamic-Link Library (DLL)` template is tagged.

I conducted some investigation and found the place where the fix has to be done:
Assembly `...\Common7\IDE\PrivateAssemblies\Microsoft.VisualStudio.TemplateProviders.Implementation.dll` (version 17.3.32804.24) contains a resource `Microsoft.VisualStudio.TemplateProviders.Implementation.TemplateTags.TagProvider.project-metadata.json`. This JSON contains entry for `Dynamic-Link Library (DLL)` template: 
![image](https://user-images.githubusercontent.com/11420785/185992457-c7094667-43d3-46e6-b28d-6a30f319d62e.png)

.. but that JSON lacks an entry for the `Dynamic-Link Library with exports (DLL)` template (Template ID `Microsoft.VisualC.Project.Windows.DllExports`)! 
Add that entry and the problem is fixed!

**Comment by mjbvz** [comment]
Closing as not about vs code
