### ISSUE TITLE
code colorization incorrect for SQL

### ISSUE THREAD

**Issue by gbritton1** [Microsoft/vscode#15886]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.2|
|code-runner|formulahendry|0.5.1|
|mssql|ms-mssql|0.1.5|
|PowerShell|ms-vscode|0.7.2|
|vscode-sql-beautify|sensourceinc|0.0.3|

---

Steps to Reproduce:

1. Open a new file, change language to SQL
2. Enter the following line:

create table #foo(a int, b char)

4. from the hash (number sign) on, the text is presented in green, as if were a comment. but in SQL, a hash does not begin a comment.  Comments either begin with '-- ' (single line) or '/*' (multiline)

**Comment by aeschli** [comment]
This issue was moved to textmate/sql.tmbundle#20
