### ISSUE TITLE
@aeschli

### ISSUE THREAD

**Issue by HemantSingh23** [microsoft/vscode#158877]
1. The code
![Screenshot 2020-10-15 175401](https://user-images.githubusercontent.com/65482473/96123506-88908c80-0f10-11eb-9a88-14b40022d4ad.png)
2.  I selected some CSS code under the <style> tag in the HTML code
![Screenshot 2020-10-15 175503](https://user-images.githubusercontent.com/65482473/96123656-c55c8380-0f10-11eb-9089-d2e16867308c.png)
3. As I pressed ctrl+/ to comment out it uses the HTML comment tag() instead of CSS comment tag(/* */)
![Screenshot 2020-10-15 175632](https://user-images.githubusercontent.com/65482473/96123740-e4f3ac00-0f10-11eb-9301-b968dcd938a2.png)
4. This is the manually typed comment of the same code
![Screenshot 2020-10-15 175950](https://user-images.githubusercontent.com/65482473/96125081-474cac80-0f11-11eb-8864-beedec48c731.png)

Note: The ctrl+/ is working in an individual .css file. I have also noticed that the shortcut also works in CSS code, embedded in an HTML code. But in my VS code, this process isn't working(as shown above). I will be thankful to know if it is a bug or a settings issue in my VS code.

_Originally posted by @hDmtP in https://github.com/microsoft/vscode/issues/108702#issuecomment-709293402_

**Comment by HemantSingh23** [comment]
please  tell me the solution  of the above problem  earlier  mentioned  by @hDmtP . same problem  for me

css code is not commenting in html file in  vs code when we use ctrl+/ .
please @hDmtP help me if you have found  the solution

**Comment by HemantSingh23** [comment]
please tell me the solution of the above problem earlier mentioned by @hDmtP . same problem for me

css code is not commenting in html file in vs code when we use ctrl+/ .
please @hDmtP help me if you have found the solution

**Comment by HemantSingh23** [comment]
@hDmtP https://github.com/hDmtP please help

**Comment by aeschli** [comment]
This works for me. What is the editor language in the status bat. is it `HTML`?
Does this reproduce with all extensions disabled? There are extensions that replace the built-in HTML functionality.

**Comment by HemantSingh23** [comment]
@aeschli yeah it works for me when i disabled all the extensions but if i enabled all extensions again then problem comes again.

**Comment by HemantSingh23** [comment]
now i have found  the problem.
thanks @aeschli
