### ISSUE TITLE
Cheese in current line decoration, in embedded editors

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#15880]
![image](https://cloud.githubusercontent.com/assets/22350/20521377/4baff19c-b0ab-11e6-8f60-5b276bb83b8b.png)

**Comment by joaomoreno** [comment]
@rebornix Don't forget to add the `bug` label, if it's a confirmed bug, so it gets verified during the endgame.

**Comment by rebornix** [comment]
@joaomoreno thanks for the info :)
