### ISSUE TITLE
ConfigurationService#lookup is responsible for 25% of startup time

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15884]
In the built version of vscode insiders do this:

* close all editors
* start profiling
* reload 
* stop profiling

<img width="935" alt="screen shot 2016-11-22 at 14 32 31" src="https://cloud.githubusercontent.com/assets/1794099/20525624/90a79948-b0c0-11e6-9109-4cafbc225a27.png">

🐌 You will find that ~25% of the time is spent doing `lookup`-calls. This is for sure is triggered by [`getEntries`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/configuration/common/configuration.ts#L48) but there seems no other way to get all values (effective, default, user, workspace) for all configuration keys. 

[CPU-20161122T143305.cpuprofile.zip](https://github.com/Microsoft/vscode/files/606481/CPU-20161122T143305.cpuprofile.zip)

**Comment by jrieken** [comment]
related to https://github.com/Microsoft/vscode/issues/15455

**Comment by bpasero** [comment]
@jrieken hm, is this with recent changes to the config service or does it reproduce in stable too?

**Comment by jrieken** [comment]
Only insiders, before we didn't need *all* configuration values but just the simple value-tree. Now that we have `inspect` we need all values.

**Comment by jrieken** [comment]
But then I can also find references to `lookup` all over our codebase

**Comment by bpasero** [comment]
@jrieken I see slowness, but only in the order of 7%. I wonder if this is dependent on:
* what viewlet was visible when you reloaded (if any)
* the contents of `settings.json` you have

**Comment by bpasero** [comment]
This seems to be coming from the newly introduced [`addToValueTree`](https://github.com/Microsoft/vscode/commit/dd407168ea53772e1439789adae8f1569c981621)

![image](https://cloud.githubusercontent.com/assets/900690/20530983/81dfc95c-b0d5-11e6-91f3-c467cae704a4.png)

@aeschli can you please check if the thing you added can be improved?

I still think that there is another condition in @jrieken setup that makes this worse compared to what I see.

**Comment by aeschli** [comment]
`addToValueTree` is just a rename from `flatten`. No code change from my side.

Each invocation of `lookup` causes the default values tree to be recreated, same for values tree the user settings.
And `lookup` is invoked for every key...

**Comment by bpasero** [comment]
Looks like a perf regression from https://github.com/Microsoft/vscode/commit/e87ab932b6c8836416ed382e048ea5d0523dc649

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/15884#issuecomment-262446958 - Yes, I already said that, but I don't have other API to get all values for all keys. 

re https://github.com/Microsoft/vscode/issues/15884#issuecomment-262282101 - The setup is insiders in which loading JavaScript code is a lot faster because things are bundled and minified. You don't get representative numbers when measuring `script/code.sh`

**Comment by bpasero** [comment]
@jrieken I always test in both Insiders and code.sh, I simply attached from code.sh because it is easier to read.

**Comment by jrieken** [comment]
Consistently slow. Make sure to wait a little when the workbench is drawn because only when the extension host has started the configuration is read

![screen shot 2016-11-23 at 12 58 27](https://cloud.githubusercontent.com/assets/1794099/20561018/8ef87dda-b17c-11e6-8056-3db6d02171f5.png)
