### ISSUE TITLE
Git branches don't refresh when you change remote url

### ISSUE THREAD

**Issue by msschambach** [Microsoft/vscode#15883]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.0.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-twig-pack|bajdzis|1.0.0|
|python|donjayamanne|0.5.2|
|Angular2|johnpapa|1.0.2|
|vscode-todo-parser|minhthai|1.8.3|
|vscode-icons|robertohuertasm|4.0.2|
|sass-indented|robinbentley|1.2.1|

---

Steps to Reproduce:

1. Create a project with a git repository.
2. Push your repository to remote (github or bitbucket e.t.c) 
3 . Change remote url e.g `git remote set-url origin https://github.com/USERNAME/OTHERREPOSITORY.git`
4. Check branches on vs code. (they will not have refreshed)
5. Restart vs code and repeat step 4. (they still will not have refreshed)

**Comment by joaomoreno** [comment]
You must run `git fetch` to be able to fetch all the remote branches from your new remote.

**Comment by msschambach** [comment]
Just ran `git fetch` and restarted vscode but it hasn't really changed anything.

**Comment by joaomoreno** [comment]
What branches do you get when running `git branch -r`?

**Comment by chrisDeFouRire** [comment]
fwiw `git fetch -p` did it for me
