### ISSUE TITLE
Copy Paste Tabulations

### ISSUE THREAD

**Issue by SkywalkerD99** [microsoft/vscode#158882]
Type: <b>Bug</b>

Hi there.
Here's the problem: when copy-pasting multiple lines that have different indentations, only the first line is indented to the required position. After pasting, it is required to hit [tab] possibly multiple times to set things right.
Cheers.

VS Code version: Code - Insiders 1.71.0-insider (28f604dec81b609dd7e69362585f7a99d4c48f88, 2022-08-19T05:18:45.149Z)
OS version: Linux x64 5.15.0-46-generic
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz (4 x 2883)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|5.67GB (0.87GB free)|
|Process Argv|--unity-launch --crash-reporter-id c556821d-e56a-481b-9e8c-fb2c5ccf6d45|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (88)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
semantic-ui-snippets|4tr|0.0.7
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
p5js-snippets|aci|0.0.6
pascal|ale|9.5.1
pascal-formatter|ale|2.6.1
bootstrap5-vscode|Anb|0.3.0
ng-template|Ang|14.1.0
pascal-language-basics|Ans|0.1.10
emojisense|bie|0.9.1
vscode-intelephense-client|bme|1.8.2
quill-icons|cdo|0.0.2
visubezier|chr|1.4.0
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
laravel-blade|cjh|1.1.2
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.15
dart-code|Dar|3.46.1
flutter|Dar|3.46.0
vscode-eslint|dba|2.2.6
npm-browser|den|1.1.3
jquerysnippets|don|0.0.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.8.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
kotlin|fwc|0.2.26
vscode-lombok|Gab|1.0.1
vscode-pull-request-github|Git|0.49.2022082309
gitlab-workflow|Git|3.48.1
go|gol|0.35.2
bootstrap5-snippets|Han|1.2.5
vscode-cdnjs|Jak|0.19.0
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.15.19
Angular2|joh|13.0.0
thymeleaf|juh|1.0.5
Kotlin|mat|1.7.1
Angular-BeastCode|Mik|10.0.3
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.30
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.245.2
remote-ssh|ms-|0.84.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.11.26
cpptools|ms-|1.11.5
cpptools-extension-pack|ms-|1.2.0
vscode-react-native|msj|1.9.2
indent-rainbow|ode|8.3.1
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
subtitles-editor|pep|1.1.7
vscode-spring-boot|Piv|1.38.0
material-icon-theme|PKi|4.20.0
fabric8-analytics|red|0.3.6
java|red|1.8.0
vscode-commons|red|0.0.6
vscode-xml|red|0.21.0
addDocComments|ste|0.0.8
vslook|sud|0.3.1
open-in-browser|tec|2.0.0
pdf|tom|1.2.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.23
vscode-arduino|vsc|0.4.12
vscode-java-debug|vsc|0.43.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.0
vscode-java-test|vsc|0.36.0
vscode-maven|vsc|0.37.0
vscode-spring-boot-dashboard|vsc|0.6.0
vscode-spring-initializr|vsc|0.10.1
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.497
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.27.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.11

(20 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonvspyt551:30291412
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52cf:30549188

```

</details>

**Comment by rebornix** [comment]
Currently the auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.

**Comment by SkywalkerD99** [comment]
Thank you for your time.
