### ISSUE TITLE
Test: Experimental fish shell integration

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158831]
Refs: #143769

- [x] anyOS @IanMatthewHuff (Linux or macOS)

Complexity: 3

Authors: @meganrogge @Tyriar

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158831%0A%0A&assignees=Tyriar,meganrogge)

---

Using the instructions to setup [here](https://github.com/microsoft/vscode-docs/pull/5560/files), test some of the functionality of shell integration in fish on Linux or macOS. See https://code.visualstudio.com/docs/terminal/shell-integration#_features for a list of features.

**Comment by IanMatthewHuff** [comment]
Initially I missed the tip for using `code-insiders` instead of `code` in the manual `fish.config`. But after sorting that small hitch out I was able to use fish for all the features listed in the shell integration docs. Looks good!
