### ISSUE TITLE
Test: Terminal blurriness fix

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#158833]
Refs: #85154

- [ ] macOS @mjbvz (a high DPI display)
- [x] windows @cwebster-99 (ideally a standard DPI display)

Complexity: 3
Roles: Designer

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23158833%0A%0A&assignees=Tyriar)

---

A long standing bug with the canvas and webgl renderers has been fixed in https://github.com/microsoft/vscode/issues/85154. What was happening was due to a rounding error the canvas could have been 1 pixel too large or too small which ended up stretching the texture to the screen, resulting in blurriness in 1 or both dimensions. This typically only happened when the `window.devicePixelRatio` was not a round number.

Please test using various font sizes, fonts and zoom levels and ensure that the text always looks "crisp", use gpuAcceleration=auto when testing as that's the default

**Comment by mjbvz** [comment]
Looks good! Tested on MacBook Pro's screen 

Only issue I ran into is that the terminal doesn't like crazy big font sizes on high dpi screens :) 

<img width="1357" alt="Screen Shot 2022-08-23 at 11 26 29 AM" src="https://user-images.githubusercontent.com/12821956/186235843-61880228-5463-4ee4-b758-5441a4637d00.png">
