### ISSUE TITLE
Bad terminal rendering with large font size on high dpi screen

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#158961]
Testing #158833

1. On a high dpi screen (tested on MacBook Pro)
2. Set `"terminal.integrated.fontSize": 60`

**bug**

This renders incorrectly (and slowly) on the high dpi screen:

<img width="1383" alt="Screen Shot 2022-08-23 at 11 30 13 AM" src="https://user-images.githubusercontent.com/12821956/186236407-310d7101-bc3c-4bf8-ab33-c958b81273b2.png">

It renders as expected on a 1x res screen:

![Screen Shot 2022-08-23 at 11 30 15 AM](https://user-images.githubusercontent.com/12821956/186236445-f1599b69-ee89-4b0a-9a78-66dfc167b29c.png)

**Comment by Tyriar** [comment]
I think you're hitting an incarnation of https://github.com/microsoft/vscode/issues/158876, where you're filling the texture atlas to its capacity in a single viewport so some glyphs get overwritten.

/duplicate
