### ISSUE TITLE
Settings Modified Elsewhere indicator hover content overflows

### ISSUE THREAD

**Issue by mahmoudsalah1993** [microsoft/vscode#158921]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: MacOS Monterey 12.5, chrome v 104.0.5112.101

Steps to Reproduce:

1. Override language specific setting e.g. `editor.formatOnSave` for a large number of languages
2. In Settings Editor, Check `editor.formatOnSave` and hover on `Modified Elsewhere` to show the hover view.

Expected:
All the overridden languages are visible and overflowing content can be scrolled to.

Actual:
The hover view is clipped at the screen height and not all languages are visible unless zooming out.

![image](https://user-images.githubusercontent.com/13228044/186187984-2187a1d8-4abd-4fa4-825e-fef0fb211a03.png)

**Comment by sbatten** [comment]
@rzhao271 this is working now, but there is some room for improvement as it does not use the maximum available space and sometimes has weird behavior with the beak. See below where the hovered text is just below the top of the widget which has a beak pointing down.

<img width="272" alt="image" src="https://user-images.githubusercontent.com/6561887/198133242-8595a447-4c68-4b1a-b959-ce175a8fb27e.png">
