### ISSUE TITLE
Uncommited changes not coming with me for `vscode-wasm` when cloning locally and opening on desktop

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#158968]
Testing #158798

![image](https://user-images.githubusercontent.com/13199757/186241516-87f3c113-584e-4486-946c-9b0ae1bf7566.png)

**Comment by joyceerhl** [comment]
Are you already signed into Edit Sessions on desktop when this happens?

**Comment by karrtikr** [comment]
Yes:

![image](https://user-images.githubusercontent.com/13199757/186264410-b648af7d-d472-4703-a7d3-dce610e1fdef.png)

**Comment by joyceerhl** [comment]
Can you share the contents of the Edit Sessions log please?

**Comment by karrtikr** [comment]
Weird, I'm unable to reproduce the issue anymore, I guess you can close this.
