### ISSUE TITLE
backslashes in existing workspace paths are not converted 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#158905]
Testing #158247

I had an old workspace file with folder paths containing backslashes:
<img width="390" alt="CleanShot 2022-08-23 at 15 47 41@2x" src="https://user-images.githubusercontent.com/1898161/186174959-514f14e7-1f0c-474e-a463-c09d6fd684ee.png">

After adding another folder the new path is using forward slashes but the old paths weren't converted:
<img width="435" alt="CleanShot 2022-08-23 at 15 46 18@2x" src="https://user-images.githubusercontent.com/1898161/186174812-5631cefd-99a0-47db-ac28-9efeed941ec9.png">

from the test's description I got the impression that old paths with backslashes are converted.

**Comment by bpasero** [comment]
How did you add the path? If you edit the workspace file directly, no conversion will take place.

**Comment by weinand** [comment]
No, I added the folder with the "Add Folder to Workspace" action.

**Comment by bpasero** [comment]
Ok, looks like my knowledge around this code was not up to date: we seem to be doing a minimal edit in this case, i.e. just adding the folder to the end of the file.

I think this is not a big deal though and I am hesitant to change this behaviour, only for the sake of converting to slashes. Will monitor if other users complain and then reconsider.
