### ISSUE TITLE
Refuses to enter full-screen

### ISSUE THREAD

**Issue by tejasmanohar** [Microsoft/vscode#15898]
- VSCode Version: 1.7.1
- OS Version: OS X 10.11.16

I started using VSCode yesterday and today, the full screen stopped working. Now, when I press the green icon or cmd+shift+f, VSCode window just shakes (seemingly so... looks like the status bar on the bottom just gets re-rendered) and refuses to enter full screen. This one sounds difficult to reproduce... is there somewhere I can get logs to show you all?

**Comment by bpasero** [comment]
@tejasmanohar can you share some video/screenshots how this behaves?

**Comment by tejasmanohar** [comment]
I wish, but it has stopped again :(

**Comment by tejasmanohar** [comment]
Closing for now. Will re-open with video if it restarts.
