### ISSUE TITLE
Test task reconnection: expected behavior on reload of killed task?

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#158964]
Testing #158787

repro:
1. run the `VS Code - Build` task
2. use CTRL+D to stop both tasks (should say "Terminal will be reused by tasks, press any key to close it.")
3. reload the window
4. tasks start running again ❓ 

Not too sure what the expected behavior should be on this, but it thought that it would reload at the same state (task stopped or not even there).

**Comment by meganrogge** [comment]
Good find - the tasks should not be re-run in this case and need to be removed from persistent tasks

**Comment by meganrogge** [comment]
@andreamah I can't reproduce this anymore - pls reopen this if you can
