### ISSUE TITLE
Weird rendering of `_`

### ISSUE THREAD

**Issue by TylerLeonhardt-alt** [microsoft/vscode#158975]
Testing #158827

I just type underscore `_` and get this weird black background?:

![image](https://user-images.githubusercontent.com/98423974/186253501-2fa68378-c446-4d23-a4d1-984e99a7c89f.png)

And if I type multiple underscores this is what it looks like:
![image](https://user-images.githubusercontent.com/98423974/186253536-5aa272ea-2f7a-4dc7-8aa3-582d1c8100fb.png)

I have no terminal specific settings.

alt account of @TylerLeonhardt when using Linux

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/158497

@TylerLeonhardt-alt could you post the font you were using on that issue?

**Comment by TylerLeonhardt** [comment]
I don't have any font set so I guess:
```
"editor.fontFamily": "'Droid Sans Mono', 'monospace', monospace"
```
