### ISSUE TITLE
mp4 video but no audio in extension webview

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#158972]
Testing #158759

- Run this webview sample which adds an mp4 in a video element https://github.com/microsoft/vscode-extension-samples/tree/roblou/mp4/webpack-sample
- See the video with no audio

**Comment by deepak1556** [comment]
MP4 usually contain AAC encoded audio stream which we don't support, if the MP4 file has audio streams encoded with codecs from the list https://github.com/microsoft/vscode/pull/158486#issue-1343087439 we support then audio should work.

You can inspect the audio codec in the file using the following command,

```
ffmpeg -i <path-to-file> -hide_banner
```

Here is a sample [mp4](https://user-images.githubusercontent.com/964386/186390788-20c9470b-3cee-41ad-a0db-e149d6e9dd2e.mp4) file that uses vorbis codec for the audio stream and works with the above webview sample.

**Comment by deepak1556** [comment]
@isidorn we should make sure to highlight the supported codecs in the release notes.

**Comment by isidorn** [comment]
@deepak1556 good point. I will write something today so you can review it.

**Comment by roblourens** [comment]
Oh, thanks that makes sense. That file still doesn't work in a notebook though: 
<img width="475" alt="image" src="https://user-images.githubusercontent.com/323878/186470840-3b4abc12-65d8-4699-9725-b6580d4c1ade.png">

any idea why?

**Comment by roblourens** [comment]
Hm, maybe it is actually something in the webview, any idea if this is a CORS thing @mjbvz?

<img width="370" alt="image" src="https://user-images.githubusercontent.com/323878/186471592-b1d374eb-e944-46e5-b0af-c94a99a69d43.png">

**Comment by mjbvz** [comment]
@roblourens Did you make sure the file is included in the webview's localResourceRoots? 401 suggests that it's being blocked for security reasons

**Comment by roblourens** [comment]
It's not, I'm just running code in a notebook. I guess that means we just can't support videos in notebook outputs? Do you know why it works for audio files but not videos?

**Comment by mjbvz** [comment]
@roblourens  Try with a file in the workspace. We block notebooks from loading resources (both images and videos) outside of the current workspace

I confirmed that this seems to be working for a local file:

![Screen Shot 2022-08-24 at 1 35 29 PM](https://user-images.githubusercontent.com/12821956/186518338-55c192b1-9a4c-4f34-b027-ede8878eaaa2.png)

**Comment by roblourens** [comment]
I see that, thanks @mjbvz. With your sample mp4 @deepak1556, I actually still don't get audio for that file, in the webview sample or in a notebook.

**Comment by roblourens** [comment]
Well actually ffmpeg says your file's audio is AAC, `  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 123 kb/s (default)` I wonder whether github reencoded it, anyway if it works for you I think we're good then

**Comment by deepak1556** [comment]
@roblourens github did indeed reencode the file 🤯I tried to check the creation time to confirm it using `ffprobe` but that just gave back empty result. Back to original issue, you can try the following command to get the vorbis codec encoded for the audio stream from the attached file above.

```
ffmpeg -i <path-to-mp4-file> -hide_banner -c:v copy -c:a libvorbis -f mp4 <output-file-name>
```
