### ISSUE TITLE
Duplicated character when typing accented character

### ISSUE THREAD

**Issue by alexlur** [Microsoft/vscode#15896]
- VSCode Version: Insiders Build 2016-11-22T07:03:01.551Z
- OS Version: OS X 10.12.2 (16C41b)

Steps to Reproduce:

1. Switch to English (U.S.) keyboard
2. Press `Opt-E`, `E`, `R`.

Expected Result:

Key  | Opt-E |   E   |   R
-----|:------|:-----|:----:
Text |   ´      |   é    |   ér

Actual Result:

Key  | Opt-E |   E   |   R
-----|:------|:-----|:----:
Text |   ´      |   é    |   éér

**Comment by rebornix** [comment]
Dup of #16017. Already fixed in Insider.
