### ISSUE TITLE
Merge Editor: Conflict navigation seems broken

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#158901]
Testing #158819

* Clone https://github.com/hediet/diff-merge-dataset
* Use the `Load Merge Editor State From Folder` command and select the `merges/demo1` folder
* Select `result` in the quick pick
* It looks like the file has 4 conflict
* Pressing "Go to Next Conflict" highlights the first conflict
* Pressing "Go to Next Conflict" again does not do anything 
* Also interesting that the editor minimap only has one conflict marker

**Comment by andreamah** [comment]
I also saw this. It seemed to happen when both inputs make the same change.

**Comment by andreamah** [comment]
On `demo1`, once it moves past the first conflict and try to go back to it, it doesn't go back to it properly.

![image](https://user-images.githubusercontent.com/31675041/186772507-4bb1cb7d-eacb-4167-946d-0ddff0de74f1.png)

**Comment by hediet** [comment]
This is weird, I cannot reproduce this. Also, for `demo1`, I only have 2 conflicts.

And this checkbox is also very weird:

![image](https://user-images.githubusercontent.com/2931520/186886978-2df19088-fc63-4504-bbc5-ca1612c22c04.png)

**Comment by andreamah** [comment]
I'm on commit 7b31d7e70b875b4afbf87410e876e5e30c3fd477, not the latest commit. Does that make a difference?

**Comment by hediet** [comment]
If you can reproduce on the latest commit, can you try to give me a call?

**Comment by andreamah** [comment]
yup, things look good on the latest on master for diff-merge-datasets for demo1. :)

One thing I noticed, though, is that, if you're focused on the result and try to skip to next conflict, it's hard to tell by looking at the two inputs where the conflict is (seems that the two inputs aren't telling me anything in this screenshot):
![Recording 2022-08-28 at 23 02 12](https://user-images.githubusercontent.com/31675041/187133247-e7e98fe1-3d9f-4f93-a155-92d31abffa53.gif)

When I make the input editors a little bigger, then it starts making a little more sense.
![Recording 2022-08-28 at 22 59 38](https://user-images.githubusercontent.com/31675041/187133025-bdb45625-4252-4060-98c7-d62d313cfb3a.gif)

Not too big of a deal though, just wanted to bring your attention to it!
