### ISSUE TITLE
Test merge editor: "Compare with Base" replaces current editor if merge editor isn't pinned

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#158958]
Testing #158819

Not sure if this is expected behavior, but viewing the base navigates away from the merge editor, which is a little annoying because looking at the base is probably done just to help with deciding how to merge.
![Recording 2022-08-23 at 11 08 18](https://user-images.githubusercontent.com/31675041/186232555-f0bad470-90a6-4a84-8e74-7869f2ca07eb.gif)

**Comment by hediet** [comment]
I think it works as expected. I think when you open the merge editor via SCM it will be sticky (but maybe not).
Maybe it makes sense to make the merge editor sticky once a compare command is invoked.
