### ISSUE TITLE
Better Formatting for Allmanstyle

### ISSUE THREAD

**Issue by equinoxr** [Microsoft/vscode#15893]
Im programming in the Allmanstyle.
if i press { i would be really faster if a new line would happen, then a tab in the new line and then a } -- but the cursor should stay in the middle of the braces (after the tab). Would be also cool to select text, and if i press { it gets formatted in the Allmanstyle... how could this be achieved??

greetz equinox

**Comment by jrieken** [comment]
@equinoxr The brackets rules are language dependent so we first need to know for what language you want that

**Comment by equinoxr** [comment]
oh sry ok im programming in C++! 

https://de.wikipedia.org/wiki/Einr%C3%BCckungsstil#Allman_.2F_BSD_.2F_.E2.80.9EEast_Coast.E2.80.9C

Here is a example how code looks when i code ;)

greetz & thx

equinoxr

**Comment by jrieken** [comment]
This issue was moved to Microsoft/vscode-cpptools#365
