### ISSUE TITLE
Test merge editor: visibility for going to next conflict

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#158944]
Testing #158819

I had one conflict remaining and I wanted to jump to it, but it wasn't immediately obvious how to jump to a conflict using this command:
<img width="545" alt="image" src="https://user-images.githubusercontent.com/31675041/186225070-f34c896d-11fa-4408-9e2f-1483218f20e8.png">

It would be nice if clicking on the "1 Conflict Remaining" triggered something to help me view that conflict (maybe a list of conflicts like how problems are in the `Problems` tab in the bottom viewlet)?

<img width="823" alt="image" src="https://user-images.githubusercontent.com/31675041/186225499-fd324e6b-f44c-4747-b0bc-3d06f2d7f87f.png">

**Comment by hediet** [comment]
> I had one conflict remaining and I wanted to jump to it, but it wasn't immediately obvious how to jump to a conflict using this command:

This command didn't work? There are also the arrow buttons

![image](https://user-images.githubusercontent.com/2931520/186358711-9cc5d441-6f5b-4f75-869b-f62ef075a3b2.png)

**Comment by andreamah** [comment]
nvm, I didn't see those. Thanks for letting me know!

**Comment by hediet** [comment]
See #159027
