### ISSUE TITLE
Unable to open ... File not found

### ISSUE THREAD

**Issue by guyellis** [Microsoft/vscode#15895]
- VSCode Version: 1.7.0
- OS Version: Ubuntu 14.04 LTS

Steps to Reproduce:

1. Run debugger or unit test that causes a stack trace to be displayed
2. View contents of debug console which look something like:

```
  0 passing (7ms)
  1 failing
  1) /app/models/plant should pass full validation:
     Error: temp
      at Context.it.only (test/app/models/test.plant.js:46:11)
```

Even though the full path to the file is shown in the parens only the part from `/app/` onwards is underlined and when clicked produces "Unable to open 'test.plant.js': File not found (/app/models/test.plant.js). Create File / Cancel"

Also tested on a Mac with same results.

**Comment by isidorn** [comment]
@guyellis thanks but dup of https://github.com/Microsoft/vscode/pull/15464
@felixfbecker for some reason every user we have has hit this issue in the past week :)
