### ISSUE TITLE
Secondary side bar visibility isn't specific to profile

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#158962]
Testing #158809

When I toggle the secondary side bar, that view doesn't seem to be saved to the profile.
For example, when I switch from profile A to B, if I had the secondary side bar visible before switching, it's still visible after switching, whereas originally, profile B didn't have the secondary side bar visible.

**Comment by sandy081** [comment]
This is collapsed state and is scoped to workspace.
