### ISSUE TITLE
"Empty" terminal window when restoring with fish and bash open side by side

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#158932]
Testing #158831

Note: I don't believe this is `fish` shell specific, but tagging as I was testing that test plan item.

<img width="2226" alt="image" src="https://user-images.githubusercontent.com/812783/186213461-4bb13e9d-79f9-437c-8eba-94805ce5ef2f.png">

Repro:
Bash shell side by side with Fish shell in the terminal window.
Close vscode-insiders
Reopen vscode-insiders
Fish shell is there but the window on the left that was the bash window is now some sort of empty terminal window that I can't type into instead of a bash window.

**Comment by IanMatthewHuff** [comment]
As can be seen from the fish history I was configuring the fish shell for terminal integration at the time of the shutdown / restore (needed to change code to code-insiders in the fish.config).

**Comment by meganrogge** [comment]
works for me

https://github.com/microsoft/vscode/assets/29464607/c781cd51-39f8-48dd-9a33-375f3d38a01d
