### ISSUE TITLE
Unable to launch Jupyter in the browser when using port forwarding in code-server

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#158993]
Testing #158840

* Launch vscode in browser as per above issue (on the current desktop)
* Create a terminal
* Install Jupyter Notebook into a python enviornment
    * e.g. `python -m pip install jupyter notebook`
* Launch Jupyter without any tokens and any passwords (i.e. without any auth)
    * `python -m jupyter notebook --NotebookApp.allow_origin="*" --NotebookApp.token="" --NotebookApp.password=""  `
    * Jupyter will not be running on the current machine on `http://localhost:8888/`
* Verify you can open the browser and point to `http://localhost:8888/`
* Now launch the above page using the forwarded port in VS Code
* The web page is empty

**Comment by connor4312** [comment]
What is the HTTP response from that page?

Also, are you on a MacBook on an ipv6 interface? I previously opened an issue about that for them: https://github.com/microsoft/basis-planning/issues/414

**Comment by DonJayamanne** [comment]
Weird can no-longer repro this issue
, re-started code-server (had to do this because I updated VSCode that was running the server in the terminal)

Closing this for now.
