### ISSUE TITLE
First Cell in ipynb file has issues with pasting images

### ISSUE THREAD

**Issue by Yoyokrazy** [microsoft/vscode#158955]
Type: <b>Bug</b>

This issue is only present on the first cell of a notebook. Any other way to create a markdown cell does not give this issue.

To repro:
- make new notebook, change first default cell to markdown, paste screenshot.

<img width="773" alt="image" src="https://user-images.githubusercontent.com/12552271/186231150-7d9e6c68-2b48-4265-96fe-d3ebfe7bb7bc.png">

VS Code version: Code - Insiders 1.71.0-insider (d5104dc1894e4a78b600662bf8958c7a2b9286a7, 2022-08-23T15:24:12.374Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (13.55GB free)|
|Process Argv|--crash-reporter-id 62122f1b-5534-43ca-aa21-fca29c482163|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
theme-monokai-pro-vscode|mon|1.1.20
python|ms-|2022.13.12341009
vscode-pylance|ms-|2022.8.31
jupyter|ms-|2022.8.1002371040
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vscode-todo-highlight|way|1.0.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30404738
wslgetstarted:30449409
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52cf:30549188

```

</details>

**Comment by joyceerhl** [comment]
I can't get pasting images from the clipboardc to work for me at all, I have enabled editor paste and ipynb paste. I'm on Windows FWIW. Is there some setup I am missing?

**Comment by Yoyokrazy** [comment]
Should be fixed by #159085, issue with the revised metadata having the attachments at top level, rather than underneath `custom`

**Comment by Yoyokrazy** [comment]
> I can't get pasting images from the clipboard to work for me at all, I have enabled editor paste and ipynb paste. I'm on Windows FWIW. Is there some setup I am missing?

Just to confirm, the markdown was probably pasting correctly, but the image was unable to render with something resembling this error: `GET attachment:image.png net::ERR_UNKNOWN_URL_SCHEME`

**Comment by joyceerhl** [comment]
Hm no, I just got `image.png` pasted into the cell.

**Comment by Yoyokrazy** [comment]
Just to confirm, you have both of these settings?
```
"ipynb.experimental.pasteImages.enabled": true,
"editor.experimental.pasteActions.enabled": true,
```

My only last thought could be the filetype you are typing to copy. Right now it only accepts png files, but in the future will be built out to support a broader range of mime types.

**Comment by joyceerhl** [comment]
Oh, I think the problem was how I was taking the screenshot. Doing a full F8 printscreen and Ctrl+V worked, but the way I normally take screenshots is Win+Shift+S to select an area to screenshot. I'm guessing that has some other mimetype which is probably why it wasn't working.
