### ISSUE TITLE
Suggestion: When using Alt + "Run Recent Command" or "Go to Recent Directory" focus the terminal

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#158935]
Testing #158831

This is just a suggestion, I'm not 100% sure if this would be the right UX approach or not. But if you trigger the "Run Recent Command" or "Go to Recent Directory" commands when holding the `Alt` button this puts the text from that command into the terminal, ready to run. However if your focus is anywhere else in the UI when you run that, focus is not moved into the terminal. So you can't just hit enter to run the command or start typing to edit the command.

It might be incorrect to steal focus from another element, but at least for my use case I was expecting that running these commands + Alt would move my focus to the terminal window so that I could run or edit the command line.

**Comment by meganrogge** [comment]
Yes IMO this should focus the terminal

**Comment by Tyriar** [comment]
We're a bit inconsistent here, but for holding alt specifically it seems pretty clear we should focus 👍
