### ISSUE TITLE
Test merge editor: "Toggle Current Conflict from Left" should only appear when valid

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#158948]
Testing #158819
When my cursor isn't inside of a conflict, this command does nothing. Should it only be visible in the quickpick when it does something? Or should there be an error message when you try to run it but it doesn't do anything? Same with the "Toggle Current Conflict from Right".

<img width="549" alt="image" src="https://user-images.githubusercontent.com/31675041/186227931-41955c39-db48-42da-9280-2efcf1430d4f.png">

**Comment by hediet** [comment]
I fear if we hide it when there is nothing to toggle, users won't discover that there is a (keybindable) command for this functionality.

How did you find this command? Was your cursor in a conflicting region?

**Comment by andreamah** [comment]
It wasn't in a conflicting region at the time

**Comment by hediet** [comment]
Let's show an error message if this command does not do anything.

**Comment by rzhao271** [comment]
If I run the toggle command in an invalid region, I get a notification, which is good.
But, if I then toggle a valid region after, the notification still stays on the screen for a while. Can the notification be hidden when the user toggles a valid region?

**Comment by hediet** [comment]
Can notifications be removed? I thought that is not possible. Also, I think this use-case is quite rare. The notification is just to teach that you should be in a conflict.
