### ISSUE TITLE
Merge Editor: Difficult to interpret conflicting lines decoration

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#158918]
Testing #158819

* Clone https://github.com/hediet/diff-merge-dataset
* Use the `Load Merge Editor State From Folder` command and select the `merges/merge-equal-parts` folder
* Select `result` in the quick pick
  <img width="1511" alt="image" src="https://user-images.githubusercontent.com/3372902/186186391-ad8fa9e0-f74d-48ca-ad53-91c19f084c28.png">

Couple of things that I am trying to wrap my head around:
1. It seems that the merge editor is in a state (both checkboxes with a circle) that is not clear to me. The conflict is clearly not resolved, as there is still one conflict pending. Also if I decide to click on any of the checkboxes, I am never able to return to this initial state.
2. Should "change3" in the result file be on line 5 instead of 9?

**Comment by hediet** [comment]
I created some follow up issues, as discussed. Let's close this, as it is unclear what to do with this feedback.
