### ISSUE TITLE
With canvas, should the line be continuous?

### ISSUE THREAD

**Issue by TylerLeonhardt-alt** [microsoft/vscode#158984]
Testing #158827

using canvas render.

![image](https://user-images.githubusercontent.com/98423974/186267017-0f69b63b-fb5e-4522-a596-050d8761398f.png)
Should the line be continuous even though it overlaps the characters?

vs "on":

![image](https://user-images.githubusercontent.com/98423974/186267312-ab51d39b-da35-4443-a0ab-eaf94639bb8c.png)

I'm talking about characters like `p` and `q`.

> @TylerLeonhardt's alt

**Comment by Tyriar** [comment]
I didn't bother adding this to the canvas renderer as it's the fallback which is primarily for iPad atm, nothing stopping it from working there too though. Should really consolidate the rendering code for webgl and canvas as they mostly do the same thing when drawing the actual characters. https://github.com/xtermjs/xterm.js/issues/4062

**Comment by rzhao271** [comment]
The wavy underline looks off with gpu enabled (first example in the attached screenshot). With the canvas setting, it's not rendered at all.
![Different terminal text underline decorations](https://user-images.githubusercontent.com/7199958/198164767-7c660dd8-c913-4b15-9024-68d3bb9ba3e1.png)

**Comment by Tyriar** [comment]
The look of curly was going to be revisited in https://github.com/xtermjs/xterm.js/issues/4064
