### ISSUE TITLE
extension cannot require('node-expat') (DLL initialization failed)

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#1589]
Calling "require('node-expat')" results in "Error: A dynamic link library (DLL) initialization routine failed"

Platforms: tested with Windows 8.1 64 and x86 (virtual machine)
Versions: VSCode 0.10.5, Node.js 4.1.1 ia64 or x86; or Node.js 5.3.0 ia64 or x86, Python 2.7.11, node-expat 2.3.9, Visual Studio 2013 Ultimate (on ia64) or 2015 Community (on x86)

On my ia64 machine, I have attempted installing both ia64 and x86 versions of Node.js and Python.

For x86, I performed a clean test on a fresh VM: installed VSCode 0.10.5, Node.js 5.3.0 x86, Python 2.7.11, and VS 2015 Community. Then I created the "Hello World" example (via yo), added "node-expat": "2.3.9" to the project dependencies, and then added "var x = require ('node-expat') to the extension initialization routine. When the extension activates, I get the above error.

... does VSCode support extensions with binary dependencies? Should this be documented?

EDIT: this appears to be a duplicate of bug #658

**Comment by bpasero** [comment]
Yup, closing.
