### ISSUE TITLE
Copy relative path button in search section

### ISSUE THREAD

**Issue by Babulekh** [microsoft/vscode#158902]
It is common case for me to copy path from search section and paste it into address bar. But it is really hard to copy full filesystem path and delete part of it.

So I suggest to make a button similar to that one appearing when you press RMB on tab

**Comment by andreamah** [comment]
related to https://github.com/microsoft/vscode/issues/47783

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
