### ISSUE TITLE
CLI help doesn't mention profile must be used with workspace

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#158957]
Testing #158809

On Mac, `code-insiders --profile name` launches a new instance without a profile, which might confuse users expecting a profile. `code-insiders --help` doesn't mention that a folder or workspace _must_ be provided.

I'm thinking we can either emphasize that a folder or workspace must be provided even more than what the current help documentation has, or we exit with an error when the user doesn't provide a folder or workspace.

**Comment by weinand** [comment]
Yes, flagging the missing workspace is a must.

**Comment by sandy081** [comment]
Updated the doc

`Opens the provided folder or workspace with the given profile and associates the profile with the workspace. If the profile does not exist, a new empty one is created. A folder or workspace must be provided for the profile to take effect.`
