### ISSUE TITLE
All three options not visible when working on Azure repos

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#158966]
Testing #158798

Repo: https://insiders.vscode.dev/azurerepos/Monacotools/Monaco/Sandbox

![image](https://user-images.githubusercontent.com/13199757/186238693-c4514762-5d7d-4932-93ac-7e2681af0bd0.png)

Expected: https://user-images.githubusercontent.com/30305945/185987422-1abf678e-090d-4bb3-bd32-d1c61ec74b70.png

**Comment by joyceerhl** [comment]
This is as designed, clarified in test plan item. Sorry for the confusion!
