### ISSUE TITLE
Test: debug console objects from output

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#15901]
- [x] @mjbvz 
- [x] @ramya-rao-a

Complexity: 2

As per https://github.com/Microsoft/vscode/issues/15796 we are now supporting expanding complex objects in repl which are coming from output channels. Have a node program, choose `node2` as `type` in 'launch.json', launch your program, open repl and verify:
* You can use `console.log` to print complex objects, these objects can be expanded in repl
* You can use `console.log` with multiple arguments, like `console.log('abc', { d: 123 })`, and they are all visible.

**Comment by alexandrudima** [comment]
This did not work for me as advertised -- see #16641

**Comment by roblourens** [comment]
Oh this is not actually implemented yet @isidorn

**Comment by isidorn** [comment]
Oh sorry for the misunderstaing, that's why I pinged you on the original issue -> lets move this to january then and unassign people

**Comment by hbenl** [comment]
FYI: I just tested this with (an unreleased version of) [my debug adapter](https://github.com/hbenl/vscode-firefox-debug) in an insider build of VS Code (Date 2017-01-13T07:03:18.620Z) and it works fine for me.
