### ISSUE TITLE
Do not use dot inside the checkbox?

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#159025]
Currently we render a dot in the checkbox for conflicts which we want the users to act on.
I think this is confusing and might confuse people from clicking on a dot. This is not a known ux pattern.

The other decorations are enough. Or is there another meaning to the dot that I am missing here?

fyi @daviddossett

**Comment by hediet** [comment]
> The other decorations are enough. Or is there another meaning to the dot that I am missing here?

I created #158925 to improve this.
The `dot` means that the conflict range is dirty. When you check and uncheck a dirty checkbox, you will end up in a different state.
When you check and uncheck an unchecked checkbox you will end up in the same state.
Effectively merge markers or custom edits cause this.

On the one hand I can see that this might be confusing. On the other hand, when you want to tweak a conflicted region in the result after accepting one side or the other, this would also uncheck the checkbox, which would be weird: When you would check that unchecked checkbox, it would reset the custom tweak.

**Comment by isidorn** [comment]
Thanks for the clarification. And thanks for pushing the issue to add hover descriptions.
I am not sure if we have any actionable items from this issue. If not, feel free to close it.

Though we can reconsider this once we hear user feedback.

**Comment by daviddossett** [comment]
I do think this is confusing but the hover will help in the meantime. Open to exploring other options to these situations in the next iteration.
