### ISSUE TITLE
ipynb image paste setting description is redundant

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#159091]
![image](https://user-images.githubusercontent.com/30305945/186492934-c4aa6253-ed9b-443d-8426-9f3404a1d533.png)

The link in the setting description links back to the setting I'm currently looking at, the second sentence in this description could probably be omitted.

**Comment by Yoyokrazy** [comment]
This was supposed to be `"editor.experimental.pasteActions.enabled": true`, I'll get a fix for that up now.
