### ISSUE TITLE
Invalid "file not found" when following a markdown link on Linux (remote)

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#159083]
Testing https://github.com/microsoft/vscode/issues/158416 on OSX connected to a Linux remote (an Alpine dev container)

1. Make a link from file `a.md` to `b.md`
2. Cmd+click on the link. You get a "file not found" screen even though the file exists (verify by copying the file path). Trying to create the file fails.
3. Change the link to `b.md#some-heading`
4. Cmd+click on the link. Now you get the file open in one editor group, but the invalid file in another editor group

https://user-images.githubusercontent.com/2230985/186485659-7e48d695-66e8-4801-a349-952e3a063b45.mp4

**Comment by Hocnonsense** [comment]
I met the same error, and it seems to create a file on local machine.

![image](https://user-images.githubusercontent.com/48747984/186603168-89944b86-f35e-494f-b967-a7d611f6a2dc.png)
![image](https://user-images.githubusercontent.com/48747984/186603201-b9817e33-95c0-41bb-a389-c6523b9a3e1c.png)

My local machine:
版本: 1.70.2 (user setup)
提交: e4503b30fc78200f846c62cf8091b76ff5547662
日期: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

Remote machine: centos8

**Comment by mjbvz** [comment]
@connor4312  I believe this was fixed by 077f5865dac519a9ce6145b39065cee0b5952232

Tested on remote containers from MacOS. If you're still seeing this, can you provide more details steps so I can verify I'm testing correctly
