### ISSUE TITLE
Select settings on the top right get covered by the sticky header

### ISSUE THREAD

**Issue by usama8800** [microsoft/vscode#159034]
Type: <b>Bug</b>

The select settings on the top right get covered by the sticky header

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.15.0-46-generic

[Before sticky header](https://imgur.com/D9hdCEe)
[After sticky header](https://imgur.com/ROCz0K3)

**Comment by gjsjohnmurray** [comment]
Are you willing to install [Insiders](https://code.visualstudio.com/insiders) and test your scenario there?

**Comment by jrieken** [comment]
Steps

* have a sticky scroll line
* select text and press cmd+d
* :bug: mode switcher is behind stricky scroll line

**Comment by jrieken** [comment]
This got fixed a while ago (see #159034)
