### ISSUE TITLE
JSDoc Comment seen as code error in JavaScript

### ISSUE THREAD

**Issue by khrome83** [Microsoft/vscode#1590]
The JSDoc comment ` * @param  {Array<string>} [plugins=['defaults']] - plugins to enables` shows a red underline below the `<` before string. 

When clicking on the error/warning notice, it says `'}' expected.`
It is expected that code within a comment does not give error/warning notices for JavaScript

Using version 0.10.5 on Windows 10.

**Comment by bpasero** [comment]
@khrome83 I cannot reproduce if I only use that comment, can you attach the full file?

**Comment by jrieken** [comment]
@khrome83 Is this in a JS or TS file?

**Comment by khrome83** [comment]
@jrieken this is a JS file.

**Comment by khrome83** [comment]
@bpasero this is happening in a different file as well, but it is varied about "when" it happens. 

In the below code, only ` * @returns {ATSNode<TextNode>} text node` causes it.
```
// Node Creation

/**
 * @private
 * @param  {string} value - string to be inserted as text
 * 
 * @returns {ATSNode<TextNode>} text node
 */
var createTextNode = function (value) {
    return {
        node: '#text',
        value: value,
        parent: null
    };
};


/**
 * Creates a document node.
 *
 * @function createDocument
 * @memberof TreeAdapter
 *
 * @returns {ASTNode<Document>} document
 */
treeAdapter.createDocument = function() {
    return {
        node: '#document',
        quirksMode: false,
        children: []
    };
};
```

**Comment by khrome83** [comment]
![issue](https://cloud.githubusercontent.com/assets/1844739/11976795/81e1a94e-a941-11e5-8813-9893adff0e8b.PNG)

Here is a screenshot of the issue, showing the red underline.

[sample.txt](https://github.com/Microsoft/vscode/files/70776/sample.txt)

This is the JS file from the screenshot example. I renamed it to text to upload it.

**Comment by jrieken** [comment]
Good catch. The JS parser tries to resolve some JSDoc constructs but doesn't seem to understand generics

**Comment by felixfbecker** [comment]
@khrome83 actually, you are using invalid JSDoc syntax. In JSDoc, a generic is notated with a dot:
```js
/**
 * @param {Array.<string>}
 */
```

**Comment by khrome83** [comment]
@felixfbecker I will give that a shot, thanks

**Comment by khrome83** [comment]
@felixfbecker that did remove VSCode from showing the error.

Do you have a link to where in the JSDoc this is shown? All examples I have seen so far, in my code and others, do not use a `.`.

**Comment by felixfbecker** [comment]
@khrome83 heres the documentation: http://usejsdoc.org/tags-type.html

**Comment by felixfbecker** [comment]
But imo validation for jsdoc comments is a feature, not a bug. I think it wont do any validation if you start your comment with `/*` and not `/**` ;)

**Comment by khrome83** [comment]
@felixfbecker its only showing the error on the first instance of a file, not the remaining lines. 
Also it is giving the incorrect fix. It is not "validating" the comment, but instead perceiving the comment as JS. 

Also valid JSDoc uses `/**` to start, not `/*`, so this would just introduce a different problem.

**Comment by jrieken** [comment]
As we now ship with project Salsa this should work.
