### ISSUE TITLE
Cannot debug tests with `--debug` flag

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159011]
* use the script to run unit test
* try to use its [`--debug`](https://github.com/microsoft/vscode/blob/1044556d8b2935bc5045128c2596d26cc1e6d1b2/test/unit/electron/index.js#L29) flag
* 😢 doesn't work anymore, it seems to collide and be consumed by Electron

```
jrieken@jrieken-m1-pro vscode % ./scripts/test.sh --debug
yarn run v1.22.17
$ node build/lib/electron
✨  Done in 0.27s.
[26333:0824/084242.537994:ERROR:node_bindings.cc(242)] Error parsing Node.js cli flags
electron: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
jrieken@jrieken-m1-pro vscode %
```

**Comment by jrieken** [comment]
@deepak1556 Is this something that can be configured inside electron or do we need to pick another flag?

**Comment by deepak1556** [comment]
When launching the main process, Electron gives Node.js a chance to parse the runtime arguments before the application script gets executed, the above error is actually thrown from Node.js https://github.com/nodejs/node/blob/main/src/node_options.cc#L45-L49 and we cannot configure it. Also, CLI parsing errors from Node.js will abort the process as default behavior. I recommend changing the flag name to make it future proof.

**Comment by jrieken** [comment]
Makes sense. Thanks for clarifying
