### ISSUE TITLE
A way to distinguish open windows on the taskbar

### ISSUE THREAD

**Issue by thorn0** [Microsoft/vscode#15902]
- VSCode Version: 1.8.0-insider
- OS Version: Windows 7 x64

Steps to Reproduce:

1. Open a couple of projects.
2. Look at the taskbar.
3. Can you quickly understand which button corresponds to which project?

![image](https://cloud.githubusercontent.com/assets/94334/20532948/dddce0ca-b0ec-11e6-8739-cfa8331c2af9.png)

You can't. Because the title has the current file name first, not the project name.

<sub>It'd be funny if VSCode used favicons for the taskbar buttons... :)</sub>

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/1723
