### ISSUE TITLE
Enabling - Disabling - Enabling Settings Profiles is causing extensions loss

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#159072]
Steps to Reproduce:

1. Download the stable build 1.71.0 (latest) - https://builds.code.visualstudio.com/builds/stable
2. Enable Settings Profile feature in Settings (Restart)
3. Create some Profile
4. Disable Settings Profile feature in Settings (Restart)
5. Install some extensions
6. Enable Settings Profile feature in Settings (Restart)

🐛 Installed extensions are gone

**Comment by connor4312** [comment]
How does one enable/disable the feature? I tried `workbench.experimental.settingsProfiles.enabled` from an old TPI, but it's not recognized and I seem to be able to enable/disable profiles without having any settings.

**Comment by rzhao271** [comment]
The installed extensions are there, but the profile I created from step 3 is gone. I created it using the "Create from Current Settings Profile" option while on the Default profile.

**Comment by sandy081** [comment]
Yes, that is expected. Turning off the feature, removes the profiles.
