### ISSUE TITLE
3 way merge editor yellow colour does not work in light theme

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#159019]
Notice how in the dark theme the border is visible and the whole yellow part is transparent - very nice.
I think we should strive towards this also in the light theme. The current light theme colours do not work since they are too heavy and the currently selected conflict is not visible (since the border is not visible).

Light theme

![Screenshot 2022-08-24 at 10 36 37](https://user-images.githubusercontent.com/1926584/186371483-b850416a-969c-41a1-ae3e-3b532e0df159.png)

Dark theme
![Screenshot 2022-08-24 at 10 36 44](https://user-images.githubusercontent.com/1926584/186371506-37f2a5ec-d19a-482c-b138-8864c3f436ab.png)

Assigning to August since I think we should tackle this in endgame, if not possible feel free to push out to September. Thanks :)

fyi @hediet

**Comment by daviddossett** [comment]
Fixed via #159199
