### ISSUE TITLE
Code Action to create functions or properties

### ISSUE THREAD

**Issue by sharpmachine** [Microsoft/vscode#15900]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra 10.12.1
- Angular 2/Typescript
Steps to Reproduce:

1. In a class, add a property or method that doesn't exist yet

Visual Studio 2015 and even Atom Typescript do this, but I can't figure out how to do it with VS Code.

**Visual Studio 2015 screenshots:**
![screen shot 2016-11-22 at 8 45 41 am 2](https://cloud.githubusercontent.com/assets/600836/20532999/d9067018-b090-11e6-85d1-93b710755b6a.png)

![screen shot 2016-11-22 at 8 46 05 am 2](https://cloud.githubusercontent.com/assets/600836/20533000/d906962e-b090-11e6-9345-e3848bd5c3e4.png)

Am I missing something or is this not possible in VS Code.

**Comment by jrieken** [comment]
This issue was moved to Microsoft/TypeScript#12462
