### ISSUE TITLE
Please integrate all emmet functionality

### ISSUE THREAD

**Issue by shafi49** [Microsoft/vscode#15903]
- VSCode Version: 1.7.1
- OS Version: Windows 10

Steps to Reproduce:

1. By default assign shortcut for popular emmet actions. For example: I love [emmet actions](http://docs.emmet.io/actions/). So after installing VS Code I had to assign shortkeys for these emmet actions manually
i. editor.emmet.action.wrapWithAbbreviation
ii.editor.emmet.action.updateTag
iii.editor.emmet.action.removeTag
iv.editor.emmet.action.balanceInward
v.editor.emmet.action.balanceOutward

2.  If all emmet action shortcuts can not be assigned then give us a handy option in menu bar for easy accessing of emmet actions. Previously I used Adobe brackets a lot. In 'Brackets' after installing emmet plugin a menu item called 'emmet' would appear. All emmet actions used to be listed under that menu. 

I hope you awesome guys will consider this issue. :) 
Thank you guys for this awesome VS Code program.

**Comment by freMea** [comment]
Yes, it took some time to set the keybindings for **EMMET**.

Here is my personal keybindings for **emmet**. Sorry, comments are in french but the commands name should be self explanatory. 

        /* =====================    EMMET    ====================== */
        /* Naviguer entre les points d'éditions.
           Les tags: <tag>|</tag>
           ou attribut vide pour les remplir: href="|" */
        {
            "key": "ctrl+e ctrl+right",
            "command": "editor.emmet.action.nextEditPoint",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+e ctrl+left",
            "command": "editor.emmet.action.previousEditPoint",
            "when": "editorTextFocus && !editorReadonly"
        },
        /* Similaire mais…
           Sélectionne les tags et attributs pour les éditer */
        {
            "key": "ctrl+e ctrl+d",
            "command": "editor.emmet.action.selectNextItem",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+e d",
            "command": "editor.emmet.action.selectPreviousItem",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Développer une sélection. Comme alt+shift+→ mais spécifique html
        {
            "key": "ctrl+e up",
            "command": "editor.emmet.action.balanceOutward",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+e down",
            "command": "editor.emmet.action.balanceInward",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Go to matching pair
        {
            "key": "ctrl+e ctrl+t",
            "command": "editor.emmet.action.matchingPair",
            "when": "editorTextFocus && !editorReadonly"
        },
        /* Commenter tag html ou règle css entier ou sélection.
           ctrl+e ctrl+/ fonctionne bien sur un clavier azerty. */
        {
            "key": "ctrl+e ctrl+/",
            "command": "editor.emmet.action.toggleComment",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Entourer avec du code
        {
            "key": "ctrl+e ctrl+a",
            "command": "editor.emmet.action.wrapWithAbbreviation",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Splits and joins tag definition, e.g. converts from <tag/> to <tag></tag> and vice versa
        {
            "key": "ctrl+e ctrl+j",
            "command": "editor.emmet.action.splitJoinTag",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Remove tags: <|x><y></y></x> will return <y></y>
        {
            "key": "ctrl+e ctrl+k",
            "command": "editor.emmet.action.removeTag",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Merge lines
        {
            "key": "ctrl+e ctrl+m",
            "command": "editor.emmet.action.mergeLines",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Increment/Decrement Number
        {
            "key": "ctrl+up",
            "command": "editor.emmet.action.incrementNumberByOne",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+down",
            "command": "editor.emmet.action.decrementNumberByOne",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+alt+up",
            "command": "editor.emmet.action.incrementNumberByOneTenth",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+alt+down",
            "command": "editor.emmet.action.decrementNumberByOneTenth",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+shift+up",
            "command": "editor.emmet.action.incrementNumberByTen",
            "when": "editorTextFocus && !editorReadonly"
        },
        {
            "key": "ctrl+shift+down",
            "command": "editor.emmet.action.decrementNumberByTen",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Reflect CSS value for vendor-prefixed properties
        {
            "key": "ctrl+e b",
            "command": "editor.emmet.action.reflectCSSValue",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Encode/Decode Image to data:URL
        {
            "key": "ctrl+e u",
            "command": "editor.emmet.action.updateTag",
            "when": "editorTextFocus && !editorReadonly"
        },
        // Remplacer/Renommer le tag HTML courant avec Emmet
        {
            "key": "ctrl+e u",
            "command": "editor.emmet.action.updateTag",
            "when": "editorTextFocus && !editorReadonly"
        }
    
You may need to add this to disable one problematic default key

        /* =====================    GENERAL    ====================== */
        // Désactiver cette commande doublon avec CTRL+P
        {
            "key": "ctrl+e",
            "command": "-workbench.action.quickOpen"
        }

**Comment by ramya-rao-a** [comment]
@shafi49 

There is an "Emmet..." menu item in the "Edit" menu

![image](https://cloud.githubusercontent.com/assets/16890566/24622372/a9d2b258-1859-11e7-8ae1-a31ca4e617a5.png)

Click on this, and the command pallet opens with all the emmet commands

![image](https://cloud.githubusercontent.com/assets/16890566/24622407/c62f767a-1859-11e7-9394-47b6f70b3f6c.png)

Hope this helps.
