### ISSUE TITLE
Debugger stops on mouse hover

### ISSUE THREAD

**Issue by sant123** [Microsoft/vscode#15905]
- VSCode Version: 1.7.1
- OS Version: Windows 8.1

Steps to Reproduce:

1. Download oracledb `npm install oracledb`
2. Paste the following code:

``` javascript
var oracledb = require('oracledb');
oracledb.outFormat = oracledb.OBJECT;

var config = {
    user: "SOMEUSER",
    password: "SOMEPASSWORD",
    connectString: "SOMEINSTANCE"
};

var oraConnection = oracledb.getConnection(config);

oraConnection.then(connection => {

    var bindvars = {
        sigla: "%J.D%"
    };

    var execute = connection.execute("SOMEQUERY", bindvars);

    execute.then(result => {
        var data = result.rows;
        var json = JSON.stringify(data);

        console.log(json);
        connection.release().catch(console.error);

        //  This is really but really bad, but here comes.... (the connection is closed now) ( ._.)
        connection.execute("SOMEQUERY", bindvars).then(result => console.log(result.rows));

    }).catch(console.error);

}).catch(console.error);
```

The following happens:

![bug debug](https://cloud.githubusercontent.com/assets/7959437/20536310/9139f4aa-b0b6-11e6-90fa-9f14819fdc44.gif)

**Comment by isidorn** [comment]
Thanks for the steps but the oracledb npm install throws errors and requires pythong etc...
So can you try to repro this with a normal node app?
Do you see this all the time?
Does the same happen if you do not hover?
Do you see some errors in the developer tools console (command pallet > toggle command pallete)?

**Comment by sant123** [comment]
Hi @isidorn, I couldn't repro it with a normal node app 😢 I just copied the oracledb's promise implementation and works as expected. However I see the Node.js process takes 19MB of RAM with the oracledb example (the example above), with my example (copying promise from oracledb) takes 16.4MB.

* I only see it when I don't catch the promise in the example above.
* Only occurs when I hover any part of the code, although if I choose continue, the application turns unresponsive.
* If you refer to `debug console` it doesn't show any error.

**Comment by isidorn** [comment]
Can you also reproduce it if you put type: node2 in your launch.json instead of node

**Comment by sant123** [comment]
I get the following error in the `debug console`:

    at ScopeContaine[...]Error processing "variables": Error: not opened
    at LoggingSocket.send (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\ws\lib\WebSocket.js:219:16)
    at LoggingSocket.send (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeConnection.js:34:20)
    at Client._sendQueuedRequests (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:83:30)
    at Client._send (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:77:14)
    at Promise (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:101:18)
    at Client.call (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:99:16)
    at Proxy.target.(anonymous function) (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\noice-json-rpc\lib\noice-json-rpc.js:141:53)
    at NodeDebugAdapter.getVariablesForObjectId (c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\ms-vscode.node-debug2\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:682:33)
    at ScopeContaine[...]

It only appeared once.

**Comment by isidorn** [comment]
Giving to @roblourens to investigate a bit more :)

**Comment by roblourens** [comment]
I think that error is from something that happened after the real problem. Can you add `"diagnosticLogging": true` to your launch config, run this again, then find the log file path at the top of the debug console, and upload that here?

**Comment by sant123** [comment]
Hi @roblourens, sure! This is the log:

Verbose logs are written to C:\Users\SANTIA~1\AppData\Local\Temp\vscode-node-debug2.txt
11:51:09 AM, 11/29/2016
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.3.5
node-debug2: 1.7.2
node --inspect=21587 --debug-brk appx.js 
Discovering targets via http://127.0.0.1:21587/json
Debugger listening on port 21587.
Warning: This is an experimental feature and could change at any time.
Paused on entry
Target node version: v7.2.0 x64
Websocket closed
Killing process with id: 8876
Terminated: websocket closed
Target exited
Terminated: Target exited
Target closed
Terminated: Target closed
Terminated: Got disconnect request

This is my launch.json

``` json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node2",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/appx.js",
            "cwd": "${workspaceRoot}",
            "diagnosticLogging": true
        },
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "port": 5858
        }
    ]
}
```

**Comment by roblourens** [comment]
Thanks, but the log doesn't really show anything unusual. It shows the Node process maybe crashing or being killed on its own, not because of the debug adapter.

Can you try one more thing? Add `"console": "integratedTerminal"` to your launch config. This will launch the node process in the integrated terminal. After it dies, check the terminal output for any error message that doesn't show up in the debug console.

**Comment by sant123** [comment]
@roblourens this is what I got:



D:\santiagoah\informacion\Desktop\testing-oracle>cd d:\santiagoah\informacion\Desktop\testing-oracle && node --inspect=29533 --debug-brk appx.js
Debugger listening on port 29533.
Warning: This is an experimental feature and could change at any time.
To start debugging, open the following URL in Chrome:
    chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:29533/ff4966fa-5c46-4f84-96b9-17782ef04c4b
Debugger attached.

D:\santiagoah\informacion\Desktop\testing-oracle>

There's no error after "debugger attached". 😢

**Comment by roblourens** [comment]
This is strange. Since it happens with 'node' and 'node2', I think it's not a problem with the debug adapters. 

You could try with a different version of node, or you could try running that command (with --inspect) in a terminal, and copying the Chrome devtools URL, to see if the same problem appears using chrome devtools.

**Comment by sant123** [comment]
I got this:

![image](https://cloud.githubusercontent.com/assets/7959437/20722568/16b388f2-b635-11e6-94be-54962a334ad0.png)


It's obviously the code has a little error (I'm kidding xD), but this is the reason why the debugger is stopping on mouse hovering.

**Comment by roblourens** [comment]
Well that's the error that you paused on, but when you're at a breakpoint, the debugger shouldn't terminate.

**Comment by sant123** [comment]
@roblourens exactly.

**Comment by roblourens** [comment]
I experimented with different ways of breaking on promise rejection, but still don't see this. But it must be Node terminating because of what it says in the warning. Will have to see if anyone else can repro it.

**Comment by sant123** [comment]
Sure, maybe this is the kind of error that 1 of 1000000000 of people will discover.
