### ISSUE TITLE
Consider to associate "browser storage" with profile

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#159060]
Testing #158809

some UI state is not kept in settings but in browser storage.
For example whether the default action in the editor's drop down menu is "Debug" or "Run". 

![CleanShot 2022-08-24 at 16 04 06@2x](https://user-images.githubusercontent.com/1898161/186439304-30f6320c-1629-4bac-a979-aa0807d6aa66.png)

It would be great if that state would be loaded from a profile, so that an empty profile would always start from a clean state.

**Comment by sandy081** [comment]
@jrieken Does this belongs to your area?

**Comment by jrieken** [comment]
Yeah, I merged @weinand PRs for this ;-) This specific features works with workspace storage: https://github.com/microsoft/vscode/blob/eed1b6ac4907e125fa9188e7a3253bc94cf7aac1/src/vs/platform/actions/browser/menuEntryActionViewItem.ts#L353. I assume profiles are only about global storage, right?

**Comment by sandy081** [comment]
>  I assume profiles are only about global storage, right?

Yes
