### ISSUE TITLE
Conflict decorations in result should not use editor cursor style

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#159020]
The conflict decorations in the result view are read only. That is fine for now.
We should just adjust the cursor style, the current one is the editor cursor and the users will wrongly think that they can copy text from the conflict decoration which is not supported.

We should just use the default cursor arrow. I believe the following css will help
`cursor: default`

fyi @daviddossett

**Comment by hediet** [comment]
Unfortunately this is not easy to do, as the view zone is in the background (please don't increase the z-index 😉).

Setting `cursor: default` has no effect.

**Comment by isidorn** [comment]
Makes sense, thanks for the explanation. 
When we have the widget we could decide if clicking on it does something, for example expands the code.

**Comment by hediet** [comment]
Closing, as the conflict decorations are no longer shown by default.
