### ISSUE TITLE
Transient vs Temporary Profiles

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#159061]
Testing #158809

A "Transient Profile" show up as "Temp 1" in the status bar.

![CleanShot 2022-08-24 at 16 14 38@2x](https://user-images.githubusercontent.com/1898161/186441597-cbd1ce96-9823-4682-b65b-4ffc873b5b5a.png)

Wouldn't it be more consistent if the feature is called "Temporary Profile" (or if we stick with "Transient Profile" use the name "Transient 1")?

**Comment by sandy081** [comment]
Used Temporary.

arg - `--profile-temp`
action - **Create a Temporary Settings Profile**
profile name - **Temp 1**
