### ISSUE TITLE
Sometimes Open with Code doesn't open the file

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode#15908]
- VSCode Version: 1.7.1
- OS Version: Windows 10 Enterprise

Sometimes when VS Code is already opened, trying to use the Open With Code menu on a file doesn't work (has no effect).

I'm not sure how to reproduce this, but it happens from time to time

**Comment by joaomoreno** [comment]
How often does it happen?

**Comment by digeff** [comment]
A few times a month, depending on how much I use VS Code

**Comment by joaomoreno** [comment]
Can you keep an open eye as to what kind of files make this happen? It's hard to figure out what could be wrong without any clues.

**Comment by digeff** [comment]
While it happens, it seems to happen with every file I try to do this with…
If I then close all open VS Code instances, Open with Code starts to work again for all files.
I also noticed that there were a lot of Code.exe instances running while this was happening…

**Comment by sebagomez** [comment]
I've found a way of reproducing this issue.
In my case at least, I have an opened command line all time which is ran as Admin. I usually start code from there `code .` or `code somefile`. When I have opened VSCode like that, I can't use Open with Code anymore, either for a file or folder.

Hope it helps track this annoying bug.

**Comment by joaomoreno** [comment]
This is #1614

**Comment by daschult** [comment]
@joaomoreno How is this related to #1614? That bug is all about Running VS Code as an administrator, whereas this is about VS Code not opening a file? I don't see the connection.

**Comment by digeff** [comment]
It happens quite often to me, and I don't run VS Code as an admin. I still haven't figured out what's the pattern though...

**Comment by daschult** [comment]
For me is really easy to reproduce:
1. Open a command prompt in windows and start VS Code by typing "code ."
2. Open a File Explorer window and try to open a file using Right Click -> Open With Code
The file doesn't open every time for me.

**Comment by joaomoreno** [comment]
@daschult This is quite old now. Can you try to fully reinstall Code?

**Comment by digeff** [comment]
I still had this issue last week, and I usually use the latest version of VS Code.

**Comment by daschult** [comment]
I just uninstalled and reinstalled VS Code and I get the same result that I reported 4 days ago. Can you guys not reproduce it?

**Comment by joaomoreno** [comment]
Can you show me a screenshot of that "Open with Code" action?

**Comment by daschult** [comment]
![image](https://cloud.githubusercontent.com/assets/7052303/23471629/d84ead0e-fe5e-11e6-92c6-8aa076338fca.png)
![image](https://cloud.githubusercontent.com/assets/7052303/23471665/ee42c078-fe5e-11e6-9d3a-ffe63278e93c.png)
![image](https://cloud.githubusercontent.com/assets/7052303/23471688/036fade4-fe5f-11e6-8805-ec40ca08eea1.png)
Ah, I just tried it with a non-administrator command prompt, and it worked, just like you said. However, if I try it from an administrator command prompt, then it does the behavior that I've described.
