### ISSUE TITLE
Authenticating an extension opens new window, doesn't do auth

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159059]
(see recording)

* have no auth for GHINB (tbh for reasons that I don't understand as I use it almost daily)
* select the auth quick fix
* :bug: a new window opens, old window isn't authenticated

https://user-images.githubusercontent.com/1794099/186435653-9363bed9-0f8d-4649-976f-4fda24daad7c.mov

**Comment by TylerLeonhardt** [comment]
Looks like @joaomoreno fixed this in https://github.com/microsoft/vscode-dev/pull/706 ... you may need to clear some browser cache to get this working again.

**Comment by TylerLeonhardt** [comment]
@joaomoreno mentioned that you may need to clear the cache on https://auth.insiders.vscode.dev by going to that domain and clearing the cache.

**Comment by joaomoreno** [comment]
Yeah, from the looks of the recording, you're hitting exactly what was temporarily broken today. @jrieken can you retry tomorrow? All caches should be void by then, since everything is capped to 1h.

**Comment by joaomoreno** [comment]
Hmm I could repro this just now. Reopening...

**Comment by joaomoreno** [comment]
Redeploying with proper fix and flushing edge cache.

**Comment by joaomoreno** [comment]
cc @sandy081 This is what you hit as well

**Comment by joaomoreno** [comment]
Deployed and cache flushed. Give it another try and clear your local cache.

**Comment by jrieken** [comment]
Actually worked without clearing caches (which is the way it should work IMO)

**Comment by joaomoreno** [comment]
Sure, I was just operating under the assumption that your browser cache might be stuck on the 1000-hour mistake.
