### ISSUE TITLE
Edit sessions shows modal dialog

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159014]
Testing #158798

* Continue from web inside desktop
* Let the window sit
* Install update (which restarts the App)
* 🧀 you are instantly greeted with a modal dialog (I wasn't even in that window of VS Code)

Ideas

* don't use a modal but the custom modal overlay which is more friendly and doesn't steep focus
* don't show this when my local changes are no different to those on the server

<img width="1391" alt="Screenshot 2022-08-24 at 09 26 13" src="https://user-images.githubusercontent.com/1794099/186358034-08d248ba-fc16-4da5-878f-a6c8c1202706.png">

**Comment by joyceerhl** [comment]
> don't use a modal but the custom modal overlay which is more friendly and doesn't steep focus

Is the custom modal overlay the same thing as the custom modal dialog, i.e. 

```ts
await this.dialogService.show(Severity.Warning, 'my message', ['my options'], { custom: true });
```

> don't show this when my local changes are no different to those on the server

:+1: I filed https://github.com/microsoft/vscode/issues/159689 for this.
