### ISSUE TITLE
Conflicts not showing in VS Code

### ISSUE THREAD

**Issue by chrisgeek07** [microsoft/vscode#159013]
Type: <b>Bug</b>

The conflicts are not showing up anywhere on VS Code, but when I run my build I can actually see that there are conflicts. I tried to disable the Merge Editor and enable CodeLens but still nothing after restarting VS Code and also my machine...

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 18.7.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|. --crash-reporter-id e8558547-74f5-451a-befa-bbd415136894|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
aws-toolkit-vscode|ama|1.48.0
laravel-extra-intellisense|ami|0.6.2
phpserver|bra|3.0.2
rails|bun|0.17.8
vscode-gemfile|bun|0.4.2
laravel-goto-view|cod|1.3.7
htmlhint|ctf|0.0.1
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.1.2
vscode-npm-script|eg2|0.3.28
vscode-great-icons|emm|2.1.86
prettier-vscode|esb|9.8.0
mithril-emmet|Fal|0.7.7
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.48.1
live-sass|gle|5.5.1
vscode-placeholder-images|Jak|0.1.0
polacode-2019|jef|0.6.1
vscode-colorize|kam|0.11.1
ruby-rubocop|mis|0.8.6
vscode-docker|ms-|1.22.1
sublime-keybindings|ms-|4.0.10
vsliveshare|ms-|1.0.5690
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.20.0
vscode-css-peek|pra|4.2.0
ruby|reb|0.28.1
LiveServer|rit|5.7.5
laravel-artisan|rya|0.0.28
slim|sia|0.1.2
vscode-todo-highlight|way|1.0.5
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30552240

```

</details>

**Comment by bantu** [comment]
@hediet Can you please link to the ticket that is being duplicated?
