### ISSUE TITLE
Unify Merge Conflict/Merge Editor commands

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#159156]
This is quite confusing:

![image](https://user-images.githubusercontent.com/2931520/186630800-5fb19c88-7e6c-4ba5-bf36-ea1d441c08a0.png)

FYI @daviddossett @jrieken

**Comment by jrieken** [comment]
I believe we can't unify but the "old" merge commands should be disabled for the merge editor

**Comment by daviddossett** [comment]
@jrieken does that mean we can fully hide the `Merge Conflict` commands from the command palette when the merge editor is opened? 👍 if so
