### ISSUE TITLE
Changing kernels causes markdown cells to disappear

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#159101]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.71.0-insider (Universal)
Commit: 7ed02a69658fc07f08740b98fa0d8d96c1a61ed4
Date: 2022-08-24T05:18:46.886Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

Steps to Reproduce:

1. Open a notebook
2. Create a markdown cell and ensure you are out of edit mode for the md cell
3. Create a code cell
4. Verify the markdown cell is rendered as expected
5. Change the kernel to something else
6. Markdown cell now dissappears

Only way to get it back is to reload vscode

**Comment by mjbvz** [comment]
Caused by https://github.com/microsoft/vscode/commit/a97d84d3754065a6b54c2f89ca04cba6fb0b1d2b
