### ISSUE TITLE
Prompt for confirmation when removing all breakpoints.

### ISSUE THREAD

**Issue by holland11** [microsoft/vscode#159100]
When trying to delete a single breakpoint, it's not super uncommon for me to accidentally click the Remove All Breakpoints context menu button instead (they are right beside each other and very similarly named). Which can be really annoying when I have quite a few breakpoints set across multiple files. 

This is obviously my fault, but I don't think it would be unreasonable to add a confirmation prompt to this feature to save me from myself. I'm guessing that I'm not alone in making this blunder either.

Thanks!

**Comment by roblourens** [comment]
Sure, but do you always use the context menu to delete breakpoints? Would it be safer to click the X button on the bp row in the debug sidebar, or click the red dot in the editor gutter?

**Comment by holland11** [comment]
That would certainly be safer and is honestly not something I had noticed
until now. Woops. Will try to get in the habit of using that instead. Thank
you!
