### ISSUE TITLE
Extensions - "Reload Required" button does not have rounded corners

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#159162]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/3372902/186637113-74855798-fe2c-4667-a5dc-a4f2927875fd.png">

**Comment by misolori** [comment]
![image](https://user-images.githubusercontent.com/35271042/187290550-cc425ebb-2d35-4fab-9f5d-0d35b96bacfc.png)
