### ISSUE TITLE
Duplicate line in stickyscroll for Python functions

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#159118]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.71.0-insider (Universal)
Commit: 7ed02a69658fc07f08740b98fa0d8d96c1a61ed4
Date: 2022-08-24T05:18:46.886Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
Steps to Reproduce:

1. Install Python Extension (not sure if this is required or not)
2. Create a python file with the following code:
```
""" Hello World """

def do_something():
    """Hello World"""
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)
    print(1)

```
3. Stick scroll will end up duplicating the sticky line 

See here
![Recording 2022-08-25 at 09 23 18](https://user-images.githubusercontent.com/1948812/186540558-11479e33-fcad-4519-b434-fec5aa96b8c3.gif)

**Comment by aiday-mar** [comment]
Hi thank you for filing the bug. I have just tested on my computer. My parameters of VS Code are:

Version: 1.71.0-insider (user setup)
Commit: 7ed02a69658fc07f08740b98fa0d8d96c1a61ed4
Date: 2022-08-24T05:18:03.269Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

I have installed the Pylance and the Python extensions developed by Microsoft. I get the following behavior. 

![sticky-scroll-python](https://user-images.githubusercontent.com/61460952/186603026-08cd6c33-253f-4163-b12a-e69d15704b5d.gif)

**Comment by jrieken** [comment]
> Install Python Extension (not sure if this is required or not)

@DonJayamanne Just to clarify - the data model of the sticky scroll is the language extension that also provides the data for outline and breadcrumbs. So, that matters and is likely an issue such that the extension doesn't return data in the shape that we expect

**Comment by DonJayamanne** [comment]
Updated vscode insiders today and then tried disabling/enabling extensions to figure out which extension caused this issue and now I can no longer repro this issue.
Weird, I only use the standard Python extension  and the corresponding language server (Pylance)

Closing this as I can no longer repro this.
