### ISSUE TITLE
Screen flickering on my ubuntu 22.04

### ISSUE THREAD

**Issue by moon21bd** [microsoft/vscode#159143]
My screen continuously flickering in Ubuntu 22.04 when ever I open vs code.

![Screenshot from 2022-08-25 12-55-31](https://user-images.githubusercontent.com/7630256/186596133-2f455140-7a60-4638-b589-1f6a8e47c18f.png)

**Comment by connor4312** [comment]
Does running VS Code with `code --disable-gpu` solve this issue?

**Comment by deepak1556** [comment]
Please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
