### ISSUE TITLE
Integrate a small In-VSCode Browser

### ISSUE THREAD

**Issue by soumya-99** [microsoft/vscode#159142]
Sometimes, we have to rely on the external browsers while coding. But with this feature, they can view it inside from the vscode. Some extension developers can use the In-VSCode Browser API to open their links/apis.

#FeatureRequest #InBuiltBrowser #VSCode

**Comment by gjsjohnmurray** [comment]
Please try using the `Simple Browser: Show` command from the Command Palette.

Extension developers already have the [Webview API](https://code.visualstudio.com/api/extension-guides/webview).

In both cases, be aware that some websites do not permit themselves to be embedded in other pages. So for example the URL https://google.com produces a blank page in a Simple Browser tab, but https://georgejames.com displays OK.
