### ISSUE TITLE
Merge conflict UI

### ISSUE THREAD

**Issue by lizzthabet** [microsoft/vscode#159192]
Type: <b>Feature Request</b>

I'm really confused by the new merge conflict UI. In the old UI, I could clearly and quickly resolve conflicts line-by-line with the "Accept Current Change," etc. menus.  I don't understand how to use this new UI with three panes. I understand the views, but I don't have the same line-by-line control that I want. 

I poked around in the VS Code docs to see if I could find information on how to use the new editor format, but I only see screenshots of the old UI.

VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Modes:

**Comment by Withyooou** [comment]
I'm also confused about this new merge conflict UI. In my opinion, it's not as clear as the original one and it makes me confused when I merge codes. Maybe VS Code can provide a configuration items for developers to choose which UI to use.

**Comment by eddysims** [comment]
I agree with this. I find it much harder to use. I spend waaaaay longer on conflicts now. would be nice to have some sort of instruction

**Comment by tjdraper** [comment]
I'm so disappointed and irritated. VSCode did have the best UI and merge management. I opened it today to solve a merge conflict and I immediately started looking for a way to revert. This new UI is SO BAD. And the old one was SO GOOD!

**Comment by utilityboy** [comment]
You can revert to the old style by disabling the merge editor feature in settings:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/130537/186767730-9c0f9778-8e25-405f-8643-c84642f10256.png">

**Comment by Rabbitzzc** [comment]
It's too hard to use. Anti-human design...🤕

**Comment by Nawbc** [comment]
The layout is so confusing and I cloud forgot to check without highlighting. 🤯

**Comment by liujianchao1995** [comment]
难用至极

**Comment by liujianchao1995** [comment]
> You can revert to the old style by disabling the merge editor feature in settings:
> 
> <img alt="image" width="509" src="https://user-images.githubusercontent.com/130537/186767730-9c0f9778-8e25-405f-8643-c84642f10256.png">

谢谢，我找了一天恢复方法，终于在这里找到了，旧版非常好用。

**Comment by TommasoAmici** [comment]
> You can revert to the old style by disabling the merge editor feature in settings:
> 
> <img alt="image" width="509" src="https://user-images.githubusercontent.com/130537/186767730-9c0f9778-8e25-405f-8643-c84642f10256.png">

This settings doesn't do anything for me on v1.70.2, I keep seeing the new UI even after disabling it

**Comment by lizzthabet** [comment]
thanks, @utilityboy! i can use the previous merge ui by turning off the merge editor setting. (i was using vscode version 1.70.1 on macos when testing the setting.)

in the interest of leaving more thoughtful feedback (than my initial frustrated issue 😅):

* it wasn't immediately clear how i was supposed to use the new split three-pane editor to resolve a complex merge conflict in a specific file.
* as someone trying to solve a problem (resolving conflicts) that was blocking me from other work, i felt frustrated that there weren't clear steps i could take to use the new ui. with a new view / feature, i might expect a toast or banner that explained there was setting to related to the new view or documentation explaining how i should use it.
* i do see the value in being able to see the three files (a, b, and their resolved view, c), since that can sometimes be hard to derive when you're just looking at the conflicts in-line.
* however, the new view doesn't help me quickly resolve conflicts, line-by-line. the previous ui more clearly labeled the current and incoming changes and let me choose which changes i wanted to keep by clicking a button. with the new ui, i attempted to copy and paste from the top two split views into the third, and i ended up making mistakes with how i resolved the conflicts.

**Comment by enjibby** [comment]
I also found this new UI confusing, in particular as it is called "3-way merge" when it does not include a pane for the original code that I find so invaluable. Once I had set `merge.conflictstyle` to `diff3`, the old VSCode UI was excellent to use, but I feel I'd lost that functionality when the new UI unexpectedly popped up.

As always, thankyou for an excellent product.

**Comment by zhouJiecode** [comment]
for this design, i can't understand. what are you thinking? .......

**Comment by ThreePalmTrees** [comment]
<img width=300 src="https://memegenerator.net/img/instances/42284691.jpg" alt="Aliens meme guy saying Microsoft" />

**Comment by utilityboy** [comment]
The August 2022 (1.71) release goes a very long way to address a number of the usability issues and provides options to maintain use of old inline merge conflict editing if desired.  Very nice improvements there.

**Comment by lizzthabet** [comment]
it looks like there are a couple of issues (#158523, #156608) where very similar feedback has been given and discussed. i'm going to close this issue as a duplicate.
