### ISSUE TITLE
Real Time Collaboration

### ISSUE THREAD

**Issue by lastnod** [Microsoft/vscode#15916]
- VSCode Version: 1.7.2
- OS Version: Windows 10

enhancement : add posibility to code like on cloud9 or eclipse che

**Comment by RationalCoding** [comment]
Still in early stages, but you can try out my extension [multihack-vscode](https://github.com/RationalCoding/multihack-vscode).

Syncs changes across an entire workspace and is compatible with the Adobe Brackets extension and a web editor. 

Uses P2P tech so it's free and fast :)

**Comment by brunolm** [comment]
multihack is not currently published https://github.com/multihack/multihack-vscode/issues/3

I tried https://github.com/sockscode/sockscode-vscode but it is really buggy, it is impossible to use.

I tried https://github.com/THE-WIRE/RT-Code-Collab but when I try to connect it says the command doesn't exist.

Does anyone know an extension that works?

Obs: btw, Atom just added that feature https://twitter.com/AtomEditor/status/930829316585275392

**Comment by brunolm** [comment]
Apparently VSCode already have this feature, but it is not yet open.

Looks like you can signup for it here https://aka.ms/vsls-signup

**Comment by RationalCoding** [comment]
https://code.visualstudio.com/blogs/2017/11/15/live-share

**Comment by a9rkzz** [comment]
While Live Share will soon an option, could multihack potentially be used as a starting point for integration with Atom's teletype? The underlying ideas seem to have a decent bit of overlap.

**Comment by amackintosh** [comment]
This functionality brings a tear to my eye. I've been waiting years for it.

**Comment by RationalCoding** [comment]
@a9rkzz Different CRDT data models (Live Share might even use Operational Transform). Maybe something could be made to bridge them? We'll have to wait and see if this helps us do inter-editor collab.

**Comment by KelSolaar** [comment]
Atom's Teletype looks great: https://blog.atom.io/2017/11/15/code-together-in-real-time-with-teletype-for-atom.html

**Comment by chrisdias** [comment]
[Live Share!](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare)

**Comment by jens1o** [comment]
Not free software, not being used. Feature Request not fulfilled. Reopen this please, @chrisdias.

> We will be evaluating the introduction of paid tiers with advanced features as we better understand the needs of the community.

It's even better, I won't route data to anywhere on the world to Microsoft servers, so there's nothing to pay for. I'm excited for the time you will shut down the servers. Who cares about P2P and distributing everything? Do you really need that power? Is there even an option to disable data collection? I don't find this option in the (too) long privacy policy.
