### ISSUE TITLE
Use bracketed paste for "Run Selected Text In Active Terminal"

### ISSUE THREAD

**Issue by tstenner** [microsoft/vscode#159153]
The "Run Selected Text In Active Terminal" function (especially with a key binding) is invaluable for quickly testing snippets in bash scripts. Unfortunately, the input is interpreted by the interactive terminal when tabs are used for indentation:

``` bash
STR="Foo
		Bar"  # two tabs
```

Running this snippet leaves the terminal like this:

```
STR="Foo
> 
Display all 2389 possibilities? (y or n)
```

For most terminals, setting `set enable-bracketed-paste on` in the `.inputrc` or running `bind 'set enable-bracketed-paste on'` skips the terminal handling for pasted text (see [bracketed paste](https://en.wikipedia.org/wiki/Bracketed-paste)).

The integrated terminal should use bracketed paste (and set this option) by default.

Currently, it can be circumvented by running `bind 'set disable-completion on'`, but then I would have to enable it manually again before using the terminal interactively.

**Comment by tstenner** [comment]
Addendum: manually pasting the block with Strg+Shift+V works as intended

**Comment by Tyriar** [comment]
If we do this we need to be careful of edge cases like https://github.com/microsoft/vscode/issues/153592#issuecomment-1182045382
