### ISSUE TITLE
Make eager service registration explicit and revisit existing one

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159178]
The [`registerSingleton`](https://github.com/microsoft/vscode/blob/fb7039f716639f2cb8ad3e0bc449973ab738c549/src/vs/platform/instantiation/common/extensions.ts#L25)-function supports a `supportsDelayedInstantiation`-argument. 

With [`InstantiationType.Delayed`](https://github.com/microsoft/vscode/blob/fb7039f716639f2cb8ad3e0bc449973ab738c549/src/vs/platform/instantiation/common/extensions.ts#L22) only proxies of services are injected and the actual instantiation happens in "slack/idle" time or at time of first actual use (whatever comes first). This is often overlooked and the default (`false`, eager) is used. This issue is about: 

* revisit existing eager usages and check if they can support delayed instantiation. This is the _preferred_ way, helps startup performance 🐎 , and is usually possible
* make the eager variant explicit, use `InstantiationType.Eager`, and feel a little bad about it 😳 

_Note_ that `Eager` should only be needed if your service is doing something "by its own", like reading files or so, which is vital to other parts of the system. This should be the exception because most services offer something (a service) to others which means can be delayed until needed

**Comment by jrieken** [comment]
@sandy081 starting with you because many of your services show as eager

**Comment by sandy081** [comment]
@jrieken adopted those service I own

**Comment by jrieken** [comment]
@bpasero you are next :-)

**Comment by bpasero** [comment]
Also did https://github.com/microsoft/vscode/pull/159972 which forces every remote service (i.e. a service that talks to the main process or shared process) to be lazy. All of these services did already declare laziness but now its just enabled by default.

**Comment by jrieken** [comment]
> would be nice to somehow signal back that service cannot be lazy so that we know which ones are not acknowledged (I guess that is the purpose of this issue but might be nicer to validate in code)

I like - I'll add another falsy value like "eager" or so

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/pull/160061

**Comment by sandy081** [comment]
> would be nice to somehow signal back that service cannot be lazy so that we know which ones are not acknowledged (I guess that is the purpose of this issue but might be nicer to validate in code)

This would be useful for revisiting.

**Comment by jrieken** [comment]
@bpasero @sandy081 You can now use `InstantiationType.Eager` to mark a service as purposefully eager

**Comment by bpasero** [comment]
@jrieken I think another set of lazy services to look at is those that do not use `registerSingleton` but just `SyncDescriptor`:
* [`sharedProcessMain`](https://github.com/microsoft/vscode/blob/1995346bc5d6ed49ba3ff31151423afec9c1797e/src/vs/code/electron-browser/sharedProcess/sharedProcessMain.ts#L261)
* [`app.ts`](https://github.com/microsoft/vscode/blob/1995346bc5d6ed49ba3ff31151423afec9c1797e/src/vs/code/electron-main/app.ts#L621)
* [`main.ts`](https://github.com/microsoft/vscode/blob/1995346bc5d6ed49ba3ff31151423afec9c1797e/src/vs/code/electron-main/main.ts#L201)
* [`cliProcessMain.ts`](https://github.com/microsoft/vscode/blob/1995346bc5d6ed49ba3ff31151423afec9c1797e/src/vs/code/node/cliProcessMain.ts#L173)

I assume setting a `SyncDescriptor` to lazy, has the same effect?

//cc @sandy081 since many services are extension related, especially in the non-workbench-window processes.

**Comment by jrieken** [comment]
> I assume setting a SyncDescriptor to lazy, has the same effect?

Yeah, it is the same

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/pull/160188 does quite a few, even those that I do not consider owning.

**Comment by sandy081** [comment]
Went through all services I own in all processes and adopted.

**Comment by bpasero** [comment]
@jrieken my change in https://github.com/microsoft/vscode/pull/160188 results in exceptions:

```
ERR [uncaught exception in main]: Event not found: onDidFocusWindow: Error: Event not found: onDidFocusWindow
    at Object.listen (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:799:27)
    at ChannelServer.onEventListen (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:281:35)
    at ChannelServer.onRawMessage (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:229:33)
    at /Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/common/ipc.js:177:73
    at Listener.invoke (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:457:27)
    at PrivateEventDeliveryQueue.deliver (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:627:38)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:592:37)
    at /Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:69:93
    at Listener.invoke (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:457:27)
    at PrivateEventDeliveryQueue.deliver (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:627:38)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:592:37)
    at /Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:82:106
    at Listener.invoke (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:457:27)
    at PrivateEventDeliveryQueue.deliver (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:627:38)
    at Emitter.fire (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:592:37)
    at fn (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/common/event.js:276:44)
    at IpcMainImpl.wrappedListener (/Users/bpasero/Development/Microsoft/vscode/out/vs/base/parts/ipc/electron-main/ipcMain.js:25:21)
    at IpcMainImpl.emit (node:events:526:28)
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:161:11014)
    at EventEmitter.emit (node:events:526:28)
```

I wonder if we hit a case where lazy instantiation does not work well with a proxy when there is another proxy involved, because for some of the main-side services we use a utility to expose the service to another process:

https://github.com/microsoft/vscode/blob/c2cc481940d538a41c311411484ffc909b8054b8/src/vs/code/electron-main/app.ts#L786-L787

I think given this I will have to go back to eager instantiation for those services that are remote accessible. Likely an issue because I am enumerating the properties here:

https://github.com/microsoft/vscode/blob/c2cc481940d538a41c311411484ffc909b8054b8/src/vs/base/parts/ipc/common/ipc.ts#L1043-L1048

**Comment by sandy081** [comment]
Right, this seems to be because of double usage of proxies. Because, those services on shared process which I made lazy and support channels seem to work as I do not use `ProxyChannel` util.

**Comment by jrieken** [comment]
Makes sense to keep them eager. I also believe that a proxy of a proxy doesn't help in perf. 

> Not 100% sure I can workaround this by doing this at a later stage when the lazy service is actually instantiated...

At the end this might be a bug with the delay-proxy as it likely doesn't react to APIs that's called on it to fullfill the `for-in` contract

**Comment by sandy081** [comment]
Adding following to the list of `SyncDescriptor` usage

- [serverServices](https://github.com/microsoft/vscode/blob/c2cc481940d538a41c311411484ffc909b8054b8/src/vs/server/node/serverServices.ts#L79)
- [remoteExtensionHostAgentCli](https://github.com/microsoft/vscode/blob/c2cc481940d538a41c311411484ffc909b8054b8/src/vs/server/node/remoteExtensionHostAgentCli.ts#L77)

**Comment by bpasero** [comment]
Yeah it will not change much in perf, will review more carefully again tomorrow, for now I revert to unblock insiders: https://github.com/microsoft/vscode/pull/160202

**Comment by bpasero** [comment]
Ok, second attempt: https://github.com/microsoft/vscode/pull/160273

(its quite tricky to know whether a service is proxied or not, you have to do a fulltext search ala `fromService.*<name of service>`)

**Comment by jrieken** [comment]
Adding @TylerLeonhardt and @lramos15 for your services

**Comment by lramos15** [comment]
I don't believe my services can be lazy. The resolver is definitely needed immediately at startup especially if you're opening something from the code-cli. If the telemetry service is lazy we also miss recording any startup events. Feel free to correct me if I'm wrong as I am not super familiar with how lazy instantiation works

**Comment by jrieken** [comment]
> If the telemetry service is lazy we also miss recording any startup events.

Only if the telemetry service logs messages by itself, e.g without any external consumer calling `publicLog` on it. As soon as a consumer starts to use the service it is being created and things works

**Comment by aeschli** [comment]
The `WorkbenchThemeService` should stay eager as the constructor restores the last used colors from storage. This needs to happen as quickly as possible for a flicker free startup experience.

**Comment by jrieken** [comment]
> The WorkbenchThemeService should stay eager as the constructor restores the last used colors from storage. This needs to happen as quickly as possible for a flicker free startup experience.

@aeschli That makes sense but please "document" this via `[InstantiationType.Eager](https://github.com/microsoft/vscode/blob/fb7039f716639f2cb8ad3e0bc449973ab738c549/src/vs/platform/instantiation/common/extensions.ts#L22)`

**Comment by jrieken** [comment]
Thanks everyone!
