### ISSUE TITLE
improve source path matching

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1591]
the VSCode debugger architecture assumes that debugger, debug-adapter and VSCode sit on the same filesystem and refer to files through the exact same path.
This makes it impossible to use VSCode in remote debugging scenarios, e.g. Docker setups.

**Comment by silverbp** [comment]
:+1:

**Comment by rnordin100** [comment]
Nice

**Comment by silverbp** [comment]
this isn't just source path mapping btw, it doesn't support remote debugging for node either although maybe that's done on purpose and isn't a lot of work to re-enable/enable that.

**Comment by weinand** [comment]
@silverbp yes, remote debugging requires more (for one, node's debug port cannot be accessed externally so a proxy or forwarding mechanism is always required).
But this feature-request is only about the path matching aspect.

**Comment by silverbp** [comment]
Somewhere along the line node is no longer binding the debug port to 127.0.0.1, because you can now get to it externally, at least on node 5.0+. I was using balance to forward the port out of the container, but it's no longer required. I guess I was referring to the fact that vscode no longer supports an address property when attaching to a node process.

**Comment by silverbp** [comment]
for instance with node cli, I can do: `node debug 192.168.99.100:5858` but vscode only lets you attach to a port and doesn't let you specify the address.

**Comment by weinand** [comment]
@silverbp yes, we've removed the address attribute because earlier versions of node did not support external addresses and it was confusing users. I've created https://github.com/Microsoft/vscode-node-debug/issues/32 to add the "address" attribute back for the January drop.
