### ISSUE TITLE
Installer stuck

### ISSUE THREAD

**Issue by RussKie** [microsoft/vscode#159141]
I'm observing that VS Code is yet again decided to update itself without my explicit approval. VS Code is installed via Chocolatey, but I'm not aware of Chocolatey auto-updating app. I have multiple apps installed via Choco, and VS Code is the only one I'm consistently having issues with (e.g, https://github.com/microsoft/vscode/issues/147763, https://github.com/microsoft/vscode/issues/158543)...

It's been now few days (I don't shutdown or restart the workstation for days), and the installer appears stuck:
![image](https://user-images.githubusercontent.com/4403806/186586491-4f7e36d4-e509-4fb2-a999-c61b4793d0de.png)

![image](https://user-images.githubusercontent.com/4403806/186587857-80de6b18-bb8b-4d61-b22a-7e48f6bd4971.png)
![image](https://user-images.githubusercontent.com/4403806/186586606-c2f88984-c406-470e-8ba2-9d4e54379d73.png)

```
path: C:\Windows\IMECache\36544169-c806-4127-a407-a51328885448_1\VSCodeSetup-x64-1.70.1.exe
command line: VSCodeSetup-x64-1.70.1.exe /VERYSILENT /MERGETASKS=!runcode

path: C:\Windows\Temp\is-P3QLG.tmp\VSCodeSetup-x64-1.70.1.tmp
command line: "C:\WINDOWS\TEMP\is-P3QLG.tmp\VSCodeSetup-x64-1.70.1.tmp" /SL5="$E300FA,81820394,828416,C:\WINDOWS\IMECache\36544169-c806-4127-a407-a51328885448_1\VSCodeSetup-x64-1.70.1.exe" /VERYSILENT /MERGETASKS=!runcode
```

I have no idea what process initiated the installation process, or how it did so...

**Comment by joaomoreno** [comment]
> VS Code is installed via Chocolatey, but I'm not aware of Chocolatey auto-updating app.

Sadly, we do not officially distribute nor support Code via Chocolatey. Our installer is configured with automatic updates by default and the Chocolately package seems not not have disabled that.

I recommend not using Chocolatey but simply install the setup package from https://code.visualstudio.com/Download
