### ISSUE TITLE
Release notes opens a tab in every window.

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#15915]
- VSCode Version: 1.7.1

Steps to Reproduce:

1. Run 1.7.1
2. Get upgrade message.
3. Click on "show release notes" button in banner.
4. "Code" menu -> "Restart".
5. Release notes is now open as a tab in every window.

I don't know if step 3 actually opened it in every window (I didn't check), or whether it was the restart in 4 that did it.

Also, it's a bit dubious that the banner disappears in step 3. I wanted to read the releases and then upgrade, but since the banner disappears, I have to go through the Code menu. Create separate issue?

**Comment by atombender** [comment]
Anyone working on this? It's super annoying every time there's a new release. I typically have a dozen windows open. (Also, sometimes VSCode forgets its state after quitting, and the release notes come back.)

**Comment by joaomoreno** [comment]
#25800
