### ISSUE TITLE
Shortcut `resolveProfileForBrowserWindow` for when 1 profile?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159173]
An idea to reduce work on the critical startup path for opening a window: if there is only 1 profile overall, return default profile.

https://github.com/microsoft/vscode/blob/57945a1416f02a6f74a7d7bf3be38454f2722b95/src/vs/platform/windows/electron-main/windowsMainService.ts#L1472-L1489

PS: method misses a return type annotation.

**Comment by sandy081** [comment]
We can but this will not remember that the workspace was opened with the default profile and opening this workspace again from a window that has a different profile opens this workspace with that profile.

**Comment by bpasero** [comment]
Oh ok, so we need to distinguish a window having a default profile from a window that was never opened to use the new profile for the window?

**Comment by sandy081** [comment]
Yes
