### ISSUE TITLE
Newline missing in markdown rendering

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#159161]
Given a HoverProvider that returns content like this:

```
String
*package:dartcode_flutter_4118/main.dart*

---
Documentation here
```

The rendering is missing the first newline:

![Screenshot 2022-08-25 at 10 57 52](https://user-images.githubusercontent.com/1078012/186635455-35744d8b-ad79-4304-94df-65b79d530c1f.png)

If I put the same markdown into GitHub, it renders with a newline:

![Screenshot 2022-08-25 at 10 58 22](https://user-images.githubusercontent.com/1078012/186635547-42bd8ce2-6b49-4223-a507-c27be05656d0.png)

I'm not which one is correct, but GitHub's seems correct to me - I don't see why the newline should be removed.

**Comment by mjbvz** [comment]
In markdown, consecutive lines are [rendered as a single paragraph](https://spec.commonmark.org/0.30/#paragraphs). You can see this in [CommonMark's rendering of that example](https://spec.commonmark.org/dingus/?text=String%0A*package%3Adartcode_flutter_4118%2Fmain.dart*%0A%0A---%0ADocumentation%20here)

Github seems has opted not to implement this for rendering comments

You can prevent this by adding two space characters at the end of a line

**Comment by DanTup** [comment]
Ah, good to know - thanks!

**Comment by DanTup** [comment]
> You can prevent this by adding two space characters at the end of a line

Is there any reason to do this rather than just insert an additional newline?

**Comment by DanTup** [comment]
@mjbvz ah, gotcha. Thanks!
