### ISSUE TITLE
I would like better support for multiple cursors.

### ISSUE THREAD

**Issue by mblander** [Microsoft/vscode#15917]
I would like some better support for multiple cursors like PHPStorm and WebStorm have.
Features like: 
- Selecting multiple different words by alt-clicking
- Copy/cut/paste per cursor
- Emmet support per cursor

See: https://www.youtube.com/watch?v=aqGNM4rvyOE

**Comment by alexandrudima** [comment]
@mblander 

- Selecting multiple different words by alt-clicking -> **this works today, but the modifier is ctrl-clicking**
- Adding a selection to the next occurence of a word -> **this works today, ctrl-d**
- Copy/cut/paste per cursor -> **this works today, perhaps there is a specific scenario that is not working? -> please file an issue with the specific problem**
- Emmet support per cursor -> tracked in #1050
