### ISSUE TITLE
Go to definition / Hovering and hinting seems to be broken in 1.7.2

### ISSUE THREAD

**Issue by brown339** [Microsoft/vscode#15914]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|githistory|donjayamanne|0.1.0|
|es6-angular-snips|kasperkeso|0.0.3|
|debugger-for-chrome|msjsdiag|2.2.2|
|debugger-for-ios-web|msjsdiag|0.1.2|
|whitespace|sandcastle|0.0.4|
|trailing-spaces|shardulm94|0.2.11|
|cordova-tools|vsmobile|1.2.3|

---

Steps to Reproduce:

1. Create a simple function `function bar () {}`
2. Create a variable and assign it to the function `var foo = bar;`
3. Notice how right-clicking on bar and selecting `Go to definition` does not jump to the function
4. Notice how holding the `cmd` key over the assigned function doesn't highlight or show information about the function.

### Version 1.6 (Working)
![code1_6](https://cloud.githubusercontent.com/assets/3903921/20540351/ed078b8e-b0c6-11e6-863a-ef1e24ddf8b5.gif)

### Version 1.7 (Not working)
![code1_7](https://cloud.githubusercontent.com/assets/3903921/20540385/07f6fe8e-b0c7-11e6-92ea-3102c61850db.gif)

**Comment by brown339** [comment]
Underlying issue may be that no symbols are being found. Not sure why that is.

### 1.7 (Same file)
![image](https://cloud.githubusercontent.com/assets/3903921/20540797/94d816b6-b0c8-11e6-9088-74b3a9509bcc.png)


### 1.6 (Same file)
![image](https://cloud.githubusercontent.com/assets/3903921/20540850/b6918a94-b0c8-11e6-9bef-34d00b042ab8.png)

**Comment by mjbvz** [comment]
I'm unable to reproduce this problem in my testing. What does your workspace look like? Is there a `jsconfig.json` or `tsconfig.json`

To help with our investigation, please try adding `"typescript.tsserver.trace": "verbose"` to your settings and restarting VSCode. Open the js file with the error and then share the results of the `Output panel -> TypeScript`.

Thanks.

**Comment by brown339** [comment]
A few restarts seem to have resolved the issue. Feel free to close.

**Comment by mjbvz** [comment]
Ok. Please let us know if you start seeing this again.

Thanks.
