### ISSUE TITLE
Underscore rendererd funny in terminal

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#159193]
Version: 1.71.0-insider
Commit: 7ed02a69658fc07f08740b98fa0d8d96c1a61ed4
Date: 2022-08-24T05:18:31.474Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.14.0-1048-oem
Sandboxed: Yes

- open the terminal, type `_`
![image](https://user-images.githubusercontent.com/6461412/186709300-3a97df34-656a-4bfd-9039-1d6979fb0acf.png)

**Comment by Tyriar** [comment]
This is fixed in latest, update xterm-addon-webgl in Code-OSS

/duplicate #158497
