### ISSUE TITLE
Search doesn't always work on files drag-and-dropped into VS Code

### ISSUE THREAD

**Issue by erikschmitz** [microsoft/vscode#159127]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2 (user)
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Select more than one (let's say five) text files using Windows Explorer or on the Desktop
2. Drag and drop them into visual studio code, all five in one fell swoop.
3. Click the Search Icon or go to Edit -> Find in Files or press CTRL-SHIFT-F
4. Search for a term that you know exists in all the files
5. Note that the only file searched is the one that was opened/displayed in the editor
6. Click through the other 4 files so each displays in the window
7. Search again and note that now, all 4 files are searched.
8. Note that this behavior does not occur if you select the 5 files on the desktop or in windows explorer, and use the right click context menu "open with code", or if you drag and drop each file into the window one-by-one.

**Comment by roblourens** [comment]
Known issue - these files out of your workspace won't be searched until they have actually been opened in an editor.

This is covered by https://github.com/microsoft/vscode/issues/20530 (it sounds like a different issue but is essentially the same work)
