### ISSUE TITLE
VSCode open folder

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#159131]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.69.2
- OS Version: centos7.9

Steps to Reproduce:

1. Open VSCode in linux baed on Centos7.9
2. when  I open folder, the toast is not on the top, I can not find it
3. I can not select the folder
4. I think it is a serious bug, can you help to fix it ?

**Comment by 18392152392** [comment]
It is a serious bug

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
