### ISSUE TITLE
Code Lens is all over the place

### ISSUE THREAD

**Issue by flq** [Microsoft/vscode#15918]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|csharp|ms-vscode|1.5.2|

---

Steps to Reproduce:

1. Open any valid code 
2. Look at the UI
<img width="850" alt="screen shot 2016-11-22 at 21 57 57" src="https://cloud.githubusercontent.com/assets/123748/20541769/d7f7f6c4-b0fe-11e6-9416-44cd71590595.png">
<img width="592" alt="screen shot 2016-11-22 at 21 58 29" src="https://cloud.githubusercontent.com/assets/123748/20541771/d8173412-b0fe-11e6-971c-6172cbb7bfc9.png">

**Comment by flq** [comment]
Well, it seems that vertically it is at the correct height.

**Comment by joaomoreno** [comment]
This has been fixed since. Can you get the update to 1.7.2, released yesterday and confirm?

![image](https://cloud.githubusercontent.com/assets/22350/20555737/d05f814c-b163-11e6-90ad-0e6c4d1389ea.png)

**Comment by flq** [comment]
Can confirm it is repaired, thanks!
