### ISSUE TITLE
Remember the workspace/space vscode was on fresh start/login

### ISSUE THREAD

**Issue by jd-solanki** [microsoft/vscode#159140]
Hi,

This is a minor but annoying issue I am facing with vscode. Certainly, you can close this if you find this invalid.

I have 3 vscode opens during my day and I separate my application windows by space/workspace (in mac or workspace in Ubuntu). Now the problem is whenever the next morning I open the vscode it opens all the windows but unlike chrome, it doesn't remember which window was in which workspace previously. All vscode windows just open in a single workspace.

Thanks.

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/152869, https://github.com/microsoft/vscode/issues/123517, https://github.com/microsoft/vscode/issues/138319
