### ISSUE TITLE
It is not possible to rebind / turn off Alt+Space for title bar customization

### ISSUE THREAD

**Issue by mareolan** [microsoft/vscode#159167]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Windows 10

Steps to Reproduce:

1. I use Alt+Space for window maximizing, which now clashes with title bar customization introduced in July 2022 release. I like the original behaviour of Alt+Space way more, but there seems to be no way to turn off the title bar customization, nor to unbind/change key binding for it. Please allow the original Alt+Space behaviour.

**Comment by sbatten** [comment]
Alt+Space's original behavior still works if the mouse is not over the title bar. Or if you right click the top left corner of the title bar.
