### ISSUE TITLE
Utility process error

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#159183]
I have gotten the following error several times:
```
  ERR Error received from starting extension host (kind: LocalProcess)
log.ts:313   ERR Error: Cannot use UtilityProcess!
```

The first time I got this error, I was running code OSS using the default F5 action in microsoft/vscode.  I wasn't able to run the OSS build again until I rebooted my PC. `window.experimental.useSandbox` was `false`. `extensions.experimental.useUtilityProcess` was `true`.

Now, I have also gotten this error in VS Code insiders. `window.experimental.useSandbox` and `extensions.experimental.useUtilityProcess` were both `true`. I had to set `window.experimental.useSandbox` to `false` after the error so that I could keep using insiders.

**Comment by bpasero** [comment]
I cannot reproduce on my Windows machine. The settings are enabled by default, I assume it makes no difference if you remove them? Does it help to start with a fresh user data dir?

**Comment by alexr00** [comment]
Now it works on both insiders and OSS for me. I'll try a fresh user data dir next time I see it.

**Comment by bpasero** [comment]
To clarify, neither sandbox nor utility process will work in OSS unless you had manually downloaded our internal builds. Enabling sandbox will enable utility automatically.

**Comment by alexr00** [comment]
I didn't manually download any builds for OSS. I just ran the "VS Code" launch config.

**Comment by bpasero** [comment]
Yeah, let me know if you still see issues for Code Insiders.

**Comment by alexr00** [comment]
Just saw the issue again on OSS. `window.experimental.useSandbox` was `true`.

**Comment by bpasero** [comment]
@alexr00 hm, I cannot reproduce, at least from a fresh user data dir (via `--user-data-dir`):

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/900690/186824554-471fc5ee-9142-49bd-ad70-404cbc3b96cb.png">

From the code, the condition to enable sandbox is this:

https://github.com/microsoft/vscode/blob/35b971c92d210face8c446a1c6f1e470ad2bcb54/src/vs/workbench/electron-sandbox/desktop.contribution.ts#L245

Can you maybe print the output of `product.quality` somewhere in your Code OSS to see if you have a value there?

**Comment by alexr00** [comment]
🤦‍♀️ I had set the quality to test something else out.

**Comment by bpasero** [comment]
Ah nice that explains it!

**Comment by bpasero** [comment]
If you see this again in insiders, please reopen. As for Code OSS, I think we figured out the reason.
