### ISSUE TITLE
React/JSX bracket formatting

### ISSUE THREAD

**Issue by ksrb** [Microsoft/vscode#15929]
- VSCode Version: 1.7.2
- OS Version: OSX 10.11.6

Remove extra space space in inline javascript for brackets `}}`

Actual:
```javascript
<input ref={(ref) => { this.inputref = ref; } } />
```

Expected:
```javascript
<input ref={(ref) => { this.inputref = ref; }} />
```

**Comment by mjbvz** [comment]
Thanks. I've opened a bug against Typescript to track this: https://github.com/Microsoft/TypeScript/issues/12456

**Comment by mjbvz** [comment]
Closing since this is tracked on the TypeScript side now.
