### ISSUE TITLE
VS Code Install While Windows Firewall Enabled Causes "CreateProcess failed; code 216"

### ISSUE THREAD

**Issue by mattflix** [Microsoft/vscode#15926]
- VSCode Version: 1.7.2
- OS Version: Windows 10 10586.679

My experience:

1. Starting with non-working VSC 1.7.2 (code.exe gives "CreateProcess failed; code 216").
2. I uninstalled VSC.
3. I disabled the Windows Firewall.
4. I re-installed VSC.
5. Newly-installed VSC launches fine.
6. I re-enabled the Windows Firewall.
7. VSC still launches fine.
8. I uninstalled VSC.
9. I re-installed VSC (from exactly the same installer .exe used in Step 4) -- note that the firewall is still enabled at this time.
10. Newly-installed VSC does not work again (code.exe back to giving "CreateProcess failed; code 216").

At this point, note that I was also able to repeat Steps 1-5 to get back to a working VSC. The "breakage" or "non-breakage" of the installed code.exe, which is apparently dependent on the state of the Windows Firewall during installation, is completely repeatable for me at this time.

(I actually did the above cycle multiple times, until I convinced myself that simply turning the firewall on/off would break/not-break the installation.)

The Windows Firewall (when enabled) seems to affect VSC installation in some way that leaves code.exe unable to run.

Maybe the VS Code team and the Windows Firewall team need to have a chat?

**Comment by joaomoreno** [comment]
To keep the number of issues in our inbox on a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: We look at the number of votes the issue has received and the number of duplicates issues filed.

Thanks for your understanding. Happy coding!
