### ISSUE TITLE
When VScode restart, the window which is fullscreen before should restore normal

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#159229]
https://user-images.githubusercontent.com/41773861/186770418-bd2f9d60-aba2-4d5d-9712-4a81facd1a91.mov

Expect:

<img width="1440" alt="Snipaste_2022-08-26_05-17-23" src="https://user-images.githubusercontent.com/41773861/186770661-a01bbc9d-0ea5-4a15-b3b4-bddb550f60e0.png">

Actual:

<img width="1440" alt="Snipaste_2022-08-26_05-17-04" src="https://user-images.githubusercontent.com/41773861/186770699-88d8f9fe-9e32-4dd4-acf9-f43b7d29dfeb.png">

```
Version: 1.71.0-insider (Universal)
Commit: 9529e11f6481ae53bba821b05e34549491b9415e
Date: 2022-08-25T13:02:01.718Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

**Comment by bpasero** [comment]
Yes, this was probably not a good change from me in https://github.com/microsoft/vscode/commit/a9ee44e80d47b01f34ccc3318e0386d61410afe5
