### ISSUE TITLE
In Output, ctrl+click can not jump to the file

### ISSUE THREAD

**Issue by sunhaoxi** [microsoft/vscode#159255]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Windows 10

Steps to Reproduce:

1. Project file structure like this:
![image](https://user-images.githubusercontent.com/87049519/186829081-fdd72d72-684e-44df-a267-27ff3722b5b1.png)

2. Create a task like this:
```
"tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo \"../folder1/test.c(123)\"",
            "options": {
                "cwd": "${workspaceRoot}/proj/"
            }
        }
    ]
```
3. Run the task and you can see the output. Press ctrl+click the file path. It should jump to the "test.c" file. But actually, I need to choose which file should be opened.
![image](https://user-images.githubusercontent.com/87049519/186829413-cfdc2519-b776-4623-9771-3f839718e47e.png)

I think VSCode should open the file according to the file path in the output. or report error if the file dosen't exist.

**Comment by sunhaoxi** [comment]
After testing, 1.68 worked. But 1.69 and 1.70 don't work anymore.

**Comment by simon8233** [comment]
I have same problem in 1.69

**Comment by sunhaoxi** [comment]
Hi, @Tyriar. Any progress? Do you have a plan to fix it? Which version can this issue be fixed? Some extensions need the latest VSCode, but can not jump by clicking the output error is very inconvenient.

**Comment by Tyriar** [comment]
I believe this is fixed in https://code.visualstudio.com/insiders/, let me know if not

**Comment by sunhaoxi** [comment]
This issue still exists in 1.72.2.
```
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19041
Sandboxed: No
```

**Comment by sunhaoxi** [comment]
It will jump to the file and line if I click the output in terminal. Like this:   
![image](https://user-images.githubusercontent.com/87049519/196839537-dde1680c-a8fe-41ee-a2d8-f9162e8bcbbf.png)
But it will ask me to choose the file if I click the output of tasks.

**Comment by sunhaoxi** [comment]
Hi, @Tyriar. any update?

**Comment by sunhaoxi** [comment]
Hi @Tyriar, It still can not jump by ctrl+click the output of tasks. Can you reproduce following my step?

**Comment by Tyriar** [comment]
It's happening because the task doesn't have shell integration's cwd coming through, as such it can't ensure it's folder is the starting cwd and falls back to search links. Maybe tasks should have their cwd fixed for link resolution, the only downside of this is if the task changes the cwd during execution in which case the link would be off. That seems like a minor edge case though.

**Comment by joyceerhl** [comment]
I can click on the file link to open it in the editor, but the shell output that I get in pwsh is different from the output in the original report which seems to be bash or similar--for pwsh the parentheses seem to be getting stripped and the `123` is on a newline. Is that expected? 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/30305945/214926186-02e48290-4c61-450b-a981-248a9a81f281.png">

**Comment by Tyriar** [comment]
@joyceerhl does this one work?

<img width="177" alt="image" src="https://user-images.githubusercontent.com/2193314/214927028-69a5825a-3e25-4b9b-8f04-a7d023a271b4.png">

Outputting onto a different line is just something related to the shell which won't impact link detection.

**Comment by joyceerhl** [comment]
@tyriar yeah that one works, just wanted to make sure that the newlines weren't a behavior change

<img width="522" alt="image" src="https://user-images.githubusercontent.com/30305945/214927868-9c84148f-8f69-4488-b16a-b97c8003ebdb.png">
