### ISSUE TITLE
Unhandled state isn't part of the checkbox undo stop

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#159237]
Testing https://github.com/microsoft/vscode/issues/158864

1. Have an unhandled change
2. Click a checkbox on either side
3. Hit undo
4. The action of checking is undone, but the merge is still marked as handled (it should revert to unhandled)

**Comment by hediet** [comment]
@alexdima is this feasible?
Maybe using the model version id and a separate map to attach data to it?

When manually marking a conflict as handled, should a single ctrl+z revert that too?
