### ISSUE TITLE
Anything i type in my terminal do not show

### ISSUE THREAD

**Issue by arkoaikins** [microsoft/vscode#159274]
ADD ISSUE DESCRIPTION HERE
I am able to type in my code space but when am to run the code at the terminal anything I type at the terminal do not show 

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by arkoaikins** [comment]
Yes, it is working now. Thank you
