### ISSUE TITLE
Failed to enable an extension when working in remote development

### ISSUE THREAD

**Issue by tianzerun** [microsoft/vscode#159263]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Darwin arm64 21.4.0

Steps to Reproduce:
1. Open VS Code on desktop.
2. Connect to any GitHub Codespace.
3. Install the gitlab.gitlab-workflow extension.
4. Disable this extension & reload.
5. Enable this extension.
6. An error message "Cannot change enablement of Git extension because of its extension kind" pops up.

I searched the error in the repository and realized it could be a bug when checking for the changeability of the builtin git extension's enablement state. The GitLab Workflow extension lists vscode.git as an [extension dependency](https://gitlab.com/gitlab-org/gitlab-vscode-extension/-/blob/main/package.json#L880), which triggers the check.
https://github.com/microsoft/vscode/blob/36351641a2051c81cc0134744e2983c111c27367/src/vs/workbench/services/extensionManagement/browser/extensionEnablementService.ts#L167
Somehow the git extension's enablement is considered not changeable. 

<img width="1440" alt="Screen Shot 2022-08-26 at 15 00 43" src="https://user-images.githubusercontent.com/23252886/186848818-d40cbc68-ba79-40a0-bc41-6a6f394e731b.png">

**Comment by sandy081** [comment]
Will investigate
