### ISSUE TITLE
Language auto-detection interferes with snippet language

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#159202]
Testing #145929

1. Add the snippet in https://github.com/microsoft/vscode/issues/145929#issuecomment-1192532575.
2. Create a new empty text file.
3. Add in the css-template JS snippet using F1 > Populate File From Snippet. The language changes to JS.
4. :bug: Auto-detection changes the language back to CSS.

**Comment by jrieken** [comment]
@TylerLeonhardt auto-detection shouldn't do that, how do I tell it to respect user-choice?
