### ISSUE TITLE
Python not working on terminal

### ISSUE THREAD

**Issue by pyadav1992** [microsoft/vscode#159214]
Type: <b>Bug</b>

Hello, 

I am not able to run python on Visual studio Code terminal:

When trying to run "python" command, the terminal is launching a pop up window with "How do you want to open this file?" message and asking the user to select an application. 

![PythonIssueOnTerminal](https://user-images.githubusercontent.com/45407020/186740396-cae32ac6-74ec-43e1-a7d5-d05d9b0d5b81.PNG)

I have already installed python on my laptop and updated the interpreter address in the visual studio code settings. 

I have tried using a command prompt terminal outside of the visual studio and the python work on it. The issue is in visual studio code. 

Need help.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.40
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by karthiknadig** [comment]
@pyadav1992 This mean that you don't have python installed or python is not available via the PATH environment variable.

**Comment by pyadav1992** [comment]
The PATH variable is updated. I was able to launch python on regular command prompt console outside the VSC. 

Anyway, I reinstalled the python and VCS on my laptop, made sure the PATH variable is updated. Now it is working! 

Thanks.
