### ISSUE TITLE
Create New Codespace fails if the current repo was cloned using SSH

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#159287]
Was trying to verify #158384

1. I installed the github remote repos, and the remote repos extension as I did not have those on desktop
2. I tried to find `Edit Sessions` but couldn't. However, with Edit sessions disabled there is a sign into edit sessions entry (first confusion)
3. I found the setting and enabled edit sessions and tried to create an edit session inside a codespace and was prompted with this
<img width="416" alt="image" src="https://user-images.githubusercontent.com/4544166/186895894-437c65e5-5698-40e5-bb6c-122a73ebf8ab.png"> git status reported no issues finding the repo name or owner. Nothing was really special about this repository (second confusion).
4. Figured it might need a reload because this is my first time enabling this settings. So I reload and am prompted with 
<img width="269" alt="image" src="https://user-images.githubusercontent.com/4544166/186896344-f30cc8e9-7964-4e9d-a1a4-0db3bf64633f.png"> which is extra bizarre because I was just told in step 3 that my edit session failed to create. This is a scary message but clicking yes seems to not do anything (third confusion).
5. So codespaces doesn't seem to work with edit sessions, so just for exploration I try insiders.vscode.dev it opens at least with the correct repo, but I'm shown this sign in prompt 
<img width="652" alt="image" src="https://user-images.githubusercontent.com/4544166/186896774-4333553b-3ad5-4ac6-af55-45e3583d1e2a.png"> not sure why it thinks I'm signed in with my Microsoft.com email as on desktop I signed in with GitHub and I've only ever signed into vscode.dev with GitHub to view GitHub repositories (fourth confusion).
6. I choose sign in with GitHub and 🥁 🥁.... my changes aren't there ☹️. Not really sure what to do at this point or if I missed a step in using this feature, I just enabled edit sessions made a local change without staging or committing it and tried to open it somewhere else. (fifth confusion).

Hope this issue helps in some way let me know if I can collect any further diagnostics or if I'm missing a big step in this feature as this is my first time using it

**Comment by joyceerhl** [comment]
In step 3, are you inside a Codespaces window or inside a GitHub Repositories window? (Either way should work) Which repo is it and are there any Codespaces or Edit Sessions logs from the output channels?

4. is a bug--we should never attempt to resume an edit session on the machine it was created on, and also should not have a dialog if the changes are identical to the ones we already have locally
 
5. also looks like a bug, have you ever used edit sessions before with Microsoft auth?

> it opens at least with the correct repo
Not sure I follow this, can you elaborate?

> I just enabled edit sessions made a local change without staging or committing it and tried to open it somewhere else. (fifth confusion).

That's not the scenario for edit sessions, the steps for https://github.com/microsoft/vscode/issues/158384 are (with more details)
1. start in `insiders.vscode.dev/github/<some>/<repo>`
2. make some uncommitted change
3. execute the Continue Working On command
4. sign into edit sessions when prompted
5. pick Create New Codespace
6. verify that the created codespace preserves your branch checkout and that the uncommitted changes that you had in insiders.vscode.dev were transferred, without you needing to sign in on the Codespaces end

**Comment by lramos15** [comment]
This was with the hex editor repo, sorry I didn't collect any logs as I was trying to document the experience. I can try again and collect logs if not.

In step 3 I was attempting to go from desktop to codespaces

For number 5, this was my first time enabling and signing into edit sessions and I never signed in to edit sesisons.

For opening the correct repo, what I mean is edit sessions onto vscode.dev opened the repository (unlike codespaces which failed) but did not apply any changes.

For the scenario is that not what I did? I have a saved change in a repository that isn't committed or staged locally but it is tracked as a changed file by my local git instance. If this isn't the correct scenario we should probably prompt that edit sessions isn't going to work as the scenario seems to try and work but fails

**Comment by joyceerhl** [comment]
OK, it sounds like you tried 
1. desktop -> codespaces (was it RemoteHub -> codespaces or a local clone of your repo?)
2. desktop  -> vscode.dev


> tried to open it somewhere else 

Just to clarify, did this happen through the Continue Working On command or something else?


If you have time to jump on a call or can share the Edit Sessions output logs from those transitions, that would be awesome.

**Comment by lramos15** [comment]
> OK, it sounds like you tried
> 
> 1. desktop -> codespaces (was it RemoteHub -> codespaces or a local clone of your repo?)
> 2. desktop  -> vscode.dev
> 
> > tried to open it somewhere else
> 
> Just to clarify, did this happen through the Continue Working On command or something else?
> 
> If you have time to jump on a call or can share the Edit Sessions output logs from those transitions, that would be awesome.

Local clone, used `Edit Sessions: Continue Edit Session...` 

I can jump on a call if you like, I feel like I must be using the feature incorrectly (if I am though it probably should be prevented :) )

**Comment by joyceerhl** [comment]
Will be fixed with v1.10.5 of the GitHub Codespaces extension.
