### ISSUE TITLE
Sticky scroll seems to render on top of minimap

### ISSUE THREAD

**Issue by Tenrys** [microsoft/vscode#159281]
- VS Code Version: 1.70.2
- OS Version: Manjaro Linux 21.3.7 "Ruah"

![Peek 26-08-2022 12-59](https://user-images.githubusercontent.com/3979239/186889556-37605cbb-d45f-4a85-83ff-d3865beaa8e8.gif)

**Comment by aiday-mar** [comment]
Hi thank you for filing this bug. It should be solved in the Insiders version of VS Code which you can download in order to verify this : https://code.visualstudio.com/insiders/. You will see the new corrected behavior in the next stable release which happens once a month.
