### ISSUE TITLE
Allow to override WM_CLASS by command line argument or env variable

### ISSUE THREAD

**Issue by ronnypaterson-developer** [microsoft/vscode#159294]
The implementation reported in issue [145455](https://github.com/microsoft/vscode/issues/145455) by the user @thejavascriptman is still necessary, because the lack of it makes the user experience bad that needs two or more different VSCode instances in the same development environment.

I transcribe below the statement of that demand, because the need remains current:

> Please allow to override the window class name (WM_CLASS) of the VS Code window. Current behaviour is to use a single window class (`code` for the official build or `code-oss` for the open source build), this can be seen with `xprop` on Linux.
> 
> If the user passes the `--user-data-dir` and `--extensions-dir` arguments to create/use a new "profile", all VS Code windows will be attached, meaning that the last VS Code instance will be launched when using .desktop files (because both "profiles" would share the same window class).
> 
> By having a custom window class it would be possible to detach the VS Code windows as well as to specify a custom icon for each VS Code "profile" inside a `.desktop` file.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/145455
