### ISSUE TITLE
Markdown rendering syntax highlighting of sql keyword if not working

### ISSUE THREAD

**Issue by MartinRyx** [microsoft/vscode#159297]
Type: <b>Bug</b>

Markdown rendering with syntax highlighting does not colour reserved word `if` correctly.

Steps to Reproduce:

1. Create a new markdown file
1. Paste the following code
   ````
   ```sql
   if 1 = 2 begin
      select 'Hello'
   end
   ```
     ````
1. Press `Ctrl`+`K` `V` to view the result

The `if` keyword stays white while for instance `begin` and `end` turns blue as expected
![image](https://user-images.githubusercontent.com/9428639/186906287-8a79541d-5cea-4a60-bbe6-f84a19bd0305.png)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (20.17GB free)|
|Process Argv|--crash-reporter-id b118d2ab-d653-4c32-a76c-dece68264a0a|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by mjbvz** [comment]
This highlighting in the markdown preview comes from highlight.js. If you are still seeing this, file an upstream issue against that project
