### ISSUE TITLE
Sticky scroll doesn't work with C++ 17 nested namespaces

### ISSUE THREAD

**Issue by stefanhaller** [microsoft/vscode#159271]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0-insider, Commit: 9529e11f6481
- OS Version: macOS 12.5.1 (21G83)

Steps to Reproduce:

Sticky scroll does not work correctly for a file like this:

```c++
namespace A::B {

void func() {
  //
  //
  //
  //
}

} // namespace A::B
```

Scrolling into the body of func() shows a sticky scroll area containing only `namespace A::B {`. I expect two lines instead, like this:
```
namespace A::B {
void func() {
```

However, it _does_ work for a C++ file like this:

```c++
namespace A {
namespace B {

void func() {
  //
  //
  //
  //
}

} // namespace B
} // namespace A
```

In this case, scrolling into the body of func() shows a sticky scroll area containing three lines, as expected:
```
namespace A {
namespace B {
void func() {
```

**Comment by aiday-mar** [comment]
Thank you for the bug. The issue was caused by a small bug in the implementation. You will be able to see the new behavior in the stable release. 

![sticky-scroll-cpp](https://user-images.githubusercontent.com/61460952/186943532-6c5a2bd6-8010-44b2-9c91-30237c4cbb36.gif)

**Comment by stefanhaller** [comment]
@aiday-mar OK, so it is in the current Insiders now, but it didn't make it into 1.71.0, which is very unfortunate. Is there a chance to get it into a point update soon, so that we don't have to wait another month for the fix?
