### ISSUE TITLE
When updating Visual Studio Code is asking for a password to Add Helper

### ISSUE THREAD

**Issue by JohnGinger** [Microsoft/vscode#15924]
- VSCode Version: 1.7.1
- OS Version: macOS Sierra 10.12.2

Steps to Reproduce:

1. Click check for updates
2. The following dialog pops up, if you enter your password it says an update is available, but when clicking to restart it doesn't do anything
3. This doesn't happen with a fresh install

<img width="1025" alt="screen shot 2016-11-22 at 22 05 13" src="https://cloud.githubusercontent.com/assets/2624571/20544092/45532558-b100-11e6-9c1e-fabb1aafa1b1.png">

**Comment by JohnGinger** [comment]
On more investigation I'm getting the following error in dev tools when I don't give the password.

Failed to clear temp storage: It was determined that certain files are unsafe for access within a Web application, or that too many calls are being made on file resources. SecurityError

**Comment by bpasero** [comment]
This dialog shows up when you had VS Code installed in one location and then you downloaded it again to another location and the auto update kicks in.

**Comment by marcovandewater** [comment]
Hi, I did not move VS Code to a different location but I am getting the same message when auto update kicks in. Furthermore it fails to install the update and I need to install new versions of VS Code manually. It seems that this happens since I am on Sierra public beta.

**Comment by bpasero** [comment]
@joaomoreno any more clues where this could come from? I only saw it once on Sandeepds machine when he downloaded VS Code to a new location, started it and it was auto updated.

**Comment by joaomoreno** [comment]
This is #7426. It happens to me when Code is in the Downloads folder. @JohnGinger where is your application bundle located?

**Comment by JohnGinger** [comment]
It looks like it is the same issue, Code is in the Downloads folder.

**Comment by joaomoreno** [comment]
If you put it in the Desktop, for example, does it work?

**Comment by JohnGinger** [comment]
It doesn't seem to update, but it doesn't prompt for a password before saying an update is avaliable.

**Comment by ramkinavy** [comment]
It keeps asking for password again and again

**Comment by xcity** [comment]
it's linking to com.apple.quarantine feature in sierra, here is the WA. 
1. remove vscode completely using appdelete or others. you cannot just simply remove vscode inside from app. 
2. change com.apple.quarantine attribute 
xattr -dr com.apple.quarantine "/Applications/Visual Studio Code - Insiders.app"

after that, run vscode won't get a prompt of having a password to install helper, you will receive a new error message indicate no permission to create temp files. Off cause, the update still fail.
3. change permission. 
sudo chown myuser:staff /Users/myuser/Library/Caches/com.microsoft.VSCode.ShipIt/*

change myuser to your user id. 
4. re-try update.

**Comment by joaomoreno** [comment]
@xcity It's better if you link people to my [post](https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150) in #7426

**Comment by yarandoo** [comment]
I have the same issue. Is there a less manual solution to this?
