### ISSUE TITLE
Add open in browser

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#15928]
I would be nice to able to open in the localhost and we could specify the localhost root address:  such as c:\xampp\htdocs etc..... 

All my other code editors have this option.

Right click the tab - open in browser (internet explorer, Firefox, chrome, opera).   Or have a menu option. Thanks.

**Comment by jrieken** [comment]
This should be done as extension - all the API for this are in place

**Comment by mjbvz** [comment]
Closing as extension-canidate. There are already a number of extensions in the marketplace that implement this: https://marketplace.visualstudio.com/search?term=open%20in%20browser&target=VSCode&category=All%20categories&sortBy=Relevance
