### ISSUE TITLE
Duplicate entries in notebook cell status bar

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#159333]
I'm not sure how I got to this state, but I see "Open 10 results" and "Open 8 results" next to each other in `endgame.github-issues`.

![GitHub issues notebook showing "Open 10 results" and "Open 8 results" links next to each other](https://user-images.githubusercontent.com/7199958/186965625-a4a50819-d6b0-40c6-b607-87a121e543cd.png)

**Comment by rebornix** [comment]
It looks like they are not disposed properly.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/159114
