### ISSUE TITLE
Hint: Startup time improvement

### ISSUE THREAD

**Issue by mathiask88** [Microsoft/vscode#1593]
Hey, 
node.js 0.10 and 0.12 were always compiled without v8 snapshotting due to a security reason that had been fixed and since io.js 2.x it should be enabled by default,  but due to a config mismatch it was not...until now ;) https://github.com/nodejs/node/pull/3962

Just want to give you this hint so that you can have a look at the effect on startup time in vscode if this patch arrives here (or if you apply that change and  build electron on your own)

**Comment by bpasero** [comment]
@mathiask88 thanks, the node.js version we use depends on whatever Electron picks up, so I think eventually we will benefit from this change.
