### ISSUE TITLE
Protocol handlers should run before a resolver

### ISSUE THREAD

**Issue by jkeech** [microsoft/vscode#159344]
Currently, VS Code respects the `window.restoreWindows` setting when launching via a `vscode://` url. That can be problematic for remote scenarios though, such as Codespaces, since the default behavior of "open the last opened folder" needs to finish the resolver first before the protocol handler kicks in. This breaks the following scenario for Codespaces:

1) Create and connect to a codespace in VS Code
2) Quit VS Code
3) Delete the codespace that you were previously connected to
4) Open a new codespace in VS Code via the protocol handler, such as `... -> Open in Visual Studio Code` from `github.com/codespaces`
![image](https://user-images.githubusercontent.com/746020/186984459-7f2f4e87-d4cf-409f-a533-629094561234.png)
5) 🐛 VS Code spawns a new window and tries to reconnect to the deleted codespace, not the requested codespace, and the resolver fails (by design) with a message saying the codespace has been deleted. The protocol handler for the new codespace connection never runs.

https://user-images.githubusercontent.com/746020/186985654-878190be-96ac-465e-aad2-ffc5d0c18a8a.mov

Expected: The protocol handler pop up appears when VS Code first launches
![image](https://user-images.githubusercontent.com/746020/186984549-1cbbea36-2a28-4b61-bf18-aa2201bfd4be.png)

A similar scenario will happen where the protocol handler won't run if a codespace is stopped in an open VS Code window (with the modal dialog asking to restart before the resolver will succeed). The protocol handler doesn't run in this case either.

https://user-images.githubusercontent.com/746020/186985049-a1f21ab0-9fca-4400-bb9c-c35d603df0f7.mov

I believe both of these scenarios are happening because the act of opening the previous folder through the resolver must complete before the protocol handler kicks in. If users manually set `"window.restoreWindows": "none"`, the behavior works as expected for the first scenario since VS Code launches a new empty window and then presents the protocol handler prompt.

Could the behavior for protocol handlers change to run before a resolver finishes? Alternatively, can they cause VS Code to launch a new window instead of using the last-opened-folder window? I don't think this is something that can currently be fixed within the Codespaces extension directly. Thanks!

**Comment by joaomoreno** [comment]
> Could the behavior for protocol handlers change to run before a resolver finishes?

Unsure how feasible this would be, but we can try.

> Alternatively, can they cause VS Code to launch a new window instead of using the last-opened-folder window?

This can already be done on a per URL basis using `windowId=_blank` on the URI. But this would _always_ force a new window.

---

Thoughts @bpasero @sandy081 ?

**Comment by bpasero** [comment]
Tough, I think the issue is that there is simply already a modal dialog opened and we queue modal dialogs up iirc to only show one. I think this would happen equally when you have another modal dialog visible (such as the one that comes up when you close a dirty file).

**Comment by jkeech** [comment]
> I think the issue is that there is simply already a modal dialog opened and we queue modal dialogs up iirc to only show one.

For the first scenario (the deleted case) there is no modal showing up, but the protocol handler still doesn't get invoked.

>This can already be done on a per URL basis using windowId=_blank on the URI. But this would always force a new window.

Nice, I didn't know about that. We can try that. I think for some of the urls we generate, it might make sense to append that query param which would definitely help even if it doesn't cover all of the ways our protocol handler can be invoked (such as from clients we don't control).

**Comment by joaomoreno** [comment]
Yeah maybe that's the best way forward. @bpasero, if a workspace is opened with `windowId=_blank`, but the previous session would already have it open, then the same window would be reused, right?

**Comment by bpasero** [comment]
The rule for opening windows is always: you can only open a workspace in a single window, never in multiple windows. So when deciding to open a window - irrespective of whether this is a first startup or a subsequent startup - we always deduplicate.

**Comment by joaomoreno** [comment]
✅ And independent of `windowId=_blank`.

@jkeech Would this be sufficient?

**Comment by jkeech** [comment]
> ✅ And independent of `windowId=_blank`.
> 
> @jkeech Would this be sufficient?

Yep, I think this will be good enough for our use case. Just tested and it seems to work well. 👍 Thanks!
