### ISSUE TITLE
`"serverReadyAction"` does not work properly with programs printing ANSI colors

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#159391]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: 12.15.1

Steps to Reproduce:

1. Try to define a `"serverReadyAction"` for Vite. Vite prints colors, which unlike problems matchers, are not stripped while matching the output. This makes it difficult to define a proper pattern for it.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by segevfiner** [comment]
[Recording 2022-08-30 at 00.36.14.gif.zip](https://github.com/microsoft/vscode/files/9448074/Recording.2022-08-30.at.00.36.14.gif.zip)
Sorry for the zip. The gif came out 1MiB bigger than GitHub will like to allow to upload. 🤷‍♂️

**Comment by meganrogge** [comment]
Thanks - based on the gif, the problem is that `env` is not taking effect - in your case, the `NO_COLOR` property

**Comment by segevfiner** [comment]
> Thanks - based on the gif, the problem is that env is not taking effect - in your case, the NO_COLOR property

It is taking effect. I'm purposefully disabling it by commenting it at first. At the start I run without it to show that `serverReadyAction` is not working with colors enabled. I then uncomment it which disables colors and show that without colors `serverReadyAction` does work.
