### ISSUE TITLE
(feature request) Smart Horizontal Scrolling

### ISSUE THREAD

**Issue by GitClickOk** [Microsoft/vscode#15938]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

My suggestion is when (vertical) scrolling a long file with a deep indentation, the relevant text will be "hidden" because with the indentation, the text will more and more to right position of the screen. Then we need "stop" the vertical scrolling, scroll a little to right to see the full text (or most of), and we can start working on that. Then if we want vertical scroll to top or bottom, the text will indent (sometimes to right, sometime to left...), you will need, again, stop the vertical scrolling, adjust the viewport scrolling to right or left, and then go on with vertical scrolling.

Look a little example:

                                                                                  _`VSCode must Smart Scroll in order to you see this text. Its not hard detect that the left side of the screen is full of tabs or whitespaces, and the actual code is here, on the right side. `_

My idea is simple, you does vertical scrolling and the VSCode can "detect" that you are seeing... nothing, the text was indented far right, so VSCode will "smart scroll" to right or left to show the actual text in that point.

**Comment by hashhar** [comment]
Great idea for an extension.

**Comment by recursionbane** [comment]
Can anyone suggest an extension for this?
If not, could we bring this forward from the back-burner?

For complex HTML + AngularJS files with automatic Beautification, this is a significant productivity killer.
An option to always scroll horizontally to end of auto-indentation would be extremely helpful upon vertical scroll (using keyboard, at least).

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.
