### ISSUE TITLE
clipboard shortcuts do not work in OSX system file dialog path modal

### ISSUE THREAD

**Issue by LunarLanding** [microsoft/vscode#159395]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: OSX 12.5.1

Steps to Reproduce:

1. Copy path into clipboard 
2. Start vscode
3. Click "Open ...". The native osx file picker dialog opens.
4. Press cmd-shift-G. A new modal shows, with a path field with a preview below.
5. Press cmd-V. A beep is emitted and nothing happens.

This bug arguably did not exist in 2017: https://github.com/microsoft/vscode/issues/39499
The screenshot of the modal also looks different from the current one.

At least one other application ( LibreOffice ) has the same bug  : https://bugs.documentfoundation.org/show_bug.cgi?id=126638

The bug is alleviated by either right clicking to access the paste button in the context menu, or by toggling on the "Files>Simple Dialog". But these are workarounds.

This bug also applies to the "add new folder to workspace" action, and presumably to all usages of the OSX system file dialog.

**Comment by deepak1556** [comment]
Unable to repro the issue in MacOS 14 with latest stable
