### ISSUE TITLE
ability to rename foo.ts to foo/index.ts

### ISSUE THREAD

**Issue by trusktr** [microsoft/vscode#159350]
I sometimes encounter a case where a file gets large, and I want to refactor it into multiple files, but want to keep the import the same in all consumers. For example, a `utils.ts` file can become a `utils/` folder with an `index.ts` (`utils/index.ts`) and I can then move things out of the `utils/index.ts` file into the `utils` folder, all without affecting import statements in other places (typically when using build tools that are designed to look for index files, although I know that technically the file name change is incompatible with native ES Modules, so this wouldn't be useful in all cases, only cases with certain common setups).

The alternative is to rename the file (the refactor affects all consumers), make the new folder, then move the file into the new folder (the refactor affects all consumers again). This process is has been known to be buggy (well, a lot better lately), but also this process is more steps (the more steps, the more chance for failure).

**Comment by mjbvz** [comment]
This feature is powered by the TypeScript project. Please [file a feature request upstream](https://github.com/microsoft/TypeScript/issues/new?template=Feature_request.md)
