### ISSUE TITLE
The border color of h1 (#) is not reflected when specifying a Markdown style sheet

### ISSUE THREAD

**Issue by Star-Delta** [microsoft/vscode#159353]
Type: <b>Bug</b>

When I specify my own CSS file and preview Markdown, the border color of h1 is not reflected.
This problem can be reproduced by following the procedure below.
1. add the following CSS file to `Markdown: Styles`
   ```css
   h1 {
       border: 10px solid red;
   }
   ```
1. preview the following Markdown file
   ```markdown
   Headline_1
   ==
   ```

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz (4 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (16.68GB free)|
|Process Argv|--crash-reporter-id 6ca6ac69-34a6-4a09-99ab-394cdacb706f|
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ja|MS-|1.70.8170911

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by Star-Delta** [comment]
After checking the generated HTML in preview, the following CSS may have been loaded.
The following CSS is loaded even when the Markdown file is converted based on the CSS specified in ``Markdown: Styles``, so it is assumed that the styles are overridden.
```html
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/Microsoft/vscode/extensions/markdown-language-features/media/markdown.css">
```
Is it possible to set the above CSS file not to be loaded?

**Comment by mjbvz** [comment]
That file provides a baseline stying that your stylesheets can then augment

In your example, you can just add a more specific css rule for light/dark:

```
.vscode-dark h1 {
    border: 10px solid pink;
} 
```

or if you want this to apply to all color themes:

```
.markdown-body h1 {
    border: 10px solid pink;
} 
```

**Comment by Star-Delta** [comment]
I understand how to write CSS for preview, thank you.
