### ISSUE TITLE
vscode.TestMessage support for stack traces

### ISSUE THREAD

**Issue by ashgti** [microsoft/vscode#159339]
When recording test issues with [vscode.TestRun](https://code.visualstudio.com/api/references/vscode-api#TestRun) using the `.errored` or `.failed` the associated [vscode.TestMessage](https://code.visualstudio.com/api/references/vscode-api#TestMessage) can only 1 location associated with the message, for example the location of an assertion failure message. 

It would be nice if we could also associate a stack trace with the message, maybe with multiple messages and locations. 

For example, using the Test runner in node (v18+, or v16.17+):

```
// example_test.mjs

import assert from 'node:assert';
import test from 'node:test';

test('synchronous passing test', (t) => {
  // This test passes because it does not throw an exception.
  assert.strictEqual(1, 1);
});

test('synchronous failing test', (t) => {
  // This test fails because it throws an exception.
  function nested() {
    assert.strictEqual(1, 2);
  }

  nested();
});
```

And running the test like:

```
$ node example_test.mjs
(node:93582) ExperimentalWarning: The test runner is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
TAP version 13
# Subtest: synchronous passing test
ok 1 - synchronous passing test
  ---
  duration_ms: 0.000721584
  ...
# Subtest: synchronous failing test
not ok 2 - synchronous failing test
  ---
  duration_ms: 0.001678833
  failureType: 'testCodeFailure'
  error: |-
    Expected values to be strictly equal:
    
    1 !== 2
    
  code: 'ERR_ASSERTION'
  stack: |-
    nested (file:///private/tmp/example_test.mjs:14:12)
    TestContext.<anonymous> (file:///private/tmp/example_test.mjs:17:3)
    Test.runInAsyncScope (node:async_hooks:203:9)
    Test.run (node:internal/test_runner/test:483:25)
    Test.processPendingSubtests (node:internal/test_runner/test:249:27)
    Test.postRun (node:internal/test_runner/test:553:19)
    Test.run (node:internal/test_runner/test:511:10)
  ...
1..2
# tests 2
# pass 1
# fail 1
# cancelled 0
# skipped 0
# todo 0
# duration_ms 0.036429416
```

The stack trace has additional information, like where the call came from. Currently, I don't think we have any way of associating the stack trace with the lines of code (e.g. the second frame of the track points back to `example_test.mjs:17:3`) only location of the failure (in this example `example_test.mjs:14:12`).

**Comment by ashgti** [comment]
One example of something similar is the [vscode.Diagnostic](https://code.visualstudio.com/api/references/vscode-api#Diagnostic) which can contain [vscode.DiagnosticRelatedInformation](https://code.visualstudio.com/api/references/vscode-api#DiagnosticRelatedInformation) to include a stack trace or associated line of code.

**Comment by connor4312** [comment]
Duplicated by https://github.com/microsoft/vscode/issues/214488. Shipped that a few months ago, just lost this issue.
