### ISSUE TITLE
VS Code freeze on startup.

### ISSUE THREAD

**Issue by Billreal** [microsoft/vscode#159354]
Type: <b>Performance Issue</b>

Step to reproduce:
1. Reinstall Admin VS Code on official style.
2. Start VS Code with "--disable-extensions" parameter.

Issue: VS Code use RAM but not any CPU, after started for a while it freezes and make other programs and Windows frozen for around 1-5 minutes. During that time no action can be made, including moving cursor and Ctrl - Alt - Delete combination. After that VS Code make Windows alert that it is not responding but pressing on wait for respond make VS Code run normal. On Startup Performance tab some number are skyrocketed to suspiciously high.
Reloading VS Code while it is running does not cause this issue.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 6.1.7601
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590S CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|3.92GB (0.72GB free)|
|Process Argv|--disable-extensions --crash-reporter-id cb42ce72-4188-4c3a-ac29-f29df54c7aa9|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    81	 11420	code main
    0	    74	  3884	   extensionHost
    0	    31	 13192	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\server\dist\node\main" --node-ipc --clientProcessId=3884
    0	    83	 10680	   shared-process
    0	    38	 11836	     fileWatcher
    0	    37	 12268	     ptyHost
    0	     4	 11364	       winpty-process
    0	    56	 12812	         C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    3	    44	 11172	   gpu-process
    0	    13	 11764	   crashpad-handler
    0	    23	 12140	   utility-network-service
    0	    48	 12484	   issue-reporter
    1	   249	 12668	   window (Startup Performance - Untitled (Workspace) - Visual Studio Code [Administrator])
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (Startup Performance - Untitled (Workspace) - Visual Studio Code [Administrator])
|    Folder (Cplusplus): 1020 files
|      File types: cpp(152) exe(147) o(92) cbp(62) layout(62) depend(52)
|                  out(35) inp(34) h(15) exe (11)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg(2)
|    Folder (Javascript): 3 files
|      File types: js(1) jpg(1) html(1)
|      Conf files:
|    Folder (Latex): 63 files
|      File types: pdf(9) aux(7) fdb_latexmk(7) fls(7) log(7) gz(7) tex(7)
|                  txt(2) bbl(1) bib(1)
|      Conf files:
|    Folder (Python): 8086 files
|      File types: py(2528) pyc(2294) pyi(1791) txt(75) pyd(65) exe(37)
|                  dll(17) h(16) html(15) typed(14)
|      Conf files: launch.json(1)
|      Launch Configs: python;
```

</details>
Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by connor4312** [comment]
Please collect performance information using https://github.com/microsoft/vscode/wiki/Performance-Issues

**Comment by Billreal** [comment]
After further searching, my problem might be caused by the GPU, not the app itself.
