### ISSUE TITLE
Continue Working On > Clone Locally when VS Code is not already installed

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#159328]
In the following dialog that appears:
<img width="696" alt="image" src="https://user-images.githubusercontent.com/30305945/186952643-8c1ada36-be5f-4617-bf65-d23c0a7ddb8d.png">

1. When in insiders.vscode.dev and opening a `vscode-insiders://` protocol url, the 'Install VS Code Insiders' button should route to a new link for installing insiders specifically rather than just https://aka.ms/vscode-install
2. Clicking Install VS Code Insiders should not dismiss the dialog, so that the user can return and try again 

cc @digitarald

**Comment by meganrogge** [comment]
not sure how this modal was arrived at, so I clicked the remote indicator and I only see an option to download VS Code - not insiders. 

![Screen Shot 2022-09-29 at 7 43 20 AM](https://user-images.githubusercontent.com/29464607/193062727-7c4fc6a0-d0b3-4a22-a456-f95713f7271c.png)

**Comment by meganrogge** [comment]
I then did the `Continue working on...` flow and saw this dialogue despite having already installed VS code Insider's, which opened.

![Screen Shot 2022-09-29 at 7 46 08 AM](https://user-images.githubusercontent.com/29464607/193063468-7faf5bb9-906b-4742-bb62-29f80f657fea.png)
