### ISSUE TITLE
multiple background colors

### ISSUE THREAD

**Issue by mjkkirschner** [Microsoft/vscode#15934]
- VSCode Version: 1.7.2
- OS Version: mac os 10.12.1
![screen shot 2016-11-22 at 9 21 48 pm](https://cloud.githubusercontent.com/assets/508936/20549462/5d784416-b0fa-11e6-9a35-9ee9ba3a7f43.png)

The bounds of the editor view that contain text are a darker background color than the bounds that do not. Is this by design or am I seeing things?

Steps to Reproduce: 

1.  open any file with some text present or create a new file.
2. use a high resolution screen or low zoom level to view the file.
3. use any included theme - seems to reproduce in all, but harder to see in light themes.

**Comment by wallverb** [comment]
https://github.com/Microsoft/vscode/issues/15126#issuecomment-259123486

**Comment by mjkkirschner** [comment]
@wallverb - thanks, didn't catch all the others :(
