### ISSUE TITLE
The Issue Reporter window doesn't get the focus when you select VSCode in the task bar

### ISSUE THREAD

**Issue by adriancuadrado** [microsoft/vscode#159371]
Type: <b>Bug</b>

1. Open VSCode and maximize the window.
2. Help --> Report Issue
3. Switch to another window
4. Switch back to the VSCode window

The Issue Reporter window that appears when you click on "Report Issue" dissappears. This is because it is behind the VSCode window. You can bring it again by resizing the VSCode window to make it smaller and moving the VSCode window to the side to see the Issue Reporter window that is in the back. Another option is to click again on Help --> Report Issue. I am reporting this as a bug because it's annoying and I expect the window to either be selectable as a separate window in the task bar as if it were another instance of VSCode, or have it showing in front of VSCode when I switch back to the VSCode window.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.43GB (2.43GB free)|
|Process Argv|--crash-reporter-id 78bf48ec-3ac2-4ab2-9796-20d8802d00af|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/130497

and should be fixed in the next release happening this week :)
