### ISSUE TITLE
Sticky scroll doesn't work with AL 

### ISSUE THREAD

**Issue by Ji-Peter** [microsoft/vscode#159335]
Does this issue occur when all extensions are disabled?: **Yes**

Version: 1.71.0-insider (system setup)
Commit: 35b971c92d210face8c446a1c6f1e470ad2bcb54
Date: 2022-08-26T05:19:46.020Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

## Steps to Reproduce:

Sticky scroll does not work correctly for a Microsoft AL file like this:
```al
pageextension 1 PrefixTestPage
{
    layout
    {
        field(No; Rec.No)
        {
            ApplicationArea = All;
            trigger OnLookup(var TextMsg: Text):Boolean
            var
                CU: Codeunit PrefixCodeunit;
            begin
                //
                // Scroll to here
                //
            end;
        }
    }
}
```
I expect 4 lines:
```al
pageextension 1 PrefixTestPage
layout
Field
trigger OnLookup(var TextMsg: Text): Boolean
```

But I'm only getting 1:
```al
layout
```
![image](https://user-images.githubusercontent.com/103147983/186966508-b0a5bea9-6350-4bbe-bac6-aa3ff70a6e17.png)

**Comment by aiday-mar** [comment]
Hi thanks for the feedback. I assume you are using the Microsoft AL extension? I opened an issue with them (https://github.com/microsoft/AL/issues/7146) where you can track the progress on this issue.

**Comment by Ji-Peter** [comment]
> 

Thanks @aiday-mar

**Comment by jrieken** [comment]
closing as extension-issue
