### ISSUE TITLE
VS Code on Ubuntu 

### ISSUE THREAD

**Issue by nitowa** [microsoft/vscode#159322]
Does this issue occur when all extensions are disabled?: Yes, although the colors in the affected regions seem to change depending on extensions

- VS Code Version:
Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:25.715Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-46-generic

- OS Version: Ubuntu 22.04.1 LTS

OS/Environment: Running on VMWare Ubuntu LTS 22.04 image from osboxes.org (no other graphical issues)
VS Code installed as outlined in https://code.visualstudio.com/docs/setup/linux via apt/apt-get

Steps to Reproduce:

1. Open VS Code
2. Select lines in file by click-dragging or shift+arrow-up/down, highlighting completely breaks

1. Open command selector (Ctrl-Shift-P)
2. Arrow up/down, colors go haywire

The issue can be temporarily fixed by tabbing to another file and back. It will occur again when triggered.

Video: 
https://streamable.com/w9dev9

**Comment by Tyriar** [comment]
Looks like a GPU-related issue

**Comment by deepak1556** [comment]
Please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
