### ISSUE TITLE
Add shortcut for file right click context menu.

### ISSUE THREAD

**Issue by lijunle** [Microsoft/vscode#15939]
- VSCode Version: 1.7.2
- OS Version: Windows Server 2008/2012

Steps to Reproduce:

No shortcut (underline) for flie right click context menu. 

![image](https://cloud.githubusercontent.com/assets/1296500/20553312/9922b0a2-b18e-11e6-9d15-6ac3d77db3b5.png)

Such underline shortcut is very useful to fast open the file with VSCode with keyboard.

**Comment by jschraub** [comment]
Are there any recommendations/specifications as to what the shortcut should be for this?

**Comment by con-ssc** [comment]
`
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\Visual Studio Code]
@="Open with &Visual Studio Code"

[HKEY_CLASSES_ROOT\*\shell\Visual Studio Code\command]
@="C:\\Program Files (x86)\\Microsoft VS Code\\Code.exe" \"%1\"
`
