### ISSUE TITLE
Using the vscode interface on ubuntu22.04 to display an exception

### ISSUE THREAD

**Issue by huenrong** [microsoft/vscode#159352]
Type: <b>Bug</b>

1. open vscode
2. Some plugin icons in the activity bar are not visible
3. File icon theme not showing

Image
![image](https://user-images.githubusercontent.com/47348530/187012279-42509552-a6a0-4c1b-a918-5d1f2242a400.png)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:25.715Z)
OS version: Linux x64 5.15.0-46-generic
Modes:

**Comment by weinand** [comment]
@huenrong problem should be fixed in more recent version of VS Code
