### ISSUE TITLE
Enable state of extensions not preserved accross codespaces

### ISSUE THREAD

**Issue by tobiasdiez** [microsoft/vscode#159337]
Type: <b>Bug</b>

1. Create a new Github Codespace.
2. Enable a globally disabled extension for this workspace. (Or disable a globally enabled one)
3. Create new codespace for the same repository.

Expected: the extension is also enabled in the new codespace.
Actual: the extension is not enabled

Summary: Codespaces for the same repo should be treated as the same workspace when it comes to setting sync

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22622
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz (4 x 1512)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.91GB (0.53GB free)|
|Process Argv|--crash-reporter-id cde5d1e5-8818-4bd5-96ad-eae74f3d8ab1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by sandy081** [comment]
Settings Sync is not enabled by default in Codespaces. So any new changes are not synced across codepsaces unless you enable syncing. Please reach out to codespaces team who controls this behaviour.

**Comment by tobiasdiez** [comment]
@sandy081 Thanks for your reaction! 
Sorry, but I forget to say that the issue occurs with settings sync enabled. I've updated the description above. Could this issue thus please be reopened, or could you point me to the correct repo. Thanks!

**Comment by sandy081** [comment]
But you have to enable settings sync after creating the codespace,  I wonder where you are enabling the settings sync.

**Comment by tobiasdiez** [comment]
I've activated the settings sync as described eg here https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#settings-sync. This was an one-time thing and since then it works well, and most settings are indeed successfully synced. I'm not sure if the enable state of the extensions is not synced correctly, or if the synced data is just not used correctly. If you let me know where to look for the synced data, I can investigate.

**Comment by sandy081** [comment]
Which action are you using to enable/disable the extension? Can you please provide me the screenshot?

**Comment by sandy081** [comment]
This needs support of syncing workspace state - https://github.com/microsoft/vscode/issues/113996
or profiles - https://github.com/microsoft/vscode/issues/116740

**Comment by tobiasdiez** [comment]
Makes sense that these issues are related, but it appears to me that they are not a full replacement/duplicate. Can you please reopen this issue here?

**Comment by sandy081** [comment]
I do not think having this issue opened is necesry because supporting other two issues will suffice this.
