### ISSUE TITLE
Terminal title not set by xterm control sequence on Windows unless it is a path

### ISSUE THREAD

**Issue by amurzeau** [microsoft/vscode#159420]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.70.2 (user setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 6.3.9600
- OS Version: Windows 8.1

Steps to Reproduce:

1. Open a terminal
2. Run this command with the xterm set title control sequence: `printf '\x1b]2;foo\a` which should set `${sequence}` to `foo`

The terminal tab name won't change even if `terminal.integrated.tabs.description` and/or `terminal.integrated.tabs.title` contains `${sequence}`.

I've found that the issue is here:
https://github.com/microsoft/vscode/blob/b5a1bb34e9c6b77c2a8ccf54bcdbb4bac4d420cb/src/vs/workbench/contrib/terminal/browser/terminalInstance.ts#L2222-L2235

When on Windows, if the title set is not a path matching the regex `^[a-zA-Z]:\\.+\.[a-zA-Z]{1,3}`, then the title is not set as `this._sequence` is set to `undefined`.

As on linux the title is always set with what the process set (no regex check), I would expect it to be the same on Windows with the title being modified only if matching the regex.

By modifying my vscode installation directly, I can make the title control sequence working by remove this part of the code:
```js
else
{
    this._sequence = undefined;
}
```
Then with this modification, I get it working (this is Git Bash on Windows which already set the terminal title via $PS1):
![image](https://user-images.githubusercontent.com/5435069/187095116-66f30bd8-9d5a-4e6f-8361-f885430a31fa.png)

**Comment by amurzeau** [comment]
As a workaround, one can use this `printf '\x1b]2;C:\\test\\foo.ext\a'` instead of `printf '\x1b]2;foo\a'`

**Comment by Tyriar** [comment]
This has been fixed
