### ISSUE TITLE
Inconsistent rounded corners in text selection

### ISSUE THREAD

**Issue by PVTejas-Yottaasys** [microsoft/vscode#159453]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Ubuntu 20.04.5

Steps to Reproduce:

1. In the Activity Bar on the left side, go to the Find and Replace tab. Type something in the find or replace text boxes and select some of it. The text selection highlight will have sharp corners.
3. Now go to the source control tab. Type and select. The text selection will have rounded corners.

**Comment by Ankitchaudharyy** [comment]
I want to work on this issue. Can I contribute?

**Comment by daviddossett** [comment]
> I want to work on this issue. Can I contribute?

A PR would be welcome. Thank you 🙏

**Comment by PVTejas-Yottaasys** [comment]
I should add that the commit message field in the source control tab is the only place where I see rounded corners anywhere in the app. It's sharp corners in every other text selection highlight.

**Comment by Ankitchaudharyy** [comment]
Hey @daviddossett, Can you help, in which branch should I fix this or make a new branch?

**Comment by Ankitchaudharyy** [comment]
Hey @daviddossett, In which branch should I commit or shall I create a new branch for this?

**Comment by lramos15** [comment]
@Ankitchaudharyy You'd want to fork the repo and create a new branch.

@daviddossett I'm not sure what we want to do here, what it happens to be is where we use monaco editor widgets (which it seems source control uses too) then we have rounded corners. Normal textboxes have sharp corners. I don't know if we want to try round our normal text boxes or sharpen the monaco editor widget. 

cc @misolori

**Comment by PVTejas-Yottaasys** [comment]
As a user, I would like to see the rounded corners everywhere. It's prettier that way. I'm not aware of the performance costs though. In the end it's only a very minor inconvenience.

**Comment by lramos15** [comment]
> As a user, I would like to see the rounded corners everywhere. It's prettier that way. I'm not aware of the performance costs though. In the end it's only a very minor inconvenience.

One could argue that rounded selection corners aren't standard. I just went around to a bunch of difference apps (even those that love to use rounded UIs in buttons and other places) and did not see rounded text selection present

**Comment by daviddossett** [comment]
Input text selection backgrounds should not have rounded corners. To me this is clearly some unintentional CSS bug.

**Comment by misolori** [comment]
Not sure why this is showing up only in SCM as it's using monaco under the hood just like the extensions and settings inputs but those aren't rounded. Selection is rounded because it's done inside the editor:

https://github.com/microsoft/vscode/blob/c7378f71d1574253059628f2c797db34e2dba3a6/src/vs/editor/browser/viewParts/selections/selections.css#L14-L17

<img width="244" alt="CleanShot 2022-08-30 at 12 39 21@2x" src="https://user-images.githubusercontent.com/35271042/187528099-7e434b52-f4c9-4aee-92dd-1352adeafdf6.png">

An easy fix would be to remove the border radius in the scm monaco input via something like `.scm-view .monaco-editor .selected-text...`

**Comment by lramos15** [comment]
> Selection is rounded because it's done inside the editor:

Is there a reason selection is rounded within the editor when selection in most places is normally not rounded?

**Comment by daviddossett** [comment]
> Is there a reason selection is rounded within the editor when selection in most places is normally not rounded?

Hazarding a guess I'd say it's at least in some part an aesthetic choice. It looks nice to me, in any case.

Have a PR up at #159612 since I can't see this repro in any other input other than the SCM view.
