### ISSUE TITLE
Cannot install VSIX from integrated terminal

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#159447]
I think this used to work:
- In the integrated terminal install a new version of an already installed extension:
```sh
❯ code-insiders --install-extension remote-containers-0.248.96.vsix
Installing extensions...
(node:51792) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Electron --trace-deprecation ...` to show where the warning was created)
Extension 'remote-containers-0.248.96.vsix' was successfully installed.
```
- Reload
- Observe 0.248.0 is still the installed version of Remote-Containers.
- Both folders are there:
```sh
/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.0
/Users/chrmarti/.vscode-insiders/extensions/ms-vscode-remote.remote-containers-0.248.96
```
- Installing through the UI still works.

Version: 1.71.0-insider (Universal)
Commit: 35b971c92d210face8c446a1c6f1e470ad2bcb54
Date: 2022-08-26T09:30:57.123Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**Comment by sandy081** [comment]
It seems to happen when there are more than one profile and its a bug in our CLI that we are not passing default profile location in this case.
