### ISSUE TITLE
Navigation of cursor to front/end of file

### ISSUE THREAD

**Issue by ujshaikh** [microsoft/vscode#159404]
I like this text editor, it will be more beneficial if you provide an enhancement to move to the top or end of the file with a short key

In the current version due to the lack of this feature, I have to scroll more to goes the top/end of the file if file lines are in thousand.

**Comment by ArturoDent** [comment]
<kbd>Ctrl/Cmd</kbd>+<kbd>Home</kbd> to go to top/first line of file.

<kbd>Ctrl/Cmd</kbd>+<kbd>End</kbd> to go to bottom/last line of file.

**Comment by ujshaikh** [comment]
Thanks, @alexr00 
I tried, but it's not working for me.
If the feature is already there then it's ok, I thought it need to implement.

**Comment by alexr00** [comment]
Please see the keyboard shortcut troubleshooting: https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings
