### ISSUE TITLE
wrong update link on 32bit

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#15945]
- VSCode Version: 1.7.1
- OS Version: kali linux rolling release 32 bit

Steps to Reproduce:

1. wait for the update notification
2. click on `Download now`

Outcome:

3. the application redirect to the 64bit download

Expected:

3. the application redirects to the 32bit download

**Comment by joaomoreno** [comment]
What is _kali linux rolling release 32 bit_?

**Comment by phra** [comment]
are you [serious](https://www.lmgtfy.com/?iie=1&q=kali+linux)?

**Comment by joaomoreno** [comment]
Where did you get Code from?

**Comment by phra** [comment]
official 32bit deb package from the website.

**Comment by joaomoreno** [comment]
The application refers to https://code.visualstudio.com, from which you can select your desired platform. A better streamlined update experience will come with #229.
