### ISSUE TITLE
Text Cursor Bug

### ISSUE THREAD

**Issue by fabestah** [microsoft/vscode#159484]
Type: <b>Bug</b>

My text cursor of windows doesn't line up with the one in VS Code when I move it with the arrow keys but only when I hold the key down for a little bit. Then the cursor speeds up more and more and that speed of the windows cursor doesn't match the one in VS Code.

My windows cursor settings are:
- Text cursor indicator: On
- Size: 2
- Color: Purple
- Text cursor thickness: 1

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.32GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|40%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.8
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.40
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9

(1 theme extensions excluded)

</details>
d data into your clipboard because it was too large to send. Please paste.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/109151
