### ISSUE TITLE
Autocomplete for Node.js

### ISSUE THREAD

**Issue by Mateusz96** [Microsoft/vscode#15942]
- v1.7.2
- Win10 Pro x64

Dont working autocomplete for nodejs as association

**Comment by jrieken** [comment]
@Mateusz96 Please read https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions and update this issue

**Comment by Mateusz96** [comment]
no autocomplete if i use plain nodejs with other modules

**Comment by jrieken** [comment]
@Mateusz96 Please read and *understand* https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions and only then update this issue with steps that allow us to reproduce this. For instance a code sample, if you are in a single file or a folder of files, what module you are trying to autocomplete etc.
