### ISSUE TITLE
Edit action with inline color decorator have incorrect behavior

### ISSUE THREAD

**Issue by BusinessDuck** [microsoft/vscode#159466]
Hi team! I don't know hot to describe this bug with you local guide. Sorry for that. Just take a look at some technical details about this bug. Also i am using **monaco**, but i guess rendering and model its part of vsc.

**Source data:**
1. This is the custom language with LSP. 
2. This bug cannot be reproduced only with `'semanticHighlighting.enabled': true`
3. Client getting colors data from LSP by [document color request](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_documentColor)
4. Start line content `plot(close, color = #000000, 123)`
5. Set up position before `123`
6. Initiate type the symbol "4" by key pressing, that should change line content to `plot(close, color = #000000, 4123)`, but this does not happen

![image](https://user-images.githubusercontent.com/10143411/187223716-197d10e3-bfba-487e-9857-35a1ec7c0d3a.png)

**The problem:**
As we can see new rendered line model looks incorrect. Mean actual line update produce line with content `plot(close, color = #000000, 44412`, instead of `plot(close, color = #000000, 4123)`

![image](https://user-images.githubusercontent.com/10143411/187223313-f2393bd1-29bc-488d-8c77-b240c8d94fe0.png)

But, full model value is fine after apply edit operation take a look

![image](https://user-images.githubusercontent.com/10143411/187225639-af3a7d34-3409-4280-a06c-8427c7f6f248.png)

All screenshots was captured at once debugger pause statement.

After rendering with incorrect HTML line string, editor have incoming changes from LSP and applying a new rendering which fix previous error. In runtime it's looks like visual  "glyph"

https://user-images.githubusercontent.com/10143411/187226698-d138ca09-cf21-4f9e-a9a1-324e5ce00069.mp4

**Comment by hediet** [comment]
Can you provide a reproducible example using the [monaco playground](https://hediet.github.io/monaco-editor/playground.html)?

**Comment by BusinessDuck** [comment]
> Can you provide a reproducible example using the [monaco playground](https://hediet.github.io/monaco-editor/playground.html)?

I found the ploblem. That is conflict between LSP and monarch rules. When i solve it the problem is gone!
