### ISSUE TITLE
UNABLE TO USE CODESPACES

### ISSUE THREAD

**Issue by stahnlee** [microsoft/vscode#159415]
I'm unable to use codespaces. It does not fully load

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

<!-- generated by web issue reporter --
![Screenshot (3)](https://user-images.githubusercontent.com/24593788/187091632-d74132b6-def8-4860-a3be-3cbc6056b06e.png)
>

**Comment by Tyriar** [comment]
Please report codespaces issues to github support
