### ISSUE TITLE
Built-in syntax highlighting for C++ breaks when returning a const reference in the `T const&` syntax

### ISSUE THREAD

**Issue by martycagas** [microsoft/vscode#159456]
**Type:** Bug

**Description:** Having a function return a constant reference (`T const&`) breaks syntax highlighting for that function declaration.

**Severity:** Little-to-none. There's no loss of productivity arising from this bug, but it's clearly an oversight.

**Reproducibility:** Consistent.

**Steps to reproduce:**

- Disable all extensions.
- Open a new file.
- Set the file's language mode to C++.
- Paste the following snippet:

```cpp
ClassA FunctionOne(int& number_one, const int& number_two, int const& number_three);

const ClassA& FunctionTwo(StructA const& struct_one,
                            const StructA& struct_two,
                            int& number_one,
                            const int& number_two,
                            int const& number_three
                            );

ClassA const& FunctionThree(StructA const& struct_one,
                            const StructA& struct_two,
                            int& number_one,
                            const int& number_two,
                            int const& number_three
                            );
```

**Expected result:** The syntaxt highlighting remains consistent as `T const&` and `const T&` are semantically identical notations.

**Observed result:** The syntax highlighting of `FunctionThree()` breaks.

I also tested this with a clean install of VS Code in Windows Sandbox. A slightly different color scheme and syntax highlighting, but the error was the same.

My own VS Code installation (looks the same with or without disabled extensions):

![image](https://user-images.githubusercontent.com/22563360/187207274-19ffd11c-4056-4dd1-a8ca-f3141ae27506.png)

Completely clean Sandbox installation:

![image](https://user-images.githubusercontent.com/22563360/187207378-1817b7f8-c323-49c0-9e9d-d14ffb5d933e.png)

**VS Code version:** Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)

**OS version:** Windows_NT x64 10.0.22000

**Comment by alexr00** [comment]
We get our C++ syntax highlighting grammar from https://github.com/jeff-hykin/better-cpp-syntax. I've moved the issue to that repo: https://github.com/jeff-hykin/better-cpp-syntax/issues/606.
