### ISSUE TITLE
Webview.postMessage can sometimes hang indefinitely

### ISSUE THREAD

**Issue by eamodio** [microsoft/vscode#159431]
I don't have a limited reproduction, but with the current GitLens insiders and a specific set of steps I can get it to happen almost 100% of the time (which I can detail if we need to).

I think the root cause might be the last line here:

https://github.com/microsoft/vscode/blob/784de603197348d570857adf3a306b3b92deea1f/src/vs/workbench/contrib/webview/browser/overlayWebview.ts#L242-L248

If there were any `this._firstLoadPendingMessages` items, all of those promises would never resolve.

To be safe we should probably do the same as here:

https://github.com/microsoft/vscode/blob/784de603197348d570857adf3a306b3b92deea1f/src/vs/workbench/contrib/webview/browser/overlayWebview.ts#L82-L85

If there is anything in the Set

/cc @mjbvz

**Comment by ThadHouse** [comment]
I'm running into this in one of my extensions. Seems like a regression, as this hasn't happened in the past.

**Comment by pluff** [comment]
I faced the same issue and created minimal reproducible example:  https://gitlab.com/pshutsin/vscode-webview-hangs-example

It seems like VSCode hangs execution if the webview wasn't ready at the time of first `postMessage`.

**Comment by shd101wyy** [comment]
Do we have any suggestions on how to fix this? I am the author of [this extension](https://github.com/shd101wyy/vscode-markdown-preview-enhanced). The webview sometimes failed to load correctly. Thank you.

**Comment by urbanfly** [comment]
I am running into the same problem. The message appears to be delivered, but the `Promise` is never resolved.

Skipping the `await` on the `postMessage` `Promise` is acceptable in my situation, but annoying.

**Comment by bpasero** [comment]
@eamodio with the fix for https://github.com/microsoft/vscode/issues/208263, maybe this issue is also gone.

**Comment by eamodio** [comment]
I tried the sample with today's insiders but am still seeing the hang

**Comment by bpasero** [comment]
@eamodio to clarify, we only released an insiders with that fix with `8cfe998a17786ace2a19079feab8b24f42ecc896` 3h ago, not earlier today.

And when you reproduce, does it still reproduce with floating windows?

**Comment by eamodio** [comment]
I just saw that and since I updated it seems to fix both issues! TY!
