### ISSUE TITLE
Add Code Explorer 

### ISSUE THREAD

**Issue by BruceGitHub** [Microsoft/vscode#15944]
@#- VSCode Version:
- OS Version: Windows, Mac, Linux

Request to add Code Explore from file 

Simil 
![vs code1](https://cloud.githubusercontent.com/assets/5399875/20555753/e8d596c6-b163-11e6-9d05-d551248d171b.JPG)

**Comment by leaxoy** [comment]
duplicate with #5605

**Comment by jrieken** [comment]
thanks @leaxoy

**Comment by BruceGitHub** [comment]
sorry! 
happen php code does not find symbols
