### ISSUE TITLE
Can't download materials for CS50 Week3 problem set

### ISSUE THREAD

**Issue by MiLu78** [microsoft/vscode#159457]
when trying to execute wget https://cdn.cs50.net/2021/fall/psets/3/plurality.zip

getting message

--2022-08-29 13:10:05--  https://cdn.cs50.net/2021/fall/psets/3/plurality.zip
Resolving cdn.cs50.net (cdn.cs50.net)... failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘cdn.cs50.net’

**Comment by mjbvz** [comment]
This isn't related to VS Code
