### ISSUE TITLE
issue report

### ISSUE THREAD

**Issue by adriankuta1** [microsoft/vscode#159423]
codespace not loading

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
Pls create an issue in the code spades repo

**Comment by F1tZ81** [comment]
Where would this repo be? The codespaces documentation points us here.
