### ISSUE TITLE
task.experimental.reconnection keeps tasks running after quit

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#159459]
Type: <b>Bug</b>

When `task.experimental.reconnection` is set to `true`, running tasks are not terminated when Visual Studio code is quit and are restored when VSCode is relaunched. This happens even if I have `terminal.integrated.confirmOnExit` set to `"hasChildProcesses"` and I select the "Terminate" option from the confirm dialog.

VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|32.00GB (7.12GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.6.1
vscode-zipfs|arc|3.0.0
restore-git-branch-tabs-improved|ava|1.1.0
beardedicons|Bea|1.0.0
vscode-css-modules|cli|0.4.2
vscode-github-actions|csc|0.24.2
vscode-eslint|dba|2.2.6
vscode-dash|dee|2.4.0
find-related|eam|0.9.0
gitlens|eam|12.1.2
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
vscode-open-in-application|fab|1.0.6
vscode-firefox-debug|fir|2.9.8
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.48.1
gitpod-desktop|git|0.0.54
go|gol|0.35.2
vscode-graphql-syntax|Gra|1.0.4
todo-tree|Gru|0.0.215
yarn2-dependency-explorer|hah|0.0.3
hcl|has|0.2.1
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
svg|joc|1.4.19
vscode-peacock|joh|4.1.0
json-escaper|jos|1.1.2
vscode-styled-components|jpo|1.7.0
ts-error-translator|mat|0.5.1
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.10.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.11.5
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5695
cssvar|pho|2.2.0
vscode-yaml|red|1.9.1
partial-diff|ryu|1.4.3
mdx|sil|0.1.1
vscode-quick-scope|ska|0.2.0
vscode-fileutils|sle|3.5.0
reveal|smu|1.2.7
swdc-vscode|sof|2.6.33
code-spell-checker|str|2.7.0
vscode-stylelint|sty|1.2.3
sass-indented|syl|1.8.22
icons|tal|3.4.0
sapling|tea|1.2.0
shellcheck|tim|0.21.3
jest-snapshot-language-support|tle|1.1.1
vscode-terminal-here|Tyr|0.2.4
vscodeintellicode|Vis|1.2.23
vscode-icons|vsc|11.16.0
vim|vsc|1.23.2
vscode-css-variables|vun|2.4.2
wvsc-serendipity|wic|0.104.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by diminutivesloop** [comment]
Yeah I forgot to try reproducing this in Insider's before reporting, but when I did I couldn't find the `task.experimental.reconnection` setting anymore. Was it renamed or completely removed?

**Comment by meganrogge** [comment]
renamed - now it's `task.reconnection`
