### ISSUE TITLE
Permission denied when file in OneDrive

### ISSUE THREAD

**Issue by dmonder** [microsoft/vscode#159419]
Type: <b>Bug</b>

Using Onedriver v0.12.0 on Ubuntu 22.04.1 with VS Code 17.0.2.

1. In terminal, navigate to file in OneDrive (e.g., `cd OneDrive/src/dir`).
2. Enter `code file.ext` to edit file.

Expected VS Code to open the file in the editor, but instead get the following error:

    cannot open path of the current working directory: Permission denied

If I open VS Code in my home folder (`cd ~`) and enter `code .`, then choose File -> Open and navigate to the file in question, VS Code is able to open the file without issue.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:25.715Z)
OS version: Linux x64 5.15.0-46-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics (1 x 3892)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 1, 1|
|Memory (System)|7.75GB (0.14GB free)|
|Process Argv|--no-sandbox /usr/share/sile/core/frameparser.lua --crash-reporter-id 82e3d01b-a529-4221-92d9-19bb79dceba9|
|Screen Reader|no|
|VM|100%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
op-vscode|1Pa|1.0.1
better-comments|aar|3.0.2
vscode-sqlite|ale|0.14.1
spellright|ban|3.0.90
github-markdown-preview|bie|0.3.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
better-toml|bun|0.3.2
docs-markdown|doc|0.2.113
xml|Dot|2.5.1
prettier-vscode|esb|9.8.0
remotehub|Git|0.40.0
vscode-pull-request-github|Git|0.48.1
beautify|Hoo|1.5.0
vscode-edit-csv|jan|0.7.2
dotnet-interactive-vscode|ms-|1.0.3405010
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
black-formatter|ms-|2022.5.12301009
isort|ms-|2022.3.12390105
pylint|ms-|2022.5.12301010
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.40
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
hexeditor|ms-|1.9.8
powershell|ms-|2022.7.2
powershell-preview|ms-|2022.8.5
remote-repositories|ms-|0.18.0
vscode-powerquery|Pow|0.1.42
quarto|qua|1.33.0
vscode-yaml|red|1.9.1
r|REd|2.5.2
sourcery|sou|0.12.7
vscodeintellicode|Vis|1.2.23
vscode-conventional-commits|viv|1.24.2
markdown-all-in-one|yzh|3.4.3

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by bpasero** [comment]
This sounds like a configuration problem that we cannot fix in VSCode but asking nevertheless: do you use the integrated terminal in VSCode for opening?

**Comment by dmonder** [comment]
I tried this in the integrated terminal and an external terminal session. Same problem.

**Comment by bpasero** [comment]
And from the command line can you create, delete, rename files without permission issues?

**Comment by dmonder** [comment]
Yes. I am able to create, delete, rename files from the external terminal session and the integrated terminal. 

I was able to confirm that I can also, from my home directory (`cd ~`), open VS Code on the directory in my OneDrive (`code OneDrive/src/dir`). From there, I can also create a file in the OneDrive folder, rename it, and delete it - all from VS Code File Explorer.

It seems the only problem is that I cannot run VS Code in the OneDrive folder itself (`cd ~/OneDrive/src/dir; code .`). I tested another Snap program (`htop`) and that has the same error. I am reporting this to the Onedriver GitHub as well.

**Comment by bpasero** [comment]
From the description the issue sounds like a setup / configuration problem outside of VSCode and nothing VSCode itself could fix.

VSCode is built on top of a large number of components that are not maintained by the VSCode team directly. This includes:
* [Electron](https://github.com/electron/electron) as the cross platform UI framework
* [node.js](https://github.com/nodejs/node) for most integration into the OS
* [Chromium](https://bugs.chromium.org/p/chromium/issues/list) as runtime and rendering engine (HTML, CSS, JS)
* and after all, the operating system VSCode is running on

We also have a large community over at https://stackoverflow.com/questions/tagged/visual-studio-code to ask for advice.

Happy Coding!
