### ISSUE TITLE
Auxiliary/Secondary sidebar uses the default 'foreground' color for text, but 'sidebar' coloring for all other elements

### ISSUE THREAD

**Issue by mj-spencer** [microsoft/vscode#159418]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:38:59.695Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 21.6.0

- OS Version: MacBook Pro (Apple Silicon Version, running Mac OS 12.5.1)
Does occur on Insiders.

Summary:

Auxiliary/Secondary sidebar uses the default 'foreground' color for text, but 'sidebar' coloring for all other elements. This is both inconsistent and problematic when using a darker sidebar and a lighter editor.background, since getting the 'main' tree text light enough to read also makes it illegible on other pages where 'foreground' is used, such as settings and keyboard shortcuts. Further, since the Auxiliary/Secondary sidebar uses the other sidebar theme colors (such as sidebarBackground, sideBarSectionHeader.background/foreground), it makes sense to use the sidebar.foreground color for tree elements rather than the default foreground. Occurs on both default VSCode light and dark themes.

Steps to Reproduce:

1. Use the following snippet for user settings:

``` json
{
    "telemetry.telemetryLevel": "off",
    "terminal.integrated.fontSize": 13,
    "workbench.colorCustomizations": {
        "sideBar.foreground": "#33ff00", //I would expect this color to be used in the auxilary/secondary sidebar
        "sideBarSectionHeader.foreground": "#f0f", //included to show that other sidebar colors are used in the aux/secondary sidebar
        "foreground": "#ff0000" //Color currently being used in the auxilary/right side sidebar foreground (when not covered by other colors for errors)
    }
}
```

2. Note that the sideBar.foreground color is not used in the auxilary sidebar, while other sideBar.xx theme settings are.

Screenshot:
<img width="2560" alt="Screen Shot 2022-08-28 at 2 28 26 PM" src="https://user-images.githubusercontent.com/64339311/187093784-dc80ef4d-155c-486a-9103-016c58257d4b.png">

**Comment by mj-spencer** [comment]
Related to this, the icons/active border in the auxilary sidebar take the panelTitle properties for the foreground, and the sidebar.background property for the background. Not sure if this should be a separate issue or not, but seems related since while the terminal within the panel may have its own coloring, the panel coloring itself may or may not be the same as the sidebar, whereas the aux sidebar is always taking its background from the primary sidebar. Keeping the theme properties for the aux sidebar consistent as opposed to pulling from a mix of sidebar, panel, and default makes the most sense.

``` json
    "panelTitle.activeBorder": "#ff0000",
    "panelTitle.activeForeground": "#ff0000",
    "panelTitle.inactiveForeground": "#ff0000",
```

<img width="326" alt="image" src="https://user-images.githubusercontent.com/64339311/187164014-28dc4993-7c97-4432-92ab-82737e37ff6e.png">

**Comment by sbatten** [comment]
Solving the first problem since they are analogous. The second problem is definitely an issue, but the icons in the secondary side bar are analogous to the activity bar icons as opposed to the side bar, so we will probably need new theme keys since the activity bar background should not be force applied.

**Comment by aeschli** [comment]
Verified that the secondary side bar uses the "sideBar.foreground" color
