### ISSUE TITLE
VS Code cannot store keyring when keyring directory does not exist (in Chrome OS)

### ISSUE THREAD

**Issue by haifeng-jin** [microsoft/vscode#159434]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Chrome OS Linux Terminal (Crostini) Debian GNU/Linux 11 (bullseye)

Steps to Reproduce:

1. Run VS Code.
2. Sign in with GitHub.
3. Close VS Code.
4. Run VS Code.
5. It ask me to sign in again.

Cause:

It is caused by the VS Code trying to create a keyring, but the directory to store the keyring does not exist yet.

My Solution:

I had to manually create the directory:
```
mkdir ~/.local/share/keyrings
```
Then the problem is solved.

However, I expect VS Code would create the directory for me if it does not exist.

**Comment by TylerLeonhardt** [comment]
We depend on https://github.com/atom/node-keytar for our keyring access. It provides a platform agnostic API so I would expect this library to create this directory. Can you get an issue going over there?
