### ISSUE TITLE
Changing Tabs with Ctrl + Page Up/Down not working for Terminals after move to editor and back to panel

### ISSUE THREAD

**Issue by flashcode** [microsoft/vscode#159471]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.70.2
- OS Version: Linux x64 5.18.0-4-amd64 (Debian Bullseye)

Steps to Reproduce:

1. Open Panel, select Terminal tab.
2. Create a new terminal.
3. Right click on terminal (panel), select "Move Terminal into Editor Area"
4. Right click on terminal (editor tab), select "Move Terminal into Panel"
5. Key bindings Ctrl-PageUp and Ctrl-PageDown to change active terminal are not working in this terminal (but still works in the first opened terminal).

Expected result:

Key bindings Ctrl-PageUp and Ctrl-PageDown are still working after moving terminal to editor and back to panel.

Additional info:

I'm not sure but this bug might have been added while fixing #128503.

**Comment by Tyriar** [comment]
Can reproduce, I'm guessing the terminal editor focus context key gets stuck somehow.

**Comment by tisilent** [comment]
I want to try
