### ISSUE TITLE
Ability to control editor.suggest.showInlineDetails

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#159422]
It would be useful if we could control what to show inside inline details for suggest widget and what not. What I would like is to hide all inline details except import information.

To be able to have this:
<img width="435" alt="Screenshot 2022-08-29 at 03 46 09 AM" src="https://user-images.githubusercontent.com/10441177/187102578-443c115c-76ea-4201-9b1b-cedcff32efb4.png">

Instead of this:
<img width="433" alt="Screenshot 2022-08-29 at 03 48 19 AM" src="https://user-images.githubusercontent.com/10441177/187102728-beb10b62-bfa4-49a2-9cbd-69facdc0af47.png">

Why? Because those inline details hide longer names and they are often useful only for import information.

**Comment by jrieken** [comment]
> What I would like is to hide all inline details except import information.

How would you classify that? You can simply turn details off and show the suggestion details for extra information

**Comment by svipas** [comment]
@jrieken Thanks a lot for comment. I'm not quite sure if I still think it's useful feature. Because those often help to see enum values, etc. So to hide all that information just so I can have longer names I think I lose too much valuable information. And, as you mentioned I could extend suggest widget to show details (ctrl + space while suggest widget is visible) which gives me additional space to see suggestion.

It's up to you to keep or close this issue.

**Comment by jrieken** [comment]
Thanks for catching up. I am closing this as question then. Not keen on yet another setting tbh
