### ISSUE TITLE
When switching tabs, wrong position in file is focused if there is collapsed code

### ISSUE THREAD

**Issue by PunchyRascal** [Microsoft/vscode#15946]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-toothpaste|aalaap|0.0.1|
|Bookmarks|alefragnani|0.10.0|
|one-monokai|azemoh|0.1.15|
|vscode-icontheme-nomo-dark|be5invis|1.1.5|
|plsql|casian|0.0.2|
|theme-dracula|dracula-theme|1.2.5|
|theme-spacemacs|dzannotti|0.0.8|
|vscode-turtle|feihuangtengda|1.0.30|
|Theme-Carbonight|gerane|0.0.2|
|Theme-CloudsMidnight|gerane|0.0.2|
|Theme-Dreamweaver|gerane|0.0.2|
|Theme-Eiffel|gerane|0.0.2|
|Theme-Frontier|gerane|0.0.2|
|Theme-Hyrule|gerane|0.0.2|
|Theme-TwoStones|gerane|0.0.2|
|Theme-Wildlife-Day|gerane|0.0.2|
|findfile|HastenS|0.0.4|
|theme-glacier|Kal|0.0.1|
|Theme-MaterialKit|ms-vscode|0.1.1|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|cucumber|stevejpurves|0.9.6|
|gitblame|waderyan|1.3.0|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1) open two files
2) collapse some large portions of code in file 1
3) click e.g. on first line in file 1
4) scroll down few screens in file 1
5) switch to file 2
6) switch back to file 1
7) you will be scrolled (focused) to a wrong position, different from where you were before the switch

**Comment by bpasero** [comment]
@PunchyRascal 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by PunchyRascal** [comment]
Same result
![image](https://cloud.githubusercontent.com/assets/821272/20560751/429a4492-b17b-11e6-86b8-da7e3d63f4ff.png)
(it would be nice if one could copy from the "about" box)

**Comment by bpasero** [comment]
Wow, this is bad.

**Comment by bpasero** [comment]
![untitled](https://cloud.githubusercontent.com/assets/900690/20563998/47f1a5a6-b18b-11e6-8049-72eb7ac9e588.gif)

I can reproduce and it looks like a bug in the editor because the view state I am setting to restore contains the scrollTop location but the editor still ends up to be where the cursor is.

@alexandrudima @rebornix can you have a look and see if this is a regression?

**Comment by rebornix** [comment]
This happens when we try to restore the state of the folding contributions, which kicks in when we restore the state of the view.

**Comment by rebornix** [comment]
@aeschli per https://github.com/Microsoft/vscode/issues/3314#issuecomment-189310134 and the code base, it seems right now this behavior is kind of `as-design`, we always reveal current cursor if there are hidden areas when switching tabs, as this piece of code has not been touched for a while, could you share some info behind it?

**Comment by aeschli** [comment]
@rebornix Revealing the cursor while restoring the folding state is a bug.
I'll push a fix. That's for tracking that down!

**Comment by orlandovallejos** [comment]
I don't know, but this is happening again.
Steps to reproduce it are the same, just in this case, press an arrow key. That will take you most of the times to the end of file.

**Comment by alexandrudima** [comment]
@orlandovallejos This should be fixed on the Insiders Build.
