### ISSUE TITLE
[java] enum with values coloring is off

### ISSUE THREAD

**Issue by Matthijs-Wessels** [Microsoft/vscode#1594]
The coloring of java enums if off when you add values. The strings in the below example will be colored as if it's code (i.e. 'Banana', 'Apple', 'Co' and 'Nut' are blue; and 'co' is white

```
public enum Fuit {
    Banana ("Banana"),
    Apple ("Apple"),
    Coconut ("Co co Nut");

    public final String text;

    private Option(final String text) {
        this.text = text;
    }
}
```

**Comment by aeschli** [comment]
This issue was moved to textmate/java.tmbundle#40

**Comment by aeschli** [comment]
Closing this issue as it is tracked in textmate/java.tmbundle#40
