### ISSUE TITLE
Quick hint creates a new method inside a method even if i comment that method

### ISSUE THREAD

**Issue by Capoutcha** [Microsoft/vscode#15948]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|dart-code|DanTup|0.14.4|
|javadebugger|donjayamanne|0.0.2|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|

---

Quick hint creates a new method inside a method even if i comment that method looks like he add the new method in that specific ligne

**Comment by jrieken** [comment]
@Capoutcha Can you include a sample and let us know with what language this happens?

**Comment by Capoutcha** [comment]
i am using DART 

![image](https://cloud.githubusercontent.com/assets/9768420/20563216/dfbc65e6-b187-11e6-8129-6d3e2d9a80c6.png)

it creates a mthod inside another one:

![image](https://cloud.githubusercontent.com/assets/9768420/20563267/1d82f58e-b188-11e6-9c4e-f2f10721a176.png)

it is like i want to always add the method at that line

simples:
[hero_service - Copie.dart.txt](https://github.com/Microsoft/vscode/files/608931/hero_service.-.Copie.dart.txt)
[heroes_component - Copie.dart.txt](https://github.com/Microsoft/vscode/files/608934/heroes_component.-.Copie.dart.txt)

**Comment by jrieken** [comment]
Thanks - please file this issue against the extension
