### ISSUE TITLE
Fetch build task is loading indefinitely

### ISSUE THREAD

**Issue by sssteja5** [microsoft/vscode#159552]
Type: <b>Bug</b>

After the latest vscode update, I see that upon ctrl+shift+b will end up in infinite wait of fetching_build_tasks

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.4.0-105-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (4.27GB free)|
|Process Argv|--crash-reporter-id 9ddb9538-093b-422d-93e3-fce0c0f24316|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: sssteja-VM-U20.habana-labs.com|
|OS|Linux x64 5.4.0-105-generic|
|CPUs|Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz (12 x 2194)|
|Memory (System)|38.97GB (8.11GB free)|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.6.1
remote-ssh|ms-|0.84.0
project-manager|ale|12.6.1
gitignore|cod|0.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|12.1.2
git-graph|mhu|1.30.0
cpptools|ms-|1.11.5
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by sssteja5** [comment]
Installing this insider build --> will this clear my existing vscode plugins/configurations, etc ?

**Comment by meganrogge** [comment]
nope it will not!

**Comment by sssteja5** [comment]
But this is trying to install in a different folder (vscode internals). Can i install in the same folder as VSCODE without messing up with my plugins/ssh_configuration, etc ?

**Comment by sssteja5** [comment]
After vscode updated to 1.71, issue no longer exists. Can close the ticket
