### ISSUE TITLE
Arrows key behavior between chunks in python jupyter notebook

### ISSUE THREAD

**Issue by Camilochiang** [microsoft/vscode#159576]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Ubuntu 18.04.6 LTS 

Steps to Reproduce:

When working with python jupyter notebooks (.ipynb) is possible to pass from one python chunk to another using the arrows keys, only from a lower chunk to a higher one (arrow up) . This do not work when trying to pass from a higher chunk to a lower one using the arrow keys
1. Create a ipynb file with three python chunks
2. Click in the middle one and try to move between chunks only using the arrows. You will see that you cannot go to lower chunks, only higher ones.

I hope that is clear! Thanks ;)

**Comment by roblourens** [comment]
I don't understand, sorry, a gif or screenshot would help

**Comment by Camilochiang** [comment]
1. Create a ipynb file with three python chunks
![Uploading Screenshot from 2022-09-29 11-13-47.png…]()

3. Click in the middle one and try to move between chunks only using the arrows. You will see that you cannot go to lower chunks, only higher ones.
![Screenshot from 2022-09-29 11-13-50](https://user-images.githubusercontent.com/48471579/192992778-b4be5036-f251-47bd-a2b6-36c392b47159.png)

**Comment by roblourens** [comment]
That's not 3 python cells, that's 2 markdown cells and a python cell. But it works for me, most likely you have an extension overriding the arrow down keybinding. Running the command "Toggle keyboard shortcuts troubleshooting" should help you figure out which one it is.
