### ISSUE TITLE
Integrated Terminal with Powerline Always shows errorcode "1"

### ISSUE THREAD

**Issue by th0ger** [microsoft/vscode#159544]
Type: <b>Bug</b>

On VS Code integrated terminal (WSL2/bash), Powerline always shows a red errorcode "1".

Powerline works well on Windows terminal.

![image](https://user-images.githubusercontent.com/26322144/187408010-f5c3492a-893b-4748-88db-3b2bfec516df.png)

--- 

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (8.77GB free)|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|24.88GB (12.48GB free)|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-drawio|hed|1.6.4
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.245.2
remote-ssh|ms-|0.84.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vscode-ndjson|adr|0.100.0
blamer-vs|bea|0.5.2
markdown-footnotes|bie|0.0.7
markdown-shiki|bie|0.1.1
vscode-markdownlint|Dav|0.48.1
xml|Dot|2.5.1
parquet-viewer|dvi|2.2.0
gitlens|eam|12.1.2
vale-server|err|0.15.2
gitlab-workflow|Git|3.49.0
vscode-edit-csv|jan|0.7.2
svn-scm|joh|2.15.5
render-crlf|med|1.6.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.22.1
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.40
jupyter|ms-|2022.7.1102252217
jupyter-renderers|ms-|1.0.9
preview-vscode|myh|1.3.0
autodocstring|njp|0.6.1
ansible|red|0.12.30
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
markdown-preview-enhanced|shd|0.6.3
svn-scm-ext|spm|1.2.1
even-better-toml|tam|0.17.1
avro-tools|tom|0.0.2
simple-rst|tro|1.5.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by th0ger** [comment]
This workaround removes the issue, but naturally also disables other stuff like Command decorations. Is this intentional?

```json
"terminal.integrated.shellIntegration.enabled": false
```
![image](https://user-images.githubusercontent.com/26322144/187418853-55af56b0-492a-49f8-bcf7-19c9b0337cfa.png)

**Comment by sdescarries** [comment]
Got the same problem on MacOS, status code is always 1 regardless of the last command, but it appears to be related to powerline. If I reset my prompt to something basic, the integration works fine.

![Screen Shot 2022-08-30 at 9 06 44 AM](https://user-images.githubusercontent.com/40470761/187444475-35eec9a1-8200-4fbe-86ec-7d0a8d6e4ba7.png)

With powerline active and `set -x` running `true`:

```
++ __vsc_preexec_only -x
++ '[' 0 = 0 ']'
++ __vsc_in_command_execution=1
++ __vsc_preexec
++ __vsc_initialized=1
++ [[ ! true =~ ^__vsc_prompt* ]]
++ __vsc_current_command=true
++ __vsc_command_output_start
++ builtin printf '\033]633;C\007'
+++ echo true
+++ sed s/%/%%/g
++ builtin printf '\033]633;E;true\007'
+ true
+++ __vsc_preexec_only true
+++ '[' 1 = 0 ']'
++ __vsc_prompt_cmd_original
++ __vsc_status=0
++ [[ 1 -gt 1 ]]
++ eval powerline
+++ powerline
+++ CODE=1
```

Shell integration seems to do about the same thing as powerline so I'm okay with disabling it, thanks @th0ger for the workaround 👍🏼

**Comment by meganrogge** [comment]
This line is meant to restore the exit  code before the next line evals 

https://github.com/microsoft/vscode/blob/1715e06bb254338f163ed75472bc367f7a742a30/src/vs/workbench/contrib/terminal/browser/media/shellIntegration-bash.sh#L192

**Comment by meganrogge** [comment]
so `eval "${__vsc_original_prompt_command:-}"` must be resulting in an error/exit code - what is your `$PROMPT_COMMAND` when you have shell integration disabled?

**Comment by meganrogge** [comment]
I see in `powerline.sh`:
```
_powerline_add_status_wrapped_command() {
        local action="$1" ; shift
        local cmd="$1" ; shift
        full_cmd="_powerline_status_wrapper $cmd"
        if test "$action" = "append" ; then
                PROMPT_COMMAND="$PROMPT_COMMAND"$'\n'"$full_cmd"
        else
                PROMPT_COMMAND="$full_cmd"$'\n'"$PROMPT_COMMAND"
        fi
}
```

and

```
_powerline_setup_prompt() {
        VIRTUAL_ENV_DISABLE_PROMPT=1
        if test -z "${POWERLINE_COMMAND}" ; then
                POWERLINE_COMMAND="$("$POWERLINE_CONFIG_COMMAND" shell command)"
        fi
        test "$PROMPT_COMMAND" != "${PROMPT_COMMAND%_powerline_set_prompt*}" \
                || _powerline_add_status_wrapped_command prepend _powerline_set_prompt
        PS2="$(_powerline_local_prompt left -r.bash 0 0 0 continuation)"
        PS3="$(_powerline_local_prompt left '' 0 0 0 select)"
}

```

**Comment by meganrogge** [comment]
@Tyriar maybe we can detect this case - upon failure of evaluating the `PROMPT_COMMAND`, reset status, disable shell integration, and return

**Comment by sdescarries** [comment]
Here's my `PROMPT_COMMAND`:

```bash
function powerline() {
  CODE=${?}
  JOBS=$(jobs -p | wc -l)
  PS1=$(powerline-go -hostname-only-if-ssh -newline -error ${CODE} -jobs ${JOBS})
}
export PROMPT_COMMAND=powerline
```

**Comment by th0ger** [comment]
```bash
$ echo $PROMPT_COMMAND
__vsc_prompt_cmd_original
```

With workaround `"terminal.integrated.shellIntegration.enabled": false` (then create new integrated terminal), and also for Windows Terminal:

```bash
$ echo $PROMPT_COMMAND 
_powerline_status_wrapper _powerline_set_prompt
```
