### ISSUE TITLE
jsconfig in default user settings?

### ISSUE THREAD

**Issue by mikeal** [Microsoft/vscode#1595]
I'm trying to figure out how to set better jsconfig defaults (without adding a new file to every project) but I can't figure out how to add them to the user settings files.

**Comment by bpasero** [comment]
I guess this is not supported @jrieken

**Comment by jrieken** [comment]
Nope. We have made ES6 the default and that's all we can do at this point. Once we have adopted project salsa we can revisit.

**Comment by mikeal** [comment]
what is project salsa?

**Comment by egamma** [comment]
pls see https://github.com/Microsoft/TypeScript/issues/4789
