### ISSUE TITLE
A11y_VisualStudioCodeClient_Sidebar Bar Options_Accessing The  Extension  bar options_keyboard: Tooltip information for the extensions under "popular" tab are not visible when going through Tab or Arrow key. 

### ISSUE THREAD

**Issue by v-inanda** [microsoft/vscode#159532]
###  **GitHub Tags:**
#A11yMAS; #A11yTCS; #A11ySev3; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2022; #WCAG2.1.1; #Keyboard.

### **Environment and OS details:**
Visual Studio Code Version: 1.70.2 (user setup)
Windows 11 Pro version 21H2 (OS Build 22000.856)

### **Repro Steps:**
Open Visual studio code editor.
Using "Ctrl+Shift+X" key tab to the extension side view bar option.
Tab to "Python" extention under "popular" tab
Verify that tooltip information for 'Python' extension is visible or not.

### **Note:**
Similar issue is also observed in Problems, Outputs, Terminal, Debug console tooltips, View problem tooltip, and also in the code in editor Window tooltip.

### **Actual Result:**
Tooltip information for the extensions under "Popular" tab are not visible when going through Tab or Arrow key. 

### **Expected Result:**
Tooltip information for the extensions under "Popular" tab should be visible when going through Tab or Arrow key. 

### **Attachment:**
![Tooltip info](https://user-images.githubusercontent.com/91525824/187369511-00f05cc4-40c8-45aa-92b3-cc82221b898f.gif)

**Comment by isidorn** [comment]
All this information is available as part of the extension details page.
So the user should focus the extension details page and navigate there
@Tyriar it would be cool if `Cmd + K, Cmd + I` worked across the workbench to trigger and move focus to native hover. That way this experience would be more accessible.

Anyways closing as this info is already covered in the extension details

**Comment by v-inanda** [comment]
Closing this bug as all the tooltip information is available as part of the extension details page.
So, the user should focus the extension details page and navigate there and see the information.
