### ISSUE TITLE
Highlighting a row of '*'

### ISSUE THREAD

**Issue by danecek099** [Microsoft/vscode#15957]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:53:14.822Z)
- OS Version: Windows_NT ia32 10.0.14393

When you type a row of stars, like this "*************************************", and then you highlight it with cursor, it makes some weird shadows and stuff... Just try it, you´ll see

**Comment by jrieken** [comment]
I believe this is the find occurrences on selection feature

**Comment by alexandrudima** [comment]
@danecek099 This can be turned off via `"editor.selectionHighlight": false`
