### ISSUE TITLE
black screen on VSCODE 1.70 even disable gpu is applied

### ISSUE THREAD

**Issue by Hemant-Git911** [microsoft/vscode#159597]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by deepak1556** [comment]
Closing as issue does not follow our bug reporting guidelines https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions
