### ISSUE TITLE
Terminal doesn't work

### ISSUE THREAD

**Issue by yuanquan404** [microsoft/vscode#159519]
Terminal doesn't work and there is no error message after upgrade.

Yesterday, there was an upgrade. I tried to restart my vscode to apply the upgrade. After the restart, the terminal stopped working.
So, how do i get the detailed error information?

![image](https://user-images.githubusercontent.com/39118901/187341648-4fb3eb9b-8695-4c2e-8597-b5a58a5fb0b8.png)

**Comment by yuanquan404** [comment]
Here are system info and extension info.
The error "Too much data" will be reported when I try to use `submit bug`, so I paste the information here.
 
![image](https://user-images.githubusercontent.com/39118901/187343047-d238cfb7-d942-46c7-b22d-7d83dc46c86e.png)
![image](https://user-images.githubusercontent.com/39118901/187343075-2e71252f-8251-4ee1-a722-5fe23240456b.png)

**Comment by yuanquan404** [comment]
Remote settings:
![image](https://user-images.githubusercontent.com/39118901/187343773-50f6d63c-8d4f-4fa8-b9bb-1651ae0161ff.png)

**Comment by yuanquan404** [comment]
A/B test info:
```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
```

**Comment by meganrogge** [comment]
Can you do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by yuanquan404** [comment]
Thanks for your reply. 

I found this error log in the file `remoteagent.log`.
`/data01/yuanquan/.vscode-server/data/logs/20220829T150410/remoteagent.log:[2022-08-31 11:26:44.756] [remoteagent] [error] ["Error: EACCES: permission denied, copyfile '/data01/yuanquan/.vscode-server/bin/da76f93349a72022ca4670c1b84860304616aaa2/out/vs/workbench/contrib/terminal/browser/media/shellIntegration-rc.zsh' -> '/tmp/vscode-zsh/.zshrc'"]`

It seems that this folder is occupied by other users. And when I tried to delete this folder and reload vs-code, the terminal resumed. 
So, how can I change the default path for zsh? or do you have some suggestions to avoid this issue?

**Comment by grst** [comment]
I'm getting the same error when connecting to a multi-user system with the ssh extension.
