### ISSUE TITLE
Please do not change default/current behaviours of VSCode

### ISSUE THREAD

**Issue by epoberezkin** [microsoft/vscode#159529]
VSCode has become bloated with features and more difficult to use - many updates introduce disruption (e.g. the most recent terminal integration, that added zero value, and made terminal unstable, until I disabled them).
These new features are added not as opt-in but as opt-out.

There is no need for so many changes in small things - it is just disruptive, to the point of disabling automatic updates, even though it's a security risk...

Please reconsider your product strategy to avoid disruption to the existing users, otherwise VSCode will lose its position of leadership, which would be a shame...

Thank you

As a side note, a similar thing seems to be happening with GitHub, it is not as bad yet as VSCode, but it is getting worse.

**Comment by epoberezkin** [comment]
The point was that you have a large and loyal user base who professionally depend on you.

It's almost a philosophical question "who owns the product". From my point of view, introducing product changes in the current workflows as opt-out rather than as opt-in shows the lack of respect to the current users and undermines the trust.

The comment was not about terminal integration, it's just one case of many changes over the last couple years, but about product evolution in general – introducing disruptive changes is a norm for VSCode, and not the exception.

Please consider offering users to enable the new features, with some tours and explanations why it might be beneficial, instead of just enabling them and offering some obscure settings to disable them.

I wouldn't normally write any of it, but the practice of changing the workflows of the users is long standing, and it went from mildly annoying, to massively disruptive.

I would really appreciate if it's re-considered, strategically.

**Comment by Tyriar** [comment]
cc @isidorn - you might be a better person to take the feedback
