### ISSUE TITLE
CSS Custom Data Autocomplete

### ISSUE THREAD

**Issue by break-stuff** [microsoft/vscode#159512]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Mac OS Monterey 12.5

Steps to Reproduce:

1. Add a reference to this custom CSS file to the VS Code settings. [vscode.css-custom-data.json.zip](https://github.com/microsoft/vscode/files/9448630/vscode.css-custom-data.json.zip)
2. Open a CSS file and add the property `--border-radius` to ruleset and notice that when the autocomplete options display the full variable name and var wrapper, but when selected it only returns only the var wrapper and not the whole value.

![vs_code_autocomplete](https://user-images.githubusercontent.com/31320098/187325070-bfe7f58e-f42f-4366-a038-a27991895668.gif)

**Comment by aeschli** [comment]
This is a bit of a sketchy use of custom data. It is meant for real properties and property value, not variables,

Still, it's a bug and I prepared a fix: https://github.com/microsoft/vscode-css-languageservice/pull/286

**Comment by break-stuff** [comment]
I can't even begin to tell you how much design systems engineers are going to love this. Thank you!
