### ISSUE TITLE
Don't directly use `MenuRegistry#onDidChangeMenu`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159564]
The `debugToolBar` directly listens on the menu registry changing. During startup this happens +1200 times and while it is fast it isn't needed as menus (once created) already emit events. 

Also, the [actual handling](https://github.com/microsoft/vscode/blob/eed1b6ac4907e125fa9188e7a3253bc94cf7aac1/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L320-L327) has a quadratic runtime has each new contribution removes and re-registers all existing contributions. 

Looking at this holistically none of it might be needed as the view itself should be powerful enough to simple merge its `ViewContainerTitle`-menu with the `DebugToolBar`-menu

**Comment by isidorn** [comment]
@jrieken great catch, thanks for creating this issue.

This change was initially done to make sure the Extension contributed command in the debug toolbar also showup when the toolbar is docked (thus it is shown in the debug view menu). Original issue https://github.com/microsoft/vscode/issues/115945
So once we do the refactoring we should just make sure that this issue still works fine.

@roblourens assigning to you and September, if you do not have time do let me know and I can also look into fixing this. Joh's suggestion for a fix is to use when clauses that register items conditionally via settings values, [for example]( https://github.com/microsoft/vscode/blob/74a7062f7412fb8a465b662495e35f35d85163d0/src/vs/workbench/contrib/notebook/browser/view/cellParts/cellEditorOptions.ts#L131).

Potential fix would change how we listen to debug toolbar menu changes https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L129 and make sure that items are present in both places with orthogonal when claues.

**Comment by jrieken** [comment]
This is now a [MicrotaskEmitter](https://github.com/microsoft/vscode/blob/f8feede2aeb45096d9e7ade97a138327cbb40372/src/vs/platform/actions/common/actions.ts#L300) and therefore not so severe anymore. The event is only fired a handful of times now. 

I'm closing this issue again. Feel free to re-open if you want to improve this still
