### ISSUE TITLE
Machine-overridable setting values not read on non-default profiles

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#159592]
On a non-default profile, settings like `emmet.extensionsPath`, which are machine-overridable, do not have their value read properly by the configurationService even when the user specifies the value in the current profile setting.json.

**Comment by sandy081** [comment]
It seems to work now. I see the profile specific value being shown in the UI.

**Comment by rzhao271** [comment]
It still doesn't seem to work. I have a small extension that inspects the setting. 
When I run the command, it inspects the `emmet.extensionsPath` setting, and it doesn't pick up the profile setting there. I'll see if I can upload the test extension soon.
![Inspect demo](https://user-images.githubusercontent.com/7199958/204923324-94ceb548-bf76-47d8-954c-239628b8885e.png)

**Comment by sandy081** [comment]
I tried this with my sample extension (following) and it works as expected for me

```ts
export async function activate(context: vscode.ExtensionContext) {
    vscode.commands.registerCommand('test.helloWorld', () => {
        console.log(`${vscode.workspace.getConfiguration().inspect('emmet.extensionsPath')?.globalValue}`);
    })
}
```

Hence closing this. Please reopen it with the reproducible steps. Thanks
