### ISSUE TITLE
Settings-JSON: Support rendering line breaks with markdownDescription

### ISSUE THREAD

**Issue by maroony** [microsoft/vscode#159526]
When using `description` in `package.json` it is possible to get a rendered text with new lines:

```json
"description": "foo\nbar"
```

At the moment something similar is not possible when using `markdownDescription`.

**Comment by aeschli** [comment]
In markdown you need to add `<br` to force a new line. You need to do the same in `markdownDescription`

**Comment by maroony** [comment]
This doesn't work:

```json
"markdownDescription": "foo<br>bar",
```

Can you please give me a fully working example?

**Comment by aeschli** [comment]
Look like we filter all html tags.
@rzhao271 Is there a way to get paragraphs?

**Comment by rzhao271** [comment]
The markdownDescription seems to be rendered at https://github.com/microsoft/vscode/blob/2818ed07ba64c0c1287b276a5a1e62300d683936/src/vs/workbench/contrib/preferences/browser/settingsTree.ts#L973. @mjbvz is there an option that can be passed in to get line breaks rendered?

**Comment by rzhao271** [comment]
What a journey.
I realized that I can enable GitHub-flavoured markdown (GFM) line breaks in `markedOptions`, and that allows linebreaks with `\n`.
However, while reading more about what exactly GFM was, I found an even easier way to get paragraphs, and that is to use `\n\n`.

**Comment by rzhao271** [comment]
Closing issue as resolved.
