### ISSUE TITLE
Doesn't seem to automatically find index.d.ts for imports of depth 2 (or more)

### ISSUE THREAD

**Issue by shiptoncraig** [Microsoft/vscode#15951]
- VSCode Version: 1.7.2
- OS Version: Windows 8

Steps to Reproduce:

1. Import something from node_modules/<module>/<folder 1>/<folder 2> within a file, e.g. 'import { inject, TestBed }  from "@angular/core/testing"'.
2. VSCode keeps saying cannot find module, yet executing the transpiled source works as expected.

Can resolve it if I explicitly specify index.d.ts:

'import { inject, TestBed }  from "@angular/core/testing/index".

I'm also using node moduleResolution and every other import works fine.

**Comment by waderyan** [comment]
Can you share your workspace?

**Comment by mjbvz** [comment]
I see this work properly now. 

![screen shot 2017-01-19 at 4 36 56 pm](https://cloud.githubusercontent.com/assets/12821956/22131081/8263492c-de65-11e6-99d7-ccd312759b7a.png)

@shiptoncraig If you are still running into this, please provide some additional info about your project so we can investigate. 

Thanks
