### ISSUE TITLE
Codespace Issue

### ISSUE THREAD

**Issue by jj931** [microsoft/vscode#159591]
Hi, I was working in my codespace yesterday when I was prompted to do an update, so I did.  Something must have gone wrong - I'm not sure how to fix or backout whatever happened.  I am getting a dialog box that states  "This codespace is currently running in recovery mode due to a container error.  Review the creation logs, update your devcontainer configuration as needed, and run the "rebuild Container" command to retry."  I don't know how to do any of this.  I'm working in this space for an intro class, so this is all new to me.  Likely its an easy fix - would appreciate your help!  Thank you.

<img width="491" alt="image" src="https://user-images.githubusercontent.com/109712681/187498764-afbc820a-abc3-4798-b21b-4d11cac39080.png">

Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by chrmarti** [comment]
Sorry for the delay, please report this issue at https://github.com/community/community/discussions/categories/codespaces. Thanks.
