### ISSUE TITLE
"The window is not responding" should disappear when the condition is not met anymore

### ISSUE THREAD

**Issue by debuglevel** [microsoft/vscode#159540]
This window should disappear as soon as vscode respondes again.

![image](https://user-images.githubusercontent.com/2401265/187405768-c2447a42-7277-4215-bae2-d933b6e7e68e.png)

**Comment by Tyriar** [comment]
This is pretty old, please report with [more info](https://github.com/microsoft/vscode/wiki/Native-Crash-Issues) if you see it again
