### ISSUE TITLE
the new merge conflict resolution interface is bad

### ISSUE THREAD

**Issue by lmisto** [microsoft/vscode#159516]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.

**Comment by NewEraCracker** [comment]
Google it a bit and you'd have found this: https://github.com/microsoft/vscode/issues/156608#issuecomment-1208700989

Some known issues with this new "feature" apparently.

My two cents.

PS: Less strong words, this tool is 100% free - as in you are not oblidged to pay anything to anyone - AFAIK, so it comes with the usual as-is no-warranties legalese.
