### ISSUE TITLE
A UI Problem

### ISSUE THREAD

**Issue by GhostKnows** [microsoft/vscode#159538]
Type: <b>Bug</b>

1. Run vs code.
2. click any bottom that will make the layout change.
3. slide the mouse away.

Then you can see there is the shadow remained  on the interface.Sometimes the area that is covered by the shadow also lead to a wrong colour column.

My computer is definitely well.Any other app has no such problem.

I have changed the theme and reinstalled VS Code but still found the problem.

![屏幕截图 2022-08-30 150206](https://user-images.githubusercontent.com/59389051/187380812-5f2ade8e-1691-4878-b9ae-17153937b667.png)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (8.05GB free)|
|Process Argv|--crash-reporter-id f7c9d1bb-ea3c-4662-aa8c-e2b63982a8b5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.70.8170916

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30542925
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by IllusionMH** [comment]
/needsMoreInfo

Is it reproducible if you disable GPU acceleration?
You can do that with `--disable-gpu` CLI flag or as permanent launch setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

/assign deepak1556 -mjbvz

**Comment by GhostKnows** [comment]
> /needsMoreInfo
> 
> Is it reproducible if you disable GPU acceleration? You can do that with `--disable-gpu` CLI flag or as permanent launch setting https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
> 
> /assign deepak1556 -mjbvz

Thanks. It works perfectly when disabling GPU acclecrayion!
