### ISSUE TITLE
Terminal always shows at the right side; VScode ignores settings.

### ISSUE THREAD

**Issue by qodroi** [microsoft/vscode#159585]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.70.2
- OS Version: Ubuntu 20.04

There aren't really any steps to reproduce. This began to occur since I moved my Terminal to the right side of my workspace, and since than it is _always_ opened there, even when the **Workbench -> Panel: Default Location** is set to **bottom**. What I've tried so far is to drag it back to bottom, reset the default location option, and obviously relaunch VSCode.

This has been like for a few months but didn't really bother me, but now it does. I repeat, no matter what I do, when I open a new terminal from the menu via **Terminal->New Terminal** VSCode always open it on the right side.

![Panel Settings](https://user-images.githubusercontent.com/51533978/187492108-5c861320-095a-4082-8118-01de806f6d42.png)
Panel Settings.

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by qodroi** [comment]
> Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues. /label info-needed terminal

Sorry but I don't know how a GIF could help, I described the issue. Whenever I open a new Terminal via the menu ( Terminal->New Terminal (Ctrl+Shift+`) ), the terminal appears on the right side instead of the bottom. It should appear on bottom because my terminal's default location setting is set to bottom.

**Comment by sosafe-merlin-scheurer** [comment]
@qodroi is your terminal in a window that shows a list of icons as tab names?

If yes, then you need to right click on every single one of them and click "reset postition".
After that you end up with an empty window, which you can close.
If you know open a new terminal it will show in a panel with names as tab names and you can re-position it again.
