### ISSUE TITLE
text editor insert snippet API

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15952]
Since we have now a `SnippetString` it would also be beneficial to allow snippets to inserted into the editor. Similar to `TextEditor.edit` we should have something that allows inserting a snippet string and bringing the editor into snippet mode.

**Comment by joelday** [comment]
https://github.com/joelday/vscode/commit/38a3a1a23930605643ac186b5ca062ca5d881252

I have no idea if this works and I hit a bunch of walls trying to test it. How far off am I?

**Comment by jrieken** [comment]
looking not too bad. keep going

**Comment by joelday** [comment]
@jrieken Thanks! Is there a workflow you would recommend for running/debugging/testing?

**Comment by jchannon** [comment]
Is #17628 the way to make this happen?

**Comment by jrieken** [comment]
yeah. #17628 is already in master and will be part of our Jan release

**Comment by joelday** [comment]
So excited to use it in docthis!
