### ISSUE TITLE
Hardcoded number of viewlets in CSS

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#15969]
https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/explorers/media/treeExplorer.contribution.css#L16

For one, this contribution shouldn't reach out to the activity bar like that at all. Second, why is that `nth-child(n+6)` in there? It hardcodes the number of non-contributed viewlets we currently have.

**Comment by bpasero** [comment]
This should probably be revisited when we implement contributed viewlets to show up below a separator in the sidebar. Still needs UX discussion if we want to go with that approach but looks like  it.

**Comment by bpasero** [comment]
I have removed this CSS hack and verified that the contributed icon looks good as long as it follows our spec.

@octref I suggest you update the custom explorer examples icons.

**Comment by octref** [comment]
@bpasero Sure. Wondering where is the spec you are referring to?

**Comment by bpasero** [comment]
I just copied one of the existing icons we had and tried. They seem to have a white background fill.
