### ISSUE TITLE
Zombie extension host

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#15962]
Write an extension that does `while(true);` and run it. Restart VS Code and notice you have zombie extension host process running forever on your system.

**Comment by jrieken** [comment]
fyi @dbaeumer

**Comment by dbaeumer** [comment]
@alexandrudima we discussed that when being in Redmond. We need a watch dog which monitors detached processes.

**Comment by alexandrudima** [comment]
Let's continue tracking in #26445
