### ISSUE TITLE
Improve issue templates so extensions get less "We have written the needed data into your clipboard. Please paste" issues

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#159688]
I'm an extension author and frequently have issues open with generic titles ("Extension issue") and not enough information to do anything with (usually ending "⚠️ We have written the needed data into your clipboard. Please paste! ⚠️" or a similar message about attaching a file) ([example](https://github.com/Dart-Code/Dart-Code/issues/4135)). I see VS Code gets many issues the same, and has a bot to close them.

It seems unfortunate that users are taking time to come to GitHub and submit issues, but they often end up closed due to not having enough information. It's not clear to me what prompts users to create these issues, but perhaps there are ways that they could be improved.

For example:

- populating the title with "Extension issue" makes it easy for a user to submit without entering a single word of text about the problem. If the field was left blank, they would not be able to submit the form without typing something that might give some indication of what prompted them to file the issue.
- perhaps GitHub could detect this string (or some variation of) and give the user a nudge that maybe they have forgotten to paste/attach something? (I know that's a request for GitHub, but they don't have a public issue tracker and perhaps this team has contacts there 🙂)
- include some summary of the data in the clipboard in the originally message (I've no idea what it is, because I don't know if anybody has ever successfully pasted it).. querystrings can be fairly long these days even if the whole message can't be included

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/pull/159491 may also help reduce these.

**Comment by DanTup** [comment]
Ah yes, that might help too. Out of interest, do you know what is prompting users to create these, and what sort of information is included in the clipboard? I'm not sure I've ever had anyone come back to me with the data (likely because their clipboard has been reused by the time they see my response) so I've zero ideas about what might be happening.

**Comment by TylerLeonhardt** [comment]
@DanTup these are created by the Issue Reporter:
![image](https://user-images.githubusercontent.com/2644648/187743971-54dacfb8-32e8-459a-bc6b-cdeb9294c0a8.png)
![image](https://user-images.githubusercontent.com/2644648/187744181-d3cdd5bb-710b-442a-8e97-eb5c7d5498d5.png)

The PR @gjsjohnmurray linked upped the max number of characters so we should see a lot less of those issues.

That said, it is suspicious that they all have the title "Extension Issue"... makes me wonder if someone wrote a script of some kind to spam issues.

**Comment by DanTup** [comment]
Hmm, that is odd - in your screenshot both the title and body are mandatory, but I get "Extension issue" so often from different peope, I'd be surprised if they were all typing it: 

![Screenshot 2022-08-31 at 18 46 11](https://user-images.githubusercontent.com/1078012/187745138-95f69380-7d54-4d4f-aefa-5b43b7bc7cbb.png)

**Comment by DanTup** [comment]
@TylerLeonhardt coming from here maybe?

https://github.com/microsoft/vscode/blob/dce493cb6e36346ef2714e82c42ce14fc461b15c/src/vs/workbench/contrib/extensions/electron-sandbox/reportExtensionIssueAction.ts#L67

**Comment by TylerLeonhardt** [comment]
Nice find. Looks like that gets run from this page:
![image](https://user-images.githubusercontent.com/2644648/187746330-2cde0cfa-ee23-4d2f-9d68-846323f20817.png)

Looks like a relic of the past... let me see what I can do here

**Comment by TylerLeonhardt** [comment]
Ok I have a PR out that will route that through the issue reporter instead.

**Comment by DanTup** [comment]
@TylerLeonhardt neat, thanks!

**Comment by gjsjohnmurray** [comment]
@TylerLeonhardt this code does similar:

https://github.com/microsoft/vscode/blob/6815774edeb1f5649cdf8e8713a04940acb88203/src/vs/workbench/contrib/performance/electron-sandbox/startupProfiler.ts#L114-L136

#159736 is a recent example of an issue created that way but lacking the clipboard-pasted info.

**Comment by TylerLeonhardt** [comment]
Verification steps:

* Open Running Extensions
* Right click on an extension and click report issue

The Issue reporter should open and not github.com
