### ISSUE TITLE
Default build tasks stack up after window reloads

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159640]
<img width="423" alt="image" src="https://user-images.githubusercontent.com/900690/187608014-4f7706af-d426-4002-8587-28b13486ed1b.png">

**Comment by meganrogge** [comment]
I am unable to repro this - could you pls provide the steps that you take?

**Comment by bpasero** [comment]
I have not found a pattern so far, might be timing related. It is not happening everytime I reload the window...

However, one thing to keep in mind is that I often use `workbench.action.tasks.runTask` and not `workbench.action.tasks.build`. That command kills the build task and relaunches it:

```
{
    "key": "cmd+shift+alt+b",
    "command": "workbench.action.tasks.runTask",
    "args": "Restart VS Code - Build"
}
```

So that may well be related to the issue.

**Comment by meganrogge** [comment]
Likely same root cause as https://github.com/microsoft/vscode/issues/160404

**Comment by meganrogge** [comment]
Thanks for the idea, but seems unrelated to that command as @joaomoreno has reproduced this with `workbench.action.tasks.build`
