### ISSUE TITLE
Run and Debug view keyboard shortcut - change default selected element 

### ISSUE THREAD

**Issue by AlexTelon** [microsoft/vscode#159672]
![image](https://user-images.githubusercontent.com/5202914/187693670-8c14d164-5ad9-4bfd-9b7d-53557fcd4bef.png)

When using the default `Ctrl + Shift + D` to open the "Run and Debug" view then the default element selected is the play icon. Using arrows you can now navigate the elements in this view and I'm suggesting that we move the default element to "one to the right" for ease of use.

**So today:**

`Ctrl + Shift + D` and then  `Enter` is same as `F5`
`Ctrl + Shift + D` and `Arrow Right` then `Enter` opens up the drop-down menu.
`Ctrl + Shift + D` and `Arrow Right` then `Arrow up/down` allows for changing the selected run option.

**My suggestion:**

**Make the option menu selected by default.** Such that
`Ctrl + Shift + D` and then  `Enter` is opens up the drop-down menu.
`Ctrl + Shift + D` then `Arrow up/down` allows for changing the selected run option.

**Why?**

Looking at some of the other views like Extensions and Search the default selected element is the most useful one, such that you can type directly to search.

But selecting the play button in debug view does not "feel" like the most useful thing to select. Again because everyone already uses `F5` right?

**Drawbacks or other solutions**
I know people might be used to current behavior and as such it could be annoying to change.
I tried to search around to see if there was already an option to get a keyboard shortcut for this directly, but could not find it. That would be an alternative approach that does not change any existing behavior.

**Comment by roblourens** [comment]
I don't really want to focus the second item in the toolbar instead of the first. I recommend setting a keybinding for the command "Select and start debugging". I use cmd+F5
