### ISSUE TITLE
Wrong relative line numbers when using Word Wrap 

### ISSUE THREAD

**Issue by gruvw** [microsoft/vscode#159683]
Does this issue occur when all extensions are disabled?: Yes
VS Code Version: 1.70.2

### Steps to Reproduce:

1. Enable Word Wrap
2. Set Word Wrap Column to 10 (for example)
3. Write enough text to notice a line wrap
4. The line number on the line where the cursor stands is wrongly numbered

### Actual behavior:
![image](https://user-images.githubusercontent.com/63407038/187711368-8e89f804-a346-4c3c-b2ae-f3c2563ace52.png)

Issues:
* Here it looks like we are not on the same line as the first Bs, even though we are.
* It looks like the file currently has 5 lines, even though it only has 4 (with different letters on each line).
* In longer files, it is not possible to differentiate a situation where we have a line wrap from one where there is a line break. (As the only way to differentiate would be to count the lines from the top of the file and see if it matches the number displayed on the line where the cursor stands.)
* For all the users of some kind of Vim emulation: doing line number relative operations (like `2j`) from a wrapped line gets us to unexpected results if they were based on displayed relative line numbers

It gets even weirder and inconsistent when the line breaks more than once:
![image](https://user-images.githubusercontent.com/63407038/187718381-6ee07f0d-3dc3-4906-a045-d2a32df97f59.png)

### Expected behavior

Here are two potential solutions to this issue:

* Option1:
![option1](https://user-images.githubusercontent.com/63407038/187715628-66849236-f717-47ea-9f57-29f00d3972a9.png)

* Option 2:
![option2](https://user-images.githubusercontent.com/63407038/187717546-b6c2ee2d-06b4-4733-8c45-b9f73ce891a8.png)

Personally, I prefer option 2 as we still have an indication that we are on the bottom (or wrapped part) of the current line.

**Comment by ArturoDent** [comment]
I can't replicate this in Insiders or Stable v1.71 (released today - you might re-test it in v1.71).  I see your "Option 1" correctly no matter how many wraps there are.

Do you see this in all file types?   No chance that an extension is getting in the way (I see that you say they are all disabled-including VIM?)?

**Comment by gruvw** [comment]
Ok so apparently this issue has been fixed in v1.71.0 so that's good to know, thank you.

However, I cannot find any other issue mentioning this bug and I didn't find anything about it in the release note either...
