### ISSUE TITLE
Copy line down keybindings doesn't work

### ISSUE THREAD

**Issue by tomtobac** [Microsoft/vscode#15967]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.3|
|vscode-icontheme-nomo-dark|be5invis|1.2.0|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Angular2|johnpapa|1.0.2|
|Theme-MaterialKit|ms-vscode|0.1.1|
|autoimport|steoates|1.2.2|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Open IDE, selecte line
2. Press `Alt`+ `Shift` + `Alt` + `down`

**Comment by alexandrudima** [comment]
I think the default on Linux for copying line down is <kbd>ctrl</kbd>+<kbd>alt</kbd>+<kbd>shift</kbd>+<kbd>down</kbd>. Varying from distribution to distribution, sometimes the window manager "steals" these key combinations. It is impossible for us to have a default that works on all the linux distributions. 

Can you please check if we even receive this keybinding? Go to Preferences > Keyboard shortcuts and use the Define Keybinding and check if we receive this key combination. Here I am doing it on Windows:

![copy-lines-down](https://cloud.githubusercontent.com/assets/5047891/20747980/9f11913c-b6ec-11e6-9924-1e8f258dbca0.gif)

**Comment by tomtobac** [comment]
Hi Alex, I try as you said and it don't get the <kbd>up</kbd> & <kbd>down</kbd> key with <kbd>ctrl</kbd> + <kbd>alt</kbd>+ <kbd>shift</kbd> , just <kbd>left</kbd> & <kbd>right</kbd>. 
But it works with <kbd>ctrl</kbd> + <kbd>alt</kbd> + <kbd>down/up</kbd>
I don't know why, but in older version I think it worked.

Thanks!

**Comment by alexandrudima** [comment]
Thanks for trying it out, this confirms that the OS or some other software is eating up these key combinations. I suggest that you define new keybindings for these actions. e.g.

```
{ "key": "shift+alt+down",        "command": "editor.action.copyLinesDownAction",
                                     "when": "editorTextFocus && !editorReadonly" },
```

The keybindings could be captured by an OS update, some new installed or updated software, etc.

Given we're not getting them, there is nothing we can do on our side, short of changing the defaults, which is also difficult because there are no more modifier + arrow keys combinations left.

**Comment by alandawkins** [comment]
How about use vim's J/K for some down/up, ctrl+shift+alt+J and ctrl+shift+alt+K, this maybe a reasonable chice. : )
