### ISSUE TITLE
Recommend changing ignoreTrimWhitespace default to false

### ISSUE THREAD

**Issue by pbrianmackey** [Microsoft/vscode#15968]
I recommend modifying VS code to default to diffEditor.ignoreTrimWhitespace = false to maintain parity with git diff.  On my team whitespace is a big part of the code review and beautification process.  Not being able to see the whitespace in a diff lead me down a rabbit hole.  That's not a good place to be for a new user.

More details on my initial experiences with this:  http://stackoverflow.com/questions/30140595/show-whitespace-characters-in-visual-studio-code/40744352#40744352

**Comment by chrisdias** [comment]
@pbrianmackey sorry about the settings confusion, we're working on this [see here](https://github.com/Microsoft/vscode/issues/15162).

Assigning to @alexandrudima for default setting question...

**Comment by alexandrudima** [comment]
Most diff editors show a prominent toggle in the form of an icon that switches between ignoring trim whitespace or not. IMHO, we need to add such a UI element.

**Comment by AmeliaBR** [comment]
+1 to an "ignore whitespace" toggle in the interface.

This issue has become even more important with the new partial-staging feature, where you can stage and commit individual changes from the editor.

Currently, if you make a change that also affects whitespace of other lines (like adding a `try` block around code, then indenting the code inside the block without changing it), the indentation change doesn't get included if you stage the new lines.   There isn't currently any way to include it other than changing your configs (or committing the entire file).

**Comment by iamdevlinph** [comment]
As of 
```
Version: 1.26.1
Commit: 493869ee8e8a846b0855873886fc79d480d342de
Date: 2018-08-16T18:38:57.434Z
Electron: 2.0.5
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```
The setting `"diffEditor.ignoreTrimWhitespace"` is still default to true. 

![image](https://user-images.githubusercontent.com/19337229/44301003-c69ac180-a342-11e8-941a-9401071e96f1.png)

**Comment by alexandrudima** [comment]
We have a prominent action in the diff editor to toggle the diff algorithm to ignore trim whitespace or not. 

There are no plans to change the default.

![15968](https://user-images.githubusercontent.com/5047891/45916596-f1f45d00-be68-11e8-9e3b-593c620be295.gif)
