### ISSUE TITLE
Extensions for plaintext documents

### ISSUE THREAD

**Issue by DPattee** [microsoft/vscode#159605]
While trying to migrate from Atom to VS Code, I'm finding that many(all?) extensions do not work against a standard plaintext document.

Language-specific linters I would not expect to function, but 'basic' things like indention coloring, matched parenthesis/grouping colorizers, excess spaces between the last character of a line and the newline, and some other 'just text parsing, no deep language understanding' type things should be able to work. 

The current workaround is to switch all my notes to markdown, but that activates other language-specific linters that want to enforce good-markdown rules on freeform-text documents inappropriately

**Comment by aeschli** [comment]
There's a simple language configuration for the `plaintext` language that contains the brackets. So I don't know why the bracket matching doesn't work. Assigning to @hediet.
@DPattee Can you add screenshots for the other features you think should work?
