### ISSUE TITLE
Workspace Profile

### ISSUE THREAD

**Issue by gmcoates101** [microsoft/vscode#159643]
When I work I am sometimes using AWS and other time Azure. Using VSCode to manage a work with these platforms is excellent however when I am working with Azure I still have a large number of AWS plugins available that at this time are not required.  They are in the way, using resources etc.

What I would like is that I can create a profile of some kind and give them a name, e.g. AWS or Azure in this example. When I then select the AWS the only plugins that are enabled are the ones I have selected to be enabled in that profile, the others are disabled.  This way we could create profiles with plugins/themes etc that give the tool the exit requirement for the current job.  You could kind of see this in a similar way that python visual envs are used.

Some plugins in this situation would be cross-profile, code-lens for example Git, those things that are used on all dev jobs regardless of platforms/languages.

**Comment by gjsjohnmurray** [comment]
See https://code.visualstudio.com/updates/v1_70#_settings-profiles for a new opt-in feature that may help you.

**Comment by gmcoates101** [comment]
@gjsjohnmurray that really does look what I was thinking about, I will give it a try and hope that gets to GA one day.

**Comment by gjsjohnmurray** [comment]
Improvements to it are in 1.71 which is likely to ship tomorrow.
