### ISSUE TITLE
Toolchain path located in .bashrc shown in prompt text

### ISSUE THREAD

**Issue by StjepanBM1** [microsoft/vscode#159645]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.70.2
- OS Version: Linux x64 5.15.0-46-generic snap (Ubuntu MATE 22.04.1 LTS x86_64)

Steps to Reproduce:

1. Create a cross-compiler (from OS Dev Wiki - https://wiki.osdev.org/GCC_Cross-Compiler)
2. Add the needed exports into `.bashrc`
3. Reload BASH
4. Load VS Code terminal

Problem :
![image](https://user-images.githubusercontent.com/94230991/187618916-52798942-9756-4026-abc7-8119d774e98b.png)
Expected behaviour :
![image](https://user-images.githubusercontent.com/94230991/187620056-199f8235-a070-4679-86b6-af7b986f6338.png)

**Comment by Andrej123456789** [comment]
Actually this happens only when using [nanobyte's tutorial](https://www.youtube.com/watch?v=TgIdFVOV_0U) as far as I know so ask him and then if you don't find anything useful come back here so Microsoft can see that they have to fix issues which they don't know how to fix, no offense though, you fixed a lot of issues for open source projects but Windows is still buggy, who puts shell and file explorer in same process...

**Comment by StjepanBM1** [comment]
@Andrej123456789 I followed OS Dev's Wiki tutorial.

**Comment by Andrej123456789** [comment]
Anyway, Windows need a serious fix though

**Comment by Tyriar** [comment]
This doesn't appear to be anything to do with VS Code? bash is in charge of what text gets displayed in the terminal.

**Comment by StjepanBM1** [comment]
Well how come my standard non-VSCode terminal shows up normally?
![image](https://user-images.githubusercontent.com/94230991/188078873-ee4644ac-2fcd-4d0a-b787-d8ec4961aa2a.png)

**Comment by StjepanBM1** [comment]
1/10 service support.

**Comment by Andrej123456789** [comment]
![image](https://user-images.githubusercontent.com/83548580/188082201-a47db0c6-1957-419e-b63f-b93e69900316.png)
This doesn't happens with zsh btw

**Comment by Tyriar** [comment]
@StjepanBM1 probably because of the environment the shell launches with, clearly VS Code doesn't hardcode anything about your toolchain folder though.

To be clear this is not a support forum but a place to report bugs and request features where you interact with the developers of the product, not support staff. I do not believe this is a bug in VS Code but an issue with the tutorial you're following. I'm happy to be proven wrong though.

**Comment by StjepanBM1** [comment]
@Tyriar well how come the normal terminal works just fine, but VS Code one has this bug. & I do think that someone would've reported this to the OS Dev Wiki.

**Comment by StjepanBM1** [comment]
Considering I used the [Wiki OS Dev Cross-Compiler](https://wiki.osdev.org/GCC_Cross-Compiler) for many other target platforms in other folders the same thing happens.

**Comment by StjepanBM1** [comment]
And in NeoVim exstension that launches BASH to run the terminal dosen't have this issue.

**Comment by StjepanBM1** [comment]
So this is not truly a `.bashrc` issue but a VS Code one. And maybe if you read the [Cross-compiler tutorial](https://wiki.osdev.org/GCC_Cross-Compiler) you would probably know that this shouldn't happen.

**Comment by Andrej123456789** [comment]
> @StjepanBM1 probably because of the environment the shell launches with, clearly VS Code doesn't hardcode anything about your toolchain folder though.
> 
> To be clear this is not a support forum but a place to report bugs and request features where you interact with the developers of the product, not support staff. I do not believe this is a bug in VS Code but an issue with the tutorial you're following. I'm happy to be proven wrong though.

I also don't think it is issue with tutorial since in other terminal emulators works nice. Just check code and try find a bug since you are vs code developer and i am not going to learn new (shit) language to fix vscode

**Comment by Tyriar** [comment]
What's the change you made to .bashrc and where does `Toolchain/i486-elf` appear in your init scripts?

Does the problem reproduce in the .deb package (not the snap)?

**Comment by Andrej123456789** [comment]
It happens to me also on Arch Linux

**Comment by StjepanBM1** [comment]
> What's the change you made to .bashrc and where does `Toolchain/i486-elf` appear in your init scripts?
> 
> Does the problem reproduce in the .deb package (not the snap)?

This is what I added :
```sh
# Compiler stuff

export PREFIX="$HOME/Toolchain/sparc-elf"
export TARGET=sparc-elf
export PATH="$PREFIX/bin:$PATH"
# export TOOLCHAIN="$HOME/Toolchain/sparc-elf"
```
Does the problem reproduce in the .deb package (not the snap)? 
Yes it does. (Tested on Debian, ArchLinux, Ubuntu, Fedora)

**Comment by StjepanBM1** [comment]
I just changed the cross-compiler to target Sparc Stations.

**Comment by Tyriar** [comment]
If you change it to this does it work?

```sh
if [ -z "$PREFIX" ]; then
  export PREFIX="$HOME/Toolchain/sparc-elf"
  export TARGET=sparc-elf
  export PATH="$PREFIX/bin:$PATH"
fi
```

Or setting `"terminal.integrated.inheritEnv": false`?

**Comment by Andrej123456789** [comment]
Setting `"terminal.integrated.inheritEnv": false` didn't worked nor first solution

**Comment by Andrej123456789** [comment]
I tried both at same time too

**Comment by Andrej123456789** [comment]
VS Code terminal:
```
SHELL=/bin/bash
SESSION_MANAGER=local/archlinux:@/tmp/.ICE-unix/902,unix/archlinux:/tmp/.ICE-unix/902
COLORTERM=truecolor
XDG_CONFIG_DIRS=/home/vangu/.config/kdedefaults:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
HISTCONTROL=ignoredups
TERM_PROGRAM_VERSION=1.70.0
APPLICATION_INSIGHTS_NO_DIAGNOSTIC_CHANNEL=true
PREFIX=/home/vangu/Toolchain/i686-elf
DESKTOP_SESSION=plasma
GTK_RC_FILES=/etc/gtk/gtkrc:/home/vangu/.gtkrc:/home/vangu/.config/gtkrc
NO_AT_BRIDGE=1
XCURSOR_SIZE=24
GTK_MODULES=canberra-gtk-module:appmenu-gtk-module
XDG_SEAT=seat0
PWD=/home/vangu/Documents/GVPaint
XDG_SESSION_DESKTOP=KDE
LOGNAME=vangu
XDG_SESSION_TYPE=x11
SYSTEMD_EXEC_PID=956
XAUTHORITY=/home/vangu/.Xauthority
VSCODE_GIT_ASKPASS_NODE=/opt/visual-studio-code/code
MOTD_SHOWN=pam
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/vangu/.gtkrc-2.0:/home/vangu/.config/gtkrc-2.0
HOME=/home/vangu
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=KDE
GIT_ASKPASS=/opt/visual-studio-code/resources/app/extensions/git/dist/askpass.sh
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
INVOCATION_ID=4125f95b444247efbb15244e9be2af26
MANAGERPID=800
CHROME_DESKTOP=code-url-handler.desktop
KDE_SESSION_UID=1000
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XDG_SESSION_CLASS=user
TERM=xterm-256color
TOOLCHAIN=/home/vangu/Toolchain/i686-elf
USER=vangu
LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:
VSCODE_GIT_IPC_HANDLE=/run/user/1000/vscode-git-c7e513105a.sock
KDE_SESSION_VERSION=5
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
DISPLAY=:0
SHLVL=2
XDG_VTNR=1
UBUNTU_MENUPROXY=1
XDG_SESSION_ID=2
LD_LIBRARY_PATH=:/usr/lib/mpc/lib/
XDG_RUNTIME_DIR=/run/user/1000
VSCODE_GIT_ASKPASS_MAIN=/opt/visual-studio-code/resources/app/extensions/git/dist/askpass-main.js
QT_AUTO_SCREEN_SCALE_FACTOR=0
JOURNAL_STREAM=8:16923
XCURSOR_THEME=breeze_cursors
XDG_DATA_DIRS=/home/vangu/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
GDK_BACKEND=x11
KDE_FULL_SESSION=true
PATH=/home/vangu/Toolchain/i686-elf/bin:/home/vangu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/x86_64/elfgcc/bin
ORIGINAL_XDG_CURRENT_DESKTOP=KDE
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
KDE_APPLICATIONS_AS_SCOPE=1
MAIL=/var/spool/mail/vangu
TARGET=i686-elf
TERM_PROGRAM=vscode
_=/usr/bin/env
```

Konsole (KDE default terminal emulator):
```
SHELL=/bin/bash
WINDOWID=125829127
COLORTERM=truecolor
XDG_CONFIG_DIRS=/home/vangu/.config/kdedefaults:/etc/xdg
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
HISTCONTROL=ignoredups
LANGUAGE=
PREFIX=/home/vangu/Toolchain/i686-elf
SHELL_SESSION_ID=23495b18016d41beaf0370debe0de46e
DESKTOP_SESSION=plasma
GTK_RC_FILES=/etc/gtk/gtkrc:/home/vangu/.gtkrc:/home/vangu/.config/gtkrc
XCURSOR_SIZE=24
GTK_MODULES=canberra-gtk-module:appmenu-gtk-module
XDG_SEAT=seat0
PWD=/home/vangu/Documents/GVPaint
XDG_SESSION_DESKTOP=KDE
LOGNAME=vangu
XDG_SESSION_TYPE=x11
SYSTEMD_EXEC_PID=917
XAUTHORITY=/home/vangu/.Xauthority
MOTD_SHOWN=pam
GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:/home/vangu/.gtkrc-2.0:/home/vangu/.config/gtkrc-2.0
HOME=/home/vangu
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=KDE
KONSOLE_DBUS_SERVICE=:1.143
KONSOLE_DBUS_SESSION=/Sessions/3
PROFILEHOME=
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
INVOCATION_ID=a8290e5d84ec44fc9435ea68c1b09999
KONSOLE_VERSION=220800
MANAGERPID=800
KDE_SESSION_UID=1000
XDG_SESSION_CLASS=user
TERM=xterm-256color
TOOLCHAIN=/home/vangu/Toolchain/i686-elf
USER=vangu
LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:
COLORFGBG=15;0
KDE_SESSION_VERSION=5
PAM_KWALLET5_LOGIN=/run/user/1000/kwallet5.socket
DISPLAY=:0
SHLVL=1
XDG_VTNR=1
UBUNTU_MENUPROXY=1
XDG_SESSION_ID=2
LD_LIBRARY_PATH=:/usr/lib/mpc/lib/
XDG_RUNTIME_DIR=/run/user/1000
QT_AUTO_SCREEN_SCALE_FACTOR=0
JOURNAL_STREAM=8:25970
XCURSOR_THEME=breeze_cursors
XDG_DATA_DIRS=/home/vangu/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
KDE_FULL_SESSION=true
PATH=/home/vangu/Toolchain/i686-elf/bin:/home/vangu/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/local/x86_64/elfgcc/bin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
KDE_APPLICATIONS_AS_SCOPE=1
MAIL=/var/spool/mail/vangu
TARGET=i686-elf
KONSOLE_DBUS_WINDOW=/Windows/1
_=/usr/bin/env
```

**Comment by Tyriar** [comment]
I don't see a `$PS1` variable on either side, do you use `PROMPT_FUNCTION` for you prompt? How is that defined?

**Comment by Andrej123456789** [comment]
```bash
PS1='[\u@\h \W]\$ '
 ```
fresh from .bashrc

**Comment by Tyriar** [comment]
Sorry I'm out of ideas. Basically the only thing that VS Code influences in bash is the cwd, environment, permissions and shell args (which are probably nothing). VS Code definitely does not print that string by itself, it's bash telling VS Code's terminal to print it. If you figure it out I'm curious to know as well.

**Comment by Andrej123456789** [comment]
Ok

**Comment by Tyriar** [comment]
The root cause of this was found by @CKeilbar 👏 https://github.com/microsoft/vscode/issues/160748

**Comment by Andrej123456789** [comment]
Good
