### ISSUE TITLE
Provide an API from `electron-main` to schedule work when window is busy starting up

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159650]
Today we schedule a large amount of work right after the `loadUrl` call for a `BrowserWindow` assuming that we can schedule work parallel to the window opening. But as I learned today, there is no guarantee that the `BrowserWindow` can do its business independent from the main process.

It is actually very likely that we do work and block the main process while the window wants something from the main process.

Ideally electron could provide an API or event that can signal us in the main process that now is a good time to work on something without impacting the loading of the window.

![Screenshot 2022-08-31 at 09 49 15](https://user-images.githubusercontent.com/900690/187623546-0dcd9d2d-3d60-475d-94e9-a3072904195a.png)

Refs: https://github.com/electron/electron/issues/35513

//cc @jrieken

**Comment by deepak1556** [comment]
Closing as not something I can work on anytime soon.
