### ISSUE TITLE
find/replace not triggering didChange

### ISSUE THREAD

**Issue by nicolasg-da** [Microsoft/vscode#15966]
- VSCode Version: 1.7.2
- OS Version: OS X 10.11.6

Steps to Reproduce:

1. open 3 files with the same string in it.
2. Search + replace for that string.
3. Language server protocol only fires a change event for one of the changed files.

  Same thing happens for a rename request.
  https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#rename-request 

What I expected:

a `textDocument/didChange` for every file that was changed.

**Comment by dbaeumer** [comment]
This will be fixed in the next version (3.x) of the Language Server protocol implementation for node (already fix in master here: https://github.com/Microsoft/vscode-languageserver-node)

**Comment by nicolasg-da** [comment]
@dbaeumer thanks for the answer

**Comment by nicolasg-da** [comment]
@dbaeumer 
we tried the same steps with version 3.0.1-alpha.3 (the newest one available five days ago and the newest one working without changing the protocol on our end) and we still had the same issues.

**Comment by dbaeumer** [comment]
@nicolasg-da actually there is still a problem. Was able to reproduce. Will address for the next LSP release.

**Comment by dbaeumer** [comment]
Fixed in vscode-languageclient@3.0.1-alpha.12

**Comment by nicolasg-da** [comment]
@dbaeumer thanks! :)
