### ISSUE TITLE
Disable all extensions and allow to enable selectively

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#159636]
I know there is alway an issue https://github.com/microsoft/vscode/issues/81950#issue-502557730. But it is locked. I want to inspect one extension issue, but I can't find a effective way to disable other extensions.

**Comment by tjx666** [comment]
I disable all extensions, and try to restore the extsnion by setting history. It seems the settings sync data restore also has issue. 

![image](https://user-images.githubusercontent.com/41773861/187586853-005e1c72-8380-47ff-ab97-95a9a8b2774c.png)

I click `Yes`, but doesn't work:

![image](https://user-images.githubusercontent.com/41773861/187586972-39044be6-0a49-40cc-81f2-4ef689e4565c.png)

**Comment by gjsjohnmurray** [comment]
Maybe try this approach:

1. Use "Save Workspace As..." from the File menu to create XYZ.code-workspace.
2. From Command Palette run `Extensions: Disable All Installed Extensions for this Workspace`.
3. On Extensions view look in the Disabled section for the extension you want to enable. Open its gearwheel menu and choose "Enable (Workspace)".

When you have finished your investigations you can close the workspace from the File menu, then optionally delete the XYZ.code-workspace file to tidy up.

**Comment by sandy081** [comment]
You can also use settings profiles feature for your scenario - https://code.visualstudio.com/updates/v1_70#_settings-profiles. Please note that this feature is enabled by default in latest insiders and thus you do not need the mentioned setting to enable.
