### ISSUE TITLE
Activating terminal links with only a single search result that exactly matches the file name matches should open it directly

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#159677]
In the xterm.js repo, ctrl+clicking the link `TypedArrayUtils.test.ts:10:5` currently results in:

![image](https://user-images.githubusercontent.com/2193314/187707133-474d89b6-8268-4a71-9d2a-c606b22c1947.png)

Since there is only a single match it should open the file instead of showing a fuzzy search. This is a more specific case of https://github.com/microsoft/vscode/issues/159676

This also happens with a link that's just the file name: `TypedArrayUtils.test.ts`

![image](https://user-images.githubusercontent.com/2193314/187707628-b9993e6a-056e-4810-a59e-27cefbe7a84f.png)

When reproducing this issue it's important that the file being searched for is _not_ in the root directory.

**Comment by fabriziotrenti** [comment]
> In the xterm.js repo, ctrl+clicking the link `TypedArrayUtils.test.ts:10:5` currently results in:
> 
> ![image](https://user-images.githubusercontent.com/2193314/187707133-474d89b6-8268-4a71-9d2a-c606b22c1947.png)
> 
> Since there is only a single match it should open the file instead of showing a fuzzy search. This is a more specific case of #159676
> 
> This also happens with a link that's just the file name: `TypedArrayUtils.test.ts`
> 
> ![image](https://user-images.githubusercontent.com/2193314/187707628-b9993e6a-056e-4810-a59e-27cefbe7a84f.png)
> 
> When reproducing this issue it's important that the file being searched for is _not_ in the root directory.

I'm experiencing exactly this situation except that in my case the file can be in the root directory, as shown here:
https://github.com/microsoft/vscode/issues/155532#issuecomment-1232951063
It doesn't matter if the file is in the root directory or has spaces in the name.

**Comment by Tyriar** [comment]
@fabriziotrenti I think the fix in https://github.com/microsoft/vscode/pull/159698 should cover your case

**Comment by fabriziotrenti** [comment]
> @fabriziotrenti I think the fix in #159698 should cover your case

Thanks @Tyriar 
So I suppose I have to wait for the fix to be released, right? Or do I have another way to test it? Thanks

**Comment by Tyriar** [comment]
@fabriziotrenti when it gets merged in it should be released in the insiders build which you could test there https://code.visualstudio.com/insiders. This issue will get the insiders-released label when it lands in insiders.
