### ISSUE TITLE
Tasks and commands integration from extensions

### ISSUE THREAD

**Issue by vadimcn** [Microsoft/vscode#1596]
There's a bunch of functionality in that is bound to tasks: the Ctrl-Shift-B shortcut, preLaunchTask in launch, etc.   On the other hand, language extensions cannot contribute tasks, only commands, and  as far as I can tell, there is no way to have a task invoke an internal VSCode command. 

It would be nice if a language extension could supply a default build task for the language, either directly, or as a command, which a task can invoke.

**Comment by bpasero** [comment]
@dbaeumer fyi

**Comment by evmar** [comment]
I'd like to better integrate http://www.bazel.io/ (the Google build system) and VSCode, and I think a hook like this would be the best way to do it.

**Comment by jrieken** [comment]
This actually landed with the June release: https://code.visualstudio.com/updates/v1_14#_new-task-api
