### ISSUE TITLE
Task reconnection status does not work for default build task

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159639]
![Recording 2022-08-31 at 08 20 47](https://user-images.githubusercontent.com/900690/187607780-a178b35c-201e-4827-83de-c20a57b98f90.gif)

I urge to selfhost on this for a bit. Status bar never shows the state for me, I think never has after window reload.

**Comment by meganrogge** [comment]
how often do you see this? I've tried a lot to repro and haven't seen it yet. 

If you see it often, could you pls turn on trace logging?

**Comment by bpasero** [comment]
@meganrogge here are my steps that should allow you to reproduce:
* run `code-insiders` from an empty fresh `--user-data-dir`
* open `vscode` folder
* hit `Cmd+Shift+B`
* notice the task bar showing 2 tasks and "Building..."
* reload the window
* notice the status bar not showing those entries

In your case, you likely have terminals panel visible, but I never have terminals visible typically.

**Comment by meganrogge** [comment]
Thanks @bpasero when you eventually do open the panel, do the statuses appear? I think I saw what you describe but upon opening the panel, the statuses appeared

**Comment by meganrogge** [comment]
I can repro the statuses not appearing until I open the panel

**Comment by meganrogge** [comment]
that's because the tasks aren't reconnected to until the terminals are restored, which doesn't happen when the panel is hidden

https://github.com/microsoft/vscode/blob/80bc53a0abde6fdf956e6439beae6e4bdcf6371c/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L179

**Comment by bpasero** [comment]
Yes, in all my issues with this, panel is never opened on startup. I typically keep it closed always.

**Comment by sandy081** [comment]
I do not think it is working as expected.

- I see the terminal is shown automatically after reload (even if I have it closed before reload)
- Status bar does not show the tasks info 
- I do not see the building (progress icon) on the tasks in the terminal

Please see the recording

https://user-images.githubusercontent.com/10746682/198305603-0204e780-10d4-4353-9e3f-a3a6e51aa89f.mp4

**Comment by jeanp413** [comment]
Created a PR fixing this https://github.com/microsoft/vscode/pull/165110
