### ISSUE TITLE
Perf: review slow running early workbench contributions

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#159675]
Refs: https://github.com/microsoft/vscode/issues/156864

I instrumented slow running code that executes via `registerWorkbenchContribution` at an early stage before editors restore. In devtools you will see a warning in case the contribution needs more than `5ms` being instantiated:

![image](https://user-images.githubusercontent.com/900690/187702708-e547115e-468e-445f-994e-0d787fdcfe69.png)

The time we spend here is time we take away from the user before the editor contents appear, thus we **block the critical startup path**.

I did some experiments from a custom build that includes this change on platforms and found some contributions that constantly appeared with above `5ms` construction times.

**Task**
* use devtools profiling to see if there is a low hanging fruit to improve performance
* review if the contribution could run at a later phase, e.g. `LifecyclePhase.Restored` or even `LifecyclePhase.Eventually`

**List**
* [x] `LocalTerminalBackendContribution` @Tyriar 
* [x] `ExtensionsContribution` @sandy081 
* [x] `PreferencesActionsContribution` @rzhao271 
* [x] `UserDataSyncWorkbenchContribution` @sandy081 
* [x] `ExtensionsViewletViewsContribution` @sandy081 
* [x] `InteractiveDocumentContribution` @rebornix 
* [x] `RemoteEmptyWorkbenchContribution` @aeschli

**Comment by bpasero** [comment]
Thanks!

**Comment by rzhao271** [comment]
Due to https://github.com/microsoft/vscode/issues/159875, I'd like to split `PreferencesActionsContribution` into smaller sets of contributions, because some parts, such as the button that brings the user from the Settings UI to the Current Profile Settings JSON, can probably be contributed later than others.
