### ISSUE TITLE
Continue Working On from desktop to vscode.dev doesn't preserve branch checkout

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#159685]
1. Have a desktop clone open with some uncommitted changes
2. Run Continue Edit Session > open on vscode.dev
3. :bug: edit session is not applied 

The reason for this is that we are opening a permalink instead of preserving the current branch checkout so the edit session identifier doesn't match up and the edit session doesn't get applied. This used to work and regressed with the edit session identifier API work, which applies stricter checks to edit session identities. Thanks @lramos15 for finding this in https://github.com/microsoft/vscode/issues/159287!

**Comment by meganrogge** [comment]
@joyceerhl not seeing a `Continue Edit Session` command

**Comment by joyceerhl** [comment]
@meganrogge sorry, that should have been `Continue Working On`, not `Continue Edit Session`
