### ISSUE TITLE
debugging: 'disconnect' doesn't work when there are subprocesses

### ISSUE THREAD

**Issue by gwisp2** [microsoft/vscode#159600]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual
Expected: clicking 'disconnect' disconnects from both sessions, debugging toolbar disappears.
Actual: clicking 'disconnect' hides information in 'call stack' panel, but the debugging toolbar is still visible.

## Steps to reproduce:

1. a.py
```
import time
print("a start")
time.sleep(10000)
print("a end")
```
2. b.py
```
import subprocess

print("b start")
subprocess.run(["python", "a.py"])
print("b end")
```
3. .vscode/launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: attach",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            },
            "pathMappings": [
                {
                    "localRoot": "${workspaceFolder}",
                    "remoteRoot": "."
                }
            ],
            "justMyCode": true
        }
    ]
}
```
4. Start debugpy
```
python -m debugpy --log-to logs --listen 5678 --wait-for-client -m b
```
5. Ensure that 'Debug: Show Sub Sessions In Tool Bar' is disabled. Start debugging (F5).
6. Click the 'disconnect' button. The 'call stack' panel becomes empty.
7. Click 'disconnect' again. Nothing happens.
8. Click 'disconnect' again. Nothing happens, error stack trace is printed to logs.

-   Python version (& distribution if applicable, e.g. Anaconda): 3.10.1
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Global
-   Value of the `python.languageServer` setting: Default

## Investigation
[Line](https://github.com/microsoft/vscode/blob/5a9675ec6bce0905703a7f839dec0fef3ee41cd4/src/vs/workbench/contrib/debug/browser/debugCommands.ts#L607)
Because of that line, debugging session for the subprocess doesn't stop, the session for the parent process stops instead.
However I couldn't reproduce the same bug when debugging JS so it is probably a bug in python extension.

## Details
<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
Connecting to DAP Server at:  localhost:5678
Connecting to DAP Server at:  localhost:5678
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

formatting
• provider: "black"

```

</p>
</details>

Extension version: 2022.13.12301015
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30542924
vsaa593:30376534
pythonvs932:30410667
wslgetstarted:30449410
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
d7fjc500:30543455
dsvsc012:30540252
azure-dev_surveyone:30548225

```

</details>

**Comment by int19h** [comment]
We don't do anything special when we detach, just unregister the tracing hooks.

If VSCode only sends one "disconnect" request to the parent process, then that's the one that'll be disconnected (but will continue running - processes are only killed on disconnect for "launch"). I suspect the reason why the stack window stops showing it is because the process being debugged is still treated as a child session by VSCode, but its parent session is now gone, so there's no node in the tree to be a parent. 

The repro steps also mention that "error stack trace is printed to logs" - @gwisp2, can you share that stack trace? If this is indeed due to confusion about the debug session parent, it should validate that.

**Comment by gwisp2** [comment]
> The repro steps also mention that "error stack trace is printed to logs" - @gwisp2, can you share that stack trace? If this is indeed due to confusion about the debug session parent, it should validate that.

```
 ERR cannot find session: Error: cannot find session
	at ExtHostDebugService.getSession (d:\dev\vscode\out\vs\workbench\api\common\extHostDebugService.js:666:19)
	at ExtHostDebugService.$acceptDebugSessionTerminated (d:\dev\vscode\out\vs\workbench\api\common\extHostDebugService.js:484:40)
	at RPCProtocol._doInvokeHandler (d:\dev\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:381:27)
	at RPCProtocol._invokeHandler (d:\dev\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:366:45)
	at RPCProtocol._receiveRequest (d:\dev\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:307:32)
	at RPCProtocol._receiveOneMessage (d:\dev\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:234:26)
	at d:\dev\vscode\out\vs\workbench\services\extensions\common\rpcProtocol.js:115:52
	at Listener.invoke (d:\dev\vscode\out\vs\base\common\event.js:457:27)
	at PrivateEventDeliveryQueue.deliver (d:\dev\vscode\out\vs\base\common\event.js:627:38)
	at Emitter.fire (d:\dev\vscode\out\vs\base\common\event.js:592:37)
	at BufferedEmitter.fire (d:\dev\vscode\out\vs\base\parts\ipc\common\ipc.net.js:478:35)
	at d:\dev\vscode\out\vs\workbench\api\node\extensionHostProcess.js:188:41
	at Listener.invoke (d:\dev\vscode\out\vs\base\common\event.js:457:27)
	at PrivateEventDeliveryQueue.deliver (d:\dev\vscode\out\vs\base\common\event.js:627:38)
	at Emitter.fire (d:\dev\vscode\out\vs\base\common\event.js:592:37)
	at BufferedEmitter.fire (d:\dev\vscode\out\vs\base\parts\ipc\common\ipc.net.js:478:35)
	at PersistentProtocol._receiveMessage (d:\dev\vscode\out\vs\base\parts\ipc\common\ipc.net.js:736:45)
	at d:\dev\vscode\out\vs\base\parts\ipc\common\ipc.net.js:622:83
	at Listener.invoke (d:\dev\vscode\out\vs\base\common\event.js:457:27)
	at PrivateEventDeliveryQueue.deliver (d:\dev\vscode\out\vs\base\common\event.js:627:38)
	at Emitter.fire (d:\dev\vscode\out\vs\base\common\event.js:592:37)
	at ProtocolReader.acceptChunk (d:\dev\vscode\out\vs\base\parts\ipc\common\ipc.net.js:269:37)
	at d:\dev\vscode\out\vs\base\parts\ipc\common\ipc.net.js:236:61
	at Socket.listener (d:\dev\vscode\out\vs\base\parts\ipc\node\ipc.net.js:50:17)
	at Socket.emit (node:events:526:28)
	at addChunk (node:internal/streams/readable:315:12)
	at readableAddChunk (node:internal/streams/readable:289:9)
	at Socket.push (node:internal/streams/readable:228:10)
	at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

That stracktrace is printed on 3rd, 5th, 7th, 9th... click on the 'disconnect' button.

**Comment by roblourens** [comment]
Is the expectation that in this case we would then show just the subsession in the callstack view and let you disconnect from that manually, or that we would disconnect from both sessions?

**Comment by int19h** [comment]
I would expect there to be a distinction between disconnecting using the floating toolbar vs disconnecting using the inline buttons on processes in the Call Stack view. For the former, the users reasonably expect it to represent the entire logical debug session, so clicking "Disconnect" there should probably disconnect everything. On the other hand, per-process "Disconnect" buttons in the Call Stack feel like they should apply only to the targeted process (and it's not an uncommon pattern for the parent process to be of no interest in a debug session once it spawns the child).

**Comment by connor4312** [comment]
I think this is fixed in https://github.com/microsoft/vscode/pull/169074, since

> On the other hand, per-process "Disconnect" buttons in the Call Stack feel like they should apply only to the targeted process (and it's not an uncommon pattern for the parent process to be of no interest in a debug session once it spawns the child).

is exactly what happens with that PR
