### ISSUE TITLE
Cyclic service dependency: `TextModelResolverService`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#159754]
The [TextModelResolverService](https://github.com/microsoft/vscode/blob/defa802e6128ce2b82dee39ca00f16d90bf3d54d/src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts#L192) has a cycling dependency onto itself via this line: https://github.com/microsoft/vscode/blob/105eef7a3079eee9d5c4c461387026b59be349f0/src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts#L196

Via injection the `ResourceModelCollection` depends on the `TextModelResolverService` which is just being created. This bug is invisible due to the magic of delayed service instantiation but will soon be warned about. To repo locally you can enforce eager instantiation of services [here](https://github.com/microsoft/vscode/blob/12710c6cfe64785140be33880c1be86290ede0ea/src/vs/platform/instantiation/common/instantiationService.ts#L226)

**Comment by jrieken** [comment]
Cycle is a bit more complex: TextModelResolverService > ResourceModelCollection > NativeTextFileService

**Comment by jrieken** [comment]
marking as `important` because this blocks completion of https://github.com/microsoft/vscode/issues/159178

**Comment by bpasero** [comment]
aye aye
