### ISSUE TITLE
[html] errors in attributes on missing semicolons and parens

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#15970]
- VSCode Version: Code - Insiders 1.8.0-insider (731c1b034ed009991c29f9ccaf035c236458e3c6, 2016-11-23T07:05:08.868Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.3|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.1.15|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.6.3|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|8.0.2|
|HTMLHint|mkaufman|0.0.3|
|vscode-stylefmt|mrmlnc|2.1.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.0.2|
|stylelint|shinnn|0.20.1|
|theme-tesla|smlombardi|5.0.0|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

I have been working with this file for weeks in VSCode Insiders.  Today, with the most recent update, certain things are being flagged as errors -- which are not errors.

I get this even when running with `--disable-extensions`

1. open a file with some "non-standard" html attributes like `ng-options` or `data-content`.  I am using [this file](http://jmp.sh/ZYxajzU).
2. the `data-content` strings have an error for every wors, for missing a semicolon:

![screen shot 2016-11-23 at 10 09 53 am](https://cloud.githubusercontent.com/assets/835148/20567268/1c1b632e-b166-11e6-89b6-2440b2c7129f.jpg)

![screen shot 2016-11-23 at 10 18 30 am](https://cloud.githubusercontent.com/assets/835148/20567304/31e48c9e-b166-11e6-9563-3fc0610024da.jpg)

and the `ng-options` string complains about missing parens:

![screen shot 2016-11-23 at 10 19 07 am](https://cloud.githubusercontent.com/assets/835148/20567336/4a087240-b166-11e6-8bdc-4cc7ebe2f992.jpg)

![screen shot 2016-11-23 at 10 19 25 am](https://cloud.githubusercontent.com/assets/835148/20567346/52c6d458-b166-11e6-9e4f-7de793362d76.jpg)

Neither of these cases are errors at all, and these were never flagged before.

**Comment by aeschli** [comment]
@smlombardi Thanks for catching this so quickly and for the good issue description!
