### ISSUE TITLE
DEBUG CONSOLE enter key showing undefined

### ISSUE THREAD

**Issue by chen0802** [Microsoft/vscode#15976]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open DEBUG CONSOLE to debug javascript files
2. Press ENTER key

Enter key should not trigger if there is no value input, scrolling to bottom of console should be good behavior since I have to drag my mouse to bottom of the window in order to see the latest information, not automatically :(

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/11350
