### ISSUE TITLE
Output auto scrolling setting is not sticky

### ISSUE THREAD

**Issue by KenSykes** [microsoft/vscode#159774]
Type: <b>Bug</b>

I like auto scroll to be enabled in output window when compiling. Several times a day it reverts back to no auto scrolling.  Seems like something is overwriting the setting..

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12800H (20 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (9.02GB free)|
|Process Argv|. --crash-reporter-id c1d9115a-8da1-4d80-9a30-b44ae9d2c0d0|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
midl3-language-server|Ale|0.0.31
markdown-mermaid|bie|1.15.2
vscode-dgmlviewer|cod|2.2.4
doxdocgen|csc|1.4.0
vscode-research|dev|1.2022.629002
vulnerability-extension|dev|1.2022.812003
graphviz-markdown-preview|gee|0.0.8
better-cpp-syntax|jef|1.15.19
l13-diff|L13|1.0.3
vscode-azdo-codereview|Mic|1.2022.28001
wavework|Mic|1.2022.620008
sarif-viewer|MS-|3.2.2
remote-containers|ms-|0.245.2
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.2.0
powershell|ms-|2022.8.5
vsliveshare|ms-|1.0.5705
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by KenSykes** [comment]
Maybe related to switching active cmake configuration?

**Comment by ElsaWu1998** [comment]
It seems that the scrolling experience is worse especially when several images are inserted in the markdown file.

**Comment by sandy081** [comment]
Can you please try disabling this setting `output.smartScroll.enabled` ?

**Comment by KenSykes** [comment]
> Can you please try disabling this setting `output.smartScroll.enabled` ?

Oh, thank you, that sounds promising from the description. Turned off smart scrolling and will see if issue goes away..

**Comment by sandy081** [comment]
Please try it out and reopen it if it does not work as expected

**Comment by KenSykes** [comment]
Been running with smart scroll off all day and no issues so this was likely it - thanks!
