### ISSUE TITLE
Suggestion on installing pylint comes with malformed terminal command

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#15977]
- VSCode Version: 1.7.2 (1.7.2)
- OS Version: macOS 10.11.6 El Capitan

Steps to Reproduce:

1. From a fresh VSCode installation, open python file (*.py)
2. Click "Install pylint" in the appearing banner:

![screen shot 2016-11-23 at 18 38 30](https://cloud.githubusercontent.com/assets/994357/20572663/a7afac9c-b1ac-11e6-9e7e-816ba1ab1dad.png)

3. See failing command in terminal:

![screen shot 2016-11-23 at 18 38 37](https://cloud.githubusercontent.com/assets/994357/20572666/abfe95f6-b1ac-11e6-82b8-5b80779eaf79.png)

### Solution

Enter the proper command:

```bash
python -m pip install pylint
```

**Comment by jrieken** [comment]
please file against the extension you are using

**Comment by fredrikaverpil** [comment]
Ah, sorry, I could've sworn I didn't have the Python extension installed - but I must've, I guess.

**Comment by karteek-paruchuri** [comment]
even I've a problem with the pylint extension. I repetitively get the prompt "Pylint is not properly installed or malfunctioning"
