### ISSUE TITLE
VSC is transparent / opaque

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#159760]
We have written the ne
Type: <b>Bug</b>

I increased how transparent it is. Now, no matter how many times I uninstall and install visual studio code, no matter how long I google this issue, I can not fix it. The standard control CTRL+ALT+C doesn't work, while CTRL+ALT+Z does. It is so transparent now, I can not work on it. Reinstalling doesn't work.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19043
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.36GB (2.74GB free)|
|Process Argv|--crash-reporter-id 0d965da4-9a5a-404c-828f-b387d4abae99|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
askia-qexml-generator-extension|Ask|1.0.1
vscode-icontheme-nomo-dark|be5|1.3.6
batch-rename-extension|Jan|0.0.5
vscode-icon-theme|jtl|1.6.6
theme-karyfoundation-themes|kar|27.2.3
material-product-icons|PKi|1.4.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
glassit|s-n|0.2.4
bootstrap4-vscode|the|6.1.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.2

(11 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

eded data into your clipboard because it was too large to send. Please paste.

**Comment by gjsjohnmurray** [comment]
> I increased how transparent it is.

Please explain what you mean. If necessary, paste screenshots.
