### ISSUE TITLE
"php.validate.executablePath" on Mac OSX

### ISSUE THREAD

**Issue by EBKH** [Microsoft/vscode#15979]
- VSCode Version: 1.7
- OS Version: OS Sierra 10.12.1

Steps to Reproduce:

1. Open VS Code
2. Open a php File

Hello, I'm used to use Windows, I do know how to configure the "php.validate.executablePath" on Windows; but I just don't find how to get the path for Mac OSX

**Comment by JacobGunther12** [comment]
Have you tried assigning PHP to $PATH? If you have, you can call the PHP executable by the $PATH variable. I am guessing this will work since most software can call $PATH.

**Comment by dbaeumer** [comment]
@EBKH where is PHP installed on our Mac?

**Comment by EBKH** [comment]
@JacobGunther12 $PATH did not solved the issue

@dbaeumer Not sure, at the office everything is Mac, so I just open "Application Manager" and start up the servers; I use xampp and I found php.ini at XAMPP/xamppfiles/etc/
However, there's no php.app/.apk or other file just named php.something
