### ISSUE TITLE
Regex search/replace sometimes corrupts text

### ISSUE THREAD

**Issue by bvschaik** [microsoft/vscode#159733]
Type: <b>Bug</b>

Context: I'm cleaning up a bunch of HTML files using search/replace with regular expressions. Sometimes the replace fails to properly process, corrupting the text.

Unfortunately this doesn't happen every time, even for the same regular expression. It seems to happen most of the time when the regular expression involves new lines (\n) with multiple consecutive matches.

Example:
Search: `\n\s+</div>` with regex enabled
Replace: `</div>`

Example text in file:
```
          <div class="pull-right"></div>
        </div>
        <div></div>
      </div>
    </div>
```

Expected result:
```
          <div class="pull-right"></div></div>
        <div></div></div></div>
```

Actual result:
```
          <div class="pull-right"></div></div></div></div></div>v>
```

<img width="1190" alt="Screen Shot 2022-09-01 at 08 41 12" src="https://user-images.githubusercontent.com/104874/187851059-823be4ac-9954-43af-8d69-3a69b55cd431.png">

VS Code version: Code 1.70.2 (Universal) (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:37.829Z)
OS version: Darwin x64 21.6.0
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|64.00GB (37.53GB free)|
|Process Argv|--crash-reporter-id 5dc625b0-18cb-4408-b2b8-6910c0953274|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
hexeditor|ms-|1.9.8

</details>

**Comment by ArturoDent** [comment]
I can't replicate this on W11 - v1.71 Stable (please test it in v1.71).  Do you see this issue in Find in a file or Search across files?

Does it make any difference if you escape the forward slash, so try `<\/div>` in your regex?  The change isn't necessary for me but you might try it.

**Comment by bvschaik** [comment]
- Tested with 1.71 (Stable): bug still exists
- This is search across files (Cmd+Shift+F on Mac / View -> Search / the sidebar panel on the left)
- Escaping the slash doesn't make a difference

I played around and the following consistently reproduces it for me:

File test.html with contents:
```
          <div class="pull-right"></div>
        </div>
        <div></div>
      </div>
    </div>
  </div>
</div>
```

1. Create a folder on your disk and copy the test.html file in it (don't do this with VSCode! I think there's some caching/buffering going on here).
2. Open a new VSCode window and open the folder, _but not the test.html file!_
3. Run a Search with replace across files for: `\n\s+</div>` with replace: `X`
4. Note that in the search result listing, the replacement is incorrect: 
<img width="226" alt="Screenshot 2022-09-02 at 08 18 45" src="https://user-images.githubusercontent.com/104874/188071738-fd5ca1ed-1046-4e05-ad19-19299b684299.png">

5. If you click any of the search results, the replace preview (compare window) shows also the wrong replacement
6. Now, with the replace preview _open_, rerun the search (click on the search input box and hit enter)
7. The replace preview will close automatically but the search results change: they are now correct 
<img width="223" alt="Screenshot 2022-09-02 at 08 21 00" src="https://user-images.githubusercontent.com/104874/188071773-c8457fd6-fc1e-4063-a470-0ed6991a7c4d.png">

8. Run the search again: incorrect results
9. Now, open the test.html file for editing
10. Run the same search again: correct results
11. Close the file and rerun the search: replacement is incorrect again

I think it only happens when the file is not yet loaded into a buffer somewhere.

**Comment by bvschaik** [comment]
Above steps also reproduce the bug on Windows 10, v1.71, so it's not a Mac-specific bug.

**Comment by roblourens** [comment]
This is https://github.com/microsoft/vscode/issues/131507
