### ISSUE TITLE
When Uncommitted/Unpushed changes Confirm Before Quit

### ISSUE THREAD

**Issue by bsell93** [microsoft/vscode#159710]
Would be nice to have a feature similar to Confirm Before Quit like discussed in #14710, except only in the case where you have uncommitted and/or unpushed (git) changes.

Kind of a first world problem, but with a mix of WFH and in-office I like to use my personal desktop (because it's faster) at home and my work laptop at work. Unfortunately many times I've did work on my home computer only to find out I forgot to commit and push my changes.

To be clear I don't have "Confirm Before Quit" on normally because I find it annoying when trying to shut down my machine and I have nothing to save or commit/push. I just want it to prevent quit when uncommitted/unpushed changes exist.

**Comment by gjsjohnmurray** [comment]
Perhaps https://code.visualstudio.com/updates/v1_70#_edit-sessions-across-vs-code-for-the-web-and-desktop is relevant to you. Upcoming 1.71 will bring more in this area too.

**Comment by bsell93** [comment]
@gjsjohnmurray that definitely seems like it would help tremendously! I will look into that. If it doesn't fit my needs I will come back and reopen with explanation! Thanks!
