### ISSUE TITLE
markers hidden by decorations

### ISSUE THREAD

**Issue by anatsegev** [Microsoft/vscode#15972]
- Monaco Editor Version: 0.7.0
- OS Version: Chrome

Hi,

We create an editor for a custom language.
The editor holds queries, separated by empty lines.
We use changeDecorations in order to highlight the current query according to the user cursor position.
The decoration use a class that sets the background-color.
I'm working on adding a validation check that will mark errors in the query. I'm using setModelMarkers for that.

It seems that the error marker is 'hidden' by the decoration. 

How do I use both markers and decorations for the same position?

Thanks,
Anat

**Comment by jrieken** [comment]
This issue was moved to Microsoft/monaco-editor#273
