### ISSUE TITLE
I want reopen all Editors(code editor, custom editor, custom text editor mixed open)

### ISSUE THREAD

**Issue by lusian01** [microsoft/vscode#159725]
I am a developer, developing extensions of visual studio code.

I was posted on stackoverflow(vscode question), but I'm sorry for posting it here because it's urgent. I wanted to upload it with the "api-proposal" tag, but it's difficult to add that tag.

What I want to do is as follows, but I am asking because it seems that the VSCode extension api does not provide the corresponding function.

[Now What i want....]
I opened custom editor, code editor, and custom text editor is opening on vscode.(mixed open) 
ex) vue file 'A' using code editor(vscode built-in), vue file 'A' using custom editor,vue file 'B' using code editor(vscode built-in), custom text editor(json file)

I want to close all currently open views by using vscode-extension api and open them again in the order in which they were originally opened.

I checked the vscode API for this, but there doesn't seem to be an api to get all open editor information and an api to reopen all editors. Are there any APIs available?

It was confirmed that "vscode.action.activeEditor" command only gets code editor information.

"view: quick open previous recenlty used editor" commands also confirmed, but it opened commandline, so this is not the result I want.

If there is no corresponding API, can I know if there is a bypass method or plan to add it?

**Comment by gjsjohnmurray** [comment]
Did you try using `window.tabGroups` as a start point?

**Comment by lusian01** [comment]
> Did you try using `window.tabGroups` as a start point?

I tried to check the data by taking "vscode.window.tabGroups" with the console log, but I got "undefined". Is the way I did it right?

**Comment by gjsjohnmurray** [comment]
I suggest https://github.com/microsoft/vscode-discussions/discussions is a better place for questions about how to use extension APIs. Also, sharing actual code (ideally as simple as possible and as a GH public repo) is probably more likely to produce help and advice from other extension devs.

**Comment by gjsjohnmurray** [comment]
/question that has now been asked on vscode-discussions
