### ISSUE TITLE
Filter for folder view, `.vsignore`?

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#1597]
Code presents a directory tree on the left in the place where a project usually resides.
This is generally fine, but folders tend to become clogged with intermediate files, or ancillary files that are uninteresting, or unrelated to the project.
I would love to see a `.vsignore` feature - more or less like `.gitignore`, so that we can configure files and patterns that should be ignored in the directory/project listing.

**Comment by mathiask88** [comment]
There is an entry in the settings for this "files.exclude".

**Comment by bpasero** [comment]
Yes, thats the one :+1:

**Comment by TurkeyMan** [comment]
Found it. Thanks!
