### ISSUE TITLE
package.json on hover does not show latest version

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/vscode#159741]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.70.2
- OS Version: macOS 12.5.1

Steps to Reproduce:

1. package.json with `typescript`
2. hover over typescript

Actual: 
<img width="455" alt="image" src="https://user-images.githubusercontent.com/17984549/187867597-7c2b0f9b-1676-454f-9b72-c51c088af8c0.png">

Expected: Latest version: 4.8.2

Code pointer: https://github.com/Microsoft/vscode/blob/9a03a86c0a54a24c355bd950ddad91a0e74de6dd/extensions/npm/src/features/packageJSONContribution.ts#L303

**Comment by gjsjohnmurray** [comment]
1.71 is likely to ship later today. When it does, please re-test and close this if fixed.

**Comment by mxschmitt** [comment]
I verified it's fixed in the insiders build, closing by that!
