### ISSUE TITLE
Remote Server extension doesn't reuse the proxy server is subsequent connections

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#159794]
The proxy server (and connection to Basis) should be reused across window reloads to make subsequent connections faster. @tanhakabir tried to get this working, but she was having an issue where it seemed like the proxy server was always getting closed when the extension host shut down regardless of whether it was "detached" or not...

**Comment by tanhakabir** [comment]
🥳

**Comment by connor4312** [comment]
It turned out `stdio: 'pipe',` made detach silently not really do anything, had to set `stdio: 'ignore',` 😛

**Comment by mjbvz** [comment]
@connor4312  Can you please provides steps to verify this?

**Comment by connor4312** [comment]
Not sure there's a good way to verify other than:

1. Have the `code-server` running somewhere, `ms-vscode.remote-server` installed on your desktop VS Code, then `Connect to Remote` to the code-server instance
2. Note roughly how long it takes for the window to connect (and start installing the VS Code server) to that remote server after reload
3. Reload again
4. The 2nd reload should be roughly 500-2000ms faster than the first connection

**Comment by rzhao271** [comment]
I reloaded and now the spinner is hanging on the "Opening Remote..." step.

**Comment by connor4312** [comment]
This is unlikely to be a verification-found of this issue. Please check your developer tools for errors, and open a new issue for that. This issue should still be verified for this endgame.
