### ISSUE TITLE
VS Code can't search with spaces

### ISSUE THREAD

**Issue by nikitavoloboev** [Microsoft/vscode#15978]
- VSCode Version: 1.7.2
- OS Version: 10.11.6

Steps to Reproduce:

1. press cmd + f and write your search query that has a space in it
2. spaces don't register 
3. for example I type in 'one word two word'
4. and I get : 
![2016-11-23 at 18 51](https://cloud.githubusercontent.com/assets/6391776/20572941/df19d512-b1ad-11e6-9dc2-24ff0401892c.png)

No spaced.

**Comment by jrieken** [comment]
not for me...

<img width="479" alt="screen shot 2016-11-23 at 21 35 08" src="https://cloud.githubusercontent.com/assets/1794099/20577886/bbdb3f0c-b1c4-11e6-937b-ef109b6511cb.png">

**Comment by nikitavoloboev** [comment]
I am also using Vim Plugin : https://github.com/VSCodeVim/Vim

Perhaps that somehow plays a role.

**Comment by yoisel** [comment]
What do you mean by "OS Version: 10.11.6" ?

**Comment by nikitavoloboev** [comment]
![2016-11-23 at 22 58](https://cloud.githubusercontent.com/assets/6391776/20580022/52910cdc-b1d0-11e6-8995-f9c5bcfead8d.png)

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#1094
