### ISSUE TITLE
Git: Post Commit Command

### ISSUE THREAD

**Issue by bpali** [microsoft/vscode#159734]
Type: <b>Bug</b>

Steps to reproduce
1. set Git: Post Commit Command to "push"
2. commit

Expected result
1. local branch to be pushed to remote

Expected result doesn't happen - please note that there is no conflict with remote branch that would prevent the push to be done.
I also tested with all my git extensions disabled (git-prefix, git-graph, gitlens, githistory)

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:25.715Z)
OS version: Linux x64 5.15.0-46-generic snap
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3899)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|2, 3, 2|
|Memory (System)|31.26GB (0.30GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id cc8251e4-236e-4c37-8f8c-ca3a4618b7a5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
vscode-intelephense-client|bme|1.8.2
dart-code|Dar|3.46.1
flutter|Dar|3.46.0
githistory|don|0.6.19
gitlens|eam|12.2.0
fold-unfold-all-icone|Fer|0.0.3
vscode-firefox-debug|fir|2.9.8
git-graph|mhu|1.30.0
Angular-BeastCode|Mik|10.0.3
python|ms-|2022.12.1
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vscode-typescript-tslint-plugin|ms-|1.3.4
back-n-forth|nic|3.1.1
vscode-print|pdc|0.9.28
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
vscode-fileutils|sle|3.5.0
git-prefix|srm|1.3.0

</details>

**Comment by lszomoru** [comment]
@bpali, I am unable to reproduce the problem locally. Would you be able to share some additional information, or maybe a recording (https://gifcap.dev) while you are trying to reproduce the problem? Thank you very much in advance!

**Comment by bpali** [comment]
With the latest version of vscode it's not reproducing anymore. Thank you for the support.
