### ISSUE TITLE
Windows 7 EOS alert on update manual check

### ISSUE THREAD

**Issue by Bellisario** [microsoft/vscode#159701]
### Introduction

When I updated VSCode to the latest release, I received the notification about the [end of support of W7](https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7) so I was expecting checking for updates would "alert" the same thing, but I see instead see the default "no update found" which may let users think there is no problems with update, when instead what are you running is (probably) one of the latest VSCode version you can run.

### Feature implementation explanation

After checking for updates, add the EOS warning on the alert "no update found" to better inform users they have to update their system to continue receiving new VSCode updates.

**Comment by joaomoreno** [comment]
You are correct: There are no problems with update.

Since that _end of support_ warning comes on startup every time, I don't think it's necessary to also show it when checking for updates.

There's no more planned work to be done on this release.
