### ISSUE TITLE
Too easy to mistakenly move files

### ISSUE THREAD

**Issue by MarcusBullock** [Microsoft/vscode#15971]
Does anyone else find it's way too easy to mistakenly drag and drop files into new folders?

Please excuse if you don't. But I've found it's very easy to move files by mistake when working on big projects and can be a nightmare trying to find where you dropped the file if, especially in a large file tree structure.

Again, this might be me and my clumsy hands so apologies, but I think it would be awesome to at least turn on an option to confirm file drag and drops. That way people who don't care for the feature wouldn't have it foisted on them.

**Comment by bpasero** [comment]
As a workaround there is a setting: `"explorer.enableDragAndDrop": false`

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/6486

**Comment by MarcusBullock** [comment]
cheers!
