### ISSUE TITLE
windows default close button location moved on its own when updating to v1.71.0

### ISSUE THREAD

**Issue by Orenico10** [microsoft/vscode#159813]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Windows 10

BEFORE UPDATING:
![image](https://user-images.githubusercontent.com/78265216/188022405-b9177a8d-2269-4de5-894c-21790b65359a.png)

AFTER UPDATING:
![image](https://user-images.githubusercontent.com/78265216/188021807-6ae7c987-d0ec-4a10-b1f1-b8d1368fea7f.png)

Steps to Reproduce:

1. update vscode to version 1.71.0
2. vscode decides to move the closing button location

**Comment by rzhao271** [comment]
Are you using a right-to-left language for your OS?

Mitigation: Disable the `window.experimental.windowControlsOverlay.enabled` setting and reload the window.

**Comment by Orenico10** [comment]
> Are you using a right-to-left language for your OS?
> 
> Mitigation: Disable the `window.experimental.windowControlsOverlay.enabled` setting and reload the window.

yes, I am using an RTL language for my OS but this has never been an issue in previous versions.

**Comment by yume-chan** [comment]
I'm curious whether native Windows apps show their controls at top-left when using an RTL language?

**Comment by deepak1556** [comment]
This is expected since the controls are drawn natively by the runtime rather than the application drawing it before `1.71`. Other native windows application also move the controls to `top-left` for RTL languages. We should adjust the rest of titlebar contents to match this behavior.

**Comment by Orenico10** [comment]
> I'm curious whether native Windows apps show their controls at top-left when using an RTL language?

![image](https://user-images.githubusercontent.com/78265216/188124834-56079f4d-dc30-4f37-9da8-7d0a38de11c3.png)
This is what Google Chrome title bar looks like if that answers your question

**Comment by A7med3bdulBaset** [comment]
I have the same bug.
How can I solve this problem?

**Comment by Orenico10** [comment]
> I have the same bug.
> How can I solve this problem?

Disable the `window.experimental.windowControlsOverlay.enabled` setting

**Comment by rzhao271** [comment]
@deepak1556 I don't think VS Code should move the titlebar contents if it is still displaying the text in English.
In the screenshot below, I have VS Code, Notepad++, Paint, and Office loaded, and Paint is the only one with both RTL text and mirrored controls.
![Screenshot](https://user-images.githubusercontent.com/7199958/188207609-d857d12b-ddae-49ad-97bf-0eb74258e2c9.PNG)

P.S. I can't read Farsi.

**Comment by A7med3bdulBaset** [comment]
open setting by `ctrl + ,` 
search about `window.experimental.windowControlsOverlay.enabled`
uncheck it.

**Comment by deepak1556** [comment]
@rzhao271 I agree. I was under the impression this bug also affected users who had RTL display language set in VSCode. Native applications I had tested was when application also had the same display language as the system. I can confirm the alignment behavior of WCO when application has LTR while system has RTL.

**Comment by ybh10** [comment]
As suggested above, disabling window.experimental.windowControlsOverlay.enabled solved the issue.
