### ISSUE TITLE
Full Screen Mode, button display will be incomplete

### ISSUE THREAD

**Issue by 0xff-dev** [microsoft/vscode#159862]
Type: <b>Bug</b>

To enter full screen mode, click the `green button` and `Cmd+Ctrl+f`. After entering full screen via the green button, when the mouse moves to the top of the screen, the button display will be incomplete.

https://user-images.githubusercontent.com/20641704/188099578-25cad8a1-25c1-4e70-b6c0-e145b2e72c62.mov

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (5.17GB free)|
|Process Argv|--crash-reporter-id 40d5101c-7919-4e07-ba49-c06bd16fbba1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.2.1
go|gol|0.35.2
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
cpptools|ms-|1.12.4
rust-analyzer|rus|0.3.1186
vim|vsc|1.23.2
vscode-todo-highlight|way|1.0.5

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
2144e591:30553903

```

</details>

**Comment by bpasero** [comment]
I am quite certain this is not something VSCode is doing wrong but some issue with either Electron or the configuration on the users OS. I am not aware of a way for VSCode to make it possible that macOS is not able to draw the full title when you go up with the mouse.

Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by 0xff-dev** [comment]
> I am quite certain this is not something VSCode is doing wrong but some issue with either Electron or the configuration on the users OS. I am not aware of a way for VSCode to make it possible that macOS is not able to draw the full title when you go up with the mouse.
> 
> Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

I tried `vscode-insiders`, same results. Here are the screenshots.
![image](https://user-images.githubusercontent.com/20641704/188256635-698c8d3b-f9df-47e9-a597-ac6bb47ab61b.png)

**Comment by bpasero** [comment]
Did you install a 3rd party software that could modify window management on macOS?

**Comment by 0xff-dev** [comment]
No. I don't have any third party window management software installed.

**Comment by bpasero** [comment]
Does it reproduce with other Electron apps such as https://github.com/electron/fiddle/releases ?

**Comment by 0xff-dev** [comment]
> Does it reproduce with other Electron apps such as https://github.com/electron/fiddle/releases ?

I just installed the software and the above problem did not occur.

**Comment by bpasero** [comment]
Can you try to run `code --disable-extensions --user-data-dir <directory>` where `<directory>` is an empty folder? This will ensure Code is starting with a fresh data directory, e.g. no specific settings and without any extensions running.

**Comment by 0xff-dev** [comment]
<img width="624" alt="image" src="https://user-images.githubusercontent.com/20641704/188257713-0631df7e-cd29-4c8b-8bcc-93f63128a497.png">
<img width="283" alt="image" src="https://user-images.githubusercontent.com/20641704/188257719-fd7d689c-32bf-41d1-9b97-3e1be1de0d65.png">
Same results. Is it possible that it's a system problem? My system is version 10.15. I asked my friend, his system is version 11.0 onwards. Didn't see the problem.

**Comment by imboye** [comment]
I have the same problem. My computer is a macbook Pro 13-inch with MacOS 10.15.7. How to fix it?

**Comment by rzhao271** [comment]
Does setting `window.experimental.windowControlsOverlay.enabled` to false fix the issue?

**Comment by rzhao271** [comment]
I'm unable to repro this issue on Big Sur.
Did this issue start with 1.71?

**Comment by 0xff-dev** [comment]
> I'm unable to repro this issue on Big Sur.
> 
> Did this issue start with 1.71?
Yes. I asked my friend whose system is bigsur and did not have this problem.

I've seen this problem in previous versions as well.

**Comment by hzbd** [comment]
https://github.com/microsoft/vscode/issues/157440#event-7142410266

**Comment by rzhao271** [comment]
Because I think the issue has to do with Electron but I don't have Catalina installed, I'm wondering what was the last stable version of VS Code that was working for you? Below, I have linked to three macOS Universal builds with their Electron versions attached. I'm expecting the issue to be between 1.67.2 and 1.69.2, but I'm not sure yet.

[1.67.2 universal (Electron 17)](https://az764295.vo.msecnd.net/stable/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/VSCode-darwin-universal.zip)
[1.69.2 universal (Electron 18)](https://az764295.vo.msecnd.net/stable/3b889b090b5ad5793f524b5d1d39fda662b96a2a/VSCode-darwin-universal.zip)

If even 1.67.2 has the full screen mode issue, here's a link to 1.65.2 to try:

[1.65.2 universal (Electron 13)](https://az764295.vo.msecnd.net/stable/c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1/VSCode-darwin-universal.zip)

Can you please try the versions and tell me which ones have the full screen mode issue?

**Comment by 0xff-dev** [comment]
```shell
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 19.6.0
```
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/20641704/189011594-706acef0-810b-47f5-b2a9-5a98fa69c598.png">

ok

---

```shell
Version: 1.69.2 (Universal)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:57.074Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 19.6.0
```
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/20641704/189010970-b2aea89b-6081-40bc-ae49-7ed94f2d99a1.png">

ok

---

```shell
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0
```
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/20641704/189011224-3e399d41-de7b-4cbe-af0a-cf517deff6f1.png">


ok

**Comment by rzhao271** [comment]
It could be from https://github.com/microsoft/vscode/pull/155906/files#diff-8df60a43bae936033d4187a89baf39cc9f4e427ce9ef6dee62918665dd2c9bb5R1085.

But, based on https://github.com/microsoft/vscode/issues/157440, it seems a similar bug was in 1.70.0.

I noticed that VS Code only started calling `setTrafficLightPosition` starting in 1.70.0.

**Comment by deepak1556** [comment]
Thanks for narrowing down the issue, macOS >= 11 have increased titlebar height compared to earlier versions you can see the context on it at https://github.com/microsoft/vscode/issues/106528#issuecomment-710686883 . This is not a regression in the `setTrafficLightPositions` API but rather we should adjust the offset provided in https://github.com/microsoft/vscode/pull/155906 to account for the different titlebar heights depending on the OS version similar to https://github.com/microsoft/vscode/blob/c7c1717456e4543aa49c0f9678f686e84dd0dd5d/src/vs/workbench/electron-sandbox/parts/titlebar/titlebarPart.ts#L33-L40

**Comment by rzhao271** [comment]
I created a [custom Insiders build](https://az764295.vo.msecnd.net/insider/85061ccca43e1b5274dc7a6a655800369deaa4a6/VSCode-darwin-universal.zip) that corresponds to the commit https://github.com/microsoft/vscode/commit/85061ccca43e1b5274dc7a6a655800369deaa4a6.

Can you try that build and:
1. Open the `Log (Main)` output window and paste the output? There should be some logs specifically about the traffic light position.
2. Tell me whether the fix works? I tried to reset the traffic light position in some cases.

Also, something I noted about Big Sur is that while it is in full screen mode, it is not affected by `setTrafficLightPosition`.

**Comment by 0xff-dev** [comment]
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/20641704/190036909-88f6a904-8535-4e14-95e4-e7104f19a857.png">
I think it has worked properly.

```shell
[2022-09-14 09:14:25.774] [main] [info] update#setState idle
[2022-09-14 09:14:26.821] [main] [info] options.height is 22
[2022-09-14 09:14:26.822] [main] [info] Setting traffic light y value to 3.5
[2022-09-14 09:14:27.163] [main] [info] UtilityProcess<1>: Creating new...
[2022-09-14 09:14:27.169] [main] [info] UtilityProcess<1>: received spawn event.
[2022-09-14 09:14:29.084] [main] [info] options.height is 0
[2022-09-14 09:14:29.084] [main] [info] Setting traffic light y value to 4
[2022-09-14 09:14:33.569] [main] [info] options.height is 22
[2022-09-14 09:14:33.569] [main] [info] Setting traffic light y value to 3.5
[2022-09-14 09:14:34.402] [main] [info] options.height is 0
[2022-09-14 09:14:34.402] [main] [info] Setting traffic light y value to 4
[2022-09-14 09:14:55.638] [main] [info] update#setState checking for updates
[2022-09-14 09:14:56.439] [main] [error] UpdateService error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information.
[2022-09-14 09:14:56.439] [main] [info] update#setState idle
[2022-09-14 09:18:00.702] [main] [info] options.height is 22
[2022-09-14 09:18:00.703] [main] [info] Setting traffic light y value to 3.5
[2022-09-14 09:18:02.122] [main] [info] options.height is 0
[2022-09-14 09:18:02.122] [main] [info] Setting traffic light y value to 4
[2022-09-14 09:18:06.736] [main] [info] options.height is 22
[2022-09-14 09:18:06.736] [main] [info] Setting traffic light y value to 3.5
[2022-09-14 09:18:09.040] [main] [info] options.height is 0
[2022-09-14 09:18:09.040] [main] [info] Setting traffic light y value to 4
[2022-09-14 09:18:19.235] [main] [info] options.height is 22
[2022-09-14 09:18:19.235] [main] [info] Setting traffic light y value to 3.5
[2022-09-14 09:18:22.086] [main] [info] options.height is 0
[2022-09-14 09:18:22.086] [main] [info] Setting traffic light y value to 4
```

**Comment by deepak1556** [comment]
Discussing the above fix with @rzhao271 , we think this issue requires further investigation on the Electron side. Current investigation shows that `height` value is 0 when application goes fullscreen for all OS versions and that is because in fullscreen the titlebar is drawn by the OS and not Electron. But what is interesting, is that `setTrafficLightPosition` api does not cause the buttons to redraw in macOS >= 11 which potential hides this issue in VSCode.

Electron decides to redraw the buttons whenever `setTrafficLightPosition` is called depending on whether a view is hosting the buttons, we think this might not be the case when application enters fullscreen in macOS >= 11 leading to a no-op call in these versions, refs https://github.com/electron/electron/blob/38a7da692aaae01dae97e96b7a5eb648765efe33/shell/browser/ui/cocoa/window_buttons_proxy.mm#L222-L229. We will confirm if that is the case and if so, align the behavior of older versions to be the same which will help remove the workaround in VSCode.
