### ISSUE TITLE
In the local text search, add auto-complete based on the top K recent search strings

### ISSUE THREAD

**Issue by yoisel** [Microsoft/vscode#15985]
This is a feature request (I think).

I am currently using:
- VSCode Version: 1.7.2
- OS Version: Linux (xubuntu 16.04 with patched libxcb.so.1 to go around the bug in vscode with xrdp, in case it matters)

Steps to Reproduce:
1. Press Ctrl+F
2. Search for a really long string that you just typed 2 min ago... you will have to enter it all over again.

For reference, take a look at how IntelliJ IDEA implemented this.

**Comment by alexandrudima** [comment]
The find widget has a history in there accessible via `alt+up` or `alt+down`, but does not have suggestions.

**Comment by activescott** [comment]
Just incorporating that secret `alt+up` key into that find dialog UX somehow (hint?) would be a HUGE value.

**Comment by yoisel** [comment]
There is a small caveat on that `alt+up/down` feature as well, the history only gets updated when the widget gets closed, if you are doing a search of several strings in a row and going back-and-forth with them, you have to close the widget and open it again every time (or at least the first time you search for each string) to take advantage of this.

**Comment by yoisel** [comment]
Maybe two extra buttons on the widget with up/down arrows and relevant tool-tips?

**Comment by yoisel** [comment]
As of 1.32.3 we now get access to previous search by simple up/down arrows on the search window, much better.
