### ISSUE TITLE
Add support for transparency in editorOverviewRuler.background

### ISSUE THREAD

**Issue by Nevro** [microsoft/vscode#159843]
```
"workbench.colorCustomizations": {
  "editorOverviewRuler.background": "#00000080"
}
```
Ruler background is set to black with 50% transparency, but vscode shows solid black!

![withminimap](https://user-images.githubusercontent.com/2953887/188068088-cee525ca-2177-4d0a-925b-e160ec078d2e.png)  ![withoutminimap](https://user-images.githubusercontent.com/2953887/188068110-e57518cb-13de-4e2b-915b-a8f31c539f98.png)

Description for editorOverviewRuler.background also says: `...Only used when the minimap is enabled and placed on the right side of the editor`, but vscode use this background if minimap is enabled or not!

**Comment by alexdima** [comment]
The color description is out of date. We changed the behavior of `editorOverviewRuler.background`  via https://github.com/microsoft/vscode/issues/148150 so we now always respect `editorOverviewRuler.background`. However, it never supported transparency, so we could add support for that.
