### ISSUE TITLE
Add option to disable new minimize/maximize/restore/close buttons due to bug with custom dialogs

### ISSUE THREAD

**Issue by ihor-oleks** [microsoft/vscode#159876]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Windows 11

Steps to Reproduce:

1. Enable custom dialogs (`"window.dialogStyle": "custom"`)
2. Create a new file
3. Try to close it

![image](https://user-images.githubusercontent.com/100670062/188112484-ad1cfbcb-1ccc-4879-875b-871b489f3a6c.png)

**Comment by gjsjohnmurray** [comment]
Please try `"window.experimental.windowControlsOverlay.enabled": false` (requires VS Code restart)

**Comment by ihor-oleks** [comment]
Works, thanks! Is it expected to be like this or as a temporary setting?

**Comment by sbatten** [comment]
@ihor-oleks is this the bug to which you refer? https://github.com/microsoft/vscode/issues/159671
