### ISSUE TITLE
Better indicator of overflow in editor's tab bar

### ISSUE THREAD

**Issue by josh-tepper** [Microsoft/vscode#15982]
- VSCode Version: 1.7.1
- OS Version: Os X 10.11.6

See image.  There is no visual indicator of the overflow.  It is not clear that there are more open editors.  Only once moused over does  the tab bar have  a scrollbar (it was moused over as I was taking the screenshot).

<img width="929" alt="screen shot 2016-11-23 at 12 58 58 pm" src="https://cloud.githubusercontent.com/assets/20231989/20573562/620116b4-b17e-11e6-9cd2-e9e6a4042b36.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7987
