### ISSUE TITLE
install extension is slow (needs caching?)

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#1598]
Invoking the command `ext install` repeatedly is really slow.

When you invoke the command, a little blue line scrolls horizontally to show it's doing something (fetching the extension database?), and eventually displays a list of extensions you can install. Repeatedly invoking the command should cache this work from last time, but it seems to re-fetch (or whatever it's doing) every time, which is fairly annoying when I want to install a few extensions at once.

**Comment by bpasero** [comment]
We improved this for 0.10.5. @joaomoreno fyi

**Comment by TurkeyMan** [comment]
I'm on 0.10.5. Can't comment on whether it's improved from prior versions, but it's still not 'fast'.

**Comment by joaomoreno** [comment]
Duplicate of #439

**Comment by TurkeyMan** [comment]
Umm, was this actually fixed? That other big was closed before I reported this one.
That fix was already made available in 0.10.5, I'm reporting on the state post-release of that prior fix. This bug is intended to represent that further work is required.

**Comment by joaomoreno** [comment]
Note that #439 is not closed.
