### ISSUE TITLE
Sticky scroll is unavailable

### ISSUE THREAD

**Issue by Igorgro** [microsoft/vscode#159807]
Type: <b>Bug</b>

Sticky scroll setting is grey and do not enable nothing, see attached screenshot

![image](https://user-images.githubusercontent.com/22894169/188012211-a5c4ac2b-050a-4962-abd0-5f94e547c6d4.png)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:10.472Z)
OS version: Linux x64 5.19.5-arch1-1
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 4700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (7.90GB free)|
|Process Argv|--unity-launch --crash-reporter-id fdb95c54-3d54-447e-96c9-f69e364947ff|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.13.0
gitlens|eam|12.2.0
gitlab-workflow|Git|3.49.0
todo-tree|Gru|0.0.215
git-graph|mhu|1.30.0
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
python|ms-|2022.14.0
hexeditor|ms-|1.9.8
material-icon-theme|PKi|4.20.0
material-product-icons|PKi|1.4.0
ansible|red|0.13.59
vscode-xml|red|0.21.0
vscode-yaml|red|1.10.1
gitmoji-vscode|sea|1.1.2
vscode-taskexplorer|spm|2.9.1
code-spell-checker|str|2.7.0
code-spell-checker-russian|str|2.0.6
jinja|who|0.0.8

</details>

**Comment by gjsjohnmurray** [comment]
The correct name is `editor.stickyScroll.enabled` (with a "d" at the end).

**Comment by Igorgro** [comment]
So this shoud be treaded as a typo in release notes 
![image](https://user-images.githubusercontent.com/22894169/188016314-2d06f6c6-02ab-41c8-b327-4eacb6982490.png)

**Comment by gjsjohnmurray** [comment]
Maybe you installed an Arch Linux distribution that was built before the final edit of the release notes. Here's what I see on my Windows workstation:

![image](https://user-images.githubusercontent.com/6726799/188019403-e5e96640-16bc-4713-9a19-e9b4c43728d6.png)

Info is also correct at https://code.visualstudio.com/updates/v1_71

**Comment by aiday-mar** [comment]
Hello, thank you @gjsjohnmurray for your very valuable contribution. I will close this issue.
