### ISSUE TITLE
Leading space in before-decorators is trimmed.

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode#15983]
- VSCode Version: Version 1.7.2
- OS Version: Windows 10 RS1

Steps to Reproduce:

Writing a vscode-istanbul plugin that shows coverage data right inside vscode.

![image](https://cloud.githubusercontent.com/assets/1018196/20574163/1240a8b2-b168-11e6-96ed-617cf9652d30.png)

The leading space for statement hits is not shown.

Decorator is created as following:

```
    const decoration = {
        range: new vscode.Range(pos.line - 1, pos.column, pos.line - 1, pos.column),
        hoverMessage: null,
        renderOptions: {
            before: {
                contentText:` ${hitCount} `,
                backgroundColor: hitCount ? hitBgColor : notHitBgColor,
                color: "rgba(255,255,255,0.5)",
            }
        }
    }

```

contentText has leading and trailing space.

**Comment by aeschli** [comment]
@nojvek What's exactly the issue? Is it that the leading and trailing whitespace in your contentText are not rendered? In that case use a fixed with whitespace such as \u2003 (See https://www.cs.tut.fi/~jkorpela/chars/spaces.html).

**Comment by nojvek** [comment]
Interesting. Thanks for the tip.
