### ISSUE TITLE
VS code Server for WSL closed unexpectedly. After vscode upgrade

### ISSUE THREAD

**Issue by pepdekpd** [microsoft/vscode#159858]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.0
- OS Version: Windows_NT x64 10.0.22000 (WSL:  5.10.102.1-microsoft-standard-WSL2) ( Ubuntu 20.04.5 LTS)

Steps to Reproduce:

1. Opening a terminal of a remote WSL project, see screendump

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/84709075/188096586-43efc165-5968-4447-a752-696e45c667b1.png">

output of:

VSCODE_WSL_DEBUG_INFO=true code ..

`+ COMMIT=784b0177c56c607789f9638da7b6bf3230d47a8c
+ APP_NAME=code
+ QUALITY=stable
+ NAME=Code
+ SERVERDATAFOLDER=.vscode-server
+ realpath /mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/bin/code
+ dirname /mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/bin
+ VSCODE_PATH=/mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code
+ ELECTRON=/mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/Code.exe
+ IN_WSL=false
+ [ -n Ubuntu ]
+ IN_WSL=true
+ [ true = true ]
+ export WSLENV=ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID
+ wslpath -m /mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ CLI=C:/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js
+ WSL_EXT_ID=ms-vscode-remote.remote-wsl
+ ELECTRON_RUN_AS_NODE=1 /mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/Code.exe C:/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js --ms-enable-electron-run-as-node --locate-extension ms-vscode-remote.remote-wsl
+ cat /tmp/remote-wsl-loc.txt
+ WSL_EXT_WLOC=c:\Users\Dekker\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.3
+ [ -n c:\Users\Dekker\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.3 ]
+ wslpath -u c:\Users\Dekker\.vscode\extensions\ms-vscode-remote.remote-wsl-0.66.3
+ WSL_CODE=/mnt/c/Users/Dekker/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh
+ /mnt/c/Users/Dekker/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh 784b0177c56c607789f9638da7b6bf3230d47a8c stable /mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/Code.exe code .vscode-server ..
+ [ -z .vscode-server ]
+ [ .vscode-server = .vscode-insiders ]
+ [ ! -t 0 ]
+ VSCODE_REMOTE_BIN=/home/pepdek/.vscode-server/bin
+ AUTHORITY=wsl+default
+ [ Ubuntu ]
+ AUTHORITY=wsl+Ubuntu
+ dirname /mnt/c/Users/Dekker/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh
+ /mnt/c/Users/Dekker/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslDownload.sh 784b0177c56c607789f9638da7b6bf3230d47a8c stable /home/pepdek/.vscode-server/bin
+ [ ! -d /home/pepdek/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c ]
+ RC=0
+ [ 0 -ne 0 ]
+ mktemp /tmp/vscode-distro-env.XXXXXX
+ STORED_ENV=/tmp/vscode-distro-env.OpPpuo
+ env
+ dirname /mnt/c/Users/Dekker/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts/wslCode.sh
+ VSCODE_CLIENT_COMMAND=/mnt/c/Users/Dekker/AppData/Local/Programs/Microsoft VS Code/Code.exe VSCODE_CLIENT_COMMAND_CWD=/mnt/c/Users/Dekker/.vscode/extensions/ms-vscode-remote.remote-wsl-0.66.3/scripts VSCODE_CLI_AUTHORITY=wsl+Ubuntu VSCODE_CLI_REMOTE_ENV=/tmp/vscode-distro-env.OpPpuo VSCODE_STDIN_FILE_PATH= WSLENV=VSCODE_CLI_REMOTE_ENV/w:ELECTRON_RUN_AS_NODE/w:WT_SESSION::WT_PROFILE_ID /home/pepdek/.vscode-server/bin/784b0177c56c607789f9638da7b6bf3230d47a8c/bin/remote-cli/code ..
+ exit 0`

**Comment by pepdekpd** [comment]
The workaround described here:
https://www.reddit.com/r/vscode/comments/kffqcr/after_upgrading_to_vscode_1521_unable_to_connect/
worked for me as well

**Comment by aeschli** [comment]
Looks like an issue with corruption in build 784b0177c56c607789f9638da7b6bf3230d47a8c.

Please speak up if you still get this.
