### ISSUE TITLE
New quickfix menu custom keybindings not working

### ISSUE THREAD

**Issue by donnyroufs** [microsoft/vscode#159811]
Does this issue occur when all extensions are disabled?: **Yes**/No

- VS Code Version: 1.71.0
- OS Version: Windows_NT x64 10.0.19044 

Steps to Reproduce:

1. Set your shortcuts like:
```json
 // probably not related
  {
    "key": "ctrl+j",
    "command": "workbench.action.quickOpenSelectNext",
    "when": "!textInputFocus"
  },
  {
    "key": "ctrl+k",
    "command": "workbench.action.quickOpenSelectPrevious",
    "when": "!textInputFocus"
  },
  // the keybindings in question
  {
    "key": "ctrl+k",
    "when": "CodeActionMenuVisible",
    "command": "focusPreviousCodeAction"
  },
  {
    "key": "ctrl+j",
    "when": "CodeActionMenuVisible",
    "command": "focusNextCodeAction"
  }
```
2. Hover a piece of code and open the quick fix menu with `ctrl+.` 
3. Try to go up and down with ctrl+j / ctrl+k

this worked before the new quick fix menu and during the experimental one. Looking at the docs it should be `codeActionMenuVisible` but that doesn't seem to work either. **Why is this needed you ask?** so that my quick open doesn't interfere. 

https://gyazo.com/ef93a8daffafd459b86c3e63759ed148?token=8479ff780a2adabc3cfc46930b6947a7

works fine without the "when" clause.

**Comment by mjbvz** [comment]
You using the old command names (they are changed before release): https://code.visualstudio.com/updates/v1_71#_new-code-action-control

```
{
    "key": "ctrl+k",
    "command": "selectNextCodeAction",
    "when": "codeActionMenuVisible"
},
{
    "key": "ctrl+j",
    "command": "selectPrevCodeAction",
    "when": "codeActionMenuVisible"
},
```

**Comment by donnyroufs** [comment]
> codeActionMenuVisible

I was certain that I had also added an example of that but I guess I did not. **That also does not work**. 
![image](https://user-images.githubusercontent.com/48981403/188019750-625aaf00-aa57-42b5-906d-039cc2495798.png)

**Comment by donnyroufs** [comment]
> selectPrevCodeAction

Ah... That's interesting, because the focus command still works without the when clause.
