### ISSUE TITLE
Generated extension fails during npm install step

### ISSUE THREAD

**Issue by rchiodo** [microsoft/vscode#159804]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: N/A
- OS Version: Windows 10

Steps to Reproduce:

1. Follow directions here: https://code.visualstudio.com/api/get-started/your-first-extension
2. Pick 'npm' as package manager
3. Say yes when asked to run 'npm install'

Fails during npm install with following output:
```
Running npm install for you to install the required dependencies.
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @types/vscode@^1.71.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aku91\AppData\Local\npm-cache\_logs\2022-09-01T20_36_42_369Z-debug-0.log
Error code

Command failed with exit code 1: npm install
```

**Comment by rchiodo** [comment]
Root cause:

```
  "devDependencies": {
    "@types/vscode": "^1.71.0",
```

Change to this and npm install works
```
  "devDependencies": {
    "@types/vscode": "^1.70.0",
```

**Comment by mjbvz** [comment]
Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62079 (wait a moment for the new package to get published)
