### ISSUE TITLE
Debug adapter process has terminated unexpectedly on Fedora 24

### ISSUE THREAD

**Issue by osmarlandin** [Microsoft/vscode#15984]
- VSCode Version: 1.7.2
- OS Version: Fedora 24

Steps to Reproduce:

1. Fresh install of Fedora 24
2. Follow the steps on https://www.microsoft.com/net/core#linuxfedora
3. Install VS Code
4. Open an existing application
5. Try to debug that

On my output window, the error is "Failed to initialize CoreCLR, HRESULT: 0x80131500"

**Comment by snaveevans** [comment]
I'm getting the same error, fresh install of openSuse and netcore.
Failed to initialize CoreCLR, HRESULT: 0x80131500
dotnet run works fine just can't attach to the process or start it directly from vs code.

**Comment by isidorn** [comment]
I believe you are trying to debug using the c# extension. Can you please file this bug against the extension repo here https://github.com/OmniSharp/omnisharp-vscode

Thanks!
