### ISSUE TITLE
Inconsistent CSS loading of codicon

### ISSUE THREAD

**Issue by NWilson** [microsoft/vscode#159877]
Hi, I believe that Monaco uses two different ways to load the codicon font, which can cause problems with certain Webpack configs.

I used the following Webpack config:

```
        module: {
            rules: [
                {
                    test: /\.css($|\?)/,
                    use: ["style-loader", "css-loader"],
                },
                {
                    test: /\.(png|jpg|jpeg|gif|ttf|svg)($|\?)/,
                    loader: "file-loader",
                    options: {
                        name: "[name].[contenthash].[ext]",
                        outputPath: "assets",
                    },
                },
            ],
        },
        plugins: [
            new MonacoWebpackPlugin({
                filename: "[name].[contenthash].worker.bundle.js",
                languages: [],
            }),
        ]
```

You can see that I'm putting the codicon font in `assets/codicon.b821e161b5644de985d2f41abb72b83b.ttf`.

## But - the codicon font is loaded in two places in Monaco:
* As a CSS file in https://github.com/microsoft/vscode/blob/485ba0e9414b927ebbc79be437060a74afea537a/src/vs/base/browser/ui/codicons/codicon/codicon.css#L9 This goes via the `css-loader`, which in turn parses the CSS file, and replaces the hardcoded reference to `src: url("./codicon.ttf?5d4d76ab2ce5108968ad644d591a16a6")` with my `[contenthash]` URL instead. Nice.
* Secondly, in https://github.com/microsoft/vscode/blob/8feb40b9284c339e2d1b0a493641e603b7f84d3d/src/vs/base/browser/ui/contextview/contextview.ts#L372 This is just a plain JavaScript string to define the `#shadow-root`'s initial CSS, and that doesn't go via any loader at all, so the context menu uses the wrong font path for codicon.

## Observed result

With this webpack config, the icons (such as "Peek »") are rendered as rectangular boxes. The codicon font is not loaded in the shadow DOM.

## Short Term Fix

Change my Webpack config, so that it doesn't use `[contenthash]` for codicon.

## Suggested Monaco fix

Could you extract the `SHADOW_ROOT_CSS` string into a `.css` file, so that it is processed through Webpack in the same way? Or, you could do an `import * as codiconPath from 'codicon.ttf';` to obtain the codicon path if you need to inject it as a string into the Shadow DOM. Or, perhaps you have some internal CSS system?

Either way, it seems wrong that with this simple Webpack config, the `codicon.tff` path should be set differently in the main DOM's `@font-face` style, as compared to the Shadow DOM's style.

**Comment by alexdima** [comment]
I believe this is a mistake in `contextview.ts` which should not use `@font-face` at all. AFAIK loading `@font-face` in the shadow dom is not supported by browsers and `@font-face` can only be used in the outer css (I think because a font globally impacts the page). See https://github.com/mdn/interactive-examples/issues/887#issuecomment-432606925
