### ISSUE TITLE
cmd + , does not work for opening settings view on macOS on lastest vscode insiders

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#159875]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.72.0-insider (Universal) Commit: c4722f1bb292284e0437eb7547808a5788fe6430
- OS Version: macOS 12.5.1（21G83）

Steps to Reproduce:

1. Use latest VSCode Insiders
2. Press cmd + ,

<img width="299" alt="スクリーンショット 2022-09-02 18 41 29" src="https://user-images.githubusercontent.com/1955233/188112403-44d26f25-37e1-45b5-a544-24fd98b1685a.png">
<img width="268" alt="スクリーンショット 2022-09-02 18 41 41" src="https://user-images.githubusercontent.com/1955233/188112409-692c3749-73c3-43c0-b8a5-c3c3493e4a28.png">

**Comment by rzhao271** [comment]
Added macos label because it seems to work fine on Windows.

**Comment by gjsjohnmurray** [comment]
@rzhao271 my screenshot was from a Windows instance of Insiders.

**Comment by rzhao271** [comment]
It might be caused by that commit, but I'm still unable to repro the issue on Windows 10 or macOS Big Sur.

**Comment by yamachu** [comment]
When I downloaded the latest Insiders to the Download folder and ran it, this did not reproduce.
It may happen when updating a global install, but I have not been able to verify this yet.
