### ISSUE TITLE
Self-contained markdown language server

### ISSUE THREAD

**Issue by tiagovla** [microsoft/vscode#159805]
I was testing the server on neovim.
I noticed the [markdown language server]( https://github.com/microsoft/vscode/tree/main/extensions/markdown-language-features/server) requires a lot from the client. Would it be possible to bundle default implementations of `markdown/parse` and all other custom requests to make the server self-contained?

**Comment by mjbvz** [comment]
I'd take a PR that does this (likely using service injection) but the current design is deliberate

- `markdown/parse` lets the client bring their own parser version 

- The custom file messages means the server is not restricted to working with local files. Ideally the LSP would also include this functionality but right now it does not

**Comment by tiagovla** [comment]
I can make a PR. Wouldn't it be simpler to add a setting for a custom tokenizer? Then call `'markdown-it'.parser` with `document._content` or make a `markdown/parse` request?

**Comment by mjbvz** [comment]
@tiagovla #160429 makes this easier to use the server as a library.  For a client that doesn't want to implement the custom messages we use, you'd instead want to use the new version of `startServer` which lets you pass in your own parser and workspace implementations
