### ISSUE TITLE
"Open in Merge Editor" and "Accept Merge" button missing in web

### ISSUE THREAD

**Issue by zWingz** [microsoft/vscode#159837]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.0

Steps to Reproduce:

1. open a codespace
2. create a merge conflict
3. open the conflict file

missin the `Open in Merge Editor` button
<img width="1461" alt="image" src="https://user-images.githubusercontent.com/13031838/188056319-eacf9f3e-574b-4cce-8901-d7215444d464.png">

missin the `Accept merge` button
<img width="1535" alt="image" src="https://user-images.githubusercontent.com/13031838/188059832-d88754eb-541e-49df-812c-405eda136f70.png">

This is context keys, current file scheme is `vscode-remote`
<img width="673" alt="image" src="https://user-images.githubusercontent.com/13031838/188056410-045db70a-5356-46cc-8a82-1f6486ef6dba.png">
<img width="703" alt="image" src="https://user-images.githubusercontent.com/13031838/188059883-9d93355b-70e3-43bb-8c09-cb670e6bdd0f.png">

but the `git.mergeChange` scheme is `file`
<img width="316" alt="image" src="https://user-images.githubusercontent.com/13031838/188056491-a8187bb8-803c-499d-b4b6-3ba1986dbedc.png">

so the button is missing because `resource in git.mergeChanges` is `false`
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/13031838/188056560-a09a4439-92d5-4985-b7fd-97583032d852.png">

**Comment by 13ibrahimov** [comment]
I can confirm that "Open in Merge Editor" & "Accept Merge" buttons are missing when VS Code is connected to WSL via Remote - WSL extension.

**Comment by jrieken** [comment]
@zWingz 👏 Thanks for the proper investigation!

**Comment by jrieken** [comment]
Let's make this a 1.70.2 candidate

**Comment by jrieken** [comment]
Fixed in main but keeping this open to cherry-pick things onto release/1.71
