### ISSUE TITLE
代码校验出错了不便于掌控

### ISSUE THREAD

**Issue by alerti** [Microsoft/vscode#15980]
is:open is:issu

> 代码校验报错全局没有报告，

**类似Ａtom 底边栏或者eslint直接显示错误在改代码下方一行,**
**在这里我只能一行一行查找,有ES7语法，关闭了自带校验，
用的ESlinte label** 
**谢谢**
:feature-request sort:reactions-+1-desc

**Comment by jrieken** [comment]
@alerti Please file issues in English

**Comment by jrieken** [comment]
@alerti ping
