### ISSUE TITLE
Explore Extensions Management notification center

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#159889]
Extracted from https://github.com/microsoft/vscode/issues/151599

We might need a way to show extension specific msgs in there. We do not want to use notifications. Example msgs: "you have 2 deprecated extensions", "you have been using this extension happily, consider sponsoring or rating it", "this extension has an update"

**Comment by sandy081** [comment]
CC @isidorn

**Comment by joaomoreno** [comment]
A possible stepping stone related to https://github.com/microsoft/vscode/issues/53405 would be to simply start by improving the default sort order of the Installed extensions view. Extensions which require attention should be placed further at the top. This might already address some of the pain points.
