### ISSUE TITLE
Quote matching logic should not apply when I am in the midst of writing a comment

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#15986]
![vscode-apostrophe-bug](https://cloud.githubusercontent.com/assets/923011/20578665/6b86db3e-b196-11e6-837e-2acacb7ef5c7.gif)

In the gif above, the `'` is automatically paired as I am writing the sentence, even though I am writing a comment and `'` used as an apostrophe is more likely to happen.

**Comment by jrieken** [comment]
The logic for that depends on the language you are using. Please update this issue with that detail

**Comment by julianlam** [comment]
Hello @jreiken, I am developing in Javascript :smile:

**Comment by waderyan** [comment]
I'm not able to reproduce on the latest Insiders. @julianlam can you try with the latest [here](https://code.visualstudio.com/insiders)?

**Comment by mjbvz** [comment]
I confirmed this behavior is present in the latest insiders builds for both singleline and multiline comments in JavaScript.

**Comment by julianlam** [comment]
@waderyan Like @mjbvz I am able to reproduce this on the latest insiders build

**Comment by mjbvz** [comment]
Seems to be fixed in the latest insiders builds. I believe the fixing change was 4bb1d18d6a6599ae93d03571961ca055ce6dcf58

**Comment by julianlam** [comment]
Confirmed fixed in the new versions updated this morning (1.8.0-insider (1.8.0-insider))
