### ISSUE TITLE
The "quick commands" text appears scrambled on a new instance window

### ISSUE THREAD

**Issue by unigazer** [microsoft/vscode#159870]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Pop!_OS 22.04 LTS (Linux)

Steps to Reproduce:

1. Launch a new VSCode instance (window)
2. The "quick commands" text appears scrambled.

Preview:
![Screenshot from 2022-09-02 11-07-54](https://user-images.githubusercontent.com/12301022/188105665-c089a30c-e3a4-4234-9b54-f3a56bc0d0a0.png)

Graphics: Mesa Intel® Xe Graphics (TGL GT2)
Windowing System: X11
GNOME Version: 42.4

**Comment by chrmarti** [comment]
I'm not aware of any changes in this area. @deepak1556 Are there any known Electron rendering issues that would show this?

**Comment by unigazer** [comment]
This is not reproducible when switching to NVIDIA Graphics on the same machine. Might be a driver issue.

**Comment by myknbani** [comment]
![Screenshot_20221004_102434](https://user-images.githubusercontent.com/5841268/193721848-a971be63-3966-46d9-b364-0398131d4c6a.png)

Happens to me as well.  It disappears on certain zoom levels.

Using an Alder Lake machine on VSCode `1.71.2`, Manjaro KDE/Plasma, X11.  Just reporting that I also experience the issue, though I understand this is not something urgent. :v:
