### ISSUE TITLE
A11y_VisualStudioCodeClient_Search_Global Search_ Keyboard:Keyboard Focus moving from search to replace instead of moving to “Match case, match whole word and Use regular expression”

### ISSUE THREAD

**Issue by VijayaBharathyA** [microsoft/vscode#159880]
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #Win32; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2022; #WCAG2.4.3; 

### Environment and OS details:
Visual Studio Code 
Windows 11 Pro version 21H2 (OS Build 22000.856)

### Repro Steps:

1.  Open Visual studio code editor    
2.  Using keyboard navigation View Menu Bar
3.  Select search option 
4. Verify that keyboard focus from search to Match case, match whole word and use regular expression or not.

### Actual Result:
 Keyboard Focus moving from search to replace instead of moving to “Match case, match whole word and Use regular expression”.

### Expected Result:
Keyboard Focus should move from search to “Match case, match whole word and Use regular expression”.

### Attachment:

![A11y-VisualStudioCodeClient-Sear](https://user-images.githubusercontent.com/100189407/188119886-c8748455-733b-40f2-b2b9-a44270aaed2b.gif)

**Comment by roblourens** [comment]
I disagree - users want to tab to the replace box much more often than they want to tab to those buttons. The buttons are in the tab flow, just a spot later.
