### ISSUE TITLE
Can't select TypeScript version from command palette

### ISSUE THREAD

**Issue by uloco** [microsoft/vscode#159917]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: 12.5.1

Steps to Reproduce:

1. Press <kbd>⌘</kbd><kbd>⇧</kbd><kbd>P</kbd> (open command palette)
2. Search for _Select Typescript version_
3. Nothing appears
4. Though, if you assign a keybinding to `typescript.selectTypeScriptVersion` you can open the popup correctly.

**Comment by mjbvz** [comment]
This is by design. The command only shows in the command palette when you are in a js or ts file

**Comment by gjsjohnmurray** [comment]
The built-in extension which contributes this command sets a when-clause to control whether or not it appears in the Command Palette:

> ![image](https://user-images.githubusercontent.com/6726799/188181584-25c52ea9-9b2b-411b-9961-655ba6a03569.png)
