### ISSUE TITLE
Ability to hide/show explorer even terminal is open by keyboard shortcuts

### ISSUE THREAD

**Issue by vieiraes** [microsoft/vscode#159936]
Its not possible to hide and show explorer when terminal is open. First i need to close teminal to do want I want.

All funcionalities I mean by shortcuts on keyboard

**Comment by meganrogge** [comment]
I've seen a recent change where sequences are unexpectedly sent to the terminal. We should investigate this.

**Comment by Tyriar** [comment]
@meganrogge I think this is by design, it works when you set:

```json
  "terminal.integrated.commandsToSkipShell": [
    "workbench.action.toggleSidebarVisibility"
  ]
```
