### ISSUE TITLE
Code action widget not preserving menu state on exit (for showing disabled/enabled actions)

### ISSUE THREAD

**Issue by justschen** [microsoft/vscode#159957]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
In Insiders at the moment, fine in stable.

1. Open the code action widget
2. Hide disabled code actions and quit out.
3. Open the code action widget again.
4. (see that the state of the action bar button is maintained, but the menu still shows disabled actions)

![Recording 2022-09-02 at 13 56 10](https://user-images.githubusercontent.com/54879025/188234104-4d80c209-68b5-4104-b9d8-48ed5c36f308.gif)

**Comment by justschen** [comment]
@mjbvz I saw that you added some refactorings and one of those was this helper 

https://github.com/microsoft/vscode/blob/6900e6f4df4157c089e895dee5fd1335a97b3c31/src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts#L623

I think the thing is that state isn't being preserved when quit out (the buttons are though) since when quit out and reopened, the menu goes back to the `show` function, and usees `options.includeDisabledActions` instead of `newShowDisabled`.

https://github.com/microsoft/vscode/blob/6900e6f4df4157c089e895dee5fd1335a97b3c31/src/vs/editor/contrib/codeAction/browser/codeActionMenu.ts#L642

**Comment by mjbvz** [comment]
Thanks @justschen!

I think this should now be fixed in the latest insiders. Give it a try and let me know if there are still any issues

**Comment by aeschli** [comment]
I don't see the footer of the code actions. Is there something special I need to do?

**Comment by mjbvz** [comment]
To validate:

1. In a js file:
```js
1 + 1
```

2. Select all
3. Trigger `refactor` using the keybinding or command
4. Try toggling if disabled code actions are shown or hidden

**Comment by aeschli** [comment]
Thanks, got it! I was trying the light bulb...
