### ISSUE TITLE
Add vscode.window.activeFolder

### ISSUE THREAD

**Issue by leotm** [microsoft/vscode#15991]
To open _git-bash.exe_ at the active folder (like _Git_ and _GitHub Desktop_).

Works 👌 for `activeTextEditor`

VS Code Marketplace: [McCarter.start-git-bash](https://marketplace.visualstudio.com/items?itemName=McCarter.start-git-bash)
Repo: [vscode-start-git-bash](https://github.com/Robert923/vscode-start-git-bash) by @Robert923

#3553 and #2067 are similar to this specific request, but not quite.

**Comment by bpasero** [comment]
Isn't that [`workspace.rootPath`](https://code.visualstudio.com/docs/extensionAPI/vscode-api#_workspace)?

**Comment by jrieken** [comment]
My understand is that it's the selected folder in the explorer. @leotm Please clarify

**Comment by leotm** [comment]
@bpasero nope.
@jrieken indeedy.

**Comment by fgodoy** [comment]
Hi guys, any news when this feature will be available? Any other way to get current selected folder?

Thanks.

**Comment by ole1986** [comment]
I woudl prefer to have vscode.activeWorkspaceFolder - Especially with the new vscode update 1.18 allowing to add multiple folders in workspace

**Comment by jrieken** [comment]
>  Any other way to get current selected folder?

Kind of... You can register commands for the [explorer context menu](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus). When being selected the resource/uri of the item in question is being passed as argument. It's not really the explorer-tree-selection but contextual and well-integrated with our commands.

**Comment by MicroCheapFx** [comment]
Few hints if someone want to do it (or note for me later) : 

- \vscode\src\vs\vscode.d.ts <= Declarations
- \vscode\src\vs\workbench\api\node\extHost.api.impl.ts <= Definitions

This API would be REALLY helpful...

**Comment by seesharper** [comment]
Is it possible to ONLY have a context menu item without it ever showing up in the command palette?

**Comment by poalrom** [comment]
How i can get selected folder if command runs using keybind? Function's params will be null

**Comment by HenrikHolmIT** [comment]
I need this feature now. Has it ever been implemented or is there another way to get the selected items in the explorer view?

I need to search for specific files but only in the currently selected folder.

**Comment by HenrikHolmIT** [comment]
This seems like such an easy low hanging fruit to harvest.

The extension we're developing has to do stuff to files located in the currently selected folder. Currently we're trying to guess that folder by looking at the file currently being edited. That's not a particular safe way of doing it but currently the only way.

It would be much more safe to have it handled by VS Code generally.

I'd like very much for you to reconsider opening this case again. To me sounds like a really easy thing to implement but I have no idea how the internals of vscode module is made.

**Comment by rndware** [comment]
> > Any other way to get current selected folder?
> 
> Kind of... You can register commands for the [explorer context menu](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesmenus). When being selected the resource/uri of the item in question is being passed as argument. It's not really the explorer-tree-selection but contextual and well-integrated with our commands.

Yeah but the resource/uri of the item in question is **not** passed if you're running the extension though a keyboard shortcut. 

So lets say you're on the explorer view and you press enter on a folder. Next you use a keyboard shortcut to run an extension you've made, it won't pass that URI as a param.

Which means you're forced to run the extension via a mouse click... which I try to avoid if at all possible :)
