### ISSUE TITLE
Prompts when changing branches in git can be misleading

### ISSUE THREAD

**Issue by humanoid2050** [microsoft/vscode#159954]
Setting up the problem scenario:
```
mkdir gittest
cd gittest/
git init
touch file
git add file
git commit -m "initial commit"
git checkout -b new_branch
echo "new_branch line" >> file
git commit -am "new_branch commit"
git checkout master
echo "master line" >> file
code .
```

At this stage, there are two branches. One has changes committed, one has changes to the working directory that can be discarded, stashed, or committed.

If you try to use the VSCode interface to simply switch to new_branch, you get a popup alerting you that local changes would be overwritten by checkout. It gives the options "Stash & Checkout", "Cancel", and "Force Checkout". The Cancel and Force Checkout buttons work as one would expect, cancelling the process or forcing it to proceed with destructive side effects respectively. The Stash & Checkout button is problematic. Based on the presented information, I would expect a call to `git stash` followed by a call to `get checkout new_branch`. End of process. This would leave me in a very sensible position where I am looking at a clean working tree reflecting new_branch, and a stash on master containing the working tree changes associated with that branch.  Instead, VSCode attempts to apply the stash to the current working tree, resulting in conflicts that have to be resolved before anything else can happen. I think either the behavior should be modified to do exactly as described, or the prompts should better reflect what will happen. Perhaps "Migrate Working Tree Edits" would be appropriate. 

Personally I think changing the behavior is the better solution, as I encounter many more instances of "oh I need to see what was done in that other branch real quick" vs "I'm on the wrong branch and should blindly migrate my edits to a different branch via a stash".

**Comment by lszomoru** [comment]
@joaomoreno, would love to get your thoughts on this one. Thank you!

**Comment by joaomoreno** [comment]
> Instead, VSCode attempts to apply the stash to the current working tree

Yeah that seems wrong. I think we should just remove the _pop after checkout_ behavior.

**Comment by lszomoru** [comment]
I have looked into this a bit further and I see that [the original label](https://github.com/microsoft/vscode/commit/ec084a25bd324087ccccb5c359829e409d6a5df1) for the action was "Smart Checkout". I do agree that if we were to use "Stash & Checkout" as the label, we should remove the code that pops the most recent stash.

**Comment by gjsjohnmurray** [comment]
Will this change of behaviour be obvious to someone who previously took advantage of how it used to conclude by popping the stash? Or should @humanoid2050's suggested "Migrate Working Tree Edits" button be added to the dialog?

**Comment by lszomoru** [comment]
Yes, this will a change in behaviour, though I would prefer not adding a third option to the dialog. @joaomoreno, thoughts?

**Comment by joaomoreno** [comment]
Up to you @lszomoru 👌

**Comment by lszomoru** [comment]
* I have added a button "Migrate Changes". Opted to use the "Changes" terminology to be consistent
* I have moved the "Force Checkout" button to the end so that it is not not the primary button in the dialog.

<img width="274" alt="image" src="https://user-images.githubusercontent.com/3372902/207871490-adbe1a92-a69b-45b9-b021-d104e9a46d8e.png">
