### ISSUE TITLE
[MacOS] Background color mismatch with dark theme

### ISSUE THREAD

**Issue by chinux23** [Microsoft/vscode#15998]
- VSCode Version: 1.7.2
- OS Version: Mac OS 10.12 (16A323)

Steps to Reproduce:

1. Download any dark theme 
2. activate dark theme

Here is a screenshot of the issue. The background is lighter than the actual background used for source code. I couldn't find any more information about this issue online. Any workaround? This is used to work but recent update seems to break it.

<img width="1762" alt="screen shot 2016-11-23 at 11 23 22 pm" src="https://cloud.githubusercontent.com/assets/387737/20586635/fbd80086-b1d3-11e6-8c72-d1514ba9fc3f.png">

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12473
