### ISSUE TITLE
Can't select suggested action by up or down key !

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode#159904]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.0 (system setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a simple c# dotnet console project in vscode, and copy below code:
``` C#
using System;

namespace TestCs
{
	class Program
	{
		static void Main(string[] args)
		{
			string dir = @"D:\LearnGameRepo\Lua";

			string[] files = Directory.GetFiles(dir, "*.c", SearchOption.TopDirectoryOnly);
			StringBuilder sb = new StringBuilder();


			Console.WriteLine("Run Finish!");
		}
	}
}
```
2. select `StringBuilder` and press down `Ctrl+.`, now vscode will show suggested actions, and i can't select a action by press down `up` or `down` key, like below:

![image](https://user-images.githubusercontent.com/8075421/188159384-ada5ba42-8a10-4793-920f-382ab21a92c8.png)

**Comment by mjbvz** [comment]
Hm, I can't reproduce this. Do you have any custom keybindings that could be interfering with this? Also, what keyboard layout are you using?

**Comment by KeithDC-SD** [comment]
Same here. Menu looked new. Was wondering if there was a way to bring the old menu back so maybe arrow keys would work again. I have not tried disabling plugins and not going to mess with my keybindings --- will simply just revert to using the mouse to select refactor options.

**Comment by KeithDC-SD** [comment]
I found the setting to revert the menu. Deselect the following preference:

> [ _ ] Editor: Use Custom Code Action Menu

**Comment by DFVSQY** [comment]
> I found the setting to revert the menu. Deselect the following preference:
> 
> > [ _ ] Editor: Use Custom Code Action Menu

Thanks for the setting.

**Comment by DFVSQY** [comment]
> Hm, I can't reproduce this. Do you have any custom keybindings that could be interfering with this? Also, what keyboard layout are you using?

It's so strange, i have do nothing, now it works well.

**Comment by DFVSQY** [comment]
> Hm, I can't reproduce this. Do you have any custom keybindings that could be interfering with this? Also, what keyboard layout are you using?

I think this question can be closed.

**Comment by mjbvz** [comment]
This sounds like a keybinding issue. The relevant commands are `selectNextCodeAction` and `selectPrevCodeAction`. If you're not seeing this working, try reconfiguring those keybindings
