### ISSUE TITLE
Renaming a gif does not update Markdown link

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#159999]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Have a gif file that is referenced as a relative link in a markdown file
2. Rename the gif from the file explorer
3. :bug: link text in markdown file is not updated, but link validation does warn that the link path is invalid

**Comment by mjbvz** [comment]
This feature is off by default. You can turn it on by setting:

```json
"markdown.experimental.updateLinksOnFileMove.enabled": "prompt"
```
