### ISSUE TITLE
Search stopped working

### ISSUE THREAD

**Issue by grapevinegizmos** [microsoft/vscode#159998]
Type: <b>Bug</b>

Routine usage of search stopped working.  
I searched in my code for the chars "getD" looking to find a function called getDocument.  As you can see it is open in the editor, but there are no search results.    Same result in search again all files. 

![image](https://user-images.githubusercontent.com/8684037/188282949-f1a27174-2ad3-49b4-b6e7-c4ff901084e6.png)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|22, 18, 14|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id a2566247-d7b6-4b99-a270-ab36a18a985b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
angular1-code-snippets|ale|0.0.3
ng-template|Ang|14.1.0
ruby-on-rails-snippets|ate|0.0.1
project-templates|can|1.2.0
solargraph|cas|0.23.0
vscode-ruby-test-adapter|con|0.9.1
vscode-protractor-snippets|dee|1.0.5
docs-images|doc|0.0.10
xml|Dot|2.5.1
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.8.0
copilot|Git|1.43.6621
remotehub|Git|0.42.0
vscode-pull-request-github|Git|0.50.0
vscode-jasmine-test-adapter|hbe|1.8.2
vscode-test-explorer|hbe|2.21.1
vscode-drawio|hed|1.6.4
generate-switch-case-for-enum-type|her|0.0.10
angular-bootstrap|her|4.0.9
rails-snippets|Hri|1.0.8
search-node-modules|jas|1.3.0
require-js|lic|0.1.33
linecounter|lyz|0.2.7
code-coverage|mar|1.8.6
code-beautifier|mic|2.3.3
ruby-rubocop|mis|0.8.6
vscode-edge-devtools|ms-|2.1.0
azure-account|ms-|0.11.1
remote-repositories|ms-|0.20.0
test-adapter-converter|ms-|0.1.6
vscode-typescript-next|ms-|4.9.20220902
vscode-paste-image|mus|1.0.4
hardhat-solidity|Nom|0.5.1
chai-snippets|nwh|0.1.0
ruby|reb|0.28.1
LiveServer|rit|5.7.9
autoimport|ste|1.5.4
vs-code-node-require|tgr|1.10.2
vscode-counter|uct|3.0.5
vscode-icons|vsc|11.16.0
vscode-ruby|win|0.28.0
JasmineSnippets|xab|1.0.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by IllusionMH** [comment]
Are you sure you don't have "Whole word" match enabled?

**Comment by grapevinegizmos** [comment]
See the illustration

**Comment by IllusionMH** [comment]
Try `*.sol` instead of just `.sol` in files to include

**Comment by grapevinegizmos** [comment]
![image](https://user-images.githubusercontent.com/8684037/188282745-ee60c2e4-e634-4f9c-8fbf-b06e43fca297.png)

**Comment by IllusionMH** [comment]
Strange. Are you sure that you don't have linebreak in search query? Look like it's multiline search at this moment

**Comment by grapevinegizmos** [comment]
Yeah, but I redownloaded the latest update and tried and again and it started working.  NO idea what that was all about but thanks.
