### ISSUE TITLE
editor.bracketPairColorization.independentColorPoolPerBracketType stopped working after update

### ISSUE THREAD

**Issue by jan-revay** [microsoft/vscode#159995]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Ubuntu 20.04, Linux x64 5.15.0-46-generic snap

Steps to Reproduce:

1. Start VSC (possibly with extensions disabled)
2. Open any C++ workspace or any folder with C++ files.
3. Set "editor.bracketPairColorization.independentColorPoolPerBracketType": true
4. Bracket pair colorization stopped working - all brackets are yellow regardless of the nesting level or bracket type.

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:10.472Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-46-generic snap
Sandboxed: No

**Comment by hediet** [comment]
This is weird, we didn't change anything there.
It works if you downgrade to the previous version of VS Code?

**Comment by vangoghcat** [comment]
Yse, I have met the same problem after updating to 1.71.0

**Comment by jtaina** [comment]
Same problem here on 1.71.0. on Windows 10.

**Comment by Geevo** [comment]
Same issue here with both typescript and html templates.... 
All brackets regardless of nesting are all yellow after auto-updating to 1.71.0

Reverting to 1.70.2 and restoring synced settings from 1wk ago resolved my issue.

**Comment by DreamSpawn** [comment]
On an interesting note for me at least, the bracket colors are all yellow, but if I enable the guide lines they have the correct color
![VSCode-bracket-colors](https://user-images.githubusercontent.com/6640479/189424232-859d8bfe-4f48-4dc0-a7bf-9723a6d9f7ff.png)

**Comment by mjdshibly** [comment]
I'm having the same issue... 
If I set `editor.bracketPairColorization.independentColorPoolPerBracketType` to `True` all brackets will always have the color defined for `editorBracketHighlight.foreground1` regardless of nesting.

**Comment by bbugh** [comment]
Turning on or off `editor.bracketPairColorization.independentColorPoolPerBracketType` doesn't make a difference for me, though it does change how the indentation is colored. I've messed around with `true`, `false`, `"active"`, setting different brackets, etc, nothing changes the outcome, all brackets are `editorBracketHighlight.foreground1`

<details>
<summary>"editor.bracketPairColorization.independentColorPoolPerBracketType": true</summary>

<img width="621" alt="image" src="https://user-images.githubusercontent.com/438465/190934188-6c323115-8e0f-4ed1-9d59-f6615a939efc.png">
</details>


<details>
<summary>"editor.bracketPairColorization.independentColorPoolPerBracketType": false</summary>

<img width="623" alt="image" src="https://user-images.githubusercontent.com/438465/190934159-1d40fe8d-8e09-4856-beed-9b21ce8f49b6.png">
</details>

**Comment by hediet** [comment]
Anyone up for a bugfix PR? 😉
Unfortunately, I was very busy with the merge editor this milestone.

**Comment by MALVAREZ84** [comment]
I have the same issue.

**Comment by keidarcy** [comment]
same problem in `Version: 1.72.2`

**Comment by hediet** [comment]
Sorry for the inconvenience. I fixed the bug and added some tests to prevent future regressions.

Verification steps:
![image](https://user-images.githubusercontent.com/2931520/197154447-a252c08e-d753-4329-a347-741de59d2234.png)

```
({[[(())]]})
```
