### ISSUE TITLE
Updates on Windows 7

### ISSUE THREAD

**Issue by oliwex** [microsoft/vscode#159996]
Updates on Windows 7

**Comment by gjsjohnmurray** [comment]
https://code.visualstudio.com/updates/v1_71#_windows-7-support-has-ended

**Comment by GitMensch** [comment]
You may want to possibly switch to vscodium once this is solved there https://github.com/VSCodium/vscodium/issues/1264 (also supports RHEL7 and other environments not supported any more "Visual Studio Code")...
