### ISSUE TITLE
enabled property of QuickPick is not working as intended

### ISSUE THREAD

**Issue by cheeze2000** [microsoft/vscode#159906]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Windows 11 Pro 21H2 22000.856

Steps to Reproduce:

1. Scaffold a new extension with `yo code`
2. Put this code in `extension.ts` inside the callback of the hello world command
```js
const qp = vscode.window.createQuickPick();
qp.enabled = false;
qp.show();
```
3. Hit F5
4. Run the Hello World command from the command palette
5. The documentation mentions if this property is false, the input field will be disabled. However, the input field is still usable.

**Comment by cheeze2000** [comment]
I just realised that the UI disabled all sort of mouse events but not keyboard events. Is this intended?

**Comment by TylerLeonhardt** [comment]
If you put the `qp.enabled` after the `qp.show()` does this work?

**Comment by cheeze2000** [comment]
> If you put the `qp.enabled` after the `qp.show()` does this work?

No, it does not.
