### ISSUE TITLE
sed -r shell integration error on OSX

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#159946]
See comments in https://github.com/microsoft/vscode/commit/e55863c5c1fc4515bd99e9cd4fb415788000a8b1

> sed -r doesn't work on OSX Catalina, I get an error at each command in the integrated terminal

Workaround for anyone hitting this is to set `HISTCONTROL` to one of `erasedups`, `ignoreboth`, `ignoredups` in your `~/.bashrc`.

**Comment by gjsjohnmurray** [comment]
See earlier report on https://github.com/microsoft/vscode/issues/159864
