### ISSUE TITLE
Line change highlight persists through git commit

### ISSUE THREAD

**Issue by ograycode** [Microsoft/vscode#15995]
**Problem**: The line highlight to show lines that changed persists through git commit. See http://zc.d.pr/spFD/1sEx17Pf

**Expected**: The line highlight disappears on commit -- this is the old behaviour and let me easily see what was changed since the last commit. The only way to make it disappear at the moment is to restart VSCode.

- VSCode Version: 1.8.0 insiders 731c1b034ed009991c29f9ccaf035c236458e3c6 2016-11-23T07:03:07.898Z
- OS Version: Mac OS X 10.11.4

Steps to Reproduce:

1.  Change a line
2.  Commit the change

**Comment by joaomoreno** [comment]
#16002
