### ISSUE TITLE
CSS syntax highlight error

### ISSUE THREAD

**Issue by nuintun** [Microsoft/vscode#15994]
- VSCode Version: 1.7.2
- OS Version: WIN10 1607

See screenshots:

![syntax-0](https://cloud.githubusercontent.com/assets/1730277/20584393/149c1ff4-b22d-11e6-950f-112f07c5ef42.png)
![syntax-1](https://cloud.githubusercontent.com/assets/1730277/20584394/1643523c-b22d-11e6-931e-340fce31a6d1.png)

**Comment by aeschli** [comment]
First problem is #3481, the second one is #7383
