### ISSUE TITLE
注释问题

### ISSUE THREAD

**Issue by holmewoo** [Microsoft/vscode#15999]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T15:27:10.246Z)
- OS Version: Darwin x64 16.1.0
- Extensions: 

Steps to Reproduce:

1.当我的js代码写在html文件中时，使用快捷键cmd+/去注释一段代码时，编辑器使用的注释方法还是html的方法，而不是js的//或者/**/的方法，这样是无效的。
2.虽然可以通过更改语言模式去解决，但是手动切换太麻烦了

**Comment by jrieken** [comment]
@holmewoo Please file issues in English

**Comment by Astray-git** [comment]
duplicate of #12969

**Comment by jrieken** [comment]
Thanks @Astray-git
