### ISSUE TITLE
ctrl+shift+j yields "Cannot read property 'openViewlet' of undefined"

### ISSUE THREAD

**Issue by rhbecker** [Microsoft/vscode#1599]
## explanation

The default keyboard shortcuts file contains:

```
{
  "key": "ctrl+shift+j",
  "command": "workbench.action.search.toggleQueryDetails",
  "when": "searchViewletVisible"
},
```

So, I tried it out, but got an error.

## repro

1. Open search view (via <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd> or mouse click).
2. Attempt to use shortcut <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>j</kbd>.
3. See error message: "Cannot read property 'openViewlet' of undefined".

## supporting info

* version: 0.10.5
* `--disable-extensions` didn't help
* no errors appear in the dev tools console

**Comment by bpasero** [comment]
@jrieken I can reproduce, somehow the viewletService is not defined in the command.

**Comment by jrieken** [comment]
Good catch!

**Comment by Roustalski** [comment]
When will this fix be released? Is there a pre-release or beta version we can grab, or another way of getting to the advanced query section?

**Comment by egamma** [comment]
@Roustalski this will be part of the January milestone (see the milestone attribute). If this isn't soon enough we can look into alternative ways to make it available :smile:
