### ISSUE TITLE
sourceFileMap when debugging externally built binary

### ISSUE THREAD

**Issue by lukaszgdula6** [microsoft/vscode#159951]
When debugging externally built binary (for example using attach on binary built on some server) paths of source files may not match paths in local project as workspaces may be different. It would be nice if we can have one of:
1) function which try to map path ignoring workspace part (i.e. matching backwards up to workspace part of path), or
2) some masks in sourceFileMap setting, so we could mask part of the path.

**Comment by weinand** [comment]
What debugger are you using?

**Comment by lukaszgdula6** [comment]
Default for Visual Studio (2017) on Windows.

**Comment by weinand** [comment]
This repository is for Visual Studio Code, and not for Visual Studio.

**Comment by lukaszgdula6** [comment]
Just thought it is VS Code responsibility to translate paths from pdb to current workspace (i.e. what sourceFileMap is for). Sorry!

**Comment by weinand** [comment]
@lukaszgdula6 May be I was confused but your statement "Default for Visual Studio (2017) on Windows."

- I was assuming that you are using "Visual Studio (2017)", correct?
- I don't understand the "Default". Neither Visual Studio nor Visual Studio Code have a default debugger. They might have a built-in debugger, but this is not a "default". So may be I should have asked "what language are you debugging?".

**Comment by lukaszgdula6** [comment]
I'm sorry for confusing response. I'm not an Windows/VS expert, I didn't apt get gdb or so - I just installed C++ section in Visual Studio 2017. It is not like they provide exe name or something in the installer, or give any choice... VS Code detected debugger itself without asking too... If you can guide me how to get actual debugger name for you I'll be more than happy to help. The only distinct thing I can see is "type": "cppvsdbg" in launch.json.

C++ of course.

The other thing I noticed is that when debug in VS it correctly map files. For example something like g:\a3423a\main.cpp is mapped to c:\myenv\main.cpp without any extra configuration. It woks both for stack walking and breakpoints setting. In VS Code I have to add entry sourceFileMap in my launch.json.
