### ISSUE TITLE
Incorrect license on RPM

### ISSUE THREAD

**Issue by jfearn** [Microsoft/vscode#15993]
- VSCode Version: 1.7.2-1479766213
- OS Version: el7

The license listed in the RPM is MIT, however the license link in the Help menu goes to https://code.visualstudio.com/license?lang=en 

The license in the spec file should be something like 'Microsoft Visual Studio Code License' ... unless you are deliberately re-licensing it for us, then just change the URL in the menu :P

**Comment by Tyriar** [comment]
I changed the license to read "Multiple, see https://code.visualstudio.com/license", similar to what Chrome does.
