### ISSUE TITLE
[f#] Block comment not colored as comment

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16]
Using the block comment in F# adds the following around 'samplesLabel':

``` F#
let mutable (*samplesLabel*) : System.Windows.Forms.Label = null
```

This is however not colored as a comment in VS Code.

**Comment by egamma** [comment]
@aeschli can you consult with the F# extension what should be done here, e.g., should we adopt the grammar from atom?

**Comment by aeschli** [comment]
We're using the grammar from https://github.com/ionide/ionide-fsharp.
Our grammar is up to date on version 1.4.11.

**Comment by aeschli** [comment]
Filed as https://github.com/ionide/ionide-fsharp/issues/186

**Comment by unional** [comment]
Seems like upstream is fixed 🌷 
https://github.com/ionide/ionide-atom-fsharp/issues/186#issuecomment-272727360

**Comment by aeschli** [comment]
I verified in 1.10-insiders that this got fixed in the meantime

**Comment by aeschli** [comment]
Comment is still not correctly colored. Closing this issue as it is tracked in ionide/ionide-atom-fsharp#186
