### ISSUE TITLE
Session dropdown menu is outside the visible view.

### ISSUE THREAD

**Issue by moalamri** [microsoft/vscode#160052]
Type: <b>Bug</b>

When I have more than one session running in debug, the dropdown menu that has `disconnect`, `stop` options is outside of the visible view and is pushed back of the editor area. Only a small portion of the dropdown menu is shown.
It doesn't matter what space I give the Side Bar; it always drops outside the visible side panel.

![ezgif-4-b1c72089b3](https://user-images.githubusercontent.com/964077/188340069-a99416b3-c420-48f8-9bc5-4ae53b6d0fa1.gif)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (5.46GB free)|
|Process Argv|--crash-reporter-id d50e185c-0bfc-44b6-9830-5d4a2c2c6978|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.25.0

</details>

**Comment by moalamri** [comment]
@weinand is it possible to add `bug` tag for better follow-up?

**Comment by weinand** [comment]
The assignee will do this.

**Comment by roblourens** [comment]
It works from the debug toolbar, right?

**Comment by moalamri** [comment]
Yes, the debug toolbar works just fine:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/964077/188996936-e138c5de-f230-454c-9332-1a442ea8e238.png">

**Comment by roblourens** [comment]
Sorry I'm actually not sure at what level the shadow dom is used or which widget you are looking for? The dropdown is inside this action view item https://github.com/microsoft/vscode/blob/d2114a401eb6dbe161ca447761758b06b6322dbc/src/vs/workbench/contrib/debug/browser/debugToolBar.ts#L282

**Comment by benibenj** [comment]
Closing as this has been fixed in the meantime
