### ISSUE TITLE
Git integration does not support `includeIf` directive with `hasconfig:remote.*.url:`

### ISSUE THREAD

**Issue by fletchto99** [microsoft/vscode#160002]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0 
- OS Version: Windows 11 21H2 (OS Build 22000.856)

Note: I've also tested on macOS and in GitHub codespaces, all with the latest vscode.

Steps to Reproduce:

1. Create a gitconfig setup that [uses remote URLs to include specific configurations](https://git-scm.com/docs/git-config#_example):

`~/.gitconfig`:
```properties
[user]
  name = My Name
  email = email@personal.com

# It is important the includeIf comes after the user configuration section
# so that the email in the work config is picked up as the email to use
[includeIf "hasconfig:remote.*.url:https://github.com/work_org/**"]
  path = .gitconfig_work

# SSH remote to cover all bases
[includeIf "hasconfig:remote.*.url:git@github.com:work_org/**"]
  path = .gitconfig_work
```

`~/.gitconfig_work`:

```properties
[user]
  email = email@work.com
```

2. Clone a repo and validate it matches the expected pattern, e.g. `git clone https://github.com/work_org/my_repo`. This can be validated with `git config --get remote.origin.url`

```bash
➜  github git:(master) git config --get remote.origin.url
https://github.com/work_org/some_repo
```

3. Observe that the email specified in the `.gitconfig_work` configuration is nowhere to be found:

```bash
➜  github git:(master) git config --get-all user.email 
email@personal.com
(END)
```

Expected result:

In `3` of `Steps to Reproduce` the expected output would be:

```bash
➜  github git:(master) git config --get-all user.email 
email@personal.com
email@work.com
(END)
```

**Comment by dscho** [comment]
Which `git` executable is this using? That sounds more like a Git problem than a VS Code problem to me (after all, your reproducer shows only Git commands, no VS Code involved).

**Comment by fletchto99** [comment]
Good call @dscho. Looks like it was indeed the git version. Locally my mac was on `2.35.1` and codespaces is running `2.30.2`. It appears that [`includeIf hasconfig:`](https://github.com/git/git/commit/399b198489a041e2842fb4b257bea5adb02d28d1) was added in git version `2.36.0`. After updating my macOS git version I can confirm this works locally as expected. Unfortunately codespaces seems to be locked into the `git` version of `ubuntu lts` so I'll see if I can figure out a solution for that.

Sorry for the noise!

**Comment by dscho** [comment]
> Unfortunately codespaces seems to be locked into the `git` version of `ubuntu lts` so I'll see if I can figure out a solution for that.

Have you tried adding [this PPA](https://launchpad.net/~git-core/+archive/ubuntu/ppa) and `apt-get`ing `git-core` from there? That should give you a current Git version even in an LTS version of Ubuntu.

**Comment by dscho** [comment]
For the record, @fletchto99 and I were chatting about this privately and figured out that the problem was due to a devcontainer definition that locks that particular Codespace to Debian 11 "Bullseye".

Running these commands in the integrated terminal of that Codespace will install Git v2.37.3:

```sh
git clone https://github.com/git/git .core-git &&
cd .core-git &&
git switch -d v2.37.3 &&
apt-get update &&
apt-get install git gcc make libssl-dev libcurl4-openssl-dev \
                     libexpat-dev tcl tk gettext git-email zlib1g-dev \
                     checkinstall &&
printf '%s\n' prefix=/usr gitexecdir=/usr/lib/git-core NO_TCLTK=1 >>config.mak &&
make -j8 &&
eval "$(tr -d ' ' <GIT-VERSION-FILE)" &&
checkinstall -y --pkgname=git --pkgversion=2:$GIT_VERSION --provides=git,\ git-man,\ git-email --replaces=git,\ git-man,\ git-email make -j8 install
```
