### ISSUE TITLE
Crash with large files + sandbox

### ISSUE THREAD

**Issue by cynecx** [microsoft/vscode#160040]
```
Version: 1.72.0-insider
Commit: c4722f1bb292284e0437eb7547808a5788fe6430
Date: 2022-09-02T05:17:54.919Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.6-arch1-1
Sandboxed: No
```

Steps to Reproduce:

1. Enable `window.experimental.useSandbox`.
2. Prepare a large text file (Citylots.json is ~190MB):

```sh
wget -O citylots.json "https://raw.githubusercontent.com/zemirco/sf-city-lots-json/master/citylots.json?raw=true"
cp citylots.json evenlarger.json
cat citylots.json citylots.json >> evenlarger.json
```

2. Open evenlarger.json in vscode.
3. vscode crashes.

Note: This also happens when I disable all extensions. However, the file loads just fine, when I disable the sandbox.

**Comment by deepak1556** [comment]
Unable to repro the issue with latest insiders https://code.visualstudio.com/insiders
