### ISSUE TITLE
Select on state.vscdb returning odd results

### ISSUE THREAD

**Issue by AxelGauffre** [microsoft/vscode#160009]
From a Typescript extension I am trying to query the state.vscdb of my workspace to see which regions are folded.

I get the following very strange behavior :
 1. The first time I call my command, no problem: It brings me the correct folded regions.
 2. Then, if I unfold or fold a region, then call the command, it brings me again the regions that were folded before the first call (from step 1).
 3. Then, if I change regions again, then call my command, it brings me the regions that were folded before the second call (from step 2).
 4. Then, if I change regions again, then call my command, it brings me the regions that were folded before the third call (from step 3).
 5. And so on.

Another strange behavior: When I unfold *all* regions, my command brings me nothing (which is normal), but when I fold some regions again, my command *continues* to bring me nothing, even when called repeatedly.

My code:

    import * as vscode from 'vscode';
    import { Database } from 'sqlite3';
    
    export function activate(context: vscode.ExtensionContext) {
    
        const sqlite3 = require('sqlite3').verbose();
    
        let disposable = vscode.commands.registerCommand(
            'axel.CountFolds',
            (pArg:string) => {
                //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
                //DB connection.
                    const dbFile = 'D:/Programmes/VS Code (portable)/' //<== I installed VS Code in portable mode.
                                    + 'data/user-data/User/workspaceStorage/'
                                    + '99cfdf4084eda620953c74c9bc25efd6' //<== My workspace.
                                    + '/state.vscdb'; //<== I am querying the sqlite db of VS Code itself.
                    let db = new sqlite3.Database(dbFile, (err: any) => {
                            if (err) {
                                vscode.window.showInformationMessage('DB connexion error => ' + err.message);
                                return
                            }
                        }
                    );
    
                //Select.
                    let sql = `SELECT value`
                            + ` FROM ItemTable`
                            + ` WHERE key = 'memento/workbench.editors.files.textFileEditor'`;
    
                    db.get(sql, (err: any, row: any) => {
                        if (err) {
                            vscode.window.showInformationMessage('Select error => ' + err.message);
                            //Deconnexion.
                                db.close((err:any) => {
                                    if (err) {
                                        vscode.window.showInformationMessage('DB close error => ' + err.message, { modal: true });
                                        return;
                                    }
                                });
                            return;
                        }
                        else if (row) {
                            try {
                                let jsonObject = JSON.parse(row.value);
                                let jsonString = '';
                                interface Fold {
                                    startLineNumber : number;
                                    endLineNumber : number;
                                }
                                let myRegions : Fold[];
                                myRegions = jsonObject.textEditorViewState[17][1][4].contributionsState["editor.contrib.folding"]["collapsedRegions"];
                                    jsonString = JSON.stringify(myRegions);
                                    vscode.window.showInformationMessage(jsonString);
                                let spy = '';
                                myRegions.forEach(function (pRegion, pIndex) {
                                    spy += `Region ${pIndex} : startLineNumber->${pRegion.startLineNumber}    endLineNumber->${pRegion.endLineNumber}` + `\n`;
                                });
                                vscode.window.showInformationMessage(spy, { modal: true });
                            }
                            catch(e) {
                            }
                        }
                        else {
                            vscode.window.showInformationMessage('Empty select.');
                        }
    
                        //Disconnection.
                            db.close((err:any) => {
                                if (err) {
                                    vscode.window.showInformationMessage('DB close error => ' + err.message, { modal: true });
                                    return;
                                }
                            });
                    });
                //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
            }
        );
        context.subscriptions.push(disposable); //???
    }
    
    export function deactivate() {}

**Comment by aeschli** [comment]
You are reading internal state. We don't recommend or support that.

Please file a feature request for an API that give access to the folded ranges. Please describe your use case.
