### ISSUE TITLE
"Ctrl + `" does not open/focus the terminal in VsCode Insiders after the update

### ISSUE THREAD

**Issue by DavudSafarli** [microsoft/vscode#160069]
Type: <b>Bug</b>

After verifying that I have the default keybinding for "Ctrl + `" shortcut as below:
```json
{
  "key": "ctrl+`",
  "command": "workbench.action.terminal.toggleTerminal",
  "when": "terminal.active"
}
```
the shortcut still does not work correctly when the terminal is out of the focus after the last 1.72 update.

To Reproduce:
Open the VsCode Insiders
Open a new page
Make the cursor focus on some text on the editor
Press the _Ctrl + `_ shortcut.

Expected behaviour:
Terminal should be opened and focused

Current Behaviour:
Nothing happens

VS Code version: Code - Insiders 1.72.0-insider (c4722f1bb292284e0437eb7547808a5788fe6430, 2022-09-02T05:17:54.919Z)
OS version: Linux x64 5.15.0-47-generic snap
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|4, 2, 1|
|Memory (System)|36.94GB (30.36GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id d139f61d-199f-4f48-a12a-aa0da5cd217b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
terraform|4op|0.2.5
vscode-sql-formatter|adp|1.4.4
gitlens|eam|12.2.1
RunOnSave|eme|0.2.0
go|gol|0.35.2
vscode-docker|ms-|1.22.1
remote-containers|ms-|0.252.0
makefile-tools|ms-|0.6.0
vscode-input-sequence|tom|0.2.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by ArturoDent** [comment]
You should try and report what vscode sees when you Ctrl+\` with the `Developer: Toggle Keyboard Shortcuts Troubleshooting` command.

**Comment by DavudSafarli** [comment]
closing the issue as it no longer happens
