### ISSUE TITLE
Visual Studio Code has crashed

### ISSUE THREAD

**Issue by liril-net** [Microsoft/vscode#1600]
> We are sorry for the inconvenience! Please restart Visual Studio Code.

I have updated my vscode today, and i can't launch it any more. So i download one from Microsoft, and then i get this message every time i open vscode, i have re-download it again and nothing works, i wanna know what should i do?
![screenshot 2015-12-23 at 10 16 35](https://cloud.githubusercontent.com/assets/16029685/11970000/46e9a07c-a95e-11e5-93bf-f762ea6a46d7.png)

**Comment by isaosao** [comment]
Yes, same as me, latest one has crashed. please provide previous version for downloading!!!!!!!

**Comment by isaosao** [comment]
the update hurts my work!!!!! crashed!!!

**Comment by isaosao** [comment]
do you solve it?

**Comment by liril-net** [comment]
Change my keyboard as US help me to solve it.

**Comment by liril-net** [comment]
You can get more help at #1463 .
