### ISSUE TITLE
Infinite FileWatcher start->crash loop

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16009]
Testing on windows 7 and after opening a folder I see an endless loop of the FileWatcher process crashing and starting. This is how it reproduces

* win7 VM 
* open VS Code
* open a folder that is shared from the mac (Mac Desktop in my case)
* 🐛 open dev tools, see endless errors about the file watcher crashing

![nov-24-2016 10-37-08](https://cloud.githubusercontent.com/assets/1794099/20593369/6b8cc7c8-b232-11e6-8aa6-8f69af2457e4.gif)

**Comment by bpasero** [comment]
@jrieken not seeing this on my Windows 7. Can you run `winver.exe` to see the version and SP status:

![image](https://cloud.githubusercontent.com/assets/900690/20594180/7e32ae9e-b235-11e6-8803-a6299f5917f1.png)

When you try to run `CodeHelper.exe` from the command line do you get an error? In my case I can:
* cd into `C:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\files\node\watcher\win32`
* run `CodeHelper.exe Y:\Desktop\test-ts`

=> Y points to my user folder on Mac and `test-ts` is just a default generated extension
=> I do not see an error

**Comment by bpasero** [comment]
Though it is true that upon termination of the watcher we just restart without having an upper limit. We should add one in the same way we have it for Chokidar.

**Comment by jrieken** [comment]
same - ![screen shot 2016-11-24 at 11 07 05](https://cloud.githubusercontent.com/assets/1794099/20594345/279a1d64-b236-11e6-99c7-c5e8ec5b9caa.png)

also happens with a local folder from the `c`-drive

misses something from dot net

![screen shot 2016-11-24 at 11 10 04](https://cloud.githubusercontent.com/assets/1794099/20594450/97f84586-b236-11e6-93c1-8657213e5dad.png)

**Comment by jrieken** [comment]
So, for once should eventually stop retrying and could also let the user know that we depend on something we couldn't find on his system.

**Comment by bpasero** [comment]
I do [inform](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/files/electron-browser/fileService.ts#L96) the user when .NET 4.5 is missing and I wonder why you are not being detected as one of those clients. 

I guess in your case .NET decides to open a dialog instead of throwing an error that I can read. I am not sure I can detect that case when some UI pops up...
