### ISSUE TITLE
A bad user experience. the Debug action panel cover the file tab if we opened lots of file

### ISSUE THREAD

**Issue by tingtien** [Microsoft/vscode#16007]
- VSCode Version:10.11.6
- OS Version:1.7.2 

Open lots of the file tab and start the Debug, The Debug action panel cover the file tab.  Although we drag the Debug action panel, But it also cover the other file tab. we don't want  repeat drag the panel.

![1124](https://cloud.githubusercontent.com/assets/5448557/20592994/6fc67d6e-b26b-11e6-974b-78820d1e9c11.jpg)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2513
If that is the use case try to move it in the viewlet area all the way to the left
