### ISSUE TITLE
TypeScript: rendered markdown base uri should be relative to defining file

### ISSUE THREAD

**Issue by DingWeizhe** [microsoft/vscode#160018]
- TypeScript issue
https://github.com/microsoft/TypeScript/issues/50665

- VS Code Version:
commit 389938998fa2ca900f9730839c2ee8c90ae0a68c

- OS Version:
macOS Monterey 12.5.1 (Apple M1)

Steps to Reproduce:

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/6461899/188301826-27730bfe-df9a-4ab5-a009-f5c01888b569.png">

Completions: 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/6461899/188301832-130e0880-5561-4813-9d88-0ba491a178ad.png">

Hover widget: 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/6461899/188301834-957c0455-eedd-496e-907e-0f59861b96ee.png">

In the current B's link, the content in the markdown previewer will be <root_of_project>/b.ts
But it should be <root_of_project>/folder/b.ts(relative to folder/A.ts)

**Comment by DingWeizhe** [comment]
relation issues: https://github.com/microsoft/vscode/issues/86564

**Comment by DingWeizhe** [comment]
I am creating a typescript issue for the response file path field when executing any command with documentation field.

**Comment by mjbvz** [comment]
Closing this in favor of the upstream issue: https://github.com/microsoft/TypeScript/issues/47718
