### ISSUE TITLE
Debugging "Run: script dev" works no more

### ISSUE THREAD

**Issue by mcoulont** [microsoft/vscode#160093]
Type: <b>Bug</b>

Hello

I use Visual Studio's Node debugger on a website on the MEAN stack (Typescript on server side, Angular 2 on client side).

I was used to see VS terminal open when I "Run: script dev" and see the logs scroll in it.

Since yesterday, running the debugger makes nothing happen in the terminal.

I've tried to:
- reboot VS
- reboot the laptop
- remove, autoremove, purge and reinstall VS But the problem remains.

However it still works on my back-up laptop (with the same project content).

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:10.472Z)
OS version: Linux x64 5.15.0-47-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11390H @ 3.40GHz (8 x 4281)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|15.38GB (11.36GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id f9f9a414-d545-45e2-b960-dd3af3043c87|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by Stoyz** [comment]
I am not able to run the dev script too but I am connecting to a VS Code Remote instance through SSH.

**Comment by mcoulont** [comment]
Must I downgrade meanwhile?

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/159881
