### ISSUE TITLE
[Emmet] 'emmet.action.expandAbbreviation' command broken in 1.71.0

### ISSUE THREAD

**Issue by Eurkidu** [microsoft/vscode#160059]
Type: <b>Bug</b>

After updating to 1.7.10, using the 'emmet.action.expandAbbreviation' command does not expand correctly

But it can be expanded correctly in the pop-up input prompt.

This also leads to the incorrect expansion of expressions using shortcut keys

I'm guessing the issue might be related to this commit

https://github.com/microsoft/vscode/pull/157035

![emmet](https://user-images.githubusercontent.com/13271070/188382396-54058756-9b0a-4360-a917-e9fdb5dc9b66.gif)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--disable-extensions --crash-reporter-id 2a58a493-15ea-4924-bafa-118c8fc086c6 --crash-reporter-id 2a58a493-15ea-4924-bafa-118c8fc086c6|
|Screen Reader|no|
|VM|18%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by altbdoor** [comment]
Ditto, happening to me too on Windows 10, VSCode 1.71.0

```
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
```

**Comment by blakewatson** [comment]
Same.

Type: <b>Bug</b>

1. Create an HTML document.
2. Add a head and body.
3. Type a valid Emmet string such as `div>p`.
4. Use the command palette (or keyboard shortcut) to expand the abbreviation.
5. Observe that nothing happens.

Here’s my full test code. I attempted it in a new tab with language set to HTML:

```html
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8" />
    <title>Test</title>
  </head>
  
  <body>
    div>p
  </body>
  
</html>
```

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Ultra (20 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 6, 5|
|Memory (System)|64.00GB (0.06GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id f5484c7d-7e52-4b93-9986-35d0ecb7bb4a|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
prettier-vscode|esb|9.8.0
font-switcher|eva|4.1.0
vscode-graphql|Gra|0.7.4
vscode-graphql-syntax|Gra|1.0.4
vscode-darklight|Iro|0.1.3
theme-karyfoundation-themes|kar|27.2.3
vetur|oct|0.36.0
rewrap|stk|1.16.3
tabnine-vscode|Tab|3.6.14
gitblame|wad|9.0.1

(12 theme extensions excluded)

</details>

**Comment by rzhao271** [comment]
Mitigation: set the `emmet.triggerExpansionOnTab` setting to true in User settings.

**Comment by rzhao271** [comment]
Verification steps:
1. Set `emmet.triggerExpansionOnTab` to false.
2. Run through the steps in https://github.com/microsoft/vscode/issues/160059#issuecomment-1237436065.

**Comment by pushqrdx** [comment]
I can confirm that this also broke my extension [`inline-html`](https://marketplace.visualstudio.com/items?itemName=pushqrdx.inline-html) which relied on executing the `emmet.action.expandAbbreviation` command to function
