### ISSUE TITLE
Cap number of sticky scroll lines (esp inside peek view)

### ISSUE THREAD

**Issue by MatteoGauthier** [microsoft/vscode#160074]
Type: <b>Bug</b>

When I check git diff directly in the vscode editor, the sticky scroll is enabled, and it's overlap the content of the peek view

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 6, 6|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id abed5057-1cf3-418c-9b06-4d1438cc4e87|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vite|ant|0.2.5
vscode-custom-css|be5|7.1.0
vscode-tailwindcss|bra|0.8.6
vscode-toggle-quotes|Bri|0.3.6
turbo-console-log|Cha|2.5.1
vscode-eslint|dba|2.2.6
vscode-styled-jsx-languageserver|Div|1.3.1
vscode-styled-jsx-syntax|Div|1.3.1
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.2.1
prettier-vscode|esb|9.8.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.50.0
go|gol|0.35.2
vscode-graphql-syntax|Gra|1.0.4
todo-tree|Gru|0.0.215
vue-snippets|hol|1.0.4
vscode-peacock|joh|4.2.0
dotenv|mik|1.0.1
zeit-co-vscode-schemas|ph1|0.1.2
prisma|Pri|4.3.1
json-schema-2020-validation|pro|0.0.5
nextjs-snippets|Pul|0.0.5
vscode-yaml|red|1.10.1
vscode-javascript-booster|sbu|14.0.1
sass-indented|syl|1.8.22
vscodeintellicode|Vis|1.2.24
vscode-icons|vsc|11.16.0
fig|wit|0.0.6
glean|wix|5.2.2
markdown-pdf|yza|1.4.4
html-css-class-completion|Zig|1.20.0

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by jrieken** [comment]
Yeah, I like that

**Comment by r3m0t** [comment]
All the peeks (peek definition, diff margin, etc) would need to be resized to consider how much sticky scroll is present at the peeking location. I opened another issue for this #163058 with another case.

**Comment by Hacksore** [comment]
My take is we should be able to opt in or out of showing them in the peek views.

If you look at my scenario I wanted to instantly know what the change was here. However, since the sticky scroll is in the peek view that requires a bit of scrolling and blocks a significant amount of information I get from the diff. 

![image](https://user-images.githubusercontent.com/996134/195997811-9d23bb02-84eb-4c05-a333-b0cc5d58592d.png)

I do think that @maxime4000's solution to limit the amount rows it shows could help but personally I don't want to see them in diffs as to me they seem less useful there.

Perhaps something like a checkbox to allow or disallow it?
![image](https://user-images.githubusercontent.com/996134/195998036-d03e4391-7209-4102-aa2c-30652a8fce77.png)

**Comment by tusharsnn** [comment]
> Perhaps something like a checkbox to allow or disallow it?
> ![](https://user-images.githubusercontent.com/996134/195998036-d03e4391-7209-4102-aa2c-30652a8fce77.png)

Also, it should remember its state from last time.

**Comment by jrieken** [comment]
Adding to December and going to make sure the number of sticky lines isn't never more X times the number of visible lines (X < 1)

**Comment by tusharsnn** [comment]
> Adding to December and going to make sure the number of sticky lines isn't never more X times the number of visible lines (X < 1)

Will it be a 'peek' specific option or sticky scroll in general,

**Comment by jrieken** [comment]
To verify:

* enable sticky scroll
* resize the editor (work best with peek but any editor does)
* make sure sticky scroll lines are never more than a quarter of the editor line (space)
