### ISSUE TITLE
Option to disable new Code Action control

### ISSUE THREAD

**Issue by lonix1** [microsoft/vscode#160083]
The latest update 1.71 introduced the [Code Action control](https://code.visualstudio.com/updates/v1_71#_new-code-action-control).

I'm using C#, and unlike JS/TS, that new popup has a single menu called "More Actions..." and everything is under there. There is no separation of items at all.

So for C# users, it takes space and adds visual noise.

You said:
> Going forward, the new code action UI provides a great foundation for further UX improvements. Be sure to let us know if you have any suggestions!

For those of us not working in JS/TS, please give us the old popup's UI, which was a simple menu without colours or icons. Please add a config option similar to: `"editor.codeaction.enabled" : false`. Thanks.

**Comment by mjbvz** [comment]
This sounds like an issue with the C# extension not tagging code actions properly

Please file feature requests for any issues. However we have removed the old menus in insiders already  and don’t plan on maintaining two UIs going forward
