### ISSUE TITLE
Safari not properly rendering Terminal after page reload

### ISSUE THREAD

**Issue by benz0li** [microsoft/vscode#160070]
Does this issue occur when all extensions are disabled?: Yes/No
👉 Not relevant.

- VS Code Version: 1.71.0, 784b0177c56c607789f9638da7b6bf3230d47a8c, x64
- OS Version: Debian 11 (bullseye)

Steps to Reproduce:

1. Open codespace in browser
1. Open Terminal
    - Safari falls back to the DOM render, as canvas can not be loaded [and WebGL is ~~not supported~~ disabled for Safari by VS Code].
1. Reload page
    👉 An artefact is overlaying the output in the Terminal.  
    <img width="930" alt="1 71 0-reload" src="https://user-images.githubusercontent.com/20233085/188412261-cb07e875-a1e4-4ca8-860b-39410541cb3c.png">

Everything works fine with Firefox as it uses the WebGL renderer.

**Comment by benz0li** [comment]
Workaround for Safari: Disable Gpu Acceleration

### Settings

<img width="450" alt="safari_workaround" src="https://user-images.githubusercontent.com/20233085/188303250-3927b7e8-7675-40ea-9251-22723062bfe6.png">

### Settings (JSON)

```json
"terminal.integrated.gpuAcceleration": "off"
```

**Comment by benz0li** [comment]
@meganrogge @Tyriar Has the time come to enable WebGL for Safari?

```diff
diff --git a/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts b/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts
index b27a4b3e847..863892baee8 100644
--- a/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts
+++ b/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts
@@ -282,7 +282,7 @@ export class XtermTerminal extends DisposableStore implements IXtermTerminal, II
        }
 
        private _shouldLoadWebgl(): boolean {
-               return !isSafari && (this._configHelper.config.gpuAcceleration === 'auto' && XtermTerminal._suggestedRendererType === undefined) || this._configHelper.config.gpuAcceleration === 'on';
+               return (this._configHelper.config.gpuAcceleration === 'auto' && XtermTerminal._suggestedRendererType === undefined) || this._configHelper.config.gpuAcceleration === 'on';
        }
 
        private _shouldLoadCanvas(): boolean {
```

Cross reference: https://github.com/xtermjs/xterm.js/issues/3357#issuecomment-927986599

**Comment by jeanp413** [comment]
Created a PR fixing it https://github.com/microsoft/vscode/pull/160144

**Comment by Tyriar** [comment]
The webgl renderer would probably have the same problem if it's related to `device-pixel-content-box` as it also uses it. I believe the addon works in Safari now, but it used to show a completely empty canvas, bricking the terminal so we should probably wait a little longer.

**Comment by Tyriar** [comment]
Upstream PR: https://github.com/xtermjs/xterm.js/pull/4105
