### ISSUE TITLE
Review built-in extensions

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#160091]
Let's review all the built in extensions that we have and consider if they really need to be shipped with VS Code

- [ ] coffeescript
- [ ] configuration-editing
- [ ] cpp
- [ ] csharp
- [ ] css
- [ ] css-language-features
- [ ] dart
- [ ] debug-auto-launch
- [ ] debug-server-ready
- [ ] diff
- [ ] docker
- [ ] emmet
- [ ] extension-editing
- [ ] fsharp
- [ ] git
- [ ] git-base
- [ ] github
- [ ] github-authentication
- [ ] go
- [ ] groovy
- [ ] gulp
- [ ] handlebars
- [ ] hlsl
- [ ] html
- [ ] html-language-features
- [ ] image-preview
- [ ] ini
- [ ] ipynb
- [ ] jake
- [ ] java
- [ ] javascript
- [ ] json
- [ ] json-language-features
- [ ] julia
- [ ] latex
- [ ] less
- [ ] log
- [ ] lua
- [ ] make
- [ ] markdown-basics
- [ ] markdown-language-features
- [ ] markdown-math
- [ ] merge-conflict
- [ ] microsoft-authentication
- [ ] notebook-renderers
- [ ] npm
- [ ] objective-c
- [ ] perl
- [ ] php
- [ ] php-language-features
- [ ] powershell
- [ ] pug
- [ ] python
- [ ] r
- [ ] razor
- [ ] references-view
- [ ] restructuredtext
- [ ] ruby
- [ ] rust
- [ ] scss
- [ ] search-result
- [ ] shaderlab
- [ ] shellscript
- [ ] simple-browser
- [ ] sql
- [ ] swift
- [ ] theme-abyss
- [ ] theme-defaults
- [ ] theme-kimbie-dark
- [ ] theme-monokai
- [ ] theme-monokai-dimmed
- [ ] theme-quietlight
- [ ] theme-red
- [ ] theme-seti
- [ ] theme-solarized-dark
- [ ] theme-solarized-light
- [ ] theme-tomorrow-night-blue
- [ ] types
- [ ] typescript-basics
- [ ] typescript-language-features
- [ ] vb
- [ ] vscode-api-tests
- [ ] vscode-colorize-tests
- [ ] vscode-notebook-tests
- [ ] vscode-test-resolver
- [ ] xml
- [ ] yaml

Extensions which can be moved out

- [ ] grunt - needs an owner

Moving out an extension requires
- [ ] Creating a new repo using https://repos.opensource.microsoft.com/
- [ ] Take the extension out of VS Code source and move it to the newly created repo
- [ ] Onboard new repo to our pipeline https://github.com/microsoft/vscode-engineering/wiki/Extensions-Build-and-Publish
- [ ] Consider if the extension should be marked as deprecated

Idea by @joaomoreno

**Comment by pgfearo** [comment]
Why is `xsl`  (XSLT) not listed here?

**Comment by isidorn** [comment]
@pgfearo this is not a final list. If xsl is a built in extension then we will add it to the list. It might be a part of some other built in extension?

**Comment by pgfearo** [comment]
@isidorn ok, I understand now, 'xsl' is I believe part of the 'xml' built-in instruction.

**Comment by isidorn** [comment]
After more discussion with @joaomoreno we decided to not yet do this work. Thus closing until we find time to review in the future.
