### ISSUE TITLE
Greek letters phi and varphi reverted in source and view

### ISSUE THREAD

**Issue by goessner** [Microsoft/vscode#16008]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Ver. 1607

Steps to Reproduce:

1. Place greek letters ϕ (/phi) and φ (/varphi) in html or markdown source.
2. Notice them reverted in preview or any browser.

**Comment by jrieken** [comment]
I see this and according to [wikipedia](https://en.wikipedia.org/wiki/Phi) that is a valid representation


![screen shot 2016-11-24 at 11 36 28](https://cloud.githubusercontent.com/assets/1794099/20595468/4273c4ce-b23a-11e6-9328-ec0975cccd1e.png)

**Comment by goessner** [comment]
hmm .. strange. I did copy my previous post and see what you saw .. but then ...

![grafik](https://cloud.githubusercontent.com/assets/4902746/20596977/6fc0cb6e-b241-11e6-8a37-d1329e2110e4.png)

I should mention, that I am using a German vscode.

**Comment by jrieken** [comment]
This should be independent of the locale but surely depends on the font. I am using `Fira Code` which seems to get it right.

**Comment by goessner** [comment]
That effect being dependent on the font sounds reasonable. As I'm happy with the default fonts I am also able to live with that small quirk ... thanks.

**Comment by jrieken** [comment]
Ok - closing in that case. Thanks for getting back to us. Happy Coding!
