### ISSUE TITLE
Can't jump to file by click path in error stack in the console.

### ISSUE THREAD

**Issue by liuyanjie** [Microsoft/vscode#16000]
- VSCode Version: 1.7.2
- OS Version: Windows 7 64bit
- lanch type: node2

Steps to Reproduce:

1. Configure and use `babel` in develop environment
2. `throw new Error('message')` 

Can't open file "...": Can't find file (...).
![image](https://cloud.githubusercontent.com/assets/5998826/20589026/84d897f8-b254-11e6-9b95-2e47ac5b4d0c.png)

![image](https://cloud.githubusercontent.com/assets/5998826/20589018/7c86da38-b254-11e6-8118-b10183898719.png)

The path don't contain “disk symbol” `x`, it can be see throw the underline in the second picture.
Because it can't correctly identify path in `at _callee$ (...)` like
```
at _callee$ (x:/git/nodejs/cms/src/app_server/controllers/api.admin.js:10:9)
```

**Comment by dbaeumer** [comment]
Looks like debugging (launch type node2)

**Comment by isidorn** [comment]
@liuyanjie can you please try this with the latest vscode insiders @felixfbecker has improved this experience
@felixfbecker you are becoming a rock start everyone is hitting this issue
