### ISSUE TITLE
Terminal cursor blinks on Windows when typing

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#160184]
I noticed a blinking which doesn't happen in some other terminals like Windows Terminal. This happens for all `terminal.integration.gpuAcceleration` values:

![Recording 2022-09-06 at 06 41 11](https://user-images.githubusercontent.com/2193314/188650350-1951cb3b-67bf-48d4-9e54-e9eccf5720a0.gif)

Might be because we respect hiding the cursor immediately or https://github.com/xtermjs/xterm.js/issues/4082?

Version: 1.72.0-insider (user setup)
Commit: c4722f1bb292284e0437eb7547808a5788fe6430
Date: 2022-09-02T05:17:36.744Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

**Comment by meganrogge** [comment]
doesn't happen on the xtermjs.org demo on windows for me

**Comment by Tyriar** [comment]
Cannot repro anymore
