### ISSUE TITLE
Command for writing text inside the editor

### ISSUE THREAD

**Issue by fabiospampinato** [microsoft/vscode#160120]
It would be useful to have a command for writing text inside the editor. Something like `workbench.action.terminal.sendSequence`, but for the editor.

If there is one already I can't find it.

**Comment by ArturoDent** [comment]
You can either make a snippet or a keybinding like this:

```jsonc
  {
    "key": "alt+z",
    "command": "type",
    "args": {
      "text": "some text here "
    }
  }
```

**Comment by fabiospampinato** [comment]
Awesome, thank you!
