### ISSUE TITLE
[folding] Folded folding ranges should be displayed on the minimap with darkened background

### ISSUE THREAD

**Issue by iliazeus** [microsoft/vscode#160162]
When folded, folding ranges are displayed in the editor as a single line with darkened background. Hovever (as of `1.70.2`), on the minimap, the background of this line is not darkened. This makes it harder to navigate using the minimap.

![image](https://user-images.githubusercontent.com/12034832/188601474-9ab7e6fb-5ed3-400f-a1a4-a5cb7360df7b.png)

**Comment by jrieken** [comment]
Either this isn't working or steps are non trivial

**Comment by jrieken** [comment]
Ok, see this working unless I have render characters enabled
