### ISSUE TITLE
Improve vscode window manager

### ISSUE THREAD

**Issue by cveld** [microsoft/vscode#160153]
In relation to https://github.com/microsoft/vscode/issues/51710 I would like to see better means to differentiate multiple vscode windows.

Occasionally I have a situation like this:

![image](https://user-images.githubusercontent.com/6196260/188588359-4e24a467-9b64-4d82-80f3-7945a1e16490.png)

It would be great to have some avatar icon per window.

Additionally, some vscode windows work in tandem, i.e. one window fullscreen on desktop 1, the other on desktop 2. It would be great to bring such grouped windows to front more easily. (Windows 11 only supports grouping windows on the same screen)

Lastly, I think it would be great to have some comparable improvements to the switch window feature.
E.g. occasionally I have this situation:

![image](https://user-images.githubusercontent.com/6196260/188592362-b5773239-a6c5-473f-99bf-9f5bf81e0762.png)

* Make it available through a click on an icon in the title bar or status bar
* I believe displaying the label "(workspace)" does not always add value
* Why is the suffix "Visual Studio Code" always displayed?
* include groups and avatar icons
* hotkeys
* Windows 11 taskbar integration. maybe the first tile should always pop up a tiled view of all vscode (grouped) windows. With two clicks you then can arrive at the desired spot

**Comment by sbatten** [comment]
Thanks for the issue @cveld. There is a lot to unpack here and I think a lot of this is something that an OS is responsible for, not an app specific issue. However, something I can answer immediately is that Visual Studio Code is always displayed here because that is part of the window title and this can be configured with `window.title` in settings.

**Comment by sbatten** [comment]
cc @bpasero

**Comment by bpasero** [comment]
Our guidelines require you to file 1 issue and not N, so I suggest to split this issue up into 1 issue per actual issue.
