### ISSUE TITLE
package.json problems

### ISSUE THREAD

**Issue by wiliamsagala01** [microsoft/vscode#160114]
Type: <b>Bug</b>

packet.json  warning Problems loading reference 'http://json.schemastore.org/package': Unable to load schema from 'http://json.schemastore.org/package': getaddrinfo ENOTFOUND json.schemastore.org.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|3.75GB (0.36GB free)|
|Process Argv|. --crash-reporter-id fdddcfa2-ccaa-415e-bbf5-4e58550758c4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.2
postcss|css|1.0.9
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.3.1
prettier-vscode|esb|9.8.0
auto-rename-tag|for|0.1.10
live-sass|gle|5.5.1
mayukaithemevsc|Gul|3.2.3
vsc-python-indent|Kev|1.17.0
vscode-language-babel|mgm|0.0.36
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
live-server|ms-|0.4.0
vscode-typescript-next|ms-|4.9.20220904
material-icon-theme|PKi|4.20.0
LiveServer|rit|5.7.9
sass-indented|syl|1.8.22
vscode-icons|vsc|11.16.0
JavaScriptSnippets|xab|1.8.0
php-debug|xde|1.28.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by aeschli** [comment]
Maybe you were offline? Is http://json.schemastore.org/package accessible in a web browser?
