### ISSUE TITLE
Allow sticky scroll/breadcrumb to show additional items without having to include them in Go-to-Symbol-in-Editor

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#160106]
Sometimes it would be useful to include items in breadcrumb/sticky scroll that do not work well in flat lists like Go-to-Symbol-in-Editor.

For example, in this React code, it would be useful to see `PhotoContextProvider` -> `HashRouter` -> `Switch` in the breadcrumb and sticky scroll:

<img width="755" alt="Screenshot 2022-09-05 at 15 57 55" src="https://user-images.githubusercontent.com/1078012/188477111-2431d410-1832-4211-bf11-9425f0989315.png">

Current when scrolled, you don't see any of the hierarchy:

<img width="525" alt="Screenshot 2022-09-05 at 16 02 17" src="https://user-images.githubusercontent.com/1078012/188477524-11e679e4-b5b1-4c44-a597-219d19adcfbf.png">

It would not be so good to include all of these `Route`s in the normal flat document symbol list though, so it would be nice if document symbols had some kind of flag (presentation hint?) that specifies whether they should show only in hierarchical views (or, more specifically, control whether they show in breadcrumb/sticky scroll/outline).

**Comment by jrieken** [comment]
> It would not be so good to include all of these Routes in the normal flat document symbol list though

I am no react expert but why would not want to seem them in the quick outline list? Is there type any special?

**Comment by DanTup** [comment]
@jrieken well, it just seemed like the list would be huge and full of dupes. I was going to say it would be like including every html tag in a document in the list, although I just noticed that is actually the case today:

<img width="525" alt="Screenshot 2022-09-06 at 09 38 19" src="https://user-images.githubusercontent.com/1078012/188588589-a0a1a95e-73d2-4939-85ce-06f6a02bb7ba.png">

That seems a little excessive and hard to find what you're looking for (at least if you're not looking for something very specific and just scanning the list), although if it's always been this way and others find it helpful perhaps that's not an opinion shared by others.
