### ISSUE TITLE
Accented letters duplicated when typing next character

### ISSUE THREAD

**Issue by kube** [Microsoft/vscode#16017]
- VSCode Version: **1.8.0-insider** 6a6ab1fc5e58227b56ffc3e5bea9951e5565c314
- OS Version: **macOS 10.12.1**

![output](https://cloud.githubusercontent.com/assets/2991143/20596299/1f7979c4-b23e-11e6-881c-e45fc1d19281.gif)

This error seems to appears on VSCode Insiders only, VSCode 1.7.2 does not reproduce this behaviour.

I have a French Keyboard, mapped with `U.S International - PC`.

### Steps to Reproduce:

1. Begin typing an accent (e.g. `Alt` + `E` to begin a acute)
2. Type the letter you want to put accent on
3. Type a next character
4. Accented letter is now duplicated.

> This does not happen when using the macOS accented letters box by pressing the letter during a certain time. But it's slower.

**Comment by satokaz** [comment]
looks like the same problem #15765

**Comment by rebornix** [comment]
Dup of #15765 . They share the same root cause, using enter to choose words will trigger the additional addition of words.
