### ISSUE TITLE
Line breaks within argument brackets result in invalid for bracket pairs

### ISSUE THREAD

**Issue by yamachu** [microsoft/vscode#160115]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0-insider (Universal) d17726fe4beae5abe87ba9e9429cd298be8b53c4, 1.71.0 (Universal) 784b0177c56c607789f9638da7b6bf3230d47a8c
- OS Version: macOS 12.5.1

Steps to Reproduce:

1. Write TypeScript code like `code: 1`

code: 1
```ts
const myToString = (
    _: unknown
): {
    toString: Pick<string, 'toString'>;
} => {
    return { toString: () => '' };
};
```

TokenType

```
>;

textmate scopes	meta.object-literal.key.ts
meta.object.member.ts
meta.objectliteral.ts
meta.var.expr.ts
source.ts
foreground	No theme selector

}·=>·{

textmate scopes	meta.object-literal.key.ts
meta.object.member.ts
meta.objectliteral.ts
meta.var.expr.ts
source.ts
foreground	No theme selector

····return·{·toString

textmate scopes	meta.object-literal.key.ts
meta.object.member.ts
meta.objectliteral.ts
meta.var.expr.ts
source.ts
foreground	No theme selector
```

<img width="299" alt="スクリーンショット 2022-09-06 3 02 57" src="https://user-images.githubusercontent.com/1955233/188498430-ec08b6e6-110a-44a0-b60f-0210fd97d391.png">

If newlines in the argument bracket are removed, they are parsed correctly.

code: 2
```ts
const myToString = (_: unknown): {
    toString: Pick<string, 'toString'>;
} => {
    return { toString: () => '' };
};
```

**Comment by hediet** [comment]
I think this is out of scope. I bet typescript does not tokenize `>` correctly.

**Comment by hediet** [comment]
A workaround would be to exclude `<`...`>` from being highlighted:
```json
"[typescript]": {
    "editor.language.colorizedBracketPairs": [
        ["{", "}"],
        ["[", "]"],
        ["(", ")"]
    ]
},
```

The underlying bug is a limitation of typescripts textmate grammar:

![image](https://user-images.githubusercontent.com/2931520/206688336-cd3688ea-5d17-4368-b86f-886fc3060815.png)

(The token should be reported as arrow, not as object-literal key)

Please file an issue here:
https://github.com/microsoft/TypeScript-TmLanguage

**Comment by wbt** [comment]
That repo has a bug report template referencing a broken link to an extension which doesn't show up as being installed in my VSCode environment, and I am observing [this issue](https://github.com/microsoft/vscode/issues/165029). The extension link in the readme is also not installed, and caused problems when a colleague had it installed.  Extensions vscode.typescript-language-features and vscode.typescript do show up, both at v1.0.0, under the search '@Builtin typescript'.
