### ISSUE TITLE
Parsing jspm configuration on package.json

### ISSUE THREAD

**Issue by pocesar** [Microsoft/vscode#1601]
Would be really nice for vscode to use the definitions set by jspm in package.json to navigate through files (and find new typings when using Typescript)

**Comment by simonh1000** [comment]
Yes, I'd like this too http://stackoverflow.com/questions/34462132/vs-code-cant-use-jspm-packages-systemjs-cant-see-angular2-ts-files

**Comment by Beachovic** [comment]
Sounds pretty much like the problem I'm having only that I've defined some maps in a SystemJS config.js file and vscode can't find the mapped names. It would be nice if it would be possible to use the mapped names and still get IntelliSense.

**Comment by pocesar** [comment]
yeah, it's mainly useful when using "packages" or "map". otherwise typescript code is full of errors, or need to manually create a definitions file for `declare module "package/something"`, and in a 40+ file project, can get nasty in no time

**Comment by pocesar** [comment]
this has been implemented in [systemjs 0.20.0-alpha.1](https://github.com/systemjs/systemjs/issues/999#issuecomment-260632861) FWIW

**Comment by mjbvz** [comment]
Closing as out of scope of core VS Code. This is something that a VS Code extension or TypeScript server plugin may be able to provide
