### ISSUE TITLE
Layout of window buttons on the custom title bar looks bad

### ISSUE THREAD

**Issue by chardon55** [microsoft/vscode#160140]
Steps to reproduce
1. Open VSCode 1.71.0 on Windows 11
2. Maximize the window
<img width="197" alt="image" src="https://user-images.githubusercontent.com/44740171/188555180-cd2685de-56d4-4de1-9dff-b2cd7524d93d.png">

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/157086
