### ISSUE TITLE
Multiple lines are collapsed into one line in markdown preview

### ISSUE THREAD

**Issue by weartist** [microsoft/vscode#160134]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:Version: 1.71.0 (Universal)
- OS Version:OS: Darwin arm64 21.5.0

Steps to Reproduce:

1.Open a Markdown editor.
2.Enter the following code:
```
aa
bb
cc
```
<img width="265" alt="image" src="https://user-images.githubusercontent.com/17105034/188545553-e687b0ea-00bd-4bd6-a2ad-2ad226c7edea.png">

<img width="286" alt="image" src="https://user-images.githubusercontent.com/17105034/188545545-6a52bb86-f644-42a0-85fe-089f86f4ebce.png">

3.Preview the Markdown, it's aa bb cc on the same line

I'm not sure if the expected behavior is intended to be displayed as multiple lines, if so I'm want to trying to fix it

**Comment by yume-chan** [comment]
Standard Markdown translates one line break into a space, and two line breaks into a paragraph.

Set `"markdown.preview.breaks": true` setting to enable soft break extension syntax.

**Comment by weartist** [comment]
> Standard Markdown translates one line break into a space, and two line breaks into a paragraph.
> 
> Set `"markdown.preview.breaks": true` setting to enable soft break extension syntax.

thanks！
