### ISSUE TITLE
`QuickInput` controller triggers layout even when not visible?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160104]
While working on https://github.com/microsoft/vscode/pull/160103 I noticed two things:
* we seem to be creating the `QuickInputController` anytime you access [`QuickInputService.controller`](https://github.com/microsoft/vscode/blob/a27fc69ce51852e47e0d3f1ef5297f4551f4cac5/src/vs/platform/quickinput/browser/quickInput.ts#L33-L40) which imho is often an unwanted side effect, esp. for the `onShow` and `onHide` events that only care about quick input actually being used (for those, my PR addresses this, but its unclear to me in other cases, e.g. shouldn't `focus` method return when `controller` is `undefined`?
* we `layout` the underlying widget but the widget is not visible at that point? unclear to me the purpose:

https://github.com/microsoft/vscode/blob/a27fc69ce51852e47e0d3f1ef5297f4551f4cac5/src/vs/platform/quickinput/browser/quickInput.ts#L87

//cc @chrmarti

**Comment by TylerLeonhardt** [comment]
@mjbvz actually fixed this recently and now we only layout when the quickpick is displayed:
https://github.com/microsoft/vscode/commit/11a7e20a9a6a1b7e49b719a48a45b0cd4ac5eeab
