### ISSUE TITLE
Vscode for Web.  The workspace disappears as soon as you refresh it

### ISSUE THREAD

**Issue by lichangwei123** [microsoft/vscode#160128]
![image](https://user-images.githubusercontent.com/46671582/188530387-9d0d65ee-b47d-46b4-a429-498aec33d65b.png)
https://insiders.vscode.dev/

**Comment by aeschli** [comment]
How do you 'refresh' it?

**Comment by lichangwei123** [comment]
![image](https://user-images.githubusercontent.com/46671582/188636693-f5a0af04-7b10-4948-ab01-1a94d4b1dc61.png)

**Comment by lichangwei123** [comment]
The refresh here

**Comment by lichangwei123** [comment]
> How do you 'refresh' it?

![image](https://user-images.githubusercontent.com/46671582/188636942-49578ecc-35cc-48a7-a40e-e296ef4e5743.png)
Refresh the browser

**Comment by lichangwei123** [comment]
> How do you 'refresh' it?

![image](https://user-images.githubusercontent.com/46671582/188637387-7ee5d608-d672-4fdb-b414-bc3cf2bcfd50.png)
Refresh the browser

**Comment by joaomoreno** [comment]
Where's the refresh button in your original screenshot? 

![image](https://user-images.githubusercontent.com/22350/188639004-df915b71-fb75-44ad-aaf6-68b060077ebb.png)

**Comment by lichangwei123** [comment]
> Where's the refresh button in your original screenshot?
> 
> ![image](https://user-images.githubusercontent.com/22350/188639004-df915b71-fb75-44ad-aaf6-68b060077ebb.png)

And by refresh I mean browser refresh

**Comment by lichangwei123** [comment]
> > Where's the refresh button in your original screenshot?
> > ![image](https://user-images.githubusercontent.com/22350/188639004-df915b71-fb75-44ad-aaf6-68b060077ebb.png)
> 
> And by refresh I mean browser refresh

Not in the screenshots.

**Comment by lichangwei123** [comment]
> > Not in the screenshots.
> 
> Please show me a full screenshot.
![image](https://user-images.githubusercontent.com/46671582/189062954-5bd0c50c-bdc2-4ad8-b661-6925303ad500.png)
Refresh the browser

**Comment by joaomoreno** [comment]
Thank you. Now I understand. This is about refreshing vscode.dev while having a local folder open.

Sadly, Web APIs do not let us hang on to open folders so it's impossible for us to restore the folder. For that reason, you have to run `Open Recent` to restore the previously opened folder.
