### ISSUE TITLE
Missing Emmet extension

### ISSUE THREAD

**Issue by nicholasirsyad** [microsoft/vscode#160150]
Type: <b>Bug</b>

Emmet stopped working all of a sudden since a few days ago. 
I just checked in settings.json and no config with emmet prefix is recognized. 
In the user folder (C:\Users\<user>\.vscode\extensions), there is no emmet folder installed. 

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.79GB (0.76GB free)|
|Process Argv|--crash-reporter-id fc423e91-9d15-4ac0-a314-b370a5e93109|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.1.0
vscode-eslint|dba|2.2.6
gitlens|eam|12.2.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.8.0
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.1
vscode-language-pack-es|MS-|1.71.8310926
material-icon-theme|PKi|4.20.0
java|red|1.10.0
vscodeintellicode|Vis|1.2.24
vscode-java-debug|vsc|0.44.0
vscode-java-pack|vsc|0.25.1
vscode-java-test|vsc|0.37.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by yume-chan** [comment]
Emmet is a built-in extension, stored in Code installation folder.

It can still be disabled, you can see it by searching for `@id:vscode.emmet` in extension panel.

**Comment by nicholasirsyad** [comment]
@yume-chan, you are right. I found a resource that says to filter my VSCode extensions with '@builtin' (without the quotes). Then I could see Emmet in one of the items being greyed out. Turns out it was disabled. Thanks.

**Comment by rzhao271** [comment]
Closing as resolved
