### ISSUE TITLE
In full screen mode

### ISSUE THREAD

**Issue by zhangquanming** [microsoft/vscode#160167]
- VS Code Version: 1.71.0
- OS Version: macOS 10.14.6

Steps to Reproduce:

In full screen mode:
![2061662456919_ pic](https://user-images.githubusercontent.com/16423271/188611520-6a99bccd-344f-4e72-af0a-5213ede6bf19.jpg)

**Comment by TylerLeonhardt** [comment]
tracking in https://github.com/microsoft/vscode/issues/159862
