### ISSUE TITLE
error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xadhoom** [Microsoft/vscode#16015]
- VSCode Version: code-insiders-1.8.0-1479970836.el7.x86_64
- OS Version: CentOS Linux release 7.2.1511 (Core)

Steps to Reproduce:

1. install code rpm from insiders build on CentOS minimal
2. try to launch it from cli

Installing GConf2 fixes it ( yum install GConf2 ).

maybe should be a dep in the rpm spec file.

**Comment by polygotdev** [comment]
hello @xadhoom 

would love more information on the _minimal install_ aspect for your use case. To clarify, are you starting with a "minimal installation" and then installing x11 after the fact ?

![centosminimalinstall](https://cloud.githubusercontent.com/assets/18198056/20608714/a11f746c-b241-11e6-8525-34c52774202b.png)

**Comment by xadhoom** [comment]
Yes,

and after that I just install the basic fonts and xorg xauth because I ssh into the devel box
and use the editor via X11 forwarding.

I've done this with other editors and is pretty handy, so I can avoid copying/checking out code from the workstation to the devel box (I write stuff meant to run over CentOS 7)

**Comment by Nashenas88** [comment]
The exact same problem occurs on Elementary OS (based on Ubuntu). Running `sudo apt install gconf2` fixes the issue. It's most likely the same missing dependency problem in the .Deb file.

**Comment by Tyriar** [comment]
@Nashenas88 this should be fixed in 1.9

**Comment by puagh** [comment]
Hello, I had the same problem on openSUSE 42.1, when I ran `sudo zypper install GConf2` the problem was solved. Btw I downloaded the .rpm file.

**Comment by bounteous** [comment]
On ArchLinux pacman -S gconf
