### ISSUE TITLE
The :has() CSS pseudo-class not supported

### ISSUE THREAD

**Issue by gita366** [microsoft/vscode#160183]
Type: <b>Bug</b>

The :has() CSS pseudo-class is not supported and Visual Studio Code incorrectly reports errors in the css.

) expected css(css-rparentexpected) and
{ expected css(css-lcurlyexpected)
...

This selector is supported by Edge and Chrome 105 and FireFox 103 (only when enabled)

**Comment by aeschli** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/147353
