### ISSUE TITLE
3-way merge editor says "unhandled conflict" but file does not have any conflicts

### ISSUE THREAD

**Issue by hasezoey** [microsoft/vscode#160172]
Type: <b>Bug</b>

1. get a merge conflict in git
2. open vscode
3. open the 3-way merge editor
4. resolve conflict
5. see that it complains about unresolved conflicts, even though there are none

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:10.472Z)
OS version: Linux x64 5.19.1-3-MANJARO
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4399)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|31.23GB (21.94GB free)|
|Process Argv|. --disable-extensions --crash-reporter-id 3159ccf7-dead-4761-b348-a6094ef14c0c|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasmawayland|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|wayland|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by hasezoey** [comment]
[merge-editor-state.json.txt](https://github.com/microsoft/vscode/files/9496506/merge-editor-state.json.txt)

Notes:
- the file itself (going back to it through the icon or opening it manually) it does not have any errors or merge conflicts
- git also says there are not merge conflicts in that file
- when running the tests in the project they also pass without any errors

**Comment by hediet** [comment]
Can you reproduce this in the latest release of VS Code? If it still reproduces, can you share your conflict using merge editor dev share as json command (F1)?
