### ISSUE TITLE
Faster startup/improve startup time

### ISSUE THREAD

**Issue by shivan** [Microsoft/vscode#16028]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. start VSCode from explorer with a simple 5 kb xml. Only python plugin installed.

Startup duration about 4 seconds on an i5 with SSD and 12 GB memory.

Competing editor sublime text 3 needs less than 1 second (including directly visible syntax highlighting)

Would be great, if startup time could be improved, too. (but without leaving it running in the background)

**Comment by bpasero** [comment]
We already want to look at this from https://github.com/Microsoft/vscode/issues/15455
