### ISSUE TITLE
Word Wrap Function Fail on large file

### ISSUE THREAD

**Issue by nyaachen** [microsoft/vscode#160260]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

[1] Open a large log file, eg >40MB
[2] Alt + Z toogle word wrap , no response

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600H with Radeon Graphics          (12 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.90GB free)|
|Process Argv|--crash-reporter-id 2c4c3c0b-a643-4e09-abff-3b3903ef1bf9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
url-encode|fle|1.1.0
pretty-formatter|mbl|0.2.2
vscode-docker|ms-|1.22.1
vscode-language-pack-zh-hans|MS-|1.71.8310936
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
vscode-typescript-next|ms-|4.9.20220905
pretty-json|sup|0.0.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by bjaastad** [comment]
I just want to add to this: 

I have a log file that just went from 299.999 lines to 300.000 lines. On my machine, VS Code will not respect the Word Wrap setting after this limit. The size of my log file is 9 887 kB, but this does not seem to be relevant to the problem.

**Comment by alexdima** [comment]
@nyaachen Do you have `"editor.wrappingStrategy": "advanced"` configured by any chance?
@bjaastad For very large files (over 300k lines or over 20MB) we automatically disable certain features, like the ViewModel in order to save RAM usage. The ViewModel is what enables the projection from model lines to wrapped lines, but it consumes some memory per line. So that is why opening a large file will disable wrapping. But a notification is shown in this case and you can use `"editor.largeFileOptimizations": false` in your settings to disable this behavior and get wrapping even for very large files (at the cost of using a lot of memory).

**Comment by bjaastad** [comment]
@alexdima Thank you. I played around with disabling the editor.largeFileOptimizations option, and I can confirm that it solves the problem. As for the memory usage, it seems to fluctuate around 500 MB whether I have the option turned on or off, with greater spikes when I'm actively using the editor (as measured, unscientifically, using the Windows Task Manager only).

**Comment by nyaachen** [comment]
> @nyaachen Do you have `"editor.wrappingStrategy": "advanced"` configured by any chance?
> 

editor.wrappingStrategy: advanced
editor.wordWrap: wordWrapColumn
editor.wordWrapColumn: 80
