### ISSUE TITLE
`workspace.onDidChangeTextDocument` unexpectedly reports changes with the file version from the source control

### ISSUE THREAD

**Issue by ArtemGovorov** [Microsoft/vscode#16023]
- VSCode Version: Version 1.8.0-insider (1.8.0-insider) 6a6ab1fc5e58227b56ffc3e5bea9951e5565c314
- OS Version: macOS Sierra 10.12

Something very strange happened to `workspace.onDidChangeTextDocument`, it looks like it now reports changes to the file by comparing its version with the Git stored version, or something like that.

Steps to Reproduce:

1. Create an extension with one line:
```javascript
workspace.onDidChangeTextDocument(event => console.log(event));
```
2. Checkout any project from Git
3. Open Dev Tools
4. Open any file of the project from Git, change the file, observe the correct and expected change reported to the console
5. **Save** the file, wait few seconds, and observe the unexpectedly reported change (also check the event `contentChanges[0].text`)

**Comment by jrieken** [comment]
Why is that unexpected? It's a valid event we broadcast, the uri clearly identifies this document via the `git-index`-scheme.

**Comment by jrieken** [comment]
fyi @joaomoreno

**Comment by ArtemGovorov** [comment]
Thanks for clarifying it. I'll add a filter in my handler to only catch `file` scheme URIs.

> Why is that unexpected?

`onDidChangeTextDocument` didn't have the `git-index`-schemed changes broadcasted through it before. We never bothered to check the URI and had no idea we needed to, but the change breaks our code, so now we need to check the URI of the changed document as well. It's not a problem to fix it in our extension, I just have a feeling that just like us, others may also be not checking the scheme and have their extension broken, but I may be mistaken.

**Comment by jrieken** [comment]
Unsure - this isn't the first 'non-file' document for which we are broadcasting changes for. This also happens for the document that is used by output channels (like `inmemory://model/4`) and also for virtual documents created with the data from `TextDocumentContentProviders`

**Comment by ArtemGovorov** [comment]
> this isn't the first 'non-file' document for which we are broadcasting changes

We didn't even notice it, because in our extension `onDidChangeTextDocument` handler we are checking a document name (against the whitelist of project files that our extension keeps), so have never hit an issue with trying to process `model/4`-like names. 

This new case however passes the real project document, just with the new URI scheme, so our name check wasn't enough.
