### ISSUE TITLE
Inline breakpoint markers are positioned incorrectly when placed one character apart

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#160281]
Pretty minor, but I don't know if it might affect all decorations (where being one char apart might be more common).

On the first line I add multiple inline breakpoints two characters apart (using Shift+F9). This works fine.
On the second line, I add them one character apart. The rendering gets messed up in this case.

![inline breakpoints](https://user-images.githubusercontent.com/1078012/188857912-07d72f0a-a815-4800-b0cd-a20e9d8b4aea.gif)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/147329, I see this a lot too @hediet  let me know if I can help investigate

**Comment by DanTup** [comment]
I was going to add a note on that issue about how to easily repro this (in case someone comes back to it in future), but it's currently locked to contributors even though it's open (and while this one is not locked, it's closed). In case it doesn' get looked at till later, it might be worth adding a comment pointing here (or the gist of the repro steps above) :)
