### ISSUE TITLE
VS Code shortcut is forgotten after an update

### ISSUE THREAD

**Issue by tSte** [Microsoft/vscode#16025]
- VSCode Version: 1.7.2
- OS Version: Windows 8.1

Steps to Reproduce:

1. Set VS Code shortcut key (e.g. open VS Code on given shortcut)
2. Update VS Code
3. Reboot
4. Open VS Code with saved shortcut

IMO updates remove all saved options (such as "Run as administrator"). This is not critical, but... it is annoying to setup on each update.

**Comment by joaomoreno** [comment]
What do you mean by "Set VS Code shortcut key"? Can you show me how you do that?

**Comment by tSte** [comment]
Sure. Its a key(s) shortcut to quickly access an application.

Right-click VS Code => Properties => Shortcut => Shortcut key.

**Comment by joaomoreno** [comment]
This seems fixed by now.

**Comment by tSte** [comment]
I'm afraid it's not. After last update I had to update shortcut again...
