### ISSUE TITLE
Unable to enter symbols via keyboard layout shifting in Wayland 

### ISSUE THREAD

**Issue by rikedyp** [microsoft/vscode#160262]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:10.472Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.6-200.fc36.x86_64
Sandboxed: No

OS: Fedora Linux 35 (Workstation Edition)
GNOME: 42.4

Steps to Reproduce:

1. Install Gnome Tweaks
2. In **Tweaks**, go to **Keyboard & Mouse** and click **Additional Layout Options**
3. Under **Switching to another layout** select a shifting key (e.g. **Right Alt (while pressed)** - note this issue does not occur if a non-(while pressed) option is selected
4. In the normal Gnome Settings, under **Keyboard** add another Input Source - it is best to use one with a different script, such as Russian, so that the problem is more obvious
5. Open a program such as **gnome-text-editor**
6. Notice that typing normally produces Latin characters (if you are using a Latin layout such as English language ones), and the holding AltGr (Right Alt, or whatever was chosen in step 3) and typing produces other characters (Cyrillic if using Russian).
7. Open VSCode
8. Try step 6 and notice that alternate characters (Cyrillic) are not produced while AltGr is held

The closest-looking issue I've found is https://github.com/microsoft/vscode/issues/127932 but setting `"keyboard.dispatch": "keyCode"` does not seem to help.

**Comment by rikedyp** [comment]
There is a workaround. The problem goes away with:
```
code --enable-features=UseOzonePlatform --ozone-platform=wayland
```

I would prefer if this was enabled by default.

**Comment by deepak1556** [comment]
We cannot flip the default backend to wayland until the runtime makes the relevant changes, refs https://github.com/microsoft/vscode/issues/134612. I recommend using the CLI flag to use the wayland backend. Also you do not need the flag `--enable-features=UseOzonePlatform`. Instead use the following `code --ozone-platform=wayland`
