### ISSUE TITLE
highlight border does not work in ts file

### ISSUE THREAD

**Issue by Rongjianying** [microsoft/vscode#160287]
Type: <b>Bug</b>

Conditions:
- enable the internal js/ts extension: **'vscode.typescript-language-features'**
- set the highlight border in setting.json
```json
"workbench.colorCustomizations": {
    "editor.selectionHighlightBorder": "#ffd700"
  },
```

The highlight border does not work in ts file, when I disable the internal js/ts extension, it works.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:25.516Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 7, 6|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id b00cc96b-9719-4333-9716-e2e95fee6d55|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-css-modules|cli|0.4.2
vscode-eslint|dba|2.2.6
gitlens|eam|12.2.2
prettier-vscode|esb|9.8.0
go|gol|0.35.2
vscode-language-pack-zh-hans|MS-|1.71.8310936
material-icon-theme|PKi|4.20.0
vscode-yaml|red|1.10.1
code-spell-checker|str|2.7.2
errorlens|use|3.6.0
vim|vsc|1.23.2
markdown-all-in-one|yzh|3.4.3
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by mjbvz** [comment]
This is because JS/TS provides smart occurrences highlighting instead of simple selection based highlighting.

Try using a setting like `editor.wordHighlightBorder` instead
