### ISSUE TITLE
data loss smoke test failures

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#160214]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184369&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ed595fa9-bdca-5f35-a51a-12f92e4d7421

```
  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies opened editors are restored:
     Error: Timeout of 120000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/1/s/test/smoke/out/main.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies editors can save and restore:
     TypeError: Cannot read properties of undefined (reading 'workbench')
      at Context.<anonymous> (src/areas/workbench/data-loss.test.ts:55:14)
```

The first test timing out probably caused the second test to fail by running at the same time and setting `app = undefined` in the middle of the second test

In this run right after, https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184376&view=logs&j=260a512b-e5ca-5cf1-3f8e-20c0fa41efc9&t=ed595fa9-bdca-5f35-a51a-12f92e4d7421, it failed on its own

```
  1) VSCode Smoke Tests (Electron)
       Data Loss (insiders -> insiders)
         verifies editors can save and restore:
     Error: Timeout: get text content ' .monaco-editor[data-uri$="app.js"] .view-lines' after 20 seconds.
      at Code.poll (/Users/runner/work/1/s/test/automation/src/code.ts:260:11)
      at Code.waitForTextContent (/Users/runner/work/1/s/test/automation/src/code.ts:192:10)
      at Context.<anonymous> (src/areas/workbench/data-loss.test.ts:67:4)
```

**Comment by bpasero** [comment]
Yeah, its an old one that I had hoped was gone. We try to exit VSCode in some of our tests only to restart and verify state was restored. In rare cases, the call to exit never seems to reach VSCode and then we do a forcefull termination of the process that leads to a crash it seems:

```
[2022-09-06 12:48:09.335] [main] [error] CodeWindow: renderer process crashed (reason: killed, code: 15)
```

It is interesting that Electron crashes like that, maybe @deepak1556 you know the reasons. We use a module called `treekill` which seems to be using `SIGTERM` by default. Maybe Electron does not like it when you terminate the entire process tree like that:

https://github.com/microsoft/vscode/blob/810b12931f012a0208ec6c337474c6ce3a0a4ce0/test/automation/src/code.ts#L172-L179

Anyway, will push a change to retry the graceful exit call and see if that helps.

**Comment by deepak1556** [comment]
@bpasero this is not a crash, the event `render-process-gone` will be emitted for all types of render process exits. `details.reason` will convey the type of exit https://github.com/electron/electron/blob/main/docs/api/web-contents.md#event-render-process-gone and in this case it is `killed` with signal `15` which is expected since we kill the main process with `SIGTERM`. Electron can accept `SIGTERM` to terminate the process tree.

**Comment by bpasero** [comment]
Thanks, I forgot about that 🙏
