### ISSUE TITLE
请支持jquery

### ISSUE THREAD

**Issue by yuwenlong** [Microsoft/vscode#16021]
- VSCode Version: 1.7.3
- OS Version: windows 10

Steps to Reproduce:

请支持jquery的代码提示，谢谢

**Comment by jrieken** [comment]
@yuwenlong Please file issues in English

**Comment by bang88** [comment]
Translates: Please support jQuery's code auto complete.

@yuwenlong If you have the latest VSCode installed,It should work like this:

![image](https://cloud.githubusercontent.com/assets/433259/20616001/c2043608-b319-11e6-8ec1-c6cd9483ae1c.png)

**Comment by yuwenlong** [comment]
@bang88 If not the first line?

**Comment by yuwenlong** [comment]
@jrieken Please support jQuery's code auto complete.

**Comment by mjbvz** [comment]
@bang88 Do you have a `package.json` with `jquery` listed in the `dependencies`? I see jquery intellisense working using automatic typings acquisition:

![screen shot 2016-11-28 at 2 06 55 pm 2](https://cloud.githubusercontent.com/assets/12821956/20688015/c3511d62-b573-11e6-893e-61495fda5dd8.png)

**Comment by yuwenlong** [comment]
@mjbvz The next version does not install any plug-ins to support the prompt, right?

**Comment by mjbvz** [comment]
@yuwenlong Correct, you do not need any extensions for this.

With VSCode 1.7.2+, if you `npm install jquery` and have `jquery` listed in your `package.json`, we will [automatically download typings](https://code.visualstudio.com/updates#_better-javascript-intellisense) for the library to provide this IntelliSense.
