### ISSUE TITLE
Menu Items blackout

### ISSUE THREAD

**Issue by 3Scratch** [microsoft/vscode#160207]
I am using vs code on ubuntu 22.04 LTS and sometimes the menu items got blackout. Please tell me how to fix it
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:10.472Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-47-generic
Sandboxed: No
![Screenshot from 2022-09-06 22-29-48](https://user-images.githubusercontent.com/50314456/188696689-9514e4d8-e152-47fc-a640-9ec1f8ffe79b.png)

**Comment by deepak1556** [comment]
Please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
