### ISSUE TITLE
Allow middle click pasting into terminal on Windows and Mac

### ISSUE THREAD

**Issue by daxandi** [microsoft/vscode#160250]
It seems that this code https://github.com/microsoft/vscode/blob/86cc884a9e1742a3fddd4e8c36b20cbf198d7260/src/vs/workbench/contrib/terminal/browser/terminalEditor.ts#L134 prevents middle click pasting in the terminal on Windows and Mac.
To make the experience more streamlined when changing between different systems, it would be useful to have this possibility.

**Comment by meganrogge** [comment]
Tracked in https://github.com/microsoft/vscode/issues/3130, note that some work has happened there and it's looking like we'll be able to support your ask in a mousebindings.json file or similar.
