### ISSUE TITLE
Cannot launch/attach debugger

### ISSUE THREAD

**Issue by ddobric** [Microsoft/vscode#16027]
- VSCode Version:1.7.2
- OS Version:WIndows10

Steps to Reproduce: Start Debugging
Error:
C:\Program Files\nodejs (chakracore)\node.exe' --debug-brk=44643 xyz.js Arg1 Arg2
Starting debugger on port 44643 failed
25720 Listener started...
Assertion failed: debugger_running, file src\node.cc, line 3486

**Comment by weinand** [comment]
@ddobric What debugger extension are you using, e.g. what is the debug type in your launch config?
What eversion of node are you using?

**Comment by weinand** [comment]
No response. Closing.
