### ISSUE TITLE
diff experimental algorithm ignores white space changes

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#160269]
Type: <b>Bug</b>

When diffing two files (from git commit and working tree) with only white space change the experimental algorithm doesn't notice the change. The default smart algorithm sees the change.
File snippet :
Left:
   void Function(
      const UserDefinedType *variableName);

Right:
   void Function(
   const UserDefinedType *variableName);

Notice the white space change on the second line.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2186M  CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.79GB (14.80GB free)|
|Process Argv|--crash-reporter-id 27b05253-eb30-4313-974d-48b1345f0a4c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
overtype|ada|0.2.0
vscode-icalendar|af4|1.0.1
read-only-indicator|ale|3.7.1
sourcetrail|ast|0.0.2
Doxygen|bbe|1.0.0
doxdocgen|csc|1.4.0
gitlens|eam|12.2.1
permute-lines|ear|1.1.0
graphviz-preview|EFa|1.5.0
vscode-toggle-column-selection|eri|1.0.6
shell-format|fox|7.2.2
matlab|Gim|2.3.1
triggertaskonsave|Gru|0.2.17
symbol-navigate-back|ike|1.1.13
reg|ion|1.1.0
better-cpp-syntax|jef|1.15.19
string-manipulation|mar|0.5.6
workspace-storage-cleanup|meh|1.1.3
git-graph|mhu|1.30.0
select-part-of-word|mle|1.0.1
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
cpptools|ms-|1.12.4
hexeditor|ms-|1.9.8
indent-rainbow|ode|8.3.1
vscode-yaml|red|1.10.1
indenticator|Sir|0.7.0
rewrap|stk|1.16.3
code-spell-checker|str|2.7.2
tabspace|Tak|0.0.1
selectline-statusbar|tom|0.0.2
vscode-todo-highlight|way|1.0.5
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
i497e931:30553904

```

</details>

**Comment by hediet** [comment]
Before:
<img width="894" alt="image" src="https://user-images.githubusercontent.com/2931520/193549985-3f29208e-eae5-4b96-845c-3e01aa9fd7ed.png">


After:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2931520/193549109-6b6294c8-3982-4d8a-80da-3593f54e7cf1.png">

**Comment by joyceerhl** [comment]
Verified by enabling `"diffEditor.diffAlgorithm": "experimental"` and ensuring that whitespace changes show up in the diff editor. Let me know if I missed steps.

**Comment by BillDenton** [comment]
@joyceerhl I assume this isn't released yet. I'm still seeing the bug on:
Version: 1.72.2 (system setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by hediet** [comment]
This is only in insiders yet. Will be released soon!
