### ISSUE TITLE
What Are The Specific Meanings of "Yours" and "Theirs" In the Merge Editor?

### ISSUE THREAD

**Issue by maguayo6** [microsoft/vscode#160203]
In the new merge editor what do "yours" and "theirs" map to or mean? For example in the old merge tool, there was "current" and "incoming." I'm a bit confused on whether the "your" panel is what is currently in your branch, or the incoming changes.

for example, if I'm on my feature branch and I `git rebase master` the merge the "yours" panel seems to be the incoming rebased code, and "theirs" panel seems to be my current branch changes.

I know this may be a novice question but I'm generally just confused and cannot seem to find a clear answer from searching online.

**Comment by jrieken** [comment]
> In the new merge editor what do "yours" and "theirs" map to or mean? For example in the old merge tool, there was "current" and "incoming."

@maguayo6 Is it possible that you are using an old version of VS Code. We have aligned the naming and the merge editor also uses "current" and "incoming" (see https://github.com/microsoft/vscode/issues/156229)
