### ISSUE TITLE
please align the icon of scm

### ISSUE THREAD

**Issue by heartacker** [microsoft/vscode#160242]
![image](https://user-images.githubusercontent.com/1876302/188783718-3e781c81-da49-43a2-a00e-ea0c658d2772.png)

**Comment by gjsjohnmurray** [comment]
What is your `scm.providerCountBadge` setting?

https://github.com/microsoft/vscode/issues/101103#issuecomment-653489709 began some previous discussion about how these badges can disrupt alignment.

**Comment by heartacker** [comment]
my setting is auto

**Comment by heartacker** [comment]
I change it to visible， and all are aligned even there is  0, thanks
