### ISSUE TITLE
JavaScript syntax highlighting not used for inline script in HTML files

### ISSUE THREAD

**Issue by martincostello** [Microsoft/vscode#16029]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Version 1607 (OS Build 14393.0)
- Color Theme: Light (Visual Studio)

Steps to Reproduce:

1. Create an HTML page that contains some inline JavaScript (example below) in a ```<script>``` tag.
2. View the HTML in Visual Studio Code.

The inline JavaScript is shown using colorization that does not match the colorization used for JavaScript files. JavaScript should be rendered in the same colours in the editor consistently.

**Example HTML**
```html
<!DOCTYPE html>
<html>
<head>
    <title>An HTML Page</title>
</head>
<body>
    <script>
        console.log("This is some inline JavaScript");
    </script>
</body>
</html>
```

**Expected appearance**
![image](https://cloud.githubusercontent.com/assets/1439341/20604256/67d665fa-b25d-11e6-9eea-a30a1f59175d.png)

**Actual appearance**
![image](https://cloud.githubusercontent.com/assets/1439341/20604234/45a8fba0-b25d-11e6-83e1-cc20f89f922e.png)

**Comment by aeschli** [comment]
This got fixed with the TextMate changes for January (#3008)
![image](https://cloud.githubusercontent.com/assets/6461412/22459774/3830988c-e7a2-11e6-8252-2d0dc465537a.png)
