### ISSUE TITLE
Create a PR on `github.dev` often errors when opening preview

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#160302]
1. open github.dev and ensure you're on insiders
2. Make a commit and create a pr
3. 🐛 The PR is created but the preview fails to open often due to a could not find PR or could not read undefined error

**Comment by alexr00** [comment]
@mjbvz I'm not sure what's happening here, but here's what I've seen so far:
- @lramos15 can repro sometimes, but not reliably, on the GHPRI description webview
- Also on the Create PR webviewView
- I was able to repro on the GitLens "Welcome (quick setup)" webview
- I'm not able to repro on any of the webviews that @lramos15 can

**Comment by mjbvz** [comment]
@lramos15 @alexr00 Please let me know if you see this issue again on insiders. I believe that #176686 fixed it but don't fully understand the root cause and I couldn't reproduce the issue reliably  (I never saw it for GitHub PR but did see it for GitLens' welcome pages)

**Comment by dbaeumer** [comment]
Stupid me. Forgot to press creates :-)
