### ISSUE TITLE
Result decorations should have more user friendly message

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#160323]
The current message is pretty cryptic and users are confused by it. We should make a more user friendly message that really tells the user what they should do.

![Screenshot 2022-09-07 at 17 40 15](https://user-images.githubusercontent.com/1926584/188920588-8c8a2a3f-1189-4cdf-88cf-cd2ce7b3ab08.png)

**Comment by hediet** [comment]
Closing, as we don't have this decoration anymore.
