### ISSUE TITLE
4-editor grid layout

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#160307]
I would like to make a case for a 4-editor grid layout for merge editor that is like this:
```
Incoming | Base | Current
          Result
```

_Originally posted by @bpasero in https://github.com/microsoft/vscode/issues/160247#issuecomment-1239435363_

**Comment by isidorn** [comment]
I think we should focus on making the experience simpler for a lot of our users that are having problems right now.
We can easily add the advanced features later. So I suggest we move this out of September.

**Comment by bpasero** [comment]
I would argue the missing 4th editor for `base` is the reason people don't understand the merge, at least for me it's hard. And comparing 2 editors with diff semantics is what every VSCode developer does, so I think this will actually make things easier.

**Comment by isidorn** [comment]
@bpasero I would disagree based on the lot of feedback I have been reading. The user problems are complex UI, not enough horizontal space, no clue how to interact with any of the views etc. And I do not see how this helps address any of these. 
I agree that it is a nice feature to have, I am just arguing that we can add it later.

**Comment by hediet** [comment]
This feature request takes 10 minutes to implement.

**Comment by bpasero** [comment]
Yes, it adds more UI, but I think understanding a merge conflict needs that UI to help how to resolve the merge conflict. And in fact, previously when I had to resolve a merge conflict I would do exactly this:
* compare my change to the base to know what I did in the conflicting range
* compare their change to base to know what they did in the conflicting range
* reason about how to correctly do the merge now knowing what each intent was (mine and theirs)

If I could do these steps from a single editor that would be awesome.

**Comment by jrieken** [comment]
I tend to agree with @isidorn and would shy away from adding more complexity to the merge editor. One thing is show/hiding base and its placement, esp considering (popular?) column mode. 

The other part (and that's where I see too much complexity) is dynamically changing the diff modes based on what editor is focused. It can all be nervous like you understand a conflict and while coping from input1/2 (for pasting into result) the diffs change...

**Comment by bpasero** [comment]
Yeah the part of changing diff when moving focus is not ideal, maybe that is not needed though, would have to play with it...

**Comment by jrieken** [comment]
Understood but still scared of complexity. With the base-column mode synchronising scrolling isn't simple - does it sync with input1 or input2? For today you can simply open a separate diff editor and use the power of workbench grid to see things at once

<img width="954" alt="Screenshot 2022-09-07 at 16 46 23" src="https://user-images.githubusercontent.com/1794099/188908090-d9868089-64d1-41e9-b396-65f44cb7b4d3.png">

**Comment by bpasero** [comment]
Yes, those commands are really helpful 👍

**Comment by hediet** [comment]
Implemented with the "Show Base At Top" command (which needs some more work though).
