### ISSUE TITLE
Editor problems with latin symbols

### ISSUE THREAD

**Issue by miqmago** [Microsoft/vscode#16036]
- VSCode Version: Code - Insiders 1.8.0-insider (6a6ab1fc5e58227b56ffc3e5bea9951e5565c314, 2016-11-24T07:05:02.837Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.3|
|jsx|TwentyChung|0.0.1|
|Bookmarks|alefragnani|0.10.0|
|stylus|buzinas|0.1.0|
|riot-tag|crisward|0.1.7|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.6.4|
|rest-client|humao|0.10.5|
|debugger-for-chrome|msjsdiag|2.2.2|
|sass-indented|robinbentley|1.2.1|
|jadeview|vivainio|1.0.0|
|vscode-react-native|vsmobile|0.2.3|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. type any accented latin symbol `í`
2. press space

They will appear twice: `íí`

Also when typing ` character and space, two of them appear but the cursor is positioning at the end of both, not in between, so you end up writting 

```
``some text
```

instead of 

```
`some text`
```

**Comment by rebornix** [comment]
Dup of #16017. Thanks for reporting this problem!

**Comment by miqmago** [comment]
I've seen... But I'm not sure if the problem with template strings is already reported, maybe we can change this issue or open a new one, the one that is causing to write:

```
``some text
```

instead of

```
`some text`
```

**Comment by miqmago** [comment]
![insiders-autoformat-1](https://cloud.githubusercontent.com/assets/1849488/20662019/e82487ea-b551-11e6-86e3-a85b445bf76d.gif)

**Comment by rebornix** [comment]
@miqmago thanks for more info! I use default US English keyboard and tried these steps, but I can't reproduce this, so IMHO it might share the same root cause. We'll revisit this issue once we have a fix for that.
