### ISSUE TITLE
Theme broke on WSL

### ISSUE THREAD

**Issue by Thienguen** [microsoft/vscode#160388]
Type: <b>Bug</b>

Color Theme One Dark Pro broke on WSL as some colors never shown but on a regular window they did show up

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.90GB (17.67GB free)|
|Process Argv|--crash-reporter-id 9f4f0fd5-6064-4d10-bf92-583bcf7c3fec|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor (24 x 3700)|
|Memory (System)|15.57GB (14.42GB free)|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
remotehub|Git|0.42.0
better-cpp-syntax|jef|1.15.19
mips|kda|0.1.0
fluent-icons|mig|0.0.18
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
remote-repositories|ms-|0.20.0
remote-server|ms-|0.1.2022090509
material-icon-theme|PKi|4.20.0
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8
JavaScriptSnippets|xab|1.8.0
code-gnu-global|aus|0.2.2
doxdocgen|csc|1.4.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
c-cpp-runner|fra|4.0.5
copilot|Git|1.44.6735
copilot-labs|Git|0.2.221
vscode-pull-request-github|Git|0.51.2022090509
gc-excelviewer|Gra|4.2.55
todo-tree|Gru|0.0.215
better-cpp-syntax|jef|1.15.19
cmake-language-support-vscode|jos|0.0.4
inline-fold|moa|0.1.7
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.3.0
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.8
js-debug-nightly|ms-|2022.9.717
live-server|ms-|0.4.0
indent-rainbow|ode|8.3.1
vscode-css-peek|pra|4.2.0
vscode-data-preview|Ran|2.3.0
LiveServer|rit|5.7.9
pdf|tom|1.2.0
cmake|twx|0.0.17
doki-theme|unt|88.1.7
vscode-lldb|vad|1.7.4
vscodeintellicode|Vis|1.2.25
better-align|wwm|1.1.6
markdown-pdf|yza|1.4.4
markdown-all-in-one|yzh|3.4.3

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by aeschli** [comment]
From which extension does the theme come from?
Is it https://marketplace.visualstudio.com/items?itemName=zhuangtongfa.Material-theme ?

**Comment by aeschli** [comment]
I tried that one in a WSL window and it worked.
Can you reproduce it every time? Only for a particular WSL folder or for any folder? Just some colors don't show, or the whole theme? Can you add a screenshot?

Do you have any workspace settings that could cause that?

**Comment by Thienguen** [comment]
Quite a handful of colors did not show and defaulted as white.

There are two scenarios that happen while using the theme, I'll include a screenshot below

1. The theme seems to work fine if I open vsCode through mnt/pathtofile/

2. The theme broke if I open the file through ~/pathtofile/ using wsl, though I am aware that we should use ~/pathtofile as it is the standard

pictures are shown below.

Thank you for your help,

![1](https://user-images.githubusercontent.com/94078395/189807931-cda9fb4f-b8e4-489e-85b0-41b9661686ea.png)
![2](https://user-images.githubusercontent.com/94078395/189807935-78455c75-8122-40d1-a615-02f00adcf5e2.png)
![3](https://user-images.githubusercontent.com/94078395/189807936-083fe9e1-f58f-49ca-bd8a-f173f3745b84.png)
![4](https://user-images.githubusercontent.com/94078395/189807937-e6b94802-8a87-4c02-a2a2-45db24af334b.png)
![5](https://user-images.githubusercontent.com/94078395/189807939-11a594ac-082b-408f-8327-937593a711f8.png)
