### ISSUE TITLE
Clicking on the Result Decorations should expand it

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#160322]
Clicking on this decoration should expand it, and instead put the actual code with the full git conflict decorators.

![Screenshot 2022-09-07 at 17 37 04](https://user-images.githubusercontent.com/1926584/188919913-08ff764f-2125-4526-bdce-4d078f302bd3.png)

So in this case it would be 

![Screenshot 2022-09-07 at 17 39 19](https://user-images.githubusercontent.com/1926584/188920425-ee287ad8-81cd-402f-b313-36cc4204f4ae.png)

It is up for debate if the Code Lens Decorations are there

**Comment by hediet** [comment]
We no longer show conflict marker view zones.
