### ISSUE TITLE
updateImportsOnFileMove does not respect updateImportsOnFileMove settings

### ISSUE THREAD

**Issue by valtism** [microsoft/vscode#160304]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: macOS 12.5.1

Steps to Reproduce:

1. Enable setting: `"javascript.preferences.importModuleSpecifier": "non-relative"`
2. Enable setting: `"javascript.updateImportsOnFileMove.enabled": "always"`
3. Move an exported JavaScript file so that its import is updated.
4. The updated import is relative, not non-relative as specified in the settings.

**Comment by mjbvz** [comment]
Can you please share a small example project that demonstrates this?

**Comment by valtism** [comment]
Hm, I can't seem to reproduce this with a minimal example. I'll close the issue for now until I can provide a reproducible case.
