### ISSUE TITLE
Run commands when new terminal opens

### ISSUE THREAD

**Issue by Vadorequest** [Microsoft/vscode#16033]
I'd like to know how I can automatically run `nvm use` when I open the terminal or a new tab. Is it already doable? Or is it something that could get implemented.

**Comment by jrieken** [comment]
How about `.bashrc`?

**Comment by Vadorequest** [comment]
What if you want to have custom commands project-based?

In this use case, a. Bashrc or alike is probably enough. But what about
other use cases? Just wondering.

Le 24 nov. 2016 5:33 PM, "Johannes Rieken" <notifications@github.com> a
écrit :

How about .bashrc?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Microsoft/vscode/issues/16033#issuecomment-262813444>,
or mute the thread

**Comment by Tyriar** [comment]
An extension could be written relatively easily to accomplish this in a general way when `.bashrc` isn't enough.
