### ISSUE TITLE
prompted for trust on behalf of automaticTasks in empty remote workspace

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#160368]
Reported by @kieferrm 

with `security.workspace.trust.emptyWindow` set to false

**Comment by meganrogge** [comment]
to verify, open any workspace (or an empty one) and configure a task with `runOptions: { runOn: openFolder}`. 

Verify that it runs when you reload the window in a trusted workspace.

Now make that same workspace untrusted. reload the window - you should not see a trust prompt _with a message about tasks running_. When you next trust the workspace, the task that you set will get run.

**Comment by rzhao271** [comment]
Closing since it looks like the fix has been merged into the release branch.
