### ISSUE TITLE
How to config "php.validate.executablePath" when php is running in a Vagrant VM?

### ISSUE THREAD

**Issue by nunomazer** [Microsoft/vscode#16032]
- VSCode Version: 1.7.2
- OS Version: Linux Mint 18

I'm trying to configure the "php.validate.executablePath" variable but my PHP is running in a virtual machine managed by Vagrant.

How can I do it to PHP validation run successful using this kind of dev environment?

**Comment by mousetraps** [comment]
Hey @nunomazer, sorry for the delay. I was on vacation, then at a conference. 

Given that the version of PHP is only required for syntax validation, the easiest solution is probably just to download a drop of PHP7 to your dev machine. But if you want to consolidate on the version (again, shouldn't matter for this particular feature, but you may want to do so for debugging), I would suggest a filesystem mapping between the VM and your dev environment

**Comment by mousetraps** [comment]
Also, I should mention that I would only expect filesystem mapping to work if your dev environment and VM are the same OS.

**Comment by nunomazer** [comment]
Thanks, gonna try the filesystem mapping

**Comment by chagamkamalakar** [comment]
@nunomazer 

were you able to set php executable path to vagrant php ?

**Comment by nunomazer** [comment]
@chagamkamalakar no, I gave up from VS for now, got back to Netbeans

**Comment by roblourens** [comment]
These are the options IMO:

> Given that the instance of PHP is only required for syntax validation, the easiest solution is probably just to download a drop of PHP7 to your dev machine and link to that. But if you want to consolidate on a particular executable (again, shouldn't matter for this particular feature, but you may want to do so for debugging), I would suggest a filesystem mapping between the VM and your dev environment

Someone let me know if there's work here.
