### ISSUE TITLE
unable to open folders

### ISSUE THREAD

**Issue by Tarush2468** [microsoft/vscode#160391]
Type: <b>Performance Issue</b>

"sometimes" (not always), VS code seems to be less responsive on my macOS (m2 chipset) when i click shotcut keys to open new file, or even try open files/folders by mouse clicks. it doesnot show any dropdown/window to select my folder which i want to open.

it is not too frequent and happens only with open folder option so i just need to quit and reopen vsCode when it happens.

hope you would guide me with a solution

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 4bb4d905-059b-47f9-88b4-b7c156e79233|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   14	   131	 33094	code main
    0	    49	 33097	   gpu-process
    0	    25	 33099	   utility-network-service
    0	   147	 33100	   window (Visual Studio Code)
    0	    90	 33104	   shared-process
    0	    25	 33108	     ptyHost
    0	    25	 33112	     fileWatcher
    0	     0	 41660	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    57	 33107	   extensionHost
    0	    25	 35812	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --serverMode partialSemantic --useInferredProjectPerProjectRoot --disableAutomaticTypingAcquisition --cancellationPipeName /var/folders/gw/y6p8ys7s58zfpd_1flz7tlp00000gn/T/vscode-typescript501/59624fa0337060c3cf8a/tscancellation-bb3a61c0f92b7c8da110.tmp* --globalPlugins @vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations /Users/tarushgupta/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.25,/Users/tarushgupta/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.25 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    25	 35813	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node --max-old-space-size=3072 /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js --useInferredProjectPerProjectRoot --enableTelemetry --cancellationPipeName /var/folders/gw/y6p8ys7s58zfpd_1flz7tlp00000gn/T/vscode-typescript501/59624fa0337060c3cf8a/tscancellation-e6127933126c1dd42536.tmp* --globalPlugins @vsintellicode/typescript-intellicode-plugin,ms-vsintellicode-typescript --pluginProbeLocations /Users/tarushgupta/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.25,/Users/tarushgupta/.vscode/extensions/visualstudioexptteam.vscodeintellicode-1.2.25 --locale en --noGetErrOnBackgroundUpdate --validateDefaultNpmLocation --useNodeIpc
    0	    25	 35817	       /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typingsInstaller.js --globalTypingsCacheLocation /Users/tarushgupta/Library/Caches/typescript/4.8 --enableTelemetry --typesMapLocation /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/typesMap.json --validateDefaultNpmLocation
    0	    25	 35814	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/css-language-features/server/dist/node/cssServerMain --node-ipc --clientProcessId=33107
    0	    25	 35815	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/html-language-features/server/dist/node/htmlServerMain --node-ipc --clientProcessId=33107
    0	    25	 35816	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/json-language-features/server/dist/node/jsonServerMain --node-ipc --clientProcessId=33107
    0	    90	 41646	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|2.7.1
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
material-icon-theme|PKi|4.20.0
java|red|1.10.0
vscodeintellicode|Vis|1.2.25
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.1
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.38.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by lramos15** [comment]
Without an easy tot make repro it's going to be very difficult for us to ever get to the bottom of this. I don't believe any team members have an M2 chip, but many have M1 chips and appear to not hit this issue. Next time you try it please try to do the following before reproducing it

> If VS Code is slugging when scrolling, moving mouse or typing, please create a performance profile. Do the following

Toggle the developer tools Help > Toggle Developer Tools
Select 'Performance'. In there click the record button.
Scroll, type or any operation leads to the slowness of the UI
Let it profile for 30 to 60 seconds, stop it.
Save the profile to a file and attach the file to your issue.

**Comment by VincentdeWit94** [comment]
This seems to be a bug, not only om M2 but also happening on M1 and seems to be a bug elsewhere. Tried to create a profile to attach, but the save profile button also does the same.

**Comment by lramos15** [comment]
@VincentdeWit94 Do you hit this will all extensions disabled too? You're just going File -> Open Folder?

**Comment by VincentdeWit94** [comment]
@lramos15 Yes, new MacBook Pro M1 Pro, new VS Code!
