### ISSUE TITLE
Test failed: Ensure tabs getter is correct

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#160337]
@lramos15 Honestly you might want to avoid touching a notebook (or maybe any webview editor) in an integration test. We have had a lot of issues with webviews in integration tests and don't run notebook tests in the web. Test that with a unit test if possible

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184552&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9fd0bccc-90ad-5118-165a-bb6fa0e94027

**Comment by lramos15** [comment]
> @lramos15 Honestly you might want to avoid touching a notebook (or maybe any webview editor) in an integration test. We have had a lot of issues with webviews in integration tests and don't run notebook tests in the web. Test that with a unit test if possible
> 
> https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184552&view=logs&j=9833cdaa-2e92-5f8d-56a8-239fd18fd628&t=9fd0bccc-90ad-5118-165a-bb6fa0e94027

It's hard to easily test this with unit tests because there are a lot of editor setup and other stuff that goes on to ensure the end to end tab model is correct. I can remove the notebook piece but then I worry if notebooks or any other non-text type could regress and we wouldn't know

**Comment by roblourens** [comment]
You could also just skip the test in web

**Comment by roblourens** [comment]
Again, in web https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184567&view=logs&j=0304f796-6596-5b42-8573-3d5da85bc4a5&t=4c50b82f-3f48-5844-7225-93b0027cedfd

**Comment by rzhao271** [comment]
Also in web for
https://dev.azure.com/vscode/VSCode/_build/results?buildId=73011&view=logs&j=4aebce06-83e9-5552-2127-6f912f36efb7&t=89d1cf9b-1b7c-5c72-3b40-7ac419a550cd
