### ISSUE TITLE
Intellisense inserts completion on at first cursor

### ISSUE THREAD

**Issue by gerardam** [Microsoft/vscode#16030]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Hay que mejorar la posición del cursor en múltiples sitios, no se distingue si el cursor se ha colocado ya para múltiple edición.
2. Permitir crear archivos sin guardar para cerrar la aplicación, y al abrir la aplicación que el archivo creado sin guardar este disponible (similar a sublime text).

**Comment by cesaraaron** [comment]
@jrieken 

1. Improve the position of the cursors in multiple sites, it doesn't differentiate if the cursor has been already set for multiple edition.
2. Allow to create files without saving to close the app, and then when open it again the created file  without saving it's still there (similar to sublime).

**Comment by jrieken** [comment]
@gerardam Please clarify the first item, for the second search for 'hot exit' which we ship early December

**Comment by gerardam** [comment]
When I type multiline and select an element from the suggestions, it only adds the selected element to the first cursor and not all of them.

**Comment by jrieken** [comment]
@gerardam Please add a sample of the exact code and completion. The simple case works for me.

**Comment by chrmarti** [comment]
Closing after not having received additional information.
