### ISSUE TITLE
[Question] File explorer jumps when closing files

### ISSUE THREAD

**Issue by felixsanz** [Microsoft/vscode#16034]
This is very annoying UX.

If you are editing a file and then you close it, then the editor focus on another file (obviously).

But when this happens, the File Explorer jumps to that file!

This is very very disturbing because if I want to edit 2 files from the top of my File Explorer, this happens:

1. Scroll tree view to top (to find my first file)
2. Edit it, close file.
3. Editor moves my tree view again to the bottom! <--- This shouldn't happen!
4. Scroll AGAIN tree view to top (to find my second file) <--- This shouldn't happen!
5. Edit it, close file.

It is possible to change this? how?

**Comment by bpasero** [comment]
@felixsanz try `"explorer.autoReveal": false`

**Comment by kiddy2910** [comment]
So, if i turn off autoReveal, what hotkey to scroll to file

**Comment by bpasero** [comment]
The command would be `workbench.files.action.showActiveFileInExplorer`
