### ISSUE TITLE
Merge editor checkboxes feel very far from code

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#160371]
One observation when using the merge editor was that the checkboxes feel very distant from the actual code being selected.

<img width="755" alt="CleanShot 2022-09-07 at 20 03 08@2x" src="https://user-images.githubusercontent.com/25163139/189024715-d4ed583c-a511-45b6-9f90-c0b97d728ae5.png">

Note the equivalent design in VS Win:

<img width="577" alt="CleanShot 2022-09-07 at 20 04 31@2x" src="https://user-images.githubusercontent.com/25163139/189024814-e82da36b-11f0-422b-ae53-9149aef843f9.png">

cc @isidorn mentioned the folding chevron area in another issue. Seems like we should use that real estate for these instead of leaving it empty. I understand there are some technical challenges here.

**Comment by hediet** [comment]
We definitely can explore that! It is a technical challenge though. Currently, the checkbox gutter is outside of the editor, this would bring it into the editor.

**Comment by isidorn** [comment]
I like this idea. We got a lot of feedback that users can not find the checkboxes. Having them closer to the code would help. Also we would save valuable screen real estate.
