### ISSUE TITLE
New files randomly opened

### ISSUE THREAD

**Issue by BenjaminMickler** [microsoft/vscode#160395]
Type: <b>Bug</b>

As I use VS Code, new files are randomly created. A tab named 'Untitled-1' will randomly appear, then a few minutes later another, this time 'Untitled-2' and so on. Being 17, I don't have any experience with submitting bug reports so I'm not sure how I am to explain how to reproduce the issue. I am relatively new to VS Code and initially installed a bunch of extensions, used it without problems for a number of weeks and then this started to happen. I am happy to provide further information/descriptions, please just let me know what.

VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:36:25.715Z)
OS version: Linux x64 5.19.4-200.fc36.x86_64
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A6-9220e RADEON R4, 5 COMPUTE CORES 2C+3G (2 x 1796)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|15.09GB (5.98GB free)|
|Process Argv|--crash-reporter-id 6ebd87ed-764a-4344-9397-251d8725d7e6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|sway|
|XDG_CURRENT_DESKTOP|undefined|
|XDG_SESSION_DESKTOP|sway|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|12.2.2
prettier-vscode|esb|9.8.0
code-runner|for|0.11.8
copilot|Git|1.44.6735
remotehub|Git|0.42.0
vscode-pull-request-github|Git|0.48.1
better-cpp-syntax|jef|1.15.19
vsc-python-indent|Kev|1.17.0
pylint|ms-|2022.4.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.7.1102252217
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.8
live-server|ms-|0.4.0
remote-repositories|ms-|0.18.0
sqltools|mtx|0.24.0
autodocstring|njp|0.6.1
vscode-print|pdc|0.9.30
quicktype|qui|12.0.46
cmake|twx|0.0.17
vscode-arduino|vsc|0.4.12
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by BenjaminMickler** [comment]
I have been using VS Code for some time with extensions disabled without the issue. It looks like you are right. I will disable all of my extensions and enable them again one at a time with some usage of VS Code in between to determine which one is causing the issue. I will then report the bug to the extension's developers. Thank you for your help.
