### ISSUE TITLE
Consider consolidating commit hash and branch name

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#160358]
Ref #160182

Thinking about various ways to reduce clutter and noise. Not sure if there's any reason to keep the branch aligned right and the commit to the left. Especially since we're looking at adding more actions via #158890. What if we just combined them with a separator e.g.

<img width="1148" alt="CleanShot 2022-09-07 at 15 18 17@2x" src="https://user-images.githubusercontent.com/25163139/188993463-aa84770f-c32a-4f49-b35c-802731844ce7.png">

cc @hediet @isidorn

**Comment by hediet** [comment]
It would also be nice if we could show more information about the commits somehow (maybe a hover or a clickable label). The hash doesn't really help, unless I have a different tool to look it up.
