### ISSUE TITLE
Better preserve merge editor vs inline conflict experience

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#160316]
1. Have a conflict, click on the file in the SCM view. merge editor is opened
2. Click on the "Open File" command in the title area -> file with inline diffs gets opened
3. Close all editors
4. Open a conflicting file again in the SCM view. merge editor is opened 👎 

I understand that this is currently by design. But I am arguing that it would be a better user experience if we remembered the mode the user opened and then treat that as the new "default" without the user having to discover the setting.

I understand that the problem is that the actions just open a new editor, and that in fact both editors would be there. So here's a rough proposal. I am not sure if it makes sense so let me know what you think:
1. Open in merge editor and title menu Open File actions open the other editor, but close the current one
2. We remember what editor the user used last
3. Next time we open that editor when there is a conflict

fyi @daviddossett @bpasero

**Comment by bpasero** [comment]
I find that a confusing behaviour and unexpected UX because we do not really open editors like that. We have a way to configure default editors based on file paths by the user and that is a setting. But now we take that to a level that imho is quite implicit and hard to understand after the fact.

Why would a user jump from a merge editor to the actual editor? To resolve the merge conflict via merge markers?

**Comment by daviddossett** [comment]
Something I've been thinking about is whether we should have the inline conflict experience be the default view when merging, clicking on the SCM view, or any other entry point. We could then position the merge editor as the "powerful" view that they can click to open—we have the blue editor button today as one such entry point. 

I suppose the assumption I'm questioning is whether the merge editor should be the primary UI with which to handle conflicts given the feedback we've been hearing. Are the clear majority of conflicts complex enough to need it as the primary experience? Not sure if we have any sort of way to measure that.

**Comment by bpasero** [comment]
Not sure, with the same argument, why do we show a diff editor with 2 sides when we could just show the diff as a patch [1]? I think we do, because our diff editor allows to better understand the change. And I think the merge editor by default should do the same for merges.

[1] example

```patch
diff -rBNu src.orig/java/org/apache/nutch/analysis/NutchAnalysisConstants.java src/java/org/apache/nutch/analysis/NutchAnalysisConstants.java
--- src.orig/java/org/apache/nutch/analysis/NutchAnalysisConstants.java 2009-03-10 11:34:01.000000000 -0700
+++ src/java/org/apache/nutch/analysis/NutchAnalysisConstants.java  2009-03-10 14:11:55.000000000 -0700
@@ -4,9 +4,12 @@

+  int CJK = 21;
+  int DIGIT = 22;

   int DEFAULT = 0;

   String[] tokenImage = {
     "<EOF>",
+    "\"OR\"",
     "<WORD>",
     "<ACRONYM>",
     "<SIGRAM>",
```

**Comment by hediet** [comment]
@bpasero I think the diff editor is just much easier to understand - it is very obvious what it does.

However, neither git conflict markers nor a proper 3-way merge editor are very easy to understand. I think of both, conflict markers are easier to deal with, even if one doesn't understand their purpose. There is no UI state, it is just text.

**Comment by isidorn** [comment]
With the latest direction we are discussing I do not think any action will be needed here. Thus closing.
Thanks for the discussion!
