### ISSUE TITLE
multi-cursor can't work when type using snippets with placeholders

### ISSUE THREAD

**Issue by Xioqua** [Microsoft/vscode#16037]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

When in VScode:

![multi-cursorsnippet](https://cloud.githubusercontent.com/assets/22351236/20606309/05f7699e-b2ab-11e6-94fb-c7d342a87a57.gif)

When in Sublime Text3:

![multi-cursorsnippetsublime](https://cloud.githubusercontent.com/assets/22351236/20606377/7b165a3c-b2ab-11e6-84c7-35e15d56fd7d.gif)

**Comment by ramya-rao-a** [comment]
Interestingly, this works if snippet doesnt have placeholders

**Comment by jrieken** [comment]
Yeah - we added a bit of mutlicursor support on top of our rusty implementation but the full deal requires some more engineering...

**Comment by tylerb** [comment]
Adding my squeaky wheel here as well. I'd love to see this fixed.

**Comment by jrieken** [comment]
implemented via https://github.com/Microsoft/vscode/pull/26042
