### ISSUE TITLE
Build failed while downloading electron step

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#160392]
https://dev.azure.com/vscode/VSCode/_build/results?buildId=72757&view=logs&j=f3dd96f0-7bf9-51c6-1e87-22c4cfa2ad69&t=278fac50-8c5c-5c6d-5d30-d3fabe025fdf

**Comment by bpasero** [comment]
Can we add a retry?

**Comment by bpasero** [comment]
Thanks!
