### ISSUE TITLE
VS code editor showing extra space towards right side of IDE in MAC Book

### ISSUE THREAD

**Issue by RaghuG1** [microsoft/vscode#160306]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. Launch VS code and create some flutter project.
2. There is a extra space created in layout towards right side which obviously is not extra tab/mini map etc. PFA.
<img width="1676" alt="Screenshot 2022-09-07 at 7 19 42 PM" src="https://user-images.githubusercontent.com/54427704/188896086-c734423b-18ea-43f1-af74-f28d38c85841.png">

**Comment by IllusionMH** [comment]
Looks like it's regular vertical ruller at 80 characters or something like that.

**Comment by chrmarti** [comment]
@RaghuG1 That looks like a vertical ruler (thanks @IllusionMH), please check your settings:
<img width="941" alt="image" src="https://user-images.githubusercontent.com/9205389/189600485-76f4fde3-c488-48f2-b106-e1e33b8d5689.png">

**Comment by RaghuG1** [comment]
Thanks @IllusionMH @chrmarti, Updated ruler info in ~/Library/Application Support/Code/User/settings.json, worked perfectly
