### ISSUE TITLE
 ES6 spread syntax in array is throwing errors

### ISSUE THREAD

**Issue by asotog** [Microsoft/vscode#16039]
- VSCode Version: 1.7.1
- OS Version: OSX Capitan

Steps to Reproduce:

Using ES6 spread syntax in array is throwing errors, please see the attached screencap:
<img width="730" alt="screen shot 2016-11-24 at 1 59 14 pm" src="https://cloud.githubusercontent.com/assets/813023/20609127/64bf483c-b24e-11e6-96d0-9526d40e54a0.png">

But webpack is compiling fine, so the error is only on editor

**Comment by jurosh** [comment]
It's new ES7 feature. I had same issue and **temporary** fix is to disable js checking by setting `"javascript.validate.enable": false` and adding eslint checking only with EsLint extension and .eslintrc.

**Comment by asotog** [comment]
thanks so much that works for me, let's wait to see if this is duplicated
