### ISSUE TITLE
Keeps signing me out of account

### ISSUE THREAD

**Issue by Magicoo51889** [microsoft/vscode#160359]
Type: <b>Bug</b>

I'm using github to sign into visual studio code on my mac m1, and each time I quit and reopen vscode, I have to sign back in again, for both my account and to sync settings with github copilot. 

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 6, 6|
|Memory (System)|16.00GB (1.41GB free)|
|Process Argv|--crash-reporter-id 0eca622c-e137-4f55-94b8-904912aaf632|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-preview-github-styles|bie|1.0.1
doxdocgen|csc|1.4.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.2.2
vscode-npm-script|eg2|0.3.28
prettier-vscode|esb|9.8.0
font-switcher|eva|4.1.0
vscode-firefox-debug|fir|2.9.8
copilot|Git|1.44.6735
better-cpp-syntax|jef|1.15.19
styled-components-snippets|jon|0.10.0
mongodb-vscode|mon|0.9.3
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.8.50
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
vscode-typescript-next|ms-|4.9.20220905
LiveServer|rit|5.7.9
vscode-nand2tetris-hdl|rob|0.1.1
p5-vscode|sam|1.2.11
vscode-icons|vsc|11.16.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by TylerLeonhardt** [comment]
Can you provide the contents of the GitHub Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by TylerLeonhardt** [comment]
@Magicoo51889  Unfortunately, images don't attach properly when you respond via email. You need to come over to the website to share images.

**Comment by Magicoo51889** [comment]
It seems to have fixed itself overnight actually. Not sure what happened but it’s fine now
