### ISSUE TITLE
vscode insiders: ctrl+click on declaration doesnt show references anymore

### ISSUE THREAD

**Issue by 1muen** [microsoft/vscode#160300]
### It works in Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Datum: 2022-09-01T07:22:41.992Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0

1. ctrl+left mouse click on a declaration moves the cursor to the reference if only one exists:

https://user-images.githubusercontent.com/49640488/188890009-d7b59c62-0bd9-4a24-8dc2-4511baff1f7b.mp4

2. ctrl+left mouse click on a declaration moves the cursor opens the reference menue if only multiple references exist:

https://user-images.githubusercontent.com/49640488/188890027-1a7521fb-32a2-419e-9ad9-39a50dc1f3a6.mp4

### It doesnt work in Version: 1.72.0-insider
Commit: 0f2de31e4856886cdbf32f85488bc40f480fb38f
Datum: 2022-09-07T05:15:40.689Z
Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:105.0) Gecko/20100101 Firefox/105.0
(Also doesnt work on the Desktop Electron App.)

https://user-images.githubusercontent.com/49640488/188890053-08806a38-fd85-4224-946b-ac7751722d81.mp4

### To reproduce:
install the versions I listed above or use https://vscode.dev/ and https://insiders.vscode.dev/ you may use this example code 😉😄  : 
```TypeScript
const thingsILike = ["linux", "vscodium", "freeSoftware"]
const sayNiceThings = (thing: string) => {
    console.log("Thanks for making "+ thing + ", I really like it! :)")
}
thingsILike.forEach((thing)=>sayNiceThings(thing))
thingsILike.forEach((thing)=>sayNiceThings(thing))
thingsILike.forEach((thing)=>sayNiceThings(thing))
```

Maybe it has something to do with this: https://github.com/microsoft/vscode/issues/155800#issuecomment-1191443830

**Comment by 1muen** [comment]
@jrieken Its the default:
"editor.gotoLocation.alternativeDefinitionCommand": "editor.action.goToReferences"
![grafik](https://user-images.githubusercontent.com/49640488/188908390-e696f002-f3ac-4b11-b2e8-25f902aa4bec.png)

I used https://insiders.vscode.dev/ without any account. So no custom settings or extensions. :)

If I use another setting like
"editor.gotoLocation.alternativeDefinitionCommand": "editor.action.referenceSearch.trigger"
it also doesnt work.

**Comment by jrieken** [comment]
Does "Peek References" or "Go to References" work when invoked on that symbol? 

btw - this works for me using Safari or FF

**Comment by 1muen** [comment]
yes
https://user-images.githubusercontent.com/49640488/188911933-ed302539-43f3-4f84-a8df-978a9a83b3ca.mp4

**Comment by 1muen** [comment]
are you using https://insiders.vscode.dev/ with your account, or in a privat window? It also doesnt work for me in other chromium based browsers, like brave nightly.

**Comment by 1muen** [comment]
The bug is also happening if I choose english as a language and or keyboard layout.

**Comment by zedd3v** [comment]
The same thing is happening to me, I'm on insiders

Version: 1.72.0-insider
Commit: 0f2de31e4856886cdbf32f85488bc40f480fb38f
Date: 2022-09-07T05:18:06.866Z (1 day ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

**Comment by felipe-linares** [comment]
> The same thing is happening to me, I'm on insiders
> 
> Version: 1.72.0-insider Commit: [0f2de31](https://github.com/microsoft/vscode/commit/0f2de31e4856886cdbf32f85488bc40f480fb38f) Date: 2022-09-07T05:18:06.866Z (1 day ago) Electron: 19.0.12 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 21.6.0 Sandboxed: Yes

Same here

**Comment by DFelten** [comment]
Same here. This is no longer working with the latest VSCode Insider version. For me it's not working with Dart code. If the usage is in the same file and there is only one, it will not jump there either.

**Comment by jrieken** [comment]
I managed to reproduce with the steps in #160785
