### ISSUE TITLE
Opening of unsupported files

### ISSUE THREAD

**Issue by andersborgabiro** [microsoft/vscode#160345]
Type: <b>Feature Request</b>

When double-clicking on any unsupported file (e.g. a Word file) I get the message "The file is not displayed in the editor because it is either binary...". 

Wouldn't it have been better to have the OS's file associations kick in and open the file separately?

Oftentimes I combine code folders with document folders in the same folder tree, so opening e.g. Word files with specifications, notes etc, or Excel files with priorities etc are a given. The way it works now I need to have Windows Explorer (etc) open too to be able to open unsupported files.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by lramos15** [comment]
https://marketplace.visualstudio.com/items?itemName=sandcastle.vscode-open
