### ISSUE TITLE
When I use Chinese the VS code become very very slow !

### ISSUE THREAD

**Issue by meinei1333** [Microsoft/vscode#1603]
Every time when I switch to the Chinese input method my VS code become very slow and it only happen in this Version 0.10.5 (0.10.5).

**Comment by be5invis** [comment]
Maybe related to #1463

**Comment by bpasero** [comment]
Once we released 0.10.6, we need to revisit this issue and see if speed is still slow. i am not sure this is #1463 because that bug causes code to not even start.

**Comment by meinei1333** [comment]
I upgrade to Version 0.10.6 (0.10.6) that cant't open when use Chinese input method was fixed, 
but sometime VS code still become slow I don't sure it whether about Chinese input method.
I wrote ES6 and in IOS 10.11.2.

**Comment by bpasero** [comment]
With this little info it is very hard to understand if there is any issue. Do you not see the slowdown when keeping the input method to english?

**Comment by bpasero** [comment]
Reopen with more info.
