### ISSUE TITLE
Cannot click maximize or minimize button on title bar with Windows tablet mode.

### ISSUE THREAD

**Issue by huajingyu** [microsoft/vscode#160433]
Type: <b>Bug</b>

Cannot click maximize/minimize button to maximize/minimize "Visual Studio Code" window with tablet mode. (But doble-click title bar is can maximize/minimize VSCode window.)
(I am using Surface Pro 7 with external keyboard, mouse and display, and Type-cover is closeed.)
Please update chromium in Visual Studio Code, because new version of Chrome/chromium has solved this case.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.60GB (5.49GB free)|
|Process Argv|--crash-reporter-id aa907e00-7f33-4aa6-85a5-6b03fd8021bf|
|Screen Reader|no|
|VM|17%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.15.19
vscode-language-pack-zh-hans|MS-|1.71.9070915
csharp|ms-|1.25.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/159851
