### ISSUE TITLE
[ERROR]: C# Extension failed to install the debugger package

### ISSUE THREAD

**Issue by AhmedMoosa** [Microsoft/vscode#16043]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: C# Extension from Microsoft.

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.2.2|
|tcl|rashwell|0.1.0|

---

Steps to Reproduce:

1. Install c# extension , by click install .
2. Click reload.
3. After restarting (to complete installation ) , vs code start downloading OmniSharp  (86x),
4. Getting that the installation complete and got this message [ERROR]: C# Extension failed to install the debugger package
5. Another message at the top display :
"An error occured during installation of the .NET Core Debugger. The C# extension may need to be reinstalled."

I tried the same steps more than once , and the result ,

Thank You

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#994
