### ISSUE TITLE
Wildcard support for `onCommand` in `activationEvents` config

### ISSUE THREAD

**Issue by mitskevich** [Microsoft/vscode#16045]
- VSCode Version: 1.7.2
- OS Version: OS X El Capitan

It would be nice to have wildcards support for `onCommand:` in `activationEvents` configuration. Currently most (all?) extension's command contributions have to be duplicated in the `activationEvents` section (and managed accordingly when commands are added/removed).

For example, if I understand correctly, [all these lines here](https://github.com/DonJayamanne/pythonVSCode/blob/1f2f3f854031c8193a79b7e31dc47cbd4ac8ab86/package.json#L45-L55) could be replaced with single `onCommand:python.*`

Maybe related to #944.

**Comment by alexandrudima** [comment]
Great suggestion! This is a good opportunity for a PR!

The logic is here -- https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensions/common/abstractExtensionService.ts#L274

Currently, it uses an `_activationMap` to quickly determine what extension should get activated on a specific event. Any PR that proposes a change in here should take into account that this method is called very often and should propose a fast implementation for determining what extension should get activated based on the current activation event.

**Comment by Gama11** [comment]
Hm, I've actually been looking forward to having an easier / less redundant way of handling this (as the issue creator mentioned, this causes a lot of duplication in a lot of extensions). Any chance this could be reconsidered (seems it's been closed automatically by the bot?).
