### ISSUE TITLE
[java] JavaDoc syntax coloring doesn't work on closing tags

### ISSUE THREAD

**Issue by fbricon** [Microsoft/vscode#16041]
This is a follow up on #15527 

- VSCode Version: 1.8.0-insider 6a6ab1fc5e58227b56ffc3e5bea9951e5565c314
- OS Version: macOS 10.12

Steps to Reproduce:

1. Create a java file with some Javadoc and some html tags in it.
2. Only the opening html tags are colored properly, not the closing ones (see `</p>` below)

<img width="358" alt="capture d ecran 2016-11-24 a 16 30 07" src="https://cloud.githubusercontent.com/assets/148698/20610173/fb12c95c-b263-11e6-9080-a40baff63dca.png">

cc @gorkem

**Comment by fbricon** [comment]
Coloring works as expected in TextMate

**Comment by aeschli** [comment]
TextMate doesn't seem to use the latest grammar version from https://github.com/textmate/javadoc.tmbundle.

I created
https://github.com/textmate/javadoc.tmbundle/pull/3
