### ISSUE TITLE
Terminal:Run Recent Command does nothing

### ISSUE THREAD

**Issue by mvbc85** [microsoft/vscode#160471]
Type: <b>Bug</b>

Ctrl+Shift+P
Search for "Terminal: Run Recent Command..."
Expected: A list of recent commands to pick from
Actual: Nothing happens

I disabled all extensions and the behavious is the same

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-10855M CPU @ 2.80GHz (12 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (34.56GB free)|
|Process Argv|--crash-reporter-id 09c6b40f-a0e9-46af-ab04-46adad5b730c|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by mvbc85** [comment]
Thanks for the help @meganrogge 
Just downloaded and installed the Insiders build.
Same issue.

![a4fbab84b4574c58a1aa74aa015363ec-0_sZuqyV2o](https://user-images.githubusercontent.com/34232584/189562005-31d3bd46-4fba-4f06-96eb-f4dfabe9d415.gif)

Sorry for the potato quality of the GIF

**Comment by meganrogge** [comment]
It looks like shell integration is disabled for you - could you provide me w your settings and/or hover over the powershell tab title?

**Comment by mvbc85** [comment]
Integration with Bash was activated but not with PowerShell
I followed the instructions in the [Terminal Shell Integration](https://code.visualstudio.com/docs/terminal/shell-integration) document, reloaded the window and now the command is working!
Thanks for your help

**Comment by mvbc85** [comment]
Seems like I spoke to soon, @meganrogge 
I'm getting all sorts of errors now and can't get the Shell integration to work.

You said to provide you with my settings, what is the best way to do that?

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.

**Comment by mvbc85** [comment]
## System Details
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

## Extensions
<details>
<summary>Extensions</summary>
BeardedBear.beardedicons
BeardedBear.beardedtheme
donjayamanne.githistory
eamodio.gitlens
johnpapa.vscode-peacock
jprestidge.theme-material-theme
mhutchie.git-graph
mohsen1.prettify-json
ms-dotnettools.dotnet-interactive-vscode
ms-python.python
ms-python.vscode-pylance
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
oderwat.indent-rainbow
PeterSchmalfeldt.explorer-exclude
PKief.material-icon-theme
RobbOwen.synthwave-vscode
samuelcolvin.jinjahtml
Shan.code-settings-sync
vscode-icons-team.vscode-icons
</details>

## Screenshots
![image](https://user-images.githubusercontent.com/34232584/191165670-226c76ce-db71-4403-a757-6977ef5c03c3.png)
![image](https://user-images.githubusercontent.com/34232584/191165798-e701d7d6-2b8c-47ff-bc26-c64763e660eb.png)

## Settings file
[settings.zip](https://github.com/microsoft/vscode/files/9603979/settings.zip)

**Comment by meganrogge** [comment]
on Windows, can you try to use a newer version of powershell instead of windows pwsh? that will probably fix it.

related to `bash`, could you pls provide your `.bashrc` and `.bash_profile`?

**Comment by mvbc85** [comment]
Both files were empty

I've gone ahead and added the following line to the `.bashrc` file, as per [the Terminal Shell Integration
 instructions](https://code.visualstudio.com/docs/terminal/shell-integration):
`[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path bash)"`

When I do that, every time I launch the terminal, I get the following error message:

`bash: Warning: 'locate-shell-integration-path' is not in the list of known options, but still passed to Electron/Chromium.: No such file or directory`

And a new VS Code window is launched.


Regarding Powershell, I've updated to version 7.2.6 but I'm getting a similar issue:

![image](https://user-images.githubusercontent.com/34232584/191875793-cd3aa6fd-8e3b-4abe-b38f-aca67efa581d.png)

**Comment by meganrogge** [comment]
this will only work on `pwsh` not on `windows pwsh` or the powershell extension terminal
