### ISSUE TITLE
Default build task asks for task

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160404]
This only started in todays insider build, I am running `workbench.action.tasks.runTask` and see this:

![image](https://user-images.githubusercontent.com/900690/189115986-32d9a2d1-cd92-4e93-a288-2d311d6431fe.png)

This used to just compile `vscode`.

//cc @alexr00

**Comment by meganrogge** [comment]
This is actually unrelated to my changes and only reproduces in a multi-root repo.

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/blob/872c9079b137119777a4afc2c6f047d4eee8d329/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L2990-L3008

**Comment by meganrogge** [comment]
reproduces in stable

**Comment by meganrogge** [comment]
This would require adding a `workspaceFolder` specific argument to run task

**Comment by bpasero** [comment]
Just to clarify: this is a regression from stable and even worked fine a few days ago. I forgot to mention how I have setup the keybinding:

```
{
    "key": "cmd+shift+alt+b",
    "command": "workbench.action.tasks.runTask",
    "args": "Restart VS Code - Build"
}
```

This used to just run the task but now asks me for input, maybe something else has changed? But the name of the task still seems to be `Restart VS Code - Build`. 

https://github.com/microsoft/vscode/blob/e373bdd2fc0458919fceca1d8f112eb4344cf5a8/.vscode/tasks.json#L106

**Comment by bpasero** [comment]
Actually what is interesting: the task seems to restart, but I still see the picker? That is strange 🤔

**Comment by meganrogge** [comment]
Thanks for the info - can repro w your setup 👍🏼
