### ISSUE TITLE
Slow Startup. Takes up to 60 seconds

### ISSUE THREAD

**Issue by Poldi321** [microsoft/vscode#160488]
Type: <b>Performance Issue</b>

Slow Startup. Takes up to 60 seconds.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (20.30GB free)|
|Process Argv|--crash-reporter-id 6be35206-e24a-4299-a892-a13417f40a1d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   106	 30920	code main
    0	    58	  7584	   issue-reporter
    0	    76	 10492	   extensionHost
    0	    34	 20920	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\server\dist\node\main" --node-ipc --clientProcessId=10492
    0	    26	 17312	   utility-network-service
    0	    23	 20460	   utility
    0	   192	 25608	   window (Startup Performance - Visual Studio Code [Administrator])
    0	    28	 29676	   utility
    0	   193	 30008	   shared-process
    0	    46	 16900	     ptyHost
    0	     7	 29284	       winpty-process
    0	    70	  6336	         C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    12	 30512	         console-window-host (Windows internal process)
    0	    35	 18360	     fileWatcher
    0	   272	 31552	   gpu-process
    0	    14	 32600	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by Poldi321** [comment]
## Performance Marks

| What                                                            | Duration | Process                   | Info                                                         |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------------------------ |
| start => app.isReady                                            | 10827    | [main]                    | initial startup: true                                        |
| nls:start => nls:end                                            | 1        | [main]                    | initial startup: true                                        |
| require(main.bundle.js)                                         | 73       | [main]                    | initial startup: true                                        |
| start crash reporter                                            | 10762    | [main]                    | initial startup: true                                        |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                        |
| create window                                                   | 266      | [main]                    | initial startup: true, state: 0ms, widget: 17ms, show: 249ms |
| app.isReady => window.loadUrl()                                 | 397      | [main]                    | initial startup: true                                        |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 31901    | [main->renderer]          | NewWindow                                                    |
| require(workbench.desktop.main.js)                              | 256      | [renderer]                | cached data: YES, node_modules took 0ms                      |
| wait for window config                                          | 0        | [renderer]                | -                                                            |
| init storage (global & workspace)                               | 40       | [renderer]                | -                                                            |
| init workspace service                                          | 31       | [renderer]                | -                                                            |
| register extensions & spawn extension host                      | 6089     | [renderer]                | -                                                            |
| restore viewlet                                                 | 0        | [renderer]                | -                                                            |
| restore panel                                                   | 62       | [renderer]                | terminal                                                     |
| restore & resolve visible editors                               | 93       | [renderer]                | 1: workbench.editors.gettingStartedInput                     |
| overall workbench load                                          | 354      | [renderer]                | -                                                            |
| workbench ready                                                 | 43786    | [main->renderer]          | -                                                            |
| renderer ready                                                  | 667      | [renderer]                | -                                                            |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                            |
| extensions registered                                           | 49998    | [renderer]

**Comment by Poldi321** [comment]
[code-8iJ70fiR.trace.txt](https://github.com/microsoft/vscode/files/9533236/code-8iJ70fiR.trace.txt)

**Comment by Poldi321** [comment]
[code-8iJ70fiR.trace.txt](https://github.com/microsoft/vscode/files/9533260/code-8iJ70fiR.trace.txt)

**Comment by Poldi321** [comment]
I also get window "The window is not responding"

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by Poldi321** [comment]
With nightly insider build VS Code opens without problem.

**Comment by Poldi321** [comment]
Thank you. :partying_face:
