### ISSUE TITLE
Terminal window not opening

### ISSUE THREAD

**Issue by dangeross** [microsoft/vscode#160441]
Type: <b>Bug</b>

Opening a terminal window from the menu Terminal > New Terminal flashes the terminal open then immediately closes

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|--crash-reporter-id f25a0ee3-9760-439b-a701-d552752ef488|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-nvm|abu|0.0.1
Bookmarks|ale|13.3.1
EditorConfig|Edi|0.16.4
vsc-material-theme|Equ|33.1.2
vsc-material-theme-icons|equ|1.2.2
prettier-vscode|esb|9.8.0
vs-code-xml-format|fab|0.1.5
go|gol|0.35.2
vscode-graphql|Gra|0.7.5
vscode-graphql-syntax|Gra|1.0.4
todo-tree|Gru|0.0.215
terraform|has|2.24.2
vscode-drawio|hed|1.6.4
rest-client|hum|0.25.1
cornflakes-linter|kev|0.5.1
restructuredtext|lex|189.1.0
vscode-docker|ms-|1.22.1
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
vscode-thunder-client|ran|1.18.7
rust|rus|0.7.8
preview-vscode|sea|2.2.5
markdown-preview-enhanced|shd|0.6.3
vscode-taskexplorer|spm|2.9.1
html-preview-vscode|tht|0.2.5
gitblame|wad|9.0.1
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by dangeross** [comment]
Sorry, it seems like restarting my mac solved the issue. Let me know if you still want the settings.json file else you can close the issue. Thanks!
