### ISSUE TITLE
copy/paste commands in notebooks can be swallowed by the wrong component 

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#160463]
Type: <b>Bug</b>

1. copy a cell
2. click on the bottom empty space in the notebook
3. paste
:bug: nothing happens - the webview has focus and so it is sent the command to be handled since it has higher priority

VS Code version: Code - Insiders 1.72.0-insider (2d27f8db6a19f93529787731b0efa8f001478f6d, 2022-09-08T05:16:42.710Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (8.22GB free)|
|Process Argv|--crash-reporter-id 1202dc88-403d-4ebc-8393-af3551a8bd5b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (28)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
tsl-problem-matcher|amo|0.6.2
wwbd|bre|2022.1.0
vscode-eslint|dba|2.2.6
python-environment-manager|don|1.0.4
gitlens-insiders|eam|2022.9.805
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.8.0
copilot|Git|1.44.6735
vscode-pull-request-github|Git|0.51.2022090809
vscode-test-explorer|hbe|2.21.1
svg|joc|1.4.19
prettify-json|moh|0.0.3
vscode-language-pack-de|MS-|1.71.9070920
python|ms-|2022.15.12511012
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.9.1002521044
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.252.0
remote-ssh|ms-|0.87.2022090715
remote-wsl|ms-|0.66.3
js-debug-nightly|ms-|2022.9.717
remote-explorer|ms-|0.1.2022090509
test-adapter-converter|ms-|0.1.6
vscode-github-issue-notebooks|ms-|0.0.119
vscode-js-profile-flame|ms-|1.0.4
vscode-yaml|red|1.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252

```

</details>

**Comment by movy** [comment]
Not sure if it's the same issue, but pasting python code in a small simple cell  lags or ignores cmd-v lots of times, i.e. I can press cmd+v 10 times and nothing would happen then suddely it pastes 2-3 copies of the same code.. Latest VSCode @ remote Ubuntu w/ Juputer Lab, accessed from local OSX.  Pasting always works via right click and I cannot observe any other key shortcuts being 'swallowed'. Everyting works fine it the notebook is open in Chrome, so seems to be a VSCode issue. 

I tried disabling various commands on paste, nothing helped. 
```  json
"[python]": {
        "editor.formatOnPaste": false,
        "editor.formatOnSaveMode": "file",
        "editor.autoIndent": "none",
        "editor.experimental.pasteActions.enabled": false
}
```

And debug logging for Jupyter seems to be gone?  Cannot see it in settings.

**Comment by ChuckJonas** [comment]
I think this might be related to https://github.com/microsoft/vscode-jupyter/issues/14923

**Comment by rebornix** [comment]
let's merge it into https://github.com/microsoft/vscode/issues/200255
