### ISSUE TITLE
Conflict looks different in inline vs. merge editor view

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#160462]
## Inline

Note all three lines highlighted with background color

<img width="262" alt="CleanShot 2022-09-08 at 16 01 57@2x" src="https://user-images.githubusercontent.com/25163139/189240750-001407b7-3b00-47f9-a3a0-e43364f9b25a.png">

## Merge Editor

We only highlight the changed line and specific word. 

<img width="184" alt="CleanShot 2022-09-08 at 16 02 04@2x" src="https://user-images.githubusercontent.com/25163139/189240805-eeca8c90-983b-49cb-9452-faf176a1894c.png">

If we followed the inline style and still rendered a word diff, wouldn't we be able to get away without using the borders to indicate the region?

cc @isidorn

**Comment by hediet** [comment]
> If we followed the inline style

The inline style does this because it has no clue about the actual conflict, it just sees the conflict markers.

> We only highlight the changed line and specific word.

We do this to show the actual change in that side.

**Comment by hediet** [comment]
I added a hidden setting `mergeEditor.useSimplifiedDecorations` (default false) so we can play with idea. @jrieken

Personally, I think it hides many important decorations, but I'm open to exploring it.

Enabled:
![image](https://user-images.githubusercontent.com/2931520/197530678-74958427-e6bb-4944-840a-68bc8dbed5d4.png)

Disabled:
![image](https://user-images.githubusercontent.com/2931520/197530727-c93ce476-288d-442f-9e88-c1ae25328fe0.png)
