### ISSUE TITLE
Urgent! NEED  Alt + mouse Pointer  function  to edit multiple text lines at the same time. It's very unconvenient to format code.

### ISSUE THREAD

**Issue by HectorChow** [Microsoft/vscode#16048]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. it's a common function of most editor and IDEs.
2.

**Comment by jrieken** [comment]
@HectorChow We do allow to set multiple cursor with alt+click. In case that isn't what you have meant please update this issue with precise steps that allow us to understand what you meant.

**Comment by HectorChow** [comment]
I use sqlserver editor to show you the situation
![image](https://cloud.githubusercontent.com/assets/8266902/21003705/ccf4633c-bd67-11e6-8199-f71892e20089.png)
look at the blue space selected via alt + click in red square. I can type tab key to move both the two line at once.
Below pic is  from vscode editor. When I use alt + click, the selected area is just like the pic.
![image](https://cloud.githubusercontent.com/assets/8266902/21003863/7dc4677a-bd68-11e6-8736-26e802379d37.png)
 Hope that I've already make it clear.
