### ISSUE TITLE
Custom keyboard shortcuts only available in the settings profile where they were created

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode#160440]
I cannot use custom keyboard shortcuts in a different settings profile than the one that created them. 

Steps to Reproduce:
1. Create two settings profiles
2. Create a custom keyboard shortcut in one of them
3. Try to use the above custom keyboard shortcut in the other settings profile

I would have expected custom keyboard shortcuts to be available in all settings profiles. 

Does this issue occur when all extensions are disabled?: Yes, in both setting profiles

> Version: 1.72.0-insider (system setup)
Commit: 2d27f8db6a19f93529787731b0efa8f001478f6d
Date: 2022-09-08T05:16:42.710Z
OS: Windows_NT x64 10.0.19044

**Comment by sandy081** [comment]
All user data (Settings, Keybindings, Extensions, UI State, Tasks & Snippets) are scoped per profile. Hence you cannot use them across.
