### ISSUE TITLE
Split settings into two file!

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#16044]
- VSCode Version: Code - Insiders 1.8.0-insider (fd4d938088d3ee94810daaa07ba9a234ecf89ca9, 2016-11-24T07:59:54.010Z)
- OS Version: Darwin x64 16.3.0

In current , we have `common settings` and `ui settings` in one file. As time going, this file becoming  more and more mass and bloated. And it's hard to find a setting item in it.
So i suggest split this file into `common` and `ui` setting.
While the `common` setting hold `editor` and `workbench` and `common` setting, and the `ui` setting hold those setting which can take effect on vsc's looks.

**Comment by sandy081** [comment]
@leaxoy Interesting idea but IMO it might not scale as each user has their own requirements of grouping. We have dome some considerable improvements to Settings in this milestone. So, I would ask you to try the latest insiders and share your experience to us. In short, we are trying to achieve easy discoverability of settings which I think you are targetting also.

Thanks

**Comment by leaxoy** [comment]
The new settings panel looks more efficient than the old one. However, if we can preview influences after a change made would be more tempting!
For example: if we change editor.fontSize, when we hover on new settings, we could pop a preview weight like an intellijsense weight dose.

**Comment by sandy081** [comment]
Closing this as we do not have plans in implementing this in next 12 months. It is also 1 year old feature request which is not often requested.
