### ISSUE TITLE
Add hook for customizing JS notebook renderer

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#160451]
Tracks letting extensions customize the default JS renderer for notebooks

This should allow them to modify the script before it is evaluated 

/cc @DonJayamanne

**Comment by mjbvz** [comment]
@DonJayamanne Not sure if this is still needed on your side but can you please verify the api? Would like to see if there are other use cases out there too

**Comment by DonJayamanne** [comment]
We are using this API in the Jupyter Renderers extension, thanks
