### ISSUE TITLE
Sticky Scroll does not work with indented .SASS syntax (no brackets or semicolons)

### ISSUE THREAD

**Issue by plagasul** [microsoft/vscode#160493]
'Sticky Scroll' does not work with indented .sass syntax (no brackets or semicolons), while it does with .scss syntax (brackets and semicolons).

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Linux Mint 20.1 Cinnamon

Steps to Reproduce:

1. Activate 'sticky scroll'
2. Open a .sass file and scroll to see sticky scroll does not work

**Comment by gjsjohnmurray** [comment]
Does your .sass file display useful information in the Outline view?

Are you using an extension to provide the language support for the file, or is it built-in?

**Comment by plagasul** [comment]
> Does your .sass file display useful information in the Outline view?
> 
> Are you using an extension to provide the language support for the file, or is it built-in?

As far as I understand, running code with extensions disabled rules out language support as the culprit?

In any case, yes, I use Syler.sass-indented

**Comment by gjsjohnmurray** [comment]
What I mean is, if your file doesn't show a nested structure in the Outline view then it won't have sticky scroll headers either. This is because sticky scroll currently uses the same information provider as Outline does. I think there's work going on to offer indentation as an alternative mechanism for determining the sticky headers.

Please run VS Code normally (i.e. not with all extensions disabled) and look at the Outline view for one of your .sass files. If it's empty, that's the issue. Maybe contact the extension author.

**Comment by plagasul** [comment]
Understood @gjsjohnmurray.

Outline seems ok, see:

![image](https://user-images.githubusercontent.com/13966673/189487396-9cede09f-133b-446a-bd5b-dd36fa303e92.png)

**Comment by gjsjohnmurray** [comment]
That's folding, not outline. Please use Command Palette to go to the Outline view.

**Comment by plagasul** [comment]
> That's folding, not outline. Please use Command Palette to go to the Outline view.

Apologies, I thought outline == minimap

Outline view shows "No symbols found in document..." for .sass files, unlike .scss, .js, .html or .php files

I am going to open an issue on the extension github page, see if that helps. 

Thanks

**Comment by aeschli** [comment]
We don't have built-in rich language support for sass, that's why you don't see any document symbols, outline, breadcrumbs.

This has to come from an extension from the marketplace. Maybe make a feature request to https://marketplace.visualstudio.com/items?itemName=Syler.sass-indented ?
