### ISSUE TITLE
renderWhitespace not work when fontFamily is "Hack, monospace"

### ISSUE THREAD

**Issue by yuanlinssdut** [Microsoft/vscode#1604]
```json
{
  "editor.fontFamily": "Hack, monospace",
  "editor.renderWhitespace": true,
}
```

**Comment by bpasero** [comment]
@alexandrudima I remember we talked about this once, I forgot the resolution though :)

**Comment by heaths** [comment]
It seems this is a problem with the Hack font. I noticed when I set the `editor.fontFamily` to "Consolas" the white space is rendered correctly and correctly spaced. With "Hack", space seems to actually be wider than a fixed-width space (like with "Consolas") causing alignments to be off:

``` javascript
// example render with "Consolas"
var gulp = require("gulp")
  , gutil = require("gulp-util")
  ;

// example render with "Hack"
var gulp = require("gulp")
    , gutil = require("gulp-util")
    ;
```

**Comment by alexandrudima** [comment]
@heaths I'm also loving Hack :+1: 

See chrissimpkins/Hack#78.

Please update to Hack v2.011 or higher.

**Comment by heaths** [comment]
Beautiful, thanks!

**Comment by yuanlinssdut** [comment]
thanks~ 😊
