### ISSUE TITLE
Multiple „Do you want to save changes… ?“ dialogs

### ISSUE THREAD

**Issue by tsabolov** [Microsoft/vscode#16049]
- VSCode Version: Code - Insiders 1.8.0-insider (ced1d697f81499df60b00d3a02ab264e5e0c99e4, 2016-11-25T07:05:03.920Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|beautify|HookyQR|0.5.5|
|vscode-docker|PeterJausovec|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-csscomb|mrmlnc|3.2.4|
|vscode-icons|robertohuertasm|4.0.1|
|vscode-nginx|shanoor|0.3.0|
|language-stylus|sysoev|1.6.0|

---

Steps to Reproduce:

1. Open/create file in VSCode
2. Change file (so its status become unsaved)
3. Press `Cmd+W` multiple times to close file (I want to close open files sequentially)
4. When „Do you want to save changes… ?“ dialog appears, press `Esc` to get rid of it (say, you changed your mind, and do not want to close it anymore)

Expected behavior:

„Do you want to save changes… ?“ dialogs dissapears and editor is available for editing again.

Actual behavior:

„Do you want to save changes… ?“ dialog for changed file is shown as many times as `Cmd+W` was presed.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11928
