### ISSUE TITLE
MacOS: Ctrl + click (equivalent to Right-click) on an Editor tab doesn't open the context menu on vscode web

### ISSUE THREAD

**Issue by guiherzog** [microsoft/vscode#160413]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0 (vscode.dev)
- OS Version: macOS 12.5.1 (21G83)

Steps to Reproduce:

1. Open any file on `vscode.dev`.
2. On the filename tab on the "Editor", hold `Ctrl` + Click on it (the same as a right-click or two-finger click on macOS).
See the image below
![AHbWdngqAx2DYQj](https://user-images.githubusercontent.com/3836025/189134850-8010a6ad-52ef-4701-9dea-78242eccf5a9.png)

**Expected**: it opens the context menu with options about the file.
**Actual**: it blinks the context menu for a fraction of a second.

A screencast of the problem:
![right-click-issue](https://user-images.githubusercontent.com/3836025/189135654-142fa288-492f-419c-ad18-1d4f016d6b41.gif)

The problem doesn't happen on VS Code desktop.

**Comment by sbatten** [comment]
is this ctrl+click behavior mac specific?

**Comment by guiherzog** [comment]
I am not entirely sure, but so far, we have only seen reports about this issue on macOS.

**Comment by mueheg** [comment]
Yes, Macs by default consider CTRL+Click a right click. This works across the entire OS.

**Comment by guiherzog** [comment]
This is great, thanks for the fix!
