### ISSUE TITLE
CWD command in launch.json cannot work when opening VSCode

### ISSUE THREAD

**Issue by Spritea** [microsoft/vscode#160457]
Type: <b>Bug</b>

# Behaviour
## Expected vs. Actual

Expected: cwd command works correctly
Actual: it doesn't work

## Steps to reproduce:

1. Close VSCode and then Open it
2. Start to debug with a custom configuration in launch.json, and the configuration contains cwd command
3. The VSCode would complain that it cannot open the directory pointed by the cws command, even though the directoy actually exists
4. If we simply comment the cwd command in launch.json, and start the debug session, and then exit after a while, we could uncomment the cwd command, and start the original debug session. Then it works as expected.

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.8.13
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Conda
-   Value of the `python.languageServer` setting: Default

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• pylintArgs: "<placeholder>"

terminal
• executeInFileDir: "<placeholder>"

```

</p>
</details>

Extension version: 2022.14.0
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-121-generic
Remote OS version: Linux x64 5.4.0-121-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.74GB free)|
|Process Argv|--crash-reporter-id 150a1c5a-ede2-4cc7-adbd-fa0af3a861fe|
|Screen Reader|no|
|VM|57%|

|Item|Value|
|---|---|
|Remote|SSH: server_a100|
|OS|Linux x64 5.4.0-121-generic|
|CPUs|AMD EPYC 7452 32-Core Processor (128 x 1457)|
|Memory (System)|251.80GB (111.99GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: server_a100|
|OS|Linux x64 5.4.0-121-generic|
|CPUs|AMD EPYC 7452 32-Core Processor (128 x 1457)|
|Memory (System)|251.80GB (111.91GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by roblourens** [comment]
Yes, the `cwd` should be an absolute path, in fact the description specifically says it must be

<img width="536" alt="image" src="https://user-images.githubusercontent.com/323878/189460644-d6b03dcb-52f5-4a73-91aa-a9819f242bb5.png">
