### ISSUE TITLE
Blurred terminal

### ISSUE THREAD

**Issue by ctrl-Sebastian** [microsoft/vscode#160456]
My temrinal is blurred and i cannot read anything. Im on my codespace of cs50

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by ctrl-Sebastian** [comment]
i fixed it by turning off the gpu acceleration
