### ISSUE TITLE
set stickyScroll style/colors

### ISSUE THREAD

**Issue by dlordi** [microsoft/vscode#160417]
it would be nice if stickyScroll could have a different background color or a different font style so that it can be easly spotted while scrolling source code... great job btw!

**Comment by ArturoDent** [comment]
There are these `colorCustomizations` at present:

```jsonc
  "workbench.colorCustomizations": {

    "editorStickyScroll.background": "#c9c7c7",
    "editorStickyScrollHover.background": "#ff0000"
```

**Comment by dlordi** [comment]
thanks, that's what I was looking for!
