### ISSUE TITLE
jsconfig path alias' linting issue

### ISSUE THREAD

**Issue by Termina94** [microsoft/vscode#160521]
Type: <b>Bug</b>

vscode will only load jsconfig file at rough directory of opened folder.

If a project has other projects inside, opening a subsirectory as your workspace will cause the jsconfig to not be read

Thie will result in eslint errors for imports as it is expecting a jsconfig file, which does exist but further up the file tree than the current working directory folder

tl;dr: vscode needs to check further  up the file tree for a jsconfig if there is not one found in the base vscode working directory

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.68GB free)|
|Process Argv|--crash-reporter-id d98e343a-42c1-43fd-8fe1-168c83b0a323|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-intelephense-client|bme|1.8.2
better-toml|bun|0.3.2
vscode-eslint|dba|2.2.6
rust-syntax|dus|0.6.1
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
smartmulticursor|ida|0.0.4
json|Mee|0.0.1
cargo|pan|0.2.3
rust-analyzer|rus|0.3.1194
vs-code-prettier-eslint|rve|5.0.4
crates|ser|0.5.10
js-jsx-snippets|sky|11.0.0
twig|wha|1.0.2
cursor-align|yo1|1.1.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

![image](https://user-images.githubusercontent.com/47091253/189344798-edae9964-6aa1-449d-9e54-4fbac2ec3deb.png)
![image](https://user-images.githubusercontent.com/47091253/189344909-d620d1e5-ee13-4f53-a780-be2c5970eddf.png)

**Comment by mjbvz** [comment]
This looks like an eslint error. Please file the issue against the eslint extension
