### ISSUE TITLE
Hovers in JSON files is broken

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16050]
Latest Insiders:

Open a json file and hover on any property. Following is seen in console from JSON Language server

```
[Error - 9:28:02 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property '$ref' of undefined
  Code: -32603 
```

**Comment by aeschli** [comment]
Looks like the textModelResolverService is broken.

The JSON schema documents served in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/contentprovider/common/contentprovider.contribution.ts#L47
never are not making it to 
https://github.com/Microsoft/vscode/blob/master/extensions/json/client/src/jsonMain.ts#L81
