### ISSUE TITLE
Comment Thread actual range

### ISSUE THREAD

**Issue by marrej** [microsoft/vscode#160535]
Hi Team,

I am trying to figure out whether it would be possible to get the actual range of a `CommentThread` (CommentDecoration).
What I see as a bit of a problem when trying to position content alongside CommentThreads (e.g. CodeLens), is that the range that is in the `CommentThread` (created in extension) is only the original range. But as users modify the source, the `CommentThread` will get repositioned. Per my understanding ReviewZonewidget contains the information about both the `CommentDecoration` & the Glyph, but the `CommentThread` itself does not (as it is a child of the `ReviewZoneWidget`).

The optimal solution would be to directly provide an `repositionedRange`, and/or event triggered when the CommentDecoration is updated on source change.

Optional solution, if the one above would not be feasible, would be to expose a function which retrieves the actual CommentDecoration position directly from the `ReviewZoneWidget` using CommentThread unique identified (which would have to be exposed on the CommentThread object).

- VS Code Version: 1.70.2
- OS Version: CromeOS 104.0.5112.83

**Comment by alexr00** [comment]
@marrej since you've posted this issue I'm guess that the CommentThread and CodeLens don't move together in the same way when the document is modified? Would your issue be solved if they did move together?

**Comment by marrej** [comment]
Hi @alexr00 I think that would solve partially the problem (Although assuming that we will move in the direction of additional actions in CommentThread, it won't be neccessary any more).
The real reason why to get the actual position of the CommentThread is to grab correct area of code related to the Comment (lines before/lines after) for additional processing.

At the moment we provide the CommentThread position only on saves, since its quite costly to recalculate, so I was thinking whether we could use the CommentThread positioning as a datapoint.

But as I understood from last weeks discussions, vscode tries to mainly go with the data APIs & its questionable whether we should move this to UX API just for the sake of sending the data back to the extension. So I am not fully sure if this is feasible or not.

**Comment by alexr00** [comment]
@marrej we are moving in the direction of additional actions in the comment thread. Closing, and if this is still needed we can re-open.
