### ISSUE TITLE
"group": "clean" is not acceptable

### ISSUE THREAD

**Issue by NogrTL** [microsoft/vscode#160513]
Type: <b>Bug</b>

Warning on default npm install task

Task script
``` json
  {
      "type": "npm",
      "script": "install",
      "group": "clean",
      "problemMatcher": [],
      "label": "Install",
      "detail": "Install dependencies"
 },
```

Warning on `"group": "clean"`
`Value is not accepted. Valid values: "build", "test", "none".`

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (4.20GB free)|
|Process Argv|--folder-uri file:///d%3A/Work/Code/smart2_1-api --crash-reporter-id 9acbba3b-fd56-4377-982e-07d6fc50654b|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-sql-formatter|adp|1.4.4
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-great-icons|emm|2.1.86
vsc-material-theme-icons|equ|2.3.1
prettier-vscode|esb|9.8.0
vscode-firefox-debug|fir|2.9.8
auto-rename-tag|for|0.1.10
vscode-lombok|Gab|1.0.1
search-node-modules|jas|1.3.0
rainbow-csv|mec|2.4.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.1
remote-wsl|ms-|0.66.3
test-adapter-converter|ms-|0.1.6
gradle-language|nac|0.2.3
docthis|oou|0.8.2
material-icon-theme|PKi|4.20.0
material-product-icons|PKi|1.4.0
java|red|1.10.0
vscode-xml|red|0.21.2022062916
vscode-yaml|red|1.10.1
vscode-gradle-extension-pack|ric|0.0.4
snyk-vulnerability-scanner|sny|1.5.0
code-spell-checker|str|2.7.2
code-spell-checker-russian|str|2.0.6
code-spell-checker-ukrainian|str|1.0.0
vscode-styled-components|sty|1.7.4
vscode-stylelint|sty|1.2.3
intellicode-api-usage-examples|Vis|0.2.2
vscodeintellicode|Vis|1.2.25
vscode-gradle|vsc|3.12.4
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.1
vscode-maven|vsc|0.38.0
vscode-icons|vsc|11.16.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3
material-theme|zhu|3.15.5
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
/confirm

Schema definition:

https://github.com/microsoft/vscode/blob/fcde8c40d199dd3733f3b01830fa8a7a6ea44124/src/vs/workbench/contrib/tasks/common/jsonSchema_v2.ts#L207-L220

Namespace:

https://github.com/microsoft/vscode/blob/fcde8c40d199dd3733f3b01830fa8a7a6ea44124/src/vs/workbench/contrib/tasks/common/tasks.ts#L371-L378

Type definition:

https://github.com/microsoft/vscode/blob/fcde8c40d199dd3733f3b01830fa8a7a6ea44124/src/vscode-dts/vscode.d.ts#L7260-L7284

**Comment by gjsjohnmurray** [comment]
And L346-347 here puts a task named `install` into the `clean` group:

https://github.com/microsoft/vscode/blob/fcde8c40d199dd3733f3b01830fa8a7a6ea44124/extensions/npm/src/tasks.ts#L341-L351

**Comment by meganrogge** [comment]
@alexr00 is there a backstory to this/ are you aware of it?

**Comment by alexr00** [comment]
I don't think this was intentional. That part of the task API was created pretty early, and I think the clean group was never well defined. For example, there is also no "Run Clean Task" command. Not sure how useful exposing a "clean" group in the tasks.json actually is, since it wouldn't surface anywhere.
