### ISSUE TITLE
search.exclude should take precedence over search.useIgnoreFiles

### ISSUE THREAD

**Issue by matthieusieben** [microsoft/vscode#160516]
Currently, when `search.useIgnoreFiles` is `true` and `search.exclude` contains **`"my_file": false`**, the file gets ignored from search results.

While this is generally ok, it can be (very) annoying when dealing with files containing secrets (e.g. `.env.local`).

You don't want a `.env.local` file to ever be tracked by git, so you typically add it to a `.gitignore` file.

Doing so results in the file being ignored during searches (because of `"search.useIgnoreFiles": true`). But one would still want to be able to search in that file.

Adding an "exception" to `search.exclude` (with a `false` value) does not seem to allow to override that behavior.

So, in the current situation, allowing to search in files ignored by git requires to replicate the `.gitignore` logic in `search.exclude` and set `search.useIgnoreFiles` to `false`. This is very annoying, especially in large (mono) repos with lots of `.gitignore` files.

**Comment by roblourens** [comment]
A couple things going on here...

Setting an exclude pattern to `false` does not include the file, it can disable the same exclude pattern set somewhere else (eg workspace settings vs user settings). Here's the feature request for supporting negative glob patterns: https://github.com/microsoft/vscode/issues/869

However even if we have that, it may or may not take precedence over gitignore. That is a little tricky and from what I remember, it's hard to predict exactly what precedence users want in different situations, and to control this in ripgrep, the search tool we use.
