### ISSUE TITLE
Reconsider git auto-sync behavior when setting to auto-stash changes is enabled

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#160544]
1. Have a branch checked out locally
2. Have the following in settings: `"git.confirmSync": false`, `"git.autoStash": true`, `"githubPullRequests.pullBranch": "always"`
3. Publish the branch with a commit
4. Reset HEAD~1 so that the remote branch is ahead of the local checkout
5. :bug: When working on local changes, every once in a while GHPRI will trigger a sync due to the pullBranch setting. The git extension doesn't ask before syncing, so the net result is that the user's changes get repeatedly stashed and popped while the upstream gets pulled 

Two thoughts:
- If the user has done a local HEAD reset (in my case this was done with `Git: Undo Last Commit`), pullBranch should probably be disabled 
- Maybe it shouldn't be possible to disable confirmation and enable autostash together?

**Comment by alexr00** [comment]
> Maybe it shouldn't be possible to disable confirmation and enable autostash together?

I agree with this. I'll add a check in GHPRI.

**Comment by heartacker** [comment]
But I think is that he should not stash and pop out if there is no conflict.

**Comment by alexr00** [comment]
> But I think is that he should not stash and pop out if there is no conflict.

I'm pretty sure that git just requires this. @lszomoru FYI.

**Comment by mjbvz** [comment]
@joyceerhl Can you please verify this issue
