### ISSUE TITLE
Allow per-folder settings at the code-workspace level

### ISSUE THREAD

**Issue by rrmcguinness** [microsoft/vscode#160584]
Related and closed: Allow to define per folder settings in .code-workspace files #81153

A workspace should be able to support multiple Java projects in a single workspace. However the limitations of the "java project" currently only allows "java.project.referencedLibraries" to be applied if directory is the root directory opened by the editor.

Example structure:

* project_root
    * project.code-workspace
        * Here, we define a folder for module1 and module 2 (breaking the "java project" paradignm)
    * module1
        * .vscode
            * settings.json
        * src
    * module2
        * .vscode
            * settings.json
        * src

Because the code-workspace is the only honored "java.project.referencedLibraries", it breaks code completion. It also forces each module to then have the same dependencies and the same JVM definitions.

This is only true for non Maven project / unmanaged projects, like Bazel, or more complex project builds.

It would be great to see the 'code-workspace' support:

```json
{
  "folders": [
   {
     "name": "Module One",
     "path": "./module1",
    "settings": {
      ...
    }
  ],
  "settings": {
    ...
  }
  ...
```
 > This could be achieved if .vscode/settings.json files were flat-mapped into their own configuration space too.

**Comment by sandy081** [comment]
As mentioned in the related issue https://github.com/microsoft/vscode/issues/81153 we have no plans in supporting this feature. I would recommend to reach out to Java Extension and ask them to make `java.project.referencedLibraries` as a resource scoped setting. I think supporting this feature does not help unless this setting is made resource scoped.

**Comment by rrmcguinness** [comment]
What about honoring the .vscode/settings.json? I will work with the Java and Go extensions teams also. Is there a limitation in the management segmentation that makes this 'too complex'?

**Comment by sandy081** [comment]
Scope of this setting is set to `window` that means it is not honoured in a multi-root workspace even if the folder has this setting in `.vscode/settings.json`. The owner of this setting has to change it to `resource` scope and adopt it accordingly. Hence asked to file an issue against the Java extension to support it.

**Comment by rrmcguinness** [comment]
Got it, I'll work with those teams. Love the product, just carrying a lot of assumptions from other IDEs.
