### ISSUE TITLE
Switch internal VS Code tests off of NotebookContentProvider api

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#160580]
The notebook content provider api is being removed: #147248

However it looks like a few of our tests are still using it:

https://github.com/microsoft/vscode/blob/07025f0b0d259db654361b99b68539a742c53c3f/extensions/vscode-api-tests/src/singlefolder-tests/notebook.kernel.test.ts#L88-L89

https://github.com/microsoft/vscode/blob/a2cd34f34734c5cdc145ff6da85c28db8fa2ca05/extensions/vscode-api-tests/src/singlefolder-tests/notebook.api.test.ts#L78

https://github.com/microsoft/vscode/blob/07025f0b0d259db654361b99b68539a742c53c3f/extensions/vscode-api-tests/src/singlefolder-tests/notebook.document.test.ts#L23

https://github.com/microsoft/vscode/blob/ac05ae7b6f069ed696d435ec3146219d28478420/extensions/vscode-notebook-tests/src/extension.ts#L23

**Comment by rebornix** [comment]
Along with the use of content provider in tests, we also need to remove the content provider used by Interactive Window.
