### ISSUE TITLE
JSON Language Server - [Error - 下午5:22:16] Request textDocument/completion failed.

### ISSUE THREAD

**Issue by mosluce** [Microsoft/vscode#16051]
- VSCode Version: 1.8.0-insider ced1d697f81499df60b00d3a02ab264e5e0c99e4
- OS Version: 10.12.1（16B2555）

Steps to Reproduce:

1. open package.json
2. show errors on console
```
[Error - 下午5:22:16] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'id' of undefined
  Code: -32603
```

**Comment by mrmlnc** [comment]
Please, use search before create a new Issue.

Duplicate of #16050

**Comment by mosluce** [comment]
#16050 is closed.
but, It's not resolved.

**Comment by mosluce** [comment]
resolved.  0b847998d914ff84fd9c13b2972cc8803745c24d
