### ISSUE TITLE
Blurring

### ISSUE THREAD

**Issue by Akfiss** [microsoft/vscode#160532]
Type: <b>Bug</b>

My visual studio code is blurring whenever i open it. I don't know why this is happen cause before it is fine, but now my visual studio code looks like this. Please help me to fix this problem. Thank you!

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.72GB (3.87GB free)|
|Process Argv|--crash-reporter-id daaa4e8f-af3f-4918-abc5-33ce7e271aab|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

![Screenshot (1017)](https://user-images.githubusercontent.com/101693895/189369406-6134d62a-f5fd-4ec6-8730-eef80ef0f213.png

**Comment by roblourens** [comment]
Does starting with `--disable-gpu` fix it?

**Comment by Akfiss** [comment]
> Does starting with `--disable-gpu` fix it?

How to do that? Can you tell me please

**Comment by roblourens** [comment]
Start vscode from the command prompt like `code --disable-gpu`

**Comment by Akfiss** [comment]
> Start vscode from the command prompt like `code --disable-gpu`

It work thanks a lot bro! 
So whenever i want to use vs code, i have to run with --disable-gpu like that again?

**Comment by Akfiss** [comment]
Ok my problem has solved, just need to switch my dedicated gpu to the other lol xD. Thank you all.
