### ISSUE TITLE
Allow revealing folders in workspace with revealInExplorer command

### ISSUE THREAD

**Issue by schlicker** [microsoft/vscode#160504]
**Problem**
When using the following code the corresponding file is highlighted in the files explorer:
```js
vscode.commands.executeCommand(
  "revealInExplorer",
  vscode.Uri.file(path.join("path", "to", "folder", "existingFile.txt"))
);
```
When I just want to highlight a folder it doesn't work:
```js
vscode.commands.executeCommand(
  "revealInExplorer",
  vscode.Uri.file(path.join("path", "to", "folder"))
);
```
I also tried `vscode.Uri.parse` with the same result.
Is this intended behaviour? And if so - is there a command to just reveal a folder?

**Further info**
- This is the corresponding code in 1.71.0: https://github.com/microsoft/vscode/blob/1.71.0/src/vs/workbench/contrib/files/browser/fileCommands.ts#L319
- I found another commit that implemented revealing folders in the markdown features extension: https://github.com/microsoft/vscode/commit/e7bc301be6fcb35f9fdc5d46665c48210756bd7d - but this feature is no longer available in the latest version.

**Comment by lramos15** [comment]
I can't see why this wouldn't work with folders, do you want to debug and try to PR a fix? That would be appreciated

**Comment by schlicker** [comment]
I will look into it after my vacation.

**Comment by schlicker** [comment]
So I took a closer look and it is probably a problem with switching from one view pane to another. Some directories are working others are not. If I step through the code the folder is marked as expected but is unmarked after the revealInExplorer command is finished. So probably some interference with a setting or a bug in the extension itself.
If I move the tree view from which that command is executed to the file explorer view pane everything works as expected.
I am closing this for now since the revealInExplorer command is working as expected.
