### ISSUE TITLE
javascript auto format on save disable not working 

### ISSUE THREAD

**Issue by muhammad-ammar** [Microsoft/vscode#16055]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.5|
|sample-ext|RolandGreim|0.0.2|
|ActiveFileInStatusBar|RoscoP|1.0.2|
|code-settings-sync|Shan|2.3.8|
|project-manager|alefragnani|0.12.2|
|django-snippets|bibhasdn|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|python|donjayamanne|0.5.5|
|ansible|haaaad|0.2.3|
|rest-client|humao|0.10.5|
|docthis|joelday|0.3.5|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|
|MagicPython|magicstack|0.6.0|
|vs-remote-debugger|mkloubert|1.9.9|
|prettify-json|mohsen1|0.0.3|
|view-in-browser|qinjia|0.0.3|
|vscode-icons|robertohuertasm|4.0.2|
|sass-indented|robinbentley|1.2.1|
|annotator|ryu1kn|0.10.1|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|
|Material-theme|zhuangtongfa|1.0.3|
|vscode-open-in-github|ziyasal|1.2.2|

---

Steps to Reproduce:

1. Edit a javascript file and save. file will be auto formatted which i don't want. Event though i have the below settings but auto format is not disabled

```JSON
    "editor.formatOnSave": false,
    "javascript.format.enable": false
```

It looks like that either the VS Code recent update is causing this issue or some extension is interfering. Due to this issue i am unable to work. Please suggest a solution.

**Comment by jrieken** [comment]
In addition to the default javascript formatter that ships with VS Code you have installed another (*vscode-JS-CSS-HTML-formatter	lonefy	0.2.2*) which is likely now format. You must either uninstall that or configure it separately.

**Comment by muhammad-ammar** [comment]
Thanks @jrieken, uninstalling `vscode-JS-CSS-HTML-formatter` solved the issue.
