### ISSUE TITLE
Intellisense and hovers broken in JSON

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16052]
- VSCode Version: Version 1.8.0-insider (1.8.0-insider)
ced1d697f81499df60b00d3a02ab264e5e0c99e4
2016-11-25T07:03:03.190Z
- OS Version:macOS

Intellisense and hovers broken in JSON files.
Just open a package.json and hover or use intellisense.
I always get error messages like this in the Output panel:
![2016-11-25_10-25-56](https://cloud.githubusercontent.com/assets/1898161/20620375/b29fa41a-b2f9-11e6-8e8c-cd513cfa0a25.png)

/cc @joaomoreno @jrieken

**Comment by mrmlnc** [comment]
Related to #16050

**Comment by aeschli** [comment]
dup of #16050
