### ISSUE TITLE
Should diff revert arrow buttons show up in index diff?

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#160538]
On the latest Insiders:
![Recording 2022-09-09 at 08 47 41](https://user-images.githubusercontent.com/7199958/189392192-926965d5-2be7-4680-9d65-0ce9be95200e.gif)

**Comment by rzhao271** [comment]
Oh wait, it's because the file was ready to be committed. It was in index.
Maybe the buttons shouldn't be there, then?

**Comment by hediet** [comment]
I no longer see these arrows. I think this has been fixed.
