### ISSUE TITLE
updating to vscode 0.10.5 issue with csharp-o

### ISSUE THREAD

**Issue by nripendra** [Microsoft/vscode#1605]
Looking into [repository](https://github.com/Microsoft/vscode/tree/master/extensions), there is no longer folder named **csharp-o**.

![csharp-o](https://cloud.githubusercontent.com/assets/1594619/11973026/891bfd78-a97c-11e5-9335-8dcc84373dfa.png)

I manually deleted the folder and restarted vscode and issue is gone. So, problem looks like installer not removing that file.

**Comment by bpasero** [comment]
Yes, another user was also reporting that the installer was unable to delete the extensions folder. @joaomoreno fyi

**Comment by jpoon** [comment]
+1 got the same error. Deleting that folder made the error go away.

**Comment by joaomoreno** [comment]
Almost definitely the famed Windows long path issue, since the installer is set to always delete all extensions on update.
@jrieken fyi

**Comment by jrieken** [comment]
@joaomoreno Not sure if it's long path. Since 0.10.5 we don't ship `csharp-o` but `jrieken.vscode-omnisharp`

**Comment by joaomoreno** [comment]
Yep. The installer failed to remove the `csharp-o` folder due to the long path and the latest Code complains about having a folder in there without a `package.json` file.

**Comment by joaomoreno** [comment]
**Workaround:** delete the `csharp-o` folder.

**Comment by jpoon** [comment]
@joaomoreno: Haha. Nice and simple.

**Comment by joaomoreno** [comment]
@jpoon In case more people hit it. Still not sure what happened there, though... You don't happen to have a snapshot of that folder before deletion...? :smile_cat:

**Comment by jpoon** [comment]
Nope. From what I recall, the extensions folder only had the one chsaop-o folder and that folder was also empty.

**Comment by joaomoreno** [comment]
Removed omnisharp from core product.
