### ISSUE TITLE
Escaping in snippet text

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16056]
The snippet syntax https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/snippet/common/snippet.md#L27
says that $ can be escaped by \\$.

In addition to that:
- the escaping character needs to escapable in order to be able to have '\\$' as content in a snippet. `\` -> `\\`
- the placeholder text needs to be able to escape }   -> `}` -> `\}`

For simplicity I suggest that the spec says that any character can be escaped using \

**Comment by jrieken** [comment]
@aeschli Is this a problem with the doc, the `SnippetString`, or how we interpret that?
