### ISSUE TITLE
XML display and Word Wrap

### ISSUE THREAD

**Issue by sixareen** [microsoft/vscode#160666]
Type: <b>Feature Request</b>

I've used what I believe are the built-in or standard extensions for XML code, but I just don't get how anyone developing these things can miss how bad they are - the only significant layout option seems to be  the WordWrap toggle, which just toggles between one unhelpful layout and another.

Where's the option to display the XML code hierarchically (e.g at its simplest, where you present each new XML level on a new line with a certain level of indentation? Or perhaps where you allow some "folding" of XML data?

BTW, When selecting the "File on" option in the dialog box that you present to people posting comments - the route I came here by - it really isn't that obvious what it actually means.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by aeschli** [comment]
Out-of-the-box. VS Code does not provide rich XML language support. For that you need to install an extension such as https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml
