### ISSUE TITLE
Consider to introduce alternative syntax for ${command.xxx} variables

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16064]
With #12735 it is now possible to use any command ID in a variable with the ${command.xxxx} syntax.

If the command ID follows the common practice to use '.' as segment separators then using it with the 'command.' prefix makes things a bit unwieldy:

``` typescript
  "program": "${command.extension.node-debug.pickProcess}"
```

I suggest that we deprecate the ${prefix.id} syntax and introduce a new ${prefix:id} syntax which results in more readable variables:

``` typescript
  "program": "${command:extension.node-debug.pickProcess}"
```

This change would apply to the other variable prefixes 'env', 'config' as well (and it would help there too because 'config' uses command IDs too).

/cc @kieferrm @egamma @dbaeumer 
your opinion?

**Comment by weinand** [comment]
We've decided to go with the proposed ':' syntax.

**Comment by weinand** [comment]
@isidorn since more people are asking about a way to use command in variables, we should really start supporting the new syntax in February.

**Comment by isidorn** [comment]
@weinand just to sum it up, in february we should support both
`env.` and `env:`
`config.` and `config:`
`command.` and `command:`

For `env.`, config. and `command.` we should somehow mark them as deprecated both in `launch.json` and `tasks.json`.

In march we drop support for `env.` `config.` and `command.`

**Comment by weinand** [comment]
@isidorn your summary is correct.

**Comment by DonJayamanne** [comment]
@isidorn @weinand 
Just out of curiosity, how will this affect existing users with settings in launch.json and others where `config.` is being used?

**Comment by isidorn** [comment]
@DonJayamanne for 2 milestone they are already getting a green squilgy warning prompting the users to use `config:` instead. After that (in April stable which will be availabe in May) it will simply fail to substitute

**Comment by DonJayamanne** [comment]
@isidorn cheers
