### ISSUE TITLE
Get Started tab still opens in Codespaces even when workbench.startupEditor is set to "none" in Remote settings

### ISSUE THREAD

**Issue by dmalan** [microsoft/vscode#160635]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.0, 784b0177c56c607789f9638da7b6bf3230d47a8c
- OS Version: Codespaces

Steps to Reproduce:

1. Create a new codespace using a `.devcontainer.json` with `"workbench.startupEditor": "none"`.
2. "Get Started" tab still appears on first launch. 

Just to follow up on @JacksonKearl's https://github.com/microsoft/vscode/issues/134073#issuecomment-940220716:

> Yes, the case of connecting to a Codespace via Insiders is a bit of an oddball, as we must display the telemetry notice in Insiders but we don't need it in Codespaces. This should be fixed for Codespaces accessed via the browser in the next stable release. 

Afraid the Get Started tab indeed still appears in Codespaces, even with `"workbench.startupEditor": "none"`, per below, though sounds like that's not intended?

Thank you!

<img width="1344" alt="Screen Shot 2022-09-10 at 11 00 49 PM" src="https://user-images.githubusercontent.com/788678/189510726-672d6dd8-8ffd-464c-b49f-a1d86c4c4c19.png">

CC @jkeech @rongxin-liu

**Comment by lramos15** [comment]
Possibly related to https://github.com/microsoft/vscode/issues/152265

**Comment by bhavyaus** [comment]
Fixed with https://github.com/microsoft/vscode/pull/169674
