### ISSUE TITLE
Pressing Esc in mini find widget closes peek references

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#160621]
Does this issue occur when all extensions are disabled?: Yes!

- VS Code Version:
- OS Version:Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Open a Peek References with results in multiple files
2. Press Ctrl+F and type to search within results, it should look something like this

![image](https://user-images.githubusercontent.com/1485998/189499768-ec09b130-2815-4952-b26d-7b638c152587.png)

This seems pretty broken...

3 a Press Enter. (Expected: mini find widget closes? Actual: nothing happens)

3 b Press Esc (Expected: mini find widget closes. Actual: peek references closes! )

3 c Press Alt+C. The search settings show up all the way... over there! (Top right of the main editor instead of in the peek references zone)

Also, the settings (match case, whole word, regex) don't seem to apply to this search anyway.

![image](https://user-images.githubusercontent.com/1485998/189499831-2cc5b00e-ddf9-4233-909a-0f2a2a447618.png)

**Comment by gjsjohnmurray** [comment]
/confirm

> 3 a Press Enter. (Expected: mini find widget closes? Actual: nothing happens)

What you call the "mini find widget" is the [recently-added](https://code.visualstudio.com/updates/v1_70#_tree-find-control) search/filter widget that is available in all trees and lists. Nothing is supposed to happen when you press Enter while focused in that widget's text field.

> 3 b Press Esc (Expected: mini find widget closes. Actual: peek references closes! )

I can repro this as a bug, even on Insiders. :bug:

> 3 c Press Alt+C. The search settings show up all the way... over there! (Top right of the main editor instead of in the peek references zone)
> Also, the settings (match case, whole word, regex) don't seem to apply to this search anyway.

The tree/list search/filter widget doesn't offer those features. The Alt+C keybinding will only affect the editor Find widget. When that widget isn't shown, toggling one of its settings via a keybinding causes the toggle buttons to appear briefly as confirmation. #160627 captures a problem of sticky scroll headers masking this brief appearance.
