### ISSUE TITLE
SSH_ASKPASS handler breaks 2FA login

### ISSUE THREAD

**Issue by muendelezaji** [microsoft/vscode#160673]
Does this issue occur when all extensions are disabled? Yes

- VS Code Version: 1.72.0-insider
- OS Version: macOS 12.5.1

Version: 1.72.0-insider
Commit: 5cecbf4746a7b95dedaf9fc4534b9786b9a30ace
Date: 2022-09-09T16:24:20.520Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes

**Steps to Reproduce:**
1. In the integrated terminal, try to SSH into a server that prompts for a 2FA code (e.g. via Yubikey). Any commands that uses SSH internally (e.g. rsync) also seem to exhibit similar behaviour.

**Expected:**
A prompt should appear in the terminal for the 2FA code to be entered. This was the previous behaviour.

**Actual:**
VSCode takes over and shows a popup asking _"Are you sure you want to continue connecting?"_. The terminal prompt isn't shown, making it impossible to log into the server.

**Additional details:**
The changes potentially responsible appear to be from #159573 (Git - implement SSH_ASKPASS handler).

The popup only seems to handle SSH fingerprint prompts, and thus makes some assumptions about the nature of the text. This leads to extracting incorrect values for `host` and `fingerprint`. Below are screenshots from 3 scenarios:

1. SSH fingerprint prompt (what the handler assumes)
<img width="701" alt="scr1" src="https://user-images.githubusercontent.com/1127221/189564852-02f4ec11-9137-40db-af88-4798e8d56f0d.png">

2. First time popup when 2fa prompt is captured (personal info redacted)
<img width="690" alt="scr2" src="https://user-images.githubusercontent.com/1127221/189564870-1139ec57-63a2-43fc-bc9b-1826870832ac.png">

3. Subsequent popups when 2fa prompt is captured
<img width="691" alt="scr3" src="https://user-images.githubusercontent.com/1127221/189564878-8f72c55e-3092-4b2b-82b8-be5797505b49.png">

Note that for (2) and (3) the `host` and `fingerprint` could be anything, depending on the actual prompt text.

**Comment by lszomoru** [comment]
@muendelezaji, could you please try the following workaround to unblock you:
- Close all integrated terminal windows
- Set the `git.terminalAuthentication` setting to `false`
- Reload VS Code and try again

**Comment by muendelezaji** [comment]
@lszomoru That has worked, back to the old behaviour for now. Thanks.

**Comment by connor4312** [comment]
@muendelezaji can you verify whether this is working for you on [VS Code Insiders](https://code.visualstudio.com/insiders/)?

**Comment by muendelezaji** [comment]
@connor4312 I can confirm it does work on Insiders, even with the default setting (`git.useIntegratedAskPass: true`). I get the 2FA prompt in the terminal as in the original behaviour. Thanks for the great work done on VSCode.
