### ISSUE TITLE
An error is reported when accessing Github using an SSH key with a password

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/vscode#160633]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.0
- OS Version: Windows 11 21H2(22000.832)

Steps to Reproduce:

**When I use SSH for code push, if this SSH key is passwordd, then VSCode will report an error, like this:**
![image](https://user-images.githubusercontent.com/96709586/189510558-98b9c0e3-3edd-4c3f-a34a-59d32994e903.png)

**Comment by CoolPlayLin** [comment]
Although it is not a big problem, but after writing the program, you still have to manually Push's feeling...

**Comment by lszomoru** [comment]
@CoolPlayLin, we have recently made some changes to start supporting SSH keys with a passphrase. These changes are currently only available in the Insiders release. Could you please download the latest Insiders from [here](https://code.visualstudio.com/insiders/), and try to push your changes to GitHub. You should see a quick input control at the top of the window to enter the passphrase for the SSH key.

**Comment by CoolPlayLin** [comment]
OK

**Comment by CoolPlayLin** [comment]
Hopefully, this feature will soon be ported from the preview version to the official version

**Comment by CoolPlayLin** [comment]
![image](https://user-images.githubusercontent.com/96709586/190599763-3e4644bd-237f-431f-9843-c8969bcda0a5.png)
It was really good

**Comment by CoolPlayLin** [comment]
@lszomoru

**Comment by CoolPlayLin** [comment]
@lszomoru However, I also noticed a problem when using it: I had to enter the push code twice to succeed when entering the password, and I don't know if it is a bug

**Comment by lszomoru** [comment]
@CoolPlayLin, thank you very much for trying out Insiders. Yes, this functionality will be included in the next Stable release that will be released to the public early next month. Could you please clarify which command you have invoked that resulted in you having to put the passphrase twice? Was it to the "Sync Changes" button? Pressing the "Sync Changes" button will result in executing *two* git command, so it is expected that it will result in having to put the passphrase in twice.

**Comment by CoolPlayLin** [comment]
Do synchronous changes pull the code once when pushing the code?

**Comment by CoolPlayLin** [comment]
If that's the case then I didn't say it

**Comment by CoolPlayLin** [comment]
Can I modify the default buttons in the settings

**Comment by CoolPlayLin** [comment]
@lszomoru

**Comment by lszomoru** [comment]
You can control the default behaviour of the "Commit" button using the `git.postCommitCommand`.
There is no setting to control the capabilities of the "Synchronize Changes" button.

**Comment by CoolPlayLin** [comment]
Thanks
