### ISSUE TITLE
an option to disable notification of "File changes watcher stopped unexpectedly"

### ISSUE THREAD

**Issue by yoshiotobe** [microsoft/vscode#160603]
I often get the notification of "File changes watcher stopped unexpectedly". 
However, everything works fine and I can continue to use vscode without problems.
I understand it's telling me that I open too much files or directories but It would be great if there is an option to disable the notification because it just bothers me.

**Comment by bpasero** [comment]
You can disable the file watcher via `files.watcherExclude` to `**`.

**Comment by yoshiotobe** [comment]
Thank you for a quick response.
However, what I asked was how to disable the notification not a file watcher itself.
If I stop the file watcher, I can't use basic functions such as builtin git.

I've read followings and made settings accordingly but get the notifications many times.

_https://github.com/microsoft/vscode/wiki/File-Watcher-Issues_
_https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc_

I can't reproduce the problem because it happens out of nowhere.
Somtimes, I use multiple vscode instances at the same time with a lot of files. So, that might be a cause. 
I made some changes to the settings, so I will see how it goes.

**Comment by bpasero** [comment]
I do not think it is a good idea to allow to permanently disable the notification. The way out is to configure excludes or increase file handles count on Linux.

**Comment by yoshiotobe** [comment]
I'm not saying permanently disable it but have an option to disable it when not being able to figure out the problem. However, if I have the option and turn it off, I guess I will never put it back on and not notice the problem. 
So, you are right, I have to figure out the problem.
