### ISSUE TITLE
Update 1.72.0-insider (issue on new UI) horrible User experience. 

### ISSUE THREAD

**Issue by brettnzl** [microsoft/vscode#160670]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 172.0-insider
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

This isn't really a technical issue, this is due to the latest update (on the insider version) which has made the UX terrible to use. on a windows computer, if you have your editor in a small window it is now almost impossible to **drag the window** around your screen, except for a small spot between the menu and the back button on the search. 

Can this change please be reverted? 

1. Open vscode 
2.  screen size 1920x1080, snap the window to 50% and try to move editor with the mouse

![image](https://user-images.githubusercontent.com/13056905/189563014-f30455bf-2756-4185-bbd9-725dc3188f07.png)

**Comment by gjsjohnmurray** [comment]
Related to #157437

@brettnzl do you see a difference between 1.72.0-insider and 1.71 Stable in this respect?

**Comment by brettnzl** [comment]
Yes, well I'm not sure what the version was before, but I had been using insider since an issue with regular Visual studio. here is a screenshot difference between 1.70.2 and 

The top is Insider and the bottom is 1.70.2 stable

![image](https://user-images.githubusercontent.com/13056905/189756704-a78353dd-74be-41fd-9b3e-99151a5d05f7.png)

Adding the search bar has made it really difficult to move the window around. especially when snapping between windows. I know this is only a minor thing... but it's a really annoying change.

**Comment by gjsjohnmurray** [comment]
It is called the Command Center and it is optional. Please search for the setting to disable it.

**Comment by brettnzl** [comment]
> 

Thank you! This is much better. Much appreciated.
