### ISSUE TITLE
getMachineId has potential for being random

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16069]
In all [error cases](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/id.ts#L19) `getMachineId` returns a random result I think defeats the purpose...

**Comment by joaomoreno** [comment]
I also thought the same when I first saw it. This came from the telemetry world where the value is stored once retrieved, so random is still OK.

But since this is now extracted, we should probably document the method that in case of failure it generates a random value. What do you think?

**Comment by jrieken** [comment]
We could just store it in the module. Then it would be at least constant during the lifetime of the app

**Comment by joaomoreno** [comment]
This has since been tackled afaik.
