### ISSUE TITLE
Can't comment out code

### ISSUE THREAD

**Issue by deandownunder** [microsoft/vscode#160668]
Type: <b>Bug</b>

Hi there, since friday I am unable to comment out code using the standard key binding cmd-k + cmd-c.

Toggling the developer keyboard shortcuts troubleshooting shows that the keybinding entries are invoking the expected command (editor.action.addCommentLine) but nothing actually happens on screen.

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.44GB free)|
|Process Argv|--crash-reporter-id d0042ed0-ac4b-4fcd-8937-3fdd8cec4e4f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|12.2.2
vscode-pull-request-github|Git|0.50.0
vscode-bicep|ms-|0.10.13
vscode-dotnet-runtime|ms-|1.5.0
azurerm-vscode-tools|msa|0.15.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by deandownunder** [comment]
<img width="1491" alt="Screen Shot 2022-09-12 at 9 57 42 am" src="https://user-images.githubusercontent.com/31467382/189554704-9f181c7f-44e3-4ff8-95de-416e4f013515.png">
<img width="340" alt="Screen Shot 2022-09-12 at 9 57 59 am" src="https://user-images.githubusercontent.com/31467382/189554708-ff20a12a-04da-40ab-a6ce-4c9e05ff642d.p
<img width="1163" alt="Screen Shot 2022-09-12 at 9 53 20 am" src="https://user-images.githubusercontent.com/31467382/189554718-90826c70-aa3e-42cd-aab4-0ee550647a93.png">
ng">

**Comment by deandownunder** [comment]
I have also manually reset the keybindings to another key combination & reinstalled VSCode but no joy

**Comment by daveinci** [comment]
Same issue, roughly same timeframe. Now on 1.72.0-insider

**Comment by IllusionMH** [comment]
@deandownunder do you see this problem in all types of files of some specific e.g. Bicep mentioned above?

Might be issue with corresponding extension.

**Comment by deandownunder** [comment]
Wow it works fine in a JSON file with the ARM extension installed, It's only BICEP and Text files that don't work

**Comment by deandownunder** [comment]
Just installed an update for VSCode, reloaded and is now working in Bicep!!
