### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by leaxoy** [Microsoft/vscode#16062]
- VSCode Version: Code - Insiders 1.8.0-insider (6a6ab1fc5e58227b56ffc3e5bea9951e5565c314, 2016-11-24T07:05:02.837Z)
- OS Version: Darwin x64 16.3.0
When install extension(visual studio keymap), then error message shows like title.

**Comment by joaomoreno** [comment]
Are you behind a proxy?

**Comment by leaxoy** [comment]
I will do more test and feedback later

**Comment by leaxoy** [comment]
Looks well after turn off proxy, that's looks so strange because other things works well behind the same proxy.

**Comment by leaxoy** [comment]
Closing

**Comment by churchs19** [comment]
I'm also seeing this behind a corporate proxy on all extensions as of today.

Version 1.8.0-insider (1.8.0-insider)
`4721762a2ac1e21f1e33094e810d4888052f3d8d`
2016-11-29T07:03:09.021Z

@joaomoreno I'm not seeing any network requests in the VS Code developer tools window, so I'm unsure of what might be causing this. If I break in net.js at line 729 where the call to createWriteReq() starts, I get the following `data` parameter on Beautify (for example - it's similar on all other extensions):

`"{"id":50,"type":0,"channelName":"extensions","name":"installFromGallery","arg":[{"id":"697255a9-3f36-44c8-b084-d3b91edfb23a","name":"beautify","version":"0.6.2","date":"2016-11-28T04:23:10.43Z","displayName":"beautify","publisherId":"901b401e-7657-4a33-8c9a-0854c569607e","publisher":"HookyQR","publisherDisplayName":"HookyQR","description":"Beautify code in place for VS Code","installCount":339711,"rating":4.625,"ratingCount":24,"assets":{"manifest":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Code.Manifest","readme":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Content.Details","download":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.VSIXPackage?install=true","icon":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Icons.Default?redirect=true","iconFallback":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Icons.Default","license":"https://hookyqr.gallerycdn.vsassets.io/extensions/hookyqr/beautify/0.6.2/1480306987732/Microsoft.VisualStudio.Services.Content.License"},"properties":{"dependencies":[],"engine":"^1.6.0"}},true]}"`

Opening the `download` URL in that parameter in my browser downloads the zip file successfully.

Also referenced this issue in https://github.com/Microsoft/vscode/issues/2384#issuecomment-263580095.

**Comment by Neutrino-Sunset** [comment]
Also seeing this.
So why is this issue closed if this is still a problem and no workaround is posted?
