### ISSUE TITLE
Improve Angular2 integration

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#16068]
Since vscode offer a huge support of Typescript, i found so bad that it does not support Angular2 very well. Some alternatives exists, some extensions, but many are missing.
For exemple there is no link between styles, templates and JS file yet.

Here is a list of usefull features that can be added in Typescript for some, and Angular2 for most : 
### template HTML Behaviour : 
_**Note:** For all this ones, it may be necessary to detect that file.component.html is angular2 template and not only html file._
- Autocompletion for string interpolation and methods
- CTRL+click on string interpolation go to definition
- Angular2 HTML snippets (alternative extension : [Angular 2 TypeScript Snippets](https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2) )
- fast encapsulate current selection with **()** , **[]** or **{}** like **""** and **' '** does: #15731 

### inline HTML Behaviour : 
- missing syntax coloration (alternative extension : [angular2-inline](https://marketplace.visualstudio.com/items?itemName=natewallace.angular2-inline) )
- command **editor.action.formatDocument** does not work properly (ALT+SHIFT+F)
- Emmet is not working ( alternative : [	Angular 2 TypeScript Emmet](https://marketplace.visualstudio.com/items?itemName=jakethashi.vscode-angular2-emmet) )

### JS/TS Behaviour : 
- Angular2 TS snippets (alternative extension : [Angular 2 TypeScript Snippets](https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2) )
- apply warning for unused import
- when typing some variables names in TS, ":" trigger autocompletion, exemple : #16072

### General Behaviour : 
- commands to fast switch between ts / html / sass or css files ( alternative : [angular2-switcher ](https://marketplace.visualstudio.com/items?itemName=infinity1207.angular2-switcher) )
- autoImport required Symbol / class / methods ( alternative : [TS Importer](https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter) )

For those who wants an **icon theme** with angular icons, here is a suggestion : [VSCode simpler Icons with Angular](https://marketplace.visualstudio.com/items?itemName=davidbabel.vscode-simpler-icons).
For help, I suggest you to put **"html.suggest.angular1": false,** if you work on angular 2.

Feel free to support this issue adding 👍 , and add your suggestions and extension recommandations, i will edit this.

**Comment by michaeljota** [comment]
I develop with Angular 2, and somethings I think are out of scope of a code editor, remember: this is just a code editor. 

> JS/TS Behaviour :
>
> * Angular2 TS snippets (alternative extension : Angular 2 TypeScript Snippets )
> * apply warning for unused import
> ...
> autoImport required Symbol / class / methods ( alternative : TS Importer )

* (snippets): I don't think there are native snippets for any FrontEnd framework, I don't think why they must start with Angular2. 
* (unused imports): Imports are just variables, if you would like warnings for that kind of things you should use a linter. Recommended [TSLint](https://github.com/palantir/tslint) with [Codelyzer](https://github.com/mgechev/codelyzer).
* (Auto import): I think VS Code just use TS underneath, so this must be asked in TS repo I think. Neverless, the best autoimport extension that I had test for TS it's [TypeScript Hero](https://github.com/buehler/typescript-hero)

Still, I support that there should be a way to improve the integration between the html template and the js/ts component file. Even if this have to be done by an extension, I guess that the editor should give developers some kind of access to do so. I really don't know if that things can be done right now, I think not. However, I hope somethings get a proper answer, cause some others already had been.

**Comment by pierredewilde** [comment]
In addition, `HTML` should suggest `Angular 2` tags with the **settings**:
```
"html.suggest.angular2": true
```

**Comment by michaeljota** [comment]
Starting in Angular 2.3, there is a language service ([link](https://github.com/angular/angular/tree/master/modules/%40angular/language-service)). They will integrate it with other editors, starting with VSCode, so I guess this is the answer we was waiting for.

**Comment by mjbvz** [comment]
Yes, please try the [Angular Language Service extension](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template). We generally don't bundle framework specific functionality with VS Code but instead leave this up to extensions. 

Please try moving some of these feature requests over to the angular language service and let us know if there is anything on the core VSCode side that blocks implementing these

**Comment by michaeljota** [comment]
You think the HTML formatting should be concern ALS or VSCode? Because usually when you format Angular templates, you do it in a certain way that the default HTML formatter does not understand. Is there a way to configure the way the HTML is being formatted?
