### ISSUE TITLE
"Clear Console" not working

### ISSUE THREAD

**Issue by len-ny** [microsoft/vscode#160631]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.71.0
- OS Version:  Windows10.0.19044

Steps to Reproduce:

1. In Angular, ng serve
2. Go Run & Debug
3. Start Debugging (Chrome: Launch)
4.  In Debug Console, right-click, Clear Console
5.  Console doesn't clear

**Comment by whalderman** [comment]
Getting the same issue.

Version: 1.71.1
Commit: e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb
Date: 2022-09-08T19:41:12.369Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.10.0-17-amd64
Sandboxed: No

Filtering works, but input commands seem to be ignored and the console can't be cleared.

**Comment by roblourens** [comment]
Same as https://github.com/microsoft/vscode/issues/146002. I am interested in solid steps to reproduce the issue though. If you can share a simple script that produces output that breaks the console like this, that would be really helpful
