### ISSUE TITLE
Git: Illegal argument: line must be non-negative

### ISSUE THREAD

**Issue by cdoublev** [microsoft/vscode#160606]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0 (user setup)
- OS Version: Windows_NT x64 10.0.19044
- Git Version: 2.30.2 (Windows)

Steps to Reproduce:

1. create a new directory
2. initialize a new Git repository
3. create a new file and append some text on the first lines
4. add this file to the staging
5. remove the line with text

An OS native dialog box error pops up with the title of this issue as text. In the console output for Git:

> [2022-09-10T11:52:33.355Z] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z HEAD [70ms]
> [2022-09-10T11:52:33.355Z] fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'

I have had this problem for a long time, 2 years I would say. I thought someone would have reported it but it seems not.

**Comment by snowskeleton** [comment]
I'm having a similar issue on macOS 12.6 (21G115).

If you have deleted lines at the top of a file and click the little arrow to undo the change, the error pops up. Notably, it still completes the undo.
<img width="396" alt="image" src="https://user-images.githubusercontent.com/51010664/206622218-50275b2d-1d57-4d3d-91bf-819cb07bbdb8.png">

**Comment by lszomoru** [comment]
@cdoublev, @snowskeleton apologies for not getting back to you on this. I used the repro steps above but I was unable to reproduce the problem with the latest VS Code Insiders (1.75) release. Could you please do me a favour and see if you are still able to reproduce the issue? If so, could you please share a recording using https://gifcap.dev so that I can further investigate the issue? Thanks!

**Comment by snowskeleton** [comment]
Issue is still present in the latest insider release on macOS.

![Recording 2022-12-19 at 10 53 32](https://user-images.githubusercontent.com/51010664/208467465-80af6afa-1d50-4c6b-b784-eb69f73db282.gif)
VSCode info:
Version: 1.75.0-insider
Commit: 64a739f7aa1092187348afa9378931d47683be12
Date: 2022-12-19T05:35:41.089Z (10 hrs ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
