### ISSUE TITLE
Markdown preview ability is completely gone

### ISSUE THREAD

**Issue by petesg** [microsoft/vscode#160698]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0
- OS Version: Windows 10 Pro 21H2

Steps to Reproduce:

1. Open .md file
2. [Preview buttons at top right](https://code.visualstudio.com/assets/docs/languages/Markdown/md-dynamic-preview.gif) are gone, Ctrl+Shift+V does nothing and "Preview" is not an option when right-clicking a .md file.

**Comment by mjbvz** [comment]
Either an extension you've installed is interfering with the markdown preview or you've disabled the built-in markdown extension. Search `@builtin markdown` in the extensions view to check this
