### ISSUE TITLE
Search "Files to Exclude" box would benefit from additional toggle to enable/disable "files to exclude"

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode#160619]
Type: <b>Feature Request</b>

In Issue #160615 it was clarified that the current behavior is by-design.
It is confusing that the toggle button inside the exclude field doesn't apply to the field itself.

This is a feature request for the following changes:

1. Move the existing toggle button _outside_ the field (to the right), like the "replace in all files" button.
2. add a new toggle button _inside_ the "files to exclude" field to enable/disable use of that field.
3. compute the effective search exclusion list based on the combination of the settings, contents of the field, and the two toggles.

Thanks for considering.

**Behavior description**

my search settings:

TargetString: "Platform/" (no options set)
files to include:  "./"
files to exclude: "*.rst,*.txt,*.cmake"

Results:
6 results in 4 files ...

disable exclude files and results are:
6 results in 4 files - exclude settings and ignore files are disabled.

REMOVE "*.cmake" from the files to exclude

Results:
688 results in 579 files - exclude ...

**extra data**

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
I tend to agree with the first suggestion. At first I thought that for consistency the "Search only in Open Editors" toggle should perhaps be moved outside the "files to include" field. But that button modifies the effect of the field's contents, so behaves like the toggles in the Search field above it.

I don't support the second suggestion. It adds clutter, is probably rarely used, and the effect can already be achieved by clearing the field (<kbd>Ctrl</kbd>+<kbd>A</kbd> on Windows, followed by <kbd>Delete</kbd>) and reinstating it from field history (<kbd>UpArrow</kbd>). Also, for consistency you'd probably want the extra toggle on the "files to include" field as well, adding even more clutter.

**Comment by roblourens** [comment]
I also disagree about the second. I think it has come up before, but I agree that using history makes it not a big deal to delete the field.

The first has also been discussed, and honestly, I just think that it looks better this way and conceptually isn't a big deal. The button label is accurate.
