### ISSUE TITLE
Windows only: debug.focusWindowOnBreak only makes icon flash

### ISSUE THREAD

**Issue by Lewiscowles1986** [microsoft/vscode#160629]
Does this issue occur when all extensions are disabled?: Yes

VS Code Version copied using button:

Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chrome: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. npm install
2. $(npm bin)/nodemon node index.js
3. open the http://localhost:3000
4. set a breakpoint on line containing `res.send(`Hello ${req.query.name || 'World'}!`);`
5. refresh browser
6. All I see is a flashing icon and it's deeply frustrating. For some reason, other IDE's and programs do not have this capturing focus problem. I Believe this is electron JS or vscode specific.

**Comment by Lewiscowles1986** [comment]
I Should note that this seems to work in OSX and Linux. It's just Windows being famously awful. It does seem this has been raised before, and those issues are now closed.

**Comment by Lewiscowles1986** [comment]
This still does not work consistently, however the following registry settings seem to help (at least sometimes)

```
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Control Panel\Desktop]
"ForegroundLockTimeout"=dword:00000000

```

Some application must have set this to a higher value at some point as it was I think 20000 or something silly. Strange other apps seemed to be able to work (notably webstorm)

**Comment by roblourens** [comment]
Thanks for the tip about the registry. But yes, I see a couple other issues about this not working on windows, or causing hangs on windows. I don't think we're going to get any further on this beyond, it sometimes is flaky on windows, sorry.

**Comment by Lewiscowles1986** [comment]
Wait a minute, so if this is working for you or others on windows, why don't we leave it open so these issues stop coming up?
