### ISSUE TITLE
Search does not respect Exclude-on/off setting - always excludes

### ISSUE THREAD

**Issue by bradlitterell** [microsoft/vscode#160615]
Type: <b>Bug</b>

my search settings:
searching in local clone of: https://gitlab.kitware.com/cmake/cmake.git

TargetString: "Platform/" (no options set)
files to include:  "./"
files to exclude: "*.rst,*.txt,*.cmake"

Results (with exclude settings active):
`6 results in 4 files ...`

Results (with exclude settings disabled): 
`6 results in 4 files - exclude settings and ignore files are disabled.`

However, if I actually remove "*.cmake" from the files to exclude, the results are:
`688 results in 579 files - exclude ...`

Seems the exclude on/off button isn't working correctly.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (7.30GB free)|
|Process Argv|--crash-reporter-id 142d2241-6057-4ccc-84bd-36797d6a7081|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
overtype|ada|0.2.0
header-builder|Alp|0.0.4
unique-lines|bib|1.0.0
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
sarif-viewer-fix|br4|3.1.7
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.48.1
vscode-codeql|Git|1.6.12
vscode-test-explorer|hbe|2.21.1
cmake-language-support-vscode|jos|0.0.4
git-graph|mhu|1.30.0
wavework|Mic|1.2022.620008
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
hexeditor|ms-|1.9.8
test-adapter-converter|ms-|0.1.6
hide-gitignored|npx|1.1.0
vscode-text-tables|Rom|0.1.5
rewrap|stk|1.16.3
markdowntable|Tak|0.10.2
vscode-mermaid-editor|tom|0.15.0
cmake|twx|0.0.17
sort-lines|Tyr|1.9.1
clang-format|xav|1.9.0
markdown-all-in-one|yzh|3.4.3
json|Zai|2.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyonecf:30548226
2144e591:30553903

```

</details>

**Comment by IllusionMH** [comment]
If you have content in "files to exclude" field - it is always used to exclude.
Toggle button inside of this input - is about toggling use of `files.exclude` and `.gitignore` files, not about disabling/enabling field.

**Comment by bradlitterell** [comment]
ok, that's notably non-obvious (it's weird to have a checkbox toggle inside a field it doesn't apply to), but thanks for the clarification.
