### ISSUE TITLE
Reduce complexity of URL handling in `openFirstWindow`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160683]
I am looking at:

https://github.com/microsoft/vscode/blob/f073778d5115dd0a92ed92117628e9433472216a/src/vs/code/electron-main/app.ts#L832

The method is complex. There are elements of it that are for opening the first window, which is good. But then it seems there is code for URL listening that I believe should move either to another method out of this one or even into the URL listener to reduce complexity.

I talk about this block of code:

https://github.com/microsoft/vscode/blob/f073778d5115dd0a92ed92117628e9433472216a/src/vs/code/electron-main/app.ts#L841-L965

Arguable from that code block, `pendingWindowOpenablesFromProtocolLinks` is relevant to `openFirstWindow` because this actually contributes to the initial set of windows to open, but maybe this can be passed in differently.

**Comment by joaomoreno** [comment]
This was cleaned up by none other than @bpasero himself!
