### ISSUE TITLE
Cannot directly "Clone from GitHub"

### ISSUE THREAD

**Issue by ChristoWolf** [microsoft/vscode#160662]
Type: <b>Bug</b>

Hi!

I have never realized this before, but since some time the `Git: Clone` command drop-down does not show "Clone from GitHub" anymore.
It's a bit mysterious to me as to why because
- disabling all extensions did not help (via `code --disable-extensions`),
- an extension bisect did neither,
- it worked though in a newly installed Insiders instance/window (so re-installing might probably help),
- completely removing all user settings also did not help,
- and I have this issue both on my personal and office machines (with settings sync enabled).

Steps to reproduce:
1. ???
2. Execute the `Git: Clone` command.
3. Input any character(s) or full names of valid, public GitHub repos.
4. "Clone from GitHub does not appear".

- VS Code version:
Version: 1.71.0 (user setup)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No
- OS version: Windows, version 21H2 (OS Build 22000.856)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|17.88GB (9.03GB free)|
|Process Argv|--crash-reporter-id 0627d675-c088-4008-adc5-bb79ec8d590b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
packer|4op|0.3.0
html-snippets|abu|0.2.1
Bookmarks|ale|13.3.1
git-rename|amb|1.3.0
vagrant|bbe|0.5.0
insert-unicode|bru|0.13.3
regex|chr|0.4.0
dart-code|Dar|3.48.3
flutter|Dar|3.48.0
vscode-markdownlint|Dav|0.48.1
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
vscode-solution-explorer|fer|0.7.1
code-runner|for|0.11.8
copilot|Git|1.44.6735
go|gol|0.35.2
hcl|has|0.2.1
terraform|has|2.24.2
vscode-todo-highlight|jgc|2.0.4
gruvbox-material-icon-theme|Jon|1.1.5
vsc-python-indent|Kev|1.17.0
MagicPython|mag|1.1.0
vscode-autohotkey-plus-plus|mar|2.8.4
rainbow-csv|mec|3.0.0
vscode-antlr4|mik|2.3.0
prettify-json|moh|0.0.3
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.22.1
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
azure-account|ms-|0.11.1
powershell|ms-|2022.8.5
remote-repositories|ms-|0.20.0
vsliveshare|ms-|1.0.5711
sqltools|mtx|0.24.0
sqltools-driver-mssql|mtx|0.3.0
uuid-generator|net|0.0.5
autodocstring|njp|0.6.1
vscode-vault|owe|2.2.3
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.18.7
typescript-hero|rbb|3.0.0
vscode-commons|red|0.0.6
vscode-xml|red|0.21.2022062916
vscode-yaml|red|1.10.1
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.7.3
vscodeintellicode|Vis|1.2.25
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by lszomoru** [comment]
@ChristoWolf, the "Clone from GitHub" command is being contributed by the "GitHub" built-in extension. Is there a chance that the "GitHub" extension is disabled? Please open the "Extensions" view, search for "@builtin" and scroll down to the "GitHub" extension. Is the extension enabled? if not, can you please enable it and see if that resolves the problem? Thanks!

**Comment by ChristoWolf** [comment]
@lszomoru: That was exactly the issue!
I have no idea how, but the built-in GitHub extension was disabled.
In hindsight I feel stupid, thanks a lot for your help!

**Comment by lszomoru** [comment]
@ChristoWolf, no worries. I am glad that we were able to fix it.
