### ISSUE TITLE
settingsSync.ignoredSettings didn't work

### ISSUE THREAD

**Issue by Neutralization** [microsoft/vscode#160641]
Type: <b>Bug</b>

settings.json
---
{
"settingsSync.ignoredSettings": [
        "-python.formatting.blackPath",
        "-python.linting.flake8Path",
        "-python.linting.pycodestylePath"
    ],
"python.formatting.blackPath": "C:\\\\Users\\\\`username`\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\Scripts\\\\black.exe",
"python.linting.flake8Path": "C:\\\\Users\\\\`username`\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\Scripts\\\\flake8.exe",
"python.linting.pycodestylePath": "C:\\\\Users\\\\`username`\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\Scripts\\\\pycodestyle.exe"
}

ignoredSettings still sync to another computer's vscode.
I use different `username` on two computers, so I need to change these paths every time to make linting work properly.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|27.86GB (17.76GB free)|
|Process Argv|--crash-reporter-id ae758070-927f-4c49-8527-8ef02f1f4e8b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
extendscript-debug|Ado|2.0.3
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
transformer|dak|1.12.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
vscode-diff|fab|1.4.2
vscode-language-pack-zh-hans|MS-|1.71.9070915
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
powershell|ms-|2022.8.5
vscode-sort-json|ric|1.20.0
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by sandy081** [comment]
`python.formatting.blackPath` is not synced by default. By adding `-python.formatting.blackPath` to `settingsSync.ignoredSettings` you made it synced. So it is working as expected. Please remove it from ignored settings if you do no want that to be synced
