### ISSUE TITLE
can't exclude files with exceptance

### ISSUE THREAD

**Issue by zzzh** [microsoft/vscode#160638]
Type: <b>Bug</b>

for example, I want to exclude path-a except the path-b in path-a, following code don't work:

in settings.json:
"files.exclude": {
        /path-a: true
        /path-a/path-b: false
    },

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A8-7650K Radeon R7, 10 Compute Cores 4C+6G  (4 x 3293)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|9.98GB (1.96GB free)|
|Process Argv|--crash-reporter-id a7a56cab-0e00-4c9c-8e98-51ca2ca2baed|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
luatos-snippet|che|0.0.995
arm|dan|1.7.4
githistory|don|0.6.19
gitlens|eam|12.2.2
EditorConfig|Edi|0.16.4
cmake-language-support-vscode|jos|0.0.4
luatide|lua|2.2.6
cortex-debug|mar|1.6.3
json|Mee|0.0.1
git-graph|mhu|1.30.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.12.26
cpptools|ms-|1.12.4
hexeditor|ms-|1.9.8
makefile-tools|ms-|0.6.0
vscode-embedded-tools|ms-|0.3.0
vscode-serial-monitor|ms-|0.3.0
indent-rainbow|ode|8.3.1
shellman|Rem|5.6.0
ninja|sur|0.0.1
even-better-toml|tam|0.18.1
devicetree|tro|2.3.1
cmake|twx|0.0.17
errorlens|use|3.6.0
vscode-icons|vsc|11.16.0
debug|web|0.26.0
luahelper|yin|0.2.19
json|Zai|2.0.2
linkerscript|Zix|1.0.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by lramos15** [comment]
\duplicate #869
