### ISSUE TITLE
Blank lines in TS code cause breakpoints to move upon browser refresh.

### ISSUE THREAD

**Issue by jeffsim** [Microsoft/vscode#16066]
- VSCode Version: 1.7.2
- OS Version: Windows 10
- Debugger for Chrome extension version: 2.2.2

I drop a breakpoint into typescript code which will get hit after the page loads as expected.  I continue running in VS Code and then hit 'f5' in the browser; the breakpoint is hit again in VS Code, but the red breakpoint dot in VS Code moves up to an earlier line in the code.  The distance it moves up is equal to the number of empty lines before the breakpoint's original position.

Here's what it looks like on first run:

![On first run](https://www.dropbox.com/s/lvj0r3uq5gcw5t4/firstRun.png?raw=1)

And here's what it looks like after continuing and then hitting refresh in Chrome:

![On first run](https://www.dropbox.com/s/dap0vm0l72oxkui/afterRefresh.png?raw=1)

Apologies if this is caused by an obvious error on my part; this seems like something everyone would have hit, so I've created a minimum repro case of the issue to help demonstrate it.  I'd greatly appreciate any assistance in understanding what's going on.

Steps to Reproduce:

1. Download the ~4kb zipped project from here: https://www.dropbox.com/s/e8xu4157n9j3hxa/tsNSRepro.zip?dl=0
2. npm install to get the dependencies, and ensure Chrome and the Debugger for Chrome extension are both installed
3. Place a breakpoint on the "console.log" line in testApp.ts.
4. Build the project and run.  The breakpoint should be hit and appear as per first picture above
5. F5 to continue running in VS Code
6. In the browser, hit F5 to refresh the page
7. Note that in vs code the breakpoint is again hit, but the red dot has moved up the page.

Try adding/removing blank lines and repeat the above, and note how the distance the red dot moves changes accordingly.

Here's the typescript file in question:
```
// NOTE: Blank lines screw up breakpoint loc on F5.


setTimeout(function() {
    console.log("i am a test");
}, 1000);
```

... and here's the gulpfile
```
var gulp = require("gulp"),
    tsc = require("gulp-typescript"),
    sourcemaps = require("gulp-sourcemaps"),
    del = require("del"),
    runSequence = require("run-sequence");

gulp.task("clean", function () {
    return del([ "testApp.js.map", "testApp.js" ]);
});

gulp.task("build-testApp", function (cb) {
    var ts = tsc.createProject("tsconfig.json");
    return gulp.src(["testApp.ts"])
        .pipe(sourcemaps.init())
        .pipe(ts())
        .pipe(sourcemaps.write(".", { includeContent: false, sourceRoot: "." })) 
        .pipe(gulp.dest("."))
});

gulp.task("build-all", function (cb) {
    runSequence("clean", "build-testApp", cb);
});
```

And finally, here's the diagnostic logging output after performing the above steps and F5'ing a couple of times - nothing seems to imply a failure to map breakpoints...

```
Verbose logs are written to C:\Users\jeffs\.vscode\extensions\msjsdiag.debugger-for-chrome-2.2.2\vscode-chrome-debug.txt
8:04:15 AM, 11/25/2016
OS: win32 ia32
Adapter node: v6.5.0 ia32
vscode-chrome-debug-core: 3.6.3
debugger-for-chrome: 2.2.1
spawn('C:\Program Files (x86)\Google\Chrome\Application\chrome.exe', ["--remote-debugging-port=9222","--no-first-run","--no-default-browser-check","--disable-session-crashed-bubble","--disable-infobars","http://127.0.0.1:1025/index.html"])
Discovering targets via http://127.0.0.1:9222/json
Target userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.99 Safari/537.36
Paths.scriptParsed: resolved http://127.0.0.1:1025/testApp.js to c:\Users\jeffs\Desktop\tsRepro\testApp.js. webRoot: c:\Users\jeffs\Desktop\tsRepro
SourceMaps.getMapForGeneratedPath: Finding SourceMap for c:\Users\jeffs\Desktop\tsRepro\testApp.js by URI: testApp.js.map and webRoot: c:\Users\jeffs\Desktop\tsRepro
SourceMaps.loadSourceMapContents: Reading local sourcemap file from c:\Users\jeffs\Desktop\tsRepro\testApp.js.map
SourceMap: creating for c:\Users\jeffs\Desktop\tsRepro\testApp.js
SourceMap: sourceRoot: .
SourceMap: sources: ["testApp.ts"]
SourceMap: webRoot: c:\Users\jeffs\Desktop\tsRepro
SourceMap: resolved sourceRoot . -> c:\Users\jeffs\Desktop\tsRepro
SourceMaps.scriptParsed: c:\Users\jeffs\Desktop\tsRepro\testApp.js was just loaded and has mapped sources: ["c:\\Users\\jeffs\\Desktop\\tsRepro\\testApp.ts"]
SourceMaps.setBP: Mapped c:\Users\jeffs\Desktop\tsRepro\testApp.ts to c:\Users\jeffs\Desktop\tsRepro\testApp.js
SourceMaps.setBP: Mapped c:\Users\jeffs\Desktop\tsRepro\testApp.ts:9:1 to c:\Users\jeffs\Desktop\tsRepro\testApp.js:3:5
Paths.setBP: Resolved c:\Users\jeffs\Desktop\tsRepro\testApp.js to http://127.0.0.1:1025/testApp.js
SourceMaps.setBP: Mapped c:\Users\jeffs\Desktop\tsRepro\testApp.js:3:5 to c:\Users\jeffs\Desktop\tsRepro\testApp.ts:9
i am a test
Paths.scriptParsed: resolved http://127.0.0.1:1025/testApp.js to c:\Users\jeffs\Desktop\tsRepro\testApp.js. webRoot: c:\Users\jeffs\Desktop\tsRepro
SourceMaps.scriptParsed: c:\Users\jeffs\Desktop\tsRepro\testApp.js was just loaded and has mapped sources: ["c:\\Users\\jeffs\\Desktop\\tsRepro\\testApp.ts"]
i am a test
Paths.scriptParsed: resolved http://127.0.0.1:1025/testApp.js to c:\Users\jeffs\Desktop\tsRepro\testApp.js. webRoot: c:\Users\jeffs\Desktop\tsRepro
SourceMaps.scriptParsed: c:\Users\jeffs\Desktop\tsRepro\testApp.js was just loaded and has mapped sources: ["c:\\Users\\jeffs\\Desktop\\tsRepro\\testApp.ts"]
i am a test
```
Other supporting files (tsconfig.json etc) can be found in the above linked zip file.

Thanks,
Jeff

**Comment by isidorn** [comment]
The breakpoint updates are coming from the debug adapter moving to @weinand

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-chrome-debug#296

**Comment by weinand** [comment]
@isidorn Rob owns the "Debugger for Chrome"
