### ISSUE TITLE
Autoindent line does not work on editor.action.insertLineAfter

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#16063]
- VSCode Version: 1.7.1
- OS Version: MacOs Sierra

Steps to Reproduce:

On this situation :

<img width="255" alt="capture d ecran 2016-11-25 a 15 33 56" src="https://cloud.githubusercontent.com/assets/5599375/20628140/9c772d68-b324-11e6-8ab1-ead6cf23bcaf.png">

if i press CMD+RightArrow then Enter i got the "format on type" triggered :

<img width="261" alt="capture d ecran 2016-11-25 a 15 35 07" src="https://cloud.githubusercontent.com/assets/5599375/20628171/c6e8190e-b324-11e6-8b87-ab6c4bd676b5.png">

But if i directly hit CMD+Enter, it trigger the editor.action.insertLineAfter which give me : 

<img width="235" alt="capture d ecran 2016-11-25 a 15 36 22" src="https://cloud.githubusercontent.com/assets/5599375/20628208/f2a7a924-b324-11e6-9612-4ce44d8332e2.png">

And it does not trigger the "format on type" for the previous line. Which reduce the interest of this command.

**Comment by alexandrudima** [comment]
@jrieken I believe @DavidBabel wishes that cmd+enter should trigger format on type.

**Comment by DavidBabel** [comment]
@alexandrudima exactly
