### ISSUE TITLE
Add CodeActionKind.move as suggested code action kind

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#160728]
Tracks adding a new `refactor.move` code action kind to `vscode.d.ts`

Extensions can already define code actions of this kind, but we should document it and surface it in the new code action menu

JS/TS already supports this kind

**Comment by mjbvz** [comment]
To verify:

1. Check the documentation of https://github.com/microsoft/vscode/blob/42a198b98b279460e1c11310759c4fb34d6be2ab/src/vscode-dts/vscode.d.ts#L2288
2. Using the [code action sample](https://github.com/microsoft/vscode-extension-samples/tree/main/code-actions-sample), make sure that `vscode.CodeActionKind.RefactorMove.value` is `refactor.move`

**Comment by rzhao271** [comment]
I wasn't able to get the new vscode-dts for the code action sample:
```
npx vscode-dts main      
Downloading vscode.d.ts
To:   C:\Users\raymondzhao\work\vscode-extension-samples\code-actions-sample\vscode.d.ts
From: https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/vscode.d.ts
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "Failed to get https://raw.githubusercontent.com/microsoft/vscode/main/src/vs/vscode.d.ts".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
```

**Comment by mjbvz** [comment]
@rzhao271 Works fine for me. Could it be a network issue?
