### ISSUE TITLE
Support arbitrary encodings for git buffers

### ISSUE THREAD

**Issue by j-oliveras** [Microsoft/vscode#16071]
- VSCode Version: 1.7.2
- OS Version: Windows 7 and Windows 10 (both Pro 64 bits).

The left side of git diff view uses a incorrect encoding (loads as utf-8?).

I tested without extensions with the same result.

Steps to Reproduce:
1. Donwload [this repository](https://github.com/j-oliveras/vscode-git-compare-utf16-bug) (sample file saved as utf-16 LE).
2. Edit the file.
3. Open diff view:
![git-diff-vscode-utf-16](https://cloud.githubusercontent.com/assets/15308683/20631227/ded8e41a-b335-11e6-8539-35da9483f19e.png)

I tested with 'Reopen with encoding' using utf-8 and is load the same way as git diff.

**Comment by joaomoreno** [comment]
@j-oliveras Are you sure this was 1.7.2 and not the Insiders release?

**Comment by j-oliveras** [comment]
I can reproduce it with both of them. In previous screenshoot vscode icon is blue.

I opened vscode with --disable-extensions.

![git-diff-vscode-utf-16-both](https://cloud.githubusercontent.com/assets/15308683/20650883/9602e7e0-b4d9-11e6-9419-3f6b51e8ca24.png)

**Comment by joaomoreno** [comment]
Have you tried setting `utf16le` in the `files.encoding` setting, in stable?

**Comment by j-oliveras** [comment]
With this setting works (after restart vscode). Seems like left side uses
default encoding instead of infer it.

El dia 28/11/2016 8:57 a. m., "João Moreno" <notifications@github.com> va
escriure:

**Comment by abrethwaite** [comment]
- VSCode version: 1.11.1

I am having the same issue described above. I used to be able to get around if by setting the files.encoding setting to utf16le but this no longer works with the most recent update for VSCode. The diff tool in Visual Studio is able to show the differences without issue.

**Comment by joaomoreno** [comment]
Git now reads the `files.encoding` value.

**Comment by abrethwaite** [comment]
Hi Joao,

As far as I can tell the original issue the OP posted about remains.

My work around thus far has been to run the "SCM: Disable Preview SCM" command and set the files.encoding setting equal to "utf16le".  It would be nice if the files.autoGuessEncoding setting worked for the diff tool as well!

Drew

**Comment by joaomoreno** [comment]
In `master`, the new SCM world also reads the `files.encoding` setting.
