### ISSUE TITLE
Weird font in terminal tab

### ISSUE THREAD

**Issue by tanhakabir** [microsoft/vscode#160722]
Version: 1.72.0-insider (Universal)
Commit: 835ace5796cec0ed19a7eec119b26b57220b0f1a
Date: 2022-09-12T05:17:27.105Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.4.0
Sandboxed: Yes

<img width="1148" alt="image" src="https://user-images.githubusercontent.com/12758612/189728809-83846fd9-67e8-4a48-a4d9-83a73f7222b2.png">

But other tabs above look fine:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/12758612/189728871-30d3c1fe-2d7d-4bf0-9f29-e6a04189a77b.png">

**Comment by Tyriar** [comment]
Fixed in upcoming 1.71.2

/duplicate
