### ISSUE TITLE
Can't Click on Options in the Quick Fix Menu

### ISSUE THREAD

**Issue by sroyal-statsig** [microsoft/vscode#160709]
Type: <b>Bug</b>

When hovering on an issue in code and then pressing quick fix to bring up the options clicking on the option does nothing. Using the arrow keys and hitting enter does still work.

VS Code version: Code - Insiders 1.72.0-insider (Universal) (835ace5796cec0ed19a7eec119b26b57220b0f1a, 2022-09-12T05:17:27.105Z)
OS version: Darwin arm64 21.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 51d7ad4a-5576-4fe7-8654-0a9d6ee53080|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|12.2.2
prettier-vscode|esb|9.8.0
vscode-pull-request-github|Git|0.50.0
vscode-graphql|Gra|0.7.5
vscode-graphql-syntax|Gra|1.0.4
vscode-power-mode|hoo|3.0.2
vscode-kubernetes-tools|ms-|1.3.10
cpptools|ms-|1.13.0
live-server|ms-|0.4.0
kitty-time|QzS|0.4.6
vscode-thunder-client|ran|1.18.7
java|red|1.10.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
vscodeintellicode|Vis|1.2.25
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.1
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.38.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
pylanb8912:30522163
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30558418
vsccc:30564266

```

</details>

**Comment by sroyal-statsig** [comment]
![Screen Shot 2022-09-12 at 8 30 32 AM](https://user-images.githubusercontent.com/76536058/189695545-b8934a58-e566-4d02-8651-b47002517ff3.png)

**Comment by mjbvz** [comment]
I can't reproduce this issue

Does this happen in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by sroyal-statsig** [comment]
I attached my version info but I believe I'm on the latest version. It does still repro with all extensions disabled
![Screen Shot 2022-09-12 at 8 59 34 AM](https://user-images.githubusercontent.com/76536058/189701231-6c2aa106-b4c7-4dc9-b8e8-35ebe7b93742.png)

**Comment by sroyal-statsig** [comment]
@mjbvz looks like this was also reported in another issue https://github.com/microsoft/vscode/issues/160714. Let me know if there is any other information I can give to help out

**Comment by 1muen** [comment]
I did the update:
Version: 1.72.0-insider (user setup)
Commit: 1a55beb2aaee64eb8d0cbe5b61b10088bbc6c895
Date: 2022-09-13T05:18:15.280Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

and it works again, but the lightbulb is gray:
![grafik](https://user-images.githubusercontent.com/49640488/189862846-0b97b86f-2af2-4c90-a976-049957f347f2.png)
