### ISSUE TITLE
Move corner when in a working tree with multiple versions

### ISSUE THREAD

**Issue by anDB123** [microsoft/vscode#160712]
Type: <b>Feature Request</b>

Like with the sidebar, it would be excellent to be able to click and drag the corner between the terminal (bottom), previous (left) and current (right) version.
This would also make the UI more consistent. 
Thanks for making great software though,
Andrew

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.18.0-394.el8.x86_64

**Comment by Tyriar** [comment]
Do you mean here when in a diff editor?

![image](https://user-images.githubusercontent.com/2193314/190412060-e08cc664-78a0-4c32-a05e-89023de6b863.png)

**Comment by anDB123** [comment]
> Do you mean here when in a diff editor?
> 
> ![image](https://user-images.githubusercontent.com/2193314/190412060-e08cc664-78a0-4c32-a05e-89023de6b863.png)

Yes, exactly!

**Comment by joaomoreno** [comment]
This is actually fairly low hanging. [Here's how the **centered view layout** did it](https://github.com/microsoft/vscode/blob/a298e58fd6cc5c87eefa30d8c7c0e68f2443261c/src/vs/base/browser/ui/centered/centeredViewLayout.ts#L85-L87).

**Comment by dmartzol** [comment]
I would like to look into this one. I'll be taking a look at it :)

**Comment by weartist** [comment]
> I would like to look into this one. I'll be taking a look at it :)

hi~is it still going well? If you are not following for now, I can look at this issue

**Comment by dmartzol** [comment]
> 

yes, this is going well, I will have it very soon. Thank you for checking

**Comment by BuraChuhadar** [comment]
Which component needs to be edited for this kind of change? The way I see it, CodeEditorWidget implements this but it is not part of the ui/layout components. If you want to bring an orthogonalStartSash and orthogonalEndSash to CodeEditorWidget, which ui component needs to be edited?

**Comment by dmartzol** [comment]
Just an update on my side: my plan was to look into this issue this past weekend but I didn't have time to work on it.

I'll be supporting @BuraChuhadar in case I can help him finish the PR that is in progress.

@joaomoreno are you sure this is a good first issue? 😅

**Comment by StephenChips** [comment]
@dmartzol Can you share you discovery and knowledge needed for implementing this feature? For instance, what modules should we look into? How does objects interacts with each other? I am willing to give you a hand but I don't know much about VSCode's internal details.

**Comment by babyccino** [comment]
> @dmartzol Can you share your discovery and knowledge needed for implementing this feature? For instance, what modules should we look into? I am willing to give you a hand but I don't know much about VSCode's internal details.

I was also looking into this but got very stuck. I'd be happy to help out anyone who is a bit more experienced with the project. Looking into DiffEditorWidgetSideBySide and SplitView was as far as I got. "orthogonal start/end sash" is the sash at the top and bottom of the editor panel. I just couldn't see an easy way to get DiffEditorWidgetSideBySide a reference to the start/end sash

**Comment by StephenChips** [comment]
@dmartzol Are you still working on it? Can you share your progress?

**Comment by harshitanov** [comment]
Hello! I'd like to work on this issue! :)

**Comment by GauravB159** [comment]
Hi, is anyone working on this? If not, can I take a look at it?

**Comment by dmartzol** [comment]
@joaomoreno is this still a "Good first issue"? A few people has looked into it with no success so far

**Comment by joaomoreno** [comment]
Sorry all for not helping more here. Been quite busy. Good news is that I have a PR that implements this: https://github.com/microsoft/vscode/pull/169864
