### ISSUE TITLE
#ifdef/endif colorization matching doesn't work correctly with C/C++

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#160744]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.72.0-insider (user setup)
Commit: 835ace5796cec0ed19a7eec119b26b57220b0f1a
Date: 2022-09-12T05:16:16.290Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
It doesn't repro with non-Insiders.

Steps to Reproduce:

1. Use a .c or .cpp file with
```cpp
#ifdef FOO
#endif
```

Bug: The matching code doesn't handle this case (and #ifndef, #else, #elif, #elifdef, #elifndef):
![image](https://user-images.githubusercontent.com/19859882/189774658-0886f7d7-6986-41ee-860b-42f969850d27.png)

The C/C++ extension is not enabled.

**Comment by RedCMD** [comment]
seems only `#if` was added as `brackets`
https://media.discordapp.net/attachments/585739600971169809/1018970139850448896/image0.jpg

**Comment by hediet** [comment]
Closing, as the PR that introduced this got reverted.
