### ISSUE TITLE
Notebook stdout Output renderer duplicates outputs and linebreaks not renderered

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#160745]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Stable & Insiders
- OS Version: Any

Steps to Reproduce:

1. Install Jupyter extension
2. Run the following cell against a Python kernel
```python
import time
import threading
from IPython.display import display

def work():
	for i in range(10):
		print('iteration %d'%i)
		time.sleep(0.1)

def spawn():
	thread = threading.Thread(target=work)
	thread.start()
	time.sleep(0.3)

spawn()
print('main thread done')
```

The expected output is fairly simple: (`main thread done` can appear some where in the middle)
```
iteration 0
iteration 1
iteration 2
main thread done
iteration 3
iteration 4
iteration 5
iteration 6
iteration 7
iteration 8
iteration 9
```

However VS Codes output is incorrect
* We are missing the line breaks (looks like this PR  https://github.com/microsoft/vscode/pull/147321/files seems to have broken that) (using `style of display `block`, instead of `inline-block` fixes this).
* We have duplicate entries (as you can see below, we have `iteration 3` multiple times) @rebornix i think this has to do with the fact that we're trying to re-use the previous output and append the new stuff into the previous output element

Note: This can be repro'ed in stable as well, but if i were to remove the code that tries to append to the previous element, then it looks as expected. Not sure when this part of the code broken though. Didn't go through the change log to determine this, @rebornix you might have a better idea.

```
iteration 0
0
iteration 1
1
iteration 2
2
main thread done
iteration 3 3 iteration 3 3 iteration 4 4 iteration 3 3 iteration 4 4 iteration 5 5 iteration 3 3 iteration 4 4 iteration 5 5 iteration 6 6 iteration 3 3 iteration 4 4 iteration 5 5 iteration 6 6 iteration 7 7 iteration 3 3 iteration 4 4 iteration 5 5 iteration 6 6 iteration 7 7 iteration 8 8 iteration 3 3 iteration 4 4 iteration 5 5 iteration 6 6 iteration 7 7 iteration 8 8 iteration 9 9
```

**Comment by amunger** [comment]
note that this is from the `More messages from background threads` test, so that could probably be modified to check for the fix

**Comment by remarcmij** [comment]
It looks like this was briefly solved (at least for me as I reported in #11638) but the problem is now reappearing.

**Comment by DonJayamanne** [comment]
I can replicate the same bug again,

**Comment by amunger** [comment]
seems to be a worse regression now (only in insiders) and repros without needing to do anything with background threads (unless I just have some bad setting):

![image](https://user-images.githubusercontent.com/2019016/211100203-7825d45f-8596-4d82-bd42-5f15a3bc4c22.png)

**Comment by remarcmij** [comment]
I'm seeing something similar with the JavaScript/tslab notebook I use for teaching async and promises. Previously, the output was inconsistent across runs with sometimes missing or duplicated output. Now all the expected output is present but with line breaks appearing only after some async code (e.g. `setTimeout()`) is executed.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/2788771/211102144-595ec5ac-6f06-4582-ae89-1be02def84ec.png">

**Comment by eoia** [comment]
I reproduced output shown by @amunger above with missing new lines in code-insiders at ~14:00 UTC +1 (CET). In a code-insiders session that has been running last 24 hours.

Restarting code-insiders approximately an hour later (15.00 UTC+1), the output is now shown with correct line breaks, see screenshot below.
Version: 1.75.0-insider (user setup)
Commit: 04b15ff231a2c3cfcdd90d90c16075a9c1e6da15
Date: 2023-01-09T05:29:27.679Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

Output after code-insiders restart:
![image](https://user-images.githubusercontent.com/11330288/211326253-032dff7d-1ea0-45c9-86f7-47db1b4fdb4f.png)

**Comment by amunger** [comment]
confirmed that this no longer seems to reproduce on the latest.

**Comment by rebornix** [comment]
Adding `verified` label as confirmed above.
