### ISSUE TITLE
Keyboard shortcuts doesn't Prevent Default Action

### ISSUE THREAD

**Issue by kaiye** [Microsoft/vscode#1607]
I have set a shortcut below:

``` json
[
{ "key": "alt+f",   "command": "workbench.action.files.revealActiveFileInWindows" },
]
```

VSCode does reveal the open file in Finder, however sometimes it also print a `ƒ` character which is unexpected. 

![shortcut](https://cloud.githubusercontent.com/assets/344283/11973379/539731a0-a994-11e5-9630-de4834576c4f.gif)

**Comment by alexandrudima** [comment]
I have validated that adding the keybinding rule:

```
{
    "key": "alt+f",
    "command": "workbench.action.files.revealActiveFileInWindows"
}
```

and pressing it repeatedly (with both the left-hand-side Alt and the right-hand-side Alt) does not result in any character being typed in the editor
