### ISSUE TITLE
MacOS Add transparent icon to dock

### ISSUE THREAD

**Issue by effolkronium** [microsoft/vscode#160737]
As MacOS user I used to amazing design software experience. The VSCode icon on MacOS seems boring and with a lot of white space on background

Please make it transparent 

Screenshot with the issue:
<img width="71" alt="image" src="https://user-images.githubusercontent.com/15274763/189764998-cc806015-5191-43d9-b469-becef0d0b52e.png">

**Comment by rajkundu** [comment]
You can set custom icons for your own computer on MacOS. Simply do the following:
1. Find the icon you want (e.g., [this](https://cdn.icon-icons.com/icons2/2107/PNG/512/file_type_vscode_icon_130084.png) VS Code logo PNG with a transparent background). Copy it to your clipboard (Right Click > Copy Image).
2. Open Finder and find the application you'd like to edit. In this case, it's VS Code, likely located at `/Applications/Visual Studio Code.app`.
3. Either right click on the application file and click "Get Info".
4. Click the application icon in the top left of the Info window that opens up. You should see a blue outline around it indicating that it is selected.
5. Paste the new icon using (<kbd>⌘ Command</kbd> + <kbd>V</kbd>)

**Comment by effolkronium** [comment]
Sorry do not have access to the icon
<img width="480" alt="image" src="https://user-images.githubusercontent.com/15274763/189774516-f735407a-eeb5-49ad-9df1-9ab4972a86e9.png">


Anyway I think it need to be commited into official vscode macos bundle. I'll try to create PR for this later

**Comment by rajkundu** [comment]
For your convenience, here is the PNG. You can right click on it and copy it, then follow the instructions above:
![image](https://user-images.githubusercontent.com/35236205/189774890-7e15955e-d519-41ca-9944-9efe521c5a3b.png)

Frankly, I don't think this calls for a pull request at all. You're requesting that Microsoft rebrand VS Code to match your personal preferences – whereas 1) Microsoft already has several professional marketing teams dedicated to these types of decisions, and 2) The VS Code logo has been deliberately designed to match the style of MacOS: see #101014.

**Comment by effolkronium** [comment]
Makes sense
