### ISSUE TITLE
JSDoc: Add support for odd tabSize in onEnterRules

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#16075]
In the description of the JSDoc inside the class declaration is not added symbol `*` when moving to a new line.

- VSCode Version: 
![image](https://cloud.githubusercontent.com/assets/3082812/20632989/e4e0199c-b352-11e6-8de7-b2e8563688a4.png)

- OS Version: Linux Mint 18 x64

Steps to Reproduce:

```js
/**
 * @class My
 * @prop {string} name
 */
class My {
   constructor() {
      this.name = 'MyName';
   }

   /**
    * @method func
    * @param {string} p1
    */
   func() {

   }
}
```
1. In the code in the `label 1` press `Enter`;
2. `*` added in new line (`label 2`);
3. In the code in the `label 3` press `Enter`;
4. `*` not added in new line (`label 4`).

screen1 | screen 2
---|---
![image](https://cloud.githubusercontent.com/assets/3082812/20633042/4c50bf50-b353-11e6-95c8-60a8338d89dd.png) | ![image](https://cloud.githubusercontent.com/assets/3082812/20633016/259914de-b353-11e6-9964-f8c6cf9ac172.png)

**Comment by alexandrudima** [comment]
@IgorNovozhilov See comment in #16076. I believe you might have installed an extension that binds the "enter" key and implements its own enter custom logic instead of our default one.

**Comment by IgorNovozhilov** [comment]
Your example doesn't match what I sent.
Not only works inside the class definition:
```js
/**
 * @class My
 * @prop {string} name
 */
class My {
   constructor() {
      this.name = 'MyName';
   }

   /**
    * @method func
    * @param {string} p1
    */
   func() {

   }
}
```

**Comment by IgorNovozhilov** [comment]
The same does not work when using an odd number of spaces when the tab for example 3

**Comment by IgorNovozhilov** [comment]
@alexandrudima, does not work when using an odd number of spaces when the tab for example 3

**Comment by IgorNovozhilov** [comment]
@alexandrudima, the same is not working if I use `Tab` instead of `Spaces`.
if line: `\t\s`*`\t`@propName
after pressing `enter` adds the string without `*`

settings:
```js
   "editor.tabSize": 2,
   "editor.insertSpaces": false
```

**Comment by alexandrudima** [comment]
The regular expressions we ship with are optimized for a certain style of JSDoc comments and for an even number `tabSize`. The typescript/javascript extension could support multiple styles of JSDoc comments through a configuration option and ajust the `onEnterRules` accordingly.

Additionally, an extension could be written to overwrite them to something new.

Code pointer: https://github.com/Microsoft/vscode/blob/4f398bafda1fde8e17ec4646371272baad6d3914/extensions/typescript/src/typescriptMain.ts#L261

fyi @mjbvz

**Comment by IgorNovozhilov** [comment]
:+1:
