### ISSUE TITLE
Process artifacts : Server failed to authenticate the request

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160754]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=184860&view=logs&j=43b54640-f671-5524-8f7b-714d77229de9&s=380ab8c6-4139-55ff-15c4-fb48260f4dca&t=8c631bd7-3091-56a7-0716-a38699ccbe61&l=492

**Comment by joaomoreno** [comment]
Very strange, never saw this before and seems to have been a temporary Azure China issue, since successive builds have succeeded.
