### ISSUE TITLE
JSDoc. Wrong spaces after description, after pressing `Enter` when tabSize is 3

### ISSUE THREAD

**Issue by IgorNovozhilov** [Microsoft/vscode#16076]
After the description of JSDoc is incorrect shall bear count of spaces in the transition to a new line.

- VSCode Version:
![image](https://cloud.githubusercontent.com/assets/3082812/20633199/f1b41b3a-b354-11e6-84c0-c5983fab31cb.png)

- OS Version: Linux Mint 18 x64

Steps to Reproduce:

```js
/**
 * @class My
 * @prop {string} name
 */
class My {
   constructor() {
      this.name = 'MyName';
   }

   /**
    * @method func
    * @param {string} p1
    */
   func() {

   }
}
```

1. In the code in the `label 1` press `Enter`;
2. Print `test`;
3. See four spaces in `label 2`;
4. Real spaces is a three (`label 3`).

screen1 | screen 2
---|---
![image](https://cloud.githubusercontent.com/assets/3082812/20633247/74d0e3b8-b355-11e6-8675-bd3cc8ce3de6.png) | ![image](https://cloud.githubusercontent.com/assets/3082812/20633244/6f68e13c-b355-11e6-8c19-fbf53cd59f08.png)

**Comment by alexandrudima** [comment]
@IgorNovozhilov interestingly, I cannot reproduce. Does this reproduce for you after disabling all extensions?

![enter-jsdoc](https://cloud.githubusercontent.com/assets/5047891/20746491/565b5780-b6e6-11e6-87f0-72ca6469ea7b.gif)

**Comment by IgorNovozhilov** [comment]
Your example doesn't match what I sent.
Not only works inside the class definition:
```js
/**
 * @class My
 * @prop {string} name
 */
class My {
   constructor() {
      this.name = 'MyName';
   }

   /**
    * @method func
    * @param {string} p1
    */
   func() {

   }
}
```

**Comment by IgorNovozhilov** [comment]
The same does not work when using an odd number of spaces when the tab for example 3

**Comment by IgorNovozhilov** [comment]
@alexandrudima, does not work when using an odd number of spaces when the tab for example 3

**Comment by joelday** [comment]
@IgorNovozhilov Are you using https://github.com/joelday/vscode-docthis?

**Comment by IgorNovozhilov** [comment]
@joelday, no, I don't use

**Comment by joelday** [comment]
@IgorNovozhilov Thanks, just checking!

**Comment by alexandrudima** [comment]
Let's merge with #16075
