### ISSUE TITLE
ssh key passphrase prompt appears sporadically and is hard to notice

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#160720]
I use an SSH key with a passphrase for my git connection and lately the prompt to enter the passphrase has started stealing focus while trying to work in the terminal.

I think there used to be a more prominent pop-up, but that pop-up still appears once in a while, so this might just be an additional prompt.

I often don't notice the prompt since I'm looking at the bottom of the window where I'm typing in the terminal, and mostly just think a git command is taking a really long time.

<img width="943" alt="image" src="https://user-images.githubusercontent.com/2019016/189725431-9f34e8e0-0390-4516-9924-e2d43d425a0b.png">

**Comment by lszomoru** [comment]
This should be fixed in the latest Insiders (2022-09-16). 
We do not override the SSH_ASKPASS environment variable for the integrated terminal.
