### ISSUE TITLE
Workspace Trust dialog shown regardless of the setting of "security.workspace.trust.startupPrompt"

### ISSUE THREAD

**Issue by TimLewis0** [microsoft/vscode#160747]
Type: <b>Bug</b>

My understanding of setting "security.workspace.trust.startupPrompt" to "never" means that I should never be shown a Workspace Trust dialog and the workspace or folder should remain untrusted.  Similarly, setting this to "once" should show the Workspace Trust dialog once per workspace or folder and never again.  Neither of these appear to be working as intended in 1.7.1.0

Set the following in the settings:

    "security.workspace.trust.enabled": true,
    "security.workspace.trust.emptyWindow": false,
    "security.workspace.trust.startupPrompt": "never",

Test 1: Open a new window.  
Expected result:  Workspace Trust should not show dialog.
Actual result: Workspace Trust dialog shown.

Test 2: Open an untrusted folder.
Expected result:  Workspace Trust should not show dialog.
Actual result: Workspace Trust dialog shown.

Test 3:  Set "security.workspace.trust.startupPrompt" to "once".  Open an untrusted folder.  Cancel out of the Workspace Trust dialog.  Re-open the same folder.
Expected result:  Workspace Trust should not show dialog.
Actual result: Workspace Trust dialog shown.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes: Restricted
Sandboxed: No

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by lszomoru** [comment]
@TimLewis0, could you please provide a screenshot of the dialog that you are seeing? Thank you!

**Comment by AlbertoFabbri93** [comment]
I have the same problem, even though I have:
```
"security.workspace.trust.startupPrompt": "never",
```
in my `settings.json`, I am shown the trust dialog shown above by @TimLewis0.
`

**Comment by lszomoru** [comment]
@TimLewis0, @AlbertoFabbri93, I believe this is a known issue that should be addressed soon. Adding @meganrogge

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by TimLewis0** [comment]
@meganrogge, I cannot reproduce this in the insider's build from your link.  In the scenarios above, the insider's build is doing what I would expect.  @AlbertoFabbri93, you may want to confirm for yourself - I'm not sure if you're doing something different that I am.

The one thing that I noticed that was missing was the dialog shown in the first picture.  I'm assuming that none of the scenarios outlined lead to a circumstance in which it is supposed to appear, but I thought I would confirm that it does not appear.

On my side, I think I can confirm that this is fixed.  Let me know if there is anything else you need or if I should close this.  Thank you!

**Comment by TimLewis0** [comment]
I just received the 1.71.**2** update and this appears to be no longer an issue in that version.  If everyone agrees, I think this can be closed.  @meganrogge, is this a dup of #160362?
