### ISSUE TITLE
Comment line shortcut Command+/ does not work anymore in .bicep files

### ISSUE THREAD

**Issue by Geertvdc** [microsoft/vscode#160723]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```
Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:25.516Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```
- OS Version:
```
macos Montery 12.5.1 (M1)
```

Steps to Reproduce:

1. Have default keybindings settings. 
2. open a .bicep file
3. Try to comment a line with `command + /` 
4. nothing happens.

I tried to enable logging of keybindings (see screenshot) and it seems to execute the comment command but nothing happens in the file. 
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/8984505/189731304-3d1b9b61-d8b0-44cd-aec1-4c66e8f340fb.png">

all other filetypes do work (tried .cs, .yaml, .md)

**Comment by gjsjohnmurray** [comment]
See also #160595

**Comment by Geertvdc** [comment]
update: it only seems to happen in .bicep files. other filetypes still work.

other options to comment `command + K, command + C` don't work either.

**Comment by alexdima** [comment]
Please report directly against the extension that supplies the language configuration for `.bicep` files.
