### ISSUE TITLE
Wrong file deleted from selected range

### ISSUE THREAD

**Issue by zifik** [microsoft/vscode#160793]
Type: <b>Bug</b>

If the user is not paying attention, they end up deleting files that were to be preserved instead of deleted. 

1) Use mouse + shift key to select a range of files for deletion.
2) Use mouse + ctrl key to deselect a file in the selected range.
3) Press the delete key. 
4) The deselected file is offered for deletion, not the selected range.

The delete key after performing the steps above should operate on the selected range, not the last file clicked.

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.13.14-200.fc34.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (11.44GB free)|
|Process Argv|--folder-uri vscode-remote://dev-container%2B7b22686f737450617468223a222f686f6d652f757365722f776f726b7370616365732f776966692d64656d6f64222c226c6f63616c446f636b6572223a66616c73652c2273657474696e6773223a7b22686f7374223a227373683a2f2f6b726973646576227d7d/workspaces/wifi-demod --crash-reporter-id ebd97425-361d-45a7-b8af-34b78197391b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: C++ @ ssh://krisdev|
|OS|Linux x64 5.13.14-200.fc34.x86_64|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (6 x 2400)|
|Memory (System)|7.75GB (6.15GB free)|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
language-cython|guy|0.0.7
firebase-snippets|has|0.0.1
better-cpp-syntax|jef|1.15.19
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
matlab-complete|Sla|1.1.1
material-theme|zhu|3.15.5
tasks|act|0.10.0
gitlens|eam|12.2.2
better-cpp-syntax|jef|1.15.19
vscode-catch2-test-adapter|mat|4.3.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.10
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
cpptools|ms-|1.12.4
cmake|twx|0.0.17

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by lramos15** [comment]
This has been fixed in the latest VS Code insiders feel free to give it a try here https://code.visualstudio.com/insiders/. It will be released in the stable builds in early october.
