### ISSUE TITLE
The default `"fileLocation": "relative"` property for tasks does not work with npm tasks that use the `"path"` property

### ISSUE THREAD

**Issue by segevfiner** [microsoft/vscode#160771]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.71.0
- OS Version: macOS 12.15.1

Steps to Reproduce:

1. Define any npm task that is in a subfolder using the `"path"` property, and define a `problemMatcher` that uses `"fileLocation": "relative"`.
2. It won't work, as the directory that it should be relative to will be the `${workspaceFolder}` rather than the actual working directory of the npm script set by `"path"`.

**Comment by babakks** [comment]
@meganrogge I looked into the problem and created [this](http://github.com/babakks/vscode-verify-problem-matchers-in-subdirs) repo to help reproduce the problem:

However, I think the solution is not that straightforward because NPM tasks (i.e., tasks defined with `{"type": "npm", "path": "some/path"}`) are not intrinsic parts of the VS Code and are contributed by the `npm` built-in extension. So, the `path` property (which is specific to NPM tasks) is not knowable to the VS Code internals that is handling the problem matchers and relative file locations (i.e., where the `"fileLocation": "relative"` is received).

Therefore, we'd need some form of integration that lets extensions provide their means for URI resolution/rewriting. This, of course, needs thorough investigation.

@segevfiner However, there's an existing solution. You can setup the problem matcher with a specific working directory (which is the location of the child `package.json`):

```json
"problemMatcher": {
    "applyTo": "allDocuments",
    "fileLocation": [
        "relative",
        "${workspaceFolder}/subdir"
    ]
}
```

**Comment by oleggladyshev** [comment]
I suggest to look at the problem a bit wider. I have been working on a project with a build system designed in a way when it changes working folders sometimes during a build process and uses relative file names. For example, if the project consist of following folders:

- system1
- system2

The build system runs: `cd system1 && make` and then `cd system2 && make`. When a compilation error generated by a compiler, VSCode knows nothing about a current folder, thus, nether "relative" nor "absolute" works for "fileLocation" when the compiler uses relative file paths. 
Taking into account the build system can't be changed to use absolute paths, would it be possible to teach VSCode to search files given by a base name in ANY folder of the project? Exactly like it does when CTRL+P is pressed. 
We could introduce a new third option for the "fileLocation" property indicating to VSCode that it should search for the file everywhere.
I believe, this approach would solve this issue, but also it could solve other issues as well.

**Comment by babakks** [comment]
Generally searching for the file could end up in unwanted file system seeks and surely incur performance issues (just think of looking for some `index.js` within a huge `node_modules` directory). But, if we could narrow down the search path this would not be a concern.

For example, having something like this makes sense:

```json
"problemMatcher": {
    "fileLocation": [
        "search",
        [
            "${workspaceFolder}/subdir1",
            "${workspaceFolder}/subdir2"
        ],
        [
            "${workspaceFolder}/subdir1/subdir-to-ignore",
            "${workspaceFolder}/subdir2/subdir-to-ignore"
        ]
    ]
}
```

Or a more verbose format like this:

```json
"problemMatcher": {
    "fileLocation": [
        "search",
        {
            "include": [
                "${workspaceFolder}/subdir1",
                "${workspaceFolder}/subdir2"
            ],
            "exclude": [
                "${workspaceFolder}/subdir1/subdir-to-ignore",
                "${workspaceFolder}/subdir2/subdir-to-ignore"
            ]
        }
    ]
}
```

@meganrogge How about this?

**Comment by segevfiner** [comment]
Arbitrary searches for files with a "similar path" could easily end up with false positives, no?

@babakks Yeah I figured that one out by myself as well, but I was a bit surprised that I had too, on the other end it's not difficult to think of why such a thing doesn't work automatically.

**Comment by oleggladyshev** [comment]
> Arbitrary searches for files with a "similar path" could easily end up with false positives, no?
> 
@segevfiner, of course, there is a chance that there are multiple files with the same name in the project. In this case VSCode could suggest to choose a proper one, exactly as it does when "Go to definition" finds more than one implementations. 

However, I like the approach suggested by @babakks. It can decrease amount of false positives if search directories configured properly on one hand and it really solve the issue on the other hand.

**Comment by babakks** [comment]
@meganrogge If that's fine with you, I can work on a PR to add such a file locating method:

```json
"problemMatcher": {
    "fileLocation": [
        "search",
        {
            "include": [
                "${workspaceFolder}/subdir1",
                "${workspaceFolder}/subdir2"
            ],
            "exclude": [
                "${workspaceFolder}/subdir1/subdir-to-ignore",
                "${workspaceFolder}/subdir2/subdir-to-ignore"
            ]
        }
    ]
```

**Comment by meganrogge** [comment]
yep @babakks that would be great 👍🏼

**Comment by babakks** [comment]
@meganrogge I've submitted the PR.

**Comment by babakks** [comment]
@meganrogge @connor4312 Sorry to intrude because it's none of my business, but since this is a new feature maybe it's not a bad idea to introduce it in the new version's release notes. Just wanted to remind you if it was missed in any way.

**Comment by meganrogge** [comment]
@babakks It's mentioned here in the release notes 

![Screenshot 2022-12-05 at 4 12 01 PM](https://user-images.githubusercontent.com/29464607/205753541-8bcc209d-5458-48a2-97bd-f7ccdafef2e3.png)

**Comment by babakks** [comment]
@meganrogge Yes, I've already seen it. I didn't mean the contributions list, though.

**Comment by meganrogge** [comment]
I will accept a PR to the vscode-docs repo on the vnext branch @babakks but otherwise am not going to get to it most likely
