### ISSUE TITLE
selecting a command from `Run recent` list should clear other text from the terminal

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#160705]
I often want to re run a command and start typing then think it's not worth the effort or I don't recall it exactly so I go to run recent and select the one I want to run. 

🐛 the command is concatenated to the incomplete command I had inputted

**Comment by meganrogge** [comment]
I remember thinking this should be the functionality originally. @Tyriar what were your concerns related to this?

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/144279

I tried to do this earlier but it was harder than anticipated
