### ISSUE TITLE
Handler for "+" button on Terminal tab

### ISSUE THREAD

**Issue by shyam-arora** [microsoft/vscode#160751]
I am working on a customized terminal. To open it, I use the command palette followed by the "terminal.show" command. Please provide a way to add a custom handler that will be triggered on clicking "+" in the terminal tab.

![image](https://user-images.githubusercontent.com/25132374/189796976-3174af0a-52a5-48e4-8668-c8e589c091e8.png)

**Comment by Tyriar** [comment]
They + button is always the default profile, you can provide a profile that a user can set as the default using the `registerTerminalProfileProvider` API
