### ISSUE TITLE
PHP Invalid syntax highlighting

### ISSUE THREAD

**Issue by ErnstStavroBlofeld** [microsoft/vscode#160713]
Type: <b>Bug</b>

Bugs:
- No support for generics `array<int, string>`
- No support for meta-types `class-string` or `class-string<ArrayAccessible>`
- No support for:
  - `@teplate`
  - `@implements`
  - `@extends`
- Namespace `\App\My\Class` will have portion `\App\My\` inherit comment color and `Class` actually properly colored (support.class.php - meta.other.type.phpdoc.php)

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

**Comment by ErnstStavroBlofeld** [comment]
Example 2 - namespaces

<img width="394" alt="image" src="https://user-images.githubusercontent.com/54907080/189702624-e8910653-e6eb-4de1-a463-55bbe8aaf262.png">

**Comment by roblourens** [comment]
Filed upstream https://github.com/atom/language-php/issues/461
