### ISSUE TITLE
VS Code icon position is wrong after full screen on mac

### ISSUE THREAD

**Issue by Laev** [microsoft/vscode#160770]
Type: <b>Bug</b>

Make the VSCODE window full screen, move the mouse to the upper viewing border to display the icons such as closed and miniaturizing, and find that the window icon is not in the middle.

![2022-09-13](https://user-images.githubusercontent.com/26376546/189861233-742ccf20-1efe-4e38-96e5-b6896baa0205.png)

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|13, 13, 6|
|Memory (System)|16.00GB (3.48GB free)|
|Process Argv|-psn_0_69649 --crash-reporter-id 98c9244c-7509-4069-bf0d-e6a70204af10|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (121)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
scss-lint|ada|0.1.10
vscode-nginx-conf|ahm|0.1.3
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
tinypng|and|1.1.1
unocss|ant|0.45.21
console-helper|AT-|2.5.1
All-Autocomplete|Ati|0.0.23
node-json-autocomplete|bhs|0.1.3
color-info|bie|0.7.0
markdown-preview-github-styles|bie|1.0.1
simple-react-snippets|bur|1.2.6
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
regex|chr|0.4.0
cssrem|cip|3.0.2
vscode-devtools-for-chrome|cod|0.0.7
vue-peek|dar|1.0.2
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
vscode-faker|dee|2.0.0
react-redux-react-router-snippets|dis|0.4.29
vscode-npm-source|dku|1.0.0
docs-yaml|doc|0.2.8
es7-react-js-snippets|dsz|4.4.3
vscode-changelog-snippets|dzg|0.1.1
gitlens|eam|12.2.2
remotehub|eam|0.5.0
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.3.1
carbon-now-sh|eri|1.2.0
prettier-vscode|esb|9.8.0
vscode-npm|fkn|3.3.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
html-slim-scss-css-class-completion|gen|1.7.8
lintlens|ghm|3.0.3
codespaces|Git|1.10.4
copilot|Git|1.44.6735
wireit|goo|0.3.0
todo-tree|Gru|0.0.215
fe-file-rename|han|0.0.10
vscode-drawio|hed|1.6.4
vscode-import-formatter|hen|0.1.8
githd|hui|2.3.3
output-colorizer|IBM|0.1.2
error-gutters|Igo|1.0.1
vscode-postfix-ts|ipa|1.10.1
vscode-env|Iro|0.1.0
vscode-cdnjs|Jak|0.19.0
batch-rename-extension|Jan|0.0.5
search-node-modules|jas|1.3.0
polacode-2019|jef|0.6.1
svg|joc|1.4.19
package-plus-plus|jun|0.0.1
vscode-codemetrics|kis|1.24.0
vscode-gutter-preview|kis|0.30.0
autoscssstruct4vue|KQ|0.1.5
px-to-vw|lee|1.0.2
vscode-leetcode|Lee|0.18.1
react-taro-snippets|liu|0.0.4
i18n-ally|lok|2.8.1
scss-refactoring|luk|0.1.4
json-to-ts|Mar|1.7.5
markdown-shortcuts|mdi|0.12.0
git-graph|mhu|1.30.0
import-sorter|mik|3.3.1
formate|Mik|1.2.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.22.1
vscode-language-pack-zh-hans|MS-|1.71.9070915
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
vs-keybindings|ms-|0.2.1
jsflowchart|MUL|0.1.6
gradle-language|nac|0.2.3
sftp|Nat|1.15.14
color-highlight|nau|2.5.0
abracadabra|nic|6.15.3
indent-rainbow|ode|8.3.1
fix-json|oli|0.1.2
docthis|oou|0.8.2
vuehelper|oys|0.1.0
vscode-yaml-sort|Pas|5.3.2
vscode-versionlens|pfl|1.0.10
material-icon-theme|PKi|4.20.0
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
any-rule|rus|0.3.15
partial-diff|ryu|1.4.3
vscode-javascript-booster|sbu|14.0.1
vscode-fileutils|sle|3.5.0
vscode-taskexplorer|spm|2.9.1
code-spell-checker|str|2.7.3
language-stylus|sys|1.16.0
stylus-supremacy|thi|2.16.0
hosts|tom|1.2.0
vscode-choosealicense|ult|0.9.0
codelf|unb|11.7.0
highlight-matching-tag|vin|0.10.1
vscodeintellicode|Vis|1.2.25
vscode-conventional-commits|viv|1.24.2
volar|Vue|0.40.13
vscode-wakatime|Wak|19.3.0
vscode-todo-highlight|way|1.0.5
vscode-nginx|wil|0.7.2
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.5.0
luahelper|yin|0.2.19
open-in-external-app|YuT|0.6.0
view-github-repository|YuT|1.1.0
markdown-all-in-one|yzh|3.4.3

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/159862
