### ISSUE TITLE
Extensions Clean-up after update 

### ISSUE THREAD

**Issue by dumians** [microsoft/vscode#160717]
Hi,

I'm a regular user of vscode . One thing that I'm finding not quite ideal it's that after updating extensions, the older versions are remaining in the .vscode\extensions folder unpacked as well as in the cache download folder. So, at the end the VSCode folders are most disk consumers. I expect that the version validation /update sequence can clean old ones after successfully installations.
<img width="353" alt="image" src="https://user-images.githubusercontent.com/3680349/189717900-e90e4ddc-2ea8-454c-a327-0563e14f38f3.png">

**Comment by sandy081** [comment]
These gets cleaned up after restarting VS Code.
