### ISSUE TITLE
":" trigger autocomplete in TS

### ISSUE THREAD

**Issue by DavidBabel** [Microsoft/vscode#16072]
- VSCode Version: 1.7.1
- OS Version: MacOs Sierra

Steps to Reproduce:

1. open a TS file
2. create a class and a field named (for example) "result"
3. press ":" (like you want to define type)
4. result in "XPathResult:" because ":" trigger autocomplete on variable, which is anoying for typescript.

**Comment by jrieken** [comment]
There is two concepts in VS Code - 24x7 IntelliSense (as you type) and trigger characters. The latter are language specific and defined as keybinding - for TypeScript the default is just the [dot](https://github.com/Microsoft/vscode/blob/master/extensions/typescript/package.json#L248), not colon. You can do the following

* update keybinding.json to remove/add trigger characters
* turn off `editor.suggestOnTriggerCharacters`
* turn off `editor.quickSuggestions` (as you type)
