### ISSUE TITLE
Chinese garbled in output -> task

### ISSUE THREAD

**Issue by qslcna** [Microsoft/vscode#16070]
- VSCode Version: 1.7.2
- OS Version: Win7 zh-cn

Steps to Reproduce:

1. Run the task I created named "test"
2. Show below
![image](https://cloud.githubusercontent.com/assets/16847935/20630586/b62cad08-b36c-11e6-8825-817175186416.png)

**Comment by qslcna** [comment]
How to solve this problem?  @dbaeumer

**Comment by dbaeumer** [comment]
Dups #3550

**Comment by dbaeumer** [comment]
As a work around you can use the terminal to run a command. This has proper output encoding handling.
