### ISSUE TITLE
Code Actions Menu

### ISSUE THREAD

**Issue by bdlindsay** [microsoft/vscode#160799]
Type: <b>Bug</b>

In your code actions rewrite, it no longer lets me type to select an option from the menu

VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.4.0
Modes:
Sandboxed: No

**Comment by mjbvz** [comment]
Duplicate of #157719
