### ISSUE TITLE
No jsDoc tags suggest in new Version

### ISSUE THREAD

**Issue by BNU-LeiWen** [microsoft/vscode#160750]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.0
- OS Version: Darwin x64 21.6.0

Steps to Reproduce:
1. with earlier version you can get the full suggestions for jsDoc comment tags like @abstract when you typing @ after '// ' or '/** */' but now it's not working anymore.
<img width="531" alt="截屏2022-09-09 17 08 23" src="https://user-images.githubusercontent.com/43022572/189787961-91e4f8be-ca31-44cc-947c-14b71ad9365d.png">
<img width="522" alt="截屏2022-09-09 17 08 39" src="https://user-images.githubusercontent.com/43022572/189787966-401d3ea1-7f84-4cb7-b75e-d444f0286f3c.png">

**Comment by mjbvz** [comment]
JSDoc tags are only supported in `/*` style comments

Your first example shows `//` style comments. These can be used for special directives but not for JSDoc tags

**Comment by BNU-LeiWen** [comment]
> JSDoc tags are only supported in `/** */` style comments
> 
> Your first example shows `//` style comments. These can be used for special directives but not for JSDoc tags

sorry I didn't make it clearly. 
The problem is that jsDoc tags suggestions don't pop up in '/** */' style; at the same time, the other tags from feature of typescript like the pictrue show above didn't show after '//' style too.
