### ISSUE TITLE
Focus shifts from terminal to editor unexpectedly after "git merge --abort"

### ISSUE THREAD

**Issue by stevencl** [microsoft/vscode#160772]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.72.0-insider (user setup)
Commit: 1a55beb2aaee64eb8d0cbe5b61b10088bbc6c895
Date: 2022-09-13T05:18:15.280Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes

Steps to Reproduce:
1. After attempting a merge, I did "git merge --abort" from the terminal in VS Code.
2. Once the command completed, I had another git command to run so I started typing it, assuming focus was still in the terminal. I was surprised to see though that focus had shifted to the editor after the git merge --abort command and that instead of typing my command in the terminal, I ended up modifying the editor.

I expected that focus would remain in the terminal after the git merge --abort command.

**Comment by lszomoru** [comment]
@stevencl, does this happen with any other git commands or only git merge --abort?

**Comment by bpasero** [comment]
I also saw this when testing merge editor and think this is relevant only for merge editors.

**Comment by stevencl** [comment]
I haven't done extensive testing of many git commands but git merge --abort is the only one I have seen so far that does this.

**Comment by lszomoru** [comment]
> I also saw this when testing merge editor and think this is relevant only for merge editors.

@hediet, @jrieken is this something that you could look into? Thanks!

**Comment by jrieken** [comment]
likely because of the workaround for https://github.com/microsoft/vscode/issues/155940. The merge editor detect the inputs (current, incoming, base) going empty and closes itself. I guess we don't tell the workbench to preserve focus then which happens somewhere [here](https://github.com/microsoft/vscode/blob/2ad3d68d9b42dfe761b3ce98d8936c766585cf2c/src/vs/workbench/contrib/mergeEditor/browser/view/mergeEditor.ts#L294)

**Comment by jrieken** [comment]
@bpasero Upon inspection I now wonder if there is a way to replace editors (via [`replaceEditors`](https://github.com/microsoft/vscode/blob/ba7c20aa6c23c8b2299f886cd4a102f5498f69be/src/vs/workbench/services/editor/common/editorService.ts#L255)) while preserving focus?

**Comment by bpasero** [comment]
@jrieken you can pass in editor options with the replace call, can you try passing `preserveFocus: true` via:

https://github.com/microsoft/vscode/blob/c6698eacedf365c2f152f1df85a79bd6da71fa02/src/vs/workbench/services/editor/common/editorGroupsService.ts#L106
