### ISSUE TITLE
Unable to use built-in renderer with a custom renderer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#160742]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.72.0-insider (Universal)
Commit: 835ace5796cec0ed19a7eec119b26b57220b0f1a
Date: 2022-09-12T05:17:27.105Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

Steps to Reproduce:

1. Clone repo https://github.com/DonJayamanne/vscode-notebook-renderer-mime
2. npm install, and build the extension
3. Install Jupyter extension and run the following cell against a Python kernel:
```
from IPython.display import display

display({
    "application/vnd.myjson+json": {
        "$schema": "https://vega.github.io/schema/vega-lite/v3.json",
        "description": "A simple bar chart with embedded data.",
        "data": {
            "values": [
                {"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
                {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
                {"a": "G", "b": 19}, {"a": "H", "b": 87}, {"a": "I", "b": 52}
            ]
        },
        "mark": "bar",
        "encoding": {
            "x": {"field": "a", "type": "ordinal"},
            "y": {"field": "b", "type": "quantitative"}
        }
    },
    "application/javascript": "console.log(1234)"
}, raw=True)
```
4. The above code will generate 1 output with two mime types, the first is not supported as there's no renderer.
5. Debug the extension and run the same cell and you'll see that rendering doesn't work for the custom mime type, therre's a weird error in the renderer picker about the renderer not being supported
6. Modiry the `package.json` in the renderer extenion to remove the following section
```
                "requiresMessaging": "optional",
                "dependencies": [
                    "vscode.builtin-renderer"
                ]
```
6. Re-run the same cell again, and it works now

**Comment by mjbvz** [comment]
`dependencies` is a list of kernel dependencies (scripts from preloads). We do not support listing another renderer as a dependency this way

After I remove the `dependencies` section, I see this working as expected. You can also still require `vscode.builtin-renderer` by calling `getRenderer` inside of your custom renderer

---

I'm going to close as by-design. We can revisit if there is a good use case for this type of dependency between output renderers
