### ISSUE TITLE
Files not opening for a repo when using 'code <repo-name>' from terminal

### ISSUE THREAD

**Issue by trishalanaman** [microsoft/vscode#160710]
Clone a new repo and open it from the terminal. If a file is opened once from the VS code search, terminal cmd works fine but for new repo, it's not able to launch successfully.

https://user-images.githubusercontent.com/47503078/189697115-79429382-84fc-4c74-b4f8-8d4231d4fc93.mp4

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by trishalanaman** [comment]
Sure, will check this on weekend.

**Comment by bpasero** [comment]
👍
