### ISSUE TITLE
i'm unable to change the colour of address bar

### ISSUE THREAD

**Issue by mhimanshum** [microsoft/vscode#160707]
Type: <b>Feature Request</b>

please tell me hoiw i change the colour of address bar and title bar

VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by meganrogge** [comment]
they'll be one of the `workbench.colorCustomizations`
