### ISSUE TITLE
Show base in merge editor result view with decoration hint

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#160832]
Instead of showing conflict markers when neither side is accepted, we could show whatever was in base and then use something similar to our conflict markers to indicate that the code is from neither side.

<img width="652" alt="CleanShot 2022-09-13 at 11 11 38@2x" src="https://user-images.githubusercontent.com/25163139/189978553-fcce2556-139b-4cc9-9d06-33e2f8322ac6.png">

cc @isidorn @hediet

**Comment by isidorn** [comment]
I agree that we should have some UI decoration to clarify to the user that what we are showing is Base. This might be the right solution, but my feeling is that we need something less "in your way". So something that should just be an UI decoration, and not real text in the editor.

**Comment by daviddossett** [comment]
This may be handled differently if we end up moving to a model where you can explicitly accept from base e.g.

<img width="365" alt="CleanShot 2022-09-19 at 11 40 31@2x" src="https://user-images.githubusercontent.com/25163139/191091486-bdfda73f-93fb-4de3-85d4-274d289459a5.png">

Will follow up on this in #160829

**Comment by daviddossett** [comment]
Closing since we indicate this in the result pane now.
