### ISSUE TITLE
there is issue in the top of design 

### ISSUE THREAD

**Issue by mahamad901** [microsoft/vscode#160846]
in the top of visual studio the button of close the program is up the file list inside of section and view

**Comment by gjsjohnmurray** [comment]
Hard to tell from your description, and you didn't give version or platform information, but maybe what you're seeing is https://github.com/microsoft/vscode/issues/159813#issuecomment-1234863008

**Comment by rzhao271** [comment]
Closing as a duplicate of #159813

**Comment by mahamad901** [comment]
> Hard to tell from your description, and you didn't give version or platform information, but maybe what you're seeing is [#159813 (comment)](https://github.com/microsoft/vscode/issues/159813#issuecomment-1234863008)

thank you very much that the solve of problem
