### ISSUE TITLE
I can't use the letter M

### ISSUE THREAD

**Issue by MitkoVtori** [microsoft/vscode#160881]
Type: <b>Bug</b>

Hi, I am triyng to use Visual Stuido code for html & css projects, but In the whole program I can't use the letter M. how can I fix that?

VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.93GB (2.85GB free)|
|Process Argv|--crash-reporter-id 37e14e25-0132-4f1a-ad94-5342e3259258|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
html-extentions-pack|bou|0.3.0
vscode-html-css|ecm|1.13.1
minify|Hoo|0.4.3
svg|joc|1.4.19
HTMLHint|mka|0.10.0
vscode-attrs-sorter|mrm|2.1.0
vscode-doiuse|mrm|1.6.0
vscode-scss|mrm|0.10.0
vscode-css-peek|pra|4.2.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.

**Comment by MitkoVtori** [comment]
I don't understand what should I do. There is so much information.

**Comment by MitkoVtori** [comment]
> Please use the advice at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.

I didn't find how to fix my issue

**Comment by gjsjohnmurray** [comment]
Did you do this?

https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting

What gets reported when you press the N key?
