### ISSUE TITLE
Support `tsc` (TypeScript compiler) output format for file links in terminal

### ISSUE THREAD

**Issue by davidpcaldwell** [microsoft/vscode#160895]
VSCode supports clicking file paths referenced in the terminal, optionally including line numbers and column indices, and jumping to the referenced file at the given position.

See, e.g., https://github.com/microsoft/vscode/issues/156439.

However, it does not understand the `tsc` output format:
```
path/to/file(4,1): some error message
```
... where `4` above is the line number, and `1` is a column offset.

Clearly it understands this in a problem matcher somewhere as the integration with `tsc` at edit time is working. It'd be nice to also understand it in the terminal, for times when `tsc` is run from there.

**Comment by Tyriar** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? Let us know if not.
