### ISSUE TITLE
Mac: No keyboard shortcut for opening the current file in Explorer

### ISSUE THREAD

**Issue by kgrossjo** [Microsoft/vscode#16080]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra 10.12.1

There does not seem to be a keyboard shortcut for opening the currently selected file in Explorer.  If I hit `Return` then I can rename the file.  If I hit `Ctrl-Return` then the file is opened to the side.  If I hit `Space` nothing useful seems to happen.  If I hit `Command-O` then a file chooser window opens.

Steps to Reproduce:

1. Open a project in VSCode.
2. Hit Command-Shift-E to focus the Explorer
3. Use the cursor keys to navigate to a file, say `foo.js`.
4. Try to open that file by hitting some key.  I tried `Return` (renames), `Ctrl-Return` (opens in another column, it's not what I want), `Space` (does nothing), `Command-O` (opens a window that allows me to choose a file, and the default is not connected to the file I've selected.

Of course, double-clicking works.  But I'm a keyboard junkie.

**Comment by bpasero** [comment]
@kgrossjo `Cmd+Down`

**Comment by kgrossjo** [comment]
Thank you @bpasero. Should I now open another ticket to have this documented?  It doesn't show up when editing the keyboard shortcuts.  It isn't mentioned on the documentation site.  There is no command that I can run with `f1`...
