### ISSUE TITLE
Auto load last file

### ISSUE THREAD

**Issue by tkggusraqk** [Microsoft/vscode#16089]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. open vscode ,auto load last edit file
2.

**Comment by jrieken** [comment]
hot exit?

**Comment by bpasero** [comment]
@tkggusraqk can you share more details please?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
