### ISSUE TITLE
Disable `javascript.validate.enable` per-file/folder

### ISSUE THREAD

**Issue by ChadBailey** [microsoft/vscode#160865]
I would like these two tightly-coupled changes:

1. Rename `javascript.validate.enable` to `javascript.validate.exclude`
2. Change the valid values for `javascript.validate.exclude` to be key value pair of `file_pattern:boolean`, mirroring the behavior of `files.exclude`.

Justification:
Popular test framework Jest requires usage of CommonJS modules out of the box. There is experimental support for ES modules, however, many users may prefer to use CommonJS style imports for their test code while allowing ES modules in their main codebase.

**Comment by mjbvz** [comment]
> Popular test framework Jest requires usage of CommonJS modules out of the box. There is experimental support for ES modules, however, many users may prefer to use CommonJS style imports for their test code while allowing ES modules in their main codebase.

Can you please explain how that is related to the validate setting

**Comment by ChadBailey** [comment]
javascript.validate.enable controls linter style suggestions to convert CommonJS modules to ES modules. I want to be prompted of this, but only for some files.

**Comment by ChadBailey** [comment]
Update: edited my reply for more clarity. Sorry if I've caused any confusion

**Comment by mjbvz** [comment]
If your goal is hiding that suggestion, disabling `validate` seems like a quite extreme solution as it will turn off all error reporting (including errors for basic syntax issues)

I suggest just disabling `javascript.suggestionActions.enabled` for now to hide it everything . https://github.com/microsoft/TypeScript/issues/28825 tracks letting you disable individual suggestions

**Comment by ChadBailey** [comment]
I appreciate your detailed response, thanks for including those extra details.

**Comment by mbhoward73** [comment]
I have another use case for this.  I'm using plop for project scaffolding with template files.  I have a templates folder within my project that has many template files with handlebars syntax mixed in in various places.  This causes all sorts of syntax validation errors.  It would be great if I could turn off validation just for my templates folder.
