### ISSUE TITLE
Extra empty lines at any documents top before line 1

### ISSUE THREAD

**Issue by devhiko** [microsoft/vscode#160848]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.1
- OS Version: Win11  V10.0.22000.918

Steps to Reproduce:

1. Open any file at vscode
2. Scroll to top most before line 1 and you can see these 
![error](https://user-images.githubusercontent.com/99843102/190012806-f903fcc4-d35e-4271-a5af-6b17f02826f1.png)

**Comment by gjsjohnmurray** [comment]
Try changing the `editor.find.addExtraSpaceOnTop` setting.

**Comment by devhiko** [comment]
thanks, man it works as of old times.
