### ISSUE TITLE
Terminal Tree - automatically organize terminals to a tree list by cwd

### ISSUE THREAD

**Issue by shmuelhizmi** [microsoft/vscode#160886]
Hey ✌️
I think a lot of developers often struggle to find their open terminals
the tabbed terminals feature helps a lot in that regard but still, it requires memorizing how you ordered your tabs and the manual work of organizing them. I think adding a way to display your terminals in a tree by their CWD could be a great solution.
maybe with a button toggle similar to how you can do with git files.

there may be some technical problems with extracting a correct CWD from a process that isn't a shell (some running executables can sometimes change it rapidly while running operations), so maybe limiting it to the last CWD provided from a shell could be a better product.

any thoughts?

![Screen Shot 2022-09-14 at 11 17 49](https://user-images.githubusercontent.com/48323313/190100062-b0095ae2-5a70-453d-ad34-59f5ea49444c.png)
![Screen Shot 2022-09-14 at 11 27 31](https://user-images.githubusercontent.com/48323313/190102512-2211acd3-dab3-49c4-963f-67d27cb2d6a2.png)

**Comment by meganrogge** [comment]
thanks for the issue. a concern i'd have with a toggle to show them by cwd is we'd have to decide how to deal w terminal groups that contain terminals in different cwds. I also don't think most users have enough terminals open for a sorting mechanism to be warranted.

**Comment by Tyriar** [comment]
Any terminals not in the root workspace folder should show their working directory in the tab (shell integration is required on Windows for this):

![image](https://user-images.githubusercontent.com/2193314/190412541-a9446d94-9977-4215-bcf8-6174997e0c2e.png)

You can also tweak it to show the full path by using this setting for example:

```json
"terminal.integrated.tabs.description": "${task}${separator}${local}${separator}${cwd}"
```

![image](https://user-images.githubusercontent.com/2193314/190412680-7d1ca991-5ecb-42c6-99c8-0ded2c151be4.png)

You can also rename and set an icon and color for terminals to help ID them:

![image](https://user-images.githubusercontent.com/2193314/190413000-1b28017b-640f-49d3-b6a0-211dc8fa5808.png)

Can you give an example of your terminal when you're in a state like this where you find the tabs unorganized?

**Comment by shmuelhizmi** [comment]
@Tyriar your suggestion is great, I do think there could be an additional value in being able to view it in a tree form, especially in big mono repos/ workspaces. I know my team struggles with that a lot

is there a way to only show the cwd active dir name using your method? it think this could help a lot my specific problem where I have a mono repo with lots of similar scripts in different projects.

**Comment by meganrogge** [comment]
can you pls provide a screenshot? would help us understand your issue better.
