### ISSUE TITLE
vscode doesn't honor files.watcherExclude

### ISSUE THREAD

**Issue by gudvinr** [Microsoft/vscode#16086]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04.1

Steps to Reproduce:

1. Set up (or leave default) `files.watcherExclude` object.
2. Open code (html/js/css project) for the first time and it starts linting at least css and json files inside node_modules and other excluded dirs.

![image](https://cloud.githubusercontent.com/assets/1712806/20649874/f6621e94-b4d9-11e6-8a54-66b20e248960.png)

**Comment by bpasero** [comment]
This setting is for excluding files from watching, I doubt it has any impact on linting, but I defer to @aeschli to comment on that.

**Comment by aeschli** [comment]
CSS/HTML validate only files that are opened in an editor.

From the name of the `files.watcherExclude` setting it is IMO clear that this only impacts the file watcher. No restriction on what files can be opened or are potentially read by language services.
