### ISSUE TITLE
keep getting prompted to install command tools whenever open vs code

### ISSUE THREAD

**Issue by simkimsia** [microsoft/vscode#160872]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:
Version: 1.71.1
Commit: e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb
Date: 2022-09-08T19:41:58.611Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
- OS Version:
mac OS 12.6

Steps to Reproduce:

1. open visual studio code
2. get prompted to download git and command tools

see image here https://twitter.com/KimStacks/status/1569924839888257030

insiders also has this issue

I have already tried installing the command tools but the situation recurs

Here's the loom to show how i reproduce the issue. https://www.loom.com/share/caffc2e635794ce893ad364f80fb4e5f

Situation seems to occur after i upgraded macOS.

**Comment by lszomoru** [comment]
@simkimsia, could you try doing the following:
- Close all instances of VS Code
- run `sudo xcodebuild -license` to accept the license agreement
- run `xcodebuild -runFirstLaunch` to install the tools

**Comment by simkimsia** [comment]
Thank you, i got it to work. I have a different issue now.
