### ISSUE TITLE
Support opening multiple panels of the same extension

### ISSUE THREAD

**Issue by gcampbell-msft** [microsoft/vscode#160838]
I'm working on an extension where I'd like to be able to open multiple "windows" of my extension. Is there support for this? Or a suggested way to implement this? 

I'm working on the [Serial Monitor extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-serial-monitor) and would like to support the ability for users to monitor multiple ports at the same time without having to open multiple instances of VSCode. 

Thanks!

**Comment by alexr00** [comment]
What do you mean by "windows"?

**Comment by gcampbell-msft** [comment]
@alexr00 I guess a better word would be "views" or "tabs". The idea being that I'd have multiple instances of the extension open. 

This is the Serial Monitor extension: 
![image](https://user-images.githubusercontent.com/86264750/190160847-6906a4b6-bc11-4c81-adfc-626067719b02.png)

And the idea would be that we'd support opening a second tab of this Serial Monitor so that someone could monitor two ports at the same time, within the same VS Code instance.

**Comment by alexr00** [comment]
@gcampbell-msft, yes, we call those views. Looks like you're specifically using webviewViews. You can have as many of those as you want, you just need to give each one a different ID. This does mean that you'll need to pre-define these views in your package.json, but you can use the `when` clause to ensure that they're hidden until you want them to be visible.
