### ISSUE TITLE
Commit button not showing up for remote repos

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#160810]
I keep having a moment of cognitive dissonance when the Commit button doesn't appear in some of my repos. It seems to boil down to being in a remote repo.

Left side is a local git folder, right side is a remote repo. Even with changed files, the button doesn't appear:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/8599/189931948-2b05e9b2-7c3a-4f7e-aa7a-0d956eb9f3d1.png">

**Comment by lszomoru** [comment]
@digitarald, could we set up some time tomorrow so that I can take a look? Thanks!

**Comment by lszomoru** [comment]
This has been addressed as currently the "Commit" action button was added to remote repositories.
