### ISSUE TITLE
Clicking on a 'problem' item will re open an already open file if there are multiple groups,

### ISSUE THREAD

**Issue by SantiSuarezMS** [microsoft/vscode#160808]
When you click on an item on the `Problems` tab, instead of searching if there is an already open tab on the groups to focus on it, VSCode will open the same file on the focused group.

- VS Code Version: 1.71.0
- OS Version: Darwin x64 21.6.0

Steps to Reproduce:

1. Open at least two groups of tabs with three files, for the sake of clarity I'll use `foo.json` to be open on **group one** and `bar.json` & `baz.json` on **group two**.
2. Introduce an error on `bar,json` so it is shown on the `Problems` tab (i.e. delete a bracket so it is not a valid JSON anymore).
3. On **group two** focus on the file that have no errors (in our example, `baz.json`), so that tab is visible, and then move the focus to `foo.json` on **group one**.
4. Click on the problem reported on the problems tab.

Expected result: The focus will move to **group two**, on the `bar.json` tab.
Actual result: The focus remains on **group one** and open a new tab with `bar.json`

Screencast: https://user-images.githubusercontent.com/106551401/189924654-5ce08e60-3386-4fa2-b574-41d50075d6a6.mov

This is inconsistent with other cases I've tried, where it always moves the focus to the already open tab (i.e. when you have the focus on another tab of the same group where the error is, or when you're in a different group but the tab with the error is visible on the other group).

**Comment by sandy081** [comment]
It's a common behaviour across all our trees (eg: Explorer, Search), to reveal the existing editor when clicking on a file. 

> This is inconsistent with other cases I've tried

What are the other cases you mean?

PS: I cannot open the screencast.

**Comment by sandy081** [comment]
Can you please upload the gif in the comment here in GitHub. The other link requires me to have an account

**Comment by sandy081** [comment]
> The third case is the one that seems inconsistent, I'd expect that instead of opening a new tab on the group with the same file (already open on another group), the focus just shift to the group where a tab with the file is already open and get the focus on that tab. Does that makes sense?

This is working as you explained as expected - the file is revealed if it is already opened. 
https://user-images.githubusercontent.com/10746682/190455940-ed6f250d-8227-4b02-af45-1924ba12485e.mp4

**Comment by SantiSuarezMS** [comment]
Tinkering around I found a setting called **Reveal if Open** that was disabled, enabling it fixed the issue for me. Thanks for your time and patience!
