### ISSUE TITLE
New code action widget does not respect my current theme

### ISSUE THREAD

**Issue by chriszrc** [microsoft/vscode#160812]
The new code action control ui (https://code.visualstudio.com/updates/v1_71#_new-code-action-control) is great in that it looks like it adds more flexibility with controls, but it does not appear to be respecting my current theme. 

First, here's the old design:

<img width="457" alt="Screen Shot 2022-09-13 at 11 17 18 AM" src="https://user-images.githubusercontent.com/25695785/189935339-67529e9e-74bb-4e5d-aef3-ad865972f0ad.png">

Looks pretty decent with the other dark colors. Now the new design:

<img width="485" alt="Screen Shot 2022-09-13 at 11 56 15 AM" src="https://user-images.githubusercontent.com/25695785/189935459-b16473c7-4cc9-4f21-9e99-ace005ff6a35.png">

It's glaring out of my screen :'( . Here's more what I would expect (by applying some custom css):

<img width="514" alt="Screen Shot 2022-09-13 at 11 58 38 AM" src="https://user-images.githubusercontent.com/25695785/189935936-66a0152c-246b-487a-a4e3-fe38166a0a89.png">

**Comment by mjbvz** [comment]
These colors are currently controlled by `menu.background`. However we should use `editorWidget.background"` instead to be consistent with other widgets
