### ISSUE TITLE
Disable auto scroll when searching

### ISSUE THREAD

**Issue by andreyc0d3r** [microsoft/vscode#160868]
Hello,

I googled around and didn't find an answer.

I was wondering if it is possible to disable auto scroll when typing a search query or submitting a search using the search within the file.

It a bit of problem when I'm looking at a very long file. Currently I'm working on a function few hundred lines of code, I need to find a variable within that function.

Every time I type in a search window, I'm being taken away from the function to anywhere on the page.

I just need the word hight lighted without the autoscrolling. I get lost every-time this happens.

I"m debugging someone else's code, so I'm not familiar with the file, so the scrolling is a big issue, very frustrating

**Comment by roblourens** [comment]
I think you want `"editor.find.cursorMoveOnType": false`
