### ISSUE TITLE
August 2022 Recovery 2 Endgame

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#160943]
- [X] Create a milestone `August 2022 Recovery 2` @mjbvz
- [X] Bump the version number @mjbvz
- [X] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22August+2022+Recovery+2%22)
- [X] Assign candidate issues to the recovery milestone **team**
- [X] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [X] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [X] Initiate `insiders` build from `main`
- [X] Issues are tested in the `insiders` **team**
- [X] Build `stable` for all platforms from release branch @mjbvz
- [x] Issues are verified on `stable` build and the `verified` label is added @mjbvz
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch @mjbvz
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit @hediet 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit @hediet 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
  - [x] Windows ARM64 @sandy081 
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal @mjbvz
    - [x] Intel @mjbvz
    - [x] Intel server @mjbvz
    - [x] Apple Silicon @jrieken 
  - [x] Linux x64 @aeschli 
    - [x] deb
    - [x] rpm
    - [x] archives
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`)
  - [x] Linux server @chrmarti 
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
- [x] Publish website **@gregvanl**
- [x] Publish stable build @mjbvz
- [x] Create an official release @mjbvz
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) @mjbvz

**Comment by albertosantini** [comment]
Just to say I cannot find "August 2022 Recovery 1 Endgame" issue and "August 2022 Recovery 2 Endgame" is not pinned.
Maybe I am wrong but it was usual pinning this kind of issue beside the iteration one.

**Comment by mjbvz** [comment]
1.71.2 has shipped
