### ISSUE TITLE
Scroll position changes on formatOnSave

### ISSUE THREAD

**Issue by jacekkopecky** [microsoft/vscode#160934]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: current main branch
- OS Version: MacOS 12.15.1

Steps to Reproduce:

1. Type some code in a code editor with formatting-on-save set up, e.g. with Prettier
2. Enter changes that will be reformatted into more lines of code, such as
   ```js
   { console.log();
   }
   ```
3. Position the cursor under these changes
4. Save
5. Observe how the cursor shifts

This is what it looks like:

![cursor disappears on format](https://user-images.githubusercontent.com/807315/190246919-b873e620-d69e-4e11-8ce2-0d40fda06d60.gif)

It's not common but it happens that there are enough changes above the cursor that a save moves the cursor off the screen like this.

I would prefer the cursor to stay put like this:

![cursor stays put on format](https://user-images.githubusercontent.com/807315/190246974-8b0215dd-e7b4-4009-b550-001525b6621a.gif)

An explicit format at least moves the cursor to the center of the screen if it disappears, but format-on-save doesn't. 

I think the current line should stay put instead of moving off the screen or to the middle of the screen.

I have the beginning of the fix ready (seen in action in the second gif) and I'd be happy to submit a PR.

**Comment by jrieken** [comment]
> Enter changes that will be reformatted into more lines of code, such as

@jacekkopecky Can you please provide the full contents here? I doubt it will reproduce with 3 lines of code and your recording show that you have much more content

Also, please try this with the built-in TS formatter extension. Asking because not all formatter compute minimal formatting edits, they often instruct us to replace the whole file content and in those situations it is harder to preserve state

**Comment by jacekkopecky** [comment]
@jrieken here's the file I used in the animations; it's just some placeholder code, not natural but it illustrates how the problem happens. If your window is big, you can duplicate the "b" lines.

```js
console.log('hi');
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
{ b;
}
console.log(foo);

function someMoreCodeHere() {
    console.log('here');
    const first = 3;
    const last = 7;
    for (let i = first; i <= last; i += 1) {
        console.log(i);
    }
}
```

I've tried it with the `.ts` file extension, I hope that runs the built-in TS formatter as you suggested, @jrieken . It behaves the same.

**Comment by jrieken** [comment]
@jacekkopecky thanks for the extra info. I can reproduce, tho the cursor stays stable but the scroll position changes (and hides the cursor)

**Comment by jacekkopecky** [comment]
@jrieken yes exactly; the editor does a good job in my experience of keeping the cursor in the right place in the text, but not on the screen. Thanks for clarifying the issue title.

If you like, I can propose a PR that would fix it; I'm thinking something like this:

- if the file fits on the screen after the format, scroll so that the whole file is visible; else
- if the cursor is off the screen before the format, or if the formatting doesn't add or remove lines above the cursor position, I wouldn't touch the scroll position of the editor, so the same line number is visible at the top; else
- if the cursor is on the screen before the format and formatting adds lines above the cursor:
  * if before the formatting there is any content above the screen (the first line of text is not visible); or if the cursor would disappear off the screen after the formatting, **preserve cursor position on screen(*)** 
- if the cursor is on the screen before the format and formatting removes lines above the cursor:
  * if after the formatting there is any content above the screen (the first line of text is not visible); or if the cursor would disappear off the screen after the formatting, **preserve cursor position on screen(*)**
 
(*) Preserving cursor position on screen means the editor would change the window's scroll position so the cursor stays put relative to the visible screen and lines are added or removed above the screen.

It's a lot of special cases, but I believe it describes natural expected behaviour.

I would also propose to implement the same behaviour for explicit formatting, not only for format-on-save.

What do you think?

**Comment by jrieken** [comment]
For suggestions we do something similar, accepting one can cause edits on lines above and we don't want the scroll position to change. We solve that by capturing the scroll state and by [restoring that after making](https://github.com/microsoft/vscode/blob/f3f9f7a10d877fd2177daec3e1f6054706c7e5bc/src/vs/editor/contrib/suggest/browser/suggestController.ts#L322) the edits...

The challenge with format-on-save (and other save participants) is that they must not have an editor attached to them (you can save documents with editors) and that the [logic that invokes](https://github.com/microsoft/vscode/blob/559e9beea981b47ffd76d90158ccccafef663324/src/vs/workbench/services/textfile/common/textFileSaveParticipant.ts#L52) format-on-save doesn't really know about editors and scroll states.

Maybe @bpasero can help to make this simpler

Good news (or debt) is that some save participants already check if they run with an editor or not. Formatting is one of them and the scroll-state persisting could be done for it (at the potential conflict cost of other participants doing something else)

> I would also propose to implement the same behaviour for explicit formatting, not only for format-on-save.

That makes sense - all formatting should be using [`formatDocumentWithProvider`](https://github.com/microsoft/vscode/blob/fe5f1aef61160d49b6bc97f34c430aa020c6d789/src/vs/editor/contrib/format/browser/format.ts#L306) or `formatDocumentRangesWithProvider` (same file)
