### ISSUE TITLE
Test extension debugging in a clean environment

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#160905]
Refs: #159572

- [x] macOS @rzhao271
- [x] windows @hediet
- [x] linux @andreamah

Complexity: 2

Authors: @weinand, @sandy081 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23160905%0A%0A&assignees=weinand,sandy081)

---

When debugging an extension, there was always the problem that the extension was running in the development environment (user settings and installed extensions) of the author of the extension and not in an environment that was more appropriate for the target user of the extension.

With the recently introduced "profiles" feature it is now possible to run the extension under development in a different environment by specifying a profile in the extension's debug configuration.

Two scenarios are supported:
- "debugging in a clean environment" by using an unnamed "empty" profile that gets automatically deleted when extension debugging has stopped.
- "debugging in a controlled environment" by using a named profile that has been created specifically for the extension under development, and that contains specific user settings and extensions.

This debug configuration shows how to "debug in a clean environment":
```json
{
    "name": "Extension",
    "type": "extensionHost",
    "request": "launch",
    "args": [
        "--profile-temp",
        "--extensionDevelopmentPath=${workspaceFolder}"
    ],
    "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
    ],
    "preLaunchTask": "npm: watch"
}
```

And here is a debug configuration for "debugging in a controlled environment" that uses a previously created profile named "extensionContext":
```json
{
    "name": "Extension",
    "type": "extensionHost",
    "request": "launch",
    "args": [
        "--profile=extensionContext",
        "--extensionDevelopmentPath=${workspaceFolder}"
    ],
    "outFiles": [
        "${workspaceFolder}/dist/**/*.js"
    ],
    "preLaunchTask": "npm: watch"
}
```

Known limitation:
when debugging an extension in a remote location (via the "Remote Development" extensions "Containers", "SSL", or "WSL"), using the `--profile-temp` flag will result in this status message:

![2022-09-08_11-46-47](https://user-images.githubusercontent.com/1898161/189095058-404ac789-43c1-4660-8749-f524b5953443.png)

This is expected because the temporary profile does not include any extensions, which means that the "Remote Development" extensions are missing too. For remote scenarios it is recommended to create an empty named profile, add the "Remote Development" extensions to it, and then use the `--profile=....` command line option.

---

Please verify for your favourite extension...

- that the "--profile-temp" and "--profile=<profile name>" command lines flags work for the two scenarios from above.
- that the "--profile=<profile name>" flag works in a **remote setup** of your choice (SSH, WSL, Container).

**Comment by hediet** [comment]
Nice work! Maybe the sample extensions should be updated to use this.

**Comment by rzhao271** [comment]
This is a pretty cool use of profiles :tada:
