### ISSUE TITLE
High CPU usage by `rg` bundled in VSCode

### ISSUE THREAD

**Issue by imWildCat** [microsoft/vscode#160927]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
```

Version: 1.71.1
Commit: e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb
Date: 2022-09-08T19:41:58.611Z (5 days ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
```
- OS Version: macOS 12.6 (21G115)

Steps to Reproduce:

1. Do some search in a large git project 
2. You may see high CPU usage of `rg` in the background, blocking other processes

I saw this issue extremely frequently while using both M1 Max MacBook Pro.

**Comment by roblourens** [comment]
rg is the search tool that we use in vscode. When you search a large project, you will probably see it using high cpu. But there are some tips for search perf on this page: https://github.com/microsoft/vscode/wiki/Search-Issues

**Comment by imWildCat** [comment]
@roblourens Sorry, I should be clear: 

Even if I'm not searching inside the project/workspace, there can be `rg` running in the background with high CPU usage.

**Comment by roblourens** [comment]
Previously you said "step 1, do a search", if the search is not necessary, then what triggers it?

Something is doing a search. Maybe it's an extension. No way I can answer this without more detail. https://github.com/microsoft/vscode/wiki/Search-Issues might help
