### ISSUE TITLE
autocomplete when cursor not at end of word causes incorrect completetion

### ISSUE THREAD

**Issue by davidnormo** [microsoft/vscode#160971]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.71.0 (Universal)
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:25:38.437Z (2 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No

Steps to Reproduce:

1. Start typing something you know can be autocompleted
2. If autocomplete popup opens automatically close it by hitting esc
3. Open autocomplete (for me that's ctrl + space)
4. Left arrow a couple of characters so the cursor is not at the end of the word
5. Choose one of the autocomplete suggestions

Expected: Entire word is replaced with selected suggestion
Actual: Characters left of the cursor are replaced and the right side is kept - the result is incorrect 
e.g. `fo|o` -> `fooBaro` instead of `fooBar`
(The pipe above indicates the cursor position when using autocomplete)

![vscode-autocomplete-error](https://user-images.githubusercontent.com/881849/190355461-08f158de-2c52-43dd-8468-72e3f8e22179.gif)

This may not be a bug (perhaps some people desire this behaviour?) but because it results in some incorrect code (and it's a bit annoying) I decided to raise a bug. I can reproduce it consistently but in real world use it happens infrequently.

Thanks for your help!

**Comment by jrieken** [comment]
Suggest usually supports insert and replace mode. The default be configured with `editor.suggest.insertMode` and the "alternative" variant is available via `Shift+Tab`, so `Tab` does insert and `Shift+Tab` does replace

**Comment by davidnormo** [comment]
@jrieken thanks - that works great, didn't know that existed!
