### ISSUE TITLE
Built in AMD module does not seem to work correctly in notebook renderer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#160965]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: All (stable and insiders)
- OS Version: Mac

Steps to Reproduce:

1. Install Jupyter extension
2. Install Python and `plotly` into the python environment
    * To do this easily in non-conda environment, just open a Jupyter notebook, select a Python environment and run a cell
    * Once a cell runs successfully then install plotly using the following code in a separate cell `pip install plotly`
4. Open a new notebook
5. Run the following code in a cell
```python
import plotly.express as px

fig = px.scatter(x=[0,1,2,3,4],y=[2,4,7,2,7])
fig.show(renderer='notebook')
```
6. Confirm a plot is displayed
7. Reload VS  Code, and you'll notice the plot is no longer displayed.
Do note that the output in the cell is plain HTML + JavaScript.
8. Now insert a cell above the current cell (i.e. ensure the follwoing code is added to a cell at the top of the notebook)
```python
from IPython.display import display
import requests
response = requests.get("https://requirejs.org/docs/release/2.3.6/comments/require.js")

display({"text/html": f'<script type="text/javascript">console.log("Loading custom require.js");(function(){{\nrequire=requirejs=define=undefined;\n{response.text}\nwindow.require=window.requirejs=requirejs; window.define=define;}})(window);\nrequire=requirejs;</script>'}, raw=True)
```
9. Run the above cell.
10. THis will merely download and inject `require.js` as a replacement for the built in AMD, we also redefine the variables `require, define and requirejs` to point to the values from `require.js`
11. Now reload VS Code and open the above notebook
You'll see the plot is now displayed.
I found that `require.undef` is not defined in the built in version of `require`, however even if i were to add a dummy function for `require.undef = function() {}`, that doesn't work.

I found that the code `define('plotly', function(require, exports, module) {` doesn't work as expected. Because immediately after that code we have `require(['plotly'` and that prints and error. I.e. `define` doesn't work as expected. You can see these errors in the console window (the code `define('plotly'` is generated by the Python package and can be found in the output html text.

**Solutions**
* Jupyter extension could load `require.js` and redefine the current global variables `require` and `define` with that of `require.js` within the renderers as well. 
    * This is already something we do today, (when running a cell)
    * Hence doing this for renderers is not an issue as well, and that's what I'll be doing to unblock the issues in Jupyter for now.

**Problem**
* I don't think this is a good long term solution, I.e. i don't think we should be using `require.js` instead of the built-in `require` module shipped by VS Code in the webviews.

@mjbvz @alexdima /cc

Note: After you uninstall/disable the Jupyter extension, you can still see the problem with plots not being rendered, and after the hacky loading of require.js that notebook works in VS Code (even without Jupyter extension).

**Comment by mjbvz** [comment]
@DonJayamanne Thanks for the investigation!

Jupyter is the only consumer of the built-in require.js that we include in the notebook webviews. I've been in favor of requiring that Jupyter bring its own require.js for a long time, but removing this has caused issues in the past: https://github.com/microsoft/vscode/commit/207fece665ed12ac93094ff59a5623dae0c7e6bd

Is switching to Jupyter's version of require.js sometime we can explore again?

**Comment by DonJayamanne** [comment]
> a long time, but removing this has caused issues in the past: https://github.com/microsoft/vscode/commit/207fece665ed12ac93094ff59a5623dae0c7e6bd

Don't remember why we needed this. Its possible it was required for some HTML outputs, will check with @IanMatthewHuff .

> switching to Jupyter's version of require.js something we can explore again?

Definitely possible.

**Comment by DonJayamanne** [comment]
Ok, got it, looks like we wanted `require` for HTML outputs and thats why we reverted the change.
And with this issue (#160965) we find that the built-in `require` isn't sufficient and we need to bring our own `require.js`
I think the solution is exactly what you suggested, Jupyter extension brings its own `require.js`.

For this to be possible we need a hook into the existing renderers like HTML and JS and others to be able to load `require.js`.
We can do this today with JS renderers via the new hook you added, and similarly do the same for other mime types like widgets, vega, plotly as we have custom renderers.
However for HTML we don't have an API to inject require.js.

We could optionally add an API hook for that as well, but I think we need a more generic solution, e.g. `for all Ipynb files ensure require.js is always loaded into the webview regardless of the mime type)
I believe that's what you've proposed here https://github.com/microsoft/vscode/issues/132557#issuecomment-933790945

**Comment by DonJayamanne** [comment]
Changing the assignment of the issue to @mjbvz and @DonJayamanne as the solution is to just use `require.js` instead of the vscodes version.

**Comment by DonJayamanne** [comment]
I think this is what we need
```jsonc
 "contributes": {
    "notebookRenderer": [
      { 
        "notebook": "jupyter-notebook", // Notebook view type that we want this to apply to. Not sure we'd want this to be empty, we'd have to be explicit.
         "type": "preload",   
        "id": "addGlobals",
        "path":"./notebook-out/index.js",
      }
   ]
}
```

This would work very well for Jupyter notebooks, as we load `requrie.js` and `jquery` in the controller today for the outputs. This would be a generic solution that would work when running cells and also opening existing notebooks.

**Comment by DonJayamanne** [comment]
@mjbvz Ran into another problem with the built in require.
When trying out `scenepic` package, there seems to be more issues with the built-in require.
I've tried removing the code that injects the built-in require and found that after we remove that things work as expected.

https://github.com/microsoft/vscode-jupyter/issues/11366

I.e. more reason to possibly remove the built-in require implementation from notebook webviews.

**Comment by mjbvz** [comment]
@DonJayamanne Should we try coordinating the switch to `require.js` again? I can make the VS Code changes if you can handle making the changes in the Jupyter extension

**Comment by DonJayamanne** [comment]
> you can handle making the changes in the Jupyter extension

sure thing. let me know when. 
though i think we'll need a new api for html (& others) renderers to preload requirejs.l (when opening existing notebooks).
not a problem when running a cell, as jupyter loads them via controller scripts. 

perhaps via an api, something like what your described earlier. 
fyi, we also need to load jquery as well.

**Comment by DonJayamanne** [comment]
Closing this issue as the Jupyter extesnion shipts its own AMD loader and vscodes AMD loader is not loaded into jupyter notebooks as a special case.
