### ISSUE TITLE
Word wrapping does not account for double width characters

### ISSUE THREAD

**Issue by Trebor-Huang** [microsoft/vscode#160978]
Type: <b>Bug</b>

- Set the word wrap feature on, wrapping at 40 characters. (This works even if lines wrap at viewport width, so the lines will actually wrap at double viewport width.)
- Enter, for example, some Chinese characters. Say repeat "这" multiple times in one line.
- It wraps at 40 Chinese characters, which is as wide as 80 characters in many monospace fonts, which is undesirable.

I see that such a bug may be difficult to fix in the `wordWrapColumn` mode, because fonts may not be monospaced. But when wrapping at viewport width, it would be unexpected and undesirable to not account for the actual width of a character.

VS Code version: Code 1.71.1 (Universal) (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:41:32.136Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 51bac6f0-a15a-4951-95ba-8e047d430bb5|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30567733

```

</details>

**Comment by alexdima** [comment]
Please try out `"editor.wrappingStrategy": "advanced"`:
```js
  // Controls the algorithm that computes wrapping points.
  //  - simple: Assumes that all characters are of the same width. This is a fast algorithm that works
  // correctly for monospace fonts and certain scripts (like Latin characters) where glyphs are of equal 
  // width.
  //  - advanced: Delegates wrapping points computation to the browser. This is a slow algorithm, 
  // that might cause freezes for large files, but it works correctly in all cases.
  "editor.wrappingStrategy": "simple"
```
