### ISSUE TITLE
JavaScript arrow ligature not working inside HTML script tags.

### ISSUE THREAD

**Issue by th3oth3rjak3** [microsoft/vscode#160906]
![image](https://user-images.githubusercontent.com/77807678/190196489-674cd234-c457-4500-854e-e93fdf9d2815.png)

I am using FiraCode iScript and have ligatures enabled in the VS Code settings. Inside of an HTML script tag, the javascript anonymous function arrow does not use the ligature. In the image above, you can see that the ligature is working outside of the script tag. 

Edit: I previously thought that the ligatures were working in .js files. They are also not working there.

**Comment by IllusionMH** [comment]
Are you sure you don't have ligatures disabled fir specific languages?
The would be inside of `"[javascript]"` object in `settings.json`

**Comment by th3oth3rjak3** [comment]
Unfortunately that's not the case. I did double check that just to be sure.

**Comment by th3oth3rjak3** [comment]
I just checked some italics settings that I had in my settings file and it turned out to be those. Not sure what changed over the course of the last update, but one of the items I had in there didn't have support for italics I guess.
