### ISSUE TITLE
codespace cs50 is always crashing

### ISSUE THREAD

**Issue by cunhamauro** [microsoft/vscode#160991]
codespace cs50 is always crashing, it disconnects and then attemps to reconnect but always fails and then asks me to reload window, I do so and then when I try to write something in the terminal it just freezes and repeats the same stuff... Cant do anything

Version: 1.71.1
Commit: e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by meganrogge** [comment]
pls create an issue in the codespaces repo about this
