### ISSUE TITLE
Opened dialog uses xWayland

### ISSUE THREAD

**Issue by pentamassiv** [microsoft/vscode#160969]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.71.0
Gnome shell on Arch Linux

Steps to Reproduce:

1. Open xeyes to easily check if the window uses Wayland
2. Open VS Code with the `--enable-features=UseOzonePlatform --ozone-platform=wayland --enable-features=WaylandWindowDecorations` flags set
3. Move cursor around on the VSCode window -> the eyes don't move so it is using Wayland
4. Click on "Files->Open Folder"
5. Move cursor on the opened dialog -> the eyes move so it is using XWayland

**Comment by GitThisBugOff** [comment]
Using my native file picker from KDE Plasma, I do not have this issue on 1.74.

**Comment by deepak1556** [comment]
@pentamassiv can you confirm if this issue persists with `1.74` ?

**Comment by pentamassiv** [comment]
I can confirm that with 1.74 it is fixed for me :)
Thank you very much
