### ISSUE TITLE
.git file/folder is hidden

### ISSUE THREAD

**Issue by kbumsik** [Microsoft/vscode#16093]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Build 14971 (Insider Program fast ring)

Hello, I am trying VS Code at this moment.
In overall, I think it is good enough to replace my Sublime 3!

But just one thing....it looks like VS Code hides .git configuration files. But I often manually change .git files directly. It is very annoying for me not able to locate .git files in VS Code. Is there any option to reveal .git files? If not please at least add an option for this...

Thank you so much.

**Comment by onlyongunz** [comment]
Go to settings > Preferences > Workspace Settings, you should be see a settings.json file on the screen now.
Add this line to the JSON file (i assume you know how it works):
```
    "files.exclude": {
        "**/.git": false,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true
    }
```

sometimes, when you type the `"file.ex` a suggestion appears for `file.exclude`. use it, and turn the rule `false` for `**/.git".

**Comment by kbumsik** [comment]
Oh I was looking for that kinds of option in `git.` section lol. Now it works like a charm thanks!
