### ISSUE TITLE
Input variables undefined when running Task with no Editor

### ISSUE THREAD

**Issue by nyqvistatwork** [microsoft/vscode#160990]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.1
- OS Version: Windows 11 21H2

Steps to Reproduce:

### %APPDATA%\Code\User\tasks.json
```JSON
{
    "version": "2.0.0",
    "tasks": [
      {
        "label": "Do something",
        "type": "shell",
        "command": "Powershell ${userHome}\\Code\\Tasks\\Task-Runner.ps1",
        "args": [
          "${input:something}"
        ],
        "problemMatcher": []
      }
    ],
    "inputs": [
      {
        "type": "pickString",
        "id": "something",
        "description": "What to do?",
        "options": [
          "New Code Extension",
        ],
        "default": "New Code Extension"
      }
    ]
}
```

1. Start with an "empty" instance of Code 

![image](https://user-images.githubusercontent.com/92366570/190407826-15e53823-954f-4d4f-a9ae-28eb1ce4f269.png)

File menu should have:

- No "Close folder"
- No "Close workspace"
- No "Close editor"

![image](https://user-images.githubusercontent.com/92366570/190413824-8ae251e8-02cf-4e7b-8d24-43f5aaa71be0.png)

2. Run task

![image](https://user-images.githubusercontent.com/92366570/190414470-4b7db8cb-bae1-4081-a41a-7fc801ac408c.png)

3. Input variable undefined

![image](https://user-images.githubusercontent.com/92366570/190414398-51a3485e-9b4d-4b2d-989c-dae2da846d9c.png)

If I open **any** folder or **any** workspace the problem solves.

**Comment by meganrogge** [comment]
what's your use case for running a task in a window w no folder open?

**Comment by nyqvistatwork** [comment]
My use case is:

- Starting vscode in a minimal environment to save time and resources.

- Clean environment to run tasks from. Independent of any folder.

I also don't find this behavior I explained expected.
