### ISSUE TITLE
Why VS CODE does not provide a history of search and replacement.

### ISSUE THREAD

**Issue by fudilove** [microsoft/vscode#160973]
Why VS CODE does not provide a history of search and replacement.
Because we often have to repeat the same search.
There are historical records. We can call them out immediately without having to re-enter them.

I know that Emediator has this function, which is very convenient.
Thank you.

**Comment by gjsjohnmurray** [comment]
It does. Simply press the <kbd>UpArrow</kbd> key when you are in the field.

**Comment by fudilove** [comment]
I've just seen it. It's already there.
However, it is inconvenient and needs to be searched one by one.
And only the search has a history, the search and replacement content should be paired together.

There should be a list (like this ∨)to quickly select what you need

**Comment by roblourens** [comment]
https://github.com/microsoft/debug-adapter-protocol/issues/146
