### ISSUE TITLE
Selection Dragging Scroll Speed

### ISSUE THREAD

**Issue by random-pixels** [microsoft/vscode#160931]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.1
- OS Version: Linux Mint 21 "Vanessa" x64

Steps to Reproduce:

1. Create a file in VS Code whose contents are about 5 viewports long (so that you have to scroll up and down to see the whole file)
2. Try to select some code that extends just past the viewport (maybe 3-5 lines past the end of the viewport window)
3. Screen rushes past at 1,000 miles an hour all the way to the bottom and it's impossible to select just the code that you need.

This bug is related to the following issue that was created as a feature request, opened since 2017 with no one assigned and no attention from developers. 
Selection Dragging Scroll Speed #40890

However, I and many others from that 5-year-old thread feel that this should not be a feature request. It's a true bug in the way VSCode works. I am hoping filing this bug report is the correct way to go about getting this extremely frustrating issue fixed.

Thanks!

**Comment by WarrenWeckesser** [comment]
I agree, it is a bug.  It probably makes more sense to remove the `feature-request` tag from https://github.com/microsoft/vscode/issues/40890 and add the tag `bug` to it, but if a new issue helps with the visibility of the issue, then +1!

**Comment by alexdima** [comment]
Done via #40890
