### ISSUE TITLE
CodeLens toggles on/off on each keystroke when attached to a blank line 

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#16097]
- VSCode Version: `1.8.0-insider (1.8.0-insider)` 0b847998d914ff84fd9c13b2972cc8803745c24d
- OS Version: macOS Sierra `10.12.1 (16B2555)`

Steps to Reproduce:

1. Open a file with the first line of the file blank
2. Use an extension ([GitLens](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens) works) that will add a CodeLens to the top of the file (i.e. to the blank line)
3. Start typing -- each keystroke will cause the CodeLens to disappear and reappear, but only this one CodeLens, any others will remain stable.

Can see animated gifs of the behavior here: https://github.com/eamodio/vscode-gitlens/issues/19

**Comment by jrieken** [comment]
I have updated our invalidation heuristic, which runs on type, to not remove empty decorations when the underlying code-lens uses an empty range. @eamodio This is fixed, but only for when decoration that aren't attached to a word are empty (start pos === end pos)

**Comment by eamodio** [comment]
@jrieken Excellent -- thank you! Looking forward to trying it out in tomorrow's build.
