### ISSUE TITLE
TextEditor 'revealRange' method forces focus in editor, but is lacking a 'preserveFocus' flag

### ISSUE THREAD

**Issue by boltex** [microsoft/vscode#160953]
My extension tries to do something similar to the search panel in vscode: showing results navigable with the keyboard arrows, showing a range in an editor. But the revealRange method seems to force the focus in the editor.

Unlike showTextDocument, which has a 'preserveFocus' flag, the TextEditor's **revealRange** method requires a range, a TextEditorRevealType, (which is a scrolling strategy for revealing), but strangely **no preserveFocus flag** to prevent the editor from taking focus.

This make it impossible to have an extension reveal a range in an editor, while preserving the focus where it was, for the user to continue using the keyboard in that original panel or view.

**Edit**: Just thought i'd also mention the fact that treeviews also have an option to reveal a node while preserving focus.

Thanks for considering this small, but useful parameter to the revealRange method!

**Comment by alexdima** [comment]
@boltex Looking at the implementation of `TextEditor.revealRange`, I don't see any calls to focus the editor. Can you please provide a simple extension sample demonstrating the problem?

**Comment by boltex** [comment]
Thanks @alexdima , I made a repo from a copy of the treeview sample test https://github.com/boltex/revealRangeTest that tests showing a text editor, setting a selections range, and also reveal that range... 

But you are right, it does not set the focus and preserves it without problem!

That means it was a bug in my extension all along that i did not spot...! Sorry to have filed an issue too fast!

( I hope that small test-repo might help someone else, as an example, who's looking in issues related to setting selection and set a visible range in a text editor via the API.) 

Many thanks for your great product and support.
