### ISSUE TITLE
Exclude a subdirectory from the explorer using exact path does not work

### ISSUE THREAD

**Issue by fvilers** [Microsoft/vscode#16090]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Create a directory `public` with a subdirectory `bundle`
2. Create a `settings.json` file under the `.vscode` directory
3. Add the following json to the `settings.json` file
```
{
  "files.exclude": {
    "public/bundle": true
  }
}
```
4. The bundle directory is still visible

Note that using `"public/*bundle": true`, or `"public/bundle*": true` or `"public/**/bundle": true` correctly hide the subdirectory.

**Comment by onlyongunz** [comment]
just updated, got this bug.

My settings:

``` json
// Place your settings in this file to overwrite default and user settings.
{
    "files.exclude": {
        "**/.git": true,
        "**/.svn": true,
        "**/.hg": true,
        "**/.DS_Store": true,
        "Engine/app/tmp": true,
        "Engine/app/uploaded/": true,
        "Engine/app/cache/": true,
        ".imdone":true,
        ".imdoneignore":true,
        "Ui/node_modules/":true
    }
}
```
`.imdone` and `.imdoneignore` are excluded from the explorer. however the `Ui/node_modules/`, `Engine/app/tmp` and such didn't get excluded.

Thankyou.

**Comment by bpasero** [comment]
I cannot reproduce and here is what I am doing:

![editors](https://cloud.githubusercontent.com/assets/900690/20668843/3a52e722-b571-11e6-9aa3-b39a966481c5.gif)

@onlyongunz @fvilers please advise

**Comment by fvilers** [comment]
Hi @bpasero, thanks for looking into this issue.

Here's a demo on my machine:
![vscode](https://cloud.githubusercontent.com/assets/1009621/20669220/3eb1fd7e-b573-11e6-978c-79ed387a39ee.gif)

This makes me thing that it could be related to an installed extension.

Fabian

**Comment by fvilers** [comment]
Even with all extensions disabled, I still have the issue. Here's my about box:

![vscode_version](https://cloud.githubusercontent.com/assets/1009621/20669293/b9f2f3d0-b573-11e6-962d-bf672acd69c8.png)

**Comment by mrmlnc** [comment]
My 2 cents:

**Windows 10**

Workspace config does not work. Global config works fine.

**Manjaro (Arch linux)**

Workspace and Global config works fine.

**Comment by fvilers** [comment]
Hmm @mrmlnc, workspace configuration does work as my node_modules is correclty excluded:

![image](https://cloud.githubusercontent.com/assets/1009621/20669641/96224f80-b575-11e6-8595-4b03076e96ca.png)

**Comment by bpasero** [comment]
@fvilers @onlyongunz can you see if adding it to workbench settings makes a difference?

**Comment by bpasero** [comment]
Also can you share your user settings?

**Comment by fvilers** [comment]
Hi @bpasero,

Adding to the user settings doesn't change anything, still displayed. Here's my user settings:

```
{
  "editor.tabSize": 2,
  "workbench.editor.enablePreview": false,
  "files.insertFinalNewline": true, // final-newline extension
  "git.confirmSync": false
}
```

**Comment by bpasero** [comment]
@fvilers does the folder hide if you do a restart? I wonder if this is an issue with file events missing after you change the `settings.json` file.

**Comment by fvilers** [comment]
I'm sorry to say that restarting doesn't change anything (user or workspace settings). :-(

**Comment by bpasero** [comment]
@fvilers in your example of https://github.com/Microsoft/vscode/issues/16090#issuecomment-263265947 does it hide the `public` folder if you only put `public`?

**Comment by fvilers** [comment]
@bpasero, yes, it does. Also, like I said in the initial issue description: public/*bundle or bundle* or public/**/bundle also hide the folder.

**Comment by bpasero** [comment]
@fvilers weird, are you sure the folder does not contain any whitespace or otherwise non printable characters? next step to try out is to actually debug the code and see why the filter does not apply if you want to do that.

**Comment by fvilers** [comment]
@bpasero Yes, I'm totally sure. I'm using the same directory layout across different projects and I've asked coworkers to test it too (also have the issue). I'll try to debug it, that's a good idea.

**Comment by bpasero** [comment]
@fvilers might be easier to setup Code to run out of sources, can you follow: https://github.com/Microsoft/vscode/wiki/How-to-Contribute ?

**Comment by fvilers** [comment]
@bpasero I'm already on it, thanks anyway ;-)

**Comment by bpasero** [comment]
@fvilers there is one function in explorerViewer.ts that decides if an entry in the tree is visible or not, called doIsVisible():

![image](https://cloud.githubusercontent.com/assets/900690/20704070/58d674a4-b61e-11e6-9694-86666bf5cec2.png)

If you can debug through it for the case of when "`bundle`" is coming in and see how `glob.match() `behaves in that case? It should return a match and thus hide it given the configured patterns. For you this does not seem to be the case.

Thanks!

**Comment by fvilers** [comment]
@bpasero Thanks for the hints. Currently, the project is not building when I execute `npm run watch`. I'll try to figure out why.

**Comment by mrmlnc** [comment]
@bpasero, well, it looks like is related to non-normalized path for pattern.

## Inside [glob.ts#L453-L462](https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/glob.ts#L453-L462)

![image](https://cloud.githubusercontent.com/assets/7034281/20706023/543f0e2a-b636-11e6-9620-8d437c56e3a4.png)

## Result for `nested/a` pattern

![photoshop_2016-11-29_13-19-23](https://cloud.githubusercontent.com/assets/7034281/20706186/0a89ea4c-b637-11e6-9ce0-209a696c30a6.png)

## The next step for glob-patterns

![code_2016-11-29_13-14-35](https://cloud.githubusercontent.com/assets/7034281/20706237/58a32856-b637-11e6-86cc-d4a1e7f7774c.png)

![code_2016-11-29_13-14-41](https://cloud.githubusercontent.com/assets/7034281/20706250/625fed20-b637-11e6-972d-7ddf06dbec50.png)

**Comment by fvilers** [comment]
Trying to use
```
{
  "files.exclude": {
    "public\\bundle": true
  }
}
```
does not work either.

**Comment by mrmlnc** [comment]
@fvilers, yeap, because the separator for path is defined incorrectly.

![code_2016-11-29_13-36-50](https://cloud.githubusercontent.com/assets/7034281/20706570/f9d72a8c-b638-11e6-88bf-a743b5fb1f00.png)

**Comment by fvilers** [comment]
@mrmlnc ok, that's explain it.

**Comment by mrmlnc** [comment]
@bpasero, small clarification from DevTools inside VS Code on Windows:

![image](https://cloud.githubusercontent.com/assets/7034281/20707362/2a8200dc-b63c-11e6-8798-390b7c582aa2.png)

**Comment by bpasero** [comment]
I can reproduce, it only seems to happen on Windows.

@chrmarti can you please have a look, it seems you did quite some refactoring in the area of glob.ts. To reproduce:
* run on windows
* open an empty folder
* create a folder "`public`"
* create a folder "`bundle`" within
* configure workspace settings to **files.exclude** `{ "public/bundle": true }`

**Comment by chrmarti** [comment]
Thanks for the detailed analysis. I changed glob.ts to assume that the paths to match against are using the platform's path separator so our code doesn't need to consider both cases for performance reason. That broke `toWorkspaceRelativePath()`. Passing `true` for `toOSPath`, as @mrmlnc suggests, should fix the problem.

**Comment by bpasero** [comment]
We cannot change toWorkspaceRelativePath to just always return native paths, but if you find you need it in one place (like glob), then just add a parameter to that method that allows to return native separators.
