### ISSUE TITLE
Can't resolve 'child_process' in '/mnt/vss/_work/1/s/extensions/typescript-language-features/src/commands'

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#160960]
https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=185332&view=logs&j=b7e68794-eaa8-5691-72db-3ac247b4387e&t=0d9eb5f7-1716-5d79-406f-05592d3e4905&l=42

```
[05:24:37] Error in plugin "webpack-stream"
Message:
    Module not found: Error: Can't resolve 'child_process' in '/mnt/vss/_work/1/s/extensions/typescript-language-features/src/commands'
Details:
    domainEmitter: [object Object]
    domainThrown: false

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by bpasero** [comment]
Unblocking build in https://github.com/microsoft/vscode/pull/160959

**Comment by mjbvz** [comment]
@DanielRosenwasser I believe this part of the getting started flow will need to be excluded from our web build. Will take a look
