### ISSUE TITLE
VS CODE 1.7.2 Stop Working

### ISSUE THREAD

**Issue by Jussif** [Microsoft/vscode#16095]
- VSCode Version: 1.7.2
- OS Version: 64-bit - VMware WorkStation 12 Pro 12.5.2 / Ubuntu 14.04 LTS with Memory 3.8GiB / 
                      Main OS Windows 10
- Processor Intel(R) Core(TM) i7-4700MQ CPU @2.4GHz (8CPUs) ~2.4GHz
- Memory: 16384MB RAM

The program was working rigth however a few days ago (3 or 4 I dont really know) , the VSC just got frozen each time more frequentely while I was coding until I decided to updgrade the program. I can not continue coding because this is just an annoying issue. I have only ONE( #1) extesion installed on it. This is Python created by Jayamanne . I disable all the EXTENSION ( A L L of them) but, the problem continue happening. When I revised on the Task Manager app, the VSC consumes more than 50% of the Disk C:
![untitled](https://cloud.githubusercontent.com/assets/8585535/20641643/8e6deb2a-b3e3-11e6-8fb1-070a86563698.png)
 memory ! 

Steps to Reproduce:
1. While coding on Python the page has stopped responding and I need to restart the virtual machine.

Well, I tried to write the more clearly english possible, sorry for that.
Please, help.
Thanks a lot.

**Comment by jrieken** [comment]
@Jussif Are you saying VSCode keeps writing/reading data to/from disk? You CPU seems idle.

**Comment by Jussif** [comment]
@jrieken What do you mean with that VSCode keeps writing/reading data to/from disk? I am installed VS Code on the Virtual Machine that has intalled on Ubuntu 14.04 . I did some performance test using another code editor and I have no any problem, so, I do not really know what It is causing the VSCode crashes.

**Comment by Jussif** [comment]
I attached the processes resume of the Task Manager app. 
![untitled2](https://cloud.githubusercontent.com/assets/8585535/20668178/9a0e4a2a-b554-11e6-97d6-c83c99a46c3b.png)

**Comment by jrieken** [comment]
@Jussif That is VMware. How is that related to VS Code?

**Comment by Jussif** [comment]
@jrieken Because I installed VS Code in VMware and it was working correctly before I did the upgrade to VS Code 1.7.2

**Comment by jrieken** [comment]
Well, maybe VMware doesn't have enough RAM assigned and is constantly swapping or something else. If you don't give details about the VS Code processes we cannot address this issue.

**Comment by Jussif** [comment]
I assigned 4GB RAM memory to VMware. How can I generate results about the VS Code processes? Thanks

**Comment by Jussif** [comment]
@jrieken 
I run $code --verbose into the terminal. I got these 
!
![1](https://cloud.githubusercontent.com/assets/8585535/20679760/6561a4dc-b583-11e6-91ec-7f4df1e45587.png)
![3](https://cloud.githubusercontent.com/assets/8585535/20679761/65698c7e-b583-11e6-9823-e97b3a66826e.png)

[2](https://cloud.githubusercontent.com/assets/8585535/20679748/5b759bae-b583-11e6-99bf-8ece142e8e5d.png)
results

**Comment by jrieken** [comment]
This is not helpful - Can you just check the developer console *inside* VS Code. Hit F1, type 'Toggle Developer Tools', show console

**Comment by Jussif** [comment]
![screenshot from 2016-11-28 19 57 06](https://cloud.githubusercontent.com/assets/8585535/20687697/afabca60-b5a4-11e6-91a1-56e41a0c80ce.png)

**Comment by mrmlnc** [comment]
It looks like is related to the number of files you are watching. The system has a limit to how many files can be watched by a user.

Maybe this will help you:

```shell
echo fs.inotify.max_user_watches=500000 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
```

This command increases the maximum amount of watches a user can have.

**Comment by Jussif** [comment]
@mrmlnc I have already used that command line when I read another issues. I will test if it works. Thanks for your help

**Comment by Jussif** [comment]
![screenshot from 2016-11-28 20 23 31](https://cloud.githubusercontent.com/assets/8585535/20688567/754c9b48-b5a8-11e6-91ed-1bd9eaddece7.png)

**Comment by mrmlnc** [comment]
And... this is related to your Python extension :neckbeard: 

> This really shouldn't happen. There's a bug in Jedi.

**Comment by Jussif** [comment]
What can I do to solve this issue? I have to uninstall the python extension? I used the extension Python 0.5.5 created by Don Jayamanne.

**Comment by mrmlnc** [comment]
I think you can try to find the answer in your plugin repository.

For example, https://github.com/DonJayamanne/pythonVSCode/issues/531.

> try adding the following setting into your `settings.json` file:

```json
    "python.devOptions":[
        "USERELEASEAUTOCOMP"
    ]
```

**Comment by Jussif** [comment]
As soon as I have results I will notify you. Thanks for your help

**Comment by Jussif** [comment]
I have been coding without any problem adding the command line shows below. After this correction, the VSCode is working correctly without increasing the PC usage memory @DonJayamanne @mrmlnc.  

"python.devOptions":["USERELEASEAUTOCOMP"]

I have continued testing. Thanks for your help

**Comment by mrmlnc** [comment]
Well, I think that @jrieken or @chrmarti can close this Issue?

**Comment by chrmarti** [comment]
https://github.com/DonJayamanne/pythonVSCode/issues/531
