### ISSUE TITLE
Need to stop auto-escaping special characters when args is defined in the launch.json.

### ISSUE THREAD

**Issue by aruruka** [microsoft/vscode#160999]
Type: <b>Feature Request</b>

I have captured several screenshots as reference of reproducing the issue.

Here is the Google Drawing link of screenshots with description: [vscode_always_escape_some_special_characters_automatically](https://docs.google.com/drawings/d/1n7RmnB_u9hYPY6xfA5myMLNz7uYtPLw6kF2EUAB_fvU/edit?usp=sharing)

and

here is the image of the screenshots with description: ![vs_code_feature_request](https://i.ibb.co/fH0hbLx/vscode-always-escape-some-special-characters-automatically.jpg)

I noticed this auto-escaping thing was reported in the past, see [Autoescaping characters in launch.json args #98471](https://github.com/microsoft/vscode/issues/98471).

But is there a way to stop auto-escaping?

VS Code now automatically escapes certain characters anyway, and if you can't turn this off, run and debug won't work as expected in some scenarios.

VS Code version: Code 1.71.1 (e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb, 2022-09-08T19:56:36.424Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.18.0-394.el8.x86_64

**Comment by roblourens** [comment]
We have a solution for this, but it needs to be adopted by the java debug extension. I filed https://github.com/microsoft/vscode-java-debug/issues/1220
