### ISSUE TITLE
Wrong indentation of block comments.

### ISSUE THREAD

**Issue by mysticatea** [Microsoft/vscode#1609]
Thank you for fixed #348.

Still, there is a case that `Indent` operation for block comments is wrong.

![wrong-indent](https://cloud.githubusercontent.com/assets/1937871/11974038/8f080372-a9a3-11e5-8ce7-644681273ad3.gif)

If there is a empty line in a block comment, after the empty line, a space followed by the first `*` on every line is lost.

We would often encounter this case if `files.trimTrailingWhitespace` setting is enabled.

----

```
Version 0.10.5
Commit dfc08dc9edf6607483b193bf934d3badc3fa2e11
Date 2015-12-17T16:08:04.766Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1
```

On Windows 7 Pro 64bit

**Comment by mysticatea** [comment]
Thank you very much!

**Comment by alexandrudima** [comment]
Thank you for reporting and being patient with me :+1:
