### ISSUE TITLE
Hide depreciated extensions

### ISSUE THREAD

**Issue by dzienisz** [microsoft/vscode#160982]
I would like to hide depreciated extension

**Comment by dzienisz** [comment]
Yes

W dniu czw., 15.09.2022 o 18:23 Sandeep Somavarapu ***@***.***>
napisał(a):

**Comment by dzienisz** [comment]
half of my marketplace ext is depreciated :(

**Comment by sandy081** [comment]
No plans to fix this.

CC @isidorn

**Comment by dzienisz** [comment]
This is not a bug this is suggestion

W dniu pon., 19.09.2022 o 22:00 Sandeep Somavarapu ***@***.***>
napisał(a):
