### ISSUE TITLE
Create a global command to switch between merge experiences

### ISSUE THREAD

**Issue by atk** [microsoft/vscode#160924]
At the moment, the old and new merge experiences can only be targeted via a setting, but it would be helpful to be able to switch between them – I, for example, prefer the new one to merge package.json, but the old one for other code.

**Comment by IllusionMH** [comment]
You should have button in actions area (in tabs row) to switch from new to old, and big blue button to switch to the new editor.

**Comment by isidorn** [comment]
@hediet the Open Merge Editor button is currently not a global command. This request is to create a global command to be able to assign a keyboard shortcut to it. I think this request makes sense overall.

**Comment by atk** [comment]
The button is already a good addition, thanks!

**Comment by jrieken** [comment]
With https://github.com/microsoft/vscode/pull/161072 you'll be able to have the "toogle keybinding" that's shown above



https://user-images.githubusercontent.com/1794099/190596675-7a774637-7216-4553-9119-7e5c8d0ef24b.mov

**Comment by hediet** [comment]
Can this be closed @jrieken?

**Comment by jrieken** [comment]
Yeah, let's close it - even without the F1 entry

**Comment by jrieken** [comment]
To verify:

* make sure keybinding config as posted https://github.com/microsoft/vscode/issues/160924#issuecomment-1249085600 works
