### ISSUE TITLE
Cannot configure custom terminals profiles for Server running on windows

### ISSUE THREAD

**Issue by grork** [microsoft/vscode#160926]
Issue:
I want to configure `cmd.exe` as my default terminal. Following the steps to reproduce below works on a normal, default, VS Code on windows install. However, when I run VS Code Server, and connect to it, the changes have no effect, and I'm left with PowerShell as my default terminal (nor is it possible to configure it as an alternative)

- VSCode Version:
> Version: 1.69.1
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:08:34.173Z (12 hrs ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
- Local OS Version: macOS Monterey 12.5
- Remote OS Version: Windows 11 21H2 22000.739
- Remote Extension/Connection Type: Self-host code-server
- Logs:

Steps to Reproduce:

1. Configure a `cmd.exe` / custom terminal for windows by adding this to your `settings.json`
```json
    "terminal.integrated.profiles.windows": {
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        }
    }
```
2. Try to set it as your default profile _or_ just leverage it creating a new profile

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No (Yes it repros remote, with all extensions disabled)

**Comment by connor4312** [comment]
This appears to be a terminal issue, you should be able to repro this (or not, if it's been fixed) with `./scripts/code-server`
