### ISSUE TITLE
simple merge conflicts in notebooks require manually editing the ipynb json

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#160941]
Locally I have an empty cell at the bottom of my notebook because I executed the last cell
When I try to merge in a change that has new cells, I get a merge conflict that requires I open the ipynb in a text editor to resolve.

![image](https://user-images.githubusercontent.com/2019016/190257887-a266cad7-3491-4eeb-942f-067228bad8a1.png)

**Comment by rebornix** [comment]
We can explore how to handle this gracefully in the serializer.

**Comment by yohfdo** [comment]
Can this please be solved? It's hard to work collaboratively within a team using Jupyter notebooks and VS Code if we can't sort out merge conflicts.

**Comment by ttimasdf** [comment]
I suggest there be an option to disable the notebook renderer temporarily in all editors. git operates at the text level and when merge conflict happens, it will likely produce a malformed JSON file.

We now have an error message to notify users to fallback to text editor, but "resolve in merge editor" button still don't work.

![image](https://github.com/microsoft/vscode/assets/2762704/cfc2d0fa-96c7-430c-acb6-077f8f728b0b)

**Comment by DonJayamanne** [comment]
**Note:**
* When there are merge conflicts, one will always have to open a plain text (json) editor to resolve the merge confligs
* I.e. its not possible to use Notebook UI to resolve merge conflicts (at least not yet)

**Steps to test**
* Ensure you have merge conflicts in a Notebook document
* Open the SCM view, and click on the IPYNB file, and verify you can see the merge conflicts in plain text editor view
* Click on the `Resolve in Merge Editor` button and verify you get the merge editor (again plain text), see here https://github.com/microsoft/vscode/issues/160941#issuecomment-1958693691
* When you have merge conflicts, try opening the ipynb file from the explorer view, if this fails verify you are displayed with an error message with the option to open the file in plain text view
