### ISSUE TITLE
VS Code QuickFix does not support up/down arrows for navigating

### ISSUE THREAD

**Issue by mszakacz** [microsoft/vscode#161011]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: MacOs 12.4

Hello,
I am using VS Code 1.71.2 (newest). Before update I used `cmd + .` shortcut to open QuickFix Menu, `up` / `down` arrows to navigate on it and `enter` to accept selected item. In 1.71 version Visual Studio Code provided many new things and one of the changes was QuickFixMenu - [1.71 verion](https://github.com/microsoft/vscode-docs/blob/vnext/release-notes/v1_71.md#new-code-action-control).
After upgrade, I am not able to do this action.
After using `cmd + .` shortcut QuickFix Menu opens, but I cannot use `up` and `down` arrows for navigating. `Enter` shortcut works. It is interesting that `up` and `down` arrows work (it changes the selected item) but I cannot see the selection frame, so it is not possible for me to know what QuickFix Action I am currently selecting. Please take a look at the screen-shot - the frame of the selected item is not visible.

NO SELECTION FRAME
<img width="547" alt="Screenshot 2022-09-15 at 21 33 41" src="https://user-images.githubusercontent.com/38291070/190493200-0b004c0b-bfe1-48b9-a64e-69bf79fb5c36.png">

EXPECTED SELECTION FRAME
<img width="498" alt="Screenshot 2022-09-15 at 21 35 26" src="https://user-images.githubusercontent.com/38291070/190493442-72c1ba67-7caa-4d88-88c8-f8c8c0405b86.png">

Interesting fact, this frame is visible when mouse hover on the specific list item.

What steps I did:
1) reinstall of VS Code,
2) removing all my shortcuts from keyblidings.json,
3) In upgrade the `selectNextCodeAction ` was changed, so I checked in DefaultKeyBlidings weather it is correct,

Any ideas why this selection frame in QuickFix Menu is not visible?

**Comment by mjbvz** [comment]
This was already fix #160582

The current insiders builds have the fix and it will go out to stable with 1.72

**Comment by mszakacz** [comment]
Solved!
Thank you.
So the problem occurs only while using `Dark High Contrast`.
Just go to `Preferences: Color Theme` and change it.
