### ISSUE TITLE
[Groovy] file highlighting not correct for certain functions

### ISSUE THREAD

**Issue by ThadHouse** [Microsoft/vscode#16103]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Anniversary 64 bit

I work on a project that uses Gradle, and sometimes the Groovy files do not highlight correctly. Mostly what happens is some functions are highlighted blue instead of white like other functions and definitions.  It seems like it happens only on variable definitions, but I've seen it at random places anywhere in a file. Attached are images that show the issue, and a file the exhibits the issue on every system I have. 

![groovy mishighlight 1](https://cloud.githubusercontent.com/assets/7727148/20645234/55b25612-b40c-11e6-9c8a-f124d3855c60.PNG)
![groovymiss2](https://cloud.githubusercontent.com/assets/7727148/20645235/58f4904c-b40c-11e6-8224-5775a7d9c88a.PNG)

[ntcore.zip](https://github.com/Microsoft/vscode/files/614544/ntcore.zip)

Steps to Reproduce:

1. Open file from attached Zip

**Comment by aeschli** [comment]
This got fixed in the January build due to the rewrite on how we match TextMate themes to scopes.

That said, the Groovy grammar is not so great. We currently use the one from https://github.com/textmate/groovy.tmbundle.
