### ISSUE TITLE
TypeScript debugger does not stop at breakpoint after blank line at the beginning of the file

### ISSUE THREAD

**Issue by adzil** [Microsoft/vscode#16107]
TypeScript debugger skips the breakpoint if you set them after blank new line at the beginning of the file.

- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. Create new index.ts
2. Copy the following typescript code

```javascript
// Intentional blank line goes after this line

hello()
hello()
hello()

function hello() {
  return 'hello'
}
```

Make sure you write the first `hello()` on the third line (the second line is empty)

3. Compile it with `tsc --sourceMap index.ts`
4. Configure debugger launch settings with

```json
{
  "type": "node",
  "request": "launch",
  "name": "Launch Program",
  "program": "${workspaceRoot}\\index.ts",
  "cwd": "${workspaceRoot}",
  "outFiles": [],
  "sourceMaps": true
}
```

5. Set breakpoints on `hello()` function call (all of them)
6. Run the debugger session

You will see that the breakpoint will stop at the second `hello()` function call, not the first one. I've already test the breakpoint with the compiled js file and it correctly stops at the first call. I don't know if this is the internal Node.js source mapping problem or the VSCode debugger integration problem.

![image](https://cloud.githubusercontent.com/assets/9102276/20646462/828b9064-b4ab-11e6-911b-00ecad01661f.png)

**Comment by sbj42** [comment]
I see the same problem.  Here's [a test repo](https://github.com/sbj42/vscode-ts-debug) exhibiting the problem.
