### ISSUE TITLE
Go to definition doesn't store the cursor location when the definition is in the same file

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16104]
After #11727 was fixed, doing 'go to definition' then 'back', would put the cursor in the correct location. But I just noticed that it still has the original behavior if the definition is in the same file as the starting position.

- Open some file `a.ts`
- Put the cursor on a reference to something that is defined in `a.ts`
- Do 'go to definition'
- Do 'back'
- See that the cursor is not on the reference, but somewhere earlier in its navigation history

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15735#issuecomment-262930066
