### ISSUE TITLE
Lightening Speed Launch Time

### ISSUE THREAD

**Issue by MehmetKaplan** [microsoft/vscode#161036]
First, elephant in the room, this is a luxurious requirement. But still it has a supporting rationale.

In the following two videos, you may see first launches of VSCODE vs MacOS's TextEdit.

Obviously, vscode has lots to load in the start up compared to TextEdit. That's why what I am requesting can be technically not feasible, but still I'll ask.

As you may observe from the videos, there is a small time difference in the start ups of the two editors. But that small difference, push users (at least me and a few colleagues I observed in online meetings) to open the TextEdit (or Notepad for windows) when a very quick editor is needed. But usually at next steps we look for the usage benefits of the vscode and need to switch back again to the vscode. But this switching is unnecessary and can be avoided if users choose to launch vscode at the first place.

So as a result, if technically possible, can the start up time of the vscode brought up to on par with lightest text editors (TextEdit, Notepad), so that the default choice for all kind of text editing also can be the vscode?

VSCODE Launch:
https://user-images.githubusercontent.com/2387157/190556655-da31a01d-e649-4651-a749-b05bdc5c86bf.mov

TextEdit Launch:
https://user-images.githubusercontent.com/2387157/190556718-35198b22-8fa9-4301-acc8-0be0ca3b06d7.mov

**Comment by jrieken** [comment]
Closing as not actionable but be assured that performance is a constant topic and always on top of our minds, just like other cross cutting features of features. The best way to follow our concrete efforts is to check issues with the https://github.com/microsoft/vscode/labels/perf label
