### ISSUE TITLE
how to debug win32 sigs on vscode

### ISSUE THREAD

**Issue by stan1334** [microsoft/vscode#161084]
i want debug program，when i product a sig，such as SIGBREAK，bug just pause by KernelBase.dll on vscode。
same operator on vs2019，i get this sig，how to debug win32 sigs on vscode

![image](https://user-images.githubusercontent.com/59048253/190615945-daf10a61-5927-4863-b7ca-9b218ea06461.png)

	m_signals.add(SIGSEGV);//segment violation(段错误)  
	m_signals.add(SIGBREAK); //Ctrl - Break sequence(Ctrl + Break中断)

m_signals.async_wait(std::bind(&CExitSignal::handler, this, std::placeholders::_1, std::placeholders::_2));
	m_io.run();

@bpasero
@jrieken
@joaomoreno

**Comment by roblourens** [comment]
Not clear what you are asking for, but this would probably be a feature request for the C++ debug extension
