### ISSUE TITLE
Be able to "git pull from" different places like "git push to"

### ISSUE THREAD

**Issue by jonathanperis** [Microsoft/vscode#16100]
In VS Code we able to push git repos to different places with "git push to" and choosing the remote server to push. I'll be nice if we can be able to choose from the repo to pull files, and manage the default remote, today the first remote repo added is the default isn't possible to change that via VS Code

**Comment by joaomoreno** [comment]
@BugraC, @matthewshirley, @Krzysztof-Cieslak Thanks for all your contributions. You all created a PR to solve the same issue; all in a surprisingly similar way. I wanted to keep the record of all your work so I did an octopus merge with git, thus keeping your names in history.

Thanks once again! 🍻
