### ISSUE TITLE
UserDataSyncStoreService test headers are reset after session is cleared

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161038]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=185433&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=65769c9f-3383-5c2e-eedc-910df4a0c5f1&l=9906

```
1) UserDataSyncStoreService
       test headers are reset after session is cleared :

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

```

**Comment by sandy081** [comment]
Can't reproduce it and I do not see which and what assertion is failing from the build.

**Comment by sandy081** [comment]
Sorry!! I cannot reproduce and output is not helpful.
