### ISSUE TITLE
Visual Studio Code Server: Passthrough USB devices from client to remote host via WebUSB

### ISSUE THREAD

**Issue by flawedworld** [microsoft/vscode#161018]
In my workflows it's very convenient for me to be able to access devices connected to my client from my remote development server. As a user I would like to connect a USB device to my client, pass it through to vscode.dev, and then choose a remote machine to pass the USB device to and use it from there.

**Comment by mjbvz** [comment]
UI extensions can already access usb devices connected to the client using webusb on web: https://code.visualstudio.com/updates/v1_69#_webusb-webserial-and-webhid-access-on-web

Allowing remote workspace extensions to also use the webusb API would require that we transparently proxy the webusb API from the client back to the remote. That's going to be a total bug farm

If your remote extension needs to talk to a usb device, instead:

- Have a UI extension that can use webusb (we may need API so extensions can force themselves to be run as web extensions, even on desktop)
- Expose vscode commands from that UI extension that do high level operations using webUSB (i.e. don't expose webusb directly)
- Have a workspace extension that invokes those commands
