### ISSUE TITLE
Build: `playwright` fails to install

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161039]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=185457&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=dafdf52c-6fc3-5431-f55d-37c3624b5ac3&l=13

```
$ node test/unit/browser/index.js --sequential --build --browser chromium --browser webkit --tfs 'Browser Unit Tests'
browserType.launch: Executable doesn't exist at /Users/runner/Library/Caches/ms-playwright/chromium-1015/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at runTestsInBrowser (/Users/runner/work/1/s/test/unit/browser/index.js:129:48)
    at /Users/runner/work/1/s/test/unit/browser/index.js:254:25 {
  name: 'Error'
}
error Command failed with exit code 1.
```

**Comment by lszomoru** [comment]
This is unrelated to the agent image or the overall build infrastructure.
Can you please reach out to your Playwright contacts and see if they can assist. Thanks!

**Comment by bpasero** [comment]
https://github.com/microsoft/playwright/issues/17394

**Comment by bpasero** [comment]
@lszomoru lets revert https://github.com/microsoft/vscode/pull/160490 because I think the issues only started then. I also noticed you added a timeout for the task, not sure why. I noticed that we already have `retry` logic in the code anyway:

https://github.com/microsoft/vscode/blob/dbdefe15134039b8dd6cb31453d2bce41d3b2920/build/azure-pipelines/common/installPlaywright.ts#L12

**Comment by lszomoru** [comment]
@bpasero, sure, please feel free to revert. I added timeout for the task as I have seen instances in which the task hangs.

**Comment by bpasero** [comment]
All the runs from today are green, so I think we can close this one 🚀
