### ISSUE TITLE
source control

### ISSUE THREAD

**Issue by Bellacmeireles** [microsoft/vscode#161020]
fiz o commit pra poder atualizar algumas coisas e no painel de source control do git, quando eu apertei commit ele da como se estivesse carregando mas fica desse jeito por horas.
![Captura de Tela (44)](https://user-images.githubusercontent.com/98926566/190528026-e15c7d75-9948-4a03-8bab-d245bca76a0a.png)

**Comment by lszomoru** [comment]
@Bellacmeireles, sorry for not getting back to you on this until now. In June we have released [a new feature](https://code.visualstudio.com/updates/v1_69#_author-commit-message-using-an-editor) that enables using the full editor to author the commit message in case no commit message is provided. In your screenshot I see that you have an editor opened with a file `COMMIT_EDITMSG`. To complete your commit you can enter the message in that file, save it and close it. You can also disable this feature by toggling the `git.useEditorAsCommitInput` setting.
