### ISSUE TITLE
[BUG] Markdown recognizes a tag as a URL

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#161073]
```
Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

## Reproduce:

Create a file with the `.md` suffix and write this content inside it:

```md
<hello:world>
  ...
</hello:world>
```

You are going to get a result like this:

![Group 1](https://user-images.githubusercontent.com/44144724/190599407-e0a6bff9-1948-45ae-a903-0efd9de0dd1f.png)

It thinks `hello:world` is a link and when you hover over it:

![Screenshot 2022-09-16 015951](https://user-images.githubusercontent.com/44144724/190599780-afcd6b91-191d-4827-88ad-df51c3fc658b.png)

When you click:

![Screenshot 2022-09-16 020024](https://user-images.githubusercontent.com/44144724/190599933-08329ba3-aaf7-40c8-b340-3082204fca8f.png)

As you can see it doesn't happen in `.html` file:

![Group 2](https://user-images.githubusercontent.com/44144724/190600073-807bd8df-4230-4378-bf92-1d2b638463e0.png)

So it works fine in `.html` file, but not in `.md` file.

**Comment by mjbvz** [comment]
This is as-designed. See #149475

**Comment by babakfp** [comment]
NO
IT'S NOT AS DESIGNED
IT'S NOT RELATED TO WHAT IT COMPILES TO
YOU CAN'T SAY A TAG IS A LINK BECAUSE A TAG IS A TAG, NOT A LINK
DOES THAT MAKE SENSE?
STOP CLOSING THIS ISSUE!!!
CAN'T YOU JUST DON'T DEAL WITH THIS ISSUE? CAN YOU IGNORE IT???!!!???!!!???!!!

**Comment by mjbvz** [comment]
Well that escalated quickly :)
