### ISSUE TITLE
Feature Request Automaticaly add Script tag also link tag for external libraries like for jquery,Bootstrap or our own external css/js etc

### ISSUE THREAD

**Issue by MandarSant** [Microsoft/vscode#16106]
- VSCode Version:latest
- OS Version:windows 8.1,mac,linux
 I am requesting for feature that whenever we download external libraries like jquey,bootstrap and etc....
we have to add script tag to html so when we download it the script  should automaticaly generated insted of typing for save time same feature can work for external our own css/javascript and also same for cdn link insted of copy paste the tag will be auto generated 

 it can be also done by just draging file from project view in the head tag and link or script tag with attr will be generated

i am just a beginer so i cant create a screen shot

**Comment by mrmlnc** [comment]
This is not necessary and can be done as extension.

**Comment by mjbvz** [comment]
Thanks for the suggestion.

If you would find this useful, I agree that creating an extension is the right way to go. Automatic actions like this do not fit into the core VSCode ideology, but we do allow extension authors to create this sort of functionality.
