### ISSUE TITLE
Fuzzy Match for word based suggestions

### ISSUE THREAD

**Issue by Cicin411** [Microsoft/vscode#16109]
- VSCode Version: 1.8 insider
What I do need is:
Fuzzy Match could work for "editor.wordBasedSuggestions", whatever the language is.

That is:
If GoodMorning, fooo_barr,  VisualStudioCode, TempVar1, tempvar2 ...in the context, as words, varablies,  function names or even just the comments
Then Typing:
gm  |  gom  |  goom  →all match→  GoodMorning 
fb    |  fob    |  foba    →all match→  fooo_barr
VSC |  vsc    |  visc     →all match→  VisualStudioCode
...
Of course, the suggestions' lists ordered by the matching accuracies.
This is very very useful in Sublime, and  hungry for it in VSC.

Thanks for the great tool ---VSC!

**Comment by yangweijie** [comment]
+1 usefull

**Comment by Alleysakura** [comment]
It's looks useful

**Comment by jrieken** [comment]
We actually do that 'smart' suggestion and match textual suggestions on prefix only such that they don't become to prominent. Unsure what to do...

**Comment by Cicin411** [comment]
@jrieken Thanks for your reply first. 
Yes, Fuzzy Match for word based suggestions, Not only on prefix, that's just what we thirst for.
It's almost the last reason before deleting sublime text from my disk, at least for me or many users.

With Fuzzy , the definitions of many variable names , function names or others become much easily to type and the code sources become much readable.  VSC to match visual_studio_code or VisualStudioCode or visualstudiocode is a good example. Not only is it very userful  for English, but also for other languages, maybe especially useful for words in other languages.  

Of course, with Fuzzy, there may be too many matches, that should be concerned, and as you said,  they may become to prominent. But it's really not a problem in my experiece in sublime text. We could limit the file sizes, matching scopes or other situations for its triggering, and the prefix matches also should be ordered higher than fuzzy.

Great Thanks!

**Comment by Christilut** [comment]
Yep, would love this too. Atom has this and when calling methods with a string, this really helps preventing mistakes there.

**Comment by jrieken** [comment]
Let's give it a try in January
