### ISSUE TITLE
terminal display

### ISSUE THREAD

**Issue by WalkAlone0325** [microsoft/vscode#161089]
- VS Code Version: 版本: 1.71.2
提交: 74b1f979648cc44d385a2286793c226e611f59e7
日期: 2022-09-14T21:07:15.900Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
沙盒化: No
- OS Version: Mac m1 pro 12.6

first open vscode, The terminal display is not normal. stop terminal then reopen it，It is ok.
![linshi](https://user-images.githubusercontent.com/40666434/190625355-9bc9249f-f5fb-4fda-837d-5bab900f2838.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by WalkAlone0325** [comment]
I reinstalled vscode, it's ok. thanks
