### ISSUE TITLE
Show potential exceptions (Python)

### ISSUE THREAD

**Issue by tdkbzh** [microsoft/vscode#161100]
When writing Python code, we do not know which exceptions can be raised by a function:

```python
import somelib

somelib.function() # which exceptions can be raised?
```

It would be nice to indicate to the developer which exceptions can be raised by a function call (or by imports).

**Comment by Keyacom** [comment]
The [Python](/Microsoft/vscode-python) extension is responsible for this, not VSCode's core.

**Comment by tdkbzh** [comment]
@Keyacom Thanks, I'm moving the issue over there
