### ISSUE TITLE
integrated terminal  Scroll bar error

### ISSUE THREAD

**Issue by kingyang** [Microsoft/vscode#16114]
- VSCode Version:1.7.2
- OS Version: win 10 x64

**integrated terminal  Scroll bar error**

Steps to Reproduce:

1. Ctrl+` show the "integrated terminal"
2. Execute  command  such as "gulp"
3. Ctrl+` hide the "integrated terminal"
4. After a while  Ctrl+` show the "integrated terminal"

and resize window also has some issues 

![image](https://cloud.githubusercontent.com/assets/1540211/20648070/e5eaa74a-b4d7-11e6-8820-806728146684.png)

![image](https://cloud.githubusercontent.com/assets/1540211/20648075/10a70410-b4d8-11e6-9359-ff99561ebc88.png)

![image](https://cloud.githubusercontent.com/assets/1540211/20648080/3b0ee16e-b4d8-11e6-84e0-456f50a8e47a.png)

**Comment by Tyriar** [comment]
Duplicate #8336
