### ISSUE TITLE
Syntax Highlighting Improvements Wanted

### ISSUE THREAD

**Issue by iDad5** [microsoft/vscode#161152]
## Introduction
I have already opened a related [issue](https://github.com/microsoft/vscode/issues/160630) some days ago, mostly stating my problems in understanding the workings of theming and syntax highlighting and pointing out problems I had with the documentation. 
As by now I do understand a lot more about the way things work, i decided to open a new issue as a feature request. What I will try to do is:

- explain my findings
- provide tips and examples for myself and others
- analyze strengths and weaknesses of 'TextMate'- and Semantic highlighting
- hope to collect input and support for improvements

My findings and examples are based on **TypeScript**, which is not only my primary language of choice but also one of the  languages with the deepest built in support in vs code._ 

To follow my thoughts, it is likely you need a slightly more than basic understanding of [Syntax Highlighting](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide) and [Semantic Highlighting](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide) 

### A short summary:

| Syntax Highlighting                                                          | Semantic Highlighting                                                  |
|------------------------------------------------------------------------------|-----------------------------------------------------------------------
| Based on RegEx, has no deeper 'understanding' of the language.               | Based on the Language Server, has a good understanding of the Language |
| Has a lot of (undocumented) selectors, that can be combined in multiple ways | Has a smaller set of tokens that can be combined with token modifiers  |
| Which selector has precedence isn't always easy to understand                | Precedence is connected specificity                                    |
| Existing syntaxes can be extended (injected)                                 | I couldn't find a way to add or change the built in syntax             |
| Is always overridden by semantic                                             | Always overrides TextMate syntax                                       |
| Renders instantly                                                            | Takes a moment to be applied                                           |
| Is always enabled an supported                                                          | can be disabled and enabled by user setting, themes etc.; is only supported for certain languages |

### [Semantic token scope map](https://code.visualstudio.com/api/language-extensions/semantic-highlight-guide#semantic-token-scope-map)

This is a concept that eluded me for a rather long time. Especially the term "Fallback TextMate Scope" made me totally misunderstand the concept. I thought, that if a semantic token would not work, or is not implemented for the context/language, semantic syntax highlighting would fall back to the mapped TextMate syntax token.

In fact it is the other way round: If your theme does not provide a semantic token definition for - let's say - 'function', it is **automatically** added to your theme by _hijacking_  the TextMate (style) definition that is mapped to function - in our case that would be: entity.name.function

🚨 **Possible pitfall:** The moment you define one of the (by default) mapped TextMate scopes like 'variable.other.readwrite' you automatically enable the semantic scope for 'variable' with the style of 'variable.other.readwrite' . (If semantic syntax is enabled somewhere, not necessarily in your theme.)
That semantic scope can be and is supposed to be '_better_' due the better understanding of the language, but this is not always the case - and often times surely not what you as a theme author desire.

🩹 **Tip / Hack:** you can avoid that by defining your TextMate token's **sope** as "source variable.other.readwrite", but if you define the mapped sematic toke by itself or through an other mapped TextMate token, your token will be useless anyhow.

My conclusion: As of now to build a somewhat elaborate theme syntax one needs to use both kinds of tokenization but the mapping behavior is not easy to understand and hard to customize / hack.
- TextMate scoping, while it lacks 'understanding' is very finely granulated (most of the time)  and can be extended to be even more so.
- Semantic scoping is (at least for the moment) mostly very broad. 

PROBLEM: **As sematic always wins we are in a situation where the broad brush almost always paints over the the fine details!** 👎

🛑EDIT:
-----------
#### Somehow I got stuck in my own thought-loop late in the evening. I will investigate further and update asap. I'll leave it as is with strikethroughs, as some or most of the other issues are still true and I still feel that most of my findings have some value. 
-------

### ~~Missing~~ (Typescript) Features in TextMate TYPE Highlighting:

⚠ I'll update this asap!
 
![support types](https://user-images.githubusercontent.com/13235473/190805056-582471a9-36fe-4b6e-a025-99d5003a39b0.png)

~~While in some contexts ist is easy to define a style for the type of a variable in others it is impossible regardless of the kind of highlighting you try it with.~~ A grammar injection by me caused the failure of the type annotation recognition I doublecheck and will update!

![variable other readwrite_incorrect](https://user-images.githubusercontent.com/13235473/190850173-09e26744-11e4-4148-881d-562911376ec4.png)

 ~~The situation regarding more complex Types is - you guessed it - more complex but equally unsatisfactory:~~ I caused the strange behavior by breaking something through a grammar injection. My bad, will investigate and update.

![array typing_invalid](https://user-images.githubusercontent.com/13235473/190850185-d54192d4-959b-4ff1-8661-8b4469268bcd.png)

~~I can / will try to inject TextMate tokens to remedy the situation, but I feel that this should be improved by default (and by cleverer people than me...)~~ Cleverer people than me already have done a good job at this, silly me just broke it. Update will follow.

## Round Up Example(s)

![scoping_issues](https://user-images.githubusercontent.com/13235473/190809610-f6db5f3a-70b8-4859-b191-d11e8a1e9722.png)

One of the key problems of both syntaxes is that the scope of variable / variable.other is so very broad. The fact that one is mapped to the other is in my eyes worsening the situation.

#### Step by step:

1. **_someObject_** in TextMate is only variable.other.readwrite, semantic know that is also declared here. So far so good.
2. ~~the type 󠀺󠀺:**_number_** is in TextMate terms also variable.other.readwrite ~~, semantic know nothing bout it. ~~Bummer!~~
3. ~~:**_VampireProps_** ins variable.other.readwrite for TextMate :-(~~ for semantic it is an interface not a type ???
4. now TextMate, thanks to the dot behind it takes **_bladeProps_**  as variable.other.object, while for semantic it is variable.readonly. (const). While _**window**_ and  **_document_**  are variable.other.objec for TextMate, at least **_Math_** is unique. Semantics however takes all three of them to be variable.defaultLibrary - that's it. 🧘‍♂️
5. Maybe it is just me, but I feel that **_eval_** and **_Symbol_** aren't too closely related - semantics trats them as the same function.defaultLibrary.
6. ~~the type :**_Vampire_** is variable.other.readwrite for TextMate once again,~~ semantic recognizes as as a class - but not as type. **_bladeProps_** is variable.other.readwrite and variable.other respectively. With **_Dracula_** in the next line TextMate guesses the variable.other.object thanks to the dot once again, semantics stays with variable.readonly.
7. ~~While semantics plainly ignores the type description :**_number_**  here once again, TextMate thinks its a (yeah) variable other read write. And now, ladies and Gentlemen:~~ **_age_** [++] in the next line is actually a variable.other.readwrite aka to semantics a variable.readonly. Wait - READONLY????. Actually that is true, for Dracula.age, which is a get function of the Vampire class, but as the return value is a primitive assigned to _ var age_  I'd go with the compiler that allows me to change it... (That the business logic behind my useless code samples, partly stolen btw., is faulty - mea culpa)

### Conclusion and Wishlist

- ~~Both highlighting concepts are great in their own way, both could use **improvements** in the case of TypeScript typing.~~
- The connection via the "Predefined TextMate scope mappings" should in my mind at least not be extended - rolled back if possible. 
- I understand that it's conceptually very problematic to override semantics with TextMate scopes, may be _weaker_ semantic scopes could be implemented - at least I feel we need a lot more specific semantic possibilities not to overpaint fine grained TextMate semantics. 
- A way to disable certain predefined scope mappings would be helpful for a start.

Important (to me): I always feel bad, when I criticize and sound negative, especially in this case. VS Code is such a great project, and the people building it are brillant and simply adorable. So please believe me, that, while I want to help you to improve the great work even further, I'm thankful to you and totally happy about your great work. Using VS Code and tinkering with it is just great.  THX!

**Comment by iDad5** [comment]
As promised I researched what I had done to break things and found another issue: [with injection](https://github.com/microsoft/vscode/issues/161177)

While I don't really understand the details why my injection broke things so badly, after looking at the TypeScript.tmLanguage.json I get the general idea pretty well. 

My question / suggestion is likely naive and I also do understand that you want to stay very close to the TextMate specification, but my idea would be to somehow 'add' to the syntax.

Replacing the whole syntax for well supported languages would absolutely seem nonsensical to me, but having some kind of 'include' mechanism that simply adds a (valid) pattern to the (end of) an existing repository for a tmLanguage.json would be something I could imagine as very helpful. In my imagination it wouldn't really touch any TextMate specification, and the likelihood of breaking any other complex built in constructs would diminish. 

What do you think?

**Comment by RedCMD** [comment]
`injections` sort already do that
they add themselves into the `patterns` array that you're targeting
tho the targeting system is a bit 'meh'
as when you target a single `scopeName`, it will inject itself into every single sub `patterns` array of the main one

**Comment by aeschli** [comment]
It's a topic that could fill a (small) book. I know our documentation has its limits as only a few extension authors will ever touch this.
Thanks a lot for writing your findings up and letting others benefit. 

Unfortunately, this issue is not the best place to continue the discussions and findings. Instead, a [discussion]
(https://github.com/microsoft/vscode-discussions/discussions) should be opened so that more users can chime in and help and benefit.

Focusing on your conclusions. Sorry if I misunderstand you, I'm actually not sure which is your angle. Are you a theme author, or a language provider

> The connection via the "Predefined TextMate scope mappings" should in my mind at least not be extended - rolled back if possible.

Please understand we can't change how theming works. It's now been around for several years, and themes and language providers have adapted for it. We can improve the documentation though.

> I understand that it's conceptually very problematic to override semantics with TextMate scopes, may be weaker semantic scopes could be implemented - at least I feel we need a lot more specific semantic possibilities not to overpaint fine grained TextMate semantics. A way to disable certain predefined scope mappings would be helpful for a start.

I think a theme is in full control here. It can always define a color (can be the default background color) for a semantic token, and the fallback scopes are not used.
If a language doesn't want certain predefined scope mappings to be applied, it can provide its own, more specific mapping.

Closing the issue, it's unfortunately already too complex and hard to act on. If you have specific change requests or doc improvements: Smaller issues or even PRs are very welcome. I'm also happy to answer questions.
