### ISSUE TITLE
Debugging Socket.io failes

### ISSUE THREAD

**Issue by FloMaetschke** [Microsoft/vscode#16112]
- VSCode Version: 1.8.0-Insiders
- OS Version: Win10

Steps to Reproduce:

1.  Execute the following source code with debugger crashes.
2.  Executing it from command line works fine.

I am compiling the official chat sample from socket.io ( https://github.com/rauchg/chat-example ) in typescript for nodejs.

When pressing F5 the debugger breaks on startup in the json3 module, inside json3.js at line 167 with "Unexpected token 	\t" as error.

When executing app.js directly from command line with node, it works fine.

Please note, i was successfully debugging and working on my application before without any of such problems.
Hopefully my configuration may be wrong and its not a bug of vscode. You can find the code and my launch.json below.
Thx!

````typescript
var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

app.get('/', function (req:any, res:any) {
    res.sendFile(__dirname + '/index.html');
});


io.on('connection', function(socket:any){
  socket.on('chat message', function(msg:any){
    io.emit('chat message', msg);
  });
});

http.listen(3000, function () {
    console.log('listening on *:3000');
});

my launch.json
------------------------------------------------------
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/src/app.ts",
            "stopOnEntry": false,
            "args": [],
            "cwd": "${workspaceRoot}",
            "preLaunchTask": null,
            "runtimeExecutable": null,
            "runtimeArgs": [
                "--nolazy"
            ],
            "env": {
                "NODE_ENV": "development"
            },
            "console": "internalConsole",
            "sourceMaps": true,
            "outDir": "${workspaceRoot}/bin"
        },
```

**Comment by FloMaetschke** [comment]
weinand, any idea why this happens?

**Comment by weinand** [comment]
@FloMaetschke I don't know yet, I'll have to investigate. What version of node are you using?

In the meantime please try our new experimental debugger by setting the `type` in your launch config to `node2`.

**Comment by FloMaetschke** [comment]
Thx for the fast response. I have updated nodejs to version 7.2 (latest).

I now get the following error with debugger node and node2:

""Unexpected token 	 in JSON at position 1""

  the part with "in JSON at position 1" is new.

**Comment by weinand** [comment]
@FloMaetschke where do you get the error message? A screenshot would help.

**Comment by FloMaetschke** [comment]
![image](https://cloud.githubusercontent.com/assets/7500948/20705291/adbb0fda-b622-11e6-975f-a917cc2591d1.png)

**Comment by adelphes** [comment]
@FloMaetschke Are you sure this is actually crashing (and not just breaking into the debugger)?
The same exception is thrown in an ordinary node REPL session, because the JSON contains an invalid escape sequence (the backslash should be escaped for it to be correct)
```
> JSON.parse('"\t"')
SyntaxError: Unexpected token 
 in JSON at position 1
    at Object.parse (native)
    at repl:1:6
    at sigintHandlersWrap (vm.js:32:31)
    at sigintHandlersWrap (vm.js:96:12)
    at ContextifyScript.Script.runInContext (vm.js:31:12)
    at REPLServer.defaultEval (repl.js:308:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.<anonymous> (repl.js:489:10)
    at emitOne (events.js:101:20)

```
The reason for the debugger breaking is that source is deliberately attempting to parse invalid JSON, causing an exception to be thrown. Your screenshot shows that you have "Break on all exceptions" enabled (bottom left).

**Comment by Ritterbitz** [comment]
Noob here. Using Visual Studio Code and turned on "All Exceptions", fed the kids, came back and faced that exact exception. Drove me mad. @adelphes You nailed it for me! Thanx!

Moral to the story, don't feed the kids after midnight!

**Comment by weinand** [comment]
Yes, breaking into the debugger it the expected behaviour.
