### ISSUE TITLE
can't find how to enable top menubar in VS code

### ISSUE THREAD

**Issue by BhushanChandak** [Microsoft/vscode#16117]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|jquerysnippets|donjayamanne|0.0.1|
|easy-less|mrcrowl|1.2.5|

---

Steps to Reproduce:

1.
2.

**Comment by bpasero** [comment]
@BhushanChandak pressing the Alt key should always show it!

**Comment by BhushanChandak** [comment]
Thank you. it's worked..
