### ISSUE TITLE
Unable to drag and drop file/folder from outside vscode 

### ISSUE THREAD

**Issue by Vernando05** [Microsoft/vscode#16116]
- VSCode Version: 1.7.2
- OS Version: Windows 10.0.10586 Build 10586

Steps to Reproduce:

1.  Open vscode 
2.  Drag and drop any file or folder

**Comment by bpasero** [comment]
@Vernando05 are you running VS Code as administrator?

**Comment by Vernando05** [comment]
yes, is it expected behavior?

**Comment by bpasero** [comment]
Yes, Chrome prevent dragging in that case, I am quite sure we have a bug for this logged already.
