### ISSUE TITLE
install VSCode error

### ISSUE THREAD

**Issue by 18392152392** [microsoft/vscode#161114]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. I have download VSCode, then I begin to install VSCode, I choose install path
2. the default path is c://users/admin/Appdata/Local
3. but I don't like this path, I want to choose another path, then I choose C://Program Files
4. then I begin to install, it report errors, it tell me can not install here
5. Can you tell me the reason, VSCode has confused me a lot , Thank you a lot

**Comment by AiziChen** [comment]
需要最高权限: 右键-选择最高管理员运行

**Comment by joaomoreno** [comment]
If you'd like to install in a System-wide path, please use the System installer: https://code.visualstudio.com/#alt-downloads
