### ISSUE TITLE
Markdown😵

### ISSUE THREAD

**Issue by babakfp** [microsoft/vscode#161130]
https://github.com/microsoft/vscode/issues/161073#issuecomment-1249576999
So much of free speech 😃
**The output of your example doesn't matter.** Understand that. You shouldn't try to replicate that!!!!! Please ask someone else to review this issue.
In previous issue someone was already recognized the issue and tried to open a PR. You are the only one forcing on a wrong idea.
That's all.

**Comment by mjbvz** [comment]
Cut it out. You are no longer contributing anything to the conversation around this issue and are instead behaving like a child because you can't get your way
