### ISSUE TITLE
preview markdown, vscode crash 

### ISSUE THREAD

**Issue by chinahuangjia** [Microsoft/vscode#16113]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-color|anseki|0.2.2|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.5|
|vscode-html-css|ecmel|0.0.30|
|vscode-javac|georgewfraser|0.0.23|
|live-html-previewer|hdg|0.0.1|
|java-properties|ithildir|0.0.1|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.7|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.preview markdown（ctrl + shift +v）
2.selsected some text and drag. the vscode will no response

**Comment by jrieken** [comment]
Can you be more specific please? Does it mean it hangs, like you cannot do anything else? Try open another file. Is VS Code idle or running hight CPU load?

**Comment by chinahuangjia** [comment]
think for your reply. I try for many times.

According to this step, is likely to appear
1. open or create a markdown file
2. edit the file, and don't press ctrl + s, then preview (ctrl + shift + v)
3. select some text, and drag(may be you should try two times).  it's will crash!

if you can't understand my poor english, this  accessory is  screen capture

________________________________
Sent from YoMail<http://www.yomail.com/?utm_source=signature>

< Johannes Rieken<mailto:notifications@github.com>> 2016-11-28 16:09:49 wrote:

Can you be more specific please? Does it mean it hangs, like you cannot do anything else? Try open another file. Is VS Code idle or running hight CPU load?

**Comment by mjbvz** [comment]
I was able to repo this on windows once, but not reliably and never on a mac. @chinahuangjia's steps are correct. Unfortunately, no crash stack was generated and I was not debugging when I reproduced the crash

**Comment by mjbvz** [comment]
@chinahuangjia Try in the [latest insiders builds](https://code.visualstudio.com/insiders). This bumps the markdown-it version and adds some extra exception handling, which may resolve the crash

Please let me know if you still see this.

Thanks
