### ISSUE TITLE
Variable substitution problem in tasks.json when Integrating with MATLAB Command Window

### ISSUE THREAD

**Issue by shikouzhong** [Microsoft/vscode#16111]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|matlab|Gimly81|0.4.0|

---

Steps to Reproduce:

1. Install the matlab extension by Gimly81 and set up linter path.
2. Configure the tasks.json file as:
```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "0.1.0",
    "command": "matlab",
    "isShellCommand": true,
    "args": ["-nosplash", "-nodesktop", "-r", "${fileBasename}"],
    "showOutput": "always",
    "echoCommand": true,
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "Run Matlab"
        }
    ]
}
```
3. Write a .m script file, and saved as **testForTask.m**. Such as:
```
[X,Y,Z] = peaks(25);
figure;
surf(X,Y,Z);
```
4. Run this task and the output pannel shows:
`running command> matlab -nosplash -nodesktop -r testForTask.m`
The Matlab Command Window shows:
`Undefined variable "testForTask" or function "testForTask.m".`
![image](https://cloud.githubusercontent.com/assets/19483441/20647538/9b5b7a0c-b4d1-11e6-84cf-de669415404b.png)
![image](https://cloud.githubusercontent.com/assets/19483441/20647543/a984b49a-b4d1-11e6-9306-574d51d0de26.png)

All required files have been on the MATLAB search path.

---

Reason:
From Matlab Help:

> Execute MATLAB Script or Function
> Execute the MATLAB statement, specified as a string or as the name of a MATLAB script or function. If statement is MATLAB code, enclose the string with double quotation marks. If statement is the name of a MATLAB function or script, do not specify the file extension and do not use quotation marks. Any required file must be on the MATLAB search path or in the startup folder.
> Example: `-r "disp(['Current folder: ' pwd])"`
> Example: `-r myscript`
> 

ATTENTION: When use a script as a argument, **Do NOT include its file extension. But in vscode, ${fileBasename} include the file extension**, we can see in the first image.

When I change the tasks.json into `"args": ["-nosplash", "-nodesktop", "-r", "testForTask"]`, it works well.
![image](https://cloud.githubusercontent.com/assets/19483441/20647646/ae318fbc-b4d2-11e6-9c7e-b1b1f80e7bfe.png)
![image](https://cloud.githubusercontent.com/assets/19483441/20647648/b70b8cdc-b4d2-11e6-8303-a69ef1127721.png)

Nobody will change the task.json every time they write a new .m file. Can anybody help?

**Comment by isidorn** [comment]
Please use `${fileBasenameNoExtension}` instead of `${fileBasename}`

**Comment by shikouzhong** [comment]
`${fileBasenameNoExtension}` is not recognized by vscode. it doesn't work.

**Comment by isidorn** [comment]
Will get fixed soon -> https://github.com/Microsoft/vscode/issues/15937

**Comment by shikouzhong** [comment]
great! Thx.
