### ISSUE TITLE
vscode 1.8.0 throws Request CSS/colorSymbols failed with message: Cannot read property 'findColorSymbols' of undefined when launching in debug mode

### ISSUE THREAD

**Issue by eriklieben** [Microsoft/vscode#16119]
- VSCode Version: 1.8.0-insiders
- Commit: 0b847998d914
- Node: 6.5.0

- OS Version:
Windows 10

Steps to Reproduce:

1. npm install -g yo generator-code
2. yo code
3. New Extension (TypeScript)
4. download the vscode.d.ts from master and place it in node_modules/vscode/vscode.d.ts (will not be auto installed) 
5. open with vscode insiders and press F5

Hi, I am trying to refactor an extension to use SnippetString for completion (https://github.com/aurelia/vscode-extension/issues/25), but the extension keeps crashing on the error "Request CSS/colorSymbols failed with message: Cannot read property 'findColorSymbols' of undefined" on line 103 of internal/process/next_tick.js. I guess this is because the CSS or HTML language server is crashing, but I'm not 100% sure because I get no call stack, but I guess it because it also happens in an empty project. I tried it once from an empty vscode extension project and that results in the same error.

**Comment by aeschli** [comment]
I'm quite sure is that this is related to https://github.com/Microsoft/vscode/commit/a603e8a765ea1cce688af291db60e7fe7e02c07c which should be in tomorrows insider build.
I'd be happy if you could test it again then.

**Comment by eriklieben** [comment]
Thanks! I will test it again tomorrow / when the new build is out and report back to you.

**Comment by eriklieben** [comment]
It works again after getting the latest version of vscode insiders, thanks!

**Comment by aeschli** [comment]
Thanks for the heads-up!
