### ISSUE TITLE
Default task based on glob pattern doesn't work

### ISSUE THREAD

**Issue by colinfang** [microsoft/vscode#161194]
v1.71.0 WSL2

https://github.com/microsoft/vscode/pull/141230 introduces the default tasks based on filenames.

However, it doesn't seem to work in my settings. I still have to choose one here, after I opened up a txt file and clicked "Tasks: Run Build Task"

<img width="986" alt="Screenshot 2022-09-18 121857" src="https://user-images.githubusercontent.com/1499555/190899481-6f994e41-49cf-49c9-b8df-74ff0336de90.png">

I would expect it auto executes `echo TextFile` in this case withou prompts, just as if I had set `isDefault: true` in `echo txt` task

**Comment by gjsjohnmurray** [comment]
Do you have a folder / workspace open? If yes, does it contain more than one .txt file, and/or more than one .js file?

**Comment by gjsjohnmurray** [comment]
Ignore my previous comment. Instead please try "**/*.txt" instead of "**.txt".

**Comment by colinfang** [comment]
Thanks. it works once I replace it with `**/*.txt`

Previously I was following from https://github.com/microsoft/vscode-docs/pull/5401/files

**Comment by gjsjohnmurray** [comment]
> Thanks. it works once I replace it with `**/*.txt`
> 
> Previously I was following from https://github.com/microsoft/vscode-docs/pull/5401/files

@alexr00 does the doc need to be amended?

**Comment by meganrogge** [comment]
I am now the owner, so will take a look.
