### ISSUE TITLE
Grammar Injection Not Working as Expected

### ISSUE THREAD

**Issue by iDad5** [microsoft/vscode#161177]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.71.2
- OS Version: win 11

Steps to Reproduce:

1. Write a grammar injection for TypeScript with the selector : "meta.var.(expr.ts)" that distinguishes 'var', 'let', and 'const'
2. It will find and scope only 'var' and 'let'

The same injection works as expected when using "source.(ts)" as injectionSelector but it breaks type annotations. 
As the only other scope one can target successfully is _meta.var.expr.ts_ the following problem occurs:

- the TypeScript.tmLanguage.json defines two patterns under "var-expr" (which is in the main repository) with the exact same name "meta.var.expr.ts", the first one for 'let' and 'var' the second one for 'const'. (Both are very similar, but the second one allows for targeting constants under certain conditions.)
- When called with the injectionSelector "meta.var..." only the first of those two patterns seems to be targeted. 
- this dose not happen, when the scope is one 'higher' - only possibility here is "source" however which breaks things...

Possible causes:

- it is 'illegal' to define two sibling patterns with the exact same name. (Unlikely as is seems to cause no other issues I could find)
- the TextMate way of injecting grammars is by design not able to solve the situation. (That would be an oversight, if the construction itself is valid.)
- **the implementation of the grammar injection misses the possibility of two sibling patterns with the same name. (My suspicion.)**
- there is a way to target that case by writing the injectionSelector differently (If so I couldn't find any documentation and my guesswork didn't pan out.)
- there is a way to formulate the pattern in the injection to do this. (I could find no way to do so, but I'm a bit out of my depth there but it seems unlikely and not the root cause of the situation.)

My use case surely isn't a deal breaker and it is even easily worked around in this case but the behavior itself seems not  wanted and if my assumptions are correct, maybe can be fixed easily.

**Comment by RedCMD** [comment]
Can you give the full example please 
both the `.tmlanguage.json` file and `package.json`

Related issue: https://github.com/microsoft/vscode-textmate/issues/179

**Comment by iDad5** [comment]
I will send the code later, but as I mentioned, the code gets all three when applied to the source scope and misses out on the second sibling (which is nearly identical to the first) when applied to the child target.

**Comment by iDad5** [comment]
@RedCMD: I tried to understand the issue you linked, but as even as I generally  understand it, the details eluded me. I do not think, however, the issues are related in that case.

Here's what I'm doing: 
 package.json (of my theme):

![package json](https://user-images.githubusercontent.com/13235473/190919850-c628c986-1b6e-497d-bbac-c2b4741f966f.png)

contents of my storage-type.json:

```
{
	"fileTypes": [".ts"],
	"injectionSelector": "L:meta.var.expr.ts",
	"name": "storage type keyword",
	"patterns": [
		{
			"match": "\\b(const|var|let)\\b",
			"name": "storage.type.$1.ts"
		}
	],
	"scopeName": "storage. Initializer-type"
}
```

**Comment by iDad5** [comment]
One other strange thing, of which I don't know it is related and which I could only find in my admittedly senseless syntax testing file is that:

![code-acrion](https://user-images.githubusercontent.com/13235473/190920007-ba04cb0f-cbe3-4a9d-88fd-fb347393d342.png)

the code-action bulb on line 144 offers me to replace something with a template string, and when I do, it actually chamged "Bruce" to `Bruce` in line 129...

**Comment by RedCMD** [comment]
> "scopeName": "storage. Initializer-type"

I'm not so sure how well having space in the `scopeName` will do
tho it seems like a typo when copying here

btw normally the file extension for json textmate grammars is `.tmLanguage.json`


`.+` is your friend :)
adding it in can very easily show if something is half working as intended
![image](https://user-images.githubusercontent.com/33529441/190923418-48e3fba3-8285-4e53-ab4e-746061345f8d.png)
and I also added the scopes `1` and `2` to `meta.var.expr.ts` for testing purposes
![image](https://user-images.githubusercontent.com/33529441/190923464-31e23017-ef06-4543-a226-5970e5c4404d.png)
![image](https://user-images.githubusercontent.com/33529441/190923496-cd5b7ab9-082f-4eac-8e81-b21b77552608.png)

it is indeed injecting into it
but for some reason the `const` part is being missed

**Comment by iDad5** [comment]
> > "scopeName": "storage. Initializer-type"
> 
that must have been an autocorrect error - sorry.
> btw normally the file extension for json textmate grammars is `.tmLanguage.json`
> 
Thx, I'll remember

> `.+` is your friend :) adding it in can very easily show if something is half working as intended

I don't understand how that would help, would you care to explain how?
> 
> it is indeed injecting into it but for some reason the `const` part is being missed
> 
Yes, that was what I assumed, Thanks for doublechecking. 

> I see the problem now normally `(?=(.+))` will not capture anything but typescript has put `beginCaptures` on the `begin` rule which does make it capture so the `const` part is not inside the `begin`/`end` rules and thus cannot be captured via `patterns` and inherently the injection ![image](https://user-images.githubusercontent.com/33529441/190923729-b82baf47-7485-4205-b159-9f6d56936efa.png) seems like an oversight for typescript prob should make a bugreport as the `begin` captures the `const` instead of the first intended pattern inside the `patterns` array

Thank you for your effort here, but there are several reasons why this isn't likely the the reason for the problem:

1. the first 'meta.var.exp.ts" (the one with var and let) has the exact same structure, with the positive look-aheat in the outer begin-pattern and without it in the inner
2. If the second one was broken because of it the "const"-expression should not be matched as storage.type.ts, or am I getting it wrong?
3. When I added the additional look ahead as you suggested as a test anyhow, It did not work.
4. When the injection ist made into source.ts the const is tagged as as expected (it just breaks a lot of other stuff - how exactly I haven't researched. 

> 
> > code-action bulb
> 
> I have no idea I don't know much about typescript and it's language server

Thank you, I will try to see if I can pin it down a little more.

**Comment by RedCMD** [comment]
> I don't understand how that would help, would you care to explain how?

It can very easily tell you if something has been injected
![image](https://user-images.githubusercontent.com/33529441/190988596-72014be0-69ef-47f2-9e02-e0c592d5c298.png)
![image](https://user-images.githubusercontent.com/33529441/190988566-0b6ef769-068e-448e-b2a9-1038c3d21bb1.png)
as you can see the injection is able to capture everything but `const`
which gives us a clue...

> the first 'meta.var.exp.ts" (the one with var and let) has the exact same structure, with the positive look-aheat in the outer begin-pattern and without it in the inner

tho the `begin` part of it is the same
`const` has `beginCaptures` attached to it (on the upper level)
![image](https://user-images.githubusercontent.com/33529441/190979140-74f4042d-5fcd-475f-82cf-42f7999ecc52.png)
which means the capture group `(const(?!\\s+enum\\b))` that is inside the lookahead will now actually capture it like normal
just like a normal capture group
this is the reason why `let`/`var` work, but not `const`
it is a quirk of how vscodes textmate works (either vscodes implemention of textmate or [oniguruma](https://github.com/kkos/oniguruma) (regex that vscode uses for textmate))
if I remove `beginCaptures`, it now works
![image](https://user-images.githubusercontent.com/33529441/190989682-cbecdaa6-b8fe-49f3-add2-d0f8eb0a6c62.png)



> If the second one was broken because of it the "const"-expression should not be matched as storage.type.ts, or am I getting it wrong?

`"name"` applies to both the `begin` & `end` captures as well as the content inside
`"contentName"` only applies to the inner content

> When the injection ist made into source.ts the const is tagged as as expected

when injecting into `meta.var.expr.ts`, you are only injecting into the 'content' of the `begin`/`end` rules
all injecting does, is effectively copy/paste the injection into the `"patterns"` array
when injecting into `source.ts`, you are effectively putting the injection at the top level `"patterns"` array
![image](https://user-images.githubusercontent.com/33529441/190980823-76bbdd6d-9e6e-405f-b29d-015e155a6357.png)

> (it just breaks a lot of other stuff - how exactly I haven't researched.

the reason should be clear
your injection is very simple
while theirs is extremely complex
complex for the very reason why yours causes issues
simply copying theirs should suffice
(including the `patterns` and `captures` etc I would assume)

**Comment by iDad5** [comment]
@RedCMD: Thanks again for you patience and support. I feel dumber every hour ;-). 

(I did overlook that difference - that is part of my 'condition' and one reason, why I want to build a them that supports me.)

I actually dread asking my next question, but I have to: 

I made the changes you outlined in what I thought was the active grammar for typescript:
```  ~user\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\typescript-basics\syntaxes\TypeScript.tmLanguage.json ```

and hoped to see some effect after restarting vs-code; nothing happend however... 
Some research around the web didn't gave me a better idea - beside the fully expected insight that I still have to learn a lot about the inner workings of vs-code.

Do I have to use (a copy) of said file in my theme to get it to work, or am I simply using the wrong file...?

**Comment by RedCMD** [comment]
Sorry. I do get little too worked up at times

That is the same file I was editing 
restarting should apply the changes
you could try sabotaging the file to see if any changes apply

are you removing the outter or inner `beginCaptures`?

just bear in mind that this is not a complete fix
as vscode will overwrite the changes when it updates

**Comment by iDad5** [comment]
@RedCMD: no need whatsoever to apologize, you are really helpful, and me feeling dumb was none of your doing - utterly my shame for not understanding your explanations. 

I also thought I was going totally crazy with that changes not doing anything, in the end I found out that I had the Typescript-Nightly extension running which actually replaces the Typescript grammar with its' own version...
(My shortcut way of testing things with no [turns out it isn't so - however] extensions of using a temp profile - didn't deactivate that.) 
Thank you again so much!. I can go on testing and learning now.

**Comment by iDad5** [comment]
@aeschli & @alexdima: As it turns out as @RedCMD has patiently explained to me the issue is connected to a problem with the .ts (and .tsx) grammar tmLanguage.json. 

The second 'meta.var.expr.ts' pattern that targets "const" has an additional _begin- capture-group_ that makes the innerContent unreachable for grammar injections. (The same situation applies to the TypeScript's nightly extension's grammar btw.)

Removing that capture-group for testing revealed no immediate problems to me, but there might be a legitimate reason I don't understand (yet) for it to be included. 

Should I try to report a new issue about that (and if so, where?) or will you take over or simply close this issue?

THX @all especially @RedCMD !

**Comment by RedCMD** [comment]
> The second 'meta.var.expr.ts' pattern that targets "const" has an additional begin- capture-group that makes the innerContent unreachable for grammar injections.

not quite 100%
the innerContent is still there and accessible
its just that the part you want `const` is no longer in the innerContent because it is instead captured by the outside `begin` rule


The orignal file in typescript's repo is: https://github.com/microsoft/TypeScript-TmLanguage/blob/master/TypeScript.tmLanguage
you can make a report there if you want
