### ISSUE TITLE
The port flag does not work when starting the server

### ISSUE THREAD

**Issue by mustard-mh** [microsoft/vscode#161138]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: From sources
- OS Version:

Steps to Reproduce:

- Start `server-main` with `--port` flag

**Comment by mustard-mh** [comment]
This bug is always there but after this PR https://github.com/microsoft/vscode/pull/160094, bug works

**Comment by mustard-mh** [comment]
Created a fix PR https://github.com/microsoft/vscode/pull/161146

**Comment by aeschli** [comment]
Fix in https://github.com/microsoft/vscode/pull/161254
