### ISSUE TITLE
Debug adapter process has terminated unexpectedly

### ISSUE THREAD

**Issue by GabrielGGuerreiro** [Microsoft/vscode#16124]
- VSCode Version: 1.8.0-insider
- OS Version: Ubuntu 16.10
- dotnet --version: 1.0.0-preview2-1-003177

Steps to Reproduce:

1. sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ yakkety main" > /etc/apt/sources.list.d/dotnetdev.list'
2. sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
3. sudo apt-get update
4. sudo apt-get install dotnet-dev-1.0.0-preview2.1-003177
5. mkdir hwapp
6. cd hwapp
7. dotnet new
8. dotnet restore
9. dotnet run (this runned fine)
10. head to https://code.visualstudio.com/insiders download the .deb which will download the vscode-insiders build
11. open the folder you created in the hwapp example
12. place a breakpoint in the Console.WriteLine("Hello World!");
13. Press F5 or Click the Debug Icon on the left and click on the run icon

![debugger error](https://cloud.githubusercontent.com/assets/13945178/20654636/3d8dc688-b502-11e6-8ebb-e60ca1f22314.png)

**Comment by weinand** [comment]
@GabrielGGuerreiro please file .net/C# related issues against this repo https://github.com/OmniSharp/omnisharp-vscode

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#997
