### ISSUE TITLE
Code structure for the current file

### ISSUE THREAD

**Issue by Mr-Binary** [Microsoft/vscode#16123]
Request feature:

Add a new button to the side-bar or invoke via shortcuts,
After invoking, show a brief of all the members in the current working file like below:

Class name A:
   Method A1:
   Method A2:
Class name B:
   Method B1:
   Method B2:

Associate with their signatures, to enable us jump through different blocks in a quicker manner.
Thanks :)

**Comment by leaxoy** [comment]
duplicate with #5605

**Comment by jrieken** [comment]
Thanks @leaxoy
