### ISSUE TITLE
Restart TS server: TSServer exited. Code: null. Signal: SIGTERM

### ISSUE THREAD

**Issue by shezhangzhang** [microsoft/vscode#161291]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:07:15.900Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
- OS Version: Darwin arm64 21.6.0

Steps to Reproduce:

<img width="571" alt="image" src="https://user-images.githubusercontent.com/26793777/191154715-78e67bce-6ffb-4865-8538-9665919017a4.png">

<img width="1474" alt="image" src="https://user-images.githubusercontent.com/26793777/191154778-203d9706-3110-45aa-b7d9-1980b94fb1b2.png">

When I restart ts server, I got this error: "TSServer exited. Code: null. Signal: SIGTERM".
What's wrong here ? Or it's ok ？

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
Oh actually, if you're restarting `SIGTERM` is expected. It just means that the previous server process was terminated

**Comment by shezhangzhang** [comment]
Thanks.

**Comment by Manuelbaun** [comment]
I got the same error, but ts does not work after restart. When I hover over something it says (loading...)
```
[Info  - 11:33:48.360] <syntax> Forking...
[Info  - 11:33:48.375] <syntax> Starting...
[Info  - 11:33:48.375] <semantic> Forking...
[Info  - 11:33:48.391] <semantic> Starting...
[Error  - 11:33:48.451] TSServer exited. Code: null. Signal: SIGTERM
```

**Comment by FrameMuse** [comment]
When I try to put this option to "always"
![image](https://user-images.githubusercontent.com/53980482/195335646-8088fe13-ed72-47c9-8d98-852d15631803.png)
TS Server stops working at all with the error:
```
[Info  - 11:49:53.558] Killing TS Server
[Info  - 11:49:53.558] Starting TS Server
[Info  - 11:49:53.558] Using tsserver from: /home/kotto/.vscode-server-insiders/bin/f4c58486f4a33b8c61f30a244374ef0d27dc19c3/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 11:49:53.558] <syntax> Forking...
[Info  - 11:49:53.564] <syntax> Starting...
[Error  - 11:49:53.567] TSServer exited. Code: null. Signal: SIGTERM
```

**Comment by IRediTOTO** [comment]
I usually have this error too. I don't know why it happened
