### ISSUE TITLE
Cannot use Ctrl+N/P to navigate anymore

### ISSUE THREAD

**Issue by lolimay** [microsoft/vscode#161288]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2 (Universal)
- OS Version: Darwin x64 22.0.0

Steps to Reproduce:

1. Use <kbd>Command</kbd> + <kbd>.</kbd> to get suggestions panel popped
2. Cannot use <kbd>Ctrl</kbd> + <kbd>N / P</kbd> to navigate cursor down or up, **which is working on previous versions**. I can only use <kbd>down</kbd> or <kbd>up</kbd> to do this but it's too far from my home row :(

    <img width="583" alt="image" src="https://user-images.githubusercontent.com/32427260/191152111-b9285b85-7143-49ec-b0fc-a9ba418f2b6a.png">

**Comment by mjbvz** [comment]
/fixedBy 6feea8bbb34af6bedc36afbaa002b7ee5f2d676f

Should already be in VS Code insiders and will go out with 1.72
