### ISSUE TITLE
Web: `autoStoreEditSession` is long running on shutdown

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161296]
Fyi there is no long running shutdown support on web, so this warning gets printed on unload:

 
<img width="955" alt="image" src="https://user-images.githubusercontent.com/900690/191165150-85af94ff-2c7d-47b5-97f0-4ef81619ba9b.png">

**Comment by joyceerhl** [comment]
In web we probably cannot support the `onShutdown` value.

**Comment by bpasero** [comment]
This is still on insiders.vscode.dev:

```
 ERR [lifecycle] Long running operations during shutdown are unsupported in the web (id: autoStoreWorkingChanges)
```

**Comment by joyceerhl** [comment]
@bpasero I cannot reproduce this, just to be sure this is on the latest insiders.vscode.dev?

**Comment by bpasero** [comment]
Yes, reproduces even with caches disabled:

![Recording 2023-02-22 at 06 56 59](https://user-images.githubusercontent.com/900690/220535461-788d6a31-a9fe-4d5d-8c2f-80526ffe848f.gif)
