### ISSUE TITLE
Can't Deactivate Hover

### ISSUE THREAD

**Issue by LeeWarnock** [Microsoft/vscode#16120]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. Hover over HTML or CSS paramter:
![hovertip](https://cloud.githubusercontent.com/assets/10902904/20651624/4cb63176-b4ae-11e6-9c2b-6762c8fa167f.gif)

2. Toggling editor.paramterHints does not change the behavior.

The desired outcome is the disable the popup-on-hover tip, but retain the typing tip suggestions.

**Comment by alexandrudima** [comment]
Please use `"editor.hover": false`

**Comment by LeeWarnock** [comment]
PERFECT! Thank you so much! I will spread this info around. 

Thanks for maintaining, guys! Great work!

**Comment by dheerajwebkul** [comment]
- VSCode Version: 1.16.0
- OS Version: Ubuntu 14.04

"editor.hover": false
is not working for my version. Please help for this version.
It's very annoying.

**Comment by dheerajwebkul** [comment]
Ohh,
This is right in the latest version:
https://github.com/Microsoft/vscode/issues/30114#issuecomment-321490156

"editor.hover": false

You have to restart the editor. and it will work.
Thanks,
