### ISSUE TITLE
The Problem With Code Folding

### ISSUE THREAD

**Issue by topcss** [Microsoft/vscode#16122]
- VSCode Version:1.7.2
- OS Version:WIN10

    < div>
        <! --
    </ div>
    < div>
-- >
    </ div>

**Comment by jrieken** [comment]
@topcss Please update this issue with steps and actual/expected behaviour

**Comment by topcss** [comment]
![folding](https://cloud.githubusercontent.com/assets/2252451/20660890/d2da117c-b586-11e6-81d3-a15a5a5f22b6.gif)
Do it like this.

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand html elements, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
