### ISSUE TITLE
Links in Terminal are not always clickable

### ISSUE THREAD

**Issue by brian-nicholls** [microsoft/vscode#161253]
Type: <b>Bug</b>

I have bash alias that prints the Github URL to create a pull request. I can then option+click (changed from cmd+click) the link to open the browser. However, after recent updates, sometimes the link is not clickable, and I have to copy/paste the URL into my browser window.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-1019-aws
Remote OS version: Linux x64 5.15.0-1019-aws
Remote OS version: Linux x64 5.15.0-1019-aws

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4771 CPU @ 3.50GHz (8 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|24.00GB (0.11GB free)|
|Process Argv|--crash-reporter-id 0679fc9a-a634-4249-a0e6-a05885ae9c49|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 54.197.255.191|
|OS|Linux x64 5.15.0-1019-aws|
|CPUs|AMD EPYC 7571 (8 x 2200)|
|Memory (System)|31.09GB (10.92GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 54.197.255.191|
|OS|Linux x64 5.15.0-1019-aws|
|CPUs|AMD EPYC 7571 (8 x 2200)|
|Memory (System)|31.09GB (10.92GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 54.197.255.191|
|OS|Linux x64 5.15.0-1019-aws|
|CPUs|AMD EPYC 7571 (8 x 2200)|
|Memory (System)|31.09GB (10.92GB free)|
|VM|0%|
</details><details><summary>Extensions (55)</summary>

Extension|Author (truncated)|Version
---|---|---
react-hooks-snippets|AlD|1.2.0
es7-react-js-snippets|dsz|4.4.3
vscode-peacock|joh|4.2.1
dotenv|mik|1.0.1
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
vscode-remote-extensionpack|ms-|0.21.0
haml|vay|1.0.1
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
ReactSnippets|xab|2.4.0
git-branch-files|Alw|0.0.1
laravel-extra-intellisense|ami|0.6.2
file-smart-reopener-vscode|big|0.0.1
vscode-intelephense-client|bme|1.8.2
laravel-goto-view|cod|1.3.7
githistory|don|0.6.19
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.2.2
json-tools|eri|1.0.2
prettier-vscode|esb|9.8.0
vscode-diff|fab|1.4.2
php-intellisense|fel|2.3.14
macros|ged|1.2.1
beautify|Hoo|1.5.0
ruby-linter|hoo|1.0.0
react-css-copypaste|Huz|0.0.5
vscode-peacock|joh|4.2.1
ruby-symbols|mig|0.1.8
vscode-docker|ms-|1.22.1
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.20
jupyter|ms-|2022.8.1002431955
makefile-tools|ms-|0.6.0
vscode-extension-auto-import|Nuc|1.4.3
laravel-blade|one|1.32.0
vscode-css-peek|pra|4.2.0
ruby|reb|0.28.1
laravel-artisan|rya|0.0.28
vscode-sql-beautify|sen|0.0.4
vscode-blade-formatter|shu|0.17.5
rufo-vscode|sil|0.0.3
css-auto-prefix|spo|0.1.7
laravel-goto-controller|ste|0.0.15
sapling|tea|1.2.0
pdf|tom|1.2.0
haml|vay|1.0.1
simple-ruby-erb|vor|0.2.1
vscode-wakatime|Wak|19.3.0
Ruby-extension-pack|wal|1.0.0
vscode-ruby|win|0.28.0
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30567733

```

</details>

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal
