### ISSUE TITLE
Resizing editor panes is really slow once settings editor is opened

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161239]
Open a text editor and settings editor side by side and resize the sash in between and notice a lot of lag:

![Recording 2022-09-19 at 15 57 29 (1)](https://user-images.githubusercontent.com/900690/191034544-64c529a5-1f9e-4d1a-b66d-d5ada51d27ab.gif)

A lot of time spend in `listView#probeDynamicHeight`:

![image](https://user-images.githubusercontent.com/900690/191034661-3902d9dc-938b-4aab-831b-4c459ac4734d.png)

[CPU-20220919T155811.cpuprofile.zip](https://github.com/microsoft/vscode/files/9599535/CPU-20220919T155811.cpuprofile.zip)

**Comment by joaomoreno** [comment]
Sadly, this is the cost of having dynamic heights. This is why dynamic height is disabled for all lists but is enabled (and actually created for) the settings editor.

**Comment by joaomoreno** [comment]
Actually, this is the culprit: https://github.com/microsoft/vscode/commit/a8c3c47555ec693a4ab9dee76a20c18e054bf50f cc @rebornix 

That `if` statement was made sure we reused DOM nodes for this computation if they were already in the DOM tree. But that commit broke this for the Settings Editor, making recomputing heights based on wrap a **lot** more expensive.

**Comment by joaomoreno** [comment]
**Before**, each frame takes 60ms:

![image](https://user-images.githubusercontent.com/22350/191966691-e9c11ea2-bc7a-4275-936e-51d6993c80c7.png)

**After**, each frame takes 12ms:

![image](https://user-images.githubusercontent.com/22350/191967074-e1184cec-449b-405d-b67d-679119017cfe.png)
