### ISSUE TITLE
File tree in Explorer creates some confusion

### ISSUE THREAD

**Issue by sonalsavaratkar** [Microsoft/vscode#16127]
- VSCode Version: 1.7.1
- OS Version: Window 10

Steps to Reproduce:

1.  Open any project with multiple folders and files in it.
2.  Issue is folder and files on the same level looks as if files are inside (children) that folder. Check the screenshot below.
![untitled](https://cloud.githubusercontent.com/assets/5352277/20656558/3c6dc24c-b554-11e6-97d2-ba468f82088d.png)

`+config` and `shared` folder are on the same level as other files (app.component.* files). But when we look at it (`ignoring the right arrow beside folder name`) it seems the `app.component.*` files are inside `shared` folder.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11762
