### ISSUE TITLE
[Notebook] - move execution count UI code from Jupyter to core

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#161260]
The .NET Interactive extension team is working on enabling the execution count for our notebooks. Had a quick chat with @amunger and he mentioned the code for this UI component currently lives within the Jupyter extension. This request is to have that code moved over to core such that other notebooks can have a consistent execution count UI with other notebooks in vs code.

**Comment by roblourens** [comment]
No, all the code and UI is in core. https://github.com/microsoft/vscode/blob/92ad3849dd987d7ef874444b56fcf25954979529/src/vscode-dts/vscode.d.ts#L13394

Can you explain what's missing for other notebooks @amunger?

**Comment by amunger** [comment]
ah, my mistake. I had disabled the jupyter extension and the execution counts disappeared, but that actually just happens when reloading vscode. The UI comes back when a cell is executed

**Comment by amunger** [comment]
@roblourens - do you know what is triggering that UI to show? If I execute a .net notebook cell after manually adding execution counts to the ipynb, I still don't see any execution counts in the notebook editor

**Comment by roblourens** [comment]
We only show them when a kernel is selected, and it sets that flag. I'm wondering whether we should show them when they are in the model but no kernel at all is selected. I guess that's not what you ran into though.

**Comment by roblourens** [comment]
The reason we need a flag is because we need to know whether to show the placeholder for cells that haven't executed. The case where a kernel doesn't set the flag but does provide executionOrders is a bit odd. But I think we should keep that behavior to prompt kernels to properly set the flag so we get the UI right.

**Comment by amunger** [comment]
ok, sounds like there's nothing for us do to here then.
@claudiaregio - The extension should be able to use executionOrder by just setting the `supportsExecutionOrder` flag as Rob pointed out and also editing the `execution_count` in the ipynb json.

**Comment by roblourens** [comment]
I did send a PR https://github.com/microsoft/vscode/issues/161283 for the case where no kernel is selected.

And to be sure,

> also editing the execution_count in the ipynb json.

no json editing is needed, the ipynb extension covers that end.
