### ISSUE TITLE
Integrated terminal up and down arrow keys with bash on ubuntu on windows

### ISSUE THREAD

**Issue by srinath29** [Microsoft/vscode#16126]
- VSCode Version: 1.7.2
- OS Version: windows 10, 1607 build

Steps to Reproduce:

1. Configure to use bash on Ubuntu on windows as mentioned in this article https://code.visualstudio.com/docs/editor/integrated-terminal#_configuration
2. get the bash (Ctrl + `)
3. run any command (like  "ls") 
4. Press the uparrow.  
The previous command will not come.

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/10163
