### ISSUE TITLE
How to display main keymap shortcut in empty entry area (see attached image)

### ISSUE THREAD

**Issue by onecentlin** [Microsoft/vscode#16125]
- VSCode Version: 1.7.2
- OS Version: Windows Server 2012

I notice this main keymap shortcut only displayed in my Windows Server 2012 box.
How to display such function in other OS (Windows 10, macOS)? 

![20161128_001](https://cloud.githubusercontent.com/assets/7122270/20656206/2e5190ce-b565-11e6-8dfa-4f9468e6b2cd.png)

**Comment by chrmarti** [comment]
We show the keymap shortcut only on the first run after installation. We might extend that to the first day after installation. Also: This only went into the insiders build and is not available in 1.7.2 you are reporting this for. It will be available in 1.8.0. I guess you have installed the insiders build on your Windows Server 2012 machine.

After the first run, you can always get at the command through Show All Commands (aka Command Palette) shown at the top of the list in the empty editor area.

**Comment by chrmarti** [comment]
You can find the command also in the menu bar under File > Preferences > Keymaps. (But again only in the insiders build and the coming release 1.8.0.) Closing as the issue seems to be that the feature is not in 1.7.2.
