### ISSUE TITLE
Code starts with a blurry window until the window is reloaded

### ISSUE THREAD

**Issue by major-mayer** [microsoft/vscode#161231]
Does this issue occur when all extensions are disabled?: Yes!

- VS Code Version: 1.72.0-insider
- OS Version: Manjaro Linux KDE Wayland  - latest rolling release

Steps to Reproduce:

1. Start Visual Studio Code (Insiders) using this command `code-insiders --ozone-platform=wayland --disable-extensions`
2. See the blurry window
3. Press F1 and execute `Developer: Reload window` (you can also open another folder to reproduce this)
4. The window reloads and is sharp again

This occurs on my KDE Wayland installation with a 4K display attached and set to 125% fractional scaling.

Before reloading the window:
![grafik](https://user-images.githubusercontent.com/17907799/191016128-4ffa81ad-b61d-467c-a8aa-fb868d0010b8.png)

After reloading the window:
![grafik](https://user-images.githubusercontent.com/17907799/191016170-5cecfb48-9027-454d-a3dc-4e953bac7caf.png)

**Comment by major-mayer** [comment]
Additional version info:
![grafik](https://user-images.githubusercontent.com/17907799/191016445-1c3b0506-77b0-489f-a5d6-4f1e6b49f7e1.png)

**Comment by Pajn** [comment]
>Is the error on my side?

Same for me. At least I now have a workaround for the blurry window so thanks for that!

**Comment by v-tibi** [comment]
This happens to me on Ubuntu if the laptop screen has fractional scaling and I position the second screen above the primary laptop screen. Vs code starts fine with sharp text if I leave the second screen at the default position on the right side, which is not very convenient.

**Comment by sedax90** [comment]
It's the same of https://github.com/microsoft/vscode/issues/72759

**Comment by major-mayer** [comment]
Not really. This issue is way more specific.
The other issus origins from 2019 where fractional scaling and Wayland support in general was not available, which is not the case anymore (at least if you put the use the right flags).

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/72759 since it already tracks the blurry window under fractional scaling.

**Comment by Pajn** [comment]
#72759 is not at all the same. It's due to how gnome treats X applications under fractional scaling and could be argued is not at all related to vscode, but even if it were, it's when running vscode under xwayland.

This issue is when running vscode under native wayland and is a bug in vscode itself with vscode rendering in a much smaller buffer than optimal. Probably due to some race condition in handling wayland events since reloading the window fixes it.

Both issues results in blurry windows yes, but due to different problems, in different applications, under different windowing systems.

**Comment by major-mayer** [comment]
@deepak1556  I'm not really happy with this. 
I mean fractional scaling works for me, but only when I reload the VS Code window.
The issue that you merged mine with deals about Wayland support in general.
First about providing the support for fractional scaling at all and now, as far as I see, mostly with the topic of enabling the command line flags by default.

@Pajn that's pretty much what I was about to write ;)

**Comment by deepak1556** [comment]
The other issue also has reports from users on native wayland, the reason for merging is to consolidate and test if a newer runtime addresses the issue. Please follow that issue for updates, there isn't much VSCode can do to address this issue than update to newer runtime version.

**Comment by yatahaze** [comment]
I am experiencing blur on 1.74.2 without it fixing on reload. I downgraded to 1.73.0 and am able to get it to render sharp after the developer reload.

I have to start it like this though:

```bash
code --enable-features=UseOzonePlatform --ozone-platform=wayland --log debug --log debug
Warning: 'enable-features' is not in the list of known options, but still passed to Electron/Chromium.
Warning: 'ozone-platform' is not in the list of known options, but still passed to Electron/Chromium.
```
