### ISSUE TITLE
Extraneous data written to package.json while debugging an extension that writes to package.json

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#161286]
Related to [vscode extension test run modifies package.json after 1.67.0](https://github.com/microsoft/vscode/issues/148975)

I have a couple of extensions that I wrote that can take user settings and create commands from them.  In order to have these commands available in the Command Palette it is necessary to write to some fields in the `package.json` for that extension.

This is happening when debugging in the ExtensionHost.  When the `package.json` is written to, other information is being added:

```json
 "identifier": {
  "value": "ArturoDent.find-and-transform",
  "_lower": "arturodent.find-and-transform"
 },
 "isBuiltin": false,
 "isUserBuiltin": false,
 "isUnderDevelopment": true,
 "extensionLocation": {
  "$mid": 1,
  "fsPath": "c:\\Users\\Mark\\find-and-transform",
  "_sep": 1,
  "external": "file:///c%3A/Users/Mark/find-and-transform",
  "path": "/c:/Users/Mark/find-and-transform",
  "scheme": "file"
 },
 "targetPlatform": "undefined",
```

There is no warning to me when this is done - sometimes this extra info is added near the top and sometimes near the bottom of the `package.json`.  If the extension gets published with this extra info, the extension fails.  It not only fails, it takes all of vscode down with it.

It is not clear to me what value that extra info adds to me as extension author but it is irritating to have to check the `package.json` and delete them.

Steps to Reproduce:

This is how I am writing to `package.json`:

```js
const findSettings = await extensionCommands.getSettings("findInCurrentFile");
const findSettingsCommands = await _makePackageCommandsFromFindSettings(findSettings);

thisExtension.packageJSON.contributes.commands = builtins.concat(findSettingsCommands);

fs.writeFileSync(path.join(context.extensionPath, 'package.json'), JSON.stringify(thisExtension.packageJSON, null, 1));
```

1.  Debug an extension that itself writes to the `package.json`
2.  Modify the user settings and reload. 
3. The extra data noted above is added to `package.json` by vscode.   

The simpler extension which exhibits this behaviour is [Command Alias](https://github.com/ArturoDent/command-alias).

@sandy081

**Comment by ArturoDent** [comment]
bump @sandy081 as I think, judging from the issue mentioned at the top, that this should be assigned to @sandy081?

**Comment by sandy081** [comment]
I think this is being added by the write you are doing. `JSON.stringify(thisExtension.packageJSON, null, 1)` contains this additional details. Please check it.

**Comment by ArturoDent** [comment]
I see that that extra data is added to the Extension Host version of the package.json immediately on start-up (of the Extension Host).

So when I later write `JSON.stringify(thisExtension.packageJSON, null, 1)` it is getting incorporated.

The question is, how do I test this without writing to the `thisExtension.packageJSON`?  To enable the ability to create commands in the user's settings that are then added to the package.json and so in the Command Palette I have to write to the package.json and reload and the commands from the settings are now available as hoped.

 I suppose I could, in testing, first strip out those fields (`identifier`, `isBuiltIn`, etc.)  before I write back to the package.json.  But that seems unfortunate since they will never be there in regular use.  And would that then screw up functioning of the Extension Host - maybe not since there has to be a reload anyway and they get added back in again?

Is that extra data necessary for the Extension Host?

**Comment by sandy081** [comment]
It is recommended to read the package.json from the extension location to get the original contents.

**Comment by alexdima** [comment]
> It is recommended to read the package.json from the extension location to get the original contents.

:+1: The best is to read the file from disk, parse it, modify the JSON and then write it back to disk. As you have discovered, the packageJSON exposed via the API contains these additional properties. We exposed them by accident since the first time we supported extensions and now it is not safe to remove them, as some existing extensions might have taken a dependency on these properties being there.

**Comment by ArturoDent** [comment]
I am using this code now:

```js
exports.getPackageJSON = async function () {

  const extensionPath = extensions.getExtension('ArturoDent.find-and-transform').extensionPath;
  
  const packageJSONUri = Uri.file(path.join(extensionPath, 'package.json'));
  const packageContents = (await workspace.fs.readFile(packageJSONUri)).toString();
  const packageJSON = JSON.parse(packageContents);

  return packageJSON;
}
```

It works around the issue.  Thanks for looking into this.
