### ISSUE TITLE
Implement diff detection (diff is never detected)

### ISSUE THREAD

**Issue by justanotheranonymoususer** [microsoft/vscode#161271]
Implement diff (patch file) syntax detection. It's rather easy to detect, but probably your ML wasn't trained on it, or it's confused as patch files are basically 99% some other language. Very annoying if dealing with patches often.

A way to reproduce:

* Open a patch file, for example: https://github.com/microsoft/vscode/pull/7559.patch
* Create a new document in VSCode and paste the content
* See how it's detected as anything but diff (I got Dart (?!))
* Be annoyed once again and change manually to "Diff"

Another way:

* Run `git diff | code -` from terminal
* Be annoyed

**Comment by TylerLeonhardt** [comment]
Linking to mega thread of samples that don't work: https://github.com/microsoft/vscode/issues/131450
