### ISSUE TITLE
Settings file lack intellisense

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16136]
Got it in this morning's build: 2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb

![image](https://cloud.githubusercontent.com/assets/22350/20660160/5608cec4-b548-11e6-9b29-17d45516b127.png)

**Comment by bpasero** [comment]
![image](https://cloud.githubusercontent.com/assets/900690/20660747/6271a840-b54b-11e6-907d-0e7c6cee9244.png)

@aeschli  ?

**Comment by sandy081** [comment]
It does not look related to my changes. @aeschli please take a look.

**Comment by aeschli** [comment]
Fixed by https://github.com/Microsoft/vscode/commit/a603e8a765ea1cce688af291db60e7fe7e02c07c
