### ISSUE TITLE
CSS auto completition isn't working

### ISSUE THREAD

**Issue by muhAlantabli** [Microsoft/vscode#16137]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-theme-onedark|akamud|0.2.14|
|Bookmarks|alefragnani|0.10.0|
|vscode-color|anseki|0.2.2|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|vscode-npm-script|eg2|0.1.2|
|php-debug|felixfbecker|1.10.0|
|auto-close-tag|formulahendry|0.3.5|
|code-runner|formulahendry|0.5.1|
|beautify|HookyQR|0.6.2|
|docthis|joelday|0.3.5|
|Angular2|johnpapa|1.0.2|
|format-indent|Kasik96|1.3.0|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.3.0|
|view-in-browser|qinjia|0.0.3|
|vscode-icons|robertohuertasm|4.0.2|
|Spell|seanmcbreen|0.8.6|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Please, provide more detailed information and steps to reproduce to your problem.

**Comment by aeschli** [comment]
Closing until detailed information is provided.
