### ISSUE TITLE
Table row gets broken when using back-quoted backslash(\)

### ISSUE THREAD

**Issue by espresso3389** [Microsoft/vscode#16134]
- VSCode Version:
1.8.0-insider
0b847998d914ff84fd9c13b2972cc8803745c24d
2016-11-25T09:18:45.881Z
1.4.6
53.0.2785.143
Node 6.5.0

- OS Version: Windows 10 Insider Preview 14971

You can see the 4-th row is not correctly handled by VSCode's markdown preview:

```md
#|a|b
--|--|--
1|`a` | `b`
2|`\a` | `b`
3|`\` | b
4|`\` | `a`
5|`\ ` | `a`
```

#|a|b
--|--|--
1|`a` | `b`
2|`\a` | `b`
3|`\` | b
4|`\` | `a`
5|`\ ` | `a`

![image](https://cloud.githubusercontent.com/assets/1311400/20659634/10ed35b0-b588-11e6-81c0-7e41f76448dd.png)

The 5-th line just appends a white space after `\` and it prevents from breaking the table row.

**Comment by mjbvz** [comment]
Thanks. This looks like an issue in the markdown-it library we use for the preview.

I've opened an issue against them to track this: https://github.com/markdown-it/markdown-it/issues/303
