### ISSUE TITLE
Move terminal trashcan button away from the opened terminal buttons

### ISSUE THREAD

**Issue by MrJGao** [microsoft/vscode#161325]
The thing is the trashcan button, which is used to kill the active terminal, is too close to the opened terminal buttons (image below). Sometimes, I would want to switch to the first terminal and end up clicking the trashcan by accident, then my terminal with hours of running code was gone. 
![image](https://user-images.githubusercontent.com/7261090/191305023-d26fe279-72ec-4c06-8119-3fb3c8cd2d9b.png)

I hope either the trashcan button or the opened terminal buttons could be moved somewhere else, for example, to the bottom of that right bar, to make them separate. Thanks!

**Comment by gjsjohnmurray** [comment]
https://github.com/microsoft/vscode/issues/154804#issuecomment-1251978390 might provide a solution for you, provided it get adopted in that part of VS Code.

**Comment by gjsjohnmurray** [comment]
Confirmed that you can now achieve this in Insiders by right-clicking on the trashcan button and asking to hide it:

![image](https://user-images.githubusercontent.com/6726799/191581068-aa92d933-4686-4bf7-a493-1e14bc70f23c.png)

The "Kill Terminal" option gets moved to a dropdown menu off the `...` button.

**Comment by meganrogge** [comment]
There are many ways you can avoid killing a terminal by accident - `terminal.integrated.confirmOnKill`, by hiding the trash can button as recommended above, and you can use `terminal.integrated.tabs.showActions` to configure which actions show

**Comment by MrJGao** [comment]
Got it, thank you all so much. I've configured the setting to hide the trashcan.
