### ISSUE TITLE
Downloaded on 21/9/2022: Linux tar 64-bit is old (1.66.3) and has a different sha256 hash than displayed on the download page.

### ISSUE THREAD

**Issue by alrashedf** [microsoft/vscode#161372]
Does this issue occur when all extensions are disabled?: NA

- VS Code Version: claimed: 1.71.2 downloaded:1.66.3
- OS Version: Red Hat Enterprise Linux 3.10.0-1160.71.1.el7.x86_64
- Browser: Firefox 105.0 (64-bit)
- My IP address (just in case it was a CDN caching issue): 109.171.129.119

Steps to Reproduce:

1. Go to https://code.visualstudio.com/sha/download?build=stable&os=linux-x64
2. The following file gets downloaded: **code-stable-x64-1663191492.tar.gz** 
    SHA256 is **44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855** 
which is different from SHA256 hashes on https://code.visualstudio.com/Download
   Linux .tar.gz (64-bit ARM) **ca14b5edd376c92336a22c9159e506471a703e199e9327e91de63f051ffef4bc**

Downloading a file with the wrong sha256 hash is a significant security risk. Please make this a priority.

**Comment by fluentmoheshwar** [comment]
> * My IP address (just in case it was a CDN caching issue): 109.171.129.119

You shouldn't have revealed your ip address.

**Comment by alrashedf** [comment]
> You shouldn't have revealed your ip address.
No worries. I'm in a university. The IP address is most likely a proxy server.

**Comment by fluentmoheshwar** [comment]
Oh okay then

> > You shouldn't have revealed your ip address.
> 
> No worries. I'm in a university. The IP address is most likely a proxy server.

Oh okay then.

**Comment by fluentmoheshwar** [comment]
> 1. Go to https://code.visualstudio.com/sha/download?build=stable&os=linux-x64

This URL don't even work on my machine.

You should download again from https://code.visualstudio.com

**Comment by alrashedf** [comment]
> You should download again from https://code.visualstudio.com

OK. I tried and I still get the same results. 

Try this from your machine: 

1. Go to https://code.visualstudio.com
2. Click Downloads
3. Choose Linux .tar.gz 64-bit
4. The file code-stable-x64-1663191492.tar.gz is downloaded

**Comment by fluentmoheshwar** [comment]
> > You should download again from https://code.visualstudio.com
> 
> OK. I tried and I still get the same results.
> 
> Try this from your machine:
> 
> 1. Go to https://code.visualstudio.com
> 2. Click Downloads
> 3. Choose Linux .tar.gz 64-bit
> 4. The file code-stable-x64-1663191492.tar.gz is downloaded
> 5. This is NOT v1.71.2

Same thing happening to me also. btw why using tar when rpm works on red hat linux.

**Comment by alrashedf** [comment]
> Same thing happening to me also. btw why using tar when rpm works on red hat linux.

This is an enterprise Red Had installation. We don't have sudo access. I untar vscode locally and run it.

**Comment by fluentmoheshwar** [comment]
> > Same thing happening to me also. btw why using tar when rpm works on red hat linux.
> 
> This is an enterprise Red Had installation. We don't have sudo access. I untar vscode locally and run it.

oh, then you should wait for a contributor.

**Comment by alrashedf** [comment]
> oh, then you should wait for a contributor.

Not an option. 

I just need the latest linux .tar.gz 64bit file. How can I get it?

**Comment by joaomoreno** [comment]
@alrashedf Unsure if something in your network is caching the results, but I just downloaded this and not only it is indeed 1.71.2, but the SHA matches what the website indicates.

If you use a command line tool to see what the URL redirects to, what do you see? For example, using [httpie](https://httpie.io/), I get:

```
$ http "https://code.visualstudio.com/sha/download?build=stable&os=linux-x64"
HTTP/1.1 302 Found
Content-Length: 134
Content-Type: text/plain; charset=utf-8
Date: Fri, 23 Sep 2022 13:43:16 GMT
Location: https://az764295.vo.msecnd.net/stable/74b1f979648cc44d385a2286793c226e611f59e7/code-stable-x64-1663191492.tar.gz
Server: Microsoft-IIS/10.0
Strict-Transport-Security: max-age=31536000
Vary: Accept, Accept-Encoding
X-Content-Type-Options: nosniff, nosniff
X-Frame-Options: SAMEORIGIN
X-Powered-By: ASP.NET
X-XSS-Protection: 1; mode=block

Found. Redirecting to https://az764295.vo.msecnd.net/stable/74b1f979648cc44d385a2286793c226e611f59e7/code-stable-x64-1663191492.tar.gz
```

**Comment by alrashedf** [comment]
After careful retracing of my steps, you are right. It all matches. 

Thanks!
