### ISSUE TITLE
Double output words when switch chinese input to english input

### ISSUE THREAD

**Issue by LFsWang** [Microsoft/vscode#16133]
- VSCode Version: Code - Insiders 1.8.0-insider (0b847998d914ff84fd9c13b2972cc8803745c24d, 2016-11-25T09:18:45.881Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|crane|HvyIndustries|0.2.2|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1. input some chinese word
2. press `enter`
3. press `shift` to switch input to english
4. input some english, and chinese word in step1 will output again...
![153](https://cloud.githubusercontent.com/assets/7088579/20659353/08361e3c-b57e-11e6-8d95-d78195bee7c7.gif)

**Comment by rebornix** [comment]
Dup of #15765 . They share the same root cause, using `enter` to choose words will trigger the additional addition of words.
