### ISSUE TITLE
file editor goes blank

### ISSUE THREAD

**Issue by WilliamDAssafMSFT** [microsoft/vscode#161352]
Type: <b>Bug</b>

Will be viewing a doc when its editor page goes blank.  I must close and re-open the doc. Seems to happen when I first change it. See attached screenshot.

Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22622
Sandboxed: No

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (14.08GB free)|
|Process Argv|--crash-reporter-id 23e2bccf-b91f-4850-af1e-24dd3f1afe30|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
json-yaml-schema-selector|74t|1.1.0
vscode-sidebar|Acr|1.2.2
LinkCheckMD|bla|0.3.1
vscode-markdownlint|Dav|0.48.1
docs-article-templates|doc|0.2.12
docs-authoring-pack|doc|0.1.16
docs-build|doc|0.3.12
docs-images|doc|0.0.10
docs-linting|doc|0.0.12
docs-markdown|doc|0.2.113
docs-metadata|doc|1.0.8
docs-preview|doc|0.3.59
docs-scaffolding|doc|0.0.15
docs-yaml|doc|0.2.8
powershell|ms-|2022.8.5
vscode-yaml|red|1.10.1
code-spell-checker|str|2.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30567733

```

</details>

![20220920](https://user-images.githubusercontent.com/74387232/191374224-4ee66a77-4f43-4735-aea9-c16791c03880.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by WilliamDAssafMSFT** [comment]
@gjsjohnmurray  Reproduced with no extensions enabled.

Type: <b>Bug</b>

Opened a doc from a link in another doc. 
Markdown is visible.
Interact with the doc - change it, high light it
Doc window suddenly turns blank.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (13.34GB free)|
|Process Argv|--crash-reporter-id 23e2bccf-b91f-4850-af1e-24dd3f1afe30|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by WilliamDAssafMSFT** [comment]
Also strange: is that I will ctrl+click on a file-relative path to open a doc, and get a blank tab. I'll do this a few times and _eventually_ the file loads. 

I cannot repro this behavior in the Insiders build.

**Comment by bpasero** [comment]
Then we probably fixed this issue.
