### ISSUE TITLE
No arrow for folding

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161370]
https://github.com/microsoft/vscode/blob/d86a6137cb58c57eb586605422001fdfb5d725c6/src/vs/workbench/browser/layout.ts#L52

<img width="436" alt="image" src="https://user-images.githubusercontent.com/900690/191422929-a862bf90-a253-421b-a2f9-c4f4ceb7036c.png">

In a PR with comments, seems to affect ranges that changed.

**Comment by aeschli** [comment]
Can you give some more specific details about what's wrong/missing?

Are you missing a folding range on `#region` ? You need to add a `//#endregion` somewhere

**Comment by bpasero** [comment]
Yes, quite sure it has an end region, it works fine now that it was pushed to `main`:

**Comment by bpasero** [comment]
i missed the endregion
