### ISSUE TITLE
Go/split/create/peek/run to test/source

### ISSUE THREAD

**Issue by icetbr** [microsoft/vscode#161335]
I would like to have a deeper integration between source/test file. If you don't mind please tell me which of these features should be present in the Test Explorer API, already is and/or or belongs to extensions.

 Given these files:
```js
// src/Comments.js

1: export const fetchComments = () => {};
2: 
3: export const createComments = () => {};
4: 
5: export const renderComments = () => {};

// test/CommentsTest.js

 1: describe('Comments', () => {
 2:
 3:    describe('fetchComments', () => {
 4:
 5:        it('', () => {});
 6:
 7:    });
 8:
 9:    describe('createComments', () => {
10:
11:        it('', () => {});
12:
13:    });    
14: });
```

1) I'm on line 1 of src, I want to (go | peek | tab split | run the test on) to line 3 on test
2) I'm on line 5 of src, I want to insert a template bellow line 13
3) test doesn't exist, `test/CommentTest.js` is created with a template

A mixture of these features can be seen on

https://marketplace.visualstudio.com/items?itemName=abierbaum.vscode-file-peek
https://marketplace.visualstudio.com/items?itemName=will-wow.vscode-alternate-file
https://marketplace.visualstudio.com/items?itemName=eskimoblood.create-test
https://marketplace.visualstudio.com/items?itemName=kylqin.fuzzy-goto-line

*********************
**Edit**

Would some of these be macroable? Can I pass an argument to "go to references"? Something like "goToReferences({ matching: `test/${currentFile}`)

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/126932
