### ISSUE TITLE
Tabs switching rapidly without input

### ISSUE THREAD

**Issue by LexiphanicStroon** [microsoft/vscode#161361]
We have written the needed data into your clipboard because it was too large to send. Please paste. 
Type: <b>Bug</b>

The steps that I take are opening visual studio code....I just opened up a fresh install of VS code, and the problem persists. It begins with zero input from me, and I even ran it with peripherals unplugged, I have video of this occuring.
Every time I open it, when any number of tabs is open, it switches lightning fast back and forth between the open project tabs. Nothing can interrupt it

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|30.46GB (21.59GB free)|
|Process Argv|--crash-reporter-id 31c9261a-54cb-4c02-bf9f-d3ef73e04455|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
phpserver|bra|3.0.2
gitlens|eam|12.2.2
prettier-vscode|esb|9.8.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.20
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
vsliveshare|ms-|1.0.5723
vsliveshare-audio|ms-|0.1.91
java|red|1.10.0
LiveServer|rit|5.7.9
tabagotchi|sam|0.5.0
intellicode-api-usage-examples|Vis|0.2.2
vscodeintellicode|Vis|1.2.27
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.1
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.38.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
fc301958:30567733

```

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by gjsjohnmurray** [comment]
@LexiphanicStroon I also recommend that you use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.
