### ISSUE TITLE
Extensions seem to get confused re Trusted Workspace

### ISSUE THREAD

**Issue by eshoberg** [microsoft/vscode#161363]
Type: <b>Feature Request</b>

So a couple of things that I think VS Code isn't so good at that perhaps it should be:

1) Per Workspace trust folders. The extensions seem to get confused on which workspaces they need to be poking around in if they think there are 'files of type' in the project because those files are found in one of the trusted directories under Workspace Trust. - This really sould reset for each Workspace, a saved workspace should know its folders and trust settings, and an unsaved workspace should be cleared of any and all folders excet those that are fairly explicitely shown to hold files pertaining to the current working project. (Perhaps even warn (or open in a new window) if the user is about to open a document outside of the workspace folders. 

2) I feel like it would be fairly easy to allow the extension makers to add an informational field that VS Code could read and determine if that extension sould be active at all. (Yes, this can be abused, and yes, the user isn't always going to agree with the extension maker; however, you can still keep the existing override options. 

3) Maybe I'm missing something but I can't seem to get source control to temporarily or otherwise disable. Sometimes it is quite annoying to have it running there. Say when you're using ng or npm update commands, it gives you a 'dirty git' error and doesn't let you proceed until you clear changes either by merge, stash, or push. 

VS Code version: Code - Insiders 1.72.0-insider (a829fbb91cbae44afb6a389341a0763fb3a6ac6f, 2022-09-20T05:17:31.528Z)
OS version: Windows_NT x64 10.0.25201
Modes:
Sandboxed: Yes

**Comment by lszomoru** [comment]
@eshoberg, thank you very much for your feedback. 

1. I have to admit that I am having difficulties trying to wrap my head around this feedback. This seems to be that it is being targeted towards specific behaviour from a specific extension. If that is the case, have you tried reaching out to the extension authors to provide them with this feedback? 

2. Extension authors already have the capability to declaratively state their capabilities as documented in [the extension authoring guide](https://code.visualstudio.com/api/extension-guides/workspace-trust). Users are also able to override the extension capabilities using [their user settings](https://code.visualstudio.com/api/extension-guides/workspace-trust).

3. Source control is currently only enabled in trusted workspaces. If you would like to disable source control in a trusted workspace, you can open the "Extensions" view, search for "@builtin" and disable globally/per workspace the "Git" extension.
