### ISSUE TITLE
Syntax highlighting issue when @ appears as first character after line continuation when indexing is present

### ISSUE THREAD

**Issue by tillahoffmann** [microsoft/vscode#161435]
### VS Code version

1.62.3

### Extension version

v2021.11.1422169775

### OS type

macOS

### OS version

11.6

### Python distribution

Other

### Python version

pyenv (installed with brew) in virtual environment (3.8.10)

### Language server

Default

### Expected behaviour

I would expect syntax highlighting to be the same irrespective of whether the line is broken before or after the `@` operator.

### Actual behaviour

<img width="417" alt="image" src="https://user-images.githubusercontent.com/966348/145118648-3cac8f7b-9be1-4380-851d-eab5b4660159.png">

### Steps to reproduce

Enter the following code into a new python file.

```python
# Define variables so pylance doesn't complain.
long_variable_name = other_long_variable_name = 1

long_variable_name \
    @ other_long_variable_name['some_index']

long_variable_name @ \
    other_long_variable_name['some_index']
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by alexr00** [comment]
Copied to the upstream repo that we pull the python grammar from: https://github.com/MagicStack/MagicPython/issues/253
