### ISSUE TITLE
Scrolling in the editor has regressed

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161485]
![Recording 2022-09-22 at 14 47 26](https://user-images.githubusercontent.com/900690/191750909-e86603d3-5b0b-4826-93ec-77a997fe2540.gif)

It seems to me that if you by accident select down a little bit, you now get scrolled out of view quickly.

That does not reproduce in stable and I only noticed it today.

**Comment by ethteck** [comment]
+1 - this exact thing is happening to me as well

**Comment by sandy081** [comment]
This seems to happen when the mouse goes horizontally away from the view port. For eg., when the mouse goes into the explorer view here.
