### ISSUE TITLE
How can I tell vscode always to use the workspace typescript version ? 

### ISSUE THREAD

**Issue by shezhangzhang** [microsoft/vscode#161475]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/26793777/191716960-b77824e4-857b-4f4a-8b36-20eaf23bce3b.png">

On the right bottom, we can select typescript version, default is the current vscode build-in typescript version. As a developer, I thinks it's better to use the different typescript version for different workspaces (especially the typescript version in their package.json). How can I tell vscode always to use the workspace typescript version ?

Actually, I was experience an issue with the version not being specified in workspace version. So I think use the workspace version is always good ? I don't know.

**Comment by mjbvz** [comment]
See #135713 and the `typescript.enablePromptUseWorkspaceTsdk` setting
