### ISSUE TITLE
[css] color pallet duplication

### ISSUE THREAD

**Issue by SCOTTY0101** [microsoft/vscode#161467]
Type: <b>Bug</b>

When using a .css file, the 'color' pallet selector is returning duplicate colors.
So far found the following colors are being returned twice in the dropdown list. (darkslateblue, dimgray, lightlategray and slategrey).

Example,

h1 {
color: darkslateblue;
};

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.57GB free)|
|Process Argv|--crash-reporter-id a269de92-be27-4844-9d4a-d11de640cf6a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
mobileview|cir|0.0.7
vscode-express|Com|0.0.5
vscode-eslint|dba|2.2.6
javascript-ejs-support|Dig|1.3.1
vscode-html-css|ecm|1.13.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-docker|ms-|1.22.1
remote-containers|ms-|0.251.0
debugger-for-chrome|msj|4.13.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
fc301958:30573243

```

</details>

**Comment by SCOTTY0101** [comment]
Hi Martin,

Thank you for the reply email and getting back to us.
He is a screenshot of what I thought was the colour duplication (darkslategray/darkslategrey and dimgray/dimgrey).
Looking closer at the code, I noticed the hex colours were listed twice but I didn't pick up on the different spelling of the named colours.
I seems like the different between American English and British English is why I thought there might have been a duplication.

Regards,

Alan


________________________________

**Comment by aeschli** [comment]
Hi Alan (@SCOTTY0101), thanks for getting back, no problem.
Yes, it's strange that colors are defined for both spellings. It's what the CSS color spec provides.

Closing the issue then.
