### ISSUE TITLE
Find regex too greedy

### ISSUE THREAD

**Issue by dfroze** [Microsoft/vscode#16144]
- VSCode Version: 1.7.2
- OS Version: Linux Mint

Steps to Reproduce:
- File content: 
${a} went and bought ${b} apple. And ${c} broke them
- Find exp: \\$\\{.+\\}

The match will be:  "${a} went and bought ${b} apple. And ${c}"
Is it ok to be this greedy? Or is it there a way to change this in settings or something?

**Comment by siegebell** [comment]
Use `\$\{.+?\}` (it seems adhere to [JavaScript RegExp](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp))

**Comment by dfroze** [comment]
@siegebell Thank you. I knew about that possibility, but i am looking for a more permanent solution.

**Comment by mjbvz** [comment]
This is the correct behavior of regular expression quantifiers so @siegebell's solution is correct.

Adding some sort of setting to change this would go against expected regular expression behavior.
