### ISSUE TITLE
Modules with two leading slashes can't be mapped properly in VS Code debugger

### ISSUE THREAD

**Issue by OEP** [microsoft/vscode#161498]
Hi, this is a follow-up to a discussion: https://github.com/microsoft/vscode-python/discussions/19835
I reported to debugpy, it was reproduced there, and they referred me here: microsoft/debugpy#1061

## Environment data

- VS Code Version 1.71.2
- debugpy version: 1.6.3
- OS and version: CentOS 7.9, macOS 11.6.2 (Big Sur)
- Python version : Tested on 3.9 (macOS), 3.7 and 3.6 (CentOS)
- Using VS Code or Visual Studio: VS Code

## Actual behavior

In VS Code, breakpoint is hit, but path-mapping does not work with an error in the editor pane.

> The editor could not be opened because the file was not found.

Creating the file tries to `mkdir /vscode-path` and fails.

In a more complex example that I couldn't find a MWE for, the Call Stack pane in VS Code says:

```
[UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
```

## Expected  behavior

Breakpoint is hit and the path-mapping works.

## Steps to reproduce:

Create a file like the following:

```
$ cat /tmp/vscode-path/vscode_blah.py 
import sys
import pprint
pprint.pprint(sys.path)

import debugpy
debugpy.listen(5678)
print("WAIT")
debugpy.wait_for_client()

print("HEY")
```

Create a standard "remote attach" debug configuration.

```
{
        "host": "localhost",
        "name": "Remote Attach",
        "port": 5678,
        "request": "attach",
        "type": "python"
}
```

In the VS Code editor, set a breakpoint on the final `print()`.

Try to import it via a PYTHONPATH with a leading double slash.

```
$ PYTHONPATH=//tmp/vscode-path python3 -c "import vscode_blah"
```

**Comment by roblourens** [comment]
Please file in the vscode-python repo

**Comment by fabioz** [comment]
@roblourens I believe this isn't an issue in debugpy. 

IMHO, `debugpy` itself does everything properly here, it's VSCode itself that doesn't support it.

i.e.: the stack frame message is correct:

`{"type": "response", "request_seq": 19, "success": true, "command": "stackTrace", "body": {"stackFrames": [{"id": 2, "name": "<module>", "line": 15, "column": 1, "source": {"path": "//tmp/vscode-path/vscode_blah.py", "sourceReference": 1}}, {"id": 3, "name": "<module>", "line": 1, "column": 1, "source": {"path": "<string>", "sourceReference": 2}}], "totalFrames": 2}, "seq": 48, "pydevd_cmd_id": 502}`

Screenshot showing error:

![image](https://user-images.githubusercontent.com/117621/191779684-51ab8c6f-82ea-49b1-937b-121aaffa9a6f.png)

The issue is that VSCode itself can't interpret it properly because it can't create its internal URI to map that filesystem folder...

**Comment by karthiknadig** [comment]
This seems to occur in the DAP client. Python extension is not involved here.

**Comment by roblourens** [comment]
Sorry, what does a path with a double leading slash mean?

**Comment by OEP** [comment]
I like [this explanation](https://askubuntu.com/a/23809). I guess it can be much more long-winded.

> `//` is usually the same as `/`. `///` must be the same as `/`.

**Comment by roblourens** [comment]
> A pathname that begins with two successive slashes may be interpreted in an implementation-defined manner

That's not entirely helpful 😆 Ok, our implementation says you get an error message.

Can you explain why you are using two slashes instead of one?

**Comment by OEP** [comment]
In this case it was an accident. But, I could be using mingw32 in which `//server/share` might be interpreted as a Windows UNC path. Not typical, but I think it's reasonable that VS Code supports whatever the underlying file system supports.

**Comment by roblourens** [comment]
Don't UNC paths use backslashes?

**Comment by OEP** [comment]
In Python it's actually fine to use either slash direction to represent a UNC path.

**Comment by roblourens** [comment]
Interesting. Honestly, I don't really think vscode is doing anything wrong here. You even said that using two slashes was an accident. I only want to spend time on this if there is a specific real world scenario that is blocking a user.

**Comment by OEP** [comment]
I did just discover this problem affects me in more ways than one. Say I deploy some Python code to `\\server\share`. But I also mount this volume over NFS as `/server/share` on some Linux clients. Setting `PYTHONPATH=//server/share` has the nice property of working on either a Linux or Windows client. But I'd have to work around this limitation in some way to use the debugger.

**Comment by OEP** [comment]
I haven't tried, but I assume it must. But the simple case I am describing is a part of a system that is unlikely to change for similar reasons -- at least I know it is a change I can't make lightly just to support VS Code. Not a hill I'm prepared to die on, just making sure I didn't undersell it.

**Comment by OEP** [comment]
I've updated the ticket description with a workaround using `pathMappings` to remove the slashes. That works for the simple reproduction case I produced, and should probably work fine for the wider problem I was dealing with.
