### ISSUE TITLE
Edit a file using Vim in the terminal of VS Code cause the terminal hang

### ISSUE THREAD

**Issue by aladine** [Microsoft/vscode#16141]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 14.5.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|gitlens|eamodio|1.2.0|
|vscode-great-icons|emmanuelbeziat|1.1.26|
|Go|lukehoban|0.6.50|
|ruby-rubocop|misogi|0.3.2|
|Ruby|rebornix|0.10.3|

---

Steps to Reproduce:

1.Open terminal. Adjust the height such that it occupied less than half of screen's height.
2.Edit a file in the folder using vim. while navigate then the terminal window hang. Only clicking on trash icon will resolve this issue.

**Comment by Tyriar** [comment]
Can you elaborate on step 2? You just open a file in vim and it freezes? What do you do in vim before this happens?

**Comment by aladine** [comment]
Edit any file in the current folder. However, if i adjust the terminal height over half of the window, the problem doesn't happen. Do I need to post my vim config here?

**Comment by Tyriar** [comment]
Hmm, I cannot repro. Could you do the following?

- Take a screenshot before and after the window hang
- After it happens open dev tools (Help > Toggle Developer Tools), open the console and paste in any errors that you see
- After it happens in dev tools inspect the terminal element, I'm interested in the children of the `.xterm-rows` div

**Comment by aladine** [comment]
Here is what i get from developer tool. Unfortunatedly, i cannot find div xterms-rows in console
document.getElementsByClassName("xterm-rows") return []

index.js:26 TypeError: Cannot set property '0' of undefined
    at Terminal.write (xterm.js:1501)
    at ChildProcess.<anonymous> (workbench.main.js:124)
    at emitTwo (events.js:111)
    at ChildProcess.emit (events.js:191)
    at process.nextTick (internal/child_process.js:744)
    at _combinedTickCallback (internal/process/next_tick.js:67)
    at process._tickCallback (internal/process/next_tick.js:98)onError @ index.js:26
xterm.js:1501 Uncaught TypeError: Cannot set property '0' of undefined
index.js:23 [uncaught exception]: TypeError: Cannot read property '0' of undefinedonError @ index.js:23
index.js:26 TypeError: Cannot read property '0' of undefined
    at Terminal.refresh (xterm.js:1111)
    at xterm.js:1058onError @ index.js:26
xterm.js:1111 Uncaught TypeError: Cannot read property '0' of undefined

**Comment by Tyriar** [comment]
Could you get a screenshot of it happening too?

**Comment by aladine** [comment]
sure, the order is from the bottom to top. 
![screen shot 2016-12-02 at 21 05 58](https://cloud.githubusercontent.com/assets/287410/20910569/49318f82-bb9d-11e6-980b-91db2ecb9f4e.png)
![screen shot 2016-12-02 at 21 05 34](https://cloud.githubusercontent.com/assets/287410/20910570/49356cba-bb9d-11e6-9467-969fed1e0fa5.png)
![screen shot 2016-12-02 at 21 05 04](https://cloud.githubusercontent.com/assets/287410/20910571/4937007a-bb9d-11e6-9951-4759b259ca88.png)

**Comment by aladine** [comment]
I suspect the arrow key cause the vim window freeze.

**Comment by Tyriar** [comment]
I think this is related to https://github.com/sourcelair/xterm.js/issues/385
