### ISSUE TITLE
Error : Extension host terminated unexpectedly in VS Code

### ISSUE THREAD

**Issue by coolhand-code** [microsoft/vscode#161439]
it causes [Error : Extension host terminated unexpectedly in VS Code](https://stackoverflow.com/questions/70052961/error-extension-host-terminated-unexpectedly-in-vs-code) and slows down the VS Code

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Embedder: codespaces

Extension version: 1.0.5

**Comment by alexdima** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/
