### ISSUE TITLE
Errors showing in editor screen (even when the code compiles)

### ISSUE THREAD

**Issue by Dnitin** [microsoft/vscode#161468]
Type: <b>Bug</b>

Steps to Reproduce(Inconsistently): 

1. Make a syntactical error.
2. fix the error.
3. The error still shows in the editor and 'PROBLEMS' tab.

I'm not sure if this issue exists with other language, but I'm facing this with C++

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.60GB free)|
|Process Argv|--remote=wsl+Ubuntu-20.04 --crash-reporter-id e3f80e10-c339-46ca-87d3-e0c2ae852de2|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-20.04|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|15.55GB (12.97GB free)|
|VM|0%|
</details>

**Comment by dbaeumer** [comment]
@Dnitin the problem is with the C/C++ extension. Can you please open an issue here: https://github.com/Microsoft/vscode-cpptools
