### ISSUE TITLE
/usr/bin/env: ‘ruby_executable_hooks’: No such file or directory

### ISSUE THREAD

**Issue by adham90** [Microsoft/vscode#16140]
- VSCode Version:1.7.2
- OS Version: ArchLinux(x86_64 Linux 4.8.10-1-ARCH)

Steps to Reproduce:

1. useing `ruby on rails` app
2. open `debug` tab
3. run `rails server`

```
        {
            "name": "Rails server",
            "type": "Ruby",
            "request": "launch",
            "showDebuggerOutput": true,
            "cwd": "${workspaceRoot}",
            "program": "${workspaceRoot}/bin/rails",
            "pathToRDebugIDE": "/home/adham/.rvm/gems/ruby-2.3.0/bin/rdebug-ide",
            "args": [
                "server"
            ]
        }
```
output this error: `/usr/bin/env: ‘ruby_executable_hooks’: No such file or directory`

**Comment by isidorn** [comment]
Please file this issue against the vscode ruby extension here https://github.com/rubyide/vscode-ruby

Thansk!
