### ISSUE TITLE
Change visual treatment of `@deprecated`

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/vscode#161410]
Today, a member of our team asked if a component I had marked `@deprecated` should not be used because it was presented in strikethrough text in VSCode.

VSCode, in my opinion, visually treats `@deprecated` in a way that communicates this incorrectly. I'm using deprecated by [this meaning](https://english.stackexchange.com/questions/87887/what-is-the-difference-between-obsolete-and-deprecate-in-computer-science):

> Deprecated means still available for use but will no longer be developed or supported and may be discontinued in the next release or so.

The key phrase is "still available for use". VSCode's strikethrough, instead of signifying that you _can_ use it, instead seems to visually say, "Do not use this, and use something else."  In software, deprecated _may_ mean there is something else to use and some teams _may_ use deprecated to mean "do not use", but that may not be the case! It just means "marked for discontinued use". So, IMO, the visual treatment of this may be something like a yellow warning underline (something much more subtle).

So the feature request would be: change the default rendering of `@deprecated` to something more universal for software team's definition of "deprecated", which gently warns about usage, instead of a line through it which indicates "never use this".

**Comment by mjbvz** [comment]
>  instead seems to visually say, "Do not use this, and use something else." 

This was our thinking when we opted to use a strikethrough :)

IMO strikethrough is a good compromise for indicated that a symbol is deprecated. It does not prevent using the symbol like an error or warning would, but makes it clear that you should not use the symbol for future code and should also look into migrating your existing code to a non-deprecated solution

**Comment by matthew-dean** [comment]
I mean, to me this changes the grammatical / semantic meaning of a strikethrough, but if I'm in the minority, that's okay. In the meantime, I've changed `@deprecated` to `// DEPRECATED` to not cause this issue
