### ISSUE TITLE
terminal links bleed together and remain underlined after focus out

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#161436]
https://user-images.githubusercontent.com/29464607/191609450-966f224e-a7b9-40ba-bd2f-b7afe8598f51.mov

**Comment by Tyriar** [comment]
It's probably hard to reproduce this

**Comment by meganrogge** [comment]
will take a gif whenever I see it happen in case there's a pattern we start to see
https://user-images.githubusercontent.com/29464607/192849108-2531ccc5-81a7-44cb-9eb6-23825f8843c9.mov

**Comment by meganrogge** [comment]
what i'm curious about is why it isn't ending the link on the first space char

![Screen Shot 2022-09-28 at 10 32 25 AM](https://user-images.githubusercontent.com/29464607/192850124-3fb6e296-96bd-4662-88e6-3fb321534b35.png)

**Comment by Tyriar** [comment]
We can't action this unfortunately until we get a good repro.
