### ISSUE TITLE
Always ask me to install develop tool

### ISSUE THREAD

**Issue by Zhangyanbo** [microsoft/vscode#161449]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2
- OS Version: MacOS 12.6

Steps to Reproduce:

1. Open VSCode
2. Do anything, then it will pop up a window says "The "git" command requires the command line developer tools." While installing the tool will not fix this problem

**Comment by yume-chan** [comment]
Maybe duplicate of #160872
