### ISSUE TITLE
Add option to diffEditor.wordWrap to inherit setting from the compared file

### ISSUE THREAD

**Issue by johannespitz** [microsoft/vscode#161412]
Problem:
Often I toggle the word wrap for a couple of files (.tex files usually). And every time I want to view the diff, the current file is displayed with word wrap while the old file is displayed without word wrap:
<img width="726" alt="image" src="https://user-images.githubusercontent.com/18274476/191553970-ee32b3de-87cc-4aa1-8194-200be557a7fd.png">
Then I have to toggle the word wrap for the old file by hand (which for some reason sends me to a different location in the file).

Solution:
I think it would always make sense to use the same word wrap setting for both files, but adding an option to enforce this behavior would also be an excellent solution for me.

**Comment by alexdima** [comment]
To verify:
* have a file with changes (modified)
* toggle word wrap (alt+z)
* open the file in the diff editor
* the original should also be word wrapped.
