### ISSUE TITLE
`interactive.history.focus` command does not set focus from Editor API perspective

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#161440]
Does this issue occur when all extensions are disabled?: Yes/No

1. create an interactive window and execute a cell (do not click into the history)
2. focus on the IW input box and use the `interactive.history.focus` command to get to the history (you'll have to set a keyboard shortcut)
3. Run a command that gets the selected cell from the editor API, as is done here: https://github.com/microsoft/vscode-jupyter/pull/11428/files
🐛 `selection` is undefined

Once you click on a cell manually, the selection is set properly

**Comment by roblourens** [comment]
The first cell in the IW is focused initially, before you run the focus command, but this isn't reflected in the model in the EH. So it seems like it isn't being initialized properly.

**Comment by amunger** [comment]
verification steps:
use the OP steps, a cell in the interactive window history should be selected
