### ISSUE TITLE
notebook/kernelSource commands don't have notebook context and don't pass in the related editor as an argument

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#161445]
We've been playing around more with these notebook/kernelSource commands and I'm seeing some issues (I believe) that are going to start causing issue with them the more we use them.

In package.json it would be really nice to be able to define a when: notebookType == 'jupyter-notebook' but this doesn't seem to currently work. Right now the Server Switching commands from the experiment showing up in .dib files (I'm fixing this now). Also when these commands are called I believe that they don't have the current editor as an argument. That would be really helpful with the kernel picking experiments that I'm working on.

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/163693 and https://github.com/microsoft/vscode/pull/163701

**Comment by IanMatthewHuff** [comment]
Makes all the kernel source command scenarios much better. Thanks much!
