### ISSUE TITLE
Right-click menu supports opening and closing files

### ISSUE THREAD

**Issue by halodong** [microsoft/vscode#161493]
Scenario: Usually there are a lot of files in a project. When I find a suitable file in many files, it may be closed due to my mistake. At this time, it is not easy to repair this operation, and I can only find it again.

Feature: Is it a good choice to add an option to reopen the last or group of closed files in the file tab right-click menu?

Remarks: I searched for relevant documents and did not find a similar function. If this function is confirmed to be developed, I expect that I can participate and provide pr.

![1663857736649](https://user-images.githubusercontent.com/48054715/191778205-39a73c1d-82a2-4748-9173-7f1f7ce8843b.jpg)

**Comment by rzhao271** [comment]
With VS Code, a lot of functionality is in the command palette.

If you hit F1 to open the command palette, you can search for the "View: Reopen Closed Editor" command. That command (along with its customizable keybinding) reopens the closed editor.
Therefore, there is a command to reopen the last editor, but there's no context menu entry for it.

Is this issue a feature request to add the context menu entry, or does my suggestion resolve the issue?

**Comment by halodong** [comment]
Sorry, I did not understand the command very deeply. I think your solution is very good, and there is no need for new features for the time being.
