### ISSUE TITLE
Add `jsx` to fenced codeblock code snippet languages

### ISSUE THREAD

**Issue by adriancch-inditex** [microsoft/vscode#161430]
In a markdown file there is a code snippet called `fenced codeblock`. When you use it, you have the option to specify the language. There are many languages, but jsx is not among them.

Also, I noted something annoying: If you enter `jsx` when the cursor is where you specify the language of the code block and then press <kbd>Tab</kbd> to move the cursor to the body of the code block, `jsx` will be replaced with `json` because that's the option VSCode thinks you want to select. Isn't there a way to move the cursor without having to press <kbd>Esc</kbd> before <kbd>Tab</kbd> to avoid this? Kind of annoying to have to press 2 keys every time for this.

**Comment by mjbvz** [comment]
The list of languages shown by this snippet is just a set of commonly used one. It is not meant to be comprehensive and it does not prevent you from writing whatever language you want

If you want to create `jsx` code blocks often, you can create your own snippet for that
