### ISSUE TITLE
[Terminal] Long links aren't detected fully

### ISSUE THREAD

**Issue by yuriybelike** [microsoft/vscode#161481]
Type: <b>Bug</b>

### Steps to reproduce

1. Create file containing long link, like:

```
https://testing-playground.com/#markup=DwEwlgbgBGILwCIBOB7FAXADAqA7A5gLQQCmSAzmCrogIwDMAdE7bQgHzACGADj4QCsUAI3J4iSEgDMANiQDG6QgFsUpZSVzpyiANoiBC9FADyww4oC6AGn3mjp+4o4AZFJOUwe5AK6eQKDLuUJTo1lBcGsby1ORGJOg+SBHgPGCU8mAEUCQyYOiMUACKPmDhMcqq4FAAFlxIfgBQuD4yMlxQAUHJuCLpEUjyNflGKBHGkjw+4Fy4IFwkhQBqZGM8SAtxWmB+XuQdO5KNIvILp+hgUOgkyjzuJFDKWWDKB96RKWBp5JlQAI4+D7DeThEAkOINLSdQLuPwAfigAEl3jkUORrI0IIEfDx0FwxCgpFIwJl+r1yOgGspwliZDi8RdhD4xK98LhLocHgD8ZduQ9XgAPF4kGnY3Fca7KRqTaZgWbzB5fXyeTQvHI7FmBPIXLgAQigAFEBTwSOA8VApFxMnkxJQnnkAQ8JY68ODMj4tBjSDIQgsTTkBWRMgyqLgbqCSea8sJVurmZ9vr8uvdCgBBVLpX74k1IXASpLHIkkuVQdrCdxUfYqgVQb213L5CI5uWeLg+YwkXaRBIpELY81hl37NKaa4YgFozq5Izx5OSMR8jZhKfCfL9Jehh5z1HkQolWA3CLtw9SHz4fLHZTssRzw9Kj4kLiOwoAVTmIqgMYlC0egXBOqdchlU0eZoW6D9SFQTpIy4Rp9hIf1t25Vs8HzMRJTuDYBiGEZFDGJ52VeWsxQZQ86ipKAUCvdIEVTdBGkta110PDD3A6EhJ0kKlCgAZRIAFeR8FAQCgGIkAaXFLlPfAOmkxthPyQoACUENyOQ5mZRo+SPSUclIdke0keRmXlH91k2UcdlbeRjKreMuAdQFW0GYZrjw8IBMaMSJIuUs23mbZdlpekJS5QExEYsAbSgVp2n8GEkDAJkIrPOVjF6XBfVUry-CHZlMjSYwCPjVQ5ApOUxBiXA4m5RJkmMmQeA6XgyBbK4bkwxZTDNDEN2oLrkWVSjwDGGrSnCDV0FG-KvkbLgQHCR8KPm2afik1LjHM8FLKaUr-wq2t8h-ASwU8Kq4kUBIkigHh2nkR8O2NU0jseLgqHnettVetkwH1fcImEOCPWMcBFA6Kjr3+UoOkHHwt2nRR4zzFCMoRABZBTOh8TJlCRsBhh9MTMPSRo9vK-EYCSB5HxdWAoYp29Xve8FlLIXYXhNM12tuNi43ILz3B8sBCgAYSoqpLjnJL4xIQNBiOi5+s8aSOnI3ZisqwX6UuDxGEaAAhdo5jXfpkL01Ue2uMM6pCF4orAF0KglwoDSfOG8DRSku2bB8mnvPzywoxiyCdGyTNx9EwOCCWmfuch9QAEQS-k3rjqH0mQxojsdcJrzKR4slnEhVwuMQuN2MM1uB8Itq2C5dlYxLkoiIC-BA2CSH0sAeyyTIQGBluczzG2cykEPjbELhhE+xtvX1AA5fj3buICXnjTl6alUG8WWI6P2Mzwy3uX8yp1SeonT5L5k8D0wRujZtsC5QESWEj8y3sAftX1RJ+nwVhRCKaYidJxST1bhoOY7FCI5A6A1JqqFEgLlKFfSIjRwDlVwIoKg4QY6+DWoVBEAAxDaooQEhmSnuISkcwQl3SPqFSJo2ggU0mTM+fNxgukwqgcI5B+xcHCApYwUUghRw8DpQ8HEkEZycggzSt50IdWPviYCkD9QrBkDXMgY9JAT0ppIUsSVYzDm7loB4514h1UaA5B2MjZZ4HSMLKAfEBLhFih8CG6Q0zoBzhaVKEp6yJRDGIPOscPregvFaWysx66eEmGpZhtoZqFVEbscxAJgbXTbLpWW91cRJEuDHb0WlSinVdC6YEAdj4yhmJA-khdqEJWlpHbO7sYZoQiI5VBHjyAIn3OQZC4R-GlW1HKBEPEsjRC7I9TmL1nTu0gqNO2jknRRAxJ3C20y8inHLHsGG1AQhJMbKwg6FTgrikZOvPELoFIoAFkgYmlVWjwJpsvO6D1vrsmASFSeYc7IEmEKcBQEp85ZK+ecpoyFChJ26H4UW4tMYHxdD3ZkU0bpojtEjJeDw4lMI0mIBs+AQJgEaDkhCdVLhwPYvUXY4I4gA2Go2R8N03lDK1GuWBsQLFJHCI3diFJilNOvvTMg-jy6eFZJ8zsrZHJ0zwQVRSSJbjPWXFNPEKpCIInnqg+C-oJzmwMhMEgxYiU3mLmudCGAHwUnKE8joRkTK1Ogl-O0aIs5tD8PqcZnocjiWCGCdSa4wWkUeWkM0oVXHvigPa-Yjr0EXEwYrAW1Ul4ZKQB5QE2LVJtH8XMh4wd9HckoFGrN6l+7BLdDsLQyxWpBIxLDEg+o6KkJCtcW2UIMon32hTMalx-y22MGc8h69cD6SmkcWWMzzSj3Hugz6voRymILoRdiy57yeDDPdVeQ6xDrDUAeLQWcUVjEXP49sTZWofGsWbOIIk1Y30jS8htUA3xgkGYUAAKoopumlqlykdS1RKHxwnGC-HiD8YjlFt0gYURER6br1DStddZBq0W+pyPROSy4xWiRxLABWXUGGylMh+CcIlhG7C4fhZ4REN20oVk0klXcezWIpicM4wKOHuyVF2FyuFUWIrhgIospIwEqPmHrNGXA2RAbfokTwbGgW+VI6In1qBkjCLGBvI++jJFQs-teF1-McWlvjKEGAmDYAD0He-PAuUZHzXM6O4+CzFodF4XSc0Pa0HJ2pKI8E6d+n2e8e7VU1ZJ12pLf4ictFgsPGs3J4pPJ6XpFbcp6zLIpPIxyLsSgUIBNPuITJWRk9CKXGMaOEgVjOm+dBVekpMB3WeAEpHdo0xolWRyEBPNfjjBpaMRM4VS5CzEhE1jHG8YBIoOUGo2TipMopf5GynUE04PKeMwkxoOZyBpEyMC4JnsKJ9ogHvWiGY1o4d86Bn8kGIGgTNlkJzRxtO7EZry+xBNzMdJsXTYeJUlslitlddTjXi1TBqQqOCjY5ISgRCYEaHtMqtYCjEnDob8OuirlCO09sXR1kEQGXJ5K4J+geHK2a6UDs5YG-mj8U9Kn6O05WSIhR9YPR-BU3dx2wQHtzQFyFUBX5kNY8Jkshb74WSfqhqC8iEf9rhI0YAAB6Xg-AhCiHYOEYA6BGqEFulaEgNRAhgiQJwJKyhddvMNzIY3nBwAQE4Iru3nBdSEEIFVPEWQyCu4d2bi3+urc26V9r-gev7oB7IA7p3QA
```
2. Print it in the Terminal (using `cat` for example)
3. Ctrl-click the link (you can see that only a part is underlined, instead of the full link)
4. VS Code fails to open the full link, using instead just some of the lines

### Notes

- Still reproducible when launching VS Code with `--disable-extensions`
- Still reproducible in latest Insiders version (1.72.0-insider ba515cdbb48470c116884deb6de17981d341ec06)
- It used to work on previous versions

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Remote OS version: Linux x64 4.19.128-microsoft-standard
Connection to 'wsl+ubuntu' could not be established

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.82GB (3.92GB free)|
|Process Argv|--crash-reporter-id 03a80955-d460-4b41-ac04-506e2ffda022|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.68GB (3.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.68GB (3.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.68GB (3.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|Memory (System)|12.68GB (3.29GB free)|
|VM|0%|

Connection to 'wsl+ubuntu' could not be established
</details>

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
fc301958:30567733

```

</details>

**Comment by Tyriar** [comment]
We actually have a hard cap currently on link length, though it looks like there may actually be a bug with it:

https://github.com/microsoft/vscode/blob/4e7ad7ed2bffe80a98ab119992a6557e574aa206/src/vs/workbench/contrib/terminal/browser/links/terminalLinkHelpers.ts#L127

`Math.max(2048, cols * 2)` is probably what we meant, but that's still below what you're after.

**Comment by Tyriar** [comment]
The link in the example above is 3247 characters. Since this is such a rare case I recommend just double clicking to select the link and pasting it into the browser for now. I don't want to add a setting as it would rarely see use, and I don't want to support giant links like this as that will end up causing link detection to use a lot of CPU.

I'll fix the `Math.max(2048, cols * 2)` error I noticed in a linked PR.
