### ISSUE TITLE
https://github.com/microsoft/vscode/issues/161468#issue-1382081417

### ISSUE THREAD

**Issue by thisishusseinali** [microsoft/vscode#161469]
[

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1.
2.
](https://github.com/microsoft/vscode/issues/161468#issue-1382081417)

**Comment by thisishusseinali** [comment]
help in this https://github.com/microsoft/vscode/issues/161468#issue-1382081417

**Comment by Dnitin** [comment]
Do you mean every other extension disabled except C/C++ extension ? 
If so, then yes.
