### ISSUE TITLE
Debug console: some output appears in red if it shouldn't

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16149]
- VSCode Version: Version 1.8.0-insider 2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb
- OS Version: macOS

Steps to Reproduce:

- run the node-debug test suite

Observe: once in a while a see some output lines in red instead of black:
![2016-11-28_13-14-22](https://cloud.githubusercontent.com/assets/1898161/20672086/4ec1a59a-b580-11e6-9adb-6bf8b851bd70.png)

How it should look like:

![2016-11-28_15-36-40](https://cloud.githubusercontent.com/assets/1898161/20672139/7a0d2e04-b580-11e6-9c8d-27c573d01e12.png)

**Comment by isidorn** [comment]
I am now more aggresively clearing the class name of the template we are reusing in the tree. Let me know if this fixes your issue
