### ISSUE TITLE
Configure build task does not work in VS Code insiders

### ISSUE THREAD

**Issue by duncanhorn** [microsoft/vscode#161455]
Does this issue occur when all extensions are disabled?: [Yes]/No

- VS Code Version: 1.72.0-insider (user setup)
- OS Version:

Steps to Reproduce:

When I do CTRL+SHIFT+B I get the "No build task to run found. Configure build task..." UI, but when I hit enter, nothing happens. Normally this should show some UI (which I choose to create a shell task) and then create/open the build settings JSON file so that I can edit it appropriately, but I get nothing in the current version.

**Comment by meganrogge** [comment]
I'm not able to reproduce - can you pls provide your tasks.json file?

**Comment by duncanhorn** [comment]
This is the scenario where there is no task.json file yet. Previously if there were no task.json it would take you through a flow to create a task.json file, but this wasn't working for me.

**Comment by duncanhorn** [comment]
![image](https://user-images.githubusercontent.com/7464140/191816237-1ffe0fed-aaf0-4843-8c0b-1dde9e631c6d.png)

If I hit CTRL+SHIFT+B I get that UI, but when I hit enter nothing happens

**Comment by duncanhorn** [comment]
Looks like `Terminal > Configure Tasks...` gives me the UI that I used to get, so that's a reasonable workaround in the meantime
