### ISSUE TITLE
Javascript syntax colouring bug

### ISSUE THREAD

**Issue by rosyatrandom** [Microsoft/vscode#16148]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-47-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.7|
|python|donjayamanne|0.5.3|

---

Steps to Reproduce:

1. make a statement using the new keyword and any constructor
2. pass a function expression into the constructor
3. add whitespace between the constructor name and the brackets.

```
new spaceBeforeArgs (() => {
    const message = "I'm coloured weirdly!";
    console.log(message);
});

```
![vs code colour bug](https://cloud.githubusercontent.com/assets/5188481/20671440/4b917f40-b575-11e6-9712-2c7e2f4141fc.png)

**Comment by mjbvz** [comment]
I confirmed this bug in 1.7.2, but see the correct colorization in 1.8 insiders builds, so I believe this has already been fixed:

![screen shot 2016-11-28 at 12 52 58 pm](https://cloud.githubusercontent.com/assets/12821956/20685468/6c955f74-b569-11e6-81e9-40815429999f.png)

Please give a recent insiders build a try if you have a chance and let us know if you still see this issue or notice any other colorization problems.

Thanks.
