### ISSUE TITLE
Wrong formatting on paste [Ruby]

### ISSUE THREAD

**Issue by amerov** [microsoft/vscode#161588]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2
- OS Version: Fedora Linux 36

format on paste: enabled
no extensions

Steps to Reproduce:

1. C-c
2. C-v

https://user-images.githubusercontent.com/196747/191953096-8dec887e-f694-4985-a531-010b05bc803e.mp4

**Comment by rebornix** [comment]
Currently the auto indent feature in VS Code is regex based, which doesn't really understand the scope (function, statement) etc. Formatting works more consistently in this scenario, so I would recommend to enable formatting on type or save. Closing this as we don't expect to get around it in the near future.
