### ISSUE TITLE
TypeScript/JavaScript IntelliSense not working

### ISSUE THREAD

**Issue by PhilWaters** [microsoft/vscode#161570]
Type: <b>Bug</b>

IntelliSense for TypeScript/JavaScript runs fine for a 5 to 10 minutes then crashes. Restarting VS Code fixes the issue but it happens again quite quickly.

I've disabled all extensions and tried the Insiders version. Both have the exact same issue.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:07:15.900Z)
OS version: Darwin arm64 21.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (2.69GB free)|
|Process Argv|--crash-reporter-id 4122833f-cab4-462d-a6eb-8ef23bad170f|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
40g7c324:30573242

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by mjbvz** [comment]
If you are still seeing it, please try collecting the TS Server log from the crashed instance:

1. Set `"typescript.tsserver.log": "verbose"`
1. Restart VS Code and reproduce the problem
1. Open the `TypeScript` section of the output panel
1. At the very top, find the first line that prints to path to the semantic error log file. It should look something like:

    ```
    [Info  - 19:54:59.247] <semantic> Log file: /Users/matb/Library/Application Support/Code - Insiders/logs/20200213T104930/exthost55/vscode.typescript-language-features/tsserver-log-ZT2zau/tsserver.log
    ```

    That file contains the typescript logs.

Look through that log file for the first error or stack trace you see. If you can share the log, I can also take a look to see if anything stands out

 > **⚠️Warning:** The TypeScript log may include information from your workspace, including file paths and source code. If you have any concerns about posting this publicly on Github, just let me know and we can arrange something else. On our side, we only use these logs to investigate issues like this

**Comment by floifydaniel** [comment]
@mjbvz I'm also running into this issue. With all extensions disabled and following your instructions, my log files all contain similar contents:

```sh
cat: /Users/me/Library/Application: No such file or directory
cat: Support/Code/logs/20220926T112234/exthost1/vscode.typescript-language-features/tsserver-log-6edBH0/tsserver.log: No such file or directory
```

The error emitted prior looks like this:

```sh
Error  - 17:23:57.2] TSServer exited. Code: null. Signal: SIGABRT
[Info  - 17:23:57.3] TSServer log file: /Users/me/Library/Application Support/Code/logs/20220926T112234/exthost1/vscode.typescript-language-features/tsserver-log-foGDxV/tsserver.log
[Info  - 17:23:57.3] Starting TS Server
[Info  - 17:23:57.3] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js
[Info  - 17:23:57.3] <syntax> Log file: /Users/me/Library/Application Support/Code/logs/20220926T112234/exthost1/vscode.typescript-language-features/tsserver-log-L0wPVL/tsserver.log
[Info  - 17:23:57.3] <syntax> Forking...
[Info  - 17:23:57.4] <syntax> Starting...
[Info  - 17:23:57.4] <semantic> Log file: /Users/me/Library/Application Support/Code/logs/20220926T112234/exthost1/vscode.typescript-language-features/tsserver-log-6edBH0/tsserver.log
[Info  - 17:23:57.4] <semantic> Forking...
[Info  - 17:23:57.4] <semantic> Starting...
```

**Comment by PhilWaters** [comment]
[tsserver.log](https://github.com/microsoft/vscode/files/9656899/tsserver.log)

Here's the output and attached is the error log. Hopefully that helps

[Info  - 14:27:50.813] <syntax> Log file: /Users/philwaters/Library/Application Support/Code - Insiders/logs/20220927T152400/exthost1/vscode.typescript-language-features/tsserver-log-HxTDbK/tsserver.log
[Info  - 14:27:50.813] <syntax> Forking...
[Info  - 14:27:50.815] <syntax> Starting...
[Info  - 14:27:50.815] <semantic> Log file: /Users/philwaters/Library/Application Support/Code - Insiders/logs/20220927T152400/exthost1/vscode.typescript-language-features/tsserver-log-V3dN11/tsserver.log
[Info  - 14:27:50.815] <semantic> Forking...
[Info  - 14:27:50.815] <semantic> Starting...
[Error  - 14:28:24.510] TSServer exited. Code: null. Signal: SIGABRT
[Info  - 14:28:24.511] TSServer log file: /Users/philwaters/Library/Application Support/Code - Insiders/logs/20220927T152400/exthost1/vscode.typescript-language-features/tsserver-log-V3dN11/tsserver.log

**Comment by diminutivesloop** [comment]
I had success fixing this issue by disabling the IntelliCode extension.

**Comment by PhilWaters** [comment]
I increased Max TS Server Memory which seems to have fixed the problem
