### ISSUE TITLE
Suggest widget glitch 

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16154]
1. Open suggest widget - type something
2. Esc to cancel suggest widget
3. Backspace to delete some characters -> notice rendering glitch

![screen shot 2016-11-28 at 18 10 16](https://cloud.githubusercontent.com/assets/1926584/20678136/ee8fd92e-b595-11e6-9da7-ad71d2c49605.png)

**Comment by joaomoreno** [comment]
@jrieken Please review, this was introduced with the last changes to the suggest world.
