### ISSUE TITLE
Format Code no longer available for JSON files

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#16150]
- VSCode Version: Code - Insiders 1.8.0-insider (2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb, 2016-11-28T07:05:06.507Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.4|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.6.5|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.0.0|
|HTMLHint|mkaufman|0.0.3|
|vscode-stylefmt|mrmlnc|2.1.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.0.2|
|stylelint|shinnn|0.20.2|
|theme-tesla|smlombardi|5.2.0|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. open JSON file where all the items are in a single line, such as [this one](http://jmp.sh/H5O8lKB)
2. try invoking "format code" `shift-option-f`
3. code is not formatted but a `Ï` is typed
4. try using the command menu: only "format css" is available.

This is new, previous versions of Insider worked fine.

**Comment by mjbvz** [comment]
Please try out the latest insiders builds. One of the insiders builds had some problems around json that I believe have since been resolved.

Thanks

**Comment by smlombardi** [comment]
Yes, it works again.  Thanks.

**Comment by itamark** [comment]
Where are the insider builds?
By the way - this is not just in JSON - it's also in typescript.
