### ISSUE TITLE
Should detect package manager with preferred-pm instead of which-pm

### ISSUE THREAD

**Issue by nickmccurdy** [microsoft/vscode#161579]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: macOS 12.6

I noticed that [`preferred-pm.ts`](https://github.com/microsoft/vscode/blob/main/extensions/npm/src/preferred-pm.ts) uses `which-pm`, which only checks for which package manager installed `node_modules`. We should probably use `preferred-pm` instead, as it uses `which-pm` but checks for lockfiles first, so you can still use the package manager detection before installing anything. This would also make VSCode's installation behavior more consistent with other tools using that package, such as pnpm and Astro.

**Comment by meganrogge** [comment]
Sorry for applying the help wanted label here. I was not aware of the historical context
