### ISSUE TITLE
command + period not working!!!!!!!!!!

### ISSUE THREAD

**Issue by eret9616** [microsoft/vscode#161555]
Type: <b>Bug</b>

i set command + period to a keyboard shortcut, after the update, this shortcut is not working

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 6|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv|--crash-reporter-id bfff7978-4783-4e67-b3ce-e90e45a37f06|
|Screen Reader|yes|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the guidance at https://github.com/microsoft/vscode/wiki/Keybinding-Issues to investigate.

**Comment by eret9616** [comment]
This is the troubleshooting screenshotwhen press command + . :
<img width="985" alt="image" src="https://user-images.githubusercontent.com/12445095/191924661-d12bceff-9a6f-4bff-9233-ff3035d4c4a1.png">


This is the keyboard shortcut I set,  
<img width="927" alt="image" src="https://user-images.githubusercontent.com/12445095/191924794-42facae3-dd0b-4096-ac1b-dbefaa4b58fa.png">

**Comment by eret9616** [comment]
After update karabiner-elements, this problem solved
