### ISSUE TITLE
Extensions icons shrink on a particular width

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161571]
Decrease the width of the extension viewlet slowly until you notice that the extension icons have been shrunk.
I find this a bit weird. In no other place do we shrink icon size to reduce space.
Was this intentional?

I suggest to either hide them or show them at full size.

![Screenshot 2022-09-23 at 10 37 15](https://user-images.githubusercontent.com/1926584/191922844-7c6c962b-bbce-47d0-b0d1-7a04baf6305f.png)

cc @benibenj

**Comment by sandy081** [comment]
It is intentional and as designed. Since Icons are important to represent extensions we do not want to hide them but when the space is less we shrink them.
