### ISSUE TITLE
Cannot enable extension for workspace only

### ISSUE THREAD

**Issue by lluchkaa** [microsoft/vscode#161574]
Type: <b>Bug</b>

1. Disable extension
2. Enable extension (workspace)

**Expected result**: Extension runs inside the current workspace
**Actual result**: Error message
<img width="448" alt="Screenshot 2022-09-17 at 00 08 45" src="https://user-images.githubusercontent.com/37471864/190748470-374e6684-f06b-45a6-b477-47927aff132e.png"> 

Extension version: 0.50.0
VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (3.54GB free)|
|Process Argv|--crash-reporter-id d370842e-a6db-4438-a8a2-60289b879aef|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30567733

```

</details>

**Comment by alexr00** [comment]
👍 Moved issue over to VS Code.

**Comment by lluchkaa** [comment]
I confirm that it works for me in 1.73.0. Closing this issue
