### ISSUE TITLE
File links containing "[" and "]" don't work in terminal

### ISSUE THREAD

**Issue by alex-statsig** [microsoft/vscode#161543]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.0-insider
- OS Version: macOS Big Sur 11.6

Steps to Reproduce:

1. echo a link in terminal containing "[" or "]" characters (ex. `echo /Users/alex/dev/statsig/console/pages/[company_id]/dashboards/[dashboard].tsx`)
2. Try to cmd+click the link, observe that it is split on those characters. For example, `/Users/alex/dev/statsig/console/pages/[company_id]/dashboards/[dashboard].tsx` links to `/Users/alex/dev/statsig/console/pages/`, `company_id`, `/dashboards/`, `dashboard`, and `.tsx`. In reality this is one valid path (nextjs uses "[ ]" to identify parameters in URLs)
<img width="526" alt="Screen Shot 2022-09-22 at 5 12 00 PM" src="https://user-images.githubusercontent.com/77301670/191872189-936ec0e3-6460-4fdc-9d71-7c652e58d4e5.png">

**Comment by Tyriar** [comment]
This works for urls:

![Image](https://user-images.githubusercontent.com/2193314/205705548-e7fef861-1e34-4372-a130-154ff4b2d4d9.png)

Not local paths:


![Image](https://user-images.githubusercontent.com/2193314/205705714-e87b6d09-dfde-4d10-9f4e-84d74d655300.png)

**Comment by Tyriar** [comment]
https://github.com/microsoft/vscode/issues/161521 reported that it does (kind of) work:

![image](https://user-images.githubusercontent.com/2193314/205706096-3dfe69b3-f1b4-4cda-a334-4e0f4b087957.png)

We would need to review all link detectors for this.

**Comment by Tyriar** [comment]
This happens with local links because [] are currently excluded chars:

https://github.com/microsoft/vscode/blob/78b2df948783c6094571635088ac625bbf73aaba/src/vs/workbench/contrib/terminal/browser/links/terminalLocalLinkDetector.ts#L39-L42
