### ISSUE TITLE
VSCode deleted my project when I launched debugging: terminal should have been cleared when starting a debug session

### ISSUE THREAD

**Issue by NicolasM-Forsk** [microsoft/vscode#161582]
- VS Code Version: 1.71.2
- OS Version: Windows 11 + WSL 2 (Ubuntu 20.04)

VSCode deleted my project! 

Steps to Reproduce:

1. Create a python project with this config
    ```
            {
                "name": "Python: Current File",
                "type": "python",
                "request": "launch",
                "program": "${file}",
                "console": "integratedTerminal",
                "justMyCode": false
            },
    ```
3. Start typing something in the terminal, but do not press enter. Ex: rm -fr toto
4. Launch debug current file: it executes unwanted code. Ex:
```
**rm -fr toto cd /home/dev/projects/test**; /usr/bin/env /home/dev/projects/test/.venv/bin/python /home/dev/.vscode-server/extensions/ms-python.python-2022.14.0/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher 33451 -- /home/dev/projects/test/patch_10_11.py 
```

**Comment by roblourens** [comment]
Debug always creates a new terminal - It looks like that would happen if you type your own command.

@meganrogge I create a terminal, and use sendText when I reuse it, is there a terminal escape code I can send that will clear the current line? I don't think I want to clear the whole thing.

**Comment by meganrogge** [comment]
@roblourens there is not, but you could do what we now do for run recent command when you have input and send the sequence for ctrl + c

**Comment by roblourens** [comment]
That would work, what is that sequence?

**Comment by meganrogge** [comment]
https://github.com/microsoft/vscode/blob/244e4feb031f22c0e1582189e5850d8b5c9f0907/src/vs/workbench/contrib/terminal/browser/terminalRunRecentQuickPick.ts#L292

**Comment by hakobpogh** [comment]
I believe it should not be on the users. You need to clear the terminal line before running the debug command. It's awful.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/106743
