### ISSUE TITLE
Allow terminal quick fixes to return simple commands to run from getActions

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161599]
`getActions` returns `IAction[] | undefined`. This is fine, but it means that every action chooses its own format for what to run. I suggest we change this to return a `IAction[] | string | undefined`, and when it's a string an action is created with the label `Run: git status`, where the part after the colon is exactly what will get run.

I expect this will also increase trust in the tool as the push set upstream quick fix currently has a label of `Git push <branch>`, whereas it would be a lot clearer what it's actually doing if it read `Run: git push --set-upstream origin <branch>`

**Comment by meganrogge** [comment]
This will decrease code duplication

**Comment by meganrogge** [comment]
I don't think we want to allow actions to be undefined, but adding `string` makes sense

**Comment by meganrogge** [comment]
@Tyriar started working on this, but realized your vision might be diff't than mine here, so will leave with you. 

We'll still need the provider to pass in the `run` callback for instance, so not sure how just a `string` will work

**Comment by Tyriar** [comment]
@meganrogge the idea was basically to change this:

```ts
export interface ITerminalQuickFixOptions {
	getQuickFixes: QuickFixCallback;
}
export type QuickFixCallback = (matchResult: QuickFixMatchResult, command: ITerminalCommand) => ITerminalQuickFixAction[] | undefined;
export interface ITerminalQuickFixAction extends IAction {
	commandToRunInTerminal?: string;
	addNewLine?: boolean;
}
```

To something like:

```ts
export interface ITerminalQuickFixOptions {
	getQuickFixes: QuickFixCallback;
}
export type QuickFixCallback = (matchResult: QuickFixMatchResult, command: ITerminalCommand) => QuickFixAction[] | undefined;
export type QuickFixAction = ITerminalQuickFixAction | ITerminalQuickFixRunAction | ITerminalQuickFixOpenLinkAction
export interface ITerminalQuickFixAction extends IAction {
	commandToRunInTerminal?: string;
	addNewLine?: boolean;
}
export interface ITerminalQuickFixRunAction {
	type: 'run';
	command: string;
}
export interface ITerminalQuickFixOpenLinkAction {
	type: 'openLink';
	link: string;
}
```

Notice how the last 2 don't extend `IAction`, we would leave that up to a core component
