### ISSUE TITLE
Relative HTML image tags in markdown are not working

### ISSUE THREAD

**Issue by RedWolves** [Microsoft/vscode#1615]
I think this relates to #803 but seems to be a bit different (or an update hasn't been deployed with the fix). 

I have a project that is the entire web site and within there is a folder where we draft blog posts in markdown.  So the folder structure looks like this:

```
app
  ⌞ posts
    ⌞ 2016
      ⌞ 01
        ⌞ blog-slug
          ⌞ index.md
          ⌞ image.png
```

When I try to reference this image in html it appears as a broken image:

```
<img src="image.png" width="100%">
```

in dev tools I see it's looking for the image in "file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/electron-browser/image.png" but only references the image by name in the rendered html. (see image)

<img width="366" alt="screen shot 2015-12-23 at 8 29 27 am" src="https://cloud.githubusercontent.com/assets/129322/11977286/5a72e720-a94f-11e5-9192-6166777cb895.png">

when referenced as markdown it renders fine:

```
![image](image.png)
```

In dev tools it has the complete file path to the image. 

<img width="384" alt="screen shot 2015-12-23 at 8 30 37 am" src="https://cloud.githubusercontent.com/assets/129322/11977305/7c34fe16-a94f-11e5-9d20-af16b39d0573.png">

**Comment by bpasero** [comment]
Please use markdown for now as workaround.

**Comment by RedWolves** [comment]
Yeah I used markdown to make sure I called the image right then used html because the image needs to be 100%.  Once I know the image was good I could live with the broken image.  That was my workaround for now.

**Comment by mtompkins** [comment]
A bit disappointing this is still on the to-do list.

**Comment by bpasero** [comment]
This is still an issue even with our new markdown extension.

**Comment by mjbvz** [comment]
I'm unable to repo this problem anymore.

![screen shot 2016-09-13 at 4 01 43 pm](https://cloud.githubusercontent.com/assets/12821956/18494523/68b47054-79cb-11e6-8af2-4b234e2e172f.png)

I also tried opening only the markdown file without a project, and this also worked.

I believe 0a386aea9cd22a246cf3b6a23a378cd7ae9c2d3a may have fixed this by adding a `<base>` tag to the markdown preview html.

**Comment by mjbvz** [comment]
Closing as fixed by https://github.com/Microsoft/vscode/commit/0a386aea9cd22a246cf3b6a23a378cd7ae9c2d3a. Please let me know if you are still running into the problem.

Thanks.
