### ISSUE TITLE
"Prompt to Save Files Before Stash" not working

### ISSUE THREAD

**Issue by aldrichdev** [microsoft/vscode#161517]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.71.2
- OS Version: Windows 10

Steps to Reproduce:

1. Change "Prompt to Save Files Before Stash" setting to **always** in Preferences
2. Make a change to a file but don't save it.
3. In the terminal, ran `git stash push -m "TestStash"`
4. No prompt occurs, the stash is created even though I have unsaved changes.
```Saved working directory and index state On testbranch: TestStash```

**Comment by gjsjohnmurray** [comment]
I wouldn't expect that setting to have any effect on git commands submitted in  terminal. What happens when you initiate the stash from Command Palette or from the ... menu of the Source Control view?

**Comment by aldrichdev** [comment]
Ah, so a stash via the terminal is not supported. That's a shame. I'll close this
