### ISSUE TITLE
Should the free port quick fix match on failed commands only?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161594]
Currently there's no exit check:

https://github.com/microsoft/vscode/blob/7872b085ca29a35ef63d1b6accece221ec5c748b/src/vs/workbench/contrib/terminal/browser/terminalBaseContextualActions.ts#L44-L67

**Comment by meganrogge** [comment]
IMO, no because when this happens (with or without exit), we know what the user wants to do

**Comment by Tyriar** [comment]
How would it match without an exit? Isn't that a requirement for the quick fixes to show up?

**Comment by meganrogge** [comment]
Perhaps after command execution occurs, we could wait a few seconds then check if there's no data being produced but command finished hasn't occurred and then scan the output for a match.
