### ISSUE TITLE
Improved sorting criteria for extensions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16156]
We can currently sort extensions by rating or install count, both are not quite adequate for sorting by "popularity". Part of the problem is that the install count includes updates.

A (presumably additional) sort criteria useful for both "top 10" list and the extension viewlet should better reflect how popular an extension is at present - as opposed to over its entire lifespan.

With such a sort criteria we should hopefully be able to phase out some of our curated lists of extensions which take time to maintain and can be slow to pay tribute to the rising stars.

Related to #15159. Part of the outcome of #15383. /cc @joaomoreno @Tyriar

**Comment by waderyan** [comment]
Ping @hamenon

Do we think trending could solve this? MP team has fine tuned this. We could look at trending for the last month, which would give us how "popular an extensions is at present"

**Comment by hamenon** [comment]
Yup that was one of the primary things that Trending was looking to solve. The way I think of the split right now is as follows:

- Featured - Manually curated - Extensions that we want to highlight on the Marketplace
- Most Popular - Sorted by downloads - Helps address new users to VS Code extensions to understand whats popular on the Marketplace
- Trending - Sorted by growth - Helps address the question of whats popular now
- Recently Added - Sorted by upload date - Helps address the question of whats new on the Marketplace

We do provide sort options for each of the above in the search and category pages as well.

We are monitoring the performance of the trending extensions currently and trying to see if any tweaks to the algorithm are necessary or if it needs to incorporate additional factors like Page views or rating etc.

**Comment by chrmarti** [comment]
@hamenon With "popular" I really mean "most actively used in the field today". The download count we currently use in the product gives too much weight to previously popular extensions. I'm not sure if with "trending" you want to list the "hot and new", which would not be what we are looking for, this list would presumably change quickly.

Our goal is to have a good sorting criteria we can use in the product for (new) users interested in the must-haves for daily work.

**Comment by hamenon** [comment]
It sounds to me like you want a sort order based on active installs of extensions in the field today? Is that right? Unfortunately we don't get active client install data in the Marketplace today. Since once the extension is downloaded from the Marketplace they don't talk back to the service. I believe this should be trackable within VS Code telemetry/usage number though? We could in fact base it on extension activations within the client as well. If there was some way we could query that (API etc) from VSCode then we could have a list based on active installs.

**Comment by chrmarti** [comment]
Extension activation might not be a good measure either because extensions can register to activate on startup and these would the win against others that are more specific in their activation triggers.

The number of active application installs where a particular extension is installed might be a better measure. That would require us to extract that data from telemetry though.

@hamenon What is the current definition of 'trending'? Is it trying to capture the 'hot & new' extensions?

**Comment by hamenon** [comment]
@chrmarti It is intended to capture the growing extensions. We primarily look at extension growth and see which extensions are trending in the specified timeline. We do have a threshold to avoid just recently added extensions from showing up and thereby duplicating the Recently Added list. 

Like you mentioned the number of active application installs would be a great measure to have as its a more accurate representation of popularity. But we don't have that information on Marketplace for VS Code today as the extensions don't contact our service after install/update.

**Comment by usernamehw** [comment]
#### Add number of active users of extension (extension was activated at least once in 7(n) days). 
It can help solving some problems:

* Extension was implemented in the core editor and now not needed
* Extension was good at the start, but now dropped (not maintained)
* Extension was good at the start, but after dramatically changed it functionality
* Extension was and is good, but now has a competitor that does it better
* Extension was bad from the start, but people downloaded it => didn't have the microsoft account (or were lazy) => removed extension not giving it feedback or rating on marketplace
* ...

**Comment by egamma** [comment]
The sorting has been improved some time ago. Closing this issue.
