### ISSUE TITLE
Terminal quick fix should remain after being dismissed without action

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161596]
![Recording 2022-09-23 at 05 56 47](https://user-images.githubusercontent.com/2193314/191965196-ff58cb90-2a06-4f80-95c2-6747718d8518.gif)

**Comment by meganrogge** [comment]
I thought we wanted to hide this after any interaction since we don't yet have a dismiss action

**Comment by Tyriar** [comment]
It doesn't seem to be possible to dismiss the editor one so I think we should align:

![image](https://user-images.githubusercontent.com/2193314/191999531-3cf9f078-6710-4b52-bc3c-3e316fdcd725.png)
