### ISSUE TITLE
Use a background color on the terminal quick fix icon

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161598]
Otherwise the decoration underneath bleeds through:

![image](https://user-images.githubusercontent.com/2193314/191965671-3ca87edb-3c5b-47e6-a84c-dd4d754c1c16.png)

Since it's partially transparent you can also see the circle outline on the yellow part

**Comment by meganrogge** [comment]
![Image](https://user-images.githubusercontent.com/29464607/192385343-d44c8b4b-c398-4d69-ac53-0e8bce752eef.png)

background is below the other decoration
