### ISSUE TITLE
Menu no accessible in second window

### ISSUE THREAD

**Issue by jb-alvarado** [microsoft/vscode#161559]
Type: <b>Bug</b>

Since 2-3 updates it is, under some circumstances, not possible to access the menu in a second window. My system is Fedora Linux 36 (Workstation Edition) with Gnome Desktop.

Steps to reproduce:
* choice file -> new window
* immediately after the seconds window is open, move it to a second screen
* try to open file menu in new window, it will not work

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:12:14.256Z)
OS version: Linux x64 5.19.9-200.fc36.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900 CPU @ 3.10GHz (16 x 4604)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 1|
|Memory (System)|31.19GB (21.24GB free)|
|Process Argv|--unity-launch --crash-reporter-id a59b65be-882a-45db-8f90-1eb6c74d97b1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by deepak1556** [comment]
Please check if the issue is present with latest stable `1.85`

**Comment by jb-alvarado** [comment]
Thanks for reminding! Since longer I have not notice this issue any more, so I guess we can close here.
