### ISSUE TITLE
Code will crash when regular expression `/-- ([a-z0-9\- ]+)+\n/` is pasted into the search dialog

### ISSUE THREAD

**Issue by tommasopeduzzi** [microsoft/vscode#161522]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:1.71.2 74b1f979648cc44d385a2286793c226e611f59e7 x64
- OS Version: 5.15.59-1-MANJARO

Steps to Reproduce:

1. Press CTRL+F or open search dialog.
2. Paste the regular expression `/-- ([a-z0-9\- ]+)+\n/` into the dialog and activate regular expressions.
3. The window will become unresponsive and code will crash.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/30874
