### ISSUE TITLE
Git similar command quick fix should match on multiple similar commands

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161595]
This currently doesn't give a quick fix:

![image](https://user-images.githubusercontent.com/2193314/191964391-c97d5369-0601-48fa-aa44-84bd256dcd6d.png)

This is a good candidate to show multiple actions

**Comment by meganrogge** [comment]
wouldn't this be one action but have a submenu?

**Comment by Tyriar** [comment]
That would be harder to use imo, we will probably also want to move to the editor's quick fix UI which doesn't do this afaik:

![image](https://user-images.githubusercontent.com/2193314/192052406-476d42dd-0ed5-462a-bc57-0ec5b827ccb1.png)

**Comment by meganrogge** [comment]
labeled it a feature so I remember to include it in the TPI
