### ISSUE TITLE
JIS (Japanese) Keyboard Layout: Define Keybinding popup window shows wrong key

### ISSUE THREAD

**Issue by ypresto** [Microsoft/vscode#16157]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra 10.12.1
- Keyboard layout: JIS (Japanese)

Steps to Reproduce:

1. Open keybindings.json
2. Press ⌘K ⌘K
3. Some of key combinations are shown as wrong key

Example of wrong combinations:

|Pressed|Expected|Actual|
|---|---|---|
|@|@|[|
|Shift+1|!|Shift+1|
|Shift+:|*|Shift+'|
|Shift+Cmd+:|Cmd+*|Shift+Cmd+;|

**Comment by alexandrudima** [comment]
@ypresto Starting with today's insiders version (i.e. after PR #22894 aka #17521) we have changed how keybinding dispatching works on OSX from using `e.keyCode` to using `e.code` (i.e. scan codes). 

Can you please download the insider's version and check if we work now correctly (i.e. labels reflect what you press).

In trying to reproduce, I have installed the Japanese keyboard layout on OS X and tried with both Hiragana and Katakana, but for me, the Keyboard Viewer always seem to reflect the US keys, and things appear to be working correctly. Can you perhaps explain in greater detail what steps I need to take to get this OS X system in the same state as yours. e.g. of the Keyboard Viewer:

![screen shot 2017-03-24 at 12 38 31](https://cloud.githubusercontent.com/assets/5047891/24292722/d307b2e0-108e-11e7-833d-a0032c11890e.png)

**Comment by ypresto** [comment]
My example of Keyboard Viewer:
![image](https://cloud.githubusercontent.com/assets/400558/24454258/2cfea886-14c6-11e7-8b62-110bb71f9c41.png)

It reproduces only when I use Japanese IME (even if alphabetical (英字 / eisuu) input is used).
But it does not reproduce when I use U.S. IME.

![image](https://cloud.githubusercontent.com/assets/400558/24454344/75332e92-14c6-11e7-860d-7d3ac028e092.png)

**Comment by ypresto** [comment]
Using Keyboard Viewer or hardware key does not change result in my env.

**Comment by alexandrudima** [comment]
@ypresto Thanks to the help of @landonepps (through PR https://github.com/Microsoft/node-native-keymap/pull/8), I believe we now support Japanese IME on JIS keyboards on OSX a lot better.

Sorry for the constant noise, could you please try again using a more recent VS Code version (I think the fix is also in stable 1.12, but best would be if you could check [using the Insiders build](https://code.visualstudio.com/insiders))

The reason I am asking is because I only have access to ANSI and ISO keyboards, and not to a JIS keyboard, and OSX has very different behaviours on the same input method if different physical keyboard types are used.

**Comment by landonepps** [comment]
@alexandrudima That's great news. I'm currently on vacation without a computer now, but I'll check if it works with a hardware keyboard when I get back.

**Comment by landonepps** [comment]
I just tested all the listed combinations, and I believe this issue can now be closed.

I'm not sure why @ypresto listed the expected value of `shift+1` as `!` and `shift+:` as `*`. The currently displayed values `shift+1` and `shift+[Quote]` match the respective physical key combination, which I think is logical.

`@` displays as `[BracketLeft]` which, while not ideal, does indicate beneath and in a tooltip that for the current keyboard layout the user should press `@`.
<img width="415" alt="screen shot 2017-05-08 at 15 44 45" src="https://cloud.githubusercontent.com/assets/1572318/25793153/d552fefc-3405-11e7-9c7e-e38151f00ba0.png">

**Comment by alexandrudima** [comment]
Thank you @landonepps 

Indeed, when a key is *ambiguous* (i.e. differs from the US keyboard layout), we generate scan code based keybindings, so this is expected.

**Comment by ypresto** [comment]
I tried insider version:

![image](https://cloud.githubusercontent.com/assets/400558/25956236/24c1a9c8-36a6-11e7-8af5-2bb0dd2afd90.png)

Wow! It is working like a charm..!! Thank you for fix!
