### ISSUE TITLE
Consider other terminal quick fixes

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161538]
With https://github.com/microsoft/vscode/issues/151937 we're getting some initial terminal quick fixes. We have a bunch more ideas, let's use this issue to track adding more at a later date when we have more information on how the feature is received.

**Comment by meganrogge** [comment]
Also want to consider the setting to disable one or more of these

**Comment by andrewbranch** [comment]
The open URL one (the only one I’ve seen so far) was a really pleasant surprise and I immediately adopted it into my workflow for opening a GitHub PR after pushing a new branch. Another one I would love to see is opening files with merge conflicts:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/3277153/195899951-53b07fad-c1dc-401d-9ae5-e7ba8a99e2a1.png">

**Comment by Tyriar** [comment]
@andrewbranch great idea!

**Comment by meganrogge** [comment]
I think this can be closed since we have individual issues tracking ideas
