### ISSUE TITLE
Monaco editor performance in virtualized list

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#161539]
While looking into @Tyriar 's experiment with webgl in editor, we discussed how we can improve the scrolling performance of notebook as currently the monaco editor creation is not buttery smooth due to the fact that we are rendering multiple in a virtualized list view. For example, if we open `.vscode/notebooks/endgame.github-issues` and scroll up and down 

1. Notebook cell list create M cell templates, each of which contains a monaco editor
2. Scroll down
3. The first visible cell gets disposed, the DOM and monaco editor for the first cell is not removed from the DOM tree, instead it will be reused
4. We reuse the first cell's template, set a new text model from the cell scrolled into view to the monaco editor
5. Step 2-4 repeats

Even though we already try to reuse the monaco editor, since we are calling `ICodeEditor#setModel` each time, the editor actually will create a view from scratch again. It includes checking bounding rects, validation positions etc, and trigger browser's recalculate styles and layout

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/876920/191866587-67cd1e37-f771-4f81-ab1f-4abae237db92.png">

The perf can sometimes be worse when you are comparing notebooks in a diff editor, which are list of text diff editors.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/876920/192014384-8c33ba21-7db3-43a4-8133-0b656d767e99.png">

While we are looking into how we can use the webgl experiment to improve the experience, I wonder if there is anything we can do in current editor to help improve the scrolling speed. We are creating multiple monaco editors, but good things are

* We reuse them when possible, so the whole DOM node for monaco editor are not destroyed and re-created
* All editors are vertically aligned, so they have the same `x` offset in the window/viewport

I'd love to hear your ideas/thoughts on this @alexdima @hediet , thanks in advance!

**Comment by alexdima** [comment]
This looks pretty bad. We should look into aligning the rendering phases across editor instances. Currently, each editor's rendering is optimized by itself to first render the text, do a forced layout to be able to convert positions -> pixels, and then render the rest of the view. But there is no orchestrating mechanism across editor instances and we should probably do something like: render the text for all editors, do a forced layout to be able to convert positions -> pixels across all editors, and then render the rest of the view for all editors. Such an orchestration would help even the regular diff editor.

There's a lot of forced layouts going on in the second screenshot 😢 . It's hard to tell from the screenshot, are you by any chance calling `layout()` without passing in the desired editor size?

**Comment by alexdima** [comment]
@rebornix You can look into passing in `postponeRendering:true` in the `layout` calls i.e. https://github.com/microsoft/vscode/pull/198957
