### ISSUE TITLE
Regex of user's email secret is incorrect

### ISSUE THREAD

**Issue by mustard-mh** [microsoft/vscode#161565]
Does this issue occur when all extensions are disabled?: Yes

The email telemetry security regex incorrectly treats near everything that includes `@xxx` as email

|IMG (see last two example)|
|-|
|<img width="992" alt="image" src="https://user-images.githubusercontent.com/20944364/191914408-482a2d11-3e69-4fd0-85bf-44f0f87abb43.png">|

https://github.com/microsoft/vscode/blob/a8cb6baddf5bae653835565ad7d6748d0edeef7e/src/vs/platform/telemetry/common/telemetryService.ts#L202-L214

- VS Code Version: From sources
- OS Version:

Steps to Reproduce:

1. Copy regex of email and test it

**Comment by mustard-mh** [comment]
I created a fix PR https://github.com/microsoft/vscode/pull/161567

**Comment by lramos15** [comment]
Not sure I follow. Can you give me an example of an email that would not be redacted here?

**Comment by mustard-mh** [comment]
@lramos15  Sorry for replying so late.

The issue is not about old regex not covering some email, but it's over-covered.

As you can see from the image in issue description, old regex marks near everything that contains `@` as an email. Which is not correct and does not align with its comment `matches @*.site`

<img width="795" alt="image" src="https://user-images.githubusercontent.com/20944364/192949440-07633e7f-0f10-4edd-babe-81328df25215.png">

**Comment by babaralishah** [comment]
Hi 
I am on Angular

And using the below regex:

`'^[a-z0-9]+([._-]?[a-z0-9]+)+@[a-z0-9]+([._-]?[a-z0-9]+)+\\.[a-z]{2,3}$'`

But its not fulfilling my requirement, my requirement is below:

`saa5@me-d_d_u.co`

please anyone tell me, why this regex is not working for my above mentioned case.

Regards
Babar Ali Shah
