### ISSUE TITLE
Search Results shown as tree: indent guide highlighting gets messy

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#161607]
Type: <b>Bug</b>

![junk](https://user-images.githubusercontent.com/6726799/191982699-8831fbee-3db1-44eb-a191-cd2ae85f48fe.gif)

VS Code version: Code - Insiders 1.72.0-insider (1f148906f1ece5c83a60ed8e211c9f387188dca3, 2022-09-23T05:17:37.024Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

/assign @andreamah

**Comment by Gabriel-Alves-Cunha** [comment]
Completely agree on this. Tree ident guide highlights are pretty awful throughout the hole app, except the editor itself because of the color lines.

**Comment by joaomoreno** [comment]
Great find!
