### ISSUE TITLE
Menu separator lines no longer visible

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#161643]
Type: <b>Bug</b>

Light+ on Insiders

![image](https://user-images.githubusercontent.com/6726799/192053045-07b34f82-d6c9-41cf-a693-b95f8d838903.png)

Light+ on Stable

![image](https://user-images.githubusercontent.com/6726799/192053138-22445ee0-6827-471f-a510-e91574291c2e.png)

Dark+ on Insiders:

![image](https://user-images.githubusercontent.com/6726799/192053268-78c2a88f-5373-4167-b4cf-76cb577b8c58.png)

Dark+ on Stable:

![image](https://user-images.githubusercontent.com/6726799/192053341-72d70999-093f-408d-ab43-69d6924728c1.png)

VS Code version: Code - Insiders 1.72.0-insider (43676d69e091e7f9451667925f3f0cc20d7e7221, 2022-09-23T15:06:00.185Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

**Comment by jrieken** [comment]
regression from https://github.com/microsoft/vscode/commit/8c0d8b98b486ba85fbdc6f7aaa42f0196f503059
