### ISSUE TITLE
The Insiders build is unresponsive after updating to 1.72

### ISSUE THREAD

**Issue by rababR1** [microsoft/vscode#161688]
Does this issue occur when all extensions are disabled?: Yes/No

No

Tried using Extension Bisect to no avail... Since the extension window wasn't working.

- VS Code Version: Insiders Version 1.72
- OS Version: Windows 11
Below, is the overall screenshot I get when starting vscode insiders:

![image](https://user-images.githubusercontent.com/65360255/192115262-97e37d2c-652d-4db7-889d-a5e8892e1057.png)

**Comment by gjsjohnmurray** [comment]
Please try launching it from a command prompt like this

```
code-insider --disable-extensions
```

**Comment by rababR1** [comment]
Never mind. I had to completely remove all my saved data from my laptop and then reinstall Insiders again, and it fixed the issue
