### ISSUE TITLE
Uncaught (in promise) TypeError: `this.extensionService.whenInstalledExtensionsRegistered` is not a function

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161698]
Only in unit tests: https://monacotools.visualstudio.com/DefaultCollection/Monaco/_build/results?buildId=186509&view=logs&j=672276a2-8d3a-5fab-615d-090c51352f92&t=354d3e13-3534-5793-0b68-b00f8c1d36f3&l=9569

**Comment by sandy081** [comment]
Fixed
