### ISSUE TITLE
Controlling frequency of Outline view and CodeLens rendering

### ISSUE THREAD

**Issue by hyangah** [microsoft/vscode#161627]
Our extension (vscode-go) uses a language server that implements providers of DocumentSymbol, CodeLens, ....
I noticed that VS Code sends DocumentSymbol, CodeLens requests almost for every key stroke. The go language server is pretty responsive, and often times, it quickly recomputes the results based on the updated document.

Unfortunately, sometimes recovery from invalid syntax gets hard, and the server returns incomplete DocumentSymbol/CodeLens results. This problem causes UI elements that depend on CodeLens and DocumentSymbol responses to bounce and flicker. Some users reported that is distracting.

I tested if returning an empty array (one way to signal lack of a result according to [API doc](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider)) while user is typing makes any difference.  But that just cleared up the Outline view and all code lenses, so I guess there is no reuse of previous response. 

Is there a way to tell VS Code to reuse the previous results? Or is there a way to control the frequency of DocumentSymbol/CodeLens queries (e.g. recompute only on save) from the client side?

How do other language servers and DocumentSymbol/CodeLens providers avoid this problem?

**Comment by jrieken** [comment]
> I tested if returning an empty array (one way to signal lack of a result according to [API doc](https://code.visualstudio.com/api/references/vscode-api#DocumentSymbolProvider)) while user is typing makes any difference. But that just cleared up the Outline view and all code lenses, so I guess there is no reuse of previous response.

No, there is no re-use. Only the outline has a [heuristic](https://github.com/microsoft/vscode/blob/1643a42b2510f99d524135e270e218c5220731ef/src/vs/workbench/contrib/codeEditor/browser/outline/documentSymbolsOutline.ts#L299) that compares the amount of textual changes with the amount of symbol-tree changes. If that's fishy it will debounce a little further

> Is there a way to tell VS Code to reuse the previous results? Or is there a way to control the frequency of DocumentSymbol/CodeLens queries (e.g. recompute only on save) from the client side?

No, we want to be in charge of the UI and how it refreshes. We do adopt to the actual speed of providers, e.g we debounce requests in proportion to the time it takes to fulfil requests for a file. 

We have some prior art with semantic tokens where we allow providers to throw a cancellation error which is then understand as "try to re-use the existing result" (see https://github.com/microsoft/vscode/issues/93686). However, we didn't adopt that in other places. 

I am unsure how other language brains deal with that and this request is fair. You, as the extension obviously have control in this by

* keep the last good result yourself
* artificially delay the result in the hope for a subsequent request against a "better state"
