### ISSUE TITLE
Refactor preview doesn't show preview with clangd

### ISSUE THREAD

**Issue by hokein** [microsoft/vscode#161604]
Coming from https://github.com/clangd/vscode-clangd/issues/376

- VS Code Version: 1.71.2
- OS Version: MacOS

Steps to Reproduce:

1. opened a dummy `t.cc` (`auto S = 1;`) in VSCode with vscode-clangd extension, waiting for clangd to warm up.
2. Move the cursor to `auto`, click the 💡 and get a CodeAction menu
3. Move the cursor to the `Expand auto type` Code ACtion, and press `Command + Enter`

Expected result: a preview pane will be shown
Actual result: we apply the code action without showing the preview

A special bit about clangd which may be related: the CodeAction returned from clangd doesn't have the `edit` field propagated, instead we use the `applyTweak` command to apply a workspace edit.

The detailed logs in case it is useful:

```
V[] <<< {"id":9,"jsonrpc":"2.0","method":"textDocument/codeAction","params":{"context":{"diagnostics":[],"triggerKind":2},"range":{"end":{"character":2,"line":0},"start":{"character":2,"line":0}},"textDocument":{"uri":"file:///tmp/t3.cpp"}}}
I[] <-- textDocument/codeAction(9)
I[] --> reply:textDocument/codeAction(9) 0 ms
V[] >>> {"id":9,"jsonrpc":"2.0","result":[{"command":{"arguments":[{"file":"file:///tmp/t3.cpp","selection":{"end":{"character":2,"line":0},"start":{"character":2,"line":0}},"tweakID":"ExpandAutoType"}],"command":"clangd.applyTweak","title":"Expand auto type"},"kind":"refactor","title":"Expand auto type"}]}


V[] <<< {"id":10,"jsonrpc":"2.0","method":"workspace/executeCommand","params":{"arguments":[{"file":"file:///tmp/t3.cpp","selection":{"end":{"character":2,"line":0},"start":{"character":2,"line":0}},"tweakID":"ExpandAutoType"}],"command":"clangd.applyTweak"}}
I[] <-- workspace/executeCommand(10)
I[] --> workspace/applyEdit(1)
V[] >>> {"id":1,"jsonrpc":"2.0","method":"workspace/applyEdit","params":{"edit":{"changes":{"file:///tmp/t3.cpp":[{"newText":"int","range":{"end":{"character":4,"line":0},"start":{"character":0,"line":0}}},{"newText":"\n","range":{"end":{"character":0,"line":2},"start":{"character":11,"line":0}}}]}}}}
```

**Comment by mjbvz** [comment]
The refactor preview only supports previewing code actions that have an `edit`. This example shows that the code action is instead using a `command`, which we are not able to preview (since running the command may have other side effects)

**Comment by hokein** [comment]
> The refactor preview only supports previewing code actions that have an `edit`.

This makes sense, but this seems more like a UX issue in VSCode -- it'd be better for VSCode to disable the preview feature if the code action that don't have `edit`.

> Can vscode-clangd investigate switching use using edits instead?

In clangd, we want to avoid paying the cost of generating edits for each code action (as code action is triggered when evert the cursor moves in VSCode). 
I think we could support the newly-added [codeAction/resolve](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#codeAction_resolve) in clangd, but it is not our priority at the moment.
