### ISSUE TITLE
theme not working

### ISSUE THREAD

**Issue by harsh2787** [microsoft/vscode#161695]
Type: <b>Feature Request</b>

My vs code is not changing when i change it it revert back to the normal black theme agian. 3-4 times i unstalled and restalled the vs code but the same problem was happining again again.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
Have you enabled Settings Sync? If yes, perhaps something is going wrong in this area?

Another thing to try is the `Start Extension Bisect` command, in case an extension is causing your problem.

**Comment by aeschli** [comment]
Very probably an extension causing this. Please try to run without extensions to verify.
