### ISSUE TITLE
Filtering in Search Tree

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#161616]
From https://github.com/microsoft/vscode/pull/161022#issuecomment-1255876319
> The tree view also miss the in-tree filtering (CTRL+F) like the one for files:
> ![image](https://user-images.githubusercontent.com/22446243/191910155-b7c14b4c-4001-470a-841d-711d4967d77b.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/67397
