### ISSUE TITLE
Provide transitive closure of all dependencies used by vscode

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode#161660]
Greetings,

I need to know all the dependencies vscode does have, recursively until I hit the transitive closure. I also need to know the version/license of each one of these dependencies. By dependencies I mean any piece of software it does require to run, whether is something you install at the OS level with, a bundled component/library, a nodejs/yarn package, a vscode internal extension, etc. Essentially, I want to know all the dependencies regardless of the "layer" at which these dependencies get used.

I suspect the following resources sort of overlap with my request:

https://github.com/microsoft/vscode/blob/main/ThirdPartyNotices.txt https://github.com/microsoft/vscode/blob/main/package.json https://github.com/microsoft/vscode/blob/main/cglicenses.json https://github.com/microsoft/vscode/blob/main/cgmanifest.json

But not sure if any of them is recursive my nature, and whether the union of all of the them gives me what I want. Would be great if Microsoft can compile a separate file containing all that information. It will help with adoption of vscode within organizations.

Thanks.

PS: It would be great to have such list for both open-source vscode and the Microsoft build.

**Comment by dariomx** [comment]
By the way, to avoid duplication of work, I would like to share that I have asked earlier same question on StackOverflow:

https://stackoverflow.com/questions/73802916/how-to-get-transitive-closure-for-all-dependencies-of-vscode-itself

But later on I realized that filing my request here would get more traction. On any case, I will be happy to provide more information if my request is not entirely clear.

Thanks in advance

**Comment by alexdima** [comment]
In the VS Code installation directory, you can find two files which list the licenses of the third party software that is distributed with VS Code: `LICENSES.chromium.html` and `ThirdPartyNotices.txt`. 

In the root of this repository, you can find a file called `ThirdPartyNotices.txt` which contains the third party software that is incorporated in this repository.

**Comment by dariomx** [comment]
Hi Alex,

Thanks for you reply. Could you also clarify whether, for the case of VS Code, those two files are the transitive closure of the dependencies? Meaning that they cover all recursive dependencies. If they do not, please share up to what level they include.

Another question I have is whether these 3 files:

https://github.com/microsoft/vscode/blob/main/package.json https://github.com/microsoft/vscode/blob/main/cglicenses.json https://github.com/microsoft/vscode/blob/main/cgmanifest.json

should be also considered. They seem to mention stuff that is not present on the files you mentioned.

Saludos + regards.

**Comment by alexdima** [comment]
> Could you also clarify whether, for the case of VS Code, those two files are the transitive closure of the dependencies? Meaning that they cover all recursive dependencies. 

In the VS Code installation directory, the two files `LICENSES.chromium.html` and `ThirdPartyNotices.txt` contain the licenses of all third party software distributed with VS Code. Note that the `ThirdPartyNotices.txt` file present in the VS Code installation directory is not equal to the `ThirdPartyNotices.txt` from the root of this repository.

> They seem to mention stuff that is not present on the files you mentioned.

Could you please give a specific example of what is missing?

**Comment by dariomx** [comment]
Hello Alex,

Any further comments? I want to call it a day but those pending question prevent proper sleep :-}

Thanks.

**Comment by rzhao271** [comment]
jschardet is in ThirdPartyNotices.txt, but make sure you're looking at the one for the installed program, rather than the one in this repository.
In the system install, for example, the file is in the `C:\Program Files\Microsoft VS Code\resources\app` folder.

**Comment by dariomx** [comment]
You are absolutely right, Alex. I was searching with an editor and that did not bring any result, but grepping did. Still, I can see these 5 dependencies [cglicenses.json] but not on ThirdPartyNotices.txt:

> @tokenizer/token
> H.264/AVC Video Standard
> emitter-listener
> noop-logger
> readable-web-to-node-stream

Please also comment about the recursivity question.

Thanks again.

**Comment by dariomx** [comment]
Hi Raymond,

Thank you for confirming that generated ThirdPartyNotices.txt does contain the transitive closure of dependencies, indeed.

As for the missing ones, it may be good to re-generate ThirdPartyNotices.txt to ensure it does include any missing piece (if any).

Cheers

**Comment by alexdima** [comment]
I see that `H.264/AVC Video Standard` is missing from ThirdPartyNotices.txt, thank you for raising that. We will correct this ASAP.

**Comment by dariomx** [comment]
Great, thank you Alex, Raymond and everyone involved. Great support, super responsive.
