### ISSUE TITLE
[MacOS] App UI is broken on macOS VM

### ISSUE THREAD

**Issue by ZeeWanderer** [microsoft/vscode#161611]
- VS Code Version: `1.71.2(Universal)`
- OS Version: `macOS 12.6` VMWare

VSCode UI is broken on macOS VM. Likely cause is `Hardware Acceleration` [#desktop/desktop/15287](https://github.com/desktop/desktop/issues/15287)

![image](https://user-images.githubusercontent.com/8377469/191987844-0e2d2fb1-607e-4e67-9a9e-39d6d122e4e6.png)

Steps to Reproduce:

1. Install VSCode on macOS VM
2. run VSCode

**Comment by ZeeWanderer** [comment]
When run un terminals as `/Applications/Visual\ Studio\ Code.app/Contents/MacOS/Electron Desktop` produces:
```
objc[2262]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb58d16ec8) and /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x11a863ce0). One of the two will be used. Which one is undefined.
```
Identical to `Github Desktop`.

How do I disable hardware acceleration to test if it is the cause?

**Comment by crisbolohan** [comment]
You have to disable the hardware acceleration using the terminal:
1. Go to .vscode folder: cd /Users/<your user>/.vscode
2. Open argv.json file: sudo nano argv.json
3. Add: "disable-hardware-acceleration": true
4. Save file
5. Restart VS Code

Another way to do this is using VS Code, if the broken UI lets you do that:
1. Open Command Palette
2. Search for Preferences: Configure Runtime Arguments
3. This will open the same argv.json file, here you have to add "disable-hardware-acceleration": true
4. Save file
5. Restart VS Code

The first option worked for me (using the terminal), hope it helps you too.

**Comment by ZeeWanderer** [comment]
@crisbolohan first way works, thanks. As for the second, UI and everything else is broken including command palette. I won't close the issue for now because unless developers decide that they don't care about VM platforms this is a bug. Thou it seems to be an Elecron bug.

**Comment by deepak1556** [comment]
Issue might get addressed with future Chromium upgrades, but generally we recommend disabling hw acceleration for these issues. Closing as it is not actionable on our end.
