### ISSUE TITLE
webview find widget customization

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#161683]
I would like to use the find option on a custom web view panel.
For simple webviews with text only this works quite well.

I would like to display a representation of some binary and offer a search on it.
The current find-widget implementation has no way to customize the search.
It would be great if some interface could be implemented.
E.g. sending the search string to the Webview and the Webview returns the found locations.
Or some options to configure the type of search, e.g. case sensitive, null-terminated, etc.

**Comment by mjbvz** [comment]
For more advanced use cases, you can build your find widget like the hex editor extension does:

![Screen Shot 2022-09-26 at 9 34 20 AM](https://user-images.githubusercontent.com/12821956/192332265-ea5193ed-63ff-4fe4-bb2a-170b47049e67.png)

This is out of scope of VS Code core
