### ISSUE TITLE
IntelliSense does not work in tsconfig.json

### ISSUE THREAD

**Issue by forethoughtde** [Microsoft/vscode#16164]
- VSCode Version: VSC Insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open VSC Insider 
2. Create tsconfig.json file and press CTRL + SPACE to get suggestion
3. Observe the bug

**Comment by mjbvz** [comment]
I confirmed this is broken in today's insiders build. I also just tried building code from master and the issue seems to be fixed.

Please try out the next insider build and let me know if you still see this. Thanks.

**Comment by mjbvz** [comment]
I believe this was a duplicate of #16050
