### ISSUE TITLE
Use better recognizable icons for keymap extensions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16162]
Most of the current icons are not well recognizable. Eclipse being the exception.

![keymap-extension-icons](https://cloud.githubusercontent.com/assets/9205389/20681925/92bf3dbe-b55a-11e6-9d68-15d27df4574a.png)

Part of the outcome of #15383.

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
