### ISSUE TITLE
Add extension to triggers for recommendations for PHP

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16168]
Given how popular PHP is, we should add one of the extensions to the list of triggers for recommending extensions when a PHP file is opened.

Part of the outcome of #15383.

**Comment by joaomoreno** [comment]
@waderyan Check with @chrmarti to know which extension to add to the recommendations list.

**Comment by chrmarti** [comment]
@mousetraps Could you advise on which extension should trigger the recommendation?

**Comment by waderyan** [comment]
We do have a couple in there for passive recommendationss. These are two of the most popular and highly rated extensions. 

```
		"felixfbecker.php-debug": "{**/*.php,**/php.ini}",
		"ikappas.phpcs": "{**/*.php,**/php.ini}",
```

I'll wait for @mousetraps to advise.

**Comment by felixfbecker** [comment]
May I also suggest https://marketplace.visualstudio.com/items?itemName=felixfbecker.php-intellisense

**Comment by chrisdias** [comment]
This is already a recommendation, just not an `important` one.
