### ISSUE TITLE
Call vscode command in shell script

### ISSUE THREAD

**Issue by loynoir** [microsoft/vscode#161662]
### If 

`Ctrl+Shift+P` `>rebuild container` have id `rebuildContainer`

### Then
Below can do the same thing outside vscode
```sh
$ env -C project_folder code command rebuildContainer
```

Call with parameters if possible
```sh
$ env -C project_folder code command rebuildContainer --foo=bar
```

### Use case
crontab

### Why
~~Thirdparty CLI `devcontainer build` does not run `initialcommand` by default~~.

https://github.com/devcontainers/cli/issues/190

**Comment by chrmarti** [comment]
https://github.com/devcontainers/cli/issues/190
