### ISSUE TITLE
VS Code is using parent's process output stream

### ISSUE THREAD

**Issue by Borschtsch** [microsoft/vscode#161676]
Type: <b>Bug</b>

When VS Code is started from a console application it is using parent's console output stream to print some debug information.
I checked with 'cmd.exe' and file manager 'Far' so far, with the latter one it overlaps the application window which makes a lot of inconvenience.

Here is an example of the information being displayed in the parent's console window:
-------------------------------------------------CUT HERE-----------------------------------------------------------
[main 2022-09-24T09:41:26.543Z] update#setState idle
[main 2022-09-24T09:41:28.417Z] Starting extension host with pid 23296 (fork() took 79 ms).
[main 2022-09-24T09:41:56.563Z] update#setState checking for updates
[main 2022-09-24T09:41:56.647Z] update#setState idle
[18068:0924/114326.453:ERROR:gpu_init.cc(481)] Passthrough is not supported, GL is disabled, ANGLE is
-------------------------------------------------CUT HERE-----------------------------------------------------------

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.97GB free)|
|Process Argv|vs.code-workspace --crash-reporter-id 2fe99cbb-e0a1-4710-96c5-d37af21a24d2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
RtEdit|Ahm|0.4.3
f5anything|dis|1.2.0
svn-scm|joh|2.15.5
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.30
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-todo-highlight|way|1.0.5
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
40g7c324:30573242

```

</details>

**Comment by roblourens** [comment]
Can you give some more details about what you're actually doing?

**Comment by Borschtsch** [comment]
Hi Rob,

I do not use --verbose option.
Below you will find two screenshots with running from command line on Windows and in Far Manager. 
I usually open the project through a file extension association, but even if I just start application directly from command line without any options I still get the same behavior. With Far Manager the window content gets shifted up which completely screws using the application.

Best regards,
-Dima

![ScreenShot](https://embeddedguy.com/wp-content/uploads/2022/09/cmd_example.png)
![ScreenShot](https://embeddedguy.com/wp-content/uploads/2022/09/Far_example.png)

**Comment by Borschtsch** [comment]
Hello @deepak1556 @roblourens ,

Another observations I have made. If I run **vscode** from the **cmd.exe** and then close the **cmd.exe** window the **vscode** crashes and closes as well. 
![ScreenShot](https://embeddedguy.com/wp-content/uploads/2022/10/app_crash.png)

If I hit CTRL+C in the **cmd.exe** window then **vscode** window just closes without any extra messages.

Regards,
-Dima

**Comment by deepak1556** [comment]
When launching `Code.exe` you will have to set `$env:ELECTRON_NO_ATTACH_CONSOLE=1` to not inherit stdio handles, this is a known issue https://github.com/microsoft/vscode/issues/66750

Can you try launching instead with our cli wrapper `Microsoft VS Code\bin\code.cmd` which should automatically launch with that environment set.

Merging to https://github.com/microsoft/vscode/issues/66750
