### ISSUE TITLE
Unable to close "Peek -> Call Heirarchy"

### ISSUE THREAD

**Issue by mpozderac** [microsoft/vscode#161634]
Type: <b>Bug</b>

Might be only when there are no callers of whatever, but I attempted to peek at something (misclick, so I might have immediately tried to do something after it) and when the overlay was displayed, it says "No callers of 'MyErrorClass'" and there is no "X" in the top corner to close it.

I could continue to use the editor, and peeking at the definition (my original intent) works and displays underneath the are that is still showing "No callers of 'MyErrorClass'".

I closed my window of that file and reopened it, and now it is still sort of there, but it moves with my scrolling and is transparent. But the blue header bar and bottom border is still there and the text of "No callers of 'MyErrorClass'" remains.

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin x64 21.5.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.14.246-187.474.amzn2.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|32.00GB (0.13GB free)|
|Process Argv|--crash-reporter-id 52f8719d-cf38-498a-b007-802ba9456837|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: asuite-dev.avatarfleet.com|
|OS|Linux x64 4.14.246-187.474.amzn2.x86_64|
|CPUs|AMD EPYC 7R32 (16 x 3297)|
|Memory (System)|31.07GB (5.17GB free)|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
auto-rename-tag|for|0.1.10
vscode-edge-devtools|ms-|2.1.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
debugger-for-edge|msj|1.0.15
vim|vsc|1.23.2
jinja|who|0.0.8
string-converter|ada|0.1.2
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
atlascode|atl|2.10.12
vscode-tailwindcss|bra|0.8.7
path-intellisense|chr|2.8.1
vscode-svgviewer|css|2.0.0
transformer|dak|1.12.1
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
python-preview|don|0.0.4
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.50.0
todo-tree|Gru|0.0.215
vscode-test-explorer|hbe|2.21.1
headwind|hey|1.7.0
Python-autopep8|him|1.0.2
vscode-text-pastry|jkj|1.3.1
rainbow-csv|mec|3.1.0
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.1
black-formatter|ms-|2022.4.0
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.30
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5723
autodocstring|njp|0.6.1
vetur|oct|0.36.0
csv-to-table|php|1.4.0
text-power-tools|qcz|1.36.1
vscode-data-preview|Ran|2.3.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
vscode-sort-json|ric|1.20.0
vscode-conventional-commits|viv|1.24.2
jinja|who|0.0.8
markdown-all-in-one|yzh|3.4.3
html-css-class-completion|Zig|1.20.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

**Comment by mpozderac** [comment]
Screenshot after closing the file and reopening it:
![image](https://user-images.githubusercontent.com/13731811/192039189-674b929b-2b8a-417c-8726-885ff5d08f6b.png)
Another one to show that it persists in the same location even if I scroll:
![image](https://user-images.githubusercontent.com/13731811/192039280-f1590ac1-b856-4f58-b794-96c416c0fa58.png)

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the issue is being caused by one of your extensions.

**Comment by jrieken** [comment]
@mpozderac what language/extension combo is this? can you share a sample that allows us to reproduce?
