### ISSUE TITLE
Missing right click options

### ISSUE THREAD

**Issue by Lv101Magikarp** [microsoft/vscode#161690]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2
- OS Version: Arch Linux x86_64
- DE: Plasma 5.25.5
- Graphics Driver: Nvidia 515

I'm using Code OSS from the Arch repositories and sometime ago most of my right click options suddenly went missing, as well as some other features like code navigation under the tab.
![missing_right_click_options](https://user-images.githubusercontent.com/19228995/192118341-8642b4f8-e402-46cf-b6ac-891e91fedc9e.png)
This also didn't happen after a particular code update. Reinstalling and clearing the metadata also didn't help, neither did using some older versions or the Microsoft vscode distribution.

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by Lv101Magikarp** [comment]
> Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

I reinstalled and cleared the metadata several times, so right now I don't have any extensions and this issue still persists...

**Comment by andreamah** [comment]
Do you have the C++ extension installed (if you're looking for the `Go To Definition` type of commands)? 

Overall, we don't support issues that arise from running Code OSS from different platforms, sorry about that! 😢

**Comment by Lv101Magikarp** [comment]
> Do you have the C++ extension installed (if you're looking for the `Go To Definition` type of commands)?
> 
> Overall, we don't support issues that arise from running Code OSS from different platforms, sorry about that! cry

The C++ extension is a globally enabled extension.
What do you mean different platforms? I see plenty of Linux issues. I also get the same issue from running the MS VSCode distribution if that's the point, so this would still be relevant...

**Comment by andreamah** [comment]
> The C++ extension is a globally enabled extension. 

Just fyi, running Code OSS would require you to download the VSIX for any extensions and install them manually onto it (since Code OSS is like another program that doesn't know about the other vscode distros on your system).

> What do you mean different platforms? I see plenty of Linux issues. 

Apologies for being unclear, I meant the process of running Code-OSS and getting that all up and running. We still support Linux for distributed vscode.

> I also get the same issue from running the MS VSCode distribution if that's the point, so this would still be relevant...

Oh, I see, that's a different story then. :) However, stuff like `Go to Definition` is contributed by the language extension. In this case, you'd probably find the most help by filing an issue with them: https://github.com/Microsoft/vscode-cpptools.

**Comment by Lv101Magikarp** [comment]
> > The C++ extension is a globally enabled extension.
> 
> Just fyi, running Code OSS would require you to download the VSIX for any extensions and install them manually onto it (since Code OSS is like another program that doesn't know about the other vscode distros on your system).
I see, but I was using the Arch community package, which should include them as requirements (Code OSS also used to work just fine, it broke at some point
> Apologies for being unclear, I meant the process of running Code-OSS and getting that all up and running. We still support Linux for distributed vscode.
> Oh, I see, that's a different story then. :) However, stuff like `Go to Definition` is contributed by the language extension. In this case, you'd probably find the most help by filing an issue with them: https://github.com/Microsoft/vscode-cpptools.
I see thanks.
Sorry I should've mentioned it in the post, but this is not a C++ exclusive issue. I am missing the options on every language I tried, like C++, Python, Go, etc. Or that's what I used to think, because I just verified that JS, and JS related languages like TS, are still working (maybe because they're native to vscode or idk). So I would think this is not an extension related issue.

**Comment by gjsjohnmurray** [comment]
@Lv101Magikarp please seek assistance from the maintainers of the build that you have chosen to use.

**Comment by Lv101Magikarp** [comment]
> @Lv101Magikarp please seek assistance from the maintainers of the build that you have chosen to use.

Again, I get the issue from both builds. I have more recently been tested on vscode since that's what you guys support. I thought it was more appropriate to get help from where the actual code is maintained. Should I open another issue not mentioning I ever used another build?

**Comment by gjsjohnmurray** [comment]
Sorry for overlooking that detail in the thread.

I suggest you launch "official" VS Code with the `--user-data-dir <dir>` argument pointed to a fresh dir. Check things are OK with the languages supported by the built-in extensions. Then start adding other extensions one at a time from the official Marketplace. Do you eventually recreate the issue?

**Comment by Lv101Magikarp** [comment]
> Sorry for overlooking that detail in the thread.
> 
> I suggest you launch "official" VS Code with the `--user-data-dir <dir>` argument pointed to a fresh dir. Check things are OK with the languages supported by the built-in extensions. Then start adding other extensions one at a time from the official Marketplace. Do you eventually recreate the issue?

No problem.
I did that and I get the issue straight away with the built-in extensions. I only get the limited options when right clicking for every language except JS.
