### ISSUE TITLE
Remove automatic new untitled file in empty workbench

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16161]
From #15547:  I don't see an effect of the untitled file experiment on the number of times an untitled file is used. It appears that creating an untitled file is intuitively understood by new users. Also users don't create new files that frequently, they read/work on existing files much more often it seems, that reduces the value of the automatically opened new untitled file further.

Part of the outcome of #15383.

**Comment by Antony74** [comment]
Yes, I'm a newcomer: it's rather annoying that empty workbench does not mean empty workbench, and the setting to disable this is too well hidden.  It's this one, if anyone else is stuck like I was:

    "telemetry.experiments.openUntitledFile": false

**Comment by deadlydog** [comment]
I don't see the `telemetry.experiments.openUntitledFile` setting in the current latest VS Code (v1.13.0), so it looks like this feature still needs to be implemented.

**Comment by chrmarti** [comment]
Will fix with #12387

**Comment by Antony74** [comment]
@deadlydog I'm not surprised you didn't find this covert setting, but `telemetry.experiments.openUntitledFile` has successfully removed the untitled file annoyance for me and continues to do so in v1.13.0.
