### ISSUE TITLE
Opening command palette sets X11 selection to ">"

### ISSUE THREAD

**Issue by ancorehraq** [microsoft/vscode#161656]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Ubuntu 22.04.01

Steps to Reproduce:
1. Select some text in a terminal.
2. Press ctrl-shift-p in vscode
3. Click middle mouse button in the terminal
4. Observed: > is pasted
5. Expected: selection from 1. is pasted

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal

**Comment by Tyriar** [comment]
test
