### ISSUE TITLE
Revisit strategy for picking an existing window when opening a single file

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16165]
Currently the last active window is used, which can seem random to the user. It would make more sense to reuse a window opened on a parent folder of the file to open, if there is such a window.

We already have `"window.openFilesInNewWindow"` which doesn't seem to work in its default setting `true`. Rather than fix that, we should consider making `false` the default so the suggested change above gets used more often (currently the effective default).

For background: Only half of all sessions are opened on a folder, about 30% are opened on a single file.

Part of the outcome of #15383.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15654
