### ISSUE TITLE
Filter file-based recommendations to those relevant to the file

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16166]
When opening recommendations from the message for an opened file, the list of recommended extensions is shown in full, not filtered down and/or sorted to those relevant to the file the message originated from.

Only showing the relevant extensions would improve the user experience and impact of the feature.

Part of the outcome of #15383.

**Comment by joaomoreno** [comment]
This is as designed since it increases exposure to other extensions that might be useful to the user given his history of open files.

**Comment by chrmarti** [comment]
I'm shown the '@recommended' list, is that filtered based on recently opened files? If yes, does the filtering change based on which folder is open? How does it handle the no-folder case?

**Comment by joaomoreno** [comment]
No. As users open files for which we have recommendations, we remember the recommendations. All remembered recommendations show up in `@recommended`.

**Comment by chrmarti** [comment]
Makes sense, thanks. Closing.
