### ISSUE TITLE
Test Settings Profiles UX

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161792]
Refs: https://github.com/microsoft/vscode/issues/155067

- [x] win @aiday-mar
- [x] linux @lramos15
- [x] mac @TylerLeonhardt

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161792%0A%0A&assignees=sandy081)

---

VS Code now shows Settings Profiles indicator at the bottom of the Activity bar. By default, the first two characters of the profile name is shown in the indicator. You can also customise it any two characters / an Emoji / a codicon. VS Code shows a default indicator when on default settings profile. 

- Test that this indicator is rendered appropriately when customised or switched between profiles. You can provide a codicon too in the format `$(${codicon})`. 
- Test customising the colours of this indicator using `activityBarItem.settingsProfilesForeground` and `activityBarItem.settingsProfilesHoverForeground` tokens. Eg:
```json
"workbench.colorCustomizations": {
		"activityBarItem.settingsProfilesForeground": "#b04444",
		"activityBarItem.settingsProfilesHoverForeground": "#23c456",
}
```

**Comment by aiday-mar** [comment]
Cool! I like the feature
