### ISSUE TITLE
The editor language guess override the language id set by extension

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#161744]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
Steps to Reproduce:

1. Run the following code with a VS Code extension:
```ts
await commands.executeCommand("workbench.action.files.newUntitledFile");
const textEditor: TextEditor | undefined = window.activeTextEditor;
if (!textEditor) {
    return;
}
const snippets: string[] = [];
snippets.push(`public \${1|class,interface,enum,abstract class,@interface|} \${2:Main} {`);
snippets.push(`\t\${0}`);
snippets.push("}");
snippets.push("");
await textEditor.insertSnippet(new SnippetString(snippets.join("\n")));
await languages.setTextDocumentLanguage(textEditor.document, "java");
```
2. The language id is set to `Java`, but suddenly it changes to `C#`

https://user-images.githubusercontent.com/6193897/192215596-4132b3b7-5010-496e-9416-9a744598051f.mp4

**Comment by TylerLeonhardt** [comment]
@jdneo this should be fixed in the VS Code Insiders build, can you confirm?

**Comment by jdneo** [comment]
Thank you @TylerLeonhardt, I can confirm that in the latest insider the language id won't change to `C#`.

**Comment by TylerLeonhardt** [comment]
The next stable will be released next week :)
