### ISSUE TITLE
Allow specifying regular expression when attaching to process

### ISSUE THREAD

**Issue by loligans** [microsoft/vscode#161790]
When attaching to a process, I would like to automatically select a process that matches a regular expression.

Example Process Picker:
```
dotnet /usr/share/dotnet/dotnet /usr/share/dotnet/sdk/6.0.401/MSBuild.dll
bash
sleep 180
dotnet myapplication.dll -- --my-app-args
```
The regex would look something like this: /dotnet.*myapplication.dll/g
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": ".NET Core Attach",
            "type": "coreclr",
            "request": "attach",
            "regex": "/dotnet.*myapplication.dll/g"
        }
    ]
}
```

If only 1 matching process was found then it automatically selects it and attaches. If multiple processes were found then it prompts the user to select 1

**Comment by roblourens** [comment]
Please file this on the repo for that extension
