### ISSUE TITLE
Incorrect highlighting of trailing slash in unquoted HTML attribute values

### ISSUE THREAD

**Issue by hsivonen** [microsoft/vscode#161764]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0-insider from 3 hours before reporting
- OS Version: Ubuntu 22.04.1

# Steps to Reproduce:

1. `code-insiders --disable-extensions test.html`
2. Type:

```html
<!DOCTYPE html>
<a href=https://example.com/><img class=foo/></a>
```

# Actual results:

The trailing slash in the value of the `href` attribute is highlighted as an error. The trailing slash in the class value `foo/` is highlighted as if it was not part of the attribute value.

![code-slash](https://user-images.githubusercontent.com/478856/192282008-380bf3dd-5046-4795-bc41-4ea6256dfafb.png)

# Expected results

Expected both slashes to be highlighted in the attribute value color, since they [parse as part of the attribute value according to the HTML spec](https://software.hixie.ch/utilities/js/live-dom-viewer/saved/10809).

**Comment by alexr00** [comment]
@hsivonen the spec you link indicates that the `href` value should be put in double quotes. I do not see this issue when surrounding the `href` value with double quotes.

**Comment by hsivonen** [comment]
I think you are misunderstanding. I didn't link to the spec. I linked to a tool that parses the input using the HTML parser in your browser and, therefore, shows how a real parser tokenizes the input according to the spec (assuming, of course, that the browser you are using complies with the spec on this point).

As for the actual spec, [I don't see](https://html.spec.whatwg.org/#attr-hyperlink-href) a requirement to use quotes around the `href` value. Can you point me to where the spec says so?

In any case, highlighting the trailing slash in an unquoted attribute value in red is defensible to call out something that the user of the editor might not intend. However, the way the slash in the value of the `class` attribute is highlighted in the example that I gave is unambiguously incorrect. The highlighting suggests that the slash isn't part of the attribute value when it most certainly is per spec and per spec-compliant browser behavior.

**Comment by hsivonen** [comment]
Specifically, in the ["Attribute value (unquoted) state"](https://html.spec.whatwg.org/multipage/parsing.html#attribute-value-(unquoted)-state) the slash goes through the "Anything else" case.

**Comment by alexr00** [comment]
Thanks for clarifying! We get our html syntax highlighting grammar from https://github.com/textmate/html.tmbundle, so this is a duplicate of the upstream issue https://github.com/textmate/html.tmbundle/issues/118.
