### ISSUE TITLE
Support free port terminal quick fix on Windows

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161775]
We'll want a Windows PowerShell (v5) script that frees the port

https://github.com/microsoft/vscode/blob/d1f20dbf2d0a331e5e7def66e2843d9a758e6e32/src/vs/workbench/contrib/terminal/browser/terminalBaseContextualActions.ts#L48

**Comment by meganrogge** [comment]
Will this not work? 

https://github.com/microsoft/vscode/blob/cba1a973fcf54856be6fa3b2d6a964b1b0099ea1/src/vs/platform/terminal/node/ptyService.ts#L135-L159

**Comment by Tyriar** [comment]
Oh yeah maybe, the quick fix is disabled in the renderer process though so that would never be called:

https://github.com/microsoft/vscode/blob/04bb72a2ada2ad092b0de889339e066a8ff2393d/src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts#L53-L59

This issue may just be removing that ternary?

**Comment by meganrogge** [comment]
yes + re-enabling the test. i'm going to try to test it w the `code-server` now

**Comment by meganrogge** [comment]
bc on command finished isn't happening, it's not scanning the output

**Comment by Tyriar** [comment]
@meganrogge oh right, well that's another case of us needing to tweak the xterm.js script to pass along the fail. It's a bug in the script and we should `throw`/`process.exit` here: https://github.com/xtermjs/xterm.js/blob/37c722d556e4b7e15ef55b63da41a93f87ddd43c/demo/server.js#L139-L143. Most servers should exit when the port is not available

**Comment by meganrogge** [comment]
The code sever doesn't throw on windows either

**Comment by meganrogge** [comment]
so seems like we'll have to do something clever here if we want it to work without an exit code...

such as, after command execution, check the # of output lines, check again in 2 seconds, if it's the same as it was, scan for a match?

**Comment by Tyriar** [comment]
> so seems like we'll have to do something clever here if we want it to work without an exit code...

I don't think we should worry about this case and assume programs will exit. It's too much of a performance concern when we start scanning in progress commands.

**Comment by Tyriar** [comment]
A "floating" lightbulb without a cursor that can accept input also feels strange

**Comment by meganrogge** [comment]
Okay well I think this issue can be closed then as it should work for Windows atm
