### ISSUE TITLE
Improve flow to get to a running debug session

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16171]
Investigation of the success rate of new users trying to start a debug session has shown that we loose ~25% at the environment picker and another ~25% once the launch.json is generated. At the same time debugging is among our user success experiences.

Some ideas that came up in discussions:
- Add a "More..." entry at the end of the environment picker that opens the extension viewlet with other debug adapters.
- Add more information to the 'debugMisconfiguration' event to be provided by the debug adapter to improve our understanding of what goes wrong.
- If there is no launch.json yet: Try to avoid the picker and/or the generated launch.json based on the currently opened file and launch a debug session directly.
- Improve the UX when the workbench did not open on a folder. (About half of all sessions.)

Part of the outcome of #15383.

**Comment by chrmarti** [comment]
Also: Having to open a folder is not intuitive in some scenarios. (See https://github.com/PowerShell/vscode-powershell/issues/354#issuecomment-264408103)

**Comment by daviwil** [comment]
Yes!  This effort will greatly help PowerShell developers migrate to VS Code smoothly.  Also, the requirement to open a folder is a big burden to adoption for PowerShell developers.  Many times a PowerShell user wants to just open VS Code to quickly debug an issue by writing a one-off script and they don't want to have to open a whole folder just to do that.  Too much friction.

Here's a recommendation I gave for how a workspaceless debugging flow could work for languages that support it: https://github.com/Microsoft/vscode/issues/285#issuecomment-265177351

I'd love to help make this a reality.

**Comment by davidanthoff** [comment]
I can only second this: it would be great if the debugger worked without a launch.json and anything like picking a configuration.

For the julia extension, really the workflow should be that if there is no launch.json, but the user has a julia file open and hits F5, then the julia debugger should start that file and debug it.

Right now we don't have a debugger (...), but the same of course is true for Ctrl+F5, I'd really like that to just work without any config.

**Comment by isidorn** [comment]
Added the 'More...' option when choosing an adapter and we are now logging the error message for the debug misconfiguration event - let's see if this gives us more interesting info.
As for the last two points they are captured as part of https://github.com/Microsoft/vscode/issues/285
Thus closing this.
