### ISSUE TITLE
If the description has a localized message with comments, it's rendered as [object object] 

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#161798]
Steps to Reproduce:

1. Search for GitHub Issue Notebooks extension
2. see this:
![image](https://user-images.githubusercontent.com/2644648/192328993-e2715db9-3cf5-4122-8517-0b0a95a81cc8.png)

Here's what it is doing that should be supported:
https://insiders.vscode.dev/github/microsoft/vscode-github-issue-notebooks/blob/bbb9f8781ddca718d1bd4687d4b9d9f2612b1bf4/package.nls.json#L3

**Comment by TylerLeonhardt** [comment]
@sandy081 has informed me that this string comes directly from the marketplace API (VSIX manifest API). @isidorn can we provide feedback to the MP team to support this?

**Comment by TylerLeonhardt** [comment]
For now, I'll remove the localized description, so this doesn't surface to the user.

**Comment by isidorn** [comment]
@TylerLeonhardt yes, we can ask this from the Marketplace. The best thing would be to create a new issue https://github.com/microsoft/vsmarketplace
Can you maybe do that, since you have more context?

**Comment by TylerLeonhardt** [comment]
FYI I also opened: https://github.com/microsoft/vsmarketplace/issues/489 to support the localized value of these strings.
