### ISSUE TITLE
Test: Git - Support SSH keys with a passphrase

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#161789]
Refs: https://github.com/microsoft/vscode/issues/13680

- [x] macOS @paulacamargo25
- [x] linux @roblourens
- [x] windows @aiday-mar

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161789%0A%0A&assignees=lszomoru)

---

This milestone we have added support for using SSH keys with a passphrase when they are not added to the ssh-agent.

### Prerequisites
- Ideally you would want to follow these steps on a machine that does not yet have [any SSH keys locally](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/checking-for-existing-ssh-keys)
- Create [a new SSH key with a passphrase](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent). Note that GitHub has different steps based on platforms. 
  ⚠️  Please do not go through the steps to add the newly created SSH key to the ssh-agent.
- [Add the newly created SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account) to your GitHub profile.
- [Test](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/testing-your-ssh-connection) the newly created SSH key

### Testplan
- Launch VS Code Insiders
- Navigate to a private repository on GitHub, expand the "Code" button and grab the SSH clone URL
- Open the integrated terminal, create a new folder and clone the repository using the SSH clone URL
  - Confirm that you are prompted for a passphrase in the terminal
- Open the cloned repository in VS Code Insiders
- Make a change to a file and commit the changes
- Use the command palette to invoke the "Git: Push" command
  - Confirm that a quick input is being shown to enter the passphrase
- Enter the passphrase and hit Enter
  - Confirm that the change is being pushed to the remote repository
- Make a change to a file and commit the changes
- Use the command palette to invoke the "Git: Push" command
  - Confirm that a quick input is being shown to enter the passphrase
- Press Escape without entering the passphrase
  - Confirm that the push does not occur and no errors are being shown

**Comment by 4c74356b41** [comment]
sorry, Im not familiar with vscode sprints or something like that. when can we expect this feature to go live?

**Comment by lszomoru** [comment]
@4c74356b41, this feature will be included in the next Stable release that is planned around October 5th.
