### ISSUE TITLE
Snippet for Markdown File

### ISSUE THREAD

**Issue by gep13** [Microsoft/vscode#1617]
I am trying to create a snippet for Markdown file, but nothing I seem to try is working.

These are the steps that I have followed:

1. Open Visual Studio Code
1. Open a markdown file, i.e Readme.md
1. Press F1, type snippet, select `Create Snippet`
1. Entered the following:
```
 "Test Snippet": {
  "prefix": "gep13",
  "body": [
   "test $1"
  ],
  "description": "Your snippet description here."
 }
```
1. Saved the file, and then went back to the markdown file, and typed `gep13` but  the snippet never appears.

Any idea as to why this isn't working?  I have read through this: https://code.visualstudio.com/docs/customization/userdefinedsnippets and it suggests that snippets for markdown files should work, but it doesn't seem to.

I have tried opening/closing VS Code, but still nothing.  I am using VS Code version `0.10.5`.

**Comment by egamma** [comment]
This works for me, notices the top-level {} that you seem to have removed, they are required.

```json
{
	"Test Snippet": {
		"prefix": "gep13",
		"body": [
			"test $1"
		],
		"description": "Your snippet description here."
	}
}
```

**Comment by gep13** [comment]
@egamma sorry, but I also have those:

![image](https://cloud.githubusercontent.com/assets/1271146/11980782/37fbb64a-a995-11e5-8740-36f5a9c7a5d0.png)

Can you confirm exactly what you mean by working?  I have an expectation that when editing any file with a `.md` or `.markdown` extension, that when I type `gep13` I should have an option to expand that into the snippet, but that is not happening for me.

Is there anything that I can do to debug this further?

**Comment by egamma** [comment]
>Can you confirm exactly what you mean by working?

The gep13 snippet shows up when I edit a markdown file.

Here are my steps:
- preferences>user snippets
- select `markdown` in the quick box
- add the snippet to the file that opens

Now open a markdown file
- type `gep` and press `ctrl-space`, the snippet shows up.

**Comment by gep13** [comment]
Ah, interesting, the `Ctrl-Space` is required.  In the Latex extension, and the Cake extension, the snippets there seemed to automatically appear, without the need for pressing `Ctrl-Space`.  What magic is happening in those extensions to make that just work?

For example, in the Latex extension, I was able to type `cha` and the snippet appeared automatically, without the need to press `ctrl-space`.  Thanks!

**Comment by egamma** [comment]
Yes this is an inconsistency. Full extensions get auto (7x24) completion by default (e.g. latex, cake), some built-in extensions like Markdown do not.

**Comment by gep13** [comment]
@egamma gotcha, ok, so the world makes sense again, at least for now :smile: Thanks for all your help with this!

**Comment by TJSoftware** [comment]
:+1: the `Ctrl-Space` was not expected.

Are there any others outside of markdown that require the use of `Ctrl-Space`?

Asking out of ignorance here, is this something that markdown files can be made into an extension like C# is an extension?

**Comment by bcsjk11** [comment]
Didn't know about the `Ctrl+Space` either until I read this here. +1 on wanting this to be build in by default. Or at least have a clear guide on what languages are support 24x7 and which are not for this.
