### ISSUE TITLE
Some SCSS items syntax coloring improperly scoped

### ISSUE THREAD

**Issue by smlombardi** [Microsoft/vscode#16172]
- VSCode Version: Code - Insiders 1.8.0-insider (2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb, 2016-11-28T07:05:06.507Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|material-icon-theme|PKief|1.1.4|
|code-settings-sync|Shan|2.3.8|
|sort-lines|Tyriar|1.1.0|
|html-css-class-completion|Zignd|1.0.3|
|Bookmarks|alefragnani|0.10.0|
|project-manager|alefragnani|0.12.2|
|one-monokai|azemoh|0.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.0|
|tslint|eg2|0.6.5|
|Angular2|johnpapa|1.0.2|
|theme-karyfoundation-themes|karyfoundation|10.0.0|
|HTMLHint|mkaufman|0.0.3|
|vscode-stylefmt|mrmlnc|2.1.0|
|Theme-1337|ms-vscode|0.1.2|
|angular2-inline|natewallace|0.0.16|
|nonbreakingspace|smlombardi|0.0.1|
|vscode-icons|robertohuertasm|4.0.2|
|stylelint|shinnn|0.20.2|
|theme-tesla|smlombardi|5.2.4|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|change-case|wmaurer|1.0.0|

---

Steps to Reproduce:

1. I'm a theme author, and I noticed some items in scss variable declartions are all scoped to `token scss meta set variable`, including font names and punctuation, making them impossible to color them to match punctuation and font names elsewhere in scss files -- since they are the same scope as the variables themselves (maroon in [my theme](https://marketplace.visualstudio.com/items?itemName=smlombardi.theme-tesla))

![screen shot 2016-11-28 at 3 57 31 pm](https://cloud.githubusercontent.com/assets/835148/20685770/c1556648-b583-11e6-91f1-d780667955d7.jpg)

The code used here is:
```scss
$font-family-sans-serif: 'Helvetica Neue', Helvetica, Arial, sans-serif;
$font-family-serif: Georgia, Times, 'Times New Roman', serif;
$font-family-base: $font-family-sans-serif;
$font-family-monospace: Menlo, Consolas, Monaco, 'Courier New', monospace;
$font-family-ps-light: 'PrecisionSans_W_Lt', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-light-italic: 'PrecisionSans_W_LtIt', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-regular: 'PrecisionSans_W_Rg', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-regular-italic: 'PrecisionSans_W_RgIt', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-medium: 'PrecisionSans_W_Md', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-medium-italic: 'PrecisionSans_W_MdIt', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-bold: 'PrecisionSans_W_Bd', 'Helvetica Neue', Arial, sans-serif;
$font-family-ps-bold-italic: 'PrecisionSans_W_BdIt', 'Helvetica Neue', Arial, sans-serif;
$headings-font-weight: normal;
$headings-line-height: 1.1;
$headings-color: inherit;
$btn-font-weight: normal;
```

**Comment by alexandrudima** [comment]
I can confirm the punctuation is not getting a specific scope in a variable declaration:

![16172](https://cloud.githubusercontent.com/assets/5047891/23474219/4b0affb0-feb3-11e6-810a-809bc2c553aa.gif)

**Comment by aeschli** [comment]
This issue was moved to atom/language-sass#207
