### ISSUE TITLE
Cannot set breakpoints where I choose

### ISSUE THREAD

**Issue by RyanMitchellWilson** [Microsoft/vscode#16170]
Every time that I try to set a breakpoint it automatically moves it to another point in my file. It should just set the breakpoint on the line that I choose not whatever it thinks is best.

<img width="499" alt="screen shot 2016-11-28 at 1 53 29 pm" src="https://cloud.githubusercontent.com/assets/11371200/20685598/36f3d162-b572-11e6-8824-0fe898cbabb6.png">

I chose line 307 here and it keeps moving it to line 316, which isn't even the same function. (You can see this at the bottom left of the screenshot). It should not be moving my breakpoint at all

- VSCode Version: 1.7.2
- OS Version: OSX Sierra 10.12.1
- React-Native 0.30.0
- Node 6.9.1
- Babel-Register 6.11.6

Steps to Reproduce:

1. Run Deugger
2. Add/Remove Some Code
3. Try to set a breakpoint

**Comment by RyanMitchellWilson** [comment]
I am using babel and node in my project so it could be related to this https://github.com/Microsoft/vscode/issues/5728#issuecomment-264226949

**Comment by roblourens** [comment]
1. In your launch config are you using type 'node', or 'node2'? Can you try the other one and see if there's a difference?
2. Does it happen everywhere in your project or just that file/line?
3. Does it break in the right place, but show the breakpoint in the wrong place?
4. Is this a project that's available for me to try on github?

**Comment by RyanMitchellWilson** [comment]
1. Don't see 'node' anywhere in my `launch.json` file so this might not be a node problem.
2. Seems to happen pretty much everywhere in project when I have 'React-Native: Run Packager' going and have the vscode debugger running. Could be a React-Native thing. Changes my break point if I have been editing the file with the packager running.
3. Occasionally will break in the right place but mostly it breaks on the line the it moved the break point to. Which looking at the screen shot above you can see that it knows it is moving my break point bucause it shows `Routes.js 307 -> 316`
4. Private project not on github.

**Comment by roblourens** [comment]
Ok, so you're debugging with the react native extension? I don't know a lot about what issues you might see in that setup. I recommend filing an issue on their repo - https://github.com/Microsoft/vscode-react-native.

**Comment by RyanMitchellWilson** [comment]
Alright can do

**Comment by basickarl** [comment]
@roblourens @RyanMitchellWilson I'm receiving the same issue, the breakpoints are jumping when using node2 as type. I'm also using babel.

When setting type to "node" it doesn't jump. Problem is that I see transpiled code though (babel).

Heres my launch option:
```
{
      "name": "Launch NPM start",
      "type": "node2",
      "smartStep": true,
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "runtimeExecutable": "/home/usr/.nvm/versions/node/v7.2.0/bin/node",
      "runtimeArgs": [
        "--harmony-async-await",
        "-r",
        "babel-register",
        "--debug-brk=5858",
        "${workspaceRoot}/src/index.js"
      ],
      "port": 5858,
      "env": {
        "PATH": "${env.PATH}:/home/usr/.nvm/versions/node/v7.2.0/bin/node",
        "NODE_PATH": "${workspaceRoot}"
      }
    }
```

.babelrc:
```
{
  "presets": [
    "es2015"
  ],
  "sourceMaps": "inline"
}
```

Heres a chronological display of how it looks (clicking on step over):

![screenshot from 2016-12-02 14-23-17](https://cloud.githubusercontent.com/assets/10507098/20835765/81016cc4-b89c-11e6-9c0c-e47b561a9197.png)

![screenshot from 2016-12-02 14-23-34](https://cloud.githubusercontent.com/assets/10507098/20835771/88960d64-b89c-11e6-9324-dbab53a4c898.png)

![screenshot from 2016-12-02 14-23-46](https://cloud.githubusercontent.com/assets/10507098/20835776/8c3e6696-b89c-11e6-9400-b80e6258f559.png)

![screenshot from 2016-12-02 14-23-55](https://cloud.githubusercontent.com/assets/10507098/20835785/9ec7fe80-b89c-11e6-9cb6-fa4da603a0e9.png)

![screenshot from 2016-12-02 14-24-03](https://cloud.githubusercontent.com/assets/10507098/20835788/a13a6ac2-b89c-11e6-8e68-a6dcd3b190d1.png)

![screenshot from 2016-12-02 14-24-12](https://cloud.githubusercontent.com/assets/10507098/20835790/a368d4a0-b89c-11e6-958b-d43c7ef695d6.png)

![screenshot from 2016-12-02 14-24-21](https://cloud.githubusercontent.com/assets/10507098/20835793/a5eeb410-b89c-11e6-94cb-509515f55865.png)

![screenshot from 2016-12-02 14-24-31](https://cloud.githubusercontent.com/assets/10507098/20835794/a8b444b2-b89c-11e6-8f6d-5015794de58d.png)

![screenshot from 2016-12-02 14-24-44](https://cloud.githubusercontent.com/assets/10507098/20835798/ac31f2e2-b89c-11e6-858d-937c80e7cd83.png)

**Comment by roblourens** [comment]
@basickarl You probably just need to set `"sourceMaps": true` to have it use sourcemaps
