### ISSUE TITLE
Editor : Hover : Sticky no longer preventing mouseover

### ISSUE THREAD

**Issue by web3d0** [microsoft/vscode#161708]
Type: <b>Bug</b>

Set Editor : Hover : Sticky to false in Preferences, but then the hover remains there while mouseover, instead of disappearing out of the way like it used to.

VS Code version: Code - Insiders 1.72.0-insider (43676d69e091e7f9451667925f3f0cc20d7e7221, 2022-09-23T15:06:14.385Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: Yes

**Comment by gjsjohnmurray** [comment]
@alexdima maybe #161407 caused this.
