### ISSUE TITLE
Test: Run Python code in the web

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#161784]
Refs: [https://github.com/microsoft/vscode-wasm/issues/6](#6)

- [x] anyOS @brettcannon 
- [x] anyOS @hediet

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode-python-web-wasm/issues/new)

---

This test plan item needs to be tested using:

- https://insiders.vscode.dev/
- latest pre-release version of Remote repositories and GitHub repositories

Setup:

- open https://insiders.vscode.dev/
- install the extension with the id: `ms-vscode.vscode-python-web-wasm`
- enable workspace trust and reload
- open a GitHub repository that has Python files. If you don't have one you can use: https://github.com/dbaeumer/python-sample **Please note** that local Python files are currently not supported.

Test:

- have a Python file that prints something to the terminal (e.g. app.py from the above repository)
- open that file
- Select `Run Python in WASM` from the editors play menu.
- Ensure that you get a dialog telling you that you need to enable cross origin isolation. Do so by adding `?vscode-coi=` to the URI.
- Rerun the run action.
- **Known issue**: due to a bug in the terminal the output is not printed on first run (see https://github.com/microsoft/vscode/issues/160914)
- run the file again. This time the output should be available in the terminal
- change some code in the file. 
- run it again. Ensure that the changes are considered.
- Run the command: `Python WASM: Start REPL`
- Ensure that a terminal opens with a Python REPL
- Ensure the you can type in the REPL and that basic keyboard navigation works (e.g. cursor left, right, del, backspace, typing)

**Comment by brettcannon** [comment]
@hediet because you didn't check off that you did the TPI I am not closing this issue. If you meant to check it off then feel free to close.
