### ISSUE TITLE
cast highlighting inconsistent across many themes

### ISSUE THREAD

**Issue by rob3c** [Microsoft/vscode#16175]
- VSCode Version: 1.8.0-insider Commit 2c8ab1a5ffc49ac26b2080bfbbbf9317fb8071bb
- OS Version: Windows 8 Pro

Casting is inconsistently rendered across many themes. It seems related to newlines. Here's a code sample (with excessive casting) and screenshots across a few themes, for reference. (even the github renderer seems confused!)

```typescript
class Foo {
    constructor(public x: string) {}
}

const foo1 = <Foo> { x: '1' };
const foo2 = <Foo> {
    x: '2'
};
const foo3 =
    <Foo> {
        x: '3'
    };

let foos: Foo[] = <Foo[]> [
    new Foo('4'),
    <Foo>{ x: '5' },
    <Foo>{
        x: '6'
    },
];

let obj = Object.assign(new Foo('7'), <Foo> { x: '8' },
    <Foo>{ x: '9' }, <Foo> { x: '10' }, <Foo>{
        x: '11'
    },
    <Foo>{
        x: '12'
    });
```
### Dark+
![dark theme casting](https://cloud.githubusercontent.com/assets/1098077/20687435/6d25658a-b58a-11e6-903e-9b9e82a03c3e.png)
### Light+
![light theme casting](https://cloud.githubusercontent.com/assets/1098077/20687440/73584526-b58a-11e6-97c0-cdc4b5a19ed7.png)
### Monokai Dimmed
![monokai dimmed theme casting](https://cloud.githubusercontent.com/assets/1098077/20687442/7365e460-b58a-11e6-94f2-2288077f8ead.png)
### Monokai
![monokai theme casting](https://cloud.githubusercontent.com/assets/1098077/20687443/73853ec8-b58a-11e6-8b33-094a436fddeb.png)
### Solarized Dark
![solarized dark theme casting](https://cloud.githubusercontent.com/assets/1098077/20687441/7363c036-b58a-11e6-804e-2f38ee19e243.png)

**Comment by aeschli** [comment]
I looks like the cast is scoped as variable.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#375

**Comment by dbaeumer** [comment]
Verified move to TS.
