### ISSUE TITLE
Codespaces issue

### ISSUE THREAD

**Issue by thatmadguy345** [microsoft/vscode#161704]
ADD ISSUE DESCRIPTION HERE

codespaces is not loading. not able to access any code. 

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.102 Safari/537.36 OPR/90.0.4480.100
Embedder: codespaces

**Comment by Tyriar** [comment]
You should report Codespaces issues to GitHub support
