### ISSUE TITLE
Badge and extension view content

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#161777]
I was presented with the following:

![CleanShot 2022-09-26 at 07 17 46](https://user-images.githubusercontent.com/4674940/192300691-fa653c95-427c-474b-aafc-9a9afcfe5bd0.gif)

The badge indicates that there is an extension that requires a reload. However, when I go to the extensions view it's pretty hard to find out which extension that is. The extension(s) that need reload should be at the top of the list.

**Comment by sandy081** [comment]
@benibenj I assume this gets fixes with your recent changes right?

**Comment by benibenj** [comment]
We split the feature into 2 different PRs to simplify reviewing and merging. The first one is already in (updating the badge and restructuring code) the second one will be in later on today (pushing extensions requiring action to the top and split button).

**Comment by sandy081** [comment]
Closing this as the two PRs are merged.
