### ISSUE TITLE
More visual help to tell different folder levels in explorer

### ISSUE THREAD

**Issue by boan-anbo** [microsoft/vscode#161706]
## Folders of different levels are hard to tell from one another.

- For example:
 ![image](https://user-images.githubusercontent.com/7269717/192152912-8805c2f1-d3ce-4c63-90f8-883e1ce20348.png)

## Currently, the only visual clues are:
1. Directions of the arrow icon
2. Different indent levels.

Of the two, the arrow offers more visual help to tell parents and subfolders but is still hard to tell at a glance.

The Indent levels are not very distinguishable from each other unless one looks closely, and this minimal difference will disappear when is a vertical distance between two indent levels (you lost the point of reference).

## In short, I feel there is a need for settings to add more visual aid to:
1. tell parent from child
2. tell two expanded folders from each other.

## Possible aids:
1. Divider between different folders
2. Different shapes or background colors for subfolders of the same parent and for different folders on the same level.

## Comparison with some other IDEs (with the same set of folders expanded as the above example)

![image](https://user-images.githubusercontent.com/7269717/192153991-95decd7a-af6d-4587-ae38-c763d824771c.png)

![image](https://user-images.githubusercontent.com/7269717/192154058-68e13a8a-a306-4ee1-9628-102e2927f71a.png)

**Comment by gjsjohnmurray** [comment]
You may like to adjust your `workbench.tree.indent` setting, and perhaps try other values for `workbench.tree.renderIndentGuides`

**Comment by lramos15** [comment]
Thank you for the detailed issue. Sorry at this time we have no plan to change the explorer indentation logic as we already allow some configuration here. If this issue shows a large community ask we may decide to re-open and revisit it in the future.

**Comment by boan-anbo** [comment]
Understandable! Thanks for the replies.

**Comment by gjsjohnmurray** [comment]
@boan-anbo you might also like to try a different File Icon Theme such as https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

**Comment by boan-anbo** [comment]
> @boan-anbo you might also like to try a different File Icon Theme such as https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme

Thanks so much! Didn't know there is File Icon. Will try it out. 

As I adjusted `workbench.tree.indent`, I found my indent setting is only 2 (the min is 4). Perhaps my setting was touched by some plugin or theme. Having more indent made it so much better now.
