### ISSUE TITLE
Powershell write-output does not write to debug console

### ISSUE THREAD

**Issue by BruceP99166** [Microsoft/vscode#16176]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro 64-bit Build 14393.447

Steps to Reproduce:

1. Select HelloWorld.ps1 containing one line
        Write-output "Hello World"
2. Open Debug view
3. Open Debug Console
4. Click Start Debugging.  Script executes but nothing shows in Debug Console.

This is probably a usage issue since I am just starting with Visual Studio Code.  Thanks in advance for your assistance.

**Comment by isidorn** [comment]
Can you please file this issue to the powershell extension here https://github.com/PowerShell/vscode-powershell

Maybe @daviwil can help here

**Comment by daviwil** [comment]
Hey @BruceP99166, this is a known issue being tracked here: https://github.com/PowerShell/vscode-powershell/issues/284.  I'm planning to provide a fix for the next update of the extension, should be in a week or two.  Thanks for your patience!
