### ISSUE TITLE
Test: Create you own Python environment

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#161787]
Refs: [https://github.com/microsoft/vscode-wasm/issues/6](#6)

- [x] anyOS @brettcannon 
- [x] anyOS @aiday-mar

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode-python-web-wasm/issues/new)

---

This test plan item needs to be tested using:

- https://insiders.vscode.dev/
- latest pre-release version of Remote repositories and GitHub repositories

Setup:

- open https://insiders.vscode.dev/
- install the extension with the id: `ms-vscode.vscode-python-web-wasm`
- enable workspace trust

Test:

### Create your own Python Environment

- switch to a terminal in our OS
- create a new GitHub repository.
- clone the repository to the OS disk.
- download a wasm-wasi-16 build from https://github.com/tiran/cpython-wasm-test/releases
- expand it into the root of the newly created repository from above
- to add source wheel packages do the following (install from https://pypi.org/):
    - create a site-packages folder in the root
    - install the package using the following command pip install my_package --target ./site-packages. Note that you need to have a Python installation in your OS including pip.
- commit the changes to the GitHub repository

### Use the Environement

- open https://insiders.vscode.dev/
- Open a remote repository that has Python files. You can use https://github.com/dbaeumer/python-sample if you don't have one.  **Please note** that local Python files are currently not supported.
- Ensure that you enable cross origin isolation by adding `?vscode-coi=` to the browser URI.
- Open the `settings.json` file for the repository
- Set the `python.wasm.runtime` setting by pointing it to the repository containing the environment (e.g. `"python.wasm.runtime": "https://github.com/dbaeumer/python-3.11.0rc"`
- Open and run a python file by using `Run Python File in WASM` action from the editor play button.
- **Known issue**: due to a bug in the terminal the output is not printed on first run (see https://github.com/microsoft/vscode/issues/160914)
- Run the file again
- Ensure that the Python environment is used
- Make use of the additional source packages you have installed into the environment (e.g. import the package into a Python file and use some API from it).
- start a REPL by running the command `Python WASM: Start REPL`
- make sure the REPL works and that you can use the additional source packages in the REPL as well.

**Comment by brettcannon** [comment]
If anyone wants a small, simple, pure Python package to install from PyPI, https://pypi.org/project/trove-classifiers/ is my go-to choice.

**Comment by brettcannon** [comment]
And if you want to force pure Python wheels, use the `--implementation py` option.

**Comment by brettcannon** [comment]
@aiday-mar not sure if you left yourself assigned on purpose or not, so I didn't close the issue even though you checked the box as being done.

**Comment by aiday-mar** [comment]
Hi, ah yes sorry I will unassign myself and close this test-plan item.
