### ISSUE TITLE
Toggle codelens via key bindings command 

### ISSUE THREAD

**Issue by NinoFloris** [Microsoft/vscode#16174]
I'd like a way to toggle codelens via a keyboard shortcut.

It would be very very welcome, sometimes in files where you have a lot of referenceable material packed in a small space (c# properties for instance) it's very distracting and other times it's the only way to get to things (c# debug test for instance).

Being able to toggle codelens would be the bee's knees.

EDIT: Oh and to add to this, being able to toggle codelens is also very nice from a responsiveness perspective as omnisharp really has a tough time serving all those "x references" queries. Seeing huge cpu spikes where mono.osx is at 200% for a while before dropping to normal levels again.
Not a problem if you stay in 1 file but going from file to file you keep hitting the language server with quite some load.

**Comment by chrmarti** [comment]
Using this as a feature request for the base VSCode. Please consider also filing a feature request for Omnisharp.

**Comment by alexandrudima** [comment]
There is a setting `"editor.codeLens"` that can be set to false to disable the feature. One could write an extension that changes the setting value via a keybinding.

**Comment by mika76** [comment]
Seems somebody already might have done it: https://marketplace.visualstudio.com/items?itemName=cmlewis89.vscode-togglecodelens

Doesn't work for me though...

**Comment by NinoFloris** [comment]
Yes this should just be a built in command/shortcut. The feature is built
in so the command to do something with it should also be in the box

**Comment by rebornix** [comment]
It's a good extension candidate and you can follow https://medium.com/hack-visual-studio-code/toggle-any-setting-in-vs-code-using-keyboard-shortcut-arguments-cdb5ddc56955 to get your preferred extension to archive that.

**Comment by mjbvz** [comment]
Closing as extension candidate. Please try this extension to toggle settings: https://marketplace.visualstudio.com/items?itemName=rebornix.toggle
