### ISSUE TITLE
@misolori When selecting "Hide Layout Control", how do I get it back?

### ISSUE THREAD

**Issue by abhijitchikane** [microsoft/vscode#161796]
@misolori When selecting "Hide Layout Control", how do I get it back?

_Originally posted by @jrieken in https://github.com/microsoft/vscode/issues/150916#issuecomment-1148441382_
      I don't see option to get back the controls once again. I could only see the option to toggle the actual views and not the control itself

**Comment by gjsjohnmurray** [comment]
In 1.71.2 the context menu on the window's titlebar should give you the option.

**Comment by jrieken** [comment]
Yes, this now works with normal context menu

<img width="338" alt="Screenshot 2022-09-27 at 08 22 46" src="https://user-images.githubusercontent.com/1794099/192448416-678e7943-a3b2-4f3c-ba5b-2df71ad24a3c.png">

**Comment by abhijitchikane** [comment]
this is bit confusing because right click on the triple dot action menu(...) is something new for me
