### ISSUE TITLE
VS Code freezes when there is lot of content in termina

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161758]
- Open terminal and run `./scode/test.sh` command
- After it finishes, there is a freeze. Some times I see window is not responding dialog
- Now type `clear` command
- Freezes again

Here is the profile that is captured while running `./scode/test.sh` command

[CPU-20220926T112910.cpuprofile.txt](https://github.com/microsoft/vscode/files/9645033/CPU-20220926T112910.cpuprofile.txt)

Here is the profile that is captured while running `clear` command

[CPU-20220926T114329.cpuprofile.txt](https://github.com/microsoft/vscode/files/9645039/CPU-20220926T114329.cpuprofile.txt)

I have set `terminal.integrated.scrollback` to `100000`

**Comment by Tyriar** [comment]
@meganrogge getOutputMatch can be too expensive:

![image](https://user-images.githubusercontent.com/2193314/192274901-a37153c2-18d0-41d3-8a1c-9895fc22a07c.png)

Is some quick fix not working on just a small line range?

**Comment by Tyriar** [comment]
The second one:

![image](https://user-images.githubusercontent.com/2193314/192275318-69c20f34-6b47-45f3-b375-5a8658ef9248.png)
