### ISSUE TITLE
Test custom view height

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#161778]
Refs: https://github.com/microsoft/vscode/issues/122283

- [x] anyOS @mjbvz
- [x] anyOS @benibenj

Complexity: 4
Roles: Developer

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161778%0A%0A&assignees=alexr00)

---

There's a new `initialSize` property that can be set on contributed views in package.json. You can see an example here: https://github.com/microsoft/vscode-pull-request-github/blob/558bc660b691b58d9dfa22337487281d340aa492/package.json#L501-L515

To test:
1. Open a folder that contains an extension project with contributed views (such as the [tree-view-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample). 
2. In the extension's package.json, add the `initialSize` property to a couple views. 
3. Read the hover information for `initialSize`. Verify that the hover information is clear. Verify that everything in the hover message is accurate.

**Comment by mjbvz** [comment]
@alexr00 Is there a way to reset the views? I'm having trouble testing since `InitialSize` is only used if the views have not been already resized

**Comment by benibenj** [comment]
I changed the name of the contributed view in `package.json` every time I changed the `InitialSize` for testing

**Comment by mjbvz** [comment]
Thanks @benibenj! Seems to work well in my testing
