### ISSUE TITLE
Test: Improvements to Edit Sessions debug view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#161860]
Refs https://github.com/microsoft/vscode/issues/156334, https://github.com/microsoft/vscode/issues/156337

- [x] Windows @gregvanl
- [x] macOS @sandy081
- [x] Linux @deepak1556

Authors: @joyceerhl

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161860%0A%0A&assignees=joyceerhl)

---

We have an Edit Sessions view for debugging purposes. This view now shows you which machine each Edit Session originates from.

1. Have some uncommitted edits in a desktop git clone of a repo or a vscode.dev repo
2. Run `Store Current Edit Session` (ideally, do this from a couple of different places, e.g. VS Code desktop as well as VS Code for the web)
3. Run `Show Edit Sessions`
4. Verify that the Edit Sessions view now tells you which machine each Edit Session came from
5. Verify that the tree node is now the repo name instead of a GUID

**Comment by sandy081** [comment]
There was one moment where it worked flawlessly that I could see sessions in browser and desktop and delete them. But most of the times I hit issues with long loading requests.

**Comment by gregvanl** [comment]
Part of the trouble I've been having may be that I don't understand how Edit Sessions are meant to work. My mental model was they were snapshots that could be applied manually to move a repo to a specific state.
It appears that Edit Sessions are more of an automatic way to apply changes to a repo when you reopen a VS Code instance on a repo which has a store Edit Session. I found the feature pretty confusing
