### ISSUE TITLE
Scrollbar decorations grow as you scroll down

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#161897]
Testing #161861

(not clear in the recording, but I had selected the initial commit in the timeline)

https://user-images.githubusercontent.com/2230985/192461958-424d88b7-337e-42b8-90ca-0a28c0b3bb19.mp4

**Comment by connor4312** [comment]
Also on https://github.com/greazer/covid-19-data/commit/f878607c6fc8d9b5258e7bcbf5ce57c529932135. I guess diff computation is just lazy? This is good in general but I think now that we have scrollbar decorations it can't be lazy.

**Comment by isidorn** [comment]
I see the same. Decorations are moving in the scrollbar as I scroll which looks like broken rendering.
