### ISSUE TITLE
Test notebook edit api

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#161840]
Test for #155245

- [x] Mac @jrieken
- [x] Linux @karthiknadig
- [x] Windows @karrtikr

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161840%0A%0A&assignees=mjbvz)

---

# Summary

The newly finalized [notebook workspace edit api](https://github.com/microsoft/vscode//blob/1723a56b2728df4160e064bb3ad76f8827e865bd/src/vscode-dts/vscode.d.ts#L3491) lets extensions add, remove, and insert notebook cells as part of an edit

For this test plan item, test out the new api and make sure it works as expected

# Testing 

- Use this branch of the extension samples: https://github.com/microsoft/vscode-extension-samples/tree/dev/mjbvz/demo-notebook-edit and checkout the code action sample

- This sample creates a code action in markdown cells of notebook deletes the first cell in that notebook. Try it out to make sure basic functionality is working

- Try using the other static methods of `NotebookEdit` to create different types of notebook edits (inserting, removing, or deleting cells)

- Try creating a workspace edit that users multiple NotebookEdits

- Try creating a workspace edit that uses a NotebookEdit in a noteobok as well as performing a normal text edit

**Comment by karthiknadig** [comment]
Nice work!! ran into same issue as #161949

When inserting markdown cells they are inserted as if "stop editing cell" was clicked. Not sure if this is expected.
