### ISSUE TITLE
Test cross origin isolation for desktop

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#161804]
Refs: https://github.com/microsoft/vscode/issues/116715

- [x] anyOS @paulacamargo25
- [x] anyOS @karrtikr
- [x] anyOS @andreamah
- [x] anyOS @sandy081
- [x] WIndows/macOS + Luna Paint @Tyriar 

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161804%0A%0A&assignees=jrieken)

---

This is a continuation of https://github.com/microsoft/vscode/issues/158792 but for desktop. 

**Background:** On desktop we now have the ability to enable cross origin isolation - that's the enabler for shared array buffers which unlocks many interesting scenarios (like "vscode-wasi"). Enabling cross origin isolation (COI) requires us to set two http header COOP and COEP. The latter means only resources that are OK with being embedded will load. This doesn't affect resources from VS Code itself but _can_ affect resources that extensions load. They need to be served with the CORP header. 

**Testing:** Check-off one of the extensions below and play around with their webview (or notebook renderering) features, like GitLens settings editor etc. Observe dev tools for errors

* quit all windows of vscode 
* restart  with the `--enable-coi` flag, e.g `code-insiders --enable-coi`
* open Developer Tool, select the "Network" tab, and check "Blocked Request"
* Keep an eye open for blocked requests
* ℹ️ we cannot fix these errors but we need to reach out to the server/CDN that serve these resources. Just append the blocked domains/urls to this issue, only file an issue against the extension if you are certain that they can fix it (inside knowledge)

The sample below is GitHub issue notebook. Notice how avatars aren't loading and how each request shows as blocked. 

<img width="1405" alt="Screenshot 2022-09-26 at 18 37 42" src="https://user-images.githubusercontent.com/1794099/192333162-5807db77-86ff-4e63-aab2-c59f154b71f7.png">

---

_tested in https://github.com/microsoft/vscode/issues/158792_

- [x] GitLens https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens
- [x] Jupyter https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter
- [x] HexEditor https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor @lramos15 
- [x] ExcelViewer https://marketplace.visualstudio.com/items?itemName=GrapeCity.gc-excelviewer
- [x] Volar https://marketplace.visualstudio.com/items?itemName=Vue.volar

_new items_
- [x] LunaPaint @Tyriar 
- [x] Bicep https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-bicep @karrtikr 
- [ ] Quokka.js https://marketplace.visualstudio.com/items?itemName=WallabyJs.quokka-vscode @sandy081 
- [x] Latex Workshop https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop
- [x] Tabnine https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode

**Comment by sandy081** [comment]
## Quokka.js

Here are the blocked requests I observed when opening the `Quokka.js: Manage License Key` page.

- https://quokkajs.com/assets/img/vsc-recent-files.gif
- https://quokkajs.com/assets/img/vsc-auto-log.gif
- https://quokkajs.com/assets/img/vsc-sticky-values.gif

I

**Comment by Tyriar** [comment]
Is this meant to work on Windows? When I run `code-insiders --enable-coi` I don't see the headers and therefore cannot access `window.SharedArrayBuffer`:

![image](https://user-images.githubusercontent.com/2193314/192590337-11a1df19-07f5-47ee-ab81-5730a4996c1b.png)

I do on my mac though:

<img width="636" alt="Screen Shot 2022-09-27 at 10 00 57 am" src="https://user-images.githubusercontent.com/2193314/192590474-9eb50eab-de5d-4933-bb7f-fe543d82f18e.png">

**Comment by Tyriar** [comment]
Luna Paint requests seems to work fine. With minimal changes I can re-enable SABs but I haven't done some of the required work to [handle Workers](https://github.com/Microsoft/vscode-docs/blob/eb58fbbf6c26e781f33aec963eeba0139337ba87/api/extension-guides/webview.md#using-web-workers), so I can't turn that stuff back on yet unfortunately.

So it's just the Windows problem above.

**Comment by andreamah** [comment]
Tabnine seems to be good on Windows (tested the hub page and its AI Assistant viewlet)

**Comment by jrieken** [comment]
> Is this meant to work on Windows?

Yes. Filed: https://github.com/microsoft/vscode/issues/162141. The request misses the `&vscode-coi=3` parameter which means the renderer itself isn't cross origin isolated which likely means the flag is getting lost somewhere along the way

**Comment by karrtikr** [comment]
No blocked requests reported from Bicep on Windows (tested getting started exp and visualizer)

**Comment by paulacamargo25** [comment]
Latex Workshop seems to be good, no blocked requests reported  (Tested on macOS)
