### ISSUE TITLE
 Cannot read property 'fsPath' of null

### ISSUE THREAD

**Issue by vscodeerrors** [Microsoft/vscode#16189]
Issue Id: <b>1338d86c-ada9-7591-e66c-adeaf70e195e</b><br /><br />*Versions* <br />- 1.8.0-insider (11/25/2016 9:15:37 AM)<br />*Stack* <br />TypeError: Cannot read property 'fsPath' of null<br />[/vs/workbench/parts/preferences/browser/preferencesService.ts#L102:65 (fsPath)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L102:65 (fsPath))<br />[/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L162:27 (resolvePreferencesEditorModel)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L162:27 (resolvePreferencesEditorModel))<br />[/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L155:52 (onModelChanged)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L155:52 (onModelChanged))<br />[/vs/base/common/event.ts#L155:12 (apply)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/event.ts#L155:12 (apply))<br />[/vs/base/common/eventEmitter.ts#L303:9 (func)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L303:9 (func))<br />[/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents))<br />[/vs/editor/common/commonCodeEditor.ts#L216:7 (emit)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/editor/common/commonCodeEditor.ts#L216:7 (emit))<br />[/vs/workbench/browser/parts/editor/stringEditor.ts#L111:14 (setModel)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/stringEditor.ts#L111:14 (setModel))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'fsPath' of null<br />[/vs/workbench/parts/preferences/browser/preferencesService.ts#L102:65 (fsPath)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L102:65 (fsPath))<br />[/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L162:27 (resolvePreferencesEditorModel)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L162:27 (resolvePreferencesEditorModel))<br />[/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L155:52 (onModelChanged)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesEditor.ts#L155:52 (onModelChanged))<br />[/vs/base/common/event.ts#L155:12 (apply)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/event.ts#L155:12 (apply))<br />[/vs/base/common/eventEmitter.ts#L303:9 (func)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L303:9 (func))<br />[/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L182:4 (safeInvoke1Arg))<br />[/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L201:8 (_emitToSpecificTypeListeners))<br />[/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/eventEmitter.ts#L216:8 (_emitEvents))<br />[/vs/editor/common/commonCodeEditor.ts#L216:7 (emit)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/editor/common/commonCodeEditor.ts#L216:7 (emit))<br />[/vs/workbench/parts/files/browser/editors/textFileEditor.ts#L145:14 (setModel)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/files/browser/editors/textFileEditor.ts#L145:14 (setModel))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'fsPath' of null<br />[/vs/workbench/parts/preferences/browser/preferencesService.ts#L310:82 (fsPath)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L310:82 (fsPath))<br />[/vs/workbench/parts/preferences/browser/preferencesService.ts#L80:38 (getConfigurationTarget)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L80:38 (getConfigurationTarget))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L430:27 (fire)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/editorPart.ts#L430:27 (fire))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1170:0 (onComplete))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L852:0 (_notify))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1068:0 (enter))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1036:0 (_run))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />

**Comment by vscodeerrors** [comment]
Here is another similar callstack 

TypeError: Cannot read property 'fsPath' of null<br />[/vs/workbench/parts/preferences/browser/preferencesService.ts#L310:82 (fsPath)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L310:82 (fsPath))<br />[/vs/workbench/parts/preferences/browser/preferencesService.ts#L80:38 (getConfigurationTarget)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/parts/preferences/browser/preferencesService.ts#L80:38 (getConfigurationTarget))<br />[/vs/base/common/callbackList.ts#L63:26 (apply)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/callbackList.ts#L63:26 (apply))<br />[/vs/base/common/event.ts#L117:26 (call)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/base/common/event.ts#L117:26 (call))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L856:26 (fire)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/editorPart.ts#L856:26 (fire))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L548:8 (onGroupFocusChanged)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/editorPart.ts#L548:8 (onGroupFocusChanged))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L510:8 (doCloseGroup)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/editorPart.ts#L510:8 (doCloseGroup))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L493:8 (doCloseActiveEditor)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/editorPart.ts#L493:8 (doCloseActiveEditor))<br />[/vs/workbench/browser/parts/editor/editorPart.ts#L485:8 (doCloseEditor)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/src/vs/workbench/browser/parts/editor/editorPart.ts#L485:8 (doCloseEditor))<br />[vs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete)](https://github.com/microsoft/vscode/blob/0b847998d914ff84fd9c13b2972cc8803745c24d/srcvs/workbench/electron-browser/vs/base/common/winjs.base.raw.js#L1566:0 (onComplete))<br />

**Comment by sandy081** [comment]
Will fix during debt week

**Comment by sandy081** [comment]
Fixed upstream by changes in `PreferencesService.ts`
