### ISSUE TITLE
Test: builtin terminal quick fixes

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#161846]
Refs https://github.com/microsoft/vscode/issues/151937

- [x] Windows @connor4312 
- [x] macOS @isidorn 
- [x] Linux @lramos15 

Complexity: 3

Authors: @meganrogge @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161846%0A%0A&assignees=meganrogge,Tyriar)

---

Verify that the terminal quick fix experience aligns with that in the editor area.

Currently, the builtin quick fixes include:

- _git similar_ : `git sttatus`
- _git push_ : checkout a branch that has no upstream and `git push`
- _git create PR_ : `git push --set-upstream origin <branch-name>`
- _free port_ : launch a server or task that uses a specific `<port>` then launch that again so you see an error related to `address already in use`

Known issues:
- #161775

**Comment by connor4312** [comment]
Are there steps needed to enable the suggest widget? I have shell integration on with Powershell 7 on Windows, however I don't see the widget appear on the suggest misspelling, or by attempting to manually trigger via `Ctrl+.` like I can in the editor

**Comment by isidorn** [comment]
Cool feature. I think this needs some polishing and will be a hit 👏 
Do we have a story how to make this contributable somehow? So more and more suggestions could appear in the quick fix?

**Comment by meganrogge** [comment]
and have this contribution point https://github.com/microsoft/vscode/issues/145234

**Comment by meganrogge** [comment]
@connor4312 what input are you trying?

we have an issue tracking this that hasn't yet been completed
https://github.com/microsoft/vscode/issues/161595#issuecomment-1256693964

**Comment by lramos15** [comment]
Works well. I can't seem to find out how to get the free port suggesting to trigger though. I just use the very basic express example http://expressjs.com/en/starter/hello-world.html and I don't even see the ports panel saying the port is in use so not sure if VS Code is not detecting it.

**Comment by meganrogge** [comment]
@lramos15 this is a little hard to test atm because some servers don't send an exit code when the address is already in use - such as the VS Code server, so we won't trigger the suggestion. 

a way to test would be to run `npm start server` in _two_ terminals in the xterm.js repo

**Comment by connor4312** [comment]
> @connor4312 what input are you trying?
> 
> we have an issue tracking this that hasn't yet been completed [#161595 (comment)](https://github.com/microsoft/vscode/issues/161595#issuecomment-1256693964)

I don't think that's the same issue.

Here's a recording:


https://user-images.githubusercontent.com/2230985/192570243-326d8d6b-3d63-4222-abbd-18b3199e2578.mp4

**Comment by connor4312** [comment]
@meganrogge on today's Insiders which includes your PR from yesterday, I'm still not able to see the suggestion either for any git quick fixes. I also tried the server case by running `node -e 'net.createServer().listen(3000)'` and didn't see suggestions there either. I tried running with a fresh `--user-data-dir` with the same result, but decorations and "run recent command" seem to work, so shell integration overall is fine.

<img width="686" alt="image" src="https://user-images.githubusercontent.com/2230985/192709940-329d7023-0b34-42df-92be-7c94d94ebc1a.png">

**Comment by Tyriar** [comment]
@connor4312 we actually only scan up 20 lines and you have a pretty large stack trace there. That number was pretty arbitrary and we could bump it up some more, maybe 30?

**Comment by Tyriar** [comment]
@connor4312 hopefully it'll work after https://github.com/microsoft/vscode/issues/162175

**Comment by Tyriar** [comment]
@connor4312 that won't work as it's missing an IP at the start. Created https://github.com/microsoft/vscode/issues/162183 and https://github.com/microsoft/vscode/issues/162175 to cover your case

**Comment by connor4312** [comment]
Ah, good finds. Though even specifying an address, I don't get anything. The I/O in that case looks like:

<img width="904" alt="image" src="https://user-images.githubusercontent.com/2230985/192818890-c573f901-582e-4116-b079-b92e1cb04e51.png">

I checked that I am still on the latest Insiders:

```
Version: 1.72.0-insider (user setup)
Commit: 835d39cfac9ede6c7c90678c8d6c3d4d0171ed6d
Date: 2022-09-28T05:20:11.324Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```

and powershell version:

```
PS C:\Users\connor\Github\enumerate-win32-apps> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

I feel like I'm doing something wrong, but am not sure what it would be... 🤔

**Comment by Tyriar** [comment]
@connor4312 your stack trace was long enough that it was on the 20th line, we only scan up 20 currently so there might be an off by one error so it ends up just below the cut off?

**Comment by connor4312** [comment]
Just debugging in Insiders, it looks like the opposite: the free port matcher doesn't match anything unless the output is more than its configured 20 lines

<img width="499" alt="image" src="https://user-images.githubusercontent.com/2230985/192822989-3b0e10a7-a4f9-4b2d-aacc-dd2e8e21e58c.png">

If I add `console.log('\r\n'.repeat(10))` then it works

**Comment by Tyriar** [comment]
@connor4312 good find! Could you create an issue?
