### ISSUE TITLE
Test: Notebook Diff Editor overview ruler

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#161861]
Refs https://github.com/microsoft/vscode/issues/146224

- [x] anyOS @isidorn
- [x] anyOS @connor4312

Authors: @rebornix 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161861%0A%0A&assignees=rebornix)

---

We now render changes decorations in the notebook diff editor, please test it's working as expected (like the text editor)

For example

* Open a notebook
* Go to Timeline view, click on any entry
* A notebook diff editor opens, please check the decorations for diff changes are rendered at the right position

**Comment by isidorn** [comment]
+1 on all the issues @connor4312 found.
imho if we must lazily compute these decorations then the experience might be better without them, since right now I mostly find them confusing.

**Comment by rebornix** [comment]
@connor4312 @isidorn thank you both for the thorough testing, the cell height being dynamic (in a virtualized list) is leading to the confusion (excluding the misalignment bugs). I'll consider having it disabled for the coming stable and having it back on in Insiders to give us time for polish.

**Comment by isidorn** [comment]
@rebornix makes sense, thanks 🙏
