### ISSUE TITLE
Test: `isMobile` context key

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#161855]
Refs https://github.com/microsoft/vscode/issues/160675

- [x] anyOS @lszomoru
- [x] anyOS @karrtikr

Authors: @joyceerhl

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161855%0A%0A&assignees=joyceerhl)

---

There is now an `isMobile` context key which checks whether we are running on a mobile device e.g. through vscode.dev or github.dev.

Verification:
1. Create and publish an extension with commands that use `isMobile` in their when clause
2. Ensure that on mobile those commands are properly hidden/shown

**Comment by karrtikr** [comment]
How to view command palette on `vscode.dev` on a mobile device, say IPhone?

**Comment by joyceerhl** [comment]
Hamburger menu > View > Command palette should do it.
