### ISSUE TITLE
Merge Editor: Git Integration Experience

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#161833]
- [x] anyOS @sandy081
- [x] anyOS @amunger
- [x] anyOS @daviddossett

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161833%0A%0A&assignees=hediet)

---

This is an issue to test the Git integration experience of the 3 way merge editor.

You can use [this script](https://github.com/hediet/diff-merge-dataset/blob/c3d49e5da6ed8456ad807a6133524468d66aa037/merges/merge-equal-parts/git-playground/script.sh) to automate creating a conflict.
You can use `git merge --abort` to reset a merge and start over.
Ideally find a real-world merge conflict that you experienced in the past and resolve it using the merge editor.

* Make sure you didn't configure `"git.mergeEditor"` in your settings
* Open a file under conflict. Verify a blue button is shown in the bottom to open the merge editor.
* Try to understand and resolve the conflict.
* Verify the merge editor can be used to successfully resolve the conflict
* Verify accepting a merge conflict works
* Verify closing the merge editor works and reasonable messages are shown

**Comment by amunger** [comment]
still hitting https://github.com/microsoft/vscode/issues/160910 for notebooks, everything else looks fine
