### ISSUE TITLE
Test: flow for missing Edit Sessions enablement when using Continue On from web to desktop

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#161872]
Refs https://github.com/microsoft/vscode/issues/161266

- [x] Windows @deepak1556
- [x] macOs @isidorn
- [x] Linux @TylerLeonhardt

Authors: @joyceerhl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161872%0A%0A&assignees=joyceerhl)

---

## Background
Previously Edit Sessions had to be manually enabled across each VS Code client (web, desktop, different machines). This caused issues if you were using Continue On from web to desktop and had not yet enabled Edit Sessions in desktop, because the desktop instance would not have Edit Sessions enabled, and so your changes would silently fail to restore in the destination. There is now a flow to onboard users to Edit Sessions if they move from web to desktop and have not yet enabled Edit Sessions in VS Code desktop.

## Verification
1. Turn off Edit Sessions on your desktop machine if you were signed in before, either from the account menu or using the `Turn off Edit Sessions` command in the palette
2. Open a GitHub or Azure Repos repo in https://insiders.vscode.dev
3. Make some uncommitted changes
4. Select Continue Working On > Clone Locally or Continue Working On > Reopen on the Desktop
5. VS Code should launch on the desktop
6. You should get a quickpick prompting you to turn on Edit Sessions in desktop
7. If you hit escape, a badge will now appear in the accounts menu which says 'Check for pending edit sessions' on hover
8. Click on the Turn On Edit Sessions... item in the accounts menu and sign in with Microsoft or GitHub
9. Your edits from step 3 should now appear
10. Also verify that the quickpick and badge do not appear unexpectedly, e.g. if you use Continue On and don't have any working changes

**Comment by isidorn** [comment]
I am blocked on https://github.com/microsoft/vscode/issues/161932
I can continue testing after that gets resolved for me :)

**Comment by TylerLeonhardt** [comment]
This worked sooo well and probably will convince me to use GitHub Repos in Desktop more often!
