### ISSUE TITLE
Use single letter for default profile's short name?

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#161865]
IMO using an icon for a profile looks strange—especially for our default profile. What if we just used "D" (or its translated equivalent)?

<img width="125" alt="CleanShot 2022-09-26 at 16 19 18@2x" src="https://user-images.githubusercontent.com/25163139/192397406-81b0198d-7028-4bda-8db3-f3ad2476509b.png">

**Comment by bpasero** [comment]
I wonder if the default profile should have a fixed icon to always reflect that it is the default?

**Comment by sandy081** [comment]
I do not like using letter `D` for default profile because it might represent a person's first letter and can be opinionated. An icon would be abstract and neutral.

**Comment by daviddossett** [comment]
> I wonder if the default profile should have a fixed icon to always reflect that it is the default?

I think that's what @sandy081 had in mind but to my eyes it looks really out of place to have a small codicon nested in there amongst the other large activity bar icons.
