### ISSUE TITLE
Test built-in audio/video preview

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#161823]
Test for #159106 

- [x] Mac @lszomoru
- [x] Linux @rzhao271
- [x] Windows @amunger

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161823%0A%0A&assignees=mjbvz)

---

# Summary

We now include a basic preview for audio and video files. For this test plan item, test out the basic functionality of these new previews

# Testing

- Try opening audio files in VS Code

    The following formats should work: mp3, wav, ogg

- Try opening a video file in VS Code

    The following formats should work: mp4, webm

Both of these previews use Chrome's built-in controls. This limits our ability to customize and theme. I opted to use these controls so we don't have to maintain our own code here. They also match how other video/audio files are rendered in VS Code (such as in notebooks)

**Comment by usernamehw** [comment]
`.opus` doesn't work. It seems like they are not in the list of added codecs https://github.com/microsoft/vscode/issues/156558#issuecomment-1213068895

**Comment by amunger** [comment]
webm and .opus both just have an error messsage when attempting to open on Windows (screenshot). and mp4 does not have audio available (linked issue)

![image](https://user-images.githubusercontent.com/2019016/192624867-85e0d36e-2f3f-4642-a4d9-213ab9fecd96.png)

**Comment by mjbvz** [comment]
@usernamehw Thanks. Yes should be `ogg` instead of `opus`

**Comment by mjbvz** [comment]
@amunger webm works for me. Can you please share the file that doesn't work:

![Screen Shot 2022-09-27 at 1 48 56 PM](https://user-images.githubusercontent.com/12821956/192632424-547b8d65-ca4c-4183-9b68-26e508bb21be.png)

**Comment by amunger** [comment]
[sample_960x540.webm](https://user-images.githubusercontent.com/2019016/192642814-f23dc958-a807-42ac-b03d-858e5e08a9b2.webm)

**Comment by mjbvz** [comment]
@amunger Thanks. The issue is that the video from your example is vp9, while we only support vp8 (the example I tested was using vp8)

`webm` is a container format, which makes it hard for us to know if the video will actually be supported as or not until we try opening it

**Comment by amunger** [comment]
✅ .ogg
