### ISSUE TITLE
Test Search Tree

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#161849]
Refs #20224, #161545

- [x] macOS @lszomoru
- [x] linux @karthiknadig
- [x] windows @bamurtaugh

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161849%0A%0A&assignees=andreamah)

---
## Set up:
Make sure you're on the latest version of insiders.

## Testing:
We can now see search results in a tree view from within the Search Viewlet. 

To see this, click on the magnifying glass on the activity bar (on the left by default) and search for something (shows results from the open workspace(s) plus any loose open files). **The button to toggle the search file tree is at the top of the viewlet. See the GIF below for reference**
![Recording 2022-09-26 at 13 05 52](https://user-images.githubusercontent.com/31675041/192370220-3af65338-6933-412e-8a55-128ea28e12fc.gif)

Please try testing it with different files/folders open in the editor. Test the tree view with different folder structures + etc. and **make sure that the list view also still works as expected**.

Here are a couple of things that I'd like you to particularly test.
### Basic Search and Replace
When you perform a search in either view, the results should be what you expect them to be. Try also using search + replace to see if that still works. Try selecting multiple results at once and act upon them (dismiss or replace) to see if multiselect still works. Double-check that you can't get a result to appear twice.

### Test Search for Really Nested File
Try searching (and replacing) a file that is nested in a bunch of folders to see if it works and performance is still acceptable.

#### Tree Compression
When a folder is the only child of another folder (and so on), the nodes should be compressed. 
![image](https://user-images.githubusercontent.com/31675041/192389286-1d3cde2c-d927-457c-b6bd-56456e4c2f2d.png)

### Test Single and Multi-root
Try searching in single and multi-root workspaces to see if the list and tree views work.

#### Test Collapse/Expand
Ensure that the collapse/expand action (triggers when pressing the collapse/expand button on the top left corner) is correct depending on the state of the nodes. See the GIFs for guidance.

##### In Tree View
**Collapses the file nodes**. If this is satisfied already, **collapses everything**. If this is satisfied, **expands everything**.
![Recording 2022-09-26 at 13 09 48](https://user-images.githubusercontent.com/31675041/192370404-1fca448d-f5c1-41b0-9ee1-14b6d569371f.gif)

##### In List View
Collapses all if anything is expands. Expands all if everything is collapsed.
![Recording 2022-09-26 at 14 13 29](https://user-images.githubusercontent.com/31675041/192381926-e0767808-373f-48c3-a5c5-38f4e5341b8e.gif)

#### In Tree View
![Recording 2022-09-26 at 16 00 46](https://user-images.githubusercontent.com/31675041/192395540-1c856d13-9bf1-409b-9890-a2f0c22bd1a4.gif)
**Collapses the file nodes**. If this is satisfied already, **collapses all children of a root folder**. If satisfied already, **collapses everything**. If this is satisfied, **expands everything**.

#### In List View
**Collapses the file nodes**, then **collapses the roots**, then **expands all**.
![Recording 2022-09-26 at 14 23 11](https://user-images.githubusercontent.com/31675041/192383170-0f389aff-2d5a-48aa-b1b3-eda8c84d875c.gif)

### Test setting for default search view.
Toggle the setting for `search.defaultViewMode` to set a default view type for search results and ensure that you see the correct view when opening the editor in a new workspace. Note that reloading in the same workspace will persist the view type.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/31675041/192383467-820ba2ae-d83e-41e9-ad03-35e4127beb8d.png">

**Comment by karthiknadig** [comment]
Nice work!!!

**Comment by lszomoru** [comment]
Great job 🚀
