### ISSUE TITLE
Wrong position of HC border on profiles activity bar item

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#161862]
<img width="259" alt="CleanShot 2022-09-26 at 15 51 26@2x" src="https://user-images.githubusercontent.com/25163139/192394463-38796566-b0b9-4f59-a8dc-5d95e1b3d8c1.png">

**Comment by sandy081** [comment]
Can you please check in today's insiders if the positioning is correct as I have done some changes yesterday?

**Comment by daviddossett** [comment]
Hmm still seeing the same behavior after updating.

**Comment by sandy081** [comment]
Oh yeah I repro it too. Sorry about it.
