### ISSUE TITLE
Consider using background instead of border for profiles activity bar item

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#161868]
The original designs had something closer to this for the default background color. IMO it isn't trying to be an icon like the other items and the border makes it feel like an icon vs. a unique element.

I also think the background and foreground should be the only customizable elements to start. I think I saw a foreground token, but not sure it was possible to do background yet.

<img width="247" alt="CleanShot 2022-09-26 at 16 29 09@2x" src="https://user-images.githubusercontent.com/25163139/192398320-9593e928-2c13-46db-b823-ca1837a02f99.png">

**Comment by bpasero** [comment]
I also like this more over the border 👍

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/192754120-d29b94db-ce3c-4ab5-bcf5-41a3ef75eff3.png)

**Comment by bpasero** [comment]
I like it but maybe with smaller font size? Here is with `11px` for example:

![image](https://user-images.githubusercontent.com/900690/192764146-68550ca3-239f-4cb3-9260-6f03832128d4.png)

**Comment by sandy081** [comment]
Current font size goes well with all (emoji, codicons) and also symmetric with activity bar icons.
