### ISSUE TITLE
Extensions don't work on Win10

### ISSUE THREAD

**Issue by mykolahnid** [Microsoft/vscode#16182]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-simpler-icons|davidbabel|1.3.0|
|tslint|eg2|0.6.5|
|vscode-npm-script|eg2|0.1.2|
|beautify|HookyQR|0.6.0|
|Angular2|johnpapa|1.0.2|
|prettify-json|mohsen1|0.0.3|
|csharp|ms-vscode|1.5.3|
|resharper9-keybindings|ms-vscode|1.1.0|
|vscode-icons|robertohuertasm|4.0.2|
|code-settings-sync|Shan|2.3.8|
|autoimport|steoates|1.2.2|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Start VSCode
2. vscode-icons, tslint, autoimport extensions don't work

**Comment by chrmarti** [comment]
`vscode-icons` was replaced with built-in functionality, see https://code.visualstudio.com/blogs/2016/09/08/icon-themes

Please uninstall that first and check if `tslint` works when all other extensions are disabled (or uninstalled). Please do the same for `autoimport`.

**Comment by mykolahnid** [comment]
1. uninstalled all extensions except tslint.
2. uninstalled VSCode.
3. installed VSCode with "Run as administrator".
4. tslint doesn't work.
5. details why do I think that it doesn't work:
there is a line _baseUrl: string = ""; and on Windows 8 it shows hint:
[tslint] " should be ' (quotemark)

don't really understand how vscode-icons was replaced. when I go to File Icon Theme, it shows me option "Find more in the Marketplace..." which then shows me vscode-icons which I can install and then select among icon themes - everything working on Win8 (VSCode version 1.7.2), but not on Win10.

**Comment by joaomoreno** [comment]
Please file an issue with https://github.com/Microsoft/vscode-tslint

**Comment by joaomoreno** [comment]
`vscode-icons` is still working, it just provides a different set of icons.

**Comment by mykolahnid** [comment]
> Please file an issue with https://github.com/Microsoft/vscode-tslint

since tslint isn't the only extension which doesn't work, I doubt it's the problem with tslint

**Comment by joaomoreno** [comment]
What is the problem with vscode-icons and with autoimport?

**Comment by mykolahnid** [comment]
they don't work...
as I have described in one of previous comments,

> when I go to File Icon Theme, it shows me option "Find more in the Marketplace..." which then shows me vscode-icons which I can install and then select among icon themes - everything working on Win8 (VSCode version 1.7.2), but not on Win10.

any other icon set also doesn't work (e.g. vscode-simpler-icons mentioned in my first comment)

autoimport: in short, it doesn't work.
to put it more detailed:
1. uninstall all extensions
2. restart vscode
3. install autoimport
4. restart vscode
5. line let headers = new Headers();
doesn't give me an option to "Import Headers from @angular/http" (which is an expected behavior and works on Win8)

**Comment by joaomoreno** [comment]
Are you using the same workspace on both machines? Same files?

**Comment by joaomoreno** [comment]
@dbaeumer  How can @mykolahnid get more information from tslint not working?

**Comment by dbaeumer** [comment]
@mykolahnid when tslint is enable there should be a TSLint status item in the status bar. You can click on it and see a log which will have more information

@egamma FYI.

**Comment by egamma** [comment]
@mykolahnid 

regarding:
> details why do I think that it doesn't work:
there is a line _baseUrl: string = ""; and on Windows 8 it shows hint:
[tslint] " should be ' (quotemark)

pls see https://github.com/Microsoft/vscode-tslint/issues/144#issuecomment-264121538
pls try it with another tslint warning that has a Fix, e.g., `no-unused-variable`

**Comment by mykolahnid** [comment]
@joaomoreno yes same
@dbaeumer there is no status item
@egamma no-unused-variable doesn't work
