### ISSUE TITLE
Test: Hyperlink terminal sequences

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#161851]
Refs: https://github.com/microsoft/vscode/issues/39278

- [x] macOS @sandy081
- [x] windows @TylerLeonhardt 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161851%0A%0A&assignees=Tyriar)

---

The terminal now supports printing hyperlinks (text that points to a url) in the terminal. The full behavior is described at https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda (we do not support the id attribute though).

Essentially you echo the following:

```
\x1b]8;; <url> \x1b\ <label> \x1b]8;;\x1b\
```

Here's an example of how to write one in bash:

```
printf '\e]8;id=abc;http://example.com/\e\\This is a link中国\e]8;;\e\\\n'
```

There are some more examples here:

https://github.com/xtermjs/xterm.js/blob/37c722d556e4b7e15ef55b63da41a93f87ddd43c/demo/client.ts#L876-L894

It's fine to test either bash or zsh on macOS.

**Comment by TylerLeonhardt** [comment]
It looks like this only works in Win11. I had @Tyriar run commands for me on his machine.... but I also verified this worked on macOS as well.

Oh also, PowerShell has a neat little feature:
```
PS > $PSStyle.FormatHyperlink("Hi friends!", "https://github.com/")
```
![image](https://user-images.githubusercontent.com/2644648/192608420-deea7099-ae80-4939-9332-5f6e75d7cc6e.png)

**Comment by autoantwort** [comment]
Why does this only works on Windows 11?

**Comment by Tyriar** [comment]
@autoantwort it needs support in [conpty](https://github.com/microsoft/terminal) which is a feature that's shipped with Windows

**Comment by autoantwort** [comment]
Hm ok. Because Windows Terminal also supports hyperlinks on Windows 10

**Comment by Tyriar** [comment]
@autoantwort Windows Terminal builds and ships conpty as part of their application, this is something we've considered but it seems too expensive for us to do currently.
