### ISSUE TITLE
Test: Continue On end-to-end scenarios

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#161875]
Refs https://github.com/microsoft/vscode/issues/160047

- [x] Windows @amunger
- [x] macOs @bpasero
- [x] Linux @karthiknadig

Authors: @joyceerhl

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161875%0A%0A&assignees=joyceerhl)

---

With this release, we now support the following Continue On transitions in core, accessible via the `Continue Working On` command in the palette. When you use Continue On, any uncommitted changes you have created in your current workspace should travel with you to the destination workspace:

![image](https://user-images.githubusercontent.com/30305945/192405616-d9c56a5d-fbe8-4b2e-aa51-212e3a2b6fb7.png)

Please play with these transitions across insiders.vscode.dev and VS Code desktop. In particular, besides filing issues for bugs and UX issues, please also file issues for missing features/transitions.

Known missing transitions:
- https://github.com/microsoft/vscode/issues/161874

**Comment by joyceerhl** [comment]
@bpasero do you have the GitHub Codespaces extension installed? That should be sufficient for the Create New Codespace option to appear.

**Comment by bpasero** [comment]
Ah I see, yeah now when I install it it seems better.

**Comment by amunger** [comment]
is it expected that `continue on desktop` from insiders.dev opens vscode stable?

**Comment by joyceerhl** [comment]
@amunger are you using Continue On > Clone Locally, or Continue On > Reopen on Desktop? The quality of VS Code (stable/insiders) should always be preserved.
