### ISSUE TITLE
Test: `l10n-dev` & `l10n` packages

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#161870]
Refs: #82595

- [x] anyOS: @dbaeumer
- [x] anyOS @joyceerhl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23161870%0A%0A&assignees=TylerLeonhardt)

---

### Goals

The goal of this test plan item is to explore what a non-Microsoft user will have to go through to support localization in their extension. The prediction is that most extensions won't have an entire team of translators at the ready translating strings... and instead an extension will need to crowd source a lot of this.

I have added a sample to `vscode-extension-samples` that demonstrates how an extension might do this by introducing the main components of localization in the README and providing some localized strings checked in to the repo. I want you to:

* Read the README to see if it makes sense (run any commands that it says to run)
* Try adding new code to the extension/package.json that introduces more strings to translate. Try running the `l10n-dev` tooling to see that these get picked up.

### Setup

In https://github.com/microsoft/vscode-extension-samples/tree/tyler/add-l10n-extension-sample I have added a new `l10n-sample`.

* Clone this repo and checkout that branch
* open the `l10n-sample` folder in vscode insiders
* You can run the extension in Japanese to get Japanese strings... or English for any other language

### Resources

Don't speak another language? No problem. Use [Pseudo Language](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-qps-ploc)! The language code is `qps-ploc` so you should be able to save a `package.nls.qps-ploc.json` and a `bundle.l10n.qps-ploc.json` and throw the strings through http://www.pseudolocalize.com/ to mimic speaking another language 😉

**Comment by dbaeumer** [comment]
@TylerLeonhardt parts of the testing is blocked due to https://github.com/microsoft/vscode/issues/161945

**Comment by joyceerhl** [comment]
Must extensions now have globally unique localization keys?

**Comment by TylerLeonhardt** [comment]
> Must extensions now have globally unique localization keys?

No. The same string will be used in those cases.... unless they have different comments because the new key for a string is:
```
message/commentcommentcomment
```
