### ISSUE TITLE
First opening of the settings editor is slow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#161982]
background: We started to monitor "very long tasks". This is based on [the long task API](https://developer.mozilla.org/en-US/docs/Web/API/Long_Tasks_API) but way more relaxed. Instead of 50ms our threshold is half the time it takes to load the renderer sources ~ 1000ms/2

* open devtools > console
* open settings UI
* notice a message like this `WARN [perf] Renderer reported VERY LONG TASK (201ms), starting auto profiling session 'd777e6a1-3dbb-4407-9937-606a2ef5ecf8'`

-- 
* reload
* repeat things with the performance recorder
* 👀 looks like creating the editor takes time but then setting input and updating config takes really long

[Profile-20220927T162338.json.txt](https://github.com/microsoft/vscode/files/9656841/Profile-20220927T162338.json.txt)

<img width="508" alt="Screenshot 2022-09-27 at 16 23 36" src="https://user-images.githubusercontent.com/1794099/192553106-985ee2db-07d6-4455-948b-8f110932c8cb.png">

**Comment by jrieken** [comment]
Looping in @sandy081 for insight/advice because most time seems to spend in the configurationModel calling `inspect`

<img width="697" alt="Screenshot 2022-09-27 at 16 26 43" src="https://user-images.githubusercontent.com/1794099/192553810-4eded99f-970a-4ac0-8169-e7e09eb9900f.png">

**Comment by sandy081** [comment]
`inspect` is expensive due to obvious reasons that it has to get values for all targets. Would be interested to know how the UI is building its view model from config model.

**Comment by rzhao271** [comment]
Merging with #179486
