### ISSUE TITLE
Notebook diff: no way to navigate between changes

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161921]
Testing #161861

Ideally there would be commands to navigate between changes. And they might deserve an action in the diff title bar.
Same as the editor diff experience.

![Screenshot 2022-09-27 at 11 02 35](https://user-images.githubusercontent.com/1926584/192483129-a7db2b50-475d-4d4d-b8ae-c81007531d80.png)

**Comment by joyceerhl** [comment]
Why is `f1:false` for these commands? I would expect them to be available from the command palette, since in a regular text editor Show Previous Change and Show Next Change both appear.
