### ISSUE TITLE
List of updates collapses after reload

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161906]
Testing #161795

I would expect the "Available Updates" view to always expand when there are entries.

![Recording 2022-09-27 at 10 19 28](https://user-images.githubusercontent.com/900690/192472869-2c22daf8-a6af-49df-8deb-657f6344bcb0.gif)

**Comment by benibenj** [comment]
This is a timing issue when reloading as we do not have the information about updates right away. Setting the collapse state works fine when using the feature regularly.

**Comment by sandy081** [comment]
May be the view can wait until installed extensions are synced with gallery?
