### ISSUE TITLE
Sign in data should be shared across profiles

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161955]
#161785

Whenever I change "Settings Profiles " I have to re-sign into everything, making syncing, github and everything very hard.

I believe that Settings profiles are not about being in "incognito" mode, it is a convenient way for users to customise settings and extensions. So sign-in data should be shared across profiles for a smoother experience.

fyi @TylerLeonhardt

**Comment by isidorn** [comment]
Another bug on top of this
1. Have profile A signed into settings sync
2. Switch to profile B that is not signed in
3. Switch back to A. You are no longer signed into settings sync 🐛

**Comment by sandy081** [comment]
I believe the sign in information is shared across profiles. I think the issue you have is when you open insiders with two different user data directories then you get signed out in another instance. Can you please check testing (switching profiles) without having another instance of VS Code pointing to different user data dir?

**Comment by isidorn** [comment]
You are right. Thanks!
Closing this as all was caused by me using VS Code insiders with different user data dirs. Sorry about the noise.
