### ISSUE TITLE
Merge UI: Input 1/2 vs Left/Right

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#161978]
Testing #161834

Using 'Left Input' and 'Right Input' would explain itself better than 'Input 1' and 'Input 2'.

**Comment by hediet** [comment]
The caller is in control of the labels. In case of the JSON feature, it will be input1 and input2.
In case of git, it is yours/theirs, remote/local, current/stashed etc, depending on the situation.

**Comment by IanMatthewHuff** [comment]
@hediet @chrmarti Just to mention I had the same reaction here, especially when seeing this:
<img width="975" alt="image" src="https://user-images.githubusercontent.com/812783/192593322-8e3e6156-3191-4dcc-9a8e-32f2eea22e8e.png">
Per your comment above I think that I get why. But I did feel like it would help a bit for something in the visual of the diff to echo the "Left / Right" naming. For a visual merge like this left / right is always super clear and I'd prefer that over the naming from the caller personally.

Like if it was:
```
Left - Input 1                                               Right - Input 2
                                                 
Accept Left                                                  Accept Right
```
