### ISSUE TITLE
Confusing message about opening VS Code Desktop

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#161928]
Testing #161857

* on vscode.dev
* run continue on
* clone locally
* I see a browser-native dialog to open desktop
* I see a custom message that just reads "We tried opening Visual Studio Code - Insiders on your computer." which is confusing

Unsure if we have to show the message or not but its wording needs to be improved. I mean vscode.dev tried and _succeed_ in opening desktop so don't confusing me with this message. If we cannot prevent it I'd suggest to rephrase it and assume that it worked and give me a close option. Today, there this only covers the "didn't work cases" despite success

https://user-images.githubusercontent.com/1794099/192487773-954d4acb-6805-4e12-a801-2f909547b6e2.mov

**Comment by joyceerhl** [comment]
We cannot tell from the browser whether opening the protocol url succeeded, and the current wording for this dialog is based on a similar dialog from Office which also unconditionally appears in the browser: https://github.com/microsoft/vscode/issues/147870#issuecomment-1106659401

Maybe renaming 'Continue here' to 'Cancel' or 'Close' would help?

Some other ideas for wording--when you launch a Zoom meeting from a browser in the desktop client, it says 
![image](https://user-images.githubusercontent.com/30305945/192682266-e1d5fc34-33ba-4fba-a0ff-fe7bc5dfc1b0.png)

**Comment by jrieken** [comment]
> We cannot tell from the browser whether opening the protocol url succeeded,

I can accept that but the wording should be positive/happy. Like: "This session now continues in VS Code Desktop. You can close this window, all your changes have been carried along. Try again if VS Code Desktop didn't start yet."
