### ISSUE TITLE
Notebook diff decorations have white horizontal lines rendered inside them

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161918]
Testing #161861

Notice the white horizontal lines inside the diff decorations.
This looks like bad rendering 🐛 

In the editor diff this does not happen.

![Screenshot 2022-09-27 at 10 57 14](https://user-images.githubusercontent.com/1926584/192481724-a5973c42-705b-4f48-b2f3-c0015518bf4f.png)
![Screenshot 2022-09-27 at 10 57 18](https://user-images.githubusercontent.com/1926584/192481728-e1d9d82d-7cb8-4e50-80ab-f2823a3aba72.png)

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/170173. We should be using `Math.round` instead of `Math.floor`.
