### ISSUE TITLE
Special keys don't work as shortcuts in dvorak layout

### ISSUE THREAD

**Issue by Yathi** [Microsoft/vscode#16193]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Ruby|rebornix|0.10.3|
|sass-indented|robinbentley|1.2.1|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Set keyboard to Dvorak layout. In this layout the key marked "{" is now the "/" which is used for commenting.
2. Try to comment with the key marked "{" on the layout. It instead indents left as should be done on a US layout. 
3. Changing it does not work because in the editor pressing the pressing the key marked "{" produces "/" as it should according to the dvorak layout. 

To clarify: The dvorak keyboard layout works correctly in the editor. But not when using shortcuts. And the shortcuts cannot be re-mapped because its tied to the editor.

**Comment by rebornix** [comment]
Dup of #6020 . @Yathi thanks for reporting this issue, let's track it there.
