### ISSUE TITLE
Avoid reloading Html Preview window when changing tabs

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#16190]
- VSCode Version: 1.7.2
- OS Version: OS X

The contents displayed in the HTML preview tab window gets reloaded when tabbing off and back to the preview tab window.

Is there a way this can be avoided. 
I'm using the HTML preview window to display custom content in two separate extensions:   
- [Python](https://github.com/DonJayamanne/pythonVSCode)  
    + Displaying results from Jupyter kernel
- [Git History](https://github.com/DonJayamanne/gitHistoryVSCode/issues/51)  
    + Displaying Git log 

As you can imagine this doesn't produce the best UX (https://github.com/DonJayamanne/gitHistoryVSCode/issues/51).

**Comment by jrieken** [comment]
Yeah, that a problem with the web view. When you reparent it, the underlying process terminates

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/5257
