### ISSUE TITLE
scm view not loading in large folder with many repositories

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#161995]
Testing #161797

![Screen Shot 2022-09-27 at 8 35 36 AM](https://user-images.githubusercontent.com/29464607/192570915-c6a10af9-1cd3-453a-a2b7-020cfe5177c5.png)

**Comment by meganrogge** [comment]
still loading after reload
![Screen Shot 2022-09-27 at 8 39 09 AM](https://user-images.githubusercontent.com/29464607/192571713-ac2b95ad-4bb4-43bb-9351-fb4049cdf7be.png)

**Comment by lszomoru** [comment]
@meganrogge, did you explicitly open your home directory in VS Code?
Next milestone we are also planning on deprecating that notification which should help.

**Comment by meganrogge** [comment]
Yes
