### ISSUE TITLE
DrawIO example: Why is the UI different from the demo examples?

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#161975]
Testing #161834

The DrawIO example opens with all conflicts resolved. When I remove the accepted input on a resolved conflict by clicking the Remove Input 1 code lens, I don't get the yellow/orange borders on that conflict that I see when I open one of the demo examples.

**Comment by hediet** [comment]
This is because the result file in that folder is already resolved.
This is just an issue of the dev command, not the merge editor itself.

**Comment by chrmarti** [comment]
@hediet I would still expect to get back to the previous UI state when I first accept an input and then remove it again. (Seen in the demo samples.)

**Comment by hediet** [comment]
This is by design at the moment: Interacting with a conflict in any way marks it as handled.
Removing an input is not equal to undo.
