### ISSUE TITLE
Terminal inputing's issue

### ISSUE THREAD

**Issue by Ruy-Zhou** [Microsoft/vscode#16195]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-atom-one-dark|andischerer|0.0.1|
|stylus|buzinas|0.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.2|
|EditorConfig|EditorConfig|0.3.4|
|php-debug|felixfbecker|1.10.0|
|minify|HookyQR|0.3.0|
|theme-chromodynamics|lei|1.0.8|
|vue|liuji-jim|0.1.5|
|ejs-language-support|QassimFarid|0.0.1|
|vscode-icons|robertohuertasm|4.0.2|
|theme-tinaciousdesign|tinaciousdesign|0.1.1|

---

Steps to Reproduce:

1. open a git project
2. display the terminal
3. input `git log`, then showing some latest commits of the project, if you hit 'enter', it show some more to you. if you wanna go back, you'll hit `ctrl + c` or `q`
4. **the issue**: when I go back  to the input surface, if I input something, it display some git logs to me wiredly, and I can't go on my work.

**Comment by LEE222** [comment]
https://drive.google.com/file/d/0B53KHD78rCtcV1l4OVJqRmNmdlU/view?usp=drivesdk

**Comment by chrmarti** [comment]
@Ruy-Zhou Could you append a screenshot or screencast of the issue?

@LEE222 Please avoid posting unrelated comments.

**Comment by Ruy-Zhou** [comment]
When you stay the scene as screenshot 1，you’ll get the scene as screenshot 2 after hitting “enter”, This issue appears frequently when you input “git log” then hit ‘enter’ more than twice.

![screenshot 1](https://cloud.githubusercontent.com/assets/5326363/20781998/b484d3ae-b7c2-11e6-81f5-fd57ddb1486a.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/5326363/20781999/b55dce84-b7c2-11e6-8531-94fb12396506.png)

**Comment by Tyriar** [comment]
@Ruy-Zhou what do you have in your settings.json file?
