### ISSUE TITLE
git create PR does not do anything

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161911]
Testing #161846

Reading the testplan item I got the impression that `git create PR` is a built in command to be recognised by quick fix.
It does not get recognised for me.

Did I misunderstand this?

![Screenshot 2022-09-27 at 10 33 17](https://user-images.githubusercontent.com/1926584/192475866-fbcaf1ca-0c4e-44af-82b0-7f88b3939885.png)

**Comment by meganrogge** [comment]
Sorry for the unclear directions. 

You should see the git create pr action when you run `git push` from a branch that has an upstream remote for the first time.

So, for example:

- git checkout -b merogge/test
- git push
- 💡 quick fix should appear to push to upstream remote
- take that suggestion
- 💡 quick fix should appear to create pr

**Comment by isidorn** [comment]
Thanks for clarifying. I just followed the steps you suggested and there is no quick fix to create a PR

![Screenshot 2022-09-27 at 15 46 07](https://user-images.githubusercontent.com/1926584/192543920-a9096d87-9bc4-4f2e-8911-24923ad972bd.png)

**Comment by meganrogge** [comment]
yeah can repro, looks like a regression

**Comment by meganrogge** [comment]
it's hitting this

![Image](https://user-images.githubusercontent.com/29464607/192620599-07bbb4dd-c802-4053-b3e9-6d20a8478de6.png)

**Comment by isidorn** [comment]
This flow is pretty sweet ✨
