### ISSUE TITLE
Cannot open conflicting file after `git stash pop`

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#161984]
* make edits to a file
* stash using `git stash`
* make edits to the same file such that a conflict is created
* commit these edits
* unstash using `git stash pop`
* the file cannot be opened from the SCM view:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/5047891/192557248-6a0dd46f-4e5e-4550-b0fb-6bc6d3bdf396.png">

* the console shows:
```
[2022-09-27T14:38:49.406Z] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z HEAD [15ms]
[2022-09-27T14:39:03.348Z] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z MERGE_HEAD [15ms]
[2022-09-27T14:39:03.348Z] fatal: ambiguous argument 'MERGE_HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[2022-09-27T14:39:03.349Z] > git show -s --format=%H%n%aN%n%aE%n%at%n%ct%n%P%n%D%n%B -z HEAD [16ms]
```
<img width="1613" alt="image" src="https://user-images.githubusercontent.com/5047891/192557150-7d28dc2d-d7f5-4bc1-b0d9-7e443db22e8c.png">

**Comment by jrieken** [comment]
Hm... The printed error shouldn't be causing failure. This happens when failing to read branch and commit info for incoming/current, the error-handling [does the print that we are seeing](https://github.com/microsoft/vscode/blob/313203ed4ebb3be6e3aa0b5f0ff7336cdb0cedd3/extensions/git/src/commands.ts#L485) and when this happens you see no details and no description.

**Comment by jrieken** [comment]
I see the same error being printed (handled) but I do see a merge editor being opened... 

https://user-images.githubusercontent.com/1794099/192569228-70de2f6f-7f7a-4d37-9b51-32220e855914.mov

**Comment by jrieken** [comment]
@alexdima does the "Open in Merge Editor" blue button work?

**Comment by alexdima** [comment]
I can't reproduce anymore 🤷
