### ISSUE TITLE
Badge value is not type validated

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161919]
Testing #161780

I can put in an actual string and it is rendered:

```ts
view.badge =  {tooltip: 'Hello WOrld 000ß', value: "kjkj5"};
```

![image](https://user-images.githubusercontent.com/900690/192482135-f7bba2e1-1b12-457d-852e-e04af18b8532.png)

**Comment by alexr00** [comment]
I would implement the `+` within VS Code instead of allowing each extension to have it's own threshold at which the `+` shows. https://github.com/microsoft/vscode/issues/162002

**Comment by gjsjohnmurray** [comment]
Are you disallowing negative numbers? Non-integers?

**Comment by gjsjohnmurray** [comment]
> Are you disallowing negative numbers?

Already covered by #161990

**Comment by alexr00** [comment]
> negative numbers

No, thanks for catching: https://github.com/microsoft/vscode/pull/162359
