### ISSUE TITLE
Reopen on desktop -> when remote repositories is not installed should still work

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161931]
Testing #161872

https://insiders.vscode.dev/
1. Uninstall Remote Repositories from VS Code.
2. Have some uncommited changes in vscode.dev
3. Continue in VS Code desktop
4. We nicely detect that Remote Repositories is not installed. Click on install
5. After extension is installed nothing happens, I have to go back to step 3 🐛 

Ideally after the extension is installed we would just continue with the flow.
There are probably technical limitations that are preventing us from doing this. But creating this issue so we discuss if it is feasible to solve.

**Comment by joyceerhl** [comment]
@meganrogge just hit this as well with GitHub Repositories installed but not enabled, we should at least show a notification here

**Comment by joyceerhl** [comment]
Duplicate https://github.com/microsoft/vscode-remote-repositories-github/issues/265
