### ISSUE TITLE
Consider using Quick Fix sound when terminal quick fix is available

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161912]
Testing #161846

I believe we already have a Quick Fix available sound. 
We should play this sound when the terminal has quick fix. And also when the editor has the quick fix (we planned on doing this but never implemented it I believe).

**Comment by meganrogge** [comment]
with `editor.accessibilitySupport` enabled, trigger the terminal quick fix via checking out a new branch, and `git push`
