### ISSUE TITLE
Toolbar items grow larger on right click

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#161999]
Testing #161802

Right click on an item in the editor toolbar. When you do this, the items grow slightly larger. This may be by-design but feels odd to me as I don't think other areas of VS Code have similar animation feedback

**Comment by jrieken** [comment]
> This may be by-design but feels odd to me as I don't think other areas of VS Code have similar animation feedback

Yeah, feature. Tho, I do agree this is a little weird. I wanted to add some kind of animation to indicate that we are now in "configure mode". Esp right-clicking on the `...` can be confusing - both show a context menu but they are fundamentally different. 


Looping in @daviddossett for some idea. 👇 that is what's current happened.

https://user-images.githubusercontent.com/1794099/192573626-51f112a1-bcff-4b0a-a5e8-810595a8df67.mov

---

Prior art from Safari which I used for inspiration - I failed to recreate a similar nice side-wiggle animation

https://user-images.githubusercontent.com/1794099/192574052-6946d25c-8363-4c2d-9b17-2bd26295edc6.mov

**Comment by daviddossett** [comment]
I do like the idea of a looping left/right animation that keeps going as long as the context menu is open. Should be relatively simple with something like  `animation: icon-wiggle 0.2s infinite;`

I'll take a look and try some options.

**Comment by jrieken** [comment]
> I'll take a look and try some options.

Thanks. Code pointer is here: https://github.com/microsoft/vscode/blob/42a198b98b279460e1c11310759c4fb34d6be2ab/src/vs/platform/actions/browser/menuEntryActionViewItem.css#L29. I can also with this

**Comment by daviddossett** [comment]
Tried a few different approaches. In both cases the animation is intended to repeat as long as the hide menu is open. As is, the animation continues after closing. So we'll need to remove the class somehow.

## Rotate and scale

This attempts to draw a connection to the language status animation which would be a nice pattern to reuse here and elsewhere:

![CleanShot 2022-09-27 at 10 42 08](https://user-images.githubusercontent.com/25163139/192598713-cdd0b4e1-0e65-420f-9407-66290369f9eb.gif)

```
@keyframes wiggle {
	0% {
		transform: rotate(0) scale(1);
	}

	15%,
	45% {
		transform: rotate(.01turn) scale(1.05);
	}

	30%,
	60% {
		transform: rotate(-.01turn) scale(1.1);
	}

	100% {
		transform: rotate(0) scale(1);
	}
}

.monaco-toolbar.config .monaco-action-bar .action-item {
	animation-duration: 1.2s;
	animation-iteration-count: infinite;
	animation-name: wiggle;
}
```



## Side-to-side wiggle

![CleanShot 2022-09-27 at 10 44 20](https://user-images.githubusercontent.com/25163139/192599011-5510a4db-f9c2-4df7-90bb-3983e317d02b.gif)

```
@keyframes shift {
	0% {
		transform: translateX(0px);
	}

	15%,
	45% {
		transform: translateX(0.5px);
	}

	30%,
	60% {
		transform: translateX(-0.5px);
	}

	100% {
		transform: translateX(0px);
	}
}

.monaco-toolbar.config .monaco-action-bar .action-item {
	animation-duration: 1.2s;
	animation-iteration-count: infinite;
	animation-name: shift;
}
```

**Comment by jrieken** [comment]
> As is, the animation continues after closing. So we'll need to remove the class somehow.

The removing is possible. 

I actually started this with reusing the wiggle but felt it being too nervous... I will try the side-ways move and see how folks feel about it

**Comment by jrieken** [comment]
I went with a more linear sideways shift but I use different delays for odd children. This makes it appear that they move towards each other and away from each other

👇 

https://user-images.githubusercontent.com/1794099/192802943-9966df6f-11ec-4a2b-ac33-88e8e8664624.mov


```css
@keyframes shift {
	0% {
		transform: translateX(0px);
	}

	33%{
		transform: translateX(0.5px);
	}

	66% {
		transform: translateX(-0.5px);
	}
}

.monaco-toolbar.config .monaco-action-bar .action-item {
	animation-duration: 1.2s;
	animation-iteration-count: infinite;
	animation-name: shift;
}

.monaco-toolbar.config .monaco-action-bar .action-item:nth-child(odd) {
	animation-delay: 0.6s;
}
```
