### ISSUE TITLE
Turn on Edit session badge updates when there are no working changes

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#161979]
Testing #161872

1) Ensure edit sessions are off on the desktop
2) Open any remote repository and do not make any changes, ex: https://insiders.vscode.dev/github/microsoft/vscode  
3) Continue working on desktop
4) Open the cloned repository and see that badge appears to turn on edit session

**Comment by roblourens** [comment]
I still see the badge

<img width="307" alt="image" src="https://user-images.githubusercontent.com/323878/193352602-13220236-2f2b-4cd5-9749-99f8cb648a0a.png">

**Comment by joyceerhl** [comment]
Sorry, I missed verification steps. To verify this issue specifically (which I just checked works as expected in latest insiders):

1. (clearing bad insiders-only local state) if you already have the badge on desktop, turn edit sessions on and then off
2. Open a remote repository and have no working changes
3. Continue working on desktop
4. Open the cloned repository and there should be no accounts badge

**Comment by roblourens** [comment]
Am I supposed to have edit sessions enabled or disabled on the web? WIth them enabled, but no changes, I ran the steps and have a badge in my new cloned repo in insiders
