### ISSUE TITLE
Give user access to a stylesheet for the editor.

### ISSUE THREAD

**Issue by ceckenrode** [Microsoft/vscode#16192]
- VSCode Version: 1.7.2
- OS Version: OSX 10.11.6

It would be great if there was a stylesheet the user had access to that took precedence over the main.css file the editor uses. That way we can add custom styles without modifying the main.css file.

**Comment by rozzzly** [comment]
I try to make the same argument here: https://github.com/Microsoft/vscode/issues/3112

**Comment by Tyriar** [comment]
Duplicate https://github.com/Microsoft/vscode/issues/459
