### ISSUE TITLE
Not seeing badge for 3 available updates

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161903]
Testing #161795

Not sure how I got into this but I do not see a badge of 3 indicating the updates:

![image](https://user-images.githubusercontent.com/900690/192472048-a8375585-fa2b-4cfb-b2c5-495676e676ee.png)

**Comment by benibenj** [comment]
This is fine. I'm guessing you manually installed an outdated version. Then we set this extension to ignore auto updates by default, as you explicitly want an old version, and don't display the badge for it. If you press the dropdown and uncheck ignore updates the badge will update, and the extension will jump to the top on reload.
