### ISSUE TITLE
VIM emulation - Ctrl-o in insert mode does not work as expected

### ISSUE THREAD

**Issue by lzybkr** [Microsoft/vscode#16191]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.4.1|
|PowerShell|ms-vscode|0.7.2|
|vim|vscodevim|0.1.10|

---

Steps to Reproduce:

1. Edit a document, make sure you are in insert mode
2. Hit Ctrl-o [see docs](http://vim.wikia.com/wiki/Use_Ctrl-O_instead_of_Esc_in_insert_mode_mappings)
3. Open file dialog opens
expected
3. I can enter a single normal mode command then continue in insert mode

**Comment by rebornix** [comment]
This issue was moved to VSCodeVim/Vim#1097
