### ISSUE TITLE
Duplicating Menu Actions when switching profiles

### ISSUE THREAD

**Issue by benibenj** [microsoft/vscode#161910]
I'm not entirely sure how to reproduce this, but this is what I did:
1. Played around with hiding title actions in the "Remote Explorer" Panel view. Hid both Refresh and Collapse action and reset the menu again.
2. When switching to a profile which does not have the extension and then switching back, the Collapse action duplicated

![image](https://user-images.githubusercontent.com/44439583/192466955-0134bbcc-d483-4af1-8994-8c0bca0b33b0.png)

It also propagated into other view panes such as the GitHub PR extension

![image](https://user-images.githubusercontent.com/44439583/192466881-0b699c88-3440-4171-80a2-896ab5e5efe7.png)

I don't think it's related to hiding. Possibly some cleanup tasks not removing all menu groups it should...?

**Comment by sandy081** [comment]
Yes, it is not related to showing/hiding actions. It can be reproduced by not toggling visibility.

- Open Pull Requests View
- Switch to a profile that does not has Pull Request view
- Switch back to the previous profile
🐛 Collapse All action is duplicated.

Only Collapse All action is getting duplicated. Seems like a tree view bug.
