### ISSUE TITLE
Continue on from web to desktop does not work for me

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161932]
Testing #161872

1. https://insiders.vscode.dev/github/microsoft/vscode
2. Have some changes in the `readme.md`
3. Continue working on desktop. Choose VS Code insiders
4. Popup appears, I click Open in VS Code (image 1)
5. Popup appears in VS Code, I say ok (image 2)
6. Nothing happens. No errors in dev tools 🐛 

![Screenshot 2022-09-27 at 11 42 56](https://user-images.githubusercontent.com/1926584/192492950-74e1772a-bf05-40b5-a2bf-e996df5f2ae2.png)
![Screenshot 2022-09-27 at 11 42 59](https://user-images.githubusercontent.com/1926584/192492953-28bb9894-a0b8-47c3-85ef-5cf3da50ae07.png)

**Comment by isidorn** [comment]
This does not work both if my "Edit Sessions" are `on` or `off`.

**Comment by joyceerhl** [comment]
Sorry, the test plan missed a step to have the GitHub Repositories extension installed on desktop--do you still see issues after installing that?

**Comment by isidorn** [comment]
@joyceerhl yes, I still see the issue after installing GitHub Repositories extension on the desktop.

**Comment by isidorn** [comment]
Yes, the issue was that I did not have the pre-release version of the extension. Sorry about that. Closing this and will test the testplan item later today / tomorrow.
