### ISSUE TITLE
Interactive window: interactive.history.focus should use when clause

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161924]
Testing #161850

Currently `interactive.history.focus` only works if the focus is in the interactive window input. I think this makes sense, but you should use a `when` clause to express this. That way I could use the same keyboard shortcut for something else and history.focus at the same time. Right now history.focus always eats up a keybinding and decides on it's own if it should be a no-op or not.

**Comment by amunger** [comment]
It doesn't seem possible to set a when clause without having a default key binding - the type system allows it, but the when clause doesn't actually show up in the keybindings.

Perhaps this can be done along with https://github.com/microsoft/vscode/issues/161925 if we can figure out the consistent keybindings to use by default.

**Comment by luabud** [comment]
FWIW `interactive.input.focus` is also displayed when the interactive window isn't active, so right now if e.g. the Jupyter extension isn't installed and you run the "Interactive Window: Focus input editor in the interactive window" command, nothing happens

**Comment by joyceerhl** [comment]
@amunger you should be able to conditionally suppress the commands from the palette by using the full `menu` syntax to add the command to the palette instead of the `f1: true` shorthand, like so:

![image](https://user-images.githubusercontent.com/30305945/214430492-8f95ec4c-e61c-45a3-9723-63c5ac9d5b90.png)
