### ISSUE TITLE
"Avialable Updates" could have a "Update all" button

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#161908]
Testing #161795

Maybe a button to the right of the view header:

![image](https://user-images.githubusercontent.com/900690/192473660-dbfb679e-3550-499f-bd61-1b57e073b751.png)

**Comment by sandy081** [comment]
@benibenj Lets have `Update All` action in the `Available Updates` view header like below

<img width="341" alt="image" src="https://user-images.githubusercontent.com/10746682/192578532-b09b41f9-2a80-44e4-bd1c-efdf77ba8aa1.png">
