### ISSUE TITLE
Toggle Whitespace Visibility (editor.renderWhitespace command)

### ISSUE THREAD

**Issue by glen-84** [Microsoft/vscode#1619]
I like to be able to quickly toggle whitespace visibility (editing a JSON file is not ideal), but it doesn't seem like there is a command associated with the editor.renderWhitespace setting, so I'm not able to create a keyboard shortcut.

See also: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/7894491-toggle-whitespace-visibility

**Comment by bpasero** [comment]
This is now available.
