### ISSUE TITLE
Js debugger stopped working after hibernation

### ISSUE THREAD

**Issue by Profesor08** [microsoft/vscode#161909]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Windows

Steps to Reproduce:

1. Run VS Code
2. Open some project
3. Attach debugger to existing tab in chrome
4. Shutdown you system into hibernation mode for some time
5. Return from hibernation mode

After this steps, debugger will not work. You will not be able to stop it, or restart. Only solution is to restart vscode.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/147050
