### ISSUE TITLE
Lazy rendering of outputs causes diff decorations to shift

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#161901]
Testing #161861

I don't know what, if any, good solution there is to this, since height computation requires rendering which basically has to be lazy. But it's a weird experience.

https://user-images.githubusercontent.com/2230985/192466381-66078c6f-4854-4964-94c7-f2abce8e1bd6.mp4

**Comment by DonJayamanne** [comment]
Given this issue has been open for 2 years, and we do not yet have a solution for this, I think its just safe to close this for now.
We would love to address this, however we do not see any solution for this at this stage, and there's no point in leaving this open for over 2 years when there haven't been any other similar issues nor any progress in this space.
