### ISSUE TITLE
Cannot set profile short name to codicon

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#161985]
Testing #161792

1. Change profile short name
2. Try to enter a codicon in the specialized syntax
3. 🐛 Says short name can only be 2 characters

**Comment by sandy081** [comment]
It works for me when I enter `$(refresh)`. Can you please check if you are following this syntax?

**Comment by lramos15** [comment]
Oh I see, I was following the TPI and doing `$(${github})` but that's not right. The parentheses should be removed from Change Short Name... when it's a codicon though
