### ISSUE TITLE
Git SCM View: Show Loading Progress

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#161965]
When opening a git repository, the SCM initially shows this:

<img alt="image" src="https://user-images.githubusercontent.com/2931520/192530580-41593e32-2275-43aa-995c-7a8a45399341.png">

Only later it finds the git repository.

I would suggest to show some loading text initially, instead of saying that there is no git repository.

**Comment by lszomoru** [comment]
Progress is not being shown during initial repository discovery.

**Comment by lszomoru** [comment]
Verification steps:
* Open a folder/workspace that contains one or more git repositories
* Switch to the "Source Control" view
  * Confirm that while repositories are being discovered the view shows a progress indicator
  * Confirm that while repositories are being discovered, a message is being shown indicating progress

**Comment by alexr00** [comment]
A small UX change, but it feels like a huge improvement 👏
