### ISSUE TITLE
Notebook diff: current location in scrollbar not always a rectangle

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#161920]
Testing #161861

Scroll a bit in the notebook diff. Notice that the current location rectangle is not always right. Notice that the first and last line are not straight.

![Screenshot 2022-09-27 at 10 59 01](https://user-images.githubusercontent.com/1926584/192482157-6bc64822-a4c8-44e7-a5c3-7f4ae5b33495.png)

**Comment by joyceerhl** [comment]
I can still get a tiny misalignment in the text diff scrollbars, not sure if it's the same scenario: 
<img width="115" alt="image" src="https://user-images.githubusercontent.com/30305945/214964817-2d87bd98-a39d-4e7c-83a5-1f1453b6999a.png">

**Comment by andreamah** [comment]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/31675041/227035344-2c8568bf-bd92-4d77-8b30-09772d9fd634.png">
How do I get that custom scrollbar in the notebook diff editor? I see a regular scrollbar
