### ISSUE TITLE
No way to set log level per extension 

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#161944]
Testing #161786

I would like to be able to migrate my extension's existing log level setting when converting over to the new extension logging API. I would also like to be configure the log level per extension, because I only care about having trace logging for one extension at a time.

**Comment by lszomoru** [comment]
+1 on Alex's request above. It would be great if we could toggle this per extension.

**Comment by sandy081** [comment]
You can now set log level per extension

![image](https://user-images.githubusercontent.com/10746682/196460609-7861d58e-6073-4c21-a397-9aa2cf97e0a9.png)
