### ISSUE TITLE
The Active Conflict Is Barely Noticable

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#161998]
I think the border should be thicker and the color should have more contrast.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/2931520/192572483-bebd5327-cc67-4d05-a116-0fb9e543d17d.png">

**Comment by daviddossett** [comment]
I think the thicker border is a little too heavy but agree that the light themes in particular suffer from a contrast issue. Do you think it's as much of a problem on the dark themes?

**Comment by hediet** [comment]
> Do you think it's as much of a problem on the dark themes?

It works much better on the dark themes (maybe also because my code-oss uses dark theme)

**Comment by daviddossett** [comment]
Ok, I'll propose some updates this week 👍

**Comment by hediet** [comment]
Before Light:

![image](https://user-images.githubusercontent.com/2931520/197523446-93ff7766-2ae3-4f4e-ae67-3b7068c74dab.png)


Before Dark:

![image](https://user-images.githubusercontent.com/2931520/197523409-fc1bb46b-dac8-46a0-b01a-0febcc9b05bf.png)


After Light:

![image](https://user-images.githubusercontent.com/2931520/197522592-24afaa90-ffdd-41ce-b54f-0e708cfe5e99.png)

After Dark:

![image](https://user-images.githubusercontent.com/2931520/197522673-910575c9-4f3a-466b-90cf-68fa279e4d56.png)
