### ISSUE TITLE
Settings: Setting element shows focus border on Light/Light+ theme

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#161960]
![image](https://user-images.githubusercontent.com/22350/192528133-7a43465a-821c-4833-b37f-91f45d541c77.png)

This doesn't render on other themes.

**Comment by meganrogge** [comment]
I see a focus border regardless of the theme now, but LGTM

<img width="772" alt="Screen Shot 2022-10-26 at 4 24 07 PM" src="https://user-images.githubusercontent.com/29464607/198129562-e63981db-4b0a-4ba0-af95-60a8d180db10.png">
