### ISSUE TITLE
Use modal after cloning a repo

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#161926]
Testing #161857

* clone a repo from within VS Code
* when done a notification is shown
* IMO a modal is the better choice of UI because this something I am awaiting and wanting to take action on

<img width="1527" alt="Screenshot 2022-09-27 at 11 15 02" src="https://user-images.githubusercontent.com/1794099/192486380-283fecbc-28e3-4ddb-ba16-ac346d1d5f1c.png">

**Comment by lszomoru** [comment]
it makes sense to me. @daviddossett, please let me know if you have any concerns. Thanks!

**Comment by bpasero** [comment]
💯 , as having notifications snoozed always, I was missing this notification but I think it should be modal as it is part of a flow that I triggered.

**Comment by daviddossett** [comment]
> it makes sense to me. @daviddossett, please let me know if you have any concerns. Thanks!

No concerns with using a modal 👍
