### ISSUE TITLE
Blurry , distorted vision

### ISSUE THREAD

**Issue by harsh-hustler** [microsoft/vscode#161994]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Bug</b>

the app is causing Unwanted blurry vision which is quite annoying, none of my app is showing this kind of vision. First i thought that it's might be my screen issue but no the issue is in my vs code only. Kindly fix it early or i will have to use some other IDE

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (4.32GB free)|
|Process Argv|--crash-reporter-id ffc0c58c-2697-4601-9474-24859134eacd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
code-tester|Aka|0.0.6
doxdocgen|csc|1.4.0
competitive-programming-helper|Div|5.9.2
code-runner|for|0.11.8
better-cpp-syntax|jef|1.15.19
vscode-leetcode|Lee|0.18.1
python|ms-|2022.14.0
vscode-pylance|ms-|2022.9.40
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.80.0
remote-wsl|ms-|0.66.3
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.0
cpptools-extension-pack|ms-|1.3.0
vetur|oct|0.36.0
material-icon-theme|PKi|4.20.0
java|red|1.10.0
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
cmake|twx|0.0.17
vscodeintellicode|Vis|1.2.27
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.2
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
JavaScriptSnippets|xab|1.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
fc301958:30573243

```

</details>

![Screenshot (70)](https://user-images.githubusercontent.com/78041915/192569988-5f615945-fd01-4cbb-9e33-53b672b363fc.png)
![Screenshot (71)](https://user-images.githubusercontent.com/78041915/192569995-725978e9-0f30-4e54-9ae8-9e0e962ea6f5.png)
![Screenshot (72)](https://user-images.githubusercontent.com/78041915/192570002-0349e642-7ffc-4d6f-a420-1784c883e8a5.png)
![Screenshot (73)](https://user-images.githubusercontent.com/78041915/192570007-1838a748-8d5f-48e5-b2cb-c47a25e004f4.png)
![Screenshot (74)](https://user-images.githubusercontent.com/78041915/192570495-dd2d2afa-0f17-4d8b-8d2a-5df6d2d34882.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226, please disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
