### ISSUE TITLE
Badge is shown even when there are no extensions requiring reload

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#161983]
Badge shows there is an extension requiring reload

<img width="440" alt="image" src="https://user-images.githubusercontent.com/10746682/192554159-258501db-99d7-4639-9f8a-eacc1e57bfd7.png">

**Comment by benibenj** [comment]
Did you refresh the view and still not see it? Then it's probably a built-in extension.

**Comment by sandy081** [comment]
Yeah I did refresh and also checked for built in extensions and I do not see any. May be shall we have a filter that shows extensions requiring action. This will help in debugging these issues?

**Comment by abhijitchikane** [comment]
I faced the same issue. But it was built in extension that is not being updated as I have turned off the setting to autoupdate the extension but later I noticed even if I changed that setting that badge was still there.

**Comment by benibenj** [comment]
Not sure we should introduce a filter for this @sandy081, but we could change the tooltip when hovering over the extension to say the name of the extension if there is only one action required.
Instead of "1 extension requires reload", "GitHub Pull Requests requires reload"
