### ISSUE TITLE
Typing in the editor is very laggy on Linux

### ISSUE THREAD

**Issue by eugen-v** [Microsoft/vscode#162]
Since the 0.10.1 update, typing anything in the editor is very laggy: characters appear with about 0.5 seconds delay and almost never in the same order I actually typed them on the keyboard.

Possibly related: scrolling to the top of a file in the editor triggers a slower top-down refresh of the contents that apper in the editor. I actually see how the code is refreshed like in a bitmap, line by line, pixel-wise.

I'm using Ubuntu Linux 15.10. This problem didn't occur with previous Visual Studio Code updates.

Later edit: I've tested it again on the same computer, but on a 15 inch screen and it works ok, without any lag when typing. Only when Visual Studio Code is on a 24 inch monitor the typing is lagging.

**Comment by meritozh** [comment]
Had test. It won't appear in OS X. How about reinstall VSCode?

**Comment by eugen-v** [comment]
I've reinstalled it. The issue is still there.

**Comment by klingtnet** [comment]
I can't confirm this issue, typing in visual-studio-code works without any noticeable delay on Arch Linux machine:
```
Version 0.10.1
Commit df352367df2efcfa9d602d471e4e2f42140a0f05
Date 2015-11-17T15:21:23.766Z
Shell 0.34.1
Renderer 45.0.2454.85
Node 4.1.1
```

**Comment by maritz** [comment]
I'm running it in a LinuxMintDebianEdition (in a vm) and do not experience this issue, so it is not a generic Linux build issue.

**Comment by eugen-v** [comment]
I've tested it again on the same computer, but on a 15 inch screen and it works ok, without any lag when typing. Only when Visual Studio Code is on a 24 inch monitor the typing is lagging.

**Comment by klingtnet** [comment]
I'm assuming that the 15" screen is the display of your laptop and the 24" model should be an external monitor, so which connection do you use for the external one (VGA,HMDI, DVI, DisplayPort)? Can you cross check if this problem persists with any other browser-based editor, g.e. [Atom](https://github.com/atom/atom/releases) or [Brackets](https://github.com/adobe/brackets/releases).

**Comment by eugen-v** [comment]
The 24" monitor is connected via HDMI.
However, I can confirm that the same issue is present in Atom v1.2.2: Laggy on 24" monitor, smooth on the 15" one.

**Comment by klingtnet** [comment]
Can you give a little more information on your hardware? Maybe your processor is to slow, because *Atom* as well as *VS Code* use quite a lot resources.

**Comment by eugen-v** [comment]
My laptop's specifications are: Intel Core i5 (model 460M, up to 2.53 GHz), 4 GB RAM, SSD, Intel i5's GPU (even though the laptop has a GeForce GT 325M discrete graphics card, it's not used under Ubuntu Linux). 
The issue that I reported never occurred to me before, and I've been using Visual Studio Code since the very first public release.

**Comment by alexandrudima** [comment]
@eugen-v 

What if you use the 24" monitor and resize the VSCode window to be smaller? What if you open 3 editors side-by-side in VSCode in the 24" monitor, and type in one of them... (i.e. is the problem one of the viewport size and the size of the GPU layers?)

How does it work when opening Chrome (you can also help by mentioning the Chrome version you try with) and typing in the editor at http://www.typescriptlang.org/Playground . Do you see such strange differences between the 15" / 24" or the window size?

**Comment by eugen-v** [comment]
The editor at http://www.typescriptlang.org/Playground works good in Chrome (Version 46.0.2490.86 (64-bit)) on the 25" monitor.

I get good performance in VSCode in a smaller window on the 24" monitor, even with 3 editors side-by-side.
Interestingly enough, on the 24" monitor, I get bad performance in a maximized window, but good performance in full-screen (even with 3 editors side-by-side).

**Comment by klingtnet** [comment]
You mean 15" right?
It's a shot in the dark, but it sounds like bug/performance problem in Unity. If your window is maximized, then Unity doesn't have to render window borders etc.

**Comment by eugen-v** [comment]
Nope, I mean 24" :)

I think it's an issue with (large) maximized windows. If I resize a non-maximezed window to be almost as large as a maximized one, the editor's performance is still good.

**Comment by alexandrudima** [comment]
@eugen-v 

Given this only happens on Ubuntu 15.10 when the window is maximized, but it doesn't happen when the window is almost maximized, and also not when in full-screen mode, I'm thinking it is a bug in Chromium...I have found a relevant issue on atom/atom#9724 which again hints this is a problem with Electron/Chromium.

On the Chromium side, I could find [this comment](https://code.google.com/p/chromium/issues/detail?id=514510#c37) which hints Chromium has issues with Intel opensource MESA drivers.

**Comment by leifcr** [comment]
@alexandrudima I've tested VScode on the same computer.

System configuration: (Dell xps 15-9530)
Ubuntu 15.10
Resolution 3200x1200
Intel HD Graphics 5000
Intel Core i7-4702hq
16 GB ram
SSD drive

And the behaviour is laggy when maximized, and fine in fullscreen and non-maximized. Same issue as in atom/atom#9724, so it's probably related to Chromium/electron.

**Comment by leifcr** [comment]
Filed against ubuntu here: https://bugs.launchpad.net/ubuntu/+source/xserver-xorg-video-intel/+bug/1525207

**Comment by egamma** [comment]
@leifcr thank you! Keeping the issue open to track the upstream problem.

**Comment by alexandrudima** [comment]
@egamma Looks like it is a confirmed driver issue of Ubuntu, not of Chromium/Electron

**Comment by der-Daniel** [comment]
@leifcr thanks you so much!
