### ISSUE TITLE
I feel like the codicon looks too close to the top

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#162046]
Testing #161792

![image](https://user-images.githubusercontent.com/2644648/192612763-4c5dbd8f-2862-4a9d-a2d3-48444dfe7466.png)

I would have expected it to be centered.... though this could just be this codicon.

**Comment by sandy081** [comment]
Is this happening with all codicons or just this one?

**Comment by sandy081** [comment]
I can see it for codicons. Fixing it
