### ISSUE TITLE
`isMobile` context key doesn't seem to be working on IPhone chrome browser

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#162085]
Testing #161855

Steps to reproduce:

- Try installing `karrtikr-web-sample` on web.

It registers two commands: `Hello world` and `My world` where `My world` is only available on mobile. See [`package.json`](https://gist.github.com/karrtikr/0c1a201fcdddcf4146ac523b3de26227).

- Open command palette to activate the extension by running `Hello world` command.
- Look for `My World` command which isn't visible.

**Comment by joyceerhl** [comment]
This seems to work for me in iPhone using Safari. 
![image](https://user-images.githubusercontent.com/30305945/192655898-a9ca26ae-a880-420e-9548-cd35f9ea8134.png)

Are you on insiders.vscode.dev (or github.dev with the Insiders quality for VS Code)? Would you mind sharing your user agent (visit a site like https://www.whatismybrowser.com/detect/what-is-my-user-agent/ from Chrome on your iPhone)

**Comment by karrtikr** [comment]
Ah I was using `vscode.dev` instead, my bad. This works on `insiders.vscode.dev`.
