### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by thoorpukarnakar** [Microsoft/vscode#16207]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by isidorn** [comment]
Please provide steps on how to reproduce this issue.
Screenshots and more details are also helpful

**Comment by ramya-rao-a** [comment]
Closing this issue as we havent heard back from the OP in a while
