### ISSUE TITLE
Invalidated Event(['variables']) does not refresh the variables view

### ISSUE THREAD

**Issue by sbobko** [microsoft/vscode#162020]
My extension makes changes to variables and I can see from the debugger log in the Debug console that they are changing. However, refreshing Variables does not occur until the user interacts with the panel, for example, add watch variable or something like that. To force refresh, I tried to use InvalidatedEvent like this:
```
import * as vscode from "vscode";
import { DebugSession, InvalidatedEvent } from 'vscode-debugadapter';


export class SimdProvider  extends DebugSession{
    blablabla
    constructor(
        blablabla
    ) {
    super();
    blablabla
    }
    public async refresh(): Promise<void> {
        blablalba
        this.sendEvent(new InvalidatedEvent(['variables']));
}
```

Sending the event successfully occurs, however, has no effect.

@connor4312, @isidorn Could you help me figure out what I'm doing wrong or is it a problem with InvalidatedEvent?

**Comment by AKurkina** [comment]
Having troubles with same issue

**Comment by detihoronyatkonya** [comment]
I believe that this event should work on the adapter side, but for some reason this does not happen despite the fact that the data in the debugger does not match the data displayed in vscode. 

I would really like to be able to update the data displayed in vscode.

**Comment by roblourens** [comment]
I hacked something into js-debug, and it seems to work fine for me. vscode will only refresh if that debug session is the selected debug session. Are you getting the variables request at all?

**Comment by sbobko** [comment]
> Are you getting the variables request at all?

hmm, I haven't tried it, but I can do it if you describe what I need to do.

**Comment by sbobko** [comment]
I got the impression that the event simply does not reach the listener, since the debugging session is not started from the extension. I think there must be some way to refer specifically to the current active debugging session.
@roblourens Could you advise me any other way to trigger an event from the extension side so that I can make sure of it?

**Comment by roblourens** [comment]
> > Are you getting the variables request at all?

> hmm, I haven't tried it, but I can do it if you describe what I need to do.

I just mean, does your debug adapter get a variables request from vscode after sending this event or not?

**Comment by sbobko** [comment]
@roblourens I'll try to show by example:
I change the state of variables with something like this:
`await session.customRequest("evaluate", { expression: "-exec thread "+ newSimdLane, context: "repl"`
and then I send the InvalidatedEvent.
Here is the full code of the example:
```
        const session = vscode.debug.activeDebugSession;

        if (session) {
            await session.customRequest("threads");
            let resStackTrace = await session.customRequest('stackTrace', { threadId: 4 })

            let frameId = resStackTrace.stackFrames[0].id;
            let resID0 = await session.customRequest('evaluate', { expression: 'id0', frameId: frameId });
            console.log(resID0.result);
            const evalresult = await session.customRequest("evaluate", { expression: "-exec thread 2.1:1", context: "repl" });
            
            if (evalresult.result === 'void') {
                return;
            }

            this.sendEvent(new InvalidatedEvent(['variables']));

            resStackTrace = await session.customRequest('stackTrace', { threadId: 4 })
            frameId = resStackTrace.stackFrames[0].id;
            resID0 = await session.customRequest('evaluate', { expression: 'id0', frameId: frameId });

            console.log(resID0.result);
        }
```

According to the logs, I see that the state has changed (it was 8 became 9), however, the event did not help to update the value in the interface:

![image](https://user-images.githubusercontent.com/46919374/193112798-5c29e065-4a97-48a9-9abb-360ad445d2f2.png)

But, for example, if I add Watch, the view will be updated:
![ViewInvalidated](https://user-images.githubusercontent.com/46919374/193114103-b0499f70-35cd-4914-ab32-96ed64c849e7.gif)
That's my problem, I send `this.sendEvent(new InvalidatedEvent(['variables']))` but nothing happens)
If you need more information, I will be happy to share it.

**Comment by roblourens** [comment]
I thought you were implementing a debug adapter, now it sounds like you are trying to trigger a refresh from outside the debug session. debug events originate from a debug adapter, I don't think it's possible to send a fake event to the client from an extension. What does `this.sendEvent` actually do? How is that sending an event to the client?

**Comment by roblourens** [comment]
The expected flow would be for the debug adapter to send this event, not for some other extension to say that something changed inside a debug session that it does not own.

**Comment by sbobko** [comment]
@roblourens  At the very beginning, something like `export class SimdProvider  extends DebugSession{` is written and I hoped that this would be enough, but obviously you are right and I am trying to report a change in the debugging session that I do not own. Is there any way to inform the debugging session about the change?

**Comment by roblourens** [comment]
Not in general for an extension - you would have to file an issue on the debug adapter for that
