### ISSUE TITLE
Can't delete a profile

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#162044]
I'll be honest, I made this profile a while ago so maybe I'm just in a bad state... but I get this:
![image](https://user-images.githubusercontent.com/2644648/192611777-9f63f3a8-e08e-4579-8e31-fac1906becbc.png)

![image](https://user-images.githubusercontent.com/2644648/192611704-b0e4e467-e45a-43e0-949a-a95606c379d1.png)

Testing #161792

**Comment by sandy081** [comment]
Hmm, I think this operation would still remove the profile instead of throwing an error.

**Comment by TylerLeonhardt** [comment]
Unfortunately, it doesn't delete it so I appear stuck with having this extra profile I made a while ago.

**Comment by sandy081** [comment]
It seems I am not catching the error for tasks I do before removing the profile. They should not stop the remove operation. Fixing it. 

Please verify in tomorrows insiders if you can remove it.

**Comment by TylerLeonhardt** [comment]
Worked today!
