### ISSUE TITLE
Enabled Filter Extension option doesn't put out of date extensions at the top

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#162071]
Testing #161806

The Installed view (no filter) puts enabled outdated extensions at the top of the Extensions view. If you add the @enabled filter, the list should be the same but the ordering is now alphabetical without the outdated extensions on the top.

No filter:
![image](https://user-images.githubusercontent.com/12818376/192643811-7d50e700-3cd0-4b02-9913-bf2f0af8a782.png)

@enabled filter:
  
![image](https://user-images.githubusercontent.com/12818376/192644014-9078e3ed-3d1c-43f5-b8c0-6c2e2382d45b.png)

**Comment by sandy081** [comment]
This is intentional. We want to apply smart sorting only for default view. As soon as you have filters sorting is alphabetical.
