### ISSUE TITLE
Improvement: Own git tracking for each branch / marking files

### ISSUE THREAD

**Issue by andrewboot** [Microsoft/vscode#16200]
- VSCode Version: 1.7.2
- OS Version: Linux Ubuntu 16.04

Steps to Reproduce:

1. Create new branch
2. Save changes
3. Move to another branch.
4. Feel frustration, since all changes from previous branch still in the Git section.

It would be **awesome**, if there will be own git tracking for every branch, because now, if you change something in several branches, staging changes after that turning into a nightmare. At least, marking like "branch -> filename" would make life easier.

Thanks in advance!

**Comment by chrmarti** [comment]
This seems to be `git checkout`s default behavior. We are using that.

**Comment by andrewboot** [comment]
Unfortunately, you didn't understand, what I mean :)
I talked about situation, when changes in certain files can be seen in Git panel, just when you are in branch, where they happened. 

I'll try to explain by example:

Let's imagine, that you changed something in 5 different branches, but didn't commit changes, just saved or even staged (in this situation, that's irrelevant). Then, for example, you go to master branch and open git panel. What will you see there? You will see all changes from all branches, mixed together. That's a nightmare, which I talked about. And I propose to add separate representation for all branches or, at least, mark files like "branch name -> filename".

If it's not clear yet, feel free to contact me: webdevelop.abut@gmail.com. I will provide all information needed. Thank you for fast response.

**Comment by chrmarti** [comment]
It still sounds like you are describing `git` default behavior which is a separate tool from VSCode: https://git-scm.com/docs/git-checkout#git-checkout-emgitcheckoutemltbranchgt

E.g. if you do the following:
- Checkout branch1
- Change and save file1.txt
- Checkout branch2

Then the changes to file1.txt will be carried over when checking out branch2, they are still in the present file1.txt on disk. That's `git checkout` behavior and VSCode is using that when you checkout branches in VSCode's UI.

The Git panel shows staged and unstaged changes and with Git these only exist against the currently checked out branch.

Does that make sense or am I missing something?

**Comment by andrewboot** [comment]
I know very well how git checkout works, it's not actually relevant now since we talk about git-status: Git panel shows what's currenty going on in local repository, which is git-status work, not git-checkout, isn't it? :)

I understand that files changed in several branches keeping up to date with current branch, but there, in git panel, it's not only them, but all, from all branches, as well.

And it looks like I proposed feature for Git itself, not only to VSCode. 

I found out that Git keep showing staged/unstaged files of all branches, without considering which branch am I currently on. I just can't believe such a powerful tool don't have this feature: showing files related only (!) to current branch. I will happy to be wrong, but for now I didn't find anything that confirm it's not true!

Nevertheless, is there any chance VSCode team will implement the feature in forseeable future?

To more explanation, here is workflow in short form:

Checkout to branch -> Git panel updates to show changed and staged files related only to this concrete branch, not to all of the branches.

**Comment by iamstarkov** [comment]
> Nevertheless, is there any chance VSCode team will implement the feature in forseeable future?

it will be disappointing if VS Code git integration's behavior will differ from actual git's behavior.

**Comment by iamstarkov** [comment]
> I found out that Git keep showing staged/unstaged files of all branches, without considering which branch am I currently on. I just can't believe such a powerful tool don't have this feature: showing files related only (!) to current branch.

git is not trying to be smart, and its a good thing. Its also stateless. Yes, you can stage files in whatever branch you are, and then do actual commit in another branch. Its not a bug, its intended simple stateless workflow.

**Comment by iamstarkov** [comment]
I would say we close this issue

**Comment by andrewboot** [comment]
I agree. Thank you @iamstarkov . @chrmarti Sorry for wasting your time.

**Comment by chrmarti** [comment]
@andrewboot Have you looked into using `git stash` to put aside the current set of local changes so you can work on others? I'm using that or a temporary commit to the branch the changes are for.

**Comment by andrewboot** [comment]
Thanks for the tip, I definitely will need and try `git stash` soon :)
