### ISSUE TITLE
Applying `SnippetTextEdit`s don't put the editor into snippet mode

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162073]
Testing #161809

1. Have the following code in a command
```ts
		const edit = new vscode.WorkspaceEdit();
		const file = vscode.Uri.joinPath(vscode.workspace.workspaceFolders![0].uri, 'test.md');
		await vscode.window.showTextDocument(file);
		const pos = new vscode.Position(0, 0);
		const snip1 = new vscode.SnippetTextEdit(new vscode.Range(pos, pos), new vscode.SnippetString('foo'));
		const snip2 = new vscode.SnippetTextEdit(new vscode.Range(pos, pos), new vscode.SnippetString('bar'));
		edit.set(file, [snip1, snip2]);
		vscode.workspace.applyEdit(edit);
```
2. Create an empty file called test.md in the root of your folder
3. Run the command 
4. :bug: editor is not put into snippet mode, edits are applied as though the file was not open in the active editor

**Comment by jrieken** [comment]
> empty file called test.md in the root of your folder

The editor for the file needs to be open at the time of submitting the edits. That's the current limitation because while we prepare the edits we decide to use editor-based text editing or not. The fact that an editor eventually opens in only due to workbench logic that auto-reveals unsaved files

**Comment by joyceerhl** [comment]
Oh to clarify, I was able to repro this behavior even when the file being edited was open in the active editor.

**Comment by jrieken** [comment]
Got the time to look into this. The issue is that the snippet edits from above aren't actually triggering snippet mode, now placeholder etc are being used so this is effectively a "normal" edit. Using something like below works fine for me. Please reopen if it doesn't work for you

```ts
const snip1 = new vscode.SnippetTextEdit(new vscode.Range(pos, pos), new vscode.SnippetString('f$1oo'));
const snip2 = new vscode.SnippetTextEdit(new vscode.Range(pos, pos), new vscode.SnippetString(`b$1a\${2:hehe}r`));
```
