### ISSUE TITLE
tmTheme highlighting issues in vscode (Material Theme)

### ISSUE THREAD

**Issue by fredrikaverpil** [Microsoft/vscode#16206]
[The Material Theme from the tmTheme editor](http://tmtheme-editor.herokuapp.com/#!/editor/theme/Material%20Theme) doesn't render as intended per the tmTheme specs in vscode. I'm not sure if these themes are supposed to render in vscode exactly like they appear in the mtTheme editor?

- VSCode Version: 1.7.2
- OS Version: Windows 10, macOS Sierra/El Capitan

Steps to Reproduce:

1. Download and install extension "Material Theme" by Fredrik Averpil (that's me)
2. Enable extension and switch theme to "Material Theme"
3. Copy paste the following and set syntax to Python:

```python
def hello(some_option=None):
    """docstring here"""

    call_some_function(with_arg='some_string')
    self.call_other_function(with_arg='some_string')
    some_object.call_yet_another_function(with_arg='some_string')
```

### Expected highlighting

As per Sublime Text:

<img width="374" alt="sublime" src="https://cloud.githubusercontent.com/assets/994357/20704580/292273f0-b620-11e6-85c7-b81c1df4a113.png">

...and tmTheme-Editor:

<img width="449" alt="tmtheme-editor" src="https://cloud.githubusercontent.com/assets/994357/20704586/2efa4370-b620-11e6-8aaf-2dd56188e9b7.png">

#### Note

The docstring is rendered differently in Sublime Text, which I guess is because of a customization for Sublime, so please disregard this.

### Actual highlighting in vscode:

<img width="397" alt="vscode" src="https://cloud.githubusercontent.com/assets/994357/20704595/36665a36-b620-11e6-9e6f-4a6d4526b131.png">

#### Issues with vscode highlighting

* Function arguments are not highlighted in orange (instead they are red)
* Strings inside function calls are not highlighted in green (instead they are blue)
* Objects are not highlighted in blue (instead they are white)

### Additional information

The extension is using the exact same `.tmTheme` theme which can be downloaded from the [tmTheme-editor](http://tmtheme-editor.herokuapp.com/#!/editor/theme/Material%20Theme). The theme is also maintained by Mattia Astorino and can be found in his git repo [here](https://github.com/equinusocio/material-theme/blob/develop/schemes/Material-Theme.tmTheme). The theme file from tmTheme-editor and from Mattia's github repo are very similar and they both produce the same highlighting issue in vscode.

**Comment by alexandrudima** [comment]
Great timing! I'm actually working on a fix for the way we match TM themes in https://github.com/Microsoft/vscode-textmate/tree/next (in the next branch). It will take some time to get it in vscode though, hopefully this month.

**Comment by fredrikaverpil** [comment]
That's great news! I'll be on the lookout for an issue update or vscode update in a while then!

**Comment by alexandrudima** [comment]
The work in vscode-texmate is done, but adopting the new logic will happen in the next milestone.

**Comment by fredrikaverpil** [comment]
@alexandrudima I Wonderful! I know this is off-topic but can I get a hold of this using some kind of developer build of vscode or something?

**Comment by alexandrudima** [comment]
The code is on the `next` branch in vscode-textmate: https://github.com/Microsoft/vscode-textmate/tree/next

The new logic will be exercised once we begin to call `IGrammar.tokenizeLine2` which will give binary encoded tokens with theme information resolved. Today, we call `IGrammar.tokenizeLine` which gives back scopes and then we let CSS do the token matching. 

The only place where the new code is exercised is in the extensive theme test suite.

The integration in vscode is still to be done (it involves adopting this new binary encoded representation in the buffer, in the view, etc.)

**Comment by fredrikaverpil** [comment]
@alexandrudima I better wait then ;) Cheers again for this nice update!

**Comment by wprater** [comment]
@alexandrudima Ive found another sublime material theme, but Im afraid it's in the new `sublime-theme` format. Is there a converter for this theme format as well?
