### ISSUE TITLE
Conflict notification blocks 'Open in Merge Editor' button

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#162037]
Testing #161833

Related to #153712, this notification blocks the button. Many users may never close it and will never see the merge editor button.

![CleanShot 2022-09-27 at 11 25 23@2x](https://user-images.githubusercontent.com/25163139/192606773-e9b67bb0-778d-4d09-8d60-dd0233e3497b.png)

**Comment by jrieken** [comment]
Adding @lszomoru because this message isn't something the 3wm editor controls but something that comes out of git itself

**Comment by jrieken** [comment]
With https://github.com/microsoft/vscode/pull/167265 I have added another option that allows user to show the SCM view/changes so that they can (1) get rid of the notification and (2) have a way to see all conflicts to handle them
