### ISSUE TITLE
Can't stop Edit Sessions

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#162098]
Testing #161860

I've gotten into a state where my Source Control view is showing two repositories even though I've just opened code-insiders in one.

![image](https://user-images.githubusercontent.com/12818376/192666010-226558a9-674a-420a-81bd-f6dc134567cf.png)

Trying Turn Off Edit Sessions doesn't seem to help.

Even odder, there are no stored Edit Sessions

![image](https://user-images.githubusercontent.com/12818376/192666274-e7ff1227-afce-4825-bad4-6998f4b80af4.png)

**Comment by gregvanl** [comment]
Signing out from GitHub doesn't seem to help either

**Comment by gregvanl** [comment]
I found the "Close repository" command which removed the vscode-docs repo from the Source Control view.
I can I'm surprised it was added when I opened the Edit Sessions view

**Comment by joyceerhl** [comment]
Did you happen to use the Continue On > Clone Locally flow at some point? Opening the Edit Sessions view should not have anything to do with this.

**Comment by gregvanl** [comment]
Hmm, the second repo came back when I reloaded the window.
I see "Resuming edit session" on the Status bar

**Comment by gregvanl** [comment]
Nope, only playing with Edit sessions.

**Comment by joyceerhl** [comment]
"Resuming edit session" will pretty much appear all the time when you first open a window unless you explicitly disable it, but it doesn't do anything with checking out git repositories. Is there anything in the `Git` or `Log (Edit Sessions)` channel, and do you recall what you've tried with Edit Sessions so far?

**Comment by gregvanl** [comment]
I was working with Edit Sessions in the vscode-docs repo and then I switched to working in vscode-website. The Edit Sessions view correctly (I believe) showed sessions from both repositories.
Not sure why the vscode-docs repo was added to the Source Control view

**Comment by gregvanl** [comment]
OK, might have been a red herring. 
The vscode-website repo clones the vscode-docs repo if you build the website locally. The vscode-docs repo shown in the Source Control view is for that sub-repo.
What is odd is that Stable doesn't show the sub-repo and I don't think I've noticed that before with the 1.72 Insiders but something might have changed recently to include sub-repos in the Source Control view?

**Comment by gregvanl** [comment]
git.autoRepositoryDetection controls the behavior. If I set it to false, VS Code doesn't pick up the sub-repo.
I wonder if an issue was fixed recently with repo detection

**Comment by gregvanl** [comment]
Closing this as not related to Edit Sessions. Seems to be a change in sub-repo detection. I'll follow up with Lad

**Comment by joyceerhl** [comment]
Yeah this landed via https://github.com/microsoft/vscode/pull/159291
