### ISSUE TITLE
Find in files issue

### ISSUE THREAD

**Issue by charlie-hou** [Microsoft/vscode#16201]
the behaviour of CMD + SHIFT + F is different from CMD + F, CMD + F will automatically fill the word under cursor into search input field, but find in files will not.

I have to select word under cursor before CMD + SHIFT + F to perform this action, and in my opinion, it's not convenient to use find in file feature.

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|beautify|HookyQR|0.5.5|
|vscode-docker|PeterJausovec|0.0.7|
|unity-debug|Unity|1.0.4|
|vscode-javascript-snippet-pack|akamud|0.1.5|
|vscode-eslint|dbaeumer|1.1.0|
|python|donjayamanne|0.5.5|
|MagicPython|magicstack|0.5.17|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|mono-debug|ms-vscode|0.11.0|
|vscode-icons|robertohuertasm|4.0.2|
|Spell|seanmcbreen|0.8.6|
|python|tht13|0.2.3|
|vim|vscodevim|0.4.3|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|
|vscode-proto3|zxh404|0.0.4|

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Works as requested in 1.11.
