### ISSUE TITLE
Merge Editor: When Accepting a Input code lens without the both option you just get left behind an empty space

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#162033]
Testing #161834

1. Open a merge conflict without an automatic "Both" option
2. Accept one of the sides

<img width="716" alt="image" src="https://user-images.githubusercontent.com/812783/192604095-3a373993-3f3a-4156-8027-1c7a0fc926b6.png">

This looks visually odd, the space is reserved for the lenses, but there is nothing there. I'd expect either of the following:
1. Put a code lens for "Remove Input 1" there so I can undo the action
2. Rerender so the empty space goes away

**Comment by hediet** [comment]
This is by design.

> Put a code lens for "Remove Input 1" there so I can undo the action

I got feedback to not show this so that it feels more "done".
@jrieken @alexdima

> Rerender so the empty space goes away

This would cause alignment issues when the space is still reserved for the other side.
