### ISSUE TITLE
open VSCode from task bar using right click

### ISSUE THREAD

**Issue by algaly** [Microsoft/vscode#16209]
on task bar i do a right click to open a centain project i want
but long path doesnt reveal project name not even a tooltip 

Steps to Reproduce:

1. show all recent projects name with tooltip for long paths

**Comment by chrmarti** [comment]
What OS is this? Which version of VSCode?

**Comment by chrmarti** [comment]
Closing after not having received additional information.

**Comment by algaly** [comment]
Hi,
Sorry for the d...e...l....a...y
OS: Win10

**Comment by chrmarti** [comment]
There should be a tooltip when you hover the mouse over one of the folder names.
