### ISSUE TITLE
Test: Discover Git Repositories - Unsure how to list all changes again

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162022]
Testing #161797

<img width="249" alt="image" src="https://user-images.githubusercontent.com/31675041/192594232-d9b1e867-8550-4ae8-ab20-e87ce833d2b1.png">
I'm in this state and it's unclear how to get back to the view where you see all of the changes in all repos. I was initially thinking that clicking outside of the viewlet would restore that view, but it seems that selection remains within the viewlet and the listing of the single repo's changes is still there.

**Comment by lszomoru** [comment]
@andreamah, the "Source Control Repositories" view that contains the list of repositories supports multi-select using either SHIFT or Ctrl. The "Source Control" view will show all the repositories that are selected in the "Source Control Repositories" view.
