### ISSUE TITLE
How to edit Comment Line style

### ISSUE THREAD

**Issue by ttn10** [Microsoft/vscode#16202]
- VSCode Version: 1.7
- OS Version: Windows 7

Hi, i used `Ctrl + /` to comment code like: `//`
but i want to output like this: `/* $1 */` :smiley_cat: 
How can i do it?

**Comment by mjbvz** [comment]
This first action (<kbd>ctrl</kbd><kbd>/</kbd>) uses the `editor.action.addCommentLine` command.

To do a block comment in languages that support them, use the `editor.action.blockComment` command. This is bound to <kbd>shift</kbd><kbd>alt</kbd><kbd>a</kbd> by default, but [you can easily change this](https://code.visualstudio.com/Docs/customization/keybindings).
