### ISSUE TITLE
Test: "Just my Code" feature of node and node2

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16208]
Test for #3215:

- [x] Windows - **@ramya-rao-a**
- [x] OS X - **@chrmarti** 
- [x] Linux - **@Tyriar** 

Complexity: 3

The VS Code node debuggers (Node Debug and Node Debug 2) now support a feature similar to Visual Studio's "Just my Code" feature. With this you can easily skip over "uninteresting" code when debugging.
The feature is enabled by specifying the skipped code through a set of glob patterns for a `skipFiles` attribute. Positive patterns (e.g. `foo/**/*.js`) add to the set of skipped files, while negative patterns (e.g. `!foo/**/bar.js`) subtract from that set. In the following "skipped code" means code that is covered by the `skipFiles` glob patterns.

If skipped code is enabled, debugging is affected in the following way:
- if you step into skipped code, VS Code will continue to 'step in' until it reaches code that is not skipped.
- If you have a breakpoint in skipped code, the debugger will still break at that breakpoint and you can step manually inside the skipped code until you 'continue' or step out of it.
- You won't break on caught exceptions thrown in skipped code.

Verify that:
- the feature works as described both for debug type `node`and `node2`

**Comment by roblourens** [comment]
Note that `!` patterns aren't implemented in node-debug2. It should print a warning message if you have any present in your launch config.
