### ISSUE TITLE
Paste image from clipboard in notebook inserts wrong link

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#162024]
These steps did not work for me - I do not see the image preview after pressing `ctrl+enter`

<img width="774" alt="image" src="https://user-images.githubusercontent.com/10746682/192572903-55e5fffa-c787-48e6-9a98-7b80577b958c.png">

May I know if I am missing something?

_Originally posted by @sandy081 in https://github.com/microsoft/vscode-jupyter/issues/11463#issuecomment-1259695698_

**Comment by mjbvz** [comment]
@rebornix This looks like the default paste behavior of VS Code, not the markdown extension

@sandy081 Did you make sure to enable both `editor.experimental.pasteActions.enabled` and `ipynb.experimental.pasteImages.enabled` for testing?

**Comment by rebornix** [comment]
@mjbvz you are right, the two settings are still required.
