### ISSUE TITLE
Missing no. of occurrences in find widget in terminal in new Insider build

### ISSUE THREAD

**Issue by abhijitchikane** [microsoft/vscode#162010]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: VS Code insider build
- OS Version: Windows 10

Steps to Reproduce:
current
![image](https://user-images.githubusercontent.com/50770619/192581308-f44d89dc-eede-406a-b4ec-2e39a9634ebf.png)

new 
![image](https://user-images.githubusercontent.com/50770619/192580947-f3d6fe55-85ff-418e-83e6-946483158990.png)

**Comment by meganrogge** [comment]
when there are matches, this styling hides it
![Image](https://user-images.githubusercontent.com/29464607/192627174-ab6fa0ca-7da0-40a5-baa1-15e2829ae2c1.png)

**Comment by meganrogge** [comment]
This is by design
