### ISSUE TITLE
Merge Editor: Orange Conflict highlights seems to have some small visual issues

### ISSUE THREAD

**Issue by IanMatthewHuff** [microsoft/vscode#162032]
Testing #161834

Using Merges / Conflicts / 0a1a.... / src_compiler_checker_ts

Issue 1 (orange box cutting into the text + scrollbar):
<img width="769" alt="image" src="https://user-images.githubusercontent.com/812783/192602360-7e623baa-9f7e-4fa0-a56f-03eab182e14b.png">

Issue 2 (scrolling up from below, the orange conflict box just goes away at one point on the Input 2 file):

Starting at the bottom:
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/812783/192602641-0b25473d-cac9-4af9-a6ae-2cc55421080e.png">

Scroll up a bit:
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/812783/192602706-f4d56f94-3334-4947-9980-38e8f7e5075e.png">

**Comment by hediet** [comment]
/duplicate #158863. Unfortunately not easy to fix.
