### ISSUE TITLE
l10n sample README feedback

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162023]
Testing #161870

Small typo in https://github.com/microsoft/vscode-extension-samples/blob/990c4253726858f4457e73bd279faf1c713949d3/l10n-sample/README.md#L24  -- either missing a second option to run an extension using a proposed API (in extension development host), or the 'either' should be removed?

For
https://github.com/microsoft/vscode-extension-samples/blob/990c4253726858f4457e73bd279faf1c713949d3/l10n-sample/README.md#L52-L58

I wonder if we can update https://github.com/microsoft/vscode-generator-code to scaffold the l10n directory, add the required "l10n" key to the package.json (once the proposed API is finalized of course), and even include a sample script like the cli.ts. Then we could also have a step in the extension generator which asks you "Do you want to set up localization for this extension" or similar. Also, is it common that extensions will have to use @vscode/l10n (my understanding is it's for extensiosn which have strings that need localizing in subprocesses), and if not, could we move that section below @vscode/l10n-dev?

Minor nit, "it's" -> "its" on https://github.com/microsoft/vscode-extension-samples/blob/990c4253726858f4457e73bd279faf1c713949d3/l10n-sample/README.md#L62

**Comment by TylerLeonhardt** [comment]
I've fixed all your README comments.

> I wonder if we can update https://github.com/microsoft/vscode-generator-code to scaffold the l10n directory, add the required "l10n" key to the package.json (once the proposed API is finalized of course), and even include a sample script like the cli.ts. Then we could also have a step in the extension generator which asks you "Do you want to set up localization for this extension" or similar.

Yeah I like this a lot. I'm thinking such a script could:
* create an l10n folder
* update the `l10n` in package.json
* add `@vscode/l10n-dev` as a dev dependency
* create a package.nls.json with `{}` and a big useful comment

I think that `@vscode/l10n`'s scenario is so uncommon that it's probably not worth including that in the generator IMO. Like it's _only_ gonna be useful if your extension has like... a language server or debug adapter written in node (in other words... subprocesses that will only be used by VS Code that aren't in the extension host)

**Comment by TylerLeonhardt** [comment]
Tracking the generator-code change in https://github.com/microsoft/vscode-generator-code/issues/381 so I can close this.

Verification can just be about making sure I fixed the typos.
