### ISSUE TITLE
Unclear whether in tree view or not (Search)

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162088]
Sometimes (especially if all the search results are in the level below the workspace root), it can be hard to determine whether you're in tree view or not in search. Example:
[![Image from Gyazo](https://i.gyazo.com/62e41da6f6f98285a2dc08653b902314.gif)](https://gyazo.com/62e41da6f6f98285a2dc08653b902314)

You'd need to know that the tree icon is available when you're in list view and the list icon is available otherwise. 

We could potentially adopt something like the "match case", which toggles a highlight or not. 
[![Image from Gyazo](https://i.gyazo.com/d0332900c8858d0a45ceebaf121f69a0.gif)](https://gyazo.com/d0332900c8858d0a45ceebaf121f69a0)

**Comment by gjsjohnmurray** [comment]
I have often wished that most of those buttons were at the top of the results instead of in the view header. In particular when the include and exclude fields are displayed it is a big jump to get to Collapse All.

**Comment by andreamah** [comment]
Potentially resolved with #164835, Will keep in mind if there is a better option
