### ISSUE TITLE
Unable to update VS Code CLI from tunnel

### ISSUE THREAD

**Issue by minsa110** [microsoft/vscode#162008]
Testing https://github.com/microsoft/vscode/issues/161856 on Windows

1. Install `VSCodeSetup-x64-1.72.0-exploration.exe` from `vscode_client_win32_x64_setup` and "add code to your path" during installation
2. Execute `code-tunnel-exploration` ✅ (on path and executes)
3. Open provided link in the browser
4. Get prompted to update VS Code CLI on the remote server 
![image](https://user-images.githubusercontent.com/10833267/192577815-b56d2d53-fda0-465a-bd1f-32ae7ffef49b.png)
5. "Always update" or "Update" (tried both)
6. Does not update ❌
7. Error shown as warning
![image](https://user-images.githubusercontent.com/10833267/192578077-08df2ea8-6eca-4a2e-98da-b49b604f4101.png)

**Comment by connor4312** [comment]
Thanks for testing, but this is expected since the CLI hasn't been updated to use the product service for its updating (https://github.com/microsoft/vscode/pull/161658) -- it still uses the logic for `code-server`

Duplicates https://github.com/microsoft/vscode/issues/159798
