### ISSUE TITLE
Terminal quick fixes end up matching against the text of all rows at the end of the output matcher

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#162070]
It seemed a bit off why the renderer froze for 50 seconds because of this when scanning a command's output and this is why:

![image](https://user-images.githubusercontent.com/2193314/192642596-ebedd848-7f00-4c04-92a3-4a7220c09724.png)

We should be doing `line.match`, not `output.match` above

**Comment by meganrogge** [comment]
often the `line` contains only a part of the pattern we're looking for though
