### ISSUE TITLE
Merge Editor: add explicit action to "Keep Base" in result pane?

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#162040]
Testing #161833

I like how the result panel says "No Changes Accepted" but I wasn't sure how I can mark the conflict as handled with the intention of keeping base.

![CleanShot 2022-09-27 at 11 28 05@2x](https://user-images.githubusercontent.com/25163139/192607249-8d85cdc6-297b-4bb3-ba92-df2e546aad2f.png)

We could add an explicit action in addition to the helpful label. Something like...

<img width="1030" alt="CleanShot 2022-09-27 at 11 32 26@2x" src="https://user-images.githubusercontent.com/25163139/192607940-939d9c20-f151-4115-9224-7af043256004.png">

...and maybe a reset option to get back to it's original untouched state? Not sure what the best way to phrase this would be:

<img width="1016" alt="CleanShot 2022-09-27 at 11 34 29@2x" src="https://user-images.githubusercontent.com/25163139/192608309-4d662368-962c-413f-bfb4-85d62d3fe06f.png">

**Comment by hediet** [comment]
I think "Base" is quite technical, maybe "Common ancestor" is better.

**Comment by daviddossett** [comment]
I do wonder what the best term is here. Incoming and Current are git-specific terms, correct? Is there a similarly common term git uses for this? 

Base is used with "Compare with Base" so I feel we should be consistent regardless of what terminology we land on.

**Comment by hediet** [comment]
Implemented by #162656
