### ISSUE TITLE
Option to stick output to bottom

### ISSUE THREAD

**Issue by depl0y** [Microsoft/vscode#16203]
When you have a lot of text scrolling by in the Output window (for example grunt tasks), it would be a nice feature to be able to let the Output window stick to the bottom, so you always see the last lines of text.

I saw an issue #3351 but this issue doesn't make it clear to me if there is an option for this or not.

**Comment by chrmarti** [comment]
This should work as you expect. What version of VSCode are you using? Is this only with grunt tasks or all tasks?

**Comment by depl0y** [comment]
@chrmarti I have this problem in at least the Git and the Tasks 'tabs' of the output window.

I am using the insiders version of Visual Studio Code (currently c032f0e2bc602eb9388221876911913e5a808aec)

**Comment by isidorn** [comment]
The output should automatically scroll if the last line is reveled already.

Thus if you have scrolled up you will remain in scroll position. Otherwise it always scrolls to bottom, more details https://github.com/Microsoft/vscode/issues/3351
Closing as designed
