### ISSUE TITLE
Merge Editor: consider "Complete Merge" for button text

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#162043]
Testing #161833

This was feedback I heard from others too—"Accept Merge" is a bit strange since you aren't really accepting a merge so much as the individual changes. I think "Complete Merge" would make more sense here.

<img width="265" alt="CleanShot 2022-09-27 at 11 50 56@2x" src="https://user-images.githubusercontent.com/25163139/192611413-bc8232fd-91b4-45a0-967d-0f38f57b9313.png">

**Comment by gjsjohnmurray** [comment]
Or maybe "Confirm Merge".

**Comment by hediet** [comment]
More ideas:
* `Stage`
* `Complete Merge` - I like this
* `Confirm Merge` - I think "confirm" is usually used to approve an already stated intention and does not fully fit here.

**Comment by isidorn** [comment]
"Complete Merge" and "Accept Merge" are the best options. I am leaning towards "Complete Merge".

fyi @bpasero

**Comment by bpasero** [comment]
👍 for "Complete Merge"
