### ISSUE TITLE
Merge Editor: Consider removing inline CodeLens icons?

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#162042]
Testing #161833

I think the merge editor CodeLens actions are the only examples I've seen of icons being used—not sure they are obvious/big enough to really be of much value here. Is there any prior art for using them?

<img width="269" alt="CleanShot 2022-09-27 at 11 42 19@2x" src="https://user-images.githubusercontent.com/25163139/192609730-bba91823-0869-4bca-9569-abaaf47939fa.png">

<img width="244" alt="CleanShot 2022-09-27 at 11 43 33@2x" src="https://user-images.githubusercontent.com/25163139/192610048-7dba097c-7891-40bd-b7e8-52dac48748c0.png">

**Comment by hediet** [comment]
I can remove them. Personally I like them, as they give a non-textual clue about what is going to happen.

**Comment by daviddossett** [comment]
Why don't we start with the minimal text and then we can always choose to add them (or something else) back. Harder to remove things once they are in.
