### ISSUE TITLE
Line indent doesn't handle leading whitespace properly

### ISSUE THREAD

**Issue by latkin** [Microsoft/vscode#1620]
Indenting a line with leading whitespace seems to have some corners that need ironing out.  It appears to be attempting something smart about tab-stop alignment, but it should really just be dumb and indent all lines the same.

e.g.
![screen shot 2015-12-23 at 1 42 16 pm](https://cloud.githubusercontent.com/assets/5943573/11985572/05ae03e2-a97b-11e5-9c29-9c59e8131adb.png)

![screen shot 2015-12-23 at 1 43 09 pm](https://cloud.githubusercontent.com/assets/5943573/11985584/21ffcf62-a97b-11e5-957d-5dd25b874630.png)

Right-justified tabular data is affected by this (e.g. output of many Powershell commands, or the robocopy usage message)

![screen shot 2015-12-23 at 1 45 18 pm](https://cloud.githubusercontent.com/assets/5943573/11985612/7890e096-a97b-11e5-9307-8577d0ee52a2.png)

![screen shot 2015-12-23 at 1 45 33 pm](https://cloud.githubusercontent.com/assets/5943573/11985616/7d47d72a-a97b-11e5-8e8b-40ef987c29a1.png)

**Comment by alexandrudima** [comment]
Maybe we should have an option for "dumbing down" the indent/unindent actions. Our thinking was to optimize them for source code, where mostly I'd say "leading whitespace aligned" lines are highly desirable.

**Comment by latkin** [comment]
I would recommend the default behavior be "dumb" block indenting (same as Visual Studio, Notepad++, every other editor), with an option "Block indent performs auto-formatting" or the like.

Even in source code this can be destructive/annoying.  Unless every line is already aligned to a tab stop, stuff is liable to get jumbled.  Certainly I like that my editor *can* auto-format for me when I ask it to, but I don't want it to do so during a bulk indent action.

![indent](https://cloud.githubusercontent.com/assets/5943573/12329261/5cb87b34-ba94-11e5-9a36-87c1e037bb27.gif)

**Comment by alexandrudima** [comment]
The indentation commands will now respect the `editor.useTabStops` setting. In other words, to get this behaviour, set `editor.useTabStops: false`.
