### ISSUE TITLE
Test: Discover Git Repositories - Closing a non-workspace file in the editor doesn't remove its source control

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162026]
Testing #161797

1. Open a file that isn't a part of the workspace, but is still tracked by git
2. Its git repo is tracked in source control (expected)
3. Close the file in the editor
4. The git repo is still tracked :bug: 

![Recording 2022-09-27 at 10 32 31](https://user-images.githubusercontent.com/31675041/192596343-1818027a-b751-472b-9b1b-39414273edbb.gif)

**Comment by lszomoru** [comment]
@joaomoreno, thanks for the insights. I will close this issue for now, and will keep an eye out for similar feedback.
