### ISSUE TITLE
"Collapse All" in search changes output order

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#162014]
Testing #161849

- Open https://github.com/microsoft/vscode-docs in VS Code Insiders
- Search for "containers"
- Exploring results and collapsing/uncollapsing works for a while
- :bug: Then "Collapse All" does nothing

![Recording 2022-09-27 at 09 53 46](https://user-images.githubusercontent.com/25310137/192588411-f02f0ec9-7f6c-4ff4-9750-7e73a4959df2.gif)

**Comment by bamurtaugh** [comment]
It seems I'm able to repro by:

- Reload window from above state
- Search for "containers" again, works correctly ✅ 
- "Collapse All," works correctly ✅ 
- Uncollapse, works correctly ✅ 
- Try "Collapse All" again, stuck in unresponsive state above 🐛

**Comment by bamurtaugh** [comment]
Actually seems I misread the button - I guess it's always "Collapse All" and doesn't become an option to uncollapse. I was confused since hitting collapse two times in a row initially looked different, so I assumed it was collapsing and then uncollapsing. Not sure if this is expected:

![Recording 2022-09-27 at 10 00 52](https://user-images.githubusercontent.com/25310137/192589966-35c63108-edaa-44a5-9cbc-e901400c4b81.gif)

If it is, please feel free to close. Sorry for confusion!

**Comment by andreamah** [comment]
No, that's totally a bug 😅, it shouldn't get stuck like that. Thanks for catching that!
