### ISSUE TITLE
Search Tree - Button to return to list view looks too much like the "Clear Search Results" button

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162089]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/31675041/192656313-7b348e6a-836a-4007-85b3-d1e0ead4b313.png">

When you're in tree view, the button that has you return to the list view is very similar to the one two to the left that is for dismissing all search results. This might cause users to click the wrong button or get mixed up.

Also, SCM uses the same icons, so if they were to be updated, it'd be best to update them in SCM for consistency.

cc @daviddossett

**Comment by gjsjohnmurray** [comment]
In general I feel that the "Clear Search Results" icon doesn't communicate its function strongly enough. Maybe it can have a bigger X. Seen alongside the New File icon's + it looks rather feeble. Also, perhaps withe fewer of the lines or less of some of them it would better convey erasure.

**Comment by daviddossett** [comment]
I see we have `list-selection` which is what I normally would have proposed as the default list icon vs. what we have today. This is consistent with Fluent icons normal list icon.

From Codicons:
<img width="124" alt="CleanShot 2022-10-03 at 15 58 04@2x" src="https://user-images.githubusercontent.com/25163139/193700440-c2ddb8d7-80d2-418f-8557-8c73a0d77d04.png">

<img width="244" alt="CleanShot 2022-10-03 at 15 59 06@2x" src="https://user-images.githubusercontent.com/25163139/193700559-fff5b32d-6552-485c-a929-84750a702f83.png">

I'd argue that our current list icon looks too much like a hamburger menu. What would you think if `list-selection` was the normal `list` icon instead? The tradeoff here is that I'd need to look at where else both are used and see if it would be problematic to update our default icon and create another for `list-selection`.

**Comment by andreamah** [comment]
I think that it makes sense to me! I also notice that the transition from the hamburger menu to the tree view looks pretty smooth; would it be possible to make a four-line list to keep the smoothness of transitioning between the two?

[![Image from Gyazo](https://i.gyazo.com/d26fb9849acf87aed953411d5d4d77de.gif)](https://gyazo.com/d26fb9849acf87aed953411d5d4d77de)

**Comment by daviddossett** [comment]
Trying an idea here where we update both icons to more closely resemble a real list. I.e. the line lengths vary. Thoughts?

![CleanShot 2022-10-03 at 20 15 36](https://user-images.githubusercontent.com/25163139/193726907-43c8d9b4-1aee-4aa0-811d-b15ef80a8243.gif)

**Comment by andreamah** [comment]
That looks awesome!! 🎉 I personally think it looks distinct enough from the "clear search results" button, so it looks good to me.

**Comment by gjsjohnmurray** [comment]
Can we try adding a second indent to the bottom horizontal line of the tree, to make it look deeper?

**Comment by daviddossett** [comment]
Merged https://github.com/microsoft/vscode-codicons/pull/137 and created #162679 to update the two icons. 

@gjsjohnmurray here's what that would look like. I think it might be a bit hard to decipher at the small size. But I'm open to ideas here for future updates.

<img width="379" alt="CleanShot 2022-10-04 at 09 37 19@2x" src="https://user-images.githubusercontent.com/25163139/193876319-4653b596-9376-487c-a484-4356e056053a.png">

**Comment by daviddossett** [comment]
Closing given that we've replaced this icon.
