### ISSUE TITLE
New: Folder on a network drive: Source control GIT not working #42502 

### ISSUE THREAD

**Issue by Naeaeaeaeae** [microsoft/vscode#162086]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. clone a Repo onto a windows network drive (mine is connected via dns entry, not IP Adress)
2. open Folder / Workspace / ... as you wish.

VS Code will not recognize the repository in the folder, but if copied onto a local drive it will work fine.
Not sure if VSCode or git issue

**Comment by lszomoru** [comment]
@Naeaeaeaeae, are you able to reproduce this issue with the latest VS Code Insiders release? Thanks!

**Comment by Naeaeaeaeae** [comment]
Yeah, the problem is there too and I now found the error of:
fatal: detected dubious ownership in repository at --folder--

VSCode seems not the problem, more the git installation with my network drive (ntfs from an unraid server)
