### ISSUE TITLE
Edit session: improve flow when continuing edit session

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162116]
Testing #161875

<img width="699" alt="image" src="https://user-images.githubusercontent.com/900690/192694852-74b780ef-9bfd-47d6-8fe6-9f92950fb52d.png">

I think here it would be nice if I was offered a way to see the changes that will be applied and then reason. Currently it is an all or nothing question where the consequences are hard for me to understand.

**Comment by bpasero** [comment]
Oh btw there also seems to be a bug that even though the message talks about 2 files, only 1 is shown in the details.

**Comment by bpasero** [comment]
And why is this using a custom dialog when I am on native desktop?

**Comment by joyceerhl** [comment]
I used the custom dialog mostly because the native one looks bad IMO 😅 is it recommended to only use custom dialogs when we're in web?

**Comment by joyceerhl** [comment]
Adding the ability to view changes is https://github.com/microsoft/vscode/issues/157113

**Comment by bpasero** [comment]
I will create a new issue for using native dialogs.

**Comment by rzhao271** [comment]
@joyceerhl what are some verification steps for this issue?

**Comment by joyceerhl** [comment]
1. In insiders.vscode.dev/github/microsoft/vscode, create a new file and modify some existing file
2. Run Store Current Edit Session
3. Further modify the file that you changed in step 1
4. Run Resume Latest Edit Session
5. You should get a dialog telling you that the modified file will be overwritten, and it should say that 1 file will be overwritten, not 2
