### ISSUE TITLE
JSON should not replace ${workspaceRoot} as a snippet insert value

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16212]
Latest vscode insiders

1. Open launch.json, trigger snippets inside the `'configurations'` array
2. Choose node.js launch configuration
3. Notice how the `${workspaceRoot}` is treated as a snippet insert value
4. This was previously possible and since now snippets require a `${number:name}` syntax the snippet content should not be treated as an insert value if it does not have a number

**Comment by isidorn** [comment]
If I try to double escape the $ via `\\$` I get left with a \ in the end. So that does not seem to work.
Escaping the curly bracket also does not do the trick

**Comment by jrieken** [comment]
The syntax you are using is the syntax for variables and default to placeholders when a variable is not known. Still, the escaping should work with a single backslash.

**Comment by isidorn** [comment]
@jrieken the escaping is not working both with single and double backslash

**Comment by aeschli** [comment]
defaultSnippets nw also support a property 'bodyText' that lets you define your snippet as a string that will be inserted 'as-is' to the JSON document. Indent and new lines will be corrected, but it can contain any content, including comments and snippet variables (or escaped snippet variables)
