### ISSUE TITLE
It takes two undo steps to undo a link definition conversion

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162151]
Testing https://github.com/microsoft/vscode/issues/162094

1. "extract link definition" on a markdown link
2. Undo it
3. Notice you need to undo twice to fully undo it

**Comment by mjbvz** [comment]
This is by-design for now as it aligns with how 'extract' works in JS/TS

In the future we can explore using snippet text edits instead for the rename, as I think this should result in a single undo stop (we're also exploring the same for JS/TS)
