### ISSUE TITLE
Extension logging API - output channel

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#162182]
Testing #161786

Are we planning on bringing the "time stamp", and "colouring" improvements to the "normal" output channels. I am asking as probably we will probably continue to have two "channel" for the Git extension (one for the git commands, and one for the logs).

**Comment by sandy081** [comment]
> Are we planning on bringing the "time stamp", and "colouring" improvements to the "normal" output channels.

I do not think so. Only log output channels will have timestamp and colouring.
