### ISSUE TITLE
VSCode will stop working when laptop goes to sleep 

### ISSUE THREAD

**Issue by Hanmo123** [microsoft/vscode#162164]
Does this issue occur when all extensions are disabled?: Not Sure

- VS Code Version: latest
- OS Version: Win11 22H2 22621.521

Steps to Reproduce:

1. Start VSCode
2. Wait until laptop goes to sleep

Not every attemp reappears. Before submitting the issue, i've tried reinstall the OS (raw OS is also Win11) , then the problem still appears, but the frequency is much lower.
When the BUG occurs, it seems that I can't do actions like inputting, moving the cursor and even closing the window. If i minimize the window and recovery, it will responding to the last operation but still not react probably. Only when i restart the window it will behave correctly.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/149247
