### ISSUE TITLE
vscode.css-language-features does not format CSS rules inside <style> section in .vue files

### ISSUE THREAD

**Issue by ildar-gilmanov** [microsoft/vscode#162154]
Type: <b>Bug</b>

1. Add the following settings to the `.vscode/settings.json` file:

```json
{
  "editor.formatOnSave": true,
  "editor.defaultFormatter": "dbaeumer.vscode-eslint",
  "editor.codeActionsOnSave": [
    "source.fixAll.eslint"
  ],
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "vue"
  ],
  "eslint.format.enable": true,
  "[css][scss][less]": {
    "editor.defaultFormatter": "vscode.css-language-features"
  }
}
```

2. Create a `test.vue` file with the ugly scss section:

```
<style lang="scss" scoped>

                 .my-class {
      position: relative;
           color: red;
}


</style>
```

3. Save the file and/or call the command `Format Document`

4. Expected results: the scss section in the `test.vue` file should be fixed. Actual results: the scss section is not changed.

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No
Remote OS version: Linux arm64 5.10.124-linuxkit
Remote OS version: Linux arm64 5.10.124-linuxkit

<details>
<summary>System Info</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.251.0
Bookmarks|ale|13.3.1
path-intellisense|chr|2.8.1
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
docs-markdown|doc|0.2.114
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
todo-tree|Gru|0.0.215
vue-snippets|hol|1.0.4
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.22.1
hexeditor|ms-|1.9.8
vscode-thunder-client|ran|1.19.3
vscode-fileutils|sle|3.5.0
code-spell-checker|str|2.8.0
code-spell-checker-russian|str|2.0.6
sort-lines|Tyr|1.9.1
vscodeintellicode|Vis|1.2.27
volar|Vue|0.40.13

</details>

**Comment by ildar-gilmanov** [comment]
I have found the similar ticket, but it was not resolved: https://github.com/microsoft/vscode-eslint/issues/1370

**Comment by aeschli** [comment]
The css formatter would only be used if the language mode is CSS, LESS or SCSS. 
I assume in your case it is `vue`. That means a formatter for vue is used. You need to install a vue extension that provides a formatter. If you already have done that and the formatter doesn't work, file an issue against the vue extension.

**Comment by ildar-gilmanov** [comment]
@aeschli , I use the `dbaeumer.vscode-eslint` for vue files and this works great for `html` and `script` sections, but it does not work for `css` (`scss`).

@dbaeumer had closed the https://github.com/microsoft/vscode-eslint/issues/1370 with the explanation:

> please file an issue against the CSS plugin that you use for formatting.

So, it is strange: Vue extension's developers say that the source of the issue in the CSS plugin, CSS plugin's developers say that the source of the issue in the Vue plugin.

@aeschli, @dbaeumer , could you please contact each other and solve the issue?

In any way, many thanks to you both - the plugins are great! But unfortunately they do not work correctly with `<style>` section in `.vue` files.

**Comment by ildar-gilmanov** [comment]
I have created a ticket for vuejs/eslint-plugin-vue: [Format CSS and SCSS code inside <style> section in .vue files](https://github.com/vuejs/eslint-plugin-vue/issues/1997)
