### ISSUE TITLE
Code action widget UX inconsistencies

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162125]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/900690/192712068-e659a83b-b068-4849-b552-16c98ada4a2f.png">

**Differences:**
* using background shadow or not
* different background color for status area
* different text colors

I feel the new widget should adopt the style from existing widgets such as hover and suggest widget.

//cc @daviddossett

**Comment by mjbvz** [comment]
I'm going to fix the foreground for September (this was a simple typo)

For the shadow, we are currently using `widget.shadow` color theme. However some widgets like the suggest widget, don't use any shadow

**Comment by bpasero** [comment]
> For the shadow, we are currently using widget.shadow color theme. However some widgets like the suggest widget, don't use any shadow

The editor hover also does not use any shadow btw.
