### ISSUE TITLE
"Extract link definition" rename automatically closes after a second

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162149]
Testing: https://github.com/microsoft/vscode/issues/162094

1. Have a markdown link, in a file without any existing link definitions
2. Ctrl+. to "extract link definition"
3. Do that, notice the rename widget. Wait a moment without interaction, and the rename widget closes automatically

**Comment by mjbvz** [comment]
I haven't been able to reproduce this

@connor4312 Is it possible something else is taking focus from the rename widget?

**Comment by connor4312** [comment]
I can repro this on multiple devices by taking this action on the first "Microsoft" link on https://github.com/microsoft/vscode/blob/main/SECURITY.md for example.

It looks like the editor takes/is given focus back, as the cursor is on `[|def]` when it closes

**Comment by ShaMan123** [comment]
I got something similar.
In some syntax cases it won't let me rename at all.

https://user-images.githubusercontent.com/34343793/195976700-69450d08-eda0-439f-b257-bee1ace4c507.mp4

**Comment by mjbvz** [comment]
@ShaMan123 Please open a new issue with the markdown source from that example

**Comment by mjbvz** [comment]
@connor4312 I still can't reproduce this following those steps.

Can you please quickly test this with extensions disabled just to make sure one of them isn't causing this. Also please any potentially relevant user settings that could be causing this? I tried autosave but that did not seem to the the issue

**Comment by connor4312** [comment]
I think there was a recent Insiders changed that fixed it. I was able to reproduce it, then after doing an overdue restart (to Tuesdays' Insiders, 1c78193f54fac6036829ec554ce218d99) it didn't reproduce.
