### ISSUE TITLE
GHPRI keeps getting uninstalled

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162103]
I have no repro steps and am on the default profile in web and desktop with settings sync enabled in both, but I have re-installed the GitHub Pull Requests and Issues extension three times today and am wondering if there is something happening in extensions land, settings sync, profiles, or something else. What is the best way to debug this further? Settings sync logs below:
[settings-sync-log.txt](https://github.com/microsoft/vscode/files/9661044/settings-sync-log.txt)

**Comment by joyceerhl** [comment]
Also it looks like I cannot install `ms-vscode.vscode-python-web-wasm` in web at all, if I click on Install Pre-release the install button says Installing and then goes back to Install Pre-release, but the extensions viewlet shows a progress indicator that never goes away

**Comment by sandy081** [comment]
> Also it looks like I cannot install ms-vscode.vscode-python-web-wasm in web at all, if I click on Install Pre-release the install button says Installing and then goes back to Install Pre-release, but the extensions viewlet shows a progress indicator that never goes away

There is a bug already for it. I will look into it.

Regarding an extension getting uninstalled, it would be great if you can share the settings sync log and shared process log from the machines.
