### ISSUE TITLE
Button to open merge editor is not shown

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#162181]
Testing #161833

![image](https://user-images.githubusercontent.com/10746682/192792796-f9e6d97c-971d-446a-8831-8f899b241af8.png)

**Comment by sandy081** [comment]
This merge file is in the sub repo folder not in the root folder.

**Comment by hediet** [comment]
Currently the context key solution does not work very well with multi-repo setups.

**Comment by jrieken** [comment]
maybe the same as https://github.com/microsoft/vscode/issues/162224

@sandy081 can you inspect context keys (F1 > Inspect Context Keys) and check the value of `git.mergeChanges`. Thanks.

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/193048641-d31d2ab5-c7b5-49cf-a5d2-97bdcfc7455a.png)

**Comment by jrieken** [comment]
> This merge file is in the sub repo folder not in the root folder.

Can you clarify what this should mean? Is this a submodule or another repo? Do you still see this?

**Comment by sandy081** [comment]
It is another repo as I did git init in the sub folder. I can still repro it.

**Comment by sandy081** [comment]
I can't reproduce it anymore and I see the button now

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/10746682/198058649-fee5a467-3d8d-4990-87de-fffeaf2e3a42.png">
