### ISSUE TITLE
Sticky scroll transition is slow between files

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162128]
1. Be in a file with a sticky scroll header
2. Switch to a different file without sticky scroll
3. Notice it takes like ~200ms to remove the sticky scroll

https://user-images.githubusercontent.com/2230985/192714875-c916312f-f0e7-4136-b6cb-5467632f734e.mp4

**Comment by slymon99** [comment]
I've had the sticky scroll from the prior tab persist into a new tab indefinitely until I focus the editor body. I've been trying to reproduce it after seeing this issue but have been unable to, not sure what the conditions are.
