### ISSUE TITLE
Extension logging API options

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#162177]
Testing #161786

It would be great if we would have options to:
- Specify the time zone for the timestamp (local vs. UTC)
- Have the ability to omit the time segment from the log
- Have the ability to omit the extension name segment from the log

**Comment by sandy081** [comment]
These options can be provided/passed while creating the output channel. Is it what you are asking for?

**Comment by lszomoru** [comment]
Yes. I have not seen such options in the current proposal.

**Comment by sandy081** [comment]
After discussing with @lszomoru we came to a conclusion that this is no longer needed.
