### ISSUE TITLE
"Continue on" from Codespace in web should allow me to continue locally

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162118]
Testing #161875

I am missing these entries:
* a way to continue working on the codespace locally by connecting to the Codespace from desktop
* a way to clone the codespace locally and apply the changes

**Comment by joyceerhl** [comment]
@lszomoru for this transition:

> a way to clone the codespace locally and apply the changes

Does it make sense to have the git extension contribute a `Continue Working in Local Clone` option in the remote indicator and command palette when there is at least one git repository open in a remote window on either the web or desktop client? I can send the PR for this change.

**Comment by joyceerhl** [comment]
With tomorrow's insiders you will be able to continue working on a git repo from a codespace to a local clone (fyi @minsa110):

https://user-images.githubusercontent.com/30305945/211971275-3f22c603-bfb3-4ccd-a6c5-b1d7a728d7e2.mp4

**Comment by joyceerhl** [comment]
From the remote indicator and the home menu we already have the ability to reopen a browser codespace in desktop:

![image](https://user-images.githubusercontent.com/30305945/212407308-8d73321d-2420-4871-9821-39af5e579c40.png)
 
![image](https://user-images.githubusercontent.com/30305945/212407239-9daaf5a5-127f-48b5-acc4-c14d0c91ecfa.png)


We now have the ability to clone from any remote window into a local desktop git repo, thus closing as completed.
