### ISSUE TITLE
Container/View Not Displaying in VSCode Activity Bar/Side Bar

### ISSUE THREAD

**Issue by david-pa** [microsoft/vscode#162142]
I am trying to add a custom Container and View to the Activity Bar that features a tree view.
So far, I have done the following:

1. Added a "contributes", "viewsContainers" and "views" section to `package.json`
```
...
"contributes": {
    "viewsContainers": {
			"activitybar": [
				{
					"id": "new-explorer",
					"title": "New Explorer",
					"icon": "media/dep.svg"
				}
			]
		},
    "views": {
			"new-explorer": [
				{
					"id": "newExplorer",
					"name": "New Data",
					"icon": "media/dep.svg",
					"contextualTitle": "New  Explorer"
				}
			]
    }
...
```
2. Created a TreeDataProvider in a new file and imported it into `extension.ts`.
```
export class DataNodeProvider implements vscode.TreeDataProvider<Data> {
  private _onDidChangeTreeData: vscode.EventEmitter<Data | undefined | void> = new vscode.EventEmitter<Data | undefined | void>();
  readonly onDidChangeTreeData: vscode.Event<Data | undefined | void> = this._onDidChangeTreeData.event;

  refresh(): void {
    this._onDidChangeTreeData.fire();
  }

  getTreeItem(element: Module): vscode.TreeItem {
    return element;
  }

  getChildren(): Thenable<Data[]> {
    const data = [];
    const dataEntry= new Data('test-data', '1.0.0', vscode.TreeItemCollapsibleState.None);
    data.push(dataEntry);
    return Promise.resolve(data);
  }
}

export class Data extends vscode.TreeItem {
  constructor(
    public readonly label: string,
    private readonly version: string,
    public readonly collapsibleState: vscode.TreeItemCollapsibleState,
    public readonly command?: vscode.Command
  ) {
    super(label, collapsibleState);

    this.tooltip = `${this.label}-${this.version}`;
    this.description = this.version;
  }

  iconPath = {
    light: path.join(__filename, '..', '..', 'resources', 'light', 'dependency.svg'),
    dark: path.join(__filename, '..', '..', 'resources', 'dark', 'dependency.svg')
  };

  contextValue = 'module';
}
```
3. Initialized the TreeDataProvider for the appropriate view ID in the `activate()` function of `extension.ts`.
```
export function activate(context: vscode.ExtensionContext) {
	const dataProvider = new DataNodeProvider();
	vscode.window.registerTreeDataProvider('newExplorer', dataProvider);
        ...
}
```

I've tested out a similar setup tinkering around with a copy of the [sample code provided](https://github.com/microsoft/vscode-extension-samples/tree/main/tree-view-sample) for this and found that the new container and view showed up with no issues. Most of this code is directly from the example code, so that makes sense. However, upon trying to add this to an existing LSP project's client files, I did not have the same result.

I got an error back in response that stated the ID assigned to the view when registering the TreeDataProvider in `extension.ts` (see step 3 above) did not exist. It's a bit odd considering the same setup worked just fine when applied to the sample code. Is there any reason that `package.json` changes wouldn't be reflected? Does anything different/additional need to occur to add a Container/View to an existing LSP project?

**Comment by alexr00** [comment]
> I got an error back in response that stated the ID assigned to the view when registering the TreeDataProvider in extension.ts (see step 3 above) did not exist.

Can you share the exact error?

**Comment by david-pa** [comment]
> > I got an error back in response that stated the ID assigned to the view when registering the TreeDataProvider in extension.ts (see step 3 above) did not exist.
> 
> Can you share the exact error?

No view is registered with id: newExplorer

**Comment by david-pa** [comment]
@alexr00 Actually if you look at the `package.json` and the code, the ID of the view in question is `newExplorer`. That view is then used to register the TreeDataProvider:

> vscode.window.registerTreeDataProvider('newExplorer', dataProvider);

The issue is that it is saying a view with the ID `newExplorer` does not exist.

**Comment by david-pa** [comment]
@alexr00 I still need help with this issue if possible.

**Comment by alexr00** [comment]
I think the problem you're having is that you don't register your view as an activation event, so your extension's activate isn't getting called when the view is made visible. Example: https://github.com/microsoft/vscode-extension-samples/blob/b296149e66db76f9a2f63c1d0828a3e3d365c260/tree-view-sample/package.json#L20-L21

**Comment by david-pa** [comment]
@alexr00 I do have the following section just above the `contributes` portion of my `package.js`, actually. I must've forgotten to include it.

```
"activationEvents": [
    "onView:newExplorer"
  ],
  "main": "./out/extension.js",
  "contributes": {
```

**Comment by david-pa** [comment]
@alexr00 I have resolved the issue, I believe. The issue is LSP configuration-specific. Rather than placing the contributes portion of the `package.json` in the Client, it had to go in the `package.json` that resides in the root project folder.
