### ISSUE TITLE
Sticky Scroll in Normal Visual Studio 2022 (not VSCode)

### ISSUE THREAD

**Issue by d4kir92** [microsoft/vscode#162131]
Sticky Scroll in Normal Visual Studio 2022 (not VSCode)

**Comment by gjsjohnmurray** [comment]
What is being asked for here?

**Comment by aiday-mar** [comment]
I think they want to have the same feature in Visual Studio. However I suppose this request should be filed on the side of Visual Studio. You may follow the following guideline to do so: https://learn.microsoft.com/en-us/visualstudio/ide/how-to-report-a-problem-with-visual-studio?view=vs-2022.

**Comment by d4kir92** [comment]
VSCode has a new feature called: Sticky Scroll
but Visual Studio 2022 (not VSCode) dont have that
