### ISSUE TITLE
When I run 'git fetch" command, I can't see whether it is complete or not.

### ISSUE THREAD

**Issue by DFVSQY** [microsoft/vscode#162179]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2 (system setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

When i run `Git: Fetch` command, i don't know whether it is complete or not. There is no circle loading animation.

![image](https://user-images.githubusercontent.com/8075421/192790324-ae4f1655-d3d4-48c9-8435-4c07faad3e6c.png)

**Comment by lszomoru** [comment]
It looks like, it was [an explicit decision](https://github.com/microsoft/vscode/issues/24170) not do show progress while the `Fetch` operation is being executed. Thinking about it, I do think that if one has auto-fetch enabled it might be quite distracting to show progress every time the fetch operation is being run as part of auto-fetch. Having said that, I do think that it makes sense to show progress when `Fetch` is being executed explicitly. @joaomoreno, thoughts?

**Comment by joaomoreno** [comment]
@lszomoru Agree.

**Comment by DFVSQY** [comment]
> It looks like, it was [an explicit decision](https://github.com/microsoft/vscode/issues/24170) not do show progress while the `Fetch` operation is being executed. Thinking about it, I do think that if one has auto-fetch enabled it might be quite distracting to show progress every time the fetch operation is being run as part of auto-fetch. Having said that, I do think that it makes sense to show progress when `Fetch` is being executed explicitly. @joaomoreno, thoughts?

Consider adding an option to decide whether to turn on the feature?

**Comment by lszomoru** [comment]
@DFVSQY, this progress indicator during a manual fetch would honour the `git.showProgress` setting.

**Comment by DFVSQY** [comment]
> @DFVSQY, this progress indicator during a manual fetch would honour the `git.showProgress` setting.

Thank you, hope see the feature soon.
