### ISSUE TITLE
"add cursor below " not working on linux

### ISSUE THREAD

**Issue by pluveto** [microsoft/vscode#162197]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
1.71.2
74b1f979648cc44d385a2286793c226e611f59e7
x6
- OS Version:
- Manjaro Linux x86_64, Kernel: 5.15.65-1-MANJARO

Steps to Reproduce:

1. set "Control+Alt+DownArrow" as short cut 
```
{
  "key": "ctrl+alt+down",
  "command": "editor.action.insertCursorBelow",
  "when": "editorTextFocus"
}
```
2. press  "ctrl+alt+down"

expect add cursor below. but not working, ctrl+alt is activating menu bar

**Comment by pluveto** [comment]
![image](https://user-images.githubusercontent.com/50045289/192804303-d6364ffb-d74c-4e77-9b53-b7c6178ee1a3.png)

See this after press  ctrl+alt , lose focus

**Comment by alexdima** [comment]
Let's first try to find out what command executes on your machine, with your settings and your keybindings when pressing `ctrl+alt+down`. Could you please [try the following](https://github.com/microsoft/vscode/wiki/Keybinding-Issues#basic-troubleshooting):

* Run the command `Developer: Toggle Keyboard Shortcuts Troubleshooting`
* This will activate logging of dispatched keyboard shortcuts and will open an output panel with the corresponding log file.
* Press exactly the keybinding you desire.
* check what VS Code detects and what command is invoked.

If you are having trouble understanding the output, please feel free to paste here and I can try to help.

**Comment by pluveto** [comment]
I press ctrl, alt, t one after another, and release them all at once. log output:
```
[2022-09-30 00:04:22.724] [renderer10] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 17, key: Control
[2022-09-30 00:04:22.758] [renderer10] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl], code: ControlLeft, keyCode: 5 ('Ctrl')
[2022-09-30 00:04:22.758] [renderer10] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
[2022-09-30 00:04:24.535] [renderer10] [info] [KeybindingService]: / Received  keydown event - modifiers: [ctrl,alt], code: AltLeft, keyCode: 18, key: Alt
[2022-09-30 00:04:24.535] [renderer10] [info] [KeybindingService]: | Converted keydown event - modifiers: [ctrl,alt], code: AltLeft, keyCode: 6 ('Alt')
[2022-09-30 00:04:24.535] [renderer10] [info] [KeybindingService]: \ Keyboard event cannot be dispatched in keydown phase.
```

seems `down` key not fired

**Comment by pluveto** [comment]
This is my binding:
![image](https://user-images.githubusercontent.com/50045289/193082372-d3a8ccb5-0152-40d5-92f2-90db84408fc3.png)
Same issue when `Developer: Reload With Extensions Disabled`

**Comment by alexdima** [comment]
@pluveto Thank you for the extra information. From your log, it looks like VS Code is not receiving the keypress from OS. There is nothing we can do on our side if the OS doesn't dispatch the keypress. Are you able to use `ctrl+alt+down` in other applications on this machine?

**Comment by pluveto** [comment]
```
██████████████████  ████████   pluveto@pcportable 
██████████████████  ████████   ------------------ 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: B450M DS3H 
████████            ████████   Kernel: 5.15.65-1-MANJARO 
████████  ████████  ████████   Uptime: 2 days, 3 hours, 11 mins 
████████  ████████  ████████   Packages: 1204 (pacman) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 2560x1080 
████████  ████████  ████████   DE: GNOME 42.4 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Flat-Remix-Violet-Dark-fullPanel 
████████  ████████  ████████
████████  ████████  ████████   Theme: Adw-dark [GTK2/3] 
                               Icons: Papirus-Dark [GTK2/3] 
                               Terminal: yakuake 
                               CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
                               GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate 
                               Memory: 9141MiB / 40036MiB 

```

I found `ctrl+alt+n` is not working in vscode, but works in https://vscode.dev/

final solution is 

```
 gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "['']"
 gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "['']"
 gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "['']"
 gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "['']"
```
