### ISSUE TITLE
Update Config giving error unknown key

### ISSUE THREAD

**Issue by shanalikhan** [Microsoft/vscode#16216]
Im try to use API in order to CREATE settings in user settings.json file by the following way.

```

const config = vscode.workspace.getConfiguration('sync');
let keys = Object.keys(syncSetting);
            keys.forEach(async keyName => {

                if (syncSetting[keyName] != null) {
                    console.log(keyName.toLowerCase() + ":" + syncSetting[keyName]);
                    allKeysUpdated.push(config.update(keyName.toLowerCase(),JSON.stringify(syncSetting[keyName]), true));
                    
                }
            });

  Promise.all(allKeysUpdated).then(async function (a) {
                await StartDownload();
            }, async function (b: any) {
                console.log(b);
                await StartDownload();
            })
```

Im getting error as ***"Unable to write to the configuration file (Unknown Key)"***

I have checked this issue and can be resolved in this link https://github.com/Microsoft/vscode/issues/13071 , but im trying to code in that way but still facing the same problem.

**Comment by bpasero** [comment]
@shanalikhan can you provide a self contained stand alone extension that demonstrates the problem please

**Comment by shanalikhan** [comment]
i have committed the rough code to perform such action in my extension branch at
https://github.com/shanalikhan/code-settings-sync/commit/9c5fee1c3c7513d60e2254bb36f2ba8047aafc96#diff-45327f86d4438556066de133327f4ca2R305
so you can view all the code

**Comment by bpasero** [comment]
@shanalikhan your extension is not declaring the configuration keys as outlined in https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration

The configuration editing API only allows to write values that are listed in the `package.json`. In general we strongly advise to declare configuration so that users can find the configuration easily when looking at the default settings.

**Comment by shanalikhan** [comment]
ok thanks, but it would be better if exception should give relative error message to write in package.json rather than uknown key so extension writers can better understand this.
