### ISSUE TITLE
Headers don't validate across files on Windows

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162129]
Testing #149979

1. Make a link to a file that exists, but to a header that does not, e.g. `[other](/other.md#no-such-title)`
2. Note that there is no problem reported

**Comment by mjbvz** [comment]
This is likely a bug with how configuration is syncrhinized. Try setting `"markdown.validate.fileLinks.markdownFragmentLinks": "warning"`

I'll fix the config issue as well. By default, this setting should inherit from `markdown.validate.fragmentLinks.enabled`
