### ISSUE TITLE
Merge editor shows conflicting lines and code lens together overlapping

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#162190]
Testing #161833

- Create merge conflicts
- Open the conflicts file
- Open the merge editor 
- Close the conflicts file and do not save

![image](https://user-images.githubusercontent.com/10746682/192801037-a710630f-cb09-4d2c-b80c-e253cf90a3c5.png)

**Comment by hediet** [comment]
> Close the conflicts file and do not save

This will restore the result file and re-introduce the conflict markers.

I'd say for now this is an unsupported scenarion, thus moving it to October.

**Comment by hediet** [comment]
I removed the conflict marker view zone, thus this should not happen anymore.
