### ISSUE TITLE
Add support for printing variables from the debugger sidebar

### ISSUE THREAD

**Issue by orta** [Microsoft/vscode#16210]
- VSCode Version: 1.7.x
- OS Version: macOS

Steps to Reproduce:

1. Hit a breakpoint
2. Right click on a variable

![screen shot 2016-11-29 at 10 33 25](https://cloud.githubusercontent.com/assets/49038/20706492/834c9a5a-b61f-11e6-8a12-08e0215915d4.png)

Ideally I'd like to be able to right-click on a variable to print it down in the console. For long strings I would need to go and write it in the console to see the full value.

**Comment by isidorn** [comment]
Currently you can just Copy Value and then paste that in the debug console as a workaround.
Let's see if more users ask for this and we can consider introducing it.

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.
