### ISSUE TITLE
Merge editor: show base at top x2?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162111]
This looks and reads a bit weird to me:

<img width="262" alt="image" src="https://user-images.githubusercontent.com/900690/192690468-7f707256-eec1-450e-b292-dc7714a315c4.png">

This does not really do anything when I am in Column Layout which I think is even the default.

**Comment by bpasero** [comment]
I think `precondition` or the `when` clause of the command, I always forget:

https://github.com/microsoft/vscode/blob/044571548e0268d0e4f09300a05887e4495b84a8/src/vs/platform/action/common/action.ts#L41

@jrieken knows for sure

**Comment by hediet** [comment]
precondition just disables that entry, it doesn't hide it

**Comment by bpasero** [comment]
@hediet try with:

https://github.com/microsoft/vscode/blob/044571548e0268d0e4f09300a05887e4495b84a8/src/vs/platform/actions/common/actions.ts#L22

**Comment by jrieken** [comment]
It is the `when` clause that defines if an item appears in the menu

**Comment by jrieken** [comment]
In addition to hiding this when it doesn't apply: can we find a better solution for when it applies. Can we have

for column mode

✔️ Show Base

for mixed mode (radio-logic for these two)

✔️ Show Base At Top
🔲  Show Base In Middle

**Comment by hediet** [comment]
Fixed
<img width="167" alt="image" src="https://user-images.githubusercontent.com/2931520/192754063-675fe6ac-ca5a-4c2a-9dad-b61fc9fe5d5a.png">

**Comment by bpasero** [comment]
I still find this weird:

<img width="198" alt="image" src="https://user-images.githubusercontent.com/900690/192756821-9d244132-707e-4b72-9521-d0e12d5744f8.png">

Throwing in some ideas:

**Column Layout**
I would think just a toggle for the base is fine so that it becomes a single entry.

**Mixed Layout**
A radio group of 3 entries: "Hide Base", "Show Base Top", "Show Base Center". Alternatively if we worry about too many entries, we could also do a submenu for "Base" specifically with these options.

**Comment by hediet** [comment]
Verification steps:

Open a merge conflict and verify these menu entries:

![image](https://user-images.githubusercontent.com/2931520/195119847-51879739-42c4-41c4-85c1-82b932cf609d.png)

![image](https://user-images.githubusercontent.com/2931520/195123319-9bf74ba0-d7fe-4628-9161-fa04d2dac8ce.png)
