### ISSUE TITLE
Error while fetchig extensions. server retutned 500

### ISSUE THREAD

**Issue by StepanKomis** [microsoft/vscode#162176]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2
- OS Version: Arch linux

Steps to Reproduce:

I just installed vscode via package manager "pacman", it started without any issues but when i serch for extensions it give me this error: "Error while fetchig extensions. server retutned 500"
I couldn't find any solution to this.
Thanks

**Comment by sandy081** [comment]
Can you please share following logs?

- F1 > Toggle Developer Tools > Console
- F1 > Toggle Developer Tools > Network

**Comment by r9pereira** [comment]
Hi, I have the same issue. Here are the logs from my side:

<details>
   <summary>Console log</summary>
<pre>
request.ts:46          POST https://open-vsx.org/vscode/gallery/extensionquery 500
(anonymous) @ request.ts:46
R @ request.ts:24
request @ requestService.ts:35
queryRawGalleryExtensions @ extensionGalleryService.ts:945
await in queryRawGalleryExtensions (async)
queryGalleryExtensions @ extensionGalleryService.ts:815
le @ extensionGalleryService.ts:771
query @ extensionGalleryService.ts:775
queryGallery @ extensionsWorkbenchService.ts:878
await in queryGallery (async)
queryGallery @ extensionsViews.ts:702
await in queryGallery (async)
query @ extensionsViews.ts:331
(anonymous) @ extensionsViews.ts:249
w @ async.ts:25
show @ extensionsViews.ts:247
show @ extensionsViews.ts:1216
(anonymous) @ extensionsViewlet.ts:668
doSearch @ extensionsViewlet.ts:667
(anonymous) @ extensionsViewlet.ts:625
(anonymous) @ async.ts:333
Promise.then (async)
trigger @ async.ts:327
triggerSearch @ extensionsViewlet.ts:625
(anonymous) @ extensionsViewlet.ts:542
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
(anonymous) @ suggestEnabledInput.ts:197
(anonymous) @ textModel.ts:236
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
endDeferredEmit @ textModel.ts:2416
pushEditOperations @ textModel.ts:1251
_innerExecuteCommands @ cursor.ts:790
executeCommands @ cursor.ts:748
_executeEditOperation @ cursor.ts:354
(anonymous) @ cursor.ts:559
_executeEdit @ cursor.ts:514
type @ cursor.ts:548
(anonymous) @ viewModelImpl.ts:1025
_withViewEventsCollector @ viewModelImpl.ts:1074
_executeCursorEdit @ viewModelImpl.ts:1013
type @ viewModelImpl.ts:1025
_type @ codeEditorWidget.ts:1168
type @ codeEditorWidget.ts:1748
type @ viewController.ts:71
(anonymous) @ textAreaHandler.ts:319
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
(anonymous) @ textAreaInput.ts:371
invoke @ event.ts:622
deliver @ event.ts:824
fire @ event.ts:785
I @ event.ts:37
Show 23 more frames
log.ts:313   ERR Error: Server returned 500
    at C (request.ts:49:9)
    at G.queryRawGalleryExtensions (extensionGalleryService.ts:956:25)
    at async G.queryGalleryExtensions (extensionGalleryService.ts:815:62)
    at async le (extensionGalleryService.ts:771:34)
    at async G.query (extensionGalleryService.ts:775:33)
    at async _o.queryGallery (extensionsWorkbenchService.ts:878:18)
    at async Ce.queryGallery (extensionsViews.ts:702:17)
    at async Ce.query (extensionsViews.ts:331:17)
    at async extensionsViews.ts:249:24
</pre>
</details>
<details>
   <summary>Network request 1</summary>
   <pre>

Request:
POST /vscode/gallery/extensionquery HTTP/1.1
Accept: application/json;api-version=3.0-preview.1
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-PT
Connection: keep-alive
Content-Length: 229
Content-Type: application/json
Host: open-vsx.org
Origin: vscode-file://vscode-app
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) code-oss/1.71.2 Chrome/102.0.5005.167 Electron/19.0.13 Safari/537.36
X-Market-Client-Id: VSCode 1.71.2
sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="102"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"

Response:
{"timestamp":"2022-09-29T13:34:09.250+00:00","status":500,"error":"Internal Server Error","message":"","path":"/vscode/gallery/extensionquery"}

HTTP/1.1 500
Server: nginx
Date: Thu, 29 Sep 2022 13:34:10 GMT
Content-Type: application/json; api-version=3.0-preview.1
Transfer-Encoding: chunked
Connection: keep-alive
vary: accept-encoding,origin,access-control-request-headers,access-control-request-method,accept-encoding
x-frame-options: DENY
strict-transport-security: max-age=31536000 ; includeSubDomains
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
content-encoding: gzip
Access-control-allow-origin: vscode-file://vscode-app

   </pre>
</details>
<details>
   <summary>Network request 2</summary>
<pre>
Request:
OPTIONS /vscode/gallery/extensionquery HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-PT
Access-Control-Request-Headers: content-type,x-market-client-id
Access-Control-Request-Method: POST
Connection: keep-alive
Host: open-vsx.org
Origin: vscode-file://vscode-app
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) code-oss/1.71.2 Chrome/102.0.5005.167 Electron/19.0.13 Safari/537.36

Response:
HTTP/1.1 204 No Content
Server: nginx
Date: Thu, 29 Sep 2022 13:34:10 GMT
Connection: keep-alive
Content-Length: 0
Vary: Origin
Vary: Access-Control-Request-Method
Vary: Access-Control-Request-Headers
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: content-type,x-market-client-id,x-market-user-id,x-client-commit,x-client-name,x-client-version,x-machine-id,vscode-sessionid
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: OPTIONS,GET,POST,PATCH,PUT,DELETE
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
strict-transport-security: max-age=31536000 ; includeSubDomains
x-frame-options: DENY
</pre>
</details>

**Comment by sandy081** [comment]
We do not own this `https://open-vsx.org` service. Please file an issue against the source from where you downloaded the application
