### ISSUE TITLE
Code folding gets confused when code isn't properly indented

### ISSUE THREAD

**Issue by warpdesign** [Microsoft/vscode#16220]
- VSCode Version: Code - Insiders 1.8.0-insider (4721762a2ac1e21f1e33094e810d4888052f3d8d, 2016-11-29T07:09:36.481Z)
- OS Version: Windows_NT ia32 10.0.14971
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|theme-dracula|dracula-theme|1.2.5|
|eval|Stormspirit|0.0.5|

---

Steps to Reproduce:

1. Type a JavaScript function and put misaligned code in the middle of the function
2. Click on the `+` to fold the function

What happens ?
Code only hides the code up to the mis-aligned comment: what's next isn't hidden although it's part of the function and should be hidden.

See:
![cold-folding](https://cloud.githubusercontent.com/assets/199648/20714326/f4ae74bc-b64b-11e6-96c6-cd7c57d5ae90.gif)

**Comment by alexandrudima** [comment]
I believe this is by design of how code folding is implemented in a language agnostic manner.

**Comment by warpdesign** [comment]
@alexandrudima I see. What could be done about that ?

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand functions, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
