### ISSUE TITLE
Context menu `Refactor...` works, but given keyboard shortcut fails

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#162236]
found while verifying https://github.com/microsoft/vscode/issues/157129

Perhaps the issue is that the shortcut shouldn't be displayed here

Repro steps:
1. Add this keyboard shortcut:

```
{
        "key": "ctrl+shift+e",
        "command": "editor.action.refactor",
        "args": {
            "kind": "refactor.extract",
            "preferred": true,
            "apply": "ifSingle"
        }
    },
```

2. Open a python file and select a line of code and right click on it

:bug: the keyboard shortcut is shown for `Refactor...`, clicking the item works, but the keyboard shortcut doesn't

The error on the right is the result of using the hotkey

![image](https://user-images.githubusercontent.com/2019016/192854184-4a38fa2b-d790-4eb8-a2b5-ee36faac032e.png)

**Comment by mjbvz** [comment]
This is expect for the example keybinding. The keybinding finds all `preferred` code actions of kind `refactor.extract`. If only one exists (`ifSingle`) then the action is automatically applied. Otherwise a list of all code actions are shown
