### ISSUE TITLE
Parameter Hints shown inline all the time (like IntelliJ)

### ISSUE THREAD

**Issue by nbransby** [microsoft/vscode#16221]
Would be useful for typescript: https://youtu.be/ZfYOddEmaRw

**Comment by mrmlnc** [comment]
Just a tip:

VS Code have Hover and SignatureHelp tips:

## Hover

![image](https://cloud.githubusercontent.com/assets/7034281/20714642/b0710c80-b65d-11e6-91de-74aa6704e353.png)

## SignatureHelp

![image](https://cloud.githubusercontent.com/assets/7034281/20714659/bda15c5c-b65d-11e6-9ab1-efd62858b693.png)

**Comment by waderyan** [comment]
@nbransby thanks for opening this up. I watched the video... what specifically are you missing? VS Code does provide parameter hints as @mrmlnc shows in his screenshots.

**Comment by nbransby** [comment]
inline parameters hints aka the args names prefixed on each value passed into a function invocation swift / objective c style. I think its a great idea to bring this to other languages, and its a perfect feature for an ide to take care of instead of actually introducing it to the language.

**Comment by waderyan** [comment]
@nbransby can you show me a screenshot? This is what we do today and I'm not seeing how what you are suggesting (args names prefixed on each value passed into a function invocation) is different:

![image](https://cloud.githubusercontent.com/assets/2449568/20844978/7235cb42-b877-11e6-9543-04d875445676.png)

**Comment by nbransby** [comment]
Difference is that its inline in the editor and present at all times - not in a popup
![image](https://cloud.githubusercontent.com/assets/1386607/20845623/e2bcb2c2-b8bd-11e6-9c20-e211b6a653fc.png)

**Comment by waderyan** [comment]
Ok interesting. Thank you for clarifying.

**Comment by balta2ar** [comment]
For the record, here is child issue in vscode-python that I think depends on this one: https://github.com/Microsoft/vscode-python/issues/53

**Comment by phiresky** [comment]
Note that this is already possible using decorations:

![image](https://user-images.githubusercontent.com/2303841/35807174-43bc0c3c-0a82-11e8-8c99-591fb650e1e0.png)

Adapting [this sample](https://github.com/Microsoft/vscode-extension-samples/tree/master/decorator-sample):

```ts
vscode.window.createTextEditorDecorationType({
        before: {
            contentText: "myParam:",
			border: "1px solid gray",
			backgroundColor: "#333",
			margin: "1px",
			textDecoration: "test",
        }
    });
```

I'm not sure how to get information from the running typescript language server though...

**Comment by phiresky** [comment]
> I'm not sure how to get information from the running typescript language server though...

Looks like this is not possible. Other plugins that manipulate typescript either use regexes ([typescript importer](https://github.com/pmneo/ts-importer/blob/master/src/Importer.ts#L28)), a separate Typescript parser ([Typescript Hero](https://github.com/buehler/typescript-hero/blob/develop/src/import-organizer/import-manager.ts#L14)) or load the files into the typescript compiler themselves ([Move TS](https://github.com/stringham/move-ts/blob/master/src/index/referenceindexer.ts#L451)). None of these methods really seem viable for this problem...

**Comment by shiMusa** [comment]
Please make this a simple to install extension!
<3 <3 <3
:3

**Comment by lannonbr** [comment]
So I've wanted this feature in VS Code as well and I ended up making it myself. I currently support JS files at the moment but am interested in adding support for other languages in the future.

Here's the extension: https://marketplace.visualstudio.com/items?itemName=lannonbr.vscode-js-annotations

**Comment by krulik** [comment]
Looking for such an extension for Golang

**Comment by DJMcNab** [comment]
This feature looks really useful - has it been considered for [the language server protocol](https://github.com/Microsoft/language-server-protocol)?

Using @phiresky's example, this could be done through the semantic highlighting api - see Microsoft/language-server-protocol#18, Microsoft/language-server-protocol#513, etc. for the proposals.

However, in my opinion `contentText` is an implementation oddity, and the protocol should not require all editors to support that part of the diagnostics api. Indeed, Microsoft/language-server-protocol#513 would not support this as it uses textmate scopes. Therefore, it should probably be a seperate feature similar in use to `textDocument/publishDiagnostics`.

CC. @dbaeumer, who appears to manage the language-server-protocol repo. A tracking/discussion issue there would probably be useful too, with your blessing.

As a further note https://github.com/rust-lang/rfcs/issues/323#issuecomment-391735876 discusses a further use for this to supercede keyword args in Rust.

**Comment by vbasky** [comment]
Is there any plan to support this feature in VSCode any time soon ?

**Comment by Sioxas** [comment]
Looking for such an extension for Java

**Comment by brunolemos** [comment]
[WebStorm 2018.3](https://www.jetbrains.com/webstorm/whatsnew/) just added this for javascript files:

![autoimports-in-javascript-816 2x](https://user-images.githubusercontent.com/619186/48727332-15454980-ec19-11e8-995b-9cb3b478c3be.gif)


We'd love to get this on vscode as well, especially for typescript.

**Comment by lannonbr** [comment]
@brunolemos If you scroll up a little in this thread, I made a VS Code extension that currently does this for JS / TS.

**Comment by ColCh** [comment]
@lannonbr that extension not works with TS files, right?

![image](https://user-images.githubusercontent.com/599439/48731661-9834c700-ec4e-11e8-949e-9b9d984c4dae.png)

**Comment by brunolemos** [comment]
@lannonbr thanks! It's a great alternative for now, unfortunately there's some pain points that would be great to be addressed:

- It has a delay between opening the file and the extension adding the annotations, which hurts ux
- It doesn't seem to work with `JavaScript React` neither `TypeScript React` files
- Add a more freely customization option to the styling, e.g. I'd like to add an opacity to it and maybe make the font smaller, or tweak the color, whatever.

**Comment by sagebind** [comment]
It would be neat for something very similar, to add decorators for inferred types (which we already know from language servers). Again as an example, taken from IntelliJ:

![](https://www.jetbrains.com/idea/whatsnew/img/2018.2/JavaTypeHints.png)

This information we already have on hover, this is just a way to do the same thing using decorations.

**Comment by kjeremy** [comment]
Hover doesn't have to display the type, it's just encouraged to in the protocol spec so you would need a different mechanism. I'm wondering if we can use #66418 for this?

**Comment by goxr3plus** [comment]
What happened ? I am waiting for this in Java ? Is it implemented :) ?

**Comment by JsonPipe** [comment]
I am missing this feature so much. I really hope they will implement it.

**Comment by cipri-tom** [comment]
The main advantage of this feature is that it allows you to see the parameter hints without masking the code above it. Currently, the parameter hints make it difficult to look at the lines just above them:

![Screenshot 2019-03-12 at 16 22 21](https://user-images.githubusercontent.com/2991890/54212331-0d205b00-44e3-11e9-8016-37e104a77614.png)

(I actually wanted to draw inspiration from the commented line above)

**Comment by dulinux** [comment]
+1 This is a great feature from IntelliJ that should definitetly be ported to vscode.

**Comment by SaschaSchlemmer** [comment]
I would really like to have this for python!

**Comment by pittersnider** [comment]
+1 for JS

**Comment by markfinlabs** [comment]
Would greatly help with cases like this (from Typescript file) where you can't see what an individual parameter is by hover. (Real example with randomised content.)

```typescript
        const myVar = new this(
          id,
          'https://example.com:6010',
          'FeZJlIDPbvSxHaZ5DSDFJDSFJksksjfjhyralaklasda',
          false,
          '00YISYSYDYYYFY33423423',
          'https://example.com:6020',
          'https://example.com:6030',
          'https://example.com:6030',
          'xxxdc9f3',
          'sldfkjjjewrjioweurfiopjdkasl;kdl;asd'
        );
```

**Comment by Joker2000** [comment]
Jetbrains have a good post on the benefits of inline parameter hints. Would love to get it in VS Code!

https://www.jetbrains.com/help/resharper/Inline_Parameter_Name_Hints.html#why-use-parameter-name-hints

**Comment by blurymind** [comment]
yes please add this to vscode!

Also this https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-rename-tag
it should be a part of the ide, not an addon

**Comment by shijiezhou1** [comment]
> @lannonbr that extension not works with TS files, right?
> 
> ![image](https://user-images.githubusercontent.com/599439/48731661-9834c700-ec4e-11e8-949e-9b9d984c4dae.png)

It is works for ts if you donwload the latest and greatest

**Comment by markfinlabs** [comment]
Would be great if this could work well for **default parameters** as well as used parameters. For example, if a default parameter is used (due to parameter missing or specified as ```undefined```) it would be great to see both the parameter name _and_ value to be substituted in the hints. This would save a function definition lookup to understand the function call which is exactly the point of this feature.

**Comment by eljenso** [comment]
Just saw this feature in my coworkers WebStorm, now I want this feature in VSCode. :smiley:

**Comment by umutcnkus** [comment]
Add me to the waiting list. It looks really cool on Intellij.

**Comment by kwiat1990** [comment]
It would be a very helpful feature.

**Comment by marcuskwan** [comment]
I agree with the others!

**Comment by zapateo** [comment]
This would be really useful.

**Comment by DominicWatts** [comment]
phpstorm has it.  I saw this and wanted in Vscode :)

**Comment by CharlesT100** [comment]
@mjbvz Requesting this feature too - could we know the status, will it be implemented by the VS Code team?

**Comment by andrewrothman** [comment]
Would love to see this in VS Code.

**Comment by SomeoneToIgnore** [comment]
One extra thing to consider for the future implementation in VS Code is the fact that those hints may be interactive.
Here's an example from the intellij-rust plugin: https://github.com/intellij-rust/intellij-rust/pull/4217

**Comment by trungnguyen22** [comment]
How about in React Native ?

**Comment by dpanic** [comment]
any news on this?

**Comment by xianyuggg** [comment]
any news on this?

**Comment by sagebind** [comment]
> any news on this?

If there were, I am quite certain the vscode team would post an appropriate update to this thread.

**Comment by joe-inz** [comment]
2020 is approaching and this feature is not implemented yet !!
would be a great improvement :smiley:

**Comment by rajkundu** [comment]
**Please** add this! It would be such a useful feature and, at least in my use, IntelliJ would have nothing over VS Code. Please!!!

**Comment by sagebind** [comment]
OT, but @rajkundu I read your comment in my head using the Chamberlain's voice: https://www.youtube.com/watch?v=lm9E3NQOuh0. It fit.

**Comment by rajkundu** [comment]
Not terribly dissimilar 😆

**Comment by djmisterjon** [comment]
any new on this , i see my friend have this 
![image](https://user-images.githubusercontent.com/24865815/67388724-35873200-f567-11e9-8178-469a4e818764.png)
This is awesome, how activate this in vscode ??
Or a plugin ?

**Comment by selimrecep** [comment]
Up. It would be great feature.

**Comment by bzrncev** [comment]
I just switched to VS Code and was missing this feature, so I implemented it myself. Still in beta, but workable: https://marketplace.visualstudio.com/items?itemName=BobbyZrncev.intellij-parameter-hints

Thanks to @lannonbr for inspiration.

**Comment by TNThacker2015** [comment]
This feature would be extremely useful!

**Comment by tbillington** [comment]
For inspiration [rust-analyzer](https://github.com/rust-analyzer/rust-analyzer) is doing this in vscode today.

![Screen Shot 2020-01-05 at 2 32 39 pm](https://user-images.githubusercontent.com/2771466/71774757-54269200-2fc8-11ea-8505-ac2f326761ca.png)

**Comment by jonit-dev** [comment]
This feature would be great! Meanwhile, I'm using JS Parameter Annotations

**Comment by JeromeDeLeon** [comment]
This would be a really great feature. Please, hear us out. 🚀

**Comment by liangjiancang** [comment]
It has been 3 years!!!

**Comment by pittersnider** [comment]
This is very helpful and give us a large productivity scale.

**Comment by mjbvz** [comment]
We hear you... but these +1 comments are not productive. Locking to prevent more noise

Try https://marketplace.visualstudio.com/items?itemName=lannonbr.vscode-js-annotations in the meantime

**Comment by jonit-dev** [comment]
I'm using this one, pretty good too: 

Name: Parameter Hints
Id: dominicvonk.parameter-hints
Description: Automatic parameter hints
Version: 0.2.7
Publisher: Dominic Vonk
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DominicVonk.parameter-hints

**Comment by djmisterjon** [comment]
> I'm using this one, pretty good too:
> 
> Name: Parameter Hints
> Id: dominicvonk.parameter-hints
> Description: Automatic parameter hints
> Version: 0.2.7
> Publisher: Dominic Vonk
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DominicVonk.parameter-hints

wow, is the first one where i add and work the first time without config ! thanks for share  ! 
look very clean for me and my theme, seem no bug ! 
![image](https://user-images.githubusercontent.com/24865815/118047923-790fdf80-b349-11eb-886b-ba7b173bddec.png)

**Comment by mjbvz** [comment]
Parameter name hints are now supported with TypeScript 4.4:

<img width="1384" alt="Screen Shot 2021-07-13 at 7 18 03 PM" src="https://user-images.githubusercontent.com/12821956/125550249-7c3e5232-6052-45c6-99ea-9a3b2a27952a.png">

TypeScript 4.4 will be picked up in the August VS Code release. To test this feature in the current [VS Code insiders build](https://code.visualstudio.com/insiders/):

1. Either install the [typescript nightly extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) OR install typescript 4.4 locally and switch your workspace to use it
2. Enable parameter hints by setting `"typescript.inlayHints.parameterNames.enabled": "all"` or `"javascript.inlayHints.parameterNames.enabled": "all"`

❗ Please give this feature a try and open **new issues** for any problems / feature requests related to it ❗

---

But wait, there's more!!!

In addition to parameter names, you can also turn on hints for:

- Variable types (if implicit): `typescript.inlayHints.variableTypes.enabled`
- Property declaration types (if implicit): `typescript.inlayHints.propertyDeclarationTypes.enabled`
- Function return types (if implicit): `typescript.inlayHints.functionLikeReturnTypes.enabled`
- Parameter types (if implicit): `typescript.inlayHints.parameterTypes.enabled`
- Enum values: `typescript.inlayHints.enumMemberValues.enabled`

These are all disabled by default in both JS and TS. Here's a look at a JS file showing some of those additional hints  enabled:

<img width="1105" alt="Screen Shot 2021-07-13 at 7 31 55 PM" src="https://user-images.githubusercontent.com/12821956/125551548-c273e30d-8554-4af0-a12d-6bd581b5350a.png">

There are also two configurations you can use to control when parameter name hints are shown:

- With `"typescript.inlayHints.parameterNames.suppressWhenArgumentMatchesName": true`, hints are not shown if the passed in argument matches the parameter name:

     ```ts
    function foo(abc: number) { }

    const abc = 123;
    foo(abc) // no hint here since abc === abc
    ```

- With `"typescript.inlayHints.parameterNames.enabled": "literals"`, parameter name hints are only shown on literal types (string, number, function, object, ...)

**Comment by HighCommander4** [comment]
> Parameter name hints are now supported with TypeScript 4.4

Out of curiosity, how does this work at the LSP layer? My understanding is the [LSP protocol support](https://github.com/microsoft/vscode-languageserver-node/pull/772) hasn't been merged yet. Or does Typescript not use LSP?

**Comment by jestarray** [comment]
@mjbvz Can you link to how it is implemented for typescript? I'd like to do implement this for another language, thank you/

**Comment by yume-chan** [comment]
> Or does Typescript not use LSP?

Correct, because TypeScript language server was created before the invention of LSP, it doesn't use LSP. TypeScript team doesn't want to switch to LSP because it will either break old clients or require maintaining two protocols.

In fact, Code also doesn't have built-in support for LSP. Code team has an official npm package to bridge between LSP features and Code extension APIs, that extension authors must install it themselves to make LSP servers work with Code.

**Comment by silicakes** [comment]
> > Or does Typescript not use LSP?
> 
> Correct, because TypeScript language server was created before the invention of LSP, it doesn't use LSP. TypeScript team doesn't want to switch to LSP because it will either break old clients or require maintaining two protocols.
> 
> In fact, Code also doesn't have built-in support for LSP. Code team has an official npm package to bridge between LSP features and Code extension APIs, that extension authors must install it themselves to make LSP servers work with Code.

This is actually part of Typescripts official roadmap:
https://github.com/microsoft/TypeScript/issues/39459

**Comment by sschneider-ihre-pvs** [comment]
How can I customize the inlay tokens with `editor.tokenColorCusomizations` ? what scope is it?

**Comment by jrieken** [comment]
Keeping this open to finalize the API

**Comment by loilo** [comment]
> How can I customize the inlay tokens with `editor.tokenColorCusomizations` ? what scope is it?

@sschneider-ihre-pvs You cannot do this via `editor.tokenColorCustomizations`, but via `workbench.colorCustomizations`:

```
...

    "workbench.colorCustomizations": {
        "[My Theme]": {
            "editorInlayHint.foreground": "#FF0000",
            "editorInlayHint.background": "#FFFF00",
        }
    },

...
```

As documented here: https://code.visualstudio.com/api/references/theme-color

**Comment by sschneider-ihre-pvs** [comment]
I meant the inlay token font-style.

**Comment by gjsjohnmurray** [comment]
> 
> 
> I meant the inlay token font-style.

Look at the `editor.inlayHints.fontFamily` setting.

**Comment by sschneider-ihre-pvs** [comment]
I did that already but I can't pick an italic style that is the reason I was asking for font-style.

**Comment by trodix** [comment]
Can we have support for inline parameters hint for others languages like Java ?

**Comment by KamasamaK** [comment]
> Can we have support for inline parameters hint for others languages like Java ?

The API is not language-specific. The language extension authors will need to implement it when the API is finalized.

**Comment by TarunavBA** [comment]
When will this feature be available for python?

**Comment by proteriax** [comment]
Should be closed by [#42089](https://github.com/microsoft/TypeScript/pull/42089)?

**Comment by imShara** [comment]
How to activate it in `.vue` components?

**Comment by coder137** [comment]
Is there a way to activate this for the `C/C++` codebases?

**Comment by HighCommander4** [comment]
> Is there a way to activate this for the `C/C++` codebases?

With the [clangd](clangd.llvm.org/) langugage server, yes (see [this post](https://stackoverflow.com/a/69656325) for how to enable).

**Comment by coder137** [comment]
> > Is there a way to activate this for the `C/C++` codebases?
> 
> With the [clangd](clangd.llvm.org/) langugage server, yes (see [this post](https://stackoverflow.com/a/69656325) for how to enable).

Thanks this worked. Hopefully, there is an official VSCode supported C/C++ extension eventually as well

**Comment by jrieken** [comment]
The API has been finalised, the feature is implemented. All further work is tracked with the `inlay-hints` label: https://github.com/microsoft/vscode/labels/inlay-hints

**Comment by jrieken** [comment]
To verify ensure that [registerInlayHintsProvider](https://github.com/microsoft/vscode/blob/a330b89e5d83293bacee75ac910626b64ad8c3fd/src/vscode-dts/vscode.d.ts#L12176) is in latest `vscode.d.ts`
