### ISSUE TITLE
Automatic Type Acquisition not working

### ISSUE THREAD

**Issue by nwinger** [Microsoft/vscode#16229]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra 10.2.1

Steps to Reproduce:

1. Clone https://github.com/nwinger/ts-boilerplate.git
2. Open folder in VSCode
3. Navigate to ./src/index.tsx
4. import statements for react and react-dom underlined with following message:
> [ts] Cannot find module 'react'
> [ts] Cannot find module 'react-dom'

**Comment by mrmlnc** [comment]
I'm not entirely sure, but ATA works only for JavaScript IntelliSense. For TypeScript you can use `npm i -D @types/NAME_OF_PACKAGE`.

**Comment by mjbvz** [comment]
@mrmlnc is correct. Automatic Typings Acquisition is mainly for JavaScript. For TypeScript, you are expected to manage the types yourself.

Just install `@types/react` and `@types/react-dom` as dev dependencies
