### ISSUE TITLE
merge affordance hides in multi-repo setup

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#162224]
* have a merge conflict
* have multiple repos open
* open a file with conflicts
* :bug: depending on which repo was refreshed last the blue button shows/hides

**Comment by jrieken** [comment]
This is because the `setContext` command runs in the scope of a single [`Repository`](https://github.com/microsoft/vscode/blob/42a198b98b279460e1c11310759c4fb34d6be2ab/extensions/git/src/repository.ts#L2107) and thereby competes with others. 

@joaomoreno @lszomoru I have copied an [existing](https://github.com/microsoft/vscode/blob/42a198b98b279460e1c11310759c4fb34d6be2ab/extensions/git/src/repository.ts#L2107) [pattern](https://github.com/microsoft/vscode/blob/42a198b98b279460e1c11310759c4fb34d6be2ab/extensions/git/src/repository.ts#L856) here and I am unsure where the good place to set context keys is

**Comment by andreamah** [comment]
Which blue button are you describing and how is it supposed to act?
