### ISSUE TITLE
Web: terminal renders blank if terminal panel got completely closed

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#162221]
In the Web/UI do the following:

- create a terminal with a pseudo tty
- write to that terminal
- close the terminal

Observe that the whole terminal panel disappears

- create another terminal with a pseudo tty
- Observe: that will recreate the terminal panel.
- write to that terminal

Observe that the terminal doesn't show the text

- create another terminal
- write to it

Observe: the terminal shows the output

- switch back to the terminal created before

Observe: you see the output.

I can provide steps how to reproduce with Python, but I need to merge PRs first and release new npm packages. Let me know if that would help.

**Comment by dbaeumer** [comment]
![cast](https://user-images.githubusercontent.com/1931590/192838944-559842e1-0e88-4f4d-80df-17191760e0fa.gif)

**Comment by Tyriar** [comment]
Closing as out of scope for now due to issue grooming, we can always prioritize in the future when we need it though.
