### ISSUE TITLE
Quickfix lightbulb appends to any existing command after applying

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162216]
Testing #161846

1. Do something that prompts a quick fix
2. Start typing a command, then realize there's a suggested fix for it
3. Accept the quickfix suggestion
4. Notice the last command is appended to whatever you had typed in step 2

Could be fixed by:

- Hiding the bulb if anything new is typed on the prompt
- Clearing the prompt when applying the fix
- Or just not appending the last command in the case something is already there

**Comment by Tyriar** [comment]
How about a combination of the suggestions:

- On user input, we _hide_ the quick fix lightbulb but still allow it to be triggered via keybinding
- When the lightbulb is hidden, we will run the same code to clear the command if needed as run recent command does (if we do this all the time you would see some ^C when we can't detect it)

**Comment by connor4312** [comment]
Sounds good to me 🙂

**Comment by meganrogge** [comment]
> On user input, we hide the quick fix lightbulb but still allow it to be triggered via keybinding

I don't think this aligns with the editor behavior and could be surprising if accidentally encountered

**Comment by meganrogge** [comment]
In the editor, the lightbulb hides on input and only reappears if there's still a suggestion. IMO, we should just remove the lightbulb on input

**Comment by Tyriar** [comment]
@meganrogge a very real scenario is the user starts typing and only after that realizes the convenient quick fix though, which is what @connor4312 ran into. Hiding it while still allowing to trigger quick fixes until command executed would cover this case for users that know the keybinding, no downside afaict.

**Comment by meganrogge** [comment]
users that know the keybinding I'd argue need less help 😄 so we should probably show the lightbulb until command execution

**Comment by Tyriar** [comment]
👍 as long as it's accessible is the main thing. Hard to say what feels better, I was thinking of it from a power user perspective; removing UI noise if it's unlikely to be used
