### ISSUE TITLE
Should we disallow an extension to create an output channel with same name?

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162261]
Testing #161786

1. In a single extension 
2. Create two output channels with the same name:

```ts
	const log = vscode.window.createOutputChannel('my custom channel', { log: true });
	const log2 = vscode.window.createOutputChannel('my custom channel', { log: true });
```

**Bug**
This results in two channels called `my custom channel` in the output UI

Should we disallow this? It feels confusing as a user and was was likely a mistake by the extension author

**Comment by sandy081** [comment]
IMO, it's a programming error and shall be fixed by the extension.
