### ISSUE TITLE
"Empty" preview in tooltip on Ctrl+hover for definitions with a zero-width range (files)

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#162227]
If I hover over a path in TypeScript and hold Ctrl, and empty line appears at the bottom of the tooltip where the preview would normally be (because presumably, the definition being used to support go-to-definition returns a range of line 0, col 0 to line 0 col 0):

https://user-images.githubusercontent.com/1078012/192850372-074b92b8-d696-4a15-aa22-1eff599f968f.mp4

In the case where there's no normal hover text, this can result in an "empty hover" instead, as seen here in Dart (top left of "example"):

![image](https://user-images.githubusercontent.com/1078012/192850645-07c20b7f-c989-442c-a81b-1427f38b9f63.png)

**Comment by jrieken** [comment]
@DanTup  Are you saying that you have a go-to-definition provider for that path but no hover provider (or no hover provider result) Please provide repo steps and a minimal code sample that allows to reproduce this.
