### ISSUE TITLE
Can't tell which extension created an output channel

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162260]
Testing #161786

1. In two separate extensions, create log output channels with the same name
1. Open output view

**Bug**
The UI does not make it clear which output channel belongs to each extension:

![Screen Shot 2022-09-28 at 2 05 23 PM](https://user-images.githubusercontent.com/12821956/192888758-7fefc800-7b15-42ed-87c4-d294a4f5c096.png)

**Comment by sandy081** [comment]
This is same with normal output channels and this is only a theoretical problem than in real time.
