### ISSUE TITLE
Use .yaml files as default for launch and settings files

### ISSUE THREAD

**Issue by asherlporetz** [microsoft/vscode#162229]
Support use of .yaml files as default for launch, tasks and settings files. This will make them more readable and need less escaping especially for command line arguments. Yaml anchors and reference can also be optionally used by users to DRY their launch files. Note that any json content is a valid yaml content, so existing .json files need not be changed if a user opts to keep using them. Official vscode documentations that use json files as examples need not be updated, only an additional entry that yaml can also be used will suffice.

**Comment by roblourens** [comment]
This has come up multiple times in the past. Example, https://github.com/microsoft/vscode/issues/90242. We don't plan to do this
