### ISSUE TITLE
Output channel lock and unlock icons seem swapped

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162263]
Testing #161786

1. In an extension:
```ts
const log = vscode.window.createOutputChannel('my custom channel', { log: true });

setInterval(() => {
	log.error(new Error('x'));
}, 1000);
```

2. Open the output channel view and view the output

**bug**
To me, it seems like the lock icon for turning on/off auto scroll is mixed up:
![Screen Shot 2022-09-28 at 2 13 00 PM](https://user-images.githubusercontent.com/12821956/192890429-4d9d60f2-c771-40df-bc04-c04c80524f75.png)

Right now:

- unlocked: auto scroll is on
- locked: auto scroll is off

I believe the icons should be the reverse:

- Lock: Auto scroll is on
- Unlock: Auto scroll is off

**Comment by sandy081** [comment]
TBH I really not sure what is the right representation and it seems it worked this way until now and have not seen any feedback. I do not know if changing this might confuse the users now?

**Comment by bpasero** [comment]
Isnt the idea that the icon represents the current state? 

@daviddossett for insights

**Comment by roblourens** [comment]
I think I like the version that shows you what will happen if you click the button. Play/Pause buttons are like that

**Comment by daviddossett** [comment]
Created https://github.com/microsoft/vscode/issues/162595 since we seem to be running into this discussion of current vs. target state icons fairly often.

**Comment by zxccvvv** [comment]
TBH I'm used to `lock` icon when auto scroll is off and `unlock` icon when auto scroll is on

now its confusing me when the `lock` icon show up but the content keep scrolling to bottom 😞

**Comment by daviddossett** [comment]
Based on the findings [here](https://github.com/microsoft/vscode/issues/162595#issuecomment-1294223339), I'm reopening since this feels strange to me to have the icon flipped.

**Comment by sandy081** [comment]
I will revert the change next milestone

**Comment by mjbvz** [comment]
@sandy081 See https://github.com/microsoft/vscode/issues/162595#issuecomment-1294244258

I am strongly against swapping the lock/unlock states back. If anything we should switch to a different icon. Maybe the pin icons? For those, pinned should be the default because the viewport is pinned to the bottom of the screen

**Comment by daviddossett** [comment]
I like the idea of a scroll-specific icon vs. trying to force the lock metaphor here. I will explore some ideas and report back.

I would be surprised if others thought about the lock icon representing the panel's viewport being locked rather than the content.

**Comment by rjra100** [comment]
For what it's worth, as a user my feeling - and the only comments I've heard here - is that the swapped icons feel "wrong". My own mental model is that it was locking the content so that it doesn't scroll anymore (and displaying the current state). But that could be just the traditional "it's different; now it sucks" thing, which goes away after a while :)

**Comment by sandy081** [comment]
@daviddossett Lets close this issue as we have done the change and released. 

Please open a new issue and continue discussion there if we want to revert the change or use different icons.
