### ISSUE TITLE
Slow startup (~45 seconds)

### ISSUE THREAD

**Issue by DStradley** [microsoft/vscode#162287]
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
2. ## System Info

* Code: 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7)
* OS: win32(10.0.19044)
* CPUs: AMD Ryzen Threadripper PRO 3945WX 12-Cores     (24 x 3992)
* Memory(System): 31.86 GB(22.25GB free)
* Memory(Process): 197.92 MB working set(159.35MB private, 1.08MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 10153    | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 106      | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 10088    | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 2        | [main]                    | initial startup: true                                      |
| create window                                                   | 33       | [main]                    | initial startup: true, state: 0ms, widget: 31ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 189      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 29200    | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 569      | [renderer]                | cached data: NO, node_modules took 0ms                     |
| wait for window config                                          | 0        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 27       | [renderer]                | -                                                          |
| init workspace service                                          | 24       | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 185      | [renderer]                | -                                                          |
| restore viewlet                                                 | 0        | [renderer]                | -                                                          |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 86       | [renderer]                | 1: PerfviewInput                                           |
| overall workbench load                                          | 352      | [renderer]                | -                                                          |
| workbench ready                                                 | 40503    | [main->renderer]          | -                                                          |
| renderer ready                                                  | 968      | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 40794    | [renderer]                | -                                                          |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1664414010736	0	0
code/didStartMain	1664414010879	143	143
code/willStartCrashReporter	1664414010896	17	160
code/didStartCrashReporter	1664414020984	10088	10248
code/mainAppReady	1664414021032	48	10296
code/willLoadMainBundle	1664414021034	2	10298
code/fork/willLoadCode	1664414021049	15	10313
code/registerFilesystem/file	1664414021135	86	10399
code/didLoadMainBundle	1664414021140	5	10404
code/willStartMainServer	1664414021147	7	10411
code/didStartMainServer	1664414021149	2	10413
code/willCreateCodeWindow	1664414021185	36	10449
code/willRestoreCodeWindowState	1664414021186	1	10450
code/didRestoreCodeWindowState	1664414021186	0	10450
code/willCreateCodeBrowserWindow	1664414021187	1	10451
code/didCreateCodeBrowserWindow	1664414021218	31	10482
code/didCreateCodeWindow	1664414021218	0	10482
code/willOpenNewWindow	1664414021221	3	10485
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1664414021215	0	0
code/didStartRenderer	1664414050414	29199	29199
code/willWaitForWindowConfig	1664414050414	0	29199
code/didWaitForWindowConfig	1664414050414	0	29199
code/willShowPartsSplash	1664414050414	0	29199
code/didShowPartsSplash	1664414050415	1	29200
code/willLoadWorkbenchMain	1664414050421	6	29206
code/didLoadWorkbenchMain	1664414050990	569	29775
code/registerFilesystem/file	1664414050994	4	29779
code/registerFilesystem/vscode-userdata	1664414050994	0	29779
code/willInitWorkspaceService	1664414050998	4	29783
code/willInitStorage	1664414050999	1	29784
code/willInitUserConfiguration	1664414051004	5	29789
code/didInitUserConfiguration	1664414051021	17	29806
code/willInitWorkspaceConfiguration	1664414051021	0	29806
code/didInitWorkspaceConfiguration	1664414051022	1	29807
code/didInitWorkspaceService	1664414051022	0	29807
code/didInitStorage	1664414051026	4	29811
code/willStartWorkbench	1664414051030	4	29815
code/LifecyclePhase/Ready	1664414051093	63	29878
code/registerFilesystem/trustedDomains	1664414051117	24	29902
code/registerFilesystem/vscode-local-history	1664414051123	6	29908
code/registerFilesystem/vscode-debug-memory	1664414051215	92	30000
code/willRestoreEditors	1664414051296	81	30081
code/didRestoreEditors	1664414051382	86	30167
code/LifecyclePhase/Restored	1664414051382	0	30167
code/didStartWorkbench	1664414051382	0	30167
code/didRemovePartsSplash	1664414051382	0	30167
code/willResumeEditSessionFromIdentifier	1664414051418	36	30203
code/didResumeEditSessionFromIdentifier	1664414051418	0	30203
code/registerFilesystem/vscode-edit-sessions	1664414051421	3	30206
code/willConnectSharedProcess	1664414051430	9	30215
code/willLoadExtensions	1664414051488	58	30273
code/willHandleExtensionPoints	1664414051547	59	30332
code/didHandleExtensionPoints	1664414051669	122	30454
code/didLoadExtensions	1664414051673	4	30458
```

### cached data created (lazy, might need refreshes)
[prof-8rw3TDOE.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9669942/prof-8rw3TDOE.main.cpuprofile.txt)

[prof-8rw3TDOE.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9669953/prof-8rw3TDOE.renderer.cpuprofile.txt)

1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
-`/C:/Users/David.Stradley/prof-8rw3TDOE.main.cpuprofile.txt`
-`/C:/Users/David.Stradley/prof-8rw3TDOE.renderer.cpuprofile.txt`

**Comment by DStradley** [comment]
This mysteriously resolved itself, though I can't tell why.  It lasted more than a week, through several reboots, etc., but the last reboot seems to have "fixed" it.  Maybe some sort of system update?

**Comment by deepak1556** [comment]
Closing for now, can reopen if the issue happens again.
