### ISSUE TITLE
No kernel selector

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#162252]
Testing microsoft/vscode-jupyter#11463

1) Open insiders.vscode.dev
1) Install Jupyter and Python extensions
1) Create a new untitled jupyter notebook

-> The notebook does not have a kernel selector. It should have since I should be able to connect the notebook to a remote server (or install the pyodide extension).

<img width="652" alt="image" src="https://user-images.githubusercontent.com/4674940/192845906-bfaef998-9199-44d9-b04f-70a11ef829a5.png">

**Comment by rebornix** [comment]
The kernel selector should now always be visible.
