### ISSUE TITLE
Merge Editor Shows Overlapped Text

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162275]
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/31675041/192902134-c83fe3ca-3f75-40b7-8b2f-a877f090c38f.png">
I opened an old merge conflict and I saw that things looked a little funky in the merge editor. The text for "Accept Current" and "No Changes Accepted" are overlapped. Also, I see some symbols before the branch names that I'm not sure where it's from? I was thinking that this might be due to the super long branch name that is part of this merge conflict 😅

Feel free to close if you can't repro, not too sure what caused this.

**Comment by hediet** [comment]
This only happens for conflicts that start with line 1.
