### ISSUE TITLE
Quick fix lightbulb should go away immediately after the fix is 'applied'

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162214]
Testing #161846

1. Trigger a port collision message
2. See the 💡 , ctrl+. to open the menu and then enter to accept
3. Notice the 💡 hangs around until the next command is run

Imho it should go away immediately like the editor does. Actioning the fix twice results in an error message and a duplicated command on the prompt in the terminal, which is ugly

**Comment by Tyriar** [comment]
Same ask in https://github.com/microsoft/vscode/issues/162180 but for create PR

**Comment by Tyriar** [comment]
Let's track there
