### ISSUE TITLE
Switch Folders Easier

### ISSUE THREAD

**Issue by appleplectic** [microsoft/vscode#162281]
It's ridiculously hard to switch between folders (ctrl+k ctrl+o, click through a million folders, select it). I frequently switch between folders, and so would like it if I could right-click and hit "open folder" or "go back one directory".

Making a directory with subdirectories is a workaround, not a solution, and also source control and extensions like rust-analyzer don't work this way.

**Comment by bpasero** [comment]
You should be using "Open Recent" picker:

<img width="773" alt="image" src="https://user-images.githubusercontent.com/900690/192953156-dde79293-0024-47a9-9e2b-7727bc08a821.png">

It keeps track of recently opened folders and provides fast filtering mechanisms.
