### ISSUE TITLE
Add ability to exclude files from "quick open" (cmd-p)

### ISSUE THREAD

**Issue by ChuckJonas** [Microsoft/vscode#16226]
Similar to the way you can exclude files from search (`search.exclude`) and workspace (`files.exclude`), it would be really nice to be able to exclude files from quick open (`cmd-p`).

My use case is that I have files like I like to be able to access rarely from the explorer pane (configuration and generated code), but I don't ever want them to show up in the quick open list.

**Comment by mjbvz** [comment]
`search.exclude` should exclude items from quick open results. If you are still seeing results from an excluded pattern, they could be coming from the editor history. #6502 tracks applying `search.exclude` to those patterns as well.

Try quick opening a file in an excluded folder that you have never opened before. Does it still show up?

**Comment by ChuckJonas** [comment]
I think this  might be a duplicate #6502... 

It seems like once I open the item it starts showing up in my "Quick Open", even if I restart VSCODE. 

This is not ideal (and actually quite an issue, because some of the file names are the same as ones I actually want in my workspace).

**Comment by chrmarti** [comment]
Thanks @ChuckJonas
