### ISSUE TITLE
Continue working on vscode.dev only includes edited files when working on a branch

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#162208]
Testing #161875

1. open a workspace for a local repo on vscode desktop
2. checkout a branch, make a change and save
3. Continue On... vscode.dev
:bug: only the file with the change is listed in the file explorer, whereas on the main branch, the entire repo is available

:bug: if no changes were made, no files are available and it doesn't open any file to edit

**Comment by amunger** [comment]
![image](https://user-images.githubusercontent.com/2019016/192822263-a7aa2fc7-1de9-4924-b9fc-85574e0baf5b.png)

**Comment by joyceerhl** [comment]
Looks like `testBranch` is not published to the remote https://github.com/microsoft/vscode-jupyter/tree/aamunger/testBranch this is a duplicate of https://github.com/microsoft/vscode/issues/160237
