### ISSUE TITLE
Add a Bracket higlight feature on scroll bar

### ISSUE THREAD

**Issue by soljohnston777** [Microsoft/vscode#16228]
When you select an object/variable, etc it shows it highlighted on the scroll bar.  Could you also do this for brackets { } ?  That way you know where a bracket opens and closes.  I us brackets in PHP, javascript, JQuery, CSS, etc.

**Comment by danrpinho** [comment]
Hey, I'd like to take a look at solving this. Do you have any ideas on where I should get started?

**Comment by alexandrudima** [comment]
`_DECORATION_OPTIONS` in `bracketMatching.ts` can use the `overviewRuler` option to render something in the overview ruler similar to how `overviewRuler` is used in the decoration options of `wordHighlighter.ts` -> `_WRITE_OPTIONS`.

The color used should also be externalized such that themese can customize it (again similar to `wordHighlighter.ts`).

**Comment by danrpinho** [comment]
Thanks, I'll get on it!

**Comment by ntnbst** [comment]
has this feature added ??

**Comment by danrpinho** [comment]
@ntnbst I submitted a working pull request almost a month ago, but it hasn't been either accepted or declined.

**Comment by alexandrudima** [comment]
Closed via #39501

**Comment by soljohnston777** [comment]
Is in the latest release?  And how can you active it?

**Comment by alexandrudima** [comment]
It is in today's Insiders Build Channel. You place the cursor near a bracket.
