### ISSUE TITLE
Consider removing full screen toggle from Zen Mode

### ISSUE THREAD

**Issue by bfulop** [Microsoft/vscode#16224]
Regarding #15647 

- VSCode Version:
1.8.0 Insiders
- OS Version:
10.11.6

Steps to Reproduce:

1.  toggle zen mode

As of today (Nov 29) zen mode also toggles full screen display. I would prefer that it _does not_ change the full screen state. 

I actually use VSCode in full screen mode with split screen mode (together with Firefox) and Zen Mode toggle destroys this layout.

**Comment by bpasero** [comment]
`"window.fullScreenZenMode": false`

**Comment by karbassi** [comment]
2017 update. 

`"zenMode.fullScreen": false`

https://github.com/Microsoft/vscode/blob/aa42e6ef8184e8ab20ddaa5682b861bfb6f0b2ad/src/vs/workbench/electron-browser/main.contribution.ts#L372-L376
