### ISSUE TITLE
Double ctrl+. does not accept suggested quick fix

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#162210]
Testing #161846

In the editor, we recently (last iteration?) made the UI improvement such that tapping Ctrl+. again after opening the quickfix menu would action the default item. This behavior isn't present in the quickfix widget in the terminal.

**Comment by mjbvz** [comment]
@meganrogge and @Tyriar Let me know if you'd like to adopt the `CodeActionWidget` in the terminal

dfc70ad2a78695b9a07f137e2e420eef84913b12 should make it easier to use the widget outside of the editor. I originally did this for #161438 but it would be great to see it used in the terminal too

**Comment by meganrogge** [comment]
@mjbvz we discussed this yesterday and plan to do so in October

**Comment by meganrogge** [comment]
blocked by https://github.com/microsoft/vscode/issues/162067

**Comment by Tyriar** [comment]
@alexr00 that's actually by design, when we can't be certain that no input was done we clear the time. This is always on Windows currently but will be improved over time.
