### ISSUE TITLE
Show a prompt when file changes on disk

### ISSUE THREAD

**Issue by scottlapoint** [Microsoft/vscode#16227]
Add a prompt if another person has modified the file you are working on - Notepad++ has this feature.  Then  you have the option to continue, or reload the file.

Also add a way to open include files directly in the document.  This is a big feature in Adobe DreamWeaver.

**Comment by bpasero** [comment]
@scottlapoint please stay away from filing 2 issues in 1 issue. See https://github.com/Microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/14298
