### ISSUE TITLE
Install Web Extension no longer works

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162240]
1. Serve a local dev build of a web extension which ships as builtin on insiders.vscode.dev over https using a task like 
``` 
{
	"version": "2.0.0",
	"tasks": [
		{
			"label": "Serve web extension over https",
			"type": "shell",
			"command": "mkcert localhost 127.0.0.1; npx --yes serve --ssl-cert localhost+1.pem --ssl-key localhost+1-key.pem --cors",
			"problemMatcher": []
		},
```
2. Use Install Web Extension to install the extension in insiders.vscode.dev
3. Reload 
4. Open Installed Web Extension Resource
5. :bug: see that the extension isn't reflected as installed from localhost

**Comment by sandy081** [comment]
It works for me when I am on default profile. But there is a bug installing an extension does not work in another profiles which I fixed just now. Can you please double check if this is the case?

**Comment by mjbvz** [comment]
@joyceerhl Can you verify this issue has been  fixed?

**Comment by joyceerhl** [comment]
This still repros for me in insiders.vscode.dev @sandy081 with the steps above :/

**Comment by joyceerhl** [comment]
It doesn't work for me when I install the following 
https://github.vscode-unpkg.net/github/vscode-pull-request-github/0.51.2022092709/extension

After a reload (which is required for the newly installed web extension to take effect), I appear to be auto updated to the latest version of the extension
<img width="759" alt="image" src="https://user-images.githubusercontent.com/30305945/193866441-05d5c336-3af9-4dcf-acb0-f609ea997a7e.png">

**Comment by sandy081** [comment]
This is a developer action to side load an extension that is not in Marketplace. But it seems your extension exists in Marketplace and is not a common scenario to side load. This is same as side loading an extension in desktop using VSIX and you see the same behaviour. So you have to make sure to disable updates if this is the case.

**Comment by joyceerhl** [comment]
Sorry to reopen this, but I currently have updates disabled and my side loaded web extensions are still getting auto updated:

![image](https://user-images.githubusercontent.com/30305945/195676869-a769bc37-cd2e-4581-a9db-f7ebca22aec8.png)

**Comment by sandy081** [comment]
It seems these are not side loaded instead they are builtin. If so they are auto updated independent of auto update flag. This flag is only for user installed extensions.

**Comment by joyceerhl** [comment]
Can builtin extensions not disable updates when side loaded?

**Comment by sandy081** [comment]
Yes, when side loaded / installed by user, they won't be auto updated. In fact, they shall not be shown in built in extensions section in that case.

**Comment by joyceerhl** [comment]
I'm seeing that when I sideload a builtin extension, ✅ they are not shown in `@builtin` , ❌ they are auto updated on reload, regardless of my setting configuration. I just confirmed that this is the case on insiders.vscode.dev, and it did not used to be the case till the last 1-2 releases.

**Comment by sandy081** [comment]
> I'm seeing that when I sideload a builtin extension, ✅ they are not shown in @builtin

This should be shown as user installed extension because it was side-loaded so that you can also remove it. I think that's the bug.

**Comment by joyceerhl** [comment]
Thank you @sandy081, works great now :tada: :sob: :partying_face: :pray:
