### ISSUE TITLE
Edit session should not force custom dialog

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162293]
![image](https://user-images.githubusercontent.com/900690/192942107-b8116890-7839-44f2-bab7-71a550b67b24.png)

As a native application on desktop we want our UI to look as native as possible. If we can use a native OS widget (such as for dialogs), we should use it and not force our custom dialog on users. If we decide to use a custom dialog in some cases the experience for our users is inconsistent.

Besides, users can configure a setting to enable custom dialogs everywhere.

**Comment by joyceerhl** [comment]
What is the setting? I tried searching for 'custom' and 'dialog' but did not find it from the settings UI.

Btw, I handled this item in https://github.com/microsoft/vscode/pull/162244 :)

**Comment by joyceerhl** [comment]
\closedWith https://github.com/microsoft/vscode/commit/4bfd9eb6e66fc25eb7d5df55a31f455f1c9b1ab7

**Comment by bpasero** [comment]
@joyceerhl 

<img width="430" alt="image" src="https://user-images.githubusercontent.com/900690/193047330-53a2321e-8c44-4cce-b4b6-1c655ce00ed7.png">
