### ISSUE TITLE
Ctrl+Enter on a Markdown cell prompts for Kernel install

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#162253]
Testing microsoft/vscode-jupyter#11463

1) Open insiders.vscode.dev
1) Install Jupyter and Python extensions
1) Create a new untitled jupyter notebook
1) Create a markdown cell
1) Paste image
1) <kbd>Ctrl</kbd>+<kbd>Enter</kbd>

-> I get a prompt for installing kernels from the market place.

<img width="925" alt="image" src="https://user-images.githubusercontent.com/4674940/192846956-4bc47d2d-0bbd-4345-9da0-b9bd228a6e65.png">

This is wrong for two reasons:
1) Since the Jupyter extension is installed I should be able to connect the notebook to a kernel on a remote server. Also see [vscode-jupyter#11479](https://github.com/microsoft/vscode/issues/162252)
1) This is a markdown cell. No kernel needed for rendering a markdown cell.

**Comment by rebornix** [comment]
I'm not seeing this locally but I can reproduce with vscode.dev. Not sure where is the best place to check whether the cells are markdown cells.
