### ISSUE TITLE
Truncated lines are not obvious in the text editor

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#162320]
Testing microsoft/vscode-jupyter#11463, I (re)learned today that we truncate long lines.

My setup:
1) Open insiders.vscode.dev
1) Install Jupyter and Python extensions
1) Create a new untitled jupyter notebook
1) Create a markdown cell
1) Paste image
1) Save notebook
1) Reopen notebook with text editor
1) Switch off line wrapping 
1) Search for character sequence `is` in the text editor

-> At some point you reach the end of the truncated line without being aware what's happening. It feels like the editor stops responding. See recording here: https://share.cleanshot.com/g4qxRZ

When I checkout the warning about tokenization and look at the setting, I don't learn that the line is truncated.

**Comment by alexdima** [comment]
Tracking this in #7772
