### ISSUE TITLE
Issue with \tag per row of {align} inside tex and markdown

### ISSUE THREAD

**Issue by dvd101x** [microsoft/vscode#162379]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Windows 10 Enterprise 21H2

Steps to Reproduce:

1. Make a new markdown file
2. Insert an equation with align and tags per line
```md
$$
\begin{align}
D &= \frac{1}{2}\rho _ g \pi a^2 u^2 C_ D(Re) \tag{1.5} \\
Re &= \frac{2 \rho _ g u a}{\mu _ g}  \tag{1.6} \\
C_ D &= \frac{24}{Re} + \frac{6}{1 + \sqrt {Re}} + 0.4  \tag{1.7} 
\end{align}
$$
```
3. Open preview

Actual result:

```
ParseError: KaTeX parse error: Multiple \tag
```

Expected result:

$$
\begin{align}
D &= \frac{1}{2}\rho _ g \pi a^2 u^2 C_ D(Re) \tag{1.5} \\
Re &= \frac{2 \rho _ g u a}{\mu _ g}  \tag{1.6} \\
C_ D &= \frac{24}{Re} + \frac{6}{1 + \sqrt {Re}} + 0.4  \tag{1.7} 
\end{align}
$$

Probable cause:
* VScode seems to be using [KaTeX v0.13.0](https://github.com/KaTeX/KaTeX/releases/tag/v0.13.0)
https://github.com/microsoft/vscode/blob/0ee05bb617c5585d9a329e7b34cc6ec9edca10dc/extensions/markdown-math/yarn.lock#L9
* \tag per row of {align} is supported since [KaTeX v0.15.1](https://github.com/KaTeX/KaTeX/releases/tag/v0.15.1)

Please consider upgrading KaTeX version

**Comment by baterson** [comment]
@mjbvz Hello! I would like to fix it but I'm not quite sure how to do it. 
So far my understing is - I should open PR with the Katex version update for the peer dependency https://github.com/iktakahiro/markdown-it-katex of the markdown-math extension. And then run the yarn upgrade in markdown-math.
Is it correct assumption?

**Comment by StephenChips** [comment]
Wired, it looks good to me.

![image](https://user-images.githubusercontent.com/17926083/193255900-7285931a-94a8-4726-afc9-832717fa4001.png)

**Comment by dvd101x** [comment]
I did test with the newer version of katex and it already works with [markdown-it-katex](https://github.com/iktakahiro/markdown-it-katex) if [loaded manually on a browser](https://katex.org/docs/browser.html).

You could validate it by entering this [math notepad](https://dvd101x.github.io/math-notepad/) and entering this code. (the same code starting with `# `) 

```mathjs
# $$
# \begin{align}
# D &= \frac{1}{2}\rho _ g \pi a^2 u^2 C_ D(Re) \tag{1.5} \\
# Re &= \frac{2 \rho _ g u a}{\mu _ g}  \tag{1.6} \\
# C_ D &= \frac{24}{Re} + \frac{6}{1 + \sqrt {Re}} + 0.4  \tag{1.7} 
# \end{align}
# $$)
```

I don't know how it works in vscode and I'm not sure if my comment is useful. I'm just sharing some information as a reference.
