### ISSUE TITLE
Starting in dark theme, switching to light and reloading window shows dark background

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16230]
Steps to Reproduce:

1. Light theme, cltr + R - switch workspace
2. Notice the black screen. This was not there yesterday

![blackscreen](https://cloud.githubusercontent.com/assets/1926584/20719193/7df4c97e-b65b-11e6-9b28-e14a1d42866b.gif)

**Comment by bpasero** [comment]
@isidorn you switched themes once, doesnt happen otherwise.

**Comment by bpasero** [comment]
Only happens when you started with dark theme, then switch to light theme in the running session. Not a big deal, has always been like that.

**Comment by bpasero** [comment]
Happens because when we create the window we set a `backgroundColor` to match the theme background. To my knowledge there is no way to change this after a window has been created.

**Comment by bpasero** [comment]
I think @aeschli fixed this 🙌

**Comment by isidorn** [comment]
There is still a flash, but very quick. All in all it is much better now

**Comment by aeschli** [comment]
As Ben said, there's a background color set on the window which can not be changed. From time to time its visible.
