### ISSUE TITLE
Build: Corrupted build uploaded to CDN

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#162316]
Something went very wrong with the `darwin-arm64` asset of the `20220929.4` build:

- [It was correctly created and uploaded to DevOps assets](https://monacotools.visualstudio.com/Monaco/_build/results?buildId=187119&view=logs&j=18bc243d-8e1c-52ef-acba-f719587ff049&t=d96fa545-c243-5eac-877a-098b8099ae34), exact size: 111,116,638 bytes. Manually downloading that confirms the app is OK.
- [It was incorrectly processed into the Publish step](https://monacotools.visualstudio.com/Monaco/_build/results?buildId=187119&view=logs&j=43b54640-f671-5524-8f7b-714d77229de9&t=8c631bd7-3091-56a7-0716-a38699ccbe61&l=855), exact size: 4,751,360 bytes. This is what got published to the CDN and is completely broken. This _blob_ shares much of the same bytes as the correct full asset, but looking closer around the end of the 4MB  I found the bytes are actually different (as in corrupted).

I suspect something went wrong in the [extraction step](https://github.com/microsoft/vscode/blob/b784e0514d4608cc20a0e7ce62baf7bc8131158c/build/azure-pipelines/product-publish.ps1#L70), after downloading the asset. There's a chance something went wrong in the [download step](https://github.com/microsoft/vscode/blob/b784e0514d4608cc20a0e7ce62baf7bc8131158c/build/azure-pipelines/product-publish.ps1#L66) but the likelihood of that happening and still producing a valid ZIP archive that `Extract` wouldn't trip on is very low.

What's ugly about this failure is that it wasn't a failure at all, the build was full green and happily pushed that thing to the CDN.

**Comment by TylerLeonhardt** [comment]
So bizarre. So the it's really like...either...

* The `Expand-Archive` doesn't actually do what it's supposed to do and fails silently
* The `Invoke-RestMethod` stores some corrupted/incorrect data in `XXXXXX.zip` and the `Expand-Archive` is convinced it's ok and 'unzips' it
* Both of the bullet points

All of these seem incredibly unlikely... I wonder how we could be "better at failing" here...

docs: https://learn.microsoft.com/en-us/rest/api/azure/devops/build/artifacts/list?view=azure-devops-rest-6.0#definitions

Ok trying out the API it looks like we have something here:
![image](https://user-images.githubusercontent.com/2644648/193150821-ec460c9b-7ddc-4589-8ba4-5238f9b5ca2c.png)
namely `artifactsize`.

I'll try comparing the value of that with the actual asset downloaded. Also what's nice about this check is that `artifactsize` is the size of the thing inside of the zip. In otherwords, it's the size of thing after we Expand-Archive.

**Comment by TylerLeonhardt** [comment]
To fix this, I'll have this check the artifact size: https://github.com/microsoft/vscode/pull/162407
I'm waiting on this build to confirm this warning doesn't show up when it shouldn't https://monacotools.visualstudio.com/Monaco/_build/results?buildId=187255&view=results

**Comment by joaomoreno** [comment]
Yup it was some Twilight Zone stuff.

Very cool, I was hoping there would be some metadata like this we could check against! Good job! 👏
