### ISSUE TITLE
Tab in CSS editor after colon creates errant autocomplete

### ISSUE THREAD

**Issue by richardtallent** [Microsoft/vscode#1623]
**Bug:** When editing a CSS file, using the tab key after a colon inserts the characters `:;` rather than actually inserting the tab. Similar expansion bugs occur when pressing tab before the colon, or after any selector.

**What should happen:** a tab character should be inserted, or if the user has chosen to expand tabs to spaces, the appropriate number of spaces.

**Steps to reproduce:**
Enter the following code in a CSS file:

``` css
div {
    font-size:12pt;
}
```

Position the cursor after the `:` and hit the tab key. Rather than `12pt` moving to the right, an extra `:;` is inserted.

**Platform:** OS X 10.11.2, Visual Studio Code 0.10.5.

I've tested this in Windows 10 on Visual Studio Community Edition, and it behaves as expected.

**Comment by aeschli** [comment]
It is emmet that expands on `:` For example. if you do `d:` it would expand to `display: block;`
It would good if emmet wouldn't expand if is not at the end of the line

**Comment by egamma** [comment]
We could also provide an option to disable emmet, this would remove the annoyance.

Need to investigate whether emmet should in general only expand on tab at the end of the line.

**Comment by egamma** [comment]
Added a setting to disable emmet expansion on TAB:  ` "emmet.triggerExpansionOnTab": false`

**Comment by ramya-rao-a** [comment]
The fix will be available in tomorrow's Insider build

**Comment by RobIsHere** [comment]
Please make this "fix" a default or maybe remove this emmet crap if it doesn't work. I have this not only in css but also in js files in all objects. Every second time vscode guesses wrong. That is not only a minor problem but a major one. CMD+Z is my new most used key.

Your team created maybe the greatest code editor ever. But sometimes i miss the attention to details in UX. As a user you ask yourself: how could a problem that happens 2 times in 2 minutes slip through quality checks and make it into a release?

Good that I googled it with the matching search string finally and found this. As a user you don't think "Hey emmet messes it up, so I search for an emmet-disable config key". As a user you think: "Somehow this is broken, and i don't know where to start looking for a fix"...then you spend some hours searching or switch your favorite editor.

**Comment by ramya-rao-a** [comment]
@RobIsHere Sorry for the trouble this got you. Emmet expansion does sneak in, in unexpected situations at times. Good news is that there is a workaround as @egamma suggests above, but bad news is that it is difficult for a user to know that this is an emmet issue to begin with like you have explained.

Personally, I do feel that this should have been an opt-in feature just like emmet support in other editors. Regardless, we now have had the emmet built-in support for over a year and disabling it by default is going to be a non-starter as it will disrupt all the existing emmet users

The good news is that we are working on getting a better emmet user experience where emmet expansions do not sneak in on you when you hit TAB. Instead it will show up in the auto-complete list.

We are doing this by using the new Emmet apis which are much smarter than the current emmet library in understanding the context of where your cursor is and will not have errors like this issue describes.

Hopefully with the current issue out of the way, you will have a more pleasant experience with VS Code

Happy Coding!

**Comment by ramya-rao-a** [comment]
The new Emmet experience is now shipped with VS Code 1.15

Tab will no longer trigger Emmet.

Please read more on what else is new at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
