### ISSUE TITLE
How to make Ctrl+Tab cycle through all open documents?

### ISSUE THREAD

**Issue by waynebloss** [Microsoft/vscode#16238]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393

Steps to Reproduce:

1. Hit Ctrl+Tab
2. It only cycles through the documents in one group.

Is there any way to make it cycle through all of the open documents like Visual Studio does?

**Comment by chrmarti** [comment]
You could use Open Previous/Next Editor. Ctrl+Alt+Left/Right Arrow on Windows I believe. It doesn't come with the drop-down list though.

**Comment by bpasero** [comment]
@waynebloss you can remap `workbench.action.showAllEditors` to Ctrl+Tab and it should work.

**Comment by waynebloss** [comment]
OK, none of these solve the issue.

We need a new command for this: `workbench.openNextRecentlyUsedEditor`

**Comment by waynebloss** [comment]
@chrmarti Ctrl+Alt+Left/Right are for the command `workbench.action.moveEditorToPreviousGroup`.

**Comment by bpasero** [comment]
Continues in https://github.com/Microsoft/vscode/issues/16463
