### ISSUE TITLE
Add sticky scroll context menu

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#162330]
It would be valuable to have a context menu for sticky scroll that allows to toggle it. We could also show it for breadcrumbs and also have the respective toggle in it.

**Comment by jrieken** [comment]
* have sticky scroll enabled (via F1 > Toggle Sticky Scroll)
* right click it
* make sure there are entries to toggle sticky scroll and breadcrumbs

**Comment by hediet** [comment]
Now I miss the context menu for the breadcrumb bar ;)
