### ISSUE TITLE
Handle 405 error from server

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#162380]
Testing #161785

@rebornix and I figured out that the issue he is seeing an issue with data inconsistency on the server. Some how client has synced a profile with a collection id but that collection does not exist on the server. `profiles` resource has a profile with a collection id and this collection id does not exist on the server.

**Comment by sandy081** [comment]
@Tyriar Any idea how this can be possible on the server? From the client side, I am deleting the collection only after removing the profile with that collection id 

https://github.com/microsoft/vscode/blob/5c168e7c3907a95135a8d95436832094dc380358/src/vs/platform/userDataSync/common/userDataProfilesManifestSync.ts#L217-L222

**Comment by Tyriar** [comment]
Is the collection there if you query the manifest and `/v1/collection`? It's a little hard to know what the issue could be by just eye balling the code as I'm not very familiar with it.

**Comment by sandy081** [comment]
> Is the collection there if you query the manifest

No collection does not exist in the manifest. 

> and /v1/collection

I do not know about it

**Comment by sandy081** [comment]
> Does trying to recreate the collection result in an error?

No, I do not recreate the collection. I assume it exists if the profile resource contains a profile with collection url.

**Comment by sandy081** [comment]
This should be fixed by https://github.com/microsoft/vscode/pull/165713

**Comment by TylerLeonhardt** [comment]
@sandy081 verification steps?

**Comment by Tyriar** [comment]
@TylerLeonhardt verifying this via code review is probably best, so make sure it looks like 405 is handled specially
