### ISSUE TITLE
Enable AutoDisableAccessibility Chromium runtime flag

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#162331]
As part of https://bugs.chromium.org/p/chromium/issues/detail?id=1143047 chromium added a runtime feature called AutoDisableAccessibility and it works like this:
```
Adds logic that disables accessibility under these circumstances:
* There are 3+ user input events in web content (mouse down, key down,
  or touch start count)
* Over a period of more than 30 seconds
* And no usage of accessibility APIs in that time.

The goal of this logic is to avoid disabling accessibility
simply due to inactivity, i.e. the browser is idle - but instead
to try to disable accessibility when there's evidence that the
user is actively using their browser but no longer using assistive
technology or anything else using accessibiltiy APIs.
```

We should try out this flag to see how it affects our accessibility detection on macOS.

**Comment by isidorn** [comment]
@deepak1556 thanks a lot for this
fyi @devinvalenciano this change might affect our telemetry numbers - since now we might auto disable accessibility when chrome decides it is actually not being needed.

**Comment by deepak1556** [comment]
@isidorn I have enabled it for all OS since there is no downside. As part of this, I also redid the accessibility event that gets fired from the runtime to work well with this feature flag. So, in endgame it would be good to have test plan that ensures our accessibility detection continues works fine on all OS.

**Comment by isidorn** [comment]
@deepak1556 ok, I can create a test plan item for that today with complexity 2.

fyi @meganrogge

**Comment by isidorn** [comment]
Created test plan item https://github.com/microsoft/vscode/issues/167159
Feel free to edit it if you think I did not cover some scenario. Thanks!
