### ISSUE TITLE
action items jiggle left and right even after menu close

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#162375]
https://user-images.githubusercontent.com/29464607/193092515-8319ad4a-293f-4a34-be80-8748d5992cb4.mov

**Comment by meganrogge** [comment]
keeps happening when the context menu is closed
https://user-images.githubusercontent.com/29464607/193092611-b44323fc-41e4-44b4-94bf-5fba710666ca.mov

**Comment by meganrogge** [comment]
@Tyriar an unexpected bug is that the jiggling doesn't stop when you close the menu

**Comment by meganrogge** [comment]
@jrieken should I verify that this is fixed?

**Comment by jrieken** [comment]
Hard to do. This is actually a duplicate of another item. @bpasero also saw the jiggle continuing and we concluded that it is a fluke. On mac, which I assume you are using, a right- is sometime emitted as left-click. This often happens out-of-dev and is something that's going wrong in electron (we believe).
