### ISSUE TITLE
Merge editor actions are all hidden in "..."

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#162340]
![image](https://user-images.githubusercontent.com/900690/193035722-53e98052-39e0-4c51-80e2-67d0359e105e.png)

I personally find it a bit strange to have no primary action and only secondary actions hidden behind "...". What is the rationale?

//cc @daviddossett

**Comment by daviddossett** [comment]
We are looking at pulling these out as primary actions like so. See #158890.

<img width="1015" alt="CleanShot 2022-10-03 at 09 11 23@2x" src="https://user-images.githubusercontent.com/25163139/193626543-2a7d1099-7d5f-4c5b-aea0-54bf401b0f49.png">
