### ISSUE TITLE
Requesting setting to hide discussion bar

### ISSUE THREAD

**Issue by rengler-noodle** [microsoft/vscode#162352]
See related issue that was closed by user who opened it: https://github.com/microsoft/vscode-pull-request-github/issues/2327

I think it'd be fantastic to hide the discussion/comment bar for those of us that like to keep our interface really minimal. Part of it is how it's distracting to see the + sign moving all over the document with the cursor. I'd like to be able to turn it off in the settings for all circumstances.

<img width="115" alt="image" src="https://user-images.githubusercontent.com/94383622/184027027-a142ef8e-a3c0-4916-a88b-c593fd75a836.png">

**Comment by DinaraAldarova** [comment]
Hello! I'm also looking forward to hiding this button. Actually I just need to make commits in vs code, and I don't use review even when a pull request is open

But of course someday I will use it, it's just that this good function is not for every day

**Comment by alexr00** [comment]
Incoming change does the following:
- Persists your pre-zen mode comment toggled state when exiting zen mode
- Introduces the setting `comments.visible`
- Still let you quickly toggle commenting on an off irrespective of `comments.visible`, similar to how toggle word wrap works.

**Comment by tbenthompson** [comment]
Thanks for the progress!! It seems like the new settings don't do anything about the double-wide gutter. That's a pretty big deal because I'm losing a decent chunk of screen real estate even when commenting is turned off.

**Comment by alexr00** [comment]
@tbenthompson I was going to address that in a separate PR to keep my changes smaller. I'm planning to fix it today!

**Comment by tbenthompson** [comment]
Oh hurray!! So exciting!!
