### ISSUE TITLE
How can I find out what parameters the built-in commands receive?

### ISSUE THREAD

**Issue by PiDmitryInke** [microsoft/vscode#162322]
I want to use **editor.action.peekDefinition** command in my custom extension, but I don't know what parameters it receives.

I asked this question a week ago on **stackoverflow**, but no one answered. Unfortunately, I didn't find it in **Google** either. Only for individual functions found parameters

**PS: I know this is off topic. But I would like documentation for all built-in commands so that you can see what parameters they take. For example, in the Keyboard Shortcuts window.**

**Comment by jrieken** [comment]
Generally built-in commands do not accept arguments, those that do are listed as "API commands" here: https://code.visualstudio.com/api/references/commands
