### ISSUE TITLE
code --list-extensions includes disabled extensions

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16231]
- VSCode Version: 1.8.0-insiders

One use-case for --list-extensions is for letting people tell us what extensions they are running, we should either excluded or mark those that are disabled.

**Comment by joaomoreno** [comment]
This could never be entirely accurate because at the level of the CLI we don't have a workspace context. There is only the notion of the global disabled extensions. The user could still open Code in a workspace which disables a specific extension.

**Comment by chrmarti** [comment]
Hadn't considered that. The Report Issues command could add an 'enabled' column then. My intent is to have a simple way to ask users for their list of enabled extensions.

**Comment by joaomoreno** [comment]
I'd do it through another way, like having a `Help > Generate Debug Report...` menu action which would provide the user some text he could copy paste onto the gh issue.

**Comment by sandy081** [comment]
Fixed by https://github.com/Microsoft/vscode/pull/37705
