### ISSUE TITLE
Consider to revert workbench contribution id

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#162305]
With 7f26c5b4ac818a6f1c7699b7a99e14b71d874d09 each workbench contribution has an identifier. This resulted in a measurable increase of our bundle size.   I don't believe the costs outweigh the value this brings. We only long the id when errors or slowness happens. This is only really useful at dev time and then things aren't bundled and we can use the ctor-function name of contributions

**Comment by bpasero** [comment]
Yes, not so happy with it anymore anyway because now that we made most services lazy, a workbench contribution may appear as slow even though it just happens to require some fat services.

**Comment by bpasero** [comment]
via https://github.com/microsoft/vscode/pull/162312

**Comment by jrieken** [comment]
> a workbench contribution may appear as slow even though it just happens to require some fat services.

That should motivate lazy contributions :-)

**Comment by bpasero** [comment]
Yeah I revisited my thinking and left the console log in for running out of sources, its still valid!
