### ISSUE TITLE
`Go to most recently failed cell` is shortened to `Go To` in actions bar

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#162378]
I'd think it should be `Go to Failed` or something

![Screen Shot 2022-09-29 at 10 08 42 AM](https://user-images.githubusercontent.com/29464607/193095582-bf95fe89-837a-4a46-bcb8-29d6ec8654e7.png)

**Comment by roblourens** [comment]
Previously it was longer, but it takes up too much space in the action bar where space is limited. Since it's a non-destructive command, I think it's fine to leave it short where people might click it to see what happens. Or, they will read the tooltip with the full label.
