### ISSUE TITLE
Cannot configure tasks when runTask is run with a filter

### ISSUE THREAD

**Issue by adam-fowler** [microsoft/vscode#162369]
Cannot configure tasks when `workbench.action.tasks.runTask` is run with a filter.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: macOS 12.6

Steps to Reproduce:

1. In an empty folder, create `.vscode` folder
2. Inside `.vscode` folder create `tasks.json` as follows
```
// See https://go.microsoft.com/fwlink/?LinkId=733558
// for the documentation about the tasks.json format
{
	"version": "2.0.0",
	"tasks": [
        {
            "label": "compile",
            "type": "npm",
            "script": "compile",
            "problemMatcher": "$tsc",
            "presentation": {
                "reveal": "never"
            }
        }
    ]
}
```
3. Open `keybindings.json` and add the following keybinding
```
    {
        "key": "shift+ctrl+i",
        "command": "workbench.action.tasks.runTask",
        "args": {
            "type": "npm"
        }
    }
```
4. Open vscode in that folder
5. Press `Shift+Ctrl+i`. A task picker should appear with one entry: compile
6. Press the configure button on the right hand side of the picker to configure the compile task
7. Nothing happens

I would have expected it to open the tasks.json file so I could configure the task

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by adam-fowler** [comment]
I tried the insiders build (1.72.0-insider) and while the configure works, the task filtering is broken. It no longer filters tasks by `type`.
