### ISSUE TITLE
environment variables from ~/.zshenv are not available using ${env:name} even though ~/.zshenv is being sourced

### ISSUE THREAD

**Issue by imthenachoman** [microsoft/vscode#162387]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Bug</b>

I am exporting some environment variables in ~/.zshenv

```
echo start of ~/.zshenv

export thisIsMyTest=(-la ~/Downloads)

echo end of ~/.zshenv
```

I have created a task to use this variable using `${env:thisIsMyTest}`:

```
{
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
        {
            "label": "test",
            "type": "shell",
            "command": "echo the thisIsMyTest variable is ${env:thisIsMyTest}"
        }
    ]
}
```

I would expect the output to be:

```
start of ...
end of ...
the thisIsMyTest variable is -la /Users/nigaman/Downloads
```

But instead the output is:

```
start of ...
end of ...
the thisIsMyTest variable is 
```

For some reason the `${env:thisIsMyTest}` does not return what it should.

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id 531df307-d774-45c4-8b5c-5b507ce330f7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
TabOut|alb|0.2.1
Bookmarks|ale|13.3.1
markdown-checkbox|bie|0.3.3
markdown-preview-github-styles|bie|1.0.1
vscode-eslint|dba|2.2.6
reg|ion|1.1.0
shortcut-menu-bar|jer|3.0.4
template-string-converter|meg|0.6.0
vscode-autohotkey|sle|0.2.2
markdowntable|Tak|0.10.2
cursor-align|yo1|1.1.0
markdown-all-in-one|yzh|3.4.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by meganrogge** [comment]
are you still seeing this behavior?

**Comment by imthenachoman** [comment]
I just updated to the latest version and yes, I am still seeing this behavior.

If I have something like:

```
export thisIsMyTest="hi"
```

then it works. But if I have something like:

```
export thisIsMyTest=(-la ~/Downloads)
```

Then it does not.

**Comment by imthenachoman** [comment]
@weartist Yes, that worked. But that is confusing. 

For some places you need `${env:variable}` and for some places you need just `${variable}`. Why would that be? 

Even the VS Code documentation says to use `${env:variable}`: https://code.visualstudio.com/docs/editor/variables-reference#_environment-variablesb.

**Comment by weartist** [comment]
> @weartist Yes, that worked. But that is confusing.
> 
> For some places you need `${env:variable}` and for some places you need just `${variable}`. Why would that be?
> 
> Even the VS Code documentation says to use `${env:variable}`: https://code.visualstudio.com/docs/editor/variables-reference#_environment-variablesb.

Indeed, it looks like the env argument was set empty when the argument was parsed

![Snip20221211_29](https://user-images.githubusercontent.com/17105034/206908725-a9e73f9c-677e-46e5-abc4-33bc91860a1c.png)

**Comment by imthenachoman** [comment]
Is that normal or a bug/issue?

**Comment by meganrogge** [comment]
Closing this as I haven't seen other reports and there is a workaround
