### ISSUE TITLE
white flash when alt+tab between vscode windows

### ISSUE THREAD

**Issue by U676** [microsoft/vscode#162334]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 4.9.0-18-amd64
- OS Version:
Debian 9
MATE Desktop Environment 1.16.2
Virtual Box 6.1.38 QT(5.6.2)

Steps to Reproduce:

1. Open 2 Windows of VSCode.
2. Make them full screen.
3. Alt+tab between the windows
4. A white flash(white screen) is shown when the windows are switching place.
        It looks like the window that is switched has a blank screen and then loads the actual content
        Especially noticeable when using dark mode! I've resorted to light mode.

**Comment by deepak1556** [comment]
Are you running on wayland ? Does this issue repro with latest stable `1.74` ?
