### ISSUE TITLE
Folding of function's body fails when it has named parameters in dart

### ISSUE THREAD

**Issue by Hexagonale** [microsoft/vscode#162300]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.70 (July)
- OS Version: Mac OS 12.3 (ARM)

Steps to Reproduce:

1. Install Dart extension
2. Create this file:
```
void functionWithNamedParameters({
  required String parameter1,
  required String parameter2,
}) {
  print('parameter1: $parameter1');
  print('parameter2: $parameter2');

  print('I cannot fold in 1.70, but I can in 1.60!');
}
```

When I use `1.69` (June) version folding works as expected:
<img width="443" alt="Screen Shot 2022-09-29 at 08 38 51" src="https://user-images.githubusercontent.com/33176470/192961070-7e803bb4-7b71-4b6b-9c1f-b41f31865488.png">

When I use `1.70` (July) version folding of function's body is impossible (only one arrow / chevron is visible):
<img width="427" alt="Screen Shot 2022-09-29 at 08 39 09" src="https://user-images.githubusercontent.com/33176470/192961388-1e6365b9-36ba-4c92-ac34-01fcdef1d545.png">
And it results in this:
<img width="452" alt="Screen Shot 2022-09-29 at 09 52 24" src="https://user-images.githubusercontent.com/33176470/192973120-d9b77919-e276-4ab3-9947-ab16a1bae2b1.png">

With Insider version it fails as well:
<img width="443" alt="Screen Shot 2022-09-29 at 08 45 26" src="https://user-images.githubusercontent.com/33176470/192961721-a7489b23-0ab6-48a1-a1a7-b278deec843d.png">

When I disable `Dart` extension it works, but when I roll back to the old version of extension it still does not work. So my understanding is that `1.70` broke some API that `Dart` uses to fold the code (since folding is handled by the Dart engine).

**Comment by aeschli** [comment]
I don't think anything changed with the folding API or implementation.

Has the issue already been filed against the Dart extension?

**Comment by Hexagonale** [comment]
No, but the Dart extension version does not influence the bug. Only the VS Code version changes the behavior. So this should not be Dart's fault, right?

**Comment by aeschli** [comment]
The Dart extension send the following ranges
![image](https://user-images.githubusercontent.com/6461412/193030118-c251e090-1fee-499c-9018-2e40552ee459.png)

The second range overlaps with the first and is ignored. It should start at line 4.

**Comment by aeschli** [comment]
-> Please file against the Dart extension.
