### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by TN-Jesus** [Microsoft/vscode#16232]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|
|startanyshell|remcoros|0.3.1|

---

Steps to Reproduce:

1.OutPut(Ctrl+Shift+U),Chinese garbled
E.g:task.json

> {
>     // See https://go.microsoft.com/fwlink/?LinkId=733558
>     // for the documentation about the tasks.json format
>     "version": "0.1.0",
>     "command": "echo",
>     "isShellCommand": true,
>     "args": ["你好，世界"],//hello,world
>     "showOutput": "always"
> }
OutPut:

> ���ã�����

**Comment by chrmarti** [comment]
Duplicates #3550
