### ISSUE TITLE
The markdown preview will show content that is under the sticky scroll items

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#162475]
The markdown preview keeps scrolling back up because of a linked image that is not actually rendered in the editor.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/2019016/193366300-0c275626-a59d-4d51-8f94-0bc7b8c9f96f.png">

markdown code:

```
# Header

## subheader

### sub subheader

![](vs-code-logo-transp.png)

#### item

Item being edited
```

**Comment by mjbvz** [comment]
This seems by-design to me

We synchronize scrolling to the top of the viewport. If we also accounted for sticky scrolling, the markdown preview would jump around more as the sticky scroll becomes taller or shorter while you scroll through the doc
