### ISSUE TITLE
Sanitize incoming cwd better

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#162456]
Thanks to @andrewburgess in https://github.com/microsoft/vscode/issues/160109, they found it was happening because the OSC 9;9 sequence was wrapping the cwd in quotes:

```
�]9;9;"G:\Projects\temp"�\
```

We should sanitize all incoming cwds inside the `ShellIntegrationAddon._updateCwd` call.

**Comment by lramos15** [comment]
Not sure how to verify this
