### ISSUE TITLE
Notebook shows changed in SCM but no diffs

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#162480]
Type: <b>Bug</b>

Re-opened a workspace from a dev container on my local folder. I didn't run the notebook, yet it shows up as changed. Opening the diff doesn't highlight any changes.

<img width="1257" alt="image" src="https://user-images.githubusercontent.com/8599/193375718-fb7ecd60-26fe-43aa-a85f-b4725e5b0506.png">

VS Code version: Code - Insiders 1.72.0-insider (2c801254ebf547baaee771b99aa76d202f999622, 2022-09-29T08:07:33.897Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 6, 6|
|Memory (System)|64.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by rebornix** [comment]
I think it's because there is document metadata change but no cell changes.
