### ISSUE TITLE
Window Page Scroll commands need to preserve selection.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#16248]
When running the "editorScroll" command, I would like an option to extend the current selection to the new location of the cursor.

We need this over in VSCodeVim: https://github.com/VSCodeVim/Vim/issues/907

Thanks! You guys are the best. 😄

**Comment by alexandrudima** [comment]
fyi @sandy081

**Comment by alexandrudima** [comment]
Duplicate of #22147
