### ISSUE TITLE
Support Git extension in vscode web

### ISSUE THREAD

**Issue by nkitsaini** [microsoft/vscode#162493]
Currently Git Extension is not available in vscode-web. And in the documentation I did not find a way to get hold of `SourceControl` instance either. So the extensions need to take care of this on there own. Also git features like `Stage Selected Ranges` are missing. Is there any plan to support this in web?
https://github.com/microsoft/vscode/blob/61f8dee571efac71035000f4c57f1c42ada04e46/extensions/git/package.json#L36

**Comment by lszomoru** [comment]
At the moment https://vscode.dev only works with GitHub repositories and Azure Repos. The current `git` extension in its current form cannot be supported on the web as it shells out to `git.exe` to perform all source control operations.

**Comment by lszomoru** [comment]
Closing as "out-of-scope" as there are no current plan to have the `vscode.git` extension work in web.
