### ISSUE TITLE
Pressing Cmd+W in Release Notes closes entire vscode.dev PWA window when installed as PWA on macOS

### ISSUE THREAD

**Issue by zhuowei** [microsoft/vscode#162485]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: macOS 12.6 / Chrome 108.0.5327.0 (Official Build) dev (x86_64)

Steps to Reproduce:

1. Go to https://vscode.dev
2. Chrome menu -> Install Visual Studio Code -> Install
3. VSCode opens in a PWA.
4. Quit and re-open the PWA.
5. Help -> Release Notes
6. Press Cmd+W

Expected: the Release Notes tab closes
Actual: the whole PWA window closes

**Comment by zhuowei** [comment]
I think this may be an example of https://github.com/microsoft/vscode/issues/150735, since the release notes view seems to be a webview - feel free to mark this as a duplicate if it is.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/150735
