### ISSUE TITLE
路径 c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib 未指向有效的 tsserver 安装。将禁用 TypeScript 语言功能。

### ISSUE THREAD

**Issue by jinjl** [Microsoft/vscode#16246]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|project-manager|alefragnani|0.12.2|
|path-intellisense|christian-kohler|1.1.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|auto-close-tag|formulahendry|0.3.5|
|auto-rename-tag|formulahendry|0.0.8|
|beautify|HookyQR|0.6.2|
|vscode-icon-theme|jtlowe|1.1.9|
|sublime-keybindings|ms-vscode|1.6.1|
|startanyshell|remcoros|0.3.1|
|vscode-icons|robertohuertasm|4.0.4|
|vue|seanwash|0.4.2|
|require-complete|sensourceinc|0.0.3|
|code-settings-sync|Shan|2.3.8|
|guides|spywhere|0.5.1|

---

Steps to Reproduce:

1.
2.

**Comment by bang88** [comment]
Translate: The path `c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib` doesn't point to a valid tsserver install.TypeScript language features will be disabled.

@jinjl Please check your vscode settings. If you use a workspace version,Please check it have installed typescript.

**Comment by chrmarti** [comment]
@jinjl Could you check what is at that path? Reinstalling might help, but it would be interesting to know what is on disk before you reinstall.

**Comment by mjbvz** [comment]
Closing as we need more info to investigate this.

@jinjl Please try checking to see if the referenced path exists and let us know so we can reopen the investigation. Also, reinstalling VSCode may fix this.
