### ISSUE TITLE
Symbols after collapsed markdown item

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162408]
When I collapse title here, I get some strange symbols after it:

[![Image from Gyazo](https://i.gyazo.com/71f98308cb84af931a2c7b5f0487088a.gif)](https://gyazo.com/71f98308cb84af931a2c7b5f0487088a)

**Comment by mjbvz** [comment]
@aeschli Assigning you since I think this is an issue with VS Code's folding implementation and not with the markdown folding provider

**Comment by aeschli** [comment]
duplicate of https://github.com/microsoft/vscode/issues/145897
