### ISSUE TITLE
"Extensions" output channel?

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#162458]
Just wondering whether the "Extensions" output channel is actually used for anything? I have checked it when troubleshooting extensions many times and don't think I've ever actually seen any output in there

**Comment by sandy081** [comment]
This is being used by debug adapter

https://github.com/microsoft/vscode/blob/ef802ebe7af412860387ac984682f6c86880af5c/src/vs/workbench/contrib/debug/node/debugAdapter.ts#L260-L263

Feel free to remove it if you are not using.

**Comment by roblourens** [comment]
Oh, wow 🪃 

No clue about that

**Comment by roblourens** [comment]
I guess it was introduced in https://github.com/microsoft/vscode/commit/45de4af158df229ae9991cb21c252296aa1b62a8, previously showed errors from all extensions, now I think those errors go to other general logs, and probably just this one usage got left behind. @isidorn any idea if there was some discussion about this in the past? Or I will remove it

**Comment by isidorn** [comment]
@roblourens not aware of anyone using it. I think we can go ahead and remove it.

fyi @weinand

**Comment by jcrben** [comment]
bit off-topic here but I was looking around for an issue around a "combined" log (showing the channel inline) - is there such a thing and I'm just missing it? that way I wouldn't have to click around into various logs when I'm trying to figure out what's going on with vscode - I realize I could tail the various files and write a script to make that more convenient

I was also thinking maybe an extension could fill that need but then I saw https://github.com/microsoft/vscode/issues/106993#issuecomment-694902345

**Comment by jcrben** [comment]
@sandy081 there are only 10 open issues tagged output - altho this issue is about output and got labeled debug instead - I looked at the debug tagged issues too and didn't see it - should I create one?

https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Aoutput+
