### ISSUE TITLE
Debugger does not function correctly when file is not selected

### ISSUE THREAD

**Issue by pconklin** [Microsoft/vscode#1624]
When the file you are debugging is not selected, it briefly will flash to the file you are debugging, then go back to what was selected with an error "unable to open 'XXX': Invalid arguments".  The debugger still continues to work as expected, but the file does not gain focus until you manually do so.  Debugger is an EXE.  Attached is a log of the JSON back and forth from VS Code and my EXE.
[test.txt](https://github.com/Microsoft/vscode/files/71382/test.txt)

**Comment by bpasero** [comment]
Not sure I follow the issue, please follow up @isidorn

**Comment by isidorn** [comment]
@pconklin the description is not very clear to me
* what is your use case? Are you building a new debug adapter?
* can I somehow reproduce this issue on my side?

The file only gets focus if you vscode gets a stopped event for that file.

**Comment by pconklin** [comment]
I am building a new debug adapter.  I quickly wrote a wrapper for the mockdebug
and found my issue.  somewhere along the way my int for the line number was
getting cast to a string.  This was causing the odd behavior i was seeing (the
quick flash of the actual source as well as the error).  Correcting this to an
Int resolved the issue.  You can reproduce by doing the following
 
have at least 2 scripts / program files
in your launch profile, have it launch program a
set the current open document to program b
have your debugger return a string instead of an int for line number
hit f5
 
You will see program a come up for a split second, then it will go back to
program b and you will get the error.  If you manually set focus to program a,
the executing line (highlighted in yellow) will follow along with the debugger
but will not scroll.

**Comment by isidorn** [comment]
If I understand properly sending the expected value (a number) fixes the issue, correct me if I am wrong. So i believe this is expected behavior since we are currently not checking any of the values passed from the adapter for validity.

The underlying issue happens when the wrong line number gets propagated all the way down to our editor service which complains that it can not open a line number which is a string.

Also feel free to ping for other debug adapter related questions.

**Comment by sstjohn** [comment]
I hit this issue as well, suggesting a more descriptive error would be helpful. It's extremely confusing that vscode obviously opens the file and even highlights the correct line before reverting all that work with such a generic message.
