### ISSUE TITLE
Incorrect function folding

### ISSUE THREAD

**Issue by dimal97** [Microsoft/vscode#16243]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|python|donjayamanne|0.3.21|
|debugger-for-chrome|msjsdiag|0.5.1|
|vscode-react-native|vsmobile|0.2.2|

---

Steps to Reproduce:
[http://ideone.com/WaSwWC](url)
1.  When you fold the first sample the code of second sample will get folded as well
2. If you make indent the same this issue will go away

**Comment by chrmarti** [comment]
@dimal97 I cannot access the linked document. Note that folding is indentation-based.

**Comment by dimal97** [comment]
Thanks, than if folding is indentation-based there is no bug
