### ISSUE TITLE
Web: Welcome banner appears below titlebar

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#162424]
![screenshot](https://user-images.githubusercontent.com/22350/193050880-b3d4ffb9-4c1b-4856-867b-4913629f2282.png)

On the web, should it appear always at the top?

Or should we separate the welcome banner from the cookies banner in vscode.dev, and just make the latter an isolated part of vscode.dev?

**Comment by sbatten** [comment]
I have pushed a change to move the banner above the title bar in the web only.

**Comment by joyceerhl** [comment]
:+1: 
<img width="1337" alt="image" src="https://user-images.githubusercontent.com/30305945/198157023-fd384dc6-31bd-4a98-b130-b440400d7da9.png">
