### ISSUE TITLE
File seems to be binary and cannot be opened as text

### ISSUE THREAD

**Issue by Kamasah-Dickson** [microsoft/vscode#162415]
Type: <b>Bug</b>

  I cant change any settings or enable autosave in vscode  again.....vscode keeps on sending this error message  "File seems to be binary and cannot be opened as text"

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 CPU         T5500  @ 1.66GHz (2 x 1663)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|2.49GB (0.14GB free)|
|Process Argv|--crash-reporter-id aba6172b-7f12-4b92-95a7-d73090556af1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
codesnap|adp|1.3.4
vscode-tailwindcss|bra|0.8.7
mobileview|cir|0.0.7
vscode-markdownlint|Dav|0.48.1
jshint|dba|0.11.0
gitlens|eam|12.2.2
vscode-npm-script|eg2|0.3.28
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.9.0
code-runner|for|0.11.8
terminal|for|0.0.10
copilot|Git|1.49.6911
vscode-pull-request-github|Git|0.51.2022090509
live-sass|gle|5.5.1
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.20.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
indenticator|Sir|0.7.0
sass-indented|syl|1.8.22
intellicode-api-usage-examples|Vis|0.2.4
vscodeintellicode|Vis|1.2.27
vscode-svg-previewer|vit|0.7.0
vscode-icons|vsc|11.18.0
quokka-vscode|Wal|1.0.504
vscode-webhint|web|2.1.3
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by bpasero** [comment]
It is possible that your settings file got corrupted maybe? Are you able to run this command: "Open User Settings (JSON)"?

**Comment by Kamasah-Dickson** [comment]
> It is possible that your settings file got corrupted maybe? Are you able to run this command: "Open User Settings (JSON)"?

No user settings(JSON) was not possible to access, error kept on popping so I uninstalled Vscode and installed again and still the same thing was happening. so I went into  local disk C users and deleted vscode manually because it left some files due to my last  uninstallation . after doing this I downloaded a new vscode and its now up and running now

By the way thank you for reaching me.
