### ISSUE TITLE
Command or API to replace tokens (${workspaceRoot}) with proper values in config items

### ISSUE THREAD

**Issue by DonJayamanne** [Microsoft/vscode#16247]
- VSCode Version: 1.7.2
- OS Version: N/A

I can't remember, the API or command used to resolve tokens (such as ${workspaceRoot} etc) in a given string (in config settings).
Looked around the documentation but couldn't find it.

**Comment by isidorn** [comment]
http://code.visualstudio.com/docs/editor/tasks#_variable-substitution

@gregvanl this document should be moved out of tasks into some parent document which should be linked from debug and tasks both
