### ISSUE TITLE
Settings editor open with no scope selected

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#162467]
I just opened the settings editor and searched for a setting, and nothing is selected in the picker:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/323878/193346037-82956d84-a58b-4ba9-95c9-1f16a5395885.png">

I was just messing with profiles earlier. Is it possible that there is a profile scope selected which doesn't actually exist in this window?

**Comment by roblourens** [comment]
(it should look like this, in this theme):

<img width="758" alt="image" src="https://user-images.githubusercontent.com/323878/193346162-b5a1cdd5-a9fa-467d-b201-8053696c44b9.png">

**Comment by rzhao271** [comment]
Unable to repro. Let me know if you still see the issue.
