### ISSUE TITLE
Don't reversibly discard changes when renaming a file or folder

### ISSUE THREAD

**Issue by dougabugg** [Microsoft/vscode#16240]
The editor currently warns the user that their unsaved changes to an open file will be discarded if they rename the file or a folder containing the file. The dialog displaying this warning has the default action result in irreversible data loss.

I propose changing this behavior, either by changing the default action to cancel the renaming operation, or some how preventing the discarding of unsaved changes during this operation.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/11997
