### ISSUE TITLE
Add close window option to continue dialog

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#162440]
I like the improved "All done. You can close this tab now."-dialog but I think it is missing a "Close Tab" option. Today, when everything works you need to hit "Cancel" but I don't have the close tab option - which is what the title suggests

**Comment by meganrogge** [comment]
what are the steps to trigger this?

**Comment by joyceerhl** [comment]
Use Continue On > Reopen on the Desktop from insiders.vscode.dev/github/microsoft/vscode
