### ISSUE TITLE
Provider a better completion navigation/details interaction

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode#16241]
Completion items (e.g. as produced by a language server) can provide 'big' documentation strings. It would be nice to display these big strings in a popup side-panel in a manner similar to how Eclipse does this.

It's actually one of the few ways in which Eclipse ui is 'better' than many other an IDE. Seeing the full doc for the method or type you are completing on easily accessible right next to the completions menu is, in my opinion, really convenient.

vscode right now shows a kind of 'shortened' version of the documentation (which can look really uggly, depending on whether the original source looks good when you just strip out newlines to attempt to display it on a single line). vscode also provides a little 'info' button you can click which opens the 'detailed' view of the docs. This is not very convenient because the extra clicks and context switch between completions view and 'details view' makes it rather hard to navigate quickly between completions and see their respective docs before making a choice on which completion you really wanted to pick.

Note: somewhat related. It would be nice if the 'side view' was capable of rendering markdown properly. But perhaps that is really a separate issue. And maybe it is covered already by this issue ticket:

https://github.com/Microsoft/language-server-protocol/issues/137

**Comment by joaomoreno** [comment]
The current design was an explicit decision: we want less popups in our source code.

**Comment by kdvolder** [comment]
That sounds good and I appreciate the 'limit the popups rule'. 

So, I agree with your rephrasing. However, please don't rule out using a well-placed popup, just because its a popup when you consider how to actually implement it. 

Popups can be annoying sure. But I don't think they are annoying by definition. A popup which shows some interesting information without being annoying/intrusive is actually a good popup.
 
The documentation side view 'popup' as I'm used to it from Eclipse, i.m.o is actually a pretty good design because:

a)  it doesn't reduce the vertical scroll area available for showing the completion items themselves
b)  it gives a fair amount of space to displaying big docs without feeling intrusive or annoying
c)  it doesn't make the completion items 'jump around' vertically to insert the extra details / docs inline into the completions list

**Comment by kdvolder** [comment]
BTW: Eclipse's 'side-view popup' is position and sized so that it aligns nicely with the completions menu. Perhaps this is a big part of why it 'feels good'. The alignment makes it feel and look more like the side-view and completions menu are a 'single popup' rather than two separate popups. So I could also imagine a single-popup design which has some extra-space to the side to show details. From user point of view that would be functionally equivalent (and doesn't violate your 'only one simultaeous popup' rule).

**Comment by ramya-rao-a** [comment]
@joaomoreno @jrieken I believe we can close this issue as we now can have the docs open to the side of the completion list.

**Comment by kdvolder** [comment]
That's right, it works very nicely now :-)
