### ISSUE TITLE
Navigate to test when left-clicking it

### ISSUE THREAD

**Issue by jepperaskdk** [microsoft/vscode#162504]
Can you make it so that left-clicking a test in the "test tree view", navigates you to that test?
You already have the "Go to Test" button, but it would be easier if it just navigated when left-clicking the test. 
It already does this when clicking failed tests.

**Comment by connor4312** [comment]
We did this in the initial versions of testing in VS Code, but later removed this behavior, because we want to allow users to easily select tests to run without losing context of their current editor.

**Comment by jepperaskdk** [comment]
Thanks @karthiknadig !

@connor4312 , from my own experience I use the navigate feature much more than selecting tests (which you would do with a ctrl+click right?). Double-click to navigate could also be a solution I suppose.
