### ISSUE TITLE
Suggestions for search function in vscode

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#1625]
it's very convenient for me to search keywords in vscode , but When I clear the search keywords, it does not clear the search result .
![n1](https://cloud.githubusercontent.com/assets/15098626/11989069/6344324e-aa32-11e5-883b-15be56755d5f.png)
![n2](https://cloud.githubusercontent.com/assets/15098626/11989070/6a1debaa-aa32-11e5-935a-ad8176bac575.png)

**Comment by bpasero** [comment]
We leave the search results because you might want to start a new search based on some results. There is still an action to clear the search results in the top right corner.
