### ISSUE TITLE
Add EOL to automatically created json files in `.vscode` folder

### ISSUE THREAD

**Issue by mfbehrens99** [microsoft/vscode#162548]
Whenever I change a workspace setting, VS Code creates this `settings.json` file. However, it never adds a EOL to the last line, about which at least GitHub desktop complains. I would highly appreciate this small little change.

Thank you for your time ;)

**Comment by aeschli** [comment]
Do you have the setting `"files.insertFinalNewline": true` ?

I just verified that if I have that setting, also the newly created `settings.json` will have the final new line.
