### ISSUE TITLE
Go to definition crashes with "Cannot read property 'startLineNumber' of undefined" message

### ISSUE THREAD

**Issue by wiz** [Microsoft/vscode#16259]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

Steps to Reproduce:

1. Ask a language server for definition location
2. LS emits following JSON:
    ```json
    {
        "result": {
            "location": {
                "uri": "untitled:Untitled-1",
                "range": {
                    "start": {
                        "line": 0,
                        "character": 0
                    },
                    "end": {
                        "line": 0,
                        "character": 1
                    }
                }
            }
        },
        "jsonrpc": "2.0",
        "id": 29
    }
    ```
3. VS Code shows warning about startLineNumber property

There's a stack trace in console:

```
Cannot read property 'startLineNumber' of undefined: TypeError: Cannot read property 'startLineNumber' of undefined
    at Function.e.collapseToStart (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:39:8028)
    at file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:77:26260
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:10217)
    at Object.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:13795)
    at _run (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15623)
    at _completed (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:15064)
    at u (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:18602)
    at Y.then.r.(anonymous function) (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:18819)
    at Object.g [as _notify] (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:10217)
    at Object.enter (file:////usr/share/code/resources/app/out/vs/workbench/workbench.main.js:31:13795)
```

----

For some reason callback receives mangled URI with lots of undefineds (taken from debugger as early as 3rd frame at the bottom of the stack):
```json
{
    "seq": "99",
    "res": {
        "uri": {
            "scheme": "",
            "authority": "",
            "path": "undefined",
            "fsPath": "undefined",
            "query": "",
            "fragment": "",
            "external": "undefined",
            "$mid": 1
        }
    }
}
```

Maybe similar to #12353

**Comment by chrmarti** [comment]
@wiz Which language server is this? The TypeScript one? Looks like a problem with the language server itself if I understand correctly?

**Comment by wiz** [comment]
@chrmarti I'm writing a test language server of my own, checking out the LSP features.

**Comment by dbaeumer** [comment]
@wiz: in the LSP uri are defined as strings. If you have a VS Code URI in hand you need to convert it using URI.toString(). If you want to restore a full URI in the server you can use the vscode-uri npm package to do so.

Can you share your code. Otherwise it is hard to say what is not working. All this works in other LSs

**Comment by wiz** [comment]
```
            "uri": "untitled:Untitled-1",
```
That was the URI I've got from the wire in [Goto Definition Request](https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#goto-definition-request).

**Comment by dbaeumer** [comment]
@wiz, hard to say without being able to look at the code. You could enable tracing between the client and the server using `'your client id'.trace.server: "messages"` (or "verbose"). For example for ESLint the setting is `"eslint.trace.server": "messages"`

**Comment by wiz** [comment]
There's a message hardcopy from the trace in the opening post. When the editor receives it, error happens.

**Comment by dbaeumer** [comment]
@wiz: I saw that but the problem is that:
```
{
    "result": {
        "location": {
            "uri": "untitled:Untitled-1",
            "range": {
                "start": {
                    "line": 0,
                    "character": 0
                },
                "end": {
                    "line": 0,
                    "character": 1
                }
            }
        }
    },
    "jsonrpc": "2.0",
    "id": 29
}
```
is valid according to the LSP and that 
```
{
    "seq": "99",
    "res": {
        "uri": {
            "scheme": "",
            "authority": "",
            "path": "undefined",
            "fsPath": "undefined",
            "query": "",
            "fragment": "",
            "external": "undefined",
            "$mid": 1
        }
    }
}
```
contains an invalid URI when send to VS Code main. I am not able to reproduce this locally so any additional tracing or code to reproduce this would be helpful.

**Comment by wiz** [comment]
The "seq" dump is from VS own internals. My result is the former, built according to LSP specs.

**Comment by dbaeumer** [comment]
@wiz: yes but my current interpretation is that the `"untitled:Untitled-1"` should have been converted to a VS Code URI successful. If I do Uri.parse('untitled:Untitled-1') I get

``` json
Uri {
  _scheme: 'untitled',
  _authority: '',
  _path: 'Untitled-1',
  _query: '',
  _fragment: '',
  _formatted: null,
  _fsPath: null }
```

Without steps it is very hard for me to say why you get:
```
"uri": {
            "scheme": "",
            "authority": "",
            "path": "undefined",
            "fsPath": "undefined",
            "query": "",
            "fragment": "",
            "external": "undefined",
            "$mid": 1
        }

```

**Comment by wiz** [comment]
Yeah.. It's difficult for me either. I've tried to pinpoint the source of such a message but it appears to enter the message loop from somewhere else.

Can you point me where to set breaks or something like that to help finding the cause? I'm using the LSP server wrapper from the example with only run/debug commands patched up to start my binary.

**Comment by dbaeumer** [comment]
A code location to set breakpoints is on the client side in the protocolConverter.js file in function toUri. This does all the string to URI conversion.

**Comment by wiz** [comment]
Okay, that was actually my fault. Thanks to @dbaeumer for the hint about `protocolConverter.js` and VS Code debugger the bug was resolved in no time.
The culprit was an extra `location` wrapper where it wasn't needed.

While I haven't found the `toUri` function in there the file itself was quite revelatory an I expect to consult it more in the future.

**Comment by dbaeumer** [comment]
@wiz good to hear that you were able to resolve it. And the name of the function I meant is `asUri` not `toUri`. Sorry about that.
