### ISSUE TITLE
inline "suggestions" or "descriptions" in VS environment that can't be removed

### ISSUE THREAD

**Issue by leooladimu** [microsoft/vscode#162527]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Type: <b>Performance Issue</b>

It's been going on for over a month. When I declare a variable or a function, a colored box that I can't get rid of appears in between, for instance, "let letters" and "= Array.from(word);" and the box contains some kind of extraneous suggestion or description that your product thinks I want, like ": any[]" in the above example. I've gone through every extension and linting functionality I'm aware of in my VS, and have been unable to get rid of these things. What the hell are they, and how do I get them off my screen when I'm working?

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:07:15.900Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|--crash-reporter-id 9e271b79-2471-42c3-9840-c75c30a7363a|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	   131	 22877	code main
    0	    66	 22880	   gpu-process
    0	    16	 22882	   utility-network-service
    0	    90	 23263	   shared-process
    0	    16	 23309	     ptyHost
    0	     8	 75100	       /opt/homebrew/Cellar/zsh/5.8.1/bin/zsh (figterm)
    0	     0	 75113	         /opt/homebrew/Cellar/zsh/5.8.1/bin/zsh --login
    0	   197	 75031	   window (repeatingTranslate.js — appAcademy)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (repeatingTranslate.js — appAcademy)
|    Folder (appAcademy): 126 files
|      File types: md(36) js(29) png(19) json(7) DS_Store(2) gitignore(1)
|                  prettierignore(1)
|      Conf files: package.json(3);
```

</details>
<details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
vscode-npm-script|eg2|0.3.28
el-vsc-product-icon-theme|ElA|0.1.8
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
path-autocomplete|ion|1.22.1
RelativePath|jak|1.5.0
fluent-icons|mig|0.0.18
vscode-docker|ms-|1.22.1
remote-containers|ms-|0.251.0
material-icon-theme|PKi|4.20.0
material-product-icons|PKi|1.4.1
pyro-icons|pyr|1.0.0
vscode-thunder-client|ran|1.19.3
java|red|1.11.0
synthwave-vscode|Rob|0.1.14
bunker|sld|1.1.6
vscode-icons|vsc|11.19.0
fig|wit|0.0.6
material-theme|zhu|3.15.5

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
i5d37513:30580093
pyindex848cf:30577861
40g7c324:30573242

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe these:

https://code.visualstudio.com/updates/v1_60#_inlay-hints-for-javascript-and-typescript

If not please paste a screenshot.

Also, it is unclear why you created this as a Performance issue.

**Comment by leooladimu** [comment]
That's totally them!! Only with the themes I like to use in my VS, these "hints" are utterly in the way (in RBE Matrix Skin Theme, for instance, they're bright yellow on an otherwise dark screen). I'll try to find and undo them in my settings right now, and if I do then I'll come close this issue. Many thanks!

**Comment by leooladimu** [comment]
Oh my God, dude. Why do I make my life so complicated? I absolutely remember having screwed around in my settings a while back for some reason, and clicking things -- that's totally what this was. Anyway, thanks! :)
