### ISSUE TITLE
Selection menu feedback

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16253]
Why is emmet in the selection menu?
Emmet should be moved into an extension and it should not have special treatment imho
Why is it so special to deserve a spot in the selection menu? How many of our users actually use emmet commands?

@ramya-rao-a @egamma

**Comment by chrmarti** [comment]
@isidorn Any selection related actions you would replace it with?

**Comment by egamma** [comment]
@isidorn there is strong feedback that emmet is not discoverable, many users do not even know that we bundle emmet. This independent from the technical implemenation as a separate extension or as part of the chore..

**Comment by egamma** [comment]
@chrmarti regarding

>Any selection related actions you would replace it with?

It isn't action but it isn't discoverable but selection related... users do not find how to make a block/rectangular selection ALT+SHIFT+Drag on Win. 

One idea would be to have an action like 'Start Block Selection' in the menu, may be you have other ideas.

**Comment by seanmcbreen** [comment]
Could we add the following to the selection menu - 
1. Insert Cursor at end of each selected line, shift+alt+i
2. select current line, Ctrl+i
3. select all occurrences of current selection, Ctrl+Shift+L
4. select all occurrences of current word, Ctrl+F2

All have keybindings - I listed the windows ones.

These are some of the more powerful multi-cursor ones.  Will need shorter name for some :)

**Comment by chrmarti** [comment]
Feedback from ZRH:
- move Select All over
- add Toggle Block Comment and Toggle Line Comment (from NPS survey)

Feedback from @gregvanl: Move Emmet actions to Edit menu.

**Comment by egamma** [comment]
@gregvanl has a valid point in #16297 we should not just put all the commands that we want to expose in the Selection menu, we should find the best spot in the existing menu structure. The Comment toggle commands should also go into the Edit menu and not the selection menu.

**Comment by egamma** [comment]
Regarding Emmet, one issue raised by @alexandrudima is that emmet actions are primarily useful in html, css. Emmet supports syntax profiles, but they do not exist for all languages. Therefore, we should consider moving the Emmet actions into the Context menu and only show it there when Emmet is applicable.

**Comment by egamma** [comment]
Regarding the block selection, there are several column selection related commands that are not even exposed in the command palette:
![image](https://cloud.githubusercontent.com/assets/172399/20825527/e884525e-b864-11e6-9633-6b056ddfe115.png)

We should expose them in the command palette and then also consider adding them in the selection menu probably in a submenu. This makes the column selection commands discoverable.

@alexandrudima

**Comment by alexandrudima** [comment]
@egamma I will create create `EditorAction` wrappers for them. Tracking in #16393

**Comment by chrmarti** [comment]
Included most of the feedback. Moved the Emmet commands to the Edit menu for now. Rectangular selection by mouse needs more thought on my side. @seanmcbreen On your suggestions:
1. Insert Cursor at end of each selected line -> 'Cursors at Line Ends' (in lack of a better idea)
2. select current line -> Command is not exposed (FYI @alexandrudima)
3. select all occurrences of current selection -> 'Select All Occurrences'
4. select all occurrences of current word -> Same command as above from what I see.

**Comment by chrmarti** [comment]
#16538 suggests to undo the move of Select All or have it in both the Selection and the Edit menu because users have come to expect it there. I'd suggest to keep it as is (only in the Selection menu), other opinions?

**Comment by chrmarti** [comment]
Closing with the latest:
![screen shot 2016-12-07 at 2 23 57 pm](https://cloud.githubusercontent.com/assets/9205389/20989263/ed245d68-bc88-11e6-89ca-6b7522b252d9.png)
and
![screen shot 2016-12-07 at 2 24 11 pm](https://cloud.githubusercontent.com/assets/9205389/20989271/f3f6d2ec-bc88-11e6-84cf-973d458aacb6.png)

Please open new issues for additional feedback.
