### ISSUE TITLE
Defer showing 'Resuming edit session' progress indicator till remote is resolved

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162540]
So can't you wait for the workspace to be resolved, then show the status bar item if there is an edit session to resume?

_Originally posted by @roblourens in https://github.com/microsoft/vscode/issues/161408#issuecomment-1260198636_

**Comment by roblourens** [comment]
If you specifically want to wait for the remote, then I think this what you want https://github.com/microsoft/vscode/blob/4c3c06f46d48f63a79a0f734ed45a8a0b8d28cde/src/vs/workbench/services/remote/common/remoteAgentService.ts#L29

I don't know what your code looks like but maybe there is a way to do it in a more generic way, like wait until you can talk to your service and know for sure whether there is an edit session, then show the status bar itemm.

**Comment by roblourens** [comment]
Actually, I'm not sure whether this is a result of some of the testing I've been doing or whether it's always like this, but I see the "Resuming edit session" status bar item in every window I open until the window has fully loaded, and these workspaces have never been used with edit sessions.

**Comment by bhavyaus** [comment]
Verified this for remote-ssh. Are there any other remote scenarios to verify?

**Comment by joyceerhl** [comment]
That should be sufficient. All other first party remote scenarios: Codespaces, WSL, Containers, Tunnels
