### ISSUE TITLE
Can't see Git Gutter in Windows.

### ISSUE THREAD

**Issue by kumarharsh** [Microsoft/vscode#16255]
- VSCode Version:1.8-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open any file
2. Make changes
3. No gutter change markers are visible. I have no zoom-level set. These are all my settings:
```
{
  "git.autofetch": false,
  "javascript.validate.enable": false,
  "editor.renderWhitespace": "all",
  "files.trimTrailingWhitespace": false,
  "eslint.nodePath": "ui/node_modules",
  "css.validate": false,
  "stylelint.enable": true
}
```

I think it broke somewhere around 1.7-insider, and I can't get it to work at all.

![2016-11-30](https://cloud.githubusercontent.com/assets/760112/20745488/9dc9a8f8-b707-11e6-9d76-c0e98e96cc39.png)

**Comment by bpasero** [comment]
@joaomoreno an issue with the dirty diff changes?

**Comment by joaomoreno** [comment]
What's your exact version? Commit id?

**Comment by kumarharsh** [comment]
It's been happening for quite some time (weeks) but I didn't find time to file an issue, or hoped that it'd get resolved... This is also happening in another Windows PC of a friend.

![image](https://cloud.githubusercontent.com/assets/760112/20757717/7745d752-b73d-11e6-9d2c-983cfd779056.png)

**Comment by joaomoreno** [comment]
Does the rest of the git integration work fine? Does it work in stable?

**Comment by kumarharsh** [comment]
Yes, the rest works (committing, diff view, etc)

**Comment by kumarharsh** [comment]
It doesn't work even in Stable:

![image](https://cloud.githubusercontent.com/assets/760112/20765643/2ef8ac9c-b759-11e6-90d6-f2e1f2b6139b.png)

**Comment by joaomoreno** [comment]
Does any git feature work at all?

**Comment by kumarharsh** [comment]
Yes, all other git features work: committing, changing branch, diff views, literally everything other than the git gutters is working.

I used the developer console to see what's going wrong, and it seems like the `<div class="git-dirty-added-diff-glyph">` which marks the gutter is missing.

**Comment by kumarharsh** [comment]
Also, I just upgraded my stable vscode installation to 1.7.2, and the gutters are working there. But still no luck in the latest insiders version.

![image](https://cloud.githubusercontent.com/assets/760112/20771021/caa48d46-b76d-11e6-9abc-9415c3510544.png)

**Comment by joaomoreno** [comment]
Thanks for inspecting the DOM, that's helpful to know.

If you open the DevTools, with sourcemaps enabled, you should be able to open `gitContentProvider.ts` (using <kbd>Ctrl O</kdb>) and put a breakpoint on line 36. When you then, back in Code, switch to another file under SCM, does the breakpoint get hit?

![image](https://cloud.githubusercontent.com/assets/22350/20771496/f4aaa694-b749-11e6-8a9a-6d6818c91743.png)

**Comment by kumarharsh** [comment]
Yes, the breakpoint does get hit.

**Comment by joaomoreno** [comment]
Interesting. Does it hit line 40? And 51?

**Comment by kumarharsh** [comment]
No, it doesn't. neither one gets hit.

**Comment by joaomoreno** [comment]
What about 56? Does it return immediately there?

**Comment by kumarharsh** [comment]
L56: `triggerModelUpdate` is not being called.

**Comment by joaomoreno** [comment]
When checking, always make sure 36 gets hit. It's impossible for line 36 to hit and 56 not to.

**Comment by kumarharsh** [comment]
@joaomoreno it's definitely not hitting 56, even after 36 is hit.

**Comment by kumarharsh** [comment]
![vscode-bug](https://cloud.githubusercontent.com/assets/760112/20827916/c6dd79c4-b89a-11e6-8a97-5164c6362ac4.gif)

**Comment by joaomoreno** [comment]
Odd, can you Step after 36, instead of Play? Further down it should call `triggerModelUpdate`. Something must be throwing up an error.

**Comment by kumarharsh** [comment]
No errors are thrown as far as I can see... See the GIF:
![vscode-bug](https://cloud.githubusercontent.com/assets/760112/20830496/bb20d750-b8a6-11e6-806f-d05f871ae117.gif)

**Comment by joaomoreno** [comment]
I was able to reproduce, will push a fix soon. Thanks for the help!

**Comment by jrad88** [comment]
4af3d17

This has been driving me nuts for weeks.  I've had no gutter info on all of my projects, and I couldn't for the life of me figure out what was wrong.  

I reverted this in source and they are working for me again.  The interesting thing about my case is that the paths are UNC paths, on a shared folder.  So \\Other-PC\Path\To\Repo.  The replacement here is breaking the gutters for my files.  Without it, they work.

Can someone find a better solution here?  For reference, mapping the directory to a drive and opening it from there (e.g. Z:\Path\To\Repo) works also, but this isn't going to be a long term solution for me.
