### ISSUE TITLE
Error stripe ignores scale display settings

### ISSUE THREAD

**Issue by hjkta** [microsoft/vscode#162563]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.71.2 (user setup)
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Change scale to 125% in Display Settings (Windows 10 Control Panel)
2. Write something that appeals as error/warning:
![image](https://user-images.githubusercontent.com/2868392/193560546-61122192-030c-4e56-969c-f98d9864c565.png)
3. Expected behavior:
![image](https://user-images.githubusercontent.com/2868392/193560974-3844240a-fbe7-4756-9d60-c6c24a50bb4c.png)

**Comment by rzhao271** [comment]
I'm unable to repro, but I'm also on Windows 11.
Is this issue still occurring for you on the latest [Insiders](https://code.visualstudio.com/insiders)?

**Comment by hjkta** [comment]
I can't reproduce it anymore. May be fixed now.

**Comment by rzhao271** [comment]
Closing for now. Let me know if it reappears again
