### ISSUE TITLE
After installing the latest version of Visual Studio Code - Insiders, Vim-like extension can't change cursor's style normally

### ISSUE THREAD

**Issue by xekri** [Microsoft/vscode#16254]
- VSCode Version: Code - Insiders 1.8.0-insider (2bd85b81138984acd08983df4cb2fbdc1c41aa4d, 2016-11-30T07:05:07.830Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vimStyle|74th|0.4.1|
|format-indent|Kasik96|1.3.0|
|material-icon-theme|PKief|1.1.4|
|code-settings-sync|Shan|2.3.8|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|theme-atom-one-dark|andischerer|0.0.1|
|alignment|annsk|0.3.0|
|amvim|auiworks|1.17.5|
|vscode-icontheme-nomo-dark|be5invis|1.2.0|
|npm-intellisense|christian-kohler|0.1.4|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|jquerysnippets|donjayamanne|0.0.1|
|vscode-html-css|ecmel|0.0.30|
|Theme-Blackboard|gerane|0.0.2|
|vue-snippets|hollowtree|0.0.8|
|RelativePath|jakob101|0.11.0|
|Angular1|johnpapa|0.1.16|
|vscode-autoprefixer|mrmlnc|2.0.0|
|vscode-postcss-sorting|mrmlnc|2.1.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|vetur|octref|0.1.0|
|vscode-icons|robertohuertasm|4.0.4|
|stylelint|shinnn|0.20.2|
|vim|vscodevim|0.4.4|
|cordova-tools|vsmobile|1.2.3|
|JavaScriptSnippets|xabikos|1.2.0|

---

When enable any Vim-like extension(amVim, Vim, vimStyle, etc.), the cursor turns block style, and it can't be changed by setting `"editor.cursorStyle": "line"`.

**Comment by xekri** [comment]
Confirmed there's no such bug in the latest public version of Visual Studio Code.

**Comment by rebornix** [comment]
@xekri thanks for reporting this issue. Fixed via https://github.com/Microsoft/vscode/commit/c18c58d0b089b61768c1b4201bd15db2c9a54c96

**Comment by rebornix** [comment]
To verifiers: Install whatever Vim extension on the marketplace or your own Vim ext to see if the cursor is changed when you switch between Normal and Insert Mode.
