### ISSUE TITLE
sbsbsbsbsb

### ISSUE THREAD

**Issue by LordLaffey** [microsoft/vscode#162509]
Type: <b>Bug</b>

sbsbsbsbsbsbsbsbsbsbsbsbsbsbsbsbsbsbsb

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.51GB free)|
|Process Argv|--crash-reporter-id 5f30e01c-0c95-41b9-9583-7d7e4b9aeae1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-command-runner|edo|0.0.122
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
copilot|Git|1.49.6911
vscode-clangd|llv|0.1.21
background-cover|man|2.3.0
vscode-filesize|mkx|3.1.0
vscode-language-pack-zh-hans|MS-|1.71.9140930
vsliveshare|ms-|1.0.5733
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.20.0
shadow-reader|rai|0.8.1
errorlens|use|3.6.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30557514
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
i5d37513:30580093
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by qingchenling** [comment]
what a pity problem

**Comment by Ptilopsisw** [comment]
what a pity!
