### ISSUE TITLE
Markdown Preview showing information not on actual markdown

### ISSUE THREAD

**Issue by subash-poudel** [microsoft/vscode#162520]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

This might not be an issue at all and even if it is it's too minor.

Steps to Reproduce:

1. Open a markdown
2. Start a code block
3. The last line in preview is something like <p data-line="44" class="sync-line" style="margin:0;"></p>
4. On github the <p> tag is not shown.

## Screenshot
<img width="1342" alt="Screen Shot 2022-10-02 at 7 42 17 PM" src="https://user-images.githubusercontent.com/1780107/193457949-c87a43d2-0759-495b-9357-915974274807.png">

**Comment by mjbvz** [comment]
Your markdown is likely invalid. Can you please share the complete example file as text

**Comment by subash-poudel** [comment]
@mjbvz The minimum sample to reproduce this:
`
## tech-dictionary-entities
 ``` 
  -> Category
        -> id
        -> name
        -> desciption
        -> url
  -> Sub-Category
        -> id
        -> name
        -> desciption
        -> url
  -> Item
        -> id
        -> name
        -> desciption
        -> mdFileContent
        -> url

`
```

**Comment by mjbvz** [comment]
Works fine for me in VS Code insiders:

![Screen Shot 2022-10-04 at 8 27 53 PM](https://user-images.githubusercontent.com/12821956/193975200-18179cf6-baff-4b02-9afa-bb22b4865040.png)

Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
