### ISSUE TITLE
Function Parameters show XML instead of parsed XML in description part.

### ISSUE THREAD

**Issue by sorab2142** [Microsoft/vscode#16252]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|python|donjayamanne|0.5.2|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Go|lukehoban|0.6.45|
|cpptools|ms-vscode|0.9.1|
|omnisharp|ms-vscode|0.3.3|
|vscode-icons|robertohuertasm|4.0.2|
|unity-debug|Unity|1.1.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1. Trigger autocomplete on function parameters
2. Notice that instead of parsing xml, the xml itself is visible in the description part.

![image](https://cloud.githubusercontent.com/assets/3336237/20743520/e50c9834-b6fc-11e6-9b5b-2b6f57239bf3.png)

**Comment by chrmarti** [comment]
Not sure if that's on our side. @joaomoreno ?

**Comment by joaomoreno** [comment]
This is an issue with the extension providing the contents to the parameter hints: [omnisharp](https://github.com/OmniSharp/omnisharp-vscode).

**Comment by chrmarti** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1003
