### ISSUE TITLE
Markdown Link Validation Fails for Header Containing Link

### ISSUE THREAD

**Issue by tapiester** [microsoft/vscode#162677]
Type: <b>Bug</b>

Make a markdown file with a link to a header that itself has a link in it. VS Code will show a warning "link.no-such-header-in-own-file" even though clicking on the link in the preview window works correctly.

Example file:
```
# Example File

[link to header](header-with-link)

## [Header with Link](https://fake.website/)
```

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.20GB (16.82GB free)|
|Process Argv|D:\\source_git\\TaskOrchestrator\\Documentation\\ReleaseMatrix.md --crash-reporter-id f9b587d4-8f78-41c0-a7e1-0677d6f0db76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.48.1
mdmath|goe|2.7.4
plantuml|jeb|2.17.4
csharp|ms-|1.25.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by mjbvz** [comment]
```
[link to header](header-with-link)
```

Doesn't seem valid as it will be treated as a file link. You need the `#` to link within the file:

```
[link to header](#header-with-link)?
```

And also test this using VS Code insiders (1.72) as I'm not sure this specific example would have worked in 1.71
