### ISSUE TITLE
"follow links" in the same workspace over the "Remote SSH" do not work due to read only FS.

### ISSUE THREAD

**Issue by hellt** [microsoft/vscode#162647]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.71.2
- OS Version: Ubuntu 20.04.2 LTS (Focal Fossa)

Hi, I am using "Remote SSH" extension and since some version the "Follow link" function stopped working for relative URLs provided in the same repo.

Consider the following file that I create in my workspace

```markdown
## test1

refer to [test1](#test1)
```

When I try to follow this link, I got an error that the file couldn't be opened, due to the read-only FS. Check this animation

![2022-10-04_11-33-41 (1)](https://user-images.githubusercontent.com/5679861/193786322-262bdac3-775f-445f-ae36-fc3c5bca7911.gif)

**Comment by mjbvz** [comment]
This should already be fixed in the current VS Code insider builds
