### ISSUE TITLE
Expose a function in registerHoverProvider to override existing hover documentation

### ISSUE THREAD

**Issue by Kokujou** [microsoft/vscode#162605]
I'm currently writing a vscode extension to improve type detection of typescript. in the frontend framework i'm using there are scenarios where typescript detects type any, but a better type can be inferred from the context.

now, sadly there is no possibility to overwrite a certain type in VSCode, because this IDE doesn't even know the types itself, as i understood it depends on plugins providing certain UI features like hover, completion, definition, type definition, and stuff.

now that leads me to the `registerHoverProvider` function. when hovering over said variable you see the typescript documentation, and now i added a hover provider to override that, but now it prints a second line and it looks like this

![grafik](https://user-images.githubusercontent.com/13001250/193661208-58b795ae-9e77-4340-94cf-8f47fcddd21d.png)

a lot of the already exported "registerXXXProvider" already allow a function for overriding and/or deleting a single item, so it shouldn't be a problem.

please consider it and fix it as soon as possible.

**Comment by mjbvz** [comment]
Have you considered using a [TypeScript language service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin) instead to override the hover that TypeScript shows?

**Comment by Kokujou** [comment]
sadly that's for some reasons not possible, maybe that's also something i could ask here, 
i was never able to get a typescript language service plugin to work with javascript files in a code-workspace. 
i thought vscode is using typescript also for javascript files, but apparently it's not.

sorry, i think i should've started with that information.
btw the frontend framework i'm using is lit-html. what i'm trying to accomplish is: I'M parsing the javascript-html render code as HTML, looking for the component definition, getting the type of the property which is mapped to a certain attribute, or the event which is dispatched and this is how i can infer the type which is "any" by default

the problem arises when i have an expression like this:

```js
return html`<my-compoennt @my-event="${(e)=>{...}}"></my-component>`
```
```

e implicitly has type any, but every developer knows that e is at least an Event, and if @my-event is not native it's a CustomEvent and when finding the dispatch code in the component source we can even infer the type parameter in CustomEvent<T>, this is what i'm trying to accomplish.

**Comment by jrieken** [comment]
> lot of the already exported "registerXXXProvider" already allow a function for overriding and/or deleting a single item, so it shouldn't be a problem.

Can you explain what you mean by that? We generally don't allow extensions to suppress other extension's results and we honestly have no plans of supporting that. It's user-choice to install/uninstall or configure extensions and extensions shouldn't overrule that. 

As suggested earlier, esp since you refine existing TS/JS behaviour, you should be using a tsserver-plugin

**Comment by Kokujou** [comment]
registerCompletionProvider, and i think also some symbol providers and registerDocumentSemanticTokensProvider already have a method in the provider that can transform or nullify existing tokens/completions
so why not just do it also for hover? i mean in the end it's a plugin and if a user is not satisfied with what it does, then they can report it and/or uninstall it.

i have a similar problem for diagnostics, that one i understand because obviously a plugin can only discuss it's own diagnostic collection and i also need to deal with it, but at least for the rest you could offer an interface. 

for some reasons i cannot use a typescript plugin, because it doesn't work well together with a javascript project and a typescript plugin seems to have no effect on the TSC command line command which i'm using to run tsc --watch on my whole solution to get project-wide errors (vscode sadly doesn't support realtime workspace error checking)

**Comment by jrieken** [comment]
> registerCompletionProvider, and i think also some symbol providers and registerDocumentSemanticTokensProvider already have a method in the provider that can transform or nullify existing tokens/completions

Sorry, that's a misunderstanding. Completion providers cannot do that. They, and some others, can only refine their own item by enriching them but they cannot nullify any item

**Comment by mjbvz** [comment]
@Kokujou  TS service plugins work for JS too. The typescript  service is used for both JavaScript and TypeScript IntelliSense in VS Code

**Comment by Kokujou** [comment]
yes, but it's not working with the tsc command apparently... but i guess at least i can work around it by appending a file system listener to every file in the work space using the vscode plugin and then have a ts plugin in addition... 
architecturally this is quite questionable but i guess there's no better way around it
