### ISSUE TITLE
merge `Open File` and `Open Folder` into one

### ISSUE THREAD

**Issue by scarf005** [microsoft/vscode#162632]
![image](https://user-images.githubusercontent.com/54838975/193737267-db072961-94bd-4a5c-8037-4183517dfea5.png)

afaik Mac version only has `open`, which can open either open files or directories.
however, Linux version has two different option, `Open File` and `Open Folder`, which is very frustrating to use because what if i wanted to open a directory but accidently pressed `Open Folder` and vice versa?
at least an option to merge the both one as `Open` would be great.

vscode version:
```
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic
Sandboxed: No
```

**Comment by lramos15** [comment]
I think this is a limitation of the native APIs, cc @bpasero

**Comment by bpasero** [comment]
Only macOS allows to pick files and folders at once from the native dialog. We would have to use the custom file picker maybe for this case, not sure whether it is supported @alexr00

**Comment by alexr00** [comment]
The simple file picker does support this, but I assume that the Open commands are contributed based on the OS.

**Comment by scarf005** [comment]
maybe it could be resolving by using this [solution](https://stackoverflow.com/a/45154209) to relevent [electron code](https://github.com/electron/electron/blob/a0dbae72c8b2d192835e01798dd4241e67a5f44f/shell/browser/ui/file_dialog_gtk.cc#L344-L360)?
