### ISSUE TITLE
Build: Process artifacts step stuck

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#162657]
Notice how in [this pipeline run](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=187673&view=logs&j=43b54640-f671-5524-8f7b-714d77229de9&t=8c631bd7-3091-56a7-0716-a38699ccbe61&s=380ab8c6-4139-55ff-15c4-fb48260f4dca) the `Process artifacts` step was stuck in the following line for at around 2 hours:

```
Processing artifact: 'vscode_server_win32_x64_archive. Downloading from: ...
```

This could either be from `Invoke-RestMethod` or from `Expand-Archive`. Maybe we should put a log between those. In any case, my bets go against the former... which can be resolved with the [`-TimeoutSec`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.2#-timeoutsec) option. WDYT?

cc @lszomoru

**Comment by TylerLeonhardt** [comment]
> which can be resolved with the [-TimeoutSec](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-7.2#-timeoutsec) option.

You're a PowerShell pro now!
