### ISSUE TITLE
diff editor code action widget ENTER keybinding not working

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#162601]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:
 
1. make a change in a TS file in git repo like (one that will give you a lightbulb with):
<img width="1677" alt="image" src="https://user-images.githubusercontent.com/2644648/193651508-4fccc050-e140-433e-b549-7639e8d59bc5.png">
2. open the code action widget with cmd+dot
3. Try hitting ENTER to accept first option

Unfortunately for me, nothing seems to happen... but this works in a non-diff editor just fine.

**Comment by mjbvz** [comment]
This likely has the same root cause as #162479
