### ISSUE TITLE
Find a better name for 'sticky scroll'

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#162637]
I really love the sticky scroll feature, should be on by default!
I just spend minutes going thorough all the settings as I forgot the name of the feature. The name `sticky scroll` doesn't 'stick' with me at all :-)
sticky scroll sounds like a variant of scrolling. But it's not really related to scrolling, it's available any time you are somewhere in the code, regardless how you got there.

Maybe `context header` ? `Outline header` ?

**Comment by jrieken** [comment]
I quite like the name because it is catchy but also because to me it is a variant of scrolling: while you "scroll" some bits "stick" around until you scroll further

**Comment by babakks** [comment]
My opinion is close to @aeschli, partly because it's more related to breadcrumbs than scrolling.

**Comment by jrieken** [comment]
closing without action
