### ISSUE TITLE
Run task is really slow

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#162600]
![Recording 2022-10-03 at 14 21 23](https://user-images.githubusercontent.com/4544166/193650330-1769370f-a6e3-4ecb-a4df-d206200fa5e3.gif)

Here is me triggering run task, it pops up very slowly in todays insiders.
[Profile-20221003T142425.json.zip](https://github.com/microsoft/vscode/files/9699983/Profile-20221003T142425.json.zip)

**Comment by meganrogge** [comment]
This is most likely because we have to wait for many things before we can provide tasks. Do you see in the status bar an extensions loading spinner?

**Comment by lramos15** [comment]
No the spinner only flashes for like one millisecond. I notice it's slow only when in a repo with just NPM tasks.

**Comment by meganrogge** [comment]
which repo are you in there?

**Comment by lramos15** [comment]
> which repo are you in there?

https://github.com/microsoft/vscode-gdpr-tooling

**Comment by meganrogge** [comment]
this has started happening recently for you, correct?

**Comment by FairlieAgile** [comment]
I am also experiencing this since updating to the latest VS code version (1.72)

**Comment by meganrogge** [comment]
@FairlieAgile can you share your tasks.json file?
