### ISSUE TITLE
Show an icon inside explorer to open files to the side

### ISSUE THREAD

**Issue by fbnlsr** [Microsoft/vscode#16260]
Right now it is possible to open a file in a split-pane view when using the `cmd+P` palette.

It would be nice if we could have the split-pane icon appear when overing a file on the Explorer and be able to click it so that it opens in a new split-pane view. That function is already available by right-clicking and selecting "open to the side" but an icon would be much more user-friendly.

**Comment by bpasero** [comment]
@fbnlsr try Ctrl+click / Cmd+click to open to the side directly from the explorer.

**Comment by fbnlsr** [comment]
Thanks @bpasero !

Do you think it'd be overwhelming to have an icon like I suggested?

**Comment by bpasero** [comment]
@fbnlsr that is true because the opened editors pane is about revealing a file that is already associated to a group. Though I do not see why we would not want to support the same keybinding there. @isidorn any objections?

**Comment by isidorn** [comment]
Cltr + cmd click in opened editors to open to the side makes perfect sense

**Comment by bpasero** [comment]
@isidorn ok, pushed via https://github.com/Microsoft/vscode/commit/0a4565de3576561e20b75c04ca787bb5712b4968
