### ISSUE TITLE
Ctrl key doesn't work on Windows if when remapped

### ISSUE THREAD

**Issue by kasajian** [microsoft/vscode#162629]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
- OS Version: Windows 11 

Steps to Reproduce:

1. Remap the Caps-lock key to either the Left of Right Ctrl key.   Although this can be done through the registry, it's easier to use a tool such as [SharpKeys](https://github.com/randyrants/sharpkeys).   You have to restart the computer.
  1.1 When you do this, you'll be able to use the Caps-Lock key a duplicate of the Ctrl key.   The original Ctrl key you remapped continues to work.   I believe it modifies something like: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Keyboard Layout ([link for scancodes](https://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/scancode.doc))   ([more info](https://superuser.com/q/550679/14215)) ([more info](https://docs.google.com/spreadsheets/d/1GSj0gKDxyWAecB3SIyEZ2ssPETZkkxn67gdIwL1zFUs/edit#gid=0))
2. In Visual Studio, open some project, and click on the text editor area.
3. Press Ctrl+Shirt+E, to navigate the focus to the Explorer view.   This will work.
4. Now do these steps again, but instead of the Ctrl key, use the CapsLock key: CapsLock+Shift+E, and you'll notice that it won't work.

Please note that CapsLock key works fine as the Ctrl key in other operations when using VSCode.  Just not this particular operation.

I suspect the problem is that the code that checks for whether the Ctrl key is held down is looking at the actual hardware key.  There's probably a different API that takes into account the mapping instead of looking for the direct hardware key being pressed.   But I'm not sure.

There seems to be a slightly related issue that's also about scancodes: #162503

**Comment by alexdima** [comment]
@kasajian Does the remapping work when opening https://vscode.dev/ in Edge or Chrome?

**Comment by kasajian** [comment]
No.  It doesn't.

**Comment by alexdima** [comment]
> I suspect the problem is that the code that checks for whether the Ctrl key is held down is looking at the actual hardware key. There's probably a different API that takes into account the mapping instead of looking for the direct hardware key being pressed. But I'm not sure.

We react to all keyboard events in the same way, as we receive them from Chromium. We don't use any other native APIs to check if a modifier key is pressed. On Windows, we dispatch keybindings using the [`e.keyCode`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) property of these `keydown` events and we look at [`e.ctrlKey`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/ctrlKey), [`e.shiftKey`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/shiftKey), [`e.altKey`](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/altKey) for modifiers. 

This can be confirmed using `F1 > Developer: Toggle Keyboard Shortcuts Troubleshooting`. There is nothing we can do on our side (there is no possible code change to do) if the event doesn't have `e.ctrlKey` set to `false`. We react to it as it comes from Chromium. I therefore suggest investigating this further using a test page like https://w3c.github.io/uievents/tools/key-event-viewer.html and reporting the issue directly to Chromium.
