### ISSUE TITLE
Can not see Git (sub-)repositories in CMake superbuild structure

### ISSUE THREAD

**Issue by ruben-fuerst** [microsoft/vscode#162670]
Type: <b>Bug</b>

Hello,

the scenario is the following:
We have a main repository which just defines the build structure using CMake. It automatically downloads missing repositories (from dependencies) into a subfolder src/. This subfolder is included in the .gitignore-file of the main repo, such that the (sub-)repositories under src/ are not checked in when making changes to the main repo. Git submodules were out of question... Here is a small example on the directory structure:

main-repo/
--> .vscode/
--> ... other folders ...
--> src/      <-- this one is ignored
-----> repo1/      <-- own repository
-----> repo2/      <-- own repository
--> CMakeLists.txt

We set "git.autoDetectRepositories = true", set the scan depth limit to -1 and even added "git.scanRepositories" as a hint for VSCode to search in src/. 
The files are stored on a linux HPC to which we connect using the standard remote SSH extension.
To our knowledge (from older issues and stackoverflow entries) this is all we have to do to be able to see all repositories, even in subfolders. But this is not the case. Is there anything we have missed? If more information is required we are free to let you know.

Thanks for your help
Ruben Fuerst

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 3.10.0-1160.76.1.el7.x86_64

<details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.15.23
vscode-language-pack-de|MS-|1.71.9140925
remote-containers|ms-|0.251.0
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.66.3
doxdocgen|csc|1.4.0
latex-workshop|Jam|8.29.0
better-cpp-syntax|jef|1.15.23
cmake-language-support-vscode|jos|0.0.4
vscode-language-pack-de|MS-|1.71.9140925
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.4
vscodeintellicode|Vis|1.2.28

(2 theme extensions excluded)

</details>

**Comment by lszomoru** [comment]
The latest Stable release (`1.72`) added support for [nested git repository discovery](https://code.visualstudio.com/updates/v1_72#_discover-nested-git-repositories).
