### ISSUE TITLE
VS code duplicate the last letter or sign when hit save command

### ISSUE THREAD

**Issue by Tabbasum5856** [microsoft/vscode#162603]
Hi, 

Every time when I make changes on a certain file and hit the save command, the last letter or sign of that file is duplicated e.g

A- code before -- <div>test</div>

B- code after save command -- <div>update</div>>

Check the result for B at the end there is another ">" sign after the saving command, we have a team of developers and everyone is facing the same issue. The theme we working on is Warehouse Shopify. Please fix this asap.

**Comment by gjsjohnmurray** [comment]
/needsMoreInfo

Please also use the `Start Extension Bisect` command to investigate possible cause.

**Comment by roblourens** [comment]
I'm a little confused by the before/after description but this sounds likely to be an extension issue, so Extension Bisect will help here as @gjsjohnmurray points out

**Comment by Tabbasum5856** [comment]
Hi roblourens, let me share the loom link, problem is not with the VS extension, we are facing that issue from the date when we update our VS code version.

While making changes with the Shopify development theme, when we try to edit the file and hit the save command the vs code copies the last sign i.e,  > , }, etc of the file and adds it again next to that sign. Hope it makes sense.

Loom: https://www.loom.com/share/7b8c5dde46174f699ededa2a45b398f8

**Comment by Mxkert** [comment]
I'm having the exact same issue. With most files, whenever I save, it adds a character to the end of the file. It seems to duplicate the last character of the file.

**Comment by Tabbasum5856** [comment]
I figured out the issue. The problem was in the extension name "Liquid" powered by "panoply," please use Shopify Native extension instead, i.e., "Shopify Liquid" powered by Shopify. The issue will be fixed.

**Comment by Mxkert** [comment]
Thanks @Tabbasum5856 that fixed the issue! I'm also a Shopify developer. :)
