### ISSUE TITLE
Compare toaster menu doesn't go away

### ISSUE THREAD

**Issue by PatOShea** [Microsoft/vscode#16267]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|erb|CraigMaslowski|0.0.1|
|vscode-markdownlint|DavidAnson|0.4.1|
|ReplaceWithNewline|jmallien|0.0.1|
|csharp|ms-vscode|0.3.7|
|mono-debug|ms-vscode|0.10.20|
|PowerShell|ms-vscode|0.6.1|
|Theme-MarkdownKit|ms-vscode|0.1.0|
|Spell|seanmcbreen|0.7.0|

---

Steps to Reproduce:

1.Try to save a read only file which was just checked into source control. A menu that drops down/up to compare file with what's on disk. Selecting "compare" shows the diff of the two files, great!
2. After comparing the files, I can't get rid of that compare menu to see the tabs I have open. Not so good and had to close out of VSCode.

**Comment by bpasero** [comment]
@PatOShea can you share a  screenshot of what you mean where you had to quit VS Code to continue?

**Comment by PatOShea** [comment]
I'll get that to you later today. Thanks!

**Comment by bpasero** [comment]
@PatOShea any update?

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
