### ISSUE TITLE
Unit test failure: RemoteInstallAction and LocalInstallAction

### ISSUE THREAD

**Issue by deepak1556** [microsoft/vscode#162644]
Refs https://dev.azure.com/monacotools/Monaco/_build/results?buildId=187669&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=b317406d-66a0-580e-b921-bd6e7e55936d

```
1) RemoteInstallAction
       "before each" hook: setupTest for "Test remote install action is disabled for local ui extension if it is also installed in remote":

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

  2) LocalInstallAction
       "before each" hook: setupTest for "Test local install action is enabled for remote ui+workspace extension":

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by sandy081** [comment]
before each hook is a set up task which is not a long running operation and do not see a reason why it takes more than 5s. I also cant repo it locally. So, I think this is a random failure. Hence closing this. If I see it more number of times I will add logs then to understand what is happening
