### ISSUE TITLE
It would be nice to have an handy bottom to select file order in the explorer instead of going to settings

### ISSUE THREAD

**Issue by ruifortes** [microsoft/vscode#162675]
related to:
 [Add option to sort files in Explorer side-bar by date modified · Issue #11823 · microsoft/vscode](https://github.com/microsoft/vscode/issues/11823)

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/108271

**Comment by lramos15** [comment]
Actually a better duplicate of https://github.com/microsoft/vscode/issues/149393
