### ISSUE TITLE
C++ Intellisense

### ISSUE THREAD

**Issue by TFreudi1** [Microsoft/vscode#16265]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.1.12-1-default
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|code-gnu-global|austin|0.2.1|
|path-intellisense|christian-kohler|1.1.0|
|CppSnippets|hars|0.0.5|
|vscode-tfs|ivangabriele|0.5.2|
|cpp-symbols|mirkoh|0.0.1|
|vscode-clang|mitaki28|0.2.1|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.4|
|view-in-default-application|seesharprun|2.0.0|
|cmake|twxs|0.0.15|
|debug|webfreak|0.12.3|

---

Steps to Reproduce:

1. define a string variable: std::string myString;
2. go a line deeper and type myString.
3. You won't get any members of myString
4. Also if you mark myString and choose "go to definition" it dont work.

**Comment by TFreudi1** [comment]
Also I can't find a browse.VC.db

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#378
