### ISSUE TITLE
OSX launches with wrong locale

### ISSUE THREAD

**Issue by mikes-gh** [microsoft/vscode#16261]
- VSCode Version: 1.7.2
- OS Version: OSX 10.12
locale en-GB
Steps to Reproduce:

1. lauch vscode from Dock or applications I get en-US dates from `Date.prototype.toLocaleString();`
2. launch vscode from terminal using `code` I get en-GB dates from `Date.prototype.toLocaleString();`

On Windows 7 I  always get en-GB dates

**Comment by dbaeumer** [comment]
This has nothing to do with i18n. 

@bpasero moving to you since this looks like a electron / node issue under Mac.

**Comment by jwhitfieldseed** [comment]
I can't replicate with:

* VSCode Version: 1.7.2
* OS Version: OSX 10.12.1

OS Language preference set to "English". `$LANG`: `en_GB.UTF-8`

Steps:
1. Launch code from Dock.
2. Open developer tools.
3. Run in the console `new Date().toLocaleString()`

I see ex. `"05/12/2016, 22:47:16"`

Then:

4. Exit code
5. Use System Preferences > Language to change locale to United States. `$LANG`: `en_US.UTF-8` 
6. Re-open code from Dock
7. Open developer tools
8. Run in the console `new Date().toLocaleString()`

I see ex. `"12/5/2016, 10:49:09 PM"`

So the OS locale is honoured and picks up changes immediately. @mikes-gh does this match what you did?

**Comment by mikes-gh** [comment]
Yes I get the same results as you. 
The developer console gives correct results.

I get incorrect results from ToLocaleString() in the extension Im working on.

You could try this as a repo.
1. ext Install 
2. select - git history (git log) 

https://github.com/DonJayamanne/gitHistoryVSCode

Steps to get incorrect results

1. Start vscode from dock or applications
2. Open any repo.
3. Right click a file -> Git View File History
4. I get american dates in the item list (incorrect locale)

Steps to get correct results

1. Start viscose from terminal using `code`
2. Open any repo.
3. Right click a file -> Git View File History
3. I get British dates (correct locale)

Let me know if you can reproduce .  Thanks for your help on this

**Comment by mikes-gh** [comment]
@jwhitfieldseed Did you mange to report?

**Comment by jwhitfieldseed** [comment]
@mikes-gh I'm sorry for the slow reply, I missed the notification.

I can repro with your steps. I also get the incorrect results launching with Spotlight and Alfred.

I can also repro with a fresh extension. I ran `yo code` and replaced the default message in `extension.ts` with:

```js
vscode.window.showInformationMessage('Hello World! ' + new Date().toLocaleString());
vscode.window.showInformationMessage(`[${vscode.env.language}]`);
```

`vscode.env.language` is `en` in both cases. `Date#toLocaleString` differs as you report.

**Comment by jwhitfieldseed** [comment]
I can also repro with a vanilla Electron app:

1. `https://github.com/electron/electron-quick-start`
2. `npm install npm install electron-packager`
3.  Add to the `createWindow` method of `main.js`: 

```js
electron.dialog.showMessageBox({  message: new Date().toLocaleString()  })
```

4. `./node_modules/.bin/electron-packager . --platform=darwin`

Running from the terminal: (`./electron-quick-start-darwin-x64/electron-quick-start.app/Contents/MacOS/electron-quick-start`) alerts `13/01/2017, 23:49:05`

Running from Finder alerts `1/13/2017 11:50:47`.

I'll raise an issue on Electron when I get a chance.

**Comment by bpasero** [comment]
@mikes-gh can you print what kind of environment variables you have defined? I suspect your terminal has some `LC_` variables defined that are set when you run from terminal and not when you run from the Dock.

**Comment by mikes-gh** [comment]
@bpasero 

```
TERM_PROGRAM=Apple_Terminal
SHELL=/bin/bash
TERM=xterm-256color
TMPDIR=/var/folders/l9/3f8nhyrj2ts60qr9w44q_rdh0000gn/T/
Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.YGit9FQ6Gk/Render
TERM_PROGRAM_VERSION=388.1
TERM_SESSION_ID=05F369FB-124B-42DF-8AB2-230ED2BEE1DE
USER=MikeS
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.DlsCIBBwuW/Listeners
__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x2
PATH=/Users/MikeS/.dnx/runtimes/dnx-mono.1.0.0-rc2-16441/bin:/Users/MikeS/.dnx/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet
PWD=/Users/MikeS
LANG=en_GB.UTF-8
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
SHLVL=1
HOME=/Users/MikeS
LOGNAME=MikeS
_=/usr/bin/env
```

**Comment by bpasero** [comment]
@mikes-gh you should be able to fix this by removing this from your environment:

`LANG=en_GB.UTF-8`

**Comment by mikes-gh** [comment]
The problem is launching from dock.
Launching from a terminal window works so actually what you suggest would break my desired behaviour.

Desired behaviour is that vscode uses computer regional settings.

Its a confirmed issue with electron

**Comment by wraith13** [comment]
I also encountered the same cause problem.
Because LANG is empty, pbcopy / pbpaste and its dependent [node-copy-paste](https://github.com/xavi-/node-copy-paste) do not work correctly with Non-ASCII characters.

**Comment by bpasero** [comment]
Is this still happening?

**Comment by wraith13** [comment]
Yes, it is. ( vscode 1.18.0, macOS Sierra 10.12.6 )

**Comment by bpasero** [comment]
Is this still happening?

**Comment by wraith13** [comment]
Yes, it is. ( vscode 1.26.1, macOS High Sierra 10.13.5 )

This is [my vscode extention](https://github.com/wraith13/multi-encode)'s screenshot when 
launch vscode from `code` command on Terminal.app. `🐕` is displayed correctly.
![2018-08-17 22 53 09](https://user-images.githubusercontent.com/645907/44269944-eeb9f000-a270-11e8-8ef7-9f9f6b755d52.png)

This is [my vscode extention](https://github.com/wraith13/multi-encode)'s screenshot when 
launch vscode from dock or launchpad or spotlight.`🐕` is not displayed correctly.
![2018-08-17 22 53 53](https://user-images.githubusercontent.com/645907/44269950-f1b4e080-a270-11e8-96ff-1522594ddab4.png)

I can not recommend vscode to mac users because of this problem.

**Comment by wraith13** [comment]
This is still happening. ( vscode 1.27.2, macOS Mojave 10.14 ( Darwin 18.0.0 )  )

( I know it is macOS's fault. This is just a report. )

**Comment by wcass77** [comment]
I'm having an issue that I think is related to this. I changed my $SHELL with 
```{bash}
chsh -s /usr/local/bin/bash
```
to use the homebrew version. The change was picked up immediately by Terminal.app when creating a new shell. VSCode continues to launch the OSX version and 
```{bash}
echo $SHELL
```
produces: `/bin/bash` (VSCode) instead of the `/usr/local/bin/bash` (Terminal.app)

A workaround is to set the "terminal.integrated.shell.osx" option. This launches the right shell, but doesn't fix $SHELL, so I also added this to ~/.bash_profile:
```{bash}
# Fix $SHELL when using vscode:
export SHELL="/usr/local/bin/bash"
```
Hope people find this helpful.
