### ISSUE TITLE
Preview area is not flexible

### ISSUE THREAD

**Issue by Serhioromano** [Microsoft/vscode#16263]
It cuts off some text when I see extensions and also on markdown previews.

![2016-11-30_16-12-19](https://cloud.githubusercontent.com/assets/650741/20748340/fae52c5a-b717-11e6-9bc4-f4a29a42d4be.png)

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-great-icons|emmanuelbeziat|1.1.26|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|markdown-table-formatter|josa|0.0.4|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|seti-icons|qinjia|0.1.3|
|vscode-icons|robertohuertasm|4.0.4|
|Spell|seanmcbreen|0.9.1|
|markdown-pdf|yzane|0.1.4|

---

Steps to Reproduce:

1.
2.

**Comment by Serhioromano** [comment]
Ok I found something. It only happens if I zoom in with `Ctrl` + `+`

**Comment by joaomoreno** [comment]
#5745
