### ISSUE TITLE
Platform and Configuration selectboxes

### ISSUE THREAD

**Issue by TurkeyMan** [Microsoft/vscode#1626]
We need the platform and configuration selectboxes like vs-proper so we can easily switch between builds and platforms.

I would suggest that they each simply be populated with entries listed in `settings.json`, and set environment variables such that build actions declared in `tasks.json` can refer to them and do the right thing.

**Comment by bpasero** [comment]
@TurkeyMan please give an example what you want. 

PS: I am not sure why you say vs-proper, it is fine to say VS and everyone in the team will understand.

**Comment by TurkeyMan** [comment]
Okay, it seemed to me like VS is ambiguous now.

I just want to be able to flip platform and config with a selectbox, exactly like in VS.
My projects often span 4-5 platforms, and have at least 3 configurations per platform.
If that matrix could be configured in the project's `settings.json`, and then `tasks.json` could refer to those variables, it would be possible to configure convenient multi-platform workflows, which is one of VS's most valuable features.

**Comment by bpasero** [comment]
> Okay, it seemed to me like VS is ambiguous now.
VS = Visual Studio, VS Code = Visual Studio Code or just Code is fine.

Thanks for the explanation, @dbaeumer fyi

**Comment by alexr00** [comment]
You can get some of this with #4758 now. If that's not enough I can reopen this.
