### ISSUE TITLE
VSCode injection grammar extension 

### ISSUE THREAD

**Issue by ravirathore** [microsoft/vscode#162635]
- VS Code Version: 1.71.2
- OS Version: Windows 10

Steps to Reproduce:

Hi,
I wanted to build one small injection grammar extension. 

I followed this tutorial. https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide.

And, updated these 2 files:
1. package.json
2. syntaxes/injection.json

File contents are mentioned below.

I tested it for javascript, python and julia languages; respectively updating files with 'source.js', 'source.python' and 'source.julia'. Results are in the end.

Files contents are: 

'injection.json' file is here:
```
{
	"scopeName": "source.injection2",
	"injectionSelector": "L:source.julia",
	"patterns": [
	  {
		"include": "#var2"
	  }
	],
	"repository": {
	  "var2": {
		"match": "abc",
		"name": "keyword.var2"
	  }
	}
  }
  

```

'package.json' file is here:

```
{
  "name": "injectv2",
  "displayName": "injectv2",
  "description": "injectv2",
  "version": "0.0.1",
  "engines": {
    "vscode": "^1.54.0"
  },
  "categories": [
    "Programming Languages"
  ],
  "contributes": {
   
    "grammars": [
      {
        "path": "./syntaxes/injection.json",
        "scopeName": "source.injection2",
        "injectTo": [
          "source.julia"
        ]
      }
    ]
  }
}



```
Results(in debugging mode) are: 
1. It worked for julia. It highlighted the 'abc' word both in comments and source code.
2. In python and javascript, it highlighted 'abc' word in comments and in strings but not in variables.

Please let know if I miss anything. 

Please advise.

Thanks and regards,

**Comment by gjsjohnmurray** [comment]
I think this belongs at https://github.com/microsoft/vscode-discussions/discussions rather than here.

**Comment by ravirathore** [comment]
Thanks, have closed this and put it there.

https://github.com/microsoft/vscode-discussions/discussions/152
