### ISSUE TITLE
API: unable to use ^ in TextMate grammar regex (tmLanguage.json)

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#162626]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:
`tmLanguage.json`:
```json
{
  "$schema": "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json",
  "name": "my-example",
  "scopeName": "source.my-example",
  "patterns": [
     {
      "begin": "^.*",
      "end": "$",
      "beginCaptures": {
        "0" : {"name": "my-foo"}
      }
    }
  ]
}
```
testing text:
```
foo:bar:bar

foo:bar:bar
foo:bar:bar
```
Only the top and bottom lines matched, not the middle

[EDIT]
The issue seems to be related to "zero or" instances, so this regex has the same issue:
```regex
^(foo)?
```
when `*` replaced with `+` (aka "one or more instance)" it works correctly

This issue only reproducible when used `begin` + `end` + `captures`(`beginCaptures`) keys. With `match` key - it works correctly.

**Comment by RedCMD** [comment]
`^` matches start of line
not start of string

use `\\G` instead
it matches the end of `"begin"`

**Comment by vanowm** [comment]
It doesn't match to anything - that's the problem...where can I find more information about this? Like this `\\G` - where is that covered?

**Comment by RedCMD** [comment]
[List of Oniguruma regex expressions ](https://github.com/kkos/oniguruma/blob/master/doc/RE) 

[My extension](https://marketplace.visualstudio.com/items?itemName=RedCMD.tmlanguage-syntax-highlighter)

**Comment by vanowm** [comment]
This was not a question and unless it's fixed, it's not "completed"

**Comment by RedCMD** [comment]
technically this isn't a bug
as it's the specification from TextMate

the `"end"` rule is tested before the inner rules
but the inner rules can push the `"end"` out if they can match before it (and over the end)

`^` works correctly at matching the start of a line

**Comment by vanowm** [comment]
What "inner rules" are you referring to? Specifically in the provided example? (note, the original post was changed since first posted)

**Comment by RedCMD** [comment]
prob should have made a new report instead of changing it

my guess is the rule `^.*`, `$` is able to match the empty line infinite times and textmate just ends up giving up and moving onto the next line (seems the the line after it gets caught up with it)
