### ISSUE TITLE
Submenu labels don't work with package.nls.json

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#162671]
To repro:
1. Have an extension that contributes a submenu to a view title. Example: https://github.com/microsoft/vscode-pull-request-github/blob/eac1aee806f92f855e99306387520fd21b8d19cf/package.json#L1307-L1308
2. Put the label of the submenu in the extension's package.nls.json and use the standard `%...%` syntax to reference the string from the `label` property of the submenu. Example:
```
"submenus": [
			{
				"id": "github.pullRequests.overflow",
				"label": "%submenu.github.pullRequests.overflow.label%",
				"icon": "$(ellipsis)"
			},
]
```
3. Run the extension and hover over your submenu:
![image](https://user-images.githubusercontent.com/38270282/193851673-af5c9f81-a29c-45d9-9fcc-22df2c4abc52.png)

**Comment by TylerLeonhardt** [comment]
This appears to be fixed.
