### ISSUE TITLE
does not start on Debian stable

### ISSUE THREAD

**Issue by simevo** [microsoft/vscode#162687]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2 74b1f979648cc44d385a2286793c226e611f59e7 x64
- OS Version: Linux Debian 11

Steps to Reproduce:

1. `code --verbose --disable-extensions`

Result:

```
LaunchProcess: failed to execvp:
/usr/share/code/chrome-sandbox
```

**Comment by josevalarezodev93** [comment]
Hi
I hope this website can help solve your problem: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=742829
Have a nice day <3

**Comment by simevo** [comment]
Thanks! you reminded me that I had a too strict apparmor profile enabled!
