### ISSUE TITLE
Deprecating the `Julia Insider` extension

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#162782]
We just switched the [Julia](https://marketplace.visualstudio.com/items?itemName=julialang.language-julia) extension over to use the official pre-release functionality for our insider builds. The docs say

> Note: Extensions that already have a separate stand alone pre-release extension should reach out to the VS Code team to enable the automatic uninstall of the outdated separate extension and install of the pre-release version of the main extension.

So that is us and me reaching out :) Could you please somehow redirect all the users of https://marketplace.visualstudio.com/items?itemName=julialang.language-julia-insider to the pre-release version of the main extension https://marketplace.visualstudio.com/items?itemName=julialang.language-julia ? And I'm not sure what we should do with the insider extension then? Presumably just delete?

**Comment by isidorn** [comment]
@davidanthoff we have added the Julia Insider extension to be auto transitioned to the pre-release version of the julia extension. It takes a bit of time to propoagate this so I think this will start happening from tomorrow.

> And I'm not sure what we should do with the insider extension then? Presumably just delete? 

I suggest you just delete the extension.

**Comment by davidanthoff** [comment]
Excellent, all done!
