### ISSUE TITLE
Add diagnostics for duplicate markdown link definitions

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#162775]
VS Code issue tracking https://github.com/microsoft/vscode-markdown-languageservice/issues/59

**Comment by mjbvz** [comment]
For testing:

1. Confirm that any duplicate link definitions in markdown files get a diagnostic:
```md
[dup]

[dup]: http://example.com
[dup]: http://example.com
```

2. Confirm the diagnostic goes away if the duplicate is removed

3. Confirm that you can use a quick fix to remove the duplicate definition

4. Confirm you can use the `markdown.validate.duplicateLinkDefinitions.enabled` setting to disable these diagnostics

4. Try exploring to see if you find any edge cases where this new feature does not work as expected

**Comment by hediet** [comment]
Also does not work:

![image](https://user-images.githubusercontent.com/2931520/197789912-212876b0-ca98-4820-a6e2-ea4b8f69df20.png)

Am I doing something wrong?

**Comment by mjbvz** [comment]
Ah you also need to set `"markdown.validate.enabled": true`
