### ISSUE TITLE
Debugger: Attach to process: 'null' doesn't look like a process id.

### ISSUE THREAD

**Issue by normalser** [Microsoft/vscode#16271]
- VSCode Version: Code - Insiders 1.8.0-insider (2bd85b81138984acd08983df4cb2fbdc1c41aa4d, 2016-11-30T07:05:07.830Z)
- OS Version: Darwin x64 16.1.0
---

Steps to Reproduce:

1. Press F5 
2. Input box gets displayed with:
![image](https://cloud.githubusercontent.com/assets/1723815/20755190/10cad22c-b6dc-11e6-9b0d-15c96f651fb2.png)

3. Press `Esc`
4. You get:
![image](https://cloud.githubusercontent.com/assets/1723815/20755224/264b25c0-b6dc-11e6-9c85-ea1717069d08.png)

Should probably just close the input box from step #2

**Comment by chrmarti** [comment]
Reproduced with:
```
        {
            "type": "node",
            "request": "attach",
            "name": "Attach to Process",
            "processId": "${command.PickProcess}"
        }
```

**Comment by isidorn** [comment]
I simply improved the error message
Yes, ideally we would not event start debugging but that would require some checking of the launch.json for unreplaced variables which is ugly code that I do not want to introduce.
@weinand can improve this message on the adapter side if needed

![screen shot 2016-12-13 at 10 59 18](https://cloud.githubusercontent.com/assets/1926584/21135847/7ba46a58-c123-11e6-984f-aad8462d4d45.png)

**Comment by weinand** [comment]
@isidorn you've fixed this with a real fix for Jan 2017. Please add a comment what you did and close the issue.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/18601
