### ISSUE TITLE
`onQueryTriggered` triggering multiple times when typing quickly

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#162754]
Seems that typing quickly in the search input with Search on Type enabled can run `onQueryTriggerred` 2-3 times, causing multiple searches to happen at once. 
https://github.com/microsoft/vscode/blob/ee73b6543eaeded5e7e81a1a70fe75008ea313f9/src/vs/workbench/contrib/search/browser/searchView.ts#L1444

https://github.com/microsoft/vscode/pull/162405 tries to stop it from rendering the tree more than once when this happens, but we should find the root cause for the issue.

**Comment by eleanorjboyd** [comment]
Closing as stale due to the changes make in this area since this issue was filed
