### ISSUE TITLE
Fix configuration editing tests

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16272]
See my workaround in https://github.com/Microsoft/vscode/commit/d3ebfacb50e63b1dffe70c0e5138379a842b55f4

**Comment by sandy081** [comment]
@bpasero Thanks for fixing it. Will take care of this when I write tests for writing configuration using model.

**Comment by sandy081** [comment]
Will be fixing this in debt week

**Comment by sandy081** [comment]
Fixed with #19152
