### ISSUE TITLE
Moved Extension

### ISSUE THREAD

**Issue by brigevans** [microsoft/vscode#162702]
I tried moving my Stripe extension to the secondary bar, and then the search, I was able to drag the search back to my activity bar, but now stripe is not there, not in the secondary bar, not in the activity bar, not in the list for the activity bar, just gone. I have uninstalled and then reinstalled the extension and that did not help. I need to figure out how to get that tool back, because I am not able to run it anywhere. Any help will be appreciated.

**Comment by sbatten** [comment]
The simplest option to get it back would be to `Reset View Locations` ... You can run this command from the command palette with Ctrl/Cmd+Shift+P. This will move everything back to its default location.

If you want to investigate where the view might be hidden, you can try running the command `Focus on X View`. Every view typically has this command which will open the view even if it is hidden away. I don't know the name of the view but you can look through the filtered list.

**Comment by brigevans** [comment]
Thank you for the information. It looks like when I moved it over to the
secondary side bar, it actually put it inside of the search, and it was
just down at the bottom, figured out how to get those out of there and we
are all good now.


BRIG EVANS
*VP of Software Engineering*
***@***.***


 WWW.TICKETSAUCE.COM
<http://www.ticketsauce.com/>
