### ISSUE TITLE
Display Set elements in debugger views

### ISSUE THREAD

**Issue by adelphes** [Microsoft/vscode#16274]
The elements added to a Set are not displayed in the debugger.

- VSCode Version: 1.7.2
- OS Version: Linux x64
- launch: node2
- node: 6.3.0

Steps to Reproduce:
1. Create a `new Set()` variable and add some elements to it.
2. View/Expand the variable in Locals/Watches or hover over variable.
3. Only the set size is displayed - none of the actual elements in the set are shown.

Evaluating Maps and Sets don't display anything other than the size. It would be nice to see what elements have been added.

![vscode-set](https://cloud.githubusercontent.com/assets/13035517/20766124/0b8794a2-b72d-11e6-90d8-44f70141899c.jpg)

A workaround to view the elements is to add a watch of the variable, converting the Set to an array using the spread operator: `[...aSetVariable]`

**Comment by chrmarti** [comment]
What type of launch config are you using? Which version of node are you using?

**Comment by roblourens** [comment]
It should at least work on a newer version of node, or using type: 'node' instead of 'node2'. 6.3.0 was the first version supporting the new protocol, and I remember some issues around Set/Map elements.

I only show what Node sends over the wire. If you repro this with Node 6.9 or 7+, let me know.
