### ISSUE TITLE
Terminal does not output `Executing task:` after `Run Build Task` more than 2 times

### ISSUE THREAD

**Issue by kkocdko** [microsoft/vscode#162732]
Does this issue occur when all extensions are disabled?: Yes, on all-new install.

- VS Code Version: 1.71.2 Stable
- OS Version: Reproduced on both Windows 10 and Fedora 36 (Wayland)

Steps to Reproduce:

1. Create a folder and add tasks.json:

```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "echo",
            "type": "shell",
            "command": "echo Hello",
            "group": {
                "kind": "build",
                "isDefault": true
            }
        }
    ]
}
```

2. Command Palette > Run Build Task, execute many times, it output 1 blank line at first but 2 lines starts from the third time.

![Screenshot from 2022-10-05 18-13-15](https://user-images.githubusercontent.com/31189892/194037941-306c2deb-86d0-4302-a9a7-9e87b675cbd2.png)

**Comment by kkocdko** [comment]
Or is this a feature? How could I disable this? (Make every time `[Run Build Task]` outputs the same content.)

**Comment by meganrogge** [comment]
they're equally spaced for me - could you pls clarify what you expect?

![Screen Shot 2022-10-05 at 9 21 14 AM](https://user-images.githubusercontent.com/29464607/194111221-8bf4d6e4-8340-42c5-9d23-fb99caec10e1.png)

**Comment by kkocdko** [comment]
Correction: Starts from the third time exec `Run Build Task`, it does not output ` *  Executing task: echo Hello` anymore.

@meganrogge Reproduced even on GitHub Codespace. Which terminal profile you choosed? And is the `tasks.json` with my provided content?

Use the bash (on linux) or cmd (on windows) terminal profile, with the tasks.json above, exec `Run Build Task (Ctrl + Shift + B)`.

![image](https://user-images.githubusercontent.com/31189892/194189987-e0d3c6bc-471d-4aba-919d-b818e5b4aea8.png)

```
(Version Info in Codespace)
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:04:17.383Z
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
```

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by kkocdko** [comment]
Ohhhh, you're right, it does not appear in the insiders build! 

I'll first to try insiders build if I found a bug next time.
