### ISSUE TITLE
cshtml files adding lines/tabs when saving

### ISSUE THREAD

**Issue by ACRonm** [microsoft/vscode#162709]
Type: <b>Bug</b>

When saving a .cshtml file using the following example code, blank lines are added to the file above the `ViewData["Title"] = "Home Page";`  are added to the file. 

Example code:

```
@{
    ViewData["Title"] = "Home Page";
}

<div class="index-head">
    <h1>
        Artificial Intelligence
    </h1>

    <p>
    </p>
</div>

```

Example after saving file 3 times:

![image](https://user-images.githubusercontent.com/102561643/193972133-9171ca1f-a6e5-4280-9f79-02d0e870699e.png)

VS Code version: Code 1.71.2 (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (6.31GB free)|
|Process Argv|--crash-reporter-id 64f0ac50-294d-443b-977f-6cf3bb656e22|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.14.1
bootstrap5-vscode|Anb|0.4.2
webvalidator|Cel|1.2.2
jquerysnippets|don|0.0.1
linter|fna|0.0.13
code-runner|for|0.11.8
live-sass|gle|5.5.1
vscode-peacock|joh|4.2.2
vscode-language-babel|mgm|0.0.36
csharp|ms-|1.25.0
vscode-edge-devtools|ms-|2.1.1
pylint|ms-|2022.5.12771045
python|ms-|2022.14.0
jupyter|ms-|2022.8.1002431955
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.9
material-icon-theme|PKi|4.20.0
LiveServer|rit|5.7.9
pdf|tom|1.2.0
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by ACRonm** [comment]
> 

Thanks John, sorry for being a noob! It seems it was the ms-dotnettools.csharp extension causing the issue. I will do some more investigation.
