### ISSUE TITLE
[Node.js] Intellisense Not Working in Other Files

### ISSUE THREAD

**Issue by WhitigolProd** [microsoft/vscode#162757]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: Latest Insiders
- OS Version: Win 10 21H2

Steps to Reproduce:

1. Init package.json
2. Install any package
3. Create a file, and create a variable that uses one of the functions from the node package
4. Create another file, and try to call that same variable.

I have tried a re-install of VSCode, and the latest insiders build. Still having the same issues. I have even tried many of the fixes that recommend adding the following to `jsconfig.json`
```json
{
    "compilerOptions": {
        "target": "es6",
        "module": "commonjs",
        
    },
    "exclude": [
        "node_modules"
    ]
}
```

Any help would be greatly appreciated. Thanks in advance!

**Comment by mjbvz** [comment]
Please share an example project that demonstrates the issue

**Comment by WhitigolProd** [comment]
Yes, sure thing: https://github.com/WhitigolProd/SnailyCAD-Manager

**Comment by mjbvz** [comment]
Thanks. This is expected. `pre` is a module because it uses `require`. That means that globals declared in it aren't accessible in other files

Instead you need to use proper imports/exports

**Comment by WhitigolProd** [comment]
Thank you, I understand that. But my issue is; the code works perfectly fine, and I want to avoid using import/export in all the files that I create. I've never had this issue before, and what I'm trying to do has worked perfectly fine without issues in the past. Is there a workaround for this issue?
