### ISSUE TITLE
Use registerAction2 instead of registerWorkbenchAction

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#162713]
continues https://github.com/microsoft/vscode/issues/96672

We should use [`registerAction2`](https://github.com/microsoft/vscode/blob/da3ba1c16cfe927e31c728cf97ba96319b95c5b4/src/vs/platform/actions/common/actions.ts#L576) instead of the old action world. Using the new way yield in less code and brings everything (command, keybinding, menus) together in one place. 

---

- [x] src/vs/workbench/browser/actions/navigationActions.ts @bpasero 
- [x] src/vs/workbench/browser/parts/auxiliarybar/auxiliaryBarActions.ts @sbatten 
- [x] src/vs/workbench/browser/parts/editor/editor.contribution.ts @bpasero 
- [x] src/vs/workbench/browser/parts/panel/panelActions.ts @sbatten 
- [x] src/vs/workbench/contrib/files/browser/fileActions.contribution.ts @lramos15 
- [x] src/vs/workbench/contrib/logs/browser/logs.contribution.ts @sandy081 
- [x] src/vs/workbench/contrib/logs/common/logs.contribution.ts @sandy081 
- [x] src/vs/workbench/contrib/logs/electron-sandbox/logs.contribution.ts @sandy081 
- [x] src/vs/workbench/contrib/preferences/browser/keyboardLayoutPicker.ts @rebornix 
- [x] src/vs/workbench/contrib/search/browser/search.contribution.ts @andreamah 
- [x] src/vs/workbench/contrib/terminal/electron-sandbox/terminalRemote.ts @Tyriar 
- [x] src/vs/workbench/contrib/update/browser/update.contribution.ts @joaomoreno 
- [x] src/vs/workbench/contrib/welcomeOverlay/browser/welcomeOverlay.ts @lramos15 
- [x] src/vs/workbench/contrib/welcomeWalkthrough/browser/walkThrough.contribution.ts @lramos15 
- [x] src/vs/workbench/services/preferences/test/browser/keybindingsEditorModel.test.ts @sandy081

**Comment by sbatten** [comment]
@jrieken in some cases, with `Action2` I have to use separate `appendMenu` calls because I need different presentations for these actions based on the menu (still text, but the wording needs to be modified by context). Should the menu property of action2 allow for optional overrides of the title?

**Comment by joaomoreno** [comment]
@jrieken @sbatten Thanks for the discussion above. I wasn't aware that `registerAction2` could support all these use cases in a single call. I further simplified the `update` world.

**Comment by sbatten** [comment]
@jrieken thanks for the details. I didn't recognize the existence of the toggled title, perhaps that is what I am looking for, and maybe need to make some changes to adopt this. I will play around with this. A good example of this is with the part toggles where sometimes we say any one of the following depending on the context: "Toggle X" "X" with a checkmark or not, or "Hide X"

**Comment by bpasero** [comment]
Work is starting, but I might limit it to 20-30 per milestone since its quite the change for the 100 editor actions 👍
