### ISSUE TITLE
Debug: Run to cursor should start/ restart session as needed 

### ISSUE THREAD

**Issue by benmkw** [microsoft/vscode#162727]
After reading https://twitter.com/pervognsen/status/1098453808651202560 I tried "Debug: Run to cursor" but could not yet find an easy way to start/ restart the debugging session. For now the workflow seems to be that I have to start the session, then use "Debug: Run to Cursor". 

Feature Request: 
A setting which would advice the "Debug: Run to cursor" to start/ restart the session as needed would be beneficial. Additionally "Debug: Run to cursor" should then be available even if not debugging session is active.

**Comment by roblourens** [comment]
Yes, this is a command for the debug session, and currently it only works within an active debug session. But this is not a bad suggestion and I think I would take a PR that implements it. Basically -

- If there is an active debug session, same behavior
- If not, then set the "temp breakpoint", do the same thing as the "Start Debugging" command, then run to that breakpoint

**Comment by Viijay-Kr** [comment]
@roblourens I would like to work on this

**Comment by roblourens** [comment]
Great, go for it

**Comment by benmkw** [comment]
@Viijay-Kr thanks a lot for working on this, I just tested this in 
```
Version: 1.76.0-insider
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-02-28T11:50:50.947Z
```

with a basic python program and it worked perfectly, from my side this issue could be closed.

Maybe its still open because its not released on stable? (or maybe its also on stable, so it can really be closed? https://github.com/microsoft/vscode/pull/169819#issuecomment-1402222300)

**Comment by Viijay-Kr** [comment]
@benmkw Actually I think its not closed because I did not say `Closes` in my plus this wasn't added to any milestone if I am not mistaken.

I guess this shall be closed

**Comment by roblourens** [comment]
Apologies, closing it now
