### ISSUE TITLE
Git conflict decorations not appearing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#162766]
1. Paste the following into a file (I do not have the merge editor enabled)
```
<<<<<<<
foo
=======
bar
>>>>>>>

```
2. :bug: no merge conflict decoration appears

This is identical to https://github.com/microsoft/vscode/issues/157827 but repros in latest insiders

@rebornix was also able to repro

**Comment by hediet** [comment]
Can you repro in stable?

**Comment by hediet** [comment]
I cannot repro:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/2931520/194142196-f37bfbf4-846b-4441-b15f-cf9109db47a5.png">

**Comment by joyceerhl** [comment]
Ah I repro when `"git.mergeEditor": true`, which is the case in the VS Code workspace settings

**Comment by joyceerhl** [comment]
But I also repro in a personal GitHub repo on insiders.vscode.dev which doesn't have that setting

**Comment by joyceerhl** [comment]
🤦‍♀️Looks like the merge conflict extension got disabled for me at some point, enabling it fixed things so closing this out for now!
