### ISSUE TITLE
Add the ability to run all tests in a file/folder from the explorer pane context menu

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#162728]
A few users migrating from IntelliJ/Android Studio have asked questions about running tests from the Explorer view (which is [available in IntelliJ/AS](https://www.jetbrains.com/help/idea/performing-tests.html#:~:text=to%20run%20all%20tests%20in%20a%20folder)). It's possible they didn't know about the test explorer, or that they just generally have the explorer visible and prefer to use that.

It would be nice if explorer context menus had options to "run/debug tests in file" and "run/debug all tests in folder" where VS code knows there are tests both for improved discovery and convenience.

@connor4312

**Comment by gjsjohnmurray** [comment]
@DanTup have those few users installed an extension which uses [the API](https://code.visualstudio.com/api/references/vscode-api#tests) that turns on the Testing icon (lab beaker) in the activity bar? If so, shouldn't it be the responsibility of that extension to contribute those extra options to `explorer/context`?

**Comment by DanTup** [comment]
> shouldn't it be the responsibility of that extension to contribute those extra options to `explorer/context`?

I guess this is subjective. If extensions do it, users might end up with multiple entries on their folder/file nodes if extensions don't scope things correctly, and they may behave inconsistently (and some might never implement it, so users will only get the feature for "some" languages). Since VS Code is generally in charge of the UI for testing (the test explorer, gutter icons, etc.) I feel like it makes most sense for it to provide this once and then all users benefit from it without every extension implementing the exact same code.

That said, I'm happy to add it to my own extension if it's deemed not appropriate for VS Code. I pinged @connor4312 on https://github.com/Dart-Code/Dart-Code/issues/4198 for his opinion and it sounds like he thinks it's better here so I thought I should raise this and wait a little before implementing it there.

**Comment by connor4312** [comment]
You could also have a folder with multiple different types of code/test in them and want to run that. I think having a unified context menu action makes sense--for the same reason that we added a unified "refresh" action.

**Comment by connor4312** [comment]
Verification:

- Have a project with unit tests, such as VS Code
- Right click on items in the Explorer and verify that the test-related actions appear and work to run tests under each subtree

**Comment by roblourens** [comment]
My explorer context menu is huge, and a lot of that is from extensions, but I wonder whether the 3 test commands should be under a submenu?
