### ISSUE TITLE
Terminals in a tab use wrong background color for gutter around the terminal

### ISSUE THREAD

**Issue by Twipped** [microsoft/vscode#162769]
Type: <b>Bug</b>

I like to have a black terminal window, but use a light window theme. This works great in the panel, but when you drag a terminal out into its own tab, there is a gutter space around the outside of the terminal which is colored using `editor.background` instead of `terminal.background`. Not only does this mess with the contrast of the terminal, but it makes the command indicator difficult to see.

![image](https://user-images.githubusercontent.com/231157/194149586-62e387b7-c951-4ffb-8a41-6c5a61e8762e.png)

VS Code version: Code 1.71.2 (Universal) (74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:05:37.721Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 0689c40f-7961-4ca5-af1f-60081e86742b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
color-info|bie|0.7.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.3.3
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.0.7
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
multi-cursor-case-preserve|Car|1.0.5
npm-intellisense|chr|1.4.2
vscode-github-actions|csc|0.24.2
vscode-simpler-icons|dav|1.6.5
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
vscode-open-in-npm|fab|1.0.4
vscode-graphql|Gra|0.7.5
vscode-graphql-syntax|Gra|1.0.4
vscode-test-explorer|hbe|2.21.1
npm|ide|1.2.0
svg|joc|1.4.20
dotenv|mik|1.0.1
graphql|mqu|0.1.2
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.22.1
makefile-tools|ms-|0.6.0
sublime-keybindings|ms-|4.0.10
test-adapter-converter|ms-|0.1.6
material-icon-theme|PKi|4.20.0
vscode-icons-mac|way|7.25.3
faster-new|wen|1.5.1
change-case|wma|1.0.0
better-align|wwm|1.1.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by Tyriar** [comment]
Panel works correctly because of this:

https://github.com/microsoft/vscode/blob/a2024df88586fcd9a30bd144c2fc689364656cfc/src/vs/workbench/contrib/terminal/browser/terminalView.ts#L303-L309

**Comment by Twipped** [comment]
Thank you!!
