### ISSUE TITLE
timed out waiting for debugger server to connect while trying to attach to python running process

### ISSUE THREAD

**Issue by johnosbb** [microsoft/vscode#162733]
Does this issue occur when all extensions are disabled?: Yes/No. It requires the python extension

- VS Code Version: Version: 1.71.2, Commit: 74b1f979648cc44d385a2286793c226e611f59e7
- OS Version:  Linux x64 5.15.0-48-generic snap

Steps to Reproduce:

1. Create a simple python file, for example
import time
while True:
     time.sleep(0.5)  
2.  Create a launch file that allows one to debug by attaching to the running process

{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
    
        {
            "name": "Python: Attach using Process Id",
            "type": "python",
            "request": "attach",
            "processId": "${command:pickProcess}",
            "justMyCode": false,
            "logToFile": true
        },
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "justMyCode": false
        }
    ]
}

3. Select the option to attach to a running process. VSCode always returns the message:

Timed out waiting for debug server to connect

The VSCode and configuration is:

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-48-generic snap
Sandboxed: N

**Comment by roblourens** [comment]
Please file this on the vscode-python extension repo
