### ISSUE TITLE
I want to open the terminal and it crashes.

### ISSUE THREAD

**Issue by Cristian-Beliera** [microsoft/vscode#162703]
When I am going to open the terminal to be able to execute the code, a window appears with the following error and until yesterday it was just fine.
code se bloqueo la ventana (motivo "crashed", code: "- 1073741819")

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
