### ISSUE TITLE
Debugger JS Coping date value in object will not be transfert

### ISSUE THREAD

**Issue by maxime4000** [microsoft/vscode#162747]
Does this issue occur when all extensions are disabled?: Not tested (Probably yes)

- VS Code Version: 1.71.2
- OS Version: 12.4 (MacOS)

Steps to Reproduce:
I have this object : 
```ts
const x = {
  $and: [
    {
      renewalDate: {
        $gte: new Date("2022-10-05T04:00:00.000Z"),
        $lte: new Date("2022-11-05T03:59:59.999Z"),
      },
    },
  ],
};
```
1. If I goes in chrome console and "copy object", this is what I get :
```json
{
	"$and": [
		{
			"renewalDate": {
				"$gte": "2022-10-05T04:00:00.000Z",
				"$lte": "2022-11-05T03:59:59.999Z"
			}
		}
	]
}
```
2. If I copy the same object from the debugger of vscode, this is what I get : 
```
{
  $and: [
    {
      renewalDate: {
        $gte: {
        },
        $lte: {
        },
      },
    },
  ],
}
```
3. I don't think I'm suppose to get empty object from date and it's really not helpful in my case because when I do this, it's because I want to take the aggregation I was working with and try it in Studio 3T and I can't without rewrite in memory value.
4. Just comparing with WebStorm, this is not an issue for them. It's not ideal, but when I copy the value, I do get a string version of the value if they couldn't return me the object like Date or ObjectId.

Note : this behaviour also happen when I work with ObjectId() which return empty object. I would prefer having the string, but I don't know if this is out of scope because it's 3rd party.

**Comment by roblourens** [comment]
[vscode-debugadapter-fa49ce5e.json.gz](https://github.com/microsoft/vscode/files/9717680/vscode-debugadapter-fa49ce5e.json.gz)

@connor4312 this is pausing after the code above and using "Copy Value" on the `$gte` property in the variables view. We evaluate `x.$and[0].renewalDate.$gte`, and js-debug returns an empty object. But evaluating the same thing in the debug console returns the expected string. I think this is relying on the toString behavior of Date

**Comment by aeschli** [comment]
I still see the same in 
Version: 1.73.0-insider (user setup)
Commit: a803dc359aa1ed48c7acf074dd81d6af1525c8c8
Date: 2022-10-25T05:18:55.889Z
OS: Windows_NT x64 10.0.22623
```
const x = {
    $and: [
      {
        renewalDate: {
          $gte: new Date("2022-10-05T04:00:00.000Z"),
          $lte: new Date("2022-11-05T03:59:59.999Z"),
        },
      },
    ],
  };

console.log(x);
```

- set break point at `console.log`, run the programm
- when stopped at breakpoint, select `x` in the variables view, run `Copy as value` from the context menu
- paste the content
```
{
  $and: [
    {
      renewalDate: {
        $gte: {
        },
        $lte: {
        },
      },
    },
  ],
}
```

**Comment by aeschli** [comment]
Oh, I was not on JavaScript Debugger (Nightly)

Works with JavaScript Debugger (Nightly) v2022.10.1817
