### ISSUE TITLE
Split Terminal in any direction

### ISSUE THREAD

**Issue by globalhuman** [microsoft/vscode#162710]
Currently the actions available to split the terminal are:

- `workbench.action.terminal.split`

It would be great to have support as is with the editor `workbench.action.splitEditorDown`. 

This would enable better usage of the terminals in the editor area to enable more dense layouts https://code.visualstudio.com/updates/v1_58#_terminals-in-the-editor-area.

**Comment by globalhuman** [comment]
A command I would hope to be able to use would be -> `workbench.action.terminal.splitBelow`

**Comment by Tyriar** [comment]
The panel uses a single dimension by design currently, you can 2d splitting by using terminals in the editor area. We plan on revisited this when we tackle https://github.com/microsoft/vscode/issues/34442

**Comment by Tyriar** [comment]
@globalhuman nice, I hadn't thought of using that command to do it in a single action 👍
