### ISSUE TITLE
[html] HTML tag completion occasionally incorrect

### ISSUE THREAD

**Issue by julianlam** [Microsoft/vscode#16279]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jslint|ajhyndman|1.2.1|
|vscode-eslint|dbaeumer|1.1.0|

---

Steps to Reproduce:

1. Start typing HTML (test source below)
1. Move cursor to the end of the line containing `</select>`, hit `Enter`
2. Attempt to trigger automatic tag completion by typing `<` and hitting `Enter`

What I expected:

* `</div>`

What happened instead:

* `</form>`

Test source:

``` html
<div class="row">
	<div class="col-sm-6">
		<form>
			<div class="form-group">
				<label for="assignee">[[flags:assignee]]</label>
				<select class="form-control" name="assignee">
					<!-- BEGIN assignees -->
					<option value="{../userslug}">{../username}</option>
					<!-- END assignees -->
				</select>
		</form>
	</div>
</div>
```

Notes:
* Tag completion works fine if I `</` and then hit `Enter`. Just `<` doesn't seem to work
* Tag completion works fine if the bottom two `</div>`s are not present

**Comment by chrmarti** [comment]
@aeschli This still reproduces in todays insiders. Shouldn't the fix have been picked up from `Microsoft/vscode-html-languageservice`?

**Comment by aeschli** [comment]
I verified that the service got updated and the fix should be in.
This is what I see with
Version 1.8.0-insider
Commit e0871329738682651367be4e8a618912ad693e03
Date 2016-12-08T07:04:29.620Z

![image](https://cloud.githubusercontent.com/assets/6461412/21011679/955260b0-bd52-11e6-8090-baf6b5e93c2e.png)

**Comment by chrmarti** [comment]
Works now with todays insiders. It was showing /form yesterday, not sure if the updated insiders made a difference or if it was a one-off. Marking verified.
