### ISSUE TITLE
Horizontal Split

### ISSUE THREAD

**Issue by MYounas** [Microsoft/vscode#16273]
- VSCode Version:1.7.2
- OS Version:windows 7x64

Steps to Reproduce:

1. Please add horizontal split functionality.This functionality should interact more developers.Because one of your competitor Brackets has this functionality.
Thanks in advance.

**Comment by chrmarti** [comment]
Have you tried horizontal layout? (Ctrl+Alt+1)

**Comment by MYounas** [comment]
(Ctrl+Alt+1) do nothing,I tried 3-4 times.

**Comment by bpasero** [comment]
@MYounas try Alt+Shift+1

**Comment by MYounas** [comment]
It also not working.

**Comment by MYounas** [comment]
Why you close this please help me,Is there in my installation or any other matter how can I get the horizontal split functionality?

**Comment by MYounas** [comment]
Its working sorry sorry My bad,Thanx alot man :*
