### ISSUE TITLE
Sometimes opening file replaces most recent opened file

### ISSUE THREAD

**Issue by jefferychow** [Microsoft/vscode#16285]
- VSCode Version: 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f)
- OS Version: OS X 10.11..6

Steps to Reproduce:

Code does this only intermittently but it's very annoying when it does happen:

1. have one or more files open for editing
2. open another document by doing one of following: A) Explorer bar, B) QuickOpen, or C) CMD+Click on c# class in current document, the new document replaces the current document. I would expect it to always open the document in a new tab

**Comment by chrmarti** [comment]
The editor that goes away might have been in 'preview' mode. You can tell by the tab's title having an italic font. If that's the issue, you can turn that off with the setting `"workbench.editor.enablePreview": false`. Let me know if that resolves the issue.

**Comment by jefferychow** [comment]
That was exactly it, thanks very much!
