### ISSUE TITLE
Need the right-click context menu of Windows 11 

### ISSUE THREAD

**Issue by Looong01** [microsoft/vscode#162805]
Need "Open in Code" Option in the right-click context menu of WIndows 11!
Like, add this buttom here:
![image](https://user-images.githubusercontent.com/69568351/194216667-cf737c7c-47df-4f24-9b65-65cdaec03d40.png)

**Comment by kanlukasz** [comment]
Under what circumstances do you not see this item in the context menu?
I tried with Windows 11 and it seems to work fine:

![image](https://user-images.githubusercontent.com/30685349/194220221-86aad117-e060-4ee4-abf2-b7fb9661b337.png)

But it is true that this option does not exist when i calls a context menu **inside** a folder
![image](https://user-images.githubusercontent.com/30685349/194220630-9d94fa3a-3b02-45f9-b4f1-c2fbed3f261c.png)

**Comment by gjsjohnmurray** [comment]
See 127365

**Comment by joaomoreno** [comment]
#127365
