### ISSUE TITLE
Verify and fix our a11y support using accessibility checker verification

### ISSUE THREAD

**Issue by candybaby407** [Microsoft/vscode#16289]
- VSCode Version: 1.7.2
- OS Version: Windows 7 AMD64

Steps to Reproduce:

1. Launch Visual Studio Code
2. Launch Accessibility Checker, select all verification routines, and click Run Verifications
3. Check the result.
![vscodeverificationresult](https://cloud.githubusercontent.com/assets/14239268/20768210/e36b643e-b6f1-11e6-8153-8954b7443bb9.jpg)

**Comment by bpasero** [comment]
@candybaby407 besides all the errors that get reported, are you actually seeing accessibility issues when you use the product? 

@chrisdias @seanmcbreen I think it would be nice to gather some feedback from people that are actually using VS Code and are in need of our accessibility support. I feel we are not getting a lot of feedback around a11y, they are very rare 👍

**Comment by candybaby407** [comment]
@bpasero We tried to use the automation framework UIAF - Designer to get the physical model of VS Code, but could only get the title bar, which blocks us from creating automation cases.

**Comment by liudavid100** [comment]
@bpasero We also meet the similar issue when try to get the automation ID of VSCode UI controls

**Comment by isidorn** [comment]
We care about real accessibilty issues, not some much about auto generated ones.
Due to that we have no plans to address this in the next 12 months -> closing
