### ISSUE TITLE
Copying the full name of the class from a tooltip produces two unnecessary line breaks

### ISSUE THREAD

**Issue by MurzNN** [microsoft/vscode#162834]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:12:14.256Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-25-generic snap
Sandboxed: No

Very often I need to quickly get the full class name by hovering on its short name, here is a screenshot of this tooltip:
![image](https://user-images.githubusercontent.com/336662/194324749-867c17ae-6e25-4824-9da1-ab07297dd119.png)

But the problem is when I try to select the full class name (the first bold line in the tooltip) via triple-click on manual drag, copy to clipboard and paste the string to the editor, it pastes with two unnecessary line breaks at the end of the line.

Steps to Reproduce:

1. Open some code and hover a mouse cursor under a short class name.
2. Select the full class name from the tooltip via a triple click on the line with the class name.
3. Copy the selected text to the clipboard (Ctrl+C or another way).
4. Paste the copied text to the editor.
5. The class name will be pasted with two unnecessary line breaks at the end!
![image](https://user-images.githubusercontent.com/336662/194324992-09960940-b1c6-40c2-9b8d-f8c80abec6f2.png)

To fix this it seems to me that we just need to replace the `<br/><br/>` in the tooltip template to the `<div>` with a margin?

**Comment by alexdima** [comment]
This is all driven by the hover contents. AFAIK we don't have any code on our side which would add extra `\n` padding in the middle of the hover contents. 

@MurzNN This doesn't reproduce for me when I hover over TS code, so I suspect this is caused by the extension providing the PHP hover. Could you please report this issue against the extension providing the hover?

**Comment by MurzNN** [comment]
Thanks for the investigation, seems yes, so I've posted a bug report here https://github.com/bmewburn/vscode-intelephense/issues/2324
