### ISSUE TITLE
Four states collapse/expand action for the Search Tree

### ISSUE THREAD

**Issue by ypapouin** [microsoft/vscode#162812]
The newly introduced « Search Tree » (#161022, @andreamah ) breaks the Expand/Collapse action that was designed to show/hide in-file result matches.

# Current behaviour

**Expand All**
![image](https://user-images.githubusercontent.com/22446243/194240192-3415341f-6be4-4138-98c4-94c9104bd6e5.png)

**Collapse All**
![image](https://user-images.githubusercontent.com/22446243/194240905-a9143f63-549e-4282-b055-e07a3ef4082c.png)

# Wanted Behaviour

Add intermediate actions (or better: a new button dedicated to theses actions, that would help to not break current folder tree state) : 
- Expand In-file results
- Collapse In-file results

Add these 2 new actions would help to achieve this result:
![image](https://user-images.githubusercontent.com/22446243/194241378-9d549639-dd5c-4715-811b-d99e3eeda9bb.png)

**Comment by ypapouin** [comment]
No it is not related to multi-root, I was just trying to explain that the collapse/expand button behavior is different between 1.72 and 1.72.

For me, in-file results are these, and they can be closed (collapsed) or opened (expanded). I'm using a different terminology to opposite them to the folders/files structure:
![image](https://user-images.githubusercontent.com/22446243/194566245-e1732c7b-2029-4081-92cc-02f66b9b7e80.png)


In VSCode  <= 1.71:
- Expand: Open all in-file results
- Collapse: Close all in-file results

Expanded
![image](https://user-images.githubusercontent.com/22446243/194561361-1d082dbb-909e-46d7-bc3e-2f9c4ac3e263.png)

Collapsed
![image](https://user-images.githubusercontent.com/22446243/194561332-12259e78-2fc1-40bd-8c1e-d4c956455390.png)

Since VSCode  1.72:
- Expand: Expand folder structure + Open all in-file results
- Collapse: Collapse folder structure + Close all in-file results

Expanded
![image](https://user-images.githubusercontent.com/22446243/194563198-defb15a6-ef71-44b6-ad49-cd00e75ad776.png)

Collapsed
![image](https://user-images.githubusercontent.com/22446243/194563323-90be4efb-3c68-46e1-a4de-b9bbf08521e9.png)

To mimic 1.71 collapsed result, you need:
- Make your search
- Collapse All
- View as List
- View as Tree

Tree expanded, In-file results collapsed
![image](https://user-images.githubusercontent.com/22446243/194564025-10554194-47ca-47a9-b509-e123681b3ea5.png)

Thinking about it, the solution could be to keep the current behavior, but pressing ALT+ Collapse/Expand would apply a collapse/expand action only on in-file results:

- Expand: Expand folder structure + Open all in-file results
- Collapse: Collapse folder structure + Close all in-file results
- (ALT + Expand) OR (ALT + Collapse) : IF at least one in-file results is open THEN close all in-file results ELSE open all in-file results WITHOUT changing current tree (means folder expanded/collapsed) state.

**Comment by andreamah** [comment]
Oh ok I think I understand where you're going with this!

Just to get this clear:
When you press the collapse button, you expect all of the individual matches to be hidden, but that isn't happening in the new tree view. Instead, all of the folders are being collapsed.

**Comment by yann-papouin** [comment]
Exactly, that's why I made the ALT modifier suggestion that would help to restore previous functionnality

**Comment by cognominal** [comment]
See also #161929

**Comment by andreamah** [comment]
> Exactly, that's why I made the ALT modifier suggestion that would help to restore previous functionnality

Now that I think about, I think the default functionality should be the collapse the individual matches and only see the files/folders. Similar to how multi-root works, we could probably have a multi-step collapse:

[![Image from Gyazo](https://i.gyazo.com/e1c3bea60e13455d506924bac1607636.gif)](https://gyazo.com/e1c3bea60e13455d506924bac1607636)

Your idea about ALT seems good too, but I don't want to complicate the process if it could just be multi-step.

**Comment by andreamah** [comment]
verif steps:
1. Use tree view in search
2. Use the collapse button to collapse the items
![image](https://user-images.githubusercontent.com/31675041/220483115-f5c5cca5-4bd9-46f5-95d5-b62337540081.png)
3. There should be two steps to the collapse: first hiding the file contents, then collapsing all of the first-level folders.
