### ISSUE TITLE
Migrate to `pnpm` or Yarn 3 (from Yarn 1)

### ISSUE THREAD

**Issue by mrienstra** [microsoft/vscode#162803]
As the [Yarn 1 repo says](https://github.com/yarnpkg/yarn#%E2%84%B9%EF%B8%8F-important-note):
> ## ℹ️ Important note
> 
> This repository holds the sources for Yarn 1.x (latest version at the time of this writing being 1.22). New releases (at this time the 3.2.3, although we're currently working on our next major) are tracked on the [yarnpkg/berry](https://github.com/yarnpkg/berry) repository, this one here being mostly kept for historical purposes and the occasional hotfix we publish to make the migration from 1.x to later releases easier.
> 
> If you hit bugs or issues with Yarn 1.x, we strongly suggest you [migrate](https://yarnpkg.com/getting-started/migration) to the latest release - at this point they have been maintained longer than 1.x, and many classes of problems have already been addressed there. By using the [`nodeLinker` setting](https://yarnpkg.com/configuration/yarnrc#nodeLinker) you'll also have the choice of how you want to install your packages: node_modules like npm, symlinks like pnpm, or manifest files via [Yarn PnP](https://yarnpkg.com/features/pnp).

Yarn timeline (partial):
- January 2019: Work on Yarn 2 began.
- January 2020: Yarn 2 released.
- February 2020: Yarn v1.22.0 released.
- July 2021: Yarn 3 released.
- May 2022: Yarn v1.22.19 released. This is likely the last Yarn 1 release.

I realize this might be a big change, but it seems like one of those things that is better to tackle sooner rather than later.

## pnpm

`pnpm` seems to be very popular nowadays, a lot of high-profile open source projects are using it.

Migrating to `pnpm` would likely require moving from dependabot to renovatebot (see dependabot/dependabot-core#1736).

Here are some `yarn` --> `pnpm` migration PRs:
- Vue: vuejs/core/pull/4766
- Next.js: vercel/next.js/pull/37259
- Vite: vitejs/vite/pull/5060
- Pinia: vuejs/pinia/pull/1179
- Cycle.js: cyclejs/cyclejs/pull/821
- Verdaccio: verdaccio/verdaccio/pull/1884
- Element Plus: element-plus/element-plus/pull/3571
- Agora Flat: https://github.com/netless-io/flat/pull/1442

`yarn` --> `pnpm` migration commits (couldn't locate PRs):
- Browserlist: https://github.com/browserslist/browserslist/commit/6d0c552
- PostCSS: https://github.com/postcss/postcss/commit/ec80417

Microsoft open source projects using pnpm:
- [Rush Stack](https://github.com/microsoft/rushstack) uses pnpm
- The [Fluid Framework](https://github.com/microsoft/FluidFramework) seems to be [working on a migration from npm to pnpm](https://github.com/microsoft/FluidFramework/search?q=pnpm&type=issues)

Also using pnpm:
- SvelteKit: https://github.com/sveltejs/kit
- Prisma: https://github.com/prisma/prisma
- Nhost: https://github.com/nhost/nhost

## Yarn 4

Yarn 4 hasn't quite made it to `4.0.0` status, but it is available to try via [`yarn set version canary`](https://yarnpkg.com/cli/set/version). The official word is that it "may take a couple more months"), but also:
>[...] what's in master is stable, and I'd recommend you to try it. The only notable difference with stable is that we reserve the right to land a couple more breaking changes in future RCs, but in terms of stability it's almost always better to use RCs than stable.

... according to https://github.com/yarnpkg/berry/discussions/4895

See https://github.com/yarnpkg/berry/issues/3591 for v4 breaking changes. I've seen two mentions of people stumbling over `enableGlobalCache` default changing from `false` to `true`. ([Google search: site:yarnpkg.com "enableGlobalCache"](https://www.google.com/search?q=site%3Ayarnpkg.com+%22enableGlobalCache%22))

If Yarn 2+ is chosen, to me it makes more sense to go straight to Yarn 4, rather than Yarn 3. It just seems like a better foundation from which to be prepared for the "ESM future".

_PS: I clearly put a lot more time into sharing `pnpm` resources, if anyone wants to do the same for Yarn 4 (or 3), please do & I'm more than happy to edit the above accordingly._

**Comment by joaomoreno** [comment]
We'll keep this in mind, but we're not touching something which works just fine for now.

**Comment by jasonwilliams** [comment]
In an effort to reduce friction for new contributors I would like to recommend returning to npm. It's already pre-installed with Nodejs so devs can be up and running straight away without needing to configure corepack or download an additional package manager.

I don't believe this project does anything yarn specific or uses any features npm doesn't support.
