### ISSUE TITLE
Debugger unexpectedly steals focus from the debug console

### ISSUE THREAD

**Issue by tbenthompson** [microsoft/vscode#162873]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

I'm using Python mostly but this seems consistent across languages

1. Set a breakpoint.
2. Start a debug session.
3. Hit the breakpoint.
4. Focus the debug console. Type some code...
5. Hit F10 or click the "Step Over" button (or any other step/continue button)
6. The focus is moved to the editor.

This is surprising and not ergonomic to me!

**Comment by roblourens** [comment]
You can change this with the setting `debug.focusEditorOnBreak`
