### ISSUE TITLE
Duplicating a line in VS code should be like Intellij Idea, that is ctr+d , it would be easier and faster to work on VS Code.

### ISSUE THREAD

**Issue by MauryaTech22** [microsoft/vscode#162830]
Duplicating a line in VS code should be like Intellij Idea, that is ctr+d , it would be easier and faster to work on VS Code.

**Comment by gjsjohnmurray** [comment]
You are welcome to change your keybindings.

**Comment by andreamah** [comment]
We likely won't be changing the default keybinding for that, but as @gjsjohnmurray mentioned, you can change your keybindings. See https://code.visualstudio.com/docs/getstarted/keybindings
