### ISSUE TITLE
Gra1

### ISSUE THREAD

**Issue by MChrzcz** [microsoft/vscode#162868]
Type: <b>Bug</b>

gra

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: unavailable_off<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.89GB (7.59GB free)|
|Process Argv|--crash-reporter-id 34bec713-aa63-4fca-9b64-d0c5718b1287|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
phpserver|bra|3.0.2
doxdocgen|csc|1.4.0
harbour|eko|0.0.8
live-html-previewer|hdg|0.3.0
better-cpp-syntax|jef|1.16.1
lang-freebasic|me0|2.0.0
vscode-language-pack-pl|MS-|1.72.10050945
csharp|ms-|1.25.0
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
LiveServer|rit|5.7.9
freebasic|sor|0.0.0
pytkfj-snippets|Sub|0.0.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by aeschli** [comment]
Closing, issue description is incomplete.
