### ISSUE TITLE
Missing docs for ITerminalInstance.freePortKillProcess

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#162840]
https://github.com/microsoft/vscode/blob/19f4680c266b8d236183b74f3406f26e2392ca1f/src/vs/workbench/contrib/terminal/browser/terminal.ts#L918

**Comment by meganrogge** [comment]
I felt like this was self explanatory based on the name

**Comment by Tyriar** [comment]
Since `ITerminalInstance` is used outside terminal land a fair bit I wanted all the methods to be documented. I noticed there are a few others that I didn't added before so I'll do them as part of this.
