### ISSUE TITLE
Command Center is shorter with no folder opened

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#162881]
Seems to repro on both macOS and Windows

<img width="819" alt="image" src="https://user-images.githubusercontent.com/25163139/194409198-96df98fe-8b27-4afd-a05f-b0f442b649a5.png">

<img width="783" alt="image" src="https://user-images.githubusercontent.com/25163139/194409133-66b7e509-d1a1-4331-9879-619bee4d45a2.png">

**Comment by jrieken** [comment]
This is the layout logic, e.g the same for CC and the normal text title

https://github.com/microsoft/vscode/blob/f9928a18462204b6725f141bc9af2303cabd2e82/src/vs/workbench/browser/parts/titlebar/titlebarPart.ts#L396-L413

**Comment by daviddossett** [comment]
I'm looking at the height, not the width. My guess is that the line height of the text was contributing to the overall height. So it has an impact when it's missing.
