### ISSUE TITLE
lightbulb in terminal leading to docs on the command?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#162890]
With the new lightbulb feature in the terminal, it might be cool to experiment with providing documentation if a command fails to run. I made something like this in an extension a while back that used terminal links:
https://marketplace.visualstudio.com/items?itemName=TylerLeonhardt.vscode-terminalcommanddocs

Not sure this should be the default behavior as it could be annoying... but maybe something to play with.

**Comment by meganrogge** [comment]
Our idea w this feature is to provide high confidence actions so as to not be too noisy. We have an `openLink` option that could definitely open to docs.

With https://github.com/microsoft/vscode/issues/145234, extensions will be able to provide that

**Comment by Tyriar** [comment]
As @meganrogge calls out, I'm not sure this is high confidence enough (eg. is almost everyone going to want to do this?). Perhaps this sort of thing should come in with the configuration discussion, for example it could still be registered as a quick fix but by default as a low confidence one that is still available via ctrl+. but doesn't show the lightbulb? The setting could then have 3 states for each quick fix:

```ts
"terminal.integrated.quickFix...": {
  "powershell.docs": "low",
  "blah": "off",
  "git.similarCommand": "high"
}
```

Also keep in mind we'll probably be able to do some clever things when/after we do powershell autocomplete like showing details when hovering over symbols in a command.

@meganrogge this is actually another concern for the extension API; overly aggressive fixes that cause the lightbulb to show up all the time 🤔

**Comment by TylerLeonhardt** [comment]
Yeah I'm definitely not confident that this would be useful for everyone all the time.

Just wanted to throw it out there as a possibility considering it's possible (or almost possible).

Maybe the lightbulb isn't the right place for it. Maybe the status menu (when a command fails) is a more natural place since that has the "rerun command" option, right?

**Comment by meganrogge** [comment]
I think that autocomplete will help w commands and provide docs in the future

**Comment by Tyriar** [comment]
We could also probably add a hover with an action at some point after autocomplete as we'll know more about the command line.

**Comment by Tyriar** [comment]
Let's close for now
