### ISSUE TITLE
Fix getting started `command:toSide`

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#162865]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
- OS Version:

Steps to Reproduce:

1. In Python extension we use `command:toSide` in our walkthrough to open a Python file while user is working with the walkthrough: [link](https://github.com/microsoft/vscode-python/blob/640a9331b6499add7064699f670575d7418920e5/package.json#L112).
2. It occupies more than half of the space and requires adjusting the column again:
![image](https://user-images.githubusercontent.com/13199757/192906434-a798c5c6-a15f-4aa8-82e0-24b651a50957.png)
3. Compare this to bicep extension where it opens up nicely:
![image](https://user-images.githubusercontent.com/13199757/192906482-fd98b856-43b7-42c3-bbbf-6c2ba8446e7a.png)

They used their own command:
```typescript
const document: TextDocument = await workspace.openTextDocument(uri);
return await vscode.window.showTextDocument(
    vscode.ViewColumn.Beside
);
```
which we cannot use in the Python extension. We have to rely on VSCode command itself: `workbench.action.files.newUntitledFile`, so a python file can be opened without waiting for extension to activate.

More context: https://github.com/microsoft/vscode/issues/152920

cc/ @luabud

**Comment by bpasero** [comment]
I am not sure who owns this today, I think Logan?

**Comment by karrtikr** [comment]
I can verify this occupies half space now, although I think it should be opened to the right side like bicep as the main context is still getting started.

**Comment by joaomoreno** [comment]
Verified. I agree it should be opened to the right side, @bhavyaus.

**Comment by bhavyaus** [comment]
> I can verify this occupies half space now, although I think it should be opened to the right side like bicep as the main context is still getting started.

Could you please open another issue for that? Thanks.
