### ISSUE TITLE
JS code changed to HTML when i click "File -- > Save All" to save all files

### ISSUE THREAD

**Issue by RookieDay** [Microsoft/vscode#16280]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|vscode-html-css|ecmel|0.0.30|
|format-php|Kasik96|1.1.2|
|vscode-JS-CSS-HTML-formatter|lonefy|0.2.2|

---

**Steps to Reproduce:**

1. create two file 01.html & 01.js
2. do some modify for 01.html & 01.js file  
3. when in 01.js window , then click "File ---> Save All" , we can find 01.html is ok but 01.js code changed to HTML.
4. when in 01.html window, then click "File --->Save All" , two files saved successfully.

**Attached reproduce steps:**
below .gif is for step3  (we can see 01.js code changed to HTML).
![issue01](https://cloud.githubusercontent.com/assets/19630825/20762554/b325d5aa-b761-11e6-8aa8-da0e954b9480.gif)

below .gif is for step4.  (we can see two files saved successfully)
![issue02](https://cloud.githubusercontent.com/assets/19630825/20762719/47bfea02-b762-11e6-8057-ec552773bb8b.gif)

**Comment by chrmarti** [comment]
@RookieDay Does this occur with all extensions turned off? (Start with `code --disable-extensions`.)

**Comment by RookieDay** [comment]
@chrmarti 
this issue did not occured when i turned off all extensions as you said,  so this issue is from extensions which i installed or maybe it`s not a bug or maybe extensions which i installed have some bug?
Thank u.

**Comment by chrmarti** [comment]
@RookieDay You seem to have at least two extensions with a formatter. Does the problem occur when you disable all extensions except one of the formatter ones? Does the problem occur when both formatter extensions are enabled? (You can disable individual extensions in the Extensions viewlet on the left.)

**Comment by RookieDay** [comment]
@chrmarti 
Hi chrmarti, 
Thanks for you response.
I installed two formatter extensions, as your suggested, i disabled both or one of extensions, it seems not occurred issue, but when i installed these two formatter extensions again, i can`t always reproduced this issue(random reproduced), hmm,i feel a little confused.

![extensions](https://cloud.githubusercontent.com/assets/19630825/20859473/71b0c67a-b99b-11e6-8969-d6075ceca53f.png)

**Comment by chrmarti** [comment]
I think this is from `vscode-JS-CSS-HTML-formatter` because the other formatter extension hasn't updated to the format-on-save API. Moving there.

**Comment by chrmarti** [comment]
This issue was moved to Lonefy/vscode-JS-CSS-HTML-formatter#36
