### ISSUE TITLE
Inability to create files and folders after installing and uninstalling Node.js

### ISSUE THREAD

**Issue by Chinedumeze** [microsoft/vscode#162880]
Unable to write file 'c:\wamp64\www\fetch\cs\index.css' (NoPermissions (FileSystemError): Error: EPERM: operation not permitted, open 'c:\wamp64\www\fetch\cs\index.css')

Lost the ability to create files and folders!

**Comment by lramos15** [comment]
Can you still create files in your Documents / Downloads? This is a native error saying you don't have permission to make files in that directory.

**Comment by Chinedumeze** [comment]
No sir, even Windows File Explorer was affected, sir! But I believe that the guidance you will give me should solve that aspect too.

Thank you very much for your reply,  Sir.

Awaiting guidance,  please Sir.

Ezeribe A. C.



Engr. Ezeribe Adolf


Gwarinpa II,
FCT Abuja, Nigeria 🇳🇬.

Phone: (+234) 803 713 3024;
              (+234) 805 673 5045

________________________________

**Comment by lramos15** [comment]
You will have to make files in a different folder as that folder is protected. Or you can look up how to adjust file permissions on windows, I believe it is in the right click properties menu
