### ISSUE TITLE
Consider moving new Emmet menu items under Edit menu group

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16297]
- VSCode Version: 1.8.0 Insiders
- OS Version: Windows 10

Currently the two Emmet commands (Emmet: Expand Abbreviation, Emmet...) are under the new Selection menu group. The Emmet commands have nothing to do with Selection and might be better under the Edit menu group.

**Comment by chrmarti** [comment]
Makes sense. /cc @egamma @kieferrm

**Comment by chrmarti** [comment]
Tracking as #16253
