### ISSUE TITLE
Add option to open markdown files in preview mode automatically

### ISSUE THREAD

**Issue by benediktms** [microsoft/vscode#162949]
Sometimes I know I will need to read a lot of markdown for a long time e.g. when reading documentation. It would be nice to have the option to automatically open markdown files in preview mode this way I don't have to manually open a file and switch to preview mode every time. Currently I'm kind of hacking around this by setting the following in the settings:
```json
  "workbench.editorAssociations": {
    "*.md": "vscode.markdown.preview.editor"
  }
```
But this also means I can't actually switch back to the editor when I actually need to edit files, I have to got to the settings and remove this snippet.

**Comment by mjbvz** [comment]
That setting is the correct way to do this

To switch back to the text editor, just use the `Reopen with...` command
