### ISSUE TITLE
“Bracket Pair Colorization: Independent Color Pool Per Bracket Type” stopped working

### ISSUE THREAD

**Issue by Melebius** [microsoft/vscode#162932]
Type: <b>Bug</b>

1. Open Settings.
2. Enable `Editor › Bracket Pair Colorization`.
3. Enable `Editor › Bracket Pair Colorization: Independent Color Pool Per Bracket Type`.
4. Type into the editor:
    ```
    {([])}
    {{{}}}
    ```

### Expected result
![expected result screenshot](https://user-images.githubusercontent.com/8669864/194541356-abd6d3a5-ccb2-4805-b5ff-9e86e7a7dd48.png)

### Actual result
![actual result screenshot](https://user-images.githubusercontent.com/8669864/194541033-c3866134-5c46-444c-b46e-1ca030444697.png)

### Details

I enabled this feature as soon as it was introduced in the stable VS Code and liked it very much. Recently I noticed, this feature stopped working and I see all brackets in one color. This happened before 1.72 and was not fixed until the insider release I installed today.

If I turn off “Independent Color Pool Per Bracket Type”, I get all brackets colored (without differentiating their types):

![screenshot with “Independent Color Pool Per Bracket Type” disabled](https://user-images.githubusercontent.com/8669864/194542795-3d1e14b6-38bf-4810-a215-83782d3280da.png)

### System info

VS Code version: Code - Insiders 1.73.0-insider (fad3a77833b9249158dfd88477114a06435e46a2, 2022-10-07T05:18:56.885Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4250U CPU @ 1.30GHz (4 x 1300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 4|
|Memory (System)|4.00GB (0.07GB free)|
|Process Argv|-psn_0_1212712 --crash-reporter-id 4d771bb7-e3a5-4b58-a1d4-eba32d254e27|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aa:30263845
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30568093
vscccc:30564267
pyindex848:30577858

```

</details>

**Comment by RedCMD** [comment]
related to https://github.com/microsoft/vscode/issues/162814
