### ISSUE TITLE
Commit button disabled after resolving merge conflict

### ISSUE THREAD

**Issue by MiSchroe** [microsoft/vscode#162927]
Type: <b>Bug</b>

1. Create branch_a from master.
2. Commit conflicting changes to both master and branch_a.
3. Merge master into branch_a.
4. Change to Source Control view.
5. Resolve the conflict.

Expected result:
- Commit button will be enabled after all conflicts are resolved.

Actual result:
- Commit button remains disabled though the conflicts are resolved.

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.34GB (2.59GB free)|
|Process Argv|--crash-reporter-id b1fe4e87-5475-43b3-bc5f-b64f909d15b9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (63)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
vscode-dbt|bas|0.5.1
armview|ben|0.4.6
vscode-eslint|dba|2.2.6
gitlens|eam|12.2.2
prettier-vscode|esb|9.9.0
dbt-language-server|Fiv|0.11.1
codespaces|Git|1.10.6
vscode-pull-request-github|Git|0.50.0
gitlab-workflow|Git|3.52.0
terraform|has|2.24.2
vscode-guid|hea|1.5.0
vscode-dbt-power-user|inn|0.7.9
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.3.0
vscode-azureappservice|ms-|0.24.4
vscode-azurefunctions|ms-|1.8.1
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.2
vscode-azurestorage|ms-|0.15.0
vscode-azureterraform|ms-|0.3.2
vscode-azurevirtualmachines|ms-|0.6.2
vscode-bicep|ms-|0.11.1
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.2
remote-wsl|ms-|0.72.0
azure-account|ms-|0.11.1
azurecli|ms-|0.5.0
powershell|ms-|2022.8.5
vscode-node-azure-pack|ms-|1.1.0
azurerm-vscode-tools|msa|0.15.7
debugger-for-chrome|msj|4.13.0
databricks-vscode|pai|1.1.4
vscode-data-table|Ran|1.12.0
java|red|1.11.0
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
jinjahtml|sam|0.19.0
scala|sca|0.5.6
snyk-vulnerability-scanner|sny|1.6.1
intellicode-api-usage-examples|Vis|0.2.4
vscodeintellicode|Vis|1.2.28
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
markdown-all-in-one|yzh|3.4.3
biml-support|zbe|1.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vscccc:30566498
pyindex848cf:30577861
40g7c324:30573242

```

</details>

**Comment by diefbell-grabcad** [comment]
Also experiencing this, and the problem also occurs on VSCode Insiders

**Comment by lszomoru** [comment]
Apologies for the inconvenience. This is a recent regression and will be fix in our recovery release later this week.
