### ISSUE TITLE
Feature request: GIT Patch Create/Apply

### ISSUE THREAD

**Issue by paragdiwan** [Microsoft/vscode#16290]
- VSCode Version: 1.7.2
- OS Version: Across all OS

As this feature is frequently use, It would be nice to have feature to create / apply patch within vscode context menu.

**Comment by joaomoreno** [comment]
This can be achieved by an extension.

**Comment by paragdiwan** [comment]
@joaomoreno : May I know which extension ? Haven't noticed any which supports this.

**Comment by joaomoreno** [comment]
I don't think any exists yet. You could make it. 😉

**Comment by paragdiwan** [comment]
:+1:

**Comment by yuristsepaniuk** [comment]
👍

**Comment by paragdiwan** [comment]
@yuristsepaniuk  @joaomoreno  : Created a extension to create/apply patch.  Still imperfect; will make it better over the period of time.
Thanks!
