### ISSUE TITLE
Renaming file when window is not in focus does not work properly

### ISSUE THREAD

**Issue by rbclark** [microsoft/vscode#162961]
Type: <b>Bug</b>

When multiple windows are open on my system running macOS and I right click to rename a file, the filename goes into edit mode however I am unable to actually change the filename since placing focus back on the filename exits edit mode. This is not consistent with how other apps handle this situation and for some reason I find myself running into this situation very often.

Example of how VSCode handles this situation:

https://user-images.githubusercontent.com/2308869/194602967-9122a1e4-3d41-4690-a0cd-0fb64b8fc7cb.mov

Example of how other apps handle this situation:

https://user-images.githubusercontent.com/2308869/194602843-e366115c-2941-45bd-8133-9cb5d9b315e8.mov

VS Code version: Code 1.72.0 (Universal) (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id aa681c69-6b37-47fa-9785-f65d5fcdfe0a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-tailwindcss|bra|0.8.7
gitlens|eam|12.2.2
copilot|Git|1.50.6974
go|gol|0.35.2
haml|kar|1.4.1
vscode-rdbg|Koi|0.0.11
vscode-docker|ms-|1.22.1
remote-containers|ms-|0.255.2
remote-ssh|ms-|0.84.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
sublime-keybindings|ms-|4.0.10
vsliveshare|ms-|1.0.5733
rails-run-spec-vscode|nok|0.1.4
ruby|reb|0.28.1
slim|sia|0.1.2
code-spell-checker|str|2.10.1
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.4.3
vscode-open-in-github|ziy|1.3.6

(1 theme extensions excluded)

</details>

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/149818
