### ISSUE TITLE
Feature request: Add "preLaunchCommand" to launch configuration

### ISSUE THREAD

**Issue by munyirik** [Microsoft/vscode#16293]
In addition "preLaunchTask," it would be useful to have the ability to run a command (in my case from an existing extension) before launching a debug session. 
This can possibly be done with the addition of a "preLaunchCommand : command" pair to launch.json.

**Comment by tripped** [comment]
That would be very handy for common use cases like "I want to automatically rebuild before launching the debugger." In my case I'm using an extension (vscode-rust) that provides relevant build commands, and it would be much nicer to be able to just have one of those run before launch.

**Comment by weinand** [comment]
Closing because we are not planning to implement this within the next 12 months.
