### ISSUE TITLE
'expandLineSelection' selects extra line when used on an empty line.

### ISSUE THREAD

**Issue by akatechis** [Microsoft/vscode#16291]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Home

Steps to Reproduce:

1. Enter the following in a text file:
```
foo

bar
baz
```
2. Move cursor to the empty line (line 2).
3. Press `ctrl+i` to invoke `expandLineSelection` command.
4. The empty line and the line containing 'bar' is selected (I would expect only the empty line to be selected).

Note, if you have multiple empty lines, you can continuously select the empty lines one at a time, but once the cursor reaches the last empty line, the next time you press `ctrl+i`, you'll select both the empty line and the next non-empty line as well.

**Comment by escaton** [comment]
fixed by #15564
