### ISSUE TITLE
Allow to set a default language mode for file without extension

### ISSUE THREAD

**Issue by hiaw** [Microsoft/vscode#1629]
There are many files which does not have extension but still need syntax highlighting. My example is [Fastlane](https://github.com/fastlane/fastlane) where I would need Ruby language syntax highlighting for the extension-less files. 

I can set it manually for each file but if I navigate away and come back, it's back to plain text again. It would be a good customisation option.

**Comment by bpasero** [comment]
You can associate file extensions to modes with our 1.0 release. 
You can give it a try from our insiders release today: http://code.visualstudio.com/Download#insiders
