### ISSUE TITLE
Terminal no more Working in Version 1.72.0

### ISSUE THREAD

**Issue by geoschwa** [microsoft/vscode#162911]
Type: <b>Bug</b>

Since the update this morning to Version 1.7.2 the integrated Terminal shows no more a prompt, and does not respond to "enter", "ctrl+c" or any other keyboard commands.  
So no working with that is possible. 

EDIT:
Disabling the terminal.integrated.shellIntegration fixes the problem

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:47.539Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|15.41GB (7.41GB free)|
|Process Argv|--no-sandbox . --crash-reporter-id 82c82ce4-1e64-49d7-ada4-4336e8936fb8|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
cucumberautocomplete|ale|2.15.2
cypress-snippets|and|1.2.0
jest-snippets|and|1.9.1
shell-syntax|bma|1.0.3
run-cy|cor|0.1.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
xml|Dot|2.5.1
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
vscode-diff|fab|1.4.2
vscode-jest-runner|fir|0.4.57
auto-close-tag|for|0.5.14
vscode-pull-request-github|Git|0.50.0
gitkraken-authentication|git|1.0.3
AWK|lug|0.0.2
vscode-docker|ms-|1.22.1
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
hexeditor|ms-|1.9.9
vscode-jest|Ort|4.6.0
java|red|1.11.0
vscode-commons|red|0.0.6
vscode-xml|red|0.21.0
vscode-yaml|red|1.10.1
markdown-preview-enhanced|shd|0.6.3
vscode-cy-helper|She|1.2.2
es6-mocha-snippets|spo|0.2.2
intellicode-api-usage-examples|Vis|0.2.4
vscodeintellicode|Vis|1.2.28
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
vscccc:30566498
pyindex848cf:30577861
40g7c324:30573242

```

</details>

**Comment by lorenzomorandini** [comment]
I confirm that disabling `terminal.integrated.shellIntegration` seems to fix.

**Comment by niemes** [comment]
thx for the quick fix ! But still painful to not have the integration with the files link and git :/ .

**Comment by domvo** [comment]
Fix doesn't work for me on MacOS 12.3 with zsh. The integrated terminal doesn't work.

**Comment by geoschwa** [comment]
Here the requested Files.
[settings_json.txt](https://github.com/microsoft/vscode/files/9734498/settings_json.txt)
[tracelog.log](https://github.com/microsoft/vscode/files/9734499/tracelog.log)

Nothing fancy in my .zshrc. Just some aliases that are work related, and I cannot share them here

**Comment by meganrogge** [comment]
thanks for those @geoschwa I should've clarified - i'll need the `ptyHost` trace logs

**Comment by geoschwa** [comment]
@meganrogge here, the correct logfile.
[ptyHostLog.txt](https://github.com/microsoft/vscode/files/9743295/ptyHostLog.txt)

**Comment by meganrogge** [comment]
I don't see a `#spawn` log that i'd expect to see - did you create a terminal when you captured those logs?

https://github.com/microsoft/vscode/blob/6ad64356e1ea2f2e44c960519c41e209cf288690/src/vs/workbench/contrib/terminal/browser/terminalTabsList.ts#L115

**Comment by geoschwa** [comment]
@meganrogge I did spawn a Terminal. Nonetheless I did it again, and spawned 4 Terminals.
[ptyHostLog2.log](https://github.com/microsoft/vscode/files/9751009/ptyHostLog2.log)
![terminals_spawned](https://user-images.githubusercontent.com/16822105/194994905-65a5c006-30f4-430a-9333-a9c165a58e60.png)

**Comment by meganrogge** [comment]
can you run `set -x ` in one of your rc files?

**Comment by geoschwa** [comment]
@meganrogge ptyHostLog with "set -x" in .zshrc

[ptyHostLog3.txt](https://github.com/microsoft/vscode/files/9817041/ptyHostLog3.txt)

**Comment by spencerthayer** [comment]
Any progress on this error?

**Comment by meganrogge** [comment]
Pretty sure this has been fixed by now. Let me know if not
