### ISSUE TITLE
Breadcrumbs are incorrect when workspace contains two folders whose `uri`s differ only in query parameters

### ISSUE THREAD

**Issue by isc-bsaviano** [microsoft/vscode#162976]
- VS Code Version: 1.72.0
- OS Version: MacOS Monterey 12.6

Steps to Reproduce:

1. Download and install the [fsprovider-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/fsprovider-sample) extension.
2. Create a `.code-workspace` with the following contents:
```json
{
	"folders": [
		{
			"name": "MemFS - Query1",
			"uri": "memfs:/?param=1"
		},
		{
			"name": "MemFS - Query2",
			"uri": "memfs:/?param=2"
		}
	],
	"settings": {}
}
```
3. Open the workspace and run the `MemFS: Create Files`.
4. Open `file.css` in folder `MemFS - Query1`. Observe that the breadcrumb says that the file is located in `MemFS - Query2`even though you opened it from `MemFS - Query1`:
<img width="696" alt="Screen Shot 2022-10-07 at 1 31 58 PM" src="https://user-images.githubusercontent.com/44776135/194616274-ad1235a8-be0e-4f0b-9912-3cd8dacf7259.png">

It appears that the breadcrumb always reports that file is located in the *last* workspace folder that the file's `uri` is a child of, even though the `uri`s have different query parameters.

**Comment by bpasero** [comment]
For figuring out which folder a file belongs we use:

https://github.com/microsoft/vscode/blob/391235a7e97e040ef0ad4e5cc42289447408d3d9/src/vs/platform/workspace/common/workspace.ts#L367-L373

**Comment by sandy081** [comment]
This is as per design - https://github.com/microsoft/vscode/pull/146859

CC @bpasero
