### ISSUE TITLE
TypeScript code formatting

### ISSUE THREAD

**Issue by arlandantas** [microsoft/vscode#162987]
Type: <b>Bug</b>

I just updated the IDE and then the code is not being formatted as usualy.
The constants, variable, string, comments collors are not correct.
The autocomplete is also not working as expected.

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:47.539Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 3210)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|15.31GB (7.45GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 9eca22c2-c829-4d24-ac1e-1f57829ec3db|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sql-formatter|adp|1.4.4
laravel-extra-intellisense|ami|0.6.2
vscode-intelephense-client|bme|1.8.2
vscode-eslint|dba|2.2.6
javascript-ejs-support|Dig|1.3.1
gitlens|eam|12.2.2
prettier-vscode|esb|9.9.0
vscode-pull-request-github|Git|0.50.0
go|gol|0.35.2
vscode-graphql-syntax|Gra|1.0.4
vscode-env|Iro|0.1.0
git-graph|mhu|1.30.0
easy-less|mrc|1.7.4
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
java|red|1.11.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
rust|rus|0.7.8
vscode-blade-formatter|shu|0.18.2
php-formatter|Sop|0.2.4
volar|Vue|1.0.0
vscode-typescript-vue-plugin|Vue|1.0.0
php-debug|xde|1.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by gustavotoyota** [comment]
Same thing here. I thought I was going crazy haha. Here's one example:
![Screenshot from 2022-10-07 15-26-41](https://user-images.githubusercontent.com/11639451/194639577-e2512319-bfe5-4e41-8270-ef9219eb0d7c.png)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by arlandantas** [comment]
I've made some tests with insiders build and the bug is not happening.

**Comment by arlandantas** [comment]
After disable some extensions the IDE looks back to normal function. Thanks for answering.

**Comment by gustavotoyota** [comment]
It doesn't seem to be happening with extensions disabled. It tested a little bit and it appears to be a Volar issue.

**Comment by olyop** [comment]
For me the problem was no typescript suggestions showing. I disabled Volar and all back to normal.

**Comment by zhixiangyao** [comment]
Same thing here. Here's one example:

Close the file and reopen it. It can fix it. (It cannot be permanently repaired)

<img width="606" alt="image" src="https://user-images.githubusercontent.com/49728521/194693400-7931a5e8-6070-4f52-8fc7-b45eca0e0c07.png">

**Comment by zhixiangyao** [comment]
> It doesn't seem to be happening with extensions disabled. It tested a little bit and it appears to be a Volar issue.

thx!!!

**Comment by zhixiangyao** [comment]
> For me the only problem was no typescript suggestions showing. I disabled Volar and all back to normal.

thx

**Comment by reitbauer** [comment]
Same here. Downgrade to Volar 0.40.13 and everything works normal

**Comment by arlandantas** [comment]
It seems that disabling or downgrading volar solves the problem.
Thank you for helping!

**Comment by gustavotoyota** [comment]
Updating to the latest version (1.0.3) solved the problem for me.
