### ISSUE TITLE
Increase terminal.integrated.scrollback to 2000

### ISSUE THREAD

**Issue by Brian-Bartels** [microsoft/vscode#162983]
https://github.com/microsoft/vscode/blob/b91245de85dc5429ad340fa491abaa4510da4ec4/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts#L262

This line hasn't been changed for 3 years. And that was just a move. So as far as I can tell, this hasn't been changed in many many years (maybe ever). Computers continue to get faster, so I believe that the average user could easily handle 2000 lines of history. The benefit would be less frustration when running commands that spit out more than 1k lines of output.

**Comment by meganrogge** [comment]
I believe this was chosen for a reason (probably performance) @Tyriar what do you think ?

**Comment by Tyriar** [comment]
I still think 1000 is a good number, keep in mind that doubling this will double the amount of memory used by the terminal and make certain things slightly slower as well. The numbers like memory are fairly small, but they get 10x biffer when you have 10 terminals open. Resize is also particularly relatively expensive as reflowing text is an `O(n)` operation.

It's easy to increase if it is an issue and as of yesterday is also called out better in the documentation https://code.visualstudio.com/docs/terminal/basics#_navigating-the-buffer

**Comment by Tyriar** [comment]
Kind of a bad time to ask as I've been diving deep into overall performance recently 😉

**Comment by Brian-Bartels** [comment]
I'll make sure to ask again in 1yr when maybe you aren't working on performance ;) I'm happy with this resolution. Thanks for the background
