### ISSUE TITLE
Unmet peer dependency warning in npm install of html extension

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16292]
![image](https://cloud.githubusercontent.com/assets/22350/20771073/3e564606-b748-11e6-9287-58a5922efa7f.png)

**Comment by aeschli** [comment]
It's not related to the html extension, but to our main package.json
@dbaeumer Dirk, you updated gulp-tsp that wants typescript@2.0.10, but our vscode package.json still depends on "typescript": "2.0.3",
I suggest we update that one to 2.0.10

**Comment by joaomoreno** [comment]
2.0.10 breaks the formatter, just like 2.0.6 did. Microsoft/TypeScript#12175

cc @egamma

**Comment by dbaeumer** [comment]
TS only fixes this in 2.1.3. Will have to wait until this becomes the default.

**Comment by dbaeumer** [comment]
npm install typescript still installs 2.0.10.

**Comment by dbaeumer** [comment]
OK. Since this is a warning and everything seems to work I opt to postpone this to the debt week and adopt 2.1.x in gulp-tsb which we need to do anyways.

**Comment by dbaeumer** [comment]
This seems to work now. Matt adopted 2.1.5.
