### ISSUE TITLE
Commit interface error

### ISSUE THREAD

**Issue by Jose-Vinicius** [microsoft/vscode#162908]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.0
- OS Version: Windows 10

Steps to Reproduce:

1. The problem is this duration when I open the part to make a new commit for my projects, not directly harming the result but interfering with the experience

2.
![Captura de tela 2022-10-06 224922](https://user-images.githubusercontent.com/70924237/194449645-22f58a79-bdd1-4e7d-aee3-8811092a0a65.png)

**Comment by lszomoru** [comment]
@TylerLeonhardt, any idea what went wrong here? Is this just a localization bug?

**Comment by TylerLeonhardt** [comment]
@lszomoru this looks ok to me:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/2644648/194604183-6f5dcce7-eeb2-4722-ab23-728b612c1bcd.png">
And the string seems ok:
https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-pt-BR/translations/extensions/git.i18n.json#L230-L234

@Jose-Vinicius couple of questions:
1. do those buttons do different things? You can see in my screenshot that they normally have different behaviors.
2. Could you uninstall and reinstall the Portuguese language pack just in case something messed up in the installation?
3. Can you try in the VS Code Insiders build to see if this is fixed there?: http://code.visualstudio.com/insiders

**Comment by Jose-Vinicius** [comment]
@TylerLeonhardt,
   I did what you said I installed the language pack, and now it works correctly again, thanks a lot for the help.

**Comment by TylerLeonhardt** [comment]
Thanks! Glad you're unblocked. I'll go ahead and close this but will investigate further if more folks chime in saying they had the same issue.
