### ISSUE TITLE
Class, ID Double quotes no suggestion is showing.

### ISSUE THREAD

**Issue by mdrakibur179** [microsoft/vscode#162963]
Type: <b>Bug</b>

Class, ID Double quotes no suggestion is showing. But when I click anywhere and then click into the double quotes then it shows the suggestion(auto complete). 

I need to click somewhere to use suggestions or I need to move cursor right or left by pressing arrow key of my keyboard, then again when cursor is into the quotes it is showing suggestion. Otherwise it doesn't show any suggestion.

I am using Windows 11 Pro.

Suggestion is not showing.
![image](https://user-images.githubusercontent.com/115276185/194601693-08c935eb-82b5-4b89-9010-5a0ee2c9a437.png)

<br>

Suggestion is showing after clicking outside of the quotes and then again clicking into the quotes.
![image](https://user-images.githubusercontent.com/115276185/194601784-7c92a3a4-5e2b-49ca-ae1f-51b947a8c4d1.png)

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600G with Radeon Graphics          (12 x 3893)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.35GB (10.88GB free)|
|Process Argv|--crash-reporter-id bbd52116-1210-4e5e-b3f1-6b22a5d03c61|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.8.7
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
python|ms-|2022.16.0
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
vsccc:30566497
pyindex848:30577860
40g7c324:30573242

```

</details>

**Comment by jrieken** [comment]
When a snippet is active, IntelliSense as you type (aka quick suggestions) is disabled. That is because there is a conflict between the <kbd>Tab</kbd>-key which moves to the next placeholder but also accepts a completion. You wouldn't be able to type in a placeholder and then move to the next placeholder as you would accept a suggestion then. You have the following options

* change the default via the `editor.suggest.snippetsPreventQuickSuggestions`-setting
* in snippets trigger suggestions manually (via Ctrl+Space, Alt+ESC (macOS), or `ctrl/cmd+i`)
