### ISSUE TITLE
Please allow Sticky Scroll to be based on indentation instead of scope

### ISSUE THREAD

**Issue by bitsoflogic** [microsoft/vscode#162904]
Simply show the line at the top of each of the indent guides to the left of the text where you're at.

```
500 async function doSomething() { 
501   try { 
535     if (user.isActive) {  
580       for (const account of accounts) {
// --- Sticky scroll border --- 
675         //
676         // This is where I happen to be in the scrolling... 
677         // 
```

This provides valuable context about where you are within the flow of code. To me, it makes the feature as intuitive as freezing Excel headers.

**Comment by jrieken** [comment]
Yeah, I like that. In the lack of the extension provide outline info we do fallback to the folding model, which in return falls back the indentation model. We could add an explicit setting for this
