### ISSUE TITLE
Open and Open Folder don't work

### ISSUE THREAD

**Issue by EmberRandall** [microsoft/vscode#162998]
Type: <b>Bug</b>

Clicking on File -> Open or File -> Open Folder... appears to do nothing after the most recent update. Other menu items seem to behave fine, but I can't open up new folders anymore. I've restarted both VSCode and my computer, and neither fixed the issue.

VS Code version: Code 1.72.0 (Universal) (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin arm64 21.3.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 8, 7|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id 1c44fd60-768f-4f92-8a5a-7175b3d85205|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
solargraph|cas|0.24.0
prettier-vscode|esb|9.9.0
ruby|reb|0.28.1
vscode-ruby|win|0.28.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by EmberRandall** [comment]
That also doesn't seem to be working, unfortunately -- whether I run it from the extensions panel or cmd-shift-p, nothing happens.

<img width="546" alt="image" src="https://user-images.githubusercontent.com/1414941/194672935-0f90cb99-ed3d-4516-a072-283075d36115.png">
<img width="637" alt="image" src="https://user-images.githubusercontent.com/1414941/194672962-dd9f73e9-6130-4b1e-a6d4-2c00ec2cc1c4.png">

**Comment by gjsjohnmurray** [comment]
Please try launching VS Code from a command prompt like this

code --disable-extensions

**Comment by EmberRandall** [comment]
Looks like that does fix the problem! How do I fix it more permanently (since I'd like to keep the extensions if possible)?

**Comment by lramos15** [comment]
Your best bet is if bisect isn't working to do it manually by disabling half your extensions and then trying to narrow down which one is causing you problems. You can then uninstall that one and file a bug on them
