### ISSUE TITLE
Text is broken in vscode

### ISSUE THREAD

**Issue by SyedHasan110** [microsoft/vscode#162935]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.73.0-insider
Commit: fad3a77833b9249158dfd88477114a06435e46a2
Date: 2022-10-07T05:18:21.081Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.13-arch1-1
Sandboxed: Yes

![Screenshot from 2022-10-07 17-32-28](https://user-images.githubusercontent.com/70736490/194549620-24722b65-c822-4d21-9718-99f0424772d2.png)

The text below the vscode icon is broken.

**Comment by SyedHasan110** [comment]
> Does the issue repro when you launch with `--disable-gpu` ?

No, the issue is gone with this flag.

**Comment by deepak1556** [comment]
This might get addressed in new runtime, until then continue to disable hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
