### ISSUE TITLE
Title Bar Actions Not Refreshed In Some Scenarios 

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16298]
Discovered while investigating #12837

**Bug**
Title bar actions with same id but different arguments are not properly handled in `titleControl.ts`. An action with a command will not be replaced by a new one with the same command but a different argument.

You can see this in the following scenario:

1. Create workspace with two md files, `a.md` and `b.md`.
2. Open previews for both files.
3. Open the preview for `a.md` again.
4. Switch to the preview for `b.md`.
5. Click the show source button in the `b.md` preview.

The editor switches to `a.md` instead of `b.md`.

Both the `a.md` and `b.md` previews register the same action (`markdown.showSource`) but with different arguments (the document URI in this case). We calculate these title actions correctly in both cases, but do not refresh them when switching to the `b.md` preview from the `a.md` preview because of this logic:

https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/titleControl.ts#L402

That line looks only at the action ids, which are both `markdown.showSource`, so we do not update the action in the UI.

**Potential Fix**
Check argument when comparing actions

**Comment by mjbvz** [comment]
@bpasero Any thoughts on what the proper fix would be for this? Removing the command array equality check entirely would work but I'm guessing it was added for performance reasons or handle some other scenario.

**Comment by bpasero** [comment]
@mjbvz very happy you found this because I also noticed this a while ago and could not pin point it. Since at my place I do not know what arguments are inside those actions, I have to re-add them to the toolbar. I do not think this would be a big perf hit, but we will see :)
