### ISSUE TITLE
Code actions widget has hover feedback on headers which are not interactable

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#162952]
![Recording 2022-10-07 at 07 45 16](https://user-images.githubusercontent.com/2193314/194581250-f7a2c9e7-fffb-4ac3-b8a7-0ce6f6340f43.gif)

Version: 1.73.0-insider (user setup)
Commit: fad3a77833b9249158dfd88477114a06435e46a2
Date: 2022-10-07T05:18:17.049Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by daviddossett** [comment]
Hm, can't repro this on mac or PC. Are you seeing this in every instance of the code actions widget?

**Comment by Tyriar** [comment]
Seems to be, I can't DOM inspect it easily as it relies on focus

**Comment by Tyriar** [comment]
This also allows keyboard focus which is also bad because it's non-interactable. cc @meganrogge

**Comment by meganrogge** [comment]
cannot reproduce on macOS

**Comment by Tyriar** [comment]
If it's only in production and !important fixed I'm guessing the CSS order is different when bundled? The hover rule probably just needs something like `:not(.header)`

**Comment by justschen** [comment]
@Tyriar I wasn't able to repro in mac or pc with either insiders or in production today. Have you still been running into this? I did have a fix on https://github.com/microsoft/vscode/issues/187492 which should be in insiders now, but I'll keep digging to see if it may be related.

**Comment by Tyriar** [comment]
@justschen it's working for me now. Something you might want to consider changing is the blue color for the headers as blue text typically indicates a link. Maybe a small topic for the UX sync?
