### ISSUE TITLE
View badge extension API documentation wrong

### ISSUE THREAD

**Issue by cnshenj** [microsoft/vscode#162900]
Does this issue occur when all extensions are disabled?: Not relevant

- VS Code Version: 1.72.0
- OS Version: Windows Version 10.0.22621.521

Steps to Reproduce:

1. Create a view badge in an extension
2. Remove the badge by setting the `badge` property to `undefined` - as described by the [doc](https://code.visualstudio.com/api/references/vscode-api#TreeView%3CT%3E):
    > The badge to display for this TreeView. To remove the badge, set to undefined. 

Expected:
Badge removed.

Actual:
Badge unchanged.
```
Exception has occurred: TypeError: Cannot read properties of undefined (reading 'value')
```

Workaround:
This might be the actual design. Setting `badge` property to `{ value: 0, tooltip: "" }` properly removes the badge.

**Comment by ArturoDent** [comment]
Yes, it is confusing.  Only `{ value: 0, tooltip: "" }` seems to work but I would think in some situations `0` would actually be valid information.  In any case `undefined` doesn't work in

```js
this.tabView.badge = {value: undefined, tooltip:''};  // doesn't work
this.tabView.badge = undefined;                       // doesn't work
```

**Comment by Lakshmikanth2001** [comment]
> Yes, it is confusing. Only `{ value: 0, tooltip: "" }` seems to work but I would think in some situations `0` would actually be valid information. In any case `undefined` doesn't work in
> 
> ```js
> this.tabView.badge = {value: undefined, tooltip:''};  // doesn't work
> this.tabView.badge = undefined;                       // doesn't work
> ```
Thank You for the work aroud
