### ISSUE TITLE
Merge editor saves files using the wrong newlines

### ISSUE THREAD

**Issue by jakebailey** [microsoft/vscode#162999]
Type: <b>Bug</b>

When rebasing a big change on the TypeScript codebase today, I ended up with a diff that didn't make sense; I traced it down to having committed the wrong newlines.

I am in WSL2, so the line ending VS Code uses is LF. However, the TS repo's files are CRLF, and are checked out as CRLF even on Linux. (Normally, VS Code saves LF, then I convert it to CRLF after a lint rule complains; in the future I'll probably just use the line ending setting and hope it works.)

When I was rebasing, I hit a merge conflict; I opened the conflicted file in the source control view, and did my merge. But, when I committed the file, it appears as though the file was saved as LF and I committed it like that. I ended up having to rebase my whole stack again and run unix2dos on each until I restored the line endings.

I recall something in the update blog post mentioning that the merge editor was implemented by reconstructing a new document from the two input files; perhaps this isn't taking into account the line endings of the original files? I don't recall this happening in previous versions.

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.57.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (47.47GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/jabaile/work/TypeScript --remote=wsl+Ubuntu --crash-reporter-id ffd813dd-a264-4f03-8c00-e2403d747bb6|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.57.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|Memory (System)|31.23GB (29.01GB free)|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-wsl|ms-|0.72.0
atom-keybindings|ms-|3.0.9
material-theme|zhu|3.15.5
gitlens|eam|12.2.2
todo-tree|Gru|0.0.215
vscode-duplicate|mrm|1.2.1
js-debug-nightly|ms-|2022.10.617
vscode-typescript-next|ms-|4.9.20221006

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
40g7c324:30573242

```

</details>

**Comment by hediet** [comment]
I cannot reproduce.

> I recall something in the update blog post mentioning that the merge editor was implemented by reconstructing a new document from the two input files; perhaps this isn't taking into account the line endings of the original files? I don't recall this happening in previous versions.

It should use the line-endings style from the result file.

**Comment by jakebailey** [comment]
This just occurred to me again just the following day; I can reproduce this with a cherry pick, so that is probably going to be easier for me to make an examples with. I'll try and make one.

**Comment by jakebailey** [comment]
Yes, that's correct, not the inline one where it's just sugar on top of a file with the `>>>>>` lines.

**Comment by jakebailey** [comment]
I've made an example repo here: https://github.com/jakebailey/vscode-issue-162999

It reproduces reliably for me. Here's a screencast.

![vscode-issue-162999](https://user-images.githubusercontent.com/5341706/194926664-8fb5029f-268f-4a6d-aab0-28b187a3fc20.gif)

**Comment by hediet** [comment]
Thank you, I can reproduce it now!
Unfortunately it always resets the EOL to LF (in my test, I checked if LF files stay LF files after merging, as CRLF is the default on my system).
I (implicitly) assumed `textModel.setValue` would normalize the EOL style the same way `textModel.applyEdits` does, which is apparently not the case.

**Comment by hediet** [comment]
Verification steps:
* Have a conflict in a repo where all files are CLRF
* Solve the conflicts in the new merge editor and complete the merge
* Ensure the staged file also has CRLF line endings

Do the same with LF files.
