### ISSUE TITLE
Consider renaming Preferences > Keymaps to Keymap Extensions

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16294]
As a user, I may not understand the difference between Preferences > Keyboard Shortcuts and Keymaps.
Calling out that Keymaps is really Keymap Extensions makes it clear that it isn't an in-product setting and they will be using an extension.
This also helps clarify what a "Keymap" is since the term doesn't exist except as a VS Code extension category.

**Comment by waderyan** [comment]
This was a suggestion from @egamma as well. If I remember correctly, @chrisdias's thought was that exposing the implementation was unnecessary. 

@gregvanl's perspective here is valid though. Although "keymap" is used in other products (see WebStorm), I was initially unfamiliar with the term.
