### ISSUE TITLE
a11y: diff: Line diff colors muddy up char diffs.

### ISSUE THREAD

**Issue by jtagcat** [microsoft/vscode#163063]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0
- OS Version: Fedora 36 KDE

![image](https://user-images.githubusercontent.com/38327267/194717864-e8fe8518-5715-403a-bc9d-30caed9eef60.png)

It has been difficult for me to view diffs quickly. The line diffs create noise (in contrast) with character diffs. It'd be much clearer if only the line numbers showed line diffs:

![image](https://user-images.githubusercontent.com/38327267/194718113-ae2b2b2d-2d17-4efa-9090-2e5fa76e3056.png)

**Comment by alexdima** [comment]
@jtagcat You can customize this by changing the `diffEditor.*` colors. e.g.:
```
	"workbench.colorCustomizations": {
		"diffEditor.insertedLineBackground": "#00000000",
		"diffEditor.removedLineBackground": "#00000000",
		"diffEditor.insertedTextBackground": "#009000aa",
		"diffEditor.removedTextBackground": "#9e0000aa",
	}
```
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/5047891/194807085-d88d2163-d043-4d14-b162-be2a836381aa.png">

**Comment by jtagcat** [comment]
I didn't find it in settings before. Thanks.

**Comment by jtagcat** [comment]
If the lines are not wrapped, it's hard to notice the (off-screen) diff. There are indicators next to line numbers, but it's not clear. Could there be a separate color used for line numbers bars?

**Comment by alexdima** [comment]
@jtagcat There are many colors, including for the line numbers. Use `ctrl+space` to discover them. 

<img width="540" alt="image" src="https://user-images.githubusercontent.com/5047891/199030080-92214ace-1f74-4005-ad1a-005639af11ca.png">

**Comment by jtagcat** [comment]
Thanks. For searcher's reference (dark theme):
```
  "workbench.colorCustomizations": {
    "diffEditor.insertedLineBackground": "#9bb9550a",
		"diffEditor.insertedTextBackground": "#9ccc2c3f",
    "diffEditorGutter.insertedLineBackground": "#9bb95533",
    "diffEditorGutter.removedLineBackground": "#ff000033",
		"diffEditor.removedLineBackground": "#ff00000a",
		"diffEditor.removedTextBackground": "#ff00003f",
  },
```

You can get default values with `workbench.action.generateColorTheme`.
