### ISSUE TITLE
Strange UI font rendering in Linux

### ISSUE THREAD

**Issue by anvltu** [microsoft/vscode#163068]
I'm having issues with font rendering in VS Code UI as shown in the attached screenshot. The same glitches are in the breakpoints list window during debug.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0
- OS Version: Manjaro with all latest updates

Steps to Reproduce:

1. Start VS code

![Снимок экрана от 2022-10-08 22-49-57](https://user-images.githubusercontent.com/75672916/194721240-7c65d153-b216-436a-b587-640c251a54d5.png)

**Comment by deepak1556** [comment]
Please try disabling hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
