### ISSUE TITLE
This is a p o s

### ISSUE THREAD

**Issue by cane2nd** [microsoft/vscode#163025]
Type: <b>Bug</b>

wants to Launch jason 
will not run
will not debug
this s$%*^% is costing me a letter grade in C programg for Sci & Eng
so what shall we do?

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.54GB free)|
|Process Argv|--crash-reporter-id 7b338b95-4e85-4451-8063-35ec9b773783|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
spellright|ban|3.0.90
c-cpp-compile-run|dan|1.0.15
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
vscode-phpmd|eco|1.3.0
prettier-vscode|esb|9.9.0
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
c-cpp-runner|fra|4.1.1
path-autocomplete|ion|1.22.1
cpptask|kay|0.0.1
vscode-phpfmt|kok|1.0.31
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.21.0
java|red|1.11.0
LiveServer|rit|5.7.9
open-in-browser|tec|2.0.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.4
vscodeintellicode|Vis|1.2.28
vscode-java-debug|vsc|0.44.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
php-debug|xde|1.28.0
php-intellisense|zob|1.0.11

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by roblourens** [comment]
Sorry for the trouble. Please file an issue on the debug extension that you're using.
