### ISSUE TITLE
A frosty screen is displayed

### ISSUE THREAD

**Issue by nirilajay** [microsoft/vscode#163070]
Type: <b>Bug</b>

The display is frosty after using the vs code for some time . Updating and reinstalling are not seems to work

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.88GB (1.34GB free)|
|Process Argv|--crash-reporter-id 0cde727e-398d-499a-be21-46869546d90c|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
latex-workshop|Jam|8.29.0
solidity|Jua|0.0.141
csharp|ms-|1.25.0
html-preview-vscode|tht|0.2.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848cf:30577861
40g7c324:30573242

```

</details>
![Screenshot 2022-10-09 000602](https://user-images.githubusercontent.com/86144656/194743369-50badd0d-9a07-4905-a835-e537747380be.png)

**Comment by nirilajay** [comment]
![Screenshot 2022-10-09 000602](https://user-images.githubusercontent.com/86144656/194743496-aac463fc-46d8-4dc7-9bb1-752454f1ef68.png)

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/124226

You can disable hw acceleration following the steps in https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration to serve as a workaround.
