### ISSUE TITLE
version 1.72 Bug(Terminal font blur)

### ISSUE THREAD

**Issue by Jtc985310527** [microsoft/vscode#163094]
Type: <b>Feature Request</b>

After updating to the new version 1.72, the terminal font is blurred and ghosting occurs

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.17763
Modes:
Sandboxed: No

**Comment by Aman123lug** [comment]
@VSCodeTriageBot is this contribution valid for hacktoberfest

**Comment by New-dev0** [comment]
![image](https://user-images.githubusercontent.com/69723581/194754914-fadc56b7-d11b-42eb-8a22-683cef5c8561.png)
you mean, like this right ?

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
