### ISSUE TITLE
格式化代码之后，后面部分代码无法按照主题颜色显示，全部显示为白色

### ISSUE THREAD

**Issue by feijie825** [Microsoft/vscode#16305]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|GBKtoUTF8|bukas|0.0.1|
|Theme-azure|gerane|0.0.2|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.4|

---

Steps to Reproduce:

1.选择格式化代码选项。
2.查看.h文件后半部分。

**Comment by recolic** [comment]
That's so ...... of you to open an issue in Chinese......

**Comment by rebornix** [comment]
He is saying after code formatting, the second half of the code (`.h` file) has no colorization.

**Comment by chrmarti** [comment]
@feijie825 Does this always occur with the same file? If so, could you attach the file?

**Comment by mjbvz** [comment]
Closing as we need more info to investigate.

@feijie825 If this still happens in VSCode 1.8.1, please provide an example file so that we can investigate

Thanks
