### ISSUE TITLE
C# Program

### ISSUE THREAD

**Issue by shinkoi01** [microsoft/vscode#163078]
Type: <b>Bug</b>

After I click Run on VSC - I need to select the .net extension for debugging. It says the .Net Core is running. Coding is all correct, simple beginner program but there is no Output on the Terminal that is visible

Downloaded and installed the normal and dev SDK, all the extensions on VSC

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 2300U with Radeon Vega Mobile Gfx   (4 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|6.96GB (1.70GB free)|
|Process Argv|--crash-reporter-id 88e21815-82fa-4e33-a249-cd001ac8e95d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
asp-net-core-switcher|adr|2.0.2
netcore-snippets|dog|3.15.2
ev3dev-browser|ev3|1.2.0
scaffold|fir|1.0.0
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.8
auto-using|Fud|0.7.15
Ionide-fsharp|Ion|7.2.3
csharpextensions|jch|1.3.1
nuget-reverse-package-search|jes|0.1.68
vscode-nuget-package-manager|jmr|1.1.6
csharp-netcore-extensionpack|jol|1.0.0
vscode-csharp-snippets|jor|1.1.0
docomment|k--|0.1.31
csharpextensions|kre|1.7.3
ev3-micropython|leg|2.0.0
dotnet-core-commands|mat|1.0.6
csharp|ms-|1.25.0
dotnet-interactive-vscode|ms-|1.0.3504060
vscode-dotnet-pack|ms-|1.0.9
vscode-dotnet-runtime|ms-|1.5.0
vscode-dotnet-sdk|ms-|0.8.0
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-bindings-vscode|ms-|0.3.0
sql-database-projects-vscode|ms-|0.19.0
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
jupyter|ms-|2022.9.1002791758
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
aspnet-helper|sch|0.6.4
msbuild-project-tools|tin|0.4.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
fc301958:30573243

```

</details>

**Comment by roblourens** [comment]
Please file this on the csharp extension repo with more details
