### ISSUE TITLE
How to point to PHP executable?

### ISSUE THREAD

**Issue by TRE8** [Microsoft/vscode#16309]
- VSCode Version: 1.7.2
- OS Version: Max osX 10.11

Steps to Reproduce:

Hi, I'm trying to point VSCode to my PHP executable.  I'm on a Mac and using MAMP Pro, which I believe is the PHP executable that I'm suppose to point to.  

I've gone into settings.json and added this line:

```
// Points to the php executable.
"php.validate.executablePath":  "/Applications/MAMP/bin/php/php7.0.12/bin"
```

Here's an image to help if needed.
![screen shot - 2016-11-30 at 9 37 46 pm](https://cloud.githubusercontent.com/assets/20779835/20782946/48e8af76-b745-11e6-99eb-06ce1371f910.png)

Not sure if I entered the file path wrong or if I should use a different one, it doesn't seem to click.  I still get a message that PHP executable is not connected to VSCode.

Also, new to Github and trying to tag this as a question but don't see an option to tag a label to this post.

**Comment by chrmarti** [comment]
The path needs to point at the php executable. (See https://code.visualstudio.com/Docs/languages/php.)

**Comment by TRE8** [comment]
Thanks, I see in the docs it says
`{
    "php.validate.executablePath": "c:/php/php.exe"
}`

But I'm on a Mac :/

Can't seem to figure out where the PHP executable is located.

**Comment by chrmarti** [comment]
Have you tried `"php.validate.executablePath":  "/Applications/MAMP/bin/php/php7.0.12/bin/php"`?

**Comment by TRE8** [comment]
Good idea and I tried your suggestion but still get the message

> The language server needs at least PHP 7 installed. Version found: 5.5.30

I tried adding ~ before "/Application" and got the following message:
`"php.validate.executablePath": "~/Applications/MAMP/bin/php/php7.0.12/bin/php"`

> Cannot validate the php file. The php program was not found. Use the 'php.validate.executablePath' setting to configure the location of 'php'

**Comment by chrmarti** [comment]
This issue was moved to felixfbecker/vscode-php-intellisense#37
