### ISSUE TITLE
History search with `fzf` is broken in the VSCode integrated terminal

### ISSUE THREAD

**Issue by scheibo** [microsoft/vscode#163028]
Type: <b>Bug</b>

1. Install [`fzf`](https://github.com/junegunn/fzf) which will install keybindings for bash, including setting up a keybinding on Ctrl + R for history search
2. Type Ctrl + R in the VSCode integrated terminal and select a command from bash history
![Screen Shot 2022-10-07 at 19 51 56](https://user-images.githubusercontent.com/117249/194684610-69f37c4b-5323-44ab-a9c1-c21cd528e95d.png)
3. VSCode then adds `^[]633;C^G^[]633;E;__fzf_history__^G` to the start of the command, breaking things
![Screen Shot 2022-10-07 at 19 52 10](https://user-images.githubusercontent.com/117249/194684613-a7b77bd3-d043-45f2-b75b-97deb9ddd22c.png)

I don't think this is a `fzf` issue given `fzf` works fine in iTerm2/Mac Terminal, and used to work in VSCode until around a month ago.

The only possibly related bugs I could find were #120825 and #120352, but the fix from those bugs (`"terminal.integrated.localEchoLatencyThreshold": -1`) did not appear to change anything.

VS Code version: Code 1.72.0 
(Universal) (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 7, 5|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--disable-extensions example.js --crash-reporter-id 79432e7f-4a1f-43a9-8f9b-83374fb3df76|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30583747
fc301958:30573243

```

</details>

**Comment by Tyriar** [comment]
@scheibo does disabling shell integration workaround the problem? `"terminal.integrated.shellIntegration.enabled": false`

**Comment by falkben** [comment]
I recently had my terminal search history stop working with zsh. Disabling `terminal.integrated.shellIntegration.enabled` and restarting my integrated terminal fixed it for me as well.  I only just started seeing this issue in the latest release (1.74.0). I am also running oh my zsh.

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/168396

will be fixed in the recovery build
