### ISSUE TITLE
Possible missing icon on debug disconnect action

### ISSUE THREAD

**Issue by zobo** [microsoft/vscode#163055]
Does this issue occur when all extensions are disabled?: Irrelevant

- VS Code Version: 1.72.0
- OS Version:  Windows

Initially there was an "alt" command that would switch between disconnect and terminate actions on the debug toolbar. Now this is a dropdown, but the Disconnect option does not present the familiar icon anymore.

![image](https://user-images.githubusercontent.com/6532485/192517264-14ae565a-1d8e-451d-b322-92bd07f65d51.png)

Original report: https://github.com/xdebug/vscode-php-debug/issues/841

Is this intentional, or is the icon missing?

Thank you!

**Comment by roblourens** [comment]
This is intentional - dropdown menus are actually not able to show icons (because on other platforms they are native menus)
