### ISSUE TITLE
Normal File Search in New Setting UX Does not Expand Sections

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16301]
Testing out the new settings UX, normal file searches <kbd>command</kbd><kbd>f</kbd> correctly find the location of strings in the default settings file but do not expand the section the result is found in:

![nov-30-2016 17-18-03](https://cloud.githubusercontent.com/assets/12821956/20778187/fc22f8be-b720-11e6-985d-76c3214cadae.gif)

**Comment by chrmarti** [comment]
Maybe we should give focus to the new search box instead of opening the find widget on Ctrl+F?

**Comment by sandy081** [comment]
@chrmarti Yes, I would be disabling the find widget in this editor.

**Comment by sandy081** [comment]
Disabled Find 6093e46dfe62c7ecff96453d4dba719102226960
