### ISSUE TITLE
Variable substitution in paths falls apart when ${workspaceFolder} is / (root)

### ISSUE THREAD

**Issue by vanklompf** [microsoft/vscode#163076]
Type: <b>Bug</b>

I'm using chroot environment and want my workspace folder to be / (root folder).
But everything falls apart. I.e paths for cmake root or compile_commands becomes garbage.

[10/8/2022, 8:41:00 PM] "components${workspaceFolder}cna${workspaceFolder}host${workspaceFolder}src${workspaceFolder}probed${workspaceFolder}build_vs_code_cmake${workspaceFolder}compile_commands.json" could not be found. 'includePath' from c_cpp_properties.json in folder '' will be used instead.

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.13.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.85GB free)|
|Process Argv|--crash-reporter-id 25665b1f-ef6a-41e0-9875-5d50ba045b00|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: vdi-ld6-lnx-203|
|OS|Linux x64 5.13.0-40-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (24 x 2199)|
|Memory (System)|46.99GB (40.82GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.16.1
remote-containers|ms-|0.255.2
remote-ssh|ms-|0.84.0
remote-wsl|ms-|0.72.0
back-n-forth|nic|3.1.1
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1:30583747
40g7c324:30573242

```

</details>

**Comment by vanklompf** [comment]
Tried to use some kind of workaround like using /folder/.. but VScode apparently flattens paths (which is reasonable)

**Comment by roblourens** [comment]
Please file on the cpp extension
