### ISSUE TITLE
JSX coloring breaks on <Link to={`${APP_ROOT}${bc.link}`}

### ISSUE THREAD

**Issue by mrkam** [Microsoft/vscode#16304]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|react-toolbox-snippets|alechp|0.12.0|
|Bookmarks|alefragnani|0.9.2|
|jsrefactor|cmstead|0.5.3|
|githistory|donjayamanne|0.1.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|auto-close-tag|formulahendry|0.3.4|
|auto-rename-tag|formulahendry|0.0.7|
|redux-snippets|jameshrisho|0.0.1|
|tag-rename|krizzdewizz|0.1.0|
|d3-helpers-snippets|ledragon|0.2.2|
|indenticator|SirTori|0.2.1|
|react-beautify|taichi|0.2.0|
|react-redux-es6-snippets|timothymclane|1.0.4|
|jsx|TwentyChung|0.0.1|
|vscode-react-native|vsmobile|0.2.0|
|JavaScriptSnippets|xabikos|1.2.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1. Type in the following fragment of JSX:
```
                        {brcr.map(bc => [
                            <i className="right chevron icon divider"></i>,
                            bc.active
                                ? <div className="active section">{bc.title}</div>
                                : <Link to={`${APP_ROOT}${bc.link}`} className="section">{bc.title}</Link>
                        ])}
```
2. Code coloring will break on `${APP_ROOT}${bc.link}`. The rest of the file is colored as the content of ``. If you remove ${APP_ROOT}${bc.link}, it will become good again.
![image](https://cloud.githubusercontent.com/assets/2104995/20780055/4c0fd8f4-b72d-11e6-86cf-a9eff2504d4a.png)

**Comment by mjbvz** [comment]
Confirmed in latest insiders builds. Here's a more minimal repo:

```jsx
1 ? 2 : <p to={`${APP_ROOT}`}>{title}</p>
var a = 10
```

<img width="353" alt="screen shot 2016-12-01 at 11 02 28 am" src="https://cloud.githubusercontent.com/assets/12821956/20807945/a9cb32ee-b7b5-11e6-966f-9937734f9530.png">

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#374

**Comment by dbaeumer** [comment]
Verified TS move.
