### ISSUE TITLE
Hyperlinking hyphenated word  for Go To Definition

### ISSUE THREAD

**Issue by TheLazyyCoder** [microsoft/vscode#163064]
If an implementation of Go To Definition for javascript returns a definition (Location | LocationLink) for a hyphenated word then the whole word is not hyperlinked when we CTRL + Hover a hyphenated word.
<br/>
![hyperlink_hyphenated_word](https://user-images.githubusercontent.com/29699907/194720092-3325d782-9061-4865-b165-6bd8c2794e37.gif)

**Comment by mjbvz** [comment]
This should already work, you just need to return the span being hovered (`originSelectionRange`). See the implementation:

https://github.com/microsoft/vscode/blob/a3192fbad7bb02871ae8b6d3703c8bfc5433e661/extensions/typescript-language-features/src/languageFeatures/definitions.ts#L38

**Comment by TheLazyyCoder** [comment]
Hi @mjbvz 
The below code snippet can be used in the Language server implementation of javascript for multiple IDE.

`const response = await this.client.execute('definitionAndBoundSpan', args, token);
 if (response.type !== 'response' || !response.body) {
     return undefined;
 }
const span = response.body.textSpan ? typeConverters.Range.fromTextSpan(response.body.textSpan) : undefined;`

**Comment by TheLazyyCoder** [comment]
@mjbvz  ```originSelectionRange```  doesn't work if we return ```LocationLink[]```.
