### ISSUE TITLE
Settings Sync: consider if "on" notification needs link to log

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#163013]
Wasn't sure why we show this link when turning Settings Sync on. Do we need it for some reason? Seems somewhat low-level/technical. If so, maybe it should be after the string e.g. `Settings Sync is turned on. Show log.`

<img width="498" alt="CleanShot 2022-10-07 at 15 43 07@2x" src="https://user-images.githubusercontent.com/25163139/194672182-c184c572-5776-42db-b1b1-829a18238c9b.png">

**Comment by sandy081** [comment]
Yah, it was added in the beginning for users to discover what is happening. But, I agree that it does not has to be user facing.
