### ISSUE TITLE
The activity bar automatically disappears by Right - click

### ISSUE THREAD

**Issue by rwerplus** [microsoft/vscode#163039]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72
- OS Version: Win11

Steps to Reproduce:

1.Right - click the profile abbreviation in the lower left corner. 
2. The activity bar automatically disappears

**Comment by sbatten** [comment]
@rwerplus do you run with the native title bar enabled? `window.titlebarstyle`?

**Comment by rwerplus** [comment]
> @rwerplus do you run with the native title bar enabled? `window.titlebarstyle`?

I set it to custom. I switched the configuration file and the active bar will disappear after a few right clicks
![right-click](https://user-images.githubusercontent.com/48611415/194900008-180acbfb-a7b1-4519-8b24-eaa05ede58c7.gif)

**Comment by bpasero** [comment]
I am quite sure this is fixed by now.
