### ISSUE TITLE
[c++] noexcept and override don't get correctly highlighted

### ISSUE THREAD

**Issue by jrlanglois** [Microsoft/vscode#16300]
- VSCode Version: 1.7.2
- OS Version: 10.11.6 (El Capitan)

### Example:
![screen shot 2016-11-30 at 19 25 43](https://cloud.githubusercontent.com/assets/1908886/20777111/de05fb30-b732-11e6-8a5f-ac670c9cb604.png)

### Code:
```c++
override
void foo() override
{
}

noexcept
void bar() noexcept
{
}
```
Funnily enough, GitHub's C++ synthax highlighter has the opposite result!

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#180

**Comment by ramya-rao-a** [comment]
Cannot verify as the upstream issue is not fixed. Moving this to next milestone
