### ISSUE TITLE
word moved the direction when arrow key pressed after type Korean letter

### ISSUE THREAD

**Issue by eunchan** [Microsoft/vscode#1630]
I've installed VSCode 0.10.6. 
When I typed Korean letter, the text pane color was changed to black.
Then if I didn't put space before move my cursor, Korean words follows the cursor.
For example, if I typed {A} word then move cursor to next line, {A} is placed in next line not the previous cursor position.

**Comment by kkc0923** [comment]
I can reproduce the same bug.

**Comment by alexandrudima** [comment]
@eunchan @kkc0923 To help me reproduce, can you please walk me through step by step on how you input Korean.
- should my language input settings look like this:
![image](https://cloud.githubusercontent.com/assets/5047891/12580066/d79f476e-c42c-11e5-8d8e-7e5e2c3e9601.png)
- can you please give me a few examples of what sequence of keys I should press on my qwerty keyboard and what characters should appear

I am sorry I need this extra information on your part, but I am not familiar with Korean.

Thank you for your patience!

**Comment by kkc0923** [comment]
@alexandrudima Here is reproduction steps.
1. Create any text file and make some lines by pressing enter keys.
2. Back your cursor to first line.
3. Press g k s r m f (it will be 한글)
4. Press down arrow key.

You will see the 한글 was moved next line with cursor.

**Comment by alexandrudima** [comment]
@kkc0923 Thank you for the detailed steps. After 7c5de8bf2bebf7280ac28d7fff8b83fafac65e0d this seems to work:

![korean-down-arrow](https://cloud.githubusercontent.com/assets/5047891/12664947/114e7b66-c634-11e5-93d7-0a591e078471.gif)
