### ISSUE TITLE
Ignore default formatter when it's no applicable

### ISSUE THREAD

**Issue by flavionm** [microsoft/vscode#163019]
When a custom `editor.defaultFormatter` is set and it can't parse a certain language, it should be ignored in favor of one that can, in case there's only one available.

If there are multiple available, it should still behave as if it's there's no default set, i.e., prompt to choose a default formatter for that language.

**Comment by jrieken** [comment]
>  prompt to choose a default formatter for that language.

We actually do that but not during auto-save or none-user-triggered save because it will appear out of context and prevent saving from happen. However, we do permanently show language status UX that the selected formatter isn't valid.
