### ISSUE TITLE
Make extension update target version visible

### ISSUE THREAD

**Issue by philippgille** [microsoft/vscode#163163]
Hello, I searched for an existing ticket with https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+extension+update+version, but didn't find anything related.

Prior to v1.72.0, the extension sidebar showed which version an extension will be updated to. And when hovering over the extension in the sidebar, or opening the extension in a tab, you could see the currently installed one. That way you could see for example if an update is a major, minor, or patch update, and depending on that dig into the release notes or not.

Further in the past, IIRC, the extension sidebar even showed both, installed and target version, which was even more convenient.

Now with v1.72.0, I don't see anywhere the target version of an extension update. Many extensions don't keep a proper changelog, so that's not a reliable place to check.

Here's an example for vscode-icons, a very popular extension with 12 million installs:
![image](https://user-images.githubusercontent.com/170670/194852810-1cbbdb0c-db05-41a8-af72-39ced1cd8bb8.png)

Only when going to the Marketplace _webpage_ ([here](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons)) we see the target version:
![image](https://user-images.githubusercontent.com/170670/194853087-3301ce6a-3274-43aa-aa69-561097ecf28e.png)

=> Feature request: Please make the target version for extension updates visible inside of VS Code again.

**Comment by sandy081** [comment]
Latest version is now shown in the hover. Update button in the extension editor shows the version.
