### ISSUE TITLE
Search is *very* slow and doesn't return any results

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16316]
Here's a comparison of stable vs today's insider:

[![Search](http://img.youtube.com/vi/Pnff2r1ezIU/0.jpg)](https://www.youtube.com/watch?v=Pnff2r1ezIU "Search")

**Comment by joaomoreno** [comment]
![image](https://cloud.githubusercontent.com/assets/22350/20788365/cadb0bbc-b7b0-11e6-948c-077ef252101f.png)

**Comment by joaomoreno** [comment]
Fixed by 6c32ad23315aa9ad39089ccceda898ca3e303dbf and be33bcdb2beb2d01c76ec8f830a70feaaa6721f5.

Turns out it was just a missing bundle reference in the buildfile.

**Comment by roblourens** [comment]
Thanks Joao!
