### ISSUE TITLE
When typing Korean, a red box suddenly appears.

### ISSUE THREAD

**Issue by vigil2** [microsoft/vscode#163106]
Type: <b>Bug</b>

When typing korean(Hangul), a red box suddenly appears.
It's been erased, so there's no problem, but it keeps popping up.
It seems to occur frequently when typing Hangul and moving with F5 or Command + arrow keys.

VS Code version: Code 1.72.0 (Universal) (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:21:58.256Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 4|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 2071bc74-d4ab-4c22-a9f8-feffb32d0868|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
gitlens|eam|12.2.2
code-runner|for|0.11.8
better-cpp-syntax|jef|1.16.1
theme-monokai-pro-vscode|mon|1.1.21
vscode-language-pack-ko|MS-|1.72.10050956
csharp|ms-|1.25.0
python|ms-|2022.16.0
vscode-pylance|ms-|2022.10.10
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.21.0
ayu|tea|1.0.5
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
material-theme|zhu|3.15.5

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30583747
fc301958:30573243

```

</details>

**Comment by alexdima** [comment]
@vigil2 Enabling macOS voice over via `cmd + G5` ends up rendering a red box around the input. Do you have that enabled? (You can disable it by long pressing `cmd + F5` again)

**Comment by vigil2** [comment]
@alexdima no. I use it with voiceover turned off. voiceover keyboard shortcuts have also been turned off.

**Comment by alexdima** [comment]
@vigil2 Could you please show a screenshot or a screen recording of the red box you're observing?

**Comment by vigil2** [comment]
@alexdima I have attached a screenshot in the link.
[https://vigil2.github.io/vscode/2022/10/23/vscode/](url)

**Comment by alexdima** [comment]
@vigil2 That looks like the IME inserts a Unicode character called a "Group Separator" https://codepoints.net/U+001D?lang=en . Could you please share with me the exact keys you press and in what order which lead to that getting inserted?
