### ISSUE TITLE
Provide a setting option for changing the font size and font family of workbench 

### ISSUE THREAD

**Issue by xishian** [microsoft/vscode#163139]
I can not find a option in settings for changing the font family of workbench, but I try to change directly the style  ``` .monaco-workbench .part>.content{font-size:13px;font-family:Cascadia Mono}``` in ```~/Microsoft VS Code\resources\app\out\vs\workbench\workbench.desktop.main.css ```, and this is effective, no side effects, so why not provide a setting option for changing the font size and font family of workbench? 

Thanks

**Comment by joaomoreno** [comment]
#519
