### ISSUE TITLE
ATA puts types in $HOME/Microsoft

### ISSUE THREAD

**Issue by Instagit** [Microsoft/vscode#16318]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

I have yet to find out how to reproduce this, but VS Code creates a *Microsoft/TypeScript/node_modules/* directory with the *types-registry* npm module in it in the home directory.

The package readme says

>This is the source code for the types-publisher service, which publishes the contents of DefinitelyTyped to npm.

I never set anything to be shared or published. So what exactly is this and what does it do?

**Comment by Instagit** [comment]
Steps to reproduce:

1. open VS Code
2. open any JavaScript file

It only happens for the first JS file that is opened. Could be a bug, too.

**Comment by chrmarti** [comment]
I guess this is from the automatic typings acquisition in recent versions of TypeScript. @Instagit Are you saying the folder is under `~/Microsoft`?

**Comment by vladima** [comment]
@chrmarti is correct - this is location of global cache for acquired type declarations. These files are downloaded on user machine to power JavaScript intelligence and never uploaded anywhere.

**Comment by chrmarti** [comment]
@vladima What are the paths that are used for this cache on the different platforms? I think on Linux it might make sense to used a folder name with a leading '.' to hide it from default `ls` and file explorer behavior - like other tools do. /cc @Tyriar

**Comment by Tyriar** [comment]
Now that you mention this I have this too. We should absolutely *not* be putting the types in `~/Microsoft`. `$XDG_CACHE_HOME/typescript` would probably make the most sense, where `$XDG_CACHE_HOME` defaulting to `$HOME/.cache` if it is not defined as per the [XDG Base Directory Specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html).

@vladima this is actually quite bad imo, is this a purely upstream problem?

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript#12674

**Comment by Tyriar** [comment]
Let's keep this open on vscode to track it. I'd like to mention the fix in release notes when it comes.

**Comment by mjbvz** [comment]
This is going into TypeScript 2.2, so we will not be picking it up in VSCode 1.8. You can install a TS 2.2 insiders build to your workspace to work around this for now.
