### ISSUE TITLE
vscode can not render this markdown file.

### ISSUE THREAD

**Issue by eromoe** [microsoft/vscode#163111]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  latest
- OS Version: mac

Steps to Reproduce:

1.  render below markdown doesn't take effect 
[simpread-评价类模型——层次分析法，一致性检验.txt](https://github.com/microsoft/vscode/files/9741314/simpread-.txt)
3. then cause markdown preview failed on other files .

**Comment by mjbvz** [comment]
Please share minimal example text that doesn't render properly

**Comment by eromoe** [comment]
@mjbvz  The file is on main post, sorry but I don't have time to shrink the file .

**Comment by mjbvz** [comment]
Please provide a minimal example and explain the issue. I'm closing this issue if you aren't able/willing to do that
