### ISSUE TITLE
Is it possible to author plugins in ES6?

### ISSUE THREAD

**Issue by capaj** [Microsoft/vscode#16311]
I have a question-is it possible to author plugins in ES6 easily?
Atom editor has a convention of `"format es6"` similar to `"use strict"` at the top of the file which allows developers to use ES6 instead of coffescript. VScode allows to use plain JS, but it does not work with ES6. I know I can achieve the same with babel-register, but it would sure be nice to have it built in.

What do you think?

**Comment by chrmarti** [comment]
Have you set the target in your folder's `jsconfig.json` to es6?
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "lib": [
            "es6"
        ]
    },
    "exclude": [
        "node_modules"
    ]
}
```
Our insiders build is at nodejs version 6.5.0, you should be able to use all es6 features that has enabled by default.

**Comment by jrieken** [comment]
There is no built-in transpiler. We would advocate the use of TypeScript obviously but since everything runs on recent versions of nodejs you can just use most of ES6 without a transpile step.
