### ISSUE TITLE
"Comma expected" error logged in cpp language-configuration.json

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#163181]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.73.0-insider (user setup)
Commit: 8e1235ee25e3aad3598ab58016c071b5596b826a
Date: 2022-10-10T09:52:32.588Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. View->Toggle Developer Console shows
2. Open a C++ (.cpp) file.

Errors parsing ...AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/extensions/cpp/language-configuration.json: [379, 1] Comma expected
_readConfigFile @ workbench.desktop.main.js:2140

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/163182
