### ISSUE TITLE
Powershell $PSScriptRoot (No simple way to run scripts)

### ISSUE THREAD

**Issue by TheKnightCoder** [Microsoft/vscode#16319]
- VSCode Version: 1.8.0-insider
- OS Version: Windows 7

Steps to Reproduce:

1. install powershell extension
2. make a script using $PSScriptRoot   (directory of script)
3. Highlight code and press F8

$PSSScriptRoot is always C:\Program Files (x86)\Microsoft VS Code Insiders

This messes up all my scripts. and this is the only easy way of running code. The only way I can get the script to run correctly is to open the folder and run debug. 

Love visual code but why is there no way of running code easily

**Comment by chrmarti** [comment]
This issue was moved to PowerShell/vscode-powershell#354
