### ISSUE TITLE
I cant get output to the terminal.

### ISSUE THREAD

**Issue by bnrks** [microsoft/vscode#163153]
Type: <b>Bug</b>

I bought a new pc and i installed vs code. Then i installed all the necessary extentions. But i cant get output to the terminal. On my old pc, i never had a problem like this. 

https://prnt.sc/FXhIKnOBoiCF

VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.22000
Modes: Restricted
Sandboxed: No

<details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.9.0
vscode-language-pack-tr|MS-|1.72.10050956
material-icon-theme|PKi|4.21.0

(5 theme extensions excluded)

</details>

**Comment by mukulchugh** [comment]
Maybe try these steps:

 in the Options dialog box, on the Projects and Solutions > General page, select Show Output window when the build starts

**Comment by bnrks** [comment]
@mukulchugh Can you explain what you're talking about with pictures? I cant find it options. Unless you mean the settings of course.

**Comment by meganrogge** [comment]
What steps are you taking to "Get output to the terminal"?

**Comment by meganrogge** [comment]
you're using windows pwsh, which is usually a poor experience - installing pwsh could help. 

if you run the program like that in an external terminal is there output? if so, could you run `toggle escape sequence logging` and share the output?

**Comment by bnrks** [comment]
I'm really having trouble understanding what you're saying. My english is not so good. I'm looking for the things you mentioned but I can't find it. i run the program with pressing F5 or i choose run>start debugging.  btw i dont get an error like this on vs 22

**Comment by bnrks** [comment]
https://prnt.sc/yiTSJ97oUKj5 https://prnt.sc/W60Ysd8xL8jp
I hope these are the things you want @meganrogge
