### ISSUE TITLE
Please make the debug button bigger

### ISSUE THREAD

**Issue by pouyakary** [microsoft/vscode#163193]
The debug button is really small. Can it be big? The drop down menu as well as the other debug buttons could be on a toolbar under the debug title and this could be much bigger and easier. 

![](https://user-images.githubusercontent.com/2157285/194909958-ddbd39a6-c730-4f85-b4e0-b2d624e1de34.png)

Or the play button could be bigger button like the 'commit' button:

<img width="422" alt="Screen Shot 2022-10-10 at 8 00 21 PM" src="https://user-images.githubusercontent.com/2157285/194913105-16014005-edc2-43c3-a1fa-007b7b2393d0.png">

**Comment by roblourens** [comment]
The clickable area of that button is 16x20. Most menu buttons are 22x22. I haven't had an issue with this but could it be a ux or accessibility issue? @isidorn @daviddossett 

Here's what it would look like if it were 22px wide

<img width="312" alt="image" src="https://user-images.githubusercontent.com/323878/194926070-adbac141-decb-4f6c-90e1-2de4366e485f.png">

The big button is an interesting idea but I'm not a big fan of that button. I find it really aggressive and loud and I disable it in scm.

**Comment by isidorn** [comment]
Making it 22px makes sense. I think it should be consistent with the other button sizes across the workbench.

**Comment by pouyakary** [comment]
@roblourens thanks a lot :) it has been the fastest fix on history :))

**Comment by roblourens** [comment]
Did slightly less than the full 22px - due to the border and the background color, I think that feels too wide. But this should help.
