### ISSUE TITLE
getting killed 9 on launch

### ISSUE THREAD

**Issue by kocoman2** [microsoft/vscode#163175]
using ventura beta with oclp 0.5 alpha

getting killed 9 on launch

can't disable sip because need for hd4000 patch for sip 803 and amfi-get-out-of-my-way=1
was working on montery with sip 802 only

**Comment by kocoman2** [comment]
ok use - Adding ipc_control_port_options=0 to boot-args

**Comment by gagermaniac** [comment]
> ok use - Adding ipc_control_port_options=0 to boot-args

Thanks it work

**Comment by deepak1556** [comment]
Closing as issue seems resolved.

**Comment by Hesham-Salama** [comment]
It's not resolved. It's basically another workaround around the real issue. Also it might not work for some people.

Disabling SIP shouldn't be a reason for VSCode to decline launching/crashing.
