### ISSUE TITLE
openNativeConsole at current location

### ISSUE THREAD

**Issue by Pithikos** [microsoft/vscode#163162]
Similar to https://github.com/microsoft/vscode/issues/134926 it would be great if there's a way to open the terminal at current file. And since that is locked, it's impossible to follow up (not able to make any sense of a workaround).

For someone transitioning from Atom this is just a huge headache and not seamless at all. Working with Linux and Gnome.

**Comment by meganrogge** [comment]
> would be great if there's a way to open the terminal at current file.

Can you pls clarify what you mean by this?

**Comment by Pithikos** [comment]
> > would be great if there's a way to open the terminal at current file.
> 
> Can you pls clarify what you mean by this?

Say I am editing file `myproject/subdir/myfile.txt`. I want to press `CTRL + SHIFT + C` and get a terminal directly at `~/myproject/subdir` to do other stuff outside VSC.

Every other major IDE I've worked with, had this as default behaviour or there was a plugin to do that. Can't seem to find anything for VSC which is strange since it's supposed to be the direct replacement of Atom (where this actually works).

**Comment by ArturoDent** [comment]
See https://stackoverflow.com/a/56222855/836330

This keybinding will do it for example:

```jsonc
{
    "key": "ctrl+alt+d",       // whatever keybinding you want
    "command": "workbench.action.terminal.sendSequence",
    "args": {"text": "cd \"${fileDirname}\"\u000D"}
}
```

**Comment by Pithikos** [comment]
> See more at https://stackoverflow.com/a/56222855/836330
> 
> This keybinding will change the current terminal:
> 
> ```js
> {
>     "key": "ctrl+alt+d",       // whatever keybinding you want
>     "command": "workbench.action.terminal.sendSequence",
>     "args": {"text": "cd \"${fileDirname}\"\u000D"}
> }
> ```
> 
> This keybinding will open a new terminal as you want:
> 
> ```js
> {
>   "key": "ctrl+shift+C",
>   "command": "workbench.action.terminal.newWithCwd",
>   "args": {
>       "cwd": "${fileDirname}"
>   }
> }
> ```

Thanks, the second seems closer to what I mean. Still the issue is that it opens the integrated terminal instead of an **external** one.

So I was looking something more like this:
```
    {
        "key": "ctrl+shift+C",
        "command": "workbench.action.terminal.openNativeConsole",
        "args": {
            "cwd": "${fileDirname}"
        }
    }
```

**Comment by Pithikos** [comment]
OK, current workaround is to make it like in Quake:
```
    {
        "key": "ctrl+`",
        "command": "workbench.action.terminal.newWithCwd",
        "when": "editorTextFocus",
        "args": {
            "cwd": "${fileDirname}"
        }
    },
```

**Comment by ArturoDent** [comment]
Yes, it doesn't look like the `workbench.action.terminal.openNativeConsole` command works with the `cwd` argument.
