### ISSUE TITLE
Enable Emmet support for js, html and css in .liquid files.

### ISSUE THREAD

**Issue by jack-fdrv** [microsoft/vscode#163118]
I would like to use Emmet Autocomplete for JS, CSS and HTML in .liquid files.
We cant make it like this:
```
"emmet.includeLanguages": {
        "liquid": "html, css, js"
},
```
or
```
"emmet.includeLanguages": {
        "liquid": "[html, css, js]"
},
```
So how?

**Comment by rzhao271** [comment]
Duplicate of https://github.com/microsoft/vscode/issues/62910
