### ISSUE TITLE
[decorators] before/after decorators for empty lines

### ISSUE THREAD

**Issue by KnisterPeter** [Microsoft/vscode#16313]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04.1 LTS

I would like to display github review comments as text-decorations in visible editors. Unfortunately the decorations are not shown for empty lines. Is there a reason to not display them in this case?
IMHO the before and after elements of the decorations should be visible.

**Comment by siegebell** [comment]
related: #8003

**Comment by aeschli** [comment]
By design the before/after annotation have to be before or after something. The empty range is not really valid.

**Comment by eamodio** [comment]
I would just like bump this, as I am working on a new release of GitLens and would *love* to be able to have decorations on blank lines.

See below:
![image](https://cloud.githubusercontent.com/assets/641685/26811879/702e8386-4a42-11e7-9455-c1455e941bde.png)

The missing lines do belong to a commit and it would be great to not break the visuals either :)

**Comment by eamodio** [comment]
This is resolved as of https://github.com/Microsoft/vscode/issues/30133

**Comment by aeschli** [comment]
@alexandrudima You mentioned that your work on this

**Comment by alexandrudima** [comment]
Yes, this should already work.
