### ISSUE TITLE
No intelligence

### ISSUE THREAD

**Issue by HopeForToday** [Microsoft/vscode#16310]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Go|lukehoban|0.6.51|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1.vsCode cannot list the member or func of fmt, when I typed “fmt.”
2.But in other people's vsCode, it will list...I don't know what to do

**Comment by chrmarti** [comment]
I guess that is with Go? Have you set the GOPATH environment variable?

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#676
