### ISSUE TITLE
Auto collapse folders without open files in the editor

### ISSUE THREAD

**Issue by andresbm05** [microsoft/vscode#163103]
When navigating through a large project sometimes you end up with a lot of folders open in the tree view which is very annoying.
I would like to have a configuration to only keep open the folder of the file I'm working on while keeping the rest collapsed.

For example, if I'm working on a component of an Angular project but I need to check the inputs of another component, I navigate to its ts file and the whole folder tree to that component is open. Then I check the type of one of it's inputs and it is inside a dependency so I have open the node_modules folder. By the time I go back to the component I'm working at, I have a huge scroll in the folder view.

My suggestion would be to create a configuration if possible with 3 options. This configuration could be something like "auto collapse folders" and the options would be:
* Disabled: keeps the current behaviour
* open editors: keeps open the folder of all the open editors
* active editor: keeps open only the folder of the active editor (the one you're currently working on)

**Comment by lramos15** [comment]
The new `explorer.autoRevealExclude` setting coming to 1.74 should help many of these cases
