### ISSUE TITLE
Set an explicit environment variable when resolving shell environment.

### ISSUE THREAD

**Issue by Sean1708** [microsoft/vscode#163186]
For various reasons I do stuff in my `.bashrc` that breaks VS Code's shell environment resolution, which I'd rather not have to get rid of. As a workaround I'm only running that stuff if I don't detect either `ELECTRON_RUN_AS_NODE` or `ELECTRON_NO_ATTACH_CONSOLE`, which are [both explicitly set for this resolution](https://github.com/microsoft/vscode/blob/7104e8fcf43136054261575c8ec311e0238a8fbb/src/vs/platform/shell/node/shellEnv.ts#L111), but this is very brittle and I'm very uncomfortable relying on it.

It would be great an environment variable like `VSCODE_RESOLVING_ENVIRONMENT` could be set for this process that users could explicitly rely on, this would also help users that run slow processes on shell startup (at least the ones that don't affect the environment, which is probably a niche case TBH).

It should be a fairly simple change, just an extra line [here](https://github.com/microsoft/vscode/blob/7104e8fcf43136054261575c8ec311e0238a8fbb/src/vs/platform/shell/node/shellEnv.ts#L111) to set the variable and an extra line [here](https://github.com/microsoft/vscode/blob/7104e8fcf43136054261575c8ec311e0238a8fbb/src/vs/platform/shell/node/shellEnv.ts#L200) to unconditionally delete. It would also need to be documented somewhere as well, but I'm not quite sure where.

I'm happy to do the work, but I wanted to check first that this is actually a sensible change before submitting a pull request.

**Comment by joaomoreno** [comment]
This is a very sensible request! [PR welcome](https://github.com/microsoft/vscode/blob/73221ee0464eacf8af8cbd555597f67b076696f4/src/vs/platform/shell/node/shellEnv.ts#L111-L115)!

**Comment by joaomoreno** [comment]
**Verification:** please code review.
