### ISSUE TITLE
Splitting terminal using "terminal.integrated.splitCwd": "workspaceRoot" always selects first option

### ISSUE THREAD

**Issue by mradcliffe** [microsoft/vscode#163172]
Does this issue occur when all extensions are disabled?: Yes (via Start Extension Bisect)

- VS Code Version: 1.72.0, 1.73.0-insider (Universal)
- OS Version: Darwin x64 21.6.0

Steps to Reproduce:

1. Open Visual Studio Code
2. Confirm that Settings > Terminal > Integrated: Split Cwd is set to "workspaceRoot".
3. Open a Workspace file.
4. Open an Integrated Terminal from Terminal > New Terminal
5. One of two methods:
   1. Click the "+" drop-down menu > Split Terminal > bash/zsh context menu option. This is my normal work flow because the the split button option below has been broken since the tab behavior was introduced.
   1. Press the split button.

**Previous Behavior**: When using 5.1, a drop-down menu is displayed at the top of Visual Studio Code until a selection is made.

**Regression Behavior**: When using either 5.1 or 5.2, a drop-down menu is briefly (<1 second) displayed and the first selection is always used without any user input and it is not possible to select a root folder using those methods.

**Workaround**: Use the command palette "Terminal: Split Terminal" command, which still offers the user a choice.

I did not capture a screen recording using Code 1.73.0-insiders, but I did test all 3 pathways to splitting a terminal using Code 1.73.0-insiders. This follows the steps to reproduce exactly as the only setting that I changed was Terminal > Integrated: Split Cwd.

I could have sworn I commented on either a pull request or an issue related to split terminal, but I can no longer find that issue in the issue queue (tried searching my username). But this is now a new regression that was not there in 1.71.x.

This is probably related to, but not a duplicate of, #117079.

#### Settings

![Screenshot of Terminal > Integrated: Split Cwd workspaceRoot option](https://user-images.githubusercontent.com/328497/194872265-95af7590-306b-4696-aa0b-fd0ffdfde8b5.png)

#### Video 1 (Using the split button) - Failure

Caption: I open an integrated terminal, it defaults to "test1". Then I try to use the "split" button. The drop-down briefly appears for less than one second, and a new integrated terminal opens in "test1".

https://user-images.githubusercontent.com/328497/194869223-a94abad6-c4d8-4a30-82d7-fd56f8f565e8.mov

#### Video 2 (Using the split context menu option) - Failure

Caption: I open an integrated terminal, it defaults to "test1". Then I try to use the drop-down menu from the "plus" button to select Split Terminal > zsh. The drop-down briefly appears for less than one second, and a new integrated terminal opens in "test1".

https://user-images.githubusercontent.com/328497/194869574-bb75b2a1-af5e-4888-a1cd-b9871cdfb771.mov

#### Video 3 (Using the "Terminal: Split Terminal" command) - Success

Caption I open an integrated terminal, it defaults to "test1". Then I bring up the Command Palette using the keystroke, type to reach the the Terminal: Split Terminal command, select the command, the folder choice drop-down menu appears, I select "test2", and a new integrated terminal opens in "test2".

https://user-images.githubusercontent.com/328497/194869242-80625ecf-e9e6-4b7e-be61-0cbe6de72fab.mov

**Comment by babakks** [comment]
@meganrogge Just submitted a PR. Could you please review it anytime?

**Comment by Tyriar** [comment]
@mradcliffe @babakks did the fix, we just reviewed it 🙂

**Comment by mradcliffe** [comment]
Thank you. I'm so sorry to forget an attribution. Thank you, babakks, Tyriar and meganrogge. 🙌
