### ISSUE TITLE
VS Code slow to start up and create new windows

### ISSUE THREAD

**Issue by robb** [microsoft/vscode#163291]
Hi VS Code team,

a PM of yours [suggested](https://twitter.com/isidorn/status/1579810927792123904) I file this issue after running into some slowness launching VS Code or creating new windows. (Creating a new window with ⇧⌘N can easily take 8 seconds until it accepts keyboard input)

LMK if the below data is sufficient.

## System Info

* Code: 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e)
* OS: darwin(21.6.0)
* CPUs: Apple M1(8 x 24)
* Memory(System): 16.00 GB(0.09GB free)
* Memory(Process): NaN MB working set(268.03MB private, 0.34MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                          |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------------------------- |
| start => app.isReady                                            | 491      | [main]                    | initial startup: true                                         |
| nls:start => nls:end                                            | 0        | [main]                    | initial startup: true                                         |
| require(main.bundle.js)                                         | 2228     | [main]                    | initial startup: true                                         |
| start crash reporter                                            | 0        | [main]                    | initial startup: true                                         |
| serve main IPC handle                                           | 9        | [main]                    | initial startup: true                                         |
| create window                                                   | 2952     | [main]                    | initial startup: true, state: 19ms, widget: 2912ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 5912     | [main]                    | initial startup: true                                         |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 8047     | [main->renderer]          | NewWindow                                                     |
| require(workbench.desktop.main.js)                              | 4603     | [renderer]                | cached data: NO, node_modules took 0ms                        |
| wait for window config                                          | 10       | [renderer]                | -                                                             |
| init storage (global & workspace)                               | 1458     | [renderer]                | -                                                             |
| init workspace service                                          | 1327     | [renderer]                | -                                                             |
| register extensions & spawn extension host                      | 2589     | [renderer]                | -                                                             |
| restore viewlet                                                 | 0        | [renderer]                | -                                                             |
| restore panel                                                   | 0        | [renderer]                | -                                                             |
| restore & resolve visible editors                               | 3894     | [renderer]                | 1: workbench.editors.untitledEditorInput                      |
| overall workbench load                                          | 9870     | [renderer]                | -                                                             |
| workbench ready                                                 | 30497    | [main->renderer]          | -                                                             |
| renderer ready                                                  | 16171    | [renderer]                | -                                                             |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                             |
| extensions registered                                           | 33612    | [renderer]                | -                                                             |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1665492946890	0	0
code/didStartMain	1665492947498	608	608
code/willStartCrashReporter	1665492947586	88	696
code/didStartCrashReporter	1665492947586	0	696
code/mainAppReady	1665492947989	403	1099
code/willLoadMainBundle	1665492947993	4	1103
code/fork/willLoadCode	1665492948063	70	1173
code/registerFilesystem/file	1665492949210	1147	2320
code/didLoadMainBundle	1665492950221	1011	3331
code/willStartMainServer	1665492950412	191	3522
code/didStartMainServer	1665492950421	9	3531
code/willCreateCodeWindow	1665492950943	522	4053
code/willRestoreCodeWindowState	1665492950945	2	4055
code/didRestoreCodeWindowState	1665492950964	19	4074
code/willCreateCodeBrowserWindow	1665492950968	4	4078
code/didCreateCodeBrowserWindow	1665492953880	2912	6990
code/didCreateCodeWindow	1665492953895	15	7005
code/willOpenNewWindow	1665492953901	6	7011
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1665492953904	0	0
code/didStartRenderer	1665492961824	7920	7920
code/willWaitForWindowConfig	1665492961837	13	7933
code/didWaitForWindowConfig	1665492961847	10	7943
code/willShowPartsSplash	1665492961848	1	7944
code/didShowPartsSplash	1665492961914	66	8010
code/willLoadWorkbenchMain	1665492961948	34	8044
code/didLoadWorkbenchMain	1665492966551	4603	12647
code/registerFilesystem/file	1665492966584	33	12680
code/registerFilesystem/vscode-userdata	1665492966602	18	12698
code/willInitWorkspaceService	1665492966619	17	12715
code/willInitStorage	1665492966621	2	12717
code/willInitUserConfiguration	1665492966732	111	12828
code/didInitUserConfiguration	1665492967467	735	13563
code/willInitWorkspaceConfiguration	1665492967467	0	13563
code/didInitWorkspaceConfiguration	1665492967946	479	14042
code/didInitWorkspaceService	1665492967946	0	14042
code/didInitStorage	1665492968079	133	14175
code/willStartWorkbench	1665492968125	46	14221
code/LifecyclePhase/Ready	1665492968140	15	14236
code/willCreateWorkbenchContributions/1	1665492968931	791	15027
code/didCreateWorkbenchContributions/1	1665492969206	275	15302
code/willCreateWorkbenchContributions/2	1665492969206	0	15302
code/registerFilesystem/trustedDomains	1665492969211	5	15307
code/registerFilesystem/vscode-local-history	1665492969215	4	15311
code/didCreateWorkbenchContributions/2	1665492969247	32	15343
code/registerFilesystem/vscode-debug-memory	1665492970274	1027	16370
code/willRestoreEditors	1665492974099	3825	20195
code/willConnectSharedProcess	1665492976521	2422	22617
code/didRestoreEditors	1665492977993	1472	24089
code/LifecyclePhase/Restored	1665492977995	2	24091
code/didStartWorkbench	1665492977995	0	24091
code/didRemovePartsSplash	1665492977995	0	24091
code/willCreateWorkbenchContributions/3	1665492977995	0	24091
code/willResumeEditSessionFromIdentifier	1665492978026	31	24122
code/didResumeEditSessionFromIdentifier	1665492978026	0	24122
code/registerFilesystem/vscode-edit-sessions	1665492978039	13	24135
code/didCreateWorkbenchContributions/3	1665492978120	81	24216
code/willLoadExtensions	1665492978521	401	24617
code/willHandleExtensionPoints	1665492980449	1928	26545
code/willHandleExtensionPoint/configurationDefaults	1665492980449	0	26545
code/didHandleExtensionPoint/configurationDefaults	1665492980472	23	26568
code/willHandleExtensionPoint/configuration	1665492980472	0	26568
code/didHandleExtensionPoint/configuration	1665492980611	139	26707
code/willHandleExtensionPoint/jsonValidation	1665492980614	3	26710
code/didHandleExtensionPoint/jsonValidation	1665492980642	28	26738
code/willHandleExtensionPoint/debuggers	1665492980642	0	26738
code/didHandleExtensionPoint/debuggers	1665492980672	30	26768
code/willHandleExtensionPoint/breakpoints	1665492980672	0	26768
code/didHandleExtensionPoint/breakpoints	1665492980673	1	26769
code/willHandleExtensionPoint/notebookRenderer	1665492980673	0	26769
code/didHandleExtensionPoint/notebookRenderer	1665492980686	13	26782
code/willHandleExtensionPoint/problemPatterns	1665492980686	0	26782
code/didHandleExtensionPoint/problemPatterns	1665492980689	3	26785
code/willHandleExtensionPoint/problemMatchers	1665492980689	0	26785
code/didHandleExtensionPoint/problemMatchers	1665492980727	38	26823
code/willHandleExtensionPoint/taskDefinitions	1665492980727	0	26823
code/didHandleExtensionPoint/taskDefinitions	1665492980729	2	26825
code/willHandleExtensionPoint/terminal	1665492980729	0	26825
code/didHandleExtensionPoint/terminal	1665492980729	0	26825
code/willHandleExtensionPoint/walkthroughs	1665492980729	0	26825
code/didHandleExtensionPoint/walkthroughs	1665492980729	0	26825
code/willHandleExtensionPoint/commands	1665492980729	0	26825
code/didHandleExtensionPoint/commands	1665492980748	19	26844
code/willHandleExtensionPoint/menus	1665492980748	0	26844
code/didHandleExtensionPoint/menus	1665492980755	7	26851
code/willHandleExtensionPoint/viewsWelcome	1665492980755	0	26851
code/didHandleExtensionPoint/viewsWelcome	1665492980756	1	26852
code/willHandleExtensionPoint/languages	1665492980756	0	26852
code/didHandleExtensionPoint/languages	1665492980809	53	26905
code/willHandleExtensionPoint/codeActions	1665492980809	0	26905
code/didHandleExtensionPoint/codeActions	1665492980809	0	26905
code/willHandleExtensionPoint/customEditors	1665492980809	0	26905
code/didHandleExtensionPoint/customEditors	1665492980810	1	26906
code/willHandleExtensionPoint/viewsContainers	1665492980810	0	26906
code/didHandleExtensionPoint/viewsContainers	1665492980822	12	26918
code/willHandleExtensionPoint/views	1665492980822	0	26918
code/didHandleExtensionPoint/views	1665492980836	14	26932
code/willHandleExtensionPoint/grammars	1665492980836	0	26932
code/didHandleExtensionPoint/grammars	1665492980880	44	26976
code/willHandleExtensionPoint/semanticTokenScopes	1665492980880	0	26976
code/didHandleExtensionPoint/semanticTokenScopes	1665492980880	0	26976
code/willHandleExtensionPoint/snippets	1665492980880	0	26976
code/didHandleExtensionPoint/snippets	1665492980881	1	26977
code/willHandleExtensionPoint/keybindings	1665492980881	0	26977
code/didHandleExtensionPoint/keybindings	1665492981095	214	27191
code/willHandleExtensionPoint/themes	1665492981095	0	27191
code/didHandleExtensionPoint/themes	1665492981099	4	27195
code/willHandleExtensionPoint/iconThemes	1665492981099	0	27195
code/didHandleExtensionPoint/iconThemes	1665492981099	0	27195
code/didHandleExtensionPoints	1665492981099	0	27195
code/didLoadExtensions	1665492981110	11	27206
```
[prof-H9WewXQa.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9755984/prof-H9WewXQa.main.cpuprofile.txt)
[prof-H9WewXQa.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9755986/prof-H9WewXQa.renderer.cpuprofile.txt)

**Comment by deepak1556** [comment]
Can you provide the startup from latest stable `1.74` if the issue still persists ?

**Comment by robb** [comment]
I've since switched computer and upgraded macOS, sorry. Feel free to close this out. Thanks for investing tho!
