### ISSUE TITLE
Send all breakpoint requests in parallel

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#163248]
Currently we send all the different types of breakpoint requests one at a time

https://github.com/microsoft/vscode/blob/ae34e8d2df286f8c8882d22db417e6dc4cdb01f5/src/vs/workbench/contrib/debug/browser/debugService.ts#L1041-L1046

This is a lot of back and forth between the client and debug adapter, and can take some time. I want to send all of these requests in parallel. In principle, nothing in the spec prevents this. But the comment above the last line is apparently from a time before the `configurationDone` event, when some DAs were using the setExceptionBreakpoints request to know when this initialization stage was done. That comment is from years ago https://github.com/microsoft/vscode/commit/3f0381cd6c9f8e85e5634317d7ba757a8c80fafd#diff-8fcf91137d71e8866175ec9c092132c5a23e4260523c72d57c0c85c5d9c2eaaeR785 and I think it should be fine today. But still I'd like to ping a handful of folks who work on DAs just to check that nobody has an issue with this.

cc @connor4312 @weinand @gregg-miskelly @DanTup @polinasok @zobo @karthiknadig

**Comment by karthiknadig** [comment]
For `debugpy` we use the following sequence for initialization https://github.com/microsoft/debugpy/wiki/DAP-Client-reference#dap-implementation-details . I think parallel set breakpoint request should work.  /cc @int19h @fabioz

**Comment by connor4312** [comment]
js-debug properly uses `configurationDone` as well

**Comment by zobo** [comment]
In vscode-php-debug I rely on `configurationDoneRequest`. I would guess all clients support that today. There is however the `supportsConfigurationDoneRequest` Capability, that you could use?

Internally I have a "BreakpointManager" and a "BreakpointAdapter" for any active PHP process (thread) living in this one Debug Session. The first gathers all breakpoint state from the IDE and each of the BAs then sync this state changes to its PHP process when that is possible.

Parallel should work, let me know if I can test it in an Insiders build.

**Comment by weinand** [comment]
If a DA sets `supportsConfigurationDoneRequest` to `true`, then a client can assume that the DA does not rely on `setExceptionBreakpoints` to know when the "configuration is done".
 
I suggest to send breakpoint requests in parallel iff `supportsConfigurationDoneRequest` is true.

**Comment by DanTup** [comment]
I've checked Dart's debug adapters and they're both setting `supportsConfigurationDoneRequest: true` and are both waiting for `configurationDone` before they begin. If the proposed change is to include the last 4 calls in the code above inside the `Promise.all` that's sending the breakpoints, that sounds fine to me.

If you can ping here if/when the change lands in insiders, it'd be good to do some brief testing though :-)

**Comment by roblourens** [comment]
This is merged in
