### ISSUE TITLE
Extensions intermittently stop working

### ISSUE THREAD

**Issue by martin-wiseweb** [Microsoft/vscode#16328]
- VSCode Version: 1.7.2
- OS Version: Windows 10

### Steps to Reproduce:

- I don't know, exactly...

My VS Code intermittently doesn't allow me to use my extensions. I have no way of knowing which extension it is (I have very many installed) and there aren't any errors produced.

This is **enfuriating**.

**Comment by chrmarti** [comment]
Could you list your extensions? `code --list-extensions` will show them. Also, Help > Report Issues will prefill a GitHub issue with the list.

**Comment by martin-wiseweb** [comment]
Thanks for the tip! My extensions are:

```
abusaidm.html-snippets
akamud.vscode-javascript-snippet-pack
alefragnani.project-manager
annsk.alignment
bcmarinacci.theme-material
casualjim.theme-desertex
codezombiech.gitignore
dbaeumer.jshint
dbaeumer.vscode-eslint
donjayamanne.githistory
donjayamanne.python
felixfbecker.php-debug
felixfbecker.php-intellisense
gerane.Theme-Carbonight
gerane.Theme-FlatDark
gerane.Theme-Laravel
HookyQR.beautify
imperez.smarty
joelday.docthis
lafe.contextualduplicate
linyang95.php-symbols
minhthai.vscode-todo-parser
mrmlnc.vscode-apache
ms-vscode.csharp
onecentlin.laravel-blade
PaulOlteanu.theme-railscasts
petemill.theme-readable-material-darker
PeterJausovec.vscode-docker
PKief.material-icon-theme
Poorchop.theme-darktooth
rafa-acioly.laravel-helpers
robertohuertasm.vscode-icons
ronnidc.nunjucks
Rubymaniac.vscode-paste-and-indent
stevencl.addDocComments
tomoki1207.pdf
wmaurer.change-case
zhuangtongfa.Material-theme
Zignd.html-css-class-completion
```

**Comment by chrmarti** [comment]
Does the console in the devtools (Help > Toggle Developer Tools) show any errors?

**Comment by martin-wiseweb** [comment]
I don't have errors, but I do have some keybinding warnings:

![image](https://cloud.githubusercontent.com/assets/3329959/20810692/b5d2a0d6-b7d8-11e6-944a-c1c0bd3b838f.png)

**Comment by mrmlnc** [comment]
Have you tried to disable `Zignd.html-css-class-completion` extension?

**Comment by martin-wiseweb** [comment]
@mrmlnc That worked. Can I know how you knew to disable that extension?

**Comment by mrmlnc** [comment]
Magic 🐼  

Unfortunately, it's a "bad" extension. More details here: https://github.com/Zignd/HTML-CSS-Class-Completion/issues/33.

And, unfortunately, I can't find time to fix it.

**Comment by mrmlnc** [comment]
/сс @chrmarti to close this issue 😃
