### ISSUE TITLE
Unverified Breakpoints in Vendor files in Laravel PHP instance

### ISSUE THREAD

**Issue by HeadStudios** [microsoft/vscode#163246]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Get Laravel app setup
2. Get some vendor folders with composer require
3. Put a breakpoint in there
4. It becomes Unverified when hit!

So I was asking about this on Reddit but found this forum - basically my xDebug with VSCode works beautifully except when I want to hit a breakpoint in my vendor folder - then it breaks down and says it's an unverified breakpoint... so... just curious if I can make any changes to my launch.json or tweak around with any settings... any input much appreciated!

My launch.json file for reference below:
https://gist.github.com/HeadStudios/e21c9b97c379c226672c603e2371b3f9

**Comment by roblourens** [comment]
Please file an issue on the repo for the debug extension

**Comment by HeadStudios** [comment]
Oh ok sorry.. I have to find it i guess - I'll have a look chrs
