### ISSUE TITLE
[Suggestion] It would be better to add an "Add Configuration..." button in the launch.json file for the Visual Studio Code - Insiders

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode#163266]
**OS:** Win10
**Visual Studio Code Version:** 1.73.0-insider (user setup)

**Repro Steps:**
1. Create a .NET core project with the command "`dotnet new mvc`".
2. Open the project in the Visual Studio Code - Insiders.
3. Open the `launch.json` file.
4. Check whether there is an "Add Configuration..." button in the `launch.json` file.

**Actual:**
There is no "Add Configuration..." button in the `launch.json` file.

**Suggestion:**
It would be better to add an "Add Configuration..." button in the `launch.json` file.

**More Info:**
This issue doesn't reproduce when open the `launch.json` file in the Visual Studio Code.
![image](https://user-images.githubusercontent.com/57662131/195052028-f8657fcc-a301-4165-bdae-40884e5b44b1.png)

**Comment by roblourens** [comment]
Works fine for me. Are you opening exactly the same folder in both instances?

Do you see any errors in the devtools console? (Help > Toggle Developer Tools)

**Comment by v-xinda** [comment]
@roblourens  This issue still reproduces on my Windows machine, but it doesn't reproduce on Mac.
There is no error in the devtools console as below.
![image](https://user-images.githubusercontent.com/57662131/195326148-021b4938-6ef9-40b5-b4b5-2dafb45802c7.png)
