### ISSUE TITLE
Limit terminal instances

### ISSUE THREAD

**Issue by Pithikos** [microsoft/vscode#163282]
It would be great to somehow be able and limit the terminal instances being opened inside VSCode. After one day of usage, I noticed there were 10s of terminals stacked there, slowing down the IDE. The old instances above the limit should be closed automatically.

This is useful for someone coming from a Linux background where multiple terminals are opened and closed (or forgotten in this case) continuously.

**Comment by meganrogge** [comment]
Thanks for the issue, but we don't want to kill terminals or their processes on behalf of the user.

**Comment by Tyriar** [comment]
I solve this with a custom keybinding on the kill terminal command.
