### ISSUE TITLE
vscode for web nls language parse error

### ISSUE THREAD

**Issue by godkite** [microsoft/vscode#163253]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

- Case1:

1. switch chrome language of zh-CN
2. install webworker extensions with zh-CN nls
3. then error happened
<img width="806" alt="image" src="https://user-images.githubusercontent.com/13809539/195013951-c78fb4b1-414d-43d8-a6ae-be357c9a1beb.png">

`packageNLSUris` cached key like: `en zh-en`, but `navigator.language` is `zh-CN` , need `toLowerCase()`
source code at [vscode repo](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/services/extensionManagement/browser/webExtensionsScannerService.ts#L680)

**Comment by godkite** [comment]
@hediet  how about it?

**Comment by TylerLeonhardt** [comment]
@godkite can you please open a new issue for case 2? We prefer 1 issue per problem.

For case 1, yes it seems like we need to be toLowerCaseing that before we read from the bundle cache. Nice catch!

**Comment by godkite** [comment]
> can you please open a new issue for case 2
#164097

**Comment by TylerLeonhardt** [comment]
@godkite this should be working again in insiders.vscode.dev... can you give it a try and let me know how it goes?

**Comment by godkite** [comment]
> @godkite this should be working again in insiders.vscode.dev... can you give it a try and let me know how it goes?

Sorry, I just saw it. It works
