### ISSUE TITLE
Add code page 865 to the list of encodings

### ISSUE THREAD

**Issue by Crunch77** [Microsoft/vscode#16322]
Feature: Add support for code page 865

**Comment by bpasero** [comment]
@Crunch77 even though we do not show it, you can configure it like that:

`"files.encoding": "cp865"`

The full list of supported encodings is here: https://github.com/ashtuchkin/iconv-lite/wiki/Supported-Encodings

**Comment by Crunch77** [comment]
Thank you very much.
It doesn't recognize it, when I change the user.setting to cp865, but it certainly works.

**Comment by bpasero** [comment]
Added to the end of encodings:

![image](https://user-images.githubusercontent.com/900690/30265147-8d695b2a-96db-11e7-9de4-a7f6327f210a.png)

**Comment by bpasero** [comment]
**Verification**: verify you can pick the encoding and save files with that encoding.

**Comment by Crunch77** [comment]
It works
