### ISSUE TITLE
Test: View scalability

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16326]
Test for #15155:

- [x] Windows - @seanmcbreen
- [x] OS X -  @cdias
- [x] Linux - @bgashler1 

Complexity: 4

In order to support scenarios where extensions contribute viewlets to the activity bar, some work was done to enable scalability in the activity bar.

**Setup:**
* get https://github.com/Microsoft/vscode-extension-samples/tree/master/tree-explorer-sample
* npm install
* run it from VS Code as extension

**Verify**
* you can show the contributed viewlet by 
   * using the new `View > Additional Viewlets` entry
   * right clicking on empty space in activity bar and selecting it
   * by using the new view picker (quick open -> type "`view `" with a trailing space)
* if you make the window small enough, viewlets that do not fit the space move into a new "..." overflow menu
   * entries in the overflow menu still indicate activity as decoration to their label
   * the current active viewlet is indicated in the overflow menu if inside
* you can move viewlets around via DND and the position is remembered between restarts
* you can remove viewlets from the activity bar and bring them back by
   * unchecking them from the activity bar context menu
   * right clicking on the viewlet and pick the related action to remove
   * removed viewlets still show up at the end of all viewlets when they are active but hide once another viewlet opens
* you can bring back a removed viewlet either by 
   * using the context menu on the empty space of activity bar
   * by opening it and from the context menu select the related entry to keep it

Verify some corner cases where you combine:
* overflow of viewlets so you see the "..."
* reordering of viewlets
* keeping/removing viewlets

Watch out for crashes in the console in that case, there may well be some layouting bugs 👍

**Comment by seanmcbreen** [comment]
Looked good to me found some minor issues attached to this.
