### ISSUE TITLE
Bracket pairs are one colour only even when nested & do not match matching lines

### ISSUE THREAD

**Issue by SexyBeast007** [microsoft/vscode#163227]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.72.0
- OS Version: Mac OS Big Sur 11.6.3

Steps to Reproduce:

1.  I have no clue how someone else can replicate this... it's the most random and erratic issue I've had with vs code.

About a month ago a VS Code update turned OFF my bracket pair colourization randomly. I think I simply didn't update VS Code for a long time and the deprecation of Bracket Pair Colourizer 2 extension was finally turned off and now it's supposed to be built in. Well now I've been dealing with no bracket colours for over a month and tried fixing it today with the following settings and everything is weird. See pictures and settings.

```
// "editor.guides.bracketPairs": false,
    // "editor.guides.bracketPairsHorizontal": false,
    // "editor.bracketPairColorization.independentColorPoolPerBracketType": false,
    // "editor.guides.highlightActiveIndentation": false,
    // "editor.bracketPairColorization.enabled": false,
    // "workbench.colorCustomizations": {
    //     "editorBracketHighlight.foreground1": "#5caeef",
    //     "editorBracketHighlight.foreground2": "#dfb976",
    //     "editorBracketHighlight.foreground3": "#c172d9",
    //     "editorBracketHighlight.foreground4": "#4fb1bc",
    //     "editorBracketHighlight.foreground5": "#97c26c",
    //     "editorBracketHighlight.foreground6": "#abb2c0",
    //     "editorBracketHighlight.unexpectedBracket.foreground": "#db6165"
    // },
    // "editor.language.colorizedBracketPairs": [
    //     ["[", "]"],
    //     ["(", ")"],
    //     ["{", "}"],
    // ],
```

Commented settings gives me this:
Lines are correct colors but brackets are not.

[![Screen-Shot-2022-10-10-at-3-02-30-PM.png](https://i.postimg.cc/RhgSB1z9/Screen-Shot-2022-10-10-at-3-02-30-PM.png)](https://postimg.cc/Pv8sbwxF)

```
"editor.guides.bracketPairs": false,
    "editor.guides.bracketPairsHorizontal": false,
    "editor.bracketPairColorization.independentColorPoolPerBracketType": false,
    "editor.guides.highlightActiveIndentation": false,
    "editor.bracketPairColorization.enabled": false,
    "workbench.colorCustomizations": {
        "editorBracketHighlight.foreground1": "#5caeef",
        "editorBracketHighlight.foreground2": "#dfb976",
        "editorBracketHighlight.foreground3": "#c172d9",
        "editorBracketHighlight.foreground4": "#4fb1bc",
        "editorBracketHighlight.foreground5": "#97c26c",
        "editorBracketHighlight.foreground6": "#abb2c0",
        "editorBracketHighlight.unexpectedBracket.foreground": "#db6165"
    },
    "editor.language.colorizedBracketPairs": [
        ["[", "]"],
        ["(", ")"],
        ["{", "}"],
    ],
```

These settings give me:
Line colors but no bracket colors at all.

[![Screen-Shot-2022-10-10-at-3-10-13-PM.png](https://i.postimg.cc/9XsVGfFL/Screen-Shot-2022-10-10-at-3-10-13-PM.png)](https://postimg.cc/4nvrGscc)

And all settings to true gives me:
Similar result to first photo.

```
"editor.guides.bracketPairs": true,
    "editor.guides.bracketPairsHorizontal": true,
    "editor.bracketPairColorization.independentColorPoolPerBracketType": true,
    "editor.guides.highlightActiveIndentation": true,
    "editor.bracketPairColorization.enabled": true,
    "workbench.colorCustomizations": {
        "editorBracketHighlight.foreground1": "#5caeef",
        "editorBracketHighlight.foreground2": "#dfb976",
        "editorBracketHighlight.foreground3": "#c172d9",
        "editorBracketHighlight.foreground4": "#4fb1bc",
        "editorBracketHighlight.foreground5": "#97c26c",
        "editorBracketHighlight.foreground6": "#abb2c0",
        "editorBracketHighlight.unexpectedBracket.foreground": "#db6165"
    },
    "editor.language.colorizedBracketPairs": [
        ["[", "]"],
        ["(", ")"],
        ["{", "}"],
    ],
```

[![Screen-Shot-2022-10-10-at-3-11-42-PM.png](https://i.postimg.cc/VLPpf0NP/Screen-Shot-2022-10-10-at-3-11-42-PM.png)](https://postimg.cc/SjVDVs8g)

I double checked for any conflicting settings and there are none! I also uninstalled all bracket pair colorizer extensions and still same issue. Tried quitting vs code and on re-launch, same issue.

The MAIN issue here is all brackets are the same color...

What might be causing this bug?

**Comment by marcusnewton** [comment]
Can confirm this has stopped working for me.
