### ISSUE TITLE
Conda create from the shell fails (Is this an azure ml error, or a VS code error?)

### ISSUE THREAD

**Issue by jmagosta** [microsoft/vscode#163299]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

- OS Version:  Version	10.0.22621 Build 22621

Steps to Reproduce: 
1. Create new compute instance 
     Standard_D16as_v4 (16 cores, 64 GB RAM, 128 GB disk),  [CPU - General purpose](https://docs.microsoft.com/azure/virtual-machines/sizes-general)
2. Launch VS Code from the MS Azure compute blade
3. open terminal window
4. run "conda activate azureml_py38 - conda responds that an init file needs to be created and the terminal restarted.  
5. Kill terminal  and create a new terminal
6. run:  conda create -n gymrl --clone azureml_py38 
   Terminal hangs: 
    "Source:      /anaconda/envs/azureml_py38
    Destination: /anaconda/envs/gymrl
    Packages: 107
    Files: 237951"
7. Kill terminal, rerun command 
    WARNING: A directory already exists at the target location '/anaconda/envs/gymrl'
     but it is not a conda environment.
    Continue creating environment (y/[n])? y
   Conda crashes with error report:  

      # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
      
          Traceback (most recent call last):
            File "/anaconda/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
              return func(*args, **kwargs)
            File "/anaconda/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
              exit_code = do_call(args, p)
            File "/anaconda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
              return getattr(module, func_name)(args, parser)
            File "/anaconda/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
              install(args, parser, 'create')
            File "/anaconda/lib/python3.9/site-packages/conda/cli/install.py", line 219, in install
              clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
            File "/anaconda/lib/python3.9/site-packages/conda/cli/install.py", line 70, in clone
              actions, untracked_files = clone_env(src_prefix, dst_prefix,
            File "/anaconda/lib/python3.9/site-packages/conda/misc.py", line 276, in clone_env
              symlink(readlink(src), dst)
          FileExistsError: [Errno 17] File exists: '../../../webpack/bin/webpack.js' -> '/anaconda/envs/gymrl/share/jupyter/lab/staging/node_modules/terser-webpack-plugin/node_modules/.bin/webpack'
      
      `$ /anaconda/bin/conda create -n gymrl --clone azureml_py38`

**Comment by meganrogge** [comment]
this is an azure ML error
