### ISSUE TITLE
Support adding outline view to custom view containers

### ISSUE THREAD

**Issue by gee4vee** [microsoft/vscode#163205]
We are developing our own extension with a custom view container and we have our own custom document symbols for use in the Outline view. We would like the Outline view to be part of our view container alongside the others. We tried specifying this in our `package.json` but we get an error `A view with id 'outline' is already registered.`. Since the Outline view is a critical part of our extension, it makes sense for it to be part of our view container so that users don't have to switch to the Explorer.

```
    "views": {
      "catalog-explorer": [
        {
          "id": "catalogModules",
          "name": "Available Modules",
          "icon": "media/dep.svg",
          "contextualTitle": "Catalog Explorer"
        },
        {
          "id": "outline",
          "name": "outline"
        }
      ]
    },
```

**Comment by sandy081** [comment]
There is already a view with id `outline`, Can you please use another id?

**Comment by gee4vee** [comment]
@sandy081 so I can bring in the Outline view in our view container using a different ID? I'm not sure if you understood my request.

**Comment by sandy081** [comment]
>  I want to be able to add the existing outline view to my custom view container:

The existing outline view is registered to explorer and we do not support moving views to another view container descriptively. Moving views is a user choice.

**Comment by gee4vee** [comment]
@sandy081 I'm not asking to be able to move the view programmatically/descriptively. I'm asking to be able to duplicate the view. A document outline can conceptually apply to multiple view containers.

**Comment by sandy081** [comment]
Do you mean, you want the same view with same data to be shown in multiple view containers?

**Comment by gee4vee** [comment]
@sandy081 yes that's correct. It would be helpful if users did not have to choose between the two view containers to see the outline because it can be useful in both contexts.

**Comment by sandy081** [comment]
I think it's an user's preference and shall not be enforced by the product or extension. I would wait to see if other users have the same request.

**Comment by gjsjohnmurray** [comment]
@gee4vee a user can drag Outline to wherever they want it. What they can't currently do is have the Outline view in more than one view container. Allowing that might be nice, but I imagine it's not trivial to implement.

**Comment by gee4vee** [comment]
> @gee4vee a user can drag Outline to wherever they want it. What they can't currently do is have the Outline view in more than one view container. Allowing that might be nice, but I imagine it's not trivial to implement.

I can't comment on the difficulty of implementation, but I think it's more than nice. If I'm using my custom extension and I have to keep switching between File Explorer and my custom view container so that I can see the outline view, that's a pretty big hit on productivity.

**Comment by gee4vee** [comment]
@sandy081 since this is a feature request with sufficient interest, can it be reopened?

**Comment by sandy081** [comment]
@gee4vee Sorry that this cannot be reopened because it is tagged as out-of-scope:

We closed this issue because we [don't plan to address it](https://aka.ms/vscode-out-of-scope) in the foreseeable future. If you disagree and feel that this issue is crucial: we are happy to listen and to reconsider.

If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap) and [issue reporting guidelines](https://aka.ms/vscodeissuereporting).

Thanks for your understanding, and happy coding!

**Comment by gjsjohnmurray** [comment]
@gee4vee have you tried putting the Outline view on the opposite side bar?

**Comment by gee4vee** [comment]
@gjsjohnmurray I understand users can choose to put views on the left or right side. However, this feature request is so that the Outline view specifically can appear in multiple container views simultaneously. That way if I switch between views, e.g. going from File Explorer to another extension's view container, I can still see my document outline. Whether it's on the left or right is not at issue.
