### ISSUE TITLE
Color theme settings property problem

### ISSUE THREAD

**Issue by bmarvinb** [microsoft/vscode#163210]
When I change property in color theme "list.activeSelectionIconForeground" to some value, I expect that it will change only icon colors, but instead it change color for extensionButton.
So when I set "list.activeSelectionIconForeground": "#434C5E",
My button in active state become
<img width="735" alt="CleanShot 2022-10-10 at 22 07 12@2x" src="https://user-images.githubusercontent.com/23120972/194936109-10f8b8ad-25a2-4d08-ae10-9c309b42e23b.png">

**Comment by pouyakary** [comment]
I agree. Managing the side effect of a color change in VS code is really hard. It could be so cool if everything that is colored had a color property and then they could look at another property as the default value. So you could have the themes being written easily, but the theme developer could change details specifically things if they wish. Something like the way scopes in tokens work.

**Comment by aeschli** [comment]
@sandy081 The extensions view should define its own colors ID for all the colors it uses. That way theme authors can theme the extensions view separate from other views.

E.g. it's already done for the `extensionButton.prominentBackground`
![image](https://user-images.githubusercontent.com/6461412/195336916-401dff0a-bbfd-45a0-ae3a-9438cfb77932.png)

**Comment by sandy081** [comment]
Can you please help me in knowing which colours are not defined by the extension view here?

**Comment by aeschli** [comment]
For example the button shown in purple in my screenshot. It currently uses `button.background` (code is [here](https://github.com/microsoft/vscode/blob/0dd2dc89d21b3e866eeb2b7335b6c7f14ee0e031/src/vs/workbench/contrib/extensions/browser/extensionsActions.ts#L2873)).
It should either use `extensionButton.prominentBackground` or should define a new color instead, for example `extensionButton.background`.
