### ISSUE TITLE
javascript code analysis error by comment

### ISSUE THREAD

**Issue by yuanlinssdut** [Microsoft/vscode#1632]
![image](https://cloud.githubusercontent.com/assets/7608992/11991064/bfab838e-aa50-11e5-9d2c-f52dd54bc6a4.png)
![image](https://cloud.githubusercontent.com/assets/7608992/11991069/ca57a9de-aa50-11e5-9d1c-bd835dcaf8cf.png)
![image](https://cloud.githubusercontent.com/assets/7608992/11991072/d47da756-aa50-11e5-913e-6bf2ba88571d.png)

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
