### ISSUE TITLE
API: Changing a setting in default profile, triggers change event in a window with different profile

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#163243]
When both default and custom profiles have the same extension installed and in default profile extension's settings changed and saved in user config, then in custom profile (if settings are not changed), the extension internally would read settings value from default profile instead of default values.

[Here](https://github.com/microsoft/vscode/files/9750240/vscode_extension_mytestextension-profile-setting.zip) is a simple extension that adds `myTestExtension.test` setting, reads it's value and `console.log` it.

Steps to reproduce:

1) in default profile install provided extension (source included) and open devtools, _it should show `value: this is default value`_
2) in settings UI change `myTestExtension.test` setting to `blah`  _in dev tools console it should show `value: blah`_
3) open new vscode window and create a new empty custom profile
4) repeat step 1 in custom profile
5) in custom profile dev tools it shows `value: blah` which is value from default profile
6) in custom profile change the setting to `new value`, _in dev tools it shown correctly `value: new value`_
7) in custom profile reset the setting to default. _Even though in the input field it shows `this is default value`, in the dev tools it shows `value: blah`_
8) in default profile change the setting to anything (don't reset)
9) for some reason `workspace.onDidChangeConfiguration` gets triggered in custom profile, it's dev tools now shows correct `value: this is default value`. At this point the bug no longer reproducible until custom profile window restarted.

Version: 1.72.0
Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
Date: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by sandy081** [comment]
@vanowm I tried your steps and I cant repro following:

> 5. in custom profile dev tools it shows value: blah which is value from default profile

At this step, I see default value. Value from default profile is not being shown for me.

> 7. in custom profile reset the setting to default. Even though in the input field it shows this is default value, in the dev tools it shows value: blah

Also here, after resetting, I see the default value in the console.

Can you please check your steps and reproduce again and let us know if you are still seeing the issue ?

**Comment by vanowm** [comment]
@sandy081 I'm no longer able reproduce this either, however changing setting in default profile somehow triggers `workspace.onDidChangeConfiguration` event in custom profile. Shouldn't profiles be totally independent?

**Comment by sandy081** [comment]
> however changing setting in default profile somehow triggers workspace.onDidChangeConfiguration event in custom profile

Yeah, I see this too. I will investigate this.

**Comment by sandy081** [comment]
To verify:

- Write a simple extension that logs when configuration changes. Eg:
```ts
vscode.workspace.onDidChangeConfiguration(() => console.log('changed'));
```
- Open a VS Code window 1 with default profile and install above extension
- Open another VS Code window 2 with default profile and install above extension
- Change the colour theme in window 1 and make sure in console (developer tools) of window 2, nothing is logged.

**Comment by TylerLeonhardt** [comment]
> Open another VS Code window 2 with default profile and install above extension

@sandy081 I'm gonna assume you meant "with a new profile" and not "with default profile". Because based on your steps you're saying both windows use the same profile which I would expect logs in both windows.
