### ISSUE TITLE
Not all Staged files have the A indicator

### ISSUE THREAD

**Issue by RevealedFrom** [microsoft/vscode#163254]
I have an existing project. I did a `git init` followed by a `git add .`. All the (1838) files appear to be staged. (I checked with `git status`.) But not all the files in the Staged Changes section in Code have the A indicator. Two of them have the U indicator, and a bunch of them have no indicators at all.

![image](https://user-images.githubusercontent.com/5305957/195016937-1651b267-231e-4980-a1f6-41a3cfbda88d.png)

How do I interpret this?

**Comment by lszomoru** [comment]
@RevealedFrom, what is the entry in the `git status` for one of the files that do not have a decoration?

**Comment by RevealedFrom** [comment]
@lszomoru 

> @RevealedFrom, what is the entry in the `git status` for one of the files that do not have a decoration?

All files, A, U, or nothing, in `git status` say "new file:" under `Changes to be committed`.

**Comment by RevealedFrom** [comment]
I could reproduce the error repeatedly by deleting the .git folder and then `git init` again. This is the Explorer view after `git init`:

![image](https://user-images.githubusercontent.com/5305957/195110904-fce9928c-fcbd-4b49-a009-32fd236e3e55.png)

`membersOnly/archive` is in the .gitignore list but not the other two white ones. After `git add`, all the files in the `membersOnly/html` folder are correctly in the Staged area.

After committing, some files (looks like all those with U or nothing in Staged area) still show as green and U in Explorer view.

PS: My environment is Code 1.71.2 on Windows 10.

**Comment by lszomoru** [comment]
@RevealedFrom, apologies for not getting back to you on this. Are you still able to reproduce this issue? Thanks!

**Comment by RevealedFrom** [comment]
It was some time ago, and it didn't really affect my work, so I sort of forgotten about it. Thanks.

**Comment by lszomoru** [comment]
@RevealedFrom, thanks for the update. I will go ahead and close the issue. 
Please feel free to reopen it in case you are still able to reproduce the problem. Thanks!
