### ISSUE TITLE
I find that in the click panel whatever you click mouse left or rigth it will confirm click

### ISSUE THREAD

**Issue by IOLOII** [microsoft/vscode#163247]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- 版本: 1.72.0 (system setup)
提交: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
日期: 2022-10-04T23:20:39.912Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
- OS Version: 
- 版本	Windows 11 家庭中文版
版本	21H2
安装日期	‎2021/‎10/‎21
操作系统版本	22000.856
体验	Windows 功能体验包 1000.22000.856.0

Steps to Reproduce:

1. mouse right button click the side menus : to open the menus panel (Please note that it's right mouse button)
2. then mouse right button click panel with one casual click , it will checked (clicked)  the under menu which mouse overed

**In my common sense like this UI action , it may be a cancel action isn't right ?** 

Here is record video
https://user-images.githubusercontent.com/34856171/194986988-8df4b174-6eca-4a0b-b794-3fc093373757.mp4

And also find that sometime it will one right click and quick hide side menus, in the upload video it happend in the last time and one times, so I try to find why? Because right click to open menus panel and don't quickly release the mouse right button , it may be sometimes trigger this action. In a nutshell : after click side menu and release rigth mouse button later ,the right mouse button has confirm function. so this happend.

---

**oh , I have another question** : I want to know what's this terminal and what's it theme, **It looks so cool!** please
***vscode update illustration***
![vscode update illustration](https://code.visualstudio.com/assets/updates/1_72/quick-fix-similar.png)
![image](https://user-images.githubusercontent.com/34856171/194990994-9c37bc38-0bb8-4223-9ec5-3fcab0241bab.png)
I guess may be zsh, but couldn't find the theme config, help me thanks, I really want use.

**Comment by sbatten** [comment]
@IOLOII I will try to outline the intended behavior and please let me know if this does not match your experience.

1. Right click in the activity bar opens the activity bar's context menu (this menu ends with "Hide Activity Bar"
2. Right click in a menu performs the same action as left click.

Where I see a bug, the context menu is appearing on mouse down, not mouse up when the right click happens over the global actions of the activity bar.

**Comment by meganrogge** [comment]
@IOLOII my terminal is using the Dark+ (default) theme and `oh-my-zsh`

**Comment by sbatten** [comment]
To Verify:
1. Right click the Accounts Icon, Settings Gear, and Profiles Icons
2. Ensure that the behavior for the context menu matches that of a right of anywhere else in the activity bar

On Windows, this means the context menu appears at the location of the mouse click and on mouse UP.

**Comment by connor4312** [comment]
On macOS, right clicking on the manage gear does not work. The context menu flashes up and immediately closes

![Kapture 2022-11-30 at 09 53 03](https://user-images.githubusercontent.com/2230985/204872023-55578866-522d-46d3-861e-99cbe16fdcd8.gif)


Similarly, right clicking the account menu has the flash, but then the account menu instead of the ordinary context menu appears:

![Kapture 2022-11-30 at 09 50 49](https://user-images.githubusercontent.com/2230985/204871662-e7d1dec8-f5ad-471b-934c-6bbe87ab245a.gif)

Sometimes these flashes are so fast as to be invisible, but other times you can see them, as in the recordings.

**Comment by connor4312** [comment]
Actually, this works on desktop. It seems like context menus are broken in PWA in general 😬
