### ISSUE TITLE
Open Recent Folder in Windows Taskbar menu fails with spaces in folder path

### ISSUE THREAD

**Issue by briannoyes** [Microsoft/vscode#16325]
- VSCode Version: 1.7.2
- OS Version: Windows 10 AU

Steps to Reproduce:

1. Create a folder with a space in the folder name (i.e. "C:\temp\Some Folder")
2. Open in Code
3. Close Code
4. Right click on VS Code icon in taskbar
5. Select C:\temp\Some Folder from Recent Folders list in taskbar popup menu
6. Code opens with two new files created: C:\temp\Some and C:\Windows\system32\Folder and no current folder
![2016-12-01_9-52-29](https://cloud.githubusercontent.com/assets/4534445/20798335/8025af04-b7ac-11e6-9c89-e956821fc5bb.png)
![2016-12-01_9-53-06](https://cloud.githubusercontent.com/assets/4534445/20798336/8026dc08-b7ac-11e6-9bdf-8dc8cba1500a.png)

**Comment by joaomoreno** [comment]
@bpasero Some quotes needed?

**Comment by briannoyes** [comment]
yeah, probably that's all that's needed at a code level. I tried to dig down in the code base to see if I could just fix it and submit a PR, but I wasn't quite sure what the entry path is when using the Windows taskbar vs a command line (the latter handles it fine because you have to supply the quotes to pass the path in from the command line).

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/15087

**Comment by briannoyes** [comment]
Ok, sorry for the dupe. I did do some searching before submitting but that one didn't end up in the results. Thanks.
