### ISSUE TITLE
`Terminal: Focus Terminal Tabs View` shortcut doesn't work

### ISSUE THREAD

**Issue by imblowfish** [microsoft/vscode#163238]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.0
- OS Version: Ubuntu 22.04, Windows 11, MacOS 12.6

Steps to Reproduce:

1. Open 2 terminal tabs
2. `ctrl+~` to focus on terminal
3. `ctrl+shift+\` to focus on terminal tabs view

Same problem with `Ctrl+PageDown`, but `Ctrl+PageUp` works

**Comment by kolchurinvv** [comment]
I've got the same issue

**Comment by imblowfish** [comment]
I will also add that when the focus is on the terminal, executing the command via `ctrl+shift+p`->`Terminal: Focus Terminal Tabs View` also does't work

Plus, the problem is not in the when condition, I checked it according to this instruction and the condition is fulfilled https://code.visualstudio.com/api/references/when-clause-contexts#inspect-context-keys-utility
