### ISSUE TITLE
Error: No such module: atom_browser_v8_util

### ISSUE THREAD

**Issue by zhiguan-hanks** [Microsoft/vscode#16321]
- VSCode Version: Code 1.6.1 (9e4e44c19e393803e2b05fe2323cf4ed7e36880e, 2016-10-13T16:21:53.542Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions: no

exception:
stack: "Error: No such module: atom_browser_v8_util\n    at Error (native)\n    at process.atomBinding (d:\\sample\\node_modules\\electron\\dist\\resources\\electron.asar\\common\\init.js:5:20)\n    at Object.<anonymous> (d:\\sample\\node_modules\\electron\\dist\\resources\\electron.asar\\browser\\api\\browser-window.js:6:24)\n    at Module._compile (module.js:556:32)\n    at Object.Module._extensions..js (module.js:565:10)\n    at Module.load (module.js:473:32)\n    at tryModuleLoad (module.js:432:12)\n    at Function.Module._load (module.js:424:3)\n    at Module.require (module.js:483:17)\n    at require (internal/module.js:20:19)"

[.vscode.zip](https://github.com/Microsoft/vscode/files/624461/default.vscode.zip)
[package.zip](https://github.com/Microsoft/vscode/files/624462/package.zip)

Steps to Reproduce:

1.open the folder
2. run or debug

**Comment by chrmarti** [comment]
Could you upgrade to the latest stable version 1.7.2 and see if the problem persists?

**Comment by zhiguan-hanks** [comment]
I have upgraded to 1.7.2, but the problem remains.
To my surprise, when I just changed the folder name from 'd:/sample' to 'd:/sample1', no exception thrown and everything seems well working. I tried times, and the folder name changing did trigger the exception exactly.

BTW, my Electron version is 1.4.3 and Node 4.6.1.

**Comment by bpasero** [comment]
@zhiguan-hanks maybe a broken installation? can you uninstall and reinstall completely? also could you try to run from this zip folder to see if it changes something: https://az764295.vo.msecnd.net/stable/7ba55c5860b152d999dda59393ca3ebeb1b5c85f/VSCode-win32-1.7.2.zip

**Comment by zhiguan-hanks** [comment]
@bpasero I have tried to run from the zip you left, but it changed nothing.:-)

**Comment by rodzero** [comment]
Hi @zhiguan-hanks, I also had this problem. I'm using VSCode 1.8.1 and it still happens. However, if I disable the check boxes All Exceptions and Uncaught Exceptions under Debug > Breakpoints, I can debug my application without problems.

![debug-breakpoints](https://cloud.githubusercontent.com/assets/2421869/21615788/25ff924a-d1c6-11e6-91b7-fd2f891a5bdd.png)

**Comment by bpasero** [comment]
Please report back if this still reproduces with our upcoming 1.9 release.
