### ISSUE TITLE
Open in web browser 

### ISSUE THREAD

**Issue by JorgeCauich** [Microsoft/vscode#16324]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-caniuse|akamud|0.5.3|
|angular1-code-snippets|alexandersage|0.0.3|
|vscode-color|anseki|0.2.2|
|vscode-eslint|dbaeumer|1.1.0|
|live-html-previewer|hdg|0.0.1|
|vscode-exec-node|miramac|0.1.8|
|vscode-jade-snippets|mrmlnc|1.0.1|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1.Open visual studio code
2. Right-click over a file html and selecting open in web browser
http://screencast.com/t/RFRveCTvma7F

**Comment by chrmarti** [comment]
This command is contributed by the live-html-previewer. Moving the issue there.

**Comment by chrmarti** [comment]
This issue was moved to HarshdeepGupta/live-html-preview#4
