### ISSUE TITLE
Code Formatting : Is there a way to format correctly Twig or Swig tags ?

### ISSUE THREAD

**Issue by cedricnicolas** [Microsoft/vscode#16323]
- VSCode Version: 1.7 or 1.8.0 Insider
- OS Version: Mac OS 10,11,4

Steps to Reproduce:

1. Open an HTML code with swig or twig tags
![image](https://cloud.githubusercontent.com/assets/2274006/20795206/339c9e1c-b7d0-11e6-94da-02abd86f8bbf.png)

2. Format the code. Result is :
![image](https://cloud.githubusercontent.com/assets/2274006/20795225/473b3bc2-b7d0-11e6-93ba-477bca9aaae9.png)

Tried to find extensions for Twig, no one is handling code formatting. Is there anyway to configure internal code format to handle that ?

**Comment by chrmarti** [comment]
Our approach is to let extensions provide support for specific languages. I'd suggest to open a feature request with one of the existing Twig extensions: https://marketplace.visualstudio.com/search?term=twig&target=VSCode&sortBy=Relevance

**Comment by camposcristianeze** [comment]
Hi guys,
There are so many people asking for this feature and all the extensions are not being maintained properly.  Could someone take over this and improve the code formatting for Twig?

**Comment by chrmarti** [comment]
Unfortunately this is outside of what we focus on in the core product. If the extensions are no longer maintained by their creators it might be best if someone from the community could step in and submit PRs to the extensions (or fork if that doesn't work well).

**Comment by bgarrant** [comment]
I have personally requested help for all Twig extension providers on this issue and no one can help. All other editors and IDEs have Twig code formatting (beautifying) support. We need some help from Microsoft Team on this one. Any way to make Twig one of the included languagesbas it is tied tightly to HTML anyway?

**Comment by chrmarti** [comment]
Have you tried changing the editor's mode to HTML and just use the HTML formatter?

If there already is a Twig formatter you could add it via an extension. There is a slightly dated post on adding formatters: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices

**Comment by bgarrant** [comment]
The HTML formatter removes the line breaks when it encounters a twig tag like `{%` or `{{`. None of the formatting extensions support twig.  It is a real shame as that is the one feature keeping a lot of us from being able to use VSC as our full-time editor.

**Comment by chrmarti** [comment]
Your best bet might be to follow HookyQR's advice in https://github.com/HookyQR/VSCodeBeautify/issues/176#issuecomment-339428822 and invest time (or money) into js-beautify because that already implements the HTML formatting and Twig formatting appears to be an increment on top of that. You'll then still need HookyQR's VSCodeBeautify extension to pick up that support from js-beautify, but that should be the smaller task.

**Comment by camposcristianeze** [comment]
Happy to invest some time/money on it, if I don't have to change my IDE
:-).
