### ISSUE TITLE
Scroll bar overlaying on top of text

### ISSUE THREAD

**Issue by kaibyao** [Microsoft/vscode#16332]
Description:
When word wrap is turned on, a long line of text should be line-breaking before the beginning of the editor window's scroll bar. Instead, the text is reaching the very end of the editor window (including the scrollbar) before line-breaking.

NOTE: I just noticed that this only happens when:
a. a period (.) is at the beginning of a line OR
b. a space is inserted before/after a backslash (but this is random to me and I haven’t discerned a noticeable pattern).

Example:
![image](https://cloud.githubusercontent.com/assets/1090861/20804243/c25131ae-b7b7-11e6-92d3-5c58c8ce73cc.png)

- VSCode Version: 1.7.2
- OS Version: MacOS El Capitan (10.11.6)

Steps to Reproduce:
1.  Create a new editor window with `View > Word Wrap` enabled.
2. Paste the following into the first line: `a/very/long/line/of/text/that/expands/beyond/your/typical/line/of/code///decrease/the/width/of/your/editor/window/to/see/the/line/breaking/in/action`.
3. Decrease the width of your editor window so that a word wrap occurs.
4. Add a period or space to the very beginning of the text OR add a space before or after the first forward-slash (right after "a").

**Comment by chrmarti** [comment]
This is also the case without word wrap.

**Comment by alexandrudima** [comment]
@ohkaiby I cannot reproduce with out of the box settings:

I think this may be caused by a combination of color theme and font settings. Can you please also share these so I can reproduce?

![16332](https://cloud.githubusercontent.com/assets/5047891/20830868/d4a61100-b882-11e6-801a-51d52ce3699a.gif)

**Comment by ohkaiby** [comment]
@alexandrudima It happens with every color theme / font I've used. Did you follow step 4? I noticed in your recording that you did not add a dot/period to the beginning of your line.

**Comment by alexandrudima** [comment]
@ohkaiby Here I try again with a period before the first `a` and a space before the first `/`:

![16332-again](https://cloud.githubusercontent.com/assets/5047891/20840022/230c1e44-b8af-11e6-9bda-208cad269c1a.gif)

I think this issue can be reproduced when:
1) the font is not 100% monospace (i.e. bold characters are wider than regular characters)
2) you use a theme that makes all tokens bold

It might be an issue only on macOS. Here I am once again on Windows with our default font, this time configured with `fontWeight: "bold"` and I cannot reproduce:

![16332-again2](https://cloud.githubusercontent.com/assets/5047891/20840221/c911b20e-b8af-11e6-8932-c8b7ff0e5429.gif)

@jrieken @bpasero @joaomoreno Can one of you please confirm you can reproduce on macOS ?

**Comment by jrieken** [comment]
Confirmed on macOS - I always thought that's a feature...

![screen shot 2016-12-02 at 17 06 18](https://cloud.githubusercontent.com/assets/1794099/20840785/b1d2cd6a-b8b1-11e6-8629-f6497fdf6493.png)

**Comment by ohkaiby** [comment]
@alexandrudima I guess it’s specific to macOS. The fonts I tested are non-bold, monospaced fonts, and the themes don’t alter the font spacing.

**Comment by rebornix** [comment]
![wrap](https://cloud.githubusercontent.com/assets/876920/20848293/5fd3d34a-b886-11e6-9146-4b22a36136f3.gif)

I can't reproduce this on macOS sierra with word wrap turned on on both 1.7.2 and 1.8 Insiders. My settings are clean as well.

**Comment by ohkaiby** [comment]
You did not miss any step. This is very weird indeed. I'm gonna play w/ my settings a big more to see if there's an extension or setting that's the culprit.

**Comment by ohkaiby** [comment]
@rebornix @alexandrudima Figured it out. It's caused by the setting `"editor.wrappingIndent": "indent"`. Changing the setting to `"none"` or `"same"` no longer causes the scrollbar to overlap.

**Comment by rebornix** [comment]
@ohkaiby thanks for your help, I can reproduce it now :)

![screen shot 2016-12-02 at 2 18 32 pm](https://cloud.githubusercontent.com/assets/876920/20852399/8ba99d10-b89a-11e6-83c3-77d5d4f5be0d.png)
