### ISSUE TITLE
Why does reloadLocalUserConfiguration use an idle callback with a forced timeout?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#163313]
Part of #161622

This ends up exacerbating a slow startup, an idle callback will fire among other eventually/idle callbacks. Can the 5000 be removed?

https://github.com/microsoft/vscode/blob/aef171d27896f1624a7ee4e2c123820cecd81829/src/vs/workbench/services/configuration/browser/configurationService.ts#L563-L566

**Comment by sandy081** [comment]
Can you please elaborate how this is impacting perf?

**Comment by Tyriar** [comment]
It's a little hard to quantify this, but in the end it probably results in milliseconds of work (how much depends on hardware), potentially before the editor shows/tokenization is done, especially on average/low end hardware. Removing the timeout will just shift that small amount of work to around `LifecyclePhase.Eventually`. There should be a reason code runs this early and this seems like an obvious candidate to push as it's already on an idle callback.

**Comment by sandy081** [comment]
> Removing the timeout will just shift that small amount of work to around LifecyclePhase.Eventually

Trying to understand this. I think runWhenIdle runs when the browser/renderer is not doing anything. Why will this run eventually if timeout is removed? May I understand what timeout is meant for here? Does the task runs forcefully after that timeout?

**Comment by Tyriar** [comment]
Yep, when it hits the timeout its treated more like a setTimeout. Calling it without the timeout will run it whenever the main thread is not busy.

**Comment by sandy081** [comment]
Ok will remove the timeout
