### ISSUE TITLE
Shell Task Status is not correct

### ISSUE THREAD

**Issue by supermanmsc** [microsoft/vscode#163393]
Does this issue occur when all extensions are disabled?: Yes/No
YES

- VS Code Version:  
- Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:23:16.506Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No
- OS Version: 
- 
![图片](https://user-images.githubusercontent.com/12078448/195247786-ce87ffcf-89d5-4db5-8e7f-573cb8d6a29d.png)

Steps to Reproduce:

1.  make a shell task  to run a shell script file ,  set  pretention as follow:
     "presentation": {
                "echo": true,
                "reveal": "always",
                "focus": false,
                "panel": "new",
                "showReuseMessage": true,
                "clear": false
            }, 
3.  use cmd+shift +B  run this task once, then ,the terminal pannel will display  run result status as  ok 
4. use cmd+shift+b run this task twice , then  ,the terminal pannel will display two termianl window, and the bug is:  the first one and the second one all display the running icon !! when the second task  display run stauts , the first termianl display running icon all the time.

**Comment by jeanp413** [comment]
@mustard-mh is working on a fix for this :slightly_smiling_face:

**Comment by mustard-mh** [comment]
I created a PR https://github.com/microsoft/vscode/pull/163952 to fix this.
