### ISSUE TITLE
Corrupted texture visible when opening a New Window

### ISSUE THREAD

**Issue by pavlos256** [microsoft/vscode#163397]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.1
- OS Version: Arch Linux / GNOME / Wayland / RX 5600 XT

Steps to Reproduce:

1. Open a New Window
2. A corrupted texture will sometimes flash quickly while the window is initializing.

![vscode](https://user-images.githubusercontent.com/311595/195259201-38c8d1c7-afab-49f1-9465-a13fbedc3660.jpg)

Note: I'm not sure if this is a VSCode issue or a graphics driver issue. It's been happening for some time. May be related to #163395.

**Comment by deepak1556** [comment]
Please try disabling hardware acceleration https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
