### ISSUE TITLE
Terminal doesn't understand some git concepts

### ISSUE THREAD

**Issue by zohrehj** [Microsoft/vscode#16336]
- VSCode Version: 1.7.2
- OS Version: Windows server 2012

Steps to Reproduce:

1. Open terminal in visual studio code in git repo
2. type in `git reset --soft HEAD^` (should soft reset the last commit)
3. This is what I get:
```
More? y
fatal: ambiguous argument 'HEAD
y': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by mjbvz** [comment]
From the error, I suspect this has nothing to do with VSCode and I confirmed that the example git command can be run correctly from the integrated terminal.

What happens if you run the same command in the project direcotry from a regular git enabled command prompt?

**Comment by chrmarti** [comment]
In Window's cmd.exe ^ is a special character that needs escaping `HEAD^^`. Alternatively `HEAD~1` would work too. Not specific to VSCode.
