### ISSUE TITLE
Can't install release version of 'ms-vscode.remote-explorer' extension because it has no release version

### ISSUE THREAD

**Issue by gopiextrahop** [microsoft/vscode#163349]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.1
- OS Version:  Darwin arm64 21.6.0

Steps to Reproduce:

1. Update VScode to 1.72.1
2. The Remote - SSH extension asks me to `update`. When I click update, I get the error `Can't install release version of 'ms-vscode.remote-explorer' extension because it has no release version`

**Comment by roblourens** [comment]
This is now fixed in https://github.com/microsoft/vscode-remote-release/issues/7330
