### ISSUE TITLE
Allow DocumentLinkProvider define to which line in file we want navigate

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Microsoft/vscode#16331]
Right now `DocumentLinkProvider` defines it's target as a `Uri`. Unfortunately this doesn't allow us to define to which line we want to navigate. I wonder if we could extend API a bit to support navigation to specific line.

**Comment by jrieken** [comment]
It does using a `L4,9`-fragment for instance `file:///Users/foo/test.file#L12` (line) or `file:///Users/foo/test.file#L12,99` (line,column)
