### ISSUE TITLE
Settings sync in github.dev has no base

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#163311]
* using safari
* visit github.dev
* settings sync has a conflict
* conflict indicated that there is now base

I am seeing the very consistently over the last days, almost every day/time I use github.dev

<img width="1512" alt="Screenshot 2022-10-11 at 18 24 00" src="https://user-images.githubusercontent.com/1794099/195147142-b8163541-35c6-4d4b-8131-2369fd30541e.png">

**Comment by sandy081** [comment]
/duplicate

Closing this in favour of https://github.com/microsoft/vscode/issues/159037. Both are same
