### ISSUE TITLE
Idle callbacks are not running as expected during startup

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#163308]
Part of #161622

I noticed idle callbacks are peppered throughout startup, see here how 2 idle callbacks occur here before a regular timer in the middle of startup:

![image](https://user-images.githubusercontent.com/2193314/195136827-8db59c7c-bc48-4de9-83d7-1a239f625b1c.png)

Do we need to wrap `requestIdleCallback` such that it only runs after `LifecyclePhase.Eventually`?

**Comment by jrieken** [comment]
> Do we need to wrap requestIdleCallback such that it only runs after LifecyclePhase.Eventually?

The general idea is to let the browser chose. The theory is that tasks that aren't as long as expected can be filled up with some extra work. That's when it invokes pending idle-callbacks. With the invocation comes a deadlines that spec how much time you have remaining and callback running longer will be blamed. Now, the specifics when a browser detects idle-time aren't clear to me tbh, but the deadlines are usually very short (~5ms)

**Comment by Tyriar** [comment]
I need to look into this a little more to understand it better, I might just be seeing eventually phase, run idle and the terminal's delayed process connection (because of pty host init) all competing for the same time which I guess is expected.

I did spot just now that one of those that I was not expecting has an explicit timeout, which exacerbates the slow startup (https://github.com/microsoft/vscode/issues/163313):
 https://github.com/microsoft/vscode/blob/aef171d27896f1624a7ee4e2c123820cecd81829/src/vs/workbench/services/configuration/browser/configurationService.ts#L565

> Now, the specifics when a browser detects idle-time aren't clear to me tbh, but the deadlines are usually very short (~5ms)

I adopted this in xterm.js recently and it seemed like it the deadline it gave was typically around ~15-20ms, this was when there was a lot of work queued up which might loosen the deadline a little.
