### ISSUE TITLE
Simple browser webview is not reused if restored

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#163387]
- VS Code Version: stable and from sources

Steps to Reproduce:

Simple browser webviews are reused when opening different url except when the webview is restored after a reload

1. Run `Simple browser: show` command
2. Reload vscode
3. :bug: Run `Simple browser: show` again, another webview is created instead of being reused

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode/pull/163389 fixing it

**Comment by sbatten** [comment]
@mjbvz how to verify this one?
