### ISSUE TITLE
Add context actions along the lines of IntelliJ

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#16338]
- VSCode Version:Version 1.8.0-insider
- OS Version: Ubuntu

Steps to Reproduce:

1. New feature request

Currently in vscode, user can associate a shortcut to a command (or) can add a right click menu item to perform an operation either in the editor/sidebar/panel.

But IntelliJ has an additional type of provision to allow developers to contribute to generators via `alt+insert` key. This allows additional context dependent actions to be added.

For eg., if you press `alt+insert` in typescript editor, you will see actions that allows you to perform operations on the typescript file, such as generate setter,create constructor, e.t.c

If you press the same combination in explorer on a directory, you will see popup-actions to add a new file/new directory/new typescript/e.t.c

This `alt+insert` is a powerful way to reduce the total number of shortcuts, as it allows the contributors to target this `alt+insert` instead of forcing the user to remember a lot of shortcuts for every action. This shortcut is context dependent & allows structural modifications to the current panel/editor at hand.

Please check if this can be added to the core so that developers can contribute in a better way at the same time it will be less overhead on the user aswell, as user will then only need to remember `alt+insert` instead of a lot of shortcuts.

**Comment by thekalinga** [comment]
In addition to `alt+insert`, intellij also provides `alt+enter` for providing suggestions that the editor is aware of in fixing this issue in the current selection.

For eg., I have implemented an interface that expects 3 methods to be implemented.

Tho the compiler shows error & vscode displays these errors, but that's where the story currently ends.

If the platform is to be more user friendly => it should be extension friendly => it should have reasonable extension points to hook into => the need for this feature.

May (#16338)[https://github.com/Microsoft/vscode/issues/16338] too can be merged with this and can be something better than intellij depending on whether the shortcut/hover happened be on

a. character/selection with errors/warnings (or)
b. Somewhere else

For eg., if the focus happen to be in
(a) => The trigger can launch know suggestions context prompt
or (b) => Show any context actions that may be applicable

with a single key stroke/hover & click

IntelliJ currently uses two key strokes for both of these actions (alt+insert => generate new content based on context, alt+enter => show suggestions based on current selection/row)

Thanks for all your hard work in making vscode one of most promising opensource editors of our time.

For more info:
https://www.jetbrains.com/help/resharper/2016.1/Coding_Assistance__Context_Actions.html

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
