### ISSUE TITLE
Setting to disable loop of "next change" in diff view

### ISSUE THREAD

**Issue by hansu** [microsoft/vscode#163331]
Setting to stop at the bottom (or top) when navigating in the diff view through the changes with "next change" and reaching the last change.
Like @GustavoASC did in https://github.com/microsoft/vscode/pull/92243

**Comment by joaomoreno** [comment]
Go ahead.

**Comment by hansu** [comment]
@weartist Thanks a lot for implementing this. But what is the setting to enable this?

**Comment by rbadapanda** [comment]
> @weartist Thanks a lot for implementing this. But what is the setting to enable this?

Looks like this behavior got added to "editor.find.loop" setting

**Comment by hansu** [comment]
No, `editor.find.loop` does not affect this unfortunately.
