### ISSUE TITLE
Bracket pair parsing runs twice on keypress

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#163304]
Part of https://github.com/microsoft/vscode/issues/161622

Bracket pair parsing appears to happen twice on a single keypress as it happens when content changes and when tokenization happens. Typically on simple input "cheap" tokenization runs in the same task:

![image](https://user-images.githubusercontent.com/2193314/195128181-3a9b8ba9-8ecc-45d4-b5ee-4145a1c18401.png)

Consider using a microtask to execute the parsing at the end of the task a single time (which may get deferred to later depending on the outcome of https://github.com/microsoft/vscode/pull/163235), rather than eagerly during the content changed event. I haven't looked much at the code but could we do bracket matching more incrementally so it's not taking several milliseconds?

The impact of this running twice is that input latency is pushed out several milliseconds on lower end/average hardware.

**Comment by hediet** [comment]
On which document did you try this out?

**Comment by Tyriar** [comment]
> On which document did you try this out?

I was mostly using InputHandler.ts from xterm.js or terminalInstance.ts from vscode yesterday.

> The entire thing is 5.98ms, so it is 2% for me.

This is on your fast machine that is likely quite a ways off the average user (and the 50% below the average). I think for that screenshot I was using 4x CPU throttling on my main computer to emphasis slow parts.

> Also, it is by design that it reacts on both content changes and token changes - maybe it can be optimized, but I wouldn't call this a "bug".

Maybe I'm misunderstanding the incremental parsing, but if it's could do in less time what it does in content change after tokenization, it should be changed. To clarify, this is how I propose you solve it:

```ts
onContentChange(() => this._queueParse());
onTokenChange(() => this._queueParse());

_queued = false
_queueParse() {
  if (!this._queued) {
    queueMicrotask(() => this._parse());
    this.queued = true;
  }
}
```

That will make `_parse` run a single time at the end of the task (ie. before any rendering occurs).

> Here is a description of the algorithm:
https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization
>
> This section is about how incrementality is achieved:
https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization#_incremental-updates
>
> Maybe there are some cheap optimizations that I missed though (e.g. getting rid of recursion).

What confused me a little is why it wasn't essentially instant when I was just typing a non-bracket character. I didn't look into how the algorithm works or dig very deep into the code as I'm sure you know what you're doing there, I'm more interested in ensuring it doesn't waste time running twice in a single task and whether this can be deferred to shortly after text is rendered.

**Comment by Tyriar** [comment]
Outcomes from our meeting:

- We probably can't defer this stuff as character changes next to brackets will shift the bracket decorations to the character to the left or right for example
- We could merge content and token change handlers into a handler, we would need to merge the ranges such that they don't overlap:
 
https://github.com/microsoft/vscode/blob/00b54ae23e42ed42f36393bb957482d13a19ebb5/src/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/bracketPairsTree.ts#L85-L113

- I'll set up a meeting for early next month to walk through the actual parsing code to see if we can come up with ideas to optimize

**Comment by hediet** [comment]
@Tyriar can you verify this issue?

**Comment by Tyriar** [comment]
I do see it happening twice on a single keypress, but one of them is delayed until stick scroll renders which occurs after `provideInlineCompletions` triggers another tokenization. So the problem I was pointing out that affects input latency is fixed 👌
