### ISSUE TITLE
VSCode can't open large CSV file

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/vscode#16335]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Anniversary Update

Steps to Reproduce:

1. Download [Lending Club data for Q3 2016](https://www.lendingclub.com/info/download-data.action)
2. Extract ZIP file into CSV file (**76.3 MB** uncompressed)
3. Open CSV file in Visual Studio Code

@alexandrudima you asked for a new issue, for each unique case of large files, so here's mine. Let me know if you need anything else from me. #6474 #13187

### Notes

- Notepad opens the same file successfully
- Excel 2016 opens the same file successfully

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by poscar** [comment]
👍

**Comment by tylerwaterfall** [comment]
What is the filesize limit? I have the same issue - a log file (tab separated) 76MB... No issues with other text editors. :(

**Comment by leizhiyuan** [comment]
@tylerwaterfall 
according this File
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/files/common/files.ts 


export const MAX_FILE_SIZE = 50 * 1024 * 1024;

It may be 50m size..

**Comment by dragonwolf83** [comment]
Let's not call this a large file, this is a medium file. Large files get in the range of 700MB - 4GB range. This is an important distinction because a lot of editors can open medium size files (100-400MB) but fail in the true large file size range.

**Comment by isidorn** [comment]
This file can now nicely be opened in the 64 bit version of vscode

**Comment by pcgeek86** [comment]
Awesome! 🤓
