### ISSUE TITLE
Repo issues 

### ISSUE THREAD

**Issue by v-macohen** [microsoft/vscode#163435]
I am writing to document my recent critical, blocking issues with Visual Studio Code.  I have also contacted my manager, Jon Meyers (jmeyers@microsoft.com) and the Help Desk Support.

On Friday 10/7/22, I called the Help Desk and spoke to Alejandro Cabrera Araya (DXC Technology Services LLC) <v-acabreraar@microsoft.com>
regarding a security issue that popped up. A ticket was filed (ticket numbers available if needed) and we had to merge two accounts. My v-macohen name hasn’t changed, but we had to redownload several programs. While I was able to download VSC, I was unable to clone the repo. On Monday I tried at least four times to clone the repo with the help of a teammate. I tried this using the instructions that the entire ADS UA team uses in the Notebook.
It was suggested by my manager Jon Meyers that I should run over these steps with a member of the Visual Studio help. It is worth noting that these steps have worked for the team, which leads me to believe that the issue is perhaps my computer.

My goal in calling the VS Help desk will be to figure out my my repo is not cloning. 

My VSC-savvy teammate provided me with a “buffer command” (git config http.postBuffer 524288000) which I added to the Terminal in VSC. Image available if needed. This failed.

<img width="761" alt="Vs 1" src="https://user-images.githubusercontent.com/108083277/195380385-9beff8ec-ea78-44bb-bbfa-a90d0dadf237.png">

He also provided me with another code (git config --global http.postBuffer 52428800).
That also did not work. Image available.

<img width="596" alt="Vs 2" src="https://user-images.githubusercontent.com/108083277/195380435-f6d4f481-bd1c-41c1-ac63-a77c1e94e5d3.png">

Yesterday in the late afternoon, I again contacted @Alejandro Cabrera Araya (DXC Technology Services LLC) via the Help Desk. He was able to try several steps with me, but ultimately all failed.
Alejandro connected me with the support for Visual Studio (there does not seem to be on just for  Visual Studio Code). We tried to fill out a ticket but the system tried to sign me up for some kind of support. 

 
We then went to Settings - Microsoft Azure where I tried to add the directory ID under my name. That didn't work either.
Ultimately, Alejandro  gave me the help desk number for Visual Studio (it seems there is not one just for VSC) and the email address vsdisc@microsoft.com .

Any ASAP help you can give on this blocking, critical issue would be greatly appreciated. I can be reached at v-macohen@microsoft.com or 954-854-0270. My manager's info is listed above.

Thank you.

**Comment by lszomoru** [comment]
@v-macohen, sorry for hear about the issue that you are running into. If I understand your description correctly, you seem to be unable to clone a particular repository using VS Code. In order to narrow down the root cause, I would like to ask you to take VS Code out of the picture completely and try to clone the repository from the command prompt or Windows Terminal. Are you able to clone the repository outside of VS Code? If not, what is the error that you are running into? Thanks!

**Comment by v-macohen** [comment]
Hi,
Thanks so much. We were able to resolve the issue!

Best,
Marissa
