### ISSUE TITLE
Notebooks show "no renderer"

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#163415]
* todays insiders
* open any notebook (ipynb or ghinb)
* no output is rendered

<img width="832" alt="Screenshot 2022-10-12 at 11 05 22" src="https://user-images.githubusercontent.com/1794099/195302952-7dea5cf8-6a74-451c-a7cf-a08ae900e95c.png">

**Comment by jrieken** [comment]
reverting https://github.com/microsoft/vscode/commit/8b0248854a4c6996ddea13e30dcc4fb0b56ef53b fixes this

**Comment by mjbvz** [comment]
Ugh sorry, missed a case where we were calling `URI.isUri(this.entrypoint)`
