### ISSUE TITLE
Не устанавливает расширение такие как Python, C#, Debug for Chrome C/C+ 

### ISSUE THREAD

**Issue by olimjhonov** [Microsoft/vscode#16344]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|php-debug|felixfbecker|1.10.0|
|vscode-clang|mitaki28|0.2.1|
|JavaScriptSnippets|xabikos|1.2.0|
|Material-theme|zhuangtongfa|1.0.3|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
Translation:

> I can't install extensions such as Python, C#, Debug for Chrome C/C+

  * Что значит "не устанавливает расширения"?
  * Что выводится в `Help -> Toggle Developer Tools` при попытке установить расширение?
  * Используете прокси?
  * Что выводится при попытке выполнить команду в консоли?

    ```
    code --verbose --install-extension mrmlnc.vscode-less
    ```

**Comment by joaomoreno** [comment]
Proxy.
