### ISSUE TITLE
cmd+, no longer opens settings

### ISSUE THREAD

**Issue by danawoodman** [microsoft/vscode#163472]
Does this issue occur when all extensions are disabled?: Yes/No

```
Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:25:13.482Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

Steps to Reproduce:

1. Open VSCode on a Mac
2. Type `cmd+,` to open settings
3. Nothing happens

I've tried this on Insiders and regular VSCode with no extensions with the same result. I've disabled other apps to make sure they weren't overriding the keyboard shortcut, but I couldn't find anything.

I've also restarted my computer and VSCode to confirm, same result.

**Comment by rzhao271** [comment]
I'm unable to repro on the latest Insiders on Monterey. This issue has shown up before, so I'm thinking there might be a race condition involved.

Also, instead of restarting the computer or app entirely, one can also run the "Developer: Reload Window" command.

**Comment by danawoodman** [comment]
@rzhao271 yeah, I've done that and everything else I can think of (restarting sometimes fixes weird stuff like this). I don't know how else I can troubleshoot this, any suggestions?
