### ISSUE TITLE
command 'extension.connect' not found

### ISSUE THREAD

**Issue by arvindravish** [Microsoft/vscode#16342]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-monokai-dark-soda|AdamCaviness|0.0.5|
|vscode-color|anseki|0.2.2|
|theme-onedark|azemoh|0.4.0|
|plsql|casian|0.0.2|
|python|donjayamanne|0.5.5|
|xml|DotJoshJohnson|1.6.0|
|terminal|formulahendry|0.0.5|
|Theme-azure|gerane|0.0.2|
|Theme-FlatlandMonokai|gerane|0.0.4|
|Theme-monokai-best|gerane|0.0.2|
|prettify-json|mohsen1|0.0.3|
|mssql|ms-mssql|0.1.5|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|PowerShell|ms-vscode|0.7.2|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|team|ms-vsts|1.108.0|
|startanyshell|remcoros|0.3.1|
|theme-obsidian|rprouse|0.2.0|
|usql-vscode-ext|usqlextpublisher|0.1.9|
|vim|vscodevim|0.4.4|
|Material-theme|zhuangtongfa|1.0.3|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. CTRL + SHIFT + P
2. MSSQL:CONNECT

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-mssql#448

**Comment by arvindravish** [comment]
Re-installing the VS Code followed by MSSQL extension fixed the problem for me. Thanks
