### ISSUE TITLE
codespace infinte loading

### ISSUE THREAD

**Issue by jvben76** [microsoft/vscode#163447]
codespace won't load.

it either gets stuck on connecting window, starting window or just infinitely loops when the IDE opens. Can't use CLI, folders in GUI can't be accessed, just loads forever.

Version: 1.72.1
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by roblourens** [comment]
Please open a topic at https://github.com/community/community/discussions
