### ISSUE TITLE
terminal cursor is too ugly and misleading

### ISSUE THREAD

**Issue by q2333gh** [microsoft/vscode#163426]
Type: <b>Feature Request</b>

i just wanna thin blink cursor,
the default square is really really misleading
that square cursor just  like insert!
 please change it !

VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by q2333gh** [comment]
![image](https://user-images.githubusercontent.com/32679742/195333209-fbb67485-8272-4196-ad6f-5f09f9375b9e.png)

![image](https://user-images.githubusercontent.com/32679742/195333284-15ddfcea-0853-4125-bdfe-15fdd15e7ea5.png)

i just wanna this blinking cursor . it`s much much more beautiful!

**Comment by q2333gh** [comment]
i searched for google this problem ,seems no solution.and seem nobody concern about it
maybe they use windows terminal .its much much more beautiful than vscode`s terminal

**Comment by meganrogge** [comment]
<img width="550" alt="Screen Shot 2022-10-18 at 2 19 47 PM" src="https://user-images.githubusercontent.com/29464607/196512468-591a2df8-a722-416e-82e4-eee26359232a.png">
