### ISSUE TITLE
Font is not changed for debug console input field.

### ISSUE THREAD

**Issue by aquix** [Microsoft/vscode#16343]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393

---

Steps to Reproduce:

1. Set custom font in settings
2. Run any script in debugger and open Debug Console
3. See that font is still default (Consolas on Windows)

![image](https://cloud.githubusercontent.com/assets/11872957/20811844/5becef66-b820-11e6-9e76-c16cf21e2011.png)

**Comment by chrmarti** [comment]
@isidorn Is this #1957?

**Comment by isidorn** [comment]
Yes closing as dup
