### ISSUE TITLE
Fold Disappeared

### ISSUE THREAD

**Issue by lukemccartney** [microsoft/vscode#163454]
Type: <b>Bug</b>

The ability to fold away segments of code disappears at random.

VS Code version: Code 1.72.1 (Universal) (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:25:13.482Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 9caa6cd3-5022-4994-8515-cece701ebce2|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
icons-carbon|ant|0.2.6
agda-mode|ban|0.3.11
npm-intellisense|chr|1.4.2
dart-code|Dar|3.50.0
flutter|Dar|3.50.0
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
vsc-material-theme-icons|equ|2.4.0
chuck|for|0.2.1
copilot|Git|1.50.6974
vscode-pull-request-github|Git|0.50.0
go|gol|0.35.2
haskell|has|2.2.1
Ionide-fsharp|Ion|7.3.0
agda|j-m|0.1.7
cmake-language-support-vscode|jos|0.0.4
language-haskell|jus|3.6.0
lean4|lea|0.0.95
dart-import|lua|0.3.1
mimium-language|mim|1.1.2
vscode-azureresourcegroups|ms-|0.5.6
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.1
csharp|ms-|1.25.0
dotnet-interactive-vscode|ms-|1.0.3504060
vscode-dotnet-pack|ms-|1.0.9
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.16.0
jupyter|ms-|2022.9.1202862440
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.3
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
azure-account|ms-|0.11.2
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
live-server|ms-|0.4.3
vscode-typescript-next|ms-|4.9.20221011
vsliveshare|ms-|1.0.5733
vsliveshare-audio|ms-|0.1.91
phoityne-vscode|pho|0.0.28
vscode-tidalcycles|tid|1.4.1
cmake|twx|0.0.17
vscode-icons|vsc|11.20.0
material-theme|zhu|3.15.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30583747
fc301958:30573243

```

</details>

**Comment by aeschli** [comment]
For what language is that? Does it reproduce with extensions disabled?

**Comment by lukemccartney** [comment]
It was with Python. I uninstalled multiple extensions and it seems to be
fixed. I have a feeling agda-mode was the problem but that isn’t confirmed
yet.

**Comment by aeschli** [comment]
Thanks, needs to be filed against agda-mode then
