### ISSUE TITLE
Param /c for CMD erroneously appear for externalTerminal when terminal.external.windowsExec is WindowsTerminal

### ISSUE THREAD

**Issue by ngkaichak** [microsoft/vscode#163409]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.1
- OS Version: Windows 10 64-bit 19044.2006

Steps to Reproduce:

1. Create a blank file app.js, and a launch config:
```json
{
    // vscode can Debug node.js without any extension.
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch Program",
            "program": "${workspaceFolder}/app.js",
            "request": "launch",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "node",
            "runtimeExecutable": "node",
            "console": "externalTerminal"
        }
    ]
}
```
2. Open Settings, set "terminal.external.windowsExec" value "wt.exe", which is WindowsTerminal.
3. Start debug, WindowsTerminal shows an Error ( The following argument was not expected /c ),and exit
![image](https://user-images.githubusercontent.com/22956763/195286702-b18fbd09-66e0-4c81-bd40-266ac6baf42f.png)

4. As I know,/c is a param for CMD, means "Carries out the command specified by string and then terminates", it's not for WindowsTerminal .
5. This also occur  when debug other program, like Python.

**Comment by connor4312** [comment]
Fixed in https://github.com/microsoft/vscode/pull/171093
