### ISSUE TITLE
[sql] syntax highlighting error

### ISSUE THREAD

**Issue by DenSmoke** [Microsoft/vscode#1634]
Problems with ' '
![f](https://cloud.githubusercontent.com/assets/16131575/11993935/7015f930-aa50-11e5-857d-e862ff373182.PNG)

**Comment by aeschli** [comment]
@DenSmoke Denis, can you paste problematic snippet? It looks like an issue with Unicode characters which I see as well, but I get different errors. Thanks!

**Comment by DenSmoke** [comment]
@aeschli 
5.1.1
INSERT INTO
	ТОВАРЫ(ИЗГОТОВИТЕЛЬ,ШИФР,НАИМЕНОВАНИЕ,ЦЕНА,ЛИМИТ)
VALUES 
	('ААА','А01','Какой то товар',100,20)
	SELECT * FROM ТОВАРЫ
5.2.1
INSERT INTO
	СТРОКИ_ПРАЙСА (КОД_ТОВАРА,НАЗВАНИЕ_ТОВАРА,ЦЕНА_ТОВАРА)
	SELECT
		ИЗГОТОВИТЕЛЬ||ШИФР,НАИМЕНОВАНИЕ,ЦЕНА
	FROM 
		ТОВАРЫ
	WHERE
		ИЗГОТОВИТЕЛЬ<>'ЗОМ'

**Comment by aeschli** [comment]
This issue was moved to textmate/sql.tmbundle#12

**Comment by k--kato** [comment]
delete lines: 570-590, it will work fine.
https://github.com/k--kato/vscode/commit/ca1924c032c0153c36ac2a84b0363dbdc55f51ce

**Comment by gontadu** [comment]
Is it that VSCode uses TextMate's format for the language syntax plist?

**Comment by aeschli** [comment]
This seems to work in the meantime. Verified in 1.10-insiders.
![image](https://cloud.githubusercontent.com/assets/6461412/23277800/898f4c6c-fa0f-11e6-98e3-6612b3dbefb6.png)
