### ISSUE TITLE
September 2022 Recovery 2 Endgame

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#163401]
- [x] Create a milestone `September 2022 Recovery 2` **@lszomoru**
- [x] Bump the version number **@lszomoru**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22September+2022+Recovery+2%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [x] Initiate `insiders` build from `main`
- [x] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@lszomoru**
- [ ] Issues are verified on `stable` build and the `verified` label is added **team**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/1.72` to ensure no other commits have been made in the release branch **@lszomoru**
- [ ] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit @hediet 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit @hediet 
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
  - [x] Windows ARM64 @joaomoreno 
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
  - [x] macOS
    - [x] Universal @weinand/@jrieken
    - [x] Intel @weinand 
    - [x] Intel server @weinand 
    - [x] Apple Silicon @jrieken 
  - [x] Linux x64 @aeschli 
    - [x] deb 
    - [x] rpm 
    - [x] archives 
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`) 
  - [x] Linux server @chrmarti 
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
    - [x] ARM64 Alpine
- [x] Publish website **@gregvanl**
- [x] Publish stable build **@mjbvz**
- [x] Create an official release **@mjbvz**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@mjbvz**

**Comment by mjbvz** [comment]
Published 🚀

**Comment by icy-fish** [comment]
> Published 🚀

@mjbvz Thanks for working, but just one question: did you guys noticed that source codes of tag 1.72.2 are exactly same with tag 1.72.1, which based on commit 129500e ?

**Comment by DeeDeeG** [comment]
Yeah, as @icy-fish said, the git tags "1.72.1" and "1.72.2" for this repo both point to commit 129500e.

Comparison showing no diff, no new commits: https://github.com/microsoft/vscode/compare/1.72.1...1.72.2

So I think the "1.72.2" tag was applied to the wrong commit. I'm unclear if that has anything to do with what code got built into the binaries published for 1.72.2, or whether downstreams such as VSCodium would  be affected by accidentally building the older code from Sept 2022 Recovery _1_ instead?

Would it be appropriate to re-tag the actual new commits, and possibly force-push the tag? Or maybe publish the corrected tag as a new version number for less disruption to contributors, forks and downstreams?

Thanks for considering.

**Comment by mjbvz** [comment]
Thanks. The tag should be fixed now

**Comment by DeeDeeG** [comment]
Thank you!

Related: I think changing the git tag may have booped the GitHub Release, since it's not visible to me at the moment. (Perhaps it got converted to draft. Similar has happened to me before when updating tags.)
