### ISSUE TITLE
Stalls caused by large global storage object

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#163446]
Thanks to @sandy081 for troubleshooting this together.

* install GHPR extension and log in, etc.
* open multiple windows
* open `vscode-build-tools`
* the global storage object for GHPR should now be ~3MB. This is caused by a property called `mentionableUsers` specific to that repository.
> <img width="571" alt="image" src="https://user-images.githubusercontent.com/5047891/195398046-defad9fa-8a0a-41e0-add5-92818a9ab7fd.png">
> <img width="1368" alt="Screenshot 2022-10-12 at 17 00 32" src="https://user-images.githubusercontent.com/5047891/195398134-88561582-722f-4575-bad1-5b2c68c77c89.png">
* open multiple windows, I have around 7
* start CPU profiling in one window
* in another window refresh the GHPR views
* this will cause the GHPR extension to write to global storage, which will create an event which will bubble to all other windows and will cause 300ms stalls in all windows:

> [CPU-20221012T183146.cpuprofile.zip](https://github.com/microsoft/vscode/files/9766946/CPU-20221012T183146.cpuprofile.zip)

> <img width="622" alt="image" src="https://user-images.githubusercontent.com/5047891/195399188-ba484c9d-79c2-4b8a-b87c-1a81aadaddd2.png">

I think there are two problems here:
* the GHPR should not write so much data to global storage
* the memento mechanism for extensions should either be a lot more performant or should warn / error if the object being written is so large as to cause freezes.

**Comment by alexr00** [comment]
Caching was added for https://github.com/microsoft/vscode-pull-request-github/issues/2892. 

I can move it to a file.

**Comment by bpasero** [comment]
A follow up from talking with @sandy081 is to investigate if we can defer the `JSON.parse` to when we really need the data. For extension data we could investigate to send the data to the extension host raw because the renderer never needs the parsed data.
