### ISSUE TITLE
Exception while running code on VS Code Debug Console, runs fine in VS Code Terminal and Win7 Command Line

### ISSUE THREAD

**Issue by wessiyad** [Microsoft/vscode#16340]
- VSCode Version: 1.7.2
- OS Version: Windows 7 SP1

Steps to Reproduce:

It appears that making this call is causing the error -             
```Console.SetCursorPosition(Console.CursorLeft - 1, Console.CursorTop);```

Sample code here: https://github.com/wessiyad/vscode-debug-console-error

**Comment by weinand** [comment]
The VS Code debug console is not a "console" that the .net library is able to recognise or use. 
This is the expected behaviour.
Since your program works fine in the VS Code Integrated Terminal (and most likely in a VS Code External Terminal as well), there are no plans to remove this limitation.
