### ISSUE TITLE
Find in files displays "spawn /snap/code/102/usr/share/code/resources... ENOENT" error

### ISSUE THREAD

**Issue by NojiLM** [microsoft/vscode#163478]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Open VSCode
2. Press control-shift-F
3. Click the magnifying glass
4. Enter text into the text field
I've seen others report similar, but their solution doesn't fix it for me.

**Comment by NojiLM** [comment]
Nevermind...on a different thread, the super suggested restarting the computer, I did that, and it's back to normal now. Sorry to have bothered you. Obviously a VSC bug.

**Comment by roblourens** [comment]
I'm not sure why this kind of thing happens sometimes, let me know if it breaks and can't be fixed
