### ISSUE TITLE
Switching tabs resolves `git:/...` URLs everytime even when nothing changed

### ISSUE THREAD

**Issue by juanjo75es** [microsoft/vscode#163499]
Does this issue occur when all extensions are disabled?: Yes (?) I test it in the docker container 

- VS Code Version: 
- OS Version: OSS (?)

Steps to Reproduce:

1. Load a project from a Github repository
2. Open two files from the file explorer (generating two tabs)
3. Put a breakpoint at the function resolveFromFile 
4. Focus on another tab
5. Check with the debugger what this function does. The file focused will be reloaded every time. In case it is a large file it won't be due to a final check in the code but this does not seem the right behavior. I think it should not attempt to reload  every time and even if it is a large file maybe it should reload if it has been modified (maybe disabling controls and showing a popup while it does)

It seems that the problem is in the lastResolvedFileStat: it is reset or not updated at some point. 
This is where the check fails:

```
// Decide on etag
let etag: string | undefined;
if (forceReadFromFile) {
	etag = ETAG_DISABLED; // disable ETag if we enforce to read from disk
} else if (this.lastResolvedFileStat) {
	etag = this.lastResolvedFileStat.etag; // otherwise respect etag to support caching
}

```
_File /workspaces/vscode/src/vs/workbench/services/textfile/common/textFileEditorModel.ts , line 419_

**EDIT: The problem seems to happen only when using a git repository. Looks like TextFileEditorModelManage.doResolve receives "git:file_uri" while it has only registered "file:file_uri" and therefore every time onEditorsChanged is fired it generates a new instance of TextFileEditorModel which consequently has no lastResolvedFileStat**

I'd like to try to fix it myself and make a pull request if I am confirmed that this is an issue and you don't have any objection.

**Comment by juanjo75es** [comment]
I don't know what this function does but if I comment it, there is no longer this issue and there is no apparent side-effect.

```
private onModelVisible(textFileModel: IResolvedTextFileEditorModel): void {
	/*const model = this.instantiationService.createInstance(DirtyDiffModel, textFileModel);
	const decorator = new DirtyDiffDecorator(textFileModel.textEditorModel, model, this.configurationService);
	this.items.set(textFileModel, new DirtyDiffItem(model, decorator));*/
}
```
_Line 1481 of /workspaces/vscode/src/vs/workbench/contrib/scm/browser/dirtydiffDecorator.ts_

I think this architecture design that involves creating new models to replace the old ones every time there is an event seems wrong and prone to cause issues like this one.

**Comment by bpasero** [comment]
We resolve the contents of a file from disk when you click on a tab. We do that in the background without blocking the opening. We do that to ensure the latest contents are loaded from disk.

As for the dirty diff decorator, moving to respective owners.

**Comment by joaomoreno** [comment]
I don't quite understand what the bug is. Is there something not quite working in the product?

**Comment by juanjo75es** [comment]
Thanks for your comments.
I think you really do not resolve the contents from the disk when the file is large... but anyway, I don't think anyone will notice it except if digging into the code. Your solution doesn't seem elegant and seems prone to cause future problems, but I was just looking at the code and found that casually. I am not really interested. I was interested in starting a branch for visualizing very large files in a google maps way (for example for visualizing genomic data) and found that "problem". But I lost interest as the code seems quite hard to work with (too many events for my taste and I didn't find any documentation for the events).
I think this issue can be closed if you are not interested. It could be interesting working on the large files navigation though if you can help me find information for not having to debug every event.

**Comment by bpasero** [comment]
> I think this issue can be closed if you are not interested.

Actually my comment in https://github.com/microsoft/vscode/issues/163499#issuecomment-1306670820 was wrong: we do NOT resolve the contents of the file on disk every time but only when we think it has changed. We compare the `mtime` of the file with our last state and skip resolving when the file did not advance in `mtime`. But as you indicated before, this requires the model to stay in memory so that we can compare the previous state to the current one. I think you figured out that we use `etag` concept for this.

But you are also right that this optimization fails to apply for the dirty decorator. I ran an experiment with clicking between 2 tabs and this is the log output:

```
TRACE [text file model] dispose() git:/Users/bpasero/Documents/ticino-playground/nakefile.js.git?%7B%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Fnakefile.js%22%2C%22ref%22%3A%22%22%7D
log.js:192 TRACE [text file model] resolve() - enter file:///Users/bpasero/Documents/ticino-playground/nakefile.js
log.js:192 TRACE [text file model] resolveFromFile() file:///Users/bpasero/Documents/ticino-playground/nakefile.js
log.js:192 TRACE [text file model] resolve() - enter git:/Users/bpasero/Documents/ticino-playground/nakefile.js.git?%7B%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Fnakefile.js%22%2C%22ref%22%3A%22%22%7D
log.js:192 TRACE [text file model] resolveFromFile() git:/Users/bpasero/Documents/ticino-playground/nakefile.js.git?%7B%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Fnakefile.js%22%2C%22ref%22%3A%22%22%7D
log.js:192 TRACE [text file model] resolveFromContent() - enter git:/Users/bpasero/Documents/ticino-playground/nakefile.js.git?%7B%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Fnakefile.js%22%2C%22ref%22%3A%22%22%7D
log.js:192 TRACE [text file model] doCreateTextModel() git:/Users/bpasero/Documents/ticino-playground/nakefile.js.git?%7B%22path%22%3A%22%2FUsers%2Fbpasero%2FDocuments%2Fticino-playground%2Fnakefile.js%22%2C%22ref%22%3A%22%22%7D
```

So there is evidence that the optimization is not working for git dirty diff decorators because the text file model that is used for it is disposed once we compute the next diff. If we wanted to improve this, the models would have to be kept around in memory until the tab is closed maybe.

**Comment by juanjo75es** [comment]
I am pretty sure that there is also a check somewhere hidden at the end of a chain of events in which the file is not reopened even if the etag check is passed but the file is too large. But I was checking that more than a month ago and now I can't find it.

**Comment by alexr00** [comment]
What's the best way to verify this?

**Comment by alexr00** [comment]
Verified offline with @joaomoreno
