### ISSUE TITLE
Feature: create multiple files using brace expansion

### ISSUE THREAD

**Issue by equiman** [microsoft/vscode#163497]
If you want to create sibling files inside VS Code, you need to create them manually, each one by one.

I would like to have the ability to create multiple files at once using brace expansion (like bash).

1. Use the `Create New File` option
![image](https://user-images.githubusercontent.com/933393/195469747-2205e6e1-7821-4364-b0b4-97e3852b5eca.png)

2. Write the file structure 
![image](https://user-images.githubusercontent.com/933393/195470220-37a4120e-bdf4-40a8-b8a5-5a584a150fe5.png)

3. Automatically create the files
![image](https://user-images.githubusercontent.com/933393/195469838-e6a90c96-2567-44cb-8361-901d0adaf9ff.png)

This option is actually available on bash with brace expansion.

Same example from the terminal:
```bash
take new && touch New{{.types,.test,}.tsx,.css}
```
More examples here:
https://www.devsrealm.com/posts/9a476191cd7eaa4d/create-multiple-files-at-once-using-brace-expansion-in-bash

It will be great to have it inside the VS Code explorer files, without the need to open a terminal for that.

**Comment by lramos15** [comment]
There is currently a PR out for this which is under discussion https://github.com/microsoft/vscode/pull/162893

**Comment by equiman** [comment]
Perfect, so I close this. Thanks!
