### ISSUE TITLE
`window.showNotebookDocument` fails for Interactive Window with "Notebook Editor creation failure for document [object Object]"

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#163469]
this is causing Interactive window restore to fail: https://github.com/microsoft/vscode-jupyter/issues/11574

1. set "interactiveWindow.restore": true
2. run a cell from a .py file to create an interactive window
3. reload VS Code
4. run a cell from the same .py file to re-use the interactive window
🐛 a new editor is created and fails to open

**Comment by lramos15** [comment]
Is this finished via https://github.com/microsoft/vscode/pull/163710?

**Comment by amunger** [comment]
yes, closings
