### ISSUE TITLE
Sorting tests in test explorer 

### ISSUE THREAD

**Issue by zljubisic** [microsoft/vscode#163449]
Type: <b>Bug</b>

If you look at the picture...

![image](https://user-images.githubusercontent.com/67708897/195381617-a3f86acd-0b9e-4748-a6a6-7e2df01ff721.png)

...you can see that tests in test explorer are sorted by parameters.
Due to the sorting, when we have a test with lot of parameters, we cannot distinguish which one failed. To find out failed test, we have to comment all parameters and than uncomment one by one.
If I pres "Go to Test" button, on any parameter, it leads me to the `@pytest.mark.parametrize()` line, which means it is not usable at all. It would be usable if "Go to Test" points to test parameters.
For example if I press it on the line from the picture above, the cursor should be positioned at line 12, not 7.
As it is right now, you can freely remove "Go to Test" from parameters, and just leave the one on the root (`test_print_one`) because it is useless.

Either stop sorting tests in test explorer (at least parameterized tests) or make "Go to Test" to go to selected parameters.

Extension version: 2022.16.0
VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

**Comment by zljubisic** [comment]
To make things more interesting you have two different orders:

![image](https://user-images.githubusercontent.com/67708897/195430491-603c9a4e-f89d-480b-b437-a29d7d629ad0.png)

**Comment by zljubisic** [comment]
> > make "Go to Test" to go to selected parameters.
> 
> This is a limitation of `pytest` itself. It does not provide the line number for the parameter. So there is no way for us to find it accurately in all scenarios. This will require work on pytest itself and then we can add that. Created [microsoft/vscode-python#19995](https://github.com/microsoft/vscode-python/issues/19995) to track this request.

All pytest parameterized tests have the same structure in a decorator: a string parameter and a list of tuples.
If you introspect decorator, that should be enough isn't it?

**Comment by karthiknadig** [comment]
> All pytest parameterized tests have the same structure in a decorator: a string parameter and a list of tuples.
If you introspect decorator, that should be enough isn't it?

@zljubisic Pytest has several extensions where the parameters are generated on the fly, the params may be wrapped by an id instead of representing them as string. You could even write out tests like this:
```python
@pytest.mark.parametrize('a', [1,2,3,4,5])
@pytest.mark.parametrize('b'. [True, False])
def test_something(a,b): ...
``` 
We would want `pytest` itself to provide us the line numbers. This way, pytest or any of its extensions can decide what is right for their scenario. We can discuss that here: https://github.com/microsoft/vscode-python/issues/19995

This issue here can track the Test Explorer UI part of the problem.

**Comment by zljubisic** [comment]
In the mean time, the only solution is to comment and uncomment tests to find out the one that has failed, isn't it?

**Comment by karthiknadig** [comment]
The failed tests should be marked as failed, so you could just use the `Test: Rerun failed tests` command from the pallet to run just the failed ones. But, for now there is no way to go to the exact parametrized value that triggered it.

**Comment by zljubisic** [comment]
Can you please turn on stop watch and tell me which parameters has failed and provide result here?

![image](https://user-images.githubusercontent.com/67708897/195522992-28866045-e131-4e0d-afc9-e1c5a77f1ed6.png)


![image](https://user-images.githubusercontent.com/67708897/195523186-8d7fe97d-cc5e-41aa-a0ab-479896ae3664.png)


Now consider that you are testing integration with lots of branches, lots of parameters (here we have only two but still it is not easy, you have to reach to the dictionary, with key find value, now it is at the same screen but usually it is on the very beginning of the file... I believe that you have got the picture).

**Comment by zljubisic** [comment]
I am just curios, how you know which test parameters to use if "Debug Test" button is pressed?

![image](https://user-images.githubusercontent.com/67708897/195583001-9429c84d-585e-49fe-8c72-bd2357d1942e.png)

**Comment by karthiknadig** [comment]
> I am just curios, how you know which test parameters to use if "Debug Test" button is pressed?

We don't. Every test item you see in the test explorer there has a `pytest` generated id. When you click the debug button, we ask pytest to run the test with that ID equivalent to `pytest -k <testid>`. You can see the `pytest` generated id yourself by running `pytest --collect-only`.

**Comment by zljubisic** [comment]
@karthiknadig Let's conclude this discussion:
1. for sorting, you need pytest id
2. for sorting that is depicted on second picture from the very beginning you can't do anything
3. jumping to parameter is not possible, but you opened #19995 for that

So, everything will stay as it is right now.
If that is the true, please close this issue.

**Comment by karthiknadig** [comment]
@zljubisic In this https://github.com/microsoft/vscode/issues/163449#issuecomment-1276640202 I think there is some issue. The order that we want there is that one that pytest gives. Things should not get reordered unless you have selected a sort order in the UI. 

@connor4312 I think the sort order provided by the extension should be preserved. Is there something that is re-ordering these  items https://github.com/microsoft/vscode/issues/163449#issuecomment-1276640202

**Comment by zljubisic** [comment]
Thanks

**Comment by zljubisic** [comment]
Do you plan to do anything with this issue?

**Comment by connor4312** [comment]
PR's welcome 🙂

**Comment by karthiknadig** [comment]
Verified.

For this source:
![image](https://user-images.githubusercontent.com/3840081/221067124-ecf29bc1-9704-439c-bb85-3bacc2f4f429.png)

Previously:
![image](https://user-images.githubusercontent.com/3840081/221067175-6d847f2f-65ef-43ea-8626-bf7c28720af0.png)

After the fix (order is preserved):
![image](https://user-images.githubusercontent.com/3840081/221067232-bd7d6b55-fcac-453f-810a-077f4ce0ad1b.png)
