### ISSUE TITLE
Vscode overwrites theme to default Dark+

### ISSUE THREAD

**Issue by khushmeeet** [microsoft/vscode#163468]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.1 (Universal)
- OS Version: MacOS Monterey 12.6 Darwin arm64 21.6.0

Steps to Reproduce:
1. Open any project, vscode will open with `Dark+` theme
2. Go to settings, change `Workbench:Color Theme`  in `Userspace` to custom theme. It will automatically revert to `Dark+`.
3. Go to `Workbench:Color Theme`  in `Workspace` and change theme. Now it will change the theme permanently. But this has to be done for every workspace (for every new project opened in vscode)
![vscode bug](https://user-images.githubusercontent.com/8711912/195416941-44de607b-9558-469f-8704-e730ca6e5693.gif)

**Comment by aeschli** [comment]
The UI says that the setting is 'Also modified in Workspace'. That would explain why changing the setting has no impact.
You would have to make the change there.

**Comment by khushmeeet** [comment]
Changing in workspace would apply this change to only one project. I want this setting to be universal, so that whenever I open any file or folder, the theme stays the same.

**Comment by aeschli** [comment]
You have to remove the workspace setting then...

**Comment by khushmeeet** [comment]
How can I do that?

**Comment by aeschli** [comment]
One way to do it:
In your workspace, open `.vscode/settings.json` and remove the `workbench.colorTheme` settings.
This can also be done through the settings UI on the `workspace` tab.

**Comment by khushmeeet** [comment]
I tried this. I removed `workbench.colorTheme` from the `settings.json` file, but after that when I open a new project, theme is reverted to default `Default Dark+` and this line is added again `"workbench.colorTheme": "Default Dark+"`.

And theme won't change until I go to the `Workspace` section of the Settings and change it.

**Comment by aeschli** [comment]
`.vscode/settings.json` is a file in the project. Can it be that the new project you opened has `workbench.colorTheme` as well?

Do you have any extension installed that switch themes?

**Comment by rbarrimond** [comment]
I have the same problem. It appears that unless I force the theme for each project, VS Code will force _every workbench visible_ to Dark+. I've downloaded other themes. Set them to my defaults in User, Remote, and Workspace levels. This behavior continues. It's definitely a bug.

**Comment by khushmeeet** [comment]
Seems like now it is working for me. Don't know what changed. But nevertheless thanks for the help @aeschli
