### ISSUE TITLE
npm extension activates in web despite declaring `virtualWorkspaces: false`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#163480]
1. Open https://insiders.vscode.dev/github/microsoft/vscode and trust the workspace
2. Go to Show Running Extensions from the extensions pane
3. :bug: See that npm extension is activated even though it declares `virtualWorkspaces: false` in its package.json, which should disable it in all virtual workspaces

![image](https://user-images.githubusercontent.com/30305945/195452383-608b87bc-c534-495a-a5f2-52539f164375.png)

**Comment by sandy081** [comment]
Virtual workspace check is only considered in Desktop. In web all extensions those are web enabled are enabled irrespective of virtual workspace.

**Comment by joyceerhl** [comment]
> In web all extensions those are web enabled are enabled irrespective of virtual workspace.

Can I ask why this is the case? The npm extension activates eagerly due to `workspaceContains:package.json` when opening a repository containing a package.json file (e.g. extensions). I don't need this extension and today would need to manually disable it.

**Comment by sandy081** [comment]
Virtual workspace support is only for desktop clients. In web all workspaces are virtual.

CC @aeschli

**Comment by aeschli** [comment]
@sandy081 is right, and I agree it's a bit confusing.
The npm extension has a `browser` main entry point where it contributes code completions for and hovers for the `dependencies` in package.json. It uses online services for that, so it also works with virtual workspaces.
That said, it should not say `virtualWorkspaces: false` but instead just disable the functionality that doesn't work when in a virtual workspace.

**Comment by aeschli** [comment]
What do we want to change?
- that `virtualWorkspaces: false` is observed in the web
- that the npm extension does not declare `virtualWorkspaces: false` ?

**Comment by joyceerhl** [comment]
I would propose the following changes:
1. npm extension does not declare `virtualWorkspaces: false` 
2. Additionally, can we make the npm extension activate less eagerly i.e. not on `workspaceContains:package.json`? Today the npm extension activates whenever we open a VS Code extension repo for e.g., which seems unnecessary. Maybe we could instead activate when a package.json file is opened? (I don't believe we have an activation event for this but perhaps we could introduce one?)

**Comment by aeschli** [comment]
`workspaceContains:package.json` is currently needed to set the `npm:showScriptExplorer` context variable that is used to enable/disable the npm explorer. @alexr00

**Comment by alexr00** [comment]
I don't think we have a work around for the `npm:showScriptExplorer` context value, so we need to keep the activation as is. @meganrogge
