### ISSUE TITLE
Can't debug TypeScript/JavaScript VS Code extensions with Insiders

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#163563]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.73.0-insider (user setup)
Commit: a8108049ab61b970f2ec1839dfb753054e07395e
Date: 2022-10-13T05:19:31.002Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Open a TypeScript/JavaScript project that is configured to debug with the extensionHost. I'm using https://github.com/microsoft/vscode-cpptools .

Bug: There's no extensionHost TypeScript/JavaScript debugger available. It works with non-Insiders.

![image](https://user-images.githubusercontent.com/19859882/195635721-17c26ddd-5b61-49cc-b065-0554cf3e1e51.png)

Logging shows:

CRITI Extension 'vscode.typescript-language-features' wants API proposal 'workspaceEditIsRefactoring' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.

NOTE: If I install the C/C++ extension (which has its own debuggers), then trying to debug shows this error:
![image](https://user-images.githubusercontent.com/19859882/195638659-d847ef84-4dd3-427c-ba8d-aa7dcdb59954.png)

**Comment by connor4312** [comment]
You seem to have disabled the built-in JavaScript debugger. You can search `@builtin js-debug` in the marketplace view and re-enable it.
