### ISSUE TITLE
Intelligence will lead to repetition in Chinese

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#16353]
- VSCode Version: Code - Insiders 1.8.0-insider (be33bcdb2beb2d01c76ec8f830a70feaaa6721f5, 2016-12-01T09:47:03.630Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-color|anseki|0.2.2|
|output-colorizer|IBM|0.0.8|
|cpptools|ms-vscode|0.9.2|
|vscode-icons|robertohuertasm|4.0.4|
|vscode-hexdump|slevesque|1.1.4|

---

Steps to Reproduce:

1.  input part content such as I want to input '计数器', firstly. I input '计数'
2. input remaining and a punctuation.  input ‘器’ and ','
![12](https://cloud.githubusercontent.com/assets/8591065/20820722/423dab2a-b878-11e6-8f4b-e87fb62362c9.gif)

**Comment by rebornix** [comment]
Dup of #15765  and fixed by https://github.com/Microsoft/vscode/pull/16187 . @ZCShou you can see it's gone after upgrading to today's Insiders.
