### ISSUE TITLE
Feature request: Edit Logpoint... keyboard shortcut

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [microsoft/vscode#163528]
Hi!

I would like to request a keyboard shortcut for the Edit Logpoint... command which is displayed in a list when you right click a logpoint.
How it would work is that when you press the keyboard shortcut the logpoint on the cursor row is edited as if you right clicked it and chose Edit Logpoint...

**Comment by roblourens** [comment]
Basically needs a new command implementation that can function as a keybinding or from the command palette, the context menu is a one-off currently.

**Comment by MonadChains** [comment]
Hi @henrikvilhelmberglund and @roblourens.
I've opened a PR that adds to the command palette a command for editing breakpoints. Let me know if it is what you want.

**Comment by henrikvilhelmberglund** [comment]
First off thanks for the PR! Is it just for breakpoints though or logpoints too? I'm guessing I would need to build VS Code from source to actually test it so I would be happy if you could test it for me if it works like this.

1. In a code file right click left of the line numbers and do Add Logpoint... and type Hello.
2. Make sure the cursor (highlighted line) is the same as the logpoint diamond to the left.
3. Press the keyboard shortcut for the command you created in the PR.

Expected result is for the Log Message  Hello       widget to appear (as if you right clicked the logpoint to the left and did Edit Logpoint...). If it does it's perfect for me!

**Comment by MonadChains** [comment]
The command should work for every kind of breakpoint.
Here the result of the test that you suggested:
![ExampleLogpoint](https://user-images.githubusercontent.com/105170638/195986862-1c175a66-803c-4657-8d07-9a3add7cca27.gif)

**Comment by henrikvilhelmberglund** [comment]
> The command should work for every kind of breakpoint. Here the result of the test that you suggested: ![ExampleLogpoint](https://user-images.githubusercontent.com/105170638/195986862-1c175a66-803c-4657-8d07-9a3add7cca27.gif) [ ![ExampleLogpoint](https://user-images.githubusercontent.com/105170638/195986862-1c175a66-803c-4657-8d07-9a3add7cca27.gif) ](https://user-images.githubusercontent.com/105170638/195986862-1c175a66-803c-4657-8d07-9a3add7cca27.gif) [ ](https://user-images.githubusercontent.com/105170638/195986862-1c175a66-803c-4657-8d07-9a3add7cca27.gif)

Perfect, thanks a lot!
