### ISSUE TITLE
Element already has context attribute: pane

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#163525]
Reproduce:

1. restart vscode
2. close panel
3. open debug console panel

![image](https://user-images.githubusercontent.com/41773861/195535158-1b717072-07c4-4049-a6af-f044a4dae483.png)

versions:

```
Version: 1.73.0-insider (Universal)
Commit: a8108049ab61b970f2ec1839dfb753054e07395e
Date: 2022-10-13T05:19:29.769Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

https://user-images.githubusercontent.com/41773861/195534837-7ad5761a-661f-48a6-8758-c79a712693af.mov

**Comment by lramos15** [comment]
@mjbvz This looks like a regression from your listener change

**Comment by mjbvz** [comment]
@loganrosen Are you sure? It looks like the call stack is in the debug panel code: 

![Screen Shot 2022-10-13 at 7 49 11 AM](https://user-images.githubusercontent.com/12821956/195630353-623e39ad-ddc5-47d3-b18d-e165091d2c29.png)

**Comment by lramos15** [comment]
@mjbvz 🤦 , oh yes even the issue says it isn't related to revealing the explorer. I just saw the explorer and the word context and thought of your PR. Guess I need to not triage so early in the morning 😂
