### ISSUE TITLE
toogle terminal commando doesn't work with open files

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#16357]
- VSCode Version: 1.7.2
- OS Version: Xubuntu 16.04.1 LTS 64bits

Steps to Reproduce:

1. Open any file and focus it;
2. Press the default combination to toggle the terminal inside of vscode and watch it not work;

**Comment by chrmarti** [comment]
@mfgabriel92 What is the assigned key combination in your case? (We have some code that tries to resolve conflicts automatically.)

**Comment by Tyriar** [comment]
Do you mean ctrl+shift+c opening the external terminal? I made an extension that gives a command for this https://marketplace.visualstudio.com/items?itemName=Tyriar.vscode-terminal-here

**Comment by Tyriar** [comment]
Could you provide a screenshot, the associated error message and any errors in the console (Help > Toggle Developer Tools)?
