### ISSUE TITLE
Wrong bracket color matching using \left. and \right| in latex documents

### ISSUE THREAD

**Issue by longisland-icetea** [microsoft/vscode#163587]
Type: <b>Bug</b>

When Bracket Pair Colorization is enabled, write \\(\left. something \right|\\) in a tex file, \left. will be the right color but \right| will be red. And all the bracket pair's color in the below will change (to the color of the next level).

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (7.13GB free)|
|Process Argv|--crash-reporter-id 23d3b0b0-0e39-49ab-b085-a2822217435f --crash-reporter-id 23d3b0b0-0e39-49ab-b085-a2822217435f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.8
shell-format|fox|7.2.2
latex-count|geo|1.2.1
vscode-vibrancy-continued|ill|1.1.7
latex-workshop|Jam|8.29.0
better-cpp-syntax|jef|1.16.1
language-julia|jul|1.37.2
vscode-language-pack-zh-hans|MS-|1.72.10121008
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
LiveServer|rit|5.7.9
vscode-ltex|val|13.1.0
vscode-icons|vsc|11.20.0
wolfram|Wol|1.7.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by hediet** [comment]
Can you share a screenshot?

**Comment by longisland-icetea** [comment]
> 

![image](https://user-images.githubusercontent.com/20827609/196964579-12f7cbf0-0bae-4002-810a-ec0903e12fbe.png)

like this

**Comment by hediet** [comment]
Can you share the latex bracket pair config? This could be an extension issue.

**Comment by longisland-icetea** [comment]
I just used the default config. By the way, I just found a similar issue
https://github.com/microsoft/vscode/issues/137774#issue-1061945380

I will issue this to [LaTeX-Workshop](https://github.com/James-Yu/LaTeX-Workshop) latter.
