### ISSUE TITLE
Sticky scroll doesn't show class name / method name etc. when the opening brace of the scope is placed in a newline beneath

### ISSUE THREAD

**Issue by mshtang** [microsoft/vscode#163568]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.1 
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. open up a `.cs` file. The code format is set as "place braces in a separate line".
2. enable the sticky note feature in VS code and scroll the code.
3. only the opening brace of a scope is shown in the sticky area, the name of the scope is missing

before scrolling into the scope:
![image](https://user-images.githubusercontent.com/32868278/195650270-c22b60ec-5f9f-4d24-9007-0d7caf86fdf7.png)

after scrolling into the scope:
![image](https://user-images.githubusercontent.com/32868278/195650069-9d801b54-6fe8-4229-b756-98982c80d84e.png)

**Comment by jrieken** [comment]
please share source-code as text and never as image

**Comment by mshtang** [comment]
The pictures are just to intuitively showcase the problem. The “source code” itself is nothing fancy at all. Any two lines of code in the editor with an open brace placed in a new line should reveal the issue. But if the source code can be helpful in any way, just let me know please.
