### ISSUE TITLE
Incorrect syntax highlighting in `.properties` files

### ISSUE THREAD

**Issue by HymanZHAN** [microsoft/vscode#163508]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.1
- OS Version: Win10 21H2 (19044.2006)

Steps to Reproduce:

1. Create a `test.properties` file as follows:

```properties
var1 = hi
var2 = hello
var3 = he's doing well
var4 = she is my friend
var5 = she's also doing well
```
2. Open it in VS Code
3. Compare the highlighting result with Sublime and Vim

![image](https://user-images.githubusercontent.com/26806995/195485045-35c2701b-c0d2-4b37-980b-007e28654454.png)

Theme comparison (not the main issue here but just FYI):
![image](https://user-images.githubusercontent.com/26806995/195485424-8385dadc-2e32-4ff5-bea6-9106e6cdf604.png)
![image](https://user-images.githubusercontent.com/26806995/195485672-af184506-2868-4502-a70d-3cd88a69c62e.png)

Related Issue: https://github.com/microsoft/vscode/issues/124348

**Comment by alexr00** [comment]
Upstream issue is here: https://github.com/textmate/ini.tmbundle/issues/3

Since that repo is unmaintained we're looking for a new grammar: https://github.com/microsoft/vscode/issues/141632
