### ISSUE TITLE
Command-Period Break Shortcut Broken in 1.72

### ISSUE THREAD

**Issue by indiebloom** [microsoft/vscode#163595]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: OSX 12.6 (21G115)

Steps to Reproduce:

1. Open a terminal in VS Code
2. Press Command-Period
Expected: break (works fine in 1.71.2)
Actual: nothing happens

Also: Ctlr-c works find in both 1.72.2 and 1.71.2

**Comment by meganrogge** [comment]
Yep this is by design. See the work around here https://code.visualstudio.com/docs/terminal/basics#_how-can-i-configure-cmd-to-map-to-ctrlc-like-macos-builtin-terminal
