### ISSUE TITLE
please add go to function ctrl+b on phpstorm

### ISSUE THREAD

**Issue by parman** [Microsoft/vscode#16359]
- VSCode Version:
- OS Version:

Steps to Reproduce:

please add go to function ctrl+b on phpstorm

**Comment by mrmlnc** [comment]
See https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings

![image](https://cloud.githubusercontent.com/assets/7034281/20826260/af215726-b87a-11e6-9612-e8de8418d547.png)

Or use `keybindings.json` with:

```json
{
  "key": "ctrl+b",
  "mac": "cmd+b",
  "command": "editor.action.goToDeclaration",
  "when": "editorHasDefinitionProvider && editorTextFocus",
  "intellij": "Go to declaration"
}
```

**Comment by chrmarti** [comment]
We are working on the discoverability of keymaps for 1.8.
