### ISSUE TITLE
How do I make it so that emmet expands classNames in JSX and JS files using single quotes instead of double?

### ISSUE THREAD

**Issue by kvoth3** [Microsoft/vscode#16354]
- VSCode Version: 1.7.2
- OS Version: Win10

I've tried adding a custom syntaxprofile for jsx like so:

`"emmet.syntaxProfiles": {
        "jsx": {
            "attr_quotes": "single"
        }
   }`

This does not work. Emmet still expands classNames using double quotes.
Also, how to make using single quotes the default behavior for .js files and not just .jsx files?

**Comment by kvoth3** [comment]
I'm also not quite sure but I think I was able to do this in 1.7.0 but not with 1.7.1+

is this an issue or is it possible and there is just a setting that i'm missing?

**Comment by mjbvz** [comment]
As a workaround, you can use:

```
"emmet.syntaxProfiles": {
    "javascriptreact": "html",
    "html": {
        "attr_quotes": "single"
    }
}
```

As for the actual fix, I did a quick investigation. A few quick findings:

* I think that [`getSytnax`](https://github.com/Microsoft/vscode/blob/c67ef57cda90b5f28499646f7cc94e8dcc5b0586/src/vs/workbench/parts/emmet/node/editorAccessor.ts#L138) should alway return one of `html`, `xml`, or `xsl`.
* Also, we we call into emmet ([`runEmmetAction`](https://github.com/Microsoft/vscode/blob/6dd7a04bbd1e596336a30a11e8471698b63b6d42/src/vs/workbench/parts/emmet/node/emmetActions.ts#L191)) I think we need to explicitly pass the profile in at that point or pass the profile in by some other means.

**Comment by kvoth3** [comment]
Ah yes, I've tried that however it breaks "className" expansion for jsx and replaces it with just "class" as it should be for html.

`<div className="test"></div>`

becomes

`<div class='test'></div>`

**Comment by kvoth3** [comment]
Any update on this guys? Also, is this an issue or just a missing feature?

**Comment by ramya-rao-a** [comment]
@kvoth3 We will look into this more in the current iteration

**Comment by ramya-rao-a** [comment]
@kvoth3 For now, can you try the below ?
```
"emmet.syntaxProfiles": {
    "xml":{
        "attr_quotes": "single"
    }
}
```

`jsx` syntax uses the `xml` profile by default. (See https://github.com/emmetio/emmet/blob/master/lib/snippets.json#L988). Any changes made to the `xml` profile gets inherited by `jsx` files

@mrmlnc @sergeche http://docs.emmet.io/customization/syntax-profiles/#create-your-own-profile says that we can create our own profile. Meaning the below should work or have we misunderstood the docs?
```
"jsx": {
            "attr_quotes": "single"
        }
```

**Comment by ramya-rao-a** [comment]
cc @egamma

**Comment by ramya-rao-a** [comment]
Ah! I spoke too soon. The root cause seem to be that VS Code integration of emmet does not implement  the `getProfileName` method https://github.com/emmetio/emmet/blob/328812c879b56104b7c2bf580d79650a7c20f05b/lib/interfaces/IEmmetEditor.js#L119.

I'll keep digging

**Comment by kvoth3** [comment]
@ramya-rao-a Thanks that's a great workaround for now!

**Comment by ramya-rao-a** [comment]
@mrmlnc @sergeche I tried the same setting as below in `syntaxProfiles.json` for Sublime Text. Doesnt work there as well.
"jsx": {
            "attr_quotes": "single"
        }
```

Which brings me to conclude that creating your own profile for syntax other than "html" and "xml" doesn't work unless the editor implements the `getProfileName`

**Comment by sergeche** [comment]
@ramya-rao-a editor must properly detect profile name for current syntax. If it fails to do so (method not implemented, syntax is unknown etc.) it falls back to html profile

**Comment by sergeche** [comment]
@ramya-rao-a not that I’m working on a new Emmet implementation right now which will use different API and logic

**Comment by ramya-rao-a** [comment]
Thanks for confirming @sergeche!
