### ISSUE TITLE
Search Tree - uncollapsed nodes that are out of viewport can cause collapse action to fail

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#163599]
![2e05551ad3e8127416d02e885ac5333b](https://user-images.githubusercontent.com/31675041/205996047-5745a412-d617-4ebe-884e-1ae06ae2b56c.gif)

repro steps
1. make a search that has a compressed node outside of the viewport
2. try to keep collapsing
3. collapsing gets stuck when trying to collapse all.

**Comment by andreamah** [comment]
repro:
1. Add the `vscode-extension-samples` repo folder into a multi-root workspace (where another workspace also has the word "debug" somewhere in it).
2. Search for the string "debug"
3. Try clicking the Collapse All button a bunch of times
4. It gets stuck after a few times :bug:

This is because the tree needs info from the `renderCompressedElements` function, which hasn't been run yet since the "compressed" element is off of the view. Therefore, when I'm calling `navigator.next()`, I eventually get to the "compressed" element that doesn't have the info that I need.

**Comment by andreamah** [comment]
@joaomoreno What is the best way to collapse all nodes of a tree at a certain level? My current (buggy) strategy involves iterating through the nodes via `navigator.next()` and collapsing them based on element types, but that depends on knowing the parent-most node in a compression (which I store when I use `renderCompressedElements`).

https://github.com/microsoft/vscode/blob/0b610dc23138637dfcae914192f303b1d2bb705f/src/vs/workbench/contrib/search/browser/searchActionsTopBar.ts#L315-L331

**Comment by joaomoreno** [comment]
> This is because the tree needs info from the `renderCompressedElements` function, which hasn't been run yet since the "compressed" element is off of the view.

This is strange. Despite the elements never being rendered, the tree should know exactly which elements have been compressed. The `renderCompressedElements` function should never create any state that other code depends on... it's purely a rendering function.

At a glance the problem seems to be that you're modifying the tree (collapsing element) as you iterate it (using navigator). Can you refactor that action such that it first collects all elements which should be collapsed and then call `collapse` on each?

**Comment by andreamah** [comment]
Ah I see, I actually collect the info earlier in the code here:
https://github.com/microsoft/vscode/blob/0b610dc23138637dfcae914192f303b1d2bb705f/src/vs/workbench/contrib/search/browser/searchActionsTopBar.ts#L284-L302

Are all of the elements that get compressed still accessible in the tree after it's constructed?

**Comment by joaomoreno** [comment]
Unsure what you mean. Take this example:

![image](https://user-images.githubusercontent.com/22350/210370171-b81db591-6f15-473c-b800-3000b0cba22f.png)

Do you mean you want to collapse `two`? What should be the visual outcome of that?

**Comment by andreamah** [comment]
Yes, I'd be talking about collapsing `one` or `two`. Now that you mention it, it would be confusing to collapse partway like that. 

The reason I bring this up is because the "collapse/expand` button in search is multi-step in multi-root and tree modes. 
Ie: in multi-root, the collapse/expand would go:
1. click collapse button once: collapses all nodes one level below root
2. click collapse again: collapses all root nodes.
3. expands everything.
and repeat

How would you imagine that it should handle the first collapse if it's a compressed series of folders (ie: root/one/two/three/four.html)? I was originally thinking that it would just compress `one`, but that would have a weird visual outcome. Do you know anywhere else where we do something like this?

**Comment by joaomoreno** [comment]
> How would you imagine that it should handle the first collapse if it's a compressed series of folders (ie: root/one/two/three/four.html)?

I would expect the `one\two\three` node would be collapsed in that case.

> click collapse button once: collapses all nodes one level below root

The key here ☝️ is _nodes_, not _folders_. The `one\two\three` node represents three folders.
