### ISSUE TITLE
Hello! Regarding the code highlighting, it is never possible to modify the foreground color, and the foreground color of the code that needs to be modified, I have marked it in detail using the red box with numbers....

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode#163503]
Type: <b>Bug</b>

Hello! Regarding the code highlighting, it is never possible to modify the foreground color, and the foreground color of the code that needs to be modified, I have marked it in detail using the red box with numbers, please see the following image.
![2022-10-13_font-color](https://user-images.githubusercontent.com/54253524/195476447-9961d387-b1fa-4ea2-96e7-8b7848feedbe.png)

It would be great if you could tell me where I can customize the foreground color so that it can match the editor theme color better and look more reasonable. Hope I can get your help! Thanks a lot! 😜

您好！關於代碼高亮，始終無法修改前景色，需要修改的代碼前景色，我已經使用紅色方框加數字進行了詳細的標註，請看下圖：
![2022-10-13_font-color](https://user-images.githubusercontent.com/54253524/195476447-9961d387-b1fa-4ea2-96e7-8b7848feedbe.png)
如果您能告訴我在什麼地方可以自定義前景色使其能與編輯器主題顏色更加匹配，看上去更加合理，那將會是一個很好的事情。希望能夠得到您的幫助！非常感謝！😜

VS Code version: Code 1.72.1
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by zhouxinghong** [comment]
Yesterday we found out that a[ torrents version of VSCode](https://www.jetbrains.com/zh-cn/fleet/) has been released, from then on VSCode has another competitor, so VSCode must cheer up and try to do better than it, better than it Oh!👍

昨天發現[山寨版VSCode](https://www.jetbrains.com/zh-cn/fleet/)已經發布了，從此VSCode又多了一個競爭對手，所以VSCode一定要加油，爭取做的比它更好，更優秀哦！👍

**Comment by aeschli** [comment]
Here's how this works:
- Put the cursor at the location of the symbol to inspect, and use the `Inspect Editor Tokens and Scopes` command.
In the hover you see textmate scope is active at that location. 
- Based on that, you can customise your theme as shown in https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting.
- Potentially there's also a semantic token active. In that case you can customise it as described in https://code.visualstudio.com/docs/getstarted/themes#_editor-semantic-highlighting

If you want a specific theme to be improved, file a request against the theme author.
If there's no textmate scope available for the symbol you are looking at, file a request against extension that providers the syntax grammar

I hope that answers your question.

**Comment by zhouxinghong** [comment]
Thank you very much for your help!👍👍👍😜
