### ISSUE TITLE
I wish I could have multiple folder panels for the same folder

### ISSUE THREAD

**Issue by techsin** [microsoft/vscode#163561]
When the codebase is large, you have to scroll up and down to see code in different folders. This is especially true when you haven't found all the files and you can't pin them. It'd be really useful if i could open multiple explorer/folder panels stacked vertically.

![temp123](https://user-images.githubusercontent.com/4664695/195634298-8626b641-b1cb-4142-bb0e-f25826acafb1.png)

If not this then maybe able to pin folders so a shortcut appears and you can quickly jump to certain folders in tree view just by clicking a name of folder pinned on top somewhere

**Comment by lramos15** [comment]
This unlikely to be something we implement. Multi-root workspaces may help you further breakdown complex folder structures.
