### ISSUE TITLE
Enable Tunnel Access from within VS Code

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#163526]
- [x] Add command to run the code server on your machine
- [x] Allow to configure machine name for tunnel
- [x] Copy to clipboard action with vscode.dev URL
- [ ] ~Render status bar item when a tunnel connection is established to current machine~

**Comment by connor4312** [comment]
Marking this as closed to clear out the inbox. If there's more work here, let's make a new issue for next iteration.
