### ISSUE TITLE
Command Terminal immediately closes once opened

### ISSUE THREAD

**Issue by PhinJ** [microsoft/vscode#163556]
Type: <b>Bug</b>

Whenever I try to open a terminal in Visual Studio Code, the terminal tab immediately closes.

VS Code version: Code 1.72.1 (Universal) (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:25:13.482Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.57GB free)|
|Process Argv|--crash-reporter-id 47652786-ade6-44b9-97b0-71eb893a1c7a --crash-reporter-id 47652786-ade6-44b9-97b0-71eb893a1c7a|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
JavaScriptSnippetsStandard|jms|1.8.0
vscode-standard|sta|2.1.2
code-spell-checker|str|2.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848cf:30577861
nodejswelcome1:30583747
fc301958:30573243

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by anastasiyamazheika** [comment]
Hello, I see the same issue on the new version of VS Code.

Version: 1.72.1 (Universal)
Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
Date: 2022-10-10T17:25:13.482Z (3 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 20.6.0
Sandboxed: No

**Comment by PhinJ** [comment]
I was able to restart my computer and the app and it resolved the issue. Apologies for the inconvenience.

**Comment by meganrogge** [comment]
Lmk if you can repro in insiders
