### ISSUE TITLE
Deletion of many selected files in explorer is slow

### ISSUE THREAD

**Issue by programmer04** [microsoft/vscode#163530]
Does this issue occur when all extensions are disabled?: _Yes_

- VS Code Version: 
   ```
   Version: 1.72.1
   Commit: 129500ee4c8ab7263461ffe327268ba56b9f210d
   Date: 2022-10-10T17:25:13.482Z
   Electron: 19.0.17
   Chromium: 102.0.5005.167
   Node.js: 16.14.2
   V8: 10.2.154.15-electron.0
   OS: Darwin x64 21.6.0
   Sandboxed: No
   ```
- OS Version: _macOS 12.6_

Steps to Reproduce:

1. Select many files in the explorer and delete them
![delete-test](https://user-images.githubusercontent.com/9593424/195551429-01986ed1-9e88-4700-818f-8c9381d8c2a8.gif)
2. Observe how slow it is (it doesn't matter if the directory is a git repo or not)

Removing an entire directory with many files in explorer does not have any performance penalty. Removing the same set of files with a terminal and command `rm` is instantaneous too.

**Comment by lramos15** [comment]
Merging with https://github.com/microsoft/vscode/issues/165271
