### ISSUE TITLE
Remove kernel preloads globals API

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#163513]
Kernel preloads can currently be loaded two ways:

- As a module that exports an `activate` function. We invoke this function with the notebook API
- As a global script. In this case, we inject the notebook API as global variables

I would like to remove the second approach as it is not something we want to finalize. For now we can still allow global scripts, but they should not have access to the VS Code apis such as `acquireVsCodeApi`

@DonJayamanne @rebornix Can you please check to see if the jupyter preloads use the global versions of any of the following API:

- `acquireVsCodeApi`
- `onDidReceiveKernelMessage`
- `postKernelMessage`

If you are using these, is it possible to switch to use module based preloads instead? If you cannot, what are the blockers?

**Comment by DonJayamanne** [comment]
@mjbvz I've made the changes in Jupyter, will remote the corresponding VS code changes and test this out later today/tomorrow.

**Comment by DonJayamanne** [comment]
@mjbvz 
Isn't the following code also meant to be removed?
src/vs/workbench/contrib/notebook/browser/view/renderers/webviewPreloads.ts

If so, then this issue has not been completed and I've missed some other parts.

```typescript
	async function activateModuleKernelPreload(url: string) {
		const module: KernelPreloadModule = await __import(url);
		if (!module.activate) {
			console.error(`Notebook preload '${url}' was expected to be a module but it does not export an 'activate' function`);
			return;
		}
		return module.activate(createKernelContext());
	}
```

**Comment by mjbvz** [comment]
@DonJayamanne We can remove that once the stable version of Jupyter is also using modules. Has that release switched over or do we need to wait?

**Comment by DonJayamanne** [comment]
> Has that release switched over or do we need to wait?

Not yet, I missed one bit and here's the corresponding PR https://github.com/microsoft/vscode-jupyter-ipywidgets/pull/16

**Comment by DonJayamanne** [comment]
This should now be fixed.
