### ISSUE TITLE
Signature Help highlighting function name instead of parameter

### ISSUE THREAD

**Issue by dbanck** [microsoft/vscode#163534]
The bug in signature help occurs when a function has the same name as a parameter. In our case, the function `format` has two parameters, `format` and `args`. Instead of highlighting the first parameter, VS Code highlights the function name.

<img width="271" alt="CleanShot 2022-10-13 at 11 43 02@2x" src="https://user-images.githubusercontent.com/45985/195563108-8c79611d-2dc9-4b92-afc1-80f8a82dd69d.png">

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0-insider
- Commit: a8108049ab61b970f2ec1839dfb753054e07395e
- Date: 2022-10-13T05:19:29.769Z
- Electron: 19.0.17
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Darwin x64 20.6.0
- Sandboxed: Yes

Steps to Reproduce:

1. Create a `package.json`
```json
{
  "name": "signature-bug",
  "publisher": "Daniel",
  "version": "1.0.0",
  "engines": {
    "vscode": "^1.70.0"
  },
  "activationEvents": [
    "*"
  ],
  "main": "./index.js"
}
```
2. Create a `index.js`
```js
const vscode = require("vscode");

exports.activate = function () {
  console.log(`I am running!`);
  vscode.languages.registerSignatureHelpProvider(
    "*",
    {
      provideSignatureHelp: (doc, pos) => {
        console.log(`providing signature help`);
        const value = new vscode.SignatureHelp();
        value.signatures = [
          {
            label: "format(format, args)",
            parameters: [
              {
                label: "format",
                documentation: "param 1",
              },
              {
                label: "args",
                documentation: "param 2",
              },
            ],
          },
        ];
        value.activeSignature = 0;
        value.activeParameter = 1;
        return value;
      },
    },
    "(",
    ","
  );
};
```
3. Run the extension development process
4. type `format(` into any buffer/file

I would be happy to take a look at this and submit a PR if you like.

**Comment by mjbvz** [comment]
You should use the offset version of the `label`: https://github.com/microsoft/vscode/blob/182beb6ee4bbed13deabce7ca29f52a30a31824a/src/vscode-dts/vscode.d.ts#L4156

This lets you specify the start and end of the parameter name in the signature help. Otherwise we have to guess where the parameter is based on its index in parameter hint label, which can fail as you are seeing
