### ISSUE TITLE
can i execute cmd in vscode 

### ISSUE THREAD

**Issue by dyh333** [Microsoft/vscode#16358]
my os is windows 10. and i want to execute cmd in vscode, such as 'npm install', or something else. is any plugin can do it?

**Comment by kaiwood** [comment]
The is an extension for npm commands [here](https://marketplace.visualstudio.com/items?itemName=fknop.vscode-npm), but for everything that has to to with the command line in general, there is a pretty good built in terminal. Instructions can be found here: https://code.visualstudio.com/docs/editor/integrated-terminal

**Comment by dyh333** [comment]
@kaiwood thanks.
