### ISSUE TITLE
Text editor background for sticky scroll header in peek view does not have peek view background color tokens

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#163694]
1. Have sticky scroll on 
2. Open peek view e.g. via Find All Implementations
3. :bug: sticky scroll header inside peek view doesn't have the peek view background color

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/30305945/195931581-ceda830e-18bb-4812-b341-dc33c16516ab.png">

**Comment by jrieken** [comment]
fixed https://github.com/microsoft/vscode/pull/168315#pullrequestreview-1208602289
