### ISSUE TITLE
VS Code Insiders redirects to browser after clicking Download Update (1) button

### ISSUE THREAD

**Issue by hamad12a** [microsoft/vscode#163657]
What I tried before asking.
I removed VS Code insiders then downloaded `sudo apt-get install apt-transport-https`
then `sudo apt-get update; sudo apt update; sudo apt-get upgrade`. After that, I installed VS C Insiders from terminal `sudo apt -y install code-insiders`

Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: Insiders latest update
- OS Version: POP OS latest update

Steps to Reproduce:

1. Click on Manage gear
2. Click Download Update (1)

**Comment by joaomoreno** [comment]
That's how the update notification works in deb/rpm. There's no automatic in product updating mechanism on those distribution packages, since the OS takes care of that for you.
