### ISSUE TITLE
Unit test failures: Async#retry

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#163619]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=189155&view=logs&j=a5d99aad-4929-5289-bf4a-26b78032353d&t=c61a688d-0a79-5b1f-223b-9376911e515d

**Comment by bpasero** [comment]
There is a bunch of other test failures (see https://github.com/microsoft/vscode/issues/165278 and https://github.com/microsoft/vscode/issues/162102) that only occur on macOS and only in web tests, though both in Chromium and Webkit. The symptoms are always the same: a seemingly random test times out that works fine in electron tests.

I can only speculate that this is an issue with `setTimeout` not firing so here in this case I can attempt to fix it with `runWithFakedTimers` but thats not really bringing us closer to understanding why this actually happens...
