### ISSUE TITLE
How to show button fold code (-) and (+) by default?

### ISSUE THREAD

**Issue by ttn10** [Microsoft/vscode#16369]
Hi, please check this image :)
http://i.imgur.com/AeAPvv3.png

**Comment by chrmarti** [comment]
Not sure what the question is, please clarify. You can enable/disable folding with the `"editor.folding"` setting.

**Comment by mrmlnc** [comment]
@chrmarti, I think that @ttn10 has in mind: show `[-]` and `[+]` buttons always without mouse Hover.

**Comment by ttn10** [comment]
Yes, i want to always  show `[-]`, current `[-]` show only via hover
default, `[+]` always show when user click to `[-]`

**Comment by alexandrudima** [comment]
fyi @aeschli

**Comment by aeschli** [comment]
duplicate of #3911
