### ISSUE TITLE
cursor auto move newline when i typing @ in file .blade.php

### ISSUE THREAD

**Issue by huyprowow** [microsoft/vscode#163653]
Type: <b>Bug</b>

typing @

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.77GB (4.28GB free)|
|Process Argv|. --crash-reporter-id 1a0422bf-f093-47eb-9820-32b46b18e9a7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (72)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
color-info|bie|0.7.0
vscode-intelephense-client|bme|1.8.2
simple-react-snippets|bur|1.2.7
turbo-console-log|Cha|2.5.1
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
glsl-canvas|cir|0.2.15
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|12.2.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.9.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
copilot|Git|1.53.7011
vscode-pull-request-github|Git|0.50.0
live-sass|gle|5.5.1
vscode-graphql|Gra|0.7.12
vscode-graphql-execution|Gra|0.1.5
vscode-graphql-syntax|Gra|1.0.4
beautify|Hoo|1.5.0
rest-client|hum|0.25.1
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
mongodb-vscode|mon|0.9.3
vscode-docker|ms-|1.22.1
vscode-kubernetes-tools|ms-|1.3.10
remote-containers|ms-|0.255.3
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
hexeditor|ms-|1.9.9
vsliveshare|ms-|1.0.5735
vsliveshare-audio|ms-|0.1.91
vscode-react-native|msj|1.9.3
sqltools|mtx|0.25.1
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.21.0
vscode-css-peek|pra|4.2.0
webgl-glsl-editor|rac|1.3.3
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
glassit|s-n|0.2.4
background|sha|1.2.1
code-settings-sync|Sha|3.4.3
markdown-preview-enhanced|shd|0.6.3
shader|sle|1.1.5
autoimport|ste|1.5.4
code-spell-checker|str|2.10.1
sass-indented|syl|1.8.22
bootstrap4-vscode|the|6.1.0
altitude-script-language|uca|0.0.3
doki-theme|unt|88.1.9
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28
vscode-icons|vsc|11.20.0
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.4.3
bootstrap-v4-snippets|Zac|1.1.3
material-theme|zhu|3.15.6
html-css-class-completion|Zig|1.20.0

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by huyprowow** [comment]
cursor auto move newline when i typing @ in file .blade.php

**Comment by roblourens** [comment]
This is probably from some extension, you can try running the "Start Extension Bisect" command to figure out which one it is.
