### ISSUE TITLE
No Folding Toggle When Nested 10+ Levels

### ISSUE THREAD

**Issue by bhaynes777** [microsoft/vscode#163671]
The folding toggle is not displayed for blocks that are nested 10 or more levels deep.  A file that reproduces the issue is attached.

Folding toggles appear for all of the describe blocks in the example file except "test group 10" and "test group 10B", which are nested 10 levels deep.  I would like to see folding toggles on blocks regardless of depth.
[test.txt](https://github.com/microsoft/vscode/files/9788721/test.txt)

VS Code version: 1.72.2
OS: Windows 8.1 (Windows_NT x64 6.3.9600)
Reproducible with all extensions disabled

**Comment by aeschli** [comment]
We have a limit of 5000 folding regions per file for performance reasons.
You can change that with the setting `editor.foldingMaximumRegions`

**Comment by bhaynes777** [comment]
@aeschli did you look at the example file?  It would have a total of 13 folding regions if deeply-nested ones worked.

**Comment by aeschli** [comment]
Oh, sorry, I didn't.
That's with TytpeScript/JavaScript? Looks loke the TypeScript language service has such a limit.
To test:
```
describe('test group', () => {
  describe('test group 2', () => {
    describe('test group 3', () => {
      describe('test group 3', () => {
        describe('test group 4', () => {
          describe('test group 5', () => {
            describe('test group 6', () => {
              describe('test group 7', () => {
                describe('test group 8', () => {
                  describe('test group 9', () => {
                    describe('test group 10', () => {
                      describe('test group 11', () => {
                        console.log()
                      });
                    });
                  });

                  describe('test group 9B', () => {
                    describe('test group 10B', () => {
                      describe('test group 11B', () => {
                        console.log()
                      });
                    });
                  });
                });
              });
            });
          });
        });
      });
    });
  });
});
```

Open as txt file: You see indent based folding range for all `describe` sections
Open as TypeScript file: No folding for `test group 10` and inner.

**Comment by bhaynes777** [comment]
@aeschli should this issue still be closed?  It looks like you were able to reproduce the issue.

**Comment by aeschli** [comment]
Oh sorry, it should be moved to the TypeScript repo.
