### ISSUE TITLE
remote debugger

### ISSUE THREAD

**Issue by SGFGOV** [microsoft/vscode#163614]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: amazon linux

Steps to Reproduce:

1. create npm with typescript on remote system
2. start the application with a break point. the Program doesn't halt at the breakpoint

**Comment by roblourens** [comment]
Please give just more details about exactly what you are doing, include the log

/jsDebugLogs

**Comment by roblourens** [comment]
I guess the bot is asleep, I'll post the steps manually

Please collect trace logs using the following instructions:

> If you're able to, add `"trace": true` to your `launch.json` and reproduce the issue. The location of the log file on your disk will be written to the Debug Console. Share that with us.
>
> ⚠️ This log file will not contain source code, but will contain file paths. You can drop it into https://microsoft.github.io/vscode-pwa-analyzer/index.html to see what it contains. If you'd rather not share the log publicly, you can email it to connor@xbox.com

**Comment by SGFGOV** [comment]
I think the issue was with my configuration file, sorry for the bother.
