### ISSUE TITLE
Next/Prev keyboard nav in Quick Open

### ISSUE THREAD

**Issue by eckdanny** [Microsoft/vscode#16362]
- VSCode Version: `1.7.2` 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
- OS Version: OSX 10.10.5 (14F2009)

next/prev keyboard nav in `quickOpen` inconsistent with other "inline prompt list" paradigms (e.g.; IntelliSense). Can this be resolved by user config or made default behavior? I'm not seeing a collision w/ existing commands.

### Steps to Reproduce:

![vscode](https://cloud.githubusercontent.com/assets/3521444/20825962/4bbac8d6-b82d-11e6-9268-26a8d467477a.gif)

**Comment by kaiwood** [comment]
Hmmm, good spot… You can bind the following to `ctrl+p` / `ctrl+n`:

	{
		"key": "ctrl+n",
		"command": "workbench.action.quickOpenNavigateNext",
		"when": "inQuickOpen"
	},
	{
		"key": "ctrl+p",
		"command": "workbench.action.quickOpenNavigatePrevious",
		"when": "inQuickOpen"
	}

But careful, those 2 commands behave not exactly the same as when you simply use up-arrow / down-arrow. They open/execute whatever is selected as soon as you lift your finger from the modifier key (try `ctrl+tab` / `ctrl+shift+tab` for reference).

A "real" up/down to bind and with those keys as default would be nice to have, so 👍 for the feature request.

**Comment by eckdanny** [comment]
Awesome! I hate having to reach for arrow keys almost as much as reaching for mouse. ^ exactly what I was looking for. Thanks!

**Comment by eckdanny** [comment]
Is very subtle the diff b/n "real" up/down and using the bindings you shared. Holding modifier key and dancing around w/ `n` and `p` feels _more_ natural to me (and saves me an `enter` keypress, _yay!_)

But the original reason i raised issue was for consistency (e.g.; with IntelliSense). For that reason, @kaiwood's argument for "real" up/down bindings & defaults is a good one.

Not closing in case maintainers wish to apply `feature-request` label.

**Comment by jpokrzyk** [comment]
This is probably obvious but would also love to see crtl+p and crtl+n implemented in the command palette as well. Thanks.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/7876
