### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by lanlianjiu** [Microsoft/vscode#16360]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1.
2.

**Comment by mjbvz** [comment]
Title translated to: "Garbled"

Closing as not actionable.

Please provide information about the issue you are seeing, as well as screenshots showing what is going wrong. 

Thanks.
