### ISSUE TITLE
Unable to rename component folder

### ISSUE THREAD

**Issue by azzurolilc** [microsoft/vscode#163707]
Type: <b>Bug</b>

Folder copied from other component, trying to rename, getting
Error: EPERM operation not permitted.

VS Code version: Code - Insiders 1.73.0-insider (7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c, 2022-10-14T05:17:07.227Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (11.83GB free)|
|Process Argv|--crash-reporter-id 086c9fdc-6ee9-40de-948d-cf1e53d2d5fb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
markdown-mermaid|bie|1.15.2
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
gitlens|eam|12.2.2
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.9.0
vscode-jest-runner|fir|0.4.59
graphql-for-vscode|kum|1.15.3
remote-containers|ms-|0.259.0
azurecli|ms-|0.5.0
vs-code-prettier-eslint|rve|5.0.4
markdown-preview-enhanced|shd|0.6.3
teams-dyson|tea|0.0.2022080301
alphabetical-sorter|ue|2.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30568093
pyind367cf:30587848
vsccc:30564266
pyindex848:30577858
nodejswelcome1:30587009

```

</details>

**Comment by lramos15** [comment]
This has to do with your file system permissions and not with VS Code. If you try to do it from the windows explorer you will see it fails as well.
