### ISSUE TITLE
Move the `NotebookController.kind` property from proposed to released

### ISSUE THREAD

**Issue by davidanthoff** [microsoft/vscode#163777]
The Julia extension can easily add a large number of notebook controllers to the UI, and when the Jupyter extension _also_ adds Julia kernels to the list, it all gets very chaotic. The Jupyter extension can nicely group its entries via the `NotebookController.kind` property, but that is only proposed and so we can't use it from the Julia extension.

Given that it has been proposed for almost a year, is being used by MS extensions and generally seems useful, could this be made regular so that the Julia extension can also use it? :)

**Comment by DonJayamanne** [comment]
For those interested here's the plan for process for promoting proposed API to stable https://github.com/microsoft/vscode/wiki/Extension-API-process
I'll work on this next week, as this week is end game

**Comment by davidanthoff** [comment]
Great, thanks!

**Comment by DonJayamanne** [comment]
@davidanthoff Sorry we didn't get to this in the previous iteration.
A lot of work was done in the kernel picker area and we weren't certain this `kind` property would still be used.
Now that we have a better idea (after the changes to the kernel picker) I think we can move with finalizging this API.
