### ISSUE TITLE
vscode Have you started charging? 

### ISSUE THREAD

**Issue by xiangxingze** [microsoft/vscode#163798]
Some netizens need to scan the code to install vscode, I hope the official can stop this behavior 
![21276c6919c82457dcedd5587c5edc0](https://user-images.githubusercontent.com/13271663/196067460-dd5c6606-3ccc-4a04-a555-9d2f8add0636.jpg)
![07e482785c0bdd0986b798bbc86e7aa](https://user-images.githubusercontent.com/13271663/196067464-8323e6f6-5e56-4407-b629-965427faf557.jpg)
![5bcc8c2dbb4d94d26fd7b41448b0d63](https://user-images.githubusercontent.com/13271663/196067467-56f07382-364c-4c72-a92c-d6faed02d97f.jpg)

**Comment by YidaozhanYa** [comment]
This is piracy and goes against the open source license ...

**Comment by Reviona** [comment]
Extremely interesting

**Comment by Huaxidesu** [comment]
Need ￥39 to install? Selling free software?

**Comment by TooYoungTooSimp** [comment]
How can you find this...  Is just typing code.visualstudio.com too difficult for some people?

**Comment by 19337361167** [comment]
hilarlious

**Comment by shirok1** [comment]
Fun fact: MIT License allows you to "sell copies of the Software" with or without modification.

**Comment by Reviona** [comment]
> How can you find this...  Is just typing code.visualstudio.com too difficult for some people?

In some countries, there is Internet interdict like Great Fire Wall in China. So people there cannot reach the servers of Microsoft.

**Comment by Chaoses-Ib** [comment]
Search from Baidu:

![image](https://user-images.githubusercontent.com/50246090/196424828-5ead4681-c783-442e-bbea-0b8e4c15fcc2.png)

The first one is https://qnw.shaid.top/vscode/index.html:

![image](https://user-images.githubusercontent.com/50246090/196424988-4523e2d7-4860-4631-876f-bfd4a2548359.png)

This website belongs to Wuhan Hongge Yibai E-commerce Co. (武汉宏格亿佰电子商务有限公司).

If you do some searches on this domain, you can find their other "products":
- [Win10 Activation Tool (Win10 激活工具)](https://qnw.shaid.top/win10/index.html)
- Telegram Chinese version (Telegram 中文版) (deleted)

  ![image](https://user-images.githubusercontent.com/50246090/196426820-f9fa3030-eb5e-430c-bdfc-026af7100576.png)

They even claim to be partners with China Mobile, China Unicom and China Telecom:
[![image](https://user-images.githubusercontent.com/50246090/196426325-f39cc8ab-8b66-40b7-8a1e-edc32ad7c08b.png)](http://www.shaid.top/)

Thanks to the Great Firewall, we have such a "great" Internet in China.

**Comment by AXFOX** [comment]
It's Chinese internet shame!

**Comment by huige233** [comment]
In fact, not only vscode, but also tools like dev-c++are used by the company for profit

**Comment by lss233** [comment]
> How can you find this... Is just typing code.visualstudio.com too difficult for some people?

Yes, IT IS difficult for some people who just know vscode or just get started learning coding.

What makes this thing more hilarlious is that,
If you search `vscode` or `visual code` on Bing China, you will get a piracy link on the first search result.
![image](https://user-images.githubusercontent.com/8984680/196569964-6d9d19ab-cfb6-4eba-95c9-a792249cc511.png)
![image](https://user-images.githubusercontent.com/8984680/196569990-a81a1105-fbde-4cf0-a667-d0716cde20c6.png)

**Comment by KasumiNova** [comment]
Interesting...

**Comment by SasebonoShigure** [comment]
Hilarious indeed, thanks to GFW.

**Comment by MCUmbrella** [comment]
樂

**Comment by bainesing** [comment]
樂

**Comment by ZeroAurora** [comment]
> Fun fact: MIT License allows you to "sell copies of the Software" with or without modification.

Not really true. The official version of Visual Studio Code contains the trademark and some modifications by Microsoft, and is therefore subjected to [Microsoft's terms](https://code.visualstudio.com/License/). The pirate version definetely goes against the terms and must be taken down.

**Comment by eternitymoe** [comment]
![image](https://user-images.githubusercontent.com/44344308/196600225-6a2c3bb0-4f94-4c0a-a595-51c48d90d123.png)
"Officially licensed": https://www.google.com
lol

**Comment by Huaxidesu** [comment]
> ![image](https://user-images.githubusercontent.com/44344308/196600820-ca8d3cbc-3c07-4bb1-b49d-dbb642854a02.png) VS Code "Officially licensed": https://www.google.com lol

典中典

**Comment by wqreytuk** [comment]
Do you know why there is a GFW in China? cause CCP sucks, these SOBs are afraid of their people knowning or telling the truth, all words published on China's social media/platform are reviewed strictly, anything CCP doesn't like will be banned, and on the other side, they claim that there is something called FREE-SPEECH is existed in China, so F*CK them

**Comment by klren0312** [comment]
you will be gave red code

**Comment by klren0312** [comment]
The necessary process of localization in China

**Comment by LaoLittle** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈

**Comment by kenvix** [comment]
典

**Comment by zhaoaaaaa5** [comment]
乐

**Comment by NWYLZW** [comment]
> ![image](https://user-images.githubusercontent.com/44344308/196600820-ca8d3cbc-3c07-4bb1-b49d-dbb642854a02.png) VS Code "Officially licensed": https://www.google.com lol

入典！！！
https://meme-libs.github.io/github/2

**Comment by karuboniru** [comment]
It's hard for me to tell if you are joking...

**Comment by karuboniru** [comment]
> Fun fact: MIT License allows you to "sell copies of the Software" with or without modification.

Thanks for the TIP, I am going to sell VS Code at $114514/copy.

**Comment by JackABlack** [comment]
mark LOL nice joke during work

**Comment by Cisku** [comment]
会上github发issue不会google一下官网是吧

**Comment by KangKang0928** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jordanmaxis** [comment]
extremly hilarious🤣🤣🤣🤣

**Comment by halodoom** [comment]
难崩，程序员版steam管家是吧

**Comment by Huaxidesu** [comment]
（vsc微软管家

**Comment by ii64** [comment]
笑死233

**Comment by Kiprey** [comment]
这该不会是钓鱼吧 hh

**Comment by randomtc** [comment]
In China, it is normal
![GZB}9_~W30KO1P_QO0IIBV0](https://user-images.githubusercontent.com/104550011/196629946-8e48742c-5527-4d9c-bd9c-117f52dc095a.jpg)

**Comment by NTLoner** [comment]
离大谱……

**Comment by StevenTang1994** [comment]
![image](https://user-images.githubusercontent.com/24404599/196631293-46c94e05-8281-409d-9cd3-cb79e72fec85.png)
Authorize to write to Google?

**Comment by Zzzode** [comment]
LOL😂

**Comment by XiaoPangxie732** [comment]
樂

**Comment by DarrenDanielDay** [comment]
If these vendors misappropriate the `Visual Studio code` trademark, I hope Microsoft sues them for copyright infringement.

**Comment by jw-foss** [comment]
If you do not wish to use the VSCode under M$, you may turn to VS Codium.

**Comment by galaxynova1999** [comment]
Developers who can't even find the official website should change careers ASAP

**Comment by zengwmFE** [comment]
LOL

**Comment by az-pasa** [comment]
LOL

**Comment by Williamren97** [comment]
crazy

**Comment by shirokaedechiya** [comment]
难绷，vscode管家是吧

**Comment by kooriookami** [comment]
F**k Baidu

**Comment by kooriookami** [comment]
F**k Baidu

**Comment by Vercharon** [comment]
VSCode need instant actions to avoid being authorized to Google. 😂

**Comment by emojiiii** [comment]
die laughing

**Comment by DragonCat1** [comment]
彳亍，牛的

**Comment by hundunzhidian** [comment]
u can alos see Steam downcenter、 manager....

**Comment by KaneGreen** [comment]
I tried to translate the Chinese characters in these three pictures into English to make it easier for more readers to understand what happened.

![1](https://user-images.githubusercontent.com/20700283/196642847-1805b401-c91d-45b8-bbca-a3993bbc81f5.jpg)
![2](https://user-images.githubusercontent.com/20700283/196642873-ab54bae8-302e-49f0-97b4-1bbf639a179f.jpg)
![3](https://user-images.githubusercontent.com/20700283/196642892-3ffa3992-15aa-4888-8c93-2526a6eb2116.jpg)

**Comment by 2659170494** [comment]
难绷😂😂😂

**Comment by sadwd12312** [comment]
a lot of fun🤣

**Comment by uf-hy** [comment]
XDDDDDDDDDDDDDD

**Comment by LucienShui** [comment]
baidu makes great firewall great again.

**Comment by weimeng23** [comment]
真·程序员版steam
real steam for programmer

**Comment by suda-code** [comment]
lol, why does this VSCode search and install on Baidu? Well, I admit that for those who are new to programming, they really don't know where to download it, but shouldn't the official website of VSCode be an English interface? Novice should be able to distinguish this.

**Comment by Chaoses-Ib** [comment]
More funny screenshots:

![image](https://user-images.githubusercontent.com/50246090/196645235-7f858aa9-5bda-4591-80bd-f23b93e6a9da.png)

![image](https://user-images.githubusercontent.com/50246090/196647834-e9e91993-a1cc-425b-985d-39c8cdaa95d7.png)

The original price is ￥69.7, but you will get a "￥20" (￥30 in fact) coupon when you close the window. Also, if you turn off the internet, it goes to ￥29.95. my guess is they did an online price increase because of the brisk sales. 🔥 

![image](https://user-images.githubusercontent.com/50246090/196646493-fdce2d63-c193-4161-8f18-c7ac9f5dbf4c.png)

The price for VS 2010 and 2012 is ￥49, 2013 is ￥59, 2017 is ￥69, 2019 is ￥79, and 2022 is ￥89. No discounts. 😭 

![image](https://user-images.githubusercontent.com/50246090/196646542-6bac2d4d-1737-4c5d-910f-7689f0dceb01.png)

Yeah, you can still buy VB 6.0 in 2022.

**Comment by suda-code** [comment]
@weimeng23 To add, China has a variety of software disguised as Steam, which is downloaded as a group number platform.

**Comment by hzk123** [comment]
![image](https://user-images.githubusercontent.com/19525769/196652433-eb7b37b0-8cbd-4ecc-b9c1-34bda3c56f8f.png)
我英文不好，如果我没有理解错的话，这个issue的意思是：张朦朦你妈死了

**Comment by panda2134** [comment]
Baidu seems to have already removed this ad in vscode search results. But the download link to microsoft website is ranked the 4th, even after tutorials on using vscode.
Bing removed the ad from "vscode" search results, but the ad is still there when you search "visual code".

IMHO, lawsuit against such piracy companies will barely work. The worst thing that will happen to them is going bankrupt.

**Comment by shen-lan** [comment]
笑尿😂
![苏喂苏喂苏喂](https://user-images.githubusercontent.com/21122615/196653570-72555758-610f-45ca-a3c0-ba270192c73a.gif)

**Comment by StevenTang1994** [comment]
既然大家都是中国人，那我就直接打中文了
先说一下他们公司是有限公司，承担的责任是有限的。
注册资本是10W，意思就是如果出了事公司法人最多赔偿10W了事。
最后，这家公司是真的无耻啊

**Comment by WangQingye** [comment]
牛的

**Comment by Silence-dream** [comment]
incomprehensible!😂

**Comment by baidan4855** [comment]
<img width="858" alt="image" src="https://user-images.githubusercontent.com/10466275/196658413-3080fed8-dab9-4bc6-993d-bcd844065143.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/10466275/196658545-1291c19f-72fc-4d91-97cb-6ad49afe5bd4.png">
看起来已经下线了，百度一生黑

**Comment by Developer27149** [comment]
FREEDOM !!! 你法我笑

**Comment by karuboniru** [comment]
> 先说一下他们公司是有限公司，承担的责任是有限的。

Limited liability company (LLC) don't imply the liability is always limited.

**Comment by PunchlY** [comment]
非蠢即坏!!

**Comment by lambdaq** [comment]
很多开源软件许可证是允许你拿出去打包售卖的  https://www.gnu.org/licenses/gpl-faq.zh-cn.html#GPLCommercially 无论你卖什么价钱，唯一的要求就是你的顾客要求你出示源码，你得无条件提供。

这里问题只是侵犯了vscode的商标。

**Comment by chaohui2** [comment]
![image](https://user-images.githubusercontent.com/17821872/196665995-191f3f7d-e8fc-47ec-b6b3-3e0a0d4e82a2.png)

**Comment by MoonShining** [comment]
lol

**Comment by apples1949** [comment]
特地前来查看
当场蚌埠住

**Comment by sena-nana** [comment]
It has been a meme for a long time XD.Finally someone shared it here.good job.

**Comment by code4EE** [comment]
牛批，还是百度🐂

**Comment by CrossingX** [comment]
LMAO

**Comment by ladyrick** [comment]
> 很多开源软件许可证是允许你拿出去打包售卖的 https://www.gnu.org/licenses/gpl-faq.zh-cn.html#GPLCommercially 无论你卖什么价钱，唯一的要求就是你的顾客要求你出示源码，你得无条件提供；顾客拿你的东西二次售卖，你也别拦着。
> 
> 开源软件不等于禁止商业化，只要许可证允许，你完全可以正大光明拿开源的东西打包换皮挣钱，比如 Redhat 就是这样一家大型企业。
> 
> 这里问题只是侵犯了vscode的商标。

官网下载的vscode不是完全开源版本的vscode，使用的license也不一样：https://code.visualstudio.com/License/。

**Comment by fengtalk** [comment]
百度无耻，Bing也不干净了。
Baidu is shameless, and Bing is no longer clean.

**Comment by Jerry-Terrasse** [comment]
lol

**Comment by Ninzeige** [comment]
![image](https://user-images.githubusercontent.com/51020316/196678924-cdbd6a49-ee46-4804-9821-f31a39278bc7.png) 
- "the graphics and software come from the Internet" 
- "respect the legitimate rights and interests of others" 
- "**if**(as if they didn't know) the content violates your legitimate rights" 
- "we will delete it as soon as possible"

**Comment by cz2415** [comment]
69.7-20=39.7

**Comment by sommio** [comment]
Essentially they only infringe on trademarks and the quality of content on the Chinese Internet is very low.

**Comment by LaurieLuo** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈，love from china

**Comment by liuoei** [comment]
非常好作品，英雄联盟，爱来自瓷器

**Comment by arimitx** [comment]
Chrome users in China: Hold my beer.

![1666180574023](https://user-images.githubusercontent.com/14220017/196684129-ec3634c4-b6f4-4e69-beca-583c2d44ee88.png)

**Comment by canliture** [comment]
![niubi](https://user-images.githubusercontent.com/31164470/196688366-8fd99f82-c9ff-4c49-bdf8-4e87bc40f85b.png)

**Comment by dreamncn** [comment]
A good suggestion is not to use Baidu search engine

**Comment by XiaoMiku01** [comment]
我们百度是这样的，@baidu

**Comment by Lakr233** [comment]
I’m thinking of popping up an alert that tells user when open for the first time. Hide alert’s code deep and dark!

**Comment by Him392** [comment]
It's very interesting that , if Microsoft prosecutes this company , it will say it just sells software installing service. But anyhow , I wish Microsoft can stop this swindle.

**Comment by Nyaacinth** [comment]
“The Fun They Had”

**Comment by ritajie** [comment]
The `Microsoft` editor authorized by `Google.com` to pay through `Alipay` searched from `Baidu.com`

**Comment by dejavuzzz** [comment]
蚌埠住了

**Comment by dbFlower** [comment]
> The `Microsoft` editor authorized by `Google.com` to pay through `Alipay` searched from `Baidu.com`

hard to "蚌"

**Comment by cronfox** [comment]
> 百度无耻，Bing也不干净了。 Baidu is shameless, and Bing is no longer clean.

只是奇怪的SEO罢了(

**Comment by Raspberry-Monster** [comment]
They even cannot do a correct calculation because 69.7-20=39.7 (The result is 49.7)

**Comment by medmin** [comment]
Apparently, the math is wrong. I am outrageous. :)

**Comment by recolic** [comment]
能用上百度，你们就偷着乐吧

**Comment by SAFEluren** [comment]
樂

**Comment by dawn-lc** [comment]
![不行，这太后现代了](https://user-images.githubusercontent.com/30336566/196826890-99382c95-0f52-4e26-9310-78749d8b496c.png)

**Comment by shenweiyan** [comment]
真是见识了

**Comment by yunyuyuan** [comment]
丢人丢到国外了属于是

**Comment by Nicolerobinn** [comment]
interesting

**Comment by yuchiXiong** [comment]
interesting

**Comment by MaYiFei1995** [comment]
V2观光团

**Comment by RE0x2A** [comment]
@baidu

**Comment by zhangjunjie6b** [comment]
感恩

**Comment by zhaixiaowai** [comment]
火钳流明

**Comment by liwenfengg** [comment]
V2观光团

**Comment by Mountain-boy** [comment]
funny

**Comment by sniperhgy** [comment]
69.7 - 20 = 39.7   ???

**Comment by chengnan049** [comment]
> How can you find this... Is just typing code.visualstudio.com too difficult for some people?

Maybe student

**Comment by tootal** [comment]
666

**Comment by Jsonpig** [comment]
> Do you know why there is a GFW in China? cause CCP sucks, these SOBs are afraid of their people knowning or telling the truth, all words published on China's social media/platform are reviewed strictly, anything CCP doesn't like will be banned, and on the other side, they claim that there is something called FREE-SPEECH is existed in China, so F*CK them

omg,Do you have any sense in saying that？LOL.

**Comment by chengnan049** [comment]
> > ![niubi]([user-images.githubusercontent.com/31164470/196688366-8fd99f82-c9ff-4c49-bdf8-4e87bc40f85b.png](https://user-images.githubusercontent.com/31164470/196688366-8fd99f82-c9ff-4c49-bdf8-4e87bc40f85b.png)
> 
> Is this picture anything related to this issue?

Yes It means unbelieve and awesome

**Comment by chengnan049** [comment]
> It's very interesting that , if Microsoft prosecutes this company , it will say it just sells software installing service. But anyhow , I wish Microsoft can stop this swindle.

There are too many such companies in China, you know? Adobe Flash Player, which is represented by a Chinese company, is still updated and added ads, does not allow you to use the international version (it will indicate that the software is damaged or not in the current area), and this ad is full of deceptive drugs and stock speculation content, some vulgar content, this adware program also comes with a virus (detected by Kaspersky), and the funniest thing is that the ads will crash when you watch the ads

**Comment by gaokun** [comment]
If a beginner can not recognize that shit, it would be the first lesson they need to learn.  ^_^

**Comment by Jsonpig** [comment]
> > 非常有趣的是，但如果微软这家公司，它会说它销售软件安装。只是，我希望微软能够阻止这种骗局。
> 
> 中国这样的公司有，你知道吗？药炒的内容，一些低俗的内容，这个广告软件程序还自带病毒（最搞笑的是看广告会崩溃）

The Internet environment in China is really bad now!

**Comment by SekiBetu** [comment]
lol

**Comment by cxinde** [comment]
雷碧，康帅傅

**Comment by sylvanas-c** [comment]
未来可期

**Comment by chengnan049** [comment]
> Developers who can't even find the official website should change careers ASAP

There are too many such fake official websites in Chinese search engines, and he just discusses this topic too much, not that he can't find the official website

**Comment by cxinde** [comment]
> 未来可期

依托Microsoft，快上市了😂

**Comment by Akimyou** [comment]
amazing.

**Comment by lovehhf** [comment]
unbelievable

**Comment by chengnan049** [comment]
> unbelievable

都在中国了，很普遍了吧

**Comment by quan7u** [comment]
6

**Comment by juju486** [comment]
> 

你是对的

**Comment by jsgjj111** [comment]
可以啊，有前途。美滋滋的

**Comment by yuxiaoyuan0406** [comment]
太丢撵了

**Comment by CaptainJackL** [comment]
![image](https://user-images.githubusercontent.com/6455728/196847294-9b5f8d32-3201-4692-9b3f-d1c767958b8b.png)
Time to manually revoke certificates from TrustAsia Technologies

The downloaded exe file is signed by:
CN = DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1

**Comment by dmlgzs** [comment]
这就是__.webp

**Comment by acerhp** [comment]
一眼顶真：鉴定为假

**Comment by qurikuduo** [comment]
[![29hEdS.gif](https://z3.ax1x.com/2021/05/26/29hEdS.gif)](https://imgse.com/i/29hEdS)

**Comment by acerhp** [comment]
信件已经收到啦~

**Comment by hurui200320** [comment]
Chinese programmer's first lesson: figuring out a way to access google (blocked in China) or bing international (blocked, and replaced by bing Chinese edition).

Chinese programmer's second lesson: learning English.

LOL

----

Anyway, I think google and Microsoft should take down those piracy and potentially harmful websites asap. Or, at least ask Nintendo and Disney about how to take down everything they don't like from the internet.

**Comment by MewX** [comment]
We can't really stop people without information source from doing those. People will always buy free software (like Chrome browser or VS Community) on Taobao because they don't know they are free.

**Comment by ZL-Asica** [comment]
这个有点厉害

**Comment by ftwater** [comment]
> Search from Baidu:
> 
> ![image](https://user-images.githubusercontent.com/50246090/196424828-5ead4681-c783-442e-bbea-0b8e4c15fcc2.png)
> 
> The first one is https://qnw.shaid.top/vscode/index.html:
> 
> ![image](https://user-images.githubusercontent.com/50246090/196424988-4523e2d7-4860-4631-876f-bfd4a2548359.png)
> 
> This website belongs to [Wuhan Hongge Yibai E-commerce Co. (武汉宏格亿佰电子商务有限公司)](http://www.shaid.top/).
> 
> If you do some searches on this domain, you can find their other "products":
> 
> * [Win10 Activation Tool (Win10 激活工具)](https://qnw.shaid.top/win10/index.html)
> * Telegram Chinese version (Telegram 中文版) (removed)
>   ![image](https://user-images.githubusercontent.com/50246090/196426820-f9fa3030-eb5e-430c-bdfc-026af7100576.png)
> * visualcpp (removed)
>   ![image](https://user-images.githubusercontent.com/50246090/196432416-34943cc9-de17-4e6b-a316-ca5a6ff3f5e7.png)
> 
> They even claim to be partners with China Mobile, China Unicom and China Telecom: [![image](https://user-images.githubusercontent.com/50246090/196426325-f39cc8ab-8b66-40b7-8a1e-edc32ad7c08b.png)](http://www.shaid.top/)
> 
> Thanks to the Great Firewall, we have such a "great" Internet in China.
> 
> Update:
> 
> Some people have found other similar companies:
> 
> * [Shangqiu Xuankangtai Network Technology Co. (商丘轩康泰网络科技有限公司)](http://www.sqiua.cn/index.html)
>   
>   * [Visual studio](http://office.xuank.top/install.php?m=visual)
>     ![image](https://user-images.githubusercontent.com/50246090/196571476-47c2e0e6-5465-4666-8889-ad34a1c4689a.png)
>   * [Software Superstore (软件商超)](https://xkt.sqiua.cn/)
>     ![image](https://user-images.githubusercontent.com/50246090/196572556-a30b1388-e5f5-43f8-a94a-419e5501c2f9.png)
>   * [System Home - Windows premium system download site (系统之家-Windows精品系统下载站)](http://windows.sqiua.cn/index.html)
>   * [visualbasic](http://office.xuank.top/install.php?m=visualbasic)
>   * [directx Repair Master (directx修复大师)](http://office.xuank.top/install.php?m=directx)
>   * [Chrome](http://chrome.sqiua.cn/)
>     ![image](https://user-images.githubusercontent.com/50246090/196573087-e4bfb9f0-3060-4e72-a6bf-05a35238a151.png)
>   * [Yixin Cat House (忆心猫舍)](http://yixinmaoshe.sqiua.cn/)
>     ![image](https://user-images.githubusercontent.com/50246090/196572912-95f01175-ad54-40d7-bfe7-2b10aaa767b8.png)
>   * [AdobeCAD](https://autocad.sqiua.cn/)
>   * [Map marking service center (地图标注服务中心)](http://mr.sqiua.cn/)
> * [Yunnan Norforkang Network Technology Co. (云南诺福康网络科技有限公司)](http://www.cvbty.cn/)
>   
>   * [Xunjian Mind Map (寻简思维导图)](http://sw.xuank.top/)

宣称三大运营山是合作伙伴，怕是开通了三大运营商的宽带套餐吧哈哈哈哈哈哈

**Comment by cronfox** [comment]
> > 我更担心在国产Linux推广开以后，会不会有类似的无良商家把黑手伸向Linux平台的vscode或其他软件。
> 
> 已经有 Ubuntu 和 CentOS 了，收费80多，B站有学生上当

要是卖实体安装介质收收本钱也不是不行(
要是提供怎么装的服务也不是不行(

**Comment by xgdyp** [comment]
In taobao, some merchants provide installation package download service too.

**Comment by jinmingyi1998** [comment]
真 智商税

**Comment by wheatup** [comment]
Wait, you guys installed VSCode for FREE?
![image](https://user-images.githubusercontent.com/6663691/196856413-fdde90d1-7d8e-41d9-bda4-123740017d27.png)

**Comment by coderweb1** [comment]
So funny

**Comment by liguonan888** [comment]
> > How can you find this... Is just typing code.visualstudio.com too difficult for some people?
> 
> Use Baidu to search for vscode. Click Open in the first advertisement......

congratulations! it's very common on the China mainland to encounter this situation

**Comment by liguonan888** [comment]
![image](https://user-images.githubusercontent.com/54622682/196858979-1b4310c8-f172-48ea-b20a-86b32e9c447b.png)

**Comment by liguonan888** [comment]
![image](https://user-images.githubusercontent.com/54622682/196860848-1c74ace1-1270-4b33-a3c5-fc0ba03201db.png)

**Comment by coyude** [comment]
![QQ图片20221020130910](https://user-images.githubusercontent.com/24607145/196861392-e5eca5c2-923a-4dc3-a649-4c5253aa2e25.jpg)

**Comment by netbuggang** [comment]
Wait, you guys are installing VSCode for FREE?

**Comment by lisenux** [comment]
建议入典

**Comment by chengnan049** [comment]
> Wait, you guys are installing VSCode for FREE?

Now that you have the ability to communicate on GitHub, I think you're kidding

**Comment by chengnan049** [comment]
> In taobao, some merchants provide installation package download service too.

这种是侵权，不一样的性质

**Comment by wheatup** [comment]
This is absurd yet quite common in China, which is more embarrassing than funny. Sh*tposting the comment section is making it even worse. Someone has to put a stop to this.

**Comment by netbuggang** [comment]
> That's the most fabulous CHINA, most successful business model. Lots of similar business models on the Chineses Internet. It's a big pity for citizens(oh, we are just _"韭菜"_, never be a true citizens ever ) here. FUCK CCP!

你小子号没了

**Comment by h7ml** [comment]
> That's the most fabulous CHINA, most successful business model. Lots of similar business models on the Chineses Internet. It's a big pity for citizens(oh, we are just _"韭菜"_, never be a true citizens ever ) here. FUCK CCP!

危

**Comment by Yinboan** [comment]
> That's the most fabulous CHINA, most successful business model. Lots of similar business models on the Chineses Internet. It's a big pity for citizens(oh, we are just _"韭菜"_, never be a true citizens ever ) here. FUCK CCP!

危

**Comment by Miroxyz** [comment]
So 69.70 - 20 = 39.70 ????

**Comment by k237618899** [comment]
It's not that surprise for me these things happening in China.
As we all know there is a firewall call "GFW" protecting user using internet so...
The truth is that the man who paid a large amount of money can do anything he want

**Comment by liguonan888** [comment]
> That's the most fabulous CHINA, most successful business model. Lots of similar business models on the Chineses Internet. It's a big pity for citizens(oh, we are just _"韭菜"_, never be a true citizen ever ) here. SO WHAT. The sun rises from the EAST day by day, never changed.
你是狗吗

**Comment by Zzy0706** [comment]
Thanks Baidu, 💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰💰

**Comment by liguonan888** [comment]
> That's the most fabulous CHINA, most successful business model. Lots of similar business models on the Chineses Internet. It's a big pity for citizens(oh, we are just _"韭菜"_, never be a true citizen ever ) here. FUCK CCP.



你是狗? 滚你妈的hi , 
这些东西是某些无良公司的作为,请你不要上升到这个层面. 
小心生孩子没屁眼. 出门被大货车压死

**Comment by LxnChan** [comment]
Even if the officials could notice, there is no way to make such people disappear. Such companies are all shell companies, a company may have just two employees, a packager and a legal officer. That's what's so pathetic.

![23EBEDCA3763335B3422895935B7BDB0](https://user-images.githubusercontent.com/46388610/196868970-476f8d72-891d-40e5-82a7-16372fd807b8.jpg)

**Comment by sineycoder** [comment]
百度果然向钱看齐

**Comment by zwh0809** [comment]
不要核酸要吃饭，不要封控要自由，不要谎言要尊严，不要文革要改革，不要领袖要选票，不做奴才做公民

**Comment by YangYongAn** [comment]
> 发起要吃饭，不要封控要自由，不要礼让，不要文革要改革，不要带头选票，不要做奴才才做

好你小子，逮住你了

**Comment by YangYongAn** [comment]
智商税，挺好的

**Comment by kukume** [comment]
楼上有个小粉红急了

**Comment by mpc82** [comment]
> 



> 
We have very good access to code.visualstudio.com

**Comment by kbtxwer** [comment]
国内网站很多都喜欢给人喂狗屎，毕竟只有你吃屎了它们才能吃上饭

**Comment by Gentlemeng** [comment]
> 安利个 google extension: 百度去广告

**Comment by zhxycn** [comment]
WHY USE Baidu? In China, [Bing](bing.com) works just as well.

**Comment by cw1997** [comment]
We call somebody who paid 'IQ tax'（智商稅） in Chinese if he has downloaded and paid for it. :-D

Long years ago, I also saw some online shops(mainly on Taobao) sell discs with burned Ubuntu ISO images, I reported these behaviors to the official community and some software engineer forums but some people replied to me that these behaviors are OK and are not illegal.
