### ISSUE TITLE
Disk Space

### ISSUE THREAD

**Issue by HugoHenrique491** [microsoft/vscode#163750]
Type: <b>Bug</b>

Hello, I have been using VS Code for a bit now and I have noticed that it has taken over almost completly my disk space. For reference, I have around 476GB total space on my device and I remember, prior to using VS Code that half of that wasn't even being used. In just one evenning it has been completly taken up and now I only have around 3,52GB available and the number seems to be going down as I write this. I looked up for solutions to this problem and it would seem that this is somehow a common issue and all the solutions that came up happened to only allow me clean up around 1GB of disk space. I am now asking for help in order to prevent this issue from happening and would like to know how exactly the application takes so much space and where does it store in order for me to be able to clean it up on me own and restore my disk space as it once were.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by aeschli** [comment]
You can find the VS Code install at `%AppData%\Local\Programs\Microsoft VS Code`. It should be around 340 MB.
Configuration data can be found at `%AppData%\Roaming\Code\User`. It contains user settings and also data stored by extensions. Some extensions cache a lot of state such as index files. I recommend to check these folders.

**Comment by HugoHenrique491** [comment]
Hello, thanks for responding. I had already explored those options and, as previously stated, it cleared around only 1 GB of space. I'll try it again whenever possible and see how that goes.

**Comment by aeschli** [comment]
Closing the issue.
