### ISSUE TITLE
command `workbench.extensions.action.showInstalledExtensions` not found

### ISSUE THREAD

**Issue by bartekpacia** [microsoft/vscode#163782]
**Does this issue occur when all extensions are disabled?**

Yes.

- VS Code Version: 1.72.2
- OS Version: macOS 12 Monterey (12.6 – 21G115)

Steps to Reproduce:

1. Have the following keybinding in `~/Library/Application Support/Code/User/keybindings.json`:
    ```json
    {
      "key": "cmd+k cmd+x",
      "command": "workbench.extensions.action.showInstalledExtensions"
    },
    ``` 
2. Use `CMD+K CMD+X` to run the command
3. See the error popup appear:
<img width="542" alt="Screenshot 2022-10-16 at 5 28 38 PM" src="https://user-images.githubusercontent.com/40357511/196043929-5cb6a135-b8f3-45c3-a4e5-b8d9460b2871.png">

I've had this command in my `keybindings.json` for more than 2 years, and now it's suddenly broken. Why? What should I use instead? This is poor DX.

**Comment by bartekpacia** [comment]
@driftingly Thanks a lot, works for me. How'd you find it?

**Comment by driftingly** [comment]
Found this on Twitter: https://twitter.com/aka_tpayne/status/1295741633909194755?s=61&t=EZ6Np6ojtuKjYm64Du89BA

**Comment by bartekpacia** [comment]
LOL, thanks a lot!
