### ISSUE TITLE
Terminal: Focus Terminal Tabs view keybinding appears dead/non-working.

### ISSUE THREAD

**Issue by NicolaasZwart** [microsoft/vscode#163789]
I'm on macOS 12.6 running VS Code version 1.72.2 (Universal) and after a recent update, the "Terminal: Focus Terminal Tabs View" keybinding won't function.

In short, while focused on the terminal pane, I used to be able to press cmd+shift+\ and move the focus to the Terminal Tabs to the right of the terminal pane (if I had more than one terminal open, which caused the Terminal Tabs to exist).

Now, that keybinding doesn't work anymore, nor does any alternative keybinding for "Terminal: Focus Terminal Tabs". 

These are the current when expressions:
"terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported || terminalHasBeenCreated && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus"

But removing those when expression entirely or altering them or testing them one at a time does nothing to solve this issue either.

**Comment by gjsjohnmurray** [comment]
I suggest you check any`terminal.integrated.commandsToSkipShell` and `terminal.integrated.sendKeybindingsToShell` settings.

**Comment by NicolaasZwart** [comment]
I just tried enabling `terminal.integrated.sendKeybindingsToShell` and that didn't change any behavior. I also looked through the default commands in `terminal.integrated.commandsToSkipShell` and didn't see any that were skipping the Focus on Terminal Tabs view command.

**Comment by AHopley** [comment]
I'm getting the same issue for 1.72.2 on Windows. It isn't just about keybindings. Pressing F1 and doing "Terminal: Focus Terminal Tabs View" moves focus to the active terminal rather than the terminal tabs view. This is true when focus is in the editor, and also if the focus is in the terminal tabs view (which now only seems to be selectable using the mouse).

**Comment by jeanp413** [comment]
This is a regression from https://github.com/microsoft/vscode/pull/161989, created a PR fixing this https://github.com/microsoft/vscode/pull/164408
