### ISSUE TITLE
Confirmation box before quit vs code

### ISSUE THREAD

**Issue by jb-thery** [microsoft/vscode#163704]
It would be very cool to have a confirmation box when you quit vs code with the keyboard shortcut `command + q `on mac. It's very annoying that vs code closes if you do `command + q `without doing it on purpose instead of `command + s`

**Comment by gjsjohnmurray** [comment]
Does the `window.confirmBeforeClose` setting help you?

**Comment by jb-thery** [comment]
Thanks ! it's that @gjsjohnmurray
