### ISSUE TITLE
Install language pack notification always show

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#163752]
After I install Chinese language pack, uninstall it, every time I open a new window, always notice it.

```
Version: 1.73.0-insider (Universal)
Commit: 7ef8e6b87a2a5a25ba1ef946bd1640ca3510956c
Date: 2022-10-14T05:18:26.756Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/41773861/196004037-890aefcd-ae0e-4754-a251-0b761ff7b49b.png">

**Comment by rzhao271** [comment]
The code now tries to use the system language to determine whether there could be a language pack to recommend to users, but I agree that showing it every new window is excessive.

**Comment by TylerLeonhardt** [comment]
@tjx666 2 questions:

1. when you run `Configure Display Language` what is the "Current" language? English? 
2. when you run `Configure Runtime Arguments` what do you have set for `"locale"` (if any) and if it's not `en` can you set it to `en` and let me know what happens for you?

**Comment by tjx666** [comment]
![image](https://user-images.githubusercontent.com/41773861/199873991-fca12128-956f-47e1-aec0-215cd56294b6.png)

![image](https://user-images.githubusercontent.com/41773861/199874042-b3bc7e2d-c90c-453e-94d4-0b6ea67a95b9.png)

It's strage that I had never manualy modified the argv.json

**Comment by TylerLeonhardt** [comment]
@tjx666 yeah I think a bug in this is that uninstalling the language pack should remove the locale property or set it to English...

Do you get what you want if you set the locale in the args to `en`?

**Comment by tjx666** [comment]
@TylerLeonhardt I had set never notify again, so I can't check that....

**Comment by tjx666** [comment]
After I install the latest insider version. This issue still exists:


https://user-images.githubusercontent.com/41773861/200897769-3957d2b7-4f74-4b9f-aba4-dc7fe4069b95.mov

**Comment by tjx666** [comment]
This is very annoying. @TylerLeonhardt Any ideas about it?

**Comment by TylerLeonhardt** [comment]
@tjx666 coming back from the holidays... there should be a "Don't show again" option under the little gear icon. Do you see that option? It's suppose to make this prompt go away forever. Does it?

**Comment by tjx666** [comment]
> @tjx666 coming back from the holidays... there should be a "Don't show again" option under the little gear icon. Do you see that option? It's suppose to make this prompt go away forever. Does it?

Yes

**Comment by TylerLeonhardt** [comment]
@tjx666 since that allows you to control whether you see this notification in the future, I feel like this issue is covered and we can close it.... unless I'm misunderstanding the issue.
