### ISSUE TITLE
Links no longer clickable in HTML

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16376]
This is a regression it seems, you could always click on a path to open it even if the file does not exist. People use it to scaffold files:

![image](https://cloud.githubusercontent.com/assets/900690/20832577/3acca7a2-b88b-11e6-9bd0-378ab1ae75b8.png)

**Comment by Mlocik97** [comment]
I think, it's not bug.

**Comment by aeschli** [comment]
![image](https://cloud.githubusercontent.com/assets/6461412/20848724/9bc02c9e-b8d3-11e6-9c82-7294ed8d452d.png)

That seems to work for me...

**Comment by bpasero** [comment]
Nope: left Insiders, right Code:

![view-picker](https://cloud.githubusercontent.com/assets/900690/20857228/84b60364-b925-11e6-82b5-2a3a162ae415.gif)

**Comment by Mlocik97** [comment]
I think, it's not bug. https://github.com/Microsoft/vscode/issues/11802

**Comment by chrmarti** [comment]
Doesn't work for me, both when the file exists and when it does not. Reopening for investigation.

- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:05:09.124Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-docker|PeterJausovec|0.0.7|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|tslint|eg2|0.6.0|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

Source:
```
<html>
	<head>
		<script type="text/javascript" src="foo.js"></script>
	</head>
	<body>
	</body>
</html>
```

**Comment by aeschli** [comment]
I see the underline, but clicking on it doesn't seem to work. Is that what you see, @chrmarti ?
That looks like a different issue. I created #16922

If not, can you find out if the language server detects links? For that, set `'html.trace.server': 'verbose'` and open the HTML language server output view

**Comment by chrmarti** [comment]
I see the underline too.
