### ISSUE TITLE
When you try to pull (or checkout) with pending changes an incorrect message is provided

### ISSUE THREAD

**Issue by asyschikov** [Microsoft/vscode#16370]
- VSCode Version: 1.7.2
- OS Version: 10.12.1

Steps to Reproduce:

1. Open a project that is linked to remote a git repositoty.
2. Do a clone in another dir or ask a friend to modify a file, commit, and push.
3. Modify the same file locally and try to pull.

You will get an error saying (emphasis mine):
> Can't pull. Please commit or **stage** your work first.

Meanwhile, in the git console you see a different and _correct_ error:

> Please commit your changes or **stash** them before you merge.

The error is that "stash" is the correct action, staging won't help.
Here is the line https://github.com/Microsoft/vscode/blob/3407c06a91ca4aabd9cf97c31f99622c908bee4d/src/vs/workbench/parts/git/browser/gitActions.ts#L938

**Comment by joaomoreno** [comment]
Fixed by #16374
