### ISSUE TITLE
I can't find the nightly version in the extension view

### ISSUE THREAD

**Issue by Aster89** [microsoft/vscode#163700]
The following is from the read me

> 1. Open the extensions view (ctrl+shift+x) and search for `@builtin @id:ms-vscode.js-debug`
> 2. Right click on the `JavaScript Debugger` extension and `Disable` it.
> 3. Search for `@id:ms-vscode.js-debug-nightly` in the extensions view.
> 4. Install that extension.

however at step 3 I don't find anything (the result shows _No extensions found_).

What am I missing?

**Comment by connor4312** [comment]
Also, to confirm, are you using VS Code proper or something like VS Codium?

**Comment by connor4312** [comment]
Yea, that appears to be a VS Codium build, and therefore does not use the same extension marketplace. You can download the nightly build from the right hand side of https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug-nightly and the use the "Install from VSIX" command to manually install it.
