### ISSUE TITLE
Better defaults for files.trimTrailingWhitespace

### ISSUE THREAD

**Issue by kendaleiv** [Microsoft/vscode#1637]
Using vscode for TypeScript with the default setting I've found I get all kinds of trailing spaces appearing.

At least in one case (markdown) end of line whitespace is important to allow, though. Not sure what kind of complexity that adds.

Basically, this issue boils down to **it's nice when the defaults 'just work'.**

However, this might be something for https://github.com/Microsoft/vscode-editorconfig to handle instead. According to the vscode-editorconfig repo [README.md](https://github.com/Microsoft/vscode-editorconfig/blob/ff3f2f13f8ea50ac78b39ecf13d0c4b434c9f743/README.md) as of now `trim_trailing_whitespace` is "On the backlog".

**Comment by bpasero** [comment]
Subsumed by https://github.com/editorconfig/editorconfig-vscode
