### ISSUE TITLE
Avoid sync fs-call at startup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16378]
In `terminal.ts` this code can be found [`if (fs.existsSync('/etc/debian_version'))`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/execution/electron-browser/terminal.ts#L10). Since this happens globally (in the module scope) it interrupts code loading and slows down the startup

**Comment by jrieken** [comment]
related to #15455

**Comment by Tyriar** [comment]
To verifier: Please check in a non-debian OS (eg. Fedora, CentOS) that the expected terminal comes up, it should be `gnome-terminal` is you're on gnome or `konsole` on KDE.
