### ISSUE TITLE
API: Output grammar applies to all output channels, not only that specified languageId

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#163784]
Does this issue occur when all extensions are disabled?: Yes

It seem there is no way (at least I couldn't find) create custom highlighting for a specific output channel only, it applies to all output channels that didn't specify `languageId`.
[Here](https://gist.github.com/vanowm/8209c95077ea4960536accbff5e48800) is a gist of example extension, it creates two channels, one that specified `languageId` (`"mytestextension-output"`) one that doesn't, both of them show text in red. In fact all other output channels (git, tasks, etc) show text in red

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by ssbarnea** [comment]
I am curious if the bug still happens you explicitly pass a language id for each call of create channel.

**Comment by vanowm** [comment]
@ssbarnea with passed language id, it doesn't interfere with other language ids. And it seems non-language-id channels inherit grammar from previous used language id.

**Comment by sandy081** [comment]
This is because you have associated `mytestextension-output` language to all output channels by adding  `text/x-code-output` mimetype. Please remove that and it should work as expected.

```json
"languages": [
      {
        "id": "mytestextension-output",
        "aliases": [],
        "mimetypes": [
          "text/x-code-output"
        ]
      }
    ],
```
