### ISSUE TITLE
Running multiple cmd tasks in tasks.json seem too mutually excluce themselves

### ISSUE THREAD

**Issue by UncleFirefox** [Microsoft/vscode#16373]
Hi, I'm creating a build task to run tsc to get compilation errors and tslint to see the warnings I've got defined for project. I just can run one task at a time, if I put isBuildCommand to more than one task only the first seems to be executed.

Note: I also have TSLint extension by egamma

- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1. Use the following tasks.json:

```
{
    "version": "0.1.0",
    "command": "cmd",
    "isShellCommand": true,
    "showOutput": "always",
    "args": [
        "/C"
    ],
    "tasks": [
        {
            "taskName": "Build Type Script",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "tsc -p ."
            ],
            "problemMatcher": "$tsc"
        },
        {
            "taskName": "tslint",
            "suppressTaskName": true,
            "isBuildCommand": true,
            "args": [
                "tslint src/**/*.ts{,x} test/**/*.ts{,x} --project tsconfig.json"
            ],
            "problemMatcher": {
                "owner": "tslint",
                "fileLocation": [
                    "relative",
                    "${workspaceRoot}"
                ],
                "severity": "warning",
                "pattern": {
                    "regexp": "^(\\S.*)\\[(\\d+), (\\d+)\\]:\\s+(.*)",
                    "file": 1,
                    "line": 2,
                    "column": 3,
                    "message": 4
                }
            }
        }
    ]
}
```

2. Do ctrl+shift+b

3. Depending on the order of the tasks I just see errors (tsc) or warning (tslint)

Is this a bug or it's just the way it works for now?

**Comment by plievone** [comment]
You may be able to run multiple commands in parallel depending on your shell and os, for example by using `&!`. So my workaround was to launch a single watching build task such as `npm run dev` which calls `npm run dev:client &! npm run dev:server` and it works nicely.

**Comment by UncleFirefox** [comment]
Thanks for the suggestion, I just saw you could specify multiple paths with tslint instead of &&. My problem is that using `"isBuildCommand":true` I just can run one of the tasks not both :(

**Comment by dbaeumer** [comment]
@UncleFirefox this is a know limitation right now. You can only run one command at a time hence only one tasks is started if you press Ctrl+Shift+B.

**Comment by dbaeumer** [comment]
Dups #981 & #1167.
