### ISSUE TITLE
Bottom panel doesn't close after closing terminal

### ISSUE THREAD

**Issue by rubenvannieuwpoort** [microsoft/vscode#163719]
Type: <b>Bug</b>

The 
When I close a terminal, the bottom panel stays open on the 'terminal' tab, without actually showing a terminal.

Screenshot right before executing "exit" to exit the terminal:
![](https://i.snipboard.io/muKPHV.jpg)

Screenshot right after executing "exit" in the terminal. As you can see, the bottom panel is still open.
![](https://i.snipboard.io/TdWLo3.jpg)

Steps to reproduce:
1. Open the terminal bottom panel by pressing ctrl + `.
2. Close the terminal by pressing ctrl + D, or by executing the "exit" command.

Actual result:
The terminal closes, but the bottom panel stays active on the 'terminal' tab. The ctrl + ` shortcut to open a new terminal in the bottom panel also no longer works until I close the bottom panel with the 'x' in the right top corner of the bottom panel.

Expected result:
I expect the bottom panel to close, as it did before the upgrade to the latest version.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.19.0-76051900-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor (32 x 3908)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|62.73GB (59.12GB free)|
|Process Argv|--new-window /home/ruben/Desktop/reals --crash-reporter-id bd92a1fa-8279-4d58-8dfa-2eacb22a7e79|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.16.1
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
back-n-forth|nic|3.1.1
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30573243

```

</details>

**Comment by nektro** [comment]
happens to me too

```
VS Code version: Code 1.68.1 (30d9c6cd9483b2cc586687151bcbcd635f373630, 2022-06-15T02:58:26.441Z)
OS version: Linux x64 5.15.52
Restricted Mode: No
```
