### ISSUE TITLE
Some lines of a file are deleted and I can only see 2 days of the timeline history of the file.

### ISSUE THREAD

**Issue by jdmanabat** [microsoft/vscode#163770]
Type: <b>Bug</b>

I'm not sure how to replicate it, but I was working on a single file with multiple components 2 days ago, and when I opened that file today some lines of that file are deleted. I tried to check the file Timeline in VSCode but I can only see 2 days of the file history local changes. I'm not sure if this is relevant but I commented out the components that got deleted. It's kind of a bit my fault for not pushing my changes to be safe.

![image](https://user-images.githubusercontent.com/36387552/196029133-5edc28a3-d7de-4dde-85a1-c4bd1b872ef1.png)

![image](https://user-images.githubusercontent.com/36387552/196029140-e0416efe-6f90-4f84-a1e9-93d6ef96741c.png)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-50-generic snap
Modes:
Sandboxed: No

**Comment by joyceerhl** [comment]
@jdmanabat is this in a local git clone of a repository or in VS Code for the web (vscode.dev/github.dev)? Which directory is your file in?

**Comment by jdmanabat** [comment]
@joyceerhl it's a local git clone of a repo. I'm not sure if this will help but I updated ubuntu and I assume the apps got updated too last Friday.

**Comment by joyceerhl** [comment]
Are your files located in the directory that your VS Code installation writes update files to? cc @joaomoreno for updates, I thought we did some work here to make it more noticeable when this happens and can't find the relevant issue...

**Comment by jdmanabat** [comment]
@joyceerhl yes. Been working on it for a few months. This is the first time that this has happened. Luckily, I still can redo the code that got deleted.

**Comment by joaomoreno** [comment]
> @joyceerhl yes.

To confirm: What is the full path of your workspace, in your disk?

**Comment by jdmanabat** [comment]
@joaomoreno `/home/jd/Desktop/Projects/Revnue/app/src/components/forms/SearchBar.tsx`

**Comment by joaomoreno** [comment]
There's not enough details here to pinpoint how your code got deleted. Do you have other tools running over your code?

**Comment by jdmanabat** [comment]
hmmm, I have docker, and vscode extensions enabled. 
![image](https://user-images.githubusercontent.com/36387552/196311442-c6f82149-aa21-4ea6-8722-4971242e7888.png)

Just also realized that even some of the lines in my scss file got deleted too.

**Comment by joaomoreno** [comment]
It's very hard to figure out what happened, unfortunately. Let us know if this happens again.
