### ISSUE TITLE
Python runs differently.

### ISSUE THREAD

**Issue by Logarithm1729** [microsoft/vscode#163725]
Type: <b>Bug</b>

I was solving a problem on a competitive programming site called Atcoder, and the debugger ゙ was processing the problem correctly, but not well in normal execution.(At input example 3)
Site (Atcoder) --> (https://atcoder.jp/contests/abc231/tasks/abc231_c)

The code is bellow

import bisect

N, Q = map(int, input().split())
A = sorted(list(map(int, input().split())))
for i in range(Q):
    x = int(input())
    print(N - bisect.bisect_left(A, x))

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:55.763Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|--crash-reporter-id 02607fab-1590-40a2-bcf0-b959982a3540 --crash-reporter-id 02607fab-1590-40a2-bcf0-b959982a3540|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.1
es7-react-js-snippets|dsz|4.4.3
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
mdmath|goe|2.7.4
go|gol|0.35.2
rainbow-csv|mec|3.2.0
vscode-docker|ms-|1.22.1
vscode-language-pack-ja|MS-|1.72.10120948
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
material-icon-theme|PKi|4.21.0
markdown-preview-enhanced|shd|0.6.3
vscode-scss-formatter|sib|2.4.3
markdown-all-in-one|yzh|3.4.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by roblourens** [comment]
Sorry, this is probably an issue with your code or that site
