### ISSUE TITLE
`Find in Folder...` in explorer context menu should be `Find it Folder`?

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#163709]
<img width="283" alt="image" src="https://user-images.githubusercontent.com/31675041/195955058-4b51b684-4247-4fbf-9eb0-93ea2a00a352.png">

`...` is usually reserved for actions that have an intermediate step before it's performed, but `Find in Folder` performs the search immediately for users with `searchOnType` enabled, and it's enabled by default. Consider taking the `...` off of the end of the command name.

**Comment by eleanorjboyd** [comment]
Cannot find this menu item anymore- likely changes have been made in this area since the time this issue was created
