### ISSUE TITLE
Have to scroll to find a specific file when open too many files

### ISSUE THREAD

**Issue by HarperCy** [microsoft/vscode#163724]
![image](https://user-images.githubusercontent.com/47998305/195976722-ac0ff900-e160-4a9e-9123-ecfec885f224.png)
As above, when I open many files in the editor groups, they all show up in a line and a scroll bar will show up. The only way to find a specific file is to scroll back and forth, which is very inefficient. I wonder if there is a way to make all files displayed in multiple lines, which will be much easier to find the file I need.

**Comment by gjsjohnmurray** [comment]
Please use the `workbench.editor.wrapTabs` setting.

**Comment by HarperCy** [comment]
Cheers!
