### ISSUE TITLE
File tree in disabled state when creating file/folder and the window is not focused

### ISSUE THREAD

**Issue by Hacksore** [microsoft/vscode#163775]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: macOS 12.4 (21F79)

Steps to Reproduce:

1. Place VSCode in the foreground and focus another app
2. Right click in the file tree and create a new file
3. Right click again in the file tree area
4. Left click into your source code file

demo

https://user-images.githubusercontent.com/996134/196033393-de07f2c4-f8d4-4c34-8ddf-635b29031348.mp4

I believe this could be solved by having the right click to create a file/folder tell electron focus the window.

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/148849
