### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by KirovYuri** [microsoft/vscode#163797]
Type: <b>Performance Issue</b>

The visual code is too Laggy when 2 tabs

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.06GB free)|
|Process Argv|C:\\Users\\client\\Desktop\\GAMEMODES\\Pogisihaven --crash-reporter-id ddcaff55-327b-4804-b957-35bb21c28203|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 20824	code main
    0	   453	  3660	   window (● bcrp.pwn - Pogisihaven - Visual Studio Code)
    0	    95	  4136	   issue-reporter
    0	   234	 11696	   gpu-process
    0	    26	 14820	   crashpad-handler
    0	   205	 16180	   extensionHost
    0	    75	  3792	     "C:\Users\client\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\client\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=16180
    0	   213	  7320	     "C:\Users\client\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\client\.vscode\extensions\southclaws.vscode-pawn-1.0.0\out\server\server.js --node-ipc --clientProcessId=16180
    0	    71	  8756	     "C:\Users\client\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\client\.vscode\extensions\mtxr.sqltools-0.25.1\dist\languageserver.js --node-ipc --clientProcessId=16180
    0	   116	 18492	   shared-process
    0	    81	  9860	     ptyHost
    0	     6	  1748	       console-window-host (Windows internal process)
    0	    55	  2108	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    75	 15464	     fileWatcher
    0	    41	 18656	   utility-network-service
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● bcrp.pwn - Pogisihaven - Visual Studio Code)
|    Folder (Pogisihaven): 3363 files
|      File types: inc(2673) own(160) txt(55) url(49) so(14) amx(13) h(12)
|                  pwn(11) xsl(8) &FP(8)
|      Conf files: settings.json(1) tasks.json(1) sln(1);
```

</details>
<details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
amxxpawn-language|Abh|0.7.6
doxdocgen|csc|1.4.0
pawn-scripting-language-support|dce|0.0.5
vscode-pull-request-github|Git|0.50.0
discord-vscode|icr|5.8.0
better-cpp-syntax|jef|1.16.1
amxxpawn-language|Kli|0.7.5
csharp|ms-|1.25.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
vsliveshare|ms-|1.0.5735
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
sqltools|mtx|0.25.1
vscode-pawn|sou|1.0.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal
