### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by RomeTheProphet** [microsoft/vscode#163732]
ADD ISSUE DESCRIPTION HERE

Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
User Agent: Mozilla/5.0 (Linux; Android 10; NEN-LX1; HMSCore 6.6.0.312) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.105 HuaweiBrowser/12.1.1.324 Mobile Safari/537.36
Embedder: github.dev

**Comment by aeschli** [comment]
Please add the issue description.
