### ISSUE TITLE
Slow launch when preLaunchTask is used

### ISSUE THREAD

**Issue by levodelellis** [microsoft/vscode#163751]
Does this issue occur when all extensions are disabled?: Yes, did not exclude the MS C++ extension as it's required.

Version info below. I test with and without extensions, speeds were the same. At the bottom I timed how long it would take me to run a script that executes clang and to launch gdb. I hit enter and ctrl+d as fast as possible and it took < 200ms. vscode is at minimum 10x slower. The problem seems to have preLaunchTask

To measure I counted frames recorded 60fps by OBS. I start counting from the first frame the debug bar shows up considering it frame 1 but I'm sure it takes a few ms for that to show.

Without prelaunchtask (with extension on) it took 41 frames to execute the binary and show hello world in the console.

When extensions OFF except the microsoft C++ extension (which I need to launch the debugger) it took 140ish frames. Having my usual extentions on took the same amount of time. I tried several times and I stopped counting after 120 frames. 41->120 is a huge gap. There's no reason the prelaunchtask should take 80frames (1.3seconds) when the actual building is 42ms. The test (time shown below) is to build, run gdb and exit, done in <200ms. 1300ms is pretty ridiculous on top of a not so fast 683ms. My real life c++ project takes <1s to build and my bigger one takes <1.5 using multiple cores. Its a pretty noticeable lag to wait 2.5s to execute the project in a debugger when an incremental build takes clang <500ms (The last one I worked on was 350ms). Usually I don't care but when I make a lot of small changes and want to run to make sure no test broke it's extremely noticeable.

	Version: 1.72.0
	Commit: 64bbfbf67ada9953918d72e1df2f4d8e537d340e
	Date: 2022-10-06T22:56:30.304Z
	Electron: 19.0.13
	Chromium: 102.0.5005.167
	Node.js: 16.14.2
	V8: 10.2.154.15-electron.0
	OS: Linux x64 5.19.13-arch1-1
	Sandboxed: No

	$ cat a.sh
	clang a.c
	gdb ./a.out

	$ time ./a.sh 
	a.c:2:1: warning: implicit declaration of function 'puts' is invalid in C99 [-Wimplicit-function-declaration]
	puts("Hello");
	^
	1 warning generated.
	GNU gdb (GDB) 12.1
	Copyright (C) 2022 Free Software Foundation, Inc.
	License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
	This is free software: you are free to change and redistribute it.
	There is NO WARRANTY, to the extent permitted by law.
	Type "show copying" and "show warranty" for details.
	This GDB was configured as "x86_64-pc-linux-gnu".
	Type "show configuration" for configuration details.
	For bug reporting instructions, please see:
	<https://www.gnu.org/software/gdb/bugs/>.
	Find the GDB manual and other documentation resources online at:
		<http://www.gnu.org/software/gdb/documentation/>.

	For help, type "help".
	Type "apropos word" to search for commands related to "word"...
	Reading symbols from ./a.out...
	(gdb) 
	quit

	real	0m0.172s
	user	0m0.091s
	sys	0m0.039s

**Comment by roblourens** [comment]
Sorry, feel like I missed a step. What is the preLaunchTask? What is the launch config?

**Comment by levodelellis** [comment]
I'm not sure what happened but 1.72.1 seemed to have fixed it. The time went from over 2 seconds to <.8

preLaunchTask and launch config are explained https://code.visualstudio.com/Docs/editor/debugging

**Comment by roblourens** [comment]
I know what they are. I was asking what exactly yours are- it's hard to understand what's actually happening without that detail. But sounds like it's fixed.
