### ISSUE TITLE
Cannot write Bengali in VSCode in Ubuntu Snap

### ISSUE THREAD

**Issue by AAShakil50** [microsoft/vscode#163747]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2 x64
- OS Version: Ubuntu 22.04.1 LTS

I cannot write Bengali in VSCode. Recently I have been writing latex files in VSCode. I wanted to write something in Bangla. I used Avro Phonetic to write Bengali. But, when I try to do that it starts writing in English. I can write Bengali with that keyboard anywhere else. ex: হেলো। But, if I try to write the same in VSCode it just writes "HelO" instead of "হেলো".

I have searched for many solutions online. But, I have found none that could solve my problem. Because, there's hardly any need  to write Bengali in VSCode by Bengali developer. So, I had to open an issue here.

Steps to Reproduce:

1. Open VSCode and open a writable file.
2. Press super+space change to bn input source.
3. Try write something in Bengali.

**Comment by alexdima** [comment]
@AAShakil50 Does this work when using a native `<input>`, like for example typing in the input of the find widget (`Ctrl+F`) ?

**Comment by AAShakil50** [comment]
No. It does not work in the Find input either. I have tried also in other inputs like, search, command pallete, new_file. Everywhere it types in English instead of Bengali.

**Comment by alexdima** [comment]
@AAShakil50 Are you using VS Code as a snap package? Does IME work when downloading the `.tar.gz` variant from https://code.visualstudio.com/#alt-downloads?

**Comment by AAShakil50** [comment]
It works as expected when using .tar.gz. Thank you so much.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/96041
