### ISSUE TITLE
Avoid sync fs calls at ext host startup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16388]
To ensure the `_getOrCreateWorkspaceStoragePath` some sync fs calls happen. We should look into making them async such that other initialisation code can run in parallel.

**Comment by bpasero** [comment]
[`exthost.api.impl`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L450) does a `fs.realPathSync` for each extension on startup of the extension host main.

**Comment by jrieken** [comment]
correct

**Comment by dbaeumer** [comment]
@jrieken Thanks!
