### ISSUE TITLE
Support multi setting of a workspace or a folder

### ISSUE THREAD

**Issue by ZZH-Finzlize** [microsoft/vscode#163816]
Type: <b>Feature Request</b>

Just like "ms-vscode.cpptools", it provides Multi C/C++ configurations, you can select which group you want to use by simple click on GUI, but sometimes we hope to change a lot of vscode settings to fit different development scenes. Such as same project build for Windows platform and Linux platform (in WSL env) using CMake. The path to cmake binary file is different, and some other setting is needed to change, so I have to manually change these setting one-by-one. Now, I`m using multi "*.code-workspace" file to simplify this operation, but it needs close vscode and reopen using another file, still very troublesome. So, I hope there is a new function to implement that operation just like the "multi C/C++ configuration"

This is how the "ms-vscode.cpptools" change a lot of setting

![image](https://user-images.githubusercontent.com/33342565/196110277-cd5715d6-369d-4e47-8f59-f37da3721c7d.png)
![image](https://user-images.githubusercontent.com/33342565/196110222-be65eb30-faa1-4179-9b6f-c2389b473d77.png)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No

**Comment by rzhao271** [comment]
Is this case covered by settings profiles? https://code.visualstudio.com/updates/v1_72#_settings-profiles

**Comment by ZZH-Finzlize** [comment]
Yes, it`s very close, it could solve my problem for now, but it will be better if we could merge different profiles by using "Merge editor" or automatically merge if two profiles have no conflict.

Think about this scene, I install a new extension, and I write some configuration about it, then I want to push these configurations to other profiles. If I have to copy and paste these texts to do it, it will be annoying
