### ISSUE TITLE
StateMainService: Avoid sync fs-calls

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#16387]
The [`StorageService`](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/storage.ts#L22) reads/write from/to disk in a synchronous matter. This happens at startup, meaning creating of other services and the window is blocked by it.

**Comment by jrieken** [comment]
related to #15455

**Comment by joaomoreno** [comment]
This is due to the nature of that service to not return promises in the `get` call.

**Comment by jrieken** [comment]
@joaomoreno Apart from the messed up nature of that service I see a way to improve this: (1) create the service with the data already loaded (before calling its ctor) and (2) perform writes async

**Comment by bpasero** [comment]
The service no longer loads sync via https://github.com/Microsoft/vscode/commit/7024e62d334efdaadd6af69863f84c7dd16cf5f0. The service is still writing sync though, but I am even thinking about maybe dropping the service in favour of our new storage service.
