### ISSUE TITLE
API: Changing cursor position after edit creates selection

### ISSUE THREAD

**Issue by roman01la** [Microsoft/vscode#16389]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra 10.12.1

Steps to Reproduce:

1. Call the following code in `workspace.onDidChangeTextDocument` handler
```js
editor.edit((edit) => {
  edit.replace(
    new Range(new Position(startRow, 0), new Position(endRow, 0)),
    text);

  const cursor = editor.selection.active;
  const nextCursor = cursor.with(cursor.line, result.cursorX);
  editor.selection = new Selection(nextCursor, nextCursor);
}, {
  undoStopAfter: false,
  undoStopBefore: false
});
```

2. Instead of just changing cursor position it creates a selection starting with a new cursor position to the end of the line.

**Comment by jrieken** [comment]
The `edit`-call returns a promise. When that resolves you can set the selection otherwise you interfere with the edit itself
