### ISSUE TITLE
No longer suggest the Python extension when opening notebook files 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode#163850]
We're looking into no longer installing the Jupyter extension by default when the Python extension is installed. 

Once that starts happening, the flow of opening a notebook when neither the extensions are installed would be the following: 
Open notebook -> See notification "Python extension is recommended" -> Click to install the Python extension -> Close extension page -> Write/edit notebook cell -> Run cell -> See prompt to install a Kernel -> Click to install -> Run cell again 

It would probably be better if either no suggest notification would be displayed (given Python + Jupyter are already recommended when trying to run a cell or select a kernel from a notebook file), or the notification directed users to both Python + Jupyter extensions.  To that end a Jupyter+Python extension pack would probably be beneficial 

cc @brettcannon @minsa110

**Comment by rebornix** [comment]
Let's verify this once we have more updates from Python extension next month.

**Comment by rzhao271** [comment]
I confirmed that no notification comes up when I open a notebook and have neither extension installed. When I run a cell, one suggestion is to install both Python and Jupyter extensions. Then, I try running the cell again, and the kernel picker shows up for me to pick a kernel. :+1:
