### ISSUE TITLE
No auto update for VSCode user installer.

### ISSUE THREAD

**Issue by StephaneAdeso** [microsoft/vscode#163871]
- VS Code Version: 1.72.2
- OS Version: windows 11 x64 21H2

At work, for security reasons, they don't let me install the VSCode System installer, so I had to install the User installer version. 
What surprises me is that it doesn't notify me when there are new versions. There is also no option in the "help" menu to check manually. I have reinstalled vscode 3 times by downloading it again from the web and the updates still don't work. How can that be solved?

PS: Updates for plugins work without problem.

![Code_wPsFyTHJLk](https://user-images.githubusercontent.com/55595063/196241744-16328f24-dd52-470d-859a-5cdd32bc5065.png)

**Comment by gjsjohnmurray** [comment]
Did you use "Run as Administrator" when you installed from the user installer kit?

**Comment by gjsjohnmurray** [comment]
Or maybe you are launching VS Code with "Run as Administrator"?

**Comment by StephaneAdeso** [comment]
hi. no, i didn't use "run as administrator" anywhere.

**Comment by joaomoreno** [comment]
Can you show the Output view, switch to the `Log (Main)` output and show me the contents?

**Comment by StephaneAdeso** [comment]
there you have: 
![image](https://user-images.githubusercontent.com/55595063/196468503-08a1b25b-24fa-43d8-a4b6-077d878d2e91.png)

**Comment by StephaneAdeso** [comment]
The option of "run as administrator"is unchecked and still have no update option. I even restarted the computer: 
![image](https://user-images.githubusercontent.com/55595063/196482154-96c553c5-b509-4c60-9549-6de859c259f7.png)

**Comment by gjsjohnmurray** [comment]
Please review this setting too:

![image](https://user-images.githubusercontent.com/6726799/196606860-deeefabd-a8c3-451c-a704-f6062d3b4f32.png)

**Comment by StephaneAdeso** [comment]
Nope. The option is unchecked. 
![image](https://user-images.githubusercontent.com/55595063/196609236-b7fa220f-e925-4dc8-84e5-0a4421caade4.png)

**Comment by gjsjohnmurray** [comment]
Instead of launching VS Code from a click please close any VS Code windows, open a regular Windows command prompt (make sure its title bar does not include the word Administrator). Then type `code`

If the title of the VS Code window that opens still mentions Administrator please consult your IT support people to discover why apps you launch normally are getting elevated.

**Comment by StephaneAdeso** [comment]
just did it. Still the same.

![image](https://user-images.githubusercontent.com/55595063/196613827-b4914836-d776-42e1-aaeb-bf73a7ccd304.png)

**Comment by gjsjohnmurray** [comment]
That latest screenshot doesn't include the VS Code title bar. Did it still indicate Administrator there?

**Comment by StephaneAdeso** [comment]
yes. It still indicate administrator.

**Comment by StephaneAdeso** [comment]
To help those who have run into the same problem as me, tell them that the problem I had was that the UAC was disabled. As soon as I enabled it, VSCode stopped booting in admin mode.
![image](https://user-images.githubusercontent.com/55595063/197800535-0eadcaf8-887b-4559-92a3-609e2b32825f.png)
