### ISSUE TITLE
Indicate whether an extension created the terminal in `terminal.creationOptions`

### ISSUE THREAD

**Issue by karrtikr** [microsoft/vscode#163873]
When a new terminal is opened, Python extension sends a bunch of activation commands to activate the terminal. In case when other extensions created the terminal using the API, in those cases extension should not be sending the command. See these issues:

- 100+ upvotes in Remote release: https://github.com/microsoft/vscode-remote-release/issues/1760
- Julia extension: https://github.com/microsoft/vscode-python/issues/20017 @rodsrodolfo
- https://github.com/microsoft/vscode-python/issues/9503

Currently there's no way for the Python ext to know that, so this is recognized as a bug.

**Comment by meganrogge** [comment]
We are worried about extension terminals to which activation events should apply getting excluded from these . for example, terminal extensions which manage layout. Python wouldn't activate in those. 

Have you thought about how to deal with that sort of case?

**Comment by karrtikr** [comment]
Hmm, I guess if there was a way to indicate whether an extension owns a terminal when creating it, such extensions can use that. But I think by default Python extension should not be interfering with terminals created by other extensions.

Although, changing default behavior can always be tricky.

**Comment by meganrogge** [comment]
We could consider exposing the `extensionOwnerId` of the terminal and keep the default behavior so as to not break things  but allow you to filter out known problem extension terminals, such as julia

**Comment by karrtikr** [comment]
That could work as well but I think that changing default here (not send commands) could serve us better long term. That is, instead of consumers keeping track of problematic extensions, the extension itself could indicate in create options whether it owns the terminal.

**Comment by MateusGarciaRodolfo** [comment]
Wouldn't the most intuitive behavior be the extension sending commands to open a terminal only when "Python: Create Terminal" is called by the user?

**Comment by Tyriar** [comment]
We actually had a discussion about this and the result was that the Python team would investigate a little more and probably leverage the environment variable collection to mixin environment variables to all terminals in order to activate environments. That would prevent the somewhat annoying activate sourcing from happening. I'm going to close this off for now.
