### ISSUE TITLE
Automatic Formatting is using 4 spaces instead of what I set it to use

### ISSUE THREAD

**Issue by Lazzu** [Microsoft/vscode#16386]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|githistory|donjayamanne|0.1.2|
|Theme-azure|gerane|0.0.2|
|theme-chrome-devtools-dark|ivanzusko|0.0.1|
|omnisharp|ms-vscode|0.3.3|
|better-merge|pprice|0.3.0|
|vscode-icons|robertohuertasm|4.0.4|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|gitblame|waderyan|1.3.0|
|unity-snippets|YclepticStudios|0.1.2|

---

Steps to Reproduce:

1. Set indentation formatting to be 2 spaces, no tabs. My config below:

"editor.tabSize": 2,
"editor.insertSpaces": true,
"editor.formatOnType": false,
"editor.formatOnSave": true

2. Automatic formatting is still using 4 spaces

**Comment by mrmlnc** [comment]
Language?

**Comment by Lazzu** [comment]
C#

**Comment by mrmlnc** [comment]
Is a random problem? 

I ask because we have same problem with JS/TS (#15316).

**Comment by Lazzu** [comment]
I haven't noticed it being random.

**Comment by chrmarti** [comment]
@waderyan @jrieken Could this be a more general issue than just with JS/TS? (#15316)

**Comment by jrieken** [comment]
re https://github.com/Microsoft/vscode/issues/16386#issuecomment-264553165 - I don't think so

**Comment by chrmarti** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1015
