### ISSUE TITLE
A  shortcoming of grammar color displaying in typescript

### ISSUE THREAD

**Issue by BirdLeeSCUT** [Microsoft/vscode#16385]
- VSCode Version: 1.7.2
- OS Version: Windows 10 x64

Steps to Reproduce:
There is a shortcoming of grammar color displaying in typescript, as follow:

![image](https://cloud.githubusercontent.com/assets/10753131/20834783/ffd37fd0-b8d1-11e6-868f-3560d1abfb9a.png)

```typescript
 interface Itest {
	a: 'a1' // a1 is good
		| 'a2' // a2 is good
		| 'a3' // a3 is good
	b: {
		a: 'a1'
			| 'a2' // oh , the color is not good !
			| 'a3' // oh , the color is not good !
	}
}
```
Sometimes we want to give clear indication of  the meanings of every items of  String Literal Types in inline comment, so we would break String Literal Types into many lines.

**Comment by mjbvz** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#376
