### ISSUE TITLE
"View: Toggle Output" sometimes needs to be run twice to hide the Output

### ISSUE THREAD

**Issue by ivan** [microsoft/vscode#163801]
Does this issue occur when all extensions are disabled?: I think this is a vscode issue because it handles display of the Output window, but I don't know how to test this with `Visual Studio Code Remote - SSH` disabled.

- VS Code Version: 1.72.2
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Start vscode with a bunch of `Visual Studio Code Remote - SSH` windows that cause Output to appear during the SSH setup.
2. Run "View: Toggle Output" or press ctrl+shift+u
3. Observe that you have to run it twice to make the Output window go away the first time.

**Comment by sandy081** [comment]
Yes this is as designed for all bottom panels. First time, it focuses the panel and the second time it hides.
