### ISSUE TITLE
Checkbox is hard to see in dark mode on selected file change node in tree view

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#163881]
With default Dark+ theme:

![image](https://user-images.githubusercontent.com/30305945/195920050-6be34592-d140-4bbd-85b6-eb0d1417400d.png)

**Comment by cooleditphoto** [comment]
Hi, I want to work on this, and I think src/vs/workbench/browser/parts/views/treeView.ts is the file that needs to be changed, could you please advise on this? Thanks! @alexr00
