### ISSUE TITLE
Avoid fs.sync calls in renderer and extension host

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16382]
We should try to avoid sync fs calls where possible because they just block code execution until finished. We typically never had sync fs calls in the renderer but now I am seeing more and more of them, also in the extension host:

* [`SnippetsTracker`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/snippets/electron-browser/snippetsTracker.ts#L40)
* [`Terminal`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/execution/electron-browser/terminal.ts#L10)
* [`Emmet`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/actions/base64.ts#L39)
* [`cli.contribution`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/cli/electron-browser/cli.contribution.ts#L41)
* [`ExtensionHostMain`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostMain.ts#L73)
* [`Main`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/main.ts#L119)
* [`exthost.api.impl`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHost.api.impl.ts#L450)

**Comment by jrieken** [comment]
I have filed individual issues for each - close this as dupe
