### ISSUE TITLE
New File in Right-Click Menu in Explorer when clicking inside folders

### ISSUE THREAD

**Issue by muchisx** [microsoft/vscode#163884]
Hi, currently, when you click inside a folder in the Explorer you only get relevant options to the file you clicked, but I often think it would be much nicer to have a New File option in there aswell, instead of having to go all the way up to the folder and make sure you are selecting the right folder and then click the New File button.

It could instead just let you add a File in the context where you right clicked!

Currently there is a New File in the Right Click menu but only on the root, if you try right clicking in a folder you will never see it.

**Comment by gjsjohnmurray** [comment]
If the Explorer selection is a file in a folder, simply clicking the New File button in the Explorer title will begin creating a new file in the same folder as the selected file.

**Comment by muchisx** [comment]
> If the Explorer selection is a file in a folder, simply clicking the New File button in the Explorer title will begin creating a new file in the same folder as the selected file.

Yep! Exactly as I said, you gotta select the folder which is extra steps!
This feature requests eliminates those extra steps

**Comment by gjsjohnmurray** [comment]
You don't have to select the folder. You can select any file in the folder, similar to what you would do if the context menu of files had the New File item you are asking for.

**Comment by muchisx** [comment]
> You don't have to select the folder. You can select any file in the folder, similar to what you would do if the context menu of files had the New File item you are asking for.

True! But selecting a file also opens it, which is most of the times not what we intent to do when selecting a context for a New File. I think we're discussing here two implementations which are fine but can also live together! Same behavior as Windows Explorer, you got your New Folder button that creates a folder in your current context and also a New Folder button in the right click menu inside the context you clicked on, the suggestion I'm making is not new

**Comment by gjsjohnmurray** [comment]
Previously requested in #60798 which was closed as an extension candidate. Adding items to everyone's context menus tends to be unpopular.

**Comment by muchisx** [comment]
> Previously requested in #60798 which was closed as an extension candidate. Adding items to everyone's context menus tends to be unpopular.

I don't really see a New File option in the right click menu as unpopular or bloat, I'd go as far as to say that is costumary.

**Comment by lramos15** [comment]
Sorry going to close this as extension candidate again. 

We currently have
- The command palette
- Keybindings
- The button

And this design follows both Windows and Mac explorer behavior when right clicking on a file.

**Comment by muchisx** [comment]
@lramos15 but not the behavior of windows when you click inside a folder in between files, I still think it's normal behavior.

**Anyways**, for anyone looking for a solution there is this extension, does the job!
https://marketplace.visualstudio.com/items?itemName=wenfangdu.faster-new

**Comment by lramos15** [comment]
Glad you found an extension!

We don't really have any empty space within folders to keep the explorer fast. Empty space such as at the very bottom has `New File..`
