### ISSUE TITLE
HTML Emmet abbreviation doesn't work.

### ISSUE THREAD

**Issue by Gamerique** [microsoft/vscode#163960]
Type: <b>Bug</b>

In my vscode html emmet abbreviations stop working from tomorrow even i installed different extensions for that, please give me a solution to fix this issue.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM)2 Duo CPU     T6400  @ 2.00GHz (2 x 1995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.05GB free)|
|Process Argv|--crash-reporter-id af300f92-674c-446c-bc88-c10b19fba6fe|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
django-html|bib|1.3.0
django-import-libraries|Dha|0.0.4
vscode-html-css|ecm|1.13.1
code-runner|for|0.11.8
gc-excelviewer|Gra|4.2.56
python|ms-|2022.16.1
LiveServer|rit|5.7.9
django-snippets|Sid|0.0.4
html-to-css-autocompletion|sol|1.1.2

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30573243

```

</details>

**Comment by rzhao271** [comment]
Can you share a screenshot or screencap of the issue?

**Comment by Gamerique** [comment]
Thanks for your help, but actually that issue was solved. That issue was happening because of Django, but I figured it and solved. And thanks again!!
