### ISSUE TITLE
Zen mode doesn't hide viewlet

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16396]
* normal mode
* open search viewlet, search for something in your current editor
* notice it's highlighted in orange
* enter zen mode
* 🐛 the orange highlight is still there

**Comment by isidorn** [comment]
@jrieken you would expect the orange highlight to be not be in the editor when you enter zen mode?
But this is the same behavior if you just hide the sidebar - there is still an orange highlight in the editor. Why do you think that zen mode needs to be a special case?

**Comment by bpasero** [comment]
@isidorn something is odd, for me search highlight removes when I hide the search viewlet. though it does not go away when entering zen mode...

**Comment by isidorn** [comment]
@bpasero yes @jrieken demonstrated this to me. The issue is that the toggleZenMode sets its state and simple calls layout - bypassing the sidebarPart.hideActiveViewlet that is done [here](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/workbench.ts#L696)

**Comment by bpasero** [comment]
@isidorn that is not good because it also means that the active viewlet does not get to know it is being hidden. what is the reason to not call the APIs properly?
