### ISSUE TITLE
snippets didn't effect for golang

### ISSUE THREAD

**Issue by jianboy** [microsoft/vscode#163930]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 

Version: 1.71.0
Commit: 784b0177c56c607789f9638da7b6bf3230d47a8c
Date: 2022-09-01T07:36:10.600Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No

Steps to Reproduce:

go.json
```
{
	"println": {
		"prefix": "print",
		"body": "println(\"Hello, Go+\")",
		"description": "(goplus) println()."
	}
}
```
1. when I type "pri", it cannot alert windows with 'println("hello Go+")' 

![image](https://user-images.githubusercontent.com/11532015/196425993-155efc2f-5622-4bbc-bd4d-3983acb046d5.png)

**Comment by jrieken** [comment]
This works for me. Please try F1 > Insert Snippet and see if the snippet is being shown there. If so, check your `"editor.quickSuggestions"`-setting and see if you have actually enabled

**Comment by jianboy** [comment]
1、F1 > Insert Snippet

it works.

2、editor.quickSuggestions

it is enabled.

3、but, only when I type string in *.go files. It didn't work.


https://user-images.githubusercontent.com/11532015/196575625-fb4b3bcb-2056-4818-a3e3-54ec161d9e1f.mp4

**Comment by jrieken** [comment]
The recording of the settings editor shows "modified elsewhere". Please get to the bottom of that

**Comment by jianboy** [comment]
Thank you very much.
