### ISSUE TITLE
Rendered completion items are limited to the previous completion item count

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#163966]
* do a `.` completion
* observe that 2 elements are shown
* choose a suggestion using `Tab`
* paste a piece of code
* press `.`
* observe that only 2 suggestions are shown instead of 6-7
* if the first suggestion shows 1 element, the second suggestion will be limited also to 1 element
* closing the suggest widget and retriggering shows all results

https://user-images.githubusercontent.com/5047891/196536162-cf4d88ee-e55d-46fb-aa1b-a0bd939b93c7.mp4

**Comment by jrieken** [comment]
I can reproduce
