### ISSUE TITLE
Remove `?` dropdown from command center 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#163957]
Given that we now have this option in the Command Center..

<img width="659" alt="CleanShot 2022-10-18 at 10 54 58@2x" src="https://user-images.githubusercontent.com/25163139/196507748-44896545-25f0-409f-b5fa-98af7d0ce83d.png">

I think it makes sense to remove this arrow button. It's misleading as it looks like the affordance to open the command center (i.e. what would open the new "home" state), not provide a shortcut to the `?` menu.

<img width="738" alt="CleanShot 2022-10-18 at 10 54 51@2x" src="https://user-images.githubusercontent.com/25163139/196507737-3202c697-79b5-4d47-b7cc-9db125ec6e8d.png">

cc @jrieken

**Comment by jrieken** [comment]
Just learned about these new options. 🎉 very cool!

**Comment by TylerLeonhardt** [comment]
Verification: no `v` button in the command center anymore.
