### ISSUE TITLE
WorkspaceConfigurationService - Folder remove setting from all targets

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#163901]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=189401&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=a0dd9636-50d2-5f8a-f17f-6bcaa254d802

```
The followings tests are failing:
 - WorkspaceConfigurationService - Folder remove setting from all targets (reason: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.)

```

**Comment by sandy081** [comment]
I do not find any reason for this test to timeout unless there is a system issue.
