### ISSUE TITLE
Uninstalled text overlaps verified icon

### ISSUE THREAD

**Issue by jewlexx** [microsoft/vscode#163986]
Type: <b>Bug</b>

1. Find an installed extension that is published by a verified author
2. Uninstalled said extension and the *✓ Uninstalled* text will be overlapping the verified symbol, in the left hand extension panel as shown below

![image](https://user-images.githubusercontent.com/61040004/196608146-850379b1-6def-4535-b4eb-25696702d3c1.png)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 2700X Eight-Core Processor          (16 x 4100)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (2.40GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Arch/home/juliette/dev/missedyouxd --remote=wsl+Arch --crash-reporter-id b58a4437-5795-4dfe-b518-f3244bf7f773|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (108)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
better-comments|aar|3.0.2
flutter-snippets|ale|3.0.0
ng-template|Ang|14.2.0
astro-vscode|ast|0.27.0
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.2
ccs-flutter-color|cir|1.0.2
vscode-css-modules|cli|0.4.2
gitignore|cod|0.9.0
vscode-github-actions|csc|0.24.2
csharpier-vscode|csh|1.3.5
arm|dan|1.7.4
dart-code|Dar|3.50.0
flutter|Dar|3.50.0
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
vscode-deno|den|3.13.2
githistory|don|0.6.19
xml|Dot|2.5.1
vscode-wasm|dts|1.3.1
rust-syntax|dus|0.6.1
gitlens|eam|13.0.2
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.8
auto-complete-tag|for|0.1.0
codespaces|Git|1.11.1
copilot|Git|1.53.7011
remotehub|Git|0.44.0
vscode-pull-request-github|Git|0.52.0
vscode-flutter-files|gor|4.4.1
todo-tree|Gru|0.0.219
vue-snippets|hol|1.0.4
discord-vscode|icr|5.8.0
sort-package|jam|1.0.0
vscode-devaffirmations|jam|1.1.5
better-cpp-syntax|jef|1.16.1
angular-essentials|joh|13.0.0
Angular2|joh|13.0.0
vscode-peacock|joh|4.2.2
rust-doc-viewer|JSc|3.0.4
rust-flash-snippets|lor|2.0.1
flutter-tree|mar|1.0.0
vscode-language-babel|mgm|0.0.36
xml-format|mik|1.1.3
dotenv|mik|1.0.1
vscode-filesize|mkx|3.1.0
inline-fold|moa|0.1.10
vscode-docker|ms-|1.22.2
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
powershell|ms-|2022.8.5
remote-repositories|ms-|0.22.0
autotrim|Nat|1.0.6
color-highlight|nau|2.5.0
gremlins|nho|0.26.0
angular-console|nrw|17.23.3
vscode-versionlens|pfl|1.0.10
material-icon-theme|PKi|4.21.0
quicktype|qui|12.0.46
fabric8-analytics|red|0.3.6
java|red|1.11.0
vscode-xml|red|0.21.2022062916
vscode-yaml|red|1.10.1
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1248
vue-vscode-snippets|sdr|3.1.1
crates|ser|0.5.10
js-jsx-snippets|sky|11.0.0
code-spell-checker|str|2.10.1
vscode-styled-components|sty|1.7.5
svelte-vscode|sve|106.2.0
sass-indented|syl|1.8.22
tauri-vscode|tau|0.2.0
shellcheck|tim|0.23.1
vscode-status-bar-format-toggle|tom|3.1.1
pdf|tom|1.2.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28
vscode-gradle|vsc|3.12.5
vscode-maven|vsc|0.39.0
volar|Vue|1.0.8
vscode-wakatime|Wak|20.0.0
browserslist|web|1.1.0
vscode-import-cost|wix|3.3.0
change-case|wma|1.0.0
JavaScriptSnippets|xab|1.8.0
vscode-folder-size|xia|0.1.0
rust-mod-generator|Zha|1.0.10
material-theme|zhu|3.15.6
html-css-class-completion|Zig|1.20.0
linkerscript|Zix|1.0.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by sandy081** [comment]
Yah we have real estate issues in the extensions view. We are planning to redesign this by moving actions to the next line. There is already an issue opened for this.
