### ISSUE TITLE
Type in an invisible cell in edit mode, it goes to command mode

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode#163943]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

When trying to type in a cell (in edit mode for sure), but the cell is invisible, it automatically goes into command mode.

Typing to an invisible cell is common: 
- user pastes many lines of code at the end of a cell;
- user scrolls to check other part of the notebook.

This can be dangerous as user may hit `d` multiple times while typing, so cells are deleted.

The expected behavior is: when cell is invisible while in edit mode,  typing should let notebook jump back to make it visible and it's kept in edit mode.

### VS Code Version

1.72.2

### Jupyter Extension Version

2022.9.1202862440

### Jupyter logs

```shell
(no special log for this issue)
```

### Running Jupyter locally or remotely?

Local

**Comment by roblourens** [comment]
As far as I know, this would only affect when the cell itself is scrolled out of the viewport. This case

> user pastes many lines of code at the end of a cell;

when the cursor is out of the viewport but the cell itself is still rendered, should be fine.

**Comment by yuuuxt** [comment]
> 

In fact, it's not fine: cell will be out of view, too.

I created this issue because I just deleted 2 cells by accident as I described.

**Comment by yuuuxt** [comment]
Also, IMAO I don't agree it's a feature request, this behaviour can confuse user and cause loss of data; hope you can reconsider its priority. :)

**Comment by rebornix** [comment]
I agree it's actually a bug, when the previous focus is in the cell out of viewport, users would expect typing can bring the cell into view, or at least just typing instead of running keybindings in command mode.

**Comment by SRooke** [comment]
I am having problems with this aspect of the Jupyter extension also, I have luckily only deleted cells a couple of times. 

With a fix underway, are there any suggested workaround settings that could perhaps at least mitigate the entering of command mode from an newly unrendered cell?

**Comment by rebornix** [comment]
This is fixed in main and will be available in next Insiders (tomorrow) and the next Stable.
