### ISSUE TITLE
Some user shortcuts not working

### ISSUE THREAD

**Issue by Cerzal** [microsoft/vscode#163917]
Type: <b>Bug</b>

I've changed the keyboard shortcut to work tabline. But when I press ALT+/ nothing happens.
My command from keybindings.json file:

        "key": "alt+/",
        "command": "tabnine.accept-inline-suggestion",
        "when": "tabnine.in-inline-suggestions && tabnine.inline-suggestion:enabled || tabnine.in-inline-suggestions && tabnine.snippet-suggestion:enabled"
    }

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.18363
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3394)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (11.06GB free)|
|Process Argv|--crash-reporter-id a263cb14-62db-410c-8dfd-c9c976eca6f8|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
vscode-install-vsix|fab|1.4.0
intellij-idea-keybindings|k--|1.5.4
vscode-language-pack-ru|MS-|1.72.10120958
csharp|ms-|1.25.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
jupyter|ms-|2022.9.1202862440
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
tabnine-vscode|Tab|3.6.15
vscode-icons|vsc|12.0.0
material-theme|zhu|3.15.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by gjsjohnmurray** [comment]
/causedByExtension

Please raise this with the tabnine extension developer. If they think it is being caused by a VS Code fault they should open an issue here to explain what is happening.

**Comment by Cerzal** [comment]
https://marketplace.visualstudio.com/items?itemName=TabNine.tabnine-vscode
