### ISSUE TITLE
Create EditorAction wrappers for column selection commands

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16393]
![image](https://cloud.githubusercontent.com/assets/172399/20825527/e884525e-b864-11e6-9633-6b056ddfe115.png)

**Comment by alexandrudima** [comment]
@egamma I'm sorry this slipped

**Comment by egamma** [comment]
@alexandrudima this one is not critical enough for November, shifting to January.

**Comment by vferko** [comment]
Can we have column selections similar to Sublime using `shift + rmb` or `middle mouse button`?
https://www.sublimetext.com/docs/2/column_selection.html

**Comment by alexandrudima** [comment]
To keep the number of issues in our inbox at a manageable level, we're closing issues that have been on the backlog for a long time but haven't gained traction: we look at the number of votes the issue has received and the number of duplicate issues filed. Thank you for your time and understanding.

If you disagree and feel that this issue is crucial: we're happy to listen and to reconsider.

**Comment by ackvf** [comment]
Should a new issue be raised in this case?
