### ISSUE TITLE
Current file in Problems windows is not synchronized with current tab after Problems windows opened

### ISSUE THREAD

**Issue by EugeneZelenko** [microsoft/vscode#163905]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: Ubuntu 18.04

Steps to Reproduce:

1. Open multiple tabs with source code that have many issues that make Problems list long.
2.  Open Problems windows. In my case file from currently selected tab is not at the top of visible problems.

Workaround is ti switch to another tab and then return back: Problems window will be properly synchronized.

**Comment by sandy081** [comment]
@EugeneZelenko Can you please check if you are able to reproduce this issue with the latest release? If so please share all steps to reproduce including the code snippet file on which problems are generated. It will make it easier for me to reproduce and diagnose.

Thanks
