### ISSUE TITLE
Viewing the list of symbols in the current script file does show variables within a function

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/vscode#16398]
- VSCode Version: 1.7.2
- OS Version: 10.0.14393

Steps to Reproduce:

1. Open a ps1 file made up of just one function
2. Issue CTRL + P
3. Enter @ symbol
4. Only thing listed is the function name, none of the variables are showing.
5. Remove the function name and brackets (`function {}`) and then repeat.
6. You will now see the variables listed.
7. Open a file with multiple functions and the same thing, none of the variables will be listed.

![vscode_symbollistmissingvariables](https://cloud.githubusercontent.com/assets/11204251/20844939/00cb8a4e-b888-11e6-8c46-ecd15081c05b.gif)

**Comment by chrmarti** [comment]
This issue was moved to PowerShell/vscode-powershell#356
