### ISSUE TITLE
Integrated Terminal Not Able to Find bash.exe

### ISSUE THREAD

**Issue by raldridge11** [Microsoft/vscode#16390]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: None

|Extension|Author|Version|
|---|---|---|

---

Steps to Reproduce:

1. Install "Bash on Ubuntu on Windows"
2. Install "VS Code", no changes to user settings (i.e. uses default settings)
3. Open "VS Code" and open an integrated terminal
4. Type "bash" in terminal 
   - will get error saying bash is not recognized
5. Navigate to bash.exe location (C:\Windows\system32)
6. type "bash" in terminal
   - will get error saying bash is not recognized
7. type "dir ba*", get no listing for bash.exe even though it exists
![vscode_no_bash](https://cloud.githubusercontent.com/assets/24261413/20839759/c5eba956-b87b-11e6-924c-fd839dc1c073.PNG)

**Comment by Tyriar** [comment]
@raldridge11 is bash.exe present in `c:\windows\syswow64`?

**Comment by raldridge11** [comment]
@Tyriar, no it is only in `c:\windows\system32`.

**Comment by Tyriar** [comment]
What is the output if you go back to regular cmd.exe (not inside bash) and checkt he dir? I do know there is some weirdness with the way that bash works, `bash` for example is a special command that cmd.exe knows how to handle. For the integrated terminal you need to run the executable directly.

**Comment by raldridge11** [comment]
Exactly what I would suspect, "dir ba*" finds bash.exe.

![vscode_no_bash2](https://cloud.githubusercontent.com/assets/24261413/20901907/bf6ed646-bb02-11e6-882c-a97eb9a96d23.PNG)

**Comment by Tyriar** [comment]
@raldridge11 does launching work if you add either of these to your settings.json?

```
"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"
```

```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\bash.exe"
```

**Comment by raldridge11** [comment]
@Tyriar, the first option, `"terminal.integrated.shell.windows": "C:\\Windows\\sysnative\\bash.exe"` works. The second option causes an error to return "Error: The terminal process terminated with exit code: 1".

However, it would be nice to have the ability to go back and forth between bash and cmd without having to edit the settings.json file.

**Comment by Tyriar** [comment]
I agree, this is not an issue with VS Code though as we just pipe data to and from cmd. I recommend creating an issue at https://github.com/Microsoft/BashOnWindows
