### ISSUE TITLE
automaticaly gone to save file section

### ISSUE THREAD

**Issue by varundasG** [microsoft/vscode#163946]
Type: <b>Bug</b>

when iam take new text file and type some letter it automaticaly gone to the save section n times how manny letters we typing 

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics          (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.31GB free)|
|Process Argv|-n --crash-reporter-id 4eccd64f-7c83-4ebc-b5ea-4c293bad9da5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
save-typing|akh|0.1.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
flow-for-vscode|flo|2.2.0
code-runner|for|0.11.8
c-cpp-runner|fra|4.1.2
vscode-pull-request-github|Git|0.50.0
classic-asp|ili|0.0.4
better-cpp-syntax|jef|1.16.1
vscode-language-babel|mgm|0.0.36
vscode-edge-devtools|ms-|2.1.1
python|ms-|2022.16.1
jupyter|ms-|2022.9.1202862440
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
live-server|ms-|0.4.3
vsliveshare|ms-|1.0.5735
vsliveshare-audio|ms-|0.1.91
vscode-react-native|msj|1.9.3
live-server-preview|neg|0.1.4
prettier-vscode-with-tabs|pas|1.1.0
java|red|1.11.0
LiveServer|rit|5.7.9
vscode-css-custom-properties|Toc|0.0.5
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
php-debug|xde|1.29.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by meganrogge** [comment]
not sure what you mean. pls upload a gif
