### ISSUE TITLE
Snippet completion sorting is wrong

### ISSUE THREAD

**Issue by jdneo** [microsoft/vscode#163923]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.73.0-insider (user setup)
Commit: 6455bf1608dfa1b955717f66295f0f9200db0f73
Date: 2022-10-17T05:17:12.448Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Steps to Reproduce:

1. Use the code: https://github.com/jdneo/vscode-extension-samples/commit/c5e384ce819695dce93102e33cc9db877d550a52
2. Make sure the setting `editor.snippetSuggestions` is set to `inline`
3. The item `for` is listed at top, while it should be expected to list under `error`.
![image](https://user-images.githubusercontent.com/6193897/196373600-5bfc24f7-6d59-422f-9691-53d96a5edd0a.png)

If removing the code:

```js
item.insertText = "for (const iterator of object) {}";
item.range = range;
item.filterText = "console.for";
```

The behavior becomes normal.

**Comment by jdneo** [comment]
Not quite sure but looks like it's related with the test edit's range of the returned completion item. @jrieken Could you confirm that?

**Comment by jrieken** [comment]
Yes, it definitely depends on the range that is provided

**Comment by jdneo** [comment]
I'm working on the postfix support in Java. In one word: `"hi!".sysout` -> `System.out.println("hi!");`

So, I have to construct a text edit to replace `"hi!".`. The range of the text edit makes the completion item always at the top of the list no matter how I set the sort text, which is annoying.

Is there any way that I can customize the location in the list in this case?

**Comment by jrieken** [comment]
> Is there any way that I can customize the location in the list in this case?

Only via range, sort text, and filter text

**Comment by jdneo** [comment]
It will be great if VS Code can have some kinds of mechanism to better support the ranking issue with the postfix completion.

Since for a postfix completion, its range has to include the tokens before the trigger character. And thus, filter text is needed as well to make the completion appear in the completion list.

Therefore, no matter how I set the sort text, the postfix completion will always list at the top - For some cases, this behavior is annoying.

**Comment by jdneo** [comment]
Update:

I finally got a solution. Instead of directly using a text edit to do a replacement, I split the replacement to `insert` + `delete`.

The insert part is addressed by `insertText`. And another additional text edit is used to delete the code.

By doing this, we can leave filter text empty. VS Code will fall back to use default word matching.
