### ISSUE TITLE
Titlebar toolbars missing gap between icon buttons 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#163948]
We use a 4px gap between icon buttons most/all toolbars other than the titlebar:

## Current state

<img width="135" alt="CleanShot 2022-10-18 at 09 36 29@2x" src="https://user-images.githubusercontent.com/25163139/196490846-cf6d8092-0f13-4126-a157-a433ce96c865.png">

## Prior art

<img width="260" alt="CleanShot 2022-10-18 at 09 36 44@2x" src="https://user-images.githubusercontent.com/25163139/196490903-c9869369-9dc5-4db4-9c74-f4f8583174ba.png">

<img width="250" alt="CleanShot 2022-10-18 at 09 39 19@2x" src="https://user-images.githubusercontent.com/25163139/196491188-1f1bc546-1ae3-4416-b4df-3439b5902d70.png">

## Example with gap

<img width="152" alt="CleanShot 2022-10-18 at 09 36 14@2x" src="https://user-images.githubusercontent.com/25163139/196490923-3bef51da-f1d4-4ee9-bf75-fa2bb973d215.png">

**Comment by sbatten** [comment]
Seems the panel global actions don't have the padding either 
<img width="64" alt="image" src="https://user-images.githubusercontent.com/6561887/196503755-793286cf-5fc1-43ed-8a8a-01bee6791147.png">

**Comment by daviddossett** [comment]
Yeah just noticed that as well. I think they should. Or at least there should be a POV over toolbars with padding vs. those that don't.

**Comment by sbatten** [comment]
Yea I think the command center actions as well (arrows) do not have this padding. My concern is that the padding in the titlebar looks very spread out and it is already so crowded
