### ISSUE TITLE
Strange symbols in the "files.eol" pop-up menu

### ISSUE THREAD

**Issue by mrmlnc** [Microsoft/vscode#16395]
- VSCode Version: Code - Insiders 1.8.0-insider (daa71ca002722c2778dc30bba151d7316e3c5e54, 2016-12-02T07:10:46.278Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-less|mrmlnc|0.6.0|
|vscode-scss|mrmlnc|0.6.0|

---

Steps to Reproduce:

1. `File` -> `Preferences` -> `User Settings`
2. Use search field in the `Default Settings` tab for string: `eol`
3. Click on the option icon 
4. Look at pop-up menu

    ![image](https://cloud.githubusercontent.com/assets/7034281/20840718/3ac9de82-b8c2-11e6-875b-757108f4c9a0.png)

**Comment by sandy081** [comment]
Thanks for reporting. Will take a look
