### ISSUE TITLE
Moving tabs from side to bottom without requiring atleast one tab

### ISSUE THREAD

**Issue by bullgom** [microsoft/vscode#163996]
This could be a bug.

Context:
I wanted to move the "run & debug" from side to bottom. But vs-code won't let me do that.
Next thing I tried: Move all tabs within "run & debug" e.g. ("variable", "call stack") from side to bottom.
Then, I noticed that vs-code won't allow me to move the one last tab. Not dependent on what kind of tab it is.
So, I had to take another unused tab e.g. "python environments" and put it in "run & debug" so that I can move all the desired tabs to the bottom. Haha, R.I.P. "python environments" tab :DDD.

Desired Feature:
Let us move the entire tab "run & debug" into the bottom.

Thank you for your work

**Comment by roblourens** [comment]
Some sidebar viewlets currently can't be moved to the panel because they have some custom UI that isn't supported to be moved- here it's the dropdown and debugtoolbar in the viewlet header. There is an issue tracking this, I can't find it at the moment.
