### ISSUE TITLE
Help -> Check for Updates is not displayed

### ISSUE THREAD

**Issue by ymasuoka** [microsoft/vscode#163984]
Type: <b>Bug</b>

Settings -> User -> Application -> Update -> Mode
to default
Help → Check for updates
is not displayed

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.90GB (9.24GB free)|
|Process Argv|--crash-reporter-id b4c47620-901a-43cc-8904-5cb2c9ce7f72 --crash-reporter-id b4c47620-901a-43cc-8904-5cb2c9ce7f72 --crash-reporter-id b4c47620-901a-43cc-8904-5cb2c9ce7f72|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
flutter-snippets|ale|3.0.0
browse-lite|ant|0.3.0
vite|ant|0.2.5
vscode-django|bat|1.10.0
npm-intellisense|chr|1.4.2
regex|chr|0.4.0
doxdocgen|csc|1.4.0
vue-peek|dar|1.0.2
dart-code|Dar|3.50.0
flutter|Dar|3.50.0
vscode-eslint|dba|2.2.6
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.9.0
vscode-todo-plus|fab|4.18.4
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
vue-snippets|hol|1.0.4
path-autocomplete|ion|1.22.1
better-cpp-syntax|jef|1.16.1
rainbow-csv|mec|3.2.0
vscode-duplicate|mrm|1.2.1
vscode-docker|ms-|1.22.2
vscode-language-pack-ja|MS-|1.72.10120948
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
vuejs-extension-pack|mub|1.9.0
awesome-flutter-snippets|Nas|3.0.3
vscode-vue2-snippets|Nic|1.1.1
autodocstring|njp|0.6.1
vetur|oct|0.36.0
open-html-in-browser|pea|2.1.9
material-icon-theme|PKi|4.21.0
LiveServer|rit|5.7.9
vue-vscode-snippets|sdr|3.1.1
trailing-spaces|sha|0.4.1
vue-docs|tit|1.0.2
cmake|twx|0.0.17
errorlens|use|3.6.0
intellicode-api-usage-examples|Vis|0.2.5
vscodeintellicode|Vis|1.2.28
volar|Vue|1.0.8
vscode-typescript-vue-plugin|Vue|1.0.8
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
local-history|xyz|1.8.1
vitest-explorer|Zix|0.2.32

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by gjsjohnmurray** [comment]
Does any of the advice in #163871 help?

**Comment by ymasuoka** [comment]
Thank you

When I unchecked "Run as administrator" in the shortcut, "Check for updates" was displayed

**Comment by jovibor** [comment]
Excuse me, but how should the "Run as Admin" option and "Check for updates" menu existence be related from the User perspective? Where is any correlation here?🤐
I'm absolutely sure these kind of questions will rise again and again in this repo.

**That's a pure stupidity in the App design.**

If you, for some reasons, unable to update the App in Admin mode, say it to the User **_explicitly_**, don't hide the menu!! forcing users to search internet for unobvious solutions.
