### ISSUE TITLE
Big problem with running and debugging

### ISSUE THREAD

**Issue by Yavko21** [microsoft/vscode#164031]
Type: <b>Bug</b>

Good afternoon! I have this problem for a week. I have a ready written code/programm and everytime I have to click on "Run without debugging/ Start debugging" nothing comes up in the debug console. Without seeing the results of my work I cannot know if I do the things properly. I have this problem for first time and I have used Visual Studio Code for month or two but have never faced such a problem! I cannot debug, or see literally anything on the debug console. I have the lastest version of this programm, there are not any mistakes in the code...
I beg you to help me!
Thank you for the attention!
Have a great rest of the day!

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 5300U with Radeon Graphics          (8 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.33GB (2.86GB free)|
|Process Argv|--crash-reporter-id 25f5e494-c117-40d8-af63-efc51e06b60f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.9.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30573243

```

</details>

**Comment by gjsjohnmurray** [comment]
What language?
