### ISSUE TITLE
NODE_OPTIONS environment variable value does not propagate to VS Code

### ISSUE THREAD

**Issue by MarkKharitonov** [microsoft/vscode#164090]
Type: <b>Bug</b>

NODE_OPTIONS is present in the global environment, but absent in the VS Code process environment. Well, it is there, but with the empty value.

Here is the process environment captured with the Process Explorer as opposed to the global environment. All the variables are there in VS Code, except for `NODE_OPTIONS`.

![image](https://user-images.githubusercontent.com/489792/196825191-cc3c991f-8534-4504-b494-8df2a7c1f580.png)

I also asked the question here - https://stackoverflow.com/questions/74103663/node-options-environment-variable-value-does-not-propagate-to-vs-code

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.76GB (18.31GB free)|
|Process Argv|--crash-reporter-id d7143f0e-0d93-4e58-9ab2-8ee6c205c051|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-test-explorer|hbe|2.21.1
azure-pipelines|ms-|1.208.0
vscode-docker|ms-|1.22.2
csharp|ms-|1.25.0
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
azure-account|ms-|0.11.2
powershell|ms-|2022.8.5
test-adapter-converter|ms-|0.1.6
vs-keybindings|ms-|0.2.1
pester-test|psp|2022.3.3
vscode-yaml|red|1.10.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
40g7c324:30573242

```

</details>

**Comment by deepak1556** [comment]
This is a limitation from the runtime, only the following `NODE_OPTIONS` are supported https://github.com/electron/electron/blob/main/docs/api/environment-variables.md#node_options
