### ISSUE TITLE
PR #154300 breaks customised HISTFILE usage (integrated shell, zsh)

### ISSUE THREAD

**Issue by proea** [microsoft/vscode#164025]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: macOS Monterey 12.5

Steps to Reproduce:

1. Configure custom HISTFILE (example custom HISTFILE per project)
2. Load integrated terminal (zsh) in VS code
3. HISTFILE will be /Users/`<user>`/.zsh_history instead of custom history file
What i use:
vscode settings.json:
```
    "terminal.integrated.env.osx": {
      "WORKSPACE_HISTFILE": "true",
      "SHELL": "/bin/zsh",
    },
```

~/.zshrc
```
if [[ "${WORKSPACE_HISTFILE:-false}" == "true" ]]; then
  history_file="${HOME}/.zsh_history_files/.zsh_history_${PWD//\//_}"
  echo ">>> Loading Workspace History File [$history_file]"

  export HISTFILE=$history_file
  fc -W
fi
```

I found that the changes made to break the ability to use a custom HISTFILE because the HISTFILE is always overwritten by these changes: 
https://github.com/microsoft/vscode/pull/154300/files#diff-b5f144ca334c56807b1af2c57851271f3c7af88fed7a4287a2627c46ebb97d05R25-R27

**Comment by t-fritsch** [comment]
Trying to set HISTFILE directly in settings, fails the same way 
```json
{
	"terminal.integrated.env.osx": {
		"HISTFILE": "${workspaceFolder}/.vscode/.zsh_history"
	}
}
```

HISTFILE is always set to `/Users/xxxx/.zsh_history`

**Comment by MonadChains** [comment]
Hi @proea, @t-fritsch, @meganrogge 
I have opened a PR with a possible solution to this issue. Let me know, if it solves the problem.

**Comment by t-fritsch** [comment]
thanks a lot @MonadChains 🙏 

Sorry for the stupid question, but do you have any macos silicon build that I could try ? I never contributed to vscode and finding how to compile it from source may take some time

**Comment by MonadChains** [comment]
Unfortunately, I don't have a Mac, however, I use Linux with Zsh so I could reproduce the bug and I could test the fix on it.

**Comment by tisba** [comment]
I think this might be related to [an issue](https://github.com/cantino/mcfly/issues/273) with McFly.
