### ISSUE TITLE
Provide a setting to use the SSH "Open File or Folder" UI instead of the native "Open" window

### ISSUE THREAD

**Issue by RoyTinker** [microsoft/vscode#164078]
On macOS, "File > Open" (or cmd+O) brings up the native file browser.

But I much prefer the file browser that appears when using the "Remote - SSH" extension:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/984080/196811815-e48e0516-ed44-4b5a-8a18-74fcac986013.png">

I would love if there could be a setting to prefer this Open window ☝️  when working locally - it's a lot faster and has better keyboard support than the native Open window.

The `bodil.file-browser` extension looks promising, but it's broken for opening a local folder (try pressing Enter once you've navigated to the folder you want to open).

**Comment by alexr00** [comment]
Glad to hear you like the simple file picker! There is a setting to enable this: `"files.simpleDialog.enable": true`

**Comment by RoyTinker** [comment]
Thanks so much @alexr00!!
