### ISSUE TITLE
The Explorer font weight is too thin

### ISSUE THREAD

**Issue by yaegar** [microsoft/vscode#164016]
![image](https://user-images.githubusercontent.com/12856549/196684799-656d0831-ac07-4073-b9f9-2d0f1cf50d49.png)

1. The Explorer font weight is too thin
2. You can compare Fleet
3. Can the explorer font be customized

**Comment by roblourens** [comment]
I wonder if you're commenting on the workbench font family/size or just the colors?

**Comment by yaegar** [comment]
> I wonder if you're commenting on the workbench font family/size or just the colors?

fontFamily

**Comment by lramos15** [comment]
\duplicate #519
