### ISSUE TITLE
Why is spread operator marked as error?

### ISSUE THREAD

**Issue by mattiamanzati** [Microsoft/vscode#1640]
Is it unsupported? Have I to switch some jsconfig.json flag?

Thanks for any help!

![image](https://cloud.githubusercontent.com/assets/13787614/11996710/44b59b38-aa69-11e5-92ea-f685f579d021.png)

**Comment by jrieken** [comment]
That's a syntax error because no property name is given (not shorthand, not dynamic naming)

**Comment by jpierson** [comment]
Not sure if I understand your explanation @jrieken, the syntax that @mattiamanzati looks correct to me for newer versions of EcmaScript.

**Comment by mattiamanzati** [comment]
Don't know if it's a ES2015 standard or something like ES2016, but babel transpile it atm.
http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=var%20a%20%3D%20%7Ba%3A%201%2C%20b%3A%202%2C%20e%3A%204%7D%3B%0Avar%20b%20%3D%20%7Bc%3A%203%2C%20f%3A5%7D%3B%0Aconsole.log(%7B...a%2C%20...b%7D)%3B
