### ISSUE TITLE
SCM input does not clear after merging 

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#164083]
I'm often merging main into a branch when resolving conflicts and this input content and validation styling is left behind even after the merge is finished:

<img width="316" alt="CleanShot 2022-10-19 at 15 44 01@2x" src="https://user-images.githubusercontent.com/25163139/196818457-018d10e0-3749-4926-85f3-d6e6daa40523.png">

**Comment by lszomoru** [comment]
I am optimistically closing this issue as I have refactored the code that clears the commit input field following a commit. Please reopen if you still repro.
