### ISSUE TITLE
Extensions: appending command to key binding

### ISSUE THREAD

**Issue by apazureck** [Microsoft/vscode#16402]
VSCode Version 1.7

Hello,

I cannot find any documentation on that topic:

I would like to append a command to a key binding. Using the keybindings contribution of my extension seems to override the default command binding. I would like to implement a go to definition command (f12), which should be fired after the original at best (or if it fails).

```
"keybindings": [ {
        "command": "ui5ts.GoToDefinition",
        "key": "f12",
        "when": "editorTextFocus"
}, ... ]
```

Is the default behavior to override the key binding when adding a keybindings contribution? I read they are executed from "bottom to top", so I guess my command is executed first. Is the rest not fired, if my "when" is called first?

See also:
http://stackoverflow.com/questions/40927851/appending-a-command-to-a-already-existing-keybinding

**Comment by chrmarti** [comment]
You could register a DefinitionProvider to do that. (See vscode.d.ts or https://code.visualstudio.com/Docs/extensionAPI/vscode-api.)

**Comment by apazureck** [comment]
ok, thanks, that really makes more sense.
