### ISSUE TITLE
Explore lazy code loading

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#164068]
As VS Code has grown larger and more featureful, so does the main bundle size that increases the time it takes to load/parse/compile the JS linearly. This isn't an issue for anything not in main bundle (shared proc, exthost, ptyhost, built-in extensions, etc.), but code for features like the terminal, tasks and the welcome page are all loaded in even if they are not used yet.

We have had various discussions about this in the past which I don't think are documented anywhere. Here are some of the things discussed and a brain dump of other thoughts on the topic:

- Moving off AMD (to ESM? https://github.com/microsoft/vscode/issues/160416) is probably the long term solution to this problem, but it's a large and difficult multi-month project
- We have not yet measured the actual impact of reducing bundle size, the current assumption is that it will reduce this compile block on startup relative to the percentage of code removed from the bundle
  ![image](https://user-images.githubusercontent.com/2193314/196791088-68aad0a1-456b-46f5-8712-7f0a5491cc98.png)
  The section after will reduce some, but I believe that is the code that is run in the top level which is mostly registering contributions which will need to remain in the main bundle.
- It will be a win if all we're doing is moving non-critical features for the editor to function to `LifecyclePhase.Eventually` as it will speed up startup
- Code splitting can be achieved manually by using a technique like in [tyriar/code_splitting](https://github.com/microsoft/vscode/tree/tyriar/code_splitting), but that's a lot of overhead put on the component author.
  - This would ideally be all handled for us by the bundler so we can keep the DX of auto importing and not worrying about what code is included in what bundle as it will inevitably cause problems.
  - Importing code could be prevented by lint rules, but there's still the overhead problem.
- It makes sense to target editor and workbench contribs are candidates for code splitting, they also typically have some well defined dependencies (eg. tasks depends on terminal, not the other way)
- xterm.js uses TypeScript projects as a way to make totally separate components of a project even stricter, this is an option we could use if we wanted more strictness around contrib dependencies. Currently this is handled by eslint, to prevent layers going in the wrong direction (`common/` cannot depend on `browser/`) and high level folders (`base/` cannot depend on `platform/`)

**Comment by Tyriar** [comment]
@jrieken and I discussed this last week but I don't think there's much action we can take until https://github.com/microsoft/vscode/issues/160416 is explored more? Let me know if you had other things we should look into for October.

**Comment by jrieken** [comment]
Some simple experiments that I am trying to do in October

* remove all editor-contributions, build, and measure impact on bundle size and load time
* split the main bundle into separate JS files and see if (sequentially) loading smaller files is better or not

**Comment by jrieken** [comment]
> much action we can take until https://github.com/microsoft/vscode/issues/160416 is explored more

Not necessarily. AMD is a dead horse but it can do all of this - the only thing that will be simpler with ESM is tree-shaking on a module-level, e.g identify unused module exports and drop them. We do have a custom bundler which we need to blow the dust off that and maybe re-learn how it works. 

A tricky thing from the past was knowing how to bundle, e.g some modules are used everywhere and those should be in the initial bundle and not be repeated in subsequent bundles. In the past we realised that most things were in the initial bundle and that contributions were super tiny. That's what might us drop the whole approach. However, by now we have plenty more contributions and this might start to pay off.

**Comment by jrieken** [comment]
We are now down the rabbit hole exploring to migrate from AMD to ESM. While this isn't needed to do bundling and lazy code loading we will benefit from being able to reuse existing bundlers (instead of rolling our own AMD-based solution). 

I am snowplowing this for now, if there is urgent need for code splitting: the `keyboardLayouts/layout.contribution`-modules are a sample of how we are doing it already today

**Comment by Tyriar** [comment]
Closing this off for now and track smaller items as they come up.
