### ISSUE TITLE
Auto-import / suggestions not working correctly anymore.

### ISSUE THREAD

**Issue by twoco** [microsoft/vscode#164084]
Since the latest update(s), the autocompletion / suggestions / auto-import / Intellisense does not work correctly. In general it works. But sometimes or more often I get no suggestion. Even if the import already exist. I noticed it when using rxjs or Angular components (material). Angular import like `Injectable` decorator works. At first I thought it's about an export issue of the packages. But I doubt it. It feels like a bug in VSCode.

Does this issue occur when all extensions are disabled?: Yes

Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. Begin to type something you want to import.
2. Wonder why there are no suggestions.

I disabled all extensions and cleared my user settings. Tested it on my private PC and at work. Same behavior. Restarted VSCode after changes, etc.

It seems that it doesn't matter if the import (path) already exists.

![auto-import-suggestions-bug](https://user-images.githubusercontent.com/53160891/196818226-8e28fd01-4099-4fb6-83d9-dbfa7d835c8a.gif)

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by twoco** [comment]
Yes

Version: 1.73.0-insider
Commit: 266ff5b78fc4a128994194e828e55b2bbeb0acbe
Date: 2022-10-20T05:19:08.669Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

(No extensions. fresh installation.)

**Comment by twoco** [comment]
I also notice that the suggestions are behaving strangely in general. For example, if you type after the period (`.` dot), the properties sometimes don't appear. Instead other stuff is displayed. I have to start over and over again to finally have the right suggestions. It's like starting a chainsaw or mower. Another weird behavior is that the theme rendering randomizes the colors (incorrect rendering). I have to scroll to fix it. But this is maybe not related. Perhabs it's an async issue? For example a missing await, etc? Let me know if you need more info. ...

**Comment by twoco** [comment]
A gentle request for updates? Am I alone with this issue? Weird, I tested it across different PCs and projects. Always with a fresh installation of insider version and with extension disabled. Any idea?

**Comment by erhardos** [comment]
I have the same issue, all extensions are disabled

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:44:09.336Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.0-23-generic
Sandboxed: No

**Comment by mjbvz** [comment]
@twoco Can you please share an example project that demonstrates the issue?

**Comment by jay-snyder** [comment]
I am also experiencing this issue, specifically with python imports.

It used to be I could start typing `json.` and VSCode would suggest importing the `json` package. This no longer happens, even with the classes, functions, etc in local project modules.

**Comment by twoco** [comment]
@mjbvz Ok, I tried to reproduce this problem successively in a new project (js and ts). I noticed this problem in several web (ts/js) projects with Angular and RxJS. I don't know what Angular Material (components) problem is but it seems that at least RxJS had issues with exports. See [CHANGELOG](https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#700-2021-04-29). Maybe Angular has similar issues. Idk. Updating RxJS fixes this issue, therefore I close this issue. Sorry, I really thought that's a problem of VSCode. I still have issues with VSCode IntelliSense that some entries are not in suggestion list yet and I have to CTRL + SPACE again and again until the expected entries appear. Maybe an async issue. But however, I'll file a new issue when I have more evidence. Or I just rely on it until someone else notices. ... I'm still a bit confused and maybe something related has changed in vscode. Because it worked before. And I'm sure that the IntelliSense have issues since the last version. Feel free to reopen if I miss anything or create a new issue with well reproducible proofs. For Angular devs. Checkout version 14.2 with rxjs 7.5. The Angular Material issue is not clear yet.
