### ISSUE TITLE
Support `extensions.experimental.affinity` in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164048]
We have `extensions.experimental.affinity` which allows to specify that certain extensions should run in a separate extension host

https://github.com/microsoft/vscode/blob/b4e1d3b68704050b7ff6b906c71b243e460bf232/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L367

However currently we only support this for `ExtensionHostKind.LocalProcess`
https://github.com/microsoft/vscode/blob/b4e1d3b68704050b7ff6b906c71b243e460bf232/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L503

https://github.com/microsoft/vscode/blob/b4e1d3b68704050b7ff6b906c71b243e460bf232/src/vs/workbench/services/extensions/common/abstractExtensionService.ts#L449-L453

**Comment by jrieken** [comment]
Reassigning to @joyceerhl who actually did all the great work here 👏
