### ISSUE TITLE
[settingssync] [info] Request failed https://vscode-sync.trafficmanager.net/v1/manifest

### ISSUE THREAD

**Issue by NicolasMonta1807** [microsoft/vscode#164069]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: Windows 11 22H2 Build 22621.674

Steps to Reproduce:

1. Turn on Settings sync
2. Sign in with Microsoft
3. Log shows "Sync started"
4. Request failed: https://vscode-sync.trafficmanager.net/v1/manifest

**Comment by sandy081** [comment]
Can you please share console log and network requests in `F1 > Toggle Shared Process` ?

**Comment by NicolasMonta1807** [comment]
[vscode-app-1666214411415.log](https://github.com/microsoft/vscode/files/9824458/vscode-app-1666214411415.log)

**Comment by TheDeskofBrad** [comment]
To confirm, I just installed vscode on a new Windows install and received the same error in the log when attempting to enable settings sync.

**Comment by RajdeepThakare** [comment]
I am facing the same exact issue, I recently installed VSCode on my Garuda Linux (Arch).

**Comment by Sorayal** [comment]
I have the same problem on Linux Mint 21 / Kernel: 5.15.0-52-generic.

**Comment by wolfboyft** [comment]
Just had the same issue on Ubuntu 22

**Comment by beerdedfellow** [comment]
Same issue on initial login/sync running 1.72.2 on OSX Monterey 12.6

**Comment by DepthTrawler** [comment]
Same issue. This has been happening since last night Eastern Std Time.

**Comment by beerdedfellow** [comment]
This issue has been resolved for me and all my extensions, settings, etc. synced. I test installed an extension on an existing install and it synced to my fresh install within a few minutes.

**Comment by sandy081** [comment]
@Tyriar @lszomoru Could be due to the downtime we saw on the server?

**Comment by lszomoru** [comment]
Yes, I believe that this was related to the issue that we have investigated last week.

**Comment by sandy081** [comment]
Closing this hoping that changes we did recently in the settings sync server fixes these issues. Please try again and if you see errors open a new issue with settings sync logs.

**Comment by wolfboyft** [comment]
Seems to work, thanks
