### ISSUE TITLE
Remove TS's use of MessageOptions.useCustom 

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#164039]
I don't think this should be lumped into the resolvers proposal. The JS/TS extension currently depends on resolvers just for this one property

**Comment by jrieken** [comment]
Unsure, we really don't want anyone to use this and it only exists for complex reconnection explainers. Once such cases are more properly modelled it should go away again

**Comment by jrieken** [comment]
> The JS/TS extension currently depends on resolvers just for this one property

What is JS/TS using this for? The normal modals should really be enough

**Comment by jrieken** [comment]
@mjbvz looked this [usage](https://github.com/microsoft/vscode/blob/7ae2857bf0d9d0e01512c959afb59414dfab40cb/extensions/typescript-language-features/src/typescriptServiceClient.ts#L646) which doesn't seem to justify the use of a custom modal. So, I'd suggest to let TS use a normal modal dialog instead
