### ISSUE TITLE
When searching for text in multiple encoding files, files encoded differently from the encoding set by the 'files.encoding' option are displayed abnormally.

### ISSUE THREAD

**Issue by yuldK** [microsoft/vscode#164121]
- VS Code Version: 1.72.2
- OS Version: Windows 11, build 22000.978

hello.
When searching for text in multiple encoding files, files encoded differently from the encoding set by the 'files.encoding' option are displayed abnormally.

* reproduce:
1. Prepare one UTF8 encoded file and one that is not (in my case, euc-kr) in the workspace.
2. Both files write one symbol and a non-single character (in my case, Hangul '* 가').
3. Search for '* 가' in the workspace.
4. According to the 'files.encoding' option of vscode, the search results for one file are displayed abnormally. (Please refer to case1.png)
![case1](https://user-images.githubusercontent.com/50822237/196912532-bc973ef6-8105-40b4-a591-b0951db1fe52.png)

+) If you search for a file that is displayed abnormally because it is different from the encoding set in 'files.encoding', the file is displayed normally. (Please refer to case2.png)
![case2](https://user-images.githubusercontent.com/50822237/196912537-4d33925d-d2cc-4b1b-9683-24bbb8d6d5fd.png)

* suggestion:
Because the 'files.encoding' option can be overwritten by using a specific extension, if a specific encoding is set for the file extension, it would be good to display the search results based on this in the search.

thank you!

**Comment by andreamah** [comment]
We currently don't support multiple file encodings for global search because we use [ripgrep](https://github.com/BurntSushi/ripgrep), which doesn't infer the file encoding before searching the file. A change would be made upstream before this fix can occur.
