### ISSUE TITLE
Naming items via Explorer interface still fails to claim focus if the application was inactive when the naming was initiated

### ISSUE THREAD

**Issue by slifty** [microsoft/vscode#164170]
- VS Code Version: 1.72.2
- OS Version: MacOS 12.6

Steps to Reproduce:

1. Have VSCode Open, but click into another window (e.g. a terminal or browser)
2. Right click to create / rename a file in the Explorer (without first bringing focus to VSCode)
3. Try to type the name of the file -- you will be typing in your terminal instead.

I appreciate this issue has been raised a dozen times; it has been closed claiming it is a duplicate of a [three year old issue that was marked as wontfix](https://github.com/microsoft/vscode/issues/70966).  This issue is very real and represents my biggest frustration with VSCode; I'm hit with this multiple times per week since I use multiple monitors and often am moving between application contexts.

I beg the team to consider this a real issue that warrants a fix!
<details>

<summary>An example of the issue (click to expand)</summary>

![example](https://user-images.githubusercontent.com/208884/197035275-4f93e9c6-6d09-426c-8c70-14d91119a55a.gif)

</details>

**Comment by slifty** [comment]
Thank you @VSCodeTriageBot -- confirmed this also applies to 1.72.2 (updating the issue to use that version)

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/149818

**Comment by slifty** [comment]
Ah thank you!  (Sorry for missing that one)
