### ISSUE TITLE
VSCode showing conda environment that has been removed

### ISSUE THREAD

**Issue by dropdx** [microsoft/vscode#164186]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: macOS Monterey 12.6

Steps to Reproduce:

1. On a Windows machine I exported a conda environment
2. I then created a conda environment on my Mac using the export
3. I didn't consider the different OS being an issue, but it installed a Windows based Python
4. I then removed the conda environment from my Mac, but it still shows on VSCode
5. It's listed as Python 3.8.5 64-bit ('envs') ~miniconda3/envs/name-of-env (GLOBAL), but that path no longer exists

I haven't found a way to remove this?

**Comment by IllusionMH** [comment]
Looks like issue with Python extension or related to python.

VS Code does not know about this envs unless extension saved this info to some settings. If you don't see it in settings you should report this issue to extension's repo

**Comment by dropdx** [comment]
It seems to be gone now. I had rebooted a few times last week, but it was still there. Maybe some cache was cleared now.
