### ISSUE TITLE
Randomly occurence of SSH passphrase prompts

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#164102]
Type: <b>Bug</b>

I occasionally wake up my machine to find VS Code asking for my SSH passphrase for git. I am usually not entering my passphrase to use git.

<img width="644" alt="image" src="https://user-images.githubusercontent.com/8599/196849540-df727a7f-6237-40aa-b9ac-6ce98f536bda.png">

```
2022-10-19 20:25:59.824 [info] git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Before and after, `fetch` just works fine.

```
022-10-19 19:31:04.962 [info] From github.com:microsoft/vscode-extension-recommender-exploration
 * branch            digitarald/patient-guineafowl -> FETCH_HEAD
```

VS Code version: Code - Insiders 1.73.0-insider (9d3fbb3d9a50055be0a8c6d721625d02c9de492d, 2022-10-19T09:48:31.480Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 7, 7|
|Memory (System)|64.00GB (4.14GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by lszomoru** [comment]
@digitarald, is the repository in question cloned using the SSH URL?
When it occurs, can you check the git output window for the latest git command that is executed?

**Comment by lszomoru** [comment]
Closing as I am unable to repro.
