### ISSUE TITLE
Regression: Ctrl+k passed to Editor with sendKeybindingsToShell: true

### ISSUE THREAD

**Issue by tim-hilt** [microsoft/vscode#164115]
**Does this issue occur when all extensions are disabled?**

Yes

**Observed Behavior**

Setting

``` json
{ "terminal.integrated.sendKeybindingsToShell": true }
```

should send (almost) all keybindings to shell, if the integrated terminal is currently focussed. This works for all shortcuts I use in the shell, except for `ctrl+k`, which deletes everything until the end of the line in Bash/Fish/ZSH. `ctrl+k` is instead sent to the editor and is interpreted as a shortcut-prefix.

I remember using `ctrl+k` with `sendKeybindingsToShell` in a previous version, but it stopped to work in one of the last to upgrades (1.71 or 1.72).

**VS Code Version**

```
~ 
λ code --version
1.72.2
d045a5eda657f4d7b676dedbfa7aab8207f8a075
x64

~ 
λ code-insiders --version
1.72.0-insider
ba515cdbb48470c116884deb6de17981d341ec06
x64
```
**OS Version**

Arch Linux, Kernel `6.0.2-arch1-1`

Steps to Reproduce:

1. set `{ "terminal.integrated.sendKeybindingsToShell": true }` in `settings.json`
2. open code with `code --disable-extensions`
3. Open integrated terminal (tested with bash and fish)
4. type `test`
5. Hit `ctrl+a` (go to beginning of line)
6. Hit `ctrl+k` (kill until end of line)

**Comment by meganrogge** [comment]
Not sure of any changes in this area recently

**Comment by Tyriar** [comment]
Chords are handled separately as all `sendKeybindingsToShell` does is override `commandsToSkipShell`, you should disable them: `"terminal.integrated.allowChords": false` https://code.visualstudio.com/docs/terminal/advanced#_chords

Yes I think this probably did change but it was a while ago. Provided you can disable chords I believe it's working as expected.

**Comment by fathyb** [comment]
I'm also getting this regression even with `allowChords: false`, I fixed it by adding a keyboard binding:
```json
{
  "key": "cmd+k",
  "command": "workbench.action.terminal.clear"
}
```

**Comment by tim-hilt** [comment]
FYI: I didn’t see this issue anymore, after I disabled terminal-keychords.

**Comment by Tyriar** [comment]
@fathyb the issue of cmd+k not working like that is described in https://code.visualstudio.com/docs/terminal/advanced#_macos-clear-screen
