### ISSUE TITLE
Feature request: Allow scroll by page with ctrl+mousewheel combination

### ISSUE THREAD

**Issue by sharwell** [microsoft/vscode#16412]
Currently it is not possible to bind the Ctrl+MouseWheel behavior. I would like to bind Ctrl+MouseWheelUp to the `scrollPageUp` action, and Ctrl+MouseWheelDown to `scrollPageDown`. This is the behavior I'm familiar with for many years from my [Mouse Fast Scroll](https://marketplace.visualstudio.com/items?itemName=SamHarwell.MouseFastScroll) extension.

**Comment by thekalinga** [comment]
`Ctrl+MouseWheelUp` is also associated with increase font size.

**Comment by sharwell** [comment]
@thekalinga This is only true when `editor.mouseWheelZoom` is true (default is false). Obviously I would not use both settings at the same time. 😆 

📝 The extension I referenced actually does two things - it disables the zoom in Visual Studio (enabled by default there) and also enables the scroll-by-page behavior requested here.

**Comment by thekalinga** [comment]
Thanks for the clarification.

**Comment by alexandrudima** [comment]
Related: #3130

**Comment by sharwell** [comment]
@alexandrudima It appears #3130 is indefinitely stalled (its generality led to non-existence). I would like to reopen this more specific issue so in order to resolve it more efficiently. It would be satisfactory for the purposes of this issue if I was able to write an extension to support this binding, even if it meant the binding was hard-coded. Is there a way within an extension to handle the mouse scroll wheel, similar to [`IMouseProcessorProvider`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.text.editor.imouseprocessor.aspx) and [`IMouseProcessor`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.text.editor.imouseprocessor.aspx) from the Visual Studio SDK?

**Comment by Stibbons** [comment]
+1

**Comment by lonix1** [comment]
@sharwell Do you know whether the SDK surfaces that functionality yet?

**Comment by alexandrudima** [comment]
We have implemented this via https://github.com/microsoft/vscode/pull/65072 . Scrolling with the mouse wheel and pressing the Alt/Option modifier will scroll a lot faster.

**Comment by Goodwine** [comment]
I hoped the modifier to be configurable, no? :(
