### ISSUE TITLE
Update Python syntax highlighting grammar

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#164184]
Latest commit is https://github.com/MagicStack/MagicPython/commit/7d0f2b22a5ad8fccbd7341bc7b7a715169283044 .

I'm happy to do the upgrade for https://github.com/microsoft/vscode/blob/main/extensions/python/syntaxes/MagicPython.tmLanguage.json , but it's in JSON while upstream is in TextMate XML. Do we have a tool we typically use to convert from TextMate XML to JSON?

**Comment by alexr00** [comment]
Yep, we have a script (`yarn run update-grammar` from the built in extension directory) and then run the integration tests. I run this during debt week and then on demand when requested. Update incoming.
