### ISSUE TITLE
VS Code cannot breakpoint 3rd party Python code in Jupyter Notebook

### ISSUE THREAD

**Issue by PeterM18** [microsoft/vscode#164178]
One of my main uses for a debugger is to step through parts of new libraries to better understand how they work and how to use them. But, my current install of VS Code refuses to let me set breakpoints or step through 3rd party libraries when I am in Jupyter Notebooks--where almost all my code is. I get a 'Breakpoint in file excluded by filters' error.

I've looked through everything I could find online about this problem, and nothing I've tried has worked. I have:

    In File > Preferences > Settings > Debug turned on 'Allow breakpoints everywhere' for both User and Workspace
    In ... Settings > Extensions > Jupyter turned off 'Debug Just My Code' for both
    In launch.json changed ' "justMyCode": true ' to ' "justMyCode": false '
    After suggestions in https://stackoverflow.com/questions/52980448/how-to-disable-just-my-code-setting-in-vscode-debugger, I tried to add a separate debug configuration to launch.json. This used to do the trick, but ' "request": "test" ' can no longer be used. Various alternatives I've tried here also do not work (e.g. "request": "attach" or "purpose": "debug-test").

If I extract the code from Jupyter Notebook, put it in a .py file, I have no problem stepping through the 3rd party code.  So, there's a filter being applied only when I 'debug cell' in a Jupyter Notebook.  But, as I've mentioned, I've set the 'Debug Just My Code' for jupyter to false in both User and Workspace.  I am at a loss for what other switches I can throw or configuration files I can alter.

**Comment by roblourens** [comment]
Please try in the latest Insiders vscode build, with the latest pre-release Jupyter extension, this was only just implemented https://github.com/microsoft/vscode-jupyter/issues/8146

**Comment by PeterM18** [comment]
Thank you roblourens!

**Comment by PeterM18** [comment]
Hi:  I'm using VSCode as part of the MX Linux repository.  More recent
versions of Code are not tested with MX Linux and would require special
upkeep because updates won't automatically be detected and installed, I
imagine, and add-ons would likely need to be reinstalled.  Because I don't
yet much need to step through 3rd party code and can work around that issue
by extracting NB code into a .py file, which does allow me to step through,
I have not yet sought to fix the problem with a new version of MSCode.
There may come a point where that takes too long.

Peter

**Comment by vickkot** [comment]
@PeterM18 
Thanks for the answer
