### ISSUE TITLE
Settings Sync Fails for GCC-H Microsoft Accounts

### ISSUE THREAD

**Issue by iamstrained** [microsoft/vscode#164145]
Type: <b>Bug</b>

Users who are attempting to use VS Code and GCC-H Microsoft accounts will find that the VS Code application is hard-coded to point users for the Settings Sync feature to Commercial Cloud instead of GCC-H. This causes this feature to fail and throw a log error such as listed below. 

This feature should not be hard-coded to support only Commercial Microsoft accounts and should be expanded/corrected.

Error while turning on Settings Sync. {"error":"invalid_request","error_description":"AADSTS900384: JWT token failed signature validation [Reason - Key was found, but use of the key to verify the signature failed.,

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by TylerLeonhardt** [comment]
merging with https://github.com/microsoft/vscode/issues/162539
