### ISSUE TITLE
ExplorerViewlet triggers two layouts on load

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#164188]
While profiling the startup of VS Code with the open editors view visible, I noticed that the `ExplorerViewletViewsContribution` ends up firing two events about updating view visibility:

![Screen Shot 2022-10-20 at 2 04 55 PM](https://user-images.githubusercontent.com/12821956/197063471-999478f6-e5b4-4d78-9bf6-3b4fd6fc96bf.png)

Each of these takes ~25ms to complete

1. [`registerViews`](https://github.com/microsoft/vscode/blob/36fdf6b697cba431beb6e391b5a8c5f3606975a1/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L56)
2. [`updateOpenEditorsVisibility`](https://github.com/microsoft/vscode/blob/36fdf6b697cba431beb6e391b5a8c5f3606975a1/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L59)

I suspect that the two events can be batched together so that we avoid doing the costly re-layout twice

**Comment by bpasero** [comment]
@isidorn I was looking into this and found the following `OpenEditorsVisibleContext` context key around open editors:

https://github.com/microsoft/vscode/blob/34cba75c513878d683004561c799dd5cd13f5222/src/vs/workbench/contrib/files/common/files.ts#L52

It is `false` by default but then will in most cases immediately be set to `true` based on this:

https://github.com/microsoft/vscode/blob/34cba75c513878d683004561c799dd5cd13f5222/src/vs/workbench/contrib/files/browser/explorerViewlet.ts#L166-L168

Unless a user has `explorer.openEditors.visible` set to `0`, which is not the default. 

To fix this issue I think flipping the default would be sufficient. However, I have general questions around this and maybe you recall: why do we even bother to hide the "Open Editors" view from the right click menu conditionally based on this context key? And isn't the name of the context key misleading? I would assume `openEditorsVisible` is about visibility of the view in the explorer viewlet but not about if I can pick it to show or not.

My 2 cents (without knowing the history of this) is to remove the context key and simply always to show the "Open Editors" view when you select it here but have it hidden by default:

<img width="417" alt="image" src="https://user-images.githubusercontent.com/900690/235317190-38081486-4d77-40b8-8f84-0c6a0bf86493.png">

**Comment by isidorn** [comment]
@bpasero sorry but I do not recall the details. My feeling is that this was done specially for the Open Editors before we had all the nice view visibility mechanisms in VS Code. 
Any change here I am fully supportive off. Thus as you suggest let's remove the context key. And let's change explorer.openEditors.visible to not support 0 👏 
It is hidden by default so we are good.

fyi @lramos15 who now owns the Open Editors view.
