### ISSUE TITLE
Font rendering artifacts on empty state

### ISSUE THREAD

**Issue by jblievremont** [microsoft/vscode#164125]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2 (also 1.73.0-insider)
- OS Version: Ubuntu 22.04.1 LTS

Steps to Reproduce:

1. Open VSCode
2. Close all editor tabs
3. Some elements of keyboard shortcuts box (element with CSS class `watermark-box`) have weird font rendering artifacts - see attached screenshot

I tried to play with the text content and font sizes, the problem seems to be triggered by "some" sequences of characters, and more frequently at smaller font sizes.

![image](https://user-images.githubusercontent.com/1734254/196917379-f3deadb3-1a63-4524-9d65-33b26ac6b232.png)

**Comment by deepak1556** [comment]
Does the issue repro when you run with `--disable-gpu` ?

**Comment by jblievremont** [comment]
With `--disable-gpu`, it seems that the text elements render properly at all sizes.

**Comment by deepak1556** [comment]
Thanks for confirming, this is an upstream issue which might get addressed with future runtime updates. Please continue to disable hardware acceleration in the application as workaround, refs https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration .
