### ISSUE TITLE
vscode stop

### ISSUE THREAD

**Issue by callor** [microsoft/vscode#164163]
Type: <b>Performance Issue</b>

Why are there 12 processes running with vscode running? If you connect remotely and use vscode, then exit the remote and connect again, vscode stops and no key is entered.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.63GB (44.15GB free)|
|Process Argv|--crash-reporter-id a979b64b-a21a-4eea-9f12-4f387fe48392|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    90	 40544	code main
    0	    27	 28988	   crashpad-handler
    0	    90	 29700	   issue-reporter
    0	    39	 37076	   utility-network-service
    0	   120	 39804	   extensionHost
    0	    79	 30484	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Program Files\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=39804
    0	   125	 35648	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Program Files\Microsoft VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=39804
    0	   229	 41020	   window (설정 - JS-2022 - Visual Studio Code)
    0	   105	 41520	   shared-process
    0	    77	 12348	     fileWatcher
    0	    80	 35632	     ptyHost
    0	     8	 39820	       console-window-host (Windows internal process)
    0	     5	 45004	       C:\WINDOWS\System32\cmd.exe
    0	   199	 43684	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (설정 - JS-2022 - Visual Studio Code)
|    Folder (JS-2022): 32 files
|      File types: html(17) js(8) gitignore(1) json(1) md(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
prettier-vscode|esb|9.9.0
vscode-language-pack-ko|MS-|1.72.10121003
material-icon-theme|PKi|4.21.0
LiveServer|rit|5.7.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
vscccc:30566498
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30573243

```

</details>

**Comment by hediet** [comment]
Can you give more details? What is the problem?

**Comment by callor** [comment]
1. Connect to win pc with remote desktop and use vscode
2. Quit remote desktop while running vscode
3. Access the remote desktop again
4. Check the vscode window
5. Keyboard not responding at all.
6. If you restart the process after ending the process in the task manager, it works normally.
7. Same symptoms as tested on two remote desktops

**Comment by callor** [comment]
> Can you give more details? What is the problem?

1. Connect to win pc with remote desktop and use vscode
2. Quit remote desktop while running vscode
3. Access the remote desktop again
4. Check the vscode window
5. Keyboard not responding at all.
6. If you restart the process after ending the process in the task manager, it works normally.
7. Same symptoms as tested on two remote desktops

**Comment by callor** [comment]
> Can you give more details? What is the problem?

Thank you !!!

1. Connect to win pc with remote desktop and use vscode
2. Quit remote desktop while running vscode
3. Access the remote desktop again
4. Check the vscode window
5. Keyboard not responding at all.
6. If you restart the process after ending the process in the task manager, it works normally.
7. Same symptoms as tested on two remote desktops

**Comment by chrmarti** [comment]
Not related to dev containers it seems.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167556
