### ISSUE TITLE
Add Shortcut (.lnk) support in the explorer tab

### ISSUE THREAD

**Issue by marvel-srikant** [microsoft/vscode#164119]
1. When I try to open a `shortcut link` in the explorer tab it's doesn't support.
![Screenshot](https://user-images.githubusercontent.com/52560067/196910124-d8ab9c33-f54f-443c-826b-41daaca341b4.png)
 in the explorer tab it's doesn't support.

**Comment by lramos15** [comment]
Here's an extension that may help! https://marketplace.visualstudio.com/items?itemName=EnkelDigital.open-lnk
