### ISSUE TITLE
"Maximize Panel" terminal button not available in some profiles, even after clearing settings.json

### ISSUE THREAD

**Issue by everdrone** [microsoft/vscode#164107]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.72.2
- OS Version: Windows 10

Steps to Reproduce:

1. The button is just not there anymore
3. Create a new blank settings profile and the button appears

So there must be something wrong with my default settings profile but can't find the settings key to enable the button again. Even after clearing out all the settings.json to an empty object it doesn't work

**Comment by gjsjohnmurray** [comment]
Is #150365 relevant?

**Comment by everdrone** [comment]
Probably!, even though it's set to "Right"
I'll try it on the machine where the issue happens and let you know

Thanks!

**Comment by gjsjohnmurray** [comment]
Maximize is only available when Panel Alignment is Center:

![image](https://user-images.githubusercontent.com/6726799/196884864-be90c46e-0d34-49e0-94f2-7da4a08b5f41.png)

**Comment by everdrone** [comment]
Thank you, it's been bugging me for a long time this solves it!
I'll close the issue then
