### ISSUE TITLE
GDB stepping isn't working right on Ubuntu

### ISSUE THREAD

**Issue by lovettchris** [Microsoft/vscode#16429]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.04

**Steps to Reproduce:**
1. install C++ extension from Microsoft and the Native Debug extension by "webfreak".
2.  setup remote debugging via GDB server of a C++ app compilied by g++ with -ggdb. 
3.  create launch.json file with "type":"gdb", "request":"attach", "remote":"true", with target set to the port that GDB server is listening on.
4. set a breakpoint that you will hit
5. hit the break point and press F10 or click "step over" button on the debug toolbar.

**Expected**: move to next line of code.

**Actual**: every step operation reports and error:
"Source ../sysdeps/unix/sysv/linux/x86_64/cancellation.S is not available."

Clicking step one more time works, but this intermediate error on every step makes debugging rather painful.  I also found step out sometimes doesn't work.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#385
