### ISSUE TITLE
Step-Over Key(alt+f10) doesnt work, as it is a Key that they browser use.

### ISSUE THREAD

**Issue by DimasVeliz** [microsoft/vscode#164236]
STEP-Over Key (alt+F10) does not work.

Hey, I wanted to report, that, when using the C# extension for VSCODE-server, the Alt+F10 key, doesnt work and I need to explicitly click  the step over button with the the mouse, F11 (Step-Into) however does work.

F10 itself, and Fn+F10, Alt+Fn+F10, neither work.

The OS I am using is Ubuntu 22.04, browser info is already written.

Thanks

Version: 1.73.0-insider
Commit: 266ff5b78fc4a128994194e828e55b2bbeb0acbe
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0
Embedder: vscode.dev

**Comment by roblourens** [comment]
This is true of lots of keybindings- You will have to change the browser, or change the keybinding in vscode. Using vscode.dev as a PWA may help.
