### ISSUE TITLE
Keyboard Shortcuts `shift+cmd+\` not work

### ISSUE THREAD

**Issue by A404coder** [microsoft/vscode#164216]
I use `shift+cmd+\` to focus terminal tabs view in work, but i found it doesn't work now.
I didn't change any config of my shortcuts.
this is my default config : 
```
{
  "key": "shift+cmd+\\",
  "command": "workbench.action.terminal.focusTabs",
  "when": "terminalFocus && terminalHasBeenCreated || terminalFocus && terminalProcessSupported || terminalHasBeenCreated && terminalTabsFocus || terminalProcessSupported && terminalTabsFocus"
}

```
I tried to change my key to "shift+cmd+2" or any other, it still doesn't work.
I want to know what the problem is and how to fix it.😭
![image](https://user-images.githubusercontent.com/94605465/197136570-eee1f3e9-afc6-440c-ba6b-e5b7c4efcd2f.png)

**Comment by A404coder** [comment]
this shortcut is work 
```
{
  "key": "shift+cmd+\\",
  "command": "editor.action.jumpToBracket",
  "when": "editorTextFocus"
}
```

**Comment by gjsjohnmurray** [comment]
I suggest you use the information at https://code.visualstudio.com/api/references/when-clause-contexts#inspect-context-keys-utility to try and verify that your when-clause is true when you want it to be.

**Comment by A404coder** [comment]
> I suggest you use the information at https://code.visualstudio.com/api/references/when-clause-contexts#inspect-context-keys-utility to try and verify that your when-clause is true when you want it to be.

well, I've verified the when-clause using this way. I think it is right.

<img width="450" src="https://user-images.githubusercontent.com/94605465/197148852-fe33051b-7a67-4478-b52b-f950e824f12f.jpg"/>

after that, I tried to change the when expression from default to 'terminal.active', A more general condition. It still not works.

<img width="450" src="https://user-images.githubusercontent.com/94605465/197147219-34b182b9-2f26-4408-9818-1402faa31dc7.png"/>

**Comment by freMea** [comment]
One year later the `workbench.action.terminal.focusTabs` still doesn’t work. It’s not a bug with shortcut and when clauses. Just try the command in palette, it fails with no error. If you try with the default shortcut, it fails with an error.

![image](https://user-images.githubusercontent.com/22337329/203820207-e81722e9-f6ee-4675-9fea-ddb6f7f35c2e.png)

**Comment by mrakul** [comment]
Just sharing the behavior I have with that, since I noticed this also some time ago. If it might be helpful.

I didn't change the keybinding for the `workbench.action.terminal.focusTabs` action:
![image](https://user-images.githubusercontent.com/11632548/204387425-9bad577f-1f71-4051-8a04-85861808782f.png)

I check what is happening after pressing `ctrl+shift+\` with _Developer: Toggle Keyboard Shortcuts Troubleshooting_ tool, observing that the command should be invoked, but nothing happens:
![image](https://user-images.githubusercontent.com/11632548/204388392-e7b82cbc-20f9-4baf-98a0-64915fee3ef7.png)

My VSCode version is:
- Version: 1.73.1 (user setup)
- Commit: 6261075646f055b99068d3688932416f2346dd3b
- Date: 2022-11-09T04:27:29.066Z
- Electron: 19.0.17
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No

Thanks, waiting for any info of it as well.

**Comment by Tyriar** [comment]
I can't reproduce on my Windows machine.

**Comment by Tyriar** [comment]
Looks like it's missing from default commands to skip shell:

https://github.com/microsoft/vscode/blob/7b20bd008e5fa5d59d4abd30e9cfef89a301905d/src/vs/workbench/contrib/terminal/common/terminal.ts#L595-L727

Try setting this as a workaround:

```json
"terminal.integrated.commandsToSkipShell": [
    "workbench.action.terminal.focusTabs"
]
```

**Comment by A404coder** [comment]
I try to add this to settings.json and restart VS Code, but it seems still doesn't work. 
I'm not sure if I set correctly, Is there anyone else can fix this problem by this way?
![image](https://user-images.githubusercontent.com/94605465/204735979-a91be01c-c89e-4855-bdd0-2e311b793c40.png)
![image](https://user-images.githubusercontent.com/94605465/204736327-801dd8b3-e321-4630-815d-199d654387b5.png)

**Comment by Tyriar** [comment]
@A404coder just to make sure, you actually have the tabs view up when you try right? With the default settings this needs 2+ terminals. Could you share you settings.json file?

**Comment by A404coder** [comment]
@Tyriar  yep, I opened 2+ terminals.
Sure, this is my settings.json.
Json files are not supported to upload. I converted it to txt.
[settings.txt](https://github.com/microsoft/vscode/files/10124939/settings.txt)

**Comment by Tyriar** [comment]
Nothing sticking out as obvious to me in your settings here. What keyboard layout(s) do you use?

**Comment by Tyriar** [comment]
Pretty sure this is related to keyboard layouts then. @alexdima any advice on how to action this? Was a recent change make to keybinding resolution that could have caused this as reports only started happening from 1.73.

**Comment by mrakul** [comment]
If it may help, concerning layouts, I use two languages (English US and Russian), English layout is standard QWERTY:
![image](https://user-images.githubusercontent.com/11632548/204865123-31ae5a95-c8d2-42f5-8f5e-7bc769069a19.png)
![image](https://user-images.githubusercontent.com/11632548/204865155-18cba5b6-91d9-42c6-a895-6551ab3da754.png)
Software version:
- Version: 1.73.1 (user setup)
- OS: Windows_NT x64 10.0.19044
- Sandboxed: No

Thanks.

**Comment by mmcintyre123** [comment]
Any luck with this yet?

**Comment by imblowfish** [comment]
Hello, just updated VSCode to 1.74 and now this shortcut works fine

**Comment by A404coder** [comment]
👍here is.  https://github.com/microsoft/vscode/pull/164408/
