### ISSUE TITLE
Offer to uninstall extensions even if they are dependencies

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#164210]
Extensions fail to uninstall when they are needed for other extensions.

In this case I clicked a few times to find the right extension to delete first, then the second, then the last:

<img width="552" alt="image" src="https://user-images.githubusercontent.com/8599/197113826-3bb83d2a-6656-434e-b2ef-d71cffe2ddd5.png">

What if we still offer a way to uninstall the whole chain of dependencies `Uninstall dependents as well`.

cc @isidorn

**Comment by isidorn** [comment]
Good idea, ideally the error message contains that button you propose.

**Comment by luabud** [comment]
This happens with the Python one too, especially if you install our tools extensions like pylint, black and flake8. It would be great if we could be offered an option to uninstall all the dependencies.

**Comment by sandy081** [comment]
This is supported now.
