### ISSUE TITLE
how to disable to change matching brackets highlighter

### ISSUE THREAD

**Issue by cybernetics** [Microsoft/vscode#16424]
- VSCode Version: 1.7.2
- OS Version: Win 7 (64-bit)

how to disable or change rectangular matching brackets highlighter. it's really very annoying specially when you have only empty pairs of brackets. is there any setting(s) to disable this or change it to something to look like as in sublime or notepad++.

**Comment by chirag64** [comment]
Hi, I was able to make the necessary changes on my local repository but I'm unable to commit my changes for one of the files `editorCommon.ts`. I think I'm following all the necessary guidelines as per the Contributing guidelines (configuration shown in screenshot).

![vscode](https://cloud.githubusercontent.com/assets/591424/22623881/0565225a-eb90-11e6-9106-ae2e5315f5e4.PNG)

Can someone please help me with this so I can attempt a PR?
