### ISSUE TITLE
Remote tunnel access spawns the wrong path on Insiders

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#164264]
1. Enable remote tunnel access on Insiders
2. Notice it fails. In the logs, it tries to spawn `/Applications/Visual Studio Code - Insiders.app/Contents/Frameworks/Code - Insiders Helper (Renderer).app/Contents/MacOS/bin/code-tunnel-insiders`.

Also in the CLI:

1. Call `code-insiders tunnel`
2. The spawned path is `/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/bin/code-tunnel-insiders`

The actual path for both places should be `/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/bin/code-tunnel-insider`. Note it's also `insider` rather than `insiders` since that's what the quality is set to in the build (we are very inconsistent about this in general 😛 )

**Comment by connor4312** [comment]
Made some tweaks in https://github.com/microsoft/vscode/pull/164285 and https://github.com/microsoft/vscode-distro/pull/502. Not sure what the best way to deal with the path is, however.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/164257

**Comment by aeschli** [comment]
All the executable names and folder names (e.g. data folders) need to come out of `product.json`. No path math or name constructing.
In theory, a product could use a completely different application name, not starting with `code`
