### ISSUE TITLE
Problems loading reference 'https://json.schemastore.org/package'

### ISSUE THREAD

**Issue by WalkAlone0325** [microsoft/vscode#164243]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Darwin arm64 21.6.0

CSS contributions to package.json

Problems loading reference 'https://json.schemastore.org/package': Unable to load schema from 'https://json.schemastore.org/package': Downloading schemas is disabled through setting 'json.schemaDownload.enable'.(768)

**Comment by gjsjohnmurray** [comment]
![image](https://user-images.githubusercontent.com/6726799/197198364-14e6f1e0-5fa3-475f-95bf-41dd51efa631.png)

What does yours look like?

**Comment by WalkAlone0325** [comment]
`"json.schemaDownload.enable"`   true or false will always have this prompt.This method will not work.

**Comment by aeschli** [comment]
I tried this our with the setting, and I checked the code (no recent changes) and can't see issues.

**Comment by ShubhamVsCode** [comment]
Any solution to this
