### ISSUE TITLE
how to reduce caret (or cursor) thickness

### ISSUE THREAD

**Issue by cybernetics** [Microsoft/vscode#16423]
- VSCode Version: 1.7.2
- OS Version: Win7 (64-bit)

How to reduce the thickness of caret (or cursor) to look like as in sublime and/or notepad++. vscode caret is so thick, not as slim and trim as in sublime or notepad++. is there any setting to achieve this effect. currently I've following setting enabled:
"editor.cursorBlinking": "smooth",

**Comment by alefragnani** [comment]
Hi @cybernetics ,

I think this is related to https://github.com/Microsoft/vscode/issues/1929

Hope this helps

**Comment by chrmarti** [comment]
Indeed, tracking with #1929. Thanks.
