### ISSUE TITLE
"Hash mismatch" when updating VS Code Insiders via Help / Update menu

### ISSUE THREAD

**Issue by scovetta** [microsoft/vscode#164278]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.0-insider
- OS Version: 10.0.22623

Additional Details:
```
Version: 1.73.0-insider (user setup)
Commit: 266ff5b78fc4a128994194e828e55b2bbeb0acbe
Date: 2022-10-20T05:19:08.669Z (1 day ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
Sandboxed: Yes
```

Steps to Reproduce:

1. Install VS Code Insiders via winget.
2. Open VS Code Insiders.
3.  Click Help -> Check for Updates
4. Notice an error popup on the bottom left corner saying "Hash mismatch".

```
2022-10-21 11:36:15.122 [info] update#setState idle
2022-10-21 11:36:15.931 [info] UtilityProcess<1>: Creating new...
2022-10-21 11:36:15.943 [info] UtilityProcess<1>: received spawn event.
2022-10-21 11:36:18.967 [info] update#setState checking for updates
2022-10-21 11:36:18.971 [info] update#setState downloading
2022-10-21 11:36:49.898 [error] Error: Hash mismatch
    at R (C:\Users\miscovet\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\code\electron-main\main.js:16:54884)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-10-21 11:36:49.899 [info] update#setState idle
```

I'm not sure if there's a better way to get diagnostics here.

**Comment by rzhao271** [comment]
I just updated and got a notification that says "Hash mismatch". There's no actionable item for the notification, and the error message itself seems vague.

![Hash mismatch notification](https://user-images.githubusercontent.com/7199958/197281433-51414dbe-68a6-41fc-9384-a6879a08e78f.png)

**Comment by camiant** [comment]
solved for me! can you confirm it too?

**Comment by scovetta** [comment]
This is working for me too now.

**Comment by joaomoreno** [comment]
Indeed something went wrong:


```
❯ http https://update.code.visualstudio.com/api/versions/commit:504c5a768a001b2099dd2b44e9dc39e10ccdfb56/win32-x64-user/insider
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: max-age=150
Content-Length: 421
Content-Type: application/json; charset=utf-8
Date: Tue, 25 Oct 2022 08:12:03 GMT
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Powered-By: Express
X-Source-Commit: ae188734df1b5b18531de9bf11c8ebf24ed5e009
request-context: appId=cid-v1:8109e553-6232-492a-afca-b78cea9b431c

{
    "hash": "d1e31a34239d3ec9aeb0afc9c5fcfb31b9d6f4d3",
    "name": "1.73.0-insider",
    "productVersion": "1.73.0-insider",
    "sha256hash": "56364af7c846723f580066eee9c101d8ea57310366253ad58a7554476baec32e",
    "supportsFastUpdate": true,
    "timestamp": 1666329404298,
    "url": "https://az764295.vo.msecnd.net/insider/504c5a768a001b2099dd2b44e9dc39e10ccdfb56/VSCodeUserSetup-x64-1.73.0-insider.exe",
    "version": "504c5a768a001b2099dd2b44e9dc39e10ccdfb56"
}

❯ Get-FileHash C:\Users\jomo\Downloads\VSCodeUserSetup-x64-1.73.0-insider.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          867A127D73C5B06636D589742D07C5AEC71B3385187314891BB1FC8D91C92BE8       C:\Users\jomo\Downloads\VSCodeUserSetup-x64-1.73.0-insider.exe
```

**Comment by joaomoreno** [comment]
Found it. There were two Publish builds on the same commit:

- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=189958
- https://dev.azure.com/monacotools/Monaco/_build/results?buildId=190024

This is a regression from https://github.com/microsoft/vscode/pull/161030.

**Comment by TylerLeonhardt** [comment]
@joaomoreno yeah I like that... or I guess we can see if [this actually ran](https://insiders.vscode.dev/github/microsoft/vscode/blob/418db217614820c7e931bf8b342077cd290529b1/build/azure-pipelines/common/createAsset.ts#L203) (and maybe the Mooncake one?) and if it did then we probably wanna run the sproc?

**Comment by camiant** [comment]
error "Hash mismatch" is back

**Comment by joaomoreno** [comment]
Yup. Confirmed.

Haven't gotten around to fix it, currently on leave. Tomorrow's build should be fine.

**Comment by lllopo** [comment]
Yup - I have it too. It's back.

**Comment by joaomoreno** [comment]
This has been fixed in our storage account.
