### ISSUE TITLE
Comment card: rendering of label action is broken with 1.71

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#164288]
Does this issue occur when all extensions are disabled?: Yes/No

We were using a command under `comments/commentThread/title` to show a label action on the comments card. With the update from 1.70.2 to 1.71.2, the rendering is broken.

Before:
![image](https://user-images.githubusercontent.com/485572/197280280-95aea51c-9fc8-4875-ae8d-9d2d507330f6.png)

After:
![image](https://user-images.githubusercontent.com/485572/197280298-ef3dc4d6-8811-4e9d-98db-addde351011b.png)

The command is defined in the package.json using:

```json
      "comments/commentThread/title": [
        {
          "command": "critique.markDraftResolved",
          "group": "main",
          "when": "commentThread =~ /<draft><unresolved>/"
        },
```

Granted, it's probably not a very used feature, but we found it useful until we can show more buttons in the comments card.

Playing with the Chrome Devtools, I can fix the rendering by commenting the `display: flex;` here (it seems to be the main difference between 1.70 and 1.71):
![image](https://user-images.githubusercontent.com/485572/197281234-1671e5a7-0075-4a09-af3e-cc0c3fe17d10.png)

**Comment by laurentlb** [comment]
cc @alexr00

**Comment by alexr00** [comment]
Looks like this was done to try to fix the size of the button: https://github.com/microsoft/vscode/commit/b77a8910a181e17af4d1f6a77100f5e227ed9f1d

@jrieken was the goal with that change to keep the button the same size as buttons with an icon?
