### ISSUE TITLE
Improve discoverability of Right Arrow action in Quick Open

### ISSUE THREAD

**Issue by eamodio** [Microsoft/vscode#16425]
- VSCode Version: `Version 1.8.0-insider (1.8.0-insider)` daa71ca002722c2778dc30bba151d7316e3c5e54
- OS Version: `macOS Sierra 10.12.1 (16B2555)`

I would be great if from the Quick Open widget you could search for a set of files (package.json, project.json, etc) and either multiselect inside the quick open to open them all at once. Or be able to click on each file individually with a modifier pressed (shift?, alt?) which would open the file (not in preview) and keep the Quick Open widget open so it could be repeated.

I find myself wanting this feature VERY often when dealing with file sets like package.json or project,json, etc, but also with any file pairs -- like code behind, controller/view, etc.

**Comment by alefragnani** [comment]
Hi @eamodio ,

You could use `Right Arrow` (instead of `Return` and `Ctrl+Return`). It will open the selected file and keep the Quick Open still opened.

Hope this helps.

**Comment by eamodio** [comment]
@alefragnani wow -- thanks. I still think it might be worth the above for better discoverability.

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
