### ISSUE TITLE
Can't open settings in dev, after reload

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#164241]
1. Run out of sources
2. <kbd>Ctrl ,</kbd> to open the settings editor

🐛 Settings don't appear, and there are errors in devtools

![image](https://user-images.githubusercontent.com/22350/197188026-3d898555-2e61-42da-a083-df7e4b2d274b.png)

**Comment by rzhao271** [comment]
\closedWith 231d74d
