### ISSUE TITLE
VSCode enables breakpoints ony when explorer view is clicked 

### ISSUE THREAD

**Issue by SWETAS04** [microsoft/vscode#164217]
Type: <b>Bug</b>

Hi ,In our vscode extension we have used this condition to enable breakpoints 
 "breakpoints": [
            {
                "language": "COBOL",
                "when": "resourcePath =~ /\\.c4z(\\\\|/)\\.extsrc/"
            }
			]
Flying over the line in the editor doesn't show the red spot to add or edit breakpoints  .We are able to set the breakpoints only after clicking the Explorer view . 

VS Code version: Code 1.72.2 (

https://user-images.githubusercontent.com/21476353/197139335-3ce1ea5c-cebf-420f-a3fc-f61b8701302e.mp4

d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.71GB (10.76GB free)|
|Process Argv|--crash-reporter-id d133a08a-6622-48f1-a60d-ef44c6e652e3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by roblourens** [comment]
The 'when' clause for breakpoint won't work to enable breakpoints in individual files like that, it's intended for a global condition
