### ISSUE TITLE
"Restart with 4096 MB" does not help

### ISSUE THREAD

**Issue by sim642** [microsoft/vscode#164260]
Type: <b>Bug</b>

While trying to open a large file, I get a memory limit error and the button "Restart with 4096 MB". If I click it, then VSCode restarts and the same file comes up with the exact same error and suggestion.

I'm guessing it actually restarted with 4096 MB, but the file is still too big and thus fails to still open. But in that case the suggestion shouldn't be "Restart with 4096 MB" any more, because it looks like that doesn't work.

It should check that VSCode is already started with that memory limit, so the suggestion makes no sense, and suggest to actually increase the configured limit.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-46-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 6, 7|
|Memory (System)|30.59GB (15.63GB free)|
|Process Argv|. --crash-reporter-id 24f060cb-acb5-4d97-8ff4-c0901728f659 --max-memory=4096 --crash-reporter-id 24f060cb-acb5-4d97-8ff4-c0901728f659|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|xubuntu|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
ide-vscode|daf|2.8.5
xml|Dot|2.5.1
vscode-ghc-simple|dra|0.2.3
gitlens|eam|13.0.3
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.219
ocamlearlybird|hac|1.2.0
cmake-language-support-vscode|jos|0.0.7
language-haskell|jus|3.6.0
intellij-idea-keybindings|k--|1.5.4
rainbow-csv|mec|3.2.0
vscode-docker|ms-|1.22.2
vscode-dotnet-runtime|ms-|1.5.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
sarif-viewer|MS-|3.3.0
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
cmake-tools|ms-|1.12.27
vsliveshare|ms-|1.0.5739
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
ocaml-platform|oca|1.10.7
vscode-commons|red|0.0.6
vscode-xml|red|0.22.0
cmake|twx|0.0.17

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vsccc:30566497
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by baosj0** [comment]
me too, VSCode has problem when opening large files
