### ISSUE TITLE
gulpfile.hygiene on Windows

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#1642]
I'm using Windows with `core.autocrlf=true` which means that files in my working directory have CRLF line endings, but are converted to LF when I commit. But I can't commit because the hygiene check fails because it sees the CRLF endings.

I got around it by converting the file to just use LF, but is there a recommended workflow for Windows environments? Working entirely in LF might work but inevitably some tool won't like that. Maybe hygiene could skip the line ending check if `core.autocrlf=true`?

**Comment by martellaj** [comment]
Can someone speak on this? I attempted to make some commits while at work today (on a PC) and was getting hygiene errors regarding copyright header and bad EOL, but the same commit worked fine on my Mac.

**Comment by joaomoreno** [comment]
Sure, let's tackle this.

**Comment by martellaj** [comment]
Cool. I'm going to investigate when I get to work today. I'll make sure I have my environment set up properly and then send y'all some more context to help with debugging.

**Comment by bgashler1** [comment]
I had the same issue a while back when I was working on a PC.  I had to resort to bypassing git hooks on a stubborn issue even though my Git was configured to normalize line endings.  Thanks for reporting this issue :)

**Comment by joaomoreno** [comment]
EOL checking is now skipped if `core.autocrlf` is set to `true`.

**Comment by roblourens** [comment]
@joaomoreno - The copyright header check fails for me, because the expected header has '\n', and it checks for that exact string. Maybe use '\r\n' when `core.autocrlf` is true, or check for either type with a regex?
