### ISSUE TITLE
Find All References feels unreliable

### ISSUE THREAD

**Issue by xerosugar** [microsoft/vscode#164234]
Type: <b>Bug</b>

If I place the cursor on a class name and run Find All References I'm only shown references to that class within that same file. I expect this command to not only show me references within the same file, but also where the class is defined and all other places in my project where the class if being imported and used. 

Also, if I place the cursor on the class name and run this command (in the file the class is defined in) and don't have the file that uses this class opened, I am not shown the class reference in that file closed anymore, only the line where the class is being defined at (from where I ran the command).

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.19.15-201.fc36.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5750G with Radeon Graphics (16 x 3395)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.14GB (20.24GB free)|
|Process Argv|--unity-launch --crash-reporter-id 60a43f92-093c-479d-9594-8d692eb08608|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
json-tools|eri|1.0.2
vscode-drawio|hed|1.6.4
rest-client|hum|0.25.1
gitblame|wad|9.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903
vscccc:30566498
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243

```

</details>

**Comment by gjsjohnmurray** [comment]
What language? I think the scope of "Find All References" will depend on whether or not there's a [WorkspaceSymbolProvider](https://code.visualstudio.com/api/references/vscode-api#WorkspaceSymbolProvider) for that language. Perhaps you need an extension.

**Comment by xerosugar** [comment]
Javascript

**Comment by mjbvz** [comment]
Try creating a jsconfig so all JS files (even unopened ones) are treated as part of the same project: https://code.visualstudio.com/docs/languages/javascript#_javascript-projects-jsconfigjson
