### ISSUE TITLE
Chinese input method is invalid.

### ISSUE THREAD

**Issue by PerssonBrown** [microsoft/vscode#164311]
Type: <b>Bug</b>

Install VScode in Ubuntu22.04 LTS, create a new file, switch to the Chinese input method to try to input, and find that Chinese cannot be input.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.0.3
vscode-language-pack-zh-hans|MS-|1.72.10121008
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0

(4 theme extensions excluded)

</details>

**Comment by alexdima** [comment]
@PerssonBrown Can you input Chinese in the input of the find widget (ctrl+f) ?

**Comment by yume-chan** [comment]
Snap has a long history of not working with IMEs, not sure the situation now though.

**Comment by alexdima** [comment]
Let's track in #96041 . The workaround is to download the `.tar.gz` from https://code.visualstudio.com/#alt-downloads
