### ISSUE TITLE
Incorrect TextMate syntax highlighting for meta category

### ISSUE THREAD

**Issue by tambry** [Microsoft/vscode#16438]
![image](https://cloud.githubusercontent.com/assets/1827708/20860834/6613dda4-b98a-11e6-8dfa-3914f8df4b68.png)

The names for the parentheses on the first line in the TextMate grammar file are defined as: `meta.keyword.bug.parantheses.[...]` and on the second line broken's metabug's name is defined as `meta.keyword.bug.parameter.metabug`.

On all themes included with Visual Studio Code by default don't specify anything about `meta.keyword[...]`, so it shouldn't be highlighted. (Dark+ theme is being used on the screenshot)

- VSCode Version: 1.7.2
- OS Version: Ubuntu 16.10

Steps to reproduce:
1. Clone [this reproduction sample](https://github.com/tambry/vscode_meta_bug).
2. Open the cloned folder in Visual Studio Code.
3. Press F5 to run the extension in a new instance.
4. Open the `test.metabug` file that's included in the sample's root folder in the new instance running the example syntax support extension.
5. Witness improper syntax highlighting.

**Comment by tambry** [comment]
Decided to investigate a bit.

VSCode seems to add the token's name to the end of the upper-level name. Ie. if `broken(metabug)` as a whole is matched to be `meta.workaround.broken.metabug` and the broken part of it is matched as `keyword.other.broken`, then the token's class will be `meta.workaround.broken.metabug.keyword.other.broken`, instead of what I'd expect to be `keyword.other.broken`. Ie. the behaviour being that the current-level token overrides previous level token's name.  
This might not be whole of the cause, as the CSS matches any token that contains `keyword` in its name somewhere.

How much of this is the expected behaviour?

**Comment by tambry** [comment]
This actually might be related to #16206.

**Comment by alexandrudima** [comment]
@tambry It is exactly caused by how we currently render (using CSS to match the scopes instead of carefully following the TM scope matching rules). Let's track in #16438,

**Comment by tambry** [comment]
@alexandrudima I think you gave the wrong issue ID for the issue that it's being tracked in.

**Comment by alexandrudima** [comment]
@tambry Sorry about that, this is where I suggest to track it: #16206
