### ISSUE TITLE
"Disconnect" icon in toolbar is probably our most ugly icon

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16431]
![image](https://cloud.githubusercontent.com/assets/900690/20857687/44c49ee6-b934-11e6-8b35-fe0c40db5516.png)

Am I the only one that thinks this icon does not fit anywhere in our UI and especially not compared to the other icons in there?

**Comment by nerdybeast** [comment]
This made me literally laugh out loud because it's both true and funny :)

**Comment by isidorn** [comment]
I also fid the icon a bit ugly but I know that @weinand was showing some passion about the semantics of this one (square with a disconnect)
Getting a new icon is perfectly fine by me

**Comment by bpasero** [comment]
Imho there is too much detail in that little space.

**Comment by weinand** [comment]
I only started to show "passion" after a different icon for "Disconnect" (vs. "Terminate") got introduced. This [new icon](https://github.com/Microsoft/vscode/issues/9740#issuecomment-240277801) was looking completely different than "Terminate" and @bpasero [complained about the icon looking "really bad"](https://github.com/Microsoft/vscode/issues/10998).

Anyone interested in this issue should read #10998 because we had this discussion already in August.

**Comment by bpasero** [comment]
Looking at the golden standard of debug UI (VS) I see the same icon being used for disconnecting from an attached debug session as well as stopping:

![image](https://cloud.githubusercontent.com/assets/900690/20881887/ba383c86-bade-11e6-99d0-93446e65f885.png)

Even though there seems to be a "Detach All" action:

![image](https://cloud.githubusercontent.com/assets/900690/20881912/dadef394-bade-11e6-9add-5f4d9181e0b1.png)

**Comment by weinand** [comment]
If we cannot design a convincing icon, then don't introduce one just for the sake of it. I don't think that there is a pressing need...

**Comment by isidorn** [comment]
Fine by me to just use the red stop square in both cases

**Comment by bgashler1** [comment]
We could ask the VS icon team to try making another icon, but I like what you guys are proposing to just use the same icon and be consistent with VS IDE.

**Comment by weinand** [comment]
So then lets use the red-square icon for Disconnect too.

**Comment by fbnlsr** [comment]
Can't we use the Standby symbol which is universally recognized?

https://en.wikipedia.org/wiki/Power_symbol

![iec5009_standby_symbol](https://cloud.githubusercontent.com/assets/1923346/20970254/f1f9a754-bc8c-11e6-9907-d5a14db927cb.png)

**Comment by weinand** [comment]
I do not see how the Standby symbol helps in conveying the semantics of "Disconnect" (vs. "Terminate")?

**Comment by siegebell** [comment]
I like the idea of a plug in a red square. How about a less detailed plug?
![disconnect](https://cloud.githubusercontent.com/assets/16118166/20976010/2655de14-bc6f-11e6-907a-4f5788815e98.png)

**Comment by isidorn** [comment]
@siegebell I actually like this icon. Others?
@joaomoreno ping since I know you are passionate here.

**Comment by weinand** [comment]
@siegebell I like that icon!

**Comment by joaomoreno** [comment]
I don't really care about the icon. Just that it is different than stop.

**Comment by fbnlsr** [comment]
Just to itterate on @siegebell's idea, here's an icon with a complementary color based on the "refresh" icon that is currently in vs code. Definitely not perfect but it's an idea.

![unplugged](https://cloud.githubusercontent.com/assets/1923346/21006660/3255c906-bd3a-11e6-8f47-2e3c87ef22ec.png)

**Comment by isidorn** [comment]
Also not bad. Could somebody provide an SVG since all our icons in debug world are svgs? 
Also for an svg I can easily change colors for different themes.

**Comment by siegebell** [comment]
Here's my source svg: [vscode - disconnect icon.zip](https://github.com/Microsoft/vscode/files/639347/vscode.-.disconnect.icon.zip)
![preview disconnect icon](https://cloud.githubusercontent.com/assets/16118166/21009980/a84ee502-bd17-11e6-8b9a-2e219dd052f0.png)

**Comment by fbnlsr** [comment]
Here's an SVG of the icon I've proposed: https://drive.google.com/file/d/0B0hj0H1Hv6IibDFjclhPa183bUk/view?usp=sharing

**Comment by isidorn** [comment]
@fbnlsr that icon works for us. Can you please provide a PR that is simply adding this icon to the vs/workbench/parts/debug/browser/media 
It would be great if you could do it in the next hour so we make it a part of the november release.

@siegebell also thanks for your svg but this one seems to be converted from a png so it has a much uglier svg form

**Comment by siegebell** [comment]
@fbnlsr did you not download the *.svg I attached? (The *.png is just a preview to put it in context)

**Comment by rkeithhill** [comment]
Did something happen with the Disconnect icon?  In VSCode 1.8.0  the PowerShell extension (0.9.0) was showing this disconnect icon;
![image](https://cloud.githubusercontent.com/assets/5177512/22813676/c100c85c-ef0a-11e6-8d81-a40b7bd8510d.png)
After I upgraded to 1.9.0 (and now 1.9.1), when I attach to a process using the PowerShell debugger, I see just the standard stop button.  Bug or did someone change their mind on using a different icon for `disconnect`?

**Comment by isidorn** [comment]
@rkeithhill no we still use it. If you have nice reproducable steps for how to get into powershell attach mode and the stop icon is showing please file a new issue in this repo and ping me on it.
