### ISSUE TITLE
Python loop syntax highlight. 

### ISSUE THREAD

**Issue by sainthkh** [Microsoft/vscode#1643]
In Python for loop, "in" should be syntax-highlighted. But it is just plain text. 

Example:

for list in lists:
    do_something(list)

"in" in code above should be syntax-highlighed, but it is not.

**Comment by nchammas** [comment]
Probably related to #1467.

**Comment by aeschli** [comment]
The python tokenizer (originating from https://github.com/textmate/python.tmbundle) treats 'in' as an operator. Changing the color of that would impact all other operators like =, +, .... Our default themes render operators white (resp. black) (was gray in November but that was bug)

Sorry, we have no plans to change that for the default themes.
