### ISSUE TITLE
Test: too many folding regions notification

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#164385]
Refs: https://github.com/microsoft/vscode/issues/163428

- [x] anyOS @lramos15
- [x] anyOS @alexr00

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164385%0A%0A&assignees=aeschli)

---

- Configure `"editor.foldingMaximumRegions": 10` with a small limit to test this issue
- Open a file with more than 10 folding ranges. Verify that the language indicator now has a warning
![image](https://user-images.githubusercontent.com/6461412/197402916-2be67eb2-7182-4e29-95a0-df9f60d11464.png)
- test that clicking the link in the notification works
- reduce the number of folding ranges and verify that the warning goes away
- test that this works for any language, including JSON and JSONC.
- use a language specific setting and test that this works as well
```
"[json]" {
    "editor.foldingMaximumRegions": 12
}
```
- test that opening a different file in the same editor correctly updates the indicator
- test with a multi column tab layout and test that setting focus in the different tab column correctly updates
- test that a large output view does no longer trigger a warning of too many ranges

**Comment by alexr00** [comment]
> test that this also works in the output view

How can I cause foldable regions in the Output view? I tried appending a bunch of JSON to an output channel, but that didn't show as foldable.

**Comment by aeschli** [comment]
@alexr00 I improved the wording of the last test bullet point. 
Steps to produce a large output are:
- set `"json.trace.server": "verbose"`
- open some JSON file, do some edits, check the `JSON Language Server` output view.

The output view does not support folding.
There's was bug that folding was computed anyways and the user could get a notification about too many folding ranges.
