### ISSUE TITLE
disabled extension last released date not right

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#164333]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/197344708-7a38aac2-d1d3-4ac2-a822-9fc1804663b3.png">

<img width="1390" alt="image" src="https://user-images.githubusercontent.com/41773861/197344737-776fc6c3-605c-40c0-9a61-03c3a90b84b8.png">

```
Version: 1.73.0-insider (Universal)
Commit: 504c5a768a001b2099dd2b44e9dc39e10ccdfb56
Date: 2022-10-21T05:38:37.339Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: Yes
```

**Comment by sandy081** [comment]
I can't repro it. Do you still see it?

**Comment by tjx666** [comment]
I can still reproduce

**Comment by tjx666** [comment]
> I can't repro it. Do you still see it?

Yes.

**Comment by sandy081** [comment]
I see. Semantics are different when compared to Marketplace. In VS Code, Last updated means when the extension was updated in VS Code. In Marketplace Last updated is when the extension was last published/released. This shall match with Last released timestamp in VS Code.
