### ISSUE TITLE
Terminal doesn't display git 'red dim' color properly

### ISSUE THREAD

**Issue by Ruminateer** [microsoft/vscode#164308]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.72.2 (user setup)
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
```
I am using WSL2 if that makes a difference.

Steps to Reproduce:

1. add custom color scheme to `.gitconfig`.
```
[core]
    pager = perl /usr/share/doc/git/contrib/diff-highlight/diff-highlight | less
[color "diff-highlight"]
    oldNormal = red dim
    oldHighlight = red
    newNormal = green dim
    newHighlight = green
```
`diff-highlight` path might be different on distributions other than Ubuntu, but the problem shall remain with simpler
```
[color "diff"]
    context = red dim
```
2. run some `git diff` with word-level differences.

The terminal displays `green dim` properly but cannot dim red.
![image](https://user-images.githubusercontent.com/31800808/197306317-de1fd0f1-13c8-4992-b849-1fa1d5e500ed.png)

I think the problem is on the vscode side because Windows Terminal can display the colors properly.
![image](https://user-images.githubusercontent.com/31800808/197306438-ca45add2-5f68-48cf-b23b-18429bf755a0.png)

**Comment by yume-chan** [comment]
Another contrast correction issue.

Set `"terminal.integrated.minimumContrastRatio": 1`
