### ISSUE TITLE
Test: Enable Tunnel Access from within VS Code

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#164392]
Refs: #163526

- [x] Windows @karthiknadig
- [x] MacOS @rzhao271
- [x] Linux @alexdima

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164392%0A%0A&assignees=aeschli)

---

Command shave been added to enable a remote tunnel access to your machine

- In the accounts view menu, use the command `Turn on Remote Tunnel Access...`
- This will bring up a quick pick to select an account to sign in
- Once authenticated, there should be a progress notification that shows while the remote access is set up. The progress dialog is a  link that when clicked shows the log.
- When done, a notification should tell you that  Remote Tunnel Access is enabled. The remote tunnel can be access through vscode.dev or from the desktop through the `Remote - Tunnels` extension
- the dialog lets you copy the link to the browser to the clipboard or show the `Remote - Tunnels` extension. Test these.
- Looking at the account menu now, you should see a command `Remote Tunnel Access in On`
- Clicking on it will bring a quick pick that lets you sign out, change the machine name or get more information
- Test that you can change the machine name
- Test that you can access the tunnel from another machine
- Test that when opening a second window, you again see the `Remote Tunnel Access in On`. 
- The connection is managed in the shared process, for all windows. Verify that in the process explorer, there's a child process `code-tunnel-insiders`
- Test that when closing VS Code, also the code-tunnel-insiders process is gone

**Comment by alexdima** [comment]
I'm blocked with testing due to #164570

**Comment by rzhao271** [comment]
This feature is magical 🧙
