### ISSUE TITLE
VSCode doesn't respect "editor.parameterHints.enabled" setting

### ISSUE THREAD

**Issue by westernwontons** [microsoft/vscode#164372]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.73.0-insider
504c5a768a001b2099dd2b44e9dc39e10ccdfb56
arm64

- OS Version:
MacOS Monterey 14.6

Steps to Reproduce:

1. Disable parameter hints, by putting this line into your settings: "editor.parameterHints.enabled" : false
2. Open any file and start typing a function or methods name.
3. Accept a suggestion.

Side note: I've also disabled this on the language level, by having the following line in my settings:
```json
"[rust]": {
    "editor.parameterHints.enabled": false
},
```

Video of it in action:

https://user-images.githubusercontent.com/75550932/197389995-605fab5d-ddd1-424c-ae5b-e3382512e9cc.mov

**Comment by jrieken** [comment]
I believe the setting in only honoured when typing and parameter help can still be invoked via the command. My guess is that the extension (which @westernwontons didn't specify) explicitly triggers parameter help after completion

**Comment by westernwontons** [comment]
> I believe the setting in only honoured when typing and parameter help can still be invoked via the command. My guess is that the extension (which @westernwontons didn't specify) explicitly triggers parameter help after completion

I'm using the `rust-analyzer` VSCode extension. If what you say is true, I'll knock on their door. Thanks for the help!

**Comment by mjbvz** [comment]
Yes run-analyzer needs to respect this setting
