### ISSUE TITLE
Rust's Cargo.lock: The action "Follow link" (ctrl + click) open URL with ending double quote

### ISSUE THREAD

**Issue by mirao** [microsoft/vscode#164342]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Uzip the file [Cargo.zip](https://github.com/microsoft/vscode/files/9844986/Cargo.zip) and open `Cargo.lock` in VSCode (or just copy the text `source = "registry+https://github.com/rust-lang/crates.io-index"` to clipboard and paste it into a new file in VSCode or into a VSCode terminal)

3. Click to the link by `Ctrl + Click` in VSCode editor/terminal

Expected result:

- URL `https://github.com/rust-lang/crates.io-index` is open

Actual result:

- URL `https://github.com/rust-lang/crates.io-index"` is open (invalid URL)
- Problem is in the prefix `registry+` inside the double quoted string. If you use `source = "https://github.com/rust-lang/crates.io-index"`, the link is parsed correctly.

I tested the issue in other applications:

- web preview of GitHub issue
- gnome-terminal
- VIM in gnome-terminal

and the link is parsed as expected everywhere

**Comment by Tyriar** [comment]
This actually works fine for me, it might have been fixed since your report?

![image](https://user-images.githubusercontent.com/2193314/205157543-beb0c405-8a79-44db-87f2-acc763fab095.png)

**Comment by mirao** [comment]
Confirmed that it's working now for me too.
