### ISSUE TITLE
Too much junk in the title bar

### ISSUE THREAD

**Issue by SmokinMac** [microsoft/vscode#164389]
Type: <b>Feature Request</b>

There is so much junk in the title bar -- menu items, search field, window controls, layout toggle buttons -- that it's difficult to find a blank part of the title bar just to drag the window to another part of the screen.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
Please see the `window.commandCenter`, `workbench.layoutControl.enabled` and `workbench.layoutControl.type` settings.

**Comment by SmokinMac** [comment]
This is a good solution!
