### ISSUE TITLE
TS/JS: rejected promise not handled within 1 second

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16432]
- VSCode Version: latest insiders
- OS Version: macOS

Steps to Reproduce:

1. open any TS or JS file

=>

![image](https://cloud.githubusercontent.com/assets/900690/20857731/35b65ed4-b935-11e6-8a60-4e5310359cd9.png)

/cc fyi @dbaeumer (might be TS lint or JS lint update related?) though I also see this when running out of sources without extensions and I only see it since maybe a couple of days.

**Comment by CoenraadS** [comment]
I have also seen this message, it caused my pull request build to fail I think: 

https://travis-ci.org/Microsoft/vscode/jobs/181022070#L2924

**Comment by joaomoreno** [comment]
I just spent 30 minutes thinking this was me, yet I still don't know where it comes from. 😠 

We need two fixes here:

- Fix the rejected promise problem
- Improve this specific error reporting to be able to catch the culprit...

**Comment by jrieken** [comment]
This message means that a promise got rejected and no-one has attached a reject-handler to it.

**Comment by joaomoreno** [comment]
Yeah but where does it come from? Could we somehow do a better job figuring that out?

**Comment by jrieken** [comment]
Come from here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostProcess.ts#L66

**Comment by joaomoreno** [comment]
Yesterday I spent quite some time trying to figure out if my new git code was the culprit. Having found this out, I figured it wasn't. @bpasero suspects it is somewhere in TypeScript code.

Rephrasing my previous question: can we, as Code, provide a better message to indicate where that promise came from?

**Comment by jrieken** [comment]
No, you cannot and that is in the nature of a promise/async code. In contrast to `throw`ing an error a promise can be rejected anytime without a meaningful stack trace. Worst, that in this case the promise is rejected without a [`reason`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/node/extensionHostProcess.ts#L74)

**Comment by jrieken** [comment]
And then a very complex search revealed this: [`Promise.reject<void>(null)`](https://github.com/Microsoft/vscode/blame/master/extensions/typescript/src/typescriptServiceClient.ts#L118)
