### ISSUE TITLE
Edge starts with vscode debug user profile when opening a new window via right-clicking taskbar icon

### ISSUE THREAD

**Issue by Asttear** [microsoft/vscode#164341]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Windows 11 build 22621.674

Steps to Reproduce:

1. Open a html file with VSCode
2. Press F5, choose debug with Microsoft Edge
3. Close all windows created above, launch Edge browser
4. Start a new window via right-clicking Edge icon on taskbar
5. Open edge://version, I get:
![image](https://user-images.githubusercontent.com/16262778/197355739-ab34a802-fa32-435d-9618-f7f00ab7afc1.png)
which shows it's using a profile from VSCode
6. Expected output:
![image](https://user-images.githubusercontent.com/16262778/197355828-77569d09-722b-4440-b445-f2116724fe1d.png)

**Comment by connor4312** [comment]
This is intentional: the debugger starts the browser in a separate `userDataDir` so that debugging can be enabled even if a browser is already running. You can disable this by setting `userDataDir: false` in your launch.json, but failures are much more likely.

**Comment by Asttear** [comment]
> This is intentional: the debugger starts the browser in a separate `userDataDir` so that debugging can be enabled even if a browser is already running. You can disable this by setting `userDataDir: false` in your launch.json, but failures are much more likely.

I realize that my description may have been somewhat misleading. In fact, when right-clicking on the taskbar icon to create a new browser window, the browser uses the wrong profile even if VSCode is not open. This is very confusing when I am simply browsing the web.

**Comment by Asttear** [comment]
I can't find this `userDataDir` setting. I'm not using the `Microsoft Edge Tools for VS Code` plugin.
