### ISSUE TITLE
Everything is Japanese

### ISSUE THREAD

**Issue by Aravindray** [microsoft/vscode#164386]
Type: <b>Bug</b>

While working with git cloned repo, every text visible in japanese in readme file. here I will add images - https://github.com/Aravindray/Arduino/blob/main/README.md

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.83GB free)|
|Process Argv|--crash-reporter-id c945fef1-5917-4641-9104-106a397e2beb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-office|cwe|2.7.9
remotehub|Git|0.44.0
vscode-pull-request-github|Git|0.52.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
jupyter|ms-|2022.9.1202862440
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.2
cpptools-extension-pack|ms-|1.3.0
remote-repositories|ms-|0.22.0
vsliveshare|ms-|1.0.5739
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
material-icon-theme|PKi|4.21.0
java|red|1.11.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-arduino|vsc|0.4.12
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
nodejswelcome1cf:30587006
40g7c324:30573242
vscutilityc:30590830

```

</details>

**Comment by TylerLeonhardt** [comment]
from your screenshots, it looks like you're using a different markdown editing experience than the default one... 
I’m suspicious of an extension causing this behavior. Can you open the Command Palette (<kbd>⌘</kbd>/<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>) and run the extension bisect command: `Help: Start Extension Bisect` and follow the prompts? ([More information about Extension Bisect here](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect))

**Comment by Aravindray** [comment]
@TylerLeonhardt Thanks for your reply, this issue has been resolved by going through this step "Can you open the Command Palette (⌘/Ctrl+Shift+P) and run the extension bisect command".

**Comment by TylerLeonhardt** [comment]
Which extension caused the problem?

**Comment by Aravindray** [comment]
Sorry for the late reply, here is the report - https://github.com/microsoft/vscode-java-test/issues/1504

**Comment by TylerLeonhardt** [comment]
I'll close this one then since you have that other issue.
