### ISSUE TITLE
The change flag lights up when the IME input is not yet finalized.

### ISSUE THREAD

**Issue by guttyon** [microsoft/vscode#164351]
Does this issue occur when all extensions are disabled?: Yes

version: 1.72.2 (user setup)
commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

The change flag lights up when the IME input is not yet finalized.
![Animation](https://user-images.githubusercontent.com/4711523/197369212-3474077e-ef80-4bc5-9a3b-f115a39b2055.gif)
The image above shows when one character is entered into the Japanese IME and cancelled with the ESC key.
The change flag lights up when a single character is entered.
After canceling the input with the ESC key, the change flag remains lit.
I think it is wrong that the change flag lights up when the text has not been changed.

**Comment by guttyon** [comment]
There is also the problem of canceling IME input, which results in an empty operation in undo/redo.

**Comment by alexdima** [comment]
Right now, whenever doing IME, we will immediately modify the text buffer, even before IME is confirmed. This allows other UI elements, such as the suggest widget, or vscode extensions, to react immediately.

I am not convinced of doing something very special for IME here. Also the file is dirty when not using IME and pressing for example <kbd>A</kbd> and then pressing <kbd>Backspace</kbd>. In other words, the dirty flag is not text buffer content based.
