### ISSUE TITLE
[css] refine vendor-specific warnings in vendor-specific rule blocks

### ISSUE THREAD

**Issue by LIXiangChen** [microsoft/vscode#164350]
- VS Code Version: 1.72.2

Please see the picture. VSC will prompt when a CSS property exists only with vendor prefix, which is a nice feature. But if the entire rule block is vendor-specific (the vendor-specific pseudo element), maybe there is no need to prompt.

![111](https://user-images.githubusercontent.com/8857634/197369015-12f06c2b-d210-4318-a7a4-9852e7cf1232.png)

**Comment by babakks** [comment]
@aeschli I'll submit a PR soon.

**Comment by babakks** [comment]
@aeschli Made the PR. I'm not sure this is a good solution though.

**Comment by LIXiangChen** [comment]
@babakks Hi, as far as I know, Firefox supports the `-webkit-` prefix, so it is possible to use a `-webkit-` attribute inside a `-moz` pseudo element (technically), the code below will work.

```
input[type="range"]::-moz-range-thumb {
    -webkit-mask-image: linear-gradient(to bottom, transparent 50%, black 50%);
}
```

**Comment by babakks** [comment]
@LIXiangChen Thanks for reminding this, but I think such things relate to the way CSS data are covered by the extension. I'm not sure about the policy on that side, though.
