### ISSUE TITLE
Using launch settings from 'C:\tmp\zz\Properties\launchSettings.json' [Profile 'http']...

### ISSUE THREAD

**Issue by Rick-Anderson** [microsoft/vscode#164302]
VSC should follow security best practices and launch the the `HTTPS` profile like VS does.

VS output has: 
```
Using launch settings from 'C:\tmp\TodoApi\Properties\launchSettings.json' [Profile 'http']...
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5072
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.
```

Follow the instructions at the [Microsoft Web API tutorial-Create a web project](https://learn.microsoft.com/en-us/aspnet/core/tutorials/first-web-api?view=aspnetcore-6.0&tabs=visual-studio-code#create-a-web-project-1)

```
dotnet new webapi -o TodoApi
cd TodoApi
dotnet add package Microsoft.EntityFrameworkCore.InMemory
code -r ../TodoApi
```

^F5 and it launches a browser to `http:localhost::<port>` not  `HTTPS` from `launchSettings.json`

related issues #164300  #71007 and https://github.com/OmniSharp/omnisharp-vscode/issues/5417

**Comment by roblourens** [comment]
I assume this is from the C# extension. launchSettings.json isn't a vscode thing as far as I'm aware.
