### ISSUE TITLE
Conditional editor contribution 

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#164309]
Currently when creating a full feature monaco editor instance, 64 editor contribs are created in `ctor`, even though not all of them will function in all files/languages, for example

* `editor.contrib.settings` only works with settings files
* `editor.contrib.acceptChangesButton2` only works with settings/sync resource
* `editor.contrib.defineKeybinding` only works in keybindings file

However since they are all created synchronously in monaco editor's `ctor`, they contribute a noticeable amount of time when creating multiple editors (e.g., notebook)

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/876920/197306839-fbb41058-c791-490a-897a-63d719e7e6e0.png">

I wonder if we can have some sort of lazy/conditional editor contributions, where the check is fairly fast and low cost, and only load contribs when they meet the condition.

**Comment by mjbvz** [comment]
Related work: https://github.com/microsoft/vscode/issues/164171

Here's contributions that I'm pretty confident should be disabled for editors embedded in notebooks:

- [ ] `editor.contrib.settings`
- [ ] `editor.contrib.untitledTextEditorHint`
- [ ] `editor.contrib.accessibilityHelpController`
- [ ] `editor.contrib.defineKeybinding`
- [ ] `editor.contrib.acceptChangesButton2`

And contributions that are candidates to disable but we need confirm:

- [ ] `editor.contrib.testingOutputPeek`
- [ ] `editor.contrib.testingDecorations`
- [ ] `editor.contrib.callStack`
- [ ] `editor.contrib.debug`
- [ ] `editor.contrib.largeFileOptimizationsWarner`
- [ ] `editor.contrib.menuPreventer`
- [ ] `editor.contrib.dirtydiff`
- [ ] `editor.contrib.findController`

**Comment by alexdima** [comment]
Notebooks can cherry pick the contributions using the [`contributions` option](https://github.com/microsoft/vscode/blob/320d6012c3bde85bd1d1ff60c422ad220570090e/src/vs/editor/browser/widget/codeEditorWidget.ts#L77). @rebornix I thought notebooks already makes effective use of this option?

(This issue is mostly about providing some kind of simple way for a contribution to ask to be instantiated only when the text model attached to an editor fulfils a certain condition. This would be useful for the text code editor of the workbench which might show a settings file, a keybindings file, etc.)

**Comment by rebornix** [comment]
@alexdima you are right, we are already filtering out some of the contributions, we had our filter list like a year ago, but the contributions keep growing and it's hard for us to keep track which contribs should be created/disabled. The contribution itself knows the best when it should be activated/created, so like you said, introducing a simple way for ask if a contrib should be instantiated would be very useful and generic.

**Comment by alexdima** [comment]
> we are already filtering out some of the contributions, we had our filter list like a year ago, but the contributions keep growing and it's hard for us to keep track which contribs should be created/disabled

If the problem is that the contributions keep growing, why don't you simply go with an allow list and not with an exclude list? I disagree that each contribution should become aware of notebooks, since the contributions are mostly editor aware and not workbench aware.

**Comment by rebornix** [comment]
> why don't you simply go with an allow list and not with an exclude list

At the end we want a full feature monaco editor, maintaining an allow list is no different from a filter list. When one builds a new feature for the editor and it's a generic one (e.g., ghost text), we would need to keep the list updated. It won't scale and require us to be aware of changes with editor contribution list. 

> I disagree that each contribution should become aware of notebooks

They shouldn't, I agree with that. They should only care when they can be instantiated.

> This issue is mostly about providing some kind of simple way for a contribution to ask to be instantiated only when the text model attached to an editor fulfils a certain condition. This would be useful for the text code editor of the workbench which might show a settings file, a keybindings file, etc.

This is very accurate and what I prefer to have.

**Comment by alexdima** [comment]
Contributions can now opt to be created at different times in the editor lifecycle. We also did a big pass and adopted most of them:
```ts
export const enum EditorContributionInstantiation {
	/**
	 * The contribution is created eagerly when the {@linkcode ICodeEditor} is instantiated.
	 * Only Eager contributions can participate in saving or restoring of view state.
	 */
	Eager,

	/**
	 * The contribution is created at the latest 50ms after the first render after attaching a text model.
	 * If the contribution is explicitly requested via `getContribution`, it will be instantiated sooner.
	 * If there is idle time available, it will be instantiated sooner.
	 */
	AfterFirstRender,

	/**
	 * The contribution is created before the editor emits events produced by user interaction (mouse events, keyboard events).
	 * If the contribution is explicitly requested via `getContribution`, it will be instantiated sooner.
	 * If there is idle time available, it will be instantiated sooner.
	 */
	BeforeFirstInteraction,

	/**
	 * The contribution is created when there is idle time available, at the latest 5000ms after the editor creation.
	 * If the contribution is explicitly requested via `getContribution`, it will be instantiated sooner.
	 */
	Eventually,

	/**
	 * The contribution is created only when explicitly requested via `getContribution`.
	 */
	Lazy,
}
```

Given this, I'll optimistically close out this issue. @rebornix Please let us know if you think we could do more in this area.
