### ISSUE TITLE
Add an explorer button in "Zen Mode"

### ISSUE THREAD

**Issue by milleym** [Microsoft/vscode#16439]
Minimal interface is terrific, but having to hop in and out to open a file (or having to type the file name) is awkward. 

A button that presents a floating explorer pane would be much more convenient.

**Comment by bpasero** [comment]
@milleym what is wrong with using quick open (`Ctrl+P`)?

**Comment by coreh** [comment]
I think moving the mouse cursor all the way to the left could summon the panel, would be pretty nice

**Comment by Zyst** [comment]
Another useful hotkey for this general use-case (That does work in Zen Mode) is Pressing `⌘B` (CtrlB in Windows?) to "Toggle Sidebar Visibility", you can just open it real quick, feel dirty for clicking stuff, and hide it again.

You can check what the key is bound to by Pressing `Ctrl/⌘ + P`, typing "Toggle Sidebar Visibility" and seeing the hotkey there.

**Comment by itsravenous** [comment]
For me, the whole point of Zen mode is to have no buttons distracting me. You can use the above keyboard shortcut to open the sidebar, or - even better - you can open the file tree directly. Default keybindings show:

`{ "key": "ctrl+shift+e",          "command": "workbench.view.explorer" }`

If you really want something to click, then you could just use fullscreen mode. It's Zen mode plus the sidebar and status bar.
