### ISSUE TITLE
"Open with Code" contextual menu button not working with `.tex` files

### ISSUE THREAD

**Issue by leonoverweel** [Microsoft/vscode#16442]
- VSCode Version: 1.4.0
- OS Version: Windows 10 build 14393.447

Steps to Reproduce:

1. Download a `.tex` (LaTeX file).
2. Browse to the file location in File Explorer.
3. Right click the file.
4. Click the "Open with Code" button.
5. A dialogue pops up: "How do you want to open this .tex file?" Visual Studio Code is not an option on the list.

Desired behavior: clicking this button should open the `.tex` file in Visual Studio Code.

**Comment by chrmarti** [comment]
@joaomoreno There must be a list of files to associate, right? (Cannot find it right now.)
