### ISSUE TITLE
Test verifying signed extensions

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#164452]
Refs: https://github.com/microsoft/vscode/issues/162284

- [x] macOS: @rzhao271 (x64)
- [x] macOS: @alexdima (arm64)
- [x] win: @rebornix (ia32)
- [x] win: @joyceerhl (x64)
- [x] win: @jrieken (arm64)
- [x] linux: @aeschli (x64)
- [x] linux: @chrmarti (arm)
- [x] linux: @alexdima (arm64)

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164452%0A%0A&assignees=sandy081)

---

### Set Up

Enable extension sign verification by adding following settings

```json
"extensions.verifySignature": true,
"_extensionsGallery.enablePPE": true
```

Restart insiders.

**Note:** Do not forget to remove this setting `_extensionsGallery.enablePPE` after testing, so that you can use actual Marketplace.

### Testing
Do not test installing regular extensions - this is expected to not work due to this setup. Only try with the extensions below.

* Open the Log (Shared) Output channel.
* Install at least 6 of the following extensions and make sure that the extension is installed properly and that "verified extension" message is logged in the output channel. Eg: `Verified extension: nikhgup1.component-creator true`
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.component-creator
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.xml1298
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.JavaScriptSnippets123
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.vscode-pull-request-github123
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.theme-dracula123
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.appmap123
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.todo-tree1298
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.material-icon-theme1298
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.vscode-thunder-client1298
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.rest-client1298
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.calva1298
    * https://marketplace.vsallin.net/items?itemName=nikhgup1.godot-tools1298

**Comment by weinand** [comment]
@sandy081 since I don't have access to an macOS ARM, I've removed my assignment

**Comment by isidorn** [comment]
This test plan item is NOT yet ready for testing. We are waiting for a Marketplace deployment that should ideally happen by tomorrow. I will update the test plan item as we get updates from the marketplace team. Sorry about this.

**Comment by sandy081** [comment]
Latest insiders is available now and you can test it now. Thanks.

**Comment by jrieken** [comment]
This doesn't seem to work on windows arm64: #164707

**Comment by isidorn** [comment]
Update: make sure to only test the signed extensions that are listed in the test plan item.
It is expected that regular extension install does not work due to this weird setup.

**Comment by joyceerhl** [comment]
I was able to install all extensions on Windows x64 except `nikhgup1.appmap123` due to version mismatch

```
2022-10-26 10:42:43.908 [error] Failed to install extension. nikhgup1.appmap123
2022-10-26 10:42:43.909 [error] Invalid: Cannot install 'nikhgup1.appmap123' extension because of version mismatch in Marketplace
    at $.checkAndGetCompatibleVersion (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:96873)
    at async $.installFromGallery (vscode-file://vscode-app/c:/Users/huer/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:87:86770)
```

**Comment by sandy081** [comment]
Thanks everyone for testing 👏
