### ISSUE TITLE
"Add to Workspace Recommendations" works  incorrectly, when extension id has upper case.

### ISSUE THREAD

**Issue by lclancey** [microsoft/vscode#164458]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
   1.72.2
- OS Version: 
  MacOS Monterey 12.3.1

Steps to Reproduce:

1. Open any directory or workspace, empty directory in the video below for example.
2. In Extensions tab, search "volar", then add first two extensions, `Vue Language Features(Volar)` and `TypeScript Vue Plugin(Volar)` into workspace recommendations.
3. Bug: Every time you try to add one of these two extensions, the newly added extension id in `./vscode/extensions.json` is a string start with a upper case like "Vue.xxx", and the rest of others will change to all lower case string like "volar.xxx", this makes further "Add to Workspace Recommendations" oprations work incorrectly.

https://user-images.githubusercontent.com/8706932/197529147-73cef34f-dd48-4362-937f-51f7f1098037.mov

My guessing: 
The function `getRecommendations` and  `getUnwantedRecommendations` returns an array of lowercase strings,
https://github.com/microsoft/vscode/blob/7bd27b4287b49e61a1cb49e18f370260144c8685/src/vs/workbench/services/extensionRecommendations/common/workspaceExtensionsConfig.ts#L82-L90
however those adding or removing functions only push the raw extensionId to config file, which causes this bug when the raw extensionId has upper case.
https://github.com/microsoft/vscode/blob/7bd27b4287b49e61a1cb49e18f370260144c8685/src/vs/workbench/services/extensionRecommendations/common/workspaceExtensionsConfig.ts#L144-L158

**Comment by sandy081** [comment]
I am not sure what the bug is here? Since extension ids are case insensitive, we handle them correctly while reading or writing. Can you please let us know what feature is not working?

**Comment by lclancey** [comment]
> I am not sure what the bug is here? Since extension ids are case insensitive, we handle them correctly while reading or writing. Can you please let us know what feature is not working?

Well, a simple description: you can click `Add to Workspace Recommendations` twice when adding vue.volar...the first time it will add "Vue.volar" string and second time "vue.volar".

https://user-images.githubusercontent.com/8706932/197571935-342a5a03-fcd8-471a-8f0e-2a8a0ed42088.mov

**Comment by sandy081** [comment]
Got it. Thanks for providing info.
