### ISSUE TITLE
New settings left pane should scale with editor.fontSize

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16447]
![image](https://cloud.githubusercontent.com/assets/2193314/20863589/87ee74e4-b984-11e6-9602-a89de2b12780.png)

**Comment by ramya-rao-a** [comment]
What about the search box?

![image](https://cloud.githubusercontent.com/assets/16890566/20992964/67313ab4-bc9c-11e6-85da-c128e36eb697.png)

**Comment by sandy081** [comment]
I think adjusting search bar with editor settings is not necessary also it is not part of the editor.

**Comment by ramya-rao-a** [comment]
Am ok with that.

**Comment by Tyriar** [comment]
@sandy081 it's more part of the editor than the workbench though imo.

**Comment by sandy081** [comment]
Agreed. I will play around with this for Search bar and see how it looks in next milestone. Thanks.
