### ISSUE TITLE
The most valuable feature to me is that vscode can auto format a file, but every time i upgrades it loses this ability!

### ISSUE THREAD

**Issue by calidion** [Microsoft/vscode#16449]
Why should an editor getting more and more useless to a user when it gets updated?
it confused me.

**Comment by calidion** [comment]
need format buttons back, it is very useful when i don't want to use keyboard.

**Comment by chrmarti** [comment]
- What extensions do you have installed? (`code --list-extensions`)
- What language are you formatting?
- In which version does it work and in which does it stop working?

**Comment by calidion** [comment]
node extension
language: javascript

in 1.6.x
right click => format code
in 1.7.x
right click => no options for code formatting.

**Comment by jrieken** [comment]
In 1.7.x is renamed to `Format Document` and given a selection `Format Selection`
