### ISSUE TITLE
Auto generate triple slash comments with parameters

### ISSUE THREAD

**Issue by EmYeuCoGiao** [Microsoft/vscode#1644]
I use VSCode for unity3d dev, i type /// but this not auto gennerate
<code>
///<summary>
///
///</summary>
///<param name=""></param>
</code>
![capture](https://cloud.githubusercontent.com/assets/14220005/11999614/a40d4bae-aaf4-11e5-96ce-064b8b02bb7e.PNG)

**Comment by bpasero** [comment]
This is currently not supported as far as I know.

**Comment by EmYeuCoGiao** [comment]
Thanks you for reply :+1:

**Comment by jrieken** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#8
