### ISSUE TITLE
Improve search performance. 

### ISSUE THREAD

**Issue by ssylvan** [Microsoft/vscode#16448]
- VSCode Version: 1.7
- OS Version: Windows 10

Steps to Reproduce:

1. Search for text in a large folder
2. Open a cmd window and search for the same text using "findstr".
3. Note how findstr is an order of magnitude faster.

Searching for stuff is a key operation. It shouldn't be this slow.

**Comment by chrmarti** [comment]
Improvements are in the upcoming 1.8. #15384

**Comment by ssylvan** [comment]
FWIW, one way to improve the perceived performance could be to prioritize searches around "known" locations of the tree.

I often open up a huge folder because I want the context, but in practice I spend 99% of my time in some tiny sub-tree. When I search for something, the thing I want is _probably_ going to be "near" some of my currently open files. Perhaps sorting the search order to prioritize folders that are close to currently opened files would mean that all the matches show up instantly (and I don't really care that it keeps searching the rest of the folder for another 10s after I've found what I wanted).

**Comment by chrmarti** [comment]
Good point, it would prevent us from showing the results in a deterministic order because the order we search depends on what files are/were open. /cc @roblourens

**Comment by roblourens** [comment]
Interesting idea, also you should see faster search in Insiders now if you want to try it out.
