### ISSUE TITLE
Show full string when hovering string paths in debugger variables tab

### ISSUE THREAD

**Issue by simon-abbott** [microsoft/vscode#164486]
When I'm debugging code I like to have the debugger tab docked to the left side of the screen. However, this is a problem when debugging anything with strings containing file paths because the end of the string gets cut off by the edge of the pane. Most other data types get around this by allowing you to hover over them, which displays a tooltip containing more information. However when hovering a string that contains a file path it instead shows "Cmd + click to follow link". Currently I have to either copy the value and paste it somewhere else to read, or I need to expand the variables tab which means I don't have much room for my code view, both of which really take me out of my debugging flow.

**Comment by roblourens** [comment]
This bugs me too. A workaround is to hover just outside of the link text, for example if the string contains a quote mark, hover that.

But would take a PR that modifies the link detector to include the full string value in the tooltip. That happens here: https://github.com/microsoft/vscode/blob/b75ba63f04aa64a8e1fdfb4e0da8af44b947f98c/src/vs/workbench/contrib/debug/browser/linkDetector.ts#L196 and the value should be passed in as an option, and only happen for expressions.

**Comment by babakks** [comment]
@roblourens I'll submit a PR.

**Comment by babakks** [comment]
@roblourens I've made the PR. Could you please review it anytime?
