### ISSUE TITLE
RSS Feed for extensions gallery

### ISSUE THREAD

**Issue by aziz** [Microsoft/vscode#16441]
It would be great to have a RSS feed for the new extensions added to the gallery. 
It might not be related to this repo but I couldn't find a repo for the extension gallery website.

**Comment by lextm** [comment]
You can get the whole gallery feed as a JSON file from http://vscode.blob.core.windows.net/gallery/index

By adding your processing logic (such as defining the time range), you can filter out the "new extensions" from them and create your own feed.

**Comment by waderyan** [comment]
Ping @hamenon

**Comment by hamenon** [comment]
Noted. Will add it to the backlog, if possible could you add it on our uservoice page as well (https://visualstudio.uservoice.com/forums/331878-visual-studio-marketplace)? It'll help us gauge the interest for the feature from other users as well.

**Comment by waderyan** [comment]
Looks like you beat me to it. When did that user voice show up? Cool! 

Separate from this issue, but relevant for future marketplace requests - could you add a link to User Voice somewhere on the Marketplace page? I can't find one today and it would be good to give users a link to navigate to.

**Comment by waderyan** [comment]
I'm going to leave this open on our end but if you stumble across this please go to https://visualstudio.uservoice.com/forums/331878-visual-studio-marketplace/suggestions/17406490-rss-feed-for-extensions-gallery and upvote!

**Comment by kumarharsh** [comment]
+1
One use-case I have come across goes like this:
I'd like to query what is the latest version of my plug-in from the marketplace, and bump my versions using semantic-release. To do something similar today, I have to *also* publish my plug-in to npm, and query from there, which doesn't feel right.

**Comment by kenijo** [comment]
I have created a PHP script that takes the JSON available at http://vscode.blob.core.windows.net/gallery/index but I found out that the JSON feed is out dated.

For instance, the MS C# extension is listed at https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp as version 1.13.1, last update from 11/13/2017, 3:00:42 PM but the JSON feed most recent version is version 1.8.0 from 2017/03/21.

Do you know of a working / up to date feed?

**Comment by egamma** [comment]
September issue grooming. Closing this issue it is not an issue we can act on in VS Code. To upvote pls see https://github.com/Microsoft/vscode/issues/16441#issuecomment-266525977
