### ISSUE TITLE
Order of output mime types not respected by Notebook Output renderer

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#164483]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Stable
- OS Version:  Any

Steps to Reproduce:

1.  Create a Jupyter notebook with the following content
<details>
  <summary>Sample ipynb file</summary>
  
  ```json
{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 10,
      "metadata": {},
      "outputs": [
        {
          "data": {
            "application/json": {
              "hello": 134
            },
            "text/html": [
              "<div>1234</div><ul><li>1</li><li>2</li><li>3</li></ul>"
            ],
            "text/plain": [
              "<__main__.Something at 0x131c3d5b0>"
            ]
          },
          "execution_count": 10,
          "metadata": {},
          "output_type": "execute_result"
        }
      ],
      "source": [
        "class Something():\n",
        "\tone = 1234\n",
        "\tdef _repr_html_(self):\n",
        "\t\treturn '<div>1234</div><ul><li>1</li><li>2</li><li>3</li></ul>'\n",
        "\n",
        "\tdef _repr_json_(self):\n",
        "\t\treturn {'hello':134}\n",
        "\n",
        "\n",
        "Something()"
      ]
    }
  ],
  "metadata": {
    "kernelspec": {
      "display_name": "Python 3.9.13 ('.venvWidgets': venv)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.13"
    },
    "orig_nbformat": 4
  },
  "nbformat": 4,
  "nbformat_minor": 2
}

  ```
</details>

3.  Open the file in VS Code
4. The JSON output is displayed instead of HTML, this is wrong, the HTML output is richer and should be given preference

@connor4312 @mjbvz based on the code we seem to have some preference hardcoded in VS Code for mime types
See here https://github.com/microsoft/vscode/blob/issue164304/src/vs/workbench/contrib/notebook/common/notebookCommon.ts#L43
```typescript
export const NOTEBOOK_DISPLAY_ORDER: readonly string[] = [
	'application/json',
	'application/javascript',
	'text/html',
	'image/svg+xml',
	Mimes.latex,
	Mimes.markdown,
	'image/png',
	'image/jpeg',
	Mimes.text
];
```

I'm not entirely sure why this is there or what what it does, but my understanding of display order of mime types was:
* Extension needs to sort the output items in the order we would like them displayed.
I.e. if the output has 2 mime types, then exnesion needs to ensure the mime types are sorted so that the first item is displayed.

Right now this results in a poor UX as users cannot see the HTML output instead end up with JSON which doesn't necesssarily contain the best output for viewing.

**Comment by mjbvz** [comment]
I also don't have any context on this. Let's revisit it in November

**Comment by DonJayamanne** [comment]
The default display order is wrong for Jupyter notebooks, perhaps we need to provide a pre-defined display order for Jupyter notebooks (i.e. contribute a default value for the settings).
However that does not work as users could have already setup a display order for other notebooks.

**thoughts:**
* Should the display order by per ntoebook type?
* Why do we have display order hardcoded?
* I was under the impression that the order of the mime types in the output defines the order in which they are to be definmed (i.e. order in the list is the order for display). At least thats what was the original intention when the API was originally worked on by @jrieken 
* Why is JSON preferred over HTML, surely HTML is a richer display format than JSON. @connor4312 any idea why this was setup in this manner?

**Comment by rebornix** [comment]
> Should the display order by per ntoebook type?
> Why do we have display order hardcoded?

Imagine users use vanilla VS Code and open an ipynb file, which contains multi-mimetype output, VS Code needs to figure out which mimetype to render. It's arguable which one should be picked, but no matter how we pick, it's a "hardcoded" order.

In the early designs, we explored serializer defined order and user defined order, and at the end, it was simplified to 

* a display order defined in core
* user preference per mimetype

---

From what I read above, it seems the current predefined display order is not great, but I don't think allowing Jupyter to override the list can solve the problem: why Jupyter's one needs to be different from the builtin one? Can they be the same? In what circumstances do they differ and how would users be aware of the difference and know how to change it if some users are not satisfied with the new opinionated?

**Comment by DonJayamanne** [comment]
>  why Jupyter's one needs to be different from the builtin one? 

I would expect the majority case to be addressed and majority of the notebooks are or was ipynb at the time of creating the notebook ui, hence going with ricker mime order seems more logical.
As mentioned I don't undertstand why JSON has a higher display order than HTML, as HTML is a richer content. This seems to be wrong even for the Node Notebook. My assumption is that richer mimes would get preference over others.

> but I don't think allowing Jupyter to override the list can solve the problem:

Agreed. 

> In what circumstances do they differ and how would users be aware of the difference and know how to change it if some

Great question, I would assume that 99.9% of the users wouldn't care once they get the richest output.
I think what matters is the renderer, e.g. having two renderers for the same mime type and then the user changing this. And we run into the exact same problem here, that being `how would users be aware of the difference and know how to change it if some`

I think we should change the display order to be simple as `Give preference to richer mime types`
However I think we need to first understand the original problem (that made this was change) and what it fixed. 
However I'm not entirely sure I understand the previous problems and how the display order fixed that.

**Comment by DonJayamanne** [comment]
> I think we should change the display order to be simple as Give preference to richer mime types

Then again, why can't the serializer define the order. The serializer knows what types of mimes are supported and has the best knowledge. 
It seems wrong for VS Code to assume that a particular mime is better than the other. Control should be handed back to the author of the notebook type, i.e. serializer.

**Comment by rebornix** [comment]
> why can't the serializer define the order
> The serializer knows what types of mimes are supported

In our system (an extensible system) the serializer doesn't actually know. The mimetypes are provided by execution engines (e.g., a kernel) and serializer is only responsible for saving them to disk. When there is an unknown mimetype, we would still a single coordinator to help enrich/consolidate the priority order.

@connor4312 I'd like to have your insights for this topic.

**Comment by connor4312** [comment]
I agree that this seems outside the responsibility of the serializer to know about. Not having worked with the notebook API in a little while and just looking at it, it doesn't look like a notebook type even needs a serializer. I think json should be just above 'text' at the end of the prioritization list, however.

In testing's API, I had a similar use case around the TestRunProfile. In that case allowed extensions to set `isDefault` on a profile to determine if that profile should be used to run tests by default, provided the user hasn't chosen different profile(s) already. If API is warranted for notebooks here, adding a similar flag on `NotebookCellOutputItem`'s might be a more minimal approach than a priority list.

**Comment by DonJayamanne** [comment]
Closing this issue as out of scope, as this haven't been reported by anyone else, no upvoted.
