### ISSUE TITLE
IMKTextInput inline composition buffer is not linebreaking when necessary.

### ISSUE THREAD

**Issue by ShikiSuen** [microsoft/vscode#164440]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2 d045a5eda657f4d7b676dedbfa7aab8207f8a075
- OS Version: 22A379

Steps to Reproduce:

1. Use any macOS buit-in Chinese Input Method (or Japanese Input Method).
2. Enable auto-wrap.
3. Type something to force the inline composition buffer (i.e. "preedit area" in Windows TSF) breaks at the line end.

<img width="863" alt="image" src="https://user-images.githubusercontent.com/3164826/197518251-5b2ba8e5-c096-4396-b057-4a6fc2c77b2b.png">

**Comment by ShikiSuen** [comment]
Update: Disabling all extensions will make this issue behaves differently, but still abnormal:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/3164826/197519450-e3e4771d-53a8-4f35-b191-f333d47f041c.png">

**Comment by ShikiSuen** [comment]
BTW, please find a native Traditional-Chinese bopomofo user to use the Zhuyin IME to test whether this issue is fixed.
My English ability is not well enough for describing other symptoms of this issue precisely.

(Simplified Chinese input methods shipped in macOS doesn't use inline composition buffer pretty much.)

**Comment by alexdima** [comment]
Let's track supporting wrapping and IME at the same time in https://github.com/microsoft/vscode/issues/28291

**Comment by ShikiSuen** [comment]
Looks like this issue is already existed for years.
Considering that it looks like it won't be dealt in the following years, I'll add both VSCode and VSCodium to the IMKTextInput blacklist of vChewing IME (a Chinese Input Method project of mine) which enables popup-composition-buffer instead of the inline one.
