### ISSUE TITLE
Expand PickList to support Images or other Icon Fonts

### ISSUE THREAD

**Issue by alefragnani** [microsoft/vscode#16445]
Today, you are able to embed icons in the text of the PickList items using **Octicons**, via `$(icon-name)`.

It would be a great addition to support Images, like in `ThemableDecorationRenderOptions.gutterIconPath`, or other Icon Fonts like **FontAwesome**, **FontMfizz**, etc.

Thanks in advance.

**Comment by bpasero** [comment]
@misolori didn't we do this with the icon font?

**Comment by misolori** [comment]
@bpasero not yet, but soon you will be able to use all of our icons (Octicons + product) in the quick pick. 

What this issue is asking for is to use other icons, like FontAwesome. In that case I'm closing this in favor of #79130 as that will allow you to do that.

**Comment by alefragnani** [comment]
@misolori @bpasero the main request was to use _Images_ (like in `ThemableDecorationRenderOptions.gutterIconPath` and `TreeItem.iconPath` supports), basicaly because I would like to reflect in the `PickList` the same images that can be used in gutter and side bar, from my [Bookmarks](https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks) and [Project Manager](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extensions. Without that, I have to _look for similar icons_, which is not a perfect scenario. 

But, supporting a wider range of icons (and customizations), like you did with the `vscode-icons` repo is a great step in the right direction. 

Thanks 👍
