### ISSUE TITLE
Test extension logging API

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#164434]
Refs: https://github.com/microsoft/vscode/issues/159892, https://github.com/microsoft/vscode/issues/161944

- [x] any @paulacamargo25
- [x] any @weinand
- [ ] any @karthiknadig

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164434%0A%0A&assignees=sandy081)

---

[Proposal](https://github.com/microsoft/vscode/blob/1dd67592e120d916a8963903babaf0fae74440c5/src/vscode-dts/vscode.proposed.extensionLog.d.ts#L1)

Added, logLevel and the corresponding change event to the output channel and env. Please test these APIs.

https://github.com/microsoft/vscode/blob/5a326b2a68369b484607a7361fc123405cc01a96/src/vscode-dts/vscode.proposed.extensionLog.d.ts#L18-L30

https://github.com/microsoft/vscode/blob/5a326b2a68369b484607a7361fc123405cc01a96/src/vscode-dts/vscode.proposed.extensionLog.d.ts#L32-L46

## Testing

Create a log output channel  using the following API 

https://github.com/microsoft/vscode/blob/5a326b2a68369b484607a7361fc123405cc01a96/src/vscode-dts/vscode.proposed.extensionLog.d.ts#L96

### Env: Testing Log Level and the change event for all logs

Configure log levels for all log channels using the command `Set Log Level...` and make sure

- log level change is being propagated in env and also in your log output channel
- log output channel UI is not logging the logs those do not respect the set log level.

### Log Output Channel: Testing Log Level and the change event for a log output channel

Configure log levels for this log channel using the command `Set Log Level...` and make sure

- log level is being propagated to your output channel
- log output channel UI is not logging the logs those do not respect the set log level.
- this overrides the log level configured for all loggers.

### CLI: Testing Log Level configure from CLI

You can now configure the default log level for an extension from CLI using the format `code --log <extensionId>:<logLevel>`, for eg., the following sets the log level to trace for all log output channels of `vscode.git` extension. 

```
code --log vscode.git:trace
```

Following will set the log level to debug for all loggers (Note this format is already supported)

```
code --log debug
```

Please make sure

- the configured log level is propagated to your output channel
- the log level that was set for all loggers from the command line, is propagated to your output channel and also in env
- log output channel UI is not logging the logs those do not respect the configured log level.
- the documentation in the CLI explains this.

**Comment by karthiknadig** [comment]
@sandy081 This command did not work for me `code-insiders --log vscode.git:trace .` but `code-insiders .` works. I verified that `vscode.git` is installed.

Version: 1.73.0-insider (system setup)
Commit: a803dc359aa1ed48c7acf074dd81d6af1525c8c8
Date: 2022-10-25T05:18:55.889Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes

**Comment by karthiknadig** [comment]
Tries this with a language server client. works fantastically!!!
![image](https://user-images.githubusercontent.com/3840081/197901042-f4a44c89-2ec9-4d31-9fdc-9243007c4d9d.png)

These are being logged from python over LSP through language client.
