### ISSUE TITLE
Test: Policy setting indicators in the Settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#164482]
Refs: #157564

- [x] macOS @eleanorjboyd
- [x] linux @alexr00

Complexity: 3

Authors: @rzhao271, @sandy081 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164482%0A%0A&assignees=rzhao271,sandy081)

---

The look of policy-managed settings is now different in the Settings editor. This TPI is intentionally only for macOS and Linux because they support the `--__enable-file-policy` flag.

1. One can find the directory of the `argv.json` file by running the "Preferences: Configure Runtime Arguments" command, followed by the "File: Reveal in File Explorer" command. In the same folder as `argv.json`, set up a file `policy.json` with the following content:
```json
{
    "UpdateMode": "none"
}
```
2. Open code-insiders from a terminal with the command `code-insiders --__enable-file-policy`
3. In the Settings editor, search for `update mode`.
4. The `update.mode` setting should show up with an indicator. The indicator currently has a warning icon on it to be extra noticeable.
5. A user should be able to change the setting value of a policy setting and have the new value reflected in the Settings editor. The JSON file should also be updated with the new value. However, the setting in the JSON file should have a warning on it also saying that the setting cannot be applied due to it being managed by a policy.
   - If step 5 fails, that's a bug. Also try changing the `update.mode` setting directly in the User `settings.json` file. One should be able to successfully save the `settings.json` file after, but the setting itself should have a warning or be faded out.
6. Use a screenreader to focus onto the policy setting in the Settings editor. Screenreaders currently cannot focus onto the indicators themselves, but when they focus onto the setting, a paraphrased version of the indicator information should be read out.

**Comment by eleanorjboyd** [comment]
Hi! Two questions - should I be able to change the "updateMode" setting in the settings UI? Mine gives the error: `Unable to write update.mode because it is configured in system policy.` which seems correct I just wanted to check. Additionally should I see the "updateMode" reflected in the settings.json file for the user settings?

**Comment by rzhao271** [comment]
Hi, the setting should be writable still. It's a bug that the setting isn't writable from the Settings editor, but if the whole feature seems confusing, you can also create an issue with that feedback.

"updateMode" should be reflected in the JSON file after adjusting the setting in the Settings editor. Can the setting be modified by editing the user settings.json file directly?

**Comment by eleanorjboyd** [comment]
Here is what I see- I go into change that setting and I get this error pop up and then I do not see updateMode in the settings.json file. To clarify I created the `policy.json` myself and the `.vscode-insiders` folder is not listed in my file explorer in VS Code but instead I found it through finder. I am able to change the UpdateMode in the `policy.json` file and I get a pop up on VS Code that says `A setting has changed that requires a restart to take effect.` - which on reload the new value does display in the settings UI.

<img width="1646" alt="Screen Shot 2022-10-25 at 10 13 54 AM" src="https://user-images.githubusercontent.com/26030610/197839959-16a22dcb-faa4-45d2-84e4-1fa4b9644a85.png">
<img width="1649" alt="Screen Shot 2022-10-25 at 10 11 23 AM" src="https://user-images.githubusercontent.com/26030610/197839965-c9d8e073-5085-4106-af6a-bb29411e740f.png">

**Comment by rzhao271** [comment]
That makes sense. I have modified the TPI and added some clarification steps.

**Comment by eleanorjboyd** [comment]
screen reader for mac works as expected 👍

**Comment by alexr00** [comment]
I can't get a screen reader working with a VM, but everything else works well!
