### ISSUE TITLE
Reloading Code OSS While Debugging Often Crashes

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#164443]
* On Windows
* When debugging Code OSS With VS Code
* Probability of crash is much higher when dev tools are opened.
    * Probability of crash when dev tools are opened: ~30-40%
    * Probability of crash when dev tools are not opened: ~15%

![Code_-_OSS_wqVkSFoAo5](https://user-images.githubusercontent.com/2931520/197521376-5dffcd64-af5d-4ee0-9cae-a3978d974c87.gif)

This is extremely annoying and started happing after an electron update (I think the latest one, happens two me for 2 months now)

**Comment by deepak1556** [comment]
Please create new issue with crash dumps https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports if this happens agains, closing for now.
