### ISSUE TITLE
Test: Workspace trust setting indicators in the Settings editor

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#164477]
Refs: #157564

- [x] macOS @digitarald
- [x] linux @aeschli
- [x] windows @gregvanl

Complexity: 3

Authors: @rzhao271, @sandy081 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164477%0A%0A&assignees=rzhao271,sandy081)

---

The look of workspace restricted settings is now different in the Settings editor.

1. Open a restricted workspace.
2. In the Manage Workspace Trust view, click on the part that says "X workspace settings aren't applied".
3. The Settings editor should show up with the Workspace tab opened and the restricted settings visible.
4. The restricted settings should have an indicator on them. The indicator currently has a warning icon on it to be extra noticeable.
5. A user should be able to change the setting value of a restricted setting and have the new value reflected in the Settings editor. The JSON file should also be updated with the new value. However, the setting in the JSON file should have a warning on it also saying that the setting cannot be applied in an untrusted workspace.
6. Use a screenreader to focus onto the restricted setting in the Settings editor. Screenreaders currently cannot focus onto the indicators themselves, but when they focus onto the setting, a paraphrased version of the indicator information should be read out.

**Comment by aeschli** [comment]
Works well, also tested with the Orca screenreader in Ubuntu.
