### ISSUE TITLE
Avoid reordering changes in update-localization PRs

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#164459]
I've reviewed/approved a couple update-localization PRs (e.g. https://github.com/microsoft/vscode-loc/pull/1118) and observed that there's always a few changes just due to reordered properties. E.g. `dist/preview/documentRenderer` in https://github.com/microsoft/vscode-loc/pull/1118/commits/751b350cd2a2ae3a2ba0b4be0ab3c08480b57667
Would be great if we can avoid these, to keep the number of changes small and simplify the reviewing.

**Comment by TylerLeonhardt** [comment]
Fixed in ^^^
