### ISSUE TITLE
Autocomplete not letting me 'enter' or 'tab' to type suggestion

### ISSUE THREAD

**Issue by Molier** [microsoft/vscode#164436]
Type: <b>Bug</b>

* connect to remote ssh using vscode.
* open a .ipynb or .py file(tested on these 2)
* type anything and the autocomplete suggestions come up
* press tab or enter(both are enabled in settings and work locally on both machines)
** expected: top most suggestion is auto completed
** actual: an enter or tab character is entered in the file.
![image](https://user-images.githubusercontent.com/7408635/197513838-5acf4cdd-9ef2-4f72-b4f5-6cd50a8ed1b1.png)
if more logs/info is needed please ask.
i tried various methods to solve but was not successful.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.33GB free)|
|Process Argv|--crash-reporter-id 433b11f6-ca06-44dd-a54a-a045e1cc2528|
|Screen Reader|no|
|VM|50%|

|Item|Value|
|---|---|
|Remote|SSH: 81.164.126.111|
|OS|Linux x64 5.15.0-52-generic|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor (16 x 3800)|
|Memory (System)|31.29GB (26.45GB free)|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
phoenix|pho|0.1.2
code-settings-sync|Sha|3.4.3
vscode-eex-snippets|ste|0.0.8
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
tabnine-vscode|Tab|3.6.18

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848:30577860
nodejswelcome1cf:30587006
40g7c324:30573242

```

</details>

**Comment by jrieken** [comment]
Please do the following

* F1 > Toggle Keyboard Shortcuts Troubleshooting
* Reproduce the issue
* from the logging view see what command `Tab` was associated with

**Comment by Molier** [comment]
> `[2022-10-24 16:38:04.321] [renderer1] [info] [KeybindingService]: \ From 9 keybinding entries, matched tab, when: editorTextFocus && !editorReadonly && !editorTabMovesFocus, source: built-in. `
> 
> ⬆️ looks like it doesn't resolve the accept completion command here... @Molier Do you have any keybindings configured?

I dont really have any custom keybinds defined I think. I maybe have an intellij keybind plugin set in the host machine.
Edit:But after removing this, this didnt solve the issue.

Can I check those 9 entries to see what the problem is?
