### ISSUE TITLE
Ignore leading `./` in "quick open"

### ISSUE THREAD

**Issue by FloEdelmann** [microsoft/vscode#164594]
I often have a webpack watcher running in an external terminal. It marks errors with a relative path, e.g. `ERROR in ./foo/bar/baz.ts:6:41`. Double-clicking the path selects the whole path in my terminal program, thus I have `./foo/bar/baz.ts:6:41` in my clipboard.

I then want to open that file (ideally at that position) in VS Code. I hit <kbd>Ctrl</kbd>+<kbd>P</kbd> to open the "quick open" bar and paste the path. However, VS Code doesn't find any matching files immediately. I first have to remove the leading `./` (by pressing <kbd>Home</kbd> → <kbd>Delete</kbd>), then it finds the file I want to open.

I suggest to ignore leading `./` in paths entered in the "quick open" bar to save me these two keystrokes.

**Comment by Tyriar** [comment]
Do you have shell integration enabled? The ./ is actually taken into account when we know the current working directory. A [gif](https://gifcap.dev/) of you doing this would be helpful to see the exact case

**Comment by TylerLeonhardt** [comment]
@Tyriar me
