### ISSUE TITLE
cant type in terminal or connect to remote extension host server

### ISSUE THREAD

**Issue by aidenomelia** [microsoft/vscode#164527]
Type: <b>Performance Issue</b>

failed to connect to the remote extension host server error but when i try to use the terminal to fix it, it wont even let me type anything in.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes: Restricted
Sandboxed: No
Connection to 'vscode-remote' could not be established  No remote extension installed to resolve codespaces.

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.40GB free)|
|Process Argv|--crash-reporter-id ca86eef2-c575-4546-a655-d995519ba9dd|
|Screen Reader|no|
|VM|0%|

Connection to 'vscode-remote' could not be established  No remote extension installed to resolve codespaces.
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    97	 24948	code main
    0	   159	  1732	   window (Settings - 101536960 [vscode-remote] - Visual Studio Code)
    0	    89	 10128	   issue-reporter
    0	    29	 10340	   crashpad-handler
    0	    40	 22244	   utility-network-service
    0	   104	 24384	   shared-process
    0	    74	  7668	     fileWatcher
    0	    75	 17876	     ptyHost
    0	    91	 25432	   extensionHost
    0	   135	 26812	   gpu-process
Connection to 'vscode-remote' could not be established  No remote extension installed to resolve codespaces.
```

</details>
<details>
<summary>Workspace Info</summary>

```

Connection to 'vscode-remote' could not be established  No remote extension installed to resolve codespaces.;
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
2144e591:30553903
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30573243
vscutilityc:30590830

```

</details>

**Comment by Tyriar** [comment]
You don't have any extensions installed for remote support:

> Connection to 'vscode-remote' could not be established No remote extension installed to resolve codespaces.
>
> Extensions: none
