### ISSUE TITLE
add option for ctrl+tab to openNextRecentlyUsedEditorInANYGroup 

### ISSUE THREAD

**Issue by wadewalker25** [Microsoft/vscode#16454]
- VSCode Version:
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:06:37.428Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
- OS Version: : Windows 10

Would like the ability to ctrl+tab between any files in any editor. If there are multiple files open between editor, then a simple number next to the file to indicate which editor group it's in would be great.

**Comment by bpasero** [comment]
@wadewalker25 you can bind `Ctrl+Tab` to `workbench.action.showAllEditors` and that should do it. Though that list is not in MRU order but in spatial order.

**Comment by bpasero** [comment]
Also https://github.com/Microsoft/vscode/issues/16463

**Comment by wadewalker25** [comment]
Fantastic! Thanks so much Benjamin!
