### ISSUE TITLE
[Feature Request] Breakpoint Group

### ISSUE THREAD

**Issue by ShuiRuTian** [microsoft/vscode#164569]
A recover of #105927
And there are many other request like #164146, #146511, #162388 could be partially/totally resolved by this feature

### Description
Breakpoints could be grouped into a Breakpoint Group, user could enable/disable the Breakpoint Group to enable/disable all breakpoints in it.

### Motivation

- To debug complex feature
- Breakpoint could be put together by logic
- Tedious to click multi-times on the red circle icon.

### Details
1. A default breakpoint group (Logically, the UI might not need to be changed until user add a new Breakpoint Group)
1. Add Breakpoint Group. 
    - An icon on "BREAKPOINTS" panel to add new group with name(Not allow same name)
    - A command to add Breakpoint Group
1. Remove Breakpoint Group. 
    - An icon on the right of hovering Breakpoint Group to remove it and all breakpoints in it.
    - "Remove Breakpoint Group itself" on right click menu, to remove the group itself, but move the breakpoints into the default Breakpoint Group
    - "Remove Breakpoint Group and inside breakpoints" on right click menu, 
1. Enable/Disable breakpoints in Breakpoint Group. 
    - A three state checkbox on the left of Breakpoint Group, the tree states are "All enabled", "Partially enabled", "All disabled"
    - "Enable/Disable all breakpoints inside the group" on right click menu.
1. Rename Breakpoint Group. 
   - Press F2 on a selected Breakpoint Group to rename it
   - "Rename" on the right click menu
1. Select multi breakpoints. 
    - Allow "Shift + click" to select multi breakpoints between current select breakpoint and target clicked breakpoint. 
      - Cross Breakpoint Group will not select the group itself
    - Allow "Ctrl + click" to select multi breakpoints.
      - click on Breakpoint Group will select/unselect all breakpoints in the group.
1. Move breakpoints into/outof Breakpoint group .
    - Drag and drop
      - drag one/multi break points and drop into another group
      - Breakpoint Group is not draggable

> Note: not allow one breakpoint to occur in multi groups in this design.

Bonus:
- The color of breakpoints in different Breakpoint Group could be different, but it seems it will be cycled.

### Hello team

If I could give a PR, could this feature be discussed by the team?

**Comment by roblourens** [comment]
Thanks but I believe that this kind of advanced management is probably best suited for an extension. Maybe there is already an extension that does this kind of thing. But you could do some cool stuff just with the existing extension API
