### ISSUE TITLE
My extension crashed so bad that uninstalling and reinstalling it doesn't work

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#16452]
I've been developing VSCodeVim, and the recent version has locked up - it doesn't respond to any extension-specific keystrokes. It's so bad that:

Is it possible to debug something like this? Can I break the execution of JS inside VSCode to see where the lock up is occurring? (I'd like to do this since the debug run is not helping me.)

**Comment by chrmarti** [comment]
- Does Code itself still respond?
- When you start the extension with F5 in debug mode, can you pause the execution in the debug viewlet or does that not work? What does the debug console show?
- What do the Developer Tools of the target show in their console?

**Comment by jrieken** [comment]
@johnfn Can you provide more information please?
