### ISSUE TITLE
Settings editor codicon colour incorrect when using keyboard to navigate list of settings

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#164510]
1. Open an untrusted workspace.
2. Open the workspace-restricted settings in the Settings editor. Settings with indicators with warning codicons should show up.
3. Switch to the light theme.
4. Use the keyboard to navigate up and down the list of settings.
5. The warning codicon sometimes renders white, which contrasts terribly against the grey background colour.

A screenshot showing the codicon:
![The warning codicon is underlined red. It is barely noticeable looking at the entire setting row](https://user-images.githubusercontent.com/7199958/197633109-62ac60b6-be18-4543-9e20-a22e381a87df.png)

**Comment by alexr00** [comment]
I can't get the warning icon to show at all. I tried following the steps in https://github.com/microsoft/vscode/issues/164482, but I wasn't able to get them to work again.

**Comment by rzhao271** [comment]
The easiest way to get to a view with those icons is to click on the X workspace settings link while being in restricted mode.

![Screenshot of manage workspace trust pane in restricted mode](https://user-images.githubusercontent.com/7199958/198373686-a0e893df-f3a0-445e-af3e-b4dc353b70ae.png)
