### ISSUE TITLE
Test: quick fix contrib

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#164526]
Refs https://github.com/microsoft/vscode/issues/162950

- [x] Windows @hediet 
- [ ] macOS @eleanorjboyd 
- [x] Linux @andreamah 

Complexity: 4

Authors: @meganrogge @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164526%0A%0A&assignees=meganrogge,Tyriar)

---

Terminal quick fixes can now be contributed via an extension's contribution in a package.json as described here 

https://github.com/microsoft/vscode/blob/476360fbc4027b7d2e194c5321d7a3c3ee04886e/src/vs/workbench/contrib/terminal/common/terminal.ts#L719-L757

We've moved several of the builtin terminal quick fix actions over to using this contribution point. 

Verify that they still work:
- `git push` on a branch without a remote should allow you set the upstream
- `git push --set-upstream...` should prompt you to create a PR

Note that this is still a proposed API contrib, so must be explicitly enabled.

```
  "enabledApiProposals": [
    "contribTerminalQuickFixes"
  ],
```

**Comment by eleanorjboyd** [comment]
same issue as @andreamah, checking mine off but agree with what she wrote in the ticket
