### ISSUE TITLE
Test updating markdown paths  on file move/rename

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#164522]
Test for #148146

- [x] Mac @weinand 
- [x] Linux @andreamah
- [x] Windows @amunger

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164522%0A%0A&assignees=mjbvz)

---

## Overview
This new feature allows markdown to automatically update all markdown links when a file is renamed/moved in the workspace. This is only supported for file moves/renames that happen within VS Code's explorer. It is also only supported for markdown style links (not html `<a>` links inside markdown)

## Testing
- Enable this new behavior using `"markdown.updateLinksOnFileMove.enabled": "prompt"`
- Create some markdown links to local files:

     For this, try out some of these variants:

    - `[text](/workspace/root/path/to/file.md)`
    - `[text](relative/path/to/file.md)`
    - `[text](path/fileNoExt)` (should reference `path/fileNoExt.md`)
    -  `[text](path/file.md#some-header)`
    -  `![alt](path/img.png)`
    -  `[definition]: /path/to/file.md`
    
- Ensure that with `prompt`, renaming or moving any `md` or image file triggers a dialog that lets you update all markdown links

- Now try renaming some directories that contain the referenced files. Ensure this also triggers a update

- Finally try changing `markdown.updateLinksOnFileMove.externalFileGlobs`. This setting controls the types of files we try updating paths for (we always enable it for markdown files).

    The default value enables it for common image file names. Try enabling it for `.js` files or some other format too

**Comment by weinand** [comment]
@mjbvz above you mentioned
> `[definition]: /path/to/file.md`

What does it do? I could not find it anywhere.

**Comment by amunger** [comment]
Created https://github.com/microsoft/vscode/issues/164650, but not directly related to the feature
