### ISSUE TITLE
action decoration in settings file makes it hard to put cursor at end of line

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#16457]
i opened my settings.json and wanted to add a new setting at the end of the file.  I moved my mouse to the end of the line and clicked to set the cursor, but instead i clicked on the decorator and i got a drop down.

So to put the cursor at the end of the line with the mouse i have to either click after the decorator or click in the single space between the end of the line and the decorator. 

If all lines had a decorator at the end i could get used to having to click way to the right. but not all settings have drop downs.

i dont have a good solution :).  Maybe the decorator needs to show up right next to the value so there isn't the temptation to try to click between the end of the word and the decorator.

**Comment by sandy081** [comment]
I liked the idea but closer to the value might interfere more with the hover text (which is true already). But, I see the issue of having space between the value and decorator.

**Comment by bpasero** [comment]
I am also hitting this and think the position of the action needs to change. We should throw in some UX ideas on this and decide.
