### ISSUE TITLE
Font is blurry

### ISSUE THREAD

**Issue by er3456qi** [Microsoft/vscode#16451]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|python|donjayamanne|0.5.5|
|Theme-Gooey|gerane|0.0.2|

---

The word is foggy. my screen is 13.3 inch, and the resolution is 1080p, system scale is 150%.

Steps to Reproduce:

1. do not need.
2.

**Comment by bpasero** [comment]
@er3456qi 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
