### ISSUE TITLE
Test: Finalized Localization API

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode#164500]
Refs: https://github.com/microsoft/vscode/issues/158213 

- [x] anyOS @lszomoru
- [x] anyOS @joyceerhl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164500%0A%0A&assignees=TylerLeonhardt)

---

This iteration we have finalized the localization `l10n` API 🎉  Since this API has been reviewed and tested a ton from non-built-in extensions, I thought it would be fitting to focus the finalization of this API on extensions that ship with VS Code. The goal here is to replace `vscode-nls`'s `localize()` calls with the new `vscode.l10n.t` calls.

#### Step 1: change the code

1. Pick an extension that currently relies on `vscode-nls` (check package.json) and has some `localize(` calls in it
2. migrate from the `vscode-nls` usage to the new `vscode.l10n` API. I'm leaving this intentionally vague so you look at the typings to guide you on usage
3. Since you've now migrated an extension, you might as well submit a PR 😄 

#### Step 2: testing the change

You can easily verify the English works by triggering some of strings you've changed and ensuring that they're still English and that parameters work and whatnot.

I wish I could have you test against an actual language, but that would be way too involved since you'd need to modify a Language Pack you have already installed (hacky) or wait for the PR to go in, and then wait for the translations to flow through and then wait for a Language Pack to be released.

I can go ahead and verify your changes once the PRs are in and the translations have flown to a released Language Pack.

**Comment by lszomoru** [comment]
Great job @TylerLeonhardt 👏🏻
