### ISSUE TITLE
zooming triggers notification

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#164582]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Disable builtin gulp and grunt extensions
2. Open VSCode folder
3. Zoom In
4. A notification is shown `There are task errors. See the output for details.`
5. Close the notification
6. Zoom in again
7. The notification is shown again `There are task errors. See the output for details.`
8. Close the notification
9. Zoom out
10. The notification is shown again `There are task errors. See the output for details.`

![zooming-notification](https://user-images.githubusercontent.com/23744935/197775334-9d24edab-b5e1-494f-8cbf-dc705a3187b0.gif)

**Comment by meganrogge** [comment]
when the zoom happens, it triggers a refresh of the lines w conpty, so this is expected
