### ISSUE TITLE
C code coloring goes wrong after a line break backslash 

### ISSUE THREAD

**Issue by DanielKristofKiss** [Microsoft/vscode#16456]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
---

Steps to Reproduce:
C source file content
```c
/* comment - green
 */
#define macro( arg ) \
        somerthingelse(arg)

/* comment - blue */

typedef int blueint;
typedef int whiteint;
```
![image](https://cloud.githubusercontent.com/assets/4526629/20865652/15599960-ba18-11e6-98b9-a27457ac68f9.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#185
