### ISSUE TITLE
Test: better branch creation flow in VS Code for the Web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164518]
Refs: https://github.com/microsoft/vscode-remote-repositories-github/issues/255, https://github.com/microsoft/vscode-remote-repositories-github/issues/253, https://github.com/microsoft/vscode-remote-repositories-github/issues/252, https://github.com/microsoft/vscode-remote-repositories-github/issues/256

- [x] anyOS @sandy081
- [x] anyOS @mjbvz

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164518%0A%0A&assignees=joyceerhl)

---

When using GitHub Repositories, Azure Repos, and Remote Repositories in VS Code for the Web, there are now better flows for committing to protected branches and switching to newly created branches.

1. Open https://insiders.vscode.dev/github/microsoft/vscode
2. Try to commit directly to the main branch
3. Verify that you are told the main branch is protected and you have a flow to create a new branch
4. Configure the following settings in your user preferences
    ```json
    {
        "remoteHub.switchToCreatedBranch": "always",
        "git.branchPrefix": "your/prefix/here/",
        "git.branchProtectionPrompt": "alwaysCommitToNewBranch"
    }
    ```
6. Repeat steps 1-3 and ensure that the setting values you configured are honored
7. Use the ref picker to create a new branch and verify that `remoteHub.switchToNewBranch` is honored there as well

**Comment by mjbvz** [comment]
Works great in my testing!
