### ISSUE TITLE
UI stuck in debugging

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#164553]
Testing #164529

* install [mock-debug-0.51.0.zip](https://github.com/microsoft/vscode/files/9856766/mock-debug-0.51.0.zip)
* open [sampleWorkspace](https://github.com/microsoft/vscode-mock-debug/tree/main/sampleWorkspace)
* start debugging
* type `startDebugging` in the debug console
* press the stop button on "Debug readme.md 2"
* pressing the top level stop button has no effect anymore and debugging is always stuck in an exception

https://user-images.githubusercontent.com/5047891/197734496-fff3451f-3ab4-4d19-baa4-50fbda3fb6b0.mp4

**Comment by luabud** [comment]
I can repro this as well:
![mockdebugbug](https://user-images.githubusercontent.com/45497113/197849991-d8cb3faf-f50c-4ec5-8c24-aa79bb7b3173.gif)

**Comment by lramos15** [comment]
Mine gets stuck with no callstack but just the debug toolbar and I can't get it to go away. Didn't file a new bug as I assume they're related

**Comment by roblourens** [comment]
Thanks. I guess it was actually pretty easy to hit that issue. But it's a long existing issue not related to the new API and this should actually make it much easier to fix, vs the rare cases where it shows up in js-deubg.

**Comment by connor4312** [comment]
Going to take this since I'm on the other issue 😛
