### ISSUE TITLE
Test markdown insert link commands

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#164525]
Test for #162809

- [x] Mac @meganrogge
- [x] Linux @chrmarti
- [x] Windows @joyceerhl

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164525%0A%0A&assignees=mjbvz)

---

## Summary
This iteration, we introduced two new commands to help user insert links and images into their markdown

- `Markdown: Insert link to file in workspace` inserts a link to any other file in the workspace (if you are on desktop, you can also insert links to other files on disk)

- `Markdown: Insert image from workspace` inserts an image from the workspace

## Testing
Try out these two commands and confirm they do the expected things. Some cases to test:

- These commands should insert relative paths to the image or file
- The insert image command should only let you select image files
- The commands should create a snippet that lets you fill in the text/alt text of the link or image
- The commands should let you insert multiple images / links by selecting multiple items
- The commands should be multi-cursor aware. At present, this just means they duplicated the inserted text. We so  support the `spread` behavior from VS Code's multi-cursor pasting (where if you select 3 files with 3 cursors, we insert each individual file into the corresponding cursor)

**Comment by chrmarti** [comment]
"We so support the spread behavior": We should, I guess (since I don't see it).

**Comment by meganrogge** [comment]
Very useful 👏🏼
