### ISSUE TITLE
I think VS Code  C++ synatax don't good

### ISSUE THREAD

**Issue by mobi12** [Microsoft/vscode#1645]
like head file, can't synatax.

**Comment by bpasero** [comment]
@mobi12 can you attach an example?

**Comment by OshotOkill** [comment]
@bpasero He says head files are not being highlighted in .cpp files while I haven't met this problem.

![1](https://cloud.githubusercontent.com/assets/6079112/12006848/efe60ef6-ac22-11e5-8ec8-3a93a7f77d6d.PNG)
