### ISSUE TITLE
Allow me to remove old synced browsers

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#164575]
Testing #164451

Opening my sync activity I see the following:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/5047891/197766740-5de6c37c-a5b2-4e26-8c7c-ff87f7ab4fe4.png">

I don't know what all those Web entries are and I would like to remove them such that they don't show up here nor do they have the ability to push up data.

**Comment by sandy081** [comment]
There is a context menu action to turn off sync from the machine which will remove the entry from the list

<img width="349" alt="image" src="https://user-images.githubusercontent.com/10746682/198045198-34e3bd9a-3790-4fac-89b2-6a45a58119d5.png">
