### ISSUE TITLE
npm.scriptExplorerExclude from .vscode/settings.json do not work

### ISSUE THREAD

**Issue by Sovgut** [microsoft/vscode#164557]
Type: <b>Bug</b>

When added any of script name, this config excluded all scripts instead of string items in config.

for example we have "start", "dev" and "build" in scripts, after adding "start" and "build" in this config, explorer view exclude all scripts and showing "No scripts found."

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.31GB free)|
|Process Argv|--crash-reporter-id 1ce0b300-83b3-4db2-8041-5a6a9c0e7b7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.14.1
swagger-snippets|adi|0.0.1
gitignore|cod|0.9.0
vscode-eslint|dba|2.2.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
dotenv|mik|1.0.1
JetBrainsIcons|Mos|1.0.4
vscode-docker|ms-|1.22.2
material-icon-theme|PKi|4.21.0
prisma|Pri|4.5.0
vscode-rapidapi-client|Rap|1.6.0
vscode-yaml|red|1.10.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537

```

</details>

**Comment by meganrogge** [comment]
can you pls provide me w your tasks.json file?

**Comment by Sovgut** [comment]
@meganrogge this issue is not related to tasks, this is related to npm scripts

If I understand correctly, `npm.scriptExplorerExclude` should remove unnecessary scripts from npm scripts view.

My current view:
![image](https://user-images.githubusercontent.com/26426861/197793499-c3e69b25-d4da-4ffd-aa34-8decac99cbb5.png)

Expected view:
![image](https://user-images.githubusercontent.com/26426861/197794946-ec4fabe7-88cb-4d69-bc1b-5e7e4c70fa27.png)

View with script exclude config:
![image](https://user-images.githubusercontent.com/26426861/197794796-8df66881-4bb8-4062-8d9f-fab7ddb0d102.png)

Used config in `.vscode/settings.json`:
```json
{
  "npm.scriptExplorerExclude": [
    "format",
    "build",
    "prepare",
    "start",
    "start:drfqdev",
    "start:production",
    "mongod"
  ]
}

```

**Comment by Sovgut** [comment]
Added tasks and nothing changed.

```json
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "npm",
      "script": "start:development",
      "group": "none",
      "label": "npm: start:development"
    },
    {
      "type": "npm",
      "script": "start:watch",
      "group": "none",
      "label": "npm: start:watch"
    }
  ]
}
```

**Comment by babakks** [comment]
I'll submit a PR.

**Comment by Sovgut** [comment]
@babakks Thanks.

I have made changes in configuration, and its works as should.
```json
{
  "npm.scriptExplorerExclude": [
    "format",
    "build",
    "prepare",
    "start$",
    "mongod",
    ":drfqdev",
    ":production"
  ]
}
```

![image](https://user-images.githubusercontent.com/26426861/198372449-bc65ec22-f0d1-4b64-9325-e6ef18f33342.png)
