### ISSUE TITLE
Test `Restrict Search to Folder` and `Exclude Folder from Search` commands

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#164506]
Refs #161864, #162628

- [x] macOS @eleanorjboyd
- [x] linux @aeschli
- [x] windows @devinvalenciano

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164506%0A%0A&assignees=andreamah)

---
## Set up:
Make sure that you have the latest insiders version.

### Intro
This testplan item tests the new context menu shortcuts to add folders to the include/exclude text field of the search viewlet.

<img alt="image" src="https://user-images.githubusercontent.com/31675041/197628602-7b233e87-a4b1-4e65-9c96-e7833eda4c7b.png">

`Restrict Search to Folder` works similarly to the `Find in Folder` that you see when you right-click a folder in the explorer viewlet. It sets any selected folders to the paths seen in the `files to include` text box in the search viewlet (and will subsequently perform a search if `searchOnType` is enabled).

<img alt="image" src="https://user-images.githubusercontent.com/31675041/197628943-62523243-fd9d-4c9e-8a9d-ac234ece232e.png">

Similarly, `Exclude Folder from Search` sets any selected folders to the paths seen in the `files to exclude` text box.

<img alt="image" src="https://user-images.githubusercontent.com/31675041/197628972-58f38e58-835b-4e97-82b4-8df278e6ce53.png">

Example of use:
[![Image from Gyazo](https://i.gyazo.com/78b9d312811f43fe55663b9a1dc512ff.gif)](https://gyazo.com/78b9d312811f43fe55663b9a1dc512ff)

### Test Items
- Test that the two new options correctly exclude/include files in the search results. 
    - `files to include` should only include its glob paths in the results.
    - `files to exclude` should prevent any of its glob paths from appearing in the search results.
- Try selecting multiple folders at once and setting the boxes for multiple paths at once.
- Is the naming for the commands clear?

Thanks for testing! 😊

**Comment by aeschli** [comment]
Works well!
