### ISSUE TITLE
Insert Link to File: Only folders can be selected

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#164549]
Testing #164525

On Ubuntu 20.04 the OS dialog is opened for folder selection and I can't select files:
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/9205389/197727739-91b7e380-3f22-47c9-ae54-f75818208ea6.png">

(Interestingly the simple file dialog works as expected.)

**Comment by joyceerhl** [comment]
I also see this behavior on Windows

**Comment by mjbvz** [comment]
Looks like only Mac supports selecting both files and folders :/
