### ISSUE TITLE
dropdown decorator only works for first setting with multiple settings on a single line 

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#16458]
if i have two or more settings on a single line, the decorator shows up for the first thing on the line...

![image](https://cloud.githubusercontent.com/assets/1487073/20865900/59b4ffa4-ba1e-11e6-8c8b-b4b7f7647559.png)

i expected to be able to hover around the "false" value in the middle of the line and see a decorator there that would give me the dropdown.

**Comment by sandy081** [comment]
There is a plan to move away from using decorations for rendering copy actions to use zone or overlay widgets. This will be considered then.
