### ISSUE TITLE
link updating cannot be restricted for built-in types 

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode#164587]
Testing #164522

By using a glob pattern `/foo/**/*.x` for the `markdown.updateLinksOnFileMove.externalFileGlobs` setting, it is possible to restrict link updating only to files inside the `foo` folder.

The same is not possible for the built-in file types "md" (and common image file formats).

Wouldn't it make sense to support overriding the built-in types?

E.g.:
- if the `markdown.updateLinksOnFileMove.externalFileGlobs` setting is used, then all built-in types are ignored, or
- if a specific built-in type is used for the setting (e.g. `/doc/**/*.md`), it takes precedence over the built-in one (`**/*.md`).

**Comment by mjbvz** [comment]
I think this makes sense. I'm going to rename this setting and also include the markdown file extensions in the new default value
