### ISSUE TITLE
`ms-vscode.js-debug` is shipped with version 1.72.0 in Insiders but 1.72.1 is in the marketplace

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#164592]
I use `"extensions.autoUpdate": false`. This causes that extensions need to be manually updated. The builtin debugger wants to update itself to `1.72.1` and that ends up showing a badge on the Extensions viewlet. But I actually don't want to install in my user extensions folder `ms-vscode.js-debug`, I would like to get the version which is tested with our integration tests (`1.72.0`). That means I'm stuck with the badge, which I don't like.

My question is why are we keeping things out of sync? If my understanding of how `"extensions.autoUpdate": true` (the default) works, then it means that effectively all users of Insiders get today `ms-vscode.js-debug@1.72.1`, but `1.72.1` is never tested by our integration test, only `1.72.0` is. Finally, this also means that once we promote the Insiders build to Stable the world will receive `ms-vscode.js-debug@1.72.0` which is not selfhosted on by Insiders users, since they're all sitting on the auto-updated `1.72.1`.

**Comment by sandy081** [comment]
Auto updating of built-in extensions is enabled in insiders for js-debug extension so that it will move away from js-debug-nighlty extension. 

@connor4312 Can you please respond to @alexdima's question from above that how you are handling it with your extension?

**Comment by sandy081** [comment]
@connor4312 May I know if your extension still depends on auto updating in insiders? I would like to remove this feature completely.

**Comment by connor4312** [comment]
Currently js-debug still uses a separate nightly version since there was ambiguities/questions about how it would be supported on Insiders.

**Comment by sandy081** [comment]
Does it mean, auto updating of extensions in insiders is not being leveraged. If so, I would revert this feature and go back to square one and understand what is needed to for js-debug to not to use separate nightly. Is that sounds good?

**Comment by connor4312** [comment]
sure. The last time I tried the difficulty was that one could not switch a built-in extension to be a prerelease extension, so after finding that I went back to having the nightly extension be published.

**Comment by sandy081** [comment]
Removed supporting updating system extensions every where.
