### ISSUE TITLE
Test: editor word wrapping while using a screen reader

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#164512]
Refs #95428

- [x] Windows @alexr00 
- [x] macOS @mjbvz 
- [x] Linux @rzhao271 

Complexity: 3

Authors: @meganrogge @alexdima @isidorn 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23164512%0A%0A&assignees=meganrogge,alexdima,isidorn)

---

We formerly have disabled word wrapping outright when a screen reader is detected to prevent a wrapped line from being read repeatedly while navigating within its parts.

For example a move of the cursor from here

```
this is a short 
sentence[CURSOR] with
wrapping
```
to here
```
this is a [CURSOR]short 
sentence with
wrapping
```
used to trigger the screen reader to read `this is a short sentence with wrapping` `this is a short sentence with wrapping`

Prereqs:
-  `editor.accessibilitySupport` & `editor.wordWrap` are enabled
-  you're using a screen reader

Verify that:
- only the line with the cursor on it is read 
- IME support works

Also try modifying the value of `editor.wordWrap` and `editor.wordWrapColumn`

**Comment by mjbvz** [comment]
Works great in my testing with VoiceOver!

**Comment by rzhao271** [comment]
To get Orca to read a line, I had to double-click on a line to select a word, and then click again after for it to start reading. This behaviour shows up in Stable as well, though.
