### ISSUE TITLE
Testing terminal quick fix: contributed quick fixes are not working

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#164660]
Testing #164526

I have this under `contributes` in my extension's package.json:

```
"terminal": {
			"quickFixes": [
				{
					"id": "test",
					"commandLineMatcher": "cd",
					"linkToOpen": "http://google.ca/",
					"outputMatcher": {"lineMatcher": ".*No such file or directory.*", "anchor": "bottom", "offset":0, "length":2}
				},
		  ]
}
```

And running `cd` into an invalid directory isn't giving me the quick pick suggestion while the extension is active.
<img alt="image" src="https://user-images.githubusercontent.com/31675041/197902204-a6f54923-766f-4e1e-8036-8f87928bf3f8.png">

Let me know if I executed this wrong! An example somewhere would also be super helpful! :D

**Comment by meganrogge** [comment]
I think this is probably because you don't specify any regex groups within your `outputMatcher` `lineMatcher`

**Comment by meganrogge** [comment]
we require a `group` to be used within the `linkToOpen` or `commandToRun` 

here's an example

```
{
				"id": "terminal-sample fix",
				"commandLineMatcher": "echo [^\\s]+",
				"outputMatcher":  {
					"lineMatcher": "(?<input>[^\\s]+) (?<inputtwo>[^\\s]+)",
					"anchor": "bottom",
					"length": 1,
					"offset": 0
				},
				"linkToOpen": "https://google.com/${group:input}${group:inputtwo}"
			},
```

**Comment by meganrogge** [comment]
here's your example but using a group:
```
{
						"id": "test",
						"commandLineMatcher": "cd [^\\s]+",
						"linkToOpen": "http://google.ca/${group:fakename}",
						"outputMatcher": {"lineMatcher": ".*no such file or directory: (?<fakename>[^\\s]+)", "anchor": "bottom", "offset":0, "length":1}
	}
```

**Comment by andreamah** [comment]
Works well on Linux with the capturing groups, thanks for the help!
