### ISSUE TITLE
workbench.js:2734 [uncaught exception]: EvalError: Possible side-effect in debug-evaluate

### ISSUE THREAD

**Issue by levivilet** [microsoft/vscode#164616]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Open Devtools in VSCode
2. Go to `Console` tab, next to `Elements`
3. Type something, e.g. `console.log("hello world")`
4. many error messages are displayed in the console: 

```
[uncaught exception]: EvalError: Possible side-effect in debug-evaluate
EvalError: Possible side-effect in debug-evaluate
SyntaxError: Unexpected end of input
SyntaxError: Unexpected end of input
[uncaught exception]: SyntaxError: Unexpected end of input
SyntaxError: Unexpected end of input
SyntaxError: Unexpected end of input
SyntaxError: Unexpected end of input
SyntaxError: Invalid or unexpected token
EvalError: Possible side-effect in debug-evaluate
```

![eval-error-cropped](https://user-images.githubusercontent.com/72156503/197832031-8a9ac0b3-3812-46a9-8f59-55a608f31b40.gif)

### Additional information: 
- The error messages do not occur when using Google Chrome 
- The error messages do not occur in VSCode 1.70.0

**Comment by roblourens** [comment]
Weird, I don't see that

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/166144
