### ISSUE TITLE
Windows 11 context menu usually don't show

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#164627]
Testing #164465

Sometimes the Windows 11 context menu shows, sometimes it doesn't (but usually it doesn't). For example, I did the following with the user installer:

Make sure the menu entry works:
1. Install VS Code, choose the option to add to the context menu.
1. Make sure that the menu is present when right-clicking on files/directories.

And ended up with this state:
- Only old context menu on files
- No context menu entry on folder

**Comment by deepak1556** [comment]
Possibility of a corrupted installation, old context menu will not show up when new context menu is installed. Can you try the following steps,

1) Uninstall insiders, make sure you don't have neither system and user installation.
2) Install version which has the old context menu https://az764295.vo.msecnd.net/insider/504c5a768a001b2099dd2b44e9dc39e10ccdfb56/VSCodeUserSetup-x64-1.73.0-insider.exe . Make sure to check the context option for files in the setup wizard.
3) Launch the verison normally
4) Open file explorer and see that old menu shows up for both files, folders.
5) Go back to insiders and check for updates
6) Wait for the gear icon to show it is ready for update
7) Close all open OS file explorers
8) Update to the newer version
7) Open file explorer and you should only see new menu for both files, folders.

**Comment by deepak1556** [comment]
@alexr00 if you have `windows sandbox` feature enabled, can you test after disabling it.

**Comment by alexr00** [comment]
I set `"window.experimental.useSandbox": false`, and then tried the steps above. The context menus worked as expected.

I started doing the full test plan again and sometimes it still didn't work:

User install update from old ✅ (after seeing all the others fail, I went back and tried this again. Second time was ❌)
User install update from new ❌
User install without update ❌
System install update from old ❌
System install update from new 
System install without update ❌

**Comment by deepak1556** [comment]
Sorry for the confusion, I was referring to the OS sandbox if you had it enabled. The context menu does not work with this OS feature enabled.

![Screenshot_20221027_040304](https://user-images.githubusercontent.com/964386/198215013-9929ac32-10f6-460b-b944-f2cfdf7578c5.png)

**Comment by alexr00** [comment]
I don't have that feature enabled:

![image](https://user-images.githubusercontent.com/38270282/198312078-69310d9d-263f-43e7-8a0f-47ea7b61dfdf.png)

**Comment by RoadToDream** [comment]
> Sorry for the confusion, I was referring to the OS sandbox if you had it enabled. The context menu does not work with this OS feature enabled.
May I ask why the context menu will not show when Sandbox is enabled? Are there some security concerns?

**Comment by deepak1556** [comment]
Closing as there has not been reports from insiders since the feature shipped.
