### ISSUE TITLE
Powershell Parser can't tell the difference between - (n-dash) and – (m-dash)

### ISSUE THREAD

**Issue by jongross4** [Microsoft/vscode#16468]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14975
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.1.6|
|PowerShell|ms-vscode|0.7.2|
The parser is treating an n-dash and m-dash as equivalent.  UTF-8 encoding changes m-dash to â€“ which PowerShell can't parse.

---

Steps to Reproduce:

1.
2.

**Comment by chrmarti** [comment]
Could you provide steps to reproduce? (It's unclear which parser you mean.)

**Comment by chrmarti** [comment]
Closing after not having received additional information.
