### ISSUE TITLE
Full Windows file path in markdown link does not work

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#164650]
1. create two markdown files and save them
2. right click the tab of one markdown file and copy the path 
3. create a reference link with that path string
`[fullpath](C:\src\test\2\folder\reference1.md)`
:bug: link does not work

neither doubling the slash character, nor switching slash direction helped. I could not figure out how to get a full path to work

**Comment by mjbvz** [comment]
This is by design since AFAIK widows style paths are not valid markdown paths. If you really want to create a absolute path, you can use a `file:///` path, but this generally isn't too helpful (and I'm not sure how well this is supported by our language service since it hasn't been a priority)
