### ISSUE TITLE
Any way to add custom jsdoc tag and get autocomplete ?

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#164620]
@mjbvz

<img width="678" alt="image" src="https://user-images.githubusercontent.com/41773861/197837358-1273d7f4-4f0b-4ef2-b3d0-9924c9969786.png">

**Comment by mjbvz** [comment]
This can either be provided by an extension or a [TypeScript service plugin](https://github.com/Microsoft/TypeScript/wiki/Writing-a-Language-Service-Plugin)
