### ISSUE TITLE
PaneView calls renderBody even when the pane is collapsed

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#164662]
**Repo**

1. In explorer, collapse the timeline view
2. Create a breakpoint in [`TimelinePane.renderBody`](https://github.com/microsoft/vscode/blob/36fdf6b697cba431beb6e391b5a8c5f3606975a1/src/vs/workbench/contrib/timeline/browser/timelinePane.ts#L885)
3. Reload window

**Bug**
See the breakpoint being hit even through the contents of the timeline are not visible

This is caused by this code:
https://github.com/microsoft/vscode/blob/84a929b8b7ea25af7f2c5fb4e76b6a65028a7a6c/src/vs/base/browser/ui/splitview/paneview.ts#L252

It seems  to me we should try to defer this work until the view actually becomes visible

**Comment by sbatten** [comment]
@mjbvz would you be willing to verify for completeness?

**Comment by mjbvz** [comment]
Works great!
