### ISSUE TITLE
CMD + Backspace while at Col 1 should remove line

### ISSUE THREAD

**Issue by patrickmcd** [microsoft/vscode#16460]
- VSCode Version: 1.7.2
- OS Version: macOS 10.12.1

CMD + Backspace at the end of a line properly removes the characters line, leaving the cursor at Col 1. But using the same combo a second time does nothing. You have to release CMD for Backspace to remove the line. You should be able to keep CMD pressed and either remove all the characters in a line, or remove the line itself if the line is empty.

Steps to Reproduce:

1. Starting at the right of a line of characters, use CMD + Backspace to remove the characters.
2. Hit the same combo again, and the line isn't removed.

**Comment by chrmarti** [comment]
You can use `Shift+Cmd+K` to delete the current line.

**Comment by patrickmcd** [comment]
Sure, but I think what I'm explaining is standard for other editors and text areas (like the one I'm typing in now).

**Comment by chrmarti** [comment]
Indeed, reopening to track as a feature request.

**Comment by atipugin** [comment]
+1

**Comment by changkun** [comment]
I have the same issue and I am on mac. The vscode version is 1.12.2.

The cmd+backspace works fine when edit text focused. So, I added a key binding for clear all left action when terminal focus:

```json
[
{ "key": "cmd+backspace",         "command": "deleteAllLeft",
                                     "when": "terminalFocus" }
]
```

However, the cmd+backspace doesn't work. What did I do wrong?

**Comment by chrmarti** [comment]
@changkun This issue is about the behavior in the text editor when the cursor is at the begin of the line. Please open a separate issue for your request (which might depend on the shell you are using).

**Comment by lukeed** [comment]
Any update on this? Or any short-term fix? TBH it's really the only lingering habit I have that trips me up in Code.

**Comment by chrmarti** [comment]
I just found that Cmd + Delete (delete right of cursor) works. (But no update.)

**Comment by poohitan** [comment]
I see that a corresponding pull request is already merged. Can anyone tell me is this already included in release build? I still encounter this issue on the latest editor version.

**Comment by chrmarti** [comment]
@poohitan Not sure which pull request you refer to, but the above one seems still pending.

**Comment by poohitan** [comment]
@chrmarti I mentioned the one above, I wonder how did I saw it as merged, I guess it was the lack of sleep :). Sorry.

**Comment by zArubaru** [comment]
Just switched over from Sublime, wishing this would be fixed :/

**Comment by alastairjwright** [comment]
Cmd + backspace is the fastest way to delete lines of code in an upward direction. 
Really hoping this gets fixed!

**Comment by jandor64** [comment]
Similarly stymied by this after moving from Sublime, I have the following short-term fix. This is a 'close enough' fix to what I am used to, but with one caveat: It doesn't stop at the linebreak like Sublime, but always removes the line break you're up against.

![deleteline](https://user-images.githubusercontent.com/2841721/42119242-b347deb6-7bbe-11e8-9425-b81e1d25c603.gif)


1. Install [Macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) extension
2. Create new macro in your settings:
```
"macros": {
    "deleteLineReturn": [
        "deleteAllLeft",
        "deleteLeft"
    ]
}
```

3. Assign key binding:
```
{
    "key": "cmd+backspace",
    "command": "macros.deleteLineReturn",
    "when": "editorTextFocus && !editorReadonly"
}
```

I went with deleteAllLeft rather than deleteLine, since you may wish to preserve what's to the right of your cursor.

**Comment by rebornix** [comment]
This is fixed already.
