### ISSUE TITLE
Disabling windows' recycling bin causes file deleting to fail

### ISSUE THREAD

**Issue by NotAdam** [Microsoft/vscode#1646]
It will fail every time showing the error:
```
Failed to move '{filename}' to the trash
```
and won't delete until you use the `Delete Permanently` option in the error message

**Comment by bpasero** [comment]
@NotAdam so you explicitly turned off the recycling bin on windows?

**Comment by NotAdam** [comment]
Yep.

**Comment by DerTolleEmil** [comment]
Beware that this might have nothing to do with disabling the recycle bin but rather the Electron bug which has also been mentioned here: https://github.com/Microsoft/vscode/issues/1485

I have my recycle bin enabled and I am also unable to delete files. I guess we won't know until Electron gets fixed.

**Comment by DerTolleEmil** [comment]
Small update: I remembered that I still have the installer from VSCode 0.10.1. I disabled my recycle bin and at least with 0.10.1 deleting files works as expected (they get deleted permanently without any errors). It's an old version for sure but at least at some point disabling the recycling bin worked.

**Comment by bpasero** [comment]
Windows 7?

**Comment by DerTolleEmil** [comment]
Yep, Win7 x64 fully patched.

**Comment by bpasero** [comment]
Ok this is #1485

**Comment by vitaminj** [comment]
Can one of this family of bugs be reopened? I have this issue on Windows 10 x64, with disabled Recycle Bin, not on a subst drive, but drive does have Bitlocker on.

**Comment by bpasero** [comment]
@vitaminj suggest to start a new issue with specific steps.
