### ISSUE TITLE
Handling of long lines issues

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode#164663]
Testing #164490

Version: 1.73.0-insider
Commit: a803dc359aa1ed48c7acf074dd81d6af1525c8c8
Date: 2022-10-25T05:18:20.717Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes

1) open a text file with a super long line, in my case 12K characters
2) toggle word wrap 
3) scroll to the end 
-> blue button (great!)
4) press the button

Observed issues:
1) toggling line wrap or closing and reopening the editor does not bring back the blue button (I would have expected so)
2) <kbd>cmd</kbd>+<kbd>ArrowRight</kbd> does **not** bring me to the end of the line but only half-way
3) scrolling to the end of line and mouse clicking puts the cursor in the same position as 2)
4) scrolling to the end of line does not show me the end of the line but is around 15 characters short

Recording of issues: https://share.cleanshot.com/zv8i3D

Proposal:
Rather than trying to deal with these long lines, use the button to enable line wrapping so that I can confidently deal with  these long lines.

**Comment by alexdima** [comment]
@kieferrm I see how it's broken in your screen recording, but I'm having a hard time reproducing. Could you please share your test file? I tried with [jquery-min.txt](https://github.com/microsoft/vscode/files/9870001/jquery-min.txt) and could not reproduce:

https://user-images.githubusercontent.com/5047891/198041809-925601e3-0fba-4826-b5f6-58a203042510.mp4

**Comment by kieferrm** [comment]
This is the file I used, zipped up: [test21.ipynb.zip](https://github.com/microsoft/vscode/files/9873417/test21.ipynb.zip)

**Comment by justschen** [comment]
with the exception of me attempting to test on 1.8 million characters, `cmd + arrow`, the button, reloading, etc, works like a charm.

![Screenshot 2024-03-26 at 4 58 41 PM](https://github.com/microsoft/vscode/assets/54879025/1c8e940a-0d08-4c00-b31a-e040b3b72c7b)

note that in large cases that the initial 12k from Kai, (I tested up to some 53k), `cmd + arrow` doesn't go to end of the line, but goes to the button. pressing the button, then `cmd + arrow` will then go to end of the line.

https://github.com/microsoft/vscode/assets/54879025/8e100ee3-28f9-4ded-8722-af9f2f514a2d
