### ISSUE TITLE
install-path not working on MacOS

### ISSUE THREAD

**Issue by paulacamargo25** [microsoft/vscode#164634]
Testing #164521

I tried the step 8, but it doesn't work. The install-path option  doesn't exist.

<img width="938" alt="Screen Shot 2022-10-25 at 11 36 57 AM" src="https://user-images.githubusercontent.com/17892325/197855578-97101338-6983-42fc-a833-82b1c78e5663.png">

When i tried with install-dir, didn't work either

<img width="1030" alt="Screen Shot 2022-10-25 at 11 39 40 AM" src="https://user-images.githubusercontent.com/17892325/197855513-f563380c-8ed9-4506-81f2-495fab58a4aa.png">

**Comment by connor4312** [comment]
The downloaded VS Code must be unzipped before it can be provided to `--install-dir`
