### ISSUE TITLE
Linux Kernel 6.x error

### ISSUE THREAD

**Issue by turowicz** [microsoft/vscode#164694]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
`d045a5ed` from snap

- OS Version: 
```
Operating System: Ubuntu 22.10                    
          Kernel: Linux 6.0.3-060003-generic
    Architecture: x86-64
 Hardware Vendor: Razer
  Hardware Model: Blade 14 _2022_ - RZ09-0427
Firmware Version: 2.02
```

Steps to Reproduce:

1. Run `code` in terminal
2. Get error:

```
/snap/code/111/usr/share/code/bin/../code: error while loading shared libraries: /snap/code/111/usr/share/code/../../lib/x86_64-linux-gnu/libXdamage.so.1: unsupported version 0 of Verneed record
```

**Comment by DonRichards** [comment]
I get the same error as well. The error clears when I reboot but will come back at some point during the day. I haven't figured out the pattern yet. I'm also on installed via snap.
- Ubuntu 22.10
- VSCode Version: 1.72.2
- Electron: 19.0.17
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Linux x64 6.0.2-060002-generic snap
- Sandboxed: No

**Comment by turowicz** [comment]
Removing the snap and installing from apt worked.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/165504
