### ISSUE TITLE
Comments panel: badge for the number of unresolved comments

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#164623]
Related to #127473, it would be useful to show the number of unresolved comments in a badge.

We currently show the number in the Problems view, but not Comments:
![image](https://user-images.githubusercontent.com/485572/197842784-1e832179-f081-4422-bf65-e2e7697832dc.png)

This would help users notice they have unresolved comments that needs their attention.

**Comment by alexr00** [comment]
I would accept a PR for this if you want to make one!
