### ISSUE TITLE
A11y_VisualStudioCodeClient_Search_Global Search_ Keyboard:Keyboard Focus moving from search to replace instead of moving to “Match case, match whole word and Use regular expression”

### ISSUE THREAD

**Issue by kjawale99** [microsoft/vscode#164697]
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #Device; #Visual Studio Code Client; #BM-VisualStudioCodeClient-MAC-Oct2022; #WCAG2.4.3; #Keyboard; #MAC; #Focus order;

### Environment and OS details:
Visual Studio Code Insiders
Screenreader: Voiceover

### Repro Steps:

1. Open Visual studio code editor
2. Using keyboard navigation View Menu Bar
3. Select search option
4. Verify that keyboard focus is moving from search to Match case, match whole word and use regular expression or not.

### Actual Result:
Keyboard Focus is moving from search to replace instead of moving to “Match case, match whole word and Use regular expression”.

### Expected Result:
Keyboard Focus should move from search to “Match case, match whole word and Use regular expression”.

### Attachment:
![keyboard issue sequence](https://user-images.githubusercontent.com/98745784/197940893-1835324d-235c-4737-bfda-5527701aa931.gif)

**Comment by isidorn** [comment]
This is as designed. We want the tab focus to move this way for a better user experience. User expect the first tab to go to the replace box.
Next tabs will move to the match case and other options.

Closing as designed
