### ISSUE TITLE
Typing to filter in second level of tasks quick pick doesn't work

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#164629]
1. Open a folder with some npm tasks
2. Run the command "Tasks: Run Task"
3. Type `npm` and choose the npm folder
4. ✅ npm tasks are listed
5. Start typing `install`, with the idea being that the quick pick will filter so that you can just hit enter to run `install`
6. Instead of filtering, the quick pick seems to go back to the previous level.

**Comment by meganrogge** [comment]
Repro:
https://user-images.githubusercontent.com/29464607/199295860-402afb9b-be55-4f65-af45-5de2512f3f5f.mov
