### ISSUE TITLE
Is it possible to get the detected tabSize value?

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#16466]
- VSCode Version: 1.8.0 Insiders
- OS Version: MacOS Sierra

I'm developing an extension and I would like to get the tabSize value of a file.

I tried this in a file that has a tab size of 4:

`vscode.workspace.getConfiguration("editor").get("tabSize");`

However, that returns `2` in a file that clearly has a tab size of `4`. I think this is because in my settings.json I set `tabSize` to `2`. 

Is it possible to get the effective value?

**Comment by jrieken** [comment]
See [`TextEditor.options.tabSize`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L624) in text editor options
