### ISSUE TITLE
Open file in editor not working when workspace name and folder name are equal

### ISSUE THREAD

**Issue by whme** [microsoft/vscode#164687]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Establish a remote connection to any linux system
2. Create the following folder structure:
```
foo/
|__bar/
|    |_main.py
|__foo/
     |_main.py
```
3. Open the top level `foo` folder in VSCode (`File` -> `Open Folder` -> chose top level `foo` folder)
![image](https://user-images.githubusercontent.com/43786929/197983897-b7427b55-d681-4666-812b-5d6c016c1f7f.png)
4. Open the integrated terminal and type the following file path
`bar/main.py`
5. Hover with your mouse cursor over the path and notice how VScode recognizes the full file path and suggests `Open file in editor`
![image](https://user-images.githubusercontent.com/43786929/197982374-1dfeb9d3-120e-4ea9-923a-74ee9a78db31.png)
6. Now type the following file path in the integrated terminal `foo/main.py`
7. Hover with your mouse cursor over the path and notice how vscode **does not** recognize the full file path
![image](https://user-images.githubusercontent.com/43786929/197982832-5a70d250-f837-46c9-a9e7-efecbfe633a6.png)

The issue seems to be that the subfolder `foo` shares it's name with it's parent folder `foo` which is opened in VSCode.
I would expect step 7 to work as step 5: VSCode should recognize `foo/main.py` as a valid path to a file and suggest to open it in the editor.

**Comment by Tyriar** [comment]
Nice catch, thanks for the report 👍

**Comment by whme** [comment]
Wow, that went by far smoother and faster than I expected! Thanks @Tyriar for looking into and fixing the bug! 🥇

**Comment by Tyriar** [comment]
@whme eventually I'll squash all these edge cases 😉
