### ISSUE TITLE
There is no way to execute the c# file that I just created and want to run

### ISSUE THREAD

**Issue by anirugu** [microsoft/vscode#164621]
I am writing c++ in Ubuntu and things going well with Vscode. What I am actually need to nothing special but writing algorithms. 

I just create a new file and debug the file and it's work pretty well. I was thinking about doing same with C# file. I have created the file, create the main method.

Now I am not able to debug the code. I run Debug, option appear for .net 5 blah blah. I select and debug. Nothing happen.

Is this means I can't create the file like Java or C++ ecosystem, if it's NO it's pretty bad. I see many youtube who are using single repos to write their algo code.

If this is possible, let me know how.  I am thinking their might be a system exists in C++ which automatically figure out the language (based on extension)  and debug the code for me.

Is it possible when directory have file in both c++ and c#. If you want to check this issue, tried to play with this repos https://github.com/anirugu/cpp

Thanks

**Comment by roblourens** [comment]
Please file an issue on the repo for the C# extension
