### ISSUE TITLE
Show running extension on web doesn't include builtin extensions

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#164618]
Testing #164515

For example, both the extension page and the running extension view shows the ipynb extension is not activated and running, but it serves the content for ipynb notebooks

**Comment by alexdima** [comment]
Any special steps to reproduce? I see builtin extensions in the Running Extensions view on web:

<img width="625" alt="image" src="https://user-images.githubusercontent.com/5047891/198064088-27e96610-0b93-4df0-a4fd-44c95251c956.png">

**Comment by rebornix** [comment]
ah actually it got activated, I missed it in the list. sorry about that.
