### ISSUE TITLE
Panel Terminal, Panel Console and easy switching between them

### ISSUE THREAD

**Issue by rhires** [Microsoft/vscode#16465]
- VSCode Version: 1.8.0-Insider
- OS Version: OS X Yosemite
Feature request: 
It would be nice to have a widget that allows me to easily switch between <code>OUTPUT</code>, <code>TERMINAL</code>, <code>DEBUG CONSOLE</code>, and <code>PROBLEMS</code>. 

While I'm at it, I wish that the upside down caret that minimizes the various terminals was a different thing, because I always want that thing to be my widget to choose among the 4 items I list above, because it seems that it would activate a menu or other visual cue to change between things. It should be a little 'x'.

**Comment by chrmarti** [comment]
Not exactly what you describe, but we have the `Open View` command, that shows a list of views/panels to choose from. You could bind that to a keyboard shortcut.

Keeping this for the feature request to switch between panels.

**Comment by bgashler1** [comment]
We are currently investigating this.

One solution we're exploring is adding tabs to the panel: once a panel is open, you could switch between other panels right where you are.

![horizontal-panels-combined-03-with-notifications](https://cloud.githubusercontent.com/assets/11839736/20899077/b6d11f32-badd-11e6-9d7d-a86f6d25140f.png)

Would love the community's feedback on this. 👍 👎 

----

*These tabs would be specific to panel only (i.e. you wouldn't be able to drag editor-tabs into the panel or panel-tabs into the editor—hence why they are designed differently than document tabs).

**Comment by rhires** [comment]
I think these should be menu-like, where that downward facing caret is on the right, so I can pick from them, rather than looking like tabs...I think that the tabs like this makes the UI inconsistent, because it changes the metaphor somewhat. If I'm running bash twice, for example, where is the other tab for that going to go? 

Or maybe repurpose (a little) the widget that shows 1. bash so that it contains more than 1 bash, plus the other console items? And it seems more natural than having those tabs.

**Comment by kelvich** [comment]
Isn't it better to leave panel tabs for terminals sessions instead of dropdown and move output/problems/terminal selection to dropdown? ISTM terminal switching is much more frequent task that switching between output/problems/terminal.

**Comment by bpasero** [comment]
The proposed design is landing for our next release:

![image](https://cloud.githubusercontent.com/assets/900690/22114157/b8b18dc4-de68-11e6-8e27-bea6106432cc.png)
