### ISSUE TITLE
`use git pull to update your local branch` quick fix

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#164639]
<img width="231" alt="Screen Shot 2022-10-25 at 2 31 32 PM (1)" src="https://user-images.githubusercontent.com/29464607/197858559-e7379846-6a9b-446e-8d3d-ff533a2bd416.png">

**Comment by meganrogge** [comment]
Should be contributed by git when the contrib point is finalized

**Comment by meganrogge** [comment]
part of #161538

**Comment by Tyriar** [comment]
👍 as long as we check the "can be fast-forwarded" part as well

**Comment by meganrogge** [comment]
WDYT about this one @Tyriar ?

**Comment by Tyriar** [comment]
@meganrogge still seems like a good request

**Comment by meganrogge** [comment]
Easy to verify in the `vscode-docs` repo

**Comment by andreamah** [comment]
I can't seem to find the action to run a pull. Am I looking at the correct place? 
<img width="496" alt="image" src="https://github.com/microsoft/vscode/assets/31675041/0d0d1cd9-5171-465d-a4cd-fe4e334b8004">

**Comment by aiday-mar** [comment]
verified on mac
