### ISSUE TITLE
Connecting from Windows to macOS results in new `c:` folder on macOS

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#164613]
Testing #164392

1. Start a tunnel on the macOS device
2. Get the Remote Tunnels extension on Windows and connect to the tunnel
3. Open a folder
4. There's a `c:` folder in the home directory that contains an appdata roaming directory. Did the extension create it?

**Comment by aeschli** [comment]
I can reproduce:
<img width="413" alt="image" src="https://user-images.githubusercontent.com/6461412/197963704-f754dc47-cbc0-4ee4-bf07-f8f06727f077.png">

**Comment by rzhao271** [comment]
Verified using Stable on macOS and Insiders on Windows.

I couldn't connect to the tunnel using Stable on Windows because it kept saying the command wasn't found. I'm not signed into any accounts on Windows, but I wasn't given a prompt to log in, either.
![Screenshot of dialog showing command not found](https://user-images.githubusercontent.com/7199958/204675948-24d7fa5c-5e29-4769-b960-57970e5d324c.png)
