### ISSUE TITLE
IntelliSense breaks when joining 'var' declarations with 'yield' keyword.

### ISSUE THREAD

**Issue by DenysYefimenko** [Microsoft/vscode#1647]
var variable1 = yield instance.generatorFunction(), variable2 = yield [[here IntelliSense stops recognizing presence of 'instance']]

**Comment by jrieken** [comment]
@DenysYefimenko What language is this? JavaScript or TypeScript?

**Comment by DenysYefimenko** [comment]
I had this problem in JavaScript.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
