### ISSUE TITLE
vscode unable to bind breakpoint when attaching to PID

### ISSUE THREAD

**Issue by slachy** [microsoft/vscode#164792]
Type: <b>Bug</b>

I'm setting a breakpoint in vscode editor, then I run debugger and attach to running PID. From log trace I can see that all paths are ok but the editor is unable to bind the breakpoint therefore debugger doesn't stop when hitting them.

My launch.json configuration:
        {
            "name": "(gdb) Attach",
            "type": "cppdbg",
            "request": "attach",
            "program": "<path_to_application>i",
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\mingw64\\bin\\gdb.exe",
            "logging": {"trace": true},
        }

trace log:
<--   R (runInTerminal-2) [2508 ms]: {"type":"response","seq":3,"command":"runInTerminal","request_seq":2,"success":true,"body":{"shellProcessId":7628}}
<--   C (setBreakpoints-4): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":4}
<--   C (setBreakpoints-5): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[1048],"breakpoints":[{"line":1048}],"sourceModified":false},"type":"request","seq":5}
<--   C (setBreakpoints-6): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":6}
<--   C (setBreakpoints-7): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":7}
<--   C (setBreakpoints-8): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":8}
<--   C (setBreakpoints-9): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":9}
<--   C (setBreakpoints-10): {"command":"setBreakpoints","arguments":{"source":{"name":"FILE_NAME.c","path":"<propper_path_to_file>"},"lines":[],"breakpoints":[],"sourceModified":false},"type":"request","seq":10}
<--   C (setFunctionBreakpoints-11): {"command":"setFunctionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":11}
<--   C (setDataBreakpoints-12): {"command":"setDataBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":12}
<--   C (setInstructionBreakpoints-13): {"command":"setInstructionBreakpoints","arguments":{"breakpoints":[]},"type":"request","seq":13}
<--   C (setExceptionBreakpoints-14): {"command":"setExceptionBreakpoints","arguments":{"filters":[],"filterOptions":[]},"type":"request","seq":14}
<--   C (configurationDone-15): {"command":"configurationDone","type":"request","seq":15}
=thread-group-added,id="i1"
GNU gdb (GDB) 11.2
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
[New Thread 15880.0x3edc]
[New Thread 15880.0x3f20]
[New Thread 15880.0xc60]
[New Thread 15880.0x3574]
[New Thread 15880.0x2350]
[New Thread 15880.0x413c]
[New Thread 15880.0x3cb8]
[New Thread 15880.0x38d8]
[New Thread 15880.0x18d0]
[New Thread 15880.0x3348]
[New Thread 15880.0x41e4]
[New Thread 15880.0x2b00]
[New Thread 15880.0x245c]
[New Thread 15880.0x2378]
[New Thread 15880.0x15c8]
[New Thread 15880.0x4b4]
[New Thread 15880.0x2244]
[New Thread 15880.0x4150]
[New Thread 15880.0x37ec]
[New Thread 15880.0xc1c]
[New Thread 15880.0x2d5c]
[New Thread 15880.0x1578]
[New Thread 15880.0x1d78]
[New Thread 15880.0x3d20]
[New Thread 15880.0x1f64]
[New Thread 15880.0x33c4]
[New Thread 15880.0x1434]
[New Thread 15880.0x400c]
[New Thread 15880.0x38dc]
[New Thread 15880.0x251c]
[New Thread 15880.0x37e4]
[New Thread 15880.0x2538]
[New Thread 15880.0x3938]
[New Thread 15880.0x4254]
[New Thread 15880.0x3378]
[New Thread 15880.0x3b24]
[New Thread 15880.0x11b8]
[Thread 15880.0x11b8 exited with code 0]
<--   C (threads-16): {"command":"threads","type":"request","seq":16}
<--   C (threads-17): {"command":"threads","type":"request","seq":17}

In editor I'm getting:
Attempting to bind the breakpoint...

I'm running on Windows 11.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (7.85GB free)|
|Process Argv|--crash-reporter-id e14b0928-e8e0-400c-95f8-88484475181d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
midas|far|0.5.4
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vim|vsc|1.24.1
debug|web|0.26.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by roblourens** [comment]
Please file an issue on the debug extension repo
