### ISSUE TITLE
Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?

### ISSUE THREAD

**Issue by maxtarquini** [microsoft/vscode#164713]
Type: <b>Bug</b>

After last update, vscode stopped working as expected.
At startup it is locked on Building java workspace. Output console shows the following  error:

Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.19.16-200.fc36.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 3942)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|31.06GB (24.76GB free)|
|Process Argv|--unity-launch --crash-reporter-id c7e47650-bdaf-4eae-93e5-fc6753dd4f2b|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.40.0
fabric8-analytics|red|0.3.6
java|red|1.11.0
rust-analyzer|rus|0.3.1258
prettier-vscode|Sim|2.0.7
sonarlint-vscode|Son|3.11.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-gradle|vsc|3.12.5
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-lombok|vsc|1.1.0
vscode-maven|vsc|0.39.0
vscode-spring-boot-dashboard|vsc|0.7.1
vscode-spring-initializr|vsc|0.11.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by gjsjohnmurray** [comment]
Are all your extensions up-to-date?

**Comment by meganrogge** [comment]
pls provide me w your tasks.json file

**Comment by maxtarquini** [comment]
@gjsjohnmurray manually removed .vscode and .config/Colder on my Fedora machine.
I also tryed to revert back to older version 1.70 and 1.71 but nothig happen

**Comment by maxtarquini** [comment]
@meganrogge  as an additional information, the 'JAVA PROJECT' tab is empty and a cursor moves from left to right.
If i try cmd+shift+p tasks: rerun last task i get same old error:
Error: there is no registered task type 'Java'. Did you miss installing an extension that provides a corresponding task provider?

![immagine](https://user-images.githubusercontent.com/44928818/198116735-a5acdc2a-4644-4b62-9c00-3928f6937e97.png)

**Comment by meganrogge** [comment]
> pls provide me w your tasks.json file

**Comment by maxtarquini** [comment]
@meganrogge there is no tasks.json file 
also used find /home/... -name tasks.json without success.
Removed code and folder and reinstalled. Java extension pack installed but nothing change. May be this is the the problem?

**Comment by meganrogge** [comment]
what happens when you run `Tasks: Configure`? 
<img width="645" alt="Screen Shot 2022-10-26 at 4 05 49 PM" src="https://user-images.githubusercontent.com/29464607/198126058-3a0d9cdb-34c0-4a2d-9814-29c1751fe41f.png">


I sense this is a java extension issue. does disabling that extension fix the issue?

**Comment by maxtarquini** [comment]
![immagine](https://user-images.githubusercontent.com/44928818/198127310-00a47988-9168-4aa0-a189-a5a6f6cdef0e.png)
 vscode prompt for a task to be configured but nothing happens even if i insert manually Java

**Comment by maxtarquini** [comment]
@meganrogge disabling java language support the problem is fixed. Nevertheless vscode is now unusefull :(

**Comment by meganrogge** [comment]
pls create an issue in the Java extension's repo
