### ISSUE TITLE
Implicit activation events

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#164701]
Today, when defining a command, a view etc you also need to define the corresponding activation event. This can lead to very long lists of activation events or can encourage the use of the `*` activation. We should help and define a list of implicit activation events that are derived from certain contributions like views, languages, commands etc

**Comment by gjsjohnmurray** [comment]
Even just #134373 would be a big help.

**Comment by jrieken** [comment]
Yeah, both are planned for Nov 22

**Comment by joyceerhl** [comment]
With thanks to @alexdima and @sandy081 the latest insiders build will infer the following activation events for extensions based on their contributions in package.json:
- `onCommand:` for all commands that an extension directly contributes
- `onNotebookSerializer:` for all notebook serializers that an extension directly contributes

This means that extension authors no longer need to spell out `onCommand:` activation events for the commands that their extensions registers, and allows us to remove debt for notebooks activation (cc @rebornix).

I'll file an issue tracking adoption across the various extension points and close this when we have adopted this in full.

**Comment by joyceerhl** [comment]
Closing this item as we have now adopted implicit activation events generation for `onView`, `onCommand`, `onCustomEditor` and `onLanguage`. Thanks everyone for the effort and adoption!
