### ISSUE TITLE
Cannot open notebook in vscode.dev, error reading property message

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#164715]
Started up insiders.vscode.dev for the first time in awhile and received the following error

<img width="576" alt="image" src="https://user-images.githubusercontent.com/4544166/198040155-96cfb9a4-b5cc-4ada-9f4b-af7c4dfe67a4.png">

Seems to come from here. 
https://github.com/microsoft/vscode/blob/0944a16e3e256ac692babe7e7e9650fc9cc80d44/src/vs/workbench/contrib/notebook/browser/notebookEditor.ts#L293-L294

This only repros when I use the [endgame vscode.dev query](https://insiders.vscode.dev/github/microsoft/vscode/blob/9f5d3eb1353f6e6bd5ab7bccab9d50b0aba15209/.vscode/notebooks/endgame.github-issues#C21:L1) provided. Opening the file myself seems to work

**Comment by rebornix** [comment]
@lramos15 do you see this every time when opening the link? It seems that it throws with an undefined error but we failed to read the error message. It didn't explain why the file opening fails though.

**Comment by lramos15** [comment]
> @lramos15 do you see this every time when opening the link? It seems that it throws with an undefined error but we failed to read the error message. It didn't explain why the file opening fails though.

I see it every time. I can try again tomorrow when this change goes in to see if there is a more detailed error message.

**Comment by joyceerhl** [comment]
I just hit this as well twice @rebornix but third time didn't repro

**Comment by joyceerhl** [comment]
This will fail
https://insiders.vscode.dev/github/microsoft/vscode/blob/9f5d3eb1353f6e6bd5ab7bccab9d50b0aba15209/.vscode/notebooks/endgame.github-issues#C22:L1

This is OK 
https://insiders.vscode.dev/github/microsoft/vscode/blob/9f5d3eb1353f6e6bd5ab7bccab9d50b0aba15209/.vscode/notebooks/endgame.github-issues#C23:L1

We think it's because C22 is a markdown cell and C23 is a code cell

**Comment by rebornix** [comment]
I prepared a fix for this one, by turning the cell into editing mode if there is a selection in the link https://github.com/microsoft/vscode/pull/164758. If we drop `L1` from the link, you can find it open successfully. 

However currently whenever we copy a link from a markdown cell preview, we always append `L1` ion the link, we should probably only append line number when the cell is in editing mode https://github.com/microsoft/vscode-dev/issues/749
