### ISSUE TITLE
Why can't I install a pre-release of GHPRI in a Codespace?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164771]
I'm guessing this is because it's now built-in, but shouldn't Codespaces users be able to choose?

<img width="820" alt="image" src="https://user-images.githubusercontent.com/30305945/198158764-d79270c2-525c-452d-bf98-1990eb05af94.png">

**Comment by sandy081** [comment]
Built in extensions are fixed and we do not support out of the band updates. Its same in the Desktop. One can always side load the extension if wanted which is supported.
