### ISSUE TITLE
Extension output: repl no longer indicates type of object

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16479]
- VSCode Version: latest insiders
- OS Version: macOS

This looks like a bad regression from stable.

Steps to Reproduce:

1. have your extension output `{ foo: "bar" }`
2. show the output in the repl

Insiders:
![image](https://cloud.githubusercontent.com/assets/900690/20875830/0a9bc15a-babe-11e6-8036-3c5faa452bce.png)

Stable:
![image](https://cloud.githubusercontent.com/assets/900690/20875823/05794350-babe-11e6-987f-a041ee89087c.png)

**Comment by isidorn** [comment]
@bpasero nice catch

**Comment by bpasero** [comment]
Still seeing this:

![image](https://cloud.githubusercontent.com/assets/900690/21006815/e166f01e-bd3a-11e6-855b-085cf2c3083a.png)
