### ISSUE TITLE
Terminal quick fix hover does not reflect changed keybinding

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164757]
1. Run `git create PR`
2. ✅ code action appears 
3. Open keyboard shortcuts editor and change the `workbench.action.terminal.quickFix` keybinding
4. Hover over existing code action 
5. :bug: code action tooltip still says `Ctrl+.` to trigger quick fix

**Comment by joyceerhl** [comment]
There is no hover feedback for the code action now, and additionally running the default keybinding for the `workbench.action.terminal.quickFix` command results in an error about the command not being found. 

![Image](https://user-images.githubusercontent.com/30305945/204879344-1abf7b41-9166-4217-921f-9af440316fa8.png)

**Comment by meganrogge** [comment]
sorry @joyceerhl the command is now: `workbench.action.terminal.showQuickFixes`

**Comment by meganrogge** [comment]
we went with this name to align with all commands IE use a verb - `show`

**Comment by joyceerhl** [comment]
I no longer see the hover with the keybinding though?

**Comment by meganrogge** [comment]
that is by design as we're using the action widget

**Comment by joyceerhl** [comment]
Are the verification steps for this issue just that the keybinding is not reflected anywhere in the UI?

**Comment by meganrogge** [comment]
Yes and that you can change the keybinding/ it works
