### ISSUE TITLE
Preview mode breaks clicking on link to a section in file, preview turn dark.

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#16471]
When I create a local link to the markdown file, clicking on the link break preview and turn everything dark.

![preview-broken](https://cloud.githubusercontent.com/assets/439226/20870827/7c438d68-ba5c-11e6-9554-2067538d7bf8.png)

Here is the same working example on Github:
https://github.com/rajinder-yadav/redux-counter#table-of-content

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-51-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|vscode-angular2-emmet|jakethashi|1.0.9|
|cpptools|ms-vscode|0.9.2|
|debugger-for-chrome|msjsdiag|2.3.2|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.6|

---

Steps to Reproduce:

1. Create a markdown file with local link to the file.
2. Click on link from preview.

**Comment by chrmarti** [comment]
Appears to be fixed in the latest insiders build. You could use that or wait for the upcoming 1.8 release.
