### ISSUE TITLE
`window.commandCenter` setting description references setting `window.titleBarStyle` in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164768]
Clicking the setting link just clears the settings UI editor query

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/30305945/198156543-7e4101cd-ef51-4ecd-8ba3-0d7d55da4866.png">

**Comment by jrieken** [comment]
Yeah, the problem is that the setting doesn't exist for web. The same applies to the `window.menuBarVisibility` setting
