### ISSUE TITLE
Windows Control Overlay maximize button is too rounded on Windows 11

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#164731]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Open VS Code
2. Enable the setting `window.experimental.windowControlsOverlay.enabled`
3. Make sure the window isn't maximized
4. :bug: The maximize button is too rounded

In the following screenshot, the VS Code maximize button is the middle one.
![Screenshot comparing maximize buttons in different programs](https://user-images.githubusercontent.com/7199958/198100037-7b872c8e-4669-4ee0-aee8-6bd08106b465.png)

Ref https://github.com/electron/electron/pull/35370.

**Comment by deepak1556** [comment]
We will start exploring Electron 22 in November milestone, I will backport the upstream fix into the product builds for Electron 19 in the interim.

**Comment by rzhao271** [comment]
Verification steps:
1. On Windows 11 and using VS Code Insiders, enable the window controls overlay setting. Reload the program if prompted.
2. Restore/unmaximize the window so that the maximize button shows up.
3. Confirm that the maximize button is now more square-shaped than in the screenshot above.

**Comment by bhavyaus** [comment]
Screenshot of new maximize button:
<img width="79" alt="image" src="https://user-images.githubusercontent.com/25044782/205138448-4888dce8-cb37-4206-bb4a-90f24f75a5a8.png">
