### ISSUE TITLE
Flag extension version incompatibility on extension page

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164733]
Testing #164452

1. Install nikhgup1.appmap123, it fails due to version incompatibility
2. Could we instead show the extension version requirement on the extension page? The Install button could also instead say Install Another Version if the latest version is incompatible with the current VS Code version

**Comment by sandy081** [comment]
It can be shown, but this is expensive to know if an extension has a compatible version or not as we have to get all versions. It is very rare that an extension does not have a compatible version for latest VS Code and we do not officially support old versions of VS Code, adding this feature might not be worth.
