### ISSUE TITLE
Cell output scrolled out of view after reexecution

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164770]
1. Run https://insiders.vscode.dev/github.com/microsoft/vscode/blob/9f5d3eb1353f6e6bd5ab7bccab9d50b0aba15209/.vscode/notebooks/endgame.github-issues#C23:L1
2. Click 'show __' more in the output area (output is large here)
3. Ctrl+enter to rerun the cell
4. :bug: after rerunning, I see the next few cells and output instead of the output for the cell I was previously running. This is a papercut for me and has happened a couple of times today during issue verification

**Comment by rebornix** [comment]
We might need some heuristics of keep the scroll top based on the context (re-execution)

**Comment by roblourens** [comment]
I don't see the issue. Trying to set up a similar situation with a new query, but when I rerun the cell, I see what I expect.

**Comment by roblourens** [comment]
I know there are issues with scroll position, I think there are still open issues for other cases, but this case seems ok to me
