### ISSUE TITLE
`process is not defined` when using `Insert Image from Workspace`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#164782]
1. Opened https://insiders.vscode.dev/github.com/microsoft/vscode/blob/9ad069358e9f09d1f49a90db36b73c953505438a/test/README.md
2. Tried to insert a link to extensions/git/resources/git.png
3. :bug: ![image](https://user-images.githubusercontent.com/30305945/198196772-f0756862-728f-43b4-b6e0-5f577e122c44.png)

**Comment by mjbvz** [comment]
Works fine for me (although it should not actually be enabled because the editor is readonly here)

![Screen Shot 2022-10-27 at 9 30 06 AM](https://user-images.githubusercontent.com/12821956/198347174-8cc8a2e0-8d2d-4d44-94d3-28b5055d6b84.png)


@joyceerhl Can you please share the stack trace of the error

**Comment by joyceerhl** [comment]
Weirdly, there is no call stack printed to the logs that I can find 👻but I debugged this and it looks like we end up in here

https://github.com/microsoft/vscode/blob/1316bf789f9db6daa267520c0d7f65965b5bd878/extensions/markdown-language-features/src/languageFeatures/dropIntoEditor.ts#L84

and `path.replace` calls into `resolve` which ends up evaluating `process.cwd`

<img width="1309" alt="image" src="https://user-images.githubusercontent.com/30305945/198352901-581f48f8-6f03-4442-8023-723b2504f721.png">


Full callstack

```
resolve (extension.js:4)
relative (extension.js:4)
(anonymous) (extension.js:4)
l (extension.js:4)
(anonymous) (extension.js:4)
(anonymous) (extension.js:4)
d (extension.js:4)
execute (extension.js:4)
await in execute (async)
_executeContributedCommand (extensionHostWorker.js:74)
$executeContributedCommand (extensionHostWorker.js:74)
_doInvokeHandler (extensionHostWorker.js:76)
_invokeHandler (extensionHostWorker.js:76)
_receiveRequest (extensionHostWorker.js:76)
_receiveOneMessage (extensionHostWorker.js:76)
eval (extensionHostWorker.js:76)
invoke (workerMain.js:16)
deliver (workerMain.js:16)
fire (workerMain.js:16)
c.port1.onmessage (extensionHostWorker.js:83)
postMessage (async)
send (workbench.web.main.js:2027)
_remoteCall (workbench.web.main.js:1777)
N.<computed>.M.charCodeAt.N.<computed> (workbench.web.main.js:1777)
(anonymous) (workbench.web.main.js:1763)
invokeFunction (workbench.web.main.js:601)
_tryExecuteCommand (workbench.web.main.js:1757)
executeCommand (workbench.web.main.js:1757)
accept (workbench.web.main.js:814)
(anonymous) (workbench.web.main.js:607)
invoke (workbench.web.main.js:80)
deliver (workbench.web.main.js:80)
fire (workbench.web.main.js:80)
handleAccept (workbench.web.main.js:591)
(anonymous) (workbench.web.main.js:591)
invoke (workbench.web.main.js:80)
deliver (workbench.web.main.js:80)
fire (workbench.web.main.js:80)
(anonymous) (workbench.web.main.js:591)
```

**Comment by joyceerhl** [comment]
As an aside, I don't know if referencing `fsPath` is quite right here, since it's only defined for paths on real filesystems versus in memory filesystems. Maybe `path` instead?

**Comment by mjbvz** [comment]
@joyceerhl Thanks! And good idea. I've switched to `path.posix` which should both avoid checking process and also let us remove the `.replace` hack for windows paths

**Comment by aeschli** [comment]
Verified by testing the steps and verified the code
