### ISSUE TITLE
What is the bare minimum for Javascript syntax checking?

### ISSUE THREAD

**Issue by MrSkinny** [Microsoft/vscode#16474]
- VSCode Version: Latest as of 12/4/16
- OS Version: 10.11.6 El Capitan

Is there any other setting necessary to have basic Javascript syntax checking/linting active in VSC? 

```
{
  "javascript.format.enable": true
}
```

ESLint works well when I `eslint --init` in a project but when I'm just fooling around with a few files and not building a project, it'd be great to just get basic syntax checking / undefined variable calls etc.  I was certain this was built into VSC.  And if it isn't, what exactly is  "javascript.format.enable" doing, because it doesn't seem to have any effect?

I also created a `jsconfig.json` in the folder root, but still no intellisense/lint happening:

```
{
    "compilerOptions": {
        "target": "ES6"
    },
    "exclude": [
        "node_modules"
    ],
    "files": [
        "src/"
    ]
}
```

Thanks!

**Comment by chrmarti** [comment]
`"javascript.format.enable"` is for the code formatter. Linting indeed only comes through extensions and is not built-in. You should get basic Intellisense without a jsconfig.json, could you provide an example showing the problem?

**Comment by MrSkinny** [comment]
@chrmarti I'm literally getting no feedback at all.  For example:

```
if {} 
sfds;
for let i;
```

No markings, underlines, etc.

**Comment by chrmarti** [comment]
@MrSkinny Which version of Code are you using? ('Latest' might refer to latest stable or latest insider version.)

What does the Output panel (View > Output) show in it's TypeScript channel (switch to TypeScript in the panels top right drop-down)?

**Comment by MrSkinny** [comment]
@chrmarti 
Using v1.7.2
Output in Typescript channel says:
```
[Info  - 9:19:07 AM] Using tsserver from location: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/typescript/node_modules/typescript/lib/tsserver.js
```

**Comment by mjbvz** [comment]
@MrSkinny Thank you for all the additional information here.

I believe you are running into a common problem: [`"files"` must be a list of file names, not glob patterns](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

Try changing your `jsconfig.json` to use `"include"` instead:

```json
{
  "include": [
    "src/**"
  ]
}
```

Please let me know if this does not work.

Thanks

**Comment by MrSkinny** [comment]
@mjbvz Added this to `jsconfig.json`:

```
{
  "include": [
    "src/**/*.js"
  ]
}
```

Created `src/index.js` and put a bunch of junk syntax/undeclared variables, and still getting no visual feedback.  View -> Output showing same as before.
