### ISSUE TITLE
Markdown links failing to render properly in edit mode

### ISSUE THREAD

**Issue by rajinder-yadav** [Microsoft/vscode#16470]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.4.0-51-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-markdownlint|DavidAnson|0.6.0|
|EditorConfig|EditorConfig|0.3.4|
|jslint|ajhyndman|1.2.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|vscode-angular2-emmet|jakethashi|1.0.9|
|cpptools|ms-vscode|0.9.2|
|debugger-for-chrome|msjsdiag|2.3.2|
|Spell|seanmcbreen|0.9.1|
|vim|vscodevim|0.4.6|

---

Steps to Reproduce:

I've circled broken areas.

![code-links](https://cloud.githubusercontent.com/assets/439226/20870687/499029d2-ba5a-11e6-9b8c-c4e3dfa699a7.png)

**Comment by rajinder-yadav** [comment]
Have tried with `code --disable-extensions`, same.

**Comment by chrmarti** [comment]
Could you append the document that shows the problem?

**Comment by mjbvz** [comment]
Closing as more info needed.

@rajinder-yadav, please provide a markdown document that shows this behavior so that we can investigate.

Thanks
