### ISSUE TITLE
[feature] Provide a button to toggle all hotkeys

### ISSUE THREAD

**Issue by Freed-Wu** [microsoft/vscode#164777]
Can vscode provide a button to toggle all hotkeys? Because when I use terminal
in vscode, some hotkeys will be overridden by vscode, such as `<C-P>`. In terminal
`<C-P>` is `up-line-or-history`. In vscode, it is open a panel. I think a button 
to toggle all hotkeys will be more convenient and let the button be off by 
default will not affect current user who don't use terminal.

**Comment by gjsjohnmurray** [comment]
Please see the `terminal.integrated.commandsToSkipShell` for a way to solve your problem.

**Comment by Freed-Wu** [comment]
Looks like this:

```json
{
  "terminal": {
    "integrated": {
      "sendKeybindingsToShell": true
    }
  }
}
```
