### ISSUE TITLE
Add method override and inheritance indicators

### ISSUE THREAD

**Issue by AbsPlayer** [microsoft/vscode#164787]
Currently VSCode does not show override/inherit indicators that the current class is overriding/inheriting methods from/to super/other class.

This indicator would help the user understand that the given method is being overridden/inherit rather than a local method.

Most editors such as intellij & eclipse have these indicators
See example on screenshot
https://drive.google.com/file/d/1-sIfYLuU_D6DZdx5ona3tgwAtUgRu_Si/view

**Comment by gjsjohnmurray** [comment]
Did you find #157461 when searching for existing issues?

**Comment by AbsPlayer** [comment]
No, I didn't find issue https://github.com/microsoft/vscode/issues/157461
Please connect my issue to issue 157461
