### ISSUE TITLE
cursorMove command needs to know which end of selection is moving.

### ISSUE THREAD

**Issue by johnfn** [Microsoft/vscode#16472]
- VSCode Version: 1.8.0 insiders
- OS Version: macOS Sierra

For VSCodeVim, we need to be able to tell the cursorMove command if the start or the end of the active selection is moving. 

Quasi-Related: #16248

**Comment by alexandrudima** [comment]
fyi @sandy081

**Comment by sandy081** [comment]
@rebornix Since you are working on the editor area let me know if you want to own this or shall I take it up.

**Comment by rebornix** [comment]
@sandy081 I can take a look and ask stupid questions if I get trouble, thanks!

**Comment by rebornix** [comment]
@johnfn the issue you mentioned https://github.com/VSCodeVim/Vim/issues/890 is actually triggered by VSCodeVim's code https://github.com/VSCodeVim/Vim/commit/b193c22324f71b85c36210e24586e8f7f3ddabe1 . We introduced that code when we tried to fix issues in Visual Line mode.
