### ISSUE TITLE
Can't open some CPU profiles with the builtin flame chart editor

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#164720]
Testing #164476

<img width="540" alt="image" src="https://user-images.githubusercontent.com/323878/198077727-ee6006c6-b0c2-446b-ac34-7d213e35340e.png">

```
2022-10-26 09:06:11.198 [error] TypeError: Cannot read properties of undefined (reading 'selfTime')
    at e.buildModel (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.vscode-js-profile-table/out/extension.js:1:37873)
    at e.CpuProfileEditorProvider.openCustomDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/ms-vscode.vscode-js-profile-table/out/extension.js:1:34838)
    at f.$createCustomDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:194986)
```

[renderer-profile-1666722014345.cpuprofile.zip](https://github.com/microsoft/vscode/files/9871262/renderer-profile-1666722014345.cpuprofile.zip)

**Comment by roblourens** [comment]
I say "some" profiles because I see some that were apparently stored yesterday that I can open. But today now that I'm looking in the right place for the logs, I've only managed to produce several .cpuProfiles that all show this error when opened.

**Comment by jrieken** [comment]
@roblourens where exactly does the file come from? The `renderer-profile`-prefix doesn't look like an autogenerated one

**Comment by roblourens** [comment]
Am I not looking at the right thing? I see

`2022-10-26 09:54:52.147 [info] [perf] stored profile to DISK '/tmp/renderer-profile-1666803292101.cpuprofile' fc0d1267-d194-4c27-9b80-cdba8250f123` in the main log, and when I open that I get the same error.

**Comment by jrieken** [comment]
@roblourens Are you sure that you are on latest? That message used to be printed in the main-log but got removed a couple of days ago (https://github.com/microsoft/vscode/commit/fec87f38cbd82f6603a44cf1686c54c3f08ffd73). Now the message is printed in the renderer log (it confusingly starts with exthost which will be fixed tomorrow)

**Comment by jrieken** [comment]
it might be that the analysis (to find the heavy samples) mutates the actual profile but with latest insiders that shouldn't matter anymore

**Comment by roblourens** [comment]
Hm. I'm using the snap on linux, I thought I'd checked that it had actually updated, but must have been out of date, sorry. Today I have the latest, and I tried the scenario again. Got a few profiles like `/tmp/renderer-397b7e.cpuprofile`, and can open all of them in vscode
