### ISSUE TITLE
Deleting FIFO files from the file explorer over SSH causes infinite loading

### ISSUE THREAD

**Issue by mason-dunn** [microsoft/vscode#164773]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version:  Win 11 22H2

Steps to Reproduce:

1.  Login to a remote linux computer
2.  Create fifo file using mkfifo
3.  Delete fifo file using file explorer
![infinite](https://user-images.githubusercontent.com/106716960/198163247-79ffbc6a-95ab-4c39-8e6e-3e549465ca74.gif)

**Comment by lramos15** [comment]
Duplicate https://github.com/microsoft/vscode/issues/148034
