### ISSUE TITLE
Empty square outline on notebook open

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#164755]
Using the default light theme, whenever I open a new jupyter or github issues notebook, I see a faint outline of a square

Jupyter:
<img width="994" alt="image" src="https://user-images.githubusercontent.com/31675041/198144795-c685a4af-8277-409b-b15d-c69773b7242b.png">

Github Issues:
<img width="993" alt="image" src="https://user-images.githubusercontent.com/31675041/198144844-1789e858-6bcf-4bd9-9329-b0e59c673f71.png">

There's this 1px square outline that appears in some themes and not others? 
<img alt="image" src="https://user-images.githubusercontent.com/31675041/198144881-a7a570d2-98b2-4892-b4cb-be7f657002c1.png">

**Comment by rebornix** [comment]
It's the gutter area of the editor, I'm not aware we have an outline for this.

**Comment by alexdima** [comment]
@andreamah I don't see these white lines. Are you perhaps using `window.zoomLevel` ?

<img width="545" alt="image" src="https://user-images.githubusercontent.com/5047891/198300094-516fa369-02b5-4bcf-b55d-cdf9d5cec408.png">

**Comment by andreamah** [comment]
Hmm, I don't seem to see it anymore (although when I got this yesterday, it would repro consistently). I'll close this for now and re-open if I see it again.
