### ISSUE TITLE
Deselect one of multi-cursors

### ISSUE THREAD

**Issue by narimiran** [Microsoft/vscode#16486]
- VSCode Version: 1.7.2
- OS Version: Win7

Steps to Reproduce:

1. Select all occurrences of current selection (Ctrl+Shift+L) or similar method (multiple Alt+click) - have two or more multi-cursors
2. Try to deselect one of multi-cursors

Is there a way of doing this?  

In Sublime and Atom, IIRC, it is the same shortcut for adding the cursors and to remove a cursor if you click on one of them.  
Following the same logic, vscode should remove the cursor with Alt+click, but I also tried various other combinations and nothing has worked.

**Comment by alexandrudima** [comment]
:+1: in the meantime, there is `ctrl+u` that undoes the last cursor selection if you wen too far with `ctrl+d`, there's also `alt+w` and `alt+c` to change it to work on whole words / case sensitive matches.

**Comment by narimiran** [comment]
Any news on this one?

**Comment by bpatram** [comment]
@narimiran Looks like a similar feature, https://github.com/Microsoft/vscode/issues/2106 was added into the May milestone.

**Comment by alexandrudima** [comment]
Indeed, this is a dup of #2106.
