### ISSUE TITLE
whether the focus is at the editor or at the terminal.

### ISSUE THREAD

**Issue by log2dx** [microsoft/vscode#164848]
In such a case, I could not determine whether the focus is at the editor or at the terminal. Because both cursor is under the visable part.

![image](https://user-images.githubusercontent.com/75123516/198412197-fd9819cf-d7b1-49c3-9494-83bfead4d8d6.png)

Where the focus is matters. For example,
**Example 1.** When I want to type a command in terminal, whether I should focus on the terminal (press **Ctrl+`**) first ?
**Example 2.** When I want to press **Ctrl+T** or **Ctrl+G**, whether I should focus on the editer (e.g. press **Ctrl+1**) first?

**Comment by Tyriar** [comment]
Scrolling out of the viewport where the cursor is in both the editor and the terminal is a bit of a contrived example. I know there are a couple of issues tracking better focus feedback in the editor/terminal/views so let's track the general problem there.
