### ISSUE TITLE
Git - polish Commit Action button

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#164873]
- [ ] Commit Action button should show progress 
- [ ] Commit Action button should indicate the performed action

**Comment by lszomoru** [comment]
Verification steps:
* Open a folder/workspace that contains a git repository
* Make changes to one or more file, and add a commit message
  * Confirm that the "Commit" action button is shown and enabled
* Expand the "Commit" action button and click a command with a post-commit action (ex: Commit & Push)
  * Confirm that the label of the button is updated to "Commit & Push"
  * Confirm that the "Commit" action button is disabled while the operation is running
  * Confirm that the "spinning icon" is being shown while the operation is running

**Comment by isidorn** [comment]
Nice work 👏
