### ISSUE TITLE
Cleanup resource performance markers

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#164810]
The resource performance markers are now PII cleansed - e.g all paths are removed which defeats the purpose of collecting them... We should do something smarter and send only selected information that isn't cleansed

**Comment by jrieken** [comment]
cc @lramos15

**Comment by jrieken** [comment]
Adding to October a least collecting the basenames-only

**Comment by jrieken** [comment]
cc @joyceerhl that we have this and that it is being fixed for this milestone

**Comment by rebornix** [comment]
if I read it correct it's now fixed via https://github.com/microsoft/vscode/pull/164812
