### ISSUE TITLE
Error updating Insiders

### ISSUE THREAD

**Issue by jtsom** [microsoft/vscode#164803]
Type: <b>Bug</b>

Trying to check for an update on Insiders is just generating an error "Hash Mismatch"

![image](https://user-images.githubusercontent.com/13488/198286841-7bd74a11-5eb4-4bbc-b0b4-bf95de045405.png)

VS Code version: Code - Insiders 1.73.0-insider (c3eebaead9d3bf1cb961b91fca1b8af31990d328, 2022-10-26T09:31:30.519Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.72GB free)|
|Process Argv|--crash-reporter-id 362817d9-b661-4b35-92b7-fe18e5872851|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
TabOut|alb|0.2.2
ng-template|Ang|14.2.0
sync-scroll|dqi|1.3.0
vs-code-xml-format|fab|0.1.5
csharpextensions|kre|1.7.3
git-graph|mhu|1.30.0
ecdc|mit|1.8.0
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.8.3
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestorage|ms-|0.15.0
vscode-cosmosdb|ms-|0.19.2
csharp|ms-|1.25.0
azure-account|ms-|0.11.2
hexeditor|ms-|1.9.9
js-debug-nightly|ms-|2022.10.1817
material-icon-theme|PKi|4.21.0
quicktype|qui|12.0.46
vscode-thunder-client|ran|1.20.1
hl7tools|Rob|1.14.2
msbuild-project-tools|tin|0.4.9
vscodeintellicode|Vis|1.2.29
jwt-debugger|yok|0.4.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
pyind367cf:30587848
vsccc:30564266
pyindex848cf:30577859
nodejswelcome1:30587009
j6j51389:30596843

```

</details>

**Comment by gjsjohnmurray** [comment]
/confirm Also happening for me (in UK)
