### ISSUE TITLE
Whether my focus is at the editor or at the terminal.

### ISSUE THREAD

**Issue by log2dx** [microsoft/vscode#164833]
In such a simple case, I could not determine whether my focus is at the editor or at the terminal.

![image](https://user-images.githubusercontent.com/75123516/198412197-fd9819cf-d7b1-49c3-9494-83bfead4d8d6.png)

Where the focus is matters. For example,
**Example 1.** When I want to type a command in terminal, whether I should focus on the terminal (press **Ctrl+`**) first ?
**Example 2.** When I want to press **Ctrl+T** or **Ctrl+G**, whether I should focus on the editer (e.g. press **Ctrl+1**) first?

**Comment by meganrogge** [comment]
Setting the terminal cursor to blink shld help w this.

**Comment by log2dx** [comment]
Terminal cursor under the visable part.🙁

**Comment by log2dx** [comment]
> Setting the terminal cursor to blink shld help w this.

Both cursor under the visable part.🙁
