### ISSUE TITLE
Add an image code and generate an image source when pasting an image in markdown

### ISSUE THREAD

**Issue by unanmed** [microsoft/vscode#164843]
When using some screenshots tools, we often add the result to the clipboard. So it's really convenient if VS Code allow us to paste an image. When pasting, VS Code can generate an image source somewhere in the project folder like assets folder in the root path of the project or the same folder as the markdown file. Or allow us to set where the image is generated.

For example, I took a screenshot of something, and paste it in a markdown file. VS Code may execute these command:

1. Read the image data, and generate a image source in the folder I set or assets folder.
2. Generate an image code `![image](path)` in the markdown file where I paste the image.

**Comment by mjbvz** [comment]
This is already being tested with the `markdown.experimental.editor.pasteLinks.enabled` setting. To enable it, make sure to set:

```
"markdown.experimental.editor.pasteLinks.enabled": true,
"editor.experimental.pasteActions.enabled": true
```

**Comment by joaociocca** [comment]
is there a way to configure where the image will be uploaded? like setting it to `/image` instead of the current folder?
