### ISSUE TITLE
Keyboard layout not used with shortcuts

### ISSUE THREAD

**Issue by WannesMalfait** [microsoft/vscode#164893]
Type: <b>Bug</b>

I have an "Azerty" keyboard layout.
When I type code it works normally (i.e. what I type is what appears on screen). However, for keyboard shortcuts it seems that a default "QWERTY" layout is used.
Example:
Pressing `CTRL + W` doesn't close the tab, but does an undo instead (`CTRL + Z`), while doing `CTRL + Z` does close the tab, instead of doing undo.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 6.0.2-76060002-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|7.65GB (3.36GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop-wayland|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop-wayland|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.0.3
latex-workshop|Jam|8.29.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.40
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
rust-analyzer|rus|0.3.1258
crates|ser|0.5.10
cmake|twx|0.0.17
vscode-ltex|val|13.1.0

(1 theme extensions excluded)

</details>

**Comment by WannesMalfait** [comment]
Restarting vs code fixed this. So not sure if reproducible

**Comment by WannesMalfait** [comment]
I have not had this happen again, so it was probably just some one-time thing. I didn't find anyway to reproduce this, so it's fine for me if this is closed.

**Comment by alexdima** [comment]
This might have been caused by you switching keyboard layouts while vscode is running. But we've written code to [detect keyboard layout changes](https://github.com/microsoft/node-native-keymap/blob/089d802efd387df4dce1f0e31898c66e28b3f67f/src/keyboard_x.cc#L369-L385). If you notice this again or find reproducible steps, please let us know.
