### ISSUE TITLE
Empty line between settings sections

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16489]
![image](https://cloud.githubusercontent.com/assets/22350/20879857/e28941d4-bad5-11e6-85ba-cb84aa250e67.png)

We could remove that extra line between sections.

**Comment by sandy081** [comment]
This is tricky, empty line was added as an hack for collapsible regions to work properly.

I will see if I can workaround it in proper way.

**Comment by sandy081** [comment]
Closing this as there are no plans in fixing this. Empty lines are needed for collapsible regions to work. Please reopen if it needs to be fixed.
