### ISSUE TITLE
How to configure IntelliSense in Visual Studio Code?

### ISSUE THREAD

**Issue by sarbbottam** [Microsoft/vscode#1648]
How to configure IntelliSense in Visual Studio Code?

For example, lets consider the below code snippet.

```js
'use strict';

import React from 'react';
import ReactDOMServer from 'react-dom/server';
```
I would like the IntelliSense to suggests the available methods on `React`, when I press `cmd + space` after typing `React.`.

Is that possible? If yes any pointer would be of great help.

**PS:**

I have already installed the `dependent modules` and updated the `package.json` and they are available at `./node_modules/`

---
*Raised it at [StackOverflow](http://stackoverflow.com/questions/33924317/how-to-configure-intellisense-in-visual-studio-code) a month ago.*

**Comment by meritozh** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/react

```
tsd install react
```

Restart, then, you can get intellisense

**Comment by sarbbottam** [comment]
Thanks @meritozh, is there no way to achieve it w/o `tsd`?

**Comment by meritozh** [comment]
@sarbbottam You must need `*.d.ts` files, so you get the definitions directly from the [Github repos](https://github.com/DefinitelyTyped/DefinitelyTyped). `tsd` is just a tool. If you want implement intellisense without something like a (typescript) definition file, you can see these  issues: #957 and Microsoft/TypeScript#4789

**Comment by sarbbottam** [comment]
Almost duplicate of #957
