### ISSUE TITLE
ALT-menu get hidden when clicking message button

### ISSUE THREAD

**Issue by jwallander** [Microsoft/vscode#16487]
- VSCode Version: 1.7.2
- OS Version: Win 7 Enterprise 64-bit

Steps to Reproduce:

1. Open menu with ALT-key
2. Select Help => Check for updates...
3. Try to click the "There are no updates currently available." Close button
4. The menu closes and you have to click the close button again

My expectation is for the message to disappear and the menu to stay visible the first time the close button is clicked.

**Comment by joaomoreno** [comment]
Can you show me a screencast of what you mean?

**Comment by jwallander** [comment]
![vscaltclose](https://cloud.githubusercontent.com/assets/1730503/20926324/029acd30-bbbc-11e6-94db-0007187ae751.gif)

Notice that I click the blue close button twice. The first time only the menu disappears and the message and button moves upp and then I have to click the button again to close the message.

**Comment by joaomoreno** [comment]
Got it. Seems to be an electron issue.

@bpasero Do we already have this issue tracked as something else?

**Comment by bpasero** [comment]
No I think this is new, but valid. however not sure how to best tackle, if you click away from the menu it will hide and move up.

**Comment by bpasero** [comment]
Not an issue anymore since notifications are now at the bottom.
