### ISSUE TITLE
word pattern when selecting and for the completion

### ISSUE THREAD

**Issue by gkotulski** [microsoft/vscode#164859]
In the language 4D the word pattern cannot be delimited with a regex.
For example:
![image](https://user-images.githubusercontent.com/35215837/198278645-2130d7b9-b970-41f1-b584-fefb16c008c4.png)

Each line is a token. When I double click on `VP ADD FORMULA NAME` all the command should be selected not one word.
`$ma variable` for example is a single token.

It impacts a lot for the completion and when we want to select a token.
A regex for wordPattern is not enough.
```json
{
    "wordPattern": "(-?\\d*\\.\\d\\w*)|([^\\`\\~\\!\\@\\#\\%\\^\\&\\*\\(\\)\\-\\=\\+\\[\\{\\]\\}\\\\\\|\\;\\:\\'\\\"\\,\\.\\<\\>\\/\\?\\r\\n\\t\\f\\v ]+)|(?<=[a-zA-Z]) ?(?=[a-zA-Z])"
}
```
The regex does not even work with look ahead and look behind.

**Comment by jrieken** [comment]
> Each line is a token.

I understand your requirement but the word pattern isn't mean to replace or implement a lexer or anything similar. It helps to get to reasonable default, e.g for completions, or to help some UI features. However, if completions or highlights are to be implemented a real lexer/parser combination should be used, the word definition isn't powerful enough and likely too slow
