### ISSUE TITLE
API: FileSystemWatcher not firing when complete filename used without wildcards

### ISSUE THREAD

**Issue by vanowm** [microsoft/vscode#164925]
Does this issue occur when all extensions are disabled?: Yes

Attempting setup a [FileSystemWatcher](https://code.visualstudio.com/api/references/vscode-api#workspace.createFileSystemWatcher) for a specific single file fails to trigger on `create`/`change`/`delete` events when complete filename provided:
```javascript
const watcher = vscode.workspace.createFileSystemWatcher(new vscode.RelativePattern("C:\\", "test.json"));
watcher.onDidChange(uri => console.log("change", uri));
watcher.onDidCreate(uri => console.log("create", uri));
watcher.onDidDelete(uri => console.log("delete", uri));
```
if `test.json` replaced with `*.json` the events triggered properly.

```text
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No
```

**Comment by ArturoDent** [comment]
Did you duplicate yourself? See https://github.com/microsoft/vscode/issues/162498

**Comment by vanowm** [comment]
Ops
