### ISSUE TITLE
Take out keymaps code from ExtensionsWorkbenchService

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16493]
The newly introduced keymaps code could and should be done by composing events from the several services into a new contribution, not by fitting it within the ExtensionsWorkbenchService's implementation details.

The new contribution should listen to `onEnablementChanged` from `IExtensionEnablementService` and `onDidInstallExtension` from `IExtensionManagementService` and make it work in an isolated file.

Additionally, if no caller of [`checkForOtherKeymaps`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/extensions/node/extensionsWorkbenchService.ts#L584) checks for its returning promise, it should just return `void` and perform the error handling inside.

**Comment by chrmarti** [comment]
The two services are somewhat hard to work with, I ended up copying stripVersion() and have my own little wrapper, just like extensionsWorkbenchService.ts.
