### ISSUE TITLE
CSS IntelliSense is not working

### ISSUE THREAD

**Issue by carlosvcerqueira** [microsoft/vscode#164914]
Type: <b>Bug</b>

The CSS IntelliSense do not work if you are in a CSS file, only when I'm in a HTML file and use the style tag

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.10GB free)|
|Process Argv|--crash-reporter-id 4803cc24-89a4-4a22-bf60-2d3ebe4e7f08|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.1
postcss|css|1.0.9
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
vscode-exec-node|mir|0.5.4
material-icon-theme|PKi|4.21.0
LiveServer|rit|5.7.9
vscode-mdx|uni|1.0.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by aeschli** [comment]
It works for me. Make sure the editor language mode is set to css (or less  or scss). The language mode can be found on the status bar.
Please try with extensions disabled (some extension take over the css language mode), and make sure the `CSS Language Features` extension  is not disabled (Enter `@builtin css language features` in the extensions view)
![image](https://user-images.githubusercontent.com/6461412/198965508-f72a0fe7-c138-455d-aa08-a516d41586e7.png)
