### ISSUE TITLE
Shellscript: separate language support fo zsh (zsh scope)

### ISSUE THREAD

**Issue by hinell** [microsoft/vscode#164985]
```js
language | shellscript
...
textmate scopes | string.quoted.double.shellmeta.scope....
```
Because `.zsh` is backwards incompatible with `bash` I'm trying to write a snippet specifically targetting `.zsh` scripts. The above is the output I get in a `.zshrc` file (via token inspection devtool) when trying to narrow down the scope for the snippet. Currently it's scoped as a `shellscript`, not `zsh`: https://github.com/microsoft/vscode/blob/7cb1b9d9f00550ffa914432d7ce8ac85d62655b8/extensions/shellscript/package.json#L28-L43

### Request
Any chance we support `zsh` language separately?  I wonder if there is a demand for this. Thank!

**Comment by aeschli** [comment]
I'm not aware of requests for a separate `zsh` language mode, A quick search also didn't give any results.
I'm afraid it would result in lots of languages, given the many shell script dialect, and most extensions written `shellscript` would have to be adopted to also work with the derived languages (or not). So I see mor e drawback than advantages in that case.
Why not define your snippets for shellscript, but name your snippets with `(zsh)`?

**Comment by hinell** [comment]
@aeschli Yeah that's exactly what I do. I just use `zsh` in the snippet's prefix. I agree that there is no wide support for this. I thought it could be quickly and cheaply implemented simply by inheriting `shellscript` `package.json` info. May be even dynamically just like json-schemas are generated. 

I will close this for now.
