### ISSUE TITLE
Enable adding/removing a breakpoint via mouse clicks in the changes/diff editor on a changed line

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode#164919]
Enable adding/removing breakpoints via mouse clicks in the changes/dif editor on a changed line. Maybe it could show a popup for the 2 different options (toggle breakpoint and the -> icon, whatever that is called).

Right now, the breakpoint can't be added/removed because the -> icon blocks it. See the screenshot. The workaround is to use a keyboard shortcut.

![image](https://user-images.githubusercontent.com/19859882/198711910-d9cbae8e-9d1c-4d49-93e5-8c8991304594.png)

**Comment by mccordsm** [comment]
removed rightarrow from gutter

**Comment by roblourens** [comment]
A worse example of this, the decoration for the current line with a breakpoint + the test checkmark: https://github.com/microsoft/vscode/issues/166267#issuecomment-1313464564

**Comment by roblourens** [comment]
I just saw this older issue, if you haven't seen it @hediet https://github.com/microsoft/vscode/issues/114776
