### ISSUE TITLE
Test: ESLint support for file types other than JS

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#16497]
Tests: 
- https://github.com/Microsoft/language-server-protocol/issues/125
- https://github.com/Microsoft/language-server-protocol/issues/126

Complexity: 3

- [x] macOS @kieferrm
- [x] any OS @bpasero  

Install ESLint from here:

To do so, download it and rename the zip to vsix. Then run code-insinder (e.g. code) --install-extension ./vscode-eslint-1.2.0.vsix to install the version of ESLint to test:

- create a new workspace
- install eslint and eslint-plugin-html using npm.
- open the workspace.
- run ESLint - create .eslintrc.json file
- add to it:
```json
    "plugins": [
        "html"
    ]
```
- create a HTML file
```
<!DOCTYPE html>
<html lang="en">
	<script>
		function foo() {
		}
		fo();
	</script>
</html>
```

Observe: no Errors are shown :-)

- open the workspace settings:
- add
```json
"eslint.validate": [
	"javascript", "javascriptreact", "html"
]
```

Observe: errors should be shown in the HTML file.

Play with the following features:

- remove  and add languages from "eslint.validate". The corresponding changes should be hot. E.g. errors disappear when removed and appear when added.
- ensure that you can remove `javascript` as well and JS files are not validated anymore.
- test other ESLint plugins (I know there are plugins for vue and TS files).
- test quick fixes and autofix on save (due to a bug in the HTML plugin this is still only available in JS). To do so make sure the following ESLint rule is enabled in the `.eslintrc.json`: `"no-extra-semi": "warn"`. Add extra semicolons and make sure that the light bulb appears. Execute actions from the light bulb.
- enable auto fix on save using the following workspace setting `"eslint.autoFixOnSave": true` (note as with format on save this is only available if ` "files.autoSave"` is off or on focus lost.). Ensure that fixes are applied on save and that the fixes are applied at the correct positions.

**Comment by dbaeumer** [comment]
The extension for testing: 
[vscode-eslint-1.2.0.zip](https://github.com/Microsoft/vscode/files/633967/vscode-eslint-1.2.0.zip)

**Comment by bpasero** [comment]
@dbaeumer I am not seeing the warning, I have attached my workspace to reproduce. I tried with latest insiders on macOS after having ESLint 1.2.0 installed:

[eslint.zip](https://github.com/Microsoft/vscode/files/635895/eslint.zip)

**Comment by dbaeumer** [comment]
@bpasero thanks. Will have a look. Does it work in a terminal using eslint test.html ?

**Comment by dbaeumer** [comment]
After installing eslint and eslint-plugin-html in the workspace using npm and creating a .eslintrc.json file I get this for the test.js

![capture](https://cloud.githubusercontent.com/assets/1931590/20981253/2c1015f0-bcb4-11e6-9103-897ed8b3b85f.png)

It also works when moving .eslintrc.js.off -> .eslintrc.js

@bpasero lets look together tomorrow at your Mac why this doesn't work for you.

**Comment by kieferrm** [comment]
I saw the warning in the html file during my testing. I'll try @bpasero workspace as well.

**Comment by kieferrm** [comment]
@bpasero The `.eslintrc.json` file in the zip misses rules that generate warnings. Here is a couple that cover the cases in `index.html`:

```json
    "rules": {
        "no-undef": "warn",
        "no-unused-vars": "warn"
    }
```

**Comment by bpasero** [comment]
@dbaeumer @kieferrm I am confused, the description is saying this:

![image](https://cloud.githubusercontent.com/assets/900690/21000235/f9274882-bd19-11e6-98fa-35901e3d4513.png)

There is no mention of adding rules, how am I supposed to know that from the test description?

**Comment by dbaeumer** [comment]
@bpasero the description says

> run ESLint - create .eslintrc.json file

Agree that a better description would have been Run command ESlint - create .eslintrc.json file.

**Comment by kieferrm** [comment]
@bpasero you got the rules implicitly when you ran the **create `.eslintrc.json` file** command from the command palette. It's one of those things where stepping outside the descriptions what we usually encourage during testing did make it harder.
