### ISSUE TITLE
Create options for performing global search that includes rendered and outputted notebook content

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#164926]
Continuation of #148068

With the notebook editors binded to the search model, we can explore adding filter options for rendered markdown and output like there is in the notebook find widget.

<img width="361" alt="image" src="https://user-images.githubusercontent.com/31675041/198733628-f6f16b69-47a7-45ab-bc18-ea588b9fe995.png">

I tentatively think that it would be through a filter icon that only appears when notebooks are binded, but there might be a better way of showing this.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/31675041/198733776-d0dd25f0-5b75-4021-b9b1-49750bc00a0b.png">

**Comment by Okaretkina7** [comment]
> ``

**Comment by andreamah** [comment]
This issue will also cover searching dirty changes in the notebook editor, for read-only and editable content.

**Comment by andreamah** [comment]
will likely go with this type of format for switching between match types (cell input, cell output, rendered/output markdown)
<img width="798" alt="image" src="https://user-images.githubusercontent.com/31675041/216155384-4e033f33-b903-496e-8b1b-7bd474e49fb7.png">
