### ISSUE TITLE
Moving selected text vertically with keyboard

### ISSUE THREAD

**Issue by hamad12a** [microsoft/vscode#164975]
There exist an extension mentioned in this answer from [SE](https://stackoverflow.com/a/59012475/6177652) but if implemented in VS Code as a build-in function it would be better

**Comment by alexdima** [comment]
There is `alt+up` and `alt+down` to move selected text up/down.

The actions are `editor.action.moveLinesUpAction` and `editor.action.moveLinesDownAction`, from default keybindings:
```
{ "key": "alt+down",              "command": "editor.action.moveLinesDownAction",
                                     "when": "editorTextFocus && !editorReadonly" },
{ "key": "alt+up",                "command": "editor.action.moveLinesUpAction",
                                     "when": "editorTextFocus && !editorReadonly" },

```
