### ISSUE TITLE
Feature Request: Support Displaying Videos in Sidebar for Custom Extensions

### ISSUE THREAD

**Issue by saiallu2020** [microsoft/vscode#164923]
**Issue Type:** Feature Request

Please add support in the Extension API to allow videos (mp4) to be displayed in the sidebar. I want to build a VSCode extension called "CodeTube" which allows developers to document their code with video. A developer would record their video through VSCode, explaining different code functions/files/folders. The "CodeTube" extension would then process the video and divide it into bite-sized video clips.

When a new developer joins the team, they can click through different files in the codebase and see the most relevant video clips show up in the VSCode sidebar. This would allow for a great onboarding experience. Video allows us to capture richer explanations than plaintext comments in the code. It's also faster to do than writing several paragraphs of comments.

Right now, the VSCode Extension API doesn't allow for a way to display videos in the sidebar (View Container). It would be really great if you could add this feature!

**Comment by mjbvz** [comment]
This should already be supported using  webviews: https://code.visualstudio.com/updates/v1_71#_ffmpeg-codecs-support

Make sure you are using a supported codec though
