### ISSUE TITLE
Command not found integrated terminal of Ubuntu

### ISSUE THREAD

**Issue by AbuAbdellah** [Microsoft/vscode#16496]
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
Steps to Reproduce:

1. Open Webworks HTML5 project.
2. Run Webworks gives : 
`abd@abd-SATELLITE-C855-2CE:/root/WebWorks Projects/TimeTacker$ webworks
webworks: command not found`

![image](https://cloud.githubusercontent.com/assets/22857205/20883361/a0d56bfc-badd-11e6-86a3-1f7713ab8c26.png)

![image](https://cloud.githubusercontent.com/assets/22857205/20883370/aee44a10-badd-11e6-97ca-fc2782f48869.png)

**Comment by bgse** [comment]
@AbuAbdellah Your first screenshot suggests that this isn't a VSCode issue, given the command does not work on Ubuntu terminal.

If it doesn't work on Ubuntu terminal, you need to figure out why that is (missing package, path issue, etc), fix the problem, and then it should work on VSCode integrated terminal as well.

**Comment by AbuAbdellah** [comment]
@bgse, after re-installing the webworks on user home directory the problem fixed.
![screenshot from 2016-12-06 09-57-15](https://cloud.githubusercontent.com/assets/22857205/20921132/acbac27e-bb9a-11e6-8e3e-6153b2abc2c0.png)

**Comment by ajaygh** [comment]
getting command commandId not found
![commandid](https://cloud.githubusercontent.com/assets/11798274/25779053/ec8c2a8c-332c-11e7-9241-c6380c724fee.png)
