### ISSUE TITLE
F12 not working for JavaScript project

### ISSUE THREAD

**Issue by siddjain** [microsoft/vscode#164911]
Type: <b>Bug</b>

F12 (Goto definition) is not working for any JavaScript project. I do have the built-in TypeScript and JavaScript Language Features extension (vscode.typescript-language-features v1.0.0) enabled.

VS Code version: Code 1.72.2 (Universal) (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|--crash-reporter-id 36275ca0-3e9c-4e60-96ab-a474de46c04b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
vscode-dbt|bas|0.5.1
vscode-markdownlint|Dav|0.48.1
graphviz-markdown-preview|gee|0.0.8
cloudcode|goo|1.20.3
vscode-dbt-power-user|inn|0.8.2
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.40
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
advanced-new-file|pat|1.2.2
vscode-print|pdc|0.10.7
vscode-boot-dev-pack|Piv|0.1.0
vscode-spring-boot|Piv|1.40.0
java|red|1.12.0
jinjahtml|sam|0.19.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.45.0
vscode-java-dependency|vsc|0.21.0
vscode-java-pack|vsc|0.25.3
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.0
vscode-spring-boot-dashboard|vsc|0.7.1
vscode-spring-initializr|vsc|0.11.0
vscode-proto3|zxh|0.5.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/issues/158765#issuecomment-1222475430

**Comment by siddjain** [comment]
I do have `tsconfig.json`.

**Comment by mjbvz** [comment]
Please share a minimal project which demonstrates the issue

**Comment by siddjain** [comment]
embarrassed to say this but this was a problem with my keyboard. the function keys (F lock) were turned off.
