### ISSUE TITLE
Cannot attach to AKS container

### ISSUE THREAD

**Issue by francotiveron** [microsoft/vscode#164949]
Type: <b>Bug</b>

Using the following launch.json configuration

```
{
            "name": "api aks attach",
            "type": "coreclr",
            "request": "attach",
            "processId": "${command:pickProcess}",
...
```

the debug session, fails. this is what I see

![image](https://user-images.githubusercontent.com/8280970/198816538-398e0711-19c9-4dbe-898c-4aed923e8895.png)

Note that if I avoid using pickProcess

```
        {
            "name": "api aks attach",
            "type": "coreclr",
            "request": "attach",
            "processId" : 1,
...
```

the debug session succeeds.

VS Code version: Code - Insiders 1.73.0-insider (3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709, 2022-10-27T21:34:51.585Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.73GB (36.64GB free)|
|Process Argv|--crash-reporter-id 069701b0-35c0-493b-b96d-091de8b8f40e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (52)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-template-fsharp-highlight|alf|1.7.0
k8s-snippets|dog|0.4.2
gitlens|eam|13.0.3
vscode-open-in-application|fab|1.0.6
remotehub|Git|0.44.0
cloudcode|goo|1.20.3
flux|inf|1.0.4
Ionide-fsharp|Ion|7.3.1
bash-ide-vscode|mad|1.14.0
file-downloader|min|1.0.12
mindaro|min|1.0.120220915
ecdc|mit|1.8.0
azure-pipelines|ms-|1.208.0
azure-dev|ms-|0.3.0
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.8.3
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-azurestorage|ms-|0.15.0
vscode-azurevirtualmachines|ms-|0.6.2
vscode-bicep|ms-|0.11.1
vscode-cosmosdb|ms-|0.19.2
vscode-dapr|ms-|0.6.1
vscode-docker|ms-|1.22.2
csharp|ms-|1.25.0
vscode-dotnet-runtime|ms-|1.5.0
vscode-aks-tools|ms-|1.3.4
vscode-kubernetes-tools|ms-|1.3.10
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.40
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.0
remote-wsl|ms-|0.72.0
azure-account|ms-|0.11.2
azurecli|ms-|0.5.0
hexeditor|ms-|1.9.9
powershell-preview|ms-|2022.10.2
remote-repositories|ms-|0.23.2022102701
vscode-node-azure-pack|ms-|1.1.0
azurerm-vscode-tools|msa|0.15.8
debugger-for-chrome-nightly|msj|2020.2.15300
vscode-thunder-client|ran|1.20.1
vscode-yaml|red|1.10.1
bash-debug|rog|0.3.9
kubernetesapply|Sha|1.4.1
azure-event-hub-explorer|Sum|0.1.1
large-file|yy0|1.0.12
k8s-snippets|yzd|0.1.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
pyind367:30587847
vscccc:30564267
pyindex848:30577858
nodejswelcome1:30587009
gswce1:30598410
j6j51389:30596843

```

</details>

**Comment by roblourens** [comment]
Please file this on the debug extension you're using
