### ISSUE TITLE
html prompt suggestion     Problem

### ISSUE THREAD

**Issue by AsukaSoryu0** [microsoft/vscode#164956]
Type: <b>Feature Request</b>

<div class="box"></div>

    <script>
        const box = document.querySelector('.box')

        box.addEventListener('touchstart', function () {
            box.style.backgroundColor = 'red'
        })

        box.addEventListener('touchmove', function () {
            box.style.backgroundColor = 'hotpink'
        })

        box.addEventListener('tou', function () {
            box.style.backgroundColor = 'yellow'
        })

    </script>

touchstart,touchmove,touchend   
It's not automatically prompted, but in a  js file, it will be prompted

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by aeschli** [comment]
`document.querySelector('.box')` returns a object of type `Element`, which does not support many events.
To get your type you have to make a typecheck:

```
	const box = document.querySelector('.box');
	if (box instanceof HTMLElement) {
		box.addEventListener('...)
	}
```

**Comment by AsukaSoryu0** [comment]
> 在TypeScript中，你可以只制作一个强制转换（但由于这是JavavScript，因此强制转换看起来像这样：`document.querySelector<HtmlElement>('.box');`
> 
> ```
> /** @type HTMLElement */
> const box = document.querySelector('.box');
> ...
> ```
> 
> 当然，如果你对元素的类型有更多的了解，你甚至可以做一个更具体的转换（例如，到HTMLImageElement）。
Thank you！I hava got it！
