### ISSUE TITLE
Add the ability for extensions to add input to a terminal window

### ISSUE THREAD

**Issue by jamestut** [microsoft/vscode#164948]
I'd like to add an input box on each of the terminal window as illustrated on the attached image. The use case for this is to "kill latency" where I can just type text in that form, and when I press enter, VSCode is going to type the entered text to the terminal. This is especially useful as I often work with remote SSH server located on the opposite side of the globe. I can also easily revise the commands/text that I want to enter using OS' native keyboard shortcuts and selection capabilities. I am aware that VSCode have the "local echo" feature, but sometimes it is not reliable (typing prediction is a difficult problem after all).

Another use case for this feature is to have a unified history across different hosts and to be effortlessly able to preserve my typing history on devices with no persistent storage (e.g. devices for testing).

<img width="1136" alt="Screen Shot 2022-10-28 at 9 12 02 am" src="https://user-images.githubusercontent.com/15940448/198815111-bdce339d-91f8-4a3b-aff0-d8080c6b803b.png">

**Comment by gjsjohnmurray** [comment]
Could you make creative use of the Interactive Window feature of the notebook interface? The [REST Book](https://marketplace.visualstudio.com/items?itemName=tanhakabir.rest-book) extension is an example of IW.

**Comment by Tyriar** [comment]
You could create an extension that pops up a quick input and sends that to the active terminal. To do this "properly" would be a lot of work though so it's out of scope.
