### ISSUE TITLE
Too many files staged for changes (10K+) before Commit that I did not make.

### ISSUE THREAD

**Issue by ddhay** [microsoft/vscode#164913]
Type: <b>Performance Issue</b>

When I open any folder to work on in VSC, I get a popup in lower right hand corner that reads:
"The git repository at C:\Users\Darrell has too many active changes, only a subset of Git features will be enabled.  Source: Git Extension."
  When I click on Source Control, I get a similar message showing 10K changes ready to Commit.  None of the changes being reported are related to my project.  Please advise what to do to fix this problem.
Darrell Haywood.  October 28, 2022.
ddhay@msn.com, ddhay41@gmail.com

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700T CPU @ 2.00GHz (16 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (8.09GB free)|
|Process Argv|--crash-reporter-id 67816ed0-c9eb-4b5a-9bbd-ae9d920ee44d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 11188	code main
    0	    88	   988	   issue-reporter
    0	    39	  3848	   utility-network-service
    0	   113	  4060	   shared-process
    0	    72	  6352	     ptyHost
    0	   101	 22292	     fileWatcher
    0	   140	  8136	   extensionHost
    0	    75	 15028	     "C:\Users\Darrell\AppData\Local\Programs\ VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Darrell\AppData\Local\Programs\ VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=8136
    0	   102	 22604	     "C:\Users\Darrell\AppData\Local\Programs\ VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\Darrell\AppData\Local\Programs\ VS Code\resources\app\extensions\html-language-features\server\dist\node\htmlServerMain" --node-ipc --clientProcessId=8136
    0	   213	 11700	   window (index.html - Unifeed-11-8.21-final 1.39pm - Visual Studio Code)
    0	    26	 19488	   crashpad-handler
    0	   145	 21224	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (index.html - Unifeed-11-8.21-final 1.39pm - Visual Studio Code)
|    Folder (Unifeed-11-8.21-final 1.39pm): 18 files
|      File types: png(10) svg(2) json(1) DS_Store(1) html(1) css(1)
|      Conf files: settings.json(1);
```

</details>
Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by gjsjohnmurray** [comment]
I guess you somehow initialized a Git repository in your  C:\Users\Darrell folder. Look for a in there named .git

Whenever you open  C:\Users\Darrell or any descendant folder in VS Code it will conclude you want to manage all its contents with Git.

I suggest you close VS Code, rename that .git folder, then open VS Code.

If that fixes the issue and you are certain you don't need that repository, delete the renamed folder.

**Comment by ddhay** [comment]
Thank you, John.  That worked.
