### ISSUE TITLE
Search for cmake project

### ISSUE THREAD

**Issue by MaJerle** [microsoft/vscode#164918]
When using cmake as build provider, a search tool could use files described by cmake that are outside workspace folder, to search in.

https://github.com/microsoft/vscode-cmake-tools/discussions/2826

**Comment by roblourens** [comment]
This sort of thing has been suggested before, but to me it feels contrary to vscode's philosophy of being a folder-based text editor, not a project-based IDE.

cc @andreamah

**Comment by roblourens** [comment]
Sorry, what you are proposing is what has been brought up in the past. I don't think it fits into vscode. One example is https://github.com/microsoft/vscode/issues/109472
