### ISSUE TITLE
Explore updated built-in color themes

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#164924]
Our built-in themes (e.g. Dark+, Light+) are, as you might expect, among the most popular themes used by VS Code users. However, as the years have gone on, the themes are starting to feel dated. I think it's worth exploring how we could refresh them to ensure VS Code continues to feel modern and fresh as well as solving for known contrast/usability issues along the way.

## Examples

These quick sketches show what Dark+ and Light+ could look like if only the workbench theme colors were updated. They do not change the syntax highlighting, however that could make sense as a next step.

![CleanShot 2022-10-28 at 13 26 12@2x](https://user-images.githubusercontent.com/25163139/198726245-79d9ceac-dca5-42a6-afd1-fa65bb0d5b87.png)

![CleanShot 2022-10-28 at 13 25 02@2x](https://user-images.githubusercontent.com/25163139/198726053-b7f91ef7-5381-4af3-a1bb-3174ce5bfc4e.png)

## Next steps

There are at least two clear options to move forward. I'm sure there are other approaches, but two obvious paths include:

1) Gradually update the existing themes over a series of releases.
2) Release a net new set of themes but keep the old themes as a "legacy" option. New installs would get the new themes automatically. Existing installs could be prompted to switch to the new theme or keep the legacy theme if they perfer.

Feedback and thoughts welcome 🙏

**Comment by awerlogus** [comment]
In my personal color theme, I painted the sidebar in the same color as the editor area so it would not attract the attention of peripheral vision while editing the code

**Comment by kytosai** [comment]
I hope with GTK4, vscode on ubuntu can bend all 4 sides of the window. Currently the vscode window is still 4 square corners on ubuntu 22.

![image](https://user-images.githubusercontent.com/1908652/203136460-87d7e6ea-1cc1-410d-b441-1e16119b26d9.png)

**Comment by daviddossett** [comment]
Here are some updates after talking with the team. Feedback welcome.

## Rolling out the new themes

This is likely to take place over two phases:
1) Add "Experimental" themes to VS Code to gather feedback on the new themes
2) When ready, the new themes will be set as the default, replacing Dark+ and Light+. If you are currently using either the Dark+ or Light+ theme, you'll get a notification telling you that we've updated them. This notification will let you switch back to the old one if you'd prefer. It's likely that we will move the old themes to the marketplace rather than keep them in the product. This means you can install the themes as an extension pack.

## So what do they look like? 

Here are a few options that we're looking at:

### Dark

Dark editor, everything else lighter:

<img width="1100" alt="Frame 1321314421" src="https://user-images.githubusercontent.com/25163139/204407627-6e37b716-140c-48ac-ab61-d45846158488.png">

Dark sidebar, everything else lighter:

<img width="1100" alt="Frame 1321314418" src="https://user-images.githubusercontent.com/25163139/204407656-b41e64ae-18a5-472b-b482-2abe1443a7bf.png">

Light editor, everything else darker:

<img width="1100" alt="Frame 1321314419" src="https://user-images.githubusercontent.com/25163139/204407668-dd31152f-a041-4979-87a3-51ccecb1fa6e.png">

Entire workbench normalized to one darker color:

<img width="1100" alt="Frame 1321314420" src="https://user-images.githubusercontent.com/25163139/204407683-0be0cec8-d3da-46a4-b2cb-e55ab41f58fb.png">

### Light

Grey sidebar, everything else white:

<img width="1100" alt="Frame 1321314422" src="https://user-images.githubusercontent.com/25163139/204407706-71a3736b-b767-48d8-ab87-3c03e15fafdb.png">

White editor, everything else grey:

![CleanShot 2022-11-28 at 16 20 34@2x](https://user-images.githubusercontent.com/25163139/204407992-62996c40-a577-45b4-8caf-e8e1daca2a31.png)

Entire workbench normalized to white:

<img width="1100" alt="Frame 1321314425" src="https://user-images.githubusercontent.com/25163139/204407733-b8b0ef3d-967e-4f62-a9a6-b4660dbbf5ee.png">

**Comment by awerlogus** [comment]
Yet another option: everything around the editor is painted in its color, the rest is darker

![изображение](https://user-images.githubusercontent.com/24425566/204471904-cbdf8fa1-b2e5-41e3-8111-8e82ce654440.png)
![изображение](https://user-images.githubusercontent.com/24425566/204473273-52f2c991-327a-4da0-84c2-0b290dfaef59.png)

**Comment by Studio384** [comment]
I throw my hat in for these 2:
- Dark theme: Light editor, everything else darker
- Light theme: White editor, everything else grey

They're the logical choice since we perceive lighter things to be close by and thus be the most important elements on screen.

**Comment by daviddossett** [comment]
> Dark theme: Light editor, everything else darker
Light theme: White editor, everything else grey

👍 that's is basically what I went with to start. Here's a quick look at how it looks just touring around the basic UI:

https://user-images.githubusercontent.com/25163139/204674428-024a2a9f-880c-46eb-9659-2d19d16b3e2c.mp4

I'll get this landed in Insiders in the next week or so so you can give it a spin 🙏

**Comment by daviddossett** [comment]
The new themes are now merged via https://github.com/microsoft/vscode/pull/167104.

Please feel free to file new issues as you try them out so I can better track them individually 🙏

**Comment by nonameolsson** [comment]
Nice work! 👍🏻 
I'm not so experienced with themes in VS Code. How can we try it out?

**Comment by nickolasoverlay** [comment]
Hi, i found a small issue. If i choose update built-in theme (Dark+ V2) the theme choice gets automatically reset to the the old Dark+ version. Same thing happens if i choose any other theme

Version: 1.75.0-insider
Commit: b92894493e6f971a3c71912d823e699d3a05d643
Date: 2022-12-08T05:37:36.940Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: Yes

https://user-images.githubusercontent.com/65836795/206389533-485b9ecc-922f-4409-8045-0a94efc6873b.mov

**Comment by nonameolsson** [comment]
> Hi, i found a small issue. If i choose the updated built-in theme (Dark+ V2), the theme choice gets automatically reset to the the old Dark+ version. Same thing happens if i choose any other theme.
> 
> Version: 1.75.0-insider Commit: [b928944](https://github.com/microsoft/vscode/commit/b92894493e6f971a3c71912d823e699d3a05d643) Date: 2022-12-08T05:37:36.940Z Electron: 19.1.8 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Darwin arm64 22.2.0 Sandboxed: Yes
> 
>  Screen.Recording.2022-12-08.at.09.48.12.mov

I can confirm that the same things happens for me with Insiders.

**Comment by daviddossett** [comment]
@nickolasoverlay @nonameolsson I see the same behavior now too after updating to today's Insiders. I believe this is an issue with the quick pick that isn't specific to themes. https://github.com/microsoft/vscode/issues/168425

**Comment by nickolasoverlay** [comment]
@daviddossett Thanks for the tip! I also found another issue related to Default Light+ Experimental specifically.

The issue is related to the contrast of cursor inside integrated-terminal. In my specific case, cursor has a block shape (caused by Vim extension)

![Screenshot 2022-12-08 at 18 04 39](https://user-images.githubusercontent.com/65836795/206497990-7421711e-f419-46bb-acb5-9a0da46fcc46.png)

**Comment by mon-jai** [comment]
It would be better if we reduce saturation for code colors IMO.

**Comment by mon-jai** [comment]
The blue code color in updated light theme feels wield. It has a higher saturation than other colors of the theme.

We should lower its saturation IMO.

**Comment by Igorgro** [comment]
Tried new the Dark theme in 1.75. In my opinion, it is much darker than the previous theme, very close to `#000000` and should be called "black theme", not "dark". Comparing with GitHub, for example, old dark theme is like "dark" and new dark theme is like "dark high contrast". I prefer to stay on old theme

**Comment by widersky** [comment]
I'm on the other side - the new themes are great! You can consider adding their more subdued variations in the future (e.g. a slightly lighter dark mode) but the current options are great and I use them every day :)

**Comment by dlschmidt** [comment]
https://github.com/microsoft/vscode/issues/173475
Please inspect this bug when working with terminals under V2 themes.

**Comment by smbkr** [comment]
@daviddossett would you prefer feedback on the new themes via separate issues, or in this thread?

A minor bit of feedback: 

With Light+ v2, it's much harder to tell which tab in the sidebar is selected. Compare the two screenshots:

|v1|v2|
|---|---|
|<img width="76" alt="Screenshot 2023-02-09 at 10 28 15" src="https://user-images.githubusercontent.com/933535/217787321-439c87ac-5cb1-43d4-9dde-4f07a6e3d524.png">|<img width="77" alt="Screenshot 2023-02-09 at 10 28 21" src="https://user-images.githubusercontent.com/933535/217787316-d7cf06d4-7bbf-46ac-81a6-f5f99bd6c907.png">|

In the "old" theme, the whole icon foreground colour changes, so it's easy to see what tab is active at a glance. With the v2 theme, only the chip to the left indicates the selection, which is hard to see, especially when using a fullscreen or left-aligned window, as it blends in with the bezel of the screen.

**Comment by daviddossett** [comment]
> would you prefer feedback on the new themes via separate issues, or in this thread?

Ideally in new issues. But I continue to monitor this one as I tweak the themes based on the feedback. 

The active items are actually a darker/lighter color than the inactive items, but I agree that it could be more obvious. I'll see what I can do here and will push up some changes 👍 

<img width="54" alt="CleanShot 2023-02-09 at 09 12 13@2x" src="https://user-images.githubusercontent.com/25163139/217887674-577fe9e6-e732-4a56-8764-63fcd2b498ab.png">
<img width="54" alt="CleanShot 2023-02-09 at 09 12 22@2x" src="https://user-images.githubusercontent.com/25163139/217887683-153d84c1-6d31-4500-83fb-ac5252c2863c.png">

**Comment by daviddossett** [comment]
> Thoughts on adding translucency and blurring to the sidebar and the tab bar?

@quackerex this is something we've talked about to inherit some nice Fluent design bits, but I believe it isn't possible with an electron-based app at the moment.

> I wonder why the remote icon in the left-bottom corner is blue while the other areas are all white or black. It always attracts my eyes.

@zeyugao this is mostly to encourage usage of remote development. But we could consider making it less prominent if others have the same feedback. cc @bamurtaugh for remote context.

**Comment by bamurtaugh** [comment]
Yes, would definitely be interested in the broad remote indicator feedback here! As it's already a small and potentially unfamiliar button, the goal of a more prominent color is as @daviddossett mentions (attracting attention is a good thing from this perspective 😄).

**Comment by aradalvand** [comment]
Just wanted to chime in and say I just tried the new theme and I think it's really good; I made the switch from [Material Theme](https://marketplace.visualstudio.com/items?itemName=Equinusocio.vsc-material-theme) and the contrast is generally a lot better in Dark+ V2, while it also doesn't look outdated like legacy Dark+.

The only thing I would say I don't like the high contrast when it comes to things like Git diff markers (I'm not sure what they're called?) — this is how they look (when you add a new line to a source-controlled file) in legacy Dark+:

![image](https://user-images.githubusercontent.com/26527405/222877598-6f9d2e0d-5cc5-4428-9b89-d20f3b251008.png)

And this is what it looks like in Dark+ V2 — it's too bright in my opinion, a slightly dimmer color would be more suitable:

![image](https://user-images.githubusercontent.com/26527405/222877602-ef27fb6a-9403-427d-867a-370d692d23dc.png)

**Comment by daviddossett** [comment]
Thanks for the find @aradalvand. I'll take a pass at these to make them less prominent 👍

**Comment by mrcaidev** [comment]
Personal opinion: This blue border on focus is a bit distracting. And the right border is somehow hidden.

![image](https://user-images.githubusercontent.com/78269445/225515038-00a1f562-0887-4b84-9107-a184ea447a8f.png)

**Comment by widersky** [comment]
@mrcaidev it's easy to disable and AFAIK enabled for accessibility. You can disable it by adding this to your `settings.json`:

```json
"workbench.colorCustomizations": {
    "focusBorder": "#ff000000",
    "list.focusAndSelectionOutline": "#ff000000",
}
```

**Comment by akpircher** [comment]
One of the reasons I've really settled on VSCode as my editor is because the default Dark+ theme does not have a lot of high contrast.

The new V2 theme seems more like a hybrid between the Dark High Contrast and existing Dark+, and within seconds of having either of those themes open, my eyes begin to hurt and I can feel a headache forming. It's also a lot harder to read filenames that have problems - the contrast between the yellow and the black almost render my glasses useless, I'm curious if anyone else with an astigmatism is having similar problems.

Does moving the current Dark+ Theme to the marketplace mean it will eventually stop being maintained or not be updated as frequently? If so, would it be possible to call this theme "Dark+ Mid Contrast" or something instead?

**Comment by xamir82** [comment]
@akpircher I don't see a reason why someone couldn't just keep using the old Dark+. I don't think they're going to remove it or anything.

**Comment by akpircher** [comment]
@xamir82 they say pretty explicitly above that the experimental V2 will, once it's not experimental anymore, replace the Dark+ default and the current Dark+ will be moved to the marketplace.

Hence my questions about maintenance.

**Comment by kytosai** [comment]
I think "**Dark sidebar, everything else lighter**" is the best choice, because it has just enough contrast, not too dark. 
And it gives a better experience than the current "Dark+ V2" (it's too black)

![image](https://user-images.githubusercontent.com/1908652/226110469-6261b27d-38c1-4323-80c3-95a68f7b61fd.png)

**Comment by HaveSpacesuit** [comment]
On big difference keeping me from switching to Light+ V2 is the difference I see in my tabs. I currently depend on only the blue line at the top to indicate unsaved changes. On Light+ V2, the active tab has a blue line at the top, making me paranoid I've accidentally made an unintended change, or haven't hit save...

![image](https://user-images.githubusercontent.com/15036346/226236176-54598457-31f1-4dc8-9d1a-f450a1e65f23.png)

**Comment by daviddossett** [comment]
Hey folks, closing this issue now that we've shipped the themes as the new defaults in the stable release as `Dark Modern` and `Light Modern` 🚀 

Please file individual issues for any feedback/bugs you see going forward. I've noted the issues in this thread, as well as other existing issues, and will be making another round of updates in the upcoming release(s). Thank you for the great feedback and ideas thus far!

**Comment by mon-jai** [comment]
@daviddossett Will syntax highlighting colors be updated too?

**Comment by zm-cttae** [comment]
I would like to see a bit of work there 😺
For one, I think all of the colours get set to the same luminance, so that they come from the same palette.

**Comment by struong-stripe** [comment]
@daviddossett what color theme do you use?

**Comment by daviddossett** [comment]
> @daviddossett ooc what color theme + font do you use?

Dark Modern, default fonts. Light Modern of Light High Contrast if I'm working outside 😉 Also a fan of the GitHub themes.

**Comment by ouweiya** [comment]
![image](https://github.com/microsoft/vscode/assets/28357731/7f536636-9252-4b7e-a9c0-d5bf3bafd54a)

If you want to keep the remote host button colors consistent.

```json
  "workbench.colorCustomizations": {
    "statusBarItem.remoteBackground": "#181818"
  },
```
