### ISSUE TITLE
Update JSDoc on `updateWorkspaceFolders` when extension host will restart

### ISSUE THREAD

**Issue by paulober** [microsoft/vscode#165010]
Does this issue occur when all extensions are disabled?: Yes/No
No

- VS Code Version: 1.72.2
- OS Version: Windows 11 22H2

Steps to Reproduce:

1. Create a new extension with it's own filesystem provider.
2. Mount the new filesystem with `updateWorkspaceFolders`.
3. VSCode reloads extension

Bug:
Every time i mount my filesystem the hole extension reloads:
```
[2022-10-30 16:10:57.926] [exthost] [info] Extension host terminating: received terminate message from renderer
[2022-10-30 16:10:57.949] [exthost] [error] ProxyResolver#resolveProxy DIRECT Canceled: Canceled
```

I think it has to do with the note you added to `updateWorkspaceFolders` jsdoc:
`If the first workspace folder is added, removed or changed, the currently executing extensions (including the one that called this method) will be terminated and restarted so that the (deprecated) rootPath property is updated to point to the first workspace folder.`

So the bug is that it also reloads the extensions if you add a workspace and not change or remove the first workspace folder.
That's realy bad if your extension keeps a constant connection with a remote location to keep the remoteFilesystem connected which will be terminated if the extension gets restarted by vscode.

**Comment by bpasero** [comment]
Yeah we probably should update the JSDoc that we also reload extension host when going from 1 folder to 2 or more folders.

**Comment by paulober** [comment]
@bpasero And is there any way that i can avoid this behaviour when mounting my remote workspace?

**Comment by bpasero** [comment]
No, see https://github.com/microsoft/vscode/issues/69335
