### ISSUE TITLE
Extenison package.json badges: Incorrect type. Expected "object".

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#165012]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/198890322-c8d1933b-e550-438e-901c-0b6751305630.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/198890339-2dbbfda8-402c-4284-a1e0-cd406a8e8d40.png">

Versions:

```
Version: 1.73.0-insider (Universal)
Commit: 3544aabd5a2b0da2cd3a6f3fa3f00759aa9d9709
Date: 2022-10-27T21:41:11.954Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: Yes
```

**Comment by aeschli** [comment]
Looks like `badges` [is now also defined](https://github.com/SchemaStore/schemastore/commit/cfe02821ecef951790bf387a726c3c7183daf485) in the standard schema for `package.json`, but with an object as type:
https://github.com/SchemaStore/schemastore/blob/cfe02821ecef951790bf387a726c3c7183daf485/src/schemas/json/package.json#L767
https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/npm-badges.json


conflicting with the badges we support for VS Code packages (array)

We were first, but I guess that doesn't help ;-)

**Comment by aeschli** [comment]
Hopefully https://github.com/SchemaStore/schemastore/issues/2582 will be accepted.

**Comment by aeschli** [comment]
https://github.com/SchemaStore/schemastore/issues/2582 was accepted
