### ISSUE TITLE
VSCode not honoring extensions versions on devcontainer.json

### ISSUE THREAD

**Issue by doublethink13** [microsoft/vscode#165005]
Type: <b>Bug</b>

Using this devcontainer.json file:

```
{
  "name": "Python-3.10.8",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "extensions": [
    "ms-python.python@2022.16.0",
    "ms-python.vscode-pylance@2022.10.10",
    "esbenp.prettier-vscode@9.8.0",
    "sourcery.sourcery@0.12.3"
  ],
  "remoteUser": "python"
}
```

After devcontainer finishes its setup, I get the following extensions:

```
$ code --list-extensions --show-versions
Extensions installed on Dev Container: Python-3.10.8:
esbenp.prettier-vscode@9.8.0
ms-python.python@2022.16.1
ms-python.vscode-pylance@2022.10.40
ms-toolsai.jupyter@2022.9.1202862440
ms-toolsai.jupyter-keymap@1.0.0
ms-toolsai.jupyter-renderers@1.0.10
ms-toolsai.vscode-jupyter-cell-tags@0.1.6
ms-toolsai.vscode-jupyter-slideshow@0.1.5
sourcery.sourcery@0.12.3
```

I don't want to install any Jupyter related extensions. I would also like to have the specified versions in the devcontainer.json actually honored for the ms-python.python and the ms-python.vscode-pylance extensions.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:26.920Z)
OS version: Linux x64 5.15.0-52-generic
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|15.34GB (11.23GB free)|
|Process Argv|. --crash-reporter-id 77a8fa93-6940-434f-9a12-36d9bb7a8bb4|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Python-3.10.8|
|OS|Linux x64 5.15.0-52-generic|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2300)|
|Memory (System)|15.34GB (11.24GB free)|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.21.0
prettier-vscode|esb|9.8.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.40
sourcery|sou|0.12.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by gjsjohnmurray** [comment]
For the version issue see #158143

**Comment by chrmarti** [comment]
The Python extension brings in the Jupyter extensions. This works as expected, you could file an issue with the Python extension for it. Closing as the remaining issue is tracked in https://github.com/microsoft/vscode/issues/158143. Thanks.
