### ISSUE TITLE
Debugging is normal, but abnormal after publishing

### ISSUE THREAD

**Issue by baikaishui01** [microsoft/vscode#165028]
- VS Code Version: 1.72.2
- OS Version: macOS 12.1 Monterey(13-inch, M1, 2020)

### demo
[this is a demo for issue](https://github.com/baikaishui01/demo-for-issue)

### my problem
It work normal when i am debugging.but when i publish, install and use command "issueDemo.showLint". it toast an error, like follow image
![](https://user-images.githubusercontent.com/48601669/198847251-1c2cdcfa-7e1f-4202-a1c8-5519b988bc9b.png)

### it work normal when i am debugging. eg:
![](https://user-images.githubusercontent.com/48601669/198846581-9d1d7747-d1f9-4226-8e0f-661c8d0a0a75.png)

**Comment by gjsjohnmurray** [comment]
Please try adding `"onCommand:issueDemo.showLint" ` to your activationEvents.

**Comment by baikaishui01** [comment]
> 

In fact, I have tried before submitting the issue

**Comment by baikaishui01** [comment]
> Please try adding `"onCommand:issueDemo.showLint" ` to your activationEvents.

In fact, I have tried before submitting the issue

**Comment by gjsjohnmurray** [comment]
Does your `webpack.config.js` need to declare another value for `entry`?

**Comment by roblourens** [comment]
Some things to check

- Any error messages, eg in devtools (Help > Toggle Developer tools)?
- Did the correct code get published to the marketplace?
- Did your extension actually get activated?

If you need to make changes to test, you can iterate faster by packing a vsix (`vsce package`) and installing that (the "Install From VSIX" command) which likely will show the same problemm.

**Comment by baikaishui01** [comment]
> Some things to check
> 
> * Any error messages, eg in devtools (Help > Toggle Developer tools)?
> * Did the correct code get published to the marketplace?
> * Did your extension actually get activated?
> 
> If you need to make changes to test, you can iterate faster by packing a vsix (`vsce package`) and installing that (the "Install From VSIX" command) which likely will show the same problemm.

Thanks, I have located the problematic code fragment and solved it yesterday. The problem is that I referenced the 'fs-extra' dependency. But I still don't know the specific reason. I will reply here when I have time to film and check the specific reason.
