### ISSUE TITLE
Expanding an object in the console after a step will show the wrong properties

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16504]
VS Code Insiders v1.8.

- Hit a breakpoint
- Eval something in the console that evaluates to an object
- Step again
- Expand the object in the console
- It will show the properties from another object, or nothing

VariableReferences are only valid between events returned from the debug adapter. For this reason the REPL may only uses handles returned from the evaluate requests until the next event occurs. When an event occurs the old objects showing in the REPL needs to be frozen and trying to drill deeper into them should be prevented.

**Comment by roblourens** [comment]
It seems like this should be left up to the debug adapter - I can implement it, and it's useful, so why prevent it?

**Comment by roblourens** [comment]
To expand on that, in Chrome devtools, a logged object can be expanded at any time before the page is refreshed.

**Comment by weinand** [comment]
I agree. I will look into this in January.

**Comment by weinand** [comment]
Nothing planned here because as Rob said: "It seems like this should be left up to the debug adapter".
