### ISSUE TITLE
Allow to configure electrons defaultFontFamily , defaultFontSize , defaultMonospaceFontSize , minimumFontSize

### ISSUE THREAD

**Issue by lukts30** [Microsoft/vscode#16507]
- VSCode Version: 1.7.2
- OS Version: Kde neon 5.8 (ubuntu 16.04)

Steps to Reproduce:

1. On a hidpi display there is no option to set the font size of the dev tools unlike chrome where it is possible to set the minimum font size ( chrome://settings/fonts ) .

2. electron seems to support this [http://electron.atom.io/docs/all/](http://electron.atom.io/docs/all/) :
defaultFontFamily , defaultFontSize , defaultMonospaceFontSize , minimumFontSize

https://github.com/electron/electron/pull/4163

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
