### ISSUE TITLE
[jsx] Mark occurrences on embeddded html: Select open and closing tag

### ISSUE THREAD

**Issue by wilsonmarkj067** [Microsoft/vscode#1650]
In large files, it is very difficult to identify the closing tag. When the cursor is present inside the opening tag, only closing tag should be highlighted.

**Comment by aeschli** [comment]
That's already what we do. The overview ruler shows helps you find the marked areas if the file is large.
![image](https://cloud.githubusercontent.com/assets/6461412/12200584/0274c240-b620-11e5-94d3-b5140bdfcb94.png)

Please reopen if I misunderstood.

**Comment by wilsonmarkj067** [comment]
Well, the problem is this. 

<img width="339" alt="screen shot 2016-01-11 at 12 07 49 am" src="https://cloud.githubusercontent.com/assets/15795265/12223218/75a532d0-b7f7-11e5-819e-ec1795511503.png">

This is a .jsx file. I hope you guys get the issue this time.

**Comment by wilsonmarkj067** [comment]
Well, the problem is this. 

<img width="339" alt="screen shot 2016-01-11 at 12 07 49 am" src="https://cloud.githubusercontent.com/assets/15795265/12223218/75a532d0-b7f7-11e5-819e-ec1795511503.png">

This is a .jsx file. I hope you guys get the issue this time.

**Comment by wilsonmarkj067** [comment]
I cannot reopen the issue. @aeschli

**Comment by egamma** [comment]
In JSX files mark occurrences is currently done just textually (and it is unrelated to what is done in .html files).

We will switch the underlying infrastructure to Salsa see Microsoft/TypeScript#4789. Salsa will provide what is done in .tsx files in .jsx files. I've just checked the latest support in .tsx and this feature request isn't covered. I suggest to reproduce your problem in a .tsx file and then file a feature request against typescript https://github.com/Microsoft/typescript.

**Comment by dlong500** [comment]
I'm not seeing anything in the typescript repo about this, and I'm finding it hard to find the right terminology to search for it.  Has there been any movement on this feature in typescript that will fix this for vscode?  It's a major pain when dealing with large JSX blocks to not be able to easily see matching opening/closing tags.
