### ISSUE TITLE
VS Code started from terminal holding console open

### ISSUE THREAD

**Issue by AnrDaemon** [microsoft/vscode#165043]
Type: <b>Bug</b>

I've reported this issue earlier and got a response to use wrapper scripts from `./bin/` directory.
Unfortunately, they only cure half the problem. The diagnostic messages cease to appear in console, but the console remains to be held by the VS Code process until I completely exit the IDE, even if application I've opened the workspace from is long gone.

Simple reproduction:

1. Win+X, open command prompt.
2. Call "%ProgramFiles%/Microsoft VS Code/bin/code.cmd" "%path%/to/your/workspace"
3. In command prompt terminal, type `exit`.
4. Even though the command interpreter is gone, the console window remains open.
5. Close VS Code. The console will close following shutdown of the IDE.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows/any
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (10.33GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/Admin/Documents/hk/invapi-php|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by AnrDaemon** [comment]
The previous issue was #98164

**Comment by bersbersbers** [comment]
This goes back as far as #6608 :) Are you aware of #10162?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/66750
