### ISSUE TITLE
Allow extensions to have visibility into the user's build command

### ISSUE THREAD

**Issue by doriext** [Microsoft/vscode#16501]
This feature request is required in order for IncrediBuild to be able to offer in its extension for VS Code the level of user experience we offer in Visual Studio.

IncrediBuild is the de-facto Visual Studio C++ \ XBox \ Android NDK **build acceleration** installed on more than 100,000 machines worldwide and as part of a partnership we've done with MS, IncrediBuild is offered as a freemium version as part of the VS2015 and soon VS2017 (any VS user can access IncrediBuild directly from within VS).

IncrediBuild is also used to accelerate a variety of compilers and build tools such as Make, Scons, ninja, Jom, Jam and many others.
 
IncrediBuild offers an extension inside IDEs allowing users to execute their builds in a distributed manner, seamlessly harnessing hundreds of idle CPUs they already own across their local network or public cloud to highly accelerate compilations \ tests \ code generation and any other compute intense process.
IncrediBuild effectively transforms the developer's 8 cores laptop into a virtual super computer with hundreds of cores and gigs of memory.

In order for IncrediBuild's VS Code extension to offer users the same seamless integration as offered in Visual Studio, we need to get as an input the build command that the user executes when compiling his project.
 
We can call VS Code's API function executeCommand to execute the 'workbench.action.tasks.build' command to build the project, however, we didn't find a way to have VS Code translate the command name to the full command line for IncrediBuild to execute.
 
We seek a way to convert the 'workbench.action.tasks.build' command to a full command line which we can feed to BuildConsole or any other way to get the full build command line to execute.

**Comment by dbaeumer** [comment]
This is captured by https://github.com/Microsoft/vscode/issues/15179 where we discuss future directions of the task runner system.

Closing as dup.
