### ISSUE TITLE
getting unix shell env is slow and blocking

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16508]
* start vscode insiders (not dev version) fresh
* show perf numbers
* 🐌 it takes ~650ms from loading `main.js` to crafting the URL to load
* 🐌 it takes another ~350ms until we begin loading `workbench.main.js`

![screen shot 2016-12-05 at 16 24 27](https://cloud.githubusercontent.com/assets/1794099/20890472/4eaeca2e-bb07-11e6-8af1-0be89a14f936.png)

**Comment by jrieken** [comment]
When profiling the `start => window.loadUrl()`-portion it shows no JS load whatsoever so I wonder if have some waterfall behaviour in there?

**Comment by jrieken** [comment]
related to #15455

**Comment by bpasero** [comment]
@jrieken are you using the v8 profiler module to profile the main side or is there some better way?

**Comment by jrieken** [comment]
Yes - I use my v8-profiler branch from here (https://github.com/jrieken/v8-profiler/commits/master). A typical profile looks like this: [start-1480949671095.cpuprofile.zip](https://github.com/Microsoft/vscode/files/631593/start-1480949671095.cpuprofile.zip)

**Comment by jrieken** [comment]
Fun fact is that in `scripts/code.sh` it takes roughly half the time compared to the built/productized variant. Maybe some https calls?

**Comment by bpasero** [comment]
@jrieken maybe try with using the exact same product.json from our distro to have the same config.

**Comment by jrieken** [comment]
I have tries with the one get from `gulp vscode-darwin-min`. No endpoints...

**Comment by bpasero** [comment]
@jrieken do you see the same when you open such a profile within VS Code, there are no times recorded:

![image](https://cloud.githubusercontent.com/assets/900690/20893779/45246322-bb13-11e6-998d-cf385475eff3.png)

Whereas when I open them in node-inspector UI, everything seems fine, including flame chart:

![image](https://cloud.githubusercontent.com/assets/900690/20893808/5da00e4c-bb13-11e6-942e-f7a8d92df3e4.png)

**Comment by jrieken** [comment]
So, apart from loading scripts I see lots of time being consumed by building the menus... I that mac specific? can we start loading the window in parallel?

**Comment by bpasero** [comment]
No, the menu is being created on all platforms and as far as I know there is no API for async menu creation. Which call specifically do you mean that takes long?

**Comment by bpasero** [comment]
What worries me more is this large program block that seems to stop the world:

![image](https://cloud.githubusercontent.com/assets/900690/20915722/d8cd6988-bb87-11e6-8bd0-c5e823872d0c.png)

I think I only see it when running a real build though, not when running out of sources.

**Comment by jrieken** [comment]
The 'stop the world' block is us getting [unix shell env](https://github.com/Microsoft/vscode/blob/master/src/vs/code/electron-main/main.ts#L430). On my machine, it takes ~250ms (that grey flatline above) and blocks/waterfalls every else.

**Comment by joaomoreno** [comment]
We can't spawn any processes (including renderers) before getting that shell env. The blocking is consistent with what we once saw in git: spawning a process actually blocks the world.

**Comment by jrieken** [comment]
I have measuring `spawn` to take 20 to 30ms, not 250

**Comment by jrieken** [comment]
The is coming from spawning another `shell`. It measures like this

```
jrieken:~/Code$ time /bin/bash -ilc 'node -p "JSON.stringify(process.env)"'
{...}

real	0m0.180s
user	0m0.107s
sys	0m0.078s
```

```
jrieken:~/Code$ time /bin/bash -ilc 'echo $PATH'
...

real	0m0.120s
user	0m0.062s
sys	0m0.063s
```

```
jrieken:~/Code$ time node -p "JSON.stringify(process.env)"
{...}

real	0m0.061s
user	0m0.045s
sys	0m0.016s
jrieken:~/Code$
```

**Comment by Tyriar** [comment]
Yes these are for default config values, the last of which is already being done asynchronously (to avoid a sync `fs` call) so I don't think there should be an issue waiting a little while. If there's some environment ready promise somewhere that we can depend on then this is just a matter of deferring the usages of the default shell until the env is ready.

My only concern here is that this could lead to some obscure bugs if future code references `process.env` before it's ready. Could we perhaps monkey patch `process.env` to throw an exception or something in case it's being used before it's ready?

@jrieken if you wanted to work on this before I get to it then I'd just make `TERMINAL_DEFAULT_SHELL_LINUX` and `TERMINAL_DEFAULT_SHELL_OSX` return `TPromise<string>` similar to `DEFAULT_TERMINAL_LINUX_READY` and adjust any references to account for that.

**Comment by jrieken** [comment]
@Microsoft/vscode This will be in the next insider build *including* a warning that complains about environment variables that are undefined while the user shell environment is still loaded. It should only be false positives, but in case something doesn't work (like a Task, debugger, or an extension) check you console for messages, like: `process.env['VSCODE_DEV'] is undefined AND 'process.lazyEnv' is NOT READY yet.`
