### ISSUE TITLE
Builtin GitHub extension is disabled in untrusted workspace 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165066]
The GitHub extension declares that it supports untrusted workspaces: https://insiders.vscode.dev/github/microsoft/vscode/blob/287d963f467d4c309e2e3fef804b49d567c92b93/extensions/github/package.json#L22-L26

However I see on desktop that it is disabled in an untrusted workspace: 
![image](https://user-images.githubusercontent.com/30305945/199070420-b4134ca5-02c5-4933-a46e-e8fb8e5c788f.png)

**Comment by sbatten** [comment]
hmm, i don't see that with a local untrusted folder, it is enabled for me. are there any other special properties about the workspace?

**Comment by joyceerhl** [comment]
Hmm, something fishy is happening here. Looks like the folder is trusted after all: 

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/30305945/199085591-6d12c6fe-52d0-4d4a-9861-7feedb1195fd.png">

**Comment by sbatten** [comment]
Do other parts of the UI (e.g. the extension viewlet) also reflect the extension as disabled due to workspace trust?

**Comment by joyceerhl** [comment]
I reloaded the page and now the extension is enabled after all, so it seems like some extension ui state got out of sync for this extension and incorrectly reported it disabled. 😕
