### ISSUE TITLE
It can not jump to the file by ctrl+click the file path in the output of tasks

### ISSUE THREAD

**Issue by sunhaoxi** [microsoft/vscode#165027]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2 (user setup)
- OS Version: Windows_NT x64 10.0.19041

It can not jump to the file by ctrl+click the file path in the output of tasks.  

Steps to Reproduce:
Duplicate with #159255. This ticket is closed and no one response, I have to open a new one.

**Comment by meganrogge** [comment]
pls provide a gif

**Comment by meganrogge** [comment]
reopened that one and will close this one
