### ISSUE TITLE
Remote SSH Terminal choppy

### ISSUE THREAD

**Issue by wojciechsi** [microsoft/vscode#165045]
Does this issue occur when all extensions are disabled?: Yes (expect from remote ssh client obviously)

- VS Code Version: 1.72.2
- OS Version: Ubuntu 22.04.1 LTS

Steps to Reproduce:

1. Connect to ssh remote host (Red Hat Enterprise Linux Server release 7.4 in my case)
2. Type in terminal eg. echo "Quick dog jumped over lazy dog" and push ENTER
3. Push UP arrow, to see the previous command
4. Push LEFT/RIGHT few times
5. Add some characters (where the cursor is)
6. Push ENTER

Effect: characters are inserted in different place than the cursor was, sliding with left/right arrow was lagging.

The issue on this remote doesn't appear when connecting via ssh directly from host terminal.

**Comment by Tyriar** [comment]
You can workaround this by disabling local echo in your settings

/duplicate https://github.com/microsoft/vscode/issues/126209

**Comment by wojciechsi** [comment]
Thanks for assistance; another solution I found today was switching to tmux instead of bash used on remote.
