### ISSUE TITLE
Wrong code colour

### ISSUE THREAD

**Issue by yasirroni** [microsoft/vscode#165030]
Type: <b>Bug</b>

Write this piece of code in .py or ipynb file,

```python
def foo(x):
    """foo
    """
    return (
        x
        * 42  # why wrong colour? treated as comment by syntax higlight
    )

def bar():
    """bar
    """
    return 42
```

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

**Comment by yasirroni** [comment]
Removing either:

```python
    """foo
    """
```

or 

```python
    """bar
    """
```

will resulted in right colour.

**Comment by yasirroni** [comment]
![image](https://user-images.githubusercontent.com/48709672/198925586-4801b04b-bd99-4d59-b432-d81ca8b2c509.png)
![image](https://user-images.githubusercontent.com/48709672/198925662-f49f2ec2-a5bf-43e1-9bac-34244abc5edc.png)

**Comment by babakks** [comment]
@yasirroni I can't repro this. Could you test it with other color themes?

This is what I get (also tested with other themes):
![python](https://user-images.githubusercontent.com/36728931/199011443-a567c502-9c83-43fc-a554-4287c87a753d.png)

**Comment by yasirroni** [comment]
It only happened in VSCode. Using JupyterLab or Jupyter Notebook, it is fine.
_
Can I know how to change highlighter theme or extension or library that it use? Maybe it could help me debug what happens on my side.

**Comment by babakks** [comment]
One way to make sure it's a problem with the tokenizer is to invoke the "Developer: Inspect Editor Tokens and Scopes" command (just press <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>P</kbd>, and find the command). This way you can inspect tokens and check if that portion of the code is interpreted as a comment.

This is what I get:

![python-2](https://user-images.githubusercontent.com/36728931/199021590-5638aee9-cfd3-43fe-b4f2-288cba9a5e25.png)

**Comment by alexr00** [comment]
@yasirroni I also can't reproduce this issue. Can you try disabling all extensions and seeing if it still happens?

**Comment by yasirroni** [comment]
I'm overwhelmed with task currently since last week. I will come back to debug this after I got times. Sorry guys, and thank you.

**Comment by yasirroni** [comment]
> One way to make sure it's a problem with the tokenizer is to invoke the "Developer: Inspect Editor Tokens and Scopes" command (just press Ctrl Shift P, and find the command). This way you can inspect tokens and check if that portion of the code is interpreted as a comment.
> 
> This is what I get:
> 
> ![python-2](https://user-images.githubusercontent.com/36728931/199021590-5638aee9-cfd3-43fe-b4f2-288cba9a5e25.png)

![image](https://user-images.githubusercontent.com/48709672/200183181-da9808ac-da3e-4521-ad10-2a9d33e41f93.png)
![image](https://user-images.githubusercontent.com/48709672/200183296-db80fde9-3b8d-4b44-ac32-c7e7653798f1.png)
![image](https://user-images.githubusercontent.com/48709672/200183301-a3d7a158-d95a-451a-abb1-d2eee443f6bf.png)
![image](https://user-images.githubusercontent.com/48709672/200183358-1c7c8736-5ce6-4546-88d8-6cd800b6836a.png)

After docstring deletion
![image](https://user-images.githubusercontent.com/48709672/200183372-56c4fa57-7908-493f-b48b-49fece8c7964.png)
![image](https://user-images.githubusercontent.com/48709672/200183384-d94e9d88-2105-4d36-8d12-7d7b76fb5aa4.png)

**Comment by yasirroni** [comment]
I think nothing wrong in `Developer: Inspect Editor Tokens and Scopes`.

**Comment by yasirroni** [comment]
Disable all extensions fix the issue.

![image](https://user-images.githubusercontent.com/48709672/200183555-d2c8fc15-49f3-4c13-b4bb-64de2e9ce779.png)

Let's find who cause this mess....

**Comment by yasirroni** [comment]
Found the cause, "Better Comments" `aaron-bond.better-comments` Version `3.0.2`.

![image](https://user-images.githubusercontent.com/48709672/200183819-edc10dfb-5fe7-4745-995d-e857c0dee0d9.png)
![image](https://user-images.githubusercontent.com/48709672/200183832-f3636c62-3b17-4c95-915d-bdbfc3d256c4.png)

It thinks that it is inside docstring when it is not.

Thank you,

**Comment by yasirroni** [comment]
Submitted to the dev https://github.com/aaron-bond/better-comments/issues/445
