### ISSUE TITLE
Detect Language Mode from Modeline Comment

### ISSUE THREAD

**Issue by bloudraak** [Microsoft/vscode#1651]
I use Vagrant a bit. The file `Vagrantfile` is extensionless and as a result is shown as plain text.  The file is actually a ruby script.  You can see it in the comments; something vim and vi support.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

end 
```

It would be extremely useful if VisualStudio Code could honor those settings and display the file in the correct language mode. It would even be better if other settings, like tab length etc could be honored. I'm assuming the latter will overwrite the workspace and user settings. 

Modeline magic
http://vim.wikia.com/wiki/Modeline_magic

**Comment by ctlajoie** [comment]
I am writing a modelines plugin that will support vim/emacs modelines as well as a Code-specific syntax. It's working fine for tabs/spaces and tab width settings, but I don't believe there is a way to set the language yet through the (documented) API. Can anyone more familiar with it than I am confirm whether this is the case?

If it's not possible then I guess I will have to release the plugin without this functionality and add it when there is an API for it.

**Comment by ctlajoie** [comment]
The extension is published, if anyone is interested.
https://marketplace.visualstudio.com/items/chrislajoie.vscode-modelines

**Comment by bbenoist** [comment]
@bloudraak You might also be interested in my new [Vagrant extension](https://marketplace.visualstudio.com/items?itemName=bbenoist.vagrant) :wink: :

**Comment by lloeki** [comment]
This would be awesome to have. I regularly have ext-less files around in various projects of mine or other that get `source`/`require`/`load`ed and there's nothing more accurate and efficient than a modeline to have some things set up correctly.

**Comment by ev0rtex** [comment]
I have many files that I need to be able to set the filetype/language/whatever based on a modeline. I have done this in SublimeText for years using an extension that enables it. From reading here it seems that what's needed is for the plugin API to support setting the language mode and then this functionality could be properly implemented.

**Comment by lloeki** [comment]
> not within the scope of the core product, but *could be addressed by an extension*.

True, but only insofar as #1800 is ever going to be resolved.
