### ISSUE TITLE
Test Runner Uses Different Paths

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#165144]
I get this when running all tests:
![image](https://user-images.githubusercontent.com/2931520/199216213-663f1495-57b2-4da1-ad6c-49b4123be0e4.png)

However, when I just run this particular test, I get this:
![image](https://user-images.githubusercontent.com/2931520/199216304-dbded048-229e-4e2e-9bc0-6ccd82149739.png)

These are different paths :(

**Comment by connor4312** [comment]
I don't reproduce this. I tried running the existing `zip.test.ts` which uses fixtures, and in all cases the path looked correct:

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/2230985/206293135-e4738ac8-5b29-4a7f-96f6-e061343c313b.png">

Can you confirm whether you still see this, and if so, are there steps to reproduce it?

**Comment by hediet** [comment]
I can still reproduce this on windows:

image.png
![image](https://user-images.githubusercontent.com/2931520/206466362-54264c27-68c0-4f5a-a4a4-3d5fab14209c.png)


Run the test `extract should handle directories` in the vscode code base.

**Comment by connor4312** [comment]
Gave it a shot on windows, and I still don't reproduce. But I also noticed we have a new function as of 05625e39e1b5b3f3a608a03ade633ed58ea9d80b. Does this still happen for you? If so, debugging into `asFileUri` would be helpful.
