### ISSUE TITLE
git checkout doesn't create track on remote branch.

### ISSUE THREAD

**Issue by blopez2010** [Microsoft/vscode#16518]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.3.8|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-jasmine-es5|deerawan|1.0.1|
|githistory|donjayamanne|0.1.2|
|gitlens|eamodio|1.3.0|
|vscode-util|guosong|1.0.5|
|rest-client|humao|0.11.0|
|Angular2|johnpapa|1.0.2|
|vscode-todo-parser|minhthai|1.8.3|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|java|redhat|0.0.7|
|vscode-icons|robertohuertasm|4.0.5|
|guides|spywhere|0.5.1|
|code-spell-checker|streetsidesoftware|0.12.2|
|lodash-snippets|tomphilbin|0.7.0|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|join-lines|wmaurer|0.2.0|
|JavaScriptSnippets|xabikos|1.2.0|
|local-history|xyz|1.1.0|

---

Steps to Reproduce:

1. git checkout branch
2. git commit "comments".
3. git push.

When pushing the branch, it ask what is the remote to track. it should be done automatically when created the branch for first time.

**Comment by joaomoreno** [comment]
Did you create the branch in the command line or in Code?

This is standard git behaviour: not to assume things like this automatically.

**Comment by blopez2010** [comment]
I understand actually, thanks @joaomoreno
