### ISSUE TITLE
border tooltips

### ISSUE THREAD

**Issue by Manix80** [microsoft/vscode#165146]
Hello, how to remove the white outline of the tooltip please?

![1667301078](https://user-images.githubusercontent.com/78910839/199221721-82b6280e-417c-4953-a879-1656edbbc256.png)

a bit like this :

![1667301026](https://user-images.githubusercontent.com/78910839/199221839-6fa7d10d-c00e-41f5-bb89-8c24903b2e74.png)

thanks

**Comment by roblourens** [comment]
What OS is this?

**Comment by Manix80** [comment]
> What OS is this?

Archlinux, Nord theme

**Comment by Manix80** [comment]
problem solved by adding this to picom.conf :

```
rounded-corners-exclude = [
    "window_type = 'tooltip'", 
];
```
but there is no way to change the colors or borders via the settings.json?
impossible to have the ownership of these tooltips with xprop ...

**Comment by deepak1556** [comment]
These are native tooltips delegated to the runtime for rendering, VSCode cannot control its behavior. Closing since there is a workaround.
