### ISSUE TITLE
VSCode-tslint: tslint 4.0 support

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#16519]
Complexity: 2

- [x] any OS @weinand 

vscode-tslint now supports tslint > 4.0 (see the tslint 4.0 [blog](https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html). 

## Setup
Install the latest vscode-tslint (version 0.7.1). Notice that tslint has a peer dependency on TypeScript and either install tslint and typescript both globally or locally.

## Test
- test that vscode-tslint still works with tslint versions < 4, e.g., 3.17.
- test that the quick fixes that come with tslint 4.0 are properly applied (see the blog for available quick fixes).
- for a set of tslint rules vscode-tslint provides quick fixes independent of tslint:  `comment-format`, 
`triple-equals`, `whitespace`, `quotemark`. Check that this fixes work when using tslint 4.0 or tslint < 4.0.
- for all warnings there is a special quick fix to disable the rule for the next line.
- test the bulk quick fixes showing in the light bulb, to fix all warnings of the same type and all autofixable problems.

A set of manual tests for the quick fixes can be found here: https://github.com/Microsoft/vscode-tslint/tree/master/tslint-tests.

**Comment by weinand** [comment]
@egamma since I couldn't find tslint 3.17, I've tested vscode-tslint with tslint 3.15.1

**Comment by ramya-rao-a** [comment]
Closing as the assigned testers are done testing
