### ISSUE TITLE
CodeWindow: renderer process gone (reason: killed, code: 9)

### ISSUE THREAD

**Issue by myview-lin** [microsoft/vscode#165127]
Just upgraded to macos 12.3, try to ENABLE System Integrity Protection if you have disabled it before: https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection

_Originally posted by @mindesik in https://github.com/microsoft/vscode/issues/145033#issuecomment-1067443824_

**Comment by myview-lin** [comment]
[1101/151906.704790:ERROR:directory_reader_posix.cc(42)] opendir /Users/xxx/Library/Application Support/Code/Crashpad/attachments/739f9d8b-107c-4a3e-8990-9fb6dc4fdb14: No such file or directory (2)
objc[2187]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffa4f13a8f0) and /Applications/Visual Studio Code.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x115684ce0). One of the two will be used. Which one is undefined.
[1101/151907.011731:WARNING:exception_types.cc(171)] EXC_CRASH should not contain exception 12
[1101/151907.180606:WARNING:exception_snapshot_mac.cc(70)] exception EXC_GUARD invalid in EXC_CRASH
[main 2022-11-01T07:19:07.195Z] CodeWindow: renderer process gone (reason: killed, code: 9)

**Comment by myview-lin** [comment]
Local OS Version: macOS 13.0 (22A380)

**Comment by deepak1556** [comment]
If the issue persists with latest stable `1.74`, can you provide the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

**Comment by myview-lin** [comment]
[completed.zip](https://github.com/microsoft/vscode/files/10206535/completed.zip)
[vscode.log](https://github.com/microsoft/vscode/files/10206537/vscode.log)

**Comment by myview-lin** [comment]
my version is 1.74

**Comment by deepak1556** [comment]
In your case, is SIP enabled or disabled ? Does it crash when you run with `--no-sandbox --disable-gpu-sandbox` ?

**Comment by myview-lin** [comment]
[vscode-log.log](https://github.com/microsoft/vscode/files/10256658/vscode-log.log)
![企业微信截图_20221219150648](https://user-images.githubusercontent.com/68991242/208367554-110c68d6-6816-4331-9bc0-9ce1561ee39f.png)
The same mistake. Are you running normally on the latest Mac 13 system

**Comment by sRaH** [comment]
I think is not specifically a vscode problem.
Im getting this for every Chromium <108 based electron app like: Logitech G-Hub

I replaced the VSCode.app/Frameworks with the latest Electron.app/Frameworks it working since but please don't do that it requires SIP disabled and this is not a solution not even a workaround.

![screenshot](https://user-images.githubusercontent.com/3193012/209587632-f4a89f58-c10f-47bf-baa9-5975abbef15d.png)

**Comment by dsbferris** [comment]
> I think is not specifically a vscode problem. Im getting this for every Chromium <108 based electron app like: Logitech G-Hub
> 
> I replaced the VSCode.app/Frameworks with the latest Electron.app/Frameworks it working since but please don't do that it requires SIP disabled and this is not a solution not even a workaround.
> 
> ![screenshot](https://user-images.githubusercontent.com/3193012/209587632-f4a89f58-c10f-47bf-baa9-5975abbef15d.png)

This "not even a workaround" works here as well. Thank you for sharing!
SIP was reduced beforehand due to OCLP, so I don't know about it. But definitely not recommended reducing/disabling it!

For anyone curios: [electron-v21.3.3-darwin-x64.zip](https://github.com/electron/electron/releases/download/v21.3.3/electron-v21.3.3-darwin-x64.zip)

**Comment by sRaH** [comment]
> > I think is not specifically a vscode problem. Im getting this for every Chromium <108 based electron app like: Logitech G-Hub
> > I replaced the VSCode.app/Frameworks with the latest Electron.app/Frameworks it working since but please don't do that it requires SIP disabled and this is not a solution not even a workaround.
> > ![screenshot](https://user-images.githubusercontent.com/3193012/209587632-f4a89f58-c10f-47bf-baa9-5975abbef15d.png)
> 
> This "not even a workaround" works here as well. Thank you for sharing! SIP was reduced beforehand due to OCLP, so I don't know about it. But definitely not recommended reducing/disabling it!
> 
> For anyone curios: [electron-v21.3.3-darwin-x64.zip](https://github.com/electron/electron/releases/download/v21.3.3/electron-v21.3.3-darwin-x64.zip)

If you are using OCLP with reduced SIP you just need to add ipc_control_port_options=0 to the nvram boot-args.

**Comment by deepak1556** [comment]
Upstream issue https://bugs.chromium.org/p/chromium/issues/detail?id=1291789

**Comment by myview-lin** [comment]
sudo nvram boot-args="-v cs_enforcement_disable=1 amfi_get_out_of_my_way=1 keepsyms=1 intcoproc_unrestricted=1 amfi_unrestrict_task_for_pid=1 amfi_allow_any_signature=1 cs_debug=1 ipc_control_port_options=0"
exec this command,program is ok

**Comment by connor4312** [comment]
@deepak1556 are there steps for this?

**Comment by deepak1556** [comment]
@connor4312 this requires booting macOS with custom arguments specifically SIP and AMFI disabled, better for authors to verify this issue.

@myview-lin can you help verify if this issue is addressed with our latest insiders https://code.visualstudio.com/insiders without having to add `ipc_control_port_options=0` to the boot args, thanks!

**Comment by janartist** [comment]
Are there any conclusions? I also have this problem

```
[0201/120310.232791:WARNING:exception_types.cc(171)] EXC_CRASH should not contain exception 12
Renderer process killed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
[0201/120310.366628:WARNING:exception_snapshot_mac.cc(70)] exception EXC_GUARD invalid in EXC_CRASH
[main 2023-02-01T04:03:10.377Z] CodeWindow: renderer process gone (reason: killed, code: 9)

```

**Comment by deepak1556** [comment]
@janartist this will be fixed in our next stable release `1.75`

**Comment by TxusBlack** [comment]
Today it keeps failing.

![image](https://user-images.githubusercontent.com/13071556/223017799-c17319dc-c5b8-4cdb-b37d-29ea19913610.png)

**Comment by deepak1556** [comment]
@TxusBlack please create a new issue with crash dumps based on the steps here https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!
