### ISSUE TITLE
vscode.openFolder does not pop up trusted workspace popup

### ISSUE THREAD

**Issue by ThadHouse** [microsoft/vscode#165121]
We have an extension that can create projects, and then calls vscode.openFolder to open the newly created project folder. In 1.66.2, this properly worked, and the Trusted Workspace popup popped up immediately. However, in 1.67 and later, the popup no longer occurs unless certain elements in the UI are clicked, or the UI is switched away from and switched back to.  This is a regression that is slightly jarring for our users, because some elements of our extension show up, but just don't work, until the user finds one of the ways to get the popup to occur.

Does this issue occur when all extensions are disabled?: An extension is required to trigger it

- VS Code Version: 1.72.2
- OS Version: Windows 11 (But reproduces on all platforms) 

Steps to Reproduce:

1. Call `vscode.commands.executeCommand('vscode.openFolder', toFolder, false);` from an extension to open a folder other then the current folder.
2. Trusted workspace popup should pop up immediately, however it does not.

**Comment by sbatten** [comment]
@ThadHouse, I do not reproduce this issue. I've created a simple extension to do the steps you outlined but am not seeing the same behavior. Can you verify if the folder path has already been trusted the trust editor via the command `Manage Workspace Trust`

**Comment by sbatten** [comment]
Alternatively, if it is opening in restricted mode, I wonder if you are repeatedly reproducing with the same folder. Since we want to minimize the noisiness of the prompt, we cache that we have already asked for a given folder path and don't prompt again.

**Comment by ThadHouse** [comment]
@sbatten I am using different folders each time to reproduce, and the bug was seen by all of our users. It definitely was not the case of a folder already being trusted. And if we close the window, and reopen it, the pop up occurs. It’s just when opened the first time from that command. 

I removed the functionality from our extension. I’ll make a custom version that adds it back in, and has an easier repro (our extension has a few steps needed to create an open a new folder)
