### ISSUE TITLE
Debt - use CSS variables over `registerThemingParticipant`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#165169]
When running VS Code (or the Monaco editor) all theme colors are exposed as CSS variables. That means components don’t need to use JavaScript to read and set colors but can simply rely on CSS. When a theme changes, the variable values automatically update. Also, with CSS variables you have less code and everything in one place.

The (long) list below is all users of [`registerThemingParticipant`](https://github.com/microsoft/vscode/blob/3a8b7e427699ecc1c411e7874cdef7f32cb8acba/src/vs/platform/theme/common/themeService.ts#L236). Those that only set/update colors are candidates for adopting CSS variables  The names of the CSS variables can be "derived" with the following logic

1. prefix `--vscode-`
2. take the theme color id and replace dots with slashes

For instance the color id `editorSuggestWidget.background`  is exposed as CSS variables `--vscode-editorSuggestWidget-background`. Find a sample adoption in this commit: https://github.com/microsoft/vscode/pull/165164/commits/3a787a80351fda9d76e7b25d1feec26a8e39685f. 

---

- [ ] `src/vs/editor/contrib/find/browser/findWidget.ts` @rebornix 
- [ ] `src/vs/workbench/browser/parts/activitybar/activitybarActions.ts`
- [x] `src/vs/workbench/browser/parts/editor/tabsTitleControl.ts` @bpasero 
- [x] `src/vs/workbench/contrib/codeEditor/browser/find/simpleFindWidget.ts` @Tyriar 
- [ ] `src/vs/workbench/contrib/codeEditor/browser/suggestEnabledInput/suggestEnabledInput.ts`
- [ ] `src/vs/workbench/contrib/codeEditor/browser/untitledTextEditorHint.ts`
- [ ] `src/vs/workbench/contrib/customEditor/browser/customEditors.ts`
- [ ] `src/vs/workbench/contrib/debug/browser/breakpointEditorContribution.ts` @roblourens 
- [ ] `src/vs/workbench/contrib/debug/browser/callStackEditorContribution.ts` @roblourens 
- [ ] `src/vs/workbench/contrib/debug/browser/debugColors.ts` @roblourens 
- [ ] `src/vs/workbench/contrib/extensions/browser/extensionsActions.ts` @sandy081 
- [ ] `src/vs/workbench/contrib/extensions/browser/extensionsList.ts` @sandy081 
- [ ] `src/vs/workbench/contrib/extensions/browser/extensionsViewer.ts` @sandy081 
- [ ] `src/vs/workbench/contrib/extensions/browser/extensionsWidgets.ts` @sandy081 
- [ ] `src/vs/workbench/contrib/interactive/browser/interactive.contribution.ts` @rebornix 
- [ ] `src/vs/workbench/contrib/output/browser/outputView.ts` @sandy081 
- [x] `src/vs/workbench/contrib/search/browser/searchView.ts` @andreamah 
- [x] `src/vs/workbench/contrib/searchEditor/browser/searchEditor.ts` @andreamah 
- [x] `src/vs/workbench/contrib/terminal/browser/terminalInstance.ts` @Tyriar 
- [x] `src/vs/workbench/contrib/terminal/browser/terminalView.ts` @Tyriar 
- [x] `src/vs/workbench/contrib/terminal/browser/widgets/terminalHoverWidget.ts` @Tyriar 
- [x] `src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts` @Tyriar 
- [x] `src/vs/workbench/contrib/terminal/browser/xterm/markNavigationAddon.ts` @Tyriar 
- [x] `src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts` @Tyriar 
- [x] `src/vs/workbench/contrib/welcomeOverlay/browser/welcomeOverlay.ts` @bhavyaus
- [x] `src/vs/workbench/contrib/welcomeWalkthrough/browser/walkThroughPart.ts` @bhavyaus

**Comment by mettij** [comment]
Hi, is this issue still up for grabs? I would like to be assigned to one of the bullets.

**Comment by lramos15** [comment]
> Hi, is this issue still up for grabs? I would like to be assigned to one of the bullets.

Yep! Just feel free to grab whichever one you want and open a PR for it :)

**Comment by dmartzol** [comment]
Hi! I would like to grab `src/vs/editor/contrib/links/browser/links.ts`

**Comment by dmartzol** [comment]
Hi @weartist. How did you marked your PR in every line of the description in this issue? I am not able to edit the description and I opened a PR for `src/vs/editor/contrib/links/browser/links.ts` 12 hours ago

**Comment by weartist** [comment]
> Moves css rules from links.ts to links.css #166258

Maybe I mentioned this issue in the pr? I have indeed modified this file a few days ago. You can look at the pr above. There are still many files that have not been adapted.

**Comment by weartist** [comment]
> Hi @weartist. How did you linked your PR in every line of the description in this issue? I am not able to edit the description and I opened a PR for `src/vs/editor/contrib/links/browser/links.ts` 12 hours ago. I guess @aeschli edited the description to add your PR but not mine?

Maybe I mentioned this issue in the pr?

**Comment by dmartzol** [comment]
> Maybe I mentioned this issue in the pr?

Yes, I was just wondering if there was an automated way of doing this, but I dont think so. Thank you!

**Comment by Tyriar** [comment]
Terminal is done, the following are intentional exceptions:

- decorationAddon.ts: We need to pull the color into TS to pass to xterm.js as it uses it in canvas calls.
- terminalHoverWidget.ts: We need to apply 0.5 opacity to the resolved color for the background, using `opacity: 0.5` won't work as it will fade the text.

**Comment by alexr00** [comment]
Tunnel view, comments, and tree view are done.

**Comment by bpasero** [comment]
@jrieken @aeschli what is the recommendation when more than the color is part of a `registerThemingParticipant`? To give an example:

https://github.com/microsoft/vscode/blob/d1f42f4857c638aa1580f0ea6d0855618f7d47ad/src/vs/workbench/browser/parts/activitybar/activitybarActions.ts#L555-L567

Here, we conditionally make an element `visibility: hidden` if we have a `ACTIVITY_BAR_ACTIVE_FOCUS_BORDER`. We cannot just blindly move that over to CSS because we then lose the check for the color.

**Comment by aeschli** [comment]
@bpasero I don't know. Has to stay in code....

**Comment by bpasero** [comment]
@aeschli can I listen to a change for a color key via theme service to conditionally toggle a class based on a color being defined or not?

**Comment by aeschli** [comment]
Yes, `IThemeService,onDidColorThemeChange` and `IColorTheme.getColor`

**Comment by connor4312** [comment]
If anyone is still working on this, you can get completions with this handy extension 🙂  https://marketplace.visualstudio.com/items?itemName=connor4312.css-theme-completions

**Comment by sandy081** [comment]
@jrieken @aeschli What is the recommendation if I have to hard code a codicon css, for eg., I am deriving the codicon class programatically as follows

```ts
const extensionRatingIcon = theme.getColor(extensionRatingIconColor);
	if (extensionRatingIcon) {
		collector.addRule(`.monaco-hover.extension-hover .markdown-hover .hover-contents ${ThemeIcon.asCSSSelector(starFullIcon)} { color: ${extensionRatingIcon}; }`);
	}
```

If I have to move this to CSS then I have to hardcode the codicon class as follows

```css
.extension-ratings .codicon-extensions-star-half {
	color: var(--vscode-extensionIcon-starForeground);
}
```

Is it ok to hardcode codicons like this?

**Comment by aeschli** [comment]
@sandy081 Looking at where verifiedPublisherThemeIcon is used, it's always in a dom node that also has the class `publisher-verified`. Better avoid the codicon class name, but use `publisher-verified` 
https://github.com/microsoft/vscode/blob/dd93163b73418600c48ede98aa78b072e7a0cde4/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L99
https://github.com/microsoft/vscode/blob/dd93163b73418600c48ede98aa78b072e7a0cde4/src/vs/workbench/contrib/extensions/browser/extensionsList.ts#L99

**Comment by bpasero** [comment]
Interesting issue where a migration to CSS variable caused a bug (https://github.com/microsoft/vscode/issues/169662). It looks like some visual behaviour is defined by the OS/runtime and not by default user agent CSS. So if your CSS variable ends up as `null/undefined`, you get some default (`tansparent`?) and the result is that the OS styling is disabled.

Relevant SO for my case: https://stackoverflow.com/questions/56798646/css-selection-with-var-fallback

**Comment by Tyriar** [comment]
I looked over mine again and they are all there still intentionally:

https://github.com/microsoft/vscode/blob/bceaaf84a27c3a95a0cdfc79287e3215b56b951c/src/vs/workbench/contrib/terminal/browser/widgets/terminalHoverWidget.ts#L135-L143

I don't think we can get the same effect of `.transparent(0.5)` in CSS using the variable.

https://github.com/microsoft/vscode/blob/bceaaf84a27c3a95a0cdfc79287e3215b56b951c/src/vs/workbench/services/hover/browser/hoverService.ts#L179-L186

Same as above.

https://github.com/microsoft/vscode/blob/bceaaf84a27c3a95a0cdfc79287e3215b56b951c/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L479-L486

This is needed as the color is handed off to xterm.js.

**Comment by jrieken** [comment]
@Tyriar please check those occurrences anyways so that we can remove them from the todo list

**Comment by andreamah** [comment]
For `searchEditor.ts`, I couldn't find references to `registerThemingParticipant`. 

For `searchView.ts`, we use the RGB values from the foreground var and we use a custom alpha. Since this only applies to the text, I don't think that there's a CSS-only equivalent. We could create a new var for this or just leave this as is; I'm not sure what's best in this case.

https://github.com/microsoft/vscode/blob/b58d49dd7ed9752af1f430da32042f62ae46b44b/src/vs/workbench/contrib/search/browser/searchView.ts#L2037-L2045

**Comment by Tyriar** [comment]
@andreamah you're setting `color` there so you can probably use a plain `opacity: 0.65` style, unless the element also has a background color as that would also apply there.

**Comment by andreamah** [comment]
> @andreamah you're setting `color` there so you can probably use a plain `opacity: 0.65` style, unless the element also has a background color as that would also apply there.

The element also has links, which have a normal alpha, so then the link opacity is affected.

**Comment by Tyriar** [comment]
@andreamah you could have another rule with higher specificity that re-applies the link color?

**Comment by aeschli** [comment]
@Tyriar For https://github.com/microsoft/vscode/blob/bceaaf84a27c3a95a0cdfc79287e3215b56b951c/src/vs/workbench/contrib/terminal/browser/widgets/terminalHoverWidget.ts#L135-L143
you could define a new (terminal hover specific) color. The default value of the color can express that it is a function of `editorHoverHighlightColor`

https://github.com/microsoft/vscode/blob/bceaaf84a27c3a95a0cdfc79287e3215b56b951c/src/vs/workbench/contrib/terminal/browser/xterm/decorationAddon.ts#L479-L486
To access a color value use `IThemeService.getColorTheme().getColor(...)`

**Comment by bpasero** [comment]
As discussed in standup, tabs have quite an involved CSS ruling that involves not only colors but also other properties. I would like to keep it this way via `registerThemingParticipant` and not invent various class names to get a similar effect to make maintenance easier there.

**Comment by jrieken** [comment]
Closing this as I believe we are done here
