### ISSUE TITLE
Terminal: “Follow link” popup on URLs — set delay before opening?

### ISSUE THREAD

**Issue by hughlilly** [microsoft/vscode#165122]
In the Terminal when a link is displayed, you can hover over it, and after a few seconds a popup like this appears:
![image](https://user-images.githubusercontent.com/12046008/199166566-17cda6e9-5a3c-445f-9a17-3c2225adef08.png)

This appears to be determined by these lines:
https://github.com/microsoft/vscode/blob/b08633e2df1dab2393b9b09921f1605adfea9dd5/src/vs/workbench/contrib/terminal/browser/links/terminalLinkManager.ts#L346-L351

Is it possible to adjust the delay? I’d like to set it to `0` so that hovering over a link immediately generates the popup.

**Comment by Tyriar** [comment]
If the delay was 0 it would be incredibly annoying though as moving the mouse to text above it could obscure it. Since this would be a obscure setting that would rarely be used I don't think we should do this to avoid bloat.
