### ISSUE TITLE
[folding] Support Shift+Click on folding marker to recursively unfold

### ISSUE THREAD

**Issue by EthanMelamed** [Microsoft/vscode#16517]
Please add the ability to recursively expand code blocks by clicking on the expand icon. Perhaps a shift+click would be an intuitive event to trigger this.

**Comment by EthanMelamed** [comment]
I have been using the [command] + [k], [command] + [0] command to collapse my code. When you do this all of the code in the file is recursively collapsed. Being able to recursively expand would save me a lot of time clicking the expand button!

**Comment by aeschli** [comment]
There already us 'Unfold recursively (Ctrl+k Ctrl + ])'. Is that what you meant?

**Comment by EthanMelamed** [comment]
Yes this is what I mean! Except that you must have your cursor in the code block already for it to work. I was hoping for this same effect to happen when you click the '+' or 'unfold/expand' icon on the line when accompanied by some keypress

**Comment by aeschli** [comment]
I updated the title. I picked 'shift' as modifier key, feel free to change it with the key of your choice

**Comment by EthanMelamed** [comment]
Hello! Is there anyway we can bump this?
Thank you!

**Comment by aeschli** [comment]
We'd need more requests ('thumbs ups') from others for the feature. I'm also happy to accept a pull request.

**Comment by EthanMelamed** [comment]
Ok that's fair thanks for the quick reply

**Comment by AdenFlorian** [comment]
I'm interested in implementing this, however I would prefer to use middle mouse click (like jetbrains IDEs), and for it to also allow recursively folding. @EthanMelamed @aeschli Would y'all be ok with this?

**Comment by EthanMelamed** [comment]
Hey thanks for doing that and sorry for the late reply, middle mouse click is nice but it doesn't help trackpad users, would it be hard to implement something for trackpad users like myself?

**Comment by aeschli** [comment]
@AdenFlorian  Yes, sounds great, thanks!

I added 'shift + click' also works to recursively fold/unfold.

**Comment by EthanMelamed** [comment]
@aeschli 'shift + click' sounds awesome! I looked at the merge pr but didnt see anything about it though. Is there another pr that has it?

**Comment by AdenFlorian** [comment]
@EthanMelamed It's in this commit: 12c6aaa

**Comment by EthanMelamed** [comment]
Great thanks for linking it!
