### ISSUE TITLE
LICENSE-ANYTHINGINCAPITALS treated as Markdown

### ISSUE THREAD

**Issue by peter-kehl** [microsoft/vscode#165116]
Replicable in current Insiders (currents as shipped by Manjaro Linux):
- Version: 1.69.0-insider
- Commit: 92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9
- Date: 2022-07-06T23:34:34.229Z
- Electron: 18.3.5
- Chromium: 100.0.4896.160
- Node.js: 16.13.2
- V8: 10.0.139.17-electron.0
- OS: Linux x64 5.19.16-2-MANJARO

Does this issue occur when all extensions are disabled?:
- N/A: The only way of testing that I know about is with "markdownlint" extension.

Steps to Reproduce:

1. Open any file with a name starting with `LICENSE-` and with capitals after the hyphen, like `LICENSE-MIT`
2. The file is treated as Markdown (it activates/applies a Markdown-specific extension, see https://github.com/DavidAnson/vscode-markdownlint/issues/257). He's a VS Code extension/API expert (much more than me), so I find him credible.

On the contrary
1. Open `LICENSE`
2. The file is not treated as Markdown (it doesn't activate/apply "markdownlint").

**Comment by mjbvz** [comment]
I do not see this in my testing:

![Uploading Screen Shot 2022-11-01 at 12.55.28 AM.png…]()

Notice how the file mode is plain text

I suspect this is either coming from some extension or you've configured the `files.associations` setting so that  `LICENSE*` files are treated as markdown

**Comment by peter-kehl** [comment]
Thank you Matt @mjbvz for showing me the file type/mode in the status bar (I usually have the status bar hidden).

To help your or others reproduce this, or to narrow it down:
- the same Insiders version as I used above
- no workspace open (only opened `LICENSE-MIT` as a file) - still treated as Markdown:
![image](https://user-images.githubusercontent.com/4270240/199303350-6050c1be-5a4f-445c-9f65-c5b69effbd2f.png)
- all extensions disabled (including the one I mentioned above), and `files.associations` shows nothing:
![image](https://user-images.githubusercontent.com/4270240/199304007-1216dcc7-4059-4158-9826-ff910f966ea9.png)
```
~/.config/Code - Insiders
grep -r files.associations .
grep: ./User/workspaceStorage/1665008696241/state.vscdb: binary file matches
grep: ./CachedData/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/chrome/js/31ee7cfab97a2fcb_0: binary file matches
grep: ./CachedData/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/main-e68719928f5a888e10af886be9e8e0c8.code: binary file matches
grep: ./CachedData/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/extensionHostProcess-7ef49542c15227bc893f7f32694b5a00.code: binary file matches
grep: ./CachedData/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/watcherMain-cc39914cfb5f441917c826245a3e721f.code: binary file matches
grep: ./CachedData/92d25e35d9bf1a6b16f7d0758f25d48ace11e5b9/ptyHostMain-30f3fcc592e9f3632fbc25575c634759.code: binary file matches
```

Please suggest steps for me, or re-open & investigate/delegate.

**Comment by mjbvz** [comment]
What about the `files.defaultLanguage` setting?

**Comment by peter-kehl** [comment]
No value seems to show up for `files.defaultLanguage` - I don't even see any input box/checkbox/dropdown list for this setting:
![image](https://user-images.githubusercontent.com/4270240/199307315-bba7ba2d-a9b6-4e3f-8d30-cc4bd2733af5.png)

That Markdown detection somehow depends on the file name being in CAPITAL-CASE. `lowercase-named-file` shows up as `Plain Text`:
![image](https://user-images.githubusercontent.com/4270240/199307680-1ccbf2e5-942d-4191-be2d-1edf7895ee25.png)

If there is any more efficient way to get my settings to you (or to anyone else), I'm happy to ZIP up whatever needed. (I'm on Manjaro Linux, have 3 VS Code installations: Insiders, (stable) VS Code and `Code - OSS`.)

**Comment by peter-kehl** [comment]
The problem shows up only if the filename starts with `LICENSE-` (in CAPS). A different prefix - even if in CAPS - makes it `Plain Text`:
![image](https://user-images.githubusercontent.com/4270240/199353031-62ebcd6a-1a0e-4220-8475-58b2865d4466.png)

**Comment by mjbvz** [comment]
This happens on no machines I've tested. You can send me your settings but tbh this isn't a priority issue
