### ISSUE TITLE
Issue with files.autoSave set to onFocusChange

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#16510]
- VSCode Version:

Version 1.8.0-insider
Commit c032f0e2bc602eb9388221876911913e5a808aec
Date 2016-12-05T07:04:32.572Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version: Ubuntu 14.04

Steps to Reproduce:

1. Set "files.autoSave": "onFocusChange" in settings.json
2. Change the file content & press ctrl+s, you will see the following message continuously (really fast, sometime you might not see because the editor goes crazy & tries to show the message in a loop as showing the message itself triggers focus change) & the file does not get saved.

Screenshot attached.
![issue with vscode](https://cloud.githubusercontent.com/assets/452518/20890655/a1a74b18-bb2d-11e6-885c-19e39f9e87bd.png)

**Comment by thekalinga** [comment]
Also,

Save should be triggered only if the file has changed, current observed behaviour, atleast in this scenario seems to be blind flush. Else, I would not be seeing the top info window showing & disappearing within millis continuously.

**Comment by bpasero** [comment]
@thekalinga 
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by thekalinga** [comment]
You are right. One of the extension is misbehaving, not sure which one..

Need to identify after disabling one after the other :(

Any help w.r.t which type of extension can cause this issue is appreciated

**Comment by thekalinga** [comment]
Found the issue.

Its with the plugin I am using.

https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter

**Comment by thekalinga** [comment]
Thanks..
