### ISSUE TITLE
Delay debugger 'disconnect' terminating the debugger and debuggee 

### ISSUE THREAD

**Issue by gaelwilson** [microsoft/vscode#165138]
Type: <b>Feature Request</b>

The Micro Focus COBOL extension contains an ExecutableDebugAdapter built on the Microsoft.VisualStudio.Shared.VSCodeDebugProtocol NuGet package.
It can be used to attach to a running process. If the user selects Disconnect both the debugger and debuggee are terminated.
The debugger executable receives the disconnect request but VS Code is terminating the executable and its children (using TASKKILL) before the debuggee has been been detached from the debugger and without waiting for a response from the disconnect request.
Adding logging to a DebugAdapterTracker and using a test program named taskkill.exe shows that taskkill is being executed less than a second after the disconnect request is sent, which is often an insufficient amount of time for the debugger to disconnect from the debuggee resulting in both being terminated.
Would it be possible to provide a means for an extension to delay the execution of taskkill for a longer amount of time or to instruct VS Code to wait for the disconnect response?

Unfortunately I cannot attach a simple cutdown. 

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

**Comment by roblourens** [comment]
We don't forcibly kill the debug adapter unless there was an error. Are you sure there wasn't an error returned from the DA? Did the stdin/out pipes get closed prematurely? Do you see an error anywhere in your logs or maybe in the vscode devtools (Help > Toggle Developer Tools)

**Comment by gaelwilson** [comment]
@roblourens Thanks for responding so quickly. 
Nothing is returned from the DA. It is in its code to disconnect when killed. 
There is no code in the DA that closes the pipes. 
I may have misunderstood what in saw in the ms-vscode repository but it looked as though taskkill is always executed in the stopSession method for an ExecutableDebugAdapter (in src/vs/workbench/contrib/debug/node/debugAdapter.ts) hence me creating a test version of taskkill to verify the exact time at which it is called.

**Comment by roblourens** [comment]
Yes but if you trace back where stopSession is called from, it's not called immediately after the disconnect request for no reason.

**Comment by gaelwilson** [comment]
Can you clarify where stopSession is being called from and how I would trace that ? The only place I could see the disconnect was in rawDebug.ts and it sends it, doesn't await the result, and calls stopDebugger in a finally block which calls stopSession.  

Would it help if I supplied a trace of the messages sent and received by the DA ?

**Comment by gaelwilson** [comment]
@roblourens It is possible to see taskkill being executed when using the Microsoft C/C++ extension pack.
Create a taskkill.exe from the following C# code

```
using System;
using System.Windows.Forms;

namespace TaskKill
{
    static class TaskKill
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            var currentTime = DateTime.Now;
            var timeString = $"Started at {currentTime.ToString()}.{currentTime.Millisecond.ToString()}";
            MessageBox.Show(timeString, "Test taskkill");
        }
    }
}
```
and add the folder containing it to PATH.
Create a C test program eg
```
#include <stdio.h>
main()
{
	printf("Hello");
	getchar();
}

```
and compile and run it.
Start VS Code attach to the running C program via the following launch.json
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Attach",
            "type": "cppvsdbg",
            "request": "attach",
        }

    ]
}

```
When you disconnect you will see the message box from the dummy taskkill.exe.

**Comment by roblourens** [comment]
Thanks for putting up with me @gaelwilson. I think this regressed, sending a PR.

**Comment by gaelwilson** [comment]
> Thanks for putting up with me @gaelwilson. I think this regressed, sending a PR.

@roblourens Thanks for following up with me on this, it is greatly appreciated. 
Regards, Gael.

**Comment by gaelwilson** [comment]
@roblourens Just to let you know, I have checked my extension with the insiders build and it works as expected now. Thanks again for your help and for resolving the issue so quickly.
