### ISSUE TITLE
Cmd-d of single character followed by typing same character as has no effect

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#16520]
- VSCode Version: 1.7.2

This is a odd one. Steps to reproduce:

1. Create document `x x`.
2. Hit cmd-D twice to select both.
3. Type `x`.
4. _Nothing will happen_.
5. Type `y`.
6. All instances will be replaced by `y`.

What I expected would happen: All instances should be replaced with `x` and the cursor moved after it, so that when you then type `y`, you end up with `xy xy`.

If it sounds minor, this happens to me all the time. For example, when replacing one-letter loop variables.

**Comment by alexandrudima** [comment]
wow, nice find! 👍

**Comment by atombender** [comment]
Just in case the above came across as a rare edge case: Let's say you have the variable `i`. You want to replace it with `iterator`. To accomplish this after hitting cmd-D, you have to type `iiterator` — an extra "i" as the first on has no effect. Pretty annoying.

**Comment by alexandrudima** [comment]
Additional steps from #25101:

1. New Untitled File
2. Press: a
3. Select: a
4. Press: a
5. Expected: Selection disappears and cursor is to the right of a.
6. Actual: Selection stays.

This only happens when overwriting with the same character.
