### ISSUE TITLE
An "edit" icon would be more suited than the copy icon for the new settings editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16529]
@chrmarti suggested a pencil icon would probably be better earlier on, not sure if this has an issue already

![image](https://cloud.githubusercontent.com/assets/2193314/20896327/1ee9276a-bad2-11e6-849d-600147dd2c8b.png)

A copy icon is particularly confusing on the right side.

**Comment by sandy081** [comment]
@bgashler1 Can you provide an appropriate icon that matches in Copy and Edit contexts

**Comment by bgashler1** [comment]
I was thinking something like this (implying it is moving some kind of setting over to the other side
<img width="500" alt="screen shot 2016-12-05 at 10 13 58 pm" src="https://cloud.githubusercontent.com/assets/11839736/20915017/25dd0c1a-bb38-11e6-8f13-7163ffe12ade.png">

If this sounds good to you, here is the icon
[arrow_forward.zip](https://github.com/Microsoft/vscode/files/633097/arrow_forward.zip)

**Comment by bgashler1** [comment]
Also, here is the pencil icon that was suggested
[Uploading edit_grey.zip…]()

**Comment by sandy081** [comment]
I sticked to edit icon so that it will be consistent in both the editors
