### ISSUE TITLE
After last update, upper menu is white even if System theme is dark

### ISSUE THREAD

**Issue by All3xJ** [microsoft/vscode#165261]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
```
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:16:26.920Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.76-1-lts
Sandboxed: No
```
- OS Version: `ArchLinux GNOME 43.0 Wayland`

Steps to Reproduce:

1. Open VS Code

![image](https://user-images.githubusercontent.com/20903913/199559146-1a1e2698-c04a-4828-a5a7-459be81c8de9.png)

Instead, if I go to Settings and modify window.titlebarstyle to custom, I have a non native, but at least dark, menu.

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/130974
