### ISSUE TITLE
Support profiles in remote set ups

### ISSUE THREAD

**Issue by burkeholland** [microsoft/vscode#165247]
When creating a new profile while connected to a Codespace, VS Code should automatically load the Codespaces extension. The current behaviour is that the user is disconnected from their Codespace and even if you install the Codespaces extension, there is no way to reconnect to the Codespace besides closing the remote connection.

https://user-images.githubusercontent.com/686963/199522601-fd13b920-794f-4f7f-824a-f5c21def4b07.mp4

**Comment by isidorn** [comment]
@burkeholland thanks for filling this. We have to fine tune the Codespaces + remote experience for profiles. We already have this item for this https://github.com/microsoft/vscode-internalbacklog/issues/3128

However I think your point is valid and we should keep that in mind when improving the Codespace experience. Thanks

**Comment by sandy081** [comment]
May be if users tries to create/switch profile when in a remote workspace, we shall be including the remote extension by default. But it is tricky because we do not know which remote extension is used for connecting to remote workspace.

**Comment by isidorn** [comment]
Just had a discussion with @sandy081 and we have ideas on how to fix this. We will look into it this milestone most likely.

**Comment by isidorn** [comment]
I assigned to Jan, so we do not lose track of this. @sandy081 hope that is ok.

**Comment by rubensa** [comment]
Please, also support [Dev Containers](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers).  For more info see: https://github.com/microsoft/vscode/issues/116740#issuecomment-1352931492

**Comment by isidorn** [comment]
Thanks for the feedback. We are looking into this. And we are thinking about a solution that would cover all remotes (ssh, wsl, containers...)

**Comment by theonlyfoxy** [comment]
WSL Support would be really appreciated!

**Comment by isidorn** [comment]
@sandy081 awesome 👏 
@burkeholland now you can demo profiles all you want in Codespaces 😊
