### ISSUE TITLE
terminal not working

### ISSUE THREAD

**Issue by yanitzz** [microsoft/vscode#165290]
ADD ISSUE DESCRIPTION HERE

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
Embedder: codespaces

**Comment by yanitzz** [comment]
terminal not allowing me to enter anything.. please help!

**Comment by meganrogge** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by muerwre** [comment]
https://github.com/microsoft/vscode/issues/165316, https://github.com/microsoft/vscode/issues/165310, https://github.com/microsoft/vscode/issues/165321

@meganrogge 

Startup performance as for now:

```
## System Info

* Code: 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f)
* OS: darwin(21.6.0)
* CPUs: Apple M1(8 x 24)
* Memory(System): 16.00 GB(0.28GB free)
* Memory(Process): NaN MB working set(189.39MB private, 0.53MB shared)
* VM(likelihood): 0%
* Initial Startup: false
* Has 1 other windows
* Screen Reader Active: false
* Empty Workspace: false

## Performance Marks

| What                                                            | Duration | Process                   | Info                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ------------------------------------------ |
| start => app.isReady                                            | -        | [main]                    | initial startup: false                     |
| nls:start => nls:end                                            | -        | [main]                    | initial startup: false                     |
| require(main.bundle.js)                                         | -        | [main]                    | initial startup: false                     |
| start crash reporter                                            | -        | [main]                    | initial startup: false                     |
| serve main IPC handle                                           | -        | [main]                    | initial startup: false                     |
| create window                                                   | -        | [main]                    | initial startup: false,                    |
| app.isReady => window.loadUrl()                                 | -        | [main]                    | initial startup: false                     |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 94       | [main->renderer]          | NewWindow                                  |
| require(workbench.desktop.main.js)                              | 156      | [renderer]                | cached data: YES, node_modules took 0ms    |
| wait for window config                                          | 0        | [renderer]                | -                                          |
| init storage (global & workspace)                               | 5        | [renderer]                | -                                          |
| init workspace service                                          | 19       | [renderer]                | -                                          |
| register extensions & spawn extension host                      | 256      | [renderer]                | -                                          |
| restore viewlet                                                 | 30       | [renderer]                | workbench.view.explorer                    |
| restore panel                                                   | 21       | [renderer]                | terminal                                   |
| restore & resolve visible editors                               | 133      | [renderer]                | 1: workbench.editors.files.fileEditorInput |
| overall workbench load                                          | 258      | [renderer]                | -                                          |
| workbench ready                                                 | 531      | [main->renderer]          | -                                          |
| renderer ready                                                  | 440      | [renderer]                | -                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                          |
| extensions registered                                           | 722      | [renderer]                | -                                          |


## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1667452470706	0	0
code/didStartMain	1667452470798	92	92
code/willStartCrashReporter	1667452470804	6	98
code/didStartCrashReporter	1667452470857	53	151
code/mainAppReady	1667452470897	40	191
code/willLoadMainBundle	1667452470938	41	232
code/fork/willLoadCode	1667452470946	8	240
code/registerFilesystem/file	1667452471006	60	300
code/didLoadMainBundle	1667452471020	14	314
code/willStartMainServer	1667452471027	7	321
code/didStartMainServer	1667452471029	2	323
code/willCreateCodeWindow	1667452471072	43	366
code/willRestoreCodeWindowState	1667452471072	0	366
code/didRestoreCodeWindowState	1667452471072	0	366
code/willCreateCodeBrowserWindow	1667452471072	0	366
code/didCreateCodeBrowserWindow	1667452471093	21	387
code/didCreateCodeWindow	1667452471094	1	388
code/willOpenNewWindow	1667452471095	1	389
code/willCreateCodeWindow	1667465935009	13463914	13464303
code/willRestoreCodeWindowState	1667465935009	0	13464303
code/didRestoreCodeWindowState	1667465935009	0	13464303
code/willCreateCodeBrowserWindow	1667465935009	0	13464303
code/didCreateCodeBrowserWindow	1667465935017	8	13464311
code/didCreateCodeWindow	1667465935017	0	13464311
code/willOpenNewWindow	1667465935017	0	13464311
code/willCreateCodeWindow	1667465948931	13914	13478225
code/willRestoreCodeWindowState	1667465948931	0	13478225
code/didRestoreCodeWindowState	1667465948931	0	13478225
code/willCreateCodeBrowserWindow	1667465948931	0	13478225
code/didCreateCodeBrowserWindow	1667465948945	14	13478239
code/didCreateCodeWindow	1667465948946	1	13478240
code/willOpenNewWindow	1667465948947	1	13478241
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1667465948947	0	0
code/didStartRenderer	1667465949038	91	91
code/willWaitForWindowConfig	1667465949038	0	91
code/didWaitForWindowConfig	1667465949038	0	91
code/willShowPartsSplash	1667465949038	0	91
code/didShowPartsSplash	1667465949039	1	92
code/willLoadWorkbenchMain	1667465949041	2	94
code/didLoadWorkbenchMain	1667465949197	156	250
code/registerFilesystem/file	1667465949198	1	251
code/registerFilesystem/vscode-userdata	1667465949198	0	251
code/willInitWorkspaceService	1667465949199	1	252
code/willInitStorage	1667465949199	0	252
code/didInitStorage	1667465949204	5	257
code/willInitUserConfiguration	1667465949207	3	260
code/didInitUserConfiguration	1667465949210	3	263
code/willInitWorkspaceConfiguration	1667465949210	0	263
code/didInitWorkspaceConfiguration	1667465949218	8	271
code/didInitWorkspaceService	1667465949218	0	271
code/willStartWorkbench	1667465949220	2	273
code/LifecyclePhase/Ready	1667465949221	1	274
code/willCreateWorkbenchContributions/1	1667465949248	27	301
code/didCreateWorkbenchContributions/1	1667465949260	12	313
code/willCreateWorkbenchContributions/2	1667465949260	0	313
code/registerFilesystem/trustedDomains	1667465949261	1	314
code/registerFilesystem/vscode-local-history	1667465949264	3	317
code/didCreateWorkbenchContributions/2	1667465949265	1	318
code/willRestoreEditors	1667465949345	80	398
code/willRestoreViewlet	1667465949348	3	401
code/willRestorePanel	1667465949357	9	410
code/didRestoreViewlet	1667465949378	21	431
code/didRestorePanel	1667465949378	0	431
code/willResolveExplorer	1667465949385	7	438
code/willLoadExtensions	1667465949413	28	466
code/didRestoreEditors	1667465949478	65	531
code/LifecyclePhase/Restored	1667465949478	0	531
code/didStartWorkbench	1667465949478	0	531
code/didRemovePartsSplash	1667465949478	0	531
code/willCreateWorkbenchContributions/3	1667465949478	0	531
code/willResumeEditSessionFromIdentifier	1667465949490	12	543
code/didResumeEditSessionFromIdentifier	1667465949490	0	543
code/registerFilesystem/vscode-edit-sessions	1667465949491	1	544
code/didCreateWorkbenchContributions/3	1667465949514	23	567
code/willConnectSharedProcess	1667465949516	2	569
code/willHandleExtensionPoints	1667465949567	51	620
code/willHandleExtensionPoint/configurationDefaults	1667465949567	0	620
code/didHandleExtensionPoint/configurationDefaults	1667465949580	13	633
code/willHandleExtensionPoint/configuration	1667465949580	0	633
code/didHandleExtensionPoint/configuration	1667465949619	39	672
code/willHandleExtensionPoint/jsonValidation	1667465949619	0	672
code/didHandleExtensionPoint/jsonValidation	1667465949619	0	672
code/willHandleExtensionPoint/debuggers	1667465949619	0	672
code/didHandleExtensionPoint/debuggers	1667465949621	2	674
code/willHandleExtensionPoint/breakpoints	1667465949621	0	674
code/didHandleExtensionPoint/breakpoints	1667465949621	0	674
code/willHandleExtensionPoint/notebooks	1667465949621	0	674
code/didHandleExtensionPoint/notebooks	1667465949622	1	675
code/willHandleExtensionPoint/notebookRenderer	1667465949622	0	675
code/didHandleExtensionPoint/notebookRenderer	1667465949622	0	675
code/willHandleExtensionPoint/problemPatterns	1667465949622	0	675
code/didHandleExtensionPoint/problemPatterns	1667465949622	0	675
code/willHandleExtensionPoint/problemMatchers	1667465949622	0	675
code/didHandleExtensionPoint/problemMatchers	1667465949623	1	676
code/willHandleExtensionPoint/taskDefinitions	1667465949623	0	676
code/didHandleExtensionPoint/taskDefinitions	1667465949624	1	677
code/willHandleExtensionPoint/terminal	1667465949624	0	677
code/didHandleExtensionPoint/terminal	1667465949624	0	677
code/willHandleExtensionPoint/walkthroughs	1667465949624	0	677
code/didHandleExtensionPoint/walkthroughs	1667465949624	0	677
code/willHandleExtensionPoint/commands	1667465949624	0	677
code/didHandleExtensionPoint/commands	1667465949626	2	679
code/willHandleExtensionPoint/submenus	1667465949626	0	679
code/didHandleExtensionPoint/submenus	1667465949626	0	679
code/willHandleExtensionPoint/menus	1667465949626	0	679
code/didHandleExtensionPoint/menus	1667465949633	7	686
code/willHandleExtensionPoint/languages	1667465949633	0	686
code/didHandleExtensionPoint/languages	1667465949643	10	696
code/willHandleExtensionPoint/customEditors	1667465949643	0	696
code/didHandleExtensionPoint/customEditors	1667465949643	0	696
code/willHandleExtensionPoint/codeActions	1667465949643	0	696
code/didHandleExtensionPoint/codeActions	1667465949643	0	696
code/willHandleExtensionPoint/viewsWelcome	1667465949643	0	696
code/didHandleExtensionPoint/viewsWelcome	1667465949643	0	696
code/willHandleExtensionPoint/authentication	1667465949643	0	696
code/didHandleExtensionPoint/authentication	1667465949643	0	696
code/willHandleExtensionPoint/resourceLabelFormatters	1667465949643	0	696
code/didHandleExtensionPoint/resourceLabelFormatters	1667465949643	0	696
code/willHandleExtensionPoint/grammars	1667465949643	0	696
code/didHandleExtensionPoint/grammars	1667465949645	2	698
code/willHandleExtensionPoint/colors	1667465949645	0	698
code/didHandleExtensionPoint/colors	1667465949646	1	699
code/willHandleExtensionPoint/icons	1667465949646	0	699
code/didHandleExtensionPoint/icons	1667465949647	1	700
code/willHandleExtensionPoint/semanticTokenScopes	1667465949647	0	700
code/didHandleExtensionPoint/semanticTokenScopes	1667465949647	0	700
code/willHandleExtensionPoint/snippets	1667465949647	0	700
code/didHandleExtensionPoint/snippets	1667465949647	0	700
code/willHandleExtensionPoint/keybindings	1667465949647	0	700
code/didHandleExtensionPoint/keybindings	1667465949650	3	703
code/willHandleExtensionPoint/themes	1667465949650	0	703
code/didHandleExtensionPoint/themes	1667465949651	1	704
code/willHandleExtensionPoint/iconThemes	1667465949651	0	704
code/didHandleExtensionPoint/iconThemes	1667465949651	0	704
code/willHandleExtensionPoint/continueEditSession	1667465949651	0	704
code/didHandleExtensionPoint/continueEditSession	1667465949651	0	704
code/willHandleExtensionPoint/viewsContainers	1667465949651	0	704
code/didHandleExtensionPoint/viewsContainers	1667465949661	10	714
code/willHandleExtensionPoint/views	1667465949661	0	714
code/didHandleExtensionPoint/views	1667465949666	5	719
code/didHandleExtensionPoints	1667465949666	0	719
code/didLoadExtensions	1667465949669	3	722
code/didResolveExplorer	1667465949801	132	854
```

## Node Cached Data Stats


### cached data used


### cached data missed


### cached data rejected


### cached data created (lazy, might need refreshes)
```

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/33246675/199682398-18234b7e-494c-41dc-a500-ad92729adee2.png">

**Comment by meganrogge** [comment]
what happens if you disable all extensions?

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAcceleration`
