### ISSUE TITLE
 the terminal no longer works.

### ISSUE THREAD

**Issue by noe0000** [microsoft/vscode#165229]
Type: <b>Bug</b>

When I opened vs code, the app offered me to trust vs code. I accepted and when I tried to run a program, nothing happened, it wouldn't launch. I looked in my settings, in your help space but I did not find anything similar.

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12600KF (16 x 3686)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (10.34GB free)|
|Process Argv|--crash-reporter-id 7ad9f0fa-82e8-45ef-808a-0e4b265b7c92|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.72.10120953
python|ms-|2022.16.1
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by sbatten** [comment]
can you please show a screen recording of your issue? @noe0000

**Comment by noe0000** [comment]
Hello, I just opened vs code and everything is working normally!!
Sorry for the inconvenience but for information absolutely nothing happened on my screen when I launched the program. I tried all the possible functionalities to launch my script but no one worked.

**Comment by sbatten** [comment]
okay thank you, it sounds more like a project or os issue than VS Code specifically, but if it comes back and you believe otherwise, please feel free to report again.

**Comment by noe0000** [comment]
I still don't know why it works again. When I launched vs code there is a notification that offered me to trust vs code and I checked the box I agree. from that moment, I could no longer launch my script. I uninstalled vs code, I searched on forums, on your help page, but I couldn't find anything similar. if i can do anything to help you please don't hesitate to contact me.
Thanks for you support.
