### ISSUE TITLE
IntelliSense broken using files tag in json config file.

### ISSUE THREAD

**Issue by blopez2010** [Microsoft/vscode#16523]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-settings-sync|Shan|2.3.8|
|html-css-class-completion|Zignd|1.0.3|
|html-snippets|abusaidm|0.0.18|
|Bookmarks|alefragnani|0.10.1|
|project-manager|alefragnani|0.12.2|
|gitignore|codezombiech|0.5.0|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-jasmine-es5|deerawan|1.0.1|
|githistory|donjayamanne|0.1.2|
|gitlens|eamodio|1.3.0|
|vscode-util|guosong|1.0.5|
|rest-client|humao|0.11.0|
|Angular2|johnpapa|1.0.2|
|vscode-todo-parser|minhthai|1.8.3|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|java|redhat|0.0.7|
|vscode-icons|robertohuertasm|4.0.5|
|guides|spywhere|0.5.1|
|code-spell-checker|streetsidesoftware|0.12.2|
|lodash-snippets|tomphilbin|0.7.0|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|join-lines|wmaurer|0.2.0|
|JavaScriptSnippets|xabikos|1.2.0|
|local-history|xyz|1.1.0|

---

Steps to Reproduce:

IntelliSense is broken when using files: ['src/']

I got this folder structure:

![image](https://cloud.githubusercontent.com/assets/15872584/20895222/26a4c930-bade-11e6-986d-b1d6d9ddc630.png)

and having this result:

![image](https://cloud.githubusercontent.com/assets/15872584/20895237/3669c726-bade-11e6-9bf3-a313e0bcecc7.png)

if I remove files from jsConfig.json everything works as expected.

**Comment by mjbvz** [comment]
@blopez2010 I believe you are running into a common problem: [`"files"` must be a list of file names, not glob patterns](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html).

Try changing your `jsconfig.json` to use `"include"` instead:

```json
{
  "include": [
    "typings/**",
    "spec/**"
  ]
}
```

Please let me know if this does not work.

Thanks
