### ISSUE TITLE
git process crashing breaks switching branches using the SCM UI

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165258]
1. Be on a feature branch
2. Try to switch branches using the ref picker in the bottom left
3. If this process fails, you get in a bad state where all operations using the SCM UI don't work anymore
4. The error message displayed says that a git process may have crashed in this directory and if so to delete `.git/HEAD.lock`
5. Additionally if you try to switch refs again, SCM retries 3 times (based on the output log) and then gives up with the same error message

Could we offer an action button to remove head.lock and retry in this scenario?

**Comment by lszomoru** [comment]
@joyceerhl, do you have repro steps that would get me in a state in which the crash occurs in the first place?

**Comment by joyceerhl** [comment]
I'm not sure how the process got killed, I think it might've been while I had a large number of changes and switching to a branch that was several dozen commits behind upstream, and I had the setting enabled to pull the branch that I switch to and stash changes when switching branches. I don't think that will reliably cause git to crash though.

**Comment by lszomoru** [comment]
Thanks @joyceerhl. Will keep the issue open for some time to see if anyone else runs into this problem.

**Comment by lszomoru** [comment]
Closing the issue for now. Please feel free to reopen in case the issue reoccurs. Thanks!
