### ISSUE TITLE
Is there an option to work around integrated terminal utf8-restriction?

### ISSUE THREAD

**Issue by GitMensch** [microsoft/vscode#165218]
https://github.com/microsoft/vscode/blob/f95bfdae3c5a662499d2f3db59b24050d4c31f48/src/vs/workbench/contrib/terminal/common/terminalConfiguration.ts#L265-L275

Question: is the restriction that led to the auto-setting and option to adjust that via `terminal.integrated.detectLocale` an "upstream Electron" issue? If yes: can this be worked around?

Option 1 (most preferred): allow at least _some_ non-UTF-8 encodings (common western iso8859 in my case...)
Option 2: replace the "normal" integrated terminal with a different integrated terminal that can be configured to be used (is this even possible; and if yes is there a terminal extension that does not have that restriction)?

**Comment by meganrogge** [comment]
you can setup an encoding of your choice by disabling `detectLocale`

**Comment by GitMensch** [comment]
> you can setup an encoding of your choice by disabling `detectLocale`

Sadly this does not work. YES the system defined locale is unchanged if I set that to `off`; but any data entered in the internal terminal or which is rendered in there is still UTF8 only.

This issue is about _using_ an encoding like en_US.iso885915 in the terminal, not only in the called programs (which then output en_US.iso885915 data which is not rendered correctly in the terminal).

Please reopen as this request isn't "completed" (it may be "closed as not planned", but I hope it can get at least to the backlog or some workaround can be found).
