### ISSUE TITLE
Please update architecture declarators

### ISSUE THREAD

**Issue by bitcrazed** [microsoft/vscode#165297]
In the VSCode download page, please consider updating the architecture declarators to a more consistent, less ambiguous common nomenclature:

![image](https://user-images.githubusercontent.com/961950/199621759-bc4f7f37-756d-4213-997d-bcd22adc40ca.png)

May I suggest for your consideration (very open to others' suggestions here, too):

| **Current** | **New** | 
| --- | ---|
| 32-bit | 32-bit x86 |
| 64-bit | 64-bit x64 |
| Arm | Arm* | 
| ARM64 | 64-bit Arm** |

\* Arm (the company) prefers we use this Camel-cased "Arm", not all-caps "ARM".
\** Arm64 is likely going to be unnecessary moving forward since Arm are deprecating 32-bit Arm Cores/SoCs starting with current generation Arm processors/SoCs.

Thanks @riverar for [the original suggestion](https://twitter.com/WithinRafael/status/1587217805870407680?s=20&t=roAP4_SV-SP1Oto3DptMhg).

**Comment by riverar** [comment]
Recommend you align with other prior art in the Microsoft ecosystem. That is `Arm64` or `ARM64`.

I do not recommend you try to use generic `Arm` usage as dev tooling can still target both 32-bit and 64-bit ARM targets and Microsoft already used this term for 32-bit targets.

Think we all agree `ARM 64` and `ARM` on this page are bad. 🙃

`Arm64`
https://dotnet.microsoft.com/download/dotnet/6.0
https://learn.microsoft.com/windows-hardware/drivers/develop/building-arm64-drivers
https://devblogs.microsoft.com/visualstudio/arm64-visual-studio/
https://learn.microsoft.com/windows-hardware/drivers/debugger/debugging-arm64
https://learn.microsoft.com/powershell/scripting/install/powershell-on-arm?view=powershell-7.2
https://blogs.windows.com/windowsdeveloper/2022/06/14/arm64-visual-studio/

`ARM64`
https://learn.microsoft.com/en-us/java/openjdk/download
https://learn.microsoft.com/visualstudio/extensibility/arm64/target-arm64-visual-studio-extension?view=vs-2022
https://devblogs.microsoft.com/cppblog/visual-studio-code-c-extension-arm-and-arm64-support/

**Comment by chrisdias** [comment]
@joaomoreno can i take a swing at this one?

**Comment by joaomoreno** [comment]
@chrisdias Be my guest!

**Comment by riverar** [comment]
Can you share the direction you went? (The live site doesn't look any different, guessing the change hasn't deployed yet.)

**Comment by chrisdias** [comment]
The original `64-bit x64` etc suggestions made the pages unreadable, so I went with what I saw on the .NET page https://dotnet.microsoft.com/download/dotnet/6.0

![image](https://user-images.githubusercontent.com/1487073/201184251-bd814b20-a3f0-4607-9f98-98d7bf22b3cb.png)

**Comment by riverar** [comment]
@chrisdias Looks great and consistent now, thanks!
