### ISSUE TITLE
Test: Javascript and CSS in HTML

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16526]
Test for #15377:

- [x] Windows - **@isidorn**
- [x] OS X - **@joaomoreno**
- [x] Linux - **@sandy081**

Complexity: 4

Test HTML files with JavaScript content:
- Content inside script tags, with an with/without type='application/javascript' and 'text/javascript'
- Content inside event handlers `onClick="alert('hello!')"`
- Test Validation, Hovers, Code Complete, Signature Help, Symbol highlighting, References, Definitions, Document symbols (Ctrl+Shift+O)
- Test code completion agains the DOM API as well as JQuery API (always available)
- Note that script includes are not taken into account, nor are other JavaScript files in the workspace. Only scripts in the current HTML file are looked at.

Test HTML files with CSS content:
- Content inside style tags
- Content inside 'style' attributes `<div style='color:red'>`
- Test Validation, Hovers, Code Complete, Symbol highlighting, Document symbols (Ctrl+Shift+O), Color decorators

Format, full document and range
- note that there's no built-in css formatter
- note that the html formatter has configuration settings that specify which tags not to be formatted

**Comment by ramya-rao-a** [comment]
Closing as the assigned testers are done testing
