### ISSUE TITLE
Show "task is already active" in a dialog instead of a notification

### ISSUE THREAD

**Issue by dovalid** [microsoft/vscode#165263]
I'd like if the "task is already active" alert would be a dialog instead of a notification. So when we press for example `CMD+SHIFT+B` intentionally to restart or terminate the build task, we could achieve it with just keyboard navigation. We can keep "Cancel" as the CTA (the same as not doing anything with the notification) as that's the least destructive option.

So instead of this:
![image](https://user-images.githubusercontent.com/38188141/199547399-2b5722a7-8757-48ab-8b07-bbdf06dbf85b.png)
I'd like this:
![image](https://user-images.githubusercontent.com/38188141/199551856-72dbc0ef-6f51-4385-870f-818487207c25.png)

Lmk if I should make a PR for it!

**Comment by meganrogge** [comment]
We have some guidelines for when to use notifications vs dialogues here
https://code.visualstudio.com/api/ux-guidelines/notifications

The notification should be navigable via F1 > Show notifications, and the up/down arrows. Pls lmk if that does not work for you

**Comment by dovalid** [comment]
Thanks, that's a great flowchart. My intention is that user input is immediately needed, since I wanted to do something and now have to choose how to forward. A notification would be great is starting a task would happen automatically, but it always happens on user action doesn't it?
