### ISSUE TITLE
Vertical selection shortcut inconsistency

### ISSUE THREAD

**Issue by anporumb** [microsoft/vscode#165251]
Type: <b>Feature Request</b>

Hello Visual Studio Code,

I will begin by saying that if I could I would migrate ALL my editors to Visual Studio Code (among those are Visual Studio IDE, Notepad++, .NETTextAnalyzer). So amazing nice job!!!

Aaaaand I am writing you to complain about the inconsistency in vertical selection of text.

Using mouse: keep pressed ALT+SHIFT, press mouse button => selection
Using keyboard: keep pressed CTRL+ALT, press UP/DOWN arrow => selection.

Would be awesome if these actions would be like in Visual Studio IDE, that is:

Using mouse: keep ALT pressed + mouse selection => selection
Using keyboard: keep ALT+SHIFT + arrows UP/DOWN => selection.

Best Regards,
Andrei Porumb

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by alexdima** [comment]
Column selection in VS Code is slightly different than box selection in VS. 

* From your message, it seems that you would like to configure `"editor.multiCursorModifier": "ctrlCmd"`. Doing so would free up <kbd>Alt</kbd> and allow that doing mouse selection (via dragging) and pressing <kbd>Alt</kbd> would switch between column selection and regular selection.

* There is also a menu item `Selection > Column Selection Mode` which toggles that all selections will be column selections until clicked again. This is something you can add a keybinding for if you want.

* You can also use the middle mouse button to make a column selection using the mouse
