### ISSUE TITLE
removeUnusedImports commands do not appear in the Command Palette

### ISSUE THREAD

**Issue by ArturoDent** [microsoft/vscode#165212]
Does this issue occur when all extensions are disabled?: Yes/No

Steps to Reproduce:

1. Check the Command Palette for the new js/ts `Remove Unused Imports` commands (in a a ts file with imports, if that matters).

The commands do not show up in the Command Palette although they are in the Keyboard Shortcuts.

Version: 1.73.0-insider (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:30:14.729Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25231
Sandboxed: Yes

**Comment by mjbvz** [comment]
The command  requires using TS 4.9+. You can create a keybinding for the command, but it will only work on that typescript version. That's why we don't show it in the command palette
