### ISSUE TITLE
Call stack filter is filtering character by character instead of words

### ISSUE THREAD

**Issue by vinicius-smartme** [microsoft/vscode#165240]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.72.2
- OS Version: Windows 10

Description:
When pausing a debug session, at pressing Ctrl+f on the Call Stack window a filter text box will pop-up. After typing the desired word and clicking the `Filter` button, it should filter the call stack elements by the typed word, but instead it is filtering by the characters composing the word

Steps to Reproduce:

1. Write and compile a program (better if multithreaded)
2. Start a debug session
3. Pause the debug session
4. Go to the Call Stack window
5. Click on any thread on the Call Stack window to set the selection on this window
6. Press Ctrl+f and type a word to be filtered (some that will provide some result after the filter is applied)
7. Observe the result

Expected Result:
- Only the stacks with the typed word should be displayed on the Call Stack window

Observed Result:
- Stacks with any character from the typed word are displayed on the Call Stack window
![image](https://user-images.githubusercontent.com/73820781/199509641-c5e61b7b-f432-4b37-8591-7c2fe528569e.png)

**Comment by roblourens** [comment]
This is just how the feature works currently- it does a fuzzy match, and you can see that the matches all contain all characters in the right order.

**Comment by gjsjohnmurray** [comment]
If/when #164376 gets merged it will help here.
