### ISSUE TITLE
News like Visual Studio - Feature Request

### ISSUE THREAD

**Issue by chandusekhar** [Microsoft/vscode#16525]
Latest news page visual studio.

**Comment by chrisdias** [comment]
Hi @chandusekhar,

Thanks for the suggestion, its the first time we've had this one!  

However, I don't foresee us adding something like this to VS Code. We want Code to be a lightweight editor and showing a news feed on startup feels contrary to that design goal.   

I'm going to close this but folks can still feel free to thumbs up/down the suggestion. If we get a bunch of interest then we'll look into it again.

Thanks again for the suggestion, we appreciate you taking the time to submit the idea.
Chris

**Comment by chandusekhar** [comment]
Thanks for implementing welcome page. This is really useful to open recent folders.  Is there any way to filter extensions by installs in last one week and month. This helps to identify the extensions those gained popularity recently.
