### ISSUE TITLE
allow terminal quick fixes to be chained together

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#165254]
I _always_ take certain actions, so part of my flow has been to anticipate the lightbulb, wait for it to show up, and then action it. 

I suggest allowing terminal quick fixes to be automatically run via an `opt-in` setting. 

Perhaps we could have the following for each action:

```
{ id: string, autoRun?: boolean disabled?: boolean }
```

Current:

https://user-images.githubusercontent.com/29464607/199536673-36025147-0bbd-40e1-a6d5-dd64ee263626.mov

Proposed:

https://user-images.githubusercontent.com/29464607/199536682-59d37c9a-83fe-443f-b717-08a3b56818dd.mov

**Comment by meganrogge** [comment]
I talked with Kai and we decided that instead of chaining together separately run commands, we should allow specifying quick fixes to apply for a given command line match pattern.

The setting could be similar to `editor.codeActionsOnSave`

**Comment by Tyriar** [comment]
> we should allow specifying quick fixes to apply for a given command line match pattern.

Interesting idea, seems very much like a power user feature regarding discovery, but I guess that's good since it's dealing with terminal input which is somewhat dangerous. Can add to quick fix docs.
