### ISSUE TITLE
Show lines modifications in vertical left stripe

### ISSUE THREAD

**Issue by stderr-to-devnull** [microsoft/vscode#165348]
I used to be able to see a colored left stripe bar between the line numbers and file content and when I modified a line in a file, I would be able to hover on that bar and click it and it would show me what was changed in the corresponding line, a mini diff opened below that line and I would be able to simply click on the previous content to revert.

I have no idea how it is called, when exactly and where it went away, I've spent more than 1 hour looking for anything related to this trying to get it back but I came up empty.

Maybe in the future try to withhold throwing the kitchen sink at this IDE because people get absolutely lost in the billions of options and layouts and views and all sorts of settings that no one can make sense of anymore. Almost every minor release _release notes_ are like a Game of Thrones book - with animations!

**Comment by gjsjohnmurray** [comment]
These are called diff decorations. Please search in Settings Editor for `diffdecorations`.

**Comment by stderr-to-devnull** [comment]
thanks for the reply, I checked and everything is enabled

![Screenshot 2022-11-03 142126](https://user-images.githubusercontent.com/54434463/199731966-a7e7942e-2048-43eb-9298-0bec60cf4fde.png)

**Comment by stderr-to-devnull** [comment]
I also tried disabling GitLens but the bar/stripe still does not appear and everything related to it is enabled.

**Comment by stderr-to-devnull** [comment]
So after more digging around I finally found out what they are called and changed the bug title accordingly.
VSCode version 1.73 on MacOS Monterey.

**Comment by stderr-to-devnull** [comment]
Upon further investigation, it doesn't work only when connected remotely over SSH with the official extension. Duplicate of `#122262`... which is open since `27 April 2021`. No hurry, probably all devs are very busy with the next emoji pack update.
