### ISSUE TITLE
Edit menu Emmet commands should be separated from Block comment commands

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16537]
- VSCode Version:1.8.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Open Edit menu
The Emmet commands are grouped with the Block Comment commands. The Emmet commands should be in their own section delimited by a line separator.

**Comment by chrmarti** [comment]
My feeling is that the Edit menu is already at (or slightly above) the limit of number of separators that add to the eye's orientation within the list. Removing the separator between the two 'find' groups might actually improve orientation for me.

**Comment by chrmarti** [comment]
Keeping it as-is for now.
