### ISSUE TITLE
Terminal unresponsive on Safari iPad

### ISSUE THREAD

**Issue by marshypants** [microsoft/vscode#165309]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0
- OS Version: iPad iOS 15.7

Steps to Reproduce:

1. Load VSCODE IDE in safari 
2. Try to type in terminal window. Nothing happens

**Comment by meganrogge** [comment]
@rebornix could you pls try this?

**Comment by marshypants** [comment]
Apologies,

This opens the @rebornix overview, what exactly am I trying?

**Comment by meganrogge** [comment]
set `terminal.integrated.gpuAcceleration` to off or canvas
