### ISSUE TITLE
Extensions requiring reloads should be at the top

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#165365]
Had a badge in the extension view and took awhile to find the extension requiring the reload because it was deep in my extension list. If the extension needs to be acted on I would prefer it be bumped to the top of the view

<img width="460" alt="image" src="https://user-images.githubusercontent.com/4544166/199741065-3c8d379c-40f0-49f2-bf16-fddf9c7353c4.png">

**Comment by sandy081** [comment]
It should be shown in the top. Did you try refreshing the view?

**Comment by lramos15** [comment]
I did not try refreshing the view and I currently do not have any extensions that need updating to test this again.

The process was
1. Reload window for extensions to update
2. New extension is found with an extension requiring an update
3. 🐛 Extension is buried deep in the list.

**Comment by lramos15** [comment]
Update I hit this again, refreshing the list does fix it. Not sure if that's a good enough solution 🤷

**Comment by sandy081** [comment]
I see. We do not move extensions automagically because that can cause jumping in the UI. Hence it requires user action.
