### ISSUE TITLE
Incorrect Syntax Highlighting in VS Dark+ For Computed JS Object Property Name

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16531]
- VSCode Version: 1.8 Insiders

From #16469

**Steps to Reproduce:**

Use VS Dark+ or VS Light+ themes with js code:

```js
({})[1 + 'x']

const a = {
    [1 + 'x']: '3'
}


```

**Expected**
Colorization of computed member is similar to the normal accessor.

**Actual**

![screen shot 2016-12-05 at 10 58 51 am](https://cloud.githubusercontent.com/assets/12821956/20898076/cd8b214a-bad9-11e6-9641-230e2142fedf.png)

This case is correctly colored using most other themes including non-plus VS Dark and VS Light:

![screen shot 2016-12-05 at 11 00 20 am](https://cloud.githubusercontent.com/assets/12821956/20898120/0153b0be-bada-11e6-9d91-ad6e98cb6adf.png)

**Comment by mjbvz** [comment]
@aeschli, it looks like f38751b6d34af94ad10b0f9da9e82d1213e7bb7e introduced this behavior. I'm not sure if it is expected or not. A better syntax highlighting may be to have the square brackets be colored blue, while the contents of the accessor retain their normal colorization.

**Comment by aeschli** [comment]
The intent is to color object keys, which t seems to do.
I'd argue that [1 + 'x'] is a corner case and is good enough for now.
