### ISSUE TITLE
Left CMD opens Peek Definition

### ISSUE THREAD

**Issue by geirsagberg** [Microsoft/vscode#16539]
- VSCode Version: Code - Insiders 1.8.0-insider (c032f0e2bc602eb9388221876911913e5a808aec, 2016-12-05T07:05:13.800Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|EditorConfig|EditorConfig|0.3.4|
|code-settings-sync|Shan|2.3.8|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|vscode-standard-format|chenxsan|0.0.12|
|npm-intellisense|christian-kohler|0.1.4|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-stylesheet-formatter|dbalage|0.2.0|
|vscode-npm-source|dkundel|0.0.3|
|tslint|eg2|0.7.1|
|vscode-npm-script|eg2|0.1.2|
|vscode-npm|fknop|3.3.0|
|auto-close-tag|formulahendry|0.3.6|
|auto-rename-tag|formulahendry|0.0.8|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|PostCSS|ricard|1.0.1|
|yo|samverschueren|0.9.3|
|editorconfig-vscode-snippet|zgudino|0.1.0|

---

Steps to Reproduce:

1. Put cursor on a line in e.g. a JavaScript project
2. Press Left CMD
3. See that Peek Definition opens, though it should not.

**Comment by alexandrudima** [comment]
I believe this is as designed, I think cmd + hover previews definition and cmd + click jumps to definition.

**Comment by bpasero** [comment]
@geirsagberg can you be more specific what you see and what you would expect?

**Comment by geirsagberg** [comment]
Well, it is really problematic when I use CMD + S to save, and peek definition suddenly shows up. Since CMD is a modifier key it shouldn't trigger any action on its own.

**Comment by geirsagberg** [comment]
What's wrong with todays shortcut Alt/Option + F12 for Peek Definition?

**Comment by bpasero** [comment]
@geirsagberg what I am confused is that peek definition just triggers on Cmd+down. Can you share a video how this looks like?

**Comment by geirsagberg** [comment]
![vscode-1](https://cloud.githubusercontent.com/assets/594564/20923685/00caa40c-bbae-11e6-9578-d7128863d877.gif)

1. I put my cursor on a word, then move it away
2. I press left CMD and Peek Definiton pops up
3. I press ESC to close it

**Comment by geirsagberg** [comment]
In other words, there is no way for me to save with LCmd + S without opening Peek Definition

**Comment by geirsagberg** [comment]
In contrast, here is how it is working in latest stable version:

![vscode-2](https://cloud.githubusercontent.com/assets/594564/20923844/b0901494-bbae-11e6-9fab-9a17e4f6a8f7.gif)

**Comment by geirsagberg** [comment]
Actually, it isn't Peek Definition that shows up when pressing LCmd, it is Peek Usages (same as pressing Shift + F12).

**Comment by geirsagberg** [comment]
Okay I have found what is causing it:

I had the following key binding:

```
  {
    "key": "cmd+<",
    "command": "editor.action.referenceSearch.trigger",
    "when": "editorTextFocus"
  },
```

On stable version this worked as expected, but on insider version this caused the bug above.

**Comment by geirsagberg** [comment]
Correction: On stable version this keybinding had no effect (because I am using a Scandinavian keyboard, I have to use "cmd+`" to use the < key. On insider version the keybinding caused the bug above.

**Comment by geirsagberg** [comment]
I will close this issue as it might be misleading, as it really was caused by an invalid keybinding. Still a bit strange that the keybinding issue only affected insider version, but not too big an issue for me to warrant its own bug report.

**Comment by bpasero** [comment]
Thanks
