### ISSUE TITLE
Terminal self-closes

### ISSUE THREAD

**Issue by andrewheumann** [microsoft/vscode#165393]
Type: <b>Bug</b>

When I open the built-in terminal, in any way, it closes itself, rendering it unusable. See attached video. Possibly relevant: my default shell is `fish`

VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id 769857e1-b4a8-4852-bbb3-0262af8cee62|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (74)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-json|and|1.5.2
glsl-literal|boy|1.0.6
vscode-tailwindcss|bra|0.9.1
gltf-vscode|ces|2.3.16
vscode-eslint|dba|2.2.6
typescript-notebook|don|2.0.6
vscode-glsllint|dto|1.8.0
gitlens|eam|13.0.3
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
vscode-solution-explorer|fer|0.7.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
dotnet-test-explorer|for|0.7.8
codespaces|Git|1.13.1
copilot|Git|1.56.7152
vscode-pull-request-github|Git|0.54.0
sass-lint|gle|1.0.7
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.219
vscode-test-explorer|hbe|2.21.1
vscode-guid|hea|1.5.0
debug-visualizer|hed|2.3.1
beautify|Hoo|1.5.0
ilspy-vscode|ics|0.13.1
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.31
graphql-for-vscode|kum|1.15.3
i18n-ally|lok|2.8.1
git-graph|mhu|1.30.0
regexsnippets|Mon|1.0.2
vscode-csscomb|mrm|5.3.2
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.25.0
dotnet-interactive-vscode|ms-|1.0.3552060
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.4.0
python|ms-|2022.18.0
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
js-debug-nightly|ms-|2022.10.1817
live-server|ms-|0.4.3
test-adapter-converter|ms-|0.1.6
vscode-typescript-tslint-plugin|ms-|1.3.4
vsliveshare|ms-|1.0.5750
vscode-paste-image|mus|1.0.4
language-liquid|nei|0.1.1
vetur|oct|0.36.1
terminal-command-keys|pet|0.3.0
material-icon-theme|PKi|4.21.0
quicktype|qui|12.0.46
vscode-commons|red|0.0.6
vscode-xml|red|0.22.0
LiveServer|rit|5.7.9
rust-analyzer|rus|0.3.1266
vscode-coverage-gutters|rya|2.10.2
fish-vscode|sky|0.2.1
shader|sle|1.1.5
velocity|sod|0.2.0
addDocComments|ste|0.0.8
rewrap|stk|1.16.3
vscode-stylelint|sty|1.2.3
sass-indented|syl|1.8.22
alphabetical-sorter|ue|2.0.1
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
volar|Vue|1.0.9
vscode-wakatime|Wak|21.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
3d0df643:30602300

```

</details>

**Comment by andrewheumann** [comment]
https://user-images.githubusercontent.com/31935763/199783757-62ccd73b-d1af-4a65-bbff-bc8c181cc08d.mp4

**Comment by andrewheumann** [comment]
Possibly duplicate of https://github.com/microsoft/vscode/issues/165381?

**Comment by meganrogge** [comment]
Does this reproduce in the insider's build? Also, any errors in the dev tools console?

**Comment by andrewheumann** [comment]
resolved after a restart... if it happens again will check dev tools console
