### ISSUE TITLE
Conflict between eslint fixAll and organizeImports in v1.73.0

### ISSUE THREAD

**Issue by saramorillon** [microsoft/vscode#165330]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.73.0
- OS Version: Windows 11

After upgrading VSCode to 1.73.0, the code actions on save are acting weird.

Steps to Reproduce:

1. Install eslint extension v2.2.6
2. Clone this repository and open it with vscode: https://github.com/saramorillon/vscode-1.73.0-eslint-plugin-import-conflict
3. Install dependencies
4. Open the file `src/file1.js` and save it. 

https://user-images.githubusercontent.com/4224278/199694233-1887341a-e6c9-441d-b650-dc008796dd8c.mp4

Note that the eslint import order does no match vscode standard import order. If both match, there is no issue.
I report this issue here and not to eslint-plugin-import because everything was working well with vscode 1.72.0.

**Comment by mjbvz** [comment]
Please file this against eslint since it sounds like it is causing the issue

**Comment by saramorillon** [comment]
Hello @mjbvz. Everything was working well with vscode v1.72.0. The upgrade to v1.73.0 broke it, that's why I posted it here. It is either a bug in vscode 1.73.0, or a change involving a breaking change. Therefore I think this should be treated here.
