### ISSUE TITLE
VS code Resize Slightly

### ISSUE THREAD

**Issue by Hoyongj** [microsoft/vscode#165327]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
- OS Version:
Edition	Windows 10 Pro
Version	21H2
Installed on	‎2021-‎03-‎13
OS build	19044.1766
Experience	Windows Feature Experience Pack 120.2212.4180.0

Steps to Reproduce:

1. Start VS Code
2. Click X button on the right-top
3. Repeat (1 and 2)
4. The more times repeating the procedure, the bigger VS Code window size is gonna be.

The size grows really slightly. 

I realized that I need to resize the window every week.

So I repeated it for 3 minutes, and I recorded a video as well.

**Comment by deepak1556** [comment]
Unable to repro the issue with latest stable `1.74`
