### ISSUE TITLE
Terminal window frozen, shows $-sign, but does not take any input

### ISSUE THREAD

**Issue by oy0203** [microsoft/vscode#165338]
ENVIRONMENT:
VSCode runs on CS50. https://code.cs50.io

PROBLEM
After accepting prompt to update to latest version of VSCode, the terminal does not accept input any more. The $ sign is displayed. The terminal window is highlighted as active, but the terminal does not respond to any input, and does not display the commands that I try to enter. The other windows works as ordinary. As a result I am not able to interact 

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
does updating your codespace help?

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAcceleration`

**Comment by oy0203** [comment]
Thanks for helping.

Unfortunately, updating my codespace didn't work.


________________________________
Fra: Megan Rogge ***@***.***>
Sendt: torsdag 3. november 2022 19:23
Til: microsoft/vscode ***@***.***>
Kopi: oy0203 ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/vscode] Terminal window frozen, shows $-sign, but does not take any input (Issue #165338)


does updating your codespace help?

**Comment by oy0203** [comment]
Thank you, Megan

This fix worked.
________________________________
Fra: Megan Rogge ***@***.***>
Sendt: torsdag 3. november 2022 22:01
Til: microsoft/vscode ***@***.***>
Kopi: oy0203 ***@***.***>; Author ***@***.***>
Emne: Re: [microsoft/vscode] Terminal window frozen, shows $-sign, but does not take any input (Issue #165338)


disable terminal.integrated.gpuAcceleration
