### ISSUE TITLE
native dialogs related to "files" are opened in background

### ISSUE THREAD

**Issue by saiballo** [microsoft/vscode#165364]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0
- OS Version: Ubuntu Mint

After 6 months native dialogs "Open file" or "Save as" opening behind main window on Ubuntu

Steps to Reproduce:

1. open "save as" dialog for first time -> all it's ok
2.  open "save as" dialog for second time -> native dialog is opened in background. I need to focus it with mouse

https://user-images.githubusercontent.com/3473910/199740028-6763f31f-1c41-4252-bdc1-32a8ebb167ff.mp4

**Comment by gjsjohnmurray** [comment]
Probably #146422

**Comment by saiballo** [comment]
it was scheduled to resolve in july, august, september, october...

**Comment by gjsjohnmurray** [comment]
@saiballo see https://github.com/microsoft/vscode/issues/146422#issuecomment-1172448048 for pointer to the upstream issue.

**Comment by saiballo** [comment]
thank you
