### ISSUE TITLE
Reconsider removing Select All from Edit menu

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16538]
- VSCode Version: 1.8.0 Insiders
- OS Version: Windows 10

I don't think we want to remove Select All from the Edit menu in the Cut/Copy/Paste section. 
If we want to add it to the Selection menu, we could have it in two places but removing it from it's usual place in the Edit menu will disturb customers.

**Comment by chrmarti** [comment]
Not sure I agree. It seems very natural to put it in the Selection menu. (I moved it as part of #16253)

**Comment by gregvanl** [comment]
Adding menu items is good, moving or removing menu items is problematic. The Edit menu is not crowded and Select All fits nicely with Cut/Copy/Paste scenarios (certainly for my workflows with Markdown it does). I recommend we have the command in two places, Edit and Selection.
Is there any downside to having it in more than one place.

**Comment by gregvanl** [comment]
Atom and Visual Studio Community have Select All under the Edit menu. Sublime Text has it under Selection.

**Comment by chrmarti** [comment]
Keeping it as-is unless there is more feedback from the team.
