### ISSUE TITLE
Error while creating Publisher  Uncaught ReferenceError: grecaptcha is not defined

### ISSUE THREAD

**Issue by wavyhair** [microsoft/vscode#165306]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. open https://marketplace.visualstudio.com/manage/createpublisher?managePageRedirect=true
2. After filling in the required fields, click the create button and the console will show Uncaught ReferenceError: grecaptcha is not defined

**Comment by gjsjohnmurray** [comment]
I think this needs to be raised at https://github.com/microsoft/vsmarketplace
