### ISSUE TITLE
Can't type in terminal 

### ISSUE THREAD

**Issue by drewshapiro** [microsoft/vscode#165381]
ADD ISSUE DESCRIPTION HERE - I opened visual studio code which Ive been working in for week and I can not type in the terminal. I've tried restarting, logging out, closing tabs and nothing worked.

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAcceleration`
