### ISSUE TITLE
Typing in multiple space characters <<` `>>  between quotes <<`""`>> inserts a dot <<`.`>>

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode#165383]
Type: <b>Bug</b>

In my C++ code or in a new empty text file on macOS:
1. Type a pair of double quotes `""`
2. Put the cursor between the double quotes`""`
3. Start typing spaces (bang on the spacebar key)

Observe: `" .         "` - a `.` is inserted as the second character.

VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 6, 5|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
markdown-mermaid|bie|1.15.2
mermaid-markdown-syntax-highlighting|bpr|1.5.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.48.1
githistory|don|0.6.19
gitlens|eam|13.0.3
EditorConfig|Edi|0.16.4
vscode-pull-request-github|Git|0.54.0
plantuml|jeb|2.17.4
vscode-catch2-test-adapter|mat|4.3.4
git-graph|mhu|1.30.0
isort|ms-|2022.4.0
pylint|ms-|2022.6.0
python|ms-|2022.18.0
vscode-pylance|ms-|2022.11.10
remote-containers|ms-|0.262.3
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.3
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
vsliveshare|ms-|1.0.5750
vsliveshare-audio|ms-|0.1.91
swift-lang|ssw|0.9.0
shellcheck|tim|0.26.2
vscode-mermaid-editor|tom|0.16.1
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
vscode-apple-swift-format|vkn|1.3.2
vscode-swiftlint|vkn|1.7.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
3d0df643:30602300

```

</details>

**Comment by H-G-Hristov** [comment]
I am not attaching a video as it seem pretty straightforward to reproduce.

**Comment by IllusionMH** [comment]
Do you see this behavior in other apps? Look like OS feature https://howchoo.com/macos/disable-double-space-bar-period-dot-macos

**Comment by H-G-Hristov** [comment]
> Do you see this behavior in other apps? Look like OS feature https://howchoo.com/macos/disable-double-space-bar-period-dot-macos

NO! I tested "MS Teams",  "Safari", "Mail", "Notes".

Please note this happens in VSCode only in between `""`.
This doesn't happen if I just bang on the space bar in an empty file.

**Comment by H-G-Hristov** [comment]
![Nov-07-2022 19-32-49](https://user-images.githubusercontent.com/47526411/200376866-e9a0d2b0-2e1c-4413-b252-398f26dd79b7.gif)

**Comment by H-G-Hristov** [comment]
![Nov-07-2022 19-38-10](https://user-images.githubusercontent.com/47526411/200377751-97541b9d-82da-4fa1-87b4-d9488f56b972.gif)

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/134410
