### ISSUE TITLE
Organize Imports broken in 1.73.0

### ISSUE THREAD

**Issue by nfantone** [microsoft/vscode#165326]
Type: <b>Bug</b>

After upgrading VSCode to `1.73.0`, the **Organize Imports** action hangs indefinitely, preventing the editor from closing gracefully. If using as part of `"editor.codeActionsOnSave"`, files can no longer be saved. Additionally, `import` statement in source files look glitchy, constantly flickering and changing colors  from the theme's to white. See screenshots below.

Reverting back to September's release fixes the issue for me.

VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<img width="679" alt="Organize Imports prevents quitting" src="https://user-images.githubusercontent.com/476069/199687540-e6ccd34d-3e77-41ce-a3d9-cba25c391239.png">

<img width="807" alt="VSCode cannot exit gracefully" src="https://user-images.githubusercontent.com/476069/199687590-45767f84-8965-48eb-b00f-d3015bbff9a8.png">

<img width="739" alt="Graphical glitch on import statements" src="https://user-images.githubusercontent.com/476069/199687876-ba24eef0-4e86-4612-bb59-dd354e58b775.png">

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (5.22GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.0.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
file-icons|fil|1.0.29
terraform|has|2.24.3
search-node-modules|jas|1.3.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.22.2
vscode-typescript-next|ms-|5.0.20221102
vscode-groovy-lint|Nic|2.0.0
code-spell-checker|str|2.10.1
sass-indented|syl|1.8.22
sort-lines|Tyr|1.9.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
volar|Vue|1.0.9
vscode-typescript-vue-plugin|Vue|1.0.9
vscode-todo-highlight|way|1.0.5
better-align|wwm|1.1.6

(1 theme extensions excluded)

</details>

**Comment by GauBen** [comment]
Same thing in Svelte files here

**Comment by RuneClaeys** [comment]
Same for me, also using Vue (Volar) extension.
Disabling organizeImports works as a temporary fix.

**Comment by Zertz** [comment]
It seems like the combination of these two settings causes to editor to save files in an endless loop:

```
"editor.codeActionsOnSave": ["source.organizeImports", "source.fixAll.eslint"],
```

**Comment by nfantone** [comment]
@Zertz I do (or did) have those two settings, indeed.

**Comment by mjbvz** [comment]
Does this reproduce with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)? Sounds like it's likely caused by an extension

**Comment by TriStarGod** [comment]
Due to `source.organizeImports` not respecting trailing commas ( #98123 - unresolved), I also use `source.fixAll.eslint` to fix it. However, the latest release cycles repeatedly.

**Comment by nfantone** [comment]
> Sounds like it's likely caused by an extension
@mjbvz Even if that's the case, this doesn't happen on previous VSCode versions.

**Comment by douira** [comment]
This also happens for me. I haven't changed my extension setup since before the last VSCode update. Even if an extension is involved in this, merely updating VSCode shouldn't be causing this.

**Comment by yoannes** [comment]
Same here on `react-native` project, it crashes vscode

```
"editor.codeActionsOnSave": [
  "source.formatDocument",
  "source.organizeImports",
  "source.fixAll"
],
```

**Comment by migmit** [comment]
Same here with the `vshaxe` extension. I only had `source.organizeImports` in my `codeActionsOnSave`.

**Comment by aamirbinabd** [comment]
Same issue using the Astro framework and its language support extension.

**Comment by tobil4sk** [comment]
Perhaps this issue might have something to do with the recent changes here: #164035 ?

**Comment by mrcaidev** [comment]
Same issue with Astro

**Comment by isJx** [comment]
After I turned off 'source.organizeImports' it was fine

**Comment by Patrick-clone** [comment]
Same issue here, infinite organize import loop with flickering of import statements. I downgraded to version 1.72.2 for now. Hopefully this can be fixed.

**Comment by letsgoaway-games** [comment]
If anyone is here still trying to fix, try do it under workspace settings instead of user settings, fixed the issue for me.

**Comment by letsgoaway-games** [comment]
```
"editor.codeActionsOnSave": {
			"source.sortImports": false
		}
```

**Comment by sergioadimedia** [comment]
For me it's still glitching with this config:
```
"editor.codeActionsOnSave": ["source.fixAll.format", "source.fixAll.eslint"]
"editor.defaultFormatter": "esbenp.prettier-vscode"
```
I had to downgrade to make it work again.

**Comment by tobil4sk** [comment]
> For me it's still glitching with this config

I think that's because the "fixAll" command also sorts/organises the imports.

**Comment by lachenmayer** [comment]
Can confirm that this is an issue for us, also since updating to the latest VS Code version and no other changes. We also have the following settings.json, and run Prettier as part of ESLint's `fixAll` rule.

```
  "editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.fixAll.eslint"
  ],
```

> I think that's because the "fixAll" command also sorts/organises the imports.

That is the case in our setup, and is the expected behavior - however this bug appears even if `fixAll` _doesn't_ reorder the imports. The previous behavior was:

- `organizeImports` reorders the imports, but this may not match the code style enforced by Prettier.
- `fixAll` runs Prettier, which changes the code style: in our case, adding trailing commas to all multi-line imports.

This is the behavior mentioned in #98123. I consider this to be normal/expected (`organizeImports` probably shouldn't reformat code, only reorder the imports).

However as explained by @TriStarGod this now occurs in a cycle: it seems like `organizeImports` is executed again after `fixAll` writes the fixed changes to the file, which then breaks the ESLint rule again.

This is the new behavior in action:

https://user-images.githubusercontent.com/38614/200349370-7eded26f-ee00-456b-b10d-8d824ef65f78.mov

**Comment by mjbvz** [comment]
Thanks for the example repo @saramorillon

I believe you can work around this by setting `"files.refactoring.autoSave": false`

@jrieken The root cause is that autosave is being triggered during the code action's save participant. I'll look into suppressing this for code actions when saving

**Comment by migmit** [comment]
Thanks @mjbvz, that workaround works.

**Comment by jrieken** [comment]
This regressed with https://github.com/microsoft/vscode/commit/dc04246b0ae4e05fe9a429915de75a9880e5db7b

**Comment by jrieken** [comment]
Local repro case

* have a dummy extension with the two code action provider (below)
* have the setting as below
* save
* 🐛 endless quick fixes


**sample**
```ts
	vscode.languages.registerCodeActionsProvider('javascript', new class implements vscode.CodeActionProvider {
		provideCodeActions(document: vscode.TextDocument, range: vscode.Range | vscode.Selection, context: vscode.CodeActionContext, token: vscode.CancellationToken): vscode.ProviderResult<(vscode.CodeAction | vscode.Command)[]> {
			const result = new vscode.CodeAction('Insert 42', vscode.CodeActionKind.SourceFixAll.append('foo'));
			result.edit = new vscode.WorkspaceEdit();
			result.edit.insert(document.uri, new vscode.Position(0, 0), '// 42\n')
			return [result];
		}
	}, { providedCodeActionKinds: [vscode.CodeActionKind.SourceFixAll] })

	vscode.languages.registerCodeActionsProvider('javascript', new class implements vscode.CodeActionProvider {
		provideCodeActions(document: vscode.TextDocument, range: vscode.Range | vscode.Selection, context: vscode.CodeActionContext, token: vscode.CancellationToken): vscode.ProviderResult<(vscode.CodeAction | vscode.Command)[]> {
			const result = new vscode.CodeAction('Insert 47', vscode.CodeActionKind.SourceFixAll.append('foo'));
			result.edit = new vscode.WorkspaceEdit();
			result.edit.insert(document.uri, new vscode.Position(0, 0), '// 47\n')
			return [result];
		}
	}, { providedCodeActionKinds: [vscode.CodeActionKind.SourceFixAll] })
```

**setting**
```json
{
    "editor.codeActionsOnSave": {
        "source.fixAll.foo": true
    }
}
```

**Comment by jrieken** [comment]
Couple of observations and ways to fix this

* Save participation should be re-entrant - that's likely a bigger task for recovery (fyi @bpasero)
* The code action save participant should apply any workspace edit with the "ignore auto save"-flag (which already exists)
* We can revert the commit that introduced this (tho, that was done for a reason...)

**Comment by abdnafees** [comment]
I am still experiencing this problem for `python` files. What is the resolution?

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:38:50.881Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

**Comment by jrieken** [comment]
This will ship with 1.73`.1`

**Comment by WheelyWonka** [comment]
Thank you very much for the speeeeeedy action 🚀
