### ISSUE TITLE
Change CSV preview active filters to alternate color (Dark+)

### ISSUE THREAD

**Issue by markdomansky** [microsoft/vscode#165366]
As shown in the image below, filters are nearly impossible to discern.  Perhaps those could be changed to use the yellow color currently shown for files with problems or something like that.  I'd be open to changing this myself, but I'm having difficulty identifying the value for settings.json.

![image](https://user-images.githubusercontent.com/4317290/199733128-c7afd81e-b21f-47ca-98c7-656bc6acbf6f.png)

**Comment by aeschli** [comment]
There's no built-in support for csv. Do you use an extension? Can you file an issue against the extension?
