### ISSUE TITLE
close, minimize and maximize button are gone after today's update (1.74.0)

### ISSUE THREAD

**Issue by edwardchenchen** [microsoft/vscode#165337]
Does this issue occur when all extensions are disabled?: Yes/No

Version: 1.74.0-insider (user setup)
Commit: 86f0f9bfa268fe21af7efae37d8f0da1dba8137f
Date: 2022-11-03T05:36:55.498Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: Yes
![image](https://user-images.githubusercontent.com/6397192/199704064-680a320b-2532-4513-8335-2b75c0e2babc.png)

**Comment by furai** [comment]
It affects as well other distributions:
```
Version: 1.74.0-insider
Commit: 86f0f9bfa268fe21af7efae37d8f0da1dba8137f
Date: 2022-11-03T05:37:22.038Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.6-arch1-1
Sandboxed: Yes
```

**Comment by gjsjohnmurray** [comment]
`"window.experimental.windowControlsOverlay.enabled": true` fixes it for me.
