### ISSUE TITLE
Code is being commented out without the use of symbols to comment out code.

### ISSUE THREAD

**Issue by bennettbe** [microsoft/vscode#165363]
Does this issue occur when all extensions are disabled?: Yes/No
Yes it does.

- VS Code Version: 1.73.0
- OS Version: macOS Monterey
- Chip: Apple M1

Steps to Reproduce:

1. I uninstalled VS Code
2. I reinstalled VS Code
3. Start Extension Bisect
4. The Problem was there on the first bisect; "... This might be a problem with Code."

I included a couple screen shots of the issue.

Code looks like it is commented out without using the right symbols to comment it out. And only part of a line of code may be commented out. It's quite strange.

![Screen Shot 2022-11-03 at 9 51 40 AM](https://user-images.githubusercontent.com/87715493/199738770-6ad3772c-ea14-4a9d-9a24-d00ba9a9a039.png)
![Screen Shot 2022-11-03 at 9 54 41 AM](https://user-images.githubusercontent.com/87715493/199739498-1e255cd6-ad0b-4ae9-b128-a084de1cfd87.png)

**Comment by alexr00** [comment]
@bennettbe this is with C++? Can you share a copy/pastable example?

**Comment by bennettbe** [comment]
Also, when I open the code in another editor (Sublime, Notepad++) I do not get this issue.

**Comment by bennettbe** [comment]
I cannot post a pastable example since the code is for a company I am working for and it is not open source.

I will post two more photos though. The following are the end of a function.

Notice how in the first image the curly bracket on line 604 is commented out.
![Screen Shot 2022-11-03 at 10 23 20 AM](https://user-images.githubusercontent.com/87715493/199746464-51090e1b-278f-4a0a-bdfe-67faa81ff0fd.png)
Description: Image 1

But in the second image if I add the curly bracket to the end of line 603 the colors register correctly.
![Screen Shot 2022-11-03 at 10 23 35 AM](https://user-images.githubusercontent.com/87715493/199746536-e65fd5bd-e58d-419d-bfba-1ef515ca3d0f.png)
Description: Image 2

Then in the third image if I remove the comment on line 602 and add the curly bracket back to line 604 the colors register correctly but only if I remove that comment otherwise its the same as in the first image.
![Screen Shot 2022-11-03 at 10 24 42 AM](https://user-images.githubusercontent.com/87715493/199746829-6e293691-a1bc-4089-8bcf-3ffc0971e186.png)
Description: Image 3

Im not sure how much this gives you because you can't reproduce yourself but this is what I am working with.

**Comment by alexr00** [comment]
If you create a new file can you reproduce the issue with the following snippet?

```cpp
static test() {
#if 0 // line comment
	test( arg1 , arg2); // line comment
#endif
}
```

Usually for a bug like this there some line in the file that throws off all the following lines in some way, which is why I'm not able to reproduce it. The sample I pasted above doesn't repro the issue for me.

**Comment by alexr00** [comment]
Thanks for checking. That means there's something on one of the lines above where you're seeing the problem that is causing the problem. Without being able to see more of the file I don't have any clues as to what might be causing the problem though. If you're able to share more or narrow down the problematic earlier line please do add it to this issue so I can keep investigating.

**Comment by bennettbe** [comment]
@alexr00, Thank your for your help! Unfortunately I wont be able to share more code. Ill try cleaning up more comments on my end.
