### ISSUE TITLE
SFTP / FTP module

### ISSUE THREAD

**Issue by otto9due** [microsoft/vscode#165325]
Develop a system for uploading, downloading, comparing and synchronizing files on an sftp / ftp. The system should also handle code changes to git pushes and pulls.

**Comment by DEXTER251** [comment]
https://marketplace.visualstudio.com/items?itemName=Natizyskunk.sftp

**Comment by otto9due** [comment]
Software of this magnitude needs a proprietary module for ftp / sftp. I have tried many of these plugins but each has limitations. For example for loading git pulls and for sustainability over time etc ..
I have also seen online that this is a highly requested feature.

**Comment by otto9due** [comment]
This is a perfect plugin for most needs: Name: Deploy (reloaded), Visual Studio Marketplace: https://marketplace.visualstudio.com/items?itemName=mkloubert.vscode-deploy-reloaded
But the latest update dates back to a 22/9/2019.
