### ISSUE TITLE
Windows 11 New Context menu add "Open with Code"

### ISSUE THREAD

**Issue by jabed-dev** [microsoft/vscode#165378]
Feature added by VS Code Insider. But the VS Code is not added. I think it should be added to the VS Code.

**Comment by gjsjohnmurray** [comment]
1.73 release notes state:

> Due to issues we encountered during development of the menu entry, we plan to limit this feature to Insiders for a couple of milestones to gain confidence before we push it out to the Stable release for all Windows 11 users.

**Comment by deepak1556** [comment]
As stated above the feature will be limited to Insiders. We will add it to milestone plan when decision is made to make it available with Stable.
