### ISSUE TITLE
Terminal issue

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode#165310]
ADD ISSUE DESCRIPTION HERE
Nothing appears in the terminal window when I try to type in it. 
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
does updating your codespace fix the issue?

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAcceleration`
