### ISSUE TITLE
[BUG][1.73.0] (Markdown) Drag and drop to insert link inserts a document to system root relative path

### ISSUE THREAD

**Issue by ieteo** [microsoft/vscode#165352]
Does this issue occur when all extensions are disabled?: **Yes**
VS Code Version: 1.73.0

Related to this feature: https://code.visualstudio.com/docs/languages/markdown#_drag-and-drop-to-insert-links-and-images

**Issue**
Since the update to 1.73.0, when dragging file with Shift into editor it inserts bad path.

**Description**
Assume we have this structure in your project directory

```
index.md
images/image.png
```

Before the update, when dragging the` image.png `  from VS Code's explorer over to `index.md` opened in editor and holding the Shift, would insert following link:

`![](images/image.png)`

However, since the update to 1.73.0 it inserts this link:

`![Alt text](../../../../../../../../C:/Users/USERNAME/Workspace/PROJECT/DIR/DIR/DIR/images/image.png)`

Kind regards
Eteo

**Comment by mjbvz** [comment]
To repo, you need to be on windows and get VS Code into a state where the document and dropped files have differently cased drive letters: `c:\` vs `C:\`

This difference doesn't matter to windows itself, but was causing issues here. Not entirely sure how to force VS Code into this state though for verification

**Comment by contentedweb** [comment]
I downloaded VS Code Insiders (v1.74.0) and whilst there is a difference I now get this as the path:

```
![Alt text](..%5C..%5Cassets%5Cimages%5C20190825_150932.jpg)
```

Whilst the path works in the preview mode, it doesn't once the site has been built and the markdown converted to HTML.

**Comment by aeschli** [comment]
Verified that there's no longer a long path.The path is now `![Alt text](images%5Cimage.PNG).`

That works, but I think a forward slash `/` would be better. Created https://github.com/microsoft/vscode/issues/167824
