### ISSUE TITLE
Typescript language server crashes often and uses high CPU

### ISSUE THREAD

**Issue by danyx23** [microsoft/vscode#165301]
Type: <b>Bug</b>

This happens in the https://github.com/owid/owid-grapher/ repository which is a medium size typescript codebase. Hard to say what causes the crashes but for a few weeks now the TS language features have been crashing a lot

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.87GB (16.00GB free)|
|Process Argv|--crash-reporter-id 69391eff-09c9-4874-a8c6-b3b64d192c49|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i7-10870H CPU @ 2.20GHz (16 x 2207)|
|Memory (System)|50.10GB (43.63GB free)|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
spellright|ban|3.0.90
color-info|bie|0.7.0
docs-view|bie|0.0.11
emojisense|bie|0.9.1
mermaid-markdown-syntax-highlighting|bpr|1.5.0
vscode-dash|dee|2.4.0
vscode-firefox-debug|fir|2.9.8
vscode-graphql-syntax|Gra|1.0.4
vscode-peacock|joh|4.2.2
vscode-pyodide|joy|0.0.11
aml|mas|0.0.1
vscode-edge-devtools|ms-|2.1.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.255.4
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-bnf|Val|0.0.1
vscode-icons|vsc|12.0.1
vim|vsc|1.24.2
vscode-todo-highlight|way|1.0.5
devdocstab|Ana|1.0.1
vscode-json|and|1.5.2
markdown-mermaid|bie|1.15.2
sqlnotebook|cmo|0.6.0
vscode-jupytext|con|0.1.2
vscode-eslint|dba|2.2.6
devdocs|dei|0.2.0
gitlens|eam|13.0.3
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
copilot|Git|1.56.7152
vscode-pull-request-github|Git|0.54.0
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.219
prettier-sql-vscode|inf|1.4.0
vscode-sql-formatter|lea|2.1.6
restructuredtext|lex|189.2.0
vscode-autohotkey-plus-plus|mar|3.0.0
git-graph|mhu|1.30.0
isort|ms-|2022.4.0
python|ms-|2022.18.0
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vsliveshare|ms-|1.0.5750
emoji|Per|1.0.1
text-power-tools|qcz|1.37.0
inline-sql-syntax|quf|2.16.0
vscode-yaml|red|1.10.1
even-better-toml|tam|0.19.0
simple-rst|tro|1.5.2
json2yaml|tux|0.2.0
vscode-counter|uct|3.1.0
markdown-all-in-one|yzh|3.4.3

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30566498
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by danyx23** [comment]
@mjbvz that looks much better! I have used it for half a day now (with only the remote development extension as I am working in WSL on Windows) and I have not noticed any crashes. Thanks for your fast reply, much appreciated! Looking forward to the next release!
