### ISSUE TITLE
Allow stash only staged items in context menu

### ISSUE THREAD

**Issue by rhalaly** [microsoft/vscode#165353]
It can be helpful to have `Stash (Staged Only)` in the Git context menu, which uses the command `git stash push --staged`

<img width="478" alt="image" src="https://user-images.githubusercontent.com/8597700/199731235-4a99abf4-510c-4f6e-8386-1ff493e12e2d.png">

**Comment by joshuaobrien** [comment]
I'll work on this

**Comment by YalandHong** [comment]
I think it's dup of #149149 and has been fixed #169539

**Comment by lszomoru** [comment]
Closing as duplicate.
