### ISSUE TITLE
[documentation] Possible out of date information on package.json keywords

### ISSUE THREAD

**Issue by zeibura** [microsoft/vscode#165488]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: all
- OS Version: all

Steps to Reproduce:

1. Go to https://code.visualstudio.com/api/references/extension-manifest
2. Read description of the "keywords" field

I think this information that the `keywords` field is limited to five (which implies that any further keywords are not indexed by the search) is wrong or out of date. I have several extensions with more than five keywords and the search responds positively to all of them. Could this be checked or clarified?

**Comment by isidorn** [comment]
@zeibura thanks for opening this issue. It is correct that currently there is no limit in the number of keyword, but the Marketplace team is working on this and soon there will be the limit of 5. So those docs will be correct.
Closing as no action planned on the vscode side

fyi @prashantvc
