### ISSUE TITLE
Can't access my terminal

### ISSUE THREAD

**Issue by ariannam22** [microsoft/vscode#165443]
I was about to run my code and when I clicked on my terminal it is not letting me type anything in it. I tried refreshing the tab, restarting my computer and creating a new terminal. It started doing that after I ran a debug, could that be the reason why it's not working?

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
Turn off terminal.integrated.gpuAcceleration
