### ISSUE TITLE
Test diff editor indicators

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#16543]
#15371 

- [x] any os @weinand 

Complexity: 3

We use `+`/`-` indicators for modification in diff view in addition to Green/Red background colors.

Please verify

* These indicators are shown by default when you make additions and deletions.
* These indicators are still shown correctly when you *Switch to Side by Side View* or `Switch to Inline View`
* These indicators are not there when you set `diffEditor.renderIndicators` as `false`.

Please note you may run into an existing issue #15911 .

**Comment by ramya-rao-a** [comment]
Closing as the assigned testers are done testing
