### ISSUE TITLE
pasting code makes cell invisible on screen

### ISSUE THREAD

**Issue by yuuuxt** [microsoft/vscode#165415]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

to reproduce:
- (using a normal 1080p and font size 13, unknown zoom level but looks like original)
- create a notebook with 45 empty cells
- paste 150 lines of code in the 2nd cell on top

what happened: 
- the 2nd cell is invisible, the notebook is scrolled to the middle
- consequences: https://github.com/microsoft/vscode/issues/163943

expected: after pasting many lines of code in one cell, the cursor (inside current cell) should be visible in an appropriate position on screen, e.g. near button; instead of being invisible and causing problems.

![temp](https://user-images.githubusercontent.com/3153534/196638776-112a4c44-0c94-4691-a58a-3b116b5a787b.gif)

(if this issue belongs to vscode instead of vscode -jupyter, please help transfer, thx!)

### VS Code Version

1.72.2

### Jupyter Extension Version

2022.9.1202862440

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
I'm not seeing this anymore in latest Insiders.

**Comment by roblourens** [comment]
I still see this. Simply, paste a large amount of text into any cell, and the list scrolls down too far. If you still don't see it, I can debug it.

**Comment by rebornix** [comment]
Thanks @roblourens I can reproduce now, it seems once I can reproduce, it's super consistent.
