### ISSUE TITLE
There is an error after creating a "Python (Programming Model V2)" project in VS Code Insider

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode#165477]
**OS:** Win0
**Version:** 1.73.0-insider (user setup)

**Repro Steps:**
1. Install Azure Function and Python extensions in VS Code Insider.
2. F1 -> Azure Functions: Create New Project... -> Select a folder -> Select "Python (Programming Model V2)" language -> Select a Python interpreter -> Open in current window.
3. Check whether there is no error.

**Expect:**
There is no error.

**Actual:**
There is an error.
![image](https://user-images.githubusercontent.com/57662131/199945837-03be9476-a34b-400b-afda-43b02f6becc9.png)

**More Info:**
This issue doesn't reproduce in VS Code.

**Comment by aeschli** [comment]
Please file the issue against https://github.com/Microsoft/vscode-azurefunctions/issues
