### ISSUE TITLE
Terminal does not allow anything to be typed into it.

### ISSUE THREAD

**Issue by CatUnderTheNameOfA** [microsoft/vscode#165459]
Codespace demanded an update 2 days ago, I complied and since then the terminal is not responding. Terminal does not allow typing, I can "select" something in the terminal but not type or copy paste anything into it. Everything else (text editor, the activity bar on the left etc.) is working. Please advise, thank you.
Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Embedder: codespaces

**Comment by CatUnderTheNameOfA** [comment]
Solution: On the Activity Bar on the left side select "Manage" then click on "Settings". Find "Terminal > Integrated: Gpu Acceleration" then select "off". Should work now.

**Comment by meganrogge** [comment]
set `terminal.integrated.gpuAccleration` to off
