### ISSUE TITLE
Create a folder/file shortcut

### ISSUE THREAD

**Issue by GeorgVerg** [microsoft/vscode#165418]
I have been creating a lot of files recently so I searched for shortcuts. There aren't any that don't require mouse input. I think it would be better if there was a pop up where you can type the name of the file and the file extension. If there is no file extension treat it as a folder.

**Comment by lramos15** [comment]
You can set keybindings for these 
<img width="792" alt="image" src="https://user-images.githubusercontent.com/4544166/200400502-9d3928b1-842d-4216-94e3-3585df744091.png">

**Comment by GeorgVerg** [comment]
Thank you. For some reason in the UI keyboard shortcuts there was no such option, so I had to change it in the .json file. Now there is the option. Weird.
