### ISSUE TITLE
Task bar has overlapping icons after navigating back to notebook tab

### ISSUE THREAD

**Issue by olguzzar** [microsoft/vscode#165414]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

### What happened?

1. Export notebook as python script
2. After the generated script loads, close the file
3. When you are brought back to the tab with the notebook, the more actions three dots are overlapped by other icons in the task bar. This goes away when the user clicks anywhere, but causes some initial confusion.

While I repro'd using the python script exporting, the issue does not seem isolated to that, it happens almost every time I open another file in a tab, close it, and am brought back to the notebook tab. Recording of repro is [here](https://microsoft-my.sharepoint.com/:v:/p/olguzzar/EVL-B7USGmFFsGjyDYKXPzEBwYqSEwrTCQLm0UxyDA0cZg?e=xoKqMB) starting at 26:55

### VS Code Version

Version: 1.72.2 (user setup) Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075 Date: 2022-10-12T22:15:18.074Z Electron: 19.0.17 Chromium: 102.0.5005.167 Node.js: 16.14.2 V8: 10.2.154.15-electron.0 OS: Windows_NT x64 10.0.22621 Sandboxed: No

### Jupyter Extension Version

v2022.9.1202862440

### Anaconda Version (if applicable)

2022.05

### Running Jupyter locally or remotely?

Local

**Comment by rebornix** [comment]
let's merge it with https://github.com/microsoft/vscode/issues/151460
