### ISSUE TITLE
Add a scope for `variable.paramater` usages, in order to highlight use of parameter

### ISSUE THREAD

**Issue by MatteoGauthier** [microsoft/vscode#165483]
Hey, as described here https://stackoverflow.com/questions/50891160/textmaterules-for-parameters-and-parameter-usages-syntax-highlighting, it might be useful to highlight the `variable.parameter` in use.

Byee

**Comment by mjbvz** [comment]
This already exists using semantic highlighting: 

![Screen Shot 2022-11-04 at 1 23 22 PM](https://user-images.githubusercontent.com/12821956/200067605-620d3ba9-e285-4ec5-b703-42fc7db83a01.png)

Notice the semantic type of `message` is `parameter`
