### ISSUE TITLE
Comment view filtering: incorrect count (Showing x of y)

### ISSUE THREAD

**Issue by laurentlb** [microsoft/vscode#165444]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.73.0
- OS Version: Windows

In some cases (I don't know when exactly), the Comment filtering widget seems to display an incorrect count. Using vscode.dev, I've made this screenshot:

![image](https://user-images.githubusercontent.com/485572/199854677-fcf59e41-bfb8-4e8c-958b-e9f17b528494.png)

If I change the filters, I get different results:
* Show resolved and unresolved: `Showing 7 of 4`
* Show resolved, hide unresolved: `Showing 3 of 4`
* Hide resolved, show unresolved: no text
* Hide resolved and unresolved: `Showing 0 of 4`

All of them seem incorrect: there are 7 comment threads.

**Comment by alexr00** [comment]
Thanks for the clear repro!
