### ISSUE TITLE
Missing close, minimize and maxamize buttons. 

### ISSUE THREAD

**Issue by jtstogner** [microsoft/vscode#165405]
Type: <b>Bug</b>

After the most recent update code insiders the title bar buttons are missing.

VS Code version: Code - Insiders 1.74.0-insider (86f0f9bfa268fe21af7efae37d8f0da1dba8137f, 2022-11-03T05:36:55.498Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.74GB (33.63GB free)|
|Process Argv|--crash-reporter-id 3bd6763e-9448-479b-ae6c-4c31d7644e19|
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|2022.11.305
vscode-firefox-debug|fir|2.9.8
classic-asp-html|jtj|0.1.2
vscode-docker|ms-|1.22.2
csharp|ms-|1.25.0
dotnet-interactive-vscode|ms-|1.0.3552061
isort|ms-|2022.5.13061128
python|ms-|2022.19.13071014
vscode-pylance|ms-|2022.11.11
jupyter|ms-|2022.11.1003091113
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.263.0
remote-wsl|ms-|0.72.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931cf:30280410
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
vsccc:30564266
pyindex848cf:30577859
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
iaj6b796:30602301
pyind779cf:30600160

```

</details>

**Comment by jtstogner** [comment]
To note: if I change the title bar settings to native. The buttons reappear. This could be a temporary workaround for anyone who's encountering the same issue.

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/165337

**Comment by alexangria1992** [comment]
> To note: if I change the title bar settings to native. The buttons reappear. This could be a temporary workaround for anyone who's encountering the same issue.

Thank you!!
