### ISSUE TITLE
Test newly introduced Sublime commands

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#16545]
Test #15787 

- [x] Windows @weinand
- [x] macOS @bpasero 
- [x] Linux @aeschli 

Complexity 4

## Overview 
We received a bunch of feature requests for Sublime and Atom commands, which are tracked in #3776 and #14316. Now we added 4 of them this sprint.

### Join Lines
Verify

* If there is no trailing spaces in the first line, the leading spaces/tabs will be removed when we run Join Lines (ctrl+j). Besides, we'll put a single cursor between the content of first and second line, and the final cursor will be after the added single space.
* If there are trailing spaces in the first line, they will be removed when we run Join Lines.
* Select several lines, run Join Lines, make sure there are only one single space between the content of selected lines. Besides, the start or end of the selection doesn't change (means they are still on the same character).

### Transpose
We follow Sublime 3's behavior

Setup
* We don't assign keybindings for this command as the one ppl use in Sublime is already taken in Code by other commands. Add below config or whatever you like to your settings file.
```
{
    "key": "ctrl+t",
    "command": "editor.action.transpose"
}
```

Verify

* We can transpose space and tabs
* We can not transpose when the line is empty
* We can not transpose when the cursor is at the end of the line
* When the cursor is at the beginning of a line and the content of current line is not empty, running Transpose will just move the cursor to column 2 (1 based).

### Upper/Lower Case

Setup
* We don't assign keybindings for this command as the one ppl use in Sublime is already taken in Code by other commands. Add below config or whatever you like to your settings file.
```
{
    "key": "ctrl+u",
    "command": "editor.action.transformToUppercase"
},
{
    "key": "ctrl+l",
    "command": "editor.action.transformToLowercase"
}
```

Verify

* If there is selection, selected text are transformed to Upper/Lower case.
* If there is no selection and the cursor is inside a word, the word is transformed to Upper/Lower case.
* Cursor or selection doesn't change.

Please note that the boundary of a word is determined by the language mode.

**Comment by thekalinga** [comment]
Can the shortcut be added to toggle case along with upper and lowercase, as this makes life easier to have just one shortcut to toggle case.

Which is what IDEA follows
