### ISSUE TITLE
Test IME Composition

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#16547]
Test #16187

- [x] VSCode Windows - complexity 2 @aeschli 
- [x] VScode Mac - complexity 2 @sandy081 
- [x] VSCode Linux - complexity 4 @joaomoreno 
- [x] monaco-editor Windows Edge - complexity 2 @jrieken 
- [x] monaco-editor Windows IE11 - complexity 2 @isidorn 
- [x] monaco-editor Any OS Chrome 53 - complexity 2 @weinand 
- [x] monaco-editor Any OS Firefox 50 - complexity 2  @bpasero 

After we adopted the latest Chromium, ppl are seeing issues when they use IMEs which don't trigger selection change when compositing words.

Set up
For the verifier of Monaco, please follow https://github.com/Microsoft/vscode/issues/11146 to set up your machine.

Verify
* Go through our Test Plan for IME https://github.com/Microsoft/vscode/wiki/IME-Test . Especially Japanese and Korean which don't have any selection change while compositing words.
* Go through linked issues in https://github.com/Microsoft/vscode/issues/15765, such as https://github.com/Microsoft/vscode/issues/15896, https://github.com/Microsoft/vscode/issues/15772, https://github.com/Microsoft/vscode/issues/16353

**Comment by jrieken** [comment]
@rebornix I was unable to test the [`[Windows] Sogou pinyin Chinese input method`](https://github.com/Microsoft/vscode/wiki/IME-Test#windows-sogou-pinyin-chinese-input-method)-portion because the website has changed. Can you help me and update the guide?

**Comment by aeschli** [comment]
@jrieken http://cdn2.ime.sogou.com/80a3f06f5bae7a4c363a5dcd569c86e8/5846e768/dl/index/1478597239/sogou_pinyin_81c.exe is the link for the download.
