### ISSUE TITLE
"jsx" file associations setting not treated the same as "javascriptreact"

### ISSUE THREAD

**Issue by jedmao** [Microsoft/vscode#16546]
- VSCode Version: 1.7.2
- OS Version: Windows 10 Pro

## Steps to Reproduce

1. Use the following workspace settings:
```json
{
    "files.associations": {
        "*.js": "jsx"
    }
}
```
2. Run `npm install lodash`
3. Create the following file and name it "foo.js":
```jsx
import { pick } from 'lodash';

pick(         // <-- No Intellisense
```
4. Notice that there is no Intellisense after the open parentheses.

## Work-around

Change `jsx` to `javascriptreact` in the `files.associations` section of the workspace settings.

## Conclusion

What is the purpose of the `jsx` setting if it's not the same as `javascriptreact`? The mere existence of `jsx` is what was throwing me off.

**Comment by mjbvz** [comment]
Adding @bpasero 

I don't think this is JavaScript specific. From my investigation, I see that the JavaScript extension contributes the following language:

```json
"languages": [
	{
		"id": "javascriptreact",
		"aliases": [
			"JavaScript React",
			"jsx"
		],
		"extensions": [
			".jsx"
		],
		"configuration": "./language-configuration.json"
	}
]
```

But when resolving the file association, in the [language registry `getMimeForMode` function](https://github.com/Microsoft/vscode/blob/a5b7e16ab43e914b7420b02d205d7b61a61ec2bb/src/vs/editor/common/services/languagesRegistry.ts#L218), `this.mime2LanguageId` only seems to have top level language ids and not the aliases so we return `null` for  `"jsx"`. `this.lowerName2Id` does have the correct associations.

**Comment by bpasero** [comment]
+ @alexandrudima

**Comment by bpasero** [comment]
jsx is not a valid value for the setting and you can see that it does not show up in the list of available values:

![image](https://cloud.githubusercontent.com/assets/900690/21071902/4d068192-beb0-11e6-88a7-f718a4abc836.png)

Please just use intellisense to pick a value and be good with it.

**Comment by jedmao** [comment]
@bpasero I do use Intellisense to pick values in vscode 1.7.2:

![image](https://cloud.githubusercontent.com/assets/1058243/21071923/833632ba-be76-11e6-8185-9261d2283e8a.png)

I tried again in the insider's build, however, and `jsx` does not show.
