### ISSUE TITLE
Activity Bar drag and drop doesn't support dropping between items

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16541]
- VSCode Version: 1.8.0 Insiders
- OS Version: Windows

I initially thought the Activity Bar drag and drop was broken for Windows because I couldn't drag and drop an item between any other items. I tried to move the Extension item to be between File Explorer and Search and it just snapped back. Only after several minutes did I realize I have to drop the item over an existing item position. 
Also the affordance for a legal drop is also very subtle (slight background shading). I would have expected the drag and drop cursor to change from an "illegal" image (maybe circle with slash) to a "legal" image (current rectangle icon). 
You also cannot drag an item and place it in the empty region below the existing items.

**Comment by bpasero** [comment]
Things to do to improve this:
* [ ] allow to drop between 2 icons
* [ ] allow to drop to the very top or bottom to move it there
* [ ] draw a stronger drop feedback (e.g. also change cursor)

**Comment by bpasero** [comment]
Continues in https://github.com/Microsoft/vscode/issues/16799

I pushed fixes to allow to drop between 2 viewlets (before you could not) and you can now drop to the very top or below the last viewlet to move it there.

**Comment by gregvanl** [comment]
Dropping to the top and bottom works great but dropping between items is still confusing. It looks like the drop can be to either the top or bottom item but not really between.

**Comment by bpasero** [comment]
@gregvanl yes, that would be addressed with #16799 when you see where the drop operation ends up being.

I am feeling good for the DND for the viewlets because it is the exact same behaviour as tabs reordering, so people are already aware of how it works there.
