### ISSUE TITLE
Test highlight current line in gutter

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#16549]
Test #14273.

- any os @bgashler1 

complexity 1

Verify:
* Option `editor.renderLineHighlight` works when set as `gutter`, `none`, `line` and `all`
* When you select some characters, the text line is not highlighted even if you set `editor.renderLineHighlight` as `line` or `all`. This behavior is there for quite a while and we didn't touch it this time, but you may want to have it improved, see https://github.com/Microsoft/vscode/issues/16024.

Note you may see issues when using default light themes https://github.com/Microsoft/vscode/issues/15876, which would be fixed in following iteration.

**Comment by bgashler1** [comment]
LGTM
