### ISSUE TITLE
Terminal has no response to typing on Codespace

### ISSUE THREAD

**Issue by rongxin-liu** [microsoft/vscode#165416]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f)
- OS Version: Browser: Mozilla/5.0 (iPad; CPU OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/107.0.5304.66 Mobile/15E148 Safari/604.1

Steps to Reproduce:

1. Open iPad (iOS 15.7)
2. Run Chrome or Safari
3. Access Codespace
4. Tap on terminal and start typing

We had received many reports indicating having terminal issues (no response to typing) on Codespaces, and it seemed only Safari users were affected. Though I could not reproduce this issue on my macOS (12.6) running Safari (Version 16.0), I was able to reliably reproduce this issue on an iPad running both Safari and Chrome.

Concretely, when users start typing in the terminal, the terminal has no visual feedback as if it wouldn't take any user input. However, the terminal was still taking user input, and one could still execute commands (just all the texts typed in were "hidden")

Here is a recording of the issue:

https://user-images.githubusercontent.com/10591665/199815990-5f41bd5f-2484-4c0b-92be-790cbfed857e.MP4

I was typing commands such as `code hello.py` and `python3`, and the command would run, just no visual response on the terminal.

**Comment by rongxin-liu** [comment]
Related issues:
https://github.com/microsoft/vscode/issues/165381
https://github.com/microsoft/vscode/issues/165370
https://github.com/microsoft/vscode/issues/165338
https://github.com/microsoft/vscode/issues/165316
https://github.com/microsoft/vscode/issues/165310
https://github.com/microsoft/vscode/issues/165290

**Comment by meganrogge** [comment]
does changing `terminal.integrated.gpuAcceleration` help?

**Comment by meganrogge** [comment]
Also, are there errors in dev tools?

**Comment by rongxin-liu** [comment]
> does changing `terminal.integrated.gpuAcceleration` help?

Turning off `terminal.integrated.gpuAcceleration` did address the issue.

**Comment by meganrogge** [comment]
depending on the safari version, gpu acceleration is unsupported

related https://github.com/microsoft/vscode/issues/133710

**Comment by rongxin-liu** [comment]
Some Chrome users also ran into the same issues on their devices. Turning off GPU acceleration for the terminal seemed okay for now.

**Comment by dascope** [comment]
Thanks @meganrogge. FYI it worked fine on iPad Air (4th Gen) iOS 14.6 until two days ago, with gpu acceleration enabled. Disabling gpu acceleration now fixes it on this device as well.

**Comment by meganrogge** [comment]
We should investigate if there's a way to check browser IE safari and version IE 15 and if so, disable gpu acceleration

**Comment by jeanp413** [comment]
isn't this handled by this already :thinking: 
https://github.com/microsoft/vscode/blob/73416439d9d9cde7f54e727853a59ab89edd99ee/src/vs/workbench/contrib/terminal/browser/xterm/xtermTerminal.ts#L326-L328

**Comment by Tyriar** [comment]
I believe this is fixed with the last xterm update, if not it will be in the one today when it's updated for https://github.com/microsoft/vscode/issues/166158

**Comment by RexBlock** [comment]
> Turning off `terminal.integrated.gpuAcceleration` did address the issue.

Where is this setting applied? 

Thanks.

**Comment by Tyriar** [comment]
@RexBlock https://code.visualstudio.com/docs/getstarted/settings
