### ISSUE TITLE
Display webp images

### ISSUE THREAD

**Issue by riderx** [microsoft/vscode#165457]
Webp image is a format dedicated for web usage and not able to display it in vscode seems a bit odd since it's the favorite IDE for webdev.
https://developers.google.com/speed/webp
https://caniuse.com/webp
The format is well-supported in browser and OS

**Comment by gsrbr** [comment]
Hello @riderx , I'm using vscode and it was able to open/show `webp` and `webm` without any problems
![2022-11-04 09-40-58](https://user-images.githubusercontent.com/27559775/199975337-da10f8d1-f82a-46ee-acf5-b8cd9e61f606.gif)
The extension **media-preview** is bundled with Visual Studio Code(It can be disabled but not uninstalled) and it can show a lot of files types, you can see the list here -> https://github.com/microsoft/vscode/tree/main/extensions/media-preview

My vscode info(pt-br): 
Versão: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Data: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
SO: Windows_NT x64 10.0.19045
Em área restrita: No

**Comment by mjbvz** [comment]
Webp also works for me

@riderx If this isn't working for you, please share some example images so I can test those

**Comment by riderx** [comment]
Sorry guys i don't understand, today all webp works well, i don't understand. seems i was living in parallel world and just come back today ^^
