### ISSUE TITLE
[css] calc() is not in IntelliSense or syntax highlight 

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1654]
calc is not included in css.plist so it is not coloured:

![screen shot 2015-12-25 at 7 36 57 pm](https://cloud.githubusercontent.com/assets/465069/12005036/16603be0-ab3f-11e5-98aa-46c835bfb7f2.png)

(no values are coloured in latest Dec update but that is a different issue.)

It is also not included in the auto complete suggestions. (although as a by product of lengths being valid values, at least those parts get Intellisense inside the brackets)

" It can be used wherever &lt;length>, &lt;frequency>, &lt;angle>, &lt;time>, &lt;number>, or &lt;integer> values are allowed. " – http://www.w3.org/TR/css3-values/#calc-notation

**Comment by aeschli** [comment]
This got fixed in the meantime.
