### ISSUE TITLE
createTerminal with customization not working properly

### ISSUE THREAD

**Issue by Maiquelrd** [microsoft/vscode#165407]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.73.0
- OS Version: Windows 11

Some time ago you added this feature: https://github.com/microsoft/vscode/pull/128856

It worked fine for a while but early this year VSCODE updated adding the feature to have default color and icon for new terminals and since it the createTerminal function using vscode API doesnt work properly, It seems like the customisations are applied at first I can see my customization for 0.5 seconds but then it be overruled by the default values in my settings.

**Comment by meganrogge** [comment]
pls provide me with your settings.json file and a gif would be helpful

**Comment by Maiquelrd** [comment]
Hello, im using the vscode api to debug an extension.

When I run the command to create the terminals using the vscode api createTerminal function this is what happens:

![ezgif-3-e953971386](https://user-images.githubusercontent.com/40647363/199862055-587dba49-a9f7-4756-bbff-a8f602874772.gif)

You can see that for a moment it the second terminal have the "terminal.ansiGreen" color but it is replaced for the default one in vscode settings.

When I console logged the terminal I saw that it was firstly created as it should have:

![image](https://user-images.githubusercontent.com/40647363/199861809-8e2a1fe5-ffee-4629-9149-fb0b70d447c9.png)


I cant upload my settings.json (im new at this) but the settings that I think is having the conflict is this one:

![image](https://user-images.githubusercontent.com/40647363/199862482-1250f648-1b40-43cd-b923-c2715c5382ea.png)

**Comment by joshuaobrien** [comment]
👋 I'm happy to take a look at this
