### ISSUE TITLE
Can not type anything in the terminal window 

### ISSUE THREAD

**Issue by TombCrawler** [microsoft/vscode#165569]
ADD ISSUE DESCRIPTION HERE

I am able to edit codes in the text editor but can not type anything in the terminal window that only shows $.
What should I do?

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Embedder: codespaces

<!-- g

<img width="604" alt="Screen Shot 2022-11-05 at 8 09 41" src="https://user-images.githubusercontent.com/106455150/200090604-4b6ee792-f2ad-4fcd-ad25-96eecce810a8.png">

**Comment by meganrogge** [comment]
Turn off terminal.integrated.gpuAcceleration
