### ISSUE TITLE
files.insertFinalNewline should Not Move Cursor to New Line

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16557]
- VSCode Version: 1.8 insiders 2016-12-05T07:03:07.371Z
- OS Version: OSX

**Steps to Reproduce**

1. Add setting for  `"files.insertFinalNewline": true` 
2. Create blank file
3. Type `a` on first line.
4. Save file.

**Expected**
Newline inserted and cursor remains on the same line at the end of `a`

**Actual**
![dec-05-2016 17-16-38](https://cloud.githubusercontent.com/assets/12821956/20909129/9944f16a-bb0e-11e6-8ba4-b8d74af9db95.gif)

On each save when a new line is added, the cursor moves to the last line.

**Comment by mjbvz** [comment]
This is particularly annoying with `"files.autoSave"`

**Comment by bpasero** [comment]
@mjbvz up for debate I would say. Here is what Sublime does:

![view-picker](https://cloud.githubusercontent.com/assets/900690/20914203/42d67a68-bb7e-11e6-9e42-c57830be7866.gif)

Here is what editor config extension does:

![view-picker](https://cloud.githubusercontent.com/assets/900690/20914219/58766806-bb7e-11e6-9207-902b0c30fa0b.gif)

The latter solves your issue but at first I thought it is a bug that saving results in a selection like that. 

Would like to hear more from others before making a move.

**Comment by jrieken** [comment]
I agree with @mjbvz and think this is bad

**Comment by bpasero** [comment]
@jrieken would you expect the cursor to just stay or do what editorconfig does?

**Comment by jrieken** [comment]
stay
