### ISSUE TITLE
in full screen mode menus cannot be opened

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#165544]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. install vscode on fedora
2. open vscode
3. switch to fullscreen (f11)
4. type alt, menu appears but click on help closes it
5. type alt+h, menu appears but closes

**Comment by rzhao271** [comment]
Related: #159852

**Comment by rzhao271** [comment]
I am unable to reproduce this issue on the latest [Insiders](https://code.visualstudio.com/insiders) on CentOS 7. Does this issue still occur for you?
If yes, which version of Fedora are you using?

**Comment by theking2** [comment]
Apparently this was repaired. On the version 1.74.0 and the current Fedora 37 this no longer happens.
