### ISSUE TITLE
github cloning not working on fedora

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#165548]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

[Screencast from 04-11-22 18:36:28.webm](https://user-images.githubusercontent.com/1612152/200060700-ab46900b-d02f-4b97-a4dd-dae7f5c9db05.webm)

**Comment by theking2** [comment]
the file location dialog is not appearing. It only appears while devtools are open or the vscode window is not full screen.

**Comment by theking2** [comment]
The specifc problem with fedora is that the select folder dialog stays under the main window and is not accesible.
This happenes if no other windows are open or have focus. Even when the screen recorder is running the select folder dialog _does_ appear. Also with Devtools on the problem does not appear. It is not possible to record this issue. 

Install F36, install vscode and attempt to clone

**Comment by theking2** [comment]
[Screencast from 04-11-22 18:51:52.webm](https://user-images.githubusercontent.com/1612152/200063183-7d836952-bef8-4329-8db1-cc41bfa1145c.webm)

**Comment by lszomoru** [comment]
@theking2, does the same happen with other "file location" dialogs opened by VS Code?

**Comment by kingma-sbw** [comment]
Not sure, will test.

**Comment by theking2** [comment]
Yes. the file open Ctrl+o dialog also pops under the main window and is not visible or directly accessible.

**Comment by lszomoru** [comment]
@deepak1556, are you aware of any known issues related to the open file dialog on fedora?

**Comment by theking2** [comment]
Just tested on F37 and vscode 1.74.0 it still happens like in the video

**Comment by deepak1556** [comment]
Yup this has the same cause as https://github.com/microsoft/vscode/issues/146422, merging.
