### ISSUE TITLE
Test: Selection menu

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16558]
#15156 

- [x] Windows @weinand 
- [x] macOS @bpasero 
- [x] Linux  @aeschli

Complexity: 2

- Check the new Selection menu makes sense
- Check the entries run the corresponding commands
- Check that simple keybindings are shown after the label (complex ones do not)
- Do the above for the 2 Edit > Toggle (Block) Comment and 2 Edit > Emmet commands

**Comment by ramya-rao-a** [comment]
Closing as the assigned testers are done testing
