### ISSUE TITLE
Python `('{}')` highlighted even when not f-string

### ISSUE THREAD

**Issue by Rudxain** [microsoft/vscode#165571]
Type: <b>Bug</b>

If a Python file/script contains the following literal:
```python
('{}()[]')
```
the `{}` is colored, but not `()[]`. This also happens if the parentheses don't encode a tuple, like here:
```py
set('{}()[]')
```

I enabled and disabled all extensions, and this happens anyways in both cases

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:44:09.336Z)
OS version: Linux x64 5.15.0-52-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2757)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.50GB (13.86GB free)|
|Process Argv|/home/rudxain/Documents/GitHub/rickroll-lang --crash-reporter-id ba7811b0-8267-4f37-9fbb-6e9dd767cf0f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30566498
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce2:30602635
3d0df643:30602300

```

</details>

**Comment by alexr00** [comment]
Upstream issue is here: https://github.com/MagicStack/MagicPython/issues/245

**Comment by Rudxain** [comment]
> Upstream issue is here: [MagicStack/MagicPython#245](https://github.com/MagicStack/MagicPython/issues/245)

Thank you for the link
