### ISSUE TITLE
Settings editor More Actions menu clipped

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#165518]
Does this issue occur when all extensions are disabled?: Yes
- VS Code Version: 1.73.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open Settings Editor
2. Filter list by Modified
3. Click More Actions gear button to see context menu.

The context menu is clipped.

![image](https://user-images.githubusercontent.com/12818376/200033354-0bcb5f9e-98bd-47e5-85e2-df306cfc2269.png)

**Comment by rzhao271** [comment]
My fix for https://github.com/microsoft/vscode/issues/164602 didn't generalize.
Repro steps:
1. Search "auto" in the Settings editor
2. Click on "Formatting" in the table of contents to filter it down to two settings
3. Click on the gear icon of the second setting
