### ISSUE TITLE
suggestWidgetMultipleSuggestions does not seem to be updated correctly

### ISSUE THREAD

**Issue by xconverge** [Microsoft/vscode#16553]
- VSCode Version: 1.7.2 or insiders as of today
- OS Version: win10 x64

There seems to be an issue with suggestWidgetMultipleSuggestions.

I am trying to use the following:

{
        "key": "down",
        "command": "extension.vim_down",
        "when": "editorTextFocus && !suggestWidgetMultipleSuggestions"
}

The key is registered correctly up until a suggestion is shown, then it is not correct until vscode is restarted. I tried it without only suggestWidgetMultipleSuggestions and the issue still occurred so I believe that suggestWidgetMultipleSuggestions is the problem.

If I had to make a guess, I would guess that it needs the value to be changed back to 0 in hide() here

https://github.com/Microsoft/vscode/blob/6b0195da05089170f904f16131cc60b2d462f90d/src/vs/editor/contrib/suggest/browser/suggestWidget.ts#L691

This is causing an issue in Vim where we are using it https://github.com/VSCodeVim/Vim/issues/1054

**Comment by joaomoreno** [comment]
Want to submit a PR for it?

At the same time, you should probably use `editorTextFocus && !suggestWidgetVisible`  instead.

**Comment by xconverge** [comment]
I will try to build from source tonight, we also use suggest widget visible but it is important for us to have both for a few reasons
