### ISSUE TITLE
Keyboard shotcut "Ctrl+." not working.

### ISSUE THREAD

**Issue by DiscreteTom** [microsoft/vscode#165592]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 
  - Version: 1.73.0 (user setup)
  - Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
  - Date: 2022-11-01T15:34:06.111Z
  - Electron: 19.0.17
  - Chromium: 102.0.5005.167
  - Node.js: 16.14.2
  - V8: 10.2.154.15-electron.0
  - OS: Windows_NT x64 10.0.22621
  - Sandboxed: No
- OS Version: Windows 11 Home 22H2

Steps to Reproduce:

1. Press "Ctrl+.", and it's not working.

More information:

- Other keyboard shortcut works as expected. Only "Ctrl+." not working.
- I opened Dev Tools and listen to keyboard events by `window.addEventListener('keydown',e=>console.log(e))`, then press "Ctrl+.", only `Ctrl` is detected, no `.`. If I press `.` only, the `.` can be detected.
- I also tried the above event listeners in Edge browser and press "Ctrl+.", both `Ctrl` and `.` can be detected, so my keyboard hardware should be fine.
- I re-installed VSCode and still not working.

**Comment by DiscreteTom** [comment]
Tested in the insider version (1.74.0), still not working.

**Comment by DiscreteTom** [comment]
Tested in browser environment (https://github.dev), the event listener still can't detect `.` after `ctrl`. But in other web pages within the same PC and browser (Edge), both `Ctrl` and `.` can be detected.

I also tried this in another PC, both VSCode desktop and github.dev (Edge/Chrome) works fine...

**Comment by samyarkd** [comment]
![image](https://user-images.githubusercontent.com/75088294/200156126-1cf950db-ed9c-4d24-bad5-720eee0c0842.png)
working fine by me on Windows 10
Ctrl + .

Pops up a quick fix window

**Comment by DiscreteTom** [comment]
It turns out that the IME "Microsoft Pinyin" has a hot key "Chinese/English punctuation switch" which blocks the "Ctrl + period" input.

Closed, thanks for the help.
