### ISSUE TITLE
Change "Explorer view" back to side panel

### ISSUE THREAD

**Issue by Noodle-Bug** [microsoft/vscode#165507]
Type: <b>Feature Request</b>

Currently when right clicking on a file tab, there are two options grouped together for navigating to the file:

- Reveal in File Explorer
- Reveal in Explorer View

the "Explorer View" option used to be called "Reveal in Side Panel" (or something along those lines) which made it very easy to distinguish at a glance. As it is now, I am constantly choosing the wrong option when all I want to do is highligh the file in the side panel. The names are similar enough that it takes a second or so of comparing the names to know which one I actually want. Not sure why this menu option was changed, but it would be much appreciated to have it be its original (more descriptive) name

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: No

**Comment by gjsjohnmurray** [comment]
See #145765 for reasoning behind this change, which happened back in March 2022.

**Comment by lramos15** [comment]
As indicated by @gjsjohnmurray's comment. No plans to address this in the near future.

**Comment by Noodle-Bug** [comment]
I understand the reason for the name change, but do both options really have to be called "Explorer"? Is there no other option for differentiation?

**Comment by gjsjohnmurray** [comment]
> Is there no other option for differentiation?

If you switched to the Mac platform I think it'll be labelled Finder 😄

**Comment by Zingam** [comment]
Just use Linux :)

**Comment by Noodle-Bug** [comment]
> Just use Linux :)

Not an option on work PC, and for personal PC... I like to do things 😛
