### ISSUE TITLE
Replace preview: 'Could not resolve any model with uri ...'

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16554]
- Open the find viewlet
- Type anything into the find and replace input boxes
- Press enter, get some results
- Click any result

Error popup: `Unable to open 'less.tmLanguage.json ↔ less.tmLanguage.json (Replace Preview)': Could not resolve any model with uri 'private:/Users/roblou/code/vscode/extensions/less/syntaxes/less.tmLanguage.json#preview'`

I don't think this would be related to my changes since results should come back in exactly the same format. The error seems to originate from `EditorPart.doSetInput` calling `editor.setInput` and failing.

**Comment by roblourens** [comment]
![image](https://cloud.githubusercontent.com/assets/323878/20908628/f3a6fd00-bb0a-11e6-8fef-83753fdd1c92.png)

**Comment by colameo** [comment]
I'm writing an extension to preview a model (DSL) in a UML preview window. Every time an exception happens (e.g. the user opens a text file which is not the expected DSL), the error above appears and then it seams that vs code cannot recover anymore. Even when everything should work correctly, the exception is raised and the extension seams not to work anymore correctly. Looks like an issue to me...
