### ISSUE TITLE
Close minimize and restore buttons are missing

### ISSUE THREAD

**Issue by amirtharajanpks** [microsoft/vscode#165508]
Type: <b>Bug</b>

Close, restore and minimize button on top right are missing

VS Code version: Code - Insiders 1.74.0-insider (86f0f9bfa268fe21af7efae37d8f0da1dba8137f, 2022-11-03T05:36:55.498Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.92GB (57.22GB free)|
|Process Argv|--crash-reporter-id 2f85e303-43cc-4612-a082-e5277583e6bc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|14.2.0
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
beautify|Hoo|1.5.0
vscode-graphviz|joa|0.0.6
my-vscode-hybris-tools|leo|1.1.11
code-groovy|mar|0.1.2
rainbow-csv|mec|3.2.0
vscode-hybris-tools|moj|0.4.0
compare-folders|mos|0.22.3
vscode-docker|ms-|1.22.2
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.5.13061128
python|ms-|2022.19.13071014
vscode-pylance|ms-|2022.11.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.263.0
remote-wsl|ms-|0.72.0
cpptools|ms-|1.12.4
vscode-typescript-next|ms-|5.0.20221103
material-icon-theme|PKi|4.21.0
vscode-jsp|pth|0.0.3
fabric8-analytics|red|0.3.6
vscode-community-server-connector|red|0.25.7
vscode-rsp-ui|red|0.23.13
vscode-xml|red|0.22.0
impex-support|sim|0.2.5
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.46.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.6
vscode-maven|vsc|0.39.2
vscode-spring-initializr|vsc|0.11.1
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256198
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pylantcb52:30590116
vscccc:30564267
pyindex848cf:30577859
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
3d0df643:30602300
pyind779:30600159

```

</details>

**Comment by gjsjohnmurray** [comment]
Please update your Insiders
