### ISSUE TITLE
f11 assigned wrongly to debugger

### ISSUE THREAD

**Issue by theking2** [microsoft/vscode#165546]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. type f11, debugger starts

F11 should go to full screen according to the menu hints

**Comment by theking2** [comment]
![Screenshot from 2022-11-04 18-22-04](https://user-images.githubusercontent.com/1612152/200058532-7736e028-ab0b-483f-b5dc-5912a5445c1a.png)
![Screenshot from 2022-11-04 18-22-48](https://user-images.githubusercontent.com/1612152/200058547-c875e846-c9f5-4daa-8085-e4afef5d8015.png)

**Comment by gjsjohnmurray** [comment]
Does this happen after running the command to reload with all extensions disabled?

Does it only happen when you have selected Run & Debug view on the Activity Bar?

**Comment by theking2** [comment]
I don't know. This was a fresh installation on Fedora but I did sync it with my account so extensions were enabled, particularly PHP Debug.

**Comment by roblourens** [comment]
PHP Debug seems to contribute this keybinding, active when a php debug config is selected: 
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/323878/200442160-6dbb5134-c91a-4436-8cf0-95f704dfbd58.png">

would be great if you could file an issue on their repo about that. The version of this command from the builtin node debug extension should only activate when the debug view is focused and node is selected: `!inDebugMode && activeViewlet == 'workbench.view.debug' && debugConfigurationType == 'node' || !inDebugMode && activeViewlet == 'workbench.view.debug' && debugConfigurationType == 'pwa-extensionHost' || !inDebugMode && activeViewlet == 'workbench.view.debug' && debugConfigurationType == 'pwa-node'`
