### ISSUE TITLE
Confused by 3-way merge, close with conflict cancel action.

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#165512]
I'm a bit confused by the three way merge experience still. 

I see this presented to me when I think I'm done 
<img width="314" alt="image" src="https://user-images.githubusercontent.com/4544166/200015743-59a63639-15b3-4f27-8c5e-f448e06e3c23.png">
but I have a hard time identifying what conflicts are left and clicking cancel here just proceeds to the next file I need to merge anyways.

**Comment by hediet** [comment]
What did the conflict counter say just before this?

**Comment by lramos15** [comment]
There was an additional conflict left (it was lower in the page). I think what surprised me is clicking cancel here doesn't keep you on the same document so you can address the conflict

**Comment by hediet** [comment]
>  I think what surprised me is clicking cancel here doesn't keep you on the same document so you can address the conflict

It works like that (well, it should):

![Code_-_Insiders_d9tGKuTUEr](https://user-images.githubusercontent.com/2931520/200300669-2b27434a-2bd6-485e-b984-ffce1e39ff3d.gif)

**Comment by lramos15** [comment]
I was clicking complete merge and not actually closing the document. I will see if I can get a gif next time I run into a merge conflict.
