### ISSUE TITLE
Configure debugger shows duplicate Node entries

### ISSUE THREAD

**Issue by timheuer** [microsoft/vscode#165555]
I created an app using `create-react-app` and then went to Run menu to start debugging.  Because there was no launch/task files it asked me to configure the debugger...I was then presented with this:

![image](https://user-images.githubusercontent.com/4821/200069729-645f668d-4680-47d0-aa01-8948485ac2c0.png)

Duplicate Node.js entries or at least duplicate appearing to me.  Neither worked by the way.

**Comment by connor4312** [comment]
I do not see this locally. What extensions do you have installed?

**Comment by timheuer** [comment]
<html>
<body>


Extension | Author (truncated) | Version
-- | -- | --
better-comments | aar | 3.0.2
npm-intellisense | chr | 1.4.2
path-intellisense | chr | 2.8.1
vscode-github-actions | csc | 0.24.4
vscode-eslint | dba | 2.2.6
npm-browser | den | 1.1.4
gitlens | eam | 13.0.4
EditorConfig | Edi | 0.16.4
vscode-solution-explorer | fer | 0.7.4
azure-storage-explorer | for | 0.1.2
visual-nuget | ful | 0.2.1
copilot | Git | 1.58.7236
remotehub | Git | 0.46.0
vscode-pull-request-github | Git | 0.54.0
vscode-test-explorer | hbe | 2.21.1
rest-client | hum | 0.25.1
vscode-nuget-package-manager | jmr | 1.1.6
vscode-peacock | joh | 4.2.2
fluent-ui-vscode | lea | 3.8.0
fluent-icons | mig | 0.0.18
lipsum-generator | MrA | 1.2.3
azure-pipelines | ms- | 1.208.0
azure-dev | ms- | 0.3.0
vscode-azureappservice | ms- | 0.24.5
vscode-azurefunctions | ms- | 1.8.3
vscode-azureresourcegroups | ms- | 0.5.6
vscode-azurestaticwebapps | ms- | 0.11.3
vscode-azurestorage | ms- | 0.15.0
vscode-azurevirtualmachines | ms- | 0.6.2
vscode-bicep | ms- | 0.12.40
vscode-cosmosdb | ms- | 0.19.2
vscode-docker | ms- | 1.22.2
csharp | ms- | 1.25.0
vscode-dotnet-pack | ms- | 1.0.9
vscode-dotnet-runtime | ms- | 1.6.0
vscode-dotnet-sdk | ms- | 0.8.0
vscode-edge-devtools | ms- | 2.1.1
data-workspace-vscode | ms- | 0.3.0
mssql | ms- | 1.16.0
playwright | ms- | 0.2.13
python | ms- | 2022.18.1
azure-deploy | ms- | 1.2.4
remote-containers | ms- | 0.262.3
remote-wsl | ms- | 0.72.0
azure-account | ms- | 0.11.2
azurecli | ms- | 0.5.0
github-issues-prs | ms- | 0.9.3
js-debug-nightly | ms- | 2022.10.1817
powershell | ms- | 2022.10.0
remote-repositories | ms- | 0.24.0
test-adapter-converter | ms- | 0.1.6
vsliveshare | ms- | 1.0.5762
azurerm-vscode-tools | msa | 0.15.8
vscode-jest | Ort | 4.6.0
polacode | pnp | 0.3.4
quicktype | qui | 12.0.46
vscode-rapidapi-client | Rap | 1.7.0
java | red | 1.12.0
vscode-yaml | red | 1.10.1
csharp-test-adapter | sam | 1.1.1
vscode-react-scripts-test-adapter | sma | 0.1.2
dotnet-containerizer | Tim | 0.0.15
intellicode-api-usage-examples | Vis | 0.2.6
vscodeintellicode | Vis | 1.2.29
application-insights | Vis | 0.4.2
vscode-java-debug | vsc | 0.46.0
vscode-java-dependency | vsc | 0.21.1
vscode-java-pack | vsc | 0.25.6
vscode-maven | vsc | 0.39.2
vscode-icons | vsc | 12.0.1


</body>
</html>

**Comment by timheuer** [comment]
It was not.  I disabled nightly, but have no idea how I got nightly?  I'm not running insiders.
