### ISSUE TITLE
Dependencies classification in ThirdPartyNotices.txt?

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode#165559]
The auto generated ThirdPartyNotices.txt is really helpful, when it comes to seeing at once all third party dependencies . But I wonder now if all these are really runtime dependencies of vscode, or, if some are there due other reasons like example code, building utilities, document generation, etc. Could be possible to know which ones are truly runtime dependencies?

Thank you.

**Comment by dariomx** [comment]
Hello folks,

Any news about this? I asked a similar question on the remote - ssh repo: 

https://github.com/microsoft/vscode-remote-release/issues/7379

But felt more chances of getting an answer here, given the tool to collect the dependencies may be generic across several products. 

Thanks in advance.

**Comment by dariomx** [comment]
Hello there,

The other question I asked to Remote - SSH extension got answered:

https://github.com/microsoft/vscode-remote-release/issues/7379

they said that all the dependencies on the file are indeed runtime dependencies. Is this something we can extend to any ThirdPartyNotices.txt generated by the mentioned internal tool?

Thanks.

**Comment by dariomx** [comment]
Nok nok, any update on the latest question?

Thanks.

**Comment by alexdima** [comment]
Hi, there are two distinct `ThirdPartyNotices.txt` files.
* There is a `ThirdPartyNotices.txt` file which you will find [at the root of this repository](https://github.com/microsoft/vscode/blob/main/ThirdPartyNotices.txt). This one contains notices for 3rd party software that is cloned on your machine together with the vscode repository (i.e. 3rd party software that is inlined in the vscode repository)
* There is a `ThirdPartyNotices.txt` file which you will find inside the VS Code installation directory. I can't link to it because it is only present in the product install dir. This one contains notices for 3rd party software that is included with VS Code at runtime, on your machine. There are also other files called `LICENSE.rtf` and `LICENSES.chromium.html` that contain notices for more 3rd party software that is included with VS Code at runtime:
* <img width="414" alt="image" src="https://user-images.githubusercontent.com/5047891/204059695-8e5325f6-c81c-4e6c-b9ef-aa3ec8252b83.png">

Please let us know if this answers your question.

**Comment by dariomx** [comment]
Hi Alexandru,

Thanks a lot for the information. If I understand correctly, it looks like the local ThirdPartyNotices.txt contains the repo one as a subset; then we can focus on that local ThirdPartyNotices.txt along with the other LICENSES.chromium.html (putting aside the LICENSE.rtf, as that is for vscode itself not for dependencies).

Using as context those two local files that come with the installation, ThirdPartyNotices.txt along with the other LICENSES.chromium.html, I can reframe my question: you have stated already that they both contain license/notices for runtime dependencies of vscode on my machine. The question though, is whether in addition to those runtime dependencies, they mention any other type of dependency. These could be, just to provide some examples: build tools, documentation generation tools, libraries used in examples, unit-test frameworks, etc. 

In other words, I want to know if those license files really restrict to runtime dependencies or whether they also contain other types of dependencies which are normally part of the development cycle (build, testing, release management, etc). That is important to me because, in order to evaluate whether I can use vscode for a project, I need to review "individually" each one of those third-party licenses. That is a lot of work, as you can imagine; therefore, I would like to discard any license which may be used just internally as part of the development cycle but that is not really required at runtime. There is no way I can distinguish among the two, just by looking at these files; hence my request for help on this ticket. If there are no licenses like that and all these truly represent runtime dependencies, a confirmation of that would suffice to my purposes.

Thank you in advance and happy holidays.

**Comment by alexdima** [comment]
> Using as context those two local files that come with the installation, ThirdPartyNotices.txt along with the other LICENSES.chromium.html, I can reframe my question: you have stated already that they both contain license/notices for runtime dependencies of vscode on my machine. The question though, is whether in addition to those runtime dependencies, they mention any other type of dependency. These could be, just to provide some examples: build tools, documentation generation tools, libraries used in examples, unit-test frameworks, etc.

* The `ThirdPartyNotices.txt` file in the install dir is generated by us (VS Code). It contains notices only for runtime dependencies. There are no notices in there for development only dependencies.

* The `LICENSES.chromium.html` file in the install dir is generated by Electron / Chromium and we just make sure to ship it too. My understanding is that it also contains only notices for runtime dependencies. But it is not generated by us, so I can't say for certain, maybe you can clarify that with [Electron maintainers](https://github.com/electron/electron).

**Comment by dariomx** [comment]
Thank you so much, Alexander. We can close this ticket.
