### ISSUE TITLE
Screen shifts when maximised

### ISSUE THREAD

**Issue by rachit-ranka** [microsoft/vscode#165647]
Type: <b>Bug</b>

when i maximise my window in ubuntu the screen shifts slightly towards right and the top menu bar which shows the time and notification hides. when i press ctrl or go to any drop down menu it fixes for a sec and then goes back to how it was earlier. 

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:44:09.336Z)
OS version: Linux x64 5.19.0-23-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1299)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|3.63GB (0.81GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
iaj6b796:30602301
dbltrim-noruby:30604474

```

</details>

**Comment by valentincepeda** [comment]
> Type: <b>Bug</b>
> 
> 
> 
> when i maximise my window in ubuntu the screen shifts slightly towards right and the top menu bar which shows the time and notification hides. when i press ctrl or go to any drop down menu it fixes for a sec and then goes back to how it was earlier. 
> 
> 
> 
> VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:44:09.336Z)
> 
> OS version: Linux x64 5.19.0-23-generic snap
> 
> Modes:
> 
> Sandboxed: No
> 
> 
> 
> <details>
> 
> <summary>System Info</summary>
> 
> 
> 
> |Item|Value|
> 
> |---|---|
> 
> |CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1299)|
> 
> |GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
> 
> |Load (avg)|1, 1, 1|
> 
> |Memory (System)|3.63GB (0.81GB free)|
> 
> |Process Argv|--no-sandbox --force-user-env --unity-launch|
> 
> |Screen Reader|no|
> 
> |VM|0%|
> 
> |DESKTOP_SESSION|ubuntu|
> 
> |XDG_CURRENT_DESKTOP|Unity|
> 
> |XDG_SESSION_DESKTOP|ubuntu|
> 
> |XDG_SESSION_TYPE|wayland|
> 
> </details>Extensions: none<details>
> 
> <summary>A/B Experiments</summary>
> 
> 
> 
> ```
> 
> vsliv368cf:30146710
> 
> vsreu685:30147344
> 
> python383:30185418
> 
> vspor879:30202332
> 
> vspor708:30202333
> 
> vspor363:30204092
> 
> vswsl492:30256859
> 
> vslsvsres303:30308271
> 
> pythonvspyl392:30443607
> 
> vserr242cf:30382550
> 
> pythontb:30283811
> 
> vsjup518:30340749
> 
> pythonptprofiler:30281270
> 
> vshan820:30294714
> 
> vstes263cf:30335440
> 
> pythondataviewer:30285071
> 
> vscod805cf:30301675
> 
> binariesv615:30325510
> 
> bridge0708:30335490
> 
> bridge0723:30353136
> 
> cmake_vspar411:30581797
> 
> vsaa593cf:30376535
> 
> pythonvs932:30410667
> 
> cppdebug:30492333
> 
> vscaac:30438847
> 
> vsclangdc:30486549
> 
> c4g48928:30535728
> 
> dsvsc012cf:30540253
> 
> azure-dev_surveyone:30548225
> 
> pyindex848:30577860
> 
> nodejswelcome1cf:30587006
> 
> fc301958:30595537
> 
> 3biah626:30602489
> 
> iaj6b796:30602301
> 
> dbltrim-noruby:30604474
> 
> 
> 
> ```
> 
> 
> 
> </details>
> 
> 
> 
> 

- @AArnott

**Comment by AArnott** [comment]
@rachit-ranka I don't work on VS Code. Please don't mention folks just to try to get attention drawn to an issue unless you know them and know that they would be particularly responsive if notified about an issue.
