### ISSUE TITLE
vscode and godef use high cpu (with steps)

### ISSUE THREAD

**Issue by zakokun** [Microsoft/vscode#16566]
- VSCode Version: 1.7.2
- OS Version: macOS Sierra
- go version: go1.7.3

extensions: 
 ![extension](http://ww1.sinaimg.cn/large/73c5712dgw1fagy7tsv5gj20bi0dudgh.jpg)

Steps to Reproduce:

1.  open vscode
2.  open a  ` .go` file, use `go def` many times
3.  then vscode use cpu high
 ![extension](http://ww3.sinaimg.cn/large/73c5712dgw1fagyr0o168j20cg06q74o.jpg)
4. use `commad +Q` quit vcode, I see many `godef` process 
 ![extension](http://ww1.sinaimg.cn/large/73c5712dgw1fagyu6a0ykj20bu04y3yl.jpg)

see `ps aux`

 ![extension](http://ww2.sinaimg.cn/large/73c5712dgw1fagywtlmk1j21kw05l43j.jpg)

`/Users/zhanghongwen/golang/src/download/load.go` is the test go file

`/Users/zhanghongwen/golang/` is the `GOPATH`

**Comment by ramya-rao-a** [comment]
This issue was moved to Microsoft/vscode-go#684
