### ISSUE TITLE
Double-clicking a file in Windows opens VSCode but does not load the file opened

### ISSUE THREAD

**Issue by Plasma** [Microsoft/vscode#16565]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|code-gnu-global|austin|0.2.1|
|LogFileHighlighter|emilast|1.0.0|
|vs-code-xml-format|fabianlauer|0.1.4|
|gc-excelviewer|GrapeCity|1.1.10|
|beautify|HookyQR|0.5.3|
|ecdc|mitchdenny|0.10.3|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.4.1|
|vscode-nginx|shanoor|0.3.0|
|vscode-hexdump|slevesque|1.1.2|

---

Steps to Reproduce:

1.Double-click a .txt file that is set to open with VSCode
2. VSCode launches and opens, but at an Untitled document, not the file that was double-clicked to be opened

**Comment by ZCShou** [comment]
@Plasma  for me  an Untitled document and selected file will both be opend
![111](https://cloud.githubusercontent.com/assets/8591065/20913744/4b4193a4-bbb5-11e6-9daf-9cc54a49747a.gif)

**Comment by joaomoreno** [comment]
#13919

You'll need to reset the file association, in the Properties dialog, again to VS Code Insiders.
