### ISSUE TITLE
vscode/package.json distro property

### ISSUE THREAD

**Issue by kev1010** [microsoft/vscode#165650]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest
- OS Version: Window 10

Steps to Reproduce:

1. [Package.json](https://github.com/microsoft/vscode)/package.json) has an invalid field("distro": "51e5bb745ed01b333d96df102d750c9ec33ffe23").
2. [Yarn package.json documentation](https://classic.yarnpkg.com/lang/en/docs/package-json/) does not include a distro field.

**Comment by aeschli** [comment]
`distro` is a custom property used by our internal build scripts. Why do you think it's invalid?

**Comment by kev1010** [comment]
I thought it was invalid because it wasn't a standard field and I didn't
see where it was used in the application by doing a search on "distro".
Which file is it used in?

**Comment by aeschli** [comment]
It's used in an internal build script. Many tools add their custom properties to `package.json`, there's nothing invalid about it.

**Comment by kev1010** [comment]
If it is used for another repository then I would say that other
repositories should be forked from this repository and its customizations
should only reside there. This would keep this repository clean and
relative. Otherwise, it seems others could do the same and the codebase
would get artificially inflated.

**Comment by kev1010** [comment]
@aeschli is the internal build script in this repository? If so, where is the distro property used in it?

**Comment by aeschli** [comment]
[Here is](https://github.com/microsoft/vscode/blob/main/build/azure-pipelines/mixin-distro-posix.yml#L39) where that property is used.
Yes, it's a commit id into a different (internal) repository that contains the bits that are used for the [Microsoft Visual Studio Code distribution](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code). Yes, I think there's some work ongoing to do this with a fork instead, but IMO having the extra field has not been an issue.
