### ISSUE TITLE
Notebook diff fails to load in PR flow

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#165662]
Type: <b>Bug</b>

I was working on PR (https://github.com/digitarald/ds-together-demo/pull/1) and had working diffs before. When I reset the files and tried to open the file again it all fell apart:

<img width="770" alt="image" src="https://user-images.githubusercontent.com/8599/200193086-68bbb7b4-62e7-4c6f-b261-4976601fef1c.png">

Error thrown when opening:
```
  ERR TypeError: Cannot read properties of undefined (reading 'outputs')
    at new I (diffNestedCellViewModel.ts:84:43)
    at o._createInstance (instantiationService.ts:120:18)
    at o.createInstance (instantiationService.ts:86:18)
    at Xi.computeModifiedLCS (notebookDiffEditor.ts:725:26)
    at Xi.computeDiff (notebookDiffEditor.ts:657:47)
    at Xi.updateLayout (notebookDiffEditor.ts:520:67)
    at async Xi.setInput (notebookDiffEditor.ts:422:3)
    at async s.doSetInput (editorPanes.ts:353:4)
    at async s.doOpenEditor (editorPanes.ts:222:34)
    at async s.openEditor (editorPanes.ts:126:11)
    at async editorGroupView.ts:1074:49
    at async editorCommands.ts:575:3
```

Maybe related, shows up repeatadly:
```
[Extension Host] unhandledRejection {"name":"Error","message":"cannot open vscode-notebook-cell://codespaces%2Bdigitarald-probable-broccoli-wrpvr9x9hjjp/workspaces/ds-together-demo/survey.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D. Detail: Unable to resolve text model content for resource vscode-notebook-cell://codespaces%2Bdigitarald-probable-broccoli-wrpvr9x9hjjp/workspaces/ds-together-demo/survey.ipynb#X13sdnNjb2RlLXJlbW90ZQ%3D%3D"}
y @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:455
_invokeHandler @ rpcProtocol.ts:440
_receiveRequest @ rpcProtocol.ts:370
_receiveOneMessage @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:670
deliver @ event.ts:877
fire @ event.ts:838
fire @ ipc.net.ts:646
_receiveMessage @ ipc.net.ts:988
(anonymous) @ ipc.net.ts:852
invoke @ event.ts:670
deliver @ event.ts:877
fire @ event.ts:838
acceptChunk @ ipc.net.ts:390
(anonymous) @ ipc.net.ts:346
(anonymous) @ browserSocketFactory.ts:230
invoke @ event.ts:670
deliver @ event.ts:877
fire @ event.ts:838
C._fileReader.onload @ browserSocketFactory.ts:91

```

VS Code version: Code - Insiders 1.74.0-insider (e764c5b816a99eb8673b2fc4fc028827f202872f, 2022-11-04T05:19:54.097Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1094-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 4|
|Memory (System)|64.00GB (15.19GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1094-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (4 x 2793)|
|Memory (System)|7.77GB (5.21GB free)|
|VM|0%|
</details>

**Comment by rebornix** [comment]
I think this is the same as notebook fails to open when editor model resolution fails.
