### ISSUE TITLE
Terminal in codespace shows only username on safari

### ISSUE THREAD

**Issue by yaakiyu** [microsoft/vscode#165674]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0-insider
- OS Version: codespace(browser: iPadOS 15.6 UserAgent: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15`)
![C9E23766-F4D7-4B38-A988-71DA61090A15](https://user-images.githubusercontent.com/62779277/200210041-8d6ecb28-df41-4644-9faf-fb77a449993f.png)
(I'm Japanese, so my English may not be good.)

Steps to Reproduce:

1. Start codespace on safari (I tested in iPad)
2. View "terminal"

**Comment by yaakiyu** [comment]
I can type in the terminal, but nothing will be displayed.

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari
