### ISSUE TITLE
Mac Insert Emoji Duplicates Text

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16562]
- VSCode Version: 1.8 Insiders
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Create blank document.
2. Type `cat`
3. Move the cursor back to between `c` and `a`
4. Insert an emoji  (such as 🐱) using the mac emoji panel

**Expected**
Result is: `a🐱bc`

**Actual**

![dec-05-2016 17-41-33](https://cloud.githubusercontent.com/assets/12821956/20909718/33c2b698-bb12-11e6-92e6-85fb6141a592.gif)

Letters after the insertion are duplicated, producing `cat🐱at`

**Comment by mjbvz** [comment]
Basic text duplication just seems like one symptom; I'm seeing the text mangled in all sorts of other ways as well.

Also, I'm only seeing this when using the panel shown above. When using the emoji window UI, I do not see this effect.

**Comment by alexandrudima** [comment]
Just checked with @joaomoreno and it is not a regression in 1.8.x (same behaviour on stable)

**Comment by alexandrudima** [comment]
Related: #4271

**Comment by alexandrudima** [comment]
Duplicate of #4271
