### ISSUE TITLE
When typing Chinese in git commit editor, There are overlapping shadows on the text.

### ISSUE THREAD

**Issue by Vikingama** [microsoft/vscode#165682]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.73.0
- OS Version: macOS 13.0 (22A380)

Steps to Reproduce:

1. switch to the version control tab in sidebar
2. typing Chinese in the commit message editor

**Comment by tu6ge** [comment]
I am also encounter the bug with [sougou](https://shurufa.sogou.com/)

**Comment by tu6ge** [comment]
sogou chinese IME, and other chinese IME , acquire a better understanding

**Comment by lszomoru** [comment]
@alexdima, @hediet any idea is this is specific to the monaco editor? Thanks!

**Comment by hediet** [comment]
Does it reproduce in the main editor?

**Comment by tu6ge** [comment]
yeah, this is not dev version

**Comment by tu6ge** [comment]
Ohooo, My OS info: Windows 11 22H2, and vscode version: 1.73.1

The problem seems to have nothing to do with OS

**Comment by hediet** [comment]
I mean does this also happen when you open a .txt file in VS Code and write into that file?

**Comment by hediet** [comment]
@lszomoru then it seems to be specific for the commit editor, not arbitrary editor instances.

**Comment by lszomoru** [comment]
@Vikingama, is this a regression or you are also able to reproduce the problem in earlier versions as well?
@hediet, the SCM input is using the `CodeEditorWidget`. Will try to track down which of the settings causes this.

**Comment by tu6ge** [comment]
Hi @Vikingama , You can precipitate and think about it and send it together to avoid disturbing others.

**Comment by alexdima** [comment]
@Vikingama what theme are you using?

**Comment by alexdima** [comment]
git bisect leads to: d08c3c2c6f6eca4262bf19639c28378d7db76720 is the first bad commit

**Comment by alexdima** [comment]
I've narrowed it down to the following change. When applying it, the IME text is no longer overlapping itself:

```patch
diff --git a/src/vs/workbench/contrib/scm/browser/media/scm.css b/src/vs/workbench/contrib/scm/browser/media/scm.css
index 37a9d5a75e2..6949cc24205 100644
--- a/src/vs/workbench/contrib/scm/browser/media/scm.css
+++ b/src/vs/workbench/contrib/scm/browser/media/scm.css
@@ -200,14 +200,6 @@
 	border-radius: 2px;
 }
 
-.scm-view .scm-input .margin {
-	width: 6px !important;
-}
-
-.scm-input .monaco-scrollable-element {
-	left: 6px !important;
-}
-
 .scm-view .scm-editor-container .monaco-editor {
 	border-radius: 2px !important;
 }
```

The root cause is that the sizing of inner editor dom nodes needs to be left to the editor, using editor options and the JS API. We shouldn't force certain sizes for private editor dom nodes using CSS. @daviddossett Do you remember what the intent of the change was? Maybe there is editor JS API that can be used to achieve the same layout.

**Comment by lszomoru** [comment]
Thanks @alexdima for tracking down the commit that introduced the regression. I will defer to @daviddossett on the reasoning for changing the left margin from `4px` to `6px` but I created a PR that results in the same layout but without the regression: https://github.com/microsoft/vscode/pull/167380
