### ISSUE TITLE
Unable to run bash script on Windows

### ISSUE THREAD

**Issue by kjsmita6** [microsoft/vscode#165658]
Type: <b>Bug</b>

1. Create a bash script with the contents:
```
#!/bin/bash
echo "Hello world"
```

2. Run it either in the embedded terminal (I was using Powershell) with `./scriptName` or by creating a task.

3. The script fails to run and you get the following error.

```
[26936:1106/125636.515:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[26936:1106/125636.515:ERROR:cache_util.cc(145)] Unable to move cache folder C:\Users\Kyle Smith\AppData\Roaming\Code\Cache\Cache_Data to C:\Users\Kyle Smith\AppData\Roaming\Code\Cache\old_Cache_Data_000
[26936:1106/125636.515:ERROR:disk_cache.cc(196)] Unable to create cache
```

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (20.42GB free)|
|Process Argv|--crash-reporter-id 2d8e062b-6afe-44f9-a2d0-42b08c10de27|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (46)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eclipse-keybindings|alp|0.16.1
shell-syntax|bma|1.0.3
vscode-intelephense-client|bme|1.8.2
insert-unicode|bru|0.14.0
path-intellisense|chr|2.8.1
doxdocgen|csc|1.4.0
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
shell-format|fox|7.2.2
sourcepawn-remote-debug|Gar|0.1.1
json2ts|Gre|0.0.6
vscode-jasmine-test-adapter|hbe|1.8.2
vscode-test-explorer|hbe|2.21.1
discord-vscode|icr|5.8.0
smarty|imp|0.3.0
latex-workshop|Jam|8.29.0
jbockle-format-files|jbo|3.4.0
better-cpp-syntax|jef|1.16.3
vscode-todo-highlight|jgc|2.0.4
ts-extension-pack|loi|0.3.0
bash-ide-vscode|mad|1.14.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
test-adapter-converter|ms-|0.1.6
tsimporter|pmn|2.0.1
quicktype|qui|12.0.46
typescript-hero|rbb|3.0.0
java|red|1.12.0
tabletopsimulator-lua|rol|1.1.3
sourcepawn-vscode|Sar|4.2.3
move-ts|str|1.12.0
tabnine-vscode|Tab|3.6.19
latex-utilities|tec|0.4.8
shellcheck|tim|0.26.3
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.46.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.6
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.2
JavaScriptSnippets|xab|1.8.0
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
3d0df643:30602300
dbltrim-noruby:30604474

```

</details>

**Comment by deepak1556** [comment]
Does the issue repro when you attempt the same with VSCode user setup installation ?

**Comment by kjsmita6** [comment]
I'm sorry, I'm not sure what this means. What is vscode user setup installation?

**Comment by deepak1556** [comment]
`User installer` in the following screenshot, allows installing the application for the current user.

<img width="292" alt="Screenshot 2022-12-06 at 1 43 59 PM" src="https://user-images.githubusercontent.com/964386/205817550-cdcdcb26-1c34-4bc3-8d26-ef216b9b1d94.png">

**Comment by Tyriar** [comment]
@kjsmita6 we're [issue grooming](https://github.com/microsoft/vscode/wiki/Issue-Grooming) and you didn't answer the question so this is blocked on you. We can reopen if you do

**Comment by kjsmita6** [comment]
Yes please reopen. The issue cleanup policy says 7 days for need info and it has only been 4.

**Comment by kjsmita6** [comment]
Just tried the steps provided by @deepak1556 , and unsurprisingly the issue remains with the same error. Not sure why using a different installer would cause this error.

**Comment by kjsmita6** [comment]
@Tyriar @meganrogge @deepak1556 bump to please reopen.

**Comment by kjsmita6** [comment]
I am on a different system now because I am away from my normal computer. 

VS Code version: Code 1.74.2
OS version: Windows_NT x64 10.0.22000

I am not getting the logging messages anymore. However, I am still getting similar behavior and the script still does not run.

https://user-images.githubusercontent.com/9405706/208966848-e188a84d-944e-435b-9957-ad5d1ecdbef0.mp4

When I run the script in the terminal, the file is opened in the editor, and the cursor is placed in a specific location (i.e., not the beginning of the file as usual - it was placed at the end but on larger files this isn't always the case, sometimes being placed in the middle). Also, the terminal doesn't return properly and the text is not printed.

I am assuming the error is still present but the messages just aren't being printed. The glitches in the console are similar to what I had when I see the messages.

**Comment by deepak1556** [comment]
Shouldn't the script be run with `bash ./test.sh` in the powershell ? Otherwise, in your case the OS is opening the file with default program associated with the file extension (in this case VSCode).

**Comment by kjsmita6** [comment]
Hmm, I suppose that is correct. Although powershell does tell me to do `.\test.sh` for a command, and for someone who doesn't realize that powershell and unix scripts are different (like me) this wouldn't make sense. But I suppose that isn't your problem :) 

I think those error messages should still be investigated (in the case that what I was doing was actually just opening the shell script in vscode).

Another thing when running the shell script - again, not sure if this is your problem or a problem with powershell. When I do my `.\test.sh`, vscode opens. Some logging messages are put in powershell which messes up the input (see below). Is vscode not flushing something correctly?

https://user-images.githubusercontent.com/9405706/209191414-3cb9b00e-c515-4af8-87af-8a1227055786.mp4

**Comment by deepak1556** [comment]
> I think those error messages should still be investigated (in the case that what I was doing was actually just opening the shell script in vscode).

Those are cache migration related error messages from the runtime, it can be ignored.

> When I do my .\test.sh, vscode opens. Some logging messages are put in powershell which messes up the input (see below). Is vscode not flushing something correctly?

This is tracked in https://github.com/microsoft/vscode/issues/66750

Closing as issue is not with VSCode.
