### ISSUE TITLE
Status bar invisible and only comes back after resizing window

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#165667]
The status bar was not rendered and only showed up after I resized the window. Wasn't able to find clear steps to reproduce it.

Happened once in a web-based Codespace and then again in VS Code desktop.

Version: 1.74.0-insider
Commit: e764c5b816a99eb8673b2fc4fc028827f202872f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.10
Embedder: codespaces

**Comment by bpasero** [comment]
Maybe something related to settings sync where status bar was hidden and then came back?

**Comment by digitarald** [comment]
> Maybe something related to settings sync where status bar was hidden and then came back?

No, I never played with that par of the layout.

**Comment by sbatten** [comment]
i'm really surprised this repro'd in desktop, if you can get something reliably that would be awesome

**Comment by digitarald** [comment]
@sbatten this was on the web.

**Comment by sbatten** [comment]
>Happened once in a web-based Codespace and then again in VS Code desktop.

@digitarald ?

**Comment by digitarald** [comment]
Sorry, misremembered that part from by bug hunt. So far it hasn't happened again.
