### ISSUE TITLE
Github copilot suggestion causes the system's own prompt not to be displayed

### ISSUE THREAD

**Issue by hlbbt** [microsoft/vscode#165692]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 

CPUs | Apple M1 (8 x 24)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled webgpu: disabled_off
Load (avg) | 3, 3, 3
Memory (System) | 8.00GB (0.10GB free)
Process Argv | --crash-reporter-id 52ca6aee-7a0e-4077-9fd8-eb29e2f34f99
Screen Reader | no
VM | 0%

![image](https://user-images.githubusercontent.com/113571052/200297734-16e12083-ebc5-4544-b0cd-99049dc8abd5.png)
When I type `webApi.`, the corresponding function and attribute will not be automatically prompted.

![image](https://user-images.githubusercontent.com/113571052/200298414-820092dd-598a-411e-9839-820081b47a5c.png)
When I close the copilot plug-in and type `webApi.`, I will automatically prompt the corresponding functions and properties

I think the automatic prompt and the copilot suggestion can be displayed at the same time, or the delay trigger setting can be added in the copilot plug-in settings. For example, after typing the content, the inline suggestion can be displayed with a delay of 1s

**Comment by isidorn** [comment]
Closing as dup of https://github.com/microsoft/vscode/issues/131940
