### ISSUE TITLE
How to open a new tab when I cmd + click?

### ISSUE THREAD

**Issue by Larry850806** [Microsoft/vscode#16563]
- VSCode Version: 1.7.1
- OS Version: MacOS Sierra 10.12.1

Steps to Reproduce:

There is two file 'a.js' and 'b.js' in my directory. 'b.js' is empty and this is my 'a.js'.

![screen shot 2016-12-06 at 11 48 47 am](https://cloud.githubusercontent.com/assets/10403741/20912396/fdd4a4a4-bba9-11e6-9b77-5189cbbaf985.png)

when I move cursor to './b.js' and 'cmd + click' to see 'b.js'. It doesn't open 'b.js' in the new tab.

![screen shot 2016-12-06 at 11 51 38 am](https://cloud.githubusercontent.com/assets/10403741/20912446/60ad0d6e-bbaa-11e6-96fb-47c6aeb48644.png)

What I want to do is to open 'b.js' in a new tab so that I can switch between 'a.js' and 'b.js'. How do I do that?

**Comment by bpasero** [comment]
@Larry850806 try setting `"workbench.editor.enablePreview": false` in settings to always force keeping a file as tab.

**Comment by jasonslyvia** [comment]
I love preview mode, but not the case when I `command + [click]` or using `quick open`, it would be much more convenient if there're more specific options for this behavior.
