### ISSUE TITLE
Displaying the type and shape of an array in the call stack during debugging

### ISSUE THREAD

**Issue by navotoz** [microsoft/vscode#165640]
Hello

During debug, the call stack in PyCharm display the type and shape of an array variable next to its name (e.g., in ```np.ndarray``` and ```torch.Tensor```).
Attached is the call stack in VScode and in PyCharm for two ```np.ndarrays```:

![VS](https://user-images.githubusercontent.com/38127869/200156808-26c3557b-1426-4bf7-b54d-25c9de6ac30b.jpg)
![CHARM](https://user-images.githubusercontent.com/38127869/200156811-a6aef5bb-f4c7-4734-8964-ed5d294922a5.jpg)

This feature saves a lot of mouse-work (finding the variable in the call stack, opening it, scrolling to the shape, etc.), especially in N-dimensional arrays that are usually used in optimization tasks (ML, DL, etc.).
For example, in matrix multiplication the elements of the intermediate matrices are usually less interesting than the N-dim shapes of the matrices themselves. which are crucial to for the multiplication operation.

Thanks for all your effort and time on the product, I really enjoy working with it.

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/146748
