### ISSUE TITLE
Bug/regression: Renaming local, non-exported variables causes the file to be automatically saved

### ISSUE THREAD

**Issue by axefrog** [microsoft/vscode#165661]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 1.73.0
- OS Version: Windows 10

When performing refactorings in TypeScript such as a renaming a variable, the former behaviour of only auto-saving changes if the refactoring impacts multiple files has now been changed to the undesirable behaviour of automatically forcing the currently-edited file to be saved even when the change had no external impact. This is annoying when making a lot of quick changes locally, as every save has the potential to trigger a build process. Sure, save changes automatically if the change affects multiple files (I don't want a project-wide rename to pop open every affected file in an unsaved state), but don't save the current file if changes are limited to the active editor. Let me, the developer, decide when to save the active document.

Steps to Reproduce:

1. Create a typescript file with a local variable that is not referenced in any other file.
2. Place the cursor on the variable name, then press F2 and rename it to something else.
3. The file is automatically saved, even though the change was local/internal only.

TypeScript refactorings should only cause the file to be automatically saved if they target multiple files.

I have confirmed that issue this also occurs in VS Code Insiders (1.74.0).

**Comment by jrieken** [comment]
We have the `files.refactoring.autoSave` setting to control that. @axefrog Are you aware of that and would be happy with it or do you want to make a differentiation between refactorings that change the current file only vs multiple files?

**Comment by axefrog** [comment]
@jrieken Yes, in my mind the only reason to autosave is because a refactoring is touching multiple files which you don't necessarily want to be forced open into an unsaved state. I like this setting, because it means I can make broad sweeping changes across the project without cluttering the active workspace every time you do so. But these are selective changes - I know when I am making "local" changes, and when I am making changes that affect the project as a whole. I find that local changes tend to be applied with much higher frequency than project-wide changes, and this often involves renaming variables (among other things) while I get the structure of the code in the local scope fully worked out. Forcing the local file to save every time I perform such a refactoring tends to feel like VS Code is being "too helpful" in an intrusive way. The behaviour before the most recent update to VS Code was fine, but something seems to have changed and now VS Code is saving the current file even for local changes, whereas prior to the recent update it did not.
