### ISSUE TITLE
Mouse scroll very slow and sometimes doesn't work at all (linux mint)

### ISSUE THREAD

**Issue by ClecioJung** [microsoft/vscode#165659]
Does this issue occur when all extensions are disabled?
Yes, It is less frequent, but still happens.

Steps to Reproduce:

When I try to move the editor window up and down using the mouse scroll, the page only moves a few seconds after I rotate the scroll. In some cases the page does not move at all. I saw this happen on a Linux Mint 20.3 x86_64  virtual machine running on VirtualBox Version .1.40 r154048. I tried to uninstall VSCode and reinstall it, but the problem persisted.

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:44:09.336Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.4.0-131-generic
Sandboxed: No

**Comment by tescher** [comment]
I see the same issue with Ubuntu 20.04 VM, VirtualBox  6.1.40 r154048 (Qt5.6.2), Win 10 host

**Comment by alexdima** [comment]
We react to all `scroll` events we receive immediately. The problem here is that we don't receive a `scroll` event from Chromium or we receive it later. There is nothing we can do on our side, there is no possible code change we can do since we're not receiving these scroll events.
