### ISSUE TITLE
Peek Call Hierarchy - close button not working

### ISSUE THREAD

**Issue by arknest** [microsoft/vscode#165646]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0-insider
- Commit: e764c5b816a99eb8673b2fc4fc028827f202872f
- Date: 2022-11-04T05:18:32.818Z
- OS Version: Windows_NT x64 6.3.9600 (server 2012 r2)

Steps to Reproduce:

1. Right click on function in text editor (in typescript file)
2. choose "Peek Call Hierarchy"
3. inline "Peek" window opens
4. close button is greyed out and unable to close window

**Comment by jrieken** [comment]
I cannot reproduce. Please check the dev tools console for error (F1 > Developer Tools > Console)

**Comment by arknest** [comment]
![ecJWXgvo5Y](https://user-images.githubusercontent.com/115984926/200377398-a1760bb7-a36b-4710-b775-33a671b12068.gif)

At startup (with --disable-extensions):
![Code_-_Insiders_05je28lkfc](https://user-images.githubusercontent.com/115984926/200377682-7280606c-16d2-47a5-b621-e9d7f8b0bebe.png)
[vscode-app-1667841972505.log](https://github.com/microsoft/vscode/files/9954107/vscode-app-1667841972505.log)

Then when "Peek Call Hierarchy" pressed:
![Code_-_Insiders_jsUq0rraa1](https://user-images.githubusercontent.com/115984926/200377907-56065147-4c24-43da-86f0-5b82447cdc81.png)
[vscode-app-1667842102881.log](https://github.com/microsoft/vscode/files/9954114/vscode-app-1667842102881.log)

**Comment by arknest** [comment]
By the way, pressing ESC does not closes the window as well

**Comment by jrieken** [comment]
@arknest Do you have the `config.editor.stablePeek`-setting enabled?

**Comment by jrieken** [comment]
I can reproduce with the setting mentioned about and will push a fix. @arknest let we know if you don't use that setting

**Comment by arknest** [comment]
> @arknest Do you have the `config.editor.stablePeek`-setting enabled?

Yes, I have it enabled.
When switched to default (false) it works as expected.
