### ISSUE TITLE
Please change the name of this app

### ISSUE THREAD

**Issue by johann1301s** [microsoft/vscode#165683]
«Visual Studio Code» is too long, and too involved, and does not resonate.

It would be cleaner with just «Code».

Single word like; Slack, Sketch, Figma, Chrome, Apple, Tesla or Atom...

**Comment by letsgoaway-games** [comment]
I dont think they will rename this app anytime soon. For now, if your on windows at least, you can Right Click on VSCode in the start menu, click Open File Location, and Right Click on visual studio code. then click properties, then you can change the name and then your vs code shortcut will be renamed.

**Comment by andreamah** [comment]
We currently do not have plans for renaming.
