### ISSUE TITLE
Favorite Directory

### ISSUE THREAD

**Issue by KaungZawHtet** [microsoft/vscode#165609]
We use [this](https://github.com/kdcro101/vscode-favorites) extension to manage favorite directories. Really useful especially when the project is too much complex with too many directories and we can focus on only what we need. But this extension is inactive and not maintain anymore. Can vs code team add such feature in default ?

**Comment by lramos15** [comment]
No plans to add this feature in the near future. Feel free to contribute to the extension as it is open source. We also support multi-root workspaces where you could put you favorite directories all at the top level that way.
