### ISSUE TITLE
Using split or creating new terminal causing terminal to bug and go blank

### ISSUE THREAD

**Issue by jellyfisssh** [microsoft/vscode#165673]
Type: <b>Bug</b>

Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Have a working terminal (Using any terminal) then press the split terminal button which causes my terminal to go blank and prevent from typing. 

I have tried to reload window and restart vscode. Only solution for me so far is to restart my whole pc.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3399)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (7.73GB free)|
|Process Argv|--crash-reporter-id 2ea21c9d-85e4-4420-93f8-04d9f98437bf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.53.0
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.0.4
vscode-graphql|Gra|0.8.1
vscode-graphql-execution|Gra|0.1.5
vscode-graphql-syntax|Gra|1.0.4
vscode-docker|ms-|1.22.2
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-database-projects-vscode|ms-|0.19.0
isort|ms-|2022.4.0
python|ms-|2022.18.1
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-typescript-next|ms-|5.0.20221103
vsliveshare|ms-|1.0.5762
vetur|oct|0.36.1
material-icon-theme|PKi|4.22.0
vscode-rapidapi-client|Rap|1.7.0
java|red|1.12.0
vscode-xml|red|0.22.0
LiveServer|rit|5.7.9
stepsize|Ste|0.69.2
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.46.0
vscode-java-pack|vsc|0.25.6
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.2
material-ui-snippets|vsc|3.3.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
vscccc:30566498
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30602634
iaj6b796:30602301
dbltrim-noruby:30604474

```

</details>

**Comment by jellyfisssh** [comment]
I just realized it occurs when I change the date and time on my windows pc, after a while it will cause the terminal to bug haha

**Comment by meganrogge** [comment]
does this happen if you disable all extensions?

has it just started recently?

any errors in the dev tools console?

does changing `terminal.integrated.gpuAcceleration` fix it?
