### ISSUE TITLE
Notebook rendering glitches after full screen

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#165638]
Type: <b>Bug</b>

After full screen I got this output, which persist after leaving full screen. Closing the sidebar also didn't fix it. Had to reopen the notebook.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/8599/200155209-481bc31c-7008-4ccd-9830-9280222932af.png">

VS Code version: Code - Insiders 1.74.0-insider (e764c5b816a99eb8673b2fc4fc028827f202872f, 2022-11-04T05:19:54.097Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.4.0-1094-azure

**Comment by rebornix** [comment]
@digitarald does it happen all the time or occasionally?

**Comment by digitarald** [comment]
When it started happening, it was easy to reproduce. Even in a new session. But right now I can't get it to reproduce, now it is instant. Maybe something with Docker backend for the container? I also tried restarting Docker.

**Comment by DonJayamanne** [comment]
Please feel free to reopen or create a new issue if you still run into this 
Since a few changes have been made since, its possible this may have been fixed.
