### ISSUE TITLE
Win/Linux: detect real casing of workspace paths

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16570]
In insiders, I had a workspace opening with a lowercase workspaceRoot path, so that file paths were reported as lowercased, and `${workspaceRoot}` in a launch config was replaced with a lowercase version which is how I noticed. I opened and closed vscode several times and it persisted. And it persisted through opening that folder again with the 'recently opened' list. I opened the folder again using cmd+o, and then it had the correct casing. I assume that the list of recently opened folders got the lowercased path somehow. Any idea how it could have happened? It's not reproing anymore unfortunately. 

I debugged it as far as the function `startup` in main.ts and saw that it was lowercased at that point.

Should be uppercased `/Users`
![image](https://cloud.githubusercontent.com/assets/323878/20915161/f0635f2a-bb38-11e6-80bd-e23d7c2616fe.png)

**Comment by bpasero** [comment]
@roblourens the workbench is using whatever path you give it, since Windows and OSX are case insensitive, lowercase paths are working. Detecting the correct case from a lowercase variant is very expensive and that is why we do not have code in place to do it, though we could add it.

**Comment by roblourens** [comment]
I see that I can do `code FOO` and open a folder, 'foo'. I didn't do anything like that though. Eh, I think what I need to do is detect this in the debug adapter and write a warning, which node-debug does. The debug adapter is not case-sensitive but Chrome is.

**Comment by roblourens** [comment]
This happened again. No clue why, I'm not doing anything out of the ordinary.

Where are the 'Open recent' paths stored?

**Comment by roblourens** [comment]
Mystery solved, it was hot exit

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
