### ISSUE TITLE
Extension API: insertSpaces and tabSize are undefined

### ISSUE THREAD

**Issue by aioutecism** [Microsoft/vscode#16573]
- VSCode Version: 1.7.2
- OS Version: OSX 10.11.6

Steps to Reproduce:

1. Build an extension and access `window.activeTextEditor.options`.
2. The `insertSpaces` and `tabSize` are undefined.

Extra Information:

- This happens when `editor.detectIndentation` is true.
- A semi accurate workaround could be done by using `workspace.getConfiguration`.

**Comment by alexandrudima** [comment]
@aioutecism I could not reproduce with the following code:

### package.json
```json
{
    "publisher": "test",
    "name": "16573",
    "version": "0.0.1",
    "engines": {
        "vscode": "^0.10.0"
    },
    "activationEvents": [
        "*"
    ],
    "main": "./index.js"
}
```

### index.js
```js
var vscode = require('vscode');

vscode.window.onDidChangeActiveTextEditor(function(ed) {
    if (!ed) {
        return;
    }
    console.log(ed.options);
});
```

I always get to see the text editor options, regardless of the `editor.detectIndentation` setting:
![image](https://cloud.githubusercontent.com/assets/5047891/20921083/dbd92944-bba2-11e6-8741-a438bc2ed4fe.png)

Is there something more to get this to reproduce ?

**Comment by aioutecism** [comment]
@alexandrudima 
You have to open existing files with tab or space indention.
As below:
![2016-12-07 14 41 41](https://cloud.githubusercontent.com/assets/2175401/20956128/5ce10528-bc8b-11e6-8ab2-b66a86390c4d.gif)

**Comment by aioutecism** [comment]
@alexandrudima 
I noticed that the "EditorConfig for Visual Studio Code" causes this problem.

I tried to reproduce the problem by setting options like this:
```ts
vscode.window.activeTextEditor.options = {
    cursorStyle: vscode.TextEditorCursorStyle.Line,
}
```

I think we should make `options` readonly or using setter method to avoid missing members.

```ts
private _options: vscode.TextEditorOptions;
set options(value: vscode.TextEditorOptions) {
    Object.assign(this._options, value);
}
```

**Comment by alexandrudima** [comment]
to reproduce:
* add a statement somewhere above the log `ed.options = { tabSize: 3}`.

**Comment by aioutecism** [comment]
Thanks for the fix!
