### ISSUE TITLE
Allow `vscode.MarkdownString` to specify newline rendering options

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#165727]
Discussion is in https://github.com/microsoft/vscode-pull-request-github/issues/3881

Different markdown renderers make different choices on when to render newlines. Could we have a flag for `vscode.MarkdownString` that let's extensions specify whether newlines should be rendered even when not a double newline and without two spaces at the end?

**Comment by mjbvz** [comment]
We try to target common mark. If other extensions need different rendering, they can try converting their markdown so that common mark can render it as they want (such as adding two spaces to the end of every line if they don't want automatic line continuations)
