### ISSUE TITLE
Editor scrolls to the wrong place when navigating to a lower line in the same file using the inline editor

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16571]
- Open any file, let's say `workbench.ts` in vscode
- Do 'find all references' on something, like `this.initServices()` on line 247
- Double click or press enter on the listing for the other reference, to navigate to it

It should be showing line 402, but the editor has actually scrolled just past line 402.

If the navigation goes up, it works correctly.

If the navigation goes across files, it works correctly. It reproes anywhere that the navigation goes downwards within the same file.

**Comment by alexandrudima** [comment]
Here is what I think happens:

* the editor still has the old view zone rendered (imagine it takes up 15 lines)
* the editor is asked to reveal line 403 in center
* it does so, and the scrollTop is X
* the references widget removes the view zone above (on line 248)
* the scrollTop remains X (all lines move up by 15 lines)
* the references widget adds a view zone after line 403
* the scrollTop remains X (line 403 is exactly the height of the references widget above the editor center)
