### ISSUE TITLE
Missing repo in source control

### ISSUE THREAD

**Issue by Leathong** [microsoft/vscode#165785]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (1 mo ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No

Steps to Reproduce:

1. create a folder <FOLDER> and init git 
2. cd <FOLDER> and clone some repo to it
3. create workspace and add all subfolder to folders
```
{
	"folders": [
		{
			"path": "sub1"
		},
		{
			"path": "sub2"
		},
                 {
			"path": "sub3"
		},
                 {
			"path": "sub4"
		}
	],
	"settings": {}
}
```
5. open workspace, open 'source control', there was missing a sub repo.

**Comment by lszomoru** [comment]
@Leathong, are you adding the second repository as a git submodule?
Could you please check the value of the `git.repositoryScanMaxDepth`?

**Comment by Leathong** [comment]
Setting repositoryScanMaxDepth to 2 is working, thanks!
