### ISSUE TITLE
the text in the terminal is invisible. I can still operate, but I can't see what is typed and I can not see output either

### ISSUE THREAD

**Issue by masonduyvesteyn** [microsoft/vscode#165796]
ADD ISSUE DESCRIPTION HERE

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.3 Safari/605.1.15
Embedder: codespaces

**Comment by masonduyvesteyn** [comment]
<img width="1165" alt="Screenshot 2022-11-08 at 8 09 52 pm" src="https://user-images.githubusercontent.com/114280883/200522935-c8186ddf-8bc7-43f2-80e9-0638f806562e.png">

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
