### ISSUE TITLE
Error hover is very small when it is at the right edge

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#165715]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/5047891/200345535-80ffaac5-e569-4c10-a499-b3160ab27441.png">

**Comment by aiday-mar** [comment]
Hover appears to the right of the mouse now. Closing the issue. 

<img width="1030" alt="Image" src="https://github.com/user-attachments/assets/ca998c2d-5f2c-4fe1-8490-b00b31dfd9a4" />
