### ISSUE TITLE
Edit Sessions tree view no longer populates when running `Show Edit Sessions`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165739]
`git bisect` points to 5ab18068041a148195b124a0ec03aa1e0a273d24, cc @alexr00

![image](https://user-images.githubusercontent.com/30305945/200396143-6410a80d-0911-4a15-83ac-7a4527314291.png)

**Comment by alexr00** [comment]
The `AbstractTreeView`, which is what Edit Sessions is using, is used mainly for extension provided trees. I fixed a race that can happen with extension provided trees that requires that the tree `dataProvider` be set before the `visible` event fire. It looks like internal users of `AbstractTreeView` like to set the `dataProvider` when the `visible` event fires, meaning that they now never set a `dataProvider`. I will look at another fix.

**Comment by alexr00** [comment]
Fixed by https://github.com/microsoft/vscode/pull/166029
