### ISSUE TITLE
Setting "mergeEditor.showCheckboxes" is not added to "mergeEditor.contribution.ts"

### ISSUE THREAD

**Issue by someC0d3r** [microsoft/vscode#165717]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
- 
![image](https://user-images.githubusercontent.com/88825803/200356009-4dee4e0f-bcf2-4699-aae6-565a93cd4cea.png)

With an update the checkboxes of the merge editor got removed and you can't display them...

The showDeletionMarkers got added:
![image](https://user-images.githubusercontent.com/88825803/200355340-1cec4f9b-8b96-4184-9c22-9cbdd9eca787.png)

showCheckboxes looks that:
![image](https://user-images.githubusercontent.com/88825803/200355409-3c05ab58-c5a7-4143-966c-f9a379561143.png)

So the getValue method is implemented for this setting, but the setting isn't displayed / can't be set. 

If I add this setting to my user settings:

![image](https://user-images.githubusercontent.com/88825803/200355735-b9deae13-f95d-4b5e-bb54-effc26386c20.png)

It displays the checkboxes again:
![image](https://user-images.githubusercontent.com/88825803/200355812-3250945c-c083-422e-9eaa-e5f919be92e8.png)

I don't know if this is intended, but it doesn't feel like it

**Comment by someC0d3r** [comment]
You can also see it's greyed out and it says that is an unknown configuration setting:
![image](https://user-images.githubusercontent.com/88825803/200356430-4edcd3ce-fad3-4a99-ab65-66d11afa5297.png)

**Comment by hediet** [comment]
This is by design.

Checkboxes are not supported/tested anymore, but we keep them until maintenance costs are too high.
