### ISSUE TITLE
some problems of "tasks.json"

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#16579]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:
1.
```js
{
	"version": "0.1.0",
	"command": "make",
	"suppressTaskName": true,
	"tasks": [
		{
			"taskName": "Release-Build",
			"isBuildCommand": true,
			"args": ["CC=gcc"]
		}
	]
}
```

Run Task:
Release-Build
<img width="714" alt="2016-12-06 5 07 54" src="https://cloud.githubusercontent.com/assets/18381153/20919400/96e77adc-bbd6-11e6-9c10-a85a3a361b9d.png">

2.
```js
{
	"version": "0.1.0",
	"command": "make",
	"suppressTaskName": true,
	"osx": {
		"tasks": [
			{
				"taskName": "Release-Build",
				"isBuildCommand": true,
				"args": ["CC=gcc"]
			}
		]
	}
}
```

Run Task:
make
Release-Build
<img width="701" alt="2016-12-06 5 07 05" src="https://cloud.githubusercontent.com/assets/18381153/20919373/78358b42-bbd6-11e6-932b-216106ef2e97.png">

**Comment by dbaeumer** [comment]
@Jackie-Yang I don't understand what the actual problem is.

**Comment by Jackie-Yang** [comment]
I mean the option "make" is redundant.

**Comment by dbaeumer** [comment]
Thanks now I see. Actually you tasks.json should not even work since the idea was never to all OS specific tasks. Need to see what is going wrong here.

**Comment by dbaeumer** [comment]
This got improved with the new terminal runner. It allows commands per task which don't automatically add the task name. And a task can have os specific commands. 

I will close the issue. If there are still improvements needed for the new terminal runner we should track them separately.
