### ISSUE TITLE
Search through descriptions of dev container features, not just the names

### ISSUE THREAD

**Issue by andreiborisov** [microsoft/vscode#165701]
When filtering dev container features, it would be very useful to take into account the features description, not just names:

![CleanShot 2022-11-07 at 17 00 56@2x](https://user-images.githubusercontent.com/13354491/200317064-aff77ed2-1b92-49c4-8ab3-7e24ec334ce9.png)

Should find the `fish` feature, yet it's not:
![CleanShot 2022-11-07 at 17 01 23@2x](https://user-images.githubusercontent.com/13354491/200317075-c26385ab-716b-4d3e-961c-fdadd080e4f0.png)

P.S. Not sure which repo is more appropriate, so I ended up double posting: https://github.com/microsoft/vscode-remote-release/issues/7483, please close the incorrect one 😇

**Comment by chrmarti** [comment]
Closing in favor of microsoft/vscode-remote-release/issues/7483.
