### ISSUE TITLE
Enable CustomTextEditor to match editorTextFocus keybindings

### ISSUE THREAD

**Issue by spenceryue** [microsoft/vscode#165777]
I want to implement a [`CustomTextEditor`](https://code.visualstudio.com/api/extension-guides/custom-editors#custom-text-editor) to render my JSON-based DSL with better formatting, while preserving the default text editing behavior.

Specifically, I'd like user keybindings to be preserved. But according to [this thread](https://github.com/microsoft/vscode/issues/99331#issuecomment-639060372), a custom editor will not match the `editorTextFocus` when clause, so most keybindings will fail to trigger.

In other words, my use case is to overwrite the "reading experience" while preserving the default "writing experience". This case is somewhere between those supported by the current [`CustomReadonlyEditorProvider`](https://code.visualstudio.com/api/extension-guides/custom-editors#readonly-custom-editors) and `CustomTextEditor` designs.

Some possible approaches to support the use case:
- Forward keyboard events from the webview to VS Code's keybinding system (and treating the editor as `editorTextFocus`)
- Add a `CustomStyledEditor` interface, which has no editing capabilities, but is only responsible for turning a `TextDocument` model into a view (perhaps with permission to set/intercept the cursor(s)).

##### Rendered output

<img width="989" alt="Anonymized" src="https://user-images.githubusercontent.com/11162148/200466174-a3132b07-b6b8-427e-b536-0f69cfe534e1.png">

##### JSON input
> ```json
> {
>   "••••••••": {
>     "•••••••••": ["•••", "••••", "•••••"],
>     "•": "•••••••••"
>   },
> 
>   "•••••": "••••••••••••••••",
> 
>   "•••••": {
>     "••••••••": null,
>     "•••••••••": "",
>     "••••••••": false,
>     "••••": "",
>     "••••••••": false,
>     "••••": "•••••••",
>     "•••": "•••••",
> 
>     "••••••••": {
>       "••••••••••": "•••••••••••••••••••••••••••••",
> 
>       "••••••••••••••": "•••••••••••••••••••••",
> 
>       "••••••••": {
>         "•••••": "•••••••••",
>         "••••••••": "•••••••••••",
>         "••••••••••••••••••••••": "••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••",
>         "••••••••": "•••••••••••",
>         "••••": "•••••••",
>         "••••••••": "•••••••••••••••••••"
>       },
> 
>       "••••••••": {
>         "••••": "••••••",
>         "•••••": {
>           "••••••••": [
>             {
>               "•••••••••": "•••••••••••••••••••••",
>               "••••••••": "•••••••••••",
>               "•••": "••••••••••",
>               "••••": "•••••••••••••••••••••••••••••••••••••••",
>               "•••": "••••••"
>             },
>             "•••••"
>           ],
> 
>           "••••••••": [
>             {
>               "••••": "•••••••",
>               "•••••": {
>                 "•••••••••": "••••••••••••",
>                 "••••": "•••••••"
>               },
>               "••••••••": "••••••••••••"
>             },
>             {
>               "••••": "••••",
>               "•••••": {
>                 "••••••••": "•••••••••••",
>                 "•••••••••": "•••••••••••••"
>               },
>               "••••••••": "••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••"
>             },
>             {
>               "••••": "••••••••••••••••••••••••••••••••",
>               "•••••": {
>                 "•••••••••": "••••••••••••",
>                 "••••": "•••••"
>               },
>               "••••••••": "•••••••••••••••••••••••"
>             }
>           ]
>         }
>       }
>     }
>   },
> 
>   "•••••••••••": "••••••"
> }
> ```

**Comment by mjbvz** [comment]
This is expected. The user keybindings for editors are implemented by VS Code. They will not do anything in custom editors, even if we enabled them inside custom editors

Instead you should add your own keybindings that implement this. We already forward keypresses inside of custom editors to VS Code to execute keybindings, so once you define a keybinding with the correct `when` clause it should just work
