### ISSUE TITLE
`Publish Branch` SCM action button text appears improperly localized

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#165735]
![image](https://user-images.githubusercontent.com/30305945/200390963-0946c390-3fc9-4915-9014-2affe0a63db2.png)

**Comment by joyceerhl** [comment]
Guessing this is because pseudolang ignores the comments

**Comment by TylerLeonhardt** [comment]
No this is weird... because what is displayed there is the key and not the value.
