### ISSUE TITLE
为什么不能完美支持C 语言

### ISSUE THREAD

**Issue by guoqingaa** [Microsoft/vscode#16578]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Bookmarks|alefragnani|0.10.1|
|jsrefactor|cmstead|0.5.3|
|cocos-creator|Chukong Technologies|0.0.1|
|cocos-debug|Chukong Technology|0.0.1|
|compulim-vscode-closetag|Compulim|0.1.2|
|vscode-clock|Compulim|0.0.1|
|jshint|dbaeumer|0.10.15|
|vscode-eslint|dbaeumer|1.1.0|
|vscode-npm-source|dkundel|0.0.3|
|vscode-great-icons|emmanuelbeziat|1.1.26|
|CppSnippets|hars|0.0.5|
|vscode-todo-parser|minhthai|1.8.3|
|vscode-clang|mitaki28|0.2.1|
|prettify-json|mohsen1|0.0.3|
|cpptools|ms-vscode|0.9.2|
|debugger-for-chrome|msjsdiag|2.3.2|
|vscode-icons|robertohuertasm|4.0.5|
|guides|spywhere|0.5.1|
|addDocComments|stevencl|0.0.8|
|html-preview-vscode|tht13|0.0.3|
|comment-snippets|Tobiah|0.2.0|
|debug|webfreak|0.12.3|
|extension-manager|webstp|0.0.5|
|JavaScriptSnippets|xabikos|1.2.0|
|clang-format|xaver|1.0.0|

---

Steps to Reproduce:

1.不能正常编写纯C语言项目，比如keil for c51 的mcu项目。
2.代码提示不完善，注释说明提示没有提供，写代码很差。

**Comment by alexandrudima** [comment]
rough translation:

Why not perfect support for C language

1. Can not normally write pure C language projects, such as keil for c51 mcu project.
2. Code hints are not perfect, note that note does not provide, write code is poor.

**Comment by guoqingaa** [comment]
对啊，在 keil for c51中，并没有合适的语法高亮支持，如 sbit 等关键字，另外includePath 也无法正常设置，鼠标移动到代码上，并不支持已经写又的注释说明Tips 提升，写C 语言代码的时候，代码提示也不够完整。无法查看引用计数。

Yes, in the Keil for C51, and there is no suitable syntax highlighting support, such as the “sbit“  keyword, includePath also cannot be set, move the mouse to the code, do not support has written comment and improve Tips, when writing C code, the code that is not complete. Cannot view reference count.

**Comment by guoqingaa** [comment]
in vscode do not support show Comment Snippets tags(Comment tips)（in C language）

 /** 
  * Note ..... 
  */ 
do not support show Tools Tips

**Comment by chrisdias** [comment]
This issue was moved to Microsoft/vscode-cpptools#392
