### ISSUE TITLE
Nerd Font is not working.

### ISSUE THREAD

**Issue by ZephTheHungryLoli** [microsoft/vscode#165786]
Nerd Fonts are simply not working. **I've tried all the solutions I can find on Google.** Still not working. 

Here's my terminal in VS Code.

![image](https://user-images.githubusercontent.com/92640971/200487300-7d230950-5ecc-4962-a9b3-8bbfa912f9ce.png)

Here's what the terminal actually looks like.

![WindowsTerminal_ZZfQ2uY7eB](https://user-images.githubusercontent.com/92640971/200487879-22d90e17-961c-4b31-8cb1-1457e18fe110.png)

Here's my settings.json.

![image](https://user-images.githubusercontent.com/92640971/200488446-dd61f09c-2e59-4809-bc9f-8a08440c5456.png)
![image](https://user-images.githubusercontent.com/92640971/200488368-7b9cbbe7-cc61-442e-b5b6-c6c746e9ab0a.png)

**Comment by IllusionMH** [comment]
Is it possible that font wasn't installed for all users?
https://github.com/microsoft/vscode/issues/163059#issuecomment-1281133218

P.S. Screenshots to show problem are great but screenshots of config/code are bad, please post them as code block next time.

**Comment by ZephTheHungryLoli** [comment]
@IllusionMH Thanks! The problem is solved now. 

And I'm new to the GitHub community so I didn't know how to post correctly. I will do it next time.
