### ISSUE TITLE
Launch widget needs ellipsis

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16577]
#16026

![image](https://cloud.githubusercontent.com/assets/22350/20919097/6f44bb48-bb9a-11e6-9eba-81ec0520e14d.png)

**Comment by isidorn** [comment]
Can not style this since I am now using a native select box
http://stackoverflow.com/questions/7289769/ellipsis-for-overflow-text-in-dropdown-boxes

Though it now looks slightly better than at your picture
