### ISSUE TITLE
TS Server Stopped 5 Times Everytime

### ISSUE THREAD

**Issue by dimaslanjaka** [microsoft/vscode#165750]
Type: <b>Bug</b>

just clone and open https://github.com/dimaslanjaka/static-blog-generator-hexo/tree/master/packages/instant-indexing

i dont know why, but every i open this project, TSServer always stopped

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (4 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.34GB free)|
|Process Argv|--crash-reporter-id 660dab0a-c1d6-497a-b9d7-ed96ba0dc144|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
intellij-idea-keybindings|k--|1.5.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30566498
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
iaj6b796:30604794
dbltrim-noruby:30604474

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by dimaslanjaka** [comment]
> Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

i was using normal VSCode, Not insider.

iam not tested it when extension disabled, i will test it at night later on home after work.

**Comment by mjbvz** [comment]
Please test both on insiders and with extensions disabled. You can download insiders here and use it alongside the stable release: https://code.visualstudio.com/insiders/

**Comment by dimaslanjaka** [comment]
> Please test on insiders and with extensions disabled. You can download insiders here and use it alongside the stable release: https://code.visualstudio.com/insiders/

its working when all extension disabled.
the error caused by local packages npm.

```txt
$root/package.json <-- here installed all packages from packages folder
$root/packages/package-name/package.json
$root/packages/package-name2/package.json <-- here installed the file:../package-name
```

i fixed them by deleting all node_modules from subfolders packages. then `npm install` from root project
