### ISSUE TITLE
The 'Format Document' not works

### ISSUE THREAD

**Issue by jackniu81** [Microsoft/vscode#16572]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|Spell|seanmcbreen|0.9.1|
|addDocComments|stevencl|0.0.8|
|html-css-class-completion|Zignd|1.0.3|

---

Steps to Reproduce:

1. use version 1.7.2
2. write a simple js file, use 'Format Document'. It not works. (It works before i upgrade to 1.7.2)

**Comment by alexandrudima** [comment]
@jackniu81 It works for me:

![16572](https://cloud.githubusercontent.com/assets/5047891/20921363/02aefbb0-bba4-11e6-9027-275df12c9006.gif)

**Comment by mjbvz** [comment]
@jackniu81  Can you please provide an example js file before formatting and what you see after formatting it, along with a short explanation of the expected formatting. Thanks

**Comment by jackniu81** [comment]
@mjbvz , find the reason now.
That was an old project that i use earlier version of VSCode before. I had typings folder, typings.json, jsconfig.json . After remove these folder/files, it is OK now.

**Comment by mjbvz** [comment]
Glad to hear

Closing as fixed.

Thanks.
