### ISSUE TITLE
Web: Cache gallery extension resources

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#165817]
The cache should persist across sessions and should be context aware, ie it could dispose old extension version resources if it is aware of a newer version, or dispose extension resources if the extension itself is disabled. The goal is avoid creating network requests.

**Comment by sandy081** [comment]
To verify:

- Open incognito mode and open network tab in developer tools, filter for `package.`
- Open insiders.vscode.dev
- Make sure there are no too many requests (it shall be around 60 to 70)
- Reload and make sure there are no requests
