### ISSUE TITLE
Files does not save

### ISSUE THREAD

**Issue by josdiaz-tech** [microsoft/vscode#165822]
Type: <b>Bug</b>

Files does not save, asking for admin privileges in locations of normal files, doesn't save when I click on "Retry as Admin".

I can't save even on previous workspaces

![image](https://user-images.githubusercontent.com/61276387/200602675-8b010baf-d977-459a-ad9d-f5847842a9ae.png)

When I click on the option, this happens:

![Screenshot 2022-11-08 111925](https://user-images.githubusercontent.com/61276387/200603301-4888d54c-4ee3-4ed2-bda5-056f88ecdec5.jpg)

This started happening on the recent release for me.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.95GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
bootstrap5-vscode|Anb|0.4.2
vscode-intelephense-client|bme|1.8.2
vscode-tailwindcss|bra|0.9.1
vscode-mysql-client2|cwe|5.8.16
vscode-markdownlint|Dav|0.48.1
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
getter-setter-constructor-php|Jes|0.0.1
create-relative-file|Jos|1.0.1
theme-monokai-pro-vscode|mon|1.1.21
vscode-apache|mrm|1.2.0
csharp|ms-|1.25.0
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
sqltools|mtx|0.25.1
sqltools-driver-mysql|mtx|0.4.0
file-and-folder-icons|nex|1.0.4
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
material-icon-theme|PKi|4.22.0
LiveServer|rit|5.7.9
rewrap|stk|1.16.3
errorlens|use|3.6.0
learn-vim|vin|0.0.28
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vim|vsc|1.24.3
php-debug|xde|1.29.0
php-pack|xde|1.0.3
php-intellisense|zob|1.0.11

(3 theme extensions excluded)

</details>

**Comment by bpasero** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by josdiaz-tech** [comment]
Hi, I tried to reproduce the problem in the insider build, In that version I don't have problems to save my files. So i guess that coul work as a temporary solution to my problem
