### ISSUE TITLE
Linux Configuration Doesn't work

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#16585]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

I want to create tasks for Mac and Linux:
This is my tasks.json

```js
{
	"version": "0.1.0",
	"command": "echo",
	"osx": {
		"args": [
			"osx"
		]
	},
	"linux": {
		"args": [
			"linux"
		]
	}
}
```
but when I select "Linux"
<img width="148" alt="2016-12-06 5 44 26" src="https://cloud.githubusercontent.com/assets/18381153/20920625/a865bcce-bbdb-11e6-81ed-d23a1af8aaa0.png">
the Configuration doesn't work
<img width="46" alt="2016-12-06 5 45 15" src="https://cloud.githubusercontent.com/assets/18381153/20920661/c96b4fa6-bbdb-11e6-970e-227de7b5004d.png">

**Comment by dbaeumer** [comment]
@Jackie-Yang what do you mean by selecting Linux. The right task is picked by the task runner automatically depending on the OS you are running. This is not user controllable. If you OS is OSX the task runner always adheres to the "osx" values.

**Comment by Jackie-Yang** [comment]
@dbaeumer But what is the meaning of "Linux" at the right corner

**Comment by dbaeumer** [comment]
I actually don't know :-) Do you have any extensions installed. Is the item visible when starting code with `--disable-extensions`

**Comment by Jackie-Yang** [comment]
@dbaeumer I see, it is a function of the extension "c/c++"
<img width="193" alt="2016-12-12 9 21 35" src="https://cloud.githubusercontent.com/assets/18381153/21085383/6a31aace-c04c-11e6-9819-dd709f34d422.png">

**Comment by dbaeumer** [comment]
@Jackie-Yang I will close the issue then since the task running system behaves as expected.
