### ISSUE TITLE
QuickFix LightBulb UI improvements

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#165844]
Currently the QuickFix light bulb UI is very context aware. Which means it only shows up on the current line.
Also for me, for some quick fixes the light bulb would only show up after I manually invoke it via `cmd+.`. Do we have multiple types of QuickFixes that influence this?

How can we make the light bulb UI more discoverable? We have been hearing this feedback from Java and Google.
In the future we might put additional functionality into the light bulb and I think it deserves to be more omnipresent.
Can we somehow be inspired by grammar suggestions that Word has - something that is easy to ignore but is still always reachable and has a more stable UI?

Opening this issue for some early discussion and only if we get some smart ideas we can plan the work some time in the future.

fyi @mjbvz @jrieken 

Current UI for reference.

![Screenshot 2022-11-08 at 18 59 41](https://user-images.githubusercontent.com/1926584/200640710-73e121fd-d130-41f5-b159-c37423770406.png)

**Comment by albertelo** [comment]
A very enthusiastic thumbs up!

**Comment by mjbvz** [comment]
@isidorn Extensions decide when the lightbulb shows up. For quick fixes, each extension can decide to only show the lightbulb when the cursors is directly on an error or an extension can decide to show quick fixes when the cursor is anywhere on a line with an error (or even when the cursor happens to be near an error in the document)

For grammar style suggestions, you can use [hint diagnostics](https://github.com/microsoft/vscode/blob/9c802415e11bf11230720bc4a93397c338121da8/src/vscode-dts/vscode.d.ts#L6063). These show as `...` under the range of the diagnostic. You can then add quick fixes for the diagnostic

**Comment by isidorn** [comment]
@mjbvz thanks for clarifying. 

>Is there a specific ux they have in mind?

Maybe @albertelo has some design proposals?

**Comment by akaroml** [comment]
@martinlippert Here's a discussion around improving the lightbulb 💡 in the editor area. This would make the rewrite proposals more discoverable while not at the cost of tons of noise.

**Comment by isidorn** [comment]
Assing to @justschen, and if you think this issue is not providing additional useful info feel free to close it. Thank you

**Comment by justschen** [comment]
Noting that there are new lightbulbs via the experimental **Editor > Lightbulb > Experimental: Show AI Icon** (  `editor.lightbulb.experimental.showAiIcon`), which can be shown everywhere, on code, or never.

> Also for me, for some quick fixes the light bulb would only show up after I manually invoke it via cmd+.. Do we have multiple types of QuickFixes that influence this?
Have been noticing this a lot recently as well - will look into why the lightbulb is showing up randomly after using Quick Fix even if it's turned off.
