### ISSUE TITLE
Preserve view state for untitled files between restarts

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16588]
re #16544

* have an untitled file, select a word on line 13
* exit, restart 
* 🐛 the cursor isn't preserved and not at 1,1

![dec-06-2016 10-48-45](https://cloud.githubusercontent.com/assets/1794099/20920782/95d5eb90-bba1-11e6-8127-fd0cadf4ae5e.gif)

**Comment by bpasero** [comment]
There is actually no view-state preserved for untitled files because we never had untitled files surviving a restart.

**Comment by bpasero** [comment]
I wanna check if this is low hanging for November, otherwise I will push it out.

**Comment by bpasero** [comment]
Will do in January, it is just a matter of persisting our untitled view state that we already track in https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/browser/parts/editor/stringEditor.ts#L36

**Comment by bpasero** [comment]
The view state of untitled editors should now preserve and restore after restart with hot exit enabled. This currently only works when having a folder opened. For empty workspaces we still need to tackle https://github.com/Microsoft/vscode/issues/207

**Comment by Tyriar** [comment]
Awesome :smile:

**Comment by bpasero** [comment]
* [ ] **To verify:** 
The view state of untitled editors should now preserve and restore after restart with hot exit enabled. This currently only works when having a folder opened.
