### ISSUE TITLE
C++ Programs wont build in VSC

### ISSUE THREAD

**Issue by WaltzingYard** [microsoft/vscode#165898]
Type: <b>Performance Issue</b>

I've moved Visual Studio Code from C: drive to D: drive, and now it wont build anything. I've tried editing the environment variables and configurations but is simply will not build.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.93GB (1.62GB free)|
|Process Argv|--crash-reporter-id 263bbc22-7882-4310-870f-089f6f87e0ae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    98	 13404	code main
    0	    42	  1956	   utility-network-service
    0	   237	  2884	   window (c_cpp_properties.json - C++ Files - Visual Studio Code)
    0	   133	  3516	   gpu-process
    0	   107	  6112	   shared-process
    0	    75	  3000	     ptyHost
    0	    78	 11688	     fileWatcher
    0	   135	 11244	   extensionHost
    0	    34	 10608	     c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\bin\cpptools.exe
    0	    11	   376	       console-window-host (Windows internal process)
    0	     4	 14236	       "c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64\bin\cpptools.exe"
    0	    46	  7736	         c:\Users\User\.vscode\extensions\ms-vscode.cpptools-1.12.4-win32-x64/bin/cpptools-srv.exe 10608 {071806DC-0F09-43D1-AB0E-1664456B65EC}
    0	    11	  9836	           console-window-host (Windows internal process)
    0	    99	 12044	     "C:\Users\User\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\User\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=11244
    2	    92	 12204	   issue-reporter
    0	    28	 12480	   crashpad-handler
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (c_cpp_properties.json - C++ Files - Visual Studio Code)
|    Folder (C++ Files): 10 files
|      File types: json(4) cpp(3) h(1) exe(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1)
|      Launch Configs: cppdbg;
```

</details>
<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
code-runner|for|0.11.8
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce1:30605430
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by WaltzingYard** [comment]
nvm i fixed it by uninstalling and reinstalling

**Comment by gjsjohnmurray** [comment]
> nvm i fixed it by uninstalling and reinstalling

@WaltzingYard please close your issue.
