### ISSUE TITLE
Unable to write to settings should offer an action to open settings

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16580]
1. Have an error in your user settings
2. View > hide activity bar
3. Notice an error that we are unable to write to settings and that the user should fix them

This error should have an action to open settings as most users have a hard time finding settings.

![screen shot 2016-12-06 at 10 31 13](https://cloud.githubusercontent.com/assets/1926584/20920193/495d4e90-bb9f-11e6-816d-f7b59005e8f7.png)

**Comment by bpasero** [comment]
Also: we should try to be more aggressive in writing to the settings file if this happens from the default settings editor. A trailing comma for example should not block us from doing the write. Since you see the result of the operation and you can undo, we can be more relaxed and validate less imho.

**Comment by BobbyBabes** [comment]
@bpasero Thanks for the hint to the trailing comma.
Just upgraded to 1.8.0. It was a bit confusing why I couldn't change settings through the pencil icon, but could with a manual change followed by Ctrl+S.
Now the "... correct errors/warnings in the file ..." part of the error message makes more sense.

**Comment by sandy081** [comment]
Enhanced config editing service to be aggressive when writing to buffer.
- If writing directly to disk, it looks for all validations
- If writing to buffer, all errors are ignored while updating and saved if not dirty.

**Comment by sandy081** [comment]
Config editing service was improved to be resilient with trailing commas. But all other errors are still valid and considered.

**Comment by sandy081** [comment]
All callees of configuration editing service are explicitly calling message service to show the message. This can be moved to config editing service to show message as an option.

**Comment by isidorn** [comment]
Reopening as I still get the same behavior as I described in my first comment

**Comment by sandy081** [comment]
Its fine to have Verification needed tag even if it was not closed. But not sure how did it come verification list? The query should not contain any open items :)

**Comment by isidorn** [comment]
I have my own cool query which obviously failed in this case :)

**Comment by gregvanl** [comment]
I think we need to add a button to open settings when this error occurs as mentioned in the initial comment. It comes up often in doc feedback verbatim where users don't know where to go when a settings.json error occurs.  Adding a button seems a good first step.

**Comment by gregvanl** [comment]
Adding @sandy081 to hopefully get this into the May milestone.
