### ISSUE TITLE
File name containing special characters(including Chinese characters) got garbled when sending text to powershell

### ISSUE THREAD

**Issue by redstoneleo** [microsoft/vscode#165800]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.73.0 (user setup)
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-01T15:34:06.111Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

- OS Version: 
Win11

Steps to Reproduce:
My .py file named `② 必须第一次就运行 PkgHelper.py`，when running it with  VS Code, I saw the name cannot be recognized correctly , it becomes garbled like the following :

```
PS F:\BaiduNetdiskDownload\SoftwareProject\LYYDownloader-dev> & C:/Users/22815/AppData/Local/Programs/Python/Python39/python.exe "f:/BaiduNetdiskDownload/SoftwareProject/LYYDownloader-dev/ 必须第一次就运行PkgHelper.py"
C:\Users\22815\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'f:\BaiduNetdiskDownload\SoftwareProject\LYYDownloader-dev\鎵撳
寘\ 蹇呴』绗竴娆″氨杩愯PkgHelper.py': [Errno 2] No such file or directory
```

**Comment by Tyriar** [comment]
I believe this is an encoding issue related to general PowerShell setup. @redstoneleo what happens when you copy `② 必须第一次就运行PkgHelper.py` and paste that into the PowerShell prompt?

**Comment by redstoneleo** [comment]
> I believe this is an encoding issue related to general PowerShell setup. @redstoneleo what happens when you copy `② 必须第一次就运行PkgHelper.py` and paste that into the PowerShell prompt?

PowerShell shows the name as it is - correctly.

**Comment by karrtikr** [comment]
@redstoneleo Can you try changing you shell to command prompt and see if it helps? Use `Select default profile` command to change it.

**Comment by Tyriar** [comment]
If this works in cmd it much be an issue with pwsh's encoding, so outside the scope of vscode.
