### ISSUE TITLE
Revisit `webview.ts` in workbench core

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#165889]
I was a bit surprised to find `src/vs/workbench/browser/webview.ts` and `src/vs/workbench/common/webview.ts`. As far as I know, webviews are a workbench contribution and not workbench core. I typically want the workbench core not provide things that only `contrib` depends on so I would recommend to move these files into `src/vs/workbench/contrib/webview/` component.

This becomes especially interesting as soon as we explore to lazily load `contrib` (https://github.com/microsoft/vscode/issues/164068)

If we have a dependency to anything in there from non-contrib then we can revisit that case by case, but I could not find any.

**Comment by mjbvz** [comment]
- `src/vs/workbench/browser/webview.ts`: This file should likely just be renamed as it's used by `webWorkerExtensionHost` too and not webview specific 

- `src/vs/workbench/common/webview.ts`: This file is used in ext host code and in notebooks. I'll see about moving it under `contrib/webview`
