### ISSUE TITLE
Web: random unit tests are timing out

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#165885]
Over the past weeks I see a trend of issues where web unit tests seem to timeout after 5 seconds. This looks very similar to https://github.com/microsoft/vscode/issues/155760 but now it seems to hit only macOS both Chromium and Webkit.

**Examples:**
* https://github.com/microsoft/vscode/issues/163619
* https://github.com/microsoft/vscode/issues/165278
* https://github.com/microsoft/vscode/issues/162102
* https://github.com/microsoft/vscode/issues/162329
* https://github.com/microsoft/vscode/issues/163901

In https://github.com/microsoft/vscode/issues/155760 I had tried to increase timeouts, update playwright, but nothing helped. So in the end I disabled Firefox tests altogether, but maybe the actual issue is just a lot more likely to occur in Firefox compared to other browsers.

For https://github.com/microsoft/vscode/issues/163619 I see direct use of `setTimeout` which I believe to be nondeterministic in browser tests. So I replaced that with our `runWithFakedTimers` utility in the hope it helps.

For others, its harder to understand what the reasons could be. Should we always enforce `runWithFakedTimers` in our tests?

@mxschmitt 👋 wondering if this rings any bell and if any other team ever reported a similar issue when using playwright for unit testing.

**Comment by rzhao271** [comment]
Potentially related: 

macOS browser unit test failure

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=193091&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33&l=17607

```
The followings tests are failing:
 - UserDataSyncService test first time sync from the client with changes - merge with profile (reason: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.)
```

**Comment by bpasero** [comment]
Not seen this in a while.
