### ISSUE TITLE
Dirty indicator shows after some delay when restoring from backup

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16584]
re #16544

* exit VS Code with an untitled (large) file
* restart VS Code
* 🐛 the untitled is retired and only after a large delay it is marked as dirty

![dec-06-2016 10-44-47](https://cloud.githubusercontent.com/assets/1794099/20920676/2f0c84f0-bba1-11e6-94cf-4eddfbd0e917.gif)

**Comment by bpasero** [comment]
@jrieken in that animation, was `large.txt` actually dirty? or are you saying the dirty decoration for `Untitled-1` kicks in late?

**Comment by jrieken** [comment]
Yes - `Untitled-1` is late by ~1sec

**Comment by bpasero** [comment]
I wonder if we could just store the dirty decoration as some view state and bring it back even before we look at the backups.

**Comment by Tyriar** [comment]
@bpasero at what point would the dirty indicator be invalidated if the backup no longer exists?

**Comment by bpasero** [comment]
Yeah it is tricky, needs more thought. The code that currently revives a backup could also act when a tab thinks it has a backup when in fact it does not.

**Comment by bpasero** [comment]
Also when you have many dirty files, it takes a long time until all backups are restored. This can easily be seen when doing a large find & replace operation without saving and then restarting.

**Comment by Tyriar** [comment]
The delay appears to be quite small for me now.
