### ISSUE TITLE
Git Clone: do the clone operation from the window

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16582]
Testing: https://github.com/Microsoft/vscode/issues/16505

The new "Git Clone" operation works fine but I wonder if it should work differently:
* you run the command
* you are being asked for a URL to clone
* you are asked for a folder to clone to
* a window opens on that folder
* the terminal opens running the clone operation

/cc @chrisdias

**Comment by chrisdias** [comment]
For long running clones I agree that this would be goodness. If the git output channel is sufficient (instead of a terminal), showing the editor as soon as possible then opening that channel would be good. That way i don't have to manage a terminal window once the clone is done.

**Comment by bpasero** [comment]
The alternative would actually be to show the git clone operation from the terminal of the current window. In Monaco for Azure we have a flow where we open the workbench, show the status of the git operation in the console and run an "npm install" after it is done.

**Comment by joaomoreno** [comment]
This asks for a tighter integration to Code than what I'd like. Especially considering that Code is going git-less, would such a behaviour be available from API?

**Comment by joaomoreno** [comment]
Can't do this now as an extension.
