### ISSUE TITLE
MacOS VSCode keypress to get accent print double character (again)

### ISSUE THREAD

**Issue by arkandias** [microsoft/vscode#165821]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.0 and 1.74-insiders
- OS Version: macOS 13.0 (Ventura)

Steps to Reproduce:

1. Open any file.
2. At the beginning of a word (but not at the beginning of a line, it must be just after a whitespace), press and hold a key to open the pop-up of accented characters.
3. Select an accented character (using either a number, the arrows, or the mouse). Then the unaccented character is printed first, followed by the accented character.

This is exactly the bug described in these issues (from 2017) :
https://github.com/microsoft/vscode/issues/32339
https://github.com/microsoft/vscode/issues/32985
https://github.com/microsoft/vscode/issues/33888
Except that this time the bug does not happen, unless the character is preceded by a whitespace.

**Comment by Lancelotbronner** [comment]
Also happens to me

```
Chip: Apple M1 Pro
macOS: Ventura 13.0 (22A380)

Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (2 days ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
```

**Comment by alexdima** [comment]
git bisect points to ffe90c3580f7bb4a4884292ad305939d9f6677b5 . FYI @Tyriar I will revert for now.
