### ISSUE TITLE
Terminal unresponsive

### ISSUE THREAD

**Issue by MariusGalyan** [microsoft/vscode#165896]
ADD ISSUE DESCRIPTION HERE

The terminal does not respond to commands. 

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416

**Comment by MariusGalyan** [comment]
thank you!
