### ISSUE TITLE
Untitled file isn't restored properly

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16589]
re #16544

* have an untitled file, make it show in slot one and two
* exit and restart
* 🐛 in slot two the file shows as empty

![dec-06-2016 10-51-20](https://cloud.githubusercontent.com/assets/1794099/20920897/1a8006aa-bba2-11e6-87a7-7a00655cb832.gif)

**Comment by Tyriar** [comment]
The gif is pretty blurry, is that `Untitled-1` in both editors?

**Comment by jrieken** [comment]
@Tyriar that's why it says 'have an untitled file, make it show in slot one and two'
