### ISSUE TITLE
Support Disassembly View in VS Code Web

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#165872]
Implementing the disassembly request as outlined in the [debug adapter protocol specification](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Disassemble) allows a debug adapter to expose the built in disassembly view in VS Code.

This works very well in a desktop environment, however our debugger also runs in the web extension host in vscode.dev and in this case, the disassembly view is not available.

As the view uses the debug adapter protocol for data, I assume there is no reason why this wouldn't just work, can it be enabled?

**Comment by roblourens** [comment]
> in this case, the disassembly view is not available.

Sorry, what's the problem? To my knowledge, this should work in web

**Comment by thegecko** [comment]
It's great top know this is intended to work.

Running on the desktop, a context menu item is available to "Open Disassembly View":

<img width="1120" alt="Screenshot 2022-11-09 at 09 22 00" src="https://user-images.githubusercontent.com/61341/200792005-291e5ba6-6472-4fe6-8f45-1489f55b212d.png">

However, in vscode.dev, the menu item doesn't exist, so it isn't clear how to open the view:

<img width="1056" alt="Screenshot 2022-11-09 at 09 24 32" src="https://user-images.githubusercontent.com/61341/200792091-dbbf64c1-6b14-4503-9576-9ed378c8802f.png">

**Comment by roblourens** [comment]
And you are using exactly the same extension in both cases? Could you check

- Does the command show up in the callstack context menu?
- Does it show up in the command palette (ctrl+shift+P > "Open Disassembly View")

One possibility is that your debugger doesn't declare this language in its supported languages array (in package.json). For some reason, we have code that checks that for this feature. So in desktop it could fall back on the cpptools extension or another one, and in web, that debugger is not activated.

**Comment by thegecko** [comment]
Thanks for the pointers @roblourens 

> Does the command show up in the callstack context menu

Yes! on desktop and web

> Does it show up in the command palette (ctrl+shift+P > "Open Disassembly View")

Yes! on desktop and web

> One possibility is that your debugger doesn't declare this language in its supported languages array (in package.json)

This was it, adding the languages array (not noticed this before), enabled the context menu. 

Something is a bit strange here, though. As you mention, I had cpptools (cppdbg) also installed on the desktop which somehow made this work. Disabling it on the desktop makes it work in same way as the web (context menu goes away) until I add the language array.

I'll close this issue, however.

**Comment by roblourens** [comment]
Yeah, it's a bit odd. However here it helps us avoid showing that option on some unrelated text file while you are debugging, so I will keep the check.
