### ISSUE TITLE
Bug when copy/pasting code from VSC to another editor

### ISSUE THREAD

**Issue by mikekenn** [microsoft/vscode#165819]
Type: <b>Bug</b>

Had some SQL that had some underscores in words. When i copy and pasted the code from VSC to Teams is removed all the underscores automatically and created a mass amount of confusion in the team as to why it worked for me but didnt work for anyone else.

Extension i am using is Oracle Explorer.

VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500B CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv|--crash-reporter-id 92df0489-8087-4ba4-84fc-c9ba8211ebd9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
doxdocgen|csc|1.4.0
vscode-pull-request-github|Git|0.54.0
better-cpp-syntax|jef|1.16.3
cmake-language-support-vscode|jos|0.0.7
vscode-docker|ms-|1.22.2
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.4.0
python|ms-|2022.18.1
vscode-pylance|ms-|2022.11.10
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.90.1
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.3
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2022.10.0
vsliveshare|ms-|1.0.5762
vsliveshare-audio|ms-|0.1.91
sqltools|mtx|0.25.1
oracledevtools|Ora|21.5.0
vscode-rapidapi-client|Rap|1.7.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-todo-highlight|way|1.0.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30566497
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce2:30605431
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by mjbvz** [comment]
This sounds like it is either caused by Oracle Explorer or Teams
