### ISSUE TITLE
The "alt" key in the built-in terminal causes a segfault

### ISSUE THREAD

**Issue by Jiliby** [microsoft/vscode#165801]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.73.0
Commit: 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
Date: 2022-11-03T14:04:08.642Z
Electron: 19.1.4
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.7-zen1-1-zen
Sandboxed: No

Steps to Reproduce:

1. open vscode
2. open built-in terminal
3. press "alt" or any combination (e.g. alt+tab)
4. vscode window disappears, segfault in kernel log ([segfault.log](https://github.com/microsoft/vscode/files/9960184/segfault.log))

using `"keyboard.dispatch": "keyCode"`, changing shell (zsh, bash) doesn't help

**Comment by deepak1556** [comment]
Can you provide the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

**Comment by Jiliby** [comment]
This is the problem, .dmp files do not appear in the specified directory

**Comment by deepak1556** [comment]
Can you try again with latest stable `1.74` and see if crash dumps are available.

**Comment by Jiliby** [comment]
Tried again on version `1.74`, the problem is still there and there are no crash dumps either.


[simplescreenrecorder-2022-12-14_11.48.37.webm](https://user-images.githubusercontent.com/114273437/207610687-05d4ad2e-a7af-4f77-afad-74c1fc6726cd.webm)

**Comment by deepak1556** [comment]
Are you running on wayland ? Can you collect the output of `code --verbose` till the crash happens.

**Comment by Jiliby** [comment]
I am running under xorg (xfce 4.16). Here is output from `code --verbose`.
[log.txt](https://github.com/microsoft/vscode/files/10228607/log.txt)

**Comment by deepak1556** [comment]
Nothing interesting in the logs, can you try the following and see if the issue persists in either runs

1) `code --disable-gpu`
2) `code --user-data-dir /tmp/vscode-new --extensions-dir /tmp/vscode-extensions`

**Comment by deepak1556** [comment]
Thanks for confirming, one last flag test. Can you run with `--no-sandbox --disable-gpu-sandbox` and confirm if the issue persists.

**Comment by deepak1556** [comment]
Sorry I am out of ideas for this issue, without crash dumps or repro on our end, it is hard to proceed further. You can use our remote tunnels and work with web version as alternative, steps at https://code.visualstudio.com/docs/remote/tunnels#_getting-started
