### ISSUE TITLE
top bar not showing correctly on ChromeOS insiders web editor(insiders.vscode.dev)

### ISSUE THREAD

**Issue by glitch128** [microsoft/vscode#165848]
ADD ISSUE DESCRIPTION HERE
The top bar does not show correctly when using the `window-controls-overlay` API on vscode insiders web
Version: 1.74.0-insider
Commit: 2282be522a8031209a739783baede67bfa9fc95a
User Agent: Mozilla/5.0 (X11; CrOS x86_64 14989.107.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
Embedder: vscode.dev

![Screenshot 2022-11-08 10 09 34 AM](https://user-images.githubusercontent.com/78228404/200643516-d1c5e4a1-71c6-4ccc-a398-b67c24285886.png)

**Comment by glitch128** [comment]
ok, yeah, now I know its not working correctly 
![image](https://user-images.githubusercontent.com/78228404/200650473-d33d7dc3-66dc-4de3-ad3d-a8a86666d5e5.png)

**Comment by glitch128** [comment]
oh, also, the menu bar disappears when the window stretches from the top to the bottom of the screen.

**Comment by glitch128** [comment]
ok, so one thing that I just found is that the `div.monaco-toolbar` has no `webkit-app-region: no-drag;`  nor does any of the elements inside the div have the CSS property, so I think that adding the CSS property would fix the command center not being able to be selected.

**Comment by sbatten** [comment]
I have no way to test this, but I made some changes that should be in insiders in early January that may have fixed this.

**Comment by sbatten** [comment]
@glitch128 this is a bug in the fullscreen logic with the menu. as a workaround, please set `window.menuBarVisibility` to `visible`
