### ISSUE TITLE
Hitting spacebar does not replay currently focused audio cue

### ISSUE THREAD

**Issue by jooyoungseo** [microsoft/vscode#165863]
CC @isidorn

## Reproducible Steps

1. Launch `Help: List Audio Cues`
2. Arrow-down to "Folded Area on Line"
3. [Let's say you want to hear the currently focused audio cue again] press spacebar
4. Focus moves back to "Error on Line" as soon as you press spacebar

## Expected Behaviors

It would be great if spacebar could trigger currently focused audio cue.

## System Info

Version: 1.74.0-insider (system setup)
Commit: 2282be522a8031209a739783baede67bfa9fc95a
Date: 2022-11-08T05:23:21.062Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by isidorn** [comment]
Thanks for opening this issue but this is how our QuickPick behaves. Space will always enter space in the Quick Pick input box, and you can only use up/down to navigate through quick pick inputs.
I am not sure if we can do anything to improve this. @meganrogge we might want to close this as designed.
