### ISSUE TITLE
Search: Exclude Folder from Search removes existing exclusion settings 

### ISSUE THREAD

**Issue by BillDenton** [microsoft/vscode#165997]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  Put something in "files to exclude folder"
2.  Select "Exclude Folder from Search"
3.  Original "files to exclude folder" is deleted.

Expected that "Exclude Folder from Search" would add to the "files to exclude folder". Unable to exclude multiple folders or add my own exclusions as well as those from "Exclude Folder from Search".

**Comment by osortega** [comment]
The repro steps are a bit unclear to me, do you mind adding more info? 

/gifPlease
