### ISSUE TITLE
Workspaces aren't restored properly

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16592]
* have two VS Code windows open, both showing a workspace/folder
* exit
* delete one of the workspaces/folders
* restart
* 🐛 Instead of showing the other/remaining workspace an empty workspace/no folder is shown

**Comment by bpasero** [comment]
I am actually not sure this is hot exit related, I think this happened in stable already.

**Comment by bpasero** [comment]
@jrieken I cannot reproduce other than having dirty files in both windows and quitting. in that case reopening one window as empty window is actually expected because we need to restore the dirty files within even when the folder they where created in does not exist anymore.
