### ISSUE TITLE
insert final new line should also trim additional lines

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16599]
* have a file with 10 final new lines
* save with the setting enabled
* you still have 10 lines, should only be one

**Comment by bpasero** [comment]
Since this is neither how ST, nor our own editor config extension behaves nor I think it makes any sense, treating as feature request.

**Comment by jmlntw** [comment]
+1 for this. Also Atom removes additional lines on save.

**Comment by jmlntw** [comment]
I wrote a extension to do this.
https://marketplace.visualstudio.com/items?itemName=jmlntw.vscode-ensure-single-final-newline

**Comment by chvndb** [comment]
@jmlntw cheers, works like expected.

Would make sense that this is native to vscode and could be configured to be turned on and of with:

```
{
  "files.trimFinalNewlines": true/false,
}
```

**Comment by alexandrudima** [comment]
I've tested PR #33947 and all looks good.
