### ISSUE TITLE
translation lost

### ISSUE THREAD

**Issue by yoyo837** [microsoft/vscode#165974]
Type: <b>Bug</b>

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 4, 4|
|Memory (System)|32.00GB (0.36GB free)|
|Process Argv|--crash-reporter-id 3314e47b-b93c-4574-a628-7c01ae6f4bea|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
browse-lite|ant|0.3.0
vite|ant|0.2.5
vscode-tailwindcss|bra|0.9.1
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-svgviewer|css|2.0.0
dart-code|Dar|3.52.1
flutter|Dar|3.52.0
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.0.4
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
git-project-manager|fel|1.8.2
auto-close-tag|for|0.5.14
code-runner|for|0.11.8
copilot|Git|1.58.7236
go|gol|0.36.0
todo-tree|Gru|0.0.220
vscode-codeowners|jas|1.1.1
i18n-ally|lok|2.8.1
start-git-bash|McC|1.2.1
vscode-language-pack-zh-hans|MS-|1.73.11090913
vsliveshare|ms-|1.0.5762
vscode-react-native|msj|1.10.0
nutui-vscode-extension|nut|0.0.2
vetur|oct|0.36.1
vscode-stylelint|sty|1.2.3
vscode-mdx|uni|1.0.3
windicss-intellisense|voo|0.21.6
vscode-icons|vsc|12.0.1
volar|Vue|1.0.9
vscode-typescript-vue-plugin|Vue|1.0.9
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce1:30605430
iaj6b796:30604794
dbltrim-noruby:30604474

```

</details>

**Comment by yoyo837** [comment]
![WX20221110-111408](https://user-images.githubusercontent.com/6134547/200992223-f09e4224-e76f-4b62-bb05-6caca591739a.png)

**Comment by yoyo837** [comment]
When I upgraded to 1.73.1 and I quit `vscode` completely and reopened it, still having this issue.

**Comment by yiliang114** [comment]
Maybe related:

![image](https://user-images.githubusercontent.com/11473889/201016300-99a189c2-d513-4616-bb5a-1c6870ac1b8a.png)

There is no translation here, it is all the default English.

 [vscode.git.i18n.json](https://github.com/microsoft/vscode-loc/blob/main/i18n/vscode-language-pack-zh-hans/translations/extensions/vscode.git.i18n.json)

**Comment by TylerLeonhardt** [comment]
@yoyo837 can you tell me what version of the language pack you are using? You should be able to see that in the Extensions view.

**Comment by yoyo837** [comment]
> @yoyo837 can you tell me what version of the language pack you are using? You should be able to see that in the Extensions view.

Yes, here it is:

|Extension | version|
|---|---|
|vscode-language-pack-zh-hans | 1.73.11090913 |

**Comment by TylerLeonhardt** [comment]
@yoyo837 are you able to install the version right before that one? If you find the language pack in the Extensions view, you should be able to select a different version.

**Comment by yoyo837** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6134547/201136429-fbca49e0-9a71-46e6-8118-35afed43cd75.png">

<img width="818" alt="image" src="https://user-images.githubusercontent.com/6134547/201136549-0733a24a-85eb-4029-a81a-fa709cdf865c.png">

Yes, I back to the previous version and it works fine now.

**Comment by TylerLeonhardt** [comment]
I am working to get that version without the translations unlisted from the marketplace so that the older version with the correct strings is used for 1.73.

**Comment by sandy081** [comment]
@TylerLeonhardt Please reach out to MP team (@SaiKanth007) for getting the extension to be unlisted.

**Comment by TylerLeonhardt** [comment]
Just to enumerate workarounds... using [VS Code Insiders](http://code.visualstudio.com/insiders) is also a valid workaround

**Comment by yoyo837** [comment]
Looks like language version `1.73.11090913` has been withdrawn.

**Comment by TylerLeonhardt** [comment]
Yes the bad version has been deleted... however, if you have a client that has updated to that "bad version" you will not be downgraded to the "good version", unfortunately.

I would need to release a new `1.73` version which is doable but a lot of work and potentially error prone...... so instead what we will do is just wait for the next `1.74` release of VS Code which will grab a newer version of the language pack that will work with it.

You can verify that the new version of 1.74 will work by installing VS Code Insiders.

**Comment by TylerLeonhardt** [comment]
Verification for the team: install VS Code Insiders, Install a language pack, make sure Git extension is localized (for the most part)

**Comment by yoyo837** [comment]
> Yes the bad version has been deleted... however, if you have a client that has updated to that "bad version" you will not be downgraded to the "good version", unfortunately.
> 
> I would need to release a new `1.73` version which is doable but a lot of work and potentially error prone...... so instead what we will do is just wait for the next `1.74` release of VS Code which will grab a newer version of the language pack that will work with it.
> 
> You can verify that the new version of 1.74 will work by installing VS Code Insiders.
> 
> I'll close this since there isn't anything left for us to do besides "business as usual" with releasing a new version projected to be at the end of the month/first week of Dec.

Great! Thank you!

**Comment by Nameonlyisname** [comment]
oh,great

**Comment by jingqinglin** [comment]
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/6134547/201136429-fbca49e0-9a71-46e6-8118-35afed43cd75.png">
> 
> <img alt="image" width="818" src="https://user-images.githubusercontent.com/6134547/201136549-0733a24a-85eb-4029-a81a-fa709cdf865c.png">
> 
> Yes, I back to the previous version and it works fine now.

Hello, how can I get the version history list?
