### ISSUE TITLE
More comfortable creating files

### ISSUE THREAD

**Issue by qingdkj** [microsoft/vscode#165985]
When there are many files in the file list, it is somewhat inelegant to create a file or folder in the open root folder by clicking somewhere else to make it focus on the root folder.

So I wish there was a more comfortable way to create files in the open root folder.

**Comment by lramos15** [comment]
Don't worry you have it's related to https://github.com/microsoft/vscode/issues/151630

**Comment by lramos15** [comment]
Will collapse into #151630 for issue cleaning purposes
