### ISSUE TITLE
Cannot Type In Terminal

### ISSUE THREAD

**Issue by Dansah2** [microsoft/vscode#165964]
I am unable to type in the terminal on VS code. Because I can't type I can no longer run or submit projects.

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6.1 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
