### ISSUE TITLE
Switch files(with comments) many times, then an warning message shown up in the console panel says "potential listener LEAK detected"

### ISSUE THREAD

**Issue by KrabsWong** [microsoft/vscode#165986]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Web version. github.dev
- OS Version: Chrome 107.0.5304.87(arm64), macOS 13.0

Steps to Reproduce:

1. Open any file of any pr with github.dev
2. Add comments to any file, such as file A
3. Switch to any other file of this pr
4. Switch back to the file A
5. Repeat step 3 and 4 (many times)

Then you will get an waning message in the console panel as the screenshot below

<img width="851" alt="image" src="https://user-images.githubusercontent.com/12368943/201034155-da033dd6-4a7e-47dc-a5a6-9195abb3075a.png">

**Comment by alexr00** [comment]
Thanks for reporting this!
