### ISSUE TITLE
Unable to use Single Quote

### ISSUE THREAD

**Issue by jadetrue** [microsoft/vscode#165936]
Type: <b>Bug</b>

The issue happens despite disabling all extensions and clearing settingsjson file.

Attempt to type a single quote in the editor.
Tooltip error saying "No definition found".

![image](https://user-images.githubusercontent.com/39219696/200891790-25695ecf-1234-49a0-8161-1b88c3c998dd.png)

Keyboard Language: UK English and recommended on Windows configuration.

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4700U with Radeon Graphics          (8 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.23GB (6.55GB free)|
|Process Argv|--crash-reporter-id aab3b39a-c6e6-4939-b346-2c88add75822|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.1
npm-intellisense|chr|1.4.2
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
theme-monokai-pro-vscode|mon|1.1.21
vsliveshare|ms-|1.0.5762
color-highlight|nau|2.5.0
vscode-extension-auto-import|Nuc|1.4.3
material-icon-theme|PKi|4.22.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
code-spell-checker|str|2.11.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30605430
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by jadetrue** [comment]
Thanks @gjsjohnmurray, I have checked this and nothing is found.

**Comment by gjsjohnmurray** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues for further advice.
