### ISSUE TITLE
[css] @namespace is not syntax highlighted

### ISSUE THREAD

**Issue by dstorey** [Microsoft/vscode#1659]
Works correctly in the parser for linting and in Intellisense, but isn't syntax highlighted as missing from css.plist

![screen shot 2015-12-26 at 2 37 41 am](https://cloud.githubusercontent.com/assets/465069/12006056/9bc57176-ab79-11e5-8cd7-bc98db523dff.png)

Syntax should be:

 namespace
    : NAMESPACE_SYM S\* [namespace_prefix S_]? [STRING|URI] S_ ';' S*
    ;
  namespace_prefix
    : IDENT
    ;

My knowledge of the syntax of css.plist and regexp isn't good enough at the moment to work out how to add the optional IDENT, as there is no predefined ident like there is for strings, etc. I know how to highlight the @namespace and string component though. 

I figure the IDENT should be coloured the same as @namespace as that is how the media type token is coloured for '@media media-type'

**Comment by dstorey** [comment]
IDENT is also needed for @keyframes, so would be good to add it in a way that can be reused, rather than defining it twice.

**Comment by aeschli** [comment]
This issue was moved to textmate/css.tmbundle#24

**Comment by aeschli** [comment]
This got fixed in the meantime.
