### ISSUE TITLE
Debug widget has some UI issues

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16596]
Testing #16026

Clone the [vscode-smoketest-express](https://github.com/Microsoft/vscode-smoketest-express) repo and checkout the `chrome-debug` branch.

Make sure Chrome is running in your machine **without** the `--debug` flag. We want the Chrome debugger to fail further ahead.

1. Put breakpoints in `routes/index.js:6` and `public/script.js:5`.
2. In debug viewlet, start `Server`.
3. In debug viewlet, start `Chrome`. Do not press Continue once the debugger breaks.
4. After 10 seconds, the Chrome debugger will timeout.

![image](https://cloud.githubusercontent.com/assets/22350/20920491/6d270324-bba0-11e6-8ac8-8f8282496401.png)

5. Dismiss the error messages.
6. Hit Play. Notice the widget:

![image](https://cloud.githubusercontent.com/assets/22350/20920536/9e2e8bb8-bba0-11e6-9aa7-9338c5186dbc.png)

6. Refresh the browser. It should hit a server breakpoint. Notice the widget:

![image](https://cloud.githubusercontent.com/assets/22350/20921604/3de60dee-bba5-11e6-93ec-06c8d96774e8.png)

---

I somehow also was able to get it stuck in this state, while playing around... No steps for this:

![image](https://cloud.githubusercontent.com/assets/22350/20921544/edbde652-bba4-11e6-9a29-3228160e4c3f.png)

**Comment by joaomoreno** [comment]
FYI, when everything is well setup (Chrome debugger properly working), I still hit this situation:

![image](https://cloud.githubusercontent.com/assets/22350/20922321/09ea51a0-bba8-11e6-9ab7-7d89ad62f207.png)

**Comment by isidorn** [comment]
The maximum call stack was actually also responsible for this issue.
The bottom line problem was that the select box in the actions widget was emitting an event on which debug reacts changing the select box which emits the event again and so on...
