### ISSUE TITLE
Add collapse to Sticky Scroll 

### ISSUE THREAD

**Issue by loud-mouth2** [microsoft/vscode#165932]
Please add code collapse option to sticky scroll headers. I think this feature might help improve utility.

**Comment by jrieken** [comment]
Not sure what you mean by collapse? Please provide more detail

**Comment by loud-mouth2** [comment]
The downward/upward arrow that provides [this functionality](https://dev.to/rfornal/vs-code-collapse-and-expand-4710). Sorry I should've used the term folding instead.

**Comment by jrieken** [comment]
I still don't understand. What do you want to fold here? Folding would always hide everything below the folded element (since this is based on containment) which would make this just like the `editor.stickyScroll.maxLineCount` setting
