### ISSUE TITLE
Way to easily dismiss watermarks

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16595]
Refs #16560

There should be a way to easily dismiss the watermark. Optimally this would be a setting
'workbench.tips.visible', and there would be an explicit action on the start screen which would flip this setting.

The users which would appreciate this:
* expert users that do not need help and like the clean UX that vscode is known for
* users that have already read through all the watermark tips we give them

**Comment by chrmarti** [comment]
Users benefit from the commands and their shortcuts always being shown so the shortcuts can be memorized over time. The design was chosen to be unobtrusive. More actions on the start screen will just clutter that and new users inadvertently dismissing the commands will loose the watermark's benefit. No need to make it more complicated.

**Comment by isidorn** [comment]
Why do you say that users benefits from the same commands being shown over and over?
The design is obtrusive for how I use vscode, I understand it is not obrusive for all the users. However for users like me we should provide a simple way to dismiss these watermarks. I do not see a downside to that.

At the very least please provide a setting.

@Microsoft/vscode for opinons / feedback

**Comment by roblourens** [comment]
I would use a setting to hide it, but I think an explicit action to hide it, like an X button, would be unnecessary visual clutter.

**Comment by chrmarti** [comment]
@isidorn New and occasional users will appreciate being reminded of some of the basic keyboard shortcuts.

Clearly we need to gear the out-of-the-box experience more towards the new to intermediate user than the expert user while still allowing the expert user to tailor the product to specific needs.

Before we introduce yet another setting: How would the watermark become useful to expert users?

**Comment by Tyriar** [comment]
I agree with @roblourens; I'd use a setting to beautify the workbench a little more but a button on the UI would be overkill.

On being useful to power users, I was tossing around an idea of using it for a means for me to learn keybindings by allowing me to either set a list or showing random ones similar to a tip of the day. I've found I just completely ignore it at this point though so I'm not sure I would use it.

**Comment by roblourens** [comment]
I was thinking about that too but I don't see it often enough to be useful for power-user tips. I usually have a file open on top of it.

**Comment by isidorn** [comment]
@chrmarti do you accept PRs that introduce a setting to hide the watermark?
Not sure how to make the watermark useful to expert users. But to users like me who like the clean look of vscode the only solution is to hide it IMHO.

**Comment by chrmarti** [comment]
Sure, go ahead.
