### ISSUE TITLE
Error activating auto attach: Error: We did not find `node` on your PATH, so we cannot enable auto-attach in your environment

### ISSUE THREAD

**Issue by rpig** [microsoft/vscode#165922]
<img width="1316" alt="image" src="https://user-images.githubusercontent.com/6789139/200847393-184b311f-cc7c-449d-920a-a231d246fbf7.png">

I try to config `runtimeExecutable` and `PATH`，but it seem not work

**Comment by connor4312** [comment]
Fixed with https://github.com/microsoft/vscode-js-debug/issues/1392
