### ISSUE TITLE
Mac can be cases-sensitive

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16591]
re #16544

> Backup files with same string but different casing on Linux (as the file system is case sensitive), make sure there are no collisions

This is more FYI that also on macOS case-sensitive file systems exist. The default is insensitive but it's easy to change. Unsure if hot-exit will handle that gracefully?

**Comment by bpasero** [comment]
This is some general debt we have which imho we can only get out by checking right on startup if you can create 2 files with different casing and then store this result somewhere accessible in all places throughout the code where today we do a simple assumption.

**Comment by jrieken** [comment]
Yeah - I am just a little worried that in the `workspace.json` stores all path in its lowercase variant which seems like a good way to get in trouble.

**Comment by bpasero** [comment]
@Tyriar wouldn't it be better to store the case as it comes in from the user but when comparing to another path just lowercase both?

**Comment by Tyriar** [comment]
@bpasero with workspaces yes, paths are a little more tricky though as we need the path in order to generate the hash. Maybe the best way to fix this is to add some `IEnvironmentService.arePathsCaseSensitive` or something and use that instead of `isLinux`?

**Comment by Tyriar** [comment]
http://apple.stackexchange.com/a/22304 shows how you can query the disk, attempting to write and then caching it would probably be a better, more general solution?

**Comment by bpasero** [comment]
@Tyriar yes, it should be in the environment service and it is as simple as doing the writing I would say instead of spawning some disk commands that are platform dependent.

I see the problem with the hash, so always using lowercase makes sense for those if you run on a case insensitive file system.

**Comment by Tyriar** [comment]
Storing the paths as they are (whether the FS case sensitive or not) is covered in #16829
