### ISSUE TITLE
Task quick pick prompts automatically

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#165946]
While working on VS Code or Jupyter repository, I found the task quick pick often prompts automatically, usually after

* `yarn`
* `yarn watchd` (or `yarn compiled` in Jupyter)

When this happens, we will see the task quick pick like you trigger it manually. Dismissing it and in a bit later it might come back.

**Comment by rebornix** [comment]
https://user-images.githubusercontent.com/876920/200920692-58a87590-e12d-49b5-abfc-6a3e1eb9244b.mov

**Comment by meganrogge** [comment]
@rebornix that is really strange. do you have a custom keybinding set for `runTask`?

**Comment by rebornix** [comment]
@meganrogge I don't have any keybindings related to tasks. And also it can prompt randomly (not right after typing). Do we have any log that can tell how the task quick pick is opened?

**Comment by meganrogge** [comment]
We do not currently. Do you know of an example where we identify the trigger source of a command?

If it is not keybindings causing this, then it's possible an extension is invoking this command directly.

https://github.com/microsoft/vscode/blob/37f1112e598e254ba5f0b7f3632a34815380eede/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L411

**Comment by rebornix** [comment]
I did a search for `workbench.action.tasks.runTask` in extension folder and found I have `boukichi.watch-run` extension installed ;( Couldn't recall when I installed this extension.

It's a bummer that our log won't tell you how calls a specific command but luckily text search works.
