### ISSUE TITLE
Quick fixes support for zsh (with OhMyZsh & powerlevel10k)

### ISSUE THREAD

**Issue by boumanb** [microsoft/vscode#165996]
Does this issue occur when all extensions are disabled?: ~~Yes/No~~ does not apply since it is related to `ms-vscode-remote.remote-containers`.

- VS Code Version: 1.73.1
6261075646f055b99068d3688932416f2346dd3b
x64
- OS Version: Manjaro Linux x86_64 (5.15.76-1-MANJARO)

Steps to Reproduce:

_Prerequisites: remote container with zsh using OhMyZsh & powerlevel10k installed. I also had to add `typeset -g POWERLEVEL9K_TERM_SHELL_INTEGRATION=true` to the `~/.p10k.zsh` file so that shell integrations works, as described [here](https://github.com/microsoft/vscode/issues/146587)_

1. Use `ms-vscode-remote.remote-containers` and get into a remote container terminal using `zsh`
2. Make sure to `cd` to a folder that contains a Git repository and `git checkout -b` to a branch that does not yet exist on the remote repository
3. Run `git push` and see that a quick fix **is not** being provided
![image](https://user-images.githubusercontent.com/29407220/201047106-8803ee59-a9a9-4924-bff0-36b39adef7c0.png)
4. Now do the same as above using a terminal that is using `bash` and see that a quick fix **is** being provided
![image](https://user-images.githubusercontent.com/29407220/201047372-9a51fed3-fbc7-43c2-8709-232ca1d3402e.png)

**Comment by Tyriar** [comment]
@meganrogge this is probably related to the fact that p10k doesn't use support all our shell integration, I think it misses the executed command (633 E) and cwd.

**Comment by meganrogge** [comment]
Yes, thus I put this on the backlog

**Comment by Tyriar** [comment]
- because of that we cannot _reliably_ detect the command line text, so the feature is disabled by design as reliability is essentially when we are suggesting to run a command. So this is as designed for us.
