### ISSUE TITLE
Editor preview tab auto-close, when navigating out of it

### ISSUE THREAD

**Issue by kmolerov** [Microsoft/vscode#16590]
When you click on file and have preview tab opened (header of tab is in italic), it would be nice, if VSCode is closing it automatically, when you navigate out of it (clicking on tab header of another opened filed).
There should also be an option in configurations to turn this off.
"workbench.editor.enablePreviewAutoClose": true - default value

**Comment by bpasero** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
