### ISSUE TITLE
Disable progress indicator in TreeDataProvider

### ISSUE THREAD

**Issue by pwsses** [microsoft/vscode#166089]
Hello.
My custom tree view base on TreeDataProvider has tree Item which update every second with time information.
So I call  `this._onDidChangeTreeData.fire(treeItem)` it work well. 
But, In tree view, progress Indicator is visible every time for a very short period of time.  because call `_onDidChangeTreeData.fire`
I want progress indicator to disable or no-display. but no way to do.
If you know way, please share to me. or please make option to it.
thank you.

**Comment by alexr00** [comment]
This is by design. Whenever the tree is updating we want to show progress.
