### ISSUE TITLE
Zoom in Zen mode brings back status bar, activity bar

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#16600]
Testing #15647

OSX
1.8.0-insiders 
commit: a8d5

To repro:
- turn on zen mode (CMD+K, Z)
- zoom in or out (CMD++ or CMD+-)

result: activity bar and status bar reappear!

**Comment by isidorn** [comment]
After investigation this is a duplicate of https://github.com/Microsoft/vscode/issues/16597 which is fixed now
