### ISSUE TITLE
VS code "fileWatcher" constantly uses the CPU

### ISSUE THREAD

**Issue by DJAGER47** [microsoft/vscode#166097]
Type: <b>Bug</b>

I had a problem not too long ago, fileWatcher uses the processor on a regular basis. I don't understand what happened.
CPU consumption is about 6-7% all the time.
"C:\Users\admin\AppData\Local\Programs\Microsoft VS Code Insiders\Code - Insiders.exe" --ms-enable-electron-run-as-node "c:\Users\admin\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\bootstrap-fork" --type=fileWatcher

The only thing that helps is deleting the folder: C:\Users\admin\AppData\Roaming\Code Insiter

But it doesn't last long and the problem appears again.

VS Code version: Code - Insiders 1.74.0-insider (ef415578d1b1019db585718968a303eeca4b8979, 2022-11-11T05:19:14.666Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.36GB (5.72GB free)|
|Process Argv|--crash-reporter-id 1b249364-e946-4e18-a356-7726644a2436|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30590116
vsccc:30564266
pyindex848:30577858
nodejswelcome1:30587009
gswce1:30602633
34cci188:30599831
pyind779cf:30600160
dbltrim-noruby:30604474

```

</details>

**Comment by bpasero** [comment]
Does it happen with any workspace you open?

**Comment by DJAGER47** [comment]
![image](https://user-images.githubusercontent.com/21174689/201361080-5eff133a-6cec-4a50-9d27-389f1acb5b07.png)
Yes. Even without an open project folder

**Comment by DJAGER47** [comment]
After another update, everything was fine.
