### ISSUE TITLE
Hope: Add a generic function && enhance 

### ISSUE THREAD

**Issue by crperlin** [Microsoft/vscode#1660]
- Minimap
![image](https://cloud.githubusercontent.com/assets/8272877/12006051/7a250c80-abff-11e5-898d-8512e6fc1827.png)

- keyword code goto (sublime -> ctrl+p [input #])

![image](https://cloud.githubusercontent.com/assets/8272877/12006063/1b68e22e-ac00-11e5-9ee3-615cbde205b4.png)

- bookrmark goto( ctrl+f2 set/unset bookmark , f2 goto next bookmark , shift+f2 goto last bookmark)

![image](https://cloud.githubusercontent.com/assets/8272877/12006071/a23cf132-ac00-11e5-9952-b2f55b922812.png)

- enhance inner format function,(html write to jsp or c#,mix format) -- webstorm can setting !

- like atom color plugin highlight or webstorm color show or sublime use plugins
![image](https://cloud.githubusercontent.com/assets/8272877/12006083/55ff6542-ac01-11e5-8c91-a559664fddab.png)
![image](https://cloud.githubusercontent.com/assets/8272877/12006087/6d8c2d3a-ac01-11e5-9077-1733435de35b.png)

Thankyou !!!

**Comment by bpasero** [comment]
@crperlin please open individual issues for individual feature requests.
