### ISSUE TITLE
Code.exe: Exec format error

### ISSUE THREAD

**Issue by Sangresz** [microsoft/vscode#166017]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Windows 10 Home (21H2) | Kali linux Release: 2022.3 (WSL)

### Steps to Reproduce:

1.  running `code` inside the wsl istance

Starting from today whenever i try to run `code` inside wsl this message appears
![image](https://user-images.githubusercontent.com/96419810/201131694-a5c6ed0e-00f3-4026-b44e-a24535cb6705.png)

`/usr/local/bin/code` is just a symbolic link to `/mnt/c/Users/Corra/AppData/Local/Programs/Microsoft VS Code/bin/code`

This is what's inside the file at line 61: 
```bash
ELECTRON_RUN_AS_NODE=1 "$ELECTRON" "$CLI" --ms-enable-electron-run-as-node "$@"

# Inside the $ELECTRON and $CLI Variable
/mnt/c/Users/corra/AppData/Local/Programs/Microsoft VS Code/Code.exe    # $ELECTRON
C:/Users/corra/AppData/Local/Programs/Microsoft VS Code/resources/app/out/cli.js    # $CLI
```

### WHAT I TRIED
- Shutting down and restarting the wsl machine
- deleting ~/.vscode-server/
- Reinstalling vs code

**Comment by aeschli** [comment]
If `Code.exe` works on Windows, but not in the distro, then this would be a WSL issue. Please check if this is a known issue https://github.com/microsoft/WSL/issues.
I read that WSL can't run 32bit binaries. Could that be the problem?
