### ISSUE TITLE
different behavior of Run vs Run Without Debugging. (python code)

### ISSUE THREAD

**Issue by jablka** [microsoft/vscode#166009]
not sure if this is a bug or a feature, but what is the difference between: 
clicking on _Run (triangle) button_ vs _Run Without Debugging (Ctrl+F5)_ ?
Because when I run this Python code:
```
import os
os.startfile("textfile.txt")
```
by _Ctrl+F5 (Run Without Debugging)_, as I'm used to, nothing happens. The code runs as if "silently" and no window (application) is open to view the text file.

But when I run the code by clicking on the _Run (triangle) button_, it behaves correctly (and my Notepad++ pops up, opens).

Sorry if this should have been reported elsewhere...

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: Windows 11

Steps to Reproduce:

1. You should have a "textfile.txt" in your project/working directory.
2. Try to run the above python code, by those two ways as described.

**Comment by roblourens** [comment]
Please file on the python extension repo
