### ISSUE TITLE
Consider what content to include in built-in walkthroughs

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166047]
Ref #165846

My hunch is that there is an opportunity to get more crisp on what we want users to know in the first seconds/minutes of using the product and reflect that in the getting started experience.

In general, it feels like the specific steps of the walkthroughs are somewhat arbitrary in their order and grouping. My sense is that users wouldn't know which section contains what content by looking at the titles alone. And sometime the titles say one thing where the content implies another. Example: "Get Started with VS Code" is framed as customization, but the steps are related to productivity-boosters like the command palette. Or basic JTBD like opening your code.

These aren't exhaustive comments, but some "first" impressions with fresh eyes:

## Get Started with VS Code

Settings sync feels like a advanced feature to throw in as a second step in the very first walkthrough. And should opening your code be much higher up the list? Seems like a grab bag of activities here.

<img width="357" alt="CleanShot 2022-11-10 at 12 26 04@2x" src="https://user-images.githubusercontent.com/25163139/201198954-f19785b0-aa02-4bca-8a5c-42c9b8646f84.png">

## Learn the fundamentals

This also feels like a mixed framing re: features vs. outcomes. What is the goal of this section? Is it coding faster/smarter, or learning about features like the terminal or settings?

<img width="347" alt="CleanShot 2022-11-10 at 12 29 40@2x" src="https://user-images.githubusercontent.com/25163139/201199507-e2a4fe8d-c1fa-4344-bb74-fc9f88f16c45.png">

# Boost your productivity

While shortcuts and side-by-side fit nicely here, using git feels like a core concept that might be better served in an earlier walkthrough.

<img width="353" alt="CleanShot 2022-11-10 at 12 30 49@2x" src="https://user-images.githubusercontent.com/25163139/201199703-cee3b86b-f688-43b2-841d-7c32c46655ab.png">

**Comment by bhavyaus** [comment]
We've recently cleaned up the built-in walkthrough content and reduced this down to two sets of walkthroughs.
