### ISSUE TITLE
vscode-uri package includes `.map` files

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#166061]
## Bug

The published `vscode-uri` package includes `.map` files such as `lib/ubm/index.js.map`

These aren't really hurting anything but also should not be published (especially since we don't publish the original `.ts`)

**Comment by jrieken** [comment]
I am leaving them because the shipped JS is minified and therefore a source map is helpful when debugging etc. Also note that the source map includes the whole (TS) source too. Shipping the minified source is maybe not how this should be done but I am not for changing that now.
