### ISSUE TITLE
No schema support for args-attribute

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16609]
re #15809

* edit keybindings
* 🐛 there is no mentioning about the `args` property

**Comment by bpasero** [comment]
@alexandrudima I forgot how we decided to show it or not (remember we talked about it).

**Comment by alexandrudima** [comment]
@bpasero :+1: for documenting the args in the schema.

**Comment by jrieken** [comment]
The schema inserts `args` as object but in fact it can be anything.
