### ISSUE TITLE
Right click on an action icon is running the action

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#166025]
Steps to Reproduce:

1. Go to explorer view
2. Right click on Collapse All action
🐛 Collapse action runs

This is making impossible for me to hide actions in Test Explorer which disappear as soon as the action is triggered

**Comment by mettij** [comment]
Hi, i'd like to take a look at this issue, is this a good issue for a student?

**Comment by jrieken** [comment]
@sandy081 Is this running out of dev and on mac? There is a known issue that sometimes the OS/chromium sends a right click as left click. Try the same (right clicking) on status bar items and check what happens. Running OSS I can debug this and see that the right click is being dispatched as left click

**Comment by sandy081** [comment]
>  Is this running out of dev and on Mac?

Its on VS Code Insiders on Mac.

I just checked again and right click seems to work. Sorry for false alarm.

**Comment by jrieken** [comment]
No worries - it is the electron/mac mystery. At times only a reboot works 🙄
