### ISSUE TITLE
Word Warp

### ISSUE THREAD

**Issue by timran453** [microsoft/vscode#166021]
When I click word warp then VS code takes 50% width for text, I can't Fix the Problem. I can't Find Word.warp.column options. Please help me.

**Comment by alexdima** [comment]
* Press Gear > Settings
* Type wrap

<img width="713" alt="image" src="https://user-images.githubusercontent.com/5047891/204058718-b8cbaf9f-b5c6-4a46-80e1-be5e54b9aadd.png">
