### ISSUE TITLE
Watermark actions should be clickable

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16601]
Refs #16560

What is the reason that watermark actions are not clickable? They would just execute the corresponding keybinding. Watermark actions are taking a huge part of the screen and when a user sees something like that he clicks on that IMHO.

**Comment by chrmarti** [comment]
The downside would be that we need feedback on the mouse cursor which could distract the user moving the mouse across the watermark when going between other UI elements.

**Comment by isidorn** [comment]
Agree, but I do not think distracting the user while he has an empty string is something we should worry about. The user is not focused since he has no editor opened
