### ISSUE TITLE
Debug widget drag handle jumps around

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16604]
Testing #16026

![bug2](https://cloud.githubusercontent.com/assets/22350/20921979/cc97e232-bba6-11e6-9ee0-76dc05d3c984.gif)
![bug](https://cloud.githubusercontent.com/assets/22350/20921980/ccaaca1e-bba6-11e6-8cc8-3f4967bfdcec.gif)

Just offset the position with the difference between the handle's origin and the original click mouse offset. 👍

**Comment by joaomoreno** [comment]
The layout math is also wrong, once the widget has a different size than the original:

![image](https://cloud.githubusercontent.com/assets/22350/20922832/da909b4c-bba9-11e6-8544-12fd9f9c71b4.png)

**Comment by isidorn** [comment]
Only happens in the multiple process debug -> pushing to January, don't want to screw up the math at the last moment

**Comment by roblourens** [comment]
Still seeing a little jitter
![jan-27-2017 10-18-48](https://cloud.githubusercontent.com/assets/323878/22382313/0bc78128-e47a-11e6-9f7c-db479157fd62.gif)
