### ISSUE TITLE
Watermarks should automatically hide when panel opened

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16606]
Refs #16560 

Open the panel, notice how the watermarks are pushing out the logo -> looks a bit broken
Users that know how to open the panel are advanced users and we they do not need watermark help imho. Thus we could automatically hide the watermark if panel is opened.

![screen shot 2016-12-06 at 11 28 47](https://cloud.githubusercontent.com/assets/1926584/20922080/33cabbe6-bba7-11e6-9489-83a0481481d8.png)

**Comment by chrmarti** [comment]
Duplicate of #16130

**Comment by isidorn** [comment]
How is this a duplicate of the test item?

**Comment by isidorn** [comment]
Sorry, clicked on the wrong item - I see how this is a duplicate, let's close it :)
