### ISSUE TITLE
Intellisense + Inline Completions interaction has flickering

### ISSUE THREAD

**Issue by juihanamshet1** [microsoft/vscode#166023]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: Windows

Steps to Reproduce:

Have these internal settings enabled: 
"editor.inlineSuggest.allowQuickSuggestions": true,
"editor.inlineSuggest.allowSuggestOnTriggerCharacters": true  
The Intellisense interaction with grey text is awesome! But I noticed some flickering. Here is the GIF. 
![intellisense_intellicode_internalsetting_flashing](https://user-images.githubusercontent.com/86270736/201146735-c2234827-cdb8-45f7-a617-ce8383b063f7.gif)

I grabbed screenshots to make the flickering clear:  
WLC prediction is in Italics 
![image](https://user-images.githubusercontent.com/86270736/201146392-b9b357c4-c12d-4a81-ab0a-ebb491339d1e.png)

When Intellisense is up, Intellisense text is in Italics and wlc prediction is not.  
![image](https://user-images.githubusercontent.com/86270736/201146472-adaca3b1-fc56-4f95-9f46-760252ccd082.png)

When .is typed, there is a small latency where wlc prediction disappears. This is because . is a trigger character for Intellisense so first it will process Intellisense and then request the wlc inlineCompletionProvider.  
![image](https://user-images.githubusercontent.com/86270736/201146536-84f02cb6-fdeb-46fc-b7e8-9aeb188fe42d.png)

After that small latency, the wlc prediction shows up again in Italics 
![image](https://user-images.githubusercontent.com/86270736/201146585-02568766-1c90-4b27-9d1c-0d3f5571ac18.png)

So, the 2 main problems here are 
1) When Intellisense pops up while walking the prediction, the prediction goes from Italics to non-Italics. It goes back to Italics when Intellisense is dismissed (either by manual dismissal or item committed). In VS, we keep the font for grey text the same regardless of whether Intellisense is up or not, that would be helpful in VS Code. 
2) The small delay that happens when a trigger character is hit and the wlc prediction disappears and comes back again.

cc @hediet

**Comment by divineniiquaye** [comment]
This is normal, I use Copilot and experience the same thing. I believe this is not a bug but a slight delay in rendering.

**Comment by hediet** [comment]
I cannot reproduce:

![Code_-_OSS_vWTDVC1Bbf](https://user-images.githubusercontent.com/2931520/202680097-532852f5-3a17-4111-93e0-a554355cd991.gif)

Please log all calls from VS Code into your implementation of the inline completions provider and send me that log.

**Comment by juihanamshet1** [comment]
[inlineCompletionProviderLogs.txt](https://github.com/microsoft/vscode/files/10044572/inlineCompletionProviderLogs.txt)

Here are the logs, lmk if you need anything else.

**Comment by juihanamshet1** [comment]
I was able to repro the bug in code-oss. ghostText is indeed `undefined` when the flickering happens. 

I captured a GIF of the logs so you can see at what point ghostText becomes undefined. 
![ghostText_undefined](https://user-images.githubusercontent.com/86270736/203131040-730217b6-58f5-46d6-b822-9d0cab328b9f.gif)

Here are the logs
[ghostText_undefined_logs.txt](https://github.com/microsoft/vscode/files/10059515/ghostText_undefined_logs.txt)

**Comment by juihanamshet1** [comment]
I was also able to repro this bug in the sample extension. I used the extension from here - https://github.com/microsoft/vscode-extension-samples/tree/main/inline-completions 

![flickering_toyExtension](https://user-images.githubusercontent.com/86270736/203134522-453b553a-b9db-4c8d-91d5-2034d5260c9b.gif)

**Comment by bhavyaus** [comment]
Verified that inline completions do not flicker anymore.
