### ISSUE TITLE
Hello, i got the same issue, every logs are the same. I have github for the setting sync and github for copilot. I can sign in to both of them but as soon as i quit vscode and relaunch everything is signed out.

### ISSUE THREAD

**Issue by AntonioCoppe** [microsoft/vscode#166086]
I have the same issue on a 2014 mac. Apparently, the issue has been closed but is not working for me. Any ideas on why?

**Comment by TylerLeonhardt** [comment]
@oopiooffioinolis  can you provide the contents of the GitHub Authentication output pane:
![image](https://user-images.githubusercontent.com/2644648/128087382-c706864f-7005-4a2e-878b-662c69c4457e.png)

And also anything that shows up in Dev Tools:

* ctrl + shift + P
* "Dev Tools"

**Comment by TylerLeonhardt** [comment]
Also, can you enumerate the platforms and OS's you see this on?

**Comment by AntonioCoppe** [comment]
Hi, Thank a lot for the reply. The issue solved itself. Not sure how.
