### ISSUE TITLE
It would be nice to have a warning for duplicate configuration/compound names

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16608]
Testing #16026 

If a user has multiple configurations/compounds with same names, it would be nice to show a warning.

**Comment by isidorn** [comment]
From @joaomoreno There should be warning or error decorations for unknown configurations.

**Comment by isidorn** [comment]
@aeschli how can I have custom validaiton for my launch.json?
Is this possible?

**Comment by aeschli** [comment]
@isidorn  You would have to do that in the configuration-editing extension

**Comment by isidorn** [comment]
Will not do this -> closing
