### ISSUE TITLE
Commands in debug widget gets hidden

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16602]
Testing #16026

Have the following compound configuration in [launch.json](https://github.com/microsoft/vscode/blob/master/.vscode/launch.json) in VSCode repo

```
"compounds": [
		{
			"name": "Debug VSCode",
			"configurations": [
				"Launch VSCode",
				"Attach to Extension Host"
			]
		}
	]
```

- Start the above compound config
- Switch between two configurations in the launch widget

This will mess up the widget and there is no way to terminate it.

This could be related/similar to the issue #16596

**Comment by isidorn** [comment]
Yes, probably a duplicate. Thanks for filing though since this has easier steps to repro

**Comment by isidorn** [comment]
Closing as duplicate, is fixed now
