### ISSUE TITLE
Allow Markdown extensions to access the document URI

### ISSUE THREAD

**Issue by miyaokamarina** [microsoft/vscode#166088]
Currently, markdown-it extensions cannot access the current document URI before the render stage. This may be desirable, for example, for extensions that rely on the configuration files relative to the document to achieve consistent results with an external Markdown rendering tool, or allow to load locally installed versions of underlying libraries (e.g., a plugin that uses a locally installed KaTeX for math rendering).

There is a number of use cases where this is desirable:

- an extension that relies on the configuration files _relative to the document path_ to achieve consistent results with an external Markdown rendering tool,
- an extension that allows to use locally installed versions of underlying libraries (e.g., a plugin that uses a locally installed KaTeX version for math rendering),
- an extension that relies on the configuration files, **and** has markdown-it parser rules that depend on the configuration (e.g., a plugin with configurable syntax).

_Even at the render stage, where the document URI is accessible at the `currentDocument` property of the env object, it’s still impossible to use any async functions (e.g., for FS operations or module loading) since markdown-it does not allow async renderer rules; and also the means it may be accessed look like an unreliable hack._

So, for better API flexibility, there should be a way to access the document URI and other metadata a) before the render stage, and b) in an async context.

It may be achieved by handling an extension surface method similar to `extendMarkdownIt`:

```typescript
export function activate(context: vscode.ExtensionContext) {
    return {
        async extendMarkdownIt(md: any) {
            ...
        },
        async initializeMarkdownIt(env: MdEnv, docInfo: MdDocInfo) {
            try {
                env[MY_EXTENSION_CONFIG] = await loadConfigFileForDoc(docInfo.uri);
            } catch {
                ...
            }
        },
    };
}
```

**Comment by mjbvz** [comment]
@miyaokamarina Why did you close #166090? Is this feature still needed?
