### ISSUE TITLE
Source control panel with multiple sub-repros have confusing commit buttons

### ISSUE THREAD

**Issue by maasha** [microsoft/vscode#166093]
A while ago the large blue Commit button was introduced - but it does breaks the user experience when you have multiple sub-repros:

I am constantly confused about what commit button belongs to what repro

![image](https://user-images.githubusercontent.com/1158057/201296628-073e6348-f2dd-4c52-b766-7490a183443b.png)

I suggest removing the large blue Commit buttons and include a small icon for committing.

**Comment by lszomoru** [comment]
You can remove the action button by toggling the `git.showActionButton` setting.

**Comment by maasha** [comment]
Brilliant, thanks.
