### ISSUE TITLE
Unclear how to leave screen reader optimized mode

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#166154]
I got into screen reader optimized mode on Windows by using NVDA, but after closing NVDA, I don't know how to leave that mode. I tried clicking on the indicator in the taskbar, and also tried searching "accessibility" in the command palette for a command that would toggle it off.

![Snapshot showing the editor is "screen reader optimized"](https://user-images.githubusercontent.com/7199958/201437675-fe10d73d-9028-46af-8eef-8b2d3edbb23d.png)

**Comment by meganrogge** [comment]
fyi @isidorn for any input

**Comment by isidorn** [comment]
Agree with the above. Also on vscode restart you should no longer be in screen reader mode @rzhao271 if that is happening, it is a bug.

@meganrogge take into account that the accessibility help dialog shown in the screenshot has not been polished since we introduced it. We could make sure the text is more concise and user friendly. Visually it should not be polished since this is targeted for screen reader users.

**Comment by meganrogge** [comment]
Try to set a custom keybinding for this command - I find it very handy

**Comment by alexr00** [comment]
How do I get that status bar entry to show? I tried the following:
- Turn on NVDA when `"editor.accessibilitySupport": "auto"`
- Manually set `"editor.accessibilitySupport": "on"

**Comment by meganrogge** [comment]
This command should work
![Screenshot 2022-11-30 at 9 46 45 AM](https://user-images.githubusercontent.com/29464607/204843735-7d2bf56a-e266-49d5-9fc8-dbfad2d07d28.png)

**Comment by alexr00** [comment]
That still doesn't cause the status bar entry to show for me. I've checked the status bar show/hide menu and it's not in there either.

**Comment by rzhao271** [comment]
I was about to say I have the same issue, but then noticed that I had to go to a text editor to test out the feature. I was running the toggle command in the Settings editor.

**Comment by alexr00** [comment]
Not being in a text editor was the problem! I was either in the settings editor or the endgame notebook.
