### ISSUE TITLE
Remove the default scroll bar in the extensions' tip modal.

### ISSUE THREAD

**Issue by langyo** [microsoft/vscode#166171]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.73.1
- OS Version: Windows_NT x64 10.0.22623

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/23103705/201459261-02623c5c-9966-486e-9949-ce1e233fb739.png)
1. Switch to the extension bar.
2. Try to hover some items. Some one may not show the default scroll bar, but the problem is exists.

![image](https://user-images.githubusercontent.com/23103705/201459838-d7ca7be4-c775-4679-b075-287fbf53a628.png)
I have tried to fix it. It seems caused by the visual bug from the issue #158921. The scroll bar will show when the content is too long.

This solution is great, but it causes another little bug in the screenshot.

I think it's unwise to remove the `overflow-y: auto` tag, so I tried another way, just add `1px` to the tag `max-height`:

![image](https://user-images.githubusercontent.com/23103705/201460066-6395b255-7266-4f97-9251-bf312dab6012.png)

I'll make a PR after this issue has submitted.

**Comment by n0099** [comment]
I can't reproduce this srollbar for all extensions in the list:
![image](https://user-images.githubusercontent.com/13030387/201474545-c553de30-fc1f-43db-aaf4-033db4d5f7c6.png)

**Comment by langyo** [comment]
> I can't reproduce this srollbar for all extensions in the list:
> ![image](https://user-images.githubusercontent.com/13030387/201474545-c553de30-fc1f-43db-aaf4-033db4d5f7c6.png)

This bug is not 100% recurring.

Some extensions' descriptions may just exceed the calculated`max-height`.

**Comment by n0099** [comment]
> > I can't reproduce this srollbar for all extensions in the list:
> 
> This bug is not 100% recurring.
> 
> Some extensions' descriptions may just exceed the calculated`max-height`.

What's ur testing extension id?

**Comment by langyo** [comment]
> > > I can't reproduce this srollbar for all extensions in the list:
> > 
> > 
> > This bug is not 100% recurring.
> > Some extensions' descriptions may just exceed the calculated`max-height`.
> 
> What's ur testing extension id?

```
ms-dotnettools.vscode-dotnet-runtime
formulahendry.auto-close-tag
steoates.autoimport
formulahendry.auto-rename-tag
manasxx.background-cover
BazelBuild.vscode-bazel
michelemelluso.code-beautifier
alefragnani.Bookmarks
ms-vscode.cpptools-extension-pack
ms-vscode.cpptools-themes
ms-dotnettools.csharp
taiyuuki.chinese-color
Pivotal.vscode-manifest-yaml
twxs.cmake
SPGoding.datapack-language-server
ms-azuretools.vscode-docker
cschlosser.doxdocgen
dsznajder.es7-react-js-snippets
miguelsolorio.fluent-icons
tombonnike.vscode-status-bar-format-toggle
donjayamanne.githistory
ms-vscode.hexeditor
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.jupyter-keymap
ms-toolsai.vscode-jupyter-slideshow
ritwickdey.LiveServer
ms-vscode.makefile-tools
DavidAnson.vscode-markdownlint
unifiedjs.vscode-mdx
roerohan.mongo-snippets-for-node-js
bmewburn.vscode-intelephense-client
ms-vscode.powershell
esbenp.prettier-vscode
rvest.vs-code-prettier-eslint
mechatroner.rainbow-csv
mskelton.react-emotion-snippets
ms-vscode-remote.remote-ssh-edit
jRichardeau.vscode-vsproj
ms-vscode.vscode-selfhost-test-provider
ms-kubernetes-tools.vscode-kubernetes-tools
```

These extensions have the problem on my machine.

**Comment by n0099** [comment]
> ms-dotnettools.vscode-dotnet-runtime
> michelemelluso.code-beautifier

![image](https://user-images.githubusercontent.com/13030387/201552239-c58bba2c-0556-46e6-a296-53fa0d55ab4c.png)
![image](https://user-images.githubusercontent.com/13030387/201552253-f177e7bc-2bdd-422e-aa32-30e5b637c3ca.png)

**Comment by langyo** [comment]
> > ms-dotnettools.vscode-dotnet-runtime
> > michelemelluso.code-beautifier
> 
> ![image](https://user-images.githubusercontent.com/13030387/201552239-c58bba2c-0556-46e6-a296-53fa0d55ab4c.png) ![image](https://user-images.githubusercontent.com/13030387/201552253-f177e7bc-2bdd-422e-aa32-30e5b637c3ca.png)

Maybe it's related to high-resolution screen.

I'm sure it's an accidental problem, but it still exists.

If you have the conditions, try adjusting the screen resolution scale to 150%.

**Comment by Tyriar** [comment]
Caused by https://github.com/Microsoft/vscode/pull/164093

@rzhao271 can you please have a look at this?
