### ISSUE TITLE
[BUG] "Run Code" ignores default PowerShell version settings.

### ISSUE THREAD

**Issue by bferg317-perrigo** [microsoft/vscode#166164]
Does this issue occur when all extensions are disabled?: Yes. VScode is loading extensions when I launch with that switch anyway.

- VS Code Version: 
Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No
- OS Version: Windows 11 Pro

Steps to Reproduce:

1. Install PowerShell Core on Windows device
2. Configure PowerShell Core as default terminal
3. Write a simple PowerShell script `$PSVersiontable` and save as ps1.
4. Hit "Run Code"
5. VSCode launches a WindowsPowershell 5.1 terminal to execute the code, ignoring all settings.

**Comment by bferg317-perrigo** [comment]
From my settings.json:

```
"terminal.explorerKind": "integrated"
"terminal.integrated.defaultProfile.windows": "PowerShell"
```

**Comment by meganrogge** [comment]
does this exist on your computer `C:\Program Files\PowerShell\7\pwsh.exe`?

**Comment by meganrogge** [comment]
what happens if you disable the powershell extension?

**Comment by bferg317-perrigo** [comment]
Same behavior.

**Comment by bferg317-perrigo** [comment]
Are you sure? Because it's showing with PowerShell extension disabled, and even when editing non-posh files. HTML, etc all show it.

**Comment by bferg317-perrigo** [comment]
Actaually, it's not PowerShell extension, but that button apparently is from https://marketplace.visualstudio.com/items?itemName=formulahendry.code-runner

Not sure why code loads extensions with the `code --disable-extensions` launch, but that's not what I'm here to solve. Sorry for the confusion.
