### ISSUE TITLE
Debug widget shows process picker with a single process

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16617]
Testing #16494

1. Using `vscode-smoketest-express`, click the Debug gear icon and select the default Node.JS debug config
2. Start the `Launch Program` configuration.
3. Start the `Attach to Process` configuration. Wait for it to timeout, since there is no process to attach.

![image](https://cloud.githubusercontent.com/assets/22350/20922741/7ab28442-bba9-11e6-81c8-334116ebe200.png)

**Comment by isidorn** [comment]
This is as designed , we have decided to always show the dropdown if a session has been at least once in a multi session state (was a discussion in the standup).
I understand that in this case your second debug session did not start successfully but I do not really want to treat that specailly. Closing as desinged, will not fix
