### ISSUE TITLE
Asymmetric behaviour of Toggle Block Comment

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16611]
while testing #16558:

Applying "Toggle Block Comment" to multiple lines adds the opening comment on the **first** line of the selection but adds the closing comment **after** the last line of the selection:

Applying "Toggle Block Comment" to this selection:
![2016-12-06_11-33-35](https://cloud.githubusercontent.com/assets/1898161/20922268/d67b0dfa-bba7-11e6-8eb5-9ff6ddd40355.png)

results in this:
![2016-12-06_11-34-33](https://cloud.githubusercontent.com/assets/1898161/20922308/fa3da4a0-bba7-11e6-98ea-8468eb0dce15.png)

**Comment by alexandrudima** [comment]
@weinand  on second look this appears to be working as designed:

#### case 1: selection ends on the line of `}` (i.e. selection does not contain `\n`):
The `*/` gets appended to the right of the cursor:
![kapture 2017-09-27 at 16 20 19](https://user-images.githubusercontent.com/5047891/30918766-c6ff864a-a39f-11e7-9340-2d0e617586be.gif)

#### case 2: selection ends one line below `}` (i.e. selection contains `\n`):
The `*/` gets appended to the right of the cursor:
![kapture 2017-09-27 at 16 21 14](https://user-images.githubusercontent.com/5047891/30918807-e6c858d0-a39f-11e7-9f89-96ee5dbee42b.gif)
