### ISSUE TITLE
last bracket in file is white with bracket colorization on

### ISSUE THREAD

**Issue by almazgaliev** [microsoft/vscode#166100]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Arch Linux x64 6.0.7-zen1-1-zen

Steps to Reproduce:
1. write bracket pairs on last line of the file

expected result:
all bracket pairs colorized with same color

actual result:
last closing bracket is white

![Screenshot_20221111_124740](https://user-images.githubusercontent.com/44805749/201317907-4178a3a6-42b9-43ec-93fa-710c70c172fe.png)

if there is at least one line after last bracket, it works correcty
![Screenshot_20221111_124728](https://user-images.githubusercontent.com/44805749/201317835-1e6d4d73-4926-4a53-923c-72b7ec3bb806.png)

![Screenshot_20221111_124755](https://user-images.githubusercontent.com/44805749/201318138-15b778af-83cc-4bcf-85e1-4d4900f340e9.png)
![Screenshot_20221111_124804](https://user-images.githubusercontent.com/44805749/201318146-f641fe4c-48ff-472c-b8d0-5cd2dec0dd08.png)

**Comment by derzhavin3016** [comment]
Having the same issue on WSL2 under Windows 11.
Also, I'd like to add that sometimes pair bracket becomes white even in the middle of the file, but after moving cursor on it, it becomes normal.

**Comment by almazgaliev** [comment]
@derzhavin3016 you are right, it has something to do with scrolling through file

https://user-images.githubusercontent.com/44805749/201392296-c3806bcf-f97e-45f5-bd80-afbbe6f9297e.mp4

**Comment by hediet** [comment]
Unfortunately, I cannot reproduce. Did you try with default settings, ideally in VS Code insiders?

**Comment by almazgaliev** [comment]
I tried it in VS Code insiders, i found parameter in my config that cause this issue, (bug is visible in config file on 3rd line, when i uncomment this parameter)

![Screenshot_20221114_142302](https://user-images.githubusercontent.com/44805749/201648744-3e6ecd96-16f1-48e2-95ce-32131512f5ee.png)

![Screenshot_20221114_142248](https://user-images.githubusercontent.com/44805749/201648731-d5952bc7-a505-40cb-834e-0506d340076c.png)

and i noticed that with this config vscode has small delay before coloring braces (in dark+ color theme). This might be the reason why vscode does not color braces with custom color themes (i tried Material and Darcula)
 
 

https://user-images.githubusercontent.com/44805749/201653852-a1dec6b4-c3ab-4fa8-b9a3-1f3bdf31ab28.mp4

**Comment by pjyi2147** [comment]
I have exact same issue.
From a ubuntu laptop running 20.04 and a window 10 laptop running ubuntu 20.04 wsl 2.
