### ISSUE TITLE
--extensions-dir is ignored for management commands

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#166147]
- Run `code-insiders --extensions-dir /tmp/emptyfolder --list-extensions`
- I get a long list of extensions from my default insiders extensions dir
- Run the same command with vscode stable
- Get no result, as expected

`--install-extensions` fails in the same way

**Comment by sandy081** [comment]
It's not that `--extensions-dir` is being ignored. Its because now list of extensions are read from a manifest file that exists in user data directory.

**Comment by roblourens** [comment]
> Its because now list of extensions are read from a manifest file that exists in user data directory.

I was having an issue symlinking extensions into my oss install, is this why? If so, is there still a way to do this? I do manual extension management like this pretty often, in oss and insiders.

**Comment by sandy081** [comment]
Symlinking shall still work. VS Code picks up newly manually added extension. But it is picked only when you symlink while VS Code is running. Can you please elaborate the issue you are seeing?
