### ISSUE TITLE
Why edit file once but emit workspace.onDidChangeTextDocument event twice

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#166138]
Reproduce:

1. reset all settings
2. run extension with following code
3. open chrome devtools
4. open a file and press a space
5. you will see two log

```typescript
import vscode from 'vscode';

export async function activate(context: vscode.ExtensionContext) {
    const { subscriptions } = context;

    vscode.workspace.onDidChangeTextDocument(async ({ document, reason, contentChanges }) => {
        console.log('changeText', document.fileName, reason, contentChanges);
    }, subscriptions);
}
```

https://user-images.githubusercontent.com/41773861/201415979-64dcd17d-0d24-48f8-8cbb-822140206654.mov

```
Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

**Comment by jrieken** [comment]
Check the docs: 

https://github.com/microsoft/vscode/blob/e2ad6b5e3bb41b009fe00a8846c319b32b9d7000/src/vscode-dts/vscode.d.ts#L12404-L12406

**Comment by tjx666** [comment]
I think it would be more useful to provide a event named `onDidChangeTextDocumentContent`
