### ISSUE TITLE
Unexpected branch names when merging main into branch

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166160]
I was merging main from the vscode repo into my branch `ddossett/theme-updates` and saw this in the middle of the process

<img width="328" alt="CleanShot 2022-11-11 at 16 02 40@2x" src="https://user-images.githubusercontent.com/25163139/201446082-3231e211-e0a6-40d7-8d20-68579f0117c6.png">

..after a while, it sorted itself out and landed on this:

<img width="302" alt="CleanShot 2022-11-11 at 16 02 49@2x" src="https://user-images.githubusercontent.com/25163139/201446103-fee9c3bc-d8d8-4224-9557-c393779c94c8.png">

Not the first time I've seen this.

**Comment by lszomoru** [comment]
That does look like a bug. Have you seen this with other repos as well? 
Do have a set of steps that I could try to reproduce this issue in isolation?

**Comment by daviddossett** [comment]
I can't say I've seen this with other repos but I will keep an eye out. I will try to repro this again. Basically it was:

1) Create a branch from vscode/main
2) Wait some longer period of time (several days or a week to have a significant # of commits). This is probably the notable repro detail.
3) Merge origin/main
4) Observe SCM view and SCM input as the updated files are listed and the input is updated. Ultimately, it resolved into that second image as expected.
