### ISSUE TITLE
Extension hover shows chrome scrollbar

### ISSUE THREAD

**Issue by tauin** [microsoft/vscode#166113]
Type: <b>Bug</b>

When Hovering over an extension, the "popup" will display the chrome scrollbar on certain extensions, im not sure how to reproduce this, only that it happens all the time

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
nugetpackagemanagergui|ali|2.0.5
vscode-neovim|asv|0.0.93
spellright|ban|3.0.90
markdown-mermaid|bie|1.15.2
cake-vscode|cak|2.1.1
vscode-markdownlint|Dav|0.48.1
python-environment-manager|don|1.0.4
EditorConfig|Edi|0.16.4
shell-format|fox|7.2.2
vscode-nuget-package-manager|jmr|1.1.6
magit|kah|0.6.34
vsc-python-indent|Kev|1.18.0
bash-ide-vscode|mad|1.14.0
mypy|mat|0.2.2
csharp|ms-|1.25.2
black-formatter|ms-|2022.6.0
isort|ms-|2022.6.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
powershell|ms-|2022.10.0
diff|raf|0.0.1
vscode-xml|red|0.22.0
shellman|Rem|5.6.0
file-bunny|rob|1.3.4
rust-analyzer|rus|0.3.1277
crates|ser|0.5.10
even-better-toml|tam|0.19.0
shellcheck|tim|0.26.3
errorlens|use|3.6.0
vscode-lldb|vad|1.8.1
vscodeintellicode|Vis|1.2.29
whichkey|VSp|0.11.3

(1 theme extensions excluded)

</details>

**Comment by tauin** [comment]
![image](https://user-images.githubusercontent.com/71744831/201349697-419605fe-cdb1-4ef9-bb6a-c8c8afda1c3a.png)

**Comment by Tyriar** [comment]
I can't reproduce this, does it happen on https://code.visualstudio.com/insiders/?

@rzhao271 did you merge in that change related to scroll bars in the hover? I can't find the PR
