### ISSUE TITLE
Issue in indentation when formatting consecutive objects

### ISSUE THREAD

**Issue by louy** [Microsoft/vscode#1661]
There's a very annoying issue when hitting "format code" in a TS file. Here's an example:
```ts
[{
}, {
}]
// or
fn({
}, {
})
```
becomes:
```ts

[{
}, {
  }]
// or
fn({
}, {
  })
```

This gets really annoying when you have large nested objects containing things like functions etc...

**Comment by bpasero** [comment]
I guess this needs to be reported against TS.

**Comment by louy** [comment]
So all code formatting is done in the tsserver? There are a couple of other issues as well.

**Comment by dbaeumer** [comment]
This issue was moved to Microsoft/TypeScript#6339

**Comment by dbaeumer** [comment]
Setting verified label. Issue got moved to TS.
