### ISSUE TITLE
Slow start up

### ISSUE THREAD

**Issue by Teleri** [microsoft/vscode#166188]
I'm having slow start up issues on a new M1 mac, running Monterey
1. :warning: We have copied additional data to your clipboard. Make sure to **paste** here. :warning:
1. :warning: Make sure to **attach** these files from your *home*-directory: :warning:
[prof-ZHIf8xow.main.cpuprofile.txt](https://github.com/microsoft/vscode/files/9995385/prof-ZHIf8xow.main.cpuprofile.txt)
[prof-ZHIf8xow.renderer.cpuprofile.txt](https://github.com/microsoft/vscode/files/9995386/prof-ZHIf8xow.renderer.cpuprofile.txt)

## System Info

* Code: 1.73.1 (6261075646f055b99068d3688932416f2346dd3b)
* OS: darwin(21.6.0)
* CPUs: Apple M1 Pro(10 x 24)
* Memory(System): 16.00 GB(1.64GB free)
* Memory(Process): NaN MB working set(191.39MB private, 0.05MB shared)
* VM(likelihood): 0%
* Initial Startup: true
* Has 0 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                                       |
| --------------------------------------------------------------- | -------- | ------------------------- | ---------------------------------------------------------- |
| start => app.isReady                                            | 280      | [main]                    | initial startup: true                                      |
| nls:start => nls:end                                            | 39       | [main]                    | initial startup: true                                      |
| require(main.bundle.js)                                         | 491      | [main]                    | initial startup: true                                      |
| start crash reporter                                            | 126      | [main]                    | initial startup: true                                      |
| serve main IPC handle                                           | 4        | [main]                    | initial startup: true                                      |
| create window                                                   | 48       | [main]                    | initial startup: true, state: 2ms, widget: 41ms, show: 0ms |
| app.isReady => window.loadUrl()                                 | 878      | [main]                    | initial startup: true                                      |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 1308     | [main->renderer]          | NewWindow                                                  |
| require(workbench.desktop.main.js)                              | 1333     | [renderer]                | cached data: YES, node_modules took 0ms                    |
| wait for window config                                          | 0        | [renderer]                | -                                                          |
| init storage (global & workspace)                               | 80       | [renderer]                | -                                                          |
| init workspace service                                          | 177      | [renderer]                | -                                                          |
| register extensions & spawn extension host                      | 639      | [renderer]                | -                                                          |
| restore viewlet                                                 | 92       | [renderer]                | workbench.view.explorer                                    |
| restore panel                                                   | 0        | [renderer]                | -                                                          |
| restore & resolve visible editors                               | 572      | [renderer]                | 0:                                                         |
| overall workbench load                                          | 1096     | [renderer]                | -                                                          |
| workbench ready                                                 | 5092     | [main->renderer]          | -                                                          |
| renderer ready                                                  | 2643     | [renderer]                | -                                                          |
| shared process connection ready                                 | 0        | [renderer->sharedprocess] | -                                                          |
| extensions registered                                           | 6713     | [renderer]                | -                                                          |

## Extension Activation Stats

| Extension                           | Eager | Load Code | Call Activate | Finish Activate | Event                             | By                                  |
| ----------------------------------- | ----- | --------- | ------------- | --------------- | --------------------------------- | ----------------------------------- |
| vscode.git                          | true  | 92        | 14            | 107             | *                                 | vscode.git                          |
| vscode.git-base                     | true  | 37        | 0             | 0               | *                                 | vscode.git                          |
| vscode.github                       | true  | 98        | 1             | 0               | *                                 | vscode.github                       |
| vscode.configuration-editing        | false | 5         | 1             | 14              | onLanguage:jsonc                  | vscode.configuration-editing        |
| vscode.debug-auto-launch            | false | 3         | 0             | 8               | onStartupFinished                 | vscode.debug-auto-launch            |
| vscode.emmet                        | false | 8         | 7             | 1               | onStartupFinished                 | vscode.emmet                        |
| vscode.extension-editing            | false | 7         | 1             | 6               | onLanguage:markdown               | vscode.extension-editing            |
| vscode.github-authentication        | false | 12        | 4             | 0               | onAuthenticationRequest:github    | vscode.github-authentication        |
| vscode.json-language-features       | false | 20        | 0             | 489             | onLanguage:jsonc                  | vscode.json-language-features       |
| vscode.markdown-language-features   | false | 32        | 6             | 348             | onLanguage:markdown               | vscode.markdown-language-features   |
| vscode.markdown-math                | false | 4         | 0             | 0               | api                               | vscode.markdown-language-features   |
| vscode.merge-conflict               | false | 9         | 1             | 0               | onStartupFinished                 | vscode.merge-conflict               |
| vscode.microsoft-authentication     | false | 32        | 5             | 120             | onAuthenticationRequest:microsoft | vscode.microsoft-authentication     |
| vscode.typescript-language-features | false | 28        | 14            | 1               | onLanguage:jsonc                  | vscode.typescript-language-features |

**Comment by KunHwang** [comment]
me too

**Comment by deepak1556** [comment]
Can you try the latest stable `1.74` and provide the startup numbers from it.

**Comment by Teleri** [comment]
@deepak1556 I installed the latest update, which didn't change much, also disabled all extensions, same story. Now did a complete reinstall, looks perfect now (all extensions enabled). I will close as no issue at present now.
