### ISSUE TITLE
Matching brackets border not functional

### ISSUE THREAD

**Issue by d0ggie** [microsoft/vscode#166109]
Hi,

For matching brackets "editorBracketMatch.border" is no longer functional.  "editorBracketMatch.background" still works.  

I suspect this has been caused by commit 83b528d4dcd37110052b947ee69cdb198099d8d2.

BracketMatching.css currently has `border: var(--vscode-editorBracketMatch-border);` but I presume this should be `border: 1px solid var(--vscode-editorBracketMatch-border);`

--

Does this issue occur when all extensions are disabled? Yes

Version: 1.74.0-insider (user setup)
Commit: ef415578d1b1019db585718968a303eeca4b8979
Date: 2022-11-11T05:19:14.666Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.20348
Sandboxed: Yes

**Comment by hediet** [comment]
Thanks for reporting and investigating! It would be awesome if you could create a PR!
