### ISSUE TITLE
Support events raised from extensions

### ISSUE THREAD

**Issue by thegecko** [microsoft/vscode#166179]
We have a need to be notified between extensions when some sort of event happens.

Our use case is that we have an extension with buttons in a webview which get enabled/disabled based on the state of things in other extensions.

We have got round this with extensions running in the same extensionHost by abusing the commands system to register an event listener:

```typescript
export class EventTest {
    private _onEvent: vscode.EventEmitter<void> = new vscode.EventEmitter<void>();
    public readonly onEvent: vscode.Event<void> = this._onEvent.event;

    public async activate(context: vscode.ExtensionContext): Promise<void> {
        context.subscriptions.push(
            vscode.commands.registerCommand('event-test.onEvent', (fn?: () => void) => {
                if (typeof fn === 'function') {
                    this.onEvent(fn);
                }
            })
        );
    }

    public raiseEvent() {
        this._onEvent.fire();
    }
}
```

This is far from ideal and doesn't work across extension hosts, is there a known pattern for this?

If not, a simple custom event system on the VS Code API would be great.

**Comment by thegecko** [comment]
Oh:
https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.ipc.d.ts

**Comment by thegecko** [comment]
> Oh:
https://github.com/microsoft/vscode/blob/main/src/vscode-dts/vscode.proposed.ipc.d.ts

It seems this only exists to send events between VS Code and webviews.

Other things investigated:

- Abusing the configuration system: Not possible because you cannot programmatically set a configuration item
- Abusing the context system: Not possible because you cannot programmatically get a context entry
- Writing to a file and implementing a file watcher. Messy and workable, but requires a writable workspace to be open

**Comment by mjbvz** [comment]
You can either use commands or return an api from your extension's `activate` function that other extensions can access:

https://github.com/microsoft/vscode/blob/96bf637c101b8832e44a97a27a26305d8c2cf22e/src/vscode-dts/vscode.d.ts#L7044
