### ISSUE TITLE
Color squares when using CSS and SCSS variables

### ISSUE THREAD

**Issue by allan2** [microsoft/vscode#166195]
Color squares appear when defining CSS or SCSS variables, but not when using them.

It would be *really useful* is the squares showed up when using variables from other files.

![variable-color-square](https://user-images.githubusercontent.com/6740989/201490259-5abe4834-6a1a-4762-a191-cd03d424697d.png)

**Comment by GauravB159** [comment]
I don't think it'll be easy to get variable colors to display from other files, at least not in a way I can think of. Maybe from the same file, it would be possible. Possibly from currently open files.

**Comment by allan2** [comment]
@GauravB159 the color completion already scopes from open files, although the behvaviour is not consistent (#166203).

**Comment by GauravB159** [comment]
@allan2 Hmm, I'll look into it then, maybe I'll find something

**Comment by aeschli** [comment]
The color decorator might not be correct. Only at runtime, the browser will know the actual value of a variable. There can be multiple declaration of the same variable, under different scopes, or the variable can be set programmatically.

So I'f prefer to leave things as they are.
