### ISSUE TITLE
Extension version downgrade broken for vscode remote

### ISSUE THREAD

**Issue by jeanp413** [microsoft/vscode#166180]
- VS Code Version: insiders and from sources

![bug-extension-version](https://user-images.githubusercontent.com/25115070/201471789-0498610c-f06a-4719-bf6a-211743b570b7.gif)

cc @sandy081

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/166182

**Comment by sandy081** [comment]
Thanks for filing the issue and coming up with the PR. Sorry that the provided PR does not have the proper fix. Hence I came up with a PR with proper fix - https://github.com/microsoft/vscode/pull/166269

**Comment by sandy081** [comment]
To verify:

- Install an extension
- Right click on installed extension and select **Install Another Version...** action
- Install a older version and make sure older version got installed and update button is showed
