### ISSUE TITLE
Cursors at Line Ends is confusing

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16618]
Testing https://github.com/Microsoft/vscode/issues/16558

The command "Selection > Cursors at Line Ends" has too many cases for where it just does nothing:
* when you do not have a selection
* when you have multiple cursors without selection
* when you have multiple cursors with selection
* when you have a selection on a single line

It only seems to work when you have a multi line selection. If that is the intent then maybe it should be renamed?

**Comment by chrmarti** [comment]
@seanmcbreen Can you think of a better name for 'Cursors at Line Ends'?

Other editors have 'Split into Lines' for a similar action that keeps the characters selected. I just cannot think of a variation that would better label ours.

**Comment by chrmarti** [comment]
I've opened #16771 to track the multi-selection case. Lets use this issue to improve the label.

**Comment by roblourens** [comment]
I think it mainly just needs a verb, like 'add cursors to line ends', I don't know if it can get any longer than that.

I think I would have figured it out if it did something when there's no selection.

**Comment by roblourens** [comment]
Any reason we don't make the behavior the same as 'split into lines', and use that same name?

**Comment by seanmcbreen** [comment]
Add Cursor to End of Selected Lines  [long I know...]

**Comment by alexandrudima** [comment]
From blaming the code that implements the action, it came in through PR #1479

IMHO this was a direct implementation of the Sublime `Split into Lines` command (`Ctrl+Shift+L`) which behaves 100% the same (@bpasero)

**Comment by bpasero** [comment]
@alexandrudima my Sublime does not seem to have such a command.

**Comment by bpasero** [comment]
+1 for naming it the same way as in ST then.

**Comment by chrmarti** [comment]
@alexandrudima The behavior is not the same from what I see. Ours ends with multiple cursor but no characters selected. Sublime's keeps the same characters selected while splitting the selection along lines.

**Comment by alexandrudima** [comment]
We can ask our Sublime keybindings experts what Sublime action this is supposed to be and if it is a bug. @waderyan ?

**Comment by waderyan** [comment]
I'll reach out and see what I can find out.

**Comment by chrmarti** [comment]
For this milestone: Updating it to 'Add Cursors to Line Ends' as @roblourens suggested. I think it is clear from the 'Selection' menu as its context that it will affect the selected lines, hence 'Add Cursor to End of Selected Lines' as @seanmcbreen suggested would seem a little redundant. Sublime's 'Split into Lines' is not a good match because that is not what the action does.

**Comment by bpasero** [comment]
I would expect this command also to work when you have a selection in a single line. Currently this does not work.

**Comment by chrmarti** [comment]
@bpasero It does to a single line what it does to the last line in a multi-line selection. That seems consistent. What would you like to see change?

**Comment by bpasero** [comment]
I see now. This is a command that is super hard to understand imho and I will never use it.

**Comment by chrmarti** [comment]
I see what you are saying. It is also slightly redundant with Add Cursor Above/Below because these followed by End achieve the same thing with only one additional keystroke. Let's see if it gets any significant use and remove it if not.
