### ISSUE TITLE
default command decorations are white instead of blue 

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#166163]
<img width="101" alt="Screenshot 2022-11-11 at 4 35 21 PM" src="https://user-images.githubusercontent.com/29464607/201447796-7116c9ca-29c1-41c9-8b56-0be24020c663.png">

**Comment by Tyriar** [comment]
I noticed this too, maybe from css var refractor?

**Comment by meganrogge** [comment]
Yeah but strange because at first glance, the code still looks correct to me
