### ISSUE TITLE
Disappearance of characters and whole lines when opening multiple terminals

### ISSUE THREAD

**Issue by imblowfish** [microsoft/vscode#166158]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. Open multiple terminals
2. Go to last created, write something
3. Go to any other than the last one
4. Write the beginning of a command and press tab for autocompletion

After a while, the characters reappear if you run any command again.

I found this issue https://github.com/microsoft/vscode/issues/165969, but according to the description it is not entirely clear which input the author means

Here is what I was able  to reproduce (In each terminal I enter the same command `cd ~/` and press `Tab`):

![Screenshot from 2022-11-12 02-46-20](https://user-images.githubusercontent.com/28269602/201441802-427dc115-8364-41aa-8445-e49b417c94f8.png)

![Screenshot from 2022-11-12 02-56-28](https://user-images.githubusercontent.com/28269602/201441813-b70e3f23-ad2d-493d-abbf-e36b71f86711.png)

**Comment by meganrogge** [comment]
I cannot repro on mac, maybe something has been fixed?

**Comment by meganrogge** [comment]
also can't repro on WSL

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by imblowfish** [comment]
I also recorded a video of how I reproduced the bug, I hope this helps
https://user-images.githubusercontent.com/28269602/201778687-bd080f1b-daf4-40cb-852a-684801400b16.mp4

**Comment by ZeroOnePro** [comment]
issue #165969

I saw your problem and it seems that there is something different from mine.

The problem with me was that if I first run the vscode after booting and type in my native language, Korean, some letters disappeared from the input.

There is no problem when typing in English.

For example, if I type '가나다라마바사' in a markdown or any file, some of the inputs disappear and become '가나라바사'.

It disappears even though I typed "다, 마"

@imblowfish Isn't your problem that the terminal input disappears?

**Comment by ZeroOnePro** [comment]
@meganrogge Is this issue the same as the issue I opened? #165969

**Comment by imblowfish** [comment]
> issue #165969
> 
> I saw your problem and it seems that there is something different from mine.
> 
> The problem with me was that if I first run the vscode after booting and type in my native language, Korean, some letters disappeared from the input.
> 
> There is no problem when typing in English.
> 
> For example, if I type '가나다라마바사' in a markdown or any file, some of the inputs disappear and become '가나라바사'.
> 
> It disappears even though I typed "다, 마"
> 
> @imblowfish Isn't your problem that the terminal input disappears?

Hi @ZeroOnePro, I think not, my problem is reproduced only in the terminal, there are no problems in the files.

**Comment by ZeroOnePro** [comment]
Hi @imblowfish 

I wonder if the cause of your problem and the cause of my problem are the same.

What's your idea?

**Comment by imblowfish** [comment]
> Hi @imblowfish 
> 
> I wonder if the cause of your problem and the cause of my problem are the same.
> 
> What's your idea?

Can't say with certainty

**Comment by meganrogge** [comment]
Different issues, thanks for the additional info

**Comment by Tyriar** [comment]
Happened to me just now:

![image](https://user-images.githubusercontent.com/2193314/202727187-7c6be1ca-70e2-4f0a-9a7b-233f18f3f7b1.png)

webgl renderer
Version: 1.74.0-insider (user setup)
Commit: 1b1e2a2c5794df1f475976062c754651827634a9
Date: 2022-11-18T05:25:18.342Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by jeanp413** [comment]
Created a PR fixing it https://github.com/xtermjs/xterm.js/pull/4271

**Comment by connor4312** [comment]
I saw sometimes, though I never found a reproduction for it. However I have not seen it this week, thus marking verified.
