### ISSUE TITLE
Provide a way to clear the recent documents list

### ISSUE THREAD

**Issue by fariyAhill** [Microsoft/vscode#1662]
On mac OSX dock, right click on code will show a list files' name opened recently,how can I clear them?

**Comment by bpasero** [comment]
Somehow I cannot get this list to be cleared, filed: https://github.com/atom/electron/issues/3932

**Comment by Voleking** [comment]
@bpasero Maybe you should reopen this issues? [electron/electron#3932](https://github.com/electron/electron/issues/3932)

**Comment by bpasero** [comment]
I pushed a change that might help. Otherwise there is nothing we can do.
