### ISSUE TITLE
Selection menu: Improve 'Cursor at lines end'

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16620]
Testing #16558, Linux

'Cursor at lines end' only works on a multi-line selection. Not being aware of that, I tried the action multiple times with out effect

Either:
- Disable the action if there is no multi-line selection
- Make the action also work for a single line selection

**Comment by chrmarti** [comment]
It already works for single line selection: When you select multiple lines with the last line selected partially, the cursor inserted on the last line will be at the end of the selection. The same holds for a selection within a single line. (/cc @rebornix)

We are currently not managing the enablement of menu items (with a few exceptions).

**Comment by aeschli** [comment]
So it's ' all line ends covered by selection'

**Comment by chrmarti** [comment]
Yes, #16618 is tracking that the label doesn't explain the action well.

**Comment by chrmarti** [comment]
Opened #16771 to track the multi-selection case. Otherwise this seems to work as designed. Closing.
