### ISSUE TITLE
Terminal doesn't work

### ISSUE THREAD

**Issue by lugiluc** [microsoft/vscode#166234]
The terminal doesn't work. I cannot do anything. It showed a warning icon but now it has disappeared. The terminal is still not working, I cannot type

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
