### ISSUE TITLE
Format on save So Slow

### ISSUE THREAD

**Issue by lynhan96** [microsoft/vscode#166289]
Type: <b>Bug</b>

set format on save with type script and save it take abou 27s

["INFO" - 11:09:25 PM] Prettier Options:
{

  "parser": "typescript",
  "bracketSpacing": true,
  "singleQuote": true,
  "trailingComma": "es5",
  "tabWidth": 2,
  "jsxSingleQuote": true,
  "useTabs": false,
  "endOfLine": "auto"
}
["INFO" - 11:09:25 PM] Formatting completed in 27411ms.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|7, 8, 9|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv|--crash-reporter-id 22113758-b6dc-4922-a3ca-f50832e91027|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
rails-db-schema|aki|0.2.6
vscode-tailwindcss|bra|0.9.1
solargraph|cas|0.24.0
npm-intellisense|chr|1.4.2
twin-macro-autocomplete-vscode|Den|0.0.5
githistory|don|0.6.19
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
rails-snippets|Hri|1.0.8
tws|jki|1.0.1
endwise|kai|1.5.1
tailwindcss-intellisense-twin|lig|3.0.0
vscode-language-babel|mgm|0.0.36
ruby|reb|0.28.1
vs-code-prettier-eslint|rve|5.0.4
code-settings-sync|Sha|3.4.3
autoimport|ste|1.5.4
code-spell-checker|str|2.11.0
vscode-styled-components|sty|1.7.5
haml|vay|1.0.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-icons|vsc|12.0.1
vscode-ruby|win|0.28.0
highlight-trailing-white-spaces|yba|0.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30605430
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by mjbvz** [comment]
Please file this against prettier
