### ISSUE TITLE
Sublime: 'Join Lines' command binds to Windows+J on Win 10

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16624]
while testing #16545:

On Windows 10 the 'Join Lines' command binds to Windows+J instead of Control+J. This is different from the corresponding binding in Sublime.

**Comment by rebornix** [comment]
AFAIK, we don't have any command binded to Windows key yet, any catch here @alexandrudima ?

**Comment by rebornix** [comment]
Talked with @Tyriar and he mentioned that Windows key is usually taken by system key shortcut, I think that's mainly why we don't do that.

We can ship it this way and see ppl's feedback on this.

**Comment by alexandrudima** [comment]
@rebornix Let's ship with the keybinding unbound on Windows and have it bound only on the mac.

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/067cf11bf0813352f5fdee3373d658d30de38b2f .

To verifier, please test that we only have key bindings for Join Lines on Mac. For Windows and Linux, you need to bind them yourselves.
