### ISSUE TITLE
EventHandlers content should have js coloring

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16628]
Refs #16526 

Event handler values should have javascript coloring. Currently it is colored as a string but all the js funcitonality is there. As a user would not expect this to work due to string coloring - thus it will be hard to find the nice intelli-sense support you have there

![screen shot 2016-12-06 at 12 14 35](https://cloud.githubusercontent.com/assets/1926584/20923644/b7e5de78-bbad-11e6-91f8-6ecdc52faa57.png)

**Comment by aeschli** [comment]
Not easy to implement as this would drag in a whole Java grammar. But not the original one, but one that uses HTML escaping rules.

**Comment by aeschli** [comment]
Would have to go into the textmate grammar we use (https://github.com/textmate/html.tmbundle)

**Comment by aeschli** [comment]
This issue was moved to textmate/html.tmbundle#50
