### ISSUE TITLE
`createTerminal` does not create a terminal at the first editor group

### ISSUE THREAD

**Issue by tamuratak** [microsoft/vscode#166241]
Version: 1.74.0-insider (Universal)
Commit: ef415578d1b1019db585718968a303eeca4b8979
Date: 2022-11-11T05:18:46.092Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 20.6.0
Sandboxed: Yes

When `location: { viewColumn: vscode.ViewColumn.One }` given, `createTerminal` does not create a terminal at the first editor group. When `location: { viewColumn: vscode.ViewColumn.Two }` and others given, it creates the terminal at an appropriate group.

```ts
vscode.window.createTerminal( { name: `Ext Terminal #${NEXT_TERM_ID++} at One`, location: { viewColumn: vscode.ViewColumn.One } });
```
Steps to Reproduce:

1. Run the extension sample: https://github.com/tamuratak/vscode-extension-samples/tree/create_terminal_vc_one/terminal-sample
2. Open three editor groups.
3. Select the third group.
4. Execute `terminalTest.createTerminal`
5. The terminal is NOT created at the first editor group

https://user-images.githubusercontent.com/10665499/201547547-e0ca0e53-01b9-4cd7-89a7-6263f72d57b7.mov

Related to #158274
CC: @Tyriar

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/169050
