### ISSUE TITLE
[BUG] Not fully Chinese

### ISSUE THREAD

**Issue by CoolPlayLin** [microsoft/vscode#166211]
Look by YOURSELF
![image](https://user-images.githubusercontent.com/96709586/201500692-03b15676-6198-4aea-854b-e0fd0fae67b9.png)

Steps to Reproduce:

1. The language in the Git column is not fully Chinese.
2.  Sometimes it is all in English after updating.

**Comment by gjsjohnmurray** [comment]
> 1. The language in the Git column is not fully Chinese

Those views are contributed by an extension, probably GitLens. Please ask the extension author to support Chinese localisation.

**Comment by CoolPlayLin** [comment]
> 

No, It is not GitLens

**Comment by gjsjohnmurray** [comment]
Please use the `Start Extension Bisect` command to discover which extension has added these views:

![image](https://user-images.githubusercontent.com/6726799/201508427-1adfc85e-2659-4e09-a2d9-ddc5bc8eeda2.png)

**Comment by CoolPlayLin** [comment]
![image](https://user-images.githubusercontent.com/96709586/201510550-7a4816db-ef3b-4a5f-85bf-c83befa81cc2.png)

**Comment by CoolPlayLin** [comment]
It is real VSCODE

**Comment by CoolPlayLin** [comment]
That Also: #166187

**Comment by CoolPlayLin** [comment]
![image](https://user-images.githubusercontent.com/96709586/201510635-c1595652-5816-4d87-824f-01f61737a392.png)

**Comment by gjsjohnmurray** [comment]
> Probably he is referring to the inbox in source control tab, and the commit button

Similar to #165735

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/165974#issuecomment-1310465539
