### ISSUE TITLE
Scopes are shown in hover on a function

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16621]
Testing #15359

See the following snippet

```
var express = require('express');
var router = express.Router();

/* GET home page. */
router.get('/', function (req, res, next) {
  let object = someFunction();
  res.render('index', { title: 'Express' });
});


function someFunction() {
  return [1, 2, 3];
}

module.exports = router;
```

When I have a break point on the following line
` let object = someFunction();` 

If I hover on someFunction() I see following hover which is having scope details. I am not sure if it makes sense to show scopes there

![screen shot 2016-12-06 at 11 54 27](https://cloud.githubusercontent.com/assets/10746682/20923216/d398f4a4-bbab-11e6-90b8-ffa7ab5d0218.png)

**Comment by roblourens** [comment]
I don't want to exclude any properties that come from the runtime. The `[[...]]` props are special things that aren't JS props but sometimes have vital information. And they show up in chrome devtools.
