### ISSUE TITLE
Color completion variable names are file-scoped inconsistently

### ISSUE THREAD

**Issue by allan2** [microsoft/vscode#166203]
This issue is for color completion having inconsistent behaviour when it comes to suggesting variable names from other files.
#166201, #166195, and this issue are probably all afflicted by the handling of non-hex variables.

![color-completion-5-file-scope](https://user-images.githubusercontent.com/6740989/201491615-ab8ded84-22dd-45a8-acbf-54164aae9275.gif)
File A autocompletion *sometimes* suggests variables from File B (the list can be reset, described in #166201)
File B autocompletion never suggests variables from File A.

Example code is here https://github.com/allan2/vs-code-css-color-issue

**Comment by aeschli** [comment]
The CSS language support does not work across files. It only looks at the content of the current file and only knows about variables defined in the current file.

https://github.com/microsoft/vscode/issues/47331 is the request

**Comment by allan2** [comment]
@aeschli could you reopen?

This is still a bug.

Variables in other files are **leaking** today. Look at how **$blue** in File B shows up in File A. I included an animation in my first post.

**Comment by aeschli** [comment]
It's a textual completion proposal. These are offered if there are no better proposals
@jrieken I assume these are gathered from all open documents of the same language mode?

@allan2 Isn't it a good thing to have such proposals? It might be what you need. Code completion is about helping the user to type. Some proposals are useful, some are not. In the end it's the user to decide which proposal to pick.

**Comment by allan2** [comment]
@aeschli I understand. It is good to have these autocompletion suggestions.

I opened this bug because under specific conditions, proposals from variables in File B show up in File A but not the other way around.

I think this is a bug related to hex colours.
