### ISSUE TITLE
INDEX .HTML not responding in VS code.

### ISSUE THREAD

**Issue by margaretnajder** [microsoft/vscode#166204]
Type: <b>Bug</b>

PLEASE HELP ME ...my code is stuck i cant do anything ..nothing is working ,i cant write ,i cant delate nothing 0 ...is not responding ..totally not responding ..this happen on onother file to and i had to delate it and start all over ,and now happen again ..not responding at all ..
please help me ..

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_61455 --crash-reporter-id ecf2f6bb-ab37-4f86-bb6a-477a49c65d15|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
vscode-javascript-snippet-pack|aka|0.1.6
Bookmarks|ale|13.3.1
html-class-suggestions|And|1.1.1
vscode-color|ans|0.4.5
path-intellisense|chr|2.8.1
githistory|don|0.6.19
bracket-pair-toggler|dzh|0.0.2
gitlens|eam|13.0.4
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.54.0
vscode-colorize|kam|0.11.1
code-beautifier|mic|2.3.3
prettify-json|moh|0.0.3
vscode-edge-devtools|ms-|2.1.1
remote-ssh-edit|ms-|0.84.0
js-debug-nightly|ms-|2022.11.917
live-server|ms-|0.4.3
live-server-preview|neg|0.1.4
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
code-settings-sync|Sha|3.4.3
code-spell-checker|str|2.11.0
turbo-console-log|trl|1.5.0
errorlens|use|3.6.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vim|vsc|1.24.3
bootstrap-3-snippets|wcw|0.1.0
JavaScriptSnippets|xab|1.8.0
vscode-colorize-plus|YuT|0.12.5
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30605430
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by gamersindo1223** [comment]
When is this happening, is thsi happening after you do something major?, have you tried uninstalling and reinstall vscode?

**Comment by aeschli** [comment]
Does it reproduce with extension disabled?

**Comment by margaretnajder** [comment]
Hello good people ..
I am not sure what I am doing wrong ..
I download vscode and then I download meny extensions ..
and i started to write simple code in html ..and got stuck ..
and then  was stuck for a day and i just pressed 20 times and started to
work ...

now i started to do css to that html and i link it and it connect and show
me on google chrome ...BUT ..i cant put any background or any images or
even do border around words ..i am not sure is it possible that extensions
blocking me somehow ?
I am totally new to it ..
i just took html on codecademy and now i bought a few courses html and css
on udemy and i am trying to learn ..
I am doing step by step as a guy in the udemy course ..and for him it is
working and for me it is not ..
i can't figure out what i am doing wrong ..every step i am doing as him
..and is stuck somehow  just let me write text nothing else now ...
what to do ? ...So sorry  so sorry that i am asking so stupid questions
...and thnak you so much for help ..

So is possible that extensions are blocking me ? i dowload 36 extensions
for html css javascript and github and some other dracula colorise etc ...

Please help,thank you so much  ..what to do ?  So sorry and thank you so
much ..I am totally new to this ,but i love it so much and so much wish to
learn it ...

**Comment by margaretnajder** [comment]
Hello good people ..
I am not sure what I am doing wrong ..
I download vscode and then I download meny extensions ..
and i started to write simple code in html ..and got stuck ..
and then  was stuck for a day and i just pressed 20 times and started to
work ...

now i started to do css to that html and i link it and it connect and show
me on google chrome ...BUT ..i cant put any background or any images or
even do border around words ..i am not sure is it possible that extensions
blocking me somehow ?
I am totally new to it ..
i just took html on codecademy and now i bought a few courses html and css
on udemy and i am trying to learn ..
I am doing step by step as a guy in the udemy course ..and for him it is
working and for me it is not ..
i can't figure out what i am doing wrong ..every step i am doing as him
..and is stuck somehow  just let me write text nothing else now ...
what to do ? ...So sorry  so sorry that i am asking so stupid questions
...and thnak you so much for help ..

So is possible that extensions are blocking me ? i dowload 36 extensions
for html css javascript and github and some other dracula colorise etc ...

**Comment by margaretnajder** [comment]
Sorry ..html is stuck again ..
So should I disable all extensions ?

**Comment by aeschli** [comment]
Yes, highly likely related to an installed extension. Does it reproduce with extensions disabled?
Do you have specific steps that reproduce the problem?

**Comment by margaretnajder** [comment]
Somehow now Html work and i even post image ..but css doesn't work at all ..
I copy and paste code fromW3school to be sure that i dont do any mistake
..and even dont link ..
i copy and past link, made file the same name and copy code from that
w3school exactly so everything is right ..and css even dont link to html
and is not making any changes ...before at least color and size was working
..now after i delete extension is even worst dont link at all .
So I am getting crazy ...I spent 4 days just trying to fix the problem and
now it is just a different  problem but still not working ..
html sims to work ..but now css dont work at all ..not even a link . i
totally dont know what to do ..i ' m completely lost ..

Please tell me what i am doing wrong ...i so much wish this could work and
i start to code ...i am totally stuck now ..
I bought all this different courses  to learn all full stack developer
languages .But I am stuck on the simplest one ...

**Comment by aeschli** [comment]
You have to provide a small HTML sample and describe the steps of what you are doing and seeing. Describe what's wrong with VS Code. Add screenshots.

**Comment by margaretnajder** [comment]
SO SORRY ...THANK YOU ! IS WORKING NOW  !
I canceled all extensions and downloaded  vc code again and now it's all
working ,css too!!!!

Everything works ..I am so happy .. I stayed until 2.18 am  and just 10
minutes ago started to work properly .
So now I can finally learn ..
O thank you so much .So much ..
thank you ..so so good to know that someone cared and tried to help when i
was totally lost ..
Thanks again ..I very very very much appreciate

**Comment by aeschli** [comment]
I'm glad you got it working. Closing the issue then.
