### ISSUE TITLE
can I hide the search bar in VS Code Insiders? 

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#166295]
Is there a way to hide this search bar in VS Code Insiders? I never use it and when I need to click to drag the window around there is really small real estate

![image](https://user-images.githubusercontent.com/19276747/201728714-224b86a4-3b21-455b-a9ac-146f2a2341ff.png)

**Comment by ArturoDent** [comment]
That is the `Command Center` and can be disabled vai the setting `Window: Command Center`.

**Comment by claudiaregio** [comment]
ah, so much better, thank you!

**Comment by ArturoDent** [comment]
@claudiaregio You should close this issue if that resolved it for you.

**Comment by claudiaregio** [comment]
I'll wait for @meganrogge who was assigned to decide, in case she wants to use this feedback for anything else

**Comment by daviddossett** [comment]
You can also right click on the Command Center to hide it. The "Launch" word is a bug. We'll get that removed.

<img width="692" alt="CleanShot 2022-11-16 at 11 48 06@2x" src="https://user-images.githubusercontent.com/25163139/202279638-ee914ec9-ae1c-4223-ad4b-50974efa9f10.png">

**Comment by claudiaregio** [comment]
Ah ok, thanks David :)

**Comment by daviddossett** [comment]
Closing given the discussion above 👆
