### ISSUE TITLE
Allow createWebviewPanel  to place a webview in the panel section instead of just editors

### ISSUE THREAD

**Issue by ZelCloud** [microsoft/vscode#166253]
Could createWebviewPanel get the option to setup a webview in the panel area (image below section D), instead of being limited to just the editor groups.

```javascript
vscode.window.createWebviewPanel(
      "catCoding",
      "My View",
      vscode.ViewColumn.One, // target panel instead of editors groups (C)
      {}
);
```

![](https://code.visualstudio.com/assets/docs/getstarted/userinterface/hero.png)

**Comment by gjsjohnmurray** [comment]
[Did you investigate ](https://code.visualstudio.com/api/extension-guides/webview) mentions "[Webview views](https://code.visualstudio.com/api/references/vscode-api#WebviewView)" and links to an [extension sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample). Did you investigate using these?

**Comment by mjbvz** [comment]
Yes as @gjsjohnmurray notes this is already possible using webview views

**Comment by ZelCloud** [comment]
I did see the [Webview API guide ](https://code.visualstudio.com/api/extension-guides/webview) and [extension sample](https://github.com/microsoft/vscode-extension-samples/tree/main/webview-view-sample), the difference is with the createWebviewPanel function you can target an editor and create the view and webview inside it even if the view doesn't exist there, but you cant do that for the panel section. For the panels to have a webview created programmatically you need to have an existing visible view to target then you resolve it.

For example [Calico Colors](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-view-sample/package.json#L30) needs the following contribute view to exist and be present in the sidebar area in order to generate a webivew outside of the editors.

```json
"contributes": {
	"views": {
		"explorer": [
			{
				"type": "webview",
				"id": "calicoColors.colorsView",
				"name": "Calico Colors"
			}
		]
	},
},
```

While [Cat Coding](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/package.json) doesn't need an existing view you can use the `createWebviewPanel` to simply say target X editor and generate the view and populate the webview content. Which is what I'd like to be able to do for the panel section. From what I've seen from the docs this doesn't seem to be possible.

**Comment by mjbvz** [comment]
@ZelCloud Yes that's how VS Code's views are designed. If you want to show as a view/panel, you also need to follow the same model

However you can pragmatically show/hide views by adding a `when` clause to the contribution point

**Comment by ZelCloud** [comment]
That sounds pretty close to what I need, one last question how would you focus on the panel view? Given this type of contributes:
```
"contributes": {
    "viewsContainers": {
      "panel": [
        {
          "id": "calico-view",
          "title": "Calico",
          "icon": "fancy.icon",
          "when": "calicoColors.calicoView"
        }
      ]
    },
    "views": {
      "calico-view": [
        {
          "type": "webview",
          "id": "calicoColors.colorsView",
          "name": "File Open",
          "when": "calicoColors.calicoView"
        }
      ]
    },
```

So initially the panel view is hidden then we use setContext to show the calico-view Panel (that works), but how would you focus on the view now?  I assume there's a way to focus on a view by id but I haven't seen any docs on it yet.
