### ISSUE TITLE
my vscode is now not supporting window 7

### ISSUE THREAD

**Issue by neerajrekwar** [microsoft/vscode#166228]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: VSCodeUserSetup-x64-1.71.2
- OS Version: 

Steps to Reproduce:

1. 740 the requested operation requires elevation
2. another instance of code is running but not responding

please solve shortly that serval time
neeraj rekwar

**Comment by deepak1556** [comment]
Windows 7 is not supported since 1.71, you can learn more about it here https://code.visualstudio.com/docs/supporting/faq#_can-i-run-vs-code-on-windows-7
