### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by golibjongulomov** [microsoft/vscode#166233]
Type: <b>Bug</b>

Hello. I'm using 2015 Macbook Pro and Chat window shows noting in Live Share

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 8, 8|
|Memory (System)|8.00GB (0.15GB free)|
|Process Argv|--crash-reporter-id ff4b80c9-338a-404c-97fa-2bbaf4cf9832|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|33.5.0
better-cpp-syntax|jef|1.16.3
vscode-language-pack-ru|MS-|1.73.11090923
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-wsl|ms-|0.72.0
remote-explorer|ms-|0.0.2
vsliveshare|ms-|1.0.5762
vsliveshare-pack|ms-|0.4.0
python-extended-snippets|tus|0.0.1
vscodeintellicode|Vis|1.2.29
jinja|who|0.0.8

(4 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30605430
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by S1983tt** [comment]
6261075646f055b99068d3688932416f2346dd3b

**Comment by hediet** [comment]
Please post your issue here: https://github.com/MicrosoftDocs/live-share
