### ISSUE TITLE
'Add line comment' should be called 'Toggle line comment'

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16626]
Notice that the add line comment actually toggles the comment. Thus the naming seems to be wrong.

![screen shot 2016-12-06 at 12 12 06](https://cloud.githubusercontent.com/assets/1926584/20923569/4e45067e-bbad-11e6-9857-b8ba404342df.png)

**Comment by alexandrudima** [comment]
@isidorn I think ctrl+k ctrl+c always adds a line comment, while ctrl+k ctrl+u always removes a line comment.

**Comment by isidorn** [comment]
Ah you are right. Clsoing as designed
