### ISSUE TITLE
go to test result

### ISSUE THREAD

**Issue by jeanbrazcosta** [microsoft/vscode#166232]
Type: <b>Feature Request</b>

When executing a unit test in java, when the test fails, a window opens with the error presented and it is also possible to press tabs and when finding a link, if pressed enter the cursor is positioned in the class and line where the error was mentioned.

However, when pressing esc, this window closes and it is not possible to go back to it, unless the test is run again.

Would it be possible to include a command in the command palette to open this window with the last error already shown?

VS Code version: Code - Insiders 1.74.0-insider (ef415578d1b1019db585718968a303eeca4b8979, 2022-11-11T05:19:14.666Z)
OS version: Windows_NT x64 10.0.19044
Modes: Restricted
Sandboxed: Yes

**Comment by connor4312** [comment]
The `Test: Peek Output` command can be used for this.
