### ISSUE TITLE
"]633;SetMark;Id=s0;Hidden" shows up in Test Peek Error windows

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#166270]
When I'm running tests recently, I'm seeing this weird markup show up in the "Peek Error" pane:

![Screenshot 2022-11-14 at 11 25 52](https://user-images.githubusercontent.com/1078012/201648573-c30d7627-1219-4be2-870b-b2430fbe1202.png)

This markup is not in the original text I'm providing to the `TestRun.appendOutput` call, but it looks like it's something VS Code is using itself:

https://github.com/microsoft/vscode/blob/90e165a528b5c81f884eb35eadb2f653921610ce/src/vs/workbench/contrib/testing/common/testResult.ts#L131

I'm not sure what's triggering it (it doesn't seem to show up in all output messages, only some) but perhaps @connor4312 (who seems to have worked on that code) will understand what's going on.

**Comment by DanTup** [comment]
Also, I don't know if it's related, but the last item seems to be duplicated in the test output compared to what was sent to `appendOutput`:

![Screenshot 2022-11-14 at 11 32 25](https://user-images.githubusercontent.com/1078012/201649877-21329031-db33-426e-9fe3-9453f91aca86.png)

**Comment by fabioz** [comment]
This happens to me too.

**Comment by DanTup** [comment]
@connor4312 thanks! The markers are gone, although I still see the last item duplicated (the last one has line numbers but the one before does not, oddly). Not sure if I'm causing this or not?

![Feb-08-2023 16-23-07](https://user-images.githubusercontent.com/1078012/217589714-c18ed618-ee1e-4b41-9819-a8cca48d200d.gif)

**Comment by aeschli** [comment]
Marking as verified as the fix for the original issue got verified. 

@DanTup Can you file a new issue for the duplicate entry?
