### ISSUE TITLE
Add link to open settings.json at top of Settings window

### ISSUE THREAD

**Issue by jez9999** [microsoft/vscode#166262]
Please add a link to "open settings.json" at the top of the Settings window.  I know you can press F1 and open settings json by searching for that command but I frequently open settings through File | Preferences, get this window, and end up scrolling down to a link somewhere for 'edit in settings.json'.

**Comment by gjsjohnmurray** [comment]
This one?

![image](https://user-images.githubusercontent.com/6726799/201649895-a897b697-e343-425b-99fc-e182e701d86a.png)

**Comment by jez9999** [comment]
Heh, missed that.  Goes to show how clear the icon is.  What is it with minuscule monochrome line art that looks indistinguishable from everything else nowadays? Oh well.

**Comment by gjsjohnmurray** [comment]
:+1: please close your issue.
