### ISSUE TITLE
Editor ruler(s) invisible when implicitly using default color

### ISSUE THREAD

**Issue by d0ggie** [microsoft/vscode#166261]
Hi.

There appears to be a small typo with b982536f83376e6266b3e0aaca6211699167b6cf (or a missing commit for editorColorRegistry.ts).

It uses `var(--vscode-editorRuler-ruler)` for the ruler color.  However, editorRuler color registry only seems to register `editorRuler.foreground` (at src/vs/editor/common/core/editorColorRegistry.ts).   So I suspect the correct variable name would be `--vscode-editorRuler-foreground`.

For each ruler a separate div element is instanciated (at src/vs/editor/browser/viewParts/rulers/rulers.ts).  An explicit color is defined if one uses the object syntax so this problem is only "visible" for users that implicitly use the default color by using the shorthand format.

So, a workaround is to use the long format, e.g. `"editor.rulers": [
 { "column": 80, "color": "#5a5a5a" } ]` (instead of `"editor.rulers": [ 80 ]`)

---
Does this issue occur when all extensions are disabled?: Yes

Version: 1.74.0-insider (user setup)
Commit: a62879bb46c84d0936798cf06debf5f92b04e4b4
Date: 2022-11-14T05:19:06.433Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.20348
Sandboxed: Yes

**Comment by thegumbyman** [comment]
I found using the (correct) var also works, i.e.
```json
"editor.rulers": [
    { "column": 80, "color": "var(--vscode-editorRuler-foreground)" }
]
```
The linter doesn't like it, as it's expecting a color, but it works.

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/pull/166698
