### ISSUE TITLE
Editor rulers aren't working anymore

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#166293]
Related?

https://github.com/microsoft/vscode/pull/165466

![image](https://user-images.githubusercontent.com/2193314/201718592-c79ecb45-0724-4d18-a98f-3ed9aae57788.png)

**Comment by r0oland** [comment]
Same here...

**Comment by r0oland** [comment]
fixed via the suggestion here:
https://github.com/microsoft/vscode/issues/166261

**Comment by sidverma32** [comment]
can i take this up? @alexdima

**Comment by alexdima** [comment]
Fixed via https://github.com/microsoft/vscode/pull/166698
