### ISSUE TITLE
 webview.asWebviewUri( vscode.window.activeTextEditor?.document.uri) unusable on VSCode/web

### ISSUE THREAD

**Issue by mihailik** [microsoft/vscode#166208]
Does this issue occur when all extensions are disabled?: No (this is to do with extension API)

- VS Code Version: 1.73.1
- OS Version: Windows 10

Steps to Reproduce:

1. Inside VSCode Web extension create a webview and invoke asWebViewUri on currently active file.
2. The resulting URI is not usable inside webview, it cannot be referred to in <style> or <script> or <img>

For example, if I use this code below to print out and compare URI taken from extension's own directory, and URI taken from the workspace filesystem, only extension's own work, i.e. resolves to a valid URL that can be loaded.

```javascript
    const panel = vscode.window.createWebviewPanel(
      'file preview',
      'HTML FILE PREVIEW',
      vscode.ViewColumn.One,
      { enableScripts: true }
    );
    panel.webview.html = '<PRE>' + JSON.stringify({
      extensionUri_asWebviewUri_str: panel.webview.asWebviewUri(context.extensionUri).toString(),
      document_uri_asWebviewUri_str: vscode.window.activeTextEditor?.document.uri ? panel.webview.asWebviewUri(vscode.window.activeTextEditor?.document.uri).toString() : undefined,

      extensionUri_asWebviewUri: panel.webview.asWebviewUri(context.extensionUri),
      document_uri_asWebviewUri: vscode.window.activeTextEditor?.document.uri ? panel.webview.asWebviewUri(vscode.window.activeTextEditor?.document.uri) : undefined,

      extensionUri: context.extensionUri,
      document_uri: vscode.window.activeTextEditor?.document.uri,
    }, null, 2);
```

If I run this inside an extension using vscode-test-web command, it prints this JSON:

```json
{
  "extensionUri_asWebviewUri_str": "http://localhost:3000/static/devextensions",
  "document_uri_asWebviewUri_str": "https://vscode-test-web%2Bmount.vscode-resource.vscode-cdn.net/small-html.html",

  "extensionUri_asWebviewUri": {
    "$mid": 1,
    "fsPath": "\\static\\devextensions",
    "_sep": 1,
    "external": "http://localhost:3000/static/devextensions",
    "path": "/static/devextensions",
    "scheme": "http",
    "authority": "localhost:3000"
  },
  "document_uri_asWebviewUri": {
    "$mid": 1,
    "path": "/small-html.html",
    "scheme": "https",
    "authority": "vscode-test-web+mount.vscode-resource.vscode-cdn.net"
  },

  "extensionUri": {
    "$mid": 1,
    "fsPath": "\\static\\devextensions",
    "_sep": 1,
    "external": "http://localhost:3000/static/devextensions",
    "path": "/static/devextensions",
    "scheme": "http",
    "authority": "localhost:3000"
  },
  "document_uri": {
    "$mid": 1,
    "fsPath": "\\small-html.html",
    "_sep": 1,
    "external": "vscode-test-web://mount/small-html.html",
    "path": "/small-html.html",
    "scheme": "vscode-test-web",
    "authority": "mount"
  }
}
```

See as **extensionUri_asWebviewUri_str** at the very top line refers to a valid HTTP URL http://localhost:3000/static/devextensions

And  **document_uri_asWebviewUri_str** in the second line refers to non-existent fake URL https://vscode-test-web%2Bmount.vscode-resource.vscode-cdn.net/small-html.html

## Why do I need it?

The end goal is to preview local workspace files inside VSCode Web extension.

There is a live preview extension that relies on HTTP server, and so it is not compatible with VSCode Web. My goal is to create a similar that would work on the web too.

**Comment by mjbvz** [comment]
Since the markdown preview (which is webview  based) can load resources on web, I suspect `asWebviewUri` is working

Can you please explain why you think the url is invalid? The uri that `asWebviewUri` only makes sense inside of webviews (i.e. it is supposed to be a "fake" url)

**Comment by mihailik** [comment]
## Confused

How is it that you **suspect it's working,** but at the same time it is **a fake** and not supposed to work?

## Clarification on the issue above

My description above means to pinpoint exact issue, calling `asWebviewUri()` works in one case, and returns unusable values in another.

<img width="1295" alt="image" src="https://user-images.githubusercontent.com/4041967/201738787-52369acd-1a6e-497c-aeb1-7cee758cb5c8.png">

See how in case (1) it returns `http://localhost:3000/...` which is a valid URL that resolves and produces valid content.

And in case (2) it returns `https://vscode-test-.....-resource.vscode.cdn.net/...` which contains invalid and very DNS host name, does not resolve and does not produce anything.

## Example of using the API

Here is the link to Microsoft's very own example of using that API to load resources:

https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/src/extension.ts#L201

In this code a chunk of HTML is loaded inside the webview, which includes references to other resources. Some of those references are for CSS stylesheet files, other for JS script files, or an animated GIF file of a cat.

Those links are not fake, they are valid URLs through which those files are fetched. The demo I am linking completely **relies** on those URLs working. Such as, the HTML document is styled with CSS and would look completely broken if that URL didn't resolve into the actual file.

Also noting you are the last one edited the file I am linking. Hopefully that means you can shed more light how to use that API correctly.

![Screen Recording 2022-11-14 at 18 43 27](https://user-images.githubusercontent.com/4041967/201741052-6ce1924d-a742-44be-8c5d-e0c0c88e3c51.gif)

## Why I need it

As I said above, my goal is to create an extension for VSCode that would be able to preview HTML files (and obviously use linked resources such as CSS, images from an HTML file). Similar to [Live Preview extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server) but able to work inside VSCode Web.

Hope this answers all your questions 👍

**Comment by mjbvz** [comment]
> How is it that you suspect it's working, but at the same time it is a fake and not supposed to work?

"Fake" in the sense that it only works inside the webview. They are valid uri strings, but only the webview can resolve them. They will not work in browsers or in any other tools

---

I still don't understand what the issue is. Please put together a minimal example that demonstrates what isn't working

**Comment by mihailik** [comment]
The URL no2 **does NOT** work inside the webview.

**Comment by mihailik** [comment]
This 1 one does work inside webview.

The secound one does not.

![image](https://user-images.githubusercontent.com/4041967/201742909-ad25080b-9cea-44bd-a8bf-4088a6ddcfad.png)

**Comment by mihailik** [comment]
Would a whole project of a dummy VSCode extension help?

**Comment by mjbvz** [comment]
How are you trying to use the url that doesn't work?

**Comment by mihailik** [comment]
Same as [that WebView demo example from Microsoft](https://github.com/microsoft/vscode-extension-samples/blob/main/webview-sample/src/extension.ts#L209): by pointing elements inside HTML towards it:

```javascript
panel.webview.html = `
  <link rel=stylesheet href="${resolvedUrl}" >
  <script src="${resolvedUrl}" >
  <iframe src="${resolvedUrl}" >
`
```

I am going to have a full dummy VSCode extension example that does that in few minutes.

**Comment by mihailik** [comment]
Oh wow, figured! 😆

It works with some elements, but not with IFRAME/OBJECT. Whatever funky server worker logic handling those magic URIs refuses to kick in for IFRAMEs.

I did find a way to make HTML preview work on VSCode Web too (sans HTMLs with nested IFRAMEs), hope to submit extension soon.

**Comment by mihailik** [comment]
For completeness, this works:

[https://github.com/mihailik/vscode-previewer/blob/3a59a...0b1a/index.js](https://github.com/mihailik/vscode-previewer/blob/3a59a639ebb979a4b399e6abd6d8395b09040b1a/index.js)

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/4041967/201792759-b84f2302-25c9-4b09-93b0-8b5b4fb7707e.png">

1. Getting HTML from the document.
2. Resolving the document base URI
3. Injecting `<base href="...">` inside the HTML
4. Pushing that HTML into WebView

The extension does a little bit more, wiring `alert()` and `document.title` from the embedded document to show in appropriate places in VSCode.

But as far as `webview.asWebviewUri(...)` call goes, it's working out properly 👍

Hope this writeup helps someone one day too.
