### ISSUE TITLE
Markdown Built-in Preview breaks when a URL ends with .com.au

### ISSUE THREAD

**Issue by metalmine** [microsoft/vscode#166393]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.73.1 (System setup)
- OS Version: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. In a markdown file have a link to an Australian website: [example](https://www.example.com.au
2. The markdown preview should now freeze at the point in which it cannot understand the new link and be unable to render the link.

I think it's because VSCode thinks that it's an audio embed?

**Comment by mjbvz** [comment]
Works fine for me:

<img width="1105" alt="Screen Shot 2022-11-15 at 12 51 59 PM" src="https://user-images.githubusercontent.com/12821956/202022937-63d46095-6cf1-4662-8d21-4485e8114dc5.png">

Please explain what the bug is

**Comment by gjsjohnmurray** [comment]
@metalmine please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by metalmine** [comment]
Ok, will do.

**Comment by metalmine** [comment]
Ok, yea it's not `VSCode`. Thanks for the tip, I'll do that in the future!
