### ISSUE TITLE
Add ability to search in a folder, triggered from the file path viewer

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/vscode#166378]
Type: <b>Feature Request</b>

Use case: I've navigated to a file in a Python library that my code uses. I want to search for a string in the whole of that library, to find an error message. How can I do that most efficiently?

For that use case, PyCharm has an awesome little UI trick: You right-click on any of the parent folders of the file you're looking at. The context menu gives you a "Search here" button.
Can we get something similar in VSCode? I could hover over any of the folders at the top of my editor window, and either have a search popup window, or pre-fill the path in the standard Search dialog.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No
Connection to 'SSH: path453' could not be established  Canceled
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

**Comment by ant0nsc** [comment]
Example: if I have `site-packages/azure/ai/ml/init.py` open, how can I quickly trigger search in `site-packages/azure`?

![image](https://user-images.githubusercontent.com/4396121/201969553-7b55b87f-e3d5-44dc-ab59-bc4932ef4006.png)

**Comment by gjsjohnmurray** [comment]
That UI element is called the breadcrumb.

If #56494 gets implemented it should become possible for extensions to add this kind of option even if it doesn't get added in the core product.

**Comment by andreamah** [comment]
If we implement #56494, we can probably talk about this again. It's likely that we'll already consider search if we implement that feature, but feel free to re-file if we do implement it! This might get lost in all of the search issues if we keep it open.
