### ISSUE TITLE
`monaco-button-dropdown-separator` has extra 1px top and bottom border artifact 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#166325]
This appears only in the latest insiders:

![image](https://user-images.githubusercontent.com/30305945/201790299-438b2574-6271-453a-b3af-b5bd20800696.png)

**Comment by lszomoru** [comment]
Nice catch!

**Comment by lszomoru** [comment]
Assigning to @aeschli as he is looking into this.

**Comment by aeschli** [comment]
Fixed by https://github.com/microsoft/vscode/pull/166362
