### ISSUE TITLE
Recommend Polyglot Notebooks extension when notebook with .NET Interactive kernel in metadata is opened

### ISSUE THREAD

**Issue by claudiaregio** [microsoft/vscode#166388]
In order to ensure the smoothest onboarding experience, it would be great if VS Code could recommend the Polyglot Notebooks Extension when a user opens a notebook with .NET Interactive as the kernel.

**Comment by rebornix** [comment]
> when a user opens a notebook with .NET Interactive as the kernel

What's the best way  for us to know that a Jupyter notebook using .NET Interactive as kernel?

**Comment by rebornix** [comment]
VS Code can recommend Polyglot Notebooks when users open .dib file (since it contributes the serializer), but it doesn't apply to ipynb files.

**Comment by claudiaregio** [comment]
Can we not read the notebook metadata and see that the kernel is .NET Interactive?

**Comment by rebornix** [comment]
@claudiaregio we can, ipynb will save kernel spec info into the document but I'm not sure we do that for .NET Interactive controllers.

**Comment by claudiaregio** [comment]
@jonsequitur @colombod @brettfo in case you guys had something to add

**Comment by jonsequitur** [comment]
The Polyglot Notebooks extension does add metadata, for example: 

```json
"metadata": {
  "kernelspec": {
   "display_name": ".NET (C#)",
   "language": "C#",
   "name": ".net-csharp"
  },
```

**Comment by DonJayamanne** [comment]
Closing this as I do not think this is required anymore.
Its been almost a year, and we haven't had any conversations around this issue, hence assume this is no longer required/important.
