### ISSUE TITLE
Last update broke C# formatter

### ISSUE THREAD

**Issue by CharlieHess** [microsoft/vscode#166329]
Type: <b>Bug</b>

Updated to 1.73.1 and now my C# formatter is busted, no longer respects my previously set preferences (brackets on same line, etc.) Of course, I have no idea or recollection of how I configured that because it was years ago, and as usual with VsCode I have no idea which one of n god forsaken extensions linked to the update broke this, so now I need to waste the next few hours of my life googling how to redo it. Plz, plz, plz never change people's settings during update and if you have to, provide a banner with migration actions. Ffs it's 2022 and we're still doing this to ppl

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 3|
|Memory (System)|32.00GB (0.03GB free)|
|Process Argv|--crash-reporter-id da296e29-1fc8-4490-861c-34888e4cdeaf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
require-sort|Per|0.0.1
shaderlabvscodefree|aml|1.3.3
ink|bru|1.3.1
gltf-vscode|ces|2.3.16
vscode-svgviewer|css|2.0.0
postcss|css|1.0.9
vscode-eslint|dba|2.2.6
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
github-actions|for|0.0.1
csharp-format-usings|gao|0.0.4
vscode-glsl|GeF|0.2.5
copilot|Git|1.58.7236
unity-code-snippets|kle|1.3.0
import-sorter|mik|3.3.1
vscode-docker|ms-|1.22.2
csharp|ms-|1.25.2
isort|ms-|2022.6.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
prisma|Pri|4.6.1
vscode-commons|red|0.0.6
vscode-xml|red|0.22.0
shader|sle|1.1.5
wallaby-vscode|Wal|1.0.348
clang-format|xav|1.9.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce2:30605431
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by mjbvz** [comment]
Please start by filing an issue against the C# extension
