### ISSUE TITLE
Possibly allow connection to remote device through web using secure password / Authenticator

### ISSUE THREAD

**Issue by navincodesalot** [microsoft/vscode#166322]
Sorry if this was mentioned before!

I was wondering if it would be possible to instead of using github or microsoft to login, you could change a setting when running your server and setup a password that would allow the user to access the files when on the URL. Adding onto that, for more security, support for apps like Google Authenticator to have a random 6 digit code that changes every so often would have more security and create another option to sign in.

Idk if doing one of these would hurt features like settings sync as they rely on github/microsoft to work.

I would love this feature to exist in VS Code Server as people that sometimes have restricted devices cannot signin with Github or Microsoft.
So if i could signin via password, I could easily access my files without having to worry about logging in with github,

**Comment by connor4312** [comment]
The underlying service is an Azure service which requires a user account for allocation. Running or allowing users to run separate services to authenticate to the tunnel is very unlikely to happen, and is outside the scope of VS Code.

However, in the future we will allow people to log in with their Microsoft account, which may be sufficient to get around the blockers.
