### ISSUE TITLE
Why vscode always autofill multi-line comments in all .c .cpp .h files?

### ISSUE THREAD

**Issue by nmpassthf** [microsoft/vscode#166398]
Type: <b>Bug</b>

Then a few months ago, vscode suddenly autofill multi-line comments (e.g. /** **/ comment) in all .c .cpp .h files and i can't get any configure to disable this feature.  (when i typing "/*", vscode will autofill "*/", i want to disable this feature)
I try to disabled all extension & delete all settings in user "settings.json" & workspace "settings.json", im pretty sure this is a vscode build in feature. 

This feature was destroyed my doxygen extension and i also couldn't run some macros.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.30GB free)|
|Process Argv|--crash-reporter-id a40099df-0744-41af-ad9c-13b7c60a78a6 --crash-reporter-id a40099df-0744-41af-ad9c-13b7c60a78a6 --crash-reporter-id a40099df-0744-41af-ad9c-13b7c60a78a6|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (62)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
vscode-django|bat|1.10.0
cmake-format|che|0.6.11
path-intellisense|chr|2.8.1
keil-assistant|cl|1.7.0
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
vscode-office|cwe|2.9.0
git-extension-pack|don|0.1.3
githistory|don|0.6.19
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
rust-syntax|dus|0.6.1
gitlens|eam|13.0.4
vsc-material-theme|Equ|33.5.0
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.9.0
macros|ged|1.2.1
todo-tree|Gru|0.0.220
CppSnippets|har|0.0.15
output-colorizer|IBM|0.1.2
vsc-python-indent|Kev|1.18.0
music-lyrics|lja|0.0.1
git-emoji-zh|mai|1.1.9
cortex-debug|mar|1.6.7
asm-code-lens|maz|1.10.2
git-graph|mhu|1.30.0
vscode-language-pack-zh-hans|MS-|1.73.11020948
isort|ms-|2022.6.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
makefile-tools|ms-|0.6.0
autodocstring|njp|0.6.1
material-icon-theme|PKi|4.22.0
java|red|1.12.0
c-cpp-definition-generator|rei|0.0.2
rust-analyzer|rus|0.3.1285
crates|ser|0.5.10
even-better-toml|tam|0.19.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscodeintellicode-completions|Vis|1.0.20
vscode-java-debug|vsc|0.46.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.6
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.2
jinja|who|0.0.8
material-theme|zhu|3.15.6
html-css-class-completion|Zig|1.20.0
linkerscript|Zix|1.0.2
vscode-open-in-github|ziy|1.3.6

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by aeschli** [comment]
VS Code has the feature that when typing `/*`, `*/` is automatically added. Is that would you mean?

**Comment by nmpassthf** [comment]
Some extension (e.g. Doxygen Documentation Generator) will generate text block when user typing `/**`, i need a config to disable this  feature

**Comment by aeschli** [comment]
https://github.com/microsoft/vscode/issues/154994 is the issue to make auto closing pairs (such as the comments) configurable.
