### ISSUE TITLE
The window has crashed (reason: "killed', code: '9')

### ISSUE THREAD

**Issue by Hesham-Salama** [microsoft/vscode#166375]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Latest stable (1.73)
- OS Version: macOS 13.0

This is a duplicate issue of https://github.com/microsoft/vscode/issues/145033

Had to make a new one since I can't comment.

The application displays "The window has crashed (reason: "killed', code: '9')" in an error message alert at startup then it exits.

I have to disable SIP due to some requirement of a third party app which I need so cannot enable it back.

I think there is no valid reason to deny starting and to be related to SIP of macOS, as other similar editors could open with no issues.

Steps to Reproduce:
1. Disable SIP 
2. Open VSCode

**Comment by jameschu** [comment]
same here 
Why vscode honor sip?

**Comment by Hesham-Salama** [comment]
Edit: there was another similar issue, its author suggests this solution, will try it and close if it works:

https://github.com/microsoft/vscode/issues/163175#issuecomment-1287596885
