### ISSUE TITLE
Debug widget broken when stopping debug while attaching to another

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16630]
Steps to Reproduce:

1. debug a node.js app 
2. start another debug session by attaching to some port that is not opened
3. while that is running stop debugging

=> the debug widget looks weird

![image](https://cloud.githubusercontent.com/assets/900690/20923690/023ca5f6-bbae-11e6-854f-e6cb7961a7b4.png)

**Comment by isidorn** [comment]
Fixed as part of the infinite call stack crazyness. Closing as dup (there were many of these filed)
