### ISSUE TITLE
Content inside style attributes should have same coloring as css style elements

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16635]
Refs #16526

Notice how the css attributes have different coloring if they are inside the style element or inside the style attributes. Ideally the coloring would be the same

![screen shot 2016-12-06 at 12 24 46](https://cloud.githubusercontent.com/assets/1926584/20923929/17be2408-bbaf-11e6-8b2c-c4c52814dcfb.png)

**Comment by aeschli** [comment]
will be fixed once https://github.com/Microsoft/vscode/issues/3008 is implemented
