### ISSUE TITLE
Sublime: 'transpose' behaviour difference

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16633]
while testing #16545:

VS Code's 'transpose' command doesn't work at end of the line. This behaviour differs from Sublime.

**Comment by rebornix** [comment]
@weinand can you help provide more info about the behavior of Sublime Text? From what I see, both Code and Sublime do nothing when the cursor is at the end of the line

Sublime Text
![sublime-transpose](https://cloud.githubusercontent.com/assets/876920/20943042/cf2b7624-bbb2-11e6-8d0d-237e537aada2.gif)

Our implementation
![vsc-tranpose](https://cloud.githubusercontent.com/assets/876920/20943118/123f2870-bbb3-11e6-90a1-10212ddf99ad.gif)

**Comment by rebornix** [comment]
Maybe I know how to find the issue, if there are trailing spaces after the last nonwhitespace character, sublime text does nothing when the cursor is between the last nonwhitespace char and the space. However here we are still transposing.

I don't know why Sublime Text does it this way as I don't see any reason that the trailing spaces are special. Besides, Sublime Text 2 and Sublime Text 3 are doing Transpose differently. I'd like to keep it this way first and see more people's feedback :)

Thanks for pointing it out!

**Comment by weinand** [comment]
@rebornix You tried transpose at the "end of the text".
What I meant was: when there is another line following, then transpose at the end of a line continues on the next line.

**Comment by rebornix** [comment]
@weinand it's a valid one!
