### ISSUE TITLE
Watch expressions should not expand in drag & drop

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16639]
Testing #14813

![14813](https://cloud.githubusercontent.com/assets/5047891/20924425/9bec42e4-bbb1-11e6-8785-f168cd093efc.gif)

**Comment by isidorn** [comment]
I see this is [tree behavior](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/treeView.ts#L1469) which currently can not be configured.
@joaomoreno shouldn't this be coming from the DragAndDrop such that I could customise in for this use case?

**Comment by joaomoreno** [comment]
![evil](https://m.popkey.co/d539df/w67bR.gif)

**Comment by joaomoreno** [comment]
@isidorn This can only happen if the [drag and drop reaction has `accept === true`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/parts/tree/browser/tree.ts#L535).

**Comment by isidorn** [comment]
Ok that is a fine workaround to not make you customise that behavior.

@alexandrudima now we only expand on the first level - it is not possible to drill down into an expression. Making it not expand also on the top level would require changes on the tree level which seem to be complicated based on the attached gif :D

**Comment by joaomoreno** [comment]
It's not a workaround, it's really the fix. 💃

**Comment by joaomoreno** [comment]
Oh no. We can do better.
