### ISSUE TITLE
Dialog buttons no longer have foreground/background color tokens

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#166321]
In insiders.vscode.dev the dialog buttons are inheriting the colors of `monaco-dialog-box`:

<img width="524" alt="image" src="https://user-images.githubusercontent.com/30305945/201780475-888abe85-c895-43ea-ac0d-37734533cf6e.png">

**Comment by sbatten** [comment]
I see this in a lot of places, and it looks to be caused by https://github.com/microsoft/vscode/commit/e5bf5a7939d586e33d5ae822891040dfa906aeb5#diff-66a07df088d0eb0a5f86befb962cf52e893a8cc3ae2fc716968effb45c485185
