### ISSUE TITLE
Cancelling "Turn on Remote Tunnel Access..." shows progress and errors

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#166354]
1. Run `Turn on Remote Tunnel Access...`
2. Escape from the quick pick

🐛 There's an error and a progress notification showing up.

![image](https://user-images.githubusercontent.com/22350/201906693-e3b32f1b-21c9-4f57-92dd-72766b6b2e45.png)

**Comment by aeschli** [comment]
This got fixed in the meantime
