### ISSUE TITLE
Not able to modify color of Tree view item in Explorer view

### ISSUE THREAD

**Issue by ajaygera** [microsoft/vscode#166382]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
1.71.2
- OS Version: 
windows 11
Steps to Reproduce:

I have added my own explorer view in my extension.
Here I added nodes/tree view items however  I am not finding any way to customize and choose color my tree view items in explorer view

**Comment by alexr00** [comment]
You can set the color with a file decoration provider (tree items do not need to be files to use file decoration providers): https://code.visualstudio.com/api/references/vscode-api#FileDecorationProvider
