### ISSUE TITLE
Tasks: Run Build Task doesn't run default build task

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#166366]
1. Open your clone of this repo in  VS Code.
2. ctrl+shift+B to run the Tasks: Run Build Task commnad
3. Instead of running the default build task, a picker shows with only NPM tasks in it.

**Comment by meganrogge** [comment]
@alexr00 I cannot repro. Do you have any keybindings configured?

**Comment by alexr00** [comment]
It also reproed when I ran the "Tasks: Run Build Task" command directly from the command palette.

**Comment by meganrogge** [comment]
Ok I'll keep trying 🤔

**Comment by alexr00** [comment]
I haven't been able to repro again yet, so I'm fine with closing.
