### ISSUE TITLE
Excessive find-replace in debugViewlet.ts

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16637]
```ts
container.textContent = value.replace(/\n/g, '\\n').replace(/\r/g, '\\r').replace(/\t/g, '\\t');
```

Why is [this line](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugViewer.ts#L79) there? Those `replace` calls don't do anything, right?

**Comment by isidorn** [comment]
How I understand the replace function it is doing something, the first one replaces real newlines with '\n' and then passes that string to the next replae function and so on. The final string is returned to the container.textContent

**Comment by joaomoreno** [comment]
Oh, it's actually escaping those characters. Got it.

You should do it in one pass, though:

```ts
const map = { '\n': '\\n', '\r': '\\r', '\t': '\\t' };
container.textContent = value.replace(/[\n\r\t]/g, char => map[char]);
```

Something like that.

**Comment by isidorn** [comment]
Did not use a map in the end since it would require excessive \\ due to string escaping and looked ugly

**Comment by joaomoreno** [comment]
Are you sure that works?

**Comment by isidorn** [comment]
@joaomoreno you are right and I was stupid
