### ISSUE TITLE
Hovers are not shown correctly for duplicate variables in a block

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16632]
Testing #15359

See the following snippet
```
router.get('/', function (req, res, next) {
  let object;
  {
    let object = '5';
    object = 7;
  }
  object = someFunction();
  res.render('index', { title: 'Express' });
});


function someFunction() {
  return [1, 2, 3];
}
```

While debugging inside the block where `object` is defined again. Hovering on it is not giving correct value. After coming out of the block, all `object` hovers are showing the value returned by `someFunction()`. See the video

![dec-06-2016 12-13-58](https://cloud.githubusercontent.com/assets/10746682/20923699/0f377d4e-bbae-11e6-9b4f-8f6331b33cc2.gif)

**Comment by isidorn** [comment]
This is coming from the node2 debug adapter. Assigning first to @roblourens to investigate

**Comment by kieferrm** [comment]
Here is a different variation of @sandy081's issue. Before the shadowing variable is introduced the line shows the outer-scope value. That makes sense since the debugger doesn't really look ahead. Once the shadowing variable is introduced no value is show for it.

![n2elnekzgv](https://cloud.githubusercontent.com/assets/4674940/20983828/c8e0907c-bc72-11e6-90ef-91ba5ffdda51.gif)

**Comment by roblourens** [comment]
Two problems, first the scope locations are not sourcemapped, which is my mistake. I'll fix it today, tracked here - https://github.com/Microsoft/vscode-chrome-debug-core/issues/141

But even when I fix that, this line causes an issue - https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L216 - it finds both variables, but they have different values, so the hover isn't shown. I'm not sure why that check exists? I think the first one should always take precedence if the scopes are in the right order.

**Comment by isidorn** [comment]
@roblourens that check exists for all the other debug adapters that do not have the scope range information. Shouldn't [this line](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/electron-browser/debugHover.ts#L212) take care of duplicate scopes? Thus only the scope with the correct range will be left?

First one taking precedence would potentially show the wrong debug hover value for other adapters, thus we decided it is better to now show any value at all.

**Comment by roblourens** [comment]
The scopes are nested, so all the scopes contain the expression.

**Comment by isidorn** [comment]
Then that line needs to be improved in order to find the most specific scope. E.g smallest scope that containes the current line.
Nothing I would change today but we can improve this in january

**Comment by roblourens** [comment]
January is fine with me

**Comment by roblourens** [comment]
The original issue is verified. There's still a related problem which I think we can't do anything about.

![image](https://cloud.githubusercontent.com/assets/323878/22384085/97a7638c-e481-11e6-8678-da2543325407.png)

This is even easier to see with inline debug values. On `console.log(bar)`, all we know is that it's in the current scope, so we use this scope's `bar`. And if the redefinition of bar was removed, it would be correct.
