### ISSUE TITLE
Keyboard shortcut to Toggle Terminal doesn't work until you click into the terminal pane

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/vscode#166306]
Type: <b>Bug</b>

1.  I have Toggle Terminal command mapped to Ctrl + `
2.  Open Visual Studio Code (the Terminal pane defaults to open)
3.  type Ctrl + ` -- nothing happens
4.  click into the open Terminal pane
5.  type Ctrl + ` -- the terminal pane collapses
6.  the keyboard shortcut works as expected for the remainder of the session.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.44GB free)|
|Process Argv|--folder-uri file:///c%3A/source/whirlwindbuildings/wsbDevPackages/Whirlwind.DotnetDevTools --crash-reporter-id 24452be9-7e87-49ef-aeb5-c1b3aefe6bde|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
add-reference|adr|1.0.2
libman|adr|1.0.1
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
gitlens|eam|13.0.4
EditorConfig|Edi|0.16.4
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
dotnet-test-explorer|for|0.7.8
rest-client|hum|0.25.1
better-cpp-syntax|jef|1.16.3
compare-folders|mos|0.22.3
vscode-bicep|ms-|0.12.40
vscode-docker|ms-|1.22.2
blazorwasm-companion|ms-|1.1.0
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
remote-ssh|ms-|0.92.0
remote-wsl|ms-|0.72.0
azure-account|ms-|0.11.2
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.2
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5762
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.10.0
vscode-jest|Ort|4.6.0
vscode-nuget-gallery|pat|0.0.24
LiveServer|rit|5.7.9
code-spell-checker|str|2.11.0
es6-string-html|Tob|2.12.0
cmake|twx|0.0.17
vscode-icons|vsc|12.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce2:30605431
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by burtonrodman** [comment]
![image](https://user-images.githubusercontent.com/7658657/201750264-30dc6a25-04db-4756-b5ba-6adc0c40db80.png)

**Comment by burtonrodman** [comment]
For reference, my goal is to be able to navigate between a code window and the terminal WITHOUT touching the mouse -- this is the behavior that has broken -- please test accordingly.

**Comment by meganrogge** [comment]
This is working for me in insiders, so has likely been fixed

**Comment by burtonrodman** [comment]
can confirm working for me in insiders.  i notice it opens with the Terminal Pane collapsed (which is fine by me).

Thanks!
