### ISSUE TITLE
Error "job table full or recursion limit exceeded" in VSCode integrated terminal when using OhMyZsh with PowerLevel10k theme.

### ISSUE THREAD

**Issue by vinibortoletto** [microsoft/vscode#166303]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.73.1
- OS Version: Pop!_OS 22.04 LTS

Steps to Reproduce:

1. Open a directory from VSCode integrated terminal: `code directoryName`
2. A new VSCode instance will open, with the integrated terminal displaying the error: `job table full or recursion limit exceeded`

![Screenshot from 2022-11-13 15-13-54](https://user-images.githubusercontent.com/47364504/201743036-4be10603-323f-44c4-964f-e2312d2a5509.png)
![Screenshot from 2022-11-13 15-14-13](https://user-images.githubusercontent.com/47364504/201743041-8640cb9f-a8b4-4e65-9977-77a0323cc53a.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
