### ISSUE TITLE
Built-in Profiles

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#166359]
We should have some Built-In profiles to help users more easily get setup with VS Code.
Profiles should not be extension / language specific but instead specific to the job the user needs to do. For example:
* Text Editor profile (minimalistic, hides UI and makes the editor the center of the experience)
* Document writer profile
* Data scientist profile
* Out of the box profile (we could ask users to use this profile when reproducing issues - bot could advertise it)

VS Code default settings are not cool, and profiles should also be used as a way to make the popular VS Code customisations more discoverable. Profiles should be opionated! There's even a website that helps with this https://makevscodeawesome.com/
The built-in profiles should be surfaced in the Welcome view and probably under the Profiles menu (maybe a submenu).

**Comment by isidorn** [comment]
@joaomoreno had a great idea that we should also link from our Docs - so in Python docs => "Would you like to apply a profile for Python, click here". User clicking on this would open VS Code and offer to apply a profile. Same for other languages. So this will connect well our website docs to the experience in VS Code.

@gregvanl @luabud what do you think?

**Comment by luabud** [comment]
I love the idea! We have some tutorials that could benefit from profiles as well, like the getting started and the web development ones.
I agree with the idea of making profiles specific to the job to be done, but given there are different frameworks that are used for the similar goals (e.g. Django, Flask and FastAPI) and each one may require different configs, is the idea that we'd offer different profiles per framework, or would it be just one profile that would include configs for all of the supported frameworks (in this case, to offer support for web development with Python more generally?)

**Comment by isidorn** [comment]
@luabud good question. Depends on the case - I suggest to best write down what would go inside the Django profile, what would go in the Flask profile, in the FastAPI one etc. And then see how much overlap there is. If there is a lot of overlap (like I think there will be) then the best is to have one Python Web Development profile.

**Comment by joaomoreno** [comment]
> We should have some Built-In profiles to help users more easily get setup with VS Code.

I'm not entirely sure it's a good idea to have built-in profiles out of the box. What VS Code should do is drive users to profiles, in certain areas of the product, ie Getting Started, docs, etc.

**Comment by alexdima** [comment]
I personally don't think of profiles in terms of the job I'm trying to do (I'm always doing the same job in my world view), but in terms of the technology and extensions I need to get things done. 
* If I work on a Rust project, I want the rust-analyzer extension, but I don't want to deal with rust-analyzer in any other projects.
* If I work on VS Code I want eslint, vscode selfhost test provider and PR pinger extensions, but I don't want them anywhere else
* If I work on vscode-docs I want the markdown preview github styling extension, but I don't want this anywhere else. 

I would therefore find it useful for VS Code to have a Rust profile out of the box that could help me get great Rust experience in VS Code, or a Java profile for the same, etc. And all of this without interfering with my other projects.

**Comment by theonlyfoxy** [comment]
Maybe even Built-in Marketplace for Profiles.

**Comment by Binboukami** [comment]
> (...) What VS Code should do is drive users to profiles, in certain areas of the product, ie Getting Started, docs, etc.

An introduction to the profiles feature could be added into one of the walkthroughs displayed on the Welcome page.

Maybe under the settings and extensibility topics.

![image](https://user-images.githubusercontent.com/43557272/225736141-6cf8ce23-ded6-4ffe-adcd-2defc1ed8554.png)

**Comment by sandy081** [comment]
Builtin profile templates are now supported in the Create flow

<img width="640" alt="image" src="https://user-images.githubusercontent.com/10746682/233493729-5b4277ea-8752-401f-a692-ef939d510990.png">
