### ISSUE TITLE
check50 (for CS50) acting weird. Please help.

### ISSUE THREAD

**Issue by CatUnderTheNameOfA** [microsoft/vscode#166425]
For about 2 days no matter what changes (major, minor and everything in between) I made to a function in my program check50 would give back the exact same result. Then when running a previous version today (which check50 had looked over before) it returned a different result - now nothing was working in that function, because there was no output (not an incorrect output, but absolutely nothing at all). I found it odd that for days it had given the same result for different program versions and was now giving different results for the same version. I then made (out of curiosity) a syntactic sugar change (instead of while( ) used for( ) in a loop), which should not have resulted in anything, and ran the program again. This time not only did an output exist, it was more correct. Is anyone else seeing similar behavior when running check50? I am worried now that I cannot trust its answers concerning the correctness of my program. Please help.

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Embedder: codespaces

**Comment by roblourens** [comment]
Sorry, I don't know what check50 is, it doesn't sound like there is an issue with vscode here.
