### ISSUE TITLE
Typescript errors with intellisense that doesn't happen in other IDEs

### ISSUE THREAD

**Issue by JavierMonleonLopezMW** [microsoft/vscode#166445]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: macOs Monterey 12.5.1 (21G83)

Steps to Reproduce:
1. Install extension Vue.volar v1.0.9
2. Instal extension Vue.vscode-typescript-vue-plugin v1.0.9
3. Install packages "vue": "3.2.37", "typescript": "4.7.4"

Intellisense is complaining about TS errors that my colleagues using other IDEs like WebStorm don't have.

Some examples:
`Default export of the module has or is using private name 'Props'.ts(4082)`
[https://github.com/johnsoncodehk/volar/issues/1232](url)

`Property 'showPicker' does not exist on type 'EventTarget'.ts(2339)`
`@mouseup="$event.target.showPicker()"`

`Unknown at rule @applycss(unknownAtRules)`

`<style scoped>
.input {

@apply p-2 w-full bg-gray-100 rounded-lg;  
}
</style>`. 

We have the same tsconfig files, with the same TS version. I also tried different volar versions, enabling _take over mode_, etc etc... 

It's sad because I really like vscode but finally I'll have to switch to jetbrains..

**Comment by mjbvz** [comment]
Please file this against Volar. VS Code does not support Vue out of the box
