### ISSUE TITLE
Searched words appear underneath the searchbox

### ISSUE THREAD

**Issue by kaminaze** [Microsoft/vscode#16644]
- VSCode Version: 1.7.2
- OS Version: Window 10

Steps to Reproduce:

1. Have a page of editor filled with text
2. Search for words at the top of the editor using Ctrl + F, now the word you've search is underneath the searchbox which is really annoying

**Comment by rebornix** [comment]
Let's track it in https://github.com/Microsoft/vscode/issues/5525 and solve it in May.
