### ISSUE TITLE
capability to place breakpoint on empty lines may mislead during debugging

### ISSUE THREAD

**Issue by udhayprakash** [microsoft/vscode#16642]
- VSCode Version:
- OS Version:

Steps to Reproduce:

1. We are able to **place the breakpoint** **on empty lines**, within the code file. I feel that it is misleading, and not necessary.

**Comment by connor4312** [comment]
Talking to Rob, this is a bit of a difficult issue. At the moment editor doesn't know what lines breakpoints can be added to. For instance, in node/chrome we don't map them to a file until we actually start debugging--it's totally possible to have an empty line that's actually sourcemapped to debuggable code, and we can't say for certain that there's no language where setting a breakpoint on an empty line is impossible.<sup>[1](https://en.wikipedia.org/wiki/Whitespace_(programming_language))</sup>.
