### ISSUE TITLE
Chinese: , and . ignored

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16647]
Refs #16547

IE11, monaco editor, turn on simplifed chinesse Type . or , in full width form. They are not typed in immediatly, they are ignored. 

Which conflicts with what is expected https://github.com/Microsoft/vscode/wiki/IME-Test#windows-chinese

**Comment by alexandrudima** [comment]
@rebornix Can you please confirm if this is a bug or not ?

**Comment by rebornix** [comment]
I still can't reproduce this issue on Windows 10, IE version 11.1066.14393

**Comment by alexandrudima** [comment]
Closing then.
