### ISSUE TITLE
Scroll wheel clicking (or shift-clicking) the taskbar icon does not open a new window

### ISSUE THREAD

**Issue by jonstodle** [Microsoft/vscode#16643]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.10586
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-auto-open-markdown-preview|hnw|0.0.3|
|copy-markdown-as-html|jerriepelser|1.0.0|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. Open VS Code
2. Scroll wheel click or shift click the taskbar icon
3. New window does not open

This is inconsistent behaviour with the OS.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/13905
