### ISSUE TITLE
Impossible to write multiple japanese words on one line

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16646]
Refs #16547

1. IE11, monaco editor
2. Turn on japanesse hiragana, try to type sennsei twice in once line. Impossible, I am only able to get one word per line

**Comment by rebornix** [comment]
@isidorn I've tried to reproduce this issue and #16647 but failed.

![sennsei](https://cloud.githubusercontent.com/assets/876920/20946739/e201289e-bbc0-11e6-9ca9-555dec5f615b.gif)

See above GIF, I typed in `，。` and two sennsei in one line, besides, the F12 tools is showing that the code is up to date as the only change I made is `isChrome` check.

Can you help provide more info then I can know how to reproduce? BTW, it's an issue then it might be IE's behavior change.

**Comment by isidorn** [comment]
@rebornix feel free to ping me when you get online so I can show you how this behaves on my win10 VM. I might be doing something wrong here.

As for the comma and dot I am pressing the basic , and . and they get ignored.
