### ISSUE TITLE
Extension tabs widget focus outline is cut off at the top

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#166476]
On Insiders

1. Navigate to an extension detail page
2. Tab to the actionbar that has entries like Details, Feature Contributions, etc.
3. :bug: The focus outline is cut off at the top

![Focused details view in the extension tabs widget showing the focus outline is cut off](https://user-images.githubusercontent.com/7199958/202238567-c0e438e8-96c6-45a2-8508-cb8ca06fc761.png)

**Comment by daviddossett** [comment]
This one-off tab UI drives me a little bit bananas. @rzhao271 how possible is it to use the same tab component that we use for the bottom panel to avoid the entropy here?

**Comment by rzhao271** [comment]
I'm not sure about the code involved, but it seems like a good idea to reuse the component. The Settings editor also currently has a one-off tab UI.
