### ISSUE TITLE
Can't expand variables and folders

### ISSUE THREAD

**Issue by blaze-Youssef** [microsoft/vscode#166495]
Type: <b>Bug</b>

When I click folders or variables while debugging the section doesn't expand.

VS Code version: Code - Insiders 1.74.0-insider (39ff7eb93b513976b85b69085414cab11f8ed4cc, 2022-11-16T14:18:57.639Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.65GB (8.73GB free)|
|Process Argv|C:\\Users\\youss\\Projects\\python\\Binance-Trader-Bot-main --crash-reporter-id faf61a85-b967-4946-9c44-b536c6a5d522|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.1
snippet|dev|1.0.3
prettier-vscode|esb|9.9.0
vscode-insertdatestring|jsy|2.3.1
procfile-support|log|0.0.1
rainbow-csv|mec|3.3.0
vscode-docker|ms-|1.22.2
black-formatter|ms-|2022.7.13061128
isort|ms-|2022.8.0
python|ms-|2022.19.13201008
vscode-pylance|ms-|2022.11.21
jupyter|ms-|2022.11.1003221035
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.2
material-icon-theme|PKi|4.22.0
colonizer|uri|0.8.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30611227
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
gswce1:30602633
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by blaze-Youssef** [comment]
I get this error in dev tools:
 
  ERR Cannot read properties of undefined (reading 'getNodeLocation'): TypeError: Cannot read properties of undefined (reading 'getNodeLocation')

**Comment by jpgmiranda** [comment]
I am having the same issue on macOS 13.0.

**Comment by MariaSolOs** [comment]
Same issue happening both on Mac and Windows machines, both with the latest Insiders versions.

**Comment by dbaeumer** [comment]
See it as well. Explorer is affected for me as well.

**Comment by dbaeumer** [comment]
Version: 1.74.0-insider (user setup)
Commit: 39ff7eb93b513976b85b69085414cab11f8ed4cc
Date: 2022-11-16T14:18:57.639Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
Sandboxed: Yes

**Comment by MrAnyx** [comment]
I have the same issue with the the `Explorer` pannel and the sidebar on the `Settings` page

**Comment by blaze-Youssef** [comment]
An update was released and fixed the problem.
