### ISSUE TITLE
Breakpoints context menu

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16645]
Testing #16013 

IMHO:
* context menu actions should be grouped in two sections: ones that contains actions applying to the current breakpoint and one that contains "global" actions
* it would be nice if the label "Enable/Disable breakpoint" would reflect the state of the current breakpoint
* it would be nice if some of the duplicated "global" actions could be removed.

![image](https://cloud.githubusercontent.com/assets/5047891/20926670/eba0d99c-bbbd-11e6-985d-56fb638b4447.png)

**Comment by bpasero** [comment]
I see there is now a lot less entries in the menu:

![image](https://cloud.githubusercontent.com/assets/900690/22294311/18afbdbe-e313-11e6-9d2f-4c2a87185fed.png)

For example, no more way of adding a "Function breakpoint". 

@isidorn please clarify what to verify here.

**Comment by isidorn** [comment]
@bpasero please verify the context menu makes sense and that there is no dupication between actions in the breakpoint title and the context menu. That the actions are nicely grouped together.
That the enable / disable label gets updated.
Bascially what alex critized in the original issue

**Comment by bpasero** [comment]
Ok I am not sure what kind of rule you are following here, it seems you removed some of the commands that exist in the header (e.g. Disable All Breakpoints and Add Function Breakpoint) but you still left in Remove All Breakpoints. 

Maybe we should just go with what dev tools do:

![image](https://cloud.githubusercontent.com/assets/900690/22297101/932873de-e31c-11e6-809b-c7d92b473bf2.png)

Anyhow, I give you the verified for cleaning up the menu.

**Comment by isidorn** [comment]
No we are way cooooooler
