### ISSUE TITLE
Cannot collapse or expand Explorer tree

### ISSUE THREAD

**Issue by ivme83** [microsoft/vscode#166478]
Type: <b>Bug</b>

Open a workspace
attempt to toggle the expand or collapse of a node in the Explorer tree

VS Code version: Code - Insiders 1.74.0-insider (39ff7eb93b513976b85b69085414cab11f8ed4cc, 2022-11-16T14:18:57.639Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.76GB (45.82GB free)|
|Process Argv|C:\\Users\\Roland\\Desktop\\shortcuts\\SpyFu_Frontend.code-workspace --crash-reporter-id 44922a6d-9ffe-4bed-8330-2b75c78031a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (60)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
add-reference|adr|1.0.2
asp-net-core-switcher|adr|2.0.2
blazor-snippet-pack|adr|2.6.1
csharp-to-typescript|adr|1.12.1
libman|adr|1.0.1
namespace|adr|1.1.2
terminal-commands|adr|1.0.5
toggle-hidden|adr|1.0.2
user-secrets|adr|2.0.1
markdown-mermaid|bie|1.15.2
mermaid-markdown-syntax-highlighting|bpr|1.5.0
htmltagwrap|bra|0.0.7
vscode-toggle-quotes|Bri|0.3.6
path-intellisense|chr|2.8.1
gitignore|cod|0.9.0
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
netcore-editorconfiggenerator|dog|0.1.1
netcore-extension-pack|dog|1.7.0
netcore-snippets|dog|3.15.2
quicktype-refresh|dog|1.0.2
gitlens|eam|13.0.4
EditorConfig|Edi|0.16.4
dotnet|for|0.0.4
dotnet-test-explorer|for|0.7.8
vscode-pull-request-github|Git|0.54.1
output-colorizer|IBM|0.1.2
vscode-edit-csv|jan|0.7.2
vscode-nuget-package-manager|jmr|1.1.6
docomment|k--|0.1.31
csharpextensions|kre|1.7.3
rainbow-csv|mec|3.3.0
csharp|ms-|1.25.2
remote-ssh|ms-|0.92.0
powershell-preview|ms-|2022.11.0
remote-explorer|ms-|0.0.2
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5762
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
vetur|oct|0.36.1
indent-rainbow|ode|8.3.1
vscode-jest|Ort|4.6.0
vscode-nuget-gallery|pat|0.0.24
vscode-versionlens|pfl|1.0.10
material-icon-theme|PKi|4.22.0
material-product-icons|PKi|1.4.1
vscode-commons|red|0.0.6
vscode-stylelint|sty|0.87.6
open-in-browser|tec|2.0.0
msbuild-project-tools|tin|0.4.9
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-icons|vsc|12.0.1
vscode-todo-highlight|way|1.0.5
vscode-js-console-utils|wht|0.7.0
change-case|wma|1.0.0
markdown-all-in-one|yzh|3.4.3
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vscaat:30438846
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30611228
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
gswce1:30602633
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by ConnorBaker** [comment]
I am experiencing the same issue, even with all extensions disabled.

VS Code version: Code - Insiders 1.74.0-insider (39ff7eb93b513976b85b69085414cab11f8ed4cc, 2022-11-16T14:32:47.781Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.0-50-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 3, 16|
|Memory (System)|64.00GB (24.83GB free)|
|Process Argv|. --crash-reporter-id 9a8065ba-d4c3-446c-a4b0-c7aff8340898|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: intuitive|
|OS|Linux x64 5.15.0-50-generic|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (8 x 2992)|
|Memory (System)|15.56GB (4.03GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.93.2022111515
jupyter-keymap|ms-|1.0.0


</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewvextcfv2:30611228
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
gswce1:30602633
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by erik-source** [comment]
Same issue here. I noticed looking at the "Window" output, when clicking a node in the explorer this error gets logged

```shell
2022-11-16 11:28:44.675 [error] Cannot read properties of undefined (reading 'getNodeLocation'): TypeError: Cannot read properties of undefined (reading 'getNodeLocation')
    at j.u (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:547:51788)
    at vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:23967
    at f.invoke (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at h.fire (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:83:23607
    at f.invoke (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:145)
    at n.deliver (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:2029)
    at h.fire (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:1667)
    at HTMLDivElement.T (vscode-file://vscode-app/c:/Users/mtl347/AppData/Local/Programs/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:85:8842)
```

**Comment by jrieken** [comment]
This is a regression from us mangling private properties. There is something along these lines `const model = ((this.tree as any).model as ITreeModel<T, TFilterData, TRef>); // internal` which is now breaking
