### ISSUE TITLE
The menu only comes up when releasing the mouse, so this appears to be fixed.

### ISSUE THREAD

**Issue by Juniorsnet** [microsoft/vscode#166484]
The menu only comes up when releasing the mouse, so this appears to be fixed.

_Originally posted by @joaomoreno in https://github.com/microsoft/vscode/issues/65787#issuecomment-624522828_
      
As version 1.73.1 the problem persist, the conext menu is showed on press mouse button not on release.

**Comment by joaomoreno** [comment]
> the conext menu is showed on press mouse button not on release

Does this create any actual issues?

**Comment by Juniorsnet** [comment]
> > the conext menu is showed on press mouse button not on release
> 
> Does this create any actual issues?

Yes I have the same problem that is in this issue https://github.com/microsoft/vscode/issues/65787

**Comment by joaomoreno** [comment]
Is this the problem?

> It's hard to open context menu (in new design) by clicking mouse right button, because it closes immediately or trigger first point "go to definition". It seems double click triggered. I opened context menu in file system (folder, terminal) and it worked correctly. Probably it's not mouse bug.

That issue should be fixed. Can you show me a screen recording?

**Comment by Juniorsnet** [comment]
Same problem thats in this video.
https://github.com/microsoft/vscode/issues/65787#issuecomment-461856370
Has a hint, when the menu has enough space in the screen there is no problem. If not, the menu show bellow the mouse and the conext menu gets triggered.
In this video show the same problem.
https://github.com/microsoft/vscode/issues/113175#issuecomment-749386790

**Comment by joaomoreno** [comment]
@deepak1556 Could something be done at the Electron level?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167941
