### ISSUE TITLE
All of extensions are not working

### ISSUE THREAD

**Issue by sevvaltuncay** [microsoft/vscode#166483]
Type: <b>Bug</b>

I don't do anything wrong and i've just opened to my file and extension hot terminated unexpected 3 times within the last 5 minutes i don't know what i do  next now

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.22GB free)|
|Process Argv|--crash-reporter-id 0d603753-5a06-44d0-8fab-02bbcaf7aa97|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (66)</summary>

Extension|Author (truncated)|Version
---|---|---
pug|ama|1.0.1
compile-superhero|Ban|10.3.2
vscode-django|bat|1.10.0
doxdocgen|csc|1.4.0
c-cpp-compile-run|dan|1.0.19
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
xml|Dot|2.5.1
prettier-vscode|esb|9.9.0
c-cpp-runner|fra|4.2.0
codespaces|Git|1.13.1
vscode-pull-request-github|Git|0.54.1
todo-tree|Gru|0.0.220
discord-vscode|icr|5.8.0
classic-asp|ili|0.0.4
better-cpp-syntax|jef|1.16.3
swift|Kas|0.2.0
vsc-python-indent|Kev|1.18.0
mongodb-vscode|mon|0.9.5
vscode-docker|ms-|1.22.2
vscode-language-pack-tr|MS-|1.73.11090923
csharp|ms-|1.25.2
dotnet-interactive-vscode|ms-|1.0.3553070
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.20
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
js-debug-nightly|ms-|2022.11.1417
makefile-tools|ms-|0.6.0
powershell|ms-|2022.10.0
remote-explorer|ms-|0.0.2
remote-repositories|ms-|0.24.0
vsliveshare|ms-|1.0.5762
autodocstring|njp|0.6.1
vscode-thunder-client|ran|1.20.1
java|red|1.12.0
vscode-xml|red|0.22.0
python|tht|0.2.3
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-swift-development-environment|vkn|2.12.3
vscode-java-debug|vsc|0.46.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.6
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.2
vscode-spring-initializr|vsc|0.11.1
opendatadsl|Wal|0.7.12
vs-asp-classic|wfe|0.0.4
jinja|who|0.0.8
eno|Wsc|2.3.53
qf|Wsc|6.8.122

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce1:30612156
iaj6b796:30608729
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by alexdima** [comment]
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: https://code.visualstudio.com/insiders/

**Comment by sevvaltuncay** [comment]
I solved the problem i deleted to vs code and rebuilding extensions. Then it worked.
