### ISSUE TITLE
Pressing Up on the first line while entering a commit message removes the current message without possibility to Ctrl-Z

### ISSUE THREAD

**Issue by Strepto** [microsoft/vscode#166454]
Does this issue occur when all extensions are disabled?: **Yes**

- VS Code Version: 
- Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
Sandboxed: No

- OS Version: Windows_NT x64 10.0.19044

Pressing `Arrow-Up` on the first line while entering a commit message replaces the current commit message you were entering, and there is no way to go back.

I had written a longer message and was just changing the title when I pressed "Arrow Up" one time too many, and the entire message was lost

Steps to Reproduce:

Using the built in Source Control module

1. Commit something with any commit message
1. Do a change an prepare a new commit
1. Write a commit message
1. Press Up on keyboard enough times to "Insert the previous commit message"
1. Try to go back to the message you were writing (This is not possible with Ctrl-Z or anything else I found)

![commitmsglost](https://user-images.githubusercontent.com/3185998/202174003-2b0956f3-7616-4958-8b3a-a5faddc723e2.gif)

**Comment by gjsjohnmurray** [comment]
Similar to #127072

**Comment by Strepto** [comment]
If you press `Arrow-Down` to the end of the final line of the "previous commit", and one more time. It seems to go back to the commit you were writing!

This is not obvious when the previous commit was multi-line, but it works at least.

Feel free to close the issue. But I still think that supporting Ctrl-Z or similar would be more intuitive. 

Tried to find a fix for this in VSCode but I could not find the code path for it :/

**Comment by lszomoru** [comment]
Closing this in favour of https://github.com/microsoft/vscode/issues/127072
