### ISSUE TITLE
Typescript: code completion not work when using property accessors

### ISSUE THREAD

**Issue by moriwang** [microsoft/vscode#166457]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No

Steps to Reproduce:
1. Type `'`, VSCode shows suggestions.
![code completion](https://user-images.githubusercontent.com/9151525/202188541-bc79cd4e-24fa-46e7-a160-97bb95ad84df.gif)

2. Type `''` first, move cursor back, then type `f`, VSCode shows nothing.
![ezgif-2-ae7ce67b9b](https://user-images.githubusercontent.com/9151525/202188853-c0b0b0e3-d713-4147-a677-9b836aa25a35.gif)

BTW, typescript playground works fine on this case.
https://www.typescriptlang.org/play?#code/FAYw9gdgzgLgBGARgKzgXjgb2HXcBmYYAXHAOSFhkA0OeiAhgE6lmNNnAC+cDUc4aDGDAkyANoUiZALpwgA

**Comment by mjbvz** [comment]
Quick suggestions are disabled by default inside of strings. You can either manually trigger suggestions when in a string or configure `editor.quickSuggestions` to enable them
