### ISSUE TITLE
`Uncaught (in promise) TypeError: this._extensionTelemetry.onExtensionError is not a function`

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#166432]
Seeing this when running unit tests:

```
Uncaught (in promise) TypeError: this._extensionTelemetry.onExtensionError is not a function
```

**Comment by lramos15** [comment]
@jrieken You added this function so assigning you as well. Not sure why we would be trying to trigger an extension error during unit tests.

**Comment by jrieken** [comment]
@lramos15 this is because an incomplete stub-instance 👁️ #166709

**Comment by lramos15** [comment]
> @lramos15 this is because an incomplete stub-instance 👁️ #166709

Yay for tests? 🤷 😝
