### ISSUE TITLE
Search viewlet progress bar never completes

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16653]
Testing #16416

I tried to stress test the search service and come up with as ugly regexes as I can produce :). While typing I would hit Enter from time to time to stress it even more. I got in the following state (I saw the 4 workers going down, but the UI progress bar continued to move until at one point it is just stuck and the workers shut down in the meantime):

![image](https://cloud.githubusercontent.com/assets/5047891/20927923/e3d40aa8-bbc3-11e6-8a77-aefc2062d99e.png)

**Comment by alexandrudima** [comment]
Better repro steps: 
* open vscode
* search for ([a-z])\1(?!\1)
* have match case, match word and regex enabled
* press Enter multiple times, while the search is running.
* the progress bar is moving (apparently by itself) and then gets stuck near 90%...

**Comment by alexandrudima** [comment]
This search is also appearing to be substantially slower than the stable version and **appears to give completely different results**
* not sure if that is an actual issue or we were just lucky before, but before I would get to see hits in the top level folder, followed by `.vscode`, followed by `build`, which sort of makes sense.
* it looks like the new version has some different traversal strategy, with the hits in the top level files or in `.vscode` not showing up


![16653](https://cloud.githubusercontent.com/assets/5047891/20928201/f3773178-bbc4-11e6-8d50-e61498d3261b.gif)

**Comment by roblourens** [comment]
If the search hits the 2048 result limit like in this case, you may see a different set of results than in stable. We traverse the files in the same order as before, but they'll get shuffled a little when they get distributed to 8 workers.

I can't repro this issue with the progress bar though. I'll keep trying.
