### ISSUE TITLE
'Builder function' might not be necessery

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16654]
Refs #15873

All the docs for methods for `SnippetString` start with 'Builder function'. As a user while I am quickly browsing through intelisense I want to quickly find out what each method does. Since each method has the same prefix 'Builder function' the process of finding out the purpose of each method is harder than needed.

'Builder function' is also not used anywhere else in our API.

Consider removing this from the docs, or at least do not put it at the very start of each method description.

**Comment by jrieken** [comment]
Disagree - it is a builder function because it used the builder-pattern (return this after invocation) which allows for code like `snippet.appendText('abc').appendPlaceholder('ddd').appendText('etc')`. That's why it is called builder-method

**Comment by isidorn** [comment]
Sure but that still does not have to be the first sentence in the doc. My point is that the actual functionality is more important and should be seen before the 'builder function'.
