### ISSUE TITLE
syntax highlighting 

### ISSUE THREAD

**Issue by HarshVirani914** [microsoft/vscode#166541]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.73.1 
- OS Version: macOS ventura 13.0.1

Issue:
Colour syntax highlighting not working properly
<img width="1440" alt="Screenshot 2022-11-17 at 11 05 37 AM" src="https://user-images.githubusercontent.com/91112662/202364879-6477dd90-6649-4474-84ca-9efce8b8f29c.png">

the import/require sentences are not highlighting properly. this was the issue when i opened my vs code today. it was working properly yesterday.

**Comment by saulgudmon** [comment]
about 15 mins ago I was reading code and vscode sort of flashed and all my comments and a bunch of other stuff turned white. Reinstalled vscode and restarted pc, still the same. Literally happened while I was looking at it and not touching any input device. And judging by the timing of your issue I'm guessing the code devs did a little oopsie?

**Comment by HarshVirani914** [comment]
downgrading the JavaScript and TypeScript Nightly extension to **v5.0.20221115** from **v5.0.20221116** seems to be working perfectly

**Comment by HarshVirani914** [comment]
> about 15 mins ago I was reading code and vscode sort of flashed and all my comments and a bunch of other stuff turned white. Reinstalled vscode and restarted pc, still the same. Literally happened while I was looking at it and not touching any input device. And judging by the timing of your issue I'm guessing the code devs did a little oopsie?
> 
> ![image](https://user-images.githubusercontent.com/33010393/202365976-64b4a7c1-36bc-4c9e-b725-f67a17aad7ad.png)
> 
> Oh, curious why did you close the issue? is it working for you now? It is still messed up for me

sorry, check the above comment and try again

**Comment by waki285** [comment]
> downgrading the JavaScript and TypeScript Nightly extension to **v5.0.20221115** from **v5.0.20221116** seems to be working perfectly

I had same problem. but this is working for me. Thanks!

**Comment by scarf005** [comment]
there weren't any option for me to downgrade it (apparently it doesn't use vscode's new 'switch to nightly' feature?), and searching `javascript and typescript` only shows nightly version.
![image](https://user-images.githubusercontent.com/54838975/202369688-05bb2209-4d0c-4737-89f6-0445acac5e2c.png)

**Comment by cvince** [comment]
Same problem with me now
<img width="501" alt="Screenshot 2022-11-16 at 10 10 35 PM" src="https://user-images.githubusercontent.com/1720051/202369838-aa7899ff-4c0f-4171-9c14-dda644e34f12.png">

**Comment by HarshVirani914** [comment]
> there weren't any option for me to downgrade it (apparently it doesn't use vscode's new 'switch to nightly' feature?), and searching `javascript and typescript` only shows nightly version. ![image](https://user-images.githubusercontent.com/54838975/202369688-05bb2209-4d0c-4737-89f6-0445acac5e2c.png)

yes this is the extension that is causing the issue.
just go to the extensions list and at the right bottom on this extension there you will see **settings icon** click it and **select install another version**..
<img width="1440" alt="Screenshot 2022-11-17 at 11 45 38 AM" src="https://user-images.githubusercontent.com/91112662/202370691-5897ce2f-85cf-4cd5-ae90-7e85b8b586b1.png">
and then select the version ending with **15.**
<img width="1440" alt="Screenshot 2022-11-17 at 11 48 15 AM" src="https://user-images.githubusercontent.com/91112662/202371091-148a1f98-ae6d-40dd-a128-af93e867a2fe.png">

**Comment by scarf005** [comment]
@HarshVirani914  thank you, this worked for me.

**Comment by Konadu-Akwasi-Akuoko** [comment]
> downgrading the JavaScript and TypeScript Nightly extension to **v5.0.20221115** from **v5.0.20221116** seems to be working perfectly

Thanks a lot @HarshVirani914, I was having the same problem, but downgrading fixed it for me. Thanks

**Comment by BarrySong97** [comment]
I have the same issue too. I just disabled JavaScript and TypeScript Nightly extension. it works for me.

**Comment by zhangky01** [comment]
> downgrading the JavaScript and TypeScript Nightly extension to **v5.0.20221115** from **v5.0.20221116** seems to be working perfectly

yup.

**Comment by HarshVirani914** [comment]
thanks now i can close this and code peacefully lol.. 🥹

**Comment by scarf005** [comment]
but there's a buggy (latest) version and the underlying problem still isn't solved, i think the issue should be kept open

**Comment by padunk** [comment]
![Screen Shot 2022-11-17 at 13 38 18](https://user-images.githubusercontent.com/25411350/202374516-9a1fee5e-f7b2-43d2-b228-37f48736259b.png)

Just like @HarshVirani914 said. This extension is the culprit.
Downgrade it to ...15 works. -> https://github.com/microsoft/vscode/issues/166541#issuecomment-1318113517

**Comment by scarf005** [comment]
@padunk  yeah I guess it should be continued in microsoft/vscode-typescript-next#49

**Comment by HarshVirani914** [comment]
> but there's a buggy (latest) version and the underlying problem still isn't solved, i think the issue should be kept open

ok then..

**Comment by georgeiliadis91** [comment]
The discussion should be continued to the extension repository not here. 
There is already an issue open here: 
https://github.com/microsoft/vscode-typescript-next/issues/50

**Comment by HarshVirani914** [comment]
this issue will be further discussed in **https://github.com/microsoft/vscode-typescript-next/issues/50** repo..
thank you

**Comment by tepafril** [comment]
> > there weren't any option for me to downgrade it (apparently it doesn't use vscode's new 'switch to nightly' feature?), and searching `javascript and typescript` only shows nightly version. ![image](https://user-images.githubusercontent.com/54838975/202369688-05bb2209-4d0c-4737-89f6-0445acac5e2c.png)
> 
> yes this is the extension that is causing the issue. just go to the extensions list and at the right bottom on this extension there you will see **settings icon** click it and **select install another version**.. <img alt="Screenshot 2022-11-17 at 11 45 38 AM" width="1440" src="https://user-images.githubusercontent.com/91112662/202370691-5897ce2f-85cf-4cd5-ae90-7e85b8b586b1.png"> and then select the version ending with **15.** <img alt="Screenshot 2022-11-17 at 11 48 15 AM" width="1440" src="https://user-images.githubusercontent.com/91112662/202371091-148a1f98-ae6d-40dd-a128-af93e867a2fe.png">

Thanks alot pal! Work like a charm

**Comment by wangdahoo** [comment]
+1
