### ISSUE TITLE
Vcode colour theme not working

### ISSUE THREAD

**Issue by alsonick** [microsoft/vscode#166582]
For some reason, the colour theme isn't working correctly for most keywords and string literals in my TypeScript & TSX files. My default theme is Dark+ (default theme). I've tried to restart vscode but that doesn't help either, also I'm not using GitHub Copilot.

<img width="694" alt="Screenshot 2022-11-17 at 13 40 30" src="https://user-images.githubusercontent.com/101022772/202461395-5c648f54-9d2d-492c-a4ad-427257df227d.png">

**Comment by rolivegab** [comment]
Having the same issue :/
It's for multiple languages, including typescript and javascript.

**Comment by rolivegab** [comment]
A solution which worked for me was to disable typescript nightly. Please try it!

**Comment by joaoggnogueira** [comment]
same issue

**Comment by joaoggnogueira** [comment]
![image](https://user-images.githubusercontent.com/10080622/202465786-987d25a3-9d37-461a-82c8-fe8fa2c67025.png)

**Comment by robindunkerley** [comment]
Also experiencing this

**Comment by mfkrause** [comment]
There seems to be a bug in the newest version of the JavaScript and TypeScript Nightly extension. Downgrade it to version 5.0.20221113.

**Comment by zhGio** [comment]
I managed to bug this up by using my workspace typescript (which is 4.x something) also

**Comment by mfkrause** [comment]
> > There seems to be a bug in the newest version of the JavaScript and TypeScript Nightly extension. Downgrade it to version 5.0.20221113.
> 
> how can I downgrade an extension?

![CleanShot 2022-11-17 at 15 03 44@2x](https://user-images.githubusercontent.com/10306735/202467011-cebdeb69-6292-4333-9c99-9cf90b36d8d0.jpg)

**Comment by joaoggnogueira** [comment]
Maybe, maybe, maybe a downgrade cannot solve all highlightings but seems better than nothing

![image](https://user-images.githubusercontent.com/10080622/202467703-42c757ab-3cad-48bd-bb9b-001ce3f9542d.png)

**Comment by alsonick** [comment]
> There seems to be a bug in the newest version of the JavaScript and TypeScript Nightly extension. Downgrade it to version 5.0.20221113.

Thanks @mfkrause!

This temporarily fixed my issue.

**Comment by robindunkerley** [comment]
If the downgrading doesn't work, make sure that your colour theme is not set to `Dark (Visual Studio)`

**Comment by nipunsadvilkar** [comment]
@rolivegab How did you figure out that it is an issue with the typescript nightly extension?

**Comment by rolivegab** [comment]
> @rolivegab How did you figure out that it is an issue with the typescript nightly extension?

Tried removing extensions 1 by 1 until figured it out

**Comment by ramsesgarate** [comment]
> There seems to be a bug in the newest version of the JavaScript and TypeScript Nightly extension. Downgrade it to version 5.0.20221113.

This worked for me

**Comment by JaLe29** [comment]
`5.0.20221113` works fine but whisper/code helper is completely dead :-(

**Comment by ctjlewis** [comment]
What if, I know this is gonna blow everyone's minds, we didn't ship nightly versions without testing to see if they totally explode when they're automatically installed into millions of user devices?

Just a thought.

**Comment by baezor** [comment]
Updating the extension to the latest version seems to fix the issue.

**Comment by Onyelaudochukwuka** [comment]
upgrading to JavaScript and TypeScript Nightly v5.0.202211170 fixed this for me

**Comment by chris-burkhardt** [comment]
I had the same problem and checked the plugin this morning. There was a button that said "Reload Required". After clicking the button, the issue was fixed.
