### ISSUE TITLE
Why two SnippetString appendVariable methods

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16652]
Refs #15873

Why do we have two appendVariable method in SnippetString. Could we not merge them into one that would have a defaultValue as an optional paramter?

The downside of the current approach is that quite some documentation is duplicated.

**Comment by jrieken** [comment]
Yeah, we should merge them together into one. Initially this was because of `$foo` vs `${foo:placeholder}` reasons (it would generate different snippet text) which we don't generate anymore.
