### ISSUE TITLE
Don't suppress the terminal from the menu bar in web

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#166506]
In the recent Edit Sessions UX study we ran, we saw several participants searching in vain for the terminal item in the compact menu on vscode.dev, sometimes for minutes:

![image](https://user-images.githubusercontent.com/30305945/202282621-ec542c56-a888-41b3-8a9d-9215173712eb.png)

Could we consider bringing it back? I'm guessing we intentionally suppressed it because terminals can't run in the web, but participants were simply confused that it wasn't there without connecting its absence to the fact that vscode.dev was a browser application. 

Additionally, RemoteHub contributes a welcome view for the terminal which is one of the primary ways we explain that users must continue working elsewhere to run or debug code, and the fact that the terminal is completely suppressed means one less opportunity for users to organically learn the limitations of vscode.dev through our welcome views.
![image](https://user-images.githubusercontent.com/30305945/202292244-2a16ca2f-5e09-43f6-9aee-2549eb42c129.png)

cc @bamurtaugh @stevencl

**Comment by Tyriar** [comment]
Yes that is why it was removed. It doesn't do much but if it helps reduce confusion I guess it's worth it?

**Comment by jrieken** [comment]
Uploading Screen Recording 2023-01-25 at 14.13.25.mov…

**Comment by Tyriar** [comment]
@meganrogge when I enable the menu again and fix up the terminal command, the run/customize task items give this on the scripts/code-web sample-folder:

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/2193314/216714091-870c81cd-2123-4a14-9afb-d4263f5b6af3.png">

That does actually run, not sure what it's doing exactly though. Is that a custom execution task running in the web worker ext host? If so you might need a context key on those menu items to only show them when a custom execution task is registered?

**Comment by meganrogge** [comment]
Unless I'm missing something, I believe only registered tasks will show there - if they're running when you select them, then I don't think there's an issue.

**Comment by Tyriar** [comment]
@meganrogge I think there's a built-in fake task when running code-web is what I mean, when run in actual vscode.dev then running it might do nothing. In that case it should hide similar to how we're changing the behavior of New Terminal depending on whether extension contributed profiles exist
