### ISSUE TITLE
div not color

### ISSUE THREAD

**Issue by alfiyansyahhh** [microsoft/vscode#166534]
Type: <b>Bug</b>

not color in tag html and react tags and import tags

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.00GB free)|
|Process Argv|--crash-reporter-id 3f6e31c4-1bd0-4c79-8d42-56ae1049df54|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
html-snippets|abu|0.2.1
bootstrap5-vscode|Anb|0.4.2
simple-react-snippets|bur|1.2.7
turbo-console-log|Cha|2.5.6
path-intellisense|chr|2.8.1
styco|Dan|0.2.5
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.0.4
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
html-snippets|gey|0.2.3
go|gol|0.36.0
vscode-react-typescript|inf|1.3.1
react-typescript-boilerplate|Mag|0.2.2
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.2
remote-containers|ms-|0.262.3
vscode-typescript-next|ms-|5.0.20221116
material-icon-theme|PKi|4.22.0
synthwave-vscode|Rob|0.1.14
vs-code-prettier-eslint|rve|5.0.4
html5-boilerplate|sid|1.1.1
prettier-vscode|Sim|2.0.7
js-jsx-snippets|sky|11.0.0
rest-api-client|unj|1.1.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
full-react-snippets|wal|1.4.2
JavaScriptSnippets|xab|1.8.0
bootstrap-v4-snippets|Zac|1.1.3
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
282f8724:30602487
gswce1:30612156
3d0df643:30608728
dbltrim-noruby:30604474

```

</details>

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode/issues/166525#issuecomment-1317981911

**Comment by aeschli** [comment]
@alfiyansyahhh Can you provide a screenshot along with a small code HTML/TS/JSX code sample that shows the problem?

**Comment by alfiyansyahhh** [comment]
> Maybe [#166525 (comment)](https://github.com/microsoft/vscode/issues/166525#issuecomment-1317981911)

solved, thanks.
