### ISSUE TITLE
React syntax highligh broken

### ISSUE THREAD

**Issue by dalladirosa** [microsoft/vscode#166543]
Type: <b>Bug</b>

After i update to ventura 13.0.1, suddenly most of all syntax become #abb2bf color

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 8, 10|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 953b0de5-86d8-4703-a1d1-230893b33274|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tailwindcss|bra|0.9.1
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|2022.11.1604
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.54.1
vscode-graphql|Gra|0.8.3
vscode-graphql-syntax|Gra|1.0.5
vue-snippets|hol|1.0.4
graphql-for-vscode|kum|1.15.3
vscode-docker|ms-|1.22.2
remote-wsl|ms-|0.72.0
vscode-typescript-next|ms-|5.0.20221116
vsliveshare|ms-|1.0.5762
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
color-highlight|nau|2.5.0
vetur|oct|0.36.1
material-icon-theme|PKi|4.22.0
typescript-hero|rbb|3.0.0
LiveServer|rit|5.7.9
vscode-styled-components|sty|1.7.5
sass-indented|syl|1.8.22
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
volar|Vue|1.0.9
vscode-typescript-vue-plugin|Vue|1.0.9
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.6

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474

```

</details>

<img width="934" alt="image" src="https://user-images.githubusercontent.com/29054050/202368199-2cf1bfb4-5727-4c08-822e-ab7798bfdd0f.png">

**Comment by duc-gp** [comment]
why is this closed, how was this resolved? I think iam facing the same issue, import, export and comment statements are not highlighted anymore

**Comment by dalladirosa** [comment]
> why is this closed, how was this resolved? I think iam facing the same issue, import, export and comment statements are not highlighted anymore

for the temporary fix, you can disable `JavaScript and TypeScript Nightly` and there are a lot of people already making the issue

**Comment by duc-gp** [comment]
oh thanks, didnt even know about this extension `JavaScript and TypeScript Nightly`. deactivating this extension solved it for me as well, thanks
