### ISSUE TITLE
syntax coloring

### ISSUE THREAD

**Issue by salmanpary** [microsoft/vscode#166576]
Type: <b>Bug</b>

nextjs syntax color formatting missing

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.74GB (8.52GB free)|
|Process Argv|--crash-reporter-id 12f5a449-c8af-4258-9982-110bdc4c4e45|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (90)</summary>

Extension|Author (truncated)|Version
---|---|---
node-js-snippet|abd|1.1.3
es7-javascript-class-snippets|abr|0.4.0
html-snippets|abu|0.2.1
flutter-snippets|ale|3.0.0
bootstrap5-vscode|Anb|0.4.2
browse-lite|ant|0.3.0
vite|ant|0.2.5
code-gnu-global|aus|0.2.2
vscode-tailwindcss|bra|0.9.1
simple-react-snippets|bur|1.2.7
java-run|cao|1.1.4
doxdocgen|csc|1.4.0
dart-code|Dar|3.52.1
flutter|Dar|3.52.0
vscode-eslint|dba|2.2.6
react-redux-react-router-snippets|dis|0.4.29
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.0.4
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
vscode-postman|eri|2.1.0
prettier-vscode|esb|9.9.0
bootstrap-4-cdn-snippet|eve|1.13.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
vscode-mysql|for|0.4.1
vscode-javac|geo|0.2.42
copilot|Git|1.59.7338
copilot-nightly|Git|1.59.7353
vscode-pull-request-github|Git|0.54.1
vscode-flutter-files|gor|4.4.2
bootstrap5-snippets|Han|1.2.5
beautify|Hoo|1.5.0
vscode-react-typescript|inf|1.3.1
latex-workshop|Jam|9.0.1
search-node-modules|jas|1.3.0
better-cpp-syntax|jef|1.16.3
cmake-language-support-vscode|jos|0.0.7
solidity|Jua|0.0.141
node-module-intellisense|lei|1.5.0
flutter-tree|mar|1.0.0
json|Mee|0.1.2
dotenv|mik|1.0.1
prettify-json|moh|0.0.3
mongodb-vscode|mon|0.9.5
vscode-docker|ms-|1.22.2
vscode-dotnet-runtime|ms-|1.6.0
data-workspace-vscode|ms-|0.3.0
mssql|ms-|1.16.0
sql-database-projects-vscode|ms-|0.19.0
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.3
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.2
vscode-typescript-next|ms-|5.0.20221116
vsliveshare|ms-|1.0.5762
vsliveshare-audio|ms-|0.1.91
awesome-flutter-snippets|Nas|3.0.3
nodejs-snippets|piy|0.0.2
material-icon-theme|PKi|4.22.0
vscode-thunder-client|ran|2.0.0
java|red|1.12.0
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
bootstrap4-vscode|the|6.1.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.46.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.6
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.39.2
vscode-spring-initializr|vsc|0.11.1
bootstrap-3-snippets|wcw|0.1.0
nextjs|Wil|0.0.8
vscode-nextjs-snippets|wil|0.3.0
c-cpp-snippets|wlh|0.1.0
JavaScriptSnippets|xab|1.8.0
json|Zai|2.0.2

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by Fapalz** [comment]
version 1.73.1
Same problem but in all projects

**Comment by filipac** [comment]
Same issue for me

**Comment by SwapnilSoni1999** [comment]
same issue in all the projects 
syntax is not properly highlighted

**Comment by salmanpary** [comment]
Roll back javascript nightly extension to version which is 3 days ago.There is a bug with its recent update

**Comment by salmanpary** [comment]
Downgrade the extension to 5.0.20221113

**Comment by iSamBa** [comment]
Same issue for me as well
VScode:
  - Version: 1.73.1
  - Commit: 6261075646f055b99068d3688932416f2346dd3b

**Comment by searc-h** [comment]
Same issue for me;

**Comment by argahsuknesib** [comment]
works now with the nightly extension, just had to reload it again.
