### ISSUE TITLE
[Regression] Vscode has a hard dependency on a printing library (CUPS), but does not even offer printing

### ISSUE THREAD

**Issue by strelec** [microsoft/vscode#166511]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Gentoo Linux

Starting with 1.72, vscode has a hard dependency on a printing library, otherwise it refuses to even start. CUPS is quite a heavy dependency and not all Linux installations have it. 

This is a bug for two reasons:
1. vscode does not even support printing (https://github.com/Microsoft/vscode/issues/5953)
2. Even then, such heavy libraries shall be only loaded on demand.

**Comment by strelec** [comment]
So, can you arrange with electron to not include the dependency on a heavy printing library?

Nobody has printers these days.

**Comment by strelec** [comment]
Do you know which vscode release is going to start using Electron 22?

**Comment by connor4312** [comment]
Verified with `dpkg -I`
