### ISSUE TITLE
Theme issue.

### ISSUE THREAD

**Issue by Udaay** [microsoft/vscode#166575]
Type: <b>Bug</b>

No matter which color theme i use [externally downloaded / default VS code theme], there are many colors which are missing.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|8.00GB (0.74GB free)|
|Process Argv|--crash-reporter-id 139b3c5c-8571-458c-8f91-ccd9ef9e8ae9|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (26)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
Bookmarks|ale|13.3.1
vscode-tailwindcss|bra|0.9.1
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.0.4
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
vscode-peacock|joh|4.2.2
lintel|mfl|1.3.4
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
vscode-docker|ms-|1.22.2
remote-containers|ms-|0.262.3
vscode-typescript-next|ms-|5.0.20221116
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.22.0
LiveServer|rit|5.7.9
addDocComments|ste|0.0.8
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
volar|Vue|1.0.9
material-theme|zhu|3.15.6

(1 theme extensions excluded)

</details>

**Comment by Udaay** [comment]
![Screenshot 2022-11-17 at 4 53 55 PM](https://user-images.githubusercontent.com/26655564/202434476-c4d9b954-5de5-44a8-91ba-9cde5cea6456.png)
I tried restaring / reinstalling but no luck.
Screenshot for the refrence.

**Comment by SijanC147** [comment]
experiencing the same issue just now after installing the latest version of [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), namely `v5.0.20221116`. 

Reverting back to `v5.0.20221115` fixed it.

**Comment by Fapalz** [comment]
> experiencing the same issue just now after installing the latest version of [JavaScript and TypeScript Nightly](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next), namely `v5.0.20221116`.
> 
> Reverting back to `v5.0.20221115` fixed it.
> 
> edit: referring to their github repo's [issues](https://github.com/microsoft/vscode-typescript-next/issues), there seems to be a lot of talk about this, probably not a vscode issue.

Thanks

**Comment by filipac** [comment]
> Reverting back to `v5.0.20221115` fixed it.

@SijanC147 how do you revert?

**Comment by SwapnilSoni1999** [comment]
> > Reverting back to `v5.0.20221115` fixed it.
> 
> @SijanC147 how do you revert?

1. Goto extension
2. Beside uninstall button there's dropdown arrow
3. Choose "Install another version" 
4. choose the older version

**Comment by Udaay** [comment]
Thanks it's working
