### ISSUE TITLE
Strange wording on Command Center visibility menu

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166503]
Not sure what "Launch" means in this case. Looks unintentional to me?

<img width="744" alt="CleanShot 2022-11-16 at 11 48 47@2x" src="https://user-images.githubusercontent.com/25163139/202279738-15e09b35-fe74-45e2-af13-d3055990c322.png">

**Comment by jrieken** [comment]
verified but we also changed this again, see https://github.com/microsoft/vscode/issues/170621#issuecomment-1372467459
