### ISSUE TITLE
serverReadyAction not working when launch configuration is in devcontainer.json

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode#166569]
Does this issue occur when all extensions are disabled?: Dev Containers extension must be enabled to check the problem

- VS Code Version: 1.73.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. In **devcontainer.json** define a launch configuration like:
```json
{
  "customizations": {
    "vscode": {
        "launch": {
          "configurations": [
            {
              "name": "Launch Chrome Debugger",
              "type": "chrome",
              "request": "launch",
              "browserLaunchLocation": "workspace",
              "url": "http://web.local.computer:4200/",
              "webRoot": "${workspaceFolder}",
              "presentation": {
                "hidden": true
              }
            },
            {
              "name": "Debug nx-app",
              "type": "node-terminal",
              "request": "launch",
              "cwd": "${workspaceFolder}",
              "command": "nx run nx-app:serve:development",
              "serverReadyAction": {
                "action": "startDebugging",
                "name": "Launch Chrome Debugger",
                "pattern": "listening on 0.0.0.0:4200"
              }
            }
          ]
        },
    }
  }
}
```
2. Rebuild the Dev Container in order for the new configuration to take effect.
3. Go to **Run and Debug** and run **Debug nx-app**.
4. After the "listening on 0.0.0.0:4200" message appears in the terminal the error message `'launch.json' does not exist for passed workspace folder.` pops up.

If the same launch configuration is provided in a **launch.json** file (instead of **devcontainer.json**), the **Launch Chrome Debugger** is run after the "listening on 0.0.0.0:4200" message appears in the terminal and there is no error message.

Related to: https://github.com/microsoft/vscode/issues/76415

**Comment by roblourens** [comment]
I don't think I knew that this is possible, is this new @chrmarti? This probably isn't the only thing that won't work.

**Comment by rubensa** [comment]
I've been using this for some time (except the **serverReadyAction** part) so it is not that new.

**Comment by rubensa** [comment]
@roblourens the **info-needed** tag is for @chrmarti or you need extra info from me?

**Comment by roblourens** [comment]
I don't think the example is actually valid? I get `Property launch is not allowed.` and the launch config isn't recognized at all.

**Comment by rubensa** [comment]
@roblourens The example I included is not a full devcontainer.json so I missed the "settings" tag between "vscode" and "lauch".

```
{
  "customizations": {
    "vscode": {
      "settings": {
        "launch": {
          "configurations": [
            {
              "name": "Launch Chrome Debugger",
              "type": "chrome",
              "request": "launch",
              "browserLaunchLocation": "workspace",
              "url": "http://web.local.computer:4200/",
              "webRoot": "${workspaceFolder}",
              "presentation": {
                "hidden": true
              }
            },
            {
              "name": "Debug nx-app",
              "type": "node-terminal",
              "request": "launch",
              "cwd": "${workspaceFolder}",
              "command": "nx run nx-app:serve:development",
              "serverReadyAction": {
                "action": "startDebugging",
                "name": "Launch Chrome Debugger",
                "pattern": "listening on 0.0.0.0:4200"
              }
            }
          ]
        },
      }
    }
  }
}
```

Please, check it and reopen the issue.

**Comment by rubensa** [comment]
New issue created with sample **devcontainer.json** updated: https://github.com/microsoft/vscode/issues/169375
