### ISSUE TITLE
remote notebook keep loading

### ISSUE THREAD

**Issue by yangtzech** [microsoft/vscode#166584]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1 (system setup)
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. ssh to a remote server, with only remote ssh extension
2. open a '.ipynb' file
3. The first ipynb can be loaded, but second file will not succeed, and keep loading
4. If close the first ipynb, it then can not be open either

The blue line in the red box shows the loading bar.
![image](https://user-images.githubusercontent.com/41911522/202466813-f4b2f2af-075c-41ca-989e-3186f6e36b70.png)

Type: <b>Bug</b>

remote notebook keep loading

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-52-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (21.61GB free)|
|Process Argv|--crash-reporter-id 36c62e9f-79c6-4b93-b1dc-223cd9a6f362|
|Screen Reader|no|
|VM|67%|

|Item|Value|
|---|---|
|Remote|SSH: a|
|OS|Linux x64 5.15.0-52-generic|
|CPUs|Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz (12 x 3300)|
|Memory (System)|62.71GB (60.22GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-zh-hans|MS-|1.73.11020948
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.2
vscode-language-pack-zh-hans|MS-|1.73.11020948

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by roblourens** [comment]
It sounds like there is a particular notebook that won't open? Can you share it with me? 

And are you able to open that notebook in a local vscode window?

**Comment by yangtzech** [comment]
> It sounds like there is a particular notebook that won't open? Can you share it with me?

The notebook is not some particular one, but anyone. 

> And are you able to open that notebook in a local vscode window?

Yes, anyone is ok.

**Comment by roblourens** [comment]
If you create a new empty notebook, is it able to open in ssh?

Can you check for errors in the devtools (Help > Toggle Developer tools)

**Comment by yangtzech** [comment]
```
workbench.desktop.main.js:609 CRITI Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:609  INFO [attempt 1] Invoking resolveAuthority(ssh-remote)
workbench.desktop.main.js:609   ERR [Extension Host] (node:3408) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
workbench.desktop.main.js:87 [Extension Host] (node:3408) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Code --trace-deprecation ...` to show where the warning was created)
E @ workbench.desktop.main.js:87
workbench.desktop.main.js:609  INFO [attempt 1] resolveAuthority(ssh-remote) returned '127.0.0.1:60557' after 3201 ms
workbench.desktop.main.js:87 [Extension Host] rejected promise not handled within 1 second: Error: connect ECONNREFUSED 127.0.0.1:7890
E @ workbench.desktop.main.js:87
workbench.desktop.main.js:87 [Extension Host] stack trace: Error: connect ECONNREFUSED 127.0.0.1:7890
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
E @ workbench.desktop.main.js:87
workbench.desktop.main.js:609   ERR connect ECONNREFUSED 127.0.0.1:7890: Error: connect ECONNREFUSED 127.0.0.1:7890
	at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
workbench.desktop.main.js:609 CRITI Extension 'ms-toolsai.jupyter' wants API proposal 'notebookDebugOptions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:609 CRITI Extension 'tabnine.tabnine-vscode' wants API proposal 'inlineCompletions' but that proposal DOES NOT EXIST. Likely, the proposal has been finalized (check 'vscode.d.ts') or was abandoned.
workbench.desktop.main.js:2147 Overwriting grammar scope name to file mapping for scope text.tex.
Old grammar file: file:///d%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/TeX.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2Ba%E6%A1%83%E5%AE%8F%E4%B9%8B%E5%89%8D%E7%94%B5%E8%84%91_by_%E8%8A%B1%E7%94%9F%E5%A3%B3/home/a/.vscode-server/extensions/james-yu.latex-workshop-9.0.1/syntax/TeX.tmLanguage.json
register @ workbench.desktop.main.js:2147
workbench.desktop.main.js:2147 Overwriting grammar scope name to file mapping for scope text.tex.latex.
Old grammar file: file:///d%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/LaTeX.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2Ba%E6%A1%83%E5%AE%8F%E4%B9%8B%E5%89%8D%E7%94%B5%E8%84%91_by_%E8%8A%B1%E7%94%9F%E5%A3%B3/home/a/.vscode-server/extensions/james-yu.latex-workshop-9.0.1/syntax/LaTeX.tmLanguage.json
register @ workbench.desktop.main.js:2147
workbench.desktop.main.js:2147 Overwriting grammar scope name to file mapping for scope text.bibtex.
Old grammar file: file:///d%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/Bibtex.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2Ba%E6%A1%83%E5%AE%8F%E4%B9%8B%E5%89%8D%E7%94%B5%E8%84%91_by_%E8%8A%B1%E7%94%9F%E5%A3%B3/home/a/.vscode-server/extensions/james-yu.latex-workshop-9.0.1/syntax/Bibtex.tmLanguage.json
register @ workbench.desktop.main.js:2147
workbench.desktop.main.js:2147 Overwriting grammar scope name to file mapping for scope text.tex.markdown_latex_combined.
Old grammar file: file:///d%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/markdown-latex-combined.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2Ba%E6%A1%83%E5%AE%8F%E4%B9%8B%E5%89%8D%E7%94%B5%E8%84%91_by_%E8%8A%B1%E7%94%9F%E5%A3%B3/home/a/.vscode-server/extensions/james-yu.latex-workshop-9.0.1/syntax/markdown-latex-combined.tmLanguage.json
register @ workbench.desktop.main.js:2147
workbench.desktop.main.js:2147 Overwriting grammar scope name to file mapping for scope source.cpp.embedded.latex.
Old grammar file: file:///d%3A/Program%20Files/Microsoft%20VS%20Code/resources/app/extensions/latex/syntaxes/cpp-grammar-bailout.tmLanguage.json.
New grammar file: vscode-remote://ssh-remote%2Ba%E6%A1%83%E5%AE%8F%E4%B9%8B%E5%89%8D%E7%94%B5%E8%84%91_by_%E8%8A%B1%E7%94%9F%E5%A3%B3/home/a/.vscode-server/extensions/james-yu.latex-workshop-9.0.1/syntax/cpp-grammar-bailout.tmLanguage.json
register @ workbench.desktop.main.js:2147
workbench.desktop.main.js:609  INFO [perf] Render performance baseline is 115ms
workbench.desktop.main.js:87 [Extension Host] capabilities resolved immediately
workbench.desktop.main.js:87 [Extension Host] Error: ENOENT: no such file or directory, scandir '/home/a/AppData/Roaming/Code/Service Worker/CacheStorage'
	at Object.readdirSync (node:fs:1392:3)
	at an.l (/home/a/.vscode-server/extensions/cweijan.vscode-office-2.9.0/out/extension.js:298:10508)
	at an.each (/home/a/.vscode-server/extensions/cweijan.vscode-office-2.9.0/out/extension.js:298:11002)
	at an.clear (/home/a/.vscode-server/extensions/cweijan.vscode-office-2.9.0/out/extension.js:298:11030)
	at Wc (/home/a/.vscode-server/extensions/cweijan.vscode-office-2.9.0/out/extension.js:298:11293)
	at Bb (/home/a/.vscode-server/extensions/cweijan.vscode-office-2.9.0/out/extension.js:303:39189)
	at Function._callActivateOptional (/home/a/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:104:17678)
	at Function._callActivate (/home/a/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:104:17338)
	at /home/a/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:104:15133
	at async w._activate (/home/a/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:8304)
	at async w._waitForDepsThenActivate (/home/a/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:8246)
	at async w._initialize (/home/a/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/out/vs/workbench/api/node/extensionHostProcess.js:90:7610)
workbench.desktop.main.js:87 [Extension Host] ms-toolsai.jupyter extension is using deprecated python APIs which will be removed soon.
E @ workbench.desktop.main.js:87
workbench.desktop.main.js:609   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
workbench.desktop.main.js:609   ERR read ECONNRESET: Error: read ECONNRESET
	at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
workbench.desktop.main.js:609   ERR Error: Unavailable due to network problems
	at y.convertToSession (d:\Program Files\Microsoft VS Code\resources\app\extensions\microsoft-authentication\dist\extension.js:1:647681)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
workbench.desktop.main.js:609  WARN Settings Sync: Accounts are not initialized
workbench.desktop.main.js:609   ERR Client network socket disconnected before secure TLS connection was established: Error: Client network socket disconnected before secure TLS connection was established
	at connResetException (node:internal/errors:691:14)
	at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)
	at TLSSocket.emit (node:events:538:35)
	at endReadableNT (node:internal/streams/readable:1345:12)
	at processTicksAndRejections (node:internal/process/task_queues:83:21)
DevTools failed to load source map: Could not load content for https://ticino.blob.core.windows.net/sourcemaps/6261075646f055b99068d3688932416f2346dd3b/core/vs/workbench/workbench.desktop.main.js.map: Load canceled due to load timeout

```


Above is what I got from `Toggle Developer Tools > Console > Sava as` shown below:

![image](https://user-images.githubusercontent.com/41911522/203215979-02b1277e-7d80-4c01-8228-19d97748a97a.png)

And I did this on a new computer. Below is the new system info.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19041
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.0-53-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (9.86GB free)|
|Process Argv|--crash-reporter-id cc4846eb-f126-46b2-a45c-c9a3d87060e5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: a|
|OS|Linux x64 5.15.0-53-generic|
|CPUs|Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz (12 x 2284)|
|Memory (System)|62.71GB (34.88GB free)|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-jetbrains-icon-theme|cha|1.0.14
vscode-language-pack-zh-hans|MS-|1.73.11020948
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.2
vscode-opennewinstance|chr|0.0.12
vscode-office|cwe|2.9.0
gitlens|eam|13.1.1
path-autocomplete|ion|1.22.1
latex-workshop|Jam|9.0.1
vscode-language-pack-zh-hans|MS-|1.73.11020948
isort|ms-|2022.8.0
python|ms-|2022.16.1
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
resourcemonitor|mut|1.0.7
tabnine-vscode|Tab|3.6.23
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by zhuhr213** [comment]
Hello collegue, no, I can't open neither a new empty notebook nor an old one in ssh. I have to open a notebook locally anyway so that the ssh notebook can be displayed.&nbsp;
I screenshot the errors for your easy reference.&nbsp;









Devola
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "microsoft/vscode"                                                                                    ***@***.***&gt;;
Date:&nbsp;Tue, Nov 22, 2022 01:57 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [microsoft/vscode] remote notebook keep loading (Issue #166584)





 
If you create a new empty notebook, is it able to open in ssh?
 
Can you check for errors in the devtools (Help &gt; Toggle Developer tools)

**Comment by yulong-me** [comment]
Same issue. Looking for solutions

**Comment by DuTim** [comment]
> 

same question , need to open a location jupyter window ,the ssh also to show content.

**Comment by DuTim** [comment]
same issue. must to open a local jupyter window ,the remote window jupyter also to normal open.

**Comment by roblourens** [comment]
I'll merge this issue into https://github.com/microsoft/vscode/issues/166860
