### ISSUE TITLE
No input in terminal

### ISSUE THREAD

**Issue by spamfro** [microsoft/vscode#166521]
- VSCode Version: 1.74.0-insider
- Local OS Version: iPadOS 15.6.1 (on iPad Pro 7th gen)
- Remote OS Version: Linux 5.14.0-1054-oem 61-Ubuntu x86_64 (running in Ubuntu container in Docker version 20.10.12, build 20.10.12-0ubuntu2~20.04.1 on Ubuntu host)
- Remote Extension/Connection Type: Server
- Logs:

Steps to Reproduce:

1. Run a fresh Ubuntu container, update, and install `wget` and `curl`
In the container:
```
docker container run --rm -it --name vscode-server ubuntu /bin/bash
```
In the container:
```
apt update
apt upgrade
apt install wget curl
```
2. In the container install `vscode-server` following the steps from the [website](https://code.visualstudio.com/docs/remote/vscode-server)
```
wget -O- https://aka.ms/install-vscode-server/setup.sh | sh
code-server
```
3. In the iPad Safari browser, authenticate and open the suggested link with the unique machine name. Accept any thrust when prompted. The server will be started. The UI is loaded and the file tree is shown in the explorer UI.
```
https://insiders.vscode.dev/+ms-vscode.remote-server/whatever-machine/
```
4. (Everything up until now works as one expects it should). From the Menu (..the sandwich icon) select `Terminal/ New terminal`.  A new terminal is opened and the prompt is shown, BUT no cursor is visible, and no keyboard input is accepted.

Does this issue occur when you try this locally?: 
Terminal is accessible as expected when the same tunnel is opened in the client loaded in Safari on macOS Ventura 13.0 on MacBook Air.
 
Does this issue occur when you try this locally and all extensions are disabled?: 
The issue is observed in a fresh install, no additional extensions installed yet.

**Comment by Tyriar** [comment]
Might be the same as https://github.com/microsoft/vscode/issues/163448
