### ISSUE TITLE
Diff editor: add tooltip to revert-change arrow?

### ISSUE THREAD

**Issue by hughlilly** [microsoft/vscode#166527]
In the Diff editor, when hovering over a right arrow pointed at a changed line, there is nothing to indicate that clicking the arrow will revert the change. I would say one should be added. (Is this usually done through the element’s `title` attribute?)

Seems like such an addition might need to be made here:
https://github.com/microsoft/vscode/blob/0182a4bf399cdacce7c112cbe499167eac759b41/src/vs/editor/browser/widget/diffEditorWidget.ts#L610-L627

**Comment by hediet** [comment]
They have a tooltip now:

![Image](https://github.com/microsoft/vscode/assets/2931520/3aebb344-bb5c-42a7-8007-c954784f3248)
