### ISSUE TITLE
typescript language service crashed 5 times in the last 5 minutes

### ISSUE THREAD

**Issue by twig-atl** [microsoft/vscode#166538]
Type: <b>Bug</b>

I'm just opening typescript files in a big project and it'll get stuck on a "Initialising JS/TS language features" loop

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.68GB (12.10GB free)|
|Process Argv|--crash-reporter-id 2ef54b4d-21d5-4097-b785-1ec0118888d7|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2687)|
|Memory (System)|24.79GB (21.91GB free)|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
auto-rename-tag|for|0.1.10
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.2
vscode-eslint|dba|2.2.6
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
vsliveshare|ms-|1.0.5762

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
3d0df643:30608728
dbltrim-noruby:30604474

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by twig-atl** [comment]
Uhh, unsure if I can do proper testing on that.

My work is set up entirely within WSL2 so vscode isn't very useful to me without extensions.

**Comment by mjbvz** [comment]
Yes you should keep that one enabled for testing. If you can test it though, do you see this issue if you open the project outside of wsl?

**Comment by twig-atl** [comment]
> do you see this issue if you open the project outside of wsl?

Personally no, but that is on an entirely different setup/machine and much smaller projects.

I haven't tried the insider build yet, but [this stackoverflow solution](https://stackoverflow.com/a/64116907/13754062) about deleting `./vscode-server` seems to have resolved it for me (hasn't crashed today so far)

**Comment by mjbvz** [comment]
Closing as it sounds like this is no longer reproducible

**Comment by twig-atl** [comment]
Deleting `./vscode-server` didn't resolve the issue, but I think I found another cause for it.

Our codebase works against TS 4.5.5 while VSCode is 4.8.4. For some reason, it reverted to using vscode's version instead of the version defined in our workspace.

![image](https://user-images.githubusercontent.com/61523379/204703391-f3959d38-a2a6-4f04-a1f7-4b1b782f2684.png)

Hope this helps out anyone that stumbles upon this issue.
