### ISSUE TITLE
vscode lose many colors for .js, .vue files

### ISSUE THREAD

**Issue by prd-quy-nguyen** [microsoft/vscode#166535]
Type: <b>Bug</b>

All of sudden, many colors of code in .js and .vue files are lost. I changed no extensions, and also it is updated to lastest. My code run just fine, no error or bug

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.15.0-53-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 4800)|
|GPU Status|2d_canvas: disabled_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|31.17GB (13.36GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 39fc1cc1-d271-4140-b531-489fee8415e6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.0.4
prettier-vscode|esb|9.9.0
vscode-docker|ms-|1.22.2
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
vscode-typescript-next|ms-|5.0.20221116
volar|Vue|1.0.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
3d0df643:30608728
dbltrim-noruby:30604474

```

</details>

**Comment by prd-quy-nguyen** [comment]
![Screenshot from 2022-11-17 11-09-14](https://user-images.githubusercontent.com/110364472/202353086-4c5fa999-ffef-4014-b9b6-5bc3db25c4c1.png)

**Comment by vtdkhoa** [comment]
Same issue
![image](https://user-images.githubusercontent.com/28914274/202358262-7fa0f41c-d6f1-4e7c-a2b5-39f6b8caa88e.png)

**Comment by vtdkhoa** [comment]
Same issue
![image](https://user-images.githubusercontent.com/28914274/202358636-d66e5909-6f13-4ee5-9501-45a650942bcd.png)

**Comment by prd-quy-nguyen** [comment]
https://github.com/microsoft/vscode/issues/166525
