### ISSUE TITLE
debug launch button looks out of place

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16657]
The custom launch button for debug seems out of place and alien. I don't understand why we have it and it why we use the html-dropdown in other places, like output?. Also its very confusion that in this UI element we launch on select and that only the tiny up/down handle also to select a different launch config.

![screen shot 2016-12-06 at 15 01 31](https://cloud.githubusercontent.com/assets/1794099/20928219/0f2dcae4-bbc5-11e6-8da4-9f51f2227a15.png)

![screen shot 2016-12-06 at 15 01 34](https://cloud.githubusercontent.com/assets/1794099/20928221/12319bda-bbc5-11e6-8f00-54b9b74acb32.png)

**Comment by jrieken** [comment]
@Microsoft/vscode for feedback/ideas?

**Comment by joaomoreno** [comment]
@isidorn Ben's suggestion would help fixing this: you should experiment with using the Play icon as the button in itself and have the text and arrows be the dropdown, while keeping a similar style.

**Comment by isidorn** [comment]
The motivation for changing this was to differentiate between the process dropdown which appears when debugging multiple sessions.
Agree that we could change the semantics that clicking on the green button starts the debug while the rest changes the current configuration.

Also the new action should not be alien to debug users as VS uses a very similar widget.

**Comment by roblourens** [comment]
Yes please, I keep trying to change the config by clicking the text, or just mis-clicking because the dropdown button is so small.

**Comment by isidorn** [comment]
Proposal by @weinand which is quite simple and has my liking -> simply hide the name of the launch config.
We would show the selected name on hover and it is shown in the native dropdown.

So this would be option1. option2 would be Ben's suggestion which Joao mentioned 3 comments above. Feedback welcome

![screen shot 2016-12-07 at 10 25 36](https://cloud.githubusercontent.com/assets/1926584/20962014/d77d1dd6-bc67-11e6-8e8e-3545565a1510.png)

**Comment by weinand** [comment]
And the interactive behaviour would work like this:
- selecting an item from the dropdown launches it immediately (and sets it as the 'current item')
- just pressing the Play button launches the 'current item'.
- initially play would be disabled because no 'current item' is set

**Comment by jrieken** [comment]
> just pressing the Play button launches the 'current item'.

And how do I know what the current item is?

**Comment by weinand** [comment]
The drop down menu has a checkmark (like already today).

BTW, my proposal is basically the Eclipse behaviour.

**Comment by weinand** [comment]
Some benefits:
- launching a different target becomes a one click process. Today you first have to select a different target from the drop down, and then you have to press the Play button (I frequently forget to press Play).
- In case of multiple targets the configuration that was launched last does no longer show up in the UI. This is less confusing for the user because what is the purpose of showing the configuration of what was launched last?

**Comment by chrisdias** [comment]
👍 on starting the debug session when you pick an item from the dropdown.
👎 on not showing the selected configuration, I really want to know what I'm about to run when I press F5, otherwise i have to pick up the mouse and hover before debugging.

So i'm in favor of Joao/Ben's suggestion, "option 2".

**Comment by isidorn** [comment]
More people seem to be in favor of option 2 let's start with that. Also it is richer experience so if we get it right I believe it can be a better.

As for launching on choosing an entry I think that makes sense for both options so we can treat that as unrelated to this discussion.
