### ISSUE TITLE
Not able see outputchannel i created in developer: SetlogLevel section and not able to import LogOutputChannel from vscode module

### ISSUE THREAD

**Issue by ThejasJainMJ** [microsoft/vscode#166578]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Created the channel using createOutputCHannel.
2. Outputchannel able top see in output console, but not able to see in Developer: Setloglevel section to set log level.
3. ANd other issue is not able to import logout channel
4. Can u please guide me how can i do that

**Comment by ThejasJainMJ** [comment]
Here able to see outputchannel(Accurev)
![image](https://user-images.githubusercontent.com/118447300/202469502-ea6aa6a8-4847-4b6d-914e-d17b8cb61f49.png)

Below section where we set log level for output channels . Not able to see the outputchannel(Accurev)
![image](https://user-images.githubusercontent.com/118447300/202469825-d1775caa-dd50-48d0-ae0d-5c9c947ee908.png)

**Comment by gjsjohnmurray** [comment]
In 1.73 (current stable) this API is still proposed. In Insiders it finalized recently (see https://github.com/microsoft/vscode/pull/165925). Which are you using?

**Comment by ThejasJainMJ** [comment]
I am using outputchannel api
![image](https://user-images.githubusercontent.com/118447300/202615647-88edfb62-72e1-4cac-aabd-b537c68b1a5f.png)

How can i set log level for the channel created using this api.

**Comment by gjsjohnmurray** [comment]
If you are developing using 1.73 you need to take additional steps to permit your extension to use the proposed API. See https://code.visualstudio.com/updates/v1_73#_proposed-apis
If you are using Insiders and are willing to set 1.74 as the minimum version required by your extension then you don't need to do that.

**Comment by sandy081** [comment]
@gjsjohnmurray Thanks for sharing the info.

@ThejasJainMJ Please follow the steps/info shared by @gjsjohnmurray and try the API. You have to create the output channel by passing `{log: true}` option.
