### ISSUE TITLE
Stale errors/warnings in launch.json

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16656]
I had an old version of `launch.json` in my workspace. First I empty all of it, then I deleted the file, and pressed the gear icon to get a new version. Until I made an editor I saw stale errors/warnings

![screen shot 2016-12-06 at 14 59 18](https://cloud.githubusercontent.com/assets/1794099/20928154/bd96fb38-bbc4-11e6-9070-e92b48c9e934.png)

**Comment by isidorn** [comment]
This errors are coming from the json world. @aeschli do I need to somehow specify to you that the content of launch.json changed completely. I would expect you listen on file events

**Comment by aeschli** [comment]
I get change events from the language server that gets it from the extension host.

To understand what and where it happend we need steps to reproduce. @jrieken ...
A good way to see if the JSON language server got any notification and did validation is setting
`"json.trace.server": "verbose"` and observe the HTML Language Server output view.

**Comment by aeschli** [comment]
I'm not able to reproduce
```
{
    // Use IntelliSense to learn about possible Node.js debug attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceRoot}/app.js",
            "cwd": "${workspaceRoot}",
            "outDir": "{workspaceRoot}/bin"
        }
    ]
}
```
I tried:
- clear the content, delete & recreate: Already when deleting I see that the error is gone from the status bar
- delete & recreate : Error is gone from the status bar

@jrieken Please reopen if you can reproduce that in you set-up.
