### ISSUE TITLE
[html] script end tag is not correctly indented

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16650]
Testing #16526

```html
<!doctype html>
<html>

<head>
	<script>
		const x = 'hello';
</script>
</head>

<body>
	<div style="position: absolute;"></div>
<div style="position: absolute;"></div>
</body>

</html>
```

![image](https://cloud.githubusercontent.com/assets/22350/20927615/aed9defa-bbc2-11e6-8386-0f7120ed2139.png)

Lines 7 and 12 should be indented. Lines 3 9 and 14 are empty lines the formatter creates.

**Comment by aeschli** [comment]
> Lines 3 9 and 14 are empty lines the formatter creates.
This controlled by the setting `"html.format.extraLiners"` which has default `"head, body, /html"`

**Comment by joaomoreno** [comment]
I'd like to point out to lines 7 and 12 too. They are outdented, when they should not be. :(

**Comment by aeschli** [comment]
Oh, sorry, I didn't intend to close it.

**Comment by rebornix** [comment]
@aeschli it seems line 7 not is correct as the commit fixed indentation of script end tag. But line 12 is still not correctly indented.

**Comment by aeschli** [comment]
I took this bug for the indent issue of the closing script tag. Please file a separate issue for line 12.
