### ISSUE TITLE
buttons duplicates

### ISSUE THREAD

**Issue by DanieleMar** [microsoft/vscode#166556]
Type: <b>Bug</b>

there are double buttons
![bug doppio vscode 1](https://user-images.githubusercontent.com/13423042/202390556-98a3194d-bbac-4fa8-9c36-ff154dbe3b55.png)

contextual menu of git source control
![bug doppio vscode 2](https://user-images.githubusercontent.com/13423042/202391232-368fcd14-6adc-4d42-ae58-6f9b3c62789e.png)

VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:44:09.336Z)
OS version: Linux x64 5.15.0-53-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 3400)|
|GPU Status|2d_canvas: disabled_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: disabled_off<br>webgl2: disabled_off<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|15.39GB (8.14GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id d0fc8761-37ca-440a-ab40-7c827f22edb6|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
clipboard-history|Anj|1.0.7
npm-intellisense|chr|1.4.2
path-intellisense|chr|2.8.1
gitignore|cod|0.9.0
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.6
snippet|dev|1.0.3
git-extension-pack|don|0.1.3
githistory|don|0.6.19
gitlens|eam|13.0.4
gitlens-insiders|eam|2022.11.1604
vscode-html-css|ecm|1.13.1
vscode-element-helper|Ele|0.5.6
json-tools|eri|1.0.2
prettier-vscode|esb|9.9.0
git-project-manager|fel|1.8.2
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
copilot|Git|1.59.7338
gitlab-workflow|Git|3.43.1
unicode-substitutions|Gle|2.3.4
todo-tree|Gru|0.0.220
githd|hui|2.3.3
output-colorizer|IBM|0.1.2
path-autocomplete|ion|1.22.1
search-editor-apply-changes|jak|0.1.1
gitlab-mr|jas|1.4.3
cmake-language-support-vscode|jos|0.0.7
google-search|kam|0.0.1
vscode-search-everywhere|kby|2.0.3
compare-helper|kee|1.1.0
wrapSelection|kon|0.10.0
vscode-dashboard|kru|2.5.2
i18n-ally|lok|2.8.1
prettify-json|moh|0.0.3
vscode-language-pack-it|MS-|1.73.11090913
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.3
live-server|ms-|0.4.3
vsliveshare|ms-|1.0.5762
env-cmd-file-syntax|Nix|0.3.0
vetur|oct|0.36.1
indent-rainbow|ode|8.3.1
vue-navigator|Pid|0.1.3
text-power-tools|qcz|1.38.0
LiveServer|rit|5.7.9
gi|rub|0.2.11
partial-diff|ryu|1.4.3
vue-vscode-extensionpack|sdr|0.2.0
swdc-vscode|sof|2.6.35
vscode-smoothtype|spi|1.2.0
autoimport|ste|1.5.4
code-spell-checker|str|2.11.0
code-spell-checker-italian|str|1.0.0
tabnine-vscode|Tab|3.6.20
vue-docs|tit|1.0.2
cmake|twx|0.0.17
errorlens|use|3.6.0
vscode-lldb|vad|1.8.1
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-icons|vsc|12.0.1
volar|Vue|1.0.9
gitblame|wad|9.0.1
vscode-import-cost|wix|3.3.0
JavaScriptSnippets|xab|1.8.0
vscode-surround|yat|1.5.0
markdown-all-in-one|yzh|3.4.3
vscode-open-in-github|ziy|1.3.6
vue|znc|0.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate this.

**Comment by DanieleMar** [comment]
found. https://github.com/gitkraken/vscode-gitlens/issues/2351
