### ISSUE TITLE
Use regular button widths for walkthroughs?

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166663]
Ref #165846

I sometimes wonder if the 100% width buttons aren't all that obvious as buttons. FWIW, I'm thinking about the same for buttons in Views (e.g. `Open Folder`).

What if we did this for walkthroughs? Thoughts @bhavyaus @digitarald?

![CleanShot 2022-11-17 at 16 47 11](https://user-images.githubusercontent.com/25163139/202590901-f6c466c8-a78b-4705-a351-e060baf2c486.gif)

**Comment by bhavyaus** [comment]
For consistency across the steps and usability (larger touch target), I prefer the buttons the way they are.

If your concern is that the button doesn't appear much like a button, perhaps we can change up the shape/other properties to make its clickable affordance more prominent?
We should also consider setting guidelines around the length of the text in those buttons.

**Comment by digitarald** [comment]
No strong feelings on this one. Smaller button do make it look a bit more approachable and less heavy.

As @bhavyaus said, the Welcome view in the sidebar also use full-width buttons (with a max width).

**Comment by daviddossett** [comment]
FWIW I actually think the 100% width buttons are not intentional in this case. From the actual designs:

<img width="743" alt="CleanShot 2022-11-18 at 12 00 06@2x" src="https://user-images.githubusercontent.com/25163139/202792265-d851fe34-31d5-441f-8e23-142c97ccc030.png">

The sidebar feels like a special case to me—we don't show the behavior anywhere else AFAIK.

**Comment by bhavyaus** [comment]
> FWIW I actually think the 100% width buttons are not intentional in this case. From the actual designs:
> 
> <img alt="CleanShot 2022-11-18 at 12 00 06@2x" width="743" src="https://user-images.githubusercontent.com/25163139/202792265-d851fe34-31d5-441f-8e23-142c97ccc030.png">
> 
> The sidebar feels like a special case to me—we don't show the behavior anywhere else AFAIK.

I'm ok either way. Are you also recommending that we bring the Next button back?

**Comment by daviddossett** [comment]
> Are you also recommending that we bring the Next button back?

Not necessarily. I think that was from an earlier proposal to make it more obvious for users that they can proceed to the next step. @digitarald may know why it ultimately didn't make it in?

**Comment by digitarald** [comment]
> may know why it ultimately didn't make it in?

Space was one consideration and in the beginning Next also checked items off which didn't seem right.

If we drop the todo-aspects (the circle/checkbox in the top-left), bringing back Next makes more sense. It also helps to have steps that don't have actions but are informational.

**Comment by bhavyaus** [comment]
> > may know why it ultimately didn't make it in?
> 
> Space was one consideration and in the beginning Next also checked items off which didn't seem right.
> 
> If we drop the todo-aspects (the circle/checkbox in the top-left), bringing back Next makes more sense. It also helps to have steps that don't have actions but are informational.

I have an issue open for that. https://github.com/microsoft/vscode/issues/166038.  Added a comment to consider adding a _Next_ button there.

**Comment by daviddossett** [comment]
👍 for adding an explicit 'Next' action if the steps are marked done once viewed.
