### ISSUE TITLE
Theme Items should be sorted in “Workbench: Color Theme”

### ISSUE THREAD

**Issue by augustsaintfreytag** [microsoft/vscode#166695]
Type: <b>Bug</b>

Opening “Settings” in GUI mode (as opposed to JSON mode) lets you select themes, the current theme, the preferred dark color theme and the preferred light color theme. The items in these pop-up menus can get quite long (50+ items) depending on what themes or theme packs were installed.

The items in these menus are not sorted alphabetically or by any useful sorting strategy. The only apparent order is that themes from the same extension are grouped. If themes are ordered by the name of the pack they belong to, this is not apparent and arguably not as useful as simply sorting all themes by their individual name.

With this, themes have to be picked entirely by going through the menu items by eye every time. In contrast, the command palette item “Preferences: Color Theme” and its pop-up menu *is* sorted alphabetically.

![Screenshot 2022-11-18 at 11 12 31@2x](https://user-images.githubusercontent.com/7656669/202677679-65cc2b4e-f945-4d0a-8294-c956dadd04ce.jpg)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz (16 x 3500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|17, 12, 8|
|Memory (System)|64.00GB (1.70GB free)|
|Process Argv|--crash-reporter-id ffd1ba93-6840-4386-8b8b-3b01b4a2290e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
formatallfilesinworkspace|ale|0.0.1
vscode-apollo|apo|1.19.11
vscode-zipfs|arc|3.0.0
beardedicons|Bea|1.2.0
markdown-mermaid|bie|1.15.2
path-intellisense|chr|2.8.1
compulim-vscode-closetag|Com|1.2.0
vscode-eslint|dba|2.2.6
arrow-function-snippets|dei|3.1.0
xml|Dot|2.5.1
vsc-material-theme-icons|equ|2.4.0
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
copilot|Git|1.59.7338
vscode-nginx-conf-hint|han|0.3.0
vscode-codemetrics|kis|1.24.0
graphql-for-vscode|kum|1.15.3
restructuredtext|lex|189.2.0
gitless|maa|11.7.2
fountain|mas|1.0.0
Kotlin|mat|1.7.1
dotenv|mik|1.0.1
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
vsliveshare|ms-|1.0.5776
rose-pine|mvl|2.4.1
vetur|oct|0.36.1
prisma|Pri|4.6.1
vscode-sort-json|ric|1.20.0
mdx|sil|0.1.1
ignore-gitignore|stu|1.0.1
notification-tester|svi|2.5.1
sass-indented|syl|1.8.22
vscode-asl|Tho|1.0.0
shellcheck|tim|0.28.2
ulss|Uly|1.0.1
vscode-swift-development-environment|vkn|2.12.3
windows-nt-vscode-theme|was|0.0.11
markdown-all-in-one|yzh|3.4.3

(22 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes516:30244333
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by rzhao271** [comment]
Hi, how does the following sort order look?

![The color theme settings, sorted by enum item label](https://user-images.githubusercontent.com/7199958/203140649-44c871a2-4388-446d-85e9-df816cfdbf23.png)
