### ISSUE TITLE
Cannot Focus terminal Tabs View using command

### ISSUE THREAD

**Issue by pakapor** [microsoft/vscode#166601]
Type: <b>Bug</b>

The command just doesn't work.
Using key combination ctrl+shift+\ doesn't work
Using command doesn't work (ctrl+shift+p >Focus Terminal Tabs View)

VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:15:18.074Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Darwin arm64 21.1.0
Remote OS version: Darwin arm64 21.1.0
Remote OS version: Linux x64 4.15.0-191-generic
Remote OS version: Darwin x64 20.5.0
Remote OS version: Linux x64 4.15.0-191-generic

<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
pine-script-syntax-highlighter|ex-|1.0.5
vsc-python-indent|Kev|1.18.0
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
remote-explorer|ms-|0.0.2
errorlens|use|3.6.0
jinja|who|0.0.8

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30608728
dbltrim-noruby:30604474
89544117:30607850

```

</details>

**Comment by meganrogge** [comment]
this is working for me. I'd suggest using the `keyboard shortcuts troubleshooting` command
