### ISSUE TITLE
tsserverlibrary.js incorrectly included in app

### ISSUE THREAD

**Issue by mjbvz** [microsoft/vscode#166652]
This was added by d0d28a629568749c12eb995e9658abf690ecf795 which tried excluding it using a `.vscodeignore`. Looks like that doesn't work though :/

**Comment by mjbvz** [comment]
Reopening since this is still being included

**Comment by eleanorjboyd** [comment]
To my understanding this fix just makes sure that the file `tsserverlibrary.js` is not shipped in the node modules folder? If so I was unable to find it and therefore can verify it is fixed

**Comment by mjbvz** [comment]
thanks for testing @eleanorjboyd Yes that's correct, with the fix you should no longer see that file in `node_modules`
