### ISSUE TITLE
[Folding] Folding action not working in Typescript with return type on separate line

### ISSUE THREAD

**Issue by user72356** [microsoft/vscode#166666]
The folding action is not triggered for Typescript functions with a return type that is on a separate line. Example:

```typescript
function test()
    : string
{
    return "";
}
```

But this works:

```typescript
function test(): string
{
    return "";
}
```

**Comment by aeschli** [comment]
The folding region is there, It starts with the line of the return type.

![image](https://user-images.githubusercontent.com/6461412/202711182-c131f224-2662-4300-8a44-18b40b75f837.png)

I would not change this. @mjbvz to decide.

**Comment by user72356** [comment]
> The folding region is there, It starts with the line of the return type.
> 
> ![image](https://user-images.githubusercontent.com/6461412/202711182-c131f224-2662-4300-8a44-18b40b75f837.png)
> 
> I would not change this. @mjbvz to decide.

Sorry for the confusion, folding manually works (via icon) but not the fold action (via action or shortcut).

**Comment by aeschli** [comment]
@user72356 When the cursor is on line 2, the fold command works for me (`Ctrl + Shift + [`).
Can you add some more details, what's not working for you?

**Comment by mjbvz** [comment]
I think the current folding range makes sense. We can revisit if there's ever significant user feedback about wanting the other behavior
