### ISSUE TITLE
debug control screen cheese 

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16664]
* use attached launch config
* start both apps
* set a breakpoint in `app.js`
* select a callstack
* 🐛 the floating UI went south

![screen shot 2016-12-06 at 15 08 58](https://cloud.githubusercontent.com/assets/1794099/20928405/fab4eaba-bbc5-11e6-8331-c6d5a8dc2efd.png)

![screen shot 2016-12-06 at 15 08 48](https://cloud.githubusercontent.com/assets/1794099/20928409/ff1cb0f6-bbc5-11e6-87e6-ba5b573c8f4d.png)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/16596
