### ISSUE TITLE
Unknown property : 'composes'

### ISSUE THREAD

**Issue by mehdigrn-code** [microsoft/vscode#166630]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.73.1
- OS Version: Windows 10

Steps to Reproduce:

Warning of Unknown property: 'composes' while using CSS modules in React JS. composes is a valid property for combining CSS classes.
![Screenshot (32)](https://user-images.githubusercontent.com/104728807/202540932-a1b25f8b-283f-41a7-b6d1-d397a7fc6206.png)

**Comment by aeschli** [comment]
`composes` is not part of the CSS spec but from of https://github.com/css-modules/css-module.
The CSS language server follows the CSS spec. You can configure the validator to accept additional properties with the setting `css.lint.validProperties`
