### ISSUE TITLE
Simplify multiple devcontainer creation process. Allow multiple devcontainer.json ,we should be able to select any json and create dev container.

### ISSUE THREAD

**Issue by SamPosh** [microsoft/vscode#166681]
Currently it allows a single devcontainer.json file per .devcontainer folder. 
This will give limitation of creating one devcontainer. Multiple devcontainer 

Instead in .devcontainer folder allow to have multiple devcontainer.json file. Also provide the menu option by right clicking json files we should be able to create devcontainer. 

For example , consider below as the folder structure

```
.devcontainer
    devcontainer.json   
    devcontainer_2.json   (it will have different dockerfile)
    devcontainer_3.json  (it will have another different dockerfile)
    devcontainer_n.json  (it will have another different dockerfile)
```

devcontainer.json ->  This is default one which will be used to created dev container when we click 'Reopen in container' menu.
devcontainer_2/3/n ->  If we right click, there should be a menu showing option 'Create devcontainer'. If I click it then devcontainer enviornment should be prepared using this file. In this file I would point to different dockerfile which contains my proxy settings and extra packages and softwares required for testing. 

So multiple container creation process would be simple.

**Comment by julien-boudry** [comment]
It should be much more coherent with Github Codespace. And also cleaner than one repository for each at the root level.

**Github Codespace recommends the following structure:**
_(or one per subfolder, but default container must directly under `.devcontainer`)_

![image](https://user-images.githubusercontent.com/4020317/204326657-30f5b4f7-352e-40be-ad55-1cb5adc98bd7.png)

**Then, Github Interface allows choosing a container:**

![image](https://user-images.githubusercontent.com/4020317/204326758-86de0c0d-11f3-4387-8d4e-0237142613b6.png)
Or in VS Code:
![image](https://user-images.githubusercontent.com/4020317/204328297-01332e10-cdb8-4f61-97ec-4264eac9e42b.png)

But it's impossible with Visual Studio Dev Container, only the default container is allowed.

**Comment by chrmarti** [comment]
Tracked as https://github.com/microsoft/vscode-remote-release/issues/7548. Thanks.
