### ISSUE TITLE
Runaway search processes should be killed when pressing Escape

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16665]
Testing #16416

I was trying to see if there's any handling for regexes that lead to catastrophic backtracking. Catastrophic backtracking in regexes is a quite fun topic. Read more at http://www.regular-expressions.info/catastrophic.html

* open the vscode repo
* search for ^(.*?,){11}P
* observe 100% CPU on all cores ;)
* press Escape
> observe 100% CPU on all cores does not stop

**Comment by roblourens** [comment]
The same thing happens in stable, just with one process running away instead of several. I can't kill the processes because they need to clean up their open file descriptors. They must be stuck on a single 8k chunk because they would notice that they're canceled as soon as they go back to fs.read. So I'm not sure how to fix this.

**Comment by roblourens** [comment]
Is it typical to encounter this on accident? Maybe it's ok to expect people to restart vscode in this case, as they would have to now on stable?

**Comment by alexandrudima** [comment]
@roblourens I think killing the worker processes will cause the OS to release the file descriptors (I think it's part of the OS's job, together with freeing RAM, etc. but maybe I am mistaken).

I don't think anyone would often run into this, I just thought that since these processes are stateless workers and we have the chance to kill them when they are unresponsive, we should do so. Not a critical issue and feel free to close as designed if you wish to.

**Comment by jvilk** [comment]
Note that this problem also occurs without regular expressions when searching in a directory with many files.

I poke at the Chromium source code using Visual Studio Code, and sometimes perform a search across all files by accident. I either have to wait a minute or so for the search to complete, or kill Visual Studio Code.

I just encountered this issue a few times today (maybe my coffee isn't working...), and felt frustrated enough to see if an issue exists. :)

**Comment by roblourens** [comment]
Ripgrep search will be enabled by default for he March release, and isn't susceptible to catastrophic regex backtracking, and I kill the process as soon as esc is pressed.
