### ISSUE TITLE
Remove context menu on Run menu

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#166623]
Reminded of this by https://github.com/microsoft/vscode/issues/166506

We currently have a context key (when clause) for the run menu (in the main menu). This means we don't know if the menu should be displayed on startup because it depends on extensions. The Terminal menu also has a context key but resolves very quickly so there is no delay. Should we remove both of these when clauses in favor of keeping them around with possibly disabled menu items.

E.g. The "Install additional debuggers" entry should still be shown in the run menu if no current contexts are available.

**Comment by isidorn** [comment]
Assigning to @roblourens who now owns the Debug UI.
Rob let me know if I can help here.

**Comment by roblourens** [comment]
Which menu are you talking about? How is the context menu involved?

**Comment by sbatten** [comment]
Context Menu should have been Context Key. Sorry about that, I'll edit the original post.

**Comment by sbatten** [comment]
Looks like @Tyriar has decided to go this route with the Terminal menu, so I think we should align here too.

**Comment by roblourens** [comment]
So the terminal menu will be shown all the time in web? That's what will happen with Run. I guess it will show "Install additional debuggers"

And should other items be disabled or missing? They currently use `when` so are missing. It would look like this

<img width="245" alt="image" src="https://user-images.githubusercontent.com/323878/206041020-d95a51b5-1274-4194-a993-dc6d82784ccd.png">

I'm fine with that if it's consistent

**Comment by roblourens** [comment]
Actually, if the Run menu doesn't have a when clause, but all the subitems do and it is false, then the Run menu still doesn't show up. Would that be ok or is that still slow?

**Comment by sbatten** [comment]
Won't install additional debuggers always be visible?

**Comment by sbatten** [comment]
I see that entry as a way for users to discover how to get our web-based code execution extensions like Python. Maybe the text is not right? We could even have a web specific entry that filters the extension list to web-supported debuggers instead of all?

**Comment by roblourens** [comment]
> We could even have a web specific entry that filters the extension list to web-supported debuggers instead of all?

Yeah, I think that when those exist we should think about what the onramp looks like. For now I'll remove the when clause on the Run menu if you think that's the right thing to do.

**Comment by sbatten** [comment]
@roblourens sounds good, thank you

**Comment by roblourens** [comment]
Ok, this actually isn't working the way I thought it did, and the result is that the Run menu never shows, at all. I must have tested it wrong, maybe you have to restart vscode for native menu changes to take full effect?

The current state is that the Run menu has no when clause, and every command inside the menu does have a when clause. But the result seems to be:

If the menu doesn't have a when clause, but initially doesn't have any enabled commands inside it, then it doesn't appear and will never appear, even if the commands inside it later get their when clauses flipped to true. The only way to get it to conditionally appear is to add a when clause to the menu itself. Does that sound like a menu bug @sbatten?

 But also I can just go back to having "Install additional debuggers" enabled all the time, I think that's fine.

**Comment by sbatten** [comment]
@roblourens that very well could be a menu bug. but thinking about it, I think having the one item always in the menu is necessary because otherwise we still result in the behavior where we don't know for some time on startup whether to show the menu or not which causes flickering.

**Comment by sbatten** [comment]
@roblourens is it expected that all of these items in the run menu are active in web? 
<img width="163" alt="image" src="https://user-images.githubusercontent.com/6561887/214669994-1fe62ede-e236-4ac5-a610-89bb7f2c52c8.png">

**Comment by roblourens** [comment]
You probably have some extension enabled for web which claims it can debug

**Comment by sbatten** [comment]
Mock Debug and Python, thanks
