### ISSUE TITLE
Testing: right click on the gutter runs tests (and then opens popup)

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/vscode#166626]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0-insider
- OS Version: macOS 13.0

Steps to Reproduce:

1. Open a file with a test
2. Right click (two-finger-tap) a gutter test decoration to be able to pick Debug in menu

Expected: menu appears
Actual: test runs + menu appears

// @connor4312

**Comment by connor4312** [comment]
@sbatten this actually sounds identical to the bizarre issue I was running into in Chrome/Edge on vscode.dev the other day -- browser/electron triggers a faulty left mousedown event before the right mousedown even.

I wasn't able to get a consistent repro (happened in some versions and channels of Edge and Chrome, sometimes I had to be in the vscode.dev PWA, soemtimes not) and it never happened on his machine.

**Comment by sbatten** [comment]
I agree that sounds eerily similar. Is there something strange going on in Ventura or a mouse driver? I don't know how to debug this since even with a repro, the culprit is beyond VS Code.

**Comment by connor4312** [comment]
I think this has gone away now(?) with either a vscode/electron update or a macos update. Let me know if not.
