### ISSUE TITLE
Preview activity bar icon reordering during drag operation (and let me be sloppy)

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode#16669]
Testing #16326

To reorder icons in the activity bar, I have to drag and drop the icon directly on the position I would like it to occupy.  I can't drop it between two icons and have it position between them.

This is generally OK, but when I want to put an icon at the bottom of the list I really just want to be sloppy and drag it to the bottom/empty area of the activity bar. I don't want to have to be accurate and drop it in the last position (the horror of having to be accurate!!)

![image](https://cloud.githubusercontent.com/assets/1487073/20929228/830ab4d2-bbc9-11e6-81e0-aa2c562b8549.png)

It would be ideal if when i dragged the icon up or down you could see the other icons move around and almost preview what the activity bar will look like when it is dropped.

**Comment by bpasero** [comment]
Yup, sean filed a similar request.

**Comment by bpasero** [comment]
Actually it was Greg, closing as duplicate: https://github.com/Microsoft/vscode/issues/16541
