### ISSUE TITLE
debt: review implicit public fields that are actually protected

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#166603]
Apparently TypeScript allows that a subtype to increase visibility of protected properties to public. This has become visible while working on property mangling (see https://github.com/microsoft/vscode/issues/165429). This mean a subtype can prevent an inherited name from being mangled. 

```ts
class Animal {
  protected legCount :number;
}

class Snail {
  public legCount = 0; // this property is now PUBLIC, thereby Animal#legCount is also public'ish
}

```

To generate the list below run `node build/lib/mangleTypeScript.js` (note that it will create a src-mangle folder)

Generally, an inherited protected field should stay protected and while scanning over the usages I see two patterns

* accidental public-making by simply forgetting to write the keyword 👉 We should fix those
* purposeful public-making to access a protected field in tests which is 🐟y. Depending on cost and impact we should fix those

---

- [ ] `setChild` from src/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/ast.ts:264 became PUBLIC because of: src/vs/editor/common/model/bracketPairsTextModelPart/bracketPairsTree/ast.ts:391
- [x] `saveState` from src/vs/workbench/common/component.ts:42 became PUBLIC because of: src/vs/workbench/browser/parts/views/viewPaneContainer.ts:733
- [x] `pinnedPanelsKey` from src/vs/workbench/browser/parts/panel/panelPart.ts:145 became PUBLIC because of: src/vs/workbench/browser/parts/panel/panelPart.ts:915
- [x] `placeholdeViewContainersKey` from src/vs/workbench/browser/parts/panel/panelPart.ts:146 became PUBLIC because of: src/vs/workbench/browser/parts/panel/panelPart.ts:916
- [x] `doInitialize` from src/vs/platform/userDataSync/common/abstractSynchronizer.ts:978 became PUBLIC because of: src/vs/platform/userDataSync/common/keybindingsSync.ts:354
- [x] `isItemNew` from src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts:180 became PUBLIC because of: src/vs/workbench/contrib/preferences/browser/settingsWidgets.ts:825
- [x] `onDidChangeObject` from src/vs/workbench/contrib/preferences/browser/settingsTree.ts:1255 became PUBLIC because of: src/vs/workbench/contrib/preferences/browser/settingsTree.ts:1380
- [x] `didRenderCell` from src/vs/workbench/contrib/notebook/browser/view/cellPart.ts:97 became PUBLIC because of: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellToolbars.ts:199
- [x] `didRenderCell` from src/vs/workbench/contrib/notebook/browser/view/cellPart.ts:38 became PUBLIC because of: src/vs/workbench/contrib/notebook/browser/view/cellParts/cellProgressBar.ts:31
- [x] `updateLabel` from src/vs/base/browser/ui/actionbar/actionViewItems.ts:339 became PUBLIC because of: src/vs/workbench/contrib/notebook/browser/viewParts/notebookKernelView.ts:172
- [x] `updateLabel` from src/vs/base/browser/ui/actionbar/actionViewItems.ts:209 became PUBLIC because of: src/vs/workbench/contrib/notebook/browser/viewParts/notebookKernelView.ts:172
- [x] `getEditorContextFromArgsOrActive` from src/vs/workbench/contrib/notebook/browser/controller/coreActions.ts:163 became PUBLIC because of: src/vs/workbench/contrib/notebook/browser/controller/executeActions.ts:144
- [x] `updateChecked` from src/vs/base/browser/ui/actionbar/actionViewItems.ts:247 became PUBLIC because of: src/vs/workbench/contrib/testing/browser/testingExplorerFilter.ts:246
- [x] `runAction` from src/vs/base/common/actions.ts:191 became PUBLIC because of: src/vs/workbench/contrib/testing/browser/testingExplorerView.ts:1016
- [x] `addDecorations` from src/vs/editor/contrib/quickAccess/browser/editorNavigationQuickAccess.ts:179 became PUBLIC because of: src/vs/workbench/contrib/codeEditor/browser/quickaccess/gotoSymbolQuickAccess.ts:122
- [x] `clearDecorations` from src/vs/editor/contrib/quickAccess/browser/editorNavigationQuickAccess.ts:223 became PUBLIC because of: src/vs/workbench/contrib/codeEditor/browser/quickaccess/gotoSymbolQuickAccess.ts:126
- [x] `extensionsWorkbenchService` from src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:814 became PUBLIC because of: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:848
- [x] `updateClass` from src/vs/base/browser/ui/actionbar/actionViewItems.ts:361 became PUBLIC because of: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:970
- [x] `updateClass` from src/vs/base/browser/ui/actionbar/actionViewItems.ts:243 became PUBLIC because of: src/vs/workbench/contrib/extensions/browser/extensionsActions.ts:970
- [ ] `_postDetachModelCleanup` from src/vs/editor/browser/widget/codeEditorWidget.ts:1839 became PUBLIC because of: src/vs/editor/standalone/browser/standaloneCodeEditor.ts:473
- [ ] `_insertSuggestion` from src/vs/editor/contrib/suggest/browser/suggestController.ts:277 became PUBLIC because of: src/vs/editor/contrib/suggest/test/browser/suggestModel.test.ts:708
- [x] `getFolderHash` from src/vs/platform/backup/electron-main/backupMainService.ts:433 became PUBLIC because of: src/vs/platform/backup/test/electron-main/backupMainService.test.ts:154
- [x] `getWorkspaceBackups` from src/vs/platform/backup/electron-main/backupMainService.ts:98 became PUBLIC because of: src/vs/platform/backup/test/electron-main/backupMainService.test.ts:158
- [x] `getFolderBackups` from src/vs/platform/backup/electron-main/backupMainService.ts:108 became PUBLIC because of: src/vs/platform/backup/test/electron-main/backupMainService.test.ts:162
- [x] `toExcludePaths` from src/vs/platform/files/node/watcher/parcel/parcelWatcher.ts:170 became PUBLIC because of: src/vs/platform/files/test/node/parcelWatcher.integrationTest.ts:50
- [x] `restartWatching` from src/vs/platform/files/node/watcher/parcel/parcelWatcher.ts:615 became PUBLIC because of: src/vs/platform/files/test/node/parcelWatcher.integrationTest.ts:54
- [x] `createStorageDatabase` from src/vs/platform/userDataProfile/common/userDataProfileStorageService.ts:123 became PUBLIC because of: src/vs/platform/userDataProfile/test/common/userDataProfileStorageService.test.ts:34
- [x] `triggerLocalChange` from src/vs/platform/userDataSync/common/abstractSynchronizer.ts:172 became PUBLIC because of: src/vs/platform/userDataSync/test/common/synchronizer.test.ts:164
- [x] `emitWillSaveState` from src/vs/platform/storage/common/storage.ts:352 became PUBLIC because of: src/vs/workbench/test/common/workbenchTestServices.ts:130
- [x] `unregisterWorkingCopy` from src/vs/workbench/services/workingCopy/common/workingCopyService.ts:196 became PUBLIC because of: src/vs/workbench/test/browser/workbenchTestServices.ts:225
- [x] `fileService` from src/vs/workbench/services/workingCopy/common/workingCopyBackupService.ts:135 became PUBLIC because of: src/vs/workbench/test/browser/workbenchTestServices.ts:1161
- [x] `onFilesConfigurationChange` from src/vs/workbench/services/filesConfiguration/common/filesConfigurationService.ts:112 became PUBLIC because of: src/vs/workbench/test/browser/workbenchTestServices.ts:1420
- [x] `saveState` from src/vs/workbench/browser/parts/editor/editorPart.ts:1138 became PUBLIC because of: src/vs/workbench/test/browser/workbenchTestServices.ts:1660
- [x] `add` from src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts:496 became PUBLIC because of: src/vs/workbench/test/browser/workbenchTestServices.ts:1730
- [x] `remove` from src/vs/workbench/services/textfile/common/textFileEditorModelManager.ts:511 became PUBLIC because of: src/vs/workbench/test/browser/workbenchTestServices.ts:1734
- [ ] `getExperiments` from src/vs/workbench/contrib/experiments/common/experimentService.ts:231 became PUBLIC because of: src/vs/workbench/contrib/experiments/test/electron-browser/experimentService.test.ts:61
- [x] `setAllToState` from src/vs/workbench/contrib/testing/common/testResult.ts:517 became PUBLIC because of: src/vs/workbench/contrib/testing/test/common/testResultService.test.ts:51
- [x] `persistScheduler` from src/vs/workbench/contrib/testing/common/testResultService.ts:114 became PUBLIC because of: src/vs/workbench/contrib/testing/test/common/testResultService.test.ts:211
- [x] `handleBeforeShutdown` from src/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.ts:77 became PUBLIC because of: src/vs/workbench/services/lifecycle/test/electron-browser/lifecycleService.test.ts:19
- [x] `handleWillShutdown` from src/vs/workbench/services/lifecycle/electron-sandbox/lifecycleService.ts:156 became PUBLIC because of: src/vs/workbench/services/lifecycle/test/electron-browser/lifecycleService.test.ts:23
- [x] `onScopeOpened` from src/vs/workbench/services/progress/browser/progressIndicator.ts:351 became PUBLIC because of: src/vs/workbench/services/progress/test/browser/progressIndicator.test.ts:70
- [x] `onScopeClosed` from src/vs/workbench/services/progress/browser/progressIndicator.ts:361 became PUBLIC because of: src/vs/workbench/services/progress/test/browser/progressIndicator.test.ts:71
- [x] `restoreBackups` from src/vs/workbench/services/workingCopy/common/workingCopyBackupTracker.ts:329 became PUBLIC because of: src/vs/workbench/services/workingCopy/test/browser/workingCopyBackupTracker.test.ts:72
- [x] `getMemento` from src/vs/workbench/common/component.ts:38 became PUBLIC because of: src/vs/workbench/test/browser/part.test.ts:49
- [x] `createViewPaneContainer` from src/vs/workbench/browser/panecomposite.ts:153 became PUBLIC because of: src/vs/workbench/test/browser/viewlet.test.ts:23
- [x] `createTextEditorModel` from src/vs/workbench/common/editor/textEditorModel.ts:146 became PUBLIC because of: src/vs/workbench/test/browser/parts/editor/editorModel.test.ts:43

**Comment by bpasero** [comment]
First round: https://github.com/microsoft/vscode/pull/166787

**Comment by bpasero** [comment]
Updated the list with latest.

**Comment by jrieken** [comment]
Closing this - there is one violation remaining but that made it onto the allow list

**Comment by KernelDeimos** [comment]
> Closing this - there is one violation remaining but that made it onto the allow list

Aha, that explains why I didn't need to change `panecomposite.ts` to fix my build. That was confusing me for a little while.
