### ISSUE TITLE
Default settings is missing HTML, CSS and TypeScrpt Settings

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16661]
Version 1.8.0-insider  Linux
Commit a8d5b9281e2118c2a10098098ddaac949ce69fe0
Date 2016-12-06T07:19:06.272Z

- open the user settings
- in the default settings pane, look for the HTML section. It's missing.

**Comment by sandy081** [comment]
@aeschli I could see HTML settings

I would like to confirm if it is a dup of #16660. Can you please do following steps

- Close Settings editor
- Refresh VS Code
- Open Settings

Are all settings are shown now?

**Comment by aeschli** [comment]
Yes refreshing shows the options. Closing as duplicate of #16660.
