### ISSUE TITLE
Disable extension pack with its dependencies

### ISSUE THREAD

**Issue by AndresOchoaS** [Microsoft/vscode#16666]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 4.8.11-1-default
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.2|
|php-debug|felixfbecker|1.10.0|
|php-intellisense|felixfbecker|0.0.12|
|php-pack|felixfbecker|1.0.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|cordova-tools|vsmobile|1.2.3|

---

Steps to Reproduce:

1. Disable php-pack in workspace
2. The extensions php-debug and php-intellisense are not disabled

**Comment by sandy081** [comment]
Duplicates #14440
