### ISSUE TITLE
[win] cached data clean up logic removes good data

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16662]
On Windows 10, open `C:\Users\<username>\AppData\Roaming\Code - Insiders\CachedData` and start insiders. Notice how snapshot files are being created but deleted like some seconds after startup.

![untitled](https://cloud.githubusercontent.com/assets/900690/20928433/1ac6b950-bbc6-11e6-83dc-ea8669261ff8.gif)

I am not seeing any output in the console.

**Comment by jrieken** [comment]
Likely due to this: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/nodeCachedDataManager.ts#L73
