### ISSUE TITLE
Make Run Tests and Debug Tests default profile in sync 

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/vscode#166642]
Currently, in vscode extension when changing default profile under Run Tests button, it doesn't automatically change it under Debug Tests button. I had to change it again in debug tests.

Does it make sense to make them in sync instead of doing it twice?

<img width="245" alt="Screen Shot 2022-11-17 at 9 41 00 AM" src="https://user-images.githubusercontent.com/22205721/202565808-1e504f2f-47d4-4579-9a0a-45738ecc33c2.png">

We are using playwright for test automation and we constantly change default profile to switch browsers. I have to change it twice in both run tests and debug tests.
https://github.com/microsoft/playwright/issues/18885

**Comment by salimshamim** [comment]
Is this already solved/added? I came here from first time issues section. How can I contribute?

**Comment by connor4312** [comment]
Not added yet. Here's a code pointer:

https://github.com/microsoft/vscode/blob/50113318edfcc3ae566a39c67d8d4fb7875329d6/src/vs/workbench/contrib/testing/common/testProfileService.ts#L63-L71

**Comment by ambujsahu81** [comment]
Hi, i wanted to work on this issue but not sure if someone else is working on it. 

so far i tried make them non specific for the group but it didn't work as profiles Id for different run group (Run Tests button and Debug Tests button) are also different. For example; -

```js
 {
        "profileId": 813829693, // this is different 
        "controllerId": "pw.extension.testController",
        "label": "chromium — Runing_projects\\playwright.config.ts", // this is same
        "group": 2,   // this is for test run group
    },
    {
        "profileId": 813829694, // this is different 
        "controllerId": "pw.extension.testController",
        "label": "chromium — Runing_projects\\playwright.config.ts", // this is same
        "group": 4, // this is for debug run group
    }
```

A work around that i could to think is while setting the selected profiles in  `preferredDefaults` also select other profiles  which has same label/tag property as that of selected profiles but with different group id to include all group from `testRunProfileBitsetList`

Not sure if this is the correct approach. Any suggestion or helpful input on how to handle different profileId issue ?

**Comment by connor4312** [comment]
Yea, I think we should attempt to sync them by their `label`. It may not be the case that there's always a same-labelled profile for run and debug, but if there is we can synchronize it

**Comment by ambujsahu81** [comment]
Hi, i have tried to fix this issue and create a pr that adds a small code to update  ( run tests or debug tests ) default profiles to make them sync with any changes done to either of them. It uses label property to sync the default profiles. Please have a look 🙂.

**Comment by TylerLeonhardt** [comment]
@connor4312 maybe I'm misunderstanding but I clicked this:
![image](https://user-images.githubusercontent.com/2644648/214686791-c8da1270-e0f1-4b54-bca8-d2d8cd280db5.png)
selected a different one here:
![image](https://user-images.githubusercontent.com/2644648/214686866-782386c1-8efe-4c3c-a09a-9194c07d9f05.png)
and debug was not updated:
![image](https://user-images.githubusercontent.com/2644648/214686926-6052caac-882e-456f-a32e-eb8103e27d52.png)

**Comment by connor4312** [comment]
The selfhost test provider has different names for the run and debug profiles. But you could [clone it locally](https://github.com/microsoft/vscode-selfhost-test-provider) and change that: this change makes profiles with the same name stay in sync between the two.
