### ISSUE TITLE
Docs > when clause contexts > view identifiers: workbench.view.scm is not correct, workbench.scm is

### ISSUE THREAD

**Issue by Yohnny777** [microsoft/vscode#166647]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1, Electron 19.0.17, Node 16.14.2, Chromium 102.0.5005.167,
- OS Version: Windows_NT x64 10.0.22000

Referring to this: https://code.visualstudio.com/api/references/when-clause-contexts#activefocused-view-or-panel-when-clause-context

When clause contexts' Source Control's view identifier is not `workbench.view.scm`
as docs state, but is actually `workbench.scm`. I discovered this while writing
key binding with `focusedView == workbench.view.scm`, it would never be true,
but it works correctly with `focusedView == workbench.scm`.  I got this value from 
Developer: Inspect context keys command.

Steps to Reproduce:

1. Try to create any keybind with focusedView == 'workbench.view.scm', shouldn't work
Try adding this for example:
```json
  {
    "key": "escape",
    "command": "workbench.explorer.fileView.focus",
    "when": "focusedView == workbench.view.scm"
  },
```
3. Change when clause to focusedView == 'workbench.scm' should work now
```json
  {
    "key": "escape",
    "command": "workbench.explorer.fileView.focus",
    "when": "focusedView == workbench.scm"
  },
```

Looks like a "typo" while writing the docs, or internally view identifiers
changed and docs were not updated.

I did not check if other IDs are correct, like `workbench.view.search` etc,
they might be wrong in the same way as well.

**Comment by lszomoru** [comment]
Adding @gregvanl, @sandy081, @sbatten to confirm whether this is indeed a documentation bug or an issue with setting `focusedView`.

**Comment by sandy081** [comment]
This seems to be a doc bug - because I see the view id in our code is `workbench.scm`here - https://github.com/microsoft/vscode/blob/f126d786635872b21ff0890c9e7108fcf54e2ab3/src/vs/workbench/contrib/scm/common/scm.ts#L18

**Comment by Yohnny777** [comment]
```ts
export const VIEWLET_ID = 'workbench.view.scm';
export const VIEW_PANE_ID = 'workbench.scm';
```

Yeah, someone must've mistaken these two

**Comment by gregvanl** [comment]
Agree with Lad, I haven't made progress on this nor the vscode-docs issue and PR until I understand when each ID should be used and whether other views have separate view and pane IDs.

`workbench.view.blah` is usually the command ID for opening the view, for example:

![image](https://user-images.githubusercontent.com/12818376/207647457-1a439d1a-ebb2-4de4-98d0-62acefb926a3.png)

**Comment by sandy081** [comment]
I see the confusion here - we have view containers (viewlets/panels) and views.  There are following three contexts

- `activeViewlet`  - which expects viewlet/view container id
- `activePanel`  - which expects panel/view container id
- `focusedView` - which expects view id

Probably we shall update the doc by listing viewlets and views ids.

**Comment by lszomoru** [comment]
Thanks @sandy081 for the clarifications. Could you please work with Greg to update the page? Thank you!

**Comment by Yohnny777** [comment]
It is almost a month and you did not do any progress on literally fixing a TYPO. I even did it for you and created pull request but you did not bother to accept it. I'm just going to switch to neovim
