### ISSUE TITLE
Integrated terminal with canvas renderer: dimensions not reported correctly

### ISSUE THREAD

**Issue by windsource** [microsoft/vscode#166682]
Type: <b>Bug</b>

Since this version of VSCode the integrated terminal does not report correct width and height and thus full screen tools like less or k9s do not use the full screen size. This problem only occurs since this version of VSCode and only with the setting

```text
 "terminal.integrated.gpuAcceleration": "canvas",
```

Steps to reproduce:

Open an integrated terminal. Type `tput lines && tput cols` to get the current height and width of the terminal. Resize the terminal e.g. by increasing the window size of VSCode of make the terminal full screen. Then type `tput lines && tput cols`  again.

Expected:

The output changes and shows the new width and height of the terminal after resizing.

Actual:

The output does not change and still shows width and height before resizing.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.15.76-1-MANJARO
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.76-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|14.34GB (10.74GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|40%|
|DESKTOP_SESSION|xfce|
|XDG_CURRENT_DESKTOP|XFCE|
|XDG_SESSION_DESKTOP|xfce|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|Dev Container: Rust|
|OS|Linux x64 5.15.76-1-MANJARO|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (4 x 2712)|
|Memory (System)|14.34GB (10.74GB free)|
|VM|0%|
</details><details><summary>Extensions (67)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-base64|ada|0.1.0
vscode-color|ans|0.4.5
swagger-viewer|Arj|3.1.2
asciidoctor-vscode|asc|2.9.8
cform|aws|0.0.24
color-info|bie|0.7.0
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.0
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
vscode-tailwindcss|bra|0.9.1
better-toml|bun|0.3.2
postcss|css|1.0.9
vscode-markdownlint|Dav|0.48.1
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|13.1.0
go|gol|0.36.0
hcl|has|0.3.0
terraform|has|2.25.0
vscode-drawio|hed|1.6.4
vscode-k3d|ine|0.0.10
vue|jcb|0.1.5
plantuml|jeb|2.17.4
vscode-graphviz|joa|0.0.6
vscode-lua-format|Koi|1.3.8
rainbow-csv|mec|3.3.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestorage|ms-|0.15.0
vscode-docker|ms-|1.22.2
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.2
azurecli|ms-|0.5.0
cpptools|ms-|1.12.4
remote-explorer|ms-|0.0.2
vscode-paste-image|mus|1.0.4
vetur|oct|0.36.1
geo-data-viewer|Ran|2.5.0
java|red|1.12.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
rust-analyzer|rus|0.3.1285
open-in-browser|tec|2.0.0
shellcheck|tim|0.28.2
vscode-terminal-here|Tyr|0.2.4
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.46.0
vscode-java-pack|vsc|0.25.6
vscode-java-test|vsc|0.37.1
jinja|who|0.0.8
vscode-proto3|zxh|0.5.5

(1 theme extensions excluded)

</details>

**Comment by jeanp413** [comment]
Seems it's already fixed in insiders as I cannot repro there

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by windsource** [comment]
The problem seems to be fixed in 1.74.0.
