### ISSUE TITLE
Participants can not see all folders

### ISSUE THREAD

**Issue by ferburs** [microsoft/vscode#166665]
Type: <b>Bug</b>

In a live session with some classmates from the faculty, not all the folders with the corresponding files appear, only some

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.15.0-53-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5600 6-Core Processor (12 x 3500)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|2, 2, 1|
|Memory (System)|15.54GB (12.25GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 5612dc50-40ec-422e-bf7f-40f82a027fe1|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
plantuml|jeb|2.17.4
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
vsliveshare|ms-|1.0.5776
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by lszomoru** [comment]
@ferburs, how is the content being shared among participants?
Have you followed up with the faculty as this does not seem to be VS Code related.

**Comment by ferburs** [comment]
We join my colleagues via live (he gives me a link generated by the vscode) and when I join some of our project folders do not appear. I don't know if I answered your question

**Comment by lszomoru** [comment]
@ferburs, do you mean Live Share - https://code.visualstudio.com/learn/collaboration/live-share?

**Comment by ferburs** [comment]
Exactly

**Comment by lszomoru** [comment]
@ferburs, could you please open an issue in [the extension's repository](https://github.com/MicrosoftDocs/live-share/issues)? Thanks!
