### ISSUE TITLE
Adopt implicit activation events generation

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#166624]
Part of https://github.com/microsoft/vscode/issues/164701

The latest insiders build will infer the following activation events for extensions based on their contributions in package.json:
- `onCommand:` for all commands that an extension directly contributes
- `onNotebookSerializer:` for all notebook serializers that an extension directly contributes

This means that extension authors no longer need to spell out `onCommand:` activation events for the commands that their extensions registers, and allows us to remove debt for notebooks activation.

To generate implicit events for an extension point that you own in core, when calling `registerExtensionPoint`, you would optionally pass an `activationEventsGenerator` which takes an array of contributions from an extension, generates activation events for each contribution, and adds them to the collector by calling `result.push(activationEvent)`, e.g. see the example below for notebooks:

https://github.com/microsoft/vscode/blob/8007c639810ac284733e1ee3acc901d5b480e706/src/vs/workbench/contrib/notebook/browser/notebookExtensionPoint.ts#L236-L242

Ask: please consider adopting `activationEventsGenerator` if you own a static contribution which is associated with an activation event that extensions must currently explicitly spell out. Some possible candidates:

- [x] views -> `onView` @alexr00 
- [x] customEditors -> `onCustomEditor` @mjbvz
- [x] webview panels -> `onWebviewPanel` @mjbvz
- [ ] ~~debuggers -> `onDebugResolve` @roblourens~~
- [x] languages -> `onLanguage` @alexdima
- [x] authentication -> `onAuthenticationRequest` @tylerleonhardt

**Comment by mjbvz** [comment]
I adopted this for custom editors. Webview panels don't have a contribution point and I think webview view will be covered by the normal `views` contribution

**Comment by sandy081** [comment]
Transferring to @alexr00 for views extension point adoption.

**Comment by alexr00** [comment]
@joyceerhl took care of views!

**Comment by roblourens** [comment]
Sorry, it's actually not possible to adopt this for debuggers. `onDebugResolve` is only needed when an extension uses a `DebugConfigurationProvider`- this is... almost all of them, but it's not required, and isn't appropriate to add automatically. You can have a debugger contribution without activating the extension at all.

**Comment by joyceerhl** [comment]
Thanks everyone for the adoption!
