### ISSUE TITLE
Line Return jumps to beginning of next line, doesn't hold tab place

### ISSUE THREAD

**Issue by sosensible** [Microsoft/vscode#16671]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|project-manager|alefragnani|0.12.2|
|githistory|donjayamanne|0.1.2|
|jquerysnippets|donjayamanne|0.0.1|
|python|donjayamanne|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|php-debug|felixfbecker|1.10.0|
|knockoutjs|furstenberg|0.1.0|
|vue-snippets|hollowtree|0.0.8|
|beautify|HookyQR|0.6.2|
|task-master|ianhoney|0.1.37|
|ionic2-vscode|jgw9617|1.0.0|
|Angular2|johnpapa|1.0.2|
|quicksnippet|mousetraps|0.0.1|
|debugger-for-chrome|msjsdiag|2.3.2|
|laravel-blade|onecentlin|1.5.0|
|laravel5-snippets|onecentlin|1.3.1|
|sharecode|RolandGreim|0.3.1|
|ColdFusion|SketchPunk|0.0.1|
|nativescript|Telerik|0.4.0|
|wordpress-snippet|tungvn|1.1.1|
|ionic2-snippets|uqutub|0.0.4|
|gitflow|vector-of-bool|0.1.0|
|vscode-react-native|vsmobile|0.2.3|
|gitblame|waderyan|1.3.0|
|bootstrap-3-snippets|wcwhitehead|0.0.8|
|nativescript-ng2-snippets|wwwalkerrun|1.2.0|

---

Steps to Reproduce:

1.  Working in app with tags, or script and when hitting return the next line is right for about one second then it jumps to the start of the line

This is a royal pain because rather than focusing on the code I am distracted with maintaining the layout.

**Comment by alexandrudima** [comment]
@sosensible Can you reproduce this when disabling all extensions and commenting out your settings (e.g. editor.formatOnType ?)

**Comment by sosensible** [comment]
You are right... it appears to be the innovation of a plugin developer. :)

Kudos.

**Comment by sosensible** [comment]
P.S. It would be great if just like disabling a plugin for a project we
could also enable a plugin for a project.

So that would give you three things.

1. Standard universal enabled/disabled plugins.
2. Ability to disable per project.
3. ( MISSING ) Ability to enable plugin per project.

**Comment by alexandrudima** [comment]
I will close this for now, please feel free to open a new issue concerning the enable extension per project request.

your last comment fyi @sandy081
