### ISSUE TITLE
vscode-tslint: no quick-fix for "ordered-imports" rule

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16676]
While testing #16519:

Enabling "ordered-imports" did result in some warnings in my test project but no quick fix lightbulb was showing up.

Since "ordered-imports" is listed on https://palantir.github.io/tslint/2016/11/17/new-for-4.0.html as having a fixer, it is not clear whether there is a problem with the corresponding quick fix in VS Code.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#148
