### ISSUE TITLE
Error formatting html

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#16675]
- VSCode Version: Windows 10
- OS Version: 1.8.0 - insider a8d5b92

Steps to Reproduce:

-- Sorry for the English, I used Google Translator --

1. Formatting was strange compared to 1.7.2. All extensions disabled

![gif9](https://cloud.githubusercontent.com/assets/19866231/20930223/d272c3ae-bbb3-11e6-94b9-f54235e0d2d5.gif)

**Comment by aberman** [comment]
+1.  Same issue here.

**Comment by aeschli** [comment]
@Tekbr @aberman Can you paste the code snippet to reproduce?

**Comment by Tekbr** [comment]
@aeschli 

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
    <div class="">
        <div class="" id="">
            <div class="">
                <h5>
			<b> Teste</b>
		</h5>
            </div>
            <hr style="margin-top: 10px;">
            <ol>
                <li>
                    <h5>
                           <img src="view/test.png" width="190" height="35" align="middle" />
		    </h5>
                </li>
            </ol>
        </div>
    </div>
    
</body>
</html>
```

**Comment by aberman** [comment]
@aeschli , the HTML by @Tekbr exhibits the issue.  Thanks!

**Comment by adjeteyadjei** [comment]
Same issue here. 
The formatting breaks after the **style** attribute.

**Comment by gmhispagnol** [comment]
Same here. Any updates?

**Comment by aeschli** [comment]
duplicate of #17849
