### ISSUE TITLE
Improve introduction to Command Palette in get started walkthrough

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166735]
Ref #165846

Talking w/ @esonnino, we noticed a few potential problems/opportunities with how the command palette is presented in the first walkthrough:
- Should we be using a button for a keyboard-driven action? Does this discourage users from learning the shortcut?
- Is there a better command to try than `View toggle`?

<img width="598" alt="CleanShot 2022-11-18 at 11 27 02@2x" src="https://user-images.githubusercontent.com/25163139/202786534-3fbdfcfb-83b4-436a-bcab-018a28a46d02.png">

**Comment by bhavyaus** [comment]
I agree that using a button for a keyboard driven action appears counter productive. 

- Perhaps we can change it up to instead show where to find it (View -> Command Palette)? In the way that built-in help on the Mac works -> an overlay with an arrow pointing at the menu item?

-  We should also stop advertising the keyboard shortcut as a "Tip" and instead make it a part of the description. Calling it a "Tip" appears to lower the importance of the information being presented making it ignorable.

Should we also mention to the users how to find it via the menu (View -> Command Palette) ?

**Comment by daviddossett** [comment]
Catching up on mountain of notifications—I'll let @esonnino weigh in on this 👍 

I agree that we should see how it looks feature the keybinding rather than as a tip. The tip could be your first point on where to find it in the menu?
