### ISSUE TITLE
Selection menu does not reflect actual shortcuts

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16673]
Testing #16558

- Open the keyboard settings and add `{ "key": "ctrl+a",                "command": "" }`
- verify that Ctrl+A does not select all anymore
- look at the Selection menu: Select all still shows Ctrl+A as shortcut

**Comment by bpasero** [comment]
@aeschli you need a restart for the keybindings in the menu to update. There is another issue for that already.

**Comment by chrmarti** [comment]
Indeed, my bad, I should have mentioned that in the test item. Thanks.
