### ISSUE TITLE
Smoke test crashes

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#166799]
Noticed some crash dumps in this build:

https://dev.azure.com/monacotools/Monaco/_build/results?buildId=193221&view=artifacts&pathAsName=false&type=publishedArtifacts

[crashes.zip](https://github.com/microsoft/vscode/files/10047199/crashes.zip)

**Comment by deepak1556** [comment]
Addressed in https://github.com/microsoft/vscode-internalbacklog/issues/3272
