### ISSUE TITLE
VS Code-tslint: no quickfix for "comment-format"

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16679]
While testing https://github.com/Microsoft/vscode/issues/16519:

Enabling "comment-format" options like "check-uppercase" etc. only offer quick fix for disabling the rule but nothing for fixing it.

**Comment by egamma** [comment]
Issue confirmed, currently there is only a quick fix for the `check-space` option.

**Comment by egamma** [comment]
This issue was moved to Microsoft/vscode-tslint#147
