### ISSUE TITLE
Move extension button down

### ISSUE THREAD

**Issue by giovannicardamone-facile** [microsoft/vscode#166704]
I would like to have extensions button down

how it is:

![image](https://user-images.githubusercontent.com/113361605/202700023-635fb65e-7607-43aa-9c49-3ebb6c324662.png)

how it should be:

![Screenshot from 2022-11-18 12-56-58](https://user-images.githubusercontent.com/113361605/202700325-9d773afd-0dc6-4eab-bfd5-91887eda430e.png)

Why:

extensions is foundamental part of vscode editor, and it's useless in top-left panel.
Like account settings or vscode settings is part of the editor

**Comment by gjsjohnmurray** [comment]
Alternatively, right-click on it and hide it, then use the View menu entry when you want to manage extensions.

**Comment by giovannicardamone-facile** [comment]
well i don't see extension as a tool / functionality. Is Primary part of VSCode editor. so i don't think it is in correct position.

**Comment by sandy081** [comment]
Thanks for the suggestion and this has been thought about and the current presentation was more favoured.
