### ISSUE TITLE
Incorrect colors are used for `\xN8` and `\xN9` in strings in Rust

### ISSUE THREAD

**Issue by noritada** [microsoft/vscode#166781]
Type: <b>Bug</b>

In strings in Rust, `\xN8` and `\xN9` (N = 0-7) are colored incorrectly.
Although these characters are ASCII, they are colored in the same way as non-ASCII characters.

I have fixed this issue locally and will send a PR later.

![ss 2022-11-19 15 53 37](https://user-images.githubusercontent.com/20850/202840842-bc5a0d0a-bca1-4cac-901b-765dbc02b1b4.png)

Many thanks,

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 6, 5|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|. --crash-reporter-id a4a7ae6c-8e69-447d-8b0d-f4f038ddd3e6|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by alexr00** [comment]
We get our Rust syntax highlighting grammar from https://github.com/dustypomerleau/rust-syntax. I've moved the issue to https://github.com/dustypomerleau/rust-syntax/issues/33 and linked your PR.
