### ISSUE TITLE
V8 Cache: error telemetry not working?

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16670]
Steps to Reproduce:

1. run out of sources
2. enable `configuration.nodeCachedDataDir` by removing the check for isBuilt in `windows.ts`
3. add console.logging into `onNodeCachedDataError` of `nodeCachedDataManager`
4. create a file `C:\Users\<username>\AppData\Roaming\code-oss-dev\CachedData\1.8.0` so that an attempt to write to there will fail because it is not a folder
5. start

=> console log is not being triggered
=> if you add console.logging into `loader.js` where `writeFile` is called you see errors

**Comment by jrieken** [comment]
When verifying this be aware that cached data is only produced (and attempted to store) when starting the editor refresh, not when reloading.
