### ISSUE TITLE
Consider a Carousel for showcasing Walkthroughs instead of the current list of tiles 

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#166744]

**Comment by daviddossett** [comment]
Would love to hear more what you have in mind here. How does the carousel help compared to the list of tiles today? Is it to reduce clutter on the 'Get Started' page, or?

cc @esonnino

**Comment by bhavyaus** [comment]
Continuing this conversation here: https://github.com/microsoft/vscode/issues/165846
