### ISSUE TITLE
Complete walkthrough steps once viewed

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166747]
As explored in #142219, I think the walkthrough experience could have less friction if steps were checked off once viewed rather than waiting for the user to actually perform the specific action.

https://user-images.githubusercontent.com/25163139/202798799-9525014b-7526-43ca-837d-287884ae9ec0.mov

We could even think about removing the "checkbox" metaphor and instead only listening for a view event.

**Comment by bhavyaus** [comment]
Here is a previously related conversation around walkthrough checkboxes: https://github.com/microsoft/vscode/issues/116799
