### ISSUE TITLE
Unable to scroll upwards when the last output is scrollable

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#166754]
* Add setting `"notebook.experimental.outputScrolling": true`
* Create a cell with a large output
```py
for i in range(0,1000000):
    print(i)
```
* Move focus into the output, scroll down to the very end
* The notebook editor continues to scroll by one more page 
* Now scroll up
* 🐛  The output scrolls but the editor doesn't, even though the mouse is not on top of the output
* 
https://user-images.githubusercontent.com/876920/202806904-7ecccf4e-9fb4-4db3-a35a-08192014700a.mov

**Comment by amunger** [comment]
this only happens as long as I continue to scroll - any pause or movement of the mouse will make the editor scroll instead. Is it more persistent for you?

**Comment by amunger** [comment]
It looks like the browser behavior is to _always_ swallow the scroll event when the mouse is over a scrollable region, whereas this behavior will pass it to the editor when at the boundary. I like the browser behavior better, and that would likely fix this issue

**Comment by amunger** [comment]
closing as part of https://github.com/microsoft/vscode/issues/174913
