### ISSUE TITLE
Select Another Kernel shouldn't be visible if there are no other sources

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#166724]
When we only have a couple of notebook controllers created for a notebook type, without any kernel detection task or kernel source commands, the "Select Another Kernel" should not show.

**Comment by joyceerhl** [comment]
1. If I have no kernels in the MRU, clicking Select Kernel brings me to this quickpick, and clicking the back button here does nothing--I think it shouldn't be shown in this scenario
![image](https://user-images.githubusercontent.com/30305945/205148591-9f3b5dfb-ac6f-45d5-8824-e85592f7a34b.png)

2. If I have the Jupyter extension installed but not the Python extension installed, with the MRU picker enabled, the Select Kernel dropdown spins forever like this:
![image](https://user-images.githubusercontent.com/30305945/205148712-add56e4e-586f-49e8-b3b9-73d2171f0e1f.png)
