### ISSUE TITLE
Portable config file

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#166755]
Due situation with W10 and W11 where is hard compile bat to 2xe without problem runing VSC portable is hard without cmd, etc. and related commands in shortcuts where is need: --user-data-dir=  --extensions-dir=
By this want suggest to find something like portable.ini  as to first read/searching where will be:
```
[portable]
user-data-dir=
extensions-dir=
Cache_Data=
other=
all_what_need_VSC_that_user_dont_Know=
```

https://github.com/microsoft/vscode/issues/63657

There is many new issues around cache in portable

```
16072:1118/224209.930:ERROR:os_crypt_win.cc(93)] Failed to decrypt:  . (0x8009000B)
[16072:1118/224210.045:ERROR:network_sandbox.cc(302)] Failed to grant sandbox access to cache directory E:\Microsoft\user\Cache\Cache_Data: Access denied.(0x5)
[16072:1118/224210.046:ERROR:network_sandbox.cc(396)] Failed to grant sandbox access to network context data directory E:\Microsoft\user\Network: Access denied.. (0x5)
[16072:1118/224210.049:ERROR:network_service_instance_impl.cc(261)] Encountered error while migrating network context data or granting sandbox access for E:\Microsoft\user\Network. Result: 11: Ok. (0x0)
[16072:1118/224210.085:ERROR:backend_impl.cc(1433)] Unable to map Index file
[main 2022-11-18T21:42:10.099Z] update#setState idle
[16072:1118/224210.133:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access denied. (0x5)
[16072:1118/224210.133:ERROR:cache_util.cc(145)] Unable to move cache folder E:\Microsoft\user\GPUCache to E:\Microsoft\user\old_GPUCache_000
[16072:1118/224210.133:ERROR:disk_cache.cc(196)] Unable to create cache
[16072:1118/224210.133:ERROR:shader_disk_cache.cc(613)] Shader Cache Creation failed: -2
[main 2022-11-18T21:42:11.498Z] Starting extension host with pid 27032 (fork() took 8 ms).
[27348:1118/224211.897:ERROR:backend_impl.cc(1433)] Unable to map Index file
[27348:1118/224211.897:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access denied.(0x5)
[27348:1118/224211.897:ERROR:cache_util.cc(145)] Unable to move cache folder E:\Microsoft\user\Cache\Cache_Data to E:\Microsoft\user\Cache\old_Cache_Data_000
[27348:1118/224211.897:ERROR:disk_cache.cc(196)] Unable to create cache

```

**Comment by IllusionMH** [comment]
If you just want portable - you can just create `data` folder in unpacked `.zip` content as described in https://code.visualstudio.com/docs/editor/portable

If this solution doesn't work for your use case - please describe details why it does not work and exactly expected end result.

**Comment by ManPython** [comment]
@IllusionMH the problem is due that in case a dirs are not in default place as %USERPROFILE%\ and linked dirs not working or are not used in this way.

**Comment by joaomoreno** [comment]
@ManPython Have you read https://code.visualstudio.com/docs/editor/portable?

**Comment by ManPython** [comment]
@joaomoreno yes, why? This topic was time ago and I prepared .bat then compiled this to .exe but in W11 is problem and can hide cmd with the logs. By this I think is bather to organize this by .ini not some --vars as external. 
Other way show me what I doing wrong or why should do this other way.
https://github.com/microsoft/vscode/issues/83132

**Comment by joaomoreno** [comment]
> I prepared .bat then compiled this to .exe but in W11 is problem

This seems to be a bug you can report to the tool you use to compile the bat to an exe.

Beyond supporting portable mode, this feature is out of scope for VS Code itself, sorry about that. Maybe StackOverflow could help you come up with a solution for your purposes.

**Comment by ManPython** [comment]
But why users must combine some bat files for portable? And search help on StackOverflow in case developers are on VSC? Can't uderstand. Perfect grooming.

**Comment by ManPython** [comment]
@IllusionMH You don't understanding what is portable.. It's mind that app can works like before Window Vista model where now is local row/roaming, etc. By this portable is to omit the `%USERPROFILE%`. That is always expectation for any "portable" app, to not interfere into main windows profile. By this portable can be install/run on pendrive with all files, and indicate extensions, cache, user config files next to app. It is for that, especially if admins manage often user profiles, or reinstalling OS on C: and VSC and any portable app can be on D: drive long time with any operation around app to care that can't work after OS or profile changes.

Damm!!! Portable. :dancers:

**Comment by IllusionMH** [comment]
> By this portable is to omit the %USERPROFILE%. That is always expectation for any "portable" app, to not interfere into main windows profile.

Isn't that exactly what I described where all data would be stored in same folder with `.exe` and other files? It doesn't use user folder.

Did you tried steps from link?

**Comment by ManPython** [comment]
But I dont' have extension in %USERPROFILE% but in my own dir next to VSC not in due portable is unpacked, by this I have procedure.. unpack new version, copy to new version from old the .bat files that indicating the extensions dir and config  --user-data-dir= --extensions-dir=
Due can't copy .exe as compiled .bat and .bat is visible cmd with logs, that complicating, I can in future copy just portable.ini 

> Did you tried steps from link?

Yes, You missing point in this all. You want to copy each new update of VSC the dir called `Code to data and rename it to user-data` and not taking idea about not touching this in case can be huge dir and many files.
