### ISSUE TITLE
Chinese simplified 'hazni' not shown as expcted

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16677]
Testing #16547

Likely a bug in the wiki, but in https://github.com/Microsoft/vscode/wiki/IME-Test#windows-chinese,
type `hazni` results in '哈子你' not in '哈祝你'.

Same result when typing in WordPad.

If this is a issue in the wiki, let's fix it there.

**Comment by rebornix** [comment]
It's a wiki issue. The result of typing `hazni` with Chinese IME is dependent on how the algorithm decides which word should show first, sometimes it's smart sometime it's not. I'll update the wiki to make sure ppl get that.
