### ISSUE TITLE
Test: terminal quick fix API

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#166762]
Refs https://github.com/microsoft/vscode/issues/162950

- [x] Windows @connor4312
- [x] macOS @aeschli 
- [x] Linux @roblourens 

Complexity: 4

Authors: @meganrogge @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23166762%0A%0A&assignees=meganrogge,Tyriar)

---

This is proposed API, so you'll need to have `terminalQuickFixProvider` in your `enabledApiProposals`.

To contribute terminal quick fixes, an extension must contribute `quickFixes` to their `package.json`. For example:

```
"terminal": {
			"quickFixes": [
				{
					"id": "myprovider",
					"commandLineMatcher": "git",
					"outputMatcher": {
						"lineMatcher": "(?:(most similar (command|commands) (is|are)))((\\n\\s*(?<fixedCommand>[^\\s]+))+)",
						"anchor": "bottom",
						"length": 10,
						"offset": 0,
						"multipleMatches": true
					},
					"exitStatus": false
				}
			]
		}
```

The extension also needs to register a terminal quick fix provider. For example:

```
	function provideTerminalQuickFixes(result: {
		commandLine: string;
		commandLineMatch: RegExpMatchArray;
		outputMatch?: {
			regexMatch: RegExpMatchArray;
			outputLines: string[];
		};
	}) {
		if (!result?.outputMatch) {
			return;
		}
		const actions = [];
		const results = result.outputMatch.regexMatch[0].split('\n').map(r => r.trim());
		for (let i = 1; i < results.length; i++) {
			const fixedCommand = results[i];
			if (fixedCommand) {
				actions.push({
					type: 'command',
					terminalCommand: result.commandLine.replace(/git\s+[^\s]+/, `git ${fixedCommand}`),
				});
			}
		}
		return actions;
	}
	(vscode.window as any).registerTerminalQuickFixProvider('myprovider', { provideTerminalQuickFixes });
```

Verify that the documentation makes sense to you and that quick fixes work

**Comment by roblourens** [comment]
The example is a little different from the current dts- there is no `id` on the `TerminalQuickFix` type, and no `addNewLine`

**Comment by roblourens** [comment]
The dts also has `TerminalOutputMatcher` which seems unused now

**Comment by Tyriar** [comment]
If the example in the issue is wrong, go off whatever it in the d.ts as that should represent the latest.

**Comment by connor4312** [comment]
Documentation on the .d.ts is minimal thus far, but that can be honed as the API goes through calls and review which'll likely change things slightly anyway 🙂

**Comment by roblourens** [comment]
It seems like this discussion has come up before, maybe it's a different API, or this will be extended later- but can I register a similar command/output regex to run some other sort of command in vscode? For example, create a launch config from a node command, or open a notebook with the jupyter server that I just started?

**Comment by Tyriar** [comment]
@roblourens that's good if suggestions like that are expected to have a high chance of being used.

Creating a launch.json is tracked in https://github.com/microsoft/vscode/issues/150460 and I mention this is an ideal spot but I'm not sure if we would want to recommend creating a launch.json for every `node` command run? Currently you can only run commands or open links but we might extend it, you could work around this by setting some args in your provider and using the args when the command gets run.

Opening a notebook from a URL sounds like a perfect use case.

**Comment by roblourens** [comment]
> but I'm not sure if we would want to recommend creating a launch.json for every node command run

It could maybe be possible to have a less visible contribution, like besides "fixes" that you get with the lightbulb, maybe a more typical action could be contributed to the dot menu that shows on every command.

**Comment by Tyriar** [comment]
We've been chatting about 2 classes of quick fixes, similar to preferred/non-preferred code actions.
