### ISSUE TITLE
[json] Json Schema Exclusion doesn't work

### ISSUE THREAD

**Issue by MrVauxs** [microsoft/vscode#166795]
Type: <b>Bug</b>

When attempting to exclude files from a generic *.json schema, VSCode doesn't seem to recognize that, and apply it anyway.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No
Remote OS version: Linux arm64 5.15.0-1021-oracle

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 1600 Six-Core Processor             (12 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.44GB free)|
|Process Argv|--crash-reporter-id e072beae-0f6d-4b6e-801e-9d13707ea4cf|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: Oracle|
|OS|Linux arm64 5.15.0-1021-oracle|
|CPUs|Neoverse-N1 (4 x 0)|
|Memory (System)|23.43GB (20.44GB free)|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
5et-homebrew-helper|GoR|0.3.1
vscode-todo-highlight|jgc|2.0.4
vscord|Leo|5.0.10
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.2
5e-syntax|Tre|0.1.0
vscode-icons|vsc|12.0.1
unity-snippets|Ycl|0.1.2
go-to-character-position|dav|2.0.0
vscode-eslint|dba|2.2.6
git-project-manager|fel|1.8.2
vscode-npm|fkn|3.3.0
sort-json-array|fvc|3.1.0
copilot|Git|1.61.7372
git-graph|mhu|1.30.0
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-json-editor|nic|0.3.0
vscode-yaml|red|1.10.1
svelte-vscode|sve|106.2.0
pdf|tom|1.2.0
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
json|Zai|2.0.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by MrVauxs** [comment]
For example, this:
```json
"json.schemas": [
			{
				"fileMatch": [
					"search/*.json"
				],
				"url": "../Pf2eTools/test/schema-template/index.json"
			},
			{
				"fileMatch": [
					"data/*/*.json",
					"!package.json",
					"!search/*.json",
					"!index.json"
				],
				"url": "../Pf2eTools/test/schema-template/schema.json"
			},
			{
				"fileMatch": [
					"*.json",
					"!package.json",
					"!search/*.json",
					"!index.json"
				],
				"url": "../Pf2eTools/test/schema-template/schema.json"
			}
		],
```
Still tries to validate `index.json` files and all files in the `search` folder. 
The first schema that applies only to the `search` folder is also, simultaneously applied with the others, while it should be the only one.

**Comment by aeschli** [comment]
Ok, I see the bug. It's because of [here](https://github.com/Microsoft/vscode/blob/main/extensions/json-language-features/client/src/jsonClient.ts#L505), where we merge the schema associations

**Comment by revilowaldow** [comment]
Also affecting myself

**Comment by aeschli** [comment]
The workaround is not use two file associations for the same schema.
Just write:
```
			{
				"fileMatch": [
					"search/*.json"
				],
				"url": "../Pf2eTools/test/schema-template/index.json"
			},
			{
				"fileMatch": [
					"*.json",
					"!package.json",
					"!search/*.json",
					"!index.json"
				],
				"url": "../Pf2eTools/test/schema-template/schema.json"
			}
```

**Comment by MrVauxs** [comment]
> The workaround is not use two file associations for the same schema. Just write:
> 
> ```
> 			{
> 				"fileMatch": [
> 					"search/*.json"
> 				],
> 				"url": "../Pf2eTools/test/schema-template/index.json"
> 			},
> 			{
> 				"fileMatch": [
> 					"*.json",
> 					"!package.json",
> 					"!search/*.json",
> 					"!index.json"
> 				],
> 				"url": "../Pf2eTools/test/schema-template/schema.json"
> 			}
> ```

This unfortunately doesn't change anything.

**Comment by MrVauxs** [comment]
To elaborate 

https://user-images.githubusercontent.com/32039708/208255257-75a772a4-0f57-4eba-a18b-b8b4be63fcf7.mp4
