### ISSUE TITLE
Editor Indent Guide ends when reaching any text

### ISSUE THREAD

**Issue by MStachowicz** [microsoft/vscode#166707]
Does this issue occur when all extensions are disabled?: **Yes**
- VS Code Version: 1.73.1
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:
1.  Enable editor.guides.bracketPairs
2.  Open a file with any number of scopes, write some text on the same column as the editor indent guide.
3.  Notice the scope outline ends on the text and does not continue beyond it.

![scopeOutlineError](https://user-images.githubusercontent.com/14092934/202730092-dbbb0b85-e3a3-4d2e-8a50-4e0d97488fcb.png)

It's very common to format c++ code to have access modifiers on the same column as the class name (see above). It is the default for VS studio and is a clang option used by many "AccessModifierOffset: -4".

I understand the outline cannot draw through the text, but in this situation it feels like it should continue on the next line after the access modifier (same as the dotted outline in Visual Studio 2022).

**Comment by hediet** [comment]
This looks like you didn't enable bracket pair guides, but indent guides.

![image](https://user-images.githubusercontent.com/2931520/205645778-870cf1fb-af56-4ee6-a56f-26ad291991bc.png)
