### ISSUE TITLE
Warnings in default settings editor

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16674]
They should not show up anywhere:

![image](https://cloud.githubusercontent.com/assets/900690/20930168/c93e4d44-bbcc-11e6-8ad5-2f0aa43b9c66.png)

**Comment by sandy081** [comment]
Improved following behavior:

- Extended resource editor input for default settings which made lifcycle management much simpler
- Warnings of default settings are shown only once
- When clicking on warnings, opens defaults settings separately (just as before)

Moving this to next milestone to decide if we want to show or not show the warning for default settings
