### ISSUE TITLE
Unbound keybindings should not show up in watermark

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16672]
![image](https://cloud.githubusercontent.com/assets/22350/20929891/d7b0d3a2-bbcb-11e6-82a5-c5717541437b.png)

**Comment by chrmarti** [comment]
Also on Windows. @mousetraps also noted the alignment of "unbound" is a little off.

**Comment by chrmarti** [comment]
Added keybinding for Open Folder (only used on Windows and Linux) and fixed the layout for 'unbound' for November.

**Comment by joaomoreno** [comment]
My point was rather: _what good do we do to a new user by telling him, the very first time he opens Code, that some command doesn't have an associated key binding_?

IMO, you should just filter out `unbound` commands from that list.

**Comment by chrmarti** [comment]
I agree and am tracking that as #16837.

**Comment by joaomoreno** [comment]
Missed the link. 👍
