### ISSUE TITLE
${file} variable should change when active editor pane switches to a different file

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#1667]
It appears that the `${file}` variable can be used in `launch.json` configurations to determine the "program" to be run when the user starts the debugger.  A couple users of the PowerShell extension have discovered that this variable will have the file path of the first opened file in the workspace.  However, if they switch active files this variable does not change, meaning that the debugger will always run that first file.  See more discussion here:

https://github.com/PowerShell/vscode-powershell/commit/a613d5eafa2f014ce0b2b5b857eb60d4e6d11fb8

It would be nice if this variable got updated dynamically so that the user can run the debugger against the currently active file without having to manually edit their `launch.json` file each time.  This is a pretty common practice when developing PowerShell scripts.

**Comment by bpasero** [comment]
@isidorn fyi

**Comment by isidorn** [comment]
Nice catch. I was doing some ovewriting of cached configurations in configuraiton service thus getting stale ones.

**Comment by daviwil** [comment]
Awesome, thanks Isidor!  This will be really helpful.

**Comment by bpasero** [comment]
Nice, I like ${file}
