### ISSUE TITLE
Changelog not appearing

### ISSUE THREAD

**Issue by mat-mcloughlin** [Microsoft/vscode#16687]
- VSCode Version: 1. She 7.2
- OS Version: OSX

I'm not sure if this a mistake on my part but for some reason my change log isn't appearing in the extensions marketplace. Nor, incidentally, can I see anybody else change log despite them being present for other users.

my extension is https://github.com/mat-mcloughlin/vscode-elixir and as far as I can tell I've defined the CONTRIBUTIONS.md file correctly

**Comment by joaomoreno** [comment]
Make sure to update `vsce`: `npm install -g vsce`.

**Comment by mat-mcloughlin** [comment]
yeah already did that I'm running `1.17.0`

**Comment by joaomoreno** [comment]
Hm ok, let me check.

**Comment by mat-mcloughlin** [comment]
Thanks man, just done some experimenting. Seems the changelog only appears if you have the extension installed. If you don't it says non is available

**Comment by joaomoreno** [comment]
The asset is definitely not in the store:

![image](https://cloud.githubusercontent.com/assets/22350/20962481/c182bc32-bc69-11e6-8843-3eb3efe38708.png)

But when I clone your repo, run `vsce package` and inspect the VSIXManifest, I do see it. It needs to work even from the store.

Did you perhaps add the CHANGELOG.md and republished without bumping up the version? You need to bump the version up before publishing.

**Comment by joaomoreno** [comment]
OK something is definitely wrong here, there's some issue in the Marketplace.

**Comment by mat-mcloughlin** [comment]
@joaomoreno you're typing quicker than me. I checked the install/not installed with the beautify extension too and its the same

**Comment by joaomoreno** [comment]
@hamenon Some asset types seem to not be properly indexed any more.

`vsce` adds a `Microsoft.VisualStudio.Services.Content.Changelog` asset to the VSIX manifest of this extension:

```xml
<?xml version="1.0" encoding="utf-8"?>
<PackageManifest Version="2.0.0" xmlns="http://schemas.microsoft.com/developer/vsx-schema/2011" xmlns:d="http://schemas.microsoft.com/developer/vsx-schema-design/2011">
  <Metadata>
    <Identity Language="en-US" Id="vscode-elixir" Version="0.1.1" Publisher="mjmcloug"/>
    <DisplayName>vscode-elixir</DisplayName>
    <Description xml:space="preserve">Elixir support for VSCode</Description>
    <Tags>Elixir,syntax,snippet,elixir,__ext_.ex,__ext_.exs,Eex,eex,__ext_.eex,HTML (Eex),__ext_.html.eex</Tags>
    <Categories>Languages</Categories>
    <GalleryFlags>Public</GalleryFlags>
    <Badges></Badges>
    <Properties>
      <Property Id="Microsoft.VisualStudio.Code.Engine" Value="^0.10.1" />
      <Property Id="Microsoft.VisualStudio.Code.ExtensionDependencies" Value="" />
      
        <Property Id="Microsoft.VisualStudio.Services.Links.Source" Value="https://github.com/mat-mcloughlin/vscode-elixir.git" />
        <Property Id="Microsoft.VisualStudio.Services.Links.Getstarted" Value="https://github.com/mat-mcloughlin/vscode-elixir.git" />
        
          <Property Id="Microsoft.VisualStudio.Services.Links.GitHub" Value="https://github.com/mat-mcloughlin/vscode-elixir.git" />
        
      
      <Property Id="Microsoft.VisualStudio.Services.Links.Support" Value="https://github.com/mat-mcloughlin/vscode-elixir/issues" />
      <Property Id="Microsoft.VisualStudio.Services.Links.Learn" Value="https://github.com/mat-mcloughlin/vscode-elixir" />
      
      
      <Property Id="Microsoft.VisualStudio.Services.GitHubFlavoredMarkdown" Value="true" />
    </Properties>
    <License>extension/LICENSE.md</License>
    <Icon>extension/images/logo.png</Icon>
  </Metadata>
  <Installation>
    <InstallationTarget Id="Microsoft.VisualStudio.Code"/>
  </Installation>
  <Dependencies/>
  <Assets>
    <Asset Type="Microsoft.VisualStudio.Code.Manifest" Path="extension/package.json" Addressable="true" />
    <Asset Type="Microsoft.VisualStudio.Services.Content.Details" Path="extension/README.md" Addressable="true" /><Asset Type="Microsoft.VisualStudio.Services.Content.Changelog" Path="extension/CHANGELOG.md" Addressable="true" /><Asset Type="Microsoft.VisualStudio.Services.Content.License" Path="extension/LICENSE.md" Addressable="true" /><Asset Type="Microsoft.VisualStudio.Services.Icons.Default" Path="extension/images/logo.png" Addressable="true" />
  </Assets>
</PackageManifest>
```

But when VS Code queries for it, it only gets these back:

![image](https://cloud.githubusercontent.com/assets/22350/20962481/c182bc32-bc69-11e6-8843-3eb3efe38708.png)

**Comment by siegebell** [comment]
I'm also having a similar issue (vscode commit 7499a9f3c565f4fbe5205e30c8664e5a5a11ae94). After waiting a couple minutes, the changelog does sometimes appear. In contrast to @mat-mcloughlin's experience, the extension did not have to be installed for it to sometimes, arbitrary appear after a while.

Also, if an extension has a changelog and it is loading asynchronously, you should replace the default message, "No Changelog available.", with "Loading Changelog..." (or equivalent).

**Comment by hamenon** [comment]
We have someone from the team looking into it. Will update the thread once we identify the issue.

**Comment by pkuma-msft** [comment]
@joaomoreno I checked the call made by VS Code and don't see the asset type Microsoft.VisualStudio.Services.Content.Changelog specified in the query.

![image](https://cloud.githubusercontent.com/assets/13727302/21007496/27690390-bd63-11e6-88d6-6d305d86880d.png)

The code below seems to have it though..
https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L104

**Comment by joaomoreno** [comment]
Oh I forgot we now list them explicitly [over here](https://github.com/Microsoft/vscode/blob/master/src/vs/platform/extensionManagement/node/extensionGalleryService.ts#L312)! OK fix is on our side then. Thanks for the help!

**Comment by mat-mcloughlin** [comment]
@joaomoreno when can see this released?

**Comment by joaomoreno** [comment]
Soon, either this or next week. It's already fixed in the Insiders.
