### ISSUE TITLE
Plugins reverting to older version after updating Insiders

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#16684]
- VSCode Version:

Version 1.8.0-insider
Commit 7499a9f3c565f4fbe5205e30c8664e5a5a11ae94
Date 2016-12-06T16:09:29.346Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0

- OS Version:

Ubuntu 14.04

Steps to Reproduce:

1. Install [IDEA Keybindings](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings). Update the version of vscode insiders
2. You would see that the version of the extension vert back to 0.1.1 where as the latest version is 0.2.6

**Comment by joaomoreno** [comment]
When you installed IDEA Keybindings in step one, which version was installed?

Now that you have 0.1.1, does Code warn you that there is an available update? If you update the extension, don't you get 0.2.6?

**Comment by thekalinga** [comment]
>>When you installed IDEA Keybindings in step one, which version was installed?

I had 0.2.5

>> Now that you have 0.1.1, does Code warn you that there is an available update?

No. The editor did not

>> If you update the extension, don't you get 0.2.6?

No.. I did not get any notification that the extension update is available, even if I check explicitly using "Check for updates" option.

I got older version continuously.

I had to manually download and install the latest version of the extension from thier github page and install.

**Comment by joaomoreno** [comment]
Did you install 0.1.1 from their github page too?

**Comment by thekalinga** [comment]
No..

**Comment by joaomoreno** [comment]
Moved to k--kato/vscode-intellij-idea-keybindings#51
