### ISSUE TITLE
Please make it possible to disable auto-update for a specific extension

### ISSUE THREAD

**Issue by bmrejen** [microsoft/vscode#166896]
Some of us are using extensions that we paid for once and whose licence have expired. For example, I can use Quokka 1.4.069 but any newer version than that won't work with my configuration. 
It would be great to select specific extensions whose versions should skip auto-update.

**Comment by sandy081** [comment]
Please try the feature `Install Another Version...` - right click on extension to see this action. Installing another version will lock the extension to that version.
