### ISSUE TITLE
Javascript Automatic Imports Stopped Working (Even With Every Other Extension Disabled)

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#166808]
> Does this issue occur when all extensions are disabled?: Yes/No

The built-in Javascript/Typescript extension is required for this feature, so the issue can't be observed with all extensions disabled.

However, I did disable all extensions *except* the built-in JS/TS one, and the issue persisted.

- VS Code Version: 
Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.4.0-126-generic
Sandboxed: No
- OS Version: 
Linux Mint 20.3

Steps to Reproduce:

1. Open a file like:

```
// import { useCurrentUser } from 'src/Contexts';

const NoAccess = () => {
    const currentUser = useCurrentUser();
    // ...
}
```

2. Expect to see a yellow underline under `useCurrentUser` (since its import is missing)
3. Instead, see a gray dotted underline just under the first "u" in `useCurrentUser`
4. When you press `CTRL` `+` `.` expect to see an option to import `useCurrentUser` ... but instead the only Quick fix is "Change spelling to 'currentUser'"

I do have `"checkJs": true,` in my `jsconfig.json`, and automatic imports were working up until a couple updates ago.  I tried installing the latest update, thinking it might fix it, but it did not.

**Comment by machineghost** [comment]
One more detail: when I click the `{ }` in the lower right (on the bottom-most blue bar) it says:

> No jsconfig                           Create jsconfig
> 4.9.3 - Typescript version     Select Version 

That's weird, because I do have a `jsconfig.json` ... in fact, when I click "Create jsconfig" it takes me right to it!

**Comment by mjbvz** [comment]
Can you share a project that demonstrates this issue? 

For the bit about `No jsconfig`: you likely have a jsconfig that does not include the current file. We currently always show a generic `create jsconfig` button to create or open a jsconfig. I'll update the button to instead show `Open jsconfig` or something similar when the file already exists

**Comment by machineghost** [comment]
Unfortunately I just had to reinstall my OS, and I'm still getting things setup (I'm not sure if the issue is even still present on a new OS, new VS Code install, etc.).

As soon as I can I'll post back (either with a sample project, if still reproducible, or by closing the issue, if not).

Thanks!

**Comment by mjbvz** [comment]
Reopening based on #168196

**Comment by mjbvz** [comment]
@machineghost Please share an example project. Right now this sounds like an question about how your project is configured but it's difficult to tell without a simple project to test with

**Comment by machineghost** [comment]
One other strange detail: both projects have the exact same `jsonconfig.json`, in the exact same place (their respective root folders).  However, when I hover over the `{}` in the lower-left, my main project says "No jsonconfig", while the test project says "jsconfig.json".

So, it would seem the presence of some other files in the main project prevents VS Code from finding the (again, identically located) `jsconfig.json` file.  Any thoughts on what files could do that?

**Comment by machineghost** [comment]
If someone could even just point me to the place in VS Code's code  where it decides whether or not to say "No jsconfig.json" ... ie. where it does:

    if(!jsConfig || X) showNoJsConfigMesage();`

that would be super helpful, and I may even be able to debug things from there.

The problem right now is just that "No jsconfig.json" (ie. what the tool tells me) is false, because I have the file ... so whatever I'm doing wrong, it must be in the `X`.  But `X` is currently a black box, so I'm not sure how to fix it.

**Comment by mjbvz** [comment]
It still sounds to me like the file you are working is not considered part of the same jsconfig project. Can you try putting together a minimal example just showing off the structure of your project? It can contain non-sense code

As for the questions:

1. It's difficult to say without seeing the project. However
    - Invalid syntax should only break auto imports if the syntax error means we can't figure out which symbols exist in that file. 
    - A `package.json` should generally only be relevant for auto imports from packages installed under `node_modules`, although it's always possible processing the package.json could cause some errors

2. I'm unable to reproduce this. Here's the exact setup I had. Here I triggered auto import on foo

![Screenshot 2022-12-08 at 4 47 16 PM](https://user-images.githubusercontent.com/12821956/206597197-4cf0e8c0-0f46-48da-9ff5-99798a65dca6.png)

Again it sounds like `index.js` is not being considered part of the correct package.json project

--- 

TypeScript is what actually determine if a file is part of the jsconfig project or not. Debugging this is not going to be easy. 

The error `no jsconfig.json` means that that specific file is not considered part of a jsconfig. The file may still exist on disk, but the current js file is not considered part of it

**Comment by machineghost** [comment]
>Can you try putting together a minimal example just showing off the structure of your project? 

Ok, this is ... weird.

I just realized I never included my `jsconfig.json` (like a moron, sorry) so I went to include it and ... not only do I have my red underline under `foo`, but when I quick fix I get the option to add the import!  But what makes it so strange is, I haven't changed anything in this sample project since I made it (and when I made it I observed an identical problem to the one in my main project).

The only thing I can think of is that I've restarted my machine since then, as I know other similar problems were fixed by people restarting their TS Server inVS Code (I actually tried that earlier, but it didn't fix my problem at the time).

Unfortunately, my main project is still broken ... even though it too has all the files in a `root/src` folder, and it too has:

> "include": ["src/**/*.js", "tests/**/*.js"],

in the `jsconfig.json`.  But between 

> it sounds like index.js is not being considered part of the correct package.json project

and my working example to compare to, I should be able to figure things out.

I'll close this ticket, but for what it's worth it'd be really nice if there was more diagnostic info provided when Intellisense breaks.  Even if VS Code can't tell me why it's breaking, if it can at least say "this is `package.json`'s fault" or `this is Typescript's fault` (or whatever) that would make a big difference.

**Comment by machineghost** [comment]
P.S. Thank you so much for all your help (not to mention all your work on VS Code).

For any future readers coming across this, my main issue (I never figured out my test example issue) turned out to be with the file *not* being in my `include` directive in `jsconfig.json`.  So even if you are sure the file is within that directive's directories, hover your mouse over the VS Code tab and make absolutely sure!
