### ISSUE TITLE
VSCode catches keypress when focus is in the input field of an output of a Notebook Cell 

### ISSUE THREAD

**Issue by Judekeyser** [microsoft/vscode#166851]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version:  macos

On-purpose duplicate of #163646, because the assignee marked it "duplicate" itself but couldn't provide any kind of detail about where is the duplicated original ticket...

Hope someone could answer my question or at least provide a viable reference. In case of doubt, consider this ticket as a gift: now #163646 truly is a duplicate :-) 

Kind regards

**Comment by rebornix** [comment]
thanks for your input and let's track this in https://github.com/microsoft/vscode/issues/137902

**Comment by Judekeyser** [comment]
Thank you !
