### ISSUE TITLE
Customizable ignore tokens for brackets matching

### ISSUE THREAD

**Issue by scnwwu** [microsoft/vscode#166838]
Currently, the brackets matching will ignore standard string, comments and regex tokens, which is good.
I'm writing an extension that supports a custom programming language. The extension provides semantic tokens for custom constants which also need to be ignored during brackets matching.
It would be great if it can ignore a semantic token as long as I map it to a standard token type (string, comment or regex) via semanticTokenTypes in package.json. Or let extension define tokens and semantic tokens that will be ignored during brackets matching. Thanks.

**Comment by ArturoDent** [comment]
@hediet I believe is the owner of this area.

**Comment by scnwwu** [comment]
Unfortunately I'm not able to make it within textmate. It takes some time to parse.

> Are you not able to do it with textmate?
