### ISSUE TITLE
Tab completion fails in certain scopes

### ISSUE THREAD

**Issue by bobbytreed** [Microsoft/vscode#16688]
Not sure if this has been reported, but it is a very odd specific case.

If you create a script (Untitled.ps1) and put one line in it $host.EnterNestedPrompt().
When you run the script you will enter a nested prompt, obviously, at that point if you create any variables you will not be able to tap complete to them.  You can see them with Get-VAriable and you can type them in manually to retrieve them, but tab completion fails.  This only happens with psreadline, if I remove the module while in the nestedprompt, tab completion works.  This can also affect debugging scenarios where you are nested as well.

Thanks

Bobby

**Comment by daviwil** [comment]
This issue was moved to PowerShell/vscode-powershell#362
