### ISSUE TITLE
Don't filter bootstrap_node.js by default

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16686]
- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:10:17.195Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|vscode-docker|PeterJausovec|0.0.7|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|tslint|eg2|0.6.0|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

---

Steps to Reproduce:

1. Step into console.log('something') with `node2`
2. Observe that the debugger stops in bootstrap_node.js

With the default adapter `node` bootstrap_node.js is skipped.

**Comment by chrmarti** [comment]
(Testing #16208)

**Comment by roblourens** [comment]
Did you have some skipFiles or smartStep option set? I don't see 'node' skipping it by default and I don't think we should skip anything by default.

**Comment by chrmarti** [comment]
See https://github.com/chrmarti/skipFiles-test/blob/master/test.js
Steps:
1. Set breakpoint on line 4 of test.js
2. Start debugging
3. Debugger stops on line 4 of test.js
4. Step in
5. a) `node2` steps into bootstrap_node.js (seems to do 2 step ins in one)
5. b) `node` stops at line 5 of test.js, keep stepping in, doesn't stop in bootstrap_node.js

**Comment by roblourens** [comment]
I think node2 is correct. Without skipFiles, `node` can step into bootstrap_node.js, so it should when it's not skipped as well.

**Comment by weinand** [comment]
The just-my-code implementation in `node` was skipping internal modules (because they were missing an absolute path). I've created a [feature request](https://github.com/Microsoft/vscode/issues/16918) for supporting internal modules explicitly.
