### ISSUE TITLE
zsh: command not found: python

### ISSUE THREAD

**Issue by nfsknight** [microsoft/vscode#166874]
Type: <b>Performance Issue</b>

I am an absolute beginner.  I'm trying to code using Python in VS Code but every action is coming back "command not found."  Please advise.  Thank you very much.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|4.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id cf4e1a65-602f-44f4-961a-748b4697f64b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   15	    86	   951	code main
    3	    37	   955	   gpu-process
    0	    12	   956	   utility-network-service
    0	   143	   959	   window (hello.py)
    5	    61	   962	   shared-process
    0	    25	   964	     ptyHost
    0	     0	   974	       /bin/zsh -il
    0	    16	   968	     fileWatcher
    2	     0	  1460	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    41	   963	   extensionHost
    0	    25	  1118	     /private/var/folders/wc/9_1696td2d7gm25j6cg0gydc0000gn/T/AppTranslocation/84AC6CE2-DC76-4559-A6F1-982934778916/d/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/nathanknight/.vscode/extensions/ms-python.vscode-pylance-2022.11.30/dist/server.bundle.js --cancellationReceive=file:41072f50b72e8cbef106d0d2905813ff33207a956c --node-ipc --clientProcessId=963
    0	     4	  1120	     /Library/Frameworks/Python.framework/Versions/3.11/Resources/Python.app/Contents/MacOS/Python /Users/nathanknight/.vscode/extensions/ms-python.isort-2022.8.0/bundled/tool/server.py
    3	    78	  1452	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
material-icon-theme|PKi|4.22.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by rebornix** [comment]
It's likely you don't have Python in PATH.

**Comment by nfsknight** [comment]
Here is my path:

PATH=/usr/local/bin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

It looks like it is in the path. Please advise. Thank you!

Nathan

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
