### ISSUE TITLE
Visual Studio Code frequently opens without window buttons

### ISSUE THREAD

**Issue by chriskuech** [microsoft/vscode#166866]
Type: <b>Bug</b>

Visual Studio Code has recently frequently been opening without the stoplight buttons in the toolbar. The window is also not responsive to the Close Window hotkey. This means that there is no way to close the window. The only way to close the window is to use Force Quit, but even that does not work very effectively.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 6, 6|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|. --crash-reporter-id f310298e-b212-47d6-946f-d87af402c8cc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (41)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.15.2
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
prettier-vscode|esb|9.9.0
codespaces|Git|1.13.1
copilot|Git|1.61.7372
remotehub|Git|0.46.0
vscode-pull-request-github|Git|0.54.1
vscode-mocha-test-adapter|hbe|2.14.1
vscode-test-explorer|hbe|2.21.1
svg|joc|1.4.23
azure-dev|ms-|0.3.0
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-azurestorage|ms-|0.15.0
vscode-azurevirtualmachines|ms-|0.6.2
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.22.2
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.2
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.0.2
remote-repositories|ms-|0.24.0
test-adapter-converter|ms-|0.1.6
vscode-node-azure-pack|ms-|1.1.1
vscode-jest|Ort|4.6.0
vscode-yaml|red|1.10.1
vscode-3dviewer|sle|0.2.2
vscode-styled-components|sty|1.7.5
vscode-mdx|uni|1.0.3
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by sbatten** [comment]
Is the window responsive otherwise? Meaning you can interact with the window but are having difficulty closing it.

**Comment by chriskuech** [comment]
@sbatten is there any more info I can provide? This happens at least daily.

**Comment by sbatten** [comment]
@deepak1556 is there a known issue on the electron side? doesn't seem like something we would control?

@chriskuech what locale is your machine configured?

**Comment by chriskuech** [comment]
@sbatten I am en-us.

I believe both Discord and Slack are Electron and have not observed the same issue there.

**Comment by sbatten** [comment]
You are right that they are Electron, but I don't know the version they use. I think I need @deepak1556 to point me in the right direction to figure this one out.

**Comment by chriskuech** [comment]
Is this possibly related to frame merging? I am _pretty sure_ I have only (inconsistently) observed this when opening VS Code (accidentally) from the dock when it is already running with no windows open. I don't think I've had such a scenario with Discord or Slack that would trigger this.

**Comment by deepak1556** [comment]
Seems related to https://github.com/microsoft/vscode/issues/161586

@chriskuech are you facing a similar usage scenario to https://github.com/microsoft/vscode/issues/161586#issue-1383667662 ? can you share your settings ?

**Comment by chriskuech** [comment]
@deepak1556 this sounds like possible match. What settings can I provide and how?

**Comment by deepak1556** [comment]
I would like to confirm your window related settings, you can share the `settings.json` output in this thread.

**Comment by chriskuech** [comment]
Ah I do see `"window.restoreFullscreen": true,`. I have set it to `false` and will report if I still see the issue. It would be nice to have this supported though.

**Comment by chriskuech** [comment]
Using that setting seems to have helped--I no longer observe this issue daily, but still occasionally observe the issue.

**Comment by deepak1556** [comment]
I will merge this to https://github.com/microsoft/vscode/issues/161586
