### ISSUE TITLE
Walkthrough images load slowly

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166890]
Ref #165846

The SVGs in our built-in walkthroughs load quite slowly—and occasionally not at all—even on a fast machine. This isn't so bad, but it can be far slower on a slower or already-busy computer:

https://user-images.githubusercontent.com/25163139/203137381-9ba3fc55-bfb2-40a0-903f-a0f52b6eeec0.mp4

Wondering if there are any quick wins here. The slight delay makes the whole experience feel sluggish and old.

@esonnino

**Comment by sandy081** [comment]
Moving this to next milestone as part of issue tracking and cleaning for the current milestone as we are close to the release.

**Comment by bhavyaus** [comment]
We updated webviews to be reused instead of recreating for each step (which have svg/markdown media). https://github.com/microsoft/vscode/pull/186267
