### ISSUE TITLE
How do you get a webview?

### ISSUE THREAD

**Issue by ndouba** [Microsoft/vscode#16681]
Hi,

I am interested in developing an extension for VSCode. One thing remains unclear in my research. How
do I create a webview? I was looking at the previewHTML command and it doesn't seem to support 
loading HTML with a base URL. Part of my extension tries to load HTML I am writing under the context
of another base URL (i.e. against a server). In webview there is a loadDataWithBaseUrl function. Is there
any equivalent in vscode?

Cheers,

Nadeem

**Comment by alexandrudima** [comment]
@ndouba Have you checked out https://github.com/Microsoft/vscode-extension-samples

You could register a content provider for a certain scheme "my-scheme" and then run the previewHTML command on the document "my-scheme://hello/world". From the content provider you can then return any arbitrary HTML.

That is what I do e.g. in https://github.com/alexandrudima/vscode-lcov/tree/master/src

**Comment by ndouba** [comment]
That's not really what I want. I'd like the base url to be the website's url so that all resources get loaded from the server. Just the html gets injected by myself.
