### ISSUE TITLE
preferences: float values display validation error

### ISSUE THREAD

**Issue by vince-fugnitto** [microsoft/vscode#166897]
#### Description

The application supports float values for many preferences (ex: `window.zoomLevel`) however if a user hovers over the values a default validation message appears that states that the preference value is invalid:

https://user-images.githubusercontent.com/40359487/203140651-32b34845-6e33-4a3e-9bf6-96a5b6459e75.mp4

The validation message is:

```
Please enter a valid value. The two nearest valid values are x and y.
```

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Ubuntu 20.04

#### Steps to Reproduce:

1. start the application
2. open the preferences-view
3. search for `window.zoomLevel`
4. set the zoom level to a float (ex: 1.5)
5. hover over the input
6. notice the default input validation message

**Comment by rzhao271** [comment]
I confirmed the setting value takes effect, but that there's a hover claiming that the value is erroneous.
