### ISSUE TITLE
Vs Code doesn't launch debugging in WSL2

### ISSUE THREAD

**Issue by Dr-Itachi** [microsoft/vscode#166863]
Windows:
Windows 11
WSL:
WSL 2 Ubuntu 20.04

My Vs code installation doesn't launch debugging no way what i did it didn't work. It builds the project successfully but after that the debug server doesn't launch. It stops after the Prelaunchtask. It works well on my mac using the exact same config. Here is my launch.json

```
"version": "0.2.0",
"configurations": [
{
"name": "Launch",
"type": "cortex-debug",
"request": "launch",
"cwd": "${workspaceRoot}",
"executable": "${workspaceRoot}/build/${workspaceRootFolderName}.elf",
"showDevDebugOutput": "raw",
"servertype": "openocd",
"interface": "swd",
"runToEntryPoint": "main",
"device": "STM32F746ZG",
"configFiles": [
"board/st_nucleo_f7.cfg"
],
"preLaunchTask": "Hermann STM32 : Build",
"svdPath": "${workspaceRoot}/STM32F746.svd"
}
]
}

}
```

**Comment by roblourens** [comment]
Does debugging launch when preLaunchTask is commented out? Maybe this is a watch task that is not ending properly?

**Comment by Dr-Itachi** [comment]
> Does debugging launch when preLaunchTask is commented out? Maybe this is a watch task that is not ending properly?

Sorry. No the debug session doesn't work when prelaunchtask is commented out. The progress bar stops right after i click to the launch button

**Comment by roblourens** [comment]
Please file this on the debug extension that you're using
