### ISSUE TITLE
Extension installation from CLI fails if there is no machine id

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#166837]
`code-insiders --user-data-dir /tmp/user --extensions-dir /tmp/exts --install-extension ms-python.python`

🐛 

```
Installing extensions...
Invalid value "undefined" for header "VSCode-SessionId"
```

Caused by https://github.com/microsoft/vscode/commit/a8909ed194ee2897125db083d8f4eb7ac310eb9f 

CC @isidorn

**Comment by isidorn** [comment]
@sandy081 how should we fix this? If there is no machine-id should we send an empty string?

Also I find it a bit strange that in this case `machineId` is `undefined`.

**Comment by sandy081** [comment]
I think we have to handle the case when there is no machine id and lets fall back to service machine id in this case.

**Comment by bhavyaus** [comment]
Verified scenario of installing without machine id.
