### ISSUE TITLE
Change debugger type in DebugConfigurationProvider

### ISSUE THREAD

**Issue by A2va** [microsoft/vscode#166862]
Currently [xmake-vscode](https://github.com/xmake-io/xmake-vscode) uses the `vscode.debug.startDebugging` function with lldb or cpp tools as debugger extensions.
And for that we have to replace the keybind f5 with a command, I think it is not ideal.

So my idea was to make a custom debug type (xmake) in the package.json, for example like this:

```json
{
	"type": "xmake",
	"configurationAttributes": {
	  "target": {
		"type": "string",
		"description":"the xmake target name"
	  }
	}
}

```
But after some research I figured out that it's not that easy. It need to implement the Debug Adapter Protocol, but xmake doesn't need it as it's based on the cpp tools or lldb extension.

My request is add the possibility to change to debugger type in the configuration provider, like this:

```ts
class XmakeConfigurationProvider implements vscode.DebugConfigurationProvider {

	/**
	 * Massage a debug configuration just before a debug session is being launched,
	 * e.g. add all missing attributes to the debug configuration.
	 */
	resolveDebugConfiguration(folder: WorkspaceFolder | undefined, config: DebugConfiguration, token?: CancellationToken): ProviderResult<DebugConfiguration> {

		const programPath = getProgram(config.target) // Find the program from xmake target
			
		// Set the config type for platform specific or extension (lldb, cpp tools)
        config.type = 'cppdbg'; // or lldb
        config.name = 'Launch';
        config.request = 'launch';
        config.program = programPath;
        config.stopOnEntry = true;

		return config;
	}
}
```

This would allow extensions to propose `launch.json` configurations more adapted to the extension, 
without having to implement DAP because it would be the role of another extension.

**Comment by roblourens** [comment]
I think that is possible, isn't it? What's going wrong?

**Comment by A2va** [comment]
I created a [mock extension](https://github.com/A2va/code-debug-conf-mock) with a new debugger type (`xmake`) in package.json, register this debug configuration like this:
```
const provider = new XmakeConfigurationProvider();
context.subscriptions.push(vscode.debug.registerDebugConfigurationProvider('xmake', provider));
```
And the `resolveDebugConfiguration` function is used to change debugger type,like my previous message.


When I start the extension and try to debug the `xmake` type, I have a error message. But the error message is different between `onDebug` and `onDebugResolve` activations events.
With `onDebug`:

![ondebug](https://user-images.githubusercontent.com/49582555/203342698-fd68b963-dcca-474d-806f-355fe1ffb2fd.png)

With `onDebugResolve`:

![ondebugresolve](https://user-images.githubusercontent.com/49582555/203342795-f62e8e28-5e55-41b1-a341-86e5693bc9b8.png)

So it's this feature not implemented or my mock is wrong ?

**Comment by A2va** [comment]
@roblourens Sorry for the ping, in your last message you seem to say that functionality already exists in code. But I can't get it to work, is it my implementation?

**Comment by A2va** [comment]
I am closing this because I have received all one answer here https://github.com/microsoft/vscode-discussions/discussions/314.
