### ISSUE TITLE
Updates for extension not visible if we check for updates

### ISSUE THREAD

**Issue by thekalinga** [Microsoft/vscode#16682]
- VSCode Version:

Version 1.8.0-insider
Commit a8d5b9281e2118c2a10098098ddaac949ce69fe0
Date 2016-12-06T07:19:06.272Z
Shell 1.4.6
Renderer 53.0.2785.143
Node 6.5.0
- OS Version:
Ubuntu 14.04

Steps to Reproduce:

1. Install any extension, wait for the new version to be published
2. You will not see the update as available.

The extension window still shows the older version. If you uninstall the extension & try to install, you will get newer version.

I faced this issue with [IDEA Keybindings](https://marketplace.visualstudio.com/items?itemName=k--kato.intellij-idea-keybindings) multiple times.

**Comment by joaomoreno** [comment]
The Marketplace may be slow due to caching, but eventually you will get informed that there are updates available.

FYI @hamenon
