### ISSUE TITLE
`satisfies` keyword showing with red underline (and defined as a constant)

### ISSUE THREAD

**Issue by matthew-dean** [microsoft/vscode#166889]
Type: <b>Bug</b>

I have upgraded to TypeScript 4.9.3 in my monorepo. I have restarted both the TypeScript language server and also tried restarting VSCode. However, the "satisfies" keyword is not recognized and is reported as a constant with a value of "any"

<img width="482" alt="Screen Shot 2022-11-21 at 11 00 07 AM" src="https://user-images.githubusercontent.com/414752/203137583-68a07fc3-b6c6-4b96-b759-2522e52bbdea.png">

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 4|
|Memory (System)|32.00GB (0.80GB free)|
|Process Argv|--crash-reporter-id 8883724e-d858-468c-b49a-cf4014a3b2cf|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.0
prettier-vscode|esb|9.9.0
vscode-graphql|Gra|0.8.3
vscode-graphql-execution|Gra|0.1.6
vscode-graphql-syntax|Gra|1.0.5
vscode-mjml|mjm|1.0.5
rust|rus|0.7.9
mdx|sil|0.1.1
svelte-vscode|sve|106.2.0
vscode-lldb|vad|1.8.1
pestfile|xor|0.3.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by hckhanh** [comment]
I think that it's still not up-to-date yet.

**Comment by estrehle** [comment]
Until VSCode upgrades to TypeScript 4.9, you can tell use your workspace version of TypeScript: https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions.

Choosing the workspace version (TypeScript 4.9.3) and restarting VSCode worked for me.

**Comment by matthew-dean** [comment]
Thanks! I had to not only set it in workspace settings AND restart VSCode but also manually change it to point to the workspace.

**Comment by mjbvz** [comment]
Yes this requires using TS 4.9+ in your workspace: https://code.visualstudio.com/docs/typescript/typescript-compiling#_using-newer-typescript-versions

Let me know if you see any issues with TS 4.9+
