### ISSUE TITLE
Ctrl+A does not select file content

### ISSUE THREAD

**Issue by alexkaysersnow** [microsoft/vscode#166888]
Type: <b>Bug</b>

- Open a source file, or text file
- put cursor in any place in the text
- Press Ctrl+A to "select all"

It does not select the text, and shows at the footer "Wainting second key of chord..."

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.75GB (13.24GB free)|
|Process Argv|.\\analytics-integration-plugin-service\\ --crash-reporter-id deddb9d2-b28e-4dab-837a-4a35bb29d174|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
tailwind-docs|aus|2.0.0
vscode-tailwindcss|bra|0.9.1
vscode-eslint|dba|2.2.6
vscode-jest-runner|fir|0.4.59
vscode-pull-request-github|Git|0.54.1
go|gol|0.36.0
vscode-docker|ms-|1.22.2
vscode-edge-devtools|ms-|2.1.1
remote-containers|ms-|0.262.3
vscode-jest|Ort|4.6.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by ArturoDent** [comment]
You may have another keybinding that starts with `Ctrl+A` and has another chord to it, like `Ctrl+A Ctrl+D`.  It may have been added by an extension.

Run the `Developer: Toggle Keyboard Shortcuts Troubleshooting` to investigate.  Or, in the Keyboard Shortcuts editor, enable the `Record Keys` icon to the right and type `Ctrl+A` and see if there is a command that starts with `Ctrl+A` but has more keys that it is waiting for.

**Comment by alexdima** [comment]
This issue has been closed automatically because it needs more information and has not had recent activity. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.

Happy Coding!
