### ISSUE TITLE
Regex search errors with Unicode character class escape + lookaround

### ISSUE THREAD

**Issue by Josh-Cena** [microsoft/vscode#166828]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:22:48.959Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: No

Steps to Reproduce:

Type in `(?![\d*#])\p{Emoji}` in the search box with regex mode on.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/55398995/202928922-e63562c6-7589-4469-88cf-5366798ada6d.png">

Weirdly, both `(?![\d*#]).` and `\p{Emoji}` on themselves work.

**Comment by RedCMD** [comment]
Works fine for me in version `1.72`
![image](https://user-images.githubusercontent.com/33529441/202931626-d7d2cc2e-11cf-485b-b133-1adc3e384d91.png)

**Comment by Josh-Cena** [comment]
I can confirm file search works—only workspace search doesn't. Sorry for not making that clear—I'm surprised they have different behaviors!

**Comment by IllusionMH** [comment]
Editors search is powered by JavaScript (V8) regexp engine as it works with editor model directly, however Workspace search is powered by ripgrep (PCRE2) engine.
You can try to use PCRE2 character classes.

**Comment by andreamah** [comment]
Yes, you'll need to use PCRE2. See here: https://github.com/microsoft/vscode/wiki/Search-Issues#notes-on-regular-expression-support. Does that work for you?

**Comment by Josh-Cena** [comment]
Thanks for the info! Glad to know it's at least working as intended (although the behavior is definitely surprising). I'll figure out the rest myself.
