### ISSUE TITLE
Address "Get Started" naming confusion

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#166885]
Ref #165846

Right now I see:
- `Help` > `Get Started` as a menu entry and command name
- "Get Started" as the tab name when looking at the welcome page
- "Show welcome page on startup" and "Reset welcome page walkthrough progress"
- "Getting Started with VS Code" as a walkthrough name

There's a mix of "Welcome" and "Get Started" usage that makes it hard to differentiate between concepts. We could either revert back to "Welcome" for the welcome page itself or rename it to differentiate from the first walkthrough.

Thoughts @digitarald @bhavyaus @esonnino?

## Examples
<img width="424" alt="CleanShot 2022-11-21 at 10 19 04@2x" src="https://user-images.githubusercontent.com/25163139/203130615-41c65cd6-088f-457f-8c06-df25833aa73e.png">

<img width="200" alt="CleanShot 2022-11-21 at 10 19 12@2x" src="https://user-images.githubusercontent.com/25163139/203130630-23aa1a7e-3efe-40af-adf7-7f784c15a5db.png">

<img width="516" alt="CleanShot 2022-11-21 at 10 19 20@2x" src="https://user-images.githubusercontent.com/25163139/203130641-11d8ac2b-0ab0-4e8b-8e1e-b79459012c7a.png">

<img width="273" alt="CleanShot 2022-11-21 at 10 19 23@2x" src="https://user-images.githubusercontent.com/25163139/203130659-df2cc716-5bcf-47c4-af61-a8df12f55244.png">

<img width="625" alt="CleanShot 2022-11-21 at 10 19 56@2x" src="https://user-images.githubusercontent.com/25163139/203130716-2f01dcb9-5ae8-4c5c-81d2-4e13cce267d4.png">

**Comment by daviddossett** [comment]
@digitarald for historical context on naming here

**Comment by esonnino** [comment]
Yeap..I believe changing the label in the tab to "Welcome" instead of "Get Started" is a good option -
It should say Welcome here:
![image](https://user-images.githubusercontent.com/113370447/203620993-0f7c5ef0-4b10-4402-ac37-b9ee2cd9b864.png)

When the user navigates away from the welcome page, the tab name should change to the walkthrough's name:
(It should say Learn the Fundamentals)
![image](https://user-images.githubusercontent.com/113370447/203621157-5d4495d8-30bf-41b3-93af-dca93690616a.png)

**Comment by digitarald** [comment]
"Welcome" was the old page and we added "Get Started" as new name during development. "Get Started" did fit better for the walkthrough style, was a more action-style verb and used in many other apps. Not sure if more thoughts went into it, as the mockups that started in https://github.com/microsoft/vscode/issues/106717 were before my time and already used "Get Started".

I haven't many users ever get into Get Started or Welcome as command, so renaming would be low risk.

**Comment by bhavyaus** [comment]
Is there a user issue mentioning the confusion? Asking to understand if we also need to account for user keyword search behavior in the command pallet when looking for walkthroughs or the Getting Started page after its been closed.

Currently, most walkthroughs use the "Get Started" terminology - Searching for "Get..." in the command palette surfaces the walkthroughs. I wonder if search terms are influenced by the page on which users first saw the walkthroughs and will the naming change have implications on the keywords to find walkthroughs?

**Comment by daviddossett** [comment]
No specific issue that I know of, I'm just spotting the issue of the strange overloading myself. @digitarald might know if we have any hard data on people searching for the command. But I'd also assume it's quite unlikely compared to going to the "Help" menu, for example.
