### ISSUE TITLE
Abnormally wide gutter when PR branch is checked out and folding is disabled

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#166910]
There are no comments so it shouldn't show a wide gutter:

![image](https://user-images.githubusercontent.com/2193314/203154825-d6085bda-43ea-4355-832e-ef913c7ca496.png)

Version: 1.74.0-insider (user setup)
Commit: fef85ea792f6627c83024d1df726ca729d8c9cb3
Date: 2022-11-21T05:22:37.848Z
Electron: 19.1.3
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

---

Expected (stable):

![image](https://user-images.githubusercontent.com/2193314/203154870-86777873-0f7e-4ebc-b88f-a5bb59f74e37.png)

**Comment by alexr00** [comment]
You get this even when folding is enabled. It looks like once there are comments in a workspace we reserve the gutter space for all editors.
