### ISSUE TITLE
Getting Started: Reset Progress command doesn't exist?

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#166998]
It's in the docs: https://code.visualstudio.com/api/references/contribution-points#Completion-events

> Once a step has been checked off, it will remain checked off until the user explicitly unchecks the step or resets their progress (via the Getting Started: Reset Progress command).

But not in command palette? 
![image](https://user-images.githubusercontent.com/2193314/203405558-864d7373-c085-4883-b251-15979cdfd5d2.png)

**Comment by bhavyaus** [comment]
This was changed to "Developer: Reset WelcomePage Walkthrough Progress"
<img width="465" alt="image" src="https://user-images.githubusercontent.com/25044782/209857496-f76c8c59-0a0c-4531-b50a-84736e2b2481.png">

All of the "Get Started" commands should be under "Get Started" command group. I'll move this back if I can't find a good reason as to why it was moved out.

**Comment by Tyriar** [comment]
Developer makes sense if we don't expect a user to ever need it. It should say get started instead of welcome page though.

**Comment by bhavyaus** [comment]
All the GetStarted tabs have been renamed to Welcome recently. So keeping this as is. 

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/25044782/214969875-2764747f-392a-46bf-b79e-1b4a22751c40.png">

**Comment by sbatten** [comment]
marked as verified because I see the command but I'm not sure if any change actually happened

**Comment by bhavyaus** [comment]
My bad. No changes were made as a part of this bug. Closed it as not planned.
