### ISSUE TITLE
Placeholder text of profile export quickpick needs improvement

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#166940]
![image](https://user-images.githubusercontent.com/6726799/203285320-c139d0f1-aaaa-4554-b29f-713c71c16762.png)

https://github.com/microsoft/vscode/blob/6dba34b79f17b789954a50610bafd70d017dc022/src/vs/workbench/services/userDataProfile/browser/userDataProfileImportExportService.ts#L342

I suggest "Select the profile export destination".

Also, maybe change "Local" to "Local File".

**Comment by sandy081** [comment]
Thanks for the suggestion. I am not sure if **destination** is right term, I would go with **Select the profile export location**

**Comment by sandy081** [comment]
CC @isidorn

**Comment by gjsjohnmurray** [comment]
>  I would go with Select the profile export location

👍 

> Went with Local because, we use same terminology in the remote file picker

On that picker "Local" is sufficient because I'm already thinking about files (and folders). Plus, the title text includes the word "File".
