### ISSUE TITLE
Scrolling speed using double finger in touch pad

### ISSUE THREAD

**Issue by ravi-telspiel** [microsoft/vscode#166931]
Type: <b>Bug</b>

when i edit a file and scroll the file up and down using double finger than its move very fast . I am using wondow 11.
My vs code detaits is:-
Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.01GB free)|
|Process Argv|--crash-reporter-id e89e4f42-256a-4a0e-83ad-df9a7c573ac1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
laravel-extra-intellisense|ami|0.6.2
vscode-intelephense-client|bme|1.8.2
laravel-goto-view|cod|1.3.8
EditorConfig|Edi|0.16.4
laravel-create-view|gli|0.0.6
laravel-blade-wrapper|IHu|1.0.1
vscode-phpfmt|kok|1.0.31
dotenv|mik|1.0.1
notepadplusplus-keybindings|ms-|1.0.7
laravel-goto-components|nao|1.2.0
laravel-blade|one|1.32.0
laravel-extension-pack|one|1.1.0
laravel5-snippets|one|1.15.0
laravel-artisan|rya|0.0.28
vscode-blade-formatter|shu|0.20.2
sonarlint-vscode|Son|3.12.0
php-intellisense|zob|1.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
pyind779cf:30617257
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by alexdima** [comment]
You can try customizing the value `editor.mouseWheelScrollSensitivity`
