### ISSUE TITLE
Code helper process high cpu usage

### ISSUE THREAD

**Issue by shuoli84** [microsoft/vscode#166945]
Type: <b>Bug</b>

I noticed my vs code is slow recently, and in acitiviy monitor, code helper process take about 100% cpu, I troubleshooted the problem, turns out there are around 8k+ history files which "code helper" keeps on stats on them. After delete all of those, "Code helper"'s cpu usage back to normal.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 5, 5|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|--crash-reporter-id e375ec04-becc-43fb-9a2b-9523089c1b92|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
intellij-idea-keybindings|k--|1.5.4
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.2
rust-analyzer|rus|0.4.1294
crates|ser|0.5.10
code-settings-sync|Sha|3.4.3
vim|vsc|1.24.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by shuoli84** [comment]
Problem:
<img width="758" alt="Screenshot 2022-11-22 at 18 09 52" src="https://user-images.githubusercontent.com/3402035/203288642-90d01fc1-8458-4f0e-b34f-9d7b5b58763a.png">

Dtruss:
![Screenshot 2022-11-22 at 18 18 19](https://user-images.githubusercontent.com/3402035/203288835-1d57ec2e-11ee-4bd4-96a4-017b558d6e0c.png)

wc -l 
<img width="160" alt="Screenshot 2022-11-22 at 18 09 59" src="https://user-images.githubusercontent.com/3402035/203288898-2991e322-a5e1-4227-b426-d441cc0f6e96.png">

**Comment by shuoli84** [comment]
Use this command to clear local history
![Screenshot 2022-11-22 at 18 25 05](https://user-images.githubusercontent.com/3402035/203290232-5d722999-99a2-4c9e-a89f-94672c60932c.png)

**Comment by bpasero** [comment]
Can you follow this wiki and post the results back here to understand more about why performance is so bad for you: https://github.com/Microsoft/vscode/wiki/Performance-Issues

Thanks!

**Comment by shuoli84** [comment]
@bpasero 
Can you try this on your machine 
```bash
 cd ~/Library/Application\ Support/Code/User/History && touch {{a..z},{A..Z},{0..99}}.txt
```

**Comment by bpasero** [comment]
Yeah I wonder what process is causing the stat to begin with. I am not aware of code in VS Code that would constantly stat all history entries. It is expected though that the history can grow very large because it contains up to 50 entries for files you make edits to.

**Comment by shuoli84** [comment]
I see. Let me see what I can do.

**Comment by shuoli84** [comment]
Yep, it is an extension called setting sync. https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync.

**Comment by shuoli84** [comment]
@bpasero from the project's github, seems the plugin both not maintained and with high cpu issue, is there any way to add an alert or something on the extension market?

**Comment by bpasero** [comment]
@shuoli84 oh great you figured that out!

@isidorn @alexdima fyi I think there was a recent issue where you also figured out that the extension causes issues.

**Comment by bpasero** [comment]
This is configurable via settings, so I suggest you look there to reduce the number of entries. I am hesitant to change the defaults though as it does not seem to cause issues otherwise. 

![image](https://user-images.githubusercontent.com/900690/204485303-d2f27792-3c26-4d98-a62b-eafb9f12776c.png)

**Comment by shuoli84** [comment]
Got it. I think neither "Max File Entries" nor "Max File size" useful for projects with many small files. I close this for now, "too many files created" is a different issue anyway. Thanks for your time~

**Comment by tamuratak** [comment]
Tracked at #147707
