### ISSUE TITLE
Settings count includes Most Commonly Used twice

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16699]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

There are 5 matches, but 2 of them are the same setting, so the count should be 4:
![screen shot 2016-12-06 at 11 08 03 am](https://cloud.githubusercontent.com/assets/9205389/20939620/5d112a2e-bba4-11e6-8a58-e6a456b2be73.png)

**Comment by chrmarti** [comment]
(Testing #16530)

**Comment by Tyriar** [comment]
I brought this up when we were shown the demo in stand up but didn't communicate to @sandy081, I think most commonly used should just be hidden all together when there is a search term.

**Comment by sandy081** [comment]
I would not like to hide any group if it has matches. This might confuse the user if he expects to see a group which he knows a setting is matched. I rendered the number of settings visible to the user without filtering duplicates. Another option is to have distinct count. I am open to this option too. We can also wait for feedback from the community.

 Thanks

**Comment by chrmarti** [comment]
Sounds all good. I don't consider this a major issue.

**Comment by sandy081** [comment]
Closing this as there is not any complaints with this behaviour.
