### ISSUE TITLE
Quick pick checkbox outline broken rendering

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#166978]
VS Code Insiders, macOS

1. Profiles in activity bad > export
2. Press tab -> notice focus outline moves to quick pick checkbox
3. Focus outline is cutoff on the left 🐛 

![image](https://user-images.githubusercontent.com/1926584/203363645-769ffc87-e6b2-4951-b862-f73e11faa010.png)

**Comment by TylerLeonhardt** [comment]
duplicate https://github.com/microsoft/vscode/issues/203473
