### ISSUE TITLE
Linux: Join line has shortcut Windows + J

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16697]
testing #16545, Linux

The short cut for Join Lines is Window +J. That's quite uncommon on Linux, I haven't see any other shortcuts using that key.

![image](https://cloud.githubusercontent.com/assets/6461412/20939006/7368acae-bbed-11e6-9294-df129b7ca12c.png)

**Comment by rebornix** [comment]
Fixed via https://github.com/Microsoft/vscode/commit/067cf11bf0813352f5fdee3373d658d30de38b2f .

To verifier, please test that we only have key bindings for Join Lines on Mac. For Windows and Linux, you need to bind them yourselves.
