### ISSUE TITLE
Make port number a tab stop in Attach to Port launch snippet (node and node2)

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16694]
Testing #16214 

The port number seems to be a good candidate for a second tab stop (after the name). (Both `node` and `node2` snippets.)

**Comment by isidorn** [comment]
Same as previous one, no strong feeling assiging to @roblourens 
fyi @weinand

**Comment by roblourens** [comment]
Oh wait, is this possible? How do I add a tab stop with a default value of a number in this format?

`"port": "${1:9229}"` will produce a string "9229"

**Comment by weinand** [comment]
I don't think this is possible, and I question whether a tab stop at the `port` value is needed. I never ever had to change the port to something else than the default. 
I suggest to keep this simple...

**Comment by isidorn** [comment]
@roblourens it is possible thanks to @aeschli ingenuity but let's keep this simple

Closing as designed

**Comment by roblourens** [comment]
For future reference, how could you do it?

**Comment by isidorn** [comment]
Actually might not be possible, some combination of ^ which martin interpretes in his json world as you just give him raw content. Try the following, might need some variations
"port": "^${port}"

**Comment by aeschli** [comment]
The variable syntax requires a tabstob-index as well. So its:

`"port": "^${1:port}"`
