### ISSUE TITLE
disable find / replace autifill query

### ISSUE THREAD

**Issue by gastrodon** [microsoft/vscode#166903]
When pressing ctrl+f to open find/replace, it auto-fills the search box with either what's selected, or whatever word the cursor is touching if nothing is selected. I'd love to be able to either disable this, or for it to not happen if text is already in the find box.

A common use case for me is finding some text, doing something, and continuing to other instances of some text. This disrupts this by forcing me to re-enter the same search term every time I want to move on

**Comment by ArturoDent** [comment]
`Editor > Find: Seed Search String From Selection` set to `never`

Same with Search across files if you want to modify the seed behaviour for that, search for `seed` in the Settings.
