### ISSUE TITLE
Every single character typed launches rg.exe which is destroying system performance

### ISSUE THREAD

**Issue by theficus** [microsoft/vscode#166900]
Type: <b>Performance Issue</b>

I have been doing light PowerShell coding work and have found that after every few characters typed my system performance completely tanks. I did an ETW trace of my system and found that within a short span of time (30 seconds), hundreds of rg.exe processes are being launched. Just to make sure this isn't specific to PowerShell, I tried opening a new empty window with no language selected and could once again reproduce this. Even just typing in gibberish caused my system to slow to a crawl and I can observe the creation of hundreds of rg.exe processes.

They all have a command line like this:

`"c:\Users\XXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\node_modules.asar.unpacked\@vscode\ripgrep\bin\rg.exe" --files --hidden --case-sensitive -g **/untitled:Untitled-1 -g !**/.git -g !**/.svn -g !**/.hg -g !**/CVS -g !**/.DS_Store -g !**/Thumbs.db -g !**/QLocal -g !**/obj -g !**/objd -g !/__cacheOutput --no-ignore --follow --no-config --no-ignore-global`

This causes VSCode to be essentially unusable on my system as a result.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (15.20GB free)|
|Process Argv|--crash-reporter-id b766c3b0-53b1-48b7-8318-261d783cda1f|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   107	 35864	code main
    0	   239	 28692	   shared-process
    0	    93	  5492	     ptyHost
    0	     8	 16904	       console-window-host (Windows internal process)
    0	     6	 26828	       C:\Windows\System32\cmd.exe
    0	     8	 33176	       console-window-host (Windows internal process)
    0	     6	 42744	       C:\Windows\System32\cmd.exe
    0	     8	 50736	       console-window-host (Windows internal process)
    0	   132	 52800	       "C:\Program Files\PowerShell\7\pwsh.exe" -NoProfile -ExecutionPolicy Bypass -Command "Import-Module 'c:\Users\XXXX\.vscode\extensions\ms-vscode.powershell-2022.11.0\modules\PowerShellEditorServices\PowerShellEditorServices.psd1'; Start-EditorServices -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2022.11.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\XXXX\.vscode\extensions\ms-vscode.powershell-2022.11.0\modules' -EnableConsoleRepl -StartupBanner '' -LogLevel 'Normal' -LogPath 'c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\logs\1669059186-8fac3a15-ba30-4fd6-aa85-bae17ddea70c1669059184495\EditorServices.log' -SessionDetailsPath 'c:\Users\XXXX\AppData\Roaming\Code\User\globalStorage\ms-vscode.powershell\sessions\PSES-VSCode-35864-813524.json' -FeatureFlags @() "
    0	    81	 26916	     fileWatcher
    0	   285	 32588	   extensionHost
    0	   162	 32752	     "C:\Users\XXXX\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\XXXX\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=32588
    0	   317	 34412	   window (● asdfasdfasdfasdfasdfasdfasdfasdfasdf • Untitled-1 - AdvancedAppManagement - Visual Studio Code)
    0	   171	 34948	   issue-reporter
    0	    29	 40572	   crashpad-handler
    0	    44	 58596	   utility-network-service
    1	   324	 63828	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● asdfasdfasdfasdfasdfasdfasdfasdfasdf • Untitled-1 - AdvancedAppManagement - Visual Studio Code)
|    Folder (AdvancedAppManagement): more than 22174 files
|      File types: yaml(14111) validation(130) md(32) json(11) txt(5) ps1(4)
|                  yml(4) gitignore(3) gitmodules(1)
|                  dockerignore(1)
|      Conf files: launch.json(1) settings.json(1) tasks.json(1) dockerfile(1)
|      Launch Configs: PowerShell;
```

</details>
<details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
midl3-language-server|Ale|0.0.31
vscode-markdownlint|Dav|0.48.1
render-crlf|med|1.6.0
azure-pipelines|ms-|1.208.0
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
sarif-viewer|MS-|3.3.3
remote-containers|ms-|0.262.3
azure-account|ms-|0.11.2
azurecli|ms-|0.5.0
cpptools|ms-|1.13.4
powershell|ms-|2022.11.0
vscode-yaml|red|1.10.1
vscode-icons|vsc|12.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
pyind779cf:30617257
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by roblourens** [comment]
Likely from an extension- You can run the command "Start Extension Bisect" to find out which one

**Comment by theficus** [comment]
Oh, thank you! That was incredibly helpful. The culprit here appears to be sarif-vscode-extension. I've filed a bug against that project.
