### ISSUE TITLE
[C++] final and override keywords are not correctly identified

### ISSUE THREAD

**Issue by rielz** [Microsoft/vscode#1669]
The C++11 specifiers [`final`](http://en.cppreference.com/w/cpp/language/final) and [`override`](http://en.cppreference.com/w/cpp/language/override) are missing in the C++ syntax file.
They are context specific keywords, so they must not always be classified as a keyword.

Ironically they are present in the [C syntax](https://github.com/Microsoft/vscode/blob/master/extensions/cpp/syntaxes/c.plist#L435) file with some checks for the correct context.
This check fails for some cases though. These three are currently missing in Code:

``` c++
class deriv final : base {
    void meth1() final;
    void meth2() override;
}
```
- final and override in class declarations
- final classes ... GitHub seems to be missing that one too :smile:

**Comment by aeschli** [comment]
This issue was moved to textmate/c.tmbundle#32

**Comment by aeschli** [comment]
This issue was moved to atom/language-c#210
