### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by andreas-hellquist-stratsys** [microsoft/vscode#166946]
Type: <b>Bug</b>

When renaming properties in an interface the derived classes are updated as expected. However, where the derived classes are used later on this is not updated.
For example if i have a property called lang with a derived class and use it like this: {{ lang.addCode }} this property will not be updated if I do a F2 rename operation.

export interface Language {
  addCode: string
  back: string
}

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (8.44GB free)|
|Process Argv|--crash-reporter-id 8676e6dc-7b88-40cf-a59d-28401208df75|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vue-peek|dar|1.0.2
vscode-eslint|dba|2.2.6
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
cloudcode|goo|1.20.4
vscode-docker|ms-|1.22.2
remote-containers|ms-|0.262.3
vetur|oct|0.36.1
volar|Vue|1.0.9
html-css-class-completion|Zig|1.20.0

</details>

**Comment by mjbvz** [comment]
Please share a self contained code snippet that demonstrates the issue

**Comment by barkermn01** [comment]
I think this is actually to do with a problem of VSCodes handling of renaming I just cloned a folder into my VSCode project and then renamed it from "master" to an appropriate name on its own,

My Use case I have a path on my system of `c:/git-repos` i have code set to have a window on this Directory,
I then Git Cloned another repo's master branch so the directory was created as `master`,
Click the `master` folder in the Explorer, press F2 wrote a new meaningful name press return
VSCode says in the bottom status bar `renaming master to meaningful name` after about 30 seconds status bar stops but the rename has not happened,

And think this might be a related issue in that VSCode is doing something on Rename that's failing and will cause issues all over the place including the auto code edits.

**Comment by mjbvz** [comment]
Closing as we need info from the original poster about the issue

@barkermn01 Please open a separate issue. This sounds completely unrelated to the original issue

**Comment by andreas-hellquist-stratsys** [comment]
![vscode renaming](https://user-images.githubusercontent.com/111274721/206739348-57e3aa82-41a9-4a38-8da5-e3f87eb5c5ca.gif)

**Comment by mjbvz** [comment]
VS Code doesn't support vue out of the box. Please file this against your vue extension
