### ISSUE TITLE
Debugging c# code on visual studio code

### ISSUE THREAD

**Issue by Cartouche** [Microsoft/vscode#16691]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|xml|DotJoshJohnson|1.6.0|
|php-intellisense|felixfbecker|0.0.12|
|auto-close-tag|formulahendry|0.3.6|
|code-runner|formulahendry|0.6.1|
|beautify|HookyQR|0.6.2|
|csharpextensions|jchannon|1.1.0|
|docomment|k--kato|0.0.8|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|mono-debug|ms-vscode|0.11.0|
|omnisharp|ms-vscode|0.3.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|vscode-icons|robertohuertasm|4.0.5|

---

Steps to Reproduce:

1.
Hi guys
I hope you can help me with this
when i debug a c# code on **visual studio code** it shows me this
![first](https://cloud.githubusercontent.com/assets/3955809/20936754/afa9a18a-bbdb-11e6-9222-24c384ee6de4.PNG)
then this :
![error](https://cloud.githubusercontent.com/assets/3955809/20936764/b83c3376-bbdb-11e6-99ae-c3a27e1c2da9.PNG)

2.
note : when I run the code in the command window with **dotnet run** command it works just fine :)

**Comment by weinand** [comment]
This is a .NET/C# issue.

**Comment by weinand** [comment]
This issue was moved to OmniSharp/omnisharp-vscode#1021
