### ISSUE TITLE
Use common filename in Launch Program snippet's program property (node and node2)

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16693]
Testing #16214

The snippet has `"program": "${workspaceRoot}/Program"`, it would be clearer is it was using something that looks like a common filename: `"program": "${workspaceRoot}/server.js"` with `server.js` selected. This is for both `node` and `node2` adapters.

**Comment by isidorn** [comment]
Assignign to rob, no strong feeling here we should just do it for both node and node2
