### ISSUE TITLE
Improve visual presentation of header area of settings editor

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#16696]
- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:10:17.195Z)
- OS Version: Darwin x64 15.6.0

---

Steps to Reproduce:

1. open user settings
2. see yellow and pink in screenshot

Yellow: The interplay of the grey and white areas don't make it obvious that this is a single editor now. Particularly for users who have experienced the two editors opening in the past.
Pink: The separation between the two sides of the editor is rather subtle. It should be more prominent. Also the use of the shadow seems not to fit nicely in the overall UI design of Code.

![screen shot 2016-12-06 at 10 31 39 am](https://cloud.githubusercontent.com/assets/4674940/20938371/b2890012-bb9f-11e6-98d3-5c46874fed0f.png)

**Comment by sandy081** [comment]
Yellow: Agreed that header part should extend to both the editors to get better visual separation, which was also part of the feedback. Planning this for next set of improvements

Pink: This separation is not something new and is reused from Diff editor. We can bring this up in UX meeting and get it fixed across.

**Comment by sandy081** [comment]
Duplicates #18132
