### ISSUE TITLE
the location of the new terminal icon in the terminal has changed after reinstalling vscode

### ISSUE THREAD

**Issue by bilibili-ayang** [microsoft/vscode#166964]
<img width="592" alt="Snipaste_2022-11-22_22-29-40" src="https://user-images.githubusercontent.com/75017711/203339940-8045570a-bece-4e66-98c8-64b5c642cc03.png">

I have tried to adjust the terminal settings one by one, but they are not adjusted back, I hope you can help me to return the plus sign to its original position, thank you very much!

**Comment by meganrogge** [comment]
`terminal.integrated.tabs.enabled` is the setting you'll need to modify
