### ISSUE TITLE
Suggestions can be equal to typed text

### ISSUE THREAD

**Issue by oiiiiiiii** [microsoft/vscode#166994]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Fedora

Steps to Reproduce:

1.  Set  ``editor.quickSuggestions`` to true for all in settings.json:
```
"editor.quickSuggestions": {
    "other": true,
    "comments": true,
    "strings": true
  },
```
2. In any text file, type a word more than once (for example test test)

When I fully typed the word twice, I get a suggestion that only shows exactly what I have typed already. So the only thing the suggestion does is that when I hit enter, I don't get into a new line but nothing happens (because it triggers the suggestion that makes no difference). I think suggestions shouldn't pop up, if they are'nt different to the already typed text:

![Bildschirmfoto vom 2022-11-22 20-12-18](https://user-images.githubusercontent.com/63345269/203403459-a68450bd-a4bb-4077-8671-d89a20ac5979.png)

**Comment by jrieken** [comment]
> When I fully typed the word twice, I get a suggestion that only shows exactly what I have typed already.

That's because when starting to type the `test` suggestion is computed. You than narrow down on it and therefore have the same suggestion to what's current typed. The `test` suggestion isn't computed when hitting ctrl+space after test. 

> So the only thing the suggestion does is that when I hit enter, I don't get into a new line but nothing happens (because it triggers the suggestion that makes no difference)

You can use the `editor.acceptSuggestionOnEnter` setting for that

**Comment by oiiiiiiii** [comment]
@jrieken why was this issue closed? I mean, yes, you explained why this behavior occurs, but I still think that this is something that should be fixed. I can't be the only person that dislikes this behavior in VSCode. I want to use enter to accept suggestions, I just don't believe it should count as a suggestion, when it is equal to what's already typed. This behavior is especially annoying when typing text like LaTeX or markdown.

**Comment by oiiiiiiii** [comment]
Should I make a feature request out of it instead of a bug report, and it got closed because it's not considered a bug? I just really understand how this is closed as completed.
