### ISSUE TITLE
Receiving "There is no formatter for 'json' files installed. When formatting too quickly.

### ISSUE THREAD

**Issue by Tiptup300** [microsoft/vscode#166988]
If open a new window, quickly choose json as that language, paste my long set of data. Then immediately press Shift+Alt+F, I'll get the message

"There is no formatter for 'json' files installed."

I do have a json formatter that normally works correctly, this is easily reproducible.

**Comment by jrieken** [comment]
Language features are dynamic and statically unknown, so we cannot know if and for how long we should wait. Language services that take a long time are encouraged to show a status message (e.g. TypeScript does that) but it's the first time I hear this about JSON. 

/cc @aeschli
