### ISSUE TITLE
Simplify generated launch.json and set in template mode (node)

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16692]
Testing #16214, related #16171

I think the generated launch.json for Node would be less intimidating if it had only one configuration for "Launch Program" and came up in template mode, like after the snippet was inserted.

**Comment by chrmarti** [comment]
Or use something like the following that works for most simple cases:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Current File",
            "program": "${file}",
            "cwd": "${fileDirname}"
        }
    ]
}
```

Having IntelliSense for the variables would help in customizing it. (#4767)

**Comment by isidorn** [comment]
What I recommend is to try to use a similar approach as the bash debugger, shown nicely in the gif here https://marketplace.visualstudio.com/items?itemName=rogalmic.bash-debug
This has also been the feedback from the user study @stevencl did, that the users are unware that the **program** is the imporant part in the `launch.json`. It would be great if we could experiment with using quick open for letting the user input the program name -> or propose some list.

This is up to the node debug to customize this case -> unassigning myself

**Comment by weinand** [comment]
The generated launch config if a package.json exists:
```js
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/index.js"
        }
```
otherwise:
```js
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${file}"
        }
```
I consider both not "intimidating".
