### ISSUE TITLE
Up arrow on first item in code action menu should loop to the last action

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#166996]
In this state:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/2230985/203404513-9ad0238c-95c0-45fa-9bdf-594ecda52f12.png">

I expect to be able to hit the up arrow to loop around to the last refactor action, but I cannot

**Comment by meganrogge** [comment]
yep @mjbvz looks like this was the previous code before the refactor

https://github.com/microsoft/vscode/pull/164096/files#diff-f6a188697ac6eb9bd9f36073cf00622a9f61c18080f1a7d8f846ba3779457ce0L265-L267

and after, it's https://github.com/microsoft/vscode/blob/9dba5385c7aefebe3756ed413da7fedf1868a71c/src/vs/platform/actionWidget/browser/actionWidget.ts#L82-L83

**Comment by meganrogge** [comment]
actually, that happens here so should be working

https://github.com/microsoft/vscode/blob/9dba5385c7aefebe3756ed413da7fedf1868a71c/src/vs/platform/actionWidget/browser/actionList.ts#L243

**Comment by meganrogge** [comment]
in debugging, none of these actions are getting triggered 🤔 https://github.com/microsoft/vscode/blob/9dba5385c7aefebe3756ed413da7fedf1868a71c/src/vs/platform/actionWidget/browser/actionWidget.ts#L259-L262

**Comment by meganrogge** [comment]
that's because the key input isn't getting sent to the workbench 

https://user-images.githubusercontent.com/29464607/204354927-132fe03e-d48d-466c-8ff9-8220fcae814f.mov
