### ISSUE TITLE
Arrows in code action menu should not stop on titles

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#166997]
1. Have a code action menu with multiple sections, like this:

    <img width="418" alt="image" src="https://user-images.githubusercontent.com/2230985/203404656-feefb750-87d2-43b5-9ec4-e148d0d39df2.png">

2. Hit "down" repeatedly
3. Notice the selection (invisibly) 'selects' the section titles, like "Rewrite..."

I would instead expect the selection to skip over titles. I assume they're selectable for screen readers, is there another way to indicate a section without adding the stop?

**Comment by mjbvz** [comment]
@meganrogge I think this may have been introduced by the refactoring

**Comment by meganrogge** [comment]
I believe same cause as #166996
