### ISSUE TITLE
Profiles icon

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#166983]
Currently we use the Profiles icon for the default profile and for the Profile viewlet that is shown when applying a profile.

![Screenshot 2022-11-22 at 18 08 35](https://user-images.githubusercontent.com/1926584/203377773-19136ac5-f9ce-481a-8709-8001fec0454f.png)
![Screenshot 2022-11-22 at 18 08 41](https://user-images.githubusercontent.com/1926584/203377776-e280413d-5eca-4100-9155-36701886adef.png)

Is there a better icon to use here? This one has the same meaning as the settings gear.
Profiles are about a job to be done - and not about a person (account). So I am a data scientist on Monday but doc writer on Friday...

fyi @sandy081

**Comment by sandy081** [comment]
Following are the notes from the user studies and stand up discussions

1. Profiles icon is not intuitive or appealing to users
2.Profiles feature shall need its own space to indicate.

Since, we want to have its own space for profiles, we shall invest on making the profiles icon more intuitive and appealing. I found this icon in our azure web sites, what do you think?

![image](https://user-images.githubusercontent.com/10746682/208890926-56fd80f5-f163-4730-981c-a55d7a2f0f35.png)

Also, we shall show the same icon for any profile.

**Comment by isidorn** [comment]
@sandy I think the icon you propose on its own might work. But I am worried that putting that icon next to the Account icon would be very confusing. Slightly related - I think the account icon should show the user picture https://github.com/microsoft/vscode/issues/136889 and then it might not be as confusing.

Outlook for mac recently launched profiles and they are using a Globe icon. Not convinced this is a good icon though...
![Screenshot 2022-12-21 at 13 40 18](https://user-images.githubusercontent.com/1926584/208907608-185da926-6eb3-4972-8393-499b29635727.png)

**Comment by isidorn** [comment]
I like @Tyriar idea to use the VS Code icon as the default profile icon. If we can not find a better one.

**Comment by Tyriar** [comment]
Is there an issue tracking the profile icon style?

<img width="80" alt="image" src="https://user-images.githubusercontent.com/2193314/212119712-27f0f835-fb06-40ff-b20c-86a8cedc9e33.png">

**Comment by sandy081** [comment]
> Is there an issue tracking the profile icon style?

What is the issue with the style? I think we can use this issue for any icon related discussion

**Comment by daviddossett** [comment]
Before getting into the icon discussion, wasn't there some talk of this icon not being valuable to people in user studies?

**Comment by Tyriar** [comment]
> What is the issue with the style? I think we can use this issue for any icon related discussion

Explained my concerns in the UX sync; having a button that looks the same on the bottom while correct from a heirarchy perspective looks off. Additionally just swapping that icon to a VS Code icon will still be confusion imo unless it's given some special presentation.

> Before getting into the icon discussion, wasn't there some talk of this icon not being valuable to people in user studies?

@daviddossett as in expose profiles through the settings button? Would the icon appear if you're in a non-default profile?

**Comment by daviddossett** [comment]
@Tyriar IIRC there was some feedback that the icon wasn't all that useful in the activity bar. I'll defer to @isidorn and @sandy081 there since they saw the studies firsthand. It would be good to know before trying to find the perfect icon/visuals.

**Comment by daviddossett** [comment]
Ok I found the quote:

> Participants had trouble noticing the profile activity bar indicator. Most participants did not find the profile short name useful. 

So it was the indicator all up + the value of the shorthand text. The original design actually implied for the option of using color to make this jump out more. But I'm curious if there was any other feedback on having an indicator in the first place. 

<img width="253" alt="CleanShot 2023-01-12 at 14 10 10@2x" src="https://user-images.githubusercontent.com/25163139/212191954-edb6a10e-f8af-4257-bc9f-37cf9735682e.png">

**Comment by isidorn** [comment]
Using colour would help make it noticeable. But my worry is that we use colours for badges. Thus we use colours for actionable things. And this is not actionable.
Maybe we go back to the previous design (of having it smaller compared to activity bar icon) but we use a stronger lines and add contrast to our grayscale icon so it is noticable compared to the activity bar background?

**Comment by daviddossett** [comment]
Yeah, I don't like how we moved to a normal activity bar icon style. It makes it look permanent/not a unique feature.

**Comment by sandy081** [comment]
Another way to find out the current profile is from the hover:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/10746682/218035109-2dfdb3ab-6b07-46a2-b69e-b8ffea619486.png">

**Comment by kieferrm** [comment]
I'm at a point where I'm close to not using profiles anymore. I started out actively using a couple, but I now ended up in a place where I have no idea what profile I'm in for what workspace. I need to explicitly go to the gear icon to find out but since I don't have any need for the gear otherwise I need to explicit remind myself to do so.

For example, below is a VS Code workspace that I created on Thursday. It ended up using the Documentation profile. I speculate the sequence of steps was: I had a local window that used Documentation, I opened a new local window from it, I cloned the repo in the integrated terminal and opened the folder. I don't want to use different themes per profile but without that I'm lost.

<img width="373" alt="image" src="https://user-images.githubusercontent.com/4674940/218565654-d85450ea-65e4-41a1-9189-ee638adcbb5b.png">

**Comment by sandy081** [comment]
<img width="107" alt="image" src="https://user-images.githubusercontent.com/10746682/218873439-18e095c9-5f4e-4728-a162-20eea43ec10a.png">

<img width="91" alt="image" src="https://user-images.githubusercontent.com/10746682/218873598-a9f18243-7760-4ddd-8523-cb86c136a10e.png">

**Comment by sandy081** [comment]
@daviddossett I pushed the mockup with first approach to main and is now available in insiders. Please feel free to play around and provide feedback and also if you have any other options. Thanks.

**Comment by sandy081** [comment]
Default profile will not have overlay

**Comment by esonnino** [comment]
Polished the indicator in the branch above -

@sandy081, if you feel strongly about having the badge and the profile indicator, we can experiment with the profile indicator shift to the left when there's a badge active:

![image](https://user-images.githubusercontent.com/113370447/219521768-4cd93108-fe84-4b41-922d-2f90255cc85c.png)

IMO the badge can stay always on the right side and temporarily vanish while there's a badge on the settings gear :)

**Comment by sandy081** [comment]
Summary:

Profile badge is shown in the same location of other badges and is hidden if there is activity badge.

![image](https://user-images.githubusercontent.com/113370447/219520962-6fe70cca-8265-462c-9611-ca5020fdde26.png)

Closing this issue with above solution. We can always listen to more feedback and open fresh issues.
