### ISSUE TITLE
Windows 10: window not put to foreground in all cases

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#167]
Sometimes the VS Code window just flashes in the task bar but is not stored to the foreground (e.g. when running code again from the command line). See https://github.com/atom/electron/issues/2867

**Comment by bpasero** [comment]
Not fixed, but I created another one for it.

**Comment by elad** [comment]
This isn't the behavior I experience. When I run Code from the command line, it always opens a new window, at least using the recommended way to start it from the command line on Mac OS X.

**Comment by bpasero** [comment]
Maybe file a separate issue for this if you think it is a bug.

**Comment by elad** [comment]
There was an open issue for it (#159), which you closed for being a duplicate of this one...

**Comment by bpasero** [comment]
Well this is about Windows 10

**Comment by elad** [comment]
Right. Issue #159 is a cross-platform issue that happened to be reported on Windows 7. You closed it as a duplicate of this one, which you say is for Windows 10. I'm sure you can see the inconsistency here.

**Comment by bpasero** [comment]
@elad this issue is a general issue on Windows, I would expect it to happen in 7 and 8 too.

**Comment by elad** [comment]
Sorry for the noise, my bad!

**Comment by earonesty** [comment]
Definitely still happens on Windows 10

**Comment by michaelvolz** [comment]
Yep, still happening to me too. Very annoying. Latest Windows 10. Latest VSCode.

**Comment by kmvan** [comment]
Happen in v1.17.
v1.15 is fine.

**Comment by kmvan** [comment]
And I found vsc will normalize show front the window if it's minimize.

**Comment by jamjnsn** [comment]
Still an issue on Windows 10 x64. Makes it very frustrating to use VS Code.

**Comment by the-ress** [comment]
The regression is tracked as #35765
