### ISSUE TITLE
Power Usage

### ISSUE THREAD

**Issue by ConnorMcWard** [microsoft/vscode#167029]
Type: <b>Performance Issue</b>

Significant power usage with my M1 Macbook Air. Even with the app quit it still drains all of my battery quickly and charging is much slower.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 9, 9|
|Memory (System)|8.00GB (0.17GB free)|
|Process Argv|--crash-reporter-id c72f1694-6718-46af-a6f4-2fdd222e2405|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   17	   156	 24169	code main
    0	    74	 24173	   gpu-process
    0	    33	 24175	   utility-network-service
    0	   246	 24176	   window (Get Started)
   10	   156	 24200	   extensionHost
    0	    49	 24308	     /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper --ms-enable-electron-run-as-node /Users/connormcward/.vscode/extensions/ms-python.vscode-pylance-2022.11.30/dist/server.bundle.js --cancellationReceive=file:64ac9669dbe51c371d7ffda87897fc062d64990700 --node-ipc --clientProcessId=24200
    1	   172	 24203	   shared-process
    2	    49	 24207	     ptyHost
    0	     0	 24282	       /bin/zsh -il
    2	    41	 24231	     fileWatcher
    0	     0	 24342	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	    66	 24204	   window (undefined)
    0	    90	 24320	   issue-reporter
```

</details>

**Comment by AIIIN** [comment]
I have the exact same issue on my Windows 10 64 Bit version notebook. Additionally, VS-Code is very slow.

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?
