### ISSUE TITLE
Changing fontSize does impact default settings editor

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16703]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

I was not surprised, but since the instructions specifically asked to test that. (Testing #16530)

Changing fontSize does impact default settings editor (using workspace settings):
![screen shot 2016-12-06 at 11 20 50 am](https://cloud.githubusercontent.com/assets/9205389/20940063/3cb12b56-bba6-11e6-8a3f-97b769b49005.png)

**Comment by sandy081** [comment]
Yes this is expected to impact and that's what asked to testing and thanks for doing that. So this works as designed.
