### ISSUE TITLE
Add More Telemetry for Audio Features

### ISSUE THREAD

**Issue by AFre100** [microsoft/vscode#167027]
To gain insights about inclusivity, D3 is requesting to add more telemetry in order to learn: 

How many _non_-visually impaired vs visually impaired users are using audio features
-How many users, total, have audio features enabled
-Breakdown of which specific audio features are enabled with # of users

There is no rush on this -- it's something we're hoping to learn at some point.

Thanks!

**Comment by AFre100** [comment]
@gino-scarpino Forgot to tag you here in case you wanted to follow :)

**Comment by meganrogge** [comment]
@isidorn have there been requests for this in the past?

**Comment by isidorn** [comment]
@meganrogge no. But the design team would like to understand better how these sounds are used.
I suggest to keep it in the backlog and we add some telemetry data in the future when we find time.

**Comment by meganrogge** [comment]
I can explore this in May

**Comment by AFre100** [comment]
@meganrogge Just wanted to check in to see if you had any updates? Cc @mrleemurray

**Comment by AFre100** [comment]
@meganrogge  (details are on the Teams message w/Lee Murray and myself if that makes sense :)

**Comment by meganrogge** [comment]
@AFre100 I don't see a teams message related to this. Could you please remind us what we are trying to learn from this telemetry?

cc @isidorn

**Comment by meganrogge** [comment]
I looked back at your initial request and while it could be nice to know numbers, I am not sure it would drive anything / change what we're doing. could you give some examples of what we'd do with this information?

**Comment by AFre100** [comment]
Answered on our teams dm — hoping to align on best way forward for one source of truth if you had any recs @meganrogge

**Comment by meganrogge** [comment]
@hediet since you own the `AudioCueService`, I believe you are the one who should add telemetry here - I'm going to add you to the teams chat where the rationale for this is discussed

**Comment by mrleemurray** [comment]
Just for clarification, we want to collect responses to help steer the direction of a new feature we are developing, that includes managing audio settings.

**Comment by hediet** [comment]
When an audio cue is played for the first time since the user started VS Code, we could send telemetry, including
* Which audio cue
* How the audio cue was triggered (a string, e.g. "diffEditor.navigation")
* Whether screen reader mode is turned on (boolean)
   
We could then group the telemetry data by machine id to get the percentages. Would this work for you?

**Comment by mrleemurray** [comment]
That sounds perfect - thanks @hediet
