### ISSUE TITLE
Easier navigation for output channels

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167004]
I use the `view ` quick access really often to open output channels. This is often inconvenient because there are also views and other things with the same name. A quick access just for output channels would be great- or besides that, just a command that opens a quick pick with all the output channels, I don't see anything that does this. Or if there is another way to easily navigate output channels, please let me know.

Also I'd gladly send a PR for this, let me know what you think.

**Comment by sandy081** [comment]
May be the `view` quick access supports filtering a section. For eg: I can type `Output` and it shows all output channels and if type further with a space, it shall filter output channels?

![image](https://user-images.githubusercontent.com/10746682/204292163-e1483c59-1ec5-4db2-8c15-c005cae9a1cb.png)

If you want a specific command, I would be more than happy to accept the PR.

**Comment by roblourens** [comment]
That seems interesting, but I'm not sure it scales/generalizes to all the different things in the "view" quick access. Or if we try to make it work that way, it seems to be inventing a new quick access syntax.

**Comment by sandy081** [comment]
Agreed and might not be worth. Please feel free to contribute a PR for supporting a command to show only output channels and select them 💪

**Comment by sandy081** [comment]
There is a new command `>Output: Show Output Channels` that lists all output channels. Please verify the command works as expected.
