### ISSUE TITLE
Too much fuzzy matching in settings

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16700]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

Search for 'auto', note there are matches that happen to have all the characters in order 'somewhere':
![screen shot 2016-12-06 at 11 14 47 am](https://cloud.githubusercontent.com/assets/9205389/20939855/67a2fef8-bba5-11e6-87d2-bb28a81601d0.png)

**Comment by chrmarti** [comment]
(Testing #16530)

**Comment by sandy081** [comment]
True that fuzzy search is more fuzzy and is good some times and not precise some times. I would see if we can have much different strategy in search settings. Also see how users does the search and adopt to search and provide apt results

**Comment by rebornix** [comment]
![screen shot 2016-12-08 at 3 20 01 pm](https://cloud.githubusercontent.com/assets/876920/21031716/d43f806c-bd59-11e6-9ea8-4d314a4510fc.png)

Sometimes the fuzzy search is too fuzzy like above I search `css`, even if `css` is a section name, it doesn't have more weight than comments.

**Comment by sandy081** [comment]
@rebornix Agreed.
