### ISSUE TITLE
Can not cancel when enabling the second keymap

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#16701]
Testing #16559 

When install the second keymap, users start to know that multiple keymaps may have conflicts. Then they may just regret to install the second keymap, however, we don't have a way for them to cancel the installation.

**Comment by chrmarti** [comment]
Need to look into it to decide if this is easily possible.

**Comment by rebornix** [comment]
@chrmarti it's kind of behavior/ux change. The whole point is letting ppl know the risk before they really install a second keymap but since they can always disable/uninstall any keymap anytime so I think we can release current feature and see ppl's feedback. Not a big deal.

**Comment by chrmarti** [comment]
Will track with the more general #16638
