### ISSUE TITLE
language error

### ISSUE THREAD

**Issue by qiaer** [microsoft/vscode#167031]
Type: <b>Bug</b>

The current language is set to Chinese, and the language of the explorer panel is still English

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 18.7.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (4.43GB free)|
|Process Argv|. --crash-reporter-id 76ea516a-125a-4aff-aa5a-f2aad8db7453|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
vscode-javascript-snippet-pack|aka|0.1.6
vscode-ant-design-vue-helper|ant|1.0.6
goto-alias|ant|0.1.0
iconify|ant|0.4.2
unocss|ant|0.46.5
markdown-preview-github-styles|bie|1.0.1
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
bracket-pair-colorizer|Coe|1.0.62
vscode-svgviewer|css|2.0.0
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
prettier-vscode|esb|9.9.0
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
todo-tree|Gru|0.0.220
headwind|hey|1.7.0
vue-snippets|hol|1.0.4
beautify|Hoo|1.5.0
vscode-htmlhint|HTM|1.0.4
path-autocomplete|ion|1.22.1
search-node-modules|jas|1.3.0
docthis|joe|0.7.1
vscode-gutter-preview|kis|0.30.0
i18n-ally|lok|2.8.1
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
vscode-fileheader|mik|0.0.2
HTMLHint|mka|0.10.0
vscode-less|mrm|0.6.3
vscode-scss|mrm|0.10.0
vscode-language-pack-zh-hans|MS-|1.73.11090913
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
remote-containers|ms-|0.262.3
sublime-keybindings|ms-|4.0.10
vscode-typescript-next|ms-|5.0.202211170
debugger-for-chrome|msj|4.13.0
indent-rainbow|ode|8.3.1
es6-css-minify|olb|3.3.3
nested-comments|phi|3.0.4
vscode-wechat|qin|0.0.6
typescript-hero|rbb|3.0.0
svg-preview|Sim|2.8.3
element-ui-snippets|SS|0.7.2
vscode-stylelint|sty|1.2.3
open-in-browser|tec|2.0.0
codelf|unb|11.7.0
vscode-icons|vsc|12.0.1
volar|Vue|1.0.9
vscode-typescript-vue-plugin|Vue|1.0.9
nodejs-extension-pack|wad|0.1.9
vscode-todo-highlight|way|1.0.5
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the untranslated panel you see is contributed by an extension.

If it isn't, please paste a screenshot.

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/165974

fixed in the next stable build of VS Code targeted this week.
