### ISSUE TITLE
ssh.exe: console device allocation failure - too many consoles in use, max consoles is 32

### ISSUE THREAD

**Issue by yunwu-jnpr** [microsoft/vscode#167096]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:
```
Version: 1.72.2
Commit: d045a5eda657f4d7b676dedbfa7aab8207f8a075
Date: 2022-10-12T22:15:18.074Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19042
Sandboxed: No
```
- OS Version: `Microsoft Windows [Version 10.0.19042.2130]`

I am running into this issue every 2 weeks, and now I found how to to 100% reproduce it:

1. Set `remote.SSH.path` to git provided ssh.exe (downloaded here: https://git-scm.com/download/win).
   You can use msys2 provided ssh.exe as well.
![image](https://user-images.githubusercontent.com/89552663/203628297-f94db8ec-839c-4fd1-acc6-fe48871eeae7.png)
![image](https://user-images.githubusercontent.com/89552663/203628468-c6c8e49e-5a53-4986-b2cf-fef5c77b6908.png)

2. Run the following command in a CMD window:
```
@for /L %i in (1,1,40) do ( start cmd /k D:\tool\git\usr\bin\ssh.exe <ssh-svr> )
```
This will start 40 CMD windows and run `D:\tool\git\usr\bin\ssh.exe <ssh-svr>` in each of them.
(Make sure you have properly configured the ssh config so `ssh.exe` can automatically connect to the server otherwise you have to manually enter username & password 😄 )
You will see `fatal error - console device allocation failure - too many consoles in use, max consoles is 32` in some launched CMD windows.
![image](https://user-images.githubusercontent.com/89552663/203630634-9c8a86d8-327a-4d63-9563-37509a8c0f4a.png)

3. Now start vscode, and you will find it can not make SSH connection anymore.
![image](https://user-images.githubusercontent.com/89552663/203631536-d4d6d6de-4d13-415b-b458-eca00f59ba78.png)

4. Logout some SSH sessions until the total SSH connection is less than 31, then your vscode will be able to make SSH connection again.

5. Now remove `cmd /k` and run the following command again:
```
@for /L %i in (1,1,40) do ( start D:\tool\git\usr\bin\ssh.exe <ssh-svr> )
```
This time `ssh.exe` is directly launched without `cmd.exe`.

6. Then your vscode should be able to make SSH connection this time, even though more than 32 SSH connections are established.

It seems to me that a `cmd.exe` can launch up to only 32 cygwin processes before running into the `too many consoles in use, max consoles is 32` error, and seems all `ssh.exe` started by vscode are launched by  `cmd.exe` so vscode inherits the limitation.
So, can vscode fix this problem by launching `ssh.exe` directly instead of launching `ssh.exe` in a `cmd.exe`?
Thanks.

**Comment by roblourens** [comment]
To me, this says that we might be leaking ssh.exe processes. When this starts happening in vscode and you haven't primed it with that manual command, do you see leftover ssh.exe processes on your system?

Also, when you encounter this, does setting `"remote.SSH.useLocalServer": true` in your settings.json help?

**Comment by yunwu-jnpr** [comment]
Just verified on vscode 1.73.1, `"remote.SSH.useLocalServer": true` fixes the problem.
Add from process tree I am not seeing `cmd.exe` any more.

![image](https://user-images.githubusercontent.com/89552663/205770478-02511d95-9257-453b-82fd-1e7dc3eba6f1.png)

Thanks very much for pointing the fix to me!
