### ISSUE TITLE
A11y_Microsoft Office Developer_Deployment_Deploy to the cloud_Keyboard: keyboard focus not reaching to the "Output window" button.

### ISSUE THREAD

**Issue by divyabharadwaj92** [microsoft/vscode#167056]
"[[Check out Accessibility Insights!](https://accessibilityinsights.io/)] - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:
#A11ySev2; #A11yMAS; #A11yTCS; #Benchmark; #DesktopApp; #Win32; #WCAG2.1.1 - Keyboard; #Visual Studio Code Client; #BM-VisualStudioCodeClient-Win32-Aug2022; #A11yWCAG2.1;

Environment Details:
Application Name: Visual Studio Code
Version: 1.71.2 (user setup)
Extension Name: Teams Toolkit Extension
Windows version: Windows 11
OS build: 25211.1001

Repro Steps:
Launch Visual studio code
Install Teams toolkit
Hit the "Teams Toolkit"
Tab till "Deployment" section and hit enter
Tab till "Deploy to the cloud" and hit enter
Observed that while deploying the keyboard focus never reaches the "output window" button.

Actual Result:
While navigating through keyboard the focus never reaches the "output window" button.

Expected Result:
While navigating with keyboard, the focus should reach to the "Output window" button.

User Impact:
Keyboard user will get confused if the keyboard focus not reaching to the "Output window" button.

Attachment for Reference:

https://user-images.githubusercontent.com/97668149/203562231-3273202a-9993-4811-abf4-ca8766dd713b.mp4

**Comment by meganrogge** [comment]
So this is an issue with the modal dialogue link not being keyboard navigable

**Comment by meganrogge** [comment]
fyi @isidorn

**Comment by isidorn** [comment]
Thanks for the ping. The gist of the issue is that link in the Notifications does not seem to be keyboard navigable.
I find this surprising, I think it should work. @meganrogge can you double check. F1 > focus notifications and then pressing Tab should focus the link.

**Comment by meganrogge** [comment]
I only see a `Show Notifications` command and that does not focus the notification
