### ISSUE TITLE
Inline completions commands UI

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#167042]
We already have `alt+[` for `editor.action.inlineSuggest.showPrevious` and `alt+]` for `editor.action.inlineSuggest.showNext`. 
We currently do not have keybindings for `editor.action.inlineSuggest.acceptNextWord`.

Whatever keybinding we introduce for `acceptNextWord` I am worried users will not discover it. Same as they have not discovered `showPrevious` and `showNext`.

So we either need "super intuitive" shortcuts. Or better UI to advertise these keybindings.

* Consider how to make the current Hover UI (image below) more discoverable. Could this appear as parameterHints - even when the mouse hover is not there? And can it have an X top right to make it easy for users to dismiss it (when users dismiss it only appears on mouse hover from then on).
* Once the Hover UI is more discoverable - tighten it up, so users can discover all the commands and keybindings. Talk to Copilot team and see if they really want a "Open GitHub Copilot" action (I know they are not super passionate about it). Removing it will save space.
* Keep current `alt+[` and `alt+]` shortcuts for previous / next so we do not break existing users. Despite @aeschli great idea
* Use `something+right` for `acceptNextWord`, `something+left` for undo. `something+down` for accept line, `something+up` for undo.
* I suggest that `something` is simply `alt` on mac and `ctrl` on `win/linux`. If we see users hitting the problem that they want to navigate to the left word but that unexpectedly undoes - then we should reconsider. 

Let me know what you think about these suggestions. I see how this is slightly going into inline completions UI overhaul so I would like us to discuss any ideas.

fyi @jrieken @daviddossett 

![Screenshot 2022-11-23 at 11 42 31](https://user-images.githubusercontent.com/1926584/203526908-6b8b8a83-22e2-42fb-abd8-8d4639939d1e.png)

**Comment by jrieken** [comment]
@hediet and I quickly discussed this and figured that a low hanging change should be some kind of info-icon at the end of the ghost text. When hovering over it, it would also just show the current information but at least got a hint

**Comment by isidorn** [comment]
@jrieken I like that. So hovering over the info-icon (or clicking) would show the current inline hover? 
Slightly related: we used to have an info icon in the Debug Console that would render when debugging is offline. So the info icon would explain why objects can not be expanded.

Did you discuss the default keybinding?

![Screenshot 2022-11-24 at 16 58 35](https://user-images.githubusercontent.com/1926584/203826033-0354dc53-e20b-4d68-9bb2-5a65a7dd3ad9.png)

**Comment by svipas** [comment]
Do you guys will make this always visible or configurable via settings? I would like this to be disabled if possible via configuration
