### ISSUE TITLE
Very slow send selected text to terminal

### ISSUE THREAD

**Issue by mrrezaie** [microsoft/vscode#167017]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Windows 10

Steps to Reproduce:

1. select huge scripts (e.g. 470)
2. open the terminal and change to ipython console
3. Terminal > Run Selected Text

Hi, Compared with Spyder [spyder-kernels], sending codes to the console is drastically slow:

https://user-images.githubusercontent.com/38867713/203438453-6516bd33-1052-44c7-93f9-499d70b966ea.mp4

My problem is the pasting/sending, not the execution. I also found several unsolved and closed issues. Any suggestion on how to enhance the vscode terminal?

Thank you in advance.

**Comment by meganrogge** [comment]
what's the value of `terminal.integrated.gpuAcceleration` for you?

**Comment by mrrezaie** [comment]
Hi, this is "on".

**Comment by Tyriar** [comment]
This is a combination of the fact that we use conpty which "renders" the screen a lot, plus we split sent text into chunks to fix a paste issue with a large amount of data:

https://github.com/microsoft/vscode/blob/38ddde8782ac6413a1303f5b1e398e130b536313/src/vs/platform/terminal/node/terminalProcess.ts#L431-L443

We're not planning on improving this on our end currently.

**Comment by mrrezaie** [comment]
Could you at least add an option to send the whole text into one chunk? Then, users can choose an option that fits their project.

**Comment by Tyriar** [comment]
@mrrezaie data was getting truncated for an unknown reason which is so much worse than the current situation.

**Comment by mrrezaie** [comment]
Thanks for your reply. What about conpty? Is there any better renderer (fast and lightweight)?

**Comment by Tyriar** [comment]
@mrrezaie no, but as you update Windows it will get various improvements. It's a shared component that is built by the Windows Terminal team https://github.com/microsoft/terminal

**Comment by mrrezaie** [comment]
@Tyriar Alright 

> data was getting truncated for an unknown reason which is so much worse than the current situation.

I'm sure you experts will find a solution for this. Until then, I have to keep using Spyder. I suggest adding this to your milestone. Based on similar posts, many users are facing this issue. 

Looking forward to seeing improvements in vscode terminal [Run Selected Text].

**Comment by mrrezaie** [comment]
Hi @Tyriar ,

Regarding this issue, I just wanted to show you how a plugin in Sublime Text editor sends the codes to the terminal in two ways and how they work. Please note that the script is the same as my first comment (~700 lines). 

Sample 1:
[https://github.com/randy3k/SendCode/blob/6775b40613bb4911ba0499ff8a600c41f48a62c2/code_sender/sender.py#L265-L285](url)

https://user-images.githubusercontent.com/38867713/205222412-694c1955-ef33-4995-9ea9-5900ef18c858.mp4

Sample 2:
https://github.com/fredcallaway/SendCode/blob/c85666f8f6b583c49287d6bf810a7bf5e1127504/code_sender/sender.py#L266-L287

https://user-images.githubusercontent.com/38867713/205222557-5d22f083-36ff-4fbd-bbca-add4dd68478e.mp4

So, the number of chunks may not matter. I attached the counterpart codes as well.

I hope this helps you improve the vscode terminal.

Best,
