### ISSUE TITLE
Unable to build the java file

### ISSUE THREAD

**Issue by Khadeer-Pathan** [microsoft/vscode#167045]
Type: <b>Feature Request</b>

Unable to debug or run the java project. 
In the terminal output reads as "Did you miss installing an extension that provides a corresponding task provider?"

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.18362
Modes:
Sandboxed: No

![image](https://user-images.githubusercontent.com/106058983/203538566-e93dd16a-07dd-4c39-ba96-68b3c8c9b7dc.png)

**Comment by gjsjohnmurray** [comment]
Have you followed instructions at https://code.visualstudio.com/docs/languages/java yet?

**Comment by Khadeer-Pathan** [comment]
> Have you followed instructions at https://code.visualstudio.com/docs/languages/java yet?

Yes, followed every instruction put out there.
