### ISSUE TITLE
Tooling for snippet syntax (variables, choice, placeholders, ...)

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#16702]
Testing - https://github.com/Microsoft/vscode/issues/15875

Is it possible to get intellisense for snippet variables in the 'body' field of snippets? Will make them much more discoverable.

**Comment by jrieken** [comment]
Yeah, at least for those that are statically known.

**Comment by jrieken** [comment]
@aeschli How do I know that a file is a snippet file? I wanna have some custom language tooling for snippet files but it's just json. Does the schema bind to `**/snippets/*.json` or how do you now if it's a snippet or not?

**Comment by jrieken** [comment]
Ok, found it here: https://github.com/Microsoft/vscode/blob/master/extensions/configuration-editing/package.json#L60

**Comment by aeschli** [comment]
We should also start using a file name convention like foo-snippets.json. I'm doing the same now for grammars (java.tmLanguage.json) and themes (*color-theme.json)
