### ISSUE TITLE
[Discussion] Issue management scheme of this repository

### ISSUE THREAD

**Issue by MasterInQuestion** [microsoft/vscode#167069]
Follow-Up: [https://github<i>.</i>com/microsoft/vscode/issues/166767#issuecomment-1321284363](https://github.com/microsoft/vscode/issues/166767#issuecomment-1321284363)

    The issue is rather serious:
    |&#x2A;| [https://github<i>.</i>com/microsoft/vscode/issues/166765](https://github.com/microsoft/vscode/issues/166765)
    ; bad aggregation and pointless spamming.
\
\
=== Somewhat related ===

    [
    |&#x2A;| Please stop closing valid issues "to keep the number of issues (to) a manageable level"
    |&#x2A;| [https://github<i>.</i>com/microsoft/vscode/issues/82095](https://github.com/microsoft/vscode/issues/82095) ]

    [
    |&#x2A;| Issue Grooming - review, categorization, assignment
    |&#x2A;| [https://github<i>.</i>com/microsoft/vscode/issues/38209](https://github.com/microsoft/vscode/issues/38209) ]

**Comment by MasterInQuestion** [comment]
See?
    |&#x2A;| [https://github<i>.</i>com/microsoft/vscode/issues/168025](https://github.com/microsoft/vscode/issues/168025)
    |&#x2A;| [https://github<i>.</i>com/microsoft/vscode/issues/120084#event-6732307758](https://github.com/microsoft/vscode/issues/120084#event-6732307758)

    The topic may not be interesting even somewhat annoying, but without first addressing which: things would be only caught in the loop, worse and worse.

**Comment by TylerLeonhardt** [comment]
I'm sorry I'm not following this issue can you please elaborate?

**Comment by MasterInQuestion** [comment]
My apologies if it appears unclear.
    But I don't know how to make it more clear, other than much repeating the already stated:
    .
    "Issue management scheme of this repository causing serious bad aggregation and pointless spamming."

**Comment by TylerLeonhardt** [comment]
I appreciate the feedback. We work really hard to manage the hundreds of issues that we receive every single day. It's a huge effort on the team to manage these issues (and the existing issues) effectively and make sense of them in a way that enables us to move quickly and work on the most critical issues.

If you do think that 2 issues are not the same, you can always respond in the issue/create a new issue and provide concrete evidence as to why they are not the same and in numerous cases, not always, the issues have been reopened.

Being a large open source project, it's impossible that everyone will be satisfied with our process and our decisions... we have to acknowledge that.

This month is our house keeping iteration https://github.com/microsoft/vscode/issues/168000

**Comment by MasterInQuestion** [comment]
I fear you missed much of the point.
    The issue is not about any particular Issue but the current general management of the Issues.
    Please follow the mentioned links to get the full information.

    I have several ideas, when deployed, I believe: shall significantly help with the situation.

**Comment by TylerLeonhardt** [comment]
I wasn't talking about any particular issue. I was speaking broadly. Our philosophy is all written up here:

https://github.com/microsoft/vscode/wiki/Issue-Grooming

Like I said, we can't make everyone happy... and we do acknowledge when we have it wrong... but generally this process has been good for us and generally pushed the product forward to help the most users we can

**Comment by MasterInQuestion** [comment]
I see.

    I have ideas to improve the situation. But planning which would take time.
    I hope the bot won't have the Issue auto locked before my post.

**Comment by TylerLeonhardt** [comment]
If not, a new issue can always be made. Feel free to share your thoughts.

I hope that you know that we do consider all feedback... but I can't guarantee that the feedback will be implemented.
