### ISSUE TITLE
PowerShell Extension Code Formatting settings being ignored.

### ISSUE THREAD

**Issue by RansomVO** [microsoft/vscode#167014]
Does this issue occur when all extensions are disabled?: Yes (Except PowerShell)

- VS Code Version: 1.73.1
- OS Version: Windows 10 Enterprise, build 19044.2006

Steps to Reproduce:

1. Ensure the following Code Formatting settings are enabled in PowerShell extension:
   - New Line After Close Brace
   - New Line After Open Brace
   - Open Brace On Same Line
2. Open file saved/formatted last week:
   ```
   try {
       throw
   }
   catch {
       Write-Host "foobar"
   }
   ```
3. Add an empty line at the bottom and re-save 
The settings are being ignored and the code gets reformatted:
   ```
   try
   {
       throw
   } catch
   {
       Write-Host "foobar"
   }
   ```

![formatter](https://user-images.githubusercontent.com/30580736/203436434-83fea7e0-f731-425f-83af-6b82bcb4bd0a.png)

Any idea what can be done to get this back to working the way it did before I did updates?

**Comment by aeschli** [comment]
You need to file this issue against the Powershell extension: https://github.com/PowerShell/vscode-powershell/issues
