### ISSUE TITLE
Terminal keeps freezing

### ISSUE THREAD

**Issue by mumu-X** [microsoft/vscode#167059]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  When I open IDE I can't type anything in the terminal have tried login and out but still no change
2.

**Comment by meganrogge** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
/label info-needed terminal
