### ISSUE TITLE
Extension view setting links aren't rendered properly

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#167001]
1. Navigate to the Remote - SSH extension
2. Open the Contributions pane
3. Scroll down to the `remote.SSH.enableRemoteCommand`
4. :bug: Links like `#remote.SSH.useLocalServer#` aren't being parsed to markdown links

**Comment by sandy081** [comment]
Yeah this is as designed. Extensions Editor is not equivalent to Settings Editor and there is no desire to make it on par.
