### ISSUE TITLE
Profile Export to GitHub doesn't ask whether the gist it creates should be Public or Secret

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode#167046]
Type: <b>Bug</b>

When I tested this Insiders feature today it created a public gist. I wasn't given a choice about this, nor was I warned in advance.

I suggest that export to GitHub presents an extra quickpick whose prompt text says "What type of GitHub gist should be created?" and whose choices are "Secret" and "Public". I suggest the default (first) choice is Secret. Each choice could have a description line below it giving the kind of clarification that the gist.github.com UI already does:

![image](https://user-images.githubusercontent.com/6726799/203543929-ffb15fce-eb46-4103-925f-21aa9448f012.png)

VS Code version: Code - Insiders 1.74.0-insider (58e7c7b8865e3c3ea77055461ffb5d656a7a46af, 2022-11-23T05:25:25.108Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

**Comment by sandy081** [comment]
CC @isidorn

**Comment by gjsjohnmurray** [comment]
I think it would be safer to start with secret gists. Imagine if I add a profile-specific setting with a sensitive value, then export the profile. At the moment it's not obvious to me that everyone on the internet can access it.

**Comment by gjsjohnmurray** [comment]
I think secret gists (the official term, not "private") are the way to go. Anyone I give the URL to will be able to use it (and anyone **they** pass it on to). And if I do want it listed as public on GH (and become findable by search engines) I can do this at gist.github.com. Once public I can't change it to secret.

**Comment by isidorn** [comment]
Good point, and I agree if that is indeed the case.
