### ISSUE TITLE
tutorial never occurs, missing files...

### ISSUE THREAD

**Issue by WilliamEJBaldwin** [microsoft/vscode#167082]
In the following article, a step-by-step procedure called "Using GCC with MinGW", there seems to be an error... perhaps an update on VSCode or a slight misstep caused this. I am new to compiled languages and C++, trying to compile my first hello world code. After creating directories in Command Prompt, VSCode launches but there is no tutorial that starts and the 3 files that are supposed to be created, tasks.json, launch.json, and c_cpp_properties.json are not created. 

I really just want to be able to use VS Code and run C++ while compiling in bash but it seems like a near impossible task. If someone could help me do EXACTLY THAT, I would be more grateful than a live turkey after Thanksgiving. Below is the link to the article:

[https://code.visualstudio.com/docs/cpp/config-mingw](url)

**Comment by imblowfish** [comment]
Hi, in the article described the following:

```
As you go through the tutorial, you will se three files created in a .vscode folder in the workspace:
- tasks.json (build instructions)
- launch.json (debugger settings)
- c_cpp_properties.json (compiler path and IntelliSense settings)
```

These 3 files will not be created immediately upon opening them with vscode.

`task.json` file will be created here https://code.visualstudio.com/docs/cpp/config-mingw#_run-helloworldcpp in step 4

`launch.json` here https://code.visualstudio.com/docs/cpp/config-mingw#_customize-debugging-with-launchjson

and `c_cpp_properties.json` https://code.visualstudio.com/docs/cpp/config-mingw#_cc-configurations

**Comment by imblowfish** [comment]
I have done the following steps to make it more visual, I hope it will help you in learning C++ using VSCode

After workspace open
![image](https://user-images.githubusercontent.com/28269602/203671356-68254340-3adc-4d85-9d81-756b52c2b4bb.png)

After f5 (first debug run)
![image](https://user-images.githubusercontent.com/28269602/203671521-40b5b1a9-34e9-46e8-9261-44599f05bad6.png)

After C/C++:Edit configuration executions (JSON) execution
![image](https://user-images.githubusercontent.com/28269602/203671642-e5b42582-9675-494b-9366-558e648b1209.png)

And after `Add Debug Configuration` click
![image](https://user-images.githubusercontent.com/28269602/203671733-5cee1ee5-f200-4298-8fc2-c8df5f6fe466.png)

I did it on linux with g++, but on windows and mingw the result should be the same if you set the mingw PATH environment variable correctly

**Comment by roblourens** [comment]
Thanks @imblowfish, if you still have issues @WilliamEJBaldwin you may need to file an issue on the c++ extension repo
