### ISSUE TITLE
Launch widget dropdown gets white background in Windows

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16706]
- VSCode Version: 1.8 insiders dated 12/6
- OS Version: Windows

Steps to Reproduce:

1. Have a launch config with more than 1 config
2. Expand the drop down and hover over the options (all is good)
3. Now continue hovering outside the expanded drop down

Boom: The drop down now has white background

![image](https://cloud.githubusercontent.com/assets/16890566/20940441/9a295a0a-bba7-11e6-98a4-14da6465f4b2.png)

Not sure if this is an electron issue.

Mac is fine

**Comment by isidorn** [comment]
This is a chrome rendering issue which happens inside a VM I believe.
We also changed this a bit but should not improve significantly (i.e. it should not behave as all our other dropdowns)

Closing as there is nothing we can do here. But double check in tomorrows build it might be better

**Comment by ramya-rao-a** [comment]
I was not using a VM while testing.

The previous drop down for debug did not have this issue. Does that make a difference to your assessment?

**Comment by isidorn** [comment]
@ramya-rao-a then you should also not see it in today's insiders. Do you still see it?

**Comment by ramya-rao-a** [comment]
I still see it. Note this is only Windows.

![image](https://cloud.githubusercontent.com/assets/16890566/21024550/caca061c-bd39-11e6-9429-292c1bcf8163.png)

**Comment by isidorn** [comment]
I think there is nothing that can be done here as we can not style them.
Though let me reopen and verify if we can do something in January
