### ISSUE TITLE
Is there a plan to support a full feature for markdown in the tooltip of TreeView item?

### ISSUE THREAD

**Issue by KrabsWong** [microsoft/vscode#167186]
Based on the link https://github.com/microsoft/vscode/blob/6d2920473c6f13759c978dd89104c4270a83422d/src/vs/base/browser/markdownRenderer.ts#L296, limited html tags and attribute can be used with `MarkdownString`.

Is there any plan to extend the MarkdownString features? Such as more html tags, more html attributes (maybe css attributes with style)

It will be helpful to make the complex UI.

**Comment by alexr00** [comment]
There is no plan to expand upon the exiting markdown support.
