### ISSUE TITLE
Search view bubbles up ripgrep ENOENT

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167122]
1. Right click on an editor tab and select Copy Path
2. Paste it into the 'files to include' field
3. Enter any search query
4. :bug: search input validation shows error
![image](https://user-images.githubusercontent.com/30305945/203677719-9e2a9b38-1fbf-424f-818b-119ef923b4d6.png)

**Comment by ArturoDent** [comment]
Related: https://github.com/microsoft/vscode/issues/48958

**Comment by andreamah** [comment]
will track in #167122

**Comment by ArturoDent** [comment]
Nit: you said "will track in https://github.com/microsoft/vscode/issues/167122" which is this issue.

**Comment by andreamah** [comment]
oops, thank you for pointing that out! :')
