### ISSUE TITLE
Can't escape ':' in a snippet variable default value

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16717]
Testing https://github.com/Microsoft/vscode/issues/15875

Have a snippet like

```
"test": {
  "prefix": "test",
  "body": "foo ${TM_SELECTED_TEXT:foo\\:bar} ${TM_SELECTED_TEXT:foo:bar}"
}
```

With no selected text, the result is `foo foo\bar foobar`. I think one of these should insert a `:`, either the escaped one, or colons after the first colon should appear.

**Comment by jrieken** [comment]
The correct syntax should be `${TM_SELECTED_TEXT:foo:bar}`
