### ISSUE TITLE
VSCode crashes without errors when signing in to GitHub or Microsoft

### ISSUE THREAD

**Issue by viv-eth** [microsoft/vscode#167136]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: CentOS 7

Steps to Reproduce:

1. Sign in to account (GitHub or Microsoft)
2. Redicrected to GitHub/Microsoft page
3. Log in
4. VSCode immediately closes without any errors or warnings

**Comment by TylerLeonhardt** [comment]
Can you attach the crash dump following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

seems like a duplicate of https://github.com/microsoft/vscode/issues/167641

**Comment by viv-eth** [comment]
[pending.zip](https://github.com/microsoft/vscode/files/10177769/pending.zip)
Please find attached the error dump

**Comment by viv-eth** [comment]
FYI: I tried version 1.74.0 and the issue still persists.

**Comment by rzhao271** [comment]
Duplicate of #164223
