### ISSUE TITLE
New settings "copy to settings" drop down is clunky

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16711]
#16530

- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T17:07:24.668Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|typescript-javascript-grammar|ms-vscode|0.0.10|
|sass-indented|robinbentley|1.2.1|
|dark-plus-material|vangware|0.1.4|

---

Instead of having a single item dropdown can we just copy the setting over automatically? if necessary could we introduce some way of bringing the user's attention to the right side?

Steps to Reproduce:

1. Open settings
2. Click the pencil icon for `editor.fontSize`
3. Click the copy to settings drop down item

**Comment by chrmarti** [comment]
I think the user will wonder what happened since it's not obvious where to look next.

**Comment by Tyriar** [comment]
Yeah but could we leverage animation or a flash or something to bring the user's attention to the other side so it happens in a single action since they obviously want to copy it to settings if the pencil is clicked.

**Comment by sandy081** [comment]
I liked the way of getting user's attention to the right side. But, showing the action always makes it consistent and will not surprise user when clicked.

**Comment by ramya-rao-a** [comment]
@sandy081 Nothing to verify here right?

**Comment by sandy081** [comment]
@ramya-rao-a You can verify that when action is used to copy/update the setting, updated setting is highlighted
