### ISSUE TITLE
Running a python file

### ISSUE THREAD

**Issue by quixxextra** [microsoft/vscode#167195]
Type: <b>Performance Issue</b>

When I try to run a python file, it does not show me an input in terminal. Have I made a mystake in my code or is it a bug? Here is my code: 
a = int (20)
b = int (30)
input = ("Unesite prvi broj: ")
input = ("Unesite drugi broj: ")
print = ("Rezultat zbira dva broja: ", a + b)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (1.56GB free)|
|Process Argv|--crash-reporter-id c25e48b3-337a-4dda-8c29-52c0e39d5ff1|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    93	  6536	code main
    0	    39	  1320	   utility-network-service
    0	   147	  1992	   extensionHost
    0	   129	  7536	     "C:\Users\Korisnik\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\Korisnik\.vscode\extensions\ms-python.vscode-pylance-2022.11.30\dist\server.bundle.js --cancellationReceive=file:1eddafb27b6e418375783fe7ad5af6e4dc21e82a58 --node-ipc --clientProcessId=1992
    0	    32	 13928	     c:\Users\Korisnik\AppData\Local\Programs\Python\Python311\python.exe c:\Users\Korisnik\.vscode\extensions\ms-python.isort-2022.8.0\bundled\tool\server.py
    0	    10	 13540	       console-window-host (Windows internal process)
    1	    90	  4772	   issue-reporter
    0	   103	 11160	   shared-process
    0	    79	  3660	     fileWatcher
    0	    80	 12296	     ptyHost
    0	     6	  6444	       console-window-host (Windows internal process)
    0	    60	 16596	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	    62	 18348	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 19248	       console-window-host (Windows internal process)
    0	    26	 11572	   crashpad-handler
    0	   188	 11764	   window (calculator.py - Python vjezbe - Visual Studio Code)
    0	   191	 13876	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (calculator.py - Python vjezbe - Visual Studio Code)
|    Folder (Python vjezbe): 8 files
|      File types: py(8)
|      Conf files:;
```

</details>
<details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.9.0
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by chris-thorpe3db** [comment]
From the looks of it, you're making a new variable called `input` twice, and assigning the value `("Unesite prvi broj: ")` to it twice. Try getting rid of the equal sign in the two input statements and the print statement and try running again,

**Comment by quixxextra** [comment]
@chris-thorpe3db  Thank you, it works now!
