### ISSUE TITLE
Black Screen in Terminal after update

### ISSUE THREAD

**Issue by japusoy** [microsoft/vscode#167115]
Type: <b>Bug</b>

Before updating vscode terminal or console is accessible. After update only return black screen in terminal I cant run my programs.

Temporary solution for now is manually open command prompt.

![image](https://user-images.githubusercontent.com/49558772/203665136-de01c3ee-3ca6-42e5-b492-2102f77e4fd9.png)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3598)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.72GB free)|
|Process Argv|--crash-reporter-id 39ad2ffe-5106-4d4d-84de-4dd8c0410293|
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
laravel-extra-intellisense|ami|0.6.2
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
laravel-goto-view|cod|1.3.8
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.9.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
atom-keybindings|ms-|3.0.9
vscode-typescript-next|ms-|5.0.202211170
color-highlight|nau|2.5.0
laravel-blade|one|1.32.0
laravel5-snippets|one|1.15.0
vs-code-prettier-eslint|rve|5.0.4
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-icons|vsc|12.0.1
php-debug|xde|1.29.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal
