### ISSUE TITLE
Test: Debugging Extensions using profiles

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#167140]
Refs: https://github.com/microsoft/vscode/issues/163392

- [x] any @isidorn 
- [x] any @joyceerhl

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167140%0A%0A&assignees=sandy081)

---

1. Open a folder A using default profile and close the window
2. Open any extension folder for debugging and have following launch config
```json
               {
			"name": "Run Extension",
			"type": "extensionHost",
			"request": "launch",
			"args": [
				"--extensionDevelopmentPath=${workspaceFolder}",
				"--log", "debug",
				"--profile-temp"
			],
			"outFiles": [
				"${workspaceFolder}/out/**/*.js"
			],
			"preLaunchTask": "${defaultBuildTask}"
		}
```
3. Start debugging extension - Launch **Run Extension** 
4. Open the first folder A in the extension host debugging window
5. Make sure the folder A is opened in Temp Profile
6. Reload window and make sure the folder A is opened in Temp Profile
7. Open any other folder in this window and make sure the folder is opened in Temp Profile
8. Stop debugging and open folder A again in normal window. Make sure the folder A is opened in its originally associated profile which is default profile here
9. Create a new profile `Debug Profile` that can be used for Extension Host debugging window.
10. Change the above launch, replace `"--profile-temp"` arg with `"--profile=Debug Profile"
11. Repeat steps 3-8 and make sure that Extension Host debugging window is always opened with Debug Profile

**Comment by isidorn** [comment]
Tested on macOS. Works well, nice job 👏
