### ISSUE TITLE
Native Window Controls Overlay with custom Title Bar Style causes title bar to be visible in fullscreen and Zen mode

### ISSUE THREAD

**Issue by jmlane** [microsoft/vscode#167183]
Type: <b>Bug</b>

User settings.json:
```
{
  "window.experimental.windowControlsOverlay.enabled": true,
  "window.titleBarStyle": "custom"
}
```

Toggle fullscreen or Zen mode:
![image](https://user-images.githubusercontent.com/95528/203817972-b5c21c68-546a-4c97-b36a-a9b0d50c6ade.png)

If I switch back to HTML window controls or native title bar style, the title bar is *not* visible in fullscreen or Zen mode.

VS Code version: Code - Insiders 1.74.0-insider (2eca6d38dede985bf6180cca64d43c16a02e9a13, 2022-11-24T05:21:24.237Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900X 12-Core Processor             (24 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (47.47GB free)|
|Process Argv|--crash-reporter-id a0532eb0-46aa-43df-a191-355b643e76b0 --crash-reporter-id a0532eb0-46aa-43df-a191-355b643e76b0 --crash-reporter-id a0532eb0-46aa-43df-a191-355b643e76b0 --crash-reporter-id a0532eb0-46aa-43df-a191-355b643e76b0 --crash-reporter-id a0532eb0-46aa-43df-a191-355b643e76b0|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by rzhao271** [comment]
LGTM without the command center enabled.
Is the titlebar supposed to remain if one has the command center enabled?

**Comment by sbatten** [comment]
@rzhao271 currently yes, that's the design
