### ISSUE TITLE
White screen on elevated startup on RHEL 8

### ISSUE THREAD

**Issue by alexeygritsenko** [microsoft/vscode#167164]
Hi, it works on RHEL 7, but RHEL 8 gives a white screen

- VS Code Version:  1.73.1
- OS Version:  Linux x64 4.18.0-425.3.1.el8.x86_64

Steps to Reproduce:

1. `sudo code --user-data-dir="~/.vscode-root" --no-sandbox`
or `sudo code --no-sandbox --user-data-dir --disable-extensions --disable-gpu`
2. any way gives a white screen
3. also I applied these commands but it didn't help
```
sudo chown root /usr/share/code/chrome-sandbox
sudo chmod 4755 /usr/share/code/chrome-sandbox
```
![code](https://user-images.githubusercontent.com/10233486/203772779-71517b45-9846-44ba-8e24-3d976862e71d.png)

**Comment by mkalbere** [comment]
There are already open&close issues about this, but none with a fully working solution.
I made it work by :close other intance of vscode
code --no-sandbox --user-data-dir=/root/.config/Code --disable-gpu --disable-gpu-sandbox

**Comment by onefreddy** [comment]
@mkalbere it help for me too, thanks!

**Comment by alexeygritsenko** [comment]
@mkalbere it help for me too, thanks!
