### ISSUE TITLE
eslint.autoFixOnSave not working

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#16710]
- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:10:17.195Z)
- OS Version: Darwin x64 15.6.0

---

Steps to Reproduce:
1. testing #16497
2. follow instructions in last bullet of #16497
> enable auto fix on save using the following workspace setting "eslint.autoFixOnSave": true (note as with format on save this is only available if "files.autoSave" is off or on focus lost.). Ensure that fixes are applied on save and that the fixes are applied at the correct positions.
3. use `"files.autoSave": "off"`
3. open `.js` file with too many semicolon such as
```js
let rudi = 'rudi';

function rudi(valdor) {
    return rudi;;;;
}

const bill = 'bill';

bill = rudi;;;;;
```
-> no corrections are applied on save

**Comment by dbaeumer** [comment]
Works for me:

![cast](https://cloud.githubusercontent.com/assets/1931590/21011790/3253354c-bd53-11e6-9c43-9fee25ec7ab3.gif)

Note that you need to set `"eslint.autoFixOnSave": true`

**Comment by sandy081** [comment]
Removing the bug tag since it is not reproducible
