### ISSUE TITLE
Measure Continue On success

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167123]
Events for the following:
1. User picks Continue On
2. User picks a Continue On destination
3. Whether user has uncommitted changes
4. Whether user chooses to sign in with Edit Sessions
5. Whether Continue On destination is successfully selected
7. Whether Edit Sessions is successfully resumed

**Comment by alexr00** [comment]
What's the best way to verify this? Just code review?

**Comment by joyceerhl** [comment]
1. Set Log Level to Trace
2. Open the telemetry output channel
3. Use Continue Working On
4. Verify that telemetry events are logged when Continue Working On is picked, when a development environment is picked, when the user chooses to enable/disable transferring working changes, when the working changes (if any) are successfully stored, and when the working changes are successfully resumed (this last one might be tricky given that the log level in the destination will not be set to trace)

**Comment by bhavyaus** [comment]
Verified telemetry events for all scenarios except - Resuming on VS Code Web from Desktop. VS Code Web keeps reverting to default log levels and I am unable to view telemetry events in this scenario.
