### ISSUE TITLE
keyCode deprecated, what VSCode team are going to use next?

### ISSUE THREAD

**Issue by bmarvinb** [microsoft/vscode#167139]
I looked into hotkey handling implementation, and found that you use "keyCode", that are deprecated, do you have a plan to migrate from it? 
MDN suggest to use "code", but it breaks shortcuts for non-QWERTY layout, like AZERTY. Any suggestions?

**Comment by alexdima** [comment]
Please see https://github.com/microsoft/vscode/wiki/Keybinding-Issues#ecode-ekeycode-and-ekey . We have no plans to move off `.keyCode` on Windows at this moment.
