### ISSUE TITLE
Debug configuration selector is disappeared

### ISSUE THREAD

**Issue by yunyuyuan** [microsoft/vscode#167137]
Does this issue occur when all extensions are disabled?: No

Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T03:54:53.913Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.78-1-MANJARO
Sandboxed: No

Steps to Reproduce:
I tried clicking the right-click of Debug panel header, it shown a menu and I clicked an option(I forgot which I clicked!),then the configuration selector is disappeared,I can't find the settings to open it, for about two hour🥲

1. 
![image](https://user-images.githubusercontent.com/45785585/203724382-b4825554-27d0-44de-9218-4b5acc201414.png)

![](https://code.visualstudio.com/assets/docs/editor/debugging/debugging_hero.png)

**Comment by roblourens** [comment]
@jrieken people keep losing the debug dropdown. I'm not sure what's special about it, but it feels unexpected for it to be hideable and go under a `...` menu. Given that I have no control over the menu itself, is there any way to make this action not hideable? This isn't really like https://github.com/microsoft/vscode/issues/162304 since the custom action view item does represent one real action.

**Comment by yunyuyuan** [comment]
> You can right-click the `...` menu to get it back. However, I don't think that menu should be hideable

#### `...`button
![image](https://user-images.githubusercontent.com/45785585/205786393-65fef26e-aa47-431e-8d75-f63b8941dca2.png)
`...`button only has two action, `Run` is disabled, `Debug Console` is opening Debug Console.
#### right-click
![image](https://user-images.githubusercontent.com/45785585/205786642-14dc091f-814e-4d04-ae6b-c9e9e55f5a5b.png)
right-click only can move or hide `Debug` panel

**Comment by yunyuyuan** [comment]
And this setting has been synced to my other machines😮

**Comment by jrieken** [comment]
Looking at https://github.com/microsoft/vscode/issues/167137#issuecomment-1338599628 make me wonder if this is really customizable menus @roblourens. The item is checked and if customized there should be a "Reset Menu" entry with the overflow. Can there other reasons why this isn't rendered?

**Comment by yunyuyuan** [comment]
@roblourens The project is opened,and **Debug** works well, the problem is I can't switch configuration that inside `launch.json`

![test](https://user-images.githubusercontent.com/45785585/206069340-164d9f84-9239-4650-af2b-1647e09ed12c.gif)

**Comment by roblourens** [comment]
Your gif shows it- once you have a launch.json, then you right click the `...` and it shows that "Start Debugging" is unchecked. Select that and it should show the dropdown

**Comment by yunyuyuan** [comment]
@roblourens Unfortunately,what `Start Debugging` does is start debugging, even I have two configurations!
![test](https://user-images.githubusercontent.com/45785585/206084289-7f4472dc-4694-4bee-9a34-8be32105687d.gif)

**Comment by roblourens** [comment]
Did you right click on that menu or left click?

**Comment by yunyuyuan** [comment]
@roblourens Yes! right click `...` button then I can enable it,thanks a lot
