### ISSUE TITLE
Should TM_DIRECTORY in an untitled file should be '' instead of '.'?

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16712]
Have a snippet like

```
"test": {
  "prefix": "test",
  "body": "foo ${TM_DIRECTORY:bar}"
}
```

In an untitled file, `TM_DIRECTORY` resolves to '.'. Should it be empty, so we can use a default value instead?

**Comment by roblourens** [comment]
Testing https://github.com/Microsoft/vscode/issues/15875

**Comment by ramya-rao-a** [comment]
so now we get `TM_DIRECTORY` as a placeholder in untitled file. Is that the fix?

**Comment by jrieken** [comment]
latest build should be better...

**Comment by ramya-rao-a** [comment]
Now it is empty string when no default is provided.
And default when default is provided.
great, verified.
