### ISSUE TITLE
code does not recognize changes, probably because of caching - powershell

### ISSUE THREAD

**Issue by damnmso** [microsoft/vscode#167220]
Type: <b>Bug</b>

I have a Powershell-Project containing couple of .psm1 and of course a .ps1.
This .ps1 includes the functions of the psm1 with "using module .\file.psm1"
Whenever i change something in the psm1, save it, and run the ps1, the changes are not recognized. Instead, the behaviour is the same as it was before. So this is a caching problem, but i dont know how to disable the cache completely in vscode. my current "workaround" is to always restart vscode, what just sucks.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.69GB (22.28GB free)|
|Process Argv|--crash-reporter-id 99774c76-f8a7-412f-894e-c62471fe053b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
csharp|ms-|1.25.2
powershell|ms-|2022.11.0
pester-test|psp|2022.3.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
pyind779:30617256
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by kilasuit** [comment]
This is nothing to do with VSCode and all to do with the PowerShell Extension & should have been filed in that extensions repo. 

However you can restart current session easily enough using the `PowerShell: Restart Current Session` command as shown in this screenshot
![image](https://user-images.githubusercontent.com/6355225/204239905-4edc527b-c0ea-47ad-8721-57e1deac502b.png)

**Comment by PrzemyslawKlys** [comment]
I believe you could also select this option and it would restart automatically every time

![image](https://user-images.githubusercontent.com/15063294/204240776-6fd5685c-6c4f-4448-a4b7-ff6cfec1394d.png)

**Comment by kilasuit** [comment]
That works if people are actually debugging properly though @PrzemyslawKlys (many aren't - I know I can be in that category from time to time)

**Comment by PrzemyslawKlys** [comment]
Works every time you press F5. If you use CTRL+F5 or run code differently then it won't work of course.

**Comment by damnmso** [comment]
thanks @PrzemyslawKlys - thats exactly what i was looking for :)
