### ISSUE TITLE
Closing Zen Mode on Windows

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#16725]
Testing #15647 

The command palette works super well to exit Zen mode - however for non-command palette users did we consider an action in the editor context to exit Zen Mode.  It's particularly difficult on Windows.

Something here perhaps based on the context. 

![image](https://cloud.githubusercontent.com/assets/1051190/20941501/71bd7c0a-bbab-11e6-9096-2e88d585534d.png)

**Comment by seanmcbreen** [comment]
I do observe that double escape works (eg. lose my selection and then press again) so this could be a non-issue unless we get feedback otherwise.

**Comment by isidorn** [comment]
Closing as designed until users complain.
Also closing vscode and starting again will leave zen mode so I am not worried somebody gets stuck in zen mode forever

**Comment by amod-upadhye** [comment]
There should be an easy to identify graphical button to exit 'Zen Mode'

**Comment by gstarbuck** [comment]
I was stuck in Zen mode until I found this thread via google - ctl-k z does not work to exit zen mode in the version I'm currently running (1.12.2). Double escape works, but is extremely non-obvious...

**Comment by Jeyanthinath** [comment]
It would be better if ctrl+k z works to exit zen mode

**Comment by KrunchMuffin** [comment]
THis needs to be addressed

**Comment by isidorn** [comment]
ctrl+k z works to exit zen mode, I just tried it on windows with latest vscode insiders and it works perfectly for me

https://code.visualstudio.com/insiders

**Comment by rdslw** [comment]
If you have vim plugin installed, neither Esc Esc, nor ctrl+k z works.
There should be menu/other way then keyboard.

**Comment by isidorn** [comment]
@rdslw 
This is the issue with full screen mode in general.
You should always be able to press `F11` to exit full screen mode.
