### ISSUE TITLE
something wrong with the Syntax highlighting (javascript)

### ISSUE THREAD

**Issue by yuanlinssdut** [Microsoft/vscode#1672]
![image](https://cloud.githubusercontent.com/assets/7608992/12013274/21861b5a-ad4e-11e5-925c-e89283f9fb9e.png)

**Comment by bpasero** [comment]
@yuanlin-ssdut more info please

**Comment by ZombieProtectionAgency** [comment]
@bpasero If I had to guess I would think they are talking about the variables highlighting. on line two `$this` should be one color.

**Comment by bpasero** [comment]
Right, my guess too.

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#43
