### ISSUE TITLE
Launch Program in Debug Panel  VSCode Insiders is missing

### ISSUE THREAD

**Issue by dippas** [microsoft/vscode#167254]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.74.0 (insider setup)
- OS Version: Windows 11 Pro - 10.0.22621 Build 22621

Steps to Reproduce:

1. Create a empty folder
2.  Add Node.JS configuration from VSCode (I've tried any config in other of my projects)

Expected:

Show Run Button and  dropdown with configurations choices from `launch.json` 

Screenshot: (VSCode 1.73.1 user setup // VSCode  1.74.0 insider setup)
![image](https://user-images.githubusercontent.com/10220287/204002287-6c297bf2-8011-4e85-b6cc-565c4865b4b4.png)

**Comment by roblourens** [comment]
Can you check the devtools for errors? Help > Toggle Developer Tools

**Comment by roblourens** [comment]
Also did you notice this happen on a certain day in insiders?

**Comment by dippas** [comment]
> Can you check the devtools for errors? Help > Toggle Developer Tools

Here's the screenshot of DevTools

![image](https://user-images.githubusercontent.com/10220287/204160943-6f82dc7e-c7cd-4c29-91cc-9f8482296619.png)

**Comment by dippas** [comment]
> Also did you notice this happen on a certain day in insiders?

Since last week

**Comment by roblourens** [comment]
Strange, I don't know what would cause this. Is it the same for every folder, or is there a different folder where it does appear?

**Comment by dippas** [comment]
Any folder, any project, I have two laptops both with insiders, both w/ same error

**Comment by veeman** [comment]
You guys have probably accidentally hidden the "Start Debugging" box.

Just enable it in the configuration context menu again:
![debug](https://user-images.githubusercontent.com/2372496/205262705-4bca76c4-e012-448f-b24f-b26382af4765.png)

**Comment by dippas** [comment]
> You guys have probably accidentally hidden the "Start Debugging" box.
> 
> Just enable it in the configuration context menu again: ![debug](https://user-images.githubusercontent.com/2372496/205262705-4bca76c4-e012-448f-b24f-b26382af4765.png)

You right but I never touched these settings before so doesn't make sense to me that they are disabled

**Comment by roblourens** [comment]
Thanks @veeman for pointing that out. I will merge this into https://github.com/microsoft/vscode/issues/167137 and I'm not sure that should be hideable.
