### ISSUE TITLE
Allow collapsing & expanding individual comment replies, programmatically and through the UI

### ISSUE THREAD

**Issue by hermannloose** [microsoft/vscode#167256]
Our users would like the ability to collapse replies from earlier code review rounds, to save vertical space taken up by the comment thread widget and focus on the latest replies. While this is less of an issue for short, one-line replies, more complex replies, e.g. containing example code snippets etc. can quickly take up significant parts of the screen. When these replies happened earlier in the conversation, their contents will generally be known to participants or not even be relevant / up-to-date anymore, but they still take up space. Note that addressing #150824 by setting a maximum width for comments to help readability (wrapping e.g. after 100 characters or similar) would likely increase the number of situations in which this becomes relevant.

We think this would probably take the form of a `collapsibleState` property on `vscode.Comment` similar to the existing one on `vscode.CommentThread`, keeping in mind that this should *not* only affect initial expansion state of the comment, see #167253.

In the UI, expanding and collapsing could be available through a rotating expansion chevron.

**Comment by alexr00** [comment]
If folks still want this then I will re-open!
