### ISSUE TITLE
Improved remote file explorer features

### ISSUE THREAD

**Issue by mwomick** [microsoft/vscode#167282]
When deleting large or many files in a remote session, VS Code is very slow. It takes much longer to delete than removing the file(s) via the terminal (_i.e._ with `rm`). It also seems to block use of the file explorer until the files are removed. The program often hangs at this point and I have to restart. It would be nice if the files could be deleted as quickly as removing thru an integrated terminal session. 

Also, when being alerted that a file is too large to open, there are only two options: Configure memory limit or restart VS Code. It would be useful to dismiss this and not open the file.

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/134653
