### ISSUE TITLE
"Copy to Settings" overwrites existing value

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16728]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

Testing #16530

1. Change e.g. fontFamily
2. Click edit icon for fontFamily in default editor
3. Choose "Copy to Settings"
4. Previous value is overwritten with the default

The existing value should not be overwritten. It might improve usability to rename the menu item to "Edit in User Settings" (and "Edit in Workspace Settings"), after all the user already is "in settings" when being shown that menu item.

(Also note that currently 'settings' starts with lowercase 's', when it should start with uppercase 'S' as we're using title casing.)

**Comment by sandy081** [comment]
Good feedback. I think it will also be good if we can say 'Replace in User Settings' when being replaced.
