### ISSUE TITLE
Error removing and changing directory in integrated terminal OhMyZsh with PowerLevel10k theme

### ISSUE THREAD

**Issue by sheikhlimon** [microsoft/vscode#167245]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Zorin OS 16.2

Steps to Reproduce:

1. Removing and changing a directory from inside VSCode integrated terminal: `code -r .`
2. A new VSCode instance will open, with the integrated terminal displaying the error: `job table full or recursion limit exceeded`

![Screenshot from 2022-11-25 18-31-43](https://user-images.githubusercontent.com/76746201/203986766-b02ceb39-1efe-4fe3-a25b-2837700e4069.png)
![Screenshot from 2022-11-25 18-32-06](https://user-images.githubusercontent.com/76746201/203986782-e6c772ca-0388-408e-b643-c658a0a762c5.png)

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by sheikhlimon** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

nope it's still the same

**Comment by sheikhlimon** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

the job table error is not showing but it's not loading ohmyzsh and powerlevel10k theme

![Screenshot from 2022-11-30 17-06-51](https://user-images.githubusercontent.com/76746201/204781009-2de77e13-1d89-45f1-88ed-c0b70638fc9f.png)
