### ISSUE TITLE
Support relative paths as links in output

### ISSUE THREAD

**Issue by damms005** [microsoft/vscode#167211]
Does this issue occur when all extensions are disabled?: Yes/No (Not applicable. An extension that logs paths/url to the Output window is required to reproduce the issue)

- VS Code Version: 1.73.1
- OS Version: Linux (Zorin OS Pro 16).

Steps to Reproduce:

1. Install an extension that logs clickable links/file paths to the Output Window (for example, [Wallaby](https://wallabyjs.com))
2. Trigger an action that makes the extension above log an entry that includes a clickable link/file path to the Output Window
3. Observe that no links/file paths in the Output window is clickable; neither via Ctrl + Click nor Alt + Click

### Expected outcome:

> Notice that the text **Launch Coverage & Test Explorer** is a clickable link

![image](https://user-images.githubusercontent.com/9839355/203912087-d3f405a6-a962-419d-806a-90b9f5525a18.png)

### Actual outcome (bug)

> Notice that the text *​*Launch Coverage & Test Explorer** is not clickable

![image](https://user-images.githubusercontent.com/9839355/203912356-1040a1f0-3217-4bf9-b1b5-c14b3bb8be89.png)

**Comment by bpasero** [comment]
We only support absolute paths that are inside the workspace as links for performance reasons. See also https://github.com/microsoft/vscode/issues/163778 and https://github.com/microsoft/vscode/issues/149153

**Comment by bpasero** [comment]
Any platform. Here is the code that creates the patterns for link detection and the workspace roots are taken as input:

https://github.com/microsoft/vscode/blob/9908b3d5ae12691da5adc2f18e21a100ee8eeb58/src/vs/workbench/contrib/output/common/outputLinkComputer.ts#L31-L44

**Comment by damms005** [comment]
Any clue as to why the same extension, same version, will behave differently? His output window is clickable (as evident in the screenshot above); while I have a different experience. Will tagging him here help?

**Comment by bpasero** [comment]
Sorry I am not sure, @sandy081 @mjbvz or @jrieken do you know if extensions can provide links to output viewer?

**Comment by bpasero** [comment]
Ah yeah thanks, I had forgotten about that API. So it is possible that there is a bug in the extension that only surfaces on some operating systems.

**Comment by smcenlly** [comment]
I'm from the Wallaby team. We had helped @damms005 triage his issue, and yes, we use the the [DocumentLinkProvider](https://github.com/microsoft/vscode/blob/7ae2857bf0d9d0e01512c959afb59414dfab40cb/src/vscode-dts/vscode.d.ts#L4844) API.

@damms005 told us the issue affected all extensions with links, not just ours.

**Comment by bpasero** [comment]
Can you produce a minimal sample in a hello world extension for us to reproduce?

**Comment by damms005** [comment]
@bpasero I am unsure if that request is directed at @smcenlly or myself. However, a hello world extension is not required to reproduce this, IMO. Only two conditions need to be met to reproduce this issue:

1. Anything that writes file paths or URLs to the output window. See the below screenshot of the built-in Git extension. None of those file paths is clickable
2. VS Code running on Linux OS (in my case, specifically Zorin OS Pro. It is based on Ubuntu)

![image](https://user-images.githubusercontent.com/9839355/205327108-8e3355a0-2566-4df5-af54-a42b0471fbd2.png)

**Comment by bpasero** [comment]
A path in the output window is only clickable if it is:
* absolute
* a child of a workspace folder that is opened

**Comment by damms005** [comment]
> From core (without extensions) we only detect and show a link if the path is:
> - absolute
> - a child of a workspace folder that is opened

Only on Linux or across platforms? If across all platforms, what explains the different behaviour on Linux systems?

**Comment by bpasero** [comment]
This is platform independent. I cannot explain platform inconsistencies, but if there is a small sample to play with, I am happy to try.

**Comment by damms005** [comment]
Perhaps I'm unable to communicate this very well, or you choose to not understand the problem. Either ways, I do not see the current direction this is headed as yielding any result.

Thanks for your efforts anyways.

**Comment by damms005** [comment]
For anyone that stumbled on this, the issue was having `"editor.links": false` in my settings.json

**Comment by damms005** [comment]
@bpasero The description for the link says 'Controls whether the editor should detect links and make them clickable'

Since this only affects the Output Window, perhaps the description should be updated to reflect same. It will be helpful in debugging like in my case
