### ISSUE TITLE
Diff editor have no more close button

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#167270]
* disable workbench tabs
* install gitlens
* open a diff editor
* there is so many commands that the split and close button overflow into the secondary menu

<img width="731" alt="Screenshot 2022-11-25 at 16 56 23" src="https://user-images.githubusercontent.com/1794099/204020642-dfc2d753-b1a9-4d29-9bdf-eaf8c8bedcb1.png">

**Comment by jrieken** [comment]
This is technically caused by extension but also annoying. I am building on the new'ish support to hide menu items and such don't count against the limit anymore

**Comment by jrieken** [comment]
To verify:

* follow the steps above
* make sure you can hide item so that split and close appear again

**Comment by sandy081** [comment]
Does the split and close actions shall not be checked?

![image](https://user-images.githubusercontent.com/10746682/205029448-cbc8a3e5-cecd-4d09-a226-5e8733d86d53.png)

**Comment by jrieken** [comment]
The checked state represents the hiding that's done by a user while overflowing is just a space constraint. I believe the activity bar behaves the same
