### ISSUE TITLE
Launch widget dropdown cuts text and has unnecessary scrollbar when zoomed in Windows

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16726]
- VSCode Version: 1.8 insiders dated 12/6
- OS Version: Windows

Steps to Reproduce:

1. Zoom in and open the drop down next to the Launch widget

![image](https://cloud.githubusercontent.com/assets/16890566/20941505/7747141a-bbab-11e6-9d59-259ece73e35b.png)

The first one in the list was "Hello there"

Mac is fine.

This might be electron too

**Comment by isidorn** [comment]
This is native electron behavior when zoomed in. Try out any other native dropdown we have and you should see the same (output)

**Comment by ramya-rao-a** [comment]
Other native dropdowns (the one in Git and Extensions that opens on clicking the ...), use OS settings and have no change when zoomed in.

Only the debug and terminal dropdowns have this issue.

@bpasero Thoughts?

**Comment by bpasero** [comment]
I see the same for the output channels so this seems like general Electron/Chrome behaviour.

**Comment by isidorn** [comment]
@ramya-rao-a Git and Extensions are native context menus not dropdowns. Debug, Terminal and OUtput and native html select elements

**Comment by ramya-rao-a** [comment]
Thanks for the clarification @isidorn . So do we log an issue in electron for this?

**Comment by isidorn** [comment]
@ramya-rao-a you can file an issue to chrome but they might close it as designed. Whatever you prefer.
