### ISSUE TITLE
Find references loosing references in editor

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167296]
Very often I loose the yellow markers in the editor for references, see here for example:

![Recording 2022-11-26 at 08 00 39](https://user-images.githubusercontent.com/900690/204076625-93790e40-225e-424e-8a89-78b5805b4669.gif)

Here I find references of [`path`](https://github.com/microsoft/vscode/blob/fd8c9037af02c02bf0c38af008a69d78f033f942/src/vs/platform/storage/electron-main/storageMain.ts#L420) and quickly dismiss the results of the one file before clicking on the other. Both files were opened before.

**Comment by jrieken** [comment]
Didn't reproduce for me. Please update with repro steps

**Comment by bpasero** [comment]
@jrieken steps
* be in a multi root workspace with `vscode` and `vscode-docs`
* close all editors
* open `storageMain.ts`
* click on [`path`](https://github.com/microsoft/vscode/blob/7af646716e9889ec1736e231cf3f3f037f5b2dbd/src/vs/platform/storage/electron-main/storageMain.ts#L428) of `InMemoryStorageMain` (at the end of the file)
* run `Shift+F12` (I have it bound to `references-view.find` command)
* expand `storageMainService.ts` by clicking it once in the references view
* click the first result
* remove the 2 references by clicking on the X starting from the first
* click on the last result from `storageMain`

🐛 no more highlights in the editor at all

Full video:
![Recording 2022-12-05 at 19 34 41](https://user-images.githubusercontent.com/900690/205715223-9bd6bd1a-66d8-4ce7-8c18-496e7a6f63ee.gif)

**Comment by jrieken** [comment]
@alexr00 When removing the `storageMainService.ts`-entry (all together or all by removing all its children) I am not (always) getting the selection change event.

**Comment by alexr00** [comment]
@jrieken anything special for reproing this? I haven't been able to hit it.

**Comment by alexr00** [comment]
Selection change event should be fixed now.

**Comment by bpasero** [comment]
Thanks 🙏

**Comment by bpasero** [comment]
@jrieken fyi noticing a few behavioural differences now, which maybe we tolerate but users might not:
* clicking on a file name now opens the first reference, previously I believe it was not navigating but just expanding/collapsing (see video 1)
* triggering find references seems to reveal the reference you are on potentially resulting in reveal flicker in some cases (see video 2)

![Recording 2022-12-13 at 08 03 25](https://user-images.githubusercontent.com/900690/207248628-ca0a9bfd-4570-4182-bc34-0c051f81ae98.gif)

![Recording 2022-12-13 at 08 04 56](https://user-images.githubusercontent.com/900690/207248934-4d3a4de1-c2f5-41e4-8f8a-dfa03ccb7bc0.gif)
