### ISSUE TITLE
cannot copy file in remote-ssh and remote-ssh editor

### ISSUE THREAD

**Issue by gland2015** [microsoft/vscode#167215]
Does this issue occur when all extensions are disabled?: Yes/No
yes

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. copy file in remote-ssh and remote-ssh editor
2.

**Comment by gland2015** [comment]
open two remote-ssh window, select a file at file directory and right click , select "copy". then select "paste" at other window. Then you will be prompted that the file cannot be found

**Comment by gland2015** [comment]
> So you're connected to the same server in two windows?

No matter the same, it cannot be copied between windows

**Comment by lramos15** [comment]
Marking as a duplicate of https://github.com/microsoft/vscode/issues/93599 even though it states dragging, the same data transfer issue is the underlying problem here
