### ISSUE TITLE
Fix typo of property AVAILABE --> AVAILABLE

### ISSUE THREAD

**Issue by warrenjokinen** [microsoft/vscode#167284]
Type: <b>Bug</b>

In src\vs\workbench\browser\actions\helpActions.ts :
Two occurrences of (property)
'AVAILABE' should be 'AVAILABLE' .

Housekeeping only:
* RESTORES consistency with existing code in this file
* IMPROVES readability
* DOES NOT CHANGE functionality
* DOES NOT CHANGE performance

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
code-spell-checker|str|2.11.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

(1 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Closing because this should be a PR

**Comment by warrenjokinen** [comment]
Hi Matt thanks for the quick reply.  I submitted this as an issue because I
saw Guidelines online that typo only corrections to code sent as PR‘s is
not recommended.

**Comment by mjbvz** [comment]
@warrenjokinen Yes because typo PR typically aren't worth the cost of reviewing them. But that doesn't mean we want issues about them instead :)
