### ISSUE TITLE
Disable run cell when kernel discovery is in progress or force user to select a kernel

### ISSUE THREAD

**Issue by DonJayamanne** [microsoft/vscode#167213]
* Open a notebook
* the progress indicator is displayed on the kernel status
* however we can still hit the run button and this causes issues
its impossible to tell what kernel was used to run the cell

This is even worse when you have other extensions that contribute to remote jupyter connections,
basically i have no idea what kernel is used when i click the run button

**Suggestions:**
* disable run (not the best option, as some kernles from some extensions are ready to go even if jupyter extension isn't)
* ensure user is forced to pick a kernel , if the user does pick a kernel,. then we should not display the progress message at this stage, instead we should display the kernel selected, After all, the user is now running a cell against a kernel (e.g. .net, julia or nodejs notebook kernel, which is very quick to load)

I believe this is fairly crucial, as i ended up in a broken state due to this. (wrong kernels running the cells)

**Comment by rebornix** [comment]
This was already resolved by showing the active kernel name.
