### ISSUE TITLE
Feature request: Add setting to .code-workspace to specify a Settings Profile

### ISSUE THREAD

**Issue by jerryq27** [microsoft/vscode#167200]
Opening a `.code-workspace` project loads the most recent Settings Profile which isn't always the preferred profile to use. It would be a great addition to add setting to the workspace file to specify a Settings Profile to load when opening the workspace. 

There is a method to specify a profile through the command line using `code ~/projects/pyproject.code-workspace --profile "PyDev"`. However, it would be more convenient to have this automated by being defined in the workspace's file rather than having to remember to open the workspace through the command line with that argument.

```jsonc
{
	"folders": [
		{
			"path": "some/path/to/folder1"
		},
		{
			"path": "some/other/path/to/folder2"
		}
	],
	"settings": {
                // Specify a profile?
                // "settingsProfile": "PyDev"
        }
}
```

**Comment by sandy081** [comment]
Thanks for using profiles feature and giving feedback. This feature is still in preview mode and we do not have plans to work on this specific request. After launching profiles feature, we would collect more feedback and see if this request is wanted y more users and will address this. Until then, I would like to close this feature as out of scope. Thanks.
