### ISSUE TITLE
terminal error

### ISSUE THREAD

**Issue by leoyox** [microsoft/vscode#167206]
Type: <b>Bug</b>

The console suddenly displays garbled codes or character blanks. For example, `hello` is displayed as `h llo` and `e` is not visible.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 21.4.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (57)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
vscode-django|bat|1.10.0
markdown-emoji|bie|0.3.0
regex|chr|0.4.0
doxdocgen|csc|1.4.0
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
auto-close-tag|for|0.5.14
code-runner|for|0.11.8
unicodetochinese|gar|1.0.0
copilot|Git|1.61.7372
go|gol|0.36.0
todo-tree|Gru|0.0.220
kite|kit|0.147.0
vscode-language-pack-zh-hans|MS-|1.73.11090913
vscode-dotnet-runtime|ms-|1.6.0
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.0.2
vsliveshare|ms-|1.0.5776
nocalhost|noc|0.6.18
korofileheader|OBK|4.9.1
indent-rainbow|ode|8.3.1
prisma|Pri|4.6.1
vscode-p3c|Rec|0.1.2
fabric8-analytics|red|0.3.6
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
rust-analyzer|rus|0.3.1293
django-intellisense|sha|0.0.2
sonarlint-vscode|Son|3.12.0
pdf|tom|1.2.0
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-pack|vsc|0.25.6
vscode-maven|vsc|0.39.2
vscode-icons|vsc|12.0.1
snippet|vsc|0.9.0
volar|Vue|1.0.9
vscode-proto3|zxh|0.5.5

(3 theme extensions excluded)

</details>

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed
