### ISSUE TITLE
Clicking elsewhere doesn't always make a context menu disappear

### ISSUE THREAD

**Issue by h-h-h-h** [microsoft/vscode#167392]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0-insider
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Make some context menu appear: from a buffer, the left sidebar, the status bar, the workspace-search textbox, the title bar (not the system menu in the area of the app icon).
2. Click on the title bar anywhere where the centered text is or on the free space to the left or right of it. This doesn't work to hide the context menu, as one would expect (not even the one *shown* by clicking in the area). Strangely, clicking further to the left or right towards where I described works (e.g., on the menu bar texts, but not on the app icon).

**Comment by sbatten** [comment]
This is a known issue and limitation in electron. These click events are taken by the OS (as they control dragging the window)
