### ISSUE TITLE
la page de code mon code ne repond pas 

### ISSUE THREAD

**Issue by 22balde** [microsoft/vscode#167330]
Type: <b>Bug</b>

j'ai tapé un petit bout de code et j'essaye de l'executer sur google chrome et ça m'affiche (cette page ne repond pas ) et pourtant j'ai tout fait j'ai nettoyé le chrome /j'ai vidée les caches toujous rien ou peut etre ça de visual studio....  

<!DOCTYPE html>
<html>
    <head>
      <title>bling bling</title>
      <script src="script.js"></script>
    </head>
    <body>
      
    </body>
</html>

var number = 0; 

while(number <3);
{
    console.log(number);
    number++;
}

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.88GB (0.90GB free)|
|Process Argv|--crash-reporter-id ba579720-d910-47c1-9cff-9c06c8fca17f|
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.73.11090913
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by okobsamoht** [comment]
hello.
vous pouvez nous donner plus de tails et le tout le contenu des fichier?
- le fichier html
- le fichier js
si possible vous pouvez les mettre sur un depot git et partager le lien pour qu'on puisse reproduire le bug.
