### ISSUE TITLE
OnEnterRule: outdent current line

### ISSUE THREAD

**Issue by siegebell** [Microsoft/vscode#16735]
`OnEnterRule` should allow for the *current* line to be outdented, not just subsequent lines.

Either:
1. extend `IndentAction` with `OutdentCurrent`;
2. extend `IndentationRule` with `decreaseCurrentIndentPattern`; or
3. extend `IndentAction` with `command`, which accepts a command name that is to be registered to a function that accepts the current editor, position where enter was pressed, and possibly a `TextEdit`.

### Example
Given the following text, with the cursor position indicated by `|`:
```
Proof.
    trivial.
    Qed.|
```
After enter:
```
Proof.
    trivial.
Qed.
|
```

**Comment by alexandrudima** [comment]
fyi @rebornix

**Comment by rebornix** [comment]
This one is already fixed via https://github.com/Microsoft/vscode/pull/16568
