### ISSUE TITLE
Cursor Icon Bug when Middle Click the Scroll Bar

### ISSUE THREAD

**Issue by VitaLemonCoffee** [microsoft/vscode#167367]
Type: <b>Bug</b>

Middle clicking on the scroll bar (the one for scrolling the code) will change the cursor icon as in most of the web browsers, but will not have any similar effect (like automatic scrolling). Furthermore, the cursor icon does not easily go back to normal by clicking anywhere else than the scroll bar. This may make it confusing when misclick on the scroll bar.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.10.16.3-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics          (16 x 2895)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.42GB (11.17GB free)|
|Process Argv|--crash-reporter-id 2d3d2338-4653-4d2c-91ad-f6cd5a580285|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 5.10.16.3-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 7 4800HS with Radeon Graphics (16 x 2894)|
|Memory (System)|11.41GB (10.76GB free)|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.16.3
Lisp|mat|0.1.12
vscode-language-pack-zh-hans|MS-|1.73.11090913
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
remote-explorer|ms-|0.0.2
autolispext|Aut|1.6.0
doxdocgen|csc|1.4.0
code-runner|for|0.11.8
c-cpp-runner|fra|4.2.2
gc-excelviewer|Gra|4.2.56
better-cpp-syntax|jef|1.16.3
vscode-html-format|moh|0.0.5
vscode-language-pack-zh-hans|MS-|1.73.11090913
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
java|red|1.12.0
markdown-preview-enhanced|shd|0.6.5
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
vscode-java-debug|vsc|0.46.0
vscode-java-dependency|vsc|0.21.1
vscode-java-test|vsc|0.37.1

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
pyind779cf:30617257
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/6302
