### ISSUE TITLE
"Breakpoints view" is not accessible unless setting at least one, thus restricting to access to  "Exceptions"

### ISSUE THREAD

**Issue by nicolasmol** [microsoft/vscode#167300]
Not sure it was always like this before, but look at this.
Unless I set at least one breakpoint, it's not possible to show the "Breakpoints view" in the panel.
Then its the only solution to toggle (All/Uncaught Exceptions). 
Was not possible to show this view without any user predefined breakpoints  ?

![breakpoints](https://user-images.githubusercontent.com/61077647/204088776-098e9dec-38df-4475-aa9c-fcdac3ef0664.gif)

Flutter 3.3.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e99c9c7cd9 (il y a 3 semaines) • 2022-11-01 16:59:00 -0700
Engine • revision 857bd6b74c
Tools • Dart 2.18.4 • DevTools 2.15.0
Vscode: 1.73.1
OS: Linux Mint 20.3 x86_64 Kenel 5.15.0-53-generic

**Comment by roblourens** [comment]
Not sure about this- did you move the breakpoints view into the test view? Does it work in the debug viewlet?

**Comment by nicolasmol** [comment]
Not sure what you mean. Maybe larger screens captures will help.
Do you see the "debug viewlet <= if it's so called" is not accessible in the menu when no breakpoint is defined
![image](https://user-images.githubusercontent.com/61077647/205278511-35a58e7b-bf9e-4cac-8513-ddc232ab4d20.png)
But when is set one breakpoint, it appears in the menu & the viewlet also
![image](https://user-images.githubusercontent.com/61077647/205278942-24f20dcc-ab33-4cb2-8c8a-0ed15c9a2ccf.png)

But this means that if you want to switch theses checkboxes :
![image](https://user-images.githubusercontent.com/61077647/205279162-3a6b3f7f-0e6c-40b1-96da-c689155b6393.png)

...you must need to define at least a breakpoint !!

Is this not 2 extras click ?
1) turn on a dummy a breakpoint <===== ???
2) switch the desired type of exception
3)  turn off the dummy breakpoint <===== ???

**Comment by nicolasmol** [comment]
Side not...
It appears that the problem was in my current Flutter project but not now ...opening another one.

I briefly checked if its a matter of path/symlink...this doesn't seem to be.

Would it be because of one dependency ?

**Comment by nicolasmol** [comment]
How strange is this...I show you side by side
**On the left :** freshly made project "test" => Debug viewlet not accessible in the right-click menu
path is : `/home/nicolasm/Dev/Flutter Courses/Dbestech/test`
**On the right:** an old project : => Debug viewlet is accessible in the right-click menu
path is: ` /home/nicolasm/Dev/Flutter Courses/Dbestech/Quiz app wih firebase`
![Peek 02-12-2022 11-36](https://user-images.githubusercontent.com/61077647/205284884-09456308-58c9-4e80-889b-753e031bb8ab.gif)

**Comment by roblourens** [comment]
I see, this happens when you don't have a launch.json in your project. Since it's possible to debug without defining a launch.json, we should show this view when you have started the debugger once previously.

**Comment by roblourens** [comment]
If anyone wants to work on this, we should add a new context key that is set to true when a debug session starts, and when that context key is true, the breakpoints view should be visible: https://github.com/microsoft/vscode/blob/ffff626751c7bfa863ceedd5dc3f64b75c2a7de9/src/vs/workbench/contrib/debug/browser/debug.contribution.ts#L412

**Comment by MonadChains** [comment]
@roblourens I've submit a patch with a possible fix, let me know if it works.

**Comment by joyceerhl** [comment]
I see the breakpoints view in a folder without a launch.json, but it has no contents when expanded, is that expected?
<img width="583" alt="image" src="https://user-images.githubusercontent.com/30305945/214719745-4d2138ff-0800-4cac-ba5e-02075e742425.png">

Also, not sure if this is an intentional behavior change, but clicking Run and Debug in Insiders in the above scenario does nothing, while in Stable I get this quickpick 
<img width="791" alt="image" src="https://user-images.githubusercontent.com/30305945/214719971-aabd7f29-723c-45d3-89d4-1155d98a518e.png">

I have Python extension v2023.1.10091012 in stable and v2023.1.10241007 in insiders, in case this is caused by an extension and not core.

**Comment by roblourens** [comment]
Good catch, filed https://github.com/microsoft/vscode/issues/172550, thanks @joyceerhl
