### ISSUE TITLE
Can't see characters inside ide

### ISSUE THREAD

**Issue by aradbm** [microsoft/vscode#167315]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: newest
- OS Version: ubuntu 22.04

Steps to Reproduce:

1. 
<img width="1440" alt="Screenshot 2022-11-26 at 23 12 40" src="https://user-images.githubusercontent.com/50054061/204109151-f41076c3-c793-4d10-9484-f7839bfe27f0.png">

2. Can't see characters inside ide after installation, tried multiple download sites and to add to the font family different font..

**Comment by connor4312** [comment]
Please try disabling hardware acceleration: https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by aradbm** [comment]
Worked perfect thanks!
