### ISSUE TITLE
Review system doesn't work well

### ISSUE THREAD

**Issue by robozb** [microsoft/vscode#167322]
![Comment](https://user-images.githubusercontent.com/8656998/204121305-c15d7776-f4ab-457c-89d9-715bc2af49ef.JPG)

<=3 stars the "Please include comments" doesn't disappear.

**Comment by gjsjohnmurray** [comment]
Maybe you need to write more words.

**Comment by robozb** [comment]
![MoreWord](https://user-images.githubusercontent.com/8656998/204165196-80891890-6317-43d7-bb1f-212dbbf2acba.JPG)

OK, thank you! That is the workaround! They should inform the user to write more words.
