### ISSUE TITLE
Can't scroll horizontally in function definition preview. 

### ISSUE THREAD

**Issue by AbdullahAmrSobh** [microsoft/vscode#167327]
Does this issue occur when all extensions are disabled?: Can't know, since intellisense is also disabled. 

- VS Code Version: 1.73.1
- OS Version: x64

![image](https://user-images.githubusercontent.com/9056576/204136863-353b399d-5924-4686-89dd-c3dba06559d7.png)

Steps to Reproduce:

1. Hover the mouse over a function with a long definition. 
2. Try to use the mouse wheel to scroll horizontally, to see the rest of the definition.  

Expected Behavior, I should be able to use the mouse wheel to scroll horizontally.

**Comment by alexdima** [comment]
Let's track in https://github.com/microsoft/vscode/issues/84136
