### ISSUE TITLE
Lost way of putting editor tabs on upper edge of screen in full screen mode

### ISSUE THREAD

**Issue by ZYinMD** [microsoft/vscode#167318]
Type: <b>Bug</b>

After upgrading to the most recent version of **Insiders**, I can't find a way to put my roll of editor tabs onto the top edge of screen in full screen mode.

There's currently 3 UI elements on the top bar: `Menu Bar` `Command Center` `Layout Controls`. When I press F11 to go full screen, I except all these to disappear, with titles of my tabs showing on the top edge. This is still the behavior in Standard, but not in Insiders.

I'm on Win11.

VS Code version: Code - Insiders 1.74.0-insider (fef85ea792f6627c83024d1df726ca729d8c9cb3, 2022-11-21T05:22:37.848Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700U with Radeon Graphics          (16 x 1797)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.33GB (13.76GB free)|
|Process Argv|--crash-reporter-id 4e03c90e-5d42-4460-a05a-ded927f2a9a9|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/154650
