### ISSUE TITLE
Apaguei, sem querer, settings.json 

### ISSUE THREAD

**Issue by Borges-22** [microsoft/vscode#167345]
Type: <b>Feature Request</b>

I accidentally deleted settings.json.
I made the path:
"run > add configuration > settings.json"
However, I was doing a debug test, and I didn't select the local folder, and I overridden the default setting, and I don't know how to get back.
![image](https://user-images.githubusercontent.com/119269153/204169854-1ce8ec16-a39f-43d1-b5f6-ae159ee94927.png)

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by rzhao271** [comment]
Check the [local history](https://code.visualstudio.com/updates/v1_66#_local-history) and see if the previous settings were there.
If not, to reset all settings back to the default, it should be enough to change the contents of the file to just `{}`.
