### ISSUE TITLE
Test: Debugging in Python WASM

### ISSUE THREAD

**Issue by dbaeumer** [microsoft/vscode#167399]
Refs: https://github.com/microsoft/vscode-python-web-wasm/issues/31

- [x] anyOS @paulacamargo25
- [x] anyOS @alexr00

Complexity: 4

Authors: @rchiodo 

[Create Issue](https://github.com/microsoft/vscode-python-web-wasm/issues/new)

---

Testing has to happen in a Chrome based browser (e.g. Google or Edge)

- open a Python sample repository from Github inside `insiders.vscode.dev`. If you need one, you can use https://insiders.vscode.dev/github/dbaeumer/python-sample?vscode-coi=
  Ensure that you add the query parameter ?vscode-coi= to the URL
- install the latest pore-release version of `Experimental - Python for the Web` (should be 0.7.0)
- open a Python file (e.g. `app.py`)
- Execute the file by using the editor's Run menu
  <img width="219" alt="image" src="https://user-images.githubusercontent.com/1931590/204286154-6c995595-051b-4cc5-89e6-72ebe3ab2bcf.png">
  Make sure that the file gets executed and the result is printed into the terminal.
  **Note** that the first execution can take some time due to the caching of GitHub files.
- Debug the Python file using the same Run menu
  Ensure that:
  -  VS Code switches into debug mode
  - You can step over and step into statements
  - The Output is printed into the debug console
- Create a launch config (e.g.)
  ```
		{
			"type": "python-web-wasm",
			"name": "Debug Active Python File",
			"request": "launch",
			"program": "${file}",
			"stopOnEntry": true,
			"console": "integratedTerminal"
		}
  ```
- Start debugging using the launch configuration
  Ensure: that the output is printed to the integrated terminal and not to the console.
- Debugger features to test:
   - Set breakpoints and make sure they are hit
    - Step into and out of functions and make sure the callstack shows the function and the caller
    - Run code across more than one module (import another file from the same workspace)
    - Type variables into the watch window and make sure you can get the values
- Open a local folder and attempt running and debugging there too (in addition to a remote repository)

**Comment by rchiodo** [comment]
I can't edit the original text, but I'd add:

- Open a local folder and attempt running and debugging there too (in addition to a remote repository)
- Set breakpoints and make sure they are hit
- Step into and out of functions and make sure the callstack shows the function and the caller
- Run code across more than one module (import another file from the same workspace)
- Type variables into the watch window and make sure you can get the values

**Comment by dbaeumer** [comment]
Added Rich's list to the test steps

**Comment by alexr00** [comment]
> Debug the Python file using the same Run menu

This took over a minute before debugging started, even though I had previously run the file without debugging much faster.

**Comment by alexr00** [comment]
> Start debugging using the launch configuration

I immediately got this error:
![image](https://user-images.githubusercontent.com/38270282/204534684-09c5f88a-7ab6-40a9-80ec-d65ba8f6c530.png)

**Comment by dbaeumer** [comment]
I noticed that yesterday as well and opened https://github.com/microsoft/vscode-python-web-wasm/issues/30 for me.

But then when trying to track it down wasn't able to do so. Need to investigate again.

@alexr00 are you still setting it?

**Comment by alexr00** [comment]
No, it only seemed to be the first debug.

**Comment by dbaeumer** [comment]
@alexr00 thanks for the info.
