### ISSUE TITLE
A multiline regex search gets stuck indefinitely

### ISSUE THREAD

**Issue by bugale** [microsoft/vscode#167396]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1 (happens on newest insider as well)
- OS Version: Windows 11 (22623.891)

Steps to Reproduce:

1. Search (with regex selected) for this regex: `([^;]*\n)*;`

This causes the editor to get stuck indefinitely.
The regex makes sense: it just searches for all multilines ending with a semicolon.

**Comment by RedCMD** [comment]
sadly this isn't really a vscode problem
as much as a generic regex issue

nesting `*` will quite often lead to catastrophic backtracking

I don't think that regex does exactly what you think it should
![image](https://user-images.githubusercontent.com/33529441/204449539-e605dbb3-f9fd-4b61-ae0f-8c069082334d.png)

**Comment by andreamah** [comment]
I see that this causes the whole window to freeze, which shouldn't happen, even if the regex is invalid.
