### ISSUE TITLE
Double-switching windows after F2 on symbol forces you to refocus buffer and input is lost

### ISSUE THREAD

**Issue by h-h-h-h** [microsoft/vscode#167389]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0-insider
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Copy this snippet into a fresh VS Code buffer and make sure it's recognized as JavaScript:

        "use strict";
        const foo = "abc";
        console.log(foo);

2. Place the cursor onto an occurence of the `foo` identifier.
3. Press F2 to rename and type `bar`. Don't hit Enter.
4. Press Alt+Tab twice to switch to another window and back to VS Code. (Practical use case: Look for information in browser helping with deciding on the new name.)
5. The input focus of the text buffer is now lost. To regain the ability to continue typing into the buffer or to initiate a second renaming attempt with F2, I have to click on the buffer's tab. Furthermore, the text I entered into the little overlayed renaming textbox is gone.

Suggestion:

- Keep overlayed renaming textbox alive when switching windows.
- If unwanted, at least make the buffer regain focus.

**Comment by jrieken** [comment]
The rename box is designed to hide on focus lost but the editor should regain then
