### ISSUE TITLE
Allow to reopen any closed editor not just files

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16733]
#16530

- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T17:07:24.668Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|typescript-javascript-grammar|ms-vscode|0.0.10|
|sass-indented|robinbentley|1.2.1|
|dark-plus-material|vangware|0.1.4|

---

Steps to Reproduce:

1. Open settings editor
2. Close settings editor
3. Run workbench.action.reopenClosedEditor, the editor is not restored

**Comment by sandy081** [comment]
This feature should come from new side by side editor. Currently this behaves similar to Diff editor.

**Comment by bpasero** [comment]
The reason why currently only files restore is that they have a resource that we can use to do the inverse operation (reopening the input). The check is here: https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/history/browser/history.ts#L329

I think we can only support more editors when we adopted resource URIs for all editors.

**Comment by sandy081** [comment]
@bpasero Since there is lot changed, how can I get this supported in workbench?

**Comment by bpasero** [comment]
@sandy081 we need some kind of support to open a rich editor (like settings) by just having the resource in hand. I think there is noting the settings editor can do here, moving to my side.

**Comment by Tyriar** [comment]
@bpasero I think we should reconsider this, is the reason it's not possible still the same as above? The link is broken, can you provide a new pointer? (always press `y` before linking in GitHub)

**Comment by bpasero** [comment]
Oh, I did not mean to indicate that this was not possible to implement. After all we are doing software and not hardware :). I just wanted to close issues that I think I will not work on in the next months. Since this issue is opened since 2 years now I would say its safe to assume that its not super critical.

**Comment by phil294** [comment]
okay, but since it's unresolved, shouldn't this be reopened anyway?

webviews for example can provide a serialization provider etc. but still View: Reopen Closed Editor doesn't work on them which can be pretty annoying imo.
