### ISSUE TITLE
Unsaved Jupyter Notebooks are blank after updating VS Code

### ISSUE THREAD

**Issue by mccarthyp-snet** [microsoft/vscode#167365]
Type: <b>Bug</b>

After updating VS Code, I have one window that seems to have all of my unsaved Open Editors from before the update except for Jupyter Notebooks. And then I have another window with a lot (kind of seems to be the same number as the unsaved Open Editors in the other window?) of Untitled-## Open Editors that are blank but saved, accompanied by 3 unsaved Open Editors titled Untitled-1.ipynb, Untitled-2.ipynb, & Untitled-3.ipynb. I'm assuming these are 3 Jupyter Notebooks that I was in the middle of working on. However, those 3 Notebooks are now blank...

At a minimum, is there somewhere I can find the previous contents of those Notebooks?

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.73GB (32.36GB free)|
|Process Argv|--crash-reporter-id 15e1fba7-6ef1-46d4-9570-4eaa699b4d76|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
aws-toolkit-vscode|ama|1.56.0
jsoncrack-vscode|Ayk|1.0.8
gitlens|eam|13.1.1
remotehub|Git|0.46.0
vscode-pull-request-github|Git|0.54.1
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-wsl|ms-|0.72.0
powershell|ms-|2022.11.0
remote-repositories|ms-|0.24.0
vscode-xml|red|0.22.0
splunk|Spl|0.2.10
sort-lines|Tyr|1.9.1
unsaved-files-vscode|wra|2.1.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by rebornix** [comment]
It's likely to the same issue Kai was seeing with setting sync.
