### ISSUE TITLE
vscode.extensions.onDidChange event not working corrently

### ISSUE THREAD

**Issue by godkite** [microsoft/vscode#167350]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: Mac m1 13.0

Steps to Reproduce:

In my extension, listen `vscode.extensions.onDidChange` event, it not working corrently:
<img width="691" alt="image" src="https://user-images.githubusercontent.com/13809539/204180685-c227656b-accc-45be-a285-b2b8fc59afd5.png">

API describe it will be fired when extensions are installed, uninstalled, enabled or disabled.

But in fact, only the case of `installed` will be triggered.

**Comment by alexdima** [comment]
I cannot reproduce. I have written the following extension:
* `package.json`:
```json
{
    "name": "167350",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {"vscode": "^1.22.0"},
    "main": "main.js",
    "activationEvents": ["*"]
}
```
* `main.js`:
```
const vscode = require('vscode');
exports.activate = function() {
    vscode.extensions.onDidChange((e) => {
        console.log(`vscode.extensions.onDidChange fired!`);
    });
    console.log(`I am activated!!`);
}
```
* I then proceed to enable / disable a different extension (which is not activated) using the UI:


https://user-images.githubusercontent.com/5047891/204253551-94997011-7e8d-463b-8d88-7f4877f67018.mp4

**Comment by godkite** [comment]
My test extension named `inix-common-worker@0.0.3`, published to vscode marketplace [link](https://marketplace.visualstudio.com/items?itemName=t-codespaces.inix-common-worker)
<img width="554" alt="image" src="https://user-images.githubusercontent.com/13809539/204309031-e1a049a0-edeb-4a12-adc1-4d5f52930afc.png">

I then proceed to enable / disable a different extension (which is activated) using the UI:

- Old installed extension can not fired this event
- Latest installed extension can fired Enable / Disable event
- Installed event both fired
- Unstalled never fired of all

See below video

https://user-images.githubusercontent.com/13809539/204312863-8d72fb84-938d-4ac4-a079-7977a2864f4f.mp4

**Comment by godkite** [comment]
In this case, the event has no practical use value...

**Comment by alexdima** [comment]
Thank you for your feedback.
