### ISSUE TITLE
Opening the current workspace settings via the explorer should open the settings editor

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16731]
#16530

- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T17:07:24.668Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|typescript-javascript-grammar|ms-vscode|0.0.10|
|sass-indented|robinbentley|1.2.1|
|dark-plus-material|vangware|0.1.4|

---

Steps to Reproduce:

1. Open vscode repository
2. Open `.vscode/settings.json` in editor, notice just the file shows
3. Open workspace settings via command palette, notice the regular `.vscode/settings.json` editor is replaced by the proper settings editor.

**Comment by sandy081** [comment]
I will disagree to open special settings editor when clicking on settings file. Clicking on settings file should open the file as is.
