### ISSUE TITLE
Monospaced digits for the status bar items

### ISSUE THREAD

**Issue by PEZ** [microsoft/vscode#167304]
When a status bar item updates frequently with something like a counter with a fixed number of digits it grows and shrinks depending on what digits are shown. This makes it look a bit broken, and it get worse if there are items to the sides of the counter.

I'd like to suggest that status bar items are rendered with fixed width/monospaced digits. I tried with making the whole VS Code UI render like this, with this CSS:

```
* { font-feature-settings: "tnum"; }
```

And I can't notice that it is bad anywhere. Here's what a timer-counter I wrote looks like with and without this CSS applied:

* [with](https://user-images.githubusercontent.com/30010/204099632-5f9fe1ec-e61c-442d-9dc9-be1e90f11002.mp4)
* [without](https://user-images.githubusercontent.com/30010/204099741-71892352-d0fd-4537-932a-8ae2dd3d1133.mp4)

See also:

* #73700

**Comment by PEZ** [comment]
I'd like to PR this, btw. 😄

**Comment by bpasero** [comment]
This is super cool also for the selection indicator, notice the before and after:

Before:
![Recording 2022-11-30 at 15 23 13](https://user-images.githubusercontent.com/900690/204820868-3dc18622-185d-4dbe-9a3d-a99c9ac4ac9d.gif)

After:
![Recording 2022-11-30 at 15 23 46](https://user-images.githubusercontent.com/900690/204820899-ef8ae22e-aa3b-4943-be3a-5d838e692e31.gif)

**Comment by bpasero** [comment]
Check with the selection status entry and change selection, the counters should not push the width.
