### ISSUE TITLE
Test: implicit activation events

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167358]
Refs https://github.com/microsoft/vscode/issues/164701, https://github.com/microsoft/vscode/issues/166624

- [x] Windows @lszomoru
- [x] macOS @Tyriar
- [x] Linux @lramos15

Authors: @joyceerhl, @alexdima, @sandy081, @jrieken

Complexity: 4

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167358%0A%0A&assignees=joyceerhl,alexdima,sandy081,jrieken)

---

This milestone we added support for implicit activation events. This means that extensions which statically declare certain contributions in their package.json no longer need to explicitly spell out associated activation events.

The following contributions currently do not require explicit activation events to be spelled out:
1. commands -> `onCommand`
1. custom editors -> `onCustomEditor`
2. languages -> `onLanguage`
3. views -> `onView`

Please create an extension or modify an extension from `vscode-extension-samples`, and verify that the above contributions do not require explicit activation events to be spelled out in order to work correctly.

**Comment by lszomoru** [comment]
Nice work 👏🏻

**Comment by Tyriar** [comment]
This makes things so much easier, I can basically remove all activation events in all my extensions 🎉
