### ISSUE TITLE
Poor coloring of View group labels in high contrast mode

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16739]
Testing #16147

See below - you can barely see the "Views" label

![image](https://cloud.githubusercontent.com/assets/762848/20944432/499e79d8-bbb8-11e6-825d-a54682f3f97e.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by bpasero** [comment]
Good catch 👍 . Applies to all quick opens I guess.
