### ISSUE TITLE
Context-aware run cofiguration dropdown

### ISSUE THREAD

**Issue by tdranv** [microsoft/vscode#167368]
Hey,

It's not rare that I would have 5+ projects loaded at the same time while working. VSCode is great at handling that, but one thing that can be improved, in my opinion, is the debug panel and especially the configurations dropdown. The setup I have currently is that each project has 3+ debug configurations and the dropdown can get a little overwhelming. Here is an example:

![image](https://user-images.githubusercontent.com/45210624/204213782-f7b55ff6-3873-4278-ae86-bb2f7c949a45.png)

Finding what I need is a tad bit tedious. 

I was wondering if the dropdown can be aware of which file you have open, and, depending on which project it's in, preselect, for example, the first run configuration for the file's project?

**Comment by roblourens** [comment]
I don't want to mess with the dropdown selection- it's important that hitting F5 act predictably and do the same thing it did last time. 

Would adding a separator between configs from different workspace folders help?

Something else you might like - the command Select and Start Debugging shows a quickpick that lets you type to filter and select a launch config. I bind it to cmd+F5 and this is the primary way I start debugging.

**Comment by tdranv** [comment]
I see where you are coming from about being predictable.

I believe a separator would be an improvement, yes. If everyone is onboard with it, I would love to give it a go. Always wanted to contribute and this seems small enough for a start.

P.S. Did not know about this feature. Sweet!

**Comment by roblourens** [comment]
Hm, I'm not sure whether I want to make that change. Launch configs do already have a `presentation: { group: 'xyz' } }` attribute, and you could use this in your project to group your launch configs as needed.

**Comment by tdranv** [comment]
This will suffice I believe.

Thank you for your help. :)
