### ISSUE TITLE
Widen the file label slider in the editor window

### ISSUE THREAD

**Issue by xiaguangbo** [microsoft/vscode#167326]
The slider is too thin and it's easy to miss and point to the label above

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/102402151/204134990-2041b323-c433-4b00-9616-de2bb276b85d.png">

**Comment by camillebruckmann** [comment]
^ Can I try this one?

**Comment by xiaguangbo** [comment]
@camillebruckmann What do you mean?

**Comment by gjsjohnmurray** [comment]
Please try setting `"workbench.editor.titleScrollbarSizing": "large"`

**Comment by xiaguangbo** [comment]
@gjsjohnmurray thanks!

**Comment by gjsjohnmurray** [comment]
Please close this issue.
