### ISSUE TITLE
Test requests in shared process

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#167383]
Ref: https://github.com/microsoft/vscode/issues/155204

- [x] Windows @luabud
- [x] macOS @chrmarti 
- [x] Linux @rzhao271

Complexity: 3

Authors: @sandy081 @deepak1556 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167383%0A%0A&assignees=sandy081,deepak1556)

---

**Note:** You can test this in a testing profile so that your development set up is in tact. You can create an empty profile or import one using this `code-insiders://profile-github/https%3A//gist.github.com/dabeaeba4d1fcbb8f49a26ccbca70ef0`

In this milestone we enabled shared process to redirect http(s) requests through main process that has a different network stack. This is a regression testing, so please do an exploratory testing of following scenarios.

- Make sure extensions installation works from VS Code UI and also VS Code CLI
- Enable settings sync and make sure all data is synced properly - settings, extensions, state etc., (Please use separate user-data-dir and extensions-dir for this, eg: `code-insiders --user-data-dir <folder> --extensions-dir <folder>`)

@chrmarti - Please test above scenarios by setting up a proxy server configuring VS Code to use it.

**Comment by luabud** [comment]
worked as expected for me :)
