### ISSUE TITLE
can't login and sync

### ISSUE THREAD

**Issue by amirhossein-fzl** [microsoft/vscode#167307]
I want to login and sync to vscode. But I get this error. what do I do? I get vscode from pacman.

![image](https://user-images.githubusercontent.com/53816722/204104981-ba19ccbd-6cd9-4ffb-9357-dc16c2f5536f.png)

and my PC info:

![image](https://user-images.githubusercontent.com/53816722/204105094-d37294fa-fd06-403b-b04e-b9e1c6dcb5b7.png)

and vscode version:

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-14T09:01:30.462Z
Electron: 19.1.4
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.9-arch1-1
Sandboxed: No

**Comment by joyceerhl** [comment]
It looks like this is Code-OSS and not a VS Code build, and in that case Microsoft's services will not work without an official release. @rzhao271 do you happen to know if the pacman distribution is officially maintained by our team? It seems we do not have an official build for Arch Linux based on https://wiki.archlinux.org/title/Visual_Studio_Code but I want to make sure. Thanks!

**Comment by rzhao271** [comment]
I don't think the Arch package is maintained by us. Instead, users on distros that don't support Debian or RPM packages need to get the tar.gz file from the [Downloads](https://code.visualstudio.com/download) page.

**Comment by joyceerhl** [comment]
Thanks @rzhao271, in that case @amirhossein-fzl I would recommend to use the tar.gz from our Downloads page in order to use our sync features.
