### ISSUE TITLE
Get coverage info from mocha tests

### ISSUE THREAD

**Issue by nixel2007** [Microsoft/vscode#16736]
- VSCode Version: 1.7.2
- OS Version: Win10 x64 Pro

Hello. I develop an VSCode extension with integrated mocha tests as described here: https://code.visualstudio.com/Docs/extensions/testing-extensions

I want to calculate code coverage information from my tests.

I tried to use istanbul and nyc (add them before `node ./node_modules/vscode/bin/test`), tried to set the `reporter` property at testrunner constructor - no luck. 

Is there any way to get coverage information from such test run?

**Comment by bpasero** [comment]
@nixel2007 the file `test/index.ts` in your extension is the one being called from the test run. you can configure Mocha as you need from there. You can also return your own test runner if you want and if you need.

The one that is being used by default looks like this: https://github.com/Microsoft/vscode-extension-vscode/blob/master/lib/testrunner.ts

**Comment by agross** [comment]
@nixel2007 Did you succeed in setting this up?

**Comment by nixel2007** [comment]
@agross yep, I've made an example repo here - https://github.com/codecov/example-typescript-vscode-extension

Also you could check the real repo - https://github.com/xDrivenDevelopment/vsc-language-1c-bsl
