### ISSUE TITLE
Bug: Invalid interpolation format for "environment" option

### ISSUE THREAD

**Issue by jorroll** [microsoft/vscode#167393]
ADD ISSUE DESCRIPTION HERE

Codespacess is failing to build my devcontainer with the following error.

```
Invalid interpolation format for "environment" option in service "graphql-engine": "{"type":"HS256", "key": "secretsecretsecretsecretsecretsecret", "claims_namespace_path": "$.claims.hasura"}"
```

The problem appears to be that the devcontainer's `docker-compose.yaml` file contains an environment variable which is a JSON formatted string (i.e. `'{"type":"HS256", "key": "secretsecretsecretsecretsecretsecret", "claims_namespace_path": "$.claims.hasura"}'`). 

It appears as though codespaces is grabbing that envirnment variable and then reinserting it somewhere else in the form `"${JORROLS_ENV_VARIABLE}"`. The problem being that this expands to `"{"type":"HS256", "key": "secretsecretsecretsecretsecretsecret", "claims_namespace_path": "$.claims.hasura"}"` which is invalid. 

In this case, it should be inserted like `'${JORROLS_ENV_VARIABLE}'` which will expand to `'{"type":"HS256", "key": "secretsecretsecretsecretsecretsecret", "claims_namespace_path": "$.claims.hasura"}'`.

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by sandy081** [comment]
Please file issue against the codespaces.

**Comment by jorroll** [comment]
@sandy081 uh, when I was running into this issue **inside a codespace** I hit the "report issue" button and it took me here.

**Comment by sandy081** [comment]
I see.

@joaomoreno / @alexdima Can you please help in transferring this issue to Codespaces?

**Comment by joaomoreno** [comment]
Here's the official Codespaces reporting UI: https://github.com/community/community/discussions/categories/codespaces
