### ISSUE TITLE
`search.useIgnoreFiles` remove `.env` from search

### ISSUE THREAD

**Issue by mrleblanc101** [microsoft/vscode#167356]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: macOS 13.0

Steps to Reproduce:

1. Enable `search.useIgnoreFiles`
2. Add a `.gitignore` with `.env` inside your projet.
3. Use `CTRL/CMD + P` to open the `Go to file` menu
4. Search for `.env`, it won't appear in the search results.

This is intended, but should be changed or overridable.
`.env` file are never commited to a projet, but often need to be modified, so not being able to find them is a hassle.

I've tried to override using this, but it did not work:
```
"search.exclude": {
    ".git": true,
    ".env": false,
},
```

**Comment by mrleblanc101** [comment]
Alternative that work, but is not ideal:
Add a `.ignore` with `!.env`.
But this would require me to add and commit this file to all my projects.

**Comment by mrleblanc101** [comment]
I've tried moving the `.ignore` at this location `~/.ignore` (where my global `~/.gitignore` is) to make it global, but it did not work. I can't find any information or documentation about how VS Code load the global `.ignore` file, do I need to define the path somewhere ?

**Comment by andreamah** [comment]
You can enable loading the global ignore by setting `"search.useGlobalIgnoreFiles": true`. That should work for your case.

Unfortunately, there aren't any extra settings to enable search on a rule set in your `.gitignore`. We try to keep the search file ignore process from being too complicated, since there are multiple places that file ignoring can come from.

**Comment by mrleblanc101** [comment]
@andreamah I did enable that. But there is zero documentation about the `.ignore` file. Where should I place it ? How does VS Code locate this file ?

**Comment by andreamah** [comment]
The directory for the global ignore is `$HOME/.config/git/ignore`. I found it [here](https://github.com/BurntSushi/ripgrep/blob/master/doc/rg.1.txt.tpl#L133), which is in the docs for the engine we use for global search (ripgrep). It took a little digging on my side too; sorry that that info is hard to track down!

**Comment by mrleblanc101** [comment]
@andreamah Thank you, all I could find on Google was about `$HOME/.config/git/exclude` which is another way to define a global `.gitignore` without defining it in the gitconfig.

Should VS Code improve the doc about this in the Settings to make it clearer ? Because Google only surface information about `.gitignore` when searching for `.ignore` and I also looked in Ripgrep doc and didn't find it, only about the local deprecated `.rgignore`

**Comment by mrleblanc101** [comment]
@andreamah Yes and it's not in the main README, but here: https://github.com/BurntSushi/ripgrep/blob/7f23cd63a51d45415bb3df28d053562844194767/doc/rg.1.txt.tpl#L133

Also, I'll have to try tonight to valide if this work. From the ripgrep exemple, I'm not sure it will.

> The precedence of ignore rules is as follows, with later items overriding
earlier items:

    * Files given by '--ignore-file'.
    * Global gitignore rules, e.g., from '$HOME/.config/git/ignore'.
    * Local rules from '.git/info/exclude'.
    * Rules from '.gitignore'.
    * Rules from '.ignore'.
    * Rules from '.rgignore'.

So wouldn't my global `!.env` inside the global `.ignore` file would be overwritten by the `.env` inside my project local `.gitignore` ?

**Comment by mrleblanc101** [comment]
As I suspected, this does not work @andreamah

**Comment by andreamah** [comment]
Unfortunately, there doesn't seem to be a clean solution to this. 

The `search.excludes` that you mention above will only remove excludes that are part of the default set of excludes (ie: `**/node_modules`) if set to false. We generally don't want to be introducing too many settings that customize excludes, since it's already creating a bit of a confusing hierarchy. You can create a feature request for a specific way to address this if you'd like, but it would still need to go through the process of getting enough upvotes.

**Comment by mrleblanc101** [comment]
I can't be the only one that want to CMD+P to q `.env` file which are always inside a `.gitignore`. And I can't uncheck the option for gitignore cause then it will search inside build file which is very annoying.

**Comment by andreamah** [comment]
Have you considered adding the build file to `search.exclude` if that is your primary concern?

**Comment by mrleblanc101** [comment]
That's what I ended up doing, but it's not the most elegant solution.
<img width="955" alt="Capture d’écran, le 2022-12-12 à 11 10 38" src="https://user-images.githubusercontent.com/17392251/207095513-1b12b399-1e68-46e2-894e-689c5ca02f88.png">
