### ISSUE TITLE
Unknown error in console while opening ts file

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16745]
- VSCode Version: 1.8 insiders dated 12/6
- OS Version: All

Steps to Reproduce:

1. Open any workspace with a ts file 
2. Toggle Developer Tools to keep the dev tools open
3. Open the ts file

You will see the below in the console:

![image](https://cloud.githubusercontent.com/assets/16890566/20945468/4462cee8-bbbc-11e6-84ec-f01bf6f84735.png)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16432
