### ISSUE TITLE
Test: Recommend remote tunnel extension

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#167455]
Refs https://github.com/microsoft/vscode-remote-tunnels/issues/555

- [x] anyOS @rzhao271
- [x] anyOS @bpasero
- [ ] anyOS @bhavyaus 

Complexity: 2

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167455%0A%0A&assignees=aeschli)

---

We now recommend to install the `Remote - Tunnel` extension when we detect that a remote tunnel has been started on a different machine. It uses settings sync to communicate

- Have two machines with VS Code installed
- Start with new profiles. Do not have the Remote Tunnel extension installed
- Start settings sync on both machines
- On one machine start a remote tunnel (Account menu, `Turn on Remote Tunnel`)
- On the other machine you should see a notification that a machine has started a tunnel.

**Comment by bpasero** [comment]
That did not work for me.

**Comment by bpasero** [comment]
Now it worked, maybe it just needs a bit of time to settle.

**Comment by rzhao271** [comment]
I'm not seeing the notification yet, and settings sync is taking a while syncing the extensions. I'm wondering which parts need to be synced for the notification to show up?

**Comment by aeschli** [comment]
The feature depends on syncing the 'UI State' (the data in the storage).
To see what hs been synced, invoke `Settings Sync: Show Synced Data`.
You should see a key `remoteTunnelServiceUsed` being synced.

**Comment by bhavyaus** [comment]
This works for me when I go from Mac to Windows - Notification shows up rather quickly on Windows.
However, I do not see the notification starting from Windows - No notification on Mac.

**Comment by bhavyaus** [comment]
Just tried this between two Windows machines and I see the notifications.
