### ISSUE TITLE
Test additional actions in comment threads

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#167400]
Refs: https://github.com/microsoft/vscode/issues/163281

- [x] macOS @eleanorjboyd
- [x] linux @andreamah
- [x] windows @sandy081

Complexity: 5

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167400%0A%0A&assignees=alexr00)

---

There's a new, proposed, menu contribution point for comments: `"comments/commentThread/additionalActions"`.

This proposed menu can be tested using the comments extension sample by changing this line to use the new menu:

https://github.com/microsoft/vscode-extension-samples/blob/31d3d4920b3fae52e03a185e434f51ee81965515/comment-sample/package.json#L129-L130

1. Verify that using the new menu causes buttons to be visible at the bottom of comment threads
2. Verify that the comment thread is passed to commands that are contributed to that menu
3. Verify that none of the buttons get colored as a primary button.

**Comment by andreamah** [comment]
great work! 👌
