### ISSUE TITLE
Add the ability to hide numbered badges on views 

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#167434]
With the addition of the badges API, badges on arbitrary view containers continue to become more common. We don't want to add settings for every view, so this should be state that is easy to set on a per view basis.

**Comment by lramos15** [comment]
First run for feedback fixed via #https://github.com/microsoft/vscode/pull/158781

**Comment by lramos15** [comment]
> When I right-click on the source-control-icon and hide the numbered-badge, if I close VS Code and re-open it the numbered-badge is back.
> 
> Is that expected?

Feel free to file an issue to track that. It doesn't currently save state and these are definitely improvements we can make.

**Comment by aslatter** [comment]
> 
> Feel free to file an issue to track that. It doesn't currently save state and these are definitely improvements we can make.

Written in https://github.com/microsoft/vscode/issues/168939

Thanks for the feature!
