### ISSUE TITLE
Better identify User vs. Workspace Settings editor

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16742]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

It is hard to identify which is which, if you don't already know:
![screen shot 2016-12-06 at 1 41 43 pm](https://cloud.githubusercontent.com/assets/9205389/20944875/05331540-bbba-11e6-9f56-5816e0b0ee4d.png)

**Comment by chrmarti** [comment]
(Testing #16530)

**Comment by sandy081** [comment]
This is same as before. But I am planning to improve the behaviour of showing workspace settings when settings are open. So moving this to next milestone.

**Comment by sandy081** [comment]
Duplicates #18132
