### ISSUE TITLE
test: terminal quick fix telemetry

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#167475]
Refs #167473

- [x] Windows @bamurtaugh 
- [x] macOS @weinand 
- [x] Linux @rzhao271 

Complexity: 3

Authors: @meganrogge @Tyriar 

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167475%0A%0A&assignees=meganrogge,Tyriar)

---

Turn on log level: trace and verify that the info for `terminal/quick-fix` is correct for all of the types of quick fixes we offer:

- _git similar_ : `git sttatus`
- _git push_ : checkout a branch that has no upstream and `git push`
- _git create PR_ : `git push --set-upstream origin <branch-name>`
- _git two dashes_: `git add . -all`
- _free port_ : launch a server or task that uses a specific `<port>` then launch that again so you see an error related to `address already in use`

**Comment by weinand** [comment]
@meganrogge I don't understand what to do here.

**Comment by bamurtaugh** [comment]
I'm also not sure what to do here - additional info / examples would be super helpful!

**Comment by Tyriar** [comment]
Sorry about that. Open up the telemetry log channel as described in https://code.visualstudio.com/docs/getstarted/telemetry#_output-channel-for-telemetry-events, then trigger quick fixes as described in https://code.visualstudio.com/docs/terminal/shell-integration#_quick-fixes. Validate you see events for each of the quick fixes.

**Comment by weinand** [comment]
@Tyriar thanks, that was helpful.

**Comment by rzhao271** [comment]
Also, what are some steps I can try to get the free port message to show up?
I don't remember the last time I encountered that scenario.

**Comment by Tyriar** [comment]
@rzhao271 this is my typical test: 

1. Clone https://github.com/xtermjs/xterm.js
2. Run `yarn`
3. ctrl+shift+b to run default build task (first server)
4. Open a new terminal and run npm start (conflicting server)
