### ISSUE TITLE
Test: Search Contributions Cleanup

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#167450]
Refs #162858

- [x] anyOS @isidorn
- [x] anyOS @rebornix
- [x] anyOS @lramos15

Complexity: 1

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167450%0A%0A&assignees=andreamah)

---
## Background
I recently cleaned up the code in for the search contributions and search actions and I just wanted a sanity check to make sure that everything still works since it was a a heavy overhaul.

## Set up:
Have the newest version of insiders installed.

## Testing:
You can pick some random commands to test out. There are multiple ways to test the commands, but this list should cover a common way to trigger each of them and a short explaination of what they do. 

Testers don't need to complete the testing of all of the commands; I just have it here so that people know what commands they can test. It'd be awesome if people could check off the ones they've tested so that there's some variety in what commands are tested, though! 😊 

### Command list

Basic search results navigation commands:
- [ ] Using action buttons to replace/remove
![image](https://user-images.githubusercontent.com/31675041/204366325-a5f1aead-a9cc-4836-bd73-3ed9a7e02e85.png)
- [ ] `enter` when focused on a match to open the file and focus on the opened file 
- [ ] `ctrl`+`enter` when focused on a match to open the file to the side and focus on it. 
- In context menu when right-clicking a search result entry:
    - [ ] "Copy" - copies the currently focused search result to clipboard
    - [ ] "Copy All" - copies all of the selected results to clipboard
    - [ ] "Copy Path" (only for file or folder entries in the search result) - copies path of file or folder to clipboard
    - [ ] "Reveal in File Explorer" (only for file match) - reveals file in File Explorer viewlet
    - [ ] "Restrict Search to Folder" (only in folder match) - adds path to "files to include"
    - [ ] "Exclude Folder from Search" (only in folder match) - adds path to "files to exclude"
        
![image](https://user-images.githubusercontent.com/31675041/204366995-80fe700d-ff46-4e31-a82f-94e7b9ca4513.png)

In context menu when right-clicking an explorer entry:
- [ ] "Find in Folder..." - add this folder to "file to include" in the search viewlet.
    
Command palette 
- [ ] "Search: Find in Files" - opens the search viewlet
- [ ] "Search: Replace in Files" - opens the search viewlet with the replace field revealed
- [ ] "Search: Focus List" - focuses on the list of search results in the viewlet
- [ ] "Search: Focus on Next Search Result" / "Search: Focus on Previous Search Result" - toggling between matches in search viewlet

Keybindings:
- [ ] `ctrl/cmd` + `shift` + `J` to toggle the files to include/exclude fields
- [ ] `escape` when focused in the "replace" output hides it
- [ ] `ctrl/cmd` + `shift` + `L` when selecting multiple results to add cursors to all of them 
- [ ] `ctrl` + `up`/`down` when focused on search input fields to toggle between them. Note that the `ctrl`+`up` when focused on the list of results to go back to the inputs only works when you're focused on the top result.

Top bar buttons:
- [ ] refresh, clear search results, open in search editor, treeview/listview toggle, and collapse/expand.

![image](https://user-images.githubusercontent.com/31675041/204367238-92488385-d66a-4a68-a5b9-f7c12df6746b.png)

Etc: 
  - [ ] using "#" in command palette to do a workspace-wide symbol search
![image](https://user-images.githubusercontent.com/31675041/204367789-02c81839-ee30-4ea7-8ba5-139f05174b32.png)

**Comment by isidorn** [comment]
I tested on macOS. Works great. I did not know all of this functionality - so thanks for the learning.
The only thing I find weird is `cmd + up/down` to navigate between input boxes. Do we use this pattern anywhere else in our UI? Is there some more common pattern we can use to pass focus between input fields so that the search view aligns with the other accessibility pattern we have in VS Code?

**Comment by lramos15** [comment]
> "Copy All" - copies all of the selected results to clipboard

This copies all for me not just the selected ones

**Comment by andreamah** [comment]
> I tested on macOS. Works great. I did not know all of this functionality - so thanks for the learning. The only thing I find weird is `cmd + up/down` to navigate between input boxes. Do we use this pattern anywhere else in our UI? Is there some more common pattern we can use to pass focus between input fields so that the search view aligns with the other accessibility pattern we have in VS Code?

I'm actually not too sure! This has been what it's been like before, but I notice that it's sort of similar to how to move down to the extension list? But strangely, that one doesn't toggle back up with `ctrl`+`up`.

[![Image from Gyazo](https://i.gyazo.com/8f29784594f24785d058e9dea9ec33a9.gif)](https://gyazo.com/8f29784594f24785d058e9dea9ec33a9)

**Comment by andreamah** [comment]
> > "Copy All" - copies all of the selected results to clipboard
> 
> This copies all for me not just the selected ones

Oops, yes, that's the intended effect.

> > Search: Focus List
> 
> What's the difference between this and Focus View? They seem to do the same thing for me

`Search: Focus List` focuses on the list of results regardless of where you were last focused when you were on the search view.
'Search: Focus on Search View` focuses on the search view wherever you last focused.
