### ISSUE TITLE
Terminal not working. At first, the webpage asking me dowload chrome because my current browser firefox dont support codespace

### ISSUE THREAD

**Issue by vappi** [microsoft/vscode#167409]
ADD ISSUE DESCRIPTION HERE

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Embedder: codespaces

**Comment by meganrogge** [comment]
It looks like your report is missing some important information, See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more info on how to report actionable terminal issues.
/label info-needed terminal

**Comment by vappi** [comment]
hfhfhgs
