### ISSUE TITLE
Setting for how much/little a debug value is truncated.

### ISSUE THREAD

**Issue by theoryshaw** [microsoft/vscode#167474]
Would be nice to have a setting, where you could control how much or how little vscode truncates debug values. 

If truncation was turned off you could see the whole value, for example. 
 `results: (Vector((1.6292068494294654e-07, -1.0, 0.0)), Vector((1.6292068494294654e-07, -1.0, 0.0)))`

verses how it is currently automatically truncates the value below...
![](https://community.osarch.org/uploads/editor/0s/nt2tb63872bx.png "")

**Comment by roblourens** [comment]
I don't think this is actually truncated by vscode? I think this just comes as-is from the debug adapter. You could file an issue on the vscode-python repo or share some code that reproes this for me to check. If you hover the value and also see a truncated value, I think that would prove it.

**Comment by theoryshaw** [comment]
My apologies, you're right!  Thanks for the clarification. 
Posted here: https://github.com/microsoft/vscode-python/issues/20287
