### ISSUE TITLE
Default settings search: Let ArrowUp/-Down navigate the result list

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16741]
Testing #16530

Similar to Enter navigating to the next setting. ArrowUp/-Down should navigate to the previous/next setting.

It would be great if that search & results UI would behave *a little bit* more like a combo box, IntelliSense or the command palette. Enter could trigger the Edit action.

Related: #16718

**Comment by sandy081** [comment]
IMO using up/down arrow navigation for settings is not correct and not consistent with Find. I think if we can let users customise by changing key bindings then users can decide what key they would like to navigate.

**Comment by sandy081** [comment]
Since navigation commands keybindings are customisable, closing this in favour of that.
