### ISSUE TITLE
Crash dump from macOS smoke test

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167499]
Sorry if this has already been reported.

[d18d8ce3-b95d-42d0-8aae-4dc7af0447a3.dmp.zip](https://github.com/microsoft/vscode/files/10111031/d18d8ce3-b95d-42d0-8aae-4dc7af0447a3.dmp.zip)

Build: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=194635&view=results

**Comment by bpasero** [comment]
Another one in: https://dev.azure.com/monacotools/Monaco/_build/results?buildId=194916&view=artifacts&pathAsName=false&type=publishedArtifacts

[cc3b619a-cda2-4989-8609-7e3864b9cf20.dmp.zip](https://github.com/microsoft/vscode/files/10123940/cc3b619a-cda2-4989-8609-7e3864b9cf20.dmp.zip)

**Comment by deepak1556** [comment]
Addressed in https://github.com/microsoft/vscode-internalbacklog/issues/3272
