### ISSUE TITLE
Ctrl+Q to navigate Views is a little close to Ctrl+W

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16740]
Testing #16147

Accidentally closed the editor while testing this feature 

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by bpasero** [comment]
As someone that has been using Ctrl+Q for quickly switching between files for the past 4 years (since introduction of quick open) I can only say, you get used to it. I never closed a file.

**Comment by mousetraps** [comment]
@bpasero *sigh* I blame my tiny hands. I have to stretch quite a bit to hit Ctrl+Q, so it gets imprecise...
