### ISSUE TITLE
taking to much time to load

### ISSUE THREAD

**Issue by fzmalik** [microsoft/vscode#167429]
ADD ISSUE DESCRIPTION HERE

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Tyriar** [comment]
Please see https://github.com/Microsoft/vscode/wiki/Performance-Issues for creating actionable performance problem issues.
