### ISSUE TITLE
Sync selected process from debug widget to callstack

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16744]
Testing https://github.com/Microsoft/vscode/issues/15305

- Start debugging two processes
- Click between one and the other in the callstack, and notice that the debug widget dropdown changes as you'd expect. 
- Change the selected process in the debug widget dropdown, and notice that the selection in the callstack doesn't change

I think everything should be in sync, especially since the editor changes, and then doesn't match the selected stack frame. When one process isn't at a breakpoint, it could select the process' root node.

**Comment by isidorn** [comment]
It should work fine now with the exception when a process is stopped.
Due to a timing issue in that case I just clear the selection and do not select the focused process

**Comment by isidorn** [comment]
Ignore my previous comment - that should also work now via 91f4651
