### ISSUE TITLE
Allow to customise content of completion items

### ISSUE THREAD

**Issue by BleyChen** [Microsoft/vscode#1674]
Now i want to use the treeview in my vscode plugin, whether i can copy the folder from vscode source and use it in my plugin?

**Comment by bpasero** [comment]
We currently do not allow for UI access from extensions.

**Comment by BleyChen** [comment]
The plugin what I want to implement has following requirement:
As you know, vscode will popup an completionitemlist when user type JavaScript in vscode, what my plugin want to do is show external information for each completionitem when user switch between each completionitem, but now I have not found any API can meet my requirement , so I suppose whether I can change the vscode source to provide an API for my plugin.

**Comment by bpasero** [comment]
Ok so would you want to show this information inside the completion item list? Like a JSDoc comment?

**Comment by BleyChen** [comment]
Yes , what i want to do is append an button inside each completion item ,and when user want to see sample ,he can click show sample button and then will expand an fixed height with scrollbar area to show sample for the completion item .
![aabbbddd](https://cloud.githubusercontent.com/assets/15098626/12028805/64a6621c-ae18-11e5-96cf-6c0a666d6208.png)

do you know how to expose this api , i am researching vscode source and i don't know how to expose this api ,can you help me ,thank you!

**Comment by bpasero** [comment]
There is currently no API to do this. Best you can probably do is to provide the text for a completion item that will show when the item is highlighted.

**Comment by roslanr18** [comment]
.

**Comment by jrieken** [comment]
Closed because have no plans to let  extensions manipulate suggestions from other extensions
