### ISSUE TITLE
test: cli service installation

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167489]
Refs https://github.com/microsoft/vscode-cli/issues/367

- [x] Windows @bamurtaugh 
- [ ] Windows @dbaeumer 
- [x] macOS @DonJayamanne 
- [x] macOS @aeschli  
- [x] Linux @alexr00 

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167489%0A%0A&assignees=connor4312)

---

Note: Linux specifically requires systemd Linux, i.e. not Alpine. Ubuntu, Fedora, Debian, etc. should work fine.

1. Download the latest standalone CLI from the build site
2. Run `./code tunnel service install`, make sure it installs sensibly
3. Run `Connect to Tunnel` on insiders.vscode.dev to make sure you can then connect to the running tunnel
4. Check that output is available at `./code tunnel service log` (should continually update). If you run into problems in step 3, share this log 🙂 
5. Run `./code tunnel service uninstall`, make sure it uninstalls sensibly. You should no longer be able to connect to the tunnel.

**Comment by alexr00** [comment]
I got the following error when running the install:

```
[2022-11-29 11:02:04] info Successfully registered service...
[2022-11-29 11:02:04] error error starting service: org.freedesktop.systemd1.NoSuchUnit: Unit code-insiders-tunnel.service not found.
```

I'm using Ubuntu 18.

**Comment by bamurtaugh** [comment]
I installed the latest standalone CLI, and I'm required to run the service install command in an elevated PowerShell terminal (understandable).

I get prompted:

```
Running a Windows service under your user requires your username and password.
These are sent to the Windows Service Manager and are not stored by VS Code.
```

I try my Windows username and password in many different configurations (just username, domain\username, username@email) but I always get `error Invalid username or password, please try again...`. Am I missing some step or username/password configuration (i.e. should I not be using my Windows 11 username and password)?

**Comment by connor4312** [comment]
It should be just username. On most Windows installs where you signed in with your Microsoft account, the password will then be the password for your Microsoft account.

**Comment by connor4312** [comment]
> I got the following error when running the install:
> 
> ```
> [2022-11-29 11:02:04] info Successfully registered service...
> [2022-11-29 11:02:04] error error starting service: org.freedesktop.systemd1.NoSuchUnit: Unit code-insiders-tunnel.service not found.
> ```
> 
> I'm using Ubuntu 18.

18 is pretty old. Please open an issue for that, but try verifying on a newer version if you can. I developed on 20.04 and 22.04, and did a sanity check just now on 22.04.

**Comment by DonJayamanne** [comment]
@connor4312 
In vscode.dev when using the command `Connect to Tunnel` i get the error message `Command 'Remote-Tunnels: Connect to Tunnel...' resulted in an error (command 'remote-tunnels.connectCurrentWindowToTunnel' not found)`

In insiders.vscode.dev I get prompted for github auth and that seems to work, however its stuck at `Connecting to es: Setting up server...`

**Comment by connor4312** [comment]
@DonJayamanne please ensure you are on the latest prerelease version of the Remote Tunnels extension.

**Comment by DonJayamanne** [comment]
I have `v0.1.2022112916` installed in vscode.dev and its marked as `pre-release`
still no joy, same error message

**Comment by connor4312** [comment]
Can you please share the logs from step 4 in a new issue?

Also, it is _not_ expected to work on stable vscode.dev at this time.

**Comment by DonJayamanne** [comment]
> it is not expected to work on stable vscode.dev at this time.

I tried that as thats what is mentioend in teh test plan above. But tried insiders as well.

**Comment by dbaeumer** [comment]
I tried various combinations of username / password on Windows as well and they all failed for me on my machine. What is interesting is that when I used an obvious incorrect combination I got

```
error Invalid username or password, please try again...
```

Right after providing the password.

When I provided an obviously correct combination I didn't get that message but the start of the service failed with

```
[2022-11-30 12:08:20] info Successfully registered service...
[2022-11-30 12:08:20] error error starting service: Winapi(Os { code: 1069, kind: Uncategorized, message: "The service did not start due to a logon failure." })
```

**Comment by dbaeumer** [comment]
I even created a local admin user on my Windows machine but that one failed with the same error message

```
[2022-11-30 12:19:31] info Successfully registered service...
[2022-11-30 12:19:31] error error starting service: Winapi(Os { code: 1069, kind: Uncategorized, message: "The service did not start due to a logon failure." })
```

I ran out of possibilities :-)

**Comment by aeschli** [comment]
I tested on the Mac (Monterey 12.6.1). Installing and unstalling worked fine. The servic ewas correctly started.
I also could access the service via Web UI.

**Comment by connor4312** [comment]
Thanks for the followup. I hit that yesterday on my domain joined Windows VM, it seems like something to do with the system policies. I want to try to find a different solution for running on Windows.

You can just mark windows as verified for now, and I will investigate this further: https://github.com/microsoft/vscode/issues/167741
