### ISSUE TITLE
Test: Git - optimistic updates

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#167418]
Refs: https://github.com/microsoft/vscode/issues/162481

- [x] anyOS @digitarald 
- [x] anyOS @aeschli

Complexity: 3

[Create Issue](https://github.com/microsoft/vscode/issues/new?body=Testing+%23167418%0A%0A&assignees=lszomoru)

---

When performing various operations in the "Source Control" view, we would execute the git command, follow which we would run various git commands (ex: git status) to update the model before refreshing the various UI elements (ex: commit input, resource list) in the "Source Control" view. 

This milestone we have made changes to that the UI gets refreshed optimistically after the git command is executed. We would still run the various git commands to update the model but that happens in the background and should not result in any UI changes. The following commands should feel much snappier: state, un-stage, discard, commit.

### Prerequisites
* Install the latest VS Code Insiders
* Ensure that `git.optimisticUpdate` is set to `true`
* Clone a large monorepo (ex: https://github.com/torvalds/linux)

### Testplan
* Open folder/workspace that contains a git monorepo
* Make changes to existing files, and add couple of new files
* Switch to the "Source Control" view
* Stage single file/multiple file in quick succession/all files
  * Confirm that changes to the resources list are immediate
* Un-stage single file/multiple files in quick succession/all files
  * Confirm that changes to the resources list are immediate
* Discard changes for a single file/multiple files in quick succession/all files
  * Confirm that changes to the resources list are immediate
* Enter a commit message, hit the commit button
  * Confirm that changes to the resources list are immediate

**Comment by aeschli** [comment]
Tested on Windows 11. Works beautifully! 
BTW to check out https://github.com/torvalds/linux in Windows: https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows
