### ISSUE TITLE
No feedback when waiting for program launch while another is running

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16752]
Testing https://github.com/Microsoft/vscode/issues/15305

Say I have an 'attach' launch config with the wrong port.

If I'm not debugging anything, and launch that config, I get a progress indicator in the debug viewlet, and the debug widget pops up, so I know it's working.

If I start another launch config first, then start my bad attach config, there's no indicator at all, but 10s later, a message pops up saying that it failed.

Maybe the entry should show up in the debug widget when I start the launch, rather than when it successfully attaches.

**Comment by isidorn** [comment]
Yes this experience could be improved. 
My suggestion is to show the progress in the debug viewlet, the same way we show it when you launch the first process. That would let the user know that a new process is starting up
