### ISSUE TITLE
Terminal quick fix API: multipleMatches is confusing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167584]
Testing #166762

I expected that if this is true and the outputMatcher regex matches multiple times, I would see these matches in the result, but I don't see any difference

**Comment by Tyriar** [comment]
@roblourens the docs say it will result in outputLines being provided to the extension:

https://github.com/microsoft/vscode/blob/510f84046f9d7f009bebd1df6889f081e1640397/src/vscode-dts/vscode.proposed.terminalQuickFixProvider.d.ts#L71-L75

It might be confusing which is valid feedback, but does that work?

**Comment by roblourens** [comment]
That does work, I get `outputLines` when it's set. I also was confused because I was trying it with multiple matches on the same line. It's confusing that I only get the regex match info for the first match, then just raw lines for the rest, would that mean that I have to rerun the regex myself if I need to parse the additional matches?

**Comment by Tyriar** [comment]
@roblourens basically yeah, it could do with some improvements.

**Comment by meganrogge** [comment]
Not sure how this can be improved - suggestions @roblourens ?

**Comment by roblourens** [comment]
It seems like if I want to get additional matches, then my regex has to exist in two places- in my package.json declaration and also in code. Ideally I wouldn't have to have the same regex in two places

**Comment by Tyriar** [comment]
Maybe we're overcomplicating things and the perf impact won't be so large if we just always send the lines over when there's an output match. In most cases length will be quite small anyway.

**Comment by roblourens** [comment]
I'm having trouble remembering exactly what my setup was, but I don't see which of my comments was addressed

- multipleMatches still doesn't have a description in package.json
- The `TerminalCommandMatchResult` API seems pretty much the same, I get one regex match and raw lines for the rest https://github.com/microsoft/vscode/blob/9476cf3775bac3c762b338fa1888b87f7f8c14d8/src/vscode-dts/vscode.proposed.terminalQuickFixProvider.d.ts#L22-L25

**Comment by Tyriar** [comment]
@meganrogge thoughts? I haven't looked much into it

**Comment by meganrogge** [comment]
yep, it's been removed. schema does not complain in general about erroneous properties

![Screenshot 2023-01-25 at 3 49 14 PM](https://user-images.githubusercontent.com/29464607/214699106-f871e8b5-8224-4fbc-969f-f4b8378d5376.png)

**Comment by meganrogge** [comment]
also not validated for other schemas

![Screenshot 2023-01-25 at 3 50 59 PM](https://user-images.githubusercontent.com/29464607/214699462-e171b623-0bc0-47f5-983a-b457cca2a453.png)

**Comment by roblourens** [comment]
I think one way to validate this is `"additionalProperties": false` although I was thinking that was the default

**Comment by meganrogge** [comment]
Yeah might want to create an issue for that because should be the default.

**Comment by roblourens** [comment]
Still- what am I verifying here? Are these issues? https://github.com/microsoft/vscode/issues/167584#issuecomment-1403913791

**Comment by meganrogge** [comment]
that without using `multipleMatches`, you can get multiple matches
