### ISSUE TITLE
Too many workspace using `Codespaces: Continue Working in a New Codespace`

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#167537]
Testing #167433

Too many workspace using `Codespaces: Continue Working in a New Codespace`:
<img width="462" alt="image" src="https://user-images.githubusercontent.com/9205389/204533968-5ca8d8df-4320-40af-bd93-b280ab17b761.png">

Same happened with the multi-step QuickPick. Correlation ids: 3985:14A6:239ED2B:242D43C:63860048 and 3984:2C12:2B3FB9B:2BDFC0E:6386008D.

**Comment by chrmarti** [comment]
Not sure this matters, but the limit seems to have changed to 6 (not 30 as per the instructions).

**Comment by joyceerhl** [comment]
There are two different limits:
1. 30 codespaces (active or inactive)
2. 6 active codespaces

It looks like the Codespaces extension isn't handling the second case.

**Comment by joyceerhl** [comment]
Will be fixed in Codespaces 1.13.3.
