### ISSUE TITLE
Settings to hide activity bar and status bar items

### ISSUE THREAD

**Issue by rue-a** [microsoft/vscode#167511]
This refers to a closed issue that didn't receive any comments and was closed by the author. I copy the Issue here:

> __[Issue#125861](https://github.com/microsoft/vscode/issues/125861)__
>Context: Many educators would like to hide or simplify parts of the VS Code UI that they feel are unnecessary or complicated for their students at a point in time. As one educator put it, "I don't want to draw attention to things that don't need attention drawn there."
>
>Feedback: Many of them would like to hide icons in the activity bar and information in the bottom status bar and have it persist as a setting that they can then share with their students, with the intent of progressively showing those parts of the editor when the educator feels students are ready to use it.
>
>Currently, we can right click and hide activity bar icons and status bar elements, but there are no settings for this to persist or to share this setting with others.

I am also teaching students and think this feature would be highly valuable. I wonder why the issue was closed, since I couldn't find an option in VS Code that satisfies the request.

**Comment by daviddossett** [comment]
Hey @rue-a, have you tried the Settings Profiles feature in Insiders? This will enable you create profiles to persist UI state, among other things.

<img width="291" alt="CleanShot 2022-11-29 at 09 40 52@2x" src="https://user-images.githubusercontent.com/25163139/204602660-f81228f2-5492-48ac-8c33-0e9a79c33f60.png">

cc @sandy081

**Comment by rue-a** [comment]
Hi, thank you for the tip. Apparently, the settings profiles already sneaked into the default version of VS Code (at least _Settings Profiles: Export ..._ and _Settings Profiles: Import from ..._). 

Now I only need to import the Profile on the creation of a Codespace (as it seems I cannot directly define the `"globalState"`, which is the interesting part of the exported profile, in the `devcontainer.json`). 

Right now, I'm searching for the place where this information is stored to overwrite in manually. Well, this is somewhat off-topic, going to close this issue the next days.
