### ISSUE TITLE
Language pack recommendation - Pseudolanguage and RTL system languages

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#167543]
Testing #167105

Went through the steps and again, after setting the primary language to Arabic, and setting the locale to "qps-ploc" I started VS Code and I got a notification to install the Pseudolanguage Language Pack. After I installed it, and restarted VS Code, the display language switched to Pseudolanguage.

The traffic light does appear on the left, but I am only seeing the "red light".

**Comment by rzhao271** [comment]
Verification steps:
1. On macOS, set the system language to Arabic.
2. Do a full system restart.
3. Open VS Code
4. Confirm that the traffic lights are on the right side and that all three of them are visible.
5. There is a bug where the traffic lights are on top of the layout controls, but that is already being tracked by https://github.com/microsoft/vscode/issues/164397
