### ISSUE TITLE
Quick fix actions in bash become 'offset'

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167591]
Testing #166761

1. Run a command that triggers a quickfix
2. Hit "enter" without accepting the fix
3. Run the command again
4. 🐛 notice there's no lightbulb. But hit enter again, and it appears

https://user-images.githubusercontent.com/2230985/204610315-5bf48709-fff3-4ee0-8ecd-26638ecb430b.mp4

**Comment by connor4312** [comment]
I also see this sometimes on new terminals, so maybe it's not related to running a previous command

<img width="539" alt="image" src="https://user-images.githubusercontent.com/2230985/204610983-c0ded889-7c44-48d9-be83-57800baffe3b.png">

**Comment by meganrogge** [comment]
I cannot reproduce this, pls let me know if you still can @connor4312
