### ISSUE TITLE
Every keyboard action with the 'modified elsewhere' pop-up open will close the pop-up and lose focus

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#167570]
Testing #167088

1. open the settings tab
2. `tab` to a "modified elsewhere" tag
3. press enter to open the pop-up
4. press enter, esc, tab or down arrow
result: pop-up closes and focus goes somewhere else (don't know where)

expected:
to be able to navigate to the link in the pop-up
if I press escape, focus should return to the tag

**Comment by rzhao271** [comment]
Does this behaviour occur on the latest Insiders? I merged in some changes recently, so you might be seeing the old behaviour.

**Comment by amunger** [comment]
no, I hadn't updated yet. works as expected
