### ISSUE TITLE
Unexpected use of quick input

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167544]
Testing #167161

I find it confusing that the input bar does not filter the options, but is disconnected from the list:

![Code_-_Insiders_SUaTObFcmq](https://user-images.githubusercontent.com/2931520/204554509-a8d0666e-4a26-4333-8d89-742ab3af518c.gif)

I think there should be two options and only if you select "Import from URL" there should be a text prompt for the URL.

Alternatively, richer UIs should be explored where the text prompt is next to a radio button "Import from URL".

**Comment by sandy081** [comment]
The placeholder says to import from file or type the URL to import. This is the pattern we already use at other places like following

<img width="617" alt="image" src="https://user-images.githubusercontent.com/10746682/204583621-52c8fd3c-d948-4e8b-bd42-1f157072c8cc.png">

I think the idea behind this is to make it easier to use by providing simpler UI and not bombarding with too many quick picks or UI for a simple feature.

**Comment by hediet** [comment]
>  like following

How can I open this?

**Comment by sandy081** [comment]
Through `Git: Clone` command

**Comment by hediet** [comment]
That behaves differently though:

image.png
![image](https://user-images.githubusercontent.com/2931520/204596463-a845f026-2b89-49d0-9bc4-dcdc84ed9c3b.png)

It is still a filter. Though it is also weird there.

**Comment by sandy081** [comment]
I understand your point. I am not sure how much it makes sense for an user to type the text **Import from...** in the input box and use it for filter as there are just two options in the picker.
