### ISSUE TITLE
terminal quick fix contribution: multipleMatches not suggested

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#167586]
Testing #166762

The example in the test item lists `multipleMatches`, which is not proposed. 

<img width="281" alt="image" src="https://user-images.githubusercontent.com/6461412/204604643-e3c65a9e-8b99-4306-a074-57555b9531d7.png">

**Comment by meganrogge** [comment]
we've decided to get rid of `multipleMatches`
