### ISSUE TITLE
Show which launch config is running when there's only one

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16755]
Test https://github.com/Microsoft/vscode/issues/15305

If I have multiple launch configs running, I can see their names, but when there's just one, I can't see its name anywhere. Just a suggestion.

Maybe it could just be grayed out or strikethrough'd in the debug config picker.

**Comment by isidorn** [comment]
Disagre, this is just how native dropdowns behave. They are enabled even when there is a single option. I believe this is how users are used to interacting with them and being overly smart here might not be good.

Places where we already behave like this: terminal, launch dropdown, output
