### ISSUE TITLE
Paths are not using backslash on windows

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167515]
Testing #167413

<img width="310" alt="image" src="https://user-images.githubusercontent.com/900690/204512763-4d23a4a8-732c-4dd0-b0a9-cbaa6b56440b.png">

**Comment by bpasero** [comment]
Same for the picker where the repositories are shown btw.

**Comment by bpasero** [comment]
And also the notification toast. I suggest to use the label service for consistent path formatting.

**Comment by lszomoru** [comment]
@bpasero, is the label service available to built-in extensions?

**Comment by bpasero** [comment]
I briefly pinged @alexr00 but there seems to be no API to format labels. I am not sure if @jrieken or @mjbvz have suggestions for how an extension can render a path label properly according to our "rules".

**Comment by alexr00** [comment]
I missed the comment on `Uri.file().fsPath` about not using it for display. microsoft/vscode-pull-request-github is definitely using that for display in a few quick picks. I don't know of another way to get the correct slashes.

**Comment by bpasero** [comment]
One downside of `.fsPath` is that drive letter is lowercased, but for display purposes it should be uppercased.

**Comment by jrieken** [comment]
You can use [`vscode.workspace.asRelativePath`](https://github.com/microsoft/vscode/blob/7ae2857bf0d9d0e01512c959afb59414dfab40cb/src/vscode-dts/vscode.d.ts#L12106) for this. It makes the path relative, pretty and can pretend the workspace name (if wanted)

**Comment by lszomoru** [comment]
Thank you all! The path itself is extracted from a git error message and decided to call `path.notmalize()` on it after I extract it from the error message. This seems to result in the correct drive letter casing and separator.

**Comment by lszomoru** [comment]
And to make things even more fun, I just learned that `safe.directory` can only handle `/` as a path separator.

**Comment by connor4312** [comment]
What's the best way to trigger this message? I made a git repo owned by the SYSTEM instead of my user, but did not encounter this warning.

**Comment by lszomoru** [comment]
We have tweaked the welcome view and the paths are not being shown any more. Will mark as verified.
