### ISSUE TITLE
terminal quick fix contribution: follow form of other contributions

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#167577]
Testing #166762
```
  "contributes": {
    "terminal": {
	"quickFixes": [
```

Typically, contributions don't have a hierarchy, but are right under `contributes`. They use camelCase and are a plural

Examples: `semanticTokenTypes`, `typescriptServerPlugins`

-> change to `terminalQuickFixes`

**Comment by meganrogge** [comment]
We also have `profiles` under "terminal" which is why I went with this

**Comment by Tyriar** [comment]
Seems like a topic to discuss in the API sync then as we're already inconsistent

**Comment by meganrogge** [comment]
@jrieken said we should go with `terminalQuickFixes` instead and consider migrating to `terminalProfiles` in the future as well
