### ISSUE TITLE
Quick pick flickers

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167554]
Testing #167161

Quick pick flickers

![Code_-_Insiders_GuqXXQQDGl](https://user-images.githubusercontent.com/2931520/204561013-ae42a887-f5a2-47a7-9afc-9a47d437d68b.gif)

First screen (is only visible for ~100 ms on my machine):

![image](https://user-images.githubusercontent.com/2931520/204561194-1e655225-0bcf-4abd-a741-58f265ca478f.png)

Second screen:

![image](https://user-images.githubusercontent.com/2931520/204561267-5ec1a290-abdd-4fc4-a667-da7271eb3285.png)

**Comment by bpasero** [comment]
This looks like https://github.com/microsoft/vscode/issues/167520

**Comment by sandy081** [comment]
@bpasero I do not think so, this is different than other issue.

I think the flickering is coming from loading the quick pick options. I am showing the quick pick and loading the options by setting the busy flag of quick pick to true. May be I can load the options and show the quick pick, but there might be a delay between clicking the export button and seeing the quick pick 🤔

**Comment by sandy081** [comment]
@TylerLeonhardt Transferring this to you because, I am loading and showing the check box items async mean while I am using the busy indicator. I assume all quick picks have same issue if the items are shown async.
