### ISSUE TITLE
unsafe repositories multiple repo warning text needs tuning

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#167595]
Testing #167413

The warning text confused me (was it talking about the parent folder?) and is only partially pluralized:

![image](https://user-images.githubusercontent.com/12818376/204611409-f2a3e34c-1fea-4aaa-9a9e-71609dba34a9.png)

Should the warning say "...potentially unsafe as the folders are owned....

Could the warnings be shorten to:

"The git repositories in the following folders are potentially unsafe as the folders are owned by someone other than the current user".

"The git repository in the following folder is potentially unsafe as the folder is owned by someone other than the current user".

**Comment by lszomoru** [comment]
@gregvanl, thank you very much for the improved message.

**Comment by gregvanl** [comment]
Looks like the warning text and UI has moved on from the proposed suggestion. New messaging looks good

**Comment by lszomoru** [comment]
@gregvanl, yes, we have tweaked the messaging a little bit. Thanks for your help!
