### ISSUE TITLE
Extension request through shared process: Proxy setting not applied

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#167508]
Testing #167383

The requests are not using the proxy setting:
<img width="740" alt="image" src="https://user-images.githubusercontent.com/9205389/204501061-f27c5749-94a9-402b-a2b9-32bd67295bd2.png">

**Comment by chrmarti** [comment]
`HTTP_PROXY` and `HTTPS_PROXY` env variables also have no effect on those requests. (I see other requests going through the proxy, e.g., for the update server, experiments, probably check for newer extension versions, but not queries from the Extensions viewlet.)

Same when setting the web proxy in the OS. Only setting the secure proxy in the OS has an effect (but doesn't work because my test proxy is not "secure"). Safari successfully uses the web proxy (also for HTTPS).

Where do you make the request in code? Is this using Node API?

**Comment by sandy081** [comment]
@chrmarti can you please check if it works as expected when you set this setting `developer.sharedProcess.redirectRequestsToMain` to `false` ?

**Comment by chrmarti** [comment]
Actually, both works. I didn't see the proxy log the marketplace connection until after I closed VS Code. Maybe the connection is kept open and the proxy only logs it when it closes. 🤷‍♂️ 

Will retest tomorrow.

**Comment by chrmarti** [comment]
Works for me.
