### ISSUE TITLE
Add terminal quick fix provider for npm in the built-in npm extension

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167588]
I noticed the terminal quick fix API is now available: https://github.com/microsoft/vscode/issues/162950

We can self-host this by using the API to implement actions in the `npm` extension, both for built-in suggestions (e.g. `npm audt`) or typo's in npm scripts (`npm run wathc`)

fyi @meganrogge

**Comment by meganrogge** [comment]
@connor4312 I don't think needs a TPI, do you? Just need the tester to run some erroneous `npm __` commands I think
