### ISSUE TITLE
Terminal quick fix - Opener type shows [object Object]

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167589]
Testing #166762

<img width="443" alt="image" src="https://user-images.githubusercontent.com/323878/204605487-e60b3434-3a8a-48f3-a915-9e44c31c4c6b.png">

<img width="438" alt="image" src="https://user-images.githubusercontent.com/323878/204605710-3d9ff7d9-0d6d-45f2-9812-8e20712a1c3b.png">

**Comment by roblourens** [comment]
A string works, but the API says Uri, which is correct I think

**Comment by Tyriar** [comment]
This is pretty bad, but since it's still proposed let's do next iteration.

**Comment by roblourens** [comment]
I didn't mention this explicitly but if it makes a difference, it also didn't open the link, when using a URI. With a string it opens the link correctly.

**Comment by Tyriar** [comment]
@meganrogge I think you might have fixed that problem of URIs vs strings?

**Comment by meganrogge** [comment]
`openerService.open` takes a `URI`, so I'm surprised this isn't working

https://github.com/microsoft/vscode/blob/a6b1e22ce8fb992895db16a3fa0ff90d584ded57/src/vs/workbench/contrib/terminal/browser/xterm/quickFixAddon.ts#L354-L365

**Comment by roblourens** [comment]
I think if it was a URI, it would also get stringified properly, so maybe it's UriComponents or something

**Comment by Tyriar** [comment]
@meganrogge do we call `URI.revive` if it's a URI like this?

https://github.com/microsoft/vscode/blob/2a16bdb4677649893126816d2e22fce76288eeb7/src/vs/workbench/contrib/terminal/browser/remotePty.ts#L170

**Comment by meganrogge** [comment]
no - that's probably the issue - though not sure why that wouldn't be handled in the `openerService` as it's expecting a `URI`

**Comment by Tyriar** [comment]
@meganrogge `URI.revive` is just a special deserialization thing we need to do to fix up the object once it comes over to/from the exthost. We wouldn't want to add it everywhere we use a URI so we try use it as soon as the URI comes over.

**Comment by Tyriar** [comment]
Take care in verifying this one as the change to fix was relatively large.

**Comment by meganrogge** [comment]
Verify that:

- the builtin opener quick fix still works: push a new branch, set the upstream origin, you should see a quick fix to create a PR
- providing a `vscode.Uri` of both the `file` and `link` variety works

**Comment by meganrogge** [comment]
example provider:

```
function provideTerminalQuickFixes(result: {
		commandLine: string;
		commandLineMatch: RegExpMatchArray;
		outputMatch?: {
			regexMatch: RegExpMatchArray;
			outputLines: string[];
		};
	}) {
		if (!result?.outputMatch) {
			return;
		}
		const actions = [];
		const results = result.outputMatch.regexMatch[0].split('\n').map(r => r.trim());
		for (let i = 1; i < results.length; i++) {
			const fixedCommand = results[i];
			if (fixedCommand) {
				actions.push({
					type: 'opener',
					uri: vscode.Uri.file("/demo.png")
				},
				{
					type: 'opener',
					uri: vscode.Uri.parse("https://google.com")
				});
			}
		}
		return actions;
	}
	(vscode.window as any).registerTerminalQuickFixProvider('myprovider', { provideTerminalQuickFixes });
```

**Comment by joyceerhl** [comment]
Yesterday's insiders: ![image](https://user-images.githubusercontent.com/30305945/205351875-d20cbfa9-b340-4e60-8a8e-ea4fc47ee3aa.png)

Today's insiders: 
![image](https://user-images.githubusercontent.com/30305945/205351937-9356853c-8f69-4b17-8deb-d53396b8fc64.png)

Builtin quickfix still works as well.
