### ISSUE TITLE
Continue On in web terminal/debug without remote repository should not mention working changes

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#167524]
Testing #167433

This is missing some action or doc link that I can try or learn about Continue On:
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/9205389/204524833-26b2fcaa-21ff-4d02-859f-e7453c42d448.png">

**Comment by chrmarti** [comment]
Same in the debug viewlet, additionally the first section seems to be misleading (since debugging is not possible at all?):
<img width="302" alt="image" src="https://user-images.githubusercontent.com/9205389/204525223-2d8df4ec-3470-4019-8475-9b8d7b84779b.png">

**Comment by joyceerhl** [comment]
🤔 are you in a GitHub repositories workspace? If in https://insiders.vscode.dev/github/microsoft/vscode there should be an action like so:

![image](https://user-images.githubusercontent.com/30305945/204617417-8920d192-7bae-4774-8f54-b6542c57fa08.png)

Debugging is now possible: https://github.com/microsoft/vscode/issues/167399

**Comment by chrmarti** [comment]
I didn't have a repository open. With that the buttons are shown. Maybe with an empty window there is still a way to use Continue On to switch to other environments? The text alone is a bit confusing.

**Comment by joyceerhl** [comment]
Yeah that is unsupported today and feature request is here: https://github.com/microsoft/vscode/issues/159220

In the meantime the welcome text shouldn't refer to working changes if the Continue Working On action isn't available.
