### ISSUE TITLE
Extension host is restarting multiple time

### ISSUE THREAD

**Issue by imranbarbhuiya** [microsoft/vscode#167550]
Type: <b>Bug</b>

Few minutes ago my vscode got updated. After that, my extensions aren't activating, I got logged out from github for copilot, copilot lab and settings sync. I tried to login again and I was able to login for copilot and copilot lab but I'm not able to login for settings sync.Also it's showing error multiple time. Here's a log from dev tool
<details>
<summary> Log </summary>

```
<--- Last few GCs --->[2064:000058C800350000]   125815 ms: Mark-sweep (reduce) 3133.6 (3472.7) -> 3133.4 (3473.7) MB, 36069.7 / 0.1 ms  (+ 25.3 ms in 2711 steps since start of marking, biggest step 0.5 ms, walltime since start of marking 37270 ms) (average mu = 0.151, current [2064:000058C800350000]   162687 ms: Mark-sweep (reduce) 3134.3 (3473.7) -> 3134.3 (3474.5) MB, 36870.4 / 0.0 ms  (average mu = 0.056, current mu = 0.000) allocation failure; scavenge might not succeed<--- JS stacktrace --->[2064:1129/200146.964:ERROR:node_bindings.cc(153)] Fatal error in V8: Reached heap limit Allocation failed - JavaScript heap out of memory
```
</details>

VS Code version: Code - Insiders 1.74.0-insider (8b9891739b703b50547f506a7e2bc9565e52beff, 2022-11-29T07:05:56.358Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.84GB (3.24GB free)|
|Process Argv|--crash-reporter-id ec92c17b-883f-4392-8d67-214edd6cbf73|
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
unocss|ant|0.47.1
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
typescript-notebook|don|2.0.6
gitlens|eam|13.1.1
prettier-vscode|esb|9.9.0
code-runner|for|0.11.8
copilot|Git|1.61.7372
copilot-labs|Git|0.4.488
remotehub|Git|0.46.0
vscode-pull-request-github|Git|0.54.1
todo-tree|Gru|0.0.220
discord-vscode|icr|5.8.0
theme-pink-candy|kub|1.3.4
scilab|mam|0.0.2
dotenv|mik|1.0.1
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.13.5
remote-explorer|ms-|0.0.2
remote-repositories|ms-|0.24.0
vsliveshare|ms-|1.0.5776
color-highlight|nau|2.5.0
material-icon-theme|PKi|4.22.0
vscode-thunder-client|ran|2.0.2
vscode-yaml|red|1.10.1
rust-analyzer|rus|0.3.1301
crates|ser|0.5.10
code-spell-checker|str|2.11.1
even-better-toml|tam|0.19.0
vscode-wakatime|Wak|22.0.1
markdown-all-in-one|yzh|3.5.0
vitest-explorer|Zix|0.2.34

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by alexdima** [comment]
There was a fix from @lramos15 that fixed things
