### ISSUE TITLE
Light bulb should be greyed out after the line/keybinding is no longer active

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167592]
Testing #166761

In the editor, users are trained that whenever they see a lightbulb, they can `ctrl+.` for a quick fix. However, in a terminal, we can show a lightbulb for a previous line:

<img width="409" alt="image" src="https://user-images.githubusercontent.com/2230985/204611258-594eceee-65c7-4dba-9b26-525751f9b5b7.png">

This light bulb can still be clicked on, but the keybinding doesn't work here. I suggest greying out (or removing) the lightbulb in this case.

**Comment by Tyriar** [comment]
This is a special case where if no command is run, the previous quick fixes are still available, for example if you double hit enter. It's correct that it's yellow but the keybinding should definitely still be working.

**Comment by meganrogge** [comment]
The keybinding still works for me even after i've hit enter a few times
