### ISSUE TITLE
Terminal quick fixes: exitStatus flag is confusing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167582]
Testing #166762

The behavior I see is that with `"exitStatus": true`, the provider only runs when the exit code was 0. With `"exitStatus": false`, it only runs when non-0. Is that right? I think there should be an option for my provider to run regardless of exit code.

**Comment by roblourens** [comment]
Or if you want the user to specify the exit code exactly, because the quick fix is targeted at a specific command and knows its behavior, that's ok. But the name and description of that property needs to be more clear.

**Comment by Tyriar** [comment]
> With "exitStatus": false, it only runs when non-0. Is that right?

That's right

> I think there should be an option for my provider to run regardless of exit code.

It was done this way to prevent accidents, a typical quick fix will almost always want to run on either success (0) of failure (non-0). Originally we had the actual exitCode, but that's not portable across OS'. 👍 to improving docs

**Comment by connor4312** [comment]
I thought `exitStatus` did the opposite and was stuck until I found this issue 😛 

Maybe the flag should be `matchWhen: /* 0 */ "succeeded" | /* non-zero */ "error" | /* any */ "exited"`

**Comment by Tyriar** [comment]
@connor4312 yeah that would probably be better, I would still exclude the "exited" one though as we want to help extension authors not be bad actors by running these regex's on successful commands unless they absolutely need to.

**Comment by meganrogge** [comment]
I was confused by `exitStatus` too, but like this proposal:

```
matchWhen: /* 0 */ "succeeded" | /* non-zero */ "error"
```

**Comment by connor4312** [comment]
nit on my own suggestion: maybe `matchOn: success | error` -- "succeeded" is a state and "error" is not, "errored" is but it doesn't sound nice 😛

**Comment by Tyriar** [comment]
I still prefer "exitStatus" though as matchOn/When doesn't strongly indicate it's about the how the command exited.

**Comment by meganrogge** [comment]
`matchOnCommandResult: success | error`?
