### ISSUE TITLE
Display branch name in the commit button pop-up

### ISSUE THREAD

**Issue by jej** [microsoft/vscode#167545]
In the source control, after changes are staged and a commit message is provided, it's no more possible to see easily the current branch name to commit to:

![screenshot_20221129-151517](https://user-images.githubusercontent.com/33821/204554004-0a35a93b-6dcb-4813-8076-4308066803f1.png)

The validation button displays a pop-up message, but this does not really add value:

![screenshot_20221129-151518](https://user-images.githubusercontent.com/33821/204554167-731c988b-6658-4817-aa91-2563f0c7d0a0.png)

I propose to display the current branch name in this pop-up:

![screenshot_20221129-151520](https://user-images.githubusercontent.com/33821/204554354-b06a77fa-30cd-45ab-8477-9618f284fb51.png)

This would dispel any doubts about the branch on which one commits. By the way, the same is possible for the "Publish Branch" button.

Is it the right idea?

**Comment by babakks** [comment]
I'll submit a PR for this.

**Comment by jej** [comment]
Whoaww, great, thanks. I had a look on it, mostly for curiosity, but I am very far from vsc dev currently...

I will review with pleasure.

**Comment by babakks** [comment]
@lszomoru @jej It's ready for review.

**Comment by jej** [comment]
It looks so easy! Thanks.

Do you think the 'Publish Branch' popup should be relooked too? The branch name appears in the commit textfield, but depending of the sidebar size it's not always visible.

![screenshot_20221201-120734](https://user-images.githubusercontent.com/33821/205037518-4768fa5b-0f0b-4763-9235-96391f6b0103.png)

**Comment by babakks** [comment]
That makes sense. I'll update the PR.

**Comment by jej** [comment]
> I first thought this was stated in the issue description too, but it wasn't. So

It is, at the end:

> By the way, the same is possible for the "Publish Branch" button.

**Comment by jej** [comment]
I guess I have to compile the whole vscode if I want to live test?...

**Comment by babakks** [comment]
@jej Yes. If it's your first time, I suggest using GitHub Codespaces or dev containers, instead of compiling/running it on your plain OS environment.

**Comment by babakks** [comment]
@jej I've updated the PR to include the branch name on the "Publish Branch" button, too.

**Comment by lszomoru** [comment]
Verification steps:
* Commit action button
  * Open a folder/workspace that contains a git repository using VS Code Insiders
  * Make a change to a file, and save the file
  * Switch to the "Source Control" view and hover over the "Commit" action button
    * Confirm that the tooltip of the action read `Commit Changes on "<branch name>"`

* Publish Branch action button
  * Open a folder/workspace that contains a git repository using VS Code Insiders
  * Create a new branch
  * Switch to the "Source Control" view and hover over the "Publish Branch" action button
    * Confirm that the tooltip of the action read `Publish Branch "<branch name>"`

**Comment by jej** [comment]
Hi,

Both verification steps are working.

Thanks.

Version: 1.75.0-insider
Commit: 9ccc2b3b30c122afe45bc6722bef0e3901fb2806
Date: 2023-01-20T05:23:42.626Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Linux x64 6.0.0-0.deb11.6-amd64
Sandboxed: Yes

**Comment by babakks** [comment]
@lszomoru @jrieken 
Do we need to submit a PR to include this in the release notes?
