### ISSUE TITLE
Unable to click setting indicator hover to focus it

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167597]
Testing #167084

![Recording 2022-11-29 at 10 18 38](https://user-images.githubusercontent.com/30305945/204613670-ab089d6c-700d-4ee0-9acc-d17fb4ca09cc.gif)

**Comment by rzhao271** [comment]
Does holding down the alt key after the hover shows up help "lock" the hover so that one can mouse over it?

**Comment by joyceerhl** [comment]
Yes it does--I was under the impression that holding alt wasn't necessary though based on

> Alternatively, one should be able to hover over an indicator with a mouse, and then click on the hover to focus it.

**Comment by rzhao271** [comment]
Seems to be fixed now
