### ISSUE TITLE
Missing terminal quick fixes after hitting a breakpoint

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167572]
Testing #166762

- Debug the example
- Hit a breakpoint in the provider, then continue
- The quick fix lightbulb doesn't appear in the terminal
- Hit enter
- The lightbulb appears

<img width="481" alt="image" src="https://user-images.githubusercontent.com/323878/204597216-76ed476e-c0ef-479d-84bc-34c1e52efd12.png">

**Comment by roblourens** [comment]
Once this happened when not hitting a breakpoint, and my provider was changed, so it was even just the built-in git provider.

<img width="494" alt="image" src="https://user-images.githubusercontent.com/323878/204601411-b56462a4-c8ed-4fa0-8133-9244e5645bdb.png">

**Comment by meganrogge** [comment]
I am not sure how we would fix this and don't think it will be an issue ppl hit
