### ISSUE TITLE
Debug console filter input box traps focus after tabbing

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167594]
Testing #167084

After entering a search query in the settings editor query box, I started tabbing in order to try navigating to the `emmet.extensionsPath` setting using only the keyboard. At some point I overshot and tabbed out of the settings editor and focus got trapped in the debug console filter box (which I had open at the time), and I couldn't move focus out of it by hitting esc. Not sure if this is an accessibility bug but figured I'd file it anyway.
![Recording 2022-11-29 at 10 12 54](https://user-images.githubusercontent.com/30305945/204612431-f1013a44-c0a7-4faa-a815-abaecc542b7d.gif)

**Comment by rzhao271** [comment]
Holding down Shift+Tab seems to cause the focus to go in a loop around the editor, but holding down Tab results in focus stopping once it reaches the Filter textbox in the Debug Console.

**Comment by roblourens** [comment]
What's going on here @sandy081?https://github.com/microsoft/vscode/blob/395753c740b3811ab6df7113eaa6c5b33f8aab53/src/vs/workbench/browser/parts/views/viewFilter.ts#L233

**Comment by roblourens** [comment]
Thanks!
