### ISSUE TITLE
SCM view could show repository erorr more in context?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167516]
Testing #167413

In the mixed case I noticed the error toast appearing. Maybe we could show the problem more in context and show an entry in the changes view for the repository but including the welcome contents?

Might get tricky with more repositories but thought I would suggest it anyway.

**Comment by lszomoru** [comment]
Thanks for the feedback. I did an exploration to introduce [proposed API](https://github.com/microsoft/vscode/issues/161200) that would enable us to show a notification within the SCM viewlet for a repository. That API would have enabled us to "open" the repository but show a warning message in the context of the repository similar to the screenshot from here - https://github.com/microsoft/vscode/issues/157159. 

The issue that I ran into is that going down that path, we would have had a repository in the SCM viewlet but all actions taken on that repository would have failed as git considers the repository unsafe so we would have had to introduce a context key and add it to *all* git commands. So for the time being we opted for a simpler solution and we will reconsider based on feedback.
