### ISSUE TITLE
QuickPick item: Icon on inline button not centered

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#167527]
<img width="663" alt="image" src="https://user-images.githubusercontent.com/9205389/204526644-e9f82379-9d34-4203-bccc-81a8675a772a.png">

Version: 1.74.0-insider (Universal)
Commit: 8b9891739b703b50547f506a7e2bc9565e52beff
Date: 2022-11-29T07:10:26.814Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: Yes

**Comment by TylerLeonhardt** [comment]
I feel like this is an issue with the codicon... but I'll own the issue for now til I can dig deeper.

**Comment by TylerLeonhardt** [comment]
This should be fixed by now
