### ISSUE TITLE
Should the setting have a default?

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167532]
Testing #167439

I was wondering why the setting has a default at all:

![image](https://user-images.githubusercontent.com/900690/204534376-85f55650-8ecb-47a5-ad72-d1d155aedcbd.png)

**Comment by lramos15** [comment]
The thought process here is that these are often folders containing code that isn't your and instead a large set of modules which can be annoying to reveal and expand your explorer that much. Often times when you go to definition of a file belonging to a node module you don't care about the folder structure of the module, but instead just about viewing that file.

**Comment by bpasero** [comment]
I see, thanks for clarifying. I wonder if we should revisit these defaults based on more modern setups. For example `bower_components` is from a time like 6y ago? I am not even sure if relevant anymore or if there are more common folders today in modern web projects.

**Comment by lramos15** [comment]
> I see, thanks for clarifying. I wonder if we should revisit these defaults based on more modern setups though. For example `bower_components` is from a time like 6y ago? I am not even sure if relevant anymore or if there are more common folders today in modern web projects.

Agreed, bower_components is historical. `node_modules` is the one I hear complained about most. Maybe we can take a look at some of the defaults for each languages .gitignore that GitHub provides when creating a repo as inspiration?

**Comment by bpasero** [comment]
Yeah I also had thought that popular `.gitignore` for web projects are good. We are a bit opiniated though in that we only care for web folders currently. I wonder if we should in general pick a better default that works for more of our core supported languages.

**Comment by lramos15** [comment]
If we do revisit these defaults probably want to revisit them for `search.exclude` and other `*.exclude` settings as that's where we took inspiration for these defaults from

**Comment by bpasero** [comment]
Yup same feeling, maybe for December.

**Comment by gjsjohnmurray** [comment]
Also see #168408 for a person who was confused by how these defaults operate, edited the JSON value down to `{}` and found that the default excludes still applied.

**Comment by lramos15** [comment]
cc @andreamah for thoughts as well since these would have to mimic a change in search defaults

**Comment by andreamah** [comment]
I would think that it'd be best to keep the default to avoid `node_modules` in search by default. For the most part, it'll just cause unnecessary files to appear when searching for most people, which would be a bit annoying imo. Why can't we just keep our settings for `search.exclude` and change the ones for auto-reveal? Do they need to be the same?

**Comment by lramos15** [comment]
Haven't gotten many complaints and doesn't seem like there is much desire around the discussion for changing these, so closing as out of scope for now.
