### ISSUE TITLE
Quick pick progress bar is not below input box

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167507]
I just now noticed how the progress bar was a the very end of the quick pick but not below input box, I think it should be below input box because the progress is for what I typed.

Steps:
* have some history entries in Cmd+P picker
* be on a slow OS (Windows)
* start to type and notice progress bar is below the history entries

//cc @daviddossett

**Comment by daviddossett** [comment]
Seems like this might have been a regression at some point. 👍 for relocating it back near the input.

**Comment by TylerLeonhardt** [comment]
I like where it is now

**Comment by bpasero** [comment]
The reason I do not like it:
* the progress bar is at a non-deterministic location depending on the number of items
* the progress bar indicator is away from the location that triggers it (the input box)
