### ISSUE TITLE
Promote environment vars to global recognition in `launch.json` and parse them before plugin launch

### ISSUE THREAD

**Issue by briantopping** [microsoft/vscode#167576]
Setting environment variables in a run/debug configuration is hit or miss. Some plugins support an `env` element, others do not. This is frustrating and can lead to days of lost time when the developers of an otherwise excellent plugin forget to provide this facility. Modern containerized apps and CI/CD is heavily dependent on environment variables, debugging these components can be difficult without the settings.

I'll advocate that the idiomatic `env` tuple array should be supported at the global level and also at the configuration level. These would be merged and set before a configuration is launched. This would be forward and backward compatible with the existing plugin universe, if a plugin didn't know the `env` key was overloaded, it would merely overwrite the environment passed in with the variables it found in the configuration it was launched with. In other words, plugin use of the `env` key becomes superfluous but not harmful. For plugins that don't already support the `env` key, the environment they were passed would have the proper environment defined already.

I can't think of any reasons that this would not be beneficial.

**Comment by roblourens** [comment]
Sorry, this just isn't possible. A debug adapter launches the debuggee, and even if vscode sets some environment variables in the debug adapter's environment, this won't have the desired effect in all cases. Please file issues on debug extensions when you notice that one doesn't provide this functionality, I agree that it's generally pretty basic and useful.

**Comment by roblourens** [comment]
From that perspective, it's too late- me asking an extension author to implement something isn't much different than you asking them to implement something (you might think it is but it isn't)

But I have to ask... how many different debug adapters are you using? Because your phrasing makes it sound like it must be a large number

**Comment by briantopping** [comment]
Thanks Rob, I appreciate your response. I understand these decisions are difficult and are based on a context that an outsider is unlikely to grasp. 

The number of DAs we are using is not huge, but environment variables have become a critical aspect of modern CI/CD. I'm more focused on the risk aspect that such large-scale omissions present to teams. Don't want to completely FUD this up, but plugins like Google Cloud Code are closed source and there's **nothing** we can do there. For the task at hand (debugging a large stack of containers via automation of Delve connections with Skaffold), there's really no way to do this except with IDE support and GCC doesn't support setting environment in VSC (although they do in IntelliJ).

I've resorted to launching VSC from the command line with the required environment set. It does indeed work, this solution would have absolutely fixed it. 

Of course it's impossible for either of us to know what the exact proportion of DAs this would similarly work for, but it's not a breaking change as you seem to suggest. It simply wouldn't have any effect for DAs that somehow prune the environment when they sub launch and would be superfluous for DAs that allow an `env` element already and don't prune the environment. 

Because of this backward compatibility, plugin authors moving forward could choose to inherit the provided environment and simply stop supporting their locally defined one. This would have the effect of a proper migration and unification over time. 

Do you agree with what I am saying here?

**Comment by roblourens** [comment]
I'm telling you that it's not really possible for vscode to have reliable control over the environment variables that end up in a debuggee, either on a per-DA or per-launch basis. You've found a case where it works, that's good. It wouldn't work well for DAs that use the `DebugAdapterDescriptorFactory` (DAs running in the EH, or spawned from the same environment, not by vscode). It wouldn't work at all for models where one DA controls multiple debug sessions. I won't try to implement something as a built-in vscode feature that can't work reliably.
