### ISSUE TITLE
Accounts activity takes seconds to open

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167521]
It seems the opening of that menu is blocked by some network activity.

![Recording 2022-11-29 at 12 55 00](https://user-images.githubusercontent.com/900690/204522722-3de242a5-2b28-4e75-92b7-b997db301b55.gif)

I am on a slow OS (Windows) which maybe makes this issue more obvious compared to my other machine (macOS). 

Marking important because I felt the action was broken altogether.

**Comment by bpasero** [comment]
Previously reported as https://github.com/microsoft/vscode/issues/111398

**Comment by sandy081** [comment]
Starting with @TylerLeonhardt for initial investigation.
