### ISSUE TITLE
Searching inconsistently searches everything or a subset

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16759]
#16416

- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T17:07:24.668Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|typescript-javascript-grammar|ms-vscode|0.0.10|
|sass-indented|robinbentley|1.2.1|
|dark-plus-material|vangware|0.1.4|

---

Searching for `t` searches for about a minute with no popup:

![image](https://cloud.githubusercontent.com/assets/2193314/20946611/49751180-bbc0-11e6-9901-dd9c529f4cc3.png)

Searching for `test` searches for ~4 seconds and gives this popup when it obviously would have less results than `t`:

![image](https://cloud.githubusercontent.com/assets/2193314/20946662/79ab14da-bbc0-11e6-8474-c811d82b310c.png)

**Comment by Tyriar** [comment]
Another search for `t` gave me the popup, then the next search went on for a minute or so again.

**Comment by roblourens** [comment]
I think this is the same as #16653
