### ISSUE TITLE
Hover steals focus

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167520]
Opening the "Delete..." action closes the picker right after opening:

![Recording 2022-11-29 at 12 48 54](https://user-images.githubusercontent.com/900690/204521354-c5f67c46-f7cb-4875-b5f8-e9123f3a8381.gif)

**Comment by bpasero** [comment]
@sandy081 
![Recording 2022-11-29 at 17 13 16](https://user-images.githubusercontent.com/900690/204582787-c40209eb-0825-481e-bd80-98fa3588f917.gif)

**Comment by bpasero** [comment]
Something weird is going on with that quick pick, for example when it opens I do not see a blinking cursor!

Debugging this, here is the stack trace that leads to quick pick closing:

```
hide (quickInput.js:1394)
(anonymous) (quickInput.js:1035)
invoke (event.js:514)
deliver (event.js:688)
fire (event.js:653)
(anonymous) (dom.js:726)
setTimeout (async)
onBlur (dom.js:722)
(anonymous) (hoverService.js:37)
invoke (event.js:514)
deliver (event.js:688)
fire (event.js:653)
dispose (hoverWidget.js:479)
hide (contextview.js:239)
hideContextView (contextViewService.js:62)
hideHover (hoverService.js:84)
(anonymous) (compositeBarActions.js:270)
```

**Comment by sandy081** [comment]
I suspect this is caused by some focus issues. There may be focus out after quick pick is shown and therefore quick pick is disappearing. Any help how to debug such issues? Its also not always consistent to me.

**Comment by bpasero** [comment]
A regression from https://github.com/microsoft/vscode/commit/dbe96ecc1ec325d3bd45c497b8265fe3ea3a25a5

**Comment by rzhao271** [comment]
I am able to repro this intermittently on macOS.
1. Open the Settings editor.
2. Open the hover for a Modified elsewhere setting indicator, focus it, and tab around.
3. Press the escape key to close the hover. Check that focus is on the setting or the indicator.
4. Click Accounts > Settings Sync. A quickpick should show up.
5. Slowly move up the mouse.
6. :bug: The quick pick closes.
