### ISSUE TITLE
terminal quick fix contribution: improve property descriptions

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#167590]
Testing #166762

<img width="302" alt="image" src="https://user-images.githubusercontent.com/6461412/204605585-9b0a8baf-f79e-44f5-9f31-a246363af254.png">

- lineMatcher: describe that this is can be a regex which will be the input to the provider?
- commandLineMatcher: is this also a pattern?
- anchor: `Which side of the output to anchor the offset and length against` not sure what that means

**Comment by Tyriar** [comment]
Related: https://github.com/microsoft/vscode/issues/167557
