### ISSUE TITLE
Language pack recommendation - Locale unset

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#167540]
Testing #167105

I went through the "Locale unset" steps on an M1 Mac and here is what I have observed:
* The scenario steps imply that after setting the display language, and restarting the machine VS Code would start up in French and no notification would be shown. In my case, VS Code started in English and a notification was shown to install the French Language Pack. After installing and restarting VS Code was in French.
* The `locale` key was not present in the `argv.json` file.

It's interesting that *after*, I have uninstalled the French Language Pack and VS Code is still in French 🤷🏻‍♂️  
I was also able to reproduce the same when running through "Scenario4". There is definitely something on macOS where the language on VS Code is not being set, and a notification is being shown to install the language pack for the `locale` that is specified in the `argv.json` file

**Comment by lramos15** [comment]
I did not see the locale get set in `argv.json` on linux either.

**Comment by meganrogge** [comment]
no locale set on windows either

**Comment by rzhao271** [comment]
I think I confused the behaviour of "Configure Display Language" with the behaviour of installing a language extension and restarting. I believe that the language should still be configured in the argv.json file after installing the extension pack if it is installed by clicking on the "Install and restart" button.
