### ISSUE TITLE
Cannot find Continue On in SCM view

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#167529]
Testing #167433

The instructions say "Continue Working On is surfaced in the SCM view as a secondary action in the SCM action button dropdown", but I don't see Continue On in the viewlet menu (...) nor in the blue button drop-down. Codespaces is the only remote extension installed.

<img width="193" alt="image" src="https://user-images.githubusercontent.com/9205389/204528492-2ed3471d-104f-430e-8993-40f8f61d7571.png">

<img width="434" alt="image" src="https://user-images.githubusercontent.com/9205389/204528554-7538a11e-2043-46f7-b226-2aca7ef6cebe.png">

**Comment by joyceerhl** [comment]
This is as expected. Sorry, the TPI should have specified that Continue Working On is only available with folders and workspaces opened via the GitHub Repositories extension.
