### ISSUE TITLE
Many Places Trust Storage Service

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#167567]
Testing #167161

https://github.com/mjbvz/vscode/blob/ce890f008cbda487ccf57e86c5055138939151df/src/vs/platform/quickinput/browser/commandsQuickAccess.ts#L235

I'm very sure that things crash when you pass in `{"usesLRU":true,"entries": 123}`.

When exporting a profile, modifying the profile a bit and then importing it, a buggy profile dump can bring VS Code into an inconsistent state.

Before importing a profile, that profile file should be trusted anyways, so feel to close this issue.

**Comment by sandy081** [comment]
It is true for any kind of data in the profile for eg., there can be a invalid setting value. But I think our system shall be resilient to any such invalid values. May be one idea is to try out the profile by creating a temp profile with the given contents and if things look good, then user can save the profile.

CC @isidorn

**Comment by isidorn** [comment]
@hediet thanks for raising this interesting issue.
@sandy081 I agree that ideally our system should be resilient as much as possible. Creating a temp profile and then saving it sounds like extra effort. I would prefer if the Profile View has some minor UI that mentions "Trust" that users would see before applying the profile.

**Comment by sandy081** [comment]
> I would prefer if the Profile View has some minor UI that mentions "Trust" that users would see before applying the profile.

We can, but I do not know if it is helpful. Because, for eg., how does user understand a storage value and say that can be trusted? I think the trust shall be made on the URL and not on the contents.

**Comment by isidorn** [comment]
@sandy081 the message should not be around the "content" but about the author of the profile. "Make sure you trust the author of this profile"
That is easier for users to figure out.
