### ISSUE TITLE
comments.visible should explain how it works with the Comments view

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#167569]
Testing #167403

Steps:
1. Open vscode
2. Checkout PR with comments
3. Set comments.visible to false

:bug: => Comments view, comment ranges, plus icon, peek comment widget all seem to be present, even after reloading

**Comment by eleanorjboyd** [comment]
I am seeing similar behavior, when I add `"comments.visable": false,` to my settings and hover over it, it says `Unknown Configuration Setting` so I am not sure if I am doing it incorrectly or if it is what SteVen is seeing.

**Comment by sbatten** [comment]
@eleanorjboyd it looks like you have a typo in "visible" making it unknown

**Comment by eleanorjboyd** [comment]
yep that was my mistake 🤦‍♀️

Thanks for the fix, I got the setting working and found some different behavior from you. The comments disappeared for me after I switched the setting and so it hid PR comments I had in a python file.

**Comment by alexr00** [comment]
@sbatten I'm not able to reproduce this. Are there any other details of your setup that might be relevant? 

Worth noting: `"comments.visible": false` does not disable the Comments view. If you open the comments view then click on a comment then comment visibility will be toggled back on.

**Comment by sbatten** [comment]
@alexr00 thanks for the explanation, that was my confusion. can we repurpose this issue to address the confusion in the setting description. Perhaps an additional sentence: You can still access comments via the comments view and this setting will be ignored for the remainder of the session if so.
