### ISSUE TITLE
not sure how to uninstall language packs

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#167651]
Testing #167105

I expected there to be a gear icon on the quick pick items in the `installed` list 

![Screenshot 2022-11-29 at 5 00 02 PM](https://user-images.githubusercontent.com/29464607/204667046-e5d64df1-eea4-43fc-9902-fafd08c9cf08.png)

**Comment by meganrogge** [comment]
oh I realize that this is a system / OS installation, so maybe this doesn't make sense. could we indicate this somehow?

**Comment by rzhao271** [comment]
Language packs are a category of extensions, so they're uninstalled through the extension view. Is the problem that VS Code is still stuck in the language after removing the language pack?

**Comment by meganrogge** [comment]
I was expecting a way to uninstall a language via that quick pick. I was confused bc thought we were pulling those languages from the system language installations

**Comment by meganrogge** [comment]
Could we have a button on the quick-pick for each item in the list of `installed` that allows you to uninstall that language pack?

**Comment by sandy081** [comment]
I also like Option 2.

BTW There is a command `workbench.extensions.uninstallExtension` to uninstall extension by id. Best case I can also move this as an API of `extensionManagementService`

**Comment by TylerLeonhardt** [comment]
@sandy081 what would be the API for showing the extension editor?

**Comment by sandy081** [comment]
Its in workbench 

https://github.com/microsoft/vscode/blob/d5ab02349e576d39cc4bb5ca3cd5f33c6289c296/src/vs/workbench/contrib/extensions/common/extensions.ts#L115

You can also use the command `extension.open` by passing extension id

**Comment by TylerLeonhardt** [comment]
Verification: Now open `Configure Display Language` and you should see a `More info` button on all the language packs. That will take you to the Extension editor where you could uninstall a pack if you have it installed.
