### ISSUE TITLE
Terminal became unresponsive, telemetry output disappeared

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#167609]
Testing #167475

Version: 1.74.0-insider (user setup)
Commit: 8b9891739b703b50547f506a7e2bc9565e52beff
Date: 2022-11-29T07:05:56.358Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25247
Sandboxed: Yes

Steps:
- Open a GitHub repo in VS Code Insiders
- Set telemetry log level to debug
- Experiment with different git commands in terminal, attempting to test [quick fixes](https://code.visualstudio.com/docs/terminal/shell-integration#_quick-fixes)
- After one of several `git push` commands, VS Code is stuck loading (SCM view doesn't show commit is pushed, status bar shows loading indefinitely)
- :bug: Eventually get a notification that the pty host in the terminal has become unresponsive. I needed to close all open VS Code instances to get back to a working terminal
- :bug: Though the terminal works now, I can no longer find the telemetry output channel - I've run the command to set log level and reloaded several times:

![image](https://user-images.githubusercontent.com/25310137/204623505-79f3e5c5-027b-4cf9-98d5-7f533d9cb085.png)

![image](https://user-images.githubusercontent.com/25310137/204623260-3d580c02-7729-4871-8b51-6afcbda4464f.png)

**Comment by bamurtaugh** [comment]
Seems setting the log level to `trace` rather than `debug` results in the Output channel displaying - should we be testing with `trace` instead?

![image](https://user-images.githubusercontent.com/25310137/204624084-5f77092b-fb8b-4f1e-b5da-f35c73ce9da4.png)

**Comment by Tyriar** [comment]
Yes trace is right as mentioned in https://code.visualstudio.com/docs/getstarted/telemetry#_output-channel-for-telemetry-events, the TPI was wrong here.

**Comment by bamurtaugh** [comment]
If I encounter again, I'll definitely share a gif - it felt like it all happened so fast that I didn't capture a gif this time.

It does look like the issue you linked - I saw the message in https://github.com/microsoft/vscode/issues/130320#issuecomment-916179807.

**Comment by meganrogge** [comment]
Debug level works for me - we log at that level exactly what is sent as telemetry

![Screenshot 2022-11-29 at 1 21 32 PM](https://user-images.githubusercontent.com/29464607/204626976-345ac013-5545-4693-98fe-aa9175fc954f.png)

**Comment by meganrogge** [comment]
@bamurtaugh pls reopen this if you see this again
