### ISSUE TITLE
undo inline conflicts with mac keyboard shortcut

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#167633]
I was testing: https://github.com/microsoft/vscode/issues/167421 and set 

> "key": "alt+shift+left",
    "command": "undo",
    "when": "inlineSuggestionVisible"

except since mac North America does not have an option key the alt is the replacement and on vscode for Mac the setting I have (which I think is the default since I haven't changed any keybindings) has "control+shift+left" as "shrink select" so it does that instead of the undo. Therefore another key binding is probably better but I do like the fill line and undo are mirrored.

**Comment by hediet** [comment]
Thanks for trying out the feature! What keybinding pair do you suggest?
What about ctrl+right/ctrl+left?

**Comment by eleanorjboyd** [comment]
Sorry yes I didn't provide other options. ctrl+right switches screens on my mac so maybe option+right/option+left? Not sure what the default is for other keyboards but on mine it doesn't seem like option+right/option+left is an important feature. I would also say after observing more keybindings "control+shift+left" is one of the less useful features in terms of all these keybindings for moving the curser and selecting text with key press (I didn't realize all the combos of control, shift, option, arrow keys all have functionality on my keyboard currently). I think "control+shift+left" could work but would it be possible to have the undo line take precedence over the "shrink selection"? For example if I wanted to use this feature I would be surprised one of the key bindings does something different and might not know where to go to change it to "undo" or that I had that power.

**Comment by hediet** [comment]
Undo would still be Ctrl+Z, but when there is an inline completion, it would also be available as option+right (which is the current favorite).

**Comment by hediet** [comment]
Closing in favor of #167927.
