### ISSUE TITLE
VS Code stuck in foreign language after uninstalling language pack

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#167604]
Testing #167105

Followed steps for scenario 1 and then went to complete scenario 2 by uninstalling the spanish language pack. I receive a notification that extensions have been modified on disk and my VS Code is stuck in spanish

**Comment by meganrogge** [comment]
seeing this also on Windows

**Comment by meganrogge** [comment]
clearing display language preferences does not fix it

**Comment by lramos15** [comment]
> clearing display language preferences does not fix it

For me clearing `locale` from your argv is what fixes this

**Comment by meganrogge** [comment]
for me, launching with `--locale=en` fixed it
