### ISSUE TITLE
Should it be possible to use arrows to move from one setting indicator group to another?

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167601]
Testing #167084

![image](https://user-images.githubusercontent.com/30305945/204616300-68db3bb2-c46b-448b-b2d6-27328727be1e.png)

When focus is on `Modified elsewhere` I can tab to `Default value changed`. I'm not sure if I should instead be able to use right/left arrows to move between indicator groups.

**Comment by rzhao271** [comment]
There is currently no support for using arrow keys in the indicators, but it is being tracked at https://github.com/microsoft/vscode/issues/167470.
