### ISSUE TITLE
Disassembly cannot be stopped

### ISSUE THREAD

**Issue by hongshui3000** [microsoft/vscode#167678]
Disassembly cannot be stopped once the disassembly window is opened. The disassembly works as long as the debug session starts, even if I close the disassembly window, or restart the debug session. Disassembly stops only after closing vscode and restarting the debug session

https://github.com/Marus/cortex-debug/issues/781

**Comment by roblourens** [comment]
Can you explain the actual issue in a bit more detail?

**Comment by hongshui3000** [comment]
Open the disassembly view After debugging my own program, I will turn off the disassembly to save resources. But this is after I found out that I can't close the disassembly except I close vscode. Even if the disassembly view is closed, the disassembly of gdb has been working. As long as I suspend the debugger, gdb starts to send disassembly commands.

**Comment by hongshui3000** [comment]
I hope there is a way to stop disassembly after it is turned on

**Comment by roblourens** [comment]
Are you saying that vscode is still sending a disassemble request to the debug adapter even when the disassembly view is closed? Or just that gdb is still doing disassembly unnecessarily?

**Comment by roblourens** [comment]
I don't see this happening. I need a log or something that shows that vscode is sending unnecessary disassembly requests. I don't think vscode is doing that.

**Comment by hongshui3000** [comment]
> I don't see this happening. I need a log or something that shows that vscode is sending unnecessary disassembly requests. I don't think vscode is doing that.


When I close the disassembly view and reconnect debug, the disassembly commands still work again.

[log.txt](https://github.com/microsoft/vscode/files/10174624/log.txt)

![image](https://user-images.githubusercontent.com/25566498/206140063-66cf4811-d590-4866-ae7c-bc66f16277c8.png)

**Comment by roblourens** [comment]
This isn't really enough to show that vscode is sending a disassemble request at the wrong time

**Comment by roblourens** [comment]
Sorry, this isn't really an actionable issue report from my end.
