### ISSUE TITLE
unsafe repositories empty SCM view with mixed repo scenario

### ISSUE THREAD

**Issue by gregvanl** [microsoft/vscode#167611]
Testing #167413

Followed scenario3 steps and I see the notification about the Admin owned vscode1 repo but the SCM view doesn't show vscode2.

![image](https://user-images.githubusercontent.com/12818376/204628101-3c33acb5-52b9-4be7-81d5-0a17e2eb5b49.png)

**Comment by gregvanl** [comment]
Only after opening the vscode1 repository from the notification do I see vscode2

**Comment by lszomoru** [comment]
@gregvanl, looking at the screenshot provided, it looks like the `vscode2` repository is opened in the SCM viewlet. In this case the folder/workspace only has one repository, so by default we are not showing its name. If you want to see the "repository" entry when there is only one repository opened you have to enable the `scm.alwaysShowRepositories` setting. Repository names are shown when multiple repositories are opened.

Based on the provided information the behavior that you are seeing is the expected one.
