### ISSUE TITLE
Inline Completions: Accept Next Word Should Also Split By Whitespace

### ISSUE THREAD

**Issue by eleanorjboyd** [microsoft/vscode#167637]
found from TPI: https://github.com/microsoft/vscode/issues/167421

When I am using Typescript, there is a bit of inconsistency with how it defines a "single word". I am not sure if this is intention behavior that I am seeing for which characters get group together or not. For example the chunks for the following text:
`for (const workspace of this.workspaceService.workspaceFolders || []) {`

it is grouped like so:

`for` `(` `const` `workspace` `of` `this` `.` `workspaceService` `.` `workspaceFolders`  `|| []) {`

Where `|| []) {` is much longer and contains spaces. 

Not sure what desired behavior is so this could also be expected behavior but wanted to point it out in case there was any inconsistency. Thanks!

**Comment by hediet** [comment]
This is by design.

Either the immediate next word is taken or all the text until the next word.

Maybe this should be adjusted, but that depends on how this feature is being used.

**Comment by eleanorjboyd** [comment]
Ah yes it makes sense once you explain it. I feel like the `||` is a different thought than maybe the entire `|| []) {`.

For example if I wanted that line to say `for (const workspace of this.workspaceService.workspaceFolders || Null) {` then I would have wanted to select through to `for (const workspace of this.workspaceService.workspaceFolders ||` then type Null instead of selecting `for (const workspace of this.workspaceService.workspaceFolders || []) {` then deleting to go back and writing Null.

I think either way is fine, it is more just a preference thing and people will quickly adapt to the design as they start using it.

**Comment by hediet** [comment]
We could additionally split by whitespace, let me reopen this issue for that.

**Comment by hediet** [comment]
@eleanorjboyd can you verify the fix? Thanks!

**Comment by eleanorjboyd** [comment]
Looks great! Thanks for the fix!
