### ISSUE TITLE
Prettify profile URL

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#167699]
Right now the profile URL looks like `vscode-insiders://profile-github/https%3A//gist.github.com/725177503274136f427527008dbf1463`

We should prettify it to look like `vscode-insiders://profile/gist/725...`

Idea by @joaomoreno

**Comment by isidorn** [comment]
Looks great -> verified
Current profile url is `vscode-insiders://profile/github/74980f797f903f2e479a72c817a177dc`
Can we even shorten it further - by shortening the UUID? Similar to how git shortens commits sometimes?

**Comment by sandy081** [comment]
> Can we even shorten it further - by shortening the UUID? Similar to how git shortens commits sometimes?

May be we can using some external libraries. But might not be worth for this usecase.
