### ISSUE TITLE
In-product release notes not displayed

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16767]
- VSCode Version: 1.8.0 Insiders
- OS Version: Windows 10

Steps to Reproduce:

1. Help > Release Notes
Goes out to wiki with fwlink 724002.

This is a regression from 1.7.2. The v1_8.md release notes file is now published on code.visualstudio.com/raw. If you update a 1.7.2 install package.json version to 1.8.0, Help > Release Notes works and displays v1_8.md in-product.

**Comment by gregvanl** [comment]
Might be related to recent src/vs/platform/request/electron-browser/requestService.ts work.
DevTools console shows "requestService.ts:65 undefined https://code.visualstudio.com/raw/v1_8.md 500 (Internal Server Error)"

**Comment by gregvanl** [comment]
Added this bug to the November 2016 milestone as the release notes won't display in-product unless it is fixed. An option if this issue can't be fixed is to link Help > Release notes back to the website.

**Comment by joaomoreno** [comment]
@jrieken It's the second time I see this happening: the request just goes out with an `undefined` HTTP method. Please review the fix, whether it makes sense.

**Comment by jrieken** [comment]
lgtm
