### ISSUE TITLE
notebook markdown and code cells have different left padding

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#167669]
They line up straight in vscode.dev

![image](https://user-images.githubusercontent.com/2019016/204673635-7730884e-81ba-4e3b-aded-4d6331f41978.png)

**Comment by amunger** [comment]
looks better now

**Comment by roblourens** [comment]
I think this is actually affected by a setting. Maybe compact mode, I forget, you might have had it one way in web and another in desktop.
