### ISSUE TITLE
Reopen on desktop wasn't clear to me

### ISSUE THREAD

**Issue by sbatten** [microsoft/vscode#167607]
Testing #167433 

It was probably wishful thinking, but I was misled by the last entry in this list 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/6561887/204621032-a195db4d-a96c-4086-b10b-6ac1d4d35942.png">

I thought I would get to open my existing local clone on desktop

**Comment by joyceerhl** [comment]
Sadly we have no way to acquire a full filepath on disk via the current state of the web filesystem api (that only gives you the name of the folder), so we can't support that transition from web to desktop (unless Remote Tunnels are enabled 🤔). I can rename this entry for now to make it clear that it's not about an existing local repo clone--maybe `Reopen Virtual Workspace on Desktop`?

**Comment by sbatten** [comment]
marking as verified as the new wording is there and a bit more clear, though it does introduce some terminology I'm not sure we have been using a lot elsewhere in this experience. A possible alternative: Reopen as Remote Repository on/via Desktop
