### ISSUE TITLE
Error reading broker pipe: The pipe has been ended. (0x6D) appears when i run a file

### ISSUE THREAD

**Issue by jamo2011** [microsoft/vscode#167666]
Type: <b>Bug</b>

(In C#) Whenever I hit the run without debugging it comes up with a bar at the top saying select debugger and I select .Net Framework 4.x. Nothing happens. I tried to run my code from the terminal but it says [12532:1129/181841.977:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D).
How can I run my file?

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
(In C#) Whenever I hit the run without debugging it comes up with a bar at the top saying select debugger and I select .Net Framework 4.x. Nothing happens. I tried to run my code from the terminal but it says [12532:1129/181841.977:ERROR:broker_win.cc(56)] Error reading broker pipe: The pipe has been ended. (0x6D).
How can I run my file?
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3250U with Radeon Graphics          (4 x 2595)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|13.94GB (5.20GB free)|
|Process Argv|--crash-reporter-id 70984e69-2428-4927-b100-9e5ebca4b5ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Ionide-fsharp|Ion|7.4.0
unity-code-snippets|kle|1.3.0
vscode-docker|ms-|1.23.0
csharp|ms-|1.25.2
dotnet-interactive-vscode|ms-|1.0.3553070
vscode-dotnet-pack|ms-|1.0.9
vscode-dotnet-sdk|ms-|0.8.0
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.30
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by roblourens** [comment]
Please file on the C# extension repo, thanks
