### ISSUE TITLE
Publishing crash reports flaked, failed integration tests

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167684]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=194862&view=logs&j=a8b516b9-5c25-5ad9-505a-b03d38bc1dad&t=726cfe94-b13b-50e3-ba83-4f78315cd046&l=9

**Comment by joaomoreno** [comment]
The real error is ECONNRESET when downloading Electron, which can happen randomly. Will keep an eye open for repeats.
