### ISSUE TITLE
Testing continue working on: no options for continue working on in source control viewlet?

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#167660]
Testing #167433

I'm in a remote github repo and can't find anything related to continue working on in the SCM viewlet. Is there supposed to be something here?
<img width="173" alt="image" src="https://user-images.githubusercontent.com/31675041/204670183-6e198bd6-1c20-492c-89bf-d591946328dd.png">

**Comment by gjsjohnmurray** [comment]
Does #167529 help?

**Comment by andreamah** [comment]
I was opening a repo via the GitHub repositories extension, so I was expecting to see something different?

**Comment by joyceerhl** [comment]
Are you using the pre-releases of Remote Repositories and GitHub Repositories? You should see this even on desktop 
![image](https://user-images.githubusercontent.com/30305945/204679613-41fa1533-6196-467c-9128-e1401ed20d16.png)

**Comment by joyceerhl** [comment]
I had the pre-releases but somehow got switched to the release versions, possibly while testing settings profiles

**Comment by andreamah** [comment]
I previously didn't have the pre-release for remote repos, but I still don't see anything. Does it have to do with being on Linux?

<img width="252" alt="image" src="https://user-images.githubusercontent.com/31675041/204680446-09bbbfbc-9586-477d-a2d3-dca5cc7bea30.png">

**Comment by joyceerhl** [comment]
It's a secondary action in the dropdown for the SCM action button--still too subtle, it seems :)

**Comment by andreamah** [comment]
Ahh I see it now! 

<img width="294" alt="image" src="https://user-images.githubusercontent.com/31675041/204681331-1f12d4f0-4157-48be-b05c-0e89b979a668.png">

Thanks! 🙂
