### ISSUE TITLE
Untitled editors are not force opened when auto save is on

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#167691]
A bug in our tracker for dirty models, somehow never reported but obvious in an issue I noticed with Copilot. The end result is that you see a dirty indicator e.g. in the explorer but no editor that is opening and associated with it.

Steps: https://github.com/github/copilot/issues/2362

**Comment by eleanorjboyd** [comment]
Tried to look at the steps to repro but seems the link to the copilot issue is broken or at least I am not able to access it.

**Comment by andreamah** [comment]
I'm still getting this with copilot nightly in insiders 

<img width="652" alt="image" src="https://user-images.githubusercontent.com/31675041/205178229-348bce42-83f5-4f48-ba10-fa4caf0d789e.png">

**Comment by bpasero** [comment]
Please note that my change does not fix the Copilot issue. The steps to verify are unclear: it is expected when you see an untitled editor opening. You must test with auto save on.

**Comment by bpasero** [comment]
Setting back verified label based on the screenshot.
