### ISSUE TITLE
terminal quick fix contribution: list return types

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#167621]
Testing #166762

the provider returns `TerminalQuickFix`. I first didn't see the subtypes `TerminalQuickFixCommandAction` and `TerminalQuickFixOpenerAction`.

- define `TerminalQuickFix` as `type TerminalQuickFix = TerminalQuickFixCommandAction |  TerminalQuickFixOpenerAction`
- align the naming: TerminalQuickFix -> TerminalQuickFixAction

**Comment by meganrogge** [comment]
I was told that `type=` should be avoided in the API.

**Comment by meganrogge** [comment]
`Fix` and `Action` are synonymous, so we should get rid of `Action`
