### ISSUE TITLE
Export as "Github Gist" instead of "Github"

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167628]
Testing #167161

In the export flow, there's the step to "Export as...". The options are "File" and "Github"

<img width="615" alt="image" src="https://user-images.githubusercontent.com/2230985/204645405-51b1eab9-6b3f-4e8b-9169-45f4118bc23c.png">

I can make the educated guess that I'm not exporting the whole of Github from my VS Code window, but it'd be better to say "Github Gist" instead, or "Export to" instead of "Export as". I prefer the former since it's clear where it's going--otherwise people might assume it creates a repo on their account or something.

**Comment by sandy081** [comment]
It was GitHub Gist before, after feedback I changed to GitHub. I will bring this to UX and see what other think too.

**Comment by isidorn** [comment]
Good feedback. We will also do a user study next week so we will see how users react here.

Alternative rendering: "GitHub" and then "gist" as the description a bit to the right - QuickPick should support this.

**Comment by isidorn** [comment]
There was some confusion in the user study when exporting as GitHub. They were expecting that it will be part of a repository.
So calling it GitHub Gist might be the way to go.

**Comment by sandy081** [comment]
I think adding `Gist` as description would be good

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/209675787-788eac8d-35ce-4016-8251-2ea4712dffb7.png)

**Comment by isidorn** [comment]
Lovely, tried it out. Verified.
