### ISSUE TITLE
terminal quick fix contribution: command is inserted but not actually run

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167657]
Testing #166762

For built-in quick fixes, the command is automatically run after selecting it. However, for custom ones, it just emits a ctrl+c and writes out the command without actually running it

![Recording 2022-11-29 at 15 07 47](https://user-images.githubusercontent.com/2230985/204668347-f6bdf96d-6d74-465e-8321-c7a2d777dec1.gif)

**Comment by meganrogge** [comment]
Cannot reproduce on Windows 🤔

**Comment by meganrogge** [comment]
![Recording 2022-11-29 at 15 11 40](https://user-images.githubusercontent.com/29464607/204668787-a86187ba-efbe-4976-b281-59d702233939.gif)

**Comment by meganrogge** [comment]
can you reproduce only w the contributed fix or also the builtin ones IE `git sttatus`?

**Comment by connor4312** [comment]
The built-in git one works fine, only the contributed one doesn't. The command being returned is the string `npm audit`. There's no new line at the end of that string, which might(?) be triggering the automatic entering if that's being returned in built-in matchers...

**Comment by connor4312** [comment]
Updated my original comment. I don't think it's an OS thing, probably just built-in vs contributed

**Comment by meganrogge** [comment]
This was working at one pt. Probably a regression when I removed `addNewLine` as a property. thanks for the info
