### ISSUE TITLE
Crash on CentOS 7 when opening fresh user data dir

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#167641]
1. Create a fresh user data directory.
2. Open code-insiders with `--user-data-dir` pointed to that directory.
3. Wait a bit.
4. :bug: VS Code Insiders crashes.

One of the last messages in the verbose output is "MainThreadSecretState#getPassword: Trying migration for:  github.auth".

![Screenshot showing the verbose output in the CentOS 7 VM](https://user-images.githubusercontent.com/7199958/204662916-fbd528a4-4ed1-4e3b-ae77-f58983688d8e.png)

**Comment by deepak1556** [comment]
Can you attach the crash dump following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports

**Comment by rzhao271** [comment]
Got it
[crash.zip](https://github.com/microsoft/vscode/files/10179234/crash.zip)
