### ISSUE TITLE
terminal quick fix contribution: anchor top/bottom seem reversed

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167661]
Testing #166762

The `anchor` property controls "Which side of the output to anchor the offset and length against", and can be set to `top` or `bottom`.

It seems to be functionally reversed, at least as far as I read it. If I set `length: 5` and `anchor: top`, the matcher will work if the result is in the last five lines of the output. If `anchor: bottom`, it'll work if it's in the first five lines of output.

**Comment by meganrogge** [comment]
Looks like we're doing the right thing here

<img width="997" alt="Screenshot 2022-12-09 at 8 50 26 PM" src="https://user-images.githubusercontent.com/29464607/206825177-8347479c-4459-4a83-9441-87c2e10809ae.png">
