### ISSUE TITLE
Open Workspace Settings message box opens plain settings.json

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16764]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

1. Open User Settings in folder with workspace settings
2. Get Open Workspace Settings message box
![screen shot 2016-12-06 at 2 55 03 pm](https://cloud.githubusercontent.com/assets/9205389/20947445/0a3d3994-bbc4-11e6-9388-4b55a1423b8d.png)
3. Open Workspace Settings
4. settings.json opens in second column next to User Settings editor
![screen shot 2016-12-06 at 2 55 12 pm](https://cloud.githubusercontent.com/assets/9205389/20947448/0eed2ddc-bbc4-11e6-8a4c-769d9f69fefb.png)

**Comment by chrmarti** [comment]
Also: In another workspace that message box does not show despite there being a .vscode/settings.json. Not sure if/how that could be disabled by myself. (Testing #16530)

**Comment by sandy081** [comment]
This was the same behaviour as before. But since settings are moved to single editor, opening workspace settings should also do same. Since there are some ideas in how to show workspace settings when settings are opened I am moving this to next milestone.

**Comment by LEE222** [comment]
+44 7397 326970

**Comment by sandy081** [comment]
Fixed it with single editor for user/workspace settings
