### ISSUE TITLE
Extension host is crashing with OOM

### ISSUE THREAD

**Issue by pocesar** [microsoft/vscode#167634]
Type: <b>Bug</b>

1. Start editor
2. Crashes after a couple of seconds

`Extension host terminated unexpectedly 3 times within the last 5 minutes.`

```
<--- Last few GCs --->[9276:00001D6600350000]    24696 ms: Scavenge (reduce) 3720.7 (4074.7) -> 3720.6 (4075.7) MB, 4.2 / 0.0 ms  (average mu = 0.929, current mu = 0.005) allocation failure; [9276:00001D6600350000]    24702 ms: Scavenge (reduce) 3721.7 (4075.7) -> 3721.7 (4075.7) MB, 3.9 / 0.0 ms  (average mu = 0.929, current mu = 0.005) allocation failure; [9276:00001D6600350000]    24706 ms: Scavenge (reduce) 3721.7 (4075.7) -> 3721.7 (4077.7) MB, 4.2 / 0.0 ms  (average mu = 0.929, current mu = 0.005) allocation failure; <--- JS stacktrace --->[9276:1129/182454.533:ERROR:node_bindings.cc(153)] Fatal error in V8: Scavenger: semi-space copy Allocation failed - JavaScript heap out of memory[9276:1129/182454.533:ERROR:crashpad_client_win.cc(812)] not connected
```

VS Code version: Code - Insiders 1.74.0-insider (8b9891739b703b50547f506a7e2bc9565e52beff, 2022-11-29T07:05:56.358Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3700X 8-Core Processor              (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (14.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
copy-relative-path|ale|0.0.2
vscode-tailwindcss|bra|0.9.1
path-intellisense|chr|2.8.3
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
xml|Dot|2.5.1
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.9.0
code-runner|for|0.11.8
copilot|Git|1.61.7372
ts-debug|kak|0.0.6
file-downloader|min|1.0.12
mindaro|min|1.0.120221031
vscode-docker|ms-|1.23.0
vscode-kubernetes-tools|ms-|1.3.11
remote-containers|ms-|0.262.3
remote-wsl|ms-|0.72.0
vscode-typescript-next|ms-|5.0.202211170
copy-json-path|nid|0.2.1
hardhat-solidity|Nom|0.6.2
prisma-insider|Pri|31.0.1665
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.0.2
vscode-yaml|red|1.10.1
vscode-icons|vsc|12.0.1
gitblame|wad|10.0.0

</details>

**Comment by alloy** [comment]
Same on macOS 13 arm64.

**Comment by gjsjohnmurray** [comment]
Can you use the Start Extension Bisect command to identify a specific extension that is causing this?

**Comment by GongT** [comment]
```
版本: 1.74.0-insider (user setup)
提交: 8b9891739b703b50547f506a7e2bc9565e52beff
日期: 2022-11-29T07:05:56.358Z
Electron: 19.1.6
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
沙盒化: Yes
```

I can confirm `GitHub Copilot` cause my issue

other 52 extensions works well in same time.

**Comment by alexdima** [comment]
Fixed by https://github.com/microsoft/vscode/pull/167653
