### ISSUE TITLE
`Profiles: Export (Default) ...` command name is confusing

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#167620]
Type: <b>Bug</b>

When I first read that, I went "'default' what?" If it's the default profile then could I suggest the command be renamed to `Export Default Profile ...`? If it turns out everyone has a default profile and the command is dynamic to list the profile name, then maybe `Export Current Profile (Default) ...`?

VS Code version: Code - Insiders 1.74.0-insider (ac084d723b7405591d2110fe374648345ecb8ce6, 2022-11-28T05:20:35.428Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.22GB free)|
|Process Argv|C:\\Users\\brcan\\OneDrive - Microsoft\\Snippets\\snippets.md --crash-reporter-id 2f8216b4-0af9-4bf4-a156-6cdcff01b0ab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (51)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
github-markdown-preview|bie|0.3.0
markdown-checkbox|bie|0.4.0
markdown-emoji|bie|0.3.0
markdown-footnotes|bie|0.1.1
markdown-mermaid|bie|1.15.2
markdown-preview-github-styles|bie|1.0.1
markdown-yaml-preamble|bie|0.1.0
wwbd|bre|2022.1.0
zephyr-asdl|bre|2021.5.0
ruff|cha|2022.0.17
vscode-github-actions|csc|0.24.4
vscode-eslint|dba|2.2.6
prettier-vscode|esb|9.9.0
vscode-yarn|gam|2.1.0
codespaces|Git|1.13.2
copilot|Git|1.61.7372
remotehub|Git|0.47.2022112901
vscode-pull-request-github|Git|0.54.1
vscode-graphql-syntax|Gra|1.0.5
vscode-todo-highlight|jgc|2.0.4
github-security-alerts|los|0.0.2
autoconf|mae|0.1.0
rainbow-csv|mec|3.3.0
ninja-syntax|mel|1.0.0
symbols|mig|0.0.7
theme-monokai-pro-vscode|mon|1.2.0
vscode-language-pack-qps-ploc|MS-|1.74.11230921
black-formatter|ms-|2022.7.13271013
isort|ms-|2022.8.0
python|ms-|2022.19.13251009
vscode-pylance|ms-|2022.11.32
jupyter|ms-|2022.11.1003341028
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.265.0
remote-wsl|ms-|0.72.0
azure-repos|ms-|0.23.2022112901
remote-repositories|ms-|0.25.2022112901
vscode-github-issue-notebooks|ms-|0.0.127
vscode-markdown-notebook|ms-|0.0.26
vscode-python-web-wasm|ms-|0.7.0
vsliveshare-pack|ms-|0.4.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
crates|ser|0.5.10
just|ske|2.0.0
fish-vscode|sky|0.2.1
even-better-toml|tam|0.19.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474

```

</details>

**Comment by sandy081** [comment]
Changed the menu to add `Profile` term to all actions so that it is clear and consistent

<img width="204" alt="image" src="https://user-images.githubusercontent.com/10746682/208242578-52d407c6-c632-4092-b427-4bce6f7e31be.png">
