### ISSUE TITLE
Don't see git push terminal quickfix

### ISSUE THREAD

**Issue by bamurtaugh** [microsoft/vscode#167613]
Testing #167475

- Open GH repo in VS Code Insiders
- Create new branch off main
- Make and commit a change in new branch
- I thought I followed the [steps shown in docs](https://code.visualstudio.com/docs/terminal/shell-integration#_quick-fixes) that'd produce a quick fix, but I'm not seeing one:

![image](https://user-images.githubusercontent.com/25310137/204630392-31f50e6d-3fa2-481c-b75c-7a89e7a76f77.png)

I assume I'm missing something obvious, but I can't seem to figure it out from experimentation and reviewing docs.

**Comment by Tyriar** [comment]
@bamurtaugh I think you have shell integration disabled as I don't see the circles to the left?

**Comment by meganrogge** [comment]
or it failed to activate for some reason - can you hover the tab @bamurtaugh ?

**Comment by bamurtaugh** [comment]
I just took the manual steps to enable shell integration in my PowerShell profile, and when I hover over the terminal tab, I see it says shell integration activated:

![image](https://user-images.githubusercontent.com/25310137/204633022-4b7474b2-7e98-45cf-a675-c510f007426f.png)

I tried the same steps but nothing seems to have changed: 

![image](https://user-images.githubusercontent.com/25310137/204633343-517b2bdf-4512-46c6-8200-f90d364f3968.png)

I realize the manual PowerShell configuration (shown below) uses `vscode` and `code` - should I update to `code-insiders`? 

```
if ($env:TERM_PROGRAM -eq "vscode") { . "$(code --locate-shell-integration-path pwsh)" }
```

I tried changing the latter `code` to `code-insiders` but didn't see a difference.

**Comment by meganrogge** [comment]
what is your powershell profile @bamurtaugh ?

**Comment by rzhao271** [comment]
I have the same issue on Ubuntu 16 with bash:
![Screenshot showing the message to create a PR, but with no lightbulb](https://user-images.githubusercontent.com/7199958/204635582-d5d5c2d1-824f-48bc-9fd8-0331b71d090b.png)

**Comment by bamurtaugh** [comment]
From running `code-insiders $Profile`, the `C:\Users\brmurtau\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1` file opens, and it is empty. I tried adding the [manual installation line](https://code.visualstudio.com/docs/terminal/shell-integration#_manual-installation) and reloading, but no change, so I've now removed it again.

I just closed all my terminals and reloaded VS Code one more time, and now when I hover over the Powershell tab, I don't see a mention of shell integration:

![image](https://user-images.githubusercontent.com/25310137/204635084-8dc2312f-bf3e-45d4-b091-1277e667fa1f.png)

I tried pasting in the manual install line, and then I got the following in a terminal, which I think makes sense since I only have Insiders installed:

![image](https://user-images.githubusercontent.com/25310137/204635361-a5413daa-980d-4d57-b962-4368297923bd.png)

I updated the install line to mention `code-insiders` (`if ($env:TERM_PROGRAM -eq "vscode") { . "$(code-insiders --locate-shell-integration-path pwsh)" }`), closed the terminal, reloaded VS Code, and now I see the integration failed to activate:

![image](https://user-images.githubusercontent.com/25310137/204635709-77ba9060-d944-4511-becd-a90f7e210d34.png)

**Comment by meganrogge** [comment]
here are the profiles I meant above... you should have one called powershell. also, do you have the pwsh extension installed?

![Screenshot 2022-11-29 at 2 02 08 PM](https://user-images.githubusercontent.com/29464607/204636107-79b09f1f-6c09-40cb-999a-e6f49c7c7176.png)

**Comment by Tyriar** [comment]
The regex should match those 🤔 

https://github.com/microsoft/vscode/blob/7b20bd008e5fa5d59d4abd30e9cfef89a301905d/src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts#L18-L20

@bamurtaugh If you're in VS Code's screen reader mode, shell integration will not work (it may say it activated which is a bug).

**Comment by meganrogge** [comment]
> I have the same issue on Ubuntu 16 with bash: ![Screenshot showing the message to create a PR, but with no lightbulb](https://user-images.githubusercontent.com/7199958/204635582-d5d5c2d1-824f-48bc-9fd8-0331b71d090b.png)

this looks different because shell integration is working for you. thanks for creating that separate issue

**Comment by meganrogge** [comment]
@bamurtaugh can you set log level to debug, open dev tools, and screenshot it like this when you run a command such as `git sttatus`?
![Screenshot 2022-11-29 at 2 04 36 PM](https://user-images.githubusercontent.com/29464607/204636615-d9257c42-dd53-40f7-a575-3bd9358d8753.png)

**Comment by bamurtaugh** [comment]
I just deleted the line from the PowerShell Profile I was editing, closed the terminal, and reloaded VS Code. I do not have the PowerShell extension installed. I do not have a mention of PowerShell in my settings.json.

I now changed log level to debug from trace. I ran `git sttatus` and here's the dev tools:

![image](https://user-images.githubusercontent.com/25310137/204637937-f7fce8b0-56e2-472a-b8e6-c98d8ee9c498.png)

**Comment by meganrogge** [comment]
Until shell integration activates, this won't work. What's the warning from powershell in your terminal say? And can you share your settings.json file?

**Comment by bamurtaugh** [comment]
> What's the warning from powershell in your terminal say?

When I add `if ($env:TERM_PROGRAM -eq "vscode") { . "$(code-insiders --locate-shell-integration-path pwsh)" }` to my Profile file? If so, it's:

```
At C:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\v
s\workbench\contrib\terminal\browser\media\shellIntegration.ps1:30 char:56
+                 [System.Text.Encoding]::UTF8.GetBytes($match.Value)
+                                                                    ~
Missing closing ')' in expression.
At C:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\v
At C:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\v 
s\workbench\contrib\terminal\browser\media\shellIntegration.ps1:34 char:3
+     })
+      ~
Unexpected token ')' in expression or statement.
At C:\Users\brmurtau\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\v 
s\workbench\contrib\terminal\browser\media\shellIntegration.ps1:35 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEndParenthesisInExpression
```

I'm attaching my settings.json here: [settingsNov.txt](https://github.com/microsoft/vscode/files/10117020/settingsNov.txt).

**Comment by meganrogge** [comment]
Manual install shouldn't be require so you can remove everything from your profile. I'd recommend doing that then running import-module psreadline

**Comment by bamurtaugh** [comment]
I removed the manual install line and reloaded. Then I ran `import-module psreadline` in an integrated PowerShell terminal.

I do now see more highlighting in the terminal!

![image](https://user-images.githubusercontent.com/25310137/204641789-417c9585-4f1a-4cd1-998f-6927f614ee3e.png)

And hovering over the tab says the shell integration is activated.

![image](https://user-images.githubusercontent.com/25310137/204641844-f1210847-679f-47bf-91d3-7e94dc1ccaf5.png)

But I'm not seeing a lightbulb.

**Comment by meganrogge** [comment]
ok great progress - now can you set log level to debug, run `git sttatus` and screenshot the result?

**Comment by meganrogge** [comment]
also just fyi from a time saving perspective - no need to reload 😄 just create a new terminal bw changes

**Comment by meganrogge** [comment]
you still don't have command decorations, which is surprising given shell integration is activated

**Comment by bamurtaugh** [comment]
@tyriar I don't see indication I'm in screenreader mode (i.e. the status bar UI mentioned [here](https://code.visualstudio.com/docs/editor/accessibility#_screen-reader-mode)).

When selecting "Use screen reader" in Windows, I don't see any options checked:
![image](https://user-images.githubusercontent.com/25310137/204645295-62d64672-bd01-4010-b653-939b723ff2bb.png)

However, when I open a new terminal, I do still see the warning:
`Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.`

Any advice for how to disable? I see a lot of different info online, so not sure if you have one top of mind.

Subsequent terminals also fail to activate shell integration, even if I run the import-module psreadline:

![image](https://user-images.githubusercontent.com/25310137/204645935-33889108-b58b-4bd9-9d9d-c643576abff0.png)

**Comment by meganrogge** [comment]
looks like `Set-ItemProperty 'registry::HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access' On 0`

**Comment by meganrogge** [comment]
you can also check the value of that via `Get-ItemPropertyValue 'registry::HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access' On`

**Comment by bamurtaugh** [comment]
`Get-ItemPropertyValue 'registry::HKEY_CURRENT_USER\Control Panel\Accessibility\Blind Access' On` outputs 1, so I'll set to 0 and restart in a bit to see if that helps.

**Comment by Tyriar** [comment]
If you see this, shell integration and quick fixes will definitely not work:

> Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

Touching the registry seems risky, I'd search for why pwsh is detecting a screen reader, this will do you good in the long run as PSReadLine makes the PS experience so much better. One possible way to work around this is to run `Import-Module PSReadLine` inside your profile (run `code $Profile`). Just running it in the terminal won't get shell integration to work, it needs to be in your profile.

**Comment by bamurtaugh** [comment]
Hmm okay, I'll do some further digging. Adding `Import-Module PSReadLine` to my Powershell Profile doesn't make a difference (and others online say the same), so I'll need to find the root cause.

**Comment by bamurtaugh** [comment]
Okay I managed to turn off screen reader access - I no longer get the warning when I open an integrated terminal or an external PowerShell terminal.

But shell integration is still failing to activate:

![image](https://user-images.githubusercontent.com/25310137/204658815-3d262be3-78cf-49c8-830a-ca26d68974a7.png)

**Comment by Tyriar** [comment]
@bamurtaugh what version of powershell are you using? Shell integration is best with pwsh 7.

**Comment by bamurtaugh** [comment]
`$PSVersionTable` outputs 5.1.25247.1000 for PSVersion. So I just installed PowerShell 7 and created a terminal profile for it in VS Code.

I now got the quick fix! Although as shown in the image, each time I open a new PowerShell 7 terminal instance, the typing is a bit odd and overlaps:

![image](https://user-images.githubusercontent.com/25310137/204665051-afd21641-41c4-4c16-b491-495d4327346c.png)

When I ran the command again, the text didn't overlap, but I didn't get a lightbulb:

![image](https://user-images.githubusercontent.com/25310137/204665187-2db4d9c7-6b82-4928-a450-49272008e309.png)

Not sure if this is expected? 

It also took some time to 1) realize I needed PowerShell 7, 2) detect PowerShell 7 in VS Code. Not sure if these items are documented.

**Comment by Tyriar** [comment]
It not working here (on Windows) is actually a known issue and there isn't much we can do about it:

![image](https://user-images.githubusercontent.com/2193314/204665762-828c52c9-7b90-4396-a839-9ad91e66b0ff.png)

See https://github.com/microsoft/vscode/issues/153476

**Comment by Tyriar** [comment]
Also the typing overlapping it also a conpty problem that I don't think it on our end.

**Comment by bamurtaugh** [comment]
I tried the `git push` commands, and there are no warnings either:

![image](https://user-images.githubusercontent.com/25310137/204665809-2a34f843-ceb7-4b28-af4e-b1db08136582.png)

I opened a new terminal, and it worked, and I get the telemetry logged correctly.

![image](https://user-images.githubusercontent.com/25310137/204666071-11967c2d-aa1a-443a-9d38-0b69df6b8587.png)

Let me know if there's anything else I can provide about the topics I mentioned above. Otherwise, I've now gotten this working, it's just not super regular and perhaps there could be greater details in docs (about versions, detecting latest version, etc).

**Comment by Tyriar** [comment]
@bamurtaugh looks like the first terminal doesn't have shell integration still, but the new one does. Since it works sometimes I'm guessing it just doesn't work now when the "placeholder decoration" isn't in the expected spot which breaks the command output detection, so a dupe of https://github.com/microsoft/vscode/issues/153476
