### ISSUE TITLE
Compound keyboard shortcuts should be delimited by commas

### ISSUE THREAD

**Issue by mousetraps** [microsoft/vscode#16770]
Testing #16560

Would help improve readability. This goes for watermark, docs, and command palette. For example:
1. `Ctrl+K Ctrl+M` -> `Ctrl+K, Ctrl+M`
2. `Ctrl+K M` -> `Ctrl+K, M`

Also note that this is scheme is consistent with almost every other editor out there. We also seem to do this for some commands, but not others. E.g. 
![image](https://cloud.githubusercontent.com/assets/762848/20948451/127db962-bbc9-11e6-9e75-185c5647f716.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by alexandrudima** [comment]
@mousetraps We use the comma in that view to render multiple different keybindings.

i.e. `Close Notification Messages` is bound to <kbd>Escape</kbd> and to <kbd>Shift</kbd>+<kbd>Escape</kbd>

while `View: Close All Editors` is bound only to <kbd>Ctrl</kbd>+<kbd>K</kbd> <kbd>Ctrl</kbd>+<kbd>W</kbd>

Should we render chords using some fancy Unicode character between the two pieces? e.g.
* `Ctrl+K ⤳ Ctrl+W`
* `Ctrl+K ⤼ Ctrl+W`
* `Ctrl+K ⟿ Ctrl+W`

Maybe you have some ideas?

**Comment by mousetraps** [comment]
@alexandrudima interesting - a couple different ideas then:
1. "or" or "and" to render multiple different keybindings
2. It seems to me that the multiple keybindings would be intended less for usability, and more to assist with muscle memory, so how about choosing only one of the mappings to display in quickopen, and being more verbose in docs?

E.g. Option 2 is what VS goes for (and iirc WebStorm as well)
![image](https://cloud.githubusercontent.com/assets/762848/20965814/5e0709ac-bc2c-11e6-871b-d959bdc949f4.png)

![image](https://cloud.githubusercontent.com/assets/762848/20965876/9047ee5e-bc2c-11e6-9ed7-21a87501588b.png)

**Comment by alexandrudima** [comment]
@bpasero We could simply show only one keybinding in the `F1` list, not sure why we're showing all of them.

**Comment by bpasero** [comment]
Fine by me, if someone wants to step in and do it. @mousetraps ?

**Comment by bpasero** [comment]
Fyi, command pallette is no longer showing multiple keybindings.

**Comment by giuscri** [comment]
As I understand this, this should be closed
