### ISSUE TITLE
Copying files for no reason

### ISSUE THREAD

**Issue by Lucas-knut** [microsoft/vscode#167705]
- VS Code Version: 1.73.1
- OS Version: Ventura 13.0.1

Hi, 
I am facing a problem on VSCode since a few days, I think it comes from the editor but it is not a certainty.
Without any reason it copies some files randomly everywhere which makes me lose time because I have to delete them each time.
I have done a lot of research but I can't find where this could be coming from, does anyone have an idea? 
Thanks in advance.

<img width="359" alt="Capture d’écran 2022-11-30 à 10 15 12" src="https://user-images.githubusercontent.com/56445538/204755787-103629d6-3f5c-4b49-9f43-15a78a726373.png">

**Comment by lramos15** [comment]
Can you try disabling all extensions? You can launch VS Code with extensions disabled to see if the experience persists via the `code --disable-extensions` CLI.

**Comment by Lucas-knut** [comment]
Hi, I found the problem thanks to this post

[Source](https://stackoverflow.com/questions/62692264/how-to-stop-vs-code-to-duplicate-files-filename-2-css)

It's because of Icloud Drive.

Thank you very much for answering me.

**Comment by lramos15** [comment]
Glad it's fixed!
