### ISSUE TITLE
ES6 Intellisense in TypeScript file?

### ISSUE THREAD

**Issue by oshalygin** [Microsoft/vscode#1677]
Can't quite figure out why I'm not getting intellisense for ES6 features in a TypeScript file.

I'm fairly certain it is related to the *lib.d.ts* file that is used in the typescript source files. For reference this is located in:

_C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\server\typescript\lib_

I noticed that the same folder contains lib.es6.d.ts. When going to definition on a method that is defined by the base interface definition files, it points you to lib.d.ts and not the es6 version. The es6 version has all of the interfaces that I need.

That said, even if I include some ES6 methods and force the task runner(which under the hood uses the typescript compiler installed), it doesn't transpile to ES5 like I expected it to.

Maybe my TypeScript compiler version is dated? Primarily I want these features:

Symbol
Array.prototype.includes
String.prototype.includes
I see these interfaces defined in the es6 typing definition file. Is there a way to get VSCode to recognize this? I'm thinking a hacky approach of just including that lib file in my project but I'm trying to avoid that and in the end it still doesn't solve my problem when I transpile to ES5 and get garbage.

**Comment by bpasero** [comment]
@oshalygin did you configure tsconfig.json to be ES 6?

**Comment by roslanr18** [comment]
.

**Comment by oshalygin** [comment]
@bpasero I'm a tad more lost after doing quite a bit more research on this topic actually and I'm not 100% sure that it can be solved, at least not yet.  The initial issue with *.prototype.includes is very minor and can be remedied by adding a polyfill.

On to the larger issue at hand,
When targeting ES6 in the tsconfig.json file, the transpilation is perfect and transpiles to ES6 just fine.  The problem is when trying to transpile down to ES5 or ES3, which is quite necessary when working with modern browsers and current development tools such as Jasmine or Karma.  

I understand that these are ES6 features and the typescript compiler transpiles down to the respective JavaScript version that the syntax is attached to.  When it comes to generator functions, .includes(...) and other ES6 features, since this isn't TypeScript syntax, the compiler targets the appropriate JS version and pushes it down accordingly.

I thought I could chain up transpilation and solve my problem but alas even Babel doesn't seem to support generators.  I transpiled to ES6 from TypeScript, then transpiled to ES5 using es2015 presets with babel.  No dice, it doesn't seem to know what to do with symbol.iterator...

If anyone has any input or advice I'm all for it :).

**Comment by oshalygin** [comment]
@bpasero if you target ES6 in the tsconfig.json that is at the root of the opened folder, VS Code will use lib.es6.d.ts, so yes it solves what I was going at.  

Anyone else having this issue, make sure you setup a tsconfig.json and set the target appropriately for the compilerOptions

**Comment by bpasero** [comment]
:+1:
