### ISSUE TITLE
"Detecting kernels" spinner icon spins the whole button when in the editor toolbar

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167769]
Testing microsoft/vscode-jupyter#11963
![Recording 2022-11-30 at 12 44 05](https://user-images.githubusercontent.com/323878/204886115-53219f4a-9c37-45a8-84e0-7a364222a6ef.gif)

**Comment by rebornix** [comment]
Thanks, it's an issue with the spinner background. It should only spin the icon but not the bg.

**Comment by jrieken** [comment]
For the wiggle I make sure this only targets the codicon, not the entire button via: [`SPAN.codicon.wiggle`](https://github.com/microsoft/vscode/blob/86127c6cce7f27b71b8b112d0c59cc6ab6d5f4ad/src/vs/workbench/contrib/languageStatus/browser/media/languageStatus.css#L28)

@roblourens @rebornix Are you just using a codicon with the spin modifier or is this something custom?

**Comment by roblourens** [comment]
This seems to not repro anymore
