### ISSUE TITLE
Help with TextDocumentContentProvider

### ISSUE THREAD

**Issue by riteshatsencha** [Microsoft/vscode#16773]
- VSCode Version: 1.7.x
- OS Version: OS X 10.10.5

Trying to figure out how to make TextDocumentContentProvider work! 

Here is the code from ``` extension.ts ```

```
    let provider = new SnippetProvider();
    let registration = vscode.workspace.registerTextDocumentContentProvider('foo', provider);

    let disposable = vscode.commands.registerCommand('extension.showFoo', () =>{
        return vscode.workspace.openTextDocument(vscode.Uri.parse('foo://auth/path')).then((doc) => {
            console.log('doc ', doc);
        });
    });

   context.subscriptions.push(disposable, registration);
```

And here is a simple class that provides snippets.

```
export default class SnippetProvider implements vscode.TextDocumentContentProvider {
    private templateUtil = new TemplateUtil();
    public provideTextDocumentContent (uri : vscode.Uri) : Thenable <string> {
        let data = this.templateUtil.loadTemplates();
        return data;
    }
}

```

I keep seeing ``` cannot open foo://auth/path. Detail: Document with resource foo://auth/path does not exist ```. Of course, I know that path does not exist. It's virtual. Where am I wrong?

Any thoughts?

Thank you,

Ritesh

**Comment by alexandrudima** [comment]
There is a complete working sample at https://github.com/Microsoft/vscode-extension-samples/tree/master/contentprovider-sample

**Comment by jrieken** [comment]
The snippet looks ok. One question: are you sure this `this.templateUtil.loadTemplates()` returns a string? That's the only thing I see there

**Comment by riteshatsencha** [comment]
@jriken good catch. I swear that return value from ``` this.templateUtil.loadTemplates() ``` was screaming at me saying `please take care of me I am an object and not a string!` I guess not loud enough for me to hear it! ;) ;) 

`stringify with pretty print took care of it`

Thank you!

**Comment by jrieken** [comment]
awesome. thanks for getting back to me.

**Comment by riteshatsencha** [comment]
@jrieken here is a tutorial that should help anyone trying to implement this functionality. 

[Content Provider Tutorial](http://riteshpatel.silvrback.com/content-provider-tutorial-for-vscode)
