### ISSUE TITLE
"editor.selectionHighlight…" colors are applied while non selected text in JSON.

### ISSUE THREAD

**Issue by Fred-Vatin** [microsoft/vscode#167766]
Does this issue occur when all extensions are disabled?: Yes

VS Code version | OS
------------------ | ----
1.73.1  | Win 10 x64 pro 21H2

## Steps to reproduce

1. Enable this setting `editor.occurrencesHighlight`
2. Apply a color. For instance add this to your **_settings.json_**
```jsonc
{
  "workbench.colorCustomizations": {
    // controlled by setting editor.selectionHighlight
    "editor.selectionHighlightBackground": "#929d4d7b", // ugly color
    "editor.selectionHighlightBorder": "#ff66eb", // Highlight flashy
    // controlled by setting editor.occurrencesHighlight
    "editor.wordHighlightBackground": "#ffffff00", // transparent
    "editor.wordHighlightBorder": "#ffffff00", // transparent
    "editor.wordHighlightStrongBackground": "#ffffff00", // transparent
    "editor.wordHighlightStrongBorder": "#ffffff00", // transparent
  }
}
```
3. Save
4. In your **_settings.json_**, move the caret, don’t select text.

## Results

```jsonc
    "editor.selectionHighlightBackground": "#929d4d7b", // ugly color
    "editor.selectionHighlightBorder": "#ff66eb", // Highlight flashy
```
Those colors 👆 are applied while any other colors supposed to control this behavior are set to transparent.

![image](https://user-images.githubusercontent.com/22337329/204902167-7fd57d51-70ae-45bf-833a-d0ebdd9e3362.png)

## Expectations
`"editor.selectionHighlight…"` colors should not be applied if no selection. **This issue only occurs in JSON files as far as I know.**

**Note**: toggle the setting `editor.selectionHighlight` has no effect on this bug. However this setting is supposed to be the only one to have effect on those colors.

It works as expected in other files.

---

There are other related issues but they are not duplicate.

**Comment by aeschli** [comment]
https://github.com/Microsoft/vscode/issues/51869#issuecomment-397983292 explains the 3 cases. We are in cae 3:
JSON does not register a `DocumentHighlightProvider`, we fall back to the selection highlighter even when there is no selection. 
That highlight uses the `selectionHighlightBackground` colors.

@alexdima To decide if this is expected. IMO it would make sense to use wordHighlight colors here.

**Comment by Fred-Vatin** [comment]
Agree
