### ISSUE TITLE
Screen cheese when splitting a notebook

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#167712]
* empty/fresh profile
* open an ipynb-file
* press split button
* 🧀 massive screen cheese

https://user-images.githubusercontent.com/1794099/204771963-49fbed84-d4c1-4352-8d0b-85f68fe47d0d.mp4

**Comment by jrieken** [comment]
This also seems to happen when opening a notebook in any side-by-side setup, e.g have two text editor open side-by-side, open a notebook, and 🧀 

<img width="1417" alt="Screenshot 2022-11-30 at 12 23 48" src="https://user-images.githubusercontent.com/1794099/204783830-2404afc5-1a27-483f-8699-9d71a5221673.png">

**Comment by Tyriar** [comment]
/duplicate https://github.com/microsoft/vscode/issues/167087, it's currently on November
