### ISSUE TITLE
Explore using https for profile links

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#167700]
Right now the profile URL looks like `vscode-insiders://profile-github/https%3A//gist.github.com/725177503274136f427527008dbf1463`
Some tools like Teams, Outlook do not detect this as a link - thus it is not clickable.

The only way out of that problem is to use `https` as the protocol. @joaomoreno suggests something like `https://vscode.dev/profile/gist/725...` that could be a page which would redirect to the native protocol.

**Comment by sandy081** [comment]
We have vscode.dev profile links now those can be shared and previewed in web and can be opened in desktop too.
