### ISSUE TITLE
`workbench.list.defaultFindMode` randomly stopped working

### ISSUE THREAD

**Issue by jsindos** [microsoft/vscode#167789]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.73.1
- OS Version: macOS Monterey 12.0.1

Steps to Reproduce:

I have really been enjoying the [workbench tree widget](https://code.visualstudio.com/updates/v1_31#_new-tree-widget), but for some reason it randomly stopped working. It seems like it is running in `simple` mode now by default, and I can't override the setting.

https://user-images.githubusercontent.com/8110172/204938870-190bdfa8-c6e0-461a-baa0-6cd720975a12.mov

**Comment by joaomoreno** [comment]
The default behavior changed in https://github.com/microsoft/vscode/pull/152481. Use <kbd>Ctrl/Cmd F</kbd> to open the new find widget.

**Comment by jsindos** [comment]
Great thanks @joaomoreno. Is there any way to revert it to the old setting?

**Comment by joaomoreno** [comment]
Unfortunately the feature request got closed given low community support: https://github.com/microsoft/vscode/issues/157986#issuecomment-1280227533
