### ISSUE TITLE
Quiet authentication requests not removed from Accounts menu after Sign In with Microsoft Auth Provider

### ISSUE THREAD

**Issue by AndreyTretyak** [microsoft/vscode#167791]
Type: <b>Bug</b>

Running following code in the extension:
```TypeScript
const scopes = ['https://graph.microsoft.com/.default'];
const session = await vscode.authentication.getSession("microsoft", scopes, { createIfNone: false });
```
Adds item into accounts menu: 
![image](https://user-images.githubusercontent.com/2550113/204944423-8c749fe7-e74b-4cc7-8c08-b41a1891f3ef.png)
Clicking on it redirects to the sign in page but successful sign in won't remove item from Accounts menu.

This is only an issue for Microsoft Auth provider, GitHub Auth provider works normally.

Also, clicking on this Account item will redirect you to sign in web page automatically, while requesting session with `createIfNone: true` provides much better experience of selecting from already signed in accounts and adding new account optionally, like this:
![image](https://user-images.githubusercontent.com/2550113/204944929-cbb55ed5-145f-4252-bae2-3409c6ce3df1.png)
It would've been great to have the same experience when clicking on auth request item in the menu.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz (20 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.71GB (13.43GB free)|
|Process Argv|--disable-extensions --crash-reporter-id bbc80aae-e75c-41dd-8004-76ef92d67a33|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by TylerLeonhardt** [comment]
Yeah you're right. This shouldn't jump straight to the browser. It should show the "choose account" quick pick.

**Comment by TylerLeonhardt** [comment]
Actually there's a lot in this issue... we need to break it up.

> Clicking on it redirects to the sign in page but successful sign in won't remove item from Accounts menu.

This is a bug. And the bug we should track in this issue.

> Also, clicking on this Account item will redirect you to sign in web page automatically, while requesting session with createIfNone: true provides much better experience of selecting from already signed in accounts and adding new account optionally, like this

It only jumps to the browser if you don't have any accounts logged in. If you have an _existing_ account associated with another extension, then you get this:

![Image](https://user-images.githubusercontent.com/2644648/206556066-77d8cf5a-2a0a-453b-933e-f69850feeee1.png)

"Grant access to..." which does in fact show you the quick pick first:

![Image](https://user-images.githubusercontent.com/2644648/206556184-b0f3a3ea-35fa-4f5b-853b-913dc83b0da1.png)
