### ISSUE TITLE
Navigating up the collapsed groups skips alternate groups

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16777]
Testing #16530 

Click on any of the group heading. Use SPACE to collapse and down arrow key to go to the next group. Repeat (Collapse and move to next) until you reach the end. Now use up arrow key to move up. Notice that alternate groups get skipped while going up.

**Comment by sandy081** [comment]
@ramya-rao-a Can you please provide more steps to reproduce this as I am not able to.

**Comment by ramya-rao-a** [comment]
Weird, it doesnt happen anymore.
Closing
