### ISSUE TITLE
Settings not aligned with heading and search box

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16772]
Testing #16530

![image](https://cloud.githubusercontent.com/assets/16890566/20948532/79feac54-bbc9-11e6-845b-259c2cc9ac9f.png)

**Comment by sandy081** [comment]
@bgashler1 Any opinions here?

**Comment by sandy081** [comment]
Adjusted it

<img width="704" alt="screen shot 2016-12-07 at 10 58 54" src="https://cloud.githubusercontent.com/assets/10746682/20963182/b0798daa-bc6c-11e6-9444-833f3bc61889.png">

**Comment by bgashler1** [comment]
Thanks for fixing this @sandy081.  I for some reason missed this in my inbox :)
