### ISSUE TITLE
Bring back unsafe terminal profile paths with a confirmation step

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#167721]
The idea is to bring back cygwin and add other shells like cmder/msys2 and any other profiles that may be in "unsafe" paths (ie. not those owned by the user or admin) and present them in the list:

![image](https://user-images.githubusercontent.com/2193314/204812280-8cb8486a-4080-47c4-9932-a0a0bf2b0ff1.png)

Note that they're in the `detected` section, not the `profiles` section, so it won't show up unless it's created via the select default profile button. It's not clear to me whether we need a warning icon or warning text here or not, but clicking it would get a notification warning before proceeding which is the main protection.

Code for the screenshot:

```ts
		detectedProfiles.set('Cygwin $(warning)', {
			path: [
				'C:\\cygwin64\\bin\\bash.exe',
				'C:\\cygwin\\bin\\bash.exe'
			],
			args: ['--login'],
			isAutoDetected: true
		});
```

**Comment by meganrogge** [comment]
IMO, we don't need a visual indicator in that list as the notification is sufficient

**Comment by Tyriar** [comment]
@meganrogge if they click either that entry or the gear icon, a notification would appear and if accepted it would be added to settings to become a proper profile. So no need to cache the answer or anything as this only needs to happen once typically.

**Comment by Tyriar** [comment]
We could also add the msys2 shells, I saw this in feedback we got from from the website:

Not sure if we need the env:

```json
"MSYS2 Bash": {
  "path": "C:\\msys64\\usr\\bin\\bash.exe",
  "args": ["--login", "-i"],
  "env": {
      "MSYSTEM": "MINGW64",
      "CHERE_INVOKING": "1",
      "MSYS2_PATH_TYPE": "inherit"
  }
}
```

From https://gist.github.com/dhkatz/106891324c9624074a84d11e2691144b

**Comment by DRSDavidSoft** [comment]
Awesome, BTW this is not strictly related, but there is an issue with shell profiles that contain a space in the environment variable.  I'd super appreciate it if you could take a look and confirm the issue: #164696
