### ISSUE TITLE
Folded notebook sections are not restored

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#167792]
Type: <b>Bug</b>

When reconnecting to a Codespaces the previously folded notebook are not restored. Works fine on refresh or closing/opening the same file.

STR:
1. Create a notebook in a Codespace (I used Insiders on macOS)
2. Disconnect from the Codespace (Open Remote Explorer panel and hit the Disconnect icon)
3. Open the same Codespace again

Bug: Folded sections are open again

VS Code version: Code - Insiders 1.74.0-insider (56d73a45e38259976188a982331c9fb5d156cd25, 2022-11-30T21:51:22.982Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.4.0-1094-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|12, 6, 4|
|Memory (System)|64.00GB (1.94GB free)|
|Process Argv|--enable-proposed-api donjayamanne.kusto --log trace --crash-reporter-id 4cf0a6f0-aaf8-4da3-9b2b-81f6c639c12b|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Codespaces|
|OS|Linux x64 5.4.0-1094-azure|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (2 x 2793)|
|Memory (System)|3.84GB (1.69GB free)|
|VM|0%|
</details>

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/168807
