### ISSUE TITLE
Terminal quick fix - resizing the terminal breaks lightbulb placement

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#167737]
Testing #166761

* Run a command that would result in a lightbulb to be shown
* Resize the Terminal
  <img width="601" alt="image" src="https://user-images.githubusercontent.com/3372902/204843079-c1d5e2c4-0e5b-44df-9ed3-6263e07f113b.png">

**Comment by Tyriar** [comment]
There's nothing we can do here on Windows unfortunately due to how conpty works, it's related to https://github.com/microsoft/vscode/issues/153476 and will possibly improve when that gets fixed upstream.
