### ISSUE TITLE
Cursor disappears when I clear screen

### ISSUE THREAD

**Issue by Toni744** [microsoft/vscode#167707]
When I clear screen on VScode terminal the whole screen goes blank and unresponsive.
<img width="866" alt="problem" src="https://user-images.githubusercontent.com/49808547/204765252-d484b418-9e27-4cd5-9768-cc6b7e0ff105.PNG">

**Comment by meganrogge** [comment]
how are you clearing ? by typing `clear`?

**Comment by Toni744** [comment]
Yeah

**Comment by meganrogge** [comment]
any errors in the dev tools console?
