### ISSUE TITLE
Empty MRU- back button does nothing

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#167768]
Testing microsoft/vscode-jupyter#11963

- Open a new window where no kernels have been used
- Open the kernel picker, get the kernel source picker
- Click the back button
- The quick pick flashes closed/opened and shows the source picker again

**Comment by minsa110** [comment]
Was trying the MRU out with my new machine and ran into the same thing. Just adding a few more comments:
- The progress bar makes it look like the process to find kernels just hangs
- I'd expect to see `Install suggested extensions` like the old experience
- `Select **Another** Kernel` feels unfinished--it's my first time picking a kernel for this project so I expect it to tell me to just `Select a Kernel` 
![kernel selection hangs](https://user-images.githubusercontent.com/10833267/205129850-afda5309-9458-4a72-aa39-cf3af03a8dd6.gif)
