### ISSUE TITLE
One-click button for updating all disabled extensions

### ISSUE THREAD

**Issue by ryenus** [microsoft/vscode#167796]
### What's happening
In the **Disabled Extensions** view, especially when there're multiple disabled extensions to update, one needs to go through each and click the "Update" button one-by-one to update all of them.

<img width="405" alt="image" src="https://user-images.githubusercontent.com/610161/204972020-d0d42a50-ab3d-4fed-9f0f-6d94c5c821e4.png">

### Expected
It's better to have a button, named something like "Update All", once clicked, would update all those disabled extensions having updates available. So that one doesn't have to update one-by-one.

**Comment by sandy081** [comment]
There is an **Update All** action in the overflow menu 

![image](https://user-images.githubusercontent.com/10746682/204982542-070d8dfb-2c46-4dcd-8339-e78f3bbf8630.png)

**Comment by ryenus** [comment]
Hmmm, exactly, how could I miss that, thank you!
