### ISSUE TITLE
Reevaluate how to run the tunnel as a service on Windows

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#167741]
The current `code tunnel service install` works sometimes on Windows, but it's not good. It seems like certain system policies can break it; the user changing their password will break the service; and we have to ask for username and password in the first place.

I want to see if there are any alternatives to this, or find a contact who works on Windows services to provide guidance.

**Comment by connor4312** [comment]
SteVen mentioned there are alternative registry keys we can use to spawn the process instead of running it as a full 'service' https://learn.microsoft.com/en-us/windows/win32/setupapi/run-and-runonce-registry-keys

**Comment by alexr00** [comment]
@connor4312 what's the best way to verify this?

**Comment by connor4312** [comment]
1. On Windows, use `code tunnel service install` (via code-insiders or downloading the latest standalone CLI build)
2. Verify that it works and the tunnel starts running without asking for username/password
3. `code tunnel service uninstall`
4. Verify the tunnel is stopped

**Comment by alexr00** [comment]
After doing the `uninstall` I get this message:

```
[2023-02-23 18:38:03] warn The tunnel service has been unregistered, but we couldn't find a running tunnel process. You may need to restart or log out and back in to fully stop the tunnel.
```
And I can still see a process `code-tunnel-insiders.exe` in the task manager.

**Comment by connor4312** [comment]
I've created a new issue for that
