### ISSUE TITLE
insertCursorAtEndOfEachLineSelected does not work with multiple selections

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16771]
- VSCode Version: Code - Insiders 1.8.0-insider (c425cd159bd389844e9400be801675f54f2443c7, 2016-12-06T16:53:46.634Z)
- OS Version: Darwin x64 15.6.0

It seems to only work on the primary selection.

**Comment by alexandrudima** [comment]
Implemented via #17698
