### ISSUE TITLE
View Scale: Missing check mark

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#16784]
Testing: #16326 

- VSCode Version: 1.8-insiders
- OS Version: Win

Steps to Reproduce:

1. Open dependancies view in debug mode.  
2. Activate via `view` menu
3. It's now in the activity bar.  But there is no check-mark right click `context` menu.  There probably shoudl be...

![image](https://cloud.githubusercontent.com/assets/1051190/20949673/899aa5a4-bbcf-11e6-8fd5-ee36f031cc8c.png)

4. Additionally is it possible to add that tot he view meny like we do for AutoSave
![image](https://cloud.githubusercontent.com/assets/1051190/20949709/b7addce0-bbcf-11e6-9bb3-e0814eaa59d3.png)

![image](https://cloud.githubusercontent.com/assets/1051190/20949714/c1257418-bbcf-11e6-81fc-52b557d7e04d.png)

Sean

**Comment by bpasero** [comment]
As designed, the checkbox only shows up for "pinned" viewlets (those that are kept in the activit bar.)
