### ISSUE TITLE
View: Additional Viewlets should be scoped to the windows workspace

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#16782]
Testing: #16326 

- VSCode Version: 1.8-insiders
- OS Version: Win

Steps to Reproduce:

1. Open Code and see no item in the view menu:
![image](https://cloud.githubusercontent.com/assets/1051190/20949404/edba9532-bbcd-11e6-985b-464248f807ad.png)

2. Load up the dependancies extension and `F5`
3. See the `view->Additional Viewlets` item in _both_ the extension host instance and standard...
![image](https://cloud.githubusercontent.com/assets/1051190/20949426/168ab834-bbce-11e6-87ee-29a55c534f2c.png)

4. Close the extension host and it's still there in the root host.
![image](https://cloud.githubusercontent.com/assets/1051190/20949449/3357a7ce-bbce-11e6-8e87-08e5de7cf389.png)

5. If you click on it you get the following error:
![image](https://cloud.githubusercontent.com/assets/1051190/20949459/432da018-bbce-11e6-8950-ee1280655a2f.png)

Seams like ideally it would not appear in any other instance other than the extension host unless loaded.

Sean

**Comment by bpasero** [comment]
Moving into https://github.com/Microsoft/vscode/issues/991
