### ISSUE TITLE
Error: An internal error has occurred

### ISSUE THREAD

**Issue by VokesoJCL** [microsoft/vscode#167892]
Type: <b>Bug</b>

Every time I try to publish code with Visual studio, I get the message 'Error: An internal error has occurred'. Problem is that I don't know what that problem is, or how to find out. There is nothing in the logs, nothing in event viewer, and nothing else I can find to figure out what the internal error is. I work for several customers all with different exension code (Business Central, several versions from BC14 - BC20) - and every one of them started giving me this error as of today, exactly the same message every time. It is not specific to any server, extension code, or version of the program.
Any troubleshooting tips?

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|60.85GB (41.64GB free)|
|Process Argv|C:\\Users\\johnl\\Documents\\GitHub\\Declaration|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
bdev-al-xml-doc|365|1.1.7
al-code-outline|and|3.0.40
al-toolbox|Bar|2.0.25
bracket-select|chu|2.0.2
al-codeactions|dav|1.0.24
githistory|don|0.6.19
gitlens|eam|13.1.1
vscode-install-vsix|fab|1.4.0
vscode-firefox-debug|fir|2.9.8
todo-tree|Gru|0.0.220
rest-client|hum|0.25.1
al-test-runner|jam|0.7.13
al-object-designer|mar|0.2.4
vscode-docker|ms-|1.23.1
al|ms-|10.1.707468
cpptools|ms-|1.12.4
notepadplusplus-keybindings|ms-|1.0.7
powershell|ms-|2022.11.0
nab-al-tools|nab|1.28.0
snippet-creator|nik|0.0.5
createGUID|nwa|0.0.2
al-var-helper|ras|2.4.0
xliff-sync|rva|1.3.0
partial-diff|ryu|1.4.3
businesscentral-lintercop|ste|0.1.4
vjeko-al-objid|vje|2.9.1
vscode-icons|vsc|12.0.1
al-extension-pack|wal|1.0.20
crs-al-language-extension|wal|1.5.19
vscode-todo-highlight|way|1.0.5
al-navigator|wbr|0.5.0
json|Zai|2.0.2

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by VokesoJCL** [comment]
I did not try that, but will in the morning. I am on the latest build, I just didn't try disabling all extensions.



Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone


-------- Original message --------
From: Matt Bierner ***@***.***>
Date: 12/1/22 7:35 PM (GMT-05:00)
To: microsoft/vscode ***@***.***>
Cc: John Lamb ***@***.***>, Author ***@***.***>
Subject: Re: [microsoft/vscode] Error: An internal error has occurred (Issue #167892)


Does this reproduce in the latest VS Code insiders build<https://code.visualstudio.com/insiders/> with all extensions disabled<https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled>?

**Comment by VokesoJCL** [comment]
Same problem. I went as far as to uninstall all extensions, uninstalled VS completely from my computer, then reinstalled VS from scratch, and only added back the AL exension (had to for the code to compile).
When I Run or Run and Debug, same error every time.
![image](https://user-images.githubusercontent.com/73313625/205349906-1220be90-2efd-4d1d-9593-6746143e4e9c.png)

**Comment by mjbvz** [comment]
Thanks for testing. This sounds like it is caused by the AL extension. Please file this issue against them
