### ISSUE TITLE
Как создать файл, который закодил

### ISSUE THREAD

**Issue by MikobroZzz** [microsoft/vscode#167858]
Type: <b>Bug</b>

Здравствуйте! Я закодил файл, но как его получить?

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4440 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.94GB (1.82GB free)|
|Process Argv|--crash-reporter-id dcd288c3-f4e0-409e-8ebc-549af32d3f23|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-ru|MS-|1.73.11020950

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by are-scenic** [comment]
> Спасибо за создание этого выпуска!
> 
> Однако, поскольку описание не на английском языке, нам трудно работать над ним. Если вы можете, пожалуйста, отредактируйте этот выпуск, чтобы он был на английском языке. Пожалуйста, не добавляйте новый комментарий или не создавайте новый выпуск, а отредактируйте существующую проблему.
> 
> К сожалению, службы автоматического перевода не могут справиться с техническим языком, необходимым для эффективного общения о проблемах программного обеспечения, поэтому мы рекомендуем найти переводчика-человека, который знаком с нашей технологией, чтобы помочь перевести.
> 
> В противном случае эта проблема была помечена как нуждающаяся в переводе, и член сообщества может помочь перевести ее.
> 
> Thanks for creating this issue!
> 
> Unfortunately, as the description is not in English, it's hard for us to work on. If possible, please edit the original issue to be in English.
> 
> In our experience, automatic translation services are not able to handle the technical language needed to effectively communicate about software issues, so we recommend finding a human translator who is familiar with our technology to help.
> 
> Otherwise, we have marked this as needing translation and a community member may be able to help out.

The original message of the issue is almost useless. It uses programming slang the way that it might have several interpretations. 

This user tells the following: I "закодил" the file, but how can I retrieve it now?". The word "закодил" is a verb that is a slang. It might have several interpretations depending on the context. For instance, it might have the following meanings:
- I have coded a file (wrote a programming file), but how do I retrieve it now?
- I have encrypted a file, but how do I retrieve it now?
- I have encoded a file, but how do I retrieve it now?

As you can see there is not enough context to understand the meaning of this slang statement.

**Comment by lramos15** [comment]
Thanks for the translation, @are-scenic sounds like a question and not a bug, so closing for now.
