### ISSUE TITLE
Trailing comma in settings stops editing of settings via the copy action icon

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16780]
Testing #16530 

 Add a trialing comma to the last setting in user settings `"editor.fontSize": 14,`. Now try to change setting using the icon. You get error message 
![image](https://cloud.githubusercontent.com/assets/16890566/20948991/dd87946e-bbcb-11e6-9e85-88d9743181e0.png)

**Comment by sandy081** [comment]
This is known and thanks for filing.
