### ISSUE TITLE
Visual Studio Code does not show code suggestions

### ISSUE THREAD

**Issue by serhatcandev** [microsoft/vscode#167896]
Hello guys. When using VS code sometimes it doesn't suggest me the codes. I installed WebStorm to try it and it works fine.

How can I force VS Code into this situation?

VS Code:
![image](https://user-images.githubusercontent.com/85739464/205185693-0df44804-ae69-433a-b1f1-d52ac7f21fe6.png)

WebStorm:
![image](https://user-images.githubusercontent.com/85739464/205185725-f6e5e63c-160e-4baf-84e9-45ab1ed398b0.png)

**Comment by mjbvz** [comment]
You need to add type annotations to tell VS Code what the type of `name` is: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#supported-jsdoc

Webstorm seems to show every possible method that could exist on `name`. We are more conservative and only suggest methods we a confident actually exist on `name`

**Comment by serhatcandev** [comment]
> Webstorm seems to show every possible method that could exist on `name`. We are more conservative and only suggest methods we a confident actually exist on `name`

Is there a plugin for this? Or some code I need to write in settings.json? Because my code is not faulty.
