### ISSUE TITLE
Visual Studio crash while trying to login into GitHub

### ISSUE THREAD

**Issue by qaziullah** [microsoft/vscode#167802]
Type: <b>Bug</b>

git clone [link to repository]

visual studio tries to open url for github login and authentication 
When clicked on open, vscode shutsdown after a couple of seconds.

OS used is Centos-7

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 3.10.0-1160.80.1.el7.x86_64
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|46.87GB (41.32GB free)|
|Process Argv|--unity-launch --crash-reporter-id da0f0393-b90d-4f1e-8cd2-5e83a00621d9|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome-classic|
|XDG_CURRENT_DESKTOP|GNOME-Classic:GNOME|
|XDG_SESSION_DESKTOP|gnome-classic|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
texinfo|cis|0.2.4
gitlens|eam|13.1.1
veriloghdl|msh|1.5.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyonecf:30548226
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by lszomoru** [comment]
@TylerLeonhardt, could you please take a look? Thanks!

**Comment by deepak1556** [comment]
Can you attach the crash logs following the steps at https://github.com/microsoft/vscode/wiki/Native-Crash-Issues#creating-and-symbolicating-local-crash-reports, thanks!

**Comment by qaziullah** [comment]
[55b9a358-23b1-442c-9916-d3f1c4a7a253.dmp.zip](https://github.com/microsoft/vscode/files/10183818/55b9a358-23b1-442c-9916-d3f1c4a7a253.dmp.zip)

I have followed the steps given at the link and have attached *.dump file, present in the /crash_report/pending directory, here for your reference.

**Comment by qaziullah** [comment]
@deepak1556 Have you looked into the crash logs.

**Comment by deepak1556** [comment]
Thanks for the logs, issue has same root cause as https://github.com/microsoft/vscode/issues/164223#issuecomment-1303309116. Please follow that issue for updates.

Merging to https://github.com/microsoft/vscode/issues/164223
