### ISSUE TITLE
Cannot recognise html code in JS

### ISSUE THREAD

**Issue by IfSheKnows** [microsoft/vscode#167888]
Type: <b>Bug</b>

I am trying to run a html code in java script by doing some thing like this: else {
        label.innerHTML = (backtick)`
        <h3>Oh no! Cart is Empty :(</h3>
        <a href="index.html">
            <button class="HomeBtn">Return to Homepage</button>
        </a>
         `(backtick);
        }
It is supposed to work and output button and the header text but it does not work. It does not even print as text on the page and I do not know what is wrong. I have been on this for over 3 hours and my VS software is up to date. Please Help as it is urgent.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
lit-html|bie|1.11.1
doxdocgen|csc|1.4.0
better-cpp-syntax|jef|1.16.3
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.2
LiveServer|rit|5.7.9
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by mjbvz** [comment]
This sounds like question about using JS, not a VS code issue. Please try asking on stackoverflow
