### ISSUE TITLE
More info section is illegible after switching to RTL language and back

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#167871]
1. Set your device to an RTL language such as arabic
2. Set your device back to LTR language such as english
3. 🐛  The more info section become illegible.
A reboot seems to fix this.

<img width="295" alt="image" src="https://user-images.githubusercontent.com/4544166/205143334-ffda320a-1479-40e2-af83-54d3a3f09cf2.png">

**Comment by lramos15** [comment]
Actually, fully expanded these don't even make much sense. Where is the day of the month, what is this timestamp?

<img width="295" alt="image" src="https://user-images.githubusercontent.com/4544166/205143334-ffda320a-1479-40e2-af83-54d3a3f09cf2.png">


<img width="419" alt="image" src="https://user-images.githubusercontent.com/4544166/205143379-0cd81f88-cab3-4947-a40a-bf46177e79c8.png">

**Comment by sandy081** [comment]
Seems like an electron/chromium issue, because I am using the underneath JS Date library to get the string format

https://github.com/microsoft/vscode/blob/930fd0e469a43fd923cd732c178e3cc9e878b58d/src/vs/workbench/contrib/extensions/browser/extensionEditor.ts#L946

**Comment by rzhao271** [comment]
Which OS is this on, and did you restart the device in between?
I actually saw a similar issue recently with the Windows 11 start menu.

**Comment by lramos15** [comment]
> Which OS is this on, and did you restart the device in between? I actually saw a similar issue recently with the Windows 11 start menu.

Mac, didn't restart the device. Restarting the device appears to fix the issue

**Comment by rzhao271** [comment]
Merging to https://github.com/microsoft/vscode/issues/169114

**Comment by deepak1556** [comment]
@rzhao271 is this merged into https://github.com/microsoft/vscode/issues/169114 because the `more info` section also does not require the system locale and reverting it to using application locale is the preferred fix ?

**Comment by rzhao271** [comment]
@TylerLeonhardt and I were discussing whether that section should even be using the system locale, and I am using #169114 as a catch-all issue for that.
