### ISSUE TITLE
LaTeX does not render on Jupyter Notebook with Sagemath kernel

### ISSUE THREAD

**Issue by SashaIr** [microsoft/vscode#167873]
## Environment data

- VS Code Version: 1.73.1
- OS Version: Windows 11 Education

## Expected behaviour
Render math after running a cell.

## Actual behaviour
Math is only rendered the very first time a cell is executed; then it's not rendered and an error `ParseError: KaTeX parse error: \newcommand{\Bold} attempting to redefine \Bold; use \renewcommand` is shown.

## Steps to Reproduce

1. [Install a SageMath kernel](https://ask.sagemath.org/question/43240/sagemath-and-vscode/).
2. Open a new Jupyter Notebook.
3. Run %display latex.
4. Run x^2.
5. Re-run x^2 or run another x^2 cell.

![image](https://user-images.githubusercontent.com/17984906/205145739-d94a1dad-2d31-4078-bb95-c87fd6c7026b.png)

**Comment by mjbvz** [comment]
Can you share the notebook file for this case? (or at least the raw text output of the two math cells)

**Comment by SashaIr** [comment]
Sure, here you go.

`{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "%display latex"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<html><script type=\"math/tex; mode=display\">\\newcommand{\\Bold}[1]{\\mathbf{#1}}x^{2}</script></html>"
      ],
      "text/latex": [
       "$$\\newcommand{\\Bold}[1]{\\mathbf{#1}}x^{2}$$"
      ],
      "text/plain": [
       "x^2"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x^2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<html><script type=\"math/tex; mode=display\">\\newcommand{\\Bold}[1]{\\mathbf{#1}}x^{2}</script></html>"
      ],
      "text/latex": [
       "$$\\newcommand{\\Bold}[1]{\\mathbf{#1}}x^{2}$$"
      ],
      "text/plain": [
       "x^2"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "x^2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "SageMath 9.3",
   "language": "",
   "name": "sagemath"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "26de051ba29f2982a8de78e945f0abaf191376122a1563185a90213a26c5da77"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
`

**Comment by SashaIr** [comment]
I found a workaround, adding 

```
from sage.misc.latex_macros import sage_configurable_latex_macros
sage_configurable_latex_macros.remove("\\newcommand{\\Bold}[1]{\\mathbf{#1}}")
```

to my sage.init file.

**Comment by mjbvz** [comment]
Thanks

I believe other notebooks rely on custom Katex commands working across cells so I don't think we can change this behavior on the VS Code side. I'm going to close this unless there is a proposal on how this can be addressed without breaking existing behavior
