### ISSUE TITLE
Visual glitch when showing native dialog on Ubuntu

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16781]
Testing Electron update - https://github.com/Microsoft/vscode/issues/15811

This is probably because I'm running it in a VM, but I don't remember seeing it before, so @Tyriar can you repro this?

In the file explorer, right click anything and click 'delete'. The confirm dialog shows up, and there are various glitches. Different every time. Usually there will be some blinking and the Code window will disappear and I see a distorted view of whatever's behind it.

![image](https://cloud.githubusercontent.com/assets/323878/20949289/6b5b18c8-bbcd-11e6-9b1b-52c3f5b6d079.png)

**Comment by roblourens** [comment]
Actually, this reproes in stable, nvm.

**Comment by bpasero** [comment]
Yeah seeing this all the time. Maybe it does not happen when you run with `--disable-gpu`?

**Comment by Tyriar** [comment]
Yes this is probably one of those Chromium in a VM graphical issues.
