### ISSUE TITLE
Ubuntu - launch configs don't show up in viewlet picker at first

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16785]
- Have all windows of vscode closed
- Open vscode, open a project with a launch.json which has never been opened before (or never debugged before?)
- Open the debug viewlet
- See that the configs don't show up

![image](https://cloud.githubusercontent.com/assets/323878/20949810/6df21106-bbd0-11e6-8f28-4e196803dccf.png)

If I click the dropdown, I can see all the options. If I pick one, it shows up in the picker. Once it shows up, it will always show up on relaunching vscode.

**Comment by isidorn** [comment]
Fixed in latest
