### ISSUE TITLE
Can't open external terminals by default from a WSL session in VS Code

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#167865]
When debugging using an external terminal from WSL you see this:

<img width="484" alt="MicrosoftTeams-image" src="https://user-images.githubusercontent.com/2193314/205131122-12a2059d-7bef-477f-bfcf-06d72fe65d4b.png">

It ends up calling the Linux exec setting:

<img width="470" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/2193314/205131244-bde36603-a927-4e98-a538-60dee28f664b.png">

Ref: https://github.com/microsoft/vscode/blob/2fa61a14b85aadde2ea126d8bf9e79e781653d00/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L228

Is there some way we can route WSL debug requests to a local external terminal? @aeschli thoughts on this? Do you think this should be handled somehow in the WSL extension? Feels like the a soft layer breaker if it goes into core.

cc @shanselman

**Comment by roblourens** [comment]
In the Slack thread, @aeschli pointed out the `WSL_DISTRO_NAME`. I think it doesn't feel too bad for us to read that to determine that the remote EH is inside WSL

**Comment by connor4312** [comment]
https://github.com/microsoft/vscode-remote-release/issues/45 is related as well. Maybe we have something generic in for remotes in core?

**Comment by aeschli** [comment]
If there's a contribution point or a env variable I can set in the WSL extension. That would be the cleanest way.

**Comment by Tyriar** [comment]
Unassigning Rob again, I think I'm doing all the work here, just might need a review/help from others.

**Comment by Tyriar** [comment]
Debugging with Windows Terminal also doesn't seem to work when these are set:

```json
  "terminal.external.windowsExec": "wt",
  "terminal.external.windowsExec": "wt.exe",
```

<img width="259" alt="image" src="https://user-images.githubusercontent.com/2193314/211893529-ba970126-ae52-4f2a-9f98-70a78956795d.png">

**Comment by Tyriar** [comment]
We explicitly support spawning a terminal:

https://github.com/microsoft/vscode/blob/1d342c908061dd7e3b4e8ac8c5a9aab327ca42e7/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L62-L65

Not debug's `runInTerminal`:

https://github.com/microsoft/vscode/blob/1d342c908061dd7e3b4e8ac8c5a9aab327ca42e7/src/vs/platform/externalTerminal/node/externalTerminalService.ts#L78-L85

**Comment by Tyriar** [comment]
I don't think it's possible to use wt properly based on `--help`, no `/c`, no `--wait` 🤔 

![image](https://user-images.githubusercontent.com/2193314/211894924-2618e12a-df95-4054-a309-1fde8c7afce5.png)

**Comment by Tyriar** [comment]
Actually /c is SUBCOMMAND, eg. `wt "cmd.exe"`

**Comment by gregg-miskelly** [comment]
I very similar issue exists for Codespaces where the `runInTerminal` request will fail, and it isn't obvious to users that that is the problem.

CC @timheuer who reported this to me

**Comment by Tyriar** [comment]
I had a go trying to fix this but it was more difficult than anticipated: https://github.com/microsoft/vscode/pull/171095
