### ISSUE TITLE
snippetsPreventQuickSuggestions doesn't prevent if start typing

### ISSUE THREAD

**Issue by DifficultNick** [microsoft/vscode#167845]
Type: <b>Bug</b>?

when `editor.suggest.snippetsPreventQuickSuggestions` is `true`:
Supposed behaviour — autocomplete handler is not fired when editing inside snippet.
Real behaviour — autocomplete handler is fired when start typing in snippet step.

When snippen is just inserted (ok):
![image](https://user-images.githubusercontent.com/18598163/205077252-28f3faab-8e9b-419d-b54b-aae79fc39cfd.png)
when start typing (autocompletes appeared):
![image](https://user-images.githubusercontent.com/18598163/205077353-96ab8c76-4e90-45fc-a905-c48a105f967d.png)

How to reproduce: modify the response of [lsp-sample](https://github.com/microsoft/vscode-extension-samples/tree/main/lsp-sample) `onCompletion` `handler` function with this:
```typescript
const attrivuteValues = ['1000', '100000', '1000000000'];
return [
	{ // full snippet
		label: 'value',
		insertText: `Value="\${1|${attrivuteValues.join(',')}|}"`,
		kind: CompletionItemKind.Snippet,
		insertTextFormat: InsertTextFormat.Snippet
	},
	...attrivuteValues.map(x => ({ // autocompletions for attr values
		label: x,
		kind: CompletionItemKind.Text
	}))
];
```

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19043
Sandboxed: No

P.S. Let me ask one more question here: is there a way to detect (from extension) if edit is inside snippet? In order to prevent the described duplication without forcing the user to change settings.

Thank you!

**Comment by svipas** [comment]
Can agree, this is kinda annoying, I always have to cancel them manually with ESC
