### ISSUE TITLE
Debug config name overflows dropdown in a Codespace 

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167894]
Found while testing https://github.com/microsoft/vscode/issues/156632

<img width="369" alt="image" src="https://user-images.githubusercontent.com/30305945/205183255-a6191aa4-2734-4709-9582-b724330e1575.png">

**Comment by roblourens** [comment]
Interesting, in Electron, there is a default style applied to all `select` from the builtin "user agent stylesheet" that sets `box-sizing: border-box`. In the browser that doesn't exist 🤔

**Comment by osortega** [comment]
@roblourens yeah we add a few things for rendering the workbench correctly.
Looks like the property messing things up is `box-sizing: content-box;` which based on the comment, seems that it was needed for VS Code itself.

I removed the attribute and everything seems ok, so I'll remove it.
