### ISSUE TITLE
Opening same workspace on another device (including terminals etc)

### ISSUE THREAD

**Issue by drmrbrewer** [microsoft/vscode#167831]
Occasionally, when away from my normal workstation, I'd like to be able to hop on to my code-server workspace to do a few bits and pieces.  In fact, that's one of the main benefits of hosting the workspace remotely, accessible from anywhere.

But I find that I don't see exactly the same workspace setup as the one when I'm at my desk.  More particularly, although I see the same folders etc, I don't have the same set of terminals already open and usable (with bash command history for ease of access), nor the same set of files already open.

Are these terminal/file settings stored locally in the browser, e.g. using cookies or [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) or something along those lines, i.e. only accessible to a specific browser?

Assuming that is the case, it would be great to have the ability to open exactly the same setup from _different_ browsers.

**Comment by sandy081** [comment]
This is as per design that the state is stored on the client side. You can use settings sync feature of VS Code to roam state.

**Comment by drmrbrewer** [comment]
@sandy081 OK thanks for the heads-up about settings sync... does the synced state include opened terminals... I can't see any mention of that?

**Comment by sandy081** [comment]
>  does the synced state include opened terminals

Opened terminals are not part of the synced data.
