### ISSUE TITLE
Moving Settings to New Tab Causes Default Settings to Go Empty

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/vscode#16789]
1.8 insiders

Steps to Reproduce:

1. Have two tabs open.
2. Open settings
3. Drag settings to other tab

See default settings area go blank

![dec-06-2016 17-34-20](https://cloud.githubusercontent.com/assets/12821956/20951377/3cc1bb0e-bbda-11e6-8cb2-f973a6f97f9a.gif)

**Comment by sandy081** [comment]
Duplicates #16743
