### ISSUE TITLE
Improved debug inline values 

### ISSUE THREAD

**Issue by dimateos** [microsoft/vscode#167853]
In C++ (dont know about other languages), the debug inline values are solved for the local scope, but it ignores local instance variables. Is quite common that a class access lots of its attributes rather than locally declared ones, so the feature seems lacking.

Prepending by "this->" does not help, in fact it shows the value of the whole instance. I can confirm this just happens with all variables idependently of the scope... this could be resolved to avoid clutter and only show the accessed value.

![image](https://user-images.githubusercontent.com/26868611/205100189-f0a5bf7e-68f5-439d-b0a1-07390a49f57e.png)

On top of that I would love options to modify which values are displayed. I can think of:
* Only last variable access (the clutter is a bit underwhelming, I decreased the default opacity)
* Only declaration (+ combine with the previous)
* Solve or not the local instance scope (I think it should be solved by default)
* Show adresses / values of referenced data
* Some padding to separate from the code
* Align all values at some column distabce (if the line is larger, just keep the previous behavior)
* There could be a separate color syle for nested variables (includes instance scope) to let the user change the shading.

**Comment by roblourens** [comment]
The extension is able to tell vscode what the variables are, so you can file this on the cpp extension repo, thanks
