### ISSUE TITLE
Text for show/hide Status/Activity bar in View menu should say "toggle"

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16787]
Testing #15812

Most of the other visibility related options are "Toggle something".
Why is the Status Bar and Activity Bar of the form "Show/Hide something" ?
We should be consistent.

The corresponding commands for Status Bar and Activity Bar say "Toggle Side/Activity Bar Visibility"

**Comment by bpasero** [comment]
We decided to be more explicit in cases where we can. since those things go through settings.json the menu can actually show the right thing. The fact that we show toggle for the other entries is UX debt.
