### ISSUE TITLE
use correct icon for terminal quick fix link types

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#167876]
We reverted this change since it's not an important fix, but can cherry pick for December

https://github.com/microsoft/vscode/pull/167784/commits/f2e4087c0c2cb14729fe115f48f98801493eca09

**Comment by Tyriar** [comment]
Also we want `go-to-file`:

![image](https://user-images.githubusercontent.com/2193314/205155240-4a02a175-8003-4eb6-9a93-cceeeff039ae.png)

**Comment by meganrogge** [comment]
there's an external link icon - perhaps we should use that instead of `link` for urls?
![Screenshot 2022-12-01 at 2 42 04 PM](https://user-images.githubusercontent.com/29464607/205155356-0a34ebf3-d6c8-4e90-a9c8-c6ca64c55d53.png)

**Comment by Tyriar** [comment]
The name certainly seems like it, let's do that but confirm in other usages
