### ISSUE TITLE
View Scale: Command Palete Entry for View Addition

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#16783]
testing: #16326 

- VSCode Version: 1.8-insiders
- OS Version: windows

Steps to Reproduce:

Should we have a command pallet entry that mimics what right clicking in the activity bar does or the `view->Additional Viewlets` menu without it you are forced to use the mouse.

Somehting in here:
![image](https://cloud.githubusercontent.com/assets/1051190/20949621/260e3d52-bbcf-11e6-9a67-4b48455c12eb.png)

**Comment by bpasero** [comment]
@seanmcbreen there should be an entry to show the new viewlet coming from an extension, what else would you expect?

**Comment by seanmcbreen** [comment]
I'm not sure how we would do this but ideally a list of each available one e.g. 
* Toggle Dependencies View
* Toggle Another Contribution View

Essentially the same items in the `view`->`additional viewlets` menu fly-out.

So in essence it's a flattened version of the menu.

**Comment by bpasero** [comment]
@seanmcbreen but there is an entry:

![image](https://cloud.githubusercontent.com/assets/900690/20969445/42761252-bc89-11e6-8e00-0f5349fdf483.png)

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
