### ISSUE TITLE
Language mode picker should give precise language matches higher priority

### ISSUE THREAD

**Issue by jtippet** [Microsoft/vscode#16788]
- VSCode Version: 1.7.2
- OS Version: Windows 10, 1607ish

Steps to Reproduce:

1. Press Ctrl+K, M to open the Language Mode picker

2. Type "C" to select the C language  (or "R" to select the R language; or "D" to select the D language [if you have code-d installed])

EXPECTED:
The C language is selected.

ACTUAL:
Some random menu option is selected.  I can't find anything that I could type to get exactly the C language.  I tried "(c)" and "C (c)" and "C99" and "CC" and "C " and "^c".  I eventually had to resort to the arrow keys to wade through the list.

PROPOSAL:
If I type something short like "c" or "go", and there's a language that exactly matches that name, always select the menu option for that specific language.  Only resort to fuzzy/substring matching if there's no language with exactly that name.

(btw, I'm new to VS code, so if there's an obvious pre-existing solution to this, please educate me!  Thanks)

**Comment by bpasero** [comment]
Fixed for January via https://github.com/Microsoft/vscode/commit/8b834d0f890f62ce25684f6b371559b4f4f6a223

**Comment by jtippet** [comment]
I tried out the daily build (Commit 80481edbdf1272a87ca54d4c48a829e0a134dffe), and I'm happy with the new behavior.  It's now easier to select the C language: Ctrl+K, M, C, <enter>.

**Comment by bpasero** [comment]
@jtippet thanks for verifying this 👍
