### ISSUE TITLE
[Setting Sync] Lost remote settings and automatic delete local settings. Crazy

### ISSUE THREAD

**Issue by Innei** [microsoft/vscode#167984]
- VS Code Version: 1.73.1
- OS Version: macOS 13.0.1

Steps to Reproduce:

1. I opened the new install vscode and opened it to sync, then notified me to restart vscode. And then, I lost all remote settings. Crazy.
<img width="359" alt="image" src="https://user-images.githubusercontent.com/41265413/205428724-c8158e5a-88d1-48f5-b7e6-86f5d57393de.png">

A new empty setting sync and replace remote settings, and I page down all synced data, all older settings are missing.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/41265413/205428760-d7cd4742-f657-497a-ab7a-a1ccabcb8d4f.png">

I realized something was wrong and immediately opened vscode on the second computer to copy the local configuration on the second computer, but it synced immediately, replacing the second computer's local setting. So I lost my vscode setting forever.

How can I find my settings. And why is there such a low-level bug

**Comment by sandy081** [comment]
> I opened the new install vscode and opened it to sync, then notified me to restart vscode. And then, I lost all remote settings. Crazy.

Can you please elaborate on this? Are you able to reproduce this?

You can get back your data from the history (shown in the above pictures), for eg:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/10746682/205919286-3ac47eb8-747b-482f-93ea-cfa85d521d5c.png">

**Comment by Innei** [comment]
> > I opened the new install vscode and opened it to sync, then notified me to restart vscode. And then, I lost all remote settings. Crazy.
> 
> Can you please elaborate on this? Are you able to reproduce this?
> 
> You can get back your data from the history (shown in the above pictures), for eg:
> 
> <img alt="image" width="386" src="https://user-images.githubusercontent.com/10746682/205919286-3ac47eb8-747b-482f-93ea-cfa85d521d5c.png">

No, can't. Because my history settings all gone, I don't know why, but it's all gone. Only the nearest ones, and they're all blank settings.

Now, I find my last week settings on my another mac, I just cutting down network then open vscode, got my setting.

**Comment by sandy081** [comment]
Can you please elaborate on this? Are you able to reproduce this? We would like to understand the issue and see if we can fix it.
