### ISSUE TITLE
Activity bar: show position viewlet will move to while drag and drop

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#16799]
Instead of replacing the dragged viewlet with the one to drop on, it would be nice to animate this (similar to how editors are animated when moved) so that you see exactly where a viewlet will move to.

**Comment by benibenj** [comment]
@bpasero Is this not supported? Could you clarify the feature otherwise

**Comment by bpasero** [comment]
This is an ask to show drag-and-drop feedback live, i.e. already move the icon to the target position before releasing the mouse.

**Comment by benibenj** [comment]
Closing as we are not doing this anywhere and I don't see this happening in the short term
