### ISSUE TITLE
Cursor issue

### ISSUE THREAD

**Issue by somesh4545** [microsoft/vscode#167981]
ADD ISSUE DESCRIPTION HERE

the original cursor is in the code file now when we tap on the already opened terminal and start typing it doesn't type on terminal instead it types on the last location that is in the file. Same goes the case with ctrl F for finding words in code.

Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by Tyriar** [comment]
Please provide a screenshot or [a gif](https://gifcap.dev/) illustrating the problem (attaching images won't work via email, you need to go to github.com). See [this wiki page](https://github.com/microsoft/vscode/wiki/Terminal-Issues) for more general info on how to report actionable terminal issues.

/label "info-needed" terminal
