### ISSUE TITLE
Code folding based on tags not indentation for php / html

### ISSUE THREAD

**Issue by daslicht** [microsoft/vscode#167989]
Code folding based on tags not indentation for php / html

Please add thge ability to collapse tags with a structure like this:
```
<div>
       <section>
<?
//collapsing the div is not working
?>
       </section>
</div>
```

atm it is impossible to collapse the above div

**Comment by aeschli** [comment]
For this you need a language aware folding provider. The built-in provider is only based on indentation.

Please try one of the PHP extensions that add such a provider.

**Comment by daslicht** [comment]
I tried all php plugins, non woks like this, do you know one ?

**Comment by aeschli** [comment]
Sorry, I'm not a PHP user. You an always file an issue against the extension you favour.
