### ISSUE TITLE
Trim Trailing Whitespace Breaks Markdown

### ISSUE THREAD

**Issue by TheColorRed** [Microsoft/vscode#1679]
When this is set to `true`

    "files.trimTrailingWhitespace": true

trailing spaces get removed at the end of the line in `md`/`markdown` files. By default, two spaces in markdown is the same as a `<br>`. When saving the file with that setting, those two spaces get removed and it changes the output of the markdown.

**Comment by bpasero** [comment]
Well I think we need language specific setting overrides which we have a feature request already for.

**Comment by matthewjohnston4** [comment]
@bpasero could you link to the other feature request to make it easy to find? Not sure whether this issue has been fixed!

**Comment by bpasero** [comment]
I think you can use the editor-config extension to configure this now (https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

**Comment by pszlazak** [comment]
Successfully disabled `files.trimTrailingWhitespace` for Markdown using [language specific configuration](https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings).  
Snippet from my `settings.json`:  
```
    "files.trimTrailingWhitespace": true,
    "[markdown]": {
        "files.trimTrailingWhitespace": false
    },
```
