### ISSUE TITLE
Ability to Validate CSON files via JSON Schema

### ISSUE THREAD

**Issue by cstayyab** [microsoft/vscode#167932]
We have the ability to validate JSON files matching a specific pattern using `json.schemas` in `settings.json`. It would be great if we can do the same for other JSON like format specifically for `CSON` files. For example:
```json
        {
            "fileMatch": [
                "*.cson"
            ],
            "url": "https://raw.githubusercontent.com/cstayyab/mve-cson-schemas-feature-vscode/master/test.schema.json"
        }, 
```
**NOTE:** Here is the complete simplified example in following repo:  https://github.com/cstayyab/mve-cson-schemas-feature-vscode

The above schema should `invaidate` the following CSON:
```cson
firstName: "Muhammad Tayyab"
lastName: "Sheikh"
age: "24"
```

There is an NPM package (https://www.npmjs.com/package/pajv) capable of doing this via Commandline:
`$:` `pajv -s test.schema.json -d person.cson`

With following Output
```
person.cson invalid
[
  {
    keyword: 'type',
    dataPath: '.age',
    schemaPath: '#/properties/age/type',
    params: { type: 'integer' },
    message: 'should be integer'
  }
]
```

Can this be achived either by directly implementing this feature from scratch (e.g. converting CSON file to JSON behind the scene and validating it with schema) or by integrating this above package to VS Code?

**Comment by aeschli** [comment]
That would have to come from a language extension for CSON. The same is done with YAML.
The YAML language server internally uses the `vscode-json-langageservice` that implements the schema validation support also for NON-JSON input
