### ISSUE TITLE
[tunnel] JS Debug Terminal is too slow

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#167911]
* use code tunnel
* use vscode sources
* open JS debug terminal
* run `yarn run gulp vscode-darwin-arm64`
* it takes **2** minutes before it actually starts doing something

The debug terminal is such a great too, esp for all the engineering work I am lately doing, but being a debugger-driven developer that's too much to endure.

**Comment by connor4312** [comment]
This isn't really related to the tunnel, but is a good opportunity to improve...
