### ISSUE TITLE
now that we detect screen readers, consider not prompting

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#167962]
We should not prompt IMO anymore since we detect the screen reader.

**Comment by meganrogge** [comment]
@isidorn let's discuss this on Monday

**Comment by isidorn** [comment]
I like the idea, but I suggest that we leave the prompt for at least one more milestone.
After that, we can compare the number of accessibility users we have after @deepak1556 changes and see how precise the detection is.

We might also see that the detection is more precise on some platforms, in which case we can leave the prompt only for some platforms.

@meganrogge Does that make sense? What do you think?

fyi @alexdima who introduced the prompt initially

**Comment by meganrogge** [comment]
Safe to remove now?

**Comment by isidorn** [comment]
I suggest to leave it on for at least one more milestone since our accessibility detection got off.
I will assign it to March for now. Hope that is ok.

**Comment by isidorn** [comment]
Thanks for fixing this. I just assigned to October and added verification-needed. I think the verify steps are the following:

On Windows turn on NVDA
1. start VS Code insiders (have no settings set). 
2. Open an editor, type some text 
3. Make sure NVDA reads this text as you navigate through it character by character

Same on macOS with VoiceOver.

**Comment by meganrogge** [comment]
I haven't heard user complaints, so let's just keep this
