### ISSUE TITLE
Tasks use Windows instead of WSL env on WSL

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#167969]
That is unexpected and looks like a bug on our side - specifically here. It does not look like a new issue/regression to me

https://github.com/microsoft/vscode/blob/7df4fd594f047d2a6c8b884d6bfb985d6e2a468c/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1075-L1086

_Originally posted by @meganrogge in https://github.com/microsoft/vscode-docker/issues/3722#issuecomment-1335869829_

**Comment by meganrogge** [comment]
not sure how involved this will be, but will try to investigate in December

fyi @Tyriar

**Comment by Tyriar** [comment]
@meganrogge can you elaborate? The snippet you linked looks right as os should be the remote OS, no?

**Comment by meganrogge** [comment]
I recall that we've had issues in the past when resolving the `os` on the renderer side, so figured that was also happening here. will need to investigate to confirm that though and might be wrong 🤷🏼‍♀️

**Comment by Tyriar** [comment]
platform is sourced from here:

https://github.com/microsoft/vscode/blob/7df4fd594f047d2a6c8b884d6bfb985d6e2a468c/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1365

Might be fine?

**Comment by meganrogge** [comment]
Yes looks right to me and I tested in WSL by running a task that echoes the `${pathSeparator}` which would be wrong if it had the wrong platform, but it was correct

**Comment by bwateratmsft** [comment]
@meganrogge we're using `CustomExecution`-based tasks, with the `resolvedDefinition` parameter that gets passed into the callback. Could that be behaving differently than what you tested?

**Comment by bwateratmsft** [comment]
I just tested and I think it _is_ using the Windows environment to substitute variables. From the "Developer Tools" window on my Remote - WSL window:
```
process.env.FOO
'windowshost'
```

From the terminal in the same Remote - WSL window:
```sh
bwater@BWATER-WIN11:~/src/dotnetproj$ echo $FOO
wslhost
```

Running a `CustomExecution` task with a `${env:FOO}` substitution:
```json
{
    "type": "docker-build",
    "label": "docker-build: debug",
    "dependsOn": [
        "build"
    ],
    "dockerBuild": {
        "tag": "dotnetproj:${env:FOO}", // Here's the substitution
        "target": "base",
        "dockerfile": "${workspaceFolder}/Dockerfile",
        "context": "${workspaceFolder}",
        "pull": true
    },
    "netCore": {
        "appProject": "${workspaceFolder}/dotnetproj.csproj"
    }
},
```

The command it runs (built from the resolved definition):
```
docker image build --pull --file '/home/bwater/src/dotnetproj/Dockerfile' --target 'base' --tag 'dotnetproj:windowshost' --label 'com.microsoft.created-by=visual-studio-code' '/home/bwater/src/dotnetproj'
```
(Note the "dotnetproj:**windowshost**" as the `--tag` value)
