### ISSUE TITLE
GIT commands are slow

### ISSUE THREAD

**Issue by ruoyu0088** [Microsoft/vscode#16794]
- VSCode Version:  1.7.2
- OS Version: windows 7 64bit

Steps to Reproduce:

All the git operations are slow. For example, it costs about 3 seconds to stage a file in a very small repository.  

I manual run the same git command:  `git add -A -- testfile.txt` in the terminal, it's very fast. 

I run the profile in the develop tools, but the total times are small, execpt `(idle)` and `(program)`. 

About the git:

I install the git from https://git-scm.com/, the version is git version 2.11.0.windows.1, 32bit.  and set the path in `settings.json` as following:

```
"git.path": "C:/Program Files (x86)/Git/cmd/git.exe"
```

here is the output of `where git` in the terminal:

```
where git
C:\Program Files (x86)\Git\cmd\git.exe
C:\Program Files (x86)\Git\bin\git.exe
```

So, I am using the same git.exe.

I also tried git 64 bit, but it's even slower then the 32bit version.

This happens to my two 64bit windows PC. But on an other 32bit windows PC, its's very fast.

**Comment by joaomoreno** [comment]
Interesting!

Which version of git do you have it installed? Where is `git.exe` located?

**Comment by whitecolor** [comment]
I use `git version 2.7.1.windows.2` and VSCode UI git operation is comparing to commands I usually use in the terminal, but I believe it is due to multiple git commands running by VSCode for one commit, I'm not sure but maybe this could be improved too. Because it really seems slow and not very pleasant experience.

**Comment by joaomoreno** [comment]
Thanks for the feedback. We won't do much for now, but keep it in mind for the future.
