### ISSUE TITLE
Intellisense for React Native not working at all

### ISSUE THREAD

**Issue by iChristosK** [microsoft/vscode#167912]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1 (Universal)
- OS Version:  macOS Ventura 13.0.1 (22A400)

Date: 2022-11-09T02:08:38.961Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.1.0
Sandboxed: No
Steps to Reproduce:

1. Purchase new Mac M1 Pro
2. Unable to add Intellisense for React Native on VS Code on M1 Mac.

Running react-native doctor on my project
`npx react-native doctor`
```
Common
 ✓ Node.js
 ✓ yarn
 ✓ Watchman - Used for watching changes in the filesystem when in development mode

Android
 ✓ JDK
 ✓ Android Studio - Required for building and installing your app on Android
 ✓ Android SDK - Required for building and installing your app on Android
 ✓ ANDROID_HOME

iOS
 ✓ Xcode - Required for building and installing your app on iOS
 ✓ CocoaPods - Required for installing iOS dependencies
 ✓ ios-deploy - Required for installing your app on a physical device with the CLI
 ✓ .xcode.env - File to customize Xcode environment

Errors:   0
Warnings: 0

```

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by iChristosK** [comment]
Just downloaded the mentioned VS code, and it works like a charm. You have no idea how much I appreciate your comment. It was affecting my workflow at work. Thank you @mjbvz
