### ISSUE TITLE
Error loading webview: Error: Could not register service workers

### ISSUE THREAD

**Issue by mdilshan** [microsoft/vscode#167929]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.73.1 (Universal)
- OS Version: Darwin arm64 20.6.0

```
Version: 1.73.1 (Universal)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 20.6.0
Sandboxed: No
```

Steps to Reproduce:

1. Open VS code & Navigate to Extension Page
2. Click on any extension page
3. View **Details** or **Changelog** tabs of the extension

Error:

```
Error loading webview: Error: Could not register service workers: 
InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

**Comment by gjsjohnmurray** [comment]
Does a restart of VS Code solve this?

**Comment by mdilshan** [comment]
No it didn't. However I did restarted the computer & it fixed the issue.

**Comment by tomcanham** [comment]
So VS Code has "restart your computer" as an acceptable solution? I'm seeing this error, too, and I have far too many processes running for restarting my computer to be a viable solution.

**Comment by gjsjohnmurray** [comment]
@tomcanham the person who opened this issue decided to close it when a reboot resolved it. I suggest you open a new issue with as much information as possible, ideally including repro steps. The Report Issue option from the Help menu is a good way to get details of your configuration included.
