### ISSUE TITLE
Notebook cell editor renders with wrong height

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167976]
1. open my-endgame.github-issues
2. run all cells
3. scroll to last cell
4. :bug: run button renders on top of execution count, also query in the cell input is not rendered
![image](https://user-images.githubusercontent.com/30305945/205407091-56c9995e-6f3e-406d-8905-8e648794c17d.png)

Collapsing the cell allows me to see the first line of the code cell but if I expand it it reverts to the behavior above. Scrolling the cell out of view and back into view also doesn't help
![image](https://user-images.githubusercontent.com/30305945/205407423-2e4d5624-3791-441f-8092-cc79456225ab.png)

**Comment by rebornix** [comment]
@joyceerhl is there anything suspicious in dev tools?

**Comment by joyceerhl** [comment]
Can't repro anymore unfortunately :/

**Comment by rebornix** [comment]
My guess is the model is disposed somehow, thus the editor is disposed. I'm closing this for now, but it would be great if you can check the dev tools if you run this again and we then reopen this issue.
