### ISSUE TITLE
Every time I click on the debug console tab, the terminal tab will disappear

### ISSUE THREAD

**Issue by blessli** [microsoft/vscode#167982]
Type: <b>Bug</b>

Every time I click on the debug console tab, the terminal tab will disappear? And other people's vscode of the same version as mine is normal。

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (5.22GB free)|
|Process Argv|--crash-reporter-id 44727d2f-6dcb-48cf-972a-33547f6cdcf1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (37)</summary>

Extension|Author (truncated)|Version
---|---|---
lua-debug|act|1.60.1
doxdocgen|csc|1.4.0
vue-peek|dar|1.0.2
gitlens|eam|13.1.1
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
go|gol|0.36.0
vue-snippets|hol|1.0.4
path-alias|IWA|0.12.3
better-cpp-syntax|jef|1.16.3
vscode-elm-jump|joe|0.0.1
vscode-docker|ms-|1.23.1
vscode-language-pack-zh-hans|MS-|1.73.11090913
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.12.4
cpptools-extension-pack|ms-|1.3.0
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.0.2
vscode-vue2-snippets|Nic|1.3.1
vetur|oct|0.36.1
java|red|1.13.0
vscode-xml|red|0.22.0
scala|sca|0.5.6
metals|sca|1.20.0
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.1
volar|Vue|1.0.10

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by blessli** [comment]
![image](https://user-images.githubusercontent.com/36662094/205427190-12708c46-a32e-4f03-bfff-effc167cd2b0.png)

**Comment by blessli** [comment]
ask for help~ @roblourens

**Comment by meganrogge** [comment]
I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)?
/label info-needed

**Comment by Tyriar** [comment]
This is related to view layout. I suspect you have hidden the terminal title, try right clicking the terminal title and see if it's checked.

**Comment by blessli** [comment]
> I believe this is already fixed, can you see if you can reproduce in the [Insiders build](https://code.visualstudio.com/insiders)? /label info-needed

thank you for your reply.  I am also very puzzled why the vscode of my colleagues in the company is normal, but this problem occurs in my vscode (and I compared the vscode version, it is exactly the same).  And I have the default configuration without any modification.  Your rebuild URL cannot download the exe program, and it is always interrupted halfway through the download

**Comment by blessli** [comment]
> @blessli this is the menu @Tyriar is referring to.
> 
> <img alt="image" width="246" src="https://user-images.githubusercontent.com/6561887/205990366-3ca81d83-681a-4526-9df4-426d29120468.png">
> 
> If the highlighted entry does not have a check mark, the you should select it to prevent it from hiding.

it work。thank you very much。this issue have solved~
