### ISSUE TITLE
Adopt implicit activation events for `onTerminalQuickFixRequest`

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#167949]
Extension authors should not have to explicitly spell out an activation event in order to get activated to provide terminal quick fixes. The terminal extension point can specify how to derive implicit activation events from contribution points here: https://github.com/microsoft/vscode/blob/ec70dcd6d8ea030a1e13cf86f47e69a34803e976/src/vs/workbench/contrib/terminal/common/terminal.ts#L729-L834

Example for notebooks:
https://github.com/microsoft/vscode/blob/8007c639810ac284733e1ee3acc901d5b480e706/src/vs/workbench/contrib/notebook/browser/notebookExtensionPoint.ts#L236-L242

Other adoption: https://github.com/microsoft/vscode/issues/166624

**Comment by joyceerhl** [comment]
Also consider adopting for `onTerminalProfile` https://github.com/microsoft/vscode-docs/blob/eead5f143f30aca35d8b7a4165f040fd506f9218/api/references/contribution-points.md#L1172-L1193

**Comment by Tyriar** [comment]
Done in https://github.com/microsoft/vscode/pull/173040
