### ISSUE TITLE
keyboard doing crazy stuf

### ISSUE THREAD

**Issue by CmdSpock** [microsoft/vscode#167994]
Type: <b>Bug</b>

on apple, opened directory, opend file started removing tekst, wanted to insert text (numbers, by the numerical keyboard) didn't work... 
other keys (numbers on the main, letters on the main board) jump over the place, some remove whole lines

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz (6 x 3700)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (12.03GB free)|
|Process Argv|--crash-reporter-id 13a81f63-cc39-4581-bc2a-8f653de0238b|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-class-suggestions|And|1.1.1
vscode-color|ans|0.4.5
vscode-eslint|dba|2.2.6
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.3
vscode-firefox-debug|fir|2.9.8
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vscode-gutter-preview|kis|0.30.0
ecsstractor|kub|2.4.2
compare-folders|mos|0.22.3
vscode-edge-devtools|ms-|2.1.1
printcode|nob|3.0.0
vscode-css-peek|pra|4.2.0
LiveServer|rit|5.7.9
nativeemmet|Sau|0.0.8
code-spell-checker|str|2.11.1
code-spell-checker-dutch|str|0.3.5
lorem-ipsum|Tyr|1.3.1
vim|vsc|1.24.3
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by alexdima** [comment]
It looks like you have installed the vim extension and perhaps you don't want it.
