### ISSUE TITLE
The File Management Tool in Explore 

### ISSUE THREAD

**Issue by isJHan** [microsoft/vscode#167993]
Hello, VSCode is the best code editor tool I have ever used. However, the file management tool in Explore sidebar is the worst I have ever used. For example, when I click a folder, it expands automatically even though I just want to push 'Enter' then rename that folder. At the same time, the file tree structure is no a good visual implementation. I usually delete or cut wrong files for this reason. 

I will be very grateful if you optimize this function! Thank you!

**Comment by lramos15** [comment]
Thanks for the issue, it's really hard to track issues when they contain multiple suggestions. You can find our issue reporting guidelines [here](https://github.com/microsoft/vscode/wiki/Submitting-Bugs-and-Suggestions).

If you're already utilizing the mouse wouldn't it be easiest to right click the folder then? If you keyboard navigate then you click enter to trigger a rename.

As for the tree structure, is it just that it's too compact? Maybe some issues such as https://github.com/microsoft/vscode/issues/144120 or https://github.com/microsoft/vscode/issues/162428 cover the issues you have. You can find all explorer issues with this [query](https://github.com/microsoft/vscode/issues?q=is%3Aopen+is%3Aissue+label%3Afile-explorer)
