### ISSUE TITLE
While applying stash , stash title copied to commit message 

### ISSUE THREAD

**Issue by bhaveshpatel-developer** [microsoft/vscode#167907]
Type: <b>Bug</b>

Whenever we apply stash then stash message applies to commit message in source control window. It stays when we apply conflict resolved branch also. at that time it.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T03:54:53.913Z)
OS version: Linux x64 5.15.0-56-generic snap
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1400)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.37GB (7.35GB free)|
|Process Argv|--no-sandbox --force-user-env --unity-launch --crash-reporter-id 8dd4fe28-d5e4-4cfb-be0f-b3e47cced9b2|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
laravel-extra-intellisense|ami|0.6.2
atlascode|atl|2.10.12
vscode-intelephense-client|bme|1.8.2
gitlens|eam|13.1.1
go|gol|0.36.0
remote-containers|ms-|0.262.3
laravel5-snippets|one|1.15.0
vscode-yaml|red|1.10.1
code-snapshot|rob|0.2.1
trailing-spaces|sha|0.4.1
php-debug|xde|1.29.0
php-intellisense|zob|1.0.11

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

![image](https://user-images.githubusercontent.com/101866333/205230760-47fed24e-6ebc-4778-a580-75440007a628.png)
![image](https://user-images.githubusercontent.com/101866333/205230924-6c91c3ac-d8e4-4a20-8642-a5ae5c8089c0.png)

**Comment by gjsjohnmurray** [comment]
Does this also happen if you disable the GitLens extension?

**Comment by bhaveshpatel-developer** [comment]
I am not sure. I think it is related to GitLens extension.

**Comment by lszomoru** [comment]
@bhaveshpatel-developer, thanks for the update. I will go ahead and close this issue based on your latest update. Please feel free to file an issue in the extension's repository - https://github.com/gitkraken/vscode-gitlens. Thanks!
