### ISSUE TITLE
Consider using a new Java grammar: Text block(JEP 378) breaks Java syntax highlighting

### ISSUE THREAD

**Issue by tzengshinfu** [microsoft/vscode#167913]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Windows 10 22H2 19045.2251

Steps to Reproduce:

Create a Java file with a text block that contains double quotes.
![img-20221202-165011](https://user-images.githubusercontent.com/2170033/205275948-ffda744a-fc56-4799-8544-563055c2395d.png)

Current Result
Notice the codes after text block are fully orange.

Expected Result
Syntax highlighting is correct.

Workaround
Add an escape character in each double quote.
![img-20221202-184608](https://user-images.githubusercontent.com/2170033/205275985-5bde4bc0-4f5b-4371-9d2f-8bb36aa93cc6.png)

**Comment by RedCMD** [comment]
The current syntax highlighter doesn't support java `Text Blocks`
prob should report to https://github.com/atom/language-java
https://github.com/atom/language-java/issues/207

**Comment by alexr00** [comment]
Given that https://github.com/atom/language-java will be archived, I'm repurposing this issue for considering a new Java grammar.

**Comment by alexr00** [comment]
Possibly a good candidate grammar: https://github.com/georgewfraser/java-language-server

**Comment by RedCMD** [comment]
@alexr00 but that repo doesn't have textmate syntax highlighting??

**Comment by alexr00** [comment]
They do have a grammar though: https://github.com/georgewfraser/java-language-server/blob/master/lib/java.tmLanguage.json

I haven't checked whether it would be an improvement.

**Comment by alexr00** [comment]
The grammar from https://github.com/georgewfraser/java-language-server doesn't highlight as much, so it's not a good option:

<img width="1179" alt="image" src="https://github.com/microsoft/vscode/assets/38270282/b24adc0e-9b7f-48d0-a0e4-907d60532fc3">

**Comment by alexr00** [comment]
New grammar was adopted with https://github.com/microsoft/vscode/pull/188361
