### ISSUE TITLE
Unexpected suggestion selected

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16798]
I would expect `proxy` to be the selected suggestion in this case, given the completion item type. I know this might contradict with the shortest suggestion rule, but it was really unexpected for me when I ended up in a complicated snippet when I wanted to do a "trivial" property assignment in a ctor.

![image](https://cloud.githubusercontent.com/assets/5047891/20962289/06001680-bc69-11e6-8713-5c3ec871f4c2.png)

settings:
```
{
	"editor.fontFamily": "Hack",
	"editor.fontSize": 16,
	"editor.renderWhitespace": "boundary",
	"editor.renderIndentGuides": true,
	"files.autoSave": "afterDelay",
	"editor.renderLineHighlight": "gutter",
	"telemetry.enableTelemetry": false,
	"telemetry.enableCrashReporter": false,
	"editor.wordSeparators": "`~!@#%^&*()-=+[{]}\\|;'\",.<>/?"
}
```

**Comment by jrieken** [comment]
@alexandrudima Are you suggesting to demote snippet suggestions?

**Comment by alexandrudima** [comment]
I'm not sure I know how this could be tackled, it's just for me as an end user it seems obvious proxy should have been chosen given I'm assigning an argument to a member of the same type. 

I don't know how this could be improved in our scoring algorithm or in our current data types, perhaps the scoring should take into account word frequency, perhaps TypeScript should provide us with some scores ... ? 

e.g. Never do we ever in our codebase use WebGLProgram, or PropertyDescriptorMap, or XSLTProcessor, yet they are there, ... adding to the noise...

**Comment by jrieken** [comment]
This is now better as we sort by score. There is still some ambiguity between the matches because TypeScript doesn't rank `proxy` higher than global symbol suggestions. That's nothing suggest can decide. Closing this as half fixed
