### ISSUE TITLE
crash on mac

### ISSUE THREAD

**Issue by pokerchina** [Microsoft/vscode#16791]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|java-debug|DSnake|0.0.2|
|Bookmarks|alefragnani|0.10.1|
|mock-debug|andreweinand|0.16.5|
|npm-intellisense|christian-kohler|0.1.4|
|path-intellisense|christian-kohler|1.1.0|
|vscode-npm-source|dkundel|0.0.3|
|githistory|donjayamanne|0.1.2|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.5|
|vscode-javac|georgewfraser|0.0.23|
|Go|lukehoban|0.6.51|
|Theme-MarkdownKit|ms-vscode|0.1.1|
|cpptools|ms-vscode|0.9.2|
|csharp|ms-vscode|1.5.3|
|mono-debug|ms-vscode|0.11.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|node-modules-resolve|naumovs|1.0.2|
|erlang|pgourlain|0.0.9|
|java|redhat|0.0.7|
|yo|samverschueren|0.9.3|
|cmake|twxs|0.0.15|
|jsirdebugger|muji|0.0.7|
|debug|webfreak|0.12.3|

---

Steps to Reproduce:

1. UE4 engine
2. code .
3. Cmd+T
4. search FName

Process:               Microsoft.VSCode.CPP.Extension.darwin [34739]
Path:                  /Users/USER/*/Microsoft.VSCode.CPP.Extension.darwin
Identifier:            Microsoft.VSCode.CPP.Extension.darwin
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        Code Helper [34720]
Responsible:           iTerm2 [445]
User ID:               501

Date/Time:             2016-12-07 13:26:15.488 +0800
OS Version:            Mac OS X 10.11.6 (15G1108)
Report Version:        11
Anonymous UUID:        2F8901A6-5C84-7E04-DA4C-FC4EC0F4233E

Sleep/Wake UUID:       915FD4E1-0A6E-42EE-8E04-004FD919ACD9

Time Awake Since Boot: 37000 seconds
Time Since Wake:       10000 seconds

System Integrity Protection: enabled

Crashed Thread:        1

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000700000209a86

VM Regions Near 0x700000209a86:
    Stack                  0000700000107000-0000700000189000 [  520K] rw-/rwx SM=COW  thread 3
--> 
    Stack                  000070000020a000-000070000020c000 [    8K] rw-/rwx SM=PRV  

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fffa08f9f8a __read_nocancel + 10
1   libsystem_c.dylib             	0x00007fff9db40155 _sread + 16
2   libsystem_c.dylib             	0x00007fff9db3f769 __srefill1 + 24
3   libsystem_c.dylib             	0x00007fff9db3f884 __srget + 14
4   libsystem_c.dylib             	0x00007fff9db3b52b getc + 52
5   libc++.1.dylib                	0x00007fff8c417051 std::__1::__stdinbuf<char>::__getchar(bool) + 119
6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d2610f9 std::__1::basic_istream<char, std::__1::char_traits<char> >& std::__1::getline<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_istream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, char) + 153
7   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d234fb7 vscode::handler_base<message_handler>::main_loop() + 375
8   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d234df6 main + 102
9   libdyld.dylib                 	0x00007fff9e6ca5ad start + 1

Thread 1 Crashed:
0   libsystem_c.dylib             	0x00007fff9db582e9 strstr + 42
1   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d27d091 browse_engine::query_files(char const*, std::__1::vector<browse_symbol, std::__1::allocator<browse_symbol> >&) + 273
2   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d240086 message_handler::workspace_symbol(vscode::WorkspaceSymbolParams) + 70
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d238b53 vscode::handler_base<message_handler>::dispatch(vscode::vscode_client_message&&, vscode::vscode_server_message&, bool) + 8643
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d2366a9 vscode::handler_base<message_handler>::handle_message(vscode::vscode_client_message&&) + 57
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d2365eb vscode::handler_base<message_handler>::main_loop()::'lambda'()::operator()() const + 75
6   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d236560 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda'()> >(void*) + 96
7   libsystem_pthread.dylib       	0x00007fff91dee99d _pthread_body + 131
8   libsystem_pthread.dylib       	0x00007fff91dee91a _pthread_start + 168
9   libsystem_pthread.dylib       	0x00007fff91dec351 thread_start + 13

Thread 2:
0   libsystem_kernel.dylib        	0x00007fffa08f9db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff91def728 _pthread_cond_wait + 767
2   libc++.1.dylib                	0x00007fff8c40968f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 47
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d260cb2 vscode::message_queue<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::pop() + 82
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d260be3 vscode::handler_base<message_handler>::main_loop()::'lambda0'()::operator()() const + 67
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d260b60 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda0'()> >(void*) + 96
6   libsystem_pthread.dylib       	0x00007fff91dee99d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff91dee91a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff91dec351 thread_start + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fffa08f9db6 __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff91def728 _pthread_cond_wait + 767
2   libc++.1.dylib                	0x00007fff8c40968f std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 47
3   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d2367c2 vscode::message_queue<vscode::vscode_client_message>::pop() + 82
4   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d260ed0 vscode::handler_base<message_handler>::main_loop()::'lambda1'()::operator()() const + 64
5   Microsoft.VSCode.CPP.Extension.darwin	0x000000010d260e50 void* std::__1::__thread_proxy<std::__1::tuple<vscode::handler_base<message_handler>::main_loop()::'lambda1'()> >(void*) + 96
6   libsystem_pthread.dylib       	0x00007fff91dee99d _pthread_body + 131
7   libsystem_pthread.dylib       	0x00007fff91dee91a _pthread_start + 168
8   libsystem_pthread.dylib       	0x00007fff91dec351 thread_start + 13

Thread 1 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000004  rbx: 0x0000700000209a86  rcx: 0x000000000000000a  rdx: 0x000070000008074a
  rdi: 0xfffffffffffffff6  rsi: 0x000000000000c000  rbp: 0x00007000000802a0  rsp: 0x0000700000080270
   r8: 0x000000000000004e   r9: 0x000000010d73f590  r10: 0x00000000ffffffff  r11: 0xfffffffffffffc68
  r12: 0x00007f97845a37c0  r13: 0x0000700000080346  r14: 0x000070000008074a  r15: 0x0000000000000004
  rip: 0x00007fff9db582e9  rfl: 0x0000000000010213  cr2: 0x0000700000209a86
  
Logical CPU:     1
Error Code:      0x00000004
Trap Number:     14

Binary Images:
       0x10d233000 -        0x10d7a7fff +Microsoft.VSCode.CPP.Extension.darwin (0) <B92C812D-9B9E-3512-B3FC-8FF2E151805C> /Users/USER/*/Microsoft.VSCode.CPP.Extension.darwin
    0x7fff62014000 -     0x7fff6204ba47  dyld (360.22) <DC81CC9D-651A-3A45-8809-928282052BD3> /usr/lib/dyld
    0x7fff8b6e6000 -     0x7fff8b6e6ff7  liblaunch.dylib (765.50.8) <834ED605-5114-3641-AA4D-ECF31B801C50> /usr/lib/system/liblaunch.dylib
    0x7fff8b845000 -     0x7fff8b856ff7  libsystem_trace.dylib (201.10.3) <E9311C03-9E61-3B13-AF3F-A64956FFF269> /usr/lib/system/libsystem_trace.dylib
    0x7fff8b9fe000 -     0x7fff8b9feff7  libkeymgr.dylib (28) <8371CE54-5FDD-3CE9-B3DF-E98C761B6FE0> /usr/lib/system/libkeymgr.dylib
    0x7fff8ba8d000 -     0x7fff8bab6ff7  libxpc.dylib (765.50.8) <54D1328E-054E-3DAA-89E2-375722F9D18F> /usr/lib/system/libxpc.dylib
    0x7fff8c402000 -     0x7fff8c455ff7  libc++.1.dylib (120.1) <8FC3D139-8055-3498-9AC5-6467CB7F4D14> /usr/lib/libc++.1.dylib
    0x7fff8c4c0000 -     0x7fff8c4c2ff7  libquarantine.dylib (80) <0F4169F0-0C84-3A25-B3AE-E47B3586D908> /usr/lib/system/libquarantine.dylib
    0x7fff8f072000 -     0x7fff8f0a1ffb  libsystem_m.dylib (3105) <08E1A4B2-6448-3DFE-A58C-ACC7335BE7E4> /usr/lib/system/libsystem_m.dylib
    0x7fff8f320000 -     0x7fff8f328fef  libsystem_platform.dylib (74.40.2) <29A905EF-6777-3C33-82B0-6C3A88C4BA15> /usr/lib/system/libsystem_platform.dylib
    0x7fff8f39b000 -     0x7fff8f6fdf3f  libobjc.A.dylib (680) <7489D2D6-1EFD-3414-B18D-2AECCCC90286> /usr/lib/libobjc.A.dylib
    0x7fff9003a000 -     0x7fff90051ff7  libsystem_asl.dylib (323.50.1) <41F8E11F-1BD0-3F1D-BA3A-AA1577ED98A9> /usr/lib/system/libsystem_asl.dylib
    0x7fff91a17000 -     0x7fff91a5dff7  libauto.dylib (186) <999E610F-41FC-32A3-ADCA-5EC049B65DFB> /usr/lib/libauto.dylib
    0x7fff91dce000 -     0x7fff91dd7ff3  libsystem_notify.dylib (150.40.1) <D48BDE34-0F7E-34CA-A0FF-C578E39987CC> /usr/lib/system/libsystem_notify.dylib
    0x7fff91deb000 -     0x7fff91df4ff7  libsystem_pthread.dylib (138.10.4) <3DD1EF4C-1D1B-3ABF-8CC6-B3B1CEEE9559> /usr/lib/system/libsystem_pthread.dylib
    0x7fff925a9000 -     0x7fff925aafff  libsystem_blocks.dylib (65) <1244D9D5-F6AA-35BB-B307-86851C24B8E5> /usr/lib/system/libsystem_blocks.dylib
    0x7fff925c3000 -     0x7fff925edff7  libc++abi.dylib (307.2) <922EFB36-0E9E-315B-8270-E81AC43472C0> /usr/lib/libc++abi.dylib
    0x7fff93f9c000 -     0x7fff93f9efff  libsystem_coreservices.dylib (19.2) <1B3F5AFC-FFCD-3ECB-8B9A-5538366FB20D> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff93f9f000 -     0x7fff93faaff7  libcommonCrypto.dylib (60075.50.1) <93732261-34B4-3914-B7A2-90A81A182DBA> /usr/lib/system/libcommonCrypto.dylib
    0x7fff95691000 -     0x7fff95692fff  libDiagnosticMessagesClient.dylib (100) <4243B6B4-21E9-355B-9C5A-95A216233B96> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff97165000 -     0x7fff97166fff  libsystem_secinit.dylib (20) <32B1A8C6-DC84-3F4F-B8CE-9A52B47C3E6B> /usr/lib/system/libsystem_secinit.dylib
    0x7fff974e7000 -     0x7fff974eeff7  libcompiler_rt.dylib (62) <A13ECF69-F59F-38AE-8609-7B731450FBCD> /usr/lib/system/libcompiler_rt.dylib
    0x7fff97d5b000 -     0x7fff97d5dff7  libsystem_configuration.dylib (802.40.13) <3DEB7DF9-6804-37E1-BC83-0166882FF0FF> /usr/lib/system/libsystem_configuration.dylib
    0x7fff98049000 -     0x7fff98051ffb  libsystem_dnssd.dylib (625.60.4) <80189998-32B0-316C-B5C5-53857486713D> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff98507000 -     0x7fff98508ffb  libSystem.B.dylib (1226.10.1) <012548CD-614D-3AF0-B3B1-676F427D2CD6> /usr/lib/libSystem.B.dylib
    0x7fff9855f000 -     0x7fff98562fff  libsystem_sandbox.dylib (460.60.2) <2A68B39C-B786-3A05-87A2-56E688469FB8> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff98e45000 -     0x7fff98e4aff3  libunwind.dylib (35.3) <F6EB48E5-4D12-359A-AB54-C937FBBE9043> /usr/lib/system/libunwind.dylib
    0x7fff98f0c000 -     0x7fff98f14fff  libsystem_networkextension.dylib (385.40.36) <66095DC7-6539-38F2-95EE-458F15F6D014> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff9974f000 -     0x7fff99753fff  libcache.dylib (75) <9548AAE9-2AB7-3525-9ECE-A2A7C4688447> /usr/lib/system/libcache.dylib
    0x7fff9a50e000 -     0x7fff9a53bfff  libdispatch.dylib (501.40.12) <C7499857-61A5-3D7D-A5EA-65DCC8C3DF92> /usr/lib/system/libdispatch.dylib
    0x7fff9a54c000 -     0x7fff9a563ff7  libsystem_coretls.dylib (83.40.5) <C90DAE38-4082-381C-A185-2A6A8B677628> /usr/lib/system/libsystem_coretls.dylib
    0x7fff9ac3b000 -     0x7fff9ac57ff7  libsystem_malloc.dylib (67.40.1) <5748E8B2-F81C-34C6-8B13-456213127678> /usr/lib/system/libsystem_malloc.dylib
    0x7fff9bbce000 -     0x7fff9bbcfffb  libremovefile.dylib (41) <552EF39E-14D7-363E-9059-4565AC2F894E> /usr/lib/system/libremovefile.dylib
    0x7fff9c7b1000 -     0x7fff9c7b1ff7  libunc.dylib (29) <DDB1E947-C775-33B8-B461-63E5EB698F0E> /usr/lib/system/libunc.dylib
    0x7fff9d9bf000 -     0x7fff9da36feb  libcorecrypto.dylib (335.50.1) <B5C05FD7-A540-345A-87BF-8E41848A3C17> /usr/lib/system/libcorecrypto.dylib
    0x7fff9dafc000 -     0x7fff9db89fef  libsystem_c.dylib (1082.60.1) <28733D22-553E-3CBC-8D2C-EDCEB46E46AF> /usr/lib/system/libsystem_c.dylib
    0x7fff9e297000 -     0x7fff9e29ffff  libcopyfile.dylib (127) <A48637BC-F3F2-34F2-BB68-4C65FD012832> /usr/lib/system/libcopyfile.dylib
    0x7fff9e3ae000 -     0x7fff9e3b3ff7  libmacho.dylib (875.1) <318264FA-58F1-39D8-8285-1F6254EE410E> /usr/lib/system/libmacho.dylib
    0x7fff9e6c7000 -     0x7fff9e6caffb  libdyld.dylib (360.22) <25D28225-99AE-3A04-B98C-ACFF47D6D9B0> /usr/lib/system/libdyld.dylib
    0x7fffa08b9000 -     0x7fffa08e2fff  libsystem_info.dylib (477.50.4) <FAA9226D-64DE-3769-A6D8-6CABA4B7FF4D> /usr/lib/system/libsystem_info.dylib
    0x7fffa08e3000 -     0x7fffa0901ff7  libsystem_kernel.dylib (3248.60.11) <A3F069EA-6A41-35CA-BDF8-187E0209B3E2> /usr/lib/system/libsystem_kernel.dylib
    0x7fffa1c59000 -     0x7fffa1cbfff7  libsystem_network.dylib (583.50.1) <B52DAB73-92DC-3DA7-B9F4-B899D66445C1> /usr/lib/system/libsystem_network.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1142
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 1250328
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=107.1M resident=0K(0%) swapped_out_or_unallocated=107.1M(100%)
Writable regions: Total=379.5M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=379.5M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                  2048K        2 
Kernel Alloc Once                    4K        2 
MALLOC                           366.6M       45 
MALLOC guard page                   16K        4 
STACK GUARD                       56.0M        5 
Stack                             9760K        6 
VM_ALLOCATE                          4K        2 
__DATA                            2824K       43 
__LINKEDIT                        94.2M        4 
__TEXT                            12.9M       43 
shared memory                       12K        4 
===========                     =======  ======= 
TOTAL                            544.0M      149 

Model: MacBookPro12,1, BootROM MBP121.0167.B17, 2 processors, Intel Core i5, 2.7 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5544
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54414C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.21.95.175.1a6)
Bluetooth: Version 4.4.6f1 17910, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0256G, 251 GB
USB Device: USB 3.0 Bus
USB Device: Elements 1042
USB Device: Bluetooth USB Host Controller
USB Device: Keyboard Hub
USB Device: Apple Optical USB Mouse
USB Device: iPhone
USB Device: Apple Keyboard
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by chrmarti** [comment]
The crashed thread appears to be in the cpp extension. Moving there.

**Comment by chrmarti** [comment]
This issue was moved to Microsoft/vscode-cpptools#389
