### ISSUE TITLE
Cannot input anything in the out pannel

### ISSUE THREAD

**Issue by xialvjun** [Microsoft/vscode#16790]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14965
- Extensions:

|Extension|Author|Version|
|---|---|---|
|clojure|avli|0.4.2|
|toml|be5invis|0.0.3|
|vscode-eslint|dbaeumer|1.1.0|
|python|donjayamanne|0.5.5|
|EditorConfig|EditorConfig|0.3.4|
|tslint|eg2|0.7.1|
|vscode-npm|fknop|3.3.0|
|Go|lukehoban|0.6.51|
|partial-diff|ryu1kn|0.2.0|
|RustyCode|saviorisdead|0.19.1|
|Align|steve8708|0.2.0|
|language-stylus|sysoev|1.6.0|
|debug|webfreak|0.14.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.RustyCode command   Cargo run    a project which need input, we cannot input anything in the out panel.

**Comment by alexandrudima** [comment]
Moved to saviorisdead/RustyCode#231
