### ISSUE TITLE
Application Architecture 

### ISSUE THREAD

**Issue by DBJDBJ** [Microsoft/vscode#168]
This is very novel (paradigm shift) architecture for standard Windows desktop software.

Can you please point into the direction of resources explaining the (detailed) App Architecture of VSCODE ?

Kind regards ...

**Comment by Tyriar** [comment]
Sorry about the delay in a response, the only information available on the architecture is captured in the wiki https://github.com/Microsoft/vscode/wiki/Code-Organization
