### ISSUE TITLE
**To verify**: Markdown preview refresh not available when CSS editor has focus.

### ISSUE THREAD

**Issue by gmccullo** [microsoft/vscode#168031]
**To verify**:
1. In a workspace with a markdown file, create a `style.css` file that sets the background color:

```css
body {
    background: hotpink !important;
}
```

1. Set `"markdown.styles": [ "./style.css" ]` 
1. Open the markdown preview to the side
1. With the preview still open, edit the css file in the other panel to change the background color.
1. Verify that the refresh command updates the preview. `Refresh` should be both in the command palette and in the `...` in the preview's status bar

_Originally posted by @mjbvz in https://github.com/microsoft/vscode/issues/32111#issuecomment-320839659_

**Comment by mjbvz** [comment]
Closing as this seems copy pasted without any context

**Comment by gmccullo** [comment]
The context is that the referenced issue cannot be commented on and the functionality described doesn't work. I suspect it's a regression.
