### ISSUE TITLE
If debug session is active all non-debug hovers are disabled

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16804]
- VSCode Version: 1.8.0 (Insiders)

Steps to Reproduce:

- use a deprecated attribute in a launch.json, e.g. `externalConsole`
- hover over the value: you will see a hover explaining the deprecation
- start debug session
- hover over the deprecated attribute value: no hover shows up

We should try to only disable regular hovers in files that are actually 'in scope' of the debug session.

**Comment by roblourens** [comment]
I don't see the problem repro in 1.8.1 - I still see the hover in launch.json while debugging.

**Comment by ramya-rao-a** [comment]
I can repro in 1.8.1 and confirm that it works in 1.9 insiders
