### ISSUE TITLE
There is constant error that VS Code can not read file csharp-o

### ISSUE THREAD

**Issue by Nedilko** [Microsoft/vscode#1680]
[c:/Program Files (x86)/Microsoft VS Code/resources/app/extensions/csharp-o]: Cannot read file c:/Program Files (x86)/Microsoft VS Code/resources/a

**Comment by bpasero** [comment]
@Nedilko can you try to delete the Microsoft VS Code folder and reinstall fresh to see if that fixes the issue?

**Comment by Nedilko** [comment]
yes, working. All I was need to do is to reinstall VS Code
