### ISSUE TITLE
Inconsistent tsx highlighting 

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#16806]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.10.1|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|auto-close-tag|formulahendry|0.3.6|
|auto-rename-tag|formulahendry|0.0.8|
|contextualduplicate|lafe|0.2.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|stylelint|shinnn|0.20.4|

---

Steps to Reproduce:

1. Create tsx file
```tsx
export class Component {
    render() {
        const a = true
        return (
            <div>
                {a === true
                    ? <span disabled={a}>{a}</span>
                    : <span disabled={a}>{a}</span>}
            </div>
        )
    }
}
```
2. Conditional expression is not highlighted correctly
![bug](https://cloud.githubusercontent.com/assets/1114090/20964969/dea81620-bc84-11e6-834e-1c94e38c4269.png)

**Comment by aeschli** [comment]
This seem to be fixed with the latest grammar (for the January build)
