### ISSUE TITLE
Display the edit icon in settings with a small delay

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16802]
Currently if you move the mouse fastly around the settings the icon apperas everywhere franticly. I would show it with a slight delay to make the experience smoother.
The gif does not illustrate well the franticness but you see what I am trying to point out :)

![settingsfrantic](https://cloud.githubusercontent.com/assets/1926584/20964331/62b72ce4-bc71-11e6-9ff9-714d337a5fcd.gif)

**Comment by sandy081** [comment]
Currently this icon is shown by using editor decorations. I think editor contributions do not have control on how to display these. So one way is to move away from decorations to zone widgets or overlay widgets where we can do things like suggested.

Thanks.
