### ISSUE TITLE
gulp-tsb warning while npm installing

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16808]
I get the following warning when running `./scripts/npm.sh install`:

```
npm WARN gulp-tsb@2.0.3 requires a peer of typescript@^2.0.10 but none was installed.
```

AFAIK `typescript@2.0.10` will break our formatter: #14519.

But if `gulp-tsb@2.0.3` really requires `typescript@2.0.10` and we are not installing it... then couldn't `gulp-tsb` break?

**Comment by dbaeumer** [comment]
gulp-tsb can still work with TS 2.0.3. I could relax the dependency in gulp-tsb however since we are switching to TS 2.1.x soon it might not be worth the effort.

**Comment by dbaeumer** [comment]
Actually dups https://github.com/Microsoft/vscode/issues/16292 :-)

**Comment by joaomoreno** [comment]
Oops! 😮
