### ISSUE TITLE
[feature] Show the "name" or the top attribute of a JSON schema when folded in `CMakePresets.json`.

### ISSUE THREAD

**Issue by hwhsu1231** [microsoft/vscode#168028]
### Feature Request

Show the "name" or the top attribute of a JSON schema when folded in `CMakePresets.json`. Take **CLion 2022.3** for reference.

* Example: [CMakePresets.zip](https://github.com/microsoft/vscode/files/10148621/CMakePresets.zip)

### Version

* **VSCode:** `1.73.1`

### Screenshots

![image](https://user-images.githubusercontent.com/71438617/205494023-dd9c8139-748b-4723-a9ee-a1a4f3707a9f.png)

**Comment by aeschli** [comment]
Depends on https://github.com/microsoft/vscode/issues/70794, marked as dup.
