### ISSUE TITLE
Debugger stops working after slight changes

### ISSUE THREAD

**Issue by tasruMLT** [microsoft/vscode#168073]
Type: <b>Bug</b>

Upon launching the debugger recognises all syntax and matches the colour scheme for the different parts of the code (e.g variables commands etc).

After doing even the slightest code change (e.g. just pressing enter) most of the code will end up white and with nonsense errors. I wouldn’t even be able to go to function through the option ‘Go to Declaration”

The only way to recover the colour scheme but not the functionality is to close and open visual studio code but again there is no proper functionality as code suggestion doesn’t work after doing changes.

I haven’t found a workaround as yet but the code executes correctly even with the reported issues.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (2.81GB free)|
|Process Argv|--crash-reporter-id 0d6746e0-273c-48f9-997c-eea96ef64edd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (33)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gc-excelviewer|Gra|4.2.56
github-repository-manager|hen|1.6.0
vsc-python-indent|Kev|1.18.0
azure-dev|ms-|0.3.0
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-azurestorage|ms-|0.15.0
vscode-azurevirtualmachines|ms-|0.6.2
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.23.1
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.40
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
azure-account|ms-|0.11.2
vscode-node-azure-pack|ms-|1.1.1
autodocstring|njp|0.6.1
vscode-yaml|red|1.10.1
sourcery|sou|1.0.1
tabnine-vscode|Tab|3.6.31
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
jinja|who|0.0.8

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by roblourens** [comment]
What language?

Does it happen if you run the command "Disable all installed extensions" and reload?

**Comment by tasruMLT** [comment]
I am using Python.

After submitting this bug I closed all tabs and closed vs code and reopened and now even after doing changes to the code the colour scheme is retained and also debugger is working fine. 

That doesn't mean that issue was resolved but it is going to make it more difficult for me to replicate the issue in case more info is required.

**Comment by roblourens** [comment]
This is likely an issue with the python extension, and you can file an issue on their repo. But first you can verify that with the "Start extension bisect" command
