### ISSUE TITLE
Settings: edit action seems to be in my way often

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16800]
I do like that we have an action but I find that it is in my way often when editing the right hand side. In other words it is hard to click at the end of a line:

![screen shot 2016-12-07 at 11 19 43](https://cloud.githubusercontent.com/assets/900690/20963786/2a16d666-bc6f-11e6-91d9-a40609013fa4.png)

I am not sure if this is planned but wasn't the idea once to show the action to the left?

**Comment by sandy081** [comment]
Duplicates #16457 

Placing action on the left was a stretch goal.
