### ISSUE TITLE
Impossibile to compile and run C++ on MacOS M1 Pro Apple Silicon. HELP.

### ISSUE THREAD

**Issue by Sladerix** [microsoft/vscode#168022]
Hi everyone I've a MacBook Pro with M1 Pro 
I download Visual Studio Code and did not turn on "Sync Settings" etc.. SO it is a fresh and clean install of VSC.
(I always used it before on a Intel one, never had problems)

Now... I wanted to create a C++ class on multiple files (.cpp and .hpp) and use it in a main.cpp file.

When I try to run the main.cpp file it fails compiling giving this error:

```
Undefined symbols for architecture arm64:
  "TalkToSPI::showDevices()", referenced from:
      setup() in main-c43bb7.o
  "TalkToSPI::removeDevice(int)", referenced from:
      setup() in main-c43bb7.o
  "TalkToSPI::talkTo(int)", referenced from:
      setup() in main-c43bb7.o
  "TalkToSPI::addDevice(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, int)", referenced from:
      setup() in main-c43bb7.o
  "TalkToSPI::TalkToSPI()", referenced from:
      setup() in main-c43bb7.o
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Same thing if I try to compile it manually from the Terminal using both g++ or clang++ 

Guys... I really don't understand what is wrong, I'm going crazy for this simple thing I can't compile/run...

What I do is to:
1. Open the project folder with VSC 
2. Open the main.cpp file 
3. Click the "play" button in the up right corner of VSC

I attach a .zip file containing all the files.
Can you try and tell me if it works for you? I'm not quite understanding what is problem.
[TalkToSPI.zip](https://github.com/microsoft/vscode/files/10148287/TalkToSPI.zip)

Thank you in advance

(P.s. I tried to run the code on Xcode and it works... so the machine is capable and the code should be correct)

**Comment by deepak1556** [comment]
> Same thing if I try to compile it manually from the Terminal using both g++ or clang++

If you are seeing the compile errors outside VSCode then it is not related to the application. It is hard for us to debug an external project, if you think the issue is with VSCode please provide isolated minimal repro steps. Thanks!
