### ISSUE TITLE
Title doesn't refresh when we jump into other tabs

### ISSUE THREAD

**Issue by sharathgg5** [Microsoft/vscode#16805]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|angular2-snippets|danwahlin|1.0.5|

---

Steps to Reproduce:

1. open a file you can see application name prefixed with current open file name in Title field of VS code.
2. open another file. Title doesn't refreshes with  current opened file name.
3. jump to another window and return back name title will be refreshed.

**Comment by sharathgg5** [comment]
title name doesn't refresh.

**Comment by bpasero** [comment]
I think this is https://github.com/Microsoft/vscode/issues/14244

**Comment by bpasero** [comment]
@sharathgg5 how are you opening "another file"?

**Comment by sharathgg5** [comment]
Open one file , then open another file in vs code... Title doesn't get
refresh ....

**Comment by sharathgg5** [comment]
Imagine a project is loaded with multi files in it...

**Comment by bpasero** [comment]
@sharathgg5 but do you just click between tabs to change files or using File menu to open?

**Comment by sharathgg5** [comment]
![image](https://cloud.githubusercontent.com/assets/12963683/21004306/e8b5c45e-bd2f-11e6-9ea9-0607f54c103c.png)

**Comment by bpasero** [comment]
@sharathgg5 thanks, this is very weird indeed. do you see something in the developer console output (help > toggle developer tools > console)?

When you are inside the developer tools console and you type "`window.document.title = 'test'`", does it show "test" in the title?

**Comment by sharathgg5** [comment]
No it doesn't change the title as well. other thing i noticed is title will be refreshed when toggle windows

**Comment by bpasero** [comment]
Ok thanks for trying 👍
