### ISSUE TITLE
inconsistent highlighting after method

### ISSUE THREAD

**Issue by anvish** [Microsoft/vscode#16801]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-file-peek|abierbaum|1.0.1|
|Bookmarks|alefragnani|0.10.1|
|path-intellisense|christian-kohler|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|auto-close-tag|formulahendry|0.3.6|
|auto-rename-tag|formulahendry|0.0.8|
|contextualduplicate|lafe|0.2.0|
|vscode-stylefmt|mrmlnc|2.2.0|
|debugger-for-chrome|msjsdiag|2.3.2|
|stylelint|shinnn|0.20.4|

---

Steps to Reproduce:

1. Create typescript file
```ts
interface A {
    prop1: string
    prop2: string
    method1(): void
    prop3: string
    prop4: string
}
```
2. Properties after a method are not highlighted

![bug](https://cloud.githubusercontent.com/assets/1114090/20963982/bd265ccc-bc80-11e6-8568-ec1377c835b4.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#379
