### ISSUE TITLE
PR: refactor telemetry to work with web-modules 

### ISSUE THREAD

**Issue by lemanschik** [microsoft/vscode#168005]
On the web there is no nodejs so you need to adopt patterns from the advertisement api which is a effort to allow anonymous telemetry and user tracking. It will collect data and only partial sync it from time to time writing down the whole spec is not needed as i need to implement that as always my self. This only informs others when there is some one who wants to take on that refactoring i can always delegate that task would be in fact a big help to not maintain this telemetry implementation. 

# Blocking Part of: 
- [x] https://github.com/microsoft/vscode/issues/167505
- [ ] https://github.com/lemanschik/src_github_microsoft_vscode/issues/2

## Will go to iterate faster with no telemetry!
This is only  low priority for my self as users do not need telemetry to code. 
- [ ] https://github.com/VSCodium/vscodium/issues/1345 merging in https://github.com/microsoft/vscode/issues/167505

# specs and so: 
- https://privacysandbox.com/
- https://blog.google/products/chrome/get-know-new-topics-api-privacy-sandbox/

its called topics and privacy sandbox. 

## Enable it Access it use it now
below posted link shows you how to access that feature today in your current browser and yes sure we have userland implementations also for that. So it is not blocked this is only a trial to not force every one into it directly. But that will happen. 
- https://developer.chrome.com/docs/privacy-sandbox/unified-origin-trial/

Shared Storage’s selectURL API will be [joining the origin trial](https://groups.google.com/a/chromium.org/g/blink-dev/c/Vi-Rj37aZLs/m/wXlBwB_UAQAJ) at 1% of Chrome Stable traffic from November 9th. As previously announced in the [Increasing the Privacy Sandbox Relevance and Measurement origin trial to 5%](https://developer.chrome.com/blog/privacy-sandbox-origin-trial-increase/) blog post, Attribution Reporting and Topics are now at 5% with FLEDGE and Fenced Frames also following on November 9th.

the strategie overall is to soft force people into that now in Jan we reach around 10% Web Scale.

**Comment by alexdima** [comment]
Please see https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests for guidelines for writing good bug reports and feature requests.
