### ISSUE TITLE
allow to set a default starter .ps1 file

### ISSUE THREAD

**Issue by damnmso** [microsoft/vscode#168055]
Type: <b>Feature Request</b>

I have a powershell project containing about 10 files. 1 .ps1 and 9 .psm1. whenever i hit the "run" button, i want to have vscode start the .ps1 and not the .psm1 - starting a .psm1 makes absolutely no sense. intellij and others have per-project "start"-files which act as entry point when the application starts. i am highly missing something like that.

unfortunately, seems like vscode is also broken when creating new feature requests, as only half the text was copied from vscode -> issue -> feature request, so guess parts of information are also missing (e.g. vscode version etc.) 

Version: 1.73.1 (user setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T04:27:29.066Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by chrmarti** [comment]
This is likely an issue with the Powershell extension you are using. Please file an issue with them. Thanks!
