### ISSUE TITLE
Unicode highlight: Non-breaking space not highlighted

### ISSUE THREAD

**Issue by veloek** [microsoft/vscode#168068]
Non-breaking space is not highlighted when it should've been.

The character 'å' is a common letter in the Norwegian alphabet and can also be used as a word. The phrase "for å gi et eksempel" (which means "to give an example") is an example of this. A non-breaking space after the word 'å' is not highlighted by vscode as can be seen in the screenshot where all spaces are non-breaking spaces (U+00A0):

![image](https://user-images.githubusercontent.com/1660659/205630244-11d19c5f-11bf-43e3-abd5-e6f6c791be93.png)

I'm guessing this is a regression introduced by #140960. I see the reason for why it's behaving like this, but it would be nice if it was possible to make it work in both scenarios.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: macOS 13.0.1

Steps to Reproduce:

1. Configure vscode with `"editor.unicodeHighlight.allowedCharacters": { "å": true }`
2. Test with this example text: "For å gi et eksempel"
3. Verify that a non-breaking space after 'å' is not highlighted

**Comment by hediet** [comment]
Thanks! The bugfix should be available soon in VS Code Insiders.
It would be awesome if you could verify the bugfix!

**Comment by veloek** [comment]
@hediet It's working fine now in vscode-insiders, sweet! Thanks again 🙂
