### ISSUE TITLE
Outline collapse setting does not persist when focusing on split views of the same file

### ISSUE THREAD

**Issue by tonyjly** [microsoft/vscode#168037]
VS Code Version: 1.73.1
Host OS Version: Windows 10 Enterprise 20H2
Remote OS Version: Ubuntu 20.04.3 LTS

Steps to Reproduce:

1. Open a notebook file
2. Change setting: `"outline.collapseItems": "alwaysExpand"`
4. Click on _Expand All_ in the Outline section
5. Click on _Split Editor Right_
6. Focus window on the (newer) right-side of split view
7. Observe outline automatically collapses
8. Focus window back on the (original) left-side of split view
9. Observe outline automatically collapses
10. Alternating views repeatedly continues to show outline view always collapsed, despite `alwaysExpand` setting

Expect switching between tabs of the same notebook file in split view to follow the last collapse/expand state.

**Comment by TylerLeonhardt** [comment]
@jrieken is it expected that if I:
* Open the Notebook (Outline is expanded) 
* change the setting to `alwaysCollapse`
* Click the Notebook tab to show it

Then the Outline is still expanded. Is that expected?

**Comment by jrieken** [comment]
Yeah, in response the settings change I didn't want to undo the current state but only apply it to future states
