### ISSUE TITLE
Breakpoints and Source maps appear broken

### ISSUE THREAD

**Issue by bobbytreed** [microsoft/vscode#168076]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74 (Latest)
- OS Version: Windows 11

Steps to Reproduce:

1.  Set breakpoint in typescript file and start debugging with extension host.
2.  Breakpoint does not hit.

I initially thought I was doing something wrong (which is still possible), but I made no relevant code changes (launch.json, tsconfig.json, webpack config, package.json, etc.).  The breakpoints also DO hit in vs code (not insiders).  The problem also started this morning.

**Comment by bobbytreed** [comment]
https://microsoft-my.sharepoint.com/:u:/p/robreed/EVfLdfk6UT9CqUGKHA68IWMBvp5uVchsiT0AWfVMzKESeA?e=X2zyh8

The code also not does not allow closing with stop button.
![image](https://user-images.githubusercontent.com/10874547/206202824-93647882-6df6-4461-ba9a-a381e66a1ac6.png)
I also get a lot of these entries in debug log 
![image](https://user-images.githubusercontent.com/10874547/206202914-3fac8b32-3847-40aa-b432-9bee54c1e3cb.png)

It's certainly possible that I'm doing something incorrectly, but it's odd that...

- I made no changes to the config files before the issue started occurring.
- The issue does not show up in VS Code.
- The issue started randomly one morning after Insiders updated.

Thank you

**Comment by connor4312** [comment]
Thanks for the update! I believe this may be the same issue seen in https://github.com/microsoft/vscode-js-debug/issues/1469. You can either swap to the new [nightly js-debug](https://github.com/microsoft/vscode-js-debug#nightly-extension) now, or wait for the next Insiders build to come out later today which will also have the fix. Please let me know if that works for you.

**Comment by theIDinside** [comment]
This should be a pretty urgent problem. It has halted extension development, dead in it's tracks on Linux. It has become utterly impossible to continue development, in my case on a debug adapter.

**Comment by connor4312** [comment]
Closing since I have not heard from the author. 

> This should be a pretty urgent problem. 

That's why the linked bug is marked as a candidate 🙂
