### ISSUE TITLE
Command generated by launch.json is missing --inspect-brk

### ISSUE THREAD

**Issue by rdmolony** [microsoft/vscode#168029]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Windows_NT x64 10.0.22621 | Windows Subsystem for Linux 2, Ubuntu, Kernel version: 5.10.102.1

Steps to Reproduce:

1. Add a `launch.json` as per the [official `Jest` documentation](https://jestjs.io/docs/29.2/troubleshooting#debugging-in-vs-code)
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Debug Jest Tests",
      "type": "node",
      "request": "launch",
      "runtimeArgs": [
        "--inspect-brk",
        "${workspaceRoot}/node_modules/.bin/jest",
        "--runInBand"
      ],
      "console": "integratedTerminal",
      "internalConsoleOptions": "neverOpen"
    }
  ]
}
```

2. Run `Debug Jest Tests` via `Debugger`

---

A command is generated that is missing `--inspect-brk`, we should see `/home/rdmolony/.nix-profile/bin/node --inspect-brk /home/rdmolony/code/combine-obsidianmd-tils-into-readme/node_modules/.bin/jest --runInBand` instead of `/home/rdmolony/.nix-profile/bin/node /home/rdmolony/code/combine-obsidianmd-tils-into-readme/node_modules/.bin/jest --runInBand`

```sh
❯  /usr/bin/env 'NODE_OPTIONS=--require /home/rdmolony/.vscode-server/bin/6261075646f055b99068d3688932416f2346dd3b/extensions/ms-vscode.js-debug/src/bootloader.bundle.js --inspect-publish-uid=http' 'VSCODE_INSPECTOR_OPTIONS={"inspectorIpc":"/tmp/node-cdp.29642-1.sock","deferredMode":false,"waitForDebugger":"","execPath":"/home/rdmolony/.nix-profile/bin/node","onlyEntrypoint":false,"autoAttachMode":"always","mandatePortTracking":true,"fileCallback":"/tmp/node-debug-callback-00e06826bbc57cbc"}' /home/rdmolony/.nix-profile/bin/node /home/rdmolony/code/combine-obsidianmd-tils-into-readme/node_modules/.bin/jest --runInBand
```

If I manually edit the above command to add `--inspect-brk` we get the expected behaviour

**Comment by connor4312** [comment]
`--inspect-brk` is intentionally removed and as it is no longer necessary and will prevent the debugger from working if present.

**Comment by rdmolony** [comment]
Thanks @connor4312 what would you recommend as alternative behaviour? In this case it seems the Jest docs are out of date (I'm happy to propose a suggestion to Jest)

In this case I was trying to call devenv to launch a the debugger within a nix environment (https://devenv.sh/), specifically to run ...

devenv shell node --debug-brk jest ...

**Comment by connor4312** [comment]
If you actually _do_ need the listening behavior of `--inspect` or `--inspect-brk`, you can specify an option `attachSimplePort` to have the debugger try to connect to a port traditionally instead of using the bootloader in the NODE_OPTIONS. If this is present, `--inspect/-brk` flags will not be sanitized from the runtime arguments.

The Jest docs could be simplified to remove that argument. It doesn't hurt at the moment, it's just a no-op.

**Comment by rdmolony** [comment]
I imagine setting up a virtual environment like nodeenv before launching a debugger faces the same problem

**Comment by rdmolony** [comment]
Thanks @connor4312 😉
