### ISSUE TITLE
Extensions want to make the following changes to the terminal's environment: VSCODE_GIT_IPC_HANDLE=\.\pipe\vscode-git-285b3099df-sock

### ISSUE THREAD

**Issue by HJLBX** [microsoft/vscode#168034]
Type: <b>Bug</b>

Install pwsh
Set Terminal default = pwsh (but same error happens with other PowerShell interpreters)
Install Git
Launch Terminal
(Intermittently - sometimes the triangle appears sometimes it does not) a triangle with an exclamation mark appears in the terminal. Hovering the cursor over it shows an error box stating:

"Extensions want to make the following changes to the terminal's environment:
VSCODE_GIT_IPC_HANDLE=\.\pipe\vscode-git-285b3099df-sock"

The above pipe is for GIT authentication.

To fix the issue the user must relaunch the Terminal every single time.

**This is a really annoying UX issue that was reported multiple times previously back in 2020 but it has never been fixed. Why intergrate Git into VS Code but never fix the issues which have been repeatedly reported?**

https://github.com/microsoft/vscode/issues/168034
https://github.com/microsoft/vscode/issues/102727

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HS with Radeon Graphics         (16 x 3294)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.41GB (7.48GB free)|
|Process Argv|--crash-reporter-id b0ec225f-2d19-4e12-a110-84d08c442ee8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-dotnet-runtime|ms-|1.6.0
powershell|ms-|2022.11.0
gistfs|vsl|0.4.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380

```

</details>

**Comment by Tyriar** [comment]
The terminal actually relaunches silently if it's safe to do so, if it's not safe (ie. potential data loss) we don't do it. There's nothing more we can do here afaict.
