### ISSUE TITLE
PR: Replace yazul and the zip support with engine methods drop the dependencie on it

### ISSUE THREAD

**Issue by lemanschik** [microsoft/vscode#168018]
as part of the web-modules transformation we need to make sure that the extensions do not depend any more on nodejs only stuff like the current zip integration

this pr will replace it with native platform methods. 

part of:
- [x] https://github.com/microsoft/vscode/issues/167505

**Comment by alexdima** [comment]
Please see https://github.com/microsoft/vscode/blob/main/CONTRIBUTING.md#writing-good-bug-reports-and-feature-requests for guidelines for writing good bug reports and feature requests.
