### ISSUE TITLE
javascript optional chaining operator auto save issue

### ISSUE THREAD

**Issue by parthapaul7** [microsoft/vscode#168027]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.73.1
- OS Version:  ubuntu 22.04

Steps to Reproduce:

1.  create a JS file 
2.  try to access an object with the optional chining ( ?.) and save the file
3.  it automatically formats the line with space as `const aMaybe = obj ? .a;`

![image](https://user-images.githubusercontent.com/83518670/205492443-fcc47c14-d8fd-4aaa-a6a0-c38a3e9e9d9b.png)

This happens without any extension and auto-formatting enable 
I could not able to turn off this auto-formatting on file saving.  
This issue occurs only on the ubuntu version. windows version is working fine

**Comment by mjbvz** [comment]
Are you sure you disabled all extensions and then restarted VS Code. This is almost certainly not caused by VS Code itself (unless you are using an ancient TypeScript version)

**Comment by mjbvz** [comment]
Without evidence, this does not sounds like an issue with VS Code. We've been using optional chaining in the VS Code base for years now without issue
