### ISSUE TITLE
Go to references vs implentations when clicking function in interface

### ISSUE THREAD

**Issue by walles** [microsoft/vscode#168030]
I'm on a mac, using VSCode 1.73.1.

Scroll down for a screenshot of the test code with line numbers.

* Open [the attached Go program](https://github.com/microsoft/vscode/files/10148966/interface-example.go.txt) in VSCode
* Hold down <kbd>cmd</kbd> / <kbd>⌘</kbd> key and left click the `area` word on line 8, in the interface declaration.

This usually does the wrong thing for me and I get to the wrong place. Then I have to navigate back, right click and manually pick "Go to Implementations" instead. Read on for details!

# Current result

You jump to where this function is called from, line 21.

# Expected result

Since there are hits both for...
* Going to implementations (line 15)
* Going to references (line 21)
... I'd like to get a popup menu where I can choose between:
* Go to Implementations
* Go to References

Clicking "Go to Implementations" should work just like if I had right clicked `area` and picked "Go to Implementations".

Clicking "Go to References" should work just like if I had right clicked `area` and picked "Go to References".

# Code

Use [the attached text version of the below code](https://github.com/microsoft/vscode/files/10148966/interface-example.go.txt) for trying this yourselves.

<img width="520" alt="interface-example" src="https://user-images.githubusercontent.com/158201/205501801-748ae070-664a-45f0-bb38-635b166dbbfc.png">

**Comment by jrieken** [comment]
> cmd / ⌘ key and left click

That performs the go to definition command, which falls back to finding references when on the definition. You can use the `editor.gotoLocation.alternativeDefinitionCommand` to configure the fallback. There is also an issue to configure what cmd+click will actually do. 

closing this as question and/or duplicate
