### ISSUE TITLE
Content of debug console not readable enough when in vertical layout

### ISSUE THREAD

**Issue by top-kat** [microsoft/vscode#168033]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/17770809/205510344-258aaf02-4b6b-4bab-ad81-5b541d66d2eb.png">

Hi, 

like visible on the screenshot, **more than half of the terminal width in vertical mode is taken to display the path of the file where the log originated**.

* I think this is not relevant to many of us since the path will point to the logger file
* At some point it gets really hard to read the logs

Just to have an option to display path in cli would be enought for me.

My screen resolution is 3072x1920 and my zoom level is -0.5 (at 0 it is even worst)

**Comment by roblourens** [comment]
This has always been a bit off- I think only showing the file name would be sufficient

**Comment by cawoodm** [comment]
To be honest, who even needs the filename? When debugging I know what my console.log messages mean and where they are generated. If I don't, a simple clickable elipsis `...` will save space and perform the same function by bringing me directly to the line of code.
