### ISSUE TITLE
Inconsistent completions in debugger

### ISSUE THREAD

**Issue by talks2much** [microsoft/vscode#168021]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0-insider
- OS Version: macOS

Steps to Reproduce:

1. Create file test.mjs:
```js
let data = {
    foo: 5,
    bar: 0,
}
```
3. Add breakpoint to the end of file, run `node test.mjs` in `Debug: JavaScript Debug Terminal`
4. Open and write `data.foo` in *Debug Console*

Completions when triggered after `.` are good, otherwise not shown.

Expected (triggered after `.`):
<img width="300" alt="Screenshot 2022-12-04 at 13 04 46" src="https://user-images.githubusercontent.com/78976241/205484865-966d8efd-0a48-49d3-b1fa-d9d9c2b50f05.png">

Actual (triggered after `foo`):
<img width="300" alt="Screenshot 2022-12-04 at 13 02 22" src="https://user-images.githubusercontent.com/78976241/205484797-cb75db12-ae70-445e-9fa2-b6deaccaf741.png">

It's really hard to use debugger sometimes as it gives false completions.

**Comment by talks2much** [comment]
Tried to debug this and it seems to be [problem](https://github.com/microsoft/vscode-js-debug/blob/4d2a78523b82ba434506469918732b0df622da53/src/adapter/completions.ts#L147) with node debug adapter. Also why extension cannot participate in giving completion items for debug repl editor?

**Comment by roblourens** [comment]
omg yes thank you @zardoy

**Comment by zardoy** [comment]
Thank you for verifying! Also, I would highly appreciate if you could look into https://github.com/microsoft/vscode/pull/187727 @roblourens 😄
