### ISSUE TITLE
"Submit a bug" button not responding

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#16817]
![image](https://cloud.githubusercontent.com/assets/8189808/20969287/a0636758-bc88-11e6-8f6d-eab6bb311c07.png)

![image](https://cloud.githubusercontent.com/assets/8189808/20969248/7ff69706-bc88-11e6-93c4-db3a09872d61.png)

1. Clicking on the Smile in the lower right corner
2. Clicking Submit a bug, nothing happens

**Comment by joaomoreno** [comment]
Very likely #16815, since I can't repro.
