### ISSUE TITLE
merge 'files.excludes'?

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16810]
Testing #16515:

- Create a new extension (Typescript) with yo code
- have
```typescript
import * as vscode from 'vscode';
function logKey(key: string) {
    let meta = vscode.workspace.getConfiguration().inspect(key);
    if (!meta) {
        os.appendLine('no meta info for '  + key);
    } else {
        os.appendLine(`key: ${meta.key}, def: ${JSON.stringify(meta.defaultValue)}, global: ${JSON.stringify(meta.globalValue)}, ws: ${JSON.stringify(meta.workspaceValue)}`);
    }
}
export function activate(context: vscode.ExtensionContext) {
    logKey('files.excludes');
}
```

- result in `no meta info for files.excludes`. 
Should show defaults and the workspace settings.

**Comment by aeschli** [comment]
Hmm, sorry, my fault. It's 'files.exclude'. That works.

**Comment by aeschli** [comment]
files.exclude, def: {"**/.git":true,"**/.svn":true,"**/.hg":true,"**/.DS_Store":true}, global: undefined, ws: {"out":false}

I wonder however if the ws setting shouldn't be a merge of ws and def

**Comment by jrieken** [comment]
Leaving this up to @bpasero

**Comment by aeschli** [comment]
I now think what we currently have is correct. One needs to know exactly what is in the workspace settings in order to make a change. The merged value can always be accessed through the value map.
