### ISSUE TITLE
Feature Request: Make output console log to disk

### ISSUE THREAD

**Issue by ghost** [Microsoft/vscode#16816]
It would be great if we were able to log the output of the output console to disk, for example if you log the tsserver in verbose mode to find latency issues while working or errors.

**Comment by siegebell** [comment]
Sometimes a user of my extension wants to output something that is multiple megabytes long; the output currently gets truncated. They need the ability to log such output to a file.

I could implement this manually, but the scenario does not happen often so it's low priority for me. Anyhow, it would be nice to not have multiple extensions reimplementing such a basic feature.

**Comment by mjbvz** [comment]
Extension output logs are now backed by on disk files. Additionally, extensions can write logs to `ExtensionContext.logPath`
