### ISSUE TITLE
VS Code Codespace: Run yarn / watch on init

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#168172]
Can we configure the codespace for the VS Code repo to run `yarn` and the watch task automatically?

When I create a codespace, `node_modules` seems to be there, but when I run `yarn`, I get this:

![image](https://user-images.githubusercontent.com/2931520/205930895-41f12533-3604-455a-aa85-293a26344426.png)

I would expect it to say that everything is already up to date.

**Comment by joaomoreno** [comment]
@chrmarti Unsure if you own this.

**Comment by chrmarti** [comment]
We now run `yarn` after creating the container. If `yarn watch` makes sense depends more on what you want to do at the time. Closing for now.
