### ISSUE TITLE
API to iterate over all keys

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode#16811]
Testing #16515:

IMO it would be good to have API that returns all currently defined (qualified) keys (from the default settings)

This currently can only be done by iterating through the configuration value tree. This is however will not work for properties like "files.exclude" that have an object as value.

**Comment by jrieken** [comment]
Yeah - sometimes I wonder if should even have an list of key/value pairs. Maybe even instead of the new reflect API... Like `configurations: Entry[]` with `type Entry = [string, Value]`
