### ISSUE TITLE
Fuzzy search icon is visible in Go to Symbol view

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#168199]
Type: <b>Bug</b>

Fuzzy search icon is visible in Go to Symbol view (Shift + CMD + O) which on press opens terminal recent search with fuzzy search. I think that button should be excluded from Go to Symbol view and be visible only in terminal recent search view.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:22:48.959Z)
OS version: Darwin arm64 22.1.0

### Go to Symbol view

<img width="607" alt="image" src="https://user-images.githubusercontent.com/10441177/205990523-f0141663-7dbd-4d56-8da3-5e479e7dab17.png">

### Terminal run recent command view

<img width="597" alt="image" src="https://user-images.githubusercontent.com/10441177/205990700-9f64ed16-ec94-49c8-bc78-8f9e82d8c82f.png">

**Comment by lramos15** [comment]
Seems like after `Terminal Run Recent Command` the icon is not cleared and shows up in any command palette entry
