### ISSUE TITLE
Syntax highlighting is broken for handlebars comments

### ISSUE THREAD

**Issue by tonyobanon** [microsoft/vscode#168179]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: Darwin x64 21.6.0

Steps to Reproduce:

1. Create a file called helloworld.hbs and paste this there: {{!-- outer comment {{!-- inner comment --}} {{hello --}}
Below is what you see on the screen.
![index view — project_panther_fe 2022-12-06 16-34-05](https://user-images.githubusercontent.com/12859467/205955142-198df9f1-d0f5-4431-bd92-2f0a02bb3370.png)

2. Visit https://handlebarsjs.com/playground.html and in the template section, also paste the above string. Then open your browser console, you will notice compile errors.
Below is what you see on the screen.
![Handlebars 2022-12-06 16-31-51](https://user-images.githubusercontent.com/12859467/205955427-7d74d0cc-a061-4fcb-aa04-72d58f7073d9.png)

According to the the handlebars parser (also as you can see in the handlebars playground as well), the first "--}}" encountered terminates the comment. But VS Code tricks the developer into thinking that the comment is only terminated after the last "--}}". This will lead to errors and a poor experience

**Comment by alexr00** [comment]
Moved to upstream repo: https://github.com/textmate/html.tmbundle/issues/123

It looks like there haven't been changes then in quite a while though. We might consider changing to a different handlebars grammar.
