### ISSUE TITLE
Allow 'Developer: Generate Color Theme From Current Settings' > 'workbench.action.generateColorTheme' from within extensions

### ISSUE THREAD

**Issue by jeremymwells** [microsoft/vscode#168190]
Extension authoring doesn't expose many texteditor display behaviors (ie rows vs columns and so on). 

In order to implement custom text editor-like interactions, authors must implement behaviors in a webview panel, and to preserve the feeling of an in-app editor experience, its reasonable to use an instance of the monaco editor.

Look and feel become an issue, as there is no way to ensure seamless style without painstakingly enumerating all the --vscode-* css vars and translating those styles through to the embedded monaco editor within the web-panel.

A user can run the `Developer: Generate Color Theme From Current Settings` command, which spits out all the requisite styles needed; however, when running that command from within the context of an extension, programmatically, the result is null/undefined.

If this command worked, those styles could be translated more easily.

**Comment by aeschli** [comment]
Closing as we have no plans to change the `Developer: Generate Color Theme From Current Settings` command to be used programmatically

**Comment by jeremymwells** [comment]
What of the color API you mention? Is that on roadmap, or is there anything like it that will allow extension authors to get active colors from the editor and recreate them in an embedded monaco editor?

**Comment by aeschli** [comment]
I don't know what's the recommended way to embed a Monaco editor in a web view (or whether this is a good idea at all). Maybe @mjbvz or can give some insights.
If enumerating all colors is a needed part of it, we can investigate into a new API like `getThemeColors()`. We don't have such an API yet (and also no request for it), wo we would need an issue for it.

**Comment by jeremymwells** [comment]
That's what my feature request is asking for. I assumed since the 'generate color theme` command was already available, making it available programmatically would be the lowest hanging fruit, but ultimately, I'd like to be able to ask vscode what its current theme is, or more specifically, what the texteditor colors are.
