### ISSUE TITLE
View: Rename View Menu Item

### ISSUE THREAD

**Issue by seanmcbreen** [Microsoft/vscode#16818]
Testing #16783 

Should we name the context menu `Additional Views` vs `Additional Viewlets`

I'm not massively passionate but it may make more sense to the user i.e. viewlet is to some degree our own internal language vs the way we show it in the menu or the command palette.

For instace we in this image we use the word `view bar` so it fells like it would be more consistent.
![codebasics_hero](https://cloud.githubusercontent.com/assets/1051190/20969262/197728ce-bc3d-11e6-8894-27ba30134e44.png)

**Comment by bpasero** [comment]
Yes, makes sense.
