### ISSUE TITLE
Disable Explorer Filename Search -- Configuration Option

### ISSUE THREAD

**Issue by Scatterblak** [microsoft/vscode#168144]
I'd like to have a way to disable all searches that occur in the Explorer pane. I often click on ctrl-f to find something in a file -- if I het ctrl-f right after opening a file, though, and the Explorer pane has focus, VS Code starts running a search dialog over there. This is basically useless to some people - there should be an easy way to configure it, or disable that behavior altogether.

**Comment by lramos15** [comment]
You should be able to disable this via your keybindings 

```
{
    "key": "cmd+f",
    "command": "-list.find",
    "when": "listFocus && treeSupportsFind"
}
```
