### ISSUE TITLE
Truncate report issues extension list if the URL is going to be too long

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#16815]
![image](https://cloud.githubusercontent.com/assets/8189808/20969122/f49277fc-bc87-11e6-9748-2087e7e878a8.png)

1. Click Help -> Report Issues
nothing happens

**Comment by joaomoreno** [comment]
Possibly related to #16817.

There seems to be some problem with your default browser since this just launches the browser. #16817 does too.

Does it repro if you restart your machine?

**Comment by con-ssc** [comment]
The "Search Feature Request" button works and a browser opens for example.

**Comment by con-ssc** [comment]
Windows restart didn't change anything.

**Comment by joaomoreno** [comment]
What's you default browser?

**Comment by con-ssc** [comment]
![image](https://cloud.githubusercontent.com/assets/8189808/20970439/e4274996-bc8d-11e6-9fb9-cccd1658b51a.png)

**Comment by joaomoreno** [comment]
How many extensions do you have installed?

**Comment by joaomoreno** [comment]
This may have been broken with 2225c4b03fff356e98229b24c044845ccf052b38 if you have a lot of extensions, producing a URL too long for browsers to handle...

ping @rebornix @Tyriar

**Comment by con-ssc** [comment]
Including Themes I have 64 extensions installed.

**Comment by Tyriar** [comment]
I believe github increased the amount of body text they accept to 6000 so this is no longer an issue even with the truncation.
