### ISSUE TITLE
Javascript Automatic Imports Stopped Working (Even With Every Other Extension Disabled), Part Deaux

### ISSUE THREAD

**Issue by machineghost** [microsoft/vscode#168196]
**Does this issue occur when all extensions are disabled?:** Yes

**- VS Code Version:** 1.73.1
**- OS Version:** Linux Mint 21

First off, I should note that I previously reported this in https://github.com/microsoft/vscode/issues/166808, but then I had some computer trouble, and by the time I resolved it that issue had been closed ("until we hear back" ... but since it's impossible for me to communicate on a closed issue, I had to start this one).

Unfortunately, the issue is still present (even on a completely fresh OS install).

**Steps to Reproduce:**

1. Disable all (non-built-in) extensions ... obviously the Javascript/Typescript extension needs to remain enabled
2. Reference an undefined variable
3. Expect to see it underlined, with a quick fix option to import it (assuming VS Code can infer the import)
4. Instead, see no underline at all (and thus no quick fix)
5. In the lower right, if you hover over the `{}` it says "No jsconfig.json    Create jsonconfig" (that last part has apparently since been fixed, in #167482,  to say "Open jsconfig", as it doesn't actually mean that no `jsconfig.json` exists)

In the previous ticket it was suggested:

>For the bit about No jsconfig: you likely have a jsconfig that does not include the current file. 

But the file should be included, and the `jsconfig.json` file should apply (when I click "Create jsonconfig", it opens that file).  I should note that this issue is happening with all files in my project, but the one I'm testing with is `project_root/src/components/error/NoAccess.js`, and that should clearly fall under my `include` of:

     "include": ["src/**/*.js", "tests/**/*.js"],

For reference my whole `proect_root/jsconfig.json` is:

```
{
  "compilerOptions": {
    "jsx": "react",
    "baseUrl": ".",
    "allowUmdGlobalAccess": true,
    "checkJs": true,
    "module": "commonjs",
    "paths": {
      "*": ["types/*", "*"]
    },
    "strictNullChecks": false,
    "strict": false,
    "target": "esnext"
  },
  "forceConsistentCasingInFileNames": true,
  "no-implicit-dependencies": [true, ["src", "app", "~"]],
  "include": ["src/**/*.js", "tests/**/*.js"],
  "exclude": ["node_modules", "**/node_modules/*", "build/*", "out/*"]
}
```

And while I can't provide my entire project, an example of the problem would be that `project_root/src/components/error/NoAccess.js` file I mentioned:

```
import Link from 'next/link';
import { useRouter } from 'next/router';

const NoAccess = () => {
  const router = useRouter();
  const state = useState(); // this line should be underlined

  return (
    <Layout>
      <h1>No Access</h1>
      <div>You do not have permission to access this page.</div>
    </Layout>
  );
};

export default NoAccess;
```

One final note: all of this *used to* work: I used to be able to see code like that `useState()` underlined, and pressing `CTRL` + `.` I would offer an option to automatically import `useState` from `react`.  So I imagine I just messed up a line of the `jsconfig.json`, or similarly broke one thing somewhere else ... I just have no idea what that one line/thing was.

**Comment by mjbvz** [comment]
#166808 is not locked so you can still post to it. Let's continue tracking the issue there
