### ISSUE TITLE
Hot exit: automatically restored window has lowercase workspace path

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16829]
MacOS

- Dirty a file
- Quit vscode
- Open some other folder with vscode so that the orginal workspace is opened
- The original workspace will have a lowercase workspace path - if you hover a file to see its full path, it will be all lowercase.

This causes problems with debugging - https://github.com/Microsoft/vscode/issues/16570

**Comment by bpasero** [comment]
This also causes issues that file events will not work under Mac, so we must ensure to not open a workspace path with the wrong casing. Marking as important because this will cause lots of issues.

**Comment by Tyriar** [comment]
Can reproduce, the second launch has both the mixed case and lowercase path in the workspaces.json.
