### ISSUE TITLE
webview: failed to XHR post with 400 respose code

### ISSUE THREAD

**Issue by muzhailong** [microsoft/vscode#168289]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: V1.73.1
- OS Version: Win11

Steps to Reproduce:

1. install extension app with id `qijige.imoyu`
2. `ctrl+shift+p` and input `moyu`
3.  click `注册` in webview page
4. input some information, here will get http code with 400
![image](https://user-images.githubusercontent.com/26669978/206149780-bdad9430-1642-48c6-ad54-eecc19bda4b3.png)

I find XHR post cause the error.

**Comment by mjbvz** [comment]
Without more evidence that this is a VS Code issue, this sounds like it is caused by the `qijige.imoyu` extension
