### ISSUE TITLE
Tree find control shortcuts for next/previous result

### ISSUE THREAD

**Issue by svipas** [microsoft/vscode#168213]
There's no shortcuts or ability to create one for tree find results to move to next/previous one. What I can find in keyboard shortcuts is only `list.find` which opens find in tree and that's it. For e.g. editor search widget have shortcuts to move to next or previous result by using Enter or Shift+Enter which resolves to `findNext` or `findPrevious`.

Tree find control:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/10441177/206010047-70d016e5-e832-47b9-a0d9-cadbeca580fc.png">

**Comment by lramos15** [comment]
@joaomoreno Maybe we want to change the tooltip to not be "search" since this is a visual filtering and works different than that of the editor.

**Comment by joaomoreno** [comment]
In the tree, whenever there are search results, `list.focusUp` and `list.focusDown` will navigate only in the subset of element which match the search term. Does this help?

**Comment by svipas** [comment]
@joaomoreno Seems it works when I disable VSCodeVim extension, but only then I move focus out of tree find control (search widget) to explorer, because inside search widget it moves my cursor to end or start using ctrl+n or ctrl+p. So seems like this isn't an issue anymore?

**Comment by joaomoreno** [comment]
Thanks for checking. Still, if you want ctrl+n or ctrl+p to navigate in the list even when focused in the search box and while the vim extension is active, you can still have custom keyboard shortcuts for it. Let me know if you need help with that.

**Comment by kuroshrk-arista** [comment]
yes please show how to do this, if possible
