### ISSUE TITLE
Feature Request: the option to open on another tab, If the definition part is the same file

### ISSUE THREAD

**Issue by YuichiNukiyama** [Microsoft/vscode#16823]
- VSCode Version: 1.8.0-insider
- OS Version: Windows10

I want option which is to open definition part on the another tab. It is useful when there are large files.
If it is the current implementation, it will move in the same file. 
So, I often do not know where the original place was.

**Comment by bpasero** [comment]
@YuichiNukiyama try with `Ctrl+Alt+click`.

**Comment by YuichiNukiyama** [comment]
Thanks.
