### ISSUE TITLE
Settings Sync prompts for login every time VSCode restarts

### ISSUE THREAD

**Issue by user4302** [microsoft/vscode#168225]
Type: <b>Bug</b>

this seems to be the exact same bug that was mentioned here: https://github.com/microsoft/vscode/issues/129813

im currently downloading the insider build to test if the bug persists in that version as its reportedly fixed there.

also im using this same account on a windows 10 as well as11 pc, and this issue only happens on my windows 10 pc,
im using the administrator account on this win10 pc in which the issue happens.

steps to reproduce:
1. open vs code
2. click on 'sign in to sync settings' 
3, click on microsoft. 
4. login.
5. successfully syncs
6. close vs code
7. open vs code
8. prompted to sign in, in order to sync settings.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No
Remote OS version: Linux arm64 5.4.17-2136.311.6.1.el8uek.aarch64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.85GB (5.95GB free)|
|Process Argv|--crash-reporter-id a9a2c16c-c623-4e44-a7bf-ac50fb916c8a|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: OCI|
|OS|Linux arm64 5.4.17-2136.311.6.1.el8uek.aarch64|
|CPUs|Neoverse-N1 (4 x 0)|
|Memory (System)|22.94GB (13.06GB free)|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-react-js-snippets|dsz|4.4.3
dotenv|mik|1.0.1
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.2
vscode-icons|vsc|12.0.1
JavaScriptSnippets|xab|1.8.0
gitlens|eam|13.1.1
git-graph|mhu|1.30.0
data-workspace-vscode|ms-|0.3.0
sqltools|mtx|0.26.0
snippets|tah|2.2.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30622703

```

</details>

**Comment by user4302** [comment]
Log (MS Auth)
![image](https://user-images.githubusercontent.com/32593782/206028210-ddcd48bd-092c-407f-b5fa-bb5709429699.png)

**Comment by user4302** [comment]
just tested it and it happendson the insiders build as well :(

**Comment by TylerLeonhardt** [comment]
Can you go into the Windows Credential Manager, into Windows Credentials, and tell me how many `vscodevscode.microsoft-authentication` items you see?

**Comment by himhimlo** [comment]
> 

Mine having same problem, and seeing tons of `vscodevscode.microsoft-authentication` items, says, at least 40

**Comment by TylerLeonhardt** [comment]
I am suspicious of https://github.com/microsoft/vscode/issues/130893#issuecomment-1232244284

**Comment by user4302** [comment]
> Can you go into the [Windows Credential Manager](https://support.microsoft.com/en-gb/windows/accessing-credential-manager-1b5c916a-6a16-889f-8581-fc16e8165ac0), into Windows Credentials, and tell me how many `vscodevscode.microsoft-authentication` items you see?

oh my i have a LOT.
im guessing thats not normal.
i have them last modified on: 
one on the 30th of october, 
one on the 28th of october, 
and a large amount on the 10th of october

**Comment by user4302** [comment]
> I am suspicious of [#130893 (comment)](https://github.com/microsoft/vscode/issues/130893#issuecomment-1232244284)

shall i run the command mentioned in that comment?
i dont wanna break anything. so ill wait till i get a response to this.

**Comment by TylerLeonhardt** [comment]
@user4302 yes it should be safe to run. Let me know if it resolves the problem for you.

**Comment by user4302** [comment]
> @user4302 yes it should be safe to run. Let me know if it resolves the problem for you.

seems to have resolved my problem, thank you :D
