### ISSUE TITLE
Cpp uses incorrect token kinds

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#168290]
Cpp uses incorrect token kinds:
```cpp
a < (/* > (*/ b)
```

![image](https://user-images.githubusercontent.com/2931520/206151513-f4826413-e1d6-4222-927d-cb627e358b60.png)

This is a bug in the cpp grammar.

**Comment by alexr00** [comment]
Moved to upstream repo: https://github.com/jeff-hykin/better-cpp-syntax/issues/617
