### ISSUE TITLE
Explorer delete action should not say files are irrecoverable in remote repository

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#168241]
![image](https://user-images.githubusercontent.com/30305945/206040592-4f2242eb-b9b7-4e1f-9aad-55e8baa84260.png)
![image](https://user-images.githubusercontent.com/30305945/206040611-5a0fce38-a80e-4de4-aeb0-d7592ea5a699.png)

In a remote repository on vscode.dev, when a file is deleted from the explorer context menu, it can be recovered via the SCM viewlet. If the deletion is tracked via workspace edits they should also be recoverable through undo. We could consider not saying that these files cannot be recovered when the user deletes them.

**Comment by bpasero** [comment]
This seems currently controlled by `useTrash` variable and then would probably have to be enriched with another choice when in remote that makes this clear:

https://github.com/microsoft/vscode/blob/1c85aeab6777c0cd07d847a8c7fa0daff22473be/src/vs/workbench/contrib/files/browser/fileActions.ts#L93

**Comment by bpasero** [comment]
Yeah it seems like a slippery slope...

**Comment by lramos15** [comment]
This isn't an easy fix, and it appears that there are no other reports besides the one from Jackson. So going to mark it as wont fix for now as it would be complicated to get this correct.
