### ISSUE TITLE
code command not working with mac os 13.x

### ISSUE THREAD

**Issue by coltonfreeman26** [microsoft/vscode#168263]
Does this issue occur when all extensions are disabled?: Yes/No
YES

- VS Code Version:  1.73.1
- OS Version: Mac OS Ventura 13.0.1

Steps to Reproduce:

1. Use above versions (only happens on mac 13.x)
2. Try to use the code command

The initial error was saying that line 6 in `/usr/local/bin/code` wasnt using python3 so I added that and now I get 
`line 10: ./MacOS/Electron: No such file or directory`
I updated the path in line 9 to point towards `/Applications/vscode/contents` but am now getting a different error `/usr/local/bin/code: line 10: /Applications/Visual\ Studio\ Code\ 3.app/Contents/MacOS/Electron: No such file or directory` but when I `ls -la` that path Electron is most definitely there. 

Any help on this would be greatly appreciated.

**Comment by deepak1556** [comment]
`/usr/local/bin/code` seems to be outdated, the cli script should't require python https://github.com/microsoft/vscode/blob/main/resources/darwin/bin/code.sh. Please reinstall VSCode and cli symlink.

**Comment by coltonfreeman26** [comment]
I copied that new file over but had no luck so I tried messing with it for a bit and then just did what i should have done from the start... uninstall vscode and delete /usr/local/bin/code reinstalled and works like a charm. Thank you for the help.
