### ISSUE TITLE
Duplicate entries in quick open

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16824]
No exact steps on how I ended up in this state but from today I am seeing duplicate entries in quick open

![screen shot 2016-12-07 at 15 40 06](https://cloud.githubusercontent.com/assets/1926584/20971918/806b33c6-bc93-11e6-9a3e-87aa72ede4d5.png)

**Comment by bpasero** [comment]
@isidorn could it be you opened the file with mixed casing so that it ends up in there? I am sure if you check the contents of local storage around `storage://workspace/Users/bpasero/Desktop/helloGo/history.entries` you would find it with mixed casing. can you check?

**Comment by isidorn** [comment]
Yes I see it under mixed entries.
Can't we do something about this mixed casing issues we are having. I am running into one issue every milestone or should I just rename my Development folder to development :D

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12448
