### ISSUE TITLE
Hot Exit: opens needless untitled file when restoring backups

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16821]
Testing #16544

(Maybe related to #16820), but this is about the Untitled file.

* run `code-insiders notes.txt`, where `notes.txt` does not exist on disk
* type something
* close the window
* launch VS Code Insiders from the taskbar

> It shows an untitled file for a split second, then `notes.txt` opens in a separate tab (in the background). I would expect it to start up and immediately show `notes.txt`, since that is the last file I had opened/typed in/left unsaved:

![image](https://cloud.githubusercontent.com/assets/5047891/20970975/0312f722-bc90-11e6-9455-b4589dcf09f5.png)

**Comment by bpasero** [comment]
This is a consequence of always opening an Untitled-1 file on startup for empty workspaces. I have an idea for a better fix here: we should just check for backups in this case and put those to restore. I can look into this for January, I think it is a bit too late to fix for November.

**Comment by alexandrudima** [comment]
Well, it now starts up like this:

![image](https://cloud.githubusercontent.com/assets/5047891/22369320/7111f70a-e48b-11e6-960c-2e91c2f25ee6.png)

Which is equally bad. If I close VSCode with a tab focused on `notes.txt`, I believe it should start up with a tab focused on `notes.txt`. We do not open the Untitled file anymore, but the behaviour I would expect is still not occuring.

**Comment by joaomoreno** [comment]
ping @chrmarti

**Comment by chrmarti** [comment]
Will fix with #19492. Closing as the original bug here seems fixed.

**Comment by roblourens** [comment]
Original issue verified
