### ISSUE TITLE
Debug Console keeps being shown when using runInTerminalRequest ("console": "integratedTerminal") with "debug.internalConsoleOptions": "openOnSessionStart"

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#168295]
I have this setting set:

```js
"debug.internalConsoleOptions": "openOnSessionStart"
```

Because I generally want to show the debug console when I start a debug session. However, this does not play nicely with `runInTerminalRequest` from a debug adapter, because it seems to force the debug console to also be shown when the process finishes running in a terminal:

![Dec-07-2022 11-05-04](https://user-images.githubusercontent.com/1078012/206163014-229e77b1-3ab8-4312-85ed-6c9851512e87.gif)

At first I thought this was a race, but I can repro in Dart where the application runs for a longer time. As soon as the process ends, VS Code switches to the Debug Console. I can't see anything in the DAP traffic that might be causing this (for example there's no output being printed there).

Changing to not use `openOnSessionStart` prevents this, but that seems inconvenient, and it doesn't match the description (which is about showing it when the session _starts_, not ends).

**Comment by roblourens** [comment]
I'm running pretty much the same launch config and don't see this. It focuses the terminal, then the debug console when debugging starts. If I close the panel, it doesn't focus the Debug Console again when debugging ends. In your gif, it looks to me like the Debug Console is focused when the session starts. You could add a 

```ts
setTimeout(() => {
    console.log(`goodbye`);
}, 3000)
```

to make it more obvious

**Comment by DanTup** [comment]
@roblourens you're right, it is happening near the start (but after the terminal was shown) rather than the end. I think when I'd originally tried to make the ts version not quit so fast I must've confused something.

Ofcourse, it still seems wrong - if the terminal has been shown as part of a `runInTerminalRequest` is seems like VS Code should never subsequently switch to the Debug Console based on `openOnSessionStart`?

![Dec-07-2022 15-48-52](https://user-images.githubusercontent.com/1078012/206225845-26926109-b112-4b61-8420-13ecb0b57128.gif)

**Comment by roblourens** [comment]
I disagree, the Debug Console is still useful when debugging in the terminal. Sometimes users don't really want to be confused by all the stuff in the terminal anyway.

**Comment by DanTup** [comment]
@roblourens I'm confused. The user has chosen to run their app in the terminal, and when they run it, they see the terminal briefly, then it vanishes in favour of an empty debug console. This doesn't seem useful in any way at all. If the user chose to run in the terminal it's likely because they want to interact with the program (otherwise there is no point running it in the terminal).

What is the benefit in showing the debug console, and why does it happen "so long" after the setting suggests (it's not happening while the session is starting, it's happening after the terminal process has been started)?

**Comment by roblourens** [comment]
You can opt out of it if that's not what you want, by setting `debug.internalConsoleOptions`, I think you pointed that out.

> why does it happen "so long" after the setting suggests (it's not happening while the session is starting, it's happening after the terminal process has been started)?

It's happening once the debug session has fully started successfully

**Comment by roblourens** [comment]
Well, the setting `debug.internalConsoleOptions` or you can set it on that particular launch config with `internalConsoleOptions` on the launch config.

And yeah, we seem to check this right after getting the response to launchRequest.
