### ISSUE TITLE
Go to type definition links in tooltip.

### ISSUE THREAD

**Issue by infacto** [microsoft/vscode#168286]
The idea is to quickly find the definition of a variable. In this case, we could just put links in the tooltip, which already leaked the types.

```ts
//#region File-1
export interface MysticalType {
  answer: 42;
}
//#endregion

//#region File-2
export const getSomething = (): MysticalType => ({ answer: 42 });
//#endregion

//#region File-3
const hoverMe = getSomething();
console.log(hoverMe);
//#endregion
```

| Current Way | New Way |
| --- | --- |
|![current](https://user-images.githubusercontent.com/60390085/206145122-47b0b4f9-28d4-49a2-8fb5-569ea75344c3.gif)|![example](https://user-images.githubusercontent.com/60390085/206145134-69dfb4ce-5979-4163-96e0-c306ec1c8140.gif)|
|Currently you have to go a long way. In this example, it's easy. But in real world code it can be a bit more complex. |With this feature request you can just click on the type in the tooltip. Skip points/files and just go to the goal. |

Current version: 1.73.1

**Comment by mjbvz** [comment]
Falls under #64566, which should also apply to hovers
