### ISSUE TITLE
Regroup view menu

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#16826]
- VSCode Version: 1.8.0 - insider 7499a9f
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Steps to Reproduce:

1. For a resolution of 1366 x 768 the view menu is getting too big, getting out of position.

2. I think it would be possible to group some menu items with a generic name and a side menu (with an arrow) to show the items (if I'm not wrong, the name is Submenu). As in `File> Open Recent>`, `File> Preferences>`, `Go> Switch Editor>`, `Go> Switch Group>`.

3. Or create a new menu in the Bar Menu by relocating some items.

![capturar](https://cloud.githubusercontent.com/assets/19866231/20972496/256de890-bc7c-11e6-8222-0a40fb412090.JPG)

**Comment by bpasero** [comment]
Idea:

![image](https://user-images.githubusercontent.com/900690/42516584-7513c8f0-845e-11e8-907d-8fe01ebcfaa5.png)

**Comment by pedrogarcia** [comment]
@bpasero It also would useful to be able to hide the side bar (ctrl+b) by toggling the current open side bar view, the same behavior of the activity panel buttons. That is, have the view menu work like the buttons in the activity panel. 

I use that option a lot and I always forget that clicking the opened view will not hide the current opened view.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --
 
Hello @bpasero!! It looks good to me that way. I believe that there would be no problem in the resolution mentioned.
When this is on the insiders, if you can tell to check!

**Comment by bpasero** [comment]
Settled on this structure:

![image](https://user-images.githubusercontent.com/900690/42585692-a381e144-8536-11e8-88ca-76327afa03dc.png)

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --

Hello, @bpasero  !! In this position, the items got even better !!
Thank you very much!! Waiting to arrive at the Insiders! Can you tell me when it will be?
