### ISSUE TITLE
Save password for ssh connection to git

### ISSUE THREAD

**Issue by stibay** [Microsoft/vscode#16828]
- VSCode Version: 1.7.2
- OS Version: Windows 7

I am trying to authenticate against my git repo through PuTTY. This type of url: ssh://localhost:8889/myRepo.git
I have to supply a username and password but in vscode I don't get any prompt I just get this error in the git output:
```
git fetch
Permission denied, please try again
Permission denied, please try again (publickey, password, keyboard-interactive)
fatal: Could not read from remote repository.
Please make sure you have the correct acces rights and the repository exists.
```
To work around this I had to use something like SourceTree since here I could save the username and password for the repo in the authentication tab in this program.

I figgured out that if I type this line in git I get a popup window when I open vscode where I can enter the password for the repo but there is no option here to save the password so I have to retype the password on every interaction that vscode does to git (which is alot)
`git config --global credential.helper wincred  `

Is there any solution for fixing this so I can save the password?

**Comment by joaomoreno** [comment]
You can try the [Git Credential Manager](https://github.com/Microsoft/Git-Credential-Manager-for-Windows) which should save your credentials. Let me know if it solves it for you.

**Comment by stibay** [comment]
I tried this before but didn't get it to work. Just reinstalled git and installed the GCMW but when I open vscode now I just get the same errors after git fetch as above. Should it prompt me for a password the first time and save this for later?

**Comment by joaomoreno** [comment]
GCMW should prompt you, yes. You can try from the command line too.

**Comment by stibay** [comment]
Yes, if I try git fetch in the command line I am asked to type in the password on the next line (no popup).
But this also works wihtout the GCMW installed. Just uninstalled it and it still asks me for a password in the command line.

So its no difference in either the command line or vscode with GCMW installed or not.

**Comment by joaomoreno** [comment]
Oh. There should definitely be a difference. What value did you set for `credential.helper` for GCMW?

**Comment by stibay** [comment]
What should I set? It says it should "magically" works. Read somewhere that setting it to "store" should save the password but that didn't do anything. Also tried the stuff with cache but no difference and I wrote in the issue what happends if I set it to wincred.

**Comment by joaomoreno** [comment]
Check the [Sample Configuration](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/blob/6d7bf014e938f197dcfef3ee9e82aa79878a2a07/Docs/Configuration.md#sample-configuration)

**Comment by stibay** [comment]
What and where should I set that? In the config file in the hidden .git folder where I cloned my repo? I added this to the bottom of the file there, but no difference. Also tried adding interactive = always but this also didn't change anything so doesn't look like it's reading that config?
```
[credential]
    helper = manager
    writelog = true
```

Should I also add something spesific for the host? Under origin in the config file it looks like this:
```
[remote "origin"]
	url = ssh://localhost:8889/local/.../my-repo.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	pushurl = ssh://localhost:8889/local/.../my-repo.git
```

**Comment by joaomoreno** [comment]
You can check what the current value is by calling `git config credential.helper`.

You don't need anything specific for the host.

**Comment by stibay** [comment]
Hmm ok, so it seems like it's reading the configuration since I can change this in the file and I can see when I type that command that the changes are reflected.
What should the helper be set to? From the sample config I can see it's manager there.

Seeing some wierd behaviour though with opening vscode from the command line versus the GIT Bash command line. Whatever I change the helper to, when I open vscode from the GIT Bash I always get the prompt for entering my password in a popup wit the title OpenSSH (thought this was only when the helper was wincred). This never saves the password.

And almost everytime I try open vscode from the command line I get the permission denied messages.

**Comment by joaomoreno** [comment]
Do you maybe have multiple git versions installed?
