### ISSUE TITLE
File Explorer file-sorting seems wrong?

### ISSUE THREAD

**Issue by zachlysobey** [Microsoft/vscode#1682]
Is there any reasonable way files are supposed to be sorted?

*This lead me to belive that it was sorted by file extension*:

![screen shot 2015-12-28 at 5 25 35 pm](https://cloud.githubusercontent.com/assets/1310403/12026607/8c42b4f4-ad89-11e5-996c-828df54f616d.png)

*but this proved that theory wrong*:

![screen shot 2015-12-28 at 5 33 22 pm](https://cloud.githubusercontent.com/assets/1310403/12026606/8c3bdb52-ad89-11e5-8f4d-1bd304b853f2.png)

IMO, it should be alphabetical (with folders on top of course), and if some people prefer sorting by file extension than it should be a user-preference.

**Comment by bpasero** [comment]
I think we tweaked this quite heavily...

**Comment by joaomoreno** [comment]
Here's the sorting algorithm:
- https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/files/browser/views/explorerViewer.ts#L633
- https://github.com/Microsoft/vscode/blob/master/src/vs/base/common/comparers.ts#L11
