### ISSUE TITLE
Markdown Language Features: Custom directory and name for pasted images

### ISSUE THREAD

**Issue by Altair-Bueno** [microsoft/vscode#168200]
Allow users to modify the target folder where the images should be stored, as well as the file name. Something like this:

```json
{
	"markdown.experimental.pastedir": "${DIRNAME}/resources",
	"markdown.experimental.filename": "${DATE}.png",
}
```

### Additional info

- I think this class is in charge of copy&paste on markdown, but im not familiar enough with the source code to attempt this change myself: https://github.com/microsoft/vscode/blob/c16bf3470b591d6e5e353eafaaf31d299de6680d/extensions/markdown-language-features/src/languageFeatures/copyPaste.ts#L81

**Comment by mjbvz** [comment]
This is already being tracked by #157043

**Comment by Altair-Bueno** [comment]
Hey @mjbvz, I believe you handed me the wrong link. The referred issue has nothing to do with the requested feature. "copy image into workspace" does not imply custom filenames and/or directory

**Comment by mjbvz** [comment]
Custom paths falls under the feature request in #157043
