### ISSUE TITLE
codespaces ports tab is missing

### ISSUE THREAD

**Issue by BalbinoOrtus** [microsoft/vscode#168205]
something happend and my codespace has no port tab
![image](https://user-images.githubusercontent.com/80276017/205996997-0700c589-2d51-46a1-b1f6-b388914000f7.png)

i do have defined in my dev container the forwarding ports
![image](https://user-images.githubusercontent.com/80276017/205997120-172b0b5c-d344-462b-860d-017588411108.png)

i think i saw a notification saying that a service worker was  asking for permission and was denied but other than that i dont know why this is happening or how can i bring it back, please help! 

Version: 1.74.0-insider
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by alexr00** [comment]
@BalbinoOrtus did the Ports view show after a few minutes? It can take a little while before Codespaces setup is complete and the Ports view is visible.

**Comment by BalbinoOrtus** [comment]
I did the issue was that by mistake i click/switch to insiders edition and did not realize until later in the day, switching back to the stable version did the trick, i just went crazy in the process, but thank you for your help @alexr00
