### ISSUE TITLE
Sporadic encoding issues for built-in Terminal

### ISSUE THREAD

**Issue by morgante** [microsoft/vscode#168261]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.73.1 (Commit: 6261075646f055b99068d3688932416f2346dd3b)
- OS Version: OS X 12.6 (21G115)

Steps to Reproduce:

1. Run various commands in the Terminal (no consistent pattern)
2. Step away for a bit, work in another window
3. When I return, the Terminal output is garbled.

I wish I had more info about how to replicate this, but I wanted to put it on the community's radar since it's been recurring for several weeks. Example output:

<img width="928" alt="image" src="https://user-images.githubusercontent.com/1627801/206077363-797ec4dd-4d41-4be3-bb8a-a7f16d4ea485.png">

**Comment by brendanfalk** [comment]
We are also particularly interested in what's going here @Tyriar! OP + a few other Fig users thought it was a Fig issue, but we have since confirmed that it also happens without Fig installed.

**Comment by Tyriar** [comment]
@brendanfalk there's an explanation of the bug in https://github.com/xtermjs/xterm.js/pull/4271#issuecomment-1324241152. Basically the glyph locations that point at a shared texture in some terminals could get stale.
