### ISSUE TITLE
Can't undo "Join with next cell"

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#168267]
- Run "Join with next/previous cell"
- press cmd+Z
- Nothing happens

**Comment by roblourens** [comment]
If I put the cursor in the joined cell and press undo, then it removes the text from the other cell, but the previous cell is not restored, so it seems we don't track this in the notebook undo stack correctly

**Comment by rebornix** [comment]
I don't reproduce this anymore.

**Comment by roblourens** [comment]
Agreed, works fine right now
