### ISSUE TITLE
[Accessibility] - Screen reader will read the `detail` of the previously displayed quick pick list when items have no detail

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/vscode#168272]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.73.1
- OS Version: macOS Ventura 13.0.1

Steps to Reproduce:

1. Enable VoiceOver
2. Launch a command that uses a Quick Pick List where the items have a `detail` as well as a title or description (demoed with Azure Extension "Create Resource") 
3. Close list
4. Launch a command that uses a Quick Pick List where the items have **no** detail, e.g. "Select Display Language" or even command palette
5. Screen reader will read the title of the new item with the **detail of the item in the previously displayed quick pick list**

https://user-images.githubusercontent.com/1532417/206096817-46feb3c2-2538-4693-8ea4-b1cbe8bdd460.mp4

Same bug with the command palette reading details for items:

https://user-images.githubusercontent.com/1532417/206097474-afc06886-adbc-40b6-a007-71ceeec07ce6.mp4

**Comment by TylerLeonhardt** [comment]
Verification steps: the issue steps are good. If you want a non-Azure extension command that shows a quick pick with details, use `Snippets: Insert Snippet`
