### ISSUE TITLE
Settings editor Settings object widget buttons layout fail when editor is in Chinese

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#168328]
1. Switch the configured display language to Simplified Chinese.
2. Navigate to the Settings editor and search for the `emmet.includeLanguages` setting.
3. Add in some values. Arbitrary strings are fine.
4. :bug: The OK and Cancel buttons on the right side overflow.

![Screenshot showing the ](https://user-images.githubusercontent.com/7199958/206247411-7ae9418a-8674-4f37-a8bd-85b4920578d0.png)

**Comment by joyceerhl** [comment]
很好 👏
