### ISSUE TITLE
Search in folder with special characters `{}` yields no results.

### ISSUE THREAD

**Issue by colelawrence** [microsoft/vscode#16834]
- VSCode Version: Version 1.7.2 (1.7.2) - 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
- OS Version: Mac OS X El Capitan 10.11.6 

Steps to Reproduce:

1. Create folder called `{hello}`
2. Place `hello.txt file` in folder with `hello`
3. Click `{hello}/` in sidebar to "Find in Folder" `hello`
> This inputs `{hello}` in the "files to include" input of the Search bar.
4. *Observe* that no results are found.

![image](https://cloud.githubusercontent.com/assets/2925395/20977078/05976918-bc6a-11e6-98c0-c7a94dac6f7f.png)

**Comment by ZombieHippie** [comment]
Possibly related:

[vscode/src/vs/workbench/parts/search/browser/patternInputWidget.ts#126](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/search/browser/patternInputWidget.ts#L126)
```ts
	public getGlob(): IExpression {
		let pattern = this.getValue();
		let isGlobPattern = this.isGlobPattern();

		if (!pattern) {
			return void 0;
		}

		let glob: IExpression = Object.create(null);

		let segments: string[];
		if (isGlobPattern) {
			segments = splitGlobAware(pattern, ',').map(s => s.trim()).filter(s => !!s.length);
		} else {
			segments = pattern.split(',').map(s => strings.trim(s.trim(), '/')).filter(s => !!s.length).map(p => {
				if (p[0] === '.') {
					p = '*' + p; // convert ".js" to "*.js"
				}

				return strings.format('{{0}/**,**/{1}}', p, p); // convert foo to {foo/**,**/foo} to cover files and folders
			});
		}

		return segments.reduce((prev, cur) => { glob[cur] = true; return glob; }, glob);
	}
```
