### ISSUE TITLE
Add a filter to the Problems pane to only show changed files

### ISSUE THREAD

**Issue by elezar42** [microsoft/vscode#168326]
Visual Studio 2019/2022 have the ability to filter the Error List by "Changed Documents." Having a similar filter for the VSCode Problems pane would be very useful.

We have a large number of pre-existing warnings in our codebase that we are slowly working through fixing. In the meantime, we have other changes that are being made, and need to make sure we're not introducing new problems with those changes. Even in normal everyday use, if another developer commits a change that has problems, while I may need to look into those problems at some point, I don't want to worry about them when I'm putting together my own commit.

I want to be able to ignore any problems in files that I'm not actively working on. Currently I have to filter the Problems by Active File, and then open each file that I've modified. This is a pain if there are a lot of modified files.

**Comment by sandy081** [comment]
I doubt if this can be done in VS Code platform. because the platform has no clue of modified files.
