### ISSUE TITLE
Keybinding service should not dispatch on modifier keys

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16833]
Have the following keybinding:
```
{
	"key": "ctrl+<",
	"command": "workbench.action.reloadWindow",
	"when": "editorTextFocus"
}
```

Press `ctrl`. Notice the workbench reloading.

Found in https://github.com/Microsoft/vscode/issues/16539#issuecomment-265126973

**Comment by Tyriar** [comment]
@alexandrudima please review, an explanation is in the commit long desc.

**Comment by alexandrudima** [comment]
@Tyriar thank you, I've written unit tests instead of reviewing this time, given the last reviews didn't uncover the regressions :).
