### ISSUE TITLE
UI glitches in find ref peek view with sticky scroll turned on

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#168372]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.75 Insiders
- OS Version:  macOS

https://user-images.githubusercontent.com/876920/206322493-0b381e8b-82e3-43bf-bc81-26837b709616.mov

**Comment by rebornix** [comment]
It seems we have a transparent background when using the v2 dark theme. Though there should always be a bg color fallback.

**Comment by alexdima** [comment]
The relevant color here is `editorStickyScroll.background`. There are two problems:
* this should be defined opaque
* if this isn't opaque, maybe we should force it to be opaque in code @jrieken

**Comment by jrieken** [comment]
this is https://github.com/microsoft/vscode/issues/168430

**Comment by rebornix** [comment]
@jrieken I'm still seeing this with Peek View. The problems listed by @alexdima https://github.com/microsoft/vscode/issues/168372#issuecomment-1342844169 is not being fixed it seems.

<img width="1330" alt="image" src="https://user-images.githubusercontent.com/876920/207203896-de0c83a9-67c0-473b-a3ee-519a0549ce33.png">

**Comment by rebornix** [comment]
> It seems we have a transparent background when using the v2 dark theme

I'm using Dark+ V2 (experimental) theme.

**Comment by daviddossett** [comment]
Likely just a theme bug then. I'll take a look.
