### ISSUE TITLE
`dockerfile.py` syntax-highlights as a Dockerfile, not a Python file

### ISSUE THREAD

**Issue by MatrixManAtYrService** [microsoft/vscode#168394]
Type: <b>Bug</b>

The title pretty much says it all.  Create a python file called "dockerfile.py" and notice that you don't get python syntax highlighting.

VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|64.00GB (20.23GB free)|
|Process Argv|--crash-reporter-id 024bf4e4-11bc-4008-aa5e-c3d69ed66fab|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|13.1.1
python-flake8|kan|0.0.1
vscode-docker|ms-|1.23.1
isort|ms-|2022.8.0
python|ms-|2022.18.2
vscode-pylance|ms-|2022.11.40
jupyter|ms-|2022.9.1303220346
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.262.3
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.2
vscode-yaml|red|1.10.1
unique-window-colors|stu|1.0.51
vim|vsc|1.24.3

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
cc2-nonfim-prod:30622702

```

</details>

**Comment by MatrixManAtYrService** [comment]
If you're going to automate issue creation, why not remind me up front?  Anyway, I upgraded:

Version: 1.74.0 (Universal)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z (2 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

The problem persists.

**Comment by aeschli** [comment]
The docker extension registers for everything `Dockerfile.* . That is a common file name pattern according to
https://docs.docker.com/engine/reference/commandline/build/#specify-a-dockerfile--f

You can customize file name associations with:
```
	"files.associations": {
		"dockerfile.py": "python"
	},
```
