### ISSUE TITLE
Titlebar on a small editor window when using VS Code in Simplified Chinese has overlapping text

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#168332]
1. Switch the editor to Simplified Chinese.
2. Resize the window to be smaller.
3. :bug: The titlebar menu entries collide with the title.

![Screenshot showing titlebar menu text collision](https://user-images.githubusercontent.com/7199958/206262726-2945843b-e74a-49c4-8d02-76e8e5c1b889.png)

**Comment by benibenj** [comment]
Unable to reproduce, an you still reproduce @rzhao271?

**Comment by rzhao271** [comment]
Nope, which is great
