### ISSUE TITLE
@Tyriar when type chinese look like this, it's happend from version `1.74`

### ISSUE THREAD

**Issue by shaodahong** [microsoft/vscode#168381]
@Tyriar when type chinese, look like this, it's happend from version `1.74`

```
Version: 1.74.0 (Universal)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```
https://user-images.githubusercontent.com/14831261/206334195-dcbf05b9-d202-4a19-951f-2de9efbcebe4.mp4

_Originally posted by @shaodahong in https://github.com/microsoft/vscode/issues/163027#issuecomment-1341849961_

**Comment by cmdyu** [comment]
Turn off Terminal › Integrated: Detect Locale meight solve the problem.

I solved the git bash  and git log chinese encoding problem on windows11 with this method.

Or you can execute this command in your terminal
···
export LANG=zh_CN.UTF8
···

Seems that v1.74 not detected the correct locale, it set LANG to 'zh_HANS_cn.UTF-8', which should be 'zh_CN.UTF8'

**Comment by msftrncs** [comment]
Looks like the console is not operating a UTF-8 encoding, but input is in UTF-8.  The shell is echoing the characters from the input, which appears to be the three byte sequences of a UTF-8 code point.

**Comment by shaodahong** [comment]
> Turn off Terminal › Integrated: Detect Locale meight solve the problem.
> 
> I solved the git bash and git log chinese encoding problem on windows11 with this method.
> 
> Or you can execute this command in your terminal
> 
> ```
> export LANG=zh_CN.UTF8
> ```
> 
> Seems that v1.74 not detected the correct locale, it set LANG to 'zh_HANS_cn.UTF-8', which should be 'zh_CN.UTF8'

My system use `EN`, but in vscode some msg need type Chinese

**Comment by A404coder** [comment]
I had the same problem.

> OS: MacOS
> VS Code: 1.74

You can fix this problem by modifying the terminal's config file.

vim ~/.zshrc
then set `export LANG=zh_CN.UTF-8`
![image](https://user-images.githubusercontent.com/94605465/206566540-693d69a2-6b1b-407f-95f5-1a34b99866e3.png)
then source ~/.zshrc

or ~/.bash_profile balaba..

**Comment by shaodahong** [comment]
> I had the same problem.
> 
> > OS: MacOS
> > VS Code: 1.74
> 
> You can fix this problem by modifying the terminal's config file.
> 
> vim ~/.zshrc then set `export LANG=zh_CN.UTF-8` ![image](https://user-images.githubusercontent.com/94605465/206566540-693d69a2-6b1b-407f-95f5-1a34b99866e3.png) then source ~/.zshrc
> 
> or ~/.bash_profile balaba..

Yep. when i set LANG and after removing it, it's also fine, so i don't know vscode do something
