### ISSUE TITLE
Cannot read properties of undefined (reading 'git')

### ISSUE THREAD

**Issue by Jademalo** [microsoft/vscode#168395]
Type: <b>Bug</b>

When trying to use source control after a recent update, I get this error in the bottom right hand corner. 
`Cannot read properties of undefined (reading 'git')`
I can't see my commit history in the source control tab, and cannot commit.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8086K CPU @ 4.00GHz (12 x 4008)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.84GB (7.38GB free)|
|Process Argv|--crash-reporter-id 75d2bff3-b4ef-4cb2-9b19-e7eeeba2b392|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
tasks|act|0.11.1
Bookmarks|ale|13.3.1
arm|dan|1.7.4
githistory|don|0.6.19
git-commits|Exe|4.1.0
vdf|GEE|0.0.7
codespaces|Git|1.13.4
vscode-pull-request-github|Git|0.56.0
vscode-autohotkey-plus-plus|mar|3.1.0
vscode-docker|ms-|1.23.1
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-wsl|ms-|0.72.0
hexeditor|ms-|1.9.9
material-icon-theme|PKi|4.22.0
pin-up|sae|1.4.1
vscode-taskexplorer|spm|2.9.1
material-theme|zhu|3.15.6

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723
ejf25101:30620729

```

</details>

**Comment by euxx** [comment]
Same here, it seems it's the issue with [Git Commits](https://github.com/Exelord/git-commits) extension, when disable the extension, the error message disappear.

**Comment by Jademalo** [comment]
Thanks, I've made a ticket for that extension.
Seems like 1.74.0 broke it.

**Comment by lszomoru** [comment]
Updated the issue in the extension's repository with what I believe caused this.
