### ISSUE TITLE
Restart running task not working - Prevented duplicate task from running

### ISSUE THREAD

**Issue by marcoSven** [microsoft/vscode#168378]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Mac 12.6

Steps to Reproduce:

The issues started with version 1.74.0

1. Run task X
2. Restart running task X - Tasks: Restart Running Task

Task X stops but does not restart. Info "Prevented duplicate task from running X"

**Comment by meganrogge** [comment]
How quickly after running the task are you restarting it?

**Comment by marcoSven** [comment]
Doesn't look like it makes a difference how long I am running a task. 

Also, I noticed that when I try to run an already-running task again I no longer get a pop-up asking if I want to terminate or restart. 

<img width="464" alt="Screen Shot 2022-12-07 at 7 07 39 PM" src="https://user-images.githubusercontent.com/3860298/206346414-66882482-4d2a-46df-b7f8-b666ca8e6789.png">


I installed Version: 1.73.1 and everything works again.

**Comment by brunnerh** [comment]
Can confirm that the popup is gone, which is how I usually restart tasks. (I am on Windows 11)

**Comment by joyceerhl** [comment]
Was able to repro this for user tasks

```
TRACE terminalInstance#dispose (instanceId: 3)
log.ts:298 DEBUG Terminal process exit (instanceId: 3) with code undefined
log.ts:298 DEBUG Terminal process exit (instanceId: 3) state 5
log.ts:304  INFO Prevented duplicate task from running Serve web extension over https
```

Version: 1.74.1 (user setup)
Commit: 7dcd27a4eeed1334a366c16b499da193c64b7f12
Date: 2022-12-13T13:30:00.464Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by joyceerhl** [comment]
Btw also repros for a task defined in .vscode/tasks.json https://github.com/microsoft/vscode-extension-samples/blob/24ee5beac4ac9fb267b54281a165bff2b08acb66/comment-sample/.vscode/tasks.json#L1-L20

**Comment by meganrogge** [comment]
Oh I can repro when I rerun a task that has already been rerun once.

**Comment by joyceerhl** [comment]
> task that has already been rerun once

In the current VS Code session or ever? I was able to repro even for a task that had not been previously rerun in the current session (not fresh user data dir though).

**Comment by meganrogge** [comment]
The issue appears to be when there are dependency tasks, they get added to `inProgressTasks` but never hit the finally here

https://github.com/microsoft/vscode/blob/18e90baa1432619e5dde79a9ed5f529310fcce80/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1228-L1232

![Screenshot 2022-12-13 at 1 55 47 PM](https://user-images.githubusercontent.com/29464607/207431364-9fc02136-5591-4045-8e2c-5241c6a5e286.png)

**Comment by meganrogge** [comment]
> > task that has already been rerun once
> 
> In the current VS Code session or ever? I was able to repro even for a task that had not been previously rerun in the current session (not fresh user data dir though).

A gif would be helpful - that's very odd and not sure how it's possible

**Comment by meganrogge** [comment]
I see the problem - `run` isn't always used. We should be adding and deleting from the set in `_executeTask`

**Comment by joyceerhl** [comment]
Hm, this is not a dependency task though, I just have a user task and I do Ctrl+P > task <name of task to run>

**Comment by meganrogge** [comment]
Yes your user task probably runs through this function which calls `_executeTask` instead of `run`

https://github.com/microsoft/vscode/blob/85c7a560bd3dcc80036f45bfe72551d393cd1b0a/src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts#L1173-L1199
