### ISSUE TITLE
`@outdated` filter not available for autocompletion in Extensions: Marketplace interface anymore, still works

### ISSUE THREAD

**Issue by macintacos** [microsoft/vscode#168314]
Does this issue occur when all extensions are disabled?: Yes

I noticed that recently, the "@outdated" filter no longer auto-completes. I don't like auto-upgrading my extensions without knowing what has been updated in them, so I use this filter fairly often. I was worried that maybe the filter was completely removed, but thankfully, it still exists - if you finish typing out the whole filter, it does filter the list as expected. Just would be nice to get the auto-completion back.

Filter not showing up while typing:

<img width="507" alt="CleanShot 2022-12-07 at 09 55 13@2x" src="https://user-images.githubusercontent.com/8128941/206213488-0b88c976-bc34-4231-a1ee-190eceb5016a.png">

When you finish typing the filter, it works as expected:

<img width="365" alt="CleanShot 2022-12-07 at 09 55 02@2x" src="https://user-images.githubusercontent.com/8128941/206213443-96b56089-180f-4eef-963d-546b6cc84efb.png">

- VS Code Version: Version: 1.73.1
	Commit: 6261075646f055b99068d3688932416f2346dd3b
	Date: 2022-11-09T02:22:48.959Z
	Electron: 19.0.17
	Chromium: 102.0.5005.167
	Node.js: 16.14.2
	V8: 10.2.154.15-electron.0
	OS: Darwin arm64 21.6.0
	Sandboxed: No
- OS Version: macos 12.6.1

Steps to Reproduce:

1. Go to the "Extensions: Marketplace" interface and start to type "@outdated"
2. Notice that no options come up for autocomplete
3. Finish typing out the filter "@outdated" - notice how it does filter the list to only extensions that are outdated, so the filter still works

**Comment by sandy081** [comment]
This is deprecated in favour of `@updates` and for backward compatibility we made sure the filter still works.

**Comment by macintacos** [comment]
Oh, great! Must've missed that announcement - `@updates` is much nicer 🙂
