### ISSUE TITLE
--extensions-dir not accepting relative path on Windows

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16836]
- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.0.7|
|python|donjayamanne|0.5.0|
|tslint|eg2|0.5.39|

---

Steps to Reproduce:

1. Does not start: code-insiders.cmd --user-data-dir tmp\user --extensions-dir tmp\exts
2. Does start: code-insiders.cmd --user-data-dir tmp\user --extensions-dir c:\Users\chrmarti\tmp\exts

**Comment by ramya-rao-a** [comment]
`code-insiders --extensions-dir /tmp/extensions` works
`code-insiders --extensions-dir tmp/extensions`  doesnt work

Which of the 2 is expected?
