### ISSUE TITLE
blurry and poor resolution

### ISSUE THREAD

**Issue by 5w00p** [microsoft/vscode#168393]
Type: <b>Bug</b>

Just start VS Code and try and use it and the window contents are very blurry.
Nvidia GTX 1060 with latest drivers.
As mouse moves, it blurs up along the path that the mouse took

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.89GB (12.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (0)</summary>

Extension|Author (truncated)|Version
---|---|---
<all extensions uninstalled>

</details>

**Comment by 5w00p** [comment]
![vsCode-blur](https://user-images.githubusercontent.com/7979695/206362961-608fe8db-cf56-4378-965f-c56bcda3051e.png)

**Comment by deepak1556** [comment]
Please disable hardware acceleration in the runtime https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

Merging to https://github.com/microsoft/vscode/issues/124226

**Comment by 5w00p** [comment]
Did not fix the issue on my work computer.
