### ISSUE TITLE
Windows PowerShell should be the default terminal program on Windows

### ISSUE THREAD

**Issue by daviwil** [Microsoft/vscode#16838]
I'd like to recommend making PowerShell the default terminal program on Windows when the user hasn't configured their path (and when the `COMSPEC` environment variable hasn't been explicitly set).  Since PowerShell will now be the default terminal program in Windows 10 going forward ([see blog post](https://blogs.windows.com/windowsexperience/2016/11/17/announcing-windows-10-insider-preview-build-14971-for-pc/)), I think it makes sense to make it the default in VS Code on Windows as well.

What do you think?

**Comment by dburt667** [comment]
I absolutely agree with PowerShell being Default Term.

**Comment by rkeithhill** [comment]
Agreed!!  Especially given that Windows 10 just [announced that PowerShell would be the default shell](https://blogs.windows.com/windowsexperience/2016/11/17/announcing-windows-10-insider-preview-build-14971-for-pc/#DZoEoutkfPYfg4SY.97) offered in the Win+X poweruser menu and in Windows Explorer.

**Comment by ChrisWarwick** [comment]
Yep.  Please.

**Comment by LaureKamalandua** [comment]
Couldn't agree more with the other people.

**Comment by mattmcnabb** [comment]
Can't argue at all. Seems natural that it would follow the Windows default command line program.

**Comment by johlju** [comment]
I agree

**Comment by Tyriar** [comment]
@daviwil isn't `COMSPEC` set by default? Is it possible to tell if it's explicitly set?

**Comment by tostca** [comment]
Sounds like an great idea :)

**Comment by MathieuBuisson** [comment]
I do agree.

**Comment by daviwil** [comment]
@Tyriar looks like it is set to cmd.exe by default.  That was my understanding too but someone suggested that there are cases when it isn't set; I don't have any data to back that up.  Even though Windows 10 is going to default to PowerShell in the UI now, I haven't heard whether they'll change `COMSPEC` to point to PowerShell.  Either way, since PowerShell is far better than cmd.exe for developers, it makes sense to default to it in VS Code on Windows.

If the team decides it's better to stick with `COMSPEC`, I might see if users of the PowerShell extension would be OK with us auto-configuring the terminal to point to PowerShell on Windows.

**Comment by Tyriar** [comment]
I'm concerned about breaking people's workflow. The little experience I do have suggests that we may be by switching this. Specifically I recall it being very slow doing trivial commands and one of my most used commands before I jumped over to Linux was`dir/w` which throws a scary looking error in PS.

By default on Windows does the post mean that powershell will appear first when you search for `"cmd"`, with cmd.exe also matching the search? Because that at least gives people a very clear option, configuring the integrated terminal is a little less trivial. It also seems preferable to rather get the Windows team to make `COMSPEC` point to (64-bit) Powershell rather than updating every tool to work around it? Right now I believe it points at the 32-bit version of cmd.exe by default, even on 64-bit machines.

Having powershell update the config in the meantime makes total sense though (via a messagebox?).

**Comment by rkeithhill** [comment]
What this means (from the MS post):
> In an effort to bring the best command line experiences to the forefront for all power users, PowerShell is now the defacto command shell from File Explorer. It replaces Command Prompt (aka, “cmd.exe”) in the WIN + X menu, in File Explorer’s File menu, and in the context menu that appears when you shift-right-click the whitespace in File Explorer.

Regarding:
> does the post mean that powershell will appear first when you search for "cmd", with cmd.exe also matching the search?

No. Folks should always be able to find cmd.exe and run it if they need/want to.

> dir/w which throws a scary looking error in PS.

Yes. There are cmd.exe `built-in` commands that are not completely emulated in PowerShell e.g. `dir` (alias) works but not `dir/w`.  Folks have been learning PowerShell over the past decade and I think its time has come.  The equivalent of `dir/w` in PS is `dir | format-wide` or `dir | fw` if you prefer to type less.  

Also, try to do this with your CMD prompt.  :-)

![image](https://cloud.githubusercontent.com/assets/5177512/20990168/bfba05ec-bc94-11e6-936c-cd810b802b58.png)

**Comment by stefanstranger** [comment]
I agree too.

**Comment by devlead** [comment]
Agree 👍

**Comment by apetitjean** [comment]
Of course!!!!

**Comment by zackJKnight** [comment]
I vote yes.

**Comment by happysysadm** [comment]
YES!

**Comment by Tyriar** [comment]
I haven't heard anything against this yet either here or from the team so I'd love to accept a PR and see how it goes in Insiders. Here are some recommendations on the implementation:

- Don't point at `powershell.exe` in `PATH` as this points to the 32-bit version on 64-bit machines
- Powershell should only be the default on Windows 10, use `platform.isWindows`, `os.release()` and `process.arch` to get whether it's 32/64-bit Windows 10 and point at correct path
- Move `TERMINAL_DEFAULT_SHELL_WINDOWS` in `/src/vs/workbench/parts/terminal/common/terminal.ts` to `/src/vs/workbench/parts/terminal/electron-browser/terminal.ts` and generate the path there (for [architectural reasons](https://github.com/Microsoft/vscode/wiki/Code-Organization#target-environments)).
- Point at the current Windows installation directory without any IO (env var?)

**Comment by rkeithhill** [comment]
@Tyriar The file `.../electron-browser/terminal.ts` doesn't exist AFAICT.  Is the idea to create a terminal.ts in the electron-browser dir?

**Comment by Tyriar** [comment]
@rkeithhill yes this would need to be created, the reason being because you can't access `require('os')` or `process` from common/ as it needs to be able to run in a browser.

**Comment by jchadwick** [comment]
@Tyriar take a look at the above commit, which implements your requirements above (I think).

However, taking your direction literally, it does not call [`processes.getWindowsShell()`](https://github.com/Microsoft/vscode/blob/master/src/vs/base/node/processes.ts#L84-L86) and therefor does not take into consideration `process.env['comspec']` to allow the user to override.  

Is this what you intended?

**Comment by Tyriar** [comment]
Thanks @jchadwick, let's discuss in the PR.

**Comment by Tyriar** [comment]
To verifier: check that powershell is now the default terminal shell on Windows 10

**Comment by ishitatsuyuki** [comment]
Please update the documents: https://code.visualstudio.com/docs/editor/integrated-terminal

**Comment by Tyriar** [comment]
Thanks @ishitatsuyuki, created https://github.com/Microsoft/vscode-docs/issues/891
