### ISSUE TITLE
Broken notebook rendering on first load

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#168330]
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/8599/206256231-401c6f22-676d-4ea1-a7e0-30ef3836aadc.png">

@rebornix's analysis: markdown cells are collapsed, however it renders the preview and markdown preview.

Reloading fixes it:

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/8599/206259142-a306110f-60e6-43fb-8dfa-1efc8d961802.png">

Version: 1.74.0-insider
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.0.0
Embedder: github.dev

**Comment by roblourens** [comment]
Had you previously collapsed those cells? Can you repro this? Working fine for me

**Comment by digitarald** [comment]
> Had you previously collapsed those cells?

Yes. It was fine after restart. @rebornix assumes this is probably a race condition, making a repro not straightforward.

**Comment by roblourens** [comment]
Does thi sstill happen? @rebornix?

**Comment by DonJayamanne** [comment]
@digitarald Please let me know if this issue still repros, we haven't had any reports for a while about such issues.
I'm assuming its been fixed since.
