### ISSUE TITLE
Tunnels is a major security concern

### ISSUE THREAD

**Issue by ohmantics** [microsoft/vscode#168370]
Type: <b>Bug</b>

I relaunched VSCode to be faced with a description of the new Remote Tunnels feature in the release notes. The documentation doesn't begin to cover what needs to be said.

* What ports does this use?
* Is data encrypted? If so, with what cyphers?
* Am I correct in describing this as a firewall-penetrating backdoor that puts GitHub/Azure in charge of authentication? If so, that's a major violation of many policies at many companies.
* "Without SSH" is a bad look. SSH is a well-understood technology and well-audited set of implementations. "Remote Tunnels" is a total unknown and doesn't on the face of it seem to provide any improvement -- only very serious questions.

VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
npm-intellisense|chr|1.4.3
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
vscode-pull-request-github|Git|0.56.0
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.0.2
fig|wit|0.0.7

</details>

**Comment by connor4312** [comment]
- Remote tunnels does not actively listen on any ports; it makes an outbound connection to an Azure service
- Data over the tunnel is end-to-end encrypted, currently we use AES 256 in CTR mode. The code that implements this can be found [here](https://github.com/microsoft/dev-tunnels) (the Rust library on the host side, TypeScript on the client side)
- Companies with such policies are encouraged (and many already do) to have a denylist or allowlist for specific services. If they have policies like this for similar services like localtunnel or ngrok, they probably want to adopt the same policy for Remote Tunnel Access.
- Thanks for your input!

**Comment by ohmantics** [comment]
I definitely think the documentation needs to spell out these details.

FWIW, I would estimate that corporate IT department decision makers that set policy wouldn't even know what localtunnel or ngrok are. Some might remember "Back to my Mac" as something they had to ban, but even that's stretching it.

**Comment by connor4312** [comment]
Circling back here, Dev Tunnels has added [group policies](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/policies) which VS Code respects as of 1.88, releasing next week.
