### ISSUE TITLE
[remote tunnels] notifies me about a new tunnel when I switch profiles, even though the other machine isn't even on

### ISSUE THREAD

**Issue by rzhao271** [microsoft/vscode#168351]
I switched from a testing profile to my default profile on my Windows machine, and got a message that my macOS machine turned on remote access, even though it's not even on.
![Screenshot showing notification alerting me of a tunnel being ready to use, even though the machine it comes from is not turned on.](https://user-images.githubusercontent.com/7199958/206311058-07809a4d-62ed-4662-8ca9-76192a8f1028.png)

**Comment by aeschli** [comment]
I didn't think of that, good catch.

I use settings sync as a communication channel to learn about other machines connecting to a tunnel.

I guess I need to add a timestamp as well.
