### ISSUE TITLE
Command "Terminal: Clear" and Ctrl+Left make cursur jump to bottom

### ISSUE THREAD

**Issue by h-h-h-h** [microsoft/vscode#168305]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0-insider
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Click menu item "Terminal > New Terminal".
2. Run `echo foo`.
3. Hold Enter to fill the terminal view.
4. Run command `Terminal: Clear` from the command palette.
5. Press up-arrow key to fill the current line with the command `echo foo` again. Don't run it.
6. Press Ctrl+left-arrow key. The cursor jumps to the last line in the terminal view, which is empty, even though we were in the first line.
7. (Hitting Enter runs the command and fills the whole terminal view again.)

**Comment by meganrogge** [comment]
I can reproduce this, but to me it looks like this is bc we're still processing the enters that were pressed before the typing occurred
