### ISSUE TITLE
Support to show "unassigned" keybindings in the release notes editor

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16830]
- VSCode Version: 1.8.0 Insiders
- OS Version: Windows 10

Unlike the website key binding rendering which returns "unassigned" for missing command key bindings, the in-product rendering simply returns the command id string.  To workaround this, we've been manually setting the key binding to "unassigned" in Markdown. This is a poor workaround when a key binding exists for some platforms (ex. Linux) but not others.

Perhaps getKeybindingLabel() could be changed to return "unassigned" instead of 0 for missing key bindings. Note that getKeybindingLabel() is used through out the product so care should be taken that a change doesn't cause a regression somewhere else.

**Comment by alexandrudima** [comment]
@gregvanl @bpasero I don't understand what this issue is about, see also other comment in the commit. Is this about the website, is this about vscode? Can you share a screenshot where something is wrong?

@bpasero You seem to have an understanding, giving to you for now.

**Comment by bpasero** [comment]
I think this is about showing the proper thing in the release notes editor when a keybinding is unassigned. 

@joaomoreno do you know where the release notes editor resolves the keybindings?

**Comment by joaomoreno** [comment]
I can take this.

**Comment by gregvanl** [comment]
I reverted the previous commit to hard-code "unassigned" in the release notes so you can see the difference between the website rendering for unbound commands:
![website-keybinding](https://cloud.githubusercontent.com/assets/12818376/21033336/6fbc344a-bd64-11e6-8a74-7ed90470a12b.png)
and in-product rendering:
![in-product-keybinding](https://cloud.githubusercontent.com/assets/12818376/21033343/79f7eefe-bd64-11e6-9ed4-9b0703d00fd5.png)
