### ISSUE TITLE
CS50 vs code has not been opening

### ISSUE THREAD

**Issue by adedayoprcs** [microsoft/vscode#168345]
My CS50 code space I've just been loading for days now. It's not been coming up

Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by aeschli** [comment]
You need to file this issue against the provider of the CS50 code spaces.
