### ISSUE TITLE
"Open" and "Save As" dialogs globally pop under after first use

### ISSUE THREAD

**Issue by codingthat** [microsoft/vscode#168416]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: codium 1.73.1.22314 from vscodium.com's ppt
- OS Version: Release Linux Mint 20.3 Una 64-bit with MATE 1.26.0

Steps to Reproduce:

1. Run `codium --disable-extensions`
2. Press Ctrl+O
3. Close the "Open file" dialog (hit Escape or click Cancel, doesn't matter how)
4. Press Ctrl+O again
5. "Open file" dialog pops **under** the main codium window and is bold in the task bar, indicating focus and/or modality, yet codium's text cursor is still blinking as if the codium window has the keyboard focus.  However, neither do—regular keystrokes don't affect either window until one clicks the "Open file" taskbar or alt-tabs to it, after which it behaves normally.
6. Steps 3-5 can be repeated indefinitely.  Once you've had one normal dialog, it never pops up normally again.

Other facts:

- Ctrl+O is interchangeable with Ctrl+Shift+S — as soon as one dialog has come up normally, any other system dialog will pop under.
- The first normal dialog behavior is global.  I.e., if I launch two codium instances, I can Ctrl+O in either of them, it doesn't matter which, and after that both of them will exhibit this pop-under behavior.

Version: 1.73.1
Release: 22314
Commit: 14f2d26367b7e8f03ff2352516ba27d6302dd7b1
Date: 2022-11-10T18:19:13.052Z
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic
Sandboxed: No

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/146422
