### ISSUE TITLE
Dragging the minimap slider sometimes doesn't scroll the editor

### ISSUE THREAD

**Issue by bevis-hobbs** [microsoft/vscode#168419]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Windows 11

Steps to Reproduce:

1. Start dragging the minimap slider from the left edge.
2. Drag the mouse to the right of the minimap while scrolling.
3. Notice how the slider on the minimap stops scrolling the editor.

https://user-images.githubusercontent.com/101095063/206411531-0f7820d4-6411-455a-b988-5c7d9d4baf53.mp4

**Comment by alexdima** [comment]
@bevis-hobbs Do you see any errors in developer tools? (Help > Toggle Developer Tools)

**Comment by bevis-hobbs** [comment]
@alexdima No, I don't see any errors in the developer tools. 
I think it's caused by a really annoying feature of windows that is standard across all scrollbars. This explains the feature: https://ux.stackexchange.com/questions/55623/why-do-scrollbars-revert-to-original-scroll-distance-when-mouse-is-dragged-sidew
It seams strange that in VSCode the minimap slider snaps back even when the mouse is still on the minimap slider. I think you should either increase the buffer zone referred to in the link, to make sure that the minimap slider never snaps back when the mouse is still on the slider while dragging, or completely remove the snap back feature which is how it is on macOS: https://superuser.com/questions/1635460/win10-annoying-back-snapping-of-the-scroll-slider
