### ISSUE TITLE
Completions list displays never-ending "loading..." when "Configure Excludes" warning is enabled

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16843]
Testing #16534

When TS gets disabled, the user's focus is on the completion list, not on the status bar - we should provide better text in the completions list to warn the user that those completions are never going to appear, no matter how long they wait (e.g. what if we displayed "Completions not available", and a hyperlink to "Configure Excludes"?)

![image](https://cloud.githubusercontent.com/assets/762848/20982852/0e2f3bc8-bc6f-11e6-9796-d55814f99654.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by mousetraps** [comment]
Also, it could be that it was actually loading something, but I did wait 30 seconds, to no avail - this is with two copies of the vscode node_modules directories in the project.

**Comment by mjbvz** [comment]
Closing in favor of #15209
