### ISSUE TITLE
setting "explorer.autoRevealExclude" doesn't work

### ISSUE THREAD

**Issue by tjx666** [microsoft/vscode#168408]
https://user-images.githubusercontent.com/41773861/206392292-65648cac-824e-49e4-aaff-e49a41ce98ca.mov

reproduce:
`
1. add setting: `"explorer.autoRevealExclude": {}`
2. open one file under `node_modules`
3. Click `Refresh Explore` icon in explorer`, but not work

```
Version: 1.74.0 (Universal)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:43:37.594Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.1.0
Sandboxed: No
```

**Comment by tjx666** [comment]
@gjsjohnmurray No, I think this setting should behave like other setting for example files.exclude

**Comment by gjsjohnmurray** [comment]
> No

Doesn't my suggestion work for you?

Or are you saying that you don't think that solution is acceptable?

**Comment by lramos15** [comment]
I definitely agree this is a bug and an empty object should not still process the defaults. For now please use the false workaround that @gjsjohnmurray pointed out until a fix can be made.

**Comment by lramos15** [comment]
Unfortunately this is as-designed. When using object-value settings we merge them and this includes merging the defaults. This can be seen better in the Settings UI when you delete the default entries. While I agree this can be confusing, we cannot fix it just for this setting and would have to change how all object value settings work which is not a refactor we're willing to undergo at this time.
