### ISSUE TITLE
markdown can't recognize record type

### ISSUE THREAD

**Issue by slowjams** [microsoft/vscode#168449]
Does this issue occur when all extensions are disabled?: No

- VS Code Version:  1.74.0
- OS Version:  Windows 10

Steps to Reproduce:

```C#
public record Student(string FirstName, string LastName); 
public record Teacher(string FirstName, string LastName); 
```

![image](https://user-images.githubusercontent.com/23098860/206459702-49cd4366-7ddd-4dc1-a1c7-af5a0ebde4af.png)

you can see that markdown doesn't really support `record` type, so there is no highlight on the keywords such as `string`, `public` and `record` keywords

**Comment by mjbvz** [comment]
Looks like the same happens in a normal c# filea:

![Screenshot 2022-12-08 at 11 28 37 AM](https://user-images.githubusercontent.com/12821956/206549417-f525aa97-7005-42d5-9d0a-aebf1b30d510.png)

**Comment by alexr00** [comment]
Upstream issue: https://github.com/dotnet/csharp-tmLanguage/issues/242
