### ISSUE TITLE
Parameter hints are dark black for me now

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#168403]
I think it used to be a lighter gray:

<img width="797" alt="image" src="https://user-images.githubusercontent.com/900690/206375982-042a41df-8035-48ce-9553-63d606a6c362.png">

**Comment by hediet** [comment]
This looks normal. Do you mean the tooltip?

**Comment by bpasero** [comment]
No this:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/900690/206476112-7f4b7700-95d7-4498-b005-214cdc0e848e.png">

Compared with stable:

<img width="555" alt="image" src="https://user-images.githubusercontent.com/900690/206476276-861feb63-b06d-4d73-bfed-f5c53fa7ad61.png">
