### ISSUE TITLE
enableProjectDiagnostics problem

### ISSUE THREAD

**Issue by thealjey** [microsoft/vscode#168410]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: macOS 13.0.1

Steps to Reproduce:

1. enable the "typescript.tsserver.experimental.enableProjectDiagnostics" setting

With the feature enabled typescript is unable to find builtin "node:" (eg "node:path") modules or their corresponding type declarations.
And for the packages installed with npm and shipped with d.ts files it also says that type declarations are not found and suggests installing a "@types/" package.

With the feature turned off everything works just fine.

**Comment by mjbvz** [comment]
This feature is experimental and is not going to be finalized because of issues like this (and it is also not worth iterating on further because it is a dead end)

The issue tracking its replacement is #13953
