### ISSUE TITLE
Git Status Updates Are Blocking

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#168453]
* Enable Auto-Save
* Create a git repo (using powershell):
```
git init

for ($i = 0; $i -lt 1000; $i++) {
$fileName = New-Guid
New-Item -ItemType File -Path $fileName
}
```

* Open the scm view, notice 1k untracked files
* Open a file and type

This causes the attached profile. Notice that every time the file is written to disk, the UI freezes for ~200ms. For more files this is even slower.

[Profile-20221208T144120.zip](https://github.com/microsoft/vscode/files/10185892/Profile-20221208T144120.zip)

![image](https://user-images.githubusercontent.com/2931520/206461943-bb14f076-63cb-4024-bee1-4f139db1721a.png)

**Comment by lszomoru** [comment]
The Insiders (2023-04-25) contains some improvements to the Source Control changes list.
@hediet, could you please retest the scenario and let us know if you are still seeing such long blocking time slices.
