### ISSUE TITLE
November 2022 Recovery 1

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#168456]
- [x] Create a milestone `November 2022 Recovery 1` **@aeschli**
- [x] Bump the version number **@aeschli**
- [ ] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22November+2022+Recovery+1%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [ ] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [ ] Initiate `insiders` build from `main`
- [ ] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@aeschli**
- [x] Issues are verified on `stable` build and the `verified` label is added **@aeschli**
- [x] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@aeschli**
- [x] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [x] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit @hediet 
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit @hediet 
    - [x] signed installer 64-bit 
    - [x] signed user installer 64-bit
    - [x] zip 64-bit 
    - [x] server 64-bit 
    - [x] cli 64-bit
  - [x] Windows ARM64 @sandy081 
    - [x] signed installer ARM64 
    - [x] signed user installer ARM64 
    - [x] zip ARM64 
    - [x] cli ARM64
  - [x] macOS
    - [x] Intel (including Universal & Server) @isidorn 
    - [x] cli Intel @isidorn 
    - [x] Apple Silicon (including Universal & Server)  @sandy081 
    - [x] cli Silicon @sandy081 
  - [x] Linux x64 @aeschli 
    - [x] deb 
    - [x] rpm
    - [x] archives
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`)
    - [x] cli
  - [x] Linux server @joaomoreno 
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
    - [x] ARM64 Alpine
- [ ] Publish website **@gregvanl**
- [x] Publish stable build **@aeschli**
- [ ] Create an official release **@aeschli**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [ ] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@aeschli**

**Comment by microhobby** [comment]
I already got a new version `1.74.1` but there is no new release on https://github.com/microsoft/vscode/releases

I think first of all, before we have a new version released on the product website it should be released here in the open source project.

**Comment by aeschli** [comment]
Release is now also created.

Thanks everyone for the help!
