### ISSUE TITLE
Quick pick is broken in insiders

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#168425]
Steps to Reproduce:

1.  Open theme picker
2.  Select any theme

🐛 Nothing happens

**Comment by aeschli** [comment]
After `onDidAccept`, I new also get a `onDidChangeActive` with empty active

**Comment by bpasero** [comment]
Maybe related? https://github.com/microsoft/vscode/issues/168402

**Comment by TylerLeonhardt** [comment]
Yes this appears to have happened yesterday. This change is suspicious:
https://github.com/microsoft/vscode/commit/a76d8ef33243bdc9b41c679268c70495f2211478
