### ISSUE TITLE
Terminal rendering problem

### ISSUE THREAD

**Issue by ansidev** [microsoft/vscode#168458]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: November 2022 (version 1.74.0)
- OS Version: macOS 12.6.1

Steps to Reproduce:

1. Install VS Code 1.74.0.
2. Open VSCode.
3. Open the integrated terminal.

Issue:

The cursor position is not right. The only case that the cursor is at the right position is: the sidebar is opening + half size VSCode window.

Video:

https://user-images.githubusercontent.com/6688235/206469319-53567fdc-4dbf-45bf-a7f2-7b5a836e6baf.mov

IMO, this is an annoying issue and should be fixed as soon as possible.

P/s: This issue does not exist in v1.73.1.

**Comment by dee-me-tree-or-love** [comment]
Tunning in as I have the same experience as @ansidev. 
Running VS Code on `macOS 13.0.1`. The half-size workaround works for me too. 👍

**Comment by ansidev** [comment]
Currently, I'm using [starship](https://starship.rs) with this [config](https://github.com/ansidev/starship-primer).

It works on 1.73.1 and doesn't work on 1.74.0.

I switch to the default starship config (empty config file) and the problem was resolved.

By the way, this issue still needs to be fixed.

**Comment by ProfSchimd** [comment]
Since updating to VS Code 1.74.0, I'm experiencing a problem that I think relates to this issue, when a command typed on the terminal wraps into a new line, the first line disappears and trying to moving the cursor back points to a position the is different from what the cursor actually shows.

I'm running VS Code 1.74.0 on Mac OS 13.0.1 with zsh 5.8.1 (using oh-my-zsh and various plugins).

**Comment by Tyriar** [comment]
Maybe related to https://github.com/microsoft/vscode/issues/166936

**Comment by Tyriar** [comment]
I can't repro on mac/zsh/oh-my-zsh defaults with that starship config.

If you still hit this on the [latest insiders](https://code.visualstudio.com/insiders/) can you run the `toggle escape sequence logging` command from the command palletecommand and press enter in the terminal to print the bad prompt, and paste the logs here?

**Comment by ansidev** [comment]
> I can't repro on mac/zsh/oh-my-zsh defaults with that starship config.
> 
> If you still hit this on the [latest insiders](https://code.visualstudio.com/insiders/) can you run the `toggle escape sequence logging` command from the command palletecommand and press enter in the terminal to print the bad prompt, and paste the logs here?

@Tyriar

1. IMO, you shouldn't use OMZ and Starship together.
2. After upgrading VSCode Stable to v1.74.2, it seems that this issue was resolved. Therefore, I guess one or some of [these issues](https://github.com/microsoft/vscode/issues?q=is%3Aissue+is%3Aclosed+milestone%3A%22November+2022+Recovery+2%22+sort%3Aupdated-desc) resolved this one. IMO, it might be #169142.
3. In case you need log, please download it [here](https://github.com/microsoft/vscode/files/10310514/vscode-term.log).

**Comment by Tyriar** [comment]
@ansidev that actually makes sense that it is https://github.com/microsoft/vscode/issues/169142. I think there was a race because of the slow windows resizing that caused the pty to get out of sync and zsh to send the wrong instructions.
