### ISSUE TITLE
[Feature] Copy entire output from Debug Console

### ISSUE THREAD

**Issue by MarkPieszak** [Microsoft/vscode#16841]
- VSCode Version: **1.7.2**
- OS Version: **Windows**

Steps to Reproduce:

*  Try `Ctrl-A` so you can select everything to copy, 
*  Or try highlighting and scrolling in the Debug Console output to get everything.

Either situation *won't* work you can only select by highlighting text that's currently visible within the Output window in the debug console. Ctrl-A (select all) doesn't work in the debug window for some reason either.

It'd be great to be able to either have a button, or just be able to do Ctrl-A (whichever) so you could copy/paste and look through some large output that came out.

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/2163

**Comment by MarkPieszak** [comment]
Thank you @isidorn apologies, looked through similar issues didn't see that one!

**Comment by isidorn** [comment]
@MarkPieszak no problemo
