### ISSUE TITLE
Sth we have in old Eclipse - double click on tab/feature title

### ISSUE THREAD

**Issue by jkowalskiqwerty** [microsoft/vscode#168413]
Type: <b>Feature Request</b>

When I double click e.g. Console tab in Eclipse, this Console expands to entire window. 
After second double click, things are going back to previous state.

Today dbl click to e.g. Terminal header just collapses it, we still have "V" arrow for collapsing.

VS Code version: Code 1.73.1 (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T04:27:29.066Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

**Comment by sbatten** [comment]
duplicate https://github.com/microsoft/vscode/issues/47661
