### ISSUE TITLE
Installed extensions not visible in sidebar

### ISSUE THREAD

**Issue by mateeni-dev** [microsoft/vscode#168409]
Type: <b>Bug</b>

None of the four extension sub-sections show anything. `Installed`, `Recommended`, `Enabled`, `Disabled` all are blank when expanded. My extension settings are preserved however, and enabled extensions also work fine, just not visible.

I have tried disabling all extensions but that doesn't solve the issue. Sometimes I can force some of the extensions to become visible by searching in the market place. 

What has worked for me:
1. Search for an `Installed` and `Enabled` extension in the marketplace.
2. Open the details view of the extension (click on the extension in the presented list basically).
3. Now clear the search and expand `Enabled` extensions in the sidebar.
4. `Enabled` extensions now become visible again.

_(here extension is installed but disabled, see the sidebar)_
![Screenshot 2022-12-08 124337](https://user-images.githubusercontent.com/36093197/206389485-9e3977b1-2c80-408a-bd99-65eafa790eb5.png)

_(here extension is installed and enabled, see the sidebar)_
![Screenshot 2022-12-08 124601](https://user-images.githubusercontent.com/36093197/206391588-f72f3c9f-6d4e-4e77-af6e-338aa47ae2f8.png)

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
codespaces|Git|1.13.4
copilot|Git|1.62.7527
rest-client|hum|0.25.1
dotenv|mik|1.0.1
mongodb-vscode|mon|0.9.5
vscode-azureresourcegroups|ms-|0.5.6
vscode-cosmosdb|ms-|0.19.2
vscode-docker|ms-|1.23.1
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
azure-account|ms-|0.11.2
remote-explorer|ms-|0.0.2
material-icon-theme|PKi|4.22.0
material-product-icons|PKi|1.4.1
JavaScriptSnippets|xab|1.8.0

</details>

**Comment by akalitenya** [comment]
Same issue. Extensions lists are empty when working with .devcontainer project.

**Comment by sandy081** [comment]
Wondering for all of you, extensions are running but are not shown in the UI? And may I know if reloading the window helps?

**Comment by sandy081** [comment]
@mateeni-dev Are you able to reproduce this consistently?

**Comment by akalitenya** [comment]
@sandy081 Reloading window or close/open vscode doesn't help. Extensions seems to work fine, but lists are empty.

If extensions lists were closed on previous vscode session. Then to make it temporary work I need to:
1) Open vscode
2) Open Extensions tab
3) Expand each of extensions lists
4) Press Refresh icon

**Comment by mateeni-dev** [comment]
@sandy081 I wouldn't say 100% because once or twice they seem to show up fine, but yes pretty much the same story 9/10 times. I open the editor, extensions are blank in UI but still running, and if I need to see them then repeat the 4 steps as described above.

About reloading the window, same story again.

Some more info just in-case it helps - This started happening in the `insiders` version `1.74`, probably 3 or so weeks ago. Also tested in `1.75` just now, same issue there as well.

**Comment by akalitenya** [comment]
For me. If extensions lists were open on previous vscode session. Then they will be shown as usual (no issue) when you open new vscode session.

**Comment by mateeni-dev** [comment]
> For me. If extensions lists were open on previous vscode session. Then they will be shown as usual (no issue) when you open new vscode session.

Huh, guess that explains why it was working once or twice for me. It does that yes, can confirm.

**Comment by mateeni-dev** [comment]
local window for me

> Can you please enable log level to trace and provide me following logs when this happen?

ah, can't seem to find any setting for log level, could you give me a hint :sweat_smile:

**Comment by sandy081** [comment]
Please use the command `F1 > Set Log Level...` to configure log level.

**Comment by sandy081** [comment]
Could be a duplicate of https://github.com/microsoft/vscode/issues/168404

May I know if the extensions views/sections are collapsed? Can you please do following and let me know if it worked?

- Expand the extensions views/sections and reload the window?

**Comment by mateeni-dev** [comment]
took me a while to respond, sorry

> Could be a duplicate of #168703

Yes, had the exact same behavior on my side as far as I can tell. The issue seems to have been fixed in `1.74.1`

> May I know if the extensions views/sections are collapsed? Can you please do following and let me know if it worked?
> 
>     * Expand the extensions views/sections and reload the window?

Not that it will help now as my problem is gone, but yes this did work for me earlier

Thanks for looking into this 🥇

**Comment by vamsi633** [comment]
![image](https://user-images.githubusercontent.com/92721694/213978435-23ebad90-c7e5-4292-97d6-3e9b1b442cd0.png)

**Comment by vamsi633** [comment]
i can't see any off my installed or search extensions in the market place. when i search something i get this warning

**Comment by vamsi633** [comment]
![image](https://user-images.githubusercontent.com/92721694/213980647-5dd09c0f-10b6-4c72-9cdc-bf2c021d6d53.png)

**Comment by vamsi633** [comment]
> Type: Bug
> 
> None of the four extension sub-sections show anything. `Installed`, `Recommended`, `Enabled`, `Disabled` all are blank when expanded. My extension settings are preserved however, and enabled extensions also work fine, just not visible.
> 
> I have tried disabling all extensions but that doesn't solve the issue. Sometimes I can force some of the extensions to become visible by searching in the market place.
> 
> What has worked for me:
> 
> 1. Search for an `Installed` and `Enabled` extension in the marketplace.
> 2. Open the details view of the extension (click on the extension in the presented list basically).
> 3. Now clear the search and expand `Enabled` extensions in the sidebar.
> 4. `Enabled` extensions now become visible again.
> 
> _(here extension is installed but disabled, see the sidebar)_ ![Screenshot 2022-12-08 124337](https://user-images.githubusercontent.com/36093197/206389485-9e3977b1-2c80-408a-bd99-65eafa790eb5.png)
> 
> _(here extension is installed and enabled, see the sidebar)_ ![Screenshot 2022-12-08 124601](https://user-images.githubusercontent.com/36093197/206391588-f72f3c9f-6d4e-4e77-af6e-338aa47ae2f8.png)
> 
> VS Code version: Code 1.74.0 ([5235c6b](https://github.com/microsoft/vscode/commit/5235c6bb189b60b01b1f49062f4ffa42384f8c91), 2022-12-05T16:38:16.075Z) OS version: Windows_NT x64 10.0.22621 Modes: Sandboxed: No
> 
> System Info
> Extensions (21)

i can't even see the installed extension.when i search
