### ISSUE TITLE
The text goes beyond the window

### ISSUE THREAD

**Issue by Risurz** [Microsoft/vscode#1684]
Open any text file and resize window in the horizontal direction.

![vscode_bug_textgoesbeyondwindow](https://cloud.githubusercontent.com/assets/6478549/12028004/3b0e291c-adfa-11e5-91ec-5e277116971b.png)

**Comment by alexandrudima** [comment]
@Risurz This is to be expected when using a non-monospace font, as we compute the wrapping cut points ourselves using an approximation for each character width.

However, I see that you are using a monospace font, I'm wondering what Windows version you're on and if you have made other changes to the font family in the settings. I'm also wondering if you can reproduce if you turn `renderWhitespace` to `false` ?

Thank you!

**Comment by Risurz** [comment]
Windows 10 Professional x64 with last updates.
I don't change any font settings. This is Consolas font as I understand. I have a same problem if I specify Lucida Console font family.
Disable renderWhitespace no change effect.
![thetextbeyondthewindow-wsoff](https://cloud.githubusercontent.com/assets/6478549/12362737/263aa684-bbef-11e5-8daa-6cc6d7bd9e0a.png)
Comments out of window not much (1-2 pixels), as I understand, this because text have italic style,

**Comment by Risurz** [comment]
With Segoe UI font family text displayed as if horizonal window size have abt 4/5 of its real size.
![thetextbeyondthewindow](https://cloud.githubusercontent.com/assets/6478549/12363216/cf199772-bbf1-11e5-8015-ce32f162bc18.png)

**Comment by alexandrudima** [comment]
I could not reproduce using Consolas.

Let's track wrapping + non-monospace fonts in #12421
