### ISSUE TITLE
无法预览服务器上的图像文件

### ISSUE THREAD

**Issue by soaprockets** [microsoft/vscode#168429]
Type: <b>Bug</b>

无法预览服务器上的图像文件

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19043
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.15.0-180-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.75GB free)|
|Process Argv|--disable-gpu --crash-reporter-id bc72b38c-eabe-4331-8c35-e1691de6a6eb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: 腾讯云v100_2|
|OS|Linux x64 4.15.0-180-generic|
|CPUs|Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz (10 x 2500)|
|Memory (System)|39.29GB (35.63GB free)|
|VM|0%|
</details><details><summary>Extensions (40)</summary>

Extension|Author (truncated)|Version
---|---|---
remotehub|Git|0.48.0
vsc-python-indent|Kev|1.18.0
vscode-language-pack-zh-hans|MS-|1.74.12070927
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.92.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
azure-repos|ms-|0.24.0
remote-explorer|ms-|0.0.2
remote-repositories|ms-|0.26.0
python-extended-snippets|tus|0.0.1
jinja|who|0.0.8
python-image-preview|076|0.1.2
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
code-runner|for|0.11.8
remotehub|Git|0.48.0
nbpreviewer|jit|1.2.2
vsc-python-indent|Kev|1.18.0
vscode-docker|ms-|1.23.1
vscode-language-pack-zh-hans|MS-|1.74.12070927
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-repos|ms-|0.24.0
remote-repositories|ms-|0.26.0
autodocstring|njp|0.6.1
jupyter-notebook-vscode|sam|0.0.2
vscode-zipexplorer|sle|0.3.1
python-extended-snippets|tus|0.0.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
jinja|who|0.0.8

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723
ejf25101:30620729

```

</details>

**Comment by planck-fanqi** [comment]
你看一下是不是 #168387 这种情况。

**Comment by Firestar-Reimu** [comment]
translation: cannot preview pictures on servers.

**Comment by Tyriar** [comment]
Still not clear what you mean, if it's the same as https://github.com/microsoft/vscode/issues/168387 then it's tracked there.
