### ISSUE TITLE
Error while opening a PR in web

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#168423]
Opened this [link](https://insiders.vscode.dev/github.com/microsoft/vscode/pull/168422) and saw following 

![image](https://user-images.githubusercontent.com/10746682/206419528-755b6254-4d59-422d-aad5-2090db686b39.png)

**Comment by alexr00** [comment]
Do you have the full text of the error?

**Comment by sandy081** [comment]
![image](https://user-images.githubusercontent.com/10746682/206430801-5a70b9e8-0151-4dfe-adf7-a55c8f56adbf.png)

**Comment by mjbvz** [comment]
I suspect this was already fixed. There are still cases where the service worker may not load, such as when third party cookies are disabled. However we now at least have more helpful error messages for those cases
