### ISSUE TITLE
request the support of chrome flag `--disable-high-precision-scrolling`

### ISSUE THREAD

**Issue by nahso** [microsoft/vscode#168424]
The first scroll event is always ignored in GTK3 based applications under Xorg, see [here](https://bbs.archlinux.org/viewtopic.php?id=223470). It looks like xinput2 causing this problem. To deal with this, one can pass the `--disable-high-precision-scrolling` flag to chromium or other electron based applications to disable xinput2. But vscode doesn't support the flag.

Can you support this flag in vscode?

**Comment by deepak1556** [comment]
Flag is supported by the [chromium version](https://source.chromium.org/chromium/chromium/src/+/refs/tags/102.0.5005.167:ui/events/devices/x11/device_data_manager_x11.cc;l=140-146) VSCode ships, can you clarify how you confirmed the flag is not supported ?

**Comment by nahso** [comment]
I ran `code --disable-high-precision-scrolling` yesterday and got a warning: `Warning: 'disable-high-precision-scrolling' is not in the list of known options, but still passed to Electron/Chromium`, and vscode itself did ignored the first scroll event. 
But today I tried this command again and vscode worked perfectly. It is so weird, but thank you for your replay.

**Comment by deepak1556** [comment]
Yeah you can ignore the warning, it just means that VSCode does not understand the flag but will pass it down to the runtime if the runtime supports. Thanks for confirming.
