### ISSUE TITLE
Download of the vscode cli via the terminal (wget) does not work - returns a 404

### ISSUE THREAD

**Issue by IvoLeist** [microsoft/vscode#168445]
Dear vscode team,

I was eager to try the new(?) vscode cli today to set up a tunnel to my virtual machine.
Hoping that it fixes my download/update extensions issues with the currently used `code-server`. 
However, it looks like the direct download link is not wget friendly? 
See error report below.

Does this issue occur when all extensions are disabled?: not applicable

- VS Code Version:  not applicable
- OS Version: CentOS Stream 8 x86_64

Steps to Reproduce:

1.  Open in your browser: https://code.visualstudio.com/docs/?dv=linux64cli
2.  Copy the link address of "Try this [direct download link.](https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64)"
3. Use wget in the virtual machine to download the cli: 
`wget https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64`

wget-log output:
> https://code.visualstudio.com/sha/download?build=stable
> Resolving code.visualstudio.com (code.visualstudio.com)... 13.69.68.34
> Connecting to code.visualstudio.com (code.visualstudio.com)|13.69.68.34|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found

**Comment by connor4312** [comment]
`https://code.visualstudio.com/sha/download?build=stable&os=cli-alpine-x64` should be wrapped in quotes: your shell is interpreting the `&` as a special sequence.

@rzhao271 we should probably have 'actual direct' download links to the CDN, or have a copyable CLI command for users.

**Comment by IvoLeist** [comment]
Thanks for the quick answer :) This indeed resolved the issue for me.

**Comment by rzhao271** [comment]
Closing this issue to avoid a duplicate with the internalbacklog issue
