### ISSUE TITLE
Documentation for "exclude" might frighten some JS devs

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16849]
Testing #16534

The piece on glob patterns mentions TypeScript 2.0, which makes sense if you know how the language service works, less sense if you don't. 

![image](https://cloud.githubusercontent.com/assets/762848/20984135/ec3f6e98-bc73-11e6-9f23-b5cf3774e18e.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by mjbvz** [comment]
These come from schema store: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/jsconfig.json

The schema definition was mostly written by people on TS as far as I can tell, so I recommend talking to them or submitting a PR with the suggested fix against schema store directly. 

Closing as upstream
