### ISSUE TITLE
Reduce Animations and Fades, popping in and out of visual elements.

### ISSUE THREAD

**Issue by stephenmartindale** [microsoft/vscode#168464]
Please provide an option to disable the fading-in and -out of borders and lines and backgrounds in the "Problems" pane, in the name of reducing motion and distraction in the U.I. Watch as I mouse about over this:

https://user-images.githubusercontent.com/6370145/206474474-e3e8b972-e007-450a-a0d2-e1bb34510195.mp4

1. The most egregious issue is the fading out of column and row borders when the pane is not focussed or under the mouse – at the very least, that should be optional.

   - Choosing the table view does rather suggest that the user wishes to see rows and columns so I really do not understand why hiding column and row borders ever would make sense?

3. Actual ***errors*** in the problems pane even have their icon changed to a "light-bulb" when one either selects them or mouses over them. Do they cease to be errors?

   - In filing this feature request, I worked out that that lightbulb becomes interactive and provides "fixes" but that, too, is a truly awful UX.

I have *Workbench: Reduce Motion* set to **on**…

```json
"workbench.reduceMotion": "on"
```

… and I have that on for a reason. I spend FAR FAR FAR too long in front of code to have flashing and flashy-animations distracting me all day.

There are still very many annoying animations and fade-effects in Visual Studio Code. Please provide options to disable them. Do it in the name of accessibility: particularly the neuro-diverse are sorely and negatively affected by these.

**Comment by sandy081** [comment]
@joaomoreno  / @lszomoru Is there a list or tree setting or colour customisation for this?

**Comment by stephenmartindale** [comment]
> @joaomoreno / @lszomoru Is there a list or tree setting or colour customisation for this?

I could believe that that might help reduce the distractions but would a customisation be able to prevent the fade-out of the lines, though? :doubtful:

**Comment by joaomoreno** [comment]
Created table bug: https://github.com/microsoft/vscode/issues/169120

**Comment by sandy081** [comment]
@joaomoreno May I know if #169120 also fixes this issue? Or shall I have to adopt it specially in problems table?

**Comment by joaomoreno** [comment]
The user reported two issues:

> 1. [...] the fading out of column and row borders when the pane is not focussed or under the mouse – at the very least, that should be optional.
> 2. Actual _**errors**_ in the problems pane even have their icon changed to a "light-bulb" when one either selects them or mouses over them. Do they cease to be errors?

Issue #169120 addresses the first one.

**Comment by sandy081** [comment]
Oh yeah, I was tricked by summary and first few lines of description. 

I do not have plans to change that behaviour, it is also same in the editor.
