### ISSUE TITLE
version 1.74

### ISSUE THREAD

**Issue by Ammar-MediaPlus-Kutubee** [microsoft/vscode#168404]
Type: <b>Bug</b>

i just dowloaded vsCode version 1.74.0  

and all my Extensions  are not showing in Extension tabs , event tho they are still running . And the searching for the extension is running fine and showing the results.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.74.2-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.91GB (5.64GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/ammar/kutubeeweb21 --remote=wsl+Ubuntu --crash-reporter-id be4286ca-e7f8-46c9-8cde-d69ac1243dbc|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.74.2-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1799)|
|Memory (System)|7.71GB (5.57GB free)|
|VM|0%|
</details><details><summary>Extensions (81)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
es7-react-js-snippets|dsz|4.4.3
python-ultisnippets|eli|2.7.0
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
vsc-python-indent|Kev|1.18.0
theme-monokai-pro-vscode|mon|1.2.0
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.72.0
material-icon-theme|PKi|4.22.0
vscode-icons|vsc|12.0.1
jinja|who|0.0.8
Bookmarks|ale|13.3.1
vscode-sqlite|ale|0.14.1
arepl|alm|2.0.4
jsoncrack-vscode|Ayk|1.0.8
vscode-django|bat|1.10.0
better-toml|bun|0.3.2
turbo-console-log|Cha|2.6.2
path-intellisense|chr|2.8.3
regex|chr|0.4.0
coderoad|Cod|0.17.2
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
python-preview|don|0.0.4
githistory|don|0.6.19
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
typescript-notebook|don|2.0.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.1.1
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
python-ultiextension-pack|eli|1.6.0
python-ultisnippets|eli|2.7.0
prettier-vscode|esb|9.10.3
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
copilot|Git|1.62.7527
vscode-pull-request-github|Git|0.56.0
live-sass|gle|5.5.1
gc-excelviewer|Gra|4.2.56
grepper|Gre|0.0.7
todo-tree|Gru|0.0.220
rest-client|hum|0.25.1
nbpreviewer|jit|1.2.2
vscode-text-pastry|jkj|1.3.1
svg|joc|1.4.23
vscode-colorize|kam|0.11.1
vsc-python-indent|Kev|1.18.0
calculator|lix|0.1.1
rainbow-csv|mec|3.4.0
python-path|mge|0.0.14
mongodb-vscode|mon|0.9.5
theme-monokai-pro-vscode|mon|1.2.0
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.13.6
autodocstring|njp|0.6.1
indent-rainbow|ode|8.3.1
material-icon-theme|PKi|4.22.0
heroku-command|pko|0.0.8
polacode|pnp|0.3.4
vscode-css-peek|pra|4.2.0
vscode-thunder-client|ran|2.1.2
LiveServer|rit|5.7.9
git-autoconfig|shy|0.0.2
wav-preview|suk|2.0.4
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-icons|vsc|12.0.1
quokka-vscode|Wal|1.0.515
jinja|who|0.0.8
vscode-import-cost|wix|3.3.0

(6 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723
ejf25101:30620729

```

</details>

**Comment by sandy081** [comment]
Can you please reload the window and see if it works?

**Comment by Ammaro173** [comment]
> Can you please reload the window and see if it works?

i did reload , and i closed the editor and re-open it  ( all local installed = 0 , WSL installed =0 , recommended =0 )
and if you go to {Show all running extension} you will be able to see them.

**Comment by sandy081** [comment]
Do you see any errors in the following logs, also please share them?

- F1 > Open View... > Shared
- F1 > Open View... > Window
- F1 > Open View... > Remote
- F1 > Toggle Developer Tools > Console/Network

**Comment by sandy081** [comment]
> all extensions started working

Do you mean you see extensions now?

**Comment by Ammaro173** [comment]
> > all extensions started working
> 
> Do you mean you see extensions now?

yes i can see them.

**Comment by sandy081** [comment]
Can you please share a gif of reloading the window...

Please enable log level to trace and share all following logs?

F1 > Open View... > Shared
F1 > Open View... > Window
F1 > Open View... > Remote
F1 > Open View... > Extension Host
F1 > Open View... > Remote Extension Host
F1 > Toggle Developer Tools > Console/Network

It seems you are using remote, may i know if you are not seeing remote extensions or also local extensions?

**Comment by Ammaro173** [comment]
what it seems like the problem was closing VsCode and re-opening it , doesnt solve the problem ,
 but when i opened Console/Network  , i was able to press f5 or ctrl + r to do a refresh or reload , and thats when my problem was solved .

- also my other pc had the same problem .. i did the same steps i just mentioned above and solved

**Comment by sandy081** [comment]
May I know if the extensions views/sections are collapsed? Can you please do following and let me know if it worked?

- Expand the extensions views/sections and reload the window?
