### ISSUE TITLE
Most commonly used settings cause workspace problems

### ISSUE THREAD

**Issue by kieferrm** [Microsoft/vscode#16842]
- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:05:09.124Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-docker|PeterJausovec|0.0.8|
|theme-toothpaste|aalaap|0.0.1|
|vscode-eslint|dbaeumer|1.2.0|
|githistory|donjayamanne|0.1.2|
|tslint|eg2|0.6.7|
|vscode-npm-script|eg2|0.1.2|
|vsc-travis-ci-status|felixrieseberg|1.0.5|
|csharp|ms-vscode|1.5.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|Ruby|rebornix|0.10.3|
|java|redhat|0.0.7|
|kustovscode|seanmcbreen|0.0.1|
|autoimport|steoates|1.2.2|
|gitblame|waderyan|1.3.0|
|vscode-open-in-github|ziyasal|1.2.2|

---

Steps to Reproduce:

1. Open View>Problems
2. Open Code Insiders>Preferences>User Settings

![screen shot 2016-12-07 at 11 12 39 am](https://cloud.githubusercontent.com/assets/4674940/20982753/a92c5c24-bc6e-11e6-9356-d95541fac6d7.png)

All keys that are in the **Most Commonly Used** section are reported as duplicated keys.

**Comment by sandy081** [comment]
Duplicates #16674
