### ISSUE TITLE
Windows Remote Debugger similar to standard Visual Studio.

### ISSUE THREAD

**Issue by pmaciejew** [microsoft/vscode#168440]
It seems that remote debugging does not work with "cppvsdbg" on Windows.

With standard Visual Studio, the user is able to build binaries locally, deploy them on remote machine and debug them remotely. 

VS Code is able to perform remote developing, but it always required to copy source code to target machine, which is not always desired, for example target platform can be only used for testing.

**Comment by roblourens** [comment]
Please file this issue on the cpp extension repo, thanks
