### ISSUE TITLE
Better handling of multiple installed language packs

### ISSUE THREAD

**Issue by colin-grant-work** [microsoft/vscode#168478]
Current behavior: 
1. Install several language packs.
2. Have an update install itself automatically.
3. Start VSCode.
4. See one toast for every installed language.
---
Desired behavior:
4. If multiple language packs are installed, show a toast with a button that brings up the language selection quick pick.
Alternatively, see no toasts, because I'd installed the language packs long ago and would have changed the language if I'd wanted to - but likely they were updated together with the application and so behaved as though they were being installed for the first time.

![image](https://user-images.githubusercontent.com/62660806/206497946-72028bbe-24b9-4808-ac65-11d8e93b348d.png)

**Comment by TylerLeonhardt** [comment]
/duplicate https://github.com/microsoft/vscode/issues/139151

merging with that one since they're fixed in the same part of the code
