### ISSUE TITLE
Transient task validation errors when opening a repo using custom tasks in Codespaces

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode#168494]
## Environment
- VS Code Version: 1.74.0
- OS Version: Debian Bullseye (Codespaces)

## Steps to Reproduce:

1. Go to https://github.com/Azure-Samples/todo-nodejs-mongo 
2. Click the "Use template" green drop-down button and choose "Open in a codespace"
3. Observe as the repo is being opened.

## Expected
There should be no errors.

## Actual 
An error popup saying "There are task errors. See output for details" is flashing a few times. The output window shows something about missing `dotenv` for a second or so, and then it disappears (I haven't been successful in screenshotting it).

## Additional information
- `dotenv` is a custom task type that [Azure Developer CLI](https://github.com/Azure/azure-dev/tree/main/ext/vscode) extension provides. This extension is used by the repo used for the repo, and the tasks.json file in the repo uses `dotenv` custom task in several places.
- Azure Developer CLI extension is installed as part of Codespace creation (is referenced by devcontainer.json). 
- As far as I can tell from the logs indicate that Azure Developer CLI is installed, but not activated during the repo open sequence. In particular, the extension has `onTaskType:dotenv` as one of the activation events listed in `package.json`, but it does not seem that any activation occurs, nor is `dotenv` task run.
- `tasks.json` is not open during Codespaces initialization

My suspicion is that `tasks.json` is being validated early, before Azure Developer CLI extension is installed, and at that time the validation system does not know yet about `dotenv` task type. If that is the case, perhaps it would be better to delay `tasks.json` validation until all extensions required by the repo are installed.

**Comment by karolz-ms** [comment]
@meganrogge I think this might be related to the area you own

**Comment by karolz-ms** [comment]
This might be a dupe of https://github.com/microsoft/vscode/issues/165292, although I do not see the symptoms described in that bug with VS Code 1.74: the Azure Developer CLI extension is installed normally and there is no prompt to install it again. I just see these transient `tasks.json` validation errors now. I will let you decide which bug to keep and which to close.

**Comment by meganrogge** [comment]
Yep @karolz-ms same as #165292
