### ISSUE TITLE
[recent history] Recent devcontainer display string corrupted on Get Started page

### ISSUE THREAD

**Issue by amurzeau** [microsoft/vscode#168564]
- VSCode Version:.
Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

- Local OS Version: Windows 10 22H2
- Remote OS Version: Debian Unstable Linux x86-64
- Remote Extension/Connection Type: SSH + Containers (docker is on the remote SSH host)

- ms-vscode-remote.remote-ssh version: v0.92.0
- ms-vscode-remote.remote-containers version: v0.266.1

Steps to Reproduce:

1. Open a devcontainer on a remote host via SSH (so the tunnel is: Windows Host ==> SSH Remote Linux ==> Docker Container)
2. Close the container and open the Get Started page (via menu Help => Get Started)

The devcontainer name in the recent list is somewhat corrupted:

![image](https://user-images.githubusercontent.com/5435069/206311846-da733ffe-6860-4706-94d9-02393c72466b.png)

I expect the blue link to be `streamlink-debian [Dev Container: Alpine @ ssh://debian64]` instead of `debian64]`.

The cause is that VS Code unconditionally use the part after the last `/` as the blue link:

In Get Started page:

https://github.com/microsoft/vscode/blob/9d1c2920c0d4a433af493b3777b0e8d45088299b/src/vs/workbench/contrib/welcomeGettingStarted/browser/gettingStarted.ts#L858-L864

In quick pick:

https://github.com/microsoft/vscode/blob/9d1c2920c0d4a433af493b3777b0e8d45088299b/src/vs/workbench/browser/actions/windowActions.ts#L219-L230

https://github.com/microsoft/vscode/blob/9d1c2920c0d4a433af493b3777b0e8d45088299b/src/vs/base/common/labels.ts#L441-L450

A workaround is to remove the slashes after `ssh:`.

Does this issue occur when you try this locally?: No
Does this issue occur when you try this locally and all extensions are disabled?: No

**Comment by aeschli** [comment]
Needs to be fixed in the label provider code.

**Comment by zifik** [comment]
I would also like to add that this issue affects the Windows "jump" lists that you can access by right clicking the VSCode icon in your taskbar.  I assume its the same code for both issues, but I wanted to mention it just in case it wasn't.

**Comment by amurzeau** [comment]
If the solution is too complex for a simple fix, can the label be changed to avoid `ssh://` and instead just use `ssh:` for example ?
This would fix this issue before the complete solution (which may involve more API changes).

**Comment by alexr00** [comment]
I tried to test with Windows Host ==> SSH remote **Windows** ==> Docker , but it looks like connecting to a container from a Windows SSH remote doesn't work. I will leave for someone else to test.

**Comment by amurzeau** [comment]
I've tried on Linux, but I can't get the full remote name and only get `foldername [Dev Container]` even when connecting to a container on a remote host via SSH (on VSCode Insider).
I've opened https://github.com/microsoft/vscode-remote-release/issues/8578 for this.
