### ISSUE TITLE
Remove extra vertical padding from title bar when enabled command center

### ISSUE THREAD

**Issue by arjittw** [microsoft/vscode#168573]
When command center is enabled, title bar takes more space vertically and adds vertical padding.
It makes title bar bigger and when hovering at its top it's not command menu is not selected because there a margin at its top

![KXjjGwhC9d](https://user-images.githubusercontent.com/82394184/206688173-ec393afe-e7d1-42d2-8715-7f371a395bd2.gif)

It would be better if its size remains the same.

**Comment by gjsjohnmurray** [comment]
Without the added vertical padding I think it would be harder to resize the window by dragging the edge directly above the command center, and we would no longer be able to move the window by dragging immediately below the command center.

**Comment by arjittw** [comment]
I don't think the bottom margin is useful.
Maybe a compact mode setting for command center would be good

**Comment by sbatten** [comment]
cc @jrieken @daviddossett 

Without the vertical padding this box is very compressed and doesn't look quite right. I don't see us supporting a setting for this, but others may chime in.
