### ISSUE TITLE
[Problems tab] setting to exclude sources

### ISSUE THREAD

**Issue by asportnoy** [microsoft/vscode#168509]
I use the [cSpell](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) extension, which shows errors inline as well as in the "Problems" tab. However, I'd like to hide them in the problems tab. I found that I could filter them out with `!cSpell`, but I'd prefer to have that be in VSCode settings and persist across everything. Could a setting be added for that?

**Comment by sandy081** [comment]
Problems are generated by extensions and as a platform VS Code does not filter any problems generated by the extensions. We expect, extensions to provide such settings so that they wont generate these problems.

**Comment by asportnoy** [comment]
@sandy081 are problems that show up inline reported differently than the problems tab?

**Comment by sandy081** [comment]
No, all of them are generated by the extensions.
