### ISSUE TITLE
change home directory in macOS break settings sync

### ISSUE THREAD

**Issue by arily** [microsoft/vscode#168543]
Type: <b>Bug</b>

1. make sure settings sync is on for an account that is going to be renamed
2. change name and home directory of the account
3. restart and launch vscode, it looks like a fresh start, all extensions are gone but sync is still on
4. install any extension, it will overwrite synced data
5. restore synced settings to a previous point, previously installed extension will be restored
6.  reload window, it will reverses itself to the state in step 3, any installed extensions and ui states between step3 to 5 are lost
7. if vscode tries to sync again, it will overwrites synced data again, this time restore to previous synced data will have no effects anymore. And every time I reload window or restart vscode, it behaves like described in step 6.

afaik the only way to get out of this trouble is to [Clean Uninstall](https://code.visualstudio.com/docs/setup/uninstall#_clean-uninstall) then enable settings sync again.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|15, 19, 24|
|Memory (System)|64.00GB (36.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
project-manager|ale|12.7.0
aya-vue3-extension-pack|Ama|0.0.7
google-cloud-platform-ssh|and|1.0.0
lit-html|bie|1.11.1
vscode-tailwindcss|bra|0.9.1
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
vscode-devtools-for-chrome|cod|0.0.7
gitignore|cod|0.9.0
postcss|css|1.0.9
vscode-markdownlint|Dav|0.48.1
macos-modern-theme|dav|2.3.18
vscode-eslint|dba|2.2.6
vscode-springboot-snippets|dev|1.2.0
githistory|don|0.6.19
javadebugger|don|0.1.5
gitlens|eam|13.1.1
vscode-html-css|ecm|1.13.1
vscode-spring-boot|ecm|0.0.10
RunOnSave|eme|0.2.0
prettier-vscode|esb|9.10.3
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.2
html-snippets|gey|0.2.3
vscode-pull-request-github|Git|0.56.0
todo-tree|Gru|0.0.220
npm-dependency-links|her|1.2.0
headwind|hey|1.7.0
vue-snippets|hol|1.0.4
vscode-npm-dependency|how|1.2.2
theme-macos-classic|hua|1.4.11
output-colorizer|IBM|0.1.2
vscode-postfix-ts|ipa|1.11.3
kubernetes-snippets|ipe|0.1.9
java-properties|ith|0.0.2
batch-rename-extension|Jan|0.0.6
vscode-pegjs-live|joe|0.0.2
springboot-extension-pack|joy|0.0.8
ts-type-expand|kim|0.0.12
vscode-phpfmt|kok|1.0.31
java-spring-extension-pack|loi|0.1.3
i18n-ally|lok|2.8.1
tailwind-sass-syntax|mac|1.3.0
testfile-generator-for-junit|mar|0.0.7
mp-rest-client-generator-vscode-ext|Mic|0.1.2
mp-starter-vscode-ext|Mic|0.2.9
vscode-microprofile-pack|Mic|0.1.3
dotenv|mik|1.0.1
vue-volar-extention-pack|Mis|1.1.5
vscode-docker|ms-|1.23.1
vscode-dotnet-runtime|ms-|1.6.0
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
vscode-remote-extensionpack|ms-|0.23.0
remote-explorer|ms-|0.0.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by sandy081** [comment]
> change name and home directory of the account

Can you please be clear what directories you changed here?

**Comment by arily** [comment]
the user's home directory. in macOS it's /Users/`{here}`.

**Comment by sandy081** [comment]
You have to quit VS Code and clean up the directory. If VS Code is running then it will save the state on shutdown. So please retry by quitting VS Code and then clean up and start VS Code.
