### ISSUE TITLE
selectNextCodeAction custom keybinding not working

### ISSUE THREAD

**Issue by JorgeHerreraU** [microsoft/vscode#168591]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Windows 11 Pro 10.0.22621

Steps to Reproduce:

1. Open keybindings.json 
2. Assign Key as following:
```
    {
        "key": "ctrl+n",
        "command": "selectNextCodeAction",
        "when": "codeActionMenuVisible"
    },
    {
        "key": "ctrl+p",
        "command": "selectPrevCodeAction",
        "when": "codeActionMenuVisible"
    },
```
Had to rollback to previous version to get it to work 1.73.1

**Comment by kubil6y** [comment]
when": "actionWidgetVisible" change to this and it works as expected.
