### ISSUE TITLE
Port forwarding is gone in version 1.74.0

### ISSUE THREAD

**Issue by chemwolf6922** [microsoft/vscode#168585]
Does this issue occur when all extensions are disabled?: Can not do that. (wsl remote is an extension)

- VS Code Version: 1.74.0
- OS Version: windows11 wsl "18.04.6 LTS (Bionic Beaver)"

Steps to Reproduce:
![image](https://user-images.githubusercontent.com/19360522/206702218-9b35ca65-a64a-487b-be8f-874b9f8deccd.png)

1. Ctrl+Shift+P
2. type in port

**Comment by chemwolf6922** [comment]
And the PORTS tab is gone too.

**Comment by alexr00** [comment]
The Ports view has never shown with the WSL Remote extension, as port forwarding is not required when connecting to WSL. The Ports view shows for SSH, Dev Containers, and Codespaces.
