### ISSUE TITLE
UI responses to window resize very slowly on macOS

### ISSUE THREAD

**Issue by haimingz** [microsoft/vscode#168547]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74
- OS Version: macOS 10.13.6

Steps to Reproduce:

1.  Resize the code app window with/without opening a folder/workspace
2. The UI elements response very slowly, taking seconds to reposition, especially when the UI is complex (see the gif).

![2022-12-09 12-14-56](https://user-images.githubusercontent.com/33821265/206622993-8795e746-23e8-4a99-835b-a1a366edb4b6.gif)

This issue does not arise on my PC running Windows 10. 
And it is not fixed in the latest insider build.

**Comment by bpasero** [comment]
Previously reported in https://github.com/microsoft/vscode/issues/165835. Moving to Deepak and labelling Electron based on the discussion there.

@HaimingZ do you also see this on our web version? https://insiders.vscode.dev

**Comment by HaimingZ** [comment]
> Previously reported in #165835. Moving to Deepak and labelling Electron based on the discussion there.
> 
> @HaimingZ do you also see this on our web version? https://insiders.vscode.dev

Hi @bpasero, thanks for your reply! I don't see this issue on the web version.

**Comment by jackpopo** [comment]
I'm having it even without opening any text/file.

https://youtu.be/v0PooTM42jE

**Comment by parejadan** [comment]
@bpasero - switching to `native` definitely suppresses the problem (but I'd argue not actually solve the issue for the titleBarStyle feature people probably prefer on the editor). 

GIF showing issue more problematic when doing split screen: 
![resize-lag](https://user-images.githubusercontent.com/11270882/207919051-4ba725c7-96ee-4e28-a36b-dd43f78d2330.gif)

GIF showing `native` flag being enabled and lag suppressed (split screen):

![no-resize-lag](https://user-images.githubusercontent.com/11270882/207919186-84f502a5-b2e3-44fb-b032-c1425cbbe47b.gif)

**Comment by HaimingZ** [comment]
> 
My test yields the same result as @parejadan. Native titlebar solve the problem for now.

**Comment by deepak1556** [comment]
Thanks for the inputs, we have confirmed the issue on our end. Merging to https://github.com/microsoft/vscode/issues/169142, please follow that issue for updates.
