### ISSUE TITLE
Extension Incorrect locale information provided

### ISSUE THREAD

**Issue by omer-musa-battal** [microsoft/vscode#168583]
Type: <b>Bug</b>

The same issue as in #122081, but the given solution does not work for me.

1. Open Extensions tab in vscode.
2. Click on any extension.
3. See the error: "The editor could not be opened due to an unexpected error: Incorrect locale information provided."

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:47:18.476Z)
OS version: Linux x64 5.15.0-56-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 0, 0|
|Memory (System)|31.02GB (26.83GB free)|
|Process Argv|--unity-launch --crash-reporter-id 62359615-f210-4a1a-b485-c01bd7dc0119|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by rzhao271** [comment]
Some questions:
- Is this a new issue?
- When running the "Configure Runtime Arguments" command, `argv.json` loads. Is there a `locale` key set? If there is, what is its value?
- What is the output of running the `locale` command in a terminal?

**Comment by omer-musa-battal** [comment]
- I am not sure if the issue is new, as I have not tried to install a new extension for a while. I just noticed it today.
- No, `argv.json` file does not contain the word `locale`.
- the output is as follows:
```
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="C.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES="C.UTF-8"
LC_PAPER=en_GB.UTF-8
LC_NAME=en_GB.UTF-8
LC_ADDRESS=en_GB.UTF-8
LC_TELEPHONE=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION=en_GB.UTF-8
LC_ALL=
```

**Comment by rzhao271** [comment]
I was able to repro the issue by setting more language environment variables as `C.UTF-8` in `/etc/locale.conf` on CentOS 7, but that config also prevented my terminal from starting up. I switched to tty2 and noticed that bash couldn't interpret the locale properly, either.

![Screenshot showing bash unable to handle the C.UTF-8 locale](https://user-images.githubusercontent.com/7199958/206784708-116031c4-0a9a-4268-8308-2b3d6d78d7c3.png)

To mitigate the issue, I suggest setting the locale environment variables to something else like `en_GB.UTF-8`.

**Comment by Patchethium** [comment]
For me the same issue appears right after upgrading to 1.74.0 and can be fixed by inserting `"locale"="en"` in `argv.json`.

<details>
<summary> My locale output </summary>

```bash
$ locale
LANG=C.UTF-8
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
```
</details>

**Comment by omer-musa-battal** [comment]
you are right, running the following command:
```
sudo localectl set-locale LANG=en_US.UTF-8
```
and then performing a logout-login resolves the issue.

however, I would rather keep my locale as `C.UTF-8` for various reasons, so I am not closing the issue yet.

**Comment by filbotblue** [comment]
My locale is set to that and I'm still receiving these errors.

![image](https://user-images.githubusercontent.com/96255204/207154086-8ce3396d-d006-496c-89db-28dc61b37d5e.png)

The error I'm seeing

![image](https://user-images.githubusercontent.com/96255204/207154182-9f8f8c18-58d9-4e5c-9689-8b1bdb47af5e.png)

My VSCode version.

![image](https://user-images.githubusercontent.com/96255204/207154270-1af26b85-aec2-4205-9452-e32f062d8102.png)

**Comment by AlexMakesSoftware** [comment]
My vscode just broke today (on ubuntu) with this error on the plugins screen. I believe all I tried to do was log in to my github account to synchronise. I tried signing out (in case this caused the issue) but I still get this error.  I tried removing and then reinstalling vscode.

Can you please take a look at this asap? Thanks.

**Comment by rzhao271** [comment]
Hi, 1.74.1 just got released. Let me know if that fixes this issue.
If it does fix the issue, I will merge this issue to #169114.

**Comment by TH3-S4LM0N** [comment]
On Arch with `visual-studio-code-bin` (aur) and 1.74.1 fixed it for me.

**Comment by omer-musa-battal** [comment]
version 1.74.1 fixed it for me as well.

**Comment by babaric-dev** [comment]
I can confirm 1.74.1 fixed this issue.

**Comment by rzhao271** [comment]
Thanks. Merging to https://github.com/microsoft/vscode/issues/169114
