### ISSUE TITLE
Errors from TextModelResolverService can have PII

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16857]
At https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/services/textmodelResolver/common/textModelResolverService.ts#L84 we throw an error if the resource cannot be found.

The `resource` can have PII and should be scrubbed.

There are 3 ways this can be done

1. Scrub PII before logging the error. Downside is that even the error in the console will not have the resource and we lose out on info that could help in debugging with a user
2. Update the `telemetryService` code to scrub the error. This would need the telemetryservice to be aware of the file pattern in use
3. Use console.log() to log the error and then return rejected promise instead of error

**Comment by jrieken** [comment]
Unsure if this is so important then I initially thought. Also, this isn't a regression and maybe something the workbench should tackle because we need the rejection to make the workbench show a message.

**Comment by bpasero** [comment]
@ramya-rao-a I do not see how this error ends up in telemetry, do you have a path? the text content will be resolved as part of an editor opening (e.g. settings) and in the end the error will bubble up to the user as a message.

I am also fine removing the URI from the message because I think this is a very technical thing and not necessarily helping users ( @joaomoreno might also want to chime in on this error message).

**Comment by joaomoreno** [comment]
Yeah, removing works. We just need to make sure that if an extension opens `foo://bar` and we can't handle it, we're able to tell the user what is it exactly that we can't handle.

**Comment by bpasero** [comment]
@joaomoreno I meant to not have it inside the error at all. I do not see how we can remove PII without knowing what kind of resources are actually being opened. These resources might have very different information compared to normal file paths. 

I am tending to turn this around and react if we find out that we leak PII in telemetry. So far I am not seeing evidence that this could happen when I look at the code path. But I might be wrong.

**Comment by joaomoreno** [comment]
@bpasero I meant it too, when I said _removing works_.

But if the situation were to happen, that a certain `foo://bar` URI can't be handled, what would Code show to the user?

**Comment by bpasero** [comment]
@joaomoreno yeah not much, I am not even sure if we could show the resource scheme. Need some education what is PII and what not.

**Comment by ramya-rao-a** [comment]
@jrieken Nope, not a regression. 

@bpasero 
Example of this particular error reaching error telemetry : https://ticino-errors.azurewebsites.net/?bucketIdHash=8844e355-fce7-6a73-9c5d-5562fe1f1394 

Its pretty late in the game for the current milestone. Moving this to January
