### ISSUE TITLE
[Feature Request] Loading git executable from WSL

### ISSUE THREAD

**Issue by Morialkar** [Microsoft/vscode#16859]
- OS Version: Windows 10 (Anniversary Update)

Hi, since WSL is now available to provide easier access to multiple command line utilities that were normally only available as workaround for windows, is there a possibility to allow VSCode to access the git executable installed on Bash instead of either being forced to maintain two git updated with ssh keys or start vscode from the bash command line (which is currently not supported but would completely solve this issue)

**Comment by joaomoreno** [comment]
#9502
