### ISSUE TITLE
Debug: Having skipFiles will skip native node APIs when using node but not with node2

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#16854]
#16208

- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:04:22.691Z)
- OS Version: Linux x64 4.8.0-27-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|python|donjayamanne|0.5.5|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|Go|lukehoban|0.6.50|
|vscode-scss|mrmlnc|0.6.0|
|csharp|ms-vscode|1.5.3|
|java|redhat|0.0.7|
|annotator|ryu1kn|0.10.1|

---

1. Clone and open https://github.com/Microsoft/vscode-smoketest-express.git
2. Created the launch.json:

    ```js
    {
        // Use IntelliSense to learn about possible Node.js debug attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
            {
                "type": "node",
                "request": "launch",
                "name": "Launch Program",
                "program": "${workspaceRoot}/bin/www",
                "cwd": "${workspaceRoot}",
                "skipFiles": [
                    "node_modules/**" // Intentionally doesn't match `http` module
                ]
            },
            {
                "type": "node",
                "request": "attach",
                "name": "Attach to Process",
                "port": 5858
            }
        ]
    }
    ```

3. Put a breakpoint at `bin/www:28` on `server.listen`
4. Start debugging
5. Hit the breakpoint
6. Step in, notice `http` *is* skipped
7. Change `type` to `node2` in `launch.json`
8. Start debugging
9. Hit the breakpoint
10. Step in, notice `http` *is not* skipped

**Comment by weinand** [comment]
dup of https://github.com/Microsoft/vscode/issues/16686
