### ISSUE TITLE
Error: there is no registered task type 'cppbuild'. Did you miss installing an extension that provides a corresponding task provider?

### ISSUE THREAD

**Issue by rababR1** [microsoft/vscode#168530]
Does this issue occur when all extensions are disabled?: Yes/No 

_**No**_

Extension Bisect does not help

- VS Code Version: Insiders version 1.5
- OS Version: Windows 11

Steps to Reproduce:

1. 
2. 
I get this message every time I install a theme or change it:

Here's the video:

https://user-images.githubusercontent.com/65360255/206593729-1229e24f-557e-4e1f-bd8c-caeb25a6288e.mp4

Worse than that, I can't even change my theme!

https://user-images.githubusercontent.com/65360255/206593832-ab5dcffc-d001-49f6-8844-13c2de13090d.mp4

I have no idea where I screwed up, and how I did it. Please help me!

**Comment by rababR1** [comment]
![image](https://user-images.githubusercontent.com/65360255/206631378-b8d2de17-6d42-450f-ac0e-a2cacf2871dd.png)
Still the same error message

**Comment by meganrogge** [comment]
Your window says reload required to disable extensions

**Comment by rababR1** [comment]
![image](https://user-images.githubusercontent.com/65360255/206738630-bf50b1ca-694a-4c5e-b5f2-2c33c1593e34.png)
No error message. But, I wonder on how to **_exactly_** fix this based on this "cppbuild" thing.

**Comment by meganrogge** [comment]
create an issue for the cpp extension

**Comment by rababR1** [comment]
Installed Build ++, and cppbuild.
It doesn't show up anymore!

**Comment by Divakar-2508** [comment]
I got the same issue, how to fix it?

**Comment by rababR1** [comment]
Install the Build ++ Extension
