### ISSUE TITLE
jsconfig creation action in status bar disappeared?

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16850]
Testing #16534

Maybe I was dreaming this... but didn't there used to be a little green lightbulb in the status bar that would offer to create a jsconfig.json for you for JS projects? If so, it is no longer showing up for me. If not, then I think we should have one.

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by mjbvz** [comment]
We removed this with #15213 as TypeScript can now pick up inferred projects better so a `jsconfig.json` is not needed in most cases.
