### ISSUE TITLE
Terminal not working

### ISSUE THREAD

**Issue by Robin-Goyal** [microsoft/vscode#168582]
Type: <b>Bug</b>

Terminal not working

VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|--crash-reporter-id 2b8f463f-0acc-46dd-8c59-41ee6b6c5c1f --max-memory=8042 --crash-reporter-id 2b8f463f-0acc-46dd-8c59-41ee6b6c5c1f --crash-reporter-id 2b8f463f-0acc-46dd-8c59-41ee6b6c5c1f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.10.12
vscode-eslint|dba|2.2.6
xml|Dot|2.5.1
gitlens|eam|13.1.1
smarty|imp|0.3.0
vscode-phpfmt|kok|1.0.31
vscode-JS-CSS-HTML-formatter|lon|0.2.3
vscode-docker|ms-|1.23.1
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
cpptools|ms-|1.13.7
powershell|ms-|2022.11.0
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5788
vetur|oct|0.36.1
vscode-yaml|red|1.10.1
git-autoconfig|shy|0.0.2
prettier-vscode|Sim|2.0.7
vscode-icons|vsc|12.0.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by SergioG-M** [comment]
Did it happen after updating to this version? I have the same issue, it doesn't open with bash (it works if you change the shell, but I prefer to use bash)

**Comment by meganrogge** [comment]
Can you share your settings.json file and also do a trace log while creating a terminal? https://github.com/microsoft/vscode/wiki/Terminal-Issues#enabling-trace-logging
/label info-needed terminal

**Comment by SergioG-M** [comment]
I get a "code: command not found" when running code --log trace

**Comment by SergioG-M** [comment]
I think this is it:

> 2022-12-09 21:30:38.208 [debug] terminalInstance added capability 2
> 2022-12-09 21:30:38.210 [debug] CommandDetectionCapability#handleCommandExecuted 0 0
> 2022-12-09 21:30:38.210 [debug] CommandDetectionCapability#setCommandLine 
> 2022-12-09 21:30:38.212 [debug] CommandDetectionCapability#handleCommandFinished 0 0  {"commandExecutedMarker":{"line":0,"isDisposed":false,"_disposables":[{"_listeners":[null],"_disposed":false},{},{},{},{}],"_id":22,"_onDispose":{"_listeners":[null],"_disposed":false}},"commandExecutedX":0,"command":"","commandFinishedMarker":{"line":0,"isDisposed":false,"_disposables":[{"_listeners":[null],"_disposed":false},{},{},{},{}],"_id":23,"_onDispose":{"_listeners":[null],"_disposed":false}}}
> 2022-12-09 21:30:38.222 [debug] terminalInstance added capability 0
> 2022-12-09 21:30:38.494 [debug] Terminal process exit (instanceId: 6) with code undefined
> 2022-12-09 21:30:38.495 [debug] Terminal process exit (instanceId: 6) state 6
> 2022-12-09 21:30:38.495 [trace] terminalInstance#dispose (instanceId: 6)
> 2022-12-09 21:30:38.595 [debug] CommandDetectionCapability#handlePromptStart 0 2
> 2022-12-09 21:30:38.595 [debug] CommandDetectionCapability#handleCommandStart 33 2

**Comment by meganrogge** [comment]
>with code undefined

this happens when a terminal is killed as a result of a user action. can you share your settings.json file?

**Comment by SergioG-M** [comment]
```
 {
    "security.workspace.trust.untrustedFiles": "open",
    "python.linting.flake8Enabled": true,
    "python.defaultInterpreterPath": "/usr/local/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/bin/python3.10",
    "python.formatting.provider": "black",
    "python.formatting.blackArgs": [
        "--line-length",
        "120"
    ],
    "python.linting.flake8Args": [
        "--max-line-length",
        "120"
    ],
    "isort.args": [
        "--profile=black"
    ],
    "notebook.output.textLineLimit": 42,
    "editor.formatOnSave": true,
    "editor.tabCompletion": "on",
    "isort.path": [
        "isort"
    ],
    "python.envFile": "${workspaceFolder}/.env",
    "terminal.integrated.env.osx": {
        "PYTHONPATH": "${workspaceFolder}:${env:PYTHONPATH}"
    },
    "editor.codeActionsOnSave": {
        "source.organizeImports": true
    },
    "jupyter.widgetScriptSources": [
        "jsdelivr.com",
        "unpkg.com"
    ],
    "terminal.integrated.enableMultiLinePasteWarning": false,
}
```

**Comment by alanwilter** [comment]
@SergioG-M was that working for you?

```json
    "python.envFile": "${workspaceFolder}/.env",
    "terminal.integrated.env.osx": {
        "PYTHONPATH": "${workspaceFolder}:${env:PYTHONPATH}"
    },
```
`Terminal` works for me but the `${env:PYTHONPATH}` in terminal no, though `${workspaceFolder}` expands fine.

```bash
# in vscode terminal:
cat .env
PYTHONPATH=src
# /home/awilter/test_case/src didn't work either for terminal

echo $PYTHONPATH
/home/awilter/test_case:

My `.env` file is fine and it works if I'm debugging with `vscode` for example.

**Comment by meganrogge** [comment]
try disabling all extensions to see if the issues persists

**Comment by SergioG-M** [comment]
> try disabling all extensions to see if the issues persists

It didn't change

**Comment by meganrogge** [comment]
what happens if you try to create a `bash` terminal? 
![Screenshot 2022-12-12 at 2 26 38 PM](https://user-images.githubusercontent.com/29464607/207147431-85156cb9-1867-4fbd-8dac-9f553bc6fdb3.png)

**Comment by SergioG-M** [comment]
> what happens if you try to create a `bash` terminal? ![Screenshot 2022-12-12 at 2 26 38 PM](https://user-images.githubusercontent.com/29464607/207147431-85156cb9-1867-4fbd-8dac-9f553bc6fdb3.png)

It opens and close in ~1 second

**Comment by SergioG-M** [comment]
https://user-images.githubusercontent.com/61322372/207148439-6591b925-6082-4ce2-a48b-b3d40373c42a.mov

**Comment by meganrogge** [comment]
Any errors in the help -> dev tools console?

**Comment by SergioG-M** [comment]
Whatever it was, after updating to 1.74.2 it is solved
