### ISSUE TITLE
Notebooks should source "markdown.styles"

### ISSUE THREAD

**Issue by Acumane** [microsoft/vscode#168571]
Stylesheets added to `"markdown.styles"` should be used by Notebooks on rendered Markdown cells! Tagging @mjbvz for his work on #121256.

**Comment by mjbvz** [comment]
I’m not convinced they should. The markdown preview and notebook cells have very different dom structures and uses

**Comment by Acumane** [comment]
@mjbvz would you be opposed to a `"notebook.markup.styles"` setting? If not, how are users with custom styles expected to achieve visual parity between plain markdown and Notebook previews currently?
