### ISSUE TITLE
Allow to configure files.exclude from the explorer

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16855]
Testing #16534

Would be nice to simply right-click on a folder to automatically add to jsconfig.json and exclude it from a project. Also would be nice for folders to have some sort of visible indication that they are excluded. 

I think this sort of functionality would be useful for most language services, so having a generic way to tie in would be handy (I've certainly used it myself in WebStorm)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by kumarharsh** [comment]
I'd like to work on this. But I have a question: which *setting* would this affect? Workspace or User (if workspace settings do not exist), or should the workspace settings be force-created if not already present.
