### ISSUE TITLE
Go to source definition not working in monorepo

### ISSUE THREAD

**Issue by unional** [microsoft/vscode#168529]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.73.1
- OS Version: MacOS 12.6.1

Steps to Reproduce:

In a monorepo of TypeScript, using `workspace:^` as well as `references` in tsconfig.json,

"Go to definition" and "Go to implementation" both points to the dts file,
and "Go to source definition" fail with "No source definition found"

The package.json of the target project has:

```json
{
  "type": "module",
  "exports": {
    ".": {
      "types": "./dts/index.d.ts",
      "import": "./esm/index.js",
      "require": "./cjs/index.cjs",
      "default": "./cjs/index.cjs"
    }
  },
  "source": "./ts/index.ts",
  "types": "./dts/index.d.ts",
}
```

**Comment by mjbvz** [comment]
Please put together a minimal sample project so we can look into this issue

**Comment by unional** [comment]
False alarm. It was due to didn't set `declarationMap: true` 🙇
