### ISSUE TITLE
Profiles: this flow with docker does not work

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#168551]
I wanted to play with Docker and remote containers and so created a new profile. This action however opened a window with my default profile, so I was not able to test it:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/900690/206633238-72dbf355-3828-481d-82f7-375dd49be1dc.png">

**Comment by sandy081** [comment]
@chrmarti I assume this command is contributed by your extension, May I know how it works and lets see if we can work together to enable this command to be profiles aware?

**Comment by chrmarti** [comment]
This uses the 'vscode.openFolder' or 'vscode.newWindow' command to open a new window.

**Comment by sandy081** [comment]
@bpasero Do you think, shall we add a arg to this command to open the folder/window using the current active window profile?

**Comment by bpasero** [comment]
@sandy081 not sure I understand, this would force all extensions to make this change? Would it not be better to open new windows with the profile of the current window?

**Comment by sandy081** [comment]
> Would it not be better to open new windows with the profile of the current window

Yes, we can do this for empty windows - I am planning to do this anyway - https://github.com/microsoft/vscode/issues/168976

Also for those folders which are not opened before - this is already supported

Given that we support above, May I know if the bug you created is covered or do you see any other missing scenarios?

**Comment by bpasero** [comment]
Maybe in a previous session I had the window already opened and thus the profile was not used, quite possible. The window that opened was not empty though.

**Comment by sandy081** [comment]
Closing this in favour of the enhancements I recommended. For the scenario of opening a remote folder (that was already opened in a different profile) is expected or we shall have to provide better UX to guide users to open in different profile when remote is not resolved which will be looked in here - #165247
