### ISSUE TITLE
Hide Path in Debug Console

### ISSUE THREAD

**Issue by cawoodm** [microsoft/vscode#168559]
As with #115625 we would like the option to completely hide the path. On a HD monitor with multiple panes it renders the debug messaging unreadable and is still waaaay too long. A simple elipsis is enough for the developer to click on, why show the entire path or even a portion of it??

![image](https://user-images.githubusercontent.com/498834/206648685-22deeaef-537d-4651-a4fb-3acb1797bf33.png)

**Comment by roblourens** [comment]
https://github.com/microsoft/vscode/issues/168033
