### ISSUE TITLE
Remote Tunnel Removed everything

### ISSUE THREAD

**Issue by hakobpogh** [microsoft/vscode#168506]
Type: <b>Bug</b>

I was trying to use Remote Tunnel. And it removed all my codes from my machine.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 5|
|Memory (System)|32.00GB (3.61GB free)|
|Process Argv|--crash-reporter-id feaa71ce-5fe2-4202-a8ac-3ccb83d13dcd|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (27)</summary>

Extension|Author (truncated)|Version
---|---|---
chrome-extension-developer-tools|aar|2.0.3
vscode-tailwindcss|bra|0.9.1
path-intellisense|chr|2.8.3
postcss|css|1.0.9
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
vscode-jest-runner|fir|0.4.59
vscode-yarn|gam|2.1.0
copilot|Git|1.62.7527
vscode-pull-request-github|Git|0.56.0
vscode-graphql|Gra|0.8.4
vscode-graphql-execution|Gra|0.1.6
vscode-graphql-syntax|Gra|1.0.5
svg|joc|1.4.23
vscode-codemetrics|kis|1.24.0
change-string-case|max|1.1.2
vscode-github-actions|me-|3.0.1
git-graph|mhu|1.30.0
mongodb-vscode|mon|0.9.5
angular-console|nrw|17.27.0
material-icon-theme|PKi|4.22.0
prisma|Pri|4.7.1
quicktype|qui|12.0.46
vscode-yaml|red|1.10.1
fig|wit|0.0.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by hakobpogh** [comment]
Actually, this happened because the `run debug` sometimes overlaps with some terminal commands. And it overlapped with a rm command and removed my whole folder. 😵‍💫

**Comment by hakobpogh** [comment]
The issue when the run command overlaps with the previous terminal commands needs to be fixed.

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/161582
