### ISSUE TITLE
Rollback request: new styling on context menus

### ISSUE THREAD

**Issue by Icedude907** [microsoft/vscode#168545]
Hi,
I'd just like to voice my dislike of the change in 1.74 to the right click menu (specifically 1px outline and changed shape of the button highlighting).
To me, the new UI doesn't fit with the rest of VSCode's strongly line-based visual language.

This 'issue' is more to facilitate discussion on the topic as I couldn't find any mention of this in the changelogs or elsewhere.
Pedantic I know, but it was so noticable to me on updating.
Thanks for listening.

<table><tr><td>

_Old 1.73_
![OLD](https://user-images.githubusercontent.com/34080011/206613275-cf4f27b6-1fb6-47dd-981c-4a4e235dbbb0.png)
</td><td>

_New 1.74_
![NEW](https://user-images.githubusercontent.com/34080011/206613283-adfebe6f-a42e-433a-b3b1-f5498395d840.png)
</td></tr></table>
Theme is "Dark+ (default dark)" on Windows 10.

**Comment by daviddossett** [comment]
Thanks for the feedback—this is a highly subjective area, so I'll wait for more input here. This is a design direction that we're applying across the product. See the command palette for a similar example:

<img width="649" alt="CleanShot 2022-12-09 at 09 38 17@2x" src="https://user-images.githubusercontent.com/25163139/206760484-70b14752-6919-4d10-a578-61114fe8901b.png">

Also see https://github.com/microsoft/vscode/pull/167773 for future planned changes across various widgets.
