### ISSUE TITLE
Preview doesn't work

### ISSUE THREAD

**Issue by SKjerland** [microsoft/vscode#168518]
Type: <b>Bug</b>

I just logged in to VS Code and noticed it had updated (i.e., it was showing Release Notes). I closed it and didn't read it and proceeded to do my work, and noticed the preview buttons that had been in the upper right were missing.  I clicked the ellipses and noticed Enable Preview Editors was checked. I unchecked it and then re-checked it, and there were still no preview buttons. I looked down at the very bottom and noticed a preview icon down there. I clicked it numerous times but it does nothing. So I closed VS Code and reopened it, but the issue still persists. I'm running version 1.74.0. My coworker is running the previous version and does not have this issue. His preview buttons are still in the upper-right corner where they've always been.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.73GB free)|
|Process Argv|--crash-reporter-id f6ad75b2-7b83-4dd1-8ba6-8a532f26b868|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.2.2
LinkCheckMD|bla|0.3.1
docs-article-templates|doc|0.2.13
docs-images|doc|0.0.10
docs-markdown|doc|0.2.116
docs-metadata|doc|1.0.9
docs-preview|doc|0.3.60
docs-yaml|doc|0.2.9
git-techreview|Git|0.0.3
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
markdown-preview-enhanced|shd|0.6.5
code-spell-checker|str|2.12.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by mjbvz** [comment]
What preview do you mean? This sounds like something provided by an extension

**Comment by SKjerland** [comment]
Sorry, that image was not supposed to be of my three screens.

**Comment by SKjerland** [comment]
Never mind. I discovered what the problem was. I'm closing this issue.

**Comment by mjbvz** [comment]
What was the issue?
