### ISSUE TITLE
Allow to search commands related to problems view with "error" or "warning"

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16852]
@jrieken suggestion from #14639  - Rename **Problems** view to **Errors and Warnings**

**Comment by sandy081** [comment]
@stevencl @bgashler1 Any opinions?

What are the impacts of changing the View name (for existing users)? 
What about marker type other than errors and warnings (eg: Info)?
What is the common title to show this information?

**Comment by pcgeek86** [comment]
@sandy081 why did you close my issue and create a new one, instead of asking me to reword my issue report, to reflect the ask?

**Comment by sandy081** [comment]
@pcgeek86 I think your issue is not about Renaming... its more about discovering Errors and Warnings. I agree it's related but not specific and got fixed by introducing a command to discover. 

I wanted to keep things separate and to the point, hence I opened a specific issue to rename.

**Comment by stevencl** [comment]
I think changing it to Errors and Warnings would be good. We have commands for navigating errors and warnings and I believe many other IDEs also use a similar name. Regarding other markers that aren't strictly errors or warnings, I think that would still be fine. It's really no different to what we have currently (e,g, Info markers showing up in the Problems panel).

**Comment by bgashler1** [comment]
I have no problem renaming it.  We have explored putting all the panels in a tabs, which makes me think "Errors and Warnings" would look more appropriate as "Errors/Warnings" (more concise and matches the other panels better IMO).
![horizontal-panels-combined-03-with-notifications](https://cloud.githubusercontent.com/assets/11839736/21025674/29231614-bd3e-11e6-869b-748e0cb6ad7d.png)
But we're also exploring other window management.

**Comment by jrieken** [comment]
Really @sandy081? A label change is too hard and needs planning?

**Comment by sandy081** [comment]
@jrieken It is not about the implementation, but closed it because of not much demand. We have this for more than an year and I do not see any pressing feedback to change it except for few users.

**Comment by pcgeek86** [comment]
The way that issues are being handled by Microsoft is a little confusing for me. I made a fairly simple request, to help bring some consistency to the VSCode user experience. Although it's ultimately the decision of the VSCode team to make or not make this change, it seemed like a universally agreeable thing.

At this point, I'm not so much concerned that this specific change get made, as I am trying to understand the process for issue reports to be managed. It's very odd that such simple issues are ignored for a very long time and then simply closed out, with no action taken. Everyone seemed to be in agreement that this minor change was worthwhile, or am I misunderstanding something?

Should I continue to report these kinds of UX issues, or will they simply be ignored?

**Comment by sandy081** [comment]
@pcgeek86 Please do not misunderstand that we ignore issues.

Your initial request was to provide an alias for `Show problems` command - [here](https://github.com/Microsoft/vscode/issues/14639#issuecomment-256964779) which was provided and fixed. 

This issue was extracted from the [comment](https://github.com/Microsoft/vscode/issues/14639#issuecomment-265469787) from that issue to rename. True that, I asked the opinion of our UX team to rename and they were in favour of that. 

Yes, it was postponed because it was not pressing. It might be just a label change but also need to update references to Problems commands and updating docs. Not sure what to do with the extensions using the term problems for their commands. We also have `problemMatcher` in `tasks` that creates problems which are shown in Problems panel. But this is not the reason I closed it. As mentioned in my previous comment, I do not see much user attention on this feature and if this rename improves the UX then I would expect more such similar issue reports which is not. I will definitely revisit if hear the same from more users.

**Comment by jrieken** [comment]
> Yes, it was postponed because it was not pressing.

Well, I'd say folks are pressing now. I also dislike the logic of out-weighing team feedback with the absence of other feedback. Surely, this is a nit but it's still valid and things should be designed to contradict each other. Either we use 'Problems' or 'Errors & Warnings', not both. 

Good news is that December will be the month of doc-a-thon, meaning we revisit and update our docs anyways. So, I really don't see a reason for not doing this.

**Comment by sandy081** [comment]
Here is the summary of the discussion with the UX team

Root cause of this issue is having the command `Show Errors & Warnings` as the alias for discovering and showing problems view. The command showing the view should have the name of the view. So, there should be only one command representing the view name (Problems) and should be discoverable when user types `problems` or `error` or `warning` or `info`.  

Output of the discussion is to have single view command `View: Focus Problems (Errors/Warnings/Info)` that can be discoverable from command pallette when user is looking for errors or warnings. Additional info (Errors/Warnings/Info) will be shown as detail/description of the command. Existing commands `Go to Next/Previous Error or Warning` can remain unchanged as they are editor commands.

@stevencl @chrisdias @bpasero FYI

**Comment by bpasero** [comment]
Yeah, on top of that we would keep the existing command `workbench.action.showErrorsWarnings` around for backwards compatibility, but it would not show up in the command palette.

**Comment by bpasero** [comment]
**Verification:** verify that you can find "Problems" view related commands (focus, toggle) by typing "error" or "warning".
