### ISSUE TITLE
Feature: Visual HTML Editor Addon for HTML Files

### ISSUE THREAD

**Issue by jogibear9988** [microsoft/vscode#168600]
Hello,
I'm working on a HTML Designer Framework in HTML (see: Demo: https://node-projects.github.io/web-component-designer-demo/index.html Code: https://github.com/node-projects/web-component-designer).

Now I wanted to create a VSCode Addon, wich could be used to edit HTML Files visually. Is this possible? So I don't want to create my own Text Editor instance inside of VSCode, I want a Addition window, wich is shown for a TextFile. So I also can write back to the HTML Code.

Maybe later this could be used for other files to, wich contain html Templates... like Vue Templates or other

Am I also be able to Access other Files form the loaded project? So I can for example import stylesheets?

**Comment by aeschli** [comment]
Developer questions should best be asked in one of our discussion channels:
https://github.com/microsoft/vscode-discussions
