### ISSUE TITLE
[c#] Storage type highlighting not working for my classes 

### ISSUE THREAD

**Issue by cdes** [Microsoft/vscode#1686]
I'm using the VSCode Version 0.10.6 (0.10.6).
Default dark theme.

Here's a sample code:
```csharp
class MyClass
{

}

class Program
{
    static void Main()
    {        
        //string is highlighted
        string s = "MyClass";
        
        //MyClass is not highlighted
        MyClass myClass = new MyClass();
    }
}
```

Here's an image:
![screen shot 2015-12-29 at 11 13 02 am](https://cloud.githubusercontent.com/assets/1207863/12031503/c113e952-ae1d-11e5-85bf-361487e95dc9.png)

Here's a video demonstration:
https://www.youtube.com/watch?v=VpRPJc42FZQ

**Comment by aeschli** [comment]
It's an issue with the csharp tokenizer, same issue in atom (languages-csharp 0.11.0)
![image](https://cloud.githubusercontent.com/assets/6461412/12174635/24a4af8c-b55e-11e5-90ed-0fcd3e8bd920.png)

**Comment by aeschli** [comment]
This issue was moved to atom/language-csharp#48

**Comment by aeschli** [comment]
Now tracked in https://github.com/OmniSharp/omnisharp-vscode/issues/101
