### ISSUE TITLE
high contrast mode - bottom border of git staged changes count badge is cut off

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16868]
Testing #15811 

![image](https://cloud.githubusercontent.com/assets/762848/20992058/a23e3aa4-bc96-11e6-94f4-b56d2ca77a2f.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by joaomoreno** [comment]
Fixed.
