### ISSUE TITLE
Some extensions get automatically re-enabled in settings profiles when they automatically update

### ISSUE THREAD

**Issue by DiegoBM** [microsoft/vscode#168687]
VS Code Version: stable 1.74.0
OS Version: Windows 11 Build 22621.900
Feature: Settings Profiles (Profiles)

When certain Extensions that I had disabled for the active profile automatically update, they get re-inserted (re-enabled) in my Extensions list for that profile, and will remain there from that point onwards.
I've noticed this with all the "C++" extensions from Microsoft, as well as the "Remote Explorer", and "Remote - SSH" also from Microsoft, but this might be happening with other extensions as well.
Even if I disable them again for that profile, they'll come back the next time they update

Steps to Reproduce:

1. Enable Profiles feature by setting the `workbench.experimental.settingsProfiles.enabled` to true.
2. Install the C++ from Microsoft on the default profile.
3. Create a new profile "A" other than default, disable the C++ extension.
4. Create a second profile "B" but enable the C++ extension.
5. Create a third profile "C" following step 2.
6. Switch to either A or C profile.
7. Close vscode, reopen it on the same folder, and wait for the C++ extension to update (I'm not aware of any means to force an extension update besides creating one myself).

You'll notice that once the C++ extension update, it will re-enable automatically on both profiles A and C, and will remain there even after re-starting vscode, until you disable it again. In which case it will reappear again once it updates.

**Comment by DiegoBM** [comment]
Hi @sandy081, as mentioned in the issue, I did not force the update since I'm not aware of any means to do that, I just waited for extensions to update.

How can I share the profiles with you in a non-public manner?

**Comment by sandy081** [comment]
You can export the profile to a file or github gist and share it with me via email - sasomava@microsoft.com

**Comment by DiegoBM** [comment]
Done. Hope that can solve it since it keeps happening. Thank you

**Comment by DiegoBM** [comment]
Why is this still labelled as info-needed?

**Comment by alexr00** [comment]
@sandy081 is there a way to simulate the extension update that is needed to reproduce the issue?

**Comment by sandy081** [comment]
Yeah there is, but its a lengthy one:

- Please open extensions installation folder and the folder where profiles are stored that is user data folder/User/profiles
- Quit VS Code
- Change the name of the extension in the extensions installation folder and also the version in the package.json
- Update the name and version in `extensions.json` file in all profiles include the file in extension installation folder.
