### ISSUE TITLE
file protocol links does not work on intgrated terminal with WSL

### ISSUE THREAD

**Issue by PhilippeVienne** [microsoft/vscode#168634]
Type: <b>Bug</b>

When a program output an hypertext link in the terminal with the file protocol, the opened file is not reached and not found because URL is wrongfuly replaced with `\` in the path.

![issue-terminal-file-links](https://user-images.githubusercontent.com/1990262/206754250-bd80367b-f9c0-466e-a8bd-4f8b11f8487c.png)

To reproduce, you can use this bash script:
```
#!/bin/bash

echo -e "\e]8;;file://$PWD/test.txt\aOpen test.txt\e]8;;\a"
```

Expected result: CTRL+Click on the "Open test.txt" link in console open a test.txt file in the path (Created before of course)

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.85GB (24.99GB free)|
|Process Argv|--crash-reporter-id d56ca21d-2704-4140-a506-da1f07b5ecc5 --crash-reporter-id d56ca21d-2704-4140-a506-da1f07b5ecc5|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|13th Gen Intel(R) Core(TM) i5-13600KF (20 x 3494)|
|Memory (System)|31.27GB (25.73GB free)|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-language-pack-fr|MS-|1.74.12070929
remote-wsl|ms-|0.72.0
vscode-language-pack-fr|MS-|1.74.12070929

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by meganrogge** [comment]
maybe related #148062

**Comment by elialgranti** [comment]
An observation:

The file protocol actually works, but vscode tries to open the link in the Windows filesystem instead of the wsl filesystem,

I.e. the link `file:///home/myuser/text.txt` tries to open the file: `C:\home\myuser\text.txt` in Windows instead of `/home/myuser/text.txt` in the wsl environment.

This can be verified by creating the file in the Windows environment before following the link.

**Comment by Tyriar** [comment]
This one is already fixed with the fix for general file protocol support: https://github.com/microsoft/vscode/issues/163545
