### ISSUE TITLE
Merge the two high latency measurement instrumentations

### ISSUE THREAD

**Issue by MarkZuber** [microsoft/vscode#168667]
In various network conditions, the user may get into a situation where the latency is poor.  Being able to detect and measure this high latency activity makes it easier to understand the networking behavior of users to help further root cause network latency issues.

This feature won't log as telemetry but to logService so that users logs could be investigated for these types of issues.

**Comment by bpasero** [comment]
@MarkZuber 👋 , fyi during this milestone I have worked on indicating high latency situations to the user via the remote indicator, simulated in below video using our test resolver:

![Recording 2023-05-22 at 12 14 12](https://github.com/microsoft/vscode/assets/900690/a0a9326a-b420-4e75-b0b3-684d6a5b36fb)

I saw your change in https://github.com/microsoft/vscode/pull/168668. I have implemented something similar here:

https://github.com/microsoft/vscode/blob/fa8eefda18bf099d82b58453f8fe5d3010196fa0/src/vs/workbench/services/remote/common/remoteAgentService.ts#L91

My algorithm is probably a bit different from yours but I would be happy to align the implementations or even reuse. In a nutshell I:
* measure the average latency to the remote over 100 samples to report to the user
* measure an initial latency over 3 samples 10s after the connection was established
* measure the current latency every 1min
* report high latency if either the current latency is above `1500ms` or if its above `500ms` and the above `2 * initial latency`

Happy to understand how you came up with your solution.

**Comment by MarkZuber** [comment]
Hi @bpasero !  

Thanks for reaching out.  Having the latency indicator is awesome and it's something we actually had initially with the work we submitted upstream but we didn't surface (it wasn't completed/tested on our end).  This will be really helpful and I know Meta will want to absorb this as well.  I'm not at Meta any longer so I'm not actively developing VS Code platform work at this time.  @alexdima will know the appropriate contacts there (I don't want to post emails here on github) to reach out to regarding existing algorithm and further integration.  I no longer have access to the custom fork we built this on so I'm not in a position to be able to comment about their customizations.

**Comment by bpasero** [comment]
Thanks for the comment, all the best for your future!

**Comment by ebluestein** [comment]
@bpasero thanks so much for this! The UI looks great, and I'm excited to see this included

Happy to collaborate or answer any questions from the Meta side!

**Comment by bpasero** [comment]
👋 hey, no specific questions so far, just curious of what I had posted in https://github.com/microsoft/vscode/issues/168667#issuecomment-1569574642

**Comment by MarkZuber** [comment]
Just a heads up that you should also loop in @alexdima since he did quite a bit of refactoring of our initial high latency check pull request so he may have some additional insights.

**Comment by ebluestein** [comment]
Totally agreed on it being best to have just one place measuring and recording latency

I think it would be good to keep the logging and telemetry for this, but those log points could move into your manager class?

I think it's also fine to change the detection algorithm. Ours is a bit simpler, but maybe that over-notifies in some scenarios. I am not sure I follow the concern about waking the connection though - the connection remains alive even if the window doesn't have focus?

**Comment by bpasero** [comment]
> Totally agreed on it being best to have just one place measuring and recording latency
> 
> I think it would be good to keep the logging and telemetry for this, but those log points could move into your manager class?

👍 

> I am not sure I follow the concern about waking the connection though - the connection remains alive even if the window doesn't have focus?

If I understand the code correctly, there is a ping to the remote happening every minute, irrespective if the user is using VS Code or not. In the case of GitHub Codespaces for example, I wonder if that will prevent a Codespace from going to sleep eventually. My solution explicitly checks for the window having focus before attempting to measure.

**Comment by bpasero** [comment]
Merging the 2 solutions (via https://github.com/microsoft/vscode/pull/184566):
* using my latency measurement that is also used as indicator in the UI
* preserving the log message so that high latency gets logged to the logs
* preserving the telemetry event `remoteConnectionHealth`
