### ISSUE TITLE
terminals/tasks restored after reload ignore confirmOnKill and confirmOnExit settings

### ISSUE THREAD

**Issue by diminutivesloop** [microsoft/vscode#168601]
Type: <b>Bug</b>

1. Ensure `terminal.integrated.confirmOnExit` is set to "hasChildProcesses" and `terminal.integrated.confirmOnKill` is set to "always".
2. Start a terminal or task with a long-running child process (e.g. a test runner in watch mode).
3. Reload VSCode via "Developer: Reload Window". Note that the terminal or task is still running after reload.
4. Attempt to either close the window or kill the terminal or task from step 2.

Expected Behavior: A confirmation dialog appears with the message "Do you want to terminate the active terminal session?" This is the actual behavior if the step 3 is skipped.

Actual Behavior: The terminal or task is terminated without confirmation.

VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 3, 3|
|Memory (System)|32.00GB (7.30GB free)|
|Process Argv|--crash-reporter-id ed50f89e-497f-43cd-86f3-a73119f730ed|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (61)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
project-manager|ale|12.7.0
vscode-zipfs|arc|3.0.0
restore-git-branch-tabs-improved|ava|1.1.0
beardedicons|Bea|1.2.0
vscode-tailwindcss|bra|0.9.1
vscode-css-modules|cli|0.4.2
vscode-github-actions|csc|0.24.4
vscode-eslint|dba|2.3.0
vscode-dash|dee|2.4.0
find-related|eam|0.9.0
gitlens|eam|13.1.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
vscode-open-in-application|fab|1.0.6
vscode-firefox-debug|fir|2.9.8
auto-rename-tag|for|0.1.10
vscode-pull-request-github|Git|0.56.0
go|gol|0.36.0
vscode-graphql-syntax|Gra|1.0.5
todo-tree|Gru|0.0.220
yarn2-dependency-explorer|hah|0.0.3
hcl|has|0.3.1
vscode-env|Iro|0.1.0
search-node-modules|jas|1.3.0
svg|joc|1.4.23
vscode-peacock|joh|4.2.2
json-escaper|jos|1.1.2
vscode-styled-components|jpo|1.7.0
bash-ide-vscode|mad|1.21.0
ts-error-translator|mat|0.5.1
vscode-tsx-arrow-definition|mia|0.1.2
vscode-duplicate|mrm|1.2.1
vscode-scss|mrm|0.10.0
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.13.7
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5788
vscode-yaml|red|1.10.1
partial-diff|ryu|1.4.3
mdx|sil|0.1.1
vscode-quick-scope|ska|0.2.0
vscode-fileutils|sle|3.5.0
reveal|smu|1.2.7
swdc-vscode|sof|2.6.35
code-spell-checker|str|2.12.0
vscode-stylelint|sty|1.2.3
sass-indented|syl|1.8.23
icons|tal|3.6.0
shellcheck|tim|0.29.1
jest-snapshot-language-support|tle|1.1.1
vscode-terminal-here|Tyr|0.2.4
vscode-mdx|uni|1.0.3
vscode-icons|vsc|12.0.1
vim|vsc|1.24.3
vscode-css-variables|vun|2.6.1
wvsc-serendipity|wic|0.105.0
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0
material-theme|zhu|3.15.6

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by jeanp413** [comment]
PR fixing it https://github.com/microsoft/vscode/pull/168922
