### ISSUE TITLE
"Unable to write settings" message bar should have button to open User Settings

### ISSUE THREAD

**Issue by gregvanl** [Microsoft/vscode#16862]
- VSCode Version:1.8.0 Insiders
- OS Version:Windows 10
Steps to Reproduce:

1. Add an extra trailing comma to user settings.json.
2. Close the settings file.
3. Try to toggle File > AutoSave.

You see the "Unable to write settings. Please open User Settings to correct..." message. 
We should add a button to open User Settings next to Close.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16580
