### ISSUE TITLE
High contrast mode - top of selection box not highlighted when over over first extension in list

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16867]
Testing #15811 

In the screenshot below, I am hovering over the top extension in the list, but there's no visual indicator that's the case because the top border is nowhere to be found. 
![image](https://cloud.githubusercontent.com/assets/762848/20992023/55691ec4-bc96-11e6-838f-3c7990f5578c.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by joaomoreno** [comment]
cc @bgashler1
