### ISSUE TITLE
Editor-area terminals are not restored after quit on 1.74.0

### ISSUE THREAD

**Issue by adamfeldman** [microsoft/vscode#168643]
Type: <b>Bug</b>

1. Ensure `terminal.integrated.enablePersistentSessions` is enabled. Ensure `window.restoreWindows` is set to `all`, `preserve` or `one` (any option that will restore the last open window after quiting and re-opening VSCode).
2. Start a terminal in the editor area, e.g. using the command "Terminal: Create New Terminal in Editor Area". Type something into the terminal e.g. `cd ~`.
3. Reload VSCode via "Developer: Reload Window". Note that the terminal tab in the editor area is still there (_restored_) after the window is reloaded. _This is the expected behavior._
4. Quit VSCode then reopen the application. Note that the terminal tab is not present (_is not restored_) when the window is restored (_and since there is no terminal tab, there is also nowhere to restore the session to 🙂_) . 
    - _This is unexpected behavior as previously this terminal tab would be restored into the editor area, with its session history, even after quitting and reopening VSCode._

Another terminal persistence bug on 1.74.0, also related to killing terminals: #168601 

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 4, 7|
|Memory (System)|32.00GB (2.82GB free)|
|Process Argv|--crash-reporter-id be1f0084-53c0-4bd2-b437-891afea08dd8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-neovim|asv|0.0.94
calva|bet|2.0.321
file-browser|bod|0.2.11
portal|djb|0.35.0
viml|dun|0.1.7
prettier-vscode|esb|9.10.3
vscode-htmlhint|HTM|1.0.4
vscode-sshfs|Kel|1.25.0
ssh-config-syntax-highlighter|mou|0.0.4
sqltools|mtx|0.26.0
sqltools-driver-pg|mtx|0.4.0
errorlens|use|3.6.0
learn-vim|vin|0.0.28
vspacecode|VSp|0.10.10
whichkey|VSp|0.11.3
markdown-all-in-one|yzh|3.5.0

</details>

**Comment by meganrogge** [comment]
I cannot reproduce that in Insider's 

https://user-images.githubusercontent.com/29464607/206786389-85084e77-3942-4850-8696-6261f47f2951.mov

**Comment by meganrogge** [comment]
@adamfeldman have you typed in the terminal before reloading? if not, that's by design

**Comment by adamfeldman** [comment]
Reviving editor-area terminals was working great in 1.73.x. This was marked as a duplicate of a feature request. Is it not a regression? @meganrogge

**Comment by jeanp413** [comment]
Created a PR https://github.com/microsoft/vscode/pull/168887 with a possible fix

**Comment by yeshiqing** [comment]
@meganrogge VSCode v1.74.2 occurs the same problem, does the fix takes effect or I need to config some settings?

**Comment by jeanp413** [comment]
The fix will be available in 1.75 release or you can try it in insiders
