### ISSUE TITLE
Tasks.json Shell Command cannot expand asterisk to match file

### ISSUE THREAD

**Issue by Evilcat325** [Microsoft/vscode#16865]
- VSCode Version: 1.7.2
- OS Version: macOS 10.12.1

Steps to Reproduce:

1.  Configure tasks.json to run `g++ -g -o main.out *.cpp -std=gnu++14`
```
{
    "version": "0.1.0",
    "command": "g++",
    "isBuildCommand":true,
    "isShellCommand": true,
    "args": ["-g", "-o", "main.out", "*.cpp", "-std=gnu++14"],
    "showOutput": "always",
    "echoCommand": true
}
```
2.  Output show the `*.cpp` is passed as-it rather than expanded by the shell
```
running command$ g++ -g -o main.out *.cpp -std=gnu++14
clang: error: no such file or directory: '*.cpp'
clang: error: no input files
```

Also tried to use run `sh g++ -g -o main.out *.cpp`, did not work.
 
The vscode passed the `*.cpp` as `*.cpp`, and if I have a `*.cpp` the task will work.
But the default behavior expected as a Shell Command should be expanding the "*.cpp" to match all files with `.cpp` extension within the same directory.

**Comment by dbaeumer** [comment]
Should be improved when we execute the command in a terminal instead of spawning our own processes which is planned for the next iteration.

**Comment by dankawka** [comment]
Same here, did you find any workaround but keep using VSCode tasks?

**Comment by dbaeumer** [comment]
@dankawka this got addressed with the new terminal runner. You can either add `"runner": "terminal"` to your tasks.json or convert to the new 2.0.0 version of the tasks.json which will ship with 1.14. The runner property requires 1.13.

I will close the issue since the solution is to use the new terminal runner.
