### ISSUE TITLE
Command navigation doesn't work as expected in task terminals

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#168624]
Notice how for the task terminal it jumps all the way to the top on the first ctrl+up, instead of going to the most recently run task:

![Recording 2022-12-09 at 08 20 53](https://user-images.githubusercontent.com/2193314/206746176-02196fbc-0343-44d3-ae20-6e2e95e0f41d.gif)

**Comment by Tyriar** [comment]
That's even worse 🤨

**Comment by meganrogge** [comment]
the call to get markers here returns undefined

![Image](https://user-images.githubusercontent.com/29464607/207650927-fb0456f4-95fd-4067-96d9-e1e4069f2c6e.png)

**Comment by meganrogge** [comment]
I bet the markers are getting disposed of, so deleted from the map in `bufferMarkCapability`
