### ISSUE TITLE
Investigate `1.75.0-insider` slowdown on perf bot

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#168639]
The perf bot shows a slowdown when we changed from 1.74.0 to 1.75.0. We should figure out if this is a fluke or some unwanted changed that happened during debt-week

**Comment by jrieken** [comment]
The perf machine data shows a slowdown when processing configuration defaults and just configurations. That would explain a little bit but not all of the slowdown

<img width="777" alt="Screenshot 2022-12-20 at 15 47 29" src="https://user-images.githubusercontent.com/1794099/208694400-dc0ed138-636e-4ec4-8abe-619f5fde0056.png">

<img width="620" alt="Screenshot 2022-12-20 at 15 47 55" src="https://user-images.githubusercontent.com/1794099/208694467-9a3dce57-3be1-4628-b3da-eb43a2242d21.png">

**Comment by jrieken** [comment]
@sandy081 Were there changes in the configuration service (during the 1.74 to 1.75 debt week) that could explain this or should I fish for a new listener here?

**Comment by sandy081** [comment]
No changes in config land except [this](https://github.com/microsoft/vscode/commit/cb226f7c7ea7e15fcd852be616cdc8658cc7d995) which is adding log statements.

**Comment by jrieken** [comment]
Good news: great improvements wrt handling contribution points. 

<img width="1611" alt="Screenshot 2023-01-03 at 09 57 01" src="https://user-images.githubusercontent.com/1794099/210326232-1bf06c6f-099a-41f4-9e11-22a936e31ffb.png">

**Comment by jrieken** [comment]
Bad news: something happens with added a big delay between the `didCreateWorkbenchContributions/3` and `willHandleExtensionPoints` phases

<img width="493" alt="Screenshot 2023-01-03 at 09 58 12" src="https://user-images.githubusercontent.com/1794099/210326552-4bdc2349-a853-43c3-9d51-622e479afefa.png">

**Comment by sandy081** [comment]
Caused by https://github.com/microsoft/vscode/commit/e90f48f1a9d58f257b8fd836b5f0a2b9b8e9d110#diff-72bc8a9f7335192506e81a38f38cec5f7438af42467722f97f1f57e58be2a372R516

Fix - https://github.com/microsoft/vscode/pull/170446

**Comment by bpasero** [comment]
I think this is solved:



![Image](https://user-images.githubusercontent.com/900690/212710946-d51843b4-94b4-4e89-8567-dded72ec3912.png)

**Comment by jrieken** [comment]
Confirmative - four fast builds in a row don't lie!

**Comment by jrieken** [comment]
Thanks everyone for helping out on this!
