### ISSUE TITLE
Improve workflow for modifying user and workspace settings.

### ISSUE THREAD

**Issue by ianwesterfield** [microsoft/vscode#168638]
Settings management between user and workspace tabs is cumbersome. There's no way to apply a value between the two (if you are mistakenly on the wrong tab, for example). This has also led to issues with state management (https://github.com/microsoft/vscode/issues/148709 & https://github.com/microsoft/vscode/issues/165175).

It would be great to see settings displayed in a non-tabbed fashion. I don't know the correct answer, but perhaps like app configurations in Azure?

![image](https://user-images.githubusercontent.com/15803541/206759682-841306aa-96c6-4c91-b68d-020bde137e8e.png)

**Comment by rzhao271** [comment]
Closing as out of scope because there are other tabs that could show up in other contexts. I think that a non-tabbed configuration could work if the only scopes were User and Workspace, but there are also Remote, Workspace Folder, and language-specific scopes that sometimes show up.
