### ISSUE TITLE
HC theme: revisit hover feedback in areas where you can click

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16869]
Testing #15811

Currently, nothing happens if you hover over the sidebar icons
![image](https://cloud.githubusercontent.com/assets/762848/20992188/585c6586-bc97-11e6-80d7-21d8f362be58.png)

And the change in the status bar is barely discernable:
![image](https://cloud.githubusercontent.com/assets/762848/20992206/6953dd60-bc97-11e6-98a2-ff8800dfb6e1.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by bpasero** [comment]
We can use the same border we use already for the tree:

![image](https://cloud.githubusercontent.com/assets/900690/21004180/5d66f850-bd2f-11e6-8f15-62f4b382d4a3.png)

**Comment by bpasero** [comment]
I think this applies to many things including all our actions.

**Comment by bpasero** [comment]
We added hovering to sidebar in HC theme.
