### ISSUE TITLE
Status Bar doesn't indicate a watch-task

### ISSUE THREAD

**Issue by anseki** [Microsoft/vscode#16864]
- VSCode Version: 1.7.2
- OS Version: Windows 8/10

I created a Gulp task that does `gulp.watch`, and added `"isWatching": true` to a `tasks.json`.
When the task is running, the Status Bar doesn't indicate an icon (spinner) that means a watch-task.

To reproduce, I created a new project that is the same as an example:
https://code.visualstudio.com/Docs/languages/markdown#_automating-markdown-compilation
I did those steps faithfully.
And, when the task is running, the Status Bar doesn't indicate a watch-task.

I tried to remove `"isWatching": true` from the `tasks.json`, then the Status Bar indicated it.
It seems that the task and the Status Bar work fine.
(But, is VS Code still waiting for the finish of the task because since `isWatching` isn't set?)

**Comment by dbaeumer** [comment]
Duplicated https://github.com/Microsoft/vscode/issues/6209

A task still needs to define start and end patterns to make the status bar work again but this is currently cumbersome due to the fact that the watching can only be defined on a problem matcher.
