### ISSUE TITLE
V1.74 bugs in vscode extension developing

### ISSUE THREAD

**Issue by ztsing** [microsoft/vscode#168693]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74.0
- OS Version: MacOS 13.0.1 (22A400)  // intel core

Steps to Reproduce:
1. Developing a vscode extension, and start run the extension;
2. vscode show error message "Extension host did not start in 10 seconds, it might be stopped on the first line and needs a debugger to continue." in the extension host 
3. The developing window seems hunged up, the searching could not respond for a long time e.g.
4. When I rolled it back to the v1.73.1, everything is ok!

**Comment by gjsjohnmurray** [comment]
Does the problem also happen if you reload with all extensions disabled, so that only the one you are developing is using the extension host (plus the built-in extensions)?

**Comment by ztsing** [comment]
It seems fixed in the v1.74.1

**Comment by gjsjohnmurray** [comment]
Good. Please close the issue.
