### ISSUE TITLE
"Change Tab Display Size" doesn't update indent guides

### ISSUE THREAD

**Issue by tao-cumplido** [microsoft/vscode#168745]
Type: <b>Bug</b>

When indenting with tabs the new action "Change Tab Display Size" updates the visual width of the tab character accordingly but indent guides keep the previous tab size.

![image](https://user-images.githubusercontent.com/6384563/206875779-35b2652c-bf95-46d4-8539-c105aa1d9b6a.png)

Using the older two-step action "Indent Using Tabs" fixes the issue.

Related: #167571

VS Code version: Code - Insiders 1.75.0-insider (f076d553210e9ea65e7bccbfa2f7a786c10fcab2, 2022-12-09T09:11:59.691Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by alexdima** [comment]
`Change Tab Display Size` is a command which allows to dissociate the indent size (number of spaces making up an indent) from the tab size (number of spaces used to render a tab character). I believe you might have wanted to use the commands `Indent Using Spaces` or `Indent Using Tabs`. The new `indentSize` setting is explained [here](https://code.visualstudio.com/updates/v1_74#_new-indent-size-setting).
