### ISSUE TITLE
VSCode hang while coding Remix-run app and using ESLint   

### ISSUE THREAD

**Issue by febrifahmi** [microsoft/vscode#168710]
Type: <b>Bug</b>

1. Start  your Remix-run development server 'npm run dev' (I'm using Tailwind css and include it in npm scripts) (or not, after sometimes I think the problem is not with the Remix-run but might be with lint plugin or autosave. I also developing Python Flask app and it doesn't have this kind of problem )
2. Start coding/editing your code, copy, paste, cut and hit Ctrl+S (ESLint active).
3. It is then hang and I cannot access any system tools/commands (but the mouse pointer still moving/clicking anything doesn't work). Everytime it's freeze I need to hard shutdown my laptop to be able to use it again.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:47:18.476Z)
OS version: Linux x64 5.10.101-amd64-desktop (Deepin)
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 2, 1|
|Memory (System)|3.76GB (0.69GB free)|
|Process Argv|--unity-launch --crash-reporter-id 1aaece5d-9e76-44e3-9e9f-d9665260cdad|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|deepin|
|XDG_CURRENT_DESKTOP|Deepin|
|XDG_SESSION_DESKTOP|deepin|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
flask-snippets|cst|0.1.3
vscode-eslint|dba|2.2.6
go|gol|0.36.0
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
material-icon-theme|PKi|4.22.0
prisma|Pri|4.7.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by aeschli** [comment]
This is highly likely caused by an extension, maybe `ESLint`
Can you try to run with without extensions? `Developer: Reload with Extensions Disabled`.

**Comment by aeschli** [comment]
Can you narrow down wich extension causes this? We have the `Help: Start Extension Bisect` command.
If it's ESLint, then I can move the issue in that repo.
