### ISSUE TITLE
[remote tunnel] cannot start with a host name that starts with dash

### ISSUE THREAD

**Issue by M-Destiny** [microsoft/vscode#168736]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
- VS Code Version: 1.74
- OS Version:  Windows 11 Pro Developers Build 

1. ![vsERR](https://user-images.githubusercontent.com/71012892/206869965-9a0f5fc5-64a6-4793-9652-06a1ebf7a57d.png)
Error Code image attached 

2.  Passes an invalid argument upon launch using the latest vs code Version 1.74

**Comment by aeschli** [comment]
I can take this...

@M-Destiny The workaround is to use the `remote.tunnels.access.hostNameOverride` setting to pick a name that does not start with a `-`

**Comment by connor4312** [comment]
1. Set `remote.tunnels.access.hostNameOverride` to something starting with a dash
2. Enable remote tunnel access
3. Verify it comes up successfully
