### ISSUE TITLE
Text and icon missing on Ubuntu 22.04

### ISSUE THREAD

**Issue by linyz0100** [microsoft/vscode#168740]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
1.74.0
5235c6bb189b60b01b1f49062f4ffa42384f8c91
arm64
- OS Version: Ubuntu 22.04

![Screenshot from 2022-12-10 14-50-44](https://user-images.githubusercontent.com/63493856/206873071-8b597290-5e05-4b0f-b63c-9c7d048fc984.png)
![Screenshot from 2022-12-10 14-51-18](https://user-images.githubusercontent.com/63493856/206873075-ff4d649e-2bab-454d-9a12-93d2742e462f.png)
![Screenshot from 2022-12-10 14-59-20](https://user-images.githubusercontent.com/63493856/206873189-b01ccaff-b9f3-4f71-9237-3cba00a1c22a.png)

Steps to Reproduce:

1. download arm64.deb installation file
2. sudo apt install ./file.deb
3. run code

**Comment by deepak1556** [comment]
Does the issue repro when you run with `--disable-gpu` ?

**Comment by linyz0100** [comment]
that fixes the issue. thank you.

**Comment by deepak1556** [comment]
Thanks for confirming, please continue to disable hardware acceleration as workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration. This might get addressed with newer runtime versions.
