### ISSUE TITLE
VSCode Insiders 1.75 broke the hack support for neon theme

### ISSUE THREAD

**Issue by VanderSP** [microsoft/vscode#168730]
Does this issue occur when all extensions are disabled?: Yes/No

It worked using a tricky of opening vscode insider as administrator for enabling the neon trick... (each time when updated),
But lately on 1.75 the trick stopped to work... 

Please, someone do something... neon is very important to my mind while developing! 
Thanks in Advance...

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by gjsjohnmurray** [comment]
Maybe https://github.com/microsoft/vscode-discussions/discussions/257#discussioncomment-4364513

**Comment by VanderSP** [comment]
Highly probable, no workarounds in sight?

**Comment by bhavyaus** [comment]
Could you please provide more info on the steps to reproduce your issue?

**Comment by VanderSP** [comment]
Nevermind! The synthwave neon theme author released an update, that fixed it, also it fixed even the need of doing the hack the used to work before 1.75, that stopped working on 1.75... so everything now is even better than before! as i can update vscode now without needing to apply the patch in admin mode... i don´t need to do nothing more now!

Thanks!

**Comment by VanderSP** [comment]
i would like to rectify what i said before... in truth after plugin author fixed it, it still needs the hack... but at least the hack works now again!
