### ISSUE TITLE
zsh integrated terminal prompt

### ISSUE THREAD

**Issue by chris-aisera** [microsoft/vscode#168772]
Type: <b>Bug</b>

In the latest (1.74 Nov 2022) release, the zsh prompt in the integrated terminal window overlaps with the terminal cursor

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 20.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (4.16GB free)|
|Process Argv|--crash-reporter-id 1db29968-f58e-4f4d-ac81-bbfdb50dcaf5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (56)</summary>

Extension|Author (truncated)|Version
---|---|---
swagger-viewer|Arj|3.1.2
atlascode|atl|2.10.12
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
gitlens|eam|13.1.1
vscode-great-icons|emm|2.1.86
vscode-pull-request-github|Git|0.56.0
cypher-query-language|jak|2.0.0
cmake-language-support-vscode|jos|0.0.7
vsc-python-indent|Kev|1.18.0
vscode-simple-icons|Lau|1.16.0
MagicPython|mag|1.1.0
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
file-downloader|min|1.0.12
vscode-docker|ms-|1.23.1
vscode-dotnet-runtime|ms-|1.6.0
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2022.20.0
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.7
autodocstring|njp|0.6.1
oracledevtools|Ora|21.5.0
csv-to-table|php|1.4.0
material-icon-theme|PKi|4.22.0
java|red|1.13.0
vscode-commons|red|0.0.6
vscode-xml|red|0.22.0
vscode-yaml|red|1.10.1
vscode-bucket-explorer|ref|1.0.0
markdown-preview-enhanced|shd|0.6.5
indenticator|Sir|0.7.0
ayu|tea|1.0.5
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-gradle|vsc|3.12.6
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.1
vscode-icons|vsc|12.0.1
jinja|who|0.0.8
current-file-path|Yos|3.1.0
material-theme|zhu|3.15.6
vscode-proto3|zxh|0.5.5

(21 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by nirfuzz** [comment]
+1, please fix this, it's terribly annoying

**Comment by peterdeme** [comment]
ZSH auto-completions stopped working too

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/168396

already fixed in insider's and soon to be fixed in our recovery release (tomorrow)
