### ISSUE TITLE
python path not being read at run time in muti-root workspace

### ISSUE THREAD

**Issue by alpha-insite** [microsoft/vscode#168794]
This is in regards to this issue which i have had no luck in getting feed back from:  https://stackoverflow.com/questions/74758616/vscode-multi-root-workspace-specifying-python-path-in-env-files

1. basically i would like to conditionally load the python paths based on different .env files driven my the OS im running under, either windows or linux (via WSL).  The problem is i cant even get a multi-root workspace to load these paths regardless if i put them in my env file or if put them in my settings.json
 
This is what the folder structure in vscode looks like:
![image](https://user-images.githubusercontent.com/855627/206924653-ce2d0191-879e-4637-8ff9-ee202075a268.png)

here are the relevant files' content in my current state - at this point im just adding python paths everywhere given im not sure exactly which of these settings are needed - and the documentation isnt clear with regards to multi-root workspaces how these various means of setting python paths should be ideally set.  In also just trying to get this to run on windows for now:

**project1:launch.json:**
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Run App",
            "type": "python",
            "request": "launch",
            "program": "${workspaceFolder:project1}/src/app/app.py",
            "console": "integratedTerminal",
            "justMyCode": true,
            "windows": {
                "envFile": "${workspaceFolder:project1}/.env"
            },
            "linux": {
                "envFile": "${workspaceFolder:project1}/.env_linux"
            }               
        }
    ]
}
```

**project1: settings.json:**
```
    "terminal.integrated.env.windows": {
        "python.envFile": "${workspaceFolder:project1}/.env",
        "python.pythonPath":"${workspaceFolder:project1}/src:${workspaceFolder:project1}/src/app:${workspaceFolder:project1}/utils",
        "PYTHONPATH":"${workspaceFolder:project1}/src:${workspaceFolder:project1}/src/app:${workspaceFolder:project1}/utils",
    },
    "terminal.integrated.env.linux": {
        "python.envFile": "${workspaceFolder:project1}/.env_linux",
    },
    "python.envFile": "${workspaceFolder:project1}/.env",
```

**.env file**
`PYTHONPATH=./src:./src/app:./src/utils:./project1/src:./project1/src/utils:./src/app:./src/services`

**project1:app.py**
`from utils import utils`

So i know it's reading the launch.json located in project1/.vscode, as the debug configuration shows up and i can run->debug.
The problem is when it run the app.py file, at the import above, i see the error:  
`No module named 'utils'`

so that tells me it's not finding the python paths either in the .env file or the settings.json file.   

1. What it the proper way to loading python path for specific projects in multi-root workspace project
2. Can this be done using .env file instead of a settings.json given that at run time, i would be using the .env file and avoids having to maintain python paths for the project in multiple places
3. Can we selective load different python paths in vscode depending on wether im running vscode on windows or whether in running on linux (via WSL)

**Comment by roblourens** [comment]
If you think there is an issue with the python extension, please file this on the vscode-python repo

**Comment by alpha-insite** [comment]
Man, it took a long time to compose this post.  That was a dudder of a response.   Like that lately around here it seems

**Comment by roblourens** [comment]
I appreciate the detailed issue report. It helped me figure out quickly that there's nothing I can do for you over here. You can copy/paste that into a report on the extension's repo (along with whatever other info they ask for) and it will be a good report for them as well.
