### ISSUE TITLE
high contrast mode - border in editor overlaps text

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16871]
Testing #15811 

See below: 
![image](https://cloud.githubusercontent.com/assets/762848/20992331/4f31ea66-bc98-11e6-848b-035ea444b70f.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by alexandrudima** [comment]
I've reduced the border width from 2px to 1px:

![image](https://cloud.githubusercontent.com/assets/5047891/24921835/7c332104-1eec-11e7-89ce-0a310c9dadfe.png)
