### ISSUE TITLE
Single nested file in folder is revealed even though "explorer.autoReveal": false setting

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [microsoft/vscode#168791]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Win10 64bit

Single nested file in folder is revealed even though "explorer.autoReveal": false setting.

Here is a gif: 
![nested](https://user-images.githubusercontent.com/110549389/206922230-e025a014-4819-4c51-91db-452717a221dd.gif)

My pattern is 
```json
"explorer.fileNesting.patterns": {
    "+page.svelte": "${basename}.js, ${basename}.server.js",
    "+layout.svelte": "${basename}.js, ${basename}.server.js"
  },
 ```
settings are 
```json
  "explorer.fileNesting.enabled": true,
  "explorer.fileNesting.expand": false,
  "explorer.autoReveal": false
```

Steps to Reproduce:

1. Open an empty folder.
2. Create a folder.
3. In the folder, create +page.svelte
4. In the folder, create +page.js
5. Close the nesting on +page.svelte by clicking the arrow.
6. Close the folder.
7. Open the folder.
8. The folder is opened with +page.svelte and +page.js autorevealed.
Expected: The folder is opened with only +page.svelte visible.

9. In the folder, create a new folder.
10. Close the nesting on +page.svelte by clicking the arrow.
11. Close the top folder.
12. Open the top folder.
13. The folder is opened with only +page.svelte visible and the newly created folder visible.

So, this works as expected with nested files which have folder or file siblings but not when they are the only files in a folder.

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/149084
