### ISSUE TITLE
Feature: Add Terminal toggle shortcut in side bar or in footer

### ISSUE THREAD

**Issue by aksdevac** [microsoft/vscode#168709]
After using IntelliJ IDE with new design I feel like it will be useful if VSCode can add terminal shortcut in primary side bar like it.

Currently only way to show/hide terminal is using keyboard shortcut.

It can be added in bottom part of sidebar or in footer.

<img width="586" alt="vscode-terminal" src="https://user-images.githubusercontent.com/2557058/206843214-d37dd53b-eb10-4540-8d8d-454b142f9d80.png">

Also currently it shows Cross icon for closing terminal but actually it behaves like hide, so it should use minimize icon instead.

**Comment by gjsjohnmurray** [comment]
Clicking on the V icon at the right end of the Panel header should hide it. Then click the problems / warnings counts in the status bar to show it.

**Comment by aksdevac** [comment]
Clicking problems/warnings requires tab change (so two clicks) as it opens Problems tab by default, & that up, down arrow like icon is for minimize & maximize. 
currently I am using running task icon in footer for toggle (because of some issue with my mac's Ctrl key ) but it only appears if task is running & it opens task view in terminal by default.

**Comment by gjsjohnmurray** [comment]
You are correct. I misremembered.

An extension called Bottom Terminal seems to do what you want.

**Comment by sbatten** [comment]
There are a couple of ways to bring up the bottom panel which would keep the tab which you last used:
1) Drag up the sash between the status bar and the editor area.
2) Use the layout control in the top right of title bar.

If you want to shortcut straight to the terminal from the status bar, an extension can do this as mentioned by @gjsjohnmurray
