### ISSUE TITLE
[Feature] Show time stamp and zone when code cell last ran

### ISSUE THREAD

**Issue by rrmistry** [microsoft/vscode#168792]
Would be good to capture when the code cell ran at the bottom of the cell.

For example:
![image](https://user-images.githubusercontent.com/25514145/140329952-1ff7d3fd-6fc3-43af-a0fa-757ec458c53c.png)

This could be toggled with a switch if it is too verbose

**Comment by maciejkos** [comment]
Thanks for working on it @roblourens ! 

I think a tooltip would be helpful in some use cases. What I think most people would want is what the [last_executed_time](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/execute_time/readme.html) Jupyter extension implements (as @greggman mentioned).

**Comment by rrmistry** [comment]
Hi @roblourens,

Thanks for the work!

_____

It would still be nice to show timestamps directly in UI (without the tooltip)

Would you recommend:

* Creating a new issue to track it in the backlog?
    _OR_
* Re-Open this issue?
    _OR_
* Is the VS Code team not planning on creating the display as the suggested example screenshot?
    ![screenshot](https://user-images.githubusercontent.com/25514145/140329952-1ff7d3fd-6fc3-43af-a0fa-757ec458c53c.png)

**Comment by wmayner** [comment]
Thank you for the tooltip! I second the previous comment, though—having it directly on the UI, so it can be seen at a glance, would be great.

**Comment by roblourens** [comment]
We can look into having this behind a setting. I'd prefer to enable extensions to contribute this, but we don't have the right API for it.

**Comment by nicocanali** [comment]
Thanks a lot for this feature!

Another suggestion could be to persist this somehow (maybe with notebook tags?). For example, see how Colab does it:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/5569767/208873715-95bbb178-e00c-4ef9-b464-72dcf0c1de10.png">

**Comment by tosaric** [comment]
Is this feature already implemented, and if yes, how to add it?

**Comment by joaofbravo** [comment]
> Is this feature already implemented, and if yes, how to add it?

Wondering the same

**Comment by marctorsoc** [comment]
> Thanks a lot for this feature!
> 
> Another suggestion could be to persist this somehow (maybe with notebook tags?). For example, see how Colab does it:
> 
> <img alt="image" width="228" src="https://user-images.githubusercontent.com/5569767/208873715-95bbb178-e00c-4ef9-b464-72dcf0c1de10.png">

See my long comment here: https://github.com/microsoft/vscode-jupyter/issues/13338#issuecomment-1645393350

**Comment by Yoyokrazy** [comment]
This will be available in tomorrow's insiders, via the setting `notebook.cellExecutionTimeVerbosity`

Default will maintain the current duration + hover appearance, with verbose now looking like the following image. The tooltip will stay the same in both cases for overhead and render times.
![Image](https://github.com/user-attachments/assets/aafb6b0c-126b-4967-adaa-c68bd0a54d77)

If you have further feedback, please feel free to bring it up here 👍

**Comment by lcnittl** [comment]
Amazing new feature! I couldn't find the following: Is it possible to change the datetime format of the last execution" time? (Are there plans to make it adjustable?)
