### ISSUE TITLE
Menu items should get greyed out if they are are no longer applicable

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16875]
Testing #15811

Menu items should get greyed out if they are are no longer applicable. E.g. Undo/Redo commands should not be displayed if we are at the bottom/top of the undo stack. Same with back/forward. In the cases below, "back" and "redo" both appear to be valid commands, even though they won't do anything. 

![image](https://cloud.githubusercontent.com/assets/762848/20992573/bbcb15a2-bc99-11e6-9c4a-39fd82187dab.png)

![image](https://cloud.githubusercontent.com/assets/762848/20992539/89d0cbdc-bc99-11e6-930f-bf5723d02b99.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/991
