### ISSUE TITLE
Unable to open markdown preview

### ISSUE THREAD

**Issue by lucadallesasse** [microsoft/vscode#168769]
Type: <b>Bug</b>

Good morning, i'm not able to open markdown preview and the system seems to be not able to recognize any markdown configurations. How can i fix it?

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (4.24GB free)|
|Process Argv|--crash-reporter-id 01904cb0-e93d-49a5-babc-e0cb851ff3a8|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
better-cpp-syntax|jef|1.17.2
vscode-docker|ms-|1.23.1
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.7
cpptools-extension-pack|ms-|1.3.0
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by lucadallesasse** [comment]
Start Extension Bisect is not able to detect the problem and it seems to be not caused by extensions

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

**Comment by lucadallesasse** [comment]
No. With the latest VS Code insiders build it works without any problem. Should I keep this build now or there is something I can do with the previous version?

**Comment by mjbvz** [comment]
Thanks for testing. I suspect that you may have disabled the builtin markdown extension. In the extensions view, search `@builtin markdown` and make sure `Markdown Language Features` is enabled:

<img width="596" alt="Screenshot 2022-12-13 at 1 53 26 PM" src="https://user-images.githubusercontent.com/12821956/207452052-22100b01-5ea5-4359-adb6-835df4e193a4.png">

If that's not the case, it's possible there is a bug in the current stable build that has already been fixed in insiders
