### ISSUE TITLE
The hover color of the close caption button of does not match Windows 11

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/vscode#168717]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: 22H2

Steps to Reproduce:

1. Open VS Code
2. Hover over close button

Screenshots:
<img width="720" alt="image" src="https://user-images.githubusercontent.com/51363864/206852854-87bac016-2d20-46c2-b53b-e6eb4f2fcbeb.png">
Indeed, the maximise icon is somehow asymmetrical?

Windows 11 now has a darker hover color

**Comment by sbatten** [comment]
This is not consistent. Our hover color matches that of several built-in apps such as: File Explorer, Edge, and Notepadd

**Comment by Poopooracoocoo** [comment]
>This is not consistent

That's why I opened the issue.

> Our hover color matches that of several built-in apps such as: File Explorer, Edge, and Notepadd

VS Code does _not_ match the new Windows 11 close caption button hover color. Edge is another culprit. I noticed that an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1320101) was filed for Chromium. I have updated the issue to include additional screenshots.

**Comment by Poopooracoocoo** [comment]
Still seeing this with version 1.81.0.

**Comment by Poopooracoocoo** [comment]
Still seeing this with version 1.89.0
