### ISSUE TITLE
git sidebar doesn't refresh after adding "large folders" to .gitignore

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16877]
Testing #15811

See below - reloading the window after you get into this state yields the appropriate behavior.

![image](https://cloud.githubusercontent.com/assets/762848/20992716/c7ed33aa-bc9a-11e6-9637-2cfc2ebac952.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by joaomoreno** [comment]
This no longer exists.
