### ISSUE TITLE
js/ts.implicitProjectConfig.checkJs error underlining something as not working, but it is

### ISSUE THREAD

**Issue by 1Euro7Cent** [microsoft/vscode#168726]
Does this issue occur when all extensions are disabled?: Yes

- Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

Steps to Reproduce:

1. have `"js/ts.implicitProjectConfig.checkJs": true,` in the settings.json 
2. have the following block in a .js file:
```js
const b = "something"

class A {
    constructor() {
        this.b = "something"
    }
    toString() {
        return this.b
    }
}
let a = new A()
if (a == b) { // it undelines this with error: This comparison appears to be unintentional because the types 'A' and 'string' have no overlap.
    console.log("it is true")
}
else {
    console.log("it is false")
}
```
when I run it I get `it is true` in the console

It seems like it does not check if there is a `toString` function in that class. In boolean comparisons NodeJS autocalls that function before comparing.

**Comment by mjbvz** [comment]
Closing as upstream

(Honestly you should probably refactor any code that does this though)
