### ISSUE TITLE
can't see what I am typing in terminal

### ISSUE THREAD

**Issue by user193647** [microsoft/vscode#168787]
Hi, I am new to this but after not being able to type anything into my terminal I have managed to change something in settings which means I now can but I can't see what I am typing. The cursor is moving but I can't see what is being written, when copy/pasting what is in the terminal I see that it is working fine just not showing me what is written.

Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15
Embedder: codespaces

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
