### ISSUE TITLE
C_Cpp.enhancedColorization is not found

### ISSUE THREAD

**Issue by rababR1** [microsoft/vscode#168763]
Does this issue occur when all extensions are disabled?: Yes/No _**No**_

- VS Code Version: 1.75 Insiders
- OS Version: Windows 11

Originally, C_Cpp.enhancedColorization was present in the settings of VSCode.

However, I messed up (because I installed waaaayyy too many extensions), so I had to uninstall it. Reinstalled and had some issues with some "cppbuild" not showing up (fixed that by installing Build ++ and then doing `npm install cppbuild`, which worked.) And, now....

I get this:

![image](https://user-images.githubusercontent.com/65360255/206889197-cdfb4b0c-6cd3-411e-b07d-92a56b86e282.png)

**Comment by gjsjohnmurray** [comment]
You probably haven't reinstalled the extension which defines this setting.

**Comment by rababR1** [comment]
What extension?

**Comment by gjsjohnmurray** [comment]
I don't know. Maybe use Extensions view to search, then check the Contributes tab of ones that look familiar to you.

**Comment by rababR1** [comment]
Installed the C++ Extension. It now shows up! 🥳

**Comment by gjsjohnmurray** [comment]
Good. Please close this issue.
