### ISSUE TITLE
partially minified source in vscode sourcemap content

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/vscode#168774]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Ubuntu 22.10

### code displayed in devtools
```
if (isFirefox) {
				// Firefox: requires to set a text data transfer to get going
				this.B(addDisposableListener(container, EventType.DRAG_START, e => e.dataTransfer?.setData(DataTransfers.TEXT, this._action.label)));
			}
```

### actual source code

```
if (isFirefox) {
				// Firefox: requires to set a text data transfer to get going
				this._register(addDisposableListener(container, EventType.DRAG_START, e => e.dataTransfer?.setData(DataTransfers.TEXT, this._action.label)));
			}
```

 `this.B` is displayed instead of `this._register`.

### Steps to Reproduce:

1.  Open Devtools in VSCode
2.  Inspect for example src/vs/base/browser/ui/actionbar/actionViewItems.ts
3. The file is different from the source in [src/vs/base/browser/ui/actionbar/actionViewItems.ts](https://github.com/microsoft/vscode/blob/main/src/vs/base/browser/ui/actionbar/actionViewItems.ts)

![sourcemap2](https://user-images.githubusercontent.com/23744935/206903075-1674ca0f-431a-4b40-b80f-0ef440a7f9f5.png)

**Comment by gjsjohnmurray** [comment]
Maybe a consequence of microsoft/vscode-discussions#257?

**Comment by jrieken** [comment]
😬 I was waiting for this. The private-property mangling process doesn't produce source maps. I gave it an unsuccessful try here but I guess I need to better understand how source maps, and source map merging, is meant to work.

**Comment by SimonSiefke** [comment]
Thank you @jrieken!
