### ISSUE TITLE
Use the "lorem" snippets in file extensions other than the ones managing HTML

### ISSUE THREAD

**Issue by sneko** [microsoft/vscode#168714]
Hi,

Currently we can use `lorem` snippets without any extension when it's related to HTML, so it will work within `.tsx` or `.html` files for example. Note that in `.tsx` file I can use the snippet in the Typescript code (even if not in a templating section).

I would like to extend this behavior and make them working also in `.ts` or `.mdx`. Is there a setting for this? I did not find it. If it does not exist, that's my feature request :)

Thank you,

EDIT: ok just saw those snippets were managed by the embedded extension "Emmet". They specify how to use their features on other file extensions https://code.visualstudio.com/docs/editor/emmet#_emmet-abbreviations-in-other-file-types but I'm not quite sure how it will "pollute" working on those other types since it's not like saying "just allow `lorem` snippets on another file extension".

**Comment by rzhao271** [comment]
If you want just lorem, I think another extension like [Tyriar.lorem-ipsum](https://marketplace.visualstudio.com/items?itemName=Tyriar.lorem-ipsum) would be better.
