### ISSUE TITLE
Excluding files in the sidebar doesn't work on files with square brackets in the folder name

### ISSUE THREAD

**Issue by CodexHere** [microsoft/vscode#168715]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.74.0 (system setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: No

Steps to Reproduce:

1. Have 2 paths in the workspace: 
    * some/path/[excludeMe]   (with brackets)
    * some/path/excludeMe     (without brackets)
2. Try to exclude the files via `settings.json`:

```json
{
  "files.exclude": {
    "[excludeMe]": true,
    "excludeMe": true
  }
}
```

With brackets, it doesn't hide. Escaping the brackets has no effect.

**Comment by gjsjohnmurray** [comment]
How did you escape them?

**Comment by CodexHere** [comment]
It complains about single back slashes, so I tried double slashes.Did I miss a special character for escaping? I was just following JSON convention.On Dec 10, 2022 12:47 PM, John Murray ***@***.***> wrote:
How did you escape them?

**Comment by gjsjohnmurray** [comment]
Please try `[[]excludeMe[]]`

**Comment by CodexHere** [comment]
OK, this got it to work:

` **/[[]gamemodes[]]`

Required the `**/` glob at the start, but overall this works now I know the trick! Thanks!
