### ISSUE TITLE
Keybindings Interface: Search by Key Combo and Export Option

### ISSUE THREAD

**Issue by iPoetDev** [microsoft/vscode#168723]
Type: <b>Feature Request</b>

Dear Team,

I am just getting up to speed with Keybindings and I find the Kinbingds interface unwieldly.

Please add a full text search by key combos and also make the keybings exportable by JSON, CSV etc for backup and porting.

Kind regards
Charles

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by sandy081** [comment]
> Please add a full text search by key combos

Can you please provide an example?

> make the keybings exportable by JSON, CSV etc for backup and porting.

Keybindings are backed by a JSON file, you can see it by clicking on the following action in the keybindings editor. You can use our Settings Sync feature for back up or Profiles (in preview) feature for exporting.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/10746682/207009925-8a12e4af-8971-43d1-bd31-23ec3e47cace.png">

**Comment by iPoetDev** [comment]
![image](https://user-images.githubusercontent.com/51715025/207127966-6cbaf759-dea5-4075-b9ef-5b91db5fbadb.png)

Of course, Actually, My bad, scratch that. I can search, I just was typing in the wrong keystrokes, as I am dyslexic/dysgraphic/mind blind sometimes.

As for export, I have been struggling to find the export function for the JSON as I don't have the same icons.

![image](https://user-images.githubusercontent.com/51715025/207128725-f34f2b7a-9756-490b-8c08-8b4af6b0ee40.png)

Also having it in a non json format would help with porting to non IDE systems. For instance, I wanted to create an IDE independent keymap in a table format in Notion (for example) and then manage and monitor the keys and learn in an out of context way, so am not coupled to the IDE.

**Comment by sandy081** [comment]
You can use this command to see the defaults:

F1 > Preferences: Open Default Keyboard Shortcuts (JSON)
