### ISSUE TITLE
regression? "launch program" selection menu opens up to side

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16883]
Testing #15811

Clicking directly on the "Launch Program" selection menu does not open menu
![image](https://cloud.githubusercontent.com/assets/762848/20993609/4468c782-bca0-11e6-8acb-16dba08025a5.png)

Instead you must click directly on the arrow, which opens it up to the side (and in a smaller font)
![image](https://cloud.githubusercontent.com/assets/762848/20993628/5d96a544-bca0-11e6-9249-7f2c7b232cc4.png)

Seems to be a regression from the  behavior in 1.7
![image](https://cloud.githubusercontent.com/assets/762848/20993646/7af68186-bca0-11e6-9123-b9ba812b5a54.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by isidorn** [comment]
Fixed in latest
