### ISSUE TITLE
Should not be possible to open 683 instances of VS Code in one user action

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16882]
Testing #15811 

Steps to Reproduce:
1. select all the directories in the VS Code node_modules folder
2. drag into file view

![image](https://cloud.githubusercontent.com/assets/762848/20991918/dd354978-bc95-11e6-95c3-4d7531c9c95d.png)

3. watch (5 min) 🍿 as VS Code transforms itself into a winning game of FreeCell

![image](https://cloud.githubusercontent.com/assets/762848/20993278/08b84c00-bc9e-11e6-8d65-6f5ae3204d1e.png)

4. Eventually VS Code will crash 

Video: https://youtu.be/ZTtuOdMqzJY

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by roblourens** [comment]
Well I can't think of anything better to do for 5 minutes.

**Comment by mousetraps** [comment]
@roblourens yeah, well it's between locking up your computer and coming up with more BuzzFeed style headlines. Tough call.

**Comment by opus-2** [comment]
I laughed.

**Comment by bpasero** [comment]
Since there is a fixed limit of memory VSCode can claim, you likely hit the out of memory case quickly in this setup. I am sure opening 683 instances of other applications can cause similar behaviour.

**Comment by roblourens** [comment]
Maybe vscode could ask to confirm before opening 683 instances, since someone could be trying to add folders to a "project", not knowing that we'll open a new instance for each one.

**Comment by opus-2** [comment]
I believe this is not about the software, it's called humour. ;-)


Em 08/12/2016 07:08, Benjamin Pasero escreveu:

**Comment by mousetraps** [comment]
Well it was mostly about the software. There were a lot of things that went wrong here. 
* you shouldn't be able to open 600 instances of anything in one user action. 
* dragging a folder into VSCode should probably copy those into the project, as we do with files, not open up new instances. 
* the visual indicator said "move" / "copy", not "open new instance"
* if we have a drag into editor to open instance option, would probably be reasonable to allow for only one at a time.
* any long-running action (eg whether it be opening 600 instances or otherwise) should be cancellable

**Comment by bpasero** [comment]
Verify: dropping > 20 folders brings up a dialog like this:

![image](https://cloud.githubusercontent.com/assets/900690/22116286/4fe4ffda-de70-11e6-8069-e59e54daacdb.png)
