### ISSUE TITLE
"Unable to write user settings" info bar should include a link to user settings

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16880]
Testing #15811

We're asking people to go there, so might as well remove a step and link them there. 

![image](https://cloud.githubusercontent.com/assets/762848/20993102/072fb6d0-bc9d-11e6-8299-2769bf850fd1.png)

<hr>

- VSCode Version: Code - Insiders 1.8.0-insider (7499a9f3c565f4fbe5205e30c8664e5a5a11ae94, 2016-12-06T16:16:15.865Z)
- OS Version: Windows_NT ia32 10.0.14965

**Comment by sandy081** [comment]
Duplicates #16580
