### ISSUE TITLE
Profiles actions are shown in too many places

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#168865]
We have noticed in the user study that users interact with profiles in different ways and they do not find the indication of active profile super useful. We should also be aware of all the Menus that profiles are present in right now in addition to the Profile activity bar item are confusing.

* Main menu
* Account activity bar item
* Gear activity bar item

**Comment by sandy081** [comment]
After discussing in today's stand up we agreed upon having its own space for profiles and therefore we wanted to show profile indicator and drop the actions in accounts and gear menus. We shall investigate on how to make this profile indicator appealing to users - https://github.com/microsoft/vscode/issues/166983

**Comment by isidorn** [comment]
Looks great -> verified
