### ISSUE TITLE
auto complete is buggy with Remix js projects 

### ISSUE THREAD

**Issue by aniketicloud** [microsoft/vscode#168871]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1.  add any named export function in `app/data/name.server.js`
2.  in `app/routes` folder at any route like `index.js`; type this named export.
3. most of the times it never shows.
4. The same is true for newly installed package.
5. do `npm install bcryptjs`
6. in `app/routes` folder at any route like `index.js`; type any named import from this new package
7. most of the times it never shows.
8. 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/54700318/207087210-8edee837-3ff4-40c0-8e88-e82d5082ebb0.png">

**Comment by aniketicloud** [comment]
Version: 1.74.0 (user setup)
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:38:16.075Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please put together a minimal example project that demonstrates the issue

**Comment by mjbvz** [comment]
Thanks for testing. Please file an issue against that extension since it seems to be the cause of of the problem

**Comment by aniketicloud** [comment]
- I got the same issue today again.
- So I disabled all the extensions. I had to reload the VS Code. Auto import worked again. 
- I restarted the VS Code again. I did `npm run dev` in my Remix project. Now Auto Import was NOT working properly.
- Here is the link to my Remix Project. Maybe you can clone try to reproduce the issue.
- https://github.com/aniketicloud/remix-expense-manager

**Comment by shreedharhegde99** [comment]
Even after disabling all the extensions, the auto-import feature is not working. It's working only if you keep open that component in a new tab/side by side. 

### When not open side by side 

![Screenshot from 2022-12-16 20-36-20](https://user-images.githubusercontent.com/90758718/208127551-c07ff1bf-51d0-463d-b58b-f120c3f80919.png)



### When open side by side
![Screenshot from 2022-12-16 20-31-39](https://user-images.githubusercontent.com/90758718/208127405-ef17737e-2cc0-4201-98d7-eed64ec4ef95.png)


```
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:35:03.979Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: No
```

**Comment by mjbvz** [comment]
If it works when the file is open but not when it is closed, your project is likely misconfigured. Make sure both the file you are working in and the file with the symbol you want to import are in the same jsconfig/tsconfig project. You can check this by clicking on the `{}` in the status bar:

<img width="725" alt="Screenshot 2022-12-16 at 11 09 17 AM" src="https://user-images.githubusercontent.com/12821956/208171183-c0fea51a-3275-4978-ae5e-aca318a1f74b.png">
