### ISSUE TITLE
Caret is only animated when cursor is moved with arrow keys, not when typing

### ISSUE THREAD

**Issue by westernwontons** [microsoft/vscode#168857]
Type: <b>Bug</b>

1. Have the `"editor.cursorSmoothCaretAnimation"` set to `true`
2. Move the cursor around with arrows. Animation is there.
3. Type something. Animation is not there.

VS Code version: Code - Insiders 1.75.0-insider (250a8f36c93721830b0ef2e39dc065d6944d9912, 2022-12-12T05:36:38.306Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (42)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
vscode-nginx-conf|ahm|0.1.3
ng-template|Ang|15.0.2
vscode-tailwindcss|bra|0.9.1
better-toml|bun|0.3.2
npm-intellisense|chr|1.4.3
vscode-eslint|dba|2.3.0
vscode-quick-select|dba|0.2.9
xml|Dot|2.5.1
gitlens|eam|13.1.1
scroll-faster|Enk|0.2.2
prettier-vscode|esb|9.10.3
vscode-jest-runner|fir|0.4.59
auto-rename-tag|for|0.1.10
shell-format|fox|7.2.2
macros|ged|1.2.1
vscode-pull-request-github|Git|0.57.2022120809
vscode-postfix-ts|ipa|1.11.3
Angular2|joh|13.0.0
center-editor-window|kai|2.3.0
graphql-for-vscode|kum|1.15.3
vscode-clangd|llv|0.1.23
ts-error-translator|mat|0.5.1
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.1
black-formatter|ms-|2022.7.13271013
isort|ms-|2022.9.13271012
python|ms-|2022.21.13431008
vscode-pylance|ms-|2022.12.21
vscode-typescript-next|ms-|5.0.202212110
vsliveshare|ms-|1.0.5788
prisma|Pri|4.7.1
vscode-yaml|red|1.10.1
better-pageup-pagedown|rus|0.0.1
rust-analyzer|rus|0.4.1316
vs-code-prettier-eslint|rve|5.0.4
justfile|scl|2.1.0
vscode-scss-formatter|sib|2.4.4
shellcheck|tim|0.29.1
vscode-input-sequence|tom|0.2.0
errorlens|use|3.6.0
vscode-lldb|vad|1.8.1

(1 theme extensions excluded)

</details>

**Comment by gjsjohnmurray** [comment]
Maybe related to #168748

/assign @alexdima

**Comment by alexdima** [comment]
@westernwontons This was an intentional change to disable the animation when typing/deleting. See https://github.com/microsoft/vscode/issues/109787

**Comment by westernwontons** [comment]
@alexdima okay, that makes perfect sense. closing.

**Comment by sumneko** [comment]
> We have intentionally removed animating the cursor when typing for #109787 which explicitly asks us to do that. But I think some folks actually prefered the old behavior of animating also when typing?

Yes, I love the animating when typing.

**Comment by westernwontons** [comment]
A good common ground could be that it becomes a setting to also have the caret animated while typing

**Comment by rababR1** [comment]
> 

Yeah. I like the animation....

**Comment by alexdima** [comment]
I've pushed a change where there will be 3 possible values for `cursorSmoothCaretAnimation`:
- off: Smooth caret animation is disabled
- explicit: Smooth caret animation is enabled only when the user moves the cursor with an explicit gesture. This should cover users who don't want it like in issue #109787
- on: Smooth caret animation is always enabled

**Comment by rababR1** [comment]
> 

Thank you so much!

**Comment by scellige** [comment]
@alexdima thank you for the changes. I noticed now cursorSmoothCaretAnimation is turned on by default and can't be turned off at all. Looks like a bug.

**Comment by gjsjohnmurray** [comment]
@scellige see #169171 which is already fixed.
