### ISSUE TITLE
Autocomplete with dash

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#16888]
- VSCode Version: Code - Insiders 1.8.0-insider (0d65ced0fa7398dc9d50c39a23a2a8cc8406ff18, 2016-12-07T07:05:09.124Z)
- OS Version: Darwin x64 16.1.0
---

Steps to Reproduce:

1. TypeScript
2.
![image](https://cloud.githubusercontent.com/assets/1723815/20995913/149e4018-bcc8-11e6-85c2-1b0b7f07261c.png)

3. Hit Enter
4. 
![image](https://cloud.githubusercontent.com/assets/1723815/20995923/26203e72-bcc8-11e6-8ff3-0aa1af888513.png)

**Comment by leaxoy** [comment]
That's a really annoying bug! Not just in `typescript`.

**Comment by jrieken** [comment]
@mjbvz The TypeScript extension tells the editor to only delete the 2 preceding characters, not the entire word. That might be a problem with the work definition you are using.

![screen shot 2016-12-08 at 10 09 37](https://cloud.githubusercontent.com/assets/1794099/21004005/91d07c34-bd2e-11e6-95be-eb6284d4d914.png)

**Comment by jrieken** [comment]
I have extrapolated about snippets to the following piece of code

```ts

type abc = 'string-multiline' | 'string-singleline';

let _a: abc;

_a = 'string-mu'

```

**Comment by mjbvz** [comment]
I think that Typescript needs to be explicit in this case, and provide a range for the completion items. We currently automatically pick up the range from `TextDocument.getWordRangeAtPosition`

**Comment by waderyan** [comment]
@mjbvz do you know if this is tracked on TS's side? I want to make sure I have it tracked in the OneNote table appropriately.

**Comment by mjbvz** [comment]
@waderyan I don't think this is an issue on the TypeScript side. The bug was that we were relying on the default VSCode logic for determining what word to replace, and it breaks words that contain `-` or any other non letter or digit characters.

The result TypeScript provides to us is correct as far as I know
