### ISSUE TITLE
Cursor position is wrong after go to definition, then go back, twice

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16881]
- Open textSearch.ts in vscode
- Put the cursor on the `ISerializedFileMatch` in `export class Engine implements ISearchEngine<ISerializedFileMatch>`
- Go to definition
- Go back (cursor is in the right place)
- Go to definition
- Go back (cursor is somewhere else)

This also reproes in stable. In insiders, the cursor is at the top of the file. In stable, it's just off by one line. Trying in other places, it happens in lots of cases but not all. Always every other iteration.

**Comment by bpasero** [comment]
@roblourens nice catch, keep em comin' ;)
