### ISSUE TITLE
Missing `TextEditorOptions.indentSize` API type

### ISSUE THREAD

**Issue by tao-cumplido** [microsoft/vscode#168836]
Setting the `TextEditorOptions.tabSize` setting in an extension behaves differently since the introduction of the new `indentSize` setting, as it only sets the tab size and not anymore the indent size, which, as I understand it, is intended behavior (#168745). Now, there is no `indentSize` property on the `TextEditorOptions` interface, ignoring TypeScript and setting it anyway does work though.

This currently affects the EditorConfig extension. See https://github.com/editorconfig/editorconfig-vscode/issues/341#issuecomment-1344255324

**Comment by alexdima** [comment]
To reproduce, you can use the following settings:
```
{
	"editor.tabSize": 2,
	"editor.detectIndentation": false,
	"editor.insertSpaces": true
}
```
And then the following extension:
* `package.json`:
```json
{
    "name": "168836",
    "publisher": "alex",
    "version": "1.0.0",
    "engines": {"vscode": "^1.22.0"},
    "main": "main.js",
    "activationEvents": ["*"]
}
```
* `main.js`:
```js
const vscode = require('vscode');
exports.activate = function(context) {
    setTimeout(() => {
        console.log(`SETTING tabSize to 4`);
        vscode.window.activeTextEditor.options.tabSize = 4;
    }, 3000);
}
```

**Comment by fwcd** [comment]
Is adding `TextEditorOptions.indentSize` to the API still planned?

**Comment by abdella0983** [comment]
R3CM90C7F9W
