### ISSUE TITLE
lagging, unresponsive window due to JavaScript intellisense?

### ISSUE THREAD

**Issue by metame** [Microsoft/vscode#16886]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 15.10

Steps to Reproduce:

1. 3000 line JavaScript file with multiple imports (es6), client-side javascript project
2. jsconfig.json to exclude all files except those within my project

Navigating through the file lags a lot (using keyboard arrow keys mostly).  Seems to especially freeze when the cursor lands on a symbol, assumedly trying to infer type, look up symbol reference/declaration.  I get the "Do you want to reload this window" unresponsive error often, but mostly just 1-10 second freezes.

**Comment by mjbvz** [comment]
Are you able to share your workspace so that we can investigate this further? Also, do you have any extensions installed?

**Comment by mjbvz** [comment]
Closing as more info is needed to investigate.

Please try upgrading to VSCode 1.8 and let me know if you still see this problem after disabling all extensions. If you do, please share the problematic file and some repo steps so that we can investigate. 

Thanks.

**Comment by metame** [comment]
1.8 seemed to have fixed it
