### ISSUE TITLE
Be able to attach debugger commands to the debug restart button

### ISSUE THREAD

**Issue by fredo514** [microsoft/vscode#168881]
To be able to use VS code for embedded development efficiently, the debug restart button should only send a reset command to the debugger, not re-start an entire debug session.

Maybe this could be achieved by exposing some interface hooks, or letting the command be replaced with a task?

**Comment by roblourens** [comment]
This is what happens when a debug adapters sends the `supportsRestartRequest` capability

**Comment by thegecko** [comment]
In this case would you expect that any 'preLaunchTask' is re-executed?

**Comment by fredo514** [comment]
Probably not, I'm really only looking for a way to reset the target without restarting the entire debug session.

**Comment by thegecko** [comment]
> Probably not, I'm really only looking for a way to reset the target without restarting the entire debug session.

Sorry, I meant this question to the VS Code team (@roblourens ?). I would not expect any `preLaunchTask` to execute when `supportsRestartRequest` is supported as it should just reset the debug session, however my experience and these issues suggest this isn't the case:

https://github.com/microsoft/vscode/issues/102296
https://github.com/microsoft/vscode/issues/28979

**Comment by roblourens** [comment]
Yeah, it seems that the decision in the past has been that this should be consistent regardless of how restart is implemented, and I still think that sounds correct.
