### ISSUE TITLE
Splitting terminal in directory with ë character fails

### ISSUE THREAD

**Issue by liam-nt** [microsoft/vscode#168804]
Does this issue occur when all extensions are disabled?: **Yes**/No

Splitting terminal in folder with ë character or any subdirectories errors and doesn't split.

The terminal process failed to launch: Starting directory (cwd) "/Users/liam-nt/Documents/vscode_bug_test/eÃ«e" does not exist.

- VS Code Version: 1.74.0 (Universal)
- OS Version: macOS Monterey 12.5 (21G72)

Steps to Reproduce:

1. Create a folder containing 'ë' in name
2. Open integrated VSCode terminal and split terminal by keyboard shortcut or interface.

**Comment by meganrogge** [comment]
related #168872

**Comment by meganrogge** [comment]
![Screenshot 2022-12-12 at 11 52 30 AM](https://user-images.githubusercontent.com/29464607/207117992-e4d8330a-0186-44c6-9427-1745f6738f21.png)

**Comment by jeanp413** [comment]
Regression from https://github.com/microsoft/vscode/pull/165632
