### ISSUE TITLE
Merge Editor Issues

### ISSUE THREAD

**Issue by inchara-1998** [microsoft/vscode#168859]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Hi I am building new vs code extension for our source control project we need merge editor for merging functionality.
2. I am using "vscode.commands.executeCommand('_open.mergeEditor', options);" for opening merge editor.
3. i came out through when scenario while doing Accept Merge operation
4. If user try to click Accept merge button if still there are conflicts unhandled. i am trying to close the merge editor before merge at that time it will trigger pop up box like there are still conflicts.
![image](https://user-images.githubusercontent.com/118963451/207048028-bdb4dbe4-99ca-4cfa-acef-ed5d8c8aca12.png)

I am using this code to close editor
                      let  didCloseTab = await vscode.window.tabGroups.close(mergeEditorTabs, true);
if its true it will continue merge

But if user select close with conflicts its closing merge editor so its setting "didCloseTab" value true and accepting merge.

I want to identify the option which user is clicking because i need to restrict merge option in this case.
How can i do that??
 is there any event i can use to capture that.

**Comment by hediet** [comment]
> is there any event i can use to capture that.

Unfortunately, no.

Currently, the merge editor cannot really be used from extensions but I think there is a feature request for proper API.

**Comment by inchara-1998** [comment]
Is there any way apart from using this command for "vscode.commands.executeCommand('_open.mergeEditor', options);"

to open merge editor and use it from VS code.?

Can you please suggest any alternative way to implement merge.

**Comment by inchara-1998** [comment]
Is there any way we can detect remaining conflicts on merge editor in my vs code extension??
