### ISSUE TITLE
Notebook cell metadata diff jitters on screen

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#168892]
1. Open https://insiders.vscode.dev/github/microsoft/vscode/blob/main/.vscode/notebooks/my-work.github-issues
2. Make a change to the file and save, do not commit
3. Open the diff view from the SCM view
4. Scroll up and down in the notebook diff view 
5. :cheese: see cell metadata area skittering on screen (the recording below does not capture how frequently the skittering actually happens)

https://user-images.githubusercontent.com/30305945/207127817-ae9003e7-9177-4b84-ac27-ed526fb69a54.mp4

**Comment by joyceerhl** [comment]
Just ran into this again:


https://user-images.githubusercontent.com/30305945/214967052-157322a8-c053-4098-a9a1-b9510a7fe5df.MOV

**Comment by roblourens** [comment]
I opened https://github.com/microsoft/vscode/issues/172331 for that, I think we can actually just reopen this one

**Comment by rebornix** [comment]
This issue should be gone now since we fixed the horizontal bar issue.
