### ISSUE TITLE
Ticking a refactor preview group with a large number of changes is very slow

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#168858]
While testing #167732 I noticed that ticking this option is very slow (6-8 seconds). There are a large number of changes, but unticking is very fast.

![Dec-12-2022 11-18-45](https://user-images.githubusercontent.com/1078012/207033533-8614b9b6-e751-469b-aba4-8c1dbb3dc55a.gif)

CPU profile (of ticking and unticking) here:

[tick_untick_refactor_profile.json.zip](https://github.com/microsoft/vscode/files/10207457/tick_untick_refactor_profile.json.zip)

**Comment by jrieken** [comment]
@DanTup Do you have a full repo here? Trying this with a simple TypeScript rename doesn't show a performance problem. You say "While testing https://github.com/microsoft/vscode/issues/167732 I noticed" but the animation doesn't show anything related to groups. This is just a file with changes, right? How many are there?

**Comment by jrieken** [comment]
I do see an issue with edits for the diff-preview being reapplied each time - it is linear and could benefit from some debounce logic but to be a real performance problem this must happen really a lot, like thousands or more edits

**Comment by DanTup** [comment]
@jrieken thanks! I don't have a great repo right now because I was just testing out the APIs locally (and this specific project was the Dart SDK which requires some setup). It's a large project and I was testing the "dart fix" functionality across the whole project so it's very possible there were thousands of edits.

I'll do some more testing once your change lands in insiders, and if it still seems slow I'll try and get something more concrete and a new profile. Thanks!

**Comment by DanTup** [comment]
@jrieken it wasn't actually as large a project as I thought, however with the latest changes toggling is instant, so the fix looks great - thank you!

Btw - not sure if a bug, but clicking on the checkbox twice quickly (essentially a double click) causes the files to open (whereas toggling twice slowly, does not).

/verified
