### ISSUE TITLE
sharing

### ISSUE THREAD

**Issue by LeopoldUn0** [microsoft/vscode#168855]
Type: <b>Performance Issue</b>

The sharing isn't working. The person joining the live share is not able to get access to it. They are told that the session is 'no longer active' despite having opened the link they were sent by the host who is inside the document.

VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

**Comment by lszomoru** [comment]
Please file an issue in the [Live Share extension's repository](https://github.com/MicrosoftDocs/live-share/issues). Thank you!
