### ISSUE TITLE
Diagnostics for empty lines hard to discover

### ISSUE THREAD

**Issue by hoovercj** [Microsoft/vscode#1688]
Diagnostics for empty/blank lines are hard to discover as a user.

For example, the tslint rule `no-consecutive-blank-lines` flags the second blank line as a warning. This puts a green mark on the right gutter but gives no indication at the actual location of the error in the editor. It might be found through the "Errors and Warnings" interfaces, but if the project contains many other issues (perhaps in other files or a dependency) this might not work either.

**Comment by dbaeumer** [comment]
There is nothing the language server framework can do about this. The framework already supports errors spawn form the start to the end of a line using Number.MAX_VALUE for the end value.

However that doesn't help with empty lines. All I can think of adding a decoration to the left gutter to improve this.

**Comment by alexandrudima** [comment]
Errors on empty lines are visible since a few releases:

<img width="165" alt="image" src="https://user-images.githubusercontent.com/5047891/33122530-c7130838-cf77-11e7-9297-7fdbb6f96b48.png">
