### ISSUE TITLE
Two problems feedback：1:(“window.openFilesInNewWindow”) 2:(.d.ts)

### ISSUE THREAD

**Issue by GameMidlet** [Microsoft/vscode#16885]
- VSCode Version:1.7.2 (1.7.2)
- OS Version:Mac 10.11

1:**"window.openFilesInNewWindow": true** 
**true**和**false**都没有效果，就想要每次打开来个新的，就怎么难吗？
 2:**.d.ts**
代码提示老出现问题，VSCode**1.3版**就可以用，**1.7版**这个就不行了,修改过里面的问题还是提示有问题，很苦恼

**Comment by alexandrudima** [comment]
rough translation:

1: "window.openFilesInNewWindow": true
True and false have no effect, you want to open each time to a new, how difficult?

2: .d.ts
Code suggested that the old problems, VSCode1.3 version can be used, version 1.7 This is not alright, the problem has been revised or suggested that there are problems, very distressed

Assigning @bpasero for 1. and @mjbvz for 2.

**Comment by bpasero** [comment]
@GameMidlet can you please explain the issues in english with greater detail

**Comment by mjbvz** [comment]
Closing as more info needed.

@GameMidlet Please provide more detail about both issues so that we can investigate. 

Thanks
