### ISSUE TITLE
Tree view item description hover sometimes renders under tree view item button tooltip

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#168895]
_Originally reported by @gregvanl_

Overlapping hovers of the GitHub Repository Remote Explorer view looks odd.

![image](https://user-images.githubusercontent.com/12818376/144111443-e12c10b0-557f-4902-a607-9058063b40b7.png)

**Comment by joyceerhl** [comment]
I was able to reproduce this exactly once with the GitHub Codespaces remote explorer view's `Connect to Codespace` item button.

**Comment by sbatten** [comment]
I'm not sure why it sometimes shows both, but I'm guessing the hover service just misses an event for reasons and then we get the button hover. One simple fix would be to just move to custom hover for these.

**Comment by Tyriar** [comment]
We want to move towards all custom hovers, so the fix here is to move the tooltip on the action to use the custom hover as well. @sbatten are you the right person for the action list, can you forward on if not?

**Comment by sbatten** [comment]
yea I can own it

**Comment by bpasero** [comment]
I think this may be good with @benibenj adopting custom hover everywhere

**Comment by benibenj** [comment]
Yes, the custom hover adoption fixes these issues
