### ISSUE TITLE
editor.guides.bracketPairs breaks cursor and selection

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#168876]
Type: <b>Bug</b>

This seems to only appear in the latest insiders, it was fine yesterday. I note if I do it in a long document that scrolls off the page, it doesn't happen until the end of page is visible.

Could be regression from https://github.com/microsoft/vscode/pull/168788 CC @alexdima @roblourens 

![Capture](https://user-images.githubusercontent.com/15258962/207094639-5c2b0ad3-cdfe-4caf-8a5a-1c7337b2fd34.gif)

VS Code version: Code - Insiders 1.75.0-insider (250a8f36c93721830b0ef2e39dc065d6944d9912, 2022-12-12T05:22:29.428Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3850)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (8.74GB free)|
|Process Argv|--crash-reporter-id d15abc04-2f14-48d4-98ba-287dac26245f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (76)</summary>

Extension|Author (truncated)|Version
---|---|---
go-outliner|766|0.1.20
codesnap|adp|1.3.4
namespace|adr|1.1.2
vscode-log-viewer|ber|0.12.2
markdown-checkbox|bie|0.4.0
markdown-mermaid|bie|1.16.0
markdown-preview-github-styles|bie|1.0.1
vscode-opennewinstance|chr|0.0.12
esbuild-problem-matchers|con|0.0.2
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
dendron-paste-image|den|1.1.1
vscode-generate-getter-setter|DSK|0.5.0
gitlens|eam|13.1.1
filter-lines|ear|1.0.0
prettier-vscode|esb|9.10.3
lintlens|ghm|6.0.0
codespaces|Git|1.13.4
copilot-nightly|Git|1.62.7573
remotehub|Git|0.48.0
vscode-pull-request-github|Git|0.56.0
gc-excelviewer|Gra|4.2.56
todo-tree|Gru|0.0.220
hcl|has|0.3.1
vscode-test-explorer|hbe|2.21.1
debug-visualizer|hed|2.4.0
vscode-drawio|hed|1.6.4
Ionide-Paket|Ion|2.0.0
powershell-universal|iro|3.1.0
csharpextensions|jch|1.3.1
vscode-peacock|joh|4.2.2
csharpextensions|kre|1.7.3
regexp-preview|Lou|0.1.5
vscode-preview-ansi|lus|0.1.2
regionfolder|map|1.0.18
git-graph|mhu|1.30.0
vscode-html-format|moh|0.0.5
vscode-azurecontainerapps|ms-|0.3.0
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-bicep|ms-|0.13.1
vscode-docker|ms-|1.23.2
vscode-dotnet-runtime|ms-|1.6.0
remote-containers|ms-|0.267.0
remote-ssh|ms-|0.95.2022121215
remote-ssh-edit|ms-|0.84.0
azure-account|ms-|0.11.2
azure-repos|ms-|0.24.0
js-debug-nightly|ms-|2022.12.717
live-server|ms-|0.4.4
remote-explorer|ms-|0.1.2022121209
remote-repositories|ms-|0.26.0
test-adapter-converter|ms-|0.1.6
vscode-typescript-next|ms-|5.0.202212110
vscode-drawio-plugin-mermaid|nop|0.1.5
indent-rainbow|ode|8.3.1
docthis|oou|0.8.2
vscode-nuget-gallery|pat|0.0.24
vscode-github-projects|Pod|1.0.0
pester-test|psp|2022.3.3
quicktype|qui|12.0.46
vscode-thunder-client|ran|2.1.2
vscode-commons|red|0.0.6
vscode-sort-json|ric|1.20.0
kuskus-kusto-language-server|ros|1.0.31
vscode-zipexplorer|sle|0.3.1
even-better-toml|tam|0.19.0
vscode-inline-values-powershell|Tyl|0.0.7
errorlens|use|3.6.0
vscode-icons|vsc|12.0.1
gistfs|vsl|0.4.1
gitdoc|vsl|0.1.0
better-align|wwm|1.1.6
markdown-all-in-one|yzh|3.5.0
vitest-explorer|Zix|0.2.34

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
dbltrim-noruby:30604474
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by hediet** [comment]
Thanks for reporting!
We fixed this in https://github.com/microsoft/vscode/pull/168851.
There should be an update ready for insiders.

**Comment by JustinGrote** [comment]
Thanks, this morning's update fixed it
