### ISSUE TITLE
Problems with displaying terminal tabs description

### ISSUE THREAD

**Issue by lon33ly** [microsoft/vscode#168872]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0
- OS Version: MACOS 13.0.1

Steps to Reproduce:

If i open any non-engilsh folder i see in terminal tabs description:
<img width="550" alt="image" src="https://user-images.githubusercontent.com/55896709/207087906-8c59aa36-d401-4c50-adc3-ec3588399a2d.png">

Setting locale in zsh doesnt help
Setting different languages in VSCODE interface doesnt help

**Comment by meganrogge** [comment]
which characters? it is working for me w these

![Screenshot 2022-12-12 at 4 17 54 PM](https://user-images.githubusercontent.com/29464607/207167150-02539795-eec0-4d66-9fd6-84ca484598d7.png)

**Comment by meganrogge** [comment]
This is working in insider's

![Screenshot 2022-12-14 at 12 33 50 PM](https://user-images.githubusercontent.com/29464607/207680982-a2f79da6-dcc7-4335-9eab-7f2b6d851d84.png)
