### ISSUE TITLE
Expression_produces_a_union_type_that_is_too_complex_to_represent_2590 on Next.js file (**.tsx)

### ISSUE THREAD

**Issue by tak-d4c** [microsoft/vscode#168964]
Type: <b>Bug</b>

I get an error `Expression_produces_a_union_type_that_is_too_complex_to_represent_2590` from the last Next.js file (**.tsx) I saved.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|64.00GB (37.44GB free)|
|Process Argv|--crash-reporter-id 122c83aa-ad27-4577-bd15-4a6319487dfc|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (43)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
nestjs-files|Abh|0.5.1
html-snippets|abu|0.2.1
jest-snippets|and|1.9.1
vscode-apollo|apo|1.19.11
nestjs|ash|1.4.2
insertnumbers|Asu|0.9.1
vscode-tailwindcss|bra|0.9.1
better-toml|bun|0.3.2
path-intellisense|chr|2.8.3
bracket-pair-colorizer|Coe|1.0.62
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
es7-react-js-snippets|dsz|4.4.3
rust-syntax|dus|0.6.1
gitlens|eam|13.1.1
prettier-vscode|esb|9.10.3
auto-rename-tag|for|0.1.10
firebase-explorer|jsa|0.3.3
vscode-snippets|mhe|2.0.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-docker|ms-|1.23.2
vscode-language-pack-ja|MS-|1.74.12070927
vscode-dotnet-runtime|ms-|1.6.0
remote-containers|ms-|0.266.1
vscode-typescript-next|ms-|5.0.202212110
vetur|oct|0.36.1
vscode-jest|Ort|4.6.0
material-icon-theme|PKi|4.22.0
tsimporter|pmn|2.0.1
polacode|pnp|0.3.4
prisma|Pri|4.7.1
code-snapshot|rob|0.2.1
rust-analyzer|rus|0.3.1317
vue-vscode-snippets|sdr|3.1.1
trailing-spaces|sha|0.4.1
code-spell-checker|str|2.12.0
vscode-stripe|str|2.0.14
control-snippets|svi|1.9.1
vsfire|tob|1.4.1
vscode-counter|uct|3.1.0
vscode-icons|vsc|12.0.1

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by mjbvz** [comment]
Does this reproduce in the [latest VS Code insiders build](https://code.visualstudio.com/insiders/) with all [extensions disabled](https://github.com/microsoft/vscode/wiki/Performance-Issues#run-with-extensions-disabled)?

If so, please share a minimal code example that shows the issue
