### ISSUE TITLE
Occurrences highlight is per individual cell, with different tokens, instead of highlighting a single token over the whole notebook

### ISSUE THREAD

**Issue by 2-5** [microsoft/vscode#168919]
## Environment data

-   VS Code version: 1.73.1
-   Jupyter Extension version: v2022.9.1303220346
-   Python Extension version: v2022.18.2
-   OS: Windows 10

## Expected behaviour

Occurrences highlight should highlight a single token, the one under the cursor in the current active cell, not a different one for each cell.

## Actual behaviour

Each Jupyter Notebook cell has it's own occurrences highlight, so you often see each cell highlighting a different token, which is annoying and breaks the purpose of occurrences highlight.

## Steps to reproduce:

Notice how in the first cell `sel_df` is highlighted, in the second cell `idx` is highlighted, in the third cell `gb_df` is highlighted. Ideally, only the token in the current cell would be highlighted over the whole notebook. Or at least occurrences highlighting would be disabled in all but the active cell.

![occurences](https://user-images.githubusercontent.com/3753822/202921804-d635ffce-9015-4577-bfae-6e8444b2911f.png)

**Comment by 2-5** [comment]
I confirm that the issue is still present in the last version of VS Code Jupyter.

**Comment by rebornix** [comment]
Similar to https://github.com/microsoft/vscode/issues/141673, let's track it there.
