### ISSUE TITLE
command 'emmet.expandAbbreviation' not found

### ISSUE THREAD

**Issue by kadaejungkalon** [microsoft/vscode#168962]
Type: <b>Bug</b>

command 'emmet.expandAbbreviation' not found. 

it's always and cannot use all extensions, including TAB

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin x64 22.1.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 4, 6|
|Memory (System)|16.00GB (1.52GB free)|
|Process Argv|--crash-reporter-id 1c36a263-1c77-4882-8a7a-5ca893ba74ff|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (49)</summary>

Extension|Author (truncated)|Version
---|---|---
android-emulator-launcher|343|0.9.0
vscode-color|ans|0.4.5
vscode-tailwindcss|bra|0.9.1
prettier-vscode-standard|bys|0.22.1
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
prettier-vscode|esb|9.10.3
vs-code-xml-format|fab|0.1.5
auto-close-tag|for|0.5.14
auto-rename-tag|for|0.1.10
unity-code-snippets|kle|1.3.0
json|Mee|0.1.2
vscode-docker|ms-|1.23.2
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
debugger-for-chrome|msj|4.13.0
vscode-react-native|msj|1.10.0
java-prettier-formatter|mwp|0.1.5
color-highlight|nau|2.5.0
java|red|1.13.0
html-to-jsx|ria|0.0.1
live-sass|rit|3.0.0
LiveServer|rit|5.7.9
sonarlint-vscode|Son|3.12.0
sass-indented|syl|1.8.23
reactreduxcoursesnippets|TCL|0.8.0
unity-tools|Tob|1.2.12
unity-debug|Uni|3.0.2
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-gradle|vsc|3.12.6
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.1
vscode-icons|vsc|12.0.1
unity-snippets|Ycl|0.1.2

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by gjsjohnmurray** [comment]
Please use the Start Extension Bisect command to investigate whether the problem is being caused by one of your extensions.

**Comment by rzhao271** [comment]
If you purposely have Emmet disabled, see #168833.
Otherwise, you can re-enable Emmet by going to the extensions viewlet with Cmd+Shift+X, searching `@builtin emmet`, and configuring the extension there.
