### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by sshilpa96** [microsoft/vscode#168959]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0
- OS Version: 
Edition	Windows 11 Home Single Language
Version	22H2
Installed on	‎22-‎09-‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0

Steps to Reproduce:

1. Run karate feature file

As mentioned in wiki sharing the system performance data in my vscode

## System Info

* Code: 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91)
* OS: win32(10.0.22621)
* CPUs: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz(4 x 2995)
* Memory(System): 11.70 GB(1.00GB free)
* Memory(Process): 174.12 MB working set(128.10MB private, 0.19MB shared)
* VM(likelihood): 0%
* Initial Startup: false
* Has 1 other windows
* Screen Reader Active: false
* Empty Workspace: true

## Performance Marks

| What                                                            | Duration | Process                   | Info                                    |
| --------------------------------------------------------------- | -------- | ------------------------- | --------------------------------------- |
| start => app.isReady                                            | -        | [main]                    | initial startup: false                  |
| nls:start => nls:end                                            | -        | [main]                    | initial startup: false                  |
| require(main.bundle.js)                                         | -        | [main]                    | initial startup: false                  |
| start crash reporter                                            | -        | [main]                    | initial startup: false                  |
| serve main IPC handle                                           | -        | [main]                    | initial startup: false                  |
| create window                                                   | -        | [main]                    | initial startup: false,                 |
| app.isReady => window.loadUrl()                                 | -        | [main]                    | initial startup: false                  |
| window.loadUrl() => begin to require(workbench.desktop.main.js) | 348      | [main->renderer]          | NewWindow                               |
| require(workbench.desktop.main.js)                              | 383      | [renderer]                | cached data: YES, node_modules took 0ms |
| wait for window config                                          | 0        | [renderer]                | -                                       |
| init storage (global & workspace)                               | 48       | [renderer]                | -                                       |
| init workspace service                                          | 65       | [renderer]                | -                                       |
| register extensions & spawn extension host                      | 847      | [renderer]                | -                                       |
| restore viewlet                                                 | 0        | [renderer]                | -                                       |
| restore panel                                                   | 0        | [renderer]                | -                                       |
| restore & resolve visible editors                               | 11       | [renderer]                | 0:                                      |
| overall workbench load                                          | 435      | [renderer]                | -                                       |
| workbench ready                                                 | 1249     | [main->renderer]          | -                                       |
| renderer ready                                                  | 917      | [renderer]                | -                                       |
| shared process connection ready                                 | 286      | [renderer->sharedprocess] | -                                       |
| extensions registered                                           | 2414     | [renderer]                | -                                       |

## Extension Activation Stats

| Extension                               | Eager | Load Code | Call Activate | Finish Activate | Event                             | By                                      |
| --------------------------------------- | ----- | --------- | ------------- | --------------- | --------------------------------- | --------------------------------------- |
| vscode.git                              | true  | 258       | 8             | 561             | *                                 | vscode.git                              |
| vscode.git-base                         | true  | 274       | 0             | 5               | *                                 | vscode.git                              |
| vscode.github                           | true  | 293       | 0             | 3               | *                                 | vscode.github                           |
| vscode.debug-auto-launch                | false | 8         | 0             | 85              | onStartupFinished                 | vscode.debug-auto-launch                |
| vscode.emmet                            | false | 52        | 6             | 79              | onStartupFinished                 | vscode.emmet                            |
| vscode.extension-editing                | false | 62        | 1             | 7               | onLanguage:markdown               | vscode.extension-editing                |
| vscode.github-authentication            | false | 243       | 1             | 3               | onAuthenticationRequest:github    | vscode.github-authentication            |
| vscode.markdown-language-features       | false | 343       | 7             | 513             | onLanguage:markdown               | vscode.markdown-language-features       |
| vscode.markdown-math                    | false | 36        | 0             | 0               | api                               | vscode.markdown-language-features       |
| vscode.merge-conflict                   | false | 195       | 1             | 80              | onStartupFinished                 | vscode.merge-conflict                   |
| vscode.microsoft-authentication         | false | 269       | 1             | 321             | onAuthenticationRequest:microsoft | vscode.microsoft-authentication         |
| ms-vscode-remote.remote-wsl-recommender | false | 297       | 8             | 81              | onStartupFinished                 | ms-vscode-remote.remote-wsl-recommender |
| eamodio.gitlens                         | false | 1307      | 65            | 47              | onStartupFinished                 | eamodio.gitlens                         |
| formulahendry.code-runner               | false | 2114      | 2             | 15              | onStartupFinished                 | formulahendry.code-runner               |

## Raw Perf Marks: main

```
Name	Timestamp	Delta	Total
code/timeOrigin	1670906781910	0	0
code/didStartMain	1670906781977	67	67
code/willStartCrashReporter	1670906781990	13	80
code/didStartCrashReporter	1670906782013	23	103
code/mainAppReady	1670906782037	24	127
code/willGenerateNls	1670906782039	2	129
code/didGenerateNls	1670906782044	5	134
code/willLoadMainBundle	1670906782044	0	134
code/fork/willLoadCode	1670906782058	14	148
code/registerFilesystem/file	1670906782113	55	203
code/didLoadMainBundle	1670906782120	7	210
code/willStartMainServer	1670906782126	6	216
code/didStartMainServer	1670906782129	3	219
code/willCreateCodeWindow	1670906782150	21	240
code/willRestoreCodeWindowState	1670906782150	0	240
code/didRestoreCodeWindowState	1670906782150	0	240
code/willCreateCodeBrowserWindow	1670906782151	1	241
code/didCreateCodeBrowserWindow	1670906782165	14	255
code/willMaximizeCodeWindow	1670906782165	0	255
code/didMaximizeCodeWindow	1670906782192	27	282
code/didCreateCodeWindow	1670906782192	0	282
code/willOpenNewWindow	1670906782193	1	283
code/willCreateCodeWindow	1670914892145	8109952	8110235
code/willRestoreCodeWindowState	1670914892148	3	8110238
code/didRestoreCodeWindowState	1670914892149	1	8110239
code/willCreateCodeBrowserWindow	1670914892150	1	8110240
code/didCreateCodeBrowserWindow	1670914892195	45	8110285
code/didCreateCodeWindow	1670914892199	4	8110289
code/willOpenNewWindow	1670914892202	3	8110292
```
## Raw Perf Marks: renderer

```
Name	Timestamp	Delta	Total
code/timeOrigin	1670914892203	0	0
code/didStartRenderer	1670914892534	331	331
code/willWaitForWindowConfig	1670914892535	1	332
code/didWaitForWindowConfig	1670914892535	0	332
code/willShowPartsSplash	1670914892535	0	332
code/didShowPartsSplash	1670914892536	1	333
code/willLoadWorkbenchMain	1670914892550	14	347
code/didLoadWorkbenchMain	1670914892933	383	730
code/registerFilesystem/file	1670914892937	4	734
code/registerFilesystem/vscode-userdata	1670914892937	0	734
code/willInitWorkspaceService	1670914892943	6	740
code/willInitStorage	1670914892943	0	740
code/didInitStorage	1670914892991	48	788
code/willInitUserConfiguration	1670914893001	10	798
code/didInitUserConfiguration	1670914893006	5	803
code/willInitWorkspaceConfiguration	1670914893006	0	803
code/didInitWorkspaceConfiguration	1670914893007	1	804
code/didInitWorkspaceService	1670914893008	1	805
code/willStartWorkbench	1670914893016	8	813
code/LifecyclePhase/Ready	1670914893018	2	815
code/willCreateWorkbenchContributions/1	1670914893123	105	920
code/didCreateWorkbenchContributions/1	1670914893222	99	1019
code/willCreateWorkbenchContributions/2	1670914893222	0	1019
code/registerFilesystem/trustedDomains	1670914893230	8	1027
code/registerFilesystem/vscode-local-history	1670914893246	16	1043
code/didCreateWorkbenchContributions/2	1670914893250	4	1047
code/willRestoreEditors	1670914893440	190	1237
code/didRestoreEditors	1670914893451	11	1248
code/LifecyclePhase/Restored	1670914893451	0	1248
code/didStartWorkbench	1670914893451	0	1248
code/didRemovePartsSplash	1670914893451	0	1248
code/willCreateWorkbenchContributions/3	1670914893451	0	1248
code/registerFilesystem/vscode-edit-sessions	1670914893498	47	1295
code/didCreateWorkbenchContributions/3	1670914893605	107	1402
code/willConnectSharedProcess	1670914893619	14	1416
code/willLoadExtensions	1670914893769	150	1566
code/didConnectSharedProcess	1670914893905	136	1702
code/willHandleExtensionPoints	1670914894115	210	1912
code/willHandleExtensionPoint/configurationDefaults	1670914894115	0	1912
code/didHandleExtensionPoint/configurationDefaults	1670914894139	24	1936
code/willHandleExtensionPoint/configuration	1670914894139	0	1936
code/didHandleExtensionPoint/configuration	1670914894273	134	2070
code/willHandleExtensionPoint/jsonValidation	1670914894273	0	2070
code/didHandleExtensionPoint/jsonValidation	1670914894275	2	2072
code/willHandleExtensionPoint/debuggers	1670914894275	0	2072
code/didHandleExtensionPoint/debuggers	1670914894279	4	2076
code/willHandleExtensionPoint/breakpoints	1670914894279	0	2076
code/didHandleExtensionPoint/breakpoints	1670914894294	15	2091
code/willHandleExtensionPoint/notebooks	1670914894294	0	2091
code/didHandleExtensionPoint/notebooks	1670914894295	1	2092
code/willHandleExtensionPoint/notebookRenderer	1670914894295	0	2092
code/didHandleExtensionPoint/notebookRenderer	1670914894297	2	2094
code/willHandleExtensionPoint/problemPatterns	1670914894297	0	2094
code/didHandleExtensionPoint/problemPatterns	1670914894298	1	2095
code/willHandleExtensionPoint/problemMatchers	1670914894298	0	2095
code/didHandleExtensionPoint/problemMatchers	1670914894299	1	2096
code/willHandleExtensionPoint/taskDefinitions	1670914894299	0	2096
code/didHandleExtensionPoint/taskDefinitions	1670914894303	4	2100
code/willHandleExtensionPoint/terminal	1670914894303	0	2100
code/didHandleExtensionPoint/terminal	1670914894303	0	2100
code/willHandleExtensionPoint/walkthroughs	1670914894303	0	2100
code/didHandleExtensionPoint/walkthroughs	1670914894303	0	2100
code/willHandleExtensionPoint/commands	1670914894304	1	2101
code/didHandleExtensionPoint/commands	1670914894318	14	2115
code/willHandleExtensionPoint/submenus	1670914894318	0	2115
code/didHandleExtensionPoint/submenus	1670914894318	0	2115
code/willHandleExtensionPoint/menus	1670914894318	0	2115
code/didHandleExtensionPoint/menus	1670914894379	61	2176
code/willHandleExtensionPoint/authentication	1670914894379	0	2176
code/didHandleExtensionPoint/authentication	1670914894379	0	2176
code/willHandleExtensionPoint/languages	1670914894379	0	2176
code/didHandleExtensionPoint/languages	1670914894405	26	2202
code/willHandleExtensionPoint/customEditors	1670914894405	0	2202
code/didHandleExtensionPoint/customEditors	1670914894406	1	2203
code/willHandleExtensionPoint/codeActions	1670914894406	0	2203
code/didHandleExtensionPoint/codeActions	1670914894406	0	2203
code/willHandleExtensionPoint/viewsWelcome	1670914894406	0	2203
code/didHandleExtensionPoint/viewsWelcome	1670914894410	4	2207
code/willHandleExtensionPoint/resourceLabelFormatters	1670914894410	0	2207
code/didHandleExtensionPoint/resourceLabelFormatters	1670914894411	1	2208
code/willHandleExtensionPoint/grammars	1670914894411	0	2208
code/didHandleExtensionPoint/grammars	1670914894487	76	2284
code/willHandleExtensionPoint/colors	1670914894487	0	2284
code/didHandleExtensionPoint/colors	1670914894490	3	2287
code/willHandleExtensionPoint/icons	1670914894490	0	2287
code/didHandleExtensionPoint/icons	1670914894493	3	2290
code/willHandleExtensionPoint/semanticTokenTypes	1670914894493	0	2290
code/didHandleExtensionPoint/semanticTokenTypes	1670914894493	0	2290
code/willHandleExtensionPoint/semanticTokenModifiers	1670914894493	0	2290
code/didHandleExtensionPoint/semanticTokenModifiers	1670914894493	0	2290
code/willHandleExtensionPoint/semanticTokenScopes	1670914894493	0	2290
code/didHandleExtensionPoint/semanticTokenScopes	1670914894494	1	2291
code/willHandleExtensionPoint/snippets	1670914894494	0	2291
code/didHandleExtensionPoint/snippets	1670914894494	0	2291
code/willHandleExtensionPoint/keybindings	1670914894494	0	2291
code/didHandleExtensionPoint/keybindings	1670914894537	43	2334
code/willHandleExtensionPoint/themes	1670914894537	0	2334
code/didHandleExtensionPoint/themes	1670914894540	3	2337
code/willHandleExtensionPoint/iconThemes	1670914894540	0	2337
code/didHandleExtensionPoint/iconThemes	1670914894540	0	2337
code/willHandleExtensionPoint/continueEditSession	1670914894540	0	2337
code/didHandleExtensionPoint/continueEditSession	1670914894540	0	2337
code/willHandleExtensionPoint/viewsContainers	1670914894540	0	2337
code/didHandleExtensionPoint/viewsContainers	1670914894555	15	2352
code/willHandleExtensionPoint/views	1670914894555	0	2352
code/didHandleExtensionPoint/views	1670914894591	36	2388
code/didHandleExtensionPoints	1670914894591	0	2388
code/didLoadExtensions	1670914894616	25	2413
```
## Raw Perf Marks: localExtHost

```
Name	Timestamp	Delta	Total
code/timeOrigin	1670914894034	0	0
code/fork/start	1670914894508	474	474
code/fork/willLoadCode	1670914894662	154	628
code/extHost/willConnectToRenderer	1670914895673	1011	1639
code/extHost/didConnectToRenderer	1670914895689	16	1655
code/extHost/didWaitForInitData	1670914895758	69	1724
code/extHost/didCreateServices	1670914895759	1	1725
code/extHost/willWaitForConfig	1670914895788	29	1754
code/extHost/didWaitForConfig	1670914895889	101	1855
code/extHost/didInitAPI	1670914895895	6	1861
code/extHost/didInitProxyResolver	1670914895911	16	1877
code/extHost/ready	1670914895911	0	1877
code/extHost/willLoadExtensionCode/vscode.microsoft-authentication	1670914896018	107	1984
code/extHost/didLoadExtensionCode/vscode.microsoft-authentication	1670914896287	269	2253
code/extHost/willLoadExtensionCode/vscode.git-base	1670914896287	0	2253
code/extHost/didLoadExtensionCode/vscode.git-base	1670914896292	5	2258
code/extHost/willActivateExtension/vscode.microsoft-authentication	1670914896652	360	2618
code/extHost/willActivateExtension/vscode.git-base	1670914896653	1	2619
code/extHost/didActivateExtension/vscode.git-base	1670914896666	13	2632
code/extHost/willLoadExtensionCode/vscode.git	1670914896673	7	2639
code/extHost/didLoadExtensionCode/vscode.git	1670914896929	256	2895
code/extHost/willLoadExtensionCode/vscode.github	1670914896929	0	2895
code/extHost/didLoadExtensionCode/vscode.github	1670914896965	36	2931
code/extHost/didActivateExtension/vscode.microsoft-authentication	1670914896974	9	2940
code/extHost/willActivateExtension/vscode.git	1670914896975	1	2941
code/extHost/willActivateExtension/vscode.github	1670914896983	8	2949
code/extHost/didActivateExtension/vscode.github	1670914896988	5	2954
code/extHost/willLoadExtensionCode/vscode.github-authentication	1670914897026	38	2992
code/extHost/didLoadExtensionCode/vscode.github-authentication	1670914897269	243	3235
code/extHost/didActivateExtension/vscode.git	1670914897545	276	3511
```

**Comment by sshilpa96** [comment]
yes

**Comment by sshilpa96** [comment]
> ?

WHAT?

**Comment by jrieken** [comment]
You just wrote "yes". Now you have added more information but still haven't clarified what the karate feature is? Is that a language or an extension? How do I get that to work on my machine so that I have a chance to experience the same issue. For me everything is normal, no performance issues, so you need to empower me to see the issue you are seeing otherwise I cannot help

**Comment by sshilpa96** [comment]
Karate is a framework used for automation testing. In which code is executed by running feature file. I think feature file is not the reason for slowness, because the same is used for a month. Now only VS code is causing issue

**Comment by sshilpa96** [comment]
Hi @jrieken VS Code is working now after reinstalling the tool and deleted the old data . So this issue will be closed by mine
