### ISSUE TITLE
November VSCode release blocks file save / formatter operations when debugging

### ISSUE THREAD

**Issue by matthewjamesadam** [microsoft/vscode#168935]
Does this issue occur when all extensions are disabled?: No, but this is a regression in the November release (ie, works fine in October release)

- VS Code Version: 1.74.0
- OS Version: MacOS 12.5.1

Our development tools include Prettier and ESLint's VSCode plugins.  We have them configured like this in our project's `settings.json` file:

```
    // Format with eslint
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },

    // Then prettify
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": true,
```

Steps to Reproduce:

1. Launch our project (itself a VSCode extension) in debug mode.  A new copy of VSCode launches with the built extension
2. In the original "parent" VSCode, attempt to edit/save a file

Results:

* An error is displayed with one of the following warnings, and stays displayed for a few minutes:
<img width="478" alt="Screen Shot 2022-12-12 at 4 31 49 PM" src="https://user-images.githubusercontent.com/2133518/207198294-f097af89-7975-4b9e-8f96-3cbd553aead5.png">
<img width="462" alt="Screen Shot 2022-12-12 at 4 34 36 PM" src="https://user-images.githubusercontent.com/2133518/207198296-4021a929-ee82-4f53-976e-157367011ca6.png">

* If I try to quit/reload VSCode, I see:
<img width="527" alt="Screen Shot 2022-12-12 at 4 35 18 PM" src="https://user-images.githubusercontent.com/2133518/207198313-d01d63da-323d-4012-92b2-b67922655a5b.png">

* If I wait several minutes, things eventually seem to calm down and I am able to edit the file as expected.

We typically use a watch mode to edit code in a REPL loop, so not being able to edit files while the debugger is running is greatly impacting us.

Note that everything works fine in the October release (1.73.1), so my assumption is that this is *not* a bug in the given extensions, but a bug in VSCode.

Let me know if there is there any way I could debug what is happening here or otherwise help with this, I've made a few commits modifying VSCode so I'm happy to help if I'm given some pointers.

**Comment by mjbvz** [comment]
Does this work if you disable prettier? What about eslint?

**Comment by matthewjamesadam** [comment]
@mjbvz I've tried all the combinations:

* If you disable *only* prettier, we see the error above for eslint
* If you disable *only* eslint, we see the error above for prettier
* If you disable *both* eslint and prettier, no error is shown

This leads me to think this is some systemic thing with VSCode's formatting/action-on-save feature.

**Comment by markw65** [comment]
I'm also working on a vscode extension, and have seen very similar behavior (with prettier; I don't have eslint configured to auto run on save), but for me it's inconsistent - sometimes it repros, and sometimes it doesn't. But its happening enough that I've had to downgrade to 1.73.1

**Comment by matthewjamesadam** [comment]
I just gave `1.74.2` a try, and this issue seems to be resolved.  Looking through the changelogs for 1.74.1 and 1.74.2 I don't see any obvious change related to this, but something fixed it!

Closing.
