### ISSUE TITLE
History lost in vscode terminal

### ISSUE THREAD

**Issue by david26694** [microsoft/vscode#168972]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.0
- OS Version: 11.3.1 (20E241)

Steps to Reproduce:

1. Open vs code terminal
2. Type history
3. History is different from the one in a terminal outside of vs code:
![image](https://user-images.githubusercontent.com/22721584/207272426-43244ced-a180-4f30-bf93-b6175efde02e.png)

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/168396

already fixed in insider's and soon to be fixed in our recovery release (tomorrow)
