### ISSUE TITLE
I want to Debug at the Integrated Terminal

### ISSUE THREAD

**Issue by Jackie-Yang** [Microsoft/vscode#16890]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

When I debug my c/c++ program, vscode will open an external Terminal(behind the vscode window), it is not convenient. How can I Debug a program at the Integrated Terminal or open an external Terminal at the top?
<img width="1024" alt="2016-12-08 11 39 07" src="https://cloud.githubusercontent.com/assets/18381153/20996773/01deb340-bd3b-11e6-8d25-bb81e41a60f6.png">

**Comment by isidorn** [comment]
This is an option in your launch.json file, simple put console: "integratedTerminal"
More details here https://code.visualstudio.com/docs/editor/debugging#_node-console
However this is currently only supported in the node debugger. Not sure if c++ debugger is supporting it, if not please file a feature request to them here https://github.com/Microsoft/vscode-cpptools
