### ISSUE TITLE
No provider when trying to resolve terminal quick fix for provider:  ms-vscode.npm-command

### ISSUE THREAD

**Issue by meganrogge** [microsoft/vscode#168936]
This should be log level `trace` instead of `warn` because will happen if the `quickFixAddon` beats the `terminalContributionService` and isn't an issue since we handle that case as well

![Screenshot 2022-12-12 at 7 15 55 PM](https://user-images.githubusercontent.com/29464607/207202223-5929c47e-173b-41a8-8f0b-54a61363c30a.png)

**Comment by Tyriar** [comment]
If there's a race, do we need a warning or trace at all? When the race happens we still fix it up regardless of the other, right? Do we need to put an `await` somewhere to prevent something from proceeding until everything is ready?

**Comment by meganrogge** [comment]
I believe that we don't need to indicate this at all because the quick fix ends up working, so we're covering the race correctly. It needs investigation to confirm that though, so I want to leave this open
