### ISSUE TITLE
Support for metadata in output cells

### ISSUE THREAD

**Issue by m-krastev** [microsoft/vscode#168923]
Currently, support for metadata is reserved only for normal input cells. However, there is no option to add metadata, such as tags, for specific output cells.

Example usage: I may want to add specific tags to hide content from outputs whenever exporting with `nbconvert`. 

Right now, I could do this by manually editing the notebook's JSON and adding the metadata tag, however, VSCode soon overwrites my changes (for example, when executing any cell). 

It could be added as an option when right-clicking the `</>` or `...` buttons, or at the very least not erased by Jupyter when executing cells.

**Comment by Rinto-kun** [comment]
Bump.

**Comment by DonJayamanne** [comment]
Thank you for this feature request, however given the fact that there haven't been any upvotes on this issue we're closing this./
You can however create an extension that edits the metadata of the outputs, however I do not see this happening natively in VS Code for the forseable future.
