### ISSUE TITLE
Multiple bug in the terminal

### ISSUE THREAD

**Issue by yunying1** [microsoft/vscode#168956]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0 (Universal)
- OS Version: MacOS 13.0.1 (22A400)

First all, these problems only occur in version 1.74.0. They did not exist before I updated it.

## Bug 1

Ghost String

Steps to Reproduce:

1. Copy **two line** text to terminal
2. Press any key

![Ghost String](https://user-images.githubusercontent.com/50652358/207235409-5fcbb63d-8e7c-4a94-b192-9aa59d5c9b5d.gif)

## Bug 2

Garbled code

Steps to Reproduce:

1. Copy **any** Chinese text to terminal

![Garbled code](https://user-images.githubusercontent.com/50652358/207236697-63c3a945-13b5-4208-8dcb-898ded4398b5.gif)

## Bug 3

Command history is strange, I can't go back to the previous records. I can only go back to the last few.
In versions prior to VSCode, the historical behavior of the terminal is consistent with that of iTerm. No matter which terminal I am in, I can quickly find the historical command by pressing the Up/Down key

Thank you for your time on VSCode, which is very important to me.

**Comment by Jiang-Xuan** [comment]
git log in terminal. has chinese text
![image](https://user-images.githubusercontent.com/13357301/207239203-eebaa922-b2b1-4f5c-8c48-0679dd10fd17.png)

**Comment by Leorowe** [comment]
> git log in terminal. has chinese text ![image](https://user-images.githubusercontent.com/13357301/207239203-eebaa922-b2b1-4f5c-8c48-0679dd10fd17.png)

![企业微信截图_7081796e-c201-4da7-a45f-5a6f3a17b046](https://user-images.githubusercontent.com/968185/207284363-13955e92-0a72-4d81-936b-1b55dad363a6.png)
After installing this plugin, the problem fixed

**Comment by yunying1** [comment]
Sorry `Bug 2` is duplicate.

`Bug 1` not in [#166936](https://github.com/microsoft/vscode/issues/166936), do you think `Bug 1` and `Bug 2` are same problem? @meganrogge 

#### Supplement
`Bug 3` is not an bug, This is a new default action. We can set `"terminal.integrated.shellIntegration.enabled"` to `false` in the settings file to go back to the previous.

**Comment by meganrogge** [comment]
`Bug 1` is a duplicate of https://github.com/microsoft/vscode/issues/168458

**Comment by yunying1** [comment]
Thanks a lot, Looking forward to the next version.

**Comment by Jiang-Xuan** [comment]
awesome, has fixed.
