### ISSUE TITLE
JS files are not being treated as independent units by default

### ISSUE THREAD

**Issue by GBcrazy** [Microsoft/vscode#16892]
- VSCode Version: 1.7.2
- OS Version: Windows 8.1

Steps to Reproduce:

I'm not sure where I read that, but I thought JS files should be treated as independent units by default (by default, I mean no jsconfig.json file). For some reason my VSCode is adding intellisense for non-imported variables across the project. As an example, let's say I have only these two simple files in a folder-project: 

test1.js 
`var foo = 'test';`

test2.js
`var foo = 10;`

So the thing is, I'm getting Intellisense for the wrong foo in test2.js: if I begin to type foo, it's only showing me String.prototype methods. From what I understood, it shouldn't work like that (could be wrong tho, I'm pretty new in VSCode), I want Intellisense only for explicit imported variables, with either commonjs require/es6 import.

I even tried creating a jsconfig.json file, with *allowSyntheticDefaultImports* set to false in jsconfig, but still couldn't make it work the way I want.

```
{
    "compilerOptions": {
        "target": "es6",
        "allowSyntheticDefaultImports": false
    }
}
```

**Comment by waderyan** [comment]
@GBcrazy You are correct in how you read the docs (I found the [docs](https://code.visualstudio.com/Docs/languages/typescript) in the TypeScript document but it also applies to JavaScript). 

We are doing work in this area, trying to provide the proper experience, so your feedback is appreciated. 

What is likely going on here is you have test1.js and test2.js both open. We will provide IntelliSense for all open files. This is a behavior we learned from our work with Visual Studio users was preferred.

When I recreate what you are describing I don't see IntelliSense for `test2.js` when I close it. Can you confirm that is the behavior you are seeing? If not, can you share a workspace with me so I can recreate it on my end? 

Also, what do you think about having us provide IntelliSense for open files? This is a feature we are evaluating.

**Comment by GBcrazy** [comment]
Hmm, yeah, that's precisely it, now it makes some sense. 

But also, I noticed if I have a jsconfig.json file (even if it's empty), then the mentioned behavior will happen even if test1.js is closed, Not sure if it is intended.

So, my opnion: I think there's definitively value to it, but it should be configurable (and also documented) somewhere, not sure if as a setting or in jsconfig.json. And probably the current file opened declarations should have priority over the others in case of same name, it seems like whoever was opened first will take priority.

Also, kinda off topic, but could you explain to me what is the purpose/expected behavior of the `allowSyntheticDefaultImports` property in the jsconfig?


Thanks for your time waderyan!

**Comment by waderyan** [comment]
@GBcrazyCool, thank you for the feedback. 

From the [docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html):

> Allow default imports from modules with no default export. This does not affect code emit, just typechecking.

**Comment by mjbvz** [comment]
I agree we should allow configuring this behavior, and it is not clear if you can currently. I've opened https://github.com/Microsoft/TypeScript/issues/14279 against TypeScript to track this
