### ISSUE TITLE
extending a language with another 

### ISSUE THREAD

**Issue by Spown** [Microsoft/vscode#1689]
How can I extend basic HTML language with another syntax without disabling the basic HTML? It seems that there are some things, that are still hardcoded into VSCode core and linked to text.html.basic that I loose if I use a html-based language that is not the text.html.basic.

In my case I'm trying to integrate Nunjucks templater into VSCode. I used the generator, and tried the plugin some other guy made (basically the same thing). And it boils down to the fact that I'm trading Nunjucks syntax coloring against all the cool staff basic VSC HTML offers (emmet, tag closing...). Legit HTML tag suggestions became replaced with some random on-the-fly-generated garbage and the coloring of the HTML syntax in Nunjucks language  plugin is inconsistent with the basic one anyway. On the other hand HTML is bickering about the errors in the script tags, if nunj is used there... So not worth it.

Is there a way already - if yes what is it? And if there is no - consider it a feature request/suggestion.

**Comment by unhealthy** [comment]
I have the same question.
I write vuejs recently, and I try to implement a plugin to support the syntax highlight and snippet of vuejs.
Since vuejs extends basic HTML and JavaScript, I want to inherit the embed support of HTML and JavaScript from Vs-code to my plugin. However I have check the document carefully and find no way.

I have try add **"extensionDependencies":['vscode.html','vscode.javascript']**, but it seems cannot work.

So how can I inherit/include/import some language support, include snippet and colorizer, to another language?

**Comment by aeschli** [comment]
@Spown @unhealthy The ways to reuse language functionality are currently very limited. Nunjucks has it's own syntax and the html extension doesn't know what to do with it. The vscode API has the capability to programmatically invoke supports for a given language, but always on a real file resource. We have been discussing if we should add the capability that you can also pass an in-memory buffer, such as you could convert the Nunjucks code to HTML before passing to the html mode, but we haven't come to any conclusions, yet. At this time, for the case of Nunjucks, you have to go the full way, and (re-) implement all the functionality that you need. But at least you have full control, and e.g. don't see any snippets that don't make sense in your context.

In the case of vuejs, that seems to be based on normal html (correct me if I'm wrong, I just read a bit on it), you can participate in the HTML mode by adding additional providers (validation, suggestions, hovers...). You can add additional snippets, but they would be visible to all html files. Alternatively, you could also replace the full mode by your own and programmatically make calls to the HTML extension for things like suggestion, hovers...
All that said, we don't have any experience in that yet, so please ping me if you tried this and couldn't get it to work.
You might have also seen that the HTML mode is not a proper extension yet. It's legacy code using internal APIs. It's on the plan to bring it to the new APIs and when doing that we will have to find solutions to the embedded languages problem such as css and js in html.

**Comment by Spown** [comment]
> At this time, for the case of Nunjucks, you have to go the full way, and (re-) implement all the functionality that you need. But at least you have full control, and e.g. don't see any snippets that don't make sense in your context.

ok, another question then: how can I re-implement emmet snippets in a language plugin?

**Comment by egamma** [comment]
> ok, another question then: how can I re-implement emmet snippets in a language plugin?

Is the question to enable emmet snippets for a particular file type? 

The emmet implementation maintains a table of file types in which emmet is enabled. You could provide a PR to enable this for your language. This is the [source](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/emmet/node/editorAccessor.ts#L22).

**Comment by Spown** [comment]
I thought emmet was an option to enable in a lang plugin... but it's totally unrelated, I see... I would say this hidden config is kinda wrong, either should it be a plugin configuration switch or a user setting... Anyway I got the big picture and I guess I'll just stick to the HTML lang for the time being. I guess you can close the issue.

Thanx

**Comment by egamma** [comment]
I agree that hard coding is not correct and needs to be improved. Closing this issue as suggested.

**Comment by Spown** [comment]
just wanted to add that [TWIG pack](/Bajdzis/vscode-twig-pack) is basically what I needed. It's syntax is consistent with Nunjucks and it has emmet and proper HTML handling

**Comment by jitendravyas** [comment]
@Spown Emmet is not working for me with `.nunjucks` files even with https://github.com/Bajdzis/vscode-twig-pack

**Comment by Spown** [comment]
@jitendravyas ``vscode-twig-pack`` works with ``twig, html.twig`` files. I configure my nunj projects to use simply ``.html`` extensions in templates. If you want to use ``.nunjucks`` you have to configure it use the HTML syntax when the ``vscode-twig-pack`` is installed. I don't know how or whether it is possible.

**Comment by mrmlnc** [comment]
@jitendravyas, @Spown, 

We have done everything possible to Emmet supported all available languages.

You can use `emmet.syntaxProfiles` option in settings of Editor. For example:

```json
"emmet.syntaxProfiles": {
  "nunjucks": "html"
}
```

Documentation: http://code.visualstudio.com/updates/v1_5#_settings-to-enabledisable-emmet-for-languages

**Comment by ramya-rao-a** [comment]
Hey All,

From VS Code 1.15 onwards, please use `emmet.includeLanguages` instead of `emmet.syntaxProfiles` to get Emmet abbreviation expansion features in your language of choice.

We are making this move because of the confusion around what `emmet.syntaxProfiles` setting was originally meant for i.e [Customizing final output](https://docs.emmet.io/customization/syntax-profiles/) and what it became i.e enabling emmet in new languages.

Please read more on this at [Emmet 2.0](https://code.visualstudio.com/blogs/2017/08/07/emmet-2.0)
