### ISSUE TITLE
"Hide Badge" doesn't persist across restarts

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#168977]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.75.0-insider (11238faea62d570d77afe6edfe05c8b732c44a2b)
- OS Version: 10.0.22621

Steps to Reproduce:

1. open VS Code
2. use "Hide Badge"
3. restart VS Code

Expected behavior: "Hide Badge" persists across restarts

**Comment by lramos15** [comment]
\duplicate https://github.com/microsoft/vscode/issues/168939
