### ISSUE TITLE
Quick Fix menu not scrollable

### ISSUE THREAD

**Issue by JacksonKearl** [microsoft/vscode#168955]
Helo!

I use the code spell checker extension which provides quick fixes for spelling "error"s. Often these are just terms that I've adopted as standard in the repo and don't aim to change. However, with the recent change to use custom context menus instead of the native ones the list of spelling quick fixes causes the refactorings I actually want to use to be out of the window, with no way to scroll them into view. 

With spell checker extension enabled:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/8586769/207236872-140e30c4-2c7e-4309-a0c0-4626ff2b3633.png">

Without:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/8586769/207236815-de065df3-a2d9-4541-9bcb-a042a2e79118.png">

Ideally the menu would support scroll. I'd accept an option to use native menus instead (the icons are nice to have but not critical). Alternatively, at minimum perhaps the refactorings could be sorted above quick fixes?

@mjbvz @sbatten

**Comment by mjbvz** [comment]
We should also limit the height of the menu. Not very pleasant to have it take up the entire height of the window

**Comment by JacksonKearl** [comment]
Works great, thanks!
