### ISSUE TITLE
terminal window is not appearing

### ISSUE THREAD

**Issue by nkosazana11** [microsoft/vscode#168925]
ADD ISSUE DESCRIPTION HERE

Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by nkosazana11** [comment]
my terminal window does not appear on sreen

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
