### ISSUE TITLE
Ambiguous "Cannot invoke an expression" hint

### ISSUE THREAD

**Issue by eserozvataf** [Microsoft/vscode#169]
I was browsing my code with visual studio code beta (v0.10.1), it underlines 5. line and says "cannot invoke an expression whose type lack a call signature.". I think the code hasn't any problems since it's not an typescript project or something type-restricted. I wanted to report it if it is a bug.

```js
                let queryMethod = isEmail ?
                    { email: userModel.getSingleByEmail } :
                    { username: userModel.getSingleByUsername };

                queryMethod(user_)
                    .then((userRecord) => {
```

Note: I didn't changed any configuration option but enabling es6 from jsconfig.json file.

**Comment by bumpmann** [comment]
`queryMethod` looks like a simple object so you cannot call it like a function, so i think this error is normal since there's no call signature for this object.

**Comment by jrieken** [comment]
Thanks @bumpmann. `queryMethod` is defined as an object which unlike a function or constructor doesn't have a call signature.

**Comment by eserozvataf** [comment]
sorry I noticed the problem after I posted this, it was definitely my bad.

**Comment by jrieken** [comment]
no worries
