### ISSUE TITLE
Selecting a different launch config should not launch it

### ISSUE THREAD

**Issue by joaomoreno** [Microsoft/vscode#16903]
With the latest UI change to that widget, we should not automatically launch just by switching the launch configuration, but rather simply select it and have the user press the Play button, like before.

Sad, I know. 😢

**Comment by isidorn** [comment]
This is up for discussion, but I agree it is not smart ot rush this change in.
So for this milestone lets behave like before and then @chrisdias or @weinand can file feature request for january if they want automatic launch by switch

**Comment by weinand** [comment]
Automatically launching a session makes only sense if the UI is based on a Play button without text (like Eclipse is doing it for 12 years).
If there is text next to the Play button, then the UI is a 'drop down' menu which typically **does not** trigger an action.

**Comment by joaomoreno** [comment]
I also have a feeling that the double arrow ![image](https://cloud.githubusercontent.com/assets/22350/21007201/37f9ae2a-bd3c-11e6-921e-78e5e9853b90.png) makes a difference from a single down arrow ▼.
