### ISSUE TITLE
highlighted files in the explorer 

### ISSUE THREAD

**Issue by DeadlyKom** [microsoft/vscode#169049]
Type: <b>Bug</b>

the problem of updating highlighted files in the explorer after fixing them (continues to highlight them). restart helps.

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.30GB free)|
|Process Argv|--crash-reporter-id b9b9e859-26d9-451c-90e3-6d0983fd05e7|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
asm-code-lens|maz|2.1.0
dezog|maz|3.1.1
z80-instruction-set|maz|1.1.1
z80-macroasm|mbo|0.7.8
z80-asm-meter|the|3.2.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by lramos15** [comment]
\gifPlease

**Comment by DeadlyKom** [comment]
https://user-images.githubusercontent.com/23453697/207657762-4a1e987b-94c8-4db9-be46-ba533808d368.mp4

**Comment by lramos15** [comment]
Is this talking about how after getting rid of a problem it still shows in the problems view?

**Comment by DeadlyKom** [comment]
yes, that's right, I remember that I found the answer, but I spent a lot of time and didn't find a solution...

**Comment by lramos15** [comment]
I believe this is caused by the language server extension. Please file a bug to https://github.com/maziac/asm-code-lens
