### ISSUE TITLE
Add find and replace in files/project

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1690]
<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>f</kbd> dialog does not feature a project-level find and replace.

**Comment by bpasero** [comment]
:+1:

**Comment by philipgiuliani** [comment]
:+1: Required for me!

**Comment by tschwartz** [comment]
:+1:

**Comment by bunterWolf** [comment]
(y)

**Comment by bunterWolf** [comment]
:thumbsup:

**Comment by morrismukiri** [comment]
+1

**Comment by ianwesterfield** [comment]
:+1:

**Comment by jaysylvester** [comment]
Please.

**Comment by be5invis** [comment]
:+1:

**Comment by Tyriar** [comment]
There were 6 distinct :+1:'s on https://github.com/Microsoft/vscode/issues/773

**Comment by be5invis** [comment]
Finally...
༼ つ ◕\_◕ ༽つ PRAISE CODE ༼ つ ◕\_◕ ༽つ

**Comment by Roustalski** [comment]
What is this still doing in the backlog? There are more important features? [:

I'm currently using another editor just for the cases when I have to do a mass find-replace for refactoring.

+1

**Comment by tjosbon** [comment]
+1

**Comment by johnsoncze** [comment]
:+1:

**Comment by JeandeCampredon** [comment]
+1

**Comment by christianmenz** [comment]
+1

**Comment by danhowitt** [comment]
+1

**Comment by dgghita** [comment]
+1 :+1:
I'm in the same situation of having to use something else solely for "replace all" in multiple files :(

**Comment by JeandeCampredon** [comment]
Ok let's try with product pain:
https://productpains.com/post/visual-studio-code/replace-all-occurences-in-multiple-files-of-a-project

**Comment by dgghita** [comment]
@JeandeCampredon To be fair, since it's been assigned, it does look like this is being worked on now :)

**Comment by ashes999** [comment]
The correct place for this is User Voice: https://visualstudio.uservoice.com/forums/293070-visual-studio-code/suggestions/11329521-find-and-replace

Please add votes there.

**Comment by Tyriar** [comment]
@ashes999 both user voice and [:+1:'s on GitHub](https://github.com/Microsoft/vscode/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc) are useful.

**Comment by ashes999** [comment]
@Tyriar if you look at user voice, MS employees actually respond to and act on those. So it's a matter of getting enough momentum there. (I don't know how closely they look at GitHub issues.)

**Comment by luisrudge** [comment]
:+1:

**Comment by ClementVidal** [comment]
:+1:

**Comment by krasi0** [comment]
+1

**Comment by Tyriar** [comment]
@ashes999 I'm one of the said Microsoft employees :smiley:

I think if GitHub reactions were around at launch then we wouldn't have needed user voice. Currently both lists are used to find what features are highly desired by the community.

**Comment by tsirolnik** [comment]
Please add this feature

**Comment by ruspaull** [comment]
+1

**Comment by mevdschee** [comment]
+1

**Comment by VRspace4** [comment]
+1

**Comment by johnfredrik** [comment]
+1

**Comment by bogosts** [comment]
+1

**Comment by olivierl** [comment]
+1

**Comment by Tyriar** [comment]
Hi all, prefer :+1: reactions on the original issue comment as that helps us with prioritization.

**Comment by JoeCostanzo** [comment]
+1

**Comment by cesarvarela** [comment]
Can't believe you guys went past version 1.0 without this!

**Comment by caseyhoward** [comment]
@cesarvarela I agree. Maybe there is an extension or something. I tried looking and couldn't find one.

**Comment by tsirolnik** [comment]
God, stop posting these +1's.
And wouldn't it be easy as calling the find&replace function over the found files?
I'll try looking it up

**Comment by Tyriar** [comment]
@tsirolnik it is as easy (or as hard) as that. It can be quite a task with matches spanning across a significant amount of files.

**Comment by aleksey-bykov** [comment]
:+1:

**Comment by xtbe** [comment]
:+1:

**Comment by TonyCurtisLives** [comment]
+1 this is a pain to do now. Also the file find/replace box covers the first line of code, very annoying!

**Comment by gavinslilley** [comment]
👍 👍 👍 👍 👍 👍 👍 👍

**Comment by shaneparsons** [comment]
+1 Probably one of the most important features to have... It makes **no** sense not to have it in.

**Comment by CarlosPlusPlus** [comment]
👍

**Comment by ammario** [comment]
This is the only thing keeping this editor from being my primary choice. It's a simple thing to implement but it saves SOOOOO much time.

**Comment by sksea** [comment]
👍

**Comment by dmiorandi** [comment]
+1

**Comment by TamerZorba** [comment]
+1 👍

**Comment by bpasero** [comment]
This is coming for June, stay tuned.

@sandy081 you deserve credit here.

**Comment by tsirolnik** [comment]
Praise the mighty @sandy081 🤗🎉

**Comment by sandy081** [comment]
Implemented using #7602

**Comment by dazewell** [comment]
And what about replacing by regexp captures?
**Content:** `SomeTextAndStopKeyword`
**Find:** `(.*)AndStopKeyword`
**Replace:** `StopKeywordAnd$1`
**Expect:** `StopKeywordAndSomeText`

Currently, I see it just replaces with a plain text `StopKeywordAnd$1`, while inline Search&Replace works just fine.

**Comment by jacquelineth** [comment]
Why is **Regex** Replace  supported on single file edition and not on multiples files, where it is really needed.
You **may search with Regex, but not replace/substitute** based on your regex conditions..

Furthermore, since preview is provided, there no risk of massive/unexpected changes
Other node based editor already implements it like Atom.

**Comment by sandy081** [comment]
@dazewell @jacquelineth 

There was no reason for not supporting it. I just pushed this feature today and is available from next insiders build. - https://github.com/Microsoft/vscode/issues/9010

Thanks

**Comment by dazewell** [comment]
Cool!
Thanks, looking forward using it.

**Comment by jacquelineth** [comment]
Just used it.... Awesome.
Thanks a lot!

**Comment by dazewell** [comment]
Today I had an update but it doesn't seem to contain those changes. So, I'm still waiting.
But what about those hotkeys for turning on the RegExp mode and Whole Word mode and Case Sensitive mode for the Global Search?

**Comment by Tyriar** [comment]
@dazewell I think you're referring to https://github.com/Microsoft/vscode/issues/4719, please add a :+1: to show your interest in it.

**Comment by sandy081** [comment]
It is available in latest insiders build (not on stable).

![screen shot 2016-07-14 at 8 10 04 pm](https://cloud.githubusercontent.com/assets/10746682/16850351/fb738bde-49fe-11e6-96a4-9e780671c5b9.png)

**Comment by dazewell** [comment]
@Tyriar thanks, that's exactly what I was talking about. Sorry for polluting this issue.
@sandy081 understood, thanks!

**Comment by repositorio-ultra** [comment]
Why is it that VS Code limits find/replace to 999 occurences only?
