### ISSUE TITLE
[regression] Cannot navigate from output panel to editor anymore

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode#16907]
When having a hygiene fail in the precommit hook, I would navigate to the file using ctrl+click in the output editor. This appears to be no longer working for me.

The hover shows I can ctrl+click, but it has no effect:

![image](https://cloud.githubusercontent.com/assets/5047891/21005067/a3a520ea-bd33-11e6-9c5a-d5d6dbe868cb.png)

**Comment by bpasero** [comment]
@alexandrudima since I see the same when trying to click a link in a HTML file, I suspect this is an editor regression.

**Comment by bpasero** [comment]
![view-picker](https://cloud.githubusercontent.com/assets/900690/21005226/3b1eece4-bd34-11e6-9a00-739a83881b5b.gif)

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16922
