### ISSUE TITLE
Overlapping Sticky Scroll in `Go To Implementation` editor preview

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#169016]
<img width="727" alt="image" src="https://user-images.githubusercontent.com/31675041/207393981-13050090-5474-47ea-bf7f-4643be0fd6e4.png">

Hovering on the overlapping text will make the sticky scroll text visible.

**Comment by jrieken** [comment]
https://github.com/microsoft/vscode/issues/169042
