### ISSUE TITLE
VSCode 1.74.0 lost zsh history in terminal

### ISSUE THREAD

**Issue by ljhm** [microsoft/vscode#169007]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: Version: 1.74.0 (Universal)
- OS Version: macOS 12.6.1 (21G217)

Steps to Reproduce:

1. The zsh terminal in VSCode lost command history, brought in 1.74.0. It did not happen in previous version.
2. The Debug terminal in VSCode has full history.
3. The system terminal has full history.

![Screen Shot 2022-12-13 at 10 59 01 PM](https://user-images.githubusercontent.com/9011764/207368421-678ae003-6bf4-4ad7-8aa6-31f3a9ccafbc.png)
![Screen Shot 2022-12-13 at 10 59 06 PM](https://user-images.githubusercontent.com/9011764/207368439-1f5f4c66-37d0-49eb-b56b-8f9d0e2b9100.png)
![Screen Shot 2022-12-13 at 10 59 09 PM](https://user-images.githubusercontent.com/9011764/207368449-a30498a8-ff3d-4e2a-a024-8b59c0c83e7e.png)

**Comment by meganrogge** [comment]
/duplicate https://github.com/microsoft/vscode/issues/168396

already fixed in insider's and soon to be fixed in our recovery release (tomorrow)
