### ISSUE TITLE
Support to navigate to the extended jsconfig/tsconfig.json

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#16905]
TS now support `extends` in the tsconfig.json file see below for an example from:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#configuration-inheritance

![image](https://cloud.githubusercontent.com/assets/172399/21004741/3b8cdf58-bd32-11e6-9c86-68f488174879.png)

It would be nice when the referenced file is validated (should be provided by TS) and the tsconfig.json editor  supports to navigate to the referenced file.

// CC @kieferrm

**Comment by aeschli** [comment]
This would best be done by the typescript extension, by registering link and validation support for the tsconfig.json file.
Note that validating that the link exists is expensive as it requires a file change listener on the whole workspace (and maybe even on files outside). Simply validating that the path is in the correct shape can be done with a regex in the schema.

The alternative is to make relative file paths a 'official' element type in JSON schema. Then schemas could be annotated by it and the JSON language server could provide the link.

**Comment by albangicquel** [comment]
+1

**Comment by mjbvz** [comment]
@aeschli I'm interested in a generic approach that let us mark `paths` in a schema. There are plenty of other json file types that also use paths for properties, such as the `main` and `types` entires in the `package.json`. Having to register s custom link provider for each file type seems redundant

**Comment by aeschli** [comment]
@mjbvz This can be done by introducing a new, VSCode proprietary, `format` for schemes:
https://spacetelescope.github.io/understanding-json-schema/reference/string.html#format
We already do that to mark colors.

Challange with adding support for paths is that the schema validation code is in [vscode-json-languageservice](https://github.com/Microsoft/vscode-json-languageservice) that must not have any node dependencies as it is also used by the monaco editor.
That means validation/code completion support would have to come in through a `file service` passed to the json-languageservice.

**Comment by JacksonKearl** [comment]
We don't implement this as described in the linked TS docs. We require the ".json" extension to be present when the docs don't include it.
