### ISSUE TITLE
Bracket write igrone

### ISSUE THREAD

**Issue by justnonamenoname** [Microsoft/vscode#16904]
- VSCode Version: Any
- OS Version: Win7

Steps to Reproduce:

1. Copy&Past this to new document: [[]
2. If you write ] after 2'nd sym - ] will not be writed

I suggest check count of brackets for add or not to add 2'nd bracket pair
[[]] - don't add ] after 2'nd sym
[[] - add ] after 2'nd sym

I think count brackets only on selected line is enough

**Comment by rebornix** [comment]
Shares the same root cause as https://github.com/Microsoft/vscode/issues/11222 , just like @justnonamenoname described, we didn't do any bracket matching count.
