### ISSUE TITLE
Add cursors to end line should not be in selection menu

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16908]
Selection menu > add cursors to end lines

This feature does not do anything 90% of the time and is a pro feature which should not be in the selection menu.
We should remove it from there imho

If we want to make the users aware of such commands we shuold write a blog post and bloat the menu. Having a smaller menu is better for start as it is always easier to add stuff than to remove.

**Comment by chrmarti** [comment]
Having a separate menu for Selection it makes sense to call out our support for multi-cursor and multi-selection operations. We could replace these with other multi-cursor commands, but it seems these are the basic ones.

**Comment by isidorn** [comment]
IMHO this one is not basic. There are already enough multi-cursor commands.
If we replace something in the future there might always be users that miss it. I recommend we remove this action straight away.

**Comment by chrmarti** [comment]
To be fair, these menu items are mostly there such that users can memorize the keyboard shortcuts. They are all too cumbersome to use through the menu, IMHO. Very few users are going to miss those that we decide to remove in the future.
