### ISSUE TITLE
Problem push github

### ISSUE THREAD

**Issue by JordanAzko** [microsoft/vscode#169005]
Type: <b>Bug</b>

Bonjour, 

nous recontrons depuis la dernière mise à jour de vscode un soucis quand on souhaite commit des changements sur main

La command sync fait :
push > pull à la place de faire pull > push

Nous n'avons jamais eu de problème jusqu'à la version 1.71.2 de vscode puis nous qui somme à la version 1.74 nous rencontrons ce soucis

En vous remerciant de traiter ce soucis au plus vite

=================================================================================

Hello,

we encounter since the last vscode update a problem when we want to commit changes on main

The sync command does:
push > pull instead of pull > push

We never had a problem until version 1.71.2 of vscode then we who are at version 1.74 we encounter this problem

Thanking you for dealing with this concerns as soon as possible.

=================================================================================

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.81GB (1.38GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 5cccba09-2685-4c71-bd63-ec4d821ee996|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
better-comments|aar|3.0.2
path-intellisense|chr|2.8.3
gitlens|eam|13.1.1
vscode-html-css|ecm|1.13.1
RunOnSave|eme|0.2.0
prettier-vscode|esb|9.10.3
beautify|Hoo|1.5.0
ftp-simple|hum|0.7.6
git-last-commit-message|Jan|1.9.0
google-fonts|lio|0.0.1
gsap-greensock-snippets|Max|1.0.2
vscode-language-pack-fr|MS-|1.74.12070929
powershell|ms-|2022.11.0
color-highlight|nau|2.5.0
indent-rainbow|ode|8.3.1
vscode-sassdoc|raf|1.0.3
LiveServer|rit|5.7.9
sass-indented|syl|1.8.23
tabnine-vscode|Tab|3.6.31
errorlens|use|3.6.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
dbltrim-noruby:30604474
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by JordanAzko** [comment]
If this can help you : https://github.com/microsoft/vscode/issues/168861

I saw this post who had the same bug

It's solve with VsCode Insider (1.75)

**Comment by lszomoru** [comment]
@JordanAzko, this has also been fixed in the latest Stable release. Could you please upgrade to the latest Stable release and reopen this issue in case you are still able to reproduce the problem. Thank you very much!
