### ISSUE TITLE
Breadcrumbs open to the side with keyboard shortcut not working

### ISSUE THREAD

**Issue by andreskebe** [microsoft/vscode#169080]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.0
- OS Version:  Mac OS Monterey 12.6

Steps to Reproduce:

1.  Focus breadcrumbs
2. Navigate using arrow keys
3. Open the picker for a file/folder segment
4. On a file tree node, do `alt-enter` (also tried `cmd-enter`) on a file on breadcrumb
5. Nothing happens

I am able to open a file on the side from the breadcrumbs when i do `alt-click`.

Was this functionality removed? I also don't see a command for doing this in the key bindings.

**Comment by jrieken** [comment]
@andreskebe Do you mean the breadcrumbs themselves (1) or the breadcrumbs picker (2)?

<img width="679" alt="Screenshot 2022-12-14 at 09 42 29" src="https://user-images.githubusercontent.com/1794099/207548050-090e4495-df36-49bf-b9f8-80e7c64d44b6.png">

**Comment by andreskebe** [comment]
@jrieken 
I meant the breadcrumbs picker! Alt clicking opens on the side but it is impossible to open any of these files to the side using the keyboard.

**Comment by jrieken** [comment]
Thanks for clarifying. Open from the picker to the side is bound to `ctrl+enter` (`cmd+enter` on mac). It will run this command: `breadcrumbs.revealFocusedFromTreeAside`. Can you check whats being invoked for you? Do F1 > Toggle Keyboard Shortcuts Troubleshooting and in the output view check what command is being executed?

**Comment by andreskebe** [comment]
I had a feeling this was the command and so i changed from `cmd-enter` to `alt-enter`.
Now the super weird thing is that i see this command being executed `Invoking command breadcrumbs.revealFocusedFromTreeAside.` but it doesn't _actually_ execute. 
I've attached a screenshot of the output. I did clear everything until i trigger the shortcut, do you want me to send you more the previous logs as well? 

 
<img width="1487" alt="Screen Shot 2022-12-15 at 11 05 01 AM" src="https://user-images.githubusercontent.com/16766540/207895298-f5a9affe-73e1-47ca-9a7e-333a421ccc62.png">

**Comment by jrieken** [comment]
Oh, now I can reproduce but only when trying with a file, but when trying with a symbol

**Comment by andreskebe** [comment]
Thank you 🙏🏽
