### ISSUE TITLE
Extensions in portable mode are broken

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#169006]
From @keck9939

If you follow exactly the instructions at https://code.visualstudio.com/docs/editor/portable#_migrate-to-portable-mode to migrate to portable mode, the extensions vanish. (I'm using Windows 10, VSCode 1.74.0). I did move rather than copy the data and code directories. This may be important, otherwise it might find things in the original location.
In addition, if you re-install the extensions in the portable installation after following the referenced instructions, and then move the whole portable directory from say d:\vscode to e:\vscode, the extensions will vanish again.

Steps to Repro:

- Create a portable VS Code and install some extensions
- Copy this set up to another machine
🐛 No extensions are shown

**Comment by sandy081** [comment]
Here is the workaround until this fix is available

- Open the extensions folder and delete following files - `extensions.json` and `.init-default-profile-extensions`

**Comment by animehunter123** [comment]
Hello, Thank you for sharing this workaround. Will this be fixed in a future version? (I use a USB Stick, and when the drive letter changes, it has to be repeated again)? Thanks!

**Comment by sandy081** [comment]
> Will this be fixed in a future version?

Yes, it is and will be available in next release 1.75.0

**Comment by Crystal-RainSlide** [comment]
There are other files that contain absolute paths too:
- `./data/user-data/languagepacks.json`
- `./data/user-data/User/globalStorage/storage.json`

Those absolute paths will be updated on VSCode start, thus they are not causing any breakages. But, to reduce file change for those portable mode users on the go, is it possible to share the new `toRelativePath()` function and apply the same fix to the code related to those files?
