### ISSUE TITLE
TextEditor.setDecorations() doesn't respects the decorations ordering

### ISSUE THREAD

**Issue by rentalhost** [microsoft/vscode#169051]
**Does this issue occur when all extensions are disabled?:** Yes

- **VS Code Version:** 1.74.0
- **OS Version:** Windows 11 x64

**Steps to Reproduce:**

I'm trying to apply multiple decorations in the same line. My intention is to highlight some parts of the text in other colors.

For example:

![image](https://user-images.githubusercontent.com/421851/207444241-cedf08ac-4d10-4400-aaa7-88af691d53f0.png)

It seems to me that it is something possible, however, vscode is not respecting the order of the decorations, and ends up inverting them randomly.

The code is something like:

```
const decorationDefault = window.createTextEditorDecorationType({})

const flush = (editor: TextEditor) => {
  // Note: same range for all decorations.
  const range = new Range(new Position(1, 4096), new Position(1, 4096))

  editor.setDecorations(decorationDefault, [
    { range, renderOptions: { after: { color: "gray", contentText: "Hello, " } } },
    { range, renderOptions: { after: { color: "blue", contentText: "user" } } },
    { range, renderOptions: { after: { color: "gray", contentText: "!!!" } } },
  ])
}
```

My question is, is there any way to ensure order is maintained like this example? None of my attempts worked. It looks like a bug to me, or I'm misusing it.

![image](https://user-images.githubusercontent.com/421851/207445728-d39340ac-fcea-4181-8057-ece8f548d3de.png)

**Comment by rentalhost** [comment]
**After note:** I managed to get this to work in a very "hackish" way. For each style variation, I need to create a new style. So if I need 8 variations on the same line, I'll need to manage 8 different styles. I really hoped that I could do it with one style, actually.

**Comment by alexdima** [comment]
We store decorations in a [red-black interval tree](https://github.com/microsoft/vscode/blob/main/src/vs/editor/common/model/intervalTree.ts) for [performance reasons](https://github.com/microsoft/vscode/pull/36410). Unfortunately, we can't guarantee that the reading order from the tree is the same as the insertion order due to the various rotation operations that occur in a red-black tree to keep it balanced. I'm sorry, but in the foreseeable future the only way is the workaround you have found.

**Comment by rentalhost** [comment]
@alexdima Oh, that seems very strange to me (probably because I didn't understand the red-black tree well).

The red-black tree update struck me as surprising. The performance was very valuable indeed. However, I still can't understand how it works in such a "random" way, since the data is always pushed in a certain order.

If the red-black tree decides the render order somehow, what parameter is used to make this happen? Perhaps it is possible to control this from my side?

I am not satisfied with the method I used. Well, it works fine, however, it seems too hackish (and probably much slower than if it were done natively).
