### ISSUE TITLE
Source location hover in CALLSTACK view shows bogus path for internal modules

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16913]
- VSCode Version: 1.8.0 Insiders

The source path starts with the (internal) variable reference used in the debug protocol: 
![2016-12-08_12-09-22](https://cloud.githubusercontent.com/assets/1898161/21007884/44868e9e-bd3f-11e6-8dc6-a11047c4d5e5.png)

We should find a better path root for this.
Ideally we should use a 'magic world' that could be used in the 'Just my code' feature to filter those modules (see https://github.com/Microsoft/vscode/issues/16918).
But the VS Code frontend should not hardcode this.

**Comment by isidorn** [comment]
@weinand so how do you propose that this magic word is contributed to vscode? Should I come from the source request?
What should ideally appear on the hover? `internal_module/module.js`?

**Comment by Eli-Goldberg** [comment]
@weinand 
Finally, Thanks.
I've opened a bug about this before: https://github.com/Microsoft/vscode/issues/17301
but couldn't reproduce.
This happens all the time when stepping in.

**Comment by weinand** [comment]
@isidorn the frontend should not have to know anything about this case. So the 'magic word' would be introduced by the backend (debug adapter) and for the debugger UI it would just appear as a regular  path segment.

**Comment by isidorn** [comment]
@weinand the frontend currently simply takes the fs path for each uri in the callstack. For internal modules this uri is fake and looks something like 'debug://internal/1056/module.js' so the fs path is 1056/module.js, namely the reference and the name.
Different internal modules need to have different uris so we decided in the past to include the reference when generting this fake uri.

Instead of using a fsPath for internal modules the frontend could use anything coming from the adapter. Should we add something to the protocol or is there already something we can use?

**Comment by roblourens** [comment]
It seems like the UI should only show `module.js` even if it uses the reference as a unique ID internally. Why do we need a magic word instead of only showing `module.js`?

**Comment by weinand** [comment]
We will continue to show only `module.js` in the CALLSTACK. But on hover we currently show the full path and the frontend manufactures a (fake) path by using the source ID. This is wrong.

Instead of doing this we should show something that makes clear that `module.js` is not a file the user will find in his workspace, but is an internal module.

If we do not want to extend the debug protocol, we could manufacture a 'better' fake path that says something like `"core_modules/module.js"`. This would be shown on hover and we could use the `core_modules` in skipFiles glob patterns as well, e.g. `"core_modules/**/*.js"`. This would be a nice consistent story.

Alternatively we could introduce some optional `information` attribute on the `Source` debug type and communicate 'internal core module' from the debug adapter to the hover. For skipFiles we would have to invent a corresponding mechanism so that the user could configure to skip internal core modules.

**Comment by isidorn** [comment]
As usual, I prefer the more pragmatic approach, the first one you proposed - manufacture a 'better' fake path.
Though I do not have strong feeling and the alternative approach would also work for me here.

**Comment by roblourens** [comment]
`$/module.js`, `%/module.js`, `&/module.js`? A symbol is simple but might not be clear what it means. `<node_internals>/module.js`

**Comment by weinand** [comment]
@isidorn as a first step towards a solution I suggest that we try to remove the path magic in the debugger UI.
- When the debug adapter returns a source object without a path, the UI manufactures a path from the `sourceReference` of the form `/1000/module.js`. Since `sourceReference` is an implementation detail of the debug adapter, it does not make sense to surface it to the user.<BR>-> I suggest to use the value of the `name` attribute for the hover if `path` is missing.
- When I return a source object with a `path` attribute `<node_internals>/module.js` it shows up in the UI as `/<node_internals>/module.js`<BR>-> I suggest to show the `path` as is, without any modification.
- If I click on a stackframe with a `<node_internals>/module.js` path, the debugger UI tries to open the path in the editor. This fails which is ok because the debug spec says: "It is not guaranteed that the source exists at this location". However, the UI should not show this as an error if a `sourceReference` is provided.<BR>-> I suggest that you try to load the source via the `sourceReference` if the load via the `path` fails. 

@isidorn do you see any issues with this approach?

**Comment by isidorn** [comment]
@weinand thanks for the suggestion, however there are limitations to what we can customise in how our workbench is display a uri.

First thing we need to consider is what internal URI representation does an internal module have. Every resource in the workbench needs to have a unique uri. Once we know that everything flows automtically from there. Currently this uri for internal modules lookes like `debug://internal/1002/module.js`

As for the last point I agree that it always makes sense to give priority to the source reference and this is fully in our control.

**Comment by weinand** [comment]
@isidorn You can continue to use your current URI representation for internal modules (as long as you are not persisting soureReferences across sessions because that would be a violation of the protocol spec).
My proposal from above only talks about what the user should see, not how this is implemented.

**Comment by weinand** [comment]
@isidorn I've delivered feature #16918 for node-debug. Since this change will return a `<node_internals>/module.js` path for internal modules it will result in the errors explained above in my comment https://github.com/Microsoft/vscode/issues/16913#issuecomment-270666642

**Comment by isidorn** [comment]
@weinand I tried out your change with my latest changes and it looks good.

We need to update the documentation as previously we would "declare" something an internal module if it does not have a `path`. Now this has changed, something is an internal module if it has `sourceReference > 0` which makes sense IMHO

**Comment by weinand** [comment]
@isidorn perfect timing!
Yes, I've updated the protocol spec already (but need to push the change).

**Comment by isidorn** [comment]
@weinand great 😉

**Comment by weinand** [comment]
@isidorn the protocol spec never talked about 'internal modules'. It only alluded that the content of a source is loaded either via a `path` or a `sourceReference` (but left unspecified what happens if both are given).

I tried to make this more precise by tweaking the comments for `path` and `sourceReference`:
- path: "The path of the source to be shown in the UI. It is only used to locate and load the content of the source if no sourceReference is specified (or its vaule is 0)."
- sourceReference: "If sourceReference > 0 the contents of the source must be retrieved through the SourceRequest (even if a path is specified). A sourceReference is only valid for a session, so it must not be used to persist a source."

**Comment by isidorn** [comment]
Looks good to me
