### ISSUE TITLE
Activated linter does not go away when switching language mode

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#1691]
**Steps to reproduce**

1. Create an invalid file featuring invalid javascript, such as:

        # I'm invalid

2. Switch language mode to javascript (command palette -> `"lang"` -> <kbd>enter</kbd> -> `"javascript"` -> <kbd>enter</kbd>)
3. Observe red underlines indicating linter errors
4. Switch language mode to something other than javascript

**Expected**

The javascript linter is deactivated

**Actual**

The javascript linter errors remain

**Comment by dbaeumer** [comment]
Happens with the built-in javascript linter.

**Comment by jrieken** [comment]
Closed with the adoption of Salsa (https://code.visualstudio.com/Updates#_languages-javascript).
