### ISSUE TITLE
xdebug not working

### ISSUE THREAD

**Issue by Esmerioneto** [microsoft/vscode#169174]
Type: <b>Bug</b>

Listening to Xdebug on port 0.0.0.0:9003 ...
I use vscode and xdebug for a long time, but in the last week I formatted my notebook and installed all the tools again. vscode cannot communicate efficiently with php's xdebug and I have tried several configurations to make it work, but without success.
Can you help me with this configuration?
Here is the information I get in the vscode terminal itself.
this is my launch.json file
{
    // Use o IntelliSense para saber mais sobre os atributos possíveis.
    // Focalizar para exibir as descrições dos atributos existentes.
    // Para obter mais informações, acesse: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
          {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9003
        }
    ]
}

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:47:18.476Z)
OS version: Linux x64 5.15.0-56-generic
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 2, 2|
|Memory (System)|15.55GB (3.45GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|wayland|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
composer-php-vscode|DEV|1.25.11537
phptools-vscode|DEV|1.25.11537
profiler-php-vscode|DEV|1.25.11537
xml|Dot|2.5.1
gitlens|eam|13.1.1
vscode-language-pack-pt-BR|MS-|1.74.12140933
format-html-in-php|rif|1.7.0
php-debug|rob|1.14.0

</details>

**Comment by roblourens** [comment]
Please file on the xdebug extension
