### ISSUE TITLE
Just my code: introduce a magic path for core modules

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16918]
Just my code: introduce a magic path for excluding/including core modules, e.g.:
```ts
    "skipFiles": [
        "core_modules/*.js"
    ]
```

In addition we should use the same magic path when showing core modules in the CALLSTACK view. This will fix the bogus path problem #16913.

**Comment by weinand** [comment]
@roblourens any suggestion what 'magic path' (or better: 'magic segment') to use for core modules?
To prevent collisions with real path segments, we could use a special character like '💻' alone or combine it with a selector, e.g. '💻core_modules'.

**Comment by roblourens** [comment]
We could use just `"*.js"` as a glob for js files that aren't under any path? I wouldn't want to use a character that I can't type, and any magic path will end up having collisions.

We could also special case it with a new flag, `"skipNodeInternals": true`

**Comment by roblourens** [comment]
Actually, that wouldn't work under what node2 does, which is to allow giving just the name of a file to skip, even if it's under some path. 

Could allow `"^*.js"` as a pseudo-regex, don't know if that's confusing. Or a special selector like `"{node_internals}"`

**Comment by weinand** [comment]
@roblourens `"{node_internals}"` is already glob syntax.
How would you like node2's internal modules be presented in the CALLSTACK view? Today node1's internal modules show up as `/<scriptid>/<name>` (see bug #16913). If we could find a better representation for this, we could use that for the skipFiles glob pattern as well.

**Comment by weinand** [comment]
I will introduce a magic segment `<node_internals>` for internal node modules. With this it is possible to use a glob pattern `"<node_internals>/**/*.js"` for skipping over internal node modules.

**Comment by roblourens** [comment]
This will also be triggered if anyone evals a script and gives it a sourceURL of some name that isn't an absolute path. I don't think that would be very common in Node, but there's always some weird library, just FYI in case it ever comes up. Maybe we would have to hardcode the list of node script names as a workaround.
