### ISSUE TITLE
Git clone pop-up menus don't close when other areas are clicked

### ISSUE THREAD

**Issue by weartist** [microsoft/vscode#169126]
Type: <b>Bug</b>

Steps to Reproduce:

1. Check to source control tab
2. Click clone option
3. An input box that pops up for clone for github

Expected: The input box closes when you tap a different area
Actual: The input box will stay

If this is indeed a bug, I'm willing to fix it

VS Code version: Code 1.74.0 (Universal) (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:43:37.594Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|--crash-reporter-id a0e70e19-77dc-4670-9ebc-f19a3a98c398|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
webview|che|0.0.1
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
vscode-eslint|dba|2.2.6
githistory|don|0.6.19
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
go|gol|0.36.0
better-cpp-syntax|jef|1.17.2
theme-monokai-pro-vscode|mon|1.2.0
vscode-language-pack-zh-hans|MS-|1.74.12070927
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.7
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
mono-debug|ms-|0.16.3
remote-explorer|ms-|0.0.3
vscode-selfhost-test-provider|ms-|0.3.11
godot-csharp-vscode|nei|0.2.1
vscode-thunder-client|ran|2.1.2
rust-analyzer|rus|0.3.1317
code-spell-checker|str|2.12.0
even-better-toml|tam|0.19.0
tauri-vscode|tau|0.2.1
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
vscode-icons|vsc|12.0.1
volar|Vue|1.0.13
vscode-typescript-vue-plugin|Vue|1.0.12
vscode-wakatime|Wak|22.1.0
material-theme|zhu|3.15.6

(5 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by gjsjohnmurray** [comment]
This is probably intentional, so you can switch elsewhere (e.g. to copy a URL to your clipboard) without the input field closing. Press Escape to close it if you change your mind about cloning.

**Comment by weartist** [comment]
> 这可能是有意为之，因此您可以在不关闭输入字段的情况下切换到其他地方（例如，将 URL 复制到剪贴板）。如果您改变对克隆的想法，请按 Esc 将其关闭。

thanks！
