### ISSUE TITLE
Dark V2 debug toolbar grey looks out of place

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169175]
Not sure if this was intentional or not but the debug toolbar grey seems to be lighter than everything:

![image](https://user-images.githubusercontent.com/2193314/207705975-505967ca-b54d-41a5-a727-9d8973f3fad7.png)

**Comment by daviddossett** [comment]
Looks like I had just missed overriding the defaults. Will be fixed via #169177
