### ISSUE TITLE
"Debug: Show Hover" does nothing when triggered from shortcut (but works with mouse)

### ISSUE THREAD

**Issue by jasonwilliams** [microsoft/vscode#169151]
Sometimes I leave the debugger running when editing code and making changes. The one thing which fails to work during this period is triggering hover from a keybinding (ctrl/cmd+k, ctrl/cmd + i). Whenever I trigger this over a red squiggly line nothing happens. I understand this is because the debugger overrides that keybinding when running but 90% of the time it's replaced with nothing.

Is it possible to fall back through to the normal hover action if im not on a line currently being inspected? This must be possible because mouse hover does exactly this.

This seems to be the UX with mouse hover:
1. When a breakpoint has triggered I get the debug info on hover.
2. When a breakpoint hasn't triggered the hover falls back to normal hover information

Triggering hover with keybindings:
1. When a breakpoint has triggered I get the debug info on hover.
2. When a breakpoint hasn't triggered nothing happens.

This issue is asking for the keyboard shortcut (ctrl/cmd+k, ctrl/cmd + i) to match up with the mouse hover.

**Comment by connor4312** [comment]
Holding `alt` while hovering in a debug session will have VS Code show the "non-debugger" hover. I think it's a bug/polish item that we should automatically fall back to that if evaluating the hovered expression in the debugger does not returning anything.

**Comment by roblourens** [comment]
Regarding the keybinding, there are two "Show hover" commands. "Debug: Show Hover" won't do anything when not at a breakpoint. You should set different keybindings, or use when clauses to run the right one, if that's what you are expecting.

**Comment by Viijay-Kr** [comment]
@connor4312 is this still considered to be a valid issue and work needs to be done ? 

I can open a PR for this if this is still legit

**Comment by jasonwilliams** [comment]
@Viijay-Kr I don't believe this issue has been addressed yet and is still valid

**Comment by Viijay-Kr** [comment]
@jasonwilliams Great , upon investigation I notice that the UX you've mentioned here 

> This seems to be the UX with mouse hover:
    When a breakpoint has triggered I get the debug info on hover.
    When a breakpoint hasn't triggered the hover falls back to normal hover information
doesn't seem to be the case. 

When I mouse over a line (containing squiggly expression/ any line for that matter) which is not at a break point nothing happens. I get normal hover information upon pressing `alt`
 
Unless I'm missing something or misunderstood the issue , I notice the behaviour is same for both keyboard and mouse commands. 
So both the actions yield nothing to me.

However , what @connor4312 and @roblourens mentioned sounds like a valid solution to the problem

**Comment by jasonwilliams** [comment]
I can’t reproduce it now but I’m sure in some cases it was showing the normal hover without needing to press Alt.

in response to @roblourens, yes that is true that new commands can be set but it’s quite un-ergonomic. 
sometimes I don’t know the debugger is running because I spend all day using it on and off. So now I have to thing which command to use for the same action. 
it also feels like broken UX when info about a symbol stops showing anything (not even a “no debug info here”) so this should be addressed regardless.
I do like @connor4312‘s suggestion of falling back to a normal hover if that’s possible as that would help with productivity, rather than pushing all your users to create workarounds.

**Comment by roblourens** [comment]
I also like connor's suggestion, that's why I left it open, the workaround is for before it gets fixed. You can have a single keyboard shortcut that runs a different command based on `"when": "inDebugMode"`

**Comment by jasonwilliams** [comment]
OK I can reproduce this now.

This is debugging VSCode itself. In this gif i am trying ctrl + K, ctrl + I (which usually reveals the hover). Nothing happens. But when I hover over with the mouse (I am not pressing `alt`) i get info.
![codeDebug](https://user-images.githubusercontent.com/936006/214162726-bcecd17d-221f-4eea-b20b-e4b5386d481e.gif)

**Comment by Viijay-Kr** [comment]
@jasonwilliams I too was able to reproduce it some time ago , I was working on the fix , hopefully will be able to submit a PR soon

**Comment by jasonwilliams** [comment]
Thank you for this @Viijay-Kr ill look forward to trying it out!

**Comment by amunger** [comment]
the hotkey still does not display hover for me while in debug mode:

```
2023-04-26 13:58:29.444 [info] [KeybindingService]: | Resolving ctrl+K,ctrl+I
2023-04-26 13:58:29.445 [info] [KeybindingService]: \ From 4 keybinding entries, matched editor.debug.action.showDebugHover, when: editorTextFocus && inDebugMode, source: built-in.
2023-04-26 13:58:29.446 [info] [KeybindingService]: + Invoking command editor.debug.action.showDebugHover.
2023-04-26 13:58:29.884 [info] [KeybindingService]: + Ignoring single modifier ctrl due to it being pressed together with other keys.
```

**Comment by roblourens** [comment]
verification-found means the issue can be reopened. This is working for me though, can you explain what you are debugging and hovering, or call me to show?

**Comment by roblourens** [comment]
Thanks @amunger, this still doesn't show the editor hover when the keybinding is used, when not at a breakpoint. cc @Viijay-Kr if you want to work on it again.

**Comment by Viijay-Kr** [comment]
Hey guys , Sure I can check . Can one of you attach a reproducible screen recording ? Does it not work under any specific circumstance ? 
Thanks

**Comment by roblourens** [comment]
Just these steps

- Start debugging, but _don't_ stop at any breakpoint
- Run the keybinding for the command
- The hover does not appear

**Comment by Viijay-Kr** [comment]
@roblourens Thanks . I will look into it this week
