### ISSUE TITLE
Understand image file links in markdown and move them when the files are moved

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169140]
I have this after pasting an image into a markdown doc:

![image](https://user-images.githubusercontent.com/2193314/207631274-412d4f30-8d73-463c-9019-b294455b715c.png)

When I drag and drop image.png into `images/`, it would be great if the markdown link would be updated, similar to TS imports being updated:

![image](https://user-images.githubusercontent.com/2193314/207631408-9da8a7a4-04b0-4e34-934f-14c198c09549.png)

**Comment by yume-chan** [comment]
`"markdown.updateLinksOnFileMove.enabled": "always"`

**Comment by mjbvz** [comment]
Yes that setting should work. Let me know if you run into any issues with it
