### ISSUE TITLE
Show feedback that extensions are processing a paste event

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169137]
Repro:

1. Set `"editor.experimental.pasteActions.enabled": true`
2. Print screen (I have 3 monitors such that the screenshot is 7200x2560px)
3. Paste in a markdown file, nothing happens for 2-4 seconds

**Comment by mjbvz** [comment]
@Tyriar Do you remember seeing this notification:

<img width="739" alt="Screenshot 2022-12-14 at 1 12 03 PM" src="https://user-images.githubusercontent.com/12821956/207715012-b652073f-8db5-4688-a3c5-8023509d06a9.png">


Do you perhaps have do not disturb mode enabled?

**Comment by Tyriar** [comment]
@mjbvz do not disturb is _not_ on and I don't see any notification when I try again just now

**Comment by mjbvz** [comment]
I haven't been able to reproduce this with a 8000x8000 image in the clipboard. After a small delay ([which we have configured](https://github.com/microsoft/vscode/blob/990a496681948ec274da5503b35cd49a7d06c0a2/src/vs/editor/contrib/copyPaste/browser/copyPasteController.ts#L202)), I always see the progress notification

It's possible that reading the clipboard event itself is taking a long time. @Tyriar If you are still seeing this problem, could you try profiling the window when this happens to see if this is the case? It would likely show up as a long running `paste` command

PS: Performance of large file paste should also be improved in general by #175809.
