### ISSUE TITLE
Having an invalid configuration in compound behaves randomly

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16916]
Verifying #16614

- Open launch.json in VS Code
- Put following compound configuration
```
"compounds": [
		{
			"name": "Compound1",
			"configurations": [
				"abcs"
			]
		}
	]
```
- Select above compound from the dropdown
- It runs Mocha unit tests

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/16615
