### ISSUE TITLE
Improve awareness of debug location in notebooks

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode#169190]
It's easy to lose track of the debugged cell in notebooks, especially when you've stepped into a cell which is different from the cell that is "running". Some improvements we could make:

- The "Go To" button should go to the cell at the top of the callstack, not the cell where the user clicked Run
- We should show overview ruler decorations for the top stackframe, as in the editor
- And overview ruler decorations for the currently running cell
- And for breakpoints (behind a setting)

cc @kieferrm

**Comment by Mohammedalanizi92** [comment]
> It's easy to lose track of the debugged cell in notebooks, especially when you've stepped into a cell which is different from the cell that is "running". Some improvements we could make:
> 
> * The "Go To" button should go to the cell at the top of the callstack, not the cell where the user clicked Run
> * We should show overview ruler decorations for the top stackframe, as in the editor
> 
> cc @kieferrm

**Comment by roblourens** [comment]
To verify, just try everything listed at the top.

For 
> the cell at the top of the callstack, not the cell where the user clicked Run

I mean, have two cells, like

```
def foo():
    print('hello')
```

and a second cell that calls `foo()`. Set a breakpoint in the function definition, click run on the second cell, and make sure "Go To" goes to that first cell where the instruction pointer is.
