### ISSUE TITLE
Support specifying where images are pasted in markdown extension

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169139]
Set `"editor.experimental.pasteActions.enabled": true` and paste an image into a markdown file, it's always put into the same folder as the file. I want it to be put into a sub-folder of the current file's folder.

Here are Obsidian's options who I'm sure have thought a lot about this:

![image](https://user-images.githubusercontent.com/2193314/207630879-353b4cfd-f0bf-4fb1-871e-e328d57de397.png)
![image](https://user-images.githubusercontent.com/2193314/207630906-639045de-86e0-44ef-ba35-22a5c884addc.png)

This is one of the gaps I experienced when moving from Obsidian to VS Code for note taking.

**Comment by mjbvz** [comment]
This fall under #157043 (which will also apply to paste)
