### ISSUE TITLE
Quick fix light bulb

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#16911]
- VSCode Version: 1.8.x

Now that we show the quick fix light bulb in the gutter it would make sense to show it as soon as an fixable error on the line exists.

**Comment by jrieken** [comment]
@dbaeumer You mean when the cursor is on that line/word?

**Comment by dbaeumer** [comment]
Yes, when the cursor is on that line.

**Comment by jrieken** [comment]
I was waiting for that: https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/quickFixModel.ts#L80

**Comment by jrieken** [comment]
@bgashler1 Can you create a second light bulb icon to differentiate the cases in which a code action is for an error/warning or a just for a word. Basically, code 'quick fix' vs 'refactoring'?  The code and css is already prepared for this, see the selectors with [`...[data-severity="high"]`](https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/quickFix/browser/lightBulbWidget.css#L24)

**Comment by bgashler1** [comment]
@jrieken are we sure we need separate icons?  In Visual Studio, there is only [one light bulb icon](https://docs.microsoft.com/en-us/visualstudio/extensibility/walkthrough-displaying-light-bulb-suggestions) for both refactoring and other fixes.

**Comment by jrieken** [comment]
Unsure - I have seen this in IntelliJ and liked it

**Comment by bgashler1** [comment]
@jrieken here's what this might look like.

![lightbulb-code-action](https://cloud.githubusercontent.com/assets/11839736/22009049/472a7146-dc35-11e6-98a6-e783bdc83656.gif)

Assume that the green top lightbulb of fixing a missing semi-colon was a quick fix (no refactoring).  Whereas, assume the red suggestion would suggest something like adding the missing variable to the end of the signature (refactoring).  (i.e. ignore the code and just pay attention to the visual difference of these two lightbulbs).

**Comment by bgashler1** [comment]
Personally, it seems weird to me to have two different light bulb icons.  Just my two cents.  It feels almost like it's duplicating information presented in the squiggles, but maybe I'm missing how it could tell something the squiggles can't.

**Comment by jrieken** [comment]
Yeah, now that I see it I am not liking it that much.

**Comment by jrieken** [comment]
We won't do another icon. This issue is resolved then

**Comment by riclf** [comment]
Frankly, I really like to see an upgrade that allows me to Turn Off the yellow bulb. It is a pain.
