### ISSUE TITLE
File changes not detected on workspace located on non-system drive

### ISSUE THREAD

**Issue by realtux** [microsoft/vscode#169155]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.0
- OS Version: Xubuntu 22.04

Steps to Reproduce:

1. Create new git repo on ext4 drive
2. Create new git repo on xfs drive
3. Save file on ext4 drive's repo and note vscode picks up the changes on save
4. Save file on xfs drive's repo and note vscode does not pick up any changes until the refresh button in git is manually clicked

In this demonstration, the top part of the screen is an xfs ssd drive acting as a storage drive mounted to `/mnt/storage` and the project folder is in there. The bottom part of the screen is an ext4 m.2 drive which is also the system drive mounted at `/` and the open project is located at `/home/brian/osxcross`.

![Peek 2022-12-14 11-18](https://user-images.githubusercontent.com/4989650/207664620-16bbeab4-6858-47fb-8089-3daf3adc93f8.gif)

I was hesitant to file a bug because I was certain this was a problem with an older OS and a broken environment having upgraded Xubuntu several times over the years. However, this is now on a fresh install. If you're wondering why I'm manually doing File -> Save, it's because I had created a workaround by combining save file with git refresh binded to ctrl+s.

**Comment by lszomoru** [comment]
@realtux, thank you very much for filing the issue. The refresh operation of the "Source Control" view is driven by file-system events so what I am suspecting is that for some reason the file-system even is not getting triggered when using the xfs ssd drive. Could you please try the following steps:
1. Start VS Code and open the folder/workspace that contains the git repository
2. Open the command palette and invoke the "Development: Set Log Level..." command
3. Scroll down to the bottom and pick the "Git" extension, and se the log level to "trace"
4. Also enable logging for file-system events as described in [this wiki](https://github.com/microsoft/vscode/wiki/File-Watcher-Issues#logging-local).
5. No make a change to a file and go to File -> Save
6. Share the contents of the [git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window)
7. Share the console logs that were generated by the file watcher

**Comment by realtux** [comment]
I have some additional information on this issue. I decided to migrate my information and format my xfs drive as ext4 and then restore the data to its original location. To my surprise, this **did not** resolve the issue. I redid the test from above where everything is identical exception the location of the code. I'm starting to wonder if VS Code won't watch for file changes on a drive other than the system one where it is installed. I'm going to update the title to reflect that this is not an xfs issue anymore.

**Comment by lszomoru** [comment]
> I'm starting to wonder if VS Code won't watch for file changes on a drive other than the system one where it is installed. I'm going to update the title to reflect that this is not an xfs issue anymore.

I do not believe that this is the case but it seems extremely weird that for one of the disks, no file-system events are being generated when you are making changes to the files. I am adding @bpasero to advise on how to investigate further as this seems like an issue related to file-system events and not per se.

**Comment by realtux** [comment]
I just resolved this by changing the ownership of the mount point for my second drive from `root` to my own user `brian`. I don't know why this fixes it since `brian` has full permissions to everything on the drive.

I don't know if this is a bug with VS Code or a dependency that deals with file watching.

**Comment by bpasero** [comment]
We support file watching on drives, but it is possible that the file system on the drive is unsupported. We use this file watcher, maybe you can see to reproduce and report upstream?

https://github.com/parcel-bundler/watcher

**Comment by realtux** [comment]
Thanks for the reply, I will do further investigation and report findings to the appropriate place. This likely isn't a bug with VS Code itself, so I'll try to run this down by experimenting with the file watcher. Feel free to close if that seems appropriate. Thank you.
