### ISSUE TITLE
Feature Request: Filter Problems from hover

### ISSUE THREAD

**Issue by wesbos** [microsoft/vscode#169179]
As someone whos code is full of problems, I'd like to be able to filter which problems show up on hover.

There are many ways to denote errors in VS Code - problems tab, red squiggles, Error Lens extension...

Both the problems tab, and the Error Lens extension allow you to pass a glob or regex to filter out errors, but there is no functionality like this for the hover panel.

<img width="1043" alt="Screenshot 2022-12-14 at 3 40 01 PM" src="https://user-images.githubusercontent.com/176013/207709155-0ec0fb8b-e3f7-4fda-a3d2-3c737e513d4e.png">

In the above example, I know there is a spelling mistake from the short underline under the first letter, and I know the variable is unused because it's greyed out. Not a problem. I'd love to be able to filter those out with `editor.hover.exclude` array.

## Examples

Error Lens:

<img width="439" alt="Screenshot 2022-12-14 at 3 45 29 PM" src="https://user-images.githubusercontent.com/176013/207710124-71df1397-60bb-46c4-9f49-9985901b0ba3.png">

Problems Tab:

<img width="944" alt="Screenshot 2022-12-14 at 3 47 43 PM" src="https://user-images.githubusercontent.com/176013/207710515-502c75fc-bac9-4bb1-a270-a1edf45c1241.png">

eh?eh?

**Comment by sandy081** [comment]
I see your correlation but unfortunately we do not want to filter any problems in the editor area and want extensions generating those errors to provide such. Hence closing this as wont fix.

**Comment by wesbos** [comment]
😢 I see your point, but in my case I don't want to turn off the TypeScript errors, I just want to filter them from showing up in the UI.
