### ISSUE TITLE
Cursor animation is on by default and cannot be turned off

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169171]
Probably caused by https://github.com/microsoft/vscode/pull/169113

Cursor animation is turned on in `main` regardless of the value of `editor.cursorSmoothCaretAnimation`

**Comment by ivanvoznyakovsky** [comment]
confirming the bug. partially solved by setting `cursorSmoothCaretAnimation` to `explicit`

**Comment by alexdima** [comment]
Sorry about this, working on a fix!

**Comment by pugson** [comment]
as a temporary workaround you can inject this style with devtools to get rid of the animation:
```
.cursor { transition: none !important }
```
