### ISSUE TITLE
Walkthrough page titles should be specific to the open walkthrough

### ISSUE THREAD

**Issue by bhavyaus** [microsoft/vscode#169163]
Walkthrough page titles all read "Get Started". We should update it to be specific to the extension/content being displayed. 
Currently, if users have multiple walkthrough pages open, they are required click into each page to determine the walkthrough content. 

<img width="801" alt="image" src="https://user-images.githubusercontent.com/25044782/207681676-ad6ba2ba-a004-4103-b41a-0c3145eafebe.png">

**Comment by ivikash** [comment]
Hello Team, could you provide an update on this issue? Additionally, is it possible to update the title from "Welcome" to something else for a specific extension?

![Screenshot 2024-06-11 at 1 03 28 PM](https://github.com/microsoft/vscode/assets/371007/8c8e83f8-46b9-47fc-9260-535a92115d4f)
