### ISSUE TITLE
In Integred Terminal, press Tab to next file, leaves blank space and traces

### ISSUE THREAD

**Issue by cwberick** [Microsoft/vscode#16914]
- VSCode Version: 1.7.2
- OS Version: Windows 10

Steps to Reproduce:

1.  Open terminal integred
2.  Press Tab many times to next files

See GIF:

![20161208_091540](https://cloud.githubusercontent.com/assets/5774595/21008143/89f5c4a8-bd27-11e6-9687-f2bfb727324f.gif)

**Comment by Tyriar** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14613

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.

**Comment by cwberick** [comment]
Ok, thanks!
