### ISSUE TITLE
Overwritting closing statement / braces

### ISSUE THREAD

**Issue by TheKnightCoder** [Microsoft/vscode#16915]
- VSCode Version: Code - Insiders 1.8.0-insider (a8d5b9281e2118c2a10098098ddaac949ce69fe0, 2016-12-06T07:11:10.946Z)
- OS Version: Windows_7
- Extensions:

Steps to Reproduce:

1. Type a " or ' or } or ) 
2. Type the same character before that character e.g. left arrow + "
(only occurs on closing)

I understand that is some cases this is a feature. But it is only a feature when VS code auto inserts the closing symbol, therefore it should only overwrite when a auto-insert occurs.

Overwriting closing statements when it was not supposed to has caused errors for me more than a few times. There is no reason for it to overwrite unless there was a auto-insert.

**Comment by phra** [comment]
yeah, i think so too.

**Comment by TheKnightCoder** [comment]
was anything done about this? or is there a way to disable bracket completion?

**Comment by TheKnightCoder** [comment]
Has this been fixed yet, literally the only thing I dislike about vscode

**Comment by JacksonKearl** [comment]
@TheKnightCoder this issue has come up a few times. I explain the difficulty of providing more correct behavior in the linked issue. If you have suggestions I'm all ears.
