### ISSUE TITLE
Renaming vars doesn't pick up variables in scope, inserts new variable names as invalid code after scope

### ISSUE THREAD

**Issue by jakehemmerle** [microsoft/vscode#169148]
Type: <b>Bug</b>

I am trying to refactor variables in my Rust code, and it does not pick up on the same named variables in the scope and it then inserts the new variable name and some stuff right after the scope ends. I have rust-analyzer installed but haven't had this issue before. My project compiles and builds and all other features (eg mousing over a subsequent use of a variable I want to rename shows the type, value etc of it) work as I expect

VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:37:54.581Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 4, 3|
|Memory (System)|64.00GB (8.79GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
project-manager|ale|12.7.0
jsdoc-generator|cry|1.1.1
vscode-markdownlint|Dav|0.48.1
gitlens|eam|13.1.1
copilot|Git|1.63.7601
rust-doc-viewer|JSc|3.0.4
rainbow-csv|mec|3.5.0
theme-monokai-pro-vscode|mon|1.2.0
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
hexeditor|ms-|1.9.9
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5788
rust-analyzer|rus|0.4.1319
even-better-toml|tam|0.19.0
vscode-lldb|vad|1.8.1
vim|vsc|1.24.3
markdown-all-in-one|yzh|3.5.0

(2 theme extensions excluded)

</details>

**Comment by mjbvz** [comment]
Please file this against the Rust extension
