### ISSUE TITLE
Switching back from custom to native title bar style has title bar rendering issues

### ISSUE THREAD

**Issue by sandy081** [Microsoft/vscode#16912]
Steps to Reproduce:

1.  Open VS Code with title bar style set to `custom`
2. Go to full screen mode
3. Change the style to `native`
4. Come out of full screen

See how title bar is rendered

![image](https://cloud.githubusercontent.com/assets/10746682/21007397/f46c17b4-bd3c-11e6-875e-68c97beabd07.png)

**Comment by bpasero** [comment]
Yeah, changing the title bar style needs a full restart and we should just prompt the user that a restart is required after changing this setting.

**Comment by bpasero** [comment]
No longer reproduces.

**Comment by roblourens** [comment]
Still reproes for me, without a full restart - 

![image](https://cloud.githubusercontent.com/assets/323878/22313783/36b17ea6-e313-11e6-8e8a-1b6d72b4c81e.png)

**Comment by bpasero** [comment]
@roblourens steps?

**Comment by roblourens** [comment]
Exactly @sandy081's original steps

**Comment by bpasero** [comment]
Got it, the steps to reproduce are not correct, I will fix them.

**Comment by bpasero** [comment]
Changing this option is now asking for a restart.
