### ISSUE TITLE
Maximize current file/tab/editor

### ISSUE THREAD

**Issue by dfroze** [microsoft/vscode#16927]
- VSCode Version: 1.7.2
- OS Version: Linux Mint

I've looked a bit but couldn't find a solution. Is there a way to toggle maximize (full screen) only the current tab/file? Even if there is split editor, it shouldn't display it, only the current file/tab.

Thanks

**Comment by bpasero** [comment]
@dfroze there is a new "Zen Mode" coming up which is maybe what you want? 
Can you try to reproduce with our nightly insider builds? You can give our preview releases a try from: http://code.visualstudio.com/Download#insiders

**Comment by dfroze** [comment]
Thank you @bpasero . I tried the insiders build:
Version 1.7.2
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0

But couldn't find the zen mode (not in the menu bar,  keyboard shortcuts conf or showCommands bar). And the full screen is the same as the release one.
Where can I find the nightly builds? Or where can I find the build you mentioned?

**Comment by bpasero** [comment]
@dfroze that is not the insiders build, it should be Version 1.8.0!

**Comment by alefragnani** [comment]
The **Zen Mode** will not maximize only the current file/tab but instead, the entire window with all groups/editors, which I prefer by the way  :smile: 

Maybe a setting to accomplish what @dfroze is asking?

**Comment by LiTiang** [comment]
what's @dfroze talk about is called maximize-panes in **_Atom_**,

this is so important that **_Eclipse_**, **_Sublime Text_** . . . also have this feature

i could not have this functionality when dev 😨

see how it work by [this](https://atom.io/packages/maximize-panes)

**Comment by danielrob** [comment]
Yeah the problem with zen mode is when switching application tabs, you can't toggle onto the zen mode on mac. I find this makes the feature basically unusable. I want Zen mode without fullscreen.

**Comment by mauro3** [comment]
Yes, this would be great to have.  One example when this would be useful: three editor panes open, then open the Settings.  Now the Settings are displayed in a completely unusable way (on my screen at least). 

Note, that this toggle and the zen mode toggle should operate independently.

**Comment by bpasero** [comment]
You can use this command:

![image](https://user-images.githubusercontent.com/900690/30249464-80ca80d6-963d-11e7-9d4d-8d715b18bf5d.png)

**Comment by PixelT** [comment]
+1 for this issue:
Atom -> https://github.com/santip/maximize-panes
SublimeText -> https://github.com/jisaacks/MaxPane

**Comment by tnhu** [comment]
+1
Brackets -> https://github.com/tnhu/brackets-maximize-editor

**Comment by tiagoaquino** [comment]
+1

**Comment by rdlaner** [comment]
+1!

**Comment by etlds** [comment]
+1

**Comment by mclang** [comment]
This is currently also my main one missing feature in VS Code, since I learned using "maximize panel" in tmux with `ctrl + <space> + z`

**Comment by Rosseyn** [comment]
@bpasero that's handy, but heavy-handed.. need to be able to restore layout afterwords.. do you know of a good way to at least un-maximize an editor group perhaps?

**Comment by bpasero** [comment]
@Rosseyn there is also:

![image](https://user-images.githubusercontent.com/900690/37016242-9246d0cc-210b-11e8-9f49-b71cdf2eecf8.png)

**Comment by ashlinchak** [comment]
+1

**Comment by Rosseyn** [comment]
That could definitely help!

**Comment by neo-anderson** [comment]
This is the main feature I'm missing in VS Code. In Atom, I can maximize the source markdown pane and then toggle between source and preview like it's a live wysiwyg preview. Scrolling stays in sync too.
In VSCode, I can't maximize the source pane. So, this doesn't work.

**Comment by utilityboy** [comment]
@bpasero, `Maximize Editor Group` + `Even Editor Group Widths` is a decent compromise as you suggested, with the caveat that it's not "togglable" since there's no context to latch onto.  See: #24163.  The result is you need to use different keystrokes to flip between the two.

**Comment by neminovno** [comment]
Maximize/restore by double click on file name in header would be great.

**Comment by TerraTech** [comment]
@neminovno @utilityboy As a relative newcomer to vscode from atom, I too was trying to figure out how to emulate atom's 'maximize-panes' behavior.  One of the first things I tried was to double click the tabbed filename to see if that would work.  Well it didn't, but from an intuition standpoint I believe that would be the best way to handle this needed feature/ability.

Using the command panel is all well in good, but for everyday usage behaviors like this (_maximize/restore panel size_) should be baked directly into the editor and in a clickable fashion.

**Comment by tbrunel** [comment]
Up?
Really need this features 🙌

**Comment by sammathu** [comment]
+1

**Comment by myfairsyer** [comment]
> IGNOREME:
I am commenting here so I can easily find this issue again in the future, [since I can't do that by subscribing alone](https://github.com/isaacs/github/issues/283).

**Comment by utilityboy** [comment]
This becomes even more important now that we have wonderful grid layouts to focus work.

**Comment by lijgame** [comment]
This is a killer feature for me as well!

**Comment by TheNorthman** [comment]
+1

**Comment by mliq** [comment]
This used to work for me just fine in VSCode using `View: Maximize Editor Group and Hide Sidebar`. On the latest versions, it does not: that command only works once when I trigger it, so I have to retrigger it if I change to a different editor group. 

Just a few months ago this worked great, I was able to toggle on this command once and it would keep maximizing whichever editor I made active until I triggered `Reset Editor Group Sizes`.

I miss this feature! Did grid view screw it up?

**Comment by derekalvarado** [comment]
I rarely ever worked with editors of even widths. Just not enough screen real estate. I loved that switching focus with Ctrl+1 Ctrl+2 Ctrl+3 would also maximize the selected editor. Now, those only give focus to the editor, without maximizing. 

My workaround is to assign a keyboard shortcut to "Maximize Editor Group", but still kind of annoyed that I need more keystrokes to get the same behavior. 

Perhaps a setting to "Maximize Editor Group On Focus"?

**Comment by misterbridge** [comment]
There's this one: https://marketplace.visualstudio.com/items?itemName=wonderful.maximize-panes
I'm not fully conviced as it kinda lags and completly hide other panes (not configurable) but it's a good start.

**Comment by Ridermansb** [comment]
Where is the ` Even Editor Group Widths` option?

I can't find it.

![screen shot 2018-08-02 at 13 42 52](https://user-images.githubusercontent.com/725337/43598062-39f34288-965a-11e8-896e-e1797604eecf.png)

![screen shot 2018-08-02 at 13 44 35](https://user-images.githubusercontent.com/725337/43598063-3a1aec02-965a-11e8-8b37-d5bf5714cbdf.png)

**Comment by zanza00** [comment]
Now is called `Reset Editor Group Size`

<img width="720" alt="image" src="https://user-images.githubusercontent.com/3732011/44082457-95596138-9fb1-11e8-9a35-2f13d611ac5a.png">

**Comment by sirius0xff** [comment]
Especially useful when doing file comparison

**Comment by ziomio** [comment]
I need this feature!

**Comment by oryandunn** [comment]
Another request for this feature. Miss it from Eclipse, Atom, etc.  A double click of a tab should maximize that tab, and another double click should restore it back to previous layout.

**Comment by eddiewang** [comment]
Would really love to see this feature happen!

**Comment by makstaks** [comment]
Example: 
iTerm2 
View > Maximize Active Pane

**Comment by utilityboy** [comment]
You can get fairly close to what iTerm offers with the following keybindings:

```
   {
        "key": "shift+cmd+enter",
        "command": "workbench.action.maximizeEditor",
    },
    {
        "key": "ctrl+shift+cmd+enter",
        "command": "workbench.action.evenEditorWidths",
    },
    {
        "key": "shift+cmd+enter",
        "command": "workbench.action.toggleMaximizedPanel",
        "when": "terminalFocus"
    },
```

**Comment by creal1976** [comment]
I will file charges of harrasment if you don't stop emailing me

Sent from my Verizon Wireless 4G LTE DROID


Brent Jubinville <notifications@github.com> wrote:


You can get fairly close to what iTerm offers with the following keybindings:

   {
        "key": "shift+cmd+enter",
        "command": "workbench.action.maximizeEditor",
    },
    {
        "key": "ctrl+shift+cmd+enter",
        "command": "workbench.action.evenEditorWidths",
    },
    {
        "key": "shift+cmd+enter",
        "command": "workbench.action.toggleMaximizedPanel",
        "when": "terminalFocus"
    },

**Comment by TerraTech** [comment]
@creal1976 I don't think robots have reached the level of sentience yet to be charged with harassment in a court of law.  However they are trainable, and you can toss them a bone by unsubscribing from this thread for which they would happily fetch a billion times over without delay.

_You are receiving this because you are subscribed to this thread._

**Comment by Argysh** [comment]
Is there a way to specify the width  `Maximize Editor Group` should maximize to?
I usually have two groups which I'd like to maximize just to my line width.

**Comment by utilityboy** [comment]
@Argysh, there is no way to do this.  It's a maximize which in VS Code takes up about 95% of the main editor window

**Comment by DavidBabel** [comment]
I had this issue too and it bored me.
I include a fix in this extension i made : https://marketplace.visualstudio.com/items?itemName=davidbabel.Clever

**Comment by zk-g** [comment]
+1

**Comment by BMourelo** [comment]
+1

**Comment by rroblik** [comment]
Double click should maxi/minimize the clicked tab, just like other IDE behavior (my oldish netbeans did it !)

**Comment by libnux** [comment]
> Double click should maxi/minimize the clicked tab, just like other IDE behavior (my oldish netbeans did it !)

This is a very useful feature. Eclipse and JetBrains' IDEs all support it.

**Comment by tedz2usa** [comment]
I'd really like to see this feature implemented. Can we bump this issue again?

**Comment by fatihacet** [comment]
I was looking for something iTerm2 does when pressed `Cmd+Shift+Enter`. Since this is not supported yet, this is the best solution to improve my workflow. Hope this helps to anyone. Add these to `keybindings.json`. Feel free to change the key shortcuts.

```js
  {
    "key": "cmd+j cmd+j",
    "command": "workbench.action.toggleMaximizedPanel"
  },
  {
    "key": "cmd+f cmd+f",
    "command": "workbench.action.maximizeEditor",
    "when": "editorTextFocus"
  },
  {
    "key": "cmd+r cmd+r",
    "command": "workbench.action.evenEditorWidths",
    "when": "editorTextFocus"
  }
```

### `workbench.action.toggleMaximizedPanel` 

This is extremely useful to see search results in a bigger panel. Before this one, I was manually resizing sidebar back and forth.

![_vscode_cmd+j](https://user-images.githubusercontent.com/712419/59474974-54531a80-8e49-11e9-957b-12e78e85f5be.gif)

### `workbench.action.maximizeEditor`

This doesn't make it fullscreen but better than nothing. This will also hide the sidebar, which is good for more room.

![_vscode_cmd+f](https://user-images.githubusercontent.com/712419/59475050-c6c3fa80-8e49-11e9-8d0a-55c34235b59d.gif)


### `workbench.action.evenEditorWidths`

After having the command above, I wanted to find a way to revert it back to the original state. This will make panes even size, in other words, won't preserve the previous width. Not a big deal tho.

![_vscode_cmd+r](https://user-images.githubusercontent.com/712419/59475104-0e4a8680-8e4a-11e9-820e-d5892803cd4b.gif)

**Comment by AmauryOrtega** [comment]
thanks! @fatihacet

**Comment by georgefst** [comment]
https://github.com/microsoft/vscode/issues/72968#issuecomment-519907919

**Comment by gcpdev** [comment]
> Another request for this feature. Miss it from Eclipse, Atom, etc. A double click of a tab should maximize that tab, and another double click should restore it back to previous layout. This should also work for any other pane, like the terminal pane.



> Double click should maxi/minimize the clicked tab, just like other IDE behavior (my oldish netbeans did it !)

Correct. Intellij also have this feature, and I *really* miss it while working with VSCode (at least 3x a day :( ).

**Comment by misterbridge** [comment]
This should be closed no ?
As georgefst mentionned, the feature is out since a little while now:
> [#72968 (comment)](https://github.com/microsoft/vscode/issues/72968#issuecomment-519907919)

Just bind your key and you're good to go
```json
{
    "key": "ctrl+shift+x",
    "command": "workbench.action.toggleEditorWidths"
}
```

**Comment by cb109** [comment]
@misterbridge Thank you for mentioning this, best solution now that is out. It still bothers me that there is no way to expand to a real full screen or to be able to configure the percentage of expansion. Hopefully this will be added as well in a future update.

**Comment by sleighsoft** [comment]
+1 for toggleMaximizedEditor !

**Comment by KarenJohnstone** [comment]
+1 
_(love if could double click the editor tab name, as that's what I did in Eclipse)_

**Comment by Machiaweliczny** [comment]
I just want it to work the same as in iTerm2, so "cmd+shift+enter" is toggle fullscreen. Don't make me learn vim :/

**Comment by KKKIIO** [comment]
Can we have "maximize editor and hide every thing except editor"? Not just hide the sider, but the panel.

**Comment by macintacos** [comment]
FWIW, I set up the following (heavy-handed) command using [the multi-command extension](https://github.com/ryuta46/vscode-multi-command):

```
  "multiCommand.commands": [
    {
      "command": "multiCommand.closePanelAndSidebarAndOtherEditors",
      "sequence": [
        "workbench.action.closePanel",
        "workbench.action.toggleSidebarVisibility",
        "workbench.action.closeEditorsInOtherGroups"
      ]
    },
...
```

And then set this new "closePanelAndSidebarAndOtherEditors" command to the following:

```
  {
    "command": "multiCommand.closePanelAndSidebarAndOtherEditors",
    "key": "cmd+w m",
    "when": "sideBarVisible"
  },
```

Which is good enough for me. Would still love a single command that does this though!

**Comment by sandric** [comment]
I honestly don't get why `workbench.action.maximizeEditor` is not maximizing current editor full width, this is the porpuse of `maximizeEditor`, no? Is there some way to reduce this minimum width of editor then, even if this is api call - I have my own extension and can make my own function, I just don't see how to change current editor width from api docs?

**Comment by telmodias** [comment]
I'm currently using the "View: Toggle Editor Groups Sizes" and it has the most similar behaviour to MaxPane that I have found so far.

**Comment by GiorgioMartini** [comment]
Please implement a shortcut to just see ONE tab in fullscreen... then toggle to see all the other tabs and other windows.. zen mode just makes fullscreen the whole editor and keeps the tabs. We want just one tab to be visible and fulscreen.

**Comment by sandric** [comment]
@telmodias well its not maximizing current editor group, hiding second, it makes it like 80/20% right?

Where is this sort of `min-width` variable for editor group is stored? Can I overwrite it in my extension?

**Comment by telmodias** [comment]
@sandric I have not found anything else yet related to this subject, I'm happy for now with this use case although I recognise that the Sublime MaxPane plugin is a better experience. If you find anything else about this topic, I would appreciate if you could post here.

**Comment by sandric** [comment]
I looked a bit, it turns out its that line, so its always minimum 220px apparently: 

https://github.com/microsoft/vscode/blob/f8432f8d9c1b1edd48e2b97d554e343f008e215c/src/vs/workbench/browser/parts/editor/editor.ts#L24

@joaomoreno is there any chance that can be moved to settings in future sprints, since many people asking about it here? Say `Editor min width`, `Editor min height`, `Editor max width` and `Editor max height` wdyt?

**Comment by joaomoreno** [comment]
-> @bpasero

**Comment by bpasero** [comment]
I think these values are carefully picked to leave a minimum of space to be able to grab the tab and/or to see the editor contents:

![image](https://user-images.githubusercontent.com/900690/79981901-bb981d00-84a5-11ea-9716-a55e15cccb27.png)

vs

![image](https://user-images.githubusercontent.com/900690/79981944-cb176600-84a5-11ea-8860-c077639333c2.png)

**Comment by sandric** [comment]
@bpasero those can be defaults, but why not give ability to change this if wanted to end users? Because of this there's currently no way to temporarily hide editor group. Say I want to maximize (100%) current editor group, then unmaximize it preserving all editors in editor group that was not visible, like described in this issue, is impossible now, right?

**Comment by bpasero** [comment]
If we end up supporting hidden editor groups as a solution to this issue then I would rather not introduce a setting for the minimal editor size. But if enough people want to configure the minimal editor size independent from this issue then I suggest to extract that into a separate issue.

**Comment by sandric** [comment]
@bpasero sure, maximized should make all other hidden. I'm actually for making editor groups hideable/visible as solution to this, I just looked what the problem currently was, I was hoping to somehow overcome this from extension, but saw hardcoded dimension. Is there near future plans to add hiding for editor groups (sorry if it was already written in discussion earlier) ?

**Comment by vijinpaulraj** [comment]
It's disappointing that such an awesome IDE doesn't have this basic feature 😞

**Comment by lukebrowell** [comment]
Bump - I want to be able to use a markdown preview panel, full screen for presenting during live coding.

**Comment by msftwindowslinux** [comment]
Hopefully I didn't miss any mention of this already, but it would be nice if there were a way for "toggling" maximization to actually preserve the original window layout when un-maximized.

Personally I'm not as bothered by the min-width display of other editors, though it is distracting. However I can't stand that the only way to revert is via "equal widths" which is emphatically not the layout I had before.

**Comment by lehoangharry** [comment]
> You can use this command to make the active editor maximum width and hide the side bar:
> 
> ![image](https://user-images.githubusercontent.com/900690/30249464-80ca80d6-963d-11e7-9d4d-8d715b18bf5d.png)

This is an amazing solution. In case you wonder how to reset the editor group to the default size, there is a reset command for that.

![image](https://user-images.githubusercontent.com/69065646/100384109-5bde9300-2fed-11eb-8ba6-80ea9c3354c4.png)

**Comment by vijinpaulraj** [comment]
@lehoangharry The catch is, it won't hide the terminal editor group!

![image](https://user-images.githubusercontent.com/14046103/100388614-fe653900-3022-11eb-9b49-d32bdc61efbd.png)

**Comment by lehoangharry** [comment]
@vijinpaulraj You can do that with `Command + J` or `Control + ``

**Comment by klisorena** [comment]
![VSCode](https://user-images.githubusercontent.com/61342995/108586370-edf5fd80-7388-11eb-910c-ed2c91b4c3bc.PNG)
Hi guys,

I'm using version 1.53.2 and there is a feature called 'Maximize Panel Size" on the terminal (not sure if it was always there on other versions). Is it possible to have this on the editor groups/splits?

This would very handy for small screen devices or when you want to temporarily focus on specific group/split/file, and then return to your original splits when you're done.

**Comment by ctf0** [comment]
@klisorena there is already `workbench.action.toggleEditorWidths` we just need to add an icon for it in the title bar

**Comment by klisorena** [comment]
@ctf0 it is not quite the same. the toggleeditorwidths only maximizes the tab to certain width. The 'maximize panel size' uses the all the space, including the other groups.

**Comment by ctf0** [comment]
i saw a setting that can change how small the group could be minimized but cant remember what was its name or if it even still there anymore

**Comment by DavidBabel** [comment]
The extension "Clever vscode" actually does that : https://marketplace.visualstudio.com/items?itemName=davidbabel.Clever#toggle-maximise-current-editor

I made it for myself but it can help others.

Here is the bindings to add : 
```json
{
  "key": "shift+ctrl+enter",
  "mac": "shift+cmd+enter",
  "command": "clever.maximize.toggleWithSidebar",
  "when": "editorTextFocus"
}
```

**Comment by ashlinchak** [comment]
Thank you @DavidBabel for your extension. But it does actually hiding the activity bar and maximizes the current tab which could be accomplished by combinations of 2 shortcuts or creating a custom one shortcut. Your extension doesn't hide completely the splitted editors, also it's not working with opened terminal/debug panel.

**Comment by DavidBabel** [comment]
I get your point, yes the behaviour is slightly different.

**Comment by chipbite** [comment]
Another issue raised (and closed) for the same thing, it seems: #8989

**Comment by kopili** [comment]
This is sooo sad ... I can say this is the only reason I still totally prefer IntelliJ to vs code - just double click and maximize the editor - what's so difficult?!? The zen mode is just not the same - you can't see the other tabs, for me it is totally confusing and I don't like it at all - maximize window in IntelliJ is so simple and effective and yet - still no one has implemented it in vs code ...

**Comment by technodrome** [comment]
VScode has many great features. Many things I love about it. But this really is sad. We see gazillion of other fancy hipster features (which nobody really needs that badly) being added left and right, but something so basic is missing. Two MIAs, together with clickable intellij-style 3-way merge. No, we have to use "workarounds", unmaintained or opinionated plugins and hacks. Because hitting 5 keys instead of one click surely is better, right? No, it isn't. This doesn't even come close to good UX in order to work semi-productively with tabs. Half-baked unfinished solution, any why? Nobody seems to know, nobody seems to care, nobody seems to react. 

Ticket open for 5 years. That speaks for itself. Volumes.

**Comment by rroblik** [comment]
@technodrome oh yeah so good summary! 
++1

**Comment by dandavison** [comment]
I think that `closeEditorsInOtherGroups` is very close to what people are asking for here.

The only problem that I'm aware of using that for this purpose it is that it sometimes asks me whether I want to save the changes that I made to a file, when really I just want to "remove the split" or "maximize the pane" and not think about whether I've got unsaved changes in that editor.

**Comment by DovRine** [comment]
+1

**Comment by whcjimmy** [comment]
+1

**Comment by ElSuture** [comment]
+1

**Comment by Hyperspaceru** [comment]
It would be convenient as it was done in adobe premiere pro, for example, by pressing "~" the active tab opens to full screen (any tab be that editor or terminal window), pressing it again returns everything back. Something like a zen mod, but only for one tab and the general layout of the tabs does not change

**Comment by Sh1ken** [comment]
> Something like a zen mod, but only for one tab and the general layout of the tabs does not change

If you meant "does not change" after untoggle, yes, exactly what I'm looking for. Is this still not a feature? :cry:

**Comment by ymentha14** [comment]
+1

**Comment by fatherofinvention** [comment]
+1

**Comment by smjure** [comment]
+1

**Comment by wayneseymour** [comment]
On my box, (latest mac, etc). I just double click on the editor tab and it toggles large, and doubling again toggles it back...in split screen mode (while not in zen mode).  
In zen mode a context menu pops.


https://user-images.githubusercontent.com/4858051/201111247-b87387a2-0c83-4590-9fce-2ee9cf47afb7.mov

**Comment by wayneseymour** [comment]
Maybe I added an extension, but I dont recall that.

**Comment by DavidOliver** [comment]
> I just double click on the editor tab and it toggles large

We're after a tab that takes up all of the window rather than most of it. :smile: 

> +1

If you could avoid replies consisting of only '+1' that would be great, as they result in less-than-useful notifications for the devs and those who are subscribed for updates. You can instead add reactions directly to the original post using the buttons underneath it. :+1:

**Comment by rameshrk** [comment]
+1

**Comment by kostia-lb** [comment]
Team, any progress on this?

**Comment by aimlessadam** [comment]
+1 please, pretty please

**Comment by aecspades** [comment]
This seems like a shocking omission for a code editor not to have this capability in 2023, and is probably one of the most basic and useful features that I use on a daily basis - for example in Eclipse v1 2004 this capability existed: double-clicking on an existing code tab maximizes the code tab and minimizes any ancillary tool window/view(s); another double-click "resets" the view/perspective(s) to how they were before the double click.  

Right now there is nothing in VSCode to match this capability - "Zen Mode" is somewhat similar but doesn't expand the editor horizontally to fill available space for some reason?!?  "Maximize Editor Group and Hide Sidebars" is better but doesn't minimize the Output/Problems panels at the bottom of the screen.  **Neither** action has a way to reset the windows to its state before the action, which is also important, and no key press combination is nearly as useful as a simple double-click (although having **both** double-click and a key press combination would be even better)

**Comment by kirilovb** [comment]
> This seems like a shocking omission for a code editor not to have this capability in 2023, and is probably one of the most basic and useful features that I use on a daily basis - for example in Eclipse v1 2004 this capability existed: double-clicking on an existing code tab maximizes the code tab and minimizes any ancillary tool window/view(s); another double-click "resets" the view/perspective(s) to how they were before the double click.
> 
> Right now there is nothing in VSCode to match this capability - "Zen Mode" is somewhat similar but doesn't expand the editor horizontally to fill available space for some reason?!? "Maximize Editor Group and Hide Sidebars" is better but doesn't minimize the Output/Problems panels at the bottom of the screen. **Neither** action has a way to reset the windows to its state before the action, which is also important, and no key press combination is nearly as useful as a simple double-click (although having **both** double-click and a key press combination would be even better)

Totally agree - 2023 and VSCode has no such useful tool - besides, from what I see in this thread, it's been at least 6 years since users started voted for such a feature ... I thought VSCode is being pushed in development to become one of the best IDEs, but apparently such a feature is not feasible for this editor ...

**Comment by dandavison** [comment]
> Neither action has a way to reset the windows to its state before the action, which is also important,

I agree with this also -- it would be fantastic if VSCode made it possible to navigate back to a previous window configuration after changing it.

> I thought VSCode is being pushed in development to become one of the best IDEs, but apparently such a feature is not feasible for this editor ...

Making snide comments and criticizing the developers isn't an appropriate or helpful contribution. Please don't do that -- we'd all like this issue to remain open and be resolved, but that will make it more likely to be closed.

**Comment by asumaran** [comment]
+1 can't believe we can't do this in VS Code. Makes me want to switch back to Sublime. Everyday. 😢

**Comment by kyochou** [comment]
+1

**Comment by astralaster** [comment]
+1

**Comment by kferrone** [comment]
Need it, desire it. Please make us happy with double click to get focused.

**Comment by apj68** [comment]
I've made several attempts over the past few years to swap from Emacs to VS Code and I always stumble onto something that puts in a wrinkle in my process.  I've been using VS Code for a week or so now (this time around) and this is my latest frustration.  If I get a window all configured like I want it then I lose the ability to focus on just a single editor unless I totally remake the window, it doesn't make sense.  Zen Mode and "focus" aren't much of a focus if you can't just look at the single editor you're in!  And this has been opened since 2016 (thanks, @dfroze, for getting the ball rolling).

I know it will take some time to adjust and VS Code is coming really well considering it is 30 years the younger.  I'm not trying to start an editor war but just saying that I thought this would be possible.

**Comment by apj68** [comment]
> @Rosseyn there is also:
> 
> ![image](https://user-images.githubusercontent.com/900690/37016242-9246d0cc-210b-11e8-9f49-b71cdf2eecf8.png)

For some reason I don't see that option (1.74.2/macOs).

**Comment by starball5** [comment]
Is this technically somewhat implemented? I just encountered [How do I stop VS Code from maximizing the size of an editor group when double-clicking one of its tabs' handles?](https://stackoverflow.com/q/76528677/11107541) and noticed that double clicking a tab causes the editor group for that tab to be maximized- not full-screened, but the editor group becomes as large as it can be, and all other editor groups become as small as they can be.

**Comment by apj68** [comment]
> ... causes the editor group for that tab to be maximized- not full-screened, but the editor group becomes as large as it can be, and all other editor groups become as small as they can be.

But I think what some of us are looking for is for the _editor_ (vs _editor group_) to be maximized (preferably, available through a keyboard shortcut).  And then unmaximizing would return to the original state of the entire window (editor group/s and layout).

**Comment by garretwilson** [comment]
When I'm in the terminal in VS Code and I want it bigger, on Windows I hit `Ctrl+Shift+J`, the terminal suddenly expands to fill the screen vertically. It would be nice if it would hide the sidebar, too, but hey, I can do that myself. I can't hit `Ctrl+B` because the terminal eats that character. So I can un-maximize the terminal with `Ctrl+Shift+J` again, switch back to the main window with `Ctrl+1`, hit `Ctrl+B` to minimize the sidebar, hit `Ctrl+~` to get back to the terminal, hit `Ctrl+Shift+J` again to maximize it … ah, there we go! Wasn't that easy? (not)

Even if I can live with `Ctrl+Shift+J` to sort-of mazimize the terminal when I'm there, what happens when I'm back in the editor? I can't hit `Ctrl+Shift+J`, because that will maximize the terminal (even though I'm in the editor). Maybe there is some other keystroke that maximizes the editor. I don't know. Why should I have to know? Why can't we just have one keypress that says "maximize this thing I'm in right now, whether it's the editor or the terminal"?

Eclipse has had this for literally decades. `Ctrl+M` just maximizes the thing where you are. `Ctrl+M` un-maximizes it. Is this really difficult for some people to understand?

Even simply improving `Ctrl+J` to detect if you're in the editor or the terminal would be a _huge_ improvement as far as I'm concerned, even though it's only halfway (actually about 40%) there.

**Comment by wuzhen0808** [comment]
+1

**Comment by benibenj** [comment]
In the newest Insider release we support maximizing editor groups. You can give it a try here: https://code.visualstudio.com/insiders/

The following ways can be used to maximize a group:
- Command Palette: Maximize Group (If at least two groups are available)
- Editor Title Menu: Maximize Group (If at least two groups are available)
- Double Click Tab: Requires `workbench.editor.doubleClickTabToToggleEditorGroupSizes: 'maximize'`

**Comment by kopili** [comment]
> In the newest Insider release we support maximizing editor groups. You can give it a try here: https://code.visualstudio.com/insiders/
> 
> The following ways can be used to maximize a group:
> 
> * Command Palette: Maximize Group (If at least two groups are available)
> * Editor Title Menu: Maximize Group (If at least two groups are available)
> * Double Click Tab: Requires `workbench.editor.doubleClickTabToToggleEditorGroupSizes: 'maximize'`

I'm sorry, but this is totally not the required feature - currently the tab only maximizes the group to the maximum window size. What we actually need is to maximize to the whole IDE size - which means to use the space of the explorer on the left, this utilizing the whole possible window size - you can try double clicking on a tab in IntelliJ IDEA and check what happens - it fully maximizes the window, thus allowing you to read the code better!

**Comment by starball5** [comment]
@benibenj thanks. I've written up some info and history in [my answer](https://stackoverflow.com/a/77356279/11107541) to [How can I temporarily maximize an editor group in VS Code?](https://stackoverflow.com/q/53925724/11107541)

@kopili see [In VS Code, how can I toggle maximization of the current workbench part / editor group?](https://stackoverflow.com/q/58885067/11107541).

**Comment by neo-anderson** [comment]
I didn’t get to test the feature yet, but if what @kopili  is saying is true, we should probably leave this issue open

**Comment by benibenj** [comment]
I created a new feature request for maximizing the editor across the workbench. I made a suggestion how this could work. Let me know if this is what you would expect the feature to do. Planning to add it in the next iteration. #196722
