### ISSUE TITLE
GitHubTokenExchangeError when trying to connect with Github via VS code (Error 403)

### ISSUE THREAD

**Issue by spaz88** [microsoft/vscode#169272]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.1
- OS Version: Windows 10 21H2

Steps to Reproduce:

1. Try to connect to Github via the profile menu
![Capture](https://user-images.githubusercontent.com/69171126/207893606-99a1d525-4140-46ad-85de-85598be8ee26.PNG)

2. Github pop up appear
![image](https://user-images.githubusercontent.com/69171126/207895000-d8fc0276-aa1a-425e-8d20-92dda75b8aa2.png)

3.Github login window opens
![image](https://user-images.githubusercontent.com/69171126/207895250-82bf6aeb-71ac-49a0-a31d-34f0c151a200.png)

4. Get GitHubTokenExchangeError
![image](https://user-images.githubusercontent.com/69171126/207895387-c4149ba2-98c3-4c60-bb31-7954951ae4b8.png)

5. Same thing if i try with "Different way"

I am working behind a corporate proxy that is properly configured in my gitconfig and my VS Code. After i made researches it may be my proxy that is blocking the reception of the token but there is no problem when doing push and pull requests. 

Full logs:
`2022-12-15 16:04:22.359 [info] Reading sessions from keychain...`
`2022-12-15 16:04:22.360 [info] Getting sessions for user:email...`
`2022-12-15 16:04:22.360 [info] Got 0 sessions for user:email...`
`2022-12-15 16:04:22.362 [info] Getting sessions for all scopes...`
`2022-12-15 16:04:22.362 [info] Got 0 sessions for ...`
`2022-12-15 16:04:27.051 [info] Getting sessions for read:user...`
`2022-12-15 16:04:27.051 [info] Got 0 sessions for read:user...`
`2022-12-15 16:04:27.152 [info] Getting sessions for read:user,repo,user:email,workflow...`
`2022-12-15 16:04:27.153 [info] Got 0 sessions for read:user,repo,user:email,workflow...`
`2022-12-15 16:04:27.427 [info] Getting sessions for read:user,repo,user:email...`
`2022-12-15 16:04:27.427 [info] Got 0 sessions for read:user,repo,user:email...`
`2022-12-15 16:04:31.697 [info] Getting sessions for read:user...`
`2022-12-15 16:04:31.697 [info] Got 0 sessions for read:user...`
`2022-12-15 16:05:03.334 [info] Logging in for the following scopes: read:user`
`2022-12-15 16:05:03.346 [info] Trying without local server... (read:user)`
`2022-12-15 16:06:05.219 [info] Exchanging code for token...`
`2022-12-15 16:06:05.289 [error] GitHubTokenExchangeError: <html><title>Cannot load block message</title>Status Code: 403'<br>MainBlockTemplate = 'index.html'<br>BlockMessage = 'authenticationrequired.html'</html>
    at t.GitHubServer.u (c:\Users\shby5041\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:2:1309015)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at c:\Users\shby5041\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\github-authentication\dist\extension.js:2:1304423`

Excuses me for any duplicates

**Comment by ttran0789** [comment]
Did you get this fixed?

**Comment by ttran0789** [comment]
@spaz88  I had a similar situation and had it fixed. I had a corporate proxy so it could never make the connection - ended up making the change in VS Code. Are you using a proxy?

**Comment by chrmarti** [comment]
Your proxy seems to require authentication. Support for that is currently incomplete. Please see https://github.com/microsoft/vscode/issues/12588#issuecomment-937324160. Tracking there, thanks.
