### ISSUE TITLE
Git - Options for discovering Git repositories outside the workspace 

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#169256]
The default value of the `git.autoRepositoryDetection` setting is `true` so Git repositories are discovered based on the workspace folders, and parent folders of the opened files. There are scenarios in which the Git repository root is outside the workspace folder. This is a valuable feature as it allows users to open a subfolder of a Git repository yet have the ability to perform source control operations. 

Unfortunately this behaviour also has some negative side-effects. The most extreme scenario is when one opens a loose file from the home folder, and there is a Git repository in the home directory. This can cause confusion as there are lots of changes in the "Source Control" view and discarding those changes results in data loss. 

//cc @digitarald

**Comment by digitarald** [comment]
Given the unexpected side effects but as some people might depend on it for quick edits, maybe this should be opt-in? Disabling the SCM view but showing an option to enable it (linking to the setting)?

**Comment by lszomoru** [comment]
Related - https://github.com/microsoft/vscode/pull/171617
