### ISSUE TITLE
Yaml auto-completed doesn't work. Can anybody answer my question?  What happen?

### ISSUE THREAD

**Issue by ln18520340281** [microsoft/vscode#169203]
![image](https://user-images.githubusercontent.com/86226705/207758463-eb6a18a9-1dff-47e2-9766-e39dca8eeebb.png)

**Comment by aeschli** [comment]
Autocomplete in YAML would be implemented in an extension. Do you use `redhat.vscode-yaml`. 
If yes, can you file the issue there? https://github.com/redhat-developer/vscode-yaml/issues 
Please provide a YAML sample that shows the problem.
