### ISSUE TITLE
Git - Command disablement

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#169293]
The Git extension contributes many commands, most of which spawn a process in which `git.exe` is being executed. Depending on the command, repository size, and the presence of git hooks some commands can take longer to execute. Historically, many of the commands can be initiated in quick succession and we have seen multiple cases that can cause unforeseen results:
* commit, and while commit is running stage/unstage file(s)
* commit, and while commit is running checkout a new branch

At the time when most of the git commands were created, "command enablement" was not available. This milestone we are exploring command enablement to disable most git commands while the following commands are running in order to avoid unforeseen results: `commit`, `checkout`, `pull`, `push`.

Based on user feedback we can tweak the list of commands. 

//cc @digitarald

**Comment by digitarald** [comment]
@lszomoru is the main issue side effects/race conditions from running commands out of order, or performance issues from sequencing too many commands?

**Comment by lszomoru** [comment]
> the main issue side effects/race conditions from running commands out of order,

☝🏻

**Comment by lszomoru** [comment]
This is currently available in VS Code Insiders. Give it a try and let me know if you see any issues. Thanks!
