### ISSUE TITLE
Url with more than ~3 lines won't be merged into one url

### ISSUE THREAD

**Issue by Greegko** [microsoft/vscode#169245]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.1 (Universal) Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
- OS Version: MacOS (Darwin arm64 21.6.0)

Steps to Reproduce:

1. Have an url in console which contains more lines.

Usecase:

I am building an application where I create automatic runnable tests in browser as well which can passed via URL the states, these are compressed and turned into base64 url correct format, tho always these are quite heavy, it would be nice if these urls could be clickable, and not copy paste these urls.

Example console output:
<img width="1502" alt="image" src="https://user-images.githubusercontent.com/7760839/207863271-5ff03108-9d10-4f54-86a5-ae508f1cd097.png">

**Comment by Tyriar** [comment]
We currently have a hard cap on URL length here: https://github.com/weartist/vscode/blob/af152735828478313cba04cb1b2edc0e344ff045/src/vs/workbench/contrib/terminal/browser/links/terminalUriLinkDetector.ts#L26-L27

This is done for performance reasons as it's relatively costly to detect links and it happens whenever you hover a new line in the terminal. Closing as designed for now but in the meantime you should be able to double click and drag to get the full URL
