### ISSUE TITLE
Terminal transparency (opacity) setting

### ISSUE THREAD

**Issue by emil14** [microsoft/vscode#169285]
Hello! I saw different ways to make thew whole VSCode window transparent but couldn't find the way to make the terminal (or at least the whole panel) window transparent. It would be super cool to have such ability in settings!

**Comment by emil14** [comment]
@Tyriar this is not a duplicate. Please read carefully 

> I saw different ways to make thew **whole VSCode window** transparent but couldn't find the way to make the **terminal**

**Comment by Tyriar** [comment]
@emil14 we don't support transparency anywhere so the ways you saw for the window are a hack, we won't support this in the terminal until we officially support it in the window.

**Comment by emil14** [comment]
@Tyriar  Is this a reason to close feature request?

**Comment by Tyriar** [comment]
Yes, because it's a duplicate of https://github.com/microsoft/vscode/issues/12578

**Comment by Tyriar** [comment]
See https://github.com/microsoft/vscode/issues/169285#issuecomment-1355094227 and https://github.com/microsoft/vscode/wiki/Issue-Grooming. There is no point tracking this for the terminal if it's not going to happen. We would only action this in the terminal if we supported it for the window.

**Comment by emil14** [comment]
Support for the whole window is harder to implement because that's something outside of CSS scope while it's possible to make terminal transparent using just CSS, that's why. These two features could have very different implementations. Also there could be people (like me) who is not interested in transparent window but instead in transparent terminal. Transparent terminals are pretty common things

**Comment by cjwijtmans** [comment]
what is the point of a transparent terminal of the window has no transparency? I do want the ability of transparency everywhere though.

**Comment by emil14** [comment]
the same usecase as with regular transparent terminal - ability to work in terminal and see the code (or the whole window) at the same time

**Comment by cjwijtmans** [comment]
> the same usecase as with regular transparent terminal - ability to work in terminal and see the code (or the whole window) at the same time

What are you talking about? There is nothing behind the terminal!

**Comment by Tyriar** [comment]
Locking this as the ask is to support something that doesn't work without hacking the sources of VS Code which is of course not a recommended or supported scenario.
