### ISSUE TITLE
context menu is automatically clickable.

### ISSUE THREAD

**Issue by icegood** [microsoft/vscode#169240]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
Version: 1.74.0
Commit: 5235c6bb189b60b01b1f49062f4ffa42384f8c91
Date: 2022-12-05T16:47:18.476Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.0-26-generic
Sandboxed: No

- OS Version: 
Linux 767b4f73c947 5.19.0-26-generic # 27-Ubuntu SMP PREEMPT_DYNAMIC Wed Nov 23 20:44:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Steps to Reproduce:
same as in https://github.com/microsoft/vscode/issues/65787. Automatically triggered menu item whatever appears under mouse pointer. In my case right click is done via 'two-finger click' on touchpad, therefore mouse release is not suitable. 
As workaroud for me now: window.titleBarStyle=custom, since in this case pointer appears exactly on border. 

Why don't vscode apply "unclickable" thick enough border instead?

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/113175
