### ISSUE TITLE
os display language is not detected in version 1.74.1

### ISSUE THREAD

**Issue by DomHel** [microsoft/vscode#169282]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.1 & 1.75.0
- OS Version: Win10_22H2_DE & Win11_22H2_DE

Steps to Reproduce:

1. Install VS Code 1.74.1 or 1.75.0 on german windows OS
2. Start VS Code
3. VS Code is not suggesting to install german language pack extension
4. even if you install the german language pack manualy, VS Code is not switching the language after a restart.

1. Install VS Code 1.74.0 on german windows os
2. start vs code
3. vs code suggests to install german language pack
4. accept and install german language pack
5. restart vs code
6. vs code is displayed in german
7. close vs code
8. install vs code 1.74.1
9. start vs code
10. vs code is displayed in english
11. vs code is not suggesting to install german language pack
12. restart vs code
13. vs code is still english

**Comment by TylerLeonhardt** [comment]
Yes unfortunately, this was because we had to make a tactical change here: https://github.com/microsoft/vscode/pull/169072

That causes the notification to no longer show up. We need to work on a better change.

**Comment by rzhao271** [comment]
Merging into https://github.com/microsoft/vscode/issues/169114
