### ISSUE TITLE
can't disable "mirage" brackets

### ISSUE THREAD

**Issue by AlexanderZagaynov** [microsoft/vscode#169224]
Type: <b>Bug</b>

Editor shows me brackets which I never typed, and I see nothing to disable that unwanted behaviour.

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:35:03.979Z)
OS version: Linux x64 5.14.0-210.el9.x86_64
Modes:
Sandboxed: No
Remote OS version: Darwin x64 22.1.0

![Screenshot from 2022-12-15 10-04-50](https://user-images.githubusercontent.com/7778414/207818290-eb0ad2d8-f5b2-480e-a79f-0d3854407abe.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10300T CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 0, 0|
|Memory (System)|62.46GB (56.55GB free)|
|Process Argv|--unity-launch --crash-reporter-id 13a895e6-9e45-4724-b8b7-b20188552956|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|

|Item|Value|
|---|---|
|Remote|SSH: 10.44.20.101|
|OS|Darwin x64 22.1.0|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|Memory (System)|32.00GB (0.12GB free)|
|VM|0%|
</details><details><summary>Extensions (107)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-openapi|42C|4.15.10
better-comments|aar|3.0.2
Bookmarks|ale|13.3.1
cucumberautocomplete|ale|2.15.2
devdocstab|Ana|1.0.1
gitstash|art|5.1.0
spellright|ban|3.0.104
vscode-tailwindcss|bra|0.9.1
solargraph|cas|0.24.0
gitignore|cod|0.9.0
doxdocgen|csc|1.4.0
dart-code|Dar|3.55.20221130
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.3.0
i3|dca|0.0.1
EditorConfig|Edi|0.16.4
vscode-diff|fab|1.4.2
vscode-firefox-debug|fir|2.9.8
foam-vscode|foa|0.20.2
remotehub|Git|0.49.2022121401
vscode-pull-request-github|Git|0.56.0
go|gol|0.36.0
rbs-syntax|Gra|0.3.0
gc-excelviewer|Gra|4.2.56
vscode-systemd-support|han|1.0.1
terraform|has|2.25.1
output-colorizer|IBM|0.1.2
openvpn|idl|0.2.3
prettier-sql-vscode|inf|1.5.0
cmake-language-support-vscode|jos|0.0.7
eml|lei|0.4.0
code-coverage|mar|1.8.6
code-groovy|mar|0.1.2
frostring|Mas|0.1.0
rainbow-csv|mec|3.5.0
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
file-downloader|min|1.0.12
mindaro|min|1.0.120221201
mongodb-vscode|mon|0.9.5
language-gettext|mro|0.2.2
vscode-azureresourcegroups|ms-|0.5.6
vscode-service-fabric-reliable-services|ms-|0.1.6
csharp|ms-|1.25.2
vscode-dotnet-runtime|ms-|1.6.0
vscode-aks-tools|ms-|1.3.7
vscode-kubernetes-tools|ms-|1.3.11
vscode-postgresql|ms-|0.3.0
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2023.1.1003441034
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.268.0
remote-ssh|ms-|0.95.2022121315
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
azure-account|ms-|0.11.2
azure-repos|ms-|0.25.2022121301
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.7
cpptools-extension-pack|ms-|1.3.0
hexeditor|ms-|1.9.9
makefile-tools|ms-|0.6.0
remote-explorer|ms-|0.1.2022121209
remote-repositories|ms-|0.26.0
vsliveshare|ms-|1.0.5788
sqltools|mtx|0.26.0
jsflowchart|MUL|0.1.6
vscode-paste-image|mus|1.0.4
back-n-forth|nic|3.1.1
vscode-groovy-lint|Nic|2.0.0
vscode-gem-lens|nin|0.3.2
vetur|oct|0.36.1
indent-rainbow|ode|8.3.1
ngrok-for-vscode|phi|1.10.0
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-extension-bpmn-editor|red|0.25.0
vscode-extension-dmn-editor|red|0.25.0
vscode-extension-red-hat-business-automation-bundle|red|0.25.0
vscode-xml|red|0.22.0
vscode-yaml|red|1.10.1
vscode-syntax-tree|rub|0.5.1
rust-analyzer|rus|0.3.1317
jinjahtml|sam|0.19.0
jenkinsfile-support|sec|0.1.0
gemfile-lock-highlight|sev|1.0.1
markdown-preview-enhanced|shd|0.6.5
slim|sia|0.1.2
prettier-vscode|Sim|2.0.7
markdown-memo|svs|0.3.19
sass-indented|syl|1.8.23
email-viewer|Tom|5.0.0
vscode-mermaid-editor|tom|0.17.1
cron-explained|tum|1.3.1
cmake|twx|0.0.17
haml|vay|1.0.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-icons|vsc|12.0.1
gitblame|wad|10.0.0
vscode-ruby|win|0.28.0
markdown-all-in-one|yzh|3.5.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by hediet** [comment]
Can you share the text? Otherwise it will be hard to reproduce.

**Comment by AlexanderZagaynov** [comment]
I tried with the fresh VS Code version - problem seems to be gone. Thank you!
