### ISSUE TITLE
No html Preview 

### ISSUE THREAD

**Issue by StanislavVasyukov** [microsoft/vscode#169259]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 
arch linux
Steps to Reproduce:

1. load vscode
2. open html file. there is no preview html button in the right corner.

![Screenshot_20221215_150345](https://user-images.githubusercontent.com/114884360/207882458-14472e55-363d-45c5-8911-018aad6ff4ca.png)

**Comment by nightboard** [comment]
@StanislavVasyukov  I think `vscode` don't have built-in support for HTML preview but you can look at different extensions that are available.

**Comment by aeschli** [comment]
You need to install the `Live Preview` extension (ms-vscode.live-server)
