### ISSUE TITLE
`standaloneTheme.defines` Always return false.

### ISSUE THREAD

**Issue by Aaaaash** [microsoft/vscode#169220]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Monaco Editor
- OS Version: 

Steps to Reproduce:

The `standaloneTheme.defines` method always return false.

https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/browser/standaloneThemeService.ts#L115-L117

```typescript
public defines(colorId: ColorIdentifier): boolean {
    return Object.prototype.hasOwnProperty.call(this.getColors(), colorId);
}
```
https://github.com/microsoft/vscode/blob/main/src/vs/editor/standalone/browser/standaloneThemeService.ts#L75

```typescript
private getColors(): Map<string, Color> {
    // ...
}
```
Because `this.getColors()` return type is a `Map`, so we should use `this.getColors().has(colorId)` in here.

**Comment by TylerLeonhardt** [comment]
@joaomoreno How can I verify this?

**Comment by aeschli** [comment]
I think only in code:
```
	public defines(colorId: ColorIdentifier): boolean {
		return this.getColors().has(colorId);
	}
```
