### ISSUE TITLE
Monaco Editor: `languageRegistry._registerLanguage` method is called too many times

### ISSUE THREAD

**Issue by Aaaaash** [microsoft/vscode#169268]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  Monaco Editor
- OS Version: macOS 13.0 (22A380)

Steps to Reproduce:
> This problem only exists in Monaco Editor

1. Run `npm run simpleserver` in the [Monaco Editor](https://github.com/microsoft/monaco-editor)
2. Add some logs in `src/vs/editor/common/services/languagesRegistry.ts#_registerLanguage` in vscode.
3. Open any Monaco editor test page.
4. View the output of the console，each call to `EditorModesRegistry.registerLanguage` will re-register all registered languages.

<img width="763" alt="image" src="https://user-images.githubusercontent.com/17701805/207886171-7dd9a271-2605-43cc-adf8-9b9b34a42c86.png">

**Comment by hediet** [comment]
Can you look into why this is the case?

**Comment by Aaaaash** [comment]
> Can you look into why this is the case, maybe even providing a PR?

Sorry for the late reply, I would be happy to submit a PR.
