### ISSUE TITLE
DefineKeybindingWidget needs to extend from FloatinClickWidget

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16923]
https://github.com/Microsoft/vscode/blob/master/src/vs/editor/contrib/defineKeybinding/browser/defineKeybinding.ts#L301

FYI @sandy081

**Comment by sandy081** [comment]
I have it in my TODO. But thanks for filing this which is better to track.

**Comment by isidorn** [comment]
Thus assigning to you, feel free to asign back to me if you do not find time to do this

**Comment by sandy081** [comment]
This will be done along with improvements to Key bindings experience. Hence moving to backlog
