### ISSUE TITLE
OOM with extension host profiling

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode#169299]
Recently I've been seeing a lot more native window crashes. In particular, I can reliably get a crash to happen in a minute when editing js-debug's [gulpfile](https://github.com/microsoft/vscode-js-debug/blob/main/gulpfile.js). Here's a dump of one:

[d9c95c49-a575-4991-b4d8-899c992003a5.dmp.zip](https://github.com/microsoft/vscode/files/10239646/d9c95c49-a575-4991-b4d8-899c992003a5.dmp.zip)

**Comment by rzhao271** [comment]
I have symbolicated the crash dump. The crash seems to occur from running out of memory.
[symbolicated-169299.log](https://github.com/microsoft/vscode/files/10240616/symbolicated-169299.log)

Are you able to create a memory profile?

**Comment by connor4312** [comment]
Looks like it has to do when extension host profiling. CpuProfileAnalysis rapidly eats memory then crashes the page

<img width="585" alt="Screenshot 2022-12-15 at 1 19 27 PM" src="https://user-images.githubusercontent.com/2230985/207969383-0a542b24-48b6-4d97-a67d-96e7c775552a.png">

**Comment by deepak1556** [comment]
@rzhao271 you would also need to add symbols for `Code - Insiders Helper (Renderer)  0.0.0.0  (main)  (WARNING: No symbols, Code - Insiders Helper (Renderer), 4C4C440555553144A109126D1646C4490)`

**Comment by jrieken** [comment]
@connor4312 It's your code that I have copied 🙊 Can you help me with it?

**Comment by rzhao271** [comment]
Here is the updated symbolicated crash dump.
[output.log](https://github.com/microsoft/vscode/files/10248197/output.log)

New info here:
```
31  Electron Framework!ElectronMain [electron_library_main.mm : 34 + 0x5]
    rbp = 0x00007ff7b82d44e0   rsp = 0x00007ff7b82d4410
    rip = 0x00000001106552a8
    Found by: previous frame's frame pointer
32  Code - Insiders Helper (Renderer)!main [electron_main_mac.cc : 68 + 0xb]
    rbp = 0x00007ff7b82d4530   rsp = 0x00007ff7b82d44f0
    rip = 0x0000000107c2a980
    Found by: previous frame's frame pointer
```

**Comment by connor4312** [comment]
I can easy reproduce. It looks like the model we build for bottom up profiles is just very memory intensive in some scenarios. However I also notice that we scarcely use the full bottom-up profile, unlike the profile editor, and can do more targeted analysis instead. I will prepare a PR.

**Comment by jrieken** [comment]
Thanks @connor4312

**Comment by roblourens** [comment]
What did you do to trigger the crash?

**Comment by connor4312** [comment]
For me, installing the [import cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost) plugin and opening js-debug's gulpfile for several seconds reliably does it. Verify that you see "starting to profile NOW" in the debug console, and that VS Code doesn't crash shortly afterwards when that finishes.
