### ISSUE TITLE
Increase size of stop icon

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16929]
To be the same size as attach and the other icons. Currently it looks too small

**Comment by isidorn** [comment]
@bgashler1 can you please increase the size of our debug stop icon to be the same size of our disconnect icon?

it just needs a bit of height
Here is the location of the current icons https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/parts/debug/browser/media/stop.svg#L12

**Comment by bgashler1** [comment]
![possible-options-of-resizing-icons](https://cloud.githubusercontent.com/assets/11839736/22172269/05946046-df57-11e6-9c07-952987c2fc54.png)
Here's what it would look like to do a variety of ways to improve this.  I agree that increasing the stop icon size slightly helped most.

**Comment by isidorn** [comment]
@bgashler1 thanks! Looks as the best option definitely!

**Comment by isidorn** [comment]
@bgashler1 is there some middle ground between the previous and the current stop icon. The one we have right now looks a bit too large, and the previous too smalh imho
Got feedback that the current one is too large from @jrieken and @roblourens 
Reopening to discuss
