### ISSUE TITLE
Suggest SCM/Git in Timeline welcome view

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#169205]
When the current file doesn't have history, the timeline shows just _"no timeline information was provided"_. This would be a great moment to tell users about source control, maybe giving them a shortcut to enable it.

<img width="270" alt="image" src="https://user-images.githubusercontent.com/8599/207771793-928cbf04-5de3-4d86-8cdf-83dc6fd25d93.png">

Ideas for wording: 
- _Use [Source Control](#) to track changes to your files and easily restore previous versions._
- _Use [Source Control](#) to take control of your files. Track changes and easily restore previous versions._
- _Need to track or restore older versions? Set up [Source Control](#)._
- Others?

Sending them to the SCM view as action would be a good start.

Maybe a follow up: Add a muted list entry _Use Source Control to track longer history …_

cc @lramos15 @lszomoru

**Comment by lszomoru** [comment]
I think that we should also tell them about the local history feature.

**Comment by lramos15** [comment]
Do we want texts or buttons? Similar to what we do with the explorer when it is empty.

**Comment by digitarald** [comment]
> I think that we should also tell them about the local history feature.

Makes sense, so we don't confuse users that have not edited yet. Maybe sth like *Changes will be tracked for each save. [git pitch here]*

**Comment by lramos15** [comment]
@gjsjohnmurray Has generously made a PR for this. We don't have easy link support just yet, so for now this is a middle ground of adding more verbose text
