### ISSUE TITLE
Git - status bar item improvements

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#169246]
- [x] Disable status bar items (Checkout, Sync) for the following operations: Checkout, Commit, Pull, Push, Sync
- [x] Checkout status bar item
  - [x] Update icon based on ref type
  - [x] Show progress while ref is checked out

//cc @digitarald

**Comment by lszomoru** [comment]
Verification steps:
- Open a folder/workspace that contains a git repository (ex: microsoft/vscode)
- Use the "Git: Checkout to..." command from the command palette to:
  - Checkout a branch
    - Confirm that the status bar item contain a branch codicon
  - Checkout a tag
    - Confirm that the status bar item contain a tag codicon
  - Checkout detached
    - Confirm that the status bar item contain a commit codicon

**Comment by alexr00** [comment]
Detached didn't work as expected, but the others did: https://github.com/microsoft/vscode/issues/172178
