### ISSUE TITLE
Allow to show diff of current file to unsaved changes

### ISSUE THREAD

**Issue by phra** [Microsoft/vscode#16921]
### Feature request

at the moment vscode use undo/redo history to tell if the file has pending changes.
it would be nice that it can also execute an in-memory diff (with of course an upper limit on the size of file specified in the config) between the last saved copy and the actual one in the editor to understand if the two copies are really different, leaving the undo/redo history.

what do you think about this guys?

**Comment by brunoleos** [comment]
I was looking for a way to show modified and unsaved lines, and hit this FR. Is there a way to show these lines in the current version 1.9.1? If not, is this FR needed to mark modified and unsaved lines with Gutter?

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/358
