### ISSUE TITLE
Cursor position jumping with line decorations

### ISSUE THREAD

**Issue by rebornix** [microsoft/vscode#169286]
* Install GitLens
* Enable line blame
* Put cursor at the end of line
* Arrow up and down

https://user-images.githubusercontent.com/876920/207919121-382148a6-acb2-40f8-b97e-a7617fc79aa0.mov

On Arrow up/down, the cursor will go the very far right and move to the end of text quickly.

**Comment by alexdima** [comment]
I believe this was caused by https://github.com/microsoft/vscode/issues/169171
