### ISSUE TITLE
Find input bleeds over toggles

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#169210]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/900690/207797091-008496de-75ef-4022-9b08-448d9d750f16.png">

I used this search string: `.part.statusbar > .items-container > .statusbar-item a:hover:not(.disabled) `

**Comment by gjsjohnmurray** [comment]
Also seeing this in Search view:

![junk](https://user-images.githubusercontent.com/6726799/207847959-945057d9-6c6a-4de2-8906-1a7d74c300e2.gif)

Version: 1.75.0-insider (user setup)
Commit: 44531ffc7b7477dbe82750040d8ed69bae2bb140
Date: 2022-12-15T08:33:44.005Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

**Comment by rebornix** [comment]
I don't recall we make changes find widget or search, it's very likely a regression of the find input.

**Comment by roblourens** [comment]
Maybe https://github.com/microsoft/vscode/pull/165989? This area is tricky

**Comment by andreamah** [comment]
Yes, I think this might have been a regression there, but I'm not able to repro either the searchview or the findwidget's overlap...
[![Image from Gyazo](https://i.gyazo.com/c89253ed05c7f60f7b58c8c5a11cf52b.gif)](https://gyazo.com/c89253ed05c7f60f7b58c8c5a11cf52b)

Are there any additional repro steps?

**Comment by andreamah** [comment]
Actually, this is probably a regression from #162036

**Comment by andreamah** [comment]
I just updated insiders an now I see the bug in the search viewlet. Since I was already pretty up to date before, was this a recent regression?

**Comment by rebornix** [comment]
Reverting https://github.com/microsoft/vscode/commit/95a0859cf744dd15df53a7065cde0929a7a89f6a fixed the problem.

**Comment by bpasero** [comment]
Should https://github.com/microsoft/vscode/issues/168199 be reopened?
