### ISSUE TITLE
"Monocraft" font not loading as intended

### ISSUE THREAD

**Issue by Deftu** [microsoft/vscode#169250]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.1
- OS Version: Windows 11 Pro 22H2 (Build 22621.963)

Steps to Reproduce:

1. Install the [Monocraft](https://github.com/IdreesInc/Monocraft) font.
2. Open VSCode.

Additional information:

The font works correctly after replacing it, hence meaning opening the font file and clicking "Install". The issue only occurs upon restarting Windows.

**Comment by deepak1556** [comment]
I am unable to repro the issue with `1.74.3`, can you share additional details about what is not working as intended possibly with some screenshots. Thanks!
![Screenshot_20230125_022529](https://user-images.githubusercontent.com/964386/214486983-579d076b-43e6-4e35-a097-5040a0aa7ccc.png)

**Comment by Deftu** [comment]
It appears that this could be an issue within Windows and not only VSCode, as other applications are also being affected. The font file seems to get corrupted each time I restart my machine, and I need to reinstall it...

**Comment by deepak1556** [comment]
In that case, I will close this as not actionable. Thanks for the follow-up.
