### ISSUE TITLE
Debug: step into node.js core function results in "Path must be string, received undefined"

### ISSUE THREAD

**Issue by bpasero** [Microsoft/vscode#16935]
Steps to Reproduce:

1. debug a node.js application (smoke test)
2. step into a require call

=> 
![image](https://cloud.githubusercontent.com/assets/900690/21016961/ef145c4c-bd67-11e6-8ab5-dd4f7717e6ef.png)

**Comment by isidorn** [comment]
@bpasero Works for me on the mac for the smoke test example. Do you always get it - if not let me know where you put a breakpoint.
Can you also repro with node2 as a type in your launch.json?

**Comment by weinand** [comment]
Cannot reproduce. What OS, node version?

**Comment by weinand** [comment]
@bpasero any errors showing up in the Chrome dev tools console?

**Comment by bpasero** [comment]
Hm this seems unrelated to debug.
