### ISSUE TITLE
Use a round border for start debug action

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16939]
So it resembles more the native dropdown

As per feedback by @jrieken

**Comment by isidorn** [comment]
Yeah I found out the same. Due to that closing as will not fix until more users complain and then I might consider having a special design for os x

**Comment by jrieken** [comment]
I keep complaining. Obviously this is a Mac only issue

**Comment by Tyriar** [comment]
Not sure if we're doing this yet but we could always add the platform as a class on `body` and scope a CSS rule to that?

**Comment by isidorn** [comment]
Yes - there is already a platform class on the top level workbench element
