### ISSUE TITLE
Trigger characters cancel quick suggest request

### ISSUE THREAD

**Issue by bradlc** [microsoft/vscode#169390]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: **1.74.1 (Universal)** and **1.75.0-insider (Universal)**
- OS Version: **macOS 12.5.1**

Steps to Reproduce:

1. Clone https://github.com/bradlc/vscode-completion-issue
2. Open the extension in VS Code and run the "Run Extension" task from the "Run and Debug" panel
3. Create a new untitled file and change the language to "TypeScript JSX"
4. Set the file contents to `''`
5. Move the cursor in between the quotes: `'|'`
6. Trigger completions manually
7. You should see two completions provided by the extension, `foo-20` and `foo-hello`
8. Type `foo-`
9. At this point the completions should still be visible
10. Type `2`
11. At this point the completion list should still be open, but it has closed
12. If you type `h` instead of `2` then the list stays open as expected

This behaviour seems to have changed recently because it worked as expected in the September release (and maybe the October one?)

**Comment by jrieken** [comment]
I can reproduce but I am not quite sure what's happening. It seems like typing `2` is understood as entering a new word and retriggering completions. That carries over the existing items (foo-20 and foo-hello) and they should be kept stable. _However_, the `2` also seems to be a trigger character which cancels the pending request, loses the in-flight items, and retriggers only for the provider that is triggered by that character

**Comment by jrieken** [comment]
Emmet is the provider that is triggered by the 2.

<img width="808" alt="Screenshot 2022-12-16 at 13 44 33" src="https://user-images.githubusercontent.com/1794099/208100998-d0661720-c0af-432d-9346-60940231d370.png">
