### ISSUE TITLE
Change All Occurrences not respecting capitalisation

### ISSUE THREAD

**Issue by 5enpai** [Microsoft/vscode#16934]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:35:54.093Z)
- OS Version: Linux ia32 3.13.0-24-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|togglehs|bbenoist|0.1.2|
|cpptools|ms-vscode|0.9.2|

---

Steps to Reproduce:

1.Highlight Symbol
2.Right-Click, Change All Occurrences

Example:
Terrain terrain ();

When renaming the instance-name, the type gets renamed, too.

**Comment by alexandrudima** [comment]
Change All Occurences respects the find widget settings for match whole words / match case which are toggleable via `alt+w`, or `alt+c`

**Comment by 5enpai** [comment]
Sorry to bother but is it possible to set those options to a default. I don't find an option under:
File/Preferences/User Settings

**Comment by alexandrudima** [comment]
Not yet, let's track in #10344
