### ISSUE TITLE
Remove message insider builds are becoming daily builds

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16931]
This is the message that is spamming every insider user we have on a new insalation. He knows that it is daily he just downloaded it from the site

I will remove this message unless someone objects
@chrisdias @bpasero @waderyan

**Comment by waderyan** [comment]
I made a PR to improve the messaging... must've fallen through the cracks.

**Comment by waderyan** [comment]
No problem removing. Sounds good from my end 👍
