### ISSUE TITLE
SCM input does not correctly apply input border

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#169309]
- Use Dark+ V2 or another theme that feature `input.border`
- See that the SCM input in it's default state renders a border, but it doesn't look

<img width="296" alt="CleanShot 2022-12-15 at 11 20 41@2x" src="https://user-images.githubusercontent.com/25163139/207948549-4e7c93d3-d2a5-41d9-887a-2fe4b9aff263.png">

<img width="290" alt="CleanShot 2022-12-15 at 11 21 19@2x" src="https://user-images.githubusercontent.com/25163139/207948539-ded18572-e2e2-40e2-9e0c-c2bf4a8e2369.png">

Removing the 1px padding yields this, which is mostly correct but produces an artifact on the right side:

<img width="292" alt="CleanShot 2022-12-15 at 11 23 17@2x" src="https://user-images.githubusercontent.com/25163139/207948972-4f1f06fe-0e83-4d93-9be2-fd4d0091e8fc.png">

**Comment by lszomoru** [comment]
@daviddossett, is this still an issue? I am seeing the correct background/border in the commit input field in Insiders:

![Image](https://user-images.githubusercontent.com/3372902/208430009-b959e0be-b808-46f7-910b-3d29d8b8abde.png)

**Comment by daviddossett** [comment]
Sorry, I fixed this before I left for holidays and forgot to close this.
