### ISSUE TITLE
SCM input shows a lighter background color on Dark+

### ISSUE THREAD

**Issue by daviddossett** [microsoft/vscode#169310]
Perhaps due to semi-opaque color being applied to multiple layers within the input:

<img width="210" alt="CleanShot 2022-12-15 at 11 28 11@2x" src="https://user-images.githubusercontent.com/25163139/207949872-fdc32ea1-7eb3-441a-a1e0-cdea91e7bf0b.png">

<img width="289" alt="CleanShot 2022-12-15 at 11 28 23@2x" src="https://user-images.githubusercontent.com/25163139/207949877-c78a2ab2-f8cc-48ff-bbca-b56f01e56cd9.png">

**Comment by robertrossmann** [comment]
The source control message input background does not seem to use `input.background` color customization at all. ⚠️

**Comment by daviddossett** [comment]
@robertrossmann I saw it in there, but it's a fairly complex component under the hood and (I think) multiple layers of the component use it. Because the color is semi-opaque it's appearing brighter than it should be after mixing with one layer with another.

**Comment by robertrossmann** [comment]
You can reproduce & verify that the colour is not applied to this particular input by setting `input.background` color customization in your settings JSON to a bright red:

```json
"workbench.colorCustomizations": {
    "input.background": "#ff0000"
  }
```

Observe all other inputs having bright red backgrounds but the commit message input background still having the same background as the surrounding panel's background.

**Comment by robertrossmann** [comment]
This is what I am seeing with the `Dark+` built-in theme, it looks like it completely blends with the panel's background. For me this is happening with all themes, built-in & third-party - the input's background inherits the panel's background and cannot be customised at all. 🤷‍♂️ 

![Screenshot 2022-12-15 at 22 06 55](https://user-images.githubusercontent.com/3058150/207967238-f071552e-2d55-44df-9551-04b1d6c10680.png)

**Comment by daviddossett** [comment]
It works for me. I don't see the behavior you do with a transparent background. I'm also noting that you have a different typeface used for the placeholder. That leads me to believe there is something else going on. Are you using any extensions that manipulate VS Code e.g. customize UI?

<img width="314" alt="CleanShot 2022-12-15 at 13 26 22@2x" src="https://user-images.githubusercontent.com/25163139/207970455-fcaff9f5-ebcf-4bdc-89ab-19949c194863.png">

**Comment by robertrossmann** [comment]
It works for me too when I place SCM panel to the left sidebar, but when SCM panel is placed to the **right** sidebar then all theming is ignored on the input. I do not see this problem mentioned in #16932

#### SCM is placed to the left sidebar - ✅ 

![Screenshot 2022-12-15 at 22 29 24](https://user-images.githubusercontent.com/3058150/207971223-27fdce71-6cfe-474d-afdd-520251b906e1.png)

#### SCM is placed to the right sidebar - ❌ 

![Screenshot 2022-12-15 at 22 33 16](https://user-images.githubusercontent.com/3058150/207971556-46552017-a1c3-4b4e-8f0d-8d6c08d51e42.png)

**Comment by daviddossett** [comment]
That one I can indeed repro. Can you file a new issue for that?

**Comment by robertrossmann** [comment]
Done! 💪 Submitted as #169326.
