### ISSUE TITLE
"Surround With" code action snippets use incorrect indentation levels and styles

### ISSUE THREAD

**Issue by DanielRosenwasser** [microsoft/vscode#169319]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.75.0-insider (user setup)
Commit: 11238faea62d570d77afe6edfe05c8b732c44a2b
Date: 2022-12-13T05:22:12.417Z (2 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes

Start with the following JS or TS file.

```ts
function foo(f, x, condition) {
    f();
    return x;
}
```

Notice that this code uses 4-space indentation. Now select the following range...

```ts
function foo(f, x, condition) {
    [|f();
    return x;|]
}
```

trigger the code actions menu (<kbd>Ctrl</kbd>+<kbd>.</kbd> on Windows), and select `Surround With: If Statement`.

Expected:

```ts
function foo(f, x, condition) {
    if (condition) {
        f();
        return x;
    }
}
```

Actual:

```ts
function foo(f, x, condition) {
if (condition) {
	    f();
	    return x;
}
}
```

Notice that

1. The "root" indentation for the surrounding code is incorrect - it starts at column 0.
2. The surrounded code is now incorrectly indented with a single tab character, followed by 4 spaces.

This is actually different from what happens if a user goes through the command palette and selects

1. `Snippets: Insert Snippet`
2. `if`

**Comment by jrieken** [comment]
I can reproduce (something similar) but I am getting 

```
function foo(f, x, condition) {
    if (condition) {
	f();
	    return x;
}
}
```
