### ISSUE TITLE
clicking `select kernel` without Jupyter extension installed opens an empty quick pick that loads forever

### ISSUE THREAD

**Issue by amunger** [microsoft/vscode#169304]
I ran into this after opening a workspace in a dev container that didn't have the Jupyter extension and trying to run a notebook. There was no suggestion for how to get anything to show up in that list.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/2019016/207943073-edc0b6e4-94c1-4c7e-b389-2c1b946c687f.png">

**Comment by rebornix** [comment]
Fixed via https://github.com/microsoft/vscode/pull/169586

**Comment by amunger** [comment]
repro:
create a temporary empty profile
open a notebook
click 'select kernel'

**Comment by rebornix** [comment]
@amunger can you share what you saw, did you see "Select Kernel" in the quick pick title? Does it work if you close and reopen the select kernel quick pick?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/876920/214463912-7464f483-7159-401b-b701-95afd8685dcd.png">

**Comment by amunger** [comment]
![noKernels](https://user-images.githubusercontent.com/2019016/214681798-79450d65-c524-4f1a-9b9f-34d427861297.gif)

**Comment by amunger** [comment]
it stays like that forever

**Comment by rebornix** [comment]
It happens when you have 

* Jupyter installed
* Play around with Jupyter notebooks a bit, especially using the kernel picker
* Switch to a new profile
* Now open a notebook, open kernel picker 🐛 

When we switch profiles, we would restart EH. The kernel detection tasks registered through previous EH were not disposed.
