### ISSUE TITLE
Adopt configurationSnippets in debug adapter

### ISSUE THREAD

**Issue by isidorn** [Microsoft/vscode#16937]
In order to have a nice add configuration experience it would be great if as many debug adapters adopt the configurationSnippets attribute in launch.json
Examples: [node debug](https://github.com/Microsoft/vscode-node-debug/blob/master/package.json#L95), [mock debug](https://github.com/Microsoft/vscode-mock-debug/blob/master/package.json#L71)

ping @delmyers @gregg-miskelly @daviwil @MSLaguana @DanTup @WebFreak001 	@andysterland @hbenl @lukaszunity 	@svaarala @vadimcn @felixfbecker @rkeithhill @DonJayamanne @MSLaguana @rebornix 

![addconfig](https://cloud.githubusercontent.com/assets/1926584/21016889/a526f37e-bd67-11e6-8322-4214dcb00b22.gif)

**Comment by DanTup** [comment]
Which version of Code does this require? (and is it safe to include in the `package.json` if still targetting older versions?)

**Comment by roblourens** [comment]
@isidorn This is in node2 also

**Comment by isidorn** [comment]
@roblourens great! I just noticed that it is missing in chrome adapter
@DanTup this requires code 1.8. It is safe to include in the package.json for older versions - it will not change any behavior

**Comment by DanTup** [comment]
@isidorn Great, thanks!

**Comment by rkeithhill** [comment]
BTW are there any prelim docs for this feature.  I have this implemented for the PowerShell extension (not committed yet). I want to make sure I grok the user scenario behind this feature.  It **looks** like this is meant for polyglot workspace debugging.  cc @daviwil

**Comment by rkeithhill** [comment]
BTW which form of escape is correct?  I see the mock debugger using `"program": "\\${workspaceRoot}/${1:Program}"` and the node debugger using `"program": "^\"\\${workspaceRoot}/${1:app.js}\""`.  I had better luck using the node debugger's syntax.  I just want to make sure the node syntax will work once the official 1.8 release of VSCode drops.

**Comment by isidorn** [comment]
@rkeithhill second example is right, I will update mock to use the correct one.

**Comment by hbenl** [comment]
Some documentation would be nice - `"^\"\\${workspaceRoot}/${1:app.js}\""` isn't really self-explanatory (although admittedly I was able to author my snippets with a few rounds of trial-and-error).

**Comment by WebFreak001** [comment]
Implemented and pushed in native debug as well as reverse continue, but as others stated The `"^\"\\${workspaceRoot}/${1:app.js}\""` is really weird, but I just accepted it and used it

**Comment by isidorn** [comment]
@hbenl @WebFreak001 the ^ json escaping is explained in our json doc [here](https://code.visualstudio.com/docs/languages/json#_json-schemas-settings)
This is needed only if you use ${workspaceRoot} or a similar variable in your snippet. The problem is coming from the fact that snippet variables have the same syntax as our debug variables, so these need to be escaped (otherwise they would be replaced as snippet placeholders).
Yes, it is a bit confusing - sorry about that
