### ISSUE TITLE
Cannot set default python interpreter

### ISSUE THREAD

**Issue by shyyhs** [microsoft/vscode#169361]
Type: <b>Bug</b>

There is always a recommand python interpreter, which is not the one I want to use. I use a interpreter in the virtualenv, however, I must set it for every python file, which is not practical. Is there a way to set a default python interpreter?

VS Code version: Code 1.74.1 (Universal) (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:33:40.793Z)
OS version: Darwin x64 21.3.0
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.4.0-51-generic
Remote OS version: Linux x64 5.4.0-51-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (1.49GB free)|
|Process Argv|--crash-reporter-id cab2c2c2-4176-43d7-be86-aff234013d74|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lotus/moss103|
|OS|Linux x64 5.4.0-51-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (20 x 1200)|
|Memory (System)|251.80GB (209.29GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: lotus/moss103|
|OS|Linux x64 5.4.0-51-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz (20 x 2965)|
|Memory (System)|251.80GB (209.30GB free)|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-great-icons|emm|2.1.86
output-colorizer|IBM|0.1.2
vscode-language-pack-ja|MS-|1.74.12140928
vscode-language-pack-zh-hans|MS-|1.74.12140931
jupyter-keymap|ms-|1.0.0
remote-ssh|ms-|0.94.0
remote-explorer|ms-|0.0.3
code-settings-sync|Sha|3.4.3
vim|vsc|1.24.3
copilot|Git|1.63.7601
chatgpt-vscode-plugin|Jay|1.1.10
vscode-language-pack-ja|MS-|1.74.12140928
vscode-language-pack-zh-hans|MS-|1.74.12140931
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by brettcannon** [comment]
You can manually set the interpreter via a setting for all files and workspaces via https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter . But if you are opening a workspace (i.e. directory), then you should only need to set it once for all the files in that workspace.
