### ISSUE TITLE
Assign accelerator keys to dialog buttons 

### ISSUE THREAD

**Issue by ssta604** [Microsoft/vscode#1693]
There are no shortcut keys defined for the dialog that pops up asking "Do you want to save the changes you made to..." when closing Code.  The keys S, N and possibly C should save, abort save or abort closing.

![codeconfirmdialog](https://cloud.githubusercontent.com/assets/9268628/12038785/bd8e4998-ae0f-11e5-90d4-ef58f09e7ca5.png)

Version 0.10.6
Commit a80232bbcfe8a5cdad1ebc98638673d9dcb02458
Date 2015-12-19T11:34:58.895Z
Shell 0.34.5
Renderer 45.0.2454.85
Node 4.1.1

**Comment by bpasero** [comment]
:+1: seems possible with our Electron version. Interestingly the "Cancel" button typically does not have a mnemonic it seems.

**Comment by ssta604** [comment]
Man you rock!  Such a quick resolution for a minor issue.

**Comment by bpasero** [comment]
From #1750 

Program exit file save confirmation dialog should provide acceleration keys.

The code at:

https://github.com/Microsoft/vscode/blob/6319a1e050de957531595511c6999aea653a5c21/src/vs/workbench/parts/files/electron-browser/textFileServices.ts#l175-l177
<br/>
should read:

```ts
const save = { label: resourcesToConfirm.length > 1 ? nls.localize('saveAll', "Save All") : nls.localize('save', "&Save"), result: ConfirmResult.SAVE };
const dontSave = { label: nls.localize('dontSave', "Do&n't Save"), result: ConfirmResult.DONT_SAVE };
const cancel = { label: nls.localize('cancel', "&Cancel"), result: ConfirmResult.CANCEL };
```

**Comment by SetTrend** [comment]
I just noticed I missed the ampersand on the "Save All" option. The suggestion should correctly read:

```ts
const save = { label: resourcesToConfirm.length > 1 ? nls.localize('saveAll', "&Save All") : nls.localize('save', "&Save"), result: ConfirmResult.SAVE };
const dontSave = { label: nls.localize('dontSave', "Do&n't Save"), result: ConfirmResult.DONT_SAVE };
const cancel = { label: nls.localize('cancel', "&Cancel"), result: ConfirmResult.CANCEL };
```

**Comment by bpasero** [comment]
:+1:

**Comment by SetTrend** [comment]
Excellent! :clap:
