### ISSUE TITLE
Copy path from editor tabs

### ISSUE THREAD

**Issue by mattmcnabb** [Microsoft/vscode#16930]
Right now we can copy a file's path from the explorer pane, but it would be great to have the same right-click context menu items available in the editor tab as well. I tend to leave the explorer pane minimized and a couple of editors open side-by-side, so if I need to copy a file path it's inconvenient to have to open the explorer pane and then right-click the file name in the open editors list.

Thanks and keep up the good work!

**Comment by bpasero** [comment]
This can and should be done as extension.

**Comment by bpasero** [comment]
Added "Copy Path" to the context menu of an editor that shows files.

**Comment by Tyriar** [comment]
This is fantastic for people who don't rely on the keybindings! Thanks for adding @bpasero :fireworks:
