### ISSUE TITLE
GitHub auth flow triggers allow URL prompt

### ISSUE THREAD

**Issue by digitaraldd** [microsoft/vscode#169458]
Type: <b>Bug</b>

Seen multiple times while testing on Windows 10 and 11 with a fresh VS Code installation.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/120693047/208213267-63bfca2c-bbe8-4888-80d8-d02ab25ebce1.png">

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.98GB (3.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.64.7694
vscode-pull-request-github|Git|0.56.0

</details>

**Comment by TylerLeonhardt** [comment]
@lramos15 this is trusted domains right? So it's you?

**Comment by lramos15** [comment]
This does not go through the trusted domain service as the extension itself is trying to open it, so this is the extension URL handler. There's some crypto check to allow for trusted extension handlers, but I'm too familiar with it.

https://github.com/microsoft/vscode/blob/854a56ce1d7a892b62cc900578e002e1ced90c41/src/vs/platform/extensionManagement/node/extensionUrlTrustService.ts#L22-L96

**Comment by joaomoreno** [comment]
https://github.com/microsoft/vscode/issues/169458

**Comment by digitarald** [comment]
@joaomoreno what are your thoughts about putting this up for the next iteration. Would be good to tackle as we smoothen out the end to end GH sign in experience.

**Comment by joaomoreno** [comment]
**Verification:** Login to GitHub using VS Code, you should not see this popup.
