### ISSUE TITLE
VSCode uninstalls itself after being open in the background while the PC shuts down

### ISSUE THREAD

**Issue by Phill030** [microsoft/vscode#169437]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.1 (user setup)
- OS Version: WINDOWS_NT x64 10.0.19045

Steps to Reproduce:

1. Open VSCode
2. Shutdown the PC while having VSCode open
3. Boot the PC
4. See that VSCode is not in the folder anymore and the link leads to a "Not found" error

**Comment by joaomoreno** [comment]
#52855
