### ISSUE TITLE
Looking for information on debugging a node C++ addon using nan and node-gyp

### ISSUE THREAD

**Issue by kmalakoff** [Microsoft/vscode#16941]
I'm having problems finding documentation on how to debug a node C++ addon using nan and node-gyp. 

There are articles to [debug JavaScript](https://github.com/Microsoft/vscode-node-debug) and [C++ applications](https://code.visualstudio.com/docs/languages/cpp), but I cannot seem to find an example of how to configure vscode to use node-gyp instead of g++ plus how to test calling between JavaScript and C++.

As a starting point, is it currently possible to debug node C++ addons with vscode and if so, is there an example project or documentation to reference?

I've been using vscode for JavaScript and loving it...now I'm hoping to do the same for node addons!

**Comment by colmartofus** [comment]
Any update on this?

**Comment by jkomyno** [comment]
+1

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#992

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-cpptools#993
