### ISSUE TITLE
Zooming UI 

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#16947]
- VSCode Version: 1.8.0 - insider
- OS Version: Windows

-- Sorry for the English, I used Google Translator --

Based on issue #14979 with  [comment](https://github.com/Microsoft/vscode/issues/14979#issuecomment-259390808).

1- Ctrl + + It should zoom in on the editor, the file we're moving, not the zoom of the whole program.
2- Ctrl + - You should zoom out within the editor, the file you are moving, not the zoom of the entire program.
3- Ctrl + 0 You should zoom back to the default, the file you are moving, not the zoom of the entire program.

4- Ctr + +, Ctr + - should work the same way when we use "editor.mouseWheelZoom", by only zooming the file. And using Ctrl + 0 returns to the default.

5- Ctr + = You should do nothing. The zoom continues. You must unlink this function.
6- Ctrl + 0 of the non-numeric keyboard does not reset the zoom.

These shortcut keys should be valid for both numeric and non-numeric keys. In the menu you should change the registration `Ctr + =` by `Ctrl + +`

Why not set specific sizes for the UI? Maybe some [problems ](https://github.com/Microsoft/vscode/issues/14979#issuecomment-265772474)mentioned by @alexandrudima would decrease!!

>In fact I am 100% in favor of eliminating the entire UI zoom we're shipping with, it causes many issues with font anti-aliasing for example and I have to maintain extraneous code to work around it (i.e. not using translate3d when the UI zoom is not 100%)

Example: Small, Normal, Large, Extra large. To set proportions, do a search with someone who uses sizes other than their normal size.

**Comment by mjbvz** [comment]
I believe zooming the editor instead of the entire ui is being tracked by #1348.

Please take a look at that issue and let us know if it does not cover your concerns. 

Thanks.

**Comment by Tekbr** [comment]
@mjbvz Yes, very similar to the issue. I'll put that question there !! Thank you.
