### ISSUE TITLE
Inlay Hints on/offUnlessedPressed is not explicit about shortcut

### ISSUE THREAD

**Issue by hffmnn** [microsoft/vscode#169478]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
```
Version: 1.74.1 (Universal)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
Sandboxed: No
```
- OS Version: `OS: Darwin arm64 21.6.0`

Steps to Reproduce:

1.  Have setting `"editor.inlayHints.enabled": "offUnlessPressed"` or `"editor.inlayHints.enabled": "onUnlessPressed"`
2. Press e.g. Ctrl - Option - Command - Shift (aka. Hyper-Key)

Expected:
The inlay hints don't show or hide because the shortcut is configured to work for modifiers `Ctrl` - `Option` only and gets ignored when any other modifier is pressed.

Experienced:
The inlay hints show or hide even if other modifiers are pressed at the same time.

**Note**
I tested with VS Code Insiders but inlay hints did not show at all when using it. 🤷

**Comment by jrieken** [comment]
Honest question: How this supposed to work? When pressing the ctrl-option subsequence for how long should we wait to await more keys? Or do you specifically mean the sequence  (1) ctrl, (2) options, (3) command, 4(shift)?

**Comment by hffmnn** [comment]
In my (naive) thought (naive because I have absolutely no idea how the VS Code key handling works), there was no awaiting for more keys involved. I thought that adding a modifier to an existing combination gets detected/handled the same way as removing a modifier. Because this is something that currently works: Pressing `Ctrl - Option` shows the inlay hints, removing the `Option` so only pressing `Ctrl` hides the inlay hints again.

**Comment by jrieken** [comment]
Yeah, that could actually work but it might mean that pressing (1) ctrl, (2) options, (3) shift will cause a short flicker because between (2) and (3) inlay hints will be active

**Comment by jrieken** [comment]
Ok, that was actually quite easy

https://user-images.githubusercontent.com/1794099/208409155-b966db1a-c244-40b1-b1f4-6963d1915b45.mov
