### ISSUE TITLE
GitHub copilot does not work/appear after the latest update

### ISSUE THREAD

**Issue by FahimFBA** [microsoft/vscode#169463]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:35:03.979Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.19.0-26-generic snap
Sandboxed: No

OS: Ubuntu 22.10

Steps to Reproduce:

1. Update VS Code to the latest and restart it
2. Copilot does not appear in the bar and nothing gets produced in the code from Copilot. Installing/Uninstalling the extension does not help.

**Comment by IsratIJK** [comment]
I am also facing the same issue.

OS: Windows 10 Version 22H2 (OS Build: 19045.2251)
VS Code: 
Version: 1.74.1 (user setup)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:30:51.966Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
Sandboxed: No

**Comment by PBW99** [comment]
copilot extension version v1.63.7601 works to mee

**Comment by AshSimmonds** [comment]
There's a scene in _Airplane_ I'm trying to re-enact to get Copilot up again, but apparently rolling back a version does the trick until a fix is in.

**Comment by Coxxs** [comment]
![image](https://user-images.githubusercontent.com/3007303/208231792-22556843-f840-43b7-9786-6265222a67f6.png)
Select `1.63.7601`

**Comment by FahimFBA** [comment]
> ![image](https://user-images.githubusercontent.com/3007303/208231792-22556843-f840-43b7-9786-6265222a67f6.png) Select `1.63.7601`

This is working!

**Comment by shriharip** [comment]
I am also facing this issue.
Co pilot not working after latest update
```
Version: 1.74.1 (Universal)
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z (2 days ago)
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

**Comment by nolanbarry** [comment]
Newest version `1.65.7705` fixes this for me.

**Comment by FahimFBA** [comment]
As changing the version solves the issue, I am closing this.
