### ISSUE TITLE
Cannot input Polish letter

### ISSUE THREAD

**Issue by wieczorek1990** [microsoft/vscode#169465]
Fresh install with theme setup and logged user.

Code 1.74.1
MacOS Ventura 13.1

Cannot input `ż` which is a letter normally produced by `Option + z`.

Please rebind on Polish language or provide a different per language keyboard shortcuts.

**Comment by gjsjohnmurray** [comment]
Please see https://code.visualstudio.com/docs/getstarted/keybindings for guidance on how you can resolve your issue.

**Comment by wieczorek1990** [comment]
Many first time users will not know why they cannot insert ż.
I deleted the bindings (two).

W dniu sob., 17.12.2022 o 11:17 John Murray ***@***.***>
napisał(a):

**Comment by alexdima** [comment]
The current default keybindings we ship with are optimized for the US standard keyboard layout. When on a different keyboard layout, we do our best to map them to the available and producible keys, but I agree that the automatic mapping does not always result in a good default experience. Please upvote https://github.com/microsoft/vscode/issues/1240 which is about us shipping with keyboard layout specific defaults.
