### ISSUE TITLE
Input validation message renders outside the input box

### ISSUE THREAD

**Issue by joyceerhl** [microsoft/vscode#169456]
Stable:

![image](https://user-images.githubusercontent.com/30305945/208209535-4e7db638-5426-4ad4-a6fa-bd73a894a44c.png)

:cheese: Insiders:

![image](https://user-images.githubusercontent.com/30305945/208209521-5f99d601-e3c7-41b5-98b4-20f29a1a3c3b.png)

**Comment by TylerLeonhardt** [comment]
This likely came in with the moving of progress. cc @daviddossett

**Comment by TylerLeonhardt** [comment]
Thought about this long enough, I don't think this is a bad thing. I don't think it needs to be contained to the quick pick box.
