### ISSUE TITLE
editor.formatOnSave adds and then removes spaces to function definitions, cluttering up the diff

### ISSUE THREAD

**Issue by mdgriest** [Microsoft/vscode#16940]
I have editor.formatOnSave set to true, as it is typically very useful for the Node project I am working on. However, this function sometimes decides to add a space between "function" and the argument list (for example, `var myFunc = function (a,b){...`), and other times decides NO space (ie `var myFunc = function(a,b){...`). This litters the diff with meaningless changes and causes a good deal of frustration.

---

- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|theme-onedark|azemoh|0.4.0|
|jshint|dbaeumer|0.10.15|
|Theme-snappy-light|gerane|0.0.2|
|vscode-exec-node|miramac|0.1.8|
|cpptools|ms-vscode|0.9.2|
|seti-icons|qinjia|0.1.3|

---

Steps to Reproduce:

1. set `editor.formatOnSave: true` in settings.json
2. work on a file, save it, commit/push, work on it some more, save it again. This won't happen every time, but frequently.

**Comment by TheColorRed** [comment]
You can run a diff without whitespace `-W`

```
git diff my-branch -W
```

**Comment by mjbvz** [comment]
@mdgriest Just to make sure I understand, is the issue that the formatter seems to lose its settings so that when it is run again, it reformats the document differently than it was formatted before?

If so, this may be related to https://github.com/Microsoft/TypeScript/issues/12618

**Comment by mjbvz** [comment]
I'm still unable to repo this and don't have enough information to investigate further.

@mdgriest If you are still hitting this issue with VSCode 1.8.1, please let me know and we can continue the investigation.

Thanks
