### ISSUE TITLE
terminal not shown at certain times

### ISSUE THREAD

**Issue by Nishil-Visawadia** [microsoft/vscode#169429]
Type: <b>Bug</b>

# Terminal issue

Not able to see the terminal on windows vs code while using the cmd or the powershell

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.94GB (0.83GB free)|
|Process Argv|--crash-reporter-id 9901315f-76f7-45b6-8eb8-dc3a1d47e633|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (50)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
html-snippets|abu|0.2.1
vscode-color|ans|0.4.5
vscode-tailwindcss|bra|0.9.1
simple-react-snippets|bur|1.2.7
npm-intellisense|chr|1.4.3
path-intellisense|chr|2.8.3
bracket-pair-colorizer-2|Coe|0.2.4
vscode-markdownlint|Dav|0.48.1
xml|Dot|2.5.1
es7-react-js-snippets|dsz|4.4.3
vscode-html-css|ecm|1.13.1
react-native-react-redux|EQu|2.0.6
prettier-vscode|esb|9.10.3
vs-code-xml-format|fab|0.1.5
auto-close-tag|for|0.5.14
auto-complete-tag|for|0.1.0
auto-rename-tag|for|0.1.10
solidity-debugger|hos|0.2.1
react-native-snippet|jun|0.5.6
vscode-language-babel|mgm|0.0.36
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
vscode-typescript-next|ms-|5.0.202212150
vscode-react-native|msj|1.10.0
hardhat-solidity|Nom|0.6.4
material-icon-theme|PKi|4.23.0
java|red|1.13.0
vscode-xml|red|0.23.0
r|REd|2.7.0
LiveServer|rit|5.7.9
vscode-javascript-booster|sbu|14.0.1
pdf|tom|1.2.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
vscode-icons|vsc|12.0.1
JavaScriptSnippets|xab|1.8.0
markdown-all-in-one|yzh|3.5.0
html-css-class-completion|Zig|1.20.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by Nishil-Visawadia** [comment]
![image](https://user-images.githubusercontent.com/100361580/208169570-342a2174-6a32-4438-878a-17d74e7e9d18.png)
image of the issue

**Comment by meganrogge** [comment]
does setting `terminal.integrated.gpuAcceleration` to off fix it?

**Comment by Nishil-Visawadia** [comment]
Just did the settings , will let you known in a few time !
Thank you for your time and consideration !!
