### ISSUE TITLE
run button missing

### ISSUE THREAD

**Issue by sanjeevshaji** [microsoft/vscode#169484]
Type: <b>Bug</b>

run button missing

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.87GB (3.43GB free)|
|Process Argv|--crash-reporter-id 7f1e1a9f-d102-4cd1-b443-dd58261a6cef|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
dart-code|Dar|3.54.1
flutter|Dar|3.54.0
vscode-eslint|dba|2.2.6
remotehub|Git|0.48.0
pubspec-assist|jer|2.3.2
dart-import|lua|0.3.1
dotenv|mik|1.0.1
azure-dev|ms-|0.3.0
vscode-azureappservice|ms-|0.24.5
vscode-azurefunctions|ms-|1.9.0
vscode-azureresourcegroups|ms-|0.5.6
vscode-azurestaticwebapps|ms-|0.11.3
vscode-azurestorage|ms-|0.15.0
vscode-azurevirtualmachines|ms-|0.6.2
vscode-cosmosdb|ms-|0.19.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
azure-account|ms-|0.11.2
azure-repos|ms-|0.24.0
js-debug-nightly|ms-|2022.12.1417
remote-repositories|ms-|0.26.0
vscode-node-azure-pack|ms-|1.1.1
material-icon-theme|PKi|4.23.0
vscode-javascript-booster|sbu|14.0.1
JavaScriptSnippets|xab|1.8.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by LukaHietala** [comment]
Which run button exactly?
