### ISSUE TITLE
Launch drop down no longer updates

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16946]
- VSCode Version: Code - Insiders 1.8.0-insider (e0871329738682651367be4e8a618912ad693e03, 2016-12-08T07:05:13.731Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|tslint|eg2|0.6.0|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

---

This was working in yesterdays insiders:
![dec-08-2016 11-21-31](https://cloud.githubusercontent.com/assets/9205389/21024247/8802c6f8-bd38-11e6-8609-de02b8fe1951.gif)

Also when adding a launch config manually.

**Comment by bpasero** [comment]
@chrmarti I cannot reproduce with latest insider

**Comment by isidorn** [comment]
Can not reproduce.
@chrmarti for some reason you were probably missing file event. If you are still in that broken state do you see git status updating when you are making changes to a file for instance,

@weinand can you also please try.

**Comment by weinand** [comment]
I cannot reproduce this in Version 1.8.0-insider, df6fcbe12a000a62fb526fe6953405e28c6e6fc3, 2016-12-09T09:00:32.682Z

**Comment by bpasero** [comment]
This is because he is running the workspace with lowercase path due to hot exit bug. in that case all file events are broken.

**Comment by isidorn** [comment]
So dup of https://github.com/Microsoft/vscode/issues/16829
