### ISSUE TITLE
vscode auto import not working

### ISSUE THREAD

**Issue by shreedharhegde99** [microsoft/vscode#169402]
Does this issue occur when all extensions are disabled?: Yes

Even after disabling all the extensions, the auto import feature is not working. It works only when you keep the required component open in another tab.

### when the component is not open in the side tab
![Screenshot from 2022-12-16 20-36-20](https://user-images.githubusercontent.com/90758718/208128970-2ce29ff4-5099-424a-8a6d-e946ebe1766c.png)

### when the component is open in the side tab
![Screenshot from 2022-12-16 20-31-39](https://user-images.githubusercontent.com/90758718/208129024-94bd8ef7-e4ef-4563-a4d5-b229f94bc725.png)

```
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:35:03.979Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-56-generic snap
Sandboxed: No
```

**Comment by mjbvz** [comment]
If it works when the file is open but not when it is closed, your project is likely misconfigured. Make sure both the file you are working in and the file with the symbol you want to import are in the same jsconfig/tsconfig project. You can check this by clicking on the `{}` in the status bar:

<img width="725" alt="Screenshot 2022-12-16 at 11 09 17 AM" src="https://user-images.githubusercontent.com/12821956/208171183-c0fea51a-3275-4978-ae5e-aca318a1f74b.png">

**Comment by shreedharhegde99** [comment]
Thank you @mjbvz . 

> Make sure both the file you are working in and the file with the symbol you want to import are in the same jsconfig/tsconfig project

But I am not using any jsconfig/tsconfig file in my project. I am using CRA with default config.


![Screenshot from 2022-12-17 13-43-40](https://user-images.githubusercontent.com/90758718/208232755-6f453013-74d7-40b3-97d4-690940f17a44.png)





![Screenshot from 2022-12-17 13-41-38](https://user-images.githubusercontent.com/90758718/208232595-762a7bcf-f3ff-480c-b4a5-2d39e2b1811c.png)

Please let me know how can I fix this. Thanks in advance.
