### ISSUE TITLE
Recent files list got erased after vscode update

### ISSUE THREAD

**Issue by T1mL3arn** [microsoft/vscode#169495]
Today I updated VSCode to 1.74.1 (the previous version was 1.64 I believe) and recent files list (the one you can access in File - Open Recent) got erased. Is there any way to restore the list? 

Version: 1.74.1 (user setup)
OS: Windows_NT x64 6.3.9600

**Comment by bpasero** [comment]
Sorry, but we had run for months with migration code to migrate it to a new location (see https://github.com/microsoft/vscode/commit/9012a26b55e697dc54e88f8c1aaf7fc8803c5b3a that removed it). Your jump of versions likely jumped over that migration code.

You may still find the list in the `C:\Users\<your name>\AppData\Roaming\Code\User\globalStorage\storage.json` with the key `openedPathsList`.

**Comment by T1mL3arn** [comment]
This file has no such key. But in this folder I found sqlite database, which contains a lot of `scm/input:Git:C:/somepath` strings. This looks like a history of all my versioned projects opened with VSCode. What structure is used to describe a "recent item" and where I should put the reconstructed list?

**Comment by bpasero** [comment]
There are 2 buckets of recent items:
* per workspace: stored in SQLite under `history.entries` in the workspace associated SQLite storage data base (there is 1 per workspace and 1 globally)
* global: stored in the global SQLite storage instance under the key `history.recentlyOpenedPathsList` for all recently opened workspaces, folders and files

**Comment by bpasero** [comment]
I am going ahead and close this item, thanks.

**Comment by T1mL3arn** [comment]
I was able add lost paths to the global storage. Surprisingly, VSCode opens not just project folders but also restores files as well (I assume the problem update did not delete such info). Thank you for help.
