### ISSUE TITLE
Fix reversed the statement when mixed RTL with LTR

### ISSUE THREAD

**Issue by AhmedElTabarani** [microsoft/vscode#169459]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74.1
- OS Version: Windows_NT x64 10.0.19044

Statements reversed when mixed RTL with LTR 

Steps to Reproduce:

Actually: right order should be as the numbers, should order the words from right to left
![208216659-1a055824-92c1-4687-9944-011e1c503d53](https://user-images.githubusercontent.com/69223584/208239811-0d6c7333-1f9c-4bab-985e-bb85a6754c31.png)

 Expected: as the order of the numbers
 
![image](https://user-images.githubusercontent.com/69223584/208216838-365838b2-a9f4-41bd-8d18-57e7b0af04af.png)

Text:

```bash
// ما هو JWT ؟
// أولًا هو اختصار لـ Json Web Token
// والـ Json هو الشكل المتعارف عليه في تخزين البيانات
```

Note: GitHub displayed the text correctly and also make the whole text go to right of the page 
this issue is not "all the text not going to the right of the screen", because that's another issue
this problem is with "sentence imbalance in general"

**Comment by alexdima** [comment]
@AhmedElTabarani  Is there any code editor which is able to display the text in the desired order (as you post in the second screenshot)? This is the HTML we generate on our side in order to render the first line:
```html
<span dir="ltr"><span style="unicode-bidi:isolate" class="mtk4">//&nbsp;ما&nbsp;هو&nbsp;JWT&nbsp;؟</span></span>
```

I've created a fiddle with it at https://jsfiddle.net/zxgbdfL7/

How should the HTML we generate look like for the first line in order to achieve the desired order and what would be the rules behind generating it in that way?

**Comment by AhmedElTabarani** [comment]
> Is there any code editor which is able to display the text in the desired order

I didn't see any code editor support that, any way most of the programs support RTL as GitHub did.

> How should the HTML we generate look like

in my website I use two way to achieve that

```css
unicode-bidi: "plaintext"
```

or
```html
<span dir="ltr">...</span>
```

preview:

![image](https://user-images.githubusercontent.com/69223584/208974476-70e2c48b-4320-41d5-b866-b280b580c304.png)

Although `//` go to the right, but this will nice improvement and much readable right now

**Comment by AhmedElTabarani** [comment]
I think it is better to make an option in `View` to make the editor render each line as  dir= `rtl` or `ltr` or `auto` to avoid any side effects and to be tested better

**Comment by alexdima** [comment]
@AhmedElTabarani  Thank you for the two suggestions. I tried both and then did a test pass over various bidi samples I collected over the years. From my testing, I don't think we can ship any of these changes without breaking other samples. 

To get the rendering that you request, we will need to implement the bidi algorithm in JavaScript. We currently delegate the text rendering in the editor to the browser. I suggest we continue tracking this issue in #11770 . Please see below what I tried:

### using `dir="auto"`

Running with the change:
```diff
diff --git a/src/vs/editor/common/viewLayout/viewLineRenderer.ts b/src/vs/editor/common/viewLayout/viewLineRenderer.ts
index 0e94382f9a8..f4f31951fc8 100644
--- a/src/vs/editor/common/viewLayout/viewLineRenderer.ts
+++ b/src/vs/editor/common/viewLayout/viewLineRenderer.ts
@@ -939,7 +939,7 @@ function _renderLine(input: ResolvedRenderLineInput, sb: StringBuilder): RenderL
 	let partDisplacement = 0;
 
 	if (containsRTL) {
-		sb.appendString('<span dir="ltr">');
+		sb.appendString('<span dir="auto">');
 	} else {
 		sb.appendString('<span>');
 	}
```

<table>
<tr>
<td>Sample</td><td>

```json
{
  "invoice_vip":[
    ["🖨️ چاپ فاکتور","🎨 تنظیمات"]
  ]
}
```

</td></tr>
<tr><td>current rendering</td><td>
<img width="292" alt="image" src="https://user-images.githubusercontent.com/5047891/208990874-0afc6ae2-a716-43c7-8891-610afd326cb3.png">
</td></tr>
<tr><td>with dir="auto"</td><td>
<img width="319" alt="image" src="https://user-images.githubusercontent.com/5047891/208990775-8b44e17a-6d07-42a4-9e91-ad5133bd80db.png">
</td></tr>

</table>


---

### using `unicode-bidi:plaintext`

Running with the change:
```diff
diff --git a/src/vs/editor/common/viewLayout/viewLineRenderer.ts b/src/vs/editor/common/viewLayout/viewLineRenderer.ts
index 0e94382f9a8..a9aa11b6872 100644
--- a/src/vs/editor/common/viewLayout/viewLineRenderer.ts
+++ b/src/vs/editor/common/viewLayout/viewLineRenderer.ts
@@ -957,7 +957,7 @@ function _renderLine(input: ResolvedRenderLineInput, sb: StringBuilder): RenderL
 
 		sb.appendString('<span ');
 		if (partContainsRTL) {
-			sb.appendString('style="unicode-bidi:isolate" ');
+			sb.appendString('style="unicode-bidi:plaintext" ');
 		}
 		sb.appendString('class="');
 		sb.appendString(partRendersWhitespaceWithWidth ? 'mtkz' : partType);
```

<table>
<tr>
<td>Sample</td><td>

```html
<b>
	9- هزینه کاهش ارزش دریافتنی‌ها    
</b>

```

</td></tr>
<tr><td>current rendering</td><td>
<img width="319" alt="image" src="https://user-images.githubusercontent.com/5047891/208991707-6477be5a-24a5-46a8-a71d-c48d4bfca378.png">
</td></tr>
<tr><td>unicode-bidi:plaintext</td><td>
<img width="339" alt="image" src="https://user-images.githubusercontent.com/5047891/208991614-004ba002-f283-43d3-bdb4-f17831625c19.png">
</td></tr>

</table>
