### ISSUE TITLE
Have a "Hide" command in the context menu of profiles

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#169475]
![image](https://user-images.githubusercontent.com/900690/208252019-42977c97-6c56-470d-89ff-5a09deb43923.png)

Compare with the Accounts menu.

**Comment by sandy081** [comment]
You have to do the right click to get the context menu where you want to hide the acitivity bar entry

![image](https://user-images.githubusercontent.com/10746682/208696731-751f0d1d-613f-49ce-9cc7-a16737f318d9.png)

**Comment by bpasero** [comment]
Yeah strange, not sure what I thought there.
