### ISSUE TITLE
New watch expression shows old value while being evaluated

### ISSUE THREAD

**Issue by chrmarti** [Microsoft/vscode#16943]
- VSCode Version: Code - Insiders 1.8.0-insider (e0871329738682651367be4e8a618912ad693e03, 2016-12-08T07:05:13.731Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|autofilename|JerryHong|0.1.3|
|vscode-docker|PeterJausovec|0.0.7|
|regex|chrmarti|0.0.7|
|vscode-eslint|dbaeumer|1.1.0|
|ghlink|dt|0.0.4|
|tslint|eg2|0.6.0|
|vscode-scss|mrmlnc|0.6.0|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|diff|rafaelmaiolla|0.0.1|
|vscode-open-in-github|sysoev|1.2.1|

---

While verifying #14499:
![dec-08-2016 10-49-34](https://cloud.githubusercontent.com/assets/9205389/21023238/840f5c18-bd34-11e6-8633-89cf3cba6a02.gif)

Note that the first watch expression's value `3` is being shown while the second one is evaluating. (Also: There is flicker while evaluating the first watch expression showing an old timeout message.)

**Comment by isidorn** [comment]
Closing as will not fix
