### ISSUE TITLE
(Renaming) WorkSpaceEdit automatically saves the file

### ISSUE THREAD

**Issue by maziac** [microsoft/vscode#169473]
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:33:40.793Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No

Steps to Reproduce:

1. Use a typescript project
2. Open a file an edit it, so that it appears unsaved in the editor (content is not saved to disk)
3. In the file choose one method and select "Rename Symbol"
4. Choose a different name and press enter

Result:
1. The name is changed which is OK
2. The file is automatically saved -> Not OK.

As a user I would expect that the file stays in an unsaved state as it was before the renaming.

(I guess the rename provider is using a WorkSpaceEdit to perform the renaming . So probably the problem is that WorkSpaceEdit automatically saves files.)

**Comment by jrieken** [comment]
This can be configured via the `files.refactoring.autoSave` setting
