### ISSUE TITLE
Run withoutdebugger attaches the debugger making the process quite slow.

### ISSUE THREAD

**Issue by AndreaCatania** [microsoft/vscode#169476]
Does this issue occur when all extensions are disabled?: **Yes**

- OS Version: Fedora 37
- VS Code Version:  1.74.1
- Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
- Date: 2022-12-14T10:35:03.979Z
- Electron: 19.1.8
- Chromium: 102.0.5005.167
- Node.js: 16.14.2
- V8: 10.2.154.15-electron.0
- OS: Linux x64 6.0.12-300.fc37.x86_64
- Sandboxed: No

Steps to Reproduce:

1. Run  **without debugging** an Unreal Engine project
2. Note down the time taken to open the project
3. Run the exact same command to launch the UE project on terminal 
4. Note down the time taken to open the project

You will notice that the Run Without debugging will take a significant amount of time compared to running it from the terminal.

I saw that this was marked as not an issue in these two other issues, but it's definitely not the case when developing for UE using VSCode. It would be quite nice be able to disable this feature from settings.
- https://github.com/microsoft/vscode/issues/103515
- https://github.com/microsoft/vscode/issues/102057

#### Run Without the Debugger
https://user-images.githubusercontent.com/8342599/208252626-0eb2a819-010c-4afd-a2a1-e1f8347098c8.mp4

#### Run from Terminal
https://user-images.githubusercontent.com/8342599/208252624-74939070-2d2e-49cf-974a-9d9ab4fb76f2.mp4

**Comment by roblourens** [comment]
Please file this on the unreal debug extension that you're using
