### ISSUE TITLE
Go to definition doesn't work on the newest version

### ISSUE THREAD

**Issue by sgp86** [microsoft/vscode#169410]
Type: <b>Bug</b>

### Env information

- VS Code Version: 1.74.1
- OS Version: Windows NT x64 10.0.19045

### Steps to Reproduce:

Issue appeared just after upgrading VSCode to ver. 1.74.1

### Actual Result:

Currently, it is impossible to go to the function definition by clicking Ctrl+Click on the function name or using the F12 button. Also, the Go to definition option in Top Menu->Go->Go to Definition is disabled.

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz (6 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|47.95GB (39.96GB free)|
|Process Argv|--crash-reporter-id 593c4c24-3aa2-42e9-9dcb-ddf06dde8ee5|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by gjsjohnmurray** [comment]
What code language?

Is the option also disabled in the context menu?

#129189 was a previous issue about this and related options not getting enabled in the top-level Go menu. Maybe this has come back. Do you think this didn't happen in 1.74.0?

**Comment by gjsjohnmurray** [comment]
> #129189 was a previous issue about this and related options not getting enabled in the top-level Go menu. Maybe this has come back. Do you think this didn't happen in 1.74.0?

@jrieken - maybe caused by 099cfa996e9ff833c020eb5b29204c8365cc23e6

**Comment by jrieken** [comment]
Yeah, looks like the precondition for the command is too strong

**Comment by sgp86** [comment]
> What code language?
> 
> Is the option also disabled in the context menu?
> 
> #129189 was a previous issue about this and related options not getting enabled in the top-level Go menu. Maybe this has come back. Do you think this didn't happen in 1.74.0?

Javascript

I don't have such an option in the context menu

I'm not 100% sure, which version I had previously installed, but I'm using VSCode almost every day, so I'm pretty sure I was using 1.74.0 or 1.73.1, and that behavior has occurred after auto-upgrade to 1.74.1. I've never noticed anything like it before.

**Comment by sgp86** [comment]
After a clean uninstall (Uninstalled and deleted %APPDATA%\Code and %USERPROFILE%\.vscode), and install 1.74.1 again, the problem does not occur anymore.
