### ISSUE TITLE
Git:Maximum call stack sizr exceeded

### ISSUE THREAD

**Issue by y-vonn** [microsoft/vscode#169499]
Type: <b>Bug</b>

When clicked on the branch icon in the Git explorer,
![image](https://user-images.githubusercontent.com/34880601/208305507-bf58ebd7-6a65-4e6c-9eda-a6fa72da149a.png)
 I see checkbox and it said:
Git:Maximum call stack size exceeded，like this:
![image](https://user-images.githubusercontent.com/34880601/208305521-bcd35eb2-9ffe-4cbc-b748-7f108b04f267.png)

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.59GB free)|
|Process Argv|--crash-reporter-id 11d0fa24-7746-4a67-8b0e-74975992ca7e|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
sort-imports|ama|6.3.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.1.1
vscode-jest-runner|fir|0.4.59
workspace-cacheclean|Mam|0.0.2
powershell|ms-|2022.12.1
peregrine-webexperience-setup|per|1.2.7
peregrineconfig|per|1.1.0
prettyxml|Pra|3.0.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by sean-mcmanus** [comment]
@y-vonn I get this too -- did you fix it somehow? I have to switch branches via the command line as a workaround.
