### ISSUE TITLE
Icon GitHub Copilot don't show

### ISSUE THREAD

**Issue by Maggy30ev** [microsoft/vscode#169461]
Type: <b>Bug</b>

Suddenly the icon disappeared as well as the recommendations.

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 4800H with Radeon Graphics          (16 x 2894)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (8.94GB free)|
|Process Argv|. --crash-reporter-id b4539705-533d-401f-b1e0-78def0194bb1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|13.3.1
vscode-intelephense-client|bme|1.8.2
simple-react-snippets|bur|1.2.7
notes|can|1.3.0
vscode-html-css|ecm|1.13.1
prettier-vscode|esb|9.10.3
code-runner|for|0.11.8
classroom|git|0.0.3
copilot|Git|1.64.7694
vscode-pull-request-github|Git|0.56.0
gc-excelviewer|Gra|4.2.56
better-cpp-syntax|jef|1.17.2
polacode-2019|jef|0.6.1
import-sorter|mik|3.3.1
vscode-language-pack-es|MS-|1.74.12140936
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-wsl|ms-|0.72.0
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.3
vsliveshare|ms-|1.0.5788
material-icon-theme|PKi|4.23.0
prisma|Pri|4.7.1
vscode-thunder-client|ran|2.2.0
java|red|1.13.0
LiveServer|rit|5.7.9
assembly-8086|Ron|1.0.1
pdf|tom|1.2.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by PBW99** [comment]
me too. same version

**Comment by Bryson-Tai** [comment]
same here, copilot icon at the right bottom corner is missing
it didn't work as usual

**Comment by Maggy30ev** [comment]
.

**Comment by mrcaidev** [comment]
Same on WSL2 with latest VSCode. The right buttom icon quickly flashes and disappears, and no suggestion is shown

**Comment by PBW99** [comment]
copilot extension version v1.63.7601 works now

**Comment by Coxxs** [comment]
![image](https://user-images.githubusercontent.com/3007303/208231792-22556843-f840-43b7-9786-6265222a67f6.png)

**Comment by Agamer12** [comment]
Same issue. A fix for now is to install 1 version older that worked for me :)

**Comment by mrcaidev** [comment]
Latest version (1.65.7705) of Copilot extension also works 👍

**Comment by Bryson-Tai** [comment]
> same here, copilot icon at the right bottom corner is missing it didn't work as usual

Updated: Latest Copilot Extension is working now
