### ISSUE TITLE
Click the run button for a test causes the explorer to switch to the files explorer

### ISSUE THREAD

**Issue by brettcannon** [microsoft/vscode#169409]
# Issue

## Steps to reproduce:

https://user-images.githubusercontent.com/54418/201782804-fcfbd192-61b0-47ac-821f-ad9b314ec8d8.mov

# Diagnostic data

-   Python version (& distribution if applicable, e.g. Anaconda): 3.11.0
-   Type of virtual environment used (e.g. conda, venv, virtualenv, etc.): Venv
-   Value of the `python.languageServer` setting: Pylance

<details>

<summary>Output for <code>Python</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Python</code>)
</summary>

<p>

```
XXX
```

</p>
</details>

<details>

<summary>User Settings</summary>

<p>

```

languageServer: "Pylance"

linting
• enabled: false

formatting
• provider: "black"

testing
• pytestArgs: "<placeholder>"
• pytestEnabled: true
• autoTestDiscoverOnSaveEnabled: false

experiments
• optInto: ["All"]

```

</p>
</details>

**Comment by connor4312** [comment]
Duplicates https://github.com/microsoft/vscode/issues/165500
