### ISSUE TITLE
show uniq references in some way js/ts

### ISSUE THREAD

**Issue by xenoterracide** [microsoft/vscode#169411]
There has to be some way of showing if 2 objects are reference equal in the debugger window for js/ts. I don't know if v8 has reference ids like Java, maybe it doesn't, but there's got to be a way to show, these are the same reference. It's hard to debug some problems when you can't see that easily.

sorry if this is in the wrong repo, has been somehow asked for before, or is impossible due to how v8 works.

**Comment by roblourens** [comment]
You can just run `x === y` in the debug console, or as a watch. But there is no object ID in v8
