### ISSUE TITLE
ERR_FILE_NOT_FOUND for nls.js and editorSimpleWorker.js

### ISSUE THREAD

**Issue by ramya-rao-a** [Microsoft/vscode#16956]
- VSCode Version: 1.8 insiders dated 12/8 around 2PM PST
- OS Version: Any

Steps to Reproduce:

1. Open a workspace and then open any file

![image](https://cloud.githubusercontent.com/assets/16890566/21033986/59f80a76-bd69-11e6-8258-9ebfe1ae833b.png)

**Comment by ramya-rao-a** [comment]
Notice the `/` in the beginning of the file path

`/C:/Program%20Files%20(x86)/Microsoft%20VS%20Code%20Insiders/resources/app/out/vs/base/worker/vs/nls.js`

**Comment by kieferrm** [comment]
The files that it tries to load are actually missing on the file system.

**Comment by alexandrudima** [comment]
Dup of #16953
