### ISSUE TITLE
high contrast mode - links in tooltips unreadable

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16951]
![image](https://cloud.githubusercontent.com/assets/762848/21030013/259ee85c-bd51-11e6-98e5-39ac525c22a4.png)

**Comment by mjbvz** [comment]
While not as bad as in high contrast mode, link color is also too dark IMO with the dark themes: 

![screen shot 2016-12-08 at 5 17 16 pm](https://cloud.githubusercontent.com/assets/12821956/21034127/309d0edc-bd6a-11e6-902d-be38a34de46e.png)

**Comment by joaomoreno** [comment]
They are in _**super**_ high contrast.
