### ISSUE TITLE
November 2022 Recovery 2

### ISSUE THREAD

**Issue by aeschli** [microsoft/vscode#169520]
- [x] Create a milestone `November 2022 Recovery 2` **@aeschli**
- [x] Bump the version number **@aeschli**
- [x] [🔖candidate issues](https://github.com/issues?utf8=✓&q=is%3Aissue+label%3Acandidate+repo%3Amicrosoft%2Fvscode+repo%3Amicrosoft%2Fvscode-internalbacklog+repo%3Amicrosoft%2Fvscode-remote-release+milestone%3A%22November+2022+Recovery+2%22)
- [x] Assign candidate issues to the recovery milestone **team**
- [x] Review the `candidate` issues, and if they pass the review assign them to the recovery milestone **team**
- [x] All `candidate` fixes are peer reviewed and pushed to `main` and then cherry-picked into the release branch **team**
- [ ] Initiate `insiders` build from `main`
- [ ] Issues are tested in the `insiders` **team**
- [x] Build `stable` for all platforms from release branch **@aeschli**
- [ ] Issues are verified on `stable` build and the `verified` label is added **@aeschli**
- [ ] Check `https://github.com/Microsoft/vscode/compare/release/<x.y>` to ensure no other commits have been made in the release branch **@aeschli**
- [ ] Update the release notes and include a link to a query for the fixed issues **@gregvanl**
- [ ] Sanity check of installable bits ([server instructions](https://github.com/microsoft/vscode-remote-release/wiki/Sanity-Check-VS-Code-Servers))
  - [x] Windows 32 bit **@joaomoreno**
    - [x] signed installer 32-bit
    - [x] signed user installer 32-bit
    - [x] zip 32-bit
    - [x] server 32-bit
  - [x] Windows 64 bit **@joaomoreno**
    - [x] signed installer 64-bit
    - [x] signed user installer 64-bit
    - [x] zip 64-bit
    - [x] server 64-bit
    - [x] cli 64-bit
  - [x] Windows ARM64 **@chrmarti**
    - [x] signed installer ARM64
    - [x] signed user installer ARM64
    - [x] zip ARM64
    - [x] cli ARM64
  - [x] macOS
    - [x] Intel + Universal **@isidorn**
    - [x] cli Intel
    - [x] Apple Silicon + Universal **@jrieken**
    - [x] cli Silicon
  - [x] Linux x64 **@aeschli**
    - [x] deb 
    - [x] rpm 
    - [x] archives
    - [x] snap (`sudo snap install --classic --dangerous <file>.snap`)
    - [x] cli
  - [x] Linux server **@chrmarti**
    - [x] x64
    - [x] x64 Alpine
    - [x] ARM32
    - [x] ARM64
    - [x] ARM64 Alpine
- [x] Publish website **@gregvanl**
- [x] Publish stable build **@aeschli**
- [x] Create an official release **@aeschli**
  - [x] Create a tag (make sure you pull the release branch first): `git tag <x.y.z> release/<x.y>`
  - [x] Push the tag: `git push origin <x.y.z>`
  - [x] Create a GitHub release: [Open the GitHub tags](https://github.com/microsoft/vscode/tags), and click far right `... > Create Release`. Use the correct title and description from our release notes. [Example](https://github.com/microsoft/vscode/releases/tag/1.39.1)
- [x] Close the milestone on [GitHub](https://github.com/microsoft/vscode/milestones) **@aeschli**

**Comment by gjsjohnmurray** [comment]
Candidate Issues link (third item in checklist) filters to the wrong milestone. Please update it.

**Comment by aeschli** [comment]
1.74.2 is released! :rocket: 
Thank you all for the great efforts and happy new year!
