### ISSUE TITLE
Source Control - warning label alignment issue

### ISSUE THREAD

**Issue by lszomoru** [microsoft/vscode#169542]
Source control warning not aligned on the right hand side with the input field:

<img width="473" alt="image" src="https://user-images.githubusercontent.com/3372902/208443415-ae750d96-c559-4652-a0ab-604740d02651.png">

**Comment by daviddossett** [comment]
Draft PR here but I feel that there is a better way. For whatever reason the editor within SCM input is not as wide as the input it is rendered in—or something like that. Open to ideas!

https://github.com/microsoft/vscode/pull/172961

**Comment by lszomoru** [comment]
Here is the updated layout:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/3372902/233021045-dcc99e12-d123-4d25-afbc-6c795656910e.png">
