### ISSUE TITLE
Keytar dead

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/vscode#169503]
Type: <b>Bug</b>

1.  Go to https://github.com/atom/node-keytar
2.  Keytar is archived

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.14GB free)|
|Process Argv|--crash-reporter-id 1c76e9ce-b4db-4184-9553-515883ccf6dd|
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
better-comments|aar|3.0.2
emojisense|bie|0.9.1
markdown-emoji|bie|0.3.0
vscode-tailwindcss|bra|0.9.1
gitignore|cod|0.9.0
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
git-cheatsheet|dzh|1.4.4
vscode-todo-plus|fab|4.19.0
todo-tree|Gru|0.0.220
vscode-guid|hea|1.7.0
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
vscode-remote-extensionpack|ms-|0.23.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.3
cmake|twx|0.0.17
errorlens|use|3.6.0
change-case|wma|1.0.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by TylerLeonhardt** [comment]
That's just from the Atom sunsetting. It will live on in a new home, but where that new home is is not yet decided. More info should come in the new year.
