### ISSUE TITLE
Delay when loading "Docker Containers using [Docker Extension]"

### ISSUE THREAD

**Issue by molecula451** [microsoft/vscode#169513]
Does this issue occur when all extensions are disabled?: Yes/No

Using Docker Extension

Steps to Reproduce:

1. Use Docker Extension to Load Containers

**Comment by molecula451** [comment]
am still debugging this one, this doesn't seem to happen when you are over dockerized TCP, however, it seems to happen locally

**Comment by chrmarti** [comment]
/causedByExtension

This is caused by Docker or the Docker extension. Please file a new issue for it: https://github.com/microsoft/vscode-docker/issues
