### ISSUE TITLE
Make soft text wrapping easier discoverable

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#1695]
We are receiving regular questions about how to enable soft text wrapping. See also the discussion in #342.

> Open Settings and add  "editor.wrappingColumn": 0 .

**Comment by egamma** [comment]
CC @Tyriar

**Comment by Tyriar** [comment]
:+1:

https://github.com/Microsoft/vscode/issues/324 is the issue with the discussion

**Comment by ctlajoie** [comment]
How are you guys thinking thinking this would be implemented? Would this menu item to toggle soft wrap (referenced from #324) only affect the currently opened document? Besides that, the only other thing I think you can do is to directly modify the user's settings.json file.

Regarding discoverability (with no disrespect or condescension intended), the typical way to modify settings in Code is with the settings.json file. If I were looking for a setting to wrap text, that's where I would look first.

**Comment by Tyriar** [comment]
Personally I'd want it exposed through the view menu and potentially with a hotkey (something like <kbd>ctrl</kbd>(+<kbd>shift</kbd>?)+<kbd>w</kbd>). I would also want it to just affect the present file until it's closed or removed from working files.

**Comment by ctlajoie** [comment]
Makes sense.. user settings are applied globally, but line wrapping is something that perhaps most people would only want to enable temporarily, and only on a specific file. What you suggested would accomplish that.

**Comment by felixfbecker** [comment]
I would also like to see this. Sometimes you want to quickly toggle this on and off. It makes sense to have a default setting but similar to how you can quickly switch between spaces/tabs now, a wrapping icon would make sense. For example, in Markdown / plain text I mostly want wrapping, while in code I don't like it.

**Comment by egamma** [comment]
There is an action to toggle word wrap in the View menu and there is a short cut - closing.

**Comment by felixfbecker** [comment]
lol totally overlooked that
