### ISSUE TITLE
broken typescript intellisesne on `tsconfig.strict = true`

### ISSUE THREAD

**Issue by qundus** [microsoft/vscode#169541]
Does this issue occur when all extensions are disabled?: Yes/No
Yes

- VS Code Version: 1.74.1
- OS Version: 6.0.12-artix1-1, Artix Linux x86_64, bash 5.1.16

Steps to Reproduce:

1. create a new typescript project
2. set `strict=true` in `tsconfig.json`
3. create a typescript file and hover over any object to trigger intellisense
4. watch intellisense `Loading...` forever

Example:
<div align="center">
  <video loading="lazy" controls src="https://user-images.githubusercontent.com/72963129/208442201-0906abd4-c080-425d-ae6d-0d172fd1865d.mp4"></video>
</div>

**Comment by IllusionMH** [comment]
Please provide code example that triggers this behavior.
Or check TSServer logs for errors (need to enable it first).

**Comment by mjbvz** [comment]
Closing as we need example code to investigate this issue
