### ISSUE TITLE
Unit test failure: TerminalLinkDetector

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#169533]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=197333&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=3a692518-c3cf-5f6a-c273-72f71dc185fb

**Comment by chrmarti** [comment]
https://dev.azure.com/monacotools/Monaco/_build/results?buildId=197359&view=logs&j=55ac390b-ffb1-50ea-3650-525dd9a3fd80&t=c01b9029-2b08-503e-eba8-b45cf5956c33&l=17416

**Comment by Tyriar** [comment]
These flakes are a bit odd, not sure what could cause them and the failures seem a bit all over the place 🤔

**Comment by Tyriar** [comment]
I added some logs that will help with debugging future failures. Closing in the meantime until a new one pops up.
