### ISSUE TITLE
Go to definition is showing up when I ctrl+click a link in a markdown file

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169593]
The content of the line:

```md
- Improvements to help debug local link detector unit tests https://github.com/microsoft/vscode/pull/169573
```

Open definition does nothing

![Recording 2022-12-19 at 16 56 38 (1)](https://user-images.githubusercontent.com/2193314/208556564-b3e84ebb-031b-4162-a980-f225d4b3d14c.gif)

**Comment by stevebrownlee** [comment]
Also happens on Mac with Cmd+Click. Makes it very difficult to navigate my documentation.

**Comment by mjbvz** [comment]
@jrieken I believe this is a result of fixing #147447

Markdown has a link provider and a definition provider. However in this case, the definition provider returns `undefined` since we are not on a reference link

**Comment by jrieken** [comment]
revert of the bad change is up
