### ISSUE TITLE
"edit" button for settings not discoverable

### ISSUE THREAD

**Issue by mousetraps** [Microsoft/vscode#16950]
Currently you have to know where it is in order for it to appear. You should be able to hover anywhere in order to trigger the setting(setting name, comment, or value), not just on the invisible pencil 
![image](https://cloud.githubusercontent.com/assets/762848/21029929/db8c9a5c-bd50-11e6-8fe0-ffbad2722f92.png)

**Comment by sandy081** [comment]
Got fixed with #17292
