### ISSUE TITLE
reusable run/debug buttons without need to find main file(solution:  add history of runs to run part)

### ISSUE THREAD

**Issue by loveyandex** [microsoft/vscode#169606]
### Problem
we are bothering to run or rerun a main file of python/go/js ...  when working in other files 

but run file is fixed so we want a UI/UX to be on our looks to see it for click
not finding main file inside of other files then going to menu to run

### solution

add history of runs to run part
![image](https://user-images.githubusercontent.com/53381292/208602005-6ebf2611-9a26-4f18-8aea-c6fdc5b21c2c.png)

**Comment by roblourens** [comment]
In this case, the best solution for you is probably to create a launch.json file with your preferred run configurations in it, then you can see your configs and run them from anywhere.
