### ISSUE TITLE
Clarify usage of CancellationError

### ISSUE THREAD

**Issue by Colengms** [microsoft/vscode#169698]
In [the VS Code API Docs, `CancellationError`](https://code.visualstudio.com/api/references/vscode-api#CancellationError) is described in such a way that it appears to be applicable almost anywhere, not just in response to a canceled `CancellationToken`.  Could we get some clarification in the docs regarding which specific providers(?) support throwing a `CancellationError` to abort and not cause an error to be logged?

`CancellationError` was originally only applicable to semantic tokens.  https://github.com/microsoft/vscode/issues/93686  That is also mentioned [in this issue](https://github.com/microsoft/vscode/issues/125799), and that it's not supported by `FoldingRangeProvider`.

I recently tested this with various provider classes and saw that `CodeActionProvider` and `DocumentSymbolProvider` would log errors when it was used, but `FoldingRangeProvider` and `InlayHintsProvider` would not.  However, today I'm unable to reproduce any logged errors for `CancellationError` with 1.74.2, from any of our providers.

When thrown from the following providers: `ReferenceProvider`, `RenameProvider`, `DocumentFormattingEditProvider`, `DocumentRangeFormattingEditProvider`, `OnTypeFormattingEditProvider`

... it appears to be uncaught, as it's flagged by the debugger as an uncaught exception.  However, for `RenameProvider`, it does also trigger a `Canceled` message box, so does seem to be handled.

![image](https://user-images.githubusercontent.com/49173979/208784798-1fca4e26-d3d9-47b0-a1f5-96309b108cba.png)

Generally speaking, we'd like to throw `CancellationError` any time we know that a provider operation could not be successfully completed due to being cancelled by VS Code or cancelled due to a conflicting operation in our own extension, rather than returning an empty result.  Hypothetically, an empty result could be interpreted by VS Code as a valid result, which may not be desirable.

**Comment by jrieken** [comment]
> ... it appears to be uncaught, as it's flagged by the debugger as an uncaught exception.

Unsure how the debugger decides that, logically all language features should be using the `_withAdapter`-wrapper and that should handle (and pass on) [cancellation errors](https://insiders.vscode.dev/github/microsoft/vscode/blob/1d73bc45c2060131e1877a539deb68ed1f873e2e/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1787-L1792)

> However, for RenameProvider, it does also trigger a Canceled message box, so does seem to be handled.

Yeah, most cancellation is silent but something like rename (and maybe others) tell the user about the operating being aborted. 

The gist is that all language operations are cancellable and that it is OK to throw the cancellation error*. In fact we do that automatically by racing against the provided token (see [these lines](https://insiders.vscode.dev/github/microsoft/vscode/blob/1d73bc45c2060131e1877a539deb68ed1f873e2e/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1799-L1801))

<sup>*</sup> The asterisks here is that most providers (unless spelled out like semantic tokens) have no result in the face of cancellation, e.g if during outline compute cancellation happens then there is no outline, we don't reuse an existing previous outline etc. I am happy to revisit these on a case by case basis, I think more "stateful cases" like outline, code lens, inlays, folding good be handling cancellation smarter (by trying to reuse an existing result) but for other like go-to-def, find symbols etc it OK to discard all data

**Comment by jrieken** [comment]
@Colengms Is your question answered? Do you have a case where throwing a cancellation error does something wrong or unexpected?

**Comment by Colengms** [comment]
> The gist is that all language operations are cancellable and that it is OK to throw the cancellation error

Thanks @jrieken .  We'll switch to throwing CancellationError from all of our providers on cancel.  If we run into any problems with that, we'll open specific issues.  Closing this one.
