### ISSUE TITLE
Telemetry extractor job fails

### ISSUE THREAD

**Issue by bpasero** [microsoft/vscode#169617]
Telemetry extractor job fails: https://github.com/microsoft/vscode/actions/runs/3738971695/jobs/6345642907

![image](https://user-images.githubusercontent.com/900690/208626391-25b72236-86aa-43d7-b2da-b92a8c78ccd1.png)

**Comment by lramos15** [comment]
@TylerLeonhardt And I saw this and investigated, but have no idea why it fails. The extractor outputs debug info as it runs and there is no output here leading me to think what is failing is actually the package download from the npm registry. @lszomoru any thoughts?

**Comment by lszomoru** [comment]
You can launch the pipeline with the "Enable System Diagnostics" option which is in the lower left-hand side of the panel when you queue a new build. Hopefully that would provide a bit more information of what is happening. Another potential cause of failure is that these pipelines still have Terrapin enabled so I wonder if that has anything to do with it.

**Comment by lramos15** [comment]
Thanks for the tip, I haven't enabled this just because of how noisy things will be, but if you see this fail please check the `Enable Debug Logging` option when re-running the failed job. So far I have not seen it fail after a re-run so still am unsure of the error.
