### ISSUE TITLE
code-insiders global search doesnt return same results as grep

### ISSUE THREAD

**Issue by noahehall** [microsoft/vscode#169656]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:

```sh
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
``` 

- OS Version:  `- 1.75.0-insider`

Steps to Reproduce:

1.  open global search
2.  search for something like $1 scoped to a directory: limited results
3.  run the same search in grep like `grep -iR '$1' .`: alot of results

> example repo: https://github.com/nirv-ai/scripts

![image](https://user-images.githubusercontent.com/10324554/208714560-b080f271-e4be-4db9-90ed-7ba9751ef7aa.png)

> same search via grep

![image](https://user-images.githubusercontent.com/10324554/208714769-a2cf7307-3c73-4453-9b38-12a5531f17f2.png)

## code-insiders --status
![image](https://user-images.githubusercontent.com/10324554/208715116-aeafb95d-6030-4b04-a0e6-47239b431ff2.png)

**Comment by andreamah** [comment]
Do you get more results if you disable exclusions?
![image](https://user-images.githubusercontent.com/31675041/208726452-5d763f2f-1893-4b4d-9e56-8f86e9408b40.png)

**Comment by noahehall** [comment]
@andreamah that worked! thanks
