### ISSUE TITLE
Showing two borders if ctrl + hover on the imported path in ts file

### ISSUE THREAD

**Issue by abhijitchikane** [microsoft/vscode#169628]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.1
- OS Version: Windows

Steps to Reproduce:

1. ctrl + hover on the import path
2. check the bottom border

![image](https://user-images.githubusercontent.com/50770619/208658859-b9812ea4-cd92-4a96-9b15-daefefa47f70.png)

**Comment by mjbvz** [comment]
I haven't been able to reproduce this. My guess is that it has already been fixed or was caused by an extension
