### ISSUE TITLE
Ctrl+Click not working anymore, instead Alt+Click does

### ISSUE THREAD

**Issue by ad-on-is** [microsoft/vscode#169637]
```
Version: 1.74.1
Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a
Date: 2022-12-14T10:35:03.979Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.12-arch1-1
Sandboxed: No
```

I noticed that suddenly <kbd>Ctrl+Click</kbd> does not trigger clicks anymore, but instead <kbd>Alt+Click</kbd> does. 
This is true for **go to definition** or clicking on any link.

How can I change that back?

**Comment by jrieken** [comment]
Sure that you or some extension didn't fiddle with the `editor.multiCursorModifier` setting?
