### ISSUE TITLE
Snippets should appear first with IntelliSense

### ISSUE THREAD

**Issue by pierredewilde** [Microsoft/vscode#16962]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0
- Extensions: none

**Steps to Reproduce:**
1. create a new JavaScript or TypeScript file
2. type `if` followed by `<Tab>` : nothing appears (same for `switch` `while` `for` ...)

**Reason:**
Snippets are located at the bottom of the list in IntelliSense

**Proposed solution:**
By placing snippets on top of the list in IntelliSense, typing `if` followed by `<Tab>` should work as expected.

**Comment by jrieken** [comment]
This is control by a setting. You get sort snippets to the bottom, top, inline, or hide them from IntelliSense. For your case that is `"editor.snippetSuggestions": "top"`.
