### ISSUE TITLE
Extend Screen

### ISSUE THREAD

**Issue by Slimand** [microsoft/vscode#169625]
Type: <b>Feature Request</b>

Greetings
I want to drop an open tab into a second screen..but the program doesnt allow me to do that..is this option not exist in vs code..
and if not ,could you please include this option into the next release..
it is a pitty if this option not exist...its very helpful to drop an open tab into a second monitor

and best of luck..
Sliman

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:30:51.966Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

**Comment by sbatten** [comment]
duplicate 
https://github.com/microsoft/vscode/issues/10121
