### ISSUE TITLE
Python debugger doesn't import local files in vs code

### ISSUE THREAD

**Issue by david26694** [microsoft/vscode#169640]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: Version: 1.74.1 (Universal)

- OS Version: macOS Big Sur, Version: 11.3.1 (20E241) Commit: 1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a

Steps to Reproduce:

1. `mkdir folder_structure`
2. `mkdir folder_structure/utils`
3. `touch folder_structure/utils/tools.py`
4. `touch folder_structure/main.py`
5. Write in main.py:
```python
from folder_structure.utils.tools import dummy

if __name__ == '__main__':
    dummy()
```
6. Write in tools.py:
```python
def dummy():
    print("Dummy")
```
7. Run the vs code debugger

I'm getting:
```
Exception has occurred: ModuleNotFoundError
No module named 'folder_structure'
  File "/Users/davidmasip/Documents/Others/python-scripts/folder_structure/main.py", line 1, in <module>
    from folder_structure.utils.tools import dummy
```

I have the following in my launch.json:
```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Python: Current File",
            "type": "python",
            "request": "launch",
            "program": "${file}",
            "console": "integratedTerminal",
            "env": {
                "PYTHONPATH": "${workspaceRoot}"
            }
        }
    ]
}
```

How can I import a local module when using the debugger?

This works for me:
```bash
python -m folder_structure.main   
```

**Comment by roblourens** [comment]
Please file this issue on the vscode-python extension's repo: https://github.com/microsoft/vscode-python/issues, thanks
