### ISSUE TITLE
Clicking in Comments view should expand the comment

### ISSUE THREAD

**Issue by Drarig29** [microsoft/vscode#169620]
Currently, I rely on the Comments view a lot (it has nice icons for resolve or not, a nice badge, etc. ❤️ ).

Single clicking a comment in this view will only reveal the correct file, and maybe it's right to not also expand/reveal the comment. 
But sometimes, the comment is collapsed (or all are collapsed), and I have to click (sometimes twice, it's not even a double click) the gutter icon to show it.

Instead of having to move the mouse to the gutter, I would rather double click the comment directly in the Comments view.

**Comment by eleanorjboyd** [comment]
How does one access the `Comments view` section?

**Comment by alexr00** [comment]
To verify:
1. Open a workspace with comment. For example, install the GitHub Pull Request extension then check out a pull request with comments.
2. Open the Comments view (command Comments: Focus on Comments View)
3. Click on comments in the Comments view and verify that they open the editor and expand the comment in the editor if it's collapsed.
