### ISSUE TITLE
No blue button selection framing

### ISSUE THREAD

**Issue by OleksandrKvl** [microsoft/vscode#169630]
Does this issue occur when all extensions are disabled?: don't know how to disable them via command line on Mac

- VS Code Version: 1.74.1
- OS Version: Darwin arm64 21.6.0

Steps to Reproduce:

1. Go to **Mac OS** Settings -> Keyboard -> Shortcuts. Enable `Use keyboard navigation to move focus between controls`.
2. Open any dialogue which contains grey and blue buttons. Maybe colors are different on different color themes. For example, for file removal confirmation it's button `Delete`, not `Cancel`.
3. Navigate to blue button using keyboard.
4. There's no framing around it, it looks like no button is actually selected.

Here's how both buttons being selected look in VSCode:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/37271580/208660326-2bb54c50-6762-4461-9cc9-ec6bad996935.png">
<img width="270" alt="image" src="https://user-images.githubusercontent.com/37271580/208660382-4e095dc6-d30c-49ac-8022-a9b0c192b57c.png">

And in the native dialogue:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/37271580/208660443-5ba8ecf5-b345-4e10-97a0-56035360db13.png">
<img width="263" alt="image" src="https://user-images.githubusercontent.com/37271580/208660472-c909ac96-ec67-4140-a251-2981eb8718a7.png">

**Comment by bpasero** [comment]
Pretty cool catch, I can actually reproduce and even with Electron Fiddle (using Electron 19) and the following example I see the outline over the blue button:

```js
const { app, BrowserWindow, dialog } = require('electron')

app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({ height: 600, width: 600 })

  // Show an "Open File" dialog and attempt to open
  // the chosen file in our window.
   dialog.showMessageBox(mainWindow, {
        'type': 'question',
        'title': 'Confirmation',
        'message': "Are you sure?",
        'buttons': [
            'Yes',
            'No'
        ]
    })
})
```

<img width="289" alt="image" src="https://user-images.githubusercontent.com/900690/208747308-8d128fd8-e686-4836-94a8-d9be0337ee3a.png">

**Comment by bpasero** [comment]
Actually nevermind, that above example seems to work fine at least when running out of sources. I wonder if our internal builds have something?

**Comment by deepak1556** [comment]
I tried the above fiddle with Electron bits from https://github.com/microsoft/vscode-electron-prebuilt but it works fine. So the issue is not with internal builds but rather whether the application is running as packaged or not. Wonder if it needs some entitlement ?

**Comment by bpasero** [comment]
This is likely an Electron issue, following Fiddle reproduces:

```js
const { app, BrowserWindow, dialog } = require('electron')

app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({ height: 600, width: 600 })

  // Show an "Open File" dialog and attempt to open
  // the chosen file in our window.
  dialog.showMessageBox(mainWindow, {
    buttons: [
      "ButtonA",
      "ButtonB"
    ],
    message: "Some message",
    defaultId: 0
  }).then(result => {
    if (result.canceled) {
      console.log('Dialog was canceled')
    } else {
      const file = result.filePaths[0]
      mainWindow.loadURL(`file://${file}`)
    }
  }).catch(err => {
    console.log(err)
  })
})
```

So it seems to be related which button labels are used and if a `defaultId` is applied. With the simple `Yes` and `No` buttons, the one button seems to be default by default and maybe that has an impact.

**Comment by bpasero** [comment]
Reported as https://github.com/electron/electron/issues/36721

**Comment by deepak1556** [comment]
Thanks for narrowing down the issue @bpasero :)

**Comment by OleksandrKvl** [comment]
Looks like it finally works as expected on 1.78.0, I think someone from Code team can close this issue now.
