### ISSUE TITLE
enable `css.format.spaceAroundSelectorSeparator` in workspace settings for repo

### ISSUE THREAD

**Issue by andreamah** [microsoft/vscode#169664]
The default is `css.format.spaceAroundSelectorSeparator: false`, which is annoying when I have `format on save` enabled and most of the codebase has spaces between separators in css files. 

I see that only 12 files have no spaces between `>` 
<img width="537" alt="image" src="https://user-images.githubusercontent.com/31675041/208727641-92c2e08b-9e10-410c-99d1-4ce53b1da0f9.png">

**Comment by bpasero** [comment]
👍 for a consistent style in our code base. I would convert the 12 files to use spaces, they have been likely converted by accident.

**Comment by bpasero** [comment]
Thanks!
