### ISSUE TITLE
[TypeScript] Interface's function properties are shown twice in autocomplete pop-up

### ISSUE THREAD

**Issue by ffxsam** [microsoft/vscode#169679]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: macOS 12.6

Steps to Reproduce:

1. Paste the below code into a TypeScript file and save it.
2. Navigate into the options object being passed into `wow()` and hit ctrl-space to autocomplete.

Result: Any properties that are functions are shown twice.

```ts
interface Opts {
  operation: () => Promise<void>;
  afterDelete?: () => void;
  afterFail: (exception: unknown, list: any[]) => void;
  beforeDelete: (list: any[]) => void;
  itsOk: boolean;
}

function wow(s: Opts): number {
  return 0;
}

wow({

});
```

<img width="479" alt="CleanShot 2022-12-20 at 14 47 17@2x" src="https://user-images.githubusercontent.com/12532733/208763703-9336049d-9324-40c5-a8e1-4f6d9255c056.png">

**Comment by captain-eddie** [comment]
I believe I have found the root of the bug in:
\src\vs\editor\contrib\suggest\browser\suggest.ts
I am currently working on a solution.

**Comment by mjbvz** [comment]
This looks expected. The first item completes just method name, the second item will complete the entire method signature 

You can use `javascript.suggest.classMemberSnippets.enabled` and `typescript.suggest.classMemberSnippets.enabled` to disable the second type of completion if you want
