### ISSUE TITLE
[loc][Query][VSCode] Please clarify the placeholder

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#16969]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Paused on {0}

File Name:
src\vs\workbench\parts\debug\electron-browser\debugViewer.nls.resx

Resource ID:
".resx", 0; "pausedOn"

Query:
We need to know the content of the placeholder. Can you please also give an example? Thanks!	Lemoine	11/16/2016 5:29:55 PM

**Comment by isidorn** [comment]
indicates reason for program being paused
for instance Paused on Breakpoint. Paused on Step
