### ISSUE TITLE
Free port quick fix only matches the first expression

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#169695]
It looks for the portNumber named capture group:

https://github.com/microsoft/vscode/blob/e34dfe658c39ed709d28bb6dbfee8300be3d5acd/src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts#L100

But only the first is named:

https://github.com/microsoft/vscode/blob/e34dfe658c39ed709d28bb6dbfee8300be3d5acd/src/vs/workbench/contrib/terminal/browser/terminalQuickFixBuiltinActions.ts#L15

**Comment by chrisdias** [comment]
it looks like i have this problem on Windows, not on Mac.  On my mac, it finds the match and I get the quick fix to restart the app/free the port.

**Comment by Tyriar** [comment]
Easy way to test this without running a process:

```sh
echo "address already in use localhost:3000" && fail
echo "address already in use :::3000" && fail
echo "can't listen on port 3000" && fail
etc.
```
