### ISSUE TITLE
vs code crash and stuck

### ISSUE THREAD

**Issue by manishsingh-rzp** [microsoft/vscode#169604]
Type: <b>Bug</b>

Cant force quit and open vs code .It was stuck

VS Code version: Code 1.74.1 (Universal) (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:33:40.793Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|6, 12, 7|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|--enable-proposed-api TabNine.tabnine-vscode --crash-reporter-id 7ba352b3-1305-4a0e-a9b9-a7451a363220|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (36)</summary>

Extension|Author (truncated)|Version
---|---|---
interactive-scala|als|1.5.0
denigma|den|0.0.15
scala-lsp|dra|0.2.3
gitlens|eam|13.1.1
code-runner|for|0.11.8
codespaces|Git|1.13.5
vscode-sbt-scala|lig|0.2.4
file-downloader|min|1.0.12
mindaro|min|1.0.120221201
vscode-docker|ms-|1.23.3
vscode-kubernetes-tools|ms-|1.3.11
isort|ms-|2022.8.0
python|ms-|2022.21.13491005
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
scala-gurus|rav|1.0.0
fabric8-analytics|red|0.3.6
java|red|1.13.0
vscode-xml|red|0.23.0
vscode-yaml|red|1.10.1
scala|sca|0.5.6
scala-snippets|sca|0.1.0
metals|sca|1.20.0
tabnine-vscode|Tab|3.6.31
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
material-theme|zhu|3.15.6

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by manishsingh-rzp** [comment]
main.log
`2022-12-20 10:36:09.704 [info] update#setState idle
2022-12-20 10:36:10.630 [error] vscode-file: Refused to load resource /private/var/folders/2f/vwh2ksd93v990l_g8dcq3fcm0000gq/T/AppTranslocation/8633A07A-5FFD-49E3-8B40-C62FC4F4D36C/d/Visual Studio Code.app/Contents/Resources/app/extensions/theme-seti/icons/seti.woff from vscode-file: protocol (original URL: vscode-file://vscode-app/private/var/folders/2f/vwh2ksd93v990l_g8dcq3fcm0000gq/T/AppTranslocation/8633A07A-5FFD-49E3-8B40-C62FC4F4D36C/d/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/theme-seti/icons/seti.woff)
2022-12-20 10:36:10.876 [info] UtilityProcess<1>: Creating new...
2022-12-20 10:36:10.884 [info] UtilityProcess<1>: received spawn event.
2022-12-20 10:36:39.711 [info] update#setState checking for updates
2022-12-20 10:36:40.109 [info] update#setState idle`

**Comment by chrmarti** [comment]
Does the UI still work (except for Quit) or did it crash entirely? If it crashed please create a crash dump and share it with us: https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by manishsingh-rzp** [comment]
This was caused due to a plugin .. removed plugin after laptop restart . Works fine now .
