### ISSUE TITLE
VS Code crashes when trying to access the `ExtensionContext.secret` API

### ISSUE THREAD

**Issue by s2terminal** [microsoft/vscode#169693]
### Applies To

- [X] Notebooks (.ipynb files)
- [ ] Interactive Window and\/or Cell Scripts (.py files with \#%% markers)

## Reproduction procedure

1. Open a notebook file.
2. In the VS Code command palette, enter the following command
3. `>Jupyter: Specify Jupyter Server for Connections`
4. Connect to an appropriate server (e.g. http://localhost:8888)
5. VS Code is forced to terminate.

It is also reproduced by opening a VS Code project with the notebook file once connected.

Reproduced with VS Code 1.72.
VS Code 1.71 does not reproduce this issue.

Using VS Code for Linux.

### VS Code Version

1.72

### Jupyter Extension Version

v2022.9.1202862440

### Jupyter logs

```shell
no logs
```

**Comment by chrmarti** [comment]
Could you create a crash dump and share that with us? https://github.com/microsoft/vscode/wiki/Native-Crash-Issues

**Comment by bpasero** [comment]
@deepak1556 there are 2 crashes and the stack is as follows.

**Crash 1**
```
Operating system: Linux
                  3.10.0 -1160 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64
CPU: amd64
     family 6 model 142 stepping 12
     8 CPUs

GPU: UNKNOWN

Crash reason:  DUMP_REQUESTED
Crash address: 0x0
Process uptime: 30 seconds

Thread 2 (crashed)
 0  code!crash_reporter::DumpWithoutCrashing() [crashpad.cc : 279 + 0x1a]
    rax = 0x00007f8b73bf5120   rdx = 0x00007f8b73bf54c0
    rcx = 0x00007f8b73bf54c0   rbx = 0x00007f8b73bf5120
    rsi = 0x00000000000000aa   rdi = 0x00007f8b73bf5120
    rbp = 0x00007f8b73bf54f0   rsp = 0x00007f8b73bf5120
     r8 = 0x0000000000000000    r9 = 0x00007f8b73bf53af
    r10 = 0x0000000000000014   r11 = 0x0000000000000010
    r12 = 0x00007f8b73bf5570   r13 = 0x000055a18e3e8200
    r14 = 0x0000000011e1a300   r15 = 0xaaaaaaaaaaaaaaaa
    rip = 0x000055a18a36682d
    Found by: given as instruction pointer in context
 1  code!base::debug::DumpWithoutCrashing(base::Location const&, base::TimeDelta) [dump_without_crashing.cc : 81 + 0x6]
    rbx = 0x0000000000000000   rbp = 0x00007f8b73bf5550
    rsp = 0x00007f8b73bf5500   r12 = 0x00007f8b73bf5570
    r13 = 0x000055a18e3e8200   r14 = 0x0000000011e1a300
    r15 = 0xaaaaaaaaaaaaaaaa   rip = 0x000055a18a370f41
    Found by: call frame info
 2  code!gpu::GpuWatchdogThread::DeliberatelyTerminateToRecoverFromHang() [gpu_watchdog_thread.cc : 664 + 0x2c]
    rbx = 0x00007f8b73bf5570   rbp = 0x00007f8b73bf55c0
    rsp = 0x00007f8b73bf5560   r12 = 0x000055a18e3e8388
    r13 = 0x000055a18e3e8278   r14 = 0x00002c7c00222b79
    r15 = 0x00002c7c00222a00   rip = 0x000055a18ba6e9ad
    Found by: call frame info
 3  code!gpu::GpuWatchdogThread::OnWatchdogTimeout() [gpu_watchdog_thread.cc : 495 + 0x8]
    rbx = 0x00002c7c00222a00   rbp = 0x00007f8b73bf5610
    rsp = 0x00007f8b73bf55d0   r12 = 0x0000000000000000
    r13 = 0x00002c7c002f6200   r14 = 0x0000000000000000
    r15 = 0x00007f8b73bf5678   rip = 0x000055a18ba6e083
    Found by: call frame info
 4  code!base::TaskAnnotator::RunTaskImpl(base::PendingTask&) [callback.h : 143 + 0x3]
    rbx = 0x00002c7c003a6000   rbp = 0x00007f8b73bf56a0
    rsp = 0x00007f8b73bf5620   r12 = 0x0000000000000000
    r13 = 0x00002c7c002f6200   r14 = 0x0000000000000000
    r15 = 0x00007f8b73bf5678   rip = 0x000055a18a3c1326
    Found by: call frame info
 5  code!non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() [task_annotator.h : 74 + 0x8]
    rbx = 0x000055a18e3fbb60   rbp = 0x00007f8b73bf5830
    rsp = 0x00007f8b73bf56b0   r12 = 0x0000000000000000
    r13 = 0x00002c7c002f6200   r14 = 0x00002c7c003a6000
    r15 = 0x0000000000000000   rip = 0x000055a18a3de75c
    Found by: call frame info
 6  code!base::MessagePumpDefault::Run(base::MessagePump::Delegate*) [message_pump_default.cc : 39 + 0xb]
    rbx = 0x00002c7c00852428   rbp = 0x00007f8b73bf58a0
    rsp = 0x00007f8b73bf5840   r12 = 0xaaaaaaaaaaaaaaaa
    r13 = 0x00002c7c002f6208   r14 = 0x00002c7c00852430
    r15 = 0x00007f8b73bf5850   rip = 0x000055a18a38c43e
    Found by: call frame info
 7  code!base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) [thread_controller_with_message_pump_impl.cc : 498 + 0x6]
    rbx = 0x00002c7c002f6200   rbp = 0x00007f8b73bf58e0
    rsp = 0x00007f8b73bf58b0   r12 = 0x00002c7c002f62c8
    r13 = 0x7fffffffffffffff   r14 = 0x0000000000000001
    r15 = 0x00002c7c002f62a8   rip = 0x000055a18a3df1e4
    Found by: call frame info
 8  code!base::RunLoop::Run(base::Location const&) [run_loop.cc : 141 + 0x12]
    rbx = 0x00007f8b73bf59f0   rbp = 0x00007f8b73bf59a0
    rsp = 0x00007f8b73bf58f0   r12 = 0x00002c7c00222a10
    r13 = 0x00002c7c00222a00   r14 = 0x00007f8b73bf5958
    r15 = 0x00007f8b73bf59b0   rip = 0x000055a18a3aa6c2
    Found by: call frame info
 9  code!base::Thread::Run(base::RunLoop*) [thread.cc : 334 + 0x2a]
    rbx = 0x00007f8b73bf59f0   rbp = 0x00007f8b73bf59e0
    rsp = 0x00007f8b73bf59b0   r12 = 0x00002c7c00222a10
    r13 = 0x00002c7c00222a00   r14 = 0x00007f8b73bf59b0
    r15 = 0x00007f8b73bf59f0   rip = 0x000055a18a3f8738
    Found by: call frame info
10  code!base::Thread::ThreadMain() [thread.cc : 405 + 0xd]
    rbx = 0x000000000000000b   rbp = 0x00007f8b73bf5a50
    rsp = 0x00007f8b73bf59f0   r12 = 0x00002c7c00222a10
    r13 = 0x00002c7c00222a00   r14 = 0x0000000000000000
    r15 = 0x00007f8b73bf59f0   rip = 0x000055a18a3f88a2
    Found by: call frame info
11  code!base::(anonymous namespace)::ThreadFunc(void*) [platform_thread_posix.cc : 101 + 0x9]
    rbx = 0x00007f8b73bf6700   rbp = 0x00007f8b73bf5a90
    rsp = 0x00007f8b73bf5a60   r12 = 0x00002c7c00254d20
    r13 = 0x0000000000801000   r14 = 0x00007f8b73bf6700
    r15 = 0x00002c7c00222a00   rip = 0x000055a18a41b240
    Found by: call frame info
12  libpthread.so.0 + 0x7ea5
    rbx = 0x0000000000000000   rbp = 0x0000000000000000
    rsp = 0x00007f8b73bf5aa0   r12 = 0x0000000000000000
    r13 = 0x0000000000801000   r14 = 0x0000000000000003
    r15 = 0x00007f8b73bf6700   rip = 0x00007f8b88d3eea5
    Found by: call frame info
13  libc.so.6 + 0xfeb0d
    rsp = 0x00007f8b73bf5b40   rip = 0x00007f8b83b92b0d
    Found by: stack scanning
```


**Crash 2**
Operating system: Linux
                  3.10.0 -1160 #1 SMP Fri Dec 16 17:29:43 UTC 2022 x86_64
CPU: amd64
     family 6 model 142 stepping 12
     8 CPUs

GPU: UNKNOWN

Crash reason:  SIGSEGV /SEGV_MAPERR
Crash address: 0x0
Process uptime: 14 seconds

Thread 15 (crashed)
 0  libc.so.6 + 0x13efd6
    rax = 0x0000000000000000   rdx = 0x0000000000000002
    rcx = 0x0000000000000000   rbx = 0x00003448039a7660
    rsi = 0x0000000000000000   rdi = 0x0000000000000000
    rbp = 0x0000344801d6eac0   rsp = 0x00007f90863ad778
     r8 = 0x0000000000000018    r9 = 0x0000000000000000
    r10 = 0x0000000000000004   r11 = 0x0000000000000005
    r12 = 0x0000000000000002   r13 = 0x00003448006a26a8
    r14 = 0x00003448039a7680   r15 = 0x00007f909a2a0190
    rip = 0x00007f909c6c0fd6
    Found by: given as instruction pointer in context
 1  libcrypto.so.10 + 0x1265b9
    rsp = 0x00007f90863ad780   rip = 0x00007f909a3555b9
    Found by: stack scanning
 2  libcrypto.so.10 + 0x1268a0
    rsp = 0x00007f90863ad7c0   rip = 0x00007f909a3558a0
    Found by: stack scanning
 3  vscode-encrypt-native.node + 0x2c46d0
    rsp = 0x00007f90863ad7d8   rip = 0x00007f90780e46d0
    Found by: stack scanning
 4  vscode-encrypt-native.node + 0x2c46d0
    rsp = 0x00007f90863ad7e8   rip = 0x00007f90780e46d0
    Found by: stack scanning
 5  libcrypto.so.10 + 0x715ff
    rsp = 0x00007f90863ad800   rip = 0x00007f909a2a05ff
    Found by: stack scanning
 6  vscode-encrypt-native.node + 0x2c46d0
    rsp = 0x00007f90863ad808   rip = 0x00007f90780e46d0
    Found by: stack scanning
 7  vscode-encrypt-native.node + 0x1ca240
    rsp = 0x00007f90863ad810   rip = 0x00007f9077fea240
    Found by: stack scanning
 8  vscode-encrypt-native.node + 0x96237
    rsp = 0x00007f90863ad818   rip = 0x00007f9077eb6237
    Found by: stack scanning
 9  vscode-encrypt-native.node + 0x1ca240
    rsp = 0x00007f90863ad820   rip = 0x00007f9077fea240
    Found by: stack scanning
10  vscode-encrypt-native.node + 0x1d0628
    rsp = 0x00007f90863ad840   rip = 0x00007f9077ff0628
    Found by: stack scanning
11  vscode-encrypt-native.node + 0x2e9364
    rsp = 0x00007f90863ad848   rip = 0x00007f9078109364
    Found by: stack scanning
12  vscode-encrypt-native.node + 0x1ca246
    rsp = 0x00007f90863ad850   rip = 0x00007f9077fea246
    Found by: stack scanning
13  libpthread.so.0 + 0x620b
    rsp = 0x00007f90863ad860   rip = 0x00007f90a182b20b
    Found by: stack scanning
14  libpthread.so.0 + 0xcec0
    rsp = 0x00007f90863ad868   rip = 0x00007f90a1831ec0
    Found by: stack scanning
15  vscode-encrypt-native.node + 0x2e9364
    rsp = 0x00007f90863ad870   rip = 0x00007f9078109364
    Found by: stack scanning
16  libsecret-1.so.0 + 0x250dc0
    rsp = 0x00007f90863ad878   rip = 0x00007f907835cdc0
    Found by: stack scanning
17  vscode-encrypt-native.node + 0x256ab6
    rsp = 0x00007f90863ad8a0   rip = 0x00007f9078076ab6
    Found by: stack scanning
18  vscode-encrypt-native.node + 0x1c9d80
    rsp = 0x00007f90863ad8b0   rip = 0x00007f9077fe9d80
    Found by: stack scanning
19  vscode-encrypt-native.node + 0x2dca50
    rsp = 0x00007f90863ad8b8   rip = 0x00007f90780fca50
    Found by: stack scanning
20  vscode-encrypt-native.node + 0x28ae2d
    rsp = 0x00007f90863ad8e0   rip = 0x00007f90780aae2d
    Found by: stack scanning
21  vscode-encrypt-native.node + 0x289b1e
    rsp = 0x00007f90863ad9a0   rip = 0x00007f90780a9b1e
    Found by: stack scanning
22  libpthread.so.0 + 0xaf9e
    rsp = 0x00007f90863ad9c8   rip = 0x00007f90a182ff9e
    Found by: stack scanning
23  vscode-encrypt-native.node + 0x28663a
    rsp = 0x00007f90863ada10   rip = 0x00007f90780a663a
    Found by: stack scanning
24  libpthread.so.0 + 0xbac5
    rsp = 0x00007f90863ada20   rip = 0x00007f90a1830ac5
    Found by: stack scanning
25  code!worker [threadpool.c : 122 + 0x4]
    rsp = 0x00007f90863ada60   rip = 0x00005642872c1f0d
    Found by: stack scanning
26  libpthread.so.0 + 0x7ea5
    rsp = 0x00007f90863adaa0   rip = 0x00007f90a182cea5
    Found by: stack scanning
27  libc.so.6 + 0xfeb0d
    rsp = 0x00007f90863adb40   rip = 0x00007f909c680b0d
    Found by: stack scanning

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/164223
