### ISSUE TITLE
Please allow us to upvote closed issues

### ISSUE THREAD

**Issue by 2rs2ts** [microsoft/vscode#169665]
https://github.com/microsoft/vscode/issues/169448 was closed because it was a dupe, and I was told to upvote the original (https://github.com/microsoft/vscode/issues/99361) instead of creating a duplicate. But I created it specifically because I cannot upvote the original, because it was locked. Please allow us to upvote closed issues, or please change your duplicate rules so that people can re-raise issues.

**Comment by TylerLeonhardt** [comment]
AFAIK GitHub does not allow upvoting when an issue is locked and we lock issues specifically so that we don't get spammed.

In any case, I'll defer to @sandy081 as the area owner for a decision here

**Comment by 2rs2ts** [comment]
> AFAIK GitHub does not allow upvoting when an issue is locked and we lock issues specifically so that we don't get spammed.

I will put in a feature request with Github to ask them to allow repo maintainers to lock issues for comments but not reactions. Of course, who knows when and if that will get delivered. In the meantime, I hope we can find an agreeable policy for letting people show interest in closed issues.

**Comment by sandy081** [comment]
Ok, I did not see the other issue was locked. Unlocked it.

**Comment by 2rs2ts** [comment]
@sandy081 thank you, that works for me for now. I hope Github implements tools to allow for upvotes in locked threads so that you don't have to deal with more requests like mine, from other users. My coworkers and I sincerely appreciate you unlocking the original issue!

**Comment by TylerLeonhardt** [comment]
> I hope Github implements tools to allow for upvotes in locked threads

We want this too :)

**Comment by 2rs2ts** [comment]
@sandy081 it looks like the github-actions bot locked #99361 again. Can that be undone and prevented from happening in the future, maybe by reopening the original issue rather than just unlocking it?
