### ISSUE TITLE
Visual Studio Code consuming insane amount of battery

### ISSUE THREAD

**Issue by paragkatoch** [microsoft/vscode#169645]
Type: <b>Bug</b>

My Visual Studio Code was consuming an insane amount of battery power. Sometimes in Activity monitor it reached to 700 in 12hr power usage.

So I completely uninstalled Visual Studio Code removed all its files and folder including `~/.vscode`.
After this I reinstalled Visual Studio Code without installing any extension or changing any setting and also turned off setting sync, but still the `12hr power usage` reached 112 in few minutes while the whole day running Brave browser was at 58.

This makes using Visual Studio Code completely unusable because it drains whole M1 Mac battery in couple of hours.

I am mainly using Visual Studio Code for Next.js projects with typescript, eslint and jest configured.

Any help will be appreciated!!

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/61873006/208687947-14d62e9c-8576-465d-ad40-ceb30af93061.png">

 

VS Code version: Code 1.74.1 (1ad8d514439d5077d2b0b7ee64d2ce82a9308e5a, 2022-12-14T10:32:34.075Z)
OS version: Darwin arm64 22.2.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 3|
|Memory (System)|8.00GB (0.14GB free)|
|Process Argv|--crash-reporter-id 360bbf44-fb6a-49c0-bc02-7b6b0f889238|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by connor4312** [comment]
Please see https://github.com/microsoft/vscode/wiki/Performance-Issues and provide more information accordingly. Thanks!

**Comment by paragkatoch** [comment]
@connor4312  any update?

**Comment by connor4312** [comment]
As shown in the screenshot, it looks like at the time of your recording, VS Code was not using much (0.1%) of CPU. Please collect information when you experience CPU spikes so we can narrow down the culprit.

**Comment by paragkatoch** [comment]
Then why is it consuming high amount of power? Also to be honest I never saw VS Code consuming high amount of CPU but energy usage remain high no matter what

**Comment by deepak1556** [comment]
power column is a combination of an applications CPU usage, idle wake up frequency, disk usage, gpu usage etc you can read https://blog.mozilla.org/nnethercote/2015/08/26/what-does-the-os-x-activity-monitors-energy-impact-actually-measure/ about how the OS measures it. Given in your case the CPU usage is not the cause, it could be from one of the other factors. Please provide the output of following command,

```
sudo powermetrics --samplers tasks --show-process-coalition --show-process-gpu --show-process-energy -n 1 -i 30000
```
