### ISSUE TITLE
Two refresh button in right click of commit

### ISSUE THREAD

**Issue by mohanbabu-zumen** [microsoft/vscode#169631]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: latest
- OS Version: Windows 11

Steps to Reproduce:

1. Expand commits on the left side and right-click it.
2. It shows two refresh button

![image](https://user-images.githubusercontent.com/102032328/208669305-6c7f7116-b3f6-4221-8b3c-8d06d71914f4.png)

**Comment by lszomoru** [comment]
@mohanbabu-zumen, the "Commits" view is being contributed by the GitLens extension.
Please create an issue in [the extension's repository](https://github.com/gitkraken/vscode-gitlens/issues) to get further assistance. Thank you!
