### ISSUE TITLE
Multi-select is not correct

### ISSUE THREAD

**Issue by zhoudotnet** [Microsoft/vscode#16960]
- VSCode Version: v1.7
- OS Version: win7

Steps to Reproduce:

1. Open vscode

2. Input the contents:
Account
acb

3. select this character: "c", and click Ctrl + F, then you will see the issue. It should have 3 cursors, but it only have 2 cursors.

**Comment by zhoudotnet** [comment]
When do you fix this issue?

**Comment by alexandrudima** [comment]
Duplicate of #6661
