### ISSUE TITLE
Errors on non-existent lines

### ISSUE THREAD

**Issue by AirScooter** [microsoft/vscode#169633]
I have a sketch that is 15 lines in length and my compiler is reporting errors on various lines 50 sometimes 60 lines away. Please, what is the fix? I can't proceed without solving these non-existent errors. Thank you .
 

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 
2.

**Comment by AirScooter** [comment]
Windows 11
VS Code v. 17.4

**Comment by mjbvz** [comment]
What language is this for?

**Comment by AirScooter** [comment]
Thank you Matt,
I am new.
I am working in PlatformIo so as i have changed nothing from default, i
assume this is C++.
Dave Lowa

**Comment by mjbvz** [comment]
Thanks. Please file this issue against either PlatformIO or the C++ extension (whichever extension is generating the errors)
