### ISSUE TITLE
diff display does not work (1.8.0-insider 2016-12-09T07:02:57.714Z)

### ISSUE THREAD

**Issue by satokaz** [Microsoft/vscode#16966]
- VSCode Version: 1.8.0-insider (1.8.0-insider) 46e96d6d73bcf731c9907955e89c9a154f7a9050 2016-12-09T07:02:57.714Z
- OS Version: macOS Sierra 10.12.1（16B2657）

Steps to Reproduce:

1. code-insiders --disable-extensions
2. `Select for Compare` and  `Compare with ...` or GIT view

Indicator showing difference is not displayed

<img width="1920" alt="2016-12-09 18 06 13" src="https://cloud.githubusercontent.com/assets/13635244/21043513/96ed340c-be3a-11e6-8377-46118c706412.png">

**Comment by alexandrudima** [comment]
Dup of #16953. Install latest update
