### ISSUE TITLE
[loc][Query][VSCode] Please clarify localizability

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#16964]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Tree Explorer Section
Contributes custom tree explorer viewlet to the sidebar
Human readable string used to render the custom tree explorer

File Name:
src\vs\workbench\parts\explorers\browser\views\treeExplorerView.nls.resx

Resource ID:
".resx", 0; "treeExplorerViewlet.tree"
".resx", 0; "vscode.extension.contributes.explorer"
".resx", 0; "vscode.extension.contributes.explorer.treeLabel"

Query:
Is Tree Explorer a product name (not localizable), or is it localizable? Thanks!

**Comment by bpasero** [comment]
@mkyjakova I would say "Tree Explorer" is a custom name that should not be translated for now. We might also change the name later, this is nothing that is currently surfacing in the UI (yet).
