### ISSUE TITLE
VSCODE_EXTENSIONS not wokring on macos

### ISSUE THREAD

**Issue by burhankhanzada** [microsoft/vscode#169600]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version:  1.74.1
- OS Version:  MacOS 13.1

Steps to Reproduce:

1.  export VSCODE_EXTENSIONS="~/microsoft/vscode/extensions"

Expecting create .vscode folder in ~/microsoft/vscode/extensions"
but its ignored i have used this envirometn varable on windows and its works flawless

**Comment by sandy081** [comment]
Can you please explain what is not working?

**Comment by burhankhanzada** [comment]
Like i want my extension to a location where i dont need to reload again if i reset like on my external drive

**Comment by sandy081** [comment]
Not sure if I understand the problem. In other words, why do you think exporting `VSCODE_EXTENSIONS` is not working for you?

**Comment by burhankhanzada** [comment]
I think that problem with macos i have read some articles that on macos gui apps doesn't use terminal sets environmental variables i think thats the reason behind it although I got a workaround for it to create symbolic link of ~/.vscode to some other location

**Comment by sandy081** [comment]
Great, closing this issue as you got it solved.
