### ISSUE TITLE
Search in run and debug for variables

### ISSUE THREAD

**Issue by ManPython** [microsoft/vscode#169648]
I looking option to Search in run and debug for variables as trapped or other - right now is list of all (it's hard to find one in this stack).
If expression or bug, not working preview for variables/line error to see problem if opened belt with error in other line.

Coz exist old problem with Python around Raised Expression to find problem around python311.zip etc. I hope that somebody well oriented around VSC can look around whats going on..  coz by this is hard to use VSC to debug anything around Django
https://github.com/microsoft/debugpy/issues/1160

**Comment by roblourens** [comment]
You can press cmd+F or ctrl+F to search for variable names. If that's not what you mean, then it's not clear, please explain some more.

**Comment by ManPython** [comment]
In debuger? No input for this. Stack..

**Comment by roblourens** [comment]
I don't understand. Yeah, click to put focus in the variables view then press it.

**Comment by ManPython** [comment]
You indicating solution in code editor, not left dock as navigator for all variables. 
I want push ctr+F to find variables as looking
https://code.visualstudio.com/assets/docs/editor/debugging/debugging_hero.png
https://code.visualstudio.com/docs/editor/debugging

**Comment by roblourens** [comment]
Yes, this is implemented 
<img width="422" alt="image" src="https://user-images.githubusercontent.com/323878/210007311-fccefd7c-6bf2-4775-afa6-97262e633f2b.png">
