### ISSUE TITLE
Native selection text color is transparent instead of blue

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#169662]
* open quick input or the find widget
* type and select some text
* observe that the selection is not rendered
(this happened with this insiders update, I'm quite sure it was working in yesterday's insiders)

https://user-images.githubusercontent.com/5047891/208724376-0f70812a-4410-4955-8151-26086d8ce5e2.mp4

```
Version: 1.75.0-insider
Commit: d957d2ca58ded0ab70ed7fadc8a1f6a36fcf2d1e
Date: 2022-12-20T10:01:06.990Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 21.6.0
Sandboxed: Yes
```

**Comment by bpasero** [comment]
So it looks like the use of CSS variables in some cases is dangerous. Here https://stackoverflow.com/questions/56798646/css-selection-with-var-fallback explains a bit more.

My fix is to revert back to how it was for `:: selection`
