### ISSUE TITLE
vscode.git extension backward incompatible api change since 1.74.1

### ISSUE THREAD

**Issue by lispercat** [microsoft/vscode#169652]
In my extension I have a code which doesn't work starting from VSCode upgrade 1.74.1
The code is to determine git modified staged files:

    var gitExtension = vscode.extensions.getExtension('vscode.git');
    if(!gitExtension){
      vscode.window.showInformationMessage(`Can't get git extension`);
      return;
    }
    const gitExports = await gitExtension.activate();
    const gitAPI = gitExports.getAPI(1);
    while(gitAPI.repositories.length === 0){
      vscode.window.showInformationMessage(`Couldn't find any git repositories`);
      //await gitAPI.onDidOpenRepository();
      return;
    }
    
    var repository = gitAPI.repositories.filter(r => r.rootUri.fsPath.replace(/\\/g, "/").startsWith(this.g_workspaceFolder))[0];
    if(undefined == repository){
      vscode.window.showErrorMessage(`Couldn't find a git repository at ${this.g_workspaceFolder} try to open VSCode with a different folder`);
      return;
    }
    const unstaged = repository.state.workingTreeChanges.map(r => r.resource);
    const staged = repository.state.indexChanges.map(r => r.resource);
    const all = unstaged.concat(staged);
    var filesToDeploy = all.filter(res => res.letter !== "D").
                            filter(res => path.extname(res.resourceUri.fsPath) === '.xml').
                            map(res => res.resourceUri.fsPath);

As of 1.74.1 elements of the list returned by repository.state.workingTreeChanges don't have "resource" properties with "letter" and "resourceUri" properties.
If it's a new vscode.git API change, where can I see the documentation so that I would make appropriate changes to my code?

Thank you,
Andrei

**Comment by lszomoru** [comment]
You might be impacted by a change that happed in VS Code rather than the git extension API. Could you please review the following [announcement](https://github.com/microsoft/vscode-discussions/discussions/257). If until now you were accessible private/protected properties it would be useful to describe the exact properties that you were using to see if there is a way to make those public. Thank you!

**Comment by lispercat** [comment]
Thanks for the tip, Ladislau!
