### ISSUE TITLE
Double backslashes when workbench.action.terminal.runActiveFile is run with no active terminal

### ISSUE THREAD

**Issue by DustinLuck** [microsoft/vscode#169694]
Type: <b>Bug</b>

1. Open VSCode
2. Set "terminal.integrated.defaultProfile.windows": "Command Prompt" in the settings
3. Open any file
4. Execute the 'Terminal: Run Active File in Active Terminal' command
5. A new terminal window (cmd.exe) will be opened and the file name will be entered on the command line with double backslashes in the path; the file will fail to execute with the error message, "The filename, directory name, or volume label syntax is incorrect."
6. Re-executing the 'Terminal: Run Active File in Active Terminal' command with the terminal window open will enter the file name with single backslashes and the file will be executed properly.

*This does not happen using the same steps when 'Windows PowerShell' is specified in step 2.

VS Code version: Code - Insiders 1.75.0-insider (64a739f7aa1092187348afa9378931d47683be12, 2022-12-19T05:22:58.250Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.21GB (0.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696
fim-prod:30623723

```

</details>

**Comment by Tyriar** [comment]
I can reproduce, it seems the escaping of the path happens before the shell is known so it applies the wrong one:

<img width="246" alt="image" src="https://user-images.githubusercontent.com/2193314/211084561-f5e693af-7f2d-4570-abd4-8236753ae001.png">

There were recent changes in this area so it makes sense if you see `\\` instead.
