### ISSUE TITLE
Workspace with many repositories - change in behaviour?

### ISSUE THREAD

**Issue by moseleyi** [microsoft/vscode#169653]
- VS Code Version: 1.74.1
- OS Version: Windows 10 Home

Not sure if there was a change in behaviour here but I have a workspace with about 60 folders and repositories. Until recently, when this workspace is opened, git wouldn't detect those repositories unless I open a file from any of them. Now, however, they are all evaluated after opening, which makes VSCode CPU consumption high during the reading of those folders. That is okay, I can wait a minute or two before being able to use VSCode but showing all repos makes it hard to find the one I may be currently working on 

![image](https://user-images.githubusercontent.com/16131590/208705846-bc6e5dca-0855-4d4c-958d-c13bd4fa41b6.png)

Steps to Reproduce:

1. Open a workspace with multiple repositories

**Comment by lszomoru** [comment]
@moseleyi, could you please check the value of the `git.autoRepositoryDetection` setting? If you set the value of the setting to `openEditors`, VS Code will only detect git repositories based on the editor that you have opened. Thanks!

**Comment by moseleyi** [comment]
Hi @lszomoru,

When I look at my settings, I never had this set neither on User nor the Workspace level. Could it be that the default value changed for this setting?

**Comment by lszomoru** [comment]
@moseleyi, I am not aware of the default value of the setting being changed.
