### ISSUE TITLE
Terminal Current Working Directory

### ISSUE THREAD

**Issue by GauravNagpure** [microsoft/vscode#169742]
Type: <b>Bug</b>

when we open terminal, path is not pointing to the same folder opened .

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details><summary>Extensions (31)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-css-formatter|aes|1.0.2
node-essentials|afr|1.1.0
ng-template|Ang|15.0.3
vscode-icontheme-nomo-dark|be5|1.3.6
vscode-exports-autocomplete|cap|0.5.4
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
rxjs-cheatsheet|dzh|1.2.1
gitlens|eam|13.2.0
vscode-html-css|ecm|1.13.1
EditorConfig|Edi|0.16.4
prettier-vscode|esb|9.10.3
vscode-pull-request-github|Git|0.56.0
Angular-BeastCode|Mik|10.0.3
dotenv|mik|1.0.1
vscode-html-format|moh|0.0.5
vscode-typescript-tslint-plugin|ms-|1.3.4
vscode-extension-auto-import|Nuc|1.4.3
vscode-jest|Ort|5.1.0
vscode-versionlens|pfl|1.0.10
rxjs-snippets|pko|0.0.2
vscode-yaml|red|1.10.1
vscode-scss-formatter|sib|2.4.4
sonarlint-vscode|Son|3.13.0
node-pack|Swe|0.1.16
highlight-matching-tag|vin|0.10.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
quokka-vscode|Wal|1.0.519
vscode-import-cost|wix|3.3.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by meganrogge** [comment]
that is by design unless you've specified `terminal.integrated.cwd`
