### ISSUE TITLE
[loc][Query][VSCode] Please clarify the context for a string

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#16973]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
[Unsupported]

File Name:
src\vs\workbench\services\history\browser\history.nls.resx

Resource ID:
".resx", 0; "patchedWindowTitle"

Query:
Please clarify context for gender/issue.	CnE_Developer_Moravia_ITA1@hotmail.com	11/15/2016 7:44:15 PM

**Comment by bpasero** [comment]
@mkyjakova we show [Unsupported] in the window title if we detect an installation that has corrupt bits on disk. Let me know if you need more details.
