### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by 3Scratch** [microsoft/vscode#169713]
Type: <b>Bug</b>

I try to push my projects on github but the process bar stucked at 50-60%.
![image](https://user-images.githubusercontent.com/50314456/208843022-81612d95-fb10-4ce0-ba20-a0aa5e382013.png)
https://drive.google.com/file/d/1r7bCf53-FgAxaE6bOW9ws7_O39AtUqhe/view?usp=sharing

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz (16 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.84GB free)|
|Process Argv|--crash-reporter-id 3f1b50dc-f173-4ddf-ae5d-22ec3bb17464|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
es7-javascript-class-snippets|abr|0.4.0
vscode-eslint|dba|2.2.6
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.5.0
prettier-vscode|esb|9.10.3
vscode-express-snippets|Exp|1.1.1
code-runner|for|0.11.8
gitignore|mic|1.0.1
cpptools|ms-|1.13.8
material-icon-theme|PKi|4.23.0
java|red|1.13.0
LiveServer|rit|5.7.9
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
JavaScriptSnippets|xab|1.8.0

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by lszomoru** [comment]
@3Scratch, are you able to reproduce this every time you are trying to publish to GitHub? 
When this happens, could you open [the git output window](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-output-window) and share the contents? Thanks!

**Comment by 3Scratch** [comment]
It is fixed now. i reinstalled vs code.
