### ISSUE TITLE
Recommended extension "not found in marketplace" but found manually

### ISSUE THREAD

**Issue by FlorentRevest** [microsoft/vscode#169729]
Type: <b>Bug</b>

My `.vscode/extensions.json` contains:

```
{
  "recommendations": [
    "florent-revest.git-send-email"
  ]
}
```

And every time I start VSCode, I get the following warning: `The 1 extension(s) below, in workspace recommendations have issues: florent-revest.git-send-email (not found in marketplace)`

However, if I search for the ID manually in the Extensions pane, I can find the extension.
Also, if I copy paste the ID into a marketplace URL like https://marketplace.visualstudio.com/items?itemName=florent-revest.git-send-email I can find it.

With another extension like `florent-revest.patchwork`, the recommendation works as expected.

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 22.1.0
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.19.11-1-amd64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.67GB free)|
|Process Argv|--crash-reporter-id 9d6e74f6-c6b5-4005-aa97-40dbbbb62512|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|SSH: xxx|
|OS|Linux x64 5.19.11-1-amd64|
|CPUs|Intel(R) Xeon(R) Gold 6154 CPU @ 3.00GHz (36 x 1200)|
|Memory (System)|187.51GB (178.74GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
kconfig|luv|1.0.3
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-explorer|ms-|0.0.3
devicetree|plo|0.1.1
vim|vsc|1.24.3
gdb-debug-adapter|arm|1.0.1
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.3
git-send-email|flo|1.1.0
patchwork|flo|1.1.0
checkpatch|ida|0.0.8
vscode-clangd|llv|0.1.23
vscode-arm64|MKo|1.0.6
cpptools|ms-|1.13.8
trailing-spaces|sha|0.4.1
vscode-lldb|vad|1.8.1

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
gswce1:30612156
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by sandy081** [comment]
I am not seeing the error you are seeing, instead I am getting the recommendation

![image](https://user-images.githubusercontent.com/10746682/208961432-dde415b7-f355-48ba-bf98-c42e6d6437a4.png)

Next time you see it, can you please open the network tab using `F1 > Developer: Toggle Developer Tools` and check for following extension query and let us know the response of that query?

![image](https://user-images.githubusercontent.com/10746682/208961796-1167dfbf-c944-482d-8b12-9517c7107555.png)

**Comment by tjx666** [comment]
same here:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/209209868-2a6b87b0-b5b3-4060-9736-636ae60c5c68.png">

```
The 1 extension(s) below, in workspace recommendations have issues: yutengjing.vscode-neo-file-utils (not found in marketplace)
```

**Comment by FlorentRevest** [comment]
Thanks Sandeep, that should help! :) I'll definitely share the query capture next time I see it.

But, unfortunately...

> This can't be reproduce every vscode restart. But often happen after open vscode and coding some time.

Same here. I could reliably reproduce it yesterday but today I can't get that warning again, uh. :| Maybe it was a transient issue on the server-side ?

If @tjx666 can't get a capture either, maybe we can close this bug and re-open it once someone managed to reproduce it and to share a capture.

**Comment by sandy081** [comment]
Make sense. Thanks for sharing.
