### ISSUE TITLE
 Check for update option disappears !!

### ISSUE THREAD

**Issue by Issam-seghir** [microsoft/vscode#169719]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.1
- OS Version: windows 10  21H2 (OS Build 190442075)

Steps to Reproduce:

the `check for update`  option disappears!! , and vs code doesn't update automatically ,  i can't update to the last version (1.74.2)

**Comment by gjsjohnmurray** [comment]
Are you using Run As Administrator when you launch VS Code?

**Comment by Issam-seghir** [comment]
https://github.com/microsoft/vscode/issues/157624#issuecomment-1222300708
