### ISSUE TITLE
Enable / Disable activit bar shortcuts back to default position

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#16975]
- VSCode Version: 1.8.0 insider
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

When you disable shortcuts in the activity bar and enable them again, it must return to the default position, not the last position, or return to the last saved configuration.

Example: When you deactivate the search and activate again the same back to last position and the correct one is to return to the second position. I say this because this is how it comes when installing VSCode for the first time. 

Or in case if I had set the search to the third position, when deactivating and activating again it should return to that position.
![capturar1](https://cloud.githubusercontent.com/assets/19866231/21048369/10a7d63e-bdf6-11e6-8011-4dd7b2c74e0f.JPG)

**Update:** it is better to go back to the last saved configuration instead of the default one.

**Comment by bpasero** [comment]
@Tekbr we try to simulate what an application dock would do: when you remove an application from the task bar and open it again, it does not go back to the position you had before. Instead it opens to the right of the pinned applications. Does that make sense?

**Comment by Tekbr** [comment]
@bpasero Since it is the default items of the IDE I think I should go back to the default position or the last chosen position. See the Eclipse example, when activating the tabs back to the last position I left. Would not this be possible with activit bar icons?

![gif](https://cloud.githubusercontent.com/assets/19866231/21052316/82b4aff8-be0b-11e6-8a67-dbbe2bad3061.gif)

**Comment by bpasero** [comment]
@stevencl @chrisdias @seanmcbreen @bgashler1 thoughts?

**Comment by chrisdias** [comment]
I can see the different models, but in my opinion the most predictable behavior for the user is the current behavior where the icon is always restored at the bottom of the list.  

Imagine a scenario where I hide the explorer and made the debug icon the first in the list.  Later I restore the Explorer icon, do I want it to be first in the list? We don't know for sure. Maybe not, maybe I still want the debug icon first. If we get it wrong and we move the debug icon down, then I'm an unhappy user.

At the same time, we can't remember where it was in the list because all but one could be in the 2nd position when it is hidden. When the user restore the icon, which one wins? 

With the model we have today it is predictable. When you restore a previously hidden icon, it shows up at the bottom of the list, no other icons are re-positioned as a result of this action.

**Comment by Tekbr** [comment]
If I understood correctly.

> I can see the different models, but in my opinion the most predictable behavior for the user is the current behavior where the icon is always restored at the bottom of the list.

I do not think that would be the most predictable behavior. If the icon was not active by default, I even agree that it came in the last position.


> Imagine a scenario where I hide the explorer and made the debug icon the first in the list. Later I restore the Explorer icon, do I want it to be first in the list? We don't know for sure. Maybe not, maybe I still want the debug icon first. If we get it wrong and we move the debug icon down, then I'm an unhappy user.

Yes, I imagined the scenario, if I want it to be in the first position, I drag it to the first position. In this case I am an unfortunate user if I do not return to the last position I left.


> At the same time, we can't remember where it was in the list because all but one could be in the 2nd position when it is hidden. 

I do not understand very well. Sorry.

> When the user restore the icon, which one wins?

Return to the last position you set before turning it off.

> With the model we have today it is predictable. When you restore a previously hidden icon, it shows up at the bottom of the list, no other icons are re-positioned as a result of this action.

I do not think that would be the most predictable behavior.

See the Visual Studio example

![gif1](https://cloud.githubusercontent.com/assets/19866231/21144917/9418b854-c133-11e6-8947-f87e2caa1ddc.gif)

**Comment by stevencl** [comment]
Thanks very much for the feedback. It's a good question and there are good arguments for either option but I agree with @chrisdias. As well as the predictability that he mentions, it's also worth considering that a user might remove an icon from the activity bar then work without it for quite some time (perhaps days, months even) and in the process, get very used to the layout without that button. So when they add it back some time later, it could be quite disruptive to that layout to place it back in the position it was previously.

Thinking about the impact over longer term usage, the option of placing the icon back at the  bottom of the list is least disruptive.

**Comment by Tekbr** [comment]
-- Sorry for the English, I used Google Translator --
@stevencl @bpasero @chrisdias I do not think it's so damaging, much less damaging, as you guys think. Some examples of applications have already been shown. 
You could leave it at **Backlog**, at least, right? Maybe someday it will be possible, will not it?
