### ISSUE TITLE
smoketest: switching projects results in a black window

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16978]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:06:36.411Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

Steps to Reproduce:

1. follow smoketest setup (launching VS Code with `<code executable> --user-data-dir <new user data dir> --extensions-dir <new extensions dir>`)
1. set theme to 'Light+'
1. open another project

Observe: while switching projects the window turns black for half a second.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/16230
