### ISSUE TITLE
Text not selectable in tooltips 

### ISSUE THREAD

**Issue by OmarOmeiri** [microsoft/vscode#169754]
Type: <b>Bug</b>

Text is not selectable in tooltips

https://user-images.githubusercontent.com/46783176/208943699-132011e7-7717-45df-a407-5bd85de391fd.mp4

This also happens with all extensions disabled.

VS Code version: Code - Insiders 1.75.0-insider (d957d2ca58ded0ab70ed7fadc8a1f6a36fcf2d1e, 2022-12-20T09:53:34.313Z)
OS version: Windows_NT x64 10.0.22622
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.95GB (12.52GB free)|
|Process Argv|--crash-reporter-id 32691aa7-d1f0-4a2d-8a78-00330cacfccb|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|Dev Container: Existing Docker Compose (Extend)|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor (20 x 3792)|
|Memory (System)|19.53GB (11.20GB free)|
|VM|0%|
</details><details><summary>Extensions (44)</summary>

Extension|Author (truncated)|Version
---|---|---
postcss|css|1.0.9
better-cpp-syntax|jef|1.17.2
styled-components-snippets|jon|0.10.0
theme-by-language|jsa|1.2.1
vscode-edge-devtools|ms-|2.1.1
jupyter-keymap|ms-|1.0.0
remote-containers|ms-|0.268.0
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
remote-wsl|ms-|0.72.0
remote-explorer|ms-|0.0.3
js-quick-console|Aha|0.0.3
turbo-console-log|Cha|2.6.2
vscode-css-modules|cli|0.4.2
js-codeformer|cms|2.6.1
jsrefactor|cms|3.0.1
vscode-eslint|dba|2.2.6
es7-react-js-snippets|dsz|4.4.3
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.3
comment-anchors|Exo|1.10.2
auto-rename-tag|for|0.1.10
code-runner|for|0.11.8
vscode-trello-viewer|Ho-|0.6.0
RelativePath|jak|1.5.0
vscode-edit-csv|jan|0.7.2
vs-color-picker|lih|1.0.0
git-graph|mhu|1.30.0
prettify-json|moh|0.0.3
vscode-docker|ms-|1.23.3
vscode-thunder-client|ran|2.2.0
r-debugger|RDe|0.5.2
vscode-yaml|red|1.10.1
r|REd|2.7.0
bash-debug|rog|0.3.9
bash-beautify|sha|0.1.1
html5-boilerplate|sid|1.1.1
vscode-styled-components|sty|1.7.5
vscode-stylelint|sty|1.2.3
tabnine-vscode|Tab|3.6.31
vscode-h2o|tet|0.2.4
vscode-icons|vsc|12.0.1
quokka-vscode|Wal|1.0.519
vscode-import-cost|wix|3.3.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by lramos15** [comment]
It is selectable just the color is gone, see https://github.com/microsoft/vscode/issues/169662
