### ISSUE TITLE
Create profile -> quick pick does not focus first element

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#169740]
Click on Create Profile > Quick Pick gets opened and the focus is weirdly on the whole Quick Pick.
I would expect that the first element is pre-selected so I can just press Enter

![Screenshot 2022-12-21 at 13 58 11](https://user-images.githubusercontent.com/1926584/208911057-513fc763-372c-4806-92cb-7c643426212e.png)

**Comment by sandy081** [comment]
Weird, I do not see it. Do you have any settings causing it?

**Comment by isidorn** [comment]
Yes, it was some setting. Sorry for the noise. Closing this.
