### ISSUE TITLE
Create a PR after pushing a remote branch

### ISSUE THREAD

**Issue by digitarald** [microsoft/vscode#169776]
How might we make it easier to create PRs when a user pushed a new remote branch. This is easy through the CLI, as it prompts a link, and VS Code should provide similar affordance as it is a natural next step.

VS Code already has an amazing [PR creation flow](https://github.com/microsoft/vscode/blob/de7ce5adf31b43f210b5b94b287dbfe6416f449d/extensions/github/src/pushErrorHandler.ts#L18) (including support for PR templates!), which is triggered when a user doesn't have permissions on the remote.

As a start, this could be triggered when a user pushes to a GH remote and the remote returns the `Create a pull request for … on GitHub by visiting` response:
- Prompt to create a PR using the [existing flow](https://github.com/microsoft/vscode/blob/de7ce5adf31b43f210b5b94b287dbfe6416f449d/extensions/github/src/pushErrorHandler.ts#L92)
- Add an option to create a draft PR if the branch is a not final – making contributions less intimidating but to allow early feedback.

**Comment by isidorn** [comment]
We did some improvements to the create PR flow. Thus closing this as tackled.
fyi @hbons and @alexr00 in case some of these ideas could be applied to the new flow.
