### ISSUE TITLE
Build failed: Segmentation fault

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#169762]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197655
Changes: https://github.com/Microsoft/vscode/compare/e69c2fc...4ab3689

./scripts/test-integration.sh: line 58:  2126 Segmentation fault      (core dumped) "$INTEGRATION_TEST_ELECTRON_PATH" $LINUX_EXTRA_ARGS $ROOT/extensions/vscode-api-tests/testWorkspace --enable-proposed-api=vscode.vscode-api-tests --extensionDevelopmentPath=$ROOT/extensions/vscode-api-tests --extensionTestsPath=$ROOT/extensions/vscode-api-tests/out/singlefolder-tests $API_TESTS_EXTRA_ARGS

**Comment by deepak1556** [comment]
Return of https://github.com/microsoft/vscode/issues/153181, will setup debug builds again.
