### ISSUE TITLE
Wrapping Indent not working

### ISSUE THREAD

**Issue by slieo** [microsoft/vscode#169794]
Type: <b>Bug</b>

when upgrade to 1.74.2, the code wrapped align to left when set Word Wrap on

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes: Unsupported
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i9-12900H (20 x 2918)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (13.59GB free)|
|Process Argv|--crash-reporter-id a9e16033-f7cb-4626-b908-b2a5fd62936c|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
auto-close-tag|for|0.5.14
vue-snippets|hol|1.0.4
svg|joc|1.4.26
emoji-icons|mig|1.5.2
vscode-filesize|mkx|3.1.0
remote-wsl|ms-|0.72.0
color-highlight|nau|2.5.0
korofileheader|OBK|4.9.2
vetur|oct|0.36.1
material-icon-theme|PKi|4.23.0
background|sha|1.2.8
uni-app-snippets-vscode|uni|0.9.5
vscode-icons|vsc|12.0.1
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.6
html-css-class-completion|Zig|1.20.0

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

![Snipaste_2022-12-22_09-59-28](https://user-images.githubusercontent.com/12100710/209040277-442c46d8-1ef5-4915-aa03-d1bfba8ea041.png)

**Comment by alexdima** [comment]
@slieo The wrapping indent is controlled via a setting called `editor.wrappingIndent`. It can take the following values:
```
  // Controls the indentation of wrapped lines.
  //  - none: No indentation. Wrapped lines begin at column 1.
  //  - same: Wrapped lines get the same indentation as the parent.
  //  - indent: Wrapped lines get +1 indentation toward the parent.
  //  - deepIndent: Wrapped lines get +2 indentation toward the parent.
  "editor.wrappingIndent": "same",
```
