### ISSUE TITLE
Is there a way to disable Ctrl Click go to reference feature?

### ISSUE THREAD

**Issue by brunolm** [Microsoft/vscode#16974]
- VSCode Version: 1.7.2
- OS Version: Ubuntu 16

Steps to Reproduce:

1. Have a reference (TypeScript) (`import * as moment from 'moment';`)
2. Ctrl click `moment` to select the word

**Expected**: Select the word `moment`

**Actual**: It goes to moment definition file

Note, the following keybinding **did not** change the behavior at all:

```json
    {
        "key": "ctrl+[mouse button]",
        "command": "cursorWordLeft",
        "when": "editorTextFocus"
    }
```

**Comment by alexandrudima** [comment]
Let's track this in #3130
