### ISSUE TITLE
Build failed: Workbench editor utils whenEditorClosed (single editor)

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#169760]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197636
Changes: https://github.com/Microsoft/vscode/compare/e641e03...170505e

```
  1) Workbench editor utils
       whenEditorClosed (single editor):

      
      + expected - actual


  Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by bpasero** [comment]
Looks like a CI fluke as this test failed once in 30 days and not before. I see no evidence of something bad in the test itself. If this comes back I will add some logging.
