### ISSUE TITLE
Renderer throttling?

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#169759]
* Add the following console log:
```diff
diff --git a/src/vs/base/parts/ipc/common/ipc.net.ts b/src/vs/base/parts/ipc/common/ipc.net.ts
index 2ba8902448c..109f10963e9 100644
--- a/src/vs/base/parts/ipc/common/ipc.net.ts
+++ b/src/vs/base/parts/ipc/common/ipc.net.ts
@@ -1354,6 +1354,7 @@ class LatencyMonitor extends Disposable {
 		}
 
 		const roundtripTime = Date.now() - this._lastLatencyMeasurementSent;
+		console.log(`ROUND TRIP TIME: ${roundtripTime}ms`);
 		const sampleIndex = this._latencySampleIndex++;
 		this._latencySamples[sampleIndex % this._latencySamples.length] = roundtripTime;
 ```
* run `./scripts/code.sh`
* from the remote indicator in the status bar, choose `New TestResolver Window`
* open dev tools and let it run for 10 minutes
* for me, it got covered by browser windows
* observe that exactly after 10 minutes, the round trip times increase from <20ms to >1s.

**Comment by deepak1556** [comment]
Launching with `--disable-background-timer-throttling` should suppress the timer throttling when renderer is in background.

**Comment by bpasero** [comment]
@alexdima could we use the knowledge around whether a window is active or not as a way to not react on this unresponsiveness in telemetry and only track active windows unresponsivesness?

Or are you suggesting to try to set the necessary Chromium flags to disable this behaviour?

**Comment by Donniewoo77** [comment]
> * Add the following console log:
> 
> ```diff
> diff --git a/src/vs/base/parts/ipc/common/ipc.net.ts b/src/vs/base/parts/ipc/common/ipc.net.ts
> index 2ba8902448c..109f10963e9 100644
> --- a/src/vs/base/parts/ipc/common/ipc.net.ts
> +++ b/src/vs/base/parts/ipc/common/ipc.net.ts
> @@ -1354,6 +1354,7 @@ class LatencyMonitor extends Disposable {
>  		}
>  
>  		const roundtripTime = Date.now() - this._lastLatencyMeasurementSent;
> +		console.log(`ROUND TRIP TIME: ${roundtripTime}ms`);
>  		const sampleIndex = this._latencySampleIndex++;
>  		this._latencySamples[sampleIndex % this._latencySamples.length] = roundtripTime;
> ```
> 
> * run `./scripts/code.sh`
> * from the remote indicator in the status bar, choose `New TestResolver Window`
> * open dev tools and let it run for 10 minutes
> * for me, it got covered by browser windows
> * observe that exactly after 10 minutes, the round trip times increase from <20ms to >1s.

**Comment by deepak1556** [comment]
I think we have established the renderer throttling mechanisms and discussed possible ways to detect them at https://vscodeteam.slack.com/archives/C7J4GP8UD/p1671638373592339
