### ISSUE TITLE
[loc][Query][VSCode] Please clarify "compound"

### ISSUE THREAD

**Issue by mkyjakova** [Microsoft/vscode#16970]
Hi, we have a question from our translator. Can you help please? Thanks!

Source:
Compound must have "configurationNames" attribute set in order to start multiple configurations.
List of compounds. Each compound references multiple configurations which will get launched together.
Name of compound. Appears in the launch configuration drop down menu.
Names of configurations that will be started as part of this compound.

File Name:
src\vs\workbench\parts\debug\node\debugConfigurationManager.nls.resx

Resource ID:
".resx", 0; "compoundMustHaveConfigurationNames"
".resx", 0; "app.launch.json.compounds"
".resx", 0; "app.launch.json.compound.name"
".resx", 0; "app.launch.json.compounds.configurations"

Query:
Please clarify compound. Considering it as "compound item" for the time being.  	CnE_Developer_Moravia_ITA1@hotmail.com	11/29/2016 12:54:43 PM

**Comment by isidorn** [comment]
compound indicates a "compounds" configuration item from launch.json
