### ISSUE TITLE
GitHub Copilot could not connect to server. Extension activation failed: "Git error"

### ISSUE THREAD

**Issue by aiwowo1** [microsoft/vscode#169780]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.2
- OS Version: Windows 11

Steps to Reproduce:

1. Enable Copilot (paid version worked fine on previous VS Code version before upgrading to the latest). 
2. Start VS and the warning popup on the right bottom corner.

**Comment by lszomoru** [comment]
@aiwowo1, could you please share a screenshot of the notification that is being shown? Thank you!

**Comment by waki285** [comment]
I have the same problem

**Comment by garymm** [comment]
Seeing this on MacOS:

<img width="451" alt="Captura de pantalla 2022-12-27 a la(s) 09 14 34" src="https://user-images.githubusercontent.com/421339/209699628-46fd5e58-4e3c-4fd2-b841-0511cf00c61a.png">

**Comment by lszomoru** [comment]
@garymm, could you please click on the "Show Output Log" button and share the contents? Thanks!

**Comment by joeedwinoffi** [comment]
![image](https://user-images.githubusercontent.com/84732988/209981566-9b9f0605-fb98-4587-bb08-70183b15d706.png)



> @garymm, could you please click on the "Show Output Log" button and share the contents? Thanks!
![image](https://user-images.githubusercontent.com/84732988/209981628-d1ecbd24-88fe-456c-9581-f4a439b3d523.png)

**Comment by garymm** [comment]
Yeah the output is the same as what was just posted.
It's transient for me. If I reload the VS Code window it sometimes works.

**Comment by lszomoru** [comment]
Please please file an issue [here](https://github.com/community/community/discussions/categories/copilot) as this seems to be related to the Copilot extension. Thank you!

**Comment by HT-Moh** [comment]
Hi, I am getting the same issue here 
```
[ERROR] [default] [2023-01-27T10:24:37.999Z] GitHub Copilot could not connect to server. Extension activation failed: "command failed with error code 2: error parsing glob '!/{**/.git,**/.svn,**/.hg,**/CVS,**/.DS_Store,**/Thumbs.db,./.DS_Store,./.git,./.hg,./.svn,./${workspaceFolder}/**/.git,./${workspaceFolder}/**/.next,./${workspaceFolder}/**/.svn,./${workspaceFolder}/**/CVS,./${workspaceFolder}/**/node_modules,./${workspaceFolder}/**/out,./${workspaceFolder}/**/vendor,./CVS,./Thumbs.db,./.git/**,./node_modules/**,./.hg/**,./.svn/**}': nested alternate groups are not allowed
"
``` 
I changed **/ to ./ , but it didn't not work

**Comment by lszomoru** [comment]
Please see https://github.com/microsoft/vscode/issues/169780#issuecomment-1368906030
