### ISSUE TITLE
The cursor moving animation

### ISSUE THREAD

**Issue by FlashMan2008** [microsoft/vscode#169709]
In the previous version, vscode insiders has animation when moving cursors.
But in the latest version, it deleted this feature, why?

**Comment by alexdima** [comment]
we had one insiders released a few days ago which would always enable cursor animations, regardless of settings, but that was a bug. It sounds like you liked that. Please configure `"editor.cursorSmoothCaretAnimation": "on"`.

**Comment by FlashMan2008** [comment]
OK, thanks!
