### ISSUE TITLE
New Light Theme - bad contrast on extension item focus

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode#169812]
1. New Light Theme
2. Open the Extensions view
3. Focus the Extension item in the list -> all letters turn black, the contrast is not good 🐛 

![Screenshot 2022-12-22 at 10 18 54](https://user-images.githubusercontent.com/1926584/209110149-b5c2190b-5ac1-461a-983e-8f61e32a23af.png)

**Comment by daviddossett** [comment]
Looks like these buttons are inheriting the codicon styling, and as a result, the `listActiveSelectionIconForeground` color. I removed it from Light+ V2 to reset it back to null. Ideally this button wouldn't use codicon styling cc @sandy081
