### ISSUE TITLE
Tree item label jiggles up and down (if inline tree item commands have text and no icon)

### ISSUE THREAD

**Issue by r3m0t** [microsoft/vscode#169822]
Does this issue occur when all extensions are disabled?: N/A

- VS Code Version: 1.74.2 and tested on insiders
- OS Version: Windows

I used git bisect to identify this commit as the cause - 0f2de31e4856886cdbf32f85488bc40f480fb38f @daviddossett 

Steps to Reproduce:

1. Build and install this extension https://github.com/r3m0t/vscode-extension-samples/tree/tree-action/tree-view-sample
2. When you select or hover over items in the tree view, the label moves up a few pixels from its correct position.

![image](https://user-images.githubusercontent.com/1485998/209121807-835dd354-f04f-4271-ba5b-2a042489078b.png)

**Comment by alexr00** [comment]
I can repro, thank you for the sample.
