### ISSUE TITLE
smoketest: generating launch.json creates file with deprecation warnings.

### ISSUE THREAD

**Issue by dbaeumer** [Microsoft/vscode#16980]
- VSCode Version: 1.8.0-insider

![capture](https://cloud.githubusercontent.com/assets/1931590/21050860/77edb77e-be1d-11e6-95b2-6453afb224ae.png)

**Comment by isidorn** [comment]
Can not repro both on win and os x.
@dbaeumer do you always see this? What do the warning messages say?

**Comment by dbaeumer** [comment]
Strange, now I can't reproduce either. Happy I took a screen shot. The error actually was about outDir being deprecated and that you should us outFile.

But I remember something else. I had an old launch.json file in my workspace which had outDir properties and I deleted it using VS Code, created a new one using the gear button and got the error. Looks like stale errors from the last content :-)

**Comment by isidorn** [comment]
Dup of https://github.com/Microsoft/vscode/issues/16656

**Comment by aeschli** [comment]
@dbaeumer It would be great you could set `"json.trace.server": "verbose"` and if the language server gets the document change event.
