### ISSUE TITLE
Expand Sample Collection

### ISSUE THREAD

**Issue by egamma** [Microsoft/vscode#16988]
Add more [extension samples](https://github.com/Microsoft/vscode-extension-samples) that illustrate our API. For example:
- contributing to the different menus
- contributing to the status line
- language: implement a completion provider
- ...

Goal is to be able to link the API description in vscode.d.ts to these samples.

## Guidelines
- minimal code
- self contained
- documented

**Comment by seanmcbreen** [comment]
Some ideas that are not really based on our API but could really benefit from guidance:
* Indicating progress (e.g. download, making a connection, parsing data, ...)
* Securely storying a secret (e.g. like SQL and VSTS do but very common)

**Comment by seanmcbreen** [comment]
Another one:
* How to download additional content for an extension - best practice e.g. getting additional binary libraries, you are too big
* Best practices for docs - including release notes, including docs

**Comment by jrieken** [comment]
*editor* - insert text, set selection, set options, add decoration 
_commands_ - register command, menu contributions, invoke another command
_languages_ - hover, errors, suggest
_window_ - terminal, status bar, quick pick

**Comment by CoenraadS** [comment]
Is it ok to request a sample in here?

https://github.com/Microsoft/vscode/issues/6374

>The purpose of TextDocumentContentChangeEvent is to allow an interested party to correctly maintain a replica of the original document by applying the same edits described in it. We don't include an oldText because that would not be needed to maintain a replica.

I think it would be useful for a sample that shows how to correctly implement a reference document.

**Comment by egamma** [comment]
Closing, samples have been expanded and it is now an ongoing task.
