### ISSUE TITLE
"selectQuickSuggestions: off" behavior change request

### ISSUE THREAD

**Issue by gil-koifman** [microsoft/vscode#169830]
Hi,
This request is a follow up for the issue:
https://github.com/microsoft/vscode/issues/151336

We would like to have selectQuickSuggestions turned off, but with a small behavior change.
If the user pressed the "triggerCharacters", in our case it's "space", then when the suggestion list shows - nothing will be selected. This is implemented today with turning off selectQuickSuggestions.
But if the user started typing something, or started deleting characters from an existing word, then we do want the first option to be selected. In the current behavior, nothing will be selected.

Thanks!

**Comment by jrieken** [comment]
To clarify: like we differentiate between trigger `editor.suggestOnTriggerCharacters` and `editor.quickSuggestions` you like to be able to configure select mode for each of these auto-modes independently, right?

So, don't have `editor.suggest.selectQuickSuggestions` as `true|false` but as `onTriggerCharacter | onQuickSuggest | always | never`

**Comment by jrieken** [comment]
As discussed offline, this is now implemented with a revised setting: `editor.suggest.selectionMode`. demo: https://github.com/microsoft/vscode/issues/139825#issuecomment-1364056148

**Comment by jrieken** [comment]
Thanks for catching up.

**Comment by jrieken** [comment]
test plan covered by https://github.com/microsoft/vscode/issues/171988
