### ISSUE TITLE
Inside built-in terminal - tabbing through folders makes text jump

### ISSUE THREAD

**Issue by jochenvw** [Microsoft/vscode#16986]
- VSCode Version: 1.7.2
- OS Version: Windows 10 / 1607 / 14393.447

Steps to Reproduce:

1. Open up built-in terminal
2. Type `cd<space<`
3. Hit <tab> a couple of times - and try <shift>+<tab>
4. Observe how text jumps around in the window

See below

![vs_code_tabbing_through_dirs_in_console](https://cloud.githubusercontent.com/assets/17111555/21053702/e7a4926a-be2a-11e6-920e-67d9f97f610f.gif)

**Note** Don't mind the white cursor block - that wasn't really there, that turned up after rendering the GIF

**Comment by Tyriar** [comment]
Merging into https://github.com/Microsoft/vscode/issues/14613

**Comment by Tyriar** [comment]
This should hopefully be fixed in tomorrow's Insiders build (via https://github.com/Microsoft/vscode/commit/63f1fa66800bf641de5e36027610503ba75085b5). Please let me know if it still reproduces.

See https://github.com/Microsoft/vscode/issues/13625 for more information.
