### ISSUE TITLE
Activation events are being trimmed

### ISSUE THREAD

**Issue by lramos15** [microsoft/vscode#169869]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/4544166/209189783-47c9933d-5f35-4759-a159-5fa362b32de9.png">

1. Open vscode.dev
2. Open dev tools
3. 🐛 See activation events are being trimmed for being too long

Code pointer for the classification piece https://github.com/microsoft/vscode/blob/3792c08268550f461f277dce342ed1be374f4ede/src/vs/workbench/api/common/extHostExtensionService.ts#L71-L72

Assigning @jrieken based on classification ownership.

**Comment by lramos15** [comment]
Anyway someone can take a look at this for debt week? We're losing data here

**Comment by jrieken** [comment]
Should we take that as signal that the data isn't needed and that we should delete the corresponding events? This is `activatePlugin` and `extensionActivationTimes`. @devinvalenciano @digitarald do any jobs/queries depend on these events?

**Comment by devinvalenciano** [comment]
@jrieken We do have jobs that depend on activateplugin.  Not aware of any that use extensionactivationtimes.

@lramos15 Do you have a sense of what portion of activateplugin events this affects?

**Comment by lramos15** [comment]
> @lramos15 Do you have a sense of what portion of activateplugin events this affects?

We don't have any telemetry on this, maybe we should add some to indicate when an event is trimmed.

**Comment by jrieken** [comment]
I am giving this a wont-fix because I don't know how else to tackle this. It seems very rare that an extension has soo many activation events that they overflow the event. I can't tell if `activationEvents` is used or not (ping @devinvalenciano - this is about that one data property of those events)
