### ISSUE TITLE
Consider adopting a new CSS syntax highlighting grammar

### ISSUE THREAD

**Issue by BenjaminAster** [microsoft/vscode#169873]
When authoring multiline CSS strings, e.g.
```css
.foo::after {
	content: "Hello \
world!";
}
```
VSCode's syntax highlighter messes up pretty badly. Here is a real-world example of using a multiline CSS string in a data URL to create a mask for random noise:
![image](https://user-images.githubusercontent.com/63414473/209197117-d9954282-4366-4546-aa8c-c6b634d0dd4d.png)
Notice how all code after the multiline string is highlighted in yellow.

This issue has already been reported multiple times (#125739, #134642, #146146, #147712, #159730), but all of them have been closed as a duplicate of atom/language-css#181, which through the sunset of Atom has now been closed and archived, too. Creating multiline strings makes things _a lot_ more readable when creating inline SVGs for background images and masks, and currently they are practically unusable in VSCode. I would be greatful if you could prioritize this, especially since I do not believe it to be a very difficult bug to fix.

Tested in VSCode version `1.74.2` (stable) and `1.75.0-insider` (pre-release).

**Comment by alexr00** [comment]
Since the upstream repo has been archived I've repurposed this issue into adopting a new CSS grammar.

**Comment by romainmenke** [comment]
@alexr00 I am unsure why I would go through the trouble of making an entirely new grammar for CSS, struggle to gain adoption just to have VSCode swoop in when it reaches critical mass?

Why can't we do this effort in collaboration within VSCode from the start?
I am happy to contribute in a technical capacity but I have zero interest in doing all the other critical parts to make a 3de party extension successful.

**Comment by alexr00** [comment]
Once something is maintained by the VS Code team then we have to keep maintaining it. At this time we don't have a developer dedicated to maintaining a CSS grammar, which is why we rely on the community.

**Comment by romainmenke** [comment]
> then we have to keep maintaining it.

> which is why we rely on the community

But in practice this will most likely be a single individual right?
And that single individual would also have to keep maintaining it, but with fewer resources.
How do we make sure that this is sustainable and that it is a good long term solution?

It is also just an impossibly small group of people who fit these characteristics :
- has the required knowledge about CSS
- has the required knowledge about grammars for VS Code
- has spare capacity for yet another project

Are there volunteers in the VS Code team to help out on a 3rd party package with aspects that do not require in depth knowledge about CSS?

- triaging issues
- writing tests
- reviewing code changes
- ...

**Comment by argyleink** [comment]
I figured y'all would take the atom grammars as they are, adopting / forking them, and then y'all become the new canonical reference we submit grammar updates to. That's why [I made a couple PRs](https://github.com/microsoft/vscode/pull/170781) to here, seems the easiest route is y'all to pick up the reigns where they got dropped? 

I'm with Romain here, waiting for some new community driven one is too much work on that maintainer. There's a perfectly good foundation ready to not be an upstream anymore.

**Comment by alexr00** [comment]
> - has the required knowledge about CSS
> - has the required knowledge about grammars for VS Code
> - has spare capacity for yet another project
...
> - triaging issues
> - writing tests
> - reviewing code changes

With the exception of writing tests (as we do have some basic grammar tests to keep our grammar integration healthy) these needs are all same reasons that the VS Code team doesn't want to own the grammars. We know maintaining a grammar can be a lot of work and we greatly appreciated all the work that folks do on the OSS projects we depend on for our grammars. https://github.com/jeff-hykin/better-cpp-syntax, https://github.com/fadeevab/make.tmbundle, https://github.com/microsoft/TypeScript-TmLanguage, and https://github.com/jeff-hykin/better-shell-syntax to name just a few.

**Comment by alexr00** [comment]
We tentatively created a new repo for the old atom grammar where we plan to take fixes: https://github.com/microsoft/vscode-css

We're still working out what taking fixes will look like, so any PRs made against that repo may take a while to receive attention.

**Comment by romainmenke** [comment]
Thank you so much @alexr00 for considering a different way forward 🎉

**Comment by argyleink** [comment]
should i move my PRs (#170782, #170781) to that repo now? or wait a bit?
thanks for considering alternative routes for this ❤️

**Comment by alexr00** [comment]
@argyleink I would suggest you wait a bit. We don't currently know how we're going to take fixes since we don't have anyone who can review the changes at the moment.

**Comment by alexr00** [comment]
@argyleink I think we'll soon start merging PRs in https://github.com/microsoft/vscode-css. If you move your PRs there then I will make sure they get reviewed.

**Comment by alexr00** [comment]
Closing as we have move the grammar to https://github.com/microsoft/vscode-css
