### ISSUE TITLE
Compiling problem

### ISSUE THREAD

**Issue by 1GretManish** [microsoft/vscode#169833]
Type: <b>Performance Issue</b>

look at first SS its error free code but still showing error.
![image](https://user-images.githubusercontent.com/94178406/209143190-0037e883-0c7d-4021-bc72-b9195316ca37.png)
and another SS running code .
![image](https://user-images.githubusercontent.com/94178406/209143349-7f98c3be-5624-4b1d-a523-9f529318f898.png)
Kindly resolve this issue.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-8145U CPU @ 2.10GHz (4 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.88GB (3.13GB free)|
|Process Argv|--crash-reporter-id 11f3b7b6-d440-4811-bc17-47f3b2d2660c|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    2	   107	  5396	code main
    1	    87	  6256	   issue-reporter
    0	    27	  7088	   crashpad-handler
    0	   123	  7988	   shared-process
    0	    80	   400	     ptyHost
    0	    77	  3680	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -noexit -command "try { . \"c:\Users\master\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\contrib\terminal\browser\media\shellIntegration.ps1\" } catch {}"
    0	     6	 14364	       console-window-host (Windows internal process)
    0	    84	  8412	     fileWatcher
    0	    40	 10852	   utility-network-service
   10	   200	 11812	   window (TechMan.c - Untitled (Workspace) - Visual Studio Code)
    0	   202	 14148	   extensionHost
    0	    28	  2508	     c:\Users\master\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64\bin\cpptools.exe
    0	     3	  8696	       "c:\Users\master\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64\bin\cpptools.exe"
    0	    17	  4924	         c:\Users\master\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64/bin/cpptools-srv.exe 2508 {7F5D36B0-F856-4C57-A420-9D88138141D9}
    0	    11	  2404	           console-window-host (Windows internal process)
    0	    11	 15336	       console-window-host (Windows internal process)
    0	    78	 10224	     "C:\Users\master\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\master\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=14148
    2	   163	 15556	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (TechMan.c - Untitled (Workspace) - Visual Studio Code)
|    Folder (C Language): 3 files
|      File types: c(1) exe(1)
|      Conf files:
|    Folder (JAVA Language): 3 files
|      File types: class(1) java(1)
|      Conf files:
|    Folder (Python Language): 2 files
|      File types: py(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (35)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-intelephense-client|bme|1.8.2
c-cpp-compile-run|dan|1.0.19
dart-code|Dar|3.56.0
code-runner|for|0.11.8
vscode-pull-request-github|Git|0.56.0
go|gol|0.37.0
csharp|ms-|1.25.2
vscode-edge-devtools|ms-|2.1.1
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
powershell|ms-|2022.12.1
platformio-ide|pla|2.5.5
vscode-thunder-client|ran|2.2.0
vscode-rapidapi-client|Rap|1.8.2
java|red|1.13.0
rust-analyzer|rus|0.3.1325
vscode-lldb|vad|1.8.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
vscode-spring-initializr|vsc|0.11.1
volar|Vue|1.0.16

(2 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by andreamah** [comment]
Please file this issue with the c/c++ extension: https://github.com/Microsoft/vscode-cpptools
