### ISSUE TITLE
smoketest: seeing 'Duplicate object key' warning for settings.json

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#16981]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:06:36.411Z)
- OS Version: Darwin x64 15.6.0
- Extensions:

---

Steps to Reproduce:

1. open user settings.json
1. open problems view

Observe: 10 'Duplicate object key' warnings are showing up. This looks silly for the OOTB experience.

**Comment by weinand** [comment]
@sandy081 duplicate of what?

**Comment by sandy081** [comment]
@weinand I was searching for it :)

Duplicates #16674.
