### ISSUE TITLE
[Perf] Use `IConfigurationChangeEvent#affectsConfiguration`

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#169806]
related https://github.com/microsoft/vscode/issues/168639

The configuration service encapsulates all our configuration settings (~750 keys) and its event fires whenever any of them change.  Naturally this service has many listener. This combination means all listeners should be conservative and avoid unnecessary work, e.g a listener that's interested in the `foo.bar` setting shouldn't do something when the `bazz.bazz` setting changes. For that the [`IConfigurationChangeEvent#affectsConfiguration`](https://insiders.vscode.dev/github/microsoft/vscode/blob/d251600ec5d258039c6424bb57536bb9072417a1/src/vs/platform/configuration/common/configuration.ts#L70)-util exists. It allows to quickly check if an event affects "your" setting, this is a good [sample](https://github.com/microsoft/vscode/blob/f3e13c1e2d1b45aa7160c42d71148705a02f7517/src/vs/workbench/contrib/codeEditor/browser/toggleMultiCursorModifier.ts#L53-L57) of being conservative. 

The following list (is hopefully complete) and all listeners that _unconditionally_ do work when _any_ configuration changes. This is wasteful and esp hurtful during startup (when all settings are registered)

---

- [x] src/vs/platform/list/browser/listService.ts @joaomoreno 
  * 686, 49: configurationService.onDidChangeConfiguration(() => {

- [x] src/vs/platform/quickinput/browser/commandsQuickAccess.ts @bpasero 
  * 221, 44: configurationService.onDidChangeConfiguration(() => this.updateConfiguration()));

- [x] src/vs/platform/request/node/requestService.ts @sandy081 
  * 56, 39: configurationService.onDidChangeConfiguration(() => this.configure(configurationService.getValue()), this));

- [x] src/vs/platform/telemetry/common/telemetryService.ts @lramos15 
  * 68, 30: _configurationService.onDidChangeConfiguration(this._updateTelemetryLevel, this, this._disposables);

- [x] src/vs/platform/telemetry/common/telemetryUtils.ts @lramos15 
  * 94, 30: configurationService.onDidChangeConfiguration(event => {

- [x] src/vs/platform/windows/electron-main/windowImpl.ts @chrmarti @sbatten
  * 619, 44: configurationService.onDidChangeConfiguration(e => this.onConfigurationUpdated(e)));

- [x] src/vs/workbench/browser/layout.ts @sbatten 
  * 277, 44: configurationService.onDidChangeConfiguration(() => this.doUpdateLayoutConfiguration()));

- [x] src/vs/workbench/browser/workbench.ts @bpasero 
  * 227, 39: configurationService.onDidChangeConfiguration(() => this.setFontAliasing(configurationService)));

- [x] src/vs/workbench/common/editor/editorGroupModel.ts @bpasero 
  * 210, 44: configurationService.onDidChangeConfiguration(() => this.onConfigurationUpdated()));

- [x] src/vs/workbench/contrib/localHistory/browser/localHistoryTimeline.ts @bpasero 
  * 88, 44: configurationService.onDidChangeConfiguration(e => {

- [x] src/vs/workbench/contrib/markers/browser/markersFileDecorations.ts @sandy081 
  * 69, 31: _configurationService.onDidChangeConfiguration(this._updateEnablement, this),

- [x] src/vs/workbench/contrib/mergeEditor/browser/model/diffComputer.ts @hediet 
  * 25, 29: configurationService.onDidChangeConfiguration,

- [x] src/vs/workbench/contrib/mergeEditor/browser/view/editors/codeEditorView.ts @hediet 
  * 63, 29: configurationService.onDidChangeConfiguration,
  68, 29: configurationService.onDidChangeConfiguration,
  73, 29: configurationService.onDidChangeConfiguration,

- [x] src/vs/workbench/contrib/mergeEditor/browser/view/mergeEditor.ts @hediet 
  * 102, 29: configurationService.onDidChangeConfiguration,

- [x] src/vs/workbench/contrib/mergeEditor/browser/view/viewModel.ts @hediet 
  * 89, 29: configurationService.onDidChangeConfiguration,

- [x] src/vs/workbench/contrib/relauncher/browser/relauncher.contribution.ts @bpasero
  * 60, 44: configurationService.onDidChangeConfiguration(e => this.onConfigurationChange(this.configurationService.getValue<IConfiguration>(), e)));

- [x] src/vs/workbench/contrib/tasks/browser/abstractTaskService.ts @meganrogge 
  * 287, 45: _configurationService.onDidChangeConfiguration(() => {

- [x] src/vs/workbench/contrib/testing/browser/testingExplorerView.ts @connor4312 
  * 570, 39: configurationService.onDidChangeConfiguration(() => {
  575, 39: configurationService.onDidChangeConfiguration(() => {

- [x] src/vs/workbench/contrib/welcomeWalkthrough/browser/walkThroughPart.ts @bhavyaus  
  * 358, 61: configurationService.onDidChangeConfiguration(() => {

- [x] src/vs/workbench/services/editor/browser/editorService.ts @bpasero 
  * 102, 44: configurationService.onDidChangeConfiguration(e => this.onConfigurationUpdated(this.configurationService.getValue<IWorkbenchEditorConfiguration>())));

**Comment by lramos15** [comment]
`telemetryUtils.ts` must remain an unconditional listener because it records anytime the settings change to gain a better understanding of what settings user's are adjusting.

**Comment by jrieken** [comment]
@lramos15 makes sense but you could debounce it and merge the listening since you being called repeated during startup

**Comment by bpasero** [comment]
Noticed the configuration listener in editor to be quite expensive, blocking startup:

![image](https://user-images.githubusercontent.com/900690/211260748-e082d823-88f5-49b7-a52b-1b796a4518ad.png)

Refs:

https://github.com/microsoft/vscode/blob/eaa9b1b70eaad291980a3e74d1748ca7d9bbd195/src/vs/editor/common/services/modelService.ts#L176

**Comment by bpasero** [comment]
Ping to remaining owners @sbatten @hediet @chrmarti @meganrogge
