### ISSUE TITLE
Per language settings are needed

### ISSUE THREAD

**Issue by cfjedimaster** [Microsoft/vscode#16983]
- VSCode Version: 1.7.2
- OS Version: Win10

Steps to Reproduce:

1. Open a Markdown file and begin writing an article.
2. Code begins offering text suggestions which get in the way of writing.

For example, I type 'te' and it suggest 'test' and 'testing' and if I try to hit enter because I'm at the end of the line and want to go to the next line, Code enters a word I didn't want.

Basically I want to turn off autocomplete for markdown, which would be easy if I could specify settings on a per language basis that override the system defaults.

**Comment by tjvantoll** [comment]
This is a big problem for me as well. I have a dedicated project I keep articles I write in Markdown, and in that project I set `"editor.wrappingColumn": 0`, `"editor.quickSuggestions": false`, and a few other options that makes writing easier.

However most of my work is done on projects that have both Markdown and non-Markdown files—for instance a `README.md` file in a project that is predominantly code. In those cases I’d love to be able to set `"editor.wrappingColumn"` and `"editor.quickSuggestions"` based on the type of file that I’m working on.

Thanks! Love the work you all do. This feature would help me spend even more time in Code 😄

**Comment by mjbvz** [comment]
I agree this could be useful.  #11879 is tracking support for these sort of settings

Thanks.
