### ISSUE TITLE
Registering a fs provider shouldn't cause a dom layout in the breadcrumbs

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#169875]
* profile on startup and have a css file opened
* the `EditSessionsContribution` registers a fs provider for `vscode-edit-sessions`
* this somehow ends up causing a dom layout via the breadcrumbs

<img width="606" alt="image" src="https://user-images.githubusercontent.com/5047891/209201943-d85716b1-f1d2-4f0c-b369-d8ce29c7c9a0.png">

**Comment by jrieken** [comment]
The trigger is that registering a file system causes a label service change event which causes breadcrumbs to re-render. Tho, we can likely optimise this
