### ISSUE TITLE
Code action menu does not show shortcuts any more since 1.74

### ISSUE THREAD

**Issue by lgrammel** [microsoft/vscode#169834]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.2
- OS Version: MacOS Monterey 12.6

Steps to Reproduce:

1.  Open the quick-fix code action menu when some code actions have shortcuts defined (via https://code.visualstudio.com/docs/getstarted/keybindings#_custom-keybindings-for-refactorings )
2. No shortcuts are shown in the code action menu.

Expected: 

The quick-fix menu shows shortcuts for actions that have them. This is how it worked in 1.73 and before.

**Comment by mjbvz** [comment]
Seems to be working now:

<img width="660" alt="Screenshot 2023-03-14 at 5 04 27 PM" src="https://user-images.githubusercontent.com/12821956/225168753-66e5834e-63c2-4a35-a387-1b4550c3c28c.png">

I suspect this was fixed sometime in the last few months
