### ISSUE TITLE
Integrated terminal messed up font rendering

### ISSUE THREAD

**Issue by lazpavel** [microsoft/vscode#169870]
Does this issue occur when all extensions are disabled?: Yes

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:27:19.253Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 6.0.12-arch1-1
Sandboxed: No

Steps to Reproduce:
The integrated terminal font gets messed up after a few commands (usually build commands that print a lot to the console output). The issue does reproduce with all extensions disabled. Killing the terminal and re-opening usually fixes but in a couple of commands the font gets messy again. Another temporary workaround is to change some terminal properties back and forth.  
Note: Selecting the messed-up font renders it correctly.

![Screenshot from 2022-12-14 11-28-04](https://user-images.githubusercontent.com/85319655/209190431-3c737ae1-12a3-420a-be78-c1e3a2682276.png)

**Comment by lazpavel** [comment]
`"terminal.integrated.gpuAcceleration": "off"` seems to solve it

**Comment by zeroepoch** [comment]
I'm seeing something similar to this, but rather than fixing the rendering when highlighting text it creates the problem. Certain characters get offset up or down slightly, but not all in the same word. Maybe has something to do with my font, Inconsolata? Restarting the terminal sometimes fixes the issue.

**Comment by thatsthat** [comment]
I have exactly the same problem using VSCode in Arch Linux with i3 did anyone find a solution other than disabling GPU acceleration? (I have a slow laptop)

**Comment by readandwrite864** [comment]
Debian i3wm same problem. GPU render works fast, I can tell because scrolling and selection doesn't lag. However, characters are messed up. CPU render is slow but correct. 

There is another render option called `canvas`. It seems that it works both fast and correct. Will use this option for now.

**Comment by Tyriar** [comment]
Does changing the font help resolve this?

**Comment by thatsthat** [comment]
Doesn't help in my case

**Comment by Tyriar** [comment]
Looks like a problem with Chromium GPU acceleration in `<canvas>`, you can try updating your graphics driver and if that doesn't work you can move to the DOM-based renderer with this setting:

```
"terminal.integrated.rendererType": "dom"
```

/label terminal terminal-rendering *question
