### ISSUE TITLE
undefined when searching for symbol

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode#16984]
* in the vscode workspace
* open a javascript file
* run workspace symbol search (cmd+t)
* search for `getDefaultUserDataPath`
* 🐛 the UI has a label that prints `undefined`

<img width="272" alt="screen shot 2016-12-09 at 15 19 03" src="https://cloud.githubusercontent.com/assets/1794099/21052135/a7b00ef2-be23-11e6-8a3b-8e2621d01da6.png">

**Comment by joaomoreno** [comment]
@mjbvz Apparently, the `release/1.8` branch has already been created, before you pushed this to `master`. Since this is assigned for November, I assume it is meant for 1.8, so I cherry picked it to `release/1.8`: 214034ac04846bc1f5c458f365e97023ce5f2a70.

cc @Tyriar @ramya-rao-a
