### ISSUE TITLE
VS Code Source Control gets stuck on sync Changes

### ISSUE THREAD

**Issue by MasterANK** [microsoft/vscode#169843]
Hi,  I am new to Git and When i use VS Code source control to publish my changes in my project the source control gets stuck on synchronizing changes and the commit doesn't get showed up even after i reload the VS code window.  Please Help me with this.

Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. Connect a Github Project with VS Code
2. Make a change in any file
3. Commit Changes in source control of VS code
4. Press the sunc button.

**Comment by MasterANK** [comment]
**I found the issue which was causing this.

The Git on my computer was not authorized with Github. This can easily be fixed by issuing a commit using Git terminal(I used Gitbash for this).**

I still don't understand why VS Code got stuck on synchronizing changes instead of giving an error. It could clearly cant synchronize anything until Git gets authorized for my Github Account.

**Comment by lszomoru** [comment]
@MasterANK, thank you very much for the update. VS Code implements all git source control functionality by spawning a child processes and executing `git.exe`. The Git authentication pipeline has multiple "hooks" where various applications (Git Credential Manager, VS Code) can "hook into" the authentication pipeline and fulfil the authentication request. 

Based on your description it seems like you had an application configured (Git Credential Manager?) to handle the authentication request that expects user input from the terminal. VS Code is unable to detect this as it invoked `git.exe` and it is waiting for the child process to complete.
