### ISSUE TITLE
DAP

### ISSUE THREAD

**Issue by suleymansahin** [microsoft/vscode#169837]
Type: <b>Feature Request</b>
![Error](https://user-images.githubusercontent.com/1921922/209153086-e4416335-331b-4281-a00a-afb2ed7c0745.PNG)

Hello I like to handle event when I try to apply filter on variables view. When I try to search. When I look into the documents, unfotunately I couldnt find any information about it

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

**Comment by roblourens** [comment]
> Hello I like to handle event when I try to apply filter on variables view

Sorry, I don't understand what you're asking for, need more details

**Comment by suleymansahin** [comment]
@roblourens  I like to handle filter(search) event, while searching variable on variables view

**Comment by roblourens** [comment]
I don't know what you mean by "handle". What exactly do you want to do?

**Comment by suleymansahin** [comment]
> I don't know what you mean by "handle". What exactly do you want to do?

'catch the event'

**Comment by roblourens** [comment]
I really need specific details about what you are asking for, I still don't know
