### ISSUE TITLE
Is it possible to add a copy word shortcut

### ISSUE THREAD

**Issue by weartist** [microsoft/vscode#169902]
Type: <b>Feature Request</b>

I see that there is a shortcut to delete the current word, but no shortcut to copy, I would be willing to submit a PR if I could

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 21.5.0
Modes:
Sandboxed: No

**Comment by rioj7** [comment]
You can construct the command yourself with the extension [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command)

```json
{
    "key": "alt+x",  // some key combo
    "command": "extension.multiCommand.execute",
    "when": "editorTextFocus && !editorHasSelection",
    "args": { 
        "sequence": [
            "editor.action.addSelectionToNextFindMatch",
            "editor.action.clipboardCopyAction"
            "cursorRight",
           { "command": "type", "args": {"text": " "} },
            "editor.action.clipboardPasteAction"
        ]
    }
},
{
    "key": "alt+x",  // same key combo
    "command": "extension.multiCommand.execute",
    "when": "editorTextFocus && editorHasSelection",
    "args": { 
        "sequence": [
            "editor.action.clipboardCopyAction"
            "cursorRight",
           { "command": "type", "args": {"text": " "} },
            "editor.action.clipboardPasteAction"
        ]
    }
}
```

**Comment by ArturoDent** [comment]
By the way - @rioj7 - if you use `jsonc` as the codeblock language you won't get the red comments:

```jsonc
    "key": "alt+x",  // some key combo
```

**Comment by weartist** [comment]
> ```js
> cursorRight
> ```

Thank you very much! can you directly copy the word where the current cursor is in this way? I only see the right and left of the copy cursor

**Comment by rioj7** [comment]
@weartist What happens when you place the cursor in a word and apply the key binding?

> I only see the right and left of the copy cursor

I don't understand, what is a `copy cursor`

**Comment by weartist** [comment]
> @weartist What happens when you place the cursor in a word and apply the key binding?
> 
> > I only see the right and left of the copy cursor
> 
> I don't understand, what is a `copy cursor`

For example, the current contant is line: 'one two three', my cursor is currently between t and w in 'two'. I hope there is a shortcut key to directly copy the word where the cursor is. If so, I can save an operation. Currently I need to select first, then copy.

**Comment by rioj7** [comment]
@weartist recently VSC has added the command `runCommands` you can now perform part of the functionality of extension [multi-command](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command).

```jsonc
{
  "key": "ctrl+alt+c",  // some key combo
  "command": "runCommands",
  "when": "editorTextFocus && !editorHasSelection",
  "args": {
    "commands": [
      "editor.action.addSelectionToNextFindMatch",
      "editor.action.clipboardCopyAction"
    ]
  }
}
```

Choose a key combo that works for you
