### ISSUE TITLE
Expand unresolved comments in editor

### ISSUE THREAD

**Issue by JonasMa** [microsoft/vscode#169928]
Our users want to see which comments need to be worked on next. During a review round there might be some comments which are not actionable anymore as their threads got resolved. For better overview we think it is valuable to be able to expand only all unresolved (and therefore actionable) comments.
Since [#158316](https://github.com/microsoft/vscode/issues/158316) we can't use `CommentThread.collapsibleState` anymore to do this from our extension.
Reading [#158316 (comment)](https://github.com/microsoft/vscode/issues/158316#issuecomment-1217611689) there is no intention in bringing back this functionality. Introducing commands like `expandUnresolvedComments` (and probably also `expandAllComments`) could be a way bring back some control over comment collapsed state to the extension without the need for extension to [mess with user state](https://github.com/microsoft/vscode/issues/167253#issuecomment-1327582527) directly.  

cc @alexr00 @hermannloose @laurentlb

**Comment by alexr00** [comment]
The new command is "Comments: Expand Unresolved Comments".

**Comment by alexr00** [comment]
To verify:
- Open a workspace with unresolved comments (a PR with comments using the GitHub Pull Requests and Issues extension works well for this).
- Collapse some comments in the editor.
- Run "Comments: Expand Unresolved Comments" and verify that all unresolved comments are expanded.

**Comment by ulugbekna** [comment]
If a comment is already collapsed when I open the file, the command "Expand Unresolved Comments" doesn't work

repro: 

1. collapse an unresolved comment
2. close the current tab
3. open the tab again
4. 🐛 run the command - the comment is not expanded 


https://user-images.githubusercontent.com/16353531/234582729-f26b7b83-6b65-422e-bae6-eb6c610621b7.mov
