### ISSUE TITLE
I'm often asked to log in again with GitHub

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#169914]
Yesterday I ran VS Code Insiders from the Downloads folder, and I used `--user-data-dir`. And today, after updating to latest Insiders I had to log in again. Here's what I noticed in one of the logs:

```
2022-12-22 19:42:40.951 [error] SyntaxError: Unexpected token y in JSON at position 0
    at JSON.parse (<anonymous>)
    at y.$getPassword (vscode-file://vscode-app/Users/alex/Downloads/Visual%20Studio%20Code%20-%20Insiders%202.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1564:41752)
```

I often also use `vscode-bisect` which downloads various versions of VS Code Insiders and uses a custom user data dir. Often I end up being signed out 🤷 .

cc @bpasero

**Comment by bpasero** [comment]
I have seen this error before and I had a time when I had to log in all the time, but not for a while anymore.

**Comment by bpasero** [comment]
Now again I hit this almost daily that I have to re-login.

**Comment by bpasero** [comment]
After 1on1, learned that this is caused simply by launching VS Code from a different path. A suggested fix is to not destroy existing credentials on startup when we fail to decrypt but only do so when we actually need to write new credentials to the store.

**Comment by andreamah** [comment]
> After 1on1, learned that this is caused simply by launching VS Code from a different path. A suggested fix is to not destroy existing credentials on startup when we fail to decrypt but only do so when we actually need to write new credentials to the store.

What are some verif steps? I'm a little confused on what you mean by "launching VS Code from a different path".

**Comment by TylerLeonhardt** [comment]
verification:

* Launch VS Code insiders, make sure you're logged in to _something_
* Close VS Code Insiders
* Open a terminal (not in VS Code Insiders) and run (This will spin up old insiders builds):
```
npx vscode-bisect --good f1b09237cd400d92987cf7a9681995e8011ef54c --bad 07d6f5b35fac559504dec65e3073d796b2d25a55
```
* Note that you are not logged in to anything (expected)
* in the terminal say `good` or `bad` doesn't matter
* Now once `vscode-bisect` is done open _your_ VS Code Insiders
* You should still be logged in to your stuff
