### ISSUE TITLE
Lancement de Python et HTML 

### ISSUE THREAD

**Issue by CITIX777** [microsoft/vscode#169927]
![Git Hub 2022-12-23 154101](https://user-images.githubusercontent.com/87914253/209353695-8cd33c71-9d78-4a1b-83a8-0eeb695cea1a.png)
ADD ISSUE DESCRIPTION HERE

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0
Embedder: codespaces

![image](https://user-images.githubusercontent.com/87914253/209353753-d528d68d-7032-4a0c-847f-b43c233f85fe.png)

Bonjour,

Je n'arrive pas à lancer la page html.
Pour  la page Python, tout fonctionne correctement.

Pourriez-vous m'aider svp?

Bien à vous

**Comment by boltex** [comment]
@CITIX777 je comprends pas ce que vous voulez dire par 'lancer' la page HTML.

Un fichier html doit etre servi par un serveur et visualizée dans un navigateur.

**Comment by lszomoru** [comment]
@brettcannon, could you please help triage this issue? Thank you!

**Comment by brettcannon** [comment]
I can't read French, so I unfortunately don't know what's being asked. Based on Google Translate, it seems like this is actually asking how to launch Live Preview for the HTML page and has nothing to do with Python (I think it's saying Python is running fine).

If the translation and my understanding is correct, then the solution is https://marketplace.visualstudio.com/items?itemName=ms-vscode.live-server . If this is wrong we can reopen the issue.
