### ISSUE TITLE
num pad on the keyboard does not work in VSCode when Chrome browser displays a notification

### ISSUE THREAD

**Issue by five70apps** [Microsoft/vscode#16995]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|csharp|ms-vscode|1.5.3|

---

Steps to Reproduce:

1. have google calendar opened in the Chrome browser (Version 54.0.2840.99 m (64-bit))
2. have a notification displayed by the Chrome browser, for example a meeting reminder
3. notice that in VSCode the num pad does not work, pressing any keys on the num pad results in moving the cursor around, just like the numlock would be off; at the same time, the num lock keys are working properly in other applications (notepad, word, edge browser)
4. close the Chrome notification, then switch to VSCode, now the num pad works properly.

**Comment by alexandrudima** [comment]
@five70apps This is most weird. 

Please open an issue against electron at https://github.com/electron/electron , as we don't deal with interpreting numlock on/off at our level, it could be an Electron or a Chromium issue.

**Comment by alexandrudima** [comment]
This is an upstream issue (possibly within Chromium), and there are no known workarounds that we could implement on our side. This means there is no possible code change for us to do in VS Code sources to improve things. 

To keep the number of issues in our inbox at a manageable level, we’re closing issues that have been on the backlog for a long time but haven’t gained traction or that are not actionable. Thank you for your time and understanding.
