### ISSUE TITLE
GitHub auth flow doesn't return to the correct window

### ISSUE THREAD

**Issue by alexdima** [microsoft/vscode#169913]
* start the GH auth flow from window1
* focus window2. This step is not necessary if you use multiple screens and the browser is on the same screen as window2. But because I couldn't easily record both screens I manually focus here.
* continue the GH auth flow in the browser
* the flow returns to window2 instead of the originating window

I grabbed the URL and it has a windowId in it:
```
https://github.com/login/oauth/authorize?client_id=xxx&redirect_uri=https%3A%2F%2Fvscode.dev%2Fredirect&scope=read%3Auser&skip_sso=true&state=vscode-insiders%253A%252F%252Fvscode.github-authentication%252Fdid-authenticate%253Fnonce%25xxx%2526windowId%253D4
```

But perhaps the windowId gets lost somewhere along the way or perhaps there is a bug on the main process. Anyways, here is the recording:

https://user-images.githubusercontent.com/5047891/209321606-dff249c6-aa08-472a-8d49-4633e641de54.mp4

**Comment by TylerLeonhardt** [comment]
@joaomoreno, Alex and I talked about this and based on what I'm seeing, I don't think it's an auth issue and seems to be a Uri Handler issue. If it was an auth bug, I would expect the `windowId` to be missing from the URL but that doesn't seem to be the case here.

**Comment by bpasero** [comment]
@joaomoreno logging revealed something that I then was able to verify in code: the change in https://github.com/microsoft/vscode/commit/2cd7a70d629fd5cac500341174291b0bfd120a6c#diff-496803cccda5ba64a749ce4b09f8734c8c98f009f2f7daa24d6d7deabf1e3dccR34 changed the `arg` kind. When previously a `URI` was passed, now it is a `[URI, options]`. So the code here needs to be adjusted:

https://github.com/microsoft/vscode/blob/1bbd5e1e87d8cae9977e428a35e0222cc0958392/src/vs/platform/url/common/urlIpc.ts#L52

I think the code could get some type love and not use `any` for that matter.

**Comment by bpasero** [comment]
Hm, I am actually not a 100% sure if that commit caused the regression because I also see you changed the receiving end, but the problem is still the `Array` of `URI` and `options` being passed in when previously it was just the `URI`

**Comment by joaomoreno** [comment]
Great catch, that's exactly right! I did not adopt the serialization format in the router. 👏 

> I think the code could get some type love and not use `any` for that matter.

I'm open to suggestions, though I'm not sure there is anything that can be done here. The whole point of these `*Ipc.fs` implementations is to (de)serialize live objects into opaque JSON things. You can add a bunch of interfaces that lock things in, but in the end we still need the generic `call<T>` and `listen<T>` methods, so I'm not sure we'd gain anything.

**Comment by bpasero** [comment]
> I'm open to suggestions

Basically what [`ProxyChannel`](https://github.com/microsoft/vscode/blob/d8568bb19e5acb54253afb2cb48123785db2f8d9/src/vs/base/parts/ipc/common/ipc.ts#L1063) does by avoiding having to code out the underlying raw methods of the IPC flow and have just a typed interface for both sender and receiver. 

Yes, in the end you cannot know for sure what data is sent because we cannot enforce it, but `ProxyChannel` (or something similar) at least allows to only have 1 place for types and when changing something, it would show an error on both ends.

**Comment by joaomoreno** [comment]
How would you adopt that in the router?

**Comment by TylerLeonhardt** [comment]
So I've never been able to repro this bug... @joaomoreno is there some steps that really focus on this fix?
