### ISSUE TITLE
Build failed with timeout in: EditorModel - EditableTextModel.applyEdits touching edits: insert and replace

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode#169910]
Build: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197772
Changes: https://github.com/Microsoft/vscode/compare/6615806...6df315f

On MacOS like https://github.com/microsoft/vscode/issues/169909.

**Comment by chrmarti** [comment]
Another build with a timeout and other failures on the MacOS agent: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197798

@lszomoru This starts looking like an issue with the build agent (see also https://github.com/microsoft/vscode/issues/169909). Could it be low on memory?

**Comment by chrmarti** [comment]
Compile step timed out after 60m on MacOS: https://dev.azure.com/monacotools/a6d41577-0fa3-498e-af22-257312ff0545/_build/results?buildId=197693

**Comment by lszomoru** [comment]
We have no control on the hardware configuration of the MacOS agents. Not sure what I can do here.
