### ISSUE TITLE
File nesting doesnt work for .test.ts

### ISSUE THREAD

**Issue by JustinGrote** [microsoft/vscode#169987]
Type: <b>Bug</b>

I've tried multiple patterns: `${capture}.test.ts` and `${basename}.test.${extname}.

Is there something special about .test.ts I'm not aware?

VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:21:57.802Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2600 Six-Core Processor             (12 x 3850)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (9.64GB free)|
|Process Argv|--crash-reporter-id d15abc04-2f14-48d4-98ba-287dac26245f|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (25)</summary>

Extension|Author (truncated)|Version
---|---|---
codesnap|adp|1.3.4
markdown-checkbox|bie|0.4.0
markdown-mermaid|bie|1.17.3
markdown-preview-github-styles|bie|1.0.1
dendron-paste-image|den|1.1.1
vscode-generate-getter-setter|DSK|0.5.0
prettier-vscode|esb|9.10.3
todo-tree|Gru|0.0.220
vscode-peacock|joh|4.2.2
regionfolder|map|1.0.18
git-graph|mhu|1.30.0
js-debug-nightly|ms-|2022.12.1417
powershell-preview|ms-|2022.12.1
vscode-typescript-next|ms-|5.0.202212230
indent-rainbow|ode|8.3.1
pester-test|psp|2022.3.3
vscode-thunder-client|ran|2.2.1
vscode-yaml|red|1.10.1
vscode-sort-json|ric|1.20.0
even-better-toml|tam|0.19.0
vscode-inline-values-powershell|Tyl|0.0.7
errorlens|use|3.6.0
vscode-icons|vsc|12.0.1
better-align|wwm|1.1.6
vitest-explorer|Zix|0.2.34

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by lramos15** [comment]
```
    "explorer.fileNesting.patterns": {
        "*.ts": "${capture}.test.ts"
    },
```
Seems to do it for me.

**Comment by JustinGrote** [comment]
So my problem was I was using a workspace and one of the individual folders in the workspace had a `.vscode/settings.json` that had file nesting defined that took precedence, and I wasn't seeing the changes. I didn't get a warning in the settings GUI interestnly enough like it normally does, not sure, but closing as "not an issue" and sorry to waste your time @lramos15, if nothing than to confirm that I was indeed crazy :)
