### ISSUE TITLE
Feature negotiation between debug adapters and Code

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1699]
Some debug adapters may not support all features (that you add in the future). For example, php-debug does not support breaking on caught exceptions. There needs to be a way to notify VS Code that this feature should be disabled (greyed out) for the user. (low priority)

**Comment by weinand** [comment]
@felixfbecker this is in the works

**Comment by weinand** [comment]
This issue was moved to Microsoft/vscode-debugadapter-node#9

**Comment by weinand** [comment]
@felixfbecker I've moved this feature over to Microsoft/vscode-debugadapter-node#9
