### ISSUE TITLE
Deleted files show up in quick open if they were deleted when vscode was closed with the file not open

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode#16997]
One case from #14761:

- Open folder A
- Create a file 'foo.txt'
- Close the tab (ie cmd+w)
- Quit vscode
- Delete foo.txt
- Reopen folder A in vscode
- See that foo.txt is in quick open. If I try to open it, I get an error message

If foo.txt was open when I quit vscode, this doesn't repro (due to looking for it when vscode opens?) If I delete the file when vscode is open, this doesn't repro. I see this on MacOS and Windows.

**Comment by Tyriar** [comment]
I see it on Linux too when the file is not open.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/12665
