### ISSUE TITLE
Consider overflow for code actions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#169903]
* open `build/lib/compilation.ts`
* use `Options` as a type annotation
* trigger quick fix to get imports suggested
* 🪜 the list is very long! it would be better if you only some some and have a way to trigger QP with all all options

<img width="1281" alt="Screenshot 2022-12-23 at 08 57 08" src="https://user-images.githubusercontent.com/1794099/209296298-01748940-94ec-4030-bd46-c106cc463214.png">

**Comment by mjbvz** [comment]
Duplicate of #168955
