### ISSUE TITLE
List: Create a setting to control type navigation mode

### ISSUE THREAD

**Issue by joaomoreno** [microsoft/vscode#169924]
If `typeNavigationMode` would be a setting, we could have extensions overwrite its default value using the `configurationDefaults` extension point, instead of having them [set a context key](https://github.dev/VSCodeVim/Vim/blob/386a3b1319c58a83f9f5eebfded30d8689199e87/extensionBase.ts#L530).

cc @TylerLeonhardt

**Comment by eleanorjboyd** [comment]
Was all that was needed in verification checking to see if the setting exists? If that is all then yes I see the setting and this is verified.

**Comment by joyceerhl** [comment]
@tylerleonhardt did you mean `a` instead of `n`? I don't see a keybinding from Atom for `n`:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/30305945/214655220-bfc73196-e64a-4cd8-9527-17a2bb2631c8.png">

**Comment by TylerLeonhardt** [comment]
huh. Yeah I guess I meant `a`. If it works with `a` it's verified.
