### ISSUE TITLE
Extensions disappearing if I quit and reopen the app

### ISSUE THREAD

**Issue by sdphadke** [microsoft/vscode#169994]
Somehow my git extension doesn't get uninstalled, but the 2 following extensions always get uninstalled.

1. ms-python.python
2. PeterStaev.lego-spikeprime-mindstorms-vscode

**Comment by sdphadke** [comment]
I dont know why this is happening. I am on macOS Monterey (12.6.2).

**Comment by sdphadke** [comment]
MacBook Air (13-inch, Early 2015)

**Comment by sandy081** [comment]
May I know which version of VS Code you are in? 
How are you installing the extensions?

**Comment by sdphadke** [comment]
Version: VSCode 2019 1.74.2 (Universal)
I am installing extensions though the extension library (on the sidebar).

**Comment by sandy081** [comment]
Can you please provide a gif/video of what you are seeing?

**Comment by sdphadke** [comment]
It's not happening any more. IDK why. Thanks for your time though!
