### ISSUE TITLE
Git colored files for staged and not staged

### ISSUE THREAD

**Issue by rurikhero** [Microsoft/vscode#16993]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|Angular2|johnpapa|1.0.2|
|csharp|ms-vscode|1.5.3|

---

Just a suggestion, colored files for git staged status will be great. Green for staged and red for not staged. It's visually comfortable and intuitive to commit.

**Comment by fbnlsr** [comment]
Atom has this feature, and it's really useful.

<img width="303" alt="atom-tree-view" src="https://cloud.githubusercontent.com/assets/1923346/21073435/131f062e-bede-11e6-9ea8-60ecfc55575e.png">

**Comment by joaomoreno** [comment]
#178
