### ISSUE TITLE
Searching settings which are not listed in Most Commonly Used expands sections incorrectly

### ISSUE THREAD

**Issue by rebornix** [Microsoft/vscode#16996]
- VSCode Version: 1.8.0-Insiders
- OS Version: macOS

Steps to Reproduce:

1. Search any setting directly by pasting the setting name into the search bar, for example `diffEditor.renderIndicators`
2.  The expansion icon shows the section is expanded while actually it's not.
![screen shot 2016-12-09 at 10 33 47 am](https://cloud.githubusercontent.com/assets/876920/21060303/7e648226-bdfb-11e6-8b01-4991ea8259bc.png)

**Comment by sandy081** [comment]
Duplicates #17491
