### ISSUE TITLE
Switching branches from Powershell

### ISSUE THREAD

**Issue by Pdzoc** [microsoft/vscode#169966]
Type: <b>Bug</b>

1. Create new project (in my case it is Angular project)
2. type git checkout -b new-branch and modify files
3. use git add command and commit all changes
4. type git checkout master

In VS Code terminal I receive info: 'Switched to branch master', but in VS Code explorer I still see files available only in 'new-branch'. And in left down corner I see new-branch instead of master. I restarted VS Code few times - result is the same. I have to click on branch name in left down corner in order to switch to master branch. In previous versions of VS Code I did always use commands to switch between branches.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3 CPU       M 380  @ 2.53GHz (4 x 2527)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|5.86GB (1.42GB free)|
|Process Argv|--crash-reporter-id c17b32d0-949f-4127-882e-5be90549aead|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|15.0.3
LiveServer|rit|5.7.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
3d0df643:30613357
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by lszomoru** [comment]
@Pdzoc, does the "state" (ex: branch name) gets updated correctly if you press the "Refresh" command in the "Source Control" view?

**Comment by Pdzoc** [comment]
We can close this issue - the problem is gone. Probably it was temporary problem with my pc. Since that time I use git bash, but today I tested VS Code terminal with few projects and for now everything is allright.
