### ISSUE TITLE
[perf] consider to yield when creating workbench contributions

### ISSUE THREAD

**Issue by jrieken** [microsoft/vscode#169937]
We have many workbench contributions for the phase `Restored` and that's visible in telemetry. The median times are quite bad - half our users "wait" for longer than 80ms. 

<img width="802" alt="Screenshot 2022-12-23 at 17 50 16" src="https://user-images.githubusercontent.com/1794099/209372144-12c11c1d-22e3-40db-8699-cbc594989241.png">

IMO we should consider to yield while this is happening, e.g instantiate contributions for some time (15 or 30ms) and then schedule a task for more creation work

**Comment by bpasero** [comment]
@jrieken open for suggestions, the slight risk is that a contribution will no longer be guaranteed to be instantiated when layout is restored, but later.

For the `LifeCyclePhase.Eventually` we already have a concept of pushing the instantiation out to idle:

https://github.com/microsoft/vscode/blob/229c95c8ac119df9059491034436bd02be303e67/src/vs/workbench/browser/workbench.ts#L432-L436

Would you suggest doing the same for `LifecyclePhase.Restored`?

**Comment by jrieken** [comment]
I had something like [this](https://github.com/microsoft/vscode/blob/ab1a31add4608f484d555e3c791f03321a4dda5f/src/vs/workbench/common/contributions.ts#L119-L129) or a static allowed time (20ms) in mind so that instantiating all contributions doesn't block for too long. And yes there is a risk of the behavioural change because some extension can become instantiated slightly later but I believe that's manageable

**Comment by bpasero** [comment]
@jrieken one thing I just realise is that we seem to be logging `code/didStartWorkbench` only after setting `lifecycleService.phase = LifecyclePhase.Restored`:

https://github.com/microsoft/vscode/blob/70c45ba0297f1ce516eafbc56d679a4a2c5a17e7/src/vs/workbench/browser/workbench.ts#L429-L451

As such, we seem to actually be waiting for each workbench contribution that is registered on `LifecyclePhase.Restored` to be instantiated before marking the time. Maybe this could explain a bit of the variance we see with the perf bot, shouldn't we immediately mark `code/didStartWorkbench` and only then set the phase to `Restored`?

**Comment by bpasero** [comment]
Oh interesting, looks like we are lucky given this `then` usage:

https://github.com/microsoft/vscode/blob/70c45ba0297f1ce516eafbc56d679a4a2c5a17e7/src/vs/workbench/common/contributions.ts#L91

Even though calling `lifecycleService.phase = LifecyclePhase.Restored;` will emit the event that the phase is reached, given we await a `Promise` the contributions are instantiated only after. 

Anyway, I would maybe still make this more explicit and move the code that marks `code/didStartWorkbench` earlier?
