### ISSUE TITLE
Changing a selection to the end or beginning of a line while selecting multiple lines behaves wrong

### ISSUE THREAD

**Issue by t-sauer** [Microsoft/vscode#16990]
- VSCode Version: 1.8.0-insider 40243d1e01f426f54670f3dbaa6b77d18469310d
- OS Version: macOS 10.11.6

Steps to Reproduce:

1. Open a file with multiple lines of text (for simplicity assume 2 lines of text in here)
2. Place cursor in the middle of line 1
3. Start selection with Shift + Down (now the text from the start column, line 1 until start column, line 2 is selected, which is as intended)
4. Now change the selection to the start of line with Cmd + Shift + Left
5. Selection now goes from start column, line 1 to column 1, line 1 (expected selection: start column, line 1 to column 1, line 2)

This gif should clarify the problem:

![lineselection](https://cloud.githubusercontent.com/assets/5306662/21056760/43690b6a-be37-11e6-803a-35f57ad64747.gif)

Here is the selection I would expect: 
<img width="250" alt="screen shot 2016-12-09 at 17 50 40" src="https://cloud.githubusercontent.com/assets/5306662/21056977/0969bf62-be38-11e6-8ba1-4f9a3cf24690.png">

This problem appears in different scenarios based on if you started your selection upwards or downwards and if you want to change the selection to the start or the end of a line.

**Comment by alexandrudima** [comment]
Let's track in #17011
