### ISSUE TITLE
"PreLaunchTask" is not finished before the launching starts

### ISSUE THREAD

**Issue by zhengbli** [Microsoft/vscode#170]
I have a simple TypeScript project, and I need to generate sourcemap before debugging. 
I have a `tsc` task that does the job, and I set it as the `preLaunchTask` field for my launching configuration. However, the launch seems to be starting before the sourcemaps finished generating.

**Comment by wesleyeff** [comment]
I'm also seeing this. I believe it was working correctly in 0.9 but doesn't seem to be working correctly now.

**Comment by irakliy81** [comment]
Happens for me - the debugger seems to be launching before the pre-launch task completes. Was working fine in 0.9.

**Comment by isidorn** [comment]
Yes I acknowledge the bug, happened because of a change in our task framework.

**Comment by isidorn** [comment]
@dbaeumer now I wait for the task to finish if it is not a watching task. You can review it debugService.ts#592

**Comment by dbaeumer** [comment]
@isidorn makes sense. However you could even be smarter with watching tasks as well. You could add a listener for state changes on the task and the wait for the first 'inactive' event.

**Comment by isidorn** [comment]
But that can take forever and then I never launch debug, right?
I am a bit reluctant to add that.

**Comment by dbaeumer** [comment]
Yes that is true.

**Comment by psulek** [comment]
I'm experiencing same issue. In which version will be this fix? I'm on Version `0.10.3` / Commit `783ecf841a2b21edca6d86853670cae89b4c244f`

**Comment by isidorn** [comment]
This will be fixed in the next stable version after 0.10.3

**Comment by psulek** [comment]
@isidorn Ok, thanks
