### ISSUE TITLE
Uncomplete link to click with path containing spaces in the Terminal (Linux)

### ISSUE THREAD

**Issue by Sebultura666** [microsoft/vscode#170059]
Type: <b>Bug</b>

When you have a project whose path contains a space, then each time an error is displayed in the Terminal, only the part after the space is turned into a link, hence the link representing the file is invalid.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.15.84-1-MANJARO
Modes:
Sandboxed: No

**Comment by meganrogge** [comment]
duplicate https://github.com/microsoft/vscode/issues/97941, which is fixed in insider's and will be in our next release
