### ISSUE TITLE
The way to overwrite or prepend PATH variable in integrated terminal.

### ISSUE THREAD

**Issue by tanshihaj** [microsoft/vscode#170045]
It seems that existing API that can be used to change environment variables in VS Code ([EnvironmentVariableCollection](https://code.visualstudio.com/api/references/vscode-api#EnvironmentVariableCollection)) doesn't allow to fully control PATH variable. After altering PATH with .prepend() or .replace() methods there is still some "default" paths prepended in PATH variable (in case of macos it is `/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`).

In my case it leads to various issues with `nix` command which relies on correct PATH variable.

Is it possible to fully control PATH variable in integrated console?

**Comment by meganrogge** [comment]
when VS Code launches, we source a "dev environment" by running your default shell, so that PATH is used. We don't have control of the PATH in other words
