### ISSUE TITLE
Git: Branch (Command Palette) closes and clears input box upon switching apps

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#17007]
- VSCode Version: Insiders 25dc9851ef6d41fb4939a37312590cadaee90327
- OS Version: macOS Sierra

Steps to Reproduce:

1. Open Command Palette
2. Type in `GIT: Branch` command to create a new branch.
3. Start typing in a name of the new branch, but don't hit enter.
4. Switch to another app and then back again using <kbd>⌘</kbd> + <kbd>Tab</kbd>
5. Note that the command palette is now closed and everything you typed has disappeared.

**Why I feel we should address this:**
As a user, I was needing to reference an issue number on GitHub as I was deciding what to name this branch.  This behavior was unexpected and made me feel like I had to do everything in one step or lose everything I typed.

**Comment by joaomoreno** [comment]
This is a general Quick Open issue, which hides itself on blur. @bpasero 

Closing as there is a workaround: the terminal. The quick open interaction is for a _quick_ action.

**Comment by bpasero** [comment]
@bgashler1 @joaomoreno there is a setting to change this behaviour:

`"workbench.quickOpen.closeOnFocusLost": false`

Also, the picker API has an option `ignoreFocusLost` that can be used to prevent closing on blur for individual pick interactions. This option does not exist on the quick open thing yet though.

**Comment by joaomoreno** [comment]
> Also, the picker API has an option ignoreFocusLost that can be used to prevent closing on blur for individual pick interactions.

We could use that... but then I wonder why isn't this used all the time?

**Comment by bpasero** [comment]
Mainly for historic reasons, we added it quite late. I know Sublime decides to never close quick open on focus lost, but I am actually not a big fan of such behaviour.
