### ISSUE TITLE
[ vscode tunnel] After one session, it can't connect to "localhost:5500"

### ISSUE THREAD

**Issue by RealFX-Code** [microsoft/vscode#170042]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 1.74.2-e8a3071ea4344d9d48ef8a4df2c097372b0c5161-x64
- OS Version: Ubuntu Server 22.04.1 LTS

Steps to Reproduce:

1. Install VSCode from `.deb` package from: `https://code.visualstudio.com/Download`
2. Add a Code Tunnel as a `.service` so it starts on machine startup
3. Open a session and close the session
4. Try and connect to another session on the same machine
5. VScode can't connect to the code tunnel anymore
6. vscode tunnel outputted:
```
Dec 26 13:13:50 <hostname> code[4761]: [2022-12-26 13:13:50] info [tunnels::connections::relay_tunnel_host] Opened new client on channel <number>
Dec 26 13:13:51 <hostname> code[4761]: [2022-12-26 13:13:51] info [tunnels::connections::relay_tunnel_host] Error connecting forwarding to 127.0.0.1:5500, Connection refused (os error 111)
```

My `.service` file that runs VScode tunnel:
```
[Unit]
Description=Visual Studio Code Tunnel Service
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=<my username>
ExecStart=/usr/bin/code tunnel

[Install]
WantedBy=multi-user.target
```

To wake up the VScode tunnel so i can use it again, i have to restart the service. E.G. `service code-tunnel.service restart`

**Comment by Fiirefox7** [comment]
Fiirefox7 Enterprise

**Comment by connor4312** [comment]
If you run top/htop in the state where you can't connect, do you see a VS Code server running with high CPU usage? If so, that may be https://github.com/microsoft/vscode-remote-release/issues/6543

**Comment by RealFX-Code** [comment]
> If you run top/htop on the host machine in the state where you can't connect, do you see a VS Code server running with high CPU usage? If so, that may be [microsoft/vscode-remote-release#6543](https://github.com/microsoft/vscode-remote-release/issues/6543)

I don't, The most I see is a VSCode Node process running with ~0.6% CPU of my not-so-powerful server i'm running it on.

Now I can't connect, but it's not throwing `Can't connect to localhost:5500` anymore, bur still can't connect. It's now apparently closed `localhost:5500` 
Now the output of `systemctl status code-tunnel` is:
```
sudo systemctl status code-tunnel
● code-tunnel.service - Visual Studio Code Tunnel Service
     Loaded: loaded (/etc/systemd/system/code-tunnel.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-01-05 07:21:51 UTC; 10h ago
   Main PID: 26228 (sh)
      Tasks: 92 (limit: 8148)
     Memory: 823.8M
        CPU: 1min 39.918s
     CGroup: /system.slice/code-tunnel.service
             ├─26228 sh /usr/bin/code tunnel
             ├─26243 /usr/share/code/bin/../code /usr/share/code/bin/../resources/app/out/cli.js --ms-enable-electron-run-as-node tunnel
             ├─26256 /usr/share/code/bin/code-tunnel tunnel
             ├─26986 sh /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/bin/code-server-insiders --connection-token=vaKaQBsrfDUehdNBx314CGDafYijS9_U-AXQsjs7YX4 --accept>
             ├─26990 /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/node /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/out/serv>
             ├─27001 /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/node /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/out/boot>
             ├─27012 /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/node /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/out/boot>
             ├─27023 /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/node /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/out/boot>
             ├─27049 /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/node /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/extensio>
             ├─27863 /usr/bin/zsh -i
             ├─28561 /bin/sh /home/realfx/.vscode-server-insiders/extensions/ritwickdey.liveserver-5.7.9/node_modules/opn/xdg-open http://127.0.0.1:5500/
             ├─28576 sh /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/bin/helpers/browser.sh http://127.0.0.1:5500/
             └─28581 /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/node /home/realfx/.vscode-cli/server-insiders/bin/4acf2d9b46b75748ae687cf3b2952a0799679873/out/serv>

Jan 05 17:37:48 the-fem-coding vsce-sign[27119]: Primary signature status:  OK
Jan 05 17:37:48 the-fem-coding vsce-sign[27119]: Timestamp signature status:  OK
Jan 05 17:37:48 the-fem-coding vsce-sign[27119]: Exit code:  Success
Jan 05 17:41:33 the-fem-coding code[26243]: [2023-01-05 17:41:33] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 3
Jan 05 17:41:34 the-fem-coding code[26243]: [2023-01-05 17:41:34] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 4
Jan 05 17:41:36 the-fem-coding code[26243]: [2023-01-05 17:41:36] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 5
Jan 05 17:44:08 the-fem-coding code[26243]: [2023-01-05 17:44:08] info [rpc.0] Unforwarding port 5500
Jan 05 17:44:17 the-fem-coding code[26243]: [2023-01-05 17:44:17] info [rpc.0] Forwarding port 5500
Jan 05 17:44:18 the-fem-coding code[26243]: [2023-01-05 17:44:18] info [rpc.0] Disposed of connection to running server.
Jan 05 17:44:20 the-fem-coding code[26243]: [2023-01-05 17:44:20] info [tunnels::connections::relay_tunnel_host] Opened new client on channel 6
```

**Comment by TerrrorByte** [comment]
This is happening to me periodically when I run `ng serve` to develop Angular apps. I'll specifically run `ng serve --host=0.0.0.0` and it will sometimes open port 4200 fine, other times it will immediately crash the connection to VSCode Desktop, but leave the port open. I then have to restart VSCode Server to close the port. If I open vscode.dev in the browser and navigate to my VSCode Server through there, it'll open fine, but still claim that 4200 is in use. Definitely something up with port forwarding

**Comment by connor4312** [comment]
Following up here.

The "Error connecting forwarding" is an error that happens when you have a forwarded port for which a service is no longer listening on the machine. It's followed by the address it tried to connect to, and the network error that it encountered.

If you hit this, something good to check is that you're listening on `127.0.0.1` rather than localhost, since sometimes localhost refers to the ipv6 loopback (`::1`) which we don't currently forward to.
