### ISSUE TITLE
Apparent package.json corruption in conjunction with npm install --save whatever

### ISSUE THREAD

**Issue by OutsourcedGuru** [Microsoft/vscode#17005]
- VSCode Version:  1.7.2
- OS Version: OS X 10.11.6
- npm Version:  3.10.9

Steps to Reproduce:

1. Open the **package.json** in vscode
2. In a terminal, install a module to your Node.js project with ``npm install --save whatever`` 

You start to see some odd errors reported in npm which suggest that it can't parse the **package.json** file.  Running ``cat`` against the file returns a lot of binary nonsense.  Returning to vscode reveals a lot of garbage.  You then need to either re-pull from git, e.g., or create a sibling project, ``npm install`` the same dependencies and attempt to recreate a new one to bring back over.

**Comment by bpasero** [comment]
@OutsourcedGuru does it reproduce anytime? does it reproduce if you disable all extensions (run `code --disable-extensions`)

**Comment by bpasero** [comment]
@OutsourcedGuru ping

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!

**Comment by OutsourcedGuru** [comment]
@bpasero Actually, my Windows 10 laptop (with that email account) hasn't been able to sync with the Mail app since November so I wasn't getting any notifications.  For the "fix", I am now running Microsoft Outlook on a MacBook so that I can actually read my email.

By all means, close the issue.  Whatever you do, don't follow the steps-to-reproduce.
