### ISSUE TITLE
Select a block of code and edit in new tab

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Microsoft/vscode#17006]
Hi,

Suggestion here: the ability to select a block of code, and have an option to edit it in a new tab.

![](https://camo.githubusercontent.com/87f2f7ace9bd3b9ff03c1fc4d1b44698c081a78a/68747470733a2f2f7261772e6769746875622e636f6d2f626f726a6163616d70696e612f7375626c696d65746578742d656469745f696e5f6e65775f7461622d706c7567696e2f6d61737465722f6578616d706c652e676966)

This is a great tool to work on a specific portion of code without being drowned in the whole content. A bit like an isolation mode in Illustrator.

Then, when you save the tab, it closes and the block of code is replaced.

It's available on Atom and SublimeText, let's get VisualStudio Code have it too!

Thanks!

**Comment by alexandrudima** [comment]
fyi @bpasero

**Comment by bpasero** [comment]
I see no reason why this cannot be done as extension 👍

**Comment by mjbvz** [comment]
Yes, this is something an extension could implement. Please see [our extension authoring docs](https://code.visualstudio.com/docs/extensions/overview) for information about writing an extension

Closing as extension-candidate
