### ISSUE TITLE
I am not able to run the c++ code normaly

### ISSUE THREAD

**Issue by TarunNehla** [microsoft/vscode#170095]
Type: <b>Performance Issue</b>

I have new laptop with ryzen 7 5800H 16gb
still it takes more more to time to run the code. and some times i doesn't give the output ......... This is happening with me from last 7 days 

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800H with Radeon Graphics          (16 x 3194)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.41GB (8.76GB free)|
|Process Argv|--crash-reporter-id 8ab90288-05af-4ab3-9172-4fc2afc74863|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    99	 13416	code main
    0	   169	  3416	   extensionHost
    0	   108	   232	     "C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\ASUS\.vscode\extensions\ms-python.vscode-pylance-2022.12.20\dist\server.bundle.js --cancellationReceive=file:7cf35f3e316ec25c28d9e8fca6bab52fc03f2fdf6d --node-ipc --clientProcessId=3416
    0	    64	  4872	     c:\Users\ASUS\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64\bin\cpptools.exe
    0	    10	 10416	       console-window-host (Windows internal process)
    0	     4	 22260	       "c:\Users\ASUS\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64\bin\cpptools.exe"
    0	   133	 14268	         c:\Users\ASUS\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64/bin/cpptools-srv.exe 4872 {300F7C33-0341-458C-AFC9-2E1B46D7A02C}
    0	    10	 20868	           console-window-host (Windows internal process)
    0	   123	 19416	         c:\Users\ASUS\.vscode\extensions\ms-vscode.cpptools-1.13.8-win32-x64/bin/cpptools-srv.exe 4872 {CE84691D-27CD-421B-A940-40ED19937164}
    0	    10	  5800	           console-window-host (Windows internal process)
    0	    95	 20840	     "C:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node "c:\Users\ASUS\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=3416
    0	   224	  4424	   window (D_Districts_Connection.cpp - Tarun - Visual Studio Code)
    0	    93	 10176	   window (undefined)
    0	    42	 20348	   utility-network-service
    0	   131	 21548	   gpu-process
    0	    94	 21724	   issue-reporter
    0	    26	 21828	   crashpad-handler
    0	   106	 22060	   shared-process
    0	    77	  6160	     fileWatcher
    0	    72	 12264	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (D_Districts_Connection.cpp - Tarun - Visual Studio Code)
|    Folder (Tarun): 28 files
|      File types: prob(11) cpp(11) exe(2) json(1) pdf(1)
|      Conf files: settings.json(1);
```

</details>
<details><summary>Extensions (18)</summary>

Extension|Author (truncated)|Version
---|---|---
code-gnu-global|aus|0.2.2
competitive-programming-helper|Div|5.9.2
code-runner|for|0.11.8
beautify|Hoo|1.5.0
better-cpp-syntax|jef|1.17.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
remote-explorer|ms-|0.0.3
cmake|twx|0.0.17

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
gswce1:30612156
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by TarunNehla** [comment]
and i have resinstalled the vs code and mingw thrice

**Comment by roblourens** [comment]
Sounds like an issue with your machine, or code, or setup. If you think it's an issue with the cpp extension, please file an issue on their repo.
