### ISSUE TITLE
flask run command not working

### ISSUE THREAD

**Issue by albedo02** [microsoft/vscode#170016]
I renamed the folders. Now github preview app is not working. Instead it's showing this error:
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.4","title":"Not Found","status":404,"traceId":"00-e13625f987b5bda38e270c6a5019b8fa-ec051e6abf63176f-00"}

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
Embedder: codespaces

**Comment by lszomoru** [comment]
@albedo02, could you please elaborate on what you mean by the "github preview app"? 
Providing a recording of the issue (https://gifcap.dev) would help investigate this issue. Thanks!

**Comment by albedo02** [comment]
Restarting the codespace worked. The issue has been resolved.

**Comment by roshnirajak** [comment]
1) You can first make **flask environment**: `py -2 -m virtualenv <name of environment>`
2) Activate it: `<name of environment>\Scripts\activate`
2) install flask in that environment directory, run: `pip install flask`
4) inside environment directory, run: `$env:FLASK_APP= "app.py"`
(app.py is name of your python file)
5) `flask run`
It worked for me, hope it works for you too
