### ISSUE TITLE
Windows: allow more styles in the menu bar and hide the title bar

### ISSUE THREAD

**Issue by Tekbr** [Microsoft/vscode#17009]
- VSCode Version: 1.7.2
- OS Version: Windows 10

-- Sorry for the English, I used Google Translator --

Allowing show / hide equal title bar happens with Firefox.

![gif2](https://cloud.githubusercontent.com/assets/19866231/21069579/7db6dd94-be62-11e6-8b52-54a5a6cb7ed7.gif)

Allow the menu bar to receive the color of the VSCode theme, just like in Firefox, rather than gray.

![gif1](https://cloud.githubusercontent.com/assets/19866231/21069599/c0f99dc6-be62-11e6-8e49-a4256215c452.gif)

![gif3](https://cloud.githubusercontent.com/assets/19866231/21069609/d2e48e60-be62-11e6-9001-e77a95ede0aa.gif)

Follow a print (very ugly) to get an idea of how it could stay.

When we leave the Menu bar active.

![img2](https://cloud.githubusercontent.com/assets/19866231/21069620/eea3d21e-be62-11e6-920f-fb9fc6d88525.jpg)

When we hide the menu bar..

![img3](https://cloud.githubusercontent.com/assets/19866231/21069626/f703ebd8-be62-11e6-9b68-4137530394d8.jpg)

When we have a group of tabs with the Menu bar hidden.

![img4](https://cloud.githubusercontent.com/assets/19866231/21069628/fb80f80e-be62-11e6-8b57-0fb0e0bbebce.jpg)

The background color of the mininize, restore / maximize, and close buttons should change color along with the theme, but when hovering over it it should change color to gray when mininize and restore / maximize and red when closed, as it currently is .

**Comment by stevencl** [comment]
Thanks for the feedback.

We have the ability to toggle the menu bar on and off at the moment (from the View menu).

@bgashler1 has been working on theming, with one of the ideas being to allow the title bar to take on the VS Code theme colours (see the full issue here: https://github.com/Microsoft/vscode/issues/3112 - Brad's comments and proposal are further on in the thread).

Let me know if this covers what you are proposing here.

**Comment by Tekbr** [comment]
@stevencl Yes, I know we can hide the menu bar.
But what I'm talking about as a suggestion is to hide the title bar, so note that the options to minimize restore / maximize and close are in the same position as the menu bar items.

If I also resolve to hide the menu bar the options to minimize restore / maximize and close remain in the same position as the tabs.

Sorry for the English and the placed images.

See if the explanation is better now.

**Comment by stevencl** [comment]
Thanks!

We've investigated hiding the title bar too but the challenge we have not yet been able to fully solve is how to support dragging individual tabs and the full window when there is no title bar, if the tabs remain full height. Our only solution has been to add space above the tabs which the user can drag to move the whole window. This is effectively a title bar, albeit potentially a smaller one to the one we have today.

**Comment by Tekbr** [comment]
@stevencl I think the biggest problem will be when you have a group of guides and not when you have a single group (since this situation looks like how browsers work Edge, Firefox, Chrome.)

I do not know if it's possible:

Note that when we have many tabs open in browsers, they also leave a space between the minimize button and the button for a new tab. Could this space be placed and be used to drag the window?

See that when we lower the Firefox and Chrome window it adds a space so that the entire window can be dragged. Could this space be added to when you have a group of tabs and when the window is dimmed?

**Comment by be5invis** [comment]
Maybe useful (based on @flagello’s [Essence](https://github.com/flagello/Essence)):

![](https://cloud.githubusercontent.com/assets/240091/21091794/7edfeb5c-c083-11e6-8542-86710ea63fbe.png)
![](https://cloud.githubusercontent.com/assets/240091/21092185/d6dc5992-c085-11e6-8776-62dbdac43989.png)

**Comment by stevencl** [comment]
Thanks for all the suggestions. I'm trying to keep track of the requirements and suggestions in this issue: https://github.com/Microsoft/vscode/issues/17060

Would love to hear your thoughts there.

I'll close this issue just now so that we can keep all the discussion and suggestions in one place.
