### ISSUE TITLE
Debugging C++ fails with an error window saying Windows cannot find C:\Program. Make sure you typed the name correctly and try again.

### ISSUE THREAD

**Issue by anoban** [microsoft/vscode#170022]
Hi there!        
I'm on Windows 10 (22H2 Build: 19045.2364) with Visual Studio 17.4.3 and VS Code Version: 1.74.2 (system setup). I usually compile my C/C++ files using the Developer PowerShell but found I'd be better off taking advantage of the C/C++ extension's build/debug options. Unfortunately the build process succeeds but debugging fails. At the end of build an error windows pops up saying "Windows cannot find C:\Program. Make sure you typed the name correctly and try again.". I guess this has to do something with the path containing a space i.e "Program Files" or "Program Files (x86)". But I do not see these directories being involved in the build process except for the Visual Studio installation directory. (I invoked VS Code from the Developer PowerShell, in case that helps).           

At the end of build I get        
"Build finished successfully. Terminal will be reused by tasks, press any key to close it."       
      
I have a fully functional installation of Visual Studio with C++ Desktop development workload installed and I'm able to build and debug C++ programmes inside VisualStudio but I do not fancy creating a new solution and setting up build configurations for each simple programme I make. If I knew where this path (assumption) issue occurs I can manually enclose the path inside quotes and get over it. But I have no idea as of now. I'd appreciate any help regerding this. 

PS. Here are the tasks.json and launch.json files. (I've customized them manually and my installation of VS Code did not generate the launch.json automatically and I prepered this manually with the help of https://code.visualstudio.com/docs/cpp/config-msvc#_run-vs-code-outside-the-developer-command-prompt       

launch.json:       
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${fileDirname}/${fileBasenameNoExtension}.exe",
            "symbolSearchPath": "${fileDirname}",
            "requireExactSource": true,
            "args": [],
            "stopAtEntry": true,
            "cwd": "${fileDirname}",
            "environment": [],
            "console": "externalTerminal",
            "preLaunchTask": "C/C++: cl.exe build active file"
        }
    ]
}
```          

and tasks.json:         
```
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: cl.exe build active file",
            "command": "cl.exe",
            "args": [
                "/Zi",
                "/EHsc",
                "/std:c++20",
                "/W4",
                "/arch:AVX512",
                "/fp:precise",
                "/guard:cf",
                "/GL",
                "/Qspectre",
                "/nologo",
                "/Fe${fileDirname}/${fileBasenameNoExtension}.exe",
                "${file}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$msCompile"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

Another note, building & debugging works perfectly in VS Code when I use MSYS2 (g++) but I'm biased towards MSVC so there's that.

**Comment by roblourens** [comment]
Please file this on the cpp extension's repo, thanks
