### ISSUE TITLE
even though I have added args in launch.json according to the document, It cannot recognize args after clicking the debug button

### ISSUE THREAD

**Issue by L-WWEEII** [microsoft/vscode#170043]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:
When I want to add args when debugging python code, even though I have added args in launch.json according to the document, I cannot recognize args after clicking the debug button

**Comment by roblourens** [comment]
Please file this issue with more specific detail on the vscode-python extension repo
