### ISSUE TITLE
Problem with debugging python code.

### ISSUE THREAD

**Issue by Akash187** [Microsoft/vscode#17004]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.1.7601
- Extensions:

|Extension|Author|Version|
|---|---|---|
|html-snippets|abusaidm|0.0.18|
|compulim-vscode-closetag|Compulim|0.1.2|
|javadebugger|donjayamanne|0.0.2|
|python|donjayamanne|0.5.5|
|code-runner|formulahendry|0.6.2|
|CppSnippets|hars|0.0.5|
|MagicPython|magicstack|0.6.1|
|cpptools|ms-vscode|0.9.3|
|debugger-for-chrome|msjsdiag|2.3.2|
|view-in-browser|qinjia|0.0.3|
|html5-boilerplate|sidthesloth|1.0.1|
|html-preview-vscode|tht13|0.0.3|
|python|tht13|0.2.3|
|java-snippets|tushortz|0.0.1|
|python-extended-snippets|tushortz|0.0.1|
|Material-theme|zhuangtongfa|1.0.3|

---
Actually the issue is that while debugging the point at which user has to enter the input debugger just get stop there even after entering the value.
Here is my code

```
import sys
min = sys.maxint
max = -sys.maxint-1
while True:
    try:
        num = raw_input("Enter a number: ")
        if num == "done":
            break
        num = int(num)
        if num > max:
            max = num
        if num < min:
            min = num
    except:
        print "Invalid input"         
print "Maximum is " + str(max)
print "Minimum is " + str(min) 
```

Steps to Reproduce:

1.
2.

**Comment by xin053** [comment]
the doc of `donjayamanne`'s `python` extension:

1. Open the file to be debugged
2. From the debug configuration select **Integrated Terminal/Console**(not debug console of vscode)
3. Start debugging
4. The integrated terminal will be displayed 

I tried it,and it worked fine.

But just as you said,the debug console of vscode cannot deal with the input when debug python code.

Maybe it is a bug of the python extension or a bug of vscode.

**Comment by DonJayamanne** [comment]
The debug console in VS Code is a readonly output window. This isn't a bug of the extension nor VS Code, but by design. This is why you'd need to use the Integrated Terminal or the external terminal (for User input).

**Comment by kieferrm** [comment]
The input box lets you interactively inspect all object accessible at the current stack frame or run any accessible code.

**Comment by xin053** [comment]
@kieferrm Ok,thanks a lot.
