### ISSUE TITLE
:before decoration of whole line breaks indent guides when word wrap is on

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode#170023]
Does this issue occur when all extensions are disabled?: Yes.

- VS Code Version: 1.74.2
- OS Version: macOS/Windows etc.

Originally reported in https://github.com/microsoft/vscode-spring-boot-dashboard/issues/257

We followed almost the same way with https://github.com/microsoft/vscode/issues/159225#issue-1351417384 to decorate lines with either an icon or a placeholder, highlighting lines related to Spring concepts, exposing related features in the hover. But when word wrap is on, indent guides are not aligned because decorator is not rendered for the wrapped "line".

#### Current Behavior
<img width="562" alt="image" src="https://user-images.githubusercontent.com/2351748/209499126-994e4cab-c65f-47a1-a6c5-e49af863b53a.png">

#### Expected Behavior
<img width="553" alt="image" src="https://user-images.githubusercontent.com/2351748/209499326-31d6e667-ee61-4c17-8150-80f97215e3ab.png">

I don't see any way to implement with current APIs. 

Ideally, I want to always render a placeholder before the "wrapped parts". E.g. if L63 is long enough, I expect an icon to be rendered before the "head line" of it and placeholders to before "wrapped lines". (currently the extension sets icon/placeholder explicitly for each line, for wrapped parts I don't think the extension has the control of it, and vscode probably should do that, but how does vscode know whether to render an icon or a placeholder?)

#### Steps to Reproduce 
(as we implemented [here](https://github.com/microsoft/vscode-spring-boot-dashboard/blob/779b22e33f0794a69c506e465b4efeadcab1673a/src/gutter/index.ts#L28-L55))

1. call `vscode.window.createTextEditorDecorationType()` with `isWholeLine:true` to create a decoration type.
2. decorate each line with either an icon or a placeholder as below:
```ts
    optionsForPlaceholder = {
        before: {
            backgroundColor: new vscode.ThemeColor("editor.background"),
            color: new vscode.ThemeColor("editor.foreground"),
            width: "2em",
            contentText: " "
        }
    };
    optionsForIcon = {
        before: {
            backgroundColor: new vscode.ThemeColor("editor.background"),
            color: new vscode.ThemeColor("editor.foreground"),
            width: "2em",
            contentIconPath: path-to-an-svg-file
        }
    };
```

**Comment by nickzhums** [comment]
Hi @isidorn , as discussed in the meeting, this is the issue that we observed from the customer when we used the gutter icon and seems there is some limitation with current rendering. We can use this issue to discuss a solution. Thanks

**Comment by isidorn** [comment]
Thanks. Let's give some time for Alex to respond.
Also fyi @hediet since you are looking into Monaco editor issues.

**Comment by alexdima** [comment]
I agree, it is not possible to achieve left-padding of wrapped lines using current text decorations API. This has been requested before at https://github.com/microsoft/vscode/issues/90426
