### ISSUE TITLE
what happen?

### ISSUE THREAD

**Issue by ChaoweiLuo** [microsoft/vscode#170088]
ADD ISSUE DESCRIPTION HERE

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.54
Embedder: codespaces

**Comment by bhavyaus** [comment]
If you have a specific issue with a VS Code, please feel free to let us know, thanks!
