### ISSUE TITLE
Pressing Command Key (while text selected) in Left-hand Side of Diff Editor Makes it Vanish

### ISSUE THREAD

**Issue by bgashler1** [Microsoft/vscode#17008]
- VSCode Version: Insiders 25dc9851ef6d41fb4939a37312590cadaee90327
- OS Version: macOS

![bug in diff](https://cloud.githubusercontent.com/assets/11839736/21069598/765c41e2-be30-11e6-8ae0-9942f07acd34.gif)

Steps to Reproduce:

1. From the Git view, open a diff containing some changes from an unstaged change
2. Select some text on the left-hand side
3. Press the <kbd>Cmd</kbd> key (as if you were going to press a hotkey to copy the selected text).
4. Note that the left-side of the diff view is now gone.

**Comment by alexandrudima** [comment]
@bgashler1 Any messages in the console ?

**Comment by joaomoreno** [comment]
Great catch!

**Comment by chrmarti** [comment]
Cannot reproduce in 40243d1e01, which doesn't have the fix. Any instructions for verification?

**Comment by roblourens** [comment]
I can't repro either. I checked out vscode at the commit before the fix

**Comment by joaomoreno** [comment]
Verifications steps:

- Change a CSS file in a git repo
- Open the diff using the git viewlet
- Hold <kbd>Ctrl</kbd> and move mouse around in the readonly editor

**Comment by bpasero** [comment]
@ramya-rao-a I verified this
