### ISSUE TITLE
Comments UI with high contrast themes.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode#170024]
If you use a high contrast theme, there seems to be issues with the glyphs and the comment background.

<img width="175" alt="image" src="https://user-images.githubusercontent.com/150152/209510676-952f75dd-0d9d-47cf-8e14-7db830c0db83.png">

<img width="154" alt="image" src="https://user-images.githubusercontent.com/150152/209510742-5d4bc652-6df9-4608-a970-25f65c0b4967.png">

Looking at the first one, it seems like it is using a "foregound" colour as the glyph background.

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/contrib/comments/browser/media/review.css#L468-L471

Or it could just be that this is a hangover from before it was a glyph, but I think the default values for High Contrast themes may need updating.

I haven't yet had a chance to check on the placeholder input - apologies for not digging into this that much before posting, I'm not sure how much time I'll have today.

**Comment by a-stewart** [comment]
Update, the input issue seems to be due to the default value of `peekViewTitle.background` being null for HC themes which means, as far as I can see, it is using the OS default button colour.

**Comment by alexr00** [comment]
I've made a fix for the comment gutter decoration. I wasn't able to reproduce the reply button issue though.

**Comment by a-stewart** [comment]
> I've made a fix for the comment gutter decoration. I wasn't able to reproduce the reply button issue though.

Thanks :)
