### ISSUE TITLE
[Question] How to programatically access New Unsaved File

### ISSUE THREAD

**Issue by jongeller** [Microsoft/vscode#17003]
Hi all, trying to get access through the vscode namespace to a new tab (unsaved) editor in the active window.

I would like to create a new document, but it needs to remain unsaved. I cannot find a way to programmatically set the content of this document while it is in a unsaved state.
I have used: commands.executeCommand("workbench.action.files.newUntitledFile") but there seems to be no way focus on that new editor window (until saved) to then add content to the document.
When I create a new temp file and open it with: workspace.openTextDocument(path) The file is already saved.

Thanks!

**Comment by mjbvz** [comment]
[I believe I just answered your question over on StackOverflow](http://stackoverflow.com/questions/41068197/vscode-create-unsaved-file-and-add-content/41069687#41069687)

Please let me know if that is what you are looking for or if anything is unclear.

Thanks.

**Comment by jongeller** [comment]
@mjbvz - thanks! That is what I was looking for, I'll follow if I have any questions.

**Comment by jongeller** [comment]
@mjbvz is there any way to do this without providing a path to save the unsaved file to? I'd like force the prompt for a save location when a user tries to save the file, instead of forcing one to be provided.

**Comment by jongeller** [comment]
@mjbvz - just pinging again, incase this got lost over the weekend.

**Comment by mjbvz** [comment]
I'm not sure if we have a good api story for that flow. 

@jrieken Do you have any thoughts on how he could accomplish this using the existing apis?

**Comment by jongeller** [comment]
Just to add a bit more. Is there anyway to leverage "workbench.action.files.newUntitledFile"? I've been trying to discern what parameters may exist, but no luck yet.

**Comment by jrieken** [comment]
@jongeller You can call [`openTextDocument`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L3928) with an URI using the `untitled`-scheme. That will create a new document, like so: 

```ts
return workspace.openTextDocument(Uri.parse('untitled:c/test/files.js').then(doc => {
	assert.equal(doc.uri.scheme, 'untitled');
	assert.ok(doc.isDirty);
});
```

**Comment by jongeller** [comment]
@jrieken right, which was what @mjbvz showed me over on stackoverflow, however, I was asking if it was possible to use the API to open a new tab, populate it, but not pre-set a save path. This way, on save, the user is prompted to provide a path.

**Comment by jongeller** [comment]
looks like these two items were added to open issues internally and externally, but haven't been addressed in a couple months:
https://github.com/Microsoft/vscode/issues/12283 
and 
https://github.com/hoovercj/vscode-octo/issues/11

**Comment by jrieken** [comment]
Yes #12283 is what you want
