### ISSUE TITLE
YAML frontmatter hyphens in markdown files are incorrectly scoped/have no scope applied

### ISSUE THREAD

**Issue by Fantazstic** [microsoft/vscode#170032]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 10 Pro 64bit 20H2

Steps to Reproduce:

1. Create feature_request.md:
```
---
name: Feature request
about: Suggest an idea for this project
title: "[REQUEST]"
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
Add any other context or screenshots about the feature request here.
```
2. Use "Developer: Inspect Editor Tokens and Scopes"
3. Select the frontmatter hyphens `---`
4. Notice empty scope/no scope applied
5. So, we can't edit the colors (cannot use `text.html.markdown` since that will select all the normal text too)

![Code_bc3iS5RDoU](https://user-images.githubusercontent.com/77517720/209538203-dcf63519-f266-4ef4-9905-529a9e5372d3.png)

**Comment by mjbvz** [comment]
YAML front matter is not a standard markdown concept. For core VS Code, we target standard common mark but support for additional features can be contributed by extensions

**Comment by Fantazstic** [comment]
@mjbvz Thanks for the reply.

It looks like VSCode can recognize [horizontal rule](https://www.markdownguide.org/basic-syntax/#horizontal-rules) common markdown, but only further down in the file. 

AFAIK other editors, for example Atom, have consistent syntax highlighting, while VSCode is being inconsistent with them.

Screenshots: 

VSCode | Atom
--- | ---
![Code_L2ILmbiOVR](https://user-images.githubusercontent.com/77517720/215313088-4120c9b6-3885-45c4-80d6-292b1a1134a4.png) | ![atom_q0BmBXTLKY](https://user-images.githubusercontent.com/77517720/215313095-c382d615-547c-4b3d-9188-b7e8489f74d0.png)


Could we get support for the untokenized separators to be tokenized as `meta.separator.markdown` as well?
