### ISSUE TITLE
allow debug bar in the red bordered area from the snapshot

### ISSUE THREAD

**Issue by sanket-bhalerao** [microsoft/vscode#170048]
Type: <b>Feature Request</b>

please allow debugging bar in the red-bordered area from the snapshot
![image](https://user-images.githubusercontent.com/9264813/209567935-68d49102-0e0a-4f9d-9687-faeda173ef04.png)

WHY:
The debug tool when in the current allowed space (filename or the line below) often hides filenames or some icons on the right side. 
Allowing it to move in the title bar could avoid this.
VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:21:57.802Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: Yes

**Comment by yume-chan** [comment]
Duplicate of #117326

**Comment by sanket-bhalerao** [comment]
closing this in favor of #117326
