### ISSUE TITLE
VS Code does not honor success: false for VariableRequests

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1700]
A bug I picked up during development. This is an screenshot showing how VS Code displays an error that was send through `sendErrorResponse` as a result for the variable, when it should really show an error message for the user.

![image](https://cloud.githubusercontent.com/assets/10532611/12044046/8d1a58de-ae8b-11e5-9c1f-15fe50d19197.png)

Here are my communication logs:
```
-> variablesRequest
{ type: 'request',
  seq: 10,
  command: 'variables',
  arguments: { variablesReference: 1 } }

<- variablesResponse
Response {
  seq: 0,
  type: 'response',
  request_seq: 10,
  command: 'variables',
  success: false,
  message: 'request \'variables\': test',
  body: 
   { error: 
      { id: 123,
        format: 'request \'variables\': test',
        showUser: true } } }
```

**Comment by isidorn** [comment]
Nice catch - thanks.
Now we show the error in italic red and we do not show the null: part so it should be clearer to the user what is going on.
We are not using our general error reportin approach to not spam the user (showing errors on top of workbench)

**Comment by felixfbecker** [comment]
:+1:
