### ISSUE TITLE
php file issue

### ISSUE THREAD

**Issue by tgl123** [Microsoft/vscode#17012]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:14:18.217Z)
- OS Version: Linux x64 3.10.0-327.36.3.el7.x86_64(centos 7)
- Extensions:

|Extension|Author|Version|
|---|---|---|

```php
<?php
class user{
    public $name;
    public $age;
    public function setName($name){
        $this->name=$name;
    }
    public function setAge($age){
        $this->age=$age;
    }
    public function getName(){
        return $this->name;
    }
    public function getAge(){
        return $this->age;
    }
}
```
---

Steps to Reproduce:

1.create php file,ex: user.php,if this file contains key word  "class"  ,in linux ,then type  " file   user.php"  ,result is :C++ source,  not is  php script !  if file not contains "class" , it is normal.

**Comment by jaseonline** [comment]
Did you include the opening tag (<?php) at the top of your file, or the shorthand version (<?)?

**Comment by alexandrudima** [comment]
@tgl123 Did you change any settings regarding file extension -> language association?

**Comment by bpasero** [comment]
@tgl123 what does the statusbar bottom right tell what language the file is associated with?

**Comment by bpasero** [comment]
@tgl123 ping

**Comment by bpasero** [comment]
A number of days has past without answer on the questions asked. I am thereby going to close this issue to clean up our backlog of issues. Once you can answer on the questions, the issue can be reopened again. Thanks for understanding this process!
