### ISSUE TITLE
Restart TS Server option is gone

### ISSUE THREAD

**Issue by robertwt7** [microsoft/vscode#170154]
I did run with `code --disable-extensions` and it is still not showing.

I'm also using `asdf` on my shell, not sure if it affects vscode behaviour? it's not supposed to since it has been working for the past year with `asdf`

suddenly when pressing `ctrl + shift + p`, restart ts server is not there anymore as usual
- VS code version:
```
Version: 1.74.2 (user setup)
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
Date: 2022-12-20T10:29:14.590Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
Sandboxed: No
```
- OS Version:  Windows 11

**Comment by IllusionMH** [comment]
Are you have TS or JS file active when you do that? Most commands are context sensitive and this one shouldn't show if you have txt file active

**Comment by robertwt7** [comment]
I am, my project is also 100% typescript. I've never seen it gone though for the past 6 years, this is the first time @IllusionMH

**Comment by robertwt7** [comment]
silly me, I didn't realise that i was on the `turbo.json` instead of ts files since i am splitting my project into 2 panes

when i am on active ts / js files the option shows up
