### ISSUE TITLE
[CSS] Lack of keywords for `align-items`, `align-content` and `align-self` suggestion

### ISSUE THREAD

**Issue by kagankan** [microsoft/vscode#170160]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a CSS file
2. Type  `align-items:`
3. Keyword suggestion is shown, but is not enough.

![image](https://user-images.githubusercontent.com/34136752/209831430-3bf5d6bf-8c78-46b9-8c61-515c47abfb60.png)

There should be more keywords below:

- `end`
- `start`
- `first` (`first baseline`)
- `last` (`last baseline`)
- `safe` (safe <content-position>, like `safe center`)
- `unsafe` (unsafe <content-position>, like `unsafe center`)

See:
https://w3c.github.io/csswg-drafts/css-align/#align-justify-content

Same issue happens for `align-content` and `align-self`

Thank you.

**Comment by mjbvz** [comment]
Tested in 0a6c277e4faa44a6b6eb82ddca8bfeccf7fecef6 but not seeing the suggestions

![Screenshot 2023-01-24 at 1 54 15 PM](https://user-images.githubusercontent.com/12821956/214429562-eba90668-095f-4327-bc09-f3a27655d1ba.png)
