### ISSUE TITLE
Wrong output in a test case of Armstrong number.

### ISSUE THREAD

**Issue by itsAnkitAkm** [microsoft/vscode#170105]
Type: <b>Bug</b>

In the following program of armstrong number value for a particular intput i.e 153 , output is showing wrong. I have tried this in different system same problem is occuring there also. But in other IDEs output is coming right.

#include <bits/stdc++.h>
using namespace std;
int main(){
    int n,d,c=0;
    cout<<"Enter the no."<<endl;
    cin>>n;
    string x= to_string(n);
    int l= x.length();
    for(int i=0; i<l; i++){
        c+= pow((x[i]-'0'),l);
    cout<<c<<endl;

    }

}

1 is not getting added in case of 153.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1240P (16 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.69GB (6.18GB free)|
|Process Argv|--crash-reporter-id dbefe028-fb7f-4176-9291-c8b228e767e5|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
flutter-snippets|ale|3.0.0
dart-code|Dar|3.56.0
flutter|Dar|3.56.0
competitive-programming-helper|Div|5.9.2
code-runner|for|0.11.8
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
material-icon-theme|PKi|4.23.1
cmake|twx|0.0.17

(3 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by roblourens** [comment]
Sounds like an issue with your code or your configuration, but if you think it's an issue with the c++ extension, please file an issue on their repo.
