### ISSUE TITLE
[vscode.dev] Default key binding shortcut for color theme does not work

### ISSUE THREAD

**Issue by veredcon** [microsoft/vscode#170149]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: VSCode Dev

Steps to Reproduce:

1. Open https://vscode.dev/ 
2. Click on Ctrl +K and then Ctrl + T - this is the shortcut key binding for opening Color theme.

Result: 
Ctrl + K - is recognized to be pressed and waiting for second key of chord as expected
Ctrl + T - opens a new browser tab.. So it just do the browser shortcut.

If we change it to Ctrl + K Ctrl +Z for example it will work as expected.
So a workaround may be to change the default shortcut or to fix it in the browser version so it won't execute the default browser command.

**Comment by aeschli** [comment]
From what I know we don't have shortcuts only for running in the browser. Conflicts are difficult to avoid as each browser might have its own shortcuts
- The best is to go full screen
- Also, users can configure their own shortcuts

**Comment by aeschli** [comment]
duolicate of https://github.com/microsoft/vscode/issues/149478
