### ISSUE TITLE
No color javascript after `${+new Date}`

### ISSUE THREAD

**Issue by Mateusz96** [Microsoft/vscode#17015]
- VSCode Version: 1.7.2
- OS Version: Win 10 Pro x64 - all latest updates 

After using `$ {+ new Date}` vs stops code syntax highlighting

I give a code to test 

```
class Foo{
  constructor(){

  }
  test(){
    return `/game.php?village=${source}&screen=main&ajaxaction=upgrade_building&type=main&h=${csrf_token}&&client_time=${+new Date}`
  }
  noColorSyntax(){
    
  }
}
```

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#381
