### ISSUE TITLE
VSCode Version: ERROR Code 1.7.2

### ISSUE THREAD

**Issue by axeldeveloper** [Microsoft/vscode#17018]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|django-html|bibhasdn|1.2.0|
|phpserver|brapifra|1.1.0|
|vscode-eslint|dbaeumer|1.1.0|
|python|donjayamanne|0.5.5|
|php-debug|felixfbecker|1.10.0|
|code-runner|formulahendry|0.5.1|
|crane|HvyIndustries|0.2.2|
|icon-fonts|idleberg|1.3.0|
|composer|ikappas|0.5.0|
|ionic2-vscode|jgw9617|1.0.0|
|ionic1-snippets|justinjames|1.0.1|
|phpmd|linyang95|1.1.1|
|MagicPython|magicstack|0.6.1|
|debugger-for-chrome|msjsdiag|2.2.0|
|python|tht13|0.2.3|
|python-extended-snippets|tushortz|0.0.1|
|cordova-tools|vsmobile|1.2.3|
|JavaScriptSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.
2.

**Comment by mrmlnc** [comment]
More details?

**Comment by axeldeveloper** [comment]
The path c:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\typescript\node_modules\typescript\lib doesn't point to a valid tsserver install. 

Note
typescript INSTALLED  LAST VERSION

**Comment by mjbvz** [comment]
@axeldeveloper Can you please try upgrading to VSCode 1.8 and let us know if you still see this issue. 

The TypeScript team fixed a number of issues with TypeScript 2.1 that we picked up in VS 1.8, and it's also possible that your VSCode installation got into a bad state somehow. Upgrading to 1.8 may resolve this

**Comment by axeldeveloper** [comment]
ok thank you peoples
