### ISSUE TITLE
Environment variables are not expanded

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/vscode#170104]
Type: <b>Bug</b>

With 2 environment variables as follows:
```
JAVA_HOME = %JAVA_HOME_DEFAULT%
JAVA_HOME_DEFAULT=C:\path\to\directory
```

and these VS Code settings:
```json
{
    "terminal.explorerKind": "external",
    "terminal.external.windowsExec": "wt"
}
```

then when I do `Open in Windows Terminal` and type `echo $Env:JAVA_HOME` (with PowerShell 7.3.1 being my default profile in Windows Terminal), the output is `%JAVA_HOME_DEFAULT%`.

However, when I open Windows Terminal outside of VS Code and type the same, the output is correct: `C:\path\to\directory`.

VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:21:57.802Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes

Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
vsc_aacf:30263846
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012:30540252
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12cf:30622697
fim-prod:30623723

```

</details>

**Comment by Tyriar** [comment]
When I set environment variables that equal others, they get automatically resolved via the environment variable window. I set TEST_VAR1 to %TEST_VAR2% and this is what happened:

<img width="228" alt="image" src="https://user-images.githubusercontent.com/2193314/211081237-743e72a0-66d8-42f0-b66d-2506db9a9f73.png">

How are you setting JAVA_HOME in this case?

**Comment by anthonyvdotbe** [comment]
In PowerShell 7.3.1 I do:
```
[Environment]::SetEnvironmentVariable('TEST_VAR1', 'foo', 'User')
[Environment]::SetEnvironmentVariable('TEST_VAR2', '%TEST_VAR1%', 'User')
```

Then in the environment variable window the result is:

![image](https://user-images.githubusercontent.com/15714253/211158131-2dbfe132-f88b-4a2f-95b5-7ebd40cafc2a.png)

**Comment by anthonyvdotbe** [comment]
@Tyriar the `info-needed` label can be removed (or further questions asked if my response was unclear)

**Comment by Tyriar** [comment]
This is working fine for me, whether I run the regular open external command or right click a folder and open in WT:

<img width="612" alt="image" src="https://user-images.githubusercontent.com/2193314/221879308-cbae4458-85d6-4064-8c2e-c59490833853.png">

**Comment by anthonyvdotbe** [comment]
@Tyriar Here's what I did in a stock Windows Sandbox:

* install [PowerShell 7.3.3](https://github.com/PowerShell/PowerShell/releases/tag/v7.3.3)
* install [Windows Terminal v1.16.1026](https://github.com/microsoft/terminal/releases/tag/v1.16.10261.0)
* download the x64 .zip of VS Code Insiders (Version: 1.76.0-insider Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb), unzip, and create a folder named `data` in it
* open PowerShell and run the following 2 commands:
```powershell
[Environment]::SetEnvironmentVariable('TEST_VAR1', 'foo', 'User')
[Environment]::SetEnvironmentVariable('TEST_VAR2', '%TEST_VAR1%', 'User')
```
* open VS Code and change the configuration:
```jsonc
{
    "terminal.explorerKind": "external",
    "terminal.external.windowsExec": "wt"
}
```
* in VS Code, `Open Folder` -> `Downloads`, right-click the VS Code .zip I downloaded earlier, choose `Open in Windows Terminal`
* in the opened Terminal, run:
```powershell
echo $Env:TEST_VAR2
```
which gives: `%TEST_VAR1%`

**Comment by anthonyvdotbe** [comment]
Just found out the exact same thing happens in VS Code's terminal. To reproduce I downloaded the current insiders version (1.78.0-insider f31dffc7f9b93a1cdef21243ec30dea7d489a615), opened an internal terminal, typed `echo $Env:JAVA_HOME` and got `%JAVA_HOME_DEFAULT%` as output.

@Tyriar have you already tried with the reproduction steps in my previous comment? And is there anything else I can do to move this issue forward?

**Comment by anthonyvdotbe** [comment]
When using an external terminal, this is due to an [issue](https://github.com/microsoft/terminal/issues/15191) in Windows Terminal.
However, the same issue occurs when using an internal terminal.

**Comment by Tyriar** [comment]
Looks like the upstream problem is fixed. It will come through to us eventually, it's shipped with Windows though so it's quite a slow process.
