### ISSUE TITLE
Inserting or removing line(s) inside a folded region causes it to unfold

### ISSUE THREAD

**Issue by ozair-dev** [microsoft/vscode#170119]
When I have the same document open in two different editors, if I fold a region inside one editor and insert or remove a line in the folded region with the other editor, it causes the folded region in the first editor to unfold. Other changes do not seem to cause the unfold.
![see demo](https://user-images.githubusercontent.com/65649182/209718177-2176dd1f-7e3a-41a2-a434-c2c9fa5d4de3.gif)

How do I prevent it? Can you add a feature to keep the folded region in its current state when adding or removing line inside it?

**Comment by mrariful786** [comment]
.github/ISSUE_TEMPLATE/--bug-report.yaml

**Comment by ozair-dev** [comment]
@mrariful786  ???
