### ISSUE TITLE
Signed git commits do not work without an agent

### ISSUE THREAD

**Issue by davidobrien1985** [Microsoft/vscode#17014]
- VSCode Version: 1.7.2
- OS Version: Windows 10, 14986

Configured git to sign commits. In order to sign a commit I now need to add a new parameter to my commit command:
`git -S -m 'commit message'`

It will then prompt me to enter my password for the private key. From vscode when trying to commit my changes I see the following error message in the git output:

```
git commit --quiet --allow-empty-message --file -
gpg: cannot open tty `no tty': No such file or directory
error: gpg failed to sign the data
fatal: failed to write commit object
git config --get-all user.name
git config --get-all user.email
```

I guess vscode should allow me to create signed commits and also prompt me for my password.

**Comment by joaomoreno** [comment]
Please check suggestion in https://github.com/Microsoft/vscode/issues/5065#issuecomment-207960831

**Comment by davidobrien1985** [comment]
@joaomoreno no, that didn't help.

```
git commit --quiet --allow-empty-message --file -
gpg: Sorry, no terminal at all requested - can't get input
error: gpg failed to sign the data
fatal: failed to write commit object
```

This `git commit` here should know how to ask for the key's password and also add the `-S` parameter to the command.
Committing on the command line works fine, it's just vscode.

**Comment by joaomoreno** [comment]
The comment mentions the fact that you should be using an agent. Without an agent we have no support for this. I've renamed the issue accordingly, but strongly suggest for you to give an agent a try.

**Comment by davidobrien1985** [comment]
What's `an agent` in this context?

**Comment by joaomoreno** [comment]
Check this out: http://unix.stackexchange.com/questions/188668/how-does-gpg-agent-work

**Comment by jgillich** [comment]
FWIW, using `no-tty` is definitely required, using an agent alone is not enough (https://github.com/Microsoft/vscode/issues/5065#issuecomment-207960831 also explicity states that).

**Comment by joaomoreno** [comment]
#5065
