### ISSUE TITLE
code commant not found

### ISSUE THREAD

**Issue by ocodista** [microsoft/vscode#170124]
Type: <b>Bug</b>

I'm trying to open code from wsl terminal but it's accusing that code command is not found.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.61GB (2.97GB free)|
|Process Argv|--crash-reporter-id bc82a686-1599-4592-b68f-b9edea11c5b5|
|Screen Reader|no|
|VM|40%|

|Item|Value|
|---|---|
|Remote|WSL: Arch|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|Memory (System)|7.57GB (6.69GB free)|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
tsl-problem-matcher|amo|0.6.2
vscode-great-icons|emm|2.1.89
auto-rename-tag|for|0.1.10
jupyter-keymap|ms-|1.0.0
remote-wsl|ms-|0.72.0
prolog|reb|0.0.4
es7-react-js-snippets|rod|1.9.3
vim|vsc|1.24.3
vscode-autosave|cod|1.2.2
vscodewriter|cod|1.0.6
vscode-eslint|dba|2.2.6
gitlens|eam|13.2.0
prettier-vscode|esb|9.10.3
raythis|Goo|1.1.0
todo-tree|Gru|0.0.220
svg|joc|1.4.26
color-highlight|nau|2.5.0
vs-code-prettier-eslint|rve|5.0.4
code-spell-checker|str|2.12.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by ansidev** [comment]
@ocodista Would you mind trying https://github.com/microsoft/vscode-remote-release/issues/3417?

**Comment by aeschli** [comment]
Also see https://code.visualstudio.com/docs/remote/troubleshooting#_fixing-problems-with-the-code-command-not-working
