### ISSUE TITLE
Settings > "Edit settings for yaml" -> "No settings found"

### ISSUE THREAD

**Issue by pmeaney-sqrt** [microsoft/vscode#170186]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version:  Mac 12.6.1 (Monterrey)

Steps to Reproduce:

1. Open settings
2. type "ya" in search bar
3. Click "edit settings for yaml
4. Notice that the link goes nowhere: "No settings found"

<img width="1066" alt="Screen Shot 2022-12-28 at 1 11 54 PM" src="https://user-images.githubusercontent.com/102547768/209867459-a0c2973d-80a2-46c5-bba3-b4e3ac4c4591.png">

<img width="470" alt="Screen Shot 2022-12-28 at 1 11 58 PM" src="https://user-images.githubusercontent.com/102547768/209867471-6e8ffcbf-a9c1-4640-920d-b7f0d5c74f2e.png">

What am I trying to do?

I am trying to disable the buggy JSON Schemas menu and delete or disable all JSON schemas.

I was hoping I could adjust YAML Settings.  But hey! Guess what! There are no YAML settings?! :(

Why?
Because when I install the RedHat YAML extension, and then install the official k8s extension... and then uninstall the official k8s extension...  I am left with a broken YAML Autocomplete for k8s files.

For example-- I can't deselect this "yannh" JSON schema (2nd in the list in the below screenshot).  Big pain in the neck :(

Apparently there are no YAML Settings I can adjust.

<img width="1248" alt="Screen Shot 2022-12-28 at 1 01 15 PM" src="https://user-images.githubusercontent.com/102547768/209867355-6491402c-250f-406d-bb27-06523e448dde.png">

**Comment by rzhao271** [comment]
Hi, I think the reason no settings show up is because clicking the link changes the search query to `@lang:yaml ya` instead of `@lang:yaml`. Try searching just `@lang:yaml` to get the YAML-specific settings to show up.

**Comment by pmeaney-sqrt** [comment]
Indeed you are correct.  Thanks @rzhao271 .  My apologies for not noticing this.  Feel free to close this-- That said, in clicking "edit settings for yaml" perhaps it's a good idea to make that click clear the search bar, so that it's only populated with "@lang:yaml"-- discarding any previous content in the search bar.  Just an idea (might improve UX for others, but maybe they're sharper than I 😂 ), but not a necessity.

**Comment by rzhao271** [comment]
There's currently a tradeoff with the search behaviour.

If one searches a term like `tabsize` and then clicks on an "edit settings for" link, they'll get the language filter added on, and be able to see the language-specific tabsize setting immediately.
If one searches something else and then clicks on the link, they'll get the language filter added on still (so the behaviour of adding on the query stays consistent), but they might end up not finding settings in that case. I'm not sure how feasible it is to do a search first, and then change the query after if no results are found.

**Comment by pmeaney-sqrt** [comment]
Makes sense! All good amigo!! Thanks for your help & the detailed info! You rock
