### ISSUE TITLE
No CSS suggestions in PHP files

### ISSUE THREAD

**Issue by nudefireninja** [microsoft/vscode#170114]
Type: <b>Bug</b>

Does this issue occur when all extensions are disabled?: Yes

Steps to Reproduce:

1. Create a new tab a set the language mode to PHP.
2. Type html and select the html:5 emmet abbreviation.
3. Add an internal stylesheet inside the head element: `<style type="text/css"></style>`
4. Type `html { backgr`
5. VS Code won't suggest `background-color` or other CSS properties or values.

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 22.2.0
Modes: Restricted
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.77GB free)|
|Process Argv|--crash-reporter-id 1f16c0d1-50db-46da-9cdc-0eee94227323|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-docker|ms-|1.23.3

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by alexr00** [comment]
Can you share a full code snippet?

**Comment by nudefireninja** [comment]
``` html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    html {
      backgr
    }
  </style>
</head>
<body>
  
</body>
</html>
```

**Comment by alexr00** [comment]
@aeschli I think this should be coming from the built in css extension.

**Comment by aeschli** [comment]
For PHP this would have to come from a PHP extension. That extension needs to provide a language server that has support for the embedded languages as only it knows how to parse and decode a PHP file.

Please check the marketplace for a PHP extension and if you already use one, file issues of feature requests against that extension.
