### ISSUE TITLE
Break reason is shared between threads

### ISSUE THREAD

**Issue by felixfbecker** [Microsoft/vscode#1701]
If one thread breaks on exception, and the other breaks on a breakpoint, whatever reason came last will always be what is shown in the UI.

![threads issue demo gif](https://cloud.githubusercontent.com/assets/10532611/12044260/cbce6464-ae8e-11e5-9c65-b1aca96d717c.gif)

**Comment by isidorn** [comment]
Nice catch.
We now show the stopped reason for whatever thread is selected. Try it out in our January release and let us know what you think.

**Comment by felixfbecker** [comment]
:+1:
