### ISSUE TITLE
[CSS] Incorrect keyword suggestion for `justify-items` and `justify-self`

### ISSUE THREAD

**Issue by kagankan** [microsoft/vscode#170161]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: Windows 10

Steps to Reproduce:

1. Open a CSS file
2. Type `justify-items:`
3. There are `save` and `unsave` in keyword suggestion, but the keywords are incorrect

![image](https://user-images.githubusercontent.com/34136752/209833167-8b94ea41-84e8-4cfb-a790-e0ff10434071.png)

See:
https://w3c.github.io/csswg-drafts/css-align/#typedef-overflow-position

Correct keywords are below:

- save → `safe`
- unsave → `unsafe`

(`f`, not `v`)

Same issue happens for `justify-self`
(Note: `justify-content` shows correct keyword.) 

Thank you

**Comment by aeschli** [comment]
Thanks a lot. Fix is in https://github.com/microsoft/vscode-custom-data/pull/64

**Comment by jrieken** [comment]
Still seeing those

<img width="769" alt="Screenshot 2023-01-25 at 09 23 57" src="https://user-images.githubusercontent.com/1794099/214513985-1bcc8daf-3273-4886-964f-46827452e8a1.png">

**Comment by aeschli** [comment]
Trying on https://insiders.vscode.dev/, Version: 1.75.0-insider
Commit: 07d6f5b35fac559504dec65e3073d796b2d25a55
![image](https://user-images.githubusercontent.com/6461412/214817151-90c3d806-051d-41c5-aa5e-a4c525346310.png)

![image](https://user-images.githubusercontent.com/6461412/214817205-0dba1962-8b66-4425-9406-c2a62b50f3dd.png)
