### ISSUE TITLE
vscode in bugs Chinese folder name garbled

### ISSUE THREAD

**Issue by jiayouzl** [microsoft/vscode#170140]
<img width="1754" alt="iShot_2022-12-28_11 40 36" src="https://user-images.githubusercontent.com/7685337/209753718-4e7e2520-1f98-4084-a743-f0a9a342eef5.png">

**Comment by Tyriar** [comment]
Easy repro:

![image](https://user-images.githubusercontent.com/2193314/209835731-d957557f-4be8-4366-aebf-0ed9b381872f.png)
![image](https://user-images.githubusercontent.com/2193314/209835747-bdc1be42-81d2-4009-afb4-4aca31dcd093.png)

Likely Windows only.

**Comment by Tyriar** [comment]
It's an encoding issue in pwsh's shell integration cwd detection

**Comment by jiayouzl** [comment]
> 



> Easy repro:
> 
> ![image](https://user-images.githubusercontent.com/2193314/209835731-d957557f-4be8-4366-aebf-0ed9b381872f.png) ![image](https://user-images.githubusercontent.com/2193314/209835747-bdc1be42-81d2-4009-afb4-4aca31dcd093.png)
> 
> Likely Windows only.

No, my MacBook has this problem too.

**Comment by jiayouzl** [comment]
@Tyriar

**Comment by Tyriar** [comment]
@jiayouzl are you using 1.75.0-insiders?

**Comment by Tyriar** [comment]
@jiayouzl yep the fix was for pwsh on all platforms

**Comment by jiayouzl** [comment]
> @jiayouzl yep the fix was for pwsh on all platforms

Updated 1.74.3 today, but found that this bug still exists, do you want to wait for the next version to fix it?

**Comment by jiayouzl** [comment]
Thanks.
