### ISSUE TITLE
While Publishing Project in Visual Studio Code MarketPlace

### ISSUE THREAD

**Issue by rahulsahay19** [Microsoft/vscode#17019]
Hi,

I have written one ASP.NET Core-Angular 2 starter kit. This project I wanted to publish. But, while doing so, I am getting timeout error saying "Error: Request timeout: /_apis/gallery/extensions"

- VSCode Version: 1.7.1
- OS Version: Win10

Steps to Reproduce:

1. Download the code from https://github.com/rahulsahay19/MovieReviewStarterKit 
2. Download Package.json from https://gist.github.com/rahulsahay19/5a21c2e0dd23fd20d63698cde407d1ac
3. I have kept this under MovieReviewStarterKit folder as well.
4. Then, applied vsce publish command. 
5. Publish started, then after waited for sometime, it gave timeout error. 

My question is whether we can publish any project as extension. If yes, am I doing something wrong here. Looks like Package.json is not compliant with project system. 

Thanks,
Rahul

**Comment by joaomoreno** [comment]
`vsce` is meant to publish extensions to VS Code. That doesn't look like it is an extension to VS Code.

Why would you want to publish this to the VS Code Marketplace?

**Comment by rahulsahay19** [comment]
ok. I thought of publishing scaffolding project of asp.net core and angular 2 via vsce. Is there any other tool via which same project can be published?

**Comment by joaomoreno** [comment]
How do you want your sscaffolding project to be consumed?

[Yeoman](http://yeoman.io/) is a good bet.

**Comment by rahulsahay19** [comment]
Thanks!
