### ISSUE TITLE
CPP highlighting with const array declaration

### ISSUE THREAD

**Issue by vware** [microsoft/vscode#170177]
Type: <b>Bug</b>

Create a new CPP file, enter this:

```c++
static const std::string led_paths[] {
    [RED] = LED_PATH("red"),
    [GREEN] = LED_PATH("green"),
    [BLUE] = LED_PATH("blue"),
    [WHITE] = LED_PATH("white"),
};
```

Observe the confused syntax highlighting from the 2nd line onwards.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: Yes
Remote OS version: Linux x64 5.15.79.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700KF (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.83GB (16.04GB free)|
|Process Argv|--crash-reporter-id e196bcfb-10d5-4bbd-9a82-0a5e6e865f63|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Debian|
|OS|Linux x64 5.15.79.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700KF (20 x 3609)|
|Memory (System)|29.38GB (28.10GB free)|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
Kotlin|mat|1.7.1
remote-wsl|ms-|0.72.0
material-icon-theme|PKi|4.23.1
gitlens|eam|13.2.0
hexeditor|ms-|1.9.9

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
3biah626:30602489
iaj6b796:30613358
89544117:30613380
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by vware** [comment]
![image](https://user-images.githubusercontent.com/3273737/209859760-8c059c3b-5362-4d90-a4e4-0704a5687d9d.png)

**Comment by alexr00** [comment]
Moved to the repo we get our C++ syntax highlighting grammar from: https://github.com/jeff-hykin/better-cpp-syntax/issues/621

**Comment by vware** [comment]
sorry but just forwarding such issues to some barely maintained project that you guys ship jwith vscode ust seems lazy. in addition to the maintainer of the project being a lovely person... not.
