### ISSUE TITLE
Feature Request: Git Diff/Undo from gutter

### ISSUE THREAD

**Issue by CoenraadS** [Microsoft/vscode#17017]
Hello

vscode 1.7.2

VSCode displays changed lines in the gutter. However to 'undo' a change, we have to first stage all the changes we want, and then undo whatever is left.

However this requires many clicks and context changes.
1. Git  
2. Diff   
3. Click Lines you want to keep  
4. Click undo on non-stages lines   

In Visual Studio I have an extension that allows me to undo lines/hunks by clicking that git gutter decoration:

![diff margin example](https://cloud.githubusercontent.com/assets/5593825/21073237/066e5ccc-bed9-11e6-867f-22029b887a93.gif)

I do not think it is possible to create a similar extension because there is no public api to hook the click event. So I am requesting it either be integrated into VS, or expose click events as an API.

**Comment by alexandrudima** [comment]
fyi @joaomoreno

**Comment by joaomoreno** [comment]
#10782
