### ISSUE TITLE
Shift+home/end now go to the end of the selection start's line, not the selection's end

### ISSUE THREAD

**Issue by Tyriar** [Microsoft/vscode#17011]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:05:39.439Z)
- OS Version: Linux x64 4.8.0-28-generic
- Extensions:

|Extension|Author|Version|
|---|---|---|
|EditorConfig|EditorConfig|0.3.4|
|lorem-ipsum|Tyriar|1.0.0|
|sort-lines|Tyriar|1.1.0|
|theme-glacier|Tyriar|0.0.10|
|vscode-svgviewer|cssho|1.2.0|
|vscode-eslint|dbaeumer|1.1.0|
|tslint|eg2|0.7.1|
|git-project-manager|felipecaputo|1.0.0|
|Theme-Wombat|gerane|0.0.2|
|md-navigate|jrieken|0.0.1|
|vscode-scss|mrmlnc|0.6.0|
|typescript-javascript-grammar|ms-vscode|0.0.11|
|sass-indented|robinbentley|1.2.1|
|dark-plus-material|vangware|0.1.4|

---

Steps to Reproduce:

1. Create an untitled file and add content:

    ```
    foo
    bar
    ```

2. Put the cursor after the `f`
3. Hold shift, press down and then end, the selection should be `oo\nbar`
4. Hold shift, press home, the selection should be `oo\n` but it is `f` because the select went to the start of the wrong line.

**Comment by kumarharsh** [comment]
This used to work till yesterday... something broke. I'm pressing <kbd>end</kbd> after going 3 lines above, and the cursor goes to the end of the selectionStart line.

![bug](https://cloud.githubusercontent.com/assets/760112/21099199/d0f0478e-c092-11e6-9827-f3f1918fc93f.gif)
