### ISSUE TITLE
Port Forwarding Incorrect Port Breaks Tunneling 

### ISSUE THREAD

**Issue by marvthedonut** [microsoft/vscode#170198]
Type: <b>Bug</b>

Tunneling server is running on an up to date Raspberry Pi V4 4gb ram. (Running Raspian)

Tunneling server will not respond after trying to add a port forward that does not exist. (E.g. trying to forward port 2000 when nothing is running on port 2000)

Steps to Reproduce
1. Start vscode tunnel in systemctl service. (code tunnel)
2. Connect to the tunnel and try to portforward a port that is not in use

The logs will show an error along the lines of "Error connecting forwarding to 127.0.0.1:<port>, Connection refused (os error 111)"

It will not connect until the service is restarted.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|11.82GB (2.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by marvthedonut** [comment]
Seems similar to #170042

**Comment by connor4312** [comment]
This is an old duplicate, fixed a while ago
