### ISSUE TITLE
Cannot attach to remote container via remote tunnel

### ISSUE THREAD

**Issue by ZgblKylin** [microsoft/vscode#170206]
When connected to remote machine via remote tunnel, the `Containers` page in `Remote resources` tab should show containers in REMOTE machine, not in HOST machine.

It's behavior should like remote SSH, we could remote-ssh to another machine, and then use `attatch to container` to oppen projects inside containers on that machine, instead of direct SSH into the remote container(that needs to run SSH service inside container).

But remote tunnel doesn't support this operation. When I connected to remote machine via tunnel, the dev container page still shows containers on my local machine.

**Comment by chrmarti** [comment]
Tracking as https://github.com/microsoft/vscode-remote-release/issues/7705. Thanks.
