### ISSUE TITLE
ClearType blurry font rendering

### ISSUE THREAD

**Issue by gwdsir** [microsoft/vscode#170225]
Does this issue occur when all extensions are disabled?: No

- VS Code Version: 1.74.2(user setup)
- OS Version: Windows_NT x64 10.0.19044

Steps to Reproduce:
It seems wrong when I launch, looks not clear when I using it. Im not sure why, or it depends on the Windows Clear Type settings, just like the following pictures:
![Snipaste_2022-12-29_21-33-33](https://user-images.githubusercontent.com/121615263/209961131-f06945d4-43c3-4784-8f40-318575beba9d.png)

plz help me!!!

**Comment by deepak1556** [comment]
Can you share your cleartype font settings ? Does the issue repro when running with `--disable-gpu` ?

**Comment by gwdsir** [comment]
> Can you share your cleartype font settings ? Does the issue repro when running with `--disable-gpu` ?

Does it means to launch vscode with the opt '--disable-gpu'?
I don't know how to share my cleartype settings. Just share the choices when setting?

**Comment by gwdsir** [comment]
> Can you share your cleartype font settings ? Does the issue repro when running with `--disable-gpu` ?

this screenshot is the view when losing focus, also happened to the areas which no longer rendering

**Comment by gwdsir** [comment]
![1](https://user-images.githubusercontent.com/121615263/210971992-79c2b47e-3c3f-46d5-8544-ecf3d619f844.png)
![2](https://user-images.githubusercontent.com/121615263/210972002-92b13c97-4d0d-4732-929e-58ec5035593a.png)
![3](https://user-images.githubusercontent.com/121615263/210972005-131bbf63-5e63-47aa-8dff-9a7de7b3ef5e.png)
![4](https://user-images.githubusercontent.com/121615263/210972007-db422ccd-473f-45c7-b5d8-7ddfa05f6a9b.png)
![5](https://user-images.githubusercontent.com/121615263/210972010-b41ae20f-564e-498d-92c6-9799630a4c6c.png)

**Comment by gwdsir** [comment]
Thanks a lot!!!
It really works well with `--disable-gpu`, but I wonder how it works.

**Comment by deepak1556** [comment]
This is issue with font rendering in the runtime https://bugs.chromium.org/p/chromium/issues/detail?id=534732, please continue to use the workaround https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration
