### ISSUE TITLE
Make the file dialog sheet appear in the right place when using the "Command Center" feature.

### ISSUE THREAD

**Issue by GGIEnrike** [microsoft/vscode#170297]
The issue is present in the insiders build.

Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2 (Universal)
- OS Version: any

Steps to Reproduce (only applicable to macOS):

1. Enable "Window: Command Center" in the settings.
2. Press cmd+o or File > Open...
 
The native file picker dialog appears as a sheet attached to the window title bar. When a window uses the native title bar, the sheet attaches to the bottom of it. So, when the title bar is created with custom html the sheet's position needs to be changed to visually appear in the right place (bottom of the title bar). When not using the "Command Center" feature, the custom title bar is the same height as the native one, so there is no need to adjust anything. But when enabling the said feature, the title bar height increases, requiring the sheet to be moved down.

As per Electron documentation ([here](https://www.electronjs.org/docs/latest/api/dialog#sheets) and [here](https://www.electronjs.org/docs/latest/api/browser-window#winsetsheetoffsetoffsety-offsetx-macos), this should be accomplished by calling `win.setSheetOffset(offsetY[, offsetX])` (the `offsetX` wouldn't be needed here).

**Comment by rzhao271** [comment]
\gifPlease
