### ISSUE TITLE
buffer newly created breakpoints until initialize request is received 

### ISSUE THREAD

**Issue by weinand** [Microsoft/vscode#1702]
A debug adapter is free to request persisted breakpoints at any time by sending an "initialize" request. If another breakpoint is created before the "initialize" request has arrived, the breakpoint is directly sent to the adapter without waiting for the "initialize" request. This is a bug. We should buffer these breakpoints and send them to the adapter only upon receipt of the "initialize".

cc @felixfbecker

**Comment by roslanr18** [comment]
.
