### ISSUE TITLE
Better coloring of matching braces.

### ISSUE THREAD

**Issue by JTMartins** [Microsoft/vscode#17029]
Request.

Currently when we have the cursor near a ( ] } etc, the matching brace color is extremely faint, and difficult to spot in the middle of the code.

A stronger and contrasting background color ( as it happens on the Brackets editor) would help tremendously.

**Comment by Mkayxx** [comment]
try downloading 1 of the 2 extensions available on the marketplace,they work preety good.
[https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets](url)
[https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer](url)

**Comment by JTMartins** [comment]
Thanks, Mkayxx,

I'm using rainbow brackets..It helps a lot for javascript.

However in HTML the matching tag has a light gray as background and that, for me is difficult to spot in a crowded document and dark theme. 

Also if you try the high contrast theme in html, you will realize that matching tags can't be seen.

instead of a gray background, a stronger colour would be much better, in my opinion.

**Comment by Mkayxx** [comment]
Try yo code, its really good for customizing your theme and brackets.Do some research and you will find what you want

**Comment by JTMartins** [comment]
will do. Many thanks.

**Comment by bpasero** [comment]
https://github.com/Microsoft/vscode/issues/3788
