### ISSUE TITLE
Autocomplete triggered on backspace

### ISSUE THREAD

**Issue by atombender** [Microsoft/vscode#17025]
- VSCode Version: 1.7.2

Steps to Reproduce:

1. Type `foo` + a space.
2. Backspace once.
3. Autocomplete dropdown is shown.

To me, this makes no sense and is disruptive. Autocompletion should only occur for the word I'm typing. If I typed a word and then space, then I was finished with it. The autocompletion dropdown is visually disruptive, but is also disruptive of one's typing. For example, if the steps are:

1. Type `foo` + a space.
2. Backspace once.
3. Press Enter.

...then no line break is inserted, because the Enter keypress confirmed the autocomplete box. I wouldn't expect this to happen: It means whether or not Enter has an effect is not deterministic; I would expect hitting Backspace + Enter in _any_ part of the editor to result in delete + line break, but this isn't true. I constantly find myself fighting the autocomplete dropdown because of this.

**Comment by jrieken** [comment]
We fixed that in Jan
