### ISSUE TITLE
Hiding submodules and making the setting available for everyone

### ISSUE THREAD

**Issue by benesjan** [microsoft/vscode#170265]
I am currently struggling with an issue which was once opened [here](https://github.com/microsoft/vscode/issues/78359). This is what my source control tab currently looks like:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/13470840/210031168-ab3c87aa-08c3-4733-894c-ead6fa953a90.png">

I know I can hide them one by one in the source control menu but this is not sufficient for me because I would like my colleagues to have them automatically hidden as well. Is there a way to commit this setting? If not I think it would be a great feature to add. Thank you

**Comment by lszomoru** [comment]
Have you tried using the `git.detectSubmodules` so that VS Code does not detect submodules? Toggling this setting will disable the detection of the submodules? If this yields the desired outcome, you can check-in the setting into the workspace in order to share it with your colleagues.

**Comment by benesjan** [comment]
`git.detectSubmodules` did the trick. Thank you
