### ISSUE TITLE
LanguageServer Crash after successuflly executing onDidChangeContent callback

### ISSUE THREAD

**Issue by apazureck** [Microsoft/vscode#17024]
- VSCode Version: 1.8.0 - Insider
- OS Version: Windows 10

Hello,

I am trying to integrate an xml linter in vscode and have a problem, that after my ondidchangecontent, after I ran xmllint and  the callback returned successfully (message in the last line of my event callback) my language server crashes and gets restarted.

I read it might have to do with memory leaks that node crashes there, but I am not able to obtain any debug information and the language server is not putting out any logs (or they are hidden anywhere).

Steps to Reproduce:

1. clone this repo: https://github.com/apazureck/vscode-xml-linter.git
2. open server folder
3. run "npm install"
4. run Build task
5. open client folder
6. run "npm install"
7. start client project
8. open in the extension development host the folder test (included in the repo)
9. open the test.xml document
10. do some changes on the document (spaces anywhere)

-> After that have a look on the console. The Languageserver will crash after the onDidDocumentChange ran.

So my questions are:
1. Why is this happening? Am I doing something wrong or may this be a bug somewhere else?
2. How can I get the crash dump from my language server? I looked everywhere and tried to catch uncaught exceptions on the server.

Thank you

**Comment by dbaeumer** [comment]
@apazureck the code looks good to me and I think the server is not crashing. I suspect that some of the libraries code have a `process.exit()` statement which makes the server simply exit. You can prevent this by monkey patching process.exit(). There is little we can do in the library. Monkey patching it in there might be unwanted as well.

Let me know if this is the problem.

**Comment by dbaeumer** [comment]
Something like:
```typescript
const nodeExit = process.exit;
process.exit = (code?: number) => {
	let stack = new Error('stack');
	connection.console.log(stack.stack);
	setTimeout(() => {
		nodeExit(code);
	}, 3000);
}
```

**Comment by apazureck** [comment]
Hi,
The developer of the xml linter told me that the script does not run well on node.js. I found other tools to work around this. Thank you for your help.
