### ISSUE TITLE
Commenting out code does not work properly

### ISSUE THREAD

**Issue by arashsa** [Microsoft/vscode#17023]
- VSCode Version: 1.7.2
- OS Version: Mac OS Sierra 10.12.1

Steps to Reproduce:

1. Open editor and a Python file
2. Try commenting out code

So this is a bug that is hard to reproduce, but at times I can't comment out code using shortcut "cmd + /". The solution for me has been to quit VSCode and then restart it.

**Comment by mrmlnc** [comment]
Hello, @arashsa,

Small clarification: you use English language for editor?

**Comment by arashsa** [comment]
Yes, English language, and the packages I have installed are: 1.Material-theme 2.Python for VSCode. So I keep it very light-weight, but I don't know if those packages might have something to do with it.

**Comment by c01nd01r** [comment]
Yep, I have a similar problem. 
And cmd + ] / cmd+ [.
MacOS 10.11, VSCode 1.7.2 (1.7.2)

**Comment by alexandrudima** [comment]
@arashsa 

This works for me:

![17023](https://cloud.githubusercontent.com/assets/5047891/21101320/d9456e74-c078-11e6-890a-a580fd74688a.gif)

Perhaps there is an extension that causes this issue, can you reproduce when disabling all extensions?

**Comment by c01nd01r** [comment]
@arashsa
For me, it's a floating bug... I do not know when he will next time.

**Comment by alexandrudima** [comment]
@c01nd01r It seems you are having a different issue that toggling line comment not working? I suggest you open a separate issue with clear steps

**Comment by alexandrudima** [comment]
Without further information about the exact keyboard layout used, I cannot validate, but simply assume that we now (i.e. after PR #22894 aka #17521 -- in tomorrow's Insiders build) behave correctly for this keyboard layout.
