### ISSUE TITLE
create a launch.json file opens extension manager instead of empty .vscode/launch.json

### ISSUE THREAD

**Issue by thadguidry** [microsoft/vscode#170289]
Type: <b>Bug</b>

1. Start a new empty project or use existing without .vscode folder setup initially.
2. Press Ctrl + Shift + D to open the Run panel.
3. Run panel is shown with a blue link for **create a launch.json file**
4. click on blue link and notice that extension manager opens trying to find a 'JSON with comments' extension in the marketplace, instead of creating a new empty `.vscode/launch.json` file.

VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:21:57.802Z)
OS version: Windows_NT x64 10.0.22623
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.93GB (48.76GB free)|
|Process Argv|--crash-reporter-id ec828980-5f99-4b3a-9589-b598d2900347|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (34)</summary>

Extension|Author (truncated)|Version
---|---|---
asciidoctor-vscode|asc|2.9.8
vscode-eslint|dba|2.3.0
gitlens|eam|13.2.0
vscode-firefox-debug|fir|2.9.8
vscode-pull-request-github|Git|0.57.2022122909
vscode-graphql|Gra|0.8.4
vscode-graphql-syntax|Gra|1.0.5
vscode-docker|ms-|1.23.3
playwright|ms-|1.0.3
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
remote-containers|ms-|0.269.0
remote-wsl|ms-|0.72.0
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
cpptools-extension-pack|ms-|1.3.0
test-adapter-converter|ms-|0.1.6
fabric8-analytics|red|0.3.6
java|red|1.13.0
vscode-xml|red|0.23.0
vscode-yaml|red|1.10.1
rust-analyzer|rus|0.3.1334
sonarlint-vscode|Son|3.13.0
svelte-vscode|sve|106.4.1
cmake|twx|0.0.17
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-java-test|vsc|0.37.1
vscode-maven|vsc|0.40.2
markdown-all-in-one|yzh|3.5.0

(1 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vshan820:30294714
pythondataviewer:30285072
vscod805:30301674
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vscaac:30438845
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30618038
pylantcb52:30590116
pyindex848:30611229
nodejswelcome1:30587009
pyind779:30611226
pythonsymbol12:30622696
fim-prod:30623723

```

</details>

**Comment by roblourens** [comment]
That extension should be built in, so either it's missing somehow or it got disabled. If you search `@builtin json` in the extensions viewlet, do you see a "JSON Language Basics" extension?

**Comment by thadguidry** [comment]
@roblourens Yes.

![image](https://user-images.githubusercontent.com/986438/210123442-339b6215-49ab-43c6-92fb-95eb95f3a5d7.png)

**Comment by roblourens** [comment]
Can you share a screenshot of what happens when you click that link?

Is it the same with extensions disabled?

Does it work in vscode stable?

**Comment by thadguidry** [comment]
@roblourens Perhaps I'm missing the C++ (GDB/LLDB) template option in the dropdown as suggested by the project setup docs here: https://docs.godotengine.org/en/stable/development/cpp/configuring_an_ide/visual_studio_code.html#debugging-the-project

If I completely delete (move to recycle bin) the `.vscode` folder by right-clicking and deleting it within VSC and then click on Run and Debug icon (CTRL + Shift + D) and then click on `create a launch.json file` blue link, it opens the dropdown (not showing an option for C++ (GDB/LLDB).

![image](https://user-images.githubusercontent.com/986438/210123612-a1c1212c-abeb-44f0-9fee-cd4b3b4551f1.png)

**Comment by roblourens** [comment]
Seems like a different issue, you could file an issue on the cpptools extension about that.

**Comment by thadguidry** [comment]
Thanks will do that. Closing.
