### ISSUE TITLE
Cell execution result not showing when it contains angle brackets

### ISSUE THREAD

**Issue by chenhao1umbc** [microsoft/vscode#170263]
Type: <b>Bug</b>

it just randomly happend, I do not know how to reproduce it. It happened quite a lot of times, which was really annoying 

Extension version: 2022.11.1003412109
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:27:19.253Z)
OS version: Linux x64 5.15.0-56-generic
Modes:
Sandboxed: No
Remote OS version: Linux x64 4.4.0-235-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1319)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|15.49GB (9.27GB free)|
|Process Argv|--unity-launch --crash-reporter-id 890f7787-50ba-4207-9b29-fe529d42b4b5|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu-xorg|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu-xorg|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: pensees|
|OS|Linux x64 4.4.0-235-generic|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (56 x 2945)|
|Memory (System)|251.81GB (237.11GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
282f8724:30602487
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by rebornix** [comment]
@DonJayamanne thanks for the analysis!
