### ISSUE TITLE
Custom keybindings are applied to wrong cursor when findInputFocussed

### ISSUE THREAD

**Issue by bohendo** [Microsoft/vscode#17026]
- VSCode Version:  1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f)
- OS Version: Ubuntu 14.04.5 LTS

keybindings.json
`[`
`{ "key": "ctrl-a",       "command": "expandLineSelection", "when": "findInputFocussed"},`
`{ "key": "ctrl-h",       "command": "deleteWordLeft"}`
`]`

Steps to Reproduce:

1. Open find widget ie `alt-e f`
2. typing ctrl-a will expand the selection around the invisible cursor in the editor body
3. typing ctrl-h will delete words in the editor body

The when clause is being successfully applied in the first case but the commands are happening at the wrong cursor ie typing `ctrl-a` will not select all, instead it will expand the selection around the invisible cursor in the editor body.

Globally applied keybindings do the same thing ie the second entry in keybindings.json

This occurs with **every** custom keybinding I've tested.

PS. I discovered `findInputFocussed` when browsing the properties of the copy/pasted context in [#16498](https://github.com/Microsoft/vscode/issues/16498).. it's misspelled and the correct spelling doesn't work. Not the core of my problem but maybe worth noting.

I'm new to VS Code and I love it so far! Thank you and keep up the great work!

**Comment by alexandrudima** [comment]
The find widget is not using an editor as its implementation at this time. The find widget is a simple HTML5 `<input>` element and does not support `expandLineSelection`.

The `expandLineSelection` command works by first picking the focused editor, and if no editor is focused, it falls back to using what the workbench considers the active editor. i.e. the last used editor. That is the editor that gets the file opened when clicking on a file in the explorer.

In this case, `expandLineSelection` sees that no editor widget is focused and proceeds to find the "active" one and execute in the context of that editor.

To make this work, we would need to replace the find widget's input box with an editor widget.

**Comment by alexandrudima** [comment]
fyi @rebornix

**Comment by rebornix** [comment]
This feature request will not be considered in the next [6-12 months roadmap](https://github.com/Microsoft/vscode/wiki/Roadmap) and as such will be closed to keep the number of issues we have to maintain actionable. Thanks for understanding and happy coding!
