### ISSUE TITLE
Can't close a non-existent repository in Source Control

### ISSUE THREAD

**Issue by Iemane291** [microsoft/vscode#170360]
Type: <b>Bug</b>

Clone a repository inside of your workspace and try to select one of the files outside of the repository folder that was made after cloning (aka your workspace) and the other files outside of that repository folder go into another non-existent repository which cannot be closed in Source Control by right clicking on the repository and clicking "Close Repository".

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 7, 6|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 0baba4a4-246c-4095-b5c8-4cbb745fa5b1|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (73)</summary>

Extension|Author (truncated)|Version
---|---|---
language-x86-64-assembly|13x|3.0.0
lua-debug|act|1.60.3
codesnap|adp|1.3.4
time-to-relax|ana|0.0.4
language-mcfunction|arc|0.18.0
intellij-theme|arz|1.11.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
vscode-html-css|ecm|1.13.1
vscode-npm-script|eg2|0.3.29
vsc-material-theme|Equ|33.6.0
vsc-material-theme-icons|equ|2.5.0
auto-rename-tag|for|0.1.10
c-cpp-runner|fra|5.0.0
haxe-hl|Hax|1.3.4
gzipdecompressor|Hyu|1.2.0
codewind-node-profiler|IBM|0.9.0
discord-vscode|icr|5.8.0
monkey-patch|ioc|0.1.23
search-node-modules|jas|1.3.0
intelliskript|Joh|1.7.0
skript|Joh|0.2.0
vscode-peacock|joh|4.2.2
MagicPython|mag|1.1.0
jetbrains-icons|mar|1.1.0
fluent-icons|mig|0.0.18
dotenv|mik|1.0.1
theme-monokai-pro-vscode|mon|1.2.0
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cmake-tools|ms-|1.12.27
cpptools|ms-|1.13.8
js-debug-nightly|ms-|2022.12.1417
live-server|ms-|0.4.4
vsliveshare|ms-|1.0.5788
vshaxe|nad|2.25.0
autodocstring|njp|0.6.1
vscode-python-typehint|njq|1.5.1
lime-vscode-extension|ope|1.4.3
skript-vscode|pen|2.1.3
material-product-icons|PKi|1.4.1
ruby|reb|0.28.1
vscode-commons|red|0.0.6
vscode-xml|red|0.23.0
LiveServer|rit|5.7.9
preview-vscode|sea|2.2.5
swdc-vscode|sof|2.6.38
datapack-language-server|SPG|3.4.1
cython|tcw|0.1.0
html-preview-vscode|tht|0.2.5
cmake|twx|0.0.17
vscode-lldb|vad|1.8.1
vskript|Vho|0.0.8
vscode-icons|vsc|12.0.1
haxe-checkstyle|vsh|1.8.2
haxe-debug|vsh|1.2.3
haxe-extension-pack|vsh|1.3.0
nodejs-extension-pack|wad|0.1.9
quokka-vscode|Wal|1.0.519
vscode-todo-highlight|way|1.0.5
codedox|wig|1.3.3
vscode-ruby|win|0.28.0
JavaScriptSnippets|xab|1.8.0
material-theme|zhu|3.15.6
One-dark-pro|zhu|3.15.6

(20 theme extensions excluded)

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vscccc:30610679
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
3d0df643:30613357
89544117:30613380
fim-prod:30623723
vscsb:30628654

```

</details>

**Comment by mrariful786** [comment]
lszomoru/scm-input-onDidChangeValue
