### ISSUE TITLE
Cannot start new terminals when opened from the terminal

### ISSUE THREAD

**Issue by azdavis** [microsoft/vscode#170388]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2 e8a3071ea4344d9d48ef8a4df2c097372b0c5161 arm64
- OS Version: macOS 12.6.1 21G217

## Steps to Reproduce

1. Open VS Code on a folder
2. Open a terminal
3. From the terminal, use the `code` command to open VS Code on a new folder
4. From that newly opened VS Code, attempt to bring up a terminal

## Expected

VS Code can bring up a new terminal

## Actual

VS Code fails to start any new terminals

## Video

[Video of the bug](https://www.dropbox.com/s/bblku0b0plh4lrx/vscode-open-folder-terminal-no-launch-bug.mov?dl=0)

**Comment by meganrogge** [comment]
You'll need to click the console tab instead of the issues one then reproduce the issue

**Comment by azdavis** [comment]
It doesn't show anything

<img width="1624" alt="Screen Shot 2023-01-06 at 5 46 27 PM" src="https://user-images.githubusercontent.com/6496454/211125752-79bddbe1-3387-4d25-89c3-288b5b1e8b31.png">

**Comment by meganrogge** [comment]
I've seen reports of this, but cannot reproduce it myself

**Comment by meganrogge** [comment]
Can you reproduce this in insider's @azdavis?

**Comment by azdavis** [comment]
I cannot
