### ISSUE TITLE
Folding does not behave well for c/c++ goto(label) syntax

### ISSUE THREAD

**Issue by tangshi** [Microsoft/vscode#17032]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:01:10.756Z)
- OS Version: Darwin x64 15.6.0

Steps to Reproduce: Always.

**Comment by aeschli** [comment]
The currently implemented folding strategy is based purely on the indentation of lines. A folding region starts when a line has a smaller indent than one or more following lines, and ends when there is a line with the same or smaller indent.

To be more smart and to, for example, understand c constructs such as goto, we will have to go one step further and introduce language agnostic folding regions. We have issue #3422 for this.
