### ISSUE TITLE
Show inline breakpoint action buttons when sidebar is truncated

### ISSUE THREAD

**Issue by BrianPittVP** [microsoft/vscode#170368]
Breakpoints in the sidebar list show the file and full path to the file.  To the far right of that line, after the full path, there are action buttons to edit or delete the breakpoint.  If the sidebar is narrow and requires scrolling, those action buttons are hidden.  The action buttons should show on mouse-over every time, regardless of the sidebar width.

![image](https://user-images.githubusercontent.com/97061131/210182072-a839c70b-3a44-4bab-9227-fb3a52be3352.png)

**Comment by roblourens** [comment]
Horizontal scrolling is not enabled by default, partly because of UX issues like this
