### ISSUE TITLE
Control the editor for viewing diffs.

### ISSUE THREAD

**Issue by zjffun** [microsoft/vscode#170325]
We create a [custom editor](https://marketplace.visualstudio.com/items?itemName=zjffun.snippetsmanager) for editing code snippets expediently. During test, we found this custom editor will be using when viewing diffs and can't change to built in text diff editor.
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/25266120/210124039-70fa2e8e-ff8f-4f50-9440-aa5656e307a8.png">

Those ways may help control the editor for viewing diffs:

- Adding `Open Changes With...` in the context menu.
  <img width="240" alt="image" src="https://user-images.githubusercontent.com/25266120/210124340-dcf7812e-71bf-477f-a918-896610670095.png">
- or adding a setting to config the editor for viewing diffs.
- or adding an option to control whether this editor should be using when viewing diffs. https://code.visualstudio.com/api/extension-guides/custom-editors#contribution-point

Thank you and happy new year.

**Comment by lszomoru** [comment]
@zjffun, apologies for not getting back to you on this. The menu items in [the resource's context menu](https://code.visualstudio.com/api/extension-guides/scm-provider#menus) are contributable so you should be able to contribute your own `Open Changes With...`  menu which when invoked would open the editor of your choice. I will go ahead and close this issue but in case you still have any questions or concerns please don't hesitate to reopen the issue. Thanks!
