### ISSUE TITLE
VScode is not quitting application or tabs

### ISSUE THREAD

**Issue by WaleedKhan24** [microsoft/vscode#170335]
Does this issue occur when all extensions are disabled?: Yes/No

- VS Code Version: 
- OS Version: 

Steps to Reproduce:

1. 

Attached is a screen recording of my issue and my problem it does not let me close any tabs or quit vs code

**Comment by WaleedKhan24** [comment]
[Screen Recording 2022-12-31 at 9.18.33 AM.mov.zip](https://github.com/microsoft/vscode/files/10328170/Screen.Recording.2022-12-31.at.9.18.33.AM.mov.zip)

**Comment by bpasero** [comment]
https://github.com/microsoft/vscode/issues/170334
