### ISSUE TITLE
Extensions get uninstalled after restarting VSCode

### ISSUE THREAD

**Issue by marcelino-borges** [microsoft/vscode#170336]
Type: <b>Bug</b>

- Install a few extensions in a VS Code fresh instalation
- Restart Vs Code
- All extensions previously installed are not installed anymore

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700K (20 x 3610)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.80GB (17.98GB free)|
|Process Argv|E:\\Projetos\\Web\\CompanyName\\project-name\\projetos\\MyProjectMobile --crash-reporter-id f66760ee-b7f8-4629-8c12-eed05fee0976|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
2e4cg342:30602488
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by SertugF** [comment]
Hello, try to remove all extensions manually then reinstall them. For windows, extensions most likely gonna be in one of these : 

>  %USER%\\.vscode\extensions (or) %USERPROFILE%\.vscode\extensions

**Comment by sandy081** [comment]
May I know how you are installing extensions? If possible please provide a gif/video of the issue you are seeing.

**Comment by marcelino-borges** [comment]
> Hello, try to remove all extensions manually then reinstall them. For windows, extensions most likely gonna be in one of these:
> 
> > %USER%\.vscode\extensions (or) %USERPROFILE%.vscode\extensions

Apparently manually removing the extensions folder from `%USER%\.vscode\extensions` and reinstalling the extensions fixed the problem. Now I'm gonna reinstall hundreds of extensions again 



> May I know how you are installing extensions? If possible please provide a gif/video of the issue you are seeing.

All my extensions were installed inside VS Code

I appreciate the help!
