### ISSUE TITLE
BackgroundDownload.exe

### ISSUE THREAD

**Issue by rezacypher** [microsoft/vscode#170361]
Type: <b>Bug</b>

keeps popping up on my BWmeter Firewall even though I have disabled the Background Download.

Why it's Attempting to Download Without My Permission?

Last Known Attempt:
C:\Users\mamad\AppData\Local\Temp\wm0icbfg.jgj\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\BackgroundDownload.exe

This is more like a worm than an auto-updater.

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (12.16GB free)|
|Process Argv|--crash-reporter-id cff85c9f-39f8-4669-ba12-92215ea35666|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
debugger-for-mainframe|Bro|1.6.0
dart-code|Dar|3.50.0
flutter|Dar|3.50.0
vscode-html-css|ecm|1.13.1
html-preview-vscode|geo|0.2.5
batch-rename-extension|Jan|0.0.5
python|ms-|2022.16.1
vscode-pylance|ms-|2022.10.30
jupyter|ms-|2022.9.1202862440
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.10
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
batch-runner|Nil|1.0.0
subtitles-editor|pep|1.1.7

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
3biah626:30602489
3d0df643:30613357
89544117:30613380
fim-prod:30623723
vscup:30628656

```

</details>

**Comment by mrariful786** [comment]
src/vs/base/browser/ui/grid/gridview.ts

**Comment by rezacypher** [comment]
> gridview.ts

Be more specific, please.
there is no folder related in my system to contain such a file.

**Comment by joaomoreno** [comment]
This seems to be an issue specific with **Visual Studio**, not **Visual Studio Code**.
