### ISSUE TITLE
2 Issues: Integrated terminal + Running NodeJS

### ISSUE THREAD

**Issue by nabulsi** [Microsoft/vscode#17035]
- VSCode Version: 1.7.2
- OS Version: OSX 10.11.6

Issue 1:
======
Steps to Reproduce:
1.  View -> integrated terminal
Then I get the the error:
_The terminal process terminated with exit code: 1_

I have tried suggestions mentioned in other tickets but no luck. E.g.:
 1) Re-installing Node and Code
 2) I have added this to "User Settings" 
"terminal.integrated.shellArgs.osx": ["-l"]

All didn't work. 
Note: I can reproduce it in Insiders (1.8.0).

Issue 2:
======
In addition, I have another issue for which I tried several things but the problem is still there. I cannot run my project, it gives me the error:
"Cannot find runtime 'node' on PATH"

Only if I add to launch.json the following line it works:
"runtimeExecutable": "/usr/local/bin/node"
I noticed that my path looks like this:
**PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin**
But if in Code, toggle developer tools -->show the console and then show "process.env", I see the PATH like this:
**"/usr/bin:/bin:/usr/sbin:/sbin"**

Which is lacking where node is installed and will fail consequently:
```
which node
/usr/local/bin/node

node -v
v7.2.1
```

I am not sure if there is a single problem causing all these issues in my setup

**Comment by Tyriar** [comment]
**Issue 1**

Did you get a different error message on Insiders? It's meant to print the shell and shell args that failed to launch now.

**Issue 2**

I believe this is due to the OSX environment not having your path that you setup in `.bashrc` (or similar) when you launch though the bar at the bottom. Can you work around this by launching vscode from your terminal?

**Comment by nabulsi** [comment]
Tyriar@
**Issue1**: In Insiders, this is the error I get:
_The terminal process command `/bin/false l` failed to launch (exit code: 1)_

**Issue2**:
When I launch VSCode from the terminal the debug works fine. I see the right path also in the developer tools.
 
On the other hand, testing to launch the app normally, I removed the runtimeExecutable from the launch.json file, then I created ~/.bashrc file and added to it:
export PATH=my_full_path

I got the same error message:
_"Cannot find runtime 'node' on PATH"_

The same behavior is applicable to Insiders

Here are some more error details:

> messageService.ts:128 Cannot find runtime 'node' on PATH.: Error: Cannot find runtime 'node' on PATH.
>     at Object.f [as create] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29:20675)
>     at file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:121:27301
>     at Object.v [as _notify] (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:10797)
>     at Object.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:14302)
>     at _run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:15623)
>     at _chainedError (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:14982)
>     at n (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:12805)
>     at then (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:16432)
>     at Object.enter (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:12874)
>     at _run (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:15623)
>     at _setCompleteValue (file:////Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:31:15317)

**Comment by Tyriar** [comment]
**Issue 1**

You have your `$SHELL` env var set to `/bin/false`, you will need to override it in your settings.json:

```js
"terminal.integrated.shell.linux": "/bin/bash"
```

**Issue 2**

@joaomoreno do you know more about this OSX env issue when launching from task bar (whatever it's called)?

**Comment by nabulsi** [comment]
Issue 1 is fixed by using the suggested setting:
"terminal.integrated.shell.osx": "/bin/bash"

I hope we can find a solution for issue 2.

Thanks

**Comment by joaomoreno** [comment]
Issue 2 is very likely also related to the fact that your `$SHELL` is set to `/bin/false`.

If you open Terminal on OSX, does it work?

- http://apple.stackexchange.com/questions/233529/el-capitan-mac-usr-bin-login-tries-to-run-bin-false
- http://unix.stackexchange.com/questions/295680/cannot-exec-bin-false-no-such-file-or-directory
- https://discussions.apple.com/thread/7519361?start=0&tstart=0

Seems to be a common issue with some OS X users.

Try changing your [default shell](http://superuser.com/questions/362372/how-to-change-the-login-shell-on-mac-os-x-from-bash-to-zsh) and restarting.

**Comment by nabulsi** [comment]
@joaomoreno and @Tyriar Thanks a lot for all your support. 

Both issues are now resolved following your suggestions.

**Comment by joaomoreno** [comment]
Awesome, great to know!

**Comment by Tyriar** [comment]
Thanks @joaomoreno
