### ISSUE TITLE
Cannot launch 1.7.2 OS X Sierra

### ISSUE THREAD

**Issue by fedorinoGore** [Microsoft/vscode#17034]
- VSCode Version: 1.7.2.
- OS Version: 10.12.1 OS X Sierra

Steps to Reproduce:

1. type `code` in terminal OR launch **VS Code** from the Application folder 
2. the icon of the **VS Code** shows itself in the dock for the second and then disappears
3. starting from terminal with `code --verbose` shows this:
```
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[main 15:01:30] Sending env to running instance...
[main 15:01:30] Sent env to running instance. Terminating... 
```

**Comment by bpasero** [comment]
@fedorinoGore you seem to have a zombie VSCode process hanging around, can you use activity monitor to find and terminate it and then try again? a restart would also help.

**Comment by fedorinoGore** [comment]
Nope. That behaviour was somehow connected with my working instance of iTerm2 app. After scanning for all processes and finding no zombies, I tried to kill and restart my terminal as other apps also acted strange (yarn, npm, atom). And this makes them all work again. I belive it was corrupted ./bashrc enviroment and has nothing to do with VS Code, sorry, false alert :(
