### ISSUE TITLE
Different Environment Variables for ptyHost than Renderer

### ISSUE THREAD

**Issue by jonathansampson** [microsoft/vscode#170324]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2
- OS Version: 10 (19045.2364)

Steps to Reproduce:

1. Create environment variable named "DEBUG"
2. Launch `node` in integrated terminal, run `process.env.DEBUG`
3. Launch `node` in external instance of cmd.exe, run `process.env.DEBUG`

`undefined` is returned for integrated terminal, but not for external cmd.exe instance.

👉 Considerably more information here: https://stackoverflow.com/q/74966735/54680

The issue doesn't reproduce for all environment variables. I evaluated 86 different variables with Visual Studio Code (integrated terminal), PowerShell, and Command Prompt. There was something about "DEBUG" (and oddly enough, "DEEBUG"), however.

Visual Studio Code, and nearly all of its child processes, have the `DEBUG` variable in their environment. The only exception is the `--type=ptyHost` child process; it does not have the variable in its environment.

![image](https://user-images.githubusercontent.com/815158/210123556-ad12a24b-136d-47c6-9e5e-9c2552cfbb4a.png)

**Comment by Tyriar** [comment]
Cannot reproduce this:

![image](https://github.com/microsoft/vscode/assets/2193314/501de8cb-911c-42e1-ad5b-9bff61b94390)

When changing environment variables something you need to make sure you do is to close VS Code entirely until we close out this issue https://github.com/microsoft/vscode/issues/47816
