### ISSUE TITLE
Tabs are forced to be folded in 2 spaces width?

### ISSUE THREAD

**Issue by BandageWorm** [Microsoft/vscode#17030]
- VSCode Version:1.7.2
- OS Version:windows10 1607

My tab only take two spaces even though the tabsize setting is: 
```
"editor.tabSize": 4,
"editor.insertSpaces": true,
```
, and it seems that every space in tab is half width than usual.

After I added `"editor.renderWhitespace": "all",` in setting then it looks like this:
![qq](https://cloud.githubusercontent.com/assets/20052211/21078502/cd21da50-bfac-11e6-9050-17cd4efa71a8.png)
tabs are folded in half. And it happended even in plain text. How can I fix it?

**Comment by alexandrudima** [comment]
@BandageWorm I am having a hard time to reproduce this issue.

![image](https://cloud.githubusercontent.com/assets/5047891/23474792/40cfe4dc-feb5-11e6-980d-c75d02332e4f.png)

Could you please share with us all your settings (especially relevant would be font family, font size, ligatures, etc.)

**Comment by BandageWorm** [comment]
Well, it turned out that this issue happened when I used a modified consolas font combined with chinese character fonts, when I used original consolas, it works fine.
