### ISSUE TITLE
VSCode [Insider] crash on project close

### ISSUE THREAD

**Issue by dalisoft** [microsoft/vscode#170303]
Type: <b>Bug</b>

On VSCode Insider closing project crashing while using macOS Native tabs. Somtimes on first tab closing causes crash

VS Code version: Code - Insiders 1.75.0-insider (6ed4d436a9b6ae131732f4e2a723868231f4473a, 2022-12-23T05:22:56.472Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No
Connection to 'ssh-remote+ubuntu-vm' could not be established
Remote OS version: Linux x64 5.15.49-linuxkit

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|14, 6, 4|
|Memory (System)|64.00GB (30.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

Connection to 'ssh-remote+ubuntu-vm' could not be established

|Item|Value|
|---|---|
|Remote|Dev Container: Start project in devcontainer @ desktop-linux|
|OS|Linux x64 5.15.49-linuxkit|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (2 x 3599)|
|Memory (System)|3.84GB (2.88GB free)|
|VM|0%|
</details><details><summary>Extensions (79)</summary>

Extension|Author (truncated)|Version
---|---|---
svgo|100|3.0.0
vscode-nginx-conf|ahm|0.1.3
vscode-fish|bma|1.0.31
vscode-intelephense-client|bme|1.8.2
npm-intellisense|chr|1.4.4
vscode-css-modules|cli|0.4.2
codeque|Cod|0.18.2
gitignore|cod|0.9.0
vscode-markdownlint|Dav|0.48.1
vscode-eslint|dba|2.2.6
vscode-deno|den|3.15.0
gitlens|eam|13.2.0
EditorConfig|Edi|0.16.4
LogFileHighlighter|emi|2.16.0
prettier-vscode|esb|9.10.3
code-runner|for|0.11.8
platformio|for|0.3.0
shell-format|fox|7.2.2
vscode-google-translate|fun|1.4.13
vscode-pull-request-github|Git|0.56.0
go|gol|0.37.0
todo-tree|Gru|0.0.220
terraform|has|2.25.2
vscode-htmlhint|HTM|1.0.4
output-colorizer|IBM|0.1.2
r-pack|Iku|0.0.2
reason-vscode|jar|1.7.13
svg|joc|1.4.26
vscode-phpfmt|kok|1.0.31
bash-ide-vscode|mad|1.23.0
rainbow-csv|mec|3.5.0
vscode-language-babel|mgm|0.0.36
git-graph|mhu|1.30.0
dotenv|mik|1.0.1
vscode-apache|mrm|1.2.0
vscode-scss|mrm|0.10.0
vscode-docker|ms-|1.23.3
gather|ms-|2022.3.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
remote-containers|ms-|0.266.1
remote-ssh|ms-|0.94.0
remote-ssh-edit|ms-|0.84.0
cpptools|ms-|1.13.8
remote-explorer|ms-|0.0.3
sftp|Nat|1.16.1
color-highlight|nau|2.5.0
bun|Pan|0.0.4
proto|pet|0.0.2
material-icon-theme|PKi|4.23.1
polacode|pnp|0.3.4
gitlink|qez|1.2.4
inline-sql-syntax|quf|2.16.0
quicktype|qui|12.0.46
nginx-formatter|ray|0.0.13
java|red|1.13.0
vscode-commons|red|0.0.6
vscode-yaml|red|1.10.1
r|REd|2.7.0
shellman|Rem|5.6.0
postcss|ric|2.0.0
rome|rom|0.20.0
rust-analyzer|rus|0.3.1334
gitconfig|sid|2.0.1
code-spell-checker|str|2.12.0
code-spell-checker-russian|str|2.0.6
vscode-styled-components|sty|1.7.5
vscode-stylelint|sty|1.2.3
hlsltools|Tim|1.1.303
vscodeintellicode|Vis|1.2.29
vscode-nginx|wil|0.7.2
viml|Xad|2.1.2
vscode-open-in-github|ziy|1.3.6

</details>

https://user-images.githubusercontent.com/3511344/210106820-34e81393-b081-45ad-8f56-1d9b6665fe53.mp4

**Comment by deepak1556** [comment]
Merging to https://github.com/microsoft/vscode/issues/167936

**Comment by deepak1556** [comment]
@dalisoft do you have a reliable repro case for this issue ? Based on your recording, crash seems to trigger when closing a remote window tab that is still loading and focusing to next tab. Does it happen without using a remote connection window ?

**Comment by dalisoft** [comment]
@deepak1556 It is not related to remote, just closing first window in native tab most of case crashes VSCode Insiders

**Comment by deepak1556** [comment]
I tried the similar steps from your screen recording but haven't been successful in reproing the issue either on arm64 (Ventura 13.2 beta) or x64 (Ventura 13.1) macOS. If you manage to create some reliable repro steps please do share them, thanks!

**Comment by dalisoft** [comment]
@deepak1556 Sorry for delays. Today i get some free time for reproduce bug. Here below case of self closing. Closing first or last tab causes VSCode crash.

https://user-images.githubusercontent.com/3511344/215356122-5641678d-04b6-4f06-95c4-2e181a6864b1.mp4



<img width="268" alt="image" src="https://user-images.githubusercontent.com/3511344/215356171-922cfcc6-6264-4bc6-bd14-fb03417e50b8.png">

**Comment by deepak1556** [comment]
Can you also share your `settings.json`, thanks!

**Comment by dalisoft** [comment]
@deepak1556 It is here https://github.com/dalisoft/vscode-config/blob/master/settings.config.json
