### ISSUE TITLE
Create a New Project

### ISSUE THREAD

**Issue by rm-minus-r-star** [microsoft/vscode#170323]
Documentation indicates that it was once possible to create a new project under the File menu option. It would seriously enhance the usability of VS if this were re-enabled. As it stands I can only use it for projects I've created in the past. 

Ability to create a new project via intuitive and obvious menu options.
![vscode_daft_new_project](https://user-images.githubusercontent.com/40910389/210120469-5a85b517-e6d1-4f8a-b106-c3d802428940.png)

**Comment by gjsjohnmurray** [comment]
> Documentation indicates that it was once possible to create a new project under the File menu option.

Please provide a reference.

**Comment by rm-minus-r-star** [comment]
https://learn.microsoft.com/en-us/visualstudio/ide/create-new-project?view=vs-2022

⁣Get BlueMail for Android ​

**Comment by gjsjohnmurray** [comment]
Visual Studio is not the same product as Visual Studio Code.

**Comment by rm-minus-r-star** [comment]
Ohhh sorry. Not sure how I would have confused them.

⁣Get BlueMail for Android ​
