### ISSUE TITLE
Extension disappears from the installed extensions section after reload/

### ISSUE THREAD

**Issue by abhishek14k** [microsoft/vscode#170337]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.74.2 (user setup)
- OS Version: Windows_NT x64 10.0.22621
- Sandboxed: No
- Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
- Date: 2022-12-20T10:29:14.590Z (1 wk ago)

Steps to Reproduce:

1. Install VS Code 1.74.2
2. Open VS Code
3. Navigate to Extensions(Ctrl + Shift + X)
4. Search for extension "Prettier - Code formatter" (v9.10.3)
5. Install the extension.
6. Click on button "Reload Required".
7. "Prettier - Code formatter" disappears from the installed extensions section.

Other extensions having the same issue as above: Simple React Snippets(v1.2.7).

![BUG_VSCode_Extension_Prettier_2022-12-31 232218](https://user-images.githubusercontent.com/37078073/210152067-af8067f7-28c9-44e0-b66b-a76a7060020a.png)

![BUG_VSCode_Extension_Simple_React_Snippets_2022-12-31 232218](https://user-images.githubusercontent.com/37078073/210152191-9cc53abc-340c-4e3a-ae8b-a993391fd40d.png)

**Comment by abhishek14k** [comment]
Hi Sandy,

Please find the attached log file of the issue.

Regards,
Ahishek
[Extension_Issue.txt](https://github.com/microsoft/vscode/files/10367764/Extension_Issue.txt)

**Comment by simjega** [comment]
I was in the same boat but figured out what went wrong for me. 

I had recently renamed my home directory and all the paths in my `extensions.js` file were using the old home directory name. A simple find and replace fixed everything.

**Comment by sandy081** [comment]
If it is related to the paths in `extensions.json` file, this is fixed in the next release.
