### ISSUE TITLE
Extension completion item provider is not called after typing character dot in javascript

### ISSUE THREAD

**Issue by hangxingliu** [Microsoft/vscode#17037]
- VSCode Version: 1.7.2 (7ba55c58, 2016-11-21T22:06:37.428Z)
- OS Version: Windows 7 6.1.7601

Steps to Reproduce:

1. I wrote a javascript variable fields completion provider extension
  (such as,  I write some fields name into a special file. And I can get these fields name after I typing character dot in the javascript file.)
2. Then I got a trouble. Because my provider function `provideCompletionItems` is not called after typing character dot. And It is not called even I type other characters after the dot.
3. But it could be called and return items when I type shortcut `alt+/`(editor.action.triggerSuggest)  
4. Is this a bug, Or I use a wrong way to achieve this function.

Codes:

![code1](https://cloud.githubusercontent.com/assets/4303130/21079054/e3742390-bfbf-11e6-8325-2447a4cd7526.png)

![code2](https://cloud.githubusercontent.com/assets/4303130/21079062/4428f670-bfc0-11e6-9d6e-19b7e3657f88.png)

**Comment by jrieken** [comment]
When calling [`registerCompletionItemProvider`](https://github.com/Microsoft/vscode/blob/master/src/vs/vscode.d.ts#L4087) you must provide a list of trigger characters, like so

```js
registerCompletionItemProvider(langSelector, provider, '.')
```

**Comment by hangxingliu** [comment]
Thanks @jrieken
(P.s. Sorry, I don't read API document detailedly :joy: )
