### ISSUE TITLE
Selecting highlights merge the next nearby same words

### ISSUE THREAD

**Issue by ccloli** [Microsoft/vscode#17038]
- VSCode Version: Code 1.7.2 (7ba55c5860b152d999dda59393ca3ebeb1b5c85f, 2016-11-21T22:06:37.428Z)
- OS Version: Windows_NT ia32 6.3.9600
- Extensions:

|Extension|Author|Version|
|---|---|---|
|jshint|dbaeumer|0.10.15|
|githistory|donjayamanne|0.1.2|
|CppSnippets|hars|0.0.5|
|JSDocTagComplete|HookyQR|0.0.2|
|docthis|joelday|0.3.5|
|sublime-keybindings|ms-vscode|1.8.0|

---

Steps to Reproduce:

1. Input the following text in VS Code:
```
foofoofoofoo
foo
```
2. Now I want to change all the `foo` to `bar`, then I select the second line `foo`
3. Press `Ctrl + F2`, the first line is selected like `foofoo` `foofoo`, not `foo` `foo` `foo` `foo`
4. Input `bar`, the first line become to `barbar`, not `barbarbarbar`
![vs1](https://cloud.githubusercontent.com/assets/8115912/21079036/64e2c504-bfbf-11e6-85fb-de09dc5fe7fa.gif)
The same steps in Sublime Text (except using `Alt + F3` to select highlights)
![st1](https://cloud.githubusercontent.com/assets/8115912/21079049/c062ba10-bfbf-11e6-84c4-b8504b0142dd.gif)

Another example, some text is looking like this:
```
aaaaaaaa
aaaaaa
aa
```
Then I select an `a` at any position, then press `Ctrl + F2` repeatly, the selecting part looks randomly, then input `b`, the length of each line is not the same as before.
![vs2](https://cloud.githubusercontent.com/assets/8115912/21079068/88733412-bfc0-11e6-98a6-2402f295500e.gif)
The same steps in Sublime Text
![st2](https://cloud.githubusercontent.com/assets/8115912/21079073/b3aaf944-bfc0-11e6-928e-611244472883.gif)

**Comment by alexandrudima** [comment]
Fixed with the fix for #6661
