### ISSUE TITLE
Accessibility issue when navigating the vscode terminal

### ISSUE THREAD

**Issue by ashleygrobler04** [microsoft/vscode#170384]
Hi there. I am using NVDA as my screen reader when using vscode. When I try to open the terminal and navigate it's output with CTRL+arrows, all I here is "list item 1 of 13" "list item 2 of 13" and so on. I've tried running it with all extensions disabled, but no difference. I am using vscode version 1.74.2.
I hope this helps. To reproduce this issue, do the following:
1. Install NVDA from https://nvaccess.org
2.  Enable NVDA after instalation if not enabled.
3. Open vscode and open your terminal.
4. Use CTRL+arrows to navigate your terminal and listen to what is reported.
5. You could also running some command-line file that has output if you want some output to play with so that you can listen to what it has to say.

**Comment by sightlesswolf** [comment]
I believe those list items you are seeing are blank lines.

**Comment by ashleygrobler04** [comment]
In the case where I had blank lines as output, I could understand. However when running something that produces output in the command prompt the results aren’t the same.Thanks and best regards,Ashley Grobler   Sent from Mail for Windows From: sightlesswolfSent: Monday, January 2, 2023 10:15To: microsoft/vscodeCc: ashleygrobler04; AuthorSubject: Re: [microsoft/vscode] Accessibility issue when navigating the vscode terminal (Issue #170384) I believe those list items you are seeing are blank lines.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
