### ISSUE TITLE
Syntax highlighting in SQL extension

### ISSUE THREAD

**Issue by bruce3** [Microsoft/vscode#17039]
- VSCode Version:
Commit 7ba55c5860b152d999dda59393ca3ebeb1b5c85f
Date 2016-11-21T22:14:18.217Z
Shell 1.3.8
Renderer 52.0.2743.82
Node 6.5.0
- OS Version:
Ubuntu 16.04

Steps to Reproduce:

Copy the following text to vscode and set language mode = SQL.
Then cast your eyes down the list for some examples.

-- Control Flow
-- highlighted
IF
BEGIN
END
THROW
TRY
CATCH
-- not highlighted
ELSE
RETURN
WAITFOR
WHILE
GOTO

EXEC          -- highlighted
EXECUTE   -- not highlighted
COLLATE    -- not highlighted

-- DDL
ON DELETE CASCADE
ON UPDATE CASCADE,		--  second CASCADE not highlighted
DEFAULT                                 -- not highlighted
NOT NULL

--	Statements
BEGIN TRANSACTION
BEGIN DISTRIBUTED TRANSACTION    -- DISTRIBUTED not highlighted
SAVE TRANSACTION				  -- SAVE not highlighted			
COMMIT TRANSACTION
COMMIT WORK
ROLLBACK TRANSACTION
ROLLBACK WORK

--	Functions
CONVERT
CAST					--	CAST is blue and CONVERT is yellow?

-- Date and time functions
CURRENT_TIMESTAMP     -- CURRENT_TIMESTAMP is yellow, @@DATEFIRST blue others nothing?
DATEDIFF
@@DATEFIRST
DATENAME
SYSDATETIME

**Comment by aeschli** [comment]
This issue was moved to textmate/sql.tmbundle#21
