### ISSUE TITLE
can't type in terminal 

### ISSUE THREAD

**Issue by karma-cs50** [microsoft/vscode#170308]
ADD ISSUE DESCRIPTION HERE

Version: 1.74.2
Commit: e8a3071ea4344d9d48ef8a4df2c097372b0c5161
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15
Embedder: codespaces

**Comment by karma-cs50** [comment]
can't type in terminal

**Comment by meganrogge** [comment]
disable `terminal.integrated.gpuAccleration` as it's not supported on certain versions of safari

/duplicate #165416
