### ISSUE TITLE
Support coloring a subset of the matched brackets

### ISSUE THREAD

**Issue by hediet** [microsoft/vscode#170497]
This issue changes the behavior when both brackets and colorizedBracketPairs are configured, for example through this configuration:
```json
"[plaintext]": {
    "editor.language.brackets": [
      ["{", "}"],
      ["(", ")"],
      ["[", "]"]
    ],
    "editor.language.colorizedBracketPairs": [
      ["{", "}"],
      ["<", ">"]
    ]
  },
```

In this case, the four bracket pairs `{}`, `()`, `[]` and `<>` should be matched.
However, only the pairs `{}` and `<>` should get highlighted.

![Code_-_OSS_R4wyxSgWhT](https://user-images.githubusercontent.com/2931520/215427587-0144fcaf-6087-46f6-b612-488a813914d1.gif)

In particular, this restores the bracket matching behavior for plain text files before colorization was introduced.

**Comment by RedCMD** [comment]
I wonder if there is any use to disable 'match' highlighting on brackets that are only listed in `editor.language.colorizedBracketPairs`, but not `editor.language.brackets`
for example, the angle brackets in the gif would be coloured but wont have the squares boxes around them

**Comment by hediet** [comment]
> I wonder if there is any use to disable 'match' highlighting on brackets that are only listed in

What would be your use-case?

**Comment by RedCMD** [comment]
I don't have any atm
was just an idea that possibly someone else might want/ need

**Comment by RedCMD** [comment]
Not sure if this is a bug or feature (I would incline towards feature)
if a bracket pair is listed under `"brackets"` but not `"colorizedBracketPairs"`
it can still be marked as invalid if it is not matching in a document

![image](https://user-images.githubusercontent.com/33529441/222704608-c71ca625-c1c0-4453-a114-a8e686f03449.png)
![image](https://user-images.githubusercontent.com/33529441/222704726-0a9f82be-9941-4a3e-bc51-1b5ab2093b43.png)
`[` is marked as invalid, even tho it is not under `"colorizedBracketPairs"`

**Comment by hediet** [comment]
This was a compromise, as for unclosed/unopened brackets we don't really know if it is colorized or not, as that depends on the missing opening/closing bracket (only complete pairs are colorized and different pairs can share brackets).
However, I'm just considering a change that brackets that are not colorized in any pair don't get red when they are unopened/unclosed. This fixes https://stackoverflow.com/questions/75610880/why-are-some-left-and-right-angle-brackets-colored-red-in-vscode and others for now.
