### ISSUE TITLE
VS Code webview API should let extensions set title and/or aria-label on `iframe`. Ensures <iframe> and <frame> elements have an accessible name (frame-title - https://accessibilityinsights.io/info-examples/web/frame-title).

### ISSUE THREAD

**Issue by alexr00** [microsoft/vscode#170440]
## Repro Steps:
1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix
2. Run the webview extension sample https://github.com/microsoft/vscode-extension-samples/tree/main/webview-sample
3. Run the command "Cat Coding: Start a Cat Coding Session" to open a webview.
4. Inspect the `iframe`.

## Issue:
Ensures <iframe> and <frame> elements have an accessible name (frame-title - https://accessibilityinsights.io/info-examples/web/frame-title)

Element path: .webview

## How to fix:
Fix any of the following:
  Element has no title attribute
  aria-label attribute does not exist or is empty
  aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
  Element's default semantics were not overridden with role="none" or role="presentation"

Environment: Microsoft Edge version 107.0.1418.56

====

This accessibility issue was found using Accessibility Insights for Web 2.35.0 (axe-core 4.4.1), a tool that helps find and fix accessibility issues. Get more information & download this tool at http://aka.ms/AccessibilityInsights.

## User Impact:
Screen reader users will not get to hear the correct announcement for the control.

**Comment by alexr00** [comment]
Discovered by accessibility testing team here: https://github.com/microsoft/vscode-pull-request-github/issues/4234

**Comment by fsteffi** [comment]
GitHubTags:#A11ySev3;#A11yTCS;#A11yMAS;#DesktopWeb;#Visual Studio Code Client;#WCAG4.1.2;#DesktopApp;#BM-VisualStudioCode-Win32-Nov2021;

**Comment by mjbvz** [comment]
Webviews consist of two iframes: an outer one that VS Code controls and an inner one that extensions control. The inner iframe is what users understand as the actual webview

Extensions can already set the `<title>` of the inner iframe with the html they generate (however not all of our built-in extensions do this)

The outer iframe is an implementation detail. Ideally screen readers should ignore this and only see the inner iframe. We even removed the `title` from this outer iframe to prevent screen readers from announcing it: #141903 (this is likely what caused this bug to be opened)

---

I don't think we should add the title back to the outer iframe as this may result in two titles being read when inside of a webview. @isidorn @alexr00 Any other ideas on addressing this?

**Comment by alexr00** [comment]
> Extensions can already set the <title> of the inner iframe with the html they generate (however not all of our built-in extensions do this)

Setting the title on the inner iframe may be enough. I don't see a way to get to the iframe though. @mjbvz can you point me to an example of how to do this?

**Comment by mjbvz** [comment]
@alexr00 This would be the the html that extensions create for the webview. They can fix this by adding a `<title>` but I can also look into adding code that sets the title for them (can't think of a good use case for having the webview `<title>` element be different from that title we show in VS Code)

**Comment by alexr00** [comment]
@mjbvz GitHub Pull Requests already does this:

https://github.com/microsoft/vscode-pull-request-github/blob/72ffe2955c4c6ff8669cab762803ff08e58b1973/src/github/createPRViewProvider.ts#L572

But that doesn't seem to set the `iframe`'s `title` property.
