### ISSUE TITLE
Self written Module NotFoundError

### ISSUE THREAD

**Issue by starzar** [microsoft/vscode#170438]
Type: <b>Bug</b>

1.This is a followup to the previously unsolved issue at https://github.com/microsoft/vscode-python/issues/20214#issuecomment-1319675492.
2.Steps provided in the solution by @karrtikr have been followed but  the error still persists.
3.All steps had already been implemented but not sure why its not visible . @karrtikr please refer the attached image;  

![py1](https://user-images.githubusercontent.com/38550930/210321847-4b63a4b8-f553-4b6f-a702-26c01164465f.jpg)
4. Output (Python):
`LSP Notebooks experiment is disabled -- Jupyter disabled or not installed
LSP Notebooks interactive window support is disabled -- not in LSP Notebooks experiment
Python interpreter path: .\.venv\Scripts\python.exe
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Starting Pylance language server.
DAP Server launched with command: h:\TwsPython\.venv\Scripts\python.exe c:\Users\User_0\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\adapter
Send text to terminal: & h:/TwsPython/.venv/Scripts/Activate.ps1
Send text to terminal:  & 'h:\TwsPython\.venv\Scripts\python.exe' 'c:\Users\User_0\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\lib\python\debugpy\adapter/../..\debugpy\launcher' '51332' '--' 'h:\TwsPython\TwsApiSamples\Python\Testbed\ContractSamples.py' 
> conda info --json
> ~\AppData\Local\Programs\Python\Python39\python.exe ~\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\interpreterInfo.py
> .\.venv\Scripts\python.exe ~\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\get_output_via_markers.py ~\.vscode\extensions\ms-python.python-2022.20.1\pythonFiles\interpreterInfo.py`

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.95GB (7.10GB free)|
|Process Argv|--crash-reporter-id 55955963-e60a-4959-b321-3e91ce3cbfb4|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
live-server|ms-|0.4.4

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
3biah626:30602489
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by karrtikr** [comment]
Please use the `Python: Report Issue` command to file this issue instead, we require your settings as asked here https://github.com/microsoft/vscode-python/issues/20440#issuecomment-1367759475.
