### ISSUE TITLE
VS Code not recognizing Node.js on my computer

### ISSUE THREAD

**Issue by Michaelar1** [microsoft/vscode#170420]
Type: <b>Bug</b>

I am running VS Code 1.74 on a Windows 10 OS. I also have installed Node.js v18.12.1. I attempted to run a basic "Hello World" JS program in VS Code using both the cmd terminal and the powershell terminal. Expected results would have been to see "Hello, world" printed on the terminal. However, I got the following error message: " { code: 'MODULE_NOT_FOUND', requireStack: [] } Node.js v18.12.1." 

It appears that VS Code isn't recognizing Node.js. I have looked on your site for solutions, however there appear to be none.  Any assistance that could be provided in this matter would be appreciated.

Thank you,

Michaela Rehm

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.90GB (1.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-node-debug-process-picker|apr|1.0.0
npm-intellisense|chr|1.4.4
path-intellisense|chr|2.8.4
vscode-eslint|dba|2.2.6
vscode-pull-request-github|Git|0.56.0
vscode-versionlens|pfl|1.0.10
node-pack|Swe|0.1.16
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29

</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1cf:30587006
3biah626:30602489
iaj6b796:30613358
89544117:30613380
fim-prod:30623723

```

</details>

**Comment by roblourens** [comment]
This would be an issue with your system/configuration. If you are just running `node xyz.js` in the terminal, vscode has no special handling here.
