### ISSUE TITLE
Editor hang/poor performance with a large number of tests in a file

### ISSUE THREAD

**Issue by DanTup** [microsoft/vscode#170493]
I'm investigating some performance issues in Dart when you have a large number of tests in a single file. Many of these issues are in the Dart extension, but while working on it I've been seeing a few bad hands in the editor that I think may be a VS Code issue. It seems to happen during `syncDecorations` which I suspect are related to the test icons in the gutter.

The test file I'm using has approximately 2,500 tests in the file.

![Screenshot 2023-01-03 at 15 12 51](https://user-images.githubusercontent.com/1078012/210385779-86717568-5b99-44ed-9175-25b9cea28790.png)

![Screenshot 2023-01-03 at 15 17 03](https://user-images.githubusercontent.com/1078012/210386146-d24b766f-bcd7-4db7-bfbb-cad77624bd03.png)

Here's an export of the profile from the dev tools:

[slow_decorations.json.zip](https://github.com/microsoft/vscode/files/10337692/slow_decorations.json.zip)

Note: I can't give precise repro steps using the Dart extension right now because I'm still making performance improvements (if you try to reproduce this with the published version of the extension you'll see significant performance issues in the extension that I'm working on), but if this profile isn't helpful on its own and you need more, I may be in a position to publish a pre-release version with some of my fixes soon.

@connor4312 FYI - I don't know if this is general decorations code or test-specific, but I think the anonymous function showing up a lot in the profile relates to this code here:

https://github.com/microsoft/vscode/blob/2377c7a4c5f81d131567d9b35ba8d32a9f070649/src/vs/workbench/contrib/testing/browser/testingDecorations.ts#L199

**Comment by connor4312** [comment]
Repro steps:

1. Use the test provider sample
2. 
  ```
  node -p "new Array(2500).fill(0).map((a, i) => \`1 + \${i} = \${i + 1}\`).join('\n')" > sample/big.md
  ````
3. F5, open big.md, and click on a decoration

**Comment by DanTup** [comment]
@connor4312 seems _much_ better now, thank you!
