### ISSUE TITLE
VSCode for Mac OS 10.7.5

### ISSUE THREAD

**Issue by con-ssc** [Microsoft/vscode#17044]
Is it possible to have VSCode for Mac OS 10.7.5? At the download page it says 10.X but that is definitely wrong.
What are the OS restrictions and why?

**Comment by Nikki1993** [comment]
I think you misunderstood what X means. In traditional case, 10.X means it supports any version that belongs to major 10th release be it 10.7.5 or 10.12.1 (latest) Macos release.

**Comment by con-ssc** [comment]
@Nikki1993 Exactly what I said, it does not support any 10.X version. You seem to need OS X Yosemite. So it is more like the latin X so you need 10.10 at least

**Comment by joaomoreno** [comment]
What happens when you open it in 10.7.5?

**Comment by Nikki1993** [comment]
@con-ssc  That's bizarre, try launching code via terminal (Open terminal and type `code`) like this and paste any errors that appear.

**Comment by mrmlnc** [comment]
> Only 64bit binaries are provided for macOS, and the minimum macOS version supported is macOS **10.9**.
>
> http://electron.atom.io/docs/tutorial/supported-platforms/#macos

Isn't this limitation of Electron?

**Comment by joaomoreno** [comment]
@waderyan @bgashler1 @gregvanl We should update the download page to say >=10.9, not 10.X.

**Comment by con-ssc** [comment]
@joaomoreno Or, if possible, make a version that runs on 10.X ;)

**Comment by con-ssc** [comment]
@Nikki1993 You cannot install Code at all so I cannot do that.

**Comment by Nikki1993** [comment]
@con-ssc electron is not managed by VS Code team. Report this upstream here https://github.com/electron/electron/issues however I don't see the support being added to outdated version of macOS as there are probable several technical reasons for support 10.9+

Any particular reason you are still staying on older version of macOS?

**Comment by con-ssc** [comment]
@Nikki1993 Hardware limitation, I cannot upgrade to any other mac os version.

**Comment by Nikki1993** [comment]
Well your best bet is to see if Electron team can add support to older versions.

**Comment by waderyan** [comment]
@joaomoreno created a docs issue to track better documentation on download page - https://github.com/Microsoft/vscode-docs/issues/711

**Comment by joaomoreno** [comment]
Moved to Microsoft/vscode-docs#711.
