### ISSUE TITLE
Dialogs: provide a simpler internal API that avoids having to use button index magic

### ISSUE THREAD

**Issue by rehmsen** [microsoft/vscode#170492]
When providing a `cancelId`, VSCode on Linux/Mac reverses the button order and moves the cancel button in the second right most position: https://github.com/microsoft/vscode/blob/f078e6db483250957314c56c3b12e23dae03d351/src/vs/base/browser/ui/dialog/dialog.ts#L489
This means that when you have e.g. three buttons, Cancel will be between the other two.

I could not find more documentation on it, so I am not sure what exactly the intent is. According [this website](https://uxplanet.org/primary-secondary-action-buttons-c16df9b36150#11bf) Windows prefers Cancel to be the right most button, and MacOS prefers an action button to be right most, and Cancel to the left of that. What is not completely clear from this guideline is what should happen if there are three buttons (say primary action, secondary action, cancel). I would have expected cancel to be either on the far left or far right, but not between the primary and secondary action. The first example for VSCode's [webview button guidelines](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/button/README.md) also seems to suggest that Cancel is not between "Publish" and "Create" but, in this case, to the left.

More generally, reordering (only) when `cancelId` is provided is a surprising side effect, and it should probably be documented that input order is expected to be Windows-style (Cancel last).

I would be happy to send a PR with some documentation around this, and would also love to send a change to avoid having the cancel button in the middle between multiple action buttons, but I first wanted to better understand what the intention in change https://github.com/microsoft/vscode/commit/3074fd588d1a01ae552243a1c4359b4cf0d5227d by @lramos15 was.

Thanks for your time!

**Comment by rehmsen** [comment]
Thanks for the response Steven!

I am from Google and we are using mainly `IDialogService.show`. I found these doc strings: https://github.com/microsoft/vscode/blob/f078e6db483250957314c56c3b12e23dae03d351/src/vs/platform/dialogs/common/dialogs.ts#L273-L285

They do mention that by convention the cancel button should be passed in last. They do not mention the side-effect of `cancelId` to reverse the buttons on Mac/Linux, and to move the button with the `cancelId` to the second last position. I could send a PR documenting that, but I think it would be good to first understand
1) Why we only reverse the button ordering when a `cancelId` is provided - this sounds like the right thing to do independent of the `cancelId`, to comply to the UX expectations on the respective platforms.
2) Why we move the cancel button into the second last position. I find it a bid odd to have [secondary] [cancel] [primary], with cancel in the middle. But given there is code that does this, maybe this is intended, and then it would help to understand why. This is the part that also seems to not be aligned with the screenshots from the [webview button guidelines](https://github.com/microsoft/vscode-webview-ui-toolkit/blob/main/src/button/README.md). 

I am happy to help by sending the PRs, just want to make sure we are aligned on what the behavior should be and why.

**Comment by rehmsen** [comment]
Hi Steven,

as it is often easier to discuss a change with a proposal, I have send a PR for a first step in the direction of making this behavior less unexpected: Adding a new option which controls the reordering behavior instead of making that a side-effect of `cancelId`. As I am a new contributor to this repo, it seems I need a maintainers approval to run checks. I did not find unit tests for this file, so I did not update any, let me know if you would like me to add some (which would probably become a larger change as my change is in a private function that cannot be tested in full isolation). 

If am planning to send a second PR for fixing  
> [fileDialogService.ts:235](https://github.com/microsoft/vscode/blob/d8568bb19e5acb54253afb2cb48123785db2f8d9/src/vs/workbench/services/dialogs/browser/fileDialogService.ts#L235) uses cancelId=-1 to indicate there is no cancel button - which has the probably undesired side-effect of moving the last button ("Open files" or "Learn more") to the second last position because of how slice works with negative indices. 

If I get these two PRs merged, I would like to work with you / your UX person to reconsider moving the cancel button second last - but let's first see if we can agree that this more explicit reordering is an improvement.

Thank you for your time, and please let me know if there is anything I can improve to simplify the merging.

Cheers
Ole

**Comment by rehmsen** [comment]
#171595 is a PR to fix the apparently undesired button reordering in the file dialog.

**Comment by bpasero** [comment]
I think the original motivation to move `Cancel` between 2 primary actions was to somewhat emulate macOS when there are 2 buttons and 1 cancel button:

<img width="698" alt="image" src="https://user-images.githubusercontent.com/900690/213152964-163f9fae-3887-416e-af2c-b6de46188698.png">

Electron does not provide us with an API to do this and besides, with more recent macOS versions buttons are also ordered from top to bottom (interestingly not in this case of TextEdit).

Interestingly enough, Xcode is putting "Cancel" all the way to the left:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/900690/213153966-b97f617b-1042-4297-a051-6b28c004d988.png">

Sometimes, but sometimes not:

<img width="663" alt="image" src="https://user-images.githubusercontent.com/900690/213154085-fb6ad114-6522-405f-b9fb-506d5ee7545f.png">

macOS HIG indicate:

```
Place buttons where people expect. In general, place the button people are most likely to choose on the trailing side in a row of buttons or at the top in a stack of buttons. Always place the default button on the trailing side of a row or at the top of a stack. Cancel buttons are typically on the leading side of a row or at the bottom of a stack.
```

From: https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts/

Before making any changes here on how to reorder we really need 100% understanding what the right thing to do is, based on the OS.

**Comment by rehmsen** [comment]
Thanks for providing context Benjamin. From what you write, it sounds like VSCode is currently not in alignment with MacOS standards at least (as they suggest to typically place "Cancel" at the leading side). However, the two PRs I send so far do not touch the position of the cancel button, only make it more explicit when to do the reordering. So these should be fine (I will respond to your comment on one of them there).

**Comment by bpasero** [comment]
Just to clarify: when I look at a very typical dialog, "Cancel" appears at the end:

![image](https://user-images.githubusercontent.com/900690/213171822-db0df50c-3dba-4b42-9de4-722db09fa6d3.png)

So I am not sure in what case we are inconsistent with the HIG.

**Comment by rehmsen** [comment]
For example when you open a file from an untrusted workspace, you get

![Dialog with three buttons and cancel in the middle](https://user-images.githubusercontent.com/29040/213650129-8cb77f92-23b2-4abb-a28e-e2fa373a62e8.png)

Notice how cancel is in the middle, while the HIG you quote says:
> Cancel buttons are typically on the leading side of a row or at the bottom of a stack.

**Comment by bpasero** [comment]
Yes, sorry, I was not carefully looking. There seems to be a major flaw in how native dialogs vs. custom dialogs are handled with regards to ordering when `cancelId` is set. To summarise:

**Native Dialogs:** 

> the cancel button should always be to the left of the primary action
> if we see more than 2 buttons, move the cancel one to the left of the primary

This seems wrong on macOS at least (not sure about Linux) given the HIG we found. So I would suggest to change this according to HIG (also on Linux if we can confirm). 

https://github.com/microsoft/vscode/blob/3fd65671022d863431871a4304a714fc20ca7bab/src/vs/workbench/electron-sandbox/parts/dialogs/dialogHandler.ts#L133-L143

**Custom Dialogs:** 

I do not fully understand the code, it seems wrong:
* why are we not reversing the buttons on Linux and macOS?
* why do we only reverse if `cancelId` is provided

https://github.com/microsoft/vscode/blob/3fd65671022d863431871a4304a714fc20ca7bab/src/vs/base/browser/ui/dialog/dialog.ts#L490-L497

I think if we want to fix this, we should do it consistently for native and custom dialogs so that they appear the same 👍

**Comment by rehmsen** [comment]
> * why are we not reversing the buttons on Linux and macOS?
> * why do we only reverse if cancelId is provided

My PR #171592 fixes this, by providing a separate parameter which controls this and defaults to reordering. The problem with the parameter is I guess that native does not support it, so they would do reordering even if its turned off, right? Would you want me to adjust my PR to remove the parameter again and always reorder on Mac/Linux, independent of cancelId?

**Comment by bpasero** [comment]
I have also pinged @daviddossett from our UX team to comment. 

Here is my thinking:

**General**
This should "just work" without an option to enable ordering or not in the API. By default we assume that "Cancel" button is the last in the array of buttons that is passed to us. I do not think anyone sets the "Cancel" button to be first or middle of an array in our code today.

If an explicit `cancelId` is provided that is `>=0`, we take that as the assumed cancel button.

**Windows**
Take buttons in the order as they are passed in. Move the cancel button to be the last if `cancelId >= 0`.

**macOS**
Take buttons as they are passed in native (where reversing is done for us), but reverse the order for custom. Move the cancel button to be first if `cancelId >= 0`.

**Linux**
Reverse the buttons for both native and custom. **TBD** figure out if "Cancel" buttons are on the far left or middle.
See here for a native dialog for text edit application on Ubuntu where interestingly the "Cancel" button is in the middle:
<img width="685" alt="image" src="https://user-images.githubusercontent.com/900690/213671680-628e0758-4fe9-4c18-912c-bfd68a0f11af.png">

**Comment by bpasero** [comment]
One thing I wonder is if there would ever be a scenario where we would want a dialog with 3 buttons where the cancel choice should be in-between. This is for dialogs that have no "Cancel" button specifically but just 3 choices. 

Doing some experiments with Electron Fiddle [1] across OS I get surprising results on macOS:

**macOS**

When you give 2 buttons, macOS reverses the order and shows buttons from left to right:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/900690/213703506-eb4cf500-3132-4ebd-8ff7-88ed43f0ad42.png">

When you give 3 buttons, macOS does partially reverse order and shows buttons from top to bottom:

<img width="289" alt="image" src="https://user-images.githubusercontent.com/900690/213703745-36dfad54-562a-4285-927d-23fb1a67f9e7.png">

You can effectively disable `Escape` key (cancellation) by passing in a `cancelId` of a button that does not exist. 

**Windows**

Windows shows the buttons in order as you give them. You cannot (!) disable `Escape` support. 

<img width="380" alt="image" src="https://user-images.githubusercontent.com/900690/213704075-4d65fb21-bdb0-4adc-9cab-b481f7b27b6a.png">


**Linux**

Linux shows the buttons in order as you give them. You cannot (!) disable `Escape` support.

<img width="319" alt="image" src="https://user-images.githubusercontent.com/900690/213704142-3f007b82-edf1-4338-a23d-5644d33b92d1.png">


[1]

```ts
const { app, BrowserWindow, dialog } = require('electron')

app.whenReady().then(() => {
  const mainWindow = new BrowserWindow({ height: 600, width: 600 })

  // Show an "Open File" dialog and attempt to open
  // the chosen file in our window.

  const res = dialog.showMessageBoxSync({
    title: "Hello World",
    buttons: ["1", "2"],
    //cancelId: -1
  });

  console.log(res);
})
```

**Comment by bpasero** [comment]
I am thinking to make an internal API change to require `cancelId: number` when `buttons` are passed. Today it is optional, but that makes it very hard to do the right thing imho because you cannot rely on order. As such the rule would be:
* button with `cancelId` gets special treatment (i.e is moved to the right place according to OS guidelines)
* all other buttons are shown in their order

This means we cannot disable dialog cancellation, but from my testing that was only possible on macOS anyway.

**Comment by bpasero** [comment]
I am so confused by how Electron/macOS puts the buttons that I also filed https://github.com/electron/electron/issues/36973 to get clarification from them.

**Comment by bpasero** [comment]
Ok I have collected the HIG for all platforms:

**Windows**

Ref: https://learn.microsoft.com/en-us/windows/win32/uxguide/win-dialog-box

> One of the following sets of concise commands: Yes/No, Yes/No/Cancel, [Do it]/Cancel, [Do it]/[Don't do it], [Do it]/[Don't do it]/Cancel.

**macOS**

Ref: https://developer.apple.com/design/human-interface-guidelines/components/presentation/alerts

> Place buttons where people expect. In general, place the button people are most likely to choose on the trailing side in a row of buttons or at the top in a stack of buttons. Always place the default button on the trailing side of a row or at the top of a stack. Cancel buttons are typically on the leading side of a row or at the bottom of a stack.

**Note:** I believe Apple HIG changed here at one point. Earlier versions of macOS seem to have "Cancel" in the middle, e.g.:

![image](https://user-images.githubusercontent.com/900690/213861935-0870bea2-272f-4a04-b2ba-97fa3f61d1d5.png)


**Linux (Gnome)**

Ref: https://developer.gnome.org/hig/patterns/feedback/dialogs.html?highlight=dialog

> Always ensure that the cancel button appears first, before the affirmative button. In left-to-right locales, this is on the left. This button order ensures that users become aware of, and are reminded of, the ability to cancel prior to encountering the affirmative button.

As such, I think here are the bugs on our end:
* **Windows:** seems fine both on native and custom
* **macOS:** seems fine on native because the OS takes care, but on custom the `cancelId` button needs to be at the edge and not between primary and secondary button
* **Linux** seems fine both on native and custom [1]

[1] this is assuming that the Linux HIG puts cancel buttons always to the left of primary buttons. It seems like it when comparing with other dialogs on Linux.

**Comment by bpasero** [comment]
I have added a method that massages dialog options based on HIG:

https://github.com/microsoft/vscode/blob/f861ec8105266783a6bc4e09e7f90ec49a606cb2/src/vs/platform/dialogs/common/dialogs.ts#L431

Since we are entering endgame, I suggest to do further changes next week when we start work on the next milestone.

**Comment by bpasero** [comment]
For archaeological purposes: screenshots of macOS 10.13.6 High Sierra for how dialogs look like in VS Code after this change (and before actually):

![Screen Shot 2023-02-02 at 11 49 07](https://user-images.githubusercontent.com/900690/216305251-368883ca-8f91-4f07-947c-cfa1d38b1c14.png)
![Screen Shot 2023-02-02 at 11 48 49](https://user-images.githubusercontent.com/900690/216305256-3b16c81d-df64-48e5-8a85-b68a6078984c.png)
![Screen Shot 2023-02-02 at 11 48 23](https://user-images.githubusercontent.com/900690/216305262-adcc5e61-a3be-4aad-8db4-cca24a141818.png)

The separation between first and second button is observed irrespective of providing a `cancelId` or not.

**Comment by bpasero** [comment]
For archaeological purposes: screenshots of macOS 10.13.6 High Sierra for how dialogs look like in VS Code after this change (and before actually):

![Screen Shot 2023-02-02 at 11 49 07](https://user-images.githubusercontent.com/900690/216305251-368883ca-8f91-4f07-947c-cfa1d38b1c14.png)
![Screen Shot 2023-02-02 at 11 48 49](https://user-images.githubusercontent.com/900690/216305256-3b16c81d-df64-48e5-8a85-b68a6078984c.png)
![Screen Shot 2023-02-02 at 11 48 23](https://user-images.githubusercontent.com/900690/216305262-adcc5e61-a3be-4aad-8db4-cca24a141818.png)

The separation between first and second button is observed irrespective of providing a `cancelId` or not.
