### ISSUE TITLE
net::ERR_CERT_DATE_INVALID

### ISSUE THREAD

**Issue by vscodenpa** [microsoft/vscode#170470]
```javascript
Error: net::ERR_CERT_DATE_INVALID
at SimpleURLLoaderWrapper.<anonymous> (node:<REDACTED: user-file-path>:105:7047)
at SimpleURLLoaderWrapper.emit (node:events:526:28)
```
[Go to Errors Site](https://vscode-errors.azurewebsites.net/card?ch=e8a3071ea4344d9d48ef8a4df2c097372b0c5161&bH=c7983642-4d0e-1b14-5ebe-ee44d35e73c9)

**Comment by Tyriar** [comment]
This is the top error by machines

**Comment by deepak1556** [comment]
@sandy081 can we log the request url to telemetry that resulted in this failure ? It would help to validate if the SSL certificate has expired.

**Comment by sandy081** [comment]
We can, but it seems like this error is not reported by the request service but instead by `SimpleURLLoaderWrapper` and not sure who is the caller to it.

**Comment by deepak1556** [comment]
`SimpleURLLoaderWrapper` is just native wrapper to the [net](https://github.com/electron/electron/blob/main/docs/api/net.md) module from Electron, the certificate error happens at the network layer hence the stack doesn't point back to `RequestService`. The above error is captured by the `error` event on the request object at https://github.com/microsoft/vscode/blob/e3dca06ca42e21184f1f75f7830ad67be5d96607/src/vs/platform/request/node/requestService.ts#L174

**Comment by rzhao271** [comment]
Closing as stale
