### ISSUE TITLE
Add quick fix provider for new pwsh preview feedback providers

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode#170484]
https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0-preview.1

https://github.com/PowerShell/PowerShell/pull/18252

![image](https://user-images.githubusercontent.com/2193314/210380677-32c9f51f-8550-475d-b424-0df1ed811143.png)

**Comment by Tyriar** [comment]
To verify this you will need to install pwsh preview from the MS Store

**Comment by bhavyaus** [comment]
I can see the suggestions after installing pwsh preview but I don't see the quick fix provider. When I start typing. Do I need to invoke it  with a keyboard shortcut like in the editor?

**Comment by roblourens** [comment]
`verification-needed` stays when `verification-steps-needed` gets added, fyi

**Comment by Tyriar** [comment]
1. Install pwsh preview from MS store
2. Open a terminal and type a command that doesn't exist but is similar to another, eg. `gti`
3. Make sure you get quick fixes for the suggestions output by pwsh
