### ISSUE TITLE
cannot launch code from command line using Git Bash on Windows

### ISSUE THREAD

**Issue by AshleyGrant** [Microsoft/vscode#1704]
`code .` works fine in cmd.exe on Windows 10, but fails with `command not found` when in Git Bash. 

Please add built-in support for launching code from the Git Bash command line. This works with atom out of the box.

**Comment by hoovercj** [comment]
It worked automatically for me on Windows 10 with git bash so I'm curious why it didn't work for you.

One of the options in the installer is to add VS Code to the Windows PATH which should work.

I just did the following though to confirm it working for me:
1. Confirmed the code/bin directory was included in my PATH
2. `code .` worked in git bash
3. Removed code/bin from PATH
4. Restarted git bash
5. `code .` did NOT work in git bash
6. Reinstalled VS Code and selected "Add to PATH"
7. Restarted git bash
8. `code .` worked in git bash

**Comment by AshleyGrant** [comment]
This is a new install of VS Code from last night. I tried your steps (removed code/bin from PATH, reinstalled VS Code w/Add to Path option selected, restarted computer, opened git bash tried typing code<Enter>) to no avail.

Is your VS Code installed to the `Program FIles (x86)` directory? I think that might be part of the problem.
![image](https://cloud.githubusercontent.com/assets/9885322/12052593/8c8193b2-aede-11e5-8fb9-ee52879decd3.png)

**Comment by hoovercj** [comment]
I realize now that I was referring to the powershell tool from the [github installation](https://desktop.github.com/) not `git-bash`. Apologies for wasting your time with that.

I just installed `git-bash` and I had to use `code.cmd` instead of `code`. So try that out

**Comment by AshleyGrant** [comment]
@hoovercj yep. Thus the issue report. I'm not good enough w/bash to create a little script to run. Also, for some reason, creating an alias isn't working for me. 

That all being said, i think this should be part of the default install given how many people use git bash.

**Comment by hoovercj** [comment]
The following shell script ported from `code.cmd` worked for me. You can put it in the bin directory and simply name it `code`. You should then be able to execute `code`, `code .`, or `code path/to/dir/`.

Correct me if I'm wrong, @AshleyGrant, but I think your suggestion was that a script like this be automatically placed in in the bin directory on installation? (I checked and yes, that is what atom does). If so, I'm not a shell expert so I'm not sure if it needs tweaked to be production ready, but it should be an easy change for the team to make if they agree with you.

```
#!/bin/sh
export ATOM_SHELL_INTERNAL_RUN_AS_NODE=1
directory=$(dirname "$0")
"$directory/../Code.exe" "$directory/code.js" $*
```

**Comment by mikemimik** [comment]
I have a solution for this.

In your home directory (/C/Users/{username}) there should be a `.bash_profile` file which will house all your custom bash alias, etc. Git-bash uses `.bash_profile` before it will load `.bashrc` (_I believe_) so if you have *only* a `.bashrc` file (and put the below in it) this might not work. The simple solution would to simply put `alias code="cmd //C code $*"` in the `.bash_profile` file and make sure your `$PATH` has what is below in it, and you should be good to go.

> Side Note: To save myself headache going back and forth between environments where I'm using bash, I do not wish to keep a separate `.bash_profile` on one machine and `.bashrc` files for others, and keep them all up to date. So I have *one* `.bashrc` file which I keep most everything in, and I have my `.bash_profile` source the `.bashrc` file.

In my *home directory* (`C:\Users\{username}`) I have two files: `.bash_profile` _and_ `.bashrc`.

#### Contents of `.bash_profile`
`$ cat ~/.bash_profile`
```Shell
if [ -f ~/.bashrc ]; then . ~/.bashrc; fi
```


#### Contents of `.bashrc`
`$ cat ~/.bashrc`
```Shell
...
alias code="cmd //C code $*"
...
```

#### Contents of `$PATH`
`$ echo $PATH`
```Shell
... :/c/Program Files (x86)/Microsoft VS Code/bin: ...
```

**Comment by Tyriar** [comment]
As mentioned in #2596, the correct place for the fix for this to go is [`resources/common/bin/code.sh`](https://github.com/Microsoft/vscode/blob/master/resources/common/bin/code.sh) and have that put in the `PATH` when elected on installation.

**Comment by joaomoreno** [comment]
Verification by running `code-alpha -v` in the Git Bash. It should print out Code's version.

**Comment by AshleyGrant** [comment]
Thanks for making this happen!

**Comment by jamesqo** [comment]
Awesome, thanks for finally implementing this! Now I won't have to keep running `start code` and closing a new command window every time I want to start it from Git Bash. (TBH this was the only reason why I was still keeping Atom around.) You guys rock!

**Comment by Tyriar** [comment]
:+1:

**Comment by SpacemanPete** [comment]
Hi all, so I know this is closed but I'm unable to launch VSCode from my git bash shell on windows. After attempting `$ code` or  `$ code .`, or `$ code /path/to/folder/` I get the following error:
`/c/Program Files (x86)/Microsoft VS Code/bin/code: line 10: /Code.exe: No such file or directory`

I confirmed that my $PATH variable includes the VSCode directory and the VSCode/bin directory. 

I'm trying to debug the code.sh script by dumping the variables to the console and I can see the VSCODE_PATH variable is not being correctly set, but I figure out why. Can anyone think of what's going haywire here?

Here's the */bin/code.sh* file modified with some additional echo statements:

>#!/usr/bin/env bash
>
>NAME="Code"
>VSCODE_PATH="$(dirname "$(dirname "$(realpath "$0")")")"
>ELECTRON="$VSCODE_PATH/$NAME.exe"
>CLI="$VSCODE_PATH/resources/app/out/cli.js"
>
>echo 0: $0
>echo realpath: $(realpath "$0")
>echo dirname: $(dirname "$(realpath "$0")")
>echo dirname2: $(dirname "$(dirname "$(realpath "$0")")")
>echo NAME: $NAME
>echo VSCODE_PATH: $VSCODE_PATH
>echo ELECTRON: $ELECTRON
>echo CLI: $CLI
>
>ELECTRON_NO_ATTACH_CONSOLE=1 ATOM_SHELL_INTERNAL_RUN_AS_NODE=1 "$ELECTRON" "$CLI" "$@"
>exit $?

and here's the output I'm getting:
`$ code .`
>0: /c/Program Files (x86)/Microsoft VS Code/bin/code
>realpath: /c/Program Files (x86)/Microsoft VS Code/bin/code
>dirname: /c/Program Files (x86)/Microsoft VS Code/bin
>dirname2: .
>NAME: Code
>VSCODE_PATH:
>ELECTRON: /Code.exe
>CLI: /resources/app/out/cli.js
>/c/Program Files (x86)/Microsoft VS Code/bin/code: line 20: /Code.exe: No such file or directory

**Comment by joaomoreno** [comment]
@SpacemanPete thanks for the detailed information, this was really helpful. :+1: 

`dirname2` looks like the point in which it started to go wrong. Maybe we can simply use `..`.

Can you fix up the script line with the following snippet and let me know if it fixes it?

```
VSCODE_PATH="$(realpath "$0")/../.."
```
