### ISSUE TITLE
Red Lines (indicating syntax errors) everywhere

### ISSUE THREAD

**Issue by varunsatish2017** [microsoft/vscode#170425]
Type: <b>Bug</b>

Red lines arbitrarily show up in the code (even though there are genuinely no syntax errors) and sometimes causes compilation errors. 

VS Code version: Code 1.74.2 (Universal) (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin x64 22.2.0
Modes:
Sandboxed: No

<details><summary>Extensions (39)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-django|bat|1.10.0
python-environment-manager|don|1.0.4
python-extension-pack|don|1.7.0
vscode-javac|geo|0.2.45
vscode-pull-request-github|Git|0.56.0
vscode-test-explorer|hbe|2.21.1
discord-vscode|icr|5.8.0
vsc-python-indent|Kev|1.18.0
vscode-python-test-adapter|lit|0.7.1
MagicPython|mag|1.1.0
csharp|ms-|1.25.2
isort|ms-|2022.8.0
python|ms-|2022.20.1
vscode-pylance|ms-|2022.12.20
jupyter|ms-|2022.11.1003412109
jupyter-keymap|ms-|1.0.0
jupyter-renderers|ms-|1.0.12
vscode-jupyter-cell-tags|ms-|0.1.6
vscode-jupyter-slideshow|ms-|0.1.5
cpptools|ms-|1.13.8
test-adapter-converter|ms-|0.1.6
vsliveshare|ms-|1.0.5788
vsliveshare-audio|ms-|0.1.91
vsliveshare-pack|ms-|0.4.0
autodocstring|njp|0.6.1
web-cat-vscode|oli|2.4.0
java|red|1.13.0
python|tht|0.2.3
pdf|tom|1.2.2
python-extended-snippets|tus|0.0.1
intellicode-api-usage-examples|Vis|0.2.6
vscodeintellicode|Vis|1.2.29
vscode-arduino|vsc|0.4.12
vscode-java-debug|vsc|0.47.0
vscode-java-dependency|vsc|0.21.1
vscode-java-pack|vsc|0.25.7
vscode-maven|vsc|0.40.2
vim|vsc|1.24.3
jinja|who|0.0.8

</details>

**Comment by mjbvz** [comment]
What language is this for?

/infoNeeded
