### ISSUE TITLE
API: Ability to Set Log Level of an output channel

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode#170450]
Use case: 

From @dbaeumer 

I actually ran in a comparable problem: I have a setting for LSP clients that let users configure the granularity of the trace level messages. Valid values are for example: `off`, `message`, `verbose`, `json`, ...

![image](https://user-images.githubusercontent.com/10746682/211598100-849a0b9e-feee-4bd2-baf6-54498afe8ee4.png)

Now if a user changes the setting from `off` to `verbose` still nothing will show up in the channel since it log level is still set to debug. So to enable logging now for LSP clients the user needs to:

- change a VS Code setting
- Use a command to enable tracing

It would be nice if I could set the log level programmatically so that I can set it to trace when the user changes the setting.

Proposal is to make following property writeable

```ts
export interface LogOutputChannel extends OutputChannel {

		/**
		 * The current log level of the channel. Defaults to {@link env.logLevel editor log level}.
		 */
		logLevel: LogLevel;
...
...
}
```

**Comment by alexr00** [comment]
+1 for GHPRI.

**Comment by sandy081** [comment]
@alexr00 This might be just a workaround for you right? If #167528 is fixed, you do not need this?

**Comment by sandy081** [comment]
If #167528 is supported, then you do not need the setting itself right? You can ask users to set the log level using the UI provided by VS Code.

**Comment by alexr00** [comment]
@sandy081 that's true. It would just be nice to have to migrate the setting then.

**Comment by dbaeumer** [comment]
@sandy081 I can do that but as a consequence I would need to remove the setting and teach everyone that uses the LSP client that the setting is not supported anymore. So for example @aeschli as to remove the setting from the JSON server (and all the other servers he has) since changing the setting it will have no effect. 

So I am a little afraid about the ripple that this will cause.
