### ISSUE TITLE
VSCode - Insiders Not Starting Pull-Request (PR) Flow When Pushing Feature Branch

### ISSUE THREAD

**Issue by conradwt** [microsoft/vscode#170429]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.75.0-insider
- OS Version: macOS 12.6.2

Steps to Reproduce:

1.   create a feature branch
2.  make changes
3.  stage changes
4.  commit changes

Expected

- Create Pull Request button is displayed in the VSCode - Insiders UI.

Actual 

- Create Pull Request button isn't displayed in the VSCode - Insiders UI.

This is the second time that I'm reporting this issue.  Is there an integration/unit test to make sure that this feature works as expected?

**Comment by lszomoru** [comment]
@alexr00, could you help investigate this issue? Thanks!

**Comment by alexr00** [comment]
> Create Pull Request button is displayed in the VSCode - Insiders UI.

Can you share a screen shot of where you expect this to show?

Can you also set `"githubPullRequests.logLevel": "debug"`, reload the window, reproduce the issue, and share the logs from GitHub Pull Request?

**Comment by conradwt** [comment]
@alexr00 It looks like this issue has resolved itself by updating VSCode - Insiders.  Thus, I'm closing this issue.
