### ISSUE TITLE
Add a terminal tab stop size setting

### ISSUE THREAD

**Issue by probablykasper** [microsoft/vscode#170432]
Type: <b>Bug</b>

When a tab is printed in the terminal, it has a tab size of 8 spaces, regardless of the tab size setting. I'm guessing this would be fixed by setting the `tabStopWidth` option of xterm.js:
https://github.com/xtermjs/xterm.js/blob/fe8981766769c19ab1903dffa19f1a64ad83da13/typings/xterm.d.ts#L221

To reproduce:
1. Update your `Editor: TabSize` setting
2. Run `echo \tx`

VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:26:09.430Z)
OS version: Darwin x64 19.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|10, 10, 7|
|Memory (System)|32.00GB (2.64GB free)|
|Process Argv|--disable-extensions --user-data-dir . --crash-reporter-id 0aabe897-4522-4802-a06b-1a466bbdc1f2|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled<details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1:30587005
282f8724:30602487
iaj6b796:30613358
f6dab269:30613381
fim-prod:30623723

```

</details>

**Comment by meganrogge** [comment]
`Editor: TabSize` is not meant to impact the terminal

**Comment by probablykasper** [comment]
Would it have to be a new setting for Terminal tab size in that case, or a global tab size option?

Would a PR for that get accepted?

**Comment by Tyriar** [comment]
I don't think we would add a setting for this, tab stops in programs aren't used very often as they can differ depending on the terminal emulator.

**Comment by probablykasper** [comment]
In my case, I have a linter that shows my source code when there are lint errors. My tab size is set to 2, but the terminal shows 8. Would love to avoid that mismatch.

iTerm2 allows you to configure it, would be great for vscode could support too.

**Comment by Tyriar** [comment]
@probablykasper can't you configure the tab size in the linter?

**Comment by probablykasper** [comment]
No, it's just showing the source code where it finds a lint issue. To be clear, the linter doesn't deal with code style, it just helpfully shows the code where there's some code issue (like the accessibility warning above).

**Comment by Tyriar** [comment]
Here's the iTerm2 setting:

<img width="969" alt="Screenshot 2023-01-06 at 11 07 08 am" src="https://user-images.githubusercontent.com/2193314/211082146-ed563edd-db32-4833-bd52-29c92a20581c.png">

Terminal.app doesn't let you configure this, neither does Windows Terminal (plus it would probably wouldn't make a difference with conpty).

**Comment by probablykasper** [comment]
Sweet, I opened a PR
