### ISSUE TITLE
Please add an environmental variable signaling that the terminal is being run in VSCode

### ISSUE THREAD

**Issue by zackees** [microsoft/vscode#170430]
I'd like to be able to test that the terminal command is being run in the VSCode terminal.
Please add an environmental variable like VSCODE_IN_TERMINAL=1 when running a terminal in Win/Mac/Linux.

This would fix a current issue where for some reason in Windows the arrow keys are being swallowed and I can't use them to interact with a text based configuration tool, but only when inside the VSCode terminal.

This kind of "escape hatch" would allow me to right code like (IWindows Batch File):

```
if defined VSCODE_IN_TERMINAL(
  REM start command new command terminal so that arrow keys work.
  start cmd /k "activate.bat && idf.py menuconfig"
) else (
  echo Not running in VSCode terminal
  activate.bat && idf.py menuconfig
)
```

**Comment by Tyriar** [comment]
Already exists, see `TERM_PROGRAM` and `TERM_PROGRAM_VERSION`
