### ISSUE TITLE
The old extension folder will not delete after updating

### ISSUE THREAD

**Issue by ZCShou** [Microsoft/vscode#17047]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:12:50.308Z)
- OS Version: Windows_NT ia32 10.0.14971
- Extensions:

|Extension|Author|Version|
|---|---|---|
|vscode-eslint|dbaeumer|1.1.0|
|githistory|donjayamanne|0.1.3|
|cpptools|ms-vscode|0.9.3|
|vscode-icons|robertohuertasm|4.0.6|
|guides|spywhere|0.5.1|

---

Steps to Reproduce:

1. update an extension
2. The old extension folder will not delete
![2016-12-11_215807](https://cloud.githubusercontent.com/assets/8591065/21080555/f946de88-bfec-11e6-988f-791481345bc4.png)

**Comment by joaomoreno** [comment]
It will delete _eventually_.
