### ISSUE TITLE
CMD+Left with selection issue

### ISSUE THREAD

**Issue by wallverb** [Microsoft/vscode#17043]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:06:36.411Z)
- OS Version: Darwin x64 16.1.0

Steps to Reproduce:

1. TS example of code:
```ts
const test = {
    a: 'b',
    c: 'd'
}
```

2. This works ok: put cusror at `3:11` 
![image](https://cloud.githubusercontent.com/assets/1723815/21080044/bdc466d4-bf72-11e6-894f-75c3398f68cd.png)

3. and hit `Cmd+Left`:
![image](https://cloud.githubusercontent.com/assets/1723815/21080046/ca844e52-bf72-11e6-8622-d44ba9fecdb5.png)

4. This does not work: (select text like this)
![image](https://cloud.githubusercontent.com/assets/1723815/21080052/f898494c-bf72-11e6-8a2b-7d91a231ab5b.png)

5. Holding `Shift` hit `Cmd+Left`, here is the result:
![image](https://cloud.githubusercontent.com/assets/1723815/21080058/224d59d0-bf73-11e6-9a4c-cdee8b790c9a.png)

Should be (this is result from Sublime, works the same in Atom):
![image](https://cloud.githubusercontent.com/assets/1723815/21080060/335fefda-bf73-11e6-98b1-4ad973133cfd.png)

Looks like it might have change recently because I'm pretty sure I was using this combination in the past (but I might be wrong)

**Comment by wallverb** [comment]
Similar to https://github.com/Microsoft/vscode/issues/16990 except expectation is different :D

**Comment by alexandrudima** [comment]
Let's track in #17011
