### ISSUE TITLE
MacOs - C# and Unity 5.5 Intellisense doesn't work

### ISSUE THREAD

**Issue by rslnautic** [Microsoft/vscode#17049]
- VSCode Version: 1.7.2
- OS Version: MacOs 10.12.1 
I use zsh. Not bash.

I can't use intellisense with C# and unity 5.5. I've tried hard but I can't solve it. Please Help!

___________________________________________________________________
Starting OmniSharp server at 12/11/2016, 6:41:17 PM
    Target: /Users/rsl/Desktop/Jugs/Jugs.sln

OmniSharp server started wth Mono
    Path: /Users/rsl/.vscode/extensions/ms-vscode.csharp-1.5.3/bin/run
    PID: 881

OmniSharp: -s /Users/rsl/Desktop/Jugs/Jugs.sln --hostPID 865 --stdio DotNet:enablePackageRestore=false --encoding utf-8
﻿﻿{"Event":"log","Body":{"LogLevel":"INFORMATION","Name":"OmniSharp.Startup","Message":"Omnisharp server running using Stdio at location '/Users/rsl/Desktop/Jugs' on host 865."},"Seq":1,"Type":"event"}
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Initializing in /Users/rsl/Desktop/Jugs
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Auto package restore: False
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Update workspace context
[INFORMATION:OmniSharp.DotNet.DotNetProjectSystem] Resolving projects references
[INFORMATION:OmniSharp#MSBuild] Detecting projects in '/Users/rsl/Desktop/Jugs/Jugs.sln'.
[INFORMATION:OmniSharp#MSBuild] Loading project from '/Users/rsl/Desktop/Jugs/Assembly-CSharp.csproj'.
[WARNING:OmniSharp#ProjectFileInfo] Couldn't locate Mono, TargetFrameworkRootPath not specified
[INFORMATION:OmniSharp#ProjectFileInfo] Using tools version: 15.0
[ERROR:OmniSharp#ProjectFileInfo] The reference assemblies for framework ".NETFramework,Version=v3.5" were not found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget your application to a version of the framework for which you have the SDK or Targeting Pack installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC) and will be used in place of reference assemblies. Therefore your assembly may not be correctly targeted for the framework you intend.
[WARNING:OmniSharp#MSBuild] Failed to process project file '/Users/rsl/Desktop/Jugs/Assembly-CSharp.csproj'.
/Users/rsl/Desktop/Jugs/Assembly-CSharp.csproj

[INFORMATION:OmniSharp.Startup] Configuration finished.

**Comment by Mkayxx** [comment]
In order to use the c# unity intellisense you have to open the file folder where your scripts are. This should work.

**Comment by alexandrudima** [comment]
Moved to OmniSharp/omnisharp-vscode#1031

**Comment by MichaelHazani** [comment]
@Mkayxx I know this issue is closed but I'm experiencing an identical one. Do you mean I should open it in VSCode? Tried opening the "Assets" folder and navigating to my scripts folder from there - didn't help.

If you worked through this issue, would you mind explaining how you did it?
Thanks!

**Comment by Mkayxx** [comment]
Try everything this site tells you https://code.visualstudio.com/Docs/runtimes/unity. 
What I mean by opening the file folder.if your unity game project is called 2d platformer meow,try finding the 2d platformer folder and open it and intelligence should work,also you have to download some of the extensions listed at the link.

**Comment by MichaelHazani** [comment]
Thanks! I followed a suggestion elsewhere and installed the newest version
of Mono, which solved the problem for me.
