### ISSUE TITLE
In-project search and in-file search should have different highlighting colors

### ISSUE THREAD

**Issue by hun1ahpu** [Microsoft/vscode#17046]
Repro steps:
1. Open in-project search (ctrl+shift+f) and search for a letter 'a'
2. Open any text file and search (ctrl+f) for a letter 'b' in it

Expected: i can distinguish 2 search results
Actual: both search results are highlighted with the same color.

Screenshot:
![image](https://cloud.githubusercontent.com/assets/4397796/21080425/431618d2-bfaf-11e6-8154-c1d0dd9d03c0.png)

**Comment by sandy081** [comment]
Assigning this to @bgashler1 to get UX input for color.

**Comment by hun1ahpu** [comment]
Same for the scroll bar.

**Comment by stevencl** [comment]
Looks like this has been fixed.
