### ISSUE TITLE
TypeScript: variable "namespace" highlight issue

### ISSUE THREAD

**Issue by unional** [Microsoft/vscode#17053]
- VSCode Version: 1.7.2
- OS Version: Windows 2012 R2

```ts
let namespace;
namespace = `${"a"}`;

let x = 1
```
![image](https://cloud.githubusercontent.com/assets/3254987/21084736/15c59980-bfbd-11e6-9765-bec93a46ac1e.png)

**Comment by aeschli** [comment]
This issue was moved to Microsoft/TypeScript-TmLanguage#380
