### ISSUE TITLE
Python extensions do not work after updating to the latest version of VS Code Insiders

### ISSUE THREAD

**Issue by WitherZuo** [microsoft/vscode#170558]
Does this issue occur when all extensions are disabled?: No

- **VS Code Version**: 1.75.0-insider (system setup) (4acf2d9b46b75748ae687cf3b2952a0799679873)  
- **OS Version**: Windows 11 Pro Insider Preview (Dev Channel) Build 25267.1000

**Steps to Reproduce:**
1. Install the latest version of VS Code Insiders
2. Install Python extension (or official extension pack) and switch to Pre-Release
3. Extension will try activating automatically, and stuck at `Python extension loading...`
4. Open Developer Tool, it will show `Activating extension 'ms-python.python' failed: this.a.sendEventData is not a function.` and **all Python-related extension can not activate correctly**.

**Other attempts:**
1. Latest version of VS Code Insiders + Python extension ( latest Pre-Release): Failed to load.
2. Latest version of VS Code Insiders + Python extension ( latest Release): Failed to load.
3. Latest version of VS Code + Python extension ( latest Release): OK.
4. Latest version of VS Code + Python extension ( latest Pre-Release): OK.

**Screenshot:**
![2023-01-04 202315](https://user-images.githubusercontent.com/25317916/210554464-22e6105a-492e-4e45-9153-58146af194c6.png)

**Comment by marcushallett** [comment]
Can confirm this occurs on my machine. Parallel to issue microsoft/vscode-python#20456 on the Python extension's repo.

**Comment by piero2c** [comment]
I am having the same issue, both in local and remote sessions.

OS Version: Windows 11 Enterprise Build 22621

**Comment by Syntrice** [comment]
Can confirm this occurs on my machine also.

**Comment by lxe** [comment]
I'm still seeing this

```
Version: 1.75.0-insider (system setup)
Commit: 727d2d32aea02baf7d13fa38787e8ed64dd858d0
Date: 2023-01-06T05:21:40.528Z
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: Yes
```
