### ISSUE TITLE
Python 3.6 Syntax highlighting of imports no longer works.

### ISSUE THREAD

**Issue by Rumbelows** [microsoft/vscode#170517]
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version:  1.74.2
- OS Version:  windows 10

Steps to Reproduce:

1.  Open VScode with python 3.6.x as python interpreter

When using python 3.6 the highlighting of imports does not occur leaving them as white text strings. This also impacts all instances of imported elements.

**Comment by jlotthammer** [comment]
This is also happening to me after updating on Ubuntu 18.04 LTS - I believe it's because the interpreter is not being discovered and set?

**Comment by bhavyaus** [comment]
This appears to be an issue with the [vscode-python](https://github.com/microsoft/vscode-python). Please use the `Python: Report issue` command to report this issue. 
cc: @karrtikr 

Related: https://github.com/microsoft/vscode/issues/170592
