### ISSUE TITLE
Graphic glitch after upgrading to MacOs Siera

### ISSUE THREAD

**Issue by Mkayxx** [Microsoft/vscode#17050]
- VSCode Version: Code 1.7.1 (02611b40b24c9df2726ad8b33f5ef5f67ac30b44, 2016-11-03T13:46:00.226Z)
- OS Version: Darwin x64 16.1.0
- Extensions:

|Extension|Author|Version|
|---|---|---|
|rainbow-brackets|2gua|0.0.6|
|bracket-pair-colorizer|CoenraadS|0.2.1|
|material-icon-theme|PKief|1.1.4|
|indenticator|SirTori|0.2.1|
|unity-tools|Tobiah|0.1.9|
|unity-debug|Unity|1.1.0|
|unity-snippets|YclepticStudios|0.1.2|
|TabOut|albert|0.1.4|
|one-monokai|azemoh|0.2.3|
|theme-onedark|azemoh|0.4.0|
|vscode-icontheme-nomo-dark|be5invis|1.2.1|
|theme-dracula|dracula-theme|1.2.5|
|extension-leaderboard|formulahendry|0.0.2|
|csharpextensions|jchannon|1.1.0|
|theme-material-theme|jprestidge|1.0.1|
|csharp|ms-vscode|1.5.3|
|mono-debug|ms-vscode|0.12.0|
|vscode-icons|robertohuertasm|4.0.6|
|theme-obsidian|rprouse|0.2.0|
|Spell|seanmcbreen|0.9.1|

---

Steps to Reproduce:

1.There are no steps to reproduce this problem.
After i installed MacOsSiera there's a weird graphical glitch in the background.
I tried re-installing but the issue didn't got fixed.
![screen shot 2016-12-11 at 9 28 41 pm](https://cloud.githubusercontent.com/assets/23614722/21082667/db69c712-bfe8-11e6-8934-3004df4807ee.png)

**Comment by Mkayxx** [comment]
The only solution i found is my lauching vs code with code --disable-gpu.
Please fix the bug ,Thank you.

**Comment by bpasero** [comment]
#12473
