### ISSUE TITLE
Should `vscode.workspace.fs.stat` API  return all content providered by User-defined FileSystem provider

### ISSUE THREAD

**Issue by yiliang114** [microsoft/vscode#170539]
I use `vscode.FileSystemProvider` interface when I develop a VS Code Extension. I have implemented the `stat` function, which inherits `vscode.FileStat` and contains some additional attributes. But when I used  `vscode.workspace.fs.stat`  to try to get the extra properties I injected, I found that I didn't get them.

Should `vscode.workspace.fs.stat` API  return all content providered by User-defined FileSystem provider Instead of returning only the following attributes? 

![image](https://user-images.githubusercontent.com/11473889/210509248-7b315d46-75ae-4c77-a109-84fe2a785d30.png)

[extHostFileSystemConsumer Stat](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostFileSystemConsumer.ts#L42)

**Comment by jrieken** [comment]
> Should vscode.workspace.fs.stat API return all content providered by User-defined FileSystem provider Instead of returning only the following attributes?

We don't do that because we want the API to work as advertised - meaning neither more nor less than spec'd. Otherwise (other) extensions would become dependent on a specific implement extension of another extensions and that would defeat the purpose of the API in the first place
