### ISSUE TITLE
VS code hangs when a folder change occurs from the opened folder

### ISSUE THREAD

**Issue by adarshjohny** [Microsoft/vscode#17057]
- VSCode Version: Code - Insiders 1.8.0-insider (40243d1e01f426f54670f3dbaa6b77d18469310d, 2016-12-09T12:12:50.308Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions:

|Extension|Author|Version|
|---|---|---|
|typescript-react-snippets|abotteram|0.1.9|
|react-toolbox-snippets|alechp|0.12.0|
|project-manager|alefragnani|0.12.2|
|copy-relative-path|alexdima|0.0.1|
|regex|chrmarti|0.0.6|
|vscode-eslint|dbaeumer|1.0.8|
|githistory|donjayamanne|0.1.0|
|vscode-generate-getter-setter|DSKWRK|0.4.1|
|vscode-babel-coloring|dzannotti|0.0.4|
|tstools|iBotMedia|1.1.3|
|path-autocomplete|ionutvmi|1.1.0|
|redux-snippets|jameshrisho|0.0.1|
|Angular1|johnpapa|0.1.16|
|web-browser|masonicboom|0.0.1|
|PowerShell|ms-vscode|0.7.2|
|debugger-for-chrome|msjsdiag|2.2.2|
|autoimport|pmneo|1.0.7|
|view-in-browser|qinjia|0.0.3|
|typescript-hero|rbbit|0.10.0|
|vscode-icons|robertohuertasm|4.0.1|
|Spell|seanmcbreen|0.8.6|
|code-settings-sync|Shan|2.3.8|
|ReactSnippetsStandard|TimonVS|1.0.3|
|react-redux-es6-snippets|timothymclane|1.0.5|
|jsx|TwentyChung|0.0.1|
|babelrc|waderyan|1.0.0|
|ReactSnippets|xabikos|1.2.0|

---

Steps to Reproduce:

1.Open the project containing folder in Vs code
2.Go to the folder through file manager
3.Add a new folder containing files to the Opened folder(opened in Vs code)
4.Then Vs code is not responsive

**Comment by bpasero** [comment]
I wonder if this issue is being caused by an installed extension. Can you try to run VS Code without extensions? From the command line (NOT the integrated terminal in Code), execute: `code --disable-extensions` and try your steps again to see if it reproduces. If you see it is an issue with the extension, please file it against the extension repository itself.

**Comment by bpasero** [comment]
@adarshjohny ping

**Comment by adarshjohny** [comment]
Thanks @bpasero after I had disabled all the extensions there is no prblems.
Thanks for the advice.
